APM:Libraries: libraries/AC_PID/examples/AC_PID_test/AC_PID_test.cpp File Reference
AC_PID_test.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AC_PID/AC_PID.h>
#include <AC_PID/AC_HELI_PID.h>
#include <RC_Channel/RC_Channel.h>
#include <RC_Channel/RC_Channels_VarInfo.h>
Classes
class RC_Channel_PIDTest
class RC_Channels_PIDTest
Macros
#define RC_CHANNELS_SUBCLASS RC_Channels_PIDTest
#define RC_CHANNEL_SUBCLASS RC_Channel_PIDTest
#define TEST_P 1.0f
#define TEST_I 0.01f
#define TEST_D 0.2f
#define TEST_IMAX 10
#define TEST_FILTER 5.0f
#define TEST_DT 0.01f
#define TEST_INITIAL_FF 0.0f
Functions
void setup ()
void loop ()
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
RC_Channels_PIDTest _rc
Macro Definition Documentation
RC_CHANNEL_SUBCLASS
#define RC_CHANNEL_SUBCLASS RC_Channel_PIDTest
Definition at line 40 of file AC_PID_test.cpp.
RC_CHANNELS_SUBCLASS
#define RC_CHANNELS_SUBCLASS RC_Channels_PIDTest
Definition at line 39 of file AC_PID_test.cpp.
TEST_D
#define TEST_D 0.2f
Definition at line 49 of file AC_PID_test.cpp.
Referenced by loop().
TEST_DT
#define TEST_DT 0.01f
Definition at line 52 of file AC_PID_test.cpp.
Referenced by loop().
TEST_FILTER
#define TEST_FILTER 5.0f
Definition at line 51 of file AC_PID_test.cpp.
Referenced by loop().
TEST_I
#define TEST_I 0.01f
Definition at line 48 of file AC_PID_test.cpp.
Referenced by loop().
TEST_IMAX
#define TEST_IMAX 10
Definition at line 50 of file AC_PID_test.cpp.
Referenced by loop().
TEST_INITIAL_FF
#define TEST_INITIAL_FF 0.0f
Definition at line 53 of file AC_PID_test.cpp.
TEST_P
#define TEST_P 1.0f
Definition at line 47 of file AC_PID_test.cpp.
Referenced by loop().
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
loop()
void loop (void)
Definition at line 70 of file AC_PID_test.cpp.
Referenced by luaV_finishget(), luaV_finishset(), AP_SmartRTL::remove_points_by_loops(), srxl_channels_get_v1v2(), and AP_RCProtocol_SRXL::srxl_channels_get_v1v2().
setup()
void setup (void)
Definition at line 56 of file AC_PID_test.cpp.
Variable Documentation
_rc
RC_Channels_PIDTest _rc
Definition at line 44 of file AC_PID_test.cpp.
Referenced by RC_Channels::clear_overrides(), RC_Channels::get_override_mask(), RC_Channels::has_active_overrides(), and RC_Channels::set_override().
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
The data_array uses 3 elements to perform the data transaction. The first element is a data byte that provides to FPGA's hardware the transaction type that will be realized inside the SPI module. Where:
╔═════════╦═════════╦══════════╦══════════╦══════════╦══════════╦══════════╦═══════════╗ ║ MSB ║ ║ ║ ║ ║ ║ ║ LSB ║ ╠═════════╬═════════╬══════════╬══════════╬══════════╬══════════╬══════════╬═══════════╣ ║ wr_addr ║ rd_addr ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ ╚═════════╩═════════╩══════════╩══════════╩══════════╩══════════╩══════════╩═══════════╝
╔═══════════╦═════════╦═════════╗ ║ Register ║ wr_addr ║ rd_addr ║ ╠═══════════╬═════════╬═════════╣ ║ write ║ 0 ║ X ║ ╠═══════════╬═════════╬═════════╣ ║ read ║ X ║ 0 ║ ╠═══════════╬═════════╬═════════╣ ║ status ║ 1 ║ 1 ║ ╚═══════════╩═════════╩═════════╝
So, to perform a write transaction in the SPI module it's necessary to send. E.g: 0b 01xx xxxx And to a read transaction.. 0b 10xx xxxx
The PWM frequency is always even and the duty cycle percentage odd. E.g: pwm_01: Address 0x0000 frequency : Address 0x0001 duty cycle pwm_02: Address 0x0002 frequency Eg of allowed values: // PWM channel in 100Hz uint16_t freq = 100;
// duty cycle in (1823/65535) that's 2.78% of 100Hz: // the signal will hold high until 278 usec uint16_t duty = 1823;
Definition at line 21 of file AC_PID_test.cpp.
Referenced by loop(), and setup().