APM:Libraries: libraries/AP_IOMCU/iofirmware/analog.h File Reference
analog.h File Reference
#include <stdint.h>
Functions
void adc_init (void)
uint16_t adc_vservo (void)
uint16_t adc_vrssi (void)
void adc_sample_channels (void)
void adc_enable_vrssi (void)
void adc_disable_vrssi (void)
Function Documentation
adc_disable_vrssi()
void adc_disable_vrssi (void)
Definition at line 89 of file analog.cpp.
Referenced by AP_IOMCU_FW::handle_code_write().
adc_enable_vrssi()
void adc_enable_vrssi (void)
Definition at line 81 of file analog.cpp.
Referenced by AP_IOMCU_FW::handle_code_write().
adc_init()
void adc_init (void)
Definition at line 50 of file analog.cpp.
Referenced by AP_IOMCU_FW::init().
adc_sample_channels()
void adc_sample_channels (void)
Definition at line 97 of file analog.cpp.
Referenced by AP_IOMCU_FW::page_status_update().
adc_vrssi()
uint16_t adc_vrssi (void)
Definition at line 122 of file analog.cpp.
Referenced by AP_IOMCU_FW::page_status_update().
adc_vservo()
uint16_t adc_vservo (void)
Definition at line 114 of file analog.cpp.
Referenced by AP_IOMCU_FW::page_status_update().