APM:Libraries: libraries/AP_IOMCU/iofirmware/analog.cpp File Reference
analog.cpp File Reference
#include "ch.h"
#include "hal.h"
#include "analog.h"
Macros
#define STM32_ADC1_NUMBER 18
#define STM32_ADC1_HANDLER Vector88
Functions
void Vector88 ()
void adc_init (void)
void adc_enable_vrssi (void)
void adc_disable_vrssi (void)
void adc_sample_channels ()
uint16_t adc_vservo (void)
uint16_t adc_vrssi (void)
static void adc_read_sample ()
OSAL_IRQ_HANDLER (STM32_ADC1_HANDLER)
Variables
const uint32_t VSERVO_CHANNEL = ADC_SQR3_SQ1_N(ADC_CHANNEL_IN4)
const uint32_t VRSSI_CHANNEL = ADC_SQR3_SQ1_N(ADC_CHANNEL_IN5)
static uint16_t vrssi_val = 0xFFFF
static uint16_t vservo_val = 0xFFFF
static bool sample_vrssi_enable = true
static bool sampling_vservo = true
Macro Definition Documentation
STM32_ADC1_HANDLER
#define STM32_ADC1_HANDLER Vector88
Definition at line 37 of file analog.cpp.
STM32_ADC1_NUMBER
#define STM32_ADC1_NUMBER 18
Definition at line 36 of file analog.cpp.
Referenced by adc_init().
Function Documentation
adc_disable_vrssi()
void adc_disable_vrssi (void)
Definition at line 89 of file analog.cpp.
Referenced by AP_IOMCU_FW::handle_code_write().
adc_enable_vrssi()
void adc_enable_vrssi (void)
Definition at line 81 of file analog.cpp.
Referenced by AP_IOMCU_FW::handle_code_write().
adc_init()
void adc_init (void)
Definition at line 50 of file analog.cpp.
Referenced by AP_IOMCU_FW::init().
adc_read_sample()
static void adc_read_sample () static
Definition at line 127 of file analog.cpp.
Referenced by OSAL_IRQ_HANDLER().
adc_sample_channels()
void adc_sample_channels (void)
Definition at line 97 of file analog.cpp.
Referenced by AP_IOMCU_FW::page_status_update().
adc_vrssi()
uint16_t adc_vrssi (void)
Definition at line 122 of file analog.cpp.
Referenced by AP_IOMCU_FW::page_status_update().
adc_vservo()
uint16_t adc_vservo (void)
Definition at line 114 of file analog.cpp.
Referenced by AP_IOMCU_FW::page_status_update().
OSAL_IRQ_HANDLER()
OSAL_IRQ_HANDLER (STM32_ADC1_HANDLER)
Definition at line 149 of file analog.cpp.
Vector88()
void Vector88 () extern
Variable Documentation
sample_vrssi_enable
bool sample_vrssi_enable = true static
Definition at line 44 of file analog.cpp.
Referenced by adc_disable_vrssi(), adc_enable_vrssi(), and adc_read_sample().
sampling_vservo
bool sampling_vservo = true static
Definition at line 45 of file analog.cpp.
Referenced by adc_read_sample().
VRSSI_CHANNEL
const uint32_t VRSSI_CHANNEL = ADC_SQR3_SQ1_N(ADC_CHANNEL_IN5)
Definition at line 40 of file analog.cpp.
Referenced by adc_read_sample().
vrssi_val
uint16_t vrssi_val = 0xFFFF static
Definition at line 42 of file analog.cpp.
Referenced by adc_read_sample(), and adc_vrssi().
VSERVO_CHANNEL
const uint32_t VSERVO_CHANNEL = ADC_SQR3_SQ1_N(ADC_CHANNEL_IN4)
Definition at line 39 of file analog.cpp.
Referenced by adc_read_sample().
vservo_val
uint16_t vservo_val = 0xFFFF static
Definition at line 43 of file analog.cpp.
Referenced by adc_read_sample(), and adc_vservo().