APM:Libraries: libraries/AP_Math/AP_Math.cpp File Reference
AP_Math.cpp File Reference
#include "AP_Math.h"
#include <float.h>
#include <AP_InternalError/AP_InternalError.h>
Macros
#define AP_MATH_FILL_NANF_USE_MEMCPY (CONFIG_HAL_BOARD == HAL_BOARD_SITL)
Functions
template<typename Arithmetic1 , typename Arithmetic2 >
std::enable_if< std::is_integral< typenamestd::common_type< Arithmetic1, Arithmetic2 >::type >::value, bool >::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
template<typename Arithmetic1 , typename Arithmetic2 >
std::enable_if< std::is_floating_point< typenamestd::common_type< Arithmetic1, Arithmetic2 >::type >::value, bool >::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
template bool is_equal< int > (const int v_1, const int v_2)
template bool is_equal< short > (const short v_1, const short v_2)
template bool is_equal< long > (const long v_1, const long v_2)
template bool is_equal< float > (const float v_1, const float v_2)
template bool is_equal< double > (const double v_1, const double v_2)
template<typename T >
float safe_asin (const T v)
template float safe_asin< int > (const int v)
template float safe_asin< short > (const short v)
template float safe_asin< float > (const float v)
template float safe_asin< double > (const double v)
template<typename T >
float safe_sqrt (const T v)
template float safe_sqrt< int > (const int v)
template float safe_sqrt< short > (const short v)
template float safe_sqrt< float > (const float v)
template float safe_sqrt< double > (const double v)
static void swap_float (float &f1, float &f2)
float linear_interpolate (float low_output, float high_output, float var_value, float var_low, float var_high)
float expo_curve (float alpha, float x)
float throttle_curve (float thr_mid, float alpha, float thr_in)
template<typename T >
T wrap_180 (const T angle)
template<typename T >
T wrap_180_cd (const T angle)
template int wrap_180< int > (const int angle)
template short wrap_180< short > (const short angle)
template float wrap_180< float > (const float angle)
template int wrap_180_cd< int > (const int angle)
template long wrap_180_cd< long > (const long angle)
template short wrap_180_cd< short > (const short angle)
template float wrap_180_cd< float > (const float angle)
float wrap_360 (const float angle)
int wrap_360 (const int angle)
float wrap_360_cd (const float angle)
int wrap_360_cd (const int angle)
long wrap_360_cd (const long angle)
ftype wrap_PI (const ftype radian)
ftype wrap_2PI (const ftype radian)
template<typename T >
T constrain_value_line (const T amt, const T low, const T high, uint32_t line)
template float constrain_value_line< float > (const float amt, const float low, const float high, uint32_t line)
template double constrain_value_line< double > (const double amt, const double low, const double high, uint32_t line)
template<typename T >
T constrain_value (const T amt, const T low, const T high)
template int constrain_value< int > (const int amt, const int low, const int high)
template unsigned int constrain_value< unsigned int > (const unsigned int amt, const unsigned int low, const unsigned int high)
template long constrain_value< long > (const long amt, const long low, const long high)
template unsigned long constrain_value< unsigned long > (const unsigned long amt, const unsigned long low, const unsigned long high)
template long long constrain_value< long long > (const long long amt, const long long low, const long long high)
template unsigned long long constrain_value< unsigned long long > (const unsigned long long amt, const unsigned long long low, const unsigned long long high)
template short constrain_value< short > (const short amt, const short low, const short high)
template unsigned short constrain_value< unsigned short > (const unsigned short amt, const unsigned short low, const unsigned short high)
template float constrain_value< float > (const float amt, const float low, const float high)
template double constrain_value< double > (const double amt, const double low, const double high)
uint16_t get_random16 (void)
bool rotation_equal (enum Rotation r1, enum Rotation r2)
Vector3F get_vel_correction_for_sensor_offset (const Vector3F &sensor_offset_bf, const Matrix3F &rot_ef_to_bf, const Vector3F &angular_rate)
float calc_lowpass_alpha_dt (float dt, float cutoff_freq)
void fill_nanf (float *f, uint16_t count)
void fill_nanf (double *f, uint16_t count)
float fixed2float (const uint16_t input, const uint8_t fractional_bits)
uint16_t float2fixed (const float input, const uint8_t fractional_bits)
float fixedwing_turn_rate (float bank_angle_deg, float airspeed)
float degF_to_Kelvin (float temp_f)
int16_t float_to_int16 (const float v)
int32_t float_to_int32 (const float v)
uint16_t float_to_uint16 (const float v)
uint32_t float_to_uint32 (const float v)
uint32_t double_to_uint32 (const double v)
int32_t double_to_int32 (const double v)
int32_t float_to_int32_le (const float &value)
float int32_to_float_le (const uint32_t &value)
double uint64_to_double_le (const uint64_t &value)
Macro Definition Documentation
AP_MATH_FILL_NANF_USE_MEMCPY
#define AP_MATH_FILL_NANF_USE_MEMCPY (CONFIG_HAL_BOARD == HAL_BOARD_SITL)
Definition at line 419 of file AP_Math.cpp.
Function Documentation
calc_lowpass_alpha_dt()
float calc_lowpass_alpha_dt (float dt, float cutoff_freq)
Definition at line 402 of file AP_Math.cpp.
Referenced by AC_PID::get_filt_D_alpha(), AC_PID_2D::get_filt_D_alpha(), AC_PID_Basic::get_filt_D_alpha(), AC_PID::get_filt_E_alpha(), AC_PID_2D::get_filt_E_alpha(), AC_PID_Basic::get_filt_E_alpha(), AC_PID::get_filt_T_alpha(), LowPassHelper::print_transfer_function(), TEST(), and AP_DAL_InertialSensor::update_filtered().
constrain_value()
template<typename T > T constrain_value (const T amt, const T low, const T high)
Definition at line 294 of file AP_Math.cpp.
Referenced by constrain_double(), constrain_int16(), constrain_int32(), constrain_int64(), constrain_uint16(), constrain_uint32(), constrain_uint64(), TEST(), and TEST().
constrain_value< double >()
template double constrain_value< double > (const double amt, const double low, const double high)
constrain_value< float >()
template float constrain_value< float > (const float amt, const float low, const float high)
constrain_value< int >()
template int constrain_value< int > (const int amt, const int low, const int high)
constrain_value< long >()
template long constrain_value< long > (const long amt, const long low, const long high)
constrain_value< long long >()
template long long constrain_value< long long > (const long long amt, const long long low, const long long high)
constrain_value< short >()
template short constrain_value< short > (const short amt, const short low, const short high)
constrain_value< unsigned int >()
template unsigned int constrain_value< unsigned int > (const unsigned int amt, const unsigned int low, const unsigned int high)
constrain_value< unsigned long >()
template unsigned long constrain_value< unsigned long > (const unsigned long amt, const unsigned long low, const unsigned long high)
constrain_value< unsigned long long >()
template unsigned long long constrain_value< unsigned long long > (const unsigned long long amt, const unsigned long long low, const unsigned long long high)
constrain_value< unsigned short >()
template unsigned short constrain_value< unsigned short > (const unsigned short amt, const unsigned short low, const unsigned short high)
constrain_value_line()
template<typename T > T constrain_value_line (const T amt, const T low, const T high, uint32_t line)
Definition at line 267 of file AP_Math.cpp.
constrain_value_line< double >()
template double constrain_value_line< double > (const double amt, const double low, const double high, uint32_t line)
constrain_value_line< float >()
template float constrain_value_line< float > (const float amt, const float low, const float high, uint32_t line)
degF_to_Kelvin()
float degF_to_Kelvin (float temp_f)
Definition at line 494 of file AP_Math.cpp.
double_to_int32()
int32_t double_to_int32 (const double v)
Definition at line 527 of file AP_Math.cpp.
double_to_uint32()
uint32_t double_to_uint32 (const double v)
Definition at line 522 of file AP_Math.cpp.
expo_curve()
float expo_curve (float alpha, float x)
Definition at line 121 of file AP_Math.cpp.
Referenced by throttle_curve().
fill_nanf() [1/2]
void fill_nanf (double * f, uint16_t count)
Definition at line 447 of file AP_Math.cpp.
fill_nanf() [2/2]
void fill_nanf (float * f, uint16_t count)
Definition at line 424 of file AP_Math.cpp.
Referenced by fill_nanf_stack(), NavEKF_core_common::fill_scratch_variables(), and fill_stack_nan().
fixed2float()
float fixed2float (const uint16_t input, const uint8_t fractional_bits)
Definition at line 472 of file AP_Math.cpp.
Referenced by TEST().
fixedwing_turn_rate()
float fixedwing_turn_rate (float bank_angle_deg, float airspeed)
Definition at line 487 of file AP_Math.cpp.
Referenced by TEST().
float2fixed()
uint16_t float2fixed (const float input, const uint8_t fractional_bits)
Definition at line 478 of file AP_Math.cpp.
Referenced by TEST().
float_to_int16()
int16_t float_to_int16 (const float v)
Definition at line 502 of file AP_Math.cpp.
Referenced by AP_Frsky_Backend::calc_gps_position().
float_to_int32()
int32_t float_to_int32 (const float v)
Definition at line 507 of file AP_Math.cpp.
Referenced by SITL::IntelligentEnergy24::update_send().
float_to_int32_le()
int32_t float_to_int32_le (const float & value)
Definition at line 533 of file AP_Math.cpp.
float_to_uint16()
uint16_t float_to_uint16 (const float v)
Definition at line 512 of file AP_Math.cpp.
Referenced by AP_Frsky_Backend::calc_gps_position(), and AP_Frsky_Backend::calc_nav_alt().
float_to_uint32()
uint32_t float_to_uint32 (const float v)
Definition at line 517 of file AP_Math.cpp.
Referenced by SITL::IntelligentEnergy24::update_send().
get_random16()
uint16_t get_random16 (void)
Definition at line 332 of file AP_Math.cpp.
Referenced by apfs_tmpfile(), HALSITL::Util::get_random_vals(), AP_IOMCU_FW::heater_update(), FlashTest::loop(), rand_num(), and TEST().
get_vel_correction_for_sensor_offset()
Vector3F get_vel_correction_for_sensor_offset (const Vector3F & sensor_offset_bf, const Matrix3F & rot_ef_to_bf, const Vector3F & angular_rate)
Definition at line 388 of file AP_Math.cpp.
Referenced by NavEKF3_core::CorrectExtNavVelForSensorOffset(), NavEKF2_core::CorrectExtNavVelForSensorOffset(), and TEST().
int32_to_float_le()
float int32_to_float_le (const uint32_t & value)
Definition at line 545 of file AP_Math.cpp.
Referenced by be32tofloat_ptr().
is_equal() [1/2]
template<typename Arithmetic1 , typename Arithmetic2 > std::enable_if< std::is_integral< typenamestd::common_type< Arithmetic1, Arithmetic2 >::type >::value, bool >::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
Definition at line 14 of file AP_Math.cpp.
Referenced by AP_Baro_Backend::_copy_to_frontend(), AP_GeodesicGrid::_from_neighbor_umbrella(), GCS_MAVLINK::_handle_command_preflight_calibration(), AP_GPS_NMEA::_term_complete(), AP_InertialSensor::accel_calibrated_ok_all(), AP_MotorsHeli::arming_checks(), AP_TempCalibration::calculate_calibration(), AP_MotorsHeli_Dual::calculate_scalars(), AP_MotorsHeli_Quad::calculate_scalars(), AP_MotorsHeli_Single::calculate_scalars(), AC_Circle::check_param_change(), AP_Param::convert_old_parameter(), AP_OADatabase::database_item_refresh(), AC_AutoTune_Heli::do_gcs_announcements(), AC_AutoTune_Heli::do_post_test_gcs_announcements(), AC_AutoTune_Heli::dwell_test_init(), AC_AutoTune_Heli::dwell_test_run(), AP_MSP_Telem_DJI::get_rssi(), AP_Camera::handle_command(), GCS_MAVLINK::handle_command_do_set_home(), GCS_MAVLINK::handle_command_int_packet(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_calibration_baro(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_reboot(), GCS_MAVLINK::handle_command_request_autopilot_capabilities(), GCS_MAVLINK::handle_control_high_latency(), GCS_MAVLINK::handle_param_set(), GCS_MAVLINK::handle_preflight_reboot(), AC_Circle::init_start_angle(), NotchFilter< T >::init_with_A_and_Q(), Vector2< T >::operator!=(), Vector3< T >::operator!=(), Vector2< T >::operator==(), Vector3< T >::operator==(), AP_Filesystem_Param::pack_param(), AC_AutoTune_Heli::reset_vehicle_test_variables(), AP_OABendyRuler::resist_bearing_change(), AP_AutoTune::save_float_if_changed(), AP_Param::save_sync(), AP_OABendyRuler::search_vertical_path(), SCurve::set_destination_speed_max(), AP_Proximity_Boundary_3D::set_filtered_distance(), HALSITL::SITL_State::set_height_agl(), SCurve::set_origin_speed_max(), AC_Circle::set_rate(), SCurve::set_speed_max(), setup(), SITL::Gripper_Servo::should_report(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), AC_AutoTune_Heli::test_init(), AC_AutoTune_Multi::twitching_abort_rate(), SITL::TSYS01::update(), SITL::TSYS03::update(), Chirp::update(), AP_InertialSensor::HarmonicNotch::update_params(), AR_WPNav::update_speed_max(), AP_MotorsMulticopter::update_throttle_filter(), AP_L1_Control::update_waypoint(), AC_WPNav::update_wpnav(), AC_AutoTune_Heli::updating_angle_p_up(), AC_AutoTune_Heli::updating_max_gains(), AC_AutoTune_Heli::updating_rate_d_up(), AC_AutoTune_Heli::updating_rate_p_up(), and AP_Logger::validate_structures().
is_equal() [2/2]
template<typename Arithmetic1 , typename Arithmetic2 > std::enable_if< std::is_floating_point< typenamestd::common_type< Arithmetic1, Arithmetic2 >::type >::value, bool >::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
Definition at line 26 of file AP_Math.cpp.
is_equal< double >()
template bool is_equal< double > (const double v_1, const double v_2)
is_equal< float >()
template bool is_equal< float > (const float v_1, const float v_2)
is_equal< int >()
template bool is_equal< int > (const int v_1, const int v_2)
is_equal< long >()
template bool is_equal< long > (const long v_1, const long v_2)
is_equal< short >()
template bool is_equal< short > (const short v_1, const short v_2)
linear_interpolate()
float linear_interpolate (float low_output, float high_output, float var_value, float var_low, float var_high)
Definition at line 98 of file AP_Math.cpp.
Referenced by AP_TECS::_update_speed_demand(), SITL::Sailboat::calc_lift_and_drag(), AP_Tuning::check_input(), AP_MotorsUGV::output_skid_steering(), AP_Mount_Siyi::send_camera_settings(), AP_Mount_Siyi::set_zoom(), TEST(), throttle_curve(), AP_AutoTune::update(), AP_WindVane_Analog::update_direction(), SITL::IntelligentEnergy24::update_send(), and AC_AutoTune_Heli::updating_max_gains().
rotation_equal()
bool rotation_equal (enum Rotation r1, enum Rotation r2)
Definition at line 368 of file AP_Math.cpp.
Referenced by TEST(), and test_rotation_duplicates().
safe_asin()
template<typename T > float safe_asin (const T v)
Definition at line 50 of file AP_Math.cpp.
Referenced by QuaternionT< T >::get_euler_pitch(), AP_MotorsHeli_Swash::get_linear_servo_output(), AP_MotorsTri::output_armed_stabilizing(), TEST(), TEST(), Matrix3< T >::to_euler(), and AP_AHRS::update_AOA_SSA().
safe_asin< double >()
template float safe_asin< double > (const double v)
safe_asin< float >()
template float safe_asin< float > (const float v)
safe_asin< int >()
template float safe_asin< int > (const int v)
safe_asin< short >()
template float safe_asin< short > (const short v)
safe_sqrt()
template<typename T > float safe_sqrt (const T v)
Definition at line 71 of file AP_Math.cpp.
Referenced by AP_InertialSensor::_acal_save_calibrations(), AP_GPS_SBP2::_attempt_state_update(), Thrust_Linearization::apply_thrust_curve_and_volt_scaling(), SplineCurve::calc_dt_speed_max(), AP_AHRS::calc_trig(), AC_Circle::calc_velocities(), SCurve::calculate_path(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), AC_AttitudeControl::control_monitor_rms_output_pitch(), AC_AttitudeControl::control_monitor_rms_output_pitch_D(), AC_AttitudeControl::control_monitor_rms_output_pitch_P(), AC_AttitudeControl::control_monitor_rms_output_roll(), AC_AttitudeControl::control_monitor_rms_output_roll_D(), AC_AttitudeControl::control_monitor_rms_output_roll_P(), AC_AttitudeControl::control_monitor_rms_output_yaw(), AC_PosControl::crosstrack_error(), Vector3< T >::distance_to_segment(), AC_AutoTune_Heli::dwell_test_run(), AC_Avoid::get_max_speed(), AP_MotorsUGV::get_scaled_throttle(), SlewCalculator2D::get_slew_rate(), AP_Follow::get_target_dist_and_vel_ned(), AR_AttitudeControl::get_turn_rate_from_heading(), AP_InertialSensor::get_vibration_levels(), limit_accel_xy(), AC_PosControl::set_max_speed_accel_xy(), shape_vel_accel_xy(), sqrt_controller(), TEST(), TEST(), SITL::SIM_Precland::update(), SITL::Sailboat::update(), and AR_PosControl::update().
safe_sqrt< double >()
template float safe_sqrt< double > (const double v)
safe_sqrt< float >()
template float safe_sqrt< float > (const float v)
safe_sqrt< int >()
template float safe_sqrt< int > (const int v)
safe_sqrt< short >()
template float safe_sqrt< short > (const short v)
swap_float()
static void swap_float (float & f1, float & f2) static
Definition at line 88 of file AP_Math.cpp.
Referenced by linear_interpolate().
throttle_curve()
float throttle_curve (float thr_mid, float alpha, float thr_in)
Definition at line 131 of file AP_Math.cpp.
Referenced by TEST().
uint64_to_double_le()
double uint64_to_double_le (const uint64_t & value)
Definition at line 557 of file AP_Math.cpp.
wrap_180()
template<typename T > T wrap_180 (const T angle)
Definition at line 147 of file AP_Math.cpp.
Referenced by AC_Avoid::adjust_speed(), SITL::Sailboat::calc_lift_and_drag(), AR_PivotTurn::check_activation(), AP_Beacon_Backend::correct_for_orient_yaw(), AR_WPNav::get_corner_angle(), AP_OABendyRuler::resist_bearing_change(), AP_OABendyRuler::search_vertical_path(), AP_OABendyRuler::search_xy_path(), TEST(), TEST(), SITL::BalanceBot::update(), SITL::Sailboat::update(), SITL::PS_LightWare_SF45B::update_output_scan(), and AR_PivotTurn::would_activate().
wrap_180< float >()
template float wrap_180< float > (const float angle)
wrap_180< int >()
template int wrap_180< int > (const int angle)
wrap_180< short >()
template short wrap_180< short > (const short angle)
wrap_180_cd()
template<typename T > T wrap_180_cd (const T angle)
Definition at line 157 of file AP_Math.cpp.
Referenced by AP_L1_Control::_prevent_indecision(), AC_AutoTune::currently_level(), AC_AutoTune_Heli::dwell_test_run(), AR_AttitudeControl::get_forward_speed(), AP_L1_Control::get_yaw_sensor(), AC_AttitudeControl_Heli::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl_Heli::input_euler_angle_roll_pitch_yaw(), AP_L1_Control::nav_bearing_cd(), AC_AutoTune_Heli::rate_ff_test_run(), AP_L1_Control::target_bearing_cd(), TEST(), TEST(), test_wrap_cd(), AC_AutoTune_Multi::twitch_test_run(), and AP_L1_Control::update_heading_hold().
wrap_180_cd< float >()
template float wrap_180_cd< float > (const float angle)
wrap_180_cd< int >()
template int wrap_180_cd< int > (const int angle)
wrap_180_cd< long >()
template long wrap_180_cd< long > (const long angle)
wrap_180_cd< short >()
template short wrap_180_cd< short > (const short angle)
wrap_2PI()
ftype wrap_2PI (const ftype radian)
Definition at line 257 of file AP_Math.cpp.
Referenced by AP_Beacon::get_next_boundary_point(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), TEST(), TEST(), SITL::Sailboat::update_wave(), and wrap_PI().
wrap_360() [1/2]
float wrap_360 (const float angle)
Definition at line 181 of file AP_Math.cpp.
Referenced by AP_GPS_ERB::_parse_gps(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_SIRF::_parse_gps(), AP_GPS_NMEA::_term_complete(), AP_AHRS_View::AP_AHRS_View(), AP_GPS::calc_blended_state(), AP_Frsky_SPort_Passthrough::calc_waypoint(), AP_Frsky_SPort_Passthrough::calc_wind(), AP_GPS_Backend::calculate_moving_base_yaw(), AP_Proximity_Boundary_3D::get_face(), SITL::InertialLabs::send_packet(), AP_WindVane::send_wind(), AP_AHRS_View::set_pitch_trim(), TEST(), TEST(), SITL::Ship::update(), AP_GPS_Backend::velocity_to_speed_course(), and wrap_180().
wrap_360() [2/2]
int wrap_360 (const int angle)
Definition at line 201 of file AP_Math.cpp.
wrap_360_cd() [1/3]
float wrap_360_cd (const float angle)
Definition at line 210 of file AP_Math.cpp.
Referenced by AP_OSD_Screen::get_arrow_font_index(), AP_GPS::gps_yaw_cdeg(), AC_AutoTune_Heli::rate_ff_test_run(), SITL::ADSB::send_report(), AP_Hott_Telem::send_Vario(), AR_WPNav::set_desired_location(), AR_WPNav::set_desired_location_expect_fast_update(), TEST(), TEST(), test_wrap_cd(), AC_Circle::update(), AP_MSP_Telem_Backend::update_flight_mode_str(), AR_WPNav::update_steering_and_speed(), and wrap_180_cd().
wrap_360_cd() [2/3]
int wrap_360_cd (const int angle)
Definition at line 230 of file AP_Math.cpp.
wrap_360_cd() [3/3]
long wrap_360_cd (const long angle)
Definition at line 239 of file AP_Math.cpp.
wrap_PI()
ftype wrap_PI (const ftype radian)
Definition at line 248 of file AP_Math.cpp.
Referenced by EKFGSF_yaw::alignYaw(), NavEKF2_core::calcQuatAndFieldStates(), Compass::calculate_heading(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), AP_Mount_Backend::MountTarget::get_bf_yaw(), AP_Mount_Backend::MountTarget::get_ef_yaw(), AR_AttitudeControl::get_turn_rate_from_heading(), AP_L1_Control::get_yaw(), NavEKF2::getLastYawResetAngle(), NavEKF3::getLastYawResetAngle(), AC_Circle::init_start_angle(), AC_AttitudeControl::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl_Sub::input_euler_angle_roll_pitch_slew_yaw(), AC_AttitudeControl::input_euler_angle_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl::input_shaping_rate_predictor(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), NavEKF2_core::resetQuatStateYawOnly(), NavEKF3_core::resetQuatStateYawOnly(), AP_Mount_Siyi::send_target_angles(), AC_Loiter::set_pilot_desired_acceleration(), NavEKF3_core::setYawFromMag(), TEST(), TEST(), TEST(), test_euler(), test_euler(), test_wrap_cd(), AC_AttitudeControl::thrust_heading_rotation_angles(), QuaternionT< T >::to_axis_angle(), AP_WindVane::update(), AP_WindVane_NMEA::update(), EKFGSF_yaw::update(), AC_Circle::update(), AP_Mount_Backend::update_angle_target_from_rate(), AP_WindVane::update_apparent_wind_dir_from_true(), AP_WindVane_Analog::update_direction(), AP_WindVane_Home::update_direction(), AP_WindVane::update_true_wind_speed_and_direction(), SITL::Vicon::update_vicon_position_estimate(), AP_L1_Control::update_waypoint(), NavEKF2::updateLaneSwitchYawResetData(), and NavEKF3::updateLaneSwitchYawResetData().