APM:Libraries: libraries/AP_HAL_ChibiOS/UARTDriver.cpp File Reference
UARTDriver.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <hal.h>
#include "UARTDriver.h"
#include "GPIO.h"
#include <usbcfg.h>
#include "shared_dma.h"
#include <AP_Math/AP_Math.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_Common/ExpandingString.h>
#include "Scheduler.h"
#include "hwdef/common/stm32_util.h"
#include <GCS_MAVLink/GCS_MAVLink.h>
Macros
#define HAL_FORWARD_OTG2_SERIAL_LOCK_KEY 0x23565283UL
#define HAL_UART_MIN_TX_SIZE 512
#define HAL_UART_MIN_RX_SIZE 512
#define HAL_UART_STACK_SIZE 320
#define HAL_UART_RX_STACK_SIZE 768
#define CONTENTION_BAUD_THRESHOLD 115200
Functions
static int hal_console_vprintf (const char *fmt, va_list arg)
void usb_initialise (void)
Variables
const AP_HAL::HAL & hal
static const eventmask_t EVT_DATA = EVENT_MASK(10)
static const eventmask_t EVT_PARITY = EVENT_MASK(11)
static const eventmask_t EVT_TRANSMIT_END = EVENT_MASK(12)
static const eventmask_t EVT_TRANSMIT_DMA_START = EVENT_MASK(0)
static const eventmask_t EVT_TRANSMIT_DMA_COMPLETE = EVENT_MASK(1)
static const eventmask_t EVT_TRANSMIT_DATA_READY = EVENT_MASK(2)
static const eventmask_t EVT_TRANSMIT_UNBUFFERED = EVENT_MASK(3)
Macro Definition Documentation
CONTENTION_BAUD_THRESHOLD
#define CONTENTION_BAUD_THRESHOLD 115200
Definition at line 99 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::_begin(), and ChibiOS::UARTDriver::write_pending_bytes_DMA().
HAL_FORWARD_OTG2_SERIAL_LOCK_KEY
#define HAL_FORWARD_OTG2_SERIAL_LOCK_KEY 0x23565283UL
Definition at line 19 of file UARTDriver.cpp.
HAL_UART_MIN_RX_SIZE
#define HAL_UART_MIN_RX_SIZE 512
Definition at line 84 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::_begin().
HAL_UART_MIN_TX_SIZE
#define HAL_UART_MIN_TX_SIZE 512
Definition at line 80 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::_begin().
HAL_UART_RX_STACK_SIZE
#define HAL_UART_RX_STACK_SIZE 768
Definition at line 92 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::thread_rx_init().
HAL_UART_STACK_SIZE
#define HAL_UART_STACK_SIZE 320
Definition at line 88 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::thread_init().
Function Documentation
hal_console_vprintf()
static int hal_console_vprintf (const char * fmt, va_list arg) static
Definition at line 225 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::_begin().
usb_initialise()
void usb_initialise (void)
Definition at line 1763 of file UARTDriver.cpp.
Referenced by __wrap_vprintf(), ChibiOS::UARTDriver::_begin(), and HAL_ChibiOS::run().
Variable Documentation
EVT_DATA
const eventmask_t EVT_DATA = EVENT_MASK(10) static
Definition at line 65 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::_rx_timer_tick(), ChibiOS::UARTDriver::_tx_timer_tick(), ChibiOS::UARTDriver::rxbuff_full_irq(), and ChibiOS::UARTDriver::wait_timeout().
EVT_PARITY
const eventmask_t EVT_PARITY = EVENT_MASK(11) static
Definition at line 68 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::configure_parity().
EVT_TRANSMIT_DATA_READY
const eventmask_t EVT_TRANSMIT_DATA_READY = EVENT_MASK(2) static
Definition at line 76 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::_flush(), ChibiOS::UARTDriver::_write(), and ChibiOS::UARTDriver::uart_thread().
EVT_TRANSMIT_DMA_COMPLETE
const eventmask_t EVT_TRANSMIT_DMA_COMPLETE = EVENT_MASK(1) static
Definition at line 75 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::tx_complete(), and ChibiOS::UARTDriver::write_pending_bytes_DMA().
EVT_TRANSMIT_DMA_START
const eventmask_t EVT_TRANSMIT_DMA_START = EVENT_MASK(0) static
Definition at line 74 of file UARTDriver.cpp.
EVT_TRANSMIT_END
const eventmask_t EVT_TRANSMIT_END = EVENT_MASK(12) static
Definition at line 71 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::set_options(), and ChibiOS::UARTDriver::uart_thread().
EVT_TRANSMIT_UNBUFFERED
const eventmask_t EVT_TRANSMIT_UNBUFFERED = EVENT_MASK(3) static
Definition at line 77 of file UARTDriver.cpp.
Referenced by ChibiOS::UARTDriver::set_unbuffered_writes(), and ChibiOS::UARTDriver::uart_thread().
hal
const AP_HAL::HAL& hal extern
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.