APM:Libraries: libraries/AP_RCProtocol/AP_RCProtocol_SRXL2.cpp File Reference
AP_RCProtocol_SRXL2.cpp File Reference
#include "AP_RCProtocol_config.h"
#include "AP_RCProtocol.h"
#include "AP_RCProtocol_SRXL2.h"
#include <AP_Math/AP_Math.h>
#include <AP_RCTelemetry/AP_Spektrum_Telem.h>
#include <AP_Vehicle/AP_Vehicle_Type.h>
#include <AP_HAL/utility/sparse-endian.h>
#include <AP_VideoTX/AP_VideoTX.h>
#include "spm_srxl.h"
Macros
#define debug(fmt, args...) do {} while(0)
Functions
void srxlChangeBaudRate (uint8_t uart, uint32_t baudRate)
void srxlSendOnUart (uint8_t uart, uint8_t *pBuffer, uint8_t length)
void srxlFillTelemetry (SrxlTelemetryData *pTelemetryData)
void srxlReceivedChannelData (SrxlChannelData *pChannelData, bool isFailsafe)
bool srxlOnBind (SrxlFullID device, SrxlBindData info)
void srxlOnVtx (SrxlVtxData *pVtxData)
Variables
const AP_HAL::HAL & hal
Macro Definition Documentation
debug
#define debug (fmt, args...) do {} while(0)
Definition at line 39 of file AP_RCProtocol_SRXL2.cpp.
Function Documentation
srxlChangeBaudRate()
void srxlChangeBaudRate (uint8_t uart, uint32_t baudRate)
Definition at line 329 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlOnFrameError(), srxlParsePacket(), and srxlRun().
srxlFillTelemetry()
void srxlFillTelemetry (SrxlTelemetryData * pTelemetryData)
Definition at line 355 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlSend().
srxlOnBind()
bool srxlOnBind (SrxlFullID device, SrxlBindData info)
Definition at line 384 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlParsePacket().
srxlOnVtx()
void srxlOnVtx (SrxlVtxData * pVtxData)
Definition at line 390 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlParsePacket().
srxlReceivedChannelData()
void srxlReceivedChannelData (SrxlChannelData * pChannelData, bool isFailsafe)
Definition at line 367 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlParsePacket().
srxlSendOnUart()
void srxlSendOnUart (uint8_t uart, uint8_t * pBuffer, uint8_t length)
Definition at line 342 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlSend().
Variable Documentation
hal
const AP_HAL::HAL& hal extern
The data_array uses 3 elements to perform the data transaction. The first element is a data byte that provides to FPGA's hardware the transaction type that will be realized inside the SPI module. Where:
╔═════════╦═════════╦══════════╦══════════╦══════════╦══════════╦══════════╦═══════════╗ ║ MSB ║ ║ ║ ║ ║ ║ ║ LSB ║ ╠═════════╬═════════╬══════════╬══════════╬══════════╬══════════╬══════════╬═══════════╣ ║ wr_addr ║ rd_addr ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ ╚═════════╩═════════╩══════════╩══════════╩══════════╩══════════╩══════════╩═══════════╝
╔═══════════╦═════════╦═════════╗ ║ Register ║ wr_addr ║ rd_addr ║ ╠═══════════╬═════════╬═════════╣ ║ write ║ 0 ║ X ║ ╠═══════════╬═════════╬═════════╣ ║ read ║ X ║ 0 ║ ╠═══════════╬═════════╬═════════╣ ║ status ║ 1 ║ 1 ║ ╚═══════════╩═════════╩═════════╝
So, to perform a write transaction in the SPI module it's necessary to send. E.g: 0b 01xx xxxx And to a read transaction.. 0b 10xx xxxx
The PWM frequency is always even and the duty cycle percentage odd. E.g: pwm_01: Address 0x0000 frequency : Address 0x0001 duty cycle pwm_02: Address 0x0002 frequency Eg of allowed values: // PWM channel in 100Hz uint16_t freq = 100;
// duty cycle in (1823/65535) that's 2.78% of 100Hz: // the signal will hold high until 278 usec uint16_t duty = 1823;
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.