APM:Libraries: libraries/AP_HAL_ChibiOS/GPIO.cpp File Reference
GPIO.cpp File Reference
#include <hal.h>
#include "GPIO.h"
#include <AP_BoardConfig/AP_BoardConfig.h>
#include "hwdef/common/stm32_util.h"
#include <AP_InternalError/AP_InternalError.h>
#include <SRV_Channel/SRV_Channel.h>
#include <GCS_MAVLink/GCS.h>
#include <AP_Vehicle/AP_Vehicle_Type.h>
#include <AP_Math/AP_Math.h>
Classes
struct gpio_entry
Macros
#define HAVE_GPIO_PINS 0
Functions
static struct gpio_entry * gpio_by_pin_num (uint8_t pin_num, bool check_enabled=true)
static void pal_interrupt_cb (void *arg)
static void pal_interrupt_cb_functor (void *arg)
static void pal_interrupt_wait (void *arg)
Variables
const AP_HAL::HAL & hal
Macro Definition Documentation
HAVE_GPIO_PINS
#define HAVE_GPIO_PINS 0
Definition at line 59 of file GPIO.cpp.
Function Documentation
gpio_by_pin_num()
static struct gpio_entry * gpio_by_pin_num (uint8_t pin_num, bool check_enabled = true) static
Definition at line 66 of file GPIO.cpp.
Referenced by ChibiOS::GPIO::attach_interrupt(), ChibiOS::GPIO::attach_interrupt(), ChibiOS::GPIO::channel(), ChibiOS::GPIO::pinMode(), ChibiOS::GPIO::read(), ChibiOS::GPIO::toggle(), ChibiOS::GPIO::valid_pin(), ChibiOS::GPIO::wait_pin(), and ChibiOS::GPIO::write().
pal_interrupt_cb()
static void pal_interrupt_cb (void * arg) static
Definition at line 436 of file GPIO.cpp.
Referenced by ChibiOS::GPIO::_attach_interrupt().
pal_interrupt_cb_functor()
static void pal_interrupt_cb_functor (void * arg) static
Definition at line 443 of file GPIO.cpp.
Referenced by ChibiOS::GPIO::attach_interrupt().
pal_interrupt_wait()
static void pal_interrupt_wait (void * arg) static
Definition at line 476 of file GPIO.cpp.
Referenced by ChibiOS::GPIO::wait_pin().
Variable Documentation
hal
const AP_HAL::HAL& hal extern
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.