APM:Libraries: libraries/AP_HAL_SITL/Storage.cpp File Reference
Storage.cpp File Reference
#include "Storage.h"
#include <AP_Vehicle/AP_Vehicle_Type.h>
#include <AP_HAL/AP_HAL.h>
#include "AP_HAL_SITL.h"
#include <assert.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
Macros
#define HAL_STORAGE_FILE "eeprom.bin"
#define HAL_FLASH_SECTOR_SIZE (16*1024)
#define HAL_FLASH_MIN_WRITE_SIZE 1
#define HAL_FLASH_ALLOW_UPDATE 1
#define HAL_RAMTRON_ALLOW_FALLBACK 0
Functions
static uint32_t sitl_flash_getpageaddr (uint32_t page)
static void sitl_flash_open (void)
static bool sitl_flash_write (uint32_t addr, const uint8_t *data, uint32_t length)
static bool sitl_flash_read (uint32_t addr, uint8_t *data, uint32_t length)
static bool sitl_flash_erasepage (uint32_t page)
Variables
HAL_SITL & hal
static int flash_fd = -1
Macro Definition Documentation
HAL_FLASH_ALLOW_UPDATE
#define HAL_FLASH_ALLOW_UPDATE 1
Definition at line 46 of file Storage.cpp.
HAL_FLASH_MIN_WRITE_SIZE
#define HAL_FLASH_MIN_WRITE_SIZE 1
Definition at line 42 of file Storage.cpp.
HAL_FLASH_SECTOR_SIZE
#define HAL_FLASH_SECTOR_SIZE (16*1024)
Definition at line 33 of file Storage.cpp.
HAL_RAMTRON_ALLOW_FALLBACK
#define HAL_RAMTRON_ALLOW_FALLBACK 0
HAL_STORAGE_FILE
#define HAL_STORAGE_FILE "eeprom.bin"
Definition at line 20 of file Storage.cpp.
Function Documentation
sitl_flash_erasepage()
static bool sitl_flash_erasepage (uint32_t page) static
Definition at line 320 of file Storage.cpp.
Referenced by HALSITL::Storage::_flash_erase_sector().
sitl_flash_getpageaddr()
static uint32_t sitl_flash_getpageaddr (uint32_t page) static
Definition at line 247 of file Storage.cpp.
Referenced by HALSITL::Storage::_flash_read_data(), and HALSITL::Storage::_flash_write_data().
sitl_flash_open()
static void sitl_flash_open (void) static
Definition at line 252 of file Storage.cpp.
Referenced by sitl_flash_erasepage(), sitl_flash_read(), and sitl_flash_write().
sitl_flash_read()
static bool sitl_flash_read (uint32_t addr, uint8_t * data, uint32_t length) static
Definition at line 314 of file Storage.cpp.
Referenced by HALSITL::Storage::_flash_read_data().
sitl_flash_write()
static bool sitl_flash_write (uint32_t addr, const uint8_t * data, uint32_t length) static
Definition at line 273 of file Storage.cpp.
Referenced by HALSITL::Storage::_flash_write_data().
Variable Documentation
flash_fd
int flash_fd = -1 static
Definition at line 245 of file Storage.cpp.
Referenced by sitl_flash_erasepage(), sitl_flash_open(), sitl_flash_read(), and sitl_flash_write().
hal
HAL_SITL& hal extern
The data_array uses 3 elements to perform the data transaction. The first element is a data byte that provides to FPGA's hardware the transaction type that will be realized inside the SPI module. Where:
╔═════════╦═════════╦══════════╦══════════╦══════════╦══════════╦══════════╦═══════════╗ ║ MSB ║ ║ ║ ║ ║ ║ ║ LSB ║ ╠═════════╬═════════╬══════════╬══════════╬══════════╬══════════╬══════════╬═══════════╣ ║ wr_addr ║ rd_addr ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ ╚═════════╩═════════╩══════════╩══════════╩══════════╩══════════╩══════════╩═══════════╝
╔═══════════╦═════════╦═════════╗ ║ Register ║ wr_addr ║ rd_addr ║ ╠═══════════╬═════════╬═════════╣ ║ write ║ 0 ║ X ║ ╠═══════════╬═════════╬═════════╣ ║ read ║ X ║ 0 ║ ╠═══════════╬═════════╬═════════╣ ║ status ║ 1 ║ 1 ║ ╚═══════════╩═════════╩═════════╝
So, to perform a write transaction in the SPI module it's necessary to send. E.g: 0b 01xx xxxx And to a read transaction.. 0b 10xx xxxx
The PWM frequency is always even and the duty cycle percentage odd. E.g: pwm_01: Address 0x0000 frequency : Address 0x0001 duty cycle pwm_02: Address 0x0002 frequency Eg of allowed values: // PWM channel in 100Hz uint16_t freq = 100;
// duty cycle in (1823/65535) that's 2.78% of 100Hz: // the signal will hold high until 278 usec uint16_t duty = 1823;
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.