APM:Libraries: libraries/AP_Filesystem/AP_Filesystem_posix.cpp File Reference
AP_Filesystem_posix.cpp File Reference
#include "AP_Filesystem_config.h"
#include "AP_Filesystem.h"
#include <AP_HAL/AP_HAL.h>
#include <AP_Vehicle/AP_Vehicle_Type.h>
#include <sys/vfs.h>
#include <utime.h>
Functions
static const char * map_filename (const char *fname)
Variables
const AP_HAL::HAL & hal
Function Documentation
map_filename()
static const char * map_filename (const char * fname) static
Definition at line 39 of file AP_Filesystem_posix.cpp.
Referenced by AP_Filesystem_Posix::disk_free(), AP_Filesystem_Posix::disk_space(), AP_Filesystem_Posix::mkdir(), AP_Filesystem_Posix::open(), AP_Filesystem_Posix::opendir(), AP_Filesystem_Posix::rename(), AP_Filesystem_Posix::set_mtime(), AP_Filesystem_Posix::stat(), and AP_Filesystem_Posix::unlink().
Variable Documentation
hal
const AP_HAL::HAL& hal extern
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.