APM:Libraries: libraries/AP_Common/AP_Common.cpp File Reference
AP_Common.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include "AP_Common.h"
Functions
bool is_bounded_int32 (int32_t value, int32_t lower_bound, int32_t upper_bound)
bool hex_to_uint8 (uint8_t a, uint8_t &res)
size_t strncpy_noterm (char *dest, const char *src, size_t n)
int16_t char_to_hex (char a)
Variables
const AP_HAL::HAL & hal
Function Documentation
char_to_hex()
int16_t char_to_hex (char a)
return the numeric value of an ascii hex character
Parameters
[in] a Hexadecimal character
Returns
Returns a binary value
Definition at line 98 of file AP_Common.cpp.
Referenced by AP_WindVane_NMEA::decode_latest_term(), and HALSITL::UARTDriver::read_from_async_csv().
hex_to_uint8()
bool hex_to_uint8 (uint8_t a, uint8_t & res)
return the numeric value of an ascii hex character
Parameters
[in] a Hexa character
[out] res uint8 value
Return values
true Conversion OK
false Input value error @Note Input character is 0-9, A-F, a-f A 0x41, a 0x61, 0 0x30
Definition at line 53 of file AP_Common.cpp.
Referenced by AP_RangeFinder_NMEA::decode_latest_term(), and TEST().
is_bounded_int32()
bool is_bounded_int32 (int32_t value, int32_t lower_bound, int32_t upper_bound)
Definition at line 32 of file AP_Common.cpp.
Referenced by RC_Channel::in_trim_dz(), and TEST().
strncpy_noterm()
size_t strncpy_noterm (char * dest, const char * src, size_t n)
Definition at line 80 of file AP_Common.cpp.
Referenced by AP_stack_overflow(), AP_Logger_Backend::Fill_Format(), AP_Logger_Backend::Fill_Format_Units(), ChibiOS::Util::log_stack_info(), AP_Logger::msg_fmt_for_name(), SITL::Gimbal::param_send(), AP_RCTelemetry::queue_message(), AP_Filesystem::readdir(), AP_Filesystem_Sys::readdir(), save_fault_watchdog(), GCS_MAVLINK::send_autopilot_version(), TEST(), AP_Logger_Backend::Write_Message(), AP_Logger_Backend::Write_Parameter(), and AP_Logger_Backend::Write_Unit().
Variable Documentation
hal
const AP_HAL::HAL& hal extern
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.
Referenced by setup(), and test_high_low_byte().