APM:Libraries: libraries/AP_HAL_ESP32/Scheduler.cpp File Reference
Scheduler.cpp File Reference
#include "AP_HAL_ESP32/Scheduler.h"
#include "AP_HAL_ESP32/RCInput.h"
#include "AP_HAL_ESP32/AnalogIn.h"
#include "AP_Math/AP_Math.h"
#include "SdCard.h"
#include "Profile.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "soc/rtc_wdt.h"
#include "esp_int_wdt.h"
#include "esp_task_wdt.h"
#include <AP_HAL/AP_HAL.h>
#include <AP_Scheduler/AP_Scheduler.h>
#include <stdio.h>
Macros
#define FASTCPU 0
#define SLOWCPU 1
#define EXTRA_THREAD_SPACE 1024
Functions
void disableCore0WDT ()
void disableCore1WDT ()
void enableCore0WDT ()
void enableCore1WDT ()
template<typename T >
void executor (T oui)
Variables
const AP_HAL::HAL & hal
TaskHandle_t idle_0 = NULL
TaskHandle_t idle_1 = NULL
Macro Definition Documentation
EXTRA_THREAD_SPACE
#define EXTRA_THREAD_SPACE 1024
FASTCPU
#define FASTCPU 0
SLOWCPU
#define SLOWCPU 1
Function Documentation
disableCore0WDT()
void disableCore0WDT ()
Definition at line 49 of file Scheduler.cpp.
Referenced by ESP32::Scheduler::init().
disableCore1WDT()
void disableCore1WDT ()
Definition at line 57 of file Scheduler.cpp.
Referenced by ESP32::Scheduler::init().
enableCore0WDT()
void enableCore0WDT ()
Definition at line 64 of file Scheduler.cpp.
Referenced by ESP32::Scheduler::init().
enableCore1WDT()
void enableCore1WDT ()
Definition at line 70 of file Scheduler.cpp.
executor()
template<typename T > void executor (T oui)
Definition at line 151 of file Scheduler.cpp.
Variable Documentation
hal
const AP_HAL::HAL& hal extern
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.
idle_0
TaskHandle_t idle_0 = NULL
Definition at line 41 of file Scheduler.cpp.
Referenced by disableCore0WDT(), and enableCore0WDT().
idle_1
TaskHandle_t idle_1 = NULL
Definition at line 42 of file Scheduler.cpp.
Referenced by disableCore1WDT(), and enableCore1WDT().