APM:Libraries: libraries/AP_Math/AP_Math.h File Reference
AP_Math.h File Reference
#include <cmath>
#include <limits>
#include <stdint.h>
#include <type_traits>
#include <AP_Common/AP_Common.h>
#include <AP_Param/AP_Param.h>
#include "definitions.h"
#include "crc.h"
#include "matrix3.h"
#include "polygon.h"
#include "quaternion.h"
#include "rotations.h"
#include "vector2.h"
#include "vector3.h"
#include "spline5.h"
#include "location.h"
#include "control.h"
Macros
#define constrain_float(amt, low, high) constrain_value_line(float(amt), float(low), float(high), uint32_t(__AP_LINE__))
#define constrain_ftype(amt, low, high) constrain_value_line(ftype(amt), ftype(low), ftype(high), uint32_t(__AP_LINE__))
Typedefs
typedef Vector2< float > Vector2F
typedef Vector3< float > Vector3F
typedef Matrix3< float > Matrix3F
typedef Quaternion QuaternionF
Functions
AP_PARAMDEFV (Vector3f, Vector3f, AP_PARAM_VECTOR3F)
template<typename Arithmetic1 , typename Arithmetic2 >
std::enable_if< std::is_integral< typenamestd::common_type< Arithmetic1, Arithmetic2 >::type >::value, bool >::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
template<typename Arithmetic1 , typename Arithmetic2 >
std::enable_if< std::is_floating_point< typenamestd::common_type< Arithmetic1, Arithmetic2 >::type >::value, bool >::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
template<typename T >
bool is_zero (const T fVal1)
template<typename T >
bool is_positive (const T fVal1)
template<typename T >
bool is_negative (const T fVal1)
bool is_positive (const double fVal1)
bool is_negative (const double fVal1)
template<typename T >
float safe_asin (const T v)
template<typename T >
float safe_sqrt (const T v)
template<typename T >
void mat_mul (const T *A, const T *B, T *C, uint16_t n)
template<typename T >
bool mat_inverse (const T *x, T *y, uint16_t dim) WARN_IF_UNUSED
template<typename T >
void mat_identity (T *x, uint16_t dim)
template<typename T >
T wrap_180 (const T angle)
template<typename T >
T wrap_180_cd (const T angle)
float wrap_360 (const float angle)
int wrap_360 (const int angle)
int wrap_360_cd (const int angle)
long wrap_360_cd (const long angle)
float wrap_360_cd (const float angle)
ftype wrap_PI (const ftype radian)
ftype wrap_2PI (const ftype radian)
template<typename T >
T constrain_value (const T amt, const T low, const T high)
template<typename T >
T constrain_value_line (const T amt, const T low, const T high, uint32_t line)
int16_t constrain_int16 (const int16_t amt, const int16_t low, const int16_t high)
uint16_t constrain_uint16 (const uint16_t amt, const uint16_t low, const uint16_t high)
int32_t constrain_int32 (const int32_t amt, const int32_t low, const int32_t high)
uint32_t constrain_uint32 (const uint32_t amt, const uint32_t low, const uint32_t high)
int64_t constrain_int64 (const int64_t amt, const int64_t low, const int64_t high)
uint64_t constrain_uint64 (const uint64_t amt, const uint64_t low, const uint64_t high)
double constrain_double (const double amt, const double low, const double high)
static constexpr ftype radians (ftype deg)
static constexpr float degrees (float rad)
template<typename T >
ftype sq (const T val)
static constexpr float sq (const float val)
template<typename T , typename... Params>
ftype sq (const T first, const Params... parameters)
template<typename T , typename U , typename... Params>
ftype norm (const T first, const U second, const Params... parameters)
template<typename A , typename B >
static auto MIN (const A &one, const B &two) -> decltype(one< two ? one :two)
template<typename A , typename B >
static auto MAX (const A &one, const B &two) -> decltype(one > two ? one :two)
constexpr uint32_t hz_to_nsec (uint32_t freq)
constexpr uint32_t nsec_to_hz (uint32_t nsec)
constexpr uint32_t usec_to_nsec (uint32_t usec)
constexpr uint32_t nsec_to_usec (uint32_t nsec)
constexpr uint32_t hz_to_usec (uint32_t freq)
constexpr uint32_t usec_to_hz (uint32_t usec)
float linear_interpolate (float low_output, float high_output, float var_value, float var_low, float var_high)
float expo_curve (float alpha, float input)
float throttle_curve (float thr_mid, float alpha, float thr_in)
uint16_t get_random16 (void)
float rand_float (void)
Vector3f rand_vec3f (void)
bool rotation_equal (enum Rotation r1, enum Rotation r2) WARN_IF_UNUSED
Vector3F get_vel_correction_for_sensor_offset (const Vector3F &sensor_offset_bf, const Matrix3F &rot_ef_to_bf, const Vector3F &angular_rate)
float calc_lowpass_alpha_dt (float dt, float cutoff_freq)
void fill_nanf (float *f, uint16_t count)
void fill_nanf (double *f, uint16_t count)
float fixed2float (const uint16_t input, const uint8_t fractional_bits=8)
uint16_t float2fixed (const float input, const uint8_t fractional_bits=8)
float fixedwing_turn_rate (float bank_angle_deg, float airspeed)
float degF_to_Kelvin (float temp_f)
int16_t float_to_int16 (const float v)
uint16_t float_to_uint16 (const float v)
int32_t float_to_int32 (const float v)
uint32_t float_to_uint32 (const float v)
uint32_t double_to_uint32 (const double v)
int32_t double_to_int32 (const double v)
int32_t float_to_int32_le (const float &value) WARN_IF_UNUSED
float int32_to_float_le (const uint32_t &value) WARN_IF_UNUSED
double uint64_to_double_le (const uint64_t &value) WARN_IF_UNUSED
Macro Definition Documentation
constrain_float
#define constrain_float (amt, low, high) constrain_value_line(float(amt), float(low), float(high), uint32_t(__AP_LINE__))
Definition at line 174 of file AP_Math.h.
Referenced by AP_AHRS::_airspeed_estimate(), AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), HALSITL::SITL_State::_output_to_flightgear(), HALSITL::SITL_State::_simulator_servos(), HALSITL::SITL_State::_sonar_pin_voltage(), AP_TECS::_update_height_demand(), AP_TECS::_update_pitch(), AP_InertialSensor_Backend::_update_sensor_rate(), AP_TECS::_update_speed(), AP_TECS::_update_speed_demand(), AP_TECS::_update_throttle_with_airspeed(), AP_TECS::_update_throttle_without_airspeed(), AP_Airspeed_MS4525::_voltage_correction(), AP_MotorsMulticopter::actuator_spin_up_to_ground_idle(), Thrust_Linearization::actuator_to_thrust(), AP_AHRS::add_trim(), AC_Avoid::adjust_roll_pitch(), SplineCurve::advance_target_along_track(), AR_WPNav::advance_wp_target_along_track(), AC_WPNav::advance_wp_target_along_track(), AC_AttitudeControl::ang_vel_limit(), DigitalLPF< T >::apply(), Thrust_Linearization::apply_thrust_curve_and_volt_scaling(), AC_AttitudeControl::attitude_from_thrust_vector(), AP_MotorsHeli_RSC::autothrottle_run(), AC_AutoTune_Multi::backup_gains_and_initialise(), AP_Frsky_SPort_Passthrough::calc_ap_status(), AC_Loiter::calc_desired_velocity(), SRV_Channels::calc_pwm(), AP_AHRS::calc_trig(), AC_Circle::calc_velocities(), SITL::SimRover::calc_yaw_rate(), SITL::Motor::calculate_forces(), SITL::Blimp::calculate_forces(), Compass::calculate_heading(), AP_MotorsHeli_Dual::calculate_scalars(), AP_MotorsHeli_Quad::calculate_scalars(), AP_MotorsHeli_Single::calculate_scalars(), AP_MotorsHeli_RSC::calculate_throttlecurve(), AP_BattMonitor_Backend::capacity_remaining_pct(), AP_Camera_Servo::configure(), AP_Generator_IE_2400::decode_legacy_data(), AP_RCProtocol_CRSF::derive_scaled_lq_value(), AP_RCProtocol_GHST::derive_scaled_lq_value(), AP_OSD_Screen::draw_horizon(), AC_AutoTune_Heli::dwell_test_run(), AC_AttitudeControl::euler_accel_limit(), SITL::FlightAxis::exchange_data(), fixedwing_turn_rate(), float_to_int16(), float_to_int32(), float_to_uint16(), float_to_uint32(), AP_Mount_Servo::get_attitude_quaternion(), Thrust_Linearization::get_compensation_gain(), AP_MotorsMulticopter::get_current_limit_max_throttle(), get_declination(), AR_PivotTurn::get_delay_duration_ms(), AR_AttitudeControl::get_desired_speed_accel_limited(), AP_Proximity_Boundary_3D::get_face(), AP_MotorsHeli_Swash::get_linear_servo_output(), AC_InputManager_Heli::get_pilot_desired_collective(), AC_AutoTune::get_poshold_attitude(), AP_YawController::get_rate_out(), AC_AttitudeControl_Heli::get_roll_trim_cd(), AC_AttitudeControl_Heli::get_roll_trim_rad(), AR_AttitudeControl::get_sail_out_from_heel(), AP_MotorsUGV::get_scaled_throttle(), AP_YawController::get_servo_out(), AP_WheelEncoder::get_signal_quality(), SRV_Channels::get_slew_limited_output_scaled(), AP_MotorsUGV::get_slew_limited_throttle(), AP_SteerController::get_steering_out_rate(), AR_AttitudeControl::get_steering_out_rate(), AC_PosControl::get_stopping_point_xy_cm(), AC_PosControl::get_stopping_point_z_cm(), AP_Motors::get_throttle(), AC_AttitudeControl_Multi::get_throttle_avg_max(), AC_AttitudeControl_Sub::get_throttle_avg_max(), AP_Motors::get_throttle_bidirectional(), AC_AttitudeControl_Multi::get_throttle_boosted(), AC_AttitudeControl_Sub::get_throttle_boosted(), AP_MotorsHeli::get_throttle_hover(), AP_MotorsMulticopter::get_throttle_hover(), AR_AttitudeControl::get_throttle_out_from_pitch(), AR_AttitudeControl::get_throttle_out_speed(), AR_AttitudeControl::get_turn_rate_from_heading(), AC_PosControl::get_vel_z_control_ratio(), AP_MotorsHeli_Single::get_yaw_offset(), SITL::Plane::getTorque(), HarmonicNotchFilter< T >::init(), AC_PrecLand::init(), NotchFilter< T >::init_with_A_and_Q(), AC_PosControl::init_z_controller(), AC_AttitudeControl::input_euler_angle_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), input_expo(), AC_PosControl::input_pos_vel_accel_z(), AC_PosControl::input_pos_xyz(), AC_AttitudeControl::input_shaping_ang_vel(), AC_AttitudeControl::input_shaping_angle(), AC_AttitudeControl::input_thrust_vector_heading(), AC_AttitudeControl::input_thrust_vector_rate_heading(), AC_PosControl::input_vel_accel_z(), AC_AttitudeControl_Heli::integrate_bf_rate_error_to_angle_errors(), limit_accel_xy(), Location::linearly_interpolate_alt(), AP_Scheduler::load_average(), AP_L1_Control::loiter_radius(), AC_AttitudeControl::max_rate_step_bf_pitch(), AC_AttitudeControl::max_rate_step_bf_roll(), AC_AttitudeControl::max_rate_step_bf_yaw(), AP_MotorsHeli_Dual::mix_tandem(), AP_MotorsHeli_Dual::mix_transverse(), AP_OSD_ParamScreen::modify_parameter(), SRV_Channels::move_servo(), AP_MSP_Telem_Backend::msp_process_out_analog(), AP_L1_Control::nav_roll_cd(), MMLPlayer::next_action(), RC_Channel::norm_input(), RC_Channel::norm_input_dz(), RC_Channel::norm_input_ignore_trim(), AP_MotorsHeli_RSC::output(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsMulticopter::output_boost_throttle(), AP_MotorsMulticopter::output_logic(), AP_MotorsUGV::output_omni(), SITL::Morse::output_quad(), AP_MotorsUGV::output_regular(), AP_MotorsUGV::output_skid_steering(), AP_MotorsUGV::output_test_pct(), SITL::Webots::output_tricopter(), AC_AttitudeControl_Multi::parameter_sanity_check(), AC_AttitudeControl_Sub::parameter_sanity_check(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), AC_PosControl::pos_offset_z_scaler(), SRV_Channel::pwm_from_angle(), SRV_Channel::pwm_from_range(), SITL::Motor::pwm_to_command(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_target_to_motor_yaw(), rc_input_to_roll_pitch(), NavEKF3_core::realignYawGPS(), SITL::JSON::recv_fdm(), AC_PID::relax_integrator(), Thrust_Linearization::remove_thrust_curve_and_volt_scaling(), AP_BattMonitor_Backend::reset_remaining(), QuaternionT< T >::roll_pitch_difference(), AP_MotorsUGV::sanity_check_parameters(), AP_RSSI::scale_and_constrain_float_rssi(), AP_OABendyRuler::search_vertical_path(), AP_OABendyRuler::search_xy_path(), AP_SmartRTL::segment_segment_dist(), SITL::CRRCSim::send_servos_fixed_wing(), SITL::CRRCSim::send_servos_heli(), GCS_MAVLINK::send_sys_status(), AP_Mount_Siyi::send_target_angles(), AP_Mount_Siyi::send_target_rates(), AP_MotorsHeli_Dual::servo_test(), AP_MotorsHeli_Single::servo_test(), AP_MotorsMulticopter::set_actuator_with_slew(), AP_Mount_Backend::set_angle_target(), AP_Winch::set_desired_rate(), AP_Param::set_float(), AC_AttitudeControl_Heli::set_hover_roll_trim_scalar(), AC_AttitudeControl::set_input_tc(), AC_PID::set_integrator(), AC_PID_Basic::set_integrator(), AP_MotorsUGV::set_lateral(), AP_MotorsUGV::set_mainsail(), AP_MotorsUGV::set_mast_rotation(), AP_TECS::set_path_proportion(), AP_MotorsUGV::set_pitch(), AC_Circle::set_radius_cm(), AP_MotorsUGV::set_roll(), AC_InputManager_Heli::set_stab_col_ramp(), AP_MotorsUGV::set_throttle(), AP_Motors::set_throttle_avg_max(), AP_MotorsHeli_RSC::set_throttle_curve(), AC_AttitudeControl_Multi::set_throttle_mix_max(), AP_MotorsMulticopter::set_throttle_passthrough_for_esc_calibration(), AP_AHRS::set_trim(), AP_MotorsUGV::set_walking_height(), AP_MotorsUGV::set_wingsail(), shape_accel(), shape_pos_vel_accel(), shape_vel_accel(), shape_vel_accel_xy(), sqrt_controller(), AP_AutoTune::start(), TEST(), throttle_curve(), AC_AttitudeControl::thrust_heading_rotation_angles(), Thrust_Linearization::thrust_to_actuator(), AC_AttitudeControl::thrust_vector_rotation_angles(), AP_Camera_Servo::trigger_pic(), AC_AutoTune_Multi::twitch_test_init(), AP_Landing::type_slope_get_target_airspeed_cm(), AP_Landing::type_slope_setup_landing_glide_slope(), AP_OABendyRuler::update(), SITL::Gripper_Servo::update(), SITL::ICEngine::update(), SITL::Sprayer::update(), SITL::Blimp::update(), SITL::FlightAxis::update(), SITL::Helicopter::update(), SITL::JSON::update(), SITL::Morse::update(), SITL::Sailboat::update(), SITL::SingleCopter::update(), SITL::Webots::update(), Airspeed_Calibration::update(), HarmonicNotchFilter< T >::update(), SITL::Ship::update(), AC_PI::update(), SpeedToFly::update(), AP_AutoTune::update(), HarmonicNotchFilter< T >::update(), SITL::Gimbal::update(), AP_RPM_Pin::update(), AC_AttitudeControl_Heli::update_althold_lean_angle_max(), AC_AttitudeControl_Multi::update_althold_lean_angle_max(), AC_AttitudeControl_Sub::update_althold_lean_angle_max(), AC_AttitudeControl::update_ang_vel_target_from_att_error(), AP_Mount_Servo::update_angle_outputs(), AP_Mount_Backend::update_angle_target_from_rate(), AP_Airspeed::update_calibration(), AP_L1_Control::update_heading_hold(), AC_PID::update_i(), AC_PID_Basic::update_i(), AP_ICEngine::update_idle_governor(), Thrust_Linearization::update_lift_max_from_batt_voltage(), AP_L1_Control::update_loiter(), AP_TECS::update_pitch_throttle(), SITL::Tracker::update_position_servos(), AP_BattMonitor_Backend::update_resistance_estimate(), AP_AutoTune::update_rmax(), SITL::Motor::update_servo(), AP_WindVane_ModernDevice::update_speed(), AC_AttitudeControl_Multi::update_throttle_gain_boost(), AP_MotorsHeli::update_throttle_hover(), AP_MotorsMulticopter::update_throttle_hover(), AC_AttitudeControl_Multi::update_throttle_rpy_mix(), AC_AttitudeControl_Sub::update_throttle_rpy_mix(), update_vel_accel(), AP_L1_Control::update_waypoint(), AC_PosControl::update_z_controller(), AC_AutoTune_Heli::updating_max_gains(), AC_AutoTune_Heli::updating_rate_d_up(), AC_AutoTune_Heli::updating_rate_ff_up(), and AC_AutoTune_Heli::updating_rate_p_up().
constrain_ftype
#define constrain_ftype (amt, low, high) constrain_value_line(ftype(amt), ftype(low), ftype(high), uint32_t(__AP_LINE__))
Definition at line 175 of file AP_Math.h.
Referenced by NavEKF2_core::calcFiltBaroOffset(), NavEKF3_core::calcFiltBaroOffset(), NavEKF2_core::calcGpsGoodForFlight(), NavEKF3_core::calcGpsGoodForFlight(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), NavEKF2_core::calcOutputStates(), NavEKF3_core::calcOutputStates(), NavEKF3_core::calcTiltErrorVariance(), NavEKF3_core::CalculateVelInnovationsAndVariances(), NavEKF2_core::ConstrainStates(), NavEKF3_core::ConstrainStates(), NavEKF2_core::ConstrainVariances(), NavEKF3_core::ConstrainVariances(), NavEKF2_core::correctEkfOriginHeight(), NavEKF3_core::correctEkfOriginHeight(), NavEKF2_core::CovariancePrediction(), NavEKF3_core::CovariancePrediction(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::fuseEulerYaw(), NavEKF2_core::FuseMagnetometer(), NavEKF3_core::FuseMagnetometer(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), NavEKF3_core::FuseSideslip(), NavEKF2_core::FuseVelPosNED(), NavEKF3_core::FuseVelPosNED(), NavEKF2_core::learnInactiveBiases(), NavEKF3_core::learnInactiveBiases(), NavEKF2_core::MagTableConstrain(), NavEKF3_core::MagTableConstrain(), Vector3< T >::point_on_line_closest_to_other_point(), EKFGSF_yaw::predictAHRS(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), NavEKF2_core::setAidingMode(), NavEKF3_core::setAidingMode(), NavEKF2_core::setWindMagStateLearningMode(), NavEKF3_core::setWindMagStateLearningMode(), NavEKF3::updateCoreRelativeErrors(), NavEKF2_core::writeOptFlowMeas(), and NavEKF3_core::writeOptFlowMeas().
Typedef Documentation
Matrix3F
typedef Matrix3<float> Matrix3F
Definition at line 31 of file AP_Math.h.
QuaternionF
typedef Quaternion QuaternionF
Definition at line 32 of file AP_Math.h.
Vector2F
typedef Vector2<float> Vector2F
Definition at line 29 of file AP_Math.h.
Vector3F
typedef Vector3<float> Vector3F
Definition at line 30 of file AP_Math.h.
Function Documentation
AP_PARAMDEFV()
AP_PARAMDEFV (Vector3f , Vector3f , AP_PARAM_VECTOR3F)
calc_lowpass_alpha_dt()
float calc_lowpass_alpha_dt (float dt, float cutoff_freq)
Definition at line 402 of file AP_Math.cpp.
Referenced by AC_PID::get_filt_D_alpha(), AC_PID_2D::get_filt_D_alpha(), AC_PID_Basic::get_filt_D_alpha(), AC_PID::get_filt_E_alpha(), AC_PID_2D::get_filt_E_alpha(), AC_PID_Basic::get_filt_E_alpha(), AC_PID::get_filt_T_alpha(), LowPassHelper::print_transfer_function(), TEST(), and AP_DAL_InertialSensor::update_filtered().
constrain_double()
double constrain_double (const double amt, const double low, const double high) inline
Definition at line 207 of file AP_Math.h.
Referenced by double_to_int32(), and double_to_uint32().
constrain_int16()
int16_t constrain_int16 (const int16_t amt, const int16_t low, const int16_t high) inline
Definition at line 177 of file AP_Math.h.
Referenced by Linux::RCOutput_Bebop::_period_us_to_rpm(), AP_InertialSensor_Invensensev2::_set_filter_and_scaling(), AP_InertialSensor_Invensense::_set_filter_register(), HALSITL::SITL_State::_simulator_servos(), AP_RunCam::AP_RunCam(), SITL::Sailboat::calc_lift_and_drag(), AP_InertialSensor_Invensensev3::calculate_fast_sampling_backend_rate(), ChibiOS::Scheduler::calculate_thread_priority(), Linux::Scheduler::calculate_thread_priority(), AP_MotorsHeli_RSC::calculate_throttlecurve(), AP_VideoTX::change_power(), AP_GPS_Backend::check_new_itow(), SRV_Channels::constrain_pwm(), AP_OSD_Screen::draw_message(), ChibiOS::RCOutput::dshot_send(), AP_SmartRTL::init(), AP_BoardConfig::init(), loop(), AP_IOMCU_FW::mix_output_angle(), AP_IOMCU_FW::mix_output_range(), AP_OSD_ParamScreen::modify_parameter(), AP_MSP_Telem_Backend::msp_process_out_analog(), AP_MSP_Telem_Backend::msp_process_out_name(), AP_Frsky_SPort::prep_number(), AP_RangeFinder_Benewake_TFMiniPlus::process_raw_measure(), RC_Channel::pwm_to_angle_dz_trim(), RC_Channel::pwm_to_range_dz(), AP_MotorsUGV::sanity_check_parameters(), AP_Mount_Siyi::send_zoom_mult(), AP_InertialSensor_Invensensev3::set_filter_and_scaling_icm456xy(), SRV_Channels::set_output_pwm_trimmed(), ChibiOS::SPIDevice::set_slowdown(), AP_InertialSensor_SCHA63T::start(), TEST(), ESP32::Scheduler::thread_create(), AP_OSD_AbstractScreen::u_icon(), AP_OSD_AbstractScreen::u_scale(), SITL::Helicopter::update(), SITL::Sailboat::update(), AP_OpticalFlow_CXOF::update(), AP_RangeFinder_Wasp::update(), and SITL::Motor::update_servo().
constrain_int32()
int32_t constrain_int32 (const int32_t amt, const int32_t low, const int32_t high) inline
Definition at line 187 of file AP_Math.h.
Referenced by AP_Compass_BMM150::_compensate_z(), AP_Declination::get_mag_field_ef(), AP_OSD_ParamScreen::modify_parameter(), AP_MSP_Telem_Backend::msp_process_out_analog(), AP_MSP_Telem_Backend::msp_process_out_comp_gps(), SRV_Channels::set_output_pwm_chan_timeout(), TEST(), AP_Landing::type_slope_constrain_roll(), AP_Landing::type_slope_get_target_airspeed_cm(), SITL::SIM_BattMonitor_SMBus::update(), and AP_AutoTune::update_rmax().
constrain_int64()
int64_t constrain_int64 (const int64_t amt, const int64_t low, const int64_t high) inline
Definition at line 197 of file AP_Math.h.
Referenced by TEST().
constrain_uint16()
uint16_t constrain_uint16 (const uint16_t amt, const uint16_t low, const uint16_t high) inline
Definition at line 182 of file AP_Math.h.
Referenced by AP_ServoRelayEvents::do_repeat_servo(), AP_ServoRelayEvents::do_set_servo(), AP_Logger::get_max_num_logs(), and AP_MotorsHeli_Single::heli_motors_param_conversions().
constrain_uint32()
uint32_t constrain_uint32 (const uint32_t amt, const uint32_t low, const uint32_t high) inline
Definition at line 192 of file AP_Math.h.
Referenced by TEST(), and ChibiOS::GPIO::wait_pin().
constrain_uint64()
uint64_t constrain_uint64 (const uint64_t amt, const uint64_t low, const uint64_t high) inline
Definition at line 202 of file AP_Math.h.
constrain_value()
template<typename T > T constrain_value (const T amt, const T low, const T high)
Definition at line 294 of file AP_Math.cpp.
Referenced by constrain_double(), constrain_int16(), constrain_int32(), constrain_int64(), constrain_uint16(), constrain_uint32(), constrain_uint64(), TEST(), and TEST().
constrain_value_line()
template<typename T > T constrain_value_line (const T amt, const T low, const T high, uint32_t line)
Definition at line 267 of file AP_Math.cpp.
degF_to_Kelvin()
float degF_to_Kelvin (float temp_f)
Definition at line 494 of file AP_Math.cpp.
degrees()
static constexpr float degrees (float rad) inline static constexpr
Definition at line 219 of file AP_Math.h.
double_to_int32()
int32_t double_to_int32 (const double v)
Definition at line 527 of file AP_Math.cpp.
double_to_uint32()
uint32_t double_to_uint32 (const double v)
Definition at line 522 of file AP_Math.cpp.
expo_curve()
float expo_curve (float alpha, float input)
Definition at line 121 of file AP_Math.cpp.
Referenced by throttle_curve().
fill_nanf() [1/2]
void fill_nanf (double * f, uint16_t count)
Definition at line 447 of file AP_Math.cpp.
fill_nanf() [2/2]
void fill_nanf (float * f, uint16_t count)
Definition at line 424 of file AP_Math.cpp.
Referenced by fill_nanf_stack(), NavEKF_core_common::fill_scratch_variables(), and fill_stack_nan().
fixed2float()
float fixed2float (const uint16_t input, const uint8_t fractional_bits = 8)
Definition at line 472 of file AP_Math.cpp.
Referenced by TEST().
fixedwing_turn_rate()
float fixedwing_turn_rate (float bank_angle_deg, float airspeed)
Definition at line 487 of file AP_Math.cpp.
Referenced by TEST().
float2fixed()
uint16_t float2fixed (const float input, const uint8_t fractional_bits = 8)
Definition at line 478 of file AP_Math.cpp.
Referenced by TEST().
float_to_int16()
int16_t float_to_int16 (const float v)
Definition at line 502 of file AP_Math.cpp.
Referenced by AP_Frsky_Backend::calc_gps_position().
float_to_int32()
int32_t float_to_int32 (const float v)
Definition at line 507 of file AP_Math.cpp.
Referenced by SITL::IntelligentEnergy24::update_send().
float_to_int32_le()
int32_t float_to_int32_le (const float & value)
Definition at line 533 of file AP_Math.cpp.
float_to_uint16()
uint16_t float_to_uint16 (const float v)
Definition at line 512 of file AP_Math.cpp.
Referenced by AP_Frsky_Backend::calc_gps_position(), and AP_Frsky_Backend::calc_nav_alt().
float_to_uint32()
uint32_t float_to_uint32 (const float v)
Definition at line 517 of file AP_Math.cpp.
Referenced by SITL::IntelligentEnergy24::update_send().
get_random16()
uint16_t get_random16 (void)
Definition at line 332 of file AP_Math.cpp.
Referenced by apfs_tmpfile(), HALSITL::Util::get_random_vals(), AP_IOMCU_FW::heater_update(), FlashTest::loop(), rand_num(), and TEST().
get_vel_correction_for_sensor_offset()
Vector3F get_vel_correction_for_sensor_offset (const Vector3F & sensor_offset_bf, const Matrix3F & rot_ef_to_bf, const Vector3F & angular_rate)
Definition at line 388 of file AP_Math.cpp.
Referenced by NavEKF3_core::CorrectExtNavVelForSensorOffset(), NavEKF2_core::CorrectExtNavVelForSensorOffset(), and TEST().
hz_to_nsec()
constexpr uint32_t hz_to_nsec (uint32_t freq) inline constexpr
Definition at line 269 of file AP_Math.h.
Referenced by Linux::PWM_Sysfs_Base::set_freq(), and TEST().
hz_to_usec()
constexpr uint32_t hz_to_usec (uint32_t freq) inline constexpr
Definition at line 289 of file AP_Math.h.
Referenced by RCOutputRGBLed::hw_set_rgb(), Linux::PeriodicThread::set_rate(), and TEST().
int32_to_float_le()
float int32_to_float_le (const uint32_t & value)
Definition at line 545 of file AP_Math.cpp.
Referenced by be32tofloat_ptr().
is_equal() [1/2]
template<typename Arithmetic1 , typename Arithmetic2 > std::enable_if< std::is_integral< typenamestd::common_type< Arithmetic1, Arithmetic2 >::type >::value, bool >::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
Definition at line 14 of file AP_Math.cpp.
is_equal() [2/2]
template<typename Arithmetic1 , typename Arithmetic2 > std::enable_if< std::is_floating_point< typenamestd::common_type< Arithmetic1, Arithmetic2 >::type >::value, bool >::type is_equal (const Arithmetic1 v_1, const Arithmetic2 v_2)
Definition at line 14 of file AP_Math.cpp.
Referenced by AP_Baro_Backend::_copy_to_frontend(), AP_GeodesicGrid::_from_neighbor_umbrella(), GCS_MAVLINK::_handle_command_preflight_calibration(), AP_GPS_NMEA::_term_complete(), AP_InertialSensor::accel_calibrated_ok_all(), AP_MotorsHeli::arming_checks(), AP_TempCalibration::calculate_calibration(), AP_MotorsHeli_Dual::calculate_scalars(), AP_MotorsHeli_Quad::calculate_scalars(), AP_MotorsHeli_Single::calculate_scalars(), AC_Circle::check_param_change(), AP_Param::convert_old_parameter(), AP_OADatabase::database_item_refresh(), AC_AutoTune_Heli::do_gcs_announcements(), AC_AutoTune_Heli::do_post_test_gcs_announcements(), AC_AutoTune_Heli::dwell_test_init(), AC_AutoTune_Heli::dwell_test_run(), AP_MSP_Telem_DJI::get_rssi(), AP_Camera::handle_command(), GCS_MAVLINK::handle_command_do_set_home(), GCS_MAVLINK::handle_command_int_packet(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_calibration_baro(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_reboot(), GCS_MAVLINK::handle_command_request_autopilot_capabilities(), GCS_MAVLINK::handle_control_high_latency(), GCS_MAVLINK::handle_param_set(), GCS_MAVLINK::handle_preflight_reboot(), AC_Circle::init_start_angle(), NotchFilter< T >::init_with_A_and_Q(), Vector2< T >::operator!=(), Vector3< T >::operator!=(), Vector2< T >::operator==(), Vector3< T >::operator==(), AP_Filesystem_Param::pack_param(), AC_AutoTune_Heli::reset_vehicle_test_variables(), AP_OABendyRuler::resist_bearing_change(), AP_AutoTune::save_float_if_changed(), AP_Param::save_sync(), AP_OABendyRuler::search_vertical_path(), SCurve::set_destination_speed_max(), AP_Proximity_Boundary_3D::set_filtered_distance(), HALSITL::SITL_State::set_height_agl(), SCurve::set_origin_speed_max(), AC_Circle::set_rate(), SCurve::set_speed_max(), setup(), SITL::Gripper_Servo::should_report(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), AC_AutoTune_Heli::test_init(), AC_AutoTune_Multi::twitching_abort_rate(), SITL::TSYS01::update(), SITL::TSYS03::update(), Chirp::update(), AP_InertialSensor::HarmonicNotch::update_params(), AR_WPNav::update_speed_max(), AP_MotorsMulticopter::update_throttle_filter(), AP_L1_Control::update_waypoint(), AC_WPNav::update_wpnav(), AC_AutoTune_Heli::updating_angle_p_up(), AC_AutoTune_Heli::updating_max_gains(), AC_AutoTune_Heli::updating_rate_d_up(), AC_AutoTune_Heli::updating_rate_p_up(), and AP_Logger::validate_structures().
is_negative() [1/2]
bool is_negative (const double fVal1) inline
Definition at line 90 of file AP_Math.h.
is_negative() [2/2]
template<typename T > bool is_negative (const T fVal1) inline
Definition at line 74 of file AP_Math.h.
Referenced by AP_TECS::_update_height_demand(), AC_Avoid::adjust_speed(), AC_Avoid::adjust_velocity_polygon(), AC_Avoid::adjust_velocity_proximity(), DigitalLPF< T >::apply(), AC_Loiter::calc_desired_velocity(), SITL::Sailboat::calc_lift_and_drag(), calc_lowpass_alpha_dt(), SCurve::calculate_path(), AP_RangeFinder_NMEA::decode_latest_term(), AP_WindVane_NMEA::decode_latest_term(), AC_AttitudeControl::euler_accel_limit(), AC_Avoid::find_max_quadrant_velocity(), AC_Avoid::find_max_quadrant_velocity_3D(), AP_RangeFinder_LightWareSerial::get_reading(), AP_MotorsUGV::get_scaled_throttle(), AC_PosControl::get_throttle_with_vibration_override(), AR_AttitudeControl::get_turn_rate_from_lat_accel(), AC_WeatherVane::get_yaw_out(), AP_Camera::handle_command(), inv_sqrt_controller(), AC_Avoid::limit_velocity_3D(), AP_MotorsUGV::output_regular(), AP_MotorsUGV::output_skid_steering(), AP_MotorsUGV::output_throttle(), AC_AttitudeControl::pre_arm_checks(), print_all_motor_matrix(), AP_Winch::release_length(), AC_P_1D::set_error_limits(), AC_P_1D::set_limits(), AC_PosControl::set_max_speed_accel_z(), SCurve::set_speed_max(), shape_pos_vel_accel(), shape_pos_vel_accel_xy(), shape_vel_accel(), sqrt_controller(), TEST(), AP_WindVane::update(), SITL::Sailboat::update(), AC_P_1D::update_all(), AC_PID_Basic::update_all(), AC_PID::update_i(), AC_PID_Basic::update_i(), SITL::Gripper_EPM::update_servobased(), AP_WindVane_ModernDevice::update_speed(), update_vel_accel(), update_vel_accel_xy(), AC_PosControl::update_xy_controller(), and SCurve::valid().
is_positive() [1/2]
bool is_positive (const double fVal1) inline
Definition at line 83 of file AP_Math.h.
is_positive() [2/2]
template<typename T > bool is_positive (const T fVal1) inline
Definition at line 63 of file AP_Math.h.
Referenced by AP_Airspeed_SDP3X::_correct_pressure(), GCS_MAVLINK::_handle_command_preflight_calibration(), HALSITL::SITL_State::_update_airspeed(), SCurve::add_segment_const_jerk(), SCurve::add_segment_decr_jerk(), SCurve::add_segment_incr_jerk(), AC_Avoid::adjust_velocity(), AR_WPNav::advance_wp_target_along_track(), AC_WPNav::advance_wp_target_along_track(), DigitalBiquadFilter< T >::apply(), Thrust_Linearization::apply_thrust_curve_and_volt_scaling(), AP_BattMonitor_Backend::arming_checks(), AP_Arming::board_voltage_checks(), AC_Avoid::calc_backup_velocity_3D(), AP_GPS::calc_blend_weights(), SplineCurve::calc_dt_speed_max(), SCurve::calc_javp_for_segment_decr_jerk(), SCurve::calc_javp_for_segment_incr_jerk(), SRV_Channels::calc_pwm(), AC_WPNav::calc_scurve_jerk_and_snap(), SCurve::calculate_path(), SCurve::calculate_track(), AC_PosControl::calculate_yaw_and_rate_yaw(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), DigitalBiquadFilter< T >::compute_params(), NavEKF3_core::EKFGSF_getYaw(), NavEKF2_core::EKFGSF_resetMainFilterYaw(), AC_Avoid::find_max_quadrant_velocity(), AC_Avoid::find_max_quadrant_velocity_3D(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), AC_Loiter::get_angle_max_cd(), AC_WPNav::get_corner_acceleration(), AR_AttitudeControl::get_decel_max(), AR_AttitudeControl::get_desired_speed_accel_limited(), get_EAS2TAS(), AP_Baro::get_EAS2TAS(), AC_PI_2D::get_i(), AC_PI_2D::get_i_shrink(), AC_PosControl::get_lean_angle_max_cd(), RC_Channels::get_override_timeout_ms(), AC_Circle::get_radius(), AP_MotorsUGV::get_rate_controlled_throttle(), AR_AttitudeControl::get_sail_out_from_heel(), SRV_Channels::get_slew_limited_output_scaled(), AC_AttitudeControl::get_slew_yaw_max_degs(), AR_AttitudeControl::get_steering_out_rate(), AR_WPNav::get_stopping_location(), AC_PosControl::get_stopping_point_xy_cm(), AC_PosControl::get_stopping_point_z_cm(), AP_Follow::get_target_dist_and_vel_ned(), AR_AttitudeControl::get_throttle_out_speed(), AC_PosControl::get_throttle_with_vibration_override(), AR_AttitudeControl::get_turn_rate_from_heading(), AC_WPNav::get_wp_acceleration(), AC_WeatherVane::get_yaw_out(), AP_MotorsUGV::have_vectored_thrust(), AP_SmartRTL::init(), AR_WPNav::init(), NotchFilter< T >::init_with_A_and_Q(), NavEKF2::InitialiseFilter(), NavEKF3::InitialiseFilter(), AC_PosControl::input_pos_xyz(), AC_AttitudeControl::input_shaping_ang_vel(), AC_AttitudeControl::input_shaping_angle(), inv_sqrt_controller(), kinematic_limit(), AC_Avoid::limit_accel(), limit_accel_xy(), Vector2< T >::limit_length(), Vector3< T >::limit_length_xy(), AC_Avoid::limit_velocity_3D(), AC_AttitudeControl::max_rate_step_bf_pitch(), AC_AttitudeControl::max_rate_step_bf_roll(), AC_AttitudeControl::max_rate_step_bf_yaw(), SlewLimiter::modifier(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsUGV::output_regular(), AP_MotorsUGV::output_skid_steering(), AC_AttitudeControl::pre_arm_checks(), AC_PosControl::pre_arm_checks(), EKFGSF_yaw::predictAHRS(), print_all_motor_matrix(), AP_GPS_SBF::process_message(), AC_AutoTune_Heli::rate_ff_test_run(), NavEKF3_core::readAirSpdData(), SITL::JSON::recv_fdm(), AC_PID::relax_integrator(), AC_PosControl::relax_velocity_controller_xy(), Thrust_Linearization::remove_thrust_curve_and_volt_scaling(), AP_OABendyRuler::resist_bearing_change(), NavEKF2_core::runYawEstimatorPrediction(), AP_Mount_Siyi::send_camera_settings(), AP_MotorsMulticopter::set_actuator_with_slew(), SITL::Battery::set_current(), AC_P_1D::set_error_limits(), AC_P_2D::set_error_max(), AC_P_2D::set_limits(), AC_P_1D::set_limits(), AC_PosControl::set_max_speed_accel_xy(), AC_PosControl::set_max_speed_accel_z(), SRV_Channels::set_slew_rate(), SCurve::set_speed_max(), AC_WPNav::set_speed_xy(), AP_Mount_Siyi::set_zoom(), shape_accel(), shape_accel_xy(), shape_pos_vel_accel(), shape_pos_vel_accel_xy(), shape_vel_accel(), shape_vel_accel_xy(), AP_Logger_RateLimiter::should_log(), AP_Logger_RateLimiter::should_log_streaming(), AC_PosControl::soften_for_landing_xy(), sqrt_controller(), sqrt_controller(), AP_AutoTune::start(), AP_AutoTune::stop(), TEST(), AP_WindVane::update(), SITL::Blimp::update(), SITL::FlightAxis::update(), SITL::Sailboat::update(), SlewCalculator2D::update(), EKFGSF_yaw::update(), AC_Circle::update(), AC_AutoTune_FreqResp::update(), SpeedToFly::update(), AP_AutoTune::update(), AP_Baro::update(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_UPFLOW::update(), AC_PID_2D::update_all(), AC_P_1D::update_all(), AC_PID_Basic::update_all(), AC_PID::update_all(), AC_PID_Basic::update_all(), AC_P_2D::update_all(), AP_DAL_InertialSensor::update_filtered(), AP_InertialSensor::HarmonicNotch::update_freq_hz(), AP_InertialSensor::HarmonicNotch::update_frequencies_hz(), AC_PID::update_i(), AC_PID_Basic::update_i(), AC_PID_2D::update_i(), update_pos_vel_accel(), update_pos_vel_accel_xy(), AP_BattMonitor_Backend::update_resistance_estimate(), AP_AutoTune::update_rmax(), SITL::Helicopter::update_rpm(), AP_WindVane_ModernDevice::update_speed(), update_vel_accel(), update_vel_accel_xy(), EKFGSF_yaw::updateRotMat(), AC_AutoTune_Heli::updating_rate_ff_up(), AP_Baro::wind_pressure_correction(), and AC_WPNav::wp_and_spline_init().
is_zero()
template<typename T > bool is_zero (const T fVal1) inline
Definition at line 53 of file AP_Math.h.
Referenced by OpticalFlow_backend::_applyYaw(), AP_GPS_SBP2::_attempt_state_update(), AP_InertialSensor::_calculate_trim(), AP_GeodesicGrid::_from_neighbor_umbrella(), AP_TECS::_get_i_gain(), HALSITL::SITL_State::_simulator_servos(), HALSITL::SITL_State::_sonar_pin_voltage(), AP_GeodesicGrid::_subtriangle_index(), AP_GeodesicGrid::_triangle_index(), AP_Compass_AK09916::_update(), AP_Compass_AK8963::_update(), AP_Compass_LSM9DS1::_update(), HALSITL::SITL_State::_update_airspeed(), AP_TECS::_update_pitch(), AP_TECS::_update_throttle_with_airspeed(), AP_InertialSensor::accel_calibrated_ok_all(), AC_AttitudeControl::accel_limiting(), AP_MotorsUGV::active(), SCurve::add_segments(), SRV_Channels::adjust_trim(), AC_Avoid::adjust_velocity(), AC_Avoid::adjust_velocity_polygon(), AC_Avoid::adjust_velocity_proximity(), AC_Avoid::adjust_velocity_z(), SCurve::advance_target_along_track(), AC_WPNav::advance_wp_target_along_track(), AC_AttitudeControl::ang_vel_limit(), AC_AttitudeControl::ang_vel_to_euler_rate(), DigitalLPF< T >::apply(), Thrust_Linearization::apply_thrust_curve_and_volt_scaling(), AC_AttitudeControl::attitude_from_thrust_vector(), AC_AutoTune_Multi::backup_gains_and_initialise(), AC_Avoid::calc_backup_velocity_3D(), AC_Loiter::calc_desired_velocity(), SplineCurve::calc_dt_speed_max(), AC_PI_2D::calc_filt_alpha(), calc_lowpass_alpha_dt(), AP_OpticalFlow_Calibrator::calc_sample_best_scalar(), AP_OpticalFlow_Calibrator::calc_scalars(), AC_WPNav::calc_scurve_jerk_and_snap(), AP_AHRS::calc_trig(), SITL::Motor::calculate_forces(), AC_PosControl::calculate_overspeed_gain(), AP_TempCalibration::calculate_p_range(), SCurve::calculate_path(), SCurve::calculate_track(), AC_PrecLand::check_if_sensor_in_range(), AP_Vehicle::check_motor_noise(), Compass::configured(), AC_PosControl::crosstrack_error(), Vector3< T >::distance_to_segment(), AP_OSD_ParamScreen::draw_parameter(), AC_AutoTune_Heli::dwell_test_run(), AC_AttitudeControl::euler_accel_limit(), SITL::FlightAxis::exchange_data(), AP_Compass_Backend::field_ok(), QuaternionT< T >::from_axis_angle(), QuaternionT< T >::from_axis_angle(), QuaternionT< T >::from_axis_angle_fast(), AC_Circle::get_closest_point_on_circle(), AP_MotorsMulticopter::get_current_limit_max_throttle(), get_EAS2TAS(), AP_Baro::get_EAS2TAS(), AP_Baro::get_ground_temperature(), AC_PI_2D::get_i(), AC_PI_2D::get_i_shrink(), AP_Scheduler::get_loop_period_s(), AC_Avoid::get_max_speed(), AP_Beacon::get_origin(), RC_Channels::get_override_timeout_ms(), AP_MotorsUGV::get_scaled_throttle(), AP_SteerController::get_steering_out_rate(), AC_Avoid::get_stopping_distance(), AR_AttitudeControl::get_stopping_distance(), AP_Follow::get_target_dist_and_vel_ned(), AR_AttitudeControl::get_throttle_out_stop(), SITL::Sailboat::get_turn_circle(), SITL::Sailboat::get_yaw_rate(), SITL::Plane::getForce(), SITL::Plane::getTorque(), AP_OSD_ParamSetting::guess_ranges(), AP_Camera::handle_command(), AP_Mount_Backend::handle_command_do_mount_control(), GCS_MAVLINK::handle_command_do_set_home(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_reboot(), SITL::EFI_Hirth::init(), HarmonicNotchFilter< T >::init(), AP_Baro::init(), NotchFilter< T >::init_with_A_and_Q(), inv_sqrt_controller(), inverse3x3(), inverse4x4(), is_zero(), QuaternionT< T >::is_zero(), Vector2< T >::is_zero(), kinematic_limit(), AP_TempCalibration::learn_calibration(), AC_Avoid::limit_accel(), AC_Avoid::limit_velocity_3D(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Heli::load_test_gains(), AC_AutoTune_Heli::load_tuned_gains(), AC_AutoTune_Multi::load_tuned_gains(), AP_L1_Control::loiter_radius(), MOVESET(), AP_MotorsMatrix::normalise_rpy_factors(), QuaternionT< T >::normalize(), QuaternionT< T >::operator/(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_MotorsMulticopter::output_logic(), AP_MotorsUGV::output_regular(), Vector3< T >::point_on_line_closest_to_other_point(), AC_PosControl::pos_offset_z_scaler(), AP_Baro_Backend::pressure_ok(), AP_OADatabase::queue_push(), Thrust_Linearization::remove_thrust_curve_and_volt_scaling(), SITL::Morse::report_FPS(), SITL::FlightAxis::report_FPS(), AC_PrecLand::retrieve_los_meas(), QuaternionT< T >::rotate_fast(), AC_AutoTune::run(), AP_Scheduler::run(), AC_AutoTune_Heli::save_tuning_gains(), AC_AutoTune_Multi::save_tuning_gains(), AP_RSSI::scale_and_constrain_float_rssi(), SITL::ADSB_Sagetech_MXS::scaled_groundspeed(), Vector2< T >::segment_intersection(), Vector3< T >::segment_plane_intersect(), AP_SmartRTL::segment_segment_dist(), Vector3< T >::segment_to_segment_closest_point(), Linux::ToneAlarm::set_buzzer_tone(), Linux::ToneAlarm_Disco::set_buzzer_tone(), AP_OSD_ParamSetting::set_by_name(), SITL::SIM_Precland::set_default_location(), AC_P_1D::set_error_limits(), AC_P_2D::set_error_max(), SplineCurve::set_origin_and_destination(), SCurve::set_speed_max(), AC_WPNav::set_wp_destination(), setup(), SITL::Motor::setup_params(), AP_Logger_RateLimiter::should_log(), SITL::Sprayer::should_report(), sqrt_controller(), TEST(), TEST(), TEST(), AC_AutoTune_Heli::test_init(), AC_AttitudeControl::thrust_heading_rotation_angles(), AC_AttitudeControl::thrust_vector_rotation_angles(), QuaternionT< T >::to_axis_angle(), AP_JSON::value::to_str(), AP_Landing::type_slope_setup_landing_glide_slope(), AP_AHRS_View::update(), SITL::SIM_GeneratorEngine::update(), SITL::SIM_Precland::update(), SITL::FlightAxis::update(), SITL::Sailboat::update(), AC_Circle::update(), AC_AutoTune_FreqResp::update(), AP_RPM_Pin::update(), AP_WheelEncoder_SITL_Quadrature::update(), AC_AttitudeControl_Multi::update_althold_lean_angle_max(), AC_AttitudeControl_Sub::update_althold_lean_angle_max(), AC_AttitudeControl::update_ang_vel_target_from_att_error(), AP_Mount_Servo::update_angle_outputs(), AP_Baro::update_field_elevation(), AP_Baro_Backend::update_healthy_flag(), AC_PID::update_i(), AC_PID_Basic::update_i(), AC_HELI_PID::update_leaky_i(), update_pos_vel_accel_xy(), AP_BattMonitor_Backend::update_resistance_estimate(), AR_WPNav::update_steering_and_speed(), SITL::Sailboat::update_wave(), AP_Mount_Siyi::update_zoom_control(), AC_AutoTune_Heli::updating_angle_p_up(), AC_AutoTune_Heli::updating_max_gains(), AC_AutoTune_Heli::updating_max_gains_all(), AC_AutoTune_Heli::updating_rate_d_up(), AC_AutoTune_Heli::updating_rate_ff_up(), AC_AutoTune_Heli::updating_rate_p_up(), AP_Airspeed::use(), SCurve::valid(), and wgsecef2llh().
linear_interpolate()
float linear_interpolate (float low_output, float high_output, float var_value, float var_low, float var_high)
Definition at line 98 of file AP_Math.cpp.
Referenced by AP_TECS::_update_speed_demand(), SITL::Sailboat::calc_lift_and_drag(), AP_Tuning::check_input(), AP_MotorsUGV::output_skid_steering(), AP_Mount_Siyi::send_camera_settings(), AP_Mount_Siyi::set_zoom(), TEST(), throttle_curve(), AP_AutoTune::update(), AP_WindVane_Analog::update_direction(), SITL::IntelligentEnergy24::update_send(), and AC_AutoTune_Heli::updating_max_gains().
mat_identity()
template<typename T > void mat_identity (T * x, uint16_t dim)
Definition at line 461 of file matrix_alg.cpp.
Referenced by test_matrix_inverse().
mat_inverse()
template<typename T > bool mat_inverse (const T * x, T * y, uint16_t dim)
Referenced by PolyFit< order, xtype, vtype >::get_polynomial(), AccelCalibrator::run_fit(), and test_matrix_inverse().
mat_mul()
template<typename T > void mat_mul (const T * A, const T * B, T * C, uint16_t n)
Definition at line 448 of file matrix_alg.cpp.
Referenced by test_matrix_inverse().
MAX()
template<typename A , typename B > static auto MAX (const A & one, const B & two) -> decltype(one > two ? one : two) inline static
Definition at line 264 of file AP_Math.h.
MIN()
template<typename A , typename B > static auto MIN (const A & one, const B & two) -> decltype(one < two ? one : two) inline static
Definition at line 257 of file AP_Math.h.
norm()
template<typename T , typename U , typename... Params> ftype norm (const T first, const U second, const Params... parameters)
Definition at line 250 of file AP_Math.h.
Referenced by AP_InertialSensor::_calculate_trim(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::FuseAirspeed(), AP_Mount_Backend::get_angle_target_to_location(), Location::get_distance(), Vector2< T >::length(), Vector3< T >::length(), Vector3< T >::limit_length_xy(), AP_MotorsHeli_Single::move_actuators(), AP_GPS_NOVA::process_message(), SITL::InertialLabs::send_packet(), SITL::ADSB::send_report(), TEST(), TEST(), Airspeed_Calibration::update(), and AP_WheelEncoder_SITL_Quadrature::update().
nsec_to_hz()
constexpr uint32_t nsec_to_hz (uint32_t nsec) inline constexpr
Definition at line 274 of file AP_Math.h.
Referenced by Linux::PWM_Sysfs_Base::get_freq(), and TEST().
nsec_to_usec()
constexpr uint32_t nsec_to_usec (uint32_t nsec) inline constexpr
Definition at line 284 of file AP_Math.h.
Referenced by Linux::RCOutput_Sysfs::read(), and TEST().
radians()
static constexpr ftype radians (ftype deg) inline static constexpr
Definition at line 213 of file AP_Math.h.
Referenced by AP_InertialSensor::_acal_save_calibrations(), AP_InertialSensor::_calculate_trim(), SITL::Calibration::_calibration_poses(), AP_InertialSensor_BMI160::_configure_gyro(), AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), HALSITL::SITL_State::_output_to_flightgear(), AP_GPS_NMEA::_term_complete(), AP_TECS::_update_pitch(), AP_TECS::_update_throttle_without_airspeed(), OpticalFlow_backend::_yawAngleRad(), AP_MotorsMatrix::add_motor(), AP_MotorsHeli_Swash::add_servo_angle(), angle_to_accel(), AP_AHRS_View::AP_AHRS_View(), AC_AttitudeControl::attitude_controller_run_quat(), SITL::SimRover::calc_lat_accel(), NavEKF2_core::calcEarthRateNED(), NavEKF3_core::calcEarthRateNED(), NavEKF3_core::calcTiltErrorVariance(), SITL::Motor::calculate_forces(), SITL::Blimp::calculate_forces(), AP_MotorsHeli_Quad::calculate_roll_pitch_collective_factors(), AP_InertialSensor_ADIS1647x::check_product_id(), NavEKF3_core::checkAttitudeAlignmentStatus(), NavEKF2_core::checkGyroCalStatus(), NavEKF3_core::checkGyroCalStatus(), AP_Beacon_Backend::correct_for_orient_yaw(), NavEKF2_core::CovarianceInit(), NavEKF3_core::CovarianceInit(), NavEKF3_core::CovariancePrediction(), AP_OSD_Screen::draw_horizon(), NavEKF3_core::EKFGSF_getYaw(), NavEKF2_core::EKFGSF_resetMainFilterYaw(), AP_GPS_Backend::fill_3d_velocity(), fixedwing_turn_rate(), NavEKF2_core::fuseEulerYaw(), AP_InertialSensor_NONE::generate_accel(), AP_InertialSensor_NONE::generate_gyro(), AC_AttitudeControl::get_accel_pitch_max_radss(), AC_AttitudeControl::get_accel_roll_max_radss(), AC_AttitudeControl::get_accel_yaw_max_radss(), AC_AttitudeControl::get_ang_vel_pitch_max_rads(), AC_AttitudeControl::get_ang_vel_roll_max_rads(), AC_AttitudeControl::get_ang_vel_yaw_max_rads(), AP_Mount_Alexmos::get_attitude_quaternion(), AP_Mount_Servo::get_attitude_quaternion(), AP_Mount_SToRM32_serial::get_attitude_quaternion(), SITL::ShipSim::get_ground_speed_adjustment(), SITL::Sailboat::get_lat_accel(), AC_Avoid::get_proximity_roll_pitch_pct(), AP_YawController::get_rate_out(), AP_Mount_Backend::get_rc_target(), AC_AttitudeControl_Heli::get_roll_trim_rad(), AC_AttitudeControl::get_slew_yaw_max_rads(), AR_AttitudeControl::get_steering_out_rate(), SITL::Sailboat::get_turn_circle(), AR_AttitudeControl::get_turn_rate_from_heading(), AR_PivotTurn::get_turn_rate_rads(), NavEKF3_core::getEarthFieldTable(), AP_InertialSensor::gyros_consistent(), SITL::Helicopter::Helicopter(), AP_OADatabase::init(), AP_CustomRotation::init(), AC_Loiter::init_target(), AC_AttitudeControl::input_angle_step_bf_roll_pitch_yaw(), AC_AttitudeControl::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl_Sub::input_euler_angle_roll_pitch_slew_yaw(), AC_AttitudeControl::input_euler_angle_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_2(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_3(), AC_AttitudeControl::input_shaping_rate_predictor(), AC_AttitudeControl::input_thrust_vector_heading(), AC_AttitudeControl::input_thrust_vector_rate_heading(), NavEKF2_core::learnInactiveBiases(), NavEKF3_core::learnInactiveBiases(), AP_L1_Control::loiter_radius(), SITL::Motor::Motor(), SITL::Motor::Motor(), AP_L1_Control::nav_roll_cd(), Location::offset_bearing(), Vector2< T >::offset_bearing(), Vector3< T >::offset_bearing(), Location::offset_bearing_and_pitch(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsUGV::output_regular(), SITL::Morse::output_rover_regular(), SITL::Morse::output_rover_skid(), AP_InertialSensor_BMI270::parse_gyro_frame(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), EKFGSF_yaw::predictAHRS(), AP_Mount_Siyi::process_packet(), SITL::SilentWings::process_packet(), AC_AttitudeControl::rate_bf_pitch_target(), AC_AttitudeControl::rate_bf_roll_target(), AC_AttitudeControl::rate_bf_yaw_target(), rc_input_to_roll_pitch(), AP_InertialSensor_BMI055::read_fifo_gyro(), AP_InertialSensor_BMI088::read_fifo_gyro(), AP_InertialSensor_SCHA63T::read_gyro(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsYawData(), NavEKF3_core::realignYawGPS(), SITL::XPlane::receive_data(), AP_InertialSensor::register_gyro(), NavEKF2_core::resetGyroBias(), NavEKF3_core::resetGyroBias(), AC_PrecLand::retrieve_los_meas(), AP_Follow::rotate_vector(), SITL::JSON_Master::send(), AP_Mount_Backend::send_gimbal_manager_information(), SITL::MicroStrain::send_imu_packet(), SITL::VectorNav::send_packet1(), SITL::ShipSim::send_report(), SITL::JSBSim::send_servos(), AP_Mount_Siyi::send_target_angles(), AP_Mount_Backend::set_angle_target(), Compass::set_declination(), AC_Loiter::set_pilot_desired_acceleration(), AP_AHRS_View::set_pitch_trim(), AP_Mount_Backend::set_rate_target(), AC_AttitudeControl_Heli::set_throttle_out(), SITL::Motor::setup_params(), NavEKF3_core::setWindMagStateLearningMode(), AP_InertialSensor_Invensense::start(), TEST(), TEST(), TEST(), TEST(), test_euler(), test_euler(), Compass::try_set_initial_location(), SITL::SimRover::turn_circle(), AP_WindVane_NMEA::update(), SITL::InvensenseV3::update(), Variometer::update(), SITL::BalanceBot::update(), SITL::Balloon::update(), SITL::Blimp::update(), SITL::FlightAxis::update(), SITL::SimRover::update(), SITL::Sailboat::update(), SITL::SingleCopter::update(), SITL::Tracker::update(), SITL::Ship::update(), AP_WheelEncoder_SITL_Quadrature::update(), AP_Mount_Servo::update_angle_outputs(), AP_Mount_Backend::update_angle_target_from_rate(), AP_WindVane::update_apparent_wind_dir_from_true(), AP_WindVane_Analog::update_direction(), AP_WindVane_Home::update_direction(), AP_L1_Control::update_heading_hold(), AP_TECS::update_pitch_throttle(), AP_WindVane::update_true_wind_speed_and_direction(), SITL::Vicon::update_vicon_position_estimate(), SITL::Sailboat::update_wave(), AP_L1_Control::update_waypoint(), NavEKF3_core::updateMovementCheck(), NavEKF3_core::verifyTiltErrorVariance(), AP_AHRS::wind_alignment(), and NavEKF3_core::writeExtNavData().
rand_float()
float rand_float (void)
Referenced by HALSITL::SITL_State::_sonar_pin_voltage(), HALSITL::SITL_State::_update_airspeed(), HALSITL::UARTDriver::_write(), SITL::MS5525::get_pressure_temperature_readings(), SITL::MS5611::get_pressure_temperature_readings(), SITL::TSYS01::get_sim_temperature(), SITL::MicroStrain::send_imu_packet(), SITL::InertialLabs::send_packet(), SITL::VectorNav::send_packet1(), and SITL::Airspeed_DLVR::update().
rand_vec3f()
Vector3f rand_vec3f (void)
rotation_equal()
bool rotation_equal (enum Rotation r1, enum Rotation r2)
Definition at line 368 of file AP_Math.cpp.
Referenced by TEST(), and test_rotation_duplicates().
safe_asin()
template<typename T > float safe_asin (const T v)
Definition at line 50 of file AP_Math.cpp.
Referenced by QuaternionT< T >::get_euler_pitch(), AP_MotorsHeli_Swash::get_linear_servo_output(), AP_MotorsTri::output_armed_stabilizing(), TEST(), TEST(), Matrix3< T >::to_euler(), and AP_AHRS::update_AOA_SSA().
safe_sqrt()
template<typename T > float safe_sqrt (const T v)
Definition at line 71 of file AP_Math.cpp.
Referenced by AP_InertialSensor::_acal_save_calibrations(), AP_GPS_SBP2::_attempt_state_update(), Thrust_Linearization::apply_thrust_curve_and_volt_scaling(), SplineCurve::calc_dt_speed_max(), AP_AHRS::calc_trig(), AC_Circle::calc_velocities(), SCurve::calculate_path(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), AC_AttitudeControl::control_monitor_rms_output_pitch(), AC_AttitudeControl::control_monitor_rms_output_pitch_D(), AC_AttitudeControl::control_monitor_rms_output_pitch_P(), AC_AttitudeControl::control_monitor_rms_output_roll(), AC_AttitudeControl::control_monitor_rms_output_roll_D(), AC_AttitudeControl::control_monitor_rms_output_roll_P(), AC_AttitudeControl::control_monitor_rms_output_yaw(), AC_PosControl::crosstrack_error(), Vector3< T >::distance_to_segment(), AC_AutoTune_Heli::dwell_test_run(), AC_Avoid::get_max_speed(), AP_MotorsUGV::get_scaled_throttle(), SlewCalculator2D::get_slew_rate(), AP_Follow::get_target_dist_and_vel_ned(), AR_AttitudeControl::get_turn_rate_from_heading(), AP_InertialSensor::get_vibration_levels(), limit_accel_xy(), AC_PosControl::set_max_speed_accel_xy(), shape_vel_accel_xy(), sqrt_controller(), TEST(), TEST(), SITL::SIM_Precland::update(), SITL::Sailboat::update(), and AR_PosControl::update().
sq() [1/3]
static constexpr float sq (const float val) inline static constexpr
Definition at line 230 of file AP_Math.h.
sq() [2/3]
template<typename T , typename... Params> ftype sq (const T first, const Params... parameters)
Definition at line 240 of file AP_Math.h.
sq() [3/3]
template<typename T > ftype sq (const T val)
Definition at line 225 of file AP_Math.h.
Referenced by AP_InertialSensor::_acal_save_calibrations(), AP_Baro_MS56XX::_calculate_5607(), AP_Baro_MS56XX::_calculate_5611(), AP_Baro_MS56XX::_calculate_5637(), AP_Airspeed_SDP3X::_correct_pressure(), HALSITL::SITL_State::_update_airspeed(), AP_SmartRTL::add_point(), SCurve::add_segment_const_jerk(), SCurve::add_segment_decr_jerk(), SCurve::add_segment_incr_jerk(), AC_WPNav::advance_wp_target_along_track(), NavEKF3_core::alignYawAngle(), AP_GPS::calc_blend_weights(), SplineCurve::calc_dt_speed_max(), AccelCalibrator::calc_mean_squared_residuals(), AP_OpticalFlow_Calibrator::calc_mean_squared_residuals(), SplineCurve::calc_target_pos_vel(), SITL::Motor::calc_thrust(), NavEKF2_core::calcOutputStates(), NavEKF3_core::calcOutputStates(), NavEKF2_core::calcQuatAndFieldStates(), NavEKF3_core::calcTiltErrorVariance(), SITL::Plane::calculate_forces(), AP_TempCalibration::calculate_p_range(), SCurve::calculate_path(), NavEKF3_core::CalculateVelInnovationsAndVariances(), NavEKF3_core::checkAttitudeAlignmentStatus(), NavEKF2_core::checkGyroCalStatus(), NavEKF3_core::checkGyroCalStatus(), NavEKF2_core::ConstrainVariances(), NavEKF3_core::ConstrainVariances(), AC_AttitudeControl::control_monitor_filter_pid(), SITL::MS5611::convert(), SITL::MS5611::convert_forward(), NavEKF2_core::correctEkfOriginHeight(), NavEKF3_core::correctEkfOriginHeight(), NavEKF2_core::CovarianceInit(), NavEKF3_core::CovarianceInit(), NavEKF2_core::CovariancePrediction(), NavEKF3_core::CovariancePrediction(), AC_PosControl::crosstrack_error(), NavEKF2_core::detectFlight(), NavEKF3_core::detectFlight(), NavEKF3_core::EKFGSF_getYaw(), NavEKF2_core::EKFGSF_resetMainFilterYaw(), NavEKF2_core::EstimateTerrainOffset(), NavEKF3_core::EstimateTerrainOffset(), QuaternionT< T >::from_axis_angle_fast(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::FuseAirspeed(), NavEKF2_core::FuseDeclination(), NavEKF3_core::FuseDeclination(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), NavEKF2_core::FuseMagnetometer(), NavEKF3_core::FuseMagnetometer(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), NavEKF2_core::FuseSideslip(), NavEKF3_core::FuseSideslip(), EKFGSF_yaw::fuseVelData(), NavEKF2_core::FuseVelPosNED(), NavEKF3_core::FuseVelPosNED(), AP_Baro::get_air_density_ratio(), SlewCalculator2D::get_slew_rate(), AC_Avoid::get_stopping_distance(), AR_AttitudeControl::get_stopping_distance(), AP_Follow::get_target_dist_and_vel_ned(), EKFGSF_yaw::getVelInnovLength(), NavEKF2_core::healthy(), NavEKF3_core::healthy(), SITL::Helicopter::Helicopter(), NotchFilter< T >::init_with_A_and_Q(), NavEKF3_core::InitialiseVariables(), inv_sqrt_controller(), AP_OADatabase::is_close_to_item_in_database(), QuaternionT< T >::length(), limit_accel_xy(), Location::line_path_proportion(), AP_L1_Control::loiter_radius(), SCurve::move_from_pos_vel_accel(), SCurve::move_to_pos_vel_accel(), norm(), AP_Beacon_Nooploop::parse_node_frame2(), Polygon_closest_distance_line(), Polygon_intersects(), EKFGSF_yaw::predict(), EKFGSF_yaw::predictAHRS(), AP_BattMonitor_Synthetic_Current::read(), NavEKF3_core::readAirSpdData(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), EKFGSF_yaw::resetEKFGSF(), NavEKF2_core::resetGyroBias(), NavEKF3_core::resetGyroBias(), NavEKF2_core::ResetHeight(), NavEKF3_core::ResetHeight(), NavEKF3_core::resetMagFieldStates(), NavEKF3_core::ResetPosition(), NavEKF2_core::ResetPosition(), NavEKF3_core::ResetVelocity(), NavEKF2_core::ResetVelocity(), QuaternionT< T >::rotate_fast(), AC_PrecLand::run_estimator(), NavEKF2_core::SelectFlowFusion(), NavEKF3_core::SelectFlowFusion(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), NavEKF2_core::SelectMagFusion(), NavEKF3_core::SelectMagFusion(), SITL::InertialLabs::send_packet(), NavEKF2_core::setAidingMode(), NavEKF3_core::setAidingMode(), setup(), NavEKF2_core::setWindMagStateLearningMode(), NavEKF3_core::setWindMagStateLearningMode(), NavEKF3_core::setYawFromMag(), shape_vel_accel_xy(), sq(), sqrt_controller(), TEST(), TEST(), TEST(), QuaternionT< T >::to_axis_angle(), AP_L1_Control::turn_distance(), SITL::Helicopter::update(), SITL::Sailboat::update(), EKFGSF_yaw::update(), Airspeed_Calibration::update(), AP_Airspeed::update_calibration(), AP_Airspeed::update_calibration(), update_pos_vel_accel(), update_pos_vel_accel_xy(), AR_WPNav::update_psc_input_shaping(), SITL::Helicopter::update_rpm(), AP_Baro_BMP388::update_temperature(), NavEKF3_core::verifyTiltErrorVariance(), AP_Baro::wind_pressure_correction(), and NavEKF3_core::writeDefaultAirSpeed().
throttle_curve()
float throttle_curve (float thr_mid, float alpha, float thr_in)
Definition at line 131 of file AP_Math.cpp.
Referenced by TEST().
uint64_to_double_le()
double uint64_to_double_le (const uint64_t & value)
Definition at line 557 of file AP_Math.cpp.
usec_to_hz()
constexpr uint32_t usec_to_hz (uint32_t usec) inline constexpr
Definition at line 294 of file AP_Math.h.
Referenced by TEST().
usec_to_nsec()
constexpr uint32_t usec_to_nsec (uint32_t usec) inline constexpr
Definition at line 279 of file AP_Math.h.
Referenced by Linux::RCOutput_Sysfs::push(), and Linux::RCOutput_Sysfs::write().
wrap_180()
template<typename T > T wrap_180 (const T angle)
Definition at line 147 of file AP_Math.cpp.
Referenced by AC_Avoid::adjust_speed(), SITL::Sailboat::calc_lift_and_drag(), AR_PivotTurn::check_activation(), AP_Beacon_Backend::correct_for_orient_yaw(), AR_WPNav::get_corner_angle(), AP_OABendyRuler::resist_bearing_change(), AP_OABendyRuler::search_vertical_path(), AP_OABendyRuler::search_xy_path(), TEST(), TEST(), SITL::BalanceBot::update(), SITL::Sailboat::update(), SITL::PS_LightWare_SF45B::update_output_scan(), and AR_PivotTurn::would_activate().
wrap_180_cd()
template<typename T > T wrap_180_cd (const T angle)
Definition at line 157 of file AP_Math.cpp.
Referenced by AP_L1_Control::_prevent_indecision(), AC_AutoTune::currently_level(), AC_AutoTune_Heli::dwell_test_run(), AR_AttitudeControl::get_forward_speed(), AP_L1_Control::get_yaw_sensor(), AC_AttitudeControl_Heli::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl_Heli::input_euler_angle_roll_pitch_yaw(), AP_L1_Control::nav_bearing_cd(), AC_AutoTune_Heli::rate_ff_test_run(), AP_L1_Control::target_bearing_cd(), TEST(), TEST(), test_wrap_cd(), AC_AutoTune_Multi::twitch_test_run(), and AP_L1_Control::update_heading_hold().
wrap_2PI()
ftype wrap_2PI (const ftype radian)
Definition at line 257 of file AP_Math.cpp.
Referenced by AP_Beacon::get_next_boundary_point(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), TEST(), TEST(), SITL::Sailboat::update_wave(), and wrap_PI().
wrap_360() [1/2]
float wrap_360 (const float angle)
Definition at line 181 of file AP_Math.cpp.
Referenced by AP_GPS_ERB::_parse_gps(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_SIRF::_parse_gps(), AP_GPS_NMEA::_term_complete(), AP_AHRS_View::AP_AHRS_View(), AP_GPS::calc_blended_state(), AP_Frsky_SPort_Passthrough::calc_waypoint(), AP_Frsky_SPort_Passthrough::calc_wind(), AP_GPS_Backend::calculate_moving_base_yaw(), AP_Proximity_Boundary_3D::get_face(), SITL::InertialLabs::send_packet(), AP_WindVane::send_wind(), AP_AHRS_View::set_pitch_trim(), TEST(), TEST(), SITL::Ship::update(), AP_GPS_Backend::velocity_to_speed_course(), and wrap_180().
wrap_360() [2/2]
int wrap_360 (const int angle)
Definition at line 201 of file AP_Math.cpp.
wrap_360_cd() [1/3]
float wrap_360_cd (const float angle)
Definition at line 210 of file AP_Math.cpp.
Referenced by AP_OSD_Screen::get_arrow_font_index(), AP_GPS::gps_yaw_cdeg(), AC_AutoTune_Heli::rate_ff_test_run(), SITL::ADSB::send_report(), AP_Hott_Telem::send_Vario(), AR_WPNav::set_desired_location(), AR_WPNav::set_desired_location_expect_fast_update(), TEST(), TEST(), test_wrap_cd(), AC_Circle::update(), AP_MSP_Telem_Backend::update_flight_mode_str(), AR_WPNav::update_steering_and_speed(), and wrap_180_cd().
wrap_360_cd() [2/3]
int wrap_360_cd (const int angle)
Definition at line 230 of file AP_Math.cpp.
wrap_360_cd() [3/3]
long wrap_360_cd (const long angle)
Definition at line 239 of file AP_Math.cpp.
wrap_PI()
ftype wrap_PI (const ftype radian)
Definition at line 248 of file AP_Math.cpp.
Referenced by EKFGSF_yaw::alignYaw(), NavEKF2_core::calcQuatAndFieldStates(), Compass::calculate_heading(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), AP_Mount_Backend::MountTarget::get_bf_yaw(), AP_Mount_Backend::MountTarget::get_ef_yaw(), AR_AttitudeControl::get_turn_rate_from_heading(), AP_L1_Control::get_yaw(), NavEKF2::getLastYawResetAngle(), NavEKF3::getLastYawResetAngle(), AC_Circle::init_start_angle(), AC_AttitudeControl::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl_Sub::input_euler_angle_roll_pitch_slew_yaw(), AC_AttitudeControl::input_euler_angle_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl::input_shaping_rate_predictor(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), NavEKF2_core::resetQuatStateYawOnly(), NavEKF3_core::resetQuatStateYawOnly(), AP_Mount_Siyi::send_target_angles(), AC_Loiter::set_pilot_desired_acceleration(), NavEKF3_core::setYawFromMag(), TEST(), TEST(), TEST(), test_euler(), test_euler(), test_wrap_cd(), AC_AttitudeControl::thrust_heading_rotation_angles(), QuaternionT< T >::to_axis_angle(), AP_WindVane::update(), AP_WindVane_NMEA::update(), EKFGSF_yaw::update(), AC_Circle::update(), AP_Mount_Backend::update_angle_target_from_rate(), AP_WindVane::update_apparent_wind_dir_from_true(), AP_WindVane_Analog::update_direction(), AP_WindVane_Home::update_direction(), AP_WindVane::update_true_wind_speed_and_direction(), SITL::Vicon::update_vicon_position_estimate(), AP_L1_Control::update_waypoint(), NavEKF2::updateLaneSwitchYawResetData(), and NavEKF3::updateLaneSwitchYawResetData().