APM:Libraries: libraries/AP_HAL_ChibiOS/system.cpp File Reference
system.cpp File Reference
#include <stdarg.h>
#include <stdio.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_HAL/system.h>
#include <AP_BoardConfig/AP_BoardConfig.h>
#include <AP_InternalError/AP_InternalError.h>
#include "hwdef/common/watchdog.h"
#include "hwdef/common/stm32_util.h"
#include <AP_Vehicle/AP_Vehicle_Type.h>
#include <ch.h>
#include "hal.h"
#include <hrt.h>
Namespaces
namespace AP_HAL
Macros
#define STR(x) #x
#define XSTR(x) STR(x)
#define AP_FAULTHANDLER_DEBUG_VARIABLES_ENABLED 1
#define QUOTE1(str) #str
#define QUOTE2(str) QUOTE1(str)
#define EXPAND_AND_QUOTE(str) QUOTE2(str)
#define ASSERT_CLOCK(clk) static_assert(HAL_EXPECTED_ ##clk == (clk), "unexpected " #clk " value: '" EXPAND_AND_QUOTE(clk) "'")
#define bkpt() __asm volatile("BKPT #0\n")
Functions
void HardFault_Handler (void)
void BusFault_Handler (void) __attribute__((alias("HardFault_Handler")))
void UsageFault_Handler (void)
void MemManage_Handler (void)
void save_fault_watchdog (uint16_t line, FaultType fault_type, uint32_t fault_addr, uint32_t lr)
void __cxa_pure_virtual (void)
void NMI_Handler (void)
uint32_t chibios_rand_generate ()
void AP_HAL::init ()
void AP_HAL::panic (const char *errormsg,...) FMT_PRINTF(1
uint32_t AP_HAL::micros ()
uint16_t AP_HAL::micros16 ()
uint32_t AP_HAL::millis ()
uint16_t AP_HAL::millis16 ()
uint64_t AP_HAL::micros64 ()
uint64_t AP_HAL::millis64 ()
Variables
const AP_HAL::HAL & hal
void * __dso_handle
Macro Definition Documentation
AP_FAULTHANDLER_DEBUG_VARIABLES_ENABLED
#define AP_FAULTHANDLER_DEBUG_VARIABLES_ENABLED 1
Definition at line 59 of file system.cpp.
ASSERT_CLOCK
#define ASSERT_CLOCK (clk) static_assert(HAL_EXPECTED_ ##clk == (clk), "unexpected " #clk " value: '" EXPAND_AND_QUOTE(clk) "'")
Definition at line 65 of file system.cpp.
bkpt
#define bkpt () __asm volatile("BKPT #0\n")
Definition at line 86 of file system.cpp.
EXPAND_AND_QUOTE
#define EXPAND_AND_QUOTE (str) QUOTE2(str)
Definition at line 64 of file system.cpp.
QUOTE1
#define QUOTE1 (str) #str
Definition at line 62 of file system.cpp.
QUOTE2
#define QUOTE2 (str) QUOTE1(str)
Definition at line 63 of file system.cpp.
STR
#define STR (x) #x
Definition at line 36 of file system.cpp.
XSTR
#define XSTR (x) STR(x)
Definition at line 37 of file system.cpp.
Function Documentation
__cxa_pure_virtual()
void __cxa_pure_virtual (void)
Definition at line 286 of file system.cpp.
BusFault_Handler()
void BusFault_Handler (void)
chibios_rand_generate()
uint32_t chibios_rand_generate (void)
Generates a block of random values, returns total values generated if nonblocking, for blocking returns if successful or not
Definition at line 313 of file system.cpp.
HardFault_Handler()
void HardFault_Handler (void)
Definition at line 91 of file system.cpp.
MemManage_Handler()
void MemManage_Handler (void)
Definition at line 199 of file system.cpp.
NMI_Handler()
void NMI_Handler (void)
Definition at line 289 of file system.cpp.
save_fault_watchdog()
void save_fault_watchdog (uint16_t line, FaultType fault_type, uint32_t fault_addr, uint32_t lr)
Definition at line 257 of file system.cpp.
Referenced by CrashCatcher_DumpStart(), HardFault_Handler(), MemManage_Handler(), and UsageFault_Handler().
UsageFault_Handler()
void UsageFault_Handler (void)
Definition at line 162 of file system.cpp.
Variable Documentation
__dso_handle
void* __dso_handle
Definition at line 283 of file system.cpp.
hal
const AP_HAL::HAL& hal extern
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.
Referenced by chibios_rand_generate(), and save_fault_watchdog().