APM:Libraries: libraries/AP_JSON/AP_JSON.cpp File Reference
AP_JSON.cpp File Reference
#include "AP_JSON.h"
#include <AP_Filesystem/AP_Filesystem.h>
#include <AP_Math/AP_Math.h>
#include <stdio.h>
Classes
class input< Iter >
class default_parse_context
Macros
#define ALLOW_DOUBLE_MATH_FUNCTIONS
#define INIT(p, v)
#define DEINIT(p)
#define INIT(p, v)
#define IS(ctype, jtype)
#define GET(ctype, var)
#define SET(ctype, jtype, setter)
#define MOVESET(ctype, jtype, setter)
#define MAP(sym, val)
#define IS(ch, text, op)
Typedefs
typedef AP_JSON::value::array array
typedef AP_JSON::value::object object
typedef AP_JSON::value value
typedef AP_JSON::null null
Enumerations
enum {
null_type , boolean_type , number_type , string_type ,
array_type , object_type
}
Functions
MOVESET (std::string, string, u_.string_=new std::string(std::move(_val));) MOVESET(array
MOVESET (object, object, u_.object_=new object(std::move(_val));) bool AP_JSON
template<typename Iter >
void copy (const std::string &s, Iter oi)
template<typename Iter >
int _parse_quadhex (input< Iter > &in)
template<typename String , typename Iter >
bool _parse_string (String &out, input< Iter > &in)
template<typename Context , typename Iter >
bool _parse_array (Context &ctx, input< Iter > &in)
template<typename Context , typename Iter >
bool _parse_object (Context &ctx, input< Iter > &in)
template<typename Iter >
std::string _parse_number (input< Iter > &in)
template<typename Context , typename Iter >
bool _parse (Context &ctx, input< Iter > &in)
template<typename Context , typename Iter >
Iter _parse (Context &ctx, const Iter &first, const Iter &last, std::string *err)
template<typename Iter >
Iter parse (value &out, const Iter &first, const Iter &last, std::string *err)
Variables
u_ array_ = new array(std::move(_val))
Macro Definition Documentation
ALLOW_DOUBLE_MATH_FUNCTIONS
#define ALLOW_DOUBLE_MATH_FUNCTIONS
Definition at line 37 of file AP_JSON.cpp.
DEINIT
#define DEINIT (p)
Value:
  case p##type:             \
    delete u_.p;            \
    break
GET
#define GET (ctype, var)
Value:
  template <> const ctype &AP_JSON::value::get<ctype>() const {        \
    return var;                                                        \
  }                                                                    \
  template <> ctype &AP_JSON::value::get<ctype>() {                    \
    return var;                                                        \
  }
Definition at line 273 of file AP_JSON.cpp.
INIT [1/2]
#define INIT (p, v)
Value:
  case p##type:                              \
    u_.p = v;                                \
    break
INIT [2/2]
#define INIT (p, v)
Value:
  case p##type:             \
    u_.p = v;               \
    break
IS [1/2]
#define IS (ch, text, op)
Value:
  case ch:                                                                                                                         \
    if (in.match(text) && op) {                                                                                                    \
      return true;                                                                                                                 \
    } else {                                                                                                                       \
      return false;                                                                                                                \
    }
Definition at line 258 of file AP_JSON.cpp.
IS [2/2]
#define IS (ctype, jtype)
Value:
  template <> bool AP_JSON::value::is<ctype>() const {      \
    return type_ == jtype##_type;                           \
  }
Definition at line 258 of file AP_JSON.cpp.
Referenced by _parse().
MAP
#define MAP (sym, val)
Value:
  case sym:                                                                                                                        \
    out.push_back(val);                                                                                                            \
    break
MOVESET
#define MOVESET (ctype, jtype, setter)
Value:
  template <> void AP_JSON::value::set<ctype>(ctype && _val) {         \
    clear();                                                           \
    type_ = jtype##_type;                                              \
    setter                                                             \
  }
Definition at line 300 of file AP_JSON.cpp.
SET
#define SET (ctype, jtype, setter)
Value:
  template <> void AP_JSON::value::set<ctype>(const ctype &_val) {     \
    clear();                                                           \
    type_ = jtype##_type;                                              \
    setter                                                             \
  }
Definition at line 287 of file AP_JSON.cpp.
Typedef Documentation
array
array
Definition at line 108 of file AP_JSON.cpp.
null
typedef AP_JSON::null null
Definition at line 111 of file AP_JSON.cpp.
object
typedef AP_JSON::value::object object
Definition at line 109 of file AP_JSON.cpp.
value
typedef AP_JSON::value value
Definition at line 110 of file AP_JSON.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
null_type
boolean_type
number_type
string_type
array_type
object_type
Definition at line 113 of file AP_JSON.cpp.
Function Documentation
_parse() [1/2]
template<typename Context , typename Iter > Iter _parse (Context & ctx, const Iter & first, const Iter & last, std::string * err)
Definition at line 688 of file AP_JSON.cpp.
_parse() [2/2]
template<typename Context , typename Iter > bool _parse (Context & ctx, input< Iter > & in)
Definition at line 582 of file AP_JSON.cpp.
Referenced by _parse(), parse(), default_parse_context::parse_array_item(), and default_parse_context::parse_object_item().
_parse_array()
template<typename Context , typename Iter > bool _parse_array (Context & ctx, input< Iter > & in)
Definition at line 527 of file AP_JSON.cpp.
Referenced by _parse().
_parse_number()
template<typename Iter > std::string _parse_number (input< Iter > & in)
Definition at line 565 of file AP_JSON.cpp.
Referenced by _parse().
_parse_object()
template<typename Context , typename Iter > bool _parse_object (Context & ctx, input< Iter > & in)
Definition at line 545 of file AP_JSON.cpp.
Referenced by _parse().
_parse_quadhex()
template<typename Iter > int _parse_quadhex (input< Iter > & in)
Definition at line 468 of file AP_JSON.cpp.
_parse_string()
template<typename String , typename Iter > bool _parse_string (String & out, input< Iter > & in)
Definition at line 490 of file AP_JSON.cpp.
Referenced by _parse_object(), and default_parse_context::parse_string().
copy()
template<typename Iter > void copy (const std::string & s, Iter oi)
Definition at line 389 of file AP_JSON.cpp.
MOVESET() [1/2]
MOVESET (object , object , u_. object_ = new object(std::move(_val));)
Definition at line 308 of file AP_JSON.cpp.
MOVESET() [2/2]
MOVESET (std::string , string , u_. string_ = new std::string(std::move(_val));)
parse()
template<typename Iter > Iter parse (value & out, const Iter & first, const Iter & last, std::string * err)
Definition at line 707 of file AP_JSON.cpp.
Variable Documentation
array_
u_ array_ = new array(std::move(_val))
Definition at line 307 of file AP_JSON.cpp.
Referenced by AP_JSON::value::clear(), AP_JSON::value::value(), and AP_JSON::value::value().