APM:Libraries: libraries/AP_Scripting/generator/src/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdarg.h>
#include <assert.h>
#include <string.h>
#include <unistd.h>
#include <getopt.h>
Classes
struct header
struct generator_state
struct range_check
struct type
struct argument
struct method
struct method_alias
struct userdata_field
struct userdata_enum
struct userdata
Macros
#define TRUE 1
#define FALSE 0
#define NULLABLE_ARG_COUNT_BASE 5000
Enumerations
enum error_codes {
ERROR_OUT_OF_MEMORY = 1 , ERROR_HEADER = 2 , ERROR_UNKNOWN_KEYWORD = 3 , ERROR_USERDATA = 4 ,
ERROR_INTERNAL = 5 , ERROR_GENERAL = 6 , ERROR_SINGLETON = 7 , ERROR_DEPENDS = 8 ,
ERROR_DOCS = 9 , ERROR_GLOBALS = 10
}
enum trace_level {
TRACE_TOKENS = (1 << 0) , TRACE_HEADER = (1 << 1) , TRACE_GENERAL = (1 << 2) , TRACE_USERDATA = (1 << 3) ,
TRACE_SINGLETON = (1 << 4) , TRACE_DEPENDS = (1 << 5)
}
enum access_flags { ACCESS_FLAG_READ = (1 << 0) , ACCESS_FLAG_WRITE = (1 << 1) }
enum field_type {
TYPE_BOOLEAN = 0 , TYPE_FLOAT , TYPE_INT8_T , TYPE_INT16_T ,
TYPE_INT32_T , TYPE_UINT8_T , TYPE_UINT16_T , TYPE_UINT32_T ,
TYPE_NONE , TYPE_STRING , TYPE_ENUM , TYPE_LITERAL ,
TYPE_USERDATA , TYPE_AP_OBJECT
}
enum operator_type {
OP_ADD = (1U << 0) , OP_SUB = (1U << 1) , OP_MUL = (1U << 2) , OP_DIV = (1U << 3) ,
OP_MANUAL = (1U << 4) , OP_LAST
}
enum access_type { ACCESS_VALUE = 0 , ACCESS_REFERENCE }
enum type_flags { TYPE_FLAGS_NULLABLE = (1U << 1) , TYPE_FLAGS_ENUM = (1U << 2) , TYPE_FLAGS_REFERNCE = (1U << 3) , TYPE_FLAGS_NO_RANGE_CHECK = (1U << 4) }
enum userdata_type { UD_USERDATA , UD_SINGLETON , UD_AP_OBJECT , UD_GLOBAL }
enum alias_type { ALIAS_TYPE_NONE , ALIAS_TYPE_MANUAL , ALIAS_TYPE_MANUAL_OPERATOR }
enum userdata_flags {
UD_FLAG_SEMAPHORE = (1U << 0) , UD_FLAG_SCHEDULER_SEMAPHORE = (1U << 1) , UD_FLAG_LITERAL = (1U << 2) , UD_FLAG_SEMAPHORE_POINTER = (1U << 3) ,
UD_FLAG_REFERENCE = (1U << 4)
}
enum type_restriction { TYPE_RESTRICTION_NONE = 0 , TYPE_RESTRICTION_OPTIONAL = (1U << 1) , TYPE_RESTRICTION_NOT_NULLABLE = (1U << 2) }
enum range_check_type { RANGE_CHECK_NONE , RANGE_CHECK_MANDATORY }
Functions
void trace (const int trace, const char *message,...)
void error (const int code, const char *message,...) __attribute__((noreturn))
char * next_token (void)
char * start_line (void)
void * allocate (const size_t size)
void string_copy (char **dest, const char *src)
void handle_header (void)
void sanitize_character (char **str, char character)
void sanatize_name (char **dest, char *src)
struct range_check * parse_range_check (enum field_type type)
unsigned int parse_access_flags (struct type *type)
int parse_type (struct type *type, const uint32_t restrictions, enum range_check_type range_type)
void handle_userdata_enum (struct userdata *data)
void handle_userdata_field (struct userdata *data)
void handle_method (struct userdata *node)
void handle_manual (struct userdata *node, enum alias_type type)
void handle_operator (struct userdata *data)
void handle_userdata (void)
void handle_singleton (void)
void handle_ap_object (void)
void handle_global (void)
void sanity_check_userdata (void)
void start_dependency (FILE *f, const char *dependency)
void end_dependency (FILE *f, const char *dependency)
void emit_headers (FILE *f)
void emit_userdata_allocators (void)
void emit_ap_object_allocators (void)
void emit_userdata_checkers (void)
void emit_ap_object_checkers (void)
void emit_singleton_checkers (void)
void emit_userdata_declarations (void)
void emit_ap_object_declarations (void)
void emit_checker (const struct type t, int arg_number, int skipped, const char *indentation)
void emit_field (const struct userdata_field *field, const char *object_name, const char *object_access)
void emit_userdata_field (const struct userdata *data, const struct userdata_field *field)
void emit_userdata_fields ()
void emit_singleton_field (const struct userdata *data, const struct userdata_field *field)
void emit_singleton_fields ()
int emit_references (const struct argument *arg, const char *tab)
void emit_userdata_method (const struct userdata *data, const struct method *method)
const char * get_name_for_operation (enum operator_type op)
void emit_operators (struct userdata *data)
void emit_methods (struct userdata *node)
void emit_enum (struct userdata *data)
void emit_index (struct userdata *head)
void emit_type_index (struct userdata *data, char *meta_name)
void emit_type_index_with_operators (struct userdata *data, char *meta_name)
void emit_loaders (void)
void emit_sandbox (void)
void emit_argcheck_helper (void)
void emit_not_supported_helper (void)
void emit_docs_type (struct type type, const char *prefix, const char *suffix)
void emit_docs_method (const char *name, const char *method_name, struct method *method)
void emit_docs (struct userdata *node, int is_userdata, int emit_creation)
void emit_index_helpers (void)
void emit_structs (void)
int main (int argc, char **argv)
Variables
char keyword_alias [] = "alias"
char keyword_rename [] = "rename"
char keyword_ap_object [] = "ap_object"
char keyword_comment [] = "--"
char keyword_depends [] = "depends"
char keyword_enum [] = "enum"
char keyword_field [] = "field"
char keyword_include [] = "include"
char keyword_method [] = "method"
char keyword_operator [] = "operator"
char keyword_read [] = "read"
char keyword_scheduler_semaphore [] = "scheduler-semaphore"
char keyword_semaphore [] = "semaphore"
char keyword_semaphore_pointer [] = "semaphore-pointer"
char keyword_singleton [] = "singleton"
char keyword_userdata [] = "userdata"
char keyword_write [] = "write"
char keyword_literal [] = "literal"
char keyword_reference [] = "reference"
char keyword_deprecate [] = "deprecate"
char keyword_manual [] = "manual"
char keyword_global [] = "global"
char keyword_creation [] = "creation"
char keyword_manual_operator [] = "manual_operator"
char keyword_attr_enum [] = "'enum"
char keyword_attr_literal [] = "'literal"
char keyword_attr_null [] = "'Null"
char keyword_attr_reference [] = "'Ref"
char keyword_attr_array [] = "'array"
char keyword_attr_no_range_check [] = "'skip_check"
char keyword_boolean [] = "boolean"
char keyword_float [] = "float"
char keyword_int8_t [] = "int8_t"
char keyword_int16_t [] = "int16_t"
char keyword_int32_t [] = "int32_t"
char keyword_string [] = "string"
char keyword_uint8_t [] = "uint8_t"
char keyword_uint16_t [] = "uint16_t"
char keyword_uint32_t [] = "uint32_t"
char keyword_void [] = "void"
FILE * description
FILE * header
FILE * source
FILE * docs
static struct generator_state state
static struct header * headers
const char * type_labels [TYPE_USERDATA+1]
int TRACE_LEVEL = 0
char * token_delimiters = " \n"
static struct userdata * parsed_userdata
static struct userdata * parsed_ap_objects
static struct userdata * parsed_globals
struct userdata * parsed_singletons = NULL
char * output_path = NULL
char * docs_path = NULL
Macro Definition Documentation
FALSE
#define FALSE 0
Definition at line 517 of file main.c.
Referenced by emit_field(), emit_sandbox(), emit_userdata_method(), main(), and parse_type().
NULLABLE_ARG_COUNT_BASE
#define NULLABLE_ARG_COUNT_BASE 5000
Definition at line 1377 of file main.c.
Referenced by emit_checker(), emit_references(), and emit_userdata_method().
TRUE
#define TRUE 1
Definition at line 516 of file main.c.
Referenced by emit_field(), emit_sandbox(), emit_userdata_method(), main(), and parse_type().
Enumeration Type Documentation
access_flags
enum access_flags
Enumerator
ACCESS_FLAG_READ
ACCESS_FLAG_WRITE
Definition at line 99 of file main.c.
access_type
enum access_type
Enumerator
ACCESS_VALUE
ACCESS_REFERENCE
Definition at line 144 of file main.c.
alias_type
enum alias_type
Enumerator
ALIAS_TYPE_NONE
ALIAS_TYPE_MANUAL
ALIAS_TYPE_MANUAL_OPERATOR
Definition at line 358 of file main.c.
error_codes
enum error_codes
Enumerator
ERROR_OUT_OF_MEMORY
ERROR_HEADER
ERROR_UNKNOWN_KEYWORD
ERROR_USERDATA
ERROR_INTERNAL
ERROR_GENERAL
ERROR_SINGLETON
ERROR_DEPENDS
ERROR_DOCS
ERROR_GLOBALS
Definition at line 55 of file main.c.
field_type
enum field_type
Enumerator
TYPE_BOOLEAN
TYPE_FLOAT
TYPE_INT8_T
TYPE_INT16_T
TYPE_INT32_T
TYPE_UINT8_T
TYPE_UINT16_T
TYPE_UINT32_T
TYPE_NONE
TYPE_STRING
TYPE_ENUM
TYPE_LITERAL
TYPE_USERDATA
TYPE_AP_OBJECT
Definition at line 104 of file main.c.
operator_type
enum operator_type
Enumerator
OP_ADD
OP_SUB
OP_MUL
OP_DIV
OP_MANUAL
OP_LAST
Definition at line 135 of file main.c.
range_check_type
enum range_check_type
Enumerator
RANGE_CHECK_NONE
RANGE_CHECK_MANDATORY
Definition at line 525 of file main.c.
trace_level
enum trace_level
Enumerator
TRACE_TOKENS
TRACE_HEADER
TRACE_GENERAL
TRACE_USERDATA
TRACE_SINGLETON
TRACE_DEPENDS
Definition at line 90 of file main.c.
type_flags
enum type_flags
Enumerator
TYPE_FLAGS_NULLABLE
TYPE_FLAGS_ENUM
TYPE_FLAGS_REFERNCE
TYPE_FLAGS_NO_RANGE_CHECK
Definition at line 156 of file main.c.
type_restriction
enum type_restriction
Enumerator
TYPE_RESTRICTION_NONE
TYPE_RESTRICTION_OPTIONAL
TYPE_RESTRICTION_NOT_NULLABLE
Definition at line 519 of file main.c.
userdata_flags
enum userdata_flags
Enumerator
UD_FLAG_SEMAPHORE
UD_FLAG_SCHEDULER_SEMAPHORE
UD_FLAG_LITERAL
UD_FLAG_SEMAPHORE_POINTER
UD_FLAG_REFERENCE
Definition at line 384 of file main.c.
userdata_type
enum userdata_type
Enumerator
UD_USERDATA
UD_SINGLETON
UD_AP_OBJECT
UD_GLOBAL
Definition at line 331 of file main.c.
Function Documentation
allocate()
void * allocate (const size_t size)
Definition at line 265 of file main.c.
Referenced by emit_docs(), emit_docs_method(), handle_ap_object(), handle_global(), handle_header(), handle_manual(), handle_method(), handle_singleton(), handle_userdata(), handle_userdata_enum(), handle_userdata_field(), main(), parse_range_check(), sanatize_name(), and string_copy().
emit_ap_object_allocators()
void emit_ap_object_allocators (void)
Definition at line 1286 of file main.c.
Referenced by main().
emit_ap_object_checkers()
void emit_ap_object_checkers (void)
Definition at line 1313 of file main.c.
Referenced by main().
emit_ap_object_declarations()
void emit_ap_object_declarations (void)
Definition at line 1366 of file main.c.
Referenced by main().
emit_argcheck_helper()
void emit_argcheck_helper (void)
Definition at line 2463 of file main.c.
Referenced by main().
emit_checker()
void emit_checker (const struct type t, int arg_number, int skipped, const char * indentation)
Definition at line 1378 of file main.c.
Referenced by emit_field(), and emit_userdata_method().
emit_docs()
void emit_docs (struct userdata * node, int is_userdata, int emit_creation)
Definition at line 2662 of file main.c.
Referenced by main().
emit_docs_method()
void emit_docs_method (const char * name, const char * method_name, struct method * method)
Definition at line 2611 of file main.c.
Referenced by emit_docs().
emit_docs_type()
void emit_docs_type (struct type type, const char * prefix, const char * suffix)
Definition at line 2563 of file main.c.
Referenced by emit_docs(), and emit_docs_method().
emit_enum()
void emit_enum (struct userdata * data)
Definition at line 2216 of file main.c.
Referenced by emit_index().
emit_field()
void emit_field (const struct userdata_field * field, const char * object_name, const char * object_access)
Definition at line 1638 of file main.c.
Referenced by emit_singleton_field(), and emit_userdata_field().
emit_headers()
void emit_headers (FILE * f)
Definition at line 1241 of file main.c.
Referenced by main().
emit_index()
void emit_index (struct userdata * head)
Definition at line 2226 of file main.c.
Referenced by main().
emit_index_helpers()
void emit_index_helpers (void)
Definition at line 2789 of file main.c.
Referenced by main().
emit_loaders()
void emit_loaders (void)
Definition at line 2327 of file main.c.
Referenced by main().
emit_methods()
void emit_methods (struct userdata * node)
Definition at line 2199 of file main.c.
Referenced by main().
emit_not_supported_helper()
void emit_not_supported_helper (void)
Definition at line 2555 of file main.c.
Referenced by main().
emit_operators()
void emit_operators (struct userdata * data)
Definition at line 2149 of file main.c.
Referenced by emit_methods().
emit_references()
int emit_references (const struct argument * arg, const char * tab)
Definition at line 1795 of file main.c.
Referenced by emit_userdata_method().
emit_sandbox()
void emit_sandbox (void)
Definition at line 2394 of file main.c.
Referenced by main().
emit_singleton_checkers()
void emit_singleton_checkers (void)
Definition at line 1332 of file main.c.
Referenced by main().
emit_singleton_field()
void emit_singleton_field (const struct userdata * data, const struct userdata_field * field)
Definition at line 1763 of file main.c.
Referenced by emit_singleton_fields().
emit_singleton_fields()
void emit_singleton_fields ()
Definition at line 1778 of file main.c.
Referenced by main().
emit_structs()
void emit_structs (void)
Definition at line 2819 of file main.c.
Referenced by main().
emit_type_index()
void emit_type_index (struct userdata * data, char * meta_name)
Definition at line 2301 of file main.c.
Referenced by emit_loaders().
emit_type_index_with_operators()
void emit_type_index_with_operators (struct userdata * data, char * meta_name)
Definition at line 2312 of file main.c.
Referenced by emit_loaders().
emit_userdata_allocators()
void emit_userdata_allocators (void)
Definition at line 1251 of file main.c.
Referenced by main().
emit_userdata_checkers()
void emit_userdata_checkers (void)
Definition at line 1299 of file main.c.
Referenced by main().
emit_userdata_declarations()
void emit_userdata_declarations (void)
Definition at line 1352 of file main.c.
Referenced by main().
emit_userdata_field()
void emit_userdata_field (const struct userdata * data, const struct userdata_field * field)
Definition at line 1741 of file main.c.
Referenced by emit_userdata_fields().
emit_userdata_fields()
void emit_userdata_fields ()
Definition at line 1747 of file main.c.
Referenced by main().
emit_userdata_method()
void emit_userdata_method (const struct userdata * data, const struct method * method)
Definition at line 1845 of file main.c.
Referenced by emit_methods().
end_dependency()
void end_dependency (FILE * f, const char * dependency)
Definition at line 1235 of file main.c.
Referenced by emit_ap_object_allocators(), emit_ap_object_checkers(), emit_ap_object_declarations(), emit_headers(), emit_index(), emit_operators(), emit_sandbox(), emit_singleton_checkers(), emit_singleton_fields(), emit_type_index(), emit_type_index_with_operators(), emit_userdata_allocators(), emit_userdata_checkers(), emit_userdata_declarations(), emit_userdata_fields(), emit_userdata_method(), and main().
error()
void error (const int code, const char * message, ...)
Definition at line 199 of file main.c.
get_name_for_operation()
const char * get_name_for_operation (enum operator_type op)
Definition at line 2130 of file main.c.
Referenced by emit_index(), and emit_operators().
handle_ap_object()
void handle_ap_object (void)
Definition at line 1114 of file main.c.
Referenced by main().
handle_global()
void handle_global (void)
Definition at line 1194 of file main.c.
Referenced by main().
handle_header()
void handle_header (void)
Definition at line 281 of file main.c.
Referenced by main().
handle_manual()
void handle_manual (struct userdata * node, enum alias_type type)
Definition at line 869 of file main.c.
Referenced by handle_ap_object(), handle_global(), handle_singleton(), and handle_userdata().
handle_method()
void handle_method (struct userdata * node)
Definition at line 753 of file main.c.
Referenced by handle_ap_object(), handle_singleton(), and handle_userdata().
handle_operator()
void handle_operator (struct userdata * data)
Definition at line 909 of file main.c.
Referenced by handle_userdata().
handle_singleton()
void handle_singleton (void)
Definition at line 1036 of file main.c.
Referenced by main().
handle_userdata()
void handle_userdata (void)
Definition at line 947 of file main.c.
Referenced by main().
handle_userdata_enum()
void handle_userdata_enum (struct userdata * data)
Definition at line 687 of file main.c.
Referenced by handle_singleton(), and handle_userdata().
handle_userdata_field()
void handle_userdata_field (struct userdata * data)
Definition at line 700 of file main.c.
Referenced by handle_singleton(), and handle_userdata().
main()
int main (int argc, char ** argv)
Definition at line 2837 of file main.c.
next_token()
char * next_token (void)
Definition at line 222 of file main.c.
Referenced by handle_ap_object(), handle_global(), handle_header(), handle_manual(), handle_method(), handle_operator(), handle_singleton(), handle_userdata(), handle_userdata_enum(), handle_userdata_field(), main(), parse_access_flags(), parse_range_check(), and parse_type().
parse_access_flags()
unsigned int parse_access_flags (struct type * type)
Definition at line 466 of file main.c.
Referenced by handle_userdata_field().
parse_range_check()
struct range_check * parse_range_check (enum field_type type)
Definition at line 441 of file main.c.
Referenced by parse_access_flags(), and parse_type().
parse_type()
int parse_type (struct type * type, const uint32_t restrictions, enum range_check_type range_type)
Definition at line 530 of file main.c.
Referenced by handle_method(), and handle_userdata_field().
sanatize_name()
void sanatize_name (char ** dest, char * src)
Definition at line 426 of file main.c.
Referenced by handle_ap_object(), handle_method(), handle_singleton(), handle_userdata(), and parse_type().
sanitize_character()
void sanitize_character (char ** str, char character)
Definition at line 418 of file main.c.
Referenced by sanatize_name().
sanity_check_userdata()
void sanity_check_userdata (void)
Definition at line 1219 of file main.c.
Referenced by main().
start_dependency()
void start_dependency (FILE * f, const char * dependency)
Definition at line 1229 of file main.c.
Referenced by emit_ap_object_allocators(), emit_ap_object_checkers(), emit_ap_object_declarations(), emit_headers(), emit_index(), emit_operators(), emit_sandbox(), emit_singleton_checkers(), emit_singleton_fields(), emit_type_index(), emit_type_index_with_operators(), emit_userdata_allocators(), emit_userdata_checkers(), emit_userdata_declarations(), emit_userdata_fields(), emit_userdata_method(), and main().
start_line()
char * start_line (void)
Definition at line 233 of file main.c.
Referenced by main().
string_copy()
void string_copy (char ** dest, const char * src)
Definition at line 276 of file main.c.
Referenced by handle_ap_object(), handle_header(), handle_manual(), handle_method(), handle_singleton(), handle_userdata(), handle_userdata_enum(), handle_userdata_field(), parse_range_check(), and parse_type().
trace()
void trace (const int trace, const char * message, ...)
Definition at line 180 of file main.c.
Referenced by emit_operators(), handle_ap_object(), handle_header(), handle_method(), handle_operator(), handle_singleton(), handle_userdata(), handle_userdata_enum(), handle_userdata_field(), main(), next_token(), parse_access_flags(), parse_range_check(), start_line(), and trace().
Variable Documentation
description
FILE* description
Definition at line 82 of file main.c.
Referenced by main(), and start_line().
docs
FILE* docs
Definition at line 85 of file main.c.
Referenced by emit_docs(), emit_docs_method(), emit_docs_type(), and main().
docs_path
char* docs_path = NULL
Definition at line 2835 of file main.c.
Referenced by main().
header
FILE* header
Definition at line 83 of file main.c.
Referenced by AP_Param::find_old_parameter(), AP_FlashStorage::load_sector(), main(), Linux::RCOutput_Bebop::play_note(), SITL::GPS_FILE::publish(), and AP_FlashStorage::switch_sectors().
headers
struct header* headers static
Definition at line 88 of file main.c.
Referenced by emit_headers(), and handle_header().
keyword_alias
char keyword_alias[] = "alias"
Definition at line 10 of file main.c.
Referenced by handle_method().
keyword_ap_object
char keyword_ap_object[] = "ap_object"
Definition at line 12 of file main.c.
Referenced by main().
keyword_attr_array
char keyword_attr_array[] = "'array"
Definition at line 40 of file main.c.
Referenced by handle_userdata_field().
keyword_attr_enum
char keyword_attr_enum[] = "'enum"
Definition at line 36 of file main.c.
Referenced by parse_type().
keyword_attr_literal
char keyword_attr_literal[] = "'literal"
Definition at line 37 of file main.c.
Referenced by parse_type().
keyword_attr_no_range_check
char keyword_attr_no_range_check[] = "'skip_check"
Definition at line 41 of file main.c.
Referenced by parse_type().
keyword_attr_null
char keyword_attr_null[] = "'Null"
Definition at line 38 of file main.c.
Referenced by parse_type().
keyword_attr_reference
char keyword_attr_reference[] = "'Ref"
Definition at line 39 of file main.c.
Referenced by parse_type().
keyword_boolean
char keyword_boolean[] = "boolean"
Definition at line 44 of file main.c.
Referenced by parse_type().
keyword_comment
char keyword_comment[] = "--"
Definition at line 13 of file main.c.
Referenced by main(), and next_token().
keyword_creation
char keyword_creation[] = "creation"
Definition at line 32 of file main.c.
Referenced by handle_userdata().
keyword_depends
char keyword_depends[] = "depends"
Definition at line 14 of file main.c.
Referenced by handle_ap_object(), handle_header(), handle_manual(), handle_method(), handle_singleton(), and handle_userdata().
keyword_deprecate
char keyword_deprecate[] = "deprecate"
Definition at line 29 of file main.c.
Referenced by handle_method().
keyword_enum
char keyword_enum[] = "enum"
Definition at line 15 of file main.c.
Referenced by handle_singleton(), and handle_userdata().
keyword_field
char keyword_field[] = "field"
Definition at line 16 of file main.c.
Referenced by handle_singleton(), and handle_userdata().
keyword_float
char keyword_float[] = "float"
Definition at line 45 of file main.c.
Referenced by parse_type().
keyword_global
char keyword_global[] = "global"
Definition at line 31 of file main.c.
Referenced by main().
keyword_include
char keyword_include[] = "include"
Definition at line 17 of file main.c.
Referenced by main().
keyword_int16_t
char keyword_int16_t[] = "int16_t"
Definition at line 47 of file main.c.
Referenced by parse_type().
keyword_int32_t
char keyword_int32_t[] = "int32_t"
Definition at line 48 of file main.c.
Referenced by parse_type().
keyword_int8_t
char keyword_int8_t[] = "int8_t"
Definition at line 46 of file main.c.
Referenced by parse_type().
keyword_literal
char keyword_literal[] = "literal"
Definition at line 27 of file main.c.
Referenced by handle_singleton().
keyword_manual
char keyword_manual[] = "manual"
Definition at line 30 of file main.c.
Referenced by handle_ap_object(), handle_global(), handle_singleton(), and handle_userdata().
keyword_manual_operator
char keyword_manual_operator[] = "manual_operator"
Definition at line 33 of file main.c.
Referenced by handle_userdata().
keyword_method
char keyword_method[] = "method"
Definition at line 18 of file main.c.
Referenced by handle_ap_object(), handle_singleton(), and handle_userdata().
keyword_operator
char keyword_operator[] = "operator"
Definition at line 19 of file main.c.
Referenced by handle_userdata().
keyword_read
char keyword_read[] = "read"
Definition at line 20 of file main.c.
Referenced by parse_access_flags().
keyword_reference
char keyword_reference[] = "reference"
Definition at line 28 of file main.c.
Referenced by handle_singleton().
keyword_rename
char keyword_rename[] = "rename"
Definition at line 11 of file main.c.
Referenced by handle_ap_object(), handle_method(), handle_singleton(), handle_userdata(), handle_userdata_field(), and parse_type().
keyword_scheduler_semaphore
char keyword_scheduler_semaphore[] = "scheduler-semaphore"
Definition at line 21 of file main.c.
Referenced by handle_ap_object(), and handle_singleton().
keyword_semaphore
char keyword_semaphore[] = "semaphore"
Definition at line 22 of file main.c.
Referenced by handle_ap_object(), and handle_singleton().
keyword_semaphore_pointer
char keyword_semaphore_pointer[] = "semaphore-pointer"
Definition at line 23 of file main.c.
Referenced by handle_ap_object(), and handle_singleton().
keyword_singleton
char keyword_singleton[] = "singleton"
Definition at line 24 of file main.c.
Referenced by main().
keyword_string
char keyword_string[] = "string"
Definition at line 49 of file main.c.
Referenced by parse_type().
keyword_uint16_t
char keyword_uint16_t[] = "uint16_t"
Definition at line 51 of file main.c.
Referenced by parse_type().
keyword_uint32_t
char keyword_uint32_t[] = "uint32_t"
Definition at line 52 of file main.c.
Referenced by parse_type().
keyword_uint8_t
char keyword_uint8_t[] = "uint8_t"
Definition at line 50 of file main.c.
Referenced by parse_type().
keyword_userdata
char keyword_userdata[] = "userdata"
Definition at line 25 of file main.c.
Referenced by main().
keyword_void
char keyword_void[] = "void"
Definition at line 53 of file main.c.
Referenced by parse_type().
keyword_write
char keyword_write[] = "write"
Definition at line 26 of file main.c.
Referenced by parse_access_flags().
output_path
char* output_path = NULL
Definition at line 2834 of file main.c.
Referenced by main().
parsed_ap_objects
struct userdata* parsed_ap_objects static
Definition at line 415 of file main.c.
Referenced by emit_ap_object_allocators(), emit_ap_object_checkers(), emit_ap_object_declarations(), emit_loaders(), handle_ap_object(), main(), and parse_type().
parsed_globals
struct userdata* parsed_globals static
Definition at line 416 of file main.c.
Referenced by emit_sandbox(), handle_global(), and main().
parsed_singletons
struct userdata* parsed_singletons = NULL
Definition at line 1034 of file main.c.
Referenced by emit_loaders(), emit_singleton_checkers(), emit_singleton_fields(), handle_singleton(), and main().
parsed_userdata
struct userdata* parsed_userdata static
Definition at line 414 of file main.c.
Referenced by emit_docs_type(), emit_loaders(), emit_sandbox(), emit_userdata_allocators(), emit_userdata_checkers(), emit_userdata_declarations(), emit_userdata_fields(), handle_userdata(), main(), and sanity_check_userdata().
source
FILE* source
Definition at line 84 of file main.c.
Referenced by ChibiOS::RCInput::_timer_tick(), AnalogIn_ADS1115::_update(), StorageAccess::copy_area(), emit_ap_object_allocators(), emit_ap_object_checkers(), emit_argcheck_helper(), emit_checker(), emit_enum(), emit_field(), emit_index(), emit_index_helpers(), emit_loaders(), emit_not_supported_helper(), emit_operators(), emit_references(), emit_sandbox(), emit_singleton_checkers(), emit_singleton_field(), emit_singleton_fields(), emit_structs(), emit_type_index(), emit_type_index_with_operators(), emit_userdata_allocators(), emit_userdata_checkers(), emit_userdata_field(), emit_userdata_fields(), emit_userdata_method(), AP_AHRS::get_vel_innovations_and_variances_for_source(), NavEKF3::getVelInnovationsAndVariancesForSource(), NavEKF3_core::getVelInnovationsAndVariancesForSource(), Linux::RCInput_RPI::init_dma_cb(), luaO_chunkid(), luaX_setinput(), main(), SITL::ADSB_Sagetech_MXS::pack_int32_into_uint8_ts(), Test::require(), RC_Channel::run_aux_function(), and RC_Channels::run_aux_function().
state
struct generator_state state static
Definition at line 87 of file main.c.
Referenced by HALSITL::SITL_State::_read_rc_sitl_input(), Linux::RCInput_RPI::_timer_tick(), OpticalFlow_backend::_update_frontend(), AP_Compass_Backend::accumulate_sample(), ap_hook_accel_sample(), ap_hook_AHRS_update(), ap_hook_gyro_sample(), AP_WheelEncoder_Quadrature::AP_WheelEncoder_Backend(), BM_Crop8bpp(), BM_GeodesicGridSections(), BM_MatrixMultiplication(), BM_YuyvToGrey(), Compass::mag_state::copy_from(), AP_Compass_Backend::correct_field(), AP_Compass_Backend::drain_accumulated_samples(), error(), AP_Beacon::get_beacon_data(), handle_ap_object(), SITL::FETtecOneWireESC::handle_fast_esc_data(), handle_global(), handle_header(), handle_manual(), handle_method(), handle_singleton(), handle_userdata_field(), AP_FlashStorage::init(), ChibiOS::RCOutput::is_dshot_send_allowed(), AP_FlashStorage::load_sector(), main(), next_token(), AP_MotorsHeli_RSC::output(), parse_access_flags(), AP_Compass_Backend::publish_filtered_field(), AP_Compass_Backend::publish_raw_field(), SITL::TSYS03::rdwr_handle_write(), ChibiOS::Scheduler::restore_interrupts(), AP_Compass_Backend::rotate_field(), run_test(), SRV_Channels::set_emergency_stop(), AP_Compass_Backend::set_last_update_usec(), AP_FlashStorage::sector_header::set_state(), start_line(), TEST(), AP_OpticalFlow_PX4Flow::timer(), SITL::SIM_BattMonitor_SMBus::update(), SITL::TSYS01::update(), SITL::TSYS03::update(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_Onboard::update(), AP_OpticalFlow_Pixart::update(), AP_OpticalFlow_UPFLOW::update(), AP_BattMonitor_Backend::update_consumed(), update_controls(), AP_MotorsHeli_Dual::update_motor_control(), AP_MotorsHeli_Quad::update_motor_control(), AP_MotorsHeli_Single::update_motor_control(), SITL::IntelligentEnergy24::update_send(), SITL::ADSB_Sagetech_MXS::update_serial_output(), and AP_OpticalFlow::update_state().
token_delimiters
char* token_delimiters = " \n"
Definition at line 220 of file main.c.
Referenced by next_token(), and start_line().
TRACE_LEVEL
int TRACE_LEVEL = 0
Definition at line 178 of file main.c.
Referenced by trace().
type_labels
const char* type_labels[TYPE_USERDATA+1]
Initial value:
= { "bool",
                                                "float",
                                                "int8_t",
                                                "int16_t",
                                                "int32_t",
                                                "uint8_t",
                                                "uint16_t",
                                                "void",
                                                "string",
                                                "enum",
                                                "userdata",
                                                "ap_object",
                                              }
Definition at line 121 of file main.c.
Referenced by parse_range_check().