APM:Libraries: libraries/AP_ADSB/sagetech-sdk/appendChecksum.c File Reference
appendChecksum.c File Reference
#include "sgUtil.h"
Functions
void appendChecksum (uint8_t *buffer, uint8_t len)
Detailed Description
Copyright
Copyright (c) 2021 Sagetech, Inc. All rights reserved.
Author
Jacob.Garrison
Date
Mar 2, 2021
Definition in file appendChecksum.c.
Function Documentation
appendChecksum()
void appendChecksum (uint8_t * buffer, uint8_t len)
Add the checksum to a host message.
Parameters
buffer The raw message buffer.
len The total quantity of bytes in the buffer
no return value, final buffer byte is set to the checksum value.
Definition at line 16 of file appendChecksum.c.
Referenced by sgEncodeDataReq(), sgEncodeFlightId(), sgEncodeGPS(), sgEncodeInstall(), sgEncodeOperating(), and sgEncodeTargetReq().