APM:Libraries: libraries/SITL/examples/Webots/controllers/ardupilot_SITL_QUAD/sockets.c File Reference
sockets.c File Reference
#include "sockets.h"
Functions
bool socket_init ()
bool socket_set_non_blocking (int fd)
int socket_accept (int server_fd)
bool socket_close (int fd)
bool socket_cleanup ()
int create_socket_server (int port)
Function Documentation
create_socket_server()
int create_socket_server (int port)
Definition at line 79 of file sockets.c.
Referenced by initialize().
socket_accept()
int socket_accept (int server_fd)
Definition at line 28 of file sockets.c.
Referenced by run().
socket_cleanup()
bool socket_cleanup ()
Definition at line 65 of file sockets.c.
Referenced by run().
socket_close()
bool socket_close (int fd)
Definition at line 57 of file sockets.c.
Referenced by create_socket_server().
socket_init()
bool socket_init ()
Definition at line 5 of file sockets.c.
Referenced by create_socket_server().
socket_set_non_blocking()
bool socket_set_non_blocking (int fd)
Definition at line 16 of file sockets.c.