APM:Libraries: libraries/SITL/examples/Webots/controllers/ardupilot_SITL_TRICOPTER/sensors.h File Reference
sensors.h File Reference
#include <webots/robot.h>
#include <webots/keyboard.h>
#include <webots/compass.h>
#include <webots/accelerometer.h>
#include <webots/inertial_unit.h>
#include <webots/gps.h>
#include <webots/gyro.h>
#include <webots/motor.h>
#include <webots/camera.h>
Functions
void getInertia (const WbDeviceTag inertialUnit, char *buf)
void getLinearVelocity (WbNodeRef nodeRef, char *buf)
void getCompass (const WbDeviceTag compass, char *buf)
void getAcc (const WbDeviceTag accelerometer, char *buf)
void getGyro (const WbDeviceTag gyro, char *buf)
void getGPS (const WbDeviceTag gps, char *buf)
void getAllSensors (char *buf, WbDeviceTag gyro, WbDeviceTag accelerometer, WbDeviceTag compass, const WbDeviceTag gps, const WbDeviceTag inertial_unit)
Variables
WbNodeRef self_node
double * linear_velocity
double timestep_scale
char pBug [1024]
Function Documentation
getAcc()
void getAcc (const WbDeviceTag accelerometer, char * buf)
Definition at line 90 of file sensors.c.
Referenced by getAllSensors().
getAllSensors()
void getAllSensors (char * buf, WbDeviceTag gyro, WbDeviceTag accelerometer, WbDeviceTag compass, const WbDeviceTag gps, const WbDeviceTag inertial_unit)
Definition at line 128 of file sensors.c.
Referenced by run().
getCompass()
void getCompass (const WbDeviceTag compass, char * buf)
Definition at line 49 of file sensors.c.
Referenced by getAllSensors().
getGPS()
void getGPS (const WbDeviceTag gps, char * buf)
Definition at line 66 of file sensors.c.
Referenced by getAllSensors().
getGyro()
void getGyro (const WbDeviceTag gyro, char * buf)
Definition at line 106 of file sensors.c.
Referenced by getAllSensors().
getInertia()
void getInertia (const WbDeviceTag inertialUnit, char * buf)
Definition at line 36 of file sensors.c.
Referenced by getAllSensors().
getLinearVelocity()
void getLinearVelocity (WbNodeRef nodeRef, char * buf)
Definition at line 117 of file sensors.c.
Referenced by getAllSensors().
Variable Documentation
linear_velocity
double* linear_velocity
Definition at line 15 of file sensors.h.
pBug
char pBug[1024]
Definition at line 17 of file sensors.h.
self_node
WbNodeRef self_node
Definition at line 14 of file sensors.h.
timestep_scale
double timestep_scale
Definition at line 16 of file sensors.h.