APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/bouncebuffer.c File Reference
bouncebuffer.c File Reference
#include "stm32_util.h"
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "bouncebuffer.h"
Macros
#define ENABLE_ECHO_SAFE 0
Functions
void bouncebuffer_init (struct bouncebuffer_t **bouncebuffer, uint32_t prealloc_bytes, bool axi_sram)
bool bouncebuffer_setup_read (struct bouncebuffer_t *bouncebuffer, uint8_t **buf, uint32_t size)
void bouncebuffer_finish_read (struct bouncebuffer_t *bouncebuffer, const uint8_t *buf, uint32_t size)
bool bouncebuffer_setup_write (struct bouncebuffer_t *bouncebuffer, const uint8_t **buf, uint32_t size)
void bouncebuffer_finish_write (struct bouncebuffer_t *bouncebuffer, const uint8_t *buf)
void bouncebuffer_abort (struct bouncebuffer_t *bouncebuffer)
Macro Definition Documentation
ENABLE_ECHO_SAFE
#define ENABLE_ECHO_SAFE 0
Definition at line 25 of file bouncebuffer.c.
Function Documentation
bouncebuffer_abort()
void bouncebuffer_abort (struct bouncebuffer_t * bouncebuffer)
Definition at line 142 of file bouncebuffer.c.
Referenced by ChibiOS::DeviceBus::bouncebuffer_setup().
bouncebuffer_finish_read()
void bouncebuffer_finish_read (struct bouncebuffer_t * bouncebuffer, const uint8_t * buf, uint32_t size)
Definition at line 82 of file bouncebuffer.c.
Referenced by ChibiOS::DeviceBus::bouncebuffer_finish().
bouncebuffer_finish_write()
void bouncebuffer_finish_write (struct bouncebuffer_t * bouncebuffer, const uint8_t * buf)
Definition at line 131 of file bouncebuffer.c.
Referenced by ChibiOS::DeviceBus::bouncebuffer_finish().
bouncebuffer_init()
void bouncebuffer_init (struct bouncebuffer_t ** bouncebuffer, uint32_t prealloc_bytes, bool axi_sram)
Definition at line 30 of file bouncebuffer.c.
Referenced by ChibiOS::DeviceBus::DeviceBus(), ChibiOS::DeviceBus::DeviceBus(), and sdcard_init().
bouncebuffer_setup_read()
bool bouncebuffer_setup_read (struct bouncebuffer_t * bouncebuffer, uint8_t ** buf, uint32_t size)
Definition at line 48 of file bouncebuffer.c.
Referenced by ChibiOS::DeviceBus::bouncebuffer_setup().
bouncebuffer_setup_write()
bool bouncebuffer_setup_write (struct bouncebuffer_t * bouncebuffer, const uint8_t ** buf, uint32_t size)
Definition at line 97 of file bouncebuffer.c.
Referenced by ChibiOS::DeviceBus::bouncebuffer_setup().