APM:Libraries: ChibiOS::GPIO Class Reference
ChibiOS::GPIO Class Reference
#include <GPIO.h>
Public Member Functions
GPIO ()
void init () override
void pinMode (uint8_t pin, uint8_t output) override
uint8_t read (uint8_t pin) override
void write (uint8_t pin, uint8_t value) override
void toggle (uint8_t pin) override
AP_HAL::DigitalSource * channel (uint16_t n) override
bool attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, INTERRUPT_TRIGGER_TYPE mode) override
bool attach_interrupt (uint8_t pin, irq_handler_fn_t fn, INTERRUPT_TRIGGER_TYPE mode) override
bool usb_connected (void) override
void set_usb_connected ()
bool _attach_interrupt (ioline_t line, AP_HAL::Proc p, uint8_t mode)
bool wait_pin (uint8_t pin, INTERRUPT_TRIGGER_TYPE mode, uint32_t timeout_us) override
void timer_tick (void) override
bool arming_checks (size_t buflen, char *buffer) const override
bool valid_pin (uint8_t pin) const override
bool pin_to_servo_channel (uint8_t pin, uint8_t &servo_ch) const override
Public Member Functions inherited from AP_HAL::GPIO
GPIO ()
virtual void pinMode (uint8_t pin, uint8_t output, uint8_t alt)
virtual bool get_mode (uint8_t pin, uint32_t &mode)
virtual void set_mode (uint8_t pin, uint32_t mode)
FUNCTOR_TYPEDEF (irq_handler_fn_t, void, uint8_t, bool, uint32_t)
bool detach_interrupt (uint8_t pin)
Static Public Member Functions
static ioline_t resolve_alt_config (ioline_t base, PERIPH_TYPE ptype, uint8_t instance)
Private Member Functions
bool _attach_interruptI (ioline_t line, palcallback_t cb, void *p, uint8_t mode)
bool _attach_interrupt (ioline_t line, palcallback_t cb, void *p, uint8_t mode)
Private Attributes
bool _usb_connected
bool _ext_started
Additional Inherited Members
Public Types inherited from AP_HAL::GPIO
enum INTERRUPT_TRIGGER_TYPE { INTERRUPT_NONE , INTERRUPT_FALLING , INTERRUPT_RISING , INTERRUPT_BOTH }
Detailed Description
Definition at line 41 of file GPIO.h.
Constructor & Destructor Documentation
GPIO()
GPIO::GPIO ()
Definition at line 85 of file GPIO.cpp.
Member Function Documentation
_attach_interrupt() [1/2]
bool GPIO::_attach_interrupt (ioline_t line, AP_HAL::Proc p, uint8_t mode)
Definition at line 328 of file GPIO.cpp.
Referenced by _attach_interrupt(), attach_interrupt(), and attach_interrupt().
_attach_interrupt() [2/2]
bool GPIO::_attach_interrupt (ioline_t line, palcallback_t cb, void * p, uint8_t mode) private
Definition at line 383 of file GPIO.cpp.
_attach_interruptI()
bool GPIO::_attach_interruptI (ioline_t line, palcallback_t cb, void * p, uint8_t mode) private
Definition at line 346 of file GPIO.cpp.
Referenced by _attach_interrupt(), and wait_pin().
arming_checks()
bool GPIO::arming_checks (size_t buflen, char * buffer) const override virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 655 of file GPIO.cpp.
attach_interrupt() [1/2]
bool GPIO::attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, INTERRUPT_TRIGGER_TYPE mode) override virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 333 of file GPIO.cpp.
Referenced by timer_tick().
attach_interrupt() [2/2]
bool GPIO::attach_interrupt (uint8_t pin, irq_handler_fn_t fn, INTERRUPT_TRIGGER_TYPE mode) override virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 304 of file GPIO.cpp.
channel()
AP_HAL::DigitalSource * GPIO::channel (uint16_t n) override virtual
Implements AP_HAL::GPIO.
Definition at line 284 of file GPIO.cpp.
init()
void GPIO::init () override virtual
Implements AP_HAL::GPIO.
Definition at line 88 of file GPIO.cpp.
pin_to_servo_channel()
bool GPIO::pin_to_servo_channel (uint8_t pin, uint8_t & servo_ch) const override virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 539 of file GPIO.cpp.
pinMode()
void GPIO::pinMode (uint8_t pin, uint8_t output) override virtual
Implements AP_HAL::GPIO.
Definition at line 212 of file GPIO.cpp.
read()
uint8_t GPIO::read (uint8_t pin) override virtual
Implements AP_HAL::GPIO.
Definition at line 238 of file GPIO.cpp.
resolve_alt_config()
ioline_t GPIO::resolve_alt_config (ioline_t base, PERIPH_TYPE ptype, uint8_t instance) static
Definition at line 181 of file GPIO.cpp.
Referenced by ChibiOS::UARTDriver::set_options().
set_usb_connected()
void ChibiOS::GPIO::set_usb_connected () inline
Definition at line 66 of file GPIO.h.
timer_tick()
void GPIO::timer_tick (void) override virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 599 of file GPIO.cpp.
toggle()
void GPIO::toggle (uint8_t pin) override virtual
Implements AP_HAL::GPIO.
Definition at line 269 of file GPIO.cpp.
usb_connected()
bool GPIO::usb_connected (void) override virtual
Implements AP_HAL::GPIO.
Definition at line 391 of file GPIO.cpp.
valid_pin()
bool GPIO::valid_pin (uint8_t pin) const override virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 527 of file GPIO.cpp.
wait_pin()
bool GPIO::wait_pin (uint8_t pin, INTERRUPT_TRIGGER_TYPE mode, uint32_t timeout_us) override virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 491 of file GPIO.cpp.
write()
void GPIO::write (uint8_t pin, uint8_t value) override virtual
Implements AP_HAL::GPIO.
Definition at line 247 of file GPIO.cpp.
Member Data Documentation
_ext_started
bool ChibiOS::GPIO::_ext_started private
Definition at line 105 of file GPIO.h.
_usb_connected
bool ChibiOS::GPIO::_usb_connected private
Definition at line 104 of file GPIO.h.
Referenced by set_usb_connected(), and usb_connected().
The documentation for this class was generated from the following files:
libraries/AP_HAL_ChibiOS/GPIO.h
libraries/AP_HAL_ChibiOS/GPIO.cpp