APM:Libraries: GPIO_Navigator Class Reference
GPIO_Navigator Class Reference
#include <GPIO_Navigator.h>
Public Member Functions
void pinMode (uint8_t pin, uint8_t output) override
void pinMode (uint8_t pin, uint8_t output, uint8_t alt) override
uint8_t read (uint8_t pin) override
void write (uint8_t pin, uint8_t value) override
Public Member Functions inherited from Linux::GPIO_RPI
GPIO_RPI ()
void init () override
void pinMode (uint8_t pin, uint8_t output) override
void pinMode (uint8_t pin, uint8_t output, uint8_t alt) override
uint8_t read (uint8_t pin) override
void write (uint8_t pin, uint8_t value) override
void toggle (uint8_t pin) override
AP_HAL::DigitalSource * channel (uint16_t n) override
bool usb_connected (void) override
Public Member Functions inherited from AP_HAL::GPIO
GPIO ()
virtual bool valid_pin (uint8_t pin) const
virtual bool pin_to_servo_channel (uint8_t pin, uint8_t &servo_ch) const
virtual bool get_mode (uint8_t pin, uint32_t &mode)
virtual void set_mode (uint8_t pin, uint32_t mode)
FUNCTOR_TYPEDEF (irq_handler_fn_t, void, uint8_t, bool, uint32_t)
virtual bool attach_interrupt (uint8_t pin, irq_handler_fn_t fn, INTERRUPT_TRIGGER_TYPE mode)
virtual bool attach_interrupt (uint8_t pin, AP_HAL::Proc proc, INTERRUPT_TRIGGER_TYPE mode)
bool detach_interrupt (uint8_t pin)
virtual bool wait_pin (uint8_t pin, INTERRUPT_TRIGGER_TYPE mode, uint32_t timeout_us)
virtual void timer_tick (void)
virtual bool arming_checks (size_t buflen, char *buffer) const
Private Member Functions
bool pinAllowed (uint8_t pin)
Private Attributes
uint8_t AllowedGPIOS [3]
Additional Inherited Members
Public Types inherited from AP_HAL::GPIO
enum INTERRUPT_TRIGGER_TYPE { INTERRUPT_NONE , INTERRUPT_FALLING , INTERRUPT_RISING , INTERRUPT_BOTH }
Detailed Description
Definition at line 8 of file GPIO_Navigator.h.
Member Function Documentation
pinAllowed()
bool GPIO_Navigator::pinAllowed (uint8_t pin) private
Definition at line 39 of file GPIO_Navigator.cpp.
Referenced by pinMode(), pinMode(), read(), and write().
pinMode() [1/2]
void GPIO_Navigator::pinMode (uint8_t pin, uint8_t output) override virtual
Implements AP_HAL::GPIO.
Definition at line 25 of file GPIO_Navigator.cpp.
pinMode() [2/2]
void GPIO_Navigator::pinMode (uint8_t pin, uint8_t output, uint8_t alt) override virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 32 of file GPIO_Navigator.cpp.
read()
uint8_t GPIO_Navigator::read (uint8_t pin) override virtual
Implements AP_HAL::GPIO.
Definition at line 3 of file GPIO_Navigator.cpp.
write()
void GPIO_Navigator::write (uint8_t pin, uint8_t value) override virtual
Implements AP_HAL::GPIO.
Definition at line 14 of file GPIO_Navigator.cpp.
Member Data Documentation
AllowedGPIOS
uint8_t GPIO_Navigator::AllowedGPIOS[3] private
Initial value:
= {
        RPI_GPIO_<18>(),
        RPI_GPIO_<26>(),
        RPI_GPIO_<27>()
    }
Definition at line 17 of file GPIO_Navigator.h.
Referenced by pinAllowed().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/GPIO_Navigator.h
libraries/AP_HAL_Linux/GPIO_Navigator.cpp