APM:Libraries: AP_RangeFinder_LeddarVu8 Class Reference
AP_RangeFinder_LeddarVu8 Class Reference
#include <AP_RangeFinder_LeddarVu8.h>
Classes
struct PACKED
Static Public Member Functions
static AP_RangeFinder_Backend_Serial * create (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params)
Protected Member Functions
uint32_t initial_baudrate (uint8_t serial_instance) const override
MAV_DISTANCE_SENSOR _get_mav_distance_sensor_type () const override
bool get_reading (float &reading_m) override
uint16_t read_timeout_ms () const override
Protected Member Functions inherited from AP_RangeFinder_Backend_Serial
virtual uint16_t rx_bufsize () const
virtual uint16_t tx_bufsize () const
virtual void update (void) override
virtual int8_t get_signal_quality_pct () const WARN_IF_UNUSED
Protected Member Functions inherited from AP_RangeFinder_Backend
void update_status (RangeFinder::RangeFinder_State &state_arg) const
void update_status ()
void set_status (RangeFinder::Status status)
Private Types
enum class FunctionCode : uint8_t {
READ_HOLDING_REGISTER = 0x03 , READ_INPUT_REGISTER = 0x04 , WRITE_HOLDING_REGISTER = 0x06 , WRITE_MULTIPLE_REGISTER = 0x10 ,
READ_WRITE_MULTIPLE_REGISTER = 0x17
}
enum class RegisterNumber : uint8_t {
REGISTER_STATUS = 1 , NUMBER_OF_SEGMENTS = 2 , NUMBER_OF_DETECTIONS = 11 , PERCENTAGE_OF_LIGHT_SOURCE_POWER = 12 ,
TIMESTAMP_LOW = 14 , TIMESTAMP_HIGH = 15 , FIRST_DISTANCE0 = 16 , FIRST_AMPLITUDE0 = 24 ,
FIRST_FLAG0 = 32
}
enum class ParseState : uint8_t {
WAITING_FOR_ADDRESS , WAITING_FOR_FUNCTION_CODE , WAITING_FOR_PAYLOAD_LEN , WAITING_FOR_PAYLOAD ,
WAITING_FOR_CRC_LOW , WAITING_FOR_CRC_HIGH
}
Private Member Functions
uint8_t get_sensor_address () const
void request_distances ()
bool parse_byte (uint8_t b, bool &valid_reading, uint16_t &reading_cm)
AP_RangeFinder_Backend_Serial (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params)
Private Attributes
struct AP_RangeFinder_LeddarVu8::PACKED parsed_msg
uint32_t last_distance_ms
uint32_t last_distance_request_ms
Additional Inherited Members
Public Member Functions inherited from AP_RangeFinder_Backend_Serial
AP_RangeFinder_Backend_Serial (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params)
void init_serial (uint8_t serial_instance) override
Public Member Functions inherited from AP_RangeFinder_Backend
AP_RangeFinder_Backend (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params)
virtual ~AP_RangeFinder_Backend (void)
virtual void handle_msg (const mavlink_message_t &msg)
enum Rotation orientation () const
float distance () const
uint16_t distance_cm () const
int8_t signal_quality_pct () const WARN_IF_UNUSED
uint16_t voltage_mv () const
virtual int16_t max_distance_cm () const
virtual int16_t min_distance_cm () const
int16_t ground_clearance_cm () const
MAV_DISTANCE_SENSOR get_mav_distance_sensor_type () const
RangeFinder::Status status () const
RangeFinder::Type type () const
bool has_data () const
uint8_t range_valid_count () const
const Vector3f & get_pos_offset () const
uint32_t last_reading_ms () const
virtual bool get_temp (float &temp) const
RangeFinder::Type allocated_type () const
Static Protected Member Functions inherited from AP_RangeFinder_Backend
static void set_status (RangeFinder::RangeFinder_State &state_arg, RangeFinder::Status status)
Protected Attributes inherited from AP_RangeFinder_Backend_Serial
AP_HAL::UARTDriver * uart = nullptr
Protected Attributes inherited from AP_RangeFinder_Backend
RangeFinder::RangeFinder_State & state
AP_RangeFinder_Params & params
HAL_Semaphore _sem
RangeFinder::Type _backend_type
Detailed Description
Definition at line 12 of file AP_RangeFinder_LeddarVu8.h.
Member Enumeration Documentation
FunctionCode
enum class AP_RangeFinder_LeddarVu8::FunctionCode : uint8_t strong private
Enumerator
READ_HOLDING_REGISTER
READ_INPUT_REGISTER
WRITE_HOLDING_REGISTER
WRITE_MULTIPLE_REGISTER
READ_WRITE_MULTIPLE_REGISTER
Definition at line 46 of file AP_RangeFinder_LeddarVu8.h.
ParseState
enum class AP_RangeFinder_LeddarVu8::ParseState : uint8_t strong private
Enumerator
WAITING_FOR_ADDRESS
WAITING_FOR_FUNCTION_CODE
WAITING_FOR_PAYLOAD_LEN
WAITING_FOR_PAYLOAD
WAITING_FOR_CRC_LOW
WAITING_FOR_CRC_HIGH
Definition at line 69 of file AP_RangeFinder_LeddarVu8.h.
RegisterNumber
enum class AP_RangeFinder_LeddarVu8::RegisterNumber : uint8_t strong private
Enumerator
REGISTER_STATUS
NUMBER_OF_SEGMENTS
NUMBER_OF_DETECTIONS
PERCENTAGE_OF_LIGHT_SOURCE_POWER
TIMESTAMP_LOW
TIMESTAMP_HIGH
FIRST_DISTANCE0
FIRST_AMPLITUDE0
FIRST_FLAG0
Definition at line 55 of file AP_RangeFinder_LeddarVu8.h.
Member Function Documentation
_get_mav_distance_sensor_type()
MAV_DISTANCE_SENSOR AP_RangeFinder_LeddarVu8::_get_mav_distance_sensor_type () const inline override protected virtual
Implements AP_RangeFinder_Backend.
Definition at line 31 of file AP_RangeFinder_LeddarVu8.h.
AP_RangeFinder_Backend_Serial()
AP_RangeFinder_Backend_Serial::AP_RangeFinder_Backend_Serial (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params) private
Definition at line 9 of file AP_RangeFinder_Backend_Serial.cpp.
create()
static AP_RangeFinder_Backend_Serial * AP_RangeFinder_LeddarVu8::create (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params) inline static
Definition at line 17 of file AP_RangeFinder_LeddarVu8.h.
Referenced by RangeFinder::detect_instance().
get_reading()
bool AP_RangeFinder_LeddarVu8::get_reading (float & reading_m) override protected virtual
Implements AP_RangeFinder_Backend_Serial.
Definition at line 34 of file AP_RangeFinder_LeddarVu8.cpp.
get_sensor_address()
uint8_t AP_RangeFinder_LeddarVu8::get_sensor_address () const private
Definition at line 91 of file AP_RangeFinder_LeddarVu8.cpp.
Referenced by parse_byte(), and request_distances().
initial_baudrate()
uint32_t AP_RangeFinder_LeddarVu8::initial_baudrate (uint8_t serial_instance) const inline override protected virtual
Reimplemented from AP_RangeFinder_Backend_Serial.
Definition at line 26 of file AP_RangeFinder_LeddarVu8.h.
parse_byte()
bool AP_RangeFinder_LeddarVu8::parse_byte (uint8_t b, bool & valid_reading, uint16_t & reading_cm) private
Definition at line 129 of file AP_RangeFinder_LeddarVu8.cpp.
Referenced by get_reading().
read_timeout_ms()
uint16_t AP_RangeFinder_LeddarVu8::read_timeout_ms () const inline override protected virtual
Reimplemented from AP_RangeFinder_Backend_Serial.
Definition at line 39 of file AP_RangeFinder_LeddarVu8.h.
request_distances()
void AP_RangeFinder_LeddarVu8::request_distances () private
Definition at line 100 of file AP_RangeFinder_LeddarVu8.cpp.
Referenced by get_reading().
Member Data Documentation
last_distance_ms
uint32_t AP_RangeFinder_LeddarVu8::last_distance_ms private
Definition at line 100 of file AP_RangeFinder_LeddarVu8.h.
Referenced by get_reading().
last_distance_request_ms
uint32_t AP_RangeFinder_LeddarVu8::last_distance_request_ms private
Definition at line 101 of file AP_RangeFinder_LeddarVu8.h.
Referenced by get_reading(), and request_distances().
parsed_msg
struct AP_RangeFinder_LeddarVu8::PACKED AP_RangeFinder_LeddarVu8::parsed_msg private
Referenced by parse_byte().
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder_LeddarVu8.h
libraries/AP_RangeFinder/AP_RangeFinder_LeddarVu8.cpp