APM:Libraries: ekf_imu_buffer Class Reference
ekf_imu_buffer Class Reference
#include <EKF_Buffer.h>
Public Member Functions
ekf_imu_buffer (uint8_t elsize)
bool init (uint32_t size)
void push_youngest_element (const void *element)
bool is_filled (void) const
void get_oldest_element (void *element)
void reset_history (const void *element)
void reset ()
void * get (uint8_t index) const
uint8_t get_oldest_index () const
uint8_t get_youngest_index () const
Protected Member Functions
void * get_offset (uint8_t idx) const
Protected Attributes
const uint8_t elsize
void * buffer
uint8_t _size
uint8_t _oldest
uint8_t _youngest
bool _filled
Detailed Description
Definition at line 95 of file EKF_Buffer.h.
Constructor & Destructor Documentation
ekf_imu_buffer()
ekf_imu_buffer::ekf_imu_buffer (uint8_t elsize)
Definition at line 114 of file EKF_Buffer.cpp.
Member Function Documentation
get()
void * ekf_imu_buffer::get (uint8_t index) const
Definition at line 191 of file EKF_Buffer.cpp.
Referenced by EKF_IMU_buffer_t< element_type >::operator[]().
get_offset()
void * ekf_imu_buffer::get_offset (uint8_t idx) const protected
Definition at line 121 of file EKF_Buffer.cpp.
Referenced by get(), get_oldest_element(), push_youngest_element(), and reset_history().
get_oldest_element()
void ekf_imu_buffer::get_oldest_element (void * element)
Definition at line 164 of file EKF_Buffer.cpp.
Referenced by EKF_IMU_buffer_t< element_type >::get_oldest_element().
get_oldest_index()
uint8_t ekf_imu_buffer::get_oldest_index () const inline
Definition at line 127 of file EKF_Buffer.h.
Referenced by EKF_IMU_buffer_t< element_type >::get_oldest_index().
get_youngest_index()
uint8_t ekf_imu_buffer::get_youngest_index () const inline
Definition at line 132 of file EKF_Buffer.h.
Referenced by EKF_IMU_buffer_t< element_type >::get_youngest_index().
init()
bool ekf_imu_buffer::init (uint32_t size)
Definition at line 127 of file EKF_Buffer.cpp.
Referenced by EKF_IMU_buffer_t< element_type >::init().
is_filled()
bool ekf_imu_buffer::is_filled (void) const inline
Definition at line 110 of file EKF_Buffer.h.
Referenced by EKF_IMU_buffer_t< element_type >::is_filled().
push_youngest_element()
void ekf_imu_buffer::push_youngest_element (const void * element)
Definition at line 147 of file EKF_Buffer.cpp.
Referenced by EKF_IMU_buffer_t< element_type >::push_youngest_element().
reset()
void ekf_imu_buffer::reset ()
Definition at line 183 of file EKF_Buffer.cpp.
Referenced by EKF_IMU_buffer_t< element_type >::reset().
reset_history()
void ekf_imu_buffer::reset_history (const void * element)
Definition at line 175 of file EKF_Buffer.cpp.
Referenced by EKF_IMU_buffer_t< element_type >::reset_history().
Member Data Documentation
_filled
bool ekf_imu_buffer::_filled protected
Definition at line 140 of file EKF_Buffer.h.
Referenced by is_filled(), and push_youngest_element().
_oldest
uint8_t ekf_imu_buffer::_oldest protected
Definition at line 139 of file EKF_Buffer.h.
Referenced by get_oldest_element(), get_oldest_index(), init(), push_youngest_element(), and reset().
_size
uint8_t ekf_imu_buffer::_size protected
Definition at line 139 of file EKF_Buffer.h.
Referenced by init(), push_youngest_element(), reset(), and reset_history().
_youngest
uint8_t ekf_imu_buffer::_youngest protected
Definition at line 139 of file EKF_Buffer.h.
Referenced by get_youngest_index(), init(), push_youngest_element(), and reset().
buffer
void* ekf_imu_buffer::buffer protected
Definition at line 138 of file EKF_Buffer.h.
Referenced by get_offset(), get_oldest_element(), init(), push_youngest_element(), and reset().
elsize
const uint8_t ekf_imu_buffer::elsize protected
Definition at line 137 of file EKF_Buffer.h.
Referenced by get_offset(), get_oldest_element(), init(), push_youngest_element(), reset(), and reset_history().
The documentation for this class was generated from the following files:
libraries/AP_NavEKF/EKF_Buffer.h
libraries/AP_NavEKF/EKF_Buffer.cpp