APM:Libraries: AP_Mount_Siyi Class Reference
AP_Mount_Siyi Class Reference
#include <AP_Mount_Siyi.h>
Classes
struct FirmwareVersion
struct GimbalConfigInfo
struct HWInfo
struct PACKED
struct Version
Public Member Functions
CLASS_NO_COPY (AP_Mount_Siyi)
void init () override
void update () override
bool healthy () const override
bool has_roll_control () const override
bool has_pan_control () const override
bool take_picture () override
bool record_video (bool start_recording) override
bool set_zoom (ZoomType zoom_type, float zoom_value) override
SetFocusResult set_focus (FocusType focus_type, float focus_value) override
bool set_lens (uint8_t lens) override
void send_camera_information (mavlink_channel_t chan) const override
void send_camera_settings (mavlink_channel_t chan) const override
bool get_rangefinder_distance (float &distance_m) const override
AP_Mount_Backend (class AP_Mount &frontend, class AP_Mount_Params &params, uint8_t instance)
Public Member Functions inherited from AP_Mount_Backend
AP_Mount_Backend (class AP_Mount &frontend, class AP_Mount_Params &params, uint8_t instance)
void set_dev_id (uint32_t id)
virtual void update_fast ()
virtual bool has_pitch_control () const
bool valid_mode (MAV_MOUNT_MODE mode) const
enum MAV_MOUNT_MODE get_mode () const
bool set_mode (enum MAV_MOUNT_MODE mode)
void set_yaw_lock (bool yaw_lock)
void set_angle_target (float roll_deg, float pitch_deg, float yaw_deg, bool yaw_is_earth_frame)
void set_rate_target (float roll_degs, float pitch_degs, float yaw_degs, bool yaw_is_earth_frame)
void set_roi_target (const Location &target_loc)
void clear_roi_target ()
void set_target_sysid (uint8_t sysid)
MAV_RESULT handle_command_do_mount_control (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_gimbal_manager_configure (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
void send_gimbal_device_attitude_status (mavlink_channel_t chan)
virtual uint32_t get_gimbal_manager_capability_flags () const
void send_gimbal_manager_information (mavlink_channel_t chan)
void send_gimbal_manager_status (mavlink_channel_t chan)
virtual void handle_gimbal_report (mavlink_channel_t chan, const mavlink_message_t &msg)
virtual void handle_param_value (const mavlink_message_t &msg)
bool handle_global_position_int (uint8_t msg_sysid, const mavlink_global_position_int_t &packet)
virtual void handle_gimbal_device_information (const mavlink_message_t &msg)
virtual void handle_gimbal_device_attitude_status (const mavlink_message_t &msg)
bool get_rate_target (float &roll_degs, float &pitch_degs, float &yaw_degs, bool &yaw_is_earth_frame)
bool get_angle_target (float &roll_deg, float &pitch_deg, float &yaw_deg, bool &yaw_is_earth_frame)
virtual bool get_location_target (Location &target_loc)
virtual void set_attitude_euler (float roll_deg, float pitch_deg, float yaw_bf_deg)
void write_log (uint64_t timestamp_us)
virtual bool set_tracking (TrackingType tracking_type, const Vector2f &p1, const Vector2f &p2)
virtual void send_camera_capture_status (mavlink_channel_t chan) const
Protected Member Functions
bool get_attitude_quaternion (Quaternion &att_quat) override
bool get_angular_velocity (Vector3f &rates) override
Protected Member Functions inherited from AP_Mount_Backend
bool yaw_range_valid () const
virtual bool suppress_heartbeat () const
void set_rctargeting_on_rcinput_change ()
void get_rc_input (float &roll_in, float &pitch_in, float &yaw_in) const
void get_rc_target (MountTargetType &target_type, MountTarget &rpy) const
bool get_angle_target_to_location (const Location &loc, MountTarget &angle_rad) const WARN_IF_UNUSED
bool get_angle_target_to_roi (MountTarget &angle_rad) const WARN_IF_UNUSED
bool get_angle_target_to_home (MountTarget &angle_rad) const WARN_IF_UNUSED
bool get_angle_target_to_sysid (MountTarget &angle_rad) const WARN_IF_UNUSED
void update_angle_target_from_rate (const MountTarget &rate_rad, MountTarget &angle_rad) const
uint16_t get_gimbal_device_flags () const
void send_warning_to_GCS (const char *warning_str)
Private Types
enum class SiyiCommandId {
ACQUIRE_FIRMWARE_VERSION = 0x01 , HARDWARE_ID = 0x02 , AUTO_FOCUS = 0x04 , MANUAL_ZOOM_AND_AUTO_FOCUS = 0x05 ,
MANUAL_FOCUS = 0x06 , GIMBAL_ROTATION = 0x07 , CENTER = 0x08 , ACQUIRE_GIMBAL_CONFIG_INFO = 0x0A ,
FUNCTION_FEEDBACK_INFO = 0x0B , PHOTO = 0x0C , ACQUIRE_GIMBAL_ATTITUDE = 0x0D , ABSOLUTE_ZOOM = 0x0F ,
SET_CAMERA_IMAGE_TYPE = 0x11 , READ_RANGEFINDER = 0x15 , EXTERNAL_ATTITUDE = 0x22 , SET_TIME = 0x30
}
enum class FunctionFeedbackInfo : uint8_t {
SUCCESS = 0 , FAILED_TO_TAKE_PHOTO = 1 , HDR_ON = 2 , HDR_OFF = 3 ,
FAILED_TO_RECORD_VIDEO = 4
}
enum class PhotoFunction : uint8_t {
TAKE_PICTURE = 0 , HDR_TOGGLE = 1 , RECORD_VIDEO_TOGGLE = 2 , LOCK_MODE = 3 ,
FOLLOW_MODE = 4 , FPV_MODE = 5
}
enum class ParseState : uint8_t {
WAITING_FOR_HEADER_LOW , WAITING_FOR_HEADER_HIGH , WAITING_FOR_CTRL , WAITING_FOR_DATALEN_LOW ,
WAITING_FOR_DATALEN_HIGH , WAITING_FOR_SEQ_LOW , WAITING_FOR_SEQ_HIGH , WAITING_FOR_CMDID ,
WAITING_FOR_DATA , WAITING_FOR_CRC_LOW , WAITING_FOR_CRC_HIGH
}
enum class HardwareModel : uint8_t {
UNKNOWN = 0 , A2 , A8 , ZR10 ,
ZR30 , ZT30
}
enum class HdrStatus : uint8_t { OFF = 0 , ON = 1 }
enum class RecordingStatus : uint8_t { OFF = 0 , ON = 1 , NO_CARD = 2 , DATA_LOSS = 3 }
enum class GimbalMotionMode : uint8_t { LOCK = 0 , FOLLOW = 1 , FPV = 2 }
enum class GimbalMountingDirection : uint8_t { UNDEFINED = 0 , NORMAL = 1 , UPSIDE_DOWN = 2 }
enum class VideoOutputStatus : uint8_t { HDMI = 0 , CVBS = 1 }
enum class CameraImageType : uint8_t {
MAIN_PIP_ZOOM_THERMAL_SUB_WIDEANGLE = 0 , MAIN_PIP_WIDEANGLE_THERMAL_SUB_ZOOM = 1 , MAIN_PIP_ZOOM_WIDEANGLE_SUB_THERMAL = 2 , MAIN_ZOOM_SUB_THERMAL = 3 ,
MAIN_ZOOM_SUB_WIDEANGLE = 4 , MAIN_WIDEANGLE_SUB_THERMAL = 5 , MAIN_WIDEANGLE_SUB_ZOOM = 6 , MAIN_THERMAL_SUB_ZOOM = 7 ,
MAIN_THERMAL_SUB_WIDEANGLE = 8
}
Private Member Functions
void read_incoming_packets ()
void process_packet ()
bool send_packet (SiyiCommandId cmd_id, const uint8_t *databuff, uint8_t databuff_len)
bool send_1byte_packet (SiyiCommandId cmd_id, uint8_t data_byte)
void request_firmware_version ()
void request_hardware_id ()
void request_configuration ()
void request_function_feedback_info ()
void request_gimbal_attitude ()
void request_rangefinder_distance ()
void rotate_gimbal (int8_t pitch_scalar, int8_t yaw_scalar, bool yaw_is_ef)
bool set_motion_mode (const GimbalMotionMode mode, const bool force=false)
void send_target_rates (float pitch_rads, float yaw_rads, bool yaw_is_ef)
void send_target_angles (float pitch_rad, float yaw_rad, bool yaw_is_ef)
bool send_zoom_rate (float zoom_value)
bool send_zoom_mult (float zoom_mult)
float get_zoom_mult_max () const
void update_zoom_control ()
const char * get_model_name () const
void check_firmware_version () const
void send_attitude (void)
Private Attributes
enum AP_Mount_Siyi::HardwareModel _hardware_model
AP_HAL::UARTDriver * _uart
bool _initialised
bool _got_hardware_id
FirmwareVersion _fw_version
uint8_t _msg_buff [AP_MOUNT_SIYI_PACKETLEN_MAX]
uint8_t _msg_buff_len
const uint8_t _msg_buff_data_start = 8
struct AP_Mount_Siyi::PACKED _parsed_msg
uint32_t _last_send_ms
uint16_t _last_seq
Vector3f _current_angle_rad
Vector3f _current_rates_rads
uint32_t _last_current_angle_rad_ms
uint32_t _last_req_current_angle_rad_ms
ZoomType _zoom_type
float _zoom_rate_target
float _zoom_mult
uint32_t _last_zoom_control_ms
GimbalConfigInfo _config_info
uint32_t _last_rangefinder_req_ms
uint32_t _last_rangefinder_dist_ms
float _rangefinder_dist_m
uint32_t _last_attitude_send_ms
uint8_t sent_time_count
Static Private Attributes
static const HWInfo hardware_lookup_table []
Additional Inherited Members
Protected Types inherited from AP_Mount_Backend
enum class MountTargetType { ANGLE , RATE }
Protected Attributes inherited from AP_Mount_Backend
AP_Mount & _frontend
AP_Mount_Params & _params
uint8_t _instance
MAV_MOUNT_MODE _mode
bool _yaw_lock
struct {
MountTargetType target_type
MountTarget angle_rad
MountTarget rate_rads
} mnt_target
Location _roi_target
bool _roi_target_set
uint8_t _target_sysid
Location _target_sysid_location
bool _target_sysid_location_set
uint32_t _last_warning_ms
struct {
int16_t roll_in
int16_t pitch_in
int16_t yaw_in
} last_rc_input
struct AP_Mount_Backend::mavlink_control_id_t mavlink_control_id
Detailed Description
Definition at line 32 of file AP_Mount_Siyi.h.
Member Enumeration Documentation
CameraImageType
enum class AP_Mount_Siyi::CameraImageType : uint8_t strong private
Enumerator
MAIN_PIP_ZOOM_THERMAL_SUB_WIDEANGLE
MAIN_PIP_WIDEANGLE_THERMAL_SUB_ZOOM
MAIN_PIP_ZOOM_WIDEANGLE_SUB_THERMAL
MAIN_ZOOM_SUB_THERMAL
MAIN_ZOOM_SUB_WIDEANGLE
MAIN_WIDEANGLE_SUB_THERMAL
MAIN_WIDEANGLE_SUB_ZOOM
MAIN_THERMAL_SUB_ZOOM
MAIN_THERMAL_SUB_WIDEANGLE
Definition at line 210 of file AP_Mount_Siyi.h.
FunctionFeedbackInfo
enum class AP_Mount_Siyi::FunctionFeedbackInfo : uint8_t strong private
Enumerator
SUCCESS
FAILED_TO_TAKE_PHOTO
HDR_ON
HDR_OFF
FAILED_TO_RECORD_VIDEO
Definition at line 125 of file AP_Mount_Siyi.h.
GimbalMotionMode
enum class AP_Mount_Siyi::GimbalMotionMode : uint8_t strong private
Enumerator
LOCK
FOLLOW
FPV
Definition at line 180 of file AP_Mount_Siyi.h.
GimbalMountingDirection
enum class AP_Mount_Siyi::GimbalMountingDirection : uint8_t strong private
Enumerator
UNDEFINED
NORMAL
UPSIDE_DOWN
Definition at line 186 of file AP_Mount_Siyi.h.
HardwareModel
enum class AP_Mount_Siyi::HardwareModel : uint8_t strong private
Enumerator
UNKNOWN
A2
A8
ZR10
ZR30
ZT30
Definition at line 159 of file AP_Mount_Siyi.h.
HdrStatus
enum class AP_Mount_Siyi::HdrStatus : uint8_t strong private
Enumerator
OFF
ON
Definition at line 168 of file AP_Mount_Siyi.h.
ParseState
enum class AP_Mount_Siyi::ParseState : uint8_t strong private
Enumerator
WAITING_FOR_HEADER_LOW
WAITING_FOR_HEADER_HIGH
WAITING_FOR_CTRL
WAITING_FOR_DATALEN_LOW
WAITING_FOR_DATALEN_HIGH
WAITING_FOR_SEQ_LOW
WAITING_FOR_SEQ_HIGH
WAITING_FOR_CMDID
WAITING_FOR_DATA
WAITING_FOR_CRC_LOW
WAITING_FOR_CRC_HIGH
Definition at line 144 of file AP_Mount_Siyi.h.
PhotoFunction
enum class AP_Mount_Siyi::PhotoFunction : uint8_t strong private
Enumerator
TAKE_PICTURE
HDR_TOGGLE
RECORD_VIDEO_TOGGLE
LOCK_MODE
FOLLOW_MODE
FPV_MODE
Definition at line 134 of file AP_Mount_Siyi.h.
RecordingStatus
enum class AP_Mount_Siyi::RecordingStatus : uint8_t strong private
Enumerator
OFF
ON
NO_CARD
DATA_LOSS
Definition at line 173 of file AP_Mount_Siyi.h.
SiyiCommandId
enum class AP_Mount_Siyi::SiyiCommandId strong private
Enumerator
ACQUIRE_FIRMWARE_VERSION
HARDWARE_ID
AUTO_FOCUS
MANUAL_ZOOM_AND_AUTO_FOCUS
MANUAL_FOCUS
GIMBAL_ROTATION
CENTER
ACQUIRE_GIMBAL_CONFIG_INFO
FUNCTION_FEEDBACK_INFO
PHOTO
ACQUIRE_GIMBAL_ATTITUDE
ABSOLUTE_ZOOM
SET_CAMERA_IMAGE_TYPE
READ_RANGEFINDER
EXTERNAL_ATTITUDE
SET_TIME
Definition at line 105 of file AP_Mount_Siyi.h.
VideoOutputStatus
enum class AP_Mount_Siyi::VideoOutputStatus : uint8_t strong private
Enumerator
HDMI
CVBS
Definition at line 192 of file AP_Mount_Siyi.h.
Member Function Documentation
AP_Mount_Backend()
AP_Mount_Backend::AP_Mount_Backend (class AP_Mount & frontend, class AP_Mount_Params & params, uint8_t instance) inline
Definition at line 37 of file AP_Mount_Backend.h.
check_firmware_version()
void AP_Mount_Siyi::check_firmware_version () const private
Definition at line 1072 of file AP_Mount_Siyi.cpp.
Referenced by process_packet().
CLASS_NO_COPY()
AP_Mount_Siyi::CLASS_NO_COPY (AP_Mount_Siyi)
get_angular_velocity()
bool AP_Mount_Siyi::get_angular_velocity (Vector3f & rates) inline override protected virtual
Reimplemented from AP_Mount_Backend.
Definition at line 97 of file AP_Mount_Siyi.h.
get_attitude_quaternion()
bool AP_Mount_Siyi::get_attitude_quaternion (Quaternion & att_quat) override protected virtual
Implements AP_Mount_Backend.
Definition at line 202 of file AP_Mount_Siyi.cpp.
get_model_name()
const char * AP_Mount_Siyi::get_model_name () const private
Definition at line 1044 of file AP_Mount_Siyi.cpp.
Referenced by process_packet(), and send_camera_information().
get_rangefinder_distance()
bool AP_Mount_Siyi::get_rangefinder_distance (float & distance_m) const override virtual
Reimplemented from AP_Mount_Backend.
Definition at line 1054 of file AP_Mount_Siyi.cpp.
get_zoom_mult_max()
float AP_Mount_Siyi::get_zoom_mult_max () const private
Definition at line 821 of file AP_Mount_Siyi.cpp.
Referenced by send_camera_settings(), and set_zoom().
has_pan_control()
bool AP_Mount_Siyi::has_pan_control () const inline override virtual
Implements AP_Mount_Backend.
Definition at line 55 of file AP_Mount_Siyi.h.
has_roll_control()
bool AP_Mount_Siyi::has_roll_control () const inline override virtual
Reimplemented from AP_Mount_Backend.
Definition at line 52 of file AP_Mount_Siyi.h.
healthy()
bool AP_Mount_Siyi::healthy () const override virtual
Reimplemented from AP_Mount_Backend.
Definition at line 184 of file AP_Mount_Siyi.cpp.
init()
void AP_Mount_Siyi::init () override virtual
Reimplemented from AP_Mount_Backend.
Definition at line 36 of file AP_Mount_Siyi.cpp.
process_packet()
void AP_Mount_Siyi::process_packet () private
Definition at line 332 of file AP_Mount_Siyi.cpp.
Referenced by read_incoming_packets().
read_incoming_packets()
void AP_Mount_Siyi::read_incoming_packets () private
Definition at line 211 of file AP_Mount_Siyi.cpp.
Referenced by update().
record_video()
bool AP_Mount_Siyi::record_video (bool start_recording) override virtual
Reimplemented from AP_Mount_Backend.
Definition at line 743 of file AP_Mount_Siyi.cpp.
request_configuration()
void AP_Mount_Siyi::request_configuration () inline private
Definition at line 249 of file AP_Mount_Siyi.h.
Referenced by record_video(), set_motion_mode(), and update().
request_firmware_version()
void AP_Mount_Siyi::request_firmware_version () inline private
Definition at line 247 of file AP_Mount_Siyi.h.
Referenced by update().
request_function_feedback_info()
void AP_Mount_Siyi::request_function_feedback_info () inline private
Definition at line 250 of file AP_Mount_Siyi.h.
request_gimbal_attitude()
void AP_Mount_Siyi::request_gimbal_attitude () inline private
Definition at line 251 of file AP_Mount_Siyi.h.
Referenced by update().
request_hardware_id()
void AP_Mount_Siyi::request_hardware_id () inline private
Definition at line 248 of file AP_Mount_Siyi.h.
Referenced by update().
request_rangefinder_distance()
void AP_Mount_Siyi::request_rangefinder_distance () inline private
Definition at line 252 of file AP_Mount_Siyi.h.
Referenced by update().
rotate_gimbal()
void AP_Mount_Siyi::rotate_gimbal (int8_t pitch_scalar, int8_t yaw_scalar, bool yaw_is_ef) private
Definition at line 645 of file AP_Mount_Siyi.cpp.
Referenced by send_target_angles(), and send_target_rates().
send_1byte_packet()
bool AP_Mount_Siyi::send_1byte_packet (SiyiCommandId cmd_id, uint8_t data_byte) private
Definition at line 638 of file AP_Mount_Siyi.cpp.
Referenced by record_video(), send_zoom_rate(), set_focus(), set_lens(), set_motion_mode(), and take_picture().
send_attitude()
void AP_Mount_Siyi::send_attitude (void) private
Definition at line 1121 of file AP_Mount_Siyi.cpp.
Referenced by update().
send_camera_information()
void AP_Mount_Siyi::send_camera_information (mavlink_channel_t chan) const override virtual
Reimplemented from AP_Mount_Backend.
Definition at line 966 of file AP_Mount_Siyi.cpp.
send_camera_settings()
void AP_Mount_Siyi::send_camera_settings (mavlink_channel_t chan) const override virtual
Reimplemented from AP_Mount_Backend.
Definition at line 1024 of file AP_Mount_Siyi.cpp.
send_packet()
bool AP_Mount_Siyi::send_packet (SiyiCommandId cmd_id, const uint8_t * databuff, uint8_t databuff_len) private
Definition at line 580 of file AP_Mount_Siyi.cpp.
Referenced by request_configuration(), request_firmware_version(), request_function_feedback_info(), request_gimbal_attitude(), request_hardware_id(), request_rangefinder_distance(), rotate_gimbal(), send_1byte_packet(), send_attitude(), send_zoom_mult(), and update().
send_target_angles()
void AP_Mount_Siyi::send_target_angles (float pitch_rad, float yaw_rad, bool yaw_is_ef) private
Definition at line 696 of file AP_Mount_Siyi.cpp.
Referenced by update().
send_target_rates()
void AP_Mount_Siyi::send_target_rates (float pitch_rads, float yaw_rads, bool yaw_is_ef) private
Definition at line 687 of file AP_Mount_Siyi.cpp.
Referenced by update().
send_zoom_mult()
bool AP_Mount_Siyi::send_zoom_mult (float zoom_mult) private
Definition at line 809 of file AP_Mount_Siyi.cpp.
Referenced by set_zoom().
send_zoom_rate()
bool AP_Mount_Siyi::send_zoom_rate (float zoom_value) private
Definition at line 793 of file AP_Mount_Siyi.cpp.
Referenced by set_zoom(), and update_zoom_control().
set_focus()
SetFocusResult AP_Mount_Siyi::set_focus (FocusType focus_type, float focus_value) override virtual
Reimplemented from AP_Mount_Backend.
Definition at line 891 of file AP_Mount_Siyi.cpp.
set_lens()
bool AP_Mount_Siyi::set_lens (uint8_t lens) override virtual
Reimplemented from AP_Mount_Backend.
Definition at line 922 of file AP_Mount_Siyi.cpp.
set_motion_mode()
bool AP_Mount_Siyi::set_motion_mode (const GimbalMotionMode mode, const bool force = false) private
Definition at line 663 of file AP_Mount_Siyi.cpp.
Referenced by rotate_gimbal().
set_zoom()
bool AP_Mount_Siyi::set_zoom (ZoomType zoom_type, float zoom_value) override virtual
Reimplemented from AP_Mount_Backend.
Definition at line 840 of file AP_Mount_Siyi.cpp.
take_picture()
bool AP_Mount_Siyi::take_picture () override virtual
Reimplemented from AP_Mount_Backend.
Definition at line 736 of file AP_Mount_Siyi.cpp.
update()
void AP_Mount_Siyi::update () override virtual
Implements AP_Mount_Backend.
Definition at line 48 of file AP_Mount_Siyi.cpp.
update_zoom_control()
void AP_Mount_Siyi::update_zoom_control () private
Definition at line 871 of file AP_Mount_Siyi.cpp.
Referenced by update().
Member Data Documentation
_config_info
GimbalConfigInfo AP_Mount_Siyi::_config_info private
Definition at line 329 of file AP_Mount_Siyi.h.
Referenced by process_packet(), record_video(), send_camera_settings(), send_target_angles(), and set_motion_mode().
_current_angle_rad
Vector3f AP_Mount_Siyi::_current_angle_rad private
Definition at line 317 of file AP_Mount_Siyi.h.
Referenced by get_attitude_quaternion(), process_packet(), and send_target_angles().
_current_rates_rads
Vector3f AP_Mount_Siyi::_current_rates_rads private
Definition at line 318 of file AP_Mount_Siyi.h.
Referenced by get_angular_velocity(), and process_packet().
_fw_version
FirmwareVersion AP_Mount_Siyi::_fw_version private
Definition at line 296 of file AP_Mount_Siyi.h.
Referenced by check_firmware_version(), healthy(), process_packet(), send_camera_information(), and update().
_got_hardware_id
bool AP_Mount_Siyi::_got_hardware_id private
Definition at line 294 of file AP_Mount_Siyi.h.
Referenced by check_firmware_version(), process_packet(), and update().
_hardware_model
enum AP_Mount_Siyi::HardwareModel AP_Mount_Siyi::_hardware_model private
Referenced by check_firmware_version(), get_model_name(), get_rangefinder_distance(), get_zoom_mult_max(), process_packet(), send_camera_information(), set_lens(), and update().
_initialised
bool AP_Mount_Siyi::_initialised private
Definition at line 293 of file AP_Mount_Siyi.h.
Referenced by healthy(), init(), record_video(), send_camera_information(), send_packet(), and update().
_last_attitude_send_ms
uint32_t AP_Mount_Siyi::_last_attitude_send_ms private
Definition at line 337 of file AP_Mount_Siyi.h.
Referenced by update().
_last_current_angle_rad_ms
uint32_t AP_Mount_Siyi::_last_current_angle_rad_ms private
Definition at line 319 of file AP_Mount_Siyi.h.
Referenced by healthy(), process_packet(), and send_target_angles().
_last_rangefinder_dist_ms
uint32_t AP_Mount_Siyi::_last_rangefinder_dist_ms private
Definition at line 333 of file AP_Mount_Siyi.h.
Referenced by get_rangefinder_distance(), and process_packet().
_last_rangefinder_req_ms
uint32_t AP_Mount_Siyi::_last_rangefinder_req_ms private
Definition at line 332 of file AP_Mount_Siyi.h.
Referenced by update().
_last_req_current_angle_rad_ms
uint32_t AP_Mount_Siyi::_last_req_current_angle_rad_ms private
Definition at line 320 of file AP_Mount_Siyi.h.
Referenced by update().
_last_send_ms
uint32_t AP_Mount_Siyi::_last_send_ms private
Definition at line 313 of file AP_Mount_Siyi.h.
Referenced by update().
_last_seq
uint16_t AP_Mount_Siyi::_last_seq private
Definition at line 314 of file AP_Mount_Siyi.h.
Referenced by send_packet().
_last_zoom_control_ms
uint32_t AP_Mount_Siyi::_last_zoom_control_ms private
Definition at line 326 of file AP_Mount_Siyi.h.
Referenced by update_zoom_control().
_msg_buff
uint8_t AP_Mount_Siyi::_msg_buff[AP_MOUNT_SIYI_PACKETLEN_MAX] private
Definition at line 299 of file AP_Mount_Siyi.h.
Referenced by process_packet(), and read_incoming_packets().
_msg_buff_data_start
const uint8_t AP_Mount_Siyi::_msg_buff_data_start = 8 private
Definition at line 301 of file AP_Mount_Siyi.h.
Referenced by process_packet().
_msg_buff_len
uint8_t AP_Mount_Siyi::_msg_buff_len private
Definition at line 300 of file AP_Mount_Siyi.h.
Referenced by read_incoming_packets().
_parsed_msg
struct AP_Mount_Siyi::PACKED AP_Mount_Siyi::_parsed_msg private
Referenced by process_packet(), and read_incoming_packets().
_rangefinder_dist_m
float AP_Mount_Siyi::_rangefinder_dist_m private
Definition at line 334 of file AP_Mount_Siyi.h.
Referenced by get_rangefinder_distance(), and process_packet().
_uart
AP_HAL::UARTDriver* AP_Mount_Siyi::_uart private
Definition at line 292 of file AP_Mount_Siyi.h.
Referenced by init(), read_incoming_packets(), and send_packet().
_zoom_mult
float AP_Mount_Siyi::_zoom_mult private
Definition at line 325 of file AP_Mount_Siyi.h.
Referenced by process_packet(), and send_camera_settings().
_zoom_rate_target
float AP_Mount_Siyi::_zoom_rate_target private
Definition at line 324 of file AP_Mount_Siyi.h.
Referenced by set_zoom(), and update_zoom_control().
_zoom_type
ZoomType AP_Mount_Siyi::_zoom_type private
Definition at line 323 of file AP_Mount_Siyi.h.
Referenced by set_zoom(), and update_zoom_control().
hardware_lookup_table
const AP_Mount_Siyi::HWInfo AP_Mount_Siyi::hardware_lookup_table static private
Initial value:
{
        {{'0','0'}, "Unknown"},
        {{'7','5'}, "A2"},
        {{'7','3'}, "A8"},
        {{'6','B'}, "ZR10"},
        {{'7','8'}, "ZR30"},
        {{'7','A'}, "ZT30"},
}
Definition at line 26 of file AP_Mount_Siyi.h.
Referenced by get_model_name(), and process_packet().
sent_time_count
uint8_t AP_Mount_Siyi::sent_time_count private
Definition at line 348 of file AP_Mount_Siyi.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/AP_Mount/AP_Mount_Siyi.h
libraries/AP_Mount/AP_Mount_Siyi.cpp