APM:Libraries: Linux::Thread Class Reference
Linux::Thread Class Reference
#include <Thread.h>
Classes
struct stack_debug
Public Member Functions
FUNCTOR_TYPEDEF (task_t, void)
Thread (task_t t)
virtual ~Thread ()
bool start (const char *name, int policy, int prio)
bool is_current_thread ()
bool is_started () const
size_t get_stack_usage ()
bool set_stack_size (size_t stack_size)
void set_auto_free (bool auto_free)
virtual bool stop ()
bool join ()
Protected Member Functions
virtual bool _run ()
void _poison_stack ()
Static Protected Member Functions
static void * _run_trampoline (void *arg)
Protected Attributes
task_t _task
bool _started = false
bool _should_exit = false
bool _auto_free = false
pthread_t _ctx = 0
struct Linux::Thread::stack_debug _stack_debug
size_t _stack_size = 0
Detailed Description
Definition at line 30 of file Thread.h.
Constructor & Destructor Documentation
Thread()
Linux::Thread::Thread (task_t t) inline
Definition at line 34 of file Thread.h.
~Thread()
virtual Linux::Thread::~Thread () inline virtual
Definition at line 36 of file Thread.h.
Member Function Documentation
_poison_stack()
void Linux::Thread::_poison_stack () protected
Definition at line 80 of file Thread.cpp.
Referenced by _run_trampoline().
_run()
bool Linux::Thread::_run () protected virtual
Reimplemented in Linux::Scheduler::SchedulerThread, TestThread1, and Linux::PeriodicThread.
Definition at line 50 of file Thread.cpp.
Referenced by _run_trampoline().
_run_trampoline()
void * Linux::Thread::_run_trampoline (void * arg) static protected
Definition at line 37 of file Thread.cpp.
Referenced by start().
FUNCTOR_TYPEDEF()
Linux::Thread::FUNCTOR_TYPEDEF (task_t , void)
get_stack_usage()
size_t Linux::Thread::get_stack_usage ()
Definition at line 132 of file Thread.cpp.
Referenced by Linux::Scheduler::_debug_stack().
is_current_thread()
bool Linux::Thread::is_current_thread ()
Definition at line 209 of file Thread.cpp.
is_started()
bool Linux::Thread::is_started () const inline
Definition at line 42 of file Thread.h.
Referenced by Linux::I2CDevice::register_periodic_callback(), Linux::SPIDevice::register_periodic_callback(), Linux::PollerThread::stop(), Linux::PeriodicThread::stop(), TEST(), and TEST().
join()
bool Linux::Thread::join ()
Definition at line 214 of file Thread.cpp.
Referenced by Linux::Scheduler::teardown(), TEST(), and TEST().
set_auto_free()
void Linux::Thread::set_auto_free (bool auto_free) inline
Definition at line 48 of file Thread.h.
Referenced by Linux::Scheduler::thread_create().
set_stack_size()
bool Linux::Thread::set_stack_size (size_t stack_size)
Definition at line 242 of file Thread.cpp.
Referenced by Linux::I2CDevice::register_periodic_callback(), Linux::SPIDevice::register_periodic_callback(), and Linux::Scheduler::thread_create().
start()
bool Linux::Thread::start (const char * name, int policy, int prio)
Definition at line 161 of file Thread.cpp.
Referenced by Linux::I2CDevice::register_periodic_callback(), Linux::SPIDevice::register_periodic_callback(), TEST(), TEST(), TEST(), TEST(), and Linux::Scheduler::thread_create().
stop()
virtual bool Linux::Thread::stop () inline virtual
Reimplemented in Linux::PollerThread, and Linux::PeriodicThread.
Definition at line 50 of file Thread.h.
Member Data Documentation
_auto_free
bool Linux::Thread::_auto_free = false protected
Definition at line 69 of file Thread.h.
Referenced by _run_trampoline(), and set_auto_free().
_ctx
pthread_t Linux::Thread::_ctx = 0 protected
Definition at line 70 of file Thread.h.
Referenced by is_current_thread(), join(), and start().
_should_exit
bool Linux::Thread::_should_exit = false protected
Definition at line 68 of file Thread.h.
Referenced by Linux::PeriodicThread::_run(), Linux::PollerThread::mainloop(), Linux::PollerThread::stop(), and Linux::PeriodicThread::stop().
_stack_debug
struct Linux::Thread::stack_debug Linux::Thread::_stack_debug protected
Referenced by _poison_stack(), and get_stack_usage().
_stack_size
size_t Linux::Thread::_stack_size = 0 protected
Definition at line 77 of file Thread.h.
Referenced by set_stack_size(), and start().
_started
bool Linux::Thread::_started = false protected
Definition at line 67 of file Thread.h.
Referenced by Linux::PeriodicThread::_run(), is_started(), Linux::PollerThread::mainloop(), Linux::PeriodicThread::set_rate(), set_stack_size(), and start().
_task
task_t Linux::Thread::_task protected
Definition at line 66 of file Thread.h.
Referenced by _run(), and Linux::PeriodicThread::_run().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Thread.h
libraries/AP_HAL_Linux/Thread.cpp