APM:Libraries: SITL::EFI_Hirth Class Reference
SITL::EFI_Hirth Class Reference
#include <SIM_EFI_Hirth.h>
Classes
class PackedRecord
class Record1
class Record2
class Record3
class SetValues
Public Member Functions
void update ()
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
Public Member Functions inherited from SITL::SerialDevice
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Private Types
enum class PacketCode : uint8_t { DataRecord1 = 4 , DataRecord2 = 11 , DataRecord3 = 13 , SetValues = 201 }
Private Member Functions
void update_receive ()
void update_send ()
void assert_receive_size (uint8_t receive_size)
void handle_set_values ()
void send_record1 ()
void send_record2 ()
void send_record3 ()
uint16_t engine_status_field_value () const
void init ()
void update_engine_model ()
Private Attributes
Record1 record1
Record2 record2
Record3 record3
SetValues settings
PackedRecord< Record1 > packed_record1 {PacketCode::DataRecord1, record1}
PackedRecord< Record2 > packed_record2 {PacketCode::DataRecord2, record2}
PackedRecord< Record3 > packed_record3 {PacketCode::DataRecord3, record3}
struct {
PacketCode code
uint32_t time_ms
} requested_data_record
uint8_t receive_buf [32]
uint8_t receive_buf_ofs
float throttle
bool init_done = false
struct {
float cht1_temperature
float cht2_temperature
uint32_t last_update_ms
} engine
Additional Inherited Members
Protected Member Functions inherited from SITL::SerialDevice
bool init_sitl_pointer () WARN_IF_UNUSED
Protected Attributes inherited from SITL::SerialDevice
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Detailed Description
Definition at line 37 of file SIM_EFI_Hirth.h.
Member Enumeration Documentation
PacketCode
enum class SITL::EFI_Hirth::PacketCode : uint8_t strong private
Enumerator
DataRecord1
DataRecord2
DataRecord3
SetValues
Definition at line 54 of file SIM_EFI_Hirth.h.
Member Function Documentation
assert_receive_size()
void EFI_Hirth::assert_receive_size (uint8_t receive_size) private
Definition at line 81 of file SIM_EFI_Hirth.cpp.
Referenced by handle_set_values(), and update_receive().
engine_status_field_value()
uint16_t EFI_Hirth::engine_status_field_value () const private
Definition at line 183 of file SIM_EFI_Hirth.cpp.
handle_set_values()
void EFI_Hirth::handle_set_values () private
Definition at line 88 of file SIM_EFI_Hirth.cpp.
Referenced by update_receive().
init()
void EFI_Hirth::init () private
Definition at line 148 of file SIM_EFI_Hirth.cpp.
Referenced by update().
send_record1()
void SITL::EFI_Hirth::send_record1 () private
Definition at line 193 of file SIM_EFI_Hirth.cpp.
Referenced by update_send().
send_record2()
void SITL::EFI_Hirth::send_record2 () private
Definition at line 212 of file SIM_EFI_Hirth.cpp.
Referenced by update_send().
send_record3()
void SITL::EFI_Hirth::send_record3 () private
Definition at line 230 of file SIM_EFI_Hirth.cpp.
Referenced by update_send().
SerialDevice()
SerialDevice::SerialDevice (uint16_t tx_bufsize = 512, uint16_t rx_bufsize = 512)
Definition at line 29 of file SIM_SerialDevice.cpp.
update()
void EFI_Hirth::update ()
Definition at line 163 of file SIM_EFI_Hirth.cpp.
Referenced by HALSITL::SITL_State_Common::sim_update().
update_engine_model()
void EFI_Hirth::update_engine_model () private
Definition at line 122 of file SIM_EFI_Hirth.cpp.
Referenced by update().
update_receive()
void EFI_Hirth::update_receive () private
Definition at line 30 of file SIM_EFI_Hirth.cpp.
Referenced by update().
update_send()
void EFI_Hirth::update_send () private
Definition at line 95 of file SIM_EFI_Hirth.cpp.
Referenced by update().
Member Data Documentation
cht1_temperature
float SITL::EFI_Hirth::cht1_temperature
Definition at line 234 of file SIM_EFI_Hirth.h.
cht2_temperature
float SITL::EFI_Hirth::cht2_temperature
Definition at line 235 of file SIM_EFI_Hirth.h.
code
PacketCode SITL::EFI_Hirth::code
Definition at line 217 of file SIM_EFI_Hirth.h.
[struct]
struct { ... } SITL::EFI_Hirth::engine
Referenced by init(), and update_engine_model().
init_done
bool SITL::EFI_Hirth::init_done = false private
Definition at line 229 of file SIM_EFI_Hirth.h.
Referenced by init(), and update().
last_update_ms
uint32_t SITL::EFI_Hirth::last_update_ms
Definition at line 236 of file SIM_EFI_Hirth.h.
packed_record1
PackedRecord<Record1> SITL::EFI_Hirth::packed_record1 {PacketCode::DataRecord1, record1} private
Definition at line 212 of file SIM_EFI_Hirth.h.
packed_record2
PackedRecord<Record2> SITL::EFI_Hirth::packed_record2 {PacketCode::DataRecord2, record2} private
Definition at line 213 of file SIM_EFI_Hirth.h.
packed_record3
PackedRecord<Record3> SITL::EFI_Hirth::packed_record3 {PacketCode::DataRecord3, record3} private
Definition at line 214 of file SIM_EFI_Hirth.h.
receive_buf
uint8_t SITL::EFI_Hirth::receive_buf[32] private
Definition at line 221 of file SIM_EFI_Hirth.h.
Referenced by assert_receive_size(), handle_set_values(), and update_receive().
receive_buf_ofs
uint8_t SITL::EFI_Hirth::receive_buf_ofs private
Definition at line 222 of file SIM_EFI_Hirth.h.
Referenced by update_receive().
record1
Record1 SITL::EFI_Hirth::record1 private
Definition at line 205 of file SIM_EFI_Hirth.h.
record2
Record2 SITL::EFI_Hirth::record2 private
Definition at line 206 of file SIM_EFI_Hirth.h.
record3
Record3 SITL::EFI_Hirth::record3 private
Definition at line 207 of file SIM_EFI_Hirth.h.
[struct]
struct { ... } SITL::EFI_Hirth::requested_data_record
Referenced by update_receive(), and update_send().
settings
SetValues SITL::EFI_Hirth::settings private
Definition at line 210 of file SIM_EFI_Hirth.h.
Referenced by handle_set_values(), and update().
throttle
float SITL::EFI_Hirth::throttle private
Definition at line 224 of file SIM_EFI_Hirth.h.
Referenced by update().
time_ms
uint32_t SITL::EFI_Hirth::time_ms
Definition at line 218 of file SIM_EFI_Hirth.h.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_EFI_Hirth.h
libraries/SITL/SIM_EFI_Hirth.cpp