APM:Libraries: AP_BattMonitor_Backend Class Reference
AP_BattMonitor_Backend Class Reference abstract
#include <AP_BattMonitor_Backend.h>
Public Member Functions
AP_BattMonitor_Backend (AP_BattMonitor &mon, AP_BattMonitor::BattMonitor_State &mon_state, AP_BattMonitor_Params &params)
virtual ~AP_BattMonitor_Backend (void)
virtual void init ()
virtual void read ()=0
virtual bool has_time_remaining () const
returns true if battery monitor instance provides time remaining info
virtual bool has_consumed_energy () const
returns true if battery monitor instance provides consumed energy info
virtual bool has_current () const =0
returns true if battery monitor instance provides current info
virtual bool has_cell_voltages () const
virtual bool has_temperature () const
virtual bool get_temperature (float &temperature) const
virtual bool capacity_remaining_pct (uint8_t &percentage) const WARN_IF_UNUSED
virtual bool get_cycle_count (uint16_t &cycles) const
bool get_state_of_health_pct (uint8_t &soh_pct) const
float voltage_resting_estimate () const
virtual void update_resistance_estimate ()
virtual AP_BattMonitor::Failsafe update_failsafes (void)
bool arming_checks (char *buffer, size_t buflen) const
virtual bool reset_remaining (float percentage)
virtual uint32_t get_mavlink_fault_bitmask () const
void Log_Write_BAT (const uint8_t instance, const uint64_t time_us) const
void Log_Write_BCL (const uint8_t instance, const uint64_t time_us) const
virtual void mppt_set_powered_state (bool power_on)
void update_esc_telem_outbound ()
bool option_is_set (const AP_BattMonitor_Params::Options option) const
Static Public Member Functions
static float calculate_mah (float amps, float dt_us)
Protected Member Functions
void check_failsafe_types (bool &low_voltage, bool &low_capacity, bool &critical_voltage, bool &critical_capacity) const
void update_consumed (AP_BattMonitor::BattMonitor_State &state, uint32_t dt_us)
Protected Attributes
AP_BattMonitor & _mon
AP_BattMonitor::BattMonitor_State & _state
AP_BattMonitor_Params & _params
Private Attributes
uint32_t _resistance_timer_ms
float _voltage_filt
float _current_max_amps
float _current_filt_amps
float _resistance_voltage_ref
float _resistance_current_ref
Detailed Description
Definition at line 25 of file AP_BattMonitor_Backend.h.
Constructor & Destructor Documentation
AP_BattMonitor_Backend()
AP_BattMonitor_Backend::AP_BattMonitor_Backend (AP_BattMonitor & mon, AP_BattMonitor::BattMonitor_State & mon_state, AP_BattMonitor_Params & params)
Definition at line 33 of file AP_BattMonitor_Backend.cpp.
~AP_BattMonitor_Backend()
virtual AP_BattMonitor_Backend::~AP_BattMonitor_Backend (void) inline virtual
Definition at line 33 of file AP_BattMonitor_Backend.h.
Member Function Documentation
arming_checks()
bool AP_BattMonitor_Backend::arming_checks (char * buffer, size_t buflen) const
Definition at line 184 of file AP_BattMonitor_Backend.cpp.
calculate_mah()
static float AP_BattMonitor_Backend::calculate_mah (float amps, float dt_us) inline static
Definition at line 100 of file AP_BattMonitor_Backend.h.
Referenced by calculate_mah(), and update_consumed().
capacity_remaining_pct()
bool AP_BattMonitor_Backend::capacity_remaining_pct (uint8_t & percentage) const virtual
Definition at line 43 of file AP_BattMonitor_Backend.cpp.
Referenced by AP_BattMonitor::capacity_remaining_pct().
check_failsafe_types()
void AP_BattMonitor_Backend::check_failsafe_types (bool & low_voltage, bool & low_capacity, bool & critical_voltage, bool & critical_capacity) const protected
Definition at line 213 of file AP_BattMonitor_Backend.cpp.
Referenced by arming_checks(), and update_failsafes().
get_cycle_count()
virtual bool AP_BattMonitor_Backend::get_cycle_count (uint16_t & cycles) const inline virtual
Reimplemented in AP_BattMonitor_SMBus.
Definition at line 64 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor::get_cycle_count().
get_mavlink_fault_bitmask()
virtual uint32_t AP_BattMonitor_Backend::get_mavlink_fault_bitmask () const inline virtual
Definition at line 86 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor::get_mavlink_fault_bitmask().
get_state_of_health_pct()
bool AP_BattMonitor_Backend::get_state_of_health_pct (uint8_t & soh_pct) const
Definition at line 115 of file AP_BattMonitor_Backend.cpp.
Referenced by AP_BattMonitor::get_state_of_health_pct().
get_temperature()
bool AP_BattMonitor_Backend::get_temperature (float & temperature) const virtual
Definition at line 293 of file AP_BattMonitor_Backend.cpp.
Referenced by AP_BattMonitor::get_temperature().
has_cell_voltages()
virtual bool AP_BattMonitor_Backend::has_cell_voltages () const inline virtual
Reimplemented in AP_BattMonitor_SMBus.
Definition at line 51 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor::has_cell_voltages().
has_consumed_energy()
virtual bool AP_BattMonitor_Backend::has_consumed_energy () const inline virtual
returns true if battery monitor instance provides consumed energy info
Reimplemented in AP_BattMonitor_Analog, AP_BattMonitor_Sum, and AP_BattMonitor_Synthetic_Current.
Definition at line 45 of file AP_BattMonitor_Backend.h.
has_current()
virtual bool AP_BattMonitor_Backend::has_current () const pure virtual
returns true if battery monitor instance provides current info
Implemented in AP_BattMonitor_Analog, AP_BattMonitor_Bebop, AP_BattMonitor_SMBus, AP_BattMonitor_Sum, and AP_BattMonitor_Synthetic_Current.
Referenced by capacity_remaining_pct(), check_failsafe_types(), and update_resistance_estimate().
has_temperature()
virtual bool AP_BattMonitor_Backend::has_temperature () const inline virtual
Reimplemented in AP_BattMonitor_SMBus.
Definition at line 54 of file AP_BattMonitor_Backend.h.
Referenced by get_temperature().
has_time_remaining()
virtual bool AP_BattMonitor_Backend::has_time_remaining () const inline virtual
returns true if battery monitor instance provides time remaining info
Definition at line 42 of file AP_BattMonitor_Backend.h.
init()
virtual void AP_BattMonitor_Backend::init (void) inline virtual
Reimplemented in AP_BattMonitor_Bebop, AP_BattMonitor_Analog, AP_BattMonitor_SMBus, AP_BattMonitor_SMBus_SUI, AP_BattMonitor_Sum, and AP_BattMonitor_Synthetic_Current.
Definition at line 36 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor::init().
Log_Write_BAT()
void AP_BattMonitor_Backend::Log_Write_BAT (const uint8_t instance, const uint64_t time_us) const
Referenced by AP_BattMonitor::read().
Log_Write_BCL()
void AP_BattMonitor_Backend::Log_Write_BCL (const uint8_t instance, const uint64_t time_us) const
Referenced by AP_BattMonitor::read().
mppt_set_powered_state()
virtual void AP_BattMonitor_Backend::mppt_set_powered_state (bool power_on) inline virtual
Definition at line 93 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor::MPPT_set_powered_state().
option_is_set()
bool AP_BattMonitor_Backend::option_is_set (const AP_BattMonitor_Params::Options option) const inline
Definition at line 103 of file AP_BattMonitor_Backend.h.
read()
virtual void AP_BattMonitor_Backend::read () pure virtual
Implemented in AP_BattMonitor_Analog, AP_BattMonitor_Bebop, AP_BattMonitor_Sum, AP_BattMonitor_Synthetic_Current, and AP_BattMonitor_SMBus.
Referenced by AP_BattMonitor::read().
reset_remaining()
bool AP_BattMonitor_Backend::reset_remaining (float percentage) virtual
Reimplemented in AP_BattMonitor_Bebop, and AP_BattMonitor_SMBus.
Definition at line 312 of file AP_BattMonitor_Backend.cpp.
Referenced by AP_BattMonitor::reset_remaining_mask().
update_consumed()
void AP_BattMonitor_Backend::update_consumed (AP_BattMonitor::BattMonitor_State & state, uint32_t dt_us) protected
Definition at line 332 of file AP_BattMonitor_Backend.cpp.
Referenced by AP_BattMonitor_Analog::read(), AP_BattMonitor_Sum::read(), and AP_BattMonitor_Synthetic_Current::read().
update_esc_telem_outbound()
void AP_BattMonitor_Backend::update_esc_telem_outbound ()
Referenced by AP_BattMonitor::read().
update_failsafes()
AP_BattMonitor::Failsafe AP_BattMonitor_Backend::update_failsafes (void) virtual
Definition at line 130 of file AP_BattMonitor_Backend.cpp.
Referenced by AP_BattMonitor::check_failsafes(), and reset_remaining().
update_resistance_estimate()
void AP_BattMonitor_Backend::update_resistance_estimate () virtual
Definition at line 67 of file AP_BattMonitor_Backend.cpp.
Referenced by AP_BattMonitor::read().
voltage_resting_estimate()
float AP_BattMonitor_Backend::voltage_resting_estimate () const
get voltage with sag removed (based on battery current draw and resistance) this will always be greater than or equal to the raw voltage
Definition at line 124 of file AP_BattMonitor_Backend.cpp.
Referenced by check_failsafe_types(), and AP_BattMonitor::voltage_resting_estimate().
Member Data Documentation
_current_filt_amps
float AP_BattMonitor_Backend::_current_filt_amps private
Definition at line 125 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
_current_max_amps
float AP_BattMonitor_Backend::_current_max_amps private
Definition at line 124 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
_mon
AP_BattMonitor& AP_BattMonitor_Backend::_mon protected
Definition at line 112 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor_Sum::read().
_params
AP_BattMonitor_Params& AP_BattMonitor_Backend::_params protected
Definition at line 114 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor_SMBus::AP_BattMonitor_SMBus(), arming_checks(), capacity_remaining_pct(), check_failsafe_types(), AP_BattMonitor_Analog::has_current(), option_is_set(), AP_BattMonitor_Bebop::read(), AP_BattMonitor_SMBus::read(), AP_BattMonitor_SMBus::read_remaining_capacity(), reset_remaining(), and update_failsafes().
_resistance_current_ref
float AP_BattMonitor_Backend::_resistance_current_ref private
Definition at line 127 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
_resistance_timer_ms
uint32_t AP_BattMonitor_Backend::_resistance_timer_ms private
Definition at line 122 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
_resistance_voltage_ref
float AP_BattMonitor_Backend::_resistance_voltage_ref private
Definition at line 126 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
_state
AP_BattMonitor::BattMonitor_State& AP_BattMonitor_Backend::_state protected
Definition at line 113 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor_Analog::AP_BattMonitor_Analog(), AP_BattMonitor_SMBus::AP_BattMonitor_SMBus(), AP_BattMonitor_Sum::AP_BattMonitor_Sum(), AP_BattMonitor_Synthetic_Current::AP_BattMonitor_Synthetic_Current(), arming_checks(), capacity_remaining_pct(), check_failsafe_types(), get_state_of_health_pct(), get_temperature(), AP_BattMonitor_Analog::read(), AP_BattMonitor_Bebop::read(), AP_BattMonitor_Sum::read(), AP_BattMonitor_Synthetic_Current::read(), AP_BattMonitor_SMBus_SUI::read_cell_voltages(), AP_BattMonitor_SMBus::read_remaining_capacity(), AP_BattMonitor_SMBus::read_temp(), AP_BattMonitor_SMBus_Rotoye::read_temp(), reset_remaining(), AP_BattMonitor_SMBus_Generic::timer(), AP_BattMonitor_SMBus_NeoDesign::timer(), AP_BattMonitor_SMBus_SUI::timer(), update_failsafes(), AP_BattMonitor_SMBus_SUI::update_health(), update_resistance_estimate(), and voltage_resting_estimate().
_voltage_filt
float AP_BattMonitor_Backend::_voltage_filt private
Definition at line 123 of file AP_BattMonitor_Backend.h.
Referenced by update_resistance_estimate().
The documentation for this class was generated from the following files:
libraries/AP_BattMonitor/AP_BattMonitor_Backend.h
libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp