APM:Libraries: AP_InertialSensor_Invensensev3 Class Reference
AP_InertialSensor_Invensensev3 Class Reference
#include <AP_InertialSensor_Invensensev3.h>
Public Types
enum class Invensensev3_Type : uint8_t {
ICM40609 = 0 , ICM42688 , ICM42605 , ICM40605 ,
IIM42652 , ICM42670 , ICM45686
}
Public Types inherited from AP_InertialSensor_Backend
enum DevTypes {
DEVTYPE_BMI160 = 0x09 , DEVTYPE_L3G4200D = 0x10 , DEVTYPE_ACC_LSM303D = 0x11 , DEVTYPE_ACC_BMA180 = 0x12 ,
DEVTYPE_ACC_MPU6000 = 0x13 , DEVTYPE_ACC_MPU9250 = 0x16 , DEVTYPE_ACC_IIS328DQ = 0x17 , DEVTYPE_ACC_LSM9DS1 = 0x18 ,
DEVTYPE_GYR_MPU6000 = 0x21 , DEVTYPE_GYR_L3GD20 = 0x22 , DEVTYPE_GYR_MPU9250 = 0x24 , DEVTYPE_GYR_I3G4250D = 0x25 ,
DEVTYPE_GYR_LSM9DS1 = 0x26 , DEVTYPE_INS_ICM20789 = 0x27 , DEVTYPE_INS_ICM20689 = 0x28 , DEVTYPE_INS_BMI055 = 0x29 ,
DEVTYPE_SITL = 0x2A , DEVTYPE_INS_BMI088 = 0x2B , DEVTYPE_INS_ICM20948 = 0x2C , DEVTYPE_INS_ICM20648 = 0x2D ,
DEVTYPE_INS_ICM20649 = 0x2E , DEVTYPE_INS_ICM20602 = 0x2F , DEVTYPE_INS_ICM20601 = 0x30 , DEVTYPE_INS_ADIS1647X = 0x31 ,
DEVTYPE_SERIAL = 0x32 , DEVTYPE_INS_ICM40609 = 0x33 , DEVTYPE_INS_ICM42688 = 0x34 , DEVTYPE_INS_ICM42605 = 0x35 ,
DEVTYPE_INS_ICM40605 = 0x36 , DEVTYPE_INS_IIM42652 = 0x37 , DEVTYPE_BMI270 = 0x38 , DEVTYPE_INS_BMI085 = 0x39 ,
DEVTYPE_INS_ICM42670 = 0x3A , DEVTYPE_INS_ICM45686 = 0x3B , DEVTYPE_INS_SCHA63T = 0x3C
}
Public Member Functions
virtual ~AP_InertialSensor_Invensensev3 ()
bool update () override
void accumulate () override
void start () override
bool get_output_banner (char *banner, uint8_t banner_len) override
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t get_id () const
float get_clip_limit () const
Static Public Member Functions
static AP_InertialSensor_Backend * probe (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation)
Public Attributes
const uint16_t multiplier_accel = INT16_MAX/(32*GRAVITY_MSS)
Private Member Functions
AP_InertialSensor_Invensensev3 (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation)
bool hardware_init ()
bool check_whoami ()
void set_filter_and_scaling (void)
void set_filter_and_scaling_icm42670 (void)
void set_filter_and_scaling_icm456xy (void)
void fifo_reset ()
uint16_t calculate_fast_sampling_backend_rate (uint16_t base_odr, uint16_t max_odr) const
void read_fifo ()
bool block_read (uint8_t reg, uint8_t *buf, uint32_t size)
uint8_t register_read (uint8_t reg)
void register_write (uint8_t reg, uint8_t val, bool checked=false)
uint8_t register_read_bank (uint8_t bank, uint8_t reg)
void register_write_bank (uint8_t bank, uint8_t reg, uint8_t val)
uint8_t register_read_bank_icm456xy (uint16_t bank_addr, uint16_t reg)
void register_write_bank_icm456xy (uint16_t bank_addr, uint16_t reg, uint8_t val)
bool accumulate_samples (const struct FIFOData *data, uint8_t n_samples)
bool accumulate_highres_samples (const struct FIFODataHighRes *data, uint8_t n_samples)
Private Attributes
uint8_t gyro_instance
uint8_t accel_instance
uint8_t fifo_config1
float temp_sensitivity
const float temp_zero = 25
enum Rotation rotation
float accel_scale = ACCEL_SCALE_16G
float gyro_scale = GYRO_SCALE_2000DPS
bool fast_sampling
uint16_t backend_rate_hz
uint32_t backend_period_us
AP_HAL::OwnPtr< AP_HAL::Device > dev
AP_HAL::Device::PeriodicHandle periodic_handle
enum Invensensev3_Type inv3_type
void * fifo_buffer
float temp_filtered
LowPassFilter2pFloat temp_filter
Static Private Attributes
static constexpr float SCALE_RANGE_16BIT = 32768
static constexpr float SCALE_RANGE_20BIT = 524288
static constexpr float SCALE_RANGE_19BIT = 262144
static constexpr float GYRO_SCALE_2000DPS = radians(1) / (SCALE_RANGE_16BIT / 2000.0)
static constexpr float GYRO_SCALE_4000DPS = radians(1) / (SCALE_RANGE_16BIT / 4000.0)
static constexpr float GYRO_SCALE_HIGHRES_2000DPS = radians(1) / (SCALE_RANGE_20BIT / 2000.0)
static constexpr float GYRO_SCALE_HIGHRES_4000DPS = radians(1) / (SCALE_RANGE_20BIT / 4000.0)
static constexpr float ACCEL_SCALE_16G = (GRAVITY_MSS / (SCALE_RANGE_16BIT / 16))
static constexpr float ACCEL_SCALE_32G = (GRAVITY_MSS / (SCALE_RANGE_16BIT / 32))
static constexpr float ACCEL_SCALE_HIGHRES_16G = (GRAVITY_MSS / (SCALE_RANGE_20BIT / 16))
static constexpr float ACCEL_SCALE_HIGHRES_32G = (GRAVITY_MSS / (SCALE_RANGE_20BIT / 32))
Additional Inherited Members
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel) __RAMFUNC__
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro) __RAMFUNC__
void _publish_gyro (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void apply_gyro_filters (const uint8_t instance, const Vector3f &gyro)
void save_gyro_window (const uint8_t instance, const Vector3f &gyro, uint8_t phase)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0) __RAMFUNC__
void _notify_new_delta_angle (uint8_t instance, const Vector3f &dangle)
void _publish_accel (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0, bool fsync_set=false) __RAMFUNC__
void _notify_new_delta_velocity (uint8_t instance, const Vector3f &dvelocity)
void _set_accel_oversampling (uint8_t instance, uint8_t n)
void _set_gyro_oversampling (uint8_t instance, uint8_t n)
void _set_accel_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_gyro_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_raw_sample_accel_multiplier (uint8_t instance, uint16_t mul)
void _set_raw_sample_gyro_multiplier (uint8_t instance, uint16_t mul)
void _update_sensor_rate (uint16_t &count, uint32_t &start_us, float &rate_hz) const __RAMFUNC__
bool sensors_converging () const
void _set_accel_max_abs_offset (uint8_t instance, float offset)
float _accel_raw_sample_rate (uint8_t instance) const
void _set_accel_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
float _gyro_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
void _publish_temperature (uint8_t instance, float temperature)
void _inc_accel_error_count (uint8_t instance) __RAMFUNC__
void _inc_gyro_error_count (uint8_t instance) __RAMFUNC__
uint16_t _accel_filter_cutoff (void) const
uint16_t _gyro_filter_cutoff (void) const
uint16_t get_loop_rate_hz (void) const
void update_gyro (uint8_t instance) __RAMFUNC__
void update_accel (uint8_t instance) __RAMFUNC__
void set_gyro_orientation (uint8_t instance, enum Rotation rotation)
void set_accel_orientation (uint8_t instance, enum Rotation rotation)
void increment_clip_count (uint8_t instance)
bool enable_fast_sampling (uint8_t instance) const
bool enable_highres_sampling (uint8_t instance) const
uint8_t get_fast_sampling_rate () const
void _notify_new_accel_sensor_rate_sample (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_gyro_sensor_rate_sample (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void notify_accel_fifo_reset (uint8_t instance) __RAMFUNC__
void notify_gyro_fifo_reset (uint8_t instance) __RAMFUNC__
void log_register_change (uint32_t bus_id, const AP_HAL::Device::checkreg &reg) __RAMFUNC__
void Write_GYR (const uint8_t instance, const uint64_t sample_us, const Vector3f &gyro, bool use_sample_timestamp=false) const __RAMFUNC__
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
HAL_Semaphore _sem
float _clip_limit = 15.5f * GRAVITY_MSS
int16_t _id = -1
uint16_t _last_accel_filter_hz
uint16_t _last_gyro_filter_hz
Detailed Description
Definition at line 17 of file AP_InertialSensor_Invensensev3.h.
Member Enumeration Documentation
Invensensev3_Type
enum class AP_InertialSensor_Invensensev3::Invensensev3_Type : uint8_t strong
Enumerator
ICM40609
ICM42688
ICM42605
ICM40605
IIM42652
ICM42670
ICM45686
Definition at line 34 of file AP_InertialSensor_Invensensev3.h.
Constructor & Destructor Documentation
~AP_InertialSensor_Invensensev3()
AP_InertialSensor_Invensensev3::~AP_InertialSensor_Invensensev3 () virtual
Definition at line 183 of file AP_InertialSensor_Invensensev3.cpp.
AP_InertialSensor_Invensensev3()
AP_InertialSensor_Invensensev3::AP_InertialSensor_Invensensev3 (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation) private
Definition at line 174 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by probe().
Member Function Documentation
accumulate()
void AP_InertialSensor_Invensensev3::accumulate () override virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 403 of file AP_InertialSensor_Invensensev3.cpp.
accumulate_highres_samples()
bool AP_InertialSensor_Invensensev3::accumulate_highres_samples (const struct FIFODataHighRes * data, uint8_t n_samples) private
Referenced by read_fifo().
accumulate_samples()
bool AP_InertialSensor_Invensensev3::accumulate_samples (const struct FIFOData * data, uint8_t n_samples) private
Definition at line 408 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by read_fifo().
block_read()
bool AP_InertialSensor_Invensensev3::block_read (uint8_t reg, uint8_t * buf, uint32_t size) private
Definition at line 586 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by read_fifo().
calculate_fast_sampling_backend_rate()
uint16_t AP_InertialSensor_Invensensev3::calculate_fast_sampling_backend_rate (uint16_t base_odr, uint16_t max_odr) const private
Definition at line 646 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by set_filter_and_scaling(), and set_filter_and_scaling_icm456xy().
check_whoami()
bool AP_InertialSensor_Invensensev3::check_whoami (void) private
Definition at line 932 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by hardware_init().
fifo_reset()
void AP_InertialSensor_Invensensev3::fifo_reset () private
Definition at line 219 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by read_fifo(), and start().
get_output_banner()
bool AP_InertialSensor_Invensensev3::get_output_banner (char * banner, uint8_t banner_len) override virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 375 of file AP_InertialSensor_Invensensev3.cpp.
hardware_init()
bool AP_InertialSensor_Invensensev3::hardware_init (void) private
Definition at line 1009 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by probe().
probe()
AP_InertialSensor_Backend * AP_InertialSensor_Invensensev3::probe (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation) static
Definition at line 197 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by AP_InertialSensor::detect_backends().
read_fifo()
void AP_InertialSensor_Invensensev3::read_fifo () private
Definition at line 509 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by start().
register_read()
uint8_t AP_InertialSensor_Invensensev3::register_read (uint8_t reg) private
Definition at line 591 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by check_whoami(), hardware_init(), register_read_bank(), register_read_bank_icm456xy(), register_write_bank_icm456xy(), set_filter_and_scaling(), and set_filter_and_scaling_icm42670().
register_read_bank()
uint8_t AP_InertialSensor_Invensensev3::register_read_bank (uint8_t bank, uint8_t reg) private
Definition at line 606 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by set_filter_and_scaling().
register_read_bank_icm456xy()
uint8_t AP_InertialSensor_Invensensev3::register_read_bank_icm456xy (uint16_t bank_addr, uint16_t reg) private
Definition at line 967 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by hardware_init(), and set_filter_and_scaling_icm456xy().
register_write()
void AP_InertialSensor_Invensensev3::register_write (uint8_t reg, uint8_t val, bool checked = false) private
Definition at line 598 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by fifo_reset(), hardware_init(), register_read_bank(), register_write_bank(), set_filter_and_scaling(), set_filter_and_scaling_icm42670(), and set_filter_and_scaling_icm456xy().
register_write_bank()
void AP_InertialSensor_Invensensev3::register_write_bank (uint8_t bank, uint8_t reg, uint8_t val) private
Definition at line 628 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by hardware_init(), and set_filter_and_scaling().
register_write_bank_icm456xy()
void AP_InertialSensor_Invensensev3::register_write_bank_icm456xy (uint16_t bank_addr, uint16_t reg, uint8_t val) private
Definition at line 990 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by hardware_init(), and set_filter_and_scaling_icm456xy().
set_filter_and_scaling()
void AP_InertialSensor_Invensensev3::set_filter_and_scaling (void) private
Definition at line 691 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by start().
set_filter_and_scaling_icm42670()
void AP_InertialSensor_Invensensev3::set_filter_and_scaling_icm42670 (void) private
Definition at line 835 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by start().
set_filter_and_scaling_icm456xy()
void AP_InertialSensor_Invensensev3::set_filter_and_scaling_icm456xy (void) private
Definition at line 860 of file AP_InertialSensor_Invensensev3.cpp.
Referenced by start().
start()
void AP_InertialSensor_Invensensev3::start (void) override virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 242 of file AP_InertialSensor_Invensensev3.cpp.
update()
bool AP_InertialSensor_Invensensev3::update (void) override virtual
Implements AP_InertialSensor_Backend.
Definition at line 391 of file AP_InertialSensor_Invensensev3.cpp.
Member Data Documentation
accel_instance
uint8_t AP_InertialSensor_Invensensev3::accel_instance private
Definition at line 79 of file AP_InertialSensor_Invensensev3.h.
Referenced by accumulate_samples(), fifo_reset(), read_fifo(), set_filter_and_scaling(), set_filter_and_scaling_icm456xy(), start(), and update().
accel_scale
float AP_InertialSensor_Invensensev3::accel_scale = ACCEL_SCALE_16G private
Definition at line 122 of file AP_InertialSensor_Invensensev3.h.
Referenced by accumulate_samples(), and start().
ACCEL_SCALE_16G
constexpr float AP_InertialSensor_Invensensev3::ACCEL_SCALE_16G = (GRAVITY_MSS / (SCALE_RANGE_16BIT / 16)) static constexpr private
Definition at line 111 of file AP_InertialSensor_Invensensev3.h.
ACCEL_SCALE_32G
constexpr float AP_InertialSensor_Invensensev3::ACCEL_SCALE_32G = (GRAVITY_MSS / (SCALE_RANGE_16BIT / 32)) static constexpr private
Definition at line 115 of file AP_InertialSensor_Invensensev3.h.
Referenced by start().
ACCEL_SCALE_HIGHRES_16G
constexpr float AP_InertialSensor_Invensensev3::ACCEL_SCALE_HIGHRES_16G = (GRAVITY_MSS / (SCALE_RANGE_20BIT / 16)) static constexpr private
Definition at line 119 of file AP_InertialSensor_Invensensev3.h.
Referenced by start().
ACCEL_SCALE_HIGHRES_32G
constexpr float AP_InertialSensor_Invensensev3::ACCEL_SCALE_HIGHRES_32G = (GRAVITY_MSS / (SCALE_RANGE_20BIT / 32)) static constexpr private
Definition at line 120 of file AP_InertialSensor_Invensensev3.h.
Referenced by start().
backend_period_us
uint32_t AP_InertialSensor_Invensensev3::backend_period_us private
Definition at line 134 of file AP_InertialSensor_Invensensev3.h.
Referenced by accumulate_samples(), read_fifo(), and start().
backend_rate_hz
uint16_t AP_InertialSensor_Invensensev3::backend_rate_hz private
Definition at line 132 of file AP_InertialSensor_Invensensev3.h.
Referenced by get_output_banner(), set_filter_and_scaling(), set_filter_and_scaling_icm42670(), set_filter_and_scaling_icm456xy(), and start().
dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_InertialSensor_Invensensev3::dev private
Definition at line 136 of file AP_InertialSensor_Invensensev3.h.
Referenced by block_read(), hardware_init(), read_fifo(), register_read(), register_read_bank_icm456xy(), register_write(), register_write_bank_icm456xy(), set_filter_and_scaling(), set_filter_and_scaling_icm456xy(), and start().
fast_sampling
bool AP_InertialSensor_Invensensev3::fast_sampling private
Definition at line 126 of file AP_InertialSensor_Invensensev3.h.
Referenced by get_output_banner(), set_filter_and_scaling(), and set_filter_and_scaling_icm456xy().
fifo_buffer
void* AP_InertialSensor_Invensensev3::fifo_buffer private
Definition at line 143 of file AP_InertialSensor_Invensensev3.h.
Referenced by read_fifo(), start(), and ~AP_InertialSensor_Invensensev3().
fifo_config1
uint8_t AP_InertialSensor_Invensensev3::fifo_config1 private
Definition at line 82 of file AP_InertialSensor_Invensensev3.h.
Referenced by fifo_reset(), and start().
gyro_instance
uint8_t AP_InertialSensor_Invensensev3::gyro_instance private
Definition at line 78 of file AP_InertialSensor_Invensensev3.h.
Referenced by accumulate_samples(), fifo_reset(), get_output_banner(), read_fifo(), start(), and update().
gyro_scale
float AP_InertialSensor_Invensensev3::gyro_scale = GYRO_SCALE_2000DPS private
Definition at line 123 of file AP_InertialSensor_Invensensev3.h.
Referenced by accumulate_samples(), and start().
GYRO_SCALE_2000DPS
constexpr float AP_InertialSensor_Invensensev3::GYRO_SCALE_2000DPS = radians(1) / (SCALE_RANGE_16BIT / 2000.0) static constexpr private
Definition at line 98 of file AP_InertialSensor_Invensensev3.h.
GYRO_SCALE_4000DPS
constexpr float AP_InertialSensor_Invensensev3::GYRO_SCALE_4000DPS = radians(1) / (SCALE_RANGE_16BIT / 4000.0) static constexpr private
Definition at line 102 of file AP_InertialSensor_Invensensev3.h.
Referenced by start().
GYRO_SCALE_HIGHRES_2000DPS
constexpr float AP_InertialSensor_Invensensev3::GYRO_SCALE_HIGHRES_2000DPS = radians(1) / (SCALE_RANGE_20BIT / 2000.0) static constexpr private
Definition at line 106 of file AP_InertialSensor_Invensensev3.h.
Referenced by start().
GYRO_SCALE_HIGHRES_4000DPS
constexpr float AP_InertialSensor_Invensensev3::GYRO_SCALE_HIGHRES_4000DPS = radians(1) / (SCALE_RANGE_20BIT / 4000.0) static constexpr private
Definition at line 107 of file AP_InertialSensor_Invensensev3.h.
Referenced by start().
inv3_type
enum Invensensev3_Type AP_InertialSensor_Invensensev3::inv3_type private
Definition at line 140 of file AP_InertialSensor_Invensensev3.h.
Referenced by check_whoami(), fifo_reset(), hardware_init(), read_fifo(), register_read_bank(), register_write_bank(), set_filter_and_scaling(), and start().
multiplier_accel
const uint16_t AP_InertialSensor_Invensensev3::multiplier_accel = INT16_MAX/(32*GRAVITY_MSS)
Definition at line 45 of file AP_InertialSensor_Invensensev3.h.
Referenced by start().
periodic_handle
AP_HAL::Device::PeriodicHandle AP_InertialSensor_Invensensev3::periodic_handle private
Definition at line 137 of file AP_InertialSensor_Invensensev3.h.
Referenced by read_fifo(), and start().
rotation
enum Rotation AP_InertialSensor_Invensensev3::rotation private
Definition at line 88 of file AP_InertialSensor_Invensensev3.h.
Referenced by start().
SCALE_RANGE_16BIT
constexpr float AP_InertialSensor_Invensensev3::SCALE_RANGE_16BIT = 32768 static constexpr private
Definition at line 90 of file AP_InertialSensor_Invensensev3.h.
SCALE_RANGE_19BIT
constexpr float AP_InertialSensor_Invensensev3::SCALE_RANGE_19BIT = 262144 static constexpr private
Definition at line 93 of file AP_InertialSensor_Invensensev3.h.
SCALE_RANGE_20BIT
constexpr float AP_InertialSensor_Invensensev3::SCALE_RANGE_20BIT = 524288 static constexpr private
Definition at line 92 of file AP_InertialSensor_Invensensev3.h.
temp_filter
LowPassFilter2pFloat AP_InertialSensor_Invensensev3::temp_filter private
Definition at line 146 of file AP_InertialSensor_Invensensev3.h.
Referenced by accumulate_samples().
temp_filtered
float AP_InertialSensor_Invensensev3::temp_filtered private
Definition at line 145 of file AP_InertialSensor_Invensensev3.h.
Referenced by accumulate_samples(), and update().
temp_sensitivity
float AP_InertialSensor_Invensensev3::temp_sensitivity private
Definition at line 85 of file AP_InertialSensor_Invensensev3.h.
Referenced by accumulate_samples(), and start().
temp_zero
const float AP_InertialSensor_Invensensev3::temp_zero = 25 private
Definition at line 86 of file AP_InertialSensor_Invensensev3.h.
Referenced by accumulate_samples().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.h
libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp