APM:Libraries: AP_JSON::value Class Reference
AP_JSON::value Class Reference
#include <AP_JSON.h>
Classes
union _storage
Public Types
typedef std::vector< value > array
typedef std::map< std::string, value > object
Public Member Functions
value ()
value (int type, bool)
value (bool b)
value (double n)
value (const std::string &s)
value (const array &a)
value (const object &o)
value (std::string &&s)
value (array &&a)
value (object &&o)
value (const char *s)
value (const char *s, size_t len)
~value ()
value (const value &x)
value & operator= (const value &x)
value (value &&x)
value & operator= (value &&x)
void swap (value &x)
template<typename T >
bool is () const
template<typename T >
const T & get () const
template<typename T >
T & get ()
template<typename T >
void set (const T &)
template<typename T >
void set (T &&)
bool evaluate_as_boolean () const
const value & get (const size_t idx) const
const value & get (const std::string &key) const
value & get (const size_t idx)
value & get (const std::string &key)
bool contains (const size_t idx) const
bool contains (const std::string &key) const
std::string to_str () const
template<>
bool is () const
Protected Attributes
int type_
_storage u_
Private Member Functions
template<typename T >
value (const T *)
void clear ()
Detailed Description
Definition at line 23 of file AP_JSON.h.
Member Typedef Documentation
array
typedef std::vector<value> AP_JSON::value::array
Definition at line 26 of file AP_JSON.h.
object
typedef std::map<std::string, value> AP_JSON::value::object
Definition at line 27 of file AP_JSON.h.
Constructor & Destructor Documentation
value() [1/15]
AP_JSON::value::value ()
Definition at line 123 of file AP_JSON.cpp.
Referenced by SITL::XPlane::send_dref().
value() [2/15]
AP_JSON::value::value (int type, bool)
Definition at line 127 of file AP_JSON.cpp.
value() [3/15]
AP_JSON::value::value (bool b) explicit
Definition at line 145 of file AP_JSON.cpp.
value() [4/15]
AP_JSON::value::value (double n) explicit
Definition at line 150 of file AP_JSON.cpp.
value() [5/15]
AP_JSON::value::value (const std::string & s) explicit
Definition at line 155 of file AP_JSON.cpp.
value() [6/15]
AP_JSON::value::value (const array & a) explicit
Definition at line 160 of file AP_JSON.cpp.
value() [7/15]
AP_JSON::value::value (const object & o) explicit
Definition at line 165 of file AP_JSON.cpp.
value() [8/15]
AP_JSON::value::value (std::string && s) explicit
Definition at line 170 of file AP_JSON.cpp.
value() [9/15]
AP_JSON::value::value (array && a) explicit
Definition at line 175 of file AP_JSON.cpp.
value() [10/15]
AP_JSON::value::value (object && o) explicit
Definition at line 180 of file AP_JSON.cpp.
value() [11/15]
AP_JSON::value::value (const char * s) explicit
Definition at line 185 of file AP_JSON.cpp.
value() [12/15]
AP_JSON::value::value (const char * s, size_t len)
Definition at line 190 of file AP_JSON.cpp.
~value()
AP_JSON::value::~value ()
Definition at line 211 of file AP_JSON.cpp.
value() [13/15]
AP_JSON::value::value (const value & x)
Definition at line 216 of file AP_JSON.cpp.
value() [14/15]
AP_JSON::value::value (value && x)
Definition at line 242 of file AP_JSON.cpp.
value() [15/15]
template<typename T > AP_JSON::value::value (const T *) private
Member Function Documentation
clear()
void AP_JSON::value::clear () private
Definition at line 195 of file AP_JSON.cpp.
contains() [1/2]
bool AP_JSON::value::contains (const size_t idx) const
Definition at line 353 of file AP_JSON.cpp.
Referenced by SITL::Frame::parse_vector3().
contains() [2/2]
bool AP_JSON::value::contains (const std::string & key) const
Definition at line 358 of file AP_JSON.cpp.
evaluate_as_boolean()
bool AP_JSON::value::evaluate_as_boolean () const
get() [1/6]
template<typename T > T & AP_JSON::value::get ()
get() [2/6]
template<typename T > const T & AP_JSON::value::get () const
Referenced by SITL::XPlane::add_dref(), AP_Param::get(), RC_Channels::get_override_timeout_ms(), Compass::init(), SITL::XPlane::load_dref_map(), SITL::Frame::load_frame_params(), default_parse_context::parse_array_item(), SITL::Frame::parse_float(), default_parse_context::parse_object_item(), default_parse_context::parse_string(), and SITL::Frame::parse_vector3().
get() [3/6]
value & AP_JSON::value::get (const size_t idx)
get() [4/6]
const value & AP_JSON::value::get (const size_t idx) const
get() [5/6]
value & AP_JSON::value::get (const std::string & key)
Definition at line 346 of file AP_JSON.cpp.
get() [6/6]
const value & AP_JSON::value::get (const std::string & key) const
Definition at line 339 of file AP_JSON.cpp.
is() [1/2]
template<> bool AP_JSON::value::is () const
Definition at line 268 of file AP_JSON.cpp.
is() [2/2]
template<typename T > bool AP_JSON::value::is () const
Referenced by SITL::Frame::parse_float(), and SITL::Frame::parse_vector3().
operator=() [1/2]
value & AP_JSON::value::operator= (const value & x)
Definition at line 233 of file AP_JSON.cpp.
operator=() [2/2]
value & AP_JSON::value::operator= (value && x)
Definition at line 246 of file AP_JSON.cpp.
set() [1/2]
template<typename T > void AP_JSON::value::set (const T &)
Referenced by Compass::init().
set() [2/2]
template<typename T > void AP_JSON::value::set (T &&)
swap()
void AP_JSON::value::swap (value & x)
Definition at line 252 of file AP_JSON.cpp.
Referenced by value().
to_str()
std::string AP_JSON::value::to_str () const
Definition at line 364 of file AP_JSON.cpp.
Referenced by SITL::Frame::parse_float(), and SITL::Frame::parse_vector3().
Member Data Documentation
type_
int AP_JSON::value::type_ protected
Definition at line 38 of file AP_JSON.h.
Referenced by value().
u_
_storage AP_JSON::value::u_ protected
Definition at line 39 of file AP_JSON.h.
Referenced by value(), value(), value(), value(), value(), value(), value(), value(), value(), value(), and value().
The documentation for this class was generated from the following files:
libraries/AP_JSON/AP_JSON.h
libraries/AP_JSON/AP_JSON.cpp