APM:Libraries: JitterCorrection Class Reference
JitterCorrection Class Reference
#include <JitterCorrection.h>
Public Member Functions
JitterCorrection (uint16_t max_lag_ms=500, uint16_t convergence_loops=100)
uint64_t correct_offboard_timestamp_usec (uint64_t offboard_usec, uint64_t local_usec)
uint32_t correct_offboard_timestamp_msec (uint32_t offboard_ms, uint32_t local_ms)
int64_t get_link_offset_usec (void) const
Private Attributes
const uint16_t max_lag_ms
const uint16_t convergence_loops
int64_t link_offset_usec
int64_t min_sample_us
bool initialised
uint16_t min_sample_counter
Detailed Description
Definition at line 7 of file JitterCorrection.h.
Constructor & Destructor Documentation
JitterCorrection()
JitterCorrection::JitterCorrection (uint16_t max_lag_ms = 500, uint16_t convergence_loops = 100)
Definition at line 39 of file JitterCorrection.cpp.
Member Function Documentation
correct_offboard_timestamp_msec()
uint32_t JitterCorrection::correct_offboard_timestamp_msec (uint32_t offboard_ms, uint32_t local_ms)
Definition at line 97 of file JitterCorrection.cpp.
Referenced by AP_Follow::handle_msg().
correct_offboard_timestamp_usec()
uint64_t JitterCorrection::correct_offboard_timestamp_usec (uint64_t offboard_usec, uint64_t local_usec)
Definition at line 50 of file JitterCorrection.cpp.
Referenced by AP_GPS_Backend::check_new_itow(), correct_offboard_timestamp_msec(), and GCS_MAVLINK::correct_offboard_timestamp_usec_to_ms().
get_link_offset_usec()
int64_t JitterCorrection::get_link_offset_usec (void) const inline
Definition at line 20 of file JitterCorrection.h.
Member Data Documentation
convergence_loops
const uint16_t JitterCorrection::convergence_loops private
Definition at line 24 of file JitterCorrection.h.
Referenced by correct_offboard_timestamp_usec().
initialised
bool JitterCorrection::initialised private
Definition at line 27 of file JitterCorrection.h.
Referenced by correct_offboard_timestamp_usec().
link_offset_usec
int64_t JitterCorrection::link_offset_usec private
Definition at line 25 of file JitterCorrection.h.
Referenced by correct_offboard_timestamp_usec(), and get_link_offset_usec().
max_lag_ms
const uint16_t JitterCorrection::max_lag_ms private
Definition at line 23 of file JitterCorrection.h.
Referenced by correct_offboard_timestamp_usec().
min_sample_counter
uint16_t JitterCorrection::min_sample_counter private
Definition at line 28 of file JitterCorrection.h.
Referenced by correct_offboard_timestamp_usec().
min_sample_us
int64_t JitterCorrection::min_sample_us private
Definition at line 26 of file JitterCorrection.h.
Referenced by correct_offboard_timestamp_usec().
The documentation for this class was generated from the following files:
libraries/AP_RTC/JitterCorrection.h
libraries/AP_RTC/JitterCorrection.cpp