APM:Libraries: SRV_Channel Class Reference
SRV_Channel Class Reference
#include <SRV_Channel.h>
Public Types
enum Aux_servo_function_t {
k_GPIO = -1 , k_none = 0 , k_manual = 1 , k_flap = 2 ,
k_flap_auto = 3 , k_aileron = 4 , k_unused1 = 5 , k_mount_pan = 6 ,
k_mount_tilt = 7 , k_mount_roll = 8 , k_mount_open = 9 , k_cam_trigger = 10 ,
k_egg_drop = 11 , k_mount2_pan = 12 , k_mount2_tilt = 13 , k_mount2_roll = 14 ,
k_mount2_open = 15 , k_dspoilerLeft1 = 16 , k_dspoilerRight1 = 17 , k_aileron_with_input = 18 ,
k_elevator = 19 , k_elevator_with_input = 20 , k_rudder = 21 , k_sprayer_pump = 22 ,
k_sprayer_spinner = 23 , k_flaperon_left = 24 , k_flaperon_right = 25 , k_steering = 26 ,
k_parachute_release = 27 , k_gripper = 28 , k_landing_gear_control = 29 , k_engine_run_enable = 30 ,
k_heli_rsc = 31 , k_heli_tail_rsc = 32 , k_motor1 = 33 , k_motor2 = 34 ,
k_motor3 = 35 , k_motor4 = 36 , k_motor5 = 37 , k_motor6 = 38 ,
k_motor7 = 39 , k_motor8 = 40 , k_motor_tilt = 41 , k_generator_control = 42 ,
k_tiltMotorRear = 45 , k_tiltMotorRearLeft = 46 , k_tiltMotorRearRight = 47 , k_rcin1 = 51 ,
k_rcin2 = 52 , k_rcin3 = 53 , k_rcin4 = 54 , k_rcin5 = 55 ,
k_rcin6 = 56 , k_rcin7 = 57 , k_rcin8 = 58 , k_rcin9 = 59 ,
k_rcin10 = 60 , k_rcin11 = 61 , k_rcin12 = 62 , k_rcin13 = 63 ,
k_rcin14 = 64 , k_rcin15 = 65 , k_rcin16 = 66 , k_ignition = 67 ,
k_choke = 68 , k_starter = 69 , k_throttle = 70 , k_tracker_yaw = 71 ,
k_tracker_pitch = 72 , k_throttleLeft = 73 , k_throttleRight = 74 , k_tiltMotorLeft = 75 ,
k_tiltMotorRight = 76 , k_elevon_left = 77 , k_elevon_right = 78 , k_vtail_left = 79 ,
k_vtail_right = 80 , k_boost_throttle = 81 , k_motor9 = 82 , k_motor10 = 83 ,
k_motor11 = 84 , k_motor12 = 85 , k_dspoilerLeft2 = 86 , k_dspoilerRight2 = 87 ,
k_winch = 88 , k_mainsail_sheet = 89 , k_cam_iso = 90 , k_cam_aperture = 91 ,
k_cam_focus = 92 , k_cam_shutter_speed = 93 , k_scripting1 = 94 , k_scripting2 = 95 ,
k_scripting3 = 96 , k_scripting4 = 97 , k_scripting5 = 98 , k_scripting6 = 99 ,
k_scripting7 = 100 , k_scripting8 = 101 , k_scripting9 = 102 , k_scripting10 = 103 ,
k_scripting11 = 104 , k_scripting12 = 105 , k_scripting13 = 106 , k_scripting14 = 107 ,
k_scripting15 = 108 , k_scripting16 = 109 , k_airbrake = 110 , k_LED_neopixel1 = 120 ,
k_LED_neopixel2 = 121 , k_LED_neopixel3 = 122 , k_LED_neopixel4 = 123 , k_roll_out = 124 ,
k_pitch_out = 125 , k_thrust_out = 126 , k_yaw_out = 127 , k_wingsail_elevator = 128 ,
k_ProfiLED_1 = 129 , k_ProfiLED_2 = 130 , k_ProfiLED_3 = 131 , k_ProfiLED_Clock = 132 ,
k_winch_clutch = 133 , k_min = 134 , k_trim = 135 , k_max = 136 ,
k_mast_rotation = 137 , k_alarm = 138 , k_alarm_inverted = 139 , k_rcin1_mapped = 140 ,
k_rcin2_mapped = 141 , k_rcin3_mapped = 142 , k_rcin4_mapped = 143 , k_rcin5_mapped = 144 ,
k_rcin6_mapped = 145 , k_rcin7_mapped = 146 , k_rcin8_mapped = 147 , k_rcin9_mapped = 148 ,
k_rcin10_mapped = 149 , k_rcin11_mapped = 150 , k_rcin12_mapped = 151 , k_rcin13_mapped = 152 ,
k_rcin14_mapped = 153 , k_rcin15_mapped = 154 , k_rcin16_mapped = 155 , k_nr_aux_servo_functions
}
enum class Limit { TRIM , MIN , MAX , ZERO_PWM }
Public Member Functions
SRV_Channel (void)
bool valid_function (void) const
void set_output_pwm (uint16_t pwm, bool force=false)
uint16_t get_output_pwm (void) const
void set_output_norm (float value)
void set_angle (int16_t angle)
void set_range (uint16_t high)
bool get_reversed (void) const
void set_output_min (uint16_t pwm)
void set_output_max (uint16_t pwm)
uint16_t get_output_min (void) const
uint16_t get_output_max (void) const
uint16_t get_trim (void) const
SRV_Channel::Aux_servo_function_t get_function (void) const
int8_t get_motor_num (void) const
void function_set_and_save (SRV_Channel::Aux_servo_function_t f)
void reversed_set_and_save_ifchanged (bool r)
bool function_configured (void) const
uint16_t pwm_from_scaled_value (float scaled_value) const
void ignore_small_rcin_changes ()
Static Public Member Functions
static bool valid_function (Aux_servo_function_t fn)
static bool is_motor (SRV_Channel::Aux_servo_function_t function)
static bool should_e_stop (SRV_Channel::Aux_servo_function_t function)
static bool is_control_surface (SRV_Channel::Aux_servo_function_t function)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
typedef uint32_t servo_mask_t
Private Member Functions
uint16_t pwm_from_range (float scaled_value) const
uint16_t pwm_from_angle (float scaled_value) const
void calc_pwm (float output_scaled)
void output_ch (void)
map a function to a servo channel and output it
void aux_servo_function_setup (void)
uint16_t get_limit_pwm (Limit limit) const
float get_output_norm (void)
void set_override (bool b)
Private Attributes
AP_Int16 servo_min
AP_Int16 servo_max
AP_Int16 servo_trim
AP_Int8 reversed
AP_Enum16< Aux_servo_function_t > function
uint16_t output_pwm
bool type_angle:1
bool type_setup:1
uint8_t ch_num
uint16_t high_out
int16_t previous_radio_in
bool ign_small_rcin_changes
bool override_active
Static Private Attributes
static servo_mask_t have_pwm_mask
Friends
class SRV_Channels
Detailed Description
Definition at line 37 of file SRV_Channel.h.
Member Typedef Documentation
servo_mask_t
typedef uint32_t SRV_Channel::servo_mask_t private
Definition at line 335 of file SRV_Channel.h.
Member Enumeration Documentation
Aux_servo_function_t
enum SRV_Channel::Aux_servo_function_t
Enumerator
k_GPIO
used as GPIO pin (input or output)
k_none
general use PWM output used by do-set-servo commands and lua scripts
k_manual
manual, just pass-thru the RC in signal
k_flap
flap
k_flap_auto
flap automated
k_aileron
aileron
k_unused1
unused function
k_mount_pan
mount yaw (pan)
k_mount_tilt
mount pitch (tilt)
k_mount_roll
mount roll
k_mount_open
mount open (deploy) / close (retract)
k_cam_trigger
camera trigger
k_egg_drop
egg drop, deprecated
k_mount2_pan
mount2 yaw (pan)
k_mount2_tilt
mount2 pitch (tilt)
k_mount2_roll
mount2 roll
k_mount2_open
mount2 open (deploy) / close (retract)
k_dspoilerLeft1
differential spoiler 1 (left wing)
k_dspoilerRight1
differential spoiler 1 (right wing)
k_aileron_with_input
aileron, with rc input, deprecated
k_elevator
elevator
k_elevator_with_input
elevator, with rc input, deprecated
k_rudder
secondary rudder channel
k_sprayer_pump
crop sprayer pump channel
k_sprayer_spinner
crop sprayer spinner channel
k_flaperon_left
flaperon, left wing
k_flaperon_right
flaperon, right wing
k_steering
ground steering, used to separate from rudder
k_parachute_release
parachute release
k_gripper
gripper
k_landing_gear_control
landing gear controller
k_engine_run_enable
engine kill switch, used for gas airplanes and helicopters
k_heli_rsc
helicopter RSC output
k_heli_tail_rsc
helicopter tail RSC output
k_motor1
these allow remapping of copter motors
k_motor2
k_motor3
k_motor4
k_motor5
k_motor6
k_motor7
k_motor8
k_motor_tilt
tiltrotor motor tilt control
k_generator_control
state control for generator
k_tiltMotorRear
vectored thrust, rear tilt
k_tiltMotorRearLeft
vectored thrust, rear left tilt
k_tiltMotorRearRight
vectored thrust, rear right tilt
k_rcin1
these are for pass-thru from arbitrary rc inputs
k_rcin2
k_rcin3
k_rcin4
k_rcin5
k_rcin6
k_rcin7
k_rcin8
k_rcin9
k_rcin10
k_rcin11
k_rcin12
k_rcin13
k_rcin14
k_rcin15
k_rcin16
k_ignition
k_choke
k_starter
not used
k_throttle
k_tracker_yaw
antennatracker yaw
k_tracker_pitch
antennatracker pitch
k_throttleLeft
k_throttleRight
k_tiltMotorLeft
vectored thrust, left tilt
k_tiltMotorRight
vectored thrust, right tilt
k_elevon_left
k_elevon_right
k_vtail_left
k_vtail_right
k_boost_throttle
vertical booster throttle
k_motor9
k_motor10
k_motor11
k_motor12
k_dspoilerLeft2
differential spoiler 2 (left wing)
k_dspoilerRight2
differential spoiler 2 (right wing)
k_winch
k_mainsail_sheet
Main Sail control via sheet.
k_cam_iso
k_cam_aperture
k_cam_focus
k_cam_shutter_speed
k_scripting1
Scripting related outputs.
k_scripting2
k_scripting3
k_scripting4
k_scripting5
k_scripting6
k_scripting7
k_scripting8
k_scripting9
k_scripting10
k_scripting11
k_scripting12
k_scripting13
k_scripting14
k_scripting15
k_scripting16
k_airbrake
k_LED_neopixel1
k_LED_neopixel2
k_LED_neopixel3
k_LED_neopixel4
k_roll_out
k_pitch_out
k_thrust_out
k_yaw_out
k_wingsail_elevator
k_ProfiLED_1
k_ProfiLED_2
k_ProfiLED_3
k_ProfiLED_Clock
k_winch_clutch
k_min
k_trim
k_max
k_mast_rotation
k_alarm
k_alarm_inverted
k_rcin1_mapped
k_rcin2_mapped
k_rcin3_mapped
k_rcin4_mapped
k_rcin5_mapped
k_rcin6_mapped
k_rcin7_mapped
k_rcin8_mapped
k_rcin9_mapped
k_rcin10_mapped
k_rcin11_mapped
k_rcin12_mapped
k_rcin13_mapped
k_rcin14_mapped
k_rcin15_mapped
k_rcin16_mapped
k_nr_aux_servo_functions
This must be the last enum value (only add new values before this one)
Definition at line 46 of file SRV_Channel.h.
Limit
enum class SRV_Channel::Limit strong
Enumerator
TRIM
MIN
MAX
ZERO_PWM
Definition at line 203 of file SRV_Channel.h.
Constructor & Destructor Documentation
SRV_Channel()
SRV_Channel::SRV_Channel (void)
Definition at line 167 of file SRV_Channel.cpp.
Member Function Documentation
aux_servo_function_setup()
void SRV_Channel::aux_servo_function_setup (void) private
Definition at line 134 of file SRV_Channel_aux.cpp.
Referenced by SRV_Channels::set_aux_channel_default(), and SRV_Channels::update_aux_servo_function().
calc_pwm()
void SRV_Channel::calc_pwm (float output_scaled) private
Definition at line 213 of file SRV_Channel.cpp.
Referenced by SRV_Channels::calc_pwm(), SRV_Channels::get_output_norm(), and SRV_Channels::get_output_pwm().
function_configured()
bool SRV_Channel::function_configured (void) const inline
Definition at line 279 of file SRV_Channel.h.
function_set_and_save()
void SRV_Channel::function_set_and_save (SRV_Channel::Aux_servo_function_t f) inline
Definition at line 267 of file SRV_Channel.h.
get_function()
SRV_Channel::Aux_servo_function_t SRV_Channel::get_function (void) const inline
Definition at line 259 of file SRV_Channel.h.
Referenced by calc_pwm(), AP_ServoRelayEvents::do_repeat_servo(), AP_ServoRelayEvents::do_set_servo(), get_motor_num(), and AP_Arming::servo_checks().
get_limit_pwm()
uint16_t SRV_Channel::get_limit_pwm (Limit limit) const private
Definition at line 290 of file SRV_Channel.cpp.
Referenced by SRV_Channels::set_failsafe_limit(), and SRV_Channels::set_output_limit().
get_motor_num()
int8_t SRV_Channel::get_motor_num (void) const
Definition at line 375 of file SRV_Channel.cpp.
get_output_max()
uint16_t SRV_Channel::get_output_max (void) const inline
Definition at line 242 of file SRV_Channel.h.
Referenced by AP_MotorsHeli_Single::heli_motors_param_conversions(), and AP_Arming::servo_checks().
get_output_min()
uint16_t SRV_Channel::get_output_min (void) const inline
Definition at line 239 of file SRV_Channel.h.
Referenced by AP_MotorsHeli_Single::heli_motors_param_conversions(), and AP_Arming::servo_checks().
get_output_norm()
float SRV_Channel::get_output_norm (void) private
Definition at line 270 of file SRV_Channel.cpp.
Referenced by SRV_Channels::get_output_norm().
get_output_pwm()
uint16_t SRV_Channel::get_output_pwm (void) const inline
Definition at line 214 of file SRV_Channel.h.
Referenced by SRV_Channels::get_output_pwm(), and AP_SBusOut::update().
get_reversed()
bool SRV_Channel::get_reversed (void) const inline
Definition at line 226 of file SRV_Channel.h.
Referenced by get_output_norm(), SRV_Channels::move_servo(), and AP_MotorsUGV::output_throttle().
get_trim()
uint16_t SRV_Channel::get_trim (void) const inline
Definition at line 245 of file SRV_Channel.h.
Referenced by AP_MotorsHeli_Single::heli_motors_param_conversions(), AP_Arming::servo_checks(), SRV_Channels::set_output_pwm_trimmed(), and AP_ServoRelayEvents::update_events().
ignore_small_rcin_changes()
void SRV_Channel::ignore_small_rcin_changes () inline
Definition at line 288 of file SRV_Channel.h.
Referenced by AP_ServoRelayEvents::do_set_servo(), and AP_ServoRelayEvents::update_events().
is_control_surface()
bool SRV_Channel::is_control_surface (SRV_Channel::Aux_servo_function_t function) static
Definition at line 344 of file SRV_Channel.cpp.
is_motor()
bool SRV_Channel::is_motor (SRV_Channel::Aux_servo_function_t function) static
Definition at line 306 of file SRV_Channel.cpp.
Referenced by AP_Arming::servo_checks(), and SRV_Channels::setup_failsafe_trim_all_non_motors().
output_ch()
void SRV_Channel::output_ch (void) private
map a function to a servo channel and output it
Definition at line 32 of file SRV_Channel_aux.cpp.
Referenced by SRV_Channels::enable_aux_servos(), SRV_Channels::output_ch_all(), SRV_Channels::set_output_pwm(), and SRV_Channels::set_output_pwm_trimmed().
pwm_from_angle()
uint16_t SRV_Channel::pwm_from_angle (float scaled_value) const private
Definition at line 188 of file SRV_Channel.cpp.
Referenced by output_ch(), and pwm_from_scaled_value().
pwm_from_range()
uint16_t SRV_Channel::pwm_from_range (float scaled_value) const private
Definition at line 175 of file SRV_Channel.cpp.
Referenced by output_ch(), and pwm_from_scaled_value().
pwm_from_scaled_value()
uint16_t SRV_Channel::pwm_from_scaled_value (float scaled_value) const
Definition at line 204 of file SRV_Channel.cpp.
Referenced by calc_pwm(), AP_ServoRelayEvents::do_repeat_servo(), AP_ServoRelayEvents::do_set_servo(), and set_output_norm().
reversed_set_and_save_ifchanged()
void SRV_Channel::reversed_set_and_save_ifchanged (bool r) inline
Definition at line 272 of file SRV_Channel.h.
set_angle()
void SRV_Channel::set_angle (int16_t angle)
Definition at line 252 of file SRV_Channel.cpp.
Referenced by aux_servo_function_setup(), and SRV_Channels::set_angle().
set_output_max()
void SRV_Channel::set_output_max (uint16_t pwm) inline
Definition at line 234 of file SRV_Channel.h.
Referenced by SRV_Channels::set_output_min_max().
set_output_min()
void SRV_Channel::set_output_min (uint16_t pwm) inline
Definition at line 231 of file SRV_Channel.h.
Referenced by SRV_Channels::set_output_min_max().
set_output_norm()
void SRV_Channel::set_output_norm (float value)
Definition at line 245 of file SRV_Channel.cpp.
Referenced by SRV_Channels::set_output_norm().
set_output_pwm()
void SRV_Channel::set_output_pwm (uint16_t pwm, bool force = false)
Definition at line 236 of file SRV_Channel.cpp.
Referenced by SRV_Channels::constrain_pwm(), AP_ServoRelayEvents::do_set_servo(), SRV_Channels::enable_aux_servos(), SRV_Channels::move_servo(), SRV_Channels::set_output_limit(), set_output_norm(), SRV_Channels::set_output_pwm(), SRV_Channels::set_output_pwm_chan(), SRV_Channels::set_output_pwm_chan_timeout(), SRV_Channels::set_output_pwm_trimmed(), SRV_Channels::set_output_to_trim(), and AP_ServoRelayEvents::update_events().
set_override()
void SRV_Channel::set_override (bool b) inline private
Definition at line 351 of file SRV_Channel.h.
Referenced by SRV_Channels::calc_pwm(), and SRV_Channels::set_output_pwm_chan_timeout().
set_range()
void SRV_Channel::set_range (uint16_t high)
Definition at line 260 of file SRV_Channel.cpp.
Referenced by aux_servo_function_setup(), and SRV_Channels::set_range().
should_e_stop()
bool SRV_Channel::should_e_stop (SRV_Channel::Aux_servo_function_t function) static
Definition at line 313 of file SRV_Channel.cpp.
Referenced by calc_pwm(), and AP_Arming::servo_checks().
valid_function() [1/2]
static bool SRV_Channel::valid_function (Aux_servo_function_t fn) inline static
Definition at line 195 of file SRV_Channel.h.
Referenced by SRV_Channels::enable_aux_servos().
valid_function() [2/2]
bool SRV_Channel::valid_function (void) const inline
Definition at line 198 of file SRV_Channel.h.
Referenced by SRV_Channels::get_output_channel_mask(), SRV_Channels::get_output_norm(), SRV_Channels::get_output_pwm(), SRV_Channels::get_output_scaled(), SRV_Channels::get_slew_limited_output_scaled(), SRV_Channels::set_aux_channel_default(), SRV_Channels::set_output_scaled(), SRV_Channels::set_slew_rate(), and valid_function().
Friends And Related Symbol Documentation
SRV_Channels
friend class SRV_Channels friend
Definition at line 39 of file SRV_Channel.h.
Member Data Documentation
ch_num
uint8_t SRV_Channel::ch_num private
Definition at line 308 of file SRV_Channel.h.
Referenced by calc_pwm(), SRV_Channels::enable_aux_servos(), SRV_Channels::find_channel(), output_ch(), SRV_Channels::set_digital_outputs(), SRV_Channels::set_failsafe_limit(), SRV_Channels::set_failsafe_pwm(), SRV_Channels::set_output_limit(), set_output_pwm(), SRV_Channels::set_rc_frequency(), and SRV_Channels::SRV_Channels().
function
AP_Enum16<Aux_servo_function_t> SRV_Channel::function private
Definition at line 296 of file SRV_Channel.h.
Referenced by SRV_Channels::adjust_trim(), aux_servo_function_setup(), SRV_Channels::channel_function(), SRV_Channels::constrain_pwm(), SRV_Channels::enable_aux_servos(), function_configured(), function_set_and_save(), get_function(), is_control_surface(), is_motor(), SRV_Channels::move_servo(), output_ch(), SRV_Channels::set_aux_channel_default(), SRV_Channels::set_default_function(), SRV_Channels::set_digital_outputs(), SRV_Channels::set_failsafe_limit(), SRV_Channels::set_failsafe_pwm(), SRV_Channels::set_output_limit(), SRV_Channels::set_output_norm(), SRV_Channels::set_rc_frequency(), should_e_stop(), SRV_Channels::SRV_Channels(), SRV_Channels::update_aux_servo_function(), SRV_Channels::upgrade_parameters(), and valid_function().
have_pwm_mask
SRV_Channel::servo_mask_t SRV_Channel::have_pwm_mask static private
Definition at line 339 of file SRV_Channel.h.
Referenced by calc_pwm(), set_output_pwm(), SRV_Channels::set_output_pwm_chan_timeout(), SRV_Channels::set_output_scaled(), and SRV_Channel().
high_out
uint16_t SRV_Channel::high_out private
Definition at line 311 of file SRV_Channel.h.
Referenced by pwm_from_angle(), pwm_from_range(), set_angle(), set_output_norm(), and set_range().
ign_small_rcin_changes
bool SRV_Channel::ign_small_rcin_changes private
Definition at line 346 of file SRV_Channel.h.
Referenced by ignore_small_rcin_changes(), and output_ch().
output_pwm
uint16_t SRV_Channel::output_pwm private
Definition at line 299 of file SRV_Channel.h.
Referenced by calc_pwm(), SRV_Channels::constrain_pwm(), get_output_norm(), get_output_pwm(), output_ch(), and set_output_pwm().
override_active
bool SRV_Channel::override_active private
Definition at line 349 of file SRV_Channel.h.
Referenced by calc_pwm(), set_output_pwm(), and set_override().
previous_radio_in
int16_t SRV_Channel::previous_radio_in private
Definition at line 342 of file SRV_Channel.h.
Referenced by output_ch().
reversed
AP_Int8 SRV_Channel::reversed private
Definition at line 295 of file SRV_Channel.h.
Referenced by SRV_Channels::adjust_trim(), get_limit_pwm(), get_reversed(), pwm_from_angle(), pwm_from_range(), and reversed_set_and_save_ifchanged().
servo_max
AP_Int16 SRV_Channel::servo_max private
Definition at line 292 of file SRV_Channel.h.
Referenced by SRV_Channels::adjust_trim(), SRV_Channels::constrain_pwm(), SRV_Channels::enable_aux_servos(), get_limit_pwm(), get_output_max(), get_output_norm(), SRV_Channels::move_servo(), pwm_from_angle(), pwm_from_range(), SRV_Channels::set_digital_outputs(), and set_output_max().
servo_min
AP_Int16 SRV_Channel::servo_min private
Definition at line 291 of file SRV_Channel.h.
Referenced by SRV_Channels::adjust_trim(), SRV_Channels::constrain_pwm(), SRV_Channels::enable_aux_servos(), get_limit_pwm(), get_output_min(), get_output_norm(), SRV_Channels::move_servo(), pwm_from_angle(), pwm_from_range(), SRV_Channels::set_digital_outputs(), set_output_min(), and SRV_Channels::set_trim_to_min_for().
servo_trim
AP_Int16 SRV_Channel::servo_trim private
Definition at line 293 of file SRV_Channel.h.
Referenced by SRV_Channels::adjust_trim(), SRV_Channels::enable_aux_servos(), get_limit_pwm(), get_trim(), pwm_from_angle(), SRV_Channels::save_trim(), SRV_Channels::set_digital_outputs(), SRV_Channels::set_trim_to_min_for(), SRV_Channels::set_trim_to_pwm_for(), and SRV_Channels::set_trim_to_servo_out_for().
type_angle
bool SRV_Channel::type_angle private
Definition at line 302 of file SRV_Channel.h.
Referenced by pwm_from_scaled_value(), set_angle(), and set_range().
type_setup
bool SRV_Channel::type_setup private
Definition at line 305 of file SRV_Channel.h.
Referenced by aux_servo_function_setup(), set_angle(), SRV_Channels::set_aux_channel_default(), and set_range().
var_info
const AP_Param::GroupInfo SRV_Channel::var_info static
Definition at line 29 of file SRV_Channel.h.
The documentation for this class was generated from the following files:
libraries/SRV_Channel/SRV_Channel.h
libraries/SRV_Channel/SRV_Channel.cpp
libraries/SRV_Channel/SRV_Channel_aux.cpp