APM:Libraries: AP_HAL::Storage Class Reference
AP_HAL::Storage Class Reference abstract
#include <Storage.h>
Public Member Functions
virtual void init ()=0
virtual bool erase ()
virtual void read_block (void *dst, uint16_t src, size_t n)=0
virtual void write_block (uint16_t dst, const void *src, size_t n)=0
virtual void _timer_tick (void)
virtual bool healthy (void)
virtual bool get_storage_ptr (void *&ptr, size_t &size)
Detailed Description
Definition at line 6 of file Storage.h.
Member Function Documentation
_timer_tick()
virtual void AP_HAL::Storage::_timer_tick (void) inline virtual
Reimplemented in ChibiOS::Storage, ESP32::Storage, Linux::Storage, and HALSITL::Storage.
Definition at line 12 of file Storage.h.
Referenced by Linux::Scheduler::_io_task(), HALSITL::Scheduler::_run_io_procs(), ChibiOS::Scheduler::_storage_thread(), and ESP32::Scheduler::_storage_thread().
erase()
bool AP_HAL::Storage::erase (void) virtual
Reimplemented in ChibiOS::Storage.
Definition at line 8 of file Storage.cpp.
Referenced by ChibiOS::Storage::erase(), and StorageManager::erase().
get_storage_ptr()
virtual bool AP_HAL::Storage::get_storage_ptr (void *& ptr, size_t & size) inline virtual
Reimplemented in ChibiOS::Storage, ESP32::Storage, Linux::Storage, and HALSITL::Storage.
Definition at line 14 of file Storage.h.
Referenced by AP_Filesystem_Sys::open().
healthy()
virtual bool AP_HAL::Storage::healthy (void) inline virtual
Reimplemented in ChibiOS::Storage, ESP32::Storage, and HALSITL::Storage.
Definition at line 13 of file Storage.h.
Referenced by AP_Arming::system_checks().
init()
virtual void AP_HAL::Storage::init () pure virtual
Implemented in ChibiOS::Storage, Empty::Storage, ESP32::Storage, Linux::Storage, and HALSITL::Storage.
Referenced by setup().
read_block()
virtual void AP_HAL::Storage::read_block (void * dst, uint16_t src, size_t n) pure virtual
Implemented in ChibiOS::Storage, Empty::Storage, ESP32::Storage, Linux::Storage, and HALSITL::Storage.
Referenced by StorageAccess::read_block(), and setup().
write_block()
virtual void AP_HAL::Storage::write_block (uint16_t dst, const void * src, size_t n) pure virtual
Implemented in ChibiOS::Storage, Empty::Storage, ESP32::Storage, Linux::Storage, and HALSITL::Storage.
Referenced by erase(), and StorageAccess::write_block().
The documentation for this class was generated from the following files:
libraries/AP_HAL/Storage.h
libraries/AP_HAL/Storage.cpp