APM:Libraries: AC_Avoid Class Reference
AC_Avoid Class Reference
#include <AC_Avoid.h>
Public Member Functions
AC_Avoid ()
Constructor.
CLASS_NO_COPY (AC_Avoid)
bool enabled () const
void adjust_velocity (Vector3f &desired_vel_cms, bool &backing_up, float kP, float accel_cmss, float kP_z, float accel_cmss_z, float dt)
void adjust_velocity (Vector3f &desired_vel_cms, float kP, float accel_cmss, float kP_z, float accel_cmss_z, float dt)
void adjust_velocity_fence (float kP, float accel_cmss, Vector3f &desired_vel_cms, Vector3f &backup_vel, float kP_z, float accel_cmss_z, float dt)
void adjust_speed (float kP, float accel, float heading, float &speed, float dt)
void adjust_velocity_z (float kP, float accel_cmss, float &climb_rate_cms, float &backup_speed, float dt)
void adjust_velocity_z (float kP, float accel_cmss, float &climb_rate_cms, float dt)
void adjust_roll_pitch (float &roll, float &pitch, float angle_max)
void proximity_avoidance_enable (bool on_off)
bool proximity_avoidance_enabled () const
void proximity_alt_avoidance_enable (bool on_off)
void limit_velocity_2D (float kP, float accel_cmss, Vector2f &desired_vel_cms, const Vector2f &limit_direction, float limit_distance_cm, float dt)
void limit_velocity_3D (float kP, float accel_cmss, Vector3f &desired_vel_cms, const Vector3f &limit_direction, float limit_distance_cm, float kP_z, float accel_cmss_z, float dt)
float get_max_speed (float kP, float accel_cmss, float distance_cm, float dt) const
float get_margin () const
float get_min_alt () const
bool limits_active () const
Static Public Member Functions
static AC_Avoid * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
enum BehaviourType { BEHAVIOR_SLIDE = 0 , BEHAVIOR_STOP = 1 }
Private Member Functions
void limit_accel (const Vector3f &original_vel, Vector3f &modified_vel, float dt)
void adjust_velocity_circle_fence (float kP, float accel_cmss, Vector2f &desired_vel_cms, Vector2f &backup_vel, float dt)
void adjust_velocity_inclusion_and_exclusion_polygons (float kP, float accel_cmss, Vector2f &desired_vel_cms, Vector2f &backup_vel, float dt)
void adjust_velocity_inclusion_circles (float kP, float accel_cmss, Vector2f &desired_vel_cms, Vector2f &backup_vel, float dt)
void adjust_velocity_exclusion_circles (float kP, float accel_cmss, Vector2f &desired_vel_cms, Vector2f &backup_vel, float dt)
void adjust_velocity_beacon_fence (float kP, float accel_cmss, Vector2f &desired_vel_cms, Vector2f &backup_vel, float dt)
void adjust_velocity_proximity (float kP, float accel_cmss, Vector3f &desired_vel_cms, Vector3f &backup_vel, float kP_z, float accel_cmss_z, float dt)
void adjust_velocity_polygon (float kP, float accel_cmss, Vector2f &desired_vel_cms, Vector2f &backup_vel, const Vector2f *boundary, uint16_t num_points, float margin, float dt, bool stay_inside)
float get_stopping_distance (float kP, float accel_cmss, float speed_cms) const
void calc_backup_velocity_2D (float kP, float accel_cmss, Vector2f &quad1_back_vel_cms, Vector2f &qua2_back_vel_cms, Vector2f &quad3_back_vel_cms, Vector2f &quad4_back_vel_cms, float back_distance_cm, Vector2f limit_direction, float dt)
void calc_backup_velocity_3D (float kP, float accel_cmss, Vector2f &quad1_back_vel_cms, Vector2f &quad2_back_vel_cms, Vector2f &quad3_back_vel_cms, Vector2f &quad4_back_vel_cms, float back_distance_cms, Vector3f limit_direction, float kp_z, float accel_cmss_z, float back_distance_z, float &min_z_vel, float &max_z_vel, float dt)
void find_max_quadrant_velocity (Vector2f &desired_vel, Vector2f &quad1_vel, Vector2f &quad2_vel, Vector2f &quad3_vel, Vector2f &quad4_vel)
void find_max_quadrant_velocity_3D (Vector3f &desired_vel, Vector2f &quad1_vel, Vector2f &quad2_vel, Vector2f &quad3_vel, Vector2f &quad4_vel, float &max_z_vel, float &min_z_vel)
float distance_to_lean_pct (float dist_m)
void get_proximity_roll_pitch_pct (float &roll_positive, float &roll_negative, float &pitch_positive, float &pitch_negative)
void Write_SimpleAvoidance (const uint8_t state, const Vector3f &desired_vel, const Vector3f &modified_vel, const bool back_up) const
Private Attributes
AP_Int8 _enabled
AP_Int16 _angle_max
AP_Float _dist_max
AP_Float _margin
AP_Int8 _behavior
AP_Float _backup_speed_max
AP_Float _alt_min
AP_Float _accel_max
AP_Float _backup_deadzone
bool _proximity_enabled = true
bool _proximity_alt_enabled = true
uint32_t _last_limit_time
uint32_t _last_log_ms
Vector3f _prev_avoid_vel
Static Private Attributes
static AC_Avoid * _singleton
Detailed Description
Definition at line 28 of file AC_Avoid.h.
Member Enumeration Documentation
BehaviourType
enum AC_Avoid::BehaviourType private
Enumerator
BEHAVIOR_SLIDE
BEHAVIOR_STOP
Definition at line 116 of file AC_Avoid.h.
Constructor & Destructor Documentation
AC_Avoid()
AC_Avoid::AC_Avoid ()
Constructor.
Definition at line 114 of file AC_Avoid.cpp.
Member Function Documentation
adjust_roll_pitch()
void AC_Avoid::adjust_roll_pitch (float & roll, float & pitch, float angle_max)
Definition at line 434 of file AC_Avoid.cpp.
adjust_speed()
void AC_Avoid::adjust_speed (float kP, float accel, float heading, float & speed, float dt)
Definition at line 320 of file AC_Avoid.cpp.
adjust_velocity() [1/2]
void AC_Avoid::adjust_velocity (Vector3f & desired_vel_cms, bool & backing_up, float kP, float accel_cmss, float kP_z, float accel_cmss_z, float dt)
Definition at line 187 of file AC_Avoid.cpp.
Referenced by adjust_speed(), adjust_velocity(), AC_Loiter::calc_desired_velocity(), and AR_PosControl::update().
adjust_velocity() [2/2]
void AC_Avoid::adjust_velocity (Vector3f & desired_vel_cms, float kP, float accel_cmss, float kP_z, float accel_cmss_z, float dt) inline
Definition at line 48 of file AC_Avoid.h.
adjust_velocity_beacon_fence()
void AC_Avoid::adjust_velocity_beacon_fence (float kP, float accel_cmss, Vector2f & desired_vel_cms, Vector2f & backup_vel, float dt) private
Referenced by adjust_velocity_fence().
adjust_velocity_circle_fence()
void AC_Avoid::adjust_velocity_circle_fence (float kP, float accel_cmss, Vector2f & desired_vel_cms, Vector2f & backup_vel, float dt) private
Referenced by adjust_velocity_fence().
adjust_velocity_exclusion_circles()
void AC_Avoid::adjust_velocity_exclusion_circles (float kP, float accel_cmss, Vector2f & desired_vel_cms, Vector2f & backup_vel, float dt) private
Referenced by adjust_velocity_fence().
adjust_velocity_fence()
void AC_Avoid::adjust_velocity_fence (float kP, float accel_cmss, Vector3f & desired_vel_cms, Vector3f & backup_vel, float kP_z, float accel_cmss_z, float dt)
Definition at line 125 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
adjust_velocity_inclusion_and_exclusion_polygons()
void AC_Avoid::adjust_velocity_inclusion_and_exclusion_polygons (float kP, float accel_cmss, Vector2f & desired_vel_cms, Vector2f & backup_vel, float dt) private
Referenced by adjust_velocity_fence().
adjust_velocity_inclusion_circles()
void AC_Avoid::adjust_velocity_inclusion_circles (float kP, float accel_cmss, Vector2f & desired_vel_cms, Vector2f & backup_vel, float dt) private
Referenced by adjust_velocity_fence().
adjust_velocity_polygon()
void AC_Avoid::adjust_velocity_polygon (float kP, float accel_cmss, Vector2f & desired_vel_cms, Vector2f & backup_vel, const Vector2f * boundary, uint16_t num_points, float margin, float dt, bool stay_inside) private
Definition at line 1276 of file AC_Avoid.cpp.
adjust_velocity_proximity()
void AC_Avoid::adjust_velocity_proximity (float kP, float accel_cmss, Vector3f & desired_vel_cms, Vector3f & backup_vel, float kP_z, float accel_cmss_z, float dt) private
Definition at line 1132 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
adjust_velocity_z() [1/2]
void AC_Avoid::adjust_velocity_z (float kP, float accel_cmss, float & climb_rate_cms, float & backup_speed, float dt)
Definition at line 353 of file AC_Avoid.cpp.
Referenced by adjust_velocity_fence(), and adjust_velocity_z().
adjust_velocity_z() [2/2]
void AC_Avoid::adjust_velocity_z (float kP, float accel_cmss, float & climb_rate_cms, float dt) inline
Definition at line 67 of file AC_Avoid.h.
calc_backup_velocity_2D()
void AC_Avoid::calc_backup_velocity_2D (float kP, float accel_cmss, Vector2f & quad1_back_vel_cms, Vector2f & qua2_back_vel_cms, Vector2f & quad3_back_vel_cms, Vector2f & quad4_back_vel_cms, float back_distance_cm, Vector2f limit_direction, float dt) private
Definition at line 561 of file AC_Avoid.cpp.
Referenced by adjust_velocity_polygon(), and calc_backup_velocity_3D().
calc_backup_velocity_3D()
void AC_Avoid::calc_backup_velocity_3D (float kP, float accel_cmss, Vector2f & quad1_back_vel_cms, Vector2f & quad2_back_vel_cms, Vector2f & quad3_back_vel_cms, Vector2f & quad4_back_vel_cms, float back_distance_cms, Vector3f limit_direction, float kp_z, float accel_cmss_z, float back_distance_z, float & min_z_vel, float & max_z_vel, float dt) private
Definition at line 585 of file AC_Avoid.cpp.
Referenced by adjust_velocity_proximity().
CLASS_NO_COPY()
AC_Avoid::CLASS_NO_COPY (AC_Avoid)
distance_to_lean_pct()
float AC_Avoid::distance_to_lean_pct (float dist_m) private
Definition at line 1418 of file AC_Avoid.cpp.
Referenced by get_proximity_roll_pitch_pct().
enabled()
bool AC_Avoid::enabled () const inline
Definition at line 41 of file AC_Avoid.h.
find_max_quadrant_velocity()
void AC_Avoid::find_max_quadrant_velocity (Vector2f & desired_vel, Vector2f & quad1_vel, Vector2f & quad2_vel, Vector2f & quad3_vel, Vector2f & quad4_vel) private
Definition at line 617 of file AC_Avoid.cpp.
Referenced by adjust_velocity_fence(), calc_backup_velocity_2D(), and find_max_quadrant_velocity_3D().
find_max_quadrant_velocity_3D()
void AC_Avoid::find_max_quadrant_velocity_3D (Vector3f & desired_vel, Vector2f & quad1_vel, Vector2f & quad2_vel, Vector2f & quad3_vel, Vector2f & quad4_vel, float & max_z_vel, float & min_z_vel) private
Definition at line 643 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
get_margin()
float AC_Avoid::get_margin () const inline
Definition at line 104 of file AC_Avoid.h.
get_max_speed()
float AC_Avoid::get_max_speed (float kP, float accel_cmss, float distance_cm, float dt) const
Definition at line 662 of file AC_Avoid.cpp.
Referenced by adjust_velocity_z(), calc_backup_velocity_2D(), calc_backup_velocity_3D(), limit_velocity_2D(), and limit_velocity_3D().
get_min_alt()
float AC_Avoid::get_min_alt () const inline
Definition at line 107 of file AC_Avoid.h.
get_proximity_roll_pitch_pct()
void AC_Avoid::get_proximity_roll_pitch_pct (float & roll_positive, float & roll_negative, float & pitch_positive, float & pitch_negative) private
Definition at line 1429 of file AC_Avoid.cpp.
Referenced by adjust_roll_pitch().
get_singleton()
static AC_Avoid * AC_Avoid::get_singleton () inline static
Definition at line 36 of file AC_Avoid.h.
Referenced by AP::ac_avoid().
get_stopping_distance()
float AC_Avoid::get_stopping_distance (float kP, float accel_cmss, float speed_cms) const private
Definition at line 1395 of file AC_Avoid.cpp.
Referenced by adjust_velocity_polygon(), and adjust_velocity_proximity().
limit_accel()
void AC_Avoid::limit_accel (const Vector3f & original_vel, Vector3f & modified_vel, float dt) private
Definition at line 286 of file AC_Avoid.cpp.
Referenced by adjust_velocity().
limit_velocity_2D()
void AC_Avoid::limit_velocity_2D (float kP, float accel_cmss, Vector2f & desired_vel_cms, const Vector2f & limit_direction, float limit_distance_cm, float dt)
Definition at line 488 of file AC_Avoid.cpp.
Referenced by adjust_velocity_polygon(), and limit_velocity_3D().
limit_velocity_3D()
void AC_Avoid::limit_velocity_3D (float kP, float accel_cmss, Vector3f & desired_vel_cms, const Vector3f & limit_direction, float limit_distance_cm, float kP_z, float accel_cmss_z, float dt)
Definition at line 503 of file AC_Avoid.cpp.
Referenced by adjust_velocity_proximity().
limits_active()
bool AC_Avoid::limits_active () const inline
Definition at line 110 of file AC_Avoid.h.
Referenced by adjust_velocity().
proximity_alt_avoidance_enable()
void AC_Avoid::proximity_alt_avoidance_enable (bool on_off) inline
Definition at line 84 of file AC_Avoid.h.
proximity_avoidance_enable()
void AC_Avoid::proximity_avoidance_enable (bool on_off) inline
Definition at line 82 of file AC_Avoid.h.
Referenced by RC_Channel::do_aux_function_avoid_proximity().
proximity_avoidance_enabled()
bool AC_Avoid::proximity_avoidance_enabled () const inline
Definition at line 83 of file AC_Avoid.h.
Referenced by adjust_roll_pitch(), adjust_velocity(), and adjust_velocity_z().
Write_SimpleAvoidance()
void AC_Avoid::Write_SimpleAvoidance (const uint8_t state, const Vector3f & desired_vel, const Vector3f & modified_vel, const bool back_up) const private
Referenced by adjust_velocity().
Member Data Documentation
_accel_max
AP_Float AC_Avoid::_accel_max private
Definition at line 216 of file AC_Avoid.h.
Referenced by limit_accel().
_alt_min
AP_Float AC_Avoid::_alt_min private
Definition at line 215 of file AC_Avoid.h.
Referenced by get_min_alt().
_angle_max
AP_Int16 AC_Avoid::_angle_max private
Definition at line 210 of file AC_Avoid.h.
Referenced by adjust_roll_pitch().
_backup_deadzone
AP_Float AC_Avoid::_backup_deadzone private
Definition at line 217 of file AC_Avoid.h.
Referenced by adjust_velocity_proximity().
_backup_speed_max
AP_Float AC_Avoid::_backup_speed_max private
Definition at line 214 of file AC_Avoid.h.
Referenced by adjust_velocity().
_behavior
AP_Int8 AC_Avoid::_behavior private
Definition at line 213 of file AC_Avoid.h.
Referenced by adjust_velocity_polygon(), and adjust_velocity_proximity().
_dist_max
AP_Float AC_Avoid::_dist_max private
Definition at line 211 of file AC_Avoid.h.
Referenced by distance_to_lean_pct(), and get_proximity_roll_pitch_pct().
_enabled
AP_Int8 AC_Avoid::_enabled private
Definition at line 209 of file AC_Avoid.h.
Referenced by adjust_velocity(), adjust_velocity_fence(), adjust_velocity_z(), enabled(), and proximity_avoidance_enabled().
_last_limit_time
uint32_t AC_Avoid::_last_limit_time private
Definition at line 221 of file AC_Avoid.h.
Referenced by adjust_velocity(), limit_accel(), and limits_active().
_last_log_ms
uint32_t AC_Avoid::_last_log_ms private
Definition at line 222 of file AC_Avoid.h.
Referenced by adjust_velocity().
_margin
AP_Float AC_Avoid::_margin private
Definition at line 212 of file AC_Avoid.h.
Referenced by adjust_velocity_proximity(), adjust_velocity_z(), and get_margin().
_prev_avoid_vel
Vector3f AC_Avoid::_prev_avoid_vel private
Definition at line 223 of file AC_Avoid.h.
Referenced by limit_accel().
_proximity_alt_enabled
bool AC_Avoid::_proximity_alt_enabled = true private
Definition at line 220 of file AC_Avoid.h.
Referenced by adjust_velocity(), and proximity_alt_avoidance_enable().
_proximity_enabled
bool AC_Avoid::_proximity_enabled = true private
Definition at line 219 of file AC_Avoid.h.
Referenced by proximity_avoidance_enable(), and proximity_avoidance_enabled().
_singleton
AC_Avoid * AC_Avoid::_singleton static private
Definition at line 225 of file AC_Avoid.h.
Referenced by AC_Avoid().
var_info
const AP_Param::GroupInfo AC_Avoid::var_info static
Definition at line 37 of file AC_Avoid.h.
The documentation for this class was generated from the following files:
libraries/AC_Avoidance/AC_Avoid.h
libraries/AC_Avoidance/AC_Avoid.cpp