APM:Libraries: AP_Frsky_SPort_Passthrough Class Reference
AP_Frsky_SPort_Passthrough Class Reference
#include <AP_Frsky_SPort_Passthrough.h>
Public Types
enum PassthroughPacketType : uint8_t {
TEXT = 0 , ATTITUDE = 1 , GPS_LAT = 2 , GPS_LON = 3 ,
VEL_YAW = 4 , AP_STATUS = 5 , GPS_STATUS = 6 , HOME = 7 ,
BATT_2 = 8 , BATT_1 = 9 , PARAM = 10 , RPM = 11 ,
UDATA = 12 , MAV = 13 , TERRAIN = 14 , WIND = 15 ,
WAYPOINT = 16 , WFQ_LAST_ITEM
}
Public Member Functions
AP_Frsky_SPort_Passthrough (AP_HAL::UARTDriver *port, bool use_external_data, AP_Frsky_Parameters *&frsky_parameters)
bool init () override
bool init_serial_port () override
bool is_packet_ready (uint8_t idx, bool queue_empty) override
void process_packet (uint8_t idx) override
void adjust_packet_weight (bool queue_empty) override
void setup_wfq_scheduler (void) override
bool get_next_msg_chunk (void) override
bool get_telem_data (sport_packet_t *packet_array, uint8_t &packet_count, const uint8_t max_size) override
bool set_telem_data (const uint8_t frame, const uint16_t appid, const uint32_t data) override
void queue_text_message (MAV_SEVERITY severity, const char *text) override
Public Member Functions inherited from AP_Frsky_SPort
AP_Frsky_SPort (AP_HAL::UARTDriver *port)
CLASS_NO_COPY (AP_Frsky_SPort)
bool sport_telemetry_push (const uint8_t sensor, const uint8_t frame, const uint16_t appid, const int32_t data)
uint16_t prep_number (int32_t const number, const uint8_t digits, const uint8_t power)
Public Member Functions inherited from AP_Frsky_Backend
AP_Frsky_Backend (AP_HAL::UARTDriver *port)
virtual ~AP_Frsky_Backend ()
virtual uint32_t initial_baud () const
Public Member Functions inherited from AP_RCTelemetry
AP_RCTelemetry (uint8_t time_slots)
virtual ~AP_RCTelemetry ()
CLASS_NO_COPY (AP_RCTelemetry)
virtual void queue_message (MAV_SEVERITY severity, const char *text)
void enable_scheduler_entry (const uint8_t slot)
void disable_scheduler_entry (const uint8_t slot)
void set_scheduler_entry_min_period (const uint8_t slot, const uint32_t min_period_ms)
bool is_scheduler_entry_enabled (const uint8_t slot) const
virtual void reset_scheduler_entry_min_periods ()
uint32_t sensor_status_flags () const
uint16_t get_avg_packet_rate () const
uint16_t get_max_packet_rate () const
Static Public Member Functions
static AP_Frsky_SPort_Passthrough * get_singleton (void)
Static Public Member Functions inherited from AP_Frsky_SPort
static AP_Frsky_SPort * get_singleton (void)
Protected Member Functions
void send () override
Protected Member Functions inherited from AP_Frsky_SPort
void send_sport_frame (uint8_t frame, uint16_t appid, uint32_t data)
uint32_t calc_gps_latlng (bool &send_latitude)
Protected Member Functions inherited from AP_Frsky_Backend
void calc_nav_alt (void)
void calc_gps_position (void)
bool calc_rpm (const uint8_t instance, int32_t &value) const
float get_vspeed_ms (void)
float format_gps (float dec)
Protected Member Functions inherited from AP_RCTelemetry
uint8_t run_wfq_scheduler (const bool use_shaper=true)
bool process_scheduler_entry (const uint8_t slot)
void set_scheduler_entry (uint8_t slot, uint32_t weight, uint32_t min_period_ms)
void add_scheduler_entry (uint32_t weight, uint32_t min_period_ms)
Private Types
enum PassthroughParam : uint8_t {
NONE = 0 , FRAME_TYPE = 1 , BATT_FS_VOLTAGE = 2 , BATT_FS_CAPACITY = 3 ,
BATT_CAPACITY_1 = 4 , BATT_CAPACITY_2 = 5 , TELEMETRY_FEATURES = 6
}
enum PassthroughFeatures : uint8_t { BIDIR = 0 , SCRIPTING = 1 }
Private Member Functions
uint32_t calc_param (void)
uint32_t calc_batt (uint8_t instance)
uint32_t calc_ap_status (void)
uint32_t calc_home (void)
uint32_t calc_velandyaw (void)
uint32_t calc_attiandrng (void)
uint32_t calc_rpm (void)
uint32_t calc_terrain (void)
uint32_t calc_wind (void)
uint32_t calc_waypoint (void)
void set_sensor_id (AP_Int8 idx, uint8_t &sensor)
void queue_rx_packet (const AP_Frsky_SPort::sport_packet_t sp)
void process_rx_queue (void)
void process_tx_queue (void)
bool send_message (const AP_Frsky_MAVlite_Message &txmsg)
void send_sport_frame (uint8_t frame, uint16_t appid, uint32_t data)
bool is_passthrough_byte (const uint8_t byte) const
uint32_t calc_gps_status (void)
Private Attributes
AP_Frsky_Parameters *& _frsky_parameters
bool _use_external_data
struct {
sport_packet_t packet
bool pending
} external_data
struct {
uint32_t chunk
uint8_t repeats
uint8_t char_index
} _msg_chunk
uint8_t downlink_sensor_id = 0x1B
struct {
uint8_t uplink_sensor_id = 0x0D
uint8_t downlink1_sensor_id = 0x34
uint8_t downlink2_sensor_id = 0x67
uint8_t tx_packet_duplicates
ObjectBuffer_TS< AP_Frsky_SPort::sport_packet_t > rx_packet_queue {SPORT_PACKET_QUEUE_LENGTH}
ObjectBuffer_TS< AP_Frsky_SPort::sport_packet_t > tx_packet_queue {SPORT_PACKET_QUEUE_LENGTH}
} _SPort_bidir
AP_Frsky_SPortParser _sport_handler
AP_Frsky_MAVlite_SPortToMAVlite sport_to_mavlite
AP_Frsky_MAVlite_MAVliteToSPort mavlite_to_sport
AP_Frsky_MAVliteMsgHandler mavlite {FUNCTOR_BIND_MEMBER(&AP_Frsky_SPort_Passthrough::send_message, bool, const AP_Frsky_MAVlite_Message &)}
uint8_t _paramID
Static Private Attributes
static AP_Frsky_SPort_Passthrough * singleton
Additional Inherited Members
Protected Types inherited from AP_Frsky_Backend
enum frsky_options_e : uint8_t { OPTION_AIRSPEED_AND_GROUNDSPEED = 1U<<0 }
Static Protected Member Functions inherited from AP_Frsky_SPort
static uint8_t calc_sensor_id (const uint8_t physical_id)
Protected Attributes inherited from AP_Frsky_SPort
struct {
bool send_latitude
bool send_airspeed
uint32_t gps_lng_sample
uint8_t new_byte
} _passthrough
struct {
sport_packet_t packet
bool pending = false
HAL_Semaphore sem
} _sport_push_buffer
Protected Attributes inherited from AP_Frsky_Backend
AP_HAL::UARTDriver * _port
struct {
int32_t vario_vspd
char lat_ns
char lon_ew
uint16_t latdddmm
uint16_t latmmmm
uint16_t londddmm
uint16_t lonmmmm
uint16_t alt_gps_meters
uint16_t alt_gps_cm
uint16_t alt_nav_meters
uint16_t alt_nav_cm
int16_t speed_in_meter
uint16_t speed_in_centimeter
uint16_t yaw
} _SPort_data
Protected Attributes inherited from AP_RCTelemetry
uint8_t _time_slots
struct {
uint32_t last_poll_timer
uint32_t avg_packet_counter
uint32_t packet_timer [TELEM_TIME_SLOT_MAX]
uint32_t packet_weight [TELEM_TIME_SLOT_MAX]
uint32_t packet_min_period [TELEM_TIME_SLOT_MAX]
uint16_t avg_packet_rate
uint16_t max_packet_rate
} _scheduler
struct {
HAL_Semaphore sem
ObjectBuffer< mavlink_statustext_t > queue {TELEM_PAYLOAD_STATUS_CAPACITY}
mavlink_statustext_t next
bool available
} _statustext
Static Protected Attributes inherited from AP_Frsky_Backend
static const uint8_t DATA_ID_GPS_ALT_BP = 0x01
static const uint8_t DATA_ID_TEMP1 = 0x02
static const uint8_t DATA_ID_FUEL = 0x04
static const uint8_t DATA_ID_TEMP2 = 0x05
static const uint8_t DATA_ID_GPS_ALT_AP = 0x09
static const uint8_t DATA_ID_BARO_ALT_BP = 0x10
static const uint8_t DATA_ID_GPS_SPEED_BP = 0x11
static const uint8_t DATA_ID_GPS_LONG_BP = 0x12
static const uint8_t DATA_ID_GPS_LAT_BP = 0x13
static const uint8_t DATA_ID_GPS_COURS_BP = 0x14
static const uint8_t DATA_ID_GPS_SPEED_AP = 0x19
static const uint8_t DATA_ID_GPS_LONG_AP = 0x1A
static const uint8_t DATA_ID_GPS_LAT_AP = 0x1B
static const uint8_t DATA_ID_BARO_ALT_AP = 0x21
static const uint8_t DATA_ID_GPS_LONG_EW = 0x22
static const uint8_t DATA_ID_GPS_LAT_NS = 0x23
static const uint8_t DATA_ID_CURRENT = 0x28
static const uint8_t DATA_ID_VFAS = 0x39
static const uint8_t START_STOP_D = 0x5E
static const uint8_t BYTESTUFF_D = 0x5D
static const uint16_t ALT_ID = 0x010F
static const uint16_t VARIO_ID = 0x011F
static const uint16_t CURR_ID = 0x020F
static const uint16_t VFAS_ID = 0x021F
static const uint16_t TEMP1_ID = 0x040F
static const uint16_t TEMP2_ID = 0x041F
static const uint16_t RPM1_ID = 0x050E
static const uint16_t RPM2_ID = 0x050F
static const uint16_t FUEL_ID = 0x060F
static const uint16_t GPS_LONG_LATI_FIRST_ID = 0x0800
static const uint16_t GPS_ALT_ID = 0x082F
static const uint16_t GPS_SPEED_ID = 0x083F
static const uint16_t GPS_COURS_ID = 0x084F
static const uint16_t DIY_FIRST_ID = 0x5000
static const uint8_t FRAME_HEAD = 0x7E
static const uint8_t FRAME_DLE = 0x7D
static const uint8_t FRAME_XOR = 0x20
static const uint8_t SPORT_DATA_FRAME = 0x10
static const uint8_t SENSOR_ID_VARIO = 0x00
static const uint8_t SENSOR_ID_FAS = 0x22
static const uint8_t SENSOR_ID_GPS = 0x83
static const uint8_t SENSOR_ID_RPM = 0xE4
static const uint8_t SENSOR_ID_SP2UR = 0xC6
Detailed Description
Definition at line 22 of file AP_Frsky_SPort_Passthrough.h.
Member Enumeration Documentation
PassthroughFeatures
enum AP_Frsky_SPort_Passthrough::PassthroughFeatures : uint8_t private
Enumerator
BIDIR
SCRIPTING
Definition at line 102 of file AP_Frsky_SPort_Passthrough.h.
PassthroughPacketType
enum AP_Frsky_SPort_Passthrough::PassthroughPacketType : uint8_t
Enumerator
TEXT
ATTITUDE
GPS_LAT
GPS_LON
VEL_YAW
AP_STATUS
GPS_STATUS
HOME
BATT_2
BATT_1
PARAM
RPM
UDATA
MAV
TERRAIN
WIND
WAYPOINT
WFQ_LAST_ITEM
Definition at line 61 of file AP_Frsky_SPort_Passthrough.h.
PassthroughParam
enum AP_Frsky_SPort_Passthrough::PassthroughParam : uint8_t private
Enumerator
NONE
FRAME_TYPE
BATT_FS_VOLTAGE
BATT_FS_CAPACITY
BATT_CAPACITY_1
BATT_CAPACITY_2
TELEMETRY_FEATURES
Definition at line 92 of file AP_Frsky_SPort_Passthrough.h.
Constructor & Destructor Documentation
AP_Frsky_SPort_Passthrough()
AP_Frsky_SPort_Passthrough::AP_Frsky_SPort_Passthrough (AP_HAL::UARTDriver * port, bool use_external_data, AP_Frsky_Parameters *& frsky_parameters) inline
Definition at line 26 of file AP_Frsky_SPort_Passthrough.h.
Member Function Documentation
adjust_packet_weight()
void AP_Frsky_SPort_Passthrough::adjust_packet_weight (bool queue_empty) override virtual
Reimplemented from AP_RCTelemetry.
Definition at line 161 of file AP_Frsky_SPort_Passthrough.cpp.
calc_ap_status()
uint32_t AP_Frsky_SPort_Passthrough::calc_ap_status (void) private
Definition at line 566 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
calc_attiandrng()
uint32_t AP_Frsky_SPort_Passthrough::calc_attiandrng (void) private
Definition at line 684 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
calc_batt()
uint32_t AP_Frsky_SPort_Passthrough::calc_batt (uint8_t instance) private
Definition at line 527 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
calc_gps_status()
uint32_t AP_Frsky_SPort_Passthrough::calc_gps_status (void) private
Definition at line 505 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
calc_home()
uint32_t AP_Frsky_SPort_Passthrough::calc_home (void) private
Definition at line 608 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
calc_param()
uint32_t AP_Frsky_SPort_Passthrough::calc_param (void) private
Definition at line 468 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
calc_rpm()
uint32_t AP_Frsky_SPort_Passthrough::calc_rpm (void) private
Definition at line 704 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
calc_terrain()
uint32_t AP_Frsky_SPort_Passthrough::calc_terrain (void) private
Definition at line 732 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
calc_velandyaw()
uint32_t AP_Frsky_SPort_Passthrough::calc_velandyaw (void) private
Definition at line 647 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
calc_waypoint()
uint32_t AP_Frsky_SPort_Passthrough::calc_waypoint (void) private
Definition at line 789 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
calc_wind()
uint32_t AP_Frsky_SPort_Passthrough::calc_wind (void) private
Definition at line 756 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
get_next_msg_chunk()
bool AP_Frsky_SPort_Passthrough::get_next_msg_chunk (void) override virtual
Reimplemented from AP_RCTelemetry.
Definition at line 407 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
get_singleton()
static AP_Frsky_SPort_Passthrough * AP_Frsky_SPort_Passthrough::get_singleton (void) inline static
Definition at line 35 of file AP_Frsky_SPort_Passthrough.h.
Referenced by AP::frsky_passthrough_telem().
get_telem_data()
bool AP_Frsky_SPort_Passthrough::get_telem_data (sport_packet_t * packet_array, uint8_t & packet_count, const uint8_t max_size) override virtual
Reimplemented from AP_Frsky_Backend.
Definition at line 819 of file AP_Frsky_SPort_Passthrough.cpp.
init()
bool AP_Frsky_SPort_Passthrough::init (void) override virtual
Reimplemented from AP_Frsky_Backend.
Definition at line 91 of file AP_Frsky_SPort_Passthrough.cpp.
init_serial_port()
bool AP_Frsky_SPort_Passthrough::init_serial_port () override virtual
Reimplemented from AP_Frsky_Backend.
Definition at line 99 of file AP_Frsky_SPort_Passthrough.cpp.
is_packet_ready()
bool AP_Frsky_SPort_Passthrough::is_packet_ready (uint8_t idx, bool queue_empty) override virtual
Reimplemented from AP_RCTelemetry.
Definition at line 206 of file AP_Frsky_SPort_Passthrough.cpp.
is_passthrough_byte()
bool AP_Frsky_SPort_Passthrough::is_passthrough_byte (const uint8_t byte) const private
Definition at line 552 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by send().
process_packet()
void AP_Frsky_SPort_Passthrough::process_packet (uint8_t idx) override virtual
Implements AP_RCTelemetry.
Definition at line 290 of file AP_Frsky_SPort_Passthrough.cpp.
process_rx_queue()
void AP_Frsky_SPort_Passthrough::process_rx_queue (void) private
Definition at line 900 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by setup_wfq_scheduler().
process_tx_queue()
void AP_Frsky_SPort_Passthrough::process_tx_queue (void) private
Definition at line 919 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet().
queue_rx_packet()
void AP_Frsky_SPort_Passthrough::queue_rx_packet (const AP_Frsky_SPort::sport_packet_t sp) private
Definition at line 888 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by send().
queue_text_message()
void AP_Frsky_SPort_Passthrough::queue_text_message (MAV_SEVERITY severity, const char * text) inline override virtual
Reimplemented from AP_Frsky_Backend.
Definition at line 56 of file AP_Frsky_SPort_Passthrough.h.
send()
void AP_Frsky_SPort_Passthrough::send (void) override protected virtual
Reimplemented from AP_Frsky_SPort.
Definition at line 367 of file AP_Frsky_SPort_Passthrough.cpp.
send_message()
bool AP_Frsky_SPort_Passthrough::send_message (const AP_Frsky_MAVlite_Message & txmsg) private
Definition at line 958 of file AP_Frsky_SPort_Passthrough.cpp.
send_sport_frame()
void AP_Frsky_SPort_Passthrough::send_sport_frame (uint8_t frame, uint16_t appid, uint32_t data) private
Definition at line 107 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by process_packet(), process_tx_queue(), and send().
set_sensor_id()
void AP_Frsky_SPort_Passthrough::set_sensor_id (AP_Int8 idx, uint8_t & sensor) private
Definition at line 941 of file AP_Frsky_SPort_Passthrough.cpp.
Referenced by setup_wfq_scheduler().
set_telem_data()
bool AP_Frsky_SPort_Passthrough::set_telem_data (const uint8_t frame, const uint16_t appid, const uint32_t data) override virtual
Reimplemented from AP_Frsky_Backend.
Definition at line 867 of file AP_Frsky_SPort_Passthrough.cpp.
setup_wfq_scheduler()
void AP_Frsky_SPort_Passthrough::setup_wfq_scheduler (void) override virtual
Implements AP_RCTelemetry.
Definition at line 123 of file AP_Frsky_SPort_Passthrough.cpp.
Member Data Documentation
_frsky_parameters
AP_Frsky_Parameters*& AP_Frsky_SPort_Passthrough::_frsky_parameters private
Definition at line 90 of file AP_Frsky_SPort_Passthrough.h.
Referenced by calc_velandyaw(), and setup_wfq_scheduler().
[struct]
struct { ... } AP_Frsky_SPort_Passthrough::_msg_chunk
Referenced by get_next_msg_chunk(), and process_packet().
_paramID
uint8_t AP_Frsky_SPort_Passthrough::_paramID private
Definition at line 169 of file AP_Frsky_SPort_Passthrough.h.
Referenced by calc_param().
[struct]
struct { ... } AP_Frsky_SPort_Passthrough::_SPort_bidir
Referenced by adjust_packet_weight(), is_packet_ready(), is_passthrough_byte(), process_rx_queue(), process_tx_queue(), queue_rx_packet(), send_message(), set_telem_data(), and setup_wfq_scheduler().
_sport_handler
AP_Frsky_SPortParser AP_Frsky_SPort_Passthrough::_sport_handler private
Definition at line 148 of file AP_Frsky_SPort_Passthrough.h.
Referenced by send().
_use_external_data
bool AP_Frsky_SPort_Passthrough::_use_external_data private
Definition at line 121 of file AP_Frsky_SPort_Passthrough.h.
Referenced by adjust_packet_weight(), get_telem_data(), init_serial_port(), is_packet_ready(), process_packet(), process_tx_queue(), and send_sport_frame().
char_index
uint8_t AP_Frsky_SPort_Passthrough::char_index
Definition at line 131 of file AP_Frsky_SPort_Passthrough.h.
chunk
uint32_t AP_Frsky_SPort_Passthrough::chunk
Definition at line 129 of file AP_Frsky_SPort_Passthrough.h.
downlink1_sensor_id
uint8_t AP_Frsky_SPort_Passthrough::downlink1_sensor_id = 0x34
Definition at line 141 of file AP_Frsky_SPort_Passthrough.h.
downlink2_sensor_id
uint8_t AP_Frsky_SPort_Passthrough::downlink2_sensor_id = 0x67
Definition at line 142 of file AP_Frsky_SPort_Passthrough.h.
downlink_sensor_id
uint8_t AP_Frsky_SPort_Passthrough::downlink_sensor_id = 0x1B private
Definition at line 135 of file AP_Frsky_SPort_Passthrough.h.
Referenced by is_packet_ready(), is_passthrough_byte(), and setup_wfq_scheduler().
[struct]
struct { ... } AP_Frsky_SPort_Passthrough::external_data
Referenced by get_telem_data(), and send_sport_frame().
mavlite
AP_Frsky_MAVliteMsgHandler AP_Frsky_SPort_Passthrough::mavlite {FUNCTOR_BIND_MEMBER(&AP_Frsky_SPort_Passthrough::send_message, bool, const AP_Frsky_MAVlite_Message &)} private
Definition at line 161 of file AP_Frsky_SPort_Passthrough.h.
Referenced by process_rx_queue().
mavlite_to_sport
AP_Frsky_MAVlite_MAVliteToSPort AP_Frsky_SPort_Passthrough::mavlite_to_sport private
Definition at line 150 of file AP_Frsky_SPort_Passthrough.h.
Referenced by send_message().
packet
sport_packet_t AP_Frsky_SPort_Passthrough::packet
Definition at line 124 of file AP_Frsky_SPort_Passthrough.h.
Referenced by process_rx_queue(), process_tx_queue(), and queue_rx_packet().
pending
bool AP_Frsky_SPort_Passthrough::pending
Definition at line 125 of file AP_Frsky_SPort_Passthrough.h.
repeats
uint8_t AP_Frsky_SPort_Passthrough::repeats
Definition at line 130 of file AP_Frsky_SPort_Passthrough.h.
rx_packet_queue
ObjectBuffer_TS<AP_Frsky_SPort::sport_packet_t> AP_Frsky_SPort_Passthrough::rx_packet_queue {SPORT_PACKET_QUEUE_LENGTH}
Definition at line 144 of file AP_Frsky_SPort_Passthrough.h.
singleton
AP_Frsky_SPort_Passthrough * AP_Frsky_SPort_Passthrough::singleton static private
Definition at line 173 of file AP_Frsky_SPort_Passthrough.h.
Referenced by AP_Frsky_SPort_Passthrough(), and get_singleton().
sport_to_mavlite
AP_Frsky_MAVlite_SPortToMAVlite AP_Frsky_SPort_Passthrough::sport_to_mavlite private
Definition at line 149 of file AP_Frsky_SPort_Passthrough.h.
Referenced by process_rx_queue().
tx_packet_duplicates
uint8_t AP_Frsky_SPort_Passthrough::tx_packet_duplicates
Definition at line 143 of file AP_Frsky_SPort_Passthrough.h.
tx_packet_queue
ObjectBuffer_TS<AP_Frsky_SPort::sport_packet_t> AP_Frsky_SPort_Passthrough::tx_packet_queue {SPORT_PACKET_QUEUE_LENGTH}
Definition at line 145 of file AP_Frsky_SPort_Passthrough.h.
uplink_sensor_id
uint8_t AP_Frsky_SPort_Passthrough::uplink_sensor_id = 0x0D
Definition at line 140 of file AP_Frsky_SPort_Passthrough.h.
The documentation for this class was generated from the following files:
libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.h
libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp