APM:Libraries: AP_Logger_Block Class Reference
AP_Logger_Block Class Reference abstract
#include <AP_Logger_Block.h>
Classes
struct FileHeader
struct PageHeader
Public Member Functions
AP_Logger_Block (AP_Logger &front, LoggerMessageWriter_DFLogStart *writer)
virtual void Init (void) override
virtual bool CardInserted (void) const override=0
void EraseAll () override
uint16_t find_last_log () override
void get_log_boundaries (uint16_t list_entry, uint32_t &start_page, uint32_t &end_page) override
void get_log_info (uint16_t list_entry, uint32_t &size, uint32_t &time_utc) override
int16_t get_log_data (uint16_t list_entry, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data) override WARN_IF_UNUSED
uint16_t get_num_logs () override
void start_new_log (void) override
uint32_t bufferspace_available () override
void stop_logging (void) override
void stop_logging_async (void) override
bool logging_failed () const override
bool logging_started (void) const override
void io_timer (void) override
Public Member Functions inherited from AP_Logger_Backend
FUNCTOR_TYPEDEF (vehicle_startup_message_Writer, void)
AP_Logger_Backend (AP_Logger &front, class LoggerMessageWriter_DFLogStart *writer)
vehicle_startup_message_Writer vehicle_message_writer () const
bool WriteBlock (const void *pBuffer, uint16_t size)
bool WriteCriticalBlock (const void *pBuffer, uint16_t size)
bool WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical, bool writev_streaming=false)
virtual uint16_t find_oldest_log ()
virtual void PrepForArming ()
void Fill_Format (const struct LogStructure *structure, struct log_Format &pkt)
void Fill_Format_Units (const struct LogStructure *s, struct log_Format_Units &pkt)
virtual void flush (void)
virtual void remote_log_block_status_msg (const class GCS_MAVLINK &link, const mavlink_message_t &msg)
virtual void periodic_tasks ()
uint8_t num_types () const
const struct LogStructure * structure (uint8_t structure) const
uint8_t num_units () const
const struct UnitStructure * unit (uint8_t unit) const
uint8_t num_multipliers () const
const struct MultiplierStructure * multiplier (uint8_t multiplier) const
bool Write_EntireMission ()
bool Write_RallyPoint (uint8_t total, uint8_t sequence, const class RallyLocation &rally_point)
bool Write_Rally ()
bool Write_Format (const struct LogStructure *structure)
bool Write_Message (const char *message)
bool Write_MessageF (const char *fmt,...)
bool Write_Mission_Cmd (const AP_Mission &mission, const AP_Mission::Mission_Command &cmd)
bool Write_Mode (uint8_t mode, const ModeReason reason)
bool Write_Parameter (const char *name, float value, float default_val)
bool Write_Parameter (const AP_Param *ap, const AP_Param::ParamToken &token, enum ap_var_type type, float default_val)
bool Write_VER ()
uint32_t num_dropped (void) const
bool Write_Emit_FMT (uint8_t msg_type)
bool Write (uint8_t msg_type, va_list arg_list, bool is_critical=false, bool is_streaming=false)
virtual bool logging_enabled () const
bool allow_start_ekf () const
virtual void vehicle_was_disarmed ()
bool Write_Unit (const struct UnitStructure *s)
bool Write_Multiplier (const struct MultiplierStructure *s)
bool Write_Format_Units (const struct LogStructure *structure)
Protected Member Functions
bool _WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical) override
void periodic_1Hz () override
void periodic_10Hz (const uint32_t now) override
bool WritesOK () const override
uint32_t get_sector (uint32_t current_page) const
uint32_t get_block (uint32_t current_page) const
Protected Member Functions inherited from AP_Logger_Backend
virtual void periodic_fullrate ()
bool ShouldLog (bool is_critical)
virtual bool StartNewLogOK () const
virtual void PrepForArming_start_logging (void)
virtual bool WriteBlockCheckStartupMessages ()
virtual void WriteMoreStartupMessages ()
virtual void push_log_blocks ()
virtual void start_new_log_reset_variables ()
uint16_t log_num_from_list_entry (const uint16_t list_entry)
uint32_t critical_message_reserved_space (uint32_t bufsize) const
uint32_t non_messagewriter_message_reserved_space (uint32_t bufsize) const
void df_stats_gather (uint16_t bytes_written, uint32_t space_remaining)
void df_stats_log ()
void df_stats_clear ()
Protected Attributes
uint32_t df_PageSize
uint16_t df_PagePerBlock
uint16_t df_PagePerSector
uint32_t df_NumPages
volatile bool log_write_started
uint8_t * buffer
uint32_t last_messagewrite_message_sent
uint32_t df_Read_PageAdr
Protected Attributes inherited from AP_Logger_Backend
AP_Logger & _front
LoggerMessageWriter_DFLogStart * _startup_messagewriter
bool _writing_startup_messages
uint16_t _cached_oldest_log
uint32_t _dropped
uint32_t _log_file_size_bytes
bool _rotate_pending
bool _initialised
AP_Logger_RateLimiter * rate_limiter
Private Types
enum class StatusMessage { NONE , ERASE_COMPLETE , RECOVERY_COMPLETE }
Private Member Functions
virtual void BufferToPage (uint32_t PageAdr)=0
virtual void PageToBuffer (uint32_t PageAdr)=0
virtual void SectorErase (uint32_t SectorAdr)=0
virtual void Sector4kErase (uint32_t SectorAdr)=0
virtual void StartErase ()=0
virtual bool InErase ()=0
void flash_test (void)
bool BlockRead (uint16_t IntPageAdr, void *pBuffer, uint16_t size)
bool NeedErase (void)
void validate_log_structure ()
int16_t get_log_data_raw (uint16_t log_num, uint32_t page, uint32_t offset, uint16_t len, uint8_t *data) WARN_IF_UNUSED
uint16_t StartRead (uint32_t PageAdr)
uint16_t ReadHeaders ()
uint32_t find_last_page (void)
uint32_t find_last_page_of_log (uint16_t log_number)
bool is_wrapped (void)
void StartWrite (uint32_t PageAdr)
void FinishWrite (void)
bool ReadBlock (void *pBuffer, uint16_t size)
void StartLogFile (uint16_t FileNumber)
uint16_t GetFileNumber () const
void _print_log_formats (AP_HAL::BetterStream *port)
bool io_thread_alive () const
void write_log_page ()
Private Attributes
HAL_Semaphore sem
HAL_Semaphore write_sem
ByteBuffer writebuf
uint16_t df_Read_BufferIdx
uint32_t df_PageAdr
uint16_t df_FileNumber
uint16_t df_Write_FileNumber
uint32_t df_FileTime
uint32_t df_FilePage
uint32_t df_Write_FilePage
uint32_t df_EraseFrom
bool adding_fmt_headers
volatile bool erase_started
volatile bool new_log_pending
volatile bool stop_log_pending
volatile bool chip_full
volatile uint32_t io_timer_heartbeat
uint8_t warning_decimation_counter
enum AP_Logger_Block::StatusMessage status_msg
Detailed Description
Definition at line 12 of file AP_Logger_Block.h.
Member Enumeration Documentation
StatusMessage
enum class AP_Logger_Block::StatusMessage strong private
Enumerator
NONE
ERASE_COMPLETE
RECOVERY_COMPLETE
Definition at line 125 of file AP_Logger_Block.h.
Constructor & Destructor Documentation
AP_Logger_Block()
AP_Logger_Block::AP_Logger_Block (AP_Logger & front, LoggerMessageWriter_DFLogStart * writer)
Definition at line 22 of file AP_Logger_Block.cpp.
Member Function Documentation
_print_log_formats()
void AP_Logger_Block::_print_log_formats (AP_HAL::BetterStream * port) private
_WritePrioritisedBlock()
bool AP_Logger_Block::_WritePrioritisedBlock (const void * pBuffer, uint16_t size, bool is_critical) override protected virtual
Implements AP_Logger_Backend.
Definition at line 126 of file AP_Logger_Block.cpp.
BlockRead()
bool AP_Logger_Block::BlockRead (uint16_t IntPageAdr, void * pBuffer, uint16_t size) private
Definition at line 808 of file AP_Logger_Block.cpp.
Referenced by NeedErase(), ReadBlock(), and ReadHeaders().
bufferspace_available()
uint32_t AP_Logger_Block::bufferspace_available () override virtual
Implements AP_Logger_Backend.
Definition at line 76 of file AP_Logger_Block.cpp.
BufferToPage()
virtual void AP_Logger_Block::BufferToPage (uint32_t PageAdr) private pure virtual
Implemented in AP_Logger_Flash_JEDEC, and AP_Logger_W25N01GV.
Referenced by FinishWrite(), and flash_test().
CardInserted()
virtual bool AP_Logger_Block::CardInserted (void) const override pure virtual
Implements AP_Logger_Backend.
Implemented in AP_Logger_Flash_JEDEC, and AP_Logger_W25N01GV.
Referenced by get_num_logs(), Init(), io_timer(), and WritesOK().
EraseAll()
void AP_Logger_Block::EraseAll () override virtual
Implements AP_Logger_Backend.
Definition at line 275 of file AP_Logger_Block.cpp.
Referenced by Init().
find_last_log()
uint16_t AP_Logger_Block::find_last_log (void) override virtual
Implements AP_Logger_Backend.
Definition at line 669 of file AP_Logger_Block.cpp.
Referenced by start_new_log().
find_last_page()
uint32_t AP_Logger_Block::find_last_page (void) private
Definition at line 677 of file AP_Logger_Block.cpp.
Referenced by find_last_log(), find_last_page_of_log(), get_num_logs(), and start_new_log().
find_last_page_of_log()
uint32_t AP_Logger_Block::find_last_page_of_log (uint16_t log_number) private
Definition at line 723 of file AP_Logger_Block.cpp.
Referenced by get_log_boundaries(), and validate_log_structure().
FinishWrite()
void AP_Logger_Block::FinishWrite (void) private
Definition at line 89 of file AP_Logger_Block.cpp.
Referenced by io_timer(), and write_log_page().
flash_test()
void AP_Logger_Block::flash_test (void) private
Definition at line 939 of file AP_Logger_Block.cpp.
get_block()
uint32_t AP_Logger_Block::get_block (uint32_t current_page) const inline protected
Definition at line 49 of file AP_Logger_Block.h.
Referenced by FinishWrite(), flash_test(), get_num_logs(), and validate_log_structure().
get_log_boundaries()
void AP_Logger_Block::get_log_boundaries (uint16_t list_entry, uint32_t & start_page, uint32_t & end_page) override virtual
Implements AP_Logger_Backend.
Definition at line 610 of file AP_Logger_Block.cpp.
Referenced by get_log_info().
get_log_data()
int16_t AP_Logger_Block::get_log_data (uint16_t list_entry, uint16_t page, uint32_t offset, uint16_t len, uint8_t * data) override virtual
get data from a log, accounting for adding FMT headers
Implements AP_Logger_Backend.
Definition at line 469 of file AP_Logger_Block.cpp.
get_log_data_raw()
int16_t AP_Logger_Block::get_log_data_raw (uint16_t log_num, uint32_t page, uint32_t offset, uint16_t len, uint8_t * data) private
get raw data from a log - page is the start page of the log, offset is the offset within the log starting at that page
Definition at line 435 of file AP_Logger_Block.cpp.
Referenced by get_log_data().
get_log_info()
void AP_Logger_Block::get_log_info (uint16_t list_entry, uint32_t & size, uint32_t & time_utc) override virtual
Implements AP_Logger_Backend.
Definition at line 778 of file AP_Logger_Block.cpp.
get_num_logs()
uint16_t AP_Logger_Block::get_num_logs (void) override virtual
Implements AP_Logger_Backend.
Definition at line 496 of file AP_Logger_Block.cpp.
Referenced by get_log_boundaries().
get_sector()
uint32_t AP_Logger_Block::get_sector (uint32_t current_page) const inline protected
Definition at line 44 of file AP_Logger_Block.h.
Referenced by EraseAll(), and io_timer().
GetFileNumber()
uint16_t AP_Logger_Block::GetFileNumber () const private
Definition at line 270 of file AP_Logger_Block.cpp.
Referenced by find_last_page(), find_last_page_of_log(), and start_new_log().
InErase()
virtual bool AP_Logger_Block::InErase () private pure virtual
Implemented in AP_Logger_Flash_JEDEC, and AP_Logger_W25N01GV.
Referenced by io_timer(), and periodic_10Hz().
Init()
void AP_Logger_Block::Init (void) override virtual
Implements AP_Logger_Backend.
Reimplemented in AP_Logger_Flash_JEDEC, and AP_Logger_W25N01GV.
Definition at line 31 of file AP_Logger_Block.cpp.
Referenced by AP_Logger_Flash_JEDEC::Init(), and AP_Logger_W25N01GV::Init().
io_thread_alive()
bool AP_Logger_Block::io_thread_alive () const private
Definition at line 831 of file AP_Logger_Block.cpp.
Referenced by logging_failed(), and periodic_1Hz().
io_timer()
void AP_Logger_Block::io_timer (void) override virtual
Reimplemented from AP_Logger_Backend.
Definition at line 844 of file AP_Logger_Block.cpp.
is_wrapped()
bool AP_Logger_Block::is_wrapped (void) private
Definition at line 662 of file AP_Logger_Block.cpp.
Referenced by find_last_page_of_log(), get_log_boundaries(), get_num_logs(), and validate_log_structure().
logging_failed()
bool AP_Logger_Block::logging_failed () const override virtual
Implements AP_Logger_Backend.
Definition at line 814 of file AP_Logger_Block.cpp.
logging_started()
bool AP_Logger_Block::logging_started (void) const inline override virtual
Implements AP_Logger_Backend.
Definition at line 33 of file AP_Logger_Block.h.
Referenced by start_new_log().
NeedErase()
bool AP_Logger_Block::NeedErase (void) private
Definition at line 372 of file AP_Logger_Block.cpp.
Referenced by Init().
PageToBuffer()
virtual void AP_Logger_Block::PageToBuffer (uint32_t PageAdr) private pure virtual
Implemented in AP_Logger_Flash_JEDEC, and AP_Logger_W25N01GV.
Referenced by flash_test(), NeedErase(), ReadBlock(), and StartRead().
periodic_10Hz()
void AP_Logger_Block::periodic_10Hz (const uint32_t now) override protected virtual
Reimplemented from AP_Logger_Backend.
Definition at line 343 of file AP_Logger_Block.cpp.
periodic_1Hz()
void AP_Logger_Block::periodic_1Hz () override protected virtual
Reimplemented from AP_Logger_Backend.
Definition at line 308 of file AP_Logger_Block.cpp.
ReadBlock()
bool AP_Logger_Block::ReadBlock (void * pBuffer, uint16_t size) private
Definition at line 223 of file AP_Logger_Block.cpp.
Referenced by get_log_data_raw().
ReadHeaders()
uint16_t AP_Logger_Block::ReadHeaders () private
Definition at line 199 of file AP_Logger_Block.cpp.
Referenced by ReadBlock(), and StartRead().
Sector4kErase()
virtual void AP_Logger_Block::Sector4kErase (uint32_t SectorAdr) private pure virtual
Implemented in AP_Logger_Flash_JEDEC, and AP_Logger_W25N01GV.
Referenced by EraseAll(), and io_timer().
SectorErase()
virtual void AP_Logger_Block::SectorErase (uint32_t SectorAdr) private pure virtual
Implemented in AP_Logger_Flash_JEDEC, and AP_Logger_W25N01GV.
Referenced by FinishWrite(), flash_test(), and io_timer().
start_new_log()
void AP_Logger_Block::start_new_log (void) override virtual
Reimplemented from AP_Logger_Backend.
Definition at line 553 of file AP_Logger_Block.cpp.
Referenced by periodic_10Hz().
StartErase()
virtual void AP_Logger_Block::StartErase () private pure virtual
Implemented in AP_Logger_Flash_JEDEC, and AP_Logger_W25N01GV.
Referenced by EraseAll().
StartLogFile()
void AP_Logger_Block::StartLogFile (uint16_t FileNumber) private
Definition at line 262 of file AP_Logger_Block.cpp.
Referenced by start_new_log().
StartRead()
uint16_t AP_Logger_Block::StartRead (uint32_t PageAdr) private
Definition at line 186 of file AP_Logger_Block.cpp.
Referenced by find_last_log(), find_last_page(), find_last_page_of_log(), FinishWrite(), get_log_boundaries(), get_log_data_raw(), get_log_info(), get_num_logs(), is_wrapped(), NeedErase(), start_new_log(), and validate_log_structure().
StartWrite()
void AP_Logger_Block::StartWrite (uint32_t PageAdr) private
Definition at line 84 of file AP_Logger_Block.cpp.
Referenced by io_timer(), and start_new_log().
stop_logging()
void AP_Logger_Block::stop_logging (void) override virtual
Implements AP_Logger_Backend.
Definition at line 534 of file AP_Logger_Block.cpp.
Referenced by start_new_log().
stop_logging_async()
void AP_Logger_Block::stop_logging_async (void) override virtual
Reimplemented from AP_Logger_Backend.
Definition at line 545 of file AP_Logger_Block.cpp.
validate_log_structure()
void AP_Logger_Block::validate_log_structure () private
Definition at line 388 of file AP_Logger_Block.cpp.
Referenced by Init().
write_log_page()
void AP_Logger_Block::write_log_page () private
Definition at line 921 of file AP_Logger_Block.cpp.
Referenced by io_timer().
WritesOK()
bool AP_Logger_Block::WritesOK () const override protected virtual
Implements AP_Logger_Backend.
Definition at line 118 of file AP_Logger_Block.cpp.
Referenced by _WritePrioritisedBlock().
Member Data Documentation
adding_fmt_headers
bool AP_Logger_Block::adding_fmt_headers private
Definition at line 111 of file AP_Logger_Block.h.
buffer
uint8_t* AP_Logger_Block::buffer protected
Definition at line 63 of file AP_Logger_Block.h.
Referenced by BlockRead(), AP_Logger_Flash_JEDEC::BufferToPage(), AP_Logger_W25N01GV::BufferToPage(), flash_test(), Init(), io_timer(), AP_Logger_Flash_JEDEC::PageToBuffer(), AP_Logger_W25N01GV::PageToBuffer(), ReadBlock(), StartRead(), and write_log_page().
chip_full
volatile bool AP_Logger_Block::chip_full private
Definition at line 120 of file AP_Logger_Block.h.
Referenced by FinishWrite(), io_timer(), logging_failed(), and periodic_1Hz().
df_EraseFrom
uint32_t AP_Logger_Block::df_EraseFrom private
Definition at line 108 of file AP_Logger_Block.h.
Referenced by io_timer(), and validate_log_structure().
df_FileNumber
uint16_t AP_Logger_Block::df_FileNumber private
Definition at line 101 of file AP_Logger_Block.h.
Referenced by get_log_info(), GetFileNumber(), ReadHeaders(), and StartLogFile().
df_FilePage
uint32_t AP_Logger_Block::df_FilePage private
Definition at line 105 of file AP_Logger_Block.h.
Referenced by find_last_page(), find_last_page_of_log(), get_log_boundaries(), get_num_logs(), ReadHeaders(), start_new_log(), and StartLogFile().
df_FileTime
uint32_t AP_Logger_Block::df_FileTime private
Definition at line 103 of file AP_Logger_Block.h.
Referenced by get_log_info(), and ReadHeaders().
df_NumPages
uint32_t AP_Logger_Block::df_NumPages protected
Definition at line 60 of file AP_Logger_Block.h.
Referenced by bufferspace_available(), AP_Logger_Flash_JEDEC::BufferToPage(), AP_Logger_W25N01GV::BufferToPage(), AP_Logger_Flash_JEDEC::CardInserted(), AP_Logger_W25N01GV::CardInserted(), EraseAll(), find_last_page(), find_last_page_of_log(), FinishWrite(), get_log_boundaries(), get_log_data_raw(), get_log_info(), AP_Logger_Flash_JEDEC::getSectorCount(), AP_Logger_W25N01GV::getSectorCount(), Init(), io_timer(), is_wrapped(), NeedErase(), AP_Logger_Flash_JEDEC::PageToBuffer(), AP_Logger_W25N01GV::PageToBuffer(), ReadBlock(), and validate_log_structure().
df_PageAdr
uint32_t AP_Logger_Block::df_PageAdr private
Definition at line 99 of file AP_Logger_Block.h.
Referenced by FinishWrite(), and StartWrite().
df_PagePerBlock
uint16_t AP_Logger_Block::df_PagePerBlock protected
Definition at line 56 of file AP_Logger_Block.h.
Referenced by FinishWrite(), flash_test(), get_block(), get_num_logs(), AP_Logger_Flash_JEDEC::getSectorCount(), AP_Logger_W25N01GV::getSectorCount(), Init(), io_timer(), AP_Logger_Flash_JEDEC::SectorErase(), AP_Logger_W25N01GV::SectorErase(), and validate_log_structure().
df_PagePerSector
uint16_t AP_Logger_Block::df_PagePerSector protected
Definition at line 58 of file AP_Logger_Block.h.
Referenced by get_sector(), AP_Logger_Flash_JEDEC::getSectorCount(), AP_Logger_W25N01GV::getSectorCount(), io_timer(), and AP_Logger_Flash_JEDEC::Sector4kErase().
df_PageSize
uint32_t AP_Logger_Block::df_PageSize protected
Definition at line 54 of file AP_Logger_Block.h.
Referenced by bufferspace_available(), AP_Logger_Flash_JEDEC::BufferToPage(), AP_Logger_W25N01GV::BufferToPage(), flash_test(), get_log_data_raw(), get_log_info(), AP_Logger_Flash_JEDEC::getSectorCount(), AP_Logger_W25N01GV::getSectorCount(), Init(), io_timer(), AP_Logger_Flash_JEDEC::PageToBuffer(), AP_Logger_W25N01GV::PageToBuffer(), ReadBlock(), AP_Logger_Flash_JEDEC::Sector4kErase(), AP_Logger_Flash_JEDEC::SectorErase(), StartRead(), and write_log_page().
df_Read_BufferIdx
uint16_t AP_Logger_Block::df_Read_BufferIdx private
Definition at line 98 of file AP_Logger_Block.h.
Referenced by get_log_data_raw(), ReadBlock(), and ReadHeaders().
df_Read_PageAdr
uint32_t AP_Logger_Block::df_Read_PageAdr protected
Definition at line 65 of file AP_Logger_Block.h.
Referenced by AP_Logger_Flash_JEDEC::BufferToPage(), AP_Logger_W25N01GV::BufferToPage(), AP_Logger_Flash_JEDEC::PageToBuffer(), AP_Logger_W25N01GV::PageToBuffer(), ReadBlock(), ReadHeaders(), and StartRead().
df_Write_FileNumber
uint16_t AP_Logger_Block::df_Write_FileNumber private
Definition at line 102 of file AP_Logger_Block.h.
Referenced by get_log_info(), StartLogFile(), and write_log_page().
df_Write_FilePage
uint32_t AP_Logger_Block::df_Write_FilePage private
Definition at line 106 of file AP_Logger_Block.h.
Referenced by FinishWrite(), StartLogFile(), and write_log_page().
erase_started
volatile bool AP_Logger_Block::erase_started private
Definition at line 114 of file AP_Logger_Block.h.
Referenced by EraseAll(), io_timer(), periodic_10Hz(), ReadBlock(), start_new_log(), StartRead(), and WritesOK().
io_timer_heartbeat
volatile uint32_t AP_Logger_Block::io_timer_heartbeat private
Definition at line 122 of file AP_Logger_Block.h.
Referenced by io_thread_alive(), and io_timer().
last_messagewrite_message_sent
uint32_t AP_Logger_Block::last_messagewrite_message_sent protected
Definition at line 64 of file AP_Logger_Block.h.
Referenced by _WritePrioritisedBlock().
log_write_started
volatile bool AP_Logger_Block::log_write_started protected
Definition at line 61 of file AP_Logger_Block.h.
Referenced by EraseAll(), io_timer(), logging_started(), start_new_log(), and stop_logging().
new_log_pending
volatile bool AP_Logger_Block::new_log_pending private
Definition at line 116 of file AP_Logger_Block.h.
Referenced by EraseAll(), io_timer(), periodic_10Hz(), and start_new_log().
sem
HAL_Semaphore AP_Logger_Block::sem private
Definition at line 92 of file AP_Logger_Block.h.
Referenced by EraseAll(), find_last_log(), find_last_page(), find_last_page_of_log(), get_log_boundaries(), get_log_data(), get_log_data_raw(), get_log_info(), get_num_logs(), Init(), io_timer(), start_new_log(), stop_logging(), and validate_log_structure().
status_msg
enum AP_Logger_Block::StatusMessage AP_Logger_Block::status_msg private
Referenced by io_timer(), and periodic_10Hz().
stop_log_pending
volatile bool AP_Logger_Block::stop_log_pending private
Definition at line 118 of file AP_Logger_Block.h.
Referenced by io_timer(), and stop_logging_async().
warning_decimation_counter
uint8_t AP_Logger_Block::warning_decimation_counter private
Definition at line 123 of file AP_Logger_Block.h.
Referenced by periodic_1Hz().
write_sem
HAL_Semaphore AP_Logger_Block::write_sem private
Definition at line 94 of file AP_Logger_Block.h.
Referenced by _WritePrioritisedBlock().
writebuf
ByteBuffer AP_Logger_Block::writebuf private
Definition at line 95 of file AP_Logger_Block.h.
Referenced by _WritePrioritisedBlock(), EraseAll(), Init(), io_timer(), start_new_log(), stop_logging(), and write_log_page().
The documentation for this class was generated from the following files:
libraries/AP_Logger/AP_Logger_Block.h
libraries/AP_Logger/AP_Logger_Block.cpp