APM:Libraries: AP_AHRS Class Reference
AP_AHRS Class Reference
#include <AP_AHRS.h>
Public Types
enum Flags { FLAG_ALWAYS_USE_EKF = 0x1 }
enum AirspeedEstimateType : uint8_t {
NO_NEW_ESTIMATE = 0 , AIRSPEED_SENSOR = 1 , DCM_SYNTHETIC = 2 , EKF3_SYNTHETIC = 3 ,
SIM = 4
}
enum class EKFType : uint8_t
enum class LogOriginType { ekf_origin = 0 , ahrs_home = 1 }
enum class VehicleClass : uint8_t {
UNKNOWN , GROUND , COPTER , FIXED_WING ,
SUBMARINE
}
Public Member Functions
AP_AHRS (uint8_t flags=0)
void init (void)
CLASS_NO_COPY (AP_AHRS)
void update_orientation ()
HAL_Semaphore & get_semaphore (void)
const Vector3f & get_gyro (void) const
const Vector3f & get_gyro_drift (void) const
void reset_gyro_drift ()
void update (bool skip_ins_update=false)
void reset ()
bool get_location (Location &loc) const
bool get_hagl (float &hagl) const WARN_IF_UNUSED
float get_error_rp () const
float get_error_yaw () const
void set_wind_estimation_enabled (bool b)
bool get_wind_estimation_enabled () const
const Vector3f & wind_estimate () const
bool wind_estimate (Vector3f &wind) const
float wind_alignment (const float heading_deg) const
float head_wind (void) const
void estimate_wind ()
uint8_t get_max_wind () const
float get_EAS2TAS (void) const
bool airspeed_estimate (float &airspeed_ret) const
bool airspeed_estimate (float &airspeed_ret, AirspeedEstimateType &type) const
bool using_airspeed_sensor () const
bool airspeed_estimate_true (float &airspeed_ret) const
bool airspeed_vector_true (Vector3f &vec) const
bool airspeed_health_data (float &innovation, float &innovationVariance, uint32_t &age_ms) const
bool airspeed_sensor_enabled (void) const
bool airspeed_sensor_enabled (uint8_t airspeed_index) const
bool synthetic_airspeed (float &ret) const WARN_IF_UNUSED
bool use_compass ()
bool get_quaternion (Quaternion &quat) const WARN_IF_UNUSED
bool get_secondary_attitude (Vector3f &eulers) const
bool get_secondary_quaternion (Quaternion &quat) const
bool get_secondary_position (Location &loc) const
const Vector2f & groundspeed_vector () const
float groundspeed (void) const
const Vector3f & get_accel_ef () const
void getCorrectedDeltaVelocityNED (Vector3f &ret, float &dt) const
bool set_origin (const Location &loc) WARN_IF_UNUSED
bool get_origin (Location &ret) const WARN_IF_UNUSED
bool have_inertial_nav () const
bool get_velocity_NED (Vector3f &vec) const WARN_IF_UNUSED
bool get_relative_position_NED_home (Vector3f &vec) const WARN_IF_UNUSED
bool get_relative_position_NED_origin (Vector3f &vec) const WARN_IF_UNUSED
bool get_relative_position_NE_home (Vector2f &posNE) const WARN_IF_UNUSED
bool get_relative_position_NE_origin (Vector2f &posNE) const WARN_IF_UNUSED
void get_relative_position_D_home (float &posD) const
bool get_relative_position_D_origin (float &posD) const WARN_IF_UNUSED
bool get_location_from_origin_offset (Location &loc, const Vector3p &offset_ned) const WARN_IF_UNUSED
bool get_location_from_home_offset (Location &loc, const Vector3p &offset_ned) const WARN_IF_UNUSED
bool get_vert_pos_rate_D (float &velocity) const
void writeOptFlowMeas (const uint8_t rawFlowQuality, const Vector2f &rawFlowRates, const Vector2f &rawGyroRates, const uint32_t msecFlowMeas, const Vector3f &posOffset, const float heightOverride)
bool getOptFlowSample (uint32_t &timeStamp_ms, Vector2f &flowRate, Vector2f &bodyRate, Vector2f &losPred) const
void writeBodyFrameOdom (float quality, const Vector3f &delPos, const Vector3f &delAng, float delTime, uint32_t timeStamp_ms, uint16_t delay_ms, const Vector3f &posOffset)
void writeDefaultAirSpeed (float airspeed, float uncertainty)
void writeExtNavData (const Vector3f &pos, const Quaternion &quat, float posErr, float angErr, uint32_t timeStamp_ms, uint16_t delay_ms, uint32_t resetTime_ms)
void writeExtNavVelData (const Vector3f &vel, float err, uint32_t timeStamp_ms, uint16_t delay_ms)
void getControlLimits (float &ekfGndSpdLimit, float &controlScaleXY) const
float getControlScaleZ (void) const
bool healthy () const
bool pre_arm_check (bool requires_position, char *failure_msg, uint8_t failure_msg_len) const
bool initialised () const
bool get_filter_status (nav_filter_status &status) const
bool getMagOffsets (uint8_t mag_idx, Vector3f &magOffsets) const
uint32_t getLastYawResetAngle (float &yawAng)
uint32_t getLastPosNorthEastReset (Vector2f &pos)
uint32_t getLastVelNorthEastReset (Vector2f &vel) const
uint32_t getLastPosDownReset (float &posDelta)
bool resetHeightDatum ()
void send_ekf_status_report (class GCS_MAVLINK &link) const
bool get_hgt_ctrl_limit (float &limit) const
void set_terrain_hgt_stable (bool stable)
bool get_innovations (Vector3f &velInnov, Vector3f &posInnov, Vector3f &magInnov, float &tasInnov, float &yawInnov) const
bool is_vibration_affected () const
bool get_variances (float &velVar, float &posVar, float &hgtVar, Vector3f &magVar, float &tasVar) const
bool get_vel_innovations_and_variances_for_source (uint8_t source, Vector3f &innovations, Vector3f &variances) const WARN_IF_UNUSED
bool get_mag_field_NED (Vector3f &ret) const
bool get_mag_field_correction (Vector3f &ret) const
uint8_t get_active_airspeed_index () const
int8_t get_primary_core_index () const
uint8_t get_primary_accel_index (void) const
uint8_t get_primary_gyro_index (void) const
void check_lane_switch (void)
void request_yaw_reset (void)
void set_posvelyaw_source_set (uint8_t source_set_idx)
uint8_t get_posvelyaw_source_set () const
void Log_Write ()
bool using_noncompass_for_yaw (void) const
bool using_extnav_for_yaw (void) const
void set_alt_measurement_noise (float noise)
int8_t get_ekf_type (void) const
void set_ekf_type (EKFType ahrs_type)
AP_AHRS_View * create_view (enum Rotation rotation, float pitch_trim_deg=0)
void Write_AOA_SSA (void) const
float getAOA (void) const
float getSSA (void) const
const Vector3f & get_trim () const
void set_trim (const Vector3f &new_trim)
void add_trim (float roll_in_radians, float pitch_in_radians, bool save_to_eeprom=true)
const Matrix3f & get_rotation_autopilot_body_to_vehicle_body (void) const
const Matrix3f & get_rotation_vehicle_body_to_autopilot_body (void) const
void Log_Write_Home_And_Origin ()
void Write_Attitude (const Vector3f &targets) const
void Write_Origin (LogOriginType origin_type, const Location &loc) const
void write_video_stabilisation () const
Vector3f get_gyro_latest (void) const
float get_yaw_rate_earth (void) const
const Location & get_home (void) const
void lock_home ()
bool home_is_locked () const
bool home_is_set (void) const
bool set_home (const Location &loc) WARN_IF_UNUSED
float get_roll () const
float get_pitch () const
float get_yaw () const
float cos_roll () const
float cos_pitch () const
float cos_yaw () const
float sin_roll () const
float sin_pitch () const
float sin_yaw () const
const Matrix3f & get_rotation_body_to_ned (void) const
void get_quat_body_to_ned (Quaternion &quat) const
Vector2f earth_to_body2D (const Vector2f &ef_vector) const
Vector2f body_to_earth2D (const Vector2f &bf) const
Vector3f body_to_earth (const Vector3f &v) const
Vector3f earth_to_body (const Vector3f &v) const
Vector3f get_vibration (void) const
const Vector3f & get_accel (void) const
const Vector3f & get_accel_bias (void) const
void set_takeoff_expected (bool b)
bool get_takeoff_expected (void) const
void set_touchdown_expected (bool b)
bool get_touchdown_expected (void) const
void set_fly_forward (bool b)
bool get_fly_forward (void) const
VehicleClass get_vehicle_class (void) const
void set_vehicle_class (VehicleClass vclass)
AP_AHRS_View * get_view (void) const
const EKFGSF_yaw * get_yaw_estimator (void) const
Static Public Member Functions
static AP_AHRS * get_singleton ()
Public Attributes
int32_t roll_sensor
int32_t pitch_sensor
int32_t yaw_sensor
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
enum class TriState { False = 0 , True = 1 , UNKNOWN = 3 }
enum class Options : uint16_t { DISABLE_DCM_FALLBACK_FW =(1U<<0) , DISABLE_DCM_FALLBACK_VTOL =(1U<<1) }
Private Member Functions
EKFType active_EKF_type (void) const
bool always_use_EKF () const
bool attitudes_consistent (char *failure_msg, const uint8_t failure_msg_len) const
void set_failure_inconsistent_message (const char *estimator, const char *axis, float diff_rad, char *failure_msg, const uint8_t failure_msg_len) const
void calc_trig (const Matrix3f &rot, float &cr, float &cp, float &cy, float &sr, float &sp, float &sy) const
void update_trig (void)
void update_cd_values (void)
EKFType ekf_type (void) const
void update_DCM ()
void load_watchdog_home ()
void update_AOA_SSA (void)
void update_trim_rotation_matrices ()
void update_flags ()
void update_notify_from_filter_status (const nav_filter_status &status)
void copy_estimates_from_backend_estimates (const AP_AHRS_Backend::Estimates &results)
void Write_AHRS2 (void) const
void Write_POS (void) const
bool _airspeed_estimate (float &airspeed_ret, AirspeedEstimateType &status) const
bool _get_secondary_attitude (Vector3f &eulers) const
bool _get_secondary_quaternion (Quaternion &quat) const
Vector2f _groundspeed_vector (void)
EKFType _active_EKF_type (void) const
bool _wind_estimate (Vector3f &wind) const WARN_IF_UNUSED
bool _airspeed_estimate_true (float &airspeed_ret) const
bool _airspeed_vector_true (Vector3f &vec) const
bool _get_quaternion (Quaternion &quat) const WARN_IF_UNUSED
bool _get_secondary_position (Location &loc) const
float _groundspeed (void)
void _getCorrectedDeltaVelocityNED (Vector3f &ret, float &dt) const
bool _get_origin (Location &ret) const WARN_IF_UNUSED
bool _get_origin (EKFType type, Location &ret) const
bool _get_velocity_NED (Vector3f &vec) const WARN_IF_UNUSED
bool _get_secondary_EKF_type (EKFType &secondary_ekf_type) const
int8_t _get_primary_core_index () const
uint8_t _get_primary_accel_index (void) const
uint8_t _get_primary_gyro_index (void) const
uint8_t _get_primary_IMU_index (void) const
bool _get_location (Location &loc) const
bool _should_use_airspeed_sensor (uint8_t airspeed_index) const
void update_state (void)
EKFType fallback_active_EKF_type (void) const
bool option_set (Options option) const
Private Attributes
float roll
float pitch
float yaw
AP_AHRS_View * _view
VehicleClass _vehicle_class {VehicleClass::UNKNOWN}
HAL_Semaphore _rsem
AP_Int8 _wind_max
AP_Int8 _board_orientation
AP_Enum< EKFType > _ekf_type
AP_Float _kp_yaw
AP_Float _kp
AP_Float gps_gain
AP_Float beta
AP_Enum< GPSUse > _gps_use
AP_Int8 _gps_minsats
float _cos_roll {1.0f}
float _cos_pitch {1.0f}
float _cos_yaw {1.0f}
float _sin_roll
float _sin_pitch
float _sin_yaw
const uint16_t startup_delay_ms = 1000
uint32_t start_time_ms
uint8_t _ekf_flags
bool _checked_watchdog_home
Location _home
bool _home_is_set:1
bool _home_locked:1
TriState terrainHgtStableState = TriState::UNKNOWN
float _AOA
float _SSA
uint32_t _last_AOA_update_ms
EKFType last_active_ekf_type
AP_Vector3f _trim
Vector3f _last_trim
Matrix3f _rotation_autopilot_body_to_vehicle_body
Matrix3f _rotation_vehicle_body_to_autopilot_body
uint32_t last_orientation_update_ms
bool takeoff_expected
uint32_t takeoff_expected_start_ms
bool touchdown_expected
uint32_t touchdown_expected_start_ms
bool wind_estimation_enabled
bool fly_forward
struct {
EKFType active_EKF
uint8_t primary_IMU
uint8_t primary_gyro
uint8_t primary_accel
uint8_t primary_core
Vector3f gyro_estimate
Matrix3f dcm_matrix
Vector3f gyro_drift
Vector3f accel_ef
Vector3f accel_bias
Vector3f wind_estimate
bool wind_estimate_ok
float EAS2TAS
bool airspeed_ok
float airspeed
AirspeedEstimateType airspeed_estimate_type
bool airspeed_true_ok
float airspeed_true
Vector3f airspeed_vec
bool airspeed_vec_ok
Quaternion quat
bool quat_ok
Vector3f secondary_attitude
bool secondary_attitude_ok
Quaternion secondary_quat
bool secondary_quat_ok
Location location
bool location_ok
Location secondary_pos
bool secondary_pos_ok
Vector2f ground_speed_vec
float ground_speed
Vector3f corrected_dv
float corrected_dv_dt
Location origin
bool origin_ok
Vector3f velocity_NED
bool velocity_NED_ok
} state
AP_Int16 _options
Static Private Attributes
static AP_AHRS * _singleton
Friends
class AP_AHRS_View
Detailed Description
Definition at line 46 of file AP_AHRS.h.
Member Enumeration Documentation
AirspeedEstimateType
enum AP_AHRS::AirspeedEstimateType : uint8_t
Enumerator
NO_NEW_ESTIMATE
AIRSPEED_SENSOR
DCM_SYNTHETIC
EKF3_SYNTHETIC
SIM
Definition at line 152 of file AP_AHRS.h.
EKFType
enum class AP_AHRS::EKFType : uint8_t strong
Definition at line 434 of file AP_AHRS.h.
Flags
enum AP_AHRS::Flags
Enumerator
FLAG_ALWAYS_USE_EKF
Definition at line 50 of file AP_AHRS.h.
LogOriginType
enum class AP_AHRS::LogOriginType strong
Enumerator
ekf_origin
ahrs_home
Definition at line 501 of file AP_AHRS.h.
Options
enum class AP_AHRS::Options : uint16_t strong private
Enumerator
DISABLE_DCM_FALLBACK_FW
DISABLE_DCM_FALLBACK_VTOL
Definition at line 1011 of file AP_AHRS.h.
TriState
enum class AP_AHRS::TriState strong private
Enumerator
False
True
UNKNOWN
Definition at line 783 of file AP_AHRS.h.
VehicleClass
enum class AP_AHRS::VehicleClass : uint8_t strong
Enumerator
UNKNOWN
GROUND
COPTER
FIXED_WING
SUBMARINE
Definition at line 659 of file AP_AHRS.h.
Constructor & Destructor Documentation
AP_AHRS()
AP_AHRS::AP_AHRS (uint8_t flags = 0)
Definition at line 202 of file AP_AHRS.cpp.
Member Function Documentation
_active_EKF_type()
AP_AHRS::EKFType AP_AHRS::_active_EKF_type (void) const private
Definition at line 1877 of file AP_AHRS.cpp.
Referenced by update().
_airspeed_estimate()
bool AP_AHRS::_airspeed_estimate (float & airspeed_ret, AirspeedEstimateType & status) const private
Definition at line 885 of file AP_AHRS.cpp.
Referenced by update_state().
_airspeed_estimate_true()
bool AP_AHRS::_airspeed_estimate_true (float & airspeed_ret) const private
Definition at line 987 of file AP_AHRS.cpp.
Referenced by update_state().
_airspeed_vector_true()
bool AP_AHRS::_airspeed_vector_true (Vector3f & vec) const private
Definition at line 1018 of file AP_AHRS.cpp.
Referenced by update_state().
_get_location()
bool AP_AHRS::_get_location (Location & loc) const private
Definition at line 733 of file AP_AHRS.cpp.
Referenced by update_state().
_get_origin() [1/2]
bool AP_AHRS::_get_origin (EKFType type, Location & ret) const private
Definition at line 2836 of file AP_AHRS.cpp.
_get_origin() [2/2]
bool AP_AHRS::_get_origin (Location & ret) const private
Definition at line 2874 of file AP_AHRS.cpp.
Referenced by _get_origin(), get_relative_position_D_home(), and update_state().
_get_primary_accel_index()
uint8_t AP_AHRS::_get_primary_accel_index (void) const private
Definition at line 3251 of file AP_AHRS.cpp.
Referenced by update_state().
_get_primary_core_index()
int8_t AP_AHRS::_get_primary_core_index () const private
Definition at line 3215 of file AP_AHRS.cpp.
Referenced by update_state().
_get_primary_gyro_index()
uint8_t AP_AHRS::_get_primary_gyro_index (void) const private
Definition at line 3257 of file AP_AHRS.cpp.
Referenced by update_state().
_get_primary_IMU_index()
uint8_t AP_AHRS::_get_primary_IMU_index (void) const private
Definition at line 3179 of file AP_AHRS.cpp.
Referenced by _get_primary_accel_index(), _get_primary_gyro_index(), and update_state().
_get_quaternion()
bool AP_AHRS::_get_quaternion (Quaternion & quat) const private
Definition at line 1127 of file AP_AHRS.cpp.
Referenced by update_state().
_get_secondary_attitude()
bool AP_AHRS::_get_secondary_attitude (Vector3f & eulers) const private
Definition at line 1175 of file AP_AHRS.cpp.
Referenced by update_state().
_get_secondary_EKF_type()
bool AP_AHRS::_get_secondary_EKF_type (EKFType & secondary_ekf_type) const private
Definition at line 2077 of file AP_AHRS.cpp.
Referenced by _get_secondary_attitude(), _get_secondary_position(), and _get_secondary_quaternion().
_get_secondary_position()
bool AP_AHRS::_get_secondary_position (Location & loc) const private
Definition at line 1287 of file AP_AHRS.cpp.
Referenced by update_state().
_get_secondary_quaternion()
bool AP_AHRS::_get_secondary_quaternion (Quaternion & quat) const private
Definition at line 1230 of file AP_AHRS.cpp.
Referenced by update_state().
_get_velocity_NED()
bool AP_AHRS::_get_velocity_NED (Vector3f & vec) const private
Definition at line 1469 of file AP_AHRS.cpp.
Referenced by update_state().
_getCorrectedDeltaVelocityNED()
void AP_AHRS::_getCorrectedDeltaVelocityNED (Vector3f & ret, float & dt) const private
Definition at line 2472 of file AP_AHRS.cpp.
Referenced by update_state().
_groundspeed()
float AP_AHRS::_groundspeed (void) private
Definition at line 1375 of file AP_AHRS.cpp.
Referenced by update_state().
_groundspeed_vector()
Vector2f AP_AHRS::_groundspeed_vector (void) private
Definition at line 1338 of file AP_AHRS.cpp.
Referenced by update_state().
_should_use_airspeed_sensor()
bool AP_AHRS::_should_use_airspeed_sensor (uint8_t airspeed_index) const private
Definition at line 864 of file AP_AHRS.cpp.
Referenced by _airspeed_estimate().
_wind_estimate()
bool AP_AHRS::_wind_estimate (Vector3f & wind) const private
Definition at line 795 of file AP_AHRS.cpp.
Referenced by update_state().
active_EKF_type()
EKFType AP_AHRS::active_EKF_type (void) const inline private
Definition at line 720 of file AP_AHRS.h.
Referenced by _airspeed_estimate(), _airspeed_estimate_true(), _airspeed_vector_true(), _get_location(), _get_origin(), _get_primary_core_index(), _get_primary_IMU_index(), _get_quaternion(), _get_secondary_EKF_type(), _get_velocity_NED(), _getCorrectedDeltaVelocityNED(), _groundspeed(), _groundspeed_vector(), _wind_estimate(), airspeed_health_data(), attitudes_consistent(), check_lane_switch(), get_active_airspeed_index(), get_hagl(), get_hgt_ctrl_limit(), get_mag_field_correction(), get_mag_field_NED(), get_relative_position_D_origin(), get_relative_position_NE_origin(), get_relative_position_NED_origin(), get_vert_pos_rate_D(), get_yaw_estimator(), getControlLimits(), getControlScaleZ(), getLastPosDownReset(), getLastPosNorthEastReset(), getLastVelNorthEastReset(), getLastYawResetAngle(), have_inertial_nav(), healthy(), pre_arm_check(), request_yaw_reset(), set_origin(), use_compass(), using_extnav_for_yaw(), and using_noncompass_for_yaw().
add_trim()
void AP_AHRS::add_trim (float roll_in_radians, float pitch_in_radians, bool save_to_eeprom = true)
Definition at line 53 of file AP_AHRS_Backend.cpp.
airspeed_estimate() [1/2]
bool AP_AHRS::airspeed_estimate (float & airspeed_ret) const
Definition at line 3475 of file AP_AHRS.cpp.
Referenced by _airspeed_estimate_true(), AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_TECS::_update_speed(), AP_AHRS_View::airspeed_estimate(), AP_YawController::get_rate_out(), AP_YawController::get_servo_out(), and Variometer::update().
airspeed_estimate() [2/2]
bool AP_AHRS::airspeed_estimate (float & airspeed_ret, AP_AHRS::AirspeedEstimateType & type) const
Definition at line 3483 of file AP_AHRS.cpp.
airspeed_estimate_true()
bool AP_AHRS::airspeed_estimate_true (float & airspeed_ret) const
Definition at line 3492 of file AP_AHRS.cpp.
Referenced by AP_AHRS_View::airspeed_estimate_true(), and AP_Frsky_SPort_Passthrough::calc_velandyaw().
airspeed_health_data()
bool AP_AHRS::airspeed_health_data (float & innovation, float & innovationVariance, uint32_t & age_ms) const
Definition at line 1050 of file AP_AHRS.cpp.
airspeed_sensor_enabled() [1/2]
bool AP_AHRS::airspeed_sensor_enabled (uint8_t airspeed_index) const inline
Definition at line 186 of file AP_AHRS.h.
airspeed_sensor_enabled() [2/2]
bool AP_AHRS::airspeed_sensor_enabled (void) const inline
Definition at line 180 of file AP_AHRS.h.
Referenced by _should_use_airspeed_sensor(), and GCS::update_sensor_status_flags().
airspeed_vector_true()
bool AP_AHRS::airspeed_vector_true (Vector3f & vec) const
Definition at line 3500 of file AP_AHRS.cpp.
always_use_EKF()
bool AP_AHRS::always_use_EKF () const inline private
Definition at line 722 of file AP_AHRS.h.
Referenced by _active_EKF_type(), _get_location(), attitudes_consistent(), and ekf_type().
attitudes_consistent()
bool AP_AHRS::attitudes_consistent (char * failure_msg, const uint8_t failure_msg_len) const private
Definition at line 2519 of file AP_AHRS.cpp.
Referenced by pre_arm_check().
body_to_earth()
Vector3f AP_AHRS::body_to_earth (const Vector3f & v) const
Definition at line 301 of file AP_AHRS.cpp.
body_to_earth2D()
Vector2f AP_AHRS::body_to_earth2D (const Vector2f & bf) const
Definition at line 241 of file AP_AHRS_Backend.cpp.
Referenced by AC_Avoid::adjust_velocity_proximity(), and AR_PosControl::update().
calc_trig()
void AP_AHRS::calc_trig (const Matrix3f & rot, float & cr, float & cp, float & cy, float & sr, float & sp, float & sy) const private
Definition at line 96 of file AP_AHRS_Backend.cpp.
Referenced by AP_AHRS_View::update(), and update_trig().
check_lane_switch()
void AP_AHRS::check_lane_switch (void)
Definition at line 3263 of file AP_AHRS.cpp.
Referenced by RC_Channel::do_aux_function().
CLASS_NO_COPY()
AP_AHRS::CLASS_NO_COPY (AP_AHRS)
copy_estimates_from_backend_estimates()
void AP_AHRS::copy_estimates_from_backend_estimates (const AP_AHRS_Backend::Estimates & results) private
Definition at line 500 of file AP_AHRS.cpp.
cos_pitch()
float AP_AHRS::cos_pitch () const inline
Definition at line 560 of file AP_AHRS.h.
cos_roll()
float AP_AHRS::cos_roll () const inline
Definition at line 557 of file AP_AHRS.h.
cos_yaw()
float AP_AHRS::cos_yaw () const inline
Definition at line 563 of file AP_AHRS.h.
Referenced by AR_AttitudeControl::get_forward_speed().
create_view()
AP_AHRS_View * AP_AHRS::create_view (enum Rotation rotation, float pitch_trim_deg = 0)
Definition at line 164 of file AP_AHRS_Backend.cpp.
earth_to_body()
Vector3f AP_AHRS::earth_to_body (const Vector3f & v) const
Definition at line 307 of file AP_AHRS.cpp.
Referenced by SoaringController::update_cruising().
earth_to_body2D()
Vector2f AP_AHRS::earth_to_body2D (const Vector2f & ef_vector) const
Definition at line 234 of file AP_AHRS_Backend.cpp.
Referenced by AC_Avoid::adjust_velocity_proximity(), and AR_PosControl::update().
ekf_type()
AP_AHRS::EKFType AP_AHRS::ekf_type (void) const private
Definition at line 1831 of file AP_AHRS.cpp.
Referenced by _active_EKF_type(), _get_origin(), attitudes_consistent(), get_filter_status(), get_innovations(), get_variances(), get_vel_innovations_and_variances_for_source(), getMagOffsets(), healthy(), initialised(), is_vibration_affected(), pre_arm_check(), resetHeightDatum(), and send_ekf_status_report().
estimate_wind()
void AP_AHRS::estimate_wind () inline
Definition at line 128 of file AP_AHRS.h.
fallback_active_EKF_type()
AP_AHRS::EKFType AP_AHRS::fallback_active_EKF_type (void) const private
Definition at line 2042 of file AP_AHRS.cpp.
Referenced by _active_EKF_type(), and _get_secondary_EKF_type().
get_accel()
const Vector3f & AP_AHRS::get_accel (void) const inline
Definition at line 615 of file AP_AHRS.h.
get_accel_bias()
const Vector3f & AP_AHRS::get_accel_bias (void) const inline
Definition at line 622 of file AP_AHRS.h.
Referenced by AP_YawController::get_servo_out().
get_accel_ef()
const Vector3f & AP_AHRS::get_accel_ef () const inline
Definition at line 227 of file AP_AHRS.h.
Referenced by AP_AHRS_View::get_accel_ef(), AR_PosControl::init(), and AP_TECS::update_50hz().
get_active_airspeed_index()
uint8_t AP_AHRS::get_active_airspeed_index () const
Definition at line 3152 of file AP_AHRS.cpp.
Referenced by _airspeed_estimate().
get_EAS2TAS()
float AP_AHRS::get_EAS2TAS (void) const inline
Definition at line 144 of file AP_AHRS.h.
Referenced by _airspeed_estimate(), _airspeed_estimate_true(), AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_TECS::_update_speed(), AP_TECS::_update_speed_demand(), AP_AHRS_View::get_EAS2TAS(), AP_YawController::get_rate_out(), AP_TECS::get_target_airspeed(), SoaringController::get_thermalling_radius(), AP_L1_Control::loiter_radius(), and AP_L1_Control::turn_distance().
get_ekf_type()
int8_t AP_AHRS::get_ekf_type (void) const inline
Definition at line 430 of file AP_AHRS.h.
get_error_rp()
float AP_AHRS::get_error_rp (void) const
Definition at line 778 of file AP_AHRS.cpp.
Referenced by AP_AHRS_View::get_error_rp().
get_error_yaw()
float AP_AHRS::get_error_yaw (void) const
Definition at line 786 of file AP_AHRS.cpp.
Referenced by AP_AHRS_View::get_error_yaw().
get_filter_status()
bool AP_AHRS::get_filter_status (nav_filter_status & status) const
Definition at line 2293 of file AP_AHRS.cpp.
Referenced by _active_EKF_type(), _should_use_airspeed_sensor(), and AP_InertialNav::get_filter_status().
get_fly_forward()
bool AP_AHRS::get_fly_forward (void) const inline
Definition at line 651 of file AP_AHRS.h.
get_gyro()
const Vector3f & AP_AHRS::get_gyro (void) const inline
Definition at line 80 of file AP_AHRS.h.
Referenced by AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_OpticalFlow_Calibrator::add_sample(), AP_YawController::get_rate_out(), AP_YawController::get_servo_out(), get_yaw_rate_earth(), AC_PrecLand::run_estimator(), AC_PrecLand::run_output_prediction(), AP_OpticalFlow_Pixart::timer(), AP_AHRS_View::update(), AP_OpticalFlow_CXOF::update(), and AP_OpticalFlow_UPFLOW::update().
get_gyro_drift()
const Vector3f & AP_AHRS::get_gyro_drift (void) const inline
Definition at line 83 of file AP_AHRS.h.
Referenced by get_gyro_latest(), and update().
get_gyro_latest()
Vector3f AP_AHRS::get_gyro_latest (void) const
Definition at line 35 of file AP_AHRS_Backend.cpp.
Referenced by AP_AHRS_View::get_gyro_latest().
get_hagl()
bool AP_AHRS::get_hagl (float & hagl) const
Definition at line 1604 of file AP_AHRS.cpp.
get_hgt_ctrl_limit()
bool AP_AHRS::get_hgt_ctrl_limit (float & limit) const
Definition at line 2946 of file AP_AHRS.cpp.
Referenced by AC_Avoid::adjust_velocity_z().
get_home()
const Location & AP_AHRS::get_home (void) const inline
Definition at line 524 of file AP_AHRS.h.
Referenced by AP_Rally::calc_best_rally_or_home_location(), AP_Frsky_SPort_Passthrough::calc_home(), AP_OABendyRuler::calc_margin_from_circular_fence(), AP_Frsky_Backend::calc_nav_alt(), Location::get_alt_cm(), get_location_from_home_offset(), get_relative_position_D_home(), SoaringController::get_target(), AP_Follow::get_target_dist_and_vel_ned(), and AP_MSP_Telem_Backend::update_home_pos().
get_innovations()
bool AP_AHRS::get_innovations (Vector3f & velInnov, Vector3f & posInnov, Vector3f & magInnov, float & tasInnov, float & yawInnov) const
Definition at line 3010 of file AP_AHRS.cpp.
get_location()
bool AP_AHRS::get_location (Location & loc) const
Definition at line 3460 of file AP_AHRS.cpp.
Referenced by AP_Frsky_Backend::calc_gps_position(), AP_Frsky_SPort_Passthrough::calc_home(), AP_Frsky_Backend::calc_nav_alt(), AP_AHRS_View::get_location(), get_relative_position_NE_home(), get_relative_position_NED_home(), AR_WPNav::update(), AP_MSP_Telem_Backend::update_home_pos(), AP_L1_Control::update_loiter(), and AP_L1_Control::update_waypoint().
get_location_from_home_offset()
bool AP_AHRS::get_location_from_home_offset (Location & loc, const Vector3p & offset_ned) const
Definition at line 3542 of file AP_AHRS.cpp.
get_location_from_origin_offset()
bool AP_AHRS::get_location_from_origin_offset (Location & loc, const Vector3p & offset_ned) const
Definition at line 3530 of file AP_AHRS.cpp.
get_mag_field_correction()
bool AP_AHRS::get_mag_field_correction (Vector3f & ret) const
Definition at line 1536 of file AP_AHRS.cpp.
get_mag_field_NED()
bool AP_AHRS::get_mag_field_NED (Vector3f & ret) const
Definition at line 1504 of file AP_AHRS.cpp.
get_max_wind()
uint8_t AP_AHRS::get_max_wind () const inline
Definition at line 135 of file AP_AHRS.h.
get_origin()
bool AP_AHRS::get_origin (Location & ret) const
Definition at line 3514 of file AP_AHRS.cpp.
Referenced by AP_OAPathPlanner::avoidance_thread(), and get_location_from_origin_offset().
get_pitch()
float AP_AHRS::get_pitch () const inline
Definition at line 553 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_TECS::_initialise_states(), AP_TECS::_update_throttle_without_airspeed(), AR_AttitudeControl::get_throttle_out_from_pitch(), and AP_L1_Control::nav_roll_cd().
get_posvelyaw_source_set()
uint8_t AP_AHRS::get_posvelyaw_source_set () const
Definition at line 3336 of file AP_AHRS.cpp.
get_primary_accel_index()
uint8_t AP_AHRS::get_primary_accel_index (void) const inline
Definition at line 401 of file AP_AHRS.h.
Referenced by AC_PrecLand::run_output_prediction().
get_primary_core_index()
int8_t AP_AHRS::get_primary_core_index () const inline
Definition at line 398 of file AP_AHRS.h.
get_primary_gyro_index()
uint8_t AP_AHRS::get_primary_gyro_index (void) const inline
Definition at line 404 of file AP_AHRS.h.
Referenced by AP_InertialSensor_Backend::apply_gyro_filters(), get_gyro_latest(), and AP_InertialSensor_Backend::log_gyro_raw().
get_quat_body_to_ned()
void AP_AHRS::get_quat_body_to_ned (Quaternion & quat) const
Definition at line 295 of file AP_AHRS.cpp.
Referenced by attitudes_consistent().
get_quaternion()
bool AP_AHRS::get_quaternion (Quaternion & quat) const
Definition at line 3507 of file AP_AHRS.cpp.
get_relative_position_D_home()
void AP_AHRS::get_relative_position_D_home (float & posD) const
Definition at line 1799 of file AP_AHRS.cpp.
Referenced by AC_Avoid::adjust_velocity_z(), AP_AHRS_View::get_relative_position_D_home(), GCS_MAVLINK::global_position_int_relative_alt(), Variometer::update(), AP_TECS::update_50hz(), and AP_MSP_Telem_Backend::update_home_pos().
get_relative_position_D_origin()
bool AP_AHRS::get_relative_position_D_origin (float & posD) const
Definition at line 1762 of file AP_AHRS.cpp.
Referenced by AC_Avoid::adjust_velocity_z(), get_relative_position_D_home(), AP_AHRS_View::get_relative_position_D_origin(), and AP_InertialNav::update().
get_relative_position_NE_home()
bool AP_AHRS::get_relative_position_NE_home (Vector2f & posNE) const
Definition at line 1744 of file AP_AHRS.cpp.
Referenced by AP_AHRS_View::get_relative_position_NE_home().
get_relative_position_NE_origin()
bool AP_AHRS::get_relative_position_NE_origin (Vector2f & posNE) const
Definition at line 1706 of file AP_AHRS.cpp.
Referenced by AC_Avoid::adjust_velocity_polygon(), AP_AHRS_View::get_relative_position_NE_origin(), AP_InertialNav::update(), and AR_PosControl::update().
get_relative_position_NED_home()
bool AP_AHRS::get_relative_position_NED_home (Vector3f & vec) const
Definition at line 1692 of file AP_AHRS.cpp.
Referenced by AP_AHRS_View::get_relative_position_NED_home(), SoaringController::init_thermalling(), and SoaringController::update_thermalling().
get_relative_position_NED_origin()
bool AP_AHRS::get_relative_position_NED_origin (Vector3f & vec) const
Definition at line 1638 of file AP_AHRS.cpp.
Referenced by AC_PrecLand::construct_pos_meas_using_rangefinder(), AP_AHRS_View::get_relative_position_NED_origin(), AC_PrecLand_StateMachine::retry_landing(), AP_SmartRTL::set_home(), and AP_SmartRTL::update().
get_roll()
float AP_AHRS::get_roll () const inline
Definition at line 552 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_YawController::get_servo_out(), and Variometer::update().
get_rotation_autopilot_body_to_vehicle_body()
const Matrix3f & AP_AHRS::get_rotation_autopilot_body_to_vehicle_body (void) const inline
Definition at line 494 of file AP_AHRS.h.
Referenced by _getCorrectedDeltaVelocityNED().
get_rotation_body_to_ned()
const Matrix3f & AP_AHRS::get_rotation_body_to_ned (void) const inline
Definition at line 581 of file AP_AHRS.h.
Referenced by AP_TECS::_update_speed(), AP_TECS::_update_throttle_with_airspeed(), AP_TECS::_update_throttle_without_airspeed(), body_to_earth(), earth_to_body(), get_quat_body_to_ned(), get_yaw_rate_earth(), AC_PrecLand::run_output_prediction(), AP_AHRS_View::update(), AC_PrecLand_SITL::update(), AP_IRLock_SITL::update(), Variometer::update(), update_AOA_SSA(), and update_trig().
get_rotation_vehicle_body_to_autopilot_body()
const Matrix3f & AP_AHRS::get_rotation_vehicle_body_to_autopilot_body (void) const inline
Definition at line 495 of file AP_AHRS.h.
get_secondary_attitude()
bool AP_AHRS::get_secondary_attitude (Vector3f & eulers) const inline
Definition at line 204 of file AP_AHRS.h.
get_secondary_position()
bool AP_AHRS::get_secondary_position (Location & loc) const inline
Definition at line 216 of file AP_AHRS.h.
get_secondary_quaternion()
bool AP_AHRS::get_secondary_quaternion (Quaternion & quat) const inline
Definition at line 210 of file AP_AHRS.h.
get_semaphore()
HAL_Semaphore & AP_AHRS::get_semaphore (void) inline
Definition at line 75 of file AP_AHRS.h.
Referenced by AP_Spektrum_Telem::calc_attandmag(), AP_Frsky_SPort_Passthrough::calc_home(), AP_Frsky_Backend::calc_nav_alt(), AP_Frsky_SPort_Passthrough::calc_velandyaw(), AP_RCTelemetry::check_ekf_status(), AP_Frsky_Backend::get_vspeed_ms(), AP_MSP_Telem_Backend::get_vspeed_ms(), and AP_MSP_Telem_Backend::update_home_pos().
get_singleton()
static AP_AHRS * AP_AHRS::get_singleton () inline static
Definition at line 64 of file AP_AHRS.h.
Referenced by AP::ahrs().
get_takeoff_expected()
bool AP_AHRS::get_takeoff_expected (void) const inline
Definition at line 632 of file AP_AHRS.h.
get_touchdown_expected()
bool AP_AHRS::get_touchdown_expected (void) const inline
Definition at line 638 of file AP_AHRS.h.
get_trim()
const Vector3f & AP_AHRS::get_trim () const inline
Definition at line 485 of file AP_AHRS.h.
get_variances()
bool AP_AHRS::get_variances (float & velVar, float & posVar, float & hgtVar, Vector3f & magVar, float & tasVar) const
Definition at line 3074 of file AP_AHRS.cpp.
Referenced by AP_RCTelemetry::check_ekf_status().
get_vehicle_class()
VehicleClass AP_AHRS::get_vehicle_class (void) const inline
Definition at line 666 of file AP_AHRS.h.
get_vel_innovations_and_variances_for_source()
bool AP_AHRS::get_vel_innovations_and_variances_for_source (uint8_t source, Vector3f & innovations, Vector3f & variances) const
Definition at line 3115 of file AP_AHRS.cpp.
get_velocity_NED()
bool AP_AHRS::get_velocity_NED (Vector3f & vec) const
Definition at line 3522 of file AP_AHRS.cpp.
Referenced by _airspeed_estimate(), AR_AttitudeControl::get_forward_speed(), AP_AHRS_View::get_velocity_NED(), AP_Frsky_Backend::get_vspeed_ms(), AP_MSP_Telem_Backend::get_vspeed_ms(), AR_PosControl::handle_ekf_xy_reset(), AC_PrecLand::run_output_prediction(), AP_InertialNav::update(), Variometer::update(), AR_PosControl::update(), AP_TECS::update_50hz(), and update_AOA_SSA().
get_vert_pos_rate_D()
bool AP_AHRS::get_vert_pos_rate_D (float & velocity) const
Definition at line 1570 of file AP_AHRS.cpp.
Referenced by AP_InertialNav::update().
get_vibration()
Vector3f AP_AHRS::get_vibration (void) const
Definition at line 272 of file AP_AHRS_Backend.cpp.
get_view()
AP_AHRS_View * AP_AHRS::get_view (void) const inline
Definition at line 674 of file AP_AHRS.h.
Referenced by AP_InertialSensor::_calculate_trim().
get_wind_estimation_enabled()
bool AP_AHRS::get_wind_estimation_enabled () const inline
Definition at line 110 of file AP_AHRS.h.
Referenced by _airspeed_estimate().
get_yaw()
float AP_AHRS::get_yaw () const inline
Definition at line 554 of file AP_AHRS.h.
Referenced by AP_L1_Control::get_yaw(), SoaringController::init_thermalling(), AC_AttitudeControl_Sub::input_euler_angle_roll_pitch_slew_yaw(), AP_WindVane::record_home_heading(), AP_L1_Control::update_level_flight(), AP_L1_Control::update_loiter(), and AP_WindVane::update_true_wind_speed_and_direction().
get_yaw_estimator()
const EKFGSF_yaw * AP_AHRS::get_yaw_estimator (void) const
Definition at line 3428 of file AP_AHRS.cpp.
get_yaw_rate_earth()
float AP_AHRS::get_yaw_rate_earth (void) const inline
Definition at line 514 of file AP_AHRS.h.
Referenced by AR_AttitudeControl::get_lat_accel(), AP_SteerController::get_steering_out_rate(), AR_AttitudeControl::get_steering_out_rate(), and GCS_MAVLINK::send_autopilot_state_for_gimbal_device().
getAOA()
float AP_AHRS::getAOA (void) const inline
Definition at line 475 of file AP_AHRS.h.
getControlLimits()
void AP_AHRS::getControlLimits (float & ekfGndSpdLimit, float & controlScaleXY) const
Definition at line 2388 of file AP_AHRS.cpp.
Referenced by AC_Loiter::calc_desired_velocity(), and AC_PosControl::update_xy_controller().
getControlScaleZ()
float AP_AHRS::getControlScaleZ (void) const
Definition at line 2427 of file AP_AHRS.cpp.
Referenced by AC_PosControl::update_z_controller().
getCorrectedDeltaVelocityNED()
void AP_AHRS::getCorrectedDeltaVelocityNED (Vector3f & ret, float & dt) const inline
Definition at line 232 of file AP_AHRS.h.
getLastPosDownReset()
uint32_t AP_AHRS::getLastPosDownReset (float & posDelta)
Definition at line 2718 of file AP_AHRS.cpp.
Referenced by AP_AHRS_View::getLastPosDownReset().
getLastPosNorthEastReset()
uint32_t AP_AHRS::getLastPosNorthEastReset (Vector2f & pos)
Definition at line 2651 of file AP_AHRS.cpp.
Referenced by AP_AHRS_View::getLastPosNorthEastReset(), AR_PosControl::handle_ekf_xy_reset(), and AR_PosControl::init_ekf_xy_reset().
getLastVelNorthEastReset()
uint32_t AP_AHRS::getLastVelNorthEastReset (Vector2f & vel) const
Definition at line 2684 of file AP_AHRS.cpp.
getLastYawResetAngle()
uint32_t AP_AHRS::getLastYawResetAngle (float & yawAng)
Definition at line 2618 of file AP_AHRS.cpp.
getMagOffsets()
bool AP_AHRS::getMagOffsets (uint8_t mag_idx, Vector3f & magOffsets) const
Definition at line 2441 of file AP_AHRS.cpp.
getOptFlowSample()
bool AP_AHRS::getOptFlowSample (uint32_t & timeStamp_ms, Vector2f & flowRate, Vector2f & bodyRate, Vector2f & losPred) const
Definition at line 2338 of file AP_AHRS.cpp.
getSSA()
float AP_AHRS::getSSA (void) const inline
Definition at line 478 of file AP_AHRS.h.
groundspeed()
float AP_AHRS::groundspeed (void) const inline
Definition at line 225 of file AP_AHRS.h.
Referenced by AP_Frsky_Backend::calc_gps_position(), AP_Frsky_SPort_Passthrough::calc_velandyaw(), AP_SteerController::get_steering_out_lat_accel(), AP_SteerController::get_steering_out_rate(), AP_AHRS_View::groundspeed(), and AP_Landing::type_slope_setup_landing_glide_slope().
groundspeed_vector()
const Vector2f & AP_AHRS::groundspeed_vector () const inline
Definition at line 222 of file AP_AHRS.h.
Referenced by _groundspeed(), AR_WPNav::get_stopping_location(), AP_AHRS_View::groundspeed_vector(), AP_OAPathPlanner::mission_avoidance(), AP_L1_Control::update_heading_hold(), AP_L1_Control::update_loiter(), and AP_L1_Control::update_waypoint().
have_inertial_nav()
bool AP_AHRS::have_inertial_nav (void) const
Definition at line 1459 of file AP_AHRS.cpp.
Referenced by _airspeed_estimate().
head_wind()
float AP_AHRS::head_wind (void) const
Definition at line 847 of file AP_AHRS.cpp.
Referenced by AP_Landing::type_slope_get_target_airspeed_cm().
healthy()
bool AP_AHRS::healthy (void) const
Definition at line 2128 of file AP_AHRS.cpp.
Referenced by pre_arm_check().
home_is_locked()
bool AP_AHRS::home_is_locked () const inline
Definition at line 533 of file AP_AHRS.h.
home_is_set()
bool AP_AHRS::home_is_set (void) const inline
Definition at line 538 of file AP_AHRS.h.
Referenced by get_location_from_home_offset(), and AP_MSP_Telem_Backend::update_home_pos().
init()
void AP_AHRS::init (void)
Definition at line 223 of file AP_AHRS.cpp.
Referenced by DummyVehicle::init(), setup(), and setup().
initialised()
bool AP_AHRS::initialised (void) const
Definition at line 2260 of file AP_AHRS.cpp.
is_vibration_affected()
bool AP_AHRS::is_vibration_affected () const
Definition at line 3046 of file AP_AHRS.cpp.
load_watchdog_home()
void AP_AHRS::load_watchdog_home () private
Definition at line 2930 of file AP_AHRS.cpp.
Referenced by update().
lock_home()
void AP_AHRS::lock_home () inline
Definition at line 530 of file AP_AHRS.h.
Log_Write()
void AP_AHRS::Log_Write ()
Definition at line 3345 of file AP_AHRS.cpp.
Log_Write_Home_And_Origin()
void AP_AHRS::Log_Write_Home_And_Origin ()
Referenced by set_home().
option_set()
bool AP_AHRS::option_set (Options option) const inline private
Definition at line 1017 of file AP_AHRS.h.
Referenced by _active_EKF_type().
pre_arm_check()
bool AP_AHRS::pre_arm_check (bool requires_position, char * failure_msg, uint8_t failure_msg_len) const
Definition at line 2189 of file AP_AHRS.cpp.
Referenced by pre_arm_check().
request_yaw_reset()
void AP_AHRS::request_yaw_reset (void)
Definition at line 3296 of file AP_AHRS.cpp.
Referenced by RC_Channel::do_aux_function().
reset()
void AP_AHRS::reset ()
Definition at line 704 of file AP_AHRS.cpp.
reset_gyro_drift()
void AP_AHRS::reset_gyro_drift (void)
Definition at line 315 of file AP_AHRS.cpp.
resetHeightDatum()
bool AP_AHRS::resetHeightDatum (void)
Definition at line 2753 of file AP_AHRS.cpp.
Referenced by AP_Baro::update_field_elevation().
send_ekf_status_report()
void AP_AHRS::send_ekf_status_report (class GCS_MAVLINK & link) const
Definition at line 2800 of file AP_AHRS.cpp.
Referenced by GCS_MAVLINK::try_send_message().
set_alt_measurement_noise()
void AP_AHRS::set_alt_measurement_noise (float noise)
Definition at line 3417 of file AP_AHRS.cpp.
set_ekf_type()
void AP_AHRS::set_ekf_type (EKFType ahrs_type) inline
Definition at line 453 of file AP_AHRS.h.
Referenced by RC_Channel::do_aux_function().
set_failure_inconsistent_message()
void AP_AHRS::set_failure_inconsistent_message (const char * estimator, const char * axis, float diff_rad, char * failure_msg, const uint8_t failure_msg_len) const private
Definition at line 2513 of file AP_AHRS.cpp.
Referenced by attitudes_consistent().
set_fly_forward()
void AP_AHRS::set_fly_forward (bool b) inline
Definition at line 648 of file AP_AHRS.h.
set_home()
bool AP_AHRS::set_home (const Location & loc)
Definition at line 2885 of file AP_AHRS.cpp.
Referenced by TEST(), and TEST().
set_origin()
bool AP_AHRS::set_origin (const Location & loc)
Definition at line 1405 of file AP_AHRS.cpp.
set_posvelyaw_source_set()
void AP_AHRS::set_posvelyaw_source_set (uint8_t source_set_idx)
Definition at line 3328 of file AP_AHRS.cpp.
Referenced by RC_Channel::do_aux_function().
set_takeoff_expected()
void AP_AHRS::set_takeoff_expected (bool b)
Definition at line 277 of file AP_AHRS_Backend.cpp.
set_terrain_hgt_stable()
void AP_AHRS::set_terrain_hgt_stable (bool stable)
Definition at line 2980 of file AP_AHRS.cpp.
set_touchdown_expected()
void AP_AHRS::set_touchdown_expected (bool b)
Definition at line 283 of file AP_AHRS_Backend.cpp.
set_trim()
void AP_AHRS::set_trim (const Vector3f & new_trim)
Definition at line 42 of file AP_AHRS_Backend.cpp.
set_vehicle_class()
void AP_AHRS::set_vehicle_class (VehicleClass vclass) inline
Definition at line 669 of file AP_AHRS.h.
set_wind_estimation_enabled()
void AP_AHRS::set_wind_estimation_enabled (bool b) inline
Definition at line 107 of file AP_AHRS.h.
sin_pitch()
float AP_AHRS::sin_pitch () const inline
Definition at line 569 of file AP_AHRS.h.
sin_roll()
float AP_AHRS::sin_roll () const inline
Definition at line 566 of file AP_AHRS.h.
sin_yaw()
float AP_AHRS::sin_yaw () const inline
Definition at line 572 of file AP_AHRS.h.
Referenced by AR_AttitudeControl::get_forward_speed().
synthetic_airspeed()
bool AP_AHRS::synthetic_airspeed (float & ret) const
Definition at line 1084 of file AP_AHRS.cpp.
update()
void AP_AHRS::update (bool skip_ins_update = false)
Definition at line 363 of file AP_AHRS.cpp.
Referenced by loop().
update_AOA_SSA()
void AP_AHRS::update_AOA_SSA (void) private
Definition at line 187 of file AP_AHRS_Backend.cpp.
Referenced by update().
update_cd_values()
void AP_AHRS::update_cd_values (void) private
Definition at line 152 of file AP_AHRS_Backend.cpp.
Referenced by copy_estimates_from_backend_estimates().
update_DCM()
void AP_AHRS::update_DCM () private
Referenced by update().
update_flags()
void AP_AHRS::update_flags (void) private
Definition at line 292 of file AP_AHRS_Backend.cpp.
Referenced by update().
update_notify_from_filter_status()
void AP_AHRS::update_notify_from_filter_status (const nav_filter_status & status) private
Definition at line 547 of file AP_AHRS.cpp.
update_orientation()
void AP_AHRS::update_orientation ()
Definition at line 71 of file AP_AHRS_Backend.cpp.
Referenced by Compass::init(), and update().
update_state()
void AP_AHRS::update_state (void) private
Definition at line 340 of file AP_AHRS.cpp.
Referenced by update().
update_trig()
void AP_AHRS::update_trig (void) private
Definition at line 142 of file AP_AHRS_Backend.cpp.
Referenced by copy_estimates_from_backend_estimates().
update_trim_rotation_matrices()
void AP_AHRS::update_trim_rotation_matrices () private
Definition at line 282 of file AP_AHRS.cpp.
Referenced by update().
use_compass()
bool AP_AHRS::use_compass (void)
Definition at line 1093 of file AP_AHRS.cpp.
using_airspeed_sensor()
bool AP_AHRS::using_airspeed_sensor () const
Definition at line 856 of file AP_AHRS.cpp.
Referenced by AP_TECS::_update_pitch(), AP_TECS::_update_speed(), and AP_TECS::update_pitch_throttle().
using_extnav_for_yaw()
bool AP_AHRS::using_extnav_for_yaw (void) const
Definition at line 3390 of file AP_AHRS.cpp.
using_noncompass_for_yaw()
bool AP_AHRS::using_noncompass_for_yaw (void) const
Definition at line 3363 of file AP_AHRS.cpp.
Referenced by attitudes_consistent().
wind_alignment()
float AP_AHRS::wind_alignment (const float heading_deg) const
Definition at line 834 of file AP_AHRS.cpp.
Referenced by head_wind().
wind_estimate() [1/2]
const Vector3f & AP_AHRS::wind_estimate () const inline
Definition at line 113 of file AP_AHRS.h.
wind_estimate() [2/2]
bool AP_AHRS::wind_estimate (Vector3f & wind) const
Write_AHRS2()
void AP_AHRS::Write_AHRS2 (void) const private
Referenced by Log_Write().
Write_AOA_SSA()
void AP_AHRS::Write_AOA_SSA (void) const
Write_Attitude()
void AP_AHRS::Write_Attitude (const Vector3f & targets) const
Write_Origin()
void AP_AHRS::Write_Origin (LogOriginType origin_type, const Location & loc) const
Write_POS()
void AP_AHRS::Write_POS (void) const private
Referenced by Log_Write().
write_video_stabilisation()
void AP_AHRS::write_video_stabilisation () const
writeBodyFrameOdom()
void AP_AHRS::writeBodyFrameOdom (float quality, const Vector3f & delPos, const Vector3f & delAng, float delTime, uint32_t timeStamp_ms, uint16_t delay_ms, const Vector3f & posOffset)
Definition at line 2347 of file AP_AHRS.cpp.
writeDefaultAirSpeed()
void AP_AHRS::writeDefaultAirSpeed (float airspeed, float uncertainty)
Definition at line 2366 of file AP_AHRS.cpp.
writeExtNavData()
void AP_AHRS::writeExtNavData (const Vector3f & pos, const Quaternion & quat, float posErr, float angErr, uint32_t timeStamp_ms, uint16_t delay_ms, uint32_t resetTime_ms)
Definition at line 2355 of file AP_AHRS.cpp.
writeExtNavVelData()
void AP_AHRS::writeExtNavVelData (const Vector3f & vel, float err, uint32_t timeStamp_ms, uint16_t delay_ms)
Definition at line 2377 of file AP_AHRS.cpp.
writeOptFlowMeas()
void AP_AHRS::writeOptFlowMeas (const uint8_t rawFlowQuality, const Vector2f & rawFlowRates, const Vector2f & rawGyroRates, const uint32_t msecFlowMeas, const Vector3f & posOffset, const float heightOverride)
Definition at line 2327 of file AP_AHRS.cpp.
Referenced by AP_OpticalFlow::update_state().
Friends And Related Symbol Documentation
AP_AHRS_View
friend class AP_AHRS_View friend
Definition at line 47 of file AP_AHRS.h.
Referenced by create_view().
Member Data Documentation
_AOA
float AP_AHRS::_AOA private
Definition at line 794 of file AP_AHRS.h.
Referenced by getAOA(), and update_AOA_SSA().
_board_orientation
AP_Int8 AP_AHRS::_board_orientation private
Definition at line 704 of file AP_AHRS.h.
Referenced by init(), and update_orientation().
_checked_watchdog_home
bool AP_AHRS::_checked_watchdog_home private
Definition at line 777 of file AP_AHRS.h.
Referenced by update().
_cos_pitch
float AP_AHRS::_cos_pitch {1.0f} private
Definition at line 748 of file AP_AHRS.h.
Referenced by cos_pitch(), and update_trig().
_cos_roll
float AP_AHRS::_cos_roll {1.0f} private
Definition at line 747 of file AP_AHRS.h.
Referenced by cos_roll(), and update_trig().
_cos_yaw
float AP_AHRS::_cos_yaw {1.0f} private
Definition at line 749 of file AP_AHRS.h.
Referenced by body_to_earth2D(), cos_yaw(), earth_to_body2D(), and update_trig().
_ekf_flags
uint8_t AP_AHRS::_ekf_flags private
Definition at line 768 of file AP_AHRS.h.
Referenced by always_use_EKF(), and AP_AHRS().
_ekf_type
AP_Enum<EKFType> AP_AHRS::_ekf_type private
Definition at line 705 of file AP_AHRS.h.
Referenced by _get_secondary_EKF_type(), ekf_type(), get_ekf_type(), init(), set_ekf_type(), and update().
_gps_minsats
AP_Int8 AP_AHRS::_gps_minsats private
Definition at line 718 of file AP_AHRS.h.
_gps_use
AP_Enum<GPSUse> AP_AHRS::_gps_use private
Definition at line 717 of file AP_AHRS.h.
Referenced by _active_EKF_type(), and get_relative_position_D_home().
_home
Location AP_AHRS::_home private
Definition at line 778 of file AP_AHRS.h.
Referenced by get_home(), get_relative_position_D_home(), get_relative_position_NE_home(), get_relative_position_NED_home(), load_watchdog_home(), and set_home().
_home_is_set
bool AP_AHRS::_home_is_set private
Definition at line 779 of file AP_AHRS.h.
Referenced by get_relative_position_D_home(), get_relative_position_NE_home(), get_relative_position_NED_home(), home_is_set(), load_watchdog_home(), and set_home().
_home_locked
bool AP_AHRS::_home_locked private
Definition at line 780 of file AP_AHRS.h.
Referenced by home_is_locked(), load_watchdog_home(), and lock_home().
_kp
AP_Float AP_AHRS::_kp private
Definition at line 712 of file AP_AHRS.h.
_kp_yaw
AP_Float AP_AHRS::_kp_yaw private
Definition at line 711 of file AP_AHRS.h.
_last_AOA_update_ms
uint32_t AP_AHRS::_last_AOA_update_ms private
Definition at line 795 of file AP_AHRS.h.
Referenced by update_AOA_SSA().
_last_trim
Vector3f AP_AHRS::_last_trim private
Definition at line 816 of file AP_AHRS.h.
Referenced by AP_AHRS(), and update_trim_rotation_matrices().
_options
AP_Int16 AP_AHRS::_options private
Definition at line 1015 of file AP_AHRS.h.
Referenced by option_set().
_rotation_autopilot_body_to_vehicle_body
Matrix3f AP_AHRS::_rotation_autopilot_body_to_vehicle_body private
Definition at line 818 of file AP_AHRS.h.
Referenced by AP_AHRS(), get_rotation_autopilot_body_to_vehicle_body(), and update_trim_rotation_matrices().
_rotation_vehicle_body_to_autopilot_body
Matrix3f AP_AHRS::_rotation_vehicle_body_to_autopilot_body private
Definition at line 819 of file AP_AHRS.h.
Referenced by AP_AHRS(), get_rotation_vehicle_body_to_autopilot_body(), and update_trim_rotation_matrices().
_rsem
HAL_Semaphore AP_AHRS::_rsem private
Definition at line 698 of file AP_AHRS.h.
Referenced by get_semaphore(), reset(), reset_gyro_drift(), resetHeightDatum(), set_home(), set_origin(), and update().
_sin_pitch
float AP_AHRS::_sin_pitch private
Definition at line 751 of file AP_AHRS.h.
Referenced by sin_pitch(), and update_trig().
_sin_roll
float AP_AHRS::_sin_roll private
Definition at line 750 of file AP_AHRS.h.
Referenced by sin_roll(), and update_trig().
_sin_yaw
float AP_AHRS::_sin_yaw private
Definition at line 752 of file AP_AHRS.h.
Referenced by body_to_earth2D(), earth_to_body2D(), sin_yaw(), and update_trig().
_singleton
AP_AHRS * AP_AHRS::_singleton static private
Definition at line 689 of file AP_AHRS.h.
Referenced by AP_AHRS(), and get_singleton().
_SSA
float AP_AHRS::_SSA private
Definition at line 794 of file AP_AHRS.h.
Referenced by getSSA(), and update_AOA_SSA().
_trim
AP_Vector3f AP_AHRS::_trim private
Definition at line 813 of file AP_AHRS.h.
Referenced by _get_quaternion(), _get_secondary_quaternion(), add_trim(), AP_AHRS(), get_trim(), set_trim(), and update_trim_rotation_matrices().
_vehicle_class
VehicleClass AP_AHRS::_vehicle_class {VehicleClass::UNKNOWN} private
Definition at line 695 of file AP_AHRS.h.
Referenced by _active_EKF_type(), get_vehicle_class(), healthy(), and set_vehicle_class().
_view
AP_AHRS_View* AP_AHRS::_view private
Definition at line 687 of file AP_AHRS.h.
Referenced by create_view(), get_view(), and update().
_wind_max
AP_Int8 AP_AHRS::_wind_max private
Definition at line 703 of file AP_AHRS.h.
Referenced by _airspeed_estimate(), and get_max_wind().
accel_bias
Vector3f AP_AHRS::accel_bias
Definition at line 959 of file AP_AHRS.h.
Referenced by _getCorrectedDeltaVelocityNED().
accel_ef
Vector3f AP_AHRS::accel_ef
Definition at line 958 of file AP_AHRS.h.
active_EKF
EKFType AP_AHRS::active_EKF
Definition at line 950 of file AP_AHRS.h.
airspeed
float AP_AHRS::airspeed
Definition at line 964 of file AP_AHRS.h.
Referenced by get_active_airspeed_index(), and writeDefaultAirSpeed().
airspeed_estimate_type
AirspeedEstimateType AP_AHRS::airspeed_estimate_type
Definition at line 965 of file AP_AHRS.h.
Referenced by _airspeed_estimate().
airspeed_ok
bool AP_AHRS::airspeed_ok
Definition at line 963 of file AP_AHRS.h.
airspeed_true
float AP_AHRS::airspeed_true
Definition at line 967 of file AP_AHRS.h.
airspeed_true_ok
bool AP_AHRS::airspeed_true_ok
Definition at line 966 of file AP_AHRS.h.
airspeed_vec
Vector3f AP_AHRS::airspeed_vec
Definition at line 968 of file AP_AHRS.h.
airspeed_vec_ok
bool AP_AHRS::airspeed_vec_ok
Definition at line 969 of file AP_AHRS.h.
beta
AP_Float AP_AHRS::beta private
Definition at line 715 of file AP_AHRS.h.
corrected_dv
Vector3f AP_AHRS::corrected_dv
Definition at line 982 of file AP_AHRS.h.
corrected_dv_dt
float AP_AHRS::corrected_dv_dt
Definition at line 983 of file AP_AHRS.h.
dcm_matrix
Matrix3f AP_AHRS::dcm_matrix
Definition at line 956 of file AP_AHRS.h.
EAS2TAS
float AP_AHRS::EAS2TAS
Definition at line 962 of file AP_AHRS.h.
fly_forward
bool AP_AHRS::fly_forward private
Definition at line 850 of file AP_AHRS.h.
Referenced by _active_EKF_type(), _should_use_airspeed_sensor(), get_fly_forward(), and set_fly_forward().
gps_gain
AP_Float AP_AHRS::gps_gain private
Definition at line 713 of file AP_AHRS.h.
ground_speed
float AP_AHRS::ground_speed
Definition at line 981 of file AP_AHRS.h.
Referenced by _active_EKF_type().
ground_speed_vec
Vector2f AP_AHRS::ground_speed_vec
Definition at line 980 of file AP_AHRS.h.
gyro_drift
Vector3f AP_AHRS::gyro_drift
Definition at line 957 of file AP_AHRS.h.
gyro_estimate
Vector3f AP_AHRS::gyro_estimate
Definition at line 955 of file AP_AHRS.h.
last_active_ekf_type
EKFType AP_AHRS::last_active_ekf_type private
Definition at line 798 of file AP_AHRS.h.
Referenced by init(), and update().
last_orientation_update_ms
uint32_t AP_AHRS::last_orientation_update_ms private
Definition at line 822 of file AP_AHRS.h.
Referenced by update_orientation().
location
Location AP_AHRS::location
Definition at line 976 of file AP_AHRS.h.
location_ok
bool AP_AHRS::location_ok
Definition at line 977 of file AP_AHRS.h.
origin
Location AP_AHRS::origin
Definition at line 984 of file AP_AHRS.h.
origin_ok
bool AP_AHRS::origin_ok
Definition at line 985 of file AP_AHRS.h.
pitch
float AP_AHRS::pitch private
Definition at line 683 of file AP_AHRS.h.
Referenced by copy_estimates_from_backend_estimates(), get_pitch(), and update_cd_values().
pitch_sensor
int32_t AP_AHRS::pitch_sensor
Definition at line 578 of file AP_AHRS.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_Spektrum_Telem::calc_attandmag(), AP_PitchController::get_servo_out(), and update_cd_values().
primary_accel
uint8_t AP_AHRS::primary_accel
Definition at line 953 of file AP_AHRS.h.
primary_core
uint8_t AP_AHRS::primary_core
Definition at line 954 of file AP_AHRS.h.
primary_gyro
uint8_t AP_AHRS::primary_gyro
Definition at line 952 of file AP_AHRS.h.
Referenced by get_gyro_latest().
primary_IMU
uint8_t AP_AHRS::primary_IMU
Definition at line 951 of file AP_AHRS.h.
quat
Quaternion AP_AHRS::quat
Definition at line 970 of file AP_AHRS.h.
Referenced by _get_quaternion(), _get_secondary_quaternion(), get_quat_body_to_ned(), get_quaternion(), get_secondary_quaternion(), and writeExtNavData().
quat_ok
bool AP_AHRS::quat_ok
Definition at line 971 of file AP_AHRS.h.
roll
float AP_AHRS::roll private
Definition at line 682 of file AP_AHRS.h.
Referenced by copy_estimates_from_backend_estimates(), get_roll(), and update_cd_values().
roll_sensor
int32_t AP_AHRS::roll_sensor
Definition at line 577 of file AP_AHRS.h.
Referenced by AP_Spektrum_Telem::calc_attandmag(), AP_PitchController::get_servo_out(), and update_cd_values().
secondary_attitude
Vector3f AP_AHRS::secondary_attitude
Definition at line 972 of file AP_AHRS.h.
secondary_attitude_ok
bool AP_AHRS::secondary_attitude_ok
Definition at line 973 of file AP_AHRS.h.
secondary_pos
Location AP_AHRS::secondary_pos
Definition at line 978 of file AP_AHRS.h.
secondary_pos_ok
bool AP_AHRS::secondary_pos_ok
Definition at line 979 of file AP_AHRS.h.
secondary_quat
Quaternion AP_AHRS::secondary_quat
Definition at line 974 of file AP_AHRS.h.
secondary_quat_ok
bool AP_AHRS::secondary_quat_ok
Definition at line 975 of file AP_AHRS.h.
start_time_ms
uint32_t AP_AHRS::start_time_ms private
Definition at line 767 of file AP_AHRS.h.
Referenced by initialised().
startup_delay_ms
const uint16_t AP_AHRS::startup_delay_ms = 1000 private
Definition at line 766 of file AP_AHRS.h.
[struct]
struct { ... } AP_AHRS::state
Referenced by _getCorrectedDeltaVelocityNED(), active_EKF_type(), airspeed_estimate(), airspeed_estimate(), airspeed_estimate_true(), airspeed_vector_true(), AP_AHRS(), copy_estimates_from_backend_estimates(), get_accel_bias(), get_accel_ef(), get_EAS2TAS(), get_gyro(), get_gyro_drift(), get_location(), get_origin(), get_primary_accel_index(), get_primary_core_index(), get_primary_gyro_index(), get_quaternion(), get_rotation_body_to_ned(), get_secondary_attitude(), get_secondary_position(), get_secondary_quaternion(), get_velocity_NED(), getCorrectedDeltaVelocityNED(), groundspeed(), groundspeed_vector(), update(), update_state(), using_airspeed_sensor(), and wind_estimate().
takeoff_expected
bool AP_AHRS::takeoff_expected private
Definition at line 834 of file AP_AHRS.h.
Referenced by get_takeoff_expected(), set_takeoff_expected(), and update_flags().
takeoff_expected_start_ms
uint32_t AP_AHRS::takeoff_expected_start_ms private
Definition at line 835 of file AP_AHRS.h.
Referenced by set_takeoff_expected(), and update_flags().
terrainHgtStableState
TriState AP_AHRS::terrainHgtStableState = TriState::UNKNOWN private
Definition at line 789 of file AP_AHRS.h.
Referenced by set_terrain_hgt_stable().
touchdown_expected
bool AP_AHRS::touchdown_expected private
Definition at line 836 of file AP_AHRS.h.
Referenced by get_touchdown_expected(), set_touchdown_expected(), and update_flags().
touchdown_expected_start_ms
uint32_t AP_AHRS::touchdown_expected_start_ms private
Definition at line 837 of file AP_AHRS.h.
Referenced by set_touchdown_expected(), and update_flags().
var_info
const AP_Param::GroupInfo AP_AHRS::var_info static
Definition at line 54 of file AP_AHRS.h.
velocity_NED
Vector3f AP_AHRS::velocity_NED
Definition at line 986 of file AP_AHRS.h.
velocity_NED_ok
bool AP_AHRS::velocity_NED_ok
Definition at line 987 of file AP_AHRS.h.
wind_estimate
bool AP_AHRS::wind_estimate
Definition at line 960 of file AP_AHRS.h.
Referenced by head_wind(), update_AOA_SSA(), SoaringController::update_cruising(), SoaringController::update_thermalling(), wind_alignment(), and AP_AHRS_View::wind_estimate().
wind_estimate_ok
bool AP_AHRS::wind_estimate_ok
Definition at line 961 of file AP_AHRS.h.
wind_estimation_enabled
bool AP_AHRS::wind_estimation_enabled private
Definition at line 842 of file AP_AHRS.h.
Referenced by get_wind_estimation_enabled(), and set_wind_estimation_enabled().
yaw
float AP_AHRS::yaw private
Definition at line 684 of file AP_AHRS.h.
Referenced by copy_estimates_from_backend_estimates(), get_yaw(), and update_cd_values().
yaw_sensor
int32_t AP_AHRS::yaw_sensor
Definition at line 579 of file AP_AHRS.h.
Referenced by AP_Spektrum_Telem::calc_attandmag(), AP_Frsky_Backend::calc_gps_position(), AP_Frsky_SPort_Passthrough::calc_velandyaw(), AR_AttitudeControl::get_forward_speed(), AP_L1_Control::get_yaw_sensor(), head_wind(), AP_Frsky_D::send(), AP_OABendyRuler::update(), update_cd_values(), AP_L1_Control::update_heading_hold(), and AP_L1_Control::update_level_flight().
The documentation for this class was generated from the following files:
libraries/AP_AHRS/AP_AHRS.h
libraries/AP_AHRS/AP_AHRS.cpp
libraries/AP_AHRS/AP_AHRS_Backend.cpp