APM:Libraries: AP_LTM_Telem Class Reference
AP_LTM_Telem Class Reference
#include <AP_LTM_Telem.h>
Public Member Functions
AP_LTM_Telem ()
CLASS_NO_COPY (AP_LTM_Telem)
void init ()
Private Member Functions
void send_Gframe (void)
void send_Sframe (void)
void send_Aframe (void)
void generate_LTM (void)
void send_LTM (uint8_t lt_packet[], uint8_t lt_packet_size)
void tick (void)
Private Attributes
AP_HAL::UARTDriver * _port
uint8_t _ltm_scheduler
uint32_t _last_frame_ms
Detailed Description
Definition at line 29 of file AP_LTM_Telem.h.
Constructor & Destructor Documentation
AP_LTM_Telem()
AP_LTM_Telem::AP_LTM_Telem () inline
Definition at line 32 of file AP_LTM_Telem.h.
Member Function Documentation
CLASS_NO_COPY()
AP_LTM_Telem::CLASS_NO_COPY (AP_LTM_Telem)
generate_LTM()
void AP_LTM_Telem::generate_LTM (void) private
Definition at line 211 of file AP_LTM_Telem.cpp.
Referenced by tick().
init()
void AP_LTM_Telem::init ()
Definition at line 32 of file AP_LTM_Telem.cpp.
send_Aframe()
void AP_LTM_Telem::send_Aframe (void) private
Definition at line 173 of file AP_LTM_Telem.cpp.
Referenced by generate_LTM().
send_Gframe()
void AP_LTM_Telem::send_Gframe (void) private
Definition at line 64 of file AP_LTM_Telem.cpp.
Referenced by generate_LTM().
send_LTM()
void AP_LTM_Telem::send_LTM (uint8_t lt_packet[], uint8_t lt_packet_size) private
Definition at line 48 of file AP_LTM_Telem.cpp.
Referenced by send_Aframe(), send_Gframe(), and send_Sframe().
send_Sframe()
void AP_LTM_Telem::send_Sframe (void) private
Definition at line 117 of file AP_LTM_Telem.cpp.
Referenced by generate_LTM().
tick()
void AP_LTM_Telem::tick (void) private
Definition at line 227 of file AP_LTM_Telem.cpp.
Referenced by init().
Member Data Documentation
_last_frame_ms
uint32_t AP_LTM_Telem::_last_frame_ms private
Definition at line 44 of file AP_LTM_Telem.h.
Referenced by tick().
_ltm_scheduler
uint8_t AP_LTM_Telem::_ltm_scheduler private
Definition at line 43 of file AP_LTM_Telem.h.
Referenced by generate_LTM(), send_Aframe(), send_Gframe(), and send_Sframe().
_port
AP_HAL::UARTDriver* AP_LTM_Telem::_port private
Definition at line 41 of file AP_LTM_Telem.h.
Referenced by init(), and send_LTM().
The documentation for this class was generated from the following files:
libraries/AP_LTM_Telem/AP_LTM_Telem.h
libraries/AP_LTM_Telem/AP_LTM_Telem.cpp