APM:Libraries: AP_GPS_Backend Class Reference
AP_GPS_Backend Class Reference abstract
#include <GPS_Backend.h>
Public Member Functions
AP_GPS_Backend (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
virtual ~AP_GPS_Backend (void)
virtual bool read ()=0
virtual AP_GPS::GPS_Status highest_supported_status (void)
virtual bool is_configured (void) const
virtual void inject_data (const uint8_t *data, uint16_t len)
virtual void broadcast_configuration_failure_reason (void) const
virtual bool get_lag (float &lag) const
virtual bool is_healthy (void) const
virtual bool logging_healthy (void) const
virtual const char * name () const =0
void broadcast_gps_type () const
virtual void Write_AP_Logger_Log_Startup_messages () const
virtual bool prepare_for_arming (void)
virtual bool get_RTCMV3 (const uint8_t *&bytes, uint16_t &len)
virtual void clear_RTCMV3 (void)
virtual bool get_error_codes (uint32_t &error_codes) const
uint32_t get_last_itow_ms (void) const
bool option_set (const AP_GPS::DriverOptions option) const
Protected Member Functions
void fill_3d_velocity (void)
void velocity_to_speed_course (AP_GPS::GPS_State &s)
void make_gps_time (uint32_t bcd_date, uint32_t bcd_milliseconds)
void _detection_message (char *buffer, uint8_t buflen) const
bool should_log () const
void set_uart_timestamp (uint16_t nbytes)
void check_new_itow (uint32_t itow, uint32_t msg_length)
bool calculate_moving_base_yaw (const float reported_heading_deg, const float reported_distance, const float reported_D)
bool calculate_moving_base_yaw (AP_GPS::GPS_State &interim_state, const float reported_heading_deg, const float reported_distance, const float reported_D)
AP_GPS::GPS_Type get_type () const
virtual void set_pps_desired_freq (uint8_t freq)
void set_alt_amsl_cm (AP_GPS::GPS_State &_state, int32_t alt_amsl_cm)
Protected Attributes
AP_HAL::UARTDriver * port
UART we are attached to.
AP_GPS & gps
access to frontend (for parameters)
AP_GPS::GPS_State & state
public state for this instance
uint64_t _last_pps_time_us
JitterCorrection jitter_correction
uint32_t _last_itow_ms
bool _have_itow
Private Attributes
uint64_t _pseudo_itow
int32_t _pseudo_itow_delta_ms
uint32_t _last_ms
uint32_t _rate_ms
uint32_t _last_rate_ms
uint16_t _rate_counter
Detailed Description
Definition at line 49 of file GPS_Backend.h.
Constructor & Destructor Documentation
AP_GPS_Backend()
AP_GPS_Backend::AP_GPS_Backend (AP_GPS & _gps, AP_GPS::GPS_State & _state, AP_HAL::UARTDriver * _port)
Definition at line 44 of file GPS_Backend.cpp.
~AP_GPS_Backend()
virtual AP_GPS_Backend::~AP_GPS_Backend (void) inline virtual
Definition at line 56 of file GPS_Backend.h.
Member Function Documentation
_detection_message()
void AP_GPS_Backend::_detection_message (char * buffer, uint8_t buflen) const protected
Definition at line 132 of file GPS_Backend.cpp.
Referenced by broadcast_gps_type(), and Write_AP_Logger_Log_Startup_messages().
broadcast_configuration_failure_reason()
virtual void AP_GPS_Backend::broadcast_configuration_failure_reason (void) const inline virtual
Reimplemented in AP_GPS_SBF, and AP_GPS_UBLOX.
Definition at line 78 of file GPS_Backend.h.
Referenced by AP_GPS::broadcast_first_configuration_failure_reason().
broadcast_gps_type()
void AP_GPS_Backend::broadcast_gps_type () const
Definition at line 152 of file GPS_Backend.cpp.
Referenced by AP_GPS::detect_instance().
calculate_moving_base_yaw() [1/2]
bool AP_GPS_Backend::calculate_moving_base_yaw (AP_GPS::GPS_State & interim_state, const float reported_heading_deg, const float reported_distance, const float reported_D) protected
Definition at line 326 of file GPS_Backend.cpp.
calculate_moving_base_yaw() [2/2]
bool AP_GPS_Backend::calculate_moving_base_yaw (const float reported_heading_deg, const float reported_distance, const float reported_D) protected
Definition at line 322 of file GPS_Backend.cpp.
Referenced by AP_GPS_UBLOX::_parse_gps(), AP_GPS_NMEA::_term_complete(), calculate_moving_base_yaw(), and AP_GPS_SBF::process_message().
check_new_itow()
void AP_GPS_Backend::check_new_itow (uint32_t itow, uint32_t msg_length) protected
Definition at line 230 of file GPS_Backend.cpp.
Referenced by AP_GPS_UBLOX::_check_new_itow(), AP_GPS_SBP::_sbp_process_message(), AP_GPS_SBP2::_sbp_process_message(), AP_GPS_NMEA::_term_complete(), AP_GPS_NOVA::process_message(), and AP_GPS_SBF::process_message().
clear_RTCMV3()
virtual void AP_GPS_Backend::clear_RTCMV3 (void) inline virtual
Reimplemented in AP_GPS_UBLOX.
Definition at line 104 of file GPS_Backend.h.
Referenced by AP_GPS::clear_RTCMV3(), and AP_GPS::update_instance().
fill_3d_velocity()
void AP_GPS_Backend::fill_3d_velocity (void) protected
Definition at line 100 of file GPS_Backend.cpp.
Referenced by AP_GPS_SIRF::_parse_gps(), AP_GPS_NMEA::_term_complete(), AP_GPS_NOVA::process_message(), and AP_GPS_GSOF::process_message().
get_error_codes()
virtual bool AP_GPS_Backend::get_error_codes (uint32_t & error_codes) const inline virtual
Reimplemented in AP_GPS_SBF, and AP_GPS_UBLOX.
Definition at line 106 of file GPS_Backend.h.
Referenced by AP_GPS::get_error_codes().
get_lag()
virtual bool AP_GPS_Backend::get_lag (float & lag) const inline virtual
Reimplemented in AP_GPS_NMEA, AP_GPS_SBF, and AP_GPS_UBLOX.
Definition at line 88 of file GPS_Backend.h.
Referenced by AP_GPS::get_lag().
get_last_itow_ms()
uint32_t AP_GPS_Backend::get_last_itow_ms (void) const
Definition at line 89 of file GPS_Backend.cpp.
Referenced by AP_GPS::get_itow(), AP_GPS::last_message_epoch_usec(), and AP_GPS::time_epoch_usec().
get_RTCMV3()
virtual bool AP_GPS_Backend::get_RTCMV3 (const uint8_t *& bytes, uint16_t & len) inline virtual
Reimplemented in AP_GPS_UBLOX.
Definition at line 103 of file GPS_Backend.h.
Referenced by AP_GPS::get_RTCMV3().
get_type()
AP_GPS::GPS_Type AP_GPS_Backend::get_type () const inline protected
Definition at line 160 of file GPS_Backend.h.
Referenced by AP_GPS_SBF::AP_GPS_SBF(), AP_GPS_NMEA::get_lag(), AP_GPS_NMEA::is_healthy(), AP_GPS_SBF::process_message(), AP_GPS_SBF::read(), and AP_GPS_NMEA::send_config().
highest_supported_status()
virtual AP_GPS::GPS_Status AP_GPS_Backend::highest_supported_status (void) inline virtual
Reimplemented in AP_GPS_ERB, AP_GPS_NOVA, AP_GPS_SBF, AP_GPS_SBP, AP_GPS_SBP2, AP_GPS_UBLOX, and AP_GPS_GSOF.
Definition at line 65 of file GPS_Backend.h.
Referenced by AP_GPS::highest_supported_status().
inject_data()
void AP_GPS_Backend::inject_data (const uint8_t * data, uint16_t len) virtual
Reimplemented in AP_GPS_SBP, and AP_GPS_SBP2.
Definition at line 120 of file GPS_Backend.cpp.
Referenced by AP_GPS::inject_data().
is_configured()
virtual bool AP_GPS_Backend::is_configured (void) const inline virtual
Reimplemented in AP_GPS_SBF, and AP_GPS_UBLOX.
Definition at line 67 of file GPS_Backend.h.
is_healthy()
virtual bool AP_GPS_Backend::is_healthy (void) const inline virtual
Reimplemented in AP_GPS_NMEA, AP_GPS_SBF, and AP_GPS_UBLOX.
Definition at line 91 of file GPS_Backend.h.
Referenced by AP_GPS::is_healthy().
logging_healthy()
virtual bool AP_GPS_Backend::logging_healthy (void) const inline virtual
Reimplemented in AP_GPS_SBF.
Definition at line 93 of file GPS_Backend.h.
make_gps_time()
void AP_GPS_Backend::make_gps_time (uint32_t bcd_date, uint32_t bcd_milliseconds) protected
fill in time_week_ms and time_week from BCD date and time components assumes MTK19 millisecond form of bcd_time
Definition at line 58 of file GPS_Backend.cpp.
Referenced by AP_GPS_NMEA::_term_complete().
name()
virtual const char * AP_GPS_Backend::name () const pure virtual
Implemented in AP_GPS_ERB, AP_GPS_GSOF, AP_GPS_NMEA, AP_GPS_NOVA, AP_GPS_SBF, AP_GPS_SBP, AP_GPS_SBP2, AP_GPS_SIRF, and AP_GPS_UBLOX.
Referenced by _detection_message().
option_set()
bool AP_GPS_Backend::option_set (const AP_GPS::DriverOptions option) const inline
Definition at line 112 of file GPS_Backend.h.
Referenced by AP_GPS_UBLOX::_request_next_config(), AP_GPS_SBF::AP_GPS_SBF(), AP_GPS_UBLOX::mb_use_uart2(), AP_GPS_SBF::process_message(), and set_alt_amsl_cm().
prepare_for_arming()
virtual bool AP_GPS_Backend::prepare_for_arming (void) inline virtual
Reimplemented in AP_GPS_SBF.
Definition at line 100 of file GPS_Backend.h.
Referenced by AP_GPS::prepare_for_arming().
read()
virtual bool AP_GPS_Backend::read () pure virtual
Implemented in AP_GPS_ERB, AP_GPS_NMEA, AP_GPS_NOVA, AP_GPS_SBF, AP_GPS_SBP, AP_GPS_SBP2, AP_GPS_SIRF, AP_GPS_UBLOX, and AP_GPS_GSOF.
Referenced by AP_GPS::update_instance().
set_alt_amsl_cm()
void AP_GPS_Backend::set_alt_amsl_cm (AP_GPS::GPS_State & _state, int32_t alt_amsl_cm) protected
Definition at line 456 of file GPS_Backend.cpp.
Referenced by AP_GPS_ERB::_parse_gps(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_SIRF::_parse_gps(), AP_GPS_NMEA::_term_complete(), AP_GPS_NOVA::process_message(), and AP_GPS_SBF::process_message().
set_pps_desired_freq()
virtual void AP_GPS_Backend::set_pps_desired_freq (uint8_t freq) inline protected virtual
Definition at line 164 of file GPS_Backend.h.
Referenced by check_new_itow().
set_uart_timestamp()
void AP_GPS_Backend::set_uart_timestamp (uint16_t nbytes) protected
Definition at line 221 of file GPS_Backend.cpp.
Referenced by AP_GPS_ERB::_parse_gps(), and AP_GPS_NMEA::_term_complete().
should_log()
bool AP_GPS_Backend::should_log () const protected
Definition at line 168 of file GPS_Backend.cpp.
Referenced by AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_GPS_UBLOX::log_rxm_raw(), and AP_GPS_UBLOX::log_rxm_rawx().
velocity_to_speed_course()
void AP_GPS_Backend::velocity_to_speed_course (AP_GPS::GPS_State & s) protected
Definition at line 113 of file GPS_Backend.cpp.
Referenced by AP_GPS_SBP::_attempt_state_update(), AP_GPS_SBP2::_attempt_state_update(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_NMEA::_term_complete(), and AP_GPS_SBF::process_message().
Write_AP_Logger_Log_Startup_messages()
void AP_GPS_Backend::Write_AP_Logger_Log_Startup_messages () const virtual
Reimplemented in AP_GPS_NMEA, and AP_GPS_UBLOX.
Definition at line 159 of file GPS_Backend.cpp.
Referenced by AP_GPS::Write_AP_Logger_Log_Startup_messages(), AP_GPS_NMEA::Write_AP_Logger_Log_Startup_messages(), and AP_GPS_UBLOX::Write_AP_Logger_Log_Startup_messages().
Member Data Documentation
_have_itow
bool AP_GPS_Backend::_have_itow protected
Definition at line 124 of file GPS_Backend.h.
Referenced by check_new_itow(), and get_last_itow_ms().
_last_itow_ms
uint32_t AP_GPS_Backend::_last_itow_ms protected
Definition at line 123 of file GPS_Backend.h.
Referenced by AP_GPS_NMEA::_term_complete(), check_new_itow(), and get_last_itow_ms().
_last_ms
uint32_t AP_GPS_Backend::_last_ms private
Definition at line 178 of file GPS_Backend.h.
Referenced by check_new_itow().
_last_pps_time_us
uint64_t AP_GPS_Backend::_last_pps_time_us protected
Definition at line 121 of file GPS_Backend.h.
Referenced by check_new_itow().
_last_rate_ms
uint32_t AP_GPS_Backend::_last_rate_ms private
Definition at line 180 of file GPS_Backend.h.
Referenced by check_new_itow().
_pseudo_itow
uint64_t AP_GPS_Backend::_pseudo_itow private
Definition at line 176 of file GPS_Backend.h.
Referenced by check_new_itow(), and get_last_itow_ms().
_pseudo_itow_delta_ms
int32_t AP_GPS_Backend::_pseudo_itow_delta_ms private
Definition at line 177 of file GPS_Backend.h.
Referenced by check_new_itow(), and get_last_itow_ms().
_rate_counter
uint16_t AP_GPS_Backend::_rate_counter private
Definition at line 181 of file GPS_Backend.h.
Referenced by check_new_itow().
_rate_ms
uint32_t AP_GPS_Backend::_rate_ms private
Definition at line 179 of file GPS_Backend.h.
Referenced by check_new_itow().
gps
AP_GPS& AP_GPS_Backend::gps protected
access to frontend (for parameters)
Definition at line 118 of file GPS_Backend.h.
Referenced by AP_GPS_UBLOX::_configure_rate(), _detection_message(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_UBLOX::_request_next_config(), AP_GPS_UBLOX::_verify_rate(), AP_GPS_GSOF::AP_GPS_GSOF(), AP_GPS_NOVA::AP_GPS_NOVA(), AP_GPS_SIRF::AP_GPS_SIRF(), AP_GPS_UBLOX::AP_GPS_UBLOX(), AP_GPS_SBF::broadcast_configuration_failure_reason(), calculate_moving_base_yaw(), check_new_itow(), AP_GPS_UBLOX::get_lag(), get_type(), AP_GPS_SBF::is_configured(), AP_GPS_UBLOX::is_configured(), AP_GPS_UBLOX::is_healthy(), AP_GPS_SBF::logging_healthy(), option_set(), AP_GPS_SBF::parse(), AP_GPS_SBF::prepare_for_arming(), AP_GPS_NOVA::read(), AP_GPS_SBF::read(), AP_GPS_UBLOX::read(), AP_GPS_GSOF::read(), AP_GPS_NMEA::send_config(), and should_log().
jitter_correction
JitterCorrection AP_GPS_Backend::jitter_correction protected
Definition at line 122 of file GPS_Backend.h.
Referenced by check_new_itow().
port
AP_HAL::UARTDriver* AP_GPS_Backend::port protected
UART we are attached to.
Definition at line 117 of file GPS_Backend.h.
Referenced by AP_GPS_UBLOX::_configure_config_set(), AP_GPS_UBLOX::_configure_message_rate(), AP_GPS_UBLOX::_configure_valget(), AP_GPS_UBLOX::_configure_valset(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_UBLOX::_request_next_config(), AP_GPS_UBLOX::_request_port(), AP_GPS_SBP::_sbp_process(), AP_GPS_SBP2::_sbp_process(), AP_GPS_UBLOX::_send_message(), AP_GPS_NOVA::AP_GPS_NOVA(), check_new_itow(), inject_data(), AP_GPS_SBP::inject_data(), AP_GPS_SBP2::inject_data(), AP_GPS_SBF::mount_disk(), AP_GPS_ERB::read(), AP_GPS_NMEA::read(), AP_GPS_NOVA::read(), AP_GPS_SBF::read(), AP_GPS_SIRF::read(), AP_GPS_UBLOX::read(), AP_GPS_GSOF::read(), AP_GPS_GSOF::requestBaud(), AP_GPS_GSOF::requestGSOF(), AP_GPS_NMEA::send_config(), set_uart_timestamp(), and AP_GPS_SBF::unmount_disk().
state
AP_GPS::GPS_State& AP_GPS_Backend::state protected
public state for this instance
Definition at line 119 of file GPS_Backend.h.
Referenced by AP_GPS_SBP::_attempt_state_update(), AP_GPS_SBP2::_attempt_state_update(), AP_GPS_UBLOX::_configure_rate(), AP_GPS_ERB::_detect(), AP_GPS_NMEA::_detect(), AP_GPS_SBP2::_detect(), AP_GPS_SBP::_detect(), AP_GPS_SIRF::_detect(), AP_GPS_UBLOX::_detect(), _detection_message(), AP_GPS_NMEA::_have_new_message(), AP_GPS_ERB::_parse_gps(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_SIRF::_parse_gps(), AP_GPS_UBLOX::_save_cfg(), AP_GPS_NMEA::_term_complete(), AP_GPS_Backend(), AP_GPS_GSOF::AP_GPS_GSOF(), AP_GPS_SBF::AP_GPS_SBF(), AP_GPS_SBP::AP_GPS_SBP(), AP_GPS_SIRF::AP_GPS_SIRF(), AP_GPS_UBLOX::AP_GPS_UBLOX(), AP_GPS_SBF::broadcast_configuration_failure_reason(), AP_GPS_UBLOX::broadcast_configuration_failure_reason(), calculate_moving_base_yaw(), calculate_moving_base_yaw(), check_new_itow(), fill_3d_velocity(), get_last_itow_ms(), get_type(), inject_data(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), make_gps_time(), AP_GPS_SBF::prepare_for_arming(), AP_GPS_NOVA::process_message(), AP_GPS_SBF::process_message(), AP_GPS_GSOF::process_message(), AP_GPS_SBF::read(), AP_GPS_GSOF::read(), AP_GPS_NMEA::send_config(), set_uart_timestamp(), AP_GPS_NMEA::Write_AP_Logger_Log_Startup_messages(), and AP_GPS_UBLOX::Write_AP_Logger_Log_Startup_messages().
The documentation for this class was generated from the following files:
libraries/AP_GPS/GPS_Backend.h
libraries/AP_GPS/GPS_Backend.cpp