APM:Libraries: SITL::CRRCSim Class Reference
SITL::CRRCSim Class Reference
#include <SIM_CRRCSim.h>
Classes
struct fdm_packet
struct servo_packet
Public Member Functions
CRRCSim (const char *frame_str)
void update (const struct sitl_input &input) override
Static Public Member Functions
static Aircraft * create (const char *frame_str)
Private Member Functions
void send_servos_heli (const struct sitl_input &input)
void send_servos_fixed_wing (const struct sitl_input &input)
void recv_fdm (const struct sitl_input &input)
void send_servos (const struct sitl_input &input)
Private Attributes
bool heli_servos
double last_timestamp
SocketAPM_native sock
Detailed Description
Definition at line 38 of file SIM_CRRCSim.h.
Constructor & Destructor Documentation
CRRCSim()
SITL::CRRCSim::CRRCSim (const char * frame_str)
Definition at line 31 of file SIM_CRRCSim.cpp.
Referenced by create().
Member Function Documentation
create()
static Aircraft * SITL::CRRCSim::create (const char * frame_str) inline static
Definition at line 46 of file SIM_CRRCSim.h.
recv_fdm()
void SITL::CRRCSim::recv_fdm (const struct sitl_input & input) private
Definition at line 108 of file SIM_CRRCSim.cpp.
Referenced by update().
send_servos()
void SITL::CRRCSim::send_servos (const struct sitl_input & input) private
Definition at line 95 of file SIM_CRRCSim.cpp.
Referenced by recv_fdm(), and update().
send_servos_fixed_wing()
void SITL::CRRCSim::send_servos_fixed_wing (const struct sitl_input & input) private
Definition at line 75 of file SIM_CRRCSim.cpp.
Referenced by send_servos().
send_servos_heli()
void SITL::CRRCSim::send_servos_heli (const struct sitl_input & input) private
Definition at line 49 of file SIM_CRRCSim.cpp.
Referenced by send_servos().
update()
void SITL::CRRCSim::update (const struct sitl_input & input) override
Definition at line 147 of file SIM_CRRCSim.cpp.
Member Data Documentation
heli_servos
bool SITL::CRRCSim::heli_servos private
Definition at line 82 of file SIM_CRRCSim.h.
Referenced by CRRCSim(), and send_servos().
last_timestamp
double SITL::CRRCSim::last_timestamp private
Definition at line 83 of file SIM_CRRCSim.h.
Referenced by recv_fdm().
sock
SocketAPM_native SITL::CRRCSim::sock private
Definition at line 84 of file SIM_CRRCSim.h.
Referenced by CRRCSim(), recv_fdm(), send_servos_fixed_wing(), and send_servos_heli().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_CRRCSim.h
libraries/SITL/SIM_CRRCSim.cpp