APM:Libraries: Linux::RCOutput_AeroIO Class Reference
Linux::RCOutput_AeroIO Class Reference
#include <RCOutput_AeroIO.h>
Public Member Functions
RCOutput_AeroIO ()
~RCOutput_AeroIO ()
void init () override
void enable_ch (uint8_t ch) override
void disable_ch (uint8_t ch) override
void set_freq (uint32_t chmask, uint16_t freq_hz) override
uint16_t get_freq (uint8_t ch) override
void write (uint8_t ch, uint16_t period_us) override
void cork () override
void push () override
uint16_t read (uint8_t ch) override
void read (uint16_t *period_us, uint8_t len) override
Public Member Functions inherited from AP_HAL::RCOutput
virtual void set_reversible_mask (uint32_t chanmask)
virtual void set_reversed_mask (uint32_t chanmask)
virtual uint32_t get_reversed_mask ()
virtual void update_channel_masks ()
virtual void disable_channel_mask_updates ()
virtual void enable_channel_mask_updates ()
virtual uint16_t read_last_sent (uint8_t chan)
virtual void read_last_sent (uint16_t *period_us, uint8_t len)
virtual void set_failsafe_pwm (uint32_t chmask, uint16_t period_us)
virtual bool force_safety_on (void)
virtual void force_safety_off (void)
void set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm)
float scale_esc_to_unity (uint16_t pwm) const
virtual uint16_t get_erpm (uint8_t chan) const
virtual float get_erpm_error_rate (uint8_t chan) const
virtual bool new_erpm ()
virtual uint32_t read_erpm (uint16_t *erpm, uint8_t len)
virtual bool enable_px4io_sbus_out (uint16_t rate_hz)
virtual void timer_tick (void)
virtual bool serial_setup_output (uint8_t chan, uint32_t baudrate, uint32_t chanmask)
virtual bool serial_write_bytes (const uint8_t *bytes, uint16_t len)
virtual uint16_t serial_read_bytes (uint8_t *buf, uint16_t len)
virtual void serial_end (void)
virtual void set_output_mode (uint32_t mask, enum output_mode mode)
virtual enum output_mode get_output_mode (uint32_t &mask)
virtual bool get_output_mode_banner (char banner_msg[], uint8_t banner_msg_len) const
virtual uint32_t get_disabled_channels (uint32_t digital_mask)
virtual void set_default_rate (uint16_t rate_hz)
virtual void set_telem_request_mask (uint32_t mask)
virtual void set_bidir_dshot_mask (uint32_t mask)
virtual void set_active_escs_mask (uint32_t mask)
virtual void set_dshot_rate (uint8_t dshot_rate, uint16_t loop_rate_hz)
virtual void set_dshot_period (uint32_t period_us, uint8_t dshot_rate)
virtual uint32_t get_dshot_period_us () const
virtual void set_dshot_esc_type (DshotEscType esc_type)
virtual DshotEscType get_dshot_esc_type () const
virtual void send_dshot_command (uint8_t command, uint8_t chan=ALL_CHANNELS, uint32_t command_timeout_ms=0, uint16_t repeat_count=10, bool priority=false)
virtual void set_motor_poles (uint8_t poles)
virtual bool set_serial_led_num_LEDs (const uint16_t chan, uint8_t num_leds, output_mode mode=MODE_PWM_NONE, uint32_t clock_mask=0)
virtual bool set_serial_led_rgb_data (const uint16_t chan, int8_t led, uint8_t red, uint8_t green, uint8_t blue)
virtual bool serial_led_send (const uint16_t chan)
virtual void timer_info (ExpandingString &str)
virtual bool supports_gpio ()
virtual void write_gpio (uint8_t chan, bool active)
Private Member Functions
bool _hw_write (uint16_t address, uint16_t data)
uint16_t _hw_read (uint16_t address)
Static Private Member Functions
static uint16_t _usec_to_hw (uint16_t freq, uint16_t usec)
static uint16_t _hw_to_usec (uint16_t freq, uint16_t hw_val)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _spi
uint16_t * _freq_buffer
uint16_t * _duty_buffer
uint32_t _pending_duty_write_mask = 0
uint32_t _pending_freq_write_mask = 0
bool _corking = false
Additional Inherited Members
Public Types inherited from AP_HAL::RCOutput
enum output_mode {
MODE_PWM_NONE , MODE_PWM_NORMAL , MODE_PWM_ONESHOT , MODE_PWM_ONESHOT125 ,
MODE_PWM_BRUSHED , MODE_PWM_DSHOT150 , MODE_PWM_DSHOT300 , MODE_PWM_DSHOT600 ,
MODE_PWM_DSHOT1200 , MODE_NEOPIXEL , MODE_PROFILED , MODE_NEOPIXELRGB
}
enum BLHeliDshotCommand : uint8_t {
DSHOT_RESET = 0 , DSHOT_BEEP1 = 1 , DSHOT_BEEP2 = 2 , DSHOT_BEEP3 = 3 ,
DSHOT_BEEP4 = 4 , DSHOT_BEEP5 = 5 , DSHOT_ESC_INFO = 6 , DSHOT_ROTATE = 7 ,
DSHOT_ROTATE_ALTERNATE = 8 , DSHOT_3D_OFF = 9 , DSHOT_3D_ON = 10 , DSHOT_SAVE = 12 ,
DSHOT_EXTENDED_TELEMETRY_ENABLE = 13 , DSHOT_EXTENDED_TELEMETRY_DISABLE = 14 , DSHOT_NORMAL = 20 , DSHOT_REVERSE = 21 ,
DSHOT_LED0_ON = 22 , DSHOT_LED1_ON = 23 , DSHOT_LED2_ON = 24 , DSHOT_LED3_ON = 25 ,
DSHOT_LED0_OFF = 26 , DSHOT_LED1_OFF = 27 , DSHOT_LED2_OFF = 28 , DSHOT_LED3_OFF = 29
}
enum DshotEscType {
DSHOT_ESC_NONE = 0 , DSHOT_ESC_BLHELI = 1 , DSHOT_ESC_BLHELI_S = 2 , DSHOT_ESC_BLHELI_EDT = 3 ,
DSHOT_ESC_BLHELI_EDT_S = 4
}
Static Public Member Functions inherited from AP_HAL::RCOutput
static bool is_dshot_protocol (const enum output_mode mode)
static bool is_led_protocol (const enum output_mode mode)
static uint32_t calculate_bitrate_prescaler (uint32_t timer_clock, uint32_t target_frequency, bool at_least_freq=false)
Public Attributes inherited from AP_HAL::RCOutput
const uint8_t DSHOT_ZERO_THROTTLE = 48
Static Public Attributes inherited from AP_HAL::RCOutput
static const uint32_t ALL_CHANNELS = 255
static constexpr uint32_t DSHOT_BIT_WIDTH_TICKS_DEFAULT = 8
static constexpr uint32_t DSHOT_BIT_0_TICKS_DEFAULT = 3
static constexpr uint32_t DSHOT_BIT_1_TICKS_DEFAULT = 6
static constexpr uint32_t DSHOT_BIT_WIDTH_TICKS_S = 11
static constexpr uint32_t DSHOT_BIT_0_TICKS_S = 4
static constexpr uint32_t DSHOT_BIT_1_TICKS_S = 8
static uint32_t DSHOT_BIT_WIDTH_TICKS = DSHOT_BIT_WIDTH_TICKS_DEFAULT
static uint32_t DSHOT_BIT_0_TICKS = DSHOT_BIT_0_TICKS_DEFAULT
static uint32_t DSHOT_BIT_1_TICKS = DSHOT_BIT_1_TICKS_DEFAULT
static constexpr uint32_t NEOP_BIT_WIDTH_TICKS = 8
static constexpr uint32_t NEOP_BIT_0_TICKS = 3
static constexpr uint32_t NEOP_BIT_1_TICKS = 6
static constexpr uint32_t PROFI_BIT_0_TICKS = 7
static constexpr uint32_t PROFI_BIT_1_TICKS = 14
static constexpr uint32_t PROFI_BIT_WIDTH_TICKS = 20
static constexpr uint32_t LED_OUTPUT_PERIOD_US = 10000
Protected Member Functions inherited from AP_HAL::RCOutput
void append_to_banner (char banner_msg[], uint8_t banner_msg_len, output_mode out_mode, uint8_t low_ch, uint8_t high_ch) const
const char * get_output_mode_string (enum output_mode out_mode) const
Protected Attributes inherited from AP_HAL::RCOutput
uint16_t _esc_pwm_min
uint16_t _esc_pwm_max
Detailed Description
Definition at line 24 of file RCOutput_AeroIO.h.
Constructor & Destructor Documentation
RCOutput_AeroIO()
RCOutput_AeroIO::RCOutput_AeroIO ()
Definition at line 96 of file RCOutput_AeroIO.cpp.
~RCOutput_AeroIO()
RCOutput_AeroIO::~RCOutput_AeroIO ()
Definition at line 102 of file RCOutput_AeroIO.cpp.
Member Function Documentation
_hw_read()
uint16_t RCOutput_AeroIO::_hw_read (uint16_t address) private
Low-level spi read
@address register address
Return: value read from @address
Definition at line 243 of file RCOutput_AeroIO.cpp.
Referenced by read().
_hw_to_usec()
uint16_t RCOutput_AeroIO::_hw_to_usec (uint16_t freq, uint16_t hw_val) static private
Convert from hw units, 16bits percentage of the frequency, to time in s
@freq Frequency @hw_val 16b percentage
Definition at line 282 of file RCOutput_AeroIO.cpp.
Referenced by read().
_hw_write()
bool RCOutput_AeroIO::_hw_write (uint16_t address, uint16_t data) private
Low-level spi write
@address register address @data value to be written
Return: true on success, false otherwise
Definition at line 226 of file RCOutput_AeroIO.cpp.
Referenced by push().
_usec_to_hw()
uint16_t RCOutput_AeroIO::_usec_to_hw (uint16_t freq, uint16_t usec) static private
Convert from s to hw units, 16bits percentage of the frequency, where 0xFFFF is 1/Freq seconds in high
@freq Frequency @usec Time in seconds
Return: conversion from s in a specific frequency to 16bits
Definition at line 275 of file RCOutput_AeroIO.cpp.
Referenced by push().
cork()
void RCOutput_AeroIO::cork (void) override virtual
Implements AP_HAL::RCOutput.
Definition at line 180 of file RCOutput_AeroIO.cpp.
Referenced by init().
disable_ch()
void RCOutput_AeroIO::disable_ch (uint8_t ch) override virtual
Disable channel (0 of duty cycle)
Implements AP_HAL::RCOutput.
Definition at line 158 of file RCOutput_AeroIO.cpp.
enable_ch()
void RCOutput_AeroIO::enable_ch (uint8_t ch) override virtual
Enable channel
Implements AP_HAL::RCOutput.
Definition at line 148 of file RCOutput_AeroIO.cpp.
get_freq()
uint16_t RCOutput_AeroIO::get_freq (uint8_t ch) override virtual
Get frequency of channel
@ch channel
Return: frequency of this channel
Implements AP_HAL::RCOutput.
Definition at line 140 of file RCOutput_AeroIO.cpp.
init()
void RCOutput_AeroIO::init () override virtual
Implements AP_HAL::RCOutput.
Definition at line 108 of file RCOutput_AeroIO.cpp.
push()
void RCOutput_AeroIO::push (void) override virtual
Implements AP_HAL::RCOutput.
Definition at line 185 of file RCOutput_AeroIO.cpp.
Referenced by disable_ch(), enable_ch(), init(), set_freq(), and write().
read() [1/2]
void RCOutput_AeroIO::read (uint16_t * period_us, uint8_t len) override virtual
Set @period_us with the values in s of each channel
@period_us vector that will be filled with duty cycle periods of each channel @len size of period_us vector
Implements AP_HAL::RCOutput.
Definition at line 219 of file RCOutput_AeroIO.cpp.
read() [2/2]
uint16_t RCOutput_AeroIO::read (uint8_t ch) override virtual
Get period of the duty cycle in s
Implements AP_HAL::RCOutput.
Definition at line 207 of file RCOutput_AeroIO.cpp.
Referenced by read().
set_freq()
void RCOutput_AeroIO::set_freq (uint32_t chmask, uint16_t freq_hz) override virtual
Set all channels in the same frequency
@chmask Bitmask @freq_hz Frequency
Implements AP_HAL::RCOutput.
Definition at line 124 of file RCOutput_AeroIO.cpp.
Referenced by init().
write()
void RCOutput_AeroIO::write (uint8_t ch, uint16_t period_us) override virtual
Set period in s
@ch channel @period_us time in s
Implements AP_HAL::RCOutput.
Definition at line 169 of file RCOutput_AeroIO.cpp.
Referenced by init().
Member Data Documentation
_corking
bool Linux::RCOutput_AeroIO::_corking = false private
If true the push must be called to perform the writing, otherwise will be not necessary.
Definition at line 152 of file RCOutput_AeroIO.h.
Referenced by cork(), disable_ch(), enable_ch(), push(), set_freq(), and write().
_duty_buffer
uint16_t* Linux::RCOutput_AeroIO::_duty_buffer private
Duty cycle buffer of last written values
Definition at line 134 of file RCOutput_AeroIO.h.
Referenced by disable_ch(), push(), read(), write(), and ~RCOutput_AeroIO().
_freq_buffer
uint16_t* Linux::RCOutput_AeroIO::_freq_buffer private
Frequency buffer of last written values
Definition at line 129 of file RCOutput_AeroIO.h.
Referenced by get_freq(), push(), read(), set_freq(), and ~RCOutput_AeroIO().
_pending_duty_write_mask
uint32_t Linux::RCOutput_AeroIO::_pending_duty_write_mask = 0 private
Save information about the channel that will be write in the next @RCOutput_AeroIOpush call.
0b...101 1st channel (Pending operation) 2nd Channel (No pending operation) 3rd Channel (Pending operation)
Definition at line 145 of file RCOutput_AeroIO.h.
Referenced by disable_ch(), enable_ch(), push(), and write().
_pending_freq_write_mask
uint32_t Linux::RCOutput_AeroIO::_pending_freq_write_mask = 0 private
Definition at line 146 of file RCOutput_AeroIO.h.
Referenced by push(), and set_freq().
_spi
AP_HAL::OwnPtr<AP_HAL::Device> Linux::RCOutput_AeroIO::_spi private
Definition at line 124 of file RCOutput_AeroIO.h.
Referenced by _hw_read(), _hw_write(), and init().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/RCOutput_AeroIO.h
libraries/AP_HAL_Linux/RCOutput_AeroIO.cpp