APM:Libraries: AC_P_2D Class Reference
AC_P_2D Class Reference
2-axis P controller
#include <AC_P_2D.h>
Public Member Functions
AC_P_2D (float initial_p)
CLASS_NO_COPY (AC_P_2D)
Vector2f update_all (postype_t &target_x, postype_t &target_y, const Vector2f &measurement) WARN_IF_UNUSED
Vector2f update_all (postype_t &target_x, postype_t &target_y, const Vector3f &measurement) WARN_IF_UNUSED
void set_limits (float output_max, float D_Out_max=0.0f, float D2_Out_max=0.0f)
void set_error_max (float error_max)
float get_error_max ()
void save_gains ()
AP_Float & kP () WARN_IF_UNUSED
const AP_Float & kP () const WARN_IF_UNUSED
const Vector2f & get_error () const
void kP (float v)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
AP_Float _kp
Vector2f _error
float _error_max
float _D1_max
const float default_kp
Detailed Description
2-axis P controller
Definition at line 11 of file AC_P_2D.h.
Constructor & Destructor Documentation
AC_P_2D()
AC_P_2D::AC_P_2D (float initial_p)
Definition at line 16 of file AC_P_2D.cpp.
Member Function Documentation
CLASS_NO_COPY()
AC_P_2D::CLASS_NO_COPY (AC_P_2D)
get_error()
const Vector2f & AC_P_2D::get_error () const inline
Definition at line 44 of file AC_P_2D.h.
Referenced by AC_PosControl::handle_ekf_xy_reset(), AR_PosControl::handle_ekf_xy_reset(), AC_PosControl::input_accel_xy(), AC_PosControl::input_pos_vel_accel_xy(), AC_PosControl::input_pos_xyz(), and AC_PosControl::input_vel_accel_xy().
get_error_max()
float AC_P_2D::get_error_max () inline
Definition at line 36 of file AC_P_2D.h.
Referenced by AC_PosControl::get_pos_error_max_xy_cm().
kP() [1/3]
const AP_Float & AC_P_2D::kP () const inline
Definition at line 43 of file AC_P_2D.h.
kP() [2/3]
AP_Float & AC_P_2D::kP () inline
Definition at line 42 of file AC_P_2D.h.
Referenced by AR_WPNav::advance_wp_target_along_track(), AC_WPNav::advance_wp_target_along_track(), AC_Loiter::calc_desired_velocity(), AC_PosControl::get_stopping_point_xy_cm(), and AR_PosControl::update().
kP() [3/3]
void AC_P_2D::kP (float v) inline
Definition at line 47 of file AC_P_2D.h.
save_gains()
void AC_P_2D::save_gains () inline
Definition at line 39 of file AC_P_2D.h.
set_error_max()
void AC_P_2D::set_error_max (float error_max)
Definition at line 63 of file AC_P_2D.cpp.
Referenced by AC_PosControl::set_pos_error_max_xy_cm().
set_limits()
void AC_P_2D::set_limits (float output_max, float D_Out_max = 0.0f, float D2_Out_max = 0.0f)
Definition at line 42 of file AC_P_2D.cpp.
Referenced by AC_PosControl::set_correction_speed_accel_xy(), and AR_PosControl::set_limits().
update_all() [1/2]
Vector2f AC_P_2D::update_all (postype_t & target_x, postype_t & target_y, const Vector2f & measurement)
Definition at line 24 of file AC_P_2D.cpp.
Referenced by AR_PosControl::update(), update_all(), and AC_PosControl::update_xy_controller().
update_all() [2/2]
Vector2f AC_P_2D::update_all (postype_t & target_x, postype_t & target_y, const Vector3f & measurement) inline
Definition at line 24 of file AC_P_2D.h.
Member Data Documentation
_D1_max
float AC_P_2D::_D1_max private
Definition at line 60 of file AC_P_2D.h.
Referenced by set_limits(), and update_all().
_error
Vector2f AC_P_2D::_error private
Definition at line 58 of file AC_P_2D.h.
Referenced by get_error(), and update_all().
_error_max
float AC_P_2D::_error_max private
Definition at line 59 of file AC_P_2D.h.
Referenced by get_error_max(), set_error_max(), set_limits(), and update_all().
_kp
AP_Float AC_P_2D::_kp private
Definition at line 55 of file AC_P_2D.h.
Referenced by kP(), kP(), kP(), save_gains(), set_limits(), and update_all().
default_kp
const float AC_P_2D::default_kp private
Definition at line 62 of file AC_P_2D.h.
var_info
const AP_Param::GroupInfo AC_P_2D::var_info static
Initial value:
= {
    AP_GROUPINFO_FLAGS_DEFAULT_POINTER("P",    0, AC_P_2D, _kp, default_kp),
    AP_GROUPEND
}
Definition at line 7 of file AC_P_2D.h.
The documentation for this class was generated from the following files:
libraries/AC_PID/AC_P_2D.h
libraries/AC_PID/AC_P_2D.cpp