APM:Libraries: Compass Class Reference
Compass Class Reference
#include <AP_Compass.h>
Classes
struct mag_state
Public Types
enum LearnType { LEARN_NONE =0 , LEARN_INTERNAL =1 , LEARN_EKF =2 , LEARN_INFLIGHT =3 }
Public Member Functions
Compass ()
CLASS_NO_COPY (Compass)
void init ()
bool read ()
bool available () const
float calculate_heading (const Matrix3f &dcm_matrix) const
float calculate_heading (const Matrix3f &dcm_matrix, uint8_t i) const
void set_offsets (uint8_t i, const Vector3f &offsets)
void set_and_save_offsets (uint8_t i, const Vector3f &offsets)
void set_and_save_diagonals (uint8_t i, const Vector3f &diagonals)
void set_and_save_offdiagonals (uint8_t i, const Vector3f &diagonals)
void set_and_save_scale_factor (uint8_t i, float scale_factor)
void set_and_save_orientation (uint8_t i, Rotation orientation)
void save_offsets (uint8_t i)
void save_offsets (void)
uint8_t get_count (void) const
uint8_t get_num_enabled (void) const
const Vector3f & get_field (uint8_t i) const
Return the current field as a Vector3f in milligauss.
const Vector3f & get_field (void) const
bool have_scale_factor (uint8_t i) const
Return true if we have set a scale factor for a compass.
void cal_update ()
void per_motor_calibration_start (void)
void per_motor_calibration_update (void)
void per_motor_calibration_end (void)
bool start_calibration_all (bool retry=false, bool autosave=false, float delay_sec=0.0f, bool autoreboot=false)
void cancel_calibration_all ()
bool compass_cal_requires_reboot () const
bool is_calibrating () const
void set_log_bit (uint32_t log_bit)
MAV_RESULT handle_mag_cal_command (const mavlink_command_int_t &packet)
bool send_mag_cal_progress (const class GCS_MAVLINK &link)
bool send_mag_cal_report (const class GCS_MAVLINK &link)
bool consistent () const
bool healthy (uint8_t i) const
Return the health of a compass.
bool healthy (void) const
uint8_t get_healthy_mask () const
const Vector3f & get_offsets (uint8_t i) const
const Vector3f & get_offsets (void) const
const Vector3f & get_diagonals (uint8_t i) const
const Vector3f & get_diagonals (void) const
const Vector3f & get_offdiagonals (uint8_t i) const
const Vector3f & get_offdiagonals (void) const
bool learn_offsets_enabled () const
bool use_for_yaw (uint8_t i) const
return true if the compass should be used for yaw calculations
bool use_for_yaw (void) const
return true if the compass should be used for yaw calculations
void set_declination (float radians, bool save_to_eeprom=true)
float get_declination () const
bool auto_declination_enabled () const
void set_board_orientation (enum Rotation orientation)
enum Rotation get_board_orientation (void) const
void motor_compensation_type (const uint8_t comp_type)
uint8_t get_motor_compensation_type () const
get the motor compensation value.
void set_motor_compensation (uint8_t i, const Vector3f &motor_comp_factor)
const Vector3f & get_motor_compensation (uint8_t i) const
get motor compensation factors as a vector
const Vector3f & get_motor_compensation (void) const
void save_motor_compensation ()
const Vector3f & get_motor_offsets (uint8_t i) const
const Vector3f & get_motor_offsets (void) const
void set_throttle (float thr_pct)
void set_voltage (float voltage)
Set the battery voltage for per-motor compensation.
bool configured (uint8_t i)
bool configured (char *failure_msg, uint8_t failure_msg_len)
uint32_t last_update_usec (void) const
uint32_t last_update_usec (uint8_t i) const
uint32_t last_update_ms (void) const
uint32_t last_update_ms (uint8_t i) const
enum LearnType get_learn_type (void) const
void set_learn_type (enum LearnType type, bool save)
uint16_t get_offsets_max (void) const
uint8_t get_filter_range () const
void force_save_calibration (void)
uint8_t get_first_usable (void) const
Static Public Member Functions
static Compass * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
enum DriverType {
DRIVER_HMC5843 =0 , DRIVER_LSM303D =1 , DRIVER_AK8963 =2 , DRIVER_BMM150 =3 ,
DRIVER_LSM9DS1 =4 , DRIVER_LIS3MDL =5 , DRIVER_AK09916 =6 , DRIVER_IST8310 =7 ,
DRIVER_ICM20948 =8 , DRIVER_MMC3416 =9 , DRIVER_QMC5883L =12 , DRIVER_MAG3110 =14 ,
DRIVER_IST8308 =15 , DRIVER_RM3100 =16 , DRIVER_MMC5XX3 =19
}
enum class Option : uint16_t { CAL_REQUIRE_GPS = (1U<<0) , ALLOW_DRONECAN_AUTO_REPLACEMENT = (1U<<1) }
Private Member Functions
DECLARE_TYPESAFE_INDEX (Priority, uint8_t)
DECLARE_TYPESAFE_INDEX (StateIndex, uint8_t)
bool register_compass (int32_t dev_id, uint8_t &instance)
bool _add_backend (AP_Compass_Backend *backend)
void _probe_external_i2c_compasses (void)
void _detect_backends (void)
void probe_i2c_spi_compasses (void)
void _update_calibration_trampoline ()
bool _accept_calibration (uint8_t i)
bool _accept_calibration_mask (uint8_t mask)
void _cancel_calibration (uint8_t i)
void _cancel_calibration_mask (uint8_t mask)
uint8_t _get_cal_mask ()
bool _start_calibration (uint8_t i, bool retry=false, float delay_sec=0.0f)
bool _start_calibration_mask (uint8_t mask, bool retry=false, bool autosave=false, float delay_sec=0.0f, bool autoreboot=false)
bool _auto_reboot () const
bool _have_i2c_driver (uint8_t bus_num, uint8_t address) const
bool _driver_enabled (enum DriverType driver_type)
StateIndex _get_state_id (Priority priority) const
const struct mag_state & _get_state (Priority priority) const
Priority _get_priority (StateIndex state_id)
void _detect_runtime (void)
void _reorder_compass_params ()
Priority _update_priority_list (int32_t dev_id)
bool is_replacement_mag (uint32_t dev_id)
void remove_unreg_dev_id (uint32_t devid)
void _reset_compass_id ()
bool option_set (Option opt) const
void try_set_initial_location ()
Private Attributes
Priority next_cal_progress_idx [MAVLINK_COMM_NUM_BUFFERS]
Priority next_cal_report_idx [MAVLINK_COMM_NUM_BUFFERS]
bool _compass_cal_autoreboot
bool _cal_requires_reboot
bool _cal_has_run
AP_Compass_Backend * _backends [COMPASS_MAX_BACKEND]
uint8_t _backend_count
AP_Int8 _enabled
uint8_t _compass_count
uint8_t _unreg_compass_count
AP_Int8 _learn
enum Rotation _board_orientation = ROTATION_NONE
AP_Float _declination
AP_Int8 _auto_declination
uint32_t _log_bit = -1
AP_Int8 _motor_comp_type
AP_Int8 _rotate_auto
float _thr
RestrictIDTypeArray< mag_state, COMPASS_MAX_INSTANCES+1, StateIndex > _state
RestrictIDTypeArray< AP_Int8, COMPASS_MAX_INSTANCES, Priority > _use_for_yaw
RestrictIDTypeArray< AP_Int32, COMPASS_MAX_INSTANCES, Priority > _priority_did_stored_list
RestrictIDTypeArray< int32_t, COMPASS_MAX_INSTANCES, Priority > _priority_did_list
AP_Int16 _offset_max
AP_Int16 _options
Compass_PerMotor _per_motor {*this}
AP_Float _calibration_threshold
AP_Int32 _driver_type_mask
AP_Int32 extra_dev_id [COMPASS_MAX_UNREG_DEV]
uint32_t _previously_unreg_mag [COMPASS_MAX_UNREG_DEV]
AP_Int8 _filter_range
CompassLearn * learn
bool learn_allocated
bool _initial_location_set
bool _cal_thread_started
bool init_done
bool suppress_devid_save
uint8_t _first_usable
Static Private Attributes
static Compass * _singleton
Friends
class AP_Compass_Backend
class CompassLearn
Detailed Description
Definition at line 80 of file AP_Compass.h.
Member Enumeration Documentation
DriverType
enum Compass::DriverType private
Enumerator
DRIVER_HMC5843
DRIVER_LSM303D
DRIVER_AK8963
DRIVER_BMM150
DRIVER_LSM9DS1
DRIVER_LIS3MDL
DRIVER_AK09916
DRIVER_IST8310
DRIVER_ICM20948
DRIVER_MMC3416
DRIVER_QMC5883L
DRIVER_MAG3110
DRIVER_IST8308
DRIVER_RM3100
DRIVER_MMC5XX3
Definition at line 430 of file AP_Compass.h.
LearnType
enum Compass::LearnType
Enumerator
LEARN_NONE
LEARN_INTERNAL
LEARN_EKF
LEARN_INFLIGHT
Definition at line 317 of file AP_Compass.h.
Option
enum class Compass::Option : uint16_t strong private
Enumerator
CAL_REQUIRE_GPS
ALLOW_DRONECAN_AUTO_REPLACEMENT
Definition at line 616 of file AP_Compass.h.
Constructor & Destructor Documentation
Compass()
Compass::Compass (void)
Definition at line 693 of file AP_Compass.cpp.
Member Function Documentation
_accept_calibration()
bool Compass::_accept_calibration (uint8_t i) private
_accept_calibration_mask()
bool Compass::_accept_calibration_mask (uint8_t mask) private
_add_backend()
bool Compass::_add_backend (AP_Compass_Backend * backend) private
Definition at line 1033 of file AP_Compass.cpp.
Referenced by _detect_runtime().
_auto_reboot()
bool Compass::_auto_reboot () const inline private
Definition at line 403 of file AP_Compass.h.
_cancel_calibration()
void Compass::_cancel_calibration (uint8_t i) private
_cancel_calibration_mask()
void Compass::_cancel_calibration_mask (uint8_t mask) private
_detect_backends()
void Compass::_detect_backends (void) private
Definition at line 1321 of file AP_Compass.cpp.
Referenced by init().
_detect_runtime()
void Compass::_detect_runtime (void) private
Definition at line 1685 of file AP_Compass.cpp.
Referenced by read().
_driver_enabled()
bool Compass::_driver_enabled (enum DriverType driver_type) private
Definition at line 1051 of file AP_Compass.cpp.
Referenced by _detect_runtime().
_get_cal_mask()
uint8_t Compass::_get_cal_mask () private
_get_priority()
Priority Compass::_get_priority (StateIndex state_id) inline private
Definition at line 586 of file AP_Compass.h.
Referenced by AP_Compass_Backend::publish_raw_field().
_get_state()
const struct mag_state & Compass::_get_state (Priority priority) const inline private
Definition at line 584 of file AP_Compass.h.
Referenced by _reset_compass_id(), configured(), get_diagonals(), get_field(), get_motor_compensation(), get_motor_offsets(), get_offdiagonals(), get_offsets(), healthy(), last_update_ms(), and last_update_usec().
_get_state_id()
Compass::StateIndex Compass::_get_state_id (Priority priority) const private
Definition at line 1016 of file AP_Compass.cpp.
Referenced by _get_state(), configured(), have_scale_factor(), save_motor_compensation(), save_offsets(), set_and_save_diagonals(), set_and_save_offdiagonals(), set_and_save_offsets(), set_and_save_orientation(), set_and_save_scale_factor(), set_motor_compensation(), and set_offsets().
_have_i2c_driver()
bool Compass::_have_i2c_driver (uint8_t bus_num, uint8_t address) const private
Definition at line 1060 of file AP_Compass.cpp.
_probe_external_i2c_compasses()
void Compass::_probe_external_i2c_compasses (void) private
Definition at line 1095 of file AP_Compass.cpp.
Referenced by _detect_backends(), and probe_i2c_spi_compasses().
_reorder_compass_params()
void Compass::_reorder_compass_params () private
Definition at line 896 of file AP_Compass.cpp.
Referenced by init().
_reset_compass_id()
void Compass::_reset_compass_id () private
Definition at line 1656 of file AP_Compass.cpp.
_start_calibration()
bool Compass::_start_calibration (uint8_t i, bool retry = false, float delay_sec = 0.0f) private
_start_calibration_mask()
bool Compass::_start_calibration_mask (uint8_t mask, bool retry = false, bool autosave = false, float delay_sec = 0.0f, bool autoreboot = false) private
_update_calibration_trampoline()
void Compass::_update_calibration_trampoline () private
_update_priority_list()
Compass::Priority Compass::_update_priority_list (int32_t dev_id) private
Definition at line 861 of file AP_Compass.cpp.
Referenced by register_compass().
auto_declination_enabled()
bool Compass::auto_declination_enabled () const inline
Definition at line 239 of file AP_Compass.h.
Referenced by NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), and AP_DAL_Compass::start_frame().
available()
bool Compass::available () const inline
Definition at line 109 of file AP_Compass.h.
Referenced by _detect_runtime(), NavEKF2_core::getMagOffsets(), NavEKF3_core::getMagOffsets(), have_scale_factor(), read(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), AP_DAL_Compass::start_frame(), GCS::update_sensor_status_flags(), and use_for_yaw().
cal_update()
void Compass::cal_update ()
calculate_heading() [1/2]
float Compass::calculate_heading (const Matrix3f & dcm_matrix) const inline
Calculate the tilt-compensated heading_ variables.
Parameters
dcm_matrix The current orientation rotation matrix
Returns
heading in radians
Definition at line 117 of file AP_Compass.h.
Referenced by calculate_heading(), loop(), and loop().
calculate_heading() [2/2]
float Compass::calculate_heading (const Matrix3f & dcm_matrix, uint8_t i) const
Definition at line 1977 of file AP_Compass.cpp.
cancel_calibration_all()
void Compass::cancel_calibration_all ()
Referenced by RC_Channel::do_aux_function().
CLASS_NO_COPY()
Compass::CLASS_NO_COPY (Compass)
compass_cal_requires_reboot()
bool Compass::compass_cal_requires_reboot () const inline
Definition at line 187 of file AP_Compass.h.
Referenced by AP_Arming::compass_checks().
configured() [1/2]
bool Compass::configured (char * failure_msg, uint8_t failure_msg_len)
Definition at line 2079 of file AP_Compass.cpp.
configured() [2/2]
bool Compass::configured (uint8_t i)
Returns True if the compasses have been configured (i.e. offsets saved)
Returns
True if compass has been configured
Definition at line 2034 of file AP_Compass.cpp.
Referenced by AP_Arming::compass_checks(), and configured().
consistent()
bool Compass::consistent () const
Definition at line 2130 of file AP_Compass.cpp.
Referenced by AP_Arming::compass_checks(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), and AP_DAL_Compass::start_frame().
DECLARE_TYPESAFE_INDEX() [1/2]
Compass::DECLARE_TYPESAFE_INDEX (Priority , uint8_t) private
DECLARE_TYPESAFE_INDEX() [2/2]
Compass::DECLARE_TYPESAFE_INDEX (StateIndex , uint8_t) private
force_save_calibration()
void Compass::force_save_calibration (void)
Definition at line 2222 of file AP_Compass.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration().
get_board_orientation()
enum Rotation Compass::get_board_orientation (void) const inline
Definition at line 247 of file AP_Compass.h.
get_count()
uint8_t Compass::get_count (void) const inline
Definition at line 153 of file AP_Compass.h.
Referenced by configured(), configured(), consistent(), get_num_enabled(), loop(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), GCS_MAVLINK::send_raw_imu(), GCS_MAVLINK::send_scaled_imu(), setup(), AP_DAL_Compass::start_frame(), NavEKF2_core::tryChangeCompass(), NavEKF3_core::tryChangeCompass(), NavEKF3_core::update_mag_selection(), and AP_Logger::Write_Compass().
get_declination()
float Compass::get_declination () const
Definition at line 1968 of file AP_Compass.cpp.
Referenced by AP_DAL_Compass::start_frame().
get_diagonals() [1/2]
const Vector3f & Compass::get_diagonals (uint8_t i) const inline
Definition at line 217 of file AP_Compass.h.
get_diagonals() [2/2]
const Vector3f & Compass::get_diagonals (void) const inline
Definition at line 218 of file AP_Compass.h.
Referenced by get_diagonals().
get_field() [1/2]
const Vector3f & Compass::get_field (uint8_t i) const inline
Return the current field as a Vector3f in milligauss.
Definition at line 159 of file AP_Compass.h.
Referenced by AP_Spektrum_Telem::calc_attandmag(), Compass_PerMotor::calibration_start(), Compass_PerMotor::calibration_update(), AP_Arming::compass_checks(), loop(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), GCS_MAVLINK::send_raw_imu(), GCS_MAVLINK::send_scaled_imu(), AP_DAL_Compass::start_frame(), and AP_Logger::Write_Compass_instance().
get_field() [2/2]
const Vector3f & Compass::get_field (void) const inline
Definition at line 160 of file AP_Compass.h.
Referenced by calculate_heading(), consistent(), and get_field().
get_filter_range()
uint8_t Compass::get_filter_range () const inline
Definition at line 343 of file AP_Compass.h.
Referenced by AP_Compass_Backend::field_ok().
get_first_usable()
uint8_t Compass::get_first_usable (void) const inline
Definition at line 366 of file AP_Compass.h.
Referenced by AP_DAL_Compass::start_frame().
get_healthy_mask()
uint8_t Compass::get_healthy_mask () const
Definition at line 1783 of file AP_Compass.cpp.
get_learn_type()
enum LearnType Compass::get_learn_type (void) const inline
Definition at line 325 of file AP_Compass.h.
get_motor_compensation() [1/2]
const Vector3f & Compass::get_motor_compensation (uint8_t i) const inline
get motor compensation factors as a vector
Definition at line 270 of file AP_Compass.h.
get_motor_compensation() [2/2]
const Vector3f & Compass::get_motor_compensation (void) const inline
Definition at line 271 of file AP_Compass.h.
Referenced by get_motor_compensation().
get_motor_compensation_type()
uint8_t Compass::get_motor_compensation_type () const inline
get the motor compensation value.
Definition at line 258 of file AP_Compass.h.
get_motor_offsets() [1/2]
const Vector3f & Compass::get_motor_offsets (uint8_t i) const inline
Returns the current motor compensation offset values
Returns
The current compass offsets in milligauss.
Definition at line 283 of file AP_Compass.h.
Referenced by AP_Logger::Write_Compass_instance().
get_motor_offsets() [2/2]
const Vector3f & Compass::get_motor_offsets (void) const inline
Definition at line 284 of file AP_Compass.h.
Referenced by get_motor_offsets().
get_num_enabled()
uint8_t Compass::get_num_enabled (void) const
Definition at line 1943 of file AP_Compass.cpp.
Referenced by AP_DAL_Compass::start_frame().
get_offdiagonals() [1/2]
const Vector3f & Compass::get_offdiagonals (uint8_t i) const inline
Definition at line 220 of file AP_Compass.h.
get_offdiagonals() [2/2]
const Vector3f & Compass::get_offdiagonals (void) const inline
Definition at line 221 of file AP_Compass.h.
Referenced by get_offdiagonals().
get_offsets() [1/2]
const Vector3f & Compass::get_offsets (uint8_t i) const inline
Returns the current offset values
Returns
The current compass offsets in milligauss.
Definition at line 213 of file AP_Compass.h.
Referenced by AP_Arming::compass_checks(), NavEKF2_core::getMagOffsets(), NavEKF3_core::getMagOffsets(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), AP_DAL_Compass::start_frame(), and AP_Logger::Write_Compass_instance().
get_offsets() [2/2]
const Vector3f & Compass::get_offsets (void) const inline
Definition at line 214 of file AP_Compass.h.
Referenced by configured(), and get_offsets().
get_offsets_max()
uint16_t Compass::get_offsets_max (void) const inline
Definition at line 339 of file AP_Compass.h.
Referenced by AP_Arming::compass_checks().
get_singleton()
static Compass * Compass::get_singleton () inline static
Definition at line 90 of file AP_Compass.h.
Referenced by AP::compass().
handle_mag_cal_command()
MAV_RESULT Compass::handle_mag_cal_command (const mavlink_command_int_t & packet)
have_scale_factor()
bool Compass::have_scale_factor (uint8_t i) const
Return true if we have set a scale factor for a compass.
Definition at line 2177 of file AP_Compass.cpp.
Referenced by AP_Compass_Backend::correct_field(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), and AP_DAL_Compass::start_frame().
healthy() [1/2]
bool Compass::healthy (uint8_t i) const
Return the health of a compass.
Definition at line 2169 of file AP_Compass.cpp.
Referenced by AP_Arming::compass_checks(), NavEKF2_core::getMagOffsets(), NavEKF3_core::getMagOffsets(), loop(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), AP_DAL_Compass::start_frame(), NavEKF2_core::tryChangeCompass(), NavEKF3_core::tryChangeCompass(), NavEKF3_core::update_mag_selection(), GCS::update_sensor_status_flags(), and AP_Logger::Write_Compass_instance().
healthy() [2/2]
bool Compass::healthy (void) const inline
Definition at line 206 of file AP_Compass.h.
Referenced by get_healthy_mask(), healthy(), read(), and use_for_yaw().
init()
void Compass::init ()
Initialize the compass device.
Returns
True if the compass was initialized OK, false if it was not found or is not functioning.
Definition at line 707 of file AP_Compass.cpp.
Referenced by setup(), and setup().
is_calibrating()
bool Compass::is_calibrating () const
Referenced by AP_Arming::compass_checks().
is_replacement_mag()
bool Compass::is_replacement_mag (uint32_t dev_id) private
Definition at line 1611 of file AP_Compass.cpp.
last_update_ms() [1/2]
uint32_t Compass::last_update_ms (uint8_t i) const inline
Definition at line 313 of file AP_Compass.h.
last_update_ms() [2/2]
uint32_t Compass::last_update_ms (void) const inline
Definition at line 312 of file AP_Compass.h.
Referenced by last_update_ms().
last_update_usec() [1/2]
uint32_t Compass::last_update_usec (uint8_t i) const inline
Definition at line 310 of file AP_Compass.h.
last_update_usec() [2/2]
uint32_t Compass::last_update_usec (void) const inline
Definition at line 309 of file AP_Compass.h.
Referenced by last_update_usec(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), AP_DAL_Compass::start_frame(), and AP_Logger::Write_Compass_instance().
learn_offsets_enabled()
bool Compass::learn_offsets_enabled () const inline
Definition at line 225 of file AP_Compass.h.
Referenced by AP_Arming::compass_checks(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), and AP_DAL_Compass::start_frame().
motor_compensation_type()
void Compass::motor_compensation_type (const uint8_t comp_type)
Set the motor compensation type
Parameters
comp_type 0 = disabled, 1 = enabled use throttle, 2 = enabled use current
Definition at line 2119 of file AP_Compass.cpp.
option_set()
bool Compass::option_set (Option opt) const inline private
Definition at line 620 of file AP_Compass.h.
per_motor_calibration_end()
void Compass::per_motor_calibration_end (void) inline
Definition at line 176 of file AP_Compass.h.
per_motor_calibration_start()
void Compass::per_motor_calibration_start (void) inline
Definition at line 170 of file AP_Compass.h.
per_motor_calibration_update()
void Compass::per_motor_calibration_update (void) inline
Definition at line 173 of file AP_Compass.h.
probe_i2c_spi_compasses()
void Compass::probe_i2c_spi_compasses (void) private
Definition at line 1377 of file AP_Compass.cpp.
Referenced by _detect_backends().
read()
bool Compass::read (void)
Read the compass and update the mag_ variables.
Definition at line 1715 of file AP_Compass.cpp.
Referenced by Compass_PerMotor::calibration_start(), init(), and loop().
register_compass()
bool Compass::register_compass (int32_t dev_id, uint8_t & instance) private
Register a new compas driver, allocating an instance number
Parameters
dev_id Dev ID of compass to register against
Returns
instance number saved against the dev id or first available empty instance number
Definition at line 938 of file AP_Compass.cpp.
Referenced by AP_Compass_Backend::register_compass().
remove_unreg_dev_id()
void Compass::remove_unreg_dev_id (uint32_t devid) private
Definition at line 1637 of file AP_Compass.cpp.
save_motor_compensation()
void Compass::save_motor_compensation ()
Saves the current motor compensation x/y/z values.
This should be invoked periodically to save the offset values calculated by the motor compensation auto learning
Definition at line 1883 of file AP_Compass.cpp.
save_offsets() [1/2]
void Compass::save_offsets (uint8_t i)
Saves the current offset x/y/z values for one or all compasses
Parameters
i compass instance
This should be invoked periodically to save the offset values maintained by ::learn_offsets.
Definition at line 1847 of file AP_Compass.cpp.
save_offsets() [2/2]
void Compass::save_offsets (void)
Definition at line 1866 of file AP_Compass.cpp.
Referenced by save_offsets(), and set_and_save_offsets().
send_mag_cal_progress()
bool Compass::send_mag_cal_progress (const class GCS_MAVLINK & link)
Referenced by GCS_MAVLINK::try_send_message().
send_mag_cal_report()
bool Compass::send_mag_cal_report (const class GCS_MAVLINK & link)
Referenced by GCS_MAVLINK::try_send_message().
set_and_save_diagonals()
void Compass::set_and_save_diagonals (uint8_t i, const Vector3f & diagonals)
Definition at line 1817 of file AP_Compass.cpp.
set_and_save_offdiagonals()
void Compass::set_and_save_offdiagonals (uint8_t i, const Vector3f & diagonals)
Definition at line 1827 of file AP_Compass.cpp.
set_and_save_offsets()
void Compass::set_and_save_offsets (uint8_t i, const Vector3f & offsets)
Sets and saves the compass offset x/y/z values.
Parameters
i compass instance
offsets Offsets to the raw mag_ values in milligauss.
Definition at line 1805 of file AP_Compass.cpp.
Referenced by setup().
set_and_save_orientation()
void Compass::set_and_save_orientation (uint8_t i, Rotation orientation)
Definition at line 1857 of file AP_Compass.cpp.
set_and_save_scale_factor()
void Compass::set_and_save_scale_factor (uint8_t i, float scale_factor)
Definition at line 1838 of file AP_Compass.cpp.
set_board_orientation()
void Compass::set_board_orientation (enum Rotation orientation) inline
Definition at line 242 of file AP_Compass.h.
Referenced by AP_AHRS::update_orientation().
set_declination()
void Compass::set_declination (float radians, bool save_to_eeprom = true)
Sets the local magnetic field declination.
Parameters
radians Local field declination.
save_to_eeprom true to save to eeprom (false saves only to memory)
Definition at line 1958 of file AP_Compass.cpp.
Referenced by setup().
set_learn_type()
void Compass::set_learn_type (enum LearnType type, bool save) inline
Definition at line 330 of file AP_Compass.h.
Referenced by RC_Channel::do_aux_function().
set_log_bit()
void Compass::set_log_bit (uint32_t log_bit) inline
Definition at line 191 of file AP_Compass.h.
set_motor_compensation()
void Compass::set_motor_compensation (uint8_t i, const Vector3f & motor_comp_factor)
Set the motor compensation factor x/y/z values.
Parameters
i instance of compass
offsets Offsets multiplied by the throttle value and added to the raw mag_ values.
Definition at line 1874 of file AP_Compass.cpp.
Referenced by motor_compensation_type().
set_offsets()
void Compass::set_offsets (uint8_t i, const Vector3f & offsets)
Sets offset x/y/z values.
Parameters
i compass instance
offsets Offsets to the raw mag_ values in milligauss.
Definition at line 1795 of file AP_Compass.cpp.
set_throttle()
void Compass::set_throttle (float thr_pct) inline
Set the throttle as a percentage from 0.0 to 1.0
Parameters
thr_pct throttle expressed as a percentage from 0 to 1.0
Definition at line 288 of file AP_Compass.h.
set_voltage()
void Compass::set_voltage (float voltage) inline
Set the battery voltage for per-motor compensation.
Definition at line 296 of file AP_Compass.h.
start_calibration_all()
bool Compass::start_calibration_all (bool retry = false, bool autosave = false, float delay_sec = 0.0f, bool autoreboot = false)
Referenced by RC_Channel::do_aux_function().
try_set_initial_location()
void Compass::try_set_initial_location () private
Sets the initial location used to get declination
Parameters
latitude GPS Latitude.
longitude GPS Longitude.
Definition at line 1895 of file AP_Compass.cpp.
Referenced by read().
use_for_yaw() [1/2]
bool Compass::use_for_yaw (uint8_t i) const
return true if the compass should be used for yaw calculations
return true if the specified compass can be used for yaw calculations
Definition at line 1928 of file AP_Compass.cpp.
Referenced by AP_AHRS::attitudes_consistent(), AP_Arming::compass_checks(), loop(), AP_DAL_Compass::start_frame(), NavEKF2_core::tryChangeCompass(), NavEKF3_core::tryChangeCompass(), NavEKF3_core::update_mag_selection(), and NavEKF3_core::use_compass().
use_for_yaw() [2/2]
bool Compass::use_for_yaw (void) const
return true if the compass should be used for yaw calculations
Definition at line 1921 of file AP_Compass.cpp.
Referenced by configured(), consistent(), get_num_enabled(), and use_for_yaw().
Friends And Related Symbol Documentation
AP_Compass_Backend
friend class AP_Compass_Backend friend
Definition at line 82 of file AP_Compass.h.
CompassLearn
friend class CompassLearn friend
Definition at line 94 of file AP_Compass.h.
Referenced by read().
Member Data Documentation
_auto_declination
AP_Int8 Compass::_auto_declination private
Definition at line 518 of file AP_Compass.h.
Referenced by auto_declination_enabled(), and try_set_initial_location().
_backend_count
uint8_t Compass::_backend_count private
Definition at line 497 of file AP_Compass.h.
Referenced by _add_backend(), _detect_backends(), and read().
_backends
AP_Compass_Backend* Compass::_backends[COMPASS_MAX_BACKEND] private
Definition at line 496 of file AP_Compass.h.
Referenced by _add_backend(), and read().
_board_orientation
enum Rotation Compass::_board_orientation = ROTATION_NONE private
Definition at line 512 of file AP_Compass.h.
Referenced by get_board_orientation(), AP_Compass_Backend::get_board_orientation(), AP_Compass_Backend::rotate_field(), and set_board_orientation().
_cal_has_run
bool Compass::_cal_has_run private
Definition at line 427 of file AP_Compass.h.
_cal_requires_reboot
bool Compass::_cal_requires_reboot private
Definition at line 426 of file AP_Compass.h.
Referenced by compass_cal_requires_reboot().
_cal_thread_started
bool Compass::_cal_thread_started private
Definition at line 656 of file AP_Compass.h.
_calibration_threshold
AP_Float Compass::_calibration_threshold private
Definition at line 632 of file AP_Compass.h.
_compass_cal_autoreboot
bool Compass::_compass_cal_autoreboot private
Definition at line 425 of file AP_Compass.h.
Referenced by _auto_reboot().
_compass_count
uint8_t Compass::_compass_count private
Definition at line 503 of file AP_Compass.h.
Referenced by _detect_backends(), _update_priority_list(), get_count(), init(), and register_compass().
_declination
AP_Float Compass::_declination private
Definition at line 515 of file AP_Compass.h.
Referenced by calculate_heading(), get_declination(), set_declination(), and try_set_initial_location().
_driver_type_mask
AP_Int32 Compass::_driver_type_mask private
Definition at line 635 of file AP_Compass.h.
Referenced by _detect_backends(), and _driver_enabled().
_enabled
AP_Int8 Compass::_enabled private
Definition at line 500 of file AP_Compass.h.
Referenced by available(), init(), and try_set_initial_location().
_filter_range
AP_Int8 Compass::_filter_range private
Definition at line 643 of file AP_Compass.h.
Referenced by get_filter_range().
_first_usable
uint8_t Compass::_first_usable private
Definition at line 665 of file AP_Compass.h.
Referenced by calculate_heading(), get_diagonals(), get_field(), get_first_usable(), get_motor_compensation(), get_motor_offsets(), get_offdiagonals(), get_offsets(), healthy(), last_update_ms(), last_update_usec(), read(), and use_for_yaw().
_initial_location_set
bool Compass::_initial_location_set private
Definition at line 654 of file AP_Compass.h.
Referenced by read(), and try_set_initial_location().
_learn
AP_Int8 Compass::_learn private
Definition at line 509 of file AP_Compass.h.
Referenced by get_learn_type(), learn_offsets_enabled(), read(), set_learn_type(), and use_for_yaw().
_log_bit
uint32_t Compass::_log_bit = -1 private
Definition at line 521 of file AP_Compass.h.
Referenced by read(), and set_log_bit().
_motor_comp_type
AP_Int8 Compass::_motor_comp_type private
Definition at line 525 of file AP_Compass.h.
Referenced by AP_Compass_Backend::correct_field(), get_motor_compensation_type(), motor_compensation_type(), save_motor_compensation(), and set_throttle().
_offset_max
AP_Int16 Compass::_offset_max private
Definition at line 613 of file AP_Compass.h.
Referenced by get_offsets_max().
_options
AP_Int16 Compass::_options private
Definition at line 621 of file AP_Compass.h.
Referenced by option_set().
_per_motor
Compass_PerMotor Compass::_per_motor {*this} private
Definition at line 629 of file AP_Compass.h.
Referenced by AP_Compass_Backend::correct_field(), per_motor_calibration_end(), per_motor_calibration_start(), per_motor_calibration_update(), and set_voltage().
_previously_unreg_mag
uint32_t Compass::_previously_unreg_mag[COMPASS_MAX_UNREG_DEV] private
Definition at line 640 of file AP_Compass.h.
Referenced by init(), and is_replacement_mag().
_priority_did_list
RestrictIDTypeArray<int32_t, COMPASS_MAX_INSTANCES, Priority> Compass::_priority_did_list private
Definition at line 610 of file AP_Compass.h.
Referenced by _get_state_id(), _reorder_compass_params(), _reset_compass_id(), _update_priority_list(), configured(), and init().
_priority_did_stored_list
RestrictIDTypeArray<AP_Int32, COMPASS_MAX_INSTANCES, Priority> Compass::_priority_did_stored_list private
Definition at line 609 of file AP_Compass.h.
Referenced by _reset_compass_id(), _update_priority_list(), configured(), and init().
_rotate_auto
AP_Int8 Compass::_rotate_auto private
Definition at line 528 of file AP_Compass.h.
_singleton
Compass * Compass::_singleton static private
Definition at line 369 of file AP_Compass.h.
Referenced by Compass(), and get_singleton().
_state
RestrictIDTypeArray<mag_state, COMPASS_MAX_INSTANCES+1, StateIndex> Compass::_state private
Definition at line 579 of file AP_Compass.h.
Referenced by _get_priority(), _get_state(), _get_state_id(), _have_i2c_driver(), _reorder_compass_params(), _reset_compass_id(), AP_Compass_Backend::accumulate_sample(), configured(), AP_Compass_Backend::correct_field(), AP_Compass_Backend::drain_accumulated_samples(), force_save_calibration(), have_scale_factor(), init(), AP_Compass_Backend::is_external(), is_replacement_mag(), AP_Compass_Backend::publish_filtered_field(), AP_Compass_Backend::publish_raw_field(), read(), register_compass(), AP_Compass_Backend::rotate_field(), AP_Compass_Backend::save_dev_id(), save_motor_compensation(), save_offsets(), set_and_save_diagonals(), set_and_save_offdiagonals(), set_and_save_offsets(), set_and_save_orientation(), set_and_save_scale_factor(), AP_Compass_Backend::set_dev_id(), AP_Compass_Backend::set_external(), AP_Compass_Backend::set_last_update_usec(), set_motor_compensation(), set_offsets(), and AP_Compass_Backend::set_rotation().
_thr
float Compass::_thr private
Definition at line 531 of file AP_Compass.h.
Referenced by AP_Compass_Backend::correct_field(), motor_compensation_type(), and set_throttle().
_unreg_compass_count
uint8_t Compass::_unreg_compass_count private
Definition at line 506 of file AP_Compass.h.
Referenced by init(), and register_compass().
_use_for_yaw
RestrictIDTypeArray<AP_Int8, COMPASS_MAX_INSTANCES, Priority> Compass::_use_for_yaw private
Definition at line 607 of file AP_Compass.h.
Referenced by read(), and use_for_yaw().
extra_dev_id
AP_Int32 Compass::extra_dev_id[COMPASS_MAX_UNREG_DEV] private
Definition at line 639 of file AP_Compass.h.
Referenced by init(), register_compass(), and remove_unreg_dev_id().
init_done
bool Compass::init_done private
Definition at line 661 of file AP_Compass.h.
Referenced by available(), and init().
learn
CompassLearn* Compass::learn private
Definition at line 645 of file AP_Compass.h.
Referenced by read().
learn_allocated
bool Compass::learn_allocated private
Definition at line 646 of file AP_Compass.h.
Referenced by read().
next_cal_progress_idx
Priority Compass::next_cal_progress_idx[MAVLINK_COMM_NUM_BUFFERS] private
Definition at line 404 of file AP_Compass.h.
next_cal_report_idx
Priority Compass::next_cal_report_idx[MAVLINK_COMM_NUM_BUFFERS] private
Definition at line 405 of file AP_Compass.h.
suppress_devid_save
bool Compass::suppress_devid_save private
Definition at line 663 of file AP_Compass.h.
Referenced by _update_priority_list(), and init().
var_info
const AP_Param::GroupInfo Compass::var_info static
Definition at line 71 of file AP_Compass.h.
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass.h
libraries/AP_Compass/AP_Compass.cpp