APM:Libraries: MAVLink_routing Class Reference
MAVLink_routing Class Reference
#include <MAVLink_routing.h>
Classes
struct route
Public Member Functions
MAVLink_routing (void)
bool check_and_forward (class GCS_MAVLINK &link, const mavlink_message_t &msg)
void send_to_components (uint32_t msgid, const char *pkt, uint8_t pkt_len)
bool find_by_mavtype (uint8_t mavtype, uint8_t &sysid, uint8_t &compid, mavlink_channel_t &channel)
bool find_by_mavtype_and_compid (uint8_t mavtype, uint8_t compid, uint8_t &sysid, mavlink_channel_t &channel) const
Private Member Functions
void learn_route (GCS_MAVLINK &link, const mavlink_message_t &msg)
void get_targets (const mavlink_message_t &msg, int16_t &sysid, int16_t &compid)
void handle_heartbeat (GCS_MAVLINK &link, const mavlink_message_t &msg)
void send_to_components (const char *pkt, const mavlink_msg_entry_t *entry, uint8_t pkt_len)
Private Attributes
uint8_t num_routes
struct MAVLink_routing::route routes [MAVLINK_MAX_ROUTES]
uint8_t no_route_mask
bool gopro_status_check
Friends
class GCS_MAVLINK
Detailed Description
Definition at line 15 of file MAVLink_routing.h.
Constructor & Destructor Documentation
MAVLink_routing()
MAVLink_routing::MAVLink_routing (void)
Definition at line 34 of file MAVLink_routing.cpp.
Member Function Documentation
check_and_forward()
bool MAVLink_routing::check_and_forward (class GCS_MAVLINK & link, const mavlink_message_t & msg)
Definition at line 95 of file MAVLink_routing.cpp.
Referenced by loop(), and GCS_MAVLINK::packetReceived().
find_by_mavtype()
bool MAVLink_routing::find_by_mavtype (uint8_t mavtype, uint8_t & sysid, uint8_t & compid, mavlink_channel_t & channel)
Definition at line 276 of file MAVLink_routing.cpp.
Referenced by GCS_MAVLINK::find_by_mavtype().
find_by_mavtype_and_compid()
bool MAVLink_routing::find_by_mavtype_and_compid (uint8_t mavtype, uint8_t compid, uint8_t & sysid, mavlink_channel_t & channel) const
Definition at line 296 of file MAVLink_routing.cpp.
Referenced by GCS_MAVLINK::find_by_mavtype_and_compid(), and GCS_MAVLINK::find_by_mavtype_and_compid().
get_targets()
void MAVLink_routing::get_targets (const mavlink_message_t & msg, int16_t & sysid, int16_t & compid) private
Definition at line 414 of file MAVLink_routing.cpp.
Referenced by check_and_forward().
handle_heartbeat()
void MAVLink_routing::handle_heartbeat (GCS_MAVLINK & link, const mavlink_message_t & msg) private
Definition at line 364 of file MAVLink_routing.cpp.
Referenced by check_and_forward().
learn_route()
void MAVLink_routing::learn_route (GCS_MAVLINK & link, const mavlink_message_t & msg) private
Definition at line 311 of file MAVLink_routing.cpp.
Referenced by check_and_forward().
send_to_components() [1/2]
void MAVLink_routing::send_to_components (const char * pkt, const mavlink_msg_entry_t * entry, uint8_t pkt_len) private
Definition at line 230 of file MAVLink_routing.cpp.
send_to_components() [2/2]
void MAVLink_routing::send_to_components (uint32_t msgid, const char * pkt, uint8_t pkt_len)
Definition at line 221 of file MAVLink_routing.cpp.
Referenced by GCS_MAVLINK::send_to_components(), and send_to_components().
Friends And Related Symbol Documentation
GCS_MAVLINK
friend class GCS_MAVLINK friend
Definition at line 17 of file MAVLink_routing.h.
Member Data Documentation
gopro_status_check
bool MAVLink_routing::gopro_status_check private
Definition at line 78 of file MAVLink_routing.h.
Referenced by check_and_forward().
no_route_mask
uint8_t MAVLink_routing::no_route_mask private
Definition at line 64 of file MAVLink_routing.h.
Referenced by GCS_MAVLINK::disable_channel_routing().
num_routes
uint8_t MAVLink_routing::num_routes private
Definition at line 55 of file MAVLink_routing.h.
Referenced by check_and_forward(), find_by_mavtype(), find_by_mavtype_and_compid(), handle_heartbeat(), learn_route(), and send_to_components().
routes
struct MAVLink_routing::route MAVLink_routing::routes[MAVLINK_MAX_ROUTES] private
Referenced by check_and_forward(), find_by_mavtype(), find_by_mavtype_and_compid(), handle_heartbeat(), learn_route(), and send_to_components().
The documentation for this class was generated from the following files:
libraries/GCS_MAVLink/MAVLink_routing.h
libraries/GCS_MAVLink/MAVLink_routing.cpp