APM:Libraries: MissionItemProtocol Class Reference
MissionItemProtocol Class Reference abstract
#include <MissionItemProtocol.h>
Public Member Functions
void handle_mission_request_list (const class GCS_MAVLINK &link, const mavlink_mission_request_list_t &packet, const mavlink_message_t &msg)
void handle_mission_request_int (GCS_MAVLINK &link, const mavlink_mission_request_int_t &packet, const mavlink_message_t &msg)
void handle_mission_request (GCS_MAVLINK &link, const mavlink_mission_request_t &packet, const mavlink_message_t &msg)
void handle_mission_count (class GCS_MAVLINK &link, const mavlink_mission_count_t &packet, const mavlink_message_t &msg)
void handle_mission_write_partial_list (GCS_MAVLINK &link, const mavlink_message_t &msg, const mavlink_mission_write_partial_list_t &packet)
void handle_mission_item (const mavlink_message_t &msg, const mavlink_mission_item_int_t &cmd)
void handle_mission_clear_all (const GCS_MAVLINK &link, const mavlink_message_t &msg)
void queued_request_send ()
Send the next pending waypoint, called from deferred message handling code.
void update ()
bool active_link_is (const GCS_MAVLINK *_link) const
virtual MAV_MISSION_TYPE mission_type () const =0
void send_mission_item_warning ()
Public Attributes
bool receiving
Protected Member Functions
virtual ap_message next_item_ap_message_id () const =0
virtual bool clear_all_items ()=0
Protected Attributes
GCS_MAVLINK * link
uint16_t request_last
Private Member Functions
virtual void truncate (const mavlink_mission_count_t &packet)=0
virtual MAV_MISSION_RESULT get_item (const GCS_MAVLINK &_link, const mavlink_message_t &msg, const mavlink_mission_request_int_t &packet, mavlink_mission_item_int_t &ret_packet)=0
void init_send_requests (GCS_MAVLINK &_link, const mavlink_message_t &msg, const int16_t _request_first, const int16_t _request_last)
virtual MAV_MISSION_RESULT allocate_receive_resources (const uint16_t count) WARN_IF_UNUSED
virtual MAV_MISSION_RESULT allocate_update_resources () WARN_IF_UNUSED
virtual void free_upload_resources ()
void send_mission_ack (const mavlink_message_t &msg, MAV_MISSION_RESULT result) const
void send_mission_ack (const GCS_MAVLINK &link, const mavlink_message_t &msg, MAV_MISSION_RESULT result) const
virtual uint16_t item_count () const =0
virtual uint16_t max_items () const =0
virtual MAV_MISSION_RESULT replace_item (const mavlink_mission_item_int_t &mission_item_int)=0
virtual MAV_MISSION_RESULT append_item (const mavlink_mission_item_int_t &mission_item_int)=0
virtual MAV_MISSION_RESULT complete (const GCS_MAVLINK &_link)
void transfer_is_complete (const GCS_MAVLINK &_link, const mavlink_message_t &msg)
virtual void timeout ()
bool mavlink2_requirement_met (const GCS_MAVLINK &_link, const mavlink_message_t &msg) const
Private Attributes
uint16_t request_i
uint8_t dest_sysid
uint8_t dest_compid
uint32_t timelast_receive_ms
uint32_t timelast_request_ms
const uint16_t upload_timeout_ms = 8000
bool mission_request_warning_sent = false
bool mission_item_warning_sent = false
Detailed Description
Definition at line 24 of file MissionItemProtocol.h.
Member Function Documentation
active_link_is()
bool MissionItemProtocol::active_link_is (const GCS_MAVLINK * _link) const inline
Definition at line 58 of file MissionItemProtocol.h.
Referenced by GCS_MAVLINK::requesting_mission_items().
allocate_receive_resources()
virtual MAV_MISSION_RESULT MissionItemProtocol::allocate_receive_resources (const uint16_t count) inline private virtual
Reimplemented in MissionItemProtocol_Fence.
Definition at line 110 of file MissionItemProtocol.h.
Referenced by handle_mission_count().
allocate_update_resources()
virtual MAV_MISSION_RESULT MissionItemProtocol::allocate_update_resources () inline private virtual
Reimplemented in MissionItemProtocol_Fence.
Definition at line 113 of file MissionItemProtocol.h.
Referenced by handle_mission_write_partial_list().
append_item()
virtual MAV_MISSION_RESULT MissionItemProtocol::append_item (const mavlink_mission_item_int_t & mission_item_int) private pure virtual
Implemented in MissionItemProtocol_Fence, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_item().
clear_all_items()
virtual bool MissionItemProtocol::clear_all_items () protected pure virtual
Implemented in MissionItemProtocol_Fence, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_clear_all().
complete()
virtual MAV_MISSION_RESULT MissionItemProtocol::complete (const GCS_MAVLINK & _link) inline private virtual
Reimplemented in MissionItemProtocol_Fence, and MissionItemProtocol_Waypoints.
Definition at line 129 of file MissionItemProtocol.h.
Referenced by transfer_is_complete().
free_upload_resources()
virtual void MissionItemProtocol::free_upload_resources () inline private virtual
Reimplemented in MissionItemProtocol_Fence.
Definition at line 116 of file MissionItemProtocol.h.
Referenced by handle_mission_count(), handle_mission_item(), transfer_is_complete(), and update().
get_item()
virtual MAV_MISSION_RESULT MissionItemProtocol::get_item (const GCS_MAVLINK & _link, const mavlink_message_t & msg, const mavlink_mission_request_int_t & packet, mavlink_mission_item_int_t & ret_packet) private pure virtual
Implemented in MissionItemProtocol_Fence, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_request_int().
handle_mission_clear_all()
void MissionItemProtocol::handle_mission_clear_all (const GCS_MAVLINK & link, const mavlink_message_t & msg)
Definition at line 32 of file MissionItemProtocol.cpp.
Referenced by GCS_MAVLINK::handle_mission_clear_all().
handle_mission_count()
void MissionItemProtocol::handle_mission_count (class GCS_MAVLINK & link, const mavlink_mission_count_t & packet, const mavlink_message_t & msg)
Definition at line 55 of file MissionItemProtocol.cpp.
Referenced by GCS_MAVLINK::handle_mission_count().
handle_mission_item()
void MissionItemProtocol::handle_mission_item (const mavlink_message_t & msg, const mavlink_mission_item_int_t & cmd)
Definition at line 240 of file MissionItemProtocol.cpp.
Referenced by GCS_MAVLINK::handle_mission_item().
handle_mission_request()
void MissionItemProtocol::handle_mission_request (GCS_MAVLINK & link, const mavlink_mission_request_t & packet, const mavlink_message_t & msg)
handle_mission_request_int()
void MissionItemProtocol::handle_mission_request_int (GCS_MAVLINK & link, const mavlink_mission_request_int_t & packet, const mavlink_message_t & msg)
Definition at line 129 of file MissionItemProtocol.cpp.
Referenced by GCS_MAVLINK::handle_mission_request_int().
handle_mission_request_list()
void MissionItemProtocol::handle_mission_request_list (const class GCS_MAVLINK & link, const mavlink_mission_request_list_t & packet, const mavlink_message_t & msg)
Definition at line 103 of file MissionItemProtocol.cpp.
Referenced by GCS_MAVLINK::handle_mission_request_list().
handle_mission_write_partial_list()
void MissionItemProtocol::handle_mission_write_partial_list (GCS_MAVLINK & link, const mavlink_message_t & msg, const mavlink_mission_write_partial_list_t & packet)
Definition at line 217 of file MissionItemProtocol.cpp.
Referenced by GCS_MAVLINK::handle_mission_write_partial_list().
init_send_requests()
void MissionItemProtocol::init_send_requests (GCS_MAVLINK & _link, const mavlink_message_t & msg, const int16_t _request_first, const int16_t _request_last) private
Definition at line 9 of file MissionItemProtocol.cpp.
Referenced by handle_mission_count(), and handle_mission_write_partial_list().
item_count()
virtual uint16_t MissionItemProtocol::item_count () const private pure virtual
Implemented in MissionItemProtocol_Fence, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_item(), handle_mission_request_list(), and handle_mission_write_partial_list().
mavlink2_requirement_met()
bool MissionItemProtocol::mavlink2_requirement_met (const GCS_MAVLINK & _link, const mavlink_message_t & msg) const private
Definition at line 41 of file MissionItemProtocol.cpp.
Referenced by handle_mission_count(), handle_mission_request_int(), and handle_mission_request_list().
max_items()
virtual uint16_t MissionItemProtocol::max_items () const private pure virtual
Implemented in MissionItemProtocol_Fence, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_count().
mission_type()
virtual MAV_MISSION_TYPE MissionItemProtocol::mission_type () const pure virtual
Implemented in MissionItemProtocol_Fence, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_request_list(), mavlink2_requirement_met(), queued_request_send(), send_mission_ack(), and update().
next_item_ap_message_id()
virtual ap_message MissionItemProtocol::next_item_ap_message_id () const protected pure virtual
Implemented in MissionItemProtocol_Fence, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_item(), init_send_requests(), and update().
queued_request_send()
void MissionItemProtocol::queued_request_send ()
Send the next pending waypoint, called from deferred message handling code.
Definition at line 333 of file MissionItemProtocol.cpp.
Referenced by handle_mission_item(), and GCS::try_send_queued_message_for_type().
replace_item()
virtual MAV_MISSION_RESULT MissionItemProtocol::replace_item (const mavlink_mission_item_int_t & mission_item_int) private pure virtual
Implemented in MissionItemProtocol_Fence, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_item().
send_mission_ack() [1/2]
void MissionItemProtocol::send_mission_ack (const GCS_MAVLINK & link, const mavlink_message_t & msg, MAV_MISSION_RESULT result) const private
Definition at line 317 of file MissionItemProtocol.cpp.
send_mission_ack() [2/2]
void MissionItemProtocol::send_mission_ack (const mavlink_message_t & msg, MAV_MISSION_RESULT result) const private
Definition at line 308 of file MissionItemProtocol.cpp.
Referenced by handle_mission_clear_all(), handle_mission_count(), handle_mission_item(), handle_mission_request_int(), handle_mission_request_list(), handle_mission_write_partial_list(), mavlink2_requirement_met(), send_mission_ack(), and transfer_is_complete().
send_mission_item_warning()
void MissionItemProtocol::send_mission_item_warning ()
Definition at line 208 of file MissionItemProtocol.cpp.
Referenced by GCS_MAVLINK::handle_mission_item().
timeout()
virtual void MissionItemProtocol::timeout () inline private virtual
Reimplemented in MissionItemProtocol_Fence, and MissionItemProtocol_Waypoints.
Definition at line 140 of file MissionItemProtocol.h.
Referenced by update().
transfer_is_complete()
void MissionItemProtocol::transfer_is_complete (const GCS_MAVLINK & _link, const mavlink_message_t & msg) private
Definition at line 299 of file MissionItemProtocol.cpp.
Referenced by handle_mission_count(), and handle_mission_item().
truncate()
virtual void MissionItemProtocol::truncate (const mavlink_mission_count_t & packet) private pure virtual
Implemented in MissionItemProtocol_Fence, and MissionItemProtocol_Waypoints.
Referenced by handle_mission_count().
update()
void MissionItemProtocol::update ()
Definition at line 355 of file MissionItemProtocol.cpp.
Referenced by GCS::update_send().
Member Data Documentation
dest_compid
uint8_t MissionItemProtocol::dest_compid private
Definition at line 88 of file MissionItemProtocol.h.
Referenced by handle_mission_count(), handle_mission_item(), init_send_requests(), queued_request_send(), and update().
dest_sysid
uint8_t MissionItemProtocol::dest_sysid private
Definition at line 87 of file MissionItemProtocol.h.
Referenced by handle_mission_count(), handle_mission_item(), init_send_requests(), queued_request_send(), and update().
link
GCS_MAVLINK* MissionItemProtocol::link protected
Definition at line 70 of file MissionItemProtocol.h.
Referenced by active_link_is(), handle_mission_item(), init_send_requests(), queued_request_send(), send_mission_ack(), transfer_is_complete(), and update().
mission_item_warning_sent
bool MissionItemProtocol::mission_item_warning_sent = false private
Definition at line 98 of file MissionItemProtocol.h.
Referenced by init_send_requests(), and send_mission_item_warning().
mission_request_warning_sent
bool MissionItemProtocol::mission_request_warning_sent = false private
Definition at line 95 of file MissionItemProtocol.h.
Referenced by init_send_requests().
receiving
bool MissionItemProtocol::receiving
Definition at line 62 of file MissionItemProtocol.h.
Referenced by handle_mission_clear_all(), handle_mission_count(), GCS_MAVLINK::handle_mission_item(), handle_mission_item(), handle_mission_request_int(), handle_mission_request_list(), init_send_requests(), queued_request_send(), GCS_MAVLINK::requesting_mission_items(), transfer_is_complete(), and update().
request_i
uint16_t MissionItemProtocol::request_i private
Definition at line 84 of file MissionItemProtocol.h.
Referenced by handle_mission_item(), init_send_requests(), and queued_request_send().
request_last
uint16_t MissionItemProtocol::request_last protected
Definition at line 78 of file MissionItemProtocol.h.
Referenced by handle_mission_item(), init_send_requests(), and queued_request_send().
timelast_receive_ms
uint32_t MissionItemProtocol::timelast_receive_ms private
Definition at line 89 of file MissionItemProtocol.h.
Referenced by handle_mission_item(), init_send_requests(), and update().
timelast_request_ms
uint32_t MissionItemProtocol::timelast_request_ms private
Definition at line 90 of file MissionItemProtocol.h.
Referenced by init_send_requests(), queued_request_send(), and update().
upload_timeout_ms
const uint16_t MissionItemProtocol::upload_timeout_ms = 8000 private
Definition at line 91 of file MissionItemProtocol.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/GCS_MAVLink/MissionItemProtocol.h
libraries/GCS_MAVLink/MissionItemProtocol.cpp