APM:Libraries: AP_RCProtocol_FPort Class Reference
AP_RCProtocol_FPort Class Reference
#include <AP_RCProtocol_FPort.h>
Public Member Functions
AP_RCProtocol_FPort (AP_RCProtocol &_frontend, bool inverted)
void process_pulse (uint32_t width_s0, uint32_t width_s1) override
void process_byte (uint8_t byte, uint32_t baudrate) override
Public Member Functions inherited from AP_RCProtocol_Backend
AP_RCProtocol_Backend (AP_RCProtocol &_frontend)
virtual ~AP_RCProtocol_Backend ()
virtual void process_handshake (uint32_t baudrate)
uint16_t read (uint8_t chan)
void read (uint16_t *pwm, uint8_t n)
bool new_input ()
uint8_t num_channels () const
virtual void start_bind (void)
virtual void update (void)
uint32_t get_rc_frame_count (void) const
void reset_rc_frame_count (void)
uint32_t get_rc_input_count (void) const
uint32_t get_rc_protocols_mask (void) const
bool protocol_enabled (enum AP_RCProtocol::rcprotocol_t protocol) const
int16_t get_RSSI (void) const
int16_t get_rx_link_quality (void) const
AP_HAL::UARTDriver * get_UART (void) const
AP_HAL::UARTDriver * get_available_UART (void) const
bool have_UART (void) const
virtual bool is_rx_active () const
bool is_detected () const
Private Member Functions
void decode_control (const FPort_Frame &frame)
void decode_downlink (const FPort_Frame &frame)
bool check_checksum (void)
void _process_byte (uint32_t timestamp_us, uint8_t byte)
Private Attributes
SoftSerial ss {115200, SoftSerial::SERIAL_CONFIG_8N1}
uint32_t saved_width
struct {
uint8_t buf [FPORT_CONTROL_FRAME_SIZE]
uint8_t ofs
uint32_t last_byte_us
bool got_DLE
} byte_input
const bool inverted
bool rx_driven_frame_rate = false
uint8_t consecutive_telemetry_frame_count
Additional Inherited Members
Protected Member Functions inherited from AP_RCProtocol_Backend
void add_input (uint8_t num_channels, uint16_t *values, bool in_failsafe, int16_t rssi=-1, int16_t rx_link_quality=-1)
void log_data (AP_RCProtocol::rcprotocol_t prot, uint32_t timestamp, const uint8_t *data, uint8_t len) const
Static Protected Member Functions inherited from AP_RCProtocol_Backend
static void decode_11bit_channels (const uint8_t *data, uint8_t nchannels, uint16_t *values, uint16_t mult, uint16_t div, uint16_t offset)
Protected Attributes inherited from AP_RCProtocol_Backend
struct AP_RCProtocol_Backend::Channels11Bit_8Chan PACKED
AP_RCProtocol & frontend
Detailed Description
Definition at line 32 of file AP_RCProtocol_FPort.h.
Constructor & Destructor Documentation
AP_RCProtocol_FPort()
AP_RCProtocol_FPort::AP_RCProtocol_FPort (AP_RCProtocol & _frontend, bool inverted)
Definition at line 81 of file AP_RCProtocol_FPort.cpp.
Member Function Documentation
_process_byte()
void AP_RCProtocol_FPort::_process_byte (uint32_t timestamp_us, uint8_t byte) private
Definition at line 232 of file AP_RCProtocol_FPort.cpp.
Referenced by process_byte(), and process_pulse().
check_checksum()
bool AP_RCProtocol_FPort::check_checksum (void) private
Definition at line 307 of file AP_RCProtocol_FPort.cpp.
Referenced by _process_byte().
decode_control()
void AP_RCProtocol_FPort::decode_control (const FPort_Frame & frame) private
Definition at line 87 of file AP_RCProtocol_FPort.cpp.
Referenced by _process_byte().
decode_downlink()
void AP_RCProtocol_FPort::decode_downlink (const FPort_Frame & frame) private
Definition at line 104 of file AP_RCProtocol_FPort.cpp.
Referenced by _process_byte().
process_byte()
void AP_RCProtocol_FPort::process_byte (uint8_t byte, uint32_t baudrate) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 314 of file AP_RCProtocol_FPort.cpp.
process_pulse()
void AP_RCProtocol_FPort::process_pulse (uint32_t width_s0, uint32_t width_s1) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 211 of file AP_RCProtocol_FPort.cpp.
Member Data Documentation
buf
uint8_t AP_RCProtocol_FPort::buf[FPORT_CONTROL_FRAME_SIZE]
Definition at line 48 of file AP_RCProtocol_FPort.h.
Referenced by decode_downlink().
[struct]
struct { ... } AP_RCProtocol_FPort::byte_input
Referenced by _process_byte(), and check_checksum().
consecutive_telemetry_frame_count
uint8_t AP_RCProtocol_FPort::consecutive_telemetry_frame_count private
Definition at line 67 of file AP_RCProtocol_FPort.h.
Referenced by decode_downlink().
got_DLE
bool AP_RCProtocol_FPort::got_DLE
Definition at line 51 of file AP_RCProtocol_FPort.h.
inverted
const bool AP_RCProtocol_FPort::inverted private
Definition at line 54 of file AP_RCProtocol_FPort.h.
Referenced by process_pulse().
last_byte_us
uint32_t AP_RCProtocol_FPort::last_byte_us
Definition at line 50 of file AP_RCProtocol_FPort.h.
ofs
uint8_t AP_RCProtocol_FPort::ofs
Definition at line 49 of file AP_RCProtocol_FPort.h.
rx_driven_frame_rate
bool AP_RCProtocol_FPort::rx_driven_frame_rate = false private
Definition at line 64 of file AP_RCProtocol_FPort.h.
Referenced by decode_downlink().
saved_width
uint32_t AP_RCProtocol_FPort::saved_width private
Definition at line 45 of file AP_RCProtocol_FPort.h.
Referenced by process_pulse().
ss
SoftSerial AP_RCProtocol_FPort::ss {115200, SoftSerial::SERIAL_CONFIG_8N1} private
Definition at line 44 of file AP_RCProtocol_FPort.h.
Referenced by process_pulse().
The documentation for this class was generated from the following files:
libraries/AP_RCProtocol/AP_RCProtocol_FPort.h
libraries/AP_RCProtocol/AP_RCProtocol_FPort.cpp