APM:Libraries: ekf_ring_buffer Class Reference
ekf_ring_buffer Class Reference
#include <EKF_Buffer.h>
Public Member Functions
ekf_ring_buffer (uint8_t elsize)
bool init (uint8_t size)
bool recall (void *element, const uint32_t sample_time_ms)
void push (const void *element)
void reset ()
Private Member Functions
uint32_t time_ms (uint8_t idx) const
void * get_offset (uint8_t idx) const
Private Attributes
const uint8_t elsize
void * buffer
uint8_t size
uint8_t oldest
uint8_t count
Detailed Description
Definition at line 17 of file EKF_Buffer.h.
Constructor & Destructor Documentation
ekf_ring_buffer()
ekf_ring_buffer::ekf_ring_buffer (uint8_t elsize)
Definition at line 12 of file EKF_Buffer.cpp.
Member Function Documentation
get_offset()
void * ekf_ring_buffer::get_offset (uint8_t idx) const private
Definition at line 34 of file EKF_Buffer.cpp.
Referenced by push(), recall(), and time_ms().
init()
bool ekf_ring_buffer::init (uint8_t size)
Definition at line 17 of file EKF_Buffer.cpp.
Referenced by EKF_obs_buffer_t< element_type >::init().
push()
void ekf_ring_buffer::push (const void * element)
Definition at line 80 of file EKF_Buffer.cpp.
Referenced by EKF_obs_buffer_t< element_type >::push().
recall()
bool ekf_ring_buffer::recall (void * element, const uint32_t sample_time_ms)
Definition at line 53 of file EKF_Buffer.cpp.
Referenced by EKF_obs_buffer_t< element_type >::recall().
reset()
void ekf_ring_buffer::reset ()
Definition at line 101 of file EKF_Buffer.cpp.
Referenced by init(), and EKF_obs_buffer_t< element_type >::reset().
time_ms()
uint32_t ekf_ring_buffer::time_ms (uint8_t idx) const private
Definition at line 42 of file EKF_Buffer.cpp.
Referenced by recall().
Member Data Documentation
buffer
void* ekf_ring_buffer::buffer private
Definition at line 44 of file EKF_Buffer.h.
Referenced by get_offset(), init(), and push().
count
uint8_t ekf_ring_buffer::count private
Definition at line 53 of file EKF_Buffer.h.
Referenced by push(), recall(), and reset().
elsize
const uint8_t ekf_ring_buffer::elsize private
Definition at line 43 of file EKF_Buffer.h.
Referenced by get_offset(), init(), push(), and recall().
oldest
uint8_t ekf_ring_buffer::oldest private
Definition at line 50 of file EKF_Buffer.h.
Referenced by push(), recall(), and reset().
size
uint8_t ekf_ring_buffer::size private
Definition at line 47 of file EKF_Buffer.h.
Referenced by init(), push(), and recall().
The documentation for this class was generated from the following files:
libraries/AP_NavEKF/EKF_Buffer.h
libraries/AP_NavEKF/EKF_Buffer.cpp