APM:Libraries: AP_Enum< eclass > Class Template Reference
AP_Enum< eclass > Class Template Reference
#include <AP_Param.h>
Public Member Functions
operator const eclass () const
void set (eclass v)
Detailed Description
template<typename eclass>
class AP_Enum< eclass >
Definition at line 1064 of file AP_Param.h.
Member Function Documentation
operator const eclass()
template<typename eclass > AP_Enum< eclass >::operator const eclass () const inline
Definition at line 1067 of file AP_Param.h.
set()
template<typename eclass > void AP_Enum< eclass >::set (eclass v) inline
Definition at line 1070 of file AP_Param.h.
Referenced by AP_AHRS::init(), AP_OSD_ParamScreen::modify_configured_parameter(), and AP_AHRS::set_ekf_type().
The documentation for this class was generated from the following file:
libraries/AP_Param/AP_Param.h