APM:Libraries: RC_Channels Class Reference
RC_Channels Class Reference abstract
#include <RC_Channel.h>
Public Types
enum class Option {
IGNORE_RECEIVER = (1U << 0) , IGNORE_OVERRIDES = (1U << 1) , IGNORE_FAILSAFE = (1U << 2) , FPORT_PAD = (1U << 3) ,
LOG_RAW_DATA = (1U << 4) , ARMING_CHECK_THROTTLE = (1U << 5) , ARMING_SKIP_CHECK_RPY = (1U << 6) , ALLOW_SWITCH_REV = (1U << 7) ,
CRSF_CUSTOM_TELEMETRY = (1U << 8) , SUPPRESS_CRSF_MESSAGE = (1U << 9) , MULTI_RECEIVER_SUPPORT = (1U << 10) , USE_CRSF_LQ_AS_RSSI = (1U << 11) ,
CRSF_FM_DISARM_STAR = (1U << 12) , ELRS_420KBAUD = (1U << 13)
}
Public Member Functions
RC_Channels (void)
void init (void)
virtual RC_Channel * channel (uint8_t chan)=0
RC_Channel * lua_rc_channel (const uint8_t chan)
uint8_t get_radio_in (uint16_t *chans, const uint8_t num_channels)
bool read_input (void)
uint16_t get_override_mask () const
class RC_Channel * find_channel_for_option (const RC_Channel::AUX_FUNC option)
bool duplicate_options_exist ()
RC_Channel::AuxSwitchPos get_channel_pos (const uint8_t rcmapchan) const
void convert_options (const RC_Channel::AUX_FUNC old_option, const RC_Channel::AUX_FUNC new_option)
void init_aux_all ()
void read_aux_all ()
void reset_mode_switch ()
virtual void read_mode_switch ()
virtual bool in_rc_failsafe () const
virtual bool has_valid_input () const
virtual RC_Channel * get_arming_channel (void) const
bool gcs_overrides_enabled () const
void set_gcs_overrides_enabled (bool enable)
bool option_is_enabled (Option option) const
virtual bool arming_check_throttle () const
bool get_override_timeout_ms (uint32_t &returned_timeout_ms) const
uint32_t enabled_protocols () const
bool has_had_rc_receiver () const
bool has_had_rc_override () const
bool get_pwm (uint8_t channel, uint16_t &pwm) const
uint32_t last_input_ms () const
bool run_aux_function (RC_Channel::AUX_FUNC ch_option, RC_Channel::AuxSwitchPos pos, RC_Channel::AuxFuncTriggerSource source)
bool flight_mode_channel_conflicts_with_rc_option () const
virtual int8_t flight_mode_channel_number () const =0
void calibrating (bool b)
bool calibrating ()
bool has_ever_seen_rc_input () const
uint32_t get_fs_timeout_ms () const
Static Public Member Functions
static RC_Channels * get_singleton ()
static uint16_t get_radio_in (const uint8_t chan)
static RC_Channel * rc_channel (const uint8_t chan)
static uint8_t get_valid_channel_count (void)
static int16_t get_receiver_rssi (void)
static int16_t get_receiver_link_quality (void)
static void clear_overrides (void)
static bool receiver_bind (const int dsmMode)
static void set_override (const uint8_t chan, const int16_t value, const uint32_t timestamp_ms=0)
static bool has_active_overrides (void)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void new_override_received ()
Private Member Functions
RC_Channel * flight_mode_channel () const
Private Attributes
uint32_t last_update_ms
bool has_new_overrides
bool _has_had_rc_receiver
bool _has_had_override
AP_Float _override_timeout
AP_Int32 _options
AP_Int32 _protocols
AP_Float _fs_timeout
bool _has_ever_seen_rc_input
bool _gcs_overrides_enabled = true
bool gcs_is_calibrating
Static Private Attributes
static RC_Channels * _singleton
static RC_Channel * channels
Friends
class SRV_Channels
class RC_Channel
Detailed Description
Definition at line 430 of file RC_Channel.h.
Member Enumeration Documentation
Option
enum class RC_Channels::Option strong
Enumerator
IGNORE_RECEIVER
IGNORE_OVERRIDES
IGNORE_FAILSAFE
FPORT_PAD
LOG_RAW_DATA
ARMING_CHECK_THROTTLE
ARMING_SKIP_CHECK_RPY
ALLOW_SWITCH_REV
CRSF_CUSTOM_TELEMETRY
SUPPRESS_CRSF_MESSAGE
MULTI_RECEIVER_SUPPORT
USE_CRSF_LQ_AS_RSSI
CRSF_FM_DISARM_STAR
ELRS_420KBAUD
Definition at line 509 of file RC_Channel.h.
Constructor & Destructor Documentation
RC_Channels()
RC_Channels::RC_Channels (void)
Definition at line 39 of file RC_Channels.cpp.
Member Function Documentation
arming_check_throttle()
virtual bool RC_Channels::arming_check_throttle () const inline virtual
Definition at line 530 of file RC_Channel.h.
calibrating() [1/2]
bool RC_Channels::calibrating () inline
Definition at line 584 of file RC_Channel.h.
calibrating() [2/2]
void RC_Channels::calibrating (bool b) inline
Definition at line 583 of file RC_Channel.h.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration().
channel()
virtual RC_Channel * RC_Channels::channel (uint8_t chan) pure virtual
Implemented in RC_Channels_Example, RC_Channels_Example, RC_Channels_PIDTest, and RC_Channels_RC.
Referenced by AP_Tuning::check_input(), AP_Tuning::check_selector_switch(), convert_options(), duplicate_options_exist(), AP_ICEngine::engine_control(), find_channel_for_option(), get_channel_pos(), get_radio_in(), get_radio_in(), init(), init_aux_all(), loop(), lua_rc_channel(), SRV_Channel::output_ch(), rc_channel(), read_aux_all(), AP_RSSI::read_channel_rssi(), read_input(), AP_Button::run_aux_functions(), SRV_Channels::set_output_limit(), setup(), and AP_ICEngine::update().
clear_overrides()
void RC_Channels::clear_overrides (void) static
Definition at line 108 of file RC_Channels.cpp.
Referenced by set_gcs_overrides_enabled().
convert_options()
void RC_Channels::convert_options (const RC_Channel::AUX_FUNC old_option, const RC_Channel::AUX_FUNC new_option)
Definition at line 1776 of file RC_Channel.cpp.
duplicate_options_exist()
bool RC_Channels::duplicate_options_exist ()
Definition at line 1748 of file RC_Channel.cpp.
enabled_protocols()
uint32_t RC_Channels::enabled_protocols () const
Definition at line 262 of file RC_Channels.cpp.
Referenced by AP_RCProtocol::check_added_uart(), AP_RCProtocol::process_byte(), and AP_RCProtocol::process_pulse().
find_channel_for_option()
RC_Channel * RC_Channels::find_channel_for_option (const RC_Channel::AUX_FUNC option)
Definition at line 1732 of file RC_Channel.cpp.
Referenced by AP_Arming::estop_checks(), AP_Mount_Backend::get_rc_input(), AP_Mount_Backend::set_rctargeting_on_rcinput_change(), and AP_WindVane_Home::update_direction().
flight_mode_channel()
RC_Channel * RC_Channels::flight_mode_channel () const private
Definition at line 197 of file RC_Channels.cpp.
Referenced by flight_mode_channel_conflicts_with_rc_option(), read_mode_switch(), and reset_mode_switch().
flight_mode_channel_conflicts_with_rc_option()
bool RC_Channels::flight_mode_channel_conflicts_with_rc_option () const
Definition at line 233 of file RC_Channels.cpp.
flight_mode_channel_number()
virtual int8_t RC_Channels::flight_mode_channel_number () const pure virtual
Implemented in RC_Channels_PIDTest, RC_Channels_RC, RC_Channels_Example, and RC_Channels_Example.
Referenced by flight_mode_channel().
gcs_overrides_enabled()
bool RC_Channels::gcs_overrides_enabled () const inline
Definition at line 501 of file RC_Channel.h.
get_arming_channel()
virtual RC_Channel * RC_Channels::get_arming_channel (void) const inline virtual
Definition at line 499 of file RC_Channel.h.
get_channel_pos()
RC_Channel::AuxSwitchPos RC_Channels::get_channel_pos (const uint8_t rcmapchan) const
Definition at line 1726 of file RC_Channel.cpp.
Referenced by AP_RunCam::map_rc_input_to_event().
get_fs_timeout_ms()
uint32_t RC_Channels::get_fs_timeout_ms () const inline
Definition at line 598 of file RC_Channel.h.
get_override_mask()
uint16_t RC_Channels::get_override_mask (void) const
Definition at line 119 of file RC_Channels.cpp.
get_override_timeout_ms()
bool RC_Channels::get_override_timeout_ms (uint32_t & returned_timeout_ms) const inline
Definition at line 537 of file RC_Channel.h.
get_pwm()
bool RC_Channels::get_pwm (uint8_t channel, uint16_t & pwm) const
Definition at line 247 of file RC_Channels.cpp.
get_radio_in() [1/2]
static uint16_t RC_Channels::get_radio_in (const uint8_t chan) inline static
Definition at line 447 of file RC_Channel.h.
get_radio_in() [2/2]
uint8_t RC_Channels::get_radio_in (uint16_t * chans, const uint8_t num_channels)
Definition at line 60 of file RC_Channels.cpp.
get_receiver_link_quality()
int16_t RC_Channels::get_receiver_link_quality (void) static
Definition at line 104 of file RC_Channels.cpp.
Referenced by AP_RSSI::read_receiver_link_quality().
get_receiver_rssi()
int16_t RC_Channels::get_receiver_rssi (void) static
Definition at line 100 of file RC_Channels.cpp.
Referenced by AP_RSSI::read_receiver_rssi().
get_singleton()
static RC_Channels * RC_Channels::get_singleton () inline static
Definition at line 440 of file RC_Channel.h.
Referenced by AP_RCProtocol_Backend::log_data(), and rc().
get_valid_channel_count()
uint8_t RC_Channels::get_valid_channel_count (void) static
Definition at line 95 of file RC_Channels.cpp.
Referenced by AP_Tuning::check_input().
has_active_overrides()
bool RC_Channels::has_active_overrides (void) static
Definition at line 139 of file RC_Channels.cpp.
has_ever_seen_rc_input()
bool RC_Channels::has_ever_seen_rc_input () const inline
Definition at line 593 of file RC_Channel.h.
has_had_rc_override()
bool RC_Channels::has_had_rc_override () const inline
Definition at line 558 of file RC_Channel.h.
has_had_rc_receiver()
bool RC_Channels::has_had_rc_receiver () const inline
Definition at line 555 of file RC_Channel.h.
has_valid_input()
virtual bool RC_Channels::has_valid_input () const inline virtual
Definition at line 497 of file RC_Channel.h.
Referenced by read_aux_all(), and read_mode_switch().
in_rc_failsafe()
virtual bool RC_Channels::in_rc_failsafe () const inline virtual
Definition at line 496 of file RC_Channel.h.
init()
void RC_Channels::init (void)
Definition at line 50 of file RC_Channels.cpp.
Referenced by setup().
init_aux_all()
void RC_Channels::init_aux_all ()
Definition at line 182 of file RC_Channels.cpp.
Referenced by init().
last_input_ms()
uint32_t RC_Channels::last_input_ms () const inline
Definition at line 567 of file RC_Channel.h.
lua_rc_channel()
RC_Channel * RC_Channels::lua_rc_channel (const uint8_t chan) inline
Definition at line 464 of file RC_Channel.h.
new_override_received()
void RC_Channels::new_override_received () inline protected
Definition at line 602 of file RC_Channel.h.
Referenced by RC_Channel::set_override().
option_is_enabled()
bool RC_Channels::option_is_enabled (Option option) const inline
Definition at line 526 of file RC_Channel.h.
Referenced by arming_check_throttle(), AP_RCProtocol_FPort::decode_downlink(), AP_RCProtocol_CRSF::get_bootstrap_baud_rate(), RC_Channel::read_3pos_switch(), and AP_RCProtocol_CRSF::update().
rc_channel()
static RC_Channel * RC_Channels::rc_channel (const uint8_t chan) inline static
Definition at line 454 of file RC_Channel.h.
Referenced by flight_mode_channel(), get_pwm(), run_aux_function(), and AP_OSD::update_current_screen().
read_aux_all()
void RC_Channels::read_aux_all ()
Definition at line 159 of file RC_Channels.cpp.
read_input()
bool RC_Channels::read_input (void)
Definition at line 73 of file RC_Channels.cpp.
Referenced by loop().
read_mode_switch()
void RC_Channels::read_mode_switch () virtual
Definition at line 218 of file RC_Channels.cpp.
receiver_bind()
bool RC_Channels::receiver_bind (const int dsmMode) static
Definition at line 151 of file RC_Channels.cpp.
reset_mode_switch()
void RC_Channels::reset_mode_switch ()
Definition at line 209 of file RC_Channels.cpp.
Referenced by init_aux_all().
run_aux_function()
bool RC_Channels::run_aux_function (RC_Channel::AUX_FUNC ch_option, RC_Channel::AuxSwitchPos pos, RC_Channel::AuxFuncTriggerSource source) inline
Definition at line 571 of file RC_Channel.h.
set_gcs_overrides_enabled()
void RC_Channels::set_gcs_overrides_enabled (bool enable) inline
Definition at line 502 of file RC_Channel.h.
Referenced by RC_Channel::do_aux_function_rc_override_enable().
set_override()
void RC_Channels::set_override (const uint8_t chan, const int16_t value, const uint32_t timestamp_ms = 0) static
Definition at line 131 of file RC_Channels.cpp.
Friends And Related Symbol Documentation
RC_Channel
friend class RC_Channel friend
Definition at line 433 of file RC_Channel.h.
SRV_Channels
friend class SRV_Channels friend
Definition at line 432 of file RC_Channel.h.
Member Data Documentation
_fs_timeout
AP_Float RC_Channels::_fs_timeout private
Definition at line 620 of file RC_Channel.h.
Referenced by get_fs_timeout_ms().
_gcs_overrides_enabled
bool RC_Channels::_gcs_overrides_enabled = true private
Definition at line 628 of file RC_Channel.h.
Referenced by gcs_overrides_enabled(), and set_gcs_overrides_enabled().
_has_ever_seen_rc_input
bool RC_Channels::_has_ever_seen_rc_input private
Definition at line 623 of file RC_Channel.h.
Referenced by has_ever_seen_rc_input(), and read_input().
_has_had_override
bool RC_Channels::_has_had_override private
Definition at line 615 of file RC_Channel.h.
Referenced by has_had_rc_override(), and new_override_received().
_has_had_rc_receiver
bool RC_Channels::_has_had_rc_receiver private
Definition at line 614 of file RC_Channel.h.
Referenced by has_had_rc_receiver(), and read_input().
_options
AP_Int32 RC_Channels::_options private
Definition at line 618 of file RC_Channel.h.
Referenced by option_is_enabled().
_override_timeout
AP_Float RC_Channels::_override_timeout private
Definition at line 617 of file RC_Channel.h.
Referenced by get_override_timeout_ms().
_protocols
AP_Int32 RC_Channels::_protocols private
Definition at line 619 of file RC_Channel.h.
Referenced by enabled_protocols().
_singleton
RC_Channels * RC_Channels::_singleton static private
Definition at line 608 of file RC_Channel.h.
Referenced by enabled_protocols(), get_radio_in(), get_singleton(), rc_channel(), and RC_Channels().
channels
RC_Channel* RC_Channels::channels static private
Definition at line 610 of file RC_Channel.h.
gcs_is_calibrating
bool RC_Channels::gcs_is_calibrating private
Definition at line 631 of file RC_Channel.h.
Referenced by calibrating(), and calibrating().
has_new_overrides
bool RC_Channels::has_new_overrides private
Definition at line 613 of file RC_Channel.h.
Referenced by new_override_received(), and read_input().
last_update_ms
uint32_t RC_Channels::last_update_ms private
Definition at line 612 of file RC_Channel.h.
Referenced by last_input_ms(), and read_input().
var_info
const AP_Param::GroupInfo RC_Channels::var_info static
Definition at line 19 of file RC_Channel.h.
The documentation for this class was generated from the following files:
libraries/RC_Channel/RC_Channel.h
libraries/RC_Channel/RC_Channel.cpp
libraries/RC_Channel/RC_Channels.cpp
libraries/RC_Channel/RC_Channels_VarInfo.h