APM:Libraries: ChibiOS::Scheduler Class Reference
ChibiOS::Scheduler Class Reference
#include <Scheduler.h>
Public Member Functions
Scheduler ()
void init () override
void delay (uint16_t ms) override
void delay_microseconds (uint16_t us) override
void delay_microseconds_boost (uint16_t us) override
void boost_end (void) override
void register_timer_process (AP_HAL::MemberProc) override
void register_io_process (AP_HAL::MemberProc) override
void register_timer_failsafe (AP_HAL::Proc, uint32_t period_us) override
void reboot (bool hold_in_bootloader) override
bool in_main_thread () const override
void set_system_initialized () override
bool is_system_initialized () override
void hal_initialized ()
bool check_called_boost (void)
void _expect_delay_ms (uint32_t ms)
void expect_delay_ms (uint32_t ms) override
bool in_expected_delay (void) const override
void * disable_interrupts_save (void) override
void restore_interrupts (void *) override
bool thread_create (AP_HAL::MemberProc, const char *name, uint32_t stack_size, priority_base base, int8_t priority) override
void watchdog_pat (void)
Public Member Functions inherited from AP_HAL::Scheduler
Scheduler ()
virtual void register_delay_callback (AP_HAL::Proc, uint16_t min_time_ms)
virtual bool in_delay_callback () const
virtual void stop_clock (uint64_t time_usec)
virtual void call_delay_cb ()
Private Member Functions
uint8_t calculate_thread_priority (priority_base base, int8_t priority) const
void _run_timers ()
void _run_io (void)
void check_stack_free (void)
Static Private Member Functions
static void _timer_thread (void *arg)
static void _rcout_thread (void *arg)
static void _rcin_thread (void *arg)
static void _io_thread (void *arg)
static void _storage_thread (void *arg)
static void _uart_thread (void *arg)
static void _monitor_thread (void *arg)
static void thread_create_trampoline (void *ctx)
static void try_force_mutex (void)
Private Attributes
bool _initialized
volatile bool _hal_initialized
AP_HAL::Proc _failsafe
bool _called_boost
bool _priority_boosted
uint32_t expect_delay_start
uint32_t expect_delay_length
uint32_t expect_delay_nesting
HAL_Semaphore expect_delay_sem
AP_HAL::MemberProc _timer_proc [CHIBIOS_SCHEDULER_MAX_TIMER_PROCS]
uint8_t _num_timer_procs
volatile bool _in_timer_proc
AP_HAL::MemberProc _io_proc [CHIBIOS_SCHEDULER_MAX_TIMER_PROCS]
uint8_t _num_io_procs
volatile bool _in_io_proc
uint32_t last_watchdog_pat_ms
thread_t * _timer_thread_ctx
thread_t * _rcout_thread_ctx
thread_t * _rcin_thread_ctx
thread_t * _io_thread_ctx
thread_t * _storage_thread_ctx
thread_t * _monitor_thread_ctx
binary_semaphore_t _timer_semaphore
binary_semaphore_t _io_semaphore
Additional Inherited Members
Public Types inherited from AP_HAL::Scheduler
enum priority_base {
PRIORITY_BOOST , PRIORITY_MAIN , PRIORITY_SPI , PRIORITY_I2C ,
PRIORITY_CAN , PRIORITY_TIMER , PRIORITY_RCOUT , PRIORITY_LED ,
PRIORITY_RCIN , PRIORITY_IO , PRIORITY_UART , PRIORITY_STORAGE ,
PRIORITY_SCRIPTING , PRIORITY_NET
}
Public Attributes inherited from AP_HAL::Scheduler
uint16_t _min_delay_cb_ms
Detailed Description
Definition at line 88 of file Scheduler.h.
Constructor & Destructor Documentation
Scheduler()
Scheduler::Scheduler ()
Definition at line 89 of file Scheduler.cpp.
Member Function Documentation
_expect_delay_ms()
void Scheduler::_expect_delay_ms (uint32_t ms)
Definition at line 746 of file Scheduler.cpp.
Referenced by expect_delay_ms().
_io_thread()
void Scheduler::_io_thread (void * arg) static private
Definition at line 547 of file Scheduler.cpp.
Referenced by init().
_monitor_thread()
void Scheduler::_monitor_thread (void * arg) static private
Definition at line 406 of file Scheduler.cpp.
Referenced by init().
_rcin_thread()
void Scheduler::_rcin_thread (void * arg) static private
Definition at line 513 of file Scheduler.cpp.
Referenced by init().
_rcout_thread()
void Scheduler::_rcout_thread (void * arg) static private
Definition at line 363 of file Scheduler.cpp.
Referenced by init().
_run_io()
void Scheduler::_run_io (void) private
Definition at line 526 of file Scheduler.cpp.
Referenced by _io_thread().
_run_timers()
void Scheduler::_run_timers () private
Definition at line 312 of file Scheduler.cpp.
Referenced by _timer_thread().
_storage_thread()
void Scheduler::_storage_thread (void * arg) static private
Definition at line 620 of file Scheduler.cpp.
Referenced by init().
_timer_thread()
void Scheduler::_timer_thread (void * arg) static private
Definition at line 343 of file Scheduler.cpp.
Referenced by init().
_uart_thread()
static void ChibiOS::Scheduler::_uart_thread (void * arg) static private
boost_end()
void Scheduler::boost_end (void) override virtual
Reimplemented from AP_HAL::Scheduler.
Definition at line 181 of file Scheduler.cpp.
Referenced by _expect_delay_ms().
calculate_thread_priority()
uint8_t Scheduler::calculate_thread_priority (priority_base base, int8_t priority) const private
Definition at line 683 of file Scheduler.cpp.
Referenced by thread_create().
check_called_boost()
bool Scheduler::check_called_boost (void)
Definition at line 210 of file Scheduler.cpp.
Referenced by main_loop().
check_stack_free()
void Scheduler::check_stack_free (void) private
Definition at line 821 of file Scheduler.cpp.
Referenced by _io_thread().
delay()
void Scheduler::delay (uint16_t ms) override virtual
Implements AP_HAL::Scheduler.
Definition at line 219 of file Scheduler.cpp.
Referenced by _monitor_thread().
delay_microseconds()
void Scheduler::delay_microseconds (uint16_t us) override virtual
Implements AP_HAL::Scheduler.
Definition at line 153 of file Scheduler.cpp.
Referenced by _io_thread(), _rcin_thread(), _rcout_thread(), _storage_thread(), _timer_thread(), delay(), and delay_microseconds_boost().
delay_microseconds_boost()
void Scheduler::delay_microseconds_boost (uint16_t us) override virtual
Reimplemented from AP_HAL::Scheduler.
Definition at line 197 of file Scheduler.cpp.
disable_interrupts_save()
void * Scheduler::disable_interrupts_save (void) override virtual
Reimplemented from AP_HAL::Scheduler.
Definition at line 659 of file Scheduler.cpp.
expect_delay_ms()
void Scheduler::expect_delay_ms (uint32_t ms) override virtual
Reimplemented from AP_HAL::Scheduler.
Definition at line 786 of file Scheduler.cpp.
hal_initialized()
void ChibiOS::Scheduler::hal_initialized () inline
Definition at line 108 of file Scheduler.h.
Referenced by main_loop().
in_expected_delay()
bool Scheduler::in_expected_delay (void) const override virtual
Reimplemented from AP_HAL::Scheduler.
Definition at line 383 of file Scheduler.cpp.
Referenced by _monitor_thread(), and _timer_thread().
in_main_thread()
bool ChibiOS::Scheduler::in_main_thread () const inline override virtual
Implements AP_HAL::Scheduler.
Definition at line 104 of file Scheduler.h.
Referenced by _expect_delay_ms(), boost_end(), delay(), delay_microseconds_boost(), and expect_delay_ms().
init()
void Scheduler::init () override virtual
Implements AP_HAL::Scheduler.
Definition at line 93 of file Scheduler.cpp.
is_system_initialized()
bool ChibiOS::Scheduler::is_system_initialized () inline override virtual
Implements AP_HAL::Scheduler.
Definition at line 107 of file Scheduler.h.
reboot()
void Scheduler::reboot (bool hold_in_bootloader) override virtual
Implements AP_HAL::Scheduler.
Definition at line 279 of file Scheduler.cpp.
register_io_process()
void Scheduler::register_io_process (AP_HAL::MemberProc proc) override virtual
Implements AP_HAL::Scheduler.
Definition at line 255 of file Scheduler.cpp.
register_timer_failsafe()
void Scheduler::register_timer_failsafe (AP_HAL::Proc failsafe, uint32_t period_us) override virtual
Implements AP_HAL::Scheduler.
Definition at line 274 of file Scheduler.cpp.
register_timer_process()
void Scheduler::register_timer_process (AP_HAL::MemberProc proc) override virtual
Implements AP_HAL::Scheduler.
Definition at line 236 of file Scheduler.cpp.
restore_interrupts()
void Scheduler::restore_interrupts (void * state) override virtual
Reimplemented from AP_HAL::Scheduler.
Definition at line 667 of file Scheduler.cpp.
set_system_initialized()
void Scheduler::set_system_initialized () override virtual
Implements AP_HAL::Scheduler.
Definition at line 645 of file Scheduler.cpp.
thread_create()
bool Scheduler::thread_create (AP_HAL::MemberProc proc, const char * name, uint32_t stack_size, priority_base base, int8_t priority) override virtual
Reimplemented from AP_HAL::Scheduler.
Definition at line 717 of file Scheduler.cpp.
thread_create_trampoline()
void Scheduler::thread_create_trampoline (void * ctx) static private
Definition at line 675 of file Scheduler.cpp.
Referenced by thread_create().
try_force_mutex()
void Scheduler::try_force_mutex (void) static private
Definition at line 859 of file Scheduler.cpp.
Referenced by _monitor_thread().
watchdog_pat()
void Scheduler::watchdog_pat (void)
Definition at line 796 of file Scheduler.cpp.
Referenced by _expect_delay_ms(), _timer_thread(), and main_loop().
Member Data Documentation
_called_boost
bool ChibiOS::Scheduler::_called_boost private
Definition at line 151 of file Scheduler.h.
Referenced by check_called_boost(), and delay_microseconds_boost().
_failsafe
AP_HAL::Proc ChibiOS::Scheduler::_failsafe private
Definition at line 150 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_failsafe().
_hal_initialized
volatile bool ChibiOS::Scheduler::_hal_initialized private
Definition at line 149 of file Scheduler.h.
Referenced by _io_thread(), _rcin_thread(), _rcout_thread(), _storage_thread(), _timer_thread(), and hal_initialized().
_in_io_proc
volatile bool ChibiOS::Scheduler::_in_io_proc private
Definition at line 164 of file Scheduler.h.
Referenced by _run_io().
_in_timer_proc
volatile bool ChibiOS::Scheduler::_in_timer_proc private
Definition at line 160 of file Scheduler.h.
Referenced by _run_timers().
_initialized
bool ChibiOS::Scheduler::_initialized private
Definition at line 148 of file Scheduler.h.
Referenced by _monitor_thread(), in_expected_delay(), is_system_initialized(), and set_system_initialized().
_io_proc
AP_HAL::MemberProc ChibiOS::Scheduler::_io_proc[CHIBIOS_SCHEDULER_MAX_TIMER_PROCS] private
Definition at line 162 of file Scheduler.h.
Referenced by _run_io(), and register_io_process().
_io_semaphore
binary_semaphore_t ChibiOS::Scheduler::_io_semaphore private
Definition at line 176 of file Scheduler.h.
Referenced by _run_io(), init(), and register_io_process().
_io_thread_ctx
thread_t* ChibiOS::Scheduler::_io_thread_ctx private
Definition at line 170 of file Scheduler.h.
Referenced by init().
_monitor_thread_ctx
thread_t* ChibiOS::Scheduler::_monitor_thread_ctx private
Definition at line 172 of file Scheduler.h.
Referenced by init().
_num_io_procs
uint8_t ChibiOS::Scheduler::_num_io_procs private
Definition at line 163 of file Scheduler.h.
Referenced by _run_io(), and register_io_process().
_num_timer_procs
uint8_t ChibiOS::Scheduler::_num_timer_procs private
Definition at line 159 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_process().
_priority_boosted
bool ChibiOS::Scheduler::_priority_boosted private
Definition at line 152 of file Scheduler.h.
Referenced by boost_end(), and delay_microseconds_boost().
_rcin_thread_ctx
thread_t* ChibiOS::Scheduler::_rcin_thread_ctx private
Definition at line 169 of file Scheduler.h.
Referenced by init().
_rcout_thread_ctx
thread_t* ChibiOS::Scheduler::_rcout_thread_ctx private
Definition at line 168 of file Scheduler.h.
Referenced by init().
_storage_thread_ctx
thread_t* ChibiOS::Scheduler::_storage_thread_ctx private
Definition at line 171 of file Scheduler.h.
Referenced by init().
_timer_proc
AP_HAL::MemberProc ChibiOS::Scheduler::_timer_proc[CHIBIOS_SCHEDULER_MAX_TIMER_PROCS] private
Definition at line 158 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_process().
_timer_semaphore
binary_semaphore_t ChibiOS::Scheduler::_timer_semaphore private
Definition at line 175 of file Scheduler.h.
Referenced by _run_timers(), init(), and register_timer_process().
_timer_thread_ctx
thread_t* ChibiOS::Scheduler::_timer_thread_ctx private
Definition at line 167 of file Scheduler.h.
Referenced by init().
expect_delay_length
uint32_t ChibiOS::Scheduler::expect_delay_length private
Definition at line 154 of file Scheduler.h.
Referenced by _expect_delay_ms(), and in_expected_delay().
expect_delay_nesting
uint32_t ChibiOS::Scheduler::expect_delay_nesting private
Definition at line 155 of file Scheduler.h.
Referenced by _expect_delay_ms().
expect_delay_sem
HAL_Semaphore ChibiOS::Scheduler::expect_delay_sem private
Definition at line 156 of file Scheduler.h.
Referenced by _expect_delay_ms().
expect_delay_start
uint32_t ChibiOS::Scheduler::expect_delay_start private
Definition at line 153 of file Scheduler.h.
Referenced by _expect_delay_ms(), and in_expected_delay().
last_watchdog_pat_ms
uint32_t ChibiOS::Scheduler::last_watchdog_pat_ms private
Definition at line 165 of file Scheduler.h.
Referenced by _monitor_thread(), and watchdog_pat().
The documentation for this class was generated from the following files:
libraries/AP_HAL_ChibiOS/Scheduler.h
libraries/AP_HAL_ChibiOS/Scheduler.cpp