APM:Libraries: AP_InertialSensor_LSM9DS1 Class Reference
AP_InertialSensor_LSM9DS1 Class Reference
#include <AP_InertialSensor_LSM9DS1.h>
Classes
struct sensor_raw_data
Public Member Functions
virtual ~AP_InertialSensor_LSM9DS1 ()
void start (void) override
bool update () override
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void accumulate ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t get_id () const
float get_clip_limit () const
virtual bool get_output_banner (char *banner, uint8_t banner_len)
Static Public Member Functions
static AP_InertialSensor_Backend * probe (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev, enum Rotation rotation)
Private Types
enum accel_scale { A_SCALE_2G = 0 , A_SCALE_4G , A_SCALE_8G , A_SCALE_16G }
Private Member Functions
AP_InertialSensor_LSM9DS1 (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev, int drdy_pin_num_xg, enum Rotation rotation)
void _poll_data ()
void _fifo_reset ()
bool _init_sensor ()
bool _hardware_init ()
void _gyro_init ()
void _accel_init ()
void _set_gyro_scale ()
void _set_accel_scale (accel_scale scale)
uint8_t _register_read (uint8_t reg)
void _register_write (uint8_t reg, uint8_t val, bool checked=false)
void _read_data_transaction_x (uint16_t samples)
void _read_data_transaction_g (uint16_t samples)
Static Private Member Functions
static AP_InertialSensor_Backend * detect (AP_InertialSensor &imu)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::SPIDevice > _dev
AP_HAL::Semaphore * _spi_sem
AP_HAL::DigitalSource * _drdy_pin_xg
float _gyro_scale
float _accel_scale
int _drdy_pin_num_xg
uint8_t _gyro_instance
uint8_t _accel_instance
enum Rotation _rotation
Additional Inherited Members
Public Types inherited from AP_InertialSensor_Backend
enum DevTypes {
DEVTYPE_BMI160 = 0x09 , DEVTYPE_L3G4200D = 0x10 , DEVTYPE_ACC_LSM303D = 0x11 , DEVTYPE_ACC_BMA180 = 0x12 ,
DEVTYPE_ACC_MPU6000 = 0x13 , DEVTYPE_ACC_MPU9250 = 0x16 , DEVTYPE_ACC_IIS328DQ = 0x17 , DEVTYPE_ACC_LSM9DS1 = 0x18 ,
DEVTYPE_GYR_MPU6000 = 0x21 , DEVTYPE_GYR_L3GD20 = 0x22 , DEVTYPE_GYR_MPU9250 = 0x24 , DEVTYPE_GYR_I3G4250D = 0x25 ,
DEVTYPE_GYR_LSM9DS1 = 0x26 , DEVTYPE_INS_ICM20789 = 0x27 , DEVTYPE_INS_ICM20689 = 0x28 , DEVTYPE_INS_BMI055 = 0x29 ,
DEVTYPE_SITL = 0x2A , DEVTYPE_INS_BMI088 = 0x2B , DEVTYPE_INS_ICM20948 = 0x2C , DEVTYPE_INS_ICM20648 = 0x2D ,
DEVTYPE_INS_ICM20649 = 0x2E , DEVTYPE_INS_ICM20602 = 0x2F , DEVTYPE_INS_ICM20601 = 0x30 , DEVTYPE_INS_ADIS1647X = 0x31 ,
DEVTYPE_SERIAL = 0x32 , DEVTYPE_INS_ICM40609 = 0x33 , DEVTYPE_INS_ICM42688 = 0x34 , DEVTYPE_INS_ICM42605 = 0x35 ,
DEVTYPE_INS_ICM40605 = 0x36 , DEVTYPE_INS_IIM42652 = 0x37 , DEVTYPE_BMI270 = 0x38 , DEVTYPE_INS_BMI085 = 0x39 ,
DEVTYPE_INS_ICM42670 = 0x3A , DEVTYPE_INS_ICM45686 = 0x3B , DEVTYPE_INS_SCHA63T = 0x3C
}
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel) __RAMFUNC__
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro) __RAMFUNC__
void _publish_gyro (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void apply_gyro_filters (const uint8_t instance, const Vector3f &gyro)
void save_gyro_window (const uint8_t instance, const Vector3f &gyro, uint8_t phase)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0) __RAMFUNC__
void _notify_new_delta_angle (uint8_t instance, const Vector3f &dangle)
void _publish_accel (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0, bool fsync_set=false) __RAMFUNC__
void _notify_new_delta_velocity (uint8_t instance, const Vector3f &dvelocity)
void _set_accel_oversampling (uint8_t instance, uint8_t n)
void _set_gyro_oversampling (uint8_t instance, uint8_t n)
void _set_accel_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_gyro_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_raw_sample_accel_multiplier (uint8_t instance, uint16_t mul)
void _set_raw_sample_gyro_multiplier (uint8_t instance, uint16_t mul)
void _update_sensor_rate (uint16_t &count, uint32_t &start_us, float &rate_hz) const __RAMFUNC__
bool sensors_converging () const
void _set_accel_max_abs_offset (uint8_t instance, float offset)
float _accel_raw_sample_rate (uint8_t instance) const
void _set_accel_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
float _gyro_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
void _publish_temperature (uint8_t instance, float temperature)
void _inc_accel_error_count (uint8_t instance) __RAMFUNC__
void _inc_gyro_error_count (uint8_t instance) __RAMFUNC__
uint16_t _accel_filter_cutoff (void) const
uint16_t _gyro_filter_cutoff (void) const
uint16_t get_loop_rate_hz (void) const
void update_gyro (uint8_t instance) __RAMFUNC__
void update_accel (uint8_t instance) __RAMFUNC__
void set_gyro_orientation (uint8_t instance, enum Rotation rotation)
void set_accel_orientation (uint8_t instance, enum Rotation rotation)
void increment_clip_count (uint8_t instance)
bool enable_fast_sampling (uint8_t instance) const
bool enable_highres_sampling (uint8_t instance) const
uint8_t get_fast_sampling_rate () const
void _notify_new_accel_sensor_rate_sample (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_gyro_sensor_rate_sample (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void notify_accel_fifo_reset (uint8_t instance) __RAMFUNC__
void notify_gyro_fifo_reset (uint8_t instance) __RAMFUNC__
void log_register_change (uint32_t bus_id, const AP_HAL::Device::checkreg &reg) __RAMFUNC__
void Write_GYR (const uint8_t instance, const uint64_t sample_us, const Vector3f &gyro, bool use_sample_timestamp=false) const __RAMFUNC__
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
HAL_Semaphore _sem
float _clip_limit = 15.5f * GRAVITY_MSS
int16_t _id = -1
uint16_t _last_accel_filter_hz
uint16_t _last_gyro_filter_hz
Detailed Description
Definition at line 12 of file AP_InertialSensor_LSM9DS1.h.
Member Enumeration Documentation
accel_scale
enum AP_InertialSensor_LSM9DS1::accel_scale private
Enumerator
A_SCALE_2G
A_SCALE_4G
A_SCALE_8G
A_SCALE_16G
Definition at line 36 of file AP_InertialSensor_LSM9DS1.h.
Constructor & Destructor Documentation
~AP_InertialSensor_LSM9DS1()
virtual AP_InertialSensor_LSM9DS1::~AP_InertialSensor_LSM9DS1 () inline virtual
Definition at line 15 of file AP_InertialSensor_LSM9DS1.h.
AP_InertialSensor_LSM9DS1()
AP_InertialSensor_LSM9DS1::AP_InertialSensor_LSM9DS1 (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev, int drdy_pin_num_xg, enum Rotation rotation) private
Definition at line 196 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by probe().
Member Function Documentation
_accel_init()
void AP_InertialSensor_LSM9DS1::_accel_init () private
Definition at line 373 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by _hardware_init().
_fifo_reset()
void AP_InertialSensor_LSM9DS1::_fifo_reset () private
Definition at line 300 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by _hardware_init(), and _poll_data().
_gyro_init()
void AP_InertialSensor_LSM9DS1::_gyro_init () private
Definition at line 360 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by _hardware_init().
_hardware_init()
bool AP_InertialSensor_LSM9DS1::_hardware_init () private
Definition at line 247 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by _init_sensor().
_init_sensor()
bool AP_InertialSensor_LSM9DS1::_init_sensor () private
Definition at line 227 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by probe().
_poll_data()
void AP_InertialSensor_LSM9DS1::_poll_data () private
Timer process to poll for new data from the LSM9DS1.
Definition at line 415 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by start().
_read_data_transaction_g()
void AP_InertialSensor_LSM9DS1::_read_data_transaction_g (uint16_t samples) private
Definition at line 475 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by _poll_data().
_read_data_transaction_x()
void AP_InertialSensor_LSM9DS1::_read_data_transaction_x (uint16_t samples) private
Definition at line 438 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by _poll_data().
_register_read()
uint8_t AP_InertialSensor_LSM9DS1::_register_read (uint8_t reg) private
Definition at line 347 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by _fifo_reset(), _hardware_init(), and _poll_data().
_register_write()
void AP_InertialSensor_LSM9DS1::_register_write (uint8_t reg, uint8_t val, bool checked = false) private
Definition at line 355 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by _accel_init(), and _gyro_init().
_set_accel_scale()
void AP_InertialSensor_LSM9DS1::_set_accel_scale (accel_scale scale) private
Definition at line 396 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by _accel_init().
_set_gyro_scale()
void AP_InertialSensor_LSM9DS1::_set_gyro_scale () private
Definition at line 386 of file AP_InertialSensor_LSM9DS1.cpp.
Referenced by _gyro_init().
detect()
static AP_InertialSensor_Backend * AP_InertialSensor_LSM9DS1::detect (AP_InertialSensor & imu) static private
probe()
AP_InertialSensor_Backend * AP_InertialSensor_LSM9DS1::probe (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev, enum Rotation rotation) static
Definition at line 208 of file AP_InertialSensor_LSM9DS1.cpp.
start()
void AP_InertialSensor_LSM9DS1::start (void) override virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 331 of file AP_InertialSensor_LSM9DS1.cpp.
update()
bool AP_InertialSensor_LSM9DS1::update (void) override virtual
Implements AP_InertialSensor_Backend.
Definition at line 508 of file AP_InertialSensor_LSM9DS1.cpp.
Member Data Documentation
_accel_instance
uint8_t AP_InertialSensor_LSM9DS1::_accel_instance private
Definition at line 72 of file AP_InertialSensor_LSM9DS1.h.
Referenced by _fifo_reset(), _poll_data(), _read_data_transaction_x(), start(), and update().
_accel_scale
float AP_InertialSensor_LSM9DS1::_accel_scale private
Definition at line 69 of file AP_InertialSensor_LSM9DS1.h.
Referenced by _read_data_transaction_x(), and _set_accel_scale().
_dev
AP_HAL::OwnPtr<AP_HAL::SPIDevice> AP_InertialSensor_LSM9DS1::_dev private
Definition at line 65 of file AP_InertialSensor_LSM9DS1.h.
Referenced by _fifo_reset(), _hardware_init(), _init_sensor(), _poll_data(), _read_data_transaction_g(), _read_data_transaction_x(), _register_read(), _register_write(), and start().
_drdy_pin_num_xg
int AP_InertialSensor_LSM9DS1::_drdy_pin_num_xg private
Definition at line 70 of file AP_InertialSensor_LSM9DS1.h.
Referenced by _init_sensor().
_drdy_pin_xg
AP_HAL::DigitalSource* AP_InertialSensor_LSM9DS1::_drdy_pin_xg private
Definition at line 67 of file AP_InertialSensor_LSM9DS1.h.
Referenced by _init_sensor().
_gyro_instance
uint8_t AP_InertialSensor_LSM9DS1::_gyro_instance private
Definition at line 71 of file AP_InertialSensor_LSM9DS1.h.
Referenced by _fifo_reset(), _read_data_transaction_g(), start(), and update().
_gyro_scale
float AP_InertialSensor_LSM9DS1::_gyro_scale private
Definition at line 68 of file AP_InertialSensor_LSM9DS1.h.
Referenced by _read_data_transaction_g(), and _set_gyro_scale().
_rotation
enum Rotation AP_InertialSensor_LSM9DS1::_rotation private
Definition at line 73 of file AP_InertialSensor_LSM9DS1.h.
Referenced by start().
_spi_sem
AP_HAL::Semaphore* AP_InertialSensor_LSM9DS1::_spi_sem private
Definition at line 66 of file AP_InertialSensor_LSM9DS1.h.
Referenced by _hardware_init(), and _init_sensor().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS1.h
libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS1.cpp