APM:Libraries: AP_NavEKF_Source Class Reference
AP_NavEKF_Source Class Reference
#include <AP_NavEKF_Source.h>
Classes
struct SourceSet
Public Types
enum class SourceXY : uint8_t {
NONE = 0 , GPS = 3 , BEACON = 4 , OPTFLOW = 5 ,
EXTNAV = 6 , WHEEL_ENCODER = 7
}
enum class SourceZ : uint8_t {
NONE = 0 , BARO = 1 , RANGEFINDER = 2 , GPS = 3 ,
BEACON = 4 , EXTNAV = 6
}
enum class SourceYaw : uint8_t {
NONE = 0 , COMPASS = 1 , GPS = 2 , GPS_COMPASS_FALLBACK = 3 ,
EXTNAV = 6 , GSF = 8
}
enum class SourceOptions { FUSE_ALL_VELOCITIES = (1 << 0) }
Public Member Functions
AP_NavEKF_Source ()
CLASS_NO_COPY (AP_NavEKF_Source)
void init ()
SourceXY getPosXYSource () const
SourceZ getPosZSource () const
void setPosVelYawSourceSet (uint8_t source_set_idx)
uint8_t getPosVelYawSourceSet () const
SourceXY getVelXYSource () const
SourceZ getVelZSource () const
bool useVelXYSource (SourceXY velxy_source) const
bool useVelZSource (SourceZ velz_source) const
bool haveVelZSource () const
SourceYaw getYawSource () const
void align_inactive_sources ()
bool usingGPS () const
bool configured ()
void mark_configured ()
bool pre_arm_check (bool requires_position, char *failure_msg, uint8_t failure_msg_len) const
bool ext_nav_enabled (void) const
bool gps_yaw_enabled (void) const
bool wheel_encoder_enabled (void) const
uint8_t get_active_source_set () const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
struct AP_NavEKF_Source::SourceSet _source_set [AP_NAKEKF_SOURCE_SET_MAX]
AP_Int16 _options
uint8_t active_source_set
bool _configured
Detailed Description
Definition at line 7 of file AP_NavEKF_Source.h.
Member Enumeration Documentation
SourceOptions
enum class AP_NavEKF_Source::SourceOptions strong
Enumerator
FUSE_ALL_VELOCITIES
Definition at line 49 of file AP_NavEKF_Source.h.
SourceXY
enum class AP_NavEKF_Source::SourceXY : uint8_t strong
Enumerator
NONE
GPS
BEACON
OPTFLOW
EXTNAV
WHEEL_ENCODER
Definition at line 17 of file AP_NavEKF_Source.h.
SourceYaw
enum class AP_NavEKF_Source::SourceYaw : uint8_t strong
Enumerator
NONE
COMPASS
GPS
GPS_COMPASS_FALLBACK
EXTNAV
GSF
Definition at line 39 of file AP_NavEKF_Source.h.
SourceZ
enum class AP_NavEKF_Source::SourceZ : uint8_t strong
Enumerator
NONE
BARO
RANGEFINDER
GPS
BEACON
EXTNAV
Definition at line 28 of file AP_NavEKF_Source.h.
Constructor & Destructor Documentation
AP_NavEKF_Source()
AP_NavEKF_Source::AP_NavEKF_Source ()
Definition at line 145 of file AP_NavEKF_Source.cpp.
Member Function Documentation
align_inactive_sources()
void AP_NavEKF_Source::align_inactive_sources ()
Definition at line 250 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3::UpdateFilter().
CLASS_NO_COPY()
AP_NavEKF_Source::CLASS_NO_COPY (AP_NavEKF_Source)
configured()
bool AP_NavEKF_Source::configured ()
Definition at line 304 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3::convert_parameters().
ext_nav_enabled()
bool AP_NavEKF_Source::ext_nav_enabled (void) const
Definition at line 515 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3_core::setup_core().
get_active_source_set()
uint8_t AP_NavEKF_Source::get_active_source_set () const
Definition at line 551 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3::get_active_source_set().
getPosVelYawSourceSet()
uint8_t AP_NavEKF_Source::getPosVelYawSourceSet () const inline
Definition at line 62 of file AP_NavEKF_Source.h.
getPosXYSource()
SourceXY AP_NavEKF_Source::getPosXYSource () const inline
Definition at line 57 of file AP_NavEKF_Source.h.
Referenced by align_inactive_sources(), NavEKF3::configuredToUseGPSForPosXY(), NavEKF3_core::InitialiseFilterBootstrap(), NavEKF3_core::readyToUseExtNav(), NavEKF3_core::readyToUseGPS(), NavEKF3_core::readyToUseRangeBeacon(), NavEKF3_core::runYawEstimatorCorrection(), NavEKF3_core::runYawEstimatorPrediction(), NavEKF3_core::SelectVelPosFusion(), NavEKF3::setOriginLLH(), NavEKF3_core::setOriginLLH(), NavEKF3_core::updateFilterStatus(), and usingGPS().
getPosZSource()
AP_NavEKF_Source::SourceZ AP_NavEKF_Source::getPosZSource () const
Definition at line 238 of file AP_NavEKF_Source.cpp.
Referenced by align_inactive_sources(), NavEKF3_core::FuseVelPosNED(), NavEKF3_core::getHeightControlLimit(), NavEKF3_core::selectHeightForFusion(), NavEKF3_core::updateFilterStatus(), and usingGPS().
getVelXYSource()
SourceXY AP_NavEKF_Source::getVelXYSource () const inline
Definition at line 65 of file AP_NavEKF_Source.h.
Referenced by usingGPS().
getVelZSource()
SourceZ AP_NavEKF_Source::getVelZSource () const inline
Definition at line 66 of file AP_NavEKF_Source.h.
Referenced by usingGPS().
getYawSource()
AP_NavEKF_Source::SourceYaw AP_NavEKF_Source::getYawSource () const
Definition at line 227 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3_core::checkGyroCalStatus(), NavEKF3_core::EKFGSF_resetMainFilterYaw(), NavEKF3_core::InitialiseFilterBootstrap(), NavEKF3::pre_arm_check(), NavEKF3_core::realignYawGPS(), NavEKF3_core::SelectMagFusion(), NavEKF3_core::updateMovementCheck(), NavEKF3_core::use_compass(), NavEKF3_core::using_extnav_for_yaw(), NavEKF3_core::using_noncompass_for_yaw(), and usingGPS().
gps_yaw_enabled()
bool AP_NavEKF_Source::gps_yaw_enabled (void) const
Definition at line 557 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3_core::setup_core().
haveVelZSource()
bool AP_NavEKF_Source::haveVelZSource () const
Definition at line 207 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3_core::FuseVelPosNED().
init()
void AP_NavEKF_Source::init ()
mark_configured()
void AP_NavEKF_Source::mark_configured ()
Definition at line 317 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3::convert_parameters().
pre_arm_check()
bool AP_NavEKF_Source::pre_arm_check (bool requires_position, char * failure_msg, uint8_t failure_msg_len) const
Definition at line 325 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3::pre_arm_check().
setPosVelYawSourceSet()
void AP_NavEKF_Source::setPosVelYawSourceSet (uint8_t source_set_idx)
Definition at line 151 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3::setPosVelYawSourceSet().
useVelXYSource()
bool AP_NavEKF_Source::useVelXYSource (SourceXY velxy_source) const
Definition at line 168 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3_core::getHeightControlLimit(), NavEKF3_core::readyToUseBodyOdm(), NavEKF3_core::readyToUseOptFlow(), NavEKF3_core::runYawEstimatorCorrection(), NavEKF3_core::runYawEstimatorPrediction(), NavEKF3_core::SelectFlowFusion(), and NavEKF3_core::SelectVelPosFusion().
useVelZSource()
bool AP_NavEKF_Source::useVelZSource (SourceZ velz_source) const
Definition at line 187 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3_core::readGpsData(), and NavEKF3_core::ResetHeight().
usingGPS()
bool AP_NavEKF_Source::usingGPS () const
Definition at line 294 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3_core::setup_core().
wheel_encoder_enabled()
bool AP_NavEKF_Source::wheel_encoder_enabled (void) const
Definition at line 539 of file AP_NavEKF_Source.cpp.
Referenced by NavEKF3_core::setup_core().
Member Data Documentation
_configured
bool AP_NavEKF_Source::_configured private
Definition at line 124 of file AP_NavEKF_Source.h.
Referenced by configured().
_options
AP_Int16 AP_NavEKF_Source::_options private
Definition at line 121 of file AP_NavEKF_Source.h.
Referenced by haveVelZSource(), useVelXYSource(), and useVelZSource().
_source_set
struct AP_NavEKF_Source::SourceSet AP_NavEKF_Source::_source_set[AP_NAKEKF_SOURCE_SET_MAX] private
Referenced by align_inactive_sources(), configured(), ext_nav_enabled(), getPosXYSource(), getPosZSource(), getVelXYSource(), getVelZSource(), getYawSource(), gps_yaw_enabled(), haveVelZSource(), mark_configured(), pre_arm_check(), useVelXYSource(), useVelZSource(), and wheel_encoder_enabled().
active_source_set
uint8_t AP_NavEKF_Source::active_source_set private
Definition at line 123 of file AP_NavEKF_Source.h.
Referenced by get_active_source_set(), getPosVelYawSourceSet(), getPosXYSource(), getPosZSource(), getVelXYSource(), getVelZSource(), getYawSource(), haveVelZSource(), setPosVelYawSourceSet(), useVelXYSource(), and useVelZSource().
var_info
const AP_Param::GroupInfo AP_NavEKF_Source::var_info static
Definition at line 24 of file AP_NavEKF_Source.h.
The documentation for this class was generated from the following files:
libraries/AP_NavEKF/AP_NavEKF_Source.h
libraries/AP_NavEKF/AP_NavEKF_Source.cpp