APM:Libraries: AP_RPM Class Reference
AP_RPM Class Reference
#include <AP_RPM.h>
Classes
struct RPM_State
Public Types
enum RPM_Type { RPM_TYPE_NONE = 0 , RPM_TYPE_PWM = 1 , RPM_TYPE_PIN = 2 }
Public Member Functions
AP_RPM ()
CLASS_NO_COPY (AP_RPM)
uint8_t num_sensors (void) const
void init (void)
void update (void)
bool get_rpm (uint8_t instance, float &rpm_value) const
float get_signal_quality (uint8_t instance) const
bool healthy (uint8_t instance) const
bool enabled (uint8_t instance) const
bool arming_checks (size_t buflen, char *buffer) const
Static Public Member Functions
static AP_RPM * get_singleton ()
Public Attributes
AP_RPM_Params _params [RPM_MAX_INSTANCES]
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void convert_params (void)
void Log_RPM () const
Private Attributes
RPM_State state [RPM_MAX_INSTANCES]
AP_RPM_Backend * drivers [RPM_MAX_INSTANCES]
uint8_t num_instances
Static Private Attributes
static AP_RPM * _singleton
Friends
class AP_RPM_Backend
Detailed Description
Definition at line 29 of file AP_RPM.h.
Member Enumeration Documentation
RPM_Type
enum AP_RPM::RPM_Type
Enumerator
RPM_TYPE_NONE
RPM_TYPE_PWM
RPM_TYPE_PIN
Definition at line 39 of file AP_RPM.h.
Constructor & Destructor Documentation
AP_RPM()
AP_RPM::AP_RPM (void)
Definition at line 49 of file AP_RPM.cpp.
Member Function Documentation
arming_checks()
bool AP_RPM::arming_checks (size_t buflen, char * buffer) const
Definition at line 262 of file AP_RPM.cpp.
Referenced by AP_Arming::system_checks().
CLASS_NO_COPY()
AP_RPM::CLASS_NO_COPY (AP_RPM)
convert_params()
void AP_RPM::convert_params (void) private
Definition at line 119 of file AP_RPM.cpp.
Referenced by init().
enabled()
bool AP_RPM::enabled (uint8_t instance) const
Definition at line 237 of file AP_RPM.cpp.
Referenced by loop(), and update().
get_rpm()
bool AP_RPM::get_rpm (uint8_t instance, float & rpm_value) const
Definition at line 252 of file AP_RPM.cpp.
Referenced by AP_Spektrum_Telem::calc_rpm(), AP_Frsky_Backend::calc_rpm(), AP_Frsky_SPort_Passthrough::calc_rpm(), AC_Autorotation::get_rpm(), loop(), AP_MotorsHeli_RSC::output(), AP_Hott_Telem::send_EAM(), and AP_ICEngine::update_idle_governor().
get_signal_quality()
float AP_RPM::get_signal_quality (uint8_t instance) const inline
Definition at line 94 of file AP_RPM.h.
Referenced by loop().
get_singleton()
static AP_RPM * AP_RPM::get_singleton () inline static
Definition at line 102 of file AP_RPM.h.
Referenced by AC_Autorotation::get_rpm(), AP_MotorsHeli_RSC::output(), and AP::rpm().
healthy()
bool AP_RPM::healthy (uint8_t instance) const
Definition at line 220 of file AP_RPM.cpp.
Referenced by get_rpm(), loop(), and AP_ICEngine::update_idle_governor().
init()
void AP_RPM::init (void)
Definition at line 62 of file AP_RPM.cpp.
Referenced by setup().
Log_RPM()
void AP_RPM::Log_RPM () const private
Referenced by update().
num_sensors()
uint8_t AP_RPM::num_sensors (void) const inline
Definition at line 76 of file AP_RPM.h.
Referenced by AP_Frsky_SPort_Passthrough::is_packet_ready(), loop(), AP_Frsky_SPort::send(), and setup().
update()
void AP_RPM::update (void)
Definition at line 192 of file AP_RPM.cpp.
Referenced by loop().
Friends And Related Symbol Documentation
AP_RPM_Backend
friend class AP_RPM_Backend friend
Definition at line 31 of file AP_RPM.h.
Member Data Documentation
_params
AP_RPM_Params AP_RPM::_params[RPM_MAX_INSTANCES]
Definition at line 71 of file AP_RPM.h.
Referenced by arming_checks(), convert_params(), enabled(), AP_RPM_Backend::get_pin(), healthy(), init(), update(), and AP_RPM_Pin::update().
_singleton
AP_RPM * AP_RPM::_singleton static private
Definition at line 110 of file AP_RPM.h.
Referenced by AP_RPM(), and get_singleton().
drivers
AP_RPM_Backend* AP_RPM::drivers[RPM_MAX_INSTANCES] private
Definition at line 113 of file AP_RPM.h.
Referenced by init(), and update().
num_instances
uint8_t AP_RPM::num_instances private
Definition at line 114 of file AP_RPM.h.
Referenced by enabled(), healthy(), init(), num_sensors(), and update().
state
RPM_State AP_RPM::state[RPM_MAX_INSTANCES] private
Definition at line 112 of file AP_RPM.h.
Referenced by get_rpm(), get_signal_quality(), healthy(), init(), SITL::EFI_MegaSquirt::update(), update(), and SITL::EFI_Hirth::update_engine_model().
var_info
const AP_Param::GroupInfo AP_RPM::var_info static
Initial value:
= {
    AP_SUBGROUPINFO(_params[0], "1_", 14, AP_RPM, AP_RPM_Params),
    AP_SUBGROUPINFO(_params[1], "2_", 15, AP_RPM, AP_RPM_Params),
    AP_GROUPEND
}
Definition at line 33 of file AP_RPM.h.
The documentation for this class was generated from the following files:
libraries/AP_RPM/AP_RPM.h
libraries/AP_RPM/AP_RPM.cpp