APM:Libraries: AC_PrecLand_StateMachine Class Reference
AC_PrecLand_StateMachine Class Reference
#include <AC_PrecLand_StateMachine.h>
Public Types
enum class Status : uint8_t { ERROR = 0 , DESCEND , RETRYING , FAILSAFE }
enum class FailSafeAction : uint8_t { HOLD_POS = 0 , DESCEND }
enum class RetryStrictness : uint8_t { NOT_STRICT = 0 , NORMAL , VERY_STRICT }
enum class RetryAction : uint8_t { GO_TO_LAST_LOC = 0 , GO_TO_TARGET_LOC }
Public Member Functions
AC_PrecLand_StateMachine ()
CLASS_NO_COPY (AC_PrecLand_StateMachine)
void init ()
Status update (Vector3f &retry_pos_m)
FailSafeAction get_failsafe_actions ()
Private Types
enum class TargetLostAction : uint8_t { INIT = 0 , DESCEND , LAND_VERTICALLY , RETRY_LANDING }
enum class RetryLanding : uint8_t { INIT = 0 , IN_PROGRESS , DESCEND , COMPLETE }
Private Member Functions
Status get_target_lost_actions (Vector3f &retry_pos_m)
Status retry_landing (Vector3f &retry_pos_m)
void reset_failed_landing_statemachine ()
Private Attributes
TargetLostAction landing_target_lost_action
RetryLanding _retry_state
uint8_t _retry_count
bool failsafe_initialized
uint32_t failsafe_start_ms
Detailed Description
Definition at line 15 of file AC_PrecLand_StateMachine.h.
Member Enumeration Documentation
FailSafeAction
enum class AC_PrecLand_StateMachine::FailSafeAction : uint8_t strong
Enumerator
HOLD_POS
DESCEND
Definition at line 38 of file AC_PrecLand_StateMachine.h.
RetryAction
enum class AC_PrecLand_StateMachine::RetryAction : uint8_t strong
Enumerator
GO_TO_LAST_LOC
GO_TO_TARGET_LOC
Definition at line 64 of file AC_PrecLand_StateMachine.h.
RetryLanding
enum class AC_PrecLand_StateMachine::RetryLanding : uint8_t strong private
Enumerator
INIT
IN_PROGRESS
DESCEND
COMPLETE
Definition at line 96 of file AC_PrecLand_StateMachine.h.
RetryStrictness
enum class AC_PrecLand_StateMachine::RetryStrictness : uint8_t strong
Enumerator
NOT_STRICT
NORMAL
VERY_STRICT
Definition at line 57 of file AC_PrecLand_StateMachine.h.
Status
enum class AC_PrecLand_StateMachine::Status : uint8_t strong
Enumerator
ERROR
DESCEND
RETRYING
FAILSAFE
Definition at line 30 of file AC_PrecLand_StateMachine.h.
TargetLostAction
enum class AC_PrecLand_StateMachine::TargetLostAction : uint8_t strong private
Enumerator
INIT
DESCEND
LAND_VERTICALLY
RETRY_LANDING
Definition at line 86 of file AC_PrecLand_StateMachine.h.
Constructor & Destructor Documentation
AC_PrecLand_StateMachine()
AC_PrecLand_StateMachine::AC_PrecLand_StateMachine () inline
Definition at line 19 of file AC_PrecLand_StateMachine.h.
Member Function Documentation
CLASS_NO_COPY()
AC_PrecLand_StateMachine::CLASS_NO_COPY (AC_PrecLand_StateMachine)
get_failsafe_actions()
AC_PrecLand_StateMachine::FailSafeAction AC_PrecLand_StateMachine::get_failsafe_actions ()
Definition at line 240 of file AC_PrecLand_StateMachine.cpp.
get_target_lost_actions()
AC_PrecLand_StateMachine::Status AC_PrecLand_StateMachine::get_target_lost_actions (Vector3f & retry_pos_m) private
Definition at line 94 of file AC_PrecLand_StateMachine.cpp.
Referenced by update().
init()
void AC_PrecLand_StateMachine::init ()
Definition at line 15 of file AC_PrecLand_StateMachine.cpp.
Referenced by AC_PrecLand_StateMachine().
reset_failed_landing_statemachine()
void AC_PrecLand_StateMachine::reset_failed_landing_statemachine () private
Definition at line 36 of file AC_PrecLand_StateMachine.cpp.
Referenced by init(), and update().
retry_landing()
AC_PrecLand_StateMachine::Status AC_PrecLand_StateMachine::retry_landing (Vector3f & retry_pos_m) private
Definition at line 150 of file AC_PrecLand_StateMachine.cpp.
Referenced by get_target_lost_actions().
update()
AC_PrecLand_StateMachine::Status AC_PrecLand_StateMachine::update (Vector3f & retry_pos_m)
Definition at line 49 of file AC_PrecLand_StateMachine.cpp.
Member Data Documentation
_retry_count
uint8_t AC_PrecLand_StateMachine::_retry_count private
Definition at line 103 of file AC_PrecLand_StateMachine.h.
Referenced by init(), and retry_landing().
_retry_state
RetryLanding AC_PrecLand_StateMachine::_retry_state private
Definition at line 102 of file AC_PrecLand_StateMachine.h.
Referenced by get_target_lost_actions(), reset_failed_landing_statemachine(), and retry_landing().
failsafe_initialized
bool AC_PrecLand_StateMachine::failsafe_initialized private
Definition at line 105 of file AC_PrecLand_StateMachine.h.
Referenced by get_failsafe_actions(), and reset_failed_landing_statemachine().
failsafe_start_ms
uint32_t AC_PrecLand_StateMachine::failsafe_start_ms private
Definition at line 106 of file AC_PrecLand_StateMachine.h.
Referenced by get_failsafe_actions().
landing_target_lost_action
TargetLostAction AC_PrecLand_StateMachine::landing_target_lost_action private
Definition at line 93 of file AC_PrecLand_StateMachine.h.
Referenced by get_target_lost_actions(), and reset_failed_landing_statemachine().
The documentation for this class was generated from the following files:
libraries/AC_PrecLand/AC_PrecLand_StateMachine.h
libraries/AC_PrecLand/AC_PrecLand_StateMachine.cpp