APM:Libraries: AP_RangeFinder_PWM Class Reference
AP_RangeFinder_PWM Class Reference
#include <AP_RangeFinder_PWM.h>
Public Member Functions
AP_RangeFinder_PWM (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params, float &_estimated_terrain_height)
~AP_RangeFinder_PWM (void)
void update (void) override
Public Member Functions inherited from AP_RangeFinder_Backend
AP_RangeFinder_Backend (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params)
virtual ~AP_RangeFinder_Backend (void)
virtual void init_serial (uint8_t serial_instance)
virtual void handle_msg (const mavlink_message_t &msg)
enum Rotation orientation () const
float distance () const
uint16_t distance_cm () const
int8_t signal_quality_pct () const WARN_IF_UNUSED
uint16_t voltage_mv () const
virtual int16_t max_distance_cm () const
virtual int16_t min_distance_cm () const
int16_t ground_clearance_cm () const
MAV_DISTANCE_SENSOR get_mav_distance_sensor_type () const
RangeFinder::Status status () const
RangeFinder::Type type () const
bool has_data () const
uint8_t range_valid_count () const
const Vector3f & get_pos_offset () const
uint32_t last_reading_ms () const
virtual bool get_temp (float &temp) const
RangeFinder::Type allocated_type () const
Static Public Member Functions
static bool detect ()
Protected Member Functions
bool get_reading (float &reading_m)
MAV_DISTANCE_SENSOR _get_mav_distance_sensor_type () const override
Protected Member Functions inherited from AP_RangeFinder_Backend
void update_status (RangeFinder::RangeFinder_State &state_arg) const
void update_status ()
void set_status (RangeFinder::Status status)
Private Member Functions
bool check_pin ()
void check_stop_pin ()
bool check_pins ()
bool out_of_range (void) const
Private Attributes
uint8_t last_stop_pin = -1
AP_HAL::PWMSource pwm_source
float & estimated_terrain_height
bool was_out_of_range = -1
Additional Inherited Members
Static Protected Member Functions inherited from AP_RangeFinder_Backend
static void set_status (RangeFinder::RangeFinder_State &state_arg, RangeFinder::Status status)
Protected Attributes inherited from AP_RangeFinder_Backend
RangeFinder::RangeFinder_State & state
AP_RangeFinder_Params & params
HAL_Semaphore _sem
RangeFinder::Type _backend_type
Detailed Description
Definition at line 24 of file AP_RangeFinder_PWM.h.
Constructor & Destructor Documentation
AP_RangeFinder_PWM()
AP_RangeFinder_PWM::AP_RangeFinder_PWM (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params, float & _estimated_terrain_height)
Definition at line 28 of file AP_RangeFinder_PWM.cpp.
~AP_RangeFinder_PWM()
AP_RangeFinder_PWM::~AP_RangeFinder_PWM (void) inline
Definition at line 33 of file AP_RangeFinder_PWM.h.
Member Function Documentation
_get_mav_distance_sensor_type()
MAV_DISTANCE_SENSOR AP_RangeFinder_PWM::_get_mav_distance_sensor_type () const inline override protected virtual
Implements AP_RangeFinder_Backend.
Definition at line 45 of file AP_RangeFinder_PWM.h.
check_pin()
bool AP_RangeFinder_PWM::check_pin () private
Definition at line 59 of file AP_RangeFinder_PWM.cpp.
Referenced by check_pins().
check_pins()
bool AP_RangeFinder_PWM::check_pins () private
Definition at line 78 of file AP_RangeFinder_PWM.cpp.
Referenced by update().
check_stop_pin()
void AP_RangeFinder_PWM::check_stop_pin () private
Definition at line 67 of file AP_RangeFinder_PWM.cpp.
Referenced by check_pins().
detect()
bool AP_RangeFinder_PWM::detect () static
Definition at line 41 of file AP_RangeFinder_PWM.cpp.
Referenced by RangeFinder::detect_instance().
get_reading()
bool AP_RangeFinder_PWM::get_reading (float & reading_m) protected
Definition at line 47 of file AP_RangeFinder_PWM.cpp.
Referenced by update().
out_of_range()
bool AP_RangeFinder_PWM::out_of_range (void) const private
Definition at line 132 of file AP_RangeFinder_PWM.cpp.
Referenced by update().
update()
void AP_RangeFinder_PWM::update (void) override virtual
Implements AP_RangeFinder_Backend.
Definition at line 88 of file AP_RangeFinder_PWM.cpp.
Member Data Documentation
estimated_terrain_height
float& AP_RangeFinder_PWM::estimated_terrain_height private
Definition at line 58 of file AP_RangeFinder_PWM.h.
Referenced by out_of_range().
last_stop_pin
uint8_t AP_RangeFinder_PWM::last_stop_pin = -1 private
Definition at line 54 of file AP_RangeFinder_PWM.h.
Referenced by check_stop_pin().
pwm_source
AP_HAL::PWMSource AP_RangeFinder_PWM::pwm_source private
Definition at line 56 of file AP_RangeFinder_PWM.h.
Referenced by check_pin(), and get_reading().
was_out_of_range
bool AP_RangeFinder_PWM::was_out_of_range = -1 private
Definition at line 62 of file AP_RangeFinder_PWM.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder_PWM.h
libraries/AP_RangeFinder/AP_RangeFinder_PWM.cpp