APM:Libraries: AP_DAL_GPS Class Reference
AP_DAL_GPS Class Reference
#include <AP_DAL_GPS.h>
Public Types
enum GPS_Status : uint8_t {
NO_GPS = GPS_FIX_TYPE_NO_GPS , NO_FIX = GPS_FIX_TYPE_NO_FIX , GPS_OK_FIX_2D = GPS_FIX_TYPE_2D_FIX , GPS_OK_FIX_3D = GPS_FIX_TYPE_3D_FIX ,
GPS_OK_FIX_3D_DGPS = GPS_FIX_TYPE_DGPS , GPS_OK_FIX_3D_RTK_FLOAT = GPS_FIX_TYPE_RTK_FLOAT , GPS_OK_FIX_3D_RTK_FIXED = GPS_FIX_TYPE_RTK_FIXED
}
GPS status codes.
Public Member Functions
AP_DAL_GPS ()
GPS_Status status (uint8_t sensor_id) const
GPS_Status status () const
const Location & location (uint8_t instance) const
bool have_vertical_velocity (uint8_t instance) const
bool have_vertical_velocity () const
bool horizontal_accuracy (uint8_t instance, float &hacc) const
bool horizontal_accuracy (float &hacc) const
bool vertical_accuracy (uint8_t instance, float &vacc) const
bool vertical_accuracy (float &vacc) const
uint16_t get_hdop (uint8_t instance) const
uint16_t get_hdop () const
uint32_t last_message_time_ms (uint8_t instance) const
uint8_t num_sats (uint8_t instance) const
uint8_t num_sats () const
bool get_lag (uint8_t instance, float &lag_sec) const
bool get_lag (float &lag_sec) const
const Vector3f & velocity (uint8_t instance) const
const Vector3f & velocity () const
bool speed_accuracy (uint8_t instance, float &sacc) const
bool speed_accuracy (float &sacc) const
bool gps_yaw_deg (uint8_t instance, float &yaw_deg, float &accuracy_deg, uint32_t &time_ms) const
uint8_t num_sensors (void) const
uint8_t primary_sensor (void) const
const Location & location () const
const Vector3f & get_antenna_offset (uint8_t instance) const
void start_frame ()
void handle_message (const log_RGPH &msg)
void handle_message (const log_RGPI &msg)
void handle_message (const log_RGPJ &msg)
Private Attributes
struct log_RGPH _RGPH
struct log_RGPI _RGPI [GPS_MAX_INSTANCES]
struct log_RGPJ _RGPJ [GPS_MAX_INSTANCES]
Location tmp_location [GPS_MAX_INSTANCES]
Detailed Description
Definition at line 7 of file AP_DAL_GPS.h.
Member Enumeration Documentation
GPS_Status
enum AP_DAL_GPS::GPS_Status : uint8_t
GPS status codes.
Enumerator
NO_GPS
No GPS connected/detected.
NO_FIX
Receiving valid GPS messages but no lock.
GPS_OK_FIX_2D
Receiving valid messages and 2D lock.
GPS_OK_FIX_3D
Receiving valid messages and 3D lock.
GPS_OK_FIX_3D_DGPS
Receiving valid messages and 3D lock with differential improvements.
GPS_OK_FIX_3D_RTK_FLOAT
Receiving valid messages and 3D RTK Float.
GPS_OK_FIX_3D_RTK_FIXED
Receiving valid messages and 3D RTK Fixed.
Definition at line 11 of file AP_DAL_GPS.h.
Constructor & Destructor Documentation
AP_DAL_GPS()
AP_DAL_GPS::AP_DAL_GPS ()
Definition at line 6 of file AP_DAL_GPS.cpp.
Member Function Documentation
get_antenna_offset()
const Vector3f & AP_DAL_GPS::get_antenna_offset (uint8_t instance) const inline
Definition at line 116 of file AP_DAL_GPS.h.
Referenced by NavEKF2_core::CorrectGPSForAntennaOffset(), and NavEKF3_core::CorrectGPSForAntennaOffset().
get_hdop() [1/2]
uint16_t AP_DAL_GPS::get_hdop () const inline
Definition at line 57 of file AP_DAL_GPS.h.
Referenced by get_hdop().
get_hdop() [2/2]
uint16_t AP_DAL_GPS::get_hdop (uint8_t instance) const inline
Definition at line 54 of file AP_DAL_GPS.h.
get_lag() [1/2]
bool AP_DAL_GPS::get_lag (float & lag_sec) const inline
Definition at line 76 of file AP_DAL_GPS.h.
get_lag() [2/2]
bool AP_DAL_GPS::get_lag (uint8_t instance, float & lag_sec) const inline
Definition at line 72 of file AP_DAL_GPS.h.
Referenced by get_lag(), and NavEKF3_core::setup_core().
gps_yaw_deg()
bool AP_DAL_GPS::gps_yaw_deg (uint8_t instance, float & yaw_deg, float & accuracy_deg, uint32_t & time_ms) const inline
Definition at line 95 of file AP_DAL_GPS.h.
Referenced by NavEKF3_core::readGpsYawData().
handle_message() [1/3]
void AP_DAL_GPS::handle_message (const log_RGPH & msg) inline
Definition at line 122 of file AP_DAL_GPS.h.
Referenced by AP_DAL::handle_message(), AP_DAL::handle_message(), and AP_DAL::handle_message().
handle_message() [2/3]
void AP_DAL_GPS::handle_message (const log_RGPI & msg) inline
Definition at line 125 of file AP_DAL_GPS.h.
handle_message() [3/3]
void AP_DAL_GPS::handle_message (const log_RGPJ & msg) inline
Definition at line 128 of file AP_DAL_GPS.h.
have_vertical_velocity() [1/2]
bool AP_DAL_GPS::have_vertical_velocity () const inline
Definition at line 35 of file AP_DAL_GPS.h.
Referenced by have_vertical_velocity().
have_vertical_velocity() [2/2]
bool AP_DAL_GPS::have_vertical_velocity (uint8_t instance) const inline
Definition at line 32 of file AP_DAL_GPS.h.
Referenced by NavEKF2_core::FuseVelPosNED(), and NavEKF2_core::ResetHeight().
horizontal_accuracy() [1/2]
bool AP_DAL_GPS::horizontal_accuracy (float & hacc) const inline
Definition at line 42 of file AP_DAL_GPS.h.
horizontal_accuracy() [2/2]
bool AP_DAL_GPS::horizontal_accuracy (uint8_t instance, float & hacc) const inline
Definition at line 38 of file AP_DAL_GPS.h.
Referenced by horizontal_accuracy().
last_message_time_ms()
uint32_t AP_DAL_GPS::last_message_time_ms (uint8_t instance) const inline
Definition at line 61 of file AP_DAL_GPS.h.
location() [1/2]
const Location & AP_DAL_GPS::location () const inline
Definition at line 111 of file AP_DAL_GPS.h.
Referenced by location().
location() [2/2]
const Location & AP_DAL_GPS::location (uint8_t instance) const inline
Definition at line 29 of file AP_DAL_GPS.h.
Referenced by NavEKF2_core::getPosNE(), NavEKF2_core::resetHeightDatum(), and NavEKF3_core::resetHeightDatum().
num_sats() [1/2]
uint8_t AP_DAL_GPS::num_sats () const inline
Definition at line 68 of file AP_DAL_GPS.h.
Referenced by num_sats().
num_sats() [2/2]
uint8_t AP_DAL_GPS::num_sats (uint8_t instance) const inline
Definition at line 65 of file AP_DAL_GPS.h.
num_sensors()
uint8_t AP_DAL_GPS::num_sensors (void) const inline
Definition at line 102 of file AP_DAL_GPS.h.
Referenced by AP_NavEKF_Source::pre_arm_check().
primary_sensor()
uint8_t AP_DAL_GPS::primary_sensor (void) const inline
Definition at line 106 of file AP_DAL_GPS.h.
Referenced by get_hdop(), get_lag(), NavEKF2_core::getPosNE(), have_vertical_velocity(), horizontal_accuracy(), NavEKF2_core::InitialiseFilterBootstrap(), num_sats(), speed_accuracy(), status(), velocity(), and vertical_accuracy().
speed_accuracy() [1/2]
bool AP_DAL_GPS::speed_accuracy (float & sacc) const inline
Definition at line 91 of file AP_DAL_GPS.h.
speed_accuracy() [2/2]
bool AP_DAL_GPS::speed_accuracy (uint8_t instance, float & sacc) const inline
Definition at line 87 of file AP_DAL_GPS.h.
Referenced by NavEKF2_core::calcGpsGoodForFlight(), NavEKF3_core::calcGpsGoodForFlight(), and speed_accuracy().
start_frame()
void AP_DAL_GPS::start_frame ()
Definition at line 14 of file AP_DAL_GPS.cpp.
Referenced by AP_DAL::start_frame().
status() [1/2]
GPS_Status AP_DAL_GPS::status () const inline
Definition at line 26 of file AP_DAL_GPS.h.
Referenced by status().
status() [2/2]
GPS_Status AP_DAL_GPS::status (uint8_t sensor_id) const inline
Definition at line 23 of file AP_DAL_GPS.h.
Referenced by NavEKF2_core::getPosNE(), NavEKF2_core::InitialiseFilterBootstrap(), and NavEKF3_core::InitialiseFilterBootstrap().
velocity() [1/2]
const Vector3f & AP_DAL_GPS::velocity () const inline
Definition at line 83 of file AP_DAL_GPS.h.
Referenced by velocity().
velocity() [2/2]
const Vector3f & AP_DAL_GPS::velocity (uint8_t instance) const inline
Definition at line 80 of file AP_DAL_GPS.h.
vertical_accuracy() [1/2]
bool AP_DAL_GPS::vertical_accuracy (float & vacc) const inline
Definition at line 50 of file AP_DAL_GPS.h.
vertical_accuracy() [2/2]
bool AP_DAL_GPS::vertical_accuracy (uint8_t instance, float & vacc) const inline
Definition at line 46 of file AP_DAL_GPS.h.
Referenced by NavEKF3_core::calcGpsGoodForFlight(), and vertical_accuracy().
Member Data Documentation
_RGPH
struct log_RGPH AP_DAL_GPS::_RGPH private
Definition at line 138 of file AP_DAL_GPS.h.
Referenced by handle_message(), location(), num_sensors(), primary_sensor(), and start_frame().
_RGPI
struct log_RGPI AP_DAL_GPS::_RGPI[GPS_MAX_INSTANCES] private
Definition at line 139 of file AP_DAL_GPS.h.
Referenced by AP_DAL_GPS(), get_antenna_offset(), get_lag(), gps_yaw_deg(), handle_message(), have_vertical_velocity(), horizontal_accuracy(), num_sats(), speed_accuracy(), start_frame(), status(), and vertical_accuracy().
_RGPJ
struct log_RGPJ AP_DAL_GPS::_RGPJ[GPS_MAX_INSTANCES] private
Definition at line 140 of file AP_DAL_GPS.h.
Referenced by AP_DAL_GPS(), get_hdop(), gps_yaw_deg(), handle_message(), horizontal_accuracy(), last_message_time_ms(), speed_accuracy(), start_frame(), velocity(), and vertical_accuracy().
tmp_location
Location AP_DAL_GPS::tmp_location[GPS_MAX_INSTANCES] private
Definition at line 142 of file AP_DAL_GPS.h.
Referenced by handle_message(), location(), and start_frame().
The documentation for this class was generated from the following files:
libraries/AP_DAL/AP_DAL_GPS.h
libraries/AP_DAL/AP_DAL_GPS.cpp