APM:Libraries: AC_PolyFence_loader Class Reference
AC_PolyFence_loader Class Reference
#include <AC_PolyFence_loader.h>
Classes
class ExclusionBoundary
class ExclusionCircle
class FenceIndex
class InclusionBoundary
class InclusionCircle
Public Member Functions
AC_PolyFence_loader (AP_Int8 &total, const AP_Int16 &options)
CLASS_NO_COPY (AC_PolyFence_loader)
void init ()
uint16_t num_stored_items () const
bool get_item (const uint16_t seq, AC_PolyFenceItem &item) WARN_IF_UNUSED
uint8_t get_exclusion_polygon_count () const
Vector2f * get_exclusion_polygon (uint16_t index, uint16_t &num_points) const
uint32_t get_exclusion_polygon_update_ms () const
return system time of last update to the exclusion polygon points
uint8_t get_inclusion_polygon_count () const
Vector2f * get_inclusion_polygon (uint16_t index, uint16_t &num_points) const
uint32_t get_inclusion_polygon_update_ms () const
return system time of last update to the inclusion polygon points
uint8_t get_exclusion_circle_count () const
bool get_exclusion_circle (uint8_t index, Vector2f &center_pos_cm, float &radius) const
uint32_t get_exclusion_circle_update_ms () const
return system time of last update to the exclusion circles
uint8_t get_inclusion_circle_count () const
bool get_inclusion_circle (uint8_t index, Vector2f &center_pos_cm, float &radius) const
bool check_inclusion_circle_margin (float margin) const
void handle_msg (class GCS_MAVLINK &link, const mavlink_message_t &msg)
bool breached () const WARN_IF_UNUSED
bool breached (const Location &loc) const WARN_IF_UNUSED
bool inclusion_boundary_available () const WARN_IF_UNUSED
bool loaded () const WARN_IF_UNUSED
uint16_t max_items () const
bool write_fence (const AC_PolyFenceItem *new_items, uint16_t count) WARN_IF_UNUSED
bool load_from_eeprom () WARN_IF_UNUSED
HAL_Semaphore & get_loaded_fence_semaphore (void)
void update ()
bool get_return_point (Vector2l &ret) WARN_IF_UNUSED
uint16_t total_fence_count () const
Private Member Functions
uint16_t index_fence_count (const AC_PolyFenceType type)
void void_index ()
bool check_indexed () WARN_IF_UNUSED
FenceIndex * find_first_fence (const AC_PolyFenceType type) const
bool find_index_for_seq (const uint16_t seq, const FenceIndex *&entry, uint16_t &i) const WARN_IF_UNUSED
bool find_storage_offset_for_seq (const uint16_t seq, uint16_t &offset, AC_PolyFenceType &type, uint16_t &vertex_count_offset) const WARN_IF_UNUSED
uint16_t sum_of_polygon_point_counts_and_returnpoint ()
bool validate_fence (const AC_PolyFenceItem *new_items, uint16_t count) const WARN_IF_UNUSED
bool formatted () const WARN_IF_UNUSED
bool format () WARN_IF_UNUSED
void unload ()
bool scale_latlon_from_origin (const Location &origin, const Vector2l &point, Vector2f &pos_cm) WARN_IF_UNUSED
bool read_polygon_from_storage (const Location &origin, uint16_t &read_offset, const uint8_t vertex_count, Vector2f *&next_storage_point, Vector2l *&next_storage_point_lla) WARN_IF_UNUSED
bool write_type_to_storage (uint16_t &offset, AC_PolyFenceType type) WARN_IF_UNUSED
bool write_latlon_to_storage (uint16_t &offset, const Vector2l &latlon) WARN_IF_UNUSED
bool read_latlon_from_storage (uint16_t &read_offset, Vector2l &latlon) const WARN_IF_UNUSED
bool write_eos_to_storage (uint16_t &offset)
FUNCTOR_TYPEDEF (scan_fn_t, void, const AC_PolyFenceType, uint16_t)
bool scan_eeprom (scan_fn_t scan_fn) WARN_IF_UNUSED
void scan_eeprom_count_fences (const AC_PolyFenceType type, uint16_t read_offset)
void scan_eeprom_index_fences (const AC_PolyFenceType type, uint16_t read_offset)
bool count_eeprom_fences () WARN_IF_UNUSED
bool index_eeprom () WARN_IF_UNUSED
uint16_t fence_storage_space_required (const AC_PolyFenceItem *new_items, uint16_t count)
Private Attributes
HAL_Semaphore _loaded_fence_sem
uint16_t _eos_offset
Vector2f * _loaded_return_point
Vector2l * _loaded_return_point_lla
InclusionBoundary * _loaded_inclusion_boundary
uint8_t _num_loaded_inclusion_boundaries
ExclusionBoundary * _loaded_exclusion_boundary
uint8_t _num_loaded_exclusion_boundaries
Vector2f * _loaded_offsets_from_origin
Vector2l * _loaded_points_lla
ExclusionCircle * _loaded_circle_exclusion_boundary
uint8_t _num_loaded_circle_exclusion_boundaries
InclusionCircle * _loaded_circle_inclusion_boundary
uint8_t _num_loaded_circle_inclusion_boundaries
bool _load_attempted
uint32_t _load_time_ms
AP_Int8 & _total
const AP_Int16 & _options
uint8_t _old_total
uint16_t _eeprom_fence_count
uint16_t _eeprom_item_count
FenceIndex * _index
bool _indexed
bool _index_attempted
uint16_t _num_fences
Static Private Attributes
static const uint8_t new_fence_storage_magic = 235
Detailed Description
Definition at line 42 of file AC_PolyFence_loader.h.
Constructor & Destructor Documentation
AC_PolyFence_loader()
AC_PolyFence_loader::AC_PolyFence_loader (AP_Int8 & total, const AP_Int16 & options) inline
Definition at line 47 of file AC_PolyFence_loader.h.
Member Function Documentation
breached() [1/2]
bool AC_PolyFence_loader::breached () const
Definition at line 1634 of file AC_PolyFence_loader.cpp.
breached() [2/2]
bool AC_PolyFence_loader::breached (const Location & loc) const
Definition at line 1635 of file AC_PolyFence_loader.cpp.
check_inclusion_circle_margin()
bool AC_PolyFence_loader::check_inclusion_circle_margin (float margin) const
check_indexed()
bool AC_PolyFence_loader::check_indexed () private
CLASS_NO_COPY()
AC_PolyFence_loader::CLASS_NO_COPY (AC_PolyFence_loader)
count_eeprom_fences()
bool AC_PolyFence_loader::count_eeprom_fences () private
fence_storage_space_required()
uint16_t AC_PolyFence_loader::fence_storage_space_required (const AC_PolyFenceItem * new_items, uint16_t count) private
find_first_fence()
FenceIndex * AC_PolyFence_loader::find_first_fence (const AC_PolyFenceType type) const private
find_index_for_seq()
bool AC_PolyFence_loader::find_index_for_seq (const uint16_t seq, const FenceIndex *& entry, uint16_t & i) const private
find_storage_offset_for_seq()
bool AC_PolyFence_loader::find_storage_offset_for_seq (const uint16_t seq, uint16_t & offset, AC_PolyFenceType & type, uint16_t & vertex_count_offset) const private
format()
bool AC_PolyFence_loader::format () private
formatted()
bool AC_PolyFence_loader::formatted () const private
FUNCTOR_TYPEDEF()
AC_PolyFence_loader::FUNCTOR_TYPEDEF (scan_fn_t , void , const AC_PolyFenceType , uint16_t) private
get_exclusion_circle()
bool AC_PolyFence_loader::get_exclusion_circle (uint8_t index, Vector2f & center_pos_cm, float & radius) const
returns the specified exclusion circle center is offsets in cm from EKF origin in NE frame, radius is in meters
Definition at line 1629 of file AC_PolyFence_loader.cpp.
Referenced by AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_circles().
get_exclusion_circle_count()
uint8_t AC_PolyFence_loader::get_exclusion_circle_count () const inline
exclusion circles
returns number of exclusion circles defined
Definition at line 99 of file AC_PolyFence_loader.h.
Referenced by AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_circles(), and total_fence_count().
get_exclusion_circle_update_ms()
uint32_t AC_PolyFence_loader::get_exclusion_circle_update_ms () const inline
return system time of last update to the exclusion circles
Definition at line 108 of file AC_PolyFence_loader.h.
get_exclusion_polygon()
Vector2f * AC_PolyFence_loader::get_exclusion_polygon (uint16_t index, uint16_t & num_points) const
returns pointer to array of exclusion polygon points and num_points is filled in with the number of points in the polygon points are offsets in cm from EKF origin in NE frame
Definition at line 1626 of file AC_PolyFence_loader.cpp.
Referenced by AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_polygons().
get_exclusion_polygon_count()
uint8_t AC_PolyFence_loader::get_exclusion_polygon_count () const inline
exclusion polygons
returns number of polygon exclusion zones defined
Definition at line 65 of file AC_PolyFence_loader.h.
Referenced by AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_polygons(), and total_fence_count().
get_exclusion_polygon_update_ms()
uint32_t AC_PolyFence_loader::get_exclusion_polygon_update_ms () const inline
return system time of last update to the exclusion polygon points
Definition at line 74 of file AC_PolyFence_loader.h.
get_inclusion_circle()
bool AC_PolyFence_loader::get_inclusion_circle (uint8_t index, Vector2f & center_pos_cm, float & radius) const
returns the specified inclusion circle center is offsets in cm from EKF origin in NE frame, radius is in meters
Definition at line 1630 of file AC_PolyFence_loader.cpp.
Referenced by AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_circles().
get_inclusion_circle_count()
uint8_t AC_PolyFence_loader::get_inclusion_circle_count () const inline
inclusion circles
returns number of inclusion circles defined
Definition at line 116 of file AC_PolyFence_loader.h.
Referenced by AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_circles(), and total_fence_count().
get_inclusion_polygon()
Vector2f * AC_PolyFence_loader::get_inclusion_polygon (uint16_t index, uint16_t & num_points) const
returns pointer to array of inclusion polygon points and num_points is filled in with the number of points in the polygon points are offsets in cm from EKF origin in NE frame
Definition at line 1627 of file AC_PolyFence_loader.cpp.
Referenced by AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_polygons().
get_inclusion_polygon_count()
uint8_t AC_PolyFence_loader::get_inclusion_polygon_count () const inline
inclusion polygons
returns number of polygon inclusion zones defined
Definition at line 82 of file AC_PolyFence_loader.h.
Referenced by AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_polygons(), and total_fence_count().
get_inclusion_polygon_update_ms()
uint32_t AC_PolyFence_loader::get_inclusion_polygon_update_ms () const inline
return system time of last update to the inclusion polygon points
Definition at line 91 of file AC_PolyFence_loader.h.
get_item()
bool AC_PolyFence_loader::get_item (const uint16_t seq, AC_PolyFenceItem & item)
Definition at line 1624 of file AC_PolyFence_loader.cpp.
get_loaded_fence_semaphore()
HAL_Semaphore & AC_PolyFence_loader::get_loaded_fence_semaphore (void) inline
Definition at line 168 of file AC_PolyFence_loader.h.
get_return_point()
bool AC_PolyFence_loader::get_return_point (Vector2l & ret)
handle_msg()
void AC_PolyFence_loader::handle_msg (class GCS_MAVLINK & link, const mavlink_message_t & msg)
mavlink
handler for polygon fence messages with GCS
Definition at line 1632 of file AC_PolyFence_loader.cpp.
inclusion_boundary_available()
bool AC_PolyFence_loader::inclusion_boundary_available () const inline
Definition at line 139 of file AC_PolyFence_loader.h.
index_eeprom()
bool AC_PolyFence_loader::index_eeprom () private
index_fence_count()
uint16_t AC_PolyFence_loader::index_fence_count (const AC_PolyFenceType type) private
init()
void AC_PolyFence_loader::init ()
Definition at line 1622 of file AC_PolyFence_loader.cpp.
Referenced by AC_Fence::init().
load_from_eeprom()
bool AC_PolyFence_loader::load_from_eeprom ()
loaded()
bool AC_PolyFence_loader::loaded () const inline
Definition at line 145 of file AC_PolyFence_loader.h.
max_items()
uint16_t AC_PolyFence_loader::max_items () const
Definition at line 1637 of file AC_PolyFence_loader.cpp.
num_stored_items()
uint16_t AC_PolyFence_loader::num_stored_items () const inline
Definition at line 58 of file AC_PolyFence_loader.h.
read_latlon_from_storage()
bool AC_PolyFence_loader::read_latlon_from_storage (uint16_t & read_offset, Vector2l & latlon) const private
read_polygon_from_storage()
bool AC_PolyFence_loader::read_polygon_from_storage (const Location & origin, uint16_t & read_offset, const uint8_t vertex_count, Vector2f *& next_storage_point, Vector2l *& next_storage_point_lla) private
scale_latlon_from_origin()
bool AC_PolyFence_loader::scale_latlon_from_origin (const Location & origin, const Vector2l & point, Vector2f & pos_cm) private
scan_eeprom()
bool AC_PolyFence_loader::scan_eeprom (scan_fn_t scan_fn) private
scan_eeprom_count_fences()
void AC_PolyFence_loader::scan_eeprom_count_fences (const AC_PolyFenceType type, uint16_t read_offset) private
scan_eeprom_index_fences()
void AC_PolyFence_loader::scan_eeprom_index_fences (const AC_PolyFenceType type, uint16_t read_offset) private
sum_of_polygon_point_counts_and_returnpoint()
uint16_t AC_PolyFence_loader::sum_of_polygon_point_counts_and_returnpoint () private
total_fence_count()
uint16_t AC_PolyFence_loader::total_fence_count () const inline
Definition at line 181 of file AC_PolyFence_loader.h.
unload()
void AC_PolyFence_loader::unload () private
update()
void AC_PolyFence_loader::update ()
Definition at line 1641 of file AC_PolyFence_loader.cpp.
Referenced by AC_Fence::update().
validate_fence()
bool AC_PolyFence_loader::validate_fence (const AC_PolyFenceItem * new_items, uint16_t count) const private
void_index()
void AC_PolyFence_loader::void_index () inline private
Definition at line 211 of file AC_PolyFence_loader.h.
write_eos_to_storage()
bool AC_PolyFence_loader::write_eos_to_storage (uint16_t & offset) private
write_fence()
bool AC_PolyFence_loader::write_fence (const AC_PolyFenceItem * new_items, uint16_t count)
Definition at line 1639 of file AC_PolyFence_loader.cpp.
write_latlon_to_storage()
bool AC_PolyFence_loader::write_latlon_to_storage (uint16_t & offset, const Vector2l & latlon) private
write_type_to_storage()
bool AC_PolyFence_loader::write_type_to_storage (uint16_t & offset, AC_PolyFenceType type) private
Member Data Documentation
_eeprom_fence_count
uint16_t AC_PolyFence_loader::_eeprom_fence_count private
Definition at line 399 of file AC_PolyFence_loader.h.
_eeprom_item_count
uint16_t AC_PolyFence_loader::_eeprom_item_count private
Definition at line 400 of file AC_PolyFence_loader.h.
Referenced by num_stored_items().
_eos_offset
uint16_t AC_PolyFence_loader::_eos_offset private
Definition at line 251 of file AC_PolyFence_loader.h.
_index
FenceIndex* AC_PolyFence_loader::_index private
Definition at line 413 of file AC_PolyFence_loader.h.
Referenced by void_index().
_index_attempted
bool AC_PolyFence_loader::_index_attempted private
Definition at line 415 of file AC_PolyFence_loader.h.
Referenced by void_index().
_indexed
bool AC_PolyFence_loader::_indexed private
Definition at line 414 of file AC_PolyFence_loader.h.
Referenced by void_index().
_load_attempted
bool AC_PolyFence_loader::_load_attempted private
Definition at line 330 of file AC_PolyFence_loader.h.
_load_time_ms
uint32_t AC_PolyFence_loader::_load_time_ms private
Definition at line 334 of file AC_PolyFence_loader.h.
Referenced by get_exclusion_circle_update_ms(), get_exclusion_polygon_update_ms(), get_inclusion_polygon_update_ms(), and loaded().
_loaded_circle_exclusion_boundary
ExclusionCircle* AC_PolyFence_loader::_loaded_circle_exclusion_boundary private
Definition at line 313 of file AC_PolyFence_loader.h.
_loaded_circle_inclusion_boundary
InclusionCircle* AC_PolyFence_loader::_loaded_circle_inclusion_boundary private
Definition at line 323 of file AC_PolyFence_loader.h.
_loaded_exclusion_boundary
ExclusionBoundary* AC_PolyFence_loader::_loaded_exclusion_boundary private
Definition at line 296 of file AC_PolyFence_loader.h.
_loaded_fence_sem
HAL_Semaphore AC_PolyFence_loader::_loaded_fence_sem private
Definition at line 192 of file AC_PolyFence_loader.h.
Referenced by get_loaded_fence_semaphore().
_loaded_inclusion_boundary
InclusionBoundary* AC_PolyFence_loader::_loaded_inclusion_boundary private
Definition at line 286 of file AC_PolyFence_loader.h.
_loaded_offsets_from_origin
Vector2f* AC_PolyFence_loader::_loaded_offsets_from_origin private
Definition at line 304 of file AC_PolyFence_loader.h.
_loaded_points_lla
Vector2l* AC_PolyFence_loader::_loaded_points_lla private
Definition at line 305 of file AC_PolyFence_loader.h.
_loaded_return_point
Vector2f* AC_PolyFence_loader::_loaded_return_point private
Definition at line 274 of file AC_PolyFence_loader.h.
_loaded_return_point_lla
Vector2l* AC_PolyFence_loader::_loaded_return_point_lla private
Definition at line 278 of file AC_PolyFence_loader.h.
_num_fences
uint16_t AC_PolyFence_loader::_num_fences private
Definition at line 418 of file AC_PolyFence_loader.h.
_num_loaded_circle_exclusion_boundaries
uint8_t AC_PolyFence_loader::_num_loaded_circle_exclusion_boundaries private
Definition at line 315 of file AC_PolyFence_loader.h.
Referenced by get_exclusion_circle_count().
_num_loaded_circle_inclusion_boundaries
uint8_t AC_PolyFence_loader::_num_loaded_circle_inclusion_boundaries private
Definition at line 325 of file AC_PolyFence_loader.h.
Referenced by get_inclusion_circle_count().
_num_loaded_exclusion_boundaries
uint8_t AC_PolyFence_loader::_num_loaded_exclusion_boundaries private
Definition at line 298 of file AC_PolyFence_loader.h.
Referenced by get_exclusion_polygon_count().
_num_loaded_inclusion_boundaries
uint8_t AC_PolyFence_loader::_num_loaded_inclusion_boundaries private
Definition at line 288 of file AC_PolyFence_loader.h.
Referenced by get_inclusion_polygon_count(), and inclusion_boundary_available().
_old_total
uint8_t AC_PolyFence_loader::_old_total private
Definition at line 386 of file AC_PolyFence_loader.h.
_options
const AP_Int16& AC_PolyFence_loader::_options private
Definition at line 385 of file AC_PolyFence_loader.h.
_total
AP_Int8& AC_PolyFence_loader::_total private
Definition at line 384 of file AC_PolyFence_loader.h.
new_fence_storage_magic
const uint8_t AC_PolyFence_loader::new_fence_storage_magic = 235 static private
Definition at line 243 of file AC_PolyFence_loader.h.
The documentation for this class was generated from the following files:
libraries/AC_Fence/AC_PolyFence_loader.h
libraries/AC_Fence/AC_PolyFence_loader.cpp