APM:Libraries: AP_Stats Class Reference
AP_Stats Class Reference
#include <AP_Stats.h>
Public Member Functions
AP_Stats ()
void init ()
void flush ()
void update ()
void set_flying (bool b)
bool get_is_flying (void) const
uint32_t get_flight_time_s (void)
Static Public Member Functions
static AP_Stats * get_singleton (void)
Public Attributes
uint32_t flttime
uint32_t runtime
uint32_t reset
uint32_t flttime_boot
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void copy_variables_from_parameters ()
void update_flighttime ()
void update_runtime ()
Private Attributes
struct {
AP_Int16 bootcount
AP_Int32 flttime
AP_Int32 runtime
AP_Int32 reset
} params
uint64_t last_flush_ms
const uint16_t flush_interval_ms = 30000
uint64_t _flying_ms
uint64_t _last_runtime_ms
HAL_Semaphore sem
Static Private Attributes
static AP_Stats * _singleton
Detailed Description
Definition at line 9 of file AP_Stats.h.
Constructor & Destructor Documentation
AP_Stats()
AP_Stats::AP_Stats (void)
Definition at line 48 of file AP_Stats.cpp.
Member Function Documentation
copy_variables_from_parameters()
void AP_Stats::copy_variables_from_parameters () private
Definition at line 54 of file AP_Stats.cpp.
Referenced by init(), and update().
flush()
void AP_Stats::flush ()
Definition at line 71 of file AP_Stats.cpp.
Referenced by update().
get_flight_time_s()
uint32_t AP_Stats::get_flight_time_s (void)
Definition at line 147 of file AP_Stats.cpp.
Referenced by AP_OSD_Screen::draw_flightime(), AP_Hott_Telem::send_EAM(), and AP_MSP_Telem_DJI::update_flight_mode_str().
get_is_flying()
bool AP_Stats::get_is_flying (void) const inline
Definition at line 35 of file AP_Stats.h.
get_singleton()
static AP_Stats * AP_Stats::get_singleton (void) inline static
Definition at line 44 of file AP_Stats.h.
Referenced by AP::stats().
init()
void AP_Stats::init ()
Definition at line 62 of file AP_Stats.cpp.
Referenced by AP_Vehicle::setup().
set_flying()
void AP_Stats::set_flying (bool b)
Definition at line 132 of file AP_Stats.cpp.
update()
void AP_Stats::update ()
Definition at line 96 of file AP_Stats.cpp.
update_flighttime()
void AP_Stats::update_flighttime () private
Definition at line 77 of file AP_Stats.cpp.
Referenced by get_flight_time_s(), set_flying(), and update().
update_runtime()
void AP_Stats::update_runtime () private
Definition at line 88 of file AP_Stats.cpp.
Referenced by update().
Member Data Documentation
_flying_ms
uint64_t AP_Stats::_flying_ms private
Definition at line 65 of file AP_Stats.h.
Referenced by get_is_flying(), set_flying(), and update_flighttime().
_last_runtime_ms
uint64_t AP_Stats::_last_runtime_ms private
Definition at line 66 of file AP_Stats.h.
Referenced by update_runtime().
_singleton
AP_Stats * AP_Stats::_singleton static private
Definition at line 51 of file AP_Stats.h.
Referenced by AP_Stats(), and get_singleton().
bootcount
AP_Int16 AP_Stats::bootcount
Definition at line 54 of file AP_Stats.h.
flttime [1/2]
uint32_t AP_Stats::flttime
Definition at line 18 of file AP_Stats.h.
Referenced by copy_variables_from_parameters(), flush(), get_flight_time_s(), and update_flighttime().
flttime [2/2]
AP_Int32 AP_Stats::flttime
Definition at line 55 of file AP_Stats.h.
flttime_boot
uint32_t AP_Stats::flttime_boot
Definition at line 21 of file AP_Stats.h.
Referenced by copy_variables_from_parameters(), and get_flight_time_s().
flush_interval_ms
const uint16_t AP_Stats::flush_interval_ms = 30000 private
Definition at line 63 of file AP_Stats.h.
Referenced by update().
last_flush_ms
uint64_t AP_Stats::last_flush_ms private
Definition at line 62 of file AP_Stats.h.
Referenced by update().
[struct]
struct { ... } AP_Stats::params
Referenced by copy_variables_from_parameters(), flush(), init(), and update().
reset [1/2]
uint32_t AP_Stats::reset
Definition at line 20 of file AP_Stats.h.
Referenced by copy_variables_from_parameters().
reset [2/2]
AP_Int32 AP_Stats::reset
Definition at line 57 of file AP_Stats.h.
runtime [1/2]
uint32_t AP_Stats::runtime
Definition at line 19 of file AP_Stats.h.
Referenced by copy_variables_from_parameters(), flush(), and update_runtime().
runtime [2/2]
AP_Int32 AP_Stats::runtime
Definition at line 56 of file AP_Stats.h.
sem
HAL_Semaphore AP_Stats::sem private
Definition at line 70 of file AP_Stats.h.
Referenced by update(), and update_flighttime().
var_info
const AP_Param::GroupInfo AP_Stats::var_info static
Definition at line 9 of file AP_Stats.h.
The documentation for this class was generated from the following files:
libraries/AP_Stats/AP_Stats.h
libraries/AP_Stats/AP_Stats.cpp