APM:Libraries: SRV_Channels Class Reference
SRV_Channels Class Reference
#include <SRV_Channel.h>
Classes
struct slew_list
struct srv_function
Public Member Functions
SRV_Channels (void)
void set_esc_scaling_for (SRV_Channel::Aux_servo_function_t function)
bool auto_trim_enabled (void) const
void adjust_trim (SRV_Channel::Aux_servo_function_t function, float v)
void save_trim (void)
void disable_passthrough (bool disable)
Static Public Member Functions
static void set_default_function (uint8_t chan, SRV_Channel::Aux_servo_function_t function)
static void set_output_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t value)
static void set_output_pwm_chan (uint8_t chan, uint16_t value)
static void set_output_pwm_chan_timeout (uint8_t chan, uint16_t value, uint16_t timeout_ms)
static void set_output_scaled (SRV_Channel::Aux_servo_function_t function, float value)
static float get_output_scaled (SRV_Channel::Aux_servo_function_t function)
static float get_slew_limited_output_scaled (SRV_Channel::Aux_servo_function_t function)
static bool get_output_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t &value)
static float get_output_norm (SRV_Channel::Aux_servo_function_t function)
static void set_output_norm (SRV_Channel::Aux_servo_function_t function, float value)
static uint32_t get_output_channel_mask (SRV_Channel::Aux_servo_function_t function)
static void set_slew_rate (SRV_Channel::Aux_servo_function_t function, float slew_rate, uint16_t range, float dt)
static void output_ch_all (void)
static void set_output_min_max (SRV_Channel::Aux_servo_function_t function, uint16_t min_pwm, uint16_t max_pwm)
static void setup_failsafe_trim_all_non_motors (void)
static void set_output_pwm_trimmed (SRV_Channel::Aux_servo_function_t function, int16_t value)
static void set_trim_to_servo_out_for (SRV_Channel::Aux_servo_function_t function)
static void set_trim_to_min_for (SRV_Channel::Aux_servo_function_t function, bool ignore_reversed=false)
static void set_trim_to_pwm_for (SRV_Channel::Aux_servo_function_t function, int16_t pwm)
static void set_output_to_min (SRV_Channel::Aux_servo_function_t function)
static void set_output_to_max (SRV_Channel::Aux_servo_function_t function)
static void set_output_to_trim (SRV_Channel::Aux_servo_function_t function)
static void copy_radio_in_out (SRV_Channel::Aux_servo_function_t function, bool do_input_output=false)
static void copy_radio_in_out_mask (uint32_t mask)
static void set_failsafe_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t pwm)
static void set_failsafe_limit (SRV_Channel::Aux_servo_function_t function, SRV_Channel::Limit limit)
static void set_output_limit (SRV_Channel::Aux_servo_function_t function, SRV_Channel::Limit limit)
static bool function_assigned (SRV_Channel::Aux_servo_function_t function)
static void move_servo (SRV_Channel::Aux_servo_function_t function, int16_t value, int16_t angle_min, int16_t angle_max)
static void enable_aux_servos (void)
static void enable_by_mask (uint32_t mask)
enable output channels using a channel mask
static SRV_Channel::Aux_servo_function_t channel_function (uint8_t channel)
static void update_aux_servo_function (void)
setup the output range types of all functions
static bool set_aux_channel_default (SRV_Channel::Aux_servo_function_t function, uint8_t channel)
static bool find_channel (SRV_Channel::Aux_servo_function_t function, uint8_t &chan)
static SRV_Channel * get_channel_for (SRV_Channel::Aux_servo_function_t function)
static void set_angle (SRV_Channel::Aux_servo_function_t function, uint16_t angle)
static void set_range (SRV_Channel::Aux_servo_function_t function, uint16_t range)
static void set_rc_frequency (SRV_Channel::Aux_servo_function_t function, uint16_t frequency)
static void constrain_pwm (SRV_Channel::Aux_servo_function_t function)
static void calc_pwm (void)
static AP_HAL::RCOutput::DshotEscType get_dshot_esc_type ()
static uint8_t get_dshot_rate ()
static uint32_t get_rc_fs_mask ()
static SRV_Channel * srv_channel (uint8_t i)
static void upgrade_parameters (void)
static SRV_Channel::Aux_servo_function_t get_motor_function (uint8_t channel)
static void cork ()
static void push ()
static void set_disabled_channel_mask (uint32_t mask)
static uint32_t get_disabled_channel_mask ()
static void set_digital_outputs (uint32_t dig_mask, uint32_t rev_mask)
static bool have_digital_outputs (uint32_t mask)
static bool have_digital_outputs ()
static void set_emergency_stop (bool state)
static bool get_emergency_stop ()
static SRV_Channels * get_singleton (void)
static void zero_rc_outputs ()
static void init (uint32_t motor_mask=0, AP_HAL::RCOutput::output_mode mode=AP_HAL::RCOutput::MODE_PWM_NONE)
static bool is_GPIO (uint8_t channel)
static bool is_alarm (uint8_t channel)
static bool is_alarm_inverted (uint8_t channel)
static bool have_32_channels ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Static Private Member Functions
static bool passthrough_disabled (void)
Private Attributes
SRV_Channel::servo_mask_t trimmed_mask
SRV_Channel obj_channels [NUM_SERVO_CHANNELS]
AP_Int8 auto_trim
AP_Int16 default_rate
AP_Int8 dshot_rate
AP_Int8 dshot_esc_type
AP_Int32 gpio_mask
AP_Int32 rc_fs_mask
HAL_Semaphore override_counter_sem
Static Private Attributes
static bool disabled_passthrough
static Bitmask< SRV_Channel::k_nr_aux_servo_functions > function_mask
static bool initialised
static SRV_Channel * channels
static SRV_Channels * _singleton
static uint32_t disabled_mask
static uint32_t digital_mask
static uint32_t reversible_mask
static uint32_t invalid_mask
static uint16_t override_counter [NUM_SERVO_CHANNELS]
static struct SRV_Channels::srv_function functions [SRV_Channel::k_nr_aux_servo_functions]
static bool emergency_stop
static slew_list * _slew
Friends
class SRV_Channel
Detailed Description
Definition at line 357 of file SRV_Channel.h.
Constructor & Destructor Documentation
SRV_Channels()
SRV_Channels::SRV_Channels (void)
Definition at line 364 of file SRV_Channels.cpp.
Member Function Documentation
adjust_trim()
void SRV_Channels::adjust_trim (SRV_Channel::Aux_servo_function_t function, float v)
Definition at line 688 of file SRV_Channel_aux.cpp.
auto_trim_enabled()
bool SRV_Channels::auto_trim_enabled (void) const inline
Definition at line 411 of file SRV_Channel.h.
calc_pwm()
void SRV_Channels::calc_pwm (void) static
Definition at line 441 of file SRV_Channels.cpp.
Referenced by AP_MotorsUGV::output(), AP_MotorsUGV::output_test_pct(), AP_MotorsUGV::output_test_pwm(), and stability_test().
channel_function()
SRV_Channel::Aux_servo_function_t SRV_Channels::channel_function (uint8_t channel) static
Definition at line 123 of file SRV_Channel_aux.cpp.
Referenced by is_alarm(), is_alarm_inverted(), and is_GPIO().
constrain_pwm()
void SRV_Channels::constrain_pwm (SRV_Channel::Aux_servo_function_t function) static
Definition at line 839 of file SRV_Channel_aux.cpp.
copy_radio_in_out()
static void SRV_Channels::copy_radio_in_out (SRV_Channel::Aux_servo_function_t function, bool do_input_output = false) static
copy_radio_in_out_mask()
static void SRV_Channels::copy_radio_in_out_mask (uint32_t mask) static
cork()
void SRV_Channels::cork () static
Definition at line 506 of file SRV_Channels.cpp.
Referenced by AP_MotorsUGV::output(), AP_MotorsUGV::output_test_pct(), AP_MotorsUGV::output_test_pwm(), and zero_rc_outputs().
disable_passthrough()
void SRV_Channels::disable_passthrough (bool disable) inline
Definition at line 499 of file SRV_Channel.h.
enable_aux_servos()
void SRV_Channels::enable_aux_servos (void) static
Should be called after the servo functions have been initialized called at 1Hz
Definition at line 236 of file SRV_Channel_aux.cpp.
Referenced by stability_test().
enable_by_mask()
void SRV_Channels::enable_by_mask (uint32_t mask) static
enable output channels using a channel mask
Definition at line 326 of file SRV_Channel_aux.cpp.
find_channel()
bool SRV_Channels::find_channel (SRV_Channel::Aux_servo_function_t function, uint8_t & chan) static
Definition at line 566 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsUGV::add_omni_motor_num(), AP_MotorsMulticopter::arming_checks(), get_channel_for(), AP_MotorsTailsitter::get_motor_mask(), get_output_norm(), get_output_pwm(), Compass_PerMotor::scaled_output(), and set_esc_scaling_for().
function_assigned()
bool SRV_Channels::function_assigned (SRV_Channel::Aux_servo_function_t function) static
Definition at line 503 of file SRV_Channel_aux.cpp.
Referenced by AP_Parachute::arming_checks(), AP_Camera::convert_params(), find_channel(), AP_Mount_Servo::has_pan_control(), AP_MotorsUGV::has_sail(), AP_MotorsUGV::have_skid_steering(), AP_MotorsTailsitter::init(), AP_MotorsTri::init(), move_servo(), AP_MotorsUGV::output_test_pct(), AP_MotorsUGV::output_test_pwm(), AP_MotorsUGV::pre_arm_check(), set_aux_channel_default(), set_failsafe_limit(), set_failsafe_pwm(), AP_MotorsTri::set_frame_class_and_type(), set_output_limit(), set_output_norm(), set_output_pwm(), set_output_pwm_trimmed(), set_trim_to_servo_out_for(), and AC_Sprayer::update().
get_channel_for()
SRV_Channel * SRV_Channels::get_channel_for (SRV_Channel::Aux_servo_function_t function) static
Definition at line 583 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsHeli_Single::heli_motors_param_conversions(), and AP_MotorsUGV::output_throttle().
get_disabled_channel_mask()
static uint32_t SRV_Channels::get_disabled_channel_mask () inline static
Definition at line 541 of file SRV_Channel.h.
Referenced by AP_Arming::servo_checks().
get_dshot_esc_type()
static AP_HAL::RCOutput::DshotEscType SRV_Channels::get_dshot_esc_type () inline static
Definition at line 510 of file SRV_Channel.h.
Referenced by AP_Motors::rc_set_freq(), and AP_MotorsUGV::setup_pwm_type().
get_dshot_rate()
static uint8_t SRV_Channels::get_dshot_rate () inline static
Definition at line 512 of file SRV_Channel.h.
get_emergency_stop()
static bool SRV_Channels::get_emergency_stop () inline static
Definition at line 556 of file SRV_Channel.h.
Referenced by AP_Arming::estop_checks().
get_motor_function()
static SRV_Channel::Aux_servo_function_t SRV_Channels::get_motor_function (uint8_t channel) inline static
Definition at line 528 of file SRV_Channel.h.
Referenced by AP_Motors::add_motor_num(), AP_MotorsUGV::add_omni_motor_num(), AP_MotorsHeli_Swash::add_servo_raw(), AP_MotorsMulticopter::arming_checks(), AP_MotorsCoax::init(), AP_MotorsSingle::init(), AP_MotorsTri::init(), AP_MotorsHeli_Quad::init_outputs(), AP_MotorsHeli_Single::init_outputs(), AP_Motors::motor_mask_to_srv_channel_mask(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsUGV::output_omni(), AP_MotorsUGV::pre_arm_check(), AP_Motors::rc_set_freq(), AP_MotorsHeli_Swash::rc_write(), AP_Motors::rc_write(), AP_Motors::rc_write_angle(), AP_MotorsUGV::setup_pwm_type(), and AP_MotorsUGV::setup_servo_output().
get_output_channel_mask()
uint32_t SRV_Channels::get_output_channel_mask (SRV_Channel::Aux_servo_function_t function) static
Definition at line 630 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsMulticopter::get_motor_mask(), AP_MotorsHeli_RSC::get_output_mask(), AP_Motors::motor_mask_to_srv_channel_mask(), and AP_MotorsUGV::setup_pwm_type().
get_output_norm()
float SRV_Channels::get_output_norm (SRV_Channel::Aux_servo_function_t function) static
Definition at line 746 of file SRV_Channel_aux.cpp.
get_output_pwm()
bool SRV_Channels::get_output_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t & value) static
Definition at line 718 of file SRV_Channel_aux.cpp.
Referenced by set_trim_to_servo_out_for().
get_output_scaled()
float SRV_Channels::get_output_scaled (SRV_Channel::Aux_servo_function_t function) static
Definition at line 600 of file SRV_Channel_aux.cpp.
Referenced by AP_BattMonitor_Synthetic_Current::read(), AP_ICEngine::update_idle_governor(), and AP_Airspeed::use().
get_rc_fs_mask()
static uint32_t SRV_Channels::get_rc_fs_mask () inline static
Definition at line 514 of file SRV_Channel.h.
Referenced by SRV_Channel::output_ch().
get_singleton()
static SRV_Channels * SRV_Channels::get_singleton (void) inline static
Definition at line 559 of file SRV_Channel.h.
get_slew_limited_output_scaled()
float SRV_Channels::get_slew_limited_output_scaled (SRV_Channel::Aux_servo_function_t function) static
Definition at line 609 of file SRV_Channel_aux.cpp.
have_32_channels()
static bool SRV_Channels::have_32_channels () inline static
Definition at line 582 of file SRV_Channel.h.
Referenced by SITL::JSON::output_servos().
have_digital_outputs() [1/2]
static bool SRV_Channels::have_digital_outputs () inline static
Definition at line 550 of file SRV_Channel.h.
Referenced by AP_MotorsMulticopter::update_throttle_range().
have_digital_outputs() [2/2]
static bool SRV_Channels::have_digital_outputs (uint32_t mask) inline static
Definition at line 547 of file SRV_Channel.h.
init()
void SRV_Channels::init (uint32_t motor_mask = 0, AP_HAL::RCOutput::output_mode mode = AP_HAL::RCOutput::MODE_PWM_NONE) static
Definition at line 405 of file SRV_Channels.cpp.
Referenced by AP_Vehicle::setup().
is_alarm()
static bool SRV_Channels::is_alarm (uint8_t channel) inline static
Definition at line 572 of file SRV_Channel.h.
Referenced by HALSITL::RCOutput::init().
is_alarm_inverted()
static bool SRV_Channels::is_alarm_inverted (uint8_t channel) inline static
Definition at line 577 of file SRV_Channel.h.
Referenced by HALSITL::RCOutput::init().
is_GPIO()
bool SRV_Channels::is_GPIO (uint8_t channel) static
Definition at line 596 of file SRV_Channels.cpp.
Referenced by ChibiOS::GPIO::init(), and HALSITL::RCOutput::init().
move_servo()
void SRV_Channels::move_servo (SRV_Channel::Aux_servo_function_t function, int16_t value, int16_t angle_min, int16_t angle_max) static
Definition at line 516 of file SRV_Channel_aux.cpp.
Referenced by AP_Mount_Servo::move_servo(), and AC_Sprayer::update().
output_ch_all()
void SRV_Channels::output_ch_all (void) static
Definition at line 107 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsUGV::output(), AP_MotorsUGV::output_test_pct(), AP_MotorsUGV::output_test_pwm(), and stability_test().
passthrough_disabled()
static bool SRV_Channels::passthrough_disabled (void) inline static private
Definition at line 669 of file SRV_Channel.h.
Referenced by SRV_Channel::output_ch().
push()
void SRV_Channels::push () static
Definition at line 514 of file SRV_Channels.cpp.
Referenced by AP_MotorsUGV::output(), AP_MotorsUGV::output_test_pct(), AP_MotorsUGV::output_test_pwm(), and zero_rc_outputs().
save_trim()
void SRV_Channels::save_trim (void)
Definition at line 419 of file SRV_Channels.cpp.
set_angle()
void SRV_Channels::set_angle (SRV_Channel::Aux_servo_function_t function, uint16_t angle) static
Definition at line 808 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsCoax::init(), AP_MotorsSingle::init(), AP_MotorsTailsitter::init(), AP_MotorsTri::init(), AP_MotorsHeli_Quad::init_outputs(), AP_MotorsHeli_Single::init_outputs(), AP_MotorsTri::output_armed_stabilizing(), and AP_MotorsUGV::setup_servo_output().
set_aux_channel_default()
bool SRV_Channels::set_aux_channel_default (SRV_Channel::Aux_servo_function_t function, uint8_t channel) static
Definition at line 540 of file SRV_Channel_aux.cpp.
Referenced by AP_Motors::add_motor_num(), AP_MotorsUGV::add_omni_motor_num(), AP_MotorsHeli_Swash::add_servo_raw(), AP_MotorsTailsitter::init(), and AP_MotorsHeli_RSC::init_servo().
set_default_function()
void SRV_Channels::set_default_function (uint8_t chan, SRV_Channel::Aux_servo_function_t function) static
Definition at line 665 of file SRV_Channel_aux.cpp.
set_digital_outputs()
void SRV_Channels::set_digital_outputs (uint32_t dig_mask, uint32_t rev_mask) static
Definition at line 286 of file SRV_Channel_aux.cpp.
set_disabled_channel_mask()
static void SRV_Channels::set_disabled_channel_mask (uint32_t mask) inline static
Definition at line 540 of file SRV_Channel.h.
set_emergency_stop()
void SRV_Channels::set_emergency_stop (bool state) static
Definition at line 609 of file SRV_Channels.cpp.
Referenced by RC_Channel::do_aux_function().
set_esc_scaling_for()
void SRV_Channels::set_esc_scaling_for (SRV_Channel::Aux_servo_function_t function)
Definition at line 676 of file SRV_Channel_aux.cpp.
set_failsafe_limit()
void SRV_Channels::set_failsafe_limit (SRV_Channel::Aux_servo_function_t function, SRV_Channel::Limit limit) static
Definition at line 457 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsUGV::setup_safety_output().
set_failsafe_pwm()
void SRV_Channels::set_failsafe_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t pwm) static
Definition at line 440 of file SRV_Channel_aux.cpp.
set_output_limit()
void SRV_Channels::set_output_limit (SRV_Channel::Aux_servo_function_t function, SRV_Channel::Limit limit) static
Definition at line 475 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsUGV::output_omni(), AP_MotorsUGV::output_regular(), AP_MotorsUGV::output_skid_steering(), AC_Sprayer::stop_spraying(), AP_MotorsHeli_Dual::update_motor_control(), AP_MotorsHeli_Quad::update_motor_control(), and AP_MotorsHeli_Single::update_motor_control().
set_output_min_max()
void SRV_Channels::set_output_min_max (SRV_Channel::Aux_servo_function_t function, uint16_t min_pwm, uint16_t max_pwm) static
Definition at line 828 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsHeli_Swash::add_servo_raw(), and AP_MotorsHeli_Single::init_outputs().
set_output_norm()
void SRV_Channels::set_output_norm (SRV_Channel::Aux_servo_function_t function, float value) static
Definition at line 759 of file SRV_Channel_aux.cpp.
set_output_pwm()
void SRV_Channels::set_output_pwm (SRV_Channel::Aux_servo_function_t function, uint16_t value) static
Definition at line 338 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsTailsitter::_output_test_seq(), AP_Camera_Servo::configure(), AP_Gripper_EPM::grab(), AP_Gripper_EPM::neutral(), AP_MotorsUGV::output_test_pwm(), AP_MotorsTailsitter::output_to_motors(), AP_Motors::rc_write(), AP_Gripper_EPM::release(), AP_ICEngine::set_ignition(), AP_ICEngine::set_starter(), AP_MotorsMulticopter::set_throttle_passthrough_for_esc_calibration(), AP_Camera_Servo::trigger_pic(), AC_Sprayer::update(), AP_Parachute::update(), and AP_Camera_Servo::update().
set_output_pwm_chan()
void SRV_Channels::set_output_pwm_chan (uint8_t chan, uint16_t value) static
Definition at line 470 of file SRV_Channels.cpp.
Referenced by RCOutputRGBLed::hw_set_rgb().
set_output_pwm_chan_timeout()
void SRV_Channels::set_output_pwm_chan_timeout (uint8_t chan, uint16_t value, uint16_t timeout_ms) static
Definition at line 480 of file SRV_Channels.cpp.
set_output_pwm_trimmed()
void SRV_Channels::set_output_pwm_trimmed (SRV_Channel::Aux_servo_function_t function, int16_t value) static
Definition at line 357 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsHeli_Swash::rc_write().
set_output_scaled()
void SRV_Channels::set_output_scaled (SRV_Channel::Aux_servo_function_t function, float value) static
Definition at line 592 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsMulticopter::output_boost_throttle(), AP_MotorsUGV::output_regular(), AP_MotorsMulticopter::output_rpyt(), AP_MotorsUGV::output_sail(), AP_MotorsUGV::output_test_pct(), AP_MotorsUGV::output_throttle(), AP_MotorsHeli_Single::output_to_ddfp_tail(), AP_MotorsTailsitter::output_to_motors(), AP_Motors::rc_write(), AP_Motors::rc_write_angle(), and AP_MotorsHeli_RSC::write_rsc().
set_output_to_max()
static void SRV_Channels::set_output_to_max (SRV_Channel::Aux_servo_function_t function) static
set_output_to_min()
static void SRV_Channels::set_output_to_min (SRV_Channel::Aux_servo_function_t function) static
set_output_to_trim()
void SRV_Channels::set_output_to_trim (SRV_Channel::Aux_servo_function_t function) static
Definition at line 733 of file SRV_Channel_aux.cpp.
set_range()
void SRV_Channels::set_range (SRV_Channel::Aux_servo_function_t function, uint16_t range) static
Definition at line 818 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsHeli_Swash::add_servo_raw(), AP_MotorsHeli_Single::init_outputs(), AP_Motors::rc_set_freq(), and AP_MotorsUGV::setup_servo_output().
set_rc_frequency()
void SRV_Channels::set_rc_frequency (SRV_Channel::Aux_servo_function_t function, uint16_t frequency) static
Definition at line 865 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsTailsitter::set_update_rate().
set_slew_rate()
void SRV_Channels::set_slew_rate (SRV_Channel::Aux_servo_function_t function, float slew_rate, uint16_t range, float dt) static
Definition at line 776 of file SRV_Channel_aux.cpp.
set_trim_to_min_for()
void SRV_Channels::set_trim_to_min_for (SRV_Channel::Aux_servo_function_t function, bool ignore_reversed = false) static
Definition at line 653 of file SRV_Channel_aux.cpp.
Referenced by AP_MotorsUGV::setup_safety_output().
set_trim_to_pwm_for()
void SRV_Channels::set_trim_to_pwm_for (SRV_Channel::Aux_servo_function_t function, int16_t pwm) static
Definition at line 643 of file SRV_Channel_aux.cpp.
set_trim_to_servo_out_for()
void SRV_Channels::set_trim_to_servo_out_for (SRV_Channel::Aux_servo_function_t function) static
Definition at line 381 of file SRV_Channel_aux.cpp.
setup_failsafe_trim_all_non_motors()
void SRV_Channels::setup_failsafe_trim_all_non_motors (void) static
Definition at line 429 of file SRV_Channels.cpp.
srv_channel()
static SRV_Channel * SRV_Channels::srv_channel (uint8_t i) inline static
Definition at line 516 of file SRV_Channel.h.
Referenced by AP_ServoRelayEvents::do_repeat_servo(), AP_ServoRelayEvents::do_set_servo(), AP_Arming::servo_checks(), AP_SBusOut::update(), and AP_ServoRelayEvents::update_events().
update_aux_servo_function()
void SRV_Channels::update_aux_servo_function (void) static
setup the output range types of all functions
Definition at line 208 of file SRV_Channel_aux.cpp.
Referenced by enable_aux_servos(), function_assigned(), and get_output_channel_mask().
upgrade_parameters()
void SRV_Channels::upgrade_parameters (void) static
Definition at line 854 of file SRV_Channel_aux.cpp.
zero_rc_outputs()
void SRV_Channels::zero_rc_outputs () static
Definition at line 579 of file SRV_Channels.cpp.
Referenced by AP_Vehicle::reboot().
Friends And Related Symbol Documentation
SRV_Channel
friend class SRV_Channel friend
Definition at line 359 of file SRV_Channel.h.
Member Data Documentation
_singleton
SRV_Channels * SRV_Channels::_singleton static private
Definition at line 601 of file SRV_Channel.h.
Referenced by calc_pwm(), enable_aux_servos(), get_dshot_esc_type(), get_dshot_rate(), get_rc_fs_mask(), get_singleton(), have_32_channels(), init(), is_GPIO(), output_ch_all(), set_output_pwm_chan_timeout(), and SRV_Channels().
_slew
SRV_Channels::slew_list * SRV_Channels::_slew static private
Definition at line 683 of file SRV_Channel.h.
Referenced by calc_pwm(), get_slew_limited_output_scaled(), and set_slew_rate().
auto_trim
AP_Int8 SRV_Channels::auto_trim private
Definition at line 658 of file SRV_Channel.h.
Referenced by auto_trim_enabled().
channels
SRV_Channel * SRV_Channels::channels static private
Definition at line 600 of file SRV_Channel.h.
Referenced by adjust_trim(), calc_pwm(), channel_function(), constrain_pwm(), enable_aux_servos(), find_channel(), get_channel_for(), get_output_norm(), get_output_pwm(), move_servo(), output_ch_all(), save_trim(), set_angle(), set_aux_channel_default(), set_default_function(), set_digital_outputs(), set_esc_scaling_for(), set_failsafe_limit(), set_failsafe_pwm(), set_output_limit(), set_output_min_max(), set_output_norm(), set_output_pwm(), set_output_pwm_chan(), set_output_pwm_chan_timeout(), set_output_pwm_trimmed(), set_output_to_trim(), set_range(), set_rc_frequency(), set_trim_to_min_for(), set_trim_to_pwm_for(), set_trim_to_servo_out_for(), setup_failsafe_trim_all_non_motors(), srv_channel(), SRV_Channels(), update_aux_servo_function(), and upgrade_parameters().
default_rate
AP_Int16 SRV_Channels::default_rate private
Definition at line 659 of file SRV_Channel.h.
Referenced by enable_aux_servos().
digital_mask
uint32_t SRV_Channels::digital_mask static private
Definition at line 637 of file SRV_Channel.h.
Referenced by have_digital_outputs(), have_digital_outputs(), and set_digital_outputs().
disabled_mask
uint32_t SRV_Channels::disabled_mask static private
Definition at line 633 of file SRV_Channel.h.
Referenced by enable_aux_servos(), get_disabled_channel_mask(), SRV_Channel::output_ch(), set_digital_outputs(), and set_disabled_channel_mask().
disabled_passthrough
bool SRV_Channels::disabled_passthrough static private
Definition at line 592 of file SRV_Channel.h.
Referenced by disable_passthrough(), and passthrough_disabled().
dshot_esc_type
AP_Int8 SRV_Channels::dshot_esc_type private
Definition at line 661 of file SRV_Channel.h.
Referenced by get_dshot_esc_type().
dshot_rate
AP_Int8 SRV_Channels::dshot_rate private
Definition at line 660 of file SRV_Channel.h.
Referenced by get_dshot_rate(), and init().
emergency_stop
bool SRV_Channels::emergency_stop static private
Definition at line 673 of file SRV_Channel.h.
Referenced by SRV_Channel::calc_pwm(), get_emergency_stop(), and set_emergency_stop().
function_mask
Bitmask< SRV_Channel::k_nr_aux_servo_functions > SRV_Channels::function_mask static private
Definition at line 596 of file SRV_Channel.h.
Referenced by function_assigned(), set_aux_channel_default(), set_default_function(), and update_aux_servo_function().
functions
SRV_Channels::srv_function SRV_Channels::functions static private
Definition at line 75 of file SRV_Channels.cpp.
Referenced by calc_pwm(), get_output_channel_mask(), get_output_norm(), get_output_pwm(), get_output_scaled(), get_slew_limited_output_scaled(), set_aux_channel_default(), set_output_scaled(), set_slew_rate(), and update_aux_servo_function().
gpio_mask
AP_Int32 SRV_Channels::gpio_mask private
Definition at line 662 of file SRV_Channel.h.
Referenced by is_GPIO().
initialised
bool SRV_Channels::initialised static private
Definition at line 597 of file SRV_Channel.h.
Referenced by function_assigned(), get_output_channel_mask(), and update_aux_servo_function().
invalid_mask
uint32_t SRV_Channels::invalid_mask static private
Definition at line 643 of file SRV_Channel.h.
Referenced by get_output_channel_mask(), and update_aux_servo_function().
obj_channels
SRV_Channel SRV_Channels::obj_channels[NUM_SERVO_CHANNELS] private
Definition at line 645 of file SRV_Channel.h.
Referenced by SRV_Channels().
override_counter
uint16_t SRV_Channels::override_counter static private
Definition at line 648 of file SRV_Channel.h.
Referenced by calc_pwm(), and set_output_pwm_chan_timeout().
override_counter_sem
HAL_Semaphore SRV_Channels::override_counter_sem private
Definition at line 686 of file SRV_Channel.h.
Referenced by calc_pwm(), and set_output_pwm_chan_timeout().
rc_fs_mask
AP_Int32 SRV_Channels::rc_fs_mask private
Definition at line 663 of file SRV_Channel.h.
Referenced by get_rc_fs_mask().
reversible_mask
uint32_t SRV_Channels::reversible_mask static private
Definition at line 640 of file SRV_Channel.h.
Referenced by set_digital_outputs().
trimmed_mask
SRV_Channel::servo_mask_t SRV_Channels::trimmed_mask private
Definition at line 594 of file SRV_Channel.h.
Referenced by adjust_trim(), and save_trim().
var_info
const AP_Param::GroupInfo SRV_Channels::var_info static
Definition at line 78 of file SRV_Channel.h.
The documentation for this class was generated from the following files:
libraries/SRV_Channel/SRV_Channel.h
libraries/SRV_Channel/SRV_Channel_aux.cpp
libraries/SRV_Channel/SRV_Channels.cpp