APM:Libraries: AP_Baro_KellerLD Class Reference
AP_Baro_KellerLD Class Reference
#include <AP_Baro_KellerLD.h>
Public Member Functions
void update () override
Public Member Functions inherited from AP_Baro_Backend
AP_Baro_Backend (AP_Baro &baro)
virtual ~AP_Baro_Backend (void)
virtual void accumulate (void)
void backend_update (uint8_t instance)
bool pressure_ok (float press)
uint32_t get_error_count () const
Static Public Member Functions
static AP_Baro_Backend * probe (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
Private Types
enum class SensorMode { PR_MODE = 0 , PA_MODE = 1 , PAA_MODE = 2 , UNDEFINED = 3 }
Private Member Functions
AP_Baro_KellerLD (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
bool _init ()
void _timer ()
bool _read ()
void _update_and_wrap_accumulator (uint16_t pressure, uint16_t temperature, uint8_t max_count)
bool transfer_with_delays (uint8_t *send, uint8_t sendlen, uint8_t *recv, uint8_t recvlen)
bool read_measurement_limit (float *limit, uint8_t msb_addr, uint8_t lsb_addr)
bool read_cal ()
bool read_mode_type ()
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _dev
struct {
uint32_t sum_pressure
uint32_t sum_temperature
uint8_t num_samples
} _accum
uint8_t _instance
SensorMode _p_mode
float _p_mode_offset
float _p_min
float _p_max
Additional Inherited Members
Public Types inherited from AP_Baro_Backend
enum DevTypes {
DEVTYPE_BARO_SITL = 0x01 , DEVTYPE_BARO_BMP085 = 0x02 , DEVTYPE_BARO_BMP280 = 0x03 , DEVTYPE_BARO_BMP388 = 0x04 ,
DEVTYPE_BARO_DPS280 = 0x05 , DEVTYPE_BARO_DPS310 = 0x06 , DEVTYPE_BARO_FBM320 = 0x07 , DEVTYPE_BARO_ICM20789 = 0x08 ,
DEVTYPE_BARO_KELLERLD = 0x09 , DEVTYPE_BARO_LPS2XH = 0x0A , DEVTYPE_BARO_MS5611 = 0x0B , DEVTYPE_BARO_SPL06 = 0x0C ,
DEVTYPE_BARO_UAVCAN = 0x0D , DEVTYPE_BARO_MSP = 0x0E , DEVTYPE_BARO_ICP101XX = 0x0F , DEVTYPE_BARO_ICP201XX = 0x10 ,
DEVTYPE_BARO_MS5607 = 0x11 , DEVTYPE_BARO_MS5837 = 0x12 , DEVTYPE_BARO_MS5637 = 0x13 , DEVTYPE_BARO_BMP390 = 0x14
}
Protected Member Functions inherited from AP_Baro_Backend
void _copy_to_frontend (uint8_t instance, float pressure, float temperature)
virtual void update_healthy_flag (uint8_t instance)
void set_bus_id (uint8_t instance, uint32_t id)
Protected Attributes inherited from AP_Baro_Backend
AP_Baro & _frontend
HAL_Semaphore _sem
float _mean_pressure
uint32_t _error_count
Detailed Description
Definition at line 40 of file AP_Baro_KellerLD.h.
Member Enumeration Documentation
SensorMode
enum class AP_Baro_KellerLD::SensorMode strong private
Enumerator
PR_MODE
PA_MODE
PAA_MODE
UNDEFINED
Definition at line 70 of file AP_Baro_KellerLD.h.
Constructor & Destructor Documentation
AP_Baro_KellerLD()
AP_Baro_KellerLD::AP_Baro_KellerLD (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev) private
Definition at line 46 of file AP_Baro_KellerLD.cpp.
Referenced by probe().
Member Function Documentation
_init()
bool AP_Baro_KellerLD::_init () private
Definition at line 178 of file AP_Baro_KellerLD.cpp.
Referenced by probe().
_read()
bool AP_Baro_KellerLD::_read () private
Definition at line 227 of file AP_Baro_KellerLD.cpp.
Referenced by _timer().
_timer()
void AP_Baro_KellerLD::_timer (void) private
Definition at line 269 of file AP_Baro_KellerLD.cpp.
Referenced by _init().
_update_and_wrap_accumulator()
void AP_Baro_KellerLD::_update_and_wrap_accumulator (uint16_t pressure, uint16_t temperature, uint8_t max_count) private
Definition at line 276 of file AP_Baro_KellerLD.cpp.
Referenced by _read().
probe()
AP_Baro_Backend * AP_Baro_KellerLD::probe (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev) static
Definition at line 53 of file AP_Baro_KellerLD.cpp.
Referenced by AP_Baro::_probe_i2c_barometers(), and AP_Baro::init().
read_cal()
bool AP_Baro_KellerLD::read_cal () private
Definition at line 117 of file AP_Baro_KellerLD.cpp.
Referenced by _init().
read_measurement_limit()
bool AP_Baro_KellerLD::read_measurement_limit (float * limit, uint8_t msb_addr, uint8_t lsb_addr) private
Definition at line 88 of file AP_Baro_KellerLD.cpp.
Referenced by read_cal().
read_mode_type()
bool AP_Baro_KellerLD::read_mode_type () private
Definition at line 138 of file AP_Baro_KellerLD.cpp.
Referenced by _init().
transfer_with_delays()
bool AP_Baro_KellerLD::transfer_with_delays (uint8_t * send, uint8_t sendlen, uint8_t * recv, uint8_t recvlen) private
Definition at line 68 of file AP_Baro_KellerLD.cpp.
Referenced by read_measurement_limit(), and read_mode_type().
update()
void AP_Baro_KellerLD::update (void) override virtual
Implements AP_Baro_Backend.
Definition at line 290 of file AP_Baro_KellerLD.cpp.
Member Data Documentation
[struct]
struct { ... } AP_Baro_KellerLD::_accum
Referenced by _init(), _update_and_wrap_accumulator(), and update().
_dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_Baro_KellerLD::_dev private
Definition at line 58 of file AP_Baro_KellerLD.h.
Referenced by _init(), _read(), _timer(), and transfer_with_delays().
_instance
uint8_t AP_Baro_KellerLD::_instance private
Definition at line 68 of file AP_Baro_KellerLD.h.
Referenced by _init(), and update().
_p_max
float AP_Baro_KellerLD::_p_max private
Definition at line 84 of file AP_Baro_KellerLD.h.
Referenced by read_cal(), and update().
_p_min
float AP_Baro_KellerLD::_p_min private
Definition at line 83 of file AP_Baro_KellerLD.h.
Referenced by read_cal(), read_measurement_limit(), and update().
_p_mode
SensorMode AP_Baro_KellerLD::_p_mode private
Definition at line 78 of file AP_Baro_KellerLD.h.
Referenced by read_mode_type(), and update().
_p_mode_offset
float AP_Baro_KellerLD::_p_mode_offset private
Definition at line 81 of file AP_Baro_KellerLD.h.
Referenced by read_mode_type(), and update().
num_samples
uint8_t AP_Baro_KellerLD::num_samples
Definition at line 65 of file AP_Baro_KellerLD.h.
Referenced by update().
sum_pressure
uint32_t AP_Baro_KellerLD::sum_pressure
Definition at line 63 of file AP_Baro_KellerLD.h.
Referenced by update().
sum_temperature
uint32_t AP_Baro_KellerLD::sum_temperature
Definition at line 64 of file AP_Baro_KellerLD.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/AP_Baro/AP_Baro_KellerLD.h
libraries/AP_Baro/AP_Baro_KellerLD.cpp