APM:Libraries: AP_Mount_Backend Class Reference
AP_Mount_Backend Class Reference abstract
#include <AP_Mount_Backend.h>
Classes
struct mavlink_control_id_t
class MountTarget
Public Member Functions
AP_Mount_Backend (class AP_Mount &frontend, class AP_Mount_Params &params, uint8_t instance)
virtual void init ()
void set_dev_id (uint32_t id)
virtual void update ()=0
virtual void update_fast ()
virtual bool healthy () const
virtual bool has_roll_control () const
virtual bool has_pitch_control () const
virtual bool has_pan_control () const =0
virtual bool get_attitude_quaternion (Quaternion &att_quat)=0
virtual bool get_angular_velocity (Vector3f &rates)
bool valid_mode (MAV_MOUNT_MODE mode) const
enum MAV_MOUNT_MODE get_mode () const
bool set_mode (enum MAV_MOUNT_MODE mode)
void set_yaw_lock (bool yaw_lock)
void set_angle_target (float roll_deg, float pitch_deg, float yaw_deg, bool yaw_is_earth_frame)
void set_rate_target (float roll_degs, float pitch_degs, float yaw_degs, bool yaw_is_earth_frame)
void set_roi_target (const Location &target_loc)
void clear_roi_target ()
void set_target_sysid (uint8_t sysid)
MAV_RESULT handle_command_do_mount_control (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_gimbal_manager_configure (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
void send_gimbal_device_attitude_status (mavlink_channel_t chan)
virtual uint32_t get_gimbal_manager_capability_flags () const
void send_gimbal_manager_information (mavlink_channel_t chan)
void send_gimbal_manager_status (mavlink_channel_t chan)
virtual void handle_gimbal_report (mavlink_channel_t chan, const mavlink_message_t &msg)
virtual void handle_param_value (const mavlink_message_t &msg)
bool handle_global_position_int (uint8_t msg_sysid, const mavlink_global_position_int_t &packet)
virtual void handle_gimbal_device_information (const mavlink_message_t &msg)
virtual void handle_gimbal_device_attitude_status (const mavlink_message_t &msg)
bool get_rate_target (float &roll_degs, float &pitch_degs, float &yaw_degs, bool &yaw_is_earth_frame)
bool get_angle_target (float &roll_deg, float &pitch_deg, float &yaw_deg, bool &yaw_is_earth_frame)
virtual bool get_location_target (Location &target_loc)
virtual void set_attitude_euler (float roll_deg, float pitch_deg, float yaw_bf_deg)
void write_log (uint64_t timestamp_us)
virtual bool take_picture ()
virtual bool record_video (bool start_recording)
virtual bool set_zoom (ZoomType zoom_type, float zoom_value)
virtual SetFocusResult set_focus (FocusType focus_type, float focus_value)
virtual bool set_tracking (TrackingType tracking_type, const Vector2f &p1, const Vector2f &p2)
virtual bool set_lens (uint8_t lens)
virtual void send_camera_information (mavlink_channel_t chan) const
virtual void send_camera_settings (mavlink_channel_t chan) const
virtual void send_camera_capture_status (mavlink_channel_t chan) const
virtual bool get_rangefinder_distance (float &distance_m) const
Protected Types
enum class MountTargetType { ANGLE , RATE }
Protected Member Functions
bool yaw_range_valid () const
virtual bool suppress_heartbeat () const
void set_rctargeting_on_rcinput_change ()
void get_rc_input (float &roll_in, float &pitch_in, float &yaw_in) const
void get_rc_target (MountTargetType &target_type, MountTarget &rpy) const
bool get_angle_target_to_location (const Location &loc, MountTarget &angle_rad) const WARN_IF_UNUSED
bool get_angle_target_to_roi (MountTarget &angle_rad) const WARN_IF_UNUSED
bool get_angle_target_to_home (MountTarget &angle_rad) const WARN_IF_UNUSED
bool get_angle_target_to_sysid (MountTarget &angle_rad) const WARN_IF_UNUSED
void update_angle_target_from_rate (const MountTarget &rate_rad, MountTarget &angle_rad) const
uint16_t get_gimbal_device_flags () const
void send_warning_to_GCS (const char *warning_str)
Protected Attributes
AP_Mount & _frontend
AP_Mount_Params & _params
uint8_t _instance
MAV_MOUNT_MODE _mode
bool _yaw_lock
struct {
MountTargetType target_type
MountTarget angle_rad
MountTarget rate_rads
} mnt_target
Location _roi_target
bool _roi_target_set
uint8_t _target_sysid
Location _target_sysid_location
bool _target_sysid_location_set
uint32_t _last_warning_ms
struct {
int16_t roll_in
int16_t pitch_in
int16_t yaw_in
} last_rc_input
struct AP_Mount_Backend::mavlink_control_id_t mavlink_control_id
Detailed Description
Definition at line 33 of file AP_Mount_Backend.h.
Member Enumeration Documentation
MountTargetType
enum class AP_Mount_Backend::MountTargetType strong protected
Enumerator
ANGLE
RATE
Definition at line 208 of file AP_Mount_Backend.h.
Constructor & Destructor Documentation
AP_Mount_Backend()
AP_Mount_Backend::AP_Mount_Backend (class AP_Mount & frontend, class AP_Mount_Params & params, uint8_t instance) inline
Definition at line 37 of file AP_Mount_Backend.h.
Member Function Documentation
clear_roi_target()
void AP_Mount_Backend::clear_roi_target ()
Definition at line 123 of file AP_Mount_Backend.cpp.
get_angle_target()
bool AP_Mount_Backend::get_angle_target (float & roll_deg, float & pitch_deg, float & yaw_deg, bool & yaw_is_earth_frame)
Definition at line 846 of file AP_Mount_Backend.cpp.
get_angle_target_to_home()
bool AP_Mount_Backend::get_angle_target_to_home (MountTarget & angle_rad) const protected
Definition at line 809 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount_Alexmos::update(), AP_Mount_Servo::update(), AP_Mount_Siyi::update(), and AP_Mount_SToRM32_serial::update().
get_angle_target_to_location()
bool AP_Mount_Backend::get_angle_target_to_location (const Location & loc, MountTarget & angle_rad) const protected
Definition at line 689 of file AP_Mount_Backend.cpp.
Referenced by get_angle_target_to_home(), get_angle_target_to_roi(), and get_angle_target_to_sysid().
get_angle_target_to_roi()
bool AP_Mount_Backend::get_angle_target_to_roi (MountTarget & angle_rad) const protected
Definition at line 726 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount_Alexmos::update(), AP_Mount_Servo::update(), AP_Mount_Siyi::update(), and AP_Mount_SToRM32_serial::update().
get_angle_target_to_sysid()
bool AP_Mount_Backend::get_angle_target_to_sysid (MountTarget & angle_rad) const protected
Definition at line 820 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount_Alexmos::update(), AP_Mount_Servo::update(), AP_Mount_Siyi::update(), and AP_Mount_SToRM32_serial::update().
get_angular_velocity()
virtual bool AP_Mount_Backend::get_angular_velocity (Vector3f & rates) inline virtual
Reimplemented in AP_Mount_Siyi.
Definition at line 71 of file AP_Mount_Backend.h.
get_attitude_quaternion()
virtual bool AP_Mount_Backend::get_attitude_quaternion (Quaternion & att_quat) pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_Siyi, and AP_Mount_SToRM32_serial.
get_gimbal_device_flags()
uint16_t AP_Mount_Backend::get_gimbal_device_flags () const protected
Definition at line 798 of file AP_Mount_Backend.cpp.
get_gimbal_manager_capability_flags()
uint32_t AP_Mount_Backend::get_gimbal_manager_capability_flags () const virtual
Definition at line 188 of file AP_Mount_Backend.cpp.
Referenced by send_gimbal_manager_information().
get_location_target()
virtual bool AP_Mount_Backend::get_location_target (Location & target_loc) inline virtual
Definition at line 153 of file AP_Mount_Backend.h.
get_mode()
enum MAV_MOUNT_MODE AP_Mount_Backend::get_mode () const inline
Definition at line 77 of file AP_Mount_Backend.h.
Referenced by clear_roi_target(), get_gimbal_device_flags(), set_rctargeting_on_rcinput_change(), AP_Mount_Alexmos::update(), AP_Mount_Servo::update(), AP_Mount_Siyi::update(), and AP_Mount_SToRM32_serial::update().
get_rangefinder_distance()
virtual bool AP_Mount_Backend::get_rangefinder_distance (float & distance_m) const inline virtual
Reimplemented in AP_Mount_Siyi.
Definition at line 204 of file AP_Mount_Backend.h.
get_rate_target()
bool AP_Mount_Backend::get_rate_target (float & roll_degs, float & pitch_degs, float & yaw_degs, bool & yaw_is_earth_frame)
Definition at line 833 of file AP_Mount_Backend.cpp.
get_rc_input()
void AP_Mount_Backend::get_rc_input (float & roll_in, float & pitch_in, float & yaw_in) const protected
Definition at line 625 of file AP_Mount_Backend.cpp.
Referenced by get_rc_target().
get_rc_target()
void AP_Mount_Backend::get_rc_target (MountTargetType & target_type, MountTarget & rpy) const protected
Definition at line 649 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount_Alexmos::update(), AP_Mount_Servo::update(), AP_Mount_Siyi::update(), and AP_Mount_SToRM32_serial::update().
handle_command_do_gimbal_manager_configure()
MAV_RESULT AP_Mount_Backend::handle_command_do_gimbal_manager_configure (const mavlink_command_int_t & packet, const mavlink_message_t & msg)
Definition at line 354 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount::handle_command_do_gimbal_manager_configure().
handle_command_do_mount_control()
MAV_RESULT AP_Mount_Backend::handle_command_do_mount_control (const mavlink_command_int_t & packet)
Definition at line 293 of file AP_Mount_Backend.cpp.
handle_gimbal_device_attitude_status()
virtual void AP_Mount_Backend::handle_gimbal_device_attitude_status (const mavlink_message_t & msg) inline virtual
Definition at line 144 of file AP_Mount_Backend.h.
Referenced by AP_Mount::handle_gimbal_device_attitude_status().
handle_gimbal_device_information()
virtual void AP_Mount_Backend::handle_gimbal_device_information (const mavlink_message_t & msg) inline virtual
Definition at line 141 of file AP_Mount_Backend.h.
Referenced by AP_Mount::handle_gimbal_device_information().
handle_gimbal_report()
virtual void AP_Mount_Backend::handle_gimbal_report (mavlink_channel_t chan, const mavlink_message_t & msg) inline virtual
Definition at line 132 of file AP_Mount_Backend.h.
Referenced by AP_Mount::handle_gimbal_report().
handle_global_position_int()
bool AP_Mount_Backend::handle_global_position_int (uint8_t msg_sysid, const mavlink_global_position_int_t & packet)
Definition at line 397 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount::handle_global_position_int().
handle_param_value()
virtual void AP_Mount_Backend::handle_param_value (const mavlink_message_t & msg) inline virtual
Definition at line 135 of file AP_Mount_Backend.h.
Referenced by AP_Mount::handle_param_value().
has_pan_control()
virtual bool AP_Mount_Backend::has_pan_control () const pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_Siyi, and AP_Mount_SToRM32_serial.
Referenced by get_gimbal_manager_capability_flags().
has_pitch_control()
bool AP_Mount_Backend::has_pitch_control () const virtual
Definition at line 44 of file AP_Mount_Backend.cpp.
Referenced by get_gimbal_manager_capability_flags().
has_roll_control()
bool AP_Mount_Backend::has_roll_control () const virtual
Reimplemented in AP_Mount_Siyi.
Definition at line 38 of file AP_Mount_Backend.cpp.
Referenced by get_gimbal_manager_capability_flags().
healthy()
virtual bool AP_Mount_Backend::healthy () const inline virtual
Reimplemented in AP_Mount_Siyi.
Definition at line 56 of file AP_Mount_Backend.h.
init()
void AP_Mount_Backend::init () virtual
Reimplemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_Siyi, and AP_Mount_SToRM32_serial.
Definition at line 16 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount::init(), AP_Mount_Alexmos::init(), AP_Mount_Servo::init(), AP_Mount_Siyi::init(), and AP_Mount_SToRM32_serial::init().
record_video()
virtual bool AP_Mount_Backend::record_video (bool start_recording) inline virtual
Reimplemented in AP_Mount_Siyi.
Definition at line 168 of file AP_Mount_Backend.h.
send_camera_capture_status()
virtual void AP_Mount_Backend::send_camera_capture_status (mavlink_channel_t chan) const inline virtual
Definition at line 192 of file AP_Mount_Backend.h.
send_camera_information()
virtual void AP_Mount_Backend::send_camera_information (mavlink_channel_t chan) const inline virtual
Reimplemented in AP_Mount_Siyi.
Definition at line 186 of file AP_Mount_Backend.h.
send_camera_settings()
virtual void AP_Mount_Backend::send_camera_settings (mavlink_channel_t chan) const inline virtual
Reimplemented in AP_Mount_Siyi.
Definition at line 189 of file AP_Mount_Backend.h.
send_gimbal_device_attitude_status()
void AP_Mount_Backend::send_gimbal_device_attitude_status (mavlink_channel_t chan)
send_gimbal_manager_information()
void AP_Mount_Backend::send_gimbal_manager_information (mavlink_channel_t chan)
Definition at line 221 of file AP_Mount_Backend.cpp.
send_gimbal_manager_status()
void AP_Mount_Backend::send_gimbal_manager_status (mavlink_channel_t chan)
Definition at line 236 of file AP_Mount_Backend.cpp.
send_warning_to_GCS()
void AP_Mount_Backend::send_warning_to_GCS (const char * warning_str) protected
Definition at line 859 of file AP_Mount_Backend.cpp.
Referenced by handle_command_do_mount_control().
set_angle_target()
void AP_Mount_Backend::set_angle_target (float roll_deg, float pitch_deg, float yaw_deg, bool yaw_is_earth_frame)
Definition at line 71 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount::handle_command_do_gimbal_manager_pitchyaw(), handle_command_do_mount_control(), AP_Mount::handle_gimbal_manager_set_attitude(), and AP_Mount::handle_gimbal_manager_set_pitchyaw().
set_attitude_euler()
virtual void AP_Mount_Backend::set_attitude_euler (float roll_deg, float pitch_deg, float yaw_bf_deg) inline virtual
Definition at line 154 of file AP_Mount_Backend.h.
set_dev_id()
void AP_Mount_Backend::set_dev_id (uint32_t id)
Definition at line 32 of file AP_Mount_Backend.cpp.
set_focus()
virtual SetFocusResult AP_Mount_Backend::set_focus (FocusType focus_type, float focus_value) inline virtual
Reimplemented in AP_Mount_Siyi.
Definition at line 175 of file AP_Mount_Backend.h.
set_lens()
virtual bool AP_Mount_Backend::set_lens (uint8_t lens) inline virtual
Reimplemented in AP_Mount_Siyi.
Definition at line 183 of file AP_Mount_Backend.h.
set_mode()
bool AP_Mount_Backend::set_mode (enum MAV_MOUNT_MODE mode)
Definition at line 60 of file AP_Mount_Backend.cpp.
Referenced by clear_roi_target(), AP_Mount::handle_command_do_gimbal_manager_pitchyaw(), handle_command_do_mount_control(), AP_Mount::handle_gimbal_manager_set_attitude(), AP_Mount::handle_gimbal_manager_set_pitchyaw(), set_angle_target(), set_rate_target(), set_rctargeting_on_rcinput_change(), set_roi_target(), and set_target_sysid().
set_rate_target()
void AP_Mount_Backend::set_rate_target (float roll_degs, float pitch_degs, float yaw_degs, bool yaw_is_earth_frame)
Definition at line 98 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount::handle_command_do_gimbal_manager_pitchyaw(), AP_Mount::handle_gimbal_manager_set_attitude(), and AP_Mount::handle_gimbal_manager_set_pitchyaw().
set_rctargeting_on_rcinput_change()
void AP_Mount_Backend::set_rctargeting_on_rcinput_change () protected
Definition at line 585 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount_Servo::update(), AP_Mount_Siyi::update(), and AP_Mount_SToRM32_serial::update().
set_roi_target()
void AP_Mount_Backend::set_roi_target (const Location & target_loc)
Definition at line 112 of file AP_Mount_Backend.cpp.
Referenced by handle_command_do_mount_control().
set_target_sysid()
void AP_Mount_Backend::set_target_sysid (uint8_t sysid)
Definition at line 136 of file AP_Mount_Backend.cpp.
set_tracking()
virtual bool AP_Mount_Backend::set_tracking (TrackingType tracking_type, const Vector2f & p1, const Vector2f & p2) inline virtual
Definition at line 180 of file AP_Mount_Backend.h.
set_yaw_lock()
void AP_Mount_Backend::set_yaw_lock (bool yaw_lock) inline
Definition at line 84 of file AP_Mount_Backend.h.
set_zoom()
virtual bool AP_Mount_Backend::set_zoom (ZoomType zoom_type, float zoom_value) inline virtual
Reimplemented in AP_Mount_Siyi.
Definition at line 171 of file AP_Mount_Backend.h.
suppress_heartbeat()
virtual bool AP_Mount_Backend::suppress_heartbeat () const inline protected virtual
Definition at line 236 of file AP_Mount_Backend.h.
take_picture()
virtual bool AP_Mount_Backend::take_picture () inline virtual
Reimplemented in AP_Mount_Siyi.
Definition at line 164 of file AP_Mount_Backend.h.
update()
virtual void AP_Mount_Backend::update () pure virtual
Implemented in AP_Mount_Alexmos, AP_Mount_Servo, AP_Mount_Siyi, and AP_Mount_SToRM32_serial.
Referenced by AP_Mount::update().
update_angle_target_from_rate()
void AP_Mount_Backend::update_angle_target_from_rate (const MountTarget & rate_rad, MountTarget & angle_rad) const protected
Definition at line 770 of file AP_Mount_Backend.cpp.
Referenced by AP_Mount_Alexmos::update(), AP_Mount_Servo::update(), and AP_Mount_SToRM32_serial::update().
update_fast()
virtual void AP_Mount_Backend::update_fast () inline virtual
Definition at line 53 of file AP_Mount_Backend.h.
Referenced by AP_Mount::update_fast().
valid_mode()
bool AP_Mount_Backend::valid_mode (MAV_MOUNT_MODE mode) const
Definition at line 49 of file AP_Mount_Backend.cpp.
Referenced by set_mode().
write_log()
void AP_Mount_Backend::write_log (uint64_t timestamp_us)
yaw_range_valid()
bool AP_Mount_Backend::yaw_range_valid () const inline protected
Definition at line 233 of file AP_Mount_Backend.h.
Referenced by AP_Mount_Alexmos::has_pan_control(), AP_Mount_Servo::has_pan_control(), AP_Mount_Siyi::has_pan_control(), and AP_Mount_SToRM32_serial::has_pan_control().
Member Data Documentation
_frontend
AP_Mount& AP_Mount_Backend::_frontend protected
Definition at line 281 of file AP_Mount_Backend.h.
_instance
uint8_t AP_Mount_Backend::_instance protected
Definition at line 283 of file AP_Mount_Backend.h.
Referenced by get_rc_input(), AP_Mount_Servo::init(), AP_Mount_Siyi::send_camera_information(), send_gimbal_manager_information(), send_gimbal_manager_status(), and set_rctargeting_on_rcinput_change().
_last_warning_ms
uint32_t AP_Mount_Backend::_last_warning_ms protected
Definition at line 313 of file AP_Mount_Backend.h.
Referenced by send_warning_to_GCS().
_mode
MAV_MOUNT_MODE AP_Mount_Backend::_mode protected
Definition at line 285 of file AP_Mount_Backend.h.
Referenced by get_mode(), and set_mode().
_params
AP_Mount_Params& AP_Mount_Backend::_params protected
Definition at line 282 of file AP_Mount_Backend.h.
Referenced by clear_roi_target(), AP_Mount_Servo::get_attitude_quaternion(), get_rc_target(), has_pitch_control(), has_roll_control(), init(), send_gimbal_manager_information(), AP_Mount_Siyi::send_target_angles(), set_angle_target(), set_dev_id(), AP_Mount_Alexmos::update(), AP_Mount_Servo::update(), AP_Mount_Siyi::update(), AP_Mount_SToRM32_serial::update(), AP_Mount_Servo::update_angle_outputs(), update_angle_target_from_rate(), and yaw_range_valid().
_roi_target
Location AP_Mount_Backend::_roi_target protected
Definition at line 306 of file AP_Mount_Backend.h.
Referenced by get_angle_target_to_roi(), and set_roi_target().
_roi_target_set
bool AP_Mount_Backend::_roi_target_set protected
Definition at line 307 of file AP_Mount_Backend.h.
Referenced by clear_roi_target(), get_angle_target_to_roi(), and set_roi_target().
_target_sysid
uint8_t AP_Mount_Backend::_target_sysid protected
Definition at line 309 of file AP_Mount_Backend.h.
Referenced by get_angle_target_to_sysid(), handle_global_position_int(), init(), and set_target_sysid().
_target_sysid_location
Location AP_Mount_Backend::_target_sysid_location protected
Definition at line 310 of file AP_Mount_Backend.h.
Referenced by get_angle_target_to_sysid(), and handle_global_position_int().
_target_sysid_location_set
bool AP_Mount_Backend::_target_sysid_location_set protected
Definition at line 311 of file AP_Mount_Backend.h.
Referenced by get_angle_target_to_sysid(), and handle_global_position_int().
_yaw_lock
bool AP_Mount_Backend::_yaw_lock protected
Definition at line 286 of file AP_Mount_Backend.h.
Referenced by get_rc_target(), send_gimbal_manager_status(), and set_yaw_lock().
angle_rad
MountTarget AP_Mount_Backend::angle_rad
Definition at line 291 of file AP_Mount_Backend.h.
Referenced by get_angle_target_to_home(), get_angle_target_to_location(), get_angle_target_to_roi(), get_angle_target_to_sysid(), AP_Mount_Servo::update_angle_outputs(), and update_angle_target_from_rate().
[struct]
struct { ... } AP_Mount_Backend::last_rc_input
Referenced by set_rctargeting_on_rcinput_change().
mavlink_control_id
struct AP_Mount_Backend::mavlink_control_id_t AP_Mount_Backend::mavlink_control_id protected
Referenced by handle_command_do_gimbal_manager_configure(), and send_gimbal_manager_status().
[struct]
struct { ... } AP_Mount_Backend::mnt_target
Referenced by get_angle_target(), AP_Mount_Servo::get_attitude_quaternion(), get_rate_target(), set_angle_target(), set_rate_target(), AP_Mount_Alexmos::update(), AP_Mount_Servo::update(), AP_Mount_Siyi::update(), and AP_Mount_SToRM32_serial::update().
pitch_in
int16_t AP_Mount_Backend::pitch_in
Definition at line 318 of file AP_Mount_Backend.h.
Referenced by get_rc_input(), get_rc_target(), and set_rctargeting_on_rcinput_change().
rate_rads
MountTarget AP_Mount_Backend::rate_rads
Definition at line 292 of file AP_Mount_Backend.h.
roll_in
int16_t AP_Mount_Backend::roll_in
Definition at line 317 of file AP_Mount_Backend.h.
Referenced by get_rc_input(), get_rc_target(), and set_rctargeting_on_rcinput_change().
target_type
MountTargetType AP_Mount_Backend::target_type
Definition at line 290 of file AP_Mount_Backend.h.
Referenced by get_rc_target().
yaw_in
int16_t AP_Mount_Backend::yaw_in
Definition at line 319 of file AP_Mount_Backend.h.
Referenced by get_rc_input(), get_rc_target(), and set_rctargeting_on_rcinput_change().
The documentation for this class was generated from the following files:
libraries/AP_Mount/AP_Mount_Backend.h
libraries/AP_Mount/AP_Mount_Backend.cpp