APM:Libraries: SITL::InvensenseV3 Class Reference
SITL::InvensenseV3 Class Reference abstract
#include <SIM_Invensense_v3.h>
Classes
struct FIFOData
Public Member Functions
void init () override
void update (const class Aircraft &aircraft) override
int rdwr (I2C::i2c_rdwr_ioctl_data *&data) override
virtual float accel_scale () const =0
float gyro_scale () const
Private Member Functions
void update_sample_count ()
void assert_register_values ()
void add_fifo (const char *name, uint8_t reg, I2CRegisters::RegMode mode)
bool write_to_fifo (uint8_t fifo, uint8_t *value, uint8_t valuelen)
int rdwr_fifo (I2C::i2c_rdwr_ioctl_data *&data)
int rdwr_block (I2C::i2c_rdwr_ioctl_data *&data)
void add_block (const char *name, uint8_t addr, uint8_t len, I2CRegisters::RegMode mode)
void set_block (uint8_t addr, uint8_t *value, uint8_t valuelen)
Private Attributes
const char * fifoname [256]
Bitmask< 256 > writable_fifos
Bitmask< 256 > readable_fifos
char * values [256]
uint8_t value_lengths [256]
const char * blockname [256]
Bitmask< 256 > writable_blocks
Bitmask< 256 > readable_blocks
char * block_values [256]
uint8_t block_value_lengths [256]
Static Private Attributes
static const uint8_t fifo_len = 64
Additional Inherited Members
Protected Types inherited from SITL::I2CRegisters
enum class RegMode { RDONLY = 11 , WRONLY = 22 , RDWR = 33 }
Protected Member Functions inherited from SITL::I2CRegisters_8Bit
virtual void rdwr_store_register_value (uint8_t reg, uint8_t value)
void set_register (uint8_t reg, uint8_t value)
void set_register (uint8_t reg, int8_t value)
uint8_t get_register (uint8_t num)
void assert_register_value (uint8_t reg, uint8_t value)
Protected Member Functions inherited from SITL::I2CRegisters
void add_register (const char *name, uint8_t reg, RegMode mode)
void set_debug (bool value)
bool get_debug () const
Protected Attributes inherited from SITL::I2CRegisters_8Bit
uint8_t byte [256]
Protected Attributes inherited from SITL::I2CRegisters
const char * regname [256]
Bitmask< 256 > writable_registers
Bitmask< 256 > readable_registers
Detailed Description
Definition at line 24 of file SIM_Invensense_v3.h.
Member Function Documentation
accel_scale()
virtual float SITL::InvensenseV3::accel_scale () const pure virtual
Implemented in SITL::ICM40609.
Referenced by update().
add_block()
void SITL::InvensenseV3::add_block (const char * name, uint8_t addr, uint8_t len, I2CRegisters::RegMode mode) private
Definition at line 159 of file SIM_Invensense_v3.cpp.
Referenced by init().
add_fifo()
void SITL::InvensenseV3::add_fifo (const char * name, uint8_t reg, I2CRegisters::RegMode mode) private
Definition at line 105 of file SIM_Invensense_v3.cpp.
Referenced by init().
assert_register_values()
void SITL::InvensenseV3::assert_register_values () private
Definition at line 36 of file SIM_Invensense_v3.cpp.
gyro_scale()
float SITL::InvensenseV3::gyro_scale () const inline
Definition at line 48 of file SIM_Invensense_v3.h.
Referenced by update().
init()
void SITL::InvensenseV3::init () inline override virtual
Reimplemented from SITL::I2CDevice.
Definition at line 27 of file SIM_Invensense_v3.h.
Referenced by SITL::ICM40609::init().
rdwr()
int SITL::InvensenseV3::rdwr (I2C::i2c_rdwr_ioctl_data *& data) override virtual
Implements SITL::I2CDevice.
Definition at line 55 of file SIM_Invensense_v3.cpp.
rdwr_block()
int SITL::InvensenseV3::rdwr_block (I2C::i2c_rdwr_ioctl_data *& data) private
Definition at line 189 of file SIM_Invensense_v3.cpp.
rdwr_fifo()
int SITL::InvensenseV3::rdwr_fifo (I2C::i2c_rdwr_ioctl_data *& data) private
Definition at line 71 of file SIM_Invensense_v3.cpp.
set_block()
void SITL::InvensenseV3::set_block (uint8_t addr, uint8_t * value, uint8_t valuelen) private
Definition at line 178 of file SIM_Invensense_v3.cpp.
update()
void SITL::InvensenseV3::update (const class Aircraft & aircraft) override virtual
Reimplemented from SITL::I2CDevice.
Definition at line 5 of file SIM_Invensense_v3.cpp.
update_sample_count()
void SITL::InvensenseV3::update_sample_count () private
Definition at line 124 of file SIM_Invensense_v3.cpp.
Referenced by update().
write_to_fifo()
bool SITL::InvensenseV3::write_to_fifo (uint8_t fifo, uint8_t * value, uint8_t valuelen) private
Definition at line 133 of file SIM_Invensense_v3.cpp.
Referenced by update().
Member Data Documentation
block_value_lengths
uint8_t SITL::InvensenseV3::block_value_lengths[256] private
Definition at line 91 of file SIM_Invensense_v3.h.
block_values
char* SITL::InvensenseV3::block_values[256] private
Definition at line 90 of file SIM_Invensense_v3.h.
blockname
const char* SITL::InvensenseV3::blockname[256] private
Definition at line 85 of file SIM_Invensense_v3.h.
fifo_len
const uint8_t SITL::InvensenseV3::fifo_len = 64 static private
Definition at line 61 of file SIM_Invensense_v3.h.
fifoname
const char* SITL::InvensenseV3::fifoname[256] private
Definition at line 62 of file SIM_Invensense_v3.h.
readable_blocks
Bitmask<256> SITL::InvensenseV3::readable_blocks private
Definition at line 87 of file SIM_Invensense_v3.h.
readable_fifos
Bitmask<256> SITL::InvensenseV3::readable_fifos private
Definition at line 64 of file SIM_Invensense_v3.h.
value_lengths
uint8_t SITL::InvensenseV3::value_lengths[256] private
Definition at line 68 of file SIM_Invensense_v3.h.
values
char* SITL::InvensenseV3::values[256] private
Definition at line 67 of file SIM_Invensense_v3.h.
writable_blocks
Bitmask<256> SITL::InvensenseV3::writable_blocks private
Definition at line 86 of file SIM_Invensense_v3.h.
writable_fifos
Bitmask<256> SITL::InvensenseV3::writable_fifos private
Definition at line 63 of file SIM_Invensense_v3.h.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_Invensense_v3.h
libraries/SITL/SIM_Invensense_v3.cpp