APM:Libraries: RangeFinder Class Reference
RangeFinder Class Reference
#include <AP_RangeFinder.h>
Classes
struct RangeFinder_State
Public Types
enum class Type {
NONE = 0 , ANALOG = 1 , MBI2C = 2 , PLI2C = 3 ,
PX4_PWM = 5 , BBB_PRU = 6 , LWI2C = 7 , LWSER = 8 ,
USD1_Serial = 11 , LEDDARONE = 12 , MBSER = 13 , TRI2C = 14 ,
PLI2CV3 = 15 , VL53L0X = 16 , NMEA = 17 , WASP = 18 ,
BenewakeTF02 = 19 , BenewakeTFmini = 20 , PLI2CV3HP = 21 , PWM = 22 ,
BLPing = 23 , BenewakeTFminiPlus = 25 , Lanbao = 26 , BenewakeTF03 = 27 ,
VL53L1X_Short = 28 , LeddarVu8_Serial = 29 , HC_SR04 = 30 , GYUS42v2 = 31 ,
TeraRanger_Serial = 35 , SIM = 100
}
enum class Function { LINEAR = 0 , INVERTED = 1 , HYPERBOLA = 2 }
enum class Status {
NotConnected = 0 , NoData , OutOfRangeLow , OutOfRangeHigh ,
Good
}
Public Member Functions
RangeFinder ()
CLASS_NO_COPY (RangeFinder)
void set_log_rfnd_bit (uint32_t log_rfnd_bit)
uint8_t num_sensors (void) const
bool prearm_healthy (char *failure_msg, const uint8_t failure_msg_len) const
void init (enum Rotation orientation_default)
void update (void)
void handle_msg (const mavlink_message_t &msg)
bool has_orientation (enum Rotation orientation) const
AP_RangeFinder_Backend * find_instance (enum Rotation orientation) const
AP_RangeFinder_Backend * get_backend (uint8_t id) const
Type get_type (uint8_t id) const
uint8_t get_address (uint8_t id) const
float distance_orient (enum Rotation orientation) const
uint16_t distance_cm_orient (enum Rotation orientation) const
int8_t signal_quality_pct_orient (enum Rotation orientation) const
int16_t max_distance_cm_orient (enum Rotation orientation) const
int16_t min_distance_cm_orient (enum Rotation orientation) const
int16_t ground_clearance_cm_orient (enum Rotation orientation) const
MAV_DISTANCE_SENSOR get_mav_distance_sensor_type_orient (enum Rotation orientation) const
RangeFinder::Status status_orient (enum Rotation orientation) const
bool has_data_orient (enum Rotation orientation) const
uint8_t range_valid_count_orient (enum Rotation orientation) const
const Vector3f & get_pos_offset_orient (enum Rotation orientation) const
uint32_t last_reading_ms (enum Rotation orientation) const
bool get_temp (enum Rotation orientation, float &temp) const
void set_estimated_terrain_height (float height)
Static Public Member Functions
static RangeFinder * get_singleton (void)
Static Public Attributes
static constexpr int8_t SIGNAL_QUALITY_MIN = 0
static constexpr int8_t SIGNAL_QUALITY_MAX = 100
static constexpr int8_t SIGNAL_QUALITY_UNKNOWN = -1
static const struct AP_Param::GroupInfo * backend_var_info [RANGEFINDER_MAX_INSTANCES]
static const struct AP_Param::GroupInfo var_info []
Protected Attributes
AP_RangeFinder_Params params [RANGEFINDER_MAX_INSTANCES]
Private Member Functions
void detect_instance (uint8_t instance, uint8_t &serial_instance)
bool _add_backend (AP_RangeFinder_Backend *driver, uint8_t instance, uint8_t serial_instance=0)
void Log_RFND () const
Private Attributes
RangeFinder_State state [RANGEFINDER_MAX_INSTANCES]
AP_RangeFinder_Backend * drivers [RANGEFINDER_MAX_INSTANCES]
uint8_t num_instances
HAL_Semaphore detect_sem
float estimated_terrain_height
Vector3f pos_offset_zero
uint32_t _log_rfnd_bit = -1
Static Private Attributes
static RangeFinder * _singleton
Friends
class AP_RangeFinder_Backend
class AP_RangeFinder_DroneCAN
Detailed Description
Definition at line 46 of file AP_RangeFinder.h.
Member Enumeration Documentation
Function
enum class RangeFinder::Function strong
Enumerator
LINEAR
INVERTED
HYPERBOLA
Definition at line 182 of file AP_RangeFinder.h.
Status
enum class RangeFinder::Status strong
Enumerator
NotConnected
NoData
OutOfRangeLow
OutOfRangeHigh
Good
Definition at line 188 of file AP_RangeFinder.h.
Type
enum class RangeFinder::Type strong
Enumerator
NONE
ANALOG
MBI2C
PLI2C
PX4_PWM
BBB_PRU
LWI2C
LWSER
USD1_Serial
LEDDARONE
MBSER
TRI2C
PLI2CV3
VL53L0X
NMEA
WASP
BenewakeTF02
BenewakeTFmini
PLI2CV3HP
PWM
BLPing
BenewakeTFminiPlus
Lanbao
BenewakeTF03
VL53L1X_Short
LeddarVu8_Serial
HC_SR04
GYUS42v2
TeraRanger_Serial
SIM
Definition at line 58 of file AP_RangeFinder.h.
Constructor & Destructor Documentation
RangeFinder()
RangeFinder::RangeFinder ()
Definition at line 178 of file AP_RangeFinder.cpp.
Member Function Documentation
_add_backend()
bool RangeFinder::_add_backend (AP_RangeFinder_Backend * driver, uint8_t instance, uint8_t serial_instance = 0) private
Definition at line 250 of file AP_RangeFinder.cpp.
Referenced by detect_instance().
CLASS_NO_COPY()
RangeFinder::CLASS_NO_COPY (RangeFinder)
detect_instance()
void RangeFinder::detect_instance (uint8_t instance, uint8_t & serial_instance) private
Definition at line 272 of file AP_RangeFinder.cpp.
Referenced by init().
distance_cm_orient()
uint16_t RangeFinder::distance_cm_orient (enum Rotation orientation) const
Definition at line 693 of file AP_RangeFinder.cpp.
Referenced by AP_Frsky_SPort_Passthrough::calc_attiandrng().
distance_orient()
float RangeFinder::distance_orient (enum Rotation orientation) const
Definition at line 684 of file AP_RangeFinder.cpp.
Referenced by distance_cm_orient(), and AP_OSD_Screen::draw_rngf().
find_instance()
AP_RangeFinder_Backend * RangeFinder::find_instance (enum Rotation orientation) const
Definition at line 662 of file AP_RangeFinder.cpp.
Referenced by distance_orient(), get_mav_distance_sensor_type_orient(), get_pos_offset_orient(), get_temp(), ground_clearance_cm_orient(), has_data_orient(), has_orientation(), last_reading_ms(), max_distance_cm_orient(), min_distance_cm_orient(), range_valid_count_orient(), signal_quality_pct_orient(), and status_orient().
get_address()
uint8_t RangeFinder::get_address (uint8_t id) const inline
Definition at line 260 of file AP_RangeFinder.h.
get_backend()
AP_RangeFinder_Backend * RangeFinder::get_backend (uint8_t id) const
Definition at line 611 of file AP_RangeFinder.cpp.
Referenced by find_instance(), loop(), GCS_MAVLINK::send_distance_sensor(), and AP_DAL_RangeFinder::start_frame().
get_mav_distance_sensor_type_orient()
MAV_DISTANCE_SENSOR RangeFinder::get_mav_distance_sensor_type_orient (enum Rotation orientation) const
Definition at line 770 of file AP_RangeFinder.cpp.
get_pos_offset_orient()
const Vector3f & RangeFinder::get_pos_offset_orient (enum Rotation orientation) const
Definition at line 752 of file AP_RangeFinder.cpp.
get_singleton()
static RangeFinder * RangeFinder::get_singleton (void) inline static
Definition at line 290 of file AP_RangeFinder.h.
Referenced by AP_Frsky_SPort_Passthrough::calc_attiandrng(), AP_OSD_Screen::draw_rngf(), AP::rangefinder(), AP_Arming::rangefinder_checks(), and GCS_MAVLINK::send_distance_sensor().
get_temp()
bool RangeFinder::get_temp (enum Rotation orientation, float & temp) const
Definition at line 780 of file AP_RangeFinder.cpp.
get_type()
Type RangeFinder::get_type (uint8_t id) const inline
Definition at line 255 of file AP_RangeFinder.h.
ground_clearance_cm_orient()
int16_t RangeFinder::ground_clearance_cm_orient (enum Rotation orientation) const
Definition at line 725 of file AP_RangeFinder.cpp.
Referenced by AP_DAL_RangeFinder::ground_clearance_cm_orient(), and AP_DAL_RangeFinder::start_frame().
handle_msg()
void RangeFinder::handle_msg (const mavlink_message_t & msg)
Definition at line 633 of file AP_RangeFinder.cpp.
Referenced by GCS_MAVLINK::handle_distance_sensor().
has_data_orient()
bool RangeFinder::has_data_orient (enum Rotation orientation) const
Definition at line 734 of file AP_RangeFinder.cpp.
has_orientation()
bool RangeFinder::has_orientation (enum Rotation orientation) const
Definition at line 656 of file AP_RangeFinder.cpp.
init()
void RangeFinder::init (enum Rotation orientation_default)
Definition at line 195 of file AP_RangeFinder.cpp.
Referenced by setup().
last_reading_ms()
uint32_t RangeFinder::last_reading_ms (enum Rotation orientation) const
Definition at line 761 of file AP_RangeFinder.cpp.
Log_RFND()
void RangeFinder::Log_RFND () const private
Referenced by update().
max_distance_cm_orient()
int16_t RangeFinder::max_distance_cm_orient (enum Rotation orientation) const
Definition at line 707 of file AP_RangeFinder.cpp.
Referenced by AP_DAL_RangeFinder::max_distance_cm_orient(), and AP_DAL_RangeFinder::start_frame().
min_distance_cm_orient()
int16_t RangeFinder::min_distance_cm_orient (enum Rotation orientation) const
Definition at line 716 of file AP_RangeFinder.cpp.
num_sensors()
uint8_t RangeFinder::num_sensors (void) const inline
Definition at line 225 of file AP_RangeFinder.h.
Referenced by AP_DAL_RangeFinder::AP_DAL_RangeFinder(), loop(), and setup().
prearm_healthy()
bool RangeFinder::prearm_healthy (char * failure_msg, const uint8_t failure_msg_len) const
Definition at line 822 of file AP_RangeFinder.cpp.
range_valid_count_orient()
uint8_t RangeFinder::range_valid_count_orient (enum Rotation orientation) const
Definition at line 743 of file AP_RangeFinder.cpp.
set_estimated_terrain_height()
void RangeFinder::set_estimated_terrain_height (float height) inline
Definition at line 286 of file AP_RangeFinder.h.
set_log_rfnd_bit()
void RangeFinder::set_log_rfnd_bit (uint32_t log_rfnd_bit) inline
Definition at line 217 of file AP_RangeFinder.h.
signal_quality_pct_orient()
int8_t RangeFinder::signal_quality_pct_orient (enum Rotation orientation) const
Definition at line 698 of file AP_RangeFinder.cpp.
status_orient()
RangeFinder::Status RangeFinder::status_orient (enum Rotation orientation) const
Definition at line 624 of file AP_RangeFinder.cpp.
Referenced by AP_OSD_Screen::draw_rngf().
update()
void RangeFinder::update (void)
Definition at line 232 of file AP_RangeFinder.cpp.
Referenced by loop().
Friends And Related Symbol Documentation
AP_RangeFinder_Backend
friend class AP_RangeFinder_Backend friend
Definition at line 48 of file AP_RangeFinder.h.
AP_RangeFinder_DroneCAN
friend class AP_RangeFinder_DroneCAN friend
Definition at line 50 of file AP_RangeFinder.h.
Member Data Documentation
_log_rfnd_bit
uint32_t RangeFinder::_log_rfnd_bit = -1 private
Definition at line 309 of file AP_RangeFinder.h.
Referenced by set_log_rfnd_bit().
_singleton
RangeFinder * RangeFinder::_singleton static private
Definition at line 296 of file AP_RangeFinder.h.
Referenced by get_singleton(), and RangeFinder().
backend_var_info
const AP_Param::GroupInfo * RangeFinder::backend_var_info static
Definition at line 212 of file AP_RangeFinder.h.
Referenced by detect_instance().
detect_sem
HAL_Semaphore RangeFinder::detect_sem private
Definition at line 301 of file AP_RangeFinder.h.
Referenced by init().
drivers
AP_RangeFinder_Backend* RangeFinder::drivers[RANGEFINDER_MAX_INSTANCES] private
Definition at line 299 of file AP_RangeFinder.h.
Referenced by _add_backend(), detect_instance(), get_backend(), handle_msg(), init(), prearm_healthy(), and update().
estimated_terrain_height
float RangeFinder::estimated_terrain_height private
Definition at line 302 of file AP_RangeFinder.h.
Referenced by detect_instance(), and set_estimated_terrain_height().
num_instances
uint8_t RangeFinder::num_instances private
Definition at line 300 of file AP_RangeFinder.h.
Referenced by _add_backend(), detect_instance(), find_instance(), get_backend(), handle_msg(), init(), num_sensors(), and update().
params
AP_RangeFinder_Params RangeFinder::params[RANGEFINDER_MAX_INSTANCES] protected
Definition at line 293 of file AP_RangeFinder.h.
Referenced by detect_instance(), get_address(), get_type(), handle_msg(), init(), prearm_healthy(), and update().
pos_offset_zero
Vector3f RangeFinder::pos_offset_zero private
Definition at line 303 of file AP_RangeFinder.h.
Referenced by get_pos_offset_orient().
SIGNAL_QUALITY_MAX
constexpr int8_t RangeFinder::SIGNAL_QUALITY_MAX = 100 static constexpr
Definition at line 197 of file AP_RangeFinder.h.
Referenced by AP_RangeFinder_LightWareSerial::get_signal_quality_pct().
SIGNAL_QUALITY_MIN
constexpr int8_t RangeFinder::SIGNAL_QUALITY_MIN = 0 static constexpr
Definition at line 196 of file AP_RangeFinder.h.
Referenced by AP_RangeFinder_LightWareSerial::get_signal_quality_pct().
SIGNAL_QUALITY_UNKNOWN
constexpr int8_t RangeFinder::SIGNAL_QUALITY_UNKNOWN = -1 static constexpr
Definition at line 198 of file AP_RangeFinder.h.
Referenced by AP_RangeFinder_BLPing::get_signal_quality_pct(), AP_RangeFinder_Backend_Serial::get_signal_quality_pct(), init(), and signal_quality_pct_orient().
state
RangeFinder_State RangeFinder::state[RANGEFINDER_MAX_INSTANCES] private
Definition at line 298 of file AP_RangeFinder.h.
Referenced by detect_instance(), init(), and update().
var_info
const AP_Param::GroupInfo RangeFinder::var_info static
Definition at line 73 of file AP_RangeFinder.h.
Referenced by setup().
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder.h
libraries/AP_RangeFinder/AP_RangeFinder.cpp