APM:Libraries: AP_OpticalFlow_PX4Flow Class Reference
AP_OpticalFlow_PX4Flow Class Reference
#include <AP_OpticalFlow_PX4Flow.h>
Classes
struct i2c_integral_frame
Public Member Functions
CLASS_NO_COPY (AP_OpticalFlow_PX4Flow)
void init () override
void update (void) override
OpticalFlow_backend (AP_OpticalFlow &_frontend)
constructor
Public Member Functions inherited from OpticalFlow_backend
OpticalFlow_backend (AP_OpticalFlow &_frontend)
virtual ~OpticalFlow_backend (void)
CLASS_NO_COPY (OpticalFlow_backend)
virtual void handle_msg (const mavlink_message_t &msg)
Static Public Member Functions
static AP_OpticalFlow_PX4Flow * detect (AP_OpticalFlow &_frontend)
Private Member Functions
bool scan_buses (void)
bool setup_sensor (void)
void timer (void)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > dev
Static Private Attributes
static const uint8_t REG_INTEGRAL_FRAME = 0x16
Additional Inherited Members
Protected Member Functions inherited from OpticalFlow_backend
void _update_frontend (const struct AP_OpticalFlow::OpticalFlow_state &state)
Vector2f _flowScaler (void) const
float _yawAngleRad (void) const
void _applyYaw (Vector2f &v)
uint8_t get_address (void) const
Protected Attributes inherited from OpticalFlow_backend
AP_OpticalFlow & frontend
HAL_Semaphore _sem
Detailed Description
Definition at line 10 of file AP_OpticalFlow_PX4Flow.h.
Member Function Documentation
CLASS_NO_COPY()
AP_OpticalFlow_PX4Flow::CLASS_NO_COPY (AP_OpticalFlow_PX4Flow)
detect()
AP_OpticalFlow_PX4Flow * AP_OpticalFlow_PX4Flow::detect (AP_OpticalFlow & _frontend) static
Definition at line 41 of file AP_OpticalFlow_PX4Flow.cpp.
Referenced by AP_OpticalFlow::init().
init()
void AP_OpticalFlow_PX4Flow::init (void) inline override virtual
Reimplemented from OpticalFlow_backend.
Definition at line 19 of file AP_OpticalFlow_PX4Flow.h.
OpticalFlow_backend()
OpticalFlow_backend::OpticalFlow_backend (AP_OpticalFlow & _frontend)
constructor
Definition at line 31 of file AP_OpticalFlow_Backend.cpp.
scan_buses()
bool AP_OpticalFlow_PX4Flow::scan_buses (void) private
Definition at line 57 of file AP_OpticalFlow_PX4Flow.cpp.
Referenced by setup_sensor().
setup_sensor()
bool AP_OpticalFlow_PX4Flow::setup_sensor (void) private
Definition at line 95 of file AP_OpticalFlow_PX4Flow.cpp.
Referenced by detect().
timer()
void AP_OpticalFlow_PX4Flow::timer (void) private
Definition at line 112 of file AP_OpticalFlow_PX4Flow.cpp.
Referenced by setup_sensor().
update()
void AP_OpticalFlow_PX4Flow::update (void) override virtual
Implements OpticalFlow_backend.
Definition at line 107 of file AP_OpticalFlow_PX4Flow.cpp.
Member Data Documentation
dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_OpticalFlow_PX4Flow::dev private
Definition at line 28 of file AP_OpticalFlow_PX4Flow.h.
Referenced by scan_buses(), setup_sensor(), and timer().
REG_INTEGRAL_FRAME
const uint8_t AP_OpticalFlow_PX4Flow::REG_INTEGRAL_FRAME = 0x16 static private
Definition at line 30 of file AP_OpticalFlow_PX4Flow.h.
Referenced by scan_buses(), and timer().
The documentation for this class was generated from the following files:
libraries/AP_OpticalFlow/AP_OpticalFlow_PX4Flow.h
libraries/AP_OpticalFlow/AP_OpticalFlow_PX4Flow.cpp