APM:Libraries: Linux::Util Class Reference
Linux::Util Class Reference
#include <Util.h>
Public Member Functions
void init (int argc, char *const *argv)
bool run_debug_shell (AP_HAL::BetterStream *stream) override
void commandline_arguments (uint8_t &argc, char *const *&argv) override
void set_hw_rtc (uint64_t time_utc_usec) override
uint64_t get_hw_rtc () const override
const char * get_custom_log_directory () const override final
const char * get_custom_terrain_directory () const override final
const char * get_custom_storage_directory () const override final
void set_custom_log_directory (const char *_custom_log_directory)
void set_custom_terrain_directory (const char *_custom_terrain_directory)
void set_custom_storage_directory (const char *_custom_storage_directory)
void set_custom_defaults_path (const char *_custom_defaults)
const char * get_custom_defaults_file () const override final
bool parse_cpu_set (const char *s, cpu_set_t *cpu_set) const
bool is_chardev_node (const char *path)
void set_imu_temp (float current) override
void set_imu_target_temp (int8_t *target) override
uint32_t available_memory (void) override
bool get_system_id (char buf[50]) override
bool get_system_id_unformatted (uint8_t buf[], uint8_t &len) override
int write_file (const char *path, const char *fmt,...) FMT_PRINTF(3
int int read_file (const char *path, const char *fmt,...) FMT_SCANF(3
int int int get_hw_arm32 ()
bool toneAlarm_init (uint8_t types) override
void toneAlarm_set_buzzer_tone (float frequency, float volume, uint32_t duration_ms) override
bool get_random_vals (uint8_t *data, size_t size) override
Public Member Functions inherited from AP_HAL::Util
int snprintf (char *str, size_t size, const char *format,...) FMT_PRINTF(4
int int vsnprintf (char *str, size_t size, const char *format, va_list ap)
virtual void set_soft_armed (const bool b)
bool get_soft_armed () const
uint32_t get_last_armed_change () const
virtual bool was_watchdog_reset () const
bool was_watchdog_safety_off () const
bool was_watchdog_armed () const
virtual void set_cmdline_parameters ()
virtual enum safety_state safety_switch_state (void)
virtual FlashBootloader flash_bootloader ()
virtual AP_HAL::BetterStream * get_shell_stream ()
virtual void * malloc_type (size_t size, Memory_Type mem_type)
virtual void free_type (void *ptr, size_t size, Memory_Type mem_type)
virtual bool trap () const
virtual void thread_info (ExpandingString &str)
virtual void dma_info (ExpandingString &str)
virtual void mem_info (ExpandingString &str)
virtual bool load_persistent_params (ExpandingString &str) const
virtual bool get_persistent_param_by_name (const char *name, char *value, size_t &len) const
virtual void timer_info (ExpandingString &str)
virtual bool get_true_random_vals (uint8_t *data, size_t size, uint32_t timeout_us)
virtual void log_stack_info (void)
Static Public Member Functions
static Util * from (AP_HAL::Util *util)
Private Attributes
int saved_argc
Heat * _heat
char *const * saved_argv
const char * custom_log_directory = nullptr
const char * custom_terrain_directory = nullptr
const char * custom_storage_directory = nullptr
const char * custom_defaults = HAL_PARAM_DEFAULTS_PATH
Static Private Attributes
static ToneAlarm_Disco _toneAlarm
static const char * _hw_names [UTIL_NUM_HARDWARES]
Additional Inherited Members
Public Types inherited from AP_HAL::Util
enum safety_state : uint8_t { SAFETY_NONE , SAFETY_DISARMED , SAFETY_ARMED }
enum class FlashBootloader {
OK =0 , NO_CHANGE =1 , FAIL =2 , NOT_AVAILABLE =3 ,
NOT_SIGNED =4
}
enum Memory_Type { MEM_DMA_SAFE , MEM_FAST , MEM_FILESYSTEM }
Public Attributes inherited from AP_HAL::Util
struct PersistentData persistent_data
struct PersistentData last_persistent_data
Protected Attributes inherited from AP_HAL::Util
bool soft_armed = false
uint32_t last_armed_change_ms
Detailed Description
Definition at line 25 of file Util.h.
Member Function Documentation
available_memory()
uint32_t Linux::Util::available_memory (void) override virtual
how much free memory do we have in bytes. If unknown return 4096
Reimplemented from AP_HAL::Util.
commandline_arguments()
void Linux::Util::commandline_arguments (uint8_t & argc, char *const *& argv) override virtual
return commandline arguments, if available
Reimplemented from AP_HAL::Util.
from()
static Util * Linux::Util::from (AP_HAL::Util * util) inline static
Definition at line 27 of file Util.h.
Referenced by Linux::GPIO_Sysfs::_pinMode(), Linux::RCOutput_Bebop::_run_rcout(), Linux::PWM_Sysfs_Base::enable(), Linux::PWM_Sysfs_Base::get_period(), Linux::PWM_Sysfs_Base::get_polarity(), Linux::Led_Sysfs::init(), Linux::PWM_Sysfs_Base::init(), Linux::PWM_Sysfs_Base::is_enabled(), Linux::PWM_Sysfs_Base::set_period(), and Linux::PWM_Sysfs_Base::set_polarity().
get_custom_defaults_file()
const char * Linux::Util::get_custom_defaults_file () const inline final override virtual
Reimplemented from AP_HAL::Util.
Definition at line 59 of file Util.h.
get_custom_log_directory()
const char * Linux::Util::get_custom_log_directory () const inline final override virtual
Reimplemented from AP_HAL::Util.
Definition at line 45 of file Util.h.
get_custom_storage_directory()
const char * Linux::Util::get_custom_storage_directory () const inline final override virtual
Reimplemented from AP_HAL::Util.
Definition at line 47 of file Util.h.
get_custom_terrain_directory()
const char * Linux::Util::get_custom_terrain_directory () const inline final override virtual
Reimplemented from AP_HAL::Util.
Definition at line 46 of file Util.h.
get_hw_arm32()
int Util::get_hw_arm32 ()
Definition at line 220 of file Util.cpp.
Referenced by Linux::RCOutput_Bebop::_run_rcout().
get_hw_rtc()
uint64_t Linux::Util::get_hw_rtc () const override virtual
Implements AP_HAL::Util.
get_random_vals()
bool Linux::Util::get_random_vals (uint8_t * data, size_t size) override virtual
Reimplemented from AP_HAL::Util.
get_system_id()
bool Linux::Util::get_system_id (char buf[50]) override virtual
Reimplemented from AP_HAL::Util.
get_system_id_unformatted()
bool Linux::Util::get_system_id_unformatted (uint8_t buf[], uint8_t & len) override virtual
Reimplemented from AP_HAL::Util.
init()
void Linux::Util::init (int argc, char *const * argv)
is_chardev_node()
bool Util::is_chardev_node (const char * path)
Definition at line 85 of file Util.cpp.
parse_cpu_set()
bool Util::parse_cpu_set (const char * s, cpu_set_t * cpu_set) const
Definition at line 322 of file Util.cpp.
read_file()
int Util::read_file (const char * path, const char * fmt, ...)
Definition at line 185 of file Util.cpp.
Referenced by Linux::PWM_Sysfs_Base::get_period(), Linux::PWM_Sysfs_Base::get_polarity(), Linux::Led_Sysfs::init(), and Linux::PWM_Sysfs_Base::is_enabled().
run_debug_shell()
bool Linux::Util::run_debug_shell (AP_HAL::BetterStream * stream) inline override virtual
Implements AP_HAL::Util.
Definition at line 32 of file Util.h.
set_custom_defaults_path()
void Linux::Util::set_custom_defaults_path (const char * _custom_defaults) inline
Definition at line 54 of file Util.h.
set_custom_log_directory()
void Linux::Util::set_custom_log_directory (const char * _custom_log_directory) inline
Definition at line 49 of file Util.h.
set_custom_storage_directory()
void Linux::Util::set_custom_storage_directory (const char * _custom_storage_directory) inline
Definition at line 51 of file Util.h.
set_custom_terrain_directory()
void Linux::Util::set_custom_terrain_directory (const char * _custom_terrain_directory) inline
Definition at line 50 of file Util.h.
set_hw_rtc()
void Linux::Util::set_hw_rtc (uint64_t time_utc_usec) override virtual
Implements AP_HAL::Util.
set_imu_target_temp()
void Util::set_imu_target_temp (int8_t * target) override virtual
Reimplemented from AP_HAL::Util.
Definition at line 51 of file Util.cpp.
set_imu_temp()
void Util::set_imu_temp (float current) override virtual
Reimplemented from AP_HAL::Util.
Definition at line 45 of file Util.cpp.
toneAlarm_init()
bool Util::toneAlarm_init (uint8_t types) inline override virtual
Reimplemented from AP_HAL::Util.
Definition at line 97 of file Util.h.
toneAlarm_set_buzzer_tone()
void Util::toneAlarm_set_buzzer_tone (float frequency, float volume, uint32_t duration_ms) inline override virtual
Reimplemented from AP_HAL::Util.
Definition at line 98 of file Util.h.
write_file()
int Util::write_file (const char * path, const char * fmt, ...)
Definition at line 160 of file Util.cpp.
Referenced by Linux::GPIO_Sysfs::_pinMode(), Linux::PWM_Sysfs_Base::enable(), Linux::PWM_Sysfs_Base::init(), Linux::PWM_Sysfs_Base::set_period(), and Linux::PWM_Sysfs_Base::set_polarity().
Member Data Documentation
_heat
Heat* Linux::Util::_heat private
Definition at line 112 of file Util.h.
_hw_names
const char * Util::_hw_names static private
Initial value:
= {
    [UTIL_HARDWARE_RPI1]   = "BCM2708",
    [UTIL_HARDWARE_RPI2]   = "BCM2709",
    [UTIL_HARDWARE_RPI4]   = "BCM2711",
    [UTIL_HARDWARE_BEBOP]  = "Mykonos3 board",
    [UTIL_HARDWARE_BEBOP2] = "Milos board",
    [UTIL_HARDWARE_DISCO]  = "Evinrude board",
}
Definition at line 210 of file Util.h.
_toneAlarm
ToneAlarm_Disco Util::_toneAlarm static private
Definition at line 107 of file Util.h.
Referenced by toneAlarm_init(), and toneAlarm_set_buzzer_tone().
custom_defaults
const char* Linux::Util::custom_defaults = HAL_PARAM_DEFAULTS_PATH private
Definition at line 117 of file Util.h.
Referenced by get_custom_defaults_file(), and set_custom_defaults_path().
custom_log_directory
const char* Linux::Util::custom_log_directory = nullptr private
Definition at line 114 of file Util.h.
Referenced by get_custom_log_directory(), and set_custom_log_directory().
custom_storage_directory
const char* Linux::Util::custom_storage_directory = nullptr private
Definition at line 116 of file Util.h.
Referenced by get_custom_storage_directory(), and set_custom_storage_directory().
custom_terrain_directory
const char* Linux::Util::custom_terrain_directory = nullptr private
Definition at line 115 of file Util.h.
Referenced by get_custom_terrain_directory(), and set_custom_terrain_directory().
saved_argc
int Linux::Util::saved_argc private
Definition at line 111 of file Util.h.
saved_argv
char* const* Linux::Util::saved_argv private
Definition at line 113 of file Util.h.
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Util.h
libraries/AP_HAL_ChibiOS/Util.cpp
libraries/AP_HAL_Linux/Util.cpp