APM:Libraries: input< Iter > Class Template Reference
input< Iter > Class Template Reference
Public Member Functions
input (const Iter &first, const Iter &last)
int getc ()
void ungetc ()
Iter cur () const
int line () const
void skip_ws ()
bool expect (const int expected)
bool match (const std::string &pattern)
Protected Attributes
Iter cur_
Iter end_
bool consumed_
int line_
Detailed Description
template<typename Iter>
class input< Iter >
Definition at line 394 of file AP_JSON.cpp.
Constructor & Destructor Documentation
input()
template<typename Iter > input< Iter >::input (const Iter & first, const Iter & last) inline
Definition at line 402 of file AP_JSON.cpp.
Member Function Documentation
cur()
template<typename Iter > Iter input< Iter >::cur () const inline
Definition at line 424 of file AP_JSON.cpp.
Referenced by _parse().
expect()
template<typename Iter > bool input< Iter >::expect (const int expected) inline
Definition at line 447 of file AP_JSON.cpp.
Referenced by _parse_array(), and _parse_object().
getc()
template<typename Iter > int input< Iter >::getc () inline
Definition at line 405 of file AP_JSON.cpp.
Referenced by _parse(), _parse(), _parse_number(), _parse_quadhex(), and _parse_string().
line()
template<typename Iter > int input< Iter >::line () const inline
Definition at line 433 of file AP_JSON.cpp.
Referenced by _parse().
match()
template<typename Iter > bool input< Iter >::match (const std::string & pattern) inline
Definition at line 456 of file AP_JSON.cpp.
skip_ws()
template<typename Iter > void input< Iter >::skip_ws () inline
Definition at line 437 of file AP_JSON.cpp.
Referenced by _parse().
ungetc()
template<typename Iter > void input< Iter >::ungetc () inline
Definition at line 420 of file AP_JSON.cpp.
Referenced by _parse(), _parse_number(), _parse_quadhex(), and _parse_string().
Member Data Documentation
consumed_
template<typename Iter > bool input< Iter >::consumed_ protected
Definition at line 398 of file AP_JSON.cpp.
Referenced by input< Iter >::cur().
cur_
template<typename Iter > Iter input< Iter >::cur_ protected
Definition at line 397 of file AP_JSON.cpp.
Referenced by input< Iter >::cur().
end_
template<typename Iter > Iter input< Iter >::end_ protected
Definition at line 397 of file AP_JSON.cpp.
line_
template<typename Iter > int input< Iter >::line_ protected
Definition at line 399 of file AP_JSON.cpp.
The documentation for this class was generated from the following file:
libraries/AP_JSON/AP_JSON.cpp