APM:Libraries: Matrix3< T > Class Template Reference
Matrix3< T > Class Template Reference
#include <matrix3.h>
Public Member Functions
constexpr Matrix3 ()
constexpr Matrix3 (const Vector3< T > &a0, const Vector3< T > &b0, const Vector3< T > &c0)
constexpr Matrix3 (const T ax, const T ay, const T az, const T bx, const T by, const T bz, const T cx, const T cy, const T cz)
void operator() (const Vector3< T > &a0, const Vector3< T > &b0, const Vector3< T > &c0)
bool operator== (const Matrix3< T > &m)
bool operator!= (const Matrix3< T > &m)
Matrix3< T > operator- (void) const
Matrix3< T > operator+ (const Matrix3< T > &m) const
Matrix3< T > & operator+= (const Matrix3< T > &m)
Matrix3< T > operator- (const Matrix3< T > &m) const
Matrix3< T > & operator-= (const Matrix3< T > &m)
Matrix3< T > operator* (const T num) const
Matrix3< T > & operator*= (const T num)
Matrix3< T > operator/ (const T num) const
Matrix3< T > & operator/= (const T num)
Vector3< T > & operator[] (uint8_t i)
const Vector3< T > & operator[] (uint8_t i) const
Vector3< T > operator* (const Vector3< T > &v) const
Vector3< T > mul_transpose (const Vector3< T > &v) const
Vector2< T > mulXY (const Vector3< T > &v) const
Vector3< T > colx (void) const
Vector3< T > coly (void) const
Vector3< T > colz (void) const
Matrix3< T > operator* (const Matrix3< T > &m) const
Matrix3< T > & operator*= (const Matrix3< T > &m)
Matrix3< T > transposed (void) const
void transpose (void)
T det () const
bool inverse (Matrix3< T > &inv) const WARN_IF_UNUSED
bool invert () WARN_IF_UNUSED
void zero (void)
void identity (void)
bool is_nan (void) WARN_IF_UNUSED
void from_euler (T roll, T pitch, T yaw)
void to_euler (T *roll, T *pitch, T *yaw) const
void from_rotation (enum Rotation rotation)
Vector3< T > to_euler312 () const
void from_euler312 (T roll, T pitch, T yaw)
void rotate (const Vector3< T > &g)
void from_axis_angle (const Vector3< T > &v, T theta)
void normalize (void)
Matrix3< double > todouble (void) const
Matrix3< float > tofloat (void) const
Public Attributes
Vector3< T > a
Vector3< T > b
Vector3< T > c
Detailed Description
template<typename T>
class Matrix3< T >
Definition at line 50 of file matrix3.h.
Constructor & Destructor Documentation
Matrix3() [1/3]
template<typename T > constexpr Matrix3< T >::Matrix3 () inline constexpr
Definition at line 58 of file matrix3.h.
Matrix3() [2/3]
template<typename T > constexpr Matrix3< T >::Matrix3 (const Vector3< T > & a0, const Vector3< T > & b0, const Vector3< T > & c0) inline constexpr
Definition at line 61 of file matrix3.h.
Matrix3() [3/3]
template<typename T > constexpr Matrix3< T >::Matrix3 (const T ax, const T ay, const T az, const T bx, const T by, const T bz, const T cx, const T cy, const T cz) inline constexpr
Definition at line 67 of file matrix3.h.
Member Function Documentation
colx()
template<typename T > Vector3< T > Matrix3< T >::colx (void) const inline
Definition at line 163 of file matrix3.h.
Referenced by Vector3< T >::row_times_mat().
coly()
template<typename T > Vector3< T > Matrix3< T >::coly (void) const inline
Definition at line 169 of file matrix3.h.
Referenced by Vector3< T >::row_times_mat().
colz()
template<typename T > Vector3< T > Matrix3< T >::colz (void) const inline
Definition at line 175 of file matrix3.h.
Referenced by Vector3< T >::row_times_mat().
det()
template<typename T > T Matrix3< T >::det () const
Calculate the determinant of this matrix.
Returns
The value of the determinant.
Definition at line 190 of file matrix3.cpp.
from_axis_angle()
template<typename T > void Matrix3< T >::from_axis_angle (const Vector3< T > & v, T theta)
Definition at line 241 of file matrix3.cpp.
Referenced by SITL::Calibration::_calibration_poses(), and test_rotation_accuracy().
from_euler()
template<typename T > void Matrix3< T >::from_euler (T roll, T pitch, T yaw)
Definition at line 26 of file matrix3.cpp.
Referenced by EKFGSF_yaw::alignYaw(), AP_AHRS::AP_AHRS(), AP_AHRS_View::AP_AHRS_View(), NavEKF2_core::calcQuatAndFieldStates(), SITL::Motor::calculate_forces(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), AP_Declination::get_earth_field_ga(), AP_CustomRotation::init(), loop(), missing_rotations(), AP_AHRS_View::set_pitch_trim(), NavEKF3_core::setYawFromMag(), test_conversion(), test_euler(), test_euler(), test_euler(), test_frame_transforms(), test_quaternion(), test_rotation_accuracy(), SITL::Sailboat::update(), AP_AHRS::update_trim_rotation_matrices(), and SITL::Vicon::update_vicon_position_estimate().
from_euler312()
template<typename T > void Matrix3< T >::from_euler312 (T roll, T pitch, T yaw)
Definition at line 92 of file matrix3.cpp.
Referenced by EKFGSF_yaw::alignYaw(), QuaternionT< T >::from_vector312(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), and NavEKF3_core::setYawFromMag().
from_rotation()
template<typename T > void Matrix3< T >::from_rotation (enum Rotation rotation)
Definition at line 63 of file matrix3.cpp.
Referenced by TEST(), and test_rotate_matrix().
identity()
template<typename T > void Matrix3< T >::identity (void) inline
Definition at line 225 of file matrix3.h.
Referenced by test_matrix_rotate().
inverse()
template<typename T > bool Matrix3< T >::inverse (Matrix3< T > & inv) const
Calculate the inverse of this matrix.
Parameters
inv[in] Where to store the result.
Returns
If this matrix is invertible, then true is returned. Otherwise, inv is unmodified and false is returned.
Definition at line 198 of file matrix3.cpp.
invert()
template<typename T > bool Matrix3< T >::invert ()
Invert this matrix if it is invertible.
Returns
Return true if this matrix could be successfully inverted and false otherwise.
Definition at line 220 of file matrix3.cpp.
is_nan()
template<typename T > bool Matrix3< T >::is_nan (void) inline
Definition at line 233 of file matrix3.h.
Referenced by test_conversion().
mul_transpose()
template<typename T > Vector3< T > Matrix3< T >::mul_transpose (const Vector3< T > & v) const
Definition at line 158 of file matrix3.cpp.
Referenced by NavEKF3_core::CorrectExtNavForSensorOffset(), NavEKF2_core::CorrectExtNavForSensorOffset(), NavEKF2_core::CorrectGPSForAntennaOffset(), NavEKF3_core::CorrectGPSForAntennaOffset(), AP_AHRS::earth_to_body(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), get_vel_correction_for_sensor_offset(), QuaternionT< T >::roll_pitch_difference(), Vector3< T >::rotate_inverse(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), AC_PrecLand_SITL::update(), AP_IRLock_SITL::update(), AP_AHRS::update_AOA_SSA(), NavEKF2_core::UpdateStrapdownEquationsNED(), and NavEKF3_core::UpdateStrapdownEquationsNED().
mulXY()
template<typename T > Vector2< T > Matrix3< T >::mulXY (const Vector3< T > & v) const
Definition at line 150 of file matrix3.cpp.
normalize()
template<typename T > void Matrix3< T >::normalize (void)
Definition at line 128 of file matrix3.cpp.
Referenced by SITL::Gimbal::update().
operator!=()
template<typename T > bool Matrix3< T >::operator!= (const Matrix3< T > & m) inline
Definition at line 87 of file matrix3.h.
operator()()
template<typename T > void Matrix3< T >::operator() (const Vector3< T > & a0, const Vector3< T > & b0, const Vector3< T > & c0) inline
Definition at line 75 of file matrix3.h.
operator*() [1/3]
template<typename T > Matrix3< T > Matrix3< T >::operator* (const Matrix3< T > & m) const
Definition at line 167 of file matrix3.cpp.
operator*() [2/3]
template<typename T > Matrix3< T > Matrix3< T >::operator* (const T num) const inline
Definition at line 119 of file matrix3.h.
operator*() [3/3]
template<typename T > Vector3< T > Matrix3< T >::operator* (const Vector3< T > & v) const
Definition at line 141 of file matrix3.cpp.
operator*=() [1/2]
template<typename T > Matrix3< T > & Matrix3< T >::operator*= (const Matrix3< T > & m) inline
Definition at line 183 of file matrix3.h.
operator*=() [2/2]
template<typename T > Matrix3< T > & Matrix3< T >::operator*= (const T num) inline
Definition at line 123 of file matrix3.h.
operator+()
template<typename T > Matrix3< T > Matrix3< T >::operator+ (const Matrix3< T > & m) const inline
Definition at line 99 of file matrix3.h.
operator+=()
template<typename T > Matrix3< T > & Matrix3< T >::operator+= (const Matrix3< T > & m) inline
Definition at line 103 of file matrix3.h.
operator-() [1/2]
template<typename T > Matrix3< T > Matrix3< T >::operator- (const Matrix3< T > & m) const inline
Definition at line 109 of file matrix3.h.
operator-() [2/2]
template<typename T > Matrix3< T > Matrix3< T >::operator- (void) const inline
Definition at line 93 of file matrix3.h.
operator-=()
template<typename T > Matrix3< T > & Matrix3< T >::operator-= (const Matrix3< T > & m) inline
Definition at line 113 of file matrix3.h.
operator/()
template<typename T > Matrix3< T > Matrix3< T >::operator/ (const T num) const inline
Definition at line 127 of file matrix3.h.
operator/=()
template<typename T > Matrix3< T > & Matrix3< T >::operator/= (const T num) inline
Definition at line 131 of file matrix3.h.
operator==()
template<typename T > bool Matrix3< T >::operator== (const Matrix3< T > & m) inline
Definition at line 81 of file matrix3.h.
operator[]() [1/2]
template<typename T > Vector3< T > & Matrix3< T >::operator[] (uint8_t i) inline
Definition at line 137 of file matrix3.h.
operator[]() [2/2]
template<typename T > const Vector3< T > & Matrix3< T >::operator[] (uint8_t i) const inline
Definition at line 145 of file matrix3.h.
rotate()
template<typename T > void Matrix3< T >::rotate (const Vector3< T > & g)
Definition at line 115 of file matrix3.cpp.
Referenced by AP_GPS_Backend::calculate_moving_base_yaw(), test_matrix_rotate(), test_rotation_accuracy(), and SITL::Gimbal::update().
to_euler()
template<typename T > void Matrix3< T >::to_euler (T * roll, T * pitch, T * yaw) const
Definition at line 49 of file matrix3.cpp.
Referenced by EKFGSF_yaw::alignYaw(), AP_AHRS::calc_trig(), test_conversion(), test_euler(), test_quaternion(), test_rotation_accuracy(), and AP_AHRS_View::update().
to_euler312()
template<typename T > Vector3< T > Matrix3< T >::to_euler312 () const
Definition at line 81 of file matrix3.cpp.
Referenced by EKFGSF_yaw::alignYaw(), QuaternionT< T >::to_vector312(), and SITL::Gimbal::update().
todouble()
template<typename T > Matrix3< double > Matrix3< T >::todouble (void) const inline
Definition at line 275 of file matrix3.h.
Referenced by AC_PrecLand_SITL::update(), and AP_IRLock_SITL::update().
tofloat()
template<typename T > Matrix3< float > Matrix3< T >::tofloat (void) const inline
Definition at line 278 of file matrix3.h.
Referenced by AP_CustomRotations::rotate(), and SITL::Vicon::update_vicon_position_estimate().
transpose()
template<typename T > void Matrix3< T >::transpose (void) inline
Definition at line 191 of file matrix3.h.
Referenced by AP_AHRS_View::AP_AHRS_View(), and AP_AHRS_View::set_pitch_trim().
transposed()
template<typename T > Matrix3< T > Matrix3< T >::transposed (void) const
Definition at line 182 of file matrix3.cpp.
Referenced by SITL::Calibration::_calibration_poses(), AP_AHRS::AP_AHRS(), NavEKF3_core::CovariancePrediction(), have_rotation(), NavEKF3_core::learnMagBiasFromGPS(), NavEKF3_core::resetMagFieldStates(), NavEKF2_core::resetQuatStateYawOnly(), TEST(), Matrix3< T >::transpose(), SITL::Gimbal::update(), and AP_AHRS::update_trim_rotation_matrices().
zero()
template<typename T > void Matrix3< T >::zero (void)
Definition at line 231 of file matrix3.cpp.
Referenced by NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), and AP_GPS::position_covariance().
Member Data Documentation
a
template<typename T > Vector3<T> Matrix3< T >::a
Definition at line 54 of file matrix3.h.
Referenced by AP_TECS::_update_throttle_with_airspeed(), AP_TECS::_update_throttle_without_airspeed(), AP_AHRS::calc_trig(), Matrix3< T >::colx(), Matrix3< T >::coly(), Matrix3< T >::colz(), NavEKF3_core::CovariancePrediction(), QuaternionT< float >::from_euler(), NavEKF3_core::FuseVelPosNED(), Matrix3< T >::identity(), Matrix3< T >::is_nan(), Matrix3< T >::operator!=(), Matrix3< T >::operator()(), Matrix3< T >::operator*(), Matrix3< T >::operator*(), Matrix3< T >::operator+(), Matrix3< T >::operator-(), Matrix3< T >::operator-(), Matrix3< T >::operator/(), operator<<(), Matrix3< T >::operator==(), Matrix3< T >::operator[](), Matrix3< T >::operator[](), QuaternionT< T >::rotation_matrix(), TEST(), TEST(), test_matrix_rotate(), Matrix3< T >::todouble(), Matrix3< T >::tofloat(), and Airspeed_Calibration::update().
b
template<typename T > Vector3<T> Matrix3< T >::b
Definition at line 54 of file matrix3.h.
Referenced by AP_TECS::_update_throttle_with_airspeed(), AP_TECS::_update_throttle_without_airspeed(), AP_AHRS::calc_trig(), Matrix3< T >::colx(), Matrix3< T >::coly(), Matrix3< T >::colz(), NavEKF3_core::CovariancePrediction(), QuaternionT< float >::from_euler(), NavEKF3_core::FuseVelPosNED(), Matrix3< T >::identity(), Matrix3< T >::is_nan(), Matrix3< T >::operator!=(), Matrix3< T >::operator()(), Matrix3< T >::operator*(), Matrix3< T >::operator*(), Matrix3< T >::operator+(), Matrix3< T >::operator-(), Matrix3< T >::operator-(), Matrix3< T >::operator/(), operator<<(), Matrix3< T >::operator==(), QuaternionT< T >::rotation_matrix(), TEST(), TEST(), test_matrix_rotate(), Matrix3< T >::todouble(), Matrix3< T >::tofloat(), and Airspeed_Calibration::update().
c
template<typename T > Vector3<T> Matrix3< T >::c
Definition at line 54 of file matrix3.h.
Referenced by AP_TECS::_update_speed(), AP_AHRS::calc_trig(), NavEKF3_core::calcOutputStates(), Compass::calculate_heading(), Matrix3< T >::colx(), Matrix3< T >::coly(), Matrix3< T >::colz(), NavEKF3_core::CovariancePrediction(), NavEKF2_core::EstimateTerrainOffset(), NavEKF3_core::EstimateTerrainOffset(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), NavEKF3_core::FuseVelPosNED(), AP_AHRS::get_yaw_rate_earth(), Matrix3< T >::identity(), Matrix3< T >::is_nan(), Matrix3< T >::operator!=(), Matrix3< T >::operator()(), Matrix3< T >::operator*(), Matrix3< T >::operator*(), Matrix3< T >::operator+(), Matrix3< T >::operator-(), Matrix3< T >::operator-(), Matrix3< T >::operator/(), operator<<(), Matrix3< T >::operator==(), QuaternionT< T >::rotation_matrix(), NavEKF2_core::SelectFlowFusion(), NavEKF3_core::SelectFlowFusion(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), TEST(), TEST(), test_matrix_rotate(), Matrix3< T >::todouble(), Matrix3< T >::tofloat(), Variometer::update(), and Airspeed_Calibration::update().
The documentation for this class was generated from the following files:
libraries/AP_Math/matrix3.h
libraries/AP_Math/matrix3.cpp