APM:Libraries: AP_FlashIface_JEDEC Class Reference
AP_FlashIface_JEDEC Class Reference
#include <AP_FlashIface_JEDEC.h>
Classes
struct device_desc
Public Member Functions
bool init () override
bool read (uint32_t offset, uint8_t *data, uint32_t size) override
uint32_t get_page_size () const override
uint32_t get_page_count () const override
bool start_program_page (uint32_t page, const uint8_t *data, uint32_t &delay_us, uint32_t &timeout_us) override
bool start_program_offset (uint32_t offset, const uint8_t *data, uint32_t size, uint32_t &programming, uint32_t &delay_us, uint32_t &timeout_us) override
bool start_mass_erase (uint32_t &delay_ms, uint32_t &timeout_ms) override
uint32_t get_sector_size () const override
uint32_t get_sector_count () const override
uint32_t min_erase_size () const override
bool start_sector_erase (uint32_t sector, uint32_t &delay_ms, uint32_t &timeout_ms) override
bool start_erase_offset (uint32_t offset, uint32_t size, uint32_t &erasing, uint32_t &delay_ms, uint32_t &timeout_ms) override
bool verify_sector_erase (uint32_t sector) override
bool is_device_busy () override
bool start_xip_mode (void **addr) override
bool stop_xip_mode () override
Protected Types
enum class WSPIMode { NormalSPI , QuadSPI , OctoSPI }
enum xip_entry_methods { XIP_ENTRY_METHOD_1 , XIP_ENTRY_METHOD_2 , XIP_ENTRY_METHOD_3 }
Protected Member Functions
void reset_device ()
bool detect_device ()
bool configure_device ()
bool write_enable ()
bool write_disable ()
void wait_ready ()
bool modify_reg (uint8_t read_ins, uint8_t write_ins, uint8_t mask, uint8_t va_list)
bool read_reg (uint8_t read_ins, uint8_t &read_val)
bool write_reg (uint8_t read_ins, uint8_t write_val)
bool send_cmd (uint8_t ins)
Protected Attributes
enum AP_FlashIface_JEDEC::WSPIMode _wide_spi_mode
AP_HAL::OwnPtr< AP_HAL::WSPIDevice > _dev
struct AP_FlashIface_JEDEC::device_desc _desc
uint8_t _dev_list_idx
bool initialised
bool write_enable_called
Detailed Description
Definition at line 27 of file AP_FlashIface_JEDEC.h.
Member Enumeration Documentation
WSPIMode
enum class AP_FlashIface_JEDEC::WSPIMode strong protected
Enumerator
NormalSPI
QuadSPI
OctoSPI
Definition at line 254 of file AP_FlashIface_JEDEC.h.
xip_entry_methods
enum AP_FlashIface_JEDEC::xip_entry_methods protected
Enumerator
XIP_ENTRY_METHOD_1
XIP_ENTRY_METHOD_2
XIP_ENTRY_METHOD_3
Definition at line 262 of file AP_FlashIface_JEDEC.h.
Member Function Documentation
configure_device()
bool AP_FlashIface_JEDEC::configure_device () protected
Definition at line 483 of file AP_FlashIface_JEDEC.cpp.
Referenced by init().
detect_device()
bool AP_FlashIface_JEDEC::detect_device () protected
Definition at line 202 of file AP_FlashIface_JEDEC.cpp.
Referenced by init().
get_page_count()
uint32_t AP_FlashIface_JEDEC::get_page_count () const inline override virtual
Gets number pages, each page can written in one go
Returns
Number of pages.
Implements AP_FlashIface.
Definition at line 63 of file AP_FlashIface_JEDEC.h.
get_page_size()
uint32_t AP_FlashIface_JEDEC::get_page_size () const inline override virtual
Gets number bytes that can be written in one go (page size).
Returns
page size in bytes.
Implements AP_FlashIface.
Definition at line 52 of file AP_FlashIface_JEDEC.h.
Referenced by test_page_program().
get_sector_count()
uint32_t AP_FlashIface_JEDEC::get_sector_count () const inline override virtual
Gets number of sectors, each sector can be erased in one go
Returns
Number of sectors.
Implements AP_FlashIface.
Definition at line 134 of file AP_FlashIface_JEDEC.h.
get_sector_size()
uint32_t AP_FlashIface_JEDEC::get_sector_size () const inline override virtual
Gets number bytes that can erased in one go(sector size)
Returns
Sector size in bytes.
Implements AP_FlashIface.
Definition at line 123 of file AP_FlashIface_JEDEC.h.
init()
bool AP_FlashIface_JEDEC::init () override virtual
Implements AP_FlashIface.
Definition at line 121 of file AP_FlashIface_JEDEC.cpp.
Referenced by main().
is_device_busy()
bool AP_FlashIface_JEDEC::is_device_busy () override virtual
Check if the device is busy.
Returns
device busy with last op.
Return values
false if the device is ready.
true if the device is busy.
Implements AP_FlashIface.
Definition at line 987 of file AP_FlashIface_JEDEC.cpp.
Referenced by test_mass_erase(), test_page_program(), test_sector_erase(), and wait_ready().
min_erase_size()
uint32_t AP_FlashIface_JEDEC::min_erase_size () const inline override virtual
minimum number of bytes that can be erased
Returns
Number of bytes.
Implements AP_FlashIface.
Definition at line 145 of file AP_FlashIface_JEDEC.h.
modify_reg()
bool AP_FlashIface_JEDEC::modify_reg (uint8_t read_ins, uint8_t write_ins, uint8_t mask, uint8_t va_list) protected
Definition at line 604 of file AP_FlashIface_JEDEC.cpp.
Referenced by start_xip_mode().
read()
bool AP_FlashIface_JEDEC::read (uint32_t offset, uint8_t * data, uint32_t size) override virtual
Read data from flash chip.
Parameters
[in] offset address offset from where to start the read
[out] data data to be read from the device
[in] size size of the data to be read
Returns
The operation status.
Return values
false if the operation failed.
true if the operation succeeded.
Implements AP_FlashIface.
Definition at line 933 of file AP_FlashIface_JEDEC.cpp.
Referenced by test_page_program(), and verify_sector_erase().
read_reg()
bool AP_FlashIface_JEDEC::read_reg (uint8_t read_ins, uint8_t & read_val) protected
Definition at line 624 of file AP_FlashIface_JEDEC.cpp.
Referenced by configure_device(), is_device_busy(), and modify_reg().
reset_device()
void AP_FlashIface_JEDEC::reset_device () protected
Definition at line 171 of file AP_FlashIface_JEDEC.cpp.
Referenced by init().
send_cmd()
bool AP_FlashIface_JEDEC::send_cmd (uint8_t ins) protected
Definition at line 660 of file AP_FlashIface_JEDEC.cpp.
Referenced by write_disable(), and write_enable().
start_erase_offset()
bool AP_FlashIface_JEDEC::start_erase_offset (uint32_t offset, uint32_t size, uint32_t & erasing, uint32_t & delay_ms, uint32_t & timeout_ms) override virtual
Tries to erase as much as possible starting from the offset until size. User needs to call this as many times as needed taking already erased bytes into account, until desired erase has taken place
Parameters
[in] offset address offset for erase
[in] size size desired to be erased
[out] erasing number of bytes erasing
[out] delay_ms Time to wait until next is_device_busy call
[out] timeout_ms Time by which the erase should have timedout
Returns
The operation status.
Return values
false if the operation failed.
true if the operation succeeded.
Reimplemented from AP_FlashIface.
Definition at line 757 of file AP_FlashIface_JEDEC.cpp.
Referenced by start_sector_erase().
start_mass_erase()
bool AP_FlashIface_JEDEC::start_mass_erase (uint32_t & delay_ms, uint32_t & timeout_ms) override virtual
Sends command to erase the entire chip.
Parameters
[out] delay_ms Time to wait until next is_device_busy call
[out] timeout_ms Time by which the erase should have timedout
Returns
The operation status.
Return values
false if the operation failed.
true if the operation succeeded.
Sends command to erase the entire chips.
Parameters
[out] delay_ms Time to wait until next is_device_busy call
[out] timeout_ms Time by which the erase should have timedout
Returns
The operation status.
Return values
false if the operation failed.
true if the operation succeeded.
Implements AP_FlashIface.
Definition at line 690 of file AP_FlashIface_JEDEC.cpp.
Referenced by test_mass_erase().
start_program_offset()
bool AP_FlashIface_JEDEC::start_program_offset (uint32_t offset, const uint8_t * data, uint32_t size, uint32_t & programming, uint32_t & delay_us, uint32_t & timeout_us) override virtual
Tries to program as much as possible starting from the offset until size. User needs to call this as many times as needed taking already programmed bytes into account.
Parameters
[in] offset address offset for program
[in] data data to be programmed
[in] size size desired to be programmed
[out] programming number of bytes programming, taking care of the limits
[out] delay_us Time to wait until program typically finishes
[out] timeout_us Time by which current program should have timedout.
Returns
The operation status.
Return values
false if the operation failed.
true if the operation succeeded.
Reimplemented from AP_FlashIface.
Definition at line 885 of file AP_FlashIface_JEDEC.cpp.
Referenced by start_program_page().
start_program_page()
bool AP_FlashIface_JEDEC::start_program_page (uint32_t page, const uint8_t * data, uint32_t & delay_us, uint32_t & timeout_us) override virtual
Sends command to start programming a page of the chip.
Parameters
[in] page Page number to be written to
[in] data data to be written
[out] delay_us Time to wait until next is_device_busy call
[out] timeout_us Time after which the erase should be timedout, should be reset at every call.
Returns
The operation status.
Return values
false if the operation failed.
true if the operation succeeded.
Implements AP_FlashIface.
Definition at line 853 of file AP_FlashIface_JEDEC.cpp.
Referenced by test_page_program().
start_sector_erase()
bool AP_FlashIface_JEDEC::start_sector_erase (uint32_t sector, uint32_t & delay_ms, uint32_t & timeout_ms) override virtual
Sends command to erase a sector of the chip.
Parameters
[in] sector Sector number to be erased
[out] delay_ms Time to wait until next is_device_busy call
[out] timeout_ms Time by which the erase should have timedout
Returns
The operation status.
Return values
false if the operation failed.
true if the operation succeeded.
Implements AP_FlashIface.
Definition at line 725 of file AP_FlashIface_JEDEC.cpp.
Referenced by test_sector_erase().
start_xip_mode()
bool AP_FlashIface_JEDEC::start_xip_mode (void ** addr) override virtual
Starts execution in place mode
Returns
if successfully entered XIP mode.
Return values
false the device failed to enter XIP mode.
true the device has entered XIP mode.
Reimplemented from AP_FlashIface.
Definition at line 1018 of file AP_FlashIface_JEDEC.cpp.
Referenced by test_page_program().
stop_xip_mode()
bool AP_FlashIface_JEDEC::stop_xip_mode () override virtual
Reimplemented from AP_FlashIface.
Definition at line 1104 of file AP_FlashIface_JEDEC.cpp.
Referenced by test_page_program().
verify_sector_erase()
bool AP_FlashIface_JEDEC::verify_sector_erase (uint32_t sector) override virtual
Check if selected sector is erased.
Parameters
[in] sector sector for which to check erase
Returns
The operation status.
Return values
false if the operation failed.
true if the operation succeeded.
Implements AP_FlashIface.
Definition at line 821 of file AP_FlashIface_JEDEC.cpp.
Referenced by test_sector_erase().
wait_ready()
void AP_FlashIface_JEDEC::wait_ready () protected
Definition at line 1003 of file AP_FlashIface_JEDEC.cpp.
Referenced by configure_device(), read(), start_erase_offset(), start_mass_erase(), start_program_offset(), start_xip_mode(), write_disable(), and write_enable().
write_disable()
bool AP_FlashIface_JEDEC::write_disable () protected
Definition at line 593 of file AP_FlashIface_JEDEC.cpp.
Referenced by configure_device(), start_erase_offset(), start_mass_erase(), start_program_offset(), and start_xip_mode().
write_enable()
bool AP_FlashIface_JEDEC::write_enable () protected
Definition at line 582 of file AP_FlashIface_JEDEC.cpp.
Referenced by configure_device(), start_erase_offset(), start_mass_erase(), start_program_offset(), and start_xip_mode().
write_reg()
bool AP_FlashIface_JEDEC::write_reg (uint8_t read_ins, uint8_t write_val) protected
Definition at line 642 of file AP_FlashIface_JEDEC.cpp.
Referenced by configure_device(), and modify_reg().
Member Data Documentation
_desc
struct AP_FlashIface_JEDEC::device_desc AP_FlashIface_JEDEC::_desc protected
Referenced by configure_device(), detect_device(), get_page_count(), get_page_size(), get_sector_count(), get_sector_size(), is_device_busy(), min_erase_size(), read(), start_erase_offset(), start_mass_erase(), start_program_offset(), start_program_page(), start_sector_erase(), start_xip_mode(), verify_sector_erase(), write_disable(), and write_enable().
_dev
AP_HAL::OwnPtr<AP_HAL::WSPIDevice> AP_FlashIface_JEDEC::_dev protected
Definition at line 260 of file AP_FlashIface_JEDEC.h.
Referenced by configure_device(), detect_device(), init(), is_device_busy(), read(), read_reg(), reset_device(), send_cmd(), start_erase_offset(), start_mass_erase(), start_program_offset(), start_xip_mode(), stop_xip_mode(), and write_reg().
_dev_list_idx
uint8_t AP_FlashIface_JEDEC::_dev_list_idx protected
Definition at line 302 of file AP_FlashIface_JEDEC.h.
Referenced by detect_device(), and init().
_wide_spi_mode
enum AP_FlashIface_JEDEC::WSPIMode AP_FlashIface_JEDEC::_wide_spi_mode protected
Referenced by configure_device(), read(), and start_xip_mode().
initialised
bool AP_FlashIface_JEDEC::initialised protected
Definition at line 303 of file AP_FlashIface_JEDEC.h.
Referenced by detect_device().
write_enable_called
bool AP_FlashIface_JEDEC::write_enable_called protected
Definition at line 304 of file AP_FlashIface_JEDEC.h.
Referenced by write_disable(), and write_enable().
The documentation for this class was generated from the following files:
libraries/AP_FlashIface/AP_FlashIface_JEDEC.h
libraries/AP_FlashIface/AP_FlashIface_JEDEC.cpp