APM:Libraries: AP_Filesystem_Sys Class Reference
AP_Filesystem_Sys Class Reference
#include <AP_Filesystem_Sys.h>
Classes
struct DirReadTracker
struct rfile
Public Member Functions
int open (const char *fname, int flags, bool allow_absolute_paths=false) override
int close (int fd) override
int32_t read (int fd, void *buf, uint32_t count) override
int32_t lseek (int fd, int32_t offset, int whence) override
int stat (const char *pathname, struct stat *stbuf) override
void * opendir (const char *pathname) override
struct dirent * readdir (void *dirp) override
int closedir (void *dirp) override
Public Member Functions inherited from AP_Filesystem_Backend
virtual int32_t write (int fd, const void *buf, uint32_t count)
virtual int fsync (int fd)
virtual int unlink (const char *pathname)
virtual int mkdir (const char *pathname)
virtual int rename (const char *oldpath, const char *newpath)
virtual int64_t disk_free (const char *path)
virtual int64_t disk_space (const char *path)
virtual bool set_mtime (const char *filename, const uint32_t mtime_sec)
virtual bool retry_mount (void)
virtual void unmount (void)
virtual bool format (void)
virtual AP_Filesystem_Backend::FormatStatus get_format_status () const
virtual FileData * load_file (const char *filename)
virtual void unload_file (FileData *fd)
Private Member Functions
int8_t file_in_sysfs (const char *fname)
Private Attributes
struct AP_Filesystem_Sys::rfile file [max_open_file]
Static Private Attributes
static constexpr uint8_t max_open_file = 4
Additional Inherited Members
Public Types inherited from AP_Filesystem_Backend
enum class FormatStatus {
NOT_STARTED , PENDING , IN_PROGRESS , SUCCESS ,
FAILURE
}
Protected Member Functions inherited from AP_Filesystem_Backend
bool file_op_allowed (void) const
Detailed Description
Definition at line 26 of file AP_Filesystem_Sys.h.
Member Function Documentation
close()
int AP_Filesystem_Sys::close (int fd) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 177 of file AP_Filesystem_Sys.cpp.
closedir()
int AP_Filesystem_Sys::closedir (void * dirp) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 254 of file AP_Filesystem_Sys.cpp.
file_in_sysfs()
int8_t AP_Filesystem_Sys::file_in_sysfs (const char * fname) private
Definition at line 60 of file AP_Filesystem_Sys.cpp.
Referenced by open(), and stat().
lseek()
int32_t AP_Filesystem_Sys::lseek (int fd, int32_t offset, int whence) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 204 of file AP_Filesystem_Sys.cpp.
open()
int AP_Filesystem_Sys::open (const char * fname, int flags, bool allow_absolute_paths = false) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 69 of file AP_Filesystem_Sys.cpp.
Referenced by close(), lseek(), open(), and read().
opendir()
void * AP_Filesystem_Sys::opendir (const char * pathname) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 225 of file AP_Filesystem_Sys.cpp.
read()
int32_t AP_Filesystem_Sys::read (int fd, void * buf, uint32_t count) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 190 of file AP_Filesystem_Sys.cpp.
readdir()
struct dirent * AP_Filesystem_Sys::readdir (void * dirp) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 240 of file AP_Filesystem_Sys.cpp.
stat()
int AP_Filesystem_Sys::stat (const char * pathname, struct stat * stbuf) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 264 of file AP_Filesystem_Sys.cpp.
Member Data Documentation
file
struct AP_Filesystem_Sys::rfile AP_Filesystem_Sys::file[max_open_file] private
Referenced by close(), lseek(), open(), and read().
max_open_file
constexpr uint8_t AP_Filesystem_Sys::max_open_file = 4 static constexpr private
Definition at line 41 of file AP_Filesystem_Sys.h.
Referenced by close(), lseek(), open(), and read().
The documentation for this class was generated from the following files:
libraries/AP_Filesystem/AP_Filesystem_Sys.h
libraries/AP_Filesystem/AP_Filesystem_Sys.cpp