APM:Libraries: AC_P_1D Class Reference
AC_P_1D Class Reference
Object managing one P controller.
#include <AC_P_1D.h>
Public Member Functions
AC_P_1D (float initial_p)
CLASS_NO_COPY (AC_P_1D)
float update_all (float &target, float measurement) WARN_IF_UNUSED
void set_limits (float output_min, float output_max, float D_Out_max=0.0f, float D2_Out_max=0.0f)
void set_error_limits (float error_min, float error_max)
float get_error_min () const
float get_error_max () const
void save_gains ()
AP_Float & kP () WARN_IF_UNUSED
const AP_Float & kP () const WARN_IF_UNUSED
float get_error () const
void kP (float v)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
AP_Float _kp
float _error
float _error_min
float _error_max
float _D1_max
const float default_kp
Detailed Description
Object managing one P controller.
Definition at line 11 of file AC_P_1D.h.
Constructor & Destructor Documentation
AC_P_1D()
AC_P_1D::AC_P_1D (float initial_p)
Definition at line 16 of file AC_P_1D.cpp.
Member Function Documentation
CLASS_NO_COPY()
AC_P_1D::CLASS_NO_COPY (AC_P_1D)
get_error()
float AC_P_1D::get_error () const inline
Definition at line 42 of file AC_P_1D.h.
Referenced by AC_PosControl::handle_ekf_z_reset(), AC_PosControl::input_accel_z(), AC_PosControl::input_pos_vel_accel_z(), AC_PosControl::input_pos_xyz(), AC_PosControl::input_vel_accel_z(), and AC_PosControl::update_pos_offset_z().
get_error_max()
float AC_P_1D::get_error_max () const inline
Definition at line 34 of file AC_P_1D.h.
Referenced by AC_PosControl::get_pos_error_z_up_cm().
get_error_min()
float AC_P_1D::get_error_min () const inline
Definition at line 31 of file AC_P_1D.h.
Referenced by AC_PosControl::get_pos_error_z_down_cm().
kP() [1/3]
const AP_Float & AC_P_1D::kP () const inline
Definition at line 41 of file AC_P_1D.h.
kP() [2/3]
AP_Float & AC_P_1D::kP () inline
Definition at line 40 of file AC_P_1D.h.
Referenced by AC_Loiter::calc_desired_velocity(), and AC_PosControl::get_stopping_point_z_cm().
kP() [3/3]
void AC_P_1D::kP (float v) inline
Definition at line 45 of file AC_P_1D.h.
save_gains()
void AC_P_1D::save_gains () inline
Definition at line 37 of file AC_P_1D.h.
set_error_limits()
void AC_P_1D::set_error_limits (float error_min, float error_max)
Definition at line 70 of file AC_P_1D.cpp.
set_limits()
void AC_P_1D::set_limits (float output_min, float output_max, float D_Out_max = 0.0f, float D2_Out_max = 0.0f)
Definition at line 44 of file AC_P_1D.cpp.
Referenced by AC_PosControl::set_correction_speed_accel_z().
update_all()
float AC_P_1D::update_all (float & target, float measurement)
Definition at line 25 of file AC_P_1D.cpp.
Referenced by AC_PosControl::update_z_controller().
Member Data Documentation
_D1_max
float AC_P_1D::_D1_max private
Definition at line 59 of file AC_P_1D.h.
Referenced by set_limits(), and update_all().
_error
float AC_P_1D::_error private
Definition at line 56 of file AC_P_1D.h.
Referenced by get_error(), and update_all().
_error_max
float AC_P_1D::_error_max private
Definition at line 58 of file AC_P_1D.h.
Referenced by get_error_max(), set_error_limits(), set_limits(), and update_all().
_error_min
float AC_P_1D::_error_min private
Definition at line 57 of file AC_P_1D.h.
Referenced by get_error_min(), set_error_limits(), set_limits(), and update_all().
_kp
AP_Float AC_P_1D::_kp private
Definition at line 53 of file AC_P_1D.h.
Referenced by kP(), kP(), kP(), save_gains(), set_limits(), and update_all().
default_kp
const float AC_P_1D::default_kp private
Definition at line 61 of file AC_P_1D.h.
var_info
const AP_Param::GroupInfo AC_P_1D::var_info static
Initial value:
= {
    AP_GROUPINFO_FLAGS_DEFAULT_POINTER("P",    0, AC_P_1D, _kp, default_kp),
    AP_GROUPEND
}
Definition at line 7 of file AC_P_1D.h.
The documentation for this class was generated from the following files:
libraries/AC_PID/AC_P_1D.h
libraries/AC_PID/AC_P_1D.cpp