APM:Libraries: AP_SmartRTL Class Reference
AP_SmartRTL Class Reference
#include <AP_SmartRTL.h>
Classes
struct dist_point
struct prune_loop_t
struct simplify_start_finish_t
Public Types
enum ThoroughCleanupType { THOROUGH_CLEAN_DEFAULT = 0 , THOROUGH_CLEAN_ALL , THOROUGH_CLEAN_SIMPLIFY_ONLY , THOROUGH_CLEAN_PRUNE_ONLY }
Public Member Functions
AP_SmartRTL (bool example_mode=false)
void init ()
bool is_active () const
uint16_t get_num_points () const
const Vector3f & get_point (uint16_t index) const
bool pop_point (Vector3f &point)
bool peek_point (Vector3f &point)
void set_home (bool position_ok)
void set_home (bool position_ok, const Vector3f &current_pos)
void update (bool position_ok, bool save_position)
void update (bool position_ok, const Vector3f &current_pos)
bool request_thorough_cleanup (ThoroughCleanupType clean_type=THOROUGH_CLEAN_DEFAULT)
void cancel_request_for_thorough_cleanup ()
void run_background_cleanup ()
bool use_pilot_yaw (void) const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
enum SRTL_Actions {
SRTL_POINT_ADD , SRTL_POINT_PRUNE , SRTL_POINT_SIMPLIFY , SRTL_ADD_FAILED_NO_SEMAPHORE ,
SRTL_ADD_FAILED_PATH_FULL , SRTL_POP_FAILED_NO_SEMAPHORE , SRTL_PEEK_FAILED_NO_SEMAPHORE , SRTL_DEACTIVATED_INIT_FAILED ,
SRTL_DEACTIVATED_BAD_POSITION , SRTL_DEACTIVATED_BAD_POSITION_TIMEOUT , SRTL_DEACTIVATED_PATH_FULL_TIMEOUT , SRTL_DEACTIVATED_PROGRAM_ERROR
}
enum class Options : int32_t { IgnorePilotYaw = (1U << 2) }
Private Member Functions
bool add_point (const Vector3f &point)
void routine_cleanup (uint16_t path_points_count, uint16_t path_points_complete_limit)
bool thorough_cleanup (uint16_t path_points_count, ThoroughCleanupType clean_type)
void detect_simplifications ()
void detect_loops ()
void restart_simplify_if_new_points (uint16_t path_points_count)
void restart_pruning_if_new_points ()
void restart_simplification (uint16_t path_points_count)
void reset_simplification ()
void restart_pruning (uint16_t path_points_count)
void reset_pruning ()
void remove_points_by_simplify_bitmask ()
bool remove_points_by_loops (uint16_t num_points_to_remove)
bool add_loop (uint16_t start_index, uint16_t end_index, const Vector3f &midpoint)
void deactivate (SRTL_Actions action, const char *reason)
void log_action (SRTL_Actions action, const Vector3f &point=Vector3f()) const
bool loops_overlap (const prune_loop_t &loop1, const prune_loop_t &loop2) const
Static Private Member Functions
static dist_point segment_segment_dist (const Vector3f &p1, const Vector3f &p2, const Vector3f &p3, const Vector3f &p4)
Private Attributes
AP_Float _accuracy
AP_Int16 _points_max
AP_Int32 _options
bool _active
bool _example_mode
bool _home_saved
uint32_t _last_good_position_ms
uint32_t _last_position_save_ms
uint32_t _thorough_clean_request_ms
uint32_t _thorough_clean_complete_ms
uint32_t _last_low_space_notify_ms
ThoroughCleanupType _thorough_clean_type
Vector3f * _path
uint16_t _path_points_max
uint16_t _path_points_count
uint16_t _path_points_completed_limit
HAL_Semaphore _path_sem
struct {
bool complete
bool removal_required
uint16_t path_points_count
uint16_t path_points_completed = SMARTRTL_POINTS_MAX
simplify_start_finish_t * stack
uint16_t stack_max
uint16_t stack_count
Bitmask< SMARTRTL_POINTS_MAX > bitmask
} _simplify
struct {
bool complete
uint16_t path_points_count
uint16_t path_points_completed
uint16_t i
uint16_t j
prune_loop_t * loops
uint16_t loops_max
uint16_t loops_count
} _prune
Detailed Description
Definition at line 25 of file AP_SmartRTL.h.
Member Enumeration Documentation
Options
enum class AP_SmartRTL::Options : int32_t strong private
Enumerator
IgnorePilotYaw
Definition at line 107 of file AP_SmartRTL.h.
SRTL_Actions
enum AP_SmartRTL::SRTL_Actions private
Enumerator
SRTL_POINT_ADD
SRTL_POINT_PRUNE
SRTL_POINT_SIMPLIFY
SRTL_ADD_FAILED_NO_SEMAPHORE
SRTL_ADD_FAILED_PATH_FULL
SRTL_POP_FAILED_NO_SEMAPHORE
SRTL_PEEK_FAILED_NO_SEMAPHORE
SRTL_DEACTIVATED_INIT_FAILED
SRTL_DEACTIVATED_BAD_POSITION
SRTL_DEACTIVATED_BAD_POSITION_TIMEOUT
SRTL_DEACTIVATED_PATH_FULL_TIMEOUT
SRTL_DEACTIVATED_PROGRAM_ERROR
Definition at line 91 of file AP_SmartRTL.h.
ThoroughCleanupType
enum AP_SmartRTL::ThoroughCleanupType
Enumerator
THOROUGH_CLEAN_DEFAULT
THOROUGH_CLEAN_ALL
THOROUGH_CLEAN_SIMPLIFY_ONLY
THOROUGH_CLEAN_PRUNE_ONLY
Definition at line 63 of file AP_SmartRTL.h.
Constructor & Destructor Documentation
AP_SmartRTL()
AP_SmartRTL::AP_SmartRTL (bool example_mode = false)
Definition at line 86 of file AP_SmartRTL.cpp.
Member Function Documentation
add_loop()
bool AP_SmartRTL::add_loop (uint16_t start_index, uint16_t end_index, const Vector3f & midpoint) private
Definition at line 764 of file AP_SmartRTL.cpp.
Referenced by detect_loops().
add_point()
bool AP_SmartRTL::add_point (const Vector3f & point) private
Definition at line 321 of file AP_SmartRTL.cpp.
Referenced by set_home(), and update().
cancel_request_for_thorough_cleanup()
void AP_SmartRTL::cancel_request_for_thorough_cleanup ()
Definition at line 311 of file AP_SmartRTL.cpp.
deactivate()
void AP_SmartRTL::deactivate (SRTL_Actions action, const char * reason) private
Definition at line 865 of file AP_SmartRTL.cpp.
Referenced by remove_points_by_loops(), remove_points_by_simplify_bitmask(), and update().
detect_loops()
void AP_SmartRTL::detect_loops () private
This method runs for the allotted time, and detects loops in a path. Any detected loops are added to _prune.loops, this function does not alter the path in memory. It works by comparing the line segment between any two sequential points to the line segment between any other two sequential points. If they get close enough, anything between them could be pruned.
reset_pruning should have been called at least once before this function is called to setup the indexes (_prune.i, etc)
Definition at line 568 of file AP_SmartRTL.cpp.
Referenced by routine_cleanup(), and thorough_cleanup().
detect_simplifications()
void AP_SmartRTL::detect_simplifications () private
Definition at line 494 of file AP_SmartRTL.cpp.
Referenced by routine_cleanup(), and thorough_cleanup().
get_num_points()
uint16_t AP_SmartRTL::get_num_points () const
Definition at line 138 of file AP_SmartRTL.cpp.
Referenced by check_path().
get_point()
const Vector3f & AP_SmartRTL::get_point (uint16_t index) const inline
Definition at line 42 of file AP_SmartRTL.h.
Referenced by check_path().
init()
void AP_SmartRTL::init ()
Definition at line 94 of file AP_SmartRTL.cpp.
Referenced by setup().
is_active()
bool AP_SmartRTL::is_active () const inline
Definition at line 36 of file AP_SmartRTL.h.
log_action()
void AP_SmartRTL::log_action (SRTL_Actions action, const Vector3f & point = Vector3f()) const inline private
Definition at line 180 of file AP_SmartRTL.h.
Referenced by add_point(), deactivate(), init(), peek_point(), pop_point(), remove_points_by_loops(), and remove_points_by_simplify_bitmask().
loops_overlap()
bool AP_SmartRTL::loops_overlap (const prune_loop_t & loop1, const prune_loop_t & loop2) const private
Definition at line 883 of file AP_SmartRTL.cpp.
Referenced by add_loop().
peek_point()
bool AP_SmartRTL::peek_point (Vector3f & point)
Definition at line 174 of file AP_SmartRTL.cpp.
pop_point()
bool AP_SmartRTL::pop_point (Vector3f & point)
Definition at line 144 of file AP_SmartRTL.cpp.
remove_points_by_loops()
bool AP_SmartRTL::remove_points_by_loops (uint16_t num_points_to_remove) private
Definition at line 703 of file AP_SmartRTL.cpp.
Referenced by routine_cleanup(), and thorough_cleanup().
remove_points_by_simplify_bitmask()
void AP_SmartRTL::remove_points_by_simplify_bitmask () private
Definition at line 665 of file AP_SmartRTL.cpp.
Referenced by routine_cleanup(), and thorough_cleanup().
request_thorough_cleanup()
bool AP_SmartRTL::request_thorough_cleanup (ThoroughCleanupType clean_type = THOROUGH_CLEAN_DEFAULT)
Definition at line 285 of file AP_SmartRTL.cpp.
Referenced by loop().
reset_pruning()
void AP_SmartRTL::reset_pruning () private
Definition at line 657 of file AP_SmartRTL.cpp.
Referenced by set_home().
reset_simplification()
void AP_SmartRTL::reset_simplification () private
Definition at line 641 of file AP_SmartRTL.cpp.
Referenced by set_home().
restart_pruning()
void AP_SmartRTL::restart_pruning (uint16_t path_points_count) private
Definition at line 648 of file AP_SmartRTL.cpp.
Referenced by reset_pruning(), and restart_pruning_if_new_points().
restart_pruning_if_new_points()
void AP_SmartRTL::restart_pruning_if_new_points () private
Definition at line 622 of file AP_SmartRTL.cpp.
Referenced by routine_cleanup(), and thorough_cleanup().
restart_simplification()
void AP_SmartRTL::restart_simplification (uint16_t path_points_count) private
Definition at line 631 of file AP_SmartRTL.cpp.
Referenced by reset_simplification(), restart_simplify_if_new_points(), and routine_cleanup().
restart_simplify_if_new_points()
void AP_SmartRTL::restart_simplify_if_new_points (uint16_t path_points_count) private
Definition at line 613 of file AP_SmartRTL.cpp.
Referenced by thorough_cleanup().
routine_cleanup()
void AP_SmartRTL::routine_cleanup (uint16_t path_points_count, uint16_t path_points_complete_limit) private
Definition at line 403 of file AP_SmartRTL.cpp.
Referenced by run_background_cleanup().
run_background_cleanup()
void AP_SmartRTL::run_background_cleanup ()
Definition at line 354 of file AP_SmartRTL.cpp.
Referenced by init(), and loop().
segment_segment_dist()
AP_SmartRTL::dist_point AP_SmartRTL::segment_segment_dist (const Vector3f & p1, const Vector3f & p2, const Vector3f & p3, const Vector3f & p4) static private
Returns the closest distance in 3D space between any part of two input segments, defined from p1 to p2 and from p3 to p4. Also returns the point which is halfway between
Limitation: This function does not work for parallel lines. In this case, dist_point.distance will be FLT_MAX. This does not matter for the path cleanup algorithm because the pruning will still occur fine between the first parallel segment and a segment which is directly before or after the second segment.
Definition at line 827 of file AP_SmartRTL.cpp.
Referenced by detect_loops().
set_home() [1/2]
void AP_SmartRTL::set_home (bool position_ok)
Definition at line 201 of file AP_SmartRTL.cpp.
Referenced by reset(), set_home(), and update().
set_home() [2/2]
void AP_SmartRTL::set_home (bool position_ok, const Vector3f & current_pos)
Definition at line 208 of file AP_SmartRTL.cpp.
thorough_cleanup()
bool AP_SmartRTL::thorough_cleanup (uint16_t path_points_count, ThoroughCleanupType clean_type) private
Definition at line 454 of file AP_SmartRTL.cpp.
Referenced by run_background_cleanup().
update() [1/2]
void AP_SmartRTL::update (bool position_ok, bool save_position)
Definition at line 241 of file AP_SmartRTL.cpp.
Referenced by reset(), and update().
update() [2/2]
void AP_SmartRTL::update (bool position_ok, const Vector3f & current_pos)
Definition at line 257 of file AP_SmartRTL.cpp.
use_pilot_yaw()
bool AP_SmartRTL::use_pilot_yaw (void) const
Definition at line 904 of file AP_SmartRTL.cpp.
Member Data Documentation
_accuracy
AP_Float AP_SmartRTL::_accuracy private
Definition at line 184 of file AP_SmartRTL.h.
Referenced by add_point(), and init().
_active
bool AP_SmartRTL::_active private
Definition at line 189 of file AP_SmartRTL.h.
Referenced by deactivate(), is_active(), peek_point(), pop_point(), request_thorough_cleanup(), run_background_cleanup(), set_home(), update(), and update().
_example_mode
bool AP_SmartRTL::_example_mode private
Definition at line 190 of file AP_SmartRTL.h.
Referenced by init().
_home_saved
bool AP_SmartRTL::_home_saved private
Definition at line 191 of file AP_SmartRTL.h.
Referenced by set_home(), and update().
_last_good_position_ms
uint32_t AP_SmartRTL::_last_good_position_ms private
Definition at line 192 of file AP_SmartRTL.h.
Referenced by set_home(), and update().
_last_low_space_notify_ms
uint32_t AP_SmartRTL::_last_low_space_notify_ms private
Definition at line 196 of file AP_SmartRTL.h.
Referenced by run_background_cleanup().
_last_position_save_ms
uint32_t AP_SmartRTL::_last_position_save_ms private
Definition at line 193 of file AP_SmartRTL.h.
Referenced by set_home(), and update().
_options
AP_Int32 AP_SmartRTL::_options private
Definition at line 186 of file AP_SmartRTL.h.
Referenced by use_pilot_yaw().
_path
Vector3f* AP_SmartRTL::_path private
Definition at line 200 of file AP_SmartRTL.h.
Referenced by add_loop(), add_point(), detect_loops(), detect_simplifications(), get_point(), init(), peek_point(), pop_point(), remove_points_by_loops(), remove_points_by_simplify_bitmask(), and set_home().
_path_points_completed_limit
uint16_t AP_SmartRTL::_path_points_completed_limit private
Definition at line 203 of file AP_SmartRTL.h.
Referenced by pop_point(), and run_background_cleanup().
_path_points_count
uint16_t AP_SmartRTL::_path_points_count private
Definition at line 202 of file AP_SmartRTL.h.
Referenced by add_point(), get_num_points(), peek_point(), pop_point(), remove_points_by_loops(), remove_points_by_simplify_bitmask(), run_background_cleanup(), and set_home().
_path_points_max
uint16_t AP_SmartRTL::_path_points_max private
Definition at line 201 of file AP_SmartRTL.h.
Referenced by add_point(), init(), routine_cleanup(), and run_background_cleanup().
_path_sem
HAL_Semaphore AP_SmartRTL::_path_sem private
Definition at line 204 of file AP_SmartRTL.h.
Referenced by add_point(), peek_point(), pop_point(), remove_points_by_loops(), remove_points_by_simplify_bitmask(), and run_background_cleanup().
_points_max
AP_Int16 AP_SmartRTL::_points_max private
Definition at line 185 of file AP_SmartRTL.h.
Referenced by init().
[struct]
struct { ... } AP_SmartRTL::_prune
Referenced by add_loop(), detect_loops(), init(), remove_points_by_loops(), reset_pruning(), restart_pruning(), restart_pruning_if_new_points(), routine_cleanup(), and thorough_cleanup().
[struct]
struct { ... } AP_SmartRTL::_simplify
Referenced by AP_SmartRTL(), detect_simplifications(), init(), remove_points_by_simplify_bitmask(), reset_simplification(), restart_pruning_if_new_points(), restart_simplification(), restart_simplify_if_new_points(), routine_cleanup(), and thorough_cleanup().
_thorough_clean_complete_ms
uint32_t AP_SmartRTL::_thorough_clean_complete_ms private
Definition at line 195 of file AP_SmartRTL.h.
Referenced by request_thorough_cleanup(), and run_background_cleanup().
_thorough_clean_request_ms
uint32_t AP_SmartRTL::_thorough_clean_request_ms private
Definition at line 194 of file AP_SmartRTL.h.
Referenced by cancel_request_for_thorough_cleanup(), request_thorough_cleanup(), and run_background_cleanup().
_thorough_clean_type
ThoroughCleanupType AP_SmartRTL::_thorough_clean_type private
Definition at line 197 of file AP_SmartRTL.h.
Referenced by request_thorough_cleanup(), and run_background_cleanup().
bitmask
Bitmask<SMARTRTL_POINTS_MAX> AP_SmartRTL::bitmask
Definition at line 220 of file AP_SmartRTL.h.
complete
bool AP_SmartRTL::complete
Definition at line 213 of file AP_SmartRTL.h.
i
uint16_t AP_SmartRTL::i
Definition at line 234 of file AP_SmartRTL.h.
Referenced by add_loop(), detect_simplifications(), and remove_points_by_loops().
j
uint16_t AP_SmartRTL::j
Definition at line 235 of file AP_SmartRTL.h.
loops
prune_loop_t* AP_SmartRTL::loops
Definition at line 236 of file AP_SmartRTL.h.
loops_count
uint16_t AP_SmartRTL::loops_count
Definition at line 238 of file AP_SmartRTL.h.
loops_max
uint16_t AP_SmartRTL::loops_max
Definition at line 237 of file AP_SmartRTL.h.
path_points_completed
uint16_t AP_SmartRTL::path_points_completed = SMARTRTL_POINTS_MAX
Definition at line 216 of file AP_SmartRTL.h.
path_points_count
uint16_t AP_SmartRTL::path_points_count
Definition at line 215 of file AP_SmartRTL.h.
Referenced by restart_pruning(), restart_simplification(), restart_simplify_if_new_points(), routine_cleanup(), run_background_cleanup(), and thorough_cleanup().
removal_required
bool AP_SmartRTL::removal_required
Definition at line 214 of file AP_SmartRTL.h.
stack
simplify_start_finish_t* AP_SmartRTL::stack
Definition at line 217 of file AP_SmartRTL.h.
stack_count
uint16_t AP_SmartRTL::stack_count
Definition at line 219 of file AP_SmartRTL.h.
stack_max
uint16_t AP_SmartRTL::stack_max
Definition at line 218 of file AP_SmartRTL.h.
var_info
const AP_Param::GroupInfo AP_SmartRTL::var_info static
Initial value:
= {
    AP_GROUPINFO("ACCURACY", 0, AP_SmartRTL, _accuracy, SMARTRTL_ACCURACY_DEFAULT),
    AP_GROUPINFO("POINTS", 1, AP_SmartRTL, _points_max, SMARTRTL_POINTS_DEFAULT),
    AP_GROUPINFO("OPTIONS", 2, AP_SmartRTL, _options, 0),
    AP_GROUPEND
}
Definition at line 22 of file AP_SmartRTL.h.
The documentation for this class was generated from the following files:
libraries/AP_SmartRTL/AP_SmartRTL.h
libraries/AP_SmartRTL/AP_SmartRTL.cpp