APM:Libraries: AP_HAL::RCOutput Class Reference
AP_HAL::RCOutput Class Reference abstract
#include <RCOutput.h>
Public Types
enum output_mode {
MODE_PWM_NONE , MODE_PWM_NORMAL , MODE_PWM_ONESHOT , MODE_PWM_ONESHOT125 ,
MODE_PWM_BRUSHED , MODE_PWM_DSHOT150 , MODE_PWM_DSHOT300 , MODE_PWM_DSHOT600 ,
MODE_PWM_DSHOT1200 , MODE_NEOPIXEL , MODE_PROFILED , MODE_NEOPIXELRGB
}
enum BLHeliDshotCommand : uint8_t {
DSHOT_RESET = 0 , DSHOT_BEEP1 = 1 , DSHOT_BEEP2 = 2 , DSHOT_BEEP3 = 3 ,
DSHOT_BEEP4 = 4 , DSHOT_BEEP5 = 5 , DSHOT_ESC_INFO = 6 , DSHOT_ROTATE = 7 ,
DSHOT_ROTATE_ALTERNATE = 8 , DSHOT_3D_OFF = 9 , DSHOT_3D_ON = 10 , DSHOT_SAVE = 12 ,
DSHOT_EXTENDED_TELEMETRY_ENABLE = 13 , DSHOT_EXTENDED_TELEMETRY_DISABLE = 14 , DSHOT_NORMAL = 20 , DSHOT_REVERSE = 21 ,
DSHOT_LED0_ON = 22 , DSHOT_LED1_ON = 23 , DSHOT_LED2_ON = 24 , DSHOT_LED3_ON = 25 ,
DSHOT_LED0_OFF = 26 , DSHOT_LED1_OFF = 27 , DSHOT_LED2_OFF = 28 , DSHOT_LED3_OFF = 29
}
enum DshotEscType {
DSHOT_ESC_NONE = 0 , DSHOT_ESC_BLHELI = 1 , DSHOT_ESC_BLHELI_S = 2 , DSHOT_ESC_BLHELI_EDT = 3 ,
DSHOT_ESC_BLHELI_EDT_S = 4
}
Public Member Functions
virtual void init ()=0
virtual void set_freq (uint32_t chmask, uint16_t freq_hz)=0
virtual uint16_t get_freq (uint8_t chan)=0
virtual void enable_ch (uint8_t chan)=0
virtual void disable_ch (uint8_t chan)=0
virtual void write (uint8_t chan, uint16_t period_us)=0
virtual void set_reversible_mask (uint32_t chanmask)
virtual void set_reversed_mask (uint32_t chanmask)
virtual uint32_t get_reversed_mask ()
virtual void update_channel_masks ()
virtual void disable_channel_mask_updates ()
virtual void enable_channel_mask_updates ()
virtual void cork ()=0
virtual void push ()=0
virtual uint16_t read (uint8_t chan)=0
virtual void read (uint16_t *period_us, uint8_t len)=0
virtual uint16_t read_last_sent (uint8_t chan)
virtual void read_last_sent (uint16_t *period_us, uint8_t len)
virtual void set_failsafe_pwm (uint32_t chmask, uint16_t period_us)
virtual bool force_safety_on (void)
virtual void force_safety_off (void)
void set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm)
float scale_esc_to_unity (uint16_t pwm) const
virtual uint16_t get_erpm (uint8_t chan) const
virtual float get_erpm_error_rate (uint8_t chan) const
virtual bool new_erpm ()
virtual uint32_t read_erpm (uint16_t *erpm, uint8_t len)
virtual bool enable_px4io_sbus_out (uint16_t rate_hz)
virtual void timer_tick (void)
virtual bool serial_setup_output (uint8_t chan, uint32_t baudrate, uint32_t chanmask)
virtual bool serial_write_bytes (const uint8_t *bytes, uint16_t len)
virtual uint16_t serial_read_bytes (uint8_t *buf, uint16_t len)
virtual void serial_end (void)
virtual void set_output_mode (uint32_t mask, enum output_mode mode)
virtual enum output_mode get_output_mode (uint32_t &mask)
virtual bool get_output_mode_banner (char banner_msg[], uint8_t banner_msg_len) const
virtual uint32_t get_disabled_channels (uint32_t digital_mask)
virtual void set_default_rate (uint16_t rate_hz)
virtual void set_telem_request_mask (uint32_t mask)
virtual void set_bidir_dshot_mask (uint32_t mask)
virtual void set_active_escs_mask (uint32_t mask)
virtual void set_dshot_rate (uint8_t dshot_rate, uint16_t loop_rate_hz)
virtual void set_dshot_period (uint32_t period_us, uint8_t dshot_rate)
virtual uint32_t get_dshot_period_us () const
virtual void set_dshot_esc_type (DshotEscType esc_type)
virtual DshotEscType get_dshot_esc_type () const
virtual void send_dshot_command (uint8_t command, uint8_t chan=ALL_CHANNELS, uint32_t command_timeout_ms=0, uint16_t repeat_count=10, bool priority=false)
virtual void set_motor_poles (uint8_t poles)
virtual bool set_serial_led_num_LEDs (const uint16_t chan, uint8_t num_leds, output_mode mode=MODE_PWM_NONE, uint32_t clock_mask=0)
virtual bool set_serial_led_rgb_data (const uint16_t chan, int8_t led, uint8_t red, uint8_t green, uint8_t blue)
virtual bool serial_led_send (const uint16_t chan)
virtual void timer_info (ExpandingString &str)
virtual bool supports_gpio ()
virtual void write_gpio (uint8_t chan, bool active)
Static Public Member Functions
static bool is_dshot_protocol (const enum output_mode mode)
static bool is_led_protocol (const enum output_mode mode)
static uint32_t calculate_bitrate_prescaler (uint32_t timer_clock, uint32_t target_frequency, bool at_least_freq=false)
Public Attributes
const uint8_t DSHOT_ZERO_THROTTLE = 48
Static Public Attributes
static const uint32_t ALL_CHANNELS = 255
static constexpr uint32_t DSHOT_BIT_WIDTH_TICKS_DEFAULT = 8
static constexpr uint32_t DSHOT_BIT_0_TICKS_DEFAULT = 3
static constexpr uint32_t DSHOT_BIT_1_TICKS_DEFAULT = 6
static constexpr uint32_t DSHOT_BIT_WIDTH_TICKS_S = 11
static constexpr uint32_t DSHOT_BIT_0_TICKS_S = 4
static constexpr uint32_t DSHOT_BIT_1_TICKS_S = 8
static uint32_t DSHOT_BIT_WIDTH_TICKS = DSHOT_BIT_WIDTH_TICKS_DEFAULT
static uint32_t DSHOT_BIT_0_TICKS = DSHOT_BIT_0_TICKS_DEFAULT
static uint32_t DSHOT_BIT_1_TICKS = DSHOT_BIT_1_TICKS_DEFAULT
static constexpr uint32_t NEOP_BIT_WIDTH_TICKS = 8
static constexpr uint32_t NEOP_BIT_0_TICKS = 3
static constexpr uint32_t NEOP_BIT_1_TICKS = 6
static constexpr uint32_t PROFI_BIT_0_TICKS = 7
static constexpr uint32_t PROFI_BIT_1_TICKS = 14
static constexpr uint32_t PROFI_BIT_WIDTH_TICKS = 20
static constexpr uint32_t LED_OUTPUT_PERIOD_US = 10000
Protected Member Functions
void append_to_banner (char banner_msg[], uint8_t banner_msg_len, output_mode out_mode, uint8_t low_ch, uint8_t high_ch) const
const char * get_output_mode_string (enum output_mode out_mode) const
Protected Attributes
uint16_t _esc_pwm_min
uint16_t _esc_pwm_max
Detailed Description
Definition at line 50 of file RCOutput.h.
Member Enumeration Documentation
BLHeliDshotCommand
enum AP_HAL::RCOutput::BLHeliDshotCommand : uint8_t
Enumerator
DSHOT_RESET
DSHOT_BEEP1
DSHOT_BEEP2
DSHOT_BEEP3
DSHOT_BEEP4
DSHOT_BEEP5
DSHOT_ESC_INFO
DSHOT_ROTATE
DSHOT_ROTATE_ALTERNATE
DSHOT_3D_OFF
DSHOT_3D_ON
DSHOT_SAVE
DSHOT_EXTENDED_TELEMETRY_ENABLE
DSHOT_EXTENDED_TELEMETRY_DISABLE
DSHOT_NORMAL
DSHOT_REVERSE
DSHOT_LED0_ON
DSHOT_LED1_ON
DSHOT_LED2_ON
DSHOT_LED3_ON
DSHOT_LED0_OFF
DSHOT_LED1_OFF
DSHOT_LED2_OFF
DSHOT_LED3_OFF
Definition at line 242 of file RCOutput.h.
DshotEscType
enum AP_HAL::RCOutput::DshotEscType
Enumerator
DSHOT_ESC_NONE
DSHOT_ESC_BLHELI
DSHOT_ESC_BLHELI_S
DSHOT_ESC_BLHELI_EDT
DSHOT_ESC_BLHELI_EDT_S
Definition at line 272 of file RCOutput.h.
output_mode
enum AP_HAL::RCOutput::output_mode
Enumerator
MODE_PWM_NONE
MODE_PWM_NORMAL
MODE_PWM_ONESHOT
MODE_PWM_ONESHOT125
MODE_PWM_BRUSHED
MODE_PWM_DSHOT150
MODE_PWM_DSHOT300
MODE_PWM_DSHOT600
MODE_PWM_DSHOT1200
MODE_NEOPIXEL
MODE_PROFILED
MODE_NEOPIXELRGB
Definition at line 211 of file RCOutput.h.
Member Function Documentation
append_to_banner()
void RCOutput::append_to_banner (char banner_msg[], uint8_t banner_msg_len, output_mode out_mode, uint8_t low_ch, uint8_t high_ch) const protected
Definition at line 44 of file RCOutput.cpp.
calculate_bitrate_prescaler()
uint32_t RCOutput::calculate_bitrate_prescaler (uint32_t timer_clock, uint32_t target_frequency, bool at_least_freq = false) static
Definition at line 80 of file RCOutput.cpp.
Referenced by PrescalerParameterizedTestFixture::test_prescaler(), and PrescalerParameterizedTestFixture::test_prescaler_neopixel().
cork()
virtual void AP_HAL::RCOutput::cork () pure virtual
Implemented in ap::RCOutput_Tap, ESP32::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_Bebop, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, ChibiOS::RCOutput, Empty::RCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, and HALSITL::RCOutput.
Referenced by SRV_Channels::cork(), and AP_IOMCU_FW::pwm_out_update().
disable_ch()
virtual void AP_HAL::RCOutput::disable_ch (uint8_t chan) pure virtual
Implemented in ap::RCOutput_Tap, ChibiOS::RCOutput, Empty::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_AioPRU, Linux::RCOutput_Bebop, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and ESP32::RCOutput.
Referenced by SRV_Channels::enable_aux_servos(), and AP_IOMCU_FW::rcout_config_update().
disable_channel_mask_updates()
virtual void AP_HAL::RCOutput::disable_channel_mask_updates () inline virtual
Definition at line 92 of file RCOutput.h.
enable_ch()
virtual void AP_HAL::RCOutput::enable_ch (uint8_t chan) pure virtual
Implemented in ap::RCOutput_Tap, ChibiOS::RCOutput, Empty::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_AioPRU, Linux::RCOutput_Bebop, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and ESP32::RCOutput.
Referenced by SRV_Channels::enable_aux_servos(), SRV_Channels::enable_by_mask(), RCOutputRGBLed::init(), RC_UART::loop(), AP_IOMCU_FW::rcout_config_update(), and setup().
enable_channel_mask_updates()
virtual void AP_HAL::RCOutput::enable_channel_mask_updates () inline virtual
Definition at line 93 of file RCOutput.h.
enable_px4io_sbus_out()
virtual bool AP_HAL::RCOutput::enable_px4io_sbus_out (uint16_t rate_hz) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 166 of file RCOutput.h.
Referenced by AP_BoardConfig::board_setup_sbus().
force_safety_off()
virtual void AP_HAL::RCOutput::force_safety_off (void) inline virtual
Reimplemented in ESP32::RCOutput, Linux::RCOutput_PCA9685, ChibiOS::RCOutput, and HALSITL::RCOutput.
Definition at line 134 of file RCOutput.h.
Referenced by GCS_MAVLINK::_set_mode_common(), AP_BoardConfig::board_init_safety(), AP_IOMCU_FW::handle_code_write(), GCS_MAVLINK::handle_do_set_safety_switch_state(), AP_IOMCU_FW::init(), RC_UART::loop(), and AP_IOMCU_FW::safety_update().
force_safety_on()
virtual bool AP_HAL::RCOutput::force_safety_on (void) inline virtual
Reimplemented in ESP32::RCOutput, Linux::RCOutput_PCA9685, ChibiOS::RCOutput, and HALSITL::RCOutput.
Definition at line 129 of file RCOutput.h.
Referenced by GCS_MAVLINK::_set_mode_common(), AP_Arming::disarm(), AP_IOMCU_FW::handle_code_write(), GCS_MAVLINK::handle_do_set_safety_switch_state(), AP_Vehicle::reboot(), ChibiOS::Scheduler::reboot(), ESP32::Scheduler::reboot(), HAL_Linux::run(), and AP_IOMCU_FW::safety_update().
get_disabled_channels()
virtual uint32_t AP_HAL::RCOutput::get_disabled_channels (uint32_t digital_mask) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 296 of file RCOutput.h.
Referenced by SRV_Channels::set_digital_outputs().
get_dshot_esc_type()
virtual DshotEscType AP_HAL::RCOutput::get_dshot_esc_type () const inline virtual
Definition at line 336 of file RCOutput.h.
Referenced by DShotLED::hw_set_rgb().
get_dshot_period_us()
virtual uint32_t AP_HAL::RCOutput::get_dshot_period_us () const inline virtual
Definition at line 329 of file RCOutput.h.
get_erpm()
virtual uint16_t AP_HAL::RCOutput::get_erpm (uint8_t chan) const inline virtual
Definition at line 155 of file RCOutput.h.
get_erpm_error_rate()
virtual float AP_HAL::RCOutput::get_erpm_error_rate (uint8_t chan) const inline virtual
Definition at line 156 of file RCOutput.h.
get_freq()
virtual uint16_t AP_HAL::RCOutput::get_freq (uint8_t chan) pure virtual
Implemented in ap::RCOutput_Tap, ChibiOS::RCOutput, Empty::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_AioPRU, Linux::RCOutput_Bebop, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and ESP32::RCOutput.
Referenced by RCOutputRGBLed::hw_set_rgb().
get_output_mode()
virtual enum output_mode AP_HAL::RCOutput::get_output_mode (uint32_t & mask) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 282 of file RCOutput.h.
Referenced by AP_IOMCU_FW::rcout_config_update().
get_output_mode_banner()
virtual bool AP_HAL::RCOutput::get_output_mode_banner (char banner_msg[], uint8_t banner_msg_len) const inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 291 of file RCOutput.h.
Referenced by AP_Vehicle::loop(), LoggerMessageWriter_WriteSysInfo::process(), and GCS_MAVLINK::send_banner().
get_output_mode_string()
const char * RCOutput::get_output_mode_string (enum output_mode out_mode) const protected
Definition at line 10 of file RCOutput.cpp.
get_reversed_mask()
virtual uint32_t AP_HAL::RCOutput::get_reversed_mask () inline virtual
Definition at line 82 of file RCOutput.h.
init()
virtual void AP_HAL::RCOutput::init () pure virtual
Implemented in ap::RCOutput_Tap, ChibiOS::RCOutput, Empty::RCOutput, ESP32::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_AioPRU, Linux::RCOutput_Bebop, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, and HALSITL::RCOutput.
Referenced by ESP32::Scheduler::_main_thread(), AP_BoardConfig::board_setup(), HAL_Linux::run(), HAL_SITL::run(), and setup().
is_dshot_protocol()
bool RCOutput::is_dshot_protocol (const enum output_mode mode) static
Definition at line 64 of file RCOutput.cpp.
Referenced by ChibiOS::RCOutput::pwm_group::can_send_dshot_pulse().
is_led_protocol()
static bool AP_HAL::RCOutput::is_led_protocol (const enum output_mode mode) inline static
Definition at line 229 of file RCOutput.h.
new_erpm()
virtual bool AP_HAL::RCOutput::new_erpm () inline virtual
Definition at line 160 of file RCOutput.h.
push()
virtual void AP_HAL::RCOutput::push () pure virtual
Implemented in ap::RCOutput_Tap, ESP32::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_Bebop, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, ChibiOS::RCOutput, Empty::RCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, and HALSITL::RCOutput.
Referenced by SRV_Channels::push(), and AP_IOMCU_FW::pwm_out_update().
read() [1/2]
virtual void AP_HAL::RCOutput::read (uint16_t * period_us, uint8_t len) pure virtual
Implemented in ap::RCOutput_Tap, ChibiOS::RCOutput, Empty::RCOutput, ESP32::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_AioPRU, Linux::RCOutput_Bebop, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, and HALSITL::RCOutput.
read() [2/2]
virtual uint16_t AP_HAL::RCOutput::read (uint8_t chan) pure virtual
Implemented in ap::RCOutput_Tap, ChibiOS::RCOutput, Empty::RCOutput, ESP32::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_AioPRU, Linux::RCOutput_Bebop, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, and HALSITL::RCOutput.
Referenced by GPIO_Navigator::read(), read_last_sent(), read_last_sent(), GCS_MAVLINK::send_servo_output_raw(), stability_test(), and AP_Logger::Write_RCOUT().
read_erpm()
virtual uint32_t AP_HAL::RCOutput::read_erpm (uint16_t * erpm, uint8_t len) inline virtual
Definition at line 161 of file RCOutput.h.
read_last_sent() [1/2]
virtual void AP_HAL::RCOutput::read_last_sent (uint16_t * period_us, uint8_t len) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 117 of file RCOutput.h.
read_last_sent() [2/2]
uint16_t RCOutput::read_last_sent (uint8_t chan) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 116 of file RCOutput.h.
Referenced by Compass_PerMotor::scaled_output().
scale_esc_to_unity()
float RCOutput::scale_esc_to_unity (uint16_t pwm) const
Definition at line 102 of file RCOutput.cpp.
Referenced by Compass_PerMotor::scaled_output().
send_dshot_command()
virtual void AP_HAL::RCOutput::send_dshot_command (uint8_t command, uint8_t chan = ALL_CHANNELS, uint32_t command_timeout_ms = 0, uint16_t repeat_count = 10, bool priority = false) inline virtual
Definition at line 343 of file RCOutput.h.
Referenced by AP_IOMCU_FW::handle_code_write(), and DShotLED::hw_set_rgb().
serial_end()
virtual void AP_HAL::RCOutput::serial_end (void) inline virtual
Definition at line 204 of file RCOutput.h.
serial_led_send()
virtual bool AP_HAL::RCOutput::serial_led_send (const uint16_t chan) inline virtual
Reimplemented in HALSITL::RCOutput.
Definition at line 365 of file RCOutput.h.
serial_read_bytes()
virtual uint16_t AP_HAL::RCOutput::serial_read_bytes (uint8_t * buf, uint16_t len) inline virtual
Definition at line 197 of file RCOutput.h.
serial_setup_output()
virtual bool AP_HAL::RCOutput::serial_setup_output (uint8_t chan, uint32_t baudrate, uint32_t chanmask) inline virtual
Definition at line 185 of file RCOutput.h.
serial_write_bytes()
virtual bool AP_HAL::RCOutput::serial_write_bytes (const uint8_t * bytes, uint16_t len) inline virtual
Definition at line 191 of file RCOutput.h.
set_active_escs_mask()
virtual void AP_HAL::RCOutput::set_active_escs_mask (uint32_t mask) inline virtual
Definition at line 318 of file RCOutput.h.
set_bidir_dshot_mask()
virtual void AP_HAL::RCOutput::set_bidir_dshot_mask (uint32_t mask) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 313 of file RCOutput.h.
Referenced by AP_IOMCU_FW::rcout_config_update().
set_default_rate()
virtual void AP_HAL::RCOutput::set_default_rate (uint16_t rate_hz) inline virtual
Reimplemented in ChibiOS::RCOutput, and ESP32::RCOutput.
Definition at line 301 of file RCOutput.h.
Referenced by SRV_Channels::enable_aux_servos(), and AP_IOMCU_FW::rcin_update().
set_dshot_esc_type()
virtual void AP_HAL::RCOutput::set_dshot_esc_type (DshotEscType esc_type) inline virtual
Definition at line 334 of file RCOutput.h.
Referenced by AP_Motors::rc_set_freq(), AP_IOMCU_FW::rcout_config_update(), and AP_MotorsUGV::setup_pwm_type().
set_dshot_period()
virtual void AP_HAL::RCOutput::set_dshot_period (uint32_t period_us, uint8_t dshot_rate) inline virtual
Definition at line 328 of file RCOutput.h.
Referenced by AP_IOMCU_FW::handle_code_write().
set_dshot_rate()
virtual void AP_HAL::RCOutput::set_dshot_rate (uint8_t dshot_rate, uint16_t loop_rate_hz) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 323 of file RCOutput.h.
Referenced by SRV_Channels::init().
set_esc_scaling()
void AP_HAL::RCOutput::set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm) inline
Definition at line 142 of file RCOutput.h.
Referenced by AP_IOMCU_FW::rcout_config_update(), SRV_Channels::set_esc_scaling_for(), and AP_MotorsMulticopter::update_throttle_range().
set_failsafe_pwm()
virtual void AP_HAL::RCOutput::set_failsafe_pwm (uint32_t chmask, uint16_t period_us) inline virtual
Reimplemented in ChibiOS::RCOutput, and ESP32::RCOutput.
Definition at line 122 of file RCOutput.h.
Referenced by SRV_Channels::set_failsafe_limit(), SRV_Channels::set_failsafe_pwm(), and SRV_Channels::setup_failsafe_trim_all_non_motors().
set_freq()
virtual void AP_HAL::RCOutput::set_freq (uint32_t chmask, uint16_t freq_hz) pure virtual
Implemented in ap::RCOutput_Tap, ChibiOS::RCOutput, Empty::RCOutput, ESP32::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_AioPRU, Linux::RCOutput_Bebop, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, and HALSITL::RCOutput.
Referenced by drive(), RCOutputRGBLed::hw_set_rgb(), AP_Motors::rc_set_freq(), AP_IOMCU_FW::rcin_update(), AP_IOMCU_FW::rcout_config_update(), SRV_Channels::set_rc_frequency(), RC_UART::setup(), and AP_MotorsUGV::setup_pwm_type().
set_motor_poles()
virtual void AP_HAL::RCOutput::set_motor_poles (uint8_t poles) inline virtual
Definition at line 348 of file RCOutput.h.
set_output_mode()
virtual void AP_HAL::RCOutput::set_output_mode (uint32_t mask, enum output_mode mode) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 280 of file RCOutput.h.
Referenced by AP_Motors::rc_set_freq(), AP_IOMCU_FW::rcout_config_update(), and AP_MotorsUGV::setup_pwm_type().
set_reversed_mask()
virtual void AP_HAL::RCOutput::set_reversed_mask (uint32_t chanmask) inline virtual
Definition at line 81 of file RCOutput.h.
set_reversible_mask()
virtual void AP_HAL::RCOutput::set_reversible_mask (uint32_t chanmask) inline virtual
Definition at line 74 of file RCOutput.h.
set_serial_led_num_LEDs()
virtual bool AP_HAL::RCOutput::set_serial_led_num_LEDs (const uint16_t chan, uint8_t num_leds, output_mode mode = MODE_PWM_NONE, uint32_t clock_mask = 0) inline virtual
Reimplemented in HALSITL::RCOutput.
Definition at line 354 of file RCOutput.h.
set_serial_led_rgb_data()
virtual bool AP_HAL::RCOutput::set_serial_led_rgb_data (const uint16_t chan, int8_t led, uint8_t red, uint8_t green, uint8_t blue) inline virtual
Reimplemented in HALSITL::RCOutput.
Definition at line 360 of file RCOutput.h.
set_telem_request_mask()
virtual void AP_HAL::RCOutput::set_telem_request_mask (uint32_t mask) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 307 of file RCOutput.h.
Referenced by AP_IOMCU_FW::handle_code_write().
supports_gpio()
virtual bool AP_HAL::RCOutput::supports_gpio () inline virtual
Reimplemented in Linux::RCOutput_PCA9685.
Definition at line 372 of file RCOutput.h.
Referenced by GPIO_Navigator::read(), and GPIO_Navigator::write().
timer_info()
virtual void AP_HAL::RCOutput::timer_info (ExpandingString & str) inline virtual
Reimplemented in ChibiOS::RCOutput.
Definition at line 367 of file RCOutput.h.
Referenced by ChibiOS::Util::timer_info().
timer_tick()
void RCOutput::timer_tick (void) inline virtual
Reimplemented in ESP32::RCOutput.
Definition at line 172 of file RCOutput.h.
Referenced by ESP32::Scheduler::_rcout_thread(), and AP_IOMCU_FW::update().
update_channel_masks()
virtual void AP_HAL::RCOutput::update_channel_masks () inline virtual
Definition at line 87 of file RCOutput.h.
Referenced by SRV_Channels::enable_aux_servos().
write()
virtual void AP_HAL::RCOutput::write (uint8_t chan, uint16_t period_us) pure virtual
Implemented in ap::RCOutput_Tap, ChibiOS::RCOutput, Empty::RCOutput, Linux::RCOutput_AeroIO, Linux::RCOutput_AioPRU, Linux::RCOutput_Bebop, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, Linux::RCOutput_Sysfs, Linux::RCOutput_ZYNQ, HALSITL::RCOutput, and ESP32::RCOutput.
Referenced by drive(), ReplayGyroFFT::loop(), loop(), RC_UART::loop(), SRV_Channel::output_ch(), AP_IOMCU_FW::pwm_out_update(), and SRV_Channels::zero_rc_outputs().
write_gpio()
virtual void AP_HAL::RCOutput::write_gpio (uint8_t chan, bool active) inline virtual
Reimplemented in Linux::RCOutput_PCA9685.
Definition at line 377 of file RCOutput.h.
Referenced by GPIO_Navigator::write().
Member Data Documentation
_esc_pwm_max
uint16_t AP_HAL::RCOutput::_esc_pwm_max protected
Definition at line 426 of file RCOutput.h.
Referenced by set_esc_scaling().
_esc_pwm_min
uint16_t AP_HAL::RCOutput::_esc_pwm_min protected
Definition at line 425 of file RCOutput.h.
Referenced by set_esc_scaling().
ALL_CHANNELS
const uint32_t AP_HAL::RCOutput::ALL_CHANNELS = 255 static
Definition at line 338 of file RCOutput.h.
DSHOT_BIT_0_TICKS
uint32_t RCOutput::DSHOT_BIT_0_TICKS = DSHOT_BIT_0_TICKS_DEFAULT static
Definition at line 404 of file RCOutput.h.
DSHOT_BIT_0_TICKS_DEFAULT
constexpr uint32_t AP_HAL::RCOutput::DSHOT_BIT_0_TICKS_DEFAULT = 3 static constexpr
Definition at line 396 of file RCOutput.h.
DSHOT_BIT_0_TICKS_S
constexpr uint32_t AP_HAL::RCOutput::DSHOT_BIT_0_TICKS_S = 4 static constexpr
Definition at line 400 of file RCOutput.h.
DSHOT_BIT_1_TICKS
uint32_t RCOutput::DSHOT_BIT_1_TICKS = DSHOT_BIT_1_TICKS_DEFAULT static
Definition at line 405 of file RCOutput.h.
DSHOT_BIT_1_TICKS_DEFAULT
constexpr uint32_t AP_HAL::RCOutput::DSHOT_BIT_1_TICKS_DEFAULT = 6 static constexpr
Definition at line 397 of file RCOutput.h.
DSHOT_BIT_1_TICKS_S
constexpr uint32_t AP_HAL::RCOutput::DSHOT_BIT_1_TICKS_S = 8 static constexpr
Definition at line 401 of file RCOutput.h.
DSHOT_BIT_WIDTH_TICKS
uint32_t RCOutput::DSHOT_BIT_WIDTH_TICKS = DSHOT_BIT_WIDTH_TICKS_DEFAULT static
Definition at line 403 of file RCOutput.h.
Referenced by TEST_P(), TEST_P(), TEST_P(), and TEST_P().
DSHOT_BIT_WIDTH_TICKS_DEFAULT
constexpr uint32_t AP_HAL::RCOutput::DSHOT_BIT_WIDTH_TICKS_DEFAULT = 8 static constexpr
Definition at line 395 of file RCOutput.h.
DSHOT_BIT_WIDTH_TICKS_S
constexpr uint32_t AP_HAL::RCOutput::DSHOT_BIT_WIDTH_TICKS_S = 11 static constexpr
Definition at line 399 of file RCOutput.h.
Referenced by TEST_P(), TEST_P(), TEST_P(), and TEST_P().
DSHOT_ZERO_THROTTLE
const uint8_t AP_HAL::RCOutput::DSHOT_ZERO_THROTTLE = 48
Definition at line 270 of file RCOutput.h.
LED_OUTPUT_PERIOD_US
constexpr uint32_t AP_HAL::RCOutput::LED_OUTPUT_PERIOD_US = 10000 static constexpr
Definition at line 417 of file RCOutput.h.
NEOP_BIT_0_TICKS
constexpr uint32_t AP_HAL::RCOutput::NEOP_BIT_0_TICKS = 3 static constexpr
Definition at line 409 of file RCOutput.h.
Referenced by PrescalerParameterizedTestFixture::test_prescaler_neopixel().
NEOP_BIT_1_TICKS
constexpr uint32_t AP_HAL::RCOutput::NEOP_BIT_1_TICKS = 6 static constexpr
Definition at line 410 of file RCOutput.h.
Referenced by PrescalerParameterizedTestFixture::test_prescaler_neopixel().
NEOP_BIT_WIDTH_TICKS
constexpr uint32_t AP_HAL::RCOutput::NEOP_BIT_WIDTH_TICKS = 8 static constexpr
Definition at line 408 of file RCOutput.h.
Referenced by TEST_P(), and PrescalerParameterizedTestFixture::test_prescaler_neopixel().
PROFI_BIT_0_TICKS
constexpr uint32_t AP_HAL::RCOutput::PROFI_BIT_0_TICKS = 7 static constexpr
Definition at line 412 of file RCOutput.h.
PROFI_BIT_1_TICKS
constexpr uint32_t AP_HAL::RCOutput::PROFI_BIT_1_TICKS = 14 static constexpr
Definition at line 413 of file RCOutput.h.
PROFI_BIT_WIDTH_TICKS
constexpr uint32_t AP_HAL::RCOutput::PROFI_BIT_WIDTH_TICKS = 20 static constexpr
Definition at line 414 of file RCOutput.h.
The documentation for this class was generated from the following files:
libraries/AP_HAL/RCOutput.h
libraries/AP_HAL/RCOutput.cpp
libraries/AP_HAL_ChibiOS/RCOutput.cpp
libraries/AP_HAL_ESP32/RCOutput.cpp