APM:Libraries: AP_RCProtocol_SBUS Class Reference
AP_RCProtocol_SBUS Class Reference
#include <AP_RCProtocol_SBUS.h>
Public Member Functions
AP_RCProtocol_SBUS (AP_RCProtocol &_frontend, bool inverted, uint32_t configured_baud)
void process_pulse (uint32_t width_s0, uint32_t width_s1) override
void process_byte (uint8_t byte, uint32_t baudrate) override
Public Member Functions inherited from AP_RCProtocol_Backend
AP_RCProtocol_Backend (AP_RCProtocol &_frontend)
virtual ~AP_RCProtocol_Backend ()
virtual void process_handshake (uint32_t baudrate)
uint16_t read (uint8_t chan)
void read (uint16_t *pwm, uint8_t n)
bool new_input ()
uint8_t num_channels () const
virtual void start_bind (void)
virtual void update (void)
uint32_t get_rc_frame_count (void) const
void reset_rc_frame_count (void)
uint32_t get_rc_input_count (void) const
uint32_t get_rc_protocols_mask (void) const
bool protocol_enabled (enum AP_RCProtocol::rcprotocol_t protocol) const
int16_t get_RSSI (void) const
int16_t get_rx_link_quality (void) const
AP_HAL::UARTDriver * get_UART (void) const
AP_HAL::UARTDriver * get_available_UART (void) const
bool have_UART (void) const
virtual bool is_rx_active () const
bool is_detected () const
Static Public Member Functions
static bool sbus_decode (const uint8_t frame[25], uint16_t *values, uint16_t *num_values, bool &sbus_failsafe, uint16_t max_values)
Private Member Functions
void _process_byte (uint32_t timestamp_us, uint8_t byte)
Private Attributes
bool inverted
SoftSerial ss
uint32_t saved_width
struct {
uint8_t buf [25]
uint8_t ofs
uint32_t last_byte_us
} byte_input
Additional Inherited Members
Protected Member Functions inherited from AP_RCProtocol_Backend
void add_input (uint8_t num_channels, uint16_t *values, bool in_failsafe, int16_t rssi=-1, int16_t rx_link_quality=-1)
void log_data (AP_RCProtocol::rcprotocol_t prot, uint32_t timestamp, const uint8_t *data, uint8_t len) const
Static Protected Member Functions inherited from AP_RCProtocol_Backend
static void decode_11bit_channels (const uint8_t *data, uint8_t nchannels, uint16_t *values, uint16_t mult, uint16_t div, uint16_t offset)
Protected Attributes inherited from AP_RCProtocol_Backend
struct AP_RCProtocol_Backend::Channels11Bit_8Chan PACKED
AP_RCProtocol & frontend
Detailed Description
Definition at line 27 of file AP_RCProtocol_SBUS.h.
Constructor & Destructor Documentation
AP_RCProtocol_SBUS()
AP_RCProtocol_SBUS::AP_RCProtocol_SBUS (AP_RCProtocol & _frontend, bool inverted, uint32_t configured_baud)
Definition at line 83 of file AP_RCProtocol_SBUS.cpp.
Member Function Documentation
_process_byte()
void AP_RCProtocol_SBUS::_process_byte (uint32_t timestamp_us, uint8_t byte) private
Definition at line 170 of file AP_RCProtocol_SBUS.cpp.
Referenced by process_byte(), and process_pulse().
process_byte()
void AP_RCProtocol_SBUS::process_byte (uint8_t byte, uint32_t baudrate) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 206 of file AP_RCProtocol_SBUS.cpp.
process_pulse()
void AP_RCProtocol_SBUS::process_pulse (uint32_t width_s0, uint32_t width_s1) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 154 of file AP_RCProtocol_SBUS.cpp.
sbus_decode()
bool AP_RCProtocol_SBUS::sbus_decode (const uint8_t frame[25], uint16_t * values, uint16_t * num_values, bool & sbus_failsafe, uint16_t max_values) static
Definition at line 90 of file AP_RCProtocol_SBUS.cpp.
Referenced by _process_byte(), Linux::RCInput::_process_sbus_pulse(), Linux::RCInput::add_sbus_input(), and TEST().
Member Data Documentation
buf
uint8_t AP_RCProtocol_SBUS::buf[25]
Definition at line 44 of file AP_RCProtocol_SBUS.h.
[struct]
struct { ... } AP_RCProtocol_SBUS::byte_input
Referenced by _process_byte().
inverted
bool AP_RCProtocol_SBUS::inverted private
Definition at line 39 of file AP_RCProtocol_SBUS.h.
Referenced by process_pulse().
last_byte_us
uint32_t AP_RCProtocol_SBUS::last_byte_us
Definition at line 46 of file AP_RCProtocol_SBUS.h.
ofs
uint8_t AP_RCProtocol_SBUS::ofs
Definition at line 45 of file AP_RCProtocol_SBUS.h.
saved_width
uint32_t AP_RCProtocol_SBUS::saved_width private
Definition at line 41 of file AP_RCProtocol_SBUS.h.
Referenced by process_pulse().
ss
SoftSerial AP_RCProtocol_SBUS::ss private
Definition at line 40 of file AP_RCProtocol_SBUS.h.
Referenced by process_byte(), and process_pulse().
The documentation for this class was generated from the following files:
libraries/AP_RCProtocol/AP_RCProtocol_SBUS.h
libraries/AP_RCProtocol/AP_RCProtocol_SBUS.cpp