APM:Libraries: QuaternionT< T > Class Template Reference
QuaternionT< T > Class Template Reference
#include <quaternion.h>
Public Member Functions
QuaternionT ()
QuaternionT (const T _q1, const T _q2, const T _q3, const T _q4)
QuaternionT (const T _q[4])
void operator() (const T _q1, const T _q2, const T _q3, const T _q4)
bool is_nan (void) const WARN_IF_UNUSED
void rotation_matrix (Matrix3f &m) const
void rotation_matrix (Matrix3d &m) const
void from_rotation_matrix (const Matrix3< T > &m)
void from_rotation (enum Rotation rotation)
void rotate (enum Rotation rotation)
void earth_to_body (Vector3< T > &v) const
void from_euler (T roll, T pitch, T yaw)
void from_euler (const Vector3< T > &v)
void from_vector312 (T roll, T pitch, T yaw)
void to_axis_angle (Vector3< T > &v) const
void from_axis_angle (Vector3< T > v)
void from_axis_angle (const Vector3< T > &axis, T theta)
void rotate (const Vector3< T > &v)
void from_axis_angle_fast (Vector3< T > v)
void from_axis_angle_fast (const Vector3< T > &axis, T theta)
void from_angular_velocity (const Vector3< T > &angular_velocity, float time_delta)
void rotate_fast (const Vector3< T > &v)
T get_euler_roll () const
T get_euler_pitch () const
T get_euler_yaw () const
void to_euler (float &roll, float &pitch, float &yaw) const
void to_euler (Vector3f &rpy) const
void to_euler (double &roll, double &pitch, double &yaw) const
void to_euler (Vector3d &rpy) const
Vector3< T > to_vector312 (void) const
T length_squared (void) const
T length (void) const
void normalize ()
bool is_zero (void) const
void zero (void)
bool is_unit_length (void) const
void initialise ()
QuaternionT< T > inverse (void) const
void invert ()
T & operator[] (uint8_t i)
const T & operator[] (uint8_t i) const
QuaternionT< T > operator* (const QuaternionT< T > &v) const
Vector3< T > operator* (const Vector3< T > &v) const
QuaternionT< T > & operator*= (const QuaternionT< T > &v)
QuaternionT< T > operator/ (const QuaternionT< T > &v) const
QuaternionT< T > angular_difference (const QuaternionT< T > &v) const
T roll_pitch_difference (const QuaternionT< T > &v) const
QuaternionT< double > todouble (void) const
QuaternionT< float > tofloat (void) const
Public Attributes
T q1
T q2
T q3
T q4
Detailed Description
template<typename T>
class QuaternionT< T >
Definition at line 29 of file quaternion.h.
Constructor & Destructor Documentation
QuaternionT() [1/3]
template<typename T > QuaternionT< T >::QuaternionT () inline
Definition at line 35 of file quaternion.h.
QuaternionT() [2/3]
template<typename T > QuaternionT< T >::QuaternionT (const T _q1, const T _q2, const T _q3, const T _q4) inline
Definition at line 42 of file quaternion.h.
QuaternionT() [3/3]
template<typename T > QuaternionT< T >::QuaternionT (const T _q[4]) inline
Definition at line 48 of file quaternion.h.
Member Function Documentation
angular_difference()
template<typename T > QuaternionT< T > QuaternionT< T >::angular_difference (const QuaternionT< T > & v) const
Definition at line 803 of file quaternion.cpp.
Referenced by AP_AHRS::attitudes_consistent().
earth_to_body()
template<typename T > void QuaternionT< T >::earth_to_body (Vector3< T > & v) const
Definition at line 412 of file quaternion.cpp.
Referenced by test_frame_transforms().
from_angular_velocity()
template<typename T > void QuaternionT< T >::from_angular_velocity (const Vector3< T > & angular_velocity, float time_delta)
Definition at line 540 of file quaternion.cpp.
from_axis_angle() [1/2]
template<typename T > void QuaternionT< T >::from_axis_angle (const Vector3< T > & axis, T theta)
Definition at line 469 of file quaternion.cpp.
from_axis_angle() [2/2]
template<typename T > void QuaternionT< T >::from_axis_angle (Vector3< T > v)
Definition at line 454 of file quaternion.cpp.
Referenced by AC_AttitudeControl::attitude_controller_run_quat(), AC_AttitudeControl::attitude_from_thrust_vector(), NavEKF2_core::calcOutputStates(), NavEKF3_core::calcOutputStates(), AC_AttitudeControl::input_angle_step_bf_roll_pitch_yaw(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_3(), AC_AttitudeControl::input_thrust_vector_rate_heading(), AC_AttitudeControl_TS::relax_attitude_controllers(), AC_AttitudeControl::reset_yaw_target_and_rate(), QuaternionT< T >::rotate(), AC_AttitudeControl::thrust_heading_rotation_angles(), and AC_AttitudeControl::thrust_vector_rotation_angles().
from_axis_angle_fast() [1/2]
template<typename T > void QuaternionT< T >::from_axis_angle_fast (const Vector3< T > & axis, T theta)
Definition at line 525 of file quaternion.cpp.
from_axis_angle_fast() [2/2]
template<typename T > void QuaternionT< T >::from_axis_angle_fast (Vector3< T > v)
Definition at line 510 of file quaternion.cpp.
from_euler() [1/2]
template<typename T > void QuaternionT< T >::from_euler (const Vector3< T > & v)
Definition at line 436 of file quaternion.cpp.
from_euler() [2/2]
template<typename T > void QuaternionT< T >::from_euler (T roll, T pitch, T yaw)
Definition at line 421 of file quaternion.cpp.
Referenced by SITL::Calibration::_attitude_set(), NavEKF2_core::calcQuatAndFieldStates(), NavEKF2_core::controlMagYawReset(), AP_Mount_Alexmos::get_attitude_quaternion(), AP_Mount_Servo::get_attitude_quaternion(), AP_Mount_SToRM32_serial::get_attitude_quaternion(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), AC_AttitudeControl::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl::input_euler_angle_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), NavEKF3_core::learnMagBiasFromGPS(), NavEKF2_core::realignYawGPS(), NavEKF2_core::resetQuatStateYawOnly(), NavEKF3_core::resetQuatStateYawOnly(), test_conversion(), test_euler(), test_euler(), test_frame_transforms(), test_quaternion(), and SITL::Vicon::update_vicon_position_estimate().
from_rotation()
template<typename T > void QuaternionT< T >::from_rotation (enum Rotation rotation)
Definition at line 133 of file quaternion.cpp.
Referenced by QuaternionT< T >::rotate(), test_euler(), and test_euler().
from_rotation_matrix()
template<typename T > void QuaternionT< T >::from_rotation_matrix (const Matrix3< T > & m)
Definition at line 86 of file quaternion.cpp.
Referenced by SITL::Calibration::_attitude_set(), AP_AHRS::attitudes_consistent(), AP_AHRS::get_quat_body_to_ned(), AP_AHRS_View::get_quat_body_to_ned(), NavEKF2::getQuaternionBodyToNED(), NavEKF3::getQuaternionBodyToNED(), AP_CustomRotation::init(), and test_quaternion().
from_vector312()
template<typename T > void QuaternionT< T >::from_vector312 (T roll, T pitch, T yaw)
Definition at line 444 of file quaternion.cpp.
Referenced by AP_Mount_Siyi::get_attitude_quaternion(), NavEKF3_core::learnMagBiasFromGPS(), NavEKF2_core::resetQuatStateYawOnly(), and NavEKF3_core::resetQuatStateYawOnly().
get_euler_pitch()
template<typename T > T QuaternionT< T >::get_euler_pitch () const
Definition at line 594 of file quaternion.cpp.
Referenced by AP_InertialSensor::_acal_save_calibrations(), and SITL::Vicon::update_vicon_position_estimate().
get_euler_roll()
template<typename T > T QuaternionT< T >::get_euler_roll () const
Definition at line 587 of file quaternion.cpp.
Referenced by AP_InertialSensor::_acal_save_calibrations(), and SITL::Vicon::update_vicon_position_estimate().
get_euler_yaw()
template<typename T > T QuaternionT< T >::get_euler_yaw () const
Definition at line 601 of file quaternion.cpp.
Referenced by SITL::Vicon::update_vicon_position_estimate().
initialise()
template<typename T > void QuaternionT< T >::initialise () inline
Definition at line 162 of file quaternion.h.
Referenced by NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariablesMag(), and AC_AttitudeControl::relax_attitude_controllers().
inverse()
template<typename T > QuaternionT< T > QuaternionT< T >::inverse (void) const
Definition at line 647 of file quaternion.cpp.
Referenced by QuaternionT< T >::angular_difference(), AC_AttitudeControl::attitude_controller_run_quat(), NavEKF3_core::CovariancePrediction(), NavEKF2_core::getAirSpdVec(), NavEKF3_core::getAirSpdVec(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl_TS::relax_attitude_controllers(), NavEKF3_core::resetMagFieldStates(), NavEKF2_core::resetQuatStateYawOnly(), NavEKF3_core::resetQuatStateYawOnly(), TEST(), TEST(), AC_AttitudeControl::thrust_vector_rotation_angles(), SITL::Vicon::update_vicon_position_estimate(), NavEKF2_core::UpdateStrapdownEquationsNED(), NavEKF3_core::UpdateStrapdownEquationsNED(), and NavEKF3_core::verifyTiltErrorVariance().
invert()
template<typename T > void QuaternionT< T >::invert ()
Definition at line 654 of file quaternion.cpp.
Referenced by SITL::Vicon::update_vicon_position_estimate().
is_nan()
template<typename T > bool QuaternionT< T >::is_nan (void) const inline
Definition at line 63 of file quaternion.h.
Referenced by NavEKF2_core::getFilterFaults(), NavEKF3_core::getFilterFaults(), NavEKF2_core::updateFilterStatus(), NavEKF3_core::updateFilterStatus(), NavEKF2_core::writeExtNavData(), and NavEKF3_core::writeExtNavData().
is_unit_length()
template<typename T > bool QuaternionT< T >::is_unit_length (void) const
Definition at line 695 of file quaternion.cpp.
is_zero()
template<typename T > bool QuaternionT< T >::is_zero (void) const
Definition at line 679 of file quaternion.cpp.
length()
template<typename T > T QuaternionT< T >::length (void) const
Definition at line 633 of file quaternion.cpp.
length_squared()
template<typename T > T QuaternionT< T >::length_squared (void) const
Definition at line 640 of file quaternion.cpp.
normalize()
template<typename T > void QuaternionT< T >::normalize (void)
Definition at line 662 of file quaternion.cpp.
Referenced by AP_InertialSensor::_acal_save_calibrations(), SITL::Calibration::_attitude_set(), AC_AttitudeControl::attitude_controller_run_quat(), NavEKF2_core::calcOutputStates(), NavEKF3_core::calcOutputStates(), NavEKF3_core::FuseAirspeed(), NavEKF3_core::FuseDeclination(), NavEKF3_core::fuseEulerYaw(), NavEKF3_core::FuseMagnetometer(), NavEKF3_core::FuseOptFlow(), NavEKF3_core::FuseSideslip(), NavEKF3_core::FuseVelPosNED(), AC_AttitudeControl::input_angle_step_bf_roll_pitch_yaw(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_3(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), AC_AttitudeControl_TS::relax_attitude_controllers(), test_frame_transforms(), NavEKF2_core::UpdateStrapdownEquationsNED(), and NavEKF3_core::UpdateStrapdownEquationsNED().
operator()()
template<typename T > void QuaternionT< T >::operator() (const T _q1, const T _q2, const T _q3, const T _q4) inline
Definition at line 54 of file quaternion.h.
operator*() [1/2]
template<typename T > QuaternionT< T > QuaternionT< T >::operator* (const QuaternionT< T > & v) const
Definition at line 705 of file quaternion.cpp.
operator*() [2/2]
template<typename T > Vector3< T > QuaternionT< T >::operator* (const Vector3< T > & v) const
Definition at line 731 of file quaternion.cpp.
operator*=()
template<typename T > QuaternionT< T > & QuaternionT< T >::operator*= (const QuaternionT< T > & v)
Definition at line 755 of file quaternion.cpp.
operator/()
template<typename T > QuaternionT< T > QuaternionT< T >::operator/ (const QuaternionT< T > & v) const
Definition at line 776 of file quaternion.cpp.
operator[]() [1/2]
template<typename T > T & QuaternionT< T >::operator[] (uint8_t i) inline
Definition at line 174 of file quaternion.h.
operator[]() [2/2]
template<typename T > const T & QuaternionT< T >::operator[] (uint8_t i) const inline
Definition at line 183 of file quaternion.h.
roll_pitch_difference()
template<typename T > T QuaternionT< T >::roll_pitch_difference (const QuaternionT< T > & v) const
Definition at line 810 of file quaternion.cpp.
Referenced by AP_AHRS::attitudes_consistent().
rotate() [1/2]
template<typename T > void QuaternionT< T >::rotate (const Vector3< T > & v)
Definition at line 487 of file quaternion.cpp.
rotate() [2/2]
template<typename T > void QuaternionT< T >::rotate (enum Rotation rotation)
Definition at line 400 of file quaternion.cpp.
Referenced by AP_AHRS::_get_quaternion(), AP_AHRS::_get_secondary_quaternion(), NavEKF2_core::FuseAirspeed(), NavEKF2_core::FuseDeclination(), NavEKF2_core::fuseEulerYaw(), NavEKF2_core::FuseMagnetometer(), NavEKF2_core::FuseOptFlow(), NavEKF2_core::FuseSideslip(), NavEKF2_core::FuseVelPosNED(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), NavEKF2_core::UpdateStrapdownEquationsNED(), and NavEKF3_core::UpdateStrapdownEquationsNED().
rotate_fast()
template<typename T > void QuaternionT< T >::rotate_fast (const Vector3< T > & v)
Definition at line 555 of file quaternion.cpp.
rotation_matrix() [1/2]
template<typename T > void QuaternionT< T >::rotation_matrix (Matrix3d & m) const
Definition at line 34 of file quaternion.cpp.
rotation_matrix() [2/2]
template<typename T > void QuaternionT< T >::rotation_matrix (Matrix3f & m) const
Definition at line 59 of file quaternion.cpp.
Referenced by NavEKF2_core::calcOutputStates(), NavEKF3_core::calcOutputStates(), NavEKF2_core::calcQuatAndFieldStates(), NavEKF3_core::CovariancePrediction(), NavEKF2_core::getAirSpdVec(), NavEKF3_core::getAirSpdVec(), NavEKF2_core::getRotationBodyToNED(), NavEKF3_core::getRotationBodyToNED(), NavEKF3_core::learnMagBiasFromGPS(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), SITL::Gazebo::recv_fdm(), NavEKF3_core::resetMagFieldStates(), NavEKF2_core::resetQuatStateYawOnly(), NavEKF3_core::resetQuatStateYawOnly(), TEST(), TEST(), TEST(), TEST(), test_conversion(), test_quaternion(), SITL::FlightAxis::update(), SITL::Vicon::update_vicon_position_estimate(), NavEKF2_core::UpdateStrapdownEquationsNED(), NavEKF3_core::UpdateStrapdownEquationsNED(), NavEKF3_core::verifyTiltErrorVariance(), and NavEKF2_core::writeOptFlowMeas().
to_axis_angle()
template<typename T > void QuaternionT< T >::to_axis_angle (Vector3< T > & v) const
Definition at line 497 of file quaternion.cpp.
Referenced by SITL::Calibration::_attitude_set(), AP_AHRS::attitudes_consistent(), NavEKF2_core::controlMagYawReset(), NavEKF3_core::controlMagYawReset(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_3(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), and AC_AttitudeControl::thrust_vector_rotation_angles().
to_euler() [1/4]
template<typename T > void QuaternionT< T >::to_euler (double & roll, double & pitch, double & yaw) const
Definition at line 608 of file quaternion.cpp.
to_euler() [2/4]
template<typename T > void QuaternionT< T >::to_euler (float & roll, float & pitch, float & yaw) const
Definition at line 616 of file quaternion.cpp.
Referenced by NavEKF2_core::calcQuatAndFieldStates(), NavEKF2_core::controlMagYawReset(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), AP_Mount::get_attitude_euler(), NavEKF2_core::getEulerAngles(), NavEKF3_core::getEulerAngles(), AP_Follow::handle_msg(), AC_AttitudeControl::inertial_frame_reset(), AC_AttitudeControl::input_angle_step_bf_roll_pitch_yaw(), AC_AttitudeControl::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl::input_euler_angle_roll_pitch_yaw(), AC_AttitudeControl::input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl::input_quaternion(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_2(), AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_3(), AC_AttitudeControl::input_thrust_vector_heading(), AC_AttitudeControl::input_thrust_vector_rate_heading(), NavEKF3_core::learnMagBiasFromGPS(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), AC_AttitudeControl::relax_attitude_controllers(), AC_AttitudeControl_TS::relax_attitude_controllers(), AC_AttitudeControl::reset_target_and_rate(), NavEKF2_core::resetQuatStateYawOnly(), NavEKF3_core::resetQuatStateYawOnly(), NavEKF2_core::setWindMagStateLearningMode(), NavEKF3_core::setWindMagStateLearningMode(), NavEKF3_core::setYawFromMag(), test_conversion(), test_euler(), test_euler(), test_quaternion(), QuaternionT< T >::to_euler(), QuaternionT< T >::to_euler(), SITL::Vicon::update_vicon_position_estimate(), and NavEKF3_core::writeExtNavData().
to_euler() [3/4]
template<typename T > void QuaternionT< T >::to_euler (Vector3d & rpy) const inline
Definition at line 138 of file quaternion.h.
to_euler() [4/4]
template<typename T > void QuaternionT< T >::to_euler (Vector3f & rpy) const inline
Definition at line 134 of file quaternion.h.
to_vector312()
template<typename T > Vector3< T > QuaternionT< T >::to_vector312 (void) const
Definition at line 625 of file quaternion.cpp.
Referenced by NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), NavEKF3_core::learnMagBiasFromGPS(), NavEKF2_core::resetQuatStateYawOnly(), NavEKF3_core::resetQuatStateYawOnly(), and NavEKF3_core::setYawFromMag().
todouble()
template<typename T > QuaternionT< double > QuaternionT< T >::todouble (void) const inline
Definition at line 204 of file quaternion.h.
Referenced by AP_CustomRotations::from_rotation().
tofloat()
template<typename T > QuaternionT< float > QuaternionT< T >::tofloat (void) const inline
Definition at line 207 of file quaternion.h.
Referenced by NavEKF2_core::getQuaternion(), and NavEKF3_core::getQuaternion().
zero()
template<typename T > void QuaternionT< T >::zero (void)
Definition at line 686 of file quaternion.cpp.
Referenced by TEST().
Member Data Documentation
q1
template<typename T > T QuaternionT< T >::q1
Definition at line 31 of file quaternion.h.
Referenced by QuaternionT< T >::initialise(), QuaternionT< T >::is_nan(), QuaternionT< T >::operator()(), QuaternionT< T >::operator*(), QuaternionT< T >::operator*=(), QuaternionT< T >::operator/(), QuaternionT< T >::operator[](), QuaternionT< T >::operator[](), QuaternionT< T >::QuaternionT(), GCS_MAVLINK::send_attitude_quaternion(), GCS_MAVLINK::send_autopilot_state_for_gimbal_device(), QuaternionT< T >::todouble(), and QuaternionT< T >::tofloat().
q2
template<typename T > T QuaternionT< T >::q2
Definition at line 31 of file quaternion.h.
Referenced by QuaternionT< T >::initialise(), QuaternionT< T >::is_nan(), QuaternionT< T >::operator()(), QuaternionT< T >::operator*(), QuaternionT< T >::operator/(), QuaternionT< T >::QuaternionT(), GCS_MAVLINK::send_attitude_quaternion(), GCS_MAVLINK::send_autopilot_state_for_gimbal_device(), TEST(), TEST(), QuaternionT< T >::todouble(), and QuaternionT< T >::tofloat().
q3
template<typename T > T QuaternionT< T >::q3
Definition at line 31 of file quaternion.h.
Referenced by QuaternionT< T >::initialise(), QuaternionT< T >::is_nan(), QuaternionT< T >::operator()(), QuaternionT< T >::operator*(), QuaternionT< T >::operator/(), QuaternionT< T >::QuaternionT(), GCS_MAVLINK::send_attitude_quaternion(), GCS_MAVLINK::send_autopilot_state_for_gimbal_device(), TEST(), TEST(), QuaternionT< T >::todouble(), and QuaternionT< T >::tofloat().
q4
template<typename T > T QuaternionT< T >::q4
Definition at line 31 of file quaternion.h.
Referenced by QuaternionT< T >::initialise(), QuaternionT< T >::is_nan(), QuaternionT< T >::operator()(), QuaternionT< T >::operator*(), QuaternionT< T >::operator/(), QuaternionT< T >::QuaternionT(), GCS_MAVLINK::send_attitude_quaternion(), GCS_MAVLINK::send_autopilot_state_for_gimbal_device(), TEST(), TEST(), QuaternionT< T >::todouble(), and QuaternionT< T >::tofloat().
The documentation for this class was generated from the following files:
libraries/AP_Math/quaternion.h
libraries/AP_Math/quaternion.cpp