APM:Libraries: AP_BattMonitor_SMBus_SUI Class Reference
AP_BattMonitor_SMBus_SUI Class Reference
#include <AP_BattMonitor_SMBus_SUI.h>
Public Member Functions
AP_BattMonitor_SMBus_SUI (AP_BattMonitor &mon, AP_BattMonitor::BattMonitor_State &mon_state, AP_BattMonitor_Params &params, uint8_t cell_count)
void init (void) override
Public Member Functions inherited from AP_BattMonitor_SMBus
AP_BattMonitor_SMBus (AP_BattMonitor &mon, AP_BattMonitor::BattMonitor_State &mon_state, AP_BattMonitor_Params &params, uint8_t i2c_bus)
Constructor.
virtual ~AP_BattMonitor_SMBus ()
bool has_cell_voltages () const override
bool has_temperature () const override
bool has_current () const override
returns true if battery monitor instance provides current info
bool reset_remaining (float percentage) override
bool get_cycle_count (uint16_t &cycles) const override
Public Member Functions inherited from AP_BattMonitor_Backend
AP_BattMonitor_Backend (AP_BattMonitor &mon, AP_BattMonitor::BattMonitor_State &mon_state, AP_BattMonitor_Params &params)
virtual ~AP_BattMonitor_Backend (void)
virtual bool has_time_remaining () const
returns true if battery monitor instance provides time remaining info
virtual bool has_consumed_energy () const
returns true if battery monitor instance provides consumed energy info
virtual bool get_temperature (float &temperature) const
virtual bool capacity_remaining_pct (uint8_t &percentage) const WARN_IF_UNUSED
bool get_state_of_health_pct (uint8_t &soh_pct) const
float voltage_resting_estimate () const
virtual void update_resistance_estimate ()
virtual AP_BattMonitor::Failsafe update_failsafes (void)
bool arming_checks (char *buffer, size_t buflen) const
virtual uint32_t get_mavlink_fault_bitmask () const
void Log_Write_BAT (const uint8_t instance, const uint64_t time_us) const
void Log_Write_BCL (const uint8_t instance, const uint64_t time_us) const
virtual void mppt_set_powered_state (bool power_on)
void update_esc_telem_outbound ()
bool option_is_set (const AP_BattMonitor_Params::Options option) const
Private Member Functions
void timer (void) override
void read_cell_voltages ()
void update_health ()
bool read_block_bare (uint8_t reg, uint8_t *data, uint8_t len) const
Private Attributes
const uint8_t cell_count
bool phase_voltages
uint32_t last_volt_read_us
Additional Inherited Members
Public Types inherited from AP_BattMonitor_SMBus
enum BATTMONITOR_SMBUS {
BATTMONITOR_SMBUS_TEMP = 0x08 , BATTMONITOR_SMBUS_VOLTAGE = 0x09 , BATTMONITOR_SMBUS_CURRENT = 0x0A , BATTMONITOR_SMBUS_REMAINING_CAPACITY = 0x0F ,
BATTMONITOR_SMBUS_FULL_CHARGE_CAPACITY = 0x10 , BATTMONITOR_SMBUS_CYCLE_COUNT = 0x17 , BATTMONITOR_SMBUS_SPECIFICATION_INFO = 0x1A , BATTMONITOR_SMBUS_SERIAL = 0x1C ,
BATTMONITOR_SMBUS_MANUFACTURE_NAME = 0x20 , BATTMONITOR_SMBUS_MANUFACTURE_DATA = 0x23
}
Static Public Member Functions inherited from AP_BattMonitor_Backend
static float calculate_mah (float amps, float dt_us)
Static Public Attributes inherited from AP_BattMonitor_SMBus
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions inherited from AP_BattMonitor_SMBus
void read (void) override
read the battery_voltage and current, should be called at 10hz
void read_full_charge_capacity (void)
void read_remaining_capacity (void)
virtual uint16_t get_capacity_scaler () const
virtual void read_temp (void)
void read_serial_number (void)
void read_cycle_count ()
bool read_word (uint8_t reg, uint16_t &data) const
uint8_t read_block (uint8_t reg, uint8_t *data, uint8_t len) const
uint8_t get_PEC (const uint8_t i2c_addr, uint8_t cmd, bool reading, const uint8_t buff[], uint8_t len) const
get_PEC - calculate packet error correction code of buffer
Protected Member Functions inherited from AP_BattMonitor_Backend
void check_failsafe_types (bool &low_voltage, bool &low_capacity, bool &critical_voltage, bool &critical_capacity) const
void update_consumed (AP_BattMonitor::BattMonitor_State &state, uint32_t dt_us)
Protected Attributes inherited from AP_BattMonitor_SMBus
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
bool _pec_supported
int32_t _serial_number = -1
uint16_t _full_charge_capacity
bool _has_cell_voltages
uint16_t _cycle_count = 0
bool _has_cycle_count
bool _has_temperature
AP_HAL::Device::PeriodicHandle timer_handle
AP_Int8 _bus
AP_Int8 _address
Protected Attributes inherited from AP_BattMonitor_Backend
AP_BattMonitor & _mon
AP_BattMonitor::BattMonitor_State & _state
AP_BattMonitor_Params & _params
Detailed Description
Definition at line 8 of file AP_BattMonitor_SMBus_SUI.h.
Constructor & Destructor Documentation
AP_BattMonitor_SMBus_SUI()
AP_BattMonitor_SMBus_SUI::AP_BattMonitor_SMBus_SUI (AP_BattMonitor & mon, AP_BattMonitor::BattMonitor_State & mon_state, AP_BattMonitor_Params & params, uint8_t cell_count)
Definition at line 21 of file AP_BattMonitor_SMBus_SUI.cpp.
Member Function Documentation
init()
void AP_BattMonitor_SMBus_SUI::init (void) override virtual
Reimplemented from AP_BattMonitor_SMBus.
Definition at line 31 of file AP_BattMonitor_SMBus_SUI.cpp.
read_block_bare()
bool AP_BattMonitor_SMBus_SUI::read_block_bare (uint8_t reg, uint8_t * data, uint8_t len) const private
Definition at line 73 of file AP_BattMonitor_SMBus_SUI.cpp.
Referenced by timer().
read_cell_voltages()
void AP_BattMonitor_SMBus_SUI::read_cell_voltages () private
Definition at line 84 of file AP_BattMonitor_SMBus_SUI.cpp.
Referenced by timer().
timer()
void AP_BattMonitor_SMBus_SUI::timer (void) override private virtual
Implements AP_BattMonitor_SMBus.
Definition at line 43 of file AP_BattMonitor_SMBus_SUI.cpp.
update_health()
void AP_BattMonitor_SMBus_SUI::update_health () private
Definition at line 133 of file AP_BattMonitor_SMBus_SUI.cpp.
Referenced by timer().
Member Data Documentation
cell_count
const uint8_t AP_BattMonitor_SMBus_SUI::cell_count private
Definition at line 29 of file AP_BattMonitor_SMBus_SUI.h.
Referenced by read_cell_voltages().
last_volt_read_us
uint32_t AP_BattMonitor_SMBus_SUI::last_volt_read_us private
Definition at line 31 of file AP_BattMonitor_SMBus_SUI.h.
Referenced by read_cell_voltages(), and update_health().
phase_voltages
bool AP_BattMonitor_SMBus_SUI::phase_voltages private
Definition at line 30 of file AP_BattMonitor_SMBus_SUI.h.
Referenced by timer().
The documentation for this class was generated from the following files:
libraries/AP_BattMonitor/AP_BattMonitor_SMBus_SUI.h
libraries/AP_BattMonitor/AP_BattMonitor_SMBus_SUI.cpp