APM:Libraries: AP_Scheduler Class Reference
AP_Scheduler Class Reference
#include <AP_Scheduler.h>
Classes
struct Task
Public Types
enum class Options : uint8_t { RECORD_TASK_INFO = 1 << 0 }
enum FastTaskPriorities { FAST_TASK_PRI0 = 0 , FAST_TASK_PRI1 = 1 , FAST_TASK_PRI2 = 2 , MAX_FAST_TASK_PRIORITIES = 3 }
Public Member Functions
AP_Scheduler ()
CLASS_NO_COPY (AP_Scheduler)
FUNCTOR_TYPEDEF (task_fn_t, void)
void init (const Task *tasks, uint8_t num_tasks, uint32_t log_performance_bit)
void loop ()
void update_logging ()
void Log_Write_Performance ()
void tick (void)
uint16_t ticks () const
uint32_t ticks32 () const
void run (uint32_t time_available)
uint16_t time_available_usec (void) const
uint8_t debug_flags (void)
float load_average ()
uint16_t get_loop_rate_hz (void)
uint32_t get_loop_period_us ()
float get_loop_period_s ()
float get_filtered_loop_time (void) const
float get_filtered_loop_rate_hz ()
float get_last_loop_time_s (void) const
uint32_t get_extra_loop_us (void) const
HAL_Semaphore & get_semaphore (void)
void task_info (ExpandingString &str)
Static Public Member Functions
static AP_Scheduler * get_singleton ()
Public Attributes
AP::PerfInfo perf_info
Static Public Attributes
static AP_Scheduler * _singleton
static const struct AP_Param::GroupInfo var_info []
Private Attributes
AP_Int8 _debug
AP_Int16 _loop_rate_hz
AP_Int16 _active_loop_rate_hz
AP_Int8 _options
uint16_t _loop_period_us
float _loop_period_s
const struct Task * _vehicle_tasks
uint8_t _num_vehicle_tasks
const struct Task * _common_tasks
uint8_t _num_common_tasks
uint8_t _num_tasks
uint16_t _tick_counter
uint32_t _tick_counter32
uint16_t * _last_run
uint32_t _task_time_allowed
uint32_t _task_time_started
uint32_t _spare_micros
uint8_t _spare_ticks
uint32_t _loop_timer_start_us
float _last_loop_time_s
uint32_t _log_performance_bit
const uint8_t max_task_slowdown = 4
uint32_t task_not_achieved
uint32_t task_all_achieved
uint32_t extra_loop_us
HAL_Semaphore _rsem
Detailed Description
Definition at line 72 of file AP_Scheduler.h.
Member Enumeration Documentation
FastTaskPriorities
enum AP_Scheduler::FastTaskPriorities
Enumerator
FAST_TASK_PRI0
FAST_TASK_PRI1
FAST_TASK_PRI2
MAX_FAST_TASK_PRIORITIES
Definition at line 97 of file AP_Scheduler.h.
Options
enum class AP_Scheduler::Options : uint8_t strong
Enumerator
RECORD_TASK_INFO
Definition at line 93 of file AP_Scheduler.h.
Constructor & Destructor Documentation
AP_Scheduler()
AP_Scheduler::AP_Scheduler ()
Definition at line 78 of file AP_Scheduler.cpp.
Member Function Documentation
CLASS_NO_COPY()
AP_Scheduler::CLASS_NO_COPY (AP_Scheduler)
debug_flags()
uint8_t AP_Scheduler::debug_flags (void) inline
Definition at line 133 of file AP_Scheduler.h.
FUNCTOR_TYPEDEF()
AP_Scheduler::FUNCTOR_TYPEDEF (task_fn_t , void)
get_extra_loop_us()
uint32_t AP_Scheduler::get_extra_loop_us (void) const inline
Definition at line 178 of file AP_Scheduler.h.
get_filtered_loop_rate_hz()
float AP_Scheduler::get_filtered_loop_rate_hz () inline
Definition at line 168 of file AP_Scheduler.h.
Referenced by load_average(), AC_AttitudeControl_Heli::set_inverted_flight(), and AP_Arming::system_checks().
get_filtered_loop_time()
float AP_Scheduler::get_filtered_loop_time (void) const inline
Definition at line 163 of file AP_Scheduler.h.
Referenced by AC_AttitudeControl::max_rate_step_bf_pitch(), AC_AttitudeControl::max_rate_step_bf_roll(), and AC_AttitudeControl::max_rate_step_bf_yaw().
get_last_loop_time_s()
float AP_Scheduler::get_last_loop_time_s (void) const inline
Definition at line 173 of file AP_Scheduler.h.
get_loop_period_s()
float AP_Scheduler::get_loop_period_s () inline
Definition at line 155 of file AP_Scheduler.h.
Referenced by AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AC_AutoTune_Heli::dwell_test_run(), AP_YawController::get_rate_out(), loop(), AP_Vehicle::loop(), AC_AutoTune_Heli::rate_ff_test_run(), AP_Vehicle::setup(), AP_AutoTune::start(), AP_ICEngine::throttle_override(), AC_AutoTune_Multi::twitch_test_run(), and AP_ICEngine::update_idle_governor().
get_loop_period_us()
uint32_t AP_Scheduler::get_loop_period_us () inline
Definition at line 148 of file AP_Scheduler.h.
Referenced by load_average(), loop(), run(), GCS_MAVLINK::set_ap_message_interval(), and SRV_Channels::set_output_pwm_chan_timeout().
get_loop_rate_hz()
uint16_t AP_Scheduler::get_loop_rate_hz (void) inline
Definition at line 141 of file AP_Scheduler.h.
Referenced by init(), SRV_Channels::init(), load_average(), and AP_Arming::system_checks().
get_semaphore()
HAL_Semaphore & AP_Scheduler::get_semaphore (void) inline
Definition at line 182 of file AP_Scheduler.h.
get_singleton()
AP_Scheduler * AP_Scheduler::get_singleton () static
Definition at line 95 of file AP_Scheduler.cpp.
Referenced by AP::scheduler().
init()
void AP_Scheduler::init (const Task * tasks, uint8_t num_tasks, uint32_t log_performance_bit)
Definition at line 101 of file AP_Scheduler.cpp.
Referenced by SchedTest::setup(), and AP_Vehicle::setup().
load_average()
float AP_Scheduler::load_average ()
Definition at line 325 of file AP_Scheduler.cpp.
Log_Write_Performance()
void AP_Scheduler::Log_Write_Performance ()
loop()
void AP_Scheduler::loop ()
Definition at line 339 of file AP_Scheduler.cpp.
Referenced by SchedTest::loop(), and AP_Vehicle::loop().
run()
void AP_Scheduler::run (uint32_t time_available)
Definition at line 182 of file AP_Scheduler.cpp.
task_info()
void AP_Scheduler::task_info (ExpandingString & str)
Definition at line 469 of file AP_Scheduler.cpp.
Referenced by AP_Filesystem_Sys::open().
tick()
void AP_Scheduler::tick (void)
Definition at line 160 of file AP_Scheduler.cpp.
Referenced by loop().
ticks()
uint16_t AP_Scheduler::ticks () const inline
Definition at line 121 of file AP_Scheduler.h.
Referenced by AP_Logger_RateLimiter::should_log().
ticks32()
uint32_t AP_Scheduler::ticks32 () const inline
Definition at line 122 of file AP_Scheduler.h.
Referenced by AC_PosControl::init_xy_controller(), AC_PosControl::init_z_controller(), AC_PosControl::is_active_xy(), AC_PosControl::is_active_z(), AC_PosControl::update_xy_controller(), and AC_PosControl::update_z_controller().
time_available_usec()
uint16_t AP_Scheduler::time_available_usec (void) const
Definition at line 313 of file AP_Scheduler.cpp.
Referenced by LoggerMessageWriter::out_of_time_for_writing_messages(), and LoggerMessageWriter_DFLogStart::out_of_time_for_writing_messages_df().
update_logging()
void AP_Scheduler::update_logging ()
Member Data Documentation
_active_loop_rate_hz
AP_Int16 AP_Scheduler::_active_loop_rate_hz private
Definition at line 199 of file AP_Scheduler.h.
Referenced by get_loop_rate_hz().
_common_tasks
const struct Task* AP_Scheduler::_common_tasks private
Definition at line 215 of file AP_Scheduler.h.
Referenced by init(), run(), and task_info().
_debug
AP_Int8 AP_Scheduler::_debug private
Definition at line 193 of file AP_Scheduler.h.
Referenced by debug_flags().
_last_loop_time_s
float AP_Scheduler::_last_loop_time_s private
Definition at line 245 of file AP_Scheduler.h.
Referenced by get_last_loop_time_s(), init(), and loop().
_last_run
uint16_t* AP_Scheduler::_last_run private
Definition at line 227 of file AP_Scheduler.h.
Referenced by init(), and run().
_log_performance_bit
uint32_t AP_Scheduler::_log_performance_bit private
Definition at line 248 of file AP_Scheduler.h.
Referenced by init().
_loop_period_s
float AP_Scheduler::_loop_period_s private
Definition at line 208 of file AP_Scheduler.h.
Referenced by get_loop_period_s().
_loop_period_us
uint16_t AP_Scheduler::_loop_period_us private
Definition at line 205 of file AP_Scheduler.h.
Referenced by get_loop_period_us().
_loop_rate_hz
AP_Int16 AP_Scheduler::_loop_rate_hz private
Definition at line 196 of file AP_Scheduler.h.
Referenced by get_loop_period_s(), get_loop_period_us(), get_loop_rate_hz(), init(), and run().
_loop_timer_start_us
uint32_t AP_Scheduler::_loop_timer_start_us private
Definition at line 242 of file AP_Scheduler.h.
Referenced by loop().
_num_common_tasks
uint8_t AP_Scheduler::_num_common_tasks private
Definition at line 216 of file AP_Scheduler.h.
Referenced by init(), run(), and task_info().
_num_tasks
uint8_t AP_Scheduler::_num_tasks private
Definition at line 219 of file AP_Scheduler.h.
Referenced by init(), run(), and task_info().
_num_vehicle_tasks
uint8_t AP_Scheduler::_num_vehicle_tasks private
Definition at line 212 of file AP_Scheduler.h.
Referenced by init(), run(), and task_info().
_options
AP_Int8 AP_Scheduler::_options private
Definition at line 202 of file AP_Scheduler.h.
Referenced by init(), and task_info().
_rsem
HAL_Semaphore AP_Scheduler::_rsem private
Definition at line 265 of file AP_Scheduler.h.
Referenced by get_semaphore(), init(), and loop().
_singleton
AP_Scheduler * AP_Scheduler::_singleton static
Definition at line 81 of file AP_Scheduler.h.
Referenced by AP_Scheduler(), and get_singleton().
_spare_micros
uint32_t AP_Scheduler::_spare_micros private
Definition at line 236 of file AP_Scheduler.h.
Referenced by load_average(), and run().
_spare_ticks
uint8_t AP_Scheduler::_spare_ticks private
Definition at line 239 of file AP_Scheduler.h.
Referenced by load_average(), and run().
_task_time_allowed
uint32_t AP_Scheduler::_task_time_allowed private
Definition at line 230 of file AP_Scheduler.h.
Referenced by run(), and time_available_usec().
_task_time_started
uint32_t AP_Scheduler::_task_time_started private
Definition at line 233 of file AP_Scheduler.h.
Referenced by run(), and time_available_usec().
_tick_counter
uint16_t AP_Scheduler::_tick_counter private
Definition at line 223 of file AP_Scheduler.h.
Referenced by init(), run(), tick(), and ticks().
_tick_counter32
uint32_t AP_Scheduler::_tick_counter32 private
Definition at line 224 of file AP_Scheduler.h.
Referenced by tick(), and ticks32().
_vehicle_tasks
const struct Task* AP_Scheduler::_vehicle_tasks private
Definition at line 211 of file AP_Scheduler.h.
Referenced by init(), run(), and task_info().
extra_loop_us
uint32_t AP_Scheduler::extra_loop_us private
Definition at line 261 of file AP_Scheduler.h.
Referenced by get_extra_loop_us(), and loop().
max_task_slowdown
const uint8_t AP_Scheduler::max_task_slowdown = 4 private
Definition at line 252 of file AP_Scheduler.h.
Referenced by run().
perf_info
AP::PerfInfo AP_Scheduler::perf_info
Definition at line 189 of file AP_Scheduler.h.
Referenced by get_filtered_loop_rate_hz(), get_filtered_loop_time(), init(), loop(), run(), and task_info().
task_all_achieved
uint32_t AP_Scheduler::task_all_achieved private
Definition at line 257 of file AP_Scheduler.h.
Referenced by loop().
task_not_achieved
uint32_t AP_Scheduler::task_not_achieved private
Definition at line 256 of file AP_Scheduler.h.
Referenced by loop(), and run().
var_info
const AP_Param::GroupInfo AP_Scheduler::var_info static
Initial value:
= {
    AP_GROUPINFO("DEBUG",    0, AP_Scheduler, _debug, 0),
    AP_GROUPINFO("LOOP_RATE",  1, AP_Scheduler, _loop_rate_hz, SCHEDULER_DEFAULT_LOOP_RATE),
    AP_GROUPINFO("OPTIONS",  2, AP_Scheduler, _options, 0),
    AP_GROUPEND
}
Definition at line 51 of file AP_Scheduler.h.
The documentation for this class was generated from the following files:
libraries/AP_Scheduler/AP_Scheduler.h
libraries/AP_Scheduler/AP_Scheduler.cpp