APM:Libraries: NCP5623 Class Reference
NCP5623 Class Reference
#include <NCP5623.h>
Public Member Functions
NCP5623 (uint8_t bus)
bool init (void) override
Public Member Functions inherited from RGBLed
RGBLed (uint8_t led_off, uint8_t led_bright, uint8_t led_medium, uint8_t led_dim)
void set_rgb (uint8_t red, uint8_t green, uint8_t blue)
virtual void update () override
void rgb_control (uint8_t r, uint8_t g, uint8_t b, uint8_t rate_hz) override
Public Member Functions inherited from NotifyDevice
virtual ~NotifyDevice ()
virtual void play_tune (const char *tune)
virtual void rgb_set_id (uint8_t r, uint8_t g, uint8_t b, uint8_t id)
virtual void send_text_blocking (const char *text, uint8_t line)
virtual void release_text (uint8_t line)
Protected Member Functions
bool hw_set_rgb (uint8_t r, uint8_t g, uint8_t b) override
Protected Member Functions inherited from RGBLed
virtual void _set_rgb (uint8_t red, uint8_t green, uint8_t blue)
void update_override ()
Private Member Functions
void _timer (void)
bool write (uint8_t reg, uint8_t data)
bool write_pwm (uint8_t rgb[3])
Private Attributes
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
uint8_t rgb [3]
bool _need_update
uint8_t _bus
Additional Inherited Members
Public Attributes inherited from NotifyDevice
const AP_Notify * pNotify
Protected Attributes inherited from RGBLed
uint8_t _red_curr
uint8_t _green_curr
uint8_t _blue_curr
uint8_t _led_off
uint8_t _led_bright
uint8_t _led_medium
uint8_t _led_dim
struct {
uint8_t r
uint8_t g
uint8_t b
uint8_t rate_hz
uint32_t start_ms
} _led_override
Detailed Description
Definition at line 23 of file NCP5623.h.
Constructor & Destructor Documentation
NCP5623()
NCP5623::NCP5623 (uint8_t bus)
Definition at line 39 of file NCP5623.cpp.
Member Function Documentation
_timer()
void NCP5623::_timer (void) private
Definition at line 114 of file NCP5623.cpp.
Referenced by init().
hw_set_rgb()
bool NCP5623::hw_set_rgb (uint8_t r, uint8_t g, uint8_t b) override protected virtual
Implements RGBLed.
Definition at line 105 of file NCP5623.cpp.
init()
bool NCP5623::init (void) override virtual
Implements NotifyDevice.
Definition at line 66 of file NCP5623.cpp.
write()
bool NCP5623::write (uint8_t reg, uint8_t data) private
Definition at line 45 of file NCP5623.cpp.
Referenced by init(), and write_pwm().
write_pwm()
bool NCP5623::write_pwm (uint8_t rgb[3]) private
Definition at line 55 of file NCP5623.cpp.
Referenced by _timer(), and init().
Member Data Documentation
_bus
uint8_t NCP5623::_bus private
Definition at line 36 of file NCP5623.h.
Referenced by init().
_dev
AP_HAL::OwnPtr<AP_HAL::I2CDevice> NCP5623::_dev private
Definition at line 30 of file NCP5623.h.
Referenced by init(), and write().
_need_update
bool NCP5623::_need_update private
Definition at line 35 of file NCP5623.h.
Referenced by _timer(), and hw_set_rgb().
rgb
uint8_t NCP5623::rgb[3] private
Definition at line 34 of file NCP5623.h.
Referenced by _timer(), and hw_set_rgb().
The documentation for this class was generated from the following files:
libraries/AP_Notify/NCP5623.h
libraries/AP_Notify/NCP5623.cpp