APM:Libraries: AP_Filesystem Class Reference
AP_Filesystem Class Reference
#include <AP_Filesystem.h>
Classes
struct Backend
struct DirHandle
struct Stat
Public Types
typedef struct AP_Filesystem::Stat stat_t
Public Member Functions
AP_Filesystem ()
int open (const char *fname, int flags, bool allow_absolute_paths=false)
int close (int fd)
int32_t read (int fd, void *buf, uint32_t count)
int32_t write (int fd, const void *buf, uint32_t count)
int fsync (int fd)
int32_t lseek (int fd, int32_t offset, int whence)
int stat (const char *pathname, struct stat *stbuf)
bool stat (const char *pathname, stat_t &stbuf)
int unlink (const char *pathname)
int mkdir (const char *pathname)
int rename (const char *oldpath, const char *newpath)
DirHandle * opendir (const char *pathname)
struct dirent * readdir (DirHandle *dirp)
int closedir (DirHandle *dirp)
int64_t disk_free (const char *path)
int64_t disk_space (const char *path)
bool set_mtime (const char *filename, const uint32_t mtime_sec)
bool retry_mount (void)
void unmount (void)
bool fgets (char *buf, uint8_t buflen, int fd)
bool crc32 (const char *fname, uint32_t &checksum) WARN_IF_UNUSED
bool format (void)
AP_Filesystem_Backend::FormatStatus get_format_status () const
FileData * load_file (const char *filename)
Static Public Member Functions
static AP_Filesystem * get_singleton (void)
Private Member Functions
const Backend & backend_by_path (const char *&path) const
const Backend & backend_by_fd (int &fd) const
Private Attributes
struct {
uint8_t backend_ofs
struct dirent de
uint8_t d_off
} virtual_dirent
Static Private Attributes
static const struct Backend backends []
Detailed Description
Definition at line 67 of file AP_Filesystem.h.
Member Typedef Documentation
stat_t
typedef struct AP_Filesystem::Stat AP_Filesystem::stat_t
Constructor & Destructor Documentation
AP_Filesystem()
AP_Filesystem::AP_Filesystem () inline
Definition at line 75 of file AP_Filesystem.h.
Member Function Documentation
backend_by_fd()
const AP_Filesystem::Backend & AP_Filesystem::backend_by_fd (int & fd) const private
Definition at line 114 of file AP_Filesystem.cpp.
Referenced by close(), fgets(), fsync(), lseek(), read(), and write().
backend_by_path()
const AP_Filesystem::Backend & AP_Filesystem::backend_by_path (const char *& path) const private
Definition at line 89 of file AP_Filesystem.cpp.
Referenced by disk_free(), disk_space(), load_file(), mkdir(), open(), opendir(), rename(), set_mtime(), stat(), and unlink().
close()
int AP_Filesystem::close (int fd)
Definition at line 142 of file AP_Filesystem.cpp.
Referenced by HALSITL::UARTDriver::_begin(), ChibiOS::Storage::_save_backup(), ChibiOS::Storage::_storage_open(), apfs_fclose(), apfs_freopen(), AP_Logger::check_crash_dump_save(), AP_Networking::SendFile::close(), crc32(), GCS_MAVLINK::ftp_worker(), AP_JSON::load_json(), read_file(), and write_file().
closedir()
int AP_Filesystem::closedir (DirHandle * dirp)
Definition at line 261 of file AP_Filesystem.cpp.
Referenced by GCS_MAVLINK::ftp_list_dir().
crc32()
bool AP_Filesystem::crc32 (const char * fname, uint32_t & checksum)
Definition at line 339 of file AP_Filesystem.cpp.
Referenced by GCS_MAVLINK::ftp_worker().
disk_free()
int64_t AP_Filesystem::disk_free (const char * path)
Definition at line 273 of file AP_Filesystem.cpp.
disk_space()
int64_t AP_Filesystem::disk_space (const char * path)
Definition at line 280 of file AP_Filesystem.cpp.
fgets()
bool AP_Filesystem::fgets (char * buf, uint8_t buflen, int fd)
Definition at line 318 of file AP_Filesystem.cpp.
Referenced by apfs_fgets().
format()
bool AP_Filesystem::format (void)
Definition at line 374 of file AP_Filesystem.cpp.
fsync()
int AP_Filesystem::fsync (int fd)
Definition at line 160 of file AP_Filesystem.cpp.
get_format_status()
AP_Filesystem_Backend::FormatStatus AP_Filesystem::get_format_status (void) const
Definition at line 381 of file AP_Filesystem.cpp.
get_singleton()
AP_Filesystem * AP_Filesystem::get_singleton (void) static
Definition at line 406 of file AP_Filesystem.cpp.
load_file()
FileData * AP_Filesystem::load_file (const char * filename)
Definition at line 311 of file AP_Filesystem.cpp.
Referenced by AP_OSD_Screen::draw_callsign(), AP_OSD_Backend::load_font_data(), and HALSITL::SITL_State::lookup_location().
lseek()
int32_t AP_Filesystem::lseek (int fd, int32_t offset, int whence)
Definition at line 166 of file AP_Filesystem.cpp.
Referenced by apfs_fseek(), apfs_ftell(), and AP_Networking::sendfile_check().
mkdir()
int AP_Filesystem::mkdir (const char * pathname)
Definition at line 184 of file AP_Filesystem.cpp.
Referenced by ChibiOS::Storage::_save_backup(), GCS_MAVLINK::ftp_worker(), sdcard_retry(), and setup().
open()
int AP_Filesystem::open (const char * fname, int flags, bool allow_absolute_paths = false)
Definition at line 124 of file AP_Filesystem.cpp.
Referenced by HALSITL::UARTDriver::_begin(), ChibiOS::Storage::_save_backup(), ChibiOS::Storage::_storage_open(), ap_networking_printf(), apfs_fopen(), apfs_freopen(), AP_Logger::check_crash_dump_save(), crc32(), GCS_MAVLINK::ftp_worker(), AP_JSON::load_json(), read_file(), and write_file().
opendir()
AP_Filesystem::DirHandle * AP_Filesystem::opendir (const char * pathname)
Definition at line 196 of file AP_Filesystem.cpp.
Referenced by GCS_MAVLINK::ftp_list_dir().
read()
int32_t AP_Filesystem::read (int fd, void * buf, uint32_t count)
Definition at line 148 of file AP_Filesystem.cpp.
Referenced by ChibiOS::Storage::_storage_open(), apfs_fread(), apfs_getc(), crc32(), GCS_MAVLINK::ftp_worker(), read_file(), and AP_Networking::sendfile_check().
readdir()
struct dirent * AP_Filesystem::readdir (DirHandle * dirp)
Definition at line 225 of file AP_Filesystem.cpp.
Referenced by GCS_MAVLINK::ftp_list_dir().
rename()
int AP_Filesystem::rename (const char * oldpath, const char * newpath)
Definition at line 190 of file AP_Filesystem.cpp.
Referenced by GCS_MAVLINK::ftp_worker().
retry_mount()
bool AP_Filesystem::retry_mount (void)
Definition at line 297 of file AP_Filesystem.cpp.
Referenced by ChibiOS::Scheduler::_io_thread().
set_mtime()
bool AP_Filesystem::set_mtime (const char * filename, const uint32_t mtime_sec)
Definition at line 290 of file AP_Filesystem.cpp.
stat() [1/2]
bool AP_Filesystem::stat (const char * pathname, stat_t & stbuf)
Definition at line 390 of file AP_Filesystem.cpp.
stat() [2/2]
int AP_Filesystem::stat (const char * pathname, struct stat * stbuf)
Definition at line 172 of file AP_Filesystem.cpp.
Referenced by GCS_MAVLINK::ftp_worker(), and stat().
unlink()
int AP_Filesystem::unlink (const char * pathname)
Definition at line 178 of file AP_Filesystem.cpp.
Referenced by apfs_fclose(), apfs_freopen(), apfs_remove(), and GCS_MAVLINK::ftp_worker().
unmount()
void AP_Filesystem::unmount (void)
Definition at line 303 of file AP_Filesystem.cpp.
Referenced by ChibiOS::Scheduler::reboot().
write()
int32_t AP_Filesystem::write (int fd, const void * buf, uint32_t count)
Definition at line 154 of file AP_Filesystem.cpp.
Referenced by ChibiOS::Storage::_save_backup(), apfs_fprintf(), apfs_fputs(), apfs_fwrite(), AP_Logger::check_crash_dump_save(), GCS_MAVLINK::ftp_worker(), and write_file().
Member Data Documentation
backend_ofs
uint8_t AP_Filesystem::backend_ofs
Definition at line 162 of file AP_Filesystem.h.
backends
const AP_Filesystem::Backend AP_Filesystem::backends static private
Initial value:
= {
    { nullptr, fs_local },
    { "@PARAM", fs_param },
    { "@SYS", fs_sys },
}
Definition at line 63 of file AP_Filesystem.h.
Referenced by backend_by_fd(), backend_by_path(), closedir(), open(), and readdir().
d_off
uint8_t AP_Filesystem::d_off
Definition at line 164 of file AP_Filesystem.h.
de
struct dirent AP_Filesystem::de
Definition at line 163 of file AP_Filesystem.h.
[struct]
struct { ... } AP_Filesystem::virtual_dirent
Referenced by opendir(), and readdir().
The documentation for this class was generated from the following files:
libraries/AP_Filesystem/AP_Filesystem.h
libraries/AP_Filesystem/AP_Filesystem.cpp