APM:Libraries: AP_InertialSensor_SCHA63T Class Reference
AP_InertialSensor_SCHA63T Class Reference
#include <AP_InertialSensor_SCHA63T.h>
Public Types
enum reg_scha63t {
RATE_XZ = 0x01 , RATE_Y = 0x03 , ACC_X = 0x04 , ACC_Y = 0x05 ,
ACC_Z = 0x06 , TEMP = 0x07 , S_SUM = 0x0E , R_S1 = 0x10 ,
A_S1 = 0x12 , C_S1 = 0x14 , C_S2 = 0x15 , G_FILT_DYN = 0x16 ,
RESCTRL = 0x18 , MODE = 0x19 , A_FILT_DYN = 0x1A , T_ID2 = 0x1C ,
T_ID0 = 0x1D , T_ID1 = 0x1E , SEL_BANK = 0x1F
}
Public Types inherited from AP_InertialSensor_Backend
enum DevTypes {
DEVTYPE_BMI160 = 0x09 , DEVTYPE_L3G4200D = 0x10 , DEVTYPE_ACC_LSM303D = 0x11 , DEVTYPE_ACC_BMA180 = 0x12 ,
DEVTYPE_ACC_MPU6000 = 0x13 , DEVTYPE_ACC_MPU9250 = 0x16 , DEVTYPE_ACC_IIS328DQ = 0x17 , DEVTYPE_ACC_LSM9DS1 = 0x18 ,
DEVTYPE_GYR_MPU6000 = 0x21 , DEVTYPE_GYR_L3GD20 = 0x22 , DEVTYPE_GYR_MPU9250 = 0x24 , DEVTYPE_GYR_I3G4250D = 0x25 ,
DEVTYPE_GYR_LSM9DS1 = 0x26 , DEVTYPE_INS_ICM20789 = 0x27 , DEVTYPE_INS_ICM20689 = 0x28 , DEVTYPE_INS_BMI055 = 0x29 ,
DEVTYPE_SITL = 0x2A , DEVTYPE_INS_BMI088 = 0x2B , DEVTYPE_INS_ICM20948 = 0x2C , DEVTYPE_INS_ICM20648 = 0x2D ,
DEVTYPE_INS_ICM20649 = 0x2E , DEVTYPE_INS_ICM20602 = 0x2F , DEVTYPE_INS_ICM20601 = 0x30 , DEVTYPE_INS_ADIS1647X = 0x31 ,
DEVTYPE_SERIAL = 0x32 , DEVTYPE_INS_ICM40609 = 0x33 , DEVTYPE_INS_ICM42688 = 0x34 , DEVTYPE_INS_ICM42605 = 0x35 ,
DEVTYPE_INS_ICM40605 = 0x36 , DEVTYPE_INS_IIM42652 = 0x37 , DEVTYPE_BMI270 = 0x38 , DEVTYPE_INS_BMI085 = 0x39 ,
DEVTYPE_INS_ICM42670 = 0x3A , DEVTYPE_INS_ICM45686 = 0x3B , DEVTYPE_INS_SCHA63T = 0x3C
}
Public Member Functions
void start () override
bool update () override
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void accumulate ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t get_id () const
float get_clip_limit () const
virtual bool get_output_banner (char *banner, uint8_t banner_len)
Static Public Member Functions
static AP_InertialSensor_Backend * probe (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev_accel, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev_gyro, enum Rotation rotation)
Private Member Functions
AP_InertialSensor_SCHA63T (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::Device > dev_accel, AP_HAL::OwnPtr< AP_HAL::Device > dev_gyro, enum Rotation rotation)
bool init ()
void read_accel ()
void read_gyro ()
bool read_register (uint8_t tp, reg_scha63t reg, uint8_t *val)
bool write_register (uint8_t tp, reg_scha63t reg, uint16_t val)
void set_temperature (uint8_t instance, uint16_t temper)
bool check_startup ()
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > dev_uno
AP_HAL::OwnPtr< AP_HAL::Device > dev_due
uint8_t accel_instance
uint8_t gyro_instance
enum Rotation rotation
Additional Inherited Members
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel) __RAMFUNC__
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro) __RAMFUNC__
void _publish_gyro (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void apply_gyro_filters (const uint8_t instance, const Vector3f &gyro)
void save_gyro_window (const uint8_t instance, const Vector3f &gyro, uint8_t phase)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0) __RAMFUNC__
void _notify_new_delta_angle (uint8_t instance, const Vector3f &dangle)
void _publish_accel (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0, bool fsync_set=false) __RAMFUNC__
void _notify_new_delta_velocity (uint8_t instance, const Vector3f &dvelocity)
void _set_accel_oversampling (uint8_t instance, uint8_t n)
void _set_gyro_oversampling (uint8_t instance, uint8_t n)
void _set_accel_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_gyro_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_raw_sample_accel_multiplier (uint8_t instance, uint16_t mul)
void _set_raw_sample_gyro_multiplier (uint8_t instance, uint16_t mul)
void _update_sensor_rate (uint16_t &count, uint32_t &start_us, float &rate_hz) const __RAMFUNC__
bool sensors_converging () const
void _set_accel_max_abs_offset (uint8_t instance, float offset)
float _accel_raw_sample_rate (uint8_t instance) const
void _set_accel_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
float _gyro_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
void _publish_temperature (uint8_t instance, float temperature)
void _inc_accel_error_count (uint8_t instance) __RAMFUNC__
void _inc_gyro_error_count (uint8_t instance) __RAMFUNC__
uint16_t _accel_filter_cutoff (void) const
uint16_t _gyro_filter_cutoff (void) const
uint16_t get_loop_rate_hz (void) const
void update_gyro (uint8_t instance) __RAMFUNC__
void update_accel (uint8_t instance) __RAMFUNC__
void set_gyro_orientation (uint8_t instance, enum Rotation rotation)
void set_accel_orientation (uint8_t instance, enum Rotation rotation)
void increment_clip_count (uint8_t instance)
bool enable_fast_sampling (uint8_t instance) const
bool enable_highres_sampling (uint8_t instance) const
uint8_t get_fast_sampling_rate () const
void _notify_new_accel_sensor_rate_sample (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_gyro_sensor_rate_sample (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void notify_accel_fifo_reset (uint8_t instance) __RAMFUNC__
void notify_gyro_fifo_reset (uint8_t instance) __RAMFUNC__
void log_register_change (uint32_t bus_id, const AP_HAL::Device::checkreg &reg) __RAMFUNC__
void Write_GYR (const uint8_t instance, const uint64_t sample_us, const Vector3f &gyro, bool use_sample_timestamp=false) const __RAMFUNC__
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
HAL_Semaphore _sem
float _clip_limit = 15.5f * GRAVITY_MSS
int16_t _id = -1
uint16_t _last_accel_filter_hz
uint16_t _last_gyro_filter_hz
Detailed Description
Definition at line 26 of file AP_InertialSensor_SCHA63T.h.
Member Enumeration Documentation
reg_scha63t
enum AP_InertialSensor_SCHA63T::reg_scha63t
Enumerator
RATE_XZ
RATE_Y
ACC_X
ACC_Y
ACC_Z
TEMP
S_SUM
R_S1
A_S1
C_S1
C_S2
G_FILT_DYN
RESCTRL
MODE
A_FILT_DYN
T_ID2
T_ID0
T_ID1
SEL_BANK
Definition at line 40 of file AP_InertialSensor_SCHA63T.h.
Constructor & Destructor Documentation
AP_InertialSensor_SCHA63T()
AP_InertialSensor_SCHA63T::AP_InertialSensor_SCHA63T (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::Device > dev_accel, AP_HAL::OwnPtr< AP_HAL::Device > dev_gyro, enum Rotation rotation) private
Definition at line 47 of file AP_InertialSensor_SCHA63T.cpp.
Referenced by probe().
Member Function Documentation
check_startup()
bool AP_InertialSensor_SCHA63T::check_startup () private
Definition at line 191 of file AP_InertialSensor_SCHA63T.cpp.
Referenced by init().
init()
bool AP_InertialSensor_SCHA63T::init () private
Definition at line 116 of file AP_InertialSensor_SCHA63T.cpp.
probe()
AP_InertialSensor_Backend * AP_InertialSensor_SCHA63T::probe (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev_accel, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev_gyro, enum Rotation rotation) static
Definition at line 58 of file AP_InertialSensor_SCHA63T.cpp.
read_accel()
void AP_InertialSensor_SCHA63T::read_accel () private
Definition at line 241 of file AP_InertialSensor_SCHA63T.cpp.
Referenced by start().
read_gyro()
void AP_InertialSensor_SCHA63T::read_gyro () private
Definition at line 315 of file AP_InertialSensor_SCHA63T.cpp.
Referenced by start().
read_register()
bool AP_InertialSensor_SCHA63T::read_register (uint8_t tp, reg_scha63t reg, uint8_t * val) private
Definition at line 416 of file AP_InertialSensor_SCHA63T.cpp.
Referenced by check_startup(), read_accel(), and read_gyro().
set_temperature()
void AP_InertialSensor_SCHA63T::set_temperature (uint8_t instance, uint16_t temper) private
Definition at line 402 of file AP_InertialSensor_SCHA63T.cpp.
Referenced by read_accel(), and read_gyro().
start()
void AP_InertialSensor_SCHA63T::start (void) override virtual
Configure the sensors and start reading routine.
Reimplemented from AP_InertialSensor_Backend.
Definition at line 84 of file AP_InertialSensor_SCHA63T.cpp.
update()
bool AP_InertialSensor_SCHA63T::update (void) override virtual
Implements AP_InertialSensor_Backend.
Definition at line 409 of file AP_InertialSensor_SCHA63T.cpp.
write_register()
bool AP_InertialSensor_SCHA63T::write_register (uint8_t tp, reg_scha63t reg, uint16_t val) private
Definition at line 454 of file AP_InertialSensor_SCHA63T.cpp.
Referenced by check_startup(), and init().
Member Data Documentation
accel_instance
uint8_t AP_InertialSensor_SCHA63T::accel_instance private
Definition at line 87 of file AP_InertialSensor_SCHA63T.h.
Referenced by read_accel(), start(), and update().
dev_due
AP_HAL::OwnPtr<AP_HAL::Device> AP_InertialSensor_SCHA63T::dev_due private
Definition at line 85 of file AP_InertialSensor_SCHA63T.h.
Referenced by init(), probe(), read_gyro(), read_register(), start(), and write_register().
dev_uno
AP_HAL::OwnPtr<AP_HAL::Device> AP_InertialSensor_SCHA63T::dev_uno private
Definition at line 84 of file AP_InertialSensor_SCHA63T.h.
Referenced by init(), probe(), read_accel(), read_register(), start(), and write_register().
gyro_instance
uint8_t AP_InertialSensor_SCHA63T::gyro_instance private
Definition at line 88 of file AP_InertialSensor_SCHA63T.h.
Referenced by read_gyro(), start(), and update().
rotation
enum Rotation AP_InertialSensor_SCHA63T::rotation private
Definition at line 89 of file AP_InertialSensor_SCHA63T.h.
Referenced by probe(), and start().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_SCHA63T.h
libraries/AP_InertialSensor/AP_InertialSensor_SCHA63T.cpp