APM:Libraries: AC_PID Class Reference
AC_PID Class Reference
Copter PID control class.
#include <AC_PID.h>
Classes
struct ac_pid_flags
struct Defaults
Public Member Functions
AC_PID (float initial_p, float initial_i, float initial_d, float initial_ff, float initial_imax, float initial_filt_T_hz, float initial_filt_E_hz, float initial_filt_D_hz, float initial_srmax=0, float initial_srtau=1.0, float initial_dff=0)
AC_PID (const AC_PID::Defaults &defaults)
CLASS_NO_COPY (AC_PID)
float update_all (float target, float measurement, float dt, bool limit=false, float boost=1.0f)
float update_error (float error, float dt, bool limit=false)
float get_p () const
float get_i () const
float get_d () const
float get_ff () const
void reset_I ()
void reset_filter ()
void load_gains ()
void save_gains ()
void operator() (float p_val, float i_val, float d_val, float ff_val, float imax_val, float input_filt_T_hz, float input_filt_E_hz, float input_filt_D_hz, float dff_val=0)
operator function call for easy initialisation
const AP_Float & kP () const
AP_Float & kP ()
AP_Float & kI ()
AP_Float & kD ()
AP_Float & kIMAX ()
AP_Float & kPDMAX ()
AP_Float & ff ()
AP_Float & filt_T_hz ()
AP_Float & filt_E_hz ()
AP_Float & filt_D_hz ()
AP_Float & slew_limit ()
AP_Float & kDff ()
float imax () const
float pdmax () const
float get_filt_T_alpha (float dt) const
float get_filt_E_alpha (float dt) const
float get_filt_D_alpha (float dt) const
void kP (const float v)
void kI (const float v)
void kD (const float v)
void ff (const float v)
void imax (const float v)
void pdmax (const float v)
void filt_T_hz (const float v)
void filt_E_hz (const float v)
void filt_D_hz (const float v)
void slew_limit (const float v)
void kDff (const float v)
void set_target_rate (float target)
void set_actual_rate (float actual)
void set_integrator (float i)
void relax_integrator (float integrator, float dt, float time_constant)
void set_slew_limit_scale (int8_t scale)
float get_slew_rate (void) const
const AP_PIDInfo & get_pid_info (void) const
void set_notch_sample_rate (float)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void update_i (float dt, bool limit)
Protected Attributes
AP_Float _kp
AP_Float _ki
AP_Float _kd
AP_Float _kff
AP_Float _kimax
AP_Float _kpdmax
AP_Float _filt_T_hz
AP_Float _filt_E_hz
AP_Float _filt_D_hz
AP_Float _slew_rate_max
AP_Float _kdff
AP_Float _slew_rate_tau
SlewLimiter _slew_limiter {_slew_rate_max, _slew_rate_tau}
struct AC_PID::ac_pid_flags _flags
float _integrator
float _target
float _error
float _derivative
int8_t _slew_limit_scale
float _target_derivative
AP_PIDInfo _pid_info
Private Attributes
const float default_kp
const float default_ki
const float default_kd
const float default_kff
const float default_kdff
const float default_kimax
const float default_filt_T_hz
const float default_filt_E_hz
const float default_filt_D_hz
const float default_slew_rate_max
Detailed Description
Copter PID control class.
Definition at line 23 of file AC_PID.h.
Constructor & Destructor Documentation
AC_PID() [1/2]
AC_PID::AC_PID (float initial_p, float initial_i, float initial_d, float initial_ff, float initial_imax, float initial_filt_T_hz, float initial_filt_E_hz, float initial_filt_D_hz, float initial_srmax = 0, float initial_srtau = 1.0, float initial_dff = 0)
Definition at line 103 of file AC_PID.cpp.
AC_PID() [2/2]
AC_PID::AC_PID (const AC_PID::Defaults & defaults) inline
Definition at line 43 of file AC_PID.h.
Member Function Documentation
CLASS_NO_COPY()
AC_PID::CLASS_NO_COPY (AC_PID)
ff() [1/2]
AP_Float & AC_PID::ff () inline
Definition at line 105 of file AC_PID.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AP_PitchController::convert_pid(), AP_RollController::convert_pid(), AC_AutoTune_Heli::dwell_test_run(), AP_AutoTune::get_gains(), AC_PosControl::init_z_controller(), AP_PitchController::kFF(), AP_RollController::kFF(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), AC_AttitudeControl::pre_arm_checks(), AP_AutoTune::restore_gains(), AP_AutoTune::save_gains(), AC_AutoTune_Heli::save_tuning_gains(), AC_AutoTune_Multi::save_tuning_gains(), AP_AutoTune::start(), and AP_AutoTune::update().
ff() [2/2]
void AC_PID::ff (const float v) inline
Definition at line 123 of file AC_PID.h.
filt_D_hz() [1/2]
AP_Float & AC_PID::filt_D_hz () inline
Definition at line 108 of file AC_PID.h.
Referenced by AP_AutoTune::get_gains(), AP_AutoTune::restore_gains(), AP_AutoTune::save_gains(), AC_AutoTune_Multi::twitch_test_init(), and AP_AutoTune::update().
filt_D_hz() [2/2]
void AC_PID::filt_D_hz (const float v)
Definition at line 145 of file AC_PID.cpp.
filt_E_hz() [1/2]
AP_Float & AC_PID::filt_E_hz () inline
Definition at line 107 of file AC_PID.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AP_AutoTune::get_gains(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), AP_AutoTune::restore_gains(), AP_AutoTune::save_gains(), AC_AutoTune_Heli::save_tuning_gains(), AC_AutoTune_Multi::save_tuning_gains(), AC_PosControl::set_max_speed_accel_z(), and AP_AutoTune::update().
filt_E_hz() [2/2]
void AC_PID::filt_E_hz (const float v)
Definition at line 139 of file AC_PID.cpp.
filt_T_hz() [1/2]
AP_Float & AC_PID::filt_T_hz () inline
Definition at line 106 of file AC_PID.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AP_AutoTune::get_gains(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AP_AutoTune::restore_gains(), AP_AutoTune::save_gains(), AC_AutoTune_Multi::save_tuning_gains(), AC_PosControl::set_max_speed_accel_z(), and AP_AutoTune::update().
filt_T_hz() [2/2]
void AC_PID::filt_T_hz (const float v)
Definition at line 133 of file AC_PID.cpp.
get_d()
float AC_PID::get_d () const
Definition at line 339 of file AC_PID.cpp.
Referenced by AR_AttitudeControl::get_sail_out_from_heel(), and loop().
get_ff()
float AC_PID::get_ff () const
Definition at line 344 of file AC_PID.cpp.
Referenced by AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AC_AutoTune_Heli::dwell_test_init(), AP_WheelRateControl::get_rate_controlled_throttle(), AP_YawController::get_rate_out(), AR_AttitudeControl::get_sail_out_from_heel(), AR_AttitudeControl::get_steering_out_rate(), AR_AttitudeControl::get_throttle_out_from_pitch(), AR_AttitudeControl::get_throttle_out_speed(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_target_to_motor_yaw(), and AC_PosControl::update_z_controller().
get_filt_D_alpha()
float AC_PID::get_filt_D_alpha (float dt) const
Definition at line 406 of file AC_PID.cpp.
Referenced by update_all().
get_filt_E_alpha()
float AC_PID::get_filt_E_alpha (float dt) const
Definition at line 400 of file AC_PID.cpp.
Referenced by update_all().
get_filt_T_alpha()
float AC_PID::get_filt_T_alpha (float dt) const
Definition at line 394 of file AC_PID.cpp.
Referenced by update_all().
get_i()
float AC_PID::get_i () const
Definition at line 334 of file AC_PID.cpp.
Referenced by AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_PitchController::decay_I(), AP_RollController::decay_I(), AP_YawController::get_rate_out(), AR_AttitudeControl::get_sail_out_from_heel(), AC_PosControl::get_throttle_with_vibration_override(), loop(), and AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch().
get_p()
float AC_PID::get_p () const
Definition at line 329 of file AC_PID.cpp.
Referenced by AC_AutoTune_Heli::dwell_test_init(), AR_AttitudeControl::get_sail_out_from_heel(), and loop().
get_pid_info()
const AP_PIDInfo & AC_PID::get_pid_info (void) const inline
Definition at line 146 of file AC_PID.h.
Referenced by AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AC_AttitudeControl::control_monitor_update(), AR_AttitudeControl::get_desired_pitch(), AP_YawController::get_rate_out(), AC_AttitudeControl::get_rpy_srate(), AR_AttitudeControl::get_srate(), and AR_AttitudeControl::get_throttle_out_speed().
get_slew_rate()
float AC_PID::get_slew_rate (void) const inline
Definition at line 144 of file AC_PID.h.
imax() [1/2]
float AC_PID::imax () const inline
Definition at line 112 of file AC_PID.h.
Referenced by loop(), and AC_PosControl::update_z_controller().
imax() [2/2]
void AC_PID::imax (const float v) inline
Definition at line 124 of file AC_PID.h.
kD() [1/2]
AP_Float & AC_PID::kD () inline
Definition at line 102 of file AC_PID.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AP_PitchController::convert_pid(), AP_RollController::convert_pid(), AP_AutoTune::get_gains(), AP_PitchController::kD(), AP_RollController::kD(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), loop(), AC_AttitudeControl::max_rate_step_bf_pitch(), AC_AttitudeControl::max_rate_step_bf_roll(), AC_AttitudeControl::max_rate_step_bf_yaw(), AC_AttitudeControl::pre_arm_checks(), AP_AutoTune::restore_gains(), AP_AutoTune::save_gains(), AC_AutoTune_Heli::save_tuning_gains(), AC_AutoTune_Multi::save_tuning_gains(), and AP_AutoTune::update().
kD() [2/2]
void AC_PID::kD (const float v) inline
Definition at line 122 of file AC_PID.h.
kDff() [1/2]
AP_Float & AC_PID::kDff () inline
Definition at line 110 of file AC_PID.h.
kDff() [2/2]
void AC_PID::kDff (const float v) inline
Definition at line 130 of file AC_PID.h.
kI() [1/2]
AP_Float & AC_PID::kI () inline
Definition at line 101 of file AC_PID.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AP_PitchController::convert_pid(), AP_RollController::convert_pid(), AP_AutoTune::get_gains(), AP_PitchController::kI(), AP_RollController::kI(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), loop(), AC_AttitudeControl::pre_arm_checks(), AP_AutoTune::restore_gains(), AP_AutoTune::save_gains(), AC_AutoTune_Heli::save_tuning_gains(), AC_AutoTune_Multi::save_tuning_gains(), and AP_AutoTune::update().
kI() [2/2]
void AC_PID::kI (const float v) inline
Definition at line 121 of file AC_PID.h.
kIMAX()
AP_Float & AC_PID::kIMAX () inline
Definition at line 103 of file AC_PID.h.
Referenced by AP_PitchController::convert_pid(), AP_RollController::convert_pid(), AP_AutoTune::get_gains(), AP_AutoTune::restore_gains(), AP_AutoTune::save_gains(), and AP_AutoTune::start().
kP() [1/3]
AP_Float & AC_PID::kP () inline
Definition at line 100 of file AC_PID.h.
kP() [2/3]
const AP_Float & AC_PID::kP () const inline
Definition at line 99 of file AC_PID.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AP_PitchController::convert_pid(), AP_RollController::convert_pid(), AC_AutoTune_Heli::dwell_test_run(), AP_AutoTune::get_gains(), AC_PosControl::init_z_controller(), AP_PitchController::kP(), AP_RollController::kP(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), loop(), AC_AttitudeControl::max_rate_step_bf_pitch(), AC_AttitudeControl::max_rate_step_bf_roll(), AC_AttitudeControl::max_rate_step_bf_yaw(), AC_AttitudeControl::pre_arm_checks(), AP_AutoTune::restore_gains(), AP_AutoTune::save_gains(), AC_AutoTune_Heli::save_tuning_gains(), AC_AutoTune_Multi::save_tuning_gains(), and AP_AutoTune::update().
kP() [3/3]
void AC_PID::kP (const float v) inline
Definition at line 120 of file AC_PID.h.
kPDMAX()
AP_Float & AC_PID::kPDMAX () inline
Definition at line 104 of file AC_PID.h.
load_gains()
void AC_PID::load_gains ()
Definition at line 356 of file AC_PID.cpp.
operator()()
void AC_PID::operator() (float p_val, float i_val, float d_val, float ff_val, float imax_val, float input_filt_T_hz, float input_filt_E_hz, float input_filt_D_hz, float dff_val = 0)
operator function call for easy initialisation
Overload the function call operator to permit easy initialisation.
Definition at line 380 of file AC_PID.cpp.
pdmax() [1/2]
float AC_PID::pdmax () const inline
Definition at line 113 of file AC_PID.h.
pdmax() [2/2]
void AC_PID::pdmax (const float v) inline
Definition at line 125 of file AC_PID.h.
relax_integrator()
void AC_PID::relax_integrator (float integrator, float dt, float time_constant)
Definition at line 417 of file AC_PID.cpp.
Referenced by AC_PosControl::relax_z_controller(), and AC_AttitudeControl::reset_rate_controller_I_terms_smoothly().
reset_filter()
void AC_PID::reset_filter () inline
Definition at line 85 of file AC_PID.h.
Referenced by AP_WheelRateControl::get_rate_controlled_throttle(), AR_AttitudeControl::get_sail_out_from_heel(), AR_AttitudeControl::get_steering_out_rate(), AR_AttitudeControl::get_throttle_out_from_pitch(), AR_AttitudeControl::get_throttle_out_speed(), AR_AttitudeControl::get_throttle_out_stop(), AC_PosControl::init_z_controller(), AC_AttitudeControl::relax_attitude_controllers(), and AP_YawController::reset_rate_PID().
reset_I()
void AC_PID::reset_I ()
Definition at line 349 of file AC_PID.cpp.
Referenced by AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_WheelRateControl::get_rate_controlled_throttle(), AP_YawController::get_rate_out(), AR_AttitudeControl::get_sail_out_from_heel(), AR_AttitudeControl::get_steering_out_rate(), AR_AttitudeControl::get_throttle_out_from_pitch(), AR_AttitudeControl::get_throttle_out_speed(), AR_AttitudeControl::get_throttle_out_stop(), AC_AttitudeControl_TS::relax_attitude_controllers(), AR_AttitudeControl::relax_I(), AP_PitchController::reset_I(), AP_RollController::reset_I(), AP_YawController::reset_I(), AC_AttitudeControl::reset_rate_controller_I_terms(), and AP_YawController::reset_rate_PID().
save_gains()
void AC_PID::save_gains ()
Definition at line 368 of file AC_PID.cpp.
Referenced by AC_AutoTune_Heli::save_tuning_gains(), and AC_AutoTune_Multi::save_tuning_gains().
set_actual_rate()
void AC_PID::set_actual_rate (float actual) inline
Definition at line 134 of file AC_PID.h.
set_integrator()
void AC_PID::set_integrator (float i)
Definition at line 411 of file AC_PID.cpp.
Referenced by AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_PitchController::decay_I(), AP_RollController::decay_I(), AP_YawController::get_rate_out(), AC_PosControl::get_throttle_with_vibration_override(), AC_PosControl::init_z_controller(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), and AC_PosControl::standby_xyz_reset().
set_notch_sample_rate()
void AC_PID::set_notch_sample_rate (float sample_rate)
Definition at line 156 of file AC_PID.cpp.
Referenced by AP_WheelRateControl::set_notch_sample_rate(), AP_PitchController::set_notch_sample_rate(), AP_RollController::set_notch_sample_rate(), AP_YawController::set_notch_sample_rate(), AR_AttitudeControl::set_notch_sample_rate(), AC_AttitudeControl_Heli::set_notch_sample_rate(), AC_AttitudeControl_Multi::set_notch_sample_rate(), and AC_AttitudeControl_Sub::set_notch_sample_rate().
set_slew_limit_scale()
void AC_PID::set_slew_limit_scale (int8_t scale) inline
Definition at line 141 of file AC_PID.h.
Referenced by AP_PitchController::AP_PitchController(), AP_RollController::AP_RollController(), and AP_YawController::AP_YawController().
set_target_rate()
void AC_PID::set_target_rate (float target) inline
Definition at line 133 of file AC_PID.h.
slew_limit() [1/2]
AP_Float & AC_PID::slew_limit () inline
Definition at line 109 of file AC_PID.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::save_tuning_gains(), AP_AutoTune::start(), and AP_AutoTune::update().
slew_limit() [2/2]
void AC_PID::slew_limit (const float v)
Definition at line 151 of file AC_PID.cpp.
update_all()
float AC_PID::update_all (float target, float measurement, float dt, bool limit = false, float boost = 1.0f)
Definition at line 193 of file AC_PID.cpp.
Referenced by AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_WheelRateControl::get_rate_controlled_throttle(), AP_YawController::get_rate_out(), AR_AttitudeControl::get_sail_out_from_heel(), AR_AttitudeControl::get_steering_out_rate(), AR_AttitudeControl::get_throttle_out_from_pitch(), AR_AttitudeControl::get_throttle_out_speed(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_target_to_motor_yaw(), update_error(), and AC_PosControl::update_z_controller().
update_error()
float AC_PID::update_error (float error, float dt, bool limit = false)
Definition at line 288 of file AC_PID.cpp.
Referenced by loop().
update_i()
void AC_PID::update_i (float dt, bool limit) protected
Definition at line 310 of file AC_PID.cpp.
Referenced by update_all().
Member Data Documentation
_derivative
float AC_PID::_derivative protected
Definition at line 194 of file AC_PID.h.
Referenced by update_all().
_error
float AC_PID::_error protected
Definition at line 193 of file AC_PID.h.
Referenced by update_all(), and update_i().
_filt_D_hz
AP_Float AC_PID::_filt_D_hz protected
Definition at line 168 of file AC_PID.h.
Referenced by filt_D_hz(), filt_D_hz(), get_filt_D_alpha(), load_gains(), operator()(), and save_gains().
_filt_E_hz
AP_Float AC_PID::_filt_E_hz protected
Definition at line 167 of file AC_PID.h.
Referenced by filt_E_hz(), filt_E_hz(), get_filt_E_alpha(), load_gains(), operator()(), and save_gains().
_filt_T_hz
AP_Float AC_PID::_filt_T_hz protected
Definition at line 166 of file AC_PID.h.
Referenced by filt_T_hz(), filt_T_hz(), get_filt_T_alpha(), load_gains(), operator()(), and save_gains().
_flags
struct AC_PID::ac_pid_flags AC_PID::_flags protected
Referenced by AC_PID(), relax_integrator(), reset_filter(), reset_I(), set_integrator(), update_all(), and update_i().
_integrator
float AC_PID::_integrator protected
Definition at line 191 of file AC_PID.h.
Referenced by get_i(), relax_integrator(), reset_I(), set_integrator(), update_all(), update_i(), and AC_HELI_PID::update_leaky_i().
_kd
AP_Float AC_PID::_kd protected
Definition at line 162 of file AC_PID.h.
Referenced by kD(), kD(), load_gains(), operator()(), save_gains(), and update_all().
_kdff
AP_Float AC_PID::_kdff protected
Definition at line 170 of file AC_PID.h.
Referenced by kDff(), kDff(), operator()(), and update_all().
_kff
AP_Float AC_PID::_kff protected
Definition at line 163 of file AC_PID.h.
Referenced by ff(), ff(), load_gains(), operator()(), save_gains(), and update_all().
_ki
AP_Float AC_PID::_ki protected
Definition at line 161 of file AC_PID.h.
Referenced by kI(), kI(), load_gains(), operator()(), save_gains(), update_i(), and AC_HELI_PID::update_leaky_i().
_kimax
AP_Float AC_PID::_kimax protected
Definition at line 164 of file AC_PID.h.
Referenced by imax(), imax(), kIMAX(), operator()(), relax_integrator(), set_integrator(), and update_i().
_kp
AP_Float AC_PID::_kp protected
Definition at line 160 of file AC_PID.h.
Referenced by kP(), kP(), kP(), load_gains(), operator()(), save_gains(), and update_all().
_kpdmax
AP_Float AC_PID::_kpdmax protected
Definition at line 165 of file AC_PID.h.
Referenced by kPDMAX(), pdmax(), pdmax(), and update_all().
_pid_info
AP_PIDInfo AC_PID::_pid_info protected
Definition at line 202 of file AC_PID.h.
Referenced by AC_PID(), get_d(), get_ff(), get_p(), get_pid_info(), set_actual_rate(), set_target_rate(), update_all(), update_error(), and update_i().
_slew_limit_scale
int8_t AC_PID::_slew_limit_scale protected
Definition at line 195 of file AC_PID.h.
Referenced by AC_PID(), set_slew_limit_scale(), and update_all().
_slew_limiter
SlewLimiter AC_PID::_slew_limiter {_slew_rate_max, _slew_rate_tau} protected
Definition at line 182 of file AC_PID.h.
Referenced by get_slew_rate(), and update_all().
_slew_rate_max
AP_Float AC_PID::_slew_rate_max protected
Definition at line 169 of file AC_PID.h.
Referenced by slew_limit(), and slew_limit().
_slew_rate_tau
AP_Float AC_PID::_slew_rate_tau protected
Definition at line 180 of file AC_PID.h.
Referenced by AC_PID().
_target
float AC_PID::_target protected
Definition at line 192 of file AC_PID.h.
Referenced by update_all(), and update_error().
_target_derivative
float AC_PID::_target_derivative protected
Definition at line 196 of file AC_PID.h.
Referenced by update_all().
default_filt_D_hz
const float AC_PID::default_filt_D_hz private
Definition at line 213 of file AC_PID.h.
default_filt_E_hz
const float AC_PID::default_filt_E_hz private
Definition at line 212 of file AC_PID.h.
default_filt_T_hz
const float AC_PID::default_filt_T_hz private
Definition at line 211 of file AC_PID.h.
default_kd
const float AC_PID::default_kd private
Definition at line 207 of file AC_PID.h.
default_kdff
const float AC_PID::default_kdff private
Definition at line 209 of file AC_PID.h.
default_kff
const float AC_PID::default_kff private
Definition at line 208 of file AC_PID.h.
default_ki
const float AC_PID::default_ki private
Definition at line 206 of file AC_PID.h.
default_kimax
const float AC_PID::default_kimax private
Definition at line 210 of file AC_PID.h.
default_kp
const float AC_PID::default_kp private
Definition at line 205 of file AC_PID.h.
default_slew_rate_max
const float AC_PID::default_slew_rate_max private
Definition at line 214 of file AC_PID.h.
var_info
const AP_Param::GroupInfo AC_PID::var_info static
Definition at line 9 of file AC_PID.h.
The documentation for this class was generated from the following files:
libraries/AC_PID/AC_PID.h
libraries/AC_PID/AC_PID.cpp