APM:Libraries: EKF_obs_buffer_t< element_type > Class Template Reference
EKF_obs_buffer_t< element_type > Class Template Reference
#include <EKF_Buffer.h>
Public Member Functions
EKF_obs_buffer_t ()
bool init (uint8_t _size)
bool recall (element_type &element, uint32_t sample_time)
void push (const element_type &element)
void reset ()
Additional Inherited Members
Private Member Functions inherited from ekf_ring_buffer
ekf_ring_buffer (uint8_t elsize)
bool init (uint8_t size)
bool recall (void *element, const uint32_t sample_time_ms)
void push (const void *element)
void reset ()
Detailed Description
template<typename element_type>
class EKF_obs_buffer_t< element_type >
Definition at line 63 of file EKF_Buffer.h.
Constructor & Destructor Documentation
EKF_obs_buffer_t()
template<typename element_type > EKF_obs_buffer_t< element_type >::EKF_obs_buffer_t () inline
Definition at line 70 of file EKF_Buffer.h.
Member Function Documentation
init()
template<typename element_type > bool EKF_obs_buffer_t< element_type >::init (uint8_t _size) inline
Definition at line 74 of file EKF_Buffer.h.
Referenced by TEST().
push()
template<typename element_type > void EKF_obs_buffer_t< element_type >::push (const element_type & element) inline
Definition at line 82 of file EKF_Buffer.h.
Referenced by TEST().
recall()
template<typename element_type > bool EKF_obs_buffer_t< element_type >::recall (element_type & element, uint32_t sample_time) inline
Definition at line 78 of file EKF_Buffer.h.
Referenced by TEST().
reset()
template<typename element_type > void EKF_obs_buffer_t< element_type >::reset () inline
Definition at line 86 of file EKF_Buffer.h.
The documentation for this class was generated from the following file:
libraries/AP_NavEKF/EKF_Buffer.h