APM:Libraries: SCurve Class Reference
SCurve Class Reference
#include <SCurve.h>
Public Member Functions
SCurve ()
void init ()
void calculate_track (const Vector3f &origin, const Vector3f &destination, float speed_xy, float speed_up, float speed_down, float accel_xy, float accel_z, float snap_maximum, float jerk_maximum)
void set_speed_max (float speed_xy, float speed_up, float speed_down)
float set_origin_speed_max (float speed)
void set_destination_speed_max (float speed)
bool advance_target_along_track (SCurve &prev_leg, SCurve &next_leg, float wp_radius, float accel_corner, bool fast_waypoint, float dt, Vector3f &target_pos, Vector3f &target_vel, Vector3f &target_accel) WARN_IF_UNUSED
bool finished () const WARN_IF_UNUSED
Static Public Member Functions
static void calculate_path (float Sm, float Jm, float V0, float Am, float Vm, float L, float &Jm_out, float &tj_out, float &t2_out, float &t4_out, float &t6_out)
Private Types
enum class SegmentType { CONSTANT_JERK , POSITIVE_JERK , NEGATIVE_JERK }
Private Member Functions
void move_from_pos_vel_accel (float dt, Vector3f &pos, Vector3f &vel, Vector3f &accel)
void move_to_pos_vel_accel (float dt, Vector3f &pos, Vector3f &vel, Vector3f &accel)
void move_from_time_pos_vel_accel (float t, Vector3f &pos, Vector3f &vel, Vector3f &accel)
float get_speed_along_track () const WARN_IF_UNUSED
float get_accel_along_track () const WARN_IF_UNUSED
const Vector3f & get_track () const WARN_IF_UNUSED
float get_time_elapsed () const WARN_IF_UNUSED
float time_end () const WARN_IF_UNUSED
float get_time_remaining () const WARN_IF_UNUSED
float get_accel_finished_time () const WARN_IF_UNUSED
bool braking () const WARN_IF_UNUSED
float time_turn_in () const WARN_IF_UNUSED
float time_turn_out () const WARN_IF_UNUSED
void advance_time (float dt)
void get_jerk_accel_vel_pos_at_time (float time_now, float &Jt_out, float &At_out, float &Vt_out, float &Pt_out) const
void calc_javp_for_segment_const_jerk (float time_now, float J0, float A0, float V0, float P0, float &Jt, float &At, float &Vt, float &Pt) const
void calc_javp_for_segment_incr_jerk (float time_now, float tj, float Jm, float A0, float V0, float P0, float &Jt, float &At, float &Vt, float &Pt) const
void calc_javp_for_segment_decr_jerk (float time_now, float tj, float Jm, float A0, float V0, float P0, float &Jt, float &At, float &Vt, float &Pt) const
void add_segments (float L)
void add_segments_jerk (uint8_t &seg_pnt, float Jm, float tj, float Tcj)
void add_segment_const_jerk (uint8_t &seg_pnt, float J0, float tin)
void add_segment_incr_jerk (uint8_t &seg_pnt, float Jm, float tj)
void add_segment_decr_jerk (uint8_t &seg_pnt, float Jm, float tj)
void set_kinematic_limits (const Vector3f &origin, const Vector3f &destination, float speed_xy, float speed_up, float speed_down, float accel_xy, float accel_z)
bool valid () const WARN_IF_UNUSED
void debug () const
void add_segment (uint8_t &seg_pnt, float end_time, SegmentType seg_type, float jerk_ref, float end_accel, float end_vel, float end_pos)
Private Attributes
float snap_max
float jerk_max
float accel_max
float vel_max
float time
float position_sq
uint8_t num_segs
struct {
float jerk_ref
SegmentType seg_type
float end_time
float end_accel
float end_vel
float end_pos
} segment [segments_max]
Vector3f track
Vector3f delta_unit
Static Private Attributes
static const uint8_t segments_max = 23
Detailed Description
Definition at line 45 of file SCurve.h.
Member Enumeration Documentation
SegmentType
enum class SCurve::SegmentType strong private
Enumerator
CONSTANT_JERK
POSITIVE_JERK
NEGATIVE_JERK
Definition at line 184 of file SCurve.h.
Constructor & Destructor Documentation
SCurve()
SCurve::SCurve ()
Definition at line 41 of file SCurve.cpp.
Member Function Documentation
add_segment()
void SCurve::add_segment (uint8_t & seg_pnt, float end_time, SegmentType seg_type, float jerk_ref, float end_accel, float end_vel, float end_pos) private
Definition at line 1019 of file SCurve.cpp.
Referenced by add_segment_const_jerk(), add_segment_decr_jerk(), add_segment_incr_jerk(), init(), set_origin_speed_max(), and set_speed_max().
add_segment_const_jerk()
void SCurve::add_segment_const_jerk (uint8_t & seg_pnt, float J0, float tin) private
Definition at line 934 of file SCurve.cpp.
Referenced by add_segments(), add_segments_jerk(), set_destination_speed_max(), set_origin_speed_max(), and set_speed_max().
add_segment_decr_jerk()
void SCurve::add_segment_decr_jerk (uint8_t & seg_pnt, float Jm, float tj) private
Definition at line 987 of file SCurve.cpp.
Referenced by add_segments_jerk().
add_segment_incr_jerk()
void SCurve::add_segment_incr_jerk (uint8_t & seg_pnt, float Jm, float tj) private
Definition at line 958 of file SCurve.cpp.
Referenced by add_segments_jerk().
add_segments()
void SCurve::add_segments (float L) private
Definition at line 743 of file SCurve.cpp.
Referenced by calculate_track(), and set_speed_max().
add_segments_jerk()
void SCurve::add_segments_jerk (uint8_t & seg_pnt, float Jm, float tj, float Tcj) private
Definition at line 924 of file SCurve.cpp.
Referenced by add_segments(), set_destination_speed_max(), set_origin_speed_max(), and set_speed_max().
advance_target_along_track()
bool SCurve::advance_target_along_track (SCurve & prev_leg, SCurve & next_leg, float wp_radius, float accel_corner, bool fast_waypoint, float dt, Vector3f & target_pos, Vector3f & target_vel, Vector3f & target_accel)
Definition at line 489 of file SCurve.cpp.
Referenced by AR_WPNav::advance_wp_target_along_track(), and AC_WPNav::advance_wp_target_along_track().
advance_time()
void SCurve::advance_time (float dt) private
Definition at line 621 of file SCurve.cpp.
Referenced by move_from_pos_vel_accel(), and move_to_pos_vel_accel().
braking()
bool SCurve::braking () const private
Definition at line 594 of file SCurve.cpp.
calc_javp_for_segment_const_jerk()
void SCurve::calc_javp_for_segment_const_jerk (float time_now, float J0, float A0, float V0, float P0, float & Jt, float & At, float & Vt, float & Pt) const private
Definition at line 689 of file SCurve.cpp.
Referenced by get_jerk_accel_vel_pos_at_time().
calc_javp_for_segment_decr_jerk()
void SCurve::calc_javp_for_segment_decr_jerk (float time_now, float tj, float Jm, float A0, float V0, float P0, float & Jt, float & At, float & Vt, float & Pt) const private
Definition at line 716 of file SCurve.cpp.
Referenced by get_jerk_accel_vel_pos_at_time().
calc_javp_for_segment_incr_jerk()
void SCurve::calc_javp_for_segment_incr_jerk (float time_now, float tj, float Jm, float A0, float V0, float P0, float & Jt, float & At, float & Vt, float & Pt) const private
Definition at line 698 of file SCurve.cpp.
Referenced by get_jerk_accel_vel_pos_at_time().
calculate_path()
void SCurve::calculate_path (float Sm, float Jm, float V0, float Am, float Vm, float L, float & Jm_out, float & tj_out, float & t2_out, float & t4_out, float & t6_out) static
Definition at line 788 of file SCurve.cpp.
Referenced by add_segments(), set_destination_speed_max(), set_origin_speed_max(), set_speed_max(), and TEST().
calculate_track()
void SCurve::calculate_track (const Vector3f & origin, const Vector3f & destination, float speed_xy, float speed_up, float speed_down, float accel_xy, float accel_z, float snap_maximum, float jerk_maximum)
Definition at line 63 of file SCurve.cpp.
Referenced by AR_WPNav::set_desired_location(), AC_WPNav::set_wp_destination(), and AC_WPNav::set_wp_destination_next().
debug()
void SCurve::debug () const private
Definition at line 1091 of file SCurve.cpp.
Referenced by calculate_track(), set_destination_speed_max(), set_origin_speed_max(), and set_speed_max().
finished()
bool SCurve::finished () const
Definition at line 523 of file SCurve.cpp.
Referenced by advance_target_along_track(), AR_WPNav::set_desired_location(), and AC_WPNav::set_wp_destination().
get_accel_along_track()
float SCurve::get_accel_along_track () const inline private
Definition at line 112 of file SCurve.h.
get_accel_finished_time()
float SCurve::get_accel_finished_time () const private
Definition at line 585 of file SCurve.cpp.
get_jerk_accel_vel_pos_at_time()
void SCurve::get_jerk_accel_vel_pos_at_time (float time_now, float & Jt_out, float & At_out, float & Vt_out, float & Pt_out) const private
Definition at line 627 of file SCurve.cpp.
Referenced by move_from_pos_vel_accel(), move_from_time_pos_vel_accel(), move_to_pos_vel_accel(), and set_speed_max().
get_speed_along_track()
float SCurve::get_speed_along_track () const inline private
Definition at line 109 of file SCurve.h.
Referenced by advance_target_along_track().
get_time_elapsed()
float SCurve::get_time_elapsed () const inline private
Definition at line 118 of file SCurve.h.
Referenced by advance_target_along_track().
get_time_remaining()
float SCurve::get_time_remaining () const private
Definition at line 576 of file SCurve.cpp.
Referenced by advance_target_along_track().
get_track()
const Vector3f & SCurve::get_track () const inline private
Definition at line 115 of file SCurve.h.
Referenced by advance_target_along_track().
init()
void SCurve::init ()
Definition at line 47 of file SCurve.cpp.
Referenced by calculate_track(), AC_WPNav::force_stop_at_next_wp(), AR_WPNav::init(), SCurve(), AR_WPNav::set_desired_location(), set_destination_speed_max(), set_origin_speed_max(), set_speed_max(), AC_WPNav::set_wp_destination(), and AC_WPNav::wp_and_spline_init().
move_from_pos_vel_accel()
void SCurve::move_from_pos_vel_accel (float dt, Vector3f & pos, Vector3f & vel, Vector3f & accel) private
Definition at line 529 of file SCurve.cpp.
Referenced by advance_target_along_track().
move_from_time_pos_vel_accel()
void SCurve::move_from_time_pos_vel_accel (float t, Vector3f & pos, Vector3f & vel, Vector3f & accel) private
Definition at line 556 of file SCurve.cpp.
Referenced by advance_target_along_track().
move_to_pos_vel_accel()
void SCurve::move_to_pos_vel_accel (float dt, Vector3f & pos, Vector3f & vel, Vector3f & accel) private
Definition at line 542 of file SCurve.cpp.
Referenced by advance_target_along_track().
set_destination_speed_max()
void SCurve::set_destination_speed_max (float speed)
Definition at line 432 of file SCurve.cpp.
Referenced by AC_WPNav::force_stop_at_next_wp(), set_speed_max(), and AC_WPNav::set_spline_destination_next().
set_kinematic_limits()
void SCurve::set_kinematic_limits (const Vector3f & origin, const Vector3f & destination, float speed_xy, float speed_up, float speed_down, float accel_xy, float accel_z) private
Definition at line 1033 of file SCurve.cpp.
Referenced by calculate_track().
set_origin_speed_max()
float SCurve::set_origin_speed_max (float speed)
Definition at line 350 of file SCurve.cpp.
Referenced by set_speed_max(), AC_WPNav::set_wp_destination(), and AC_WPNav::set_wp_destination_next().
set_speed_max()
void SCurve::set_speed_max (float speed_xy, float speed_up, float speed_down)
Definition at line 116 of file SCurve.cpp.
Referenced by AR_WPNav::update_speed_max(), and AC_WPNav::update_track_with_speed_accel_limits().
time_end()
float SCurve::time_end () const private
Definition at line 567 of file SCurve.cpp.
Referenced by advance_target_along_track(), advance_time(), and finished().
time_turn_in()
float SCurve::time_turn_in () const private
Definition at line 603 of file SCurve.cpp.
Referenced by advance_target_along_track().
time_turn_out()
float SCurve::time_turn_out () const private
Definition at line 612 of file SCurve.cpp.
Referenced by advance_target_along_track().
valid()
bool SCurve::valid () const private
Definition at line 1053 of file SCurve.cpp.
Referenced by calculate_track(), set_destination_speed_max(), set_origin_speed_max(), and set_speed_max().
Member Data Documentation
accel_max
float SCurve::accel_max private
Definition at line 196 of file SCurve.h.
Referenced by add_segments(), calculate_track(), debug(), get_accel_along_track(), init(), set_destination_speed_max(), set_kinematic_limits(), set_origin_speed_max(), and set_speed_max().
delta_unit
Vector3f SCurve::delta_unit private
Definition at line 219 of file SCurve.h.
Referenced by calculate_track(), debug(), init(), move_from_pos_vel_accel(), move_from_time_pos_vel_accel(), move_to_pos_vel_accel(), and set_speed_max().
end_accel
float SCurve::end_accel
Definition at line 213 of file SCurve.h.
Referenced by add_segment(), add_segment_const_jerk(), add_segment_decr_jerk(), add_segment_incr_jerk(), debug(), set_speed_max(), and valid().
end_pos
float SCurve::end_pos
Definition at line 215 of file SCurve.h.
Referenced by add_segment(), add_segment_const_jerk(), add_segment_decr_jerk(), add_segment_incr_jerk(), add_segments(), debug(), set_destination_speed_max(), set_origin_speed_max(), set_speed_max(), and valid().
end_time
float SCurve::end_time
Definition at line 212 of file SCurve.h.
Referenced by add_segment(), add_segment_const_jerk(), add_segment_decr_jerk(), add_segment_incr_jerk(), debug(), get_jerk_accel_vel_pos_at_time(), set_speed_max(), and valid().
end_vel
float SCurve::end_vel
Definition at line 214 of file SCurve.h.
Referenced by add_segment(), add_segment_const_jerk(), add_segment_decr_jerk(), add_segment_incr_jerk(), add_segments(), debug(), set_destination_speed_max(), set_origin_speed_max(), set_speed_max(), and valid().
jerk_max
float SCurve::jerk_max private
Definition at line 195 of file SCurve.h.
Referenced by add_segments(), calculate_track(), debug(), init(), set_destination_speed_max(), set_origin_speed_max(), and set_speed_max().
jerk_ref
float SCurve::jerk_ref
Definition at line 210 of file SCurve.h.
Referenced by add_segment(), debug(), and valid().
num_segs
uint8_t SCurve::num_segs private
Definition at line 208 of file SCurve.h.
Referenced by add_segments(), braking(), debug(), get_accel_finished_time(), get_jerk_accel_vel_pos_at_time(), get_time_remaining(), init(), set_destination_speed_max(), set_origin_speed_max(), set_speed_max(), time_end(), time_turn_in(), time_turn_out(), and valid().
position_sq
float SCurve::position_sq private
Definition at line 199 of file SCurve.h.
Referenced by advance_target_along_track(), finished(), init(), move_from_pos_vel_accel(), and move_to_pos_vel_accel().
seg_type
SegmentType SCurve::seg_type
Definition at line 211 of file SCurve.h.
Referenced by add_segment(), and debug().
[struct]
struct { ... } SCurve::segment[segments_max]
Referenced by add_segment(), add_segment_const_jerk(), add_segment_decr_jerk(), add_segment_incr_jerk(), add_segments(), braking(), debug(), get_accel_finished_time(), get_jerk_accel_vel_pos_at_time(), get_time_remaining(), set_destination_speed_max(), set_origin_speed_max(), set_speed_max(), time_end(), time_turn_in(), time_turn_out(), and valid().
segments_max
const uint8_t SCurve::segments_max = 23 static private
Definition at line 206 of file SCurve.h.
Referenced by braking(), get_accel_finished_time(), get_jerk_accel_vel_pos_at_time(), get_time_remaining(), set_destination_speed_max(), set_origin_speed_max(), set_speed_max(), time_end(), time_turn_in(), time_turn_out(), and valid().
snap_max
float SCurve::snap_max private
Definition at line 194 of file SCurve.h.
Referenced by add_segments(), calculate_track(), debug(), init(), set_destination_speed_max(), set_origin_speed_max(), and set_speed_max().
time
float SCurve::time private
Definition at line 198 of file SCurve.h.
Referenced by advance_time(), braking(), debug(), finished(), get_time_elapsed(), get_time_remaining(), init(), move_from_pos_vel_accel(), move_to_pos_vel_accel(), and set_speed_max().
track
Vector3f SCurve::track private
Definition at line 218 of file SCurve.h.
Referenced by advance_target_along_track(), calculate_track(), debug(), finished(), get_track(), init(), move_to_pos_vel_accel(), set_destination_speed_max(), and set_origin_speed_max().
vel_max
float SCurve::vel_max private
Definition at line 197 of file SCurve.h.
Referenced by add_segments(), calculate_track(), debug(), get_speed_along_track(), init(), set_kinematic_limits(), and set_speed_max().
The documentation for this class was generated from the following files:
libraries/AP_Math/SCurve.h
libraries/AP_Math/SCurve.cpp