APM:Libraries: AP_WindVane_Backend Class Reference
AP_WindVane_Backend Class Reference
#include <AP_WindVane_Backend.h>
Public Member Functions
AP_WindVane_Backend (AP_WindVane &frontend)
virtual ~AP_WindVane_Backend ()
virtual void init (const AP_SerialManager &serial_manager)
virtual void update_speed ()
virtual void update_direction ()
virtual void calibrate ()
Protected Attributes
AP_WindVane & _frontend
Detailed Description
Definition at line 23 of file AP_WindVane_Backend.h.
Constructor & Destructor Documentation
AP_WindVane_Backend()
AP_WindVane_Backend::AP_WindVane_Backend (AP_WindVane & frontend)
Definition at line 26 of file AP_WindVane_Backend.cpp.
~AP_WindVane_Backend()
virtual AP_WindVane_Backend::~AP_WindVane_Backend () inline virtual
Definition at line 31 of file AP_WindVane_Backend.h.
Member Function Documentation
calibrate()
void AP_WindVane_Backend::calibrate () virtual
Reimplemented in AP_WindVane_Analog, and AP_WindVane_ModernDevice.
Definition at line 32 of file AP_WindVane_Backend.cpp.
Referenced by AP_WindVane::update().
init()
virtual void AP_WindVane_Backend::init (const AP_SerialManager & serial_manager) inline virtual
Reimplemented in AP_WindVane_NMEA.
Definition at line 34 of file AP_WindVane_Backend.h.
Referenced by AP_WindVane::init().
update_direction()
virtual void AP_WindVane_Backend::update_direction () inline virtual
Reimplemented in AP_WindVane_Analog, AP_WindVane_Home, and AP_WindVane_NMEA.
Definition at line 38 of file AP_WindVane_Backend.h.
Referenced by AP_WindVane::update().
update_speed()
virtual void AP_WindVane_Backend::update_speed () inline virtual
Reimplemented in AP_WindVane_ModernDevice, and AP_WindVane_NMEA.
Definition at line 37 of file AP_WindVane_Backend.h.
Referenced by AP_WindVane::update().
Member Data Documentation
_frontend
AP_WindVane& AP_WindVane_Backend::_frontend protected
Definition at line 43 of file AP_WindVane_Backend.h.
Referenced by calibrate(), AP_WindVane_Analog::calibrate(), AP_WindVane_ModernDevice::calibrate(), AP_WindVane_NMEA::update(), AP_WindVane_Analog::update_direction(), AP_WindVane_Home::update_direction(), AP_WindVane_NMEA::update_direction(), and AP_WindVane_ModernDevice::update_speed().
The documentation for this class was generated from the following files:
libraries/AP_WindVane/AP_WindVane_Backend.h
libraries/AP_WindVane/AP_WindVane_Backend.cpp