APM:Libraries: AP_Logger Class Reference
AP_Logger Class Reference
#include <AP_Logger.h>
Classes
struct log_write_fmt
struct log_write_fmt_strings
Public Types
enum class LogDisarmed : uint8_t { NONE = 0 , LOG_WHILE_DISARMED = 1 , LOG_WHILE_DISARMED_NOT_USB = 2 , LOG_WHILE_DISARMED_DISCARD = 3 }
Public Member Functions
FUNCTOR_TYPEDEF (vehicle_startup_message_Writer, void)
AP_Logger ()
CLASS_NO_COPY (AP_Logger)
void init (const AP_Int32 &log_bitmask, const struct LogStructure *structure, uint8_t num_types)
void set_num_types (uint8_t num_types)
bool CardInserted (void)
void log_pause (bool value)
void EraseAll ()
void WriteBlock (const void *pBuffer, uint16_t size)
bool WriteBlock_first_succeed (const void *pBuffer, uint16_t size)
void WriteCriticalBlock (const void *pBuffer, uint16_t size)
bool WriteReplayBlock (uint8_t msg_id, const void *pBuffer, uint16_t size)
uint16_t find_last_log () const
void get_log_boundaries (uint16_t log_num, uint32_t &start_page, uint32_t &end_page)
uint16_t get_num_logs (void)
uint16_t get_max_num_logs ()
void setVehicle_Startup_Writer (vehicle_startup_message_Writer writer)
void PrepForArming ()
void EnableWrites (bool enable)
bool WritesEnabled () const
void StopLogging ()
void Write_Parameter (const char *name, float value)
void Write_Event (LogEvent id)
void Write_Error (LogErrorSubsystem sub_system, LogErrorCode error_code)
void Write_RCIN (void)
void Write_RCOUT (void)
void Write_RSSI ()
void Write_Rally ()
void Write_NamedValueFloat (const char *name, float value)
void Write_Power (void)
void Write_Radio (const mavlink_radio_t &packet)
void Write_Message (const char *message)
void Write_MessageF (const char *fmt,...)
void Write_ServoStatus (uint64_t time_us, uint8_t id, float position, float force, float speed, uint8_t power_pct, float pos_cmd, float voltage, float current, float mot_temp, float pcb_temp, uint8_t error)
void Write_Compass ()
void Write_Mode (uint8_t mode, const ModeReason reason)
void Write_EntireMission ()
void Write_Command (const mavlink_command_int_t &packet, uint8_t source_system, uint8_t source_component, MAV_RESULT result, bool was_command_long=false)
void Write_Mission_Cmd (const AP_Mission &mission, const AP_Mission::Mission_Command &cmd)
void Write_RallyPoint (uint8_t total, uint8_t sequence, const class RallyLocation &rally_point)
void Write_SRTL (bool active, uint16_t num_points, uint16_t max_points, uint8_t action, const Vector3f &point)
void Write_Winch (bool healthy, bool thread_end, bool moving, bool clutch, uint8_t mode, float desired_length, float length, float desired_rate, uint16_t tension, float voltage, int8_t temp)
void Write (const char *name, const char *labels, const char *fmt,...)
void Write (const char *name, const char *labels, const char *units, const char *mults, const char *fmt,...)
void WriteStreaming (const char *name, const char *labels, const char *fmt,...)
void WriteStreaming (const char *name, const char *labels, const char *units, const char *mults, const char *fmt,...)
void WriteCritical (const char *name, const char *labels, const char *fmt,...)
void WriteCritical (const char *name, const char *labels, const char *units, const char *mults, const char *fmt,...)
void WriteV (const char *name, const char *labels, const char *units, const char *mults, const char *fmt, va_list arg_list, bool is_critical=false, bool is_streaming=false)
void Write_PID (uint8_t msg_type, const class AP_PIDInfo &info)
bool should_log (uint32_t mask) const
bool logging_started (void)
void flush (void)
void handle_mavlink_msg (class GCS_MAVLINK &, const mavlink_message_t &msg)
void periodic_tasks ()
bool allow_start_ekf () const
uint32_t num_dropped (void) const
void set_force_log_disarmed (bool force_logging)
void set_long_log_persist (bool b)
bool log_while_disarmed (void) const
bool in_log_persistance (void) const
uint8_t log_replay (void) const
const struct LogStructure * structure (uint16_t num) const
const struct UnitStructure * unit (uint16_t num) const
const struct MultiplierStructure * multiplier (uint16_t num) const
bool logging_present () const
bool logging_enabled () const
bool logging_failed () const
void arming_failure ()
void set_vehicle_armed (bool armed_state)
bool vehicle_is_armed () const
void handle_log_send ()
bool in_log_download () const
float quiet_nanf () const
double quiet_nan () const
bool msg_type_in_use (uint8_t msg_type) const
int16_t Write_calc_msg_len (const char *fmt) const
struct log_write_fmt * msg_fmt_for_name (const char *name, const char *labels, const char *units, const char *mults, const char *fmt, const bool direct_comp=false, const bool copy_strings=false)
void Safe_Write_Emit_FMT (log_write_fmt *f)
uint8_t get_log_start_count (void) const
void log_file_content (const char *name)
Static Public Member Functions
static AP_Logger * get_singleton (void)
Public Attributes
bool _log_pause
vehicle_startup_message_Writer _vehicle_messages
struct {
AP_Int8 backend_types
AP_Int16 file_bufsize
AP_Int8 file_disarm_rot
AP_Enum< LogDisarmed > log_disarmed
AP_Int8 log_replay
AP_Int8 mav_bufsize
AP_Int16 file_timeout
AP_Int16 min_MB_free
AP_Float file_ratemax
AP_Float mav_ratemax
AP_Float blk_ratemax
AP_Float disarm_ratemax
AP_Int16 max_log_files
} _params
struct AP_Logger::log_write_fmt * log_write_fmts
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical)
Protected Attributes
const struct LogStructure * _structures
uint8_t _num_types
const struct UnitStructure * _units = log_Units
const struct MultiplierStructure * _multipliers = log_Multipliers
const uint8_t _num_units = (sizeof(log_Units) / sizeof(log_Units[0]))
const uint8_t _num_multipliers = (sizeof(log_Multipliers) / sizeof(log_Multipliers[0]))
Private Types
enum class Backend_Type : uint8_t { NONE = 0 , FILESYSTEM = (1<<0) , MAVLINK = (1<<1) , BLOCK = (1<<2) }
enum class RCLoggingFlags : uint8_t { HAS_VALID_INPUT = 1U<<0 , IN_RC_FAILSAFE = 1U<<1 }
enum class TransferActivity { IDLE , LISTING , SENDING }
Private Member Functions
const struct log_write_fmt * log_write_fmt_for_msg_type (uint8_t msg_type) const
const struct LogStructure * structure_for_msg_type (uint8_t msg_type) const
int16_t find_free_msg_type () const
bool fill_log_write_logstructure (struct LogStructure &logstruct, const uint8_t msg_type) const
void Write_Compass_instance (uint64_t time_us, uint8_t mag_instance)
void backend_starting_new_log (const AP_Logger_Backend *backend)
bool validate_structure (const struct LogStructure *logstructure, int16_t offset)
void validate_structures (const struct LogStructure *logstructures, const uint8_t num_types)
void dump_structure_field (const struct LogStructure *logstructure, const char *label, const uint8_t fieldnum)
pretty-print field information from a log structure
void dump_structures (const struct LogStructure *logstructures, const uint8_t num_types)
bool assert_same_fmt_for_name (const log_write_fmt *f, const char *name, const char *labels, const char *units, const char *mults, const char *fmt) const
const char * unit_name (const uint8_t unit_id)
return a unit name given its ID
double multiplier_name (const uint8_t multiplier_id)
return a multiplier value given its ID
bool labels_string_is_good (const char *labels) const
void save_format_Replay (const void *pBuffer)
void start_io_thread (void)
void io_thread ()
bool check_crash_dump_save (void)
void handle_log_message (class GCS_MAVLINK &, const mavlink_message_t &msg)
void handle_log_request_list (class GCS_MAVLINK &, const mavlink_message_t &msg)
void handle_log_request_data (class GCS_MAVLINK &, const mavlink_message_t &msg)
void handle_log_request_erase (class GCS_MAVLINK &, const mavlink_message_t &msg)
void handle_log_request_end (class GCS_MAVLINK &, const mavlink_message_t &msg)
void handle_log_send_listing ()
void handle_log_sending ()
bool handle_log_send_data ()
void get_log_info (uint16_t log_num, uint32_t &size, uint32_t &time_utc)
int16_t get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)
Private Attributes
uint8_t _next_backend
AP_Logger_Backend * backends [LOGGER_MAX_BACKENDS]
const AP_Int32 * _log_bitmask
HAL_Semaphore log_write_fmts_sem
bool _armed
bool should_log_rcin2
bool seen_ids [256] = { }
bool _writes_enabled:1
bool _force_log_disarmed:1
bool _force_long_log_persist:1
bool _io_thread_started
enum AP_Logger::TransferActivity transfer_activity = TransferActivity::IDLE
uint32_t _last_mavlink_log_transfer_message_handled_ms
bool _warned_log_disarm
uint16_t _log_next_list_entry
uint16_t _log_last_list_entry
uint16_t _log_num_logs
uint16_t _log_num_data
uint32_t _log_data_offset
uint32_t _log_data_size
uint32_t _log_data_remaining
uint32_t _log_data_page
GCS_MAVLINK * _log_sending_link
HAL_Semaphore _log_send_sem
uint32_t _last_arming_failure_ms
uint8_t _log_start_count
Static Private Attributes
static AP_Logger * _singleton
Friends
class AP_Logger_Backend
class AP_Logger_RateLimiter
Detailed Description
Definition at line 182 of file AP_Logger.h.
Member Enumeration Documentation
Backend_Type
enum class AP_Logger::Backend_Type : uint8_t strong private
Enumerator
NONE
FILESYSTEM
MAVLINK
BLOCK
Definition at line 428 of file AP_Logger.h.
LogDisarmed
enum class AP_Logger::LogDisarmed : uint8_t strong
Enumerator
NONE
LOG_WHILE_DISARMED
LOG_WHILE_DISARMED_NOT_USB
LOG_WHILE_DISARMED_DISCARD
Definition at line 317 of file AP_Logger.h.
RCLoggingFlags
enum class AP_Logger::RCLoggingFlags : uint8_t strong private
Enumerator
HAS_VALID_INPUT
IN_RC_FAILSAFE
Definition at line 435 of file AP_Logger.h.
TransferActivity
enum class AP_Logger::TransferActivity strong private
Enumerator
IDLE
LISTING
SENDING
Definition at line 538 of file AP_Logger.h.
Constructor & Destructor Documentation
AP_Logger()
AP_Logger::AP_Logger ()
Definition at line 196 of file AP_Logger.cpp.
Member Function Documentation
allow_start_ekf()
bool AP_Logger::allow_start_ekf () const
Definition at line 1062 of file AP_Logger.cpp.
Referenced by allow_start_ekf(), and AP_DAL::start_frame().
arming_failure()
void AP_Logger::arming_failure () inline
Definition at line 355 of file AP_Logger.h.
Referenced by AP_Arming::arm().
assert_same_fmt_for_name()
bool AP_Logger::assert_same_fmt_for_name (const log_write_fmt * f, const char * name, const char * labels, const char * units, const char * mults, const char * fmt) const private
Definition at line 1078 of file AP_Logger.cpp.
Referenced by msg_fmt_for_name().
backend_starting_new_log()
void AP_Logger::backend_starting_new_log (const AP_Logger_Backend * backend) private
Definition at line 614 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::start_new_log_reset_variables().
CardInserted()
bool AP_Logger::CardInserted (void)
Definition at line 792 of file AP_Logger.cpp.
Referenced by CardInserted().
check_crash_dump_save()
bool AP_Logger::check_crash_dump_save (void) private
Definition at line 1400 of file AP_Logger.cpp.
Referenced by io_thread().
CLASS_NO_COPY()
AP_Logger::CLASS_NO_COPY (AP_Logger)
dump_structure_field()
void AP_Logger::dump_structure_field (const struct LogStructure * logstructure, const char * label, const uint8_t fieldnum) private
pretty-print field information from a log structure
Definition at line 314 of file AP_Logger.cpp.
Referenced by dump_structures().
dump_structures()
void AP_Logger::dump_structures (const struct LogStructure * logstructures, const uint8_t num_types) private
pretty-print log structures
Note
structures MUST be well-formed
Definition at line 321 of file AP_Logger.cpp.
Referenced by init().
EnableWrites()
void AP_Logger::EnableWrites (bool enable) inline
Definition at line 237 of file AP_Logger.h.
Referenced by init(), and AP_Vehicle::scheduler_delay_callback().
EraseAll()
void AP_Logger::EraseAll ()
Definition at line 788 of file AP_Logger.cpp.
Referenced by EraseAll().
fill_log_write_logstructure()
bool AP_Logger::fill_log_write_logstructure (struct LogStructure & logstruct, const uint8_t msg_type) const private
Definition at line 1316 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::Write_Emit_FMT().
find_free_msg_type()
int16_t AP_Logger::find_free_msg_type () const private
Definition at line 1300 of file AP_Logger.cpp.
Referenced by msg_fmt_for_name().
find_last_log()
uint16_t AP_Logger::find_last_log () const
Definition at line 806 of file AP_Logger.cpp.
Referenced by AP_LoggerTest_AllTypes::Log_Write_TypeMessages(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), and AP_LoggerTest::setup().
flush()
void AP_Logger::flush (void)
Definition at line 882 of file AP_Logger.cpp.
Referenced by flush(), AP_LoggerTest_AllTypes::flush_logger(), and AP_LoggerTest::setup().
FUNCTOR_TYPEDEF()
AP_Logger::FUNCTOR_TYPEDEF (vehicle_startup_message_Writer , void)
get_log_boundaries()
void AP_Logger::get_log_boundaries (uint16_t log_num, uint32_t & start_page, uint32_t & end_page)
Definition at line 812 of file AP_Logger.cpp.
get_log_data()
int16_t AP_Logger::get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t * data) private
Definition at line 824 of file AP_Logger.cpp.
get_log_info()
void AP_Logger::get_log_info (uint16_t log_num, uint32_t & size, uint32_t & time_utc) private
Definition at line 818 of file AP_Logger.cpp.
get_log_start_count()
uint8_t AP_Logger::get_log_start_count (void) const inline
Definition at line 400 of file AP_Logger.h.
get_max_num_logs()
uint16_t AP_Logger::get_max_num_logs ()
Definition at line 837 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::log_num_from_list_entry().
get_num_logs()
uint16_t AP_Logger::get_num_logs (void)
Definition at line 830 of file AP_Logger.cpp.
get_singleton()
static AP_Logger * AP_Logger::get_singleton (void) inline static
Definition at line 196 of file AP_Logger.h.
Referenced by ChibiOS::Scheduler::_monitor_thread(), AP_Arming::arm_checks(), RC_Channel::do_aux_function(), GCS_MAVLINK::handle_named_value(), GCS_MAVLINK::handle_param_set(), GCS_MAVLINK::handle_statustext(), GCS_MAVLINK::handle_timesync(), AP_InertialSensor_Backend::log_accel_raw(), AP_InertialSensor_Backend::log_gyro_raw(), AP::logger(), AP_BattMonitor::read(), ChibiOS::Scheduler::reboot(), GCS::send_parameter_value(), GCS::send_textv(), SRV_Channels::set_emergency_stop(), and AP_GPS::should_log().
handle_log_message()
void AP_Logger::handle_log_message (class GCS_MAVLINK & , const mavlink_message_t & msg) private
Referenced by handle_mavlink_msg().
handle_log_request_data()
void AP_Logger::handle_log_request_data (class GCS_MAVLINK & , const mavlink_message_t & msg) private
handle_log_request_end()
void AP_Logger::handle_log_request_end (class GCS_MAVLINK & , const mavlink_message_t & msg) private
handle_log_request_erase()
void AP_Logger::handle_log_request_erase (class GCS_MAVLINK & , const mavlink_message_t & msg) private
handle_log_request_list()
void AP_Logger::handle_log_request_list (class GCS_MAVLINK & , const mavlink_message_t & msg) private
handle_log_send()
void AP_Logger::handle_log_send ()
Referenced by periodic_tasks(), and GCS_MAVLINK::update_send().
handle_log_send_data()
bool AP_Logger::handle_log_send_data () private
handle_log_send_listing()
void AP_Logger::handle_log_send_listing () private
handle_log_sending()
void AP_Logger::handle_log_sending () private
handle_mavlink_msg()
void AP_Logger::handle_mavlink_msg (class GCS_MAVLINK & link, const mavlink_message_t & msg)
Definition at line 855 of file AP_Logger.cpp.
Referenced by GCS_MAVLINK::handle_message().
in_log_download()
bool AP_Logger::in_log_download () const
Definition at line 651 of file AP_Logger.cpp.
Referenced by should_log(), AP_Logger_Backend::ShouldLog(), and AP_Logger_Backend::StartNewLogOK().
in_log_persistance()
bool AP_Logger::in_log_persistance (void) const
Definition at line 1514 of file AP_Logger.cpp.
Referenced by log_while_disarmed(), and AP_Logger_RateLimiter::should_log().
init()
void AP_Logger::init (const AP_Int32 & log_bitmask, const struct LogStructure * structure, uint8_t num_types)
Definition at line 206 of file AP_Logger.cpp.
Referenced by setup(), AP_LoggerTest::setup(), AP_LoggerTest_AllTypes::setup(), and AP_Vehicle::setup().
io_thread()
void AP_Logger::io_thread (void) private
Definition at line 1428 of file AP_Logger.cpp.
Referenced by start_io_thread().
labels_string_is_good()
bool AP_Logger::labels_string_is_good (const char * labels) const private
Definition at line 350 of file AP_Logger.cpp.
Referenced by validate_structure().
log_file_content()
void AP_Logger::log_file_content (const char * name)
log_pause()
void AP_Logger::log_pause (bool value) inline
Definition at line 208 of file AP_Logger.h.
Referenced by RC_Channel::do_aux_function().
log_replay()
uint8_t AP_Logger::log_replay (void) const inline
Definition at line 313 of file AP_Logger.h.
log_while_disarmed()
bool AP_Logger::log_while_disarmed (void) const
Definition at line 1541 of file AP_Logger.cpp.
Referenced by allow_start_ekf(), AP_Logger_Backend::logging_enabled(), should_log(), AP_Logger_Backend::ShouldLog(), and WriteReplayBlock().
log_write_fmt_for_msg_type()
const struct AP_Logger::log_write_fmt * AP_Logger::log_write_fmt_for_msg_type (uint8_t msg_type) const private
Definition at line 1266 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::validate_WritePrioritisedBlock().
logging_enabled()
bool AP_Logger::logging_enabled () const
Definition at line 576 of file AP_Logger.cpp.
Referenced by logging_enabled(), SRV_Channels::set_emergency_stop(), and GCS::update_sensor_status_flags().
logging_failed()
bool AP_Logger::logging_failed () const
Definition at line 588 of file AP_Logger.cpp.
Referenced by logging_failed(), and GCS::update_sensor_status_flags().
logging_present()
bool AP_Logger::logging_present () const
Definition at line 572 of file AP_Logger.cpp.
Referenced by AP_Arming::arm_checks(), and GCS::update_sensor_status_flags().
logging_started()
bool AP_Logger::logging_started (void)
Definition at line 846 of file AP_Logger.cpp.
Referenced by AP_Arming::arm_checks(), logging_started(), and AP_DAL::start_frame().
msg_fmt_for_name()
AP_Logger::log_write_fmt * AP_Logger::msg_fmt_for_name (const char * name, const char * labels, const char * units, const char * mults, const char * fmt, const bool direct_comp = false, const bool copy_strings = false)
Definition at line 1126 of file AP_Logger.cpp.
Referenced by WriteV().
msg_type_in_use()
bool AP_Logger::msg_type_in_use (uint8_t msg_type) const
Definition at line 1279 of file AP_Logger.cpp.
Referenced by find_free_msg_type().
multiplier()
const struct MultiplierStructure * AP_Logger::multiplier (uint16_t num) const
Definition at line 666 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::multiplier().
multiplier_name()
double AP_Logger::multiplier_name (const uint8_t multiplier_id) private
return a multiplier value given its ID
Definition at line 302 of file AP_Logger.cpp.
Referenced by dump_structure_field().
num_dropped()
uint32_t AP_Logger::num_dropped (void) const
Definition at line 962 of file AP_Logger.cpp.
periodic_tasks()
void AP_Logger::periodic_tasks ()
Definition at line 873 of file AP_Logger.cpp.
Referenced by loop(), and periodic_tasks().
PrepForArming()
void AP_Logger::PrepForArming ()
Definition at line 678 of file AP_Logger.cpp.
Referenced by AP_Arming::arm_checks(), ReplayGyroFFT::loop(), and PrepForArming().
quiet_nan()
double AP_Logger::quiet_nan () const inline
Definition at line 369 of file AP_Logger.h.
Referenced by AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write().
quiet_nanf()
float AP_Logger::quiet_nanf () const inline
Definition at line 368 of file AP_Logger.h.
Referenced by AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), LoggerMessageWriter_DFLogStart::process(), LoggerMessageWriter_DFLogStart::reset(), and Write_Parameter().
Safe_Write_Emit_FMT()
void AP_Logger::Safe_Write_Emit_FMT (log_write_fmt * f)
Definition at line 950 of file AP_Logger.cpp.
save_format_Replay()
void AP_Logger::save_format_Replay (const void * pBuffer) private
set_force_log_disarmed()
void AP_Logger::set_force_log_disarmed (bool force_logging) inline
Definition at line 309 of file AP_Logger.h.
set_long_log_persist()
void AP_Logger::set_long_log_persist (bool b) inline
Definition at line 310 of file AP_Logger.h.
set_num_types()
void AP_Logger::set_num_types (uint8_t num_types) inline
Definition at line 202 of file AP_Logger.h.
set_vehicle_armed()
void AP_Logger::set_vehicle_armed (bool armed_state)
Definition at line 688 of file AP_Logger.cpp.
Referenced by ReplayGyroFFT::loop(), AP_LoggerTest::setup(), and AP_LoggerTest_AllTypes::setup().
setVehicle_Startup_Writer()
void AP_Logger::setVehicle_Startup_Writer (vehicle_startup_message_Writer writer)
Definition at line 683 of file AP_Logger.cpp.
should_log()
bool AP_Logger::should_log (uint32_t mask) const
Definition at line 629 of file AP_Logger.cpp.
Referenced by AP_BattMonitor::read(), and AP_GPS::should_log().
start_io_thread()
void AP_Logger::start_io_thread (void) private
Definition at line 1466 of file AP_Logger.cpp.
Referenced by init().
StopLogging()
void AP_Logger::StopLogging ()
Definition at line 801 of file AP_Logger.cpp.
Referenced by AP_LoggerTest_AllTypes::Log_Write_TypeMessages(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), and ChibiOS::Scheduler::reboot().
structure()
const struct LogStructure * AP_Logger::structure (uint16_t num) const
Definition at line 567 of file AP_Logger.cpp.
Referenced by msg_type_in_use(), AP_Logger_Backend::structure(), and structure_for_msg_type().
structure_for_msg_type()
const struct LogStructure * AP_Logger::structure_for_msg_type (uint8_t msg_type) const private
Definition at line 1254 of file AP_Logger.cpp.
Referenced by AP_Logger_RateLimiter::should_log(), and AP_Logger_Backend::validate_WritePrioritisedBlock().
unit()
const struct UnitStructure * AP_Logger::unit (uint16_t num) const
Definition at line 661 of file AP_Logger.cpp.
Referenced by AP_Logger_Backend::unit().
unit_name()
const char * AP_Logger::unit_name (const uint8_t unit_id) private
return a unit name given its ID
Definition at line 291 of file AP_Logger.cpp.
Referenced by dump_structure_field().
validate_structure()
bool AP_Logger::validate_structure (const struct LogStructure * logstructure, int16_t offset) private
Definition at line 392 of file AP_Logger.cpp.
Referenced by msg_fmt_for_name(), and validate_structures().
validate_structures()
void AP_Logger::validate_structures (const struct LogStructure * logstructures, const uint8_t num_types) private
Definition at line 512 of file AP_Logger.cpp.
Referenced by init().
vehicle_is_armed()
bool AP_Logger::vehicle_is_armed () const inline
Definition at line 363 of file AP_Logger.h.
Referenced by should_log(), and AP_Logger_Backend::ShouldLog().
Write() [1/2]
void AP_Logger::Write (const char * name, const char * labels, const char * fmt, ...)
Definition at line 974 of file AP_Logger.cpp.
Referenced by SCurve::calculate_path(), GCS_MAVLINK::handle_named_value(), GCS_MAVLINK::handle_timesync(), AP_InertialSensor_Backend::log_register_change(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), RC_Channel::run_aux_function(), AP_Relay::set_pin_by_instance(), AP_LoggerTest::setup(), and AP_Compass_MMC3416::timer().
Write() [2/2]
void AP_Logger::Write (const char * name, const char * labels, const char * units, const char * mults, const char * fmt, ...)
Definition at line 983 of file AP_Logger.cpp.
Write_calc_msg_len()
int16_t AP_Logger::Write_calc_msg_len (const char * fmt) const
Definition at line 1360 of file AP_Logger.cpp.
Referenced by msg_fmt_for_name(), and validate_structure().
Write_Command()
void AP_Logger::Write_Command (const mavlink_command_int_t & packet, uint8_t source_system, uint8_t source_component, MAV_RESULT result, bool was_command_long = false)
Definition at line 270 of file LogFile.cpp.
Referenced by GCS_MAVLINK::handle_command_int(), and GCS_MAVLINK::handle_command_long().
Write_Compass()
void AP_Logger::Write_Compass ()
Definition at line 427 of file LogFile.cpp.
Referenced by Compass::read().
Write_Compass_instance()
void AP_Logger::Write_Compass_instance (uint64_t time_us, uint8_t mag_instance) private
Definition at line 400 of file LogFile.cpp.
Referenced by Write_Compass().
Write_EntireMission()
void AP_Logger::Write_EntireMission ()
Definition at line 888 of file AP_Logger.cpp.
Referenced by Write_EntireMission().
Write_Error()
void AP_Logger::Write_Error (LogErrorSubsystem sub_system, LogErrorCode error_code)
Definition at line 1498 of file AP_Logger.cpp.
Referenced by Compass::read(), and AP_Baro::update().
Write_Event()
void AP_Logger::Write_Event (LogEvent id)
Definition at line 1487 of file AP_Logger.cpp.
Referenced by SRV_Channels::set_emergency_stop(), AP_AHRS::set_home(), AP_NavEKF_Source::setPosVelYawSourceSet(), AP_Airspeed::update(), and AP_GPS::update().
Write_Message()
void AP_Logger::Write_Message (const char * message)
Definition at line 893 of file AP_Logger.cpp.
Referenced by GCS_MAVLINK::handle_statustext(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), GCS::send_textv(), AP_LoggerTest::setup(), AP_LoggerTest_AllTypes::setup(), AP_GPS_Backend::Write_AP_Logger_Log_Startup_messages(), Write_Message(), and Write_MessageF().
Write_MessageF()
void AP_Logger::Write_MessageF (const char * fmt, ...)
Definition at line 602 of file AP_Logger.cpp.
Referenced by AP_InertialSensor_Invensense::_read_fifo(), AP_InertialSensor_Invensense::update(), AP_GPS_NMEA::Write_AP_Logger_Log_Startup_messages(), and AP_GPS_UBLOX::Write_AP_Logger_Log_Startup_messages().
Write_Mission_Cmd()
void AP_Logger::Write_Mission_Cmd (const AP_Mission & mission, const AP_Mission::Mission_Command & cmd)
Definition at line 908 of file AP_Logger.cpp.
Referenced by Write_Mission_Cmd().
Write_Mode()
void AP_Logger::Write_Mode (uint8_t mode, const ModeReason reason)
Definition at line 898 of file AP_Logger.cpp.
Referenced by Write_Mode().
Write_NamedValueFloat()
void AP_Logger::Write_NamedValueFloat (const char * name, float value)
Definition at line 935 of file AP_Logger.cpp.
Write_Parameter()
void AP_Logger::Write_Parameter (const char * name, float value)
Definition at line 903 of file AP_Logger.cpp.
Referenced by GCS_MAVLINK::handle_param_set(), GCS::send_parameter_value(), and Write_Parameter().
Write_PID()
void AP_Logger::Write_PID (uint8_t msg_type, const class AP_PIDInfo & info)
Definition at line 476 of file LogFile.cpp.
Write_Power()
void AP_Logger::Write_Power (void)
Definition at line 341 of file LogFile.cpp.
Referenced by AP_BattMonitor::read().
Write_Radio()
void AP_Logger::Write_Radio (const mavlink_radio_t & packet)
Definition at line 384 of file LogFile.cpp.
Referenced by GCS_MAVLINK::handle_radio_status().
Write_Rally()
void AP_Logger::Write_Rally ()
Write_RallyPoint()
void AP_Logger::Write_RallyPoint (uint8_t total, uint8_t sequence, const class RallyLocation & rally_point)
Referenced by AP_Rally::set_rally_point_with_index().
Write_RCIN()
void AP_Logger::Write_RCIN (void)
Referenced by RC_Channels::read_aux_all().
Write_RCOUT()
void AP_Logger::Write_RCOUT (void)
Definition at line 183 of file LogFile.cpp.
Write_RSSI()
void AP_Logger::Write_RSSI ()
Write_ServoStatus()
void AP_Logger::Write_ServoStatus (uint64_t time_us, uint8_t id, float position, float force, float speed, uint8_t power_pct, float pos_cmd, float voltage, float current, float mot_temp, float pcb_temp, uint8_t error)
Definition at line 453 of file LogFile.cpp.
Write_SRTL()
void AP_Logger::Write_SRTL (bool active, uint16_t num_points, uint16_t max_points, uint8_t action, const Vector3f & point)
Definition at line 517 of file LogFile.cpp.
Write_Winch()
void AP_Logger::Write_Winch (bool healthy, bool thread_end, bool moving, bool clutch, uint8_t mode, float desired_length, float length, float desired_rate, uint16_t tension, float voltage, int8_t temp)
Definition at line 533 of file LogFile.cpp.
WriteBlock()
void AP_Logger::WriteBlock (const void * pBuffer, uint16_t size)
Definition at line 18 of file main.cpp.
Referenced by AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_UBLOX::log_rxm_rawx(), ChibiOS::Util::log_stack_info(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages(), AP_LoggerTest::setup(), AP_AutoTune::update(), NavEKF3_core::updateMovementCheck(), NavEKF3_core::verifyTiltErrorVariance(), Write_Command(), Write_Compass_instance(), Write_PID(), Write_Power(), Write_Radio(), Write_RCOUT(), Write_ServoStatus(), Write_SRTL(), and Write_Winch().
WriteBlock_first_succeed()
bool AP_Logger::WriteBlock_first_succeed (const void * pBuffer, uint16_t size)
Definition at line 739 of file AP_Logger.cpp.
WriteCritical() [1/2]
void AP_Logger::WriteCritical (const char * name, const char * labels, const char * fmt, ...)
Definition at line 1010 of file AP_Logger.cpp.
Referenced by HAL_SITL::run(), AP_LoggerTest::setup(), and ChibiOS::Scheduler::try_force_mutex().
WriteCritical() [2/2]
void AP_Logger::WriteCritical (const char * name, const char * labels, const char * units, const char * mults, const char * fmt, ...)
Definition at line 1019 of file AP_Logger.cpp.
WriteCriticalBlock()
void AP_Logger::WriteCriticalBlock (const void * pBuffer, uint16_t size)
Definition at line 779 of file AP_Logger.cpp.
Referenced by ChibiOS::Scheduler::_monitor_thread(), Write_Error(), Write_Event(), and WriteCriticalBlock().
WritePrioritisedBlock()
void AP_Logger::WritePrioritisedBlock (const void * pBuffer, uint16_t size, bool is_critical) protected
Definition at line 783 of file AP_Logger.cpp.
Referenced by WritePrioritisedBlock(), and WriteReplayBlock().
WriteReplayBlock()
bool AP_Logger::WriteReplayBlock (uint8_t msg_id, const void * pBuffer, uint16_t size)
Definition at line 754 of file AP_Logger.cpp.
WritesEnabled()
bool AP_Logger::WritesEnabled () const inline
Definition at line 238 of file AP_Logger.h.
Referenced by AP_Logger_Backend::ShouldLog().
WriteStreaming() [1/2]
void AP_Logger::WriteStreaming (const char * name, const char * labels, const char * fmt, ...)
Definition at line 992 of file AP_Logger.cpp.
Referenced by AP_TECS::_update_pitch(), AP_TECS::_update_throttle_with_airspeed(), SITL::Blimp::calculate_forces(), AP_GPS_Backend::calculate_moving_base_yaw(), AP_Follow::handle_msg(), AP_RCProtocol_Backend::log_data(), SITL::JSON_Master::receive(), SITL::AirSim::recv_fdm(), SITL::JSON::recv_fdm(), AP_WindVane::update(), AP_Baro_ICM20789::update(), Variometer::update(), SITL::Blimp::update(), SoaringController::update_cruising(), AP_TECS::update_pitch_throttle(), SoaringController::update_thermalling(), and Write_NamedValueFloat().
WriteStreaming() [2/2]
void AP_Logger::WriteStreaming (const char * name, const char * labels, const char * units, const char * mults, const char * fmt, ...)
Definition at line 1001 of file AP_Logger.cpp.
WriteV()
void AP_Logger::WriteV (const char * name, const char * labels, const char * units, const char * mults, const char * fmt, va_list arg_list, bool is_critical = false, bool is_streaming = false)
Definition at line 1028 of file AP_Logger.cpp.
Referenced by Write(), Write(), WriteCritical(), WriteCritical(), WriteStreaming(), and WriteStreaming().
Friends And Related Symbol Documentation
AP_Logger_Backend
friend class AP_Logger_Backend friend
Definition at line 184 of file AP_Logger.h.
AP_Logger_RateLimiter
friend class AP_Logger_RateLimiter friend
Definition at line 185 of file AP_Logger.h.
Member Data Documentation
_armed
bool AP_Logger::_armed private
Definition at line 457 of file AP_Logger.h.
Referenced by set_vehicle_armed(), and vehicle_is_armed().
_force_log_disarmed
bool AP_Logger::_force_log_disarmed private
Definition at line 486 of file AP_Logger.h.
Referenced by log_while_disarmed(), and set_force_log_disarmed().
_force_long_log_persist
bool AP_Logger::_force_long_log_persist private
Definition at line 487 of file AP_Logger.h.
Referenced by in_log_persistance(), and set_long_log_persist().
_io_thread_started
bool AP_Logger::_io_thread_started private
Definition at line 501 of file AP_Logger.h.
Referenced by start_io_thread().
_last_arming_failure_ms
uint32_t AP_Logger::_last_arming_failure_ms private
Definition at line 576 of file AP_Logger.h.
Referenced by arming_failure(), and in_log_persistance().
_last_mavlink_log_transfer_message_handled_ms
uint32_t AP_Logger::_last_mavlink_log_transfer_message_handled_ms private
Definition at line 545 of file AP_Logger.h.
Referenced by AP_Logger_Backend::ShouldLog().
_log_bitmask
const AP_Int32* AP_Logger::_log_bitmask private
Definition at line 426 of file AP_Logger.h.
Referenced by init(), should_log(), and AP_Logger_Backend::StartNewLogOK().
_log_data_offset
uint32_t AP_Logger::_log_data_offset private
Definition at line 561 of file AP_Logger.h.
_log_data_page
uint32_t AP_Logger::_log_data_page private
Definition at line 570 of file AP_Logger.h.
_log_data_remaining
uint32_t AP_Logger::_log_data_remaining private
Definition at line 567 of file AP_Logger.h.
_log_data_size
uint32_t AP_Logger::_log_data_size private
Definition at line 564 of file AP_Logger.h.
_log_last_list_entry
uint16_t AP_Logger::_log_last_list_entry private
Definition at line 552 of file AP_Logger.h.
_log_next_list_entry
uint16_t AP_Logger::_log_next_list_entry private
Definition at line 549 of file AP_Logger.h.
_log_num_data
uint16_t AP_Logger::_log_num_data private
Definition at line 558 of file AP_Logger.h.
_log_num_logs
uint16_t AP_Logger::_log_num_logs private
Definition at line 555 of file AP_Logger.h.
_log_pause
bool AP_Logger::_log_pause
Definition at line 205 of file AP_Logger.h.
Referenced by log_pause(), AP_Logger_Block::periodic_1Hz(), AP_Logger_RateLimiter::should_log(), and AP_Logger_RateLimiter::should_log_streaming().
_log_send_sem
HAL_Semaphore AP_Logger::_log_send_sem private
Definition at line 573 of file AP_Logger.h.
Referenced by start_io_thread().
_log_sending_link
GCS_MAVLINK* AP_Logger::_log_sending_link private
Definition at line 572 of file AP_Logger.h.
_log_start_count
uint8_t AP_Logger::_log_start_count private
Definition at line 580 of file AP_Logger.h.
Referenced by backend_starting_new_log(), and get_log_start_count().
_multipliers
const struct MultiplierStructure* AP_Logger::_multipliers = log_Multipliers protected
Definition at line 412 of file AP_Logger.h.
Referenced by multiplier_name(), and validate_structure().
_next_backend
uint8_t AP_Logger::_next_backend private
Definition at line 424 of file AP_Logger.h.
Referenced by allow_start_ekf(), backend_starting_new_log(), CardInserted(), find_last_log(), get_log_boundaries(), get_log_data(), get_log_info(), get_num_logs(), init(), logging_enabled(), logging_failed(), logging_present(), logging_started(), num_dropped(), Safe_Write_Emit_FMT(), should_log(), WriteBlock_first_succeed(), WriteReplayBlock(), and WriteV().
_num_multipliers
const uint8_t AP_Logger::_num_multipliers = (sizeof(log_Multipliers) / sizeof(log_Multipliers[0])) protected
Definition at line 414 of file AP_Logger.h.
Referenced by multiplier_name(), AP_Logger_Backend::num_multipliers(), and validate_structure().
_num_types
uint8_t AP_Logger::_num_types protected
Definition at line 410 of file AP_Logger.h.
Referenced by init(), msg_type_in_use(), AP_Logger_Backend::num_types(), set_num_types(), and structure_for_msg_type().
_num_units
const uint8_t AP_Logger::_num_units = (sizeof(log_Units) / sizeof(log_Units[0])) protected
Definition at line 413 of file AP_Logger.h.
Referenced by AP_Logger_Backend::num_units(), unit_name(), and validate_structure().
[struct]
struct { ... } AP_Logger::_params
Referenced by get_max_num_logs(), in_log_download(), init(), AP_Logger_Block::Init(), log_replay(), log_while_disarmed(), AP_Logger_Block::periodic_1Hz(), AP_Logger_Backend::ShouldLog(), and AP_Logger_Backend::vehicle_was_disarmed().
_singleton
AP_Logger * AP_Logger::_singleton static private
Definition at line 466 of file AP_Logger.h.
Referenced by AP_Logger(), and get_singleton().
_structures
const struct LogStructure* AP_Logger::_structures protected
Definition at line 409 of file AP_Logger.h.
Referenced by init(), and structure().
_units
const struct UnitStructure* AP_Logger::_units = log_Units protected
Definition at line 411 of file AP_Logger.h.
Referenced by unit(), unit_name(), and validate_structure().
_vehicle_messages
vehicle_startup_message_Writer AP_Logger::_vehicle_messages
Definition at line 315 of file AP_Logger.h.
Referenced by setVehicle_Startup_Writer(), and AP_Logger_Backend::vehicle_message_writer().
_warned_log_disarm
bool AP_Logger::_warned_log_disarm private
Definition at line 546 of file AP_Logger.h.
_writes_enabled
bool AP_Logger::_writes_enabled private
Definition at line 485 of file AP_Logger.h.
Referenced by EnableWrites(), and WritesEnabled().
backend_types
AP_Int8 AP_Logger::backend_types
Definition at line 327 of file AP_Logger.h.
backends
AP_Logger_Backend* AP_Logger::backends[LOGGER_MAX_BACKENDS] private
Definition at line 425 of file AP_Logger.h.
Referenced by allow_start_ekf(), backend_starting_new_log(), CardInserted(), find_last_log(), get_log_boundaries(), get_log_data(), get_log_info(), get_num_logs(), init(), logging_enabled(), logging_failed(), logging_started(), num_dropped(), Safe_Write_Emit_FMT(), WriteBlock_first_succeed(), WriteReplayBlock(), and WriteV().
blk_ratemax
AP_Float AP_Logger::blk_ratemax
Definition at line 337 of file AP_Logger.h.
Referenced by AP_Logger_Block::periodic_1Hz().
disarm_ratemax
AP_Float AP_Logger::disarm_ratemax
Definition at line 338 of file AP_Logger.h.
Referenced by AP_Logger_Block::periodic_1Hz().
file_bufsize
AP_Int16 AP_Logger::file_bufsize
Definition at line 328 of file AP_Logger.h.
Referenced by init(), and AP_Logger_Block::Init().
file_disarm_rot
AP_Int8 AP_Logger::file_disarm_rot
Definition at line 329 of file AP_Logger.h.
Referenced by AP_Logger_Backend::ShouldLog(), and AP_Logger_Backend::vehicle_was_disarmed().
file_ratemax
AP_Float AP_Logger::file_ratemax
Definition at line 335 of file AP_Logger.h.
file_timeout
AP_Int16 AP_Logger::file_timeout
Definition at line 333 of file AP_Logger.h.
log_disarmed
AP_Enum<LogDisarmed> AP_Logger::log_disarmed
Definition at line 330 of file AP_Logger.h.
log_replay
AP_Int8 AP_Logger::log_replay
Definition at line 331 of file AP_Logger.h.
Referenced by allow_start_ekf(), AP_Logger_Backend::vehicle_was_disarmed(), and WriteReplayBlock().
log_write_fmts
struct AP_Logger::log_write_fmt * AP_Logger::log_write_fmts
Referenced by backend_starting_new_log(), fill_log_write_logstructure(), log_write_fmt_for_msg_type(), msg_fmt_for_name(), msg_type_in_use(), and AP_Logger_Backend::Write().
log_write_fmts_sem
HAL_Semaphore AP_Logger::log_write_fmts_sem private
Definition at line 444 of file AP_Logger.h.
Referenced by msg_fmt_for_name().
mav_bufsize
AP_Int8 AP_Logger::mav_bufsize
Definition at line 332 of file AP_Logger.h.
mav_ratemax
AP_Float AP_Logger::mav_ratemax
Definition at line 336 of file AP_Logger.h.
max_log_files
AP_Int16 AP_Logger::max_log_files
Definition at line 339 of file AP_Logger.h.
min_MB_free
AP_Int16 AP_Logger::min_MB_free
Definition at line 334 of file AP_Logger.h.
seen_ids
bool AP_Logger::seen_ids[256] = { } private
Definition at line 481 of file AP_Logger.h.
Referenced by validate_structure().
should_log_rcin2
bool AP_Logger::should_log_rcin2 private
Definition at line 460 of file AP_Logger.h.
transfer_activity
enum AP_Logger::TransferActivity AP_Logger::transfer_activity = TransferActivity::IDLE private
Referenced by in_log_download().
var_info
const AP_Param::GroupInfo AP_Logger::var_info static
Definition at line 83 of file AP_Logger.h.
The documentation for this class was generated from the following files:
libraries/AP_Logger/AP_Logger.h
libraries/AP_DAL/examples/AP_DAL_Standalone/main.cpp
libraries/AP_Logger/AP_Logger.cpp
libraries/AP_Logger/LogFile.cpp