APM:Libraries: SITL::Gazebo Class Reference
SITL::Gazebo Class Reference
#include <SIM_Gazebo.h>
Classes
struct fdm_packet
struct servo_packet
Public Member Functions
Gazebo (const char *frame_str)
void update (const struct sitl_input &input) override
void set_interface_ports (const char *address, const int port_in, const int port_out) override
Static Public Member Functions
static Aircraft * create (const char *frame_str)
Private Member Functions
void recv_fdm (const struct sitl_input &input)
void send_servos (const struct sitl_input &input)
void drain_sockets ()
Private Attributes
double last_timestamp
SocketAPM_native socket_sitl
const char * _gazebo_address = "127.0.0.1"
int _gazebo_port = 9002
Static Private Attributes
static const uint64_t GAZEBO_TIMEOUT_US = 5000000
Detailed Description
Definition at line 37 of file SIM_Gazebo.h.
Constructor & Destructor Documentation
Gazebo()
SITL::Gazebo::Gazebo (const char * frame_str)
Definition at line 28 of file SIM_Gazebo.cpp.
Referenced by create().
Member Function Documentation
create()
static Aircraft * SITL::Gazebo::create (const char * frame_str) inline static
Definition at line 45 of file SIM_Gazebo.h.
drain_sockets()
void SITL::Gazebo::drain_sockets () private
Definition at line 136 of file SIM_Gazebo.cpp.
Referenced by update().
recv_fdm()
void SITL::Gazebo::recv_fdm (const struct sitl_input & input) private
Definition at line 77 of file SIM_Gazebo.cpp.
Referenced by update().
send_servos()
void SITL::Gazebo::send_servos (const struct sitl_input & input) private
Definition at line 61 of file SIM_Gazebo.cpp.
Referenced by recv_fdm(), and update().
set_interface_ports()
void SITL::Gazebo::set_interface_ports (const char * address, const int port_in, const int port_out) override
Definition at line 39 of file SIM_Gazebo.cpp.
update()
void SITL::Gazebo::update (const struct sitl_input & input) override
Definition at line 159 of file SIM_Gazebo.cpp.
Member Data Documentation
_gazebo_address
const char* SITL::Gazebo::_gazebo_address = "127.0.0.1" private
Definition at line 80 of file SIM_Gazebo.h.
Referenced by send_servos(), and set_interface_ports().
_gazebo_port
int SITL::Gazebo::_gazebo_port = 9002 private
Definition at line 81 of file SIM_Gazebo.h.
Referenced by send_servos(), and set_interface_ports().
GAZEBO_TIMEOUT_US
const uint64_t SITL::Gazebo::GAZEBO_TIMEOUT_US = 5000000 static private
Definition at line 82 of file SIM_Gazebo.h.
Referenced by recv_fdm().
last_timestamp
double SITL::Gazebo::last_timestamp private
Definition at line 77 of file SIM_Gazebo.h.
Referenced by recv_fdm().
socket_sitl
SocketAPM_native SITL::Gazebo::socket_sitl private
Definition at line 79 of file SIM_Gazebo.h.
Referenced by drain_sockets(), recv_fdm(), send_servos(), and set_interface_ports().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_Gazebo.h
libraries/SITL/SIM_Gazebo.cpp