APM:Libraries: SIM_RGBLED Class Reference
SIM_RGBLED Class Reference
#include <SIM_RGBLED.h>
Public Member Functions
SIM_RGBLED (const char *_name)
void init ()
void set_colours (uint8_t _red, uint8_t _green, uint8_t _blue)
Private Member Functions
void update_thread (void)
Static Private Member Functions
static void * update_thread_start (void *obj)
Private Attributes
const char * name
uint8_t red
uint8_t green
uint8_t blue
pthread_t thread
uint32_t last_colour
Static Private Attributes
static constexpr uint8_t height = 50
static constexpr uint8_t width = height
Detailed Description
Definition at line 12 of file SIM_RGBLED.h.
Constructor & Destructor Documentation
SIM_RGBLED()
SIM_RGBLED::SIM_RGBLED (const char * _name) inline
Definition at line 15 of file SIM_RGBLED.h.
Member Function Documentation
init()
void SIM_RGBLED::init ()
Definition at line 60 of file SIM_RGBLED.cpp.
Referenced by SITL::LM2755::init(), and SITL::ToshibaLED::init().
set_colours()
void SIM_RGBLED::set_colours (uint8_t _red, uint8_t _green, uint8_t _blue) inline
Definition at line 21 of file SIM_RGBLED.h.
Referenced by SITL::LM2755::update(), and SITL::ToshibaLED::update().
update_thread()
void SIM_RGBLED::update_thread (void) private
update_thread_start()
static void * SIM_RGBLED::update_thread_start (void * obj) static private
Referenced by init().
Member Data Documentation
blue
uint8_t SIM_RGBLED::blue private
Definition at line 33 of file SIM_RGBLED.h.
Referenced by set_colours().
green
uint8_t SIM_RGBLED::green private
Definition at line 32 of file SIM_RGBLED.h.
Referenced by set_colours().
height
constexpr uint8_t SIM_RGBLED::height = 50 static constexpr private
Definition at line 35 of file SIM_RGBLED.h.
last_colour
uint32_t SIM_RGBLED::last_colour private
Definition at line 42 of file SIM_RGBLED.h.
name
const char* SIM_RGBLED::name private
Definition at line 29 of file SIM_RGBLED.h.
red
uint8_t SIM_RGBLED::red private
Definition at line 31 of file SIM_RGBLED.h.
Referenced by set_colours().
thread
pthread_t SIM_RGBLED::thread private
Definition at line 38 of file SIM_RGBLED.h.
Referenced by init().
width
constexpr uint8_t SIM_RGBLED::width = height static constexpr private
Definition at line 36 of file SIM_RGBLED.h.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_RGBLED.h
libraries/SITL/SIM_RGBLED.cpp