APM:Libraries: AC_AutoTune_Multi Class Reference
AC_AutoTune_Multi Class Reference
#include <AC_AutoTune_Multi.h>
Public Member Functions
AC_AutoTune_Multi ()
void save_tuning_gains () override
Public Member Functions inherited from AC_AutoTune
AC_AutoTune ()
virtual void run ()
void stop ()
void reset ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void backup_gains_and_initialise () override
void load_orig_gains () override
void load_tuned_gains () override
void load_intra_test_gains () override
void load_test_gains () override
void reset_vehicle_test_variables () override
void reset_update_gain_variables () override
void test_init () override
void test_run (AxisType test_axis, const float dir_sign) override
void do_gcs_announcements () override
void do_post_test_gcs_announcements () override
void report_final_gains (AxisType test_axis) const override
void updating_rate_p_up_all (AxisType test_axis) override
void updating_rate_d_up_all (AxisType test_axis) override
void updating_rate_d_down_all (AxisType test_axis) override
void updating_rate_ff_up_all (AxisType test_axis) override
void updating_angle_p_up_all (AxisType test_axis) override
void updating_angle_p_down_all (AxisType test_axis) override
void updating_max_gains_all (AxisType test_axis) override
void set_gains_post_tune (AxisType test_axis) override
bool twitch_reverse_direction () override
void set_tune_sequence () override
uint8_t get_axis_bitmask () const override
uint32_t get_testing_step_timeout_ms () const override
Protected Member Functions inherited from AC_AutoTune
virtual bool init (void)=0
virtual float get_pilot_desired_climb_rate_cms (void) const =0
virtual void get_pilot_desired_rp_yrate_cd (float &roll_cd, float &pitch_cd, float &yaw_rate_cds)=0
virtual void init_z_limits ()=0
bool roll_enabled () const
bool pitch_enabled () const
bool yaw_enabled () const
bool yaw_d_enabled () const
bool init_internals (bool use_poshold, AC_AttitudeControl *attitude_control, AC_PosControl *pos_control, AP_AHRS_View *ahrs_view, AP_InertialNav *inertial_nav)
void update_gcs (uint8_t message_id) const
void send_step_string ()
const char * type_string () const
const char * axis_string () const
void next_tune_type (TuneType &curr_tune_type, bool reset)
void get_poshold_attitude (float &roll_cd, float &pitch_cd, float &yaw_cd)
void load_gains (enum GainType gain_type)
Private Member Functions
void twitch_test_init ()
void twitch_test_run (AxisType test_axis, const float dir_sign)
void twitching_test_rate (float rate, float rate_target, float &meas_rate_min, float &meas_rate_max)
void twitching_abort_rate (float angle, float rate, float angle_max, float meas_rate_min)
void twitching_test_angle (float angle, float rate, float angle_target, float &meas_angle_min, float &meas_angle_max, float &meas_rate_min, float &meas_rate_max)
void twitching_measure_acceleration (float &rate_of_change, float rate_measurement, float &rate_measurement_max) const
void updating_rate_d_up (float &tune_d, float tune_d_min, float tune_d_max, float tune_d_step_ratio, float &tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float rate_target, float meas_rate_min, float meas_rate_max)
void updating_rate_d_down (float &tune_d, float tune_d_min, float tune_d_step_ratio, float &tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float rate_target, float meas_rate_min, float meas_rate_max)
void updating_rate_p_up_d_down (float &tune_d, float tune_d_min, float tune_d_step_ratio, float &tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float rate_target, float meas_rate_min, float meas_rate_max)
void updating_angle_p_down (float &tune_p, float tune_p_min, float tune_p_step_ratio, float angle_target, float meas_angle_max, float meas_rate_min, float meas_rate_max)
void updating_angle_p_up (float &tune_p, float tune_p_max, float tune_p_step_ratio, float angle_target, float meas_angle_max, float meas_rate_min, float meas_rate_max)
void report_axis_gains (const char *axis_string, float rate_P, float rate_I, float rate_D, float angle_P, float max_accel) const
Private Attributes
AP_Int8 axis_bitmask
AP_Float aggressiveness
AP_Float min_d
Additional Inherited Members
Protected Types inherited from AC_AutoTune
enum AxisType { ROLL = 0 , PITCH = 1 , YAW = 2 , YAW_D = 3 }
enum StepType { WAITING_FOR_LEVEL = 0 , TESTING = 1 , UPDATE_GAINS = 2 }
enum TuneType {
RD_UP = 0 , RD_DOWN = 1 , RP_UP = 2 , RFF_UP = 3 ,
SP_UP = 4 , SP_DOWN = 5 , MAX_GAINS = 6 , TUNE_CHECK = 7 ,
TUNE_COMPLETE = 8
}
enum GainType { GAIN_ORIGINAL = 0 , GAIN_TEST = 1 , GAIN_INTRA_TEST = 2 , GAIN_TUNED = 3 }
enum TuneMode { UNINITIALISED = 0 , TUNING = 1 , SUCCESS = 2 , FAILED = 3 }
Protected Attributes inherited from AC_AutoTune
TuneType tune_seq [6]
uint8_t tune_seq_curr
TuneMode mode
AC_AttitudeControl * attitude_control
AC_PosControl * pos_control
AP_AHRS_View * ahrs_view
AP_InertialNav * inertial_nav
AP_Motors * motors
AxisType axis
bool positive_direction
StepType step
TuneType tune_type
bool ignore_next
bool twitch_first_iter
uint8_t axes_completed
float test_rate_min
float test_rate_max
float test_angle_min
float test_angle_max
uint32_t step_start_time_ms
uint32_t step_time_limit_ms
int8_t counter
float target_rate
float target_angle
float start_rate
float start_angle
float rate_max
float test_accel_max
float step_scaler
float abort_angle
float desired_yaw_cd
LowPassFilterFloat rotation_rate_filt
float orig_roll_rp
float orig_roll_ri
float orig_roll_rd
float orig_roll_rff
float orig_roll_fltt
float orig_roll_smax
float orig_roll_sp
float orig_roll_accel
float orig_pitch_rp
float orig_pitch_ri
float orig_pitch_rd
float orig_pitch_rff
float orig_pitch_fltt
float orig_pitch_smax
float orig_pitch_sp
float orig_pitch_accel
float orig_yaw_rp
float orig_yaw_ri
float orig_yaw_rd
float orig_yaw_rff
float orig_yaw_fltt
float orig_yaw_smax
float orig_yaw_rLPF
float orig_yaw_sp
float orig_yaw_accel
bool orig_bf_feedforward
float tune_roll_rp
float tune_roll_rd
float tune_roll_sp
float tune_roll_accel
float tune_pitch_rp
float tune_pitch_rd
float tune_pitch_sp
float tune_pitch_accel
float tune_yaw_rp
float tune_yaw_rLPF
float tune_yaw_sp
float tune_yaw_accel
float tune_roll_rff
float tune_pitch_rff
float tune_yaw_rd
float tune_yaw_rff
uint32_t announce_time
float lean_angle
float rotation_rate
float roll_cd
float pitch_cd
uint8_t freq_cnt
float start_freq
float stop_freq
bool ff_up_first_iter
Detailed Description
Definition at line 28 of file AC_AutoTune_Multi.h.
Constructor & Destructor Documentation
AC_AutoTune_Multi()
AC_AutoTune_Multi::AC_AutoTune_Multi ()
Definition at line 111 of file AC_AutoTune_Multi.cpp.
Member Function Documentation
backup_gains_and_initialise()
void AC_AutoTune_Multi::backup_gains_and_initialise () override protected virtual
Reimplemented from AC_AutoTune.
Definition at line 139 of file AC_AutoTune_Multi.cpp.
do_gcs_announcements()
void AC_AutoTune_Multi::do_gcs_announcements () override protected virtual
Implements AC_AutoTune.
Definition at line 117 of file AC_AutoTune_Multi.cpp.
do_post_test_gcs_announcements()
void AC_AutoTune_Multi::do_post_test_gcs_announcements () inline override protected virtual
Implements AC_AutoTune.
Definition at line 73 of file AC_AutoTune_Multi.h.
get_axis_bitmask()
uint8_t AC_AutoTune_Multi::get_axis_bitmask () const inline override protected virtual
Implements AC_AutoTune.
Definition at line 132 of file AC_AutoTune_Multi.h.
get_testing_step_timeout_ms()
uint32_t AC_AutoTune_Multi::get_testing_step_timeout_ms () const override protected virtual
Implements AC_AutoTune.
Definition at line 1250 of file AC_AutoTune_Multi.cpp.
load_intra_test_gains()
void AC_AutoTune_Multi::load_intra_test_gains () override protected virtual
Implements AC_AutoTune.
Definition at line 289 of file AC_AutoTune_Multi.cpp.
load_orig_gains()
void AC_AutoTune_Multi::load_orig_gains () override protected virtual
Implements AC_AutoTune.
Definition at line 200 of file AC_AutoTune_Multi.cpp.
load_test_gains()
void AC_AutoTune_Multi::load_test_gains () override protected virtual
Implements AC_AutoTune.
Definition at line 326 of file AC_AutoTune_Multi.cpp.
load_tuned_gains()
void AC_AutoTune_Multi::load_tuned_gains () override protected virtual
Implements AC_AutoTune.
Definition at line 243 of file AC_AutoTune_Multi.cpp.
report_axis_gains()
void AC_AutoTune_Multi::report_axis_gains (const char * axis_string, float rate_P, float rate_I, float rate_D, float angle_P, float max_accel) const private
Definition at line 492 of file AC_AutoTune_Multi.cpp.
Referenced by report_final_gains().
report_final_gains()
void AC_AutoTune_Multi::report_final_gains (AxisType test_axis) const override protected virtual
Implements AC_AutoTune.
Definition at line 473 of file AC_AutoTune_Multi.cpp.
reset_update_gain_variables()
void AC_AutoTune_Multi::reset_update_gain_variables () inline override protected virtual
Implements AC_AutoTune.
Definition at line 64 of file AC_AutoTune_Multi.h.
reset_vehicle_test_variables()
void AC_AutoTune_Multi::reset_vehicle_test_variables () inline override protected virtual
Implements AC_AutoTune.
Definition at line 61 of file AC_AutoTune_Multi.h.
save_tuning_gains()
void AC_AutoTune_Multi::save_tuning_gains () override virtual
Implements AC_AutoTune.
Definition at line 366 of file AC_AutoTune_Multi.cpp.
set_gains_post_tune()
void AC_AutoTune_Multi::set_gains_post_tune (AxisType test_axis) override protected virtual
Implements AC_AutoTune.
Definition at line 714 of file AC_AutoTune_Multi.cpp.
set_tune_sequence()
void AC_AutoTune_Multi::set_tune_sequence () inline override protected virtual
Implements AC_AutoTune.
Definition at line 122 of file AC_AutoTune_Multi.h.
test_init()
void AC_AutoTune_Multi::test_init () override protected virtual
Implements AC_AutoTune.
Definition at line 127 of file AC_AutoTune_Multi.cpp.
test_run()
void AC_AutoTune_Multi::test_run (AxisType test_axis, const float dir_sign) override protected virtual
Implements AC_AutoTune.
Definition at line 132 of file AC_AutoTune_Multi.cpp.
twitch_reverse_direction()
bool AC_AutoTune_Multi::twitch_reverse_direction () inline override protected virtual
Implements AC_AutoTune.
Definition at line 109 of file AC_AutoTune_Multi.h.
twitch_test_init()
void AC_AutoTune_Multi::twitch_test_init () private
Definition at line 1099 of file AC_AutoTune_Multi.cpp.
Referenced by test_init().
twitch_test_run()
void AC_AutoTune_Multi::twitch_test_run (AxisType test_axis, const float dir_sign) private
Definition at line 1140 of file AC_AutoTune_Multi.cpp.
Referenced by test_run().
twitching_abort_rate()
void AC_AutoTune_Multi::twitching_abort_rate (float angle, float rate, float angle_max, float meas_rate_min) private
Definition at line 543 of file AC_AutoTune_Multi.cpp.
Referenced by twitch_test_run().
twitching_measure_acceleration()
void AC_AutoTune_Multi::twitching_measure_acceleration (float & rate_of_change, float rate_measurement, float & rate_measurement_max) const private
Definition at line 614 of file AC_AutoTune_Multi.cpp.
Referenced by twitch_test_run().
twitching_test_angle()
void AC_AutoTune_Multi::twitching_test_angle (float angle, float rate, float angle_target, float & meas_angle_min, float & meas_angle_max, float & meas_rate_min, float & meas_rate_max) private
Definition at line 560 of file AC_AutoTune_Multi.cpp.
Referenced by twitch_test_run().
twitching_test_rate()
void AC_AutoTune_Multi::twitching_test_rate (float rate, float rate_target, float & meas_rate_min, float & meas_rate_max) private
Definition at line 501 of file AC_AutoTune_Multi.cpp.
Referenced by twitch_test_run().
updating_angle_p_down()
void AC_AutoTune_Multi::updating_angle_p_down (float & tune_p, float tune_p_min, float tune_p_step_ratio, float angle_target, float meas_angle_max, float meas_rate_min, float meas_rate_max) private
Definition at line 945 of file AC_AutoTune_Multi.cpp.
Referenced by updating_angle_p_down_all().
updating_angle_p_down_all()
void AC_AutoTune_Multi::updating_angle_p_down_all (AxisType test_axis) override protected virtual
Implements AC_AutoTune.
Definition at line 697 of file AC_AutoTune_Multi.cpp.
updating_angle_p_up()
void AC_AutoTune_Multi::updating_angle_p_up (float & tune_p, float tune_p_max, float tune_p_step_ratio, float angle_target, float meas_angle_max, float meas_rate_min, float meas_rate_max) private
Definition at line 974 of file AC_AutoTune_Multi.cpp.
Referenced by updating_angle_p_up_all().
updating_angle_p_up_all()
void AC_AutoTune_Multi::updating_angle_p_up_all (AxisType test_axis) override protected virtual
Implements AC_AutoTune.
Definition at line 680 of file AC_AutoTune_Multi.cpp.
updating_max_gains_all()
void AC_AutoTune_Multi::updating_max_gains_all (AxisType test_axis) inline override protected virtual
Implements AC_AutoTune.
Definition at line 100 of file AC_AutoTune_Multi.h.
updating_rate_d_down()
void AC_AutoTune_Multi::updating_rate_d_down (float & tune_d, float tune_d_min, float tune_d_step_ratio, float & tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float rate_target, float meas_rate_min, float meas_rate_max) private
Definition at line 840 of file AC_AutoTune_Multi.cpp.
Referenced by updating_rate_d_down_all().
updating_rate_d_down_all()
void AC_AutoTune_Multi::updating_rate_d_down_all (AxisType test_axis) override protected virtual
Implements AC_AutoTune.
Definition at line 661 of file AC_AutoTune_Multi.cpp.
updating_rate_d_up()
void AC_AutoTune_Multi::updating_rate_d_up (float & tune_d, float tune_d_min, float tune_d_max, float tune_d_step_ratio, float & tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float rate_target, float meas_rate_min, float meas_rate_max) private
Definition at line 785 of file AC_AutoTune_Multi.cpp.
Referenced by updating_rate_d_up_all().
updating_rate_d_up_all()
void AC_AutoTune_Multi::updating_rate_d_up_all (AxisType test_axis) override protected virtual
Implements AC_AutoTune.
Definition at line 642 of file AC_AutoTune_Multi.cpp.
updating_rate_ff_up_all()
void AC_AutoTune_Multi::updating_rate_ff_up_all (AxisType test_axis) inline override protected virtual
Implements AC_AutoTune.
Definition at line 88 of file AC_AutoTune_Multi.h.
updating_rate_p_up_all()
void AC_AutoTune_Multi::updating_rate_p_up_all (AxisType test_axis) override protected virtual
Implements AC_AutoTune.
Definition at line 623 of file AC_AutoTune_Multi.cpp.
updating_rate_p_up_d_down()
void AC_AutoTune_Multi::updating_rate_p_up_d_down (float & tune_d, float tune_d_min, float tune_d_step_ratio, float & tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float rate_target, float meas_rate_min, float meas_rate_max) private
Definition at line 895 of file AC_AutoTune_Multi.cpp.
Referenced by updating_rate_p_up_all().
Member Data Documentation
aggressiveness
AP_Float AC_AutoTune_Multi::aggressiveness private
Definition at line 174 of file AC_AutoTune_Multi.h.
Referenced by backup_gains_and_initialise(), twitch_test_run(), twitching_test_angle(), twitching_test_rate(), updating_angle_p_down(), updating_angle_p_up(), updating_rate_d_down(), updating_rate_d_up(), and updating_rate_p_up_d_down().
axis_bitmask
AP_Int8 AC_AutoTune_Multi::axis_bitmask private
Definition at line 173 of file AC_AutoTune_Multi.h.
Referenced by get_axis_bitmask().
min_d
AP_Float AC_AutoTune_Multi::min_d private
Definition at line 175 of file AC_AutoTune_Multi.h.
Referenced by backup_gains_and_initialise(), set_gains_post_tune(), updating_rate_d_down_all(), updating_rate_d_up_all(), and updating_rate_p_up_all().
var_info
const AP_Param::GroupInfo AC_AutoTune_Multi::var_info static
Initial value:
= {
    AP_GROUPINFO("AXES", 1, AC_AutoTune_Multi, axis_bitmask,  7),
    AP_GROUPINFO("AGGR", 2, AC_AutoTune_Multi, aggressiveness, 0.1f),
    AP_GROUPINFO("MIN_D", 3, AC_AutoTune_Multi, min_d,  0.001f),
    AP_GROUPEND
}
Definition at line 84 of file AC_AutoTune_Multi.h.
The documentation for this class was generated from the following files:
libraries/AC_AutoTune/AC_AutoTune_Multi.h
libraries/AC_AutoTune/AC_AutoTune_Multi.cpp