APM:Libraries: AP_RCProtocol Class Reference
AP_RCProtocol Class Reference
#include <AP_RCProtocol.h>
Classes
class SerialConfig
Public Types
enum rcprotocol_t {
PPMSUM = 0 , IBUS = 1 , SBUS = 2 , SBUS_NI = 3 ,
DSM = 4 , SUMD = 5 , SRXL = 6 , SRXL2 = 7 ,
CRSF = 8 , ST24 = 9 , FPORT = 10 , FASTSBUS = 12 ,
GHST = 14 , NONE
}
Public Member Functions
AP_RCProtocol ()
~AP_RCProtocol ()
void init ()
bool valid_serial_prot () const
bool should_search (uint32_t now_ms) const
void process_pulse (uint32_t width_s0, uint32_t width_s1)
void process_pulse_list (const uint32_t *widths, uint16_t n, bool need_swap)
bool process_byte (uint8_t byte, uint32_t baudrate)
void process_handshake (uint32_t baudrate)
void update (void)
bool failsafe_active () const
void set_failsafe_active (bool active)
void disable_for_pulses (enum rcprotocol_t protocol)
bool requires_3_frames (enum rcprotocol_t p)
uint8_t num_channels ()
uint16_t read (uint8_t chan)
void read (uint16_t *pwm, uint8_t n)
bool new_input ()
void start_bind (void)
int16_t get_RSSI (void) const
int16_t get_rx_link_quality (void) const
const char * protocol_name (void) const
enum rcprotocol_t protocol_detected (void) const
void add_uart (AP_HAL::UARTDriver *uart)
bool has_uart () const
void set_rc_protocols (uint32_t mask)
bool using_uart (void) const
Static Public Member Functions
static const char * protocol_name_from_protocol (rcprotocol_t protocol)
Private Member Functions
void check_added_uart (void)
bool protocol_enabled (enum rcprotocol_t protocol) const
bool detect_async_protocol (rcprotocol_t protocol)
Private Attributes
enum rcprotocol_t _detected_protocol = NONE
uint16_t _disabled_for_pulses
bool _detected_with_bytes
AP_RCProtocol_Backend * backend [NONE]
bool _new_input
uint32_t _last_input_ms
bool _failsafe_active
bool _valid_serial_prot
struct {
AP_HAL::UARTDriver * uart
bool opened
uint32_t last_config_change_ms
uint8_t config_num
} added
uint32_t rc_protocols_mask
Friends
class AP_RCProtocol_Backend
Detailed Description
Definition at line 29 of file AP_RCProtocol.h.
Member Enumeration Documentation
rcprotocol_t
enum AP_RCProtocol::rcprotocol_t
Enumerator
PPMSUM
IBUS
SBUS
SBUS_NI
DSM
SUMD
SRXL
SRXL2
CRSF
ST24
FPORT
FASTSBUS
GHST
NONE
Definition at line 32 of file AP_RCProtocol.h.
Constructor & Destructor Documentation
AP_RCProtocol()
AP_RCProtocol::AP_RCProtocol () inline
Definition at line 86 of file AP_RCProtocol.h.
~AP_RCProtocol()
AP_RCProtocol::~AP_RCProtocol ()
Definition at line 93 of file AP_RCProtocol.cpp.
Member Function Documentation
add_uart()
void AP_RCProtocol::add_uart (AP_HAL::UARTDriver * uart)
Definition at line 576 of file AP_RCProtocol.cpp.
Referenced by AP_SerialManager::init().
check_added_uart()
void AP_RCProtocol::check_added_uart (void) private
Definition at line 316 of file AP_RCProtocol.cpp.
Referenced by new_input(), and update().
detect_async_protocol()
bool AP_RCProtocol::detect_async_protocol (rcprotocol_t protocol) private
Definition at line 373 of file AP_RCProtocol.cpp.
Referenced by new_input().
disable_for_pulses()
void AP_RCProtocol::disable_for_pulses (enum rcprotocol_t protocol) inline
Definition at line 109 of file AP_RCProtocol.h.
Referenced by AP_IOMCU_FW::rcin_serial_init().
failsafe_active()
bool AP_RCProtocol::failsafe_active () const inline
Definition at line 102 of file AP_RCProtocol.h.
get_RSSI()
int16_t AP_RCProtocol::get_RSSI (void) const
Definition at line 464 of file AP_RCProtocol.cpp.
Referenced by ChibiOS::RCInput::_timer_tick(), and ESP32::RCInput::_timer_tick().
get_rx_link_quality()
int16_t AP_RCProtocol::get_rx_link_quality (void) const
Definition at line 471 of file AP_RCProtocol.cpp.
Referenced by ChibiOS::RCInput::_timer_tick().
has_uart()
bool AP_RCProtocol::has_uart () const inline
Definition at line 186 of file AP_RCProtocol.h.
init()
void AP_RCProtocol::init ()
Definition at line 44 of file AP_RCProtocol.cpp.
Referenced by ChibiOS::RCInput::init(), ESP32::RCInput::init(), Linux::RCInput_RCProtocol::init(), setup(), test_protocol(), and test_protocol_bytesonly().
new_input()
bool AP_RCProtocol::new_input ()
Definition at line 408 of file AP_RCProtocol.cpp.
Referenced by ChibiOS::RCInput::_timer_tick(), ESP32::RCInput::_timer_tick(), check_result(), loop(), process_byte(), and process_pulse().
num_channels()
uint8_t AP_RCProtocol::num_channels ()
Definition at line 441 of file AP_RCProtocol.cpp.
Referenced by ChibiOS::RCInput::_timer_tick(), ESP32::RCInput::_timer_tick(), Linux::RCInput_RCProtocol::_timer_tick(), check_result(), and loop().
process_byte()
bool AP_RCProtocol::process_byte (uint8_t byte, uint32_t baudrate)
Definition at line 202 of file AP_RCProtocol.cpp.
Referenced by Linux::RCInput_RCProtocol::_timer_tick(), check_added_uart(), loop(), and test_byte_protocol().
process_handshake()
void AP_RCProtocol::process_handshake (uint32_t baudrate)
Definition at line 264 of file AP_RCProtocol.cpp.
Referenced by check_added_uart().
process_pulse()
void AP_RCProtocol::process_pulse (uint32_t width_s0, uint32_t width_s1)
Definition at line 118 of file AP_RCProtocol.cpp.
Referenced by ChibiOS::RCInput::_timer_tick(), ESP32::RCInput::_timer_tick(), process_pulse_list(), and send_bit().
process_pulse_list()
void AP_RCProtocol::process_pulse_list (const uint32_t * widths, uint16_t n, bool need_swap)
Definition at line 182 of file AP_RCProtocol.cpp.
Referenced by ChibiOS::RCInput::_timer_tick().
protocol_detected()
enum rcprotocol_t AP_RCProtocol::protocol_detected (void) const inline
Definition at line 180 of file AP_RCProtocol.h.
protocol_enabled()
bool AP_RCProtocol::protocol_enabled (enum rcprotocol_t protocol) const private
Definition at line 583 of file AP_RCProtocol.cpp.
Referenced by process_byte(), process_pulse(), and AP_RCProtocol_Backend::protocol_enabled().
protocol_name()
const char * AP_RCProtocol::protocol_name (void) const
Definition at line 568 of file AP_RCProtocol.cpp.
Referenced by ChibiOS::RCInput::_timer_tick(), ESP32::RCInput::_timer_tick(), and check_result().
protocol_name_from_protocol()
const char * AP_RCProtocol::protocol_name_from_protocol (rcprotocol_t protocol) static
Definition at line 495 of file AP_RCProtocol.cpp.
Referenced by protocol_name().
read() [1/2]
void AP_RCProtocol::read (uint16_t * pwm, uint8_t n)
Definition at line 457 of file AP_RCProtocol.cpp.
read() [2/2]
uint16_t AP_RCProtocol::read (uint8_t chan)
Definition at line 449 of file AP_RCProtocol.cpp.
Referenced by ChibiOS::RCInput::_timer_tick(), ESP32::RCInput::_timer_tick(), Linux::RCInput_RCProtocol::_timer_tick(), check_result(), and loop().
requires_3_frames()
bool AP_RCProtocol::requires_3_frames (enum rcprotocol_t p) inline
Definition at line 114 of file AP_RCProtocol.h.
Referenced by process_byte(), and process_pulse().
set_failsafe_active()
void AP_RCProtocol::set_failsafe_active (bool active) inline
Definition at line 105 of file AP_RCProtocol.h.
Referenced by AP_RCProtocol_Backend::add_input().
set_rc_protocols()
void AP_RCProtocol::set_rc_protocols (uint32_t mask) inline
Definition at line 189 of file AP_RCProtocol.h.
Referenced by AP_IOMCU_FW::handle_code_write().
should_search()
bool AP_RCProtocol::should_search (uint32_t now_ms) const
Definition at line 103 of file AP_RCProtocol.cpp.
Referenced by check_added_uart(), detect_async_protocol(), process_byte(), and process_pulse().
start_bind()
void AP_RCProtocol::start_bind (void)
Definition at line 481 of file AP_RCProtocol.cpp.
Referenced by ChibiOS::RCInput::rc_bind().
update()
void AP_RCProtocol::update (void)
Definition at line 365 of file AP_RCProtocol.cpp.
Referenced by HALSITL::Scheduler::_run_io_procs().
using_uart()
bool AP_RCProtocol::using_uart (void) const inline
Definition at line 204 of file AP_RCProtocol.h.
Referenced by ChibiOS::RCInput::_timer_tick().
valid_serial_prot()
bool AP_RCProtocol::valid_serial_prot () const inline
Definition at line 91 of file AP_RCProtocol.h.
Friends And Related Symbol Documentation
AP_RCProtocol_Backend
friend class AP_RCProtocol_Backend friend
Definition at line 88 of file AP_RCProtocol.h.
Member Data Documentation
_detected_protocol
enum rcprotocol_t AP_RCProtocol::_detected_protocol = NONE private
Definition at line 219 of file AP_RCProtocol.h.
Referenced by check_added_uart(), detect_async_protocol(), get_RSSI(), get_rx_link_quality(), AP_RCProtocol_Backend::is_detected(), num_channels(), process_byte(), process_handshake(), process_pulse(), protocol_detected(), protocol_name(), read(), read(), and should_search().
_detected_with_bytes
bool AP_RCProtocol::_detected_with_bytes private
Definition at line 221 of file AP_RCProtocol.h.
Referenced by check_added_uart(), AP_RCProtocol_Backend::get_UART(), process_byte(), process_pulse(), and using_uart().
_disabled_for_pulses
uint16_t AP_RCProtocol::_disabled_for_pulses private
Definition at line 220 of file AP_RCProtocol.h.
Referenced by disable_for_pulses(), and process_pulse().
_failsafe_active
bool AP_RCProtocol::_failsafe_active private
Definition at line 225 of file AP_RCProtocol.h.
Referenced by failsafe_active(), and set_failsafe_active().
_last_input_ms
uint32_t AP_RCProtocol::_last_input_ms private
Definition at line 224 of file AP_RCProtocol.h.
Referenced by new_input(), process_byte(), process_handshake(), process_pulse(), and should_search().
_new_input
bool AP_RCProtocol::_new_input private
Definition at line 223 of file AP_RCProtocol.h.
Referenced by new_input(), process_byte(), and process_pulse().
_valid_serial_prot
bool AP_RCProtocol::_valid_serial_prot private
Definition at line 226 of file AP_RCProtocol.h.
Referenced by valid_serial_prot().
[struct]
struct { ... } AP_RCProtocol::added
Referenced by add_uart(), check_added_uart(), AP_RCProtocol_Backend::get_available_UART(), AP_RCProtocol_Backend::get_UART(), has_uart(), and AP_RCProtocol_Backend::have_UART().
backend
AP_RCProtocol_Backend* AP_RCProtocol::backend[NONE] private
Definition at line 222 of file AP_RCProtocol.h.
Referenced by check_added_uart(), detect_async_protocol(), get_RSSI(), get_rx_link_quality(), init(), AP_RCProtocol_Backend::is_detected(), new_input(), num_channels(), process_byte(), process_handshake(), process_pulse(), read(), read(), start_bind(), and ~AP_RCProtocol().
config_num
uint8_t AP_RCProtocol::config_num
Definition at line 233 of file AP_RCProtocol.h.
last_config_change_ms
uint32_t AP_RCProtocol::last_config_change_ms
Definition at line 232 of file AP_RCProtocol.h.
opened
bool AP_RCProtocol::opened
Definition at line 231 of file AP_RCProtocol.h.
rc_protocols_mask
uint32_t AP_RCProtocol::rc_protocols_mask private
Definition at line 237 of file AP_RCProtocol.h.
Referenced by check_added_uart(), AP_RCProtocol_Backend::get_rc_protocols_mask(), process_byte(), process_pulse(), protocol_enabled(), and set_rc_protocols().
uart
AP_HAL::UARTDriver* AP_RCProtocol::uart
Definition at line 230 of file AP_RCProtocol.h.
Referenced by add_uart(), AP_RCProtocol::SerialConfig::apply_to_uart(), AP_RCProtocol_Backend::get_available_UART(), AP_RCProtocol_Backend::get_UART(), and AP_RCProtocol_Backend::have_UART().
The documentation for this class was generated from the following files:
libraries/AP_RCProtocol/AP_RCProtocol.h
libraries/AP_RCProtocol/AP_RCProtocol.cpp