APM:Libraries: AP_Mission Class Reference
AP_Mission Class Reference
Object managing Mission.
#include <AP_Mission.h>
Classes
struct Altitude_Wait
struct AuxFunction
struct Cam_Trigg_Distance
struct Change_Speed_Command
struct Conditional_Delay_Command
struct Conditional_Distance_Command
union Content
struct Digicam_Configure
struct Digicam_Control
struct Do_Engine_Control
struct Do_VTOL_Transition
struct gimbal_manager_pitchyaw_Command
struct Gripper_Command
struct Guided_Limits_Command
struct image_start_capture_Command
struct Jump_Command
struct jump_tracking_struct
struct Mission_Command
struct Mission_Flags
struct Mount_Control
struct nav_attitude_time_Command
struct Navigation_Delay_Command
struct Repeat_Relay_Command
struct Repeat_Servo_Command
struct scripting_Command
struct set_camera_focus_Command
struct set_camera_zoom_Command
struct Set_Relay_Command
struct Set_Servo_Command
struct Set_Yaw_Speed
struct video_start_capture_Command
struct video_stop_capture_Command
struct Winch_Command
struct Yaw_Command
Public Types
enum mission_state { MISSION_STOPPED =0 , MISSION_RUNNING =1 , MISSION_COMPLETE =2 }
Public Member Functions
FUNCTOR_TYPEDEF (mission_cmd_fn_t, bool, const Mission_Command &)
FUNCTOR_TYPEDEF (mission_complete_fn_t, void)
AP_Mission (mission_cmd_fn_t cmd_start_fn, mission_cmd_fn_t cmd_verify_fn, mission_complete_fn_t mission_complete_fn)
CLASS_NO_COPY (AP_Mission)
void init ()
init - initialises this library including checks the version in eeprom matches this library
mission_state state () const
status - returns the status of the mission (i.e. Mission_Started, Mission_Complete, Mission_Stopped
uint16_t num_commands () const
uint16_t num_commands_max () const
num_commands_max - returns maximum number of commands that can be stored
void start ()
void stop ()
stop - stops mission execution. subsequent calls to update() will have no effect until the mission is started or resumed
void resume ()
void start_or_resume ()
start_or_resume - if MIS_AUTORESTART=0 this will call resume(), otherwise it will call start()
bool starts_with_takeoff_cmd ()
check mission starts with a takeoff command
void reset ()
reset - reset mission to the first command
bool clear ()
clear - clears out mission
void truncate (uint16_t index)
truncate - truncate any mission items beyond given index
void update ()
bool add_cmd (Mission_Command &cmd)
bool replace_cmd (uint16_t index, const Mission_Command &cmd)
const Mission_Command & get_current_nav_cmd () const
get_current_nav_cmd - returns the current "navigation" command
uint16_t get_current_nav_index () const
uint16_t get_current_nav_id () const
get_current_nav_id - return the id of the current nav command
uint16_t get_prev_nav_cmd_id () const
uint16_t get_prev_nav_cmd_index () const
uint16_t get_prev_nav_cmd_with_wp_index () const
bool get_next_nav_cmd (uint16_t start_index, Mission_Command &cmd)
int32_t get_next_ground_course_cd (int32_t default_angle)
const Mission_Command & get_current_do_cmd () const
get_current_do_cmd - returns active "do" command
uint16_t get_current_do_cmd_id () const
get_current_do_cmd_id - returns id of the active "do" command
bool set_current_cmd (uint16_t index)
bool restart_current_nav_cmd ()
bool read_cmd_from_storage (uint16_t index, Mission_Command &cmd) const
bool write_cmd_to_storage (uint16_t index, const Mission_Command &cmd)
void write_home_to_storage ()
uint32_t last_change_time_ms (void) const
uint16_t get_landing_sequence_start ()
bool jump_to_landing_sequence (void)
bool jump_to_abort_landing_sequence (void)
bool is_best_land_sequence (void)
void set_in_landing_sequence_flag (bool flag)
bool get_in_landing_sequence_flag () const
void set_force_resume (bool force_resume)
HAL_Semaphore & get_semaphore (void)
bool contains_item (MAV_CMD command) const
bool contains_terrain_alt_items (void)
void reset_wp_history (void)
bool continue_after_land_check_for_takeoff (void)
bool continue_after_land (void) const
bool get_item (uint16_t index, mavlink_mission_item_int_t &result) const
bool set_item (uint16_t index, mavlink_mission_item_int_t &source)
bool get_last_jump_tag (uint16_t &tag, uint16_t &age) const
bool jump_to_tag (const uint16_t tag)
uint16_t get_index_of_jump_tag (const uint16_t tag) const
bool is_valid_index (const uint16_t index) const
Static Public Member Functions
static AP_Mission * get_singleton ()
static bool is_nav_cmd (const Mission_Command &cmd)
is_nav_cmd - returns true if the command's id is a "navigation" command, false if "do" or "conditional" command
static MAV_MISSION_RESULT convert_MISSION_ITEM_to_MISSION_ITEM_INT (const mavlink_mission_item_t &mission_item, mavlink_mission_item_int_t &mission_item_int) WARN_IF_UNUSED
static MAV_MISSION_RESULT convert_MISSION_ITEM_INT_to_MISSION_ITEM (const mavlink_mission_item_int_t &mission_item_int, mavlink_mission_item_t &mission_item) WARN_IF_UNUSED
static MAV_MISSION_RESULT mavlink_int_to_mission_cmd (const mavlink_mission_item_int_t &packet, AP_Mission::Mission_Command &cmd)
static bool mission_cmd_to_mavlink_int (const AP_Mission::Mission_Command &cmd, mavlink_mission_item_int_t &packet)
static bool cmd_has_location (const uint16_t command)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void complete ()
complete - mission is marked complete and clean-up performed including calling the mission_complete_fn
bool verify_command (const Mission_Command &cmd)
bool start_command (const Mission_Command &cmd)
bool advance_current_nav_cmd (uint16_t starting_index=0)
advance_current_nav_cmd - moves current nav command forward
void advance_current_do_cmd ()
bool get_next_cmd (uint16_t start_index, Mission_Command &cmd, bool increment_jump_num_times_if_found, bool send_gcs_msg=true)
bool get_next_do_cmd (uint16_t start_index, Mission_Command &cmd)
void init_jump_tracking ()
int16_t get_jump_times_run (const Mission_Command &cmd)
void increment_jump_times_run (Mission_Command &cmd, bool send_gcs_msg=true)
increment_jump_times_run - increments the recorded number of times the jump command has been run
void check_eeprom_version ()
bool is_landing_type_cmd (uint16_t id) const
bool is_takeoff_type_cmd (uint16_t id) const
bool distance_to_landing (uint16_t index, float &tot_distance, Location current_loc)
bool calc_rewind_pos (Mission_Command &rewind_cmd)
void update_exit_position (void)
void on_mission_timestamp_change ()
bool is_takeoff_next (uint16_t start_index)
check if the next nav command is a takeoff, skipping delays
uint16_t get_command_id (uint16_t index) const
bool calculate_contains_terrain_alt_items (void) const
bool start_command_do_aux_function (const AP_Mission::Mission_Command &cmd)
bool start_command_do_gripper (const AP_Mission::Mission_Command &cmd)
bool start_command_do_servorelayevents (const AP_Mission::Mission_Command &cmd)
bool start_command_camera (const AP_Mission::Mission_Command &cmd)
bool start_command_parachute (const AP_Mission::Mission_Command &cmd)
bool command_do_set_repeat_dist (const AP_Mission::Mission_Command &cmd)
bool start_command_do_sprayer (const AP_Mission::Mission_Command &cmd)
bool start_command_do_scripting (const AP_Mission::Mission_Command &cmd)
bool start_command_do_gimbal_manager_pitchyaw (const AP_Mission::Mission_Command &cmd)
void format_conversion (uint8_t tag_byte, const Mission_Command &cmd, PackedContent &packed_content) const
Static Private Member Functions
static bool stored_in_location (uint16_t id)
static MAV_MISSION_RESULT sanity_check_params (const mavlink_mission_item_int_t &packet)
sanity checks that the masked fields are not NaN's or infinite
Private Attributes
struct {
uint16_t age
uint16_t tag
} _jump_tag
struct AP_Mission::Mission_Flags _flags
uint16_t _wp_index_history [AP_MISSION_MAX_WP_HISTORY]
mission_cmd_fn_t _cmd_start_fn
mission_cmd_fn_t _cmd_verify_fn
mission_complete_fn_t _mission_complete_fn
AP_Int16 _cmd_total
AP_Int16 _options
AP_Int8 _restart
bool _force_resume
uint16_t _repeat_dist
struct Mission_Command _nav_cmd
struct Mission_Command _do_cmd
struct Mission_Command _resume_cmd
uint16_t _prev_nav_cmd_id
uint16_t _prev_nav_cmd_index
uint16_t _prev_nav_cmd_wp_index
Location _exit_position
struct AP_Mission::jump_tracking_struct _jump_tracking [AP_MISSION_MAX_NUM_DO_JUMP_COMMANDS]
uint32_t _last_change_time_ms
uint32_t _last_change_time_prev_ms
uint16_t _commands_max
bool _contains_terrain_alt_items
uint32_t _last_contains_relative_calculated_ms
Static Private Attributes
static AP_Mission * _singleton
static StorageAccess _storage
static HAL_Semaphore _rsem
Detailed Description
Object managing Mission.
Definition at line 65 of file AP_Mission.h.
Member Enumeration Documentation
mission_state
enum AP_Mission::mission_state
Enumerator
MISSION_STOPPED
MISSION_RUNNING
MISSION_COMPLETE
Definition at line 472 of file AP_Mission.h.
Constructor & Destructor Documentation
AP_Mission()
AP_Mission::AP_Mission (mission_cmd_fn_t cmd_start_fn, mission_cmd_fn_t cmd_verify_fn, mission_complete_fn_t mission_complete_fn) inline
Definition at line 439 of file AP_Mission.h.
Member Function Documentation
add_cmd()
bool AP_Mission::add_cmd (Mission_Command & cmd)
public command methods add_cmd - adds a command to the end of the command list and writes to storage returns true if successfully added, false on failure cmd.index is updated with it's new position in the mission
Referenced by MissionTest::init_mission(), MissionTest::init_mission_endless_loop(), MissionTest::init_mission_ends_with_do_commands(), MissionTest::init_mission_ends_with_jump_command(), MissionTest::init_mission_jump_to_nonnav(), MissionTest::init_mission_no_nav_commands(), MissionTest::init_mission_starts_with_do_commands(), MissionTest::run_max_cmd_test(), MissionTest::run_replace_cmd_test(), MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_test(), and MissionTest::run_set_current_cmd_while_stopped_test().
advance_current_do_cmd()
void AP_Mission::advance_current_do_cmd () private
advance_current_do_cmd - moves current do command forward accounts for do-jump commands returns true if successfully advanced (can it ever be unsuccessful?)
advance_current_nav_cmd()
bool AP_Mission::advance_current_nav_cmd (uint16_t starting_index = 0) private
advance_current_nav_cmd - moves current nav command forward
do command will also be loaded accounts for do-jump commands
calc_rewind_pos()
bool AP_Mission::calc_rewind_pos (Mission_Command & rewind_cmd) private
calculate_contains_terrain_alt_items()
bool AP_Mission::calculate_contains_terrain_alt_items (void) const private
check_eeprom_version()
void AP_Mission::check_eeprom_version () private
check_eeprom_version - checks version of missions stored in eeprom matches this library command list will be cleared if they do not match
CLASS_NO_COPY()
AP_Mission::CLASS_NO_COPY (AP_Mission)
clear()
bool AP_Mission::clear ()
clear - clears out mission
Referenced by MissionTest::init_mission(), MissionTest::init_mission_endless_loop(), MissionTest::init_mission_ends_with_do_commands(), MissionTest::init_mission_ends_with_jump_command(), MissionTest::init_mission_jump_to_nonnav(), MissionTest::init_mission_no_nav_commands(), and MissionTest::init_mission_starts_with_do_commands().
cmd_has_location()
static bool AP_Mission::cmd_has_location (const uint16_t command) static
command_do_set_repeat_dist()
bool AP_Mission::command_do_set_repeat_dist (const AP_Mission::Mission_Command & cmd) private
complete()
void AP_Mission::complete () private
complete - mission is marked complete and clean-up performed including calling the mission_complete_fn
private methods
contains_item()
bool AP_Mission::contains_item (MAV_CMD command) const
contains_terrain_alt_items()
bool AP_Mission::contains_terrain_alt_items (void)
Referenced by AP_Arming::terrain_database_required().
continue_after_land()
bool AP_Mission::continue_after_land (void) const inline
Definition at line 714 of file AP_Mission.h.
Referenced by AP_Landing::type_slope_verify_land().
continue_after_land_check_for_takeoff()
bool AP_Mission::continue_after_land_check_for_takeoff (void)
convert_MISSION_ITEM_INT_to_MISSION_ITEM()
static MAV_MISSION_RESULT AP_Mission::convert_MISSION_ITEM_INT_to_MISSION_ITEM (const mavlink_mission_item_int_t & mission_item_int, mavlink_mission_item_t & mission_item) static
convert_MISSION_ITEM_to_MISSION_ITEM_INT()
static MAV_MISSION_RESULT AP_Mission::convert_MISSION_ITEM_to_MISSION_ITEM_INT (const mavlink_mission_item_t & mission_item, mavlink_mission_item_int_t & mission_item_int) static
Referenced by GCS_MAVLINK::handle_mission_item().
distance_to_landing()
bool AP_Mission::distance_to_landing (uint16_t index, float & tot_distance, Location current_loc) private
format_conversion()
void AP_Mission::format_conversion (uint8_t tag_byte, const Mission_Command & cmd, PackedContent & packed_content) const private
FUNCTOR_TYPEDEF() [1/2]
AP_Mission::FUNCTOR_TYPEDEF (mission_cmd_fn_t , bool , const Mission_Command &)
FUNCTOR_TYPEDEF() [2/2]
AP_Mission::FUNCTOR_TYPEDEF (mission_complete_fn_t , void)
get_command_id()
uint16_t AP_Mission::get_command_id (uint16_t index) const private
get_current_do_cmd()
const Mission_Command & AP_Mission::get_current_do_cmd () const inline
get_current_do_cmd - returns active "do" command
Definition at line 605 of file AP_Mission.h.
get_current_do_cmd_id()
uint16_t AP_Mission::get_current_do_cmd_id () const inline
get_current_do_cmd_id - returns id of the active "do" command
Definition at line 611 of file AP_Mission.h.
get_current_nav_cmd()
const Mission_Command & AP_Mission::get_current_nav_cmd () const inline
get_current_nav_cmd - returns the current "navigation" command
Definition at line 551 of file AP_Mission.h.
Referenced by AP_AdvancedFailsafe::check(), and AP_Landing::restart_landing_sequence().
get_current_nav_id()
uint16_t AP_Mission::get_current_nav_id () const inline
get_current_nav_id - return the id of the current nav command
Definition at line 565 of file AP_Mission.h.
get_current_nav_index()
uint16_t AP_Mission::get_current_nav_index () const inline
get_current_nav_index - returns the current "navigation" command index Note that this will return 0 if there is no command. This is used in MAVLink reporting of the mission command
Definition at line 559 of file AP_Mission.h.
Referenced by AP_Frsky_SPort_Passthrough::calc_waypoint(), AP_Frsky_SPort_Passthrough::is_packet_ready(), AP_Landing::restart_landing_sequence(), GCS_MAVLINK::send_high_latency2(), AP_Hott_Telem::send_Vario(), and GCS_MAVLINK::try_send_mission_message().
get_in_landing_sequence_flag()
bool AP_Mission::get_in_landing_sequence_flag () const inline
Definition at line 678 of file AP_Mission.h.
get_index_of_jump_tag()
uint16_t AP_Mission::get_index_of_jump_tag (const uint16_t tag) const
get_item()
bool AP_Mission::get_item (uint16_t index, mavlink_mission_item_int_t & result) const
get_jump_times_run()
int16_t AP_Mission::get_jump_times_run (const Mission_Command & cmd) private
get_jump_times_run - returns number of times the jump command has been run return is signed to be consistent with do-jump cmd's repeat count which can be -1 (to signify to repeat forever)
get_landing_sequence_start()
uint16_t AP_Mission::get_landing_sequence_start ()
Referenced by AP_Landing::restart_landing_sequence().
get_last_jump_tag()
bool AP_Mission::get_last_jump_tag (uint16_t & tag, uint16_t & age) const
get_next_cmd()
bool AP_Mission::get_next_cmd (uint16_t start_index, Mission_Command & cmd, bool increment_jump_num_times_if_found, bool send_gcs_msg = true) private
get_next_cmd - gets next command found at or after start_index returns true if found, false if not found (i.e. mission complete) accounts for do_jump commands increment_jump_num_times_if_found should be set to true if advancing the active navigation command
get_next_do_cmd()
bool AP_Mission::get_next_do_cmd (uint16_t start_index, Mission_Command & cmd) private
get_next_do_cmd - gets next "do" or "conditional" command after start_index returns true if found, false if not found stops and returns false if it hits another navigation command before it finds the first do or conditional command accounts for do_jump commands but never increments the jump's num_times_run (get_next_nav_cmd is responsible for this)
get_next_ground_course_cd()
int32_t AP_Mission::get_next_ground_course_cd (int32_t default_angle)
get the ground course of the next navigation leg in centidegrees from 0 36000. Return default_angle if next navigation leg cannot be determined
get_next_nav_cmd()
bool AP_Mission::get_next_nav_cmd (uint16_t start_index, Mission_Command & cmd)
get_next_nav_cmd - gets next "navigation" command found at or after start_index returns true if found, false if not found (i.e. reached end of mission command list) accounts for do_jump commands
get_prev_nav_cmd_id()
uint16_t AP_Mission::get_prev_nav_cmd_id () const inline
get_prev_nav_cmd_id - returns the previous "navigation" command id if there was no previous nav command it returns AP_MISSION_CMD_ID_NONE we do not return the entire command to save on RAM
Definition at line 573 of file AP_Mission.h.
Referenced by AP_Landing::type_slope_verify_land().
get_prev_nav_cmd_index()
uint16_t AP_Mission::get_prev_nav_cmd_index () const inline
get_prev_nav_cmd_index - returns the previous "navigation" commands index (i.e. position in the mission command list) if there was no previous nav command it returns AP_MISSION_CMD_INDEX_NONE we do not return the entire command to save on RAM
Definition at line 581 of file AP_Mission.h.
get_prev_nav_cmd_with_wp_index()
uint16_t AP_Mission::get_prev_nav_cmd_with_wp_index () const inline
get_prev_nav_cmd_with_wp_index - returns the previous "navigation" commands index that contains a waypoint (i.e. position in the mission command list) if there was no previous nav command it returns AP_MISSION_CMD_INDEX_NONE we do not return the entire command to save on RAM
Definition at line 589 of file AP_Mission.h.
Referenced by AP_Landing::restart_landing_sequence().
get_semaphore()
HAL_Semaphore & AP_Mission::get_semaphore (void) inline
Definition at line 690 of file AP_Mission.h.
get_singleton()
static AP_Mission * AP_Mission::get_singleton () inline static
Definition at line 463 of file AP_Mission.h.
increment_jump_times_run()
void AP_Mission::increment_jump_times_run (Mission_Command & cmd, bool send_gcs_msg = true) private
increment_jump_times_run - increments the recorded number of times the jump command has been run
init()
void AP_Mission::init ()
init - initialises this library including checks the version in eeprom matches this library
public mission methods
init_jump_tracking()
void AP_Mission::init_jump_tracking () private
jump handling methods
is_best_land_sequence()
bool AP_Mission::is_best_land_sequence (void)
is_landing_type_cmd()
bool AP_Mission::is_landing_type_cmd (uint16_t id) const private
is_nav_cmd()
static bool AP_Mission::is_nav_cmd (const Mission_Command & cmd) static
is_nav_cmd - returns true if the command's id is a "navigation" command, false if "do" or "conditional" command
Referenced by MissionTest::print_mission(), MissionTest::start_cmd(), and MissionTest::verify_cmd().
is_takeoff_next()
bool AP_Mission::is_takeoff_next (uint16_t start_index) private
check if the next nav command is a takeoff, skipping delays
is_takeoff_type_cmd()
bool AP_Mission::is_takeoff_type_cmd (uint16_t id) const private
is_valid_index()
bool AP_Mission::is_valid_index (const uint16_t index) const inline
Definition at line 740 of file AP_Mission.h.
jump_to_abort_landing_sequence()
bool AP_Mission::jump_to_abort_landing_sequence (void)
jump_to_landing_sequence()
bool AP_Mission::jump_to_landing_sequence (void)
jump_to_tag()
bool AP_Mission::jump_to_tag (const uint16_t tag)
last_change_time_ms()
uint32_t AP_Mission::last_change_time_ms (void) const inline
Definition at line 650 of file AP_Mission.h.
mavlink_int_to_mission_cmd()
static MAV_MISSION_RESULT AP_Mission::mavlink_int_to_mission_cmd (const mavlink_mission_item_int_t & packet, AP_Mission::Mission_Command & cmd) static
Referenced by GCS_MAVLINK::handle_mission_item().
mission_cmd_to_mavlink_int()
static bool AP_Mission::mission_cmd_to_mavlink_int (const AP_Mission::Mission_Command & cmd, mavlink_mission_item_int_t & packet) static
Referenced by AP_Logger_Backend::Write_Mission_Cmd().
num_commands()
uint16_t AP_Mission::num_commands () const inline
num_commands - returns total number of commands in the mission this number includes offset 0, the home location
Definition at line 493 of file AP_Mission.h.
Referenced by GCS_MAVLINK::mission_state(), MissionTest::print_mission(), MissionTest::run_max_cmd_test(), GCS_MAVLINK::send_mission_current(), and AP_Logger_Backend::Write_Mission_Cmd().
num_commands_max()
uint16_t AP_Mission::num_commands_max () const inline
num_commands_max - returns maximum number of commands that can be stored
Definition at line 499 of file AP_Mission.h.
Referenced by MissionTest::run_max_cmd_test(), and MissionTest::setup().
on_mission_timestamp_change()
void AP_Mission::on_mission_timestamp_change () private
read_cmd_from_storage()
bool AP_Mission::read_cmd_from_storage (uint16_t index, Mission_Command & cmd) const
load_cmd_from_storage - load command from storage true is return if successful
Referenced by MissionTest::print_mission(), LoggerMessageWriter_WriteEntireMission::process(), AP_Landing::restart_landing_sequence(), and MissionTest::run_max_cmd_test().
replace_cmd()
bool AP_Mission::replace_cmd (uint16_t index, const Mission_Command & cmd)
replace_cmd - replaces the command at position 'index' in the command list with the provided cmd replacing the current active command will have no effect until the command is restarted returns true if successfully replaced, false on failure
Referenced by MissionTest::run_replace_cmd_test().
reset()
void AP_Mission::reset ()
reset - reset mission to the first command
reset_wp_history()
void AP_Mission::reset_wp_history (void)
restart_current_nav_cmd()
bool AP_Mission::restart_current_nav_cmd ()
resume()
void AP_Mission::resume ()
resume - continues the mission execution from where we last left off previous running commands will be re-initialised
Referenced by MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_while_stopped_test(), and AP_Landing::verify_abort_landing().
sanity_check_params()
static MAV_MISSION_RESULT AP_Mission::sanity_check_params (const mavlink_mission_item_int_t & packet) static private
sanity checks that the masked fields are not NaN's or infinite
set_current_cmd()
bool AP_Mission::set_current_cmd (uint16_t index)
Referenced by AP_AdvancedFailsafe::check(), AP_Landing::restart_landing_sequence(), MissionTest::run_set_current_cmd_test(), and MissionTest::run_set_current_cmd_while_stopped_test().
set_force_resume()
void AP_Mission::set_force_resume (bool force_resume) inline
Definition at line 683 of file AP_Mission.h.
set_in_landing_sequence_flag()
void AP_Mission::set_in_landing_sequence_flag (bool flag) inline
Definition at line 672 of file AP_Mission.h.
set_item()
bool AP_Mission::set_item (uint16_t index, mavlink_mission_item_int_t & source)
start()
void AP_Mission::start ()
start - resets current commands to point to the beginning of the mission To-Do: should we validate the mission first and return true/false?
Referenced by MissionTest::run_mission_test(), MissionTest::run_replace_cmd_test(), MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_test(), and MissionTest::run_set_current_cmd_while_stopped_test().
start_command()
bool AP_Mission::start_command (const Mission_Command & cmd) private
start_command_camera()
bool AP_Mission::start_command_camera (const AP_Mission::Mission_Command & cmd) private
start_command_do_aux_function()
bool AP_Mission::start_command_do_aux_function (const AP_Mission::Mission_Command & cmd) private
start_command_do_gimbal_manager_pitchyaw()
bool AP_Mission::start_command_do_gimbal_manager_pitchyaw (const AP_Mission::Mission_Command & cmd) private
start_command_do_gripper()
bool AP_Mission::start_command_do_gripper (const AP_Mission::Mission_Command & cmd) private
start_command_do_scripting()
bool AP_Mission::start_command_do_scripting (const AP_Mission::Mission_Command & cmd) private
start_command_do_servorelayevents()
bool AP_Mission::start_command_do_servorelayevents (const AP_Mission::Mission_Command & cmd) private
start_command_do_sprayer()
bool AP_Mission::start_command_do_sprayer (const AP_Mission::Mission_Command & cmd) private
start_command_parachute()
bool AP_Mission::start_command_parachute (const AP_Mission::Mission_Command & cmd) private
start_or_resume()
void AP_Mission::start_or_resume ()
start_or_resume - if MIS_AUTORESTART=0 this will call resume(), otherwise it will call start()
starts_with_takeoff_cmd()
bool AP_Mission::starts_with_takeoff_cmd ()
check mission starts with a takeoff command
state()
mission_state AP_Mission::state () const inline
status - returns the status of the mission (i.e. Mission_Started, Mission_Complete, Mission_Stopped
Definition at line 486 of file AP_Mission.h.
Referenced by GCS_MAVLINK::mission_state(), and MissionTest::run_set_current_cmd_while_stopped_test().
stop()
void AP_Mission::stop ()
stop - stops mission execution. subsequent calls to update() will have no effect until the mission is started or resumed
Referenced by MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_while_stopped_test(), and AP_Landing::verify_abort_landing().
stored_in_location()
static bool AP_Mission::stored_in_location (uint16_t id) static private
truncate()
void AP_Mission::truncate (uint16_t index)
truncate - truncate any mission items beyond given index
update()
void AP_Mission::update ()
update - ensures the command queues are loaded with the next command and calls main programs command_init and command_verify functions to progress the mission should be called at 10hz or higher
Referenced by MissionTest::run_mission_test(), MissionTest::run_replace_cmd_test(), MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_test(), and MissionTest::run_set_current_cmd_while_stopped_test().
update_exit_position()
void AP_Mission::update_exit_position (void) private
verify_command()
bool AP_Mission::verify_command (const Mission_Command & cmd) private
write_cmd_to_storage()
bool AP_Mission::write_cmd_to_storage (uint16_t index, const Mission_Command & cmd)
write_cmd_to_storage - write a command to storage cmd.index is used to calculate the storage location true is returned if successful
write_home_to_storage()
void AP_Mission::write_home_to_storage ()
write_home_to_storage - writes the special purpose cmd 0 (home) to storage home is taken directly from ahrs
Member Data Documentation
_cmd_start_fn
mission_cmd_fn_t AP_Mission::_cmd_start_fn private
Definition at line 847 of file AP_Mission.h.
_cmd_total
AP_Int16 AP_Mission::_cmd_total private
Definition at line 852 of file AP_Mission.h.
Referenced by is_valid_index(), and num_commands().
_cmd_verify_fn
mission_cmd_fn_t AP_Mission::_cmd_verify_fn private
Definition at line 848 of file AP_Mission.h.
_commands_max
uint16_t AP_Mission::_commands_max private
Definition at line 878 of file AP_Mission.h.
Referenced by num_commands_max().
_contains_terrain_alt_items
bool AP_Mission::_contains_terrain_alt_items private
Definition at line 888 of file AP_Mission.h.
_do_cmd
struct Mission_Command AP_Mission::_do_cmd private
Definition at line 860 of file AP_Mission.h.
Referenced by AP_Mission(), get_current_do_cmd(), and get_current_do_cmd_id().
_exit_position
Location AP_Mission::_exit_position private
Definition at line 865 of file AP_Mission.h.
_flags
struct AP_Mission::Mission_Flags AP_Mission::_flags private
Referenced by get_in_landing_sequence_flag(), set_in_landing_sequence_flag(), and state().
_force_resume
bool AP_Mission::_force_resume private
Definition at line 857 of file AP_Mission.h.
Referenced by set_force_resume().
[struct]
struct { ... } AP_Mission::_jump_tag
_jump_tracking
struct AP_Mission::jump_tracking_struct AP_Mission::_jump_tracking[AP_MISSION_MAX_NUM_DO_JUMP_COMMANDS] private
_last_change_time_ms
uint32_t AP_Mission::_last_change_time_ms private
Definition at line 874 of file AP_Mission.h.
Referenced by last_change_time_ms().
_last_change_time_prev_ms
uint32_t AP_Mission::_last_change_time_prev_ms private
Definition at line 875 of file AP_Mission.h.
_last_contains_relative_calculated_ms
uint32_t AP_Mission::_last_contains_relative_calculated_ms private
Definition at line 889 of file AP_Mission.h.
_mission_complete_fn
mission_complete_fn_t AP_Mission::_mission_complete_fn private
Definition at line 849 of file AP_Mission.h.
_nav_cmd
struct Mission_Command AP_Mission::_nav_cmd private
Definition at line 859 of file AP_Mission.h.
Referenced by AP_Mission(), get_current_nav_cmd(), get_current_nav_id(), and get_current_nav_index().
_options
AP_Int16 AP_Mission::_options private
Definition at line 853 of file AP_Mission.h.
Referenced by continue_after_land().
_prev_nav_cmd_id
uint16_t AP_Mission::_prev_nav_cmd_id private
Definition at line 862 of file AP_Mission.h.
Referenced by get_prev_nav_cmd_id().
_prev_nav_cmd_index
uint16_t AP_Mission::_prev_nav_cmd_index private
Definition at line 863 of file AP_Mission.h.
Referenced by get_prev_nav_cmd_index().
_prev_nav_cmd_wp_index
uint16_t AP_Mission::_prev_nav_cmd_wp_index private
Definition at line 864 of file AP_Mission.h.
Referenced by get_prev_nav_cmd_with_wp_index().
_repeat_dist
uint16_t AP_Mission::_repeat_dist private
Definition at line 858 of file AP_Mission.h.
_restart
AP_Int8 AP_Mission::_restart private
Definition at line 854 of file AP_Mission.h.
_resume_cmd
struct Mission_Command AP_Mission::_resume_cmd private
Definition at line 861 of file AP_Mission.h.
_rsem
HAL_Semaphore AP_Mission::_rsem static private
Definition at line 894 of file AP_Mission.h.
Referenced by get_semaphore().
_singleton
AP_Mission* AP_Mission::_singleton static private
Definition at line 749 of file AP_Mission.h.
Referenced by AP_Mission(), and get_singleton().
_storage
StorageAccess AP_Mission::_storage static private
Definition at line 751 of file AP_Mission.h.
_wp_index_history
uint16_t AP_Mission::_wp_index_history[AP_MISSION_MAX_WP_HISTORY] private
Definition at line 770 of file AP_Mission.h.
age
uint16_t AP_Mission::age
Definition at line 756 of file AP_Mission.h.
tag
uint16_t AP_Mission::tag
Definition at line 757 of file AP_Mission.h.
var_info
const struct AP_Param::GroupInfo AP_Mission::var_info[] static
Definition at line 719 of file AP_Mission.h.
The documentation for this class was generated from the following file:
libraries/AP_Mission/AP_Mission.h