APM:Libraries: AP_JSON Class Reference
AP_JSON Class Reference
#include <AP_JSON.h>
Classes
struct null
class value
Static Public Member Functions
static std::string parse (value &out, const std::string &s)
static value * load_json (const char *filename)
Detailed Description
Definition at line 18 of file AP_JSON.h.
Member Function Documentation
load_json()
AP_JSON::value * AP_JSON::load_json (const char * filename) static
Definition at line 47 of file AP_JSON.cpp.
Referenced by SITL::XPlane::load_dref_map(), SITL::Frame::load_frame_params(), and test_xplane().
parse()
std::string AP_JSON::parse (value & out, const std::string & s) static
Definition at line 713 of file AP_JSON.cpp.
Referenced by load_json(), and parse().
The documentation for this class was generated from the following files:
libraries/AP_JSON/AP_JSON.h
libraries/AP_JSON/AP_JSON.cpp