APM:Libraries: AP_BattMonitor_Bebop Class Reference
AP_BattMonitor_Bebop Class Reference
#include <AP_BattMonitor_Bebop.h>
Public Member Functions
AP_BattMonitor_Bebop (AP_BattMonitor &mon, AP_BattMonitor::BattMonitor_State &mon_state, AP_BattMonitor_Params &params)
virtual ~AP_BattMonitor_Bebop (void)
void init () override
void read () override
bool has_current () const override
returns true if battery monitor instance provides current info
bool reset_remaining (float percentage) override
Public Member Functions inherited from AP_BattMonitor_Backend
AP_BattMonitor_Backend (AP_BattMonitor &mon, AP_BattMonitor::BattMonitor_State &mon_state, AP_BattMonitor_Params &params)
virtual ~AP_BattMonitor_Backend (void)
virtual bool has_time_remaining () const
returns true if battery monitor instance provides time remaining info
virtual bool has_consumed_energy () const
returns true if battery monitor instance provides consumed energy info
virtual bool has_cell_voltages () const
virtual bool has_temperature () const
virtual bool get_temperature (float &temperature) const
virtual bool capacity_remaining_pct (uint8_t &percentage) const WARN_IF_UNUSED
virtual bool get_cycle_count (uint16_t &cycles) const
bool get_state_of_health_pct (uint8_t &soh_pct) const
float voltage_resting_estimate () const
virtual void update_resistance_estimate ()
virtual AP_BattMonitor::Failsafe update_failsafes (void)
bool arming_checks (char *buffer, size_t buflen) const
virtual uint32_t get_mavlink_fault_bitmask () const
void Log_Write_BAT (const uint8_t instance, const uint64_t time_us) const
void Log_Write_BCL (const uint8_t instance, const uint64_t time_us) const
virtual void mppt_set_powered_state (bool power_on)
void update_esc_telem_outbound ()
bool option_is_set (const AP_BattMonitor_Params::Options option) const
Private Member Functions
float _compute_compensation (const uint16_t *rpm, float vbat_raw)
float _filter_voltage (float vbat_raw)
float _compute_battery_percentage (float vbat)
Private Attributes
float _prev_vbat_raw
float _prev_vbat
float _battery_voltage_max
Additional Inherited Members
Static Public Member Functions inherited from AP_BattMonitor_Backend
static float calculate_mah (float amps, float dt_us)
Protected Member Functions inherited from AP_BattMonitor_Backend
void check_failsafe_types (bool &low_voltage, bool &low_capacity, bool &critical_voltage, bool &critical_capacity) const
void update_consumed (AP_BattMonitor::BattMonitor_State &state, uint32_t dt_us)
Protected Attributes inherited from AP_BattMonitor_Backend
AP_BattMonitor & _mon
AP_BattMonitor::BattMonitor_State & _state
AP_BattMonitor_Params & _params
Detailed Description
Definition at line 21 of file AP_BattMonitor_Bebop.h.
Constructor & Destructor Documentation
AP_BattMonitor_Bebop()
AP_BattMonitor_Bebop::AP_BattMonitor_Bebop (AP_BattMonitor & mon, AP_BattMonitor::BattMonitor_State & mon_state, AP_BattMonitor_Params & params) inline
Definition at line 25 of file AP_BattMonitor_Bebop.h.
~AP_BattMonitor_Bebop()
virtual AP_BattMonitor_Bebop::~AP_BattMonitor_Bebop (void) inline virtual
Definition at line 32 of file AP_BattMonitor_Bebop.h.
Member Function Documentation
_compute_battery_percentage()
float AP_BattMonitor_Bebop::_compute_battery_percentage (float vbat) private
Definition at line 136 of file AP_BattMonitor_Bebop.cpp.
Referenced by read().
_compute_compensation()
float AP_BattMonitor_Bebop::_compute_compensation (const uint16_t * rpm, float vbat_raw) private
Definition at line 118 of file AP_BattMonitor_Bebop.cpp.
Referenced by read().
_filter_voltage()
float AP_BattMonitor_Bebop::_filter_voltage (float vbat_raw) private
Definition at line 88 of file AP_BattMonitor_Bebop.cpp.
Referenced by read().
has_current()
bool AP_BattMonitor_Bebop::has_current () const inline override virtual
returns true if battery monitor instance provides current info
Implements AP_BattMonitor_Backend.
Definition at line 41 of file AP_BattMonitor_Bebop.h.
init()
void AP_BattMonitor_Bebop::init (void) override virtual
Reimplemented from AP_BattMonitor_Backend.
Definition at line 81 of file AP_BattMonitor_Bebop.cpp.
read()
void AP_BattMonitor_Bebop::read (void) override virtual
Implements AP_BattMonitor_Backend.
Definition at line 159 of file AP_BattMonitor_Bebop.cpp.
reset_remaining()
bool AP_BattMonitor_Bebop::reset_remaining (float percentage) inline override virtual
Reimplemented from AP_BattMonitor_Backend.
Definition at line 44 of file AP_BattMonitor_Bebop.h.
Member Data Documentation
_battery_voltage_max
float AP_BattMonitor_Bebop::_battery_voltage_max private
Definition at line 49 of file AP_BattMonitor_Bebop.h.
Referenced by init(), and read().
_prev_vbat
float AP_BattMonitor_Bebop::_prev_vbat private
Definition at line 48 of file AP_BattMonitor_Bebop.h.
Referenced by _filter_voltage(), and init().
_prev_vbat_raw
float AP_BattMonitor_Bebop::_prev_vbat_raw private
Definition at line 47 of file AP_BattMonitor_Bebop.h.
Referenced by _filter_voltage(), and init().
The documentation for this class was generated from the following files:
libraries/AP_BattMonitor/AP_BattMonitor_Bebop.h
libraries/AP_BattMonitor/AP_BattMonitor_Bebop.cpp