APM:Libraries: AP_HAL::Scheduler Class Reference
AP_HAL::Scheduler Class Reference abstract
#include <Scheduler.h>
Public Types
enum priority_base {
PRIORITY_BOOST , PRIORITY_MAIN , PRIORITY_SPI , PRIORITY_I2C ,
PRIORITY_CAN , PRIORITY_TIMER , PRIORITY_RCOUT , PRIORITY_LED ,
PRIORITY_RCIN , PRIORITY_IO , PRIORITY_UART , PRIORITY_STORAGE ,
PRIORITY_SCRIPTING , PRIORITY_NET
}
Public Member Functions
Scheduler ()
virtual void init ()=0
virtual void delay (uint16_t ms)=0
virtual void delay_microseconds (uint16_t us)=0
virtual void delay_microseconds_boost (uint16_t us)
virtual void expect_delay_ms (uint32_t ms)
virtual bool in_expected_delay (void) const
virtual void boost_end (void)
virtual void register_delay_callback (AP_HAL::Proc, uint16_t min_time_ms)
virtual bool in_delay_callback () const
virtual void register_timer_process (AP_HAL::MemberProc)=0
virtual void register_io_process (AP_HAL::MemberProc)=0
virtual void register_timer_failsafe (AP_HAL::Proc, uint32_t period_us)=0
virtual void set_system_initialized ()=0
virtual bool is_system_initialized ()=0
virtual void reboot (bool hold_in_bootloader)=0
virtual void stop_clock (uint64_t time_usec)
virtual bool in_main_thread () const =0
virtual void * disable_interrupts_save (void)
virtual void restore_interrupts (void *)
virtual void call_delay_cb ()
virtual bool thread_create (AP_HAL::MemberProc proc, const char *name, uint32_t stack_size, priority_base base, int8_t priority)
Public Attributes
uint16_t _min_delay_cb_ms
Private Attributes
AP_HAL::Proc _delay_cb
bool _in_delay_callback: 1
Detailed Description
Definition at line 11 of file Scheduler.h.
Member Enumeration Documentation
priority_base
enum AP_HAL::Scheduler::priority_base
Enumerator
PRIORITY_BOOST
PRIORITY_MAIN
PRIORITY_SPI
PRIORITY_I2C
PRIORITY_CAN
PRIORITY_TIMER
PRIORITY_RCOUT
PRIORITY_LED
PRIORITY_RCIN
PRIORITY_IO
PRIORITY_UART
PRIORITY_STORAGE
PRIORITY_SCRIPTING
PRIORITY_NET
Definition at line 104 of file Scheduler.h.
Constructor & Destructor Documentation
Scheduler()
AP_HAL::Scheduler::Scheduler () inline
Definition at line 13 of file Scheduler.h.
Member Function Documentation
boost_end()
virtual void AP_HAL::Scheduler::boost_end (void) inline virtual
Reimplemented in ChibiOS::Scheduler.
Definition at line 49 of file Scheduler.h.
Referenced by AP_AHRS::update().
call_delay_cb()
void Scheduler::call_delay_cb () virtual
Definition at line 16 of file Scheduler.cpp.
Referenced by ChibiOS::Scheduler::delay(), ESP32::Scheduler::delay(), Linux::Scheduler::delay(), and HALSITL::Scheduler::delay().
delay()
virtual void AP_HAL::Scheduler::delay (uint16_t ms) pure virtual
Implemented in ChibiOS::Scheduler, Empty::Scheduler, ESP32::Scheduler, Linux::Scheduler, and HALSITL::Scheduler.
Referenced by AP_InertialSensor_L3G4200D::_accel_init(), AP_InertialSensor_LSM9DS0::_accel_init(), AP_InertialSensor_LSM9DS1::_accel_init(), Linux::CameraSensor_Mt9v117::_apply_patch(), ChibiOS::UARTDriver::_begin(), Linux::UARTDriver::_begin(), AP_Compass_HMC5843::_calibrate(), Linux::CameraSensor_Mt9v117::_config_change(), AP_InertialSensor_BMI160::_configure_accel(), AP_InertialSensor_BMI160::_configure_fifo(), AP_InertialSensor_BMI160::_configure_gyro(), AP_InertialSensor_BMI160::_configure_int1_pin(), ChibiOS::UARTDriver::_end(), Linux::UARTDriver::_end(), ChibiOS::Storage::_flash_erase_sector(), ChibiOS::Storage::_flash_write_data(), AP_InertialSensor_L3G4200D::_gyro_init(), AP_InertialSensor_LSM9DS0::_gyro_init(), AP_InertialSensor_LSM9DS1::_gyro_init(), AP_Compass_LSM303D::_hardware_init(), AP_Compass_MAG3110::_hardware_init(), AP_InertialSensor_BMI160::_hardware_init(), AP_InertialSensor_Invensense::_hardware_init(), AP_InertialSensor_Invensensev2::_hardware_init(), AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_LSM9DS1::_hardware_init(), Menu::_help(), AP_Baro_LPS2XH::_imu_i2c_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_RangeFinder_MaxsonarI2CXL::_init(), AP_InertialSensor::_init_gyro(), AP_InertialSensor_RST::_init_gyro(), Linux::CameraSensor_Mt9v117::_init_sensor(), ChibiOS::Storage::_save_backup(), Linux::CameraSensor_Mt9v117::_soft_reset(), AP_InertialSensor_BMI055::accel_init(), AP_OAPathPlanner::avoidance_thread(), AP_BoardConfig::board_init_safety(), AP_Baro_ICP201XX::boot_sequence(), AP_Baro::calibrate(), Compass_PerMotor::calibration_start(), AP_InertialSensor_SCHA63T::check_startup(), AP_RCProtocol_CRSF::decode_crsf_packet(), delay_ms(), AP_RangeFinder_BBB_PRU::detect(), RangeFinder::detect_instance(), drive(), failed(), AP_Param::flush(), AP_LoggerTest_AllTypes::flush_logger(), GCS_MAVLINK::ftp_push_replies(), GCS_MAVLINK::ftp_worker(), full_spectrum(), get_device(), AP_RangeFinder_VL53L1X::get_reading(), AP_RangeFinder_VL53L0X::get_SPAD_info(), AP_Logger_Flash_JEDEC::getSectorCount(), AP_Logger_W25N01GV::getSectorCount(), AP_InertialSensor_BMI055::gyro_init(), AP_InertialSensor_BMI088::gyro_init(), GCS_MAVLINK::handle_preflight_reboot(), GCS_MAVLINK::handle_serial_control(), AP_InertialSensor_BMI270::hardware_init(), AP_InertialSensor_Invensensev3::hardware_init(), AP_Baro_ICM20789::imu_i2c_init(), AP_Baro_ICM20789::imu_spi_init(), AP_Baro_ICM20789::init(), AP_Baro_ICP101XX::init(), AP_Baro_ICP201XX::init(), Compass::init(), AP_Compass_BMM150::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_InertialSensor_ADIS1647x::init(), AP_InertialSensor_SCHA63T::init(), AP_RangeFinder_Benewake_TFMiniPlus::init(), Linux::RCInput_RPI::init(), GCS_MAVLINK::init(), AP_BoardConfig::init(), AP_RangeFinder_TeraRangerI2C::init(), AP_Logger_W25N01GV::Init(), loop(), loop(), AP_LoggerTest::loop(), MissionTest::loop(), AP_SmartAudio::loop(), FlashTest::loop(), AP_LoggerTest_AllTypes::loop(), AP_Frsky_Backend::loop(), loop(), AP_MSP::loop(), AP_Baro_ICP201XX::mode_select(), motor_order_test(), AP_OSD::osd_thread(), AP_HAL::panic(), AP_Filesystem_Param::param_upload_parse(), AP_Invensense_AuxiliaryBusSlave::passthrough_read(), AP_Invensensev2_AuxiliaryBusSlave::passthrough_read(), AP_Invensense_AuxiliaryBusSlave::passthrough_write(), AP_Invensensev2_AuxiliaryBusSlave::passthrough_write(), AP_RangeFinder_VL53L0X::performSingleRefCalibration(), AP_Airspeed_MS4525::probe(), AP_Compass_AK09916::probe_ICM20948(), AP_RAMTRON::read(), AP_Airspeed_MS5525::read_prom(), AP_Vehicle::reboot(), AP_RangeFinder_VL53L1X::reset(), Linux::RCOutput_PCA9685::reset_all_channels(), Menu::run(), AP_IOMCU_FW::safety_update(), AP_OpticalFlow_PX4Flow::scan_buses(), AP_Networking::sendfile_check(), setup(), setup(), AP_LoggerTest::setup(), AP_LoggerTest_AllTypes::setup(), RC_UART::setup(), setup(), AP_OpticalFlow_Pixart::setup_sensor(), AP_RangeFinder_LightWareI2C::sf20_get_version(), AP_RangeFinder_LightWareI2C::sf20_send_and_expect(), AP_RangeFinder_LightWareI2C::sf20_wait_on_reply(), AP_Baro_ICP201XX::soft_reset(), AP_OpticalFlow_Pixart::srom_download(), AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), AP_Networking::startup_wait(), AP_BoardConfig::throw_error(), AP_Baro_KellerLD::transfer_with_delays(), AP_Baro_ICP201XX::wait_read(), and AP_RAMTRON::write().
delay_microseconds()
virtual void AP_HAL::Scheduler::delay_microseconds (uint16_t us) pure virtual
Implemented in ChibiOS::Scheduler, Empty::Scheduler, ESP32::Scheduler, Linux::Scheduler, and HALSITL::Scheduler.
Referenced by AP_InertialSensor_Invensensev2::_fifo_reset(), AP_InertialSensor_LSM9DS1::_fifo_reset(), AP_InertialSensor_Invensense::_fifo_reset(), ESP32::WiFiDriver::_wifi_thread(), AP_Baro_ICP201XX::boot_sequence(), ChibiOS::DeviceBus::bus_thread(), ESP32::DeviceBus::bus_thread(), AP_RCProtocol_CRSF::decode_crsf_packet(), delay_microseconds_boost(), GCS_MAVLINK::handle_preflight_reboot(), AP_InertialSensor_Invensensev3::hardware_init(), AP_Airspeed_SDP3X::init(), IS31FL3195::init(), LP5562::init(), Linux::RCInput_RPI::init_DMA(), Linux::RCInput_RPI::init_PCM(), AP_Logger::io_thread(), loop(), AP_Scheduler::loop(), AP_Hott_Telem::loop(), AP_InertialSensor_ADIS1647x::loop(), main_loop(), AP_OpticalFlow_Pixart::motion_burst(), AP_HAL::panic(), ChibiOS::RCOutput::rcout_thread(), AP_Baro_ICP201XX::read_otp_data(), AP_InertialSensor_ADIS1647x::read_reg16(), RC_UART::read_wait(), AP_OpticalFlow_Pixart::reg_read(), AP_OpticalFlow_Pixart::reg_write(), AP_InertialSensor_Invensensev3::register_read_bank(), AP_InertialSensor_Invensensev3::register_read_bank_icm456xy(), AP_InertialSensor_Invensensev3::register_write_bank(), AP_InertialSensor_Invensensev3::register_write_bank_icm456xy(), Radio_CC2500::Reset(), AP_RangeFinder_VL53L1X::reset(), AP_Param::save(), AP_Hott_Telem::send_packet(), AP_InertialSensor_Invensensev3::set_filter_and_scaling(), AP_InertialSensor_Invensensev3::set_filter_and_scaling_icm42670(), AP_OpticalFlow_Pixart::srom_download(), ChibiOS::Semaphore::take(), ESP32::Semaphore::take(), Linux::Semaphore::take(), HALSITL::Semaphore::take(), ChibiOS::RCOutput::trigger_groups(), ChibiOS::UARTDriver::uart_rx_thread(), ChibiOS::UARTDriver::uart_thread(), AP_AHRS::update(), AP_RangeFinder_HC_SR04::update(), AP_RCProtocol_DSM::update(), HALSITL::BinarySemaphore::wait(), AP_InertialSensor::wait_for_sample(), AP_Logger_Flash_JEDEC::WaitReady(), AP_Logger_W25N01GV::WaitReady(), and AP_InertialSensor_ADIS1647x::write_reg16().
delay_microseconds_boost()
virtual void AP_HAL::Scheduler::delay_microseconds_boost (uint16_t us) inline virtual
Reimplemented in ChibiOS::Scheduler.
Definition at line 30 of file Scheduler.h.
Referenced by AP_InertialSensor::wait_for_sample().
disable_interrupts_save()
virtual void * AP_HAL::Scheduler::disable_interrupts_save (void) inline virtual
Reimplemented in ChibiOS::Scheduler.
Definition at line 89 of file Scheduler.h.
Referenced by GCS_MAVLINK::do_try_send_message(), GCS_MAVLINK::find_next_bucket_to_send(), AP_HAL::PWMSource::get_pwm_avg_us(), AP_HAL::PWMSource::get_pwm_us(), AP_RPM_Pin::update(), AP_WheelEncoder_Quadrature::update(), and NavEKF2_core::UpdateFilter().
expect_delay_ms()
virtual void AP_HAL::Scheduler::expect_delay_ms (uint32_t ms) inline virtual
Reimplemented in ChibiOS::Scheduler.
Definition at line 38 of file Scheduler.h.
Referenced by ExpectDelay::ExpectDelay(), AP_Param::flush(), AP_Param::save(), and ExpectDelay::~ExpectDelay().
in_delay_callback()
virtual bool AP_HAL::Scheduler::in_delay_callback () const inline virtual
Definition at line 58 of file Scheduler.h.
Referenced by GCS_MAVLINK::do_try_send_message(), GCS::out_of_time(), and GCS_MAVLINK::update_send().
in_expected_delay()
virtual bool AP_HAL::Scheduler::in_expected_delay (void) const inline virtual
Reimplemented in ChibiOS::Scheduler.
Definition at line 44 of file Scheduler.h.
Referenced by AP_InertialSensor_Invensensev2::_accumulate(), AP_InertialSensor_Invensense::_accumulate(), AP_InertialSensor_Invensensev2::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Invensense::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Invensense::_fifo_reset(), AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), and ChibiOS::SPIDevice::do_transfer().
in_main_thread()
virtual bool AP_HAL::Scheduler::in_main_thread () const pure virtual
Implemented in ChibiOS::Scheduler, ESP32::Scheduler, Linux::Scheduler, and HALSITL::Scheduler.
Referenced by AP_Filesystem_Backend::file_op_allowed(), AP_Param::save(), AP_Logger_Backend::ShouldLog(), AP_Logger_Backend::StartNewLogOK(), AP_Networking::startup_wait(), ChibiOS::RCOutput::trigger_groups(), HALSITL::BinarySemaphore::wait(), HALSITL::SITL_State::wait_clock(), WithSemaphore::WithSemaphore(), and AP_Logger_Backend::WriteBlockCheckStartupMessages().
init()
virtual void AP_HAL::Scheduler::init () pure virtual
Implemented in ChibiOS::Scheduler, Empty::Scheduler, ESP32::Scheduler, Linux::Scheduler, and HALSITL::Scheduler.
Referenced by main_loop(), HAL_Empty::run(), HAL_ESP32::run(), HAL_Linux::run(), and HAL_SITL::run().
is_system_initialized()
virtual bool AP_HAL::Scheduler::is_system_initialized () pure virtual
Implemented in ChibiOS::Scheduler, Empty::Scheduler, ESP32::Scheduler, Linux::Scheduler, and HALSITL::Scheduler.
Referenced by ChibiOS::AnalogIn::_timer_tick(), SITL::Blimp::calculate_forces(), SITL::FlightAxis::exchange_data(), ChibiOS::RCOutput::get_output_mode_banner(), AP_Logger_Block::io_thread_alive(), AP_SmartAudio::loop(), ChibiOS::RCOutput::rcout_thread(), AP_Param::save_io_handler(), AP_Networking::startup_wait(), and SITL::Blimp::update().
reboot()
virtual void AP_HAL::Scheduler::reboot (bool hold_in_bootloader) pure virtual
Implemented in ChibiOS::Scheduler, Empty::Scheduler, ESP32::Scheduler, Linux::Scheduler, and HALSITL::Scheduler.
Referenced by GCS_MAVLINK::handle_preflight_reboot(), loop(), AP_Vehicle::reboot(), AP_IOMCU_FW::update(), and AP_OSD_ParamScreen::update_state_machine().
register_delay_callback()
void Scheduler::register_delay_callback (AP_HAL::Proc proc, uint16_t min_time_ms) virtual
Definition at line 9 of file Scheduler.cpp.
Referenced by AP_Vehicle::reboot(), and AP_Vehicle::setup().
register_io_process()
virtual void AP_HAL::Scheduler::register_io_process (AP_HAL::MemberProc) pure virtual
Implemented in ChibiOS::Scheduler, Empty::Scheduler, ESP32::Scheduler, Linux::Scheduler, and HALSITL::Scheduler.
Referenced by GCS_MAVLINK::handle_param_request_read(), GCS_MAVLINK::handle_preflight_reboot(), AP_LTM_Telem::init(), AP_SmartRTL::init(), AP_Param::load_all(), and AP_Frsky_SPort_Passthrough::setup_wfq_scheduler().
register_timer_failsafe()
virtual void AP_HAL::Scheduler::register_timer_failsafe (AP_HAL::Proc , uint32_t period_us) pure virtual
Implemented in ChibiOS::Scheduler, Empty::Scheduler, ESP32::Scheduler, Linux::Scheduler, and HALSITL::Scheduler.
register_timer_process()
virtual void AP_HAL::Scheduler::register_timer_process (AP_HAL::MemberProc) pure virtual
Implemented in ChibiOS::Scheduler, Empty::Scheduler, ESP32::Scheduler, Linux::Scheduler, and HALSITL::Scheduler.
Referenced by AnalogIn_ADS1115::init(), HALSITL::RCOutput::init(), AP_ToneAlarm::init(), AP_Camera_Backend::setup_feedback_callback(), AP_InertialSensor_NONE::start(), AP_Button::update(), and GCS::update_passthru().
restore_interrupts()
virtual void AP_HAL::Scheduler::restore_interrupts (void *) inline virtual
Reimplemented in ChibiOS::Scheduler.
Definition at line 94 of file Scheduler.h.
Referenced by GCS_MAVLINK::do_try_send_message(), GCS_MAVLINK::find_next_bucket_to_send(), AP_HAL::PWMSource::get_pwm_avg_us(), AP_HAL::PWMSource::get_pwm_us(), AP_RPM_Pin::update(), AP_WheelEncoder_Quadrature::update(), and NavEKF2_core::UpdateFilter().
set_system_initialized()
virtual void AP_HAL::Scheduler::set_system_initialized () pure virtual
Implemented in ChibiOS::Scheduler, Empty::Scheduler, ESP32::Scheduler, Linux::Scheduler, and HALSITL::Scheduler.
Referenced by main_loop(), HAL_Empty::run(), HAL_Linux::run(), and HAL_SITL::run().
stop_clock()
virtual void AP_HAL::Scheduler::stop_clock (uint64_t time_usec) inline virtual
optional function to stop clock at a given time, used by log replay
Reimplemented in Linux::Scheduler, and HALSITL::Scheduler.
Definition at line 78 of file Scheduler.h.
Referenced by HALSITL::SITL_State::_fdm_input_local(), HALSITL::SITL_State::_sitl_setup(), HALSITL::Scheduler::delay_microseconds(), delay_ms(), loop(), setup(), and setup().
thread_create()
virtual bool AP_HAL::Scheduler::thread_create (AP_HAL::MemberProc proc, const char * name, uint32_t stack_size, priority_base base, int8_t priority) inline virtual
Reimplemented in ChibiOS::Scheduler, ESP32::Scheduler, Linux::Scheduler, and HALSITL::Scheduler.
Definition at line 124 of file Scheduler.h.
Referenced by SITL::FlightAxis::FlightAxis(), GCS_MAVLINK::ftp_init(), AP_Mount_Backend::init(), AP_MSP::init(), AP_OSD::init(), AP_SmartAudio::init(), Linux::GPIO_Sysfs::init(), AP_Hott_Telem::init(), AP_Frsky_Backend::init_serial_port(), AP_Networking::sendfile(), BinarySemTest::setup(), AP_InertialSensor_ADIS1647x::start(), AP_Logger::start_io_thread(), and AP_OAPathPlanner::start_thread().
Member Data Documentation
_delay_cb
AP_HAL::Proc AP_HAL::Scheduler::_delay_cb private
Definition at line 131 of file Scheduler.h.
Referenced by call_delay_cb(), and register_delay_callback().
_in_delay_callback
bool AP_HAL::Scheduler::_in_delay_callback private
Definition at line 132 of file Scheduler.h.
Referenced by call_delay_cb(), and in_delay_callback().
_min_delay_cb_ms
uint16_t AP_HAL::Scheduler::_min_delay_cb_ms
Definition at line 98 of file Scheduler.h.
Referenced by ChibiOS::Scheduler::delay(), ESP32::Scheduler::delay(), Linux::Scheduler::delay(), HALSITL::Scheduler::delay(), and register_delay_callback().
The documentation for this class was generated from the following files:
libraries/AP_HAL/Scheduler.h
libraries/AP_HAL/Scheduler.cpp