APM:Libraries: AP_RCTelemetry Class Reference
AP_RCTelemetry Class Reference abstract
#include <AP_RCTelemetry.h>
Public Member Functions
AP_RCTelemetry (uint8_t time_slots)
virtual ~AP_RCTelemetry ()
CLASS_NO_COPY (AP_RCTelemetry)
virtual void queue_message (MAV_SEVERITY severity, const char *text)
void enable_scheduler_entry (const uint8_t slot)
void disable_scheduler_entry (const uint8_t slot)
void set_scheduler_entry_min_period (const uint8_t slot, const uint32_t min_period_ms)
bool is_scheduler_entry_enabled (const uint8_t slot) const
virtual void reset_scheduler_entry_min_periods ()
uint32_t sensor_status_flags () const
uint16_t get_avg_packet_rate () const
uint16_t get_max_packet_rate () const
Protected Member Functions
uint8_t run_wfq_scheduler (const bool use_shaper=true)
bool process_scheduler_entry (const uint8_t slot)
void set_scheduler_entry (uint8_t slot, uint32_t weight, uint32_t min_period_ms)
void add_scheduler_entry (uint32_t weight, uint32_t min_period_ms)
virtual bool init (void)
Protected Attributes
uint8_t _time_slots
struct {
uint32_t last_poll_timer
uint32_t avg_packet_counter
uint32_t packet_timer [TELEM_TIME_SLOT_MAX]
uint32_t packet_weight [TELEM_TIME_SLOT_MAX]
uint32_t packet_min_period [TELEM_TIME_SLOT_MAX]
uint16_t avg_packet_rate
uint16_t max_packet_rate
} _scheduler
struct {
HAL_Semaphore sem
ObjectBuffer< mavlink_statustext_t > queue {TELEM_PAYLOAD_STATUS_CAPACITY}
mavlink_statustext_t next
bool available
} _statustext
Private Member Functions
virtual void setup_wfq_scheduler ()=0
virtual bool get_next_msg_chunk (void)
virtual bool is_packet_ready (uint8_t idx, bool queue_empty)
virtual void process_packet (uint8_t idx)=0
virtual void adjust_packet_weight (bool queue_empty)
bool check_scheduler_entry_time_constraints (const uint32_t now, uint8_t slot, const bool use_shaper) const
void update_avg_packet_rate ()
void update_max_packet_rate ()
void check_sensor_status_flags (void)
void check_ekf_status (void)
Private Attributes
uint32_t check_sensor_status_timer
uint32_t check_ekf_status_timer
uint32_t _disabled_scheduler_entries_bitmask
Detailed Description
Definition at line 28 of file AP_RCTelemetry.h.
Constructor & Destructor Documentation
AP_RCTelemetry()
AP_RCTelemetry::AP_RCTelemetry (uint8_t time_slots) inline
Definition at line 30 of file AP_RCTelemetry.h.
~AP_RCTelemetry()
virtual AP_RCTelemetry::~AP_RCTelemetry () inline virtual
Definition at line 31 of file AP_RCTelemetry.h.
Member Function Documentation
add_scheduler_entry()
void AP_RCTelemetry::add_scheduler_entry (uint32_t weight, uint32_t min_period_ms) inline protected
Definition at line 93 of file AP_RCTelemetry.h.
Referenced by AP_Spektrum_Telem::setup_wfq_scheduler().
adjust_packet_weight()
virtual void AP_RCTelemetry::adjust_packet_weight (bool queue_empty) inline private virtual
Reimplemented in AP_Frsky_SPort_Passthrough, AP_MSP_Telem_Backend, and AP_Spektrum_Telem.
Definition at line 135 of file AP_RCTelemetry.h.
Referenced by run_wfq_scheduler().
check_ekf_status()
void AP_RCTelemetry::check_ekf_status (void) private
Definition at line 242 of file AP_RCTelemetry.cpp.
Referenced by run_wfq_scheduler().
check_scheduler_entry_time_constraints()
bool AP_RCTelemetry::check_scheduler_entry_time_constraints (const uint32_t now, uint8_t slot, const bool use_shaper) const inline private
Definition at line 136 of file AP_RCTelemetry.h.
Referenced by run_wfq_scheduler().
check_sensor_status_flags()
void AP_RCTelemetry::check_sensor_status_flags (void) private
Definition at line 191 of file AP_RCTelemetry.cpp.
Referenced by run_wfq_scheduler().
CLASS_NO_COPY()
AP_RCTelemetry::CLASS_NO_COPY (AP_RCTelemetry)
disable_scheduler_entry()
void AP_RCTelemetry::disable_scheduler_entry (const uint8_t slot) inline
Definition at line 46 of file AP_RCTelemetry.h.
enable_scheduler_entry()
void AP_RCTelemetry::enable_scheduler_entry (const uint8_t slot) inline
Definition at line 40 of file AP_RCTelemetry.h.
get_avg_packet_rate()
uint16_t AP_RCTelemetry::get_avg_packet_rate () const inline
Definition at line 73 of file AP_RCTelemetry.h.
get_max_packet_rate()
uint16_t AP_RCTelemetry::get_max_packet_rate () const inline
Definition at line 76 of file AP_RCTelemetry.h.
get_next_msg_chunk()
virtual bool AP_RCTelemetry::get_next_msg_chunk (void) inline private virtual
Reimplemented in AP_Frsky_SPort_Passthrough, AP_MSP_Telem_Backend, and AP_Spektrum_Telem.
Definition at line 132 of file AP_RCTelemetry.h.
init()
bool AP_RCTelemetry::init (void) protected virtual
Reimplemented in AP_Frsky_SPort_Passthrough, AP_MSP_Telem_Backend, and AP_Spektrum_Telem.
Definition at line 40 of file AP_RCTelemetry.cpp.
Referenced by AP_Frsky_SPort_Passthrough::init(), AP_MSP_Telem_Backend::init(), and AP_Spektrum_Telem::init().
is_packet_ready()
virtual bool AP_RCTelemetry::is_packet_ready (uint8_t idx, bool queue_empty) inline private virtual
Reimplemented in AP_Frsky_SPort_Passthrough, AP_MSP_Telem_Backend, and AP_Spektrum_Telem.
Definition at line 133 of file AP_RCTelemetry.h.
Referenced by process_scheduler_entry(), and run_wfq_scheduler().
is_scheduler_entry_enabled()
bool AP_RCTelemetry::is_scheduler_entry_enabled (const uint8_t slot) const inline
Definition at line 59 of file AP_RCTelemetry.h.
Referenced by process_scheduler_entry(), and run_wfq_scheduler().
process_packet()
virtual void AP_RCTelemetry::process_packet (uint8_t idx) private pure virtual
Implemented in AP_Frsky_SPort_Passthrough, AP_MSP_Telem_Backend, and AP_Spektrum_Telem.
Referenced by process_scheduler_entry(), and run_wfq_scheduler().
process_scheduler_entry()
bool AP_RCTelemetry::process_scheduler_entry (const uint8_t slot) protected
Definition at line 150 of file AP_RCTelemetry.cpp.
Referenced by AP_Frsky_SPort_Passthrough::get_telem_data().
queue_message()
void AP_RCTelemetry::queue_message (MAV_SEVERITY severity, const char * text) virtual
Definition at line 174 of file AP_RCTelemetry.cpp.
Referenced by check_ekf_status(), check_sensor_status_flags(), init(), AP_Frsky_SPort_Passthrough::queue_text_message(), and GCS::send_textv().
reset_scheduler_entry_min_periods()
virtual void AP_RCTelemetry::reset_scheduler_entry_min_periods () inline virtual
Definition at line 66 of file AP_RCTelemetry.h.
run_wfq_scheduler()
uint8_t AP_RCTelemetry::run_wfq_scheduler (const bool use_shaper = true) protected
Definition at line 89 of file AP_RCTelemetry.cpp.
Referenced by AP_Spektrum_Telem::_get_telem_data(), AP_Frsky_SPort_Passthrough::get_telem_data(), AP_MSP_Telem_Backend::process_outgoing_data(), and AP_Frsky_SPort_Passthrough::send().
sensor_status_flags()
uint32_t AP_RCTelemetry::sensor_status_flags () const
Definition at line 281 of file AP_RCTelemetry.cpp.
Referenced by check_sensor_status_flags().
set_scheduler_entry()
void AP_RCTelemetry::set_scheduler_entry (uint8_t slot, uint32_t weight, uint32_t min_period_ms) inline protected
Definition at line 85 of file AP_RCTelemetry.h.
Referenced by add_scheduler_entry(), AP_Frsky_SPort_Passthrough::setup_wfq_scheduler(), and AP_MSP_Telem_Backend::setup_wfq_scheduler().
set_scheduler_entry_min_period()
void AP_RCTelemetry::set_scheduler_entry_min_period (const uint8_t slot, const uint32_t min_period_ms) inline
Definition at line 52 of file AP_RCTelemetry.h.
setup_wfq_scheduler()
virtual void AP_RCTelemetry::setup_wfq_scheduler () private pure virtual
Implemented in AP_Frsky_SPort_Passthrough, AP_MSP_Telem_Backend, and AP_Spektrum_Telem.
Referenced by init().
update_avg_packet_rate()
void AP_RCTelemetry::update_avg_packet_rate () private
Definition at line 59 of file AP_RCTelemetry.cpp.
Referenced by run_wfq_scheduler().
update_max_packet_rate()
void AP_RCTelemetry::update_max_packet_rate () inline private
Definition at line 144 of file AP_RCTelemetry.h.
Referenced by run_wfq_scheduler().
Member Data Documentation
_disabled_scheduler_entries_bitmask
uint32_t AP_RCTelemetry::_disabled_scheduler_entries_bitmask private
Definition at line 128 of file AP_RCTelemetry.h.
Referenced by disable_scheduler_entry(), enable_scheduler_entry(), and is_scheduler_entry_enabled().
[struct]
struct { ... } AP_RCTelemetry::_scheduler
Referenced by AP_Frsky_SPort_Passthrough::adjust_packet_weight(), AP_Spektrum_Telem::adjust_packet_weight(), check_scheduler_entry_time_constraints(), get_avg_packet_rate(), get_max_packet_rate(), AP_Frsky_SPort_Passthrough::get_next_msg_chunk(), AP_Frsky_SPort_Passthrough::process_packet(), AP_Spektrum_Telem::repeat_msg_chunk(), run_wfq_scheduler(), set_scheduler_entry(), set_scheduler_entry_min_period(), update_avg_packet_rate(), and update_max_packet_rate().
[struct]
struct { ... } AP_RCTelemetry::_statustext
Referenced by AP_Frsky_SPort_Passthrough::get_next_msg_chunk(), AP_Spektrum_Telem::get_next_msg_chunk(), process_scheduler_entry(), queue_message(), and run_wfq_scheduler().
_time_slots
uint8_t AP_RCTelemetry::_time_slots protected
Definition at line 102 of file AP_RCTelemetry.h.
Referenced by add_scheduler_entry(), and run_wfq_scheduler().
available
bool AP_RCTelemetry::available
Definition at line 122 of file AP_RCTelemetry.h.
avg_packet_counter
uint32_t AP_RCTelemetry::avg_packet_counter
Definition at line 107 of file AP_RCTelemetry.h.
avg_packet_rate
uint16_t AP_RCTelemetry::avg_packet_rate
Definition at line 111 of file AP_RCTelemetry.h.
check_ekf_status_timer
uint32_t AP_RCTelemetry::check_ekf_status_timer private
Definition at line 127 of file AP_RCTelemetry.h.
Referenced by check_ekf_status().
check_sensor_status_timer
uint32_t AP_RCTelemetry::check_sensor_status_timer private
Definition at line 126 of file AP_RCTelemetry.h.
Referenced by check_sensor_status_flags().
last_poll_timer
uint32_t AP_RCTelemetry::last_poll_timer
Definition at line 106 of file AP_RCTelemetry.h.
max_packet_rate
uint16_t AP_RCTelemetry::max_packet_rate
Definition at line 112 of file AP_RCTelemetry.h.
next
mavlink_statustext_t AP_RCTelemetry::next
Definition at line 121 of file AP_RCTelemetry.h.
packet_min_period
uint32_t AP_RCTelemetry::packet_min_period[TELEM_TIME_SLOT_MAX]
Definition at line 110 of file AP_RCTelemetry.h.
packet_timer
uint32_t AP_RCTelemetry::packet_timer[TELEM_TIME_SLOT_MAX]
Definition at line 108 of file AP_RCTelemetry.h.
packet_weight
uint32_t AP_RCTelemetry::packet_weight[TELEM_TIME_SLOT_MAX]
Definition at line 109 of file AP_RCTelemetry.h.
queue
ObjectBuffer<mavlink_statustext_t> AP_RCTelemetry::queue {TELEM_PAYLOAD_STATUS_CAPACITY}
Definition at line 120 of file AP_RCTelemetry.h.
sem
HAL_Semaphore AP_RCTelemetry::sem
Definition at line 119 of file AP_RCTelemetry.h.
The documentation for this class was generated from the following files:
libraries/AP_RCTelemetry/AP_RCTelemetry.h
libraries/AP_RCTelemetry/AP_RCTelemetry.cpp