APM:Libraries: AP_HAL::SPIDeviceManager Class Reference
AP_HAL::SPIDeviceManager Class Reference
#include <SPIDevice.h>
Public Member Functions
virtual OwnPtr< SPIDevice > get_device (const char *name)
virtual uint8_t get_count ()
virtual const char * get_device_name (uint8_t idx)
virtual void set_register_rw_callback (const char *name, AP_HAL::Device::RegisterRWCb cb)
Detailed Description
Definition at line 69 of file SPIDevice.h.
Member Function Documentation
get_count()
virtual uint8_t AP_HAL::SPIDeviceManager::get_count () inline virtual
Reimplemented in Linux::SPIDeviceManager.
Definition at line 77 of file SPIDevice.h.
Referenced by get_device().
get_device()
virtual OwnPtr< SPIDevice > AP_HAL::SPIDeviceManager::get_device (const char * name) inline virtual
Reimplemented in ChibiOS::SPIDeviceManager, Empty::SPIDeviceManager, ESP32::SPIDeviceManager, Linux::SPIDeviceManager, and HALSITL::SPIDeviceManager.
Definition at line 71 of file SPIDevice.h.
Referenced by Linux::SPIUARTDriver::_begin(), AP_OpticalFlow_Pixart::AP_OpticalFlow_Pixart(), AP_InertialSensor::detect_backends(), get_device(), GCS_MAVLINK::handle_device_op_read(), GCS_MAVLINK::handle_device_op_write(), Linux::RCOutput_AeroIO::init(), AP_Baro::init(), AP_RAMTRON::init(), AP_Logger_Flash_JEDEC::Init(), AP_Logger_W25N01GV::Init(), NavigatorLED::init(), AP_OSD::init_backend(), Compass::probe_i2c_spi_compasses(), sdcard_init(), and setup().
get_device_name()
virtual const char * AP_HAL::SPIDeviceManager::get_device_name (uint8_t idx) inline virtual
Reimplemented in Linux::SPIDeviceManager.
Definition at line 80 of file SPIDevice.h.
Referenced by get_device().
set_register_rw_callback()
virtual void AP_HAL::SPIDeviceManager::set_register_rw_callback (const char * name, AP_HAL::Device::RegisterRWCb cb) inline virtual
Reimplemented in ChibiOS::SPIDeviceManager.
Definition at line 82 of file SPIDevice.h.
The documentation for this class was generated from the following file:
libraries/AP_HAL/SPIDevice.h