APM:Libraries: SITL::VectorNav Class Reference
SITL::VectorNav Class Reference
#include <SIM_VectorNav.h>
Public Member Functions
VectorNav ()
void update (void)
Public Member Functions inherited from SITL::SerialDevice
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Private Member Functions
void send_packet1 ()
void send_packet2 ()
void nmea_printf (const char *fmt,...)
Private Attributes
uint32_t last_pkt1_us
uint32_t last_pkt2_us
uint32_t last_type_us
Additional Inherited Members
Protected Member Functions inherited from SITL::SerialDevice
bool init_sitl_pointer () WARN_IF_UNUSED
Protected Attributes inherited from SITL::SerialDevice
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Detailed Description
Definition at line 35 of file SIM_VectorNav.h.
Constructor & Destructor Documentation
VectorNav()
VectorNav::VectorNav ()
Definition at line 27 of file SIM_VectorNav.cpp.
Member Function Documentation
nmea_printf()
void VectorNav::nmea_printf (const char * fmt, ...) private
Definition at line 183 of file SIM_VectorNav.cpp.
Referenced by update().
send_packet1()
void VectorNav::send_packet1 (void) private
Definition at line 83 of file SIM_VectorNav.cpp.
Referenced by update().
send_packet2()
void VectorNav::send_packet2 (void) private
Definition at line 146 of file SIM_VectorNav.cpp.
Referenced by update().
update()
void VectorNav::update (void)
Definition at line 199 of file SIM_VectorNav.cpp.
Referenced by HALSITL::SITL_State_Common::sim_update().
Member Data Documentation
last_pkt1_us
uint32_t SITL::VectorNav::last_pkt1_us private
Definition at line 44 of file SIM_VectorNav.h.
Referenced by update().
last_pkt2_us
uint32_t SITL::VectorNav::last_pkt2_us private
Definition at line 45 of file SIM_VectorNav.h.
Referenced by update().
last_type_us
uint32_t SITL::VectorNav::last_type_us private
Definition at line 46 of file SIM_VectorNav.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_VectorNav.h
libraries/SITL/SIM_VectorNav.cpp