APM:Libraries: LowPassFilter2p< T > Class Template Reference
LowPassFilter2p< T > Class Template Reference
#include <LowPassFilter2p.h>
Public Member Functions
LowPassFilter2p ()
LowPassFilter2p (float sample_freq, float cutoff_freq)
void set_cutoff_frequency (float sample_freq, float cutoff_freq)
float get_cutoff_freq (void) const
float get_sample_freq (void) const
T apply (const T &sample)
void reset (void)
void reset (const T &value)
CLASS_NO_COPY (LowPassFilter2p)
Protected Attributes
struct DigitalBiquadFilter< T >::biquad_params _params
Private Attributes
DigitalBiquadFilter< T > _filter
Detailed Description
template<class T>
class LowPassFilter2p< T >
Definition at line 54 of file LowPassFilter2p.h.
Constructor & Destructor Documentation
LowPassFilter2p() [1/2]
template<class T > LowPassFilter2p< T >::LowPassFilter2p ()
Definition at line 75 of file LowPassFilter2p.cpp.
LowPassFilter2p() [2/2]
template<class T > LowPassFilter2p< T >::LowPassFilter2p (float sample_freq, float cutoff_freq)
Definition at line 81 of file LowPassFilter2p.cpp.
Member Function Documentation
apply()
template<class T > T LowPassFilter2p< T >::apply (const T & sample)
Definition at line 104 of file LowPassFilter2p.cpp.
Referenced by AP_InertialSensor_Invensensev2::_accumulate(), AP_InertialSensor_Invensense::_accumulate(), AP_InertialSensor_Invensensev2::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Invensense::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_notify_new_delta_velocity(), AP_InertialSensor_LSM9DS0::_read_data_transaction_a(), AP_InertialSensor_Invensensev3::accumulate_samples(), AP_InertialSensor_Backend::apply_gyro_filters(), apply_to_filter_under_test(), and loop().
CLASS_NO_COPY()
template<class T > LowPassFilter2p< T >::CLASS_NO_COPY (LowPassFilter2p< T >)
get_cutoff_freq()
template<class T > float LowPassFilter2p< T >::get_cutoff_freq (void) const
Definition at line 94 of file LowPassFilter2p.cpp.
get_sample_freq()
template<class T > float LowPassFilter2p< T >::get_sample_freq (void) const
Definition at line 99 of file LowPassFilter2p.cpp.
reset() [1/2]
template<class T > void LowPassFilter2p< T >::reset (const T & value)
Definition at line 114 of file LowPassFilter2p.cpp.
reset() [2/2]
template<class T > void LowPassFilter2p< T >::reset (void)
Definition at line 109 of file LowPassFilter2p.cpp.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_notify_new_delta_velocity(), AP_InertialSensor_Backend::apply_gyro_filters(), and reset_all().
set_cutoff_frequency()
template<class T > void LowPassFilter2p< T >::set_cutoff_frequency (float sample_freq, float cutoff_freq)
Definition at line 88 of file LowPassFilter2p.cpp.
Referenced by AP_InertialSensor_L3G4200D::_set_filter_frequency(), setup(), AP_InertialSensor_Backend::update_accel(), and AP_InertialSensor_Backend::update_gyro().
Member Data Documentation
_filter
template<class T > DigitalBiquadFilter<T> LowPassFilter2p< T >::_filter private
Definition at line 74 of file LowPassFilter2p.h.
_params
template<class T > struct DigitalBiquadFilter< T >::biquad_params LowPassFilter2p< T >::_params protected
Definition at line 71 of file LowPassFilter2p.h.
The documentation for this class was generated from the following files:
libraries/Filter/LowPassFilter2p.h
libraries/Filter/LowPassFilter2p.cpp