APM:Libraries: AP_DAL_Compass Class Reference
AP_DAL_Compass Class Reference
#include <AP_DAL_Compass.h>
Public Member Functions
bool use_for_yaw (uint8_t i) const
bool healthy (uint8_t i) const
const Vector3f & get_offsets (uint8_t i) const
bool have_scale_factor (uint8_t i) const
bool auto_declination_enabled () const
uint8_t get_count () const
float get_declination () const
bool available () const
uint8_t get_num_enabled (void) const
bool learn_offsets_enabled () const
uint32_t last_update_usec (uint8_t i) const
const Vector3f & get_field (uint8_t i) const
Return the current field as a Vector3f in milligauss.
bool consistent () const
uint8_t get_first_usable () const
AP_DAL_Compass ()
void start_frame ()
void handle_message (const log_RMGH &msg)
void handle_message (const log_RMGI &msg)
Private Attributes
struct log_RMGH _RMGH
struct log_RMGI _RMGI [COMPASS_MAX_INSTANCES]
Detailed Description
Definition at line 7 of file AP_DAL_Compass.h.
Constructor & Destructor Documentation
AP_DAL_Compass()
AP_DAL_Compass::AP_DAL_Compass ()
Definition at line 8 of file AP_DAL_Compass.cpp.
Member Function Documentation
auto_declination_enabled()
bool AP_DAL_Compass::auto_declination_enabled () const inline
Definition at line 27 of file AP_DAL_Compass.h.
available()
bool AP_DAL_Compass::available () const inline
Definition at line 39 of file AP_DAL_Compass.h.
consistent()
bool AP_DAL_Compass::consistent () const inline
Definition at line 56 of file AP_DAL_Compass.h.
get_count()
uint8_t AP_DAL_Compass::get_count () const inline
Definition at line 31 of file AP_DAL_Compass.h.
get_declination()
float AP_DAL_Compass::get_declination () const inline
Definition at line 35 of file AP_DAL_Compass.h.
Referenced by NavEKF2_core::MagDeclination(), and NavEKF3_core::MagDeclination().
get_field()
const Vector3f & AP_DAL_Compass::get_field (uint8_t i) const inline
Return the current field as a Vector3f in milligauss.
Definition at line 53 of file AP_DAL_Compass.h.
get_first_usable()
uint8_t AP_DAL_Compass::get_first_usable () const inline
Definition at line 59 of file AP_DAL_Compass.h.
Referenced by NavEKF2_core::InitialiseVariablesMag(), and NavEKF3_core::InitialiseVariablesMag().
get_num_enabled()
uint8_t AP_DAL_Compass::get_num_enabled (void) const inline
Definition at line 44 of file AP_DAL_Compass.h.
Referenced by NavEKF3_core::EKFGSF_resetMainFilterYaw(), and AP_NavEKF_Source::pre_arm_check().
get_offsets()
const Vector3f & AP_DAL_Compass::get_offsets (uint8_t i) const inline
Definition at line 19 of file AP_DAL_Compass.h.
handle_message() [1/2]
void AP_DAL_Compass::handle_message (const log_RMGH & msg) inline
Definition at line 66 of file AP_DAL_Compass.h.
Referenced by AP_DAL::handle_message(), and AP_DAL::handle_message().
handle_message() [2/2]
void AP_DAL_Compass::handle_message (const log_RMGI & msg) inline
Definition at line 69 of file AP_DAL_Compass.h.
have_scale_factor()
bool AP_DAL_Compass::have_scale_factor (uint8_t i) const inline
Definition at line 23 of file AP_DAL_Compass.h.
healthy()
bool AP_DAL_Compass::healthy (uint8_t i) const inline
Definition at line 15 of file AP_DAL_Compass.h.
last_update_usec()
uint32_t AP_DAL_Compass::last_update_usec (uint8_t i) const inline
Definition at line 50 of file AP_DAL_Compass.h.
learn_offsets_enabled()
bool AP_DAL_Compass::learn_offsets_enabled () const inline
Definition at line 47 of file AP_DAL_Compass.h.
start_frame()
void AP_DAL_Compass::start_frame ()
Definition at line 15 of file AP_DAL_Compass.cpp.
Referenced by AP_DAL::start_frame().
use_for_yaw()
bool AP_DAL_Compass::use_for_yaw (uint8_t i) const inline
Definition at line 11 of file AP_DAL_Compass.h.
Referenced by NavEKF2_core::use_compass().
Member Data Documentation
_RMGH
struct log_RMGH AP_DAL_Compass::_RMGH private
Definition at line 75 of file AP_DAL_Compass.h.
Referenced by auto_declination_enabled(), available(), consistent(), get_count(), get_declination(), get_first_usable(), get_num_enabled(), handle_message(), learn_offsets_enabled(), and start_frame().
_RMGI
struct log_RMGI AP_DAL_Compass::_RMGI[COMPASS_MAX_INSTANCES] private
Definition at line 76 of file AP_DAL_Compass.h.
Referenced by AP_DAL_Compass(), get_field(), get_offsets(), handle_message(), have_scale_factor(), healthy(), last_update_usec(), start_frame(), and use_for_yaw().
The documentation for this class was generated from the following files:
libraries/AP_DAL/AP_DAL_Compass.h
libraries/AP_DAL/AP_DAL_Compass.cpp