APM:Libraries: AP_RangeFinder_LightWareI2C Class Reference
AP_RangeFinder_LightWareI2C Class Reference
#include <AP_RangeFinder_LightWareI2C.h>
Public Member Functions
void update (void) override
Public Member Functions inherited from AP_RangeFinder_Backend
AP_RangeFinder_Backend (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params)
virtual ~AP_RangeFinder_Backend (void)
virtual void init_serial (uint8_t serial_instance)
virtual void handle_msg (const mavlink_message_t &msg)
enum Rotation orientation () const
float distance () const
uint16_t distance_cm () const
int8_t signal_quality_pct () const WARN_IF_UNUSED
uint16_t voltage_mv () const
virtual int16_t max_distance_cm () const
virtual int16_t min_distance_cm () const
int16_t ground_clearance_cm () const
MAV_DISTANCE_SENSOR get_mav_distance_sensor_type () const
RangeFinder::Status status () const
RangeFinder::Type type () const
bool has_data () const
uint8_t range_valid_count () const
const Vector3f & get_pos_offset () const
uint32_t last_reading_ms () const
virtual bool get_temp (float &temp) const
RangeFinder::Type allocated_type () const
Static Public Member Functions
static AP_RangeFinder_Backend * detect (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
Protected Member Functions
virtual MAV_DISTANCE_SENSOR _get_mav_distance_sensor_type () const override
Protected Member Functions inherited from AP_RangeFinder_Backend
void update_status (RangeFinder::RangeFinder_State &state_arg) const
void update_status ()
void set_status (RangeFinder::Status status)
Private Member Functions
AP_RangeFinder_LightWareI2C (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
bool write_bytes (uint8_t *write_buf_u8, uint32_t len_u8)
void sf20_disable_address_tagging ()
bool sf20_send_and_expect (const char *send, const char *expected_reply)
bool sf20_set_lost_signal_confirmations ()
void sf20_get_version (const char *send_msg, const char *reply_prefix, char reply[5])
bool sf20_wait_on_reply (uint8_t *rx_two_bytes)
bool init ()
bool legacy_init ()
bool sf20_init ()
void sf20_init_streamRecovery ()
void legacy_timer ()
void sf20_timer ()
bool legacy_get_reading (float &reading_m)
bool sf20_get_reading (float &reading_m)
bool sf20_parse_stream (uint8_t *stream_buf, size_t *p_num_processed_chars, const char *string_identifier, uint16_t &val)
void data_log (uint16_t *val)
Private Attributes
uint16_t sf20_stream_val [NUM_SF20_DATA_STREAMS]
int currentStreamSequenceIndex = 0
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
Additional Inherited Members
Static Protected Member Functions inherited from AP_RangeFinder_Backend
static void set_status (RangeFinder::RangeFinder_State &state_arg, RangeFinder::Status status)
Protected Attributes inherited from AP_RangeFinder_Backend
RangeFinder::RangeFinder_State & state
AP_RangeFinder_Params & params
HAL_Semaphore _sem
RangeFinder::Type _backend_type
Detailed Description
Definition at line 14 of file AP_RangeFinder_LightWareI2C.h.
Constructor & Destructor Documentation
AP_RangeFinder_LightWareI2C()
AP_RangeFinder_LightWareI2C::AP_RangeFinder_LightWareI2C (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev) private
Definition at line 64 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by detect().
Member Function Documentation
_get_mav_distance_sensor_type()
virtual MAV_DISTANCE_SENSOR AP_RangeFinder_LightWareI2C::_get_mav_distance_sensor_type () const inline override protected virtual
Implements AP_RangeFinder_Backend.
Definition at line 28 of file AP_RangeFinder_LightWareI2C.h.
data_log()
void AP_RangeFinder_LightWareI2C::data_log (uint16_t * val) private
detect()
AP_RangeFinder_Backend * AP_RangeFinder_LightWareI2C::detect (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev) static
Definition at line 75 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by RangeFinder::detect_instance().
init()
bool AP_RangeFinder_LightWareI2C::init () private
Definition at line 191 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by detect().
legacy_get_reading()
bool AP_RangeFinder_LightWareI2C::legacy_get_reading (float & reading_m) private
Definition at line 343 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by legacy_timer().
legacy_init()
bool AP_RangeFinder_LightWareI2C::legacy_init () private
Definition at line 208 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by init().
legacy_timer()
void AP_RangeFinder_LightWareI2C::legacy_timer (void) private
Definition at line 466 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by legacy_init().
sf20_disable_address_tagging()
void AP_RangeFinder_LightWareI2C::sf20_disable_address_tagging () private
Disables "address tagging" in the sf20 response packets.
Definition at line 110 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by sf20_init().
sf20_get_reading()
bool AP_RangeFinder_LightWareI2C::sf20_get_reading (float & reading_m) private
Definition at line 364 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by sf20_timer().
sf20_get_version()
void AP_RangeFinder_LightWareI2C::sf20_get_version (const char * send_msg, const char * reply_prefix, char reply[5]) private
Definition at line 158 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by sf20_init().
sf20_init()
bool AP_RangeFinder_LightWareI2C::sf20_init () private
Definition at line 240 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by init().
sf20_init_streamRecovery()
void AP_RangeFinder_LightWareI2C::sf20_init_streamRecovery () private
sf20_parse_stream()
bool AP_RangeFinder_LightWareI2C::sf20_parse_stream (uint8_t * stream_buf, size_t * p_num_processed_chars, const char * string_identifier, uint16_t & val) private
Definition at line 400 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by sf20_get_reading().
sf20_send_and_expect()
bool AP_RangeFinder_LightWareI2C::sf20_send_and_expect (const char * send, const char * expected_reply) private
Definition at line 118 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by sf20_disable_address_tagging(), and sf20_init().
sf20_set_lost_signal_confirmations()
bool AP_RangeFinder_LightWareI2C::sf20_set_lost_signal_confirmations () private
sf20_timer()
void AP_RangeFinder_LightWareI2C::sf20_timer (void) private
Definition at line 476 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by sf20_init().
sf20_wait_on_reply()
bool AP_RangeFinder_LightWareI2C::sf20_wait_on_reply (uint8_t * rx_two_bytes) private
Definition at line 487 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by sf20_get_version(), sf20_init(), and sf20_send_and_expect().
update()
void AP_RangeFinder_LightWareI2C::update (void) override virtual
Implements AP_RangeFinder_Backend.
Definition at line 461 of file AP_RangeFinder_LightWareI2C.cpp.
write_bytes()
bool AP_RangeFinder_LightWareI2C::write_bytes (uint8_t * write_buf_u8, uint32_t len_u8) private
Wrapper function over #transfer() to write a sequence of bytes to device. No values are read.
Definition at line 102 of file AP_RangeFinder_LightWareI2C.cpp.
Referenced by sf20_get_reading(), sf20_get_version(), sf20_init(), and sf20_send_and_expect().
Member Data Documentation
_dev
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_RangeFinder_LightWareI2C::_dev private
Definition at line 64 of file AP_RangeFinder_LightWareI2C.h.
Referenced by detect(), legacy_get_reading(), legacy_init(), sf20_get_reading(), sf20_get_version(), sf20_init(), sf20_send_and_expect(), sf20_wait_on_reply(), and write_bytes().
currentStreamSequenceIndex
int AP_RangeFinder_LightWareI2C::currentStreamSequenceIndex = 0 private
Definition at line 36 of file AP_RangeFinder_LightWareI2C.h.
Referenced by sf20_get_reading().
sf20_stream_val
uint16_t AP_RangeFinder_LightWareI2C::sf20_stream_val[NUM_SF20_DATA_STREAMS] private
Definition at line 35 of file AP_RangeFinder_LightWareI2C.h.
Referenced by sf20_get_reading().
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder_LightWareI2C.h
libraries/AP_RangeFinder/AP_RangeFinder_LightWareI2C.cpp