APM:Libraries: AP_OSD_Backend Class Reference
AP_OSD_Backend Class Reference abstract
#include <AP_OSD_Backend.h>
Public Member Functions
AP_OSD_Backend (AP_OSD &osd)
virtual ~AP_OSD_Backend (void)
virtual void write (uint8_t x, uint8_t y, const char *text)=0
virtual void write (uint8_t x, uint8_t y, bool blink, const char *fmt,...) FMT_PRINTF(5
virtual void virtual bool init ()=0
virtual void flush ()=0
virtual float get_aspect_ratio_correction () const
virtual void clear ()
virtual void init_symbol_set (uint8_t *symbols, const uint8_t size)
virtual bool is_compatible_with_backend_type (AP_OSD::osd_types type) const =0
virtual AP_OSD::osd_types get_backend_type () const =0
virtual void osd_thread_run_once ()
AP_OSD * get_osd ()
Protected Types
enum vid_format { FORMAT_UNKNOWN = 0 , FORMAT_NTSC = 1 , FORMAT_PAL = 2 }
Protected Member Functions
uint8_t get_font_num (void) const
bool check_option (uint32_t option) const
uint8_t convert_to_decimal_packed_characters (char *buff, uint8_t size)
virtual uint8_t format_string_for_osd (char *dst, uint8_t size, bool decimal_packed, const char *fmt, va_list ap)
FileData * load_font_data (uint8_t font_num)
Protected Attributes
AP_OSD & _osd
int8_t blink_phase
enum AP_OSD_Backend::vid_format _format
Static Protected Attributes
static const uint8_t SYM_M = 0xB9
static const uint8_t SYM_KM = 0xBA
static const uint8_t SYM_FT = 0x0F
static const uint8_t SYM_MI = 0xBB
static const uint8_t SYM_ALT_M = 0xB1
static const uint8_t SYM_ALT_FT = 0xB3
static const uint8_t SYM_BATT_FULL = 0x90
static const uint8_t SYM_RSSI = 0x01
static const uint8_t SYM_VOLT = 0x06
static const uint8_t SYM_AMP = 0x9A
static const uint8_t SYM_MAH = 0x07
static const uint8_t SYM_MS = 0x9F
static const uint8_t SYM_FS = 0x99
static const uint8_t SYM_KMH = 0xA1
static const uint8_t SYM_MPH = 0xB0
static const uint8_t SYM_DEGR = 0xA8
static const uint8_t SYM_PCNT = 0x25
static const uint8_t SYM_RPM = 0xE0
static const uint8_t SYM_ASPD = 0xE1
static const uint8_t SYM_GSPD = 0xE2
static const uint8_t SYM_WSPD = 0xE3
static const uint8_t SYM_VSPD = 0xE4
static const uint8_t SYM_WPNO = 0xE5
static const uint8_t SYM_WPDIR = 0xE6
static const uint8_t SYM_WPDST = 0xE7
static const uint8_t SYM_FTMIN = 0xE8
static const uint8_t SYM_FTSEC = 0x99
static const uint8_t SYM_SAT_L = 0x1E
static const uint8_t SYM_SAT_R = 0x1F
static const uint8_t SYM_HDOP_L = 0xBD
static const uint8_t SYM_HDOP_R = 0xBE
static const uint8_t SYM_HOME = 0xBF
static const uint8_t SYM_WIND = 0x16
static const uint8_t SYM_ARROW_START = 0x60
static const uint8_t SYM_ARROW_COUNT = 16
static const uint8_t SYM_AH_H_START = 0x80
static const uint8_t SYM_AH_H_COUNT = 9
static const uint8_t SYM_AH_V_START = 0xCA
static const uint8_t SYM_AH_V_COUNT = 6
static const uint8_t SYM_AH_CENTER_LINE_LEFT = 0x26
static const uint8_t SYM_AH_CENTER_LINE_RIGHT = 0x27
static const uint8_t SYM_AH_CENTER = 0x7E
static const uint8_t SYM_HEADING_N = 0x18
static const uint8_t SYM_HEADING_S = 0x19
static const uint8_t SYM_HEADING_E = 0x1A
static const uint8_t SYM_HEADING_W = 0x1B
static const uint8_t SYM_HEADING_DIVIDED_LINE = 0x1C
static const uint8_t SYM_HEADING_LINE = 0x1D
static const uint8_t SYM_UP_UP = 0xA2
static const uint8_t SYM_UP = 0xA3
static const uint8_t SYM_DOWN = 0xA4
static const uint8_t SYM_DOWN_DOWN = 0xA5
static const uint8_t SYM_DEGREES_C = 0x0E
static const uint8_t SYM_DEGREES_F = 0x0D
static const uint8_t SYM_GPS_LAT = 0xA6
static const uint8_t SYM_GPS_LONG = 0xA7
static const uint8_t SYM_ARMED = 0x00
static const uint8_t SYM_DISARMED = 0xE9
static const uint8_t SYM_ROLL0 = 0x2D
static const uint8_t SYM_ROLLR = 0xEA
static const uint8_t SYM_ROLLL = 0xEB
static const uint8_t SYM_PTCH0 = 0x7C
static const uint8_t SYM_PTCHUP = 0xEC
static const uint8_t SYM_PTCHDWN = 0xED
static const uint8_t SYM_XERR = 0xEE
static const uint8_t SYM_KN = 0xF0
static const uint8_t SYM_NM = 0xF1
static const uint8_t SYM_DIST = 0x22
static const uint8_t SYM_FLY = 0x9C
static const uint8_t SYM_EFF = 0xF2
static const uint8_t SYM_AH = 0xF3
static const uint8_t SYM_MW = 0xF4
static const uint8_t SYM_CLK = 0xBC
static const uint8_t SYM_KILO = 0x4B
static const uint8_t SYM_TERALT = 0xEF
static const uint8_t SYM_FENCE_ENABLED = 0xF5
static const uint8_t SYM_FENCE_DISABLED = 0xF6
static const uint8_t SYM_RNGFD = 0xF7
static const uint8_t SYM_LQ = 0xF8
static const uint8_t SYM_SIDEBAR_R_ARROW = 0x09
static const uint8_t SYM_SIDEBAR_L_ARROW = 0x0A
static const uint8_t SYM_SIDEBAR_A = 0x13
static const uint8_t SYM_SIDEBAR_B = 0x14
static const uint8_t SYM_SIDEBAR_C = 0x15
static const uint8_t SYM_SIDEBAR_D = 0xDD
static const uint8_t SYM_SIDEBAR_E = 0xDB
static const uint8_t SYM_SIDEBAR_F = 0xDC
static const uint8_t SYM_SIDEBAR_G = 0xDA
static const uint8_t SYM_SIDEBAR_H = 0xDE
static const uint8_t SYM_SIDEBAR_I = 0x11
static const uint8_t SYM_SIDEBAR_J = 0x12
static constexpr uint8_t symbols [AP_OSD_NUM_SYMBOLS]
Detailed Description
Definition at line 24 of file AP_OSD_Backend.h.
Member Enumeration Documentation
vid_format
enum AP_OSD_Backend::vid_format protected
Enumerator
FORMAT_UNKNOWN
FORMAT_NTSC
FORMAT_PAL
Definition at line 92 of file AP_OSD_Backend.h.
Constructor & Destructor Documentation
AP_OSD_Backend()
AP_OSD_Backend::AP_OSD_Backend (AP_OSD & osd) inline
Definition at line 29 of file AP_OSD_Backend.h.
~AP_OSD_Backend()
virtual AP_OSD_Backend::~AP_OSD_Backend (void) inline virtual
Definition at line 32 of file AP_OSD_Backend.h.
Member Function Documentation
check_option()
bool AP_OSD_Backend::check_option (uint32_t option) const inline protected
Definition at line 79 of file AP_OSD_Backend.h.
Referenced by write().
clear()
virtual void AP_OSD_Backend::clear () inline virtual
Reimplemented in AP_OSD_MSP.
Definition at line 51 of file AP_OSD_Backend.h.
Referenced by AP_OSD::update_osd().
convert_to_decimal_packed_characters()
uint8_t AP_OSD_Backend::convert_to_decimal_packed_characters (char * buff, uint8_t size) protected
Definition at line 29 of file AP_OSD_Backend.cpp.
Referenced by format_string_for_osd().
flush()
virtual void AP_OSD_Backend::flush () pure virtual
Implemented in AP_OSD_MSP.
Referenced by AP_OSD::update_osd().
format_string_for_osd()
uint8_t AP_OSD_Backend::format_string_for_osd (char * dst, uint8_t size, bool decimal_packed, const char * fmt, va_list ap) protected virtual
Definition at line 55 of file AP_OSD_Backend.cpp.
Referenced by write().
get_aspect_ratio_correction()
virtual float AP_OSD_Backend::get_aspect_ratio_correction () const inline virtual
Definition at line 47 of file AP_OSD_Backend.h.
Referenced by AP_OSD_Screen::draw_horizon().
get_backend_type()
virtual AP_OSD::osd_types AP_OSD_Backend::get_backend_type () const pure virtual
Implemented in AP_OSD_MSP.
get_font_num()
uint8_t AP_OSD_Backend::get_font_num (void) const inline protected
Definition at line 73 of file AP_OSD_Backend.h.
get_osd()
AP_OSD * AP_OSD_Backend::get_osd () inline
Definition at line 64 of file AP_OSD_Backend.h.
Referenced by AP_OSD_AbstractScreen::set_backend().
init()
virtual void virtual bool AP_OSD_Backend::init () pure virtual
Implemented in AP_OSD_MSP.
init_symbol_set()
void AP_OSD_Backend::init_symbol_set (uint8_t * symbols, const uint8_t size) virtual
Definition at line 123 of file AP_OSD_Backend.cpp.
Referenced by AP_OSD::init_backend().
is_compatible_with_backend_type()
virtual bool AP_OSD_Backend::is_compatible_with_backend_type (AP_OSD::osd_types type) const pure virtual
Implemented in AP_OSD_MSP.
load_font_data()
FileData * AP_OSD_Backend::load_font_data (uint8_t font_num) protected
Definition at line 97 of file AP_OSD_Backend.cpp.
Referenced by load_font_data().
osd_thread_run_once()
virtual void AP_OSD_Backend::osd_thread_run_once () inline virtual
Definition at line 62 of file AP_OSD_Backend.h.
Referenced by AP_OSD::osd_thread().
write() [1/2]
void AP_OSD_Backend::write (uint8_t x, uint8_t y, bool blink, const char * fmt, ...) virtual
Definition at line 77 of file AP_OSD_Backend.cpp.
write() [2/2]
virtual void AP_OSD_Backend::write (uint8_t x, uint8_t y, const char * text) pure virtual
Implemented in AP_OSD_MSP.
Referenced by AP_OSD_Screen::draw_altitude(), AP_OSD_Screen::draw_aspd1(), AP_OSD_Screen::draw_aspd2(), AP_OSD_Screen::draw_aspeed(), AP_OSD_Screen::draw_atemp(), AP_OSD_Screen::draw_callsign(), AP_OSD_Screen::draw_compass(), AP_OSD_Screen::draw_dist(), AP_OSD_Screen::draw_distance(), AP_OSD_Screen::draw_flightime(), AP_OSD_Screen::draw_fltmode(), AP_OSD_Screen::draw_gps_latitude(), AP_OSD_Screen::draw_gps_longitude(), AP_OSD_Screen::draw_gspeed(), AP_OSD_Screen::draw_hdop(), AP_OSD_Screen::draw_heading(), AP_OSD_Screen::draw_home(), AP_OSD_Screen::draw_horizon(), AP_OSD_Screen::draw_message(), AP_OSD_ParamScreen::draw_parameter(), AP_OSD_Screen::draw_pitch_angle(), AP_OSD_Screen::draw_rngf(), AP_OSD_Screen::draw_roll_angle(), AP_OSD_Screen::draw_sats(), AP_OSD_Screen::draw_sidebars(), AP_OSD_Screen::draw_speed(), AP_OSD_Screen::draw_stat(), AP_OSD_Screen::draw_temp(), AP_OSD_Screen::draw_throttle(), AP_OSD_Screen::draw_vspeed(), AP_OSD_Screen::draw_waypoint(), AP_OSD_Screen::draw_wind(), AP_OSD_Screen::draw_xtrack_error(), and write().
Member Data Documentation
_format
enum AP_OSD_Backend::vid_format AP_OSD_Backend::_format protected
_osd
AP_OSD& AP_OSD_Backend::_osd protected
Definition at line 70 of file AP_OSD_Backend.h.
Referenced by check_option(), get_font_num(), and get_osd().
blink_phase
int8_t AP_OSD_Backend::blink_phase protected
Definition at line 90 of file AP_OSD_Backend.h.
Referenced by clear(), and write().
SYM_AH
const uint8_t AP_OSD_Backend::SYM_AH = 0xF3 static protected
Definition at line 178 of file AP_OSD_Backend.h.
SYM_AH_CENTER
const uint8_t AP_OSD_Backend::SYM_AH_CENTER = 0x7E static protected
Definition at line 146 of file AP_OSD_Backend.h.
SYM_AH_CENTER_LINE_LEFT
const uint8_t AP_OSD_Backend::SYM_AH_CENTER_LINE_LEFT = 0x26 static protected
Definition at line 144 of file AP_OSD_Backend.h.
SYM_AH_CENTER_LINE_RIGHT
const uint8_t AP_OSD_Backend::SYM_AH_CENTER_LINE_RIGHT = 0x27 static protected
Definition at line 145 of file AP_OSD_Backend.h.
SYM_AH_H_COUNT
const uint8_t AP_OSD_Backend::SYM_AH_H_COUNT = 9 static protected
Definition at line 139 of file AP_OSD_Backend.h.
SYM_AH_H_START
const uint8_t AP_OSD_Backend::SYM_AH_H_START = 0x80 static protected
Definition at line 138 of file AP_OSD_Backend.h.
SYM_AH_V_COUNT
const uint8_t AP_OSD_Backend::SYM_AH_V_COUNT = 6 static protected
Definition at line 142 of file AP_OSD_Backend.h.
SYM_AH_V_START
const uint8_t AP_OSD_Backend::SYM_AH_V_START = 0xCA static protected
Definition at line 141 of file AP_OSD_Backend.h.
SYM_ALT_FT
const uint8_t AP_OSD_Backend::SYM_ALT_FT = 0xB3 static protected
Definition at line 104 of file AP_OSD_Backend.h.
SYM_ALT_M
const uint8_t AP_OSD_Backend::SYM_ALT_M = 0xB1 static protected
Definition at line 103 of file AP_OSD_Backend.h.
SYM_AMP
const uint8_t AP_OSD_Backend::SYM_AMP = 0x9A static protected
Definition at line 109 of file AP_OSD_Backend.h.
SYM_ARMED
const uint8_t AP_OSD_Backend::SYM_ARMED = 0x00 static protected
Definition at line 164 of file AP_OSD_Backend.h.
SYM_ARROW_COUNT
const uint8_t AP_OSD_Backend::SYM_ARROW_COUNT = 16 static protected
Definition at line 137 of file AP_OSD_Backend.h.
SYM_ARROW_START
const uint8_t AP_OSD_Backend::SYM_ARROW_START = 0x60 static protected
Definition at line 136 of file AP_OSD_Backend.h.
SYM_ASPD
const uint8_t AP_OSD_Backend::SYM_ASPD = 0xE1 static protected
Definition at line 118 of file AP_OSD_Backend.h.
SYM_BATT_FULL
const uint8_t AP_OSD_Backend::SYM_BATT_FULL = 0x90 static protected
Definition at line 105 of file AP_OSD_Backend.h.
SYM_CLK
const uint8_t AP_OSD_Backend::SYM_CLK = 0xBC static protected
Definition at line 180 of file AP_OSD_Backend.h.
SYM_DEGR
const uint8_t AP_OSD_Backend::SYM_DEGR = 0xA8 static protected
Definition at line 115 of file AP_OSD_Backend.h.
SYM_DEGREES_C
const uint8_t AP_OSD_Backend::SYM_DEGREES_C = 0x0E static protected
Definition at line 160 of file AP_OSD_Backend.h.
SYM_DEGREES_F
const uint8_t AP_OSD_Backend::SYM_DEGREES_F = 0x0D static protected
Definition at line 161 of file AP_OSD_Backend.h.
SYM_DISARMED
const uint8_t AP_OSD_Backend::SYM_DISARMED = 0xE9 static protected
Definition at line 165 of file AP_OSD_Backend.h.
SYM_DIST
const uint8_t AP_OSD_Backend::SYM_DIST = 0x22 static protected
Definition at line 175 of file AP_OSD_Backend.h.
SYM_DOWN
const uint8_t AP_OSD_Backend::SYM_DOWN = 0xA4 static protected
Definition at line 157 of file AP_OSD_Backend.h.
SYM_DOWN_DOWN
const uint8_t AP_OSD_Backend::SYM_DOWN_DOWN = 0xA5 static protected
Definition at line 158 of file AP_OSD_Backend.h.
SYM_EFF
const uint8_t AP_OSD_Backend::SYM_EFF = 0xF2 static protected
Definition at line 177 of file AP_OSD_Backend.h.
SYM_FENCE_DISABLED
const uint8_t AP_OSD_Backend::SYM_FENCE_DISABLED = 0xF6 static protected
Definition at line 184 of file AP_OSD_Backend.h.
SYM_FENCE_ENABLED
const uint8_t AP_OSD_Backend::SYM_FENCE_ENABLED = 0xF5 static protected
Definition at line 183 of file AP_OSD_Backend.h.
SYM_FLY
const uint8_t AP_OSD_Backend::SYM_FLY = 0x9C static protected
Definition at line 176 of file AP_OSD_Backend.h.
SYM_FS
const uint8_t AP_OSD_Backend::SYM_FS = 0x99 static protected
Definition at line 112 of file AP_OSD_Backend.h.
SYM_FT
const uint8_t AP_OSD_Backend::SYM_FT = 0x0F static protected
Definition at line 101 of file AP_OSD_Backend.h.
SYM_FTMIN
const uint8_t AP_OSD_Backend::SYM_FTMIN = 0xE8 static protected
Definition at line 125 of file AP_OSD_Backend.h.
SYM_FTSEC
const uint8_t AP_OSD_Backend::SYM_FTSEC = 0x99 static protected
Definition at line 126 of file AP_OSD_Backend.h.
SYM_GPS_LAT
const uint8_t AP_OSD_Backend::SYM_GPS_LAT = 0xA6 static protected
Definition at line 162 of file AP_OSD_Backend.h.
SYM_GPS_LONG
const uint8_t AP_OSD_Backend::SYM_GPS_LONG = 0xA7 static protected
Definition at line 163 of file AP_OSD_Backend.h.
SYM_GSPD
const uint8_t AP_OSD_Backend::SYM_GSPD = 0xE2 static protected
Definition at line 119 of file AP_OSD_Backend.h.
SYM_HDOP_L
const uint8_t AP_OSD_Backend::SYM_HDOP_L = 0xBD static protected
Definition at line 130 of file AP_OSD_Backend.h.
SYM_HDOP_R
const uint8_t AP_OSD_Backend::SYM_HDOP_R = 0xBE static protected
Definition at line 131 of file AP_OSD_Backend.h.
SYM_HEADING_DIVIDED_LINE
const uint8_t AP_OSD_Backend::SYM_HEADING_DIVIDED_LINE = 0x1C static protected
Definition at line 152 of file AP_OSD_Backend.h.
SYM_HEADING_E
const uint8_t AP_OSD_Backend::SYM_HEADING_E = 0x1A static protected
Definition at line 150 of file AP_OSD_Backend.h.
SYM_HEADING_LINE
const uint8_t AP_OSD_Backend::SYM_HEADING_LINE = 0x1D static protected
Definition at line 153 of file AP_OSD_Backend.h.
SYM_HEADING_N
const uint8_t AP_OSD_Backend::SYM_HEADING_N = 0x18 static protected
Definition at line 148 of file AP_OSD_Backend.h.
SYM_HEADING_S
const uint8_t AP_OSD_Backend::SYM_HEADING_S = 0x19 static protected
Definition at line 149 of file AP_OSD_Backend.h.
SYM_HEADING_W
const uint8_t AP_OSD_Backend::SYM_HEADING_W = 0x1B static protected
Definition at line 151 of file AP_OSD_Backend.h.
SYM_HOME
const uint8_t AP_OSD_Backend::SYM_HOME = 0xBF static protected
Definition at line 133 of file AP_OSD_Backend.h.
SYM_KILO
const uint8_t AP_OSD_Backend::SYM_KILO = 0x4B static protected
Definition at line 181 of file AP_OSD_Backend.h.
SYM_KM
const uint8_t AP_OSD_Backend::SYM_KM = 0xBA static protected
Definition at line 100 of file AP_OSD_Backend.h.
SYM_KMH
const uint8_t AP_OSD_Backend::SYM_KMH = 0xA1 static protected
Definition at line 113 of file AP_OSD_Backend.h.
SYM_KN
const uint8_t AP_OSD_Backend::SYM_KN = 0xF0 static protected
Definition at line 173 of file AP_OSD_Backend.h.
SYM_LQ
const uint8_t AP_OSD_Backend::SYM_LQ = 0xF8 static protected
Definition at line 186 of file AP_OSD_Backend.h.
SYM_M
const uint8_t AP_OSD_Backend::SYM_M = 0xB9 static protected
Definition at line 99 of file AP_OSD_Backend.h.
SYM_MAH
const uint8_t AP_OSD_Backend::SYM_MAH = 0x07 static protected
Definition at line 110 of file AP_OSD_Backend.h.
SYM_MI
const uint8_t AP_OSD_Backend::SYM_MI = 0xBB static protected
Definition at line 102 of file AP_OSD_Backend.h.
SYM_MPH
const uint8_t AP_OSD_Backend::SYM_MPH = 0xB0 static protected
Definition at line 114 of file AP_OSD_Backend.h.
SYM_MS
const uint8_t AP_OSD_Backend::SYM_MS = 0x9F static protected
Definition at line 111 of file AP_OSD_Backend.h.
SYM_MW
const uint8_t AP_OSD_Backend::SYM_MW = 0xF4 static protected
Definition at line 179 of file AP_OSD_Backend.h.
SYM_NM
const uint8_t AP_OSD_Backend::SYM_NM = 0xF1 static protected
Definition at line 174 of file AP_OSD_Backend.h.
SYM_PCNT
const uint8_t AP_OSD_Backend::SYM_PCNT = 0x25 static protected
Definition at line 116 of file AP_OSD_Backend.h.
SYM_PTCH0
const uint8_t AP_OSD_Backend::SYM_PTCH0 = 0x7C static protected
Definition at line 169 of file AP_OSD_Backend.h.
SYM_PTCHDWN
const uint8_t AP_OSD_Backend::SYM_PTCHDWN = 0xED static protected
Definition at line 171 of file AP_OSD_Backend.h.
SYM_PTCHUP
const uint8_t AP_OSD_Backend::SYM_PTCHUP = 0xEC static protected
Definition at line 170 of file AP_OSD_Backend.h.
SYM_RNGFD
const uint8_t AP_OSD_Backend::SYM_RNGFD = 0xF7 static protected
Definition at line 185 of file AP_OSD_Backend.h.
SYM_ROLL0
const uint8_t AP_OSD_Backend::SYM_ROLL0 = 0x2D static protected
Definition at line 166 of file AP_OSD_Backend.h.
SYM_ROLLL
const uint8_t AP_OSD_Backend::SYM_ROLLL = 0xEB static protected
Definition at line 168 of file AP_OSD_Backend.h.
SYM_ROLLR
const uint8_t AP_OSD_Backend::SYM_ROLLR = 0xEA static protected
Definition at line 167 of file AP_OSD_Backend.h.
SYM_RPM
const uint8_t AP_OSD_Backend::SYM_RPM = 0xE0 static protected
Definition at line 117 of file AP_OSD_Backend.h.
SYM_RSSI
const uint8_t AP_OSD_Backend::SYM_RSSI = 0x01 static protected
Definition at line 106 of file AP_OSD_Backend.h.
SYM_SAT_L
const uint8_t AP_OSD_Backend::SYM_SAT_L = 0x1E static protected
Definition at line 128 of file AP_OSD_Backend.h.
SYM_SAT_R
const uint8_t AP_OSD_Backend::SYM_SAT_R = 0x1F static protected
Definition at line 129 of file AP_OSD_Backend.h.
SYM_SIDEBAR_A
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_A = 0x13 static protected
Definition at line 190 of file AP_OSD_Backend.h.
SYM_SIDEBAR_B
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_B = 0x14 static protected
Definition at line 191 of file AP_OSD_Backend.h.
SYM_SIDEBAR_C
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_C = 0x15 static protected
Definition at line 192 of file AP_OSD_Backend.h.
SYM_SIDEBAR_D
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_D = 0xDD static protected
Definition at line 193 of file AP_OSD_Backend.h.
SYM_SIDEBAR_E
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_E = 0xDB static protected
Definition at line 194 of file AP_OSD_Backend.h.
SYM_SIDEBAR_F
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_F = 0xDC static protected
Definition at line 195 of file AP_OSD_Backend.h.
SYM_SIDEBAR_G
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_G = 0xDA static protected
Definition at line 196 of file AP_OSD_Backend.h.
SYM_SIDEBAR_H
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_H = 0xDE static protected
Definition at line 197 of file AP_OSD_Backend.h.
SYM_SIDEBAR_I
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_I = 0x11 static protected
Definition at line 198 of file AP_OSD_Backend.h.
SYM_SIDEBAR_J
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_J = 0x12 static protected
Definition at line 199 of file AP_OSD_Backend.h.
SYM_SIDEBAR_L_ARROW
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_L_ARROW = 0x0A static protected
Definition at line 189 of file AP_OSD_Backend.h.
SYM_SIDEBAR_R_ARROW
const uint8_t AP_OSD_Backend::SYM_SIDEBAR_R_ARROW = 0x09 static protected
Definition at line 188 of file AP_OSD_Backend.h.
SYM_TERALT
const uint8_t AP_OSD_Backend::SYM_TERALT = 0xEF static protected
Definition at line 182 of file AP_OSD_Backend.h.
SYM_UP
const uint8_t AP_OSD_Backend::SYM_UP = 0xA3 static protected
Definition at line 156 of file AP_OSD_Backend.h.
SYM_UP_UP
const uint8_t AP_OSD_Backend::SYM_UP_UP = 0xA2 static protected
Definition at line 155 of file AP_OSD_Backend.h.
SYM_VOLT
const uint8_t AP_OSD_Backend::SYM_VOLT = 0x06 static protected
Definition at line 108 of file AP_OSD_Backend.h.
SYM_VSPD
const uint8_t AP_OSD_Backend::SYM_VSPD = 0xE4 static protected
Definition at line 121 of file AP_OSD_Backend.h.
SYM_WIND
const uint8_t AP_OSD_Backend::SYM_WIND = 0x16 static protected
Definition at line 134 of file AP_OSD_Backend.h.
SYM_WPDIR
const uint8_t AP_OSD_Backend::SYM_WPDIR = 0xE6 static protected
Definition at line 123 of file AP_OSD_Backend.h.
SYM_WPDST
const uint8_t AP_OSD_Backend::SYM_WPDST = 0xE7 static protected
Definition at line 124 of file AP_OSD_Backend.h.
SYM_WPNO
const uint8_t AP_OSD_Backend::SYM_WPNO = 0xE5 static protected
Definition at line 122 of file AP_OSD_Backend.h.
SYM_WSPD
const uint8_t AP_OSD_Backend::SYM_WSPD = 0xE3 static protected
Definition at line 120 of file AP_OSD_Backend.h.
SYM_XERR
const uint8_t AP_OSD_Backend::SYM_XERR = 0xEE static protected
Definition at line 172 of file AP_OSD_Backend.h.
symbols
constexpr uint8_t AP_OSD_Backend::symbols static constexpr protected
Definition at line 201 of file AP_OSD_Backend.h.
Referenced by init_symbol_set().
The documentation for this class was generated from the following files:
libraries/AP_OSD/AP_OSD_Backend.h
libraries/AP_OSD/AP_OSD_Backend.cpp