APM:Libraries: AP_Logger_Backend Class Reference
AP_Logger_Backend Class Reference abstract
#include <AP_Logger_Backend.h>
Classes
struct df_stats
Public Member Functions
FUNCTOR_TYPEDEF (vehicle_startup_message_Writer, void)
AP_Logger_Backend (AP_Logger &front, class LoggerMessageWriter_DFLogStart *writer)
vehicle_startup_message_Writer vehicle_message_writer () const
virtual bool CardInserted (void) const =0
virtual void EraseAll ()=0
bool WriteBlock (const void *pBuffer, uint16_t size)
bool WriteCriticalBlock (const void *pBuffer, uint16_t size)
bool WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical, bool writev_streaming=false)
virtual uint16_t find_last_log ()=0
virtual void get_log_boundaries (uint16_t list_entry, uint32_t &start_page, uint32_t &end_page)=0
virtual void get_log_info (uint16_t list_entry, uint32_t &size, uint32_t &time_utc)=0
virtual int16_t get_log_data (uint16_t list_entry, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)=0
virtual uint16_t get_num_logs ()=0
virtual uint16_t find_oldest_log ()
virtual bool logging_started (void) const =0
virtual void Init ()=0
virtual uint32_t bufferspace_available ()=0
virtual void PrepForArming ()
virtual void start_new_log ()
virtual void stop_logging (void)=0
virtual void stop_logging_async (void)
void Fill_Format (const struct LogStructure *structure, struct log_Format &pkt)
void Fill_Format_Units (const struct LogStructure *s, struct log_Format_Units &pkt)
virtual void flush (void)
virtual void remote_log_block_status_msg (const class GCS_MAVLINK &link, const mavlink_message_t &msg)
virtual void periodic_tasks ()
uint8_t num_types () const
const struct LogStructure * structure (uint8_t structure) const
uint8_t num_units () const
const struct UnitStructure * unit (uint8_t unit) const
uint8_t num_multipliers () const
const struct MultiplierStructure * multiplier (uint8_t multiplier) const
bool Write_EntireMission ()
bool Write_RallyPoint (uint8_t total, uint8_t sequence, const class RallyLocation &rally_point)
bool Write_Rally ()
bool Write_Format (const struct LogStructure *structure)
bool Write_Message (const char *message)
bool Write_MessageF (const char *fmt,...)
bool Write_Mission_Cmd (const AP_Mission &mission, const AP_Mission::Mission_Command &cmd)
bool Write_Mode (uint8_t mode, const ModeReason reason)
bool Write_Parameter (const char *name, float value, float default_val)
bool Write_Parameter (const AP_Param *ap, const AP_Param::ParamToken &token, enum ap_var_type type, float default_val)
bool Write_VER ()
uint32_t num_dropped (void) const
bool Write_Emit_FMT (uint8_t msg_type)
bool Write (uint8_t msg_type, va_list arg_list, bool is_critical=false, bool is_streaming=false)
virtual bool logging_enabled () const
virtual bool logging_failed () const =0
bool allow_start_ekf () const
virtual void vehicle_was_disarmed ()
bool Write_Unit (const struct UnitStructure *s)
bool Write_Multiplier (const struct MultiplierStructure *s)
bool Write_Format_Units (const struct LogStructure *structure)
virtual void io_timer (void)
Protected Member Functions
virtual void periodic_10Hz (const uint32_t now)
virtual void periodic_1Hz ()
virtual void periodic_fullrate ()
bool ShouldLog (bool is_critical)
virtual bool WritesOK () const =0
virtual bool StartNewLogOK () const
virtual void PrepForArming_start_logging (void)
virtual bool WriteBlockCheckStartupMessages ()
virtual void WriteMoreStartupMessages ()
virtual void push_log_blocks ()
virtual void start_new_log_reset_variables ()
uint16_t log_num_from_list_entry (const uint16_t list_entry)
uint32_t critical_message_reserved_space (uint32_t bufsize) const
uint32_t non_messagewriter_message_reserved_space (uint32_t bufsize) const
virtual bool _WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical)=0
void df_stats_gather (uint16_t bytes_written, uint32_t space_remaining)
void df_stats_log ()
void df_stats_clear ()
Protected Attributes
AP_Logger & _front
LoggerMessageWriter_DFLogStart * _startup_messagewriter
bool _writing_startup_messages
uint16_t _cached_oldest_log
uint32_t _dropped
uint32_t _log_file_size_bytes
bool _rotate_pending
bool _initialised
AP_Logger_RateLimiter * rate_limiter
Private Member Functions
void Write_AP_Logger_Stats_File (const struct df_stats &_stats)
void validate_WritePrioritisedBlock (const void *pBuffer, uint16_t size)
Private Attributes
struct df_stats stats
uint32_t _last_periodic_1Hz
uint32_t _last_periodic_10Hz
bool have_logged_armed
Detailed Description
Definition at line 46 of file AP_Logger_Backend.h.
Constructor & Destructor Documentation
AP_Logger_Backend()
AP_Logger_Backend::AP_Logger_Backend (AP_Logger & front, class LoggerMessageWriter_DFLogStart * writer)
Definition at line 22 of file AP_Logger_Backend.cpp.
Member Function Documentation
_WritePrioritisedBlock()
virtual bool AP_Logger_Backend::_WritePrioritisedBlock (const void * pBuffer, uint16_t size, bool is_critical) protected pure virtual
Implemented in AP_Logger_Block.
Referenced by WritePrioritisedBlock().
allow_start_ekf()
bool AP_Logger_Backend::allow_start_ekf () const
Definition at line 107 of file AP_Logger_Backend.cpp.
bufferspace_available()
virtual uint32_t AP_Logger_Backend::bufferspace_available () pure virtual
Implemented in AP_Logger_Block.
Referenced by LoggerMessageWriter_DFLogStart::process(), and Write().
CardInserted()
virtual bool AP_Logger_Backend::CardInserted (void) const pure virtual
Implemented in AP_Logger_Flash_JEDEC, AP_Logger_W25N01GV, and AP_Logger_Block.
critical_message_reserved_space()
uint32_t AP_Logger_Backend::critical_message_reserved_space (uint32_t bufsize) const inline protected
Definition at line 217 of file AP_Logger_Backend.h.
Referenced by AP_Logger_Block::_WritePrioritisedBlock().
df_stats_clear()
void AP_Logger_Backend::df_stats_clear () protected
Definition at line 677 of file AP_Logger_Backend.cpp.
Referenced by AP_Logger_Block::AP_Logger_Block(), and df_stats_log().
df_stats_gather()
void AP_Logger_Backend::df_stats_gather (uint16_t bytes_written, uint32_t space_remaining) protected
Definition at line 663 of file AP_Logger_Backend.cpp.
Referenced by AP_Logger_Block::_WritePrioritisedBlock().
df_stats_log()
void AP_Logger_Backend::df_stats_log () protected
Definition at line 682 of file AP_Logger_Backend.cpp.
Referenced by periodic_1Hz().
EraseAll()
virtual void AP_Logger_Backend::EraseAll () pure virtual
Implemented in AP_Logger_Block.
Fill_Format()
void AP_Logger_Backend::Fill_Format (const struct LogStructure * structure, struct log_Format & pkt)
Definition at line 28 of file LogFile.cpp.
Referenced by Write_Format().
Fill_Format_Units()
void AP_Logger_Backend::Fill_Format_Units (const struct LogStructure * s, struct log_Format_Units & pkt)
Definition at line 44 of file LogFile.cpp.
Referenced by Write_Format_Units().
find_last_log()
virtual uint16_t AP_Logger_Backend::find_last_log () pure virtual
Implemented in AP_Logger_Block.
Referenced by AP_Logger::find_last_log(), and find_oldest_log().
find_oldest_log()
uint16_t AP_Logger_Backend::find_oldest_log () virtual
Definition at line 611 of file AP_Logger_Backend.cpp.
Referenced by log_num_from_list_entry().
flush()
virtual void AP_Logger_Backend::flush (void) inline virtual
Definition at line 106 of file AP_Logger_Backend.h.
FUNCTOR_TYPEDEF()
AP_Logger_Backend::FUNCTOR_TYPEDEF (vehicle_startup_message_Writer , void)
get_log_boundaries()
virtual void AP_Logger_Backend::get_log_boundaries (uint16_t list_entry, uint32_t & start_page, uint32_t & end_page) pure virtual
Implemented in AP_Logger_Block.
Referenced by AP_Logger::get_log_boundaries().
get_log_data()
virtual int16_t AP_Logger_Backend::get_log_data (uint16_t list_entry, uint16_t page, uint32_t offset, uint16_t len, uint8_t * data) pure virtual
Implemented in AP_Logger_Block.
Referenced by AP_Logger::get_log_data().
get_log_info()
virtual void AP_Logger_Backend::get_log_info (uint16_t list_entry, uint32_t & size, uint32_t & time_utc) pure virtual
Implemented in AP_Logger_Block.
Referenced by AP_Logger::get_log_info().
get_num_logs()
virtual uint16_t AP_Logger_Backend::get_num_logs () pure virtual
Implemented in AP_Logger_Block.
Referenced by find_oldest_log(), and AP_Logger::get_num_logs().
Init()
virtual void AP_Logger_Backend::Init () pure virtual
Implemented in AP_Logger_Block, AP_Logger_Flash_JEDEC, and AP_Logger_W25N01GV.
Referenced by AP_Logger::init().
io_timer()
virtual void AP_Logger_Backend::io_timer (void) inline virtual
Reimplemented in AP_Logger_Block.
Definition at line 176 of file AP_Logger_Backend.h.
log_num_from_list_entry()
uint16_t AP_Logger_Backend::log_num_from_list_entry (const uint16_t list_entry) protected
Definition at line 594 of file AP_Logger_Backend.cpp.
Referenced by AP_Logger_Block::get_log_boundaries(), and AP_Logger_Block::get_log_data().
logging_enabled()
bool AP_Logger_Backend::logging_enabled () const virtual
Definition at line 639 of file AP_Logger_Backend.cpp.
Referenced by periodic_1Hz().
logging_failed()
virtual bool AP_Logger_Backend::logging_failed () const pure virtual
Implemented in AP_Logger_Block.
logging_started()
virtual bool AP_Logger_Backend::logging_started (void) const pure virtual
Implemented in AP_Logger_Block.
Referenced by PrepForArming(), and StartNewLogOK().
multiplier()
const struct MultiplierStructure * AP_Logger_Backend::multiplier (uint8_t multiplier) const
Definition at line 55 of file AP_Logger_Backend.cpp.
Referenced by LoggerMessageWriter_DFLogStart::process().
non_messagewriter_message_reserved_space()
uint32_t AP_Logger_Backend::non_messagewriter_message_reserved_space (uint32_t bufsize) const inline protected
Definition at line 226 of file AP_Logger_Backend.h.
Referenced by AP_Logger_Block::_WritePrioritisedBlock().
num_dropped()
uint32_t AP_Logger_Backend::num_dropped (void) const inline
Definition at line 147 of file AP_Logger_Backend.h.
Referenced by AP_Logger::num_dropped().
num_multipliers()
uint8_t AP_Logger_Backend::num_multipliers () const
Definition at line 50 of file AP_Logger_Backend.cpp.
num_types()
uint8_t AP_Logger_Backend::num_types () const
Definition at line 30 of file AP_Logger_Backend.cpp.
num_units()
uint8_t AP_Logger_Backend::num_units () const
Definition at line 40 of file AP_Logger_Backend.cpp.
periodic_10Hz()
void AP_Logger_Backend::periodic_10Hz (const uint32_t now) protected virtual
Reimplemented in AP_Logger_Block.
Definition at line 64 of file AP_Logger_Backend.cpp.
Referenced by periodic_tasks().
periodic_1Hz()
void AP_Logger_Backend::periodic_1Hz () protected virtual
Reimplemented in AP_Logger_Block.
Definition at line 68 of file AP_Logger_Backend.cpp.
Referenced by AP_Logger_Block::periodic_1Hz(), and periodic_tasks().
periodic_fullrate()
void AP_Logger_Backend::periodic_fullrate () protected virtual
Definition at line 78 of file AP_Logger_Backend.cpp.
Referenced by periodic_tasks().
periodic_tasks()
void AP_Logger_Backend::periodic_tasks () virtual
Definition at line 83 of file AP_Logger_Backend.cpp.
PrepForArming()
void AP_Logger_Backend::PrepForArming () virtual
Definition at line 485 of file AP_Logger_Backend.cpp.
PrepForArming_start_logging()
virtual void AP_Logger_Backend::PrepForArming_start_logging (void) inline protected virtual
Definition at line 191 of file AP_Logger_Backend.h.
Referenced by PrepForArming().
push_log_blocks()
void AP_Logger_Backend::push_log_blocks () protected virtual
Definition at line 122 of file AP_Logger_Backend.cpp.
Referenced by periodic_fullrate(), and WriteBlockCheckStartupMessages().
remote_log_block_status_msg()
virtual void AP_Logger_Backend::remote_log_block_status_msg (const class GCS_MAVLINK & link, const mavlink_message_t & msg) inline virtual
Definition at line 110 of file AP_Logger_Backend.h.
ShouldLog()
bool AP_Logger_Backend::ShouldLog (bool is_critical) protected
Definition at line 440 of file AP_Logger_Backend.cpp.
Referenced by WritePrioritisedBlock().
start_new_log()
virtual void AP_Logger_Backend::start_new_log (void) inline virtual
Reimplemented in AP_Logger_Block.
Definition at line 89 of file AP_Logger_Backend.h.
Referenced by PrepForArming_start_logging(), and WritePrioritisedBlock().
start_new_log_reset_variables()
void AP_Logger_Backend::start_new_log_reset_variables () protected virtual
Definition at line 97 of file AP_Logger_Backend.cpp.
Referenced by AP_Logger_Block::start_new_log().
StartNewLogOK()
bool AP_Logger_Backend::StartNewLogOK () const protected virtual
Definition at line 348 of file AP_Logger_Backend.cpp.
Referenced by WritePrioritisedBlock().
stop_logging()
virtual void AP_Logger_Backend::stop_logging (void) pure virtual
Implemented in AP_Logger_Block.
Referenced by PrepForArming(), and stop_logging_async().
stop_logging_async()
virtual void AP_Logger_Backend::stop_logging_async (void) inline virtual
Reimplemented in AP_Logger_Block.
Definition at line 99 of file AP_Logger_Backend.h.
Referenced by periodic_1Hz().
structure()
const struct LogStructure * AP_Logger_Backend::structure (uint8_t structure) const
Definition at line 35 of file AP_Logger_Backend.cpp.
Referenced by LoggerMessageWriter_DFLogStart::process().
unit()
const struct UnitStructure * AP_Logger_Backend::unit (uint8_t unit) const
Definition at line 45 of file AP_Logger_Backend.cpp.
Referenced by LoggerMessageWriter_DFLogStart::process().
validate_WritePrioritisedBlock()
void AP_Logger_Backend::validate_WritePrioritisedBlock (const void * pBuffer, uint16_t size) private
Definition at line 366 of file AP_Logger_Backend.cpp.
Referenced by WritePrioritisedBlock().
vehicle_message_writer()
AP_Logger_Backend::vehicle_startup_message_Writer AP_Logger_Backend::vehicle_message_writer () const
Definition at line 60 of file AP_Logger_Backend.cpp.
Referenced by LoggerMessageWriter_DFLogStart::process().
vehicle_was_disarmed()
void AP_Logger_Backend::vehicle_was_disarmed () virtual
Definition at line 627 of file AP_Logger_Backend.cpp.
Write()
bool AP_Logger_Backend::Write (uint8_t msg_type, va_list arg_list, bool is_critical = false, bool is_streaming = false)
Definition at line 222 of file AP_Logger_Backend.cpp.
Referenced by AP_Logger::WriteV().
Write_AP_Logger_Stats_File()
void AP_Logger_Backend::Write_AP_Logger_Stats_File (const struct df_stats & _stats) private
Definition at line 648 of file AP_Logger_Backend.cpp.
Referenced by df_stats_log().
Write_Emit_FMT()
bool AP_Logger_Backend::Write_Emit_FMT (uint8_t msg_type)
Definition at line 183 of file AP_Logger_Backend.cpp.
Write_EntireMission()
bool AP_Logger_Backend::Write_EntireMission ()
Write_Format()
bool AP_Logger_Backend::Write_Format (const struct LogStructure * structure)
Definition at line 59 of file LogFile.cpp.
Referenced by LoggerMessageWriter_DFLogStart::process(), and Write_Emit_FMT().
Write_Format_Units()
bool AP_Logger_Backend::Write_Format_Units (const struct LogStructure * structure)
Definition at line 100 of file LogFile.cpp.
Referenced by LoggerMessageWriter_DFLogStart::process(), and Write_Emit_FMT().
Write_Message()
bool AP_Logger_Backend::Write_Message (const char * message)
Definition at line 330 of file LogFile.cpp.
Referenced by LoggerMessageWriter_WriteSysInfo::process(), LoggerMessageWriter_WriteEntireMission::process(), and Write_MessageF().
Write_MessageF()
bool AP_Logger_Backend::Write_MessageF (const char * fmt, ...)
Definition at line 497 of file AP_Logger_Backend.cpp.
Referenced by LoggerMessageWriter_WriteSysInfo::process().
Write_Mission_Cmd()
bool AP_Logger_Backend::Write_Mission_Cmd (const AP_Mission & mission, const AP_Mission::Mission_Command & cmd)
Definition at line 298 of file LogFile.cpp.
Referenced by LoggerMessageWriter_WriteEntireMission::process().
Write_Mode()
bool AP_Logger_Backend::Write_Mode (uint8_t mode, const ModeReason reason)
Definition at line 437 of file LogFile.cpp.
Write_Multiplier()
bool AP_Logger_Backend::Write_Multiplier (const struct MultiplierStructure * s)
Definition at line 85 of file LogFile.cpp.
Referenced by LoggerMessageWriter_DFLogStart::process().
Write_Parameter() [1/2]
bool AP_Logger_Backend::Write_Parameter (const AP_Param * ap, const AP_Param::ParamToken & token, enum ap_var_type type, float default_val)
Definition at line 126 of file LogFile.cpp.
Write_Parameter() [2/2]
bool AP_Logger_Backend::Write_Parameter (const char * name, float value, float default_val)
Definition at line 110 of file LogFile.cpp.
Referenced by LoggerMessageWriter_DFLogStart::process(), and Write_Parameter().
Write_Rally()
bool AP_Logger_Backend::Write_Rally ()
Write_RallyPoint()
bool AP_Logger_Backend::Write_RallyPoint (uint8_t total, uint8_t sequence, const class RallyLocation & rally_point)
Write_Unit()
bool AP_Logger_Backend::Write_Unit (const struct UnitStructure * s)
Definition at line 69 of file LogFile.cpp.
Referenced by LoggerMessageWriter_DFLogStart::process().
Write_VER()
bool AP_Logger_Backend::Write_VER ()
Definition at line 563 of file AP_Logger_Backend.cpp.
Referenced by LoggerMessageWriter_WriteSysInfo::process().
WriteBlock()
bool AP_Logger_Backend::WriteBlock (const void * pBuffer, uint16_t size) inline
Definition at line 63 of file AP_Logger_Backend.h.
Referenced by Write_AP_Logger_Stats_File(), Write_Mission_Cmd(), and AP_Logger::WriteBlock_first_succeed().
WriteBlockCheckStartupMessages()
bool AP_Logger_Backend::WriteBlockCheckStartupMessages () protected virtual
Definition at line 128 of file AP_Logger_Backend.cpp.
Referenced by AP_Logger_Block::_WritePrioritisedBlock().
WriteCriticalBlock()
bool AP_Logger_Backend::WriteCriticalBlock (const void * pBuffer, uint16_t size) inline
Definition at line 67 of file AP_Logger_Backend.h.
Referenced by Write_Format(), Write_Format_Units(), Write_Message(), Write_Mode(), Write_Multiplier(), Write_Parameter(), Write_Unit(), and Write_VER().
WriteMoreStartupMessages()
void AP_Logger_Backend::WriteMoreStartupMessages () protected virtual
Definition at line 163 of file AP_Logger_Backend.cpp.
Referenced by push_log_blocks().
WritePrioritisedBlock()
bool AP_Logger_Backend::WritePrioritisedBlock (const void * pBuffer, uint16_t size, bool is_critical, bool writev_streaming = false)
Definition at line 415 of file AP_Logger_Backend.cpp.
Referenced by Write(), WriteBlock(), and WriteCriticalBlock().
WritesOK()
virtual bool AP_Logger_Backend::WritesOK () const protected pure virtual
Implemented in AP_Logger_Block.
Referenced by WritePrioritisedBlock().
Member Data Documentation
_cached_oldest_log
uint16_t AP_Logger_Backend::_cached_oldest_log protected
Definition at line 205 of file AP_Logger_Backend.h.
Referenced by find_oldest_log(), and AP_Logger_Block::FinishWrite().
_dropped
uint32_t AP_Logger_Backend::_dropped protected
Definition at line 207 of file AP_Logger_Backend.h.
Referenced by AP_Logger_Block::_WritePrioritisedBlock(), num_dropped(), and start_new_log_reset_variables().
_front
AP_Logger& AP_Logger_Backend::_front protected
Definition at line 180 of file AP_Logger_Backend.h.
Referenced by AP_Logger_Block::Init(), log_num_from_list_entry(), logging_enabled(), multiplier(), num_multipliers(), num_types(), num_units(), AP_Logger_Block::periodic_1Hz(), ShouldLog(), start_new_log_reset_variables(), StartNewLogOK(), structure(), unit(), validate_WritePrioritisedBlock(), vehicle_message_writer(), vehicle_was_disarmed(), Write(), and Write_Emit_FMT().
_initialised
bool AP_Logger_Backend::_initialised protected
Definition at line 240 of file AP_Logger_Backend.h.
Referenced by AP_Logger_Block::Init(), AP_Logger_Block::io_timer(), AP_Logger_Block::logging_failed(), AP_Logger_Block::periodic_1Hz(), and ShouldLog().
_last_periodic_10Hz
uint32_t AP_Logger_Backend::_last_periodic_10Hz private
Definition at line 260 of file AP_Logger_Backend.h.
Referenced by periodic_tasks().
_last_periodic_1Hz
uint32_t AP_Logger_Backend::_last_periodic_1Hz private
Definition at line 259 of file AP_Logger_Backend.h.
Referenced by periodic_tasks().
_log_file_size_bytes
uint32_t AP_Logger_Backend::_log_file_size_bytes protected
Definition at line 208 of file AP_Logger_Backend.h.
Referenced by df_stats_gather(), and start_new_log_reset_variables().
_rotate_pending
bool AP_Logger_Backend::_rotate_pending protected
Definition at line 210 of file AP_Logger_Backend.h.
Referenced by periodic_1Hz(), PrepForArming(), and vehicle_was_disarmed().
_startup_messagewriter
LoggerMessageWriter_DFLogStart* AP_Logger_Backend::_startup_messagewriter protected
Definition at line 202 of file AP_Logger_Backend.h.
Referenced by AP_Logger_Block::_WritePrioritisedBlock(), allow_start_ekf(), ShouldLog(), start_new_log_reset_variables(), WriteBlockCheckStartupMessages(), and WriteMoreStartupMessages().
_writing_startup_messages
bool AP_Logger_Backend::_writing_startup_messages protected
Definition at line 203 of file AP_Logger_Backend.h.
Referenced by AP_Logger_Block::_WritePrioritisedBlock(), WriteBlockCheckStartupMessages(), and WriteMoreStartupMessages().
have_logged_armed
bool AP_Logger_Backend::have_logged_armed private
Definition at line 261 of file AP_Logger_Backend.h.
Referenced by ShouldLog().
rate_limiter
AP_Logger_RateLimiter* AP_Logger_Backend::rate_limiter protected
Definition at line 246 of file AP_Logger_Backend.h.
Referenced by AP_Logger_Block::periodic_1Hz(), and WritePrioritisedBlock().
stats
struct df_stats AP_Logger_Backend::stats private
Definition at line 257 of file AP_Logger_Backend.h.
Referenced by df_stats_clear(), df_stats_gather(), and df_stats_log().
The documentation for this class was generated from the following files:
libraries/AP_Logger/AP_Logger_Backend.h
libraries/AP_Logger/AP_Logger_Backend.cpp
libraries/AP_Logger/LogFile.cpp