APM:Libraries: SITL::MS5525 Class Reference
SITL::MS5525 Class Reference
#include <SIM_MS5525.h>
Protected Member Functions
void get_pressure_temperature_readings (float &P_Pa, float &Temp_C) override
void convert (float P_Pa, float Temp_C, uint32_t &D1, uint32_t &D2) override
void convert_forward (int32_t D1, int32_t D2, float &P_Pa, float &Temp_C) override
void check_conversion_accuracy (float P_Pa, float Temp_C, uint32_t D1, uint32_t D2) override
void load_prom (uint16_t *_loaded_prom, uint8_t len) const override
Protected Member Functions inherited from SITL::MS5XXX
int rdwr (I2C::i2c_rdwr_ioctl_data *&data) override
void update (const class Aircraft &aircraft) override
Private Attributes
const uint16_t prom [8]
const uint8_t Qx_coeff [6]
Additional Inherited Members
Public Member Functions inherited from SITL::MS5XXX
MS5XXX ()
Public Member Functions inherited from SITL::I2CDevice
virtual void init ()
Detailed Description
Definition at line 7 of file SIM_MS5525.h.
Member Function Documentation
check_conversion_accuracy()
void MS5525::check_conversion_accuracy (float P_Pa, float Temp_C, uint32_t D1, uint32_t D2) override protected virtual
Implements SITL::MS5XXX.
Definition at line 47 of file SIM_MS5525.cpp.
convert()
void MS5525::convert (float P_Pa, float Temp_C, uint32_t & D1, uint32_t & D2) override protected virtual
Implements SITL::MS5XXX.
Definition at line 27 of file SIM_MS5525.cpp.
Referenced by dummy::convert_pub().
convert_forward()
void MS5525::convert_forward (int32_t D1, int32_t D2, float & P_Pa, float & Temp_C) override protected virtual
Implements SITL::MS5XXX.
Definition at line 7 of file SIM_MS5525.cpp.
Referenced by check_conversion_accuracy(), and dummy::convert_forward_pub().
get_pressure_temperature_readings()
void MS5525::get_pressure_temperature_readings (float & P_Pa, float & Temp_C) override protected virtual
Implements SITL::MS5XXX.
Definition at line 66 of file SIM_MS5525.cpp.
load_prom()
void SITL::MS5525::load_prom (uint16_t * _loaded_prom, uint8_t len) const inline override protected virtual
Implements SITL::MS5XXX.
Definition at line 19 of file SIM_MS5525.h.
Member Data Documentation
prom
const uint16_t SITL::MS5525::prom[8] private
Initial value:
{
        0xFFFF,
        36402,
        39473,
        40393,
        29523,
        29854,
        21917,
        0x000c
    }
Definition at line 26 of file SIM_MS5525.h.
Referenced by convert(), convert_forward(), and load_prom().
Qx_coeff
const uint8_t SITL::MS5525::Qx_coeff[6] private
Initial value:
{
        15, 17, 7, 5, 7, 21
    }
Definition at line 38 of file SIM_MS5525.h.
Referenced by convert(), and convert_forward().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_MS5525.h
libraries/SITL/SIM_MS5525.cpp