APM:Libraries: AP_Hott_Telem Class Reference
AP_Hott_Telem Class Reference
#include <AP_Hott_Telem.h>
Public Member Functions
AP_Hott_Telem ()
CLASS_NO_COPY (AP_Hott_Telem)
void init (void)
Static Public Member Functions
static AP_Hott_Telem * get_singleton (void)
Private Member Functions
void loop (void)
void send_EAM ()
void send_GPS ()
void send_Vario ()
void send_packet (const uint8_t *b, uint8_t len)
void GPS_to_DDM (float decimal, uint8_t &sign, uint16_t &dm, uint16_t &sec) const
Private Attributes
AP_HAL::UARTDriver * uart
float min_alt
float max_alt
Static Private Attributes
static AP_Hott_Telem * singleton
Detailed Description
Definition at line 24 of file AP_Hott_Telem.h.
Constructor & Destructor Documentation
AP_Hott_Telem()
AP_Hott_Telem::AP_Hott_Telem (void)
Definition at line 53 of file AP_Hott_Telem.cpp.
Member Function Documentation
CLASS_NO_COPY()
AP_Hott_Telem::CLASS_NO_COPY (AP_Hott_Telem)
get_singleton()
static AP_Hott_Telem * AP_Hott_Telem::get_singleton (void) inline static
Definition at line 31 of file AP_Hott_Telem.h.
Referenced by AP::hott_telem().
GPS_to_DDM()
void AP_Hott_Telem::GPS_to_DDM (float decimal, uint8_t & sign, uint16_t & dm, uint16_t & sec) const private
Definition at line 187 of file AP_Hott_Telem.cpp.
Referenced by send_GPS().
init()
void AP_Hott_Telem::init (void)
Definition at line 66 of file AP_Hott_Telem.cpp.
Referenced by AP_Vehicle::setup().
loop()
void AP_Hott_Telem::loop (void) private
Definition at line 410 of file AP_Hott_Telem.cpp.
Referenced by init().
send_EAM()
void AP_Hott_Telem::send_EAM (void) private
Definition at line 84 of file AP_Hott_Telem.cpp.
Referenced by loop().
send_GPS()
void AP_Hott_Telem::send_GPS (void) private
Definition at line 200 of file AP_Hott_Telem.cpp.
Referenced by loop().
send_packet()
void AP_Hott_Telem::send_packet (const uint8_t * b, uint8_t len) private
Definition at line 381 of file AP_Hott_Telem.cpp.
Referenced by send_EAM(), send_GPS(), and send_Vario().
send_Vario()
void AP_Hott_Telem::send_Vario (void) private
Definition at line 309 of file AP_Hott_Telem.cpp.
Referenced by loop().
Member Data Documentation
max_alt
float AP_Hott_Telem::max_alt private
Definition at line 50 of file AP_Hott_Telem.h.
Referenced by send_Vario().
min_alt
float AP_Hott_Telem::min_alt private
Definition at line 50 of file AP_Hott_Telem.h.
Referenced by send_Vario().
singleton
AP_Hott_Telem * AP_Hott_Telem::singleton static private
Definition at line 39 of file AP_Hott_Telem.h.
Referenced by AP_Hott_Telem(), and get_singleton().
uart
AP_HAL::UARTDriver* AP_Hott_Telem::uart private
Definition at line 41 of file AP_Hott_Telem.h.
Referenced by init(), loop(), and send_packet().
The documentation for this class was generated from the following files:
libraries/AP_Hott_Telem/AP_Hott_Telem.h
libraries/AP_Hott_Telem/AP_Hott_Telem.cpp