APM:Libraries: RC_Channel Class Reference
RC_Channel Class Reference
Object managing one RC channel.
#include <RC_Channel.h>
Classes
struct LookupTable
Public Types
enum class ControlType { ANGLE = 0 , RANGE = 1 }
enum class AUX_FUNC {
DO_NOTHING = 0 , FLIP = 2 , SIMPLE_MODE = 3 , RTL = 4 ,
SAVE_TRIM = 5 , SAVE_WP = 7 , CAMERA_TRIGGER = 9 , RANGEFINDER = 10 ,
FENCE = 11 , RESETTOARMEDYAW = 12 , SUPERSIMPLE_MODE = 13 , ACRO_TRAINER = 14 ,
SPRAYER = 15 , AUTO = 16 , AUTOTUNE = 17 , LAND = 18 ,
GRIPPER = 19 , PARACHUTE_ENABLE = 21 , PARACHUTE_RELEASE = 22 , PARACHUTE_3POS = 23 ,
MISSION_RESET = 24 , ATTCON_FEEDFWD = 25 , ATTCON_ACCEL_LIM = 26 , RETRACT_MOUNT1 = 27 ,
RELAY = 28 , LANDING_GEAR = 29 , LOST_VEHICLE_SOUND = 30 , MOTOR_ESTOP = 31 ,
MOTOR_INTERLOCK = 32 , BRAKE = 33 , RELAY2 = 34 , RELAY3 = 35 ,
RELAY4 = 36 , THROW = 37 , AVOID_ADSB = 38 , PRECISION_LOITER = 39 ,
AVOID_PROXIMITY = 40 , ARMDISARM_UNUSED = 41 , SMART_RTL = 42 , INVERTED = 43 ,
WINCH_ENABLE = 44 , WINCH_CONTROL = 45 , RC_OVERRIDE_ENABLE = 46 , USER_FUNC1 = 47 ,
USER_FUNC2 = 48 , USER_FUNC3 = 49 , LEARN_CRUISE = 50 , MANUAL = 51 ,
ACRO = 52 , STEERING = 53 , HOLD = 54 , GUIDED = 55 ,
LOITER = 56 , FOLLOW = 57 , CLEAR_WP = 58 , SIMPLE = 59 ,
ZIGZAG = 60 , ZIGZAG_SaveWP = 61 , COMPASS_LEARN = 62 , SAILBOAT_TACK = 63 ,
REVERSE_THROTTLE = 64 , GPS_DISABLE = 65 , RELAY5 = 66 , RELAY6 = 67 ,
STABILIZE = 68 , POSHOLD = 69 , ALTHOLD = 70 , FLOWHOLD = 71 ,
CIRCLE = 72 , DRIFT = 73 , SAILBOAT_MOTOR_3POS = 74 , SURFACE_TRACKING = 75 ,
STANDBY = 76 , TAKEOFF = 77 , RUNCAM_CONTROL = 78 , RUNCAM_OSD_CONTROL = 79 ,
VISODOM_ALIGN = 80 , DISARM = 81 , Q_ASSIST = 82 , ZIGZAG_Auto = 83 ,
AIRMODE = 84 , GENERATOR = 85 , TER_DISABLE = 86 , CROW_SELECT = 87 ,
SOARING = 88 , LANDING_FLARE = 89 , EKF_POS_SOURCE = 90 , ARSPD_CALIBRATE = 91 ,
FBWA = 92 , RELOCATE_MISSION = 93 , VTX_POWER = 94 , FBWA_TAILDRAGGER = 95 ,
MODE_SWITCH_RESET = 96 , WIND_VANE_DIR_OFSSET = 97 , TRAINING = 98 , AUTO_RTL = 99 ,
KILL_IMU1 = 100 , KILL_IMU2 = 101 , CAM_MODE_TOGGLE = 102 , EKF_LANE_SWITCH = 103 ,
EKF_YAW_RESET = 104 , GPS_DISABLE_YAW = 105 , DISABLE_AIRSPEED_USE = 106 , FW_AUTOTUNE = 107 ,
QRTL = 108 , CUSTOM_CONTROLLER = 109 , KILL_IMU3 = 110 , LOWEHEISER_STARTER = 111 ,
AHRS_TYPE = 112 , CRUISE = 150 , TURTLE = 151 , SIMPLE_HEADING_RESET = 152 ,
ARMDISARM = 153 , ARMDISARM_AIRMODE = 154 , TRIM_TO_CURRENT_SERVO_RC = 155 , TORQEEDO_CLEAR_ERR = 156 ,
EMERGENCY_LANDING_EN = 157 , OPTFLOW_CAL = 158 , FORCEFLYING = 159 , WEATHER_VANE_ENABLE = 160 ,
TURBINE_START = 161 , FFT_NOTCH_TUNE = 162 , MOUNT_LOCK = 163 , LOG_PAUSE = 164 ,
ARM_EMERGENCY_STOP = 165 , CAMERA_REC_VIDEO = 166 , CAMERA_ZOOM = 167 , CAMERA_MANUAL_FOCUS = 168 ,
CAMERA_AUTO_FOCUS = 169 , QSTABILIZE = 170 , MAG_CAL = 171 , BATTERY_MPPT_ENABLE = 172 ,
PLANE_AUTO_LANDING_ABORT = 173 , CAMERA_IMAGE_TRACKING = 174 , CAMERA_LENS = 175 , VFWD_THR_OVERRIDE = 176 ,
ROLL = 201 , PITCH = 202 , THROTTLE = 203 , YAW = 204 ,
MAINSAIL = 207 , FLAP = 208 , FWD_THR = 209 , AIRBRAKE = 210 ,
WALKING_HEIGHT = 211 , MOUNT1_ROLL = 212 , MOUNT1_PITCH = 213 , MOUNT1_YAW = 214 ,
MOUNT2_ROLL = 215 , MOUNT2_PITCH = 216 , MOUNT2_YAW = 217 , LOWEHEISER_THROTTLE = 218 ,
SCRIPTING_1 = 300 , SCRIPTING_2 = 301 , SCRIPTING_3 = 302 , SCRIPTING_4 = 303 ,
SCRIPTING_5 = 304 , SCRIPTING_6 = 305 , SCRIPTING_7 = 306 , SCRIPTING_8 = 307 ,
AUX_FUNCTION_MAX = 308
}
enum class AuxSwitchPos : uint8_t { LOW , MIDDLE , HIGH }
enum class AuxFuncTriggerSource : uint8_t {
INIT , RC , BUTTON , MAVLINK ,
MISSION , SCRIPTING
}
Public Member Functions
RC_Channel (void)
void set_range (uint16_t high)
uint16_t get_range () const
void set_angle (uint16_t angle)
bool get_reverse (void) const
void set_default_dead_zone (int16_t dzone)
uint16_t get_dead_zone (void) const
int16_t get_control_mid () const
bool update (void)
int16_t pwm_to_angle_dz_trim (uint16_t dead_zone, uint16_t trim) const
float norm_input () const
float norm_input_dz () const
float norm_input_ignore_trim () const
bool in_min_dz () const
uint8_t percent_input () const
bool in_trim_dz () const
int16_t get_radio_in () const
void set_radio_in (int16_t val)
int16_t get_control_in () const
void set_control_in (int16_t val)
void clear_override ()
void set_override (const uint16_t v, const uint32_t timestamp_ms)
bool has_override () const
float stick_mixing (const float servo_in)
int16_t get_control_in_zero_dz (void) const
int16_t get_radio_min () const
int16_t get_radio_max () const
int16_t get_radio_trim () const
void set_and_save_trim ()
void set_and_save_radio_trim (int16_t val)
bool configured ()
ControlType get_type (void) const
void init_aux ()
bool read_aux ()
AuxSwitchPos get_aux_switch_pos () const
bool run_aux_function (AUX_FUNC ch_option, AuxSwitchPos pos, AuxFuncTriggerSource source)
const char * string_for_aux_function (AUX_FUNC function) const
const char * string_for_aux_pos (AuxSwitchPos pos) const
Public Attributes
AP_Int16 option
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
static const uint16_t RC_MIN_LIMIT_PWM = 800
static const uint16_t RC_MAX_LIMIT_PWM = 2200
static const uint16_t RC_CALIB_MIN_LIMIT_PWM = 1300
static const uint16_t RC_CALIB_MAX_LIMIT_PWM = 1700
static const uint16_t AUX_SWITCH_PWM_TRIGGER_HIGH = 1800
static const uint16_t AUX_SWITCH_PWM_TRIGGER_LOW = 1200
static const uint16_t AUX_PWM_TRIGGER_HIGH = 1700
static const uint16_t AUX_PWM_TRIGGER_LOW = 1300
Protected Types
typedef int8_t modeswitch_pos_t
Protected Member Functions
virtual void init_aux_function (AUX_FUNC ch_option, AuxSwitchPos)
virtual bool do_aux_function (AUX_FUNC ch_option, AuxSwitchPos)
void do_aux_function_armdisarm (const AuxSwitchPos ch_flag)
void do_aux_function_avoid_adsb (const AuxSwitchPos ch_flag)
void do_aux_function_avoid_proximity (const AuxSwitchPos ch_flag)
void do_aux_function_camera_trigger (const AuxSwitchPos ch_flag)
bool do_aux_function_record_video (const AuxSwitchPos ch_flag)
bool do_aux_function_camera_zoom (const AuxSwitchPos ch_flag)
bool do_aux_function_camera_manual_focus (const AuxSwitchPos ch_flag)
bool do_aux_function_camera_auto_focus (const AuxSwitchPos ch_flag)
bool do_aux_function_camera_image_tracking (const AuxSwitchPos ch_flag)
bool do_aux_function_camera_lens (const AuxSwitchPos ch_flag)
void do_aux_function_runcam_control (const AuxSwitchPos ch_flag)
void do_aux_function_runcam_osd_control (const AuxSwitchPos ch_flag)
void do_aux_function_fence (const AuxSwitchPos ch_flag)
void do_aux_function_clear_wp (const AuxSwitchPos ch_flag)
void do_aux_function_gripper (const AuxSwitchPos ch_flag)
void do_aux_function_lost_vehicle_sound (const AuxSwitchPos ch_flag)
void do_aux_function_mission_reset (const AuxSwitchPos ch_flag)
void do_aux_function_rc_override_enable (const AuxSwitchPos ch_flag)
void do_aux_function_relay (uint8_t relay, bool val)
void do_aux_function_sprayer (const AuxSwitchPos ch_flag)
void do_aux_function_generator (const AuxSwitchPos ch_flag)
void do_aux_function_fft_notch_tune (const AuxSwitchPos ch_flag)
virtual void mode_switch_changed (modeswitch_pos_t new_pos)
Private Member Functions
int16_t pwm_to_angle () const
int16_t pwm_to_angle_dz (uint16_t dead_zone) const
int16_t pwm_to_range () const
int16_t pwm_to_range_dz (uint16_t dead_zone) const
bool read_3pos_switch (AuxSwitchPos &ret) const WARN_IF_UNUSED
bool read_6pos_switch (int8_t &position) WARN_IF_UNUSED
void reset_mode_switch ()
void read_mode_switch ()
bool debounce_completed (int8_t position)
Private Attributes
int16_t radio_in
int16_t control_in
AP_Int16 radio_min
AP_Int16 radio_trim
AP_Int16 radio_max
AP_Int8 reversed
AP_Int16 dead_zone
ControlType type_in
int16_t high_in
uint8_t ch_in
uint16_t override_value
uint32_t last_override_time
struct {
int8_t debounce_position = -1
int8_t current_position = -1
uint32_t last_edge_time_ms
} switch_state
Static Private Attributes
static const LookupTable lookuptable []
Friends
class RC_Channels
Detailed Description
Object managing one RC channel.
Definition at line 18 of file RC_Channel.h.
Member Typedef Documentation
modeswitch_pos_t
typedef int8_t RC_Channel::modeswitch_pos_t protected
Definition at line 364 of file RC_Channel.h.
Member Enumeration Documentation
AUX_FUNC
enum class RC_Channel::AUX_FUNC strong
Enumerator
DO_NOTHING
FLIP
SIMPLE_MODE
RTL
SAVE_TRIM
SAVE_WP
CAMERA_TRIGGER
RANGEFINDER
FENCE
RESETTOARMEDYAW
SUPERSIMPLE_MODE
ACRO_TRAINER
SPRAYER
AUTO
AUTOTUNE
LAND
GRIPPER
PARACHUTE_ENABLE
PARACHUTE_RELEASE
PARACHUTE_3POS
MISSION_RESET
ATTCON_FEEDFWD
ATTCON_ACCEL_LIM
RETRACT_MOUNT1
RELAY
LANDING_GEAR
LOST_VEHICLE_SOUND
MOTOR_ESTOP
MOTOR_INTERLOCK
BRAKE
RELAY2
RELAY3
RELAY4
THROW
AVOID_ADSB
PRECISION_LOITER
AVOID_PROXIMITY
ARMDISARM_UNUSED
SMART_RTL
INVERTED
WINCH_ENABLE
WINCH_CONTROL
RC_OVERRIDE_ENABLE
USER_FUNC1
USER_FUNC2
USER_FUNC3
LEARN_CRUISE
MANUAL
ACRO
STEERING
HOLD
GUIDED
LOITER
FOLLOW
CLEAR_WP
SIMPLE
ZIGZAG
ZIGZAG_SaveWP
COMPASS_LEARN
SAILBOAT_TACK
REVERSE_THROTTLE
GPS_DISABLE
RELAY5
RELAY6
STABILIZE
POSHOLD
ALTHOLD
FLOWHOLD
CIRCLE
DRIFT
SAILBOAT_MOTOR_3POS
SURFACE_TRACKING
STANDBY
TAKEOFF
RUNCAM_CONTROL
RUNCAM_OSD_CONTROL
VISODOM_ALIGN
DISARM
Q_ASSIST
ZIGZAG_Auto
AIRMODE
GENERATOR
TER_DISABLE
CROW_SELECT
SOARING
LANDING_FLARE
EKF_POS_SOURCE
ARSPD_CALIBRATE
FBWA
RELOCATE_MISSION
VTX_POWER
FBWA_TAILDRAGGER
MODE_SWITCH_RESET
WIND_VANE_DIR_OFSSET
TRAINING
AUTO_RTL
KILL_IMU1
KILL_IMU2
CAM_MODE_TOGGLE
EKF_LANE_SWITCH
EKF_YAW_RESET
GPS_DISABLE_YAW
DISABLE_AIRSPEED_USE
FW_AUTOTUNE
QRTL
CUSTOM_CONTROLLER
KILL_IMU3
LOWEHEISER_STARTER
AHRS_TYPE
CRUISE
TURTLE
SIMPLE_HEADING_RESET
ARMDISARM
ARMDISARM_AIRMODE
TRIM_TO_CURRENT_SERVO_RC
TORQEEDO_CLEAR_ERR
EMERGENCY_LANDING_EN
OPTFLOW_CAL
FORCEFLYING
WEATHER_VANE_ENABLE
TURBINE_START
FFT_NOTCH_TUNE
MOUNT_LOCK
LOG_PAUSE
ARM_EMERGENCY_STOP
CAMERA_REC_VIDEO
CAMERA_ZOOM
CAMERA_MANUAL_FOCUS
CAMERA_AUTO_FOCUS
QSTABILIZE
MAG_CAL
BATTERY_MPPT_ENABLE
PLANE_AUTO_LANDING_ABORT
CAMERA_IMAGE_TRACKING
CAMERA_LENS
VFWD_THR_OVERRIDE
ROLL
PITCH
THROTTLE
YAW
MAINSAIL
FLAP
FWD_THR
AIRBRAKE
WALKING_HEIGHT
MOUNT1_ROLL
MOUNT1_PITCH
MOUNT1_YAW
MOUNT2_ROLL
MOUNT2_PITCH
MOUNT2_YAW
LOWEHEISER_THROTTLE
SCRIPTING_1
SCRIPTING_2
SCRIPTING_3
SCRIPTING_4
SCRIPTING_5
SCRIPTING_6
SCRIPTING_7
SCRIPTING_8
AUX_FUNCTION_MAX
Definition at line 107 of file RC_Channel.h.
AuxFuncTriggerSource
enum class RC_Channel::AuxFuncTriggerSource : uint8_t strong
Enumerator
INIT
RC
BUTTON
MAVLINK
MISSION
SCRIPTING
Definition at line 296 of file RC_Channel.h.
AuxSwitchPos
enum class RC_Channel::AuxSwitchPos : uint8_t strong
Enumerator
LOW
MIDDLE
HIGH
Definition at line 290 of file RC_Channel.h.
ControlType
enum class RC_Channel::ControlType strong
Enumerator
ANGLE
RANGE
Definition at line 24 of file RC_Channel.h.
Constructor & Destructor Documentation
RC_Channel()
RC_Channel::RC_Channel (void)
Definition at line 256 of file RC_Channel.cpp.
Member Function Documentation
clear_override()
void RC_Channel::clear_override ()
Definition at line 495 of file RC_Channel.cpp.
Referenced by RC_Channels::clear_overrides().
configured()
bool RC_Channel::configured () inline
Definition at line 96 of file RC_Channel.h.
debounce_completed()
bool RC_Channel::debounce_completed (int8_t position) private
Definition at line 591 of file RC_Channel.cpp.
Referenced by read_6pos_switch(), and read_aux().
do_aux_function()
bool RC_Channel::do_aux_function (AUX_FUNC ch_option, AuxSwitchPos ch_flag) protected virtual
Definition at line 1248 of file RC_Channel.cpp.
Referenced by run_aux_function().
do_aux_function_armdisarm()
void RC_Channel::do_aux_function_armdisarm (const AuxSwitchPos ch_flag) protected
Definition at line 846 of file RC_Channel.cpp.
Referenced by do_aux_function().
do_aux_function_avoid_adsb()
void RC_Channel::do_aux_function_avoid_adsb (const AuxSwitchPos ch_flag) protected
Definition at line 862 of file RC_Channel.cpp.
Referenced by do_aux_function().
do_aux_function_avoid_proximity()
void RC_Channel::do_aux_function_avoid_proximity (const AuxSwitchPos ch_flag) protected
Definition at line 892 of file RC_Channel.cpp.
Referenced by do_aux_function().
do_aux_function_camera_auto_focus()
bool RC_Channel::do_aux_function_camera_auto_focus (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_camera_image_tracking()
bool RC_Channel::do_aux_function_camera_image_tracking (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_camera_lens()
bool RC_Channel::do_aux_function_camera_lens (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_camera_manual_focus()
bool RC_Channel::do_aux_function_camera_manual_focus (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_camera_trigger()
void RC_Channel::do_aux_function_camera_trigger (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_camera_zoom()
bool RC_Channel::do_aux_function_camera_zoom (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_clear_wp()
void RC_Channel::do_aux_function_clear_wp (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_fence()
void RC_Channel::do_aux_function_fence (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_fft_notch_tune()
void RC_Channel::do_aux_function_fft_notch_tune (const AuxSwitchPos ch_flag) protected
Definition at line 1193 of file RC_Channel.cpp.
Referenced by do_aux_function().
do_aux_function_generator()
void RC_Channel::do_aux_function_generator (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_gripper()
void RC_Channel::do_aux_function_gripper (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_lost_vehicle_sound()
void RC_Channel::do_aux_function_lost_vehicle_sound (const AuxSwitchPos ch_flag) protected
Definition at line 1147 of file RC_Channel.cpp.
Referenced by do_aux_function().
do_aux_function_mission_reset()
void RC_Channel::do_aux_function_mission_reset (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_rc_override_enable()
void RC_Channel::do_aux_function_rc_override_enable (const AuxSwitchPos ch_flag) protected
Definition at line 1162 of file RC_Channel.cpp.
Referenced by do_aux_function().
do_aux_function_record_video()
bool RC_Channel::do_aux_function_record_video (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
do_aux_function_relay()
void RC_Channel::do_aux_function_relay (uint8_t relay, bool val) protected
Referenced by do_aux_function().
do_aux_function_runcam_control()
void RC_Channel::do_aux_function_runcam_control (const AuxSwitchPos ch_flag) protected
Definition at line 1013 of file RC_Channel.cpp.
Referenced by do_aux_function().
do_aux_function_runcam_osd_control()
void RC_Channel::do_aux_function_runcam_osd_control (const AuxSwitchPos ch_flag) protected
Definition at line 1035 of file RC_Channel.cpp.
Referenced by do_aux_function().
do_aux_function_sprayer()
void RC_Channel::do_aux_function_sprayer (const AuxSwitchPos ch_flag) protected
Referenced by do_aux_function().
get_aux_switch_pos()
RC_Channel::AuxSwitchPos RC_Channel::get_aux_switch_pos () const
Definition at line 1716 of file RC_Channel.cpp.
get_control_in()
int16_t RC_Channel::get_control_in () const inline
Definition at line 72 of file RC_Channel.h.
get_control_in_zero_dz()
int16_t RC_Channel::get_control_in_zero_dz (void) const
Definition at line 393 of file RC_Channel.cpp.
get_control_mid()
int16_t RC_Channel::get_control_mid () const
Definition at line 308 of file RC_Channel.cpp.
get_dead_zone()
uint16_t RC_Channel::get_dead_zone (void) const inline
Definition at line 35 of file RC_Channel.h.
Referenced by SRV_Channel::output_ch(), and AP_Mount_Backend::set_rctargeting_on_rcinput_change().
get_radio_in()
int16_t RC_Channel::get_radio_in () const inline
Definition at line 69 of file RC_Channel.h.
Referenced by AP_Tuning::check_selector_switch(), AP_ICEngine::engine_control(), RC_Channels::get_radio_in(), RC_Channels::get_radio_in(), AP_Mount_Backend::get_rc_input(), loop(), SRV_Channel::output_ch(), read_3pos_switch(), read_6pos_switch(), AP_RSSI::read_channel_rssi(), AP_Mount_Backend::set_rctargeting_on_rcinput_change(), AP_ICEngine::update(), and AP_OSD::update_current_screen().
get_radio_max()
int16_t RC_Channel::get_radio_max () const inline
Definition at line 86 of file RC_Channel.h.
get_radio_min()
int16_t RC_Channel::get_radio_min () const inline
Definition at line 84 of file RC_Channel.h.
get_radio_trim()
int16_t RC_Channel::get_radio_trim () const inline
Definition at line 88 of file RC_Channel.h.
Referenced by SRV_Channel::output_ch(), and AP_OSD::update_current_screen().
get_range()
uint16_t RC_Channel::get_range () const inline
Definition at line 31 of file RC_Channel.h.
get_reverse()
bool RC_Channel::get_reverse (void) const
Definition at line 278 of file RC_Channel.cpp.
get_type()
ControlType RC_Channel::get_type (void) const inline
Definition at line 98 of file RC_Channel.h.
Referenced by SRV_Channel::output_ch().
has_override()
bool RC_Channel::has_override () const
Definition at line 501 of file RC_Channel.cpp.
Referenced by RC_Channels::get_override_mask(), RC_Channels::has_active_overrides(), and update().
in_min_dz()
bool RC_Channel::in_min_dz () const
Definition at line 479 of file RC_Channel.cpp.
in_trim_dz()
bool RC_Channel::in_trim_dz () const
Definition at line 470 of file RC_Channel.cpp.
init_aux()
void RC_Channel::init_aux ()
Definition at line 1684 of file RC_Channel.cpp.
Referenced by RC_Channels::init_aux_all().
init_aux_function()
void RC_Channel::init_aux_function (AUX_FUNC ch_option, AuxSwitchPos ch_flag) protected virtual
Definition at line 620 of file RC_Channel.cpp.
Referenced by init_aux().
mode_switch_changed()
virtual void RC_Channel::mode_switch_changed (modeswitch_pos_t new_pos) inline protected virtual
Definition at line 365 of file RC_Channel.h.
Referenced by read_mode_switch().
norm_input()
float RC_Channel::norm_input () const
Definition at line 403 of file RC_Channel.cpp.
norm_input_dz()
float RC_Channel::norm_input_dz () const
Definition at line 421 of file RC_Channel.cpp.
Referenced by AP_Mount_Backend::get_rc_input(), and SRV_Channel::output_ch().
norm_input_ignore_trim()
float RC_Channel::norm_input_ignore_trim () const
Definition at line 439 of file RC_Channel.cpp.
Referenced by SRV_Channel::output_ch().
percent_input()
uint8_t RC_Channel::percent_input () const
Definition at line 452 of file RC_Channel.cpp.
pwm_to_angle()
int16_t RC_Channel::pwm_to_angle () const private
Definition at line 357 of file RC_Channel.cpp.
Referenced by update().
pwm_to_angle_dz()
int16_t RC_Channel::pwm_to_angle_dz (uint16_t dead_zone) const private
Definition at line 348 of file RC_Channel.cpp.
Referenced by get_control_in_zero_dz(), and pwm_to_angle().
pwm_to_angle_dz_trim()
int16_t RC_Channel::pwm_to_angle_dz_trim (uint16_t dead_zone, uint16_t trim) const
Definition at line 325 of file RC_Channel.cpp.
Referenced by pwm_to_angle_dz().
pwm_to_range()
int16_t RC_Channel::pwm_to_range () const private
Definition at line 387 of file RC_Channel.cpp.
Referenced by update().
pwm_to_range_dz()
int16_t RC_Channel::pwm_to_range_dz (uint16_t dead_zone) const private
Definition at line 367 of file RC_Channel.cpp.
Referenced by get_control_in_zero_dz(), and pwm_to_range().
read_3pos_switch()
bool RC_Channel::read_3pos_switch (RC_Channel::AuxSwitchPos & ret) const private
Definition at line 1694 of file RC_Channel.cpp.
Referenced by get_aux_switch_pos(), init_aux(), and read_aux().
read_6pos_switch()
bool RC_Channel::read_6pos_switch (int8_t & position) private
Definition at line 553 of file RC_Channel.cpp.
Referenced by read_aux(), and read_mode_switch().
read_aux()
bool RC_Channel::read_aux ()
Definition at line 805 of file RC_Channel.cpp.
Referenced by RC_Channels::read_aux_all().
read_mode_switch()
void RC_Channel::read_mode_switch () private
Definition at line 582 of file RC_Channel.cpp.
Referenced by RC_Channels::read_mode_switch(), and reset_mode_switch().
reset_mode_switch()
void RC_Channel::reset_mode_switch () private
Definition at line 545 of file RC_Channel.cpp.
Referenced by RC_Channels::reset_mode_switch().
run_aux_function()
bool RC_Channel::run_aux_function (AUX_FUNC ch_option, AuxSwitchPos pos, AuxFuncTriggerSource source)
Definition at line 1213 of file RC_Channel.cpp.
Referenced by init_aux_function(), read_aux(), RC_Channels::run_aux_function(), and AP_Button::run_aux_functions().
set_and_save_radio_trim()
void RC_Channel::set_and_save_radio_trim (int16_t val) inline
Definition at line 93 of file RC_Channel.h.
set_and_save_trim()
void RC_Channel::set_and_save_trim () inline
Definition at line 90 of file RC_Channel.h.
set_angle()
void RC_Channel::set_angle (uint16_t angle)
Definition at line 267 of file RC_Channel.cpp.
Referenced by setup().
set_control_in()
void RC_Channel::set_control_in (int16_t val) inline
Definition at line 73 of file RC_Channel.h.
set_default_dead_zone()
void RC_Channel::set_default_dead_zone (int16_t dzone)
Definition at line 273 of file RC_Channel.cpp.
Referenced by setup().
set_override()
void RC_Channel::set_override (const uint16_t v, const uint32_t timestamp_ms)
Definition at line 484 of file RC_Channel.cpp.
Referenced by RC_Channels::set_override().
set_radio_in()
void RC_Channel::set_radio_in (int16_t val) inline
Definition at line 70 of file RC_Channel.h.
Referenced by SRV_Channels::set_output_limit().
set_range()
void RC_Channel::set_range (uint16_t high)
Definition at line 261 of file RC_Channel.cpp.
Referenced by setup().
stick_mixing()
float RC_Channel::stick_mixing (const float servo_in)
Definition at line 527 of file RC_Channel.cpp.
string_for_aux_function()
const char * RC_Channel::string_for_aux_function (AUX_FUNC function) const
Definition at line 776 of file RC_Channel.cpp.
Referenced by read_aux(), and AP_Button::run_aux_functions().
string_for_aux_pos()
const char * RC_Channel::string_for_aux_pos (AuxSwitchPos pos) const
Definition at line 787 of file RC_Channel.cpp.
Referenced by read_aux(), and AP_Button::run_aux_functions().
update()
bool RC_Channel::update (void)
Definition at line 284 of file RC_Channel.cpp.
Referenced by RC_Channels::read_input().
Friends And Related Symbol Documentation
RC_Channels
friend class RC_Channels friend
Definition at line 20 of file RC_Channel.h.
Member Data Documentation
AUX_PWM_TRIGGER_HIGH
const uint16_t RC_Channel::AUX_PWM_TRIGGER_HIGH = 1700 static
Definition at line 330 of file RC_Channel.h.
Referenced by AP_Tuning::check_selector_switch(), and AP_ICEngine::update().
AUX_PWM_TRIGGER_LOW
const uint16_t RC_Channel::AUX_PWM_TRIGGER_LOW = 1300 static
Definition at line 332 of file RC_Channel.h.
Referenced by AP_Tuning::check_selector_switch(), AP_ICEngine::engine_control(), and AP_ICEngine::update().
AUX_SWITCH_PWM_TRIGGER_HIGH
const uint16_t RC_Channel::AUX_SWITCH_PWM_TRIGGER_HIGH = 1800 static
Definition at line 325 of file RC_Channel.h.
Referenced by read_3pos_switch(), and AP_Button::update().
AUX_SWITCH_PWM_TRIGGER_LOW
const uint16_t RC_Channel::AUX_SWITCH_PWM_TRIGGER_LOW = 1200 static
Definition at line 327 of file RC_Channel.h.
Referenced by read_3pos_switch(), and AP_Button::update().
ch_in
uint8_t RC_Channel::ch_in private
Definition at line 389 of file RC_Channel.h.
Referenced by RC_Channels::init(), init_aux_function(), read_aux(), and update().
control_in
int16_t RC_Channel::control_in private
Definition at line 376 of file RC_Channel.h.
Referenced by get_control_in(), set_control_in(), stick_mixing(), and update().
current_position
int8_t RC_Channel::current_position = -1
Definition at line 407 of file RC_Channel.h.
dead_zone
AP_Int16 RC_Channel::dead_zone private
Definition at line 383 of file RC_Channel.h.
Referenced by get_control_mid(), get_dead_zone(), in_min_dz(), in_trim_dz(), norm_input_dz(), pwm_to_angle(), pwm_to_range(), and set_default_dead_zone().
debounce_position
int8_t RC_Channel::debounce_position = -1
Definition at line 406 of file RC_Channel.h.
high_in
int16_t RC_Channel::high_in private
Definition at line 386 of file RC_Channel.h.
Referenced by get_control_mid(), get_range(), pwm_to_angle_dz_trim(), pwm_to_range_dz(), set_angle(), and set_range().
last_edge_time_ms
uint32_t RC_Channel::last_edge_time_ms
Definition at line 408 of file RC_Channel.h.
last_override_time
uint32_t RC_Channel::last_override_time private
Definition at line 393 of file RC_Channel.h.
Referenced by clear_override(), has_override(), and set_override().
lookuptable
const RC_Channel::LookupTable RC_Channel::lookuptable static private
Definition at line 721 of file RC_Channel.h.
Referenced by string_for_aux_function().
option
AP_Int16 RC_Channel::option
Definition at line 100 of file RC_Channel.h.
Referenced by RC_Channels::convert_options(), RC_Channels::duplicate_options_exist(), RC_Channels::find_channel_for_option(), init_aux(), and read_aux().
override_value
uint16_t RC_Channel::override_value private
Definition at line 392 of file RC_Channel.h.
Referenced by clear_override(), has_override(), set_override(), and update().
radio_in
int16_t RC_Channel::radio_in private
Definition at line 373 of file RC_Channel.h.
Referenced by get_radio_in(), in_min_dz(), in_trim_dz(), norm_input(), norm_input_dz(), norm_input_ignore_trim(), percent_input(), pwm_to_angle_dz_trim(), pwm_to_range_dz(), set_and_save_trim(), set_radio_in(), stick_mixing(), and update().
radio_max
AP_Int16 RC_Channel::radio_max private
Definition at line 380 of file RC_Channel.h.
Referenced by configured(), get_control_mid(), get_radio_max(), norm_input(), norm_input_dz(), norm_input_ignore_trim(), percent_input(), pwm_to_angle_dz_trim(), and pwm_to_range_dz().
radio_min
AP_Int16 RC_Channel::radio_min private
Definition at line 378 of file RC_Channel.h.
Referenced by configured(), get_control_mid(), get_radio_min(), in_min_dz(), norm_input(), norm_input_dz(), norm_input_ignore_trim(), percent_input(), pwm_to_angle_dz_trim(), and pwm_to_range_dz().
radio_trim
AP_Int16 RC_Channel::radio_trim private
Definition at line 379 of file RC_Channel.h.
Referenced by configured(), get_radio_trim(), in_trim_dz(), norm_input(), norm_input_dz(), pwm_to_angle_dz(), set_and_save_radio_trim(), set_and_save_trim(), and stick_mixing().
RC_CALIB_MAX_LIMIT_PWM
const uint16_t RC_Channel::RC_CALIB_MAX_LIMIT_PWM = 1700 static
Definition at line 322 of file RC_Channel.h.
RC_CALIB_MIN_LIMIT_PWM
const uint16_t RC_Channel::RC_CALIB_MIN_LIMIT_PWM = 1300 static
Definition at line 320 of file RC_Channel.h.
RC_MAX_LIMIT_PWM
const uint16_t RC_Channel::RC_MAX_LIMIT_PWM = 2200 static
Definition at line 317 of file RC_Channel.h.
Referenced by read_3pos_switch(), read_6pos_switch(), and AP_Button::update().
RC_MIN_LIMIT_PWM
const uint16_t RC_Channel::RC_MIN_LIMIT_PWM = 800 static
Definition at line 315 of file RC_Channel.h.
reversed
AP_Int8 RC_Channel::reversed private
Definition at line 382 of file RC_Channel.h.
Referenced by get_reverse(), norm_input(), norm_input_dz(), norm_input_ignore_trim(), percent_input(), pwm_to_angle_dz_trim(), pwm_to_range_dz(), and read_3pos_switch().
[struct]
struct { ... } RC_Channel::switch_state
Referenced by debounce_completed(), and reset_mode_switch().
type_in
ControlType RC_Channel::type_in private
Definition at line 385 of file RC_Channel.h.
Referenced by get_control_in_zero_dz(), get_control_mid(), get_type(), set_angle(), set_range(), and update().
var_info
const AP_Param::GroupInfo RC_Channel::var_info static
Definition at line 64 of file RC_Channel.h.
The documentation for this class was generated from the following files:
libraries/RC_Channel/RC_Channel.h
libraries/RC_Channel/RC_Channel.cpp