APM:Libraries: AP_SerialManager::UARTState Class Reference
AP_SerialManager::UARTState Class Reference
#include <AP_SerialManager.h>
Public Member Functions
bool option_enabled (uint16_t option) const
uint32_t baudrate () const
AP_SerialManager::SerialProtocol get_protocol () const
Public Attributes
AP_Int32 baud
AP_Int16 options
AP_Int8 protocol
uint8_t idx
Friends
class AP_SerialManager
Detailed Description
Definition at line 137 of file AP_SerialManager.h.
Member Function Documentation
baudrate()
uint32_t AP_SerialManager::UARTState::baudrate () const inline
Definition at line 145 of file AP_SerialManager.h.
Referenced by AP_SerialManager::find_baudrate(), and GCS_MAVLINK::init().
get_protocol()
AP_SerialManager::SerialProtocol AP_SerialManager::UARTState::get_protocol () const inline
Definition at line 148 of file AP_SerialManager.h.
Referenced by GCS_MAVLINK::capabilities(), GCS_MAVLINK::init(), and GCS_MAVLINK::packetReceived().
option_enabled()
bool AP_SerialManager::UARTState::option_enabled (uint16_t option) const inline
Definition at line 140 of file AP_SerialManager.h.
Referenced by GCS_MAVLINK::init().
Friends And Related Symbol Documentation
AP_SerialManager
friend class AP_SerialManager friend
Definition at line 138 of file AP_SerialManager.h.
Member Data Documentation
baud
AP_Int32 AP_SerialManager::UARTState::baud
Definition at line 151 of file AP_SerialManager.h.
Referenced by baudrate(), AP_SerialManager::init(), and AP_SerialManager::set_protocol_and_baud().
idx
uint8_t AP_SerialManager::UARTState::idx
Definition at line 156 of file AP_SerialManager.h.
Referenced by AP_SerialManager::find_portnum(), AP_SerialManager::find_serial(), and AP_SerialManager::init().
options
AP_Int16 AP_SerialManager::UARTState::options
Definition at line 152 of file AP_SerialManager.h.
Referenced by AP_SerialManager::find_serial(), option_enabled(), and AP_SerialManager::set_options().
protocol
AP_Int8 AP_SerialManager::UARTState::protocol
Definition at line 153 of file AP_SerialManager.h.
Referenced by get_protocol(), AP_SerialManager::init(), and AP_SerialManager::set_protocol_and_baud().
The documentation for this class was generated from the following file:
libraries/AP_SerialManager/AP_SerialManager.h