APM:Libraries: AP_HAL::AnalogIn Class Reference
AP_HAL::AnalogIn Class Reference abstract
#include <AnalogIn.h>
Public Types
enum class PowerStatusFlag : uint16_t {
BRICK_VALID = 1 , SERVO_VALID = 2 , USB_CONNECTED = 4 , PERIPH_OVERCURRENT = 8 ,
PERIPH_HIPOWER_OVERCURRENT = 16 , CHANGED = 32
}
Public Member Functions
virtual void init ()=0
virtual AP_HAL::AnalogSource * channel (int16_t n)=0
virtual float board_voltage (void)=0
virtual float servorail_voltage (void)
virtual uint16_t power_status_flags (void)
virtual uint16_t accumulated_power_status_flags (void) const
Detailed Description
Definition at line 27 of file AnalogIn.h.
Member Enumeration Documentation
PowerStatusFlag
enum class AP_HAL::AnalogIn::PowerStatusFlag : uint16_t strong
Enumerator
BRICK_VALID
SERVO_VALID
USB_CONNECTED
PERIPH_OVERCURRENT
PERIPH_HIPOWER_OVERCURRENT
CHANGED
Definition at line 46 of file AnalogIn.h.
Member Function Documentation
accumulated_power_status_flags()
virtual uint16_t AP_HAL::AnalogIn::accumulated_power_status_flags (void) const inline virtual
Reimplemented in ChibiOS::AnalogIn.
Definition at line 43 of file AnalogIn.h.
Referenced by AP_Logger::Write_Power().
board_voltage()
virtual float AP_HAL::AnalogIn::board_voltage (void) pure virtual
Implemented in ESP32::AnalogIn, AnalogIn_ADS1115, ChibiOS::AnalogIn, Empty::AnalogIn, AnalogIn_IIO, AnalogIn_Navio2, and HALSITL::AnalogIn.
Referenced by AP_Airspeed_MS4525::_voltage_correction(), AP_Arming::board_voltage_checks(), GCS_MAVLINK::send_hwstatus(), GCS_MAVLINK::send_power_status(), and AP_Logger::Write_Power().
channel()
virtual AP_HAL::AnalogSource * AP_HAL::AnalogIn::channel (int16_t n) pure virtual
Implemented in Empty::AnalogIn, AnalogIn_ADS1115, AnalogIn_IIO, AnalogIn_Navio2, HALSITL::AnalogIn, ChibiOS::AnalogIn, and ESP32::AnalogIn.
Referenced by AP_Airspeed_Analog::AP_Airspeed_Analog(), AP_BattMonitor_Analog::AP_BattMonitor_Analog(), AP_BattMonitor_Synthetic_Current::AP_BattMonitor_Synthetic_Current(), AP_LeakDetector_Analog::AP_LeakDetector_Analog(), AP_RangeFinder_analog::AP_RangeFinder_analog(), AP_WindVane_Analog::AP_WindVane_Analog(), AP_WindVane_ModernDevice::AP_WindVane_ModernDevice(), AP_RSSI::init(), and setup().
init()
virtual void AP_HAL::AnalogIn::init () pure virtual
Implemented in ChibiOS::AnalogIn, Empty::AnalogIn, ESP32::AnalogIn, AnalogIn_ADS1115, AnalogIn_IIO, AnalogIn_Navio2, and HALSITL::AnalogIn.
Referenced by ESP32::Scheduler::_main_thread(), main_loop(), HAL_Linux::run(), and HAL_SITL::run().
power_status_flags()
virtual uint16_t AP_HAL::AnalogIn::power_status_flags (void) inline virtual
Reimplemented in ChibiOS::AnalogIn.
Definition at line 39 of file AnalogIn.h.
Referenced by GCS_MAVLINK::send_power_status(), and AP_Logger::Write_Power().
servorail_voltage()
virtual float AP_HAL::AnalogIn::servorail_voltage (void) inline virtual
Reimplemented in ChibiOS::AnalogIn, and AnalogIn_Navio2.
Definition at line 36 of file AnalogIn.h.
Referenced by AP_Arming::board_voltage_checks(), GCS_MAVLINK::send_power_status(), and AP_Logger::Write_Power().
The documentation for this class was generated from the following file:
libraries/AP_HAL/AnalogIn.h