APM:Libraries: Linux::I2CDeviceManager Class Reference
Linux::I2CDeviceManager Class Reference
#include <I2CDevice.h>
Public Member Functions
I2CDeviceManager ()
AP_HAL::OwnPtr< AP_HAL::I2CDevice > get_device (std::vector< const char * > devpaths, uint8_t address) override
AP_HAL::OwnPtr< AP_HAL::I2CDevice > get_device (uint8_t bus, uint8_t address, uint32_t bus_clock=400000, bool use_smbus=false, uint32_t timeout_ms=4) override
void teardown ()
uint32_t get_bus_mask (void) const override
uint32_t get_bus_mask_external (void) const override
uint32_t get_bus_mask_internal (void) const override
Static Public Member Functions
static I2CDeviceManager * from (AP_HAL::I2CDeviceManager *i2c_mgr)
Protected Member Functions
void _unregister (I2CBus &b)
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _create_device (I2CBus &b, uint8_t address) const
Protected Attributes
std::vector< I2CBus * > _buses
Friends
class I2CDevice
Detailed Description
Definition at line 86 of file I2CDevice.h.
Constructor & Destructor Documentation
I2CDeviceManager()
Linux::I2CDeviceManager::I2CDeviceManager ()
Definition at line 277 of file I2CDevice.cpp.
Member Function Documentation
_create_device()
AP_HAL::OwnPtr< AP_HAL::I2CDevice > Linux::I2CDeviceManager::_create_device (I2CBus & b, uint8_t address) const protected
Definition at line 378 of file I2CDevice.cpp.
Referenced by get_device().
_unregister()
void Linux::I2CDeviceManager::_unregister (I2CBus & b) protected
Definition at line 388 of file I2CDevice.cpp.
Referenced by Linux::I2CDevice::~I2CDevice().
from()
static I2CDeviceManager * Linux::I2CDeviceManager::from (AP_HAL::I2CDeviceManager * i2c_mgr) inline static
Definition at line 90 of file I2CDevice.h.
Referenced by HAL_Linux::run(), and Linux::I2CDevice::~I2CDevice().
get_bus_mask()
uint32_t Linux::I2CDeviceManager::get_bus_mask (void) const override virtual
Reimplemented from AP_HAL::I2CDeviceManager.
Definition at line 419 of file I2CDevice.cpp.
get_bus_mask_external()
uint32_t Linux::I2CDeviceManager::get_bus_mask_external (void) const override virtual
Reimplemented from AP_HAL::I2CDeviceManager.
Definition at line 435 of file I2CDevice.cpp.
get_bus_mask_internal()
uint32_t Linux::I2CDeviceManager::get_bus_mask_internal (void) const override virtual
Reimplemented from AP_HAL::I2CDeviceManager.
Definition at line 427 of file I2CDevice.cpp.
get_device() [1/2]
AP_HAL::OwnPtr< AP_HAL::I2CDevice > Linux::I2CDeviceManager::get_device (std::vector< const char * > devpaths, uint8_t address) override virtual
Reimplemented from AP_HAL::I2CDeviceManager.
Definition at line 284 of file I2CDevice.cpp.
Referenced by get_device().
get_device() [2/2]
AP_HAL::OwnPtr< AP_HAL::I2CDevice > Linux::I2CDeviceManager::get_device (uint8_t bus, uint8_t address, uint32_t bus_clock = 400000, bool use_smbus = false, uint32_t timeout_ms = 4) override virtual
Implements AP_HAL::I2CDeviceManager.
Definition at line 345 of file I2CDevice.cpp.
teardown()
void Linux::I2CDeviceManager::teardown ()
Definition at line 403 of file I2CDevice.cpp.
Referenced by HAL_Linux::run().
Friends And Related Symbol Documentation
I2CDevice
friend class I2CDevice friend
Definition at line 88 of file I2CDevice.h.
Referenced by _create_device().
Member Data Documentation
_buses
std::vector<I2CBus*> Linux::I2CDeviceManager::_buses protected
Definition at line 132 of file I2CDevice.h.
Referenced by _unregister(), get_device(), I2CDeviceManager(), and teardown().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/I2CDevice.h
libraries/AP_HAL_Linux/I2CDevice.cpp