APM:Libraries: AP_Airspeed_Backend Class Reference
AP_Airspeed_Backend Class Reference abstract
#include <AP_Airspeed_Backend.h>
Public Member Functions
AP_Airspeed_Backend (AP_Airspeed &frontend, uint8_t instance)
virtual ~AP_Airspeed_Backend ()
virtual bool init (void)=0
virtual bool get_differential_pressure (float &pressure)
virtual bool get_temperature (float &temperature)=0
virtual bool has_airspeed ()
virtual bool get_airspeed (float &airspeed)
virtual void handle_msp (const MSP::msp_airspeed_data_message_t &pkt)
Protected Types
enum class DevType {
SITL = 0x01 , MS4525 = 0x02 , MS5525 = 0x03 , DLVR = 0x04 ,
MSP = 0x05 , SDP3X = 0x06 , UAVCAN = 0x07 , ANALOG = 0x08 ,
NMEA = 0x09 , ASP5033 = 0x0A
}
Protected Member Functions
int8_t get_pin (void) const
float get_psi_range (void) const
uint8_t get_bus (void) const
bool bus_is_configured (void) const
uint8_t get_instance (void) const
bool disable_voltage_correction (void) const
AP_Airspeed::pitot_tube_order get_tube_order (void) const
float get_airspeed_ratio (void) const
void set_use_zero_offset (void)
void set_skip_cal (void)
void set_offset (float ofs)
void set_use (int8_t use)
void set_bus_id (uint32_t id)
Protected Attributes
HAL_Semaphore sem
Private Attributes
AP_Airspeed & frontend
uint8_t instance
Detailed Description
Definition at line 31 of file AP_Airspeed_Backend.h.
Member Enumeration Documentation
DevType
enum class AP_Airspeed_Backend::DevType strong protected
Enumerator
SITL
MS4525
MS5525
DLVR
MSP
SDP3X
UAVCAN
ANALOG
NMEA
ASP5033
Definition at line 119 of file AP_Airspeed_Backend.h.
Constructor & Destructor Documentation
AP_Airspeed_Backend()
AP_Airspeed_Backend::AP_Airspeed_Backend (AP_Airspeed & frontend, uint8_t instance)
Definition at line 31 of file AP_Airspeed_Backend.cpp.
~AP_Airspeed_Backend()
AP_Airspeed_Backend::~AP_Airspeed_Backend (void) virtual
Definition at line 37 of file AP_Airspeed_Backend.cpp.
Member Function Documentation
bus_is_configured()
bool AP_Airspeed_Backend::bus_is_configured (void) const protected
Definition at line 61 of file AP_Airspeed_Backend.cpp.
Referenced by AP_Airspeed_MS4525::init().
disable_voltage_correction()
bool AP_Airspeed_Backend::disable_voltage_correction (void) const inline protected
Definition at line 71 of file AP_Airspeed_Backend.h.
Referenced by AP_Airspeed_MS4525::_collect().
get_airspeed()
virtual bool AP_Airspeed_Backend::get_airspeed (float & airspeed) inline virtual
Reimplemented in AP_Airspeed_NMEA.
Definition at line 49 of file AP_Airspeed_Backend.h.
Referenced by AP_Airspeed::read().
get_airspeed_ratio()
float AP_Airspeed_Backend::get_airspeed_ratio (void) const inline protected
Definition at line 86 of file AP_Airspeed_Backend.h.
Referenced by AP_Airspeed_SDP3X::_correct_pressure().
get_bus()
uint8_t AP_Airspeed_Backend::get_bus (void) const protected
Definition at line 56 of file AP_Airspeed_Backend.cpp.
Referenced by AP_Airspeed_ASP5033::init(), AP_Airspeed_DLVR::init(), AP_Airspeed_MS4525::init(), AP_Airspeed_MS5525::init(), and AP_Airspeed_SDP3X::init().
get_differential_pressure()
virtual bool AP_Airspeed_Backend::get_differential_pressure (float & pressure) inline virtual
Reimplemented in AP_Airspeed_ASP5033, AP_Airspeed_Analog, AP_Airspeed_DLVR, AP_Airspeed_MS4525, AP_Airspeed_MS5525, and AP_Airspeed_SDP3X.
Definition at line 40 of file AP_Airspeed_Backend.h.
Referenced by AP_Airspeed::get_pressure().
get_instance()
uint8_t AP_Airspeed_Backend::get_instance (void) const inline protected
Definition at line 66 of file AP_Airspeed_Backend.h.
Referenced by AP_Airspeed_MS4525::init(), AP_Airspeed_MS5525::init(), and AP_Airspeed_SDP3X::init().
get_pin()
int8_t AP_Airspeed_Backend::get_pin (void) const protected
Definition at line 42 of file AP_Airspeed_Backend.cpp.
Referenced by AP_Airspeed_Analog::AP_Airspeed_Analog(), and AP_Airspeed_Analog::get_differential_pressure().
get_psi_range()
float AP_Airspeed_Backend::get_psi_range (void) const protected
Definition at line 51 of file AP_Airspeed_Backend.cpp.
Referenced by AP_Airspeed_MS4525::_get_pressure(), and AP_Airspeed_Analog::get_differential_pressure().
get_temperature()
virtual bool AP_Airspeed_Backend::get_temperature (float & temperature) pure virtual
Implemented in AP_Airspeed_ASP5033, AP_Airspeed_Analog, AP_Airspeed_DLVR, AP_Airspeed_MS4525, AP_Airspeed_MS5525, AP_Airspeed_NMEA, and AP_Airspeed_SDP3X.
Referenced by AP_Airspeed::get_temperature().
get_tube_order()
AP_Airspeed::pitot_tube_order AP_Airspeed_Backend::get_tube_order (void) const inline protected
Definition at line 75 of file AP_Airspeed_Backend.h.
Referenced by AP_Airspeed_SDP3X::_correct_pressure().
handle_msp()
virtual void AP_Airspeed_Backend::handle_msp (const MSP::msp_airspeed_data_message_t & pkt) inline virtual
Definition at line 51 of file AP_Airspeed_Backend.h.
has_airspeed()
virtual bool AP_Airspeed_Backend::has_airspeed () inline virtual
Reimplemented in AP_Airspeed_NMEA.
Definition at line 46 of file AP_Airspeed_Backend.h.
init()
virtual bool AP_Airspeed_Backend::init (void) pure virtual
Implemented in AP_Airspeed_ASP5033, AP_Airspeed_DLVR, AP_Airspeed_MS4525, AP_Airspeed_MS5525, AP_Airspeed_SDP3X, AP_Airspeed_Analog, and AP_Airspeed_NMEA.
set_bus_id()
void AP_Airspeed_Backend::set_bus_id (uint32_t id) protected
Definition at line 66 of file AP_Airspeed_Backend.cpp.
Referenced by AP_Airspeed_ASP5033::init(), AP_Airspeed_MS4525::init(), AP_Airspeed_MS5525::init(), AP_Airspeed_SDP3X::init(), and AP_Airspeed_DLVR::setup().
set_offset()
void AP_Airspeed_Backend::set_offset (float ofs) inline protected
Definition at line 103 of file AP_Airspeed_Backend.h.
Referenced by AP_Airspeed_SDP3X::init().
set_skip_cal()
void AP_Airspeed_Backend::set_skip_cal (void) inline protected
Definition at line 96 of file AP_Airspeed_Backend.h.
Referenced by AP_Airspeed_SDP3X::init().
set_use()
void AP_Airspeed_Backend::set_use (int8_t use) inline protected
Definition at line 110 of file AP_Airspeed_Backend.h.
set_use_zero_offset()
void AP_Airspeed_Backend::set_use_zero_offset (void) inline protected
Definition at line 91 of file AP_Airspeed_Backend.h.
Referenced by AP_Airspeed_SDP3X::init().
Member Data Documentation
frontend
AP_Airspeed& AP_Airspeed_Backend::frontend private
Definition at line 133 of file AP_Airspeed_Backend.h.
Referenced by bus_is_configured(), disable_voltage_correction(), get_airspeed_ratio(), get_bus(), get_pin(), get_psi_range(), get_tube_order(), set_bus_id(), set_offset(), set_skip_cal(), set_use(), and set_use_zero_offset().
instance
uint8_t AP_Airspeed_Backend::instance private
Definition at line 134 of file AP_Airspeed_Backend.h.
Referenced by bus_is_configured(), get_airspeed_ratio(), get_bus(), get_instance(), get_pin(), get_psi_range(), get_tube_order(), set_bus_id(), set_offset(), set_skip_cal(), set_use(), and set_use_zero_offset().
sem
HAL_Semaphore AP_Airspeed_Backend::sem protected
Definition at line 84 of file AP_Airspeed_Backend.h.
Referenced by AP_Airspeed_MS4525::_collect(), AP_Airspeed_SDP3X::_timer(), AP_Airspeed_MS5525::calculate(), AP_Airspeed_ASP5033::get_differential_pressure(), AP_Airspeed_DLVR::get_differential_pressure(), AP_Airspeed_MS4525::get_differential_pressure(), AP_Airspeed_MS5525::get_differential_pressure(), AP_Airspeed_SDP3X::get_differential_pressure(), AP_Airspeed_ASP5033::get_temperature(), AP_Airspeed_DLVR::get_temperature(), AP_Airspeed_MS4525::get_temperature(), AP_Airspeed_MS5525::get_temperature(), AP_Airspeed_SDP3X::get_temperature(), AP_Airspeed_ASP5033::timer(), and AP_Airspeed_DLVR::timer().
The documentation for this class was generated from the following files:
libraries/AP_Airspeed/AP_Airspeed_Backend.h
libraries/AP_Airspeed/AP_Airspeed_Backend.cpp