APM:Libraries: AP_Beacon_Backend Class Reference
AP_Beacon_Backend Class Reference abstract
#include <AP_Beacon_Backend.h>
Public Member Functions
AP_Beacon_Backend (AP_Beacon &frontend)
virtual bool healthy ()=0
virtual void update ()=0
void set_vehicle_position (const Vector3f &pos, float accuracy_estimate)
void set_beacon_distance (uint8_t beacon_instance, float distance)
void set_beacon_position (uint8_t beacon_instance, const Vector3f &pos)
float get_beacon_origin_lat (void) const
float get_beacon_origin_lon (void) const
float get_beacon_origin_alt (void) const
Protected Member Functions
Vector3f correct_for_orient_yaw (const Vector3f &vector)
Protected Attributes
AP_Beacon & _frontend
int16_t orient_yaw_deg
float orient_cos_yaw = 0.0f
float orient_sin_yaw = 1.0f
AP_HAL::UARTDriver * uart
Detailed Description
Definition at line 25 of file AP_Beacon_Backend.h.
Constructor & Destructor Documentation
AP_Beacon_Backend()
AP_Beacon_Backend::AP_Beacon_Backend (AP_Beacon & frontend)
Definition at line 28 of file AP_Beacon_Backend.cpp.
Member Function Documentation
correct_for_orient_yaw()
Vector3f AP_Beacon_Backend::correct_for_orient_yaw (const Vector3f & vector) protected
Definition at line 87 of file AP_Beacon_Backend.cpp.
Referenced by set_beacon_position(), and set_vehicle_position().
get_beacon_origin_alt()
float AP_Beacon_Backend::get_beacon_origin_alt (void) const inline
Definition at line 51 of file AP_Beacon_Backend.h.
Referenced by AP_Beacon_SITL::update().
get_beacon_origin_lat()
float AP_Beacon_Backend::get_beacon_origin_lat (void) const inline
Definition at line 49 of file AP_Beacon_Backend.h.
Referenced by AP_Beacon_SITL::update().
get_beacon_origin_lon()
float AP_Beacon_Backend::get_beacon_origin_lon (void) const inline
Definition at line 50 of file AP_Beacon_Backend.h.
Referenced by AP_Beacon_SITL::update().
healthy()
virtual bool AP_Beacon_Backend::healthy () pure virtual
Implemented in AP_Beacon_Marvelmind, AP_Beacon_Nooploop, AP_Beacon_Pozyx, and AP_Beacon_SITL.
Referenced by AP_Beacon::healthy().
set_beacon_distance()
void AP_Beacon_Backend::set_beacon_distance (uint8_t beacon_instance, float distance)
Definition at line 51 of file AP_Beacon_Backend.cpp.
Referenced by AP_Beacon_Pozyx::parse_buffer(), AP_Beacon_Nooploop::parse_node_frame2(), AP_Beacon_Marvelmind::process_beacons_distances_datagram(), and AP_Beacon_SITL::update().
set_beacon_position()
void AP_Beacon_Backend::set_beacon_position (uint8_t beacon_instance, const Vector3f & pos)
Definition at line 70 of file AP_Beacon_Backend.cpp.
Referenced by AP_Beacon_Pozyx::parse_buffer(), AP_Beacon_Nooploop::parse_setting_frame0(), AP_Beacon_Marvelmind::set_stationary_beacons_positions(), and AP_Beacon_SITL::update().
set_vehicle_position()
void AP_Beacon_Backend::set_vehicle_position (const Vector3f & pos, float accuracy_estimate)
Definition at line 43 of file AP_Beacon_Backend.cpp.
Referenced by AP_Beacon_Pozyx::parse_buffer(), AP_Beacon_Nooploop::parse_node_frame2(), AP_Beacon_Marvelmind::set_stationary_beacons_positions(), and AP_Beacon_SITL::update().
update()
virtual void AP_Beacon_Backend::update () pure virtual
Implemented in AP_Beacon_Marvelmind, AP_Beacon_Nooploop, AP_Beacon_Pozyx, and AP_Beacon_SITL.
Referenced by AP_Beacon::update().
Member Data Documentation
_frontend
AP_Beacon& AP_Beacon_Backend::_frontend protected
Definition at line 56 of file AP_Beacon_Backend.h.
Referenced by correct_for_orient_yaw(), get_beacon_origin_alt(), get_beacon_origin_lat(), get_beacon_origin_lon(), set_beacon_distance(), set_beacon_position(), and set_vehicle_position().
orient_cos_yaw
float AP_Beacon_Backend::orient_cos_yaw = 0.0f protected
Definition at line 60 of file AP_Beacon_Backend.h.
Referenced by correct_for_orient_yaw().
orient_sin_yaw
float AP_Beacon_Backend::orient_sin_yaw = 1.0f protected
Definition at line 61 of file AP_Beacon_Backend.h.
Referenced by correct_for_orient_yaw().
orient_yaw_deg
int16_t AP_Beacon_Backend::orient_yaw_deg protected
Definition at line 59 of file AP_Beacon_Backend.h.
Referenced by correct_for_orient_yaw().
uart
AP_HAL::UARTDriver* AP_Beacon_Backend::uart protected
Definition at line 66 of file AP_Beacon_Backend.h.
Referenced by AP_Beacon_Nooploop::request_setting(), AP_Beacon_Marvelmind::update(), AP_Beacon_Nooploop::update(), and AP_Beacon_Pozyx::update().
The documentation for this class was generated from the following files:
libraries/AP_Beacon/AP_Beacon_Backend.h
libraries/AP_Beacon/AP_Beacon_Backend.cpp