APM:Libraries: SITL::JEDEC Class Reference
SITL::JEDEC Class Reference abstract
#include <SIM_JEDEC.h>
Public Member Functions
int rdwr (uint8_t count, SPI::spi_ioc_transfer *&data) override
Public Member Functions inherited from SITL::SPIDevice
virtual void init ()
virtual void update (const class Aircraft &aircraft)
Protected Member Functions
virtual void fill_rdid (uint8_t *buf, uint8_t len)=0
virtual void fill_rdsr (uint8_t *buf, uint8_t len)=0
virtual const char * filename () const =0
virtual uint8_t get_num_blocks () const =0
virtual uint16_t get_page_per_block () const =0
virtual uint8_t get_page_per_sector () const =0
virtual uint16_t get_page_size () const =0
uint32_t get_storage_size () const
uint32_t get_num_pages () const
Private Types
enum class State {
WAITING , READING_RDID , READING , WRITING ,
READING_RDSR
}
Private Member Functions
void sector4k_erase (uint32_t addr)
void block64k_erase (uint32_t addr)
void page_erase (uint32_t addr)
void bulk_erase ()
uint32_t parse_addr (uint8_t *buffer, uint32_t len)
void assert_writes_enabled ()
void open_storage_fd ()
Private Attributes
enum SITL::JEDEC::State state = State::WAITING
bool write_enabled
uint32_t xfr_addr
int storage_fd = -1
Detailed Description
Definition at line 15 of file SIM_JEDEC.h.
Member Enumeration Documentation
State
enum class SITL::JEDEC::State strong private
Enumerator
WAITING
READING_RDID
READING
WRITING
READING_RDSR
Definition at line 35 of file SIM_JEDEC.h.
Member Function Documentation
assert_writes_enabled()
void JEDEC::assert_writes_enabled () private
Definition at line 81 of file SIM_JEDEC.cpp.
Referenced by rdwr().
block64k_erase()
void JEDEC::block64k_erase (uint32_t addr) private
Definition at line 42 of file SIM_JEDEC.cpp.
Referenced by bulk_erase(), and rdwr().
bulk_erase()
void JEDEC::bulk_erase () private
Definition at line 64 of file SIM_JEDEC.cpp.
Referenced by rdwr().
filename()
virtual const char * SITL::JEDEC::filename () const protected pure virtual
Implemented in SITL::JEDEC_MX25L3206E.
Referenced by open_storage_fd().
fill_rdid()
virtual void SITL::JEDEC::fill_rdid (uint8_t * buf, uint8_t len) protected pure virtual
Implemented in SITL::JEDEC_MX25L3206E.
Referenced by rdwr().
fill_rdsr()
virtual void SITL::JEDEC::fill_rdsr (uint8_t * buf, uint8_t len) protected pure virtual
Implemented in SITL::JEDEC_MX25L3206E.
Referenced by rdwr().
get_num_blocks()
virtual uint8_t SITL::JEDEC::get_num_blocks () const protected pure virtual
Implemented in SITL::JEDEC_MX25L3206E.
Referenced by bulk_erase(), and get_num_pages().
get_num_pages()
uint32_t SITL::JEDEC::get_num_pages () const inline protected
Definition at line 31 of file SIM_JEDEC.h.
Referenced by get_storage_size().
get_page_per_block()
virtual uint16_t SITL::JEDEC::get_page_per_block () const protected pure virtual
Implemented in SITL::JEDEC_MX25L3206E.
Referenced by bulk_erase(), and get_num_pages().
get_page_per_sector()
virtual uint8_t SITL::JEDEC::get_page_per_sector () const protected pure virtual
Implemented in SITL::JEDEC_MX25L3206E.
Referenced by block64k_erase(), and sector4k_erase().
get_page_size()
virtual uint16_t SITL::JEDEC::get_page_size () const protected pure virtual
Implemented in SITL::JEDEC_MX25L3206E.
Referenced by block64k_erase(), bulk_erase(), get_storage_size(), page_erase(), and sector4k_erase().
get_storage_size()
uint32_t SITL::JEDEC::get_storage_size () const inline protected
Definition at line 30 of file SIM_JEDEC.h.
Referenced by open_storage_fd(), page_erase(), and rdwr().
open_storage_fd()
void JEDEC::open_storage_fd () private
Definition at line 17 of file SIM_JEDEC.cpp.
Referenced by rdwr().
page_erase()
void JEDEC::page_erase (uint32_t addr) private
Definition at line 50 of file SIM_JEDEC.cpp.
Referenced by sector4k_erase().
parse_addr()
uint32_t JEDEC::parse_addr (uint8_t * buffer, uint32_t len) private
Definition at line 71 of file SIM_JEDEC.cpp.
Referenced by rdwr().
rdwr()
int JEDEC::rdwr (uint8_t count, SPI::spi_ioc_transfer *& data) override virtual
Implements SITL::SPIDevice.
Definition at line 88 of file SIM_JEDEC.cpp.
sector4k_erase()
void JEDEC::sector4k_erase (uint32_t addr) private
Definition at line 35 of file SIM_JEDEC.cpp.
Referenced by block64k_erase(), and rdwr().
Member Data Documentation
state
enum SITL::JEDEC::State SITL::JEDEC::state = State::WAITING private
Referenced by rdwr().
storage_fd
int SITL::JEDEC::storage_fd = -1 private
Definition at line 53 of file SIM_JEDEC.h.
Referenced by open_storage_fd(), page_erase(), and rdwr().
write_enabled
bool SITL::JEDEC::write_enabled private
Definition at line 43 of file SIM_JEDEC.h.
Referenced by assert_writes_enabled(), and rdwr().
xfr_addr
uint32_t SITL::JEDEC::xfr_addr private
Definition at line 44 of file SIM_JEDEC.h.
Referenced by rdwr().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_JEDEC.h
libraries/SITL/SIM_JEDEC.cpp