APM:Libraries: SITL::PS_RPLidar Class Reference
SITL::PS_RPLidar Class Reference abstract
#include <SIM_PS_RPLidar.h>
Public Member Functions
uint32_t packet_for_location (const Location &location, uint8_t *data, uint8_t buflen) override
void update (const Location &location) override
SerialProximitySensor ()
Public Member Functions inherited from SITL::SerialProximitySensor
SerialProximitySensor ()
virtual uint16_t reading_interval_ms () const
float measure_distance_at_angle_bf (const Location &location, float angle) const
Public Member Functions inherited from SITL::SerialDevice
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Private Types
enum class State { IDLE = 17 , SCANNING = 18 }
enum class InputState { WAITING_FOR_PREAMBLE = 45 , GOT_PREAMBLE = 46 , RESETTING_START = 47 , RESETTING_SEND_FIRMWARE_INFO = 48 }
enum class Command {
STOP = 0x25 , SCAN = 0x20 , FORCE_SCAN = 0x21 , RESET = 0x40 ,
GET_DEVICE_INFO = 0x50 , GET_HEALTH = 0x52
}
enum class DataType { Unknown04 = 0x04 , Unknown06 = 0x06 , Unknown81 = 0x81 }
enum class SendMode { SRSR = 0x00 , SRMR = 0x40 }
Private Member Functions
void update_input ()
void update_output (const Location &location)
void update_output_scan (const Location &location)
void set_state (State newstate)
void set_inputstate (InputState newstate)
void move_preamble_in_buffer ()
void send_response_descriptor (uint32_t data_response_length, SendMode sendmode, DataType datatype)
virtual uint8_t device_info_model () const =0
virtual uint8_t max_range () const =0
Private Attributes
uint32_t last_scan_output_time_ms
float last_degrees_bf
char _buffer [256]
uint8_t _buflen
State _state = State::IDLE
InputState _inputstate = InputState::WAITING_FOR_PREAMBLE
uint8_t _firmware_info_offset
Static Private Attributes
static const uint8_t PREAMBLE = 0xA5
static const constexpr char * FIRMWARE_INFO = "R12345678901234567890123456789012345678901234567890123456789012"
Additional Inherited Members
Protected Member Functions inherited from SITL::SerialDevice
bool init_sitl_pointer () WARN_IF_UNUSED
Protected Attributes inherited from SITL::SerialDevice
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Detailed Description
Definition at line 58 of file SIM_PS_RPLidar.h.
Member Enumeration Documentation
Command
enum class SITL::PS_RPLidar::Command strong private
Enumerator
STOP
SCAN
FORCE_SCAN
RESET
GET_DEVICE_INFO
GET_HEALTH
Definition at line 107 of file SIM_PS_RPLidar.h.
DataType
enum class SITL::PS_RPLidar::DataType strong private
Enumerator
Unknown04
Unknown06
Unknown81
Definition at line 118 of file SIM_PS_RPLidar.h.
InputState
enum class SITL::PS_RPLidar::InputState strong private
Enumerator
WAITING_FOR_PREAMBLE
GOT_PREAMBLE
RESETTING_START
RESETTING_SEND_FIRMWARE_INFO
Definition at line 93 of file SIM_PS_RPLidar.h.
SendMode
enum class SITL::PS_RPLidar::SendMode strong private
Enumerator
SRSR
SRMR
Definition at line 124 of file SIM_PS_RPLidar.h.
State
enum class SITL::PS_RPLidar::State strong private
Enumerator
IDLE
SCANNING
Definition at line 83 of file SIM_PS_RPLidar.h.
Member Function Documentation
device_info_model()
virtual uint8_t SITL::PS_RPLidar::device_info_model () const private pure virtual
Implemented in SITL::PS_RPLidarA1, and SITL::PS_RPLidarA2.
Referenced by update_input().
max_range()
virtual uint8_t SITL::PS_RPLidar::max_range () const private pure virtual
Implemented in SITL::PS_RPLidarA1, and SITL::PS_RPLidarA2.
Referenced by update_output_scan().
move_preamble_in_buffer()
void PS_RPLidar::move_preamble_in_buffer () private
Definition at line 36 of file SIM_PS_RPLidar.cpp.
Referenced by update_input().
packet_for_location()
uint32_t PS_RPLidar::packet_for_location (const Location & location, uint8_t * data, uint8_t buflen) override virtual
Implements SITL::SerialProximitySensor.
Definition at line 29 of file SIM_PS_RPLidar.cpp.
send_response_descriptor()
void PS_RPLidar::send_response_descriptor (uint32_t data_response_length, SendMode sendmode, DataType datatype) private
Definition at line 239 of file SIM_PS_RPLidar.cpp.
Referenced by update_input().
SerialProximitySensor()
SITL::SerialProximitySensor::SerialProximitySensor () inline
Definition at line 36 of file SIM_SerialProximitySensor.h.
set_inputstate()
void SITL::PS_RPLidar::set_inputstate (InputState newstate) inline private
Definition at line 100 of file SIM_PS_RPLidar.h.
Referenced by update_input().
set_state()
void SITL::PS_RPLidar::set_state (State newstate) inline private
Definition at line 88 of file SIM_PS_RPLidar.h.
Referenced by update_input().
update()
void PS_RPLidar::update (const Location & location) override virtual
Reimplemented from SITL::SerialProximitySensor.
Definition at line 232 of file SIM_PS_RPLidar.cpp.
Referenced by HALSITL::SITL_State_Common::sim_update().
update_input()
void PS_RPLidar::update_input () private
Definition at line 51 of file SIM_PS_RPLidar.cpp.
Referenced by update().
update_output()
void PS_RPLidar::update_output (const Location & location) private
Definition at line 221 of file SIM_PS_RPLidar.cpp.
Referenced by update().
update_output_scan()
void PS_RPLidar::update_output_scan (const Location & location) private
< on the first revolution 1 else 0
< complementary to startbit
< Related the reflected laser pulse strength
< always set to 1
< Actual heading = angle_q6/64.0 Degree
< Actual Distance = distance_q2/4.0 mm
Definition at line 162 of file SIM_PS_RPLidar.cpp.
Referenced by update_output().
Member Data Documentation
_buffer
char SITL::PS_RPLidar::_buffer[256] private
Definition at line 79 of file SIM_PS_RPLidar.h.
Referenced by move_preamble_in_buffer(), and update_input().
_buflen
uint8_t SITL::PS_RPLidar::_buflen private
Definition at line 80 of file SIM_PS_RPLidar.h.
Referenced by move_preamble_in_buffer(), and update_input().
_firmware_info_offset
uint8_t SITL::PS_RPLidar::_firmware_info_offset private
Definition at line 136 of file SIM_PS_RPLidar.h.
Referenced by update_input().
_inputstate
InputState SITL::PS_RPLidar::_inputstate = InputState::WAITING_FOR_PREAMBLE private
Definition at line 99 of file SIM_PS_RPLidar.h.
Referenced by set_inputstate(), and update_input().
_state
State SITL::PS_RPLidar::_state = State::IDLE private
Definition at line 87 of file SIM_PS_RPLidar.h.
Referenced by set_state(), and update_output().
FIRMWARE_INFO
const constexpr char* SITL::PS_RPLidar::FIRMWARE_INFO = "R12345678901234567890123456789012345678901234567890123456789012" static constexpr private
Definition at line 135 of file SIM_PS_RPLidar.h.
Referenced by update_input().
last_degrees_bf
float SITL::PS_RPLidar::last_degrees_bf private
Definition at line 77 of file SIM_PS_RPLidar.h.
Referenced by update_output_scan().
last_scan_output_time_ms
uint32_t SITL::PS_RPLidar::last_scan_output_time_ms private
Definition at line 75 of file SIM_PS_RPLidar.h.
Referenced by update_output_scan().
PREAMBLE
const uint8_t SITL::PS_RPLidar::PREAMBLE = 0xA5 static private
Definition at line 105 of file SIM_PS_RPLidar.h.
Referenced by move_preamble_in_buffer().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_PS_RPLidar.h
libraries/SITL/SIM_PS_RPLidar.cpp