APM:Libraries: AP_Baro_ICP201XX Class Reference
AP_Baro_ICP201XX Class Reference
#include <AP_Baro_ICP201XX.h>
Public Member Functions
void update () override
Public Member Functions inherited from AP_Baro_Backend
AP_Baro_Backend (AP_Baro &baro)
virtual ~AP_Baro_Backend (void)
virtual void accumulate (void)
void backend_update (uint8_t instance)
bool pressure_ok (float press)
uint32_t get_error_count () const
Static Public Member Functions
static AP_Baro_Backend * probe (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
Private Types
enum class OP_MODE : uint8_t {
OP_MODE0 = 0 , OP_MODE1 , OP_MODE2 , OP_MODE3 ,
OP_MODE4
}
enum class FIFO_READOUT_MODE : uint8_t { FIFO_READOUT_MODE_PRES_TEMP = 0 , FIFO_READOUT_MODE_TEMP_ONLY = 1 , FIFO_READOUT_MODE_TEMP_PRES = 2 , FIFO_READOUT_MODE_PRES_ONLY = 3 }
enum class POWER_MODE : uint8_t { POWER_MODE_NORMAL = 0 , POWER_MODE_ACTIVE = 1 }
enum MEAS_MODE : uint8_t { MEAS_MODE_FORCED_TRIGGER = 0 , MEAS_MODE_CONTINUOUS = 1 }
enum FORCED_MEAS_TRIGGER : uint8_t { FORCE_MEAS_STANDBY = 0 , FORCE_MEAS_TRIGGER_FORCE_MEAS = 1 }
Private Member Functions
AP_Baro_ICP201XX (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
bool init ()
void dummy_reg ()
bool read_reg (uint8_t reg, uint8_t *buf, uint8_t len)
bool read_reg (uint8_t reg, uint8_t *val)
bool write_reg (uint8_t reg, uint8_t val)
bool mode_select (uint8_t mode)
bool read_otp_data (uint8_t addr, uint8_t cmd, uint8_t *val)
bool get_sensor_data (float *pressure, float *temperature)
void soft_reset ()
bool boot_sequence ()
bool configure ()
void wait_read ()
bool flush_fifo ()
void timer ()
Private Attributes
uint8_t instance
AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev
struct {
float tsum
float psum
uint32_t count
} accum
uint32_t last_measure_us
enum AP_Baro_ICP201XX::OP_MODE OP_MODE2
enum AP_Baro_ICP201XX::FIFO_READOUT_MODE FIFO_READOUT_MODE_PRES_TEMP
enum AP_Baro_ICP201XX::POWER_MODE POWER_MODE_NORMAL
enum AP_Baro_ICP201XX::MEAS_MODE MEAS_MODE_CONTINUOUS
enum AP_Baro_ICP201XX::FORCED_MEAS_TRIGGER FORCE_MEAS_STANDBY
Additional Inherited Members
Public Types inherited from AP_Baro_Backend
enum DevTypes {
DEVTYPE_BARO_SITL = 0x01 , DEVTYPE_BARO_BMP085 = 0x02 , DEVTYPE_BARO_BMP280 = 0x03 , DEVTYPE_BARO_BMP388 = 0x04 ,
DEVTYPE_BARO_DPS280 = 0x05 , DEVTYPE_BARO_DPS310 = 0x06 , DEVTYPE_BARO_FBM320 = 0x07 , DEVTYPE_BARO_ICM20789 = 0x08 ,
DEVTYPE_BARO_KELLERLD = 0x09 , DEVTYPE_BARO_LPS2XH = 0x0A , DEVTYPE_BARO_MS5611 = 0x0B , DEVTYPE_BARO_SPL06 = 0x0C ,
DEVTYPE_BARO_UAVCAN = 0x0D , DEVTYPE_BARO_MSP = 0x0E , DEVTYPE_BARO_ICP101XX = 0x0F , DEVTYPE_BARO_ICP201XX = 0x10 ,
DEVTYPE_BARO_MS5607 = 0x11 , DEVTYPE_BARO_MS5837 = 0x12 , DEVTYPE_BARO_MS5637 = 0x13 , DEVTYPE_BARO_BMP390 = 0x14
}
Protected Member Functions inherited from AP_Baro_Backend
void _copy_to_frontend (uint8_t instance, float pressure, float temperature)
virtual void update_healthy_flag (uint8_t instance)
void set_bus_id (uint8_t instance, uint32_t id)
Protected Attributes inherited from AP_Baro_Backend
AP_Baro & _frontend
HAL_Semaphore _sem
float _mean_pressure
uint32_t _error_count
Detailed Description
Definition at line 11 of file AP_Baro_ICP201XX.h.
Member Enumeration Documentation
FIFO_READOUT_MODE
enum class AP_Baro_ICP201XX::FIFO_READOUT_MODE : uint8_t strong private
Enumerator
FIFO_READOUT_MODE_PRES_TEMP
FIFO_READOUT_MODE_TEMP_ONLY
FIFO_READOUT_MODE_TEMP_PRES
FIFO_READOUT_MODE_PRES_ONLY
Definition at line 58 of file AP_Baro_ICP201XX.h.
FORCED_MEAS_TRIGGER
enum AP_Baro_ICP201XX::FORCED_MEAS_TRIGGER : uint8_t private
Enumerator
FORCE_MEAS_STANDBY
FORCE_MEAS_TRIGGER_FORCE_MEAS
Definition at line 75 of file AP_Baro_ICP201XX.h.
MEAS_MODE
enum AP_Baro_ICP201XX::MEAS_MODE : uint8_t private
Enumerator
MEAS_MODE_FORCED_TRIGGER
MEAS_MODE_CONTINUOUS
Definition at line 70 of file AP_Baro_ICP201XX.h.
OP_MODE
enum class AP_Baro_ICP201XX::OP_MODE : uint8_t strong private
Enumerator
OP_MODE0
OP_MODE1
OP_MODE2
OP_MODE3
OP_MODE4
Definition at line 50 of file AP_Baro_ICP201XX.h.
POWER_MODE
enum class AP_Baro_ICP201XX::POWER_MODE : uint8_t strong private
Enumerator
POWER_MODE_NORMAL
POWER_MODE_ACTIVE
Definition at line 65 of file AP_Baro_ICP201XX.h.
Constructor & Destructor Documentation
AP_Baro_ICP201XX()
AP_Baro_ICP201XX::AP_Baro_ICP201XX (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev) private
Definition at line 78 of file AP_Baro_ICP201XX.cpp.
Referenced by probe().
Member Function Documentation
boot_sequence()
bool AP_Baro_ICP201XX::boot_sequence () private
Definition at line 292 of file AP_Baro_ICP201XX.cpp.
Referenced by init().
configure()
bool AP_Baro_ICP201XX::configure () private
Definition at line 402 of file AP_Baro_ICP201XX.cpp.
Referenced by init().
dummy_reg()
void AP_Baro_ICP201XX::dummy_reg () private
Definition at line 152 of file AP_Baro_ICP201XX.cpp.
Referenced by read_reg(), and write_reg().
flush_fifo()
bool AP_Baro_ICP201XX::flush_fifo () private
Definition at line 449 of file AP_Baro_ICP201XX.cpp.
Referenced by get_sensor_data(), soft_reset(), timer(), and wait_read().
get_sensor_data()
bool AP_Baro_ICP201XX::get_sensor_data (float * pressure, float * temperature) private
Definition at line 247 of file AP_Baro_ICP201XX.cpp.
Referenced by timer().
init()
bool AP_Baro_ICP201XX::init () private
Definition at line 98 of file AP_Baro_ICP201XX.cpp.
Referenced by probe().
mode_select()
bool AP_Baro_ICP201XX::mode_select (uint8_t mode) private
Definition at line 198 of file AP_Baro_ICP201XX.cpp.
Referenced by boot_sequence(), configure(), and soft_reset().
probe()
AP_Baro_Backend * AP_Baro_ICP201XX::probe (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev) static
Definition at line 84 of file AP_Baro_ICP201XX.cpp.
read_otp_data()
bool AP_Baro_ICP201XX::read_otp_data (uint8_t addr, uint8_t cmd, uint8_t * val) private
Definition at line 215 of file AP_Baro_ICP201XX.cpp.
Referenced by boot_sequence().
read_reg() [1/2]
bool AP_Baro_ICP201XX::read_reg (uint8_t reg, uint8_t * buf, uint8_t len) private
Definition at line 161 of file AP_Baro_ICP201XX.cpp.
Referenced by boot_sequence(), flush_fifo(), get_sensor_data(), init(), mode_select(), read_otp_data(), read_reg(), and wait_read().
read_reg() [2/2]
bool AP_Baro_ICP201XX::read_reg (uint8_t reg, uint8_t * val) private
Definition at line 169 of file AP_Baro_ICP201XX.cpp.
soft_reset()
void AP_Baro_ICP201XX::soft_reset () private
Definition at line 183 of file AP_Baro_ICP201XX.cpp.
Referenced by init().
timer()
void AP_Baro_ICP201XX::timer () private
Definition at line 466 of file AP_Baro_ICP201XX.cpp.
Referenced by init().
update()
void AP_Baro_ICP201XX::update (void) override virtual
Implements AP_Baro_Backend.
Definition at line 486 of file AP_Baro_ICP201XX.cpp.
wait_read()
void AP_Baro_ICP201XX::wait_read () private
Definition at line 424 of file AP_Baro_ICP201XX.cpp.
Referenced by init().
write_reg()
bool AP_Baro_ICP201XX::write_reg (uint8_t reg, uint8_t val) private
Definition at line 174 of file AP_Baro_ICP201XX.cpp.
Referenced by boot_sequence(), flush_fifo(), mode_select(), read_otp_data(), and soft_reset().
Member Data Documentation
[struct]
struct { ... } AP_Baro_ICP201XX::accum
Referenced by timer(), and update().
count
uint32_t AP_Baro_ICP201XX::count
Definition at line 44 of file AP_Baro_ICP201XX.h.
dev
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_Baro_ICP201XX::dev private
Definition at line 38 of file AP_Baro_ICP201XX.h.
Referenced by dummy_reg(), init(), probe(), read_reg(), and write_reg().
FIFO_READOUT_MODE_PRES_TEMP
enum AP_Baro_ICP201XX::FIFO_READOUT_MODE AP_Baro_ICP201XX::FIFO_READOUT_MODE_PRES_TEMP private
FORCE_MEAS_STANDBY
enum AP_Baro_ICP201XX::FORCED_MEAS_TRIGGER AP_Baro_ICP201XX::FORCE_MEAS_STANDBY private
instance
uint8_t AP_Baro_ICP201XX::instance private
Definition at line 36 of file AP_Baro_ICP201XX.h.
Referenced by init(), and update().
last_measure_us
uint32_t AP_Baro_ICP201XX::last_measure_us private
Definition at line 48 of file AP_Baro_ICP201XX.h.
Referenced by timer().
MEAS_MODE_CONTINUOUS
enum AP_Baro_ICP201XX::MEAS_MODE AP_Baro_ICP201XX::MEAS_MODE_CONTINUOUS private
OP_MODE2
enum AP_Baro_ICP201XX::OP_MODE AP_Baro_ICP201XX::OP_MODE2 private
POWER_MODE_NORMAL
enum AP_Baro_ICP201XX::POWER_MODE AP_Baro_ICP201XX::POWER_MODE_NORMAL private
psum
float AP_Baro_ICP201XX::psum
Definition at line 43 of file AP_Baro_ICP201XX.h.
tsum
float AP_Baro_ICP201XX::tsum
Definition at line 42 of file AP_Baro_ICP201XX.h.
The documentation for this class was generated from the following files:
libraries/AP_Baro/AP_Baro_ICP201XX.h
libraries/AP_Baro/AP_Baro_ICP201XX.cpp