APM:Libraries: AP_InertialSensor_LSM9DS0 Class Reference
AP_InertialSensor_LSM9DS0 Class Reference
#include <AP_InertialSensor_LSM9DS0.h>
Classes
struct sensor_raw_data
Public Member Functions
virtual ~AP_InertialSensor_LSM9DS0 ()
void start (void) override
bool update () override
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void accumulate ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t get_id () const
float get_clip_limit () const
virtual bool get_output_banner (char *banner, uint8_t banner_len)
Static Public Member Functions
static AP_InertialSensor_Backend * probe (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::Device > dev_gyro, AP_HAL::OwnPtr< AP_HAL::Device > dev_accel, enum Rotation rotation_a, enum Rotation rotation_g, enum Rotation rotation_gH)
Private Types
enum gyro_scale { G_SCALE_245DPS = 0 , G_SCALE_500DPS , G_SCALE_2000DPS }
enum accel_scale {
A_SCALE_2G = 0 , A_SCALE_4G , A_SCALE_6G , A_SCALE_8G ,
A_SCALE_16G
}
Private Member Functions
AP_InertialSensor_LSM9DS0 (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::Device > dev_gyro, AP_HAL::OwnPtr< AP_HAL::Device > dev_accel, int drdy_pin_num_a, int drdy_pin_num_b, enum Rotation rotation_a, enum Rotation rotation_g, enum Rotation rotation_gH)
bool _accel_data_ready ()
bool _gyro_data_ready ()
void _poll_data ()
bool _init_sensor ()
bool _hardware_init ()
void _gyro_init ()
void _accel_init ()
void _gyro_disable_i2c ()
void _accel_disable_i2c ()
void _set_gyro_scale (gyro_scale scale)
void _set_accel_scale (accel_scale scale)
uint8_t _register_read_xm (uint8_t reg)
uint8_t _register_read_g (uint8_t reg)
void _register_write_xm (uint8_t reg, uint8_t val, bool checked=false)
void _register_write_g (uint8_t reg, uint8_t val, bool checked=false)
void _read_data_transaction_a ()
void _read_data_transaction_g ()
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _dev_gyro
AP_HAL::OwnPtr< AP_HAL::Device > _dev_accel
AP_HAL::Semaphore * _spi_sem
AP_HAL::DigitalSource * _drdy_pin_a
AP_HAL::DigitalSource * _drdy_pin_g
float _gyro_scale
float _accel_scale
int _drdy_pin_num_a
int _drdy_pin_num_g
uint8_t _gyro_instance
uint8_t _accel_instance
float _temperature
uint8_t _temp_counter
LowPassFilter2pFloat _temp_filter
uint8_t whoami_g
enum Rotation _rotation_a
enum Rotation _rotation_g
enum Rotation _rotation_gH
Additional Inherited Members
Public Types inherited from AP_InertialSensor_Backend
enum DevTypes {
DEVTYPE_BMI160 = 0x09 , DEVTYPE_L3G4200D = 0x10 , DEVTYPE_ACC_LSM303D = 0x11 , DEVTYPE_ACC_BMA180 = 0x12 ,
DEVTYPE_ACC_MPU6000 = 0x13 , DEVTYPE_ACC_MPU9250 = 0x16 , DEVTYPE_ACC_IIS328DQ = 0x17 , DEVTYPE_ACC_LSM9DS1 = 0x18 ,
DEVTYPE_GYR_MPU6000 = 0x21 , DEVTYPE_GYR_L3GD20 = 0x22 , DEVTYPE_GYR_MPU9250 = 0x24 , DEVTYPE_GYR_I3G4250D = 0x25 ,
DEVTYPE_GYR_LSM9DS1 = 0x26 , DEVTYPE_INS_ICM20789 = 0x27 , DEVTYPE_INS_ICM20689 = 0x28 , DEVTYPE_INS_BMI055 = 0x29 ,
DEVTYPE_SITL = 0x2A , DEVTYPE_INS_BMI088 = 0x2B , DEVTYPE_INS_ICM20948 = 0x2C , DEVTYPE_INS_ICM20648 = 0x2D ,
DEVTYPE_INS_ICM20649 = 0x2E , DEVTYPE_INS_ICM20602 = 0x2F , DEVTYPE_INS_ICM20601 = 0x30 , DEVTYPE_INS_ADIS1647X = 0x31 ,
DEVTYPE_SERIAL = 0x32 , DEVTYPE_INS_ICM40609 = 0x33 , DEVTYPE_INS_ICM42688 = 0x34 , DEVTYPE_INS_ICM42605 = 0x35 ,
DEVTYPE_INS_ICM40605 = 0x36 , DEVTYPE_INS_IIM42652 = 0x37 , DEVTYPE_BMI270 = 0x38 , DEVTYPE_INS_BMI085 = 0x39 ,
DEVTYPE_INS_ICM42670 = 0x3A , DEVTYPE_INS_ICM45686 = 0x3B , DEVTYPE_INS_SCHA63T = 0x3C
}
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel) __RAMFUNC__
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro) __RAMFUNC__
void _publish_gyro (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void apply_gyro_filters (const uint8_t instance, const Vector3f &gyro)
void save_gyro_window (const uint8_t instance, const Vector3f &gyro, uint8_t phase)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0) __RAMFUNC__
void _notify_new_delta_angle (uint8_t instance, const Vector3f &dangle)
void _publish_accel (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0, bool fsync_set=false) __RAMFUNC__
void _notify_new_delta_velocity (uint8_t instance, const Vector3f &dvelocity)
void _set_accel_oversampling (uint8_t instance, uint8_t n)
void _set_gyro_oversampling (uint8_t instance, uint8_t n)
void _set_accel_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_gyro_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_raw_sample_accel_multiplier (uint8_t instance, uint16_t mul)
void _set_raw_sample_gyro_multiplier (uint8_t instance, uint16_t mul)
void _update_sensor_rate (uint16_t &count, uint32_t &start_us, float &rate_hz) const __RAMFUNC__
bool sensors_converging () const
void _set_accel_max_abs_offset (uint8_t instance, float offset)
float _accel_raw_sample_rate (uint8_t instance) const
void _set_accel_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
float _gyro_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
void _publish_temperature (uint8_t instance, float temperature)
void _inc_accel_error_count (uint8_t instance) __RAMFUNC__
void _inc_gyro_error_count (uint8_t instance) __RAMFUNC__
uint16_t _accel_filter_cutoff (void) const
uint16_t _gyro_filter_cutoff (void) const
uint16_t get_loop_rate_hz (void) const
void update_gyro (uint8_t instance) __RAMFUNC__
void update_accel (uint8_t instance) __RAMFUNC__
void set_gyro_orientation (uint8_t instance, enum Rotation rotation)
void set_accel_orientation (uint8_t instance, enum Rotation rotation)
void increment_clip_count (uint8_t instance)
bool enable_fast_sampling (uint8_t instance) const
bool enable_highres_sampling (uint8_t instance) const
uint8_t get_fast_sampling_rate () const
void _notify_new_accel_sensor_rate_sample (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_gyro_sensor_rate_sample (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void notify_accel_fifo_reset (uint8_t instance) __RAMFUNC__
void notify_gyro_fifo_reset (uint8_t instance) __RAMFUNC__
void log_register_change (uint32_t bus_id, const AP_HAL::Device::checkreg &reg) __RAMFUNC__
void Write_GYR (const uint8_t instance, const uint64_t sample_us, const Vector3f &gyro, bool use_sample_timestamp=false) const __RAMFUNC__
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
HAL_Semaphore _sem
float _clip_limit = 15.5f * GRAVITY_MSS
int16_t _id = -1
uint16_t _last_accel_filter_hz
uint16_t _last_gyro_filter_hz
Detailed Description
Definition at line 12 of file AP_InertialSensor_LSM9DS0.h.
Member Enumeration Documentation
accel_scale
enum AP_InertialSensor_LSM9DS0::accel_scale private
Enumerator
A_SCALE_2G
A_SCALE_4G
A_SCALE_6G
A_SCALE_8G
A_SCALE_16G
Definition at line 47 of file AP_InertialSensor_LSM9DS0.h.
gyro_scale
enum AP_InertialSensor_LSM9DS0::gyro_scale private
Enumerator
G_SCALE_245DPS
G_SCALE_500DPS
G_SCALE_2000DPS
Definition at line 41 of file AP_InertialSensor_LSM9DS0.h.
Constructor & Destructor Documentation
~AP_InertialSensor_LSM9DS0()
virtual AP_InertialSensor_LSM9DS0::~AP_InertialSensor_LSM9DS0 () inline virtual
Definition at line 15 of file AP_InertialSensor_LSM9DS0.h.
AP_InertialSensor_LSM9DS0()
AP_InertialSensor_LSM9DS0::AP_InertialSensor_LSM9DS0 (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::Device > dev_gyro, AP_HAL::OwnPtr< AP_HAL::Device > dev_accel, int drdy_pin_num_a, int drdy_pin_num_b, enum Rotation rotation_a, enum Rotation rotation_g, enum Rotation rotation_gH) private
Definition at line 374 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by probe().
Member Function Documentation
_accel_data_ready()
bool AP_InertialSensor_LSM9DS0::_accel_data_ready () private
Definition at line 711 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init(), and _poll_data().
_accel_disable_i2c()
void AP_InertialSensor_LSM9DS0::_accel_disable_i2c () private
Definition at line 576 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _accel_init().
_accel_init()
void AP_InertialSensor_LSM9DS0::_accel_init () private
Definition at line 620 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init().
_gyro_data_ready()
bool AP_InertialSensor_LSM9DS0::_gyro_data_ready () private
Definition at line 721 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init(), and _poll_data().
_gyro_disable_i2c()
void AP_InertialSensor_LSM9DS0::_gyro_disable_i2c () private
Definition at line 562 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _gyro_init().
_gyro_init()
void AP_InertialSensor_LSM9DS0::_gyro_init () private
Definition at line 588 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init().
_hardware_init()
bool AP_InertialSensor_LSM9DS0::_hardware_init () private
Definition at line 451 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor().
_init_sensor()
bool AP_InertialSensor_LSM9DS0::_init_sensor () private
Definition at line 416 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by probe().
_poll_data()
void AP_InertialSensor_LSM9DS0::_poll_data () private
Timer process to poll for new data from the LSM9DS0.
Definition at line 690 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by start().
_read_data_transaction_a()
void AP_InertialSensor_LSM9DS0::_read_data_transaction_a () private
Definition at line 731 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _poll_data().
_read_data_transaction_g()
void AP_InertialSensor_LSM9DS0::_read_data_transaction_g () private
Definition at line 760 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _poll_data().
_register_read_g()
uint8_t AP_InertialSensor_LSM9DS0::_register_read_g (uint8_t reg) private
Definition at line 543 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _gyro_data_ready(), _gyro_disable_i2c(), and _hardware_init().
_register_read_xm()
uint8_t AP_InertialSensor_LSM9DS0::_register_read_xm (uint8_t reg) private
Definition at line 534 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _accel_data_ready(), _accel_disable_i2c(), _accel_init(), and _hardware_init().
_register_write_g()
void AP_InertialSensor_LSM9DS0::_register_write_g (uint8_t reg, uint8_t val, bool checked = false) private
Definition at line 557 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _gyro_disable_i2c(), and _gyro_init().
_register_write_xm()
void AP_InertialSensor_LSM9DS0::_register_write_xm (uint8_t reg, uint8_t val, bool checked = false) private
Definition at line 552 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _accel_disable_i2c(), and _accel_init().
_set_accel_scale()
void AP_InertialSensor_LSM9DS0::_set_accel_scale (accel_scale scale) private
Definition at line 671 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _accel_init().
_set_gyro_scale()
void AP_InertialSensor_LSM9DS0::_set_gyro_scale (gyro_scale scale) private
Definition at line 650 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _gyro_init().
probe()
AP_InertialSensor_Backend * AP_InertialSensor_LSM9DS0::probe (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::Device > dev_gyro, AP_HAL::OwnPtr< AP_HAL::Device > dev_accel, enum Rotation rotation_a, enum Rotation rotation_g, enum Rotation rotation_gH) static
Definition at line 394 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by AP_InertialSensor::detect_backends().
start()
void AP_InertialSensor_LSM9DS0::start (void) override virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 513 of file AP_InertialSensor_LSM9DS0.cpp.
update()
bool AP_InertialSensor_LSM9DS0::update (void) override virtual
Implements AP_InertialSensor_Backend.
Definition at line 777 of file AP_InertialSensor_LSM9DS0.cpp.
Member Data Documentation
_accel_instance
uint8_t AP_InertialSensor_LSM9DS0::_accel_instance private
Definition at line 101 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _poll_data(), _read_data_transaction_a(), start(), and update().
_accel_scale
float AP_InertialSensor_LSM9DS0::_accel_scale private
Definition at line 97 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_a(), and _set_accel_scale().
_dev_accel
AP_HAL::OwnPtr<AP_HAL::Device> AP_InertialSensor_LSM9DS0::_dev_accel private
Definition at line 85 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _hardware_init(), _poll_data(), _read_data_transaction_a(), _register_read_xm(), _register_write_xm(), and start().
_dev_gyro
AP_HAL::OwnPtr<AP_HAL::Device> AP_InertialSensor_LSM9DS0::_dev_gyro private
Definition at line 84 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _hardware_init(), _init_sensor(), _poll_data(), _read_data_transaction_g(), _register_read_g(), _register_write_g(), and start().
_drdy_pin_a
AP_HAL::DigitalSource* AP_InertialSensor_LSM9DS0::_drdy_pin_a private
Definition at line 94 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _accel_data_ready(), and _init_sensor().
_drdy_pin_g
AP_HAL::DigitalSource* AP_InertialSensor_LSM9DS0::_drdy_pin_g private
Definition at line 95 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _gyro_data_ready(), and _init_sensor().
_drdy_pin_num_a
int AP_InertialSensor_LSM9DS0::_drdy_pin_num_a private
Definition at line 98 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _init_sensor().
_drdy_pin_num_g
int AP_InertialSensor_LSM9DS0::_drdy_pin_num_g private
Definition at line 99 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _init_sensor().
_gyro_instance
uint8_t AP_InertialSensor_LSM9DS0::_gyro_instance private
Definition at line 100 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _poll_data(), _read_data_transaction_g(), start(), and update().
_gyro_scale
float AP_InertialSensor_LSM9DS0::_gyro_scale private
Definition at line 96 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_g(), and _set_gyro_scale().
_rotation_a
enum Rotation AP_InertialSensor_LSM9DS0::_rotation_a private
Definition at line 113 of file AP_InertialSensor_LSM9DS0.h.
Referenced by start().
_rotation_g
enum Rotation AP_InertialSensor_LSM9DS0::_rotation_g private
Definition at line 114 of file AP_InertialSensor_LSM9DS0.h.
Referenced by start().
_rotation_gH
enum Rotation AP_InertialSensor_LSM9DS0::_rotation_gH private
Definition at line 115 of file AP_InertialSensor_LSM9DS0.h.
Referenced by start().
_spi_sem
AP_HAL::Semaphore* AP_InertialSensor_LSM9DS0::_spi_sem private
Definition at line 86 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _hardware_init(), and _init_sensor().
_temp_counter
uint8_t AP_InertialSensor_LSM9DS0::_temp_counter private
Definition at line 103 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_a().
_temp_filter
LowPassFilter2pFloat AP_InertialSensor_LSM9DS0::_temp_filter private
Definition at line 104 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_a().
_temperature
float AP_InertialSensor_LSM9DS0::_temperature private
Definition at line 102 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_a(), and update().
whoami_g
uint8_t AP_InertialSensor_LSM9DS0::whoami_g private
Definition at line 107 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _hardware_init(), and start().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS0.h
libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS0.cpp