APM:Libraries: AP_RCProtocol_Backend Class Reference
AP_RCProtocol_Backend Class Reference
#include <AP_RCProtocol_Backend.h>
Classes
struct Channels11Bit_8Chan
Public Member Functions
AP_RCProtocol_Backend (AP_RCProtocol &_frontend)
virtual ~AP_RCProtocol_Backend ()
virtual void process_pulse (uint32_t width_s0, uint32_t width_s1)
virtual void process_byte (uint8_t byte, uint32_t baudrate)
virtual void process_handshake (uint32_t baudrate)
uint16_t read (uint8_t chan)
void read (uint16_t *pwm, uint8_t n)
bool new_input ()
uint8_t num_channels () const
virtual void start_bind (void)
virtual void update (void)
uint32_t get_rc_frame_count (void) const
void reset_rc_frame_count (void)
uint32_t get_rc_input_count (void) const
uint32_t get_rc_protocols_mask (void) const
bool protocol_enabled (enum AP_RCProtocol::rcprotocol_t protocol) const
int16_t get_RSSI (void) const
int16_t get_rx_link_quality (void) const
AP_HAL::UARTDriver * get_UART (void) const
AP_HAL::UARTDriver * get_available_UART (void) const
bool have_UART (void) const
virtual bool is_rx_active () const
bool is_detected () const
Protected Member Functions
void add_input (uint8_t num_channels, uint16_t *values, bool in_failsafe, int16_t rssi=-1, int16_t rx_link_quality=-1)
void log_data (AP_RCProtocol::rcprotocol_t prot, uint32_t timestamp, const uint8_t *data, uint8_t len) const
Static Protected Member Functions
static void decode_11bit_channels (const uint8_t *data, uint8_t nchannels, uint16_t *values, uint16_t mult, uint16_t div, uint16_t offset)
Protected Attributes
struct AP_RCProtocol_Backend::Channels11Bit_8Chan PACKED
AP_RCProtocol & frontend
Private Attributes
uint32_t rc_input_count
uint32_t last_rc_input_count
uint32_t rc_frame_count
uint16_t _pwm_values [MAX_RCIN_CHANNELS]
uint8_t _num_channels
int16_t rssi = -1
int16_t rx_link_quality = -1
Friends
class AP_RCProtcol
Detailed Description
Definition at line 27 of file AP_RCProtocol_Backend.h.
Constructor & Destructor Documentation
AP_RCProtocol_Backend()
AP_RCProtocol_Backend::AP_RCProtocol_Backend (AP_RCProtocol & _frontend)
Definition at line 37 of file AP_RCProtocol_Backend.cpp.
~AP_RCProtocol_Backend()
virtual AP_RCProtocol_Backend::~AP_RCProtocol_Backend () inline virtual
Definition at line 32 of file AP_RCProtocol_Backend.h.
Member Function Documentation
add_input()
void AP_RCProtocol_Backend::add_input (uint8_t num_channels, uint16_t * values, bool in_failsafe, int16_t rssi = -1, int16_t rx_link_quality = -1) protected
Definition at line 74 of file AP_RCProtocol_Backend.cpp.
Referenced by AP_RCProtocol_DSM::_process_byte(), AP_RCProtocol_GHST::_process_byte(), AP_RCProtocol_IBUS::_process_byte(), AP_RCProtocol_SBUS::_process_byte(), AP_RCProtocol_SRXL::_process_byte(), AP_RCProtocol_SRXL2::_process_byte(), AP_RCProtocol_SUMD::_process_byte(), AP_RCProtocol_ST24::_process_byte(), AP_RCProtocol_CRSF::check_frame(), AP_RCProtocol_FPort::decode_control(), and AP_RCProtocol_PPMSum::process_pulse().
decode_11bit_channels()
void AP_RCProtocol_Backend::decode_11bit_channels (const uint8_t * data, uint8_t nchannels, uint16_t * values, uint16_t mult, uint16_t div, uint16_t offset) static protected
Definition at line 101 of file AP_RCProtocol_Backend.cpp.
Referenced by AP_RCProtocol_FPort::decode_control(), AP_RCProtocol_CRSF::decode_crsf_packet(), and AP_RCProtocol_SBUS::sbus_decode().
get_available_UART()
AP_HAL::UARTDriver * AP_RCProtocol_Backend::get_available_UART (void) const inline
Definition at line 84 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol_CRSF::change_baud_rate(), AP_RCProtocol_SRXL2::change_baud_rate(), AP_RCProtocol_CRSF::get_current_UART(), AP_RCProtocol_GHST::get_current_UART(), and AP_RCProtocol_SRXL2::send_on_uart().
get_rc_frame_count()
uint32_t AP_RCProtocol_Backend::get_rc_frame_count (void) const inline
Definition at line 48 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::process_byte(), and AP_RCProtocol::process_pulse().
get_rc_input_count()
uint32_t AP_RCProtocol_Backend::get_rc_input_count (void) const inline
Definition at line 58 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::process_byte(), AP_RCProtocol::process_pulse(), and AP_RCProtocol_CRSF::update().
get_rc_protocols_mask()
uint32_t AP_RCProtocol_Backend::get_rc_protocols_mask (void) const inline
Definition at line 62 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol_SRXL2::process_handshake().
get_RSSI()
int16_t AP_RCProtocol_Backend::get_RSSI (void) const inline
Definition at line 71 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::get_RSSI().
get_rx_link_quality()
int16_t AP_RCProtocol_Backend::get_rx_link_quality (void) const inline
Definition at line 74 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::get_rx_link_quality().
get_UART()
AP_HAL::UARTDriver * AP_RCProtocol_Backend::get_UART (void) const inline
Definition at line 79 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol_FPort::decode_downlink().
have_UART()
bool AP_RCProtocol_Backend::have_UART (void) const inline
Definition at line 89 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol_FPort::process_pulse().
is_detected()
bool AP_RCProtocol_Backend::is_detected () const inline
Definition at line 98 of file AP_RCProtocol_Backend.h.
is_rx_active()
virtual bool AP_RCProtocol_Backend::is_rx_active () const inline virtual
Reimplemented in AP_RCProtocol_CRSF, and AP_RCProtocol_GHST.
Definition at line 94 of file AP_RCProtocol_Backend.h.
log_data()
void AP_RCProtocol_Backend::log_data (AP_RCProtocol::rcprotocol_t prot, uint32_t timestamp, const uint8_t * data, uint8_t len) const protected
Definition at line 179 of file AP_RCProtocol_Backend.cpp.
Referenced by AP_RCProtocol_FPort::_process_byte(), AP_RCProtocol_GHST::_process_byte(), AP_RCProtocol_IBUS::_process_byte(), AP_RCProtocol_SBUS::_process_byte(), AP_RCProtocol_SRXL::_process_byte(), AP_RCProtocol_SRXL2::_process_byte(), AP_RCProtocol_SUMD::_process_byte(), AP_RCProtocol_ST24::_process_byte(), AP_RCProtocol_CRSF::check_frame(), and AP_RCProtocol_DSM::dsm_parse_byte().
new_input()
bool AP_RCProtocol_Backend::new_input ()
Definition at line 44 of file AP_RCProtocol_Backend.cpp.
Referenced by AP_RCProtocol::detect_async_protocol().
num_channels()
uint8_t AP_RCProtocol_Backend::num_channels () const
Definition at line 53 of file AP_RCProtocol_Backend.cpp.
Referenced by AP_RCProtocol::num_channels().
process_byte()
virtual void AP_RCProtocol_Backend::process_byte (uint8_t byte, uint32_t baudrate) inline virtual
Reimplemented in AP_RCProtocol_CRSF, AP_RCProtocol_DSM, AP_RCProtocol_FPort, AP_RCProtocol_GHST, AP_RCProtocol_IBUS, AP_RCProtocol_SBUS, AP_RCProtocol_SRXL, AP_RCProtocol_SRXL2, AP_RCProtocol_ST24, and AP_RCProtocol_SUMD.
Definition at line 34 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::process_byte().
process_handshake()
virtual void AP_RCProtocol_Backend::process_handshake (uint32_t baudrate) inline virtual
Reimplemented in AP_RCProtocol_CRSF, AP_RCProtocol_GHST, and AP_RCProtocol_SRXL2.
Definition at line 35 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::process_handshake().
process_pulse()
virtual void AP_RCProtocol_Backend::process_pulse (uint32_t width_s0, uint32_t width_s1) inline virtual
Reimplemented in AP_RCProtocol_DSM, AP_RCProtocol_FPort, AP_RCProtocol_IBUS, AP_RCProtocol_PPMSum, AP_RCProtocol_SBUS, AP_RCProtocol_SRXL, AP_RCProtocol_ST24, and AP_RCProtocol_SUMD.
Definition at line 33 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::process_pulse().
protocol_enabled()
bool AP_RCProtocol_Backend::protocol_enabled (enum AP_RCProtocol::rcprotocol_t protocol) const inline
Definition at line 66 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol_CRSF::process_handshake(), and AP_RCProtocol_GHST::process_handshake().
read() [1/2]
void AP_RCProtocol_Backend::read (uint16_t * pwm, uint8_t n)
Definition at line 63 of file AP_RCProtocol_Backend.cpp.
read() [2/2]
uint16_t AP_RCProtocol_Backend::read (uint8_t chan)
Definition at line 58 of file AP_RCProtocol_Backend.cpp.
Referenced by AP_RCProtocol::read(), and AP_RCProtocol::read().
reset_rc_frame_count()
void AP_RCProtocol_Backend::reset_rc_frame_count (void) inline
Definition at line 53 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol_DSM::dsm_parse_byte(), AP_RCProtocol::process_byte(), and AP_RCProtocol::process_pulse().
start_bind()
virtual void AP_RCProtocol_Backend::start_bind (void) inline virtual
Reimplemented in AP_RCProtocol_DSM, and AP_RCProtocol_SRXL2.
Definition at line 42 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::start_bind().
update()
virtual void AP_RCProtocol_Backend::update (void) inline virtual
Reimplemented in AP_RCProtocol_CRSF, AP_RCProtocol_DSM, AP_RCProtocol_GHST, and AP_RCProtocol_SRXL2.
Definition at line 45 of file AP_RCProtocol_Backend.h.
Referenced by AP_RCProtocol::new_input().
Friends And Related Symbol Documentation
AP_RCProtcol
friend class AP_RCProtcol friend
Definition at line 28 of file AP_RCProtocol_Backend.h.
Member Data Documentation
_num_channels
uint8_t AP_RCProtocol_Backend::_num_channels private
Definition at line 137 of file AP_RCProtocol_Backend.h.
Referenced by add_input(), and num_channels().
_pwm_values
uint16_t AP_RCProtocol_Backend::_pwm_values[MAX_RCIN_CHANNELS] private
Definition at line 136 of file AP_RCProtocol_Backend.h.
Referenced by add_input(), read(), and read().
frontend
AP_RCProtocol& AP_RCProtocol_Backend::frontend protected
Definition at line 124 of file AP_RCProtocol_Backend.h.
Referenced by add_input(), get_available_UART(), get_rc_protocols_mask(), get_UART(), have_UART(), is_detected(), and protocol_enabled().
last_rc_input_count
uint32_t AP_RCProtocol_Backend::last_rc_input_count private
Definition at line 133 of file AP_RCProtocol_Backend.h.
Referenced by new_input().
PACKED
struct AP_RCProtocol_Backend::Channels11Bit_8Chan AP_RCProtocol_Backend::PACKED protected
rc_frame_count
uint32_t AP_RCProtocol_Backend::rc_frame_count private
Definition at line 134 of file AP_RCProtocol_Backend.h.
Referenced by add_input(), get_rc_frame_count(), and reset_rc_frame_count().
rc_input_count
uint32_t AP_RCProtocol_Backend::rc_input_count private
Definition at line 132 of file AP_RCProtocol_Backend.h.
Referenced by add_input(), get_rc_input_count(), and new_input().
rssi
int16_t AP_RCProtocol_Backend::rssi = -1 private
Definition at line 138 of file AP_RCProtocol_Backend.h.
Referenced by add_input(), and get_RSSI().
rx_link_quality
int16_t AP_RCProtocol_Backend::rx_link_quality = -1 private
Definition at line 139 of file AP_RCProtocol_Backend.h.
Referenced by add_input(), and get_rx_link_quality().
The documentation for this class was generated from the following files:
libraries/AP_RCProtocol/AP_RCProtocol_Backend.h
libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp