APM:Libraries: AP_HAL::PWMSource Class Reference
AP_HAL::PWMSource Class Reference
#include <GPIO.h>
Public Member Functions
~PWMSource ()
bool set_pin (int16_t new_pin, const char *subsystem)
int16_t pin () const
uint16_t get_pwm_us ()
uint16_t get_pwm_avg_us ()
Private Member Functions
void irq_handler (uint8_t pin, bool pin_state, uint32_t timestamp)
Private Attributes
uint16_t _irq_value_us
uint32_t _pulse_start_us
int16_t _pin = -1
uint32_t _irq_value_us_sum
uint32_t _irq_value_us_count
bool interrupt_attached
Detailed Description
Definition at line 19 of file GPIO.h.
Constructor & Destructor Documentation
~PWMSource()
AP_HAL::PWMSource::~PWMSource ()
Definition at line 9 of file GPIO.cpp.
Member Function Documentation
get_pwm_avg_us()
uint16_t AP_HAL::PWMSource::get_pwm_avg_us ()
Definition at line 99 of file GPIO.cpp.
Referenced by AP_RangeFinder_PWM::get_reading().
get_pwm_us()
uint16_t AP_HAL::PWMSource::get_pwm_us ()
Definition at line 88 of file GPIO.cpp.
Referenced by AP_RSSI::read_pwm_pin_rssi(), AP_Button::update(), and AP_RangeFinder_HC_SR04::update().
irq_handler()
void AP_HAL::PWMSource::irq_handler (uint8_t pin, bool pin_state, uint32_t timestamp) private
Definition at line 67 of file GPIO.cpp.
Referenced by set_pin().
pin()
int16_t AP_HAL::PWMSource::pin () const inline
Definition at line 26 of file GPIO.h.
set_pin()
bool AP_HAL::PWMSource::set_pin (int16_t new_pin, const char * subsystem)
Definition at line 18 of file GPIO.cpp.
Referenced by AP_RangeFinder_HC_SR04::check_echo_pin(), AP_RangeFinder_PWM::check_pin(), AP_RSSI::read_pwm_pin_rssi(), and AP_Button::setup_pins().
Member Data Documentation
_irq_value_us
uint16_t AP_HAL::PWMSource::_irq_value_us private
Definition at line 32 of file GPIO.h.
_irq_value_us_count
uint32_t AP_HAL::PWMSource::_irq_value_us_count private
Definition at line 37 of file GPIO.h.
_irq_value_us_sum
uint32_t AP_HAL::PWMSource::_irq_value_us_sum private
Definition at line 36 of file GPIO.h.
_pin
int16_t AP_HAL::PWMSource::_pin = -1 private
Definition at line 34 of file GPIO.h.
Referenced by pin(), and ~PWMSource().
_pulse_start_us
uint32_t AP_HAL::PWMSource::_pulse_start_us private
Definition at line 33 of file GPIO.h.
interrupt_attached
bool AP_HAL::PWMSource::interrupt_attached private
Definition at line 39 of file GPIO.h.
Referenced by ~PWMSource().
The documentation for this class was generated from the following files:
libraries/AP_HAL/GPIO.h
libraries/AP_HAL/GPIO.cpp