APM:Libraries: AP_DAL_Baro Class Reference
AP_DAL_Baro Class Reference
#include <AP_DAL_Baro.h>
Public Member Functions
uint8_t get_primary () const
uint8_t num_instances () const
bool healthy (uint8_t sensor_id) const
uint32_t get_last_update (uint8_t sensor_id) const
uint32_t get_last_update () const
float get_altitude (uint8_t sensor_id) const
float get_altitude () const
void update_calibration ()
AP_DAL_Baro ()
void start_frame ()
void handle_message (const log_RBRH &msg)
void handle_message (const log_RBRI &msg)
Private Attributes
struct log_RBRH _RBRH
struct log_RBRI _RBRI [BARO_MAX_INSTANCES]
Detailed Description
Definition at line 7 of file AP_DAL_Baro.h.
Constructor & Destructor Documentation
AP_DAL_Baro()
AP_DAL_Baro::AP_DAL_Baro ()
Definition at line 6 of file AP_DAL_Baro.cpp.
Member Function Documentation
get_altitude() [1/2]
float AP_DAL_Baro::get_altitude () const inline
Definition at line 28 of file AP_DAL_Baro.h.
Referenced by get_altitude().
get_altitude() [2/2]
float AP_DAL_Baro::get_altitude (uint8_t sensor_id) const inline
Definition at line 25 of file AP_DAL_Baro.h.
get_last_update() [1/2]
uint32_t AP_DAL_Baro::get_last_update () const inline
Definition at line 22 of file AP_DAL_Baro.h.
Referenced by get_last_update().
get_last_update() [2/2]
uint32_t AP_DAL_Baro::get_last_update (uint8_t sensor_id) const inline
Definition at line 19 of file AP_DAL_Baro.h.
get_primary()
uint8_t AP_DAL_Baro::get_primary () const inline
Definition at line 10 of file AP_DAL_Baro.h.
Referenced by get_altitude(), and get_last_update().
handle_message() [1/2]
void AP_DAL_Baro::handle_message (const log_RBRH & msg) inline
Definition at line 41 of file AP_DAL_Baro.h.
Referenced by AP_DAL::handle_message(), and AP_DAL::handle_message().
handle_message() [2/2]
void AP_DAL_Baro::handle_message (const log_RBRI & msg) inline
Definition at line 44 of file AP_DAL_Baro.h.
healthy()
bool AP_DAL_Baro::healthy (uint8_t sensor_id) const inline
Definition at line 16 of file AP_DAL_Baro.h.
num_instances()
uint8_t AP_DAL_Baro::num_instances () const inline
Definition at line 13 of file AP_DAL_Baro.h.
Referenced by AP_NavEKF_Source::pre_arm_check().
start_frame()
void AP_DAL_Baro::start_frame ()
Definition at line 13 of file AP_DAL_Baro.cpp.
Referenced by AP_DAL::start_frame().
update_calibration()
void AP_DAL_Baro::update_calibration ()
Definition at line 32 of file AP_DAL_Baro.cpp.
Referenced by NavEKF2_core::resetHeightDatum(), and NavEKF3_core::resetHeightDatum().
Member Data Documentation
_RBRH
struct log_RBRH AP_DAL_Baro::_RBRH private
Definition at line 50 of file AP_DAL_Baro.h.
Referenced by get_primary(), handle_message(), num_instances(), and start_frame().
_RBRI
struct log_RBRI AP_DAL_Baro::_RBRI[BARO_MAX_INSTANCES] private
Definition at line 51 of file AP_DAL_Baro.h.
Referenced by AP_DAL_Baro(), get_altitude(), get_last_update(), handle_message(), healthy(), and start_frame().
The documentation for this class was generated from the following files:
libraries/AP_DAL/AP_DAL_Baro.h
libraries/AP_DAL/AP_DAL_Baro.cpp