APM:Libraries: AP_Frsky_MAVliteMsgHandler Class Reference
AP_Frsky_MAVliteMsgHandler Class Reference
#include <AP_Frsky_MAVliteMsgHandler.h>
Public Member Functions
FUNCTOR_TYPEDEF (send_mavlite_fn_t, bool, const AP_Frsky_MAVlite_Message &)
AP_Frsky_MAVliteMsgHandler (send_mavlite_fn_t send_fn)
void process_message (const AP_Frsky_MAVlite_Message &rxmsg)
Private Member Functions
bool send_message (AP_Frsky_MAVlite_Message &txmsg)
void handle_param_request_read (const AP_Frsky_MAVlite_Message &rxmsg)
void handle_param_set (const AP_Frsky_MAVlite_Message &rxmsg)
void handle_command_long (const AP_Frsky_MAVlite_Message &rxmsg)
MAV_RESULT handle_command (const mavlink_command_long_t &mav_command_long)
MAV_RESULT handle_command_preflight_calibration_baro (const mavlink_command_long_t &mav_command_long)
MAV_RESULT handle_command_do_set_mode (const mavlink_command_long_t &mav_command_long)
MAV_RESULT handle_command_do_fence_enable (const mavlink_command_long_t &mav_command_long)
MAV_RESULT handle_command_preflight_reboot (const mavlink_command_long_t &mav_command_long)
void send_command_ack (const MAV_RESULT mav_result, const uint16_t cmdid)
Private Attributes
send_mavlite_fn_t _send_fn
Detailed Description
Definition at line 9 of file AP_Frsky_MAVliteMsgHandler.h.
Constructor & Destructor Documentation
AP_Frsky_MAVliteMsgHandler()
AP_Frsky_MAVliteMsgHandler::AP_Frsky_MAVliteMsgHandler (send_mavlite_fn_t send_fn) inline
Definition at line 13 of file AP_Frsky_MAVliteMsgHandler.h.
Member Function Documentation
FUNCTOR_TYPEDEF()
AP_Frsky_MAVliteMsgHandler::FUNCTOR_TYPEDEF (send_mavlite_fn_t , bool , const AP_Frsky_MAVlite_Message &)
handle_command()
MAV_RESULT AP_Frsky_MAVliteMsgHandler::handle_command (const mavlink_command_long_t & mav_command_long) private
Definition at line 49 of file AP_Frsky_MAVliteMsgHandler.cpp.
Referenced by handle_command_long().
handle_command_do_fence_enable()
MAV_RESULT AP_Frsky_MAVliteMsgHandler::handle_command_do_fence_enable (const mavlink_command_long_t & mav_command_long) private
Referenced by handle_command().
handle_command_do_set_mode()
MAV_RESULT AP_Frsky_MAVliteMsgHandler::handle_command_do_set_mode (const mavlink_command_long_t & mav_command_long) private
Definition at line 101 of file AP_Frsky_MAVliteMsgHandler.cpp.
Referenced by handle_command().
handle_command_long()
void AP_Frsky_MAVliteMsgHandler::handle_command_long (const AP_Frsky_MAVlite_Message & rxmsg) private
Definition at line 15 of file AP_Frsky_MAVliteMsgHandler.cpp.
Referenced by process_message().
handle_command_preflight_calibration_baro()
MAV_RESULT AP_Frsky_MAVliteMsgHandler::handle_command_preflight_calibration_baro (const mavlink_command_long_t & mav_command_long) private
Definition at line 122 of file AP_Frsky_MAVliteMsgHandler.cpp.
Referenced by handle_command().
handle_command_preflight_reboot()
MAV_RESULT AP_Frsky_MAVliteMsgHandler::handle_command_preflight_reboot (const mavlink_command_long_t & mav_command_long) private
Definition at line 254 of file AP_Frsky_MAVliteMsgHandler.cpp.
Referenced by handle_command().
handle_param_request_read()
void AP_Frsky_MAVliteMsgHandler::handle_param_request_read (const AP_Frsky_MAVlite_Message & rxmsg) private
Definition at line 171 of file AP_Frsky_MAVliteMsgHandler.cpp.
Referenced by process_message().
handle_param_set()
void AP_Frsky_MAVliteMsgHandler::handle_param_set (const AP_Frsky_MAVlite_Message & rxmsg) private
Definition at line 198 of file AP_Frsky_MAVliteMsgHandler.cpp.
Referenced by process_message().
process_message()
void AP_Frsky_MAVliteMsgHandler::process_message (const AP_Frsky_MAVlite_Message & rxmsg)
Definition at line 273 of file AP_Frsky_MAVliteMsgHandler.cpp.
Referenced by AP_Frsky_SPort_Passthrough::process_rx_queue().
send_command_ack()
void AP_Frsky_MAVliteMsgHandler::send_command_ack (const MAV_RESULT mav_result, const uint16_t cmdid) private
Definition at line 109 of file AP_Frsky_MAVliteMsgHandler.cpp.
Referenced by handle_command_long().
send_message()
bool AP_Frsky_MAVliteMsgHandler::send_message (AP_Frsky_MAVlite_Message & txmsg) private
Definition at line 291 of file AP_Frsky_MAVliteMsgHandler.cpp.
Referenced by handle_param_request_read(), handle_param_set(), and send_command_ack().
Member Data Documentation
_send_fn
send_mavlite_fn_t AP_Frsky_MAVliteMsgHandler::_send_fn private
Definition at line 36 of file AP_Frsky_MAVliteMsgHandler.h.
Referenced by send_message().
The documentation for this class was generated from the following files:
libraries/AP_Frsky_Telem/AP_Frsky_MAVliteMsgHandler.h
libraries/AP_Frsky_Telem/AP_Frsky_MAVliteMsgHandler.cpp