APM:Libraries: AP_GPS_UBLOX Class Reference
AP_GPS_UBLOX Class Reference
#include <AP_GPS_UBLOX.h>
Classes
struct config_list
union PACKED
struct ubx_ack_ack
struct ubx_ack_nack
struct ubx_cfg_cfg
struct ubx_cfg_gnss
struct ubx_cfg_msg
struct ubx_cfg_msg_rate
struct ubx_cfg_msg_rate_6
struct ubx_cfg_nav_rate
struct ubx_cfg_nav_settings
struct ubx_cfg_prt
struct ubx_cfg_sbas
struct ubx_cfg_tp5
struct ubx_cfg_valget
struct ubx_cfg_valset
struct ubx_header
struct ubx_mon_hw2
struct ubx_mon_hw_60
struct ubx_mon_hw_68
struct ubx_mon_ver
struct ubx_nav_dop
struct ubx_nav_posllh
struct ubx_nav_pvt
struct ubx_nav_relposned
struct ubx_nav_solution
struct ubx_nav_status
struct ubx_nav_svinfo_header
struct ubx_nav_timegps
struct ubx_nav_velned
struct ubx_rxm_raw
struct ubx_rxm_rawx
struct ubx_tim_tm2
Public Member Functions
AP_GPS_UBLOX (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port, AP_GPS::GPS_Role role)
~AP_GPS_UBLOX () override
bool read () override
AP_GPS::GPS_Status highest_supported_status (void) override
bool is_configured (void) const override
bool get_error_codes (uint32_t &error_codes) const override
void broadcast_configuration_failure_reason (void) const override
void Write_AP_Logger_Log_Startup_messages () const override
bool get_lag (float &lag_sec) const override
const char * name () const override
bool get_RTCMV3 (const uint8_t *&bytes, uint16_t &len) override
void clear_RTCMV3 (void) override
bool is_healthy (void) const override
Public Member Functions inherited from AP_GPS_Backend
AP_GPS_Backend (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
virtual ~AP_GPS_Backend (void)
virtual void inject_data (const uint8_t *data, uint16_t len)
virtual bool logging_healthy (void) const
void broadcast_gps_type () const
virtual bool prepare_for_arming (void)
uint32_t get_last_itow_ms (void) const
bool option_set (const AP_GPS::DriverOptions option) const
Static Public Member Functions
static bool _detect (struct UBLOX_detect_state &state, uint8_t data)
Private Types
enum class ConfigKey : uint32_t {
TMODE_MODE = 0x20030001 , CFG_RATE_MEAS = 0x30210001 , CFG_UART1_BAUDRATE = 0x40520001 , CFG_UART1_ENABLED = 0x10520005 ,
CFG_UART1INPROT_UBX = 0x10730001 , CFG_UART1INPROT_NMEA = 0x10730002 , CFG_UART1INPROT_RTCM3X = 0x10730004 , CFG_UART1OUTPROT_UBX = 0x10740001 ,
CFG_UART1OUTPROT_NMEA = 0x10740002 , CFG_UART1OUTPROT_RTCM3X = 0x10740004 , CFG_UART2_BAUDRATE = 0x40530001 , CFG_UART2_ENABLED = 0x10530005 ,
CFG_UART2INPROT_UBX = 0x10750001 , CFG_UART2INPROT_NMEA = 0x10750002 , CFG_UART2INPROT_RTCM3X = 0x10750004 , CFG_UART2OUTPROT_UBX = 0x10760001 ,
CFG_UART2OUTPROT_NMEA = 0x10760002 , CFG_UART2OUTPROT_RTCM3X = 0x10760004 , MSGOUT_RTCM_3X_TYPE4072_0_UART1 = 0x209102ff , MSGOUT_RTCM_3X_TYPE4072_1_UART1 = 0x20910382 ,
MSGOUT_RTCM_3X_TYPE1077_UART1 = 0x209102cd , MSGOUT_RTCM_3X_TYPE1087_UART1 = 0x209102d2 , MSGOUT_RTCM_3X_TYPE1097_UART1 = 0x20910319 , MSGOUT_RTCM_3X_TYPE1127_UART1 = 0x209102d7 ,
MSGOUT_RTCM_3X_TYPE1230_UART1 = 0x20910304 , MSGOUT_UBX_NAV_RELPOSNED_UART1 = 0x2091008e , MSGOUT_RTCM_3X_TYPE4072_0_UART2 = 0x20910300 , MSGOUT_RTCM_3X_TYPE4072_1_UART2 = 0x20910383 ,
MSGOUT_RTCM_3X_TYPE1077_UART2 = 0x209102ce , MSGOUT_RTCM_3X_TYPE1087_UART2 = 0x209102d3 , MSGOUT_RTCM_3X_TYPE1097_UART2 = 0x2091031a , MSGOUT_RTCM_3X_TYPE1127_UART2 = 0x209102d8 ,
MSGOUT_RTCM_3X_TYPE1230_UART2 = 0x20910305 , MSGOUT_UBX_NAV_RELPOSNED_UART2 = 0x2091008f , CFG_SIGNAL_GPS_ENA = 0x1031001f , CFG_SIGNAL_GPS_L1CA_ENA = 0x10310001 ,
CFG_SIGNAL_GPS_L2C_ENA = 0x10310003 , CFG_SIGNAL_GPS_L5_ENA = 0x10310004 , CFG_SIGNAL_SBAS_ENA = 0x10310020 , CFG_SIGNAL_SBAS_L1CA_ENA = 0x10310005 ,
CFG_SIGNAL_GAL_ENA = 0x10310021 , CFG_SIGNAL_GAL_E1_ENA = 0x10310007 , CFG_SIGNAL_GAL_E5A_ENA = 0x10310009 , CFG_SIGNAL_GAL_E5B_ENA = 0x1031000a ,
CFG_SIGNAL_BDS_ENA = 0x10310022 , CFG_SIGNAL_BDS_B1_ENA = 0x1031000d , CFG_SIGNAL_BDS_B1C_ENA = 0x1031000f , CFG_SIGNAL_BDS_B2_ENA = 0x1031000e ,
CFG_SIGNAL_BDS_B2A_ENA = 0x10310028 , CFG_SIGNAL_QZSS_ENA = 0x10310024 , CFG_SIGNAL_QZSS_L1CA_ENA = 0x10310012 , CFG_SIGNAL_QZSS_L1S_ENA = 0x10310014 ,
CFG_SIGNAL_QZSS_L2C_ENA = 0x10310015 , CFG_SIGNAL_QZSS_L5_ENA = 0x10310017 , CFG_SIGNAL_GLO_ENA = 0x10310025 , CFG_SIGNAL_GLO_L1_ENA = 0x10310018 ,
CFG_SIGNAL_GLO_L2_ENA = 0x1031001a , CFG_SIGNAL_NAVIC_ENA = 0x10310026 , CFG_SIGNAL_NAVIC_L5_ENA = 0x1031001d , CFG_SIGNAL_L5_HEALTH_OVRD = 0x10320001 ,
CFG_NAVSPG_DYNMODEL = 0x20110021
}
enum class RELPOSNED {
gnssFixOK = 1U << 0 , diffSoln = 1U << 1 , relPosValid = 1U << 2 , carrSolnFloat = 1U << 3 ,
carrSolnFixed = 1U << 4 , isMoving = 1U << 5 , refPosMiss = 1U << 6 , refObsMiss = 1U << 7 ,
relPosHeadingValid = 1U << 8 , relPosNormalized = 1U << 9
}
enum ubs_protocol_bytes {
PREAMBLE1 = 0xb5 , PREAMBLE2 = 0x62 , CLASS_NAV = 0x01 , CLASS_ACK = 0x05 ,
CLASS_CFG = 0x06 , CLASS_MON = 0x0A , CLASS_RXM = 0x02 , CLASS_TIM = 0x0d ,
MSG_ACK_NACK = 0x00 , MSG_ACK_ACK = 0x01 , MSG_POSLLH = 0x2 , MSG_STATUS = 0x3 ,
MSG_DOP = 0x4 , MSG_SOL = 0x6 , MSG_PVT = 0x7 , MSG_TIMEGPS = 0x20 ,
MSG_RELPOSNED = 0x3c , MSG_VELNED = 0x12 , MSG_CFG_CFG = 0x09 , MSG_CFG_RATE = 0x08 ,
MSG_CFG_MSG = 0x01 , MSG_CFG_NAV_SETTINGS = 0x24 , MSG_CFG_PRT = 0x00 , MSG_CFG_SBAS = 0x16 ,
MSG_CFG_GNSS = 0x3E , MSG_CFG_TP5 = 0x31 , MSG_CFG_VALSET = 0x8A , MSG_CFG_VALGET = 0x8B ,
MSG_MON_HW = 0x09 , MSG_MON_HW2 = 0x0B , MSG_MON_VER = 0x04 , MSG_NAV_SVINFO = 0x30 ,
MSG_RXM_RAW = 0x10 , MSG_RXM_RAWX = 0x15 , MSG_TIM_TM2 = 0x03
}
enum ubx_gnss_identifier {
GNSS_GPS = 0x00 , GNSS_SBAS = 0x01 , GNSS_GALILEO = 0x02 , GNSS_BEIDOU = 0x03 ,
GNSS_IMES = 0x04 , GNSS_QZSS = 0x05 , GNSS_GLONASS = 0x06
}
enum ubs_nav_fix_type {
FIX_NONE = 0 , FIX_DEAD_RECKONING = 1 , FIX_2D = 2 , FIX_3D = 3 ,
FIX_GPS_DEAD_RECKONING = 4 , FIX_TIME = 5
}
enum ubx_nav_status_bits { NAV_STATUS_FIX_VALID = 1 , NAV_STATUS_DGPS_USED = 2 }
enum ubx_hardware_version {
ANTARIS = 0 , UBLOX_5 , UBLOX_6 , UBLOX_7 ,
UBLOX_M8 , UBLOX_F9 = 0x80 , UBLOX_M9 = 0x81 , UBLOX_M10 = 0x82 ,
UBLOX_UNKNOWN_HARDWARE_GENERATION = 0xff
}
enum config_step {
STEP_PVT = 0 , STEP_NAV_RATE , STEP_SOL , STEP_PORT ,
STEP_STATUS , STEP_POSLLH , STEP_VELNED , STEP_TIMEGPS ,
STEP_POLL_SVINFO , STEP_POLL_SBAS , STEP_POLL_NAV , STEP_POLL_GNSS ,
STEP_POLL_TP5 , STEP_TMODE , STEP_DOP , STEP_MON_HW ,
STEP_MON_HW2 , STEP_RAW , STEP_RAWX , STEP_VERSION ,
STEP_RTK_MOVBASE , STEP_TIM_TM2 , STEP_M10 , STEP_L5 ,
STEP_LAST
}
Private Member Functions
bool _parse_gps ()
bool _configure_message_rate (uint8_t msg_class, uint8_t msg_id, uint8_t rate)
bool _configure_valset (ConfigKey key, const void *value, uint8_t layers=UBX_VALSET_LAYER_ALL)
bool _configure_valget (ConfigKey key)
void _configure_rate (void)
void _configure_sbas (bool enable)
void _update_checksum (uint8_t *data, uint16_t len, uint8_t &ck_a, uint8_t &ck_b)
bool _send_message (uint8_t msg_class, uint8_t msg_id, const void *msg, uint16_t size)
void send_next_rate_update (void)
bool _request_message_rate (uint8_t msg_class, uint8_t msg_id)
void _request_next_config (void)
void _request_port (void)
void _request_version (void)
void _save_cfg (void)
void _verify_rate (uint8_t msg_class, uint8_t msg_id, uint8_t rate)
void _check_new_itow (uint32_t itow)
void unexpected_message (void)
void log_mon_hw (void)
void log_mon_hw2 (void)
void log_tim_tm2 (void)
void log_rxm_raw (const struct ubx_rxm_raw &raw)
void log_rxm_rawx (const struct ubx_rxm_rawx &raw)
bool mb_use_uart2 (void) const
uint8_t config_key_size (ConfigKey key) const
bool _configure_config_set (const config_list *list, uint8_t count, uint32_t unconfig_bit, uint8_t layers=UBX_VALSET_LAYER_ALL)
int8_t find_active_config_index (ConfigKey key) const
bool supports_F9_config (void) const
Private Attributes
union AP_GPS_UBLOX::PACKED _buffer
uint8_t _ck_a
uint8_t _ck_b
uint8_t _step
uint8_t _msg_id
uint16_t _payload_length
uint16_t _payload_counter
uint8_t _class
bool _cfg_saved
uint32_t _last_vel_time
uint32_t _last_pos_time
uint32_t _last_cfg_sent_time
uint8_t _num_cfg_save_tries
uint32_t _last_config_time
uint16_t _delay_time
uint8_t _next_message
uint8_t _ublox_port
bool _have_version
struct ubx_mon_ver _version
uint32_t _unconfigured_messages
uint8_t _hardware_generation
uint32_t _last_pvt_itow
uint32_t _last_relposned_itow
uint32_t _last_relposned_ms
AP_GPS::GPS_Role role
bool _new_position:1
bool _new_speed:1
uint8_t _disable_counter
AP_GPS::GPS_Status next_fix
bool _cfg_needs_save
bool noReceivedHdop
bool havePvtMsg
uint8_t _pps_freq = 1
struct {
const config_list * list
uint8_t count
uint32_t done_mask
uint32_t unconfig_bit
uint8_t layers
int8_t fetch_index
} active_config
RTCM3_Parser * rtcm3_parser
bool supports_l5
Static Private Attributes
static const config_list config_MB_Base_uart1 []
static const config_list config_MB_Base_uart2 []
static const config_list config_MB_Rover_uart1 []
static const config_list config_MB_Rover_uart2 []
static const config_list config_M10 []
static const config_list config_L5_ovrd_ena []
static const config_list config_L5_ovrd_dis []
Additional Inherited Members
Protected Member Functions inherited from AP_GPS_Backend
void fill_3d_velocity (void)
void velocity_to_speed_course (AP_GPS::GPS_State &s)
void make_gps_time (uint32_t bcd_date, uint32_t bcd_milliseconds)
void _detection_message (char *buffer, uint8_t buflen) const
bool should_log () const
void set_uart_timestamp (uint16_t nbytes)
void check_new_itow (uint32_t itow, uint32_t msg_length)
bool calculate_moving_base_yaw (const float reported_heading_deg, const float reported_distance, const float reported_D)
bool calculate_moving_base_yaw (AP_GPS::GPS_State &interim_state, const float reported_heading_deg, const float reported_distance, const float reported_D)
AP_GPS::GPS_Type get_type () const
virtual void set_pps_desired_freq (uint8_t freq)
void set_alt_amsl_cm (AP_GPS::GPS_State &_state, int32_t alt_amsl_cm)
Protected Attributes inherited from AP_GPS_Backend
AP_HAL::UARTDriver * port
UART we are attached to.
AP_GPS & gps
access to frontend (for parameters)
AP_GPS::GPS_State & state
public state for this instance
uint64_t _last_pps_time_us
JitterCorrection jitter_correction
uint32_t _last_itow_ms
bool _have_itow
Detailed Description
Definition at line 124 of file AP_GPS_UBLOX.h.
Member Enumeration Documentation
config_step
enum AP_GPS_UBLOX::config_step private
Enumerator
STEP_PVT
STEP_NAV_RATE
STEP_SOL
STEP_PORT
STEP_STATUS
STEP_POSLLH
STEP_VELNED
STEP_TIMEGPS
STEP_POLL_SVINFO
STEP_POLL_SBAS
STEP_POLL_NAV
STEP_POLL_GNSS
STEP_POLL_TP5
STEP_TMODE
STEP_DOP
STEP_MON_HW
STEP_MON_HW2
STEP_RAW
STEP_RAWX
STEP_VERSION
STEP_RTK_MOVBASE
STEP_TIM_TM2
STEP_M10
STEP_L5
STEP_LAST
Definition at line 720 of file AP_GPS_UBLOX.h.
ConfigKey
enum class AP_GPS_UBLOX::ConfigKey : uint32_t strong private
Enumerator
TMODE_MODE
CFG_RATE_MEAS
CFG_UART1_BAUDRATE
CFG_UART1_ENABLED
CFG_UART1INPROT_UBX
CFG_UART1INPROT_NMEA
CFG_UART1INPROT_RTCM3X
CFG_UART1OUTPROT_UBX
CFG_UART1OUTPROT_NMEA
CFG_UART1OUTPROT_RTCM3X
CFG_UART2_BAUDRATE
CFG_UART2_ENABLED
CFG_UART2INPROT_UBX
CFG_UART2INPROT_NMEA
CFG_UART2INPROT_RTCM3X
CFG_UART2OUTPROT_UBX
CFG_UART2OUTPROT_NMEA
CFG_UART2OUTPROT_RTCM3X
MSGOUT_RTCM_3X_TYPE4072_0_UART1
MSGOUT_RTCM_3X_TYPE4072_1_UART1
MSGOUT_RTCM_3X_TYPE1077_UART1
MSGOUT_RTCM_3X_TYPE1087_UART1
MSGOUT_RTCM_3X_TYPE1097_UART1
MSGOUT_RTCM_3X_TYPE1127_UART1
MSGOUT_RTCM_3X_TYPE1230_UART1
MSGOUT_UBX_NAV_RELPOSNED_UART1
MSGOUT_RTCM_3X_TYPE4072_0_UART2
MSGOUT_RTCM_3X_TYPE4072_1_UART2
MSGOUT_RTCM_3X_TYPE1077_UART2
MSGOUT_RTCM_3X_TYPE1087_UART2
MSGOUT_RTCM_3X_TYPE1097_UART2
MSGOUT_RTCM_3X_TYPE1127_UART2
MSGOUT_RTCM_3X_TYPE1230_UART2
MSGOUT_UBX_NAV_RELPOSNED_UART2
CFG_SIGNAL_GPS_ENA
CFG_SIGNAL_GPS_L1CA_ENA
CFG_SIGNAL_GPS_L2C_ENA
CFG_SIGNAL_GPS_L5_ENA
CFG_SIGNAL_SBAS_ENA
CFG_SIGNAL_SBAS_L1CA_ENA
CFG_SIGNAL_GAL_ENA
CFG_SIGNAL_GAL_E1_ENA
CFG_SIGNAL_GAL_E5A_ENA
CFG_SIGNAL_GAL_E5B_ENA
CFG_SIGNAL_BDS_ENA
CFG_SIGNAL_BDS_B1_ENA
CFG_SIGNAL_BDS_B1C_ENA
CFG_SIGNAL_BDS_B2_ENA
CFG_SIGNAL_BDS_B2A_ENA
CFG_SIGNAL_QZSS_ENA
CFG_SIGNAL_QZSS_L1CA_ENA
CFG_SIGNAL_QZSS_L1S_ENA
CFG_SIGNAL_QZSS_L2C_ENA
CFG_SIGNAL_QZSS_L5_ENA
CFG_SIGNAL_GLO_ENA
CFG_SIGNAL_GLO_L1_ENA
CFG_SIGNAL_GLO_L2_ENA
CFG_SIGNAL_NAVIC_ENA
CFG_SIGNAL_NAVIC_L5_ENA
CFG_SIGNAL_L5_HEALTH_OVRD
CFG_NAVSPG_DYNMODEL
Definition at line 254 of file AP_GPS_UBLOX.h.
RELPOSNED
enum class AP_GPS_UBLOX::RELPOSNED strong private
Enumerator
gnssFixOK
diffSoln
relPosValid
carrSolnFloat
carrSolnFixed
isMoving
refPosMiss
refObsMiss
relPosHeadingValid
relPosNormalized
Definition at line 634 of file AP_GPS_UBLOX.h.
ubs_nav_fix_type
enum AP_GPS_UBLOX::ubs_nav_fix_type private
Enumerator
FIX_NONE
FIX_DEAD_RECKONING
FIX_2D
FIX_3D
FIX_GPS_DEAD_RECKONING
FIX_TIME
Definition at line 695 of file AP_GPS_UBLOX.h.
ubs_protocol_bytes
enum AP_GPS_UBLOX::ubs_protocol_bytes private
Enumerator
PREAMBLE1
PREAMBLE2
CLASS_NAV
CLASS_ACK
CLASS_CFG
CLASS_MON
CLASS_RXM
CLASS_TIM
MSG_ACK_NACK
MSG_ACK_ACK
MSG_POSLLH
MSG_STATUS
MSG_DOP
MSG_SOL
MSG_PVT
MSG_TIMEGPS
MSG_RELPOSNED
MSG_VELNED
MSG_CFG_CFG
MSG_CFG_RATE
MSG_CFG_MSG
MSG_CFG_NAV_SETTINGS
MSG_CFG_PRT
MSG_CFG_SBAS
MSG_CFG_GNSS
MSG_CFG_TP5
MSG_CFG_VALSET
MSG_CFG_VALGET
MSG_MON_HW
MSG_MON_HW2
MSG_MON_VER
MSG_NAV_SVINFO
MSG_RXM_RAW
MSG_RXM_RAWX
MSG_TIM_TM2
Definition at line 649 of file AP_GPS_UBLOX.h.
ubx_gnss_identifier
enum AP_GPS_UBLOX::ubx_gnss_identifier private
Enumerator
GNSS_GPS
GNSS_SBAS
GNSS_GALILEO
GNSS_BEIDOU
GNSS_IMES
GNSS_QZSS
GNSS_GLONASS
Definition at line 686 of file AP_GPS_UBLOX.h.
ubx_hardware_version
enum AP_GPS_UBLOX::ubx_hardware_version private
Enumerator
ANTARIS
UBLOX_5
UBLOX_6
UBLOX_7
UBLOX_M8
UBLOX_F9
UBLOX_M9
UBLOX_M10
UBLOX_UNKNOWN_HARDWARE_GENERATION
Definition at line 707 of file AP_GPS_UBLOX.h.
ubx_nav_status_bits
enum AP_GPS_UBLOX::ubx_nav_status_bits private
Enumerator
NAV_STATUS_FIX_VALID
NAV_STATUS_DGPS_USED
Definition at line 703 of file AP_GPS_UBLOX.h.
Constructor & Destructor Documentation
AP_GPS_UBLOX()
AP_GPS_UBLOX::AP_GPS_UBLOX (AP_GPS & _gps, AP_GPS::GPS_State & _state, AP_HAL::UARTDriver * _port, AP_GPS::GPS_Role role)
Definition at line 97 of file AP_GPS_UBLOX.cpp.
~AP_GPS_UBLOX()
AP_GPS_UBLOX::~AP_GPS_UBLOX () override
Definition at line 132 of file AP_GPS_UBLOX.cpp.
Member Function Documentation
_check_new_itow()
void AP_GPS_UBLOX::_check_new_itow (uint32_t itow) private
Definition at line 2129 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps().
_configure_config_set()
bool AP_GPS_UBLOX::_configure_config_set (const config_list * list, uint8_t count, uint32_t unconfig_bit, uint8_t layers = UBX_VALSET_LAYER_ALL) private
Definition at line 1911 of file AP_GPS_UBLOX.cpp.
Referenced by _request_next_config().
_configure_message_rate()
bool AP_GPS_UBLOX::_configure_message_rate (uint8_t msg_class, uint8_t msg_id, uint8_t rate) private
Definition at line 1843 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps(), _verify_rate(), and unexpected_message().
_configure_rate()
void AP_GPS_UBLOX::_configure_rate (void) private
Definition at line 2027 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps().
_configure_sbas()
void AP_GPS_UBLOX::_configure_sbas (bool enable) private
_configure_valget()
bool AP_GPS_UBLOX::_configure_valget (ConfigKey key) private
Definition at line 1885 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps(), and _request_next_config().
_configure_valset()
bool AP_GPS_UBLOX::_configure_valset (ConfigKey key, const void * value, uint8_t layers = UBX_VALSET_LAYER_ALL) private
Definition at line 1860 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps().
_detect()
bool AP_GPS_UBLOX::_detect (struct UBLOX_detect_state & state, uint8_t data) static
Definition at line 1963 of file AP_GPS_UBLOX.cpp.
Referenced by AP_GPS::_detect_instance().
_parse_gps()
bool AP_GPS_UBLOX::_parse_gps (void) private
Definition at line 991 of file AP_GPS_UBLOX.cpp.
Referenced by read().
_request_message_rate()
bool AP_GPS_UBLOX::_request_message_rate (uint8_t msg_class, uint8_t msg_id) private
Definition at line 1823 of file AP_GPS_UBLOX.cpp.
Referenced by _request_next_config().
_request_next_config()
void AP_GPS_UBLOX::_request_next_config (void) private
Definition at line 273 of file AP_GPS_UBLOX.cpp.
Referenced by AP_GPS_UBLOX(), and read().
_request_port()
void AP_GPS_UBLOX::_request_port (void) private
Definition at line 588 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps(), _request_message_rate(), and _request_next_config().
_request_version()
void AP_GPS_UBLOX::_request_version (void) private
Definition at line 2021 of file AP_GPS_UBLOX.cpp.
Referenced by _request_next_config().
_save_cfg()
void AP_GPS_UBLOX::_save_cfg (void) private
Definition at line 1943 of file AP_GPS_UBLOX.cpp.
Referenced by read().
_send_message()
bool AP_GPS_UBLOX::_send_message (uint8_t msg_class, uint8_t msg_id, const void * msg, uint16_t size) private
Definition at line 1794 of file AP_GPS_UBLOX.cpp.
Referenced by _configure_config_set(), _configure_message_rate(), _configure_rate(), _configure_valget(), _configure_valset(), _parse_gps(), _request_message_rate(), _request_next_config(), _request_port(), _request_version(), and _save_cfg().
_update_checksum()
void AP_GPS_UBLOX::_update_checksum (uint8_t * data, uint16_t len, uint8_t & ck_a, uint8_t & ck_b) private
Definition at line 1780 of file AP_GPS_UBLOX.cpp.
Referenced by _send_message().
_verify_rate()
void AP_GPS_UBLOX::_verify_rate (uint8_t msg_class, uint8_t msg_id, uint8_t rate) private
Definition at line 493 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps().
broadcast_configuration_failure_reason()
void AP_GPS_UBLOX::broadcast_configuration_failure_reason (void) const override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 2062 of file AP_GPS_UBLOX.cpp.
clear_RTCMV3()
void AP_GPS_UBLOX::clear_RTCMV3 (void) override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 2147 of file AP_GPS_UBLOX.cpp.
config_key_size()
uint8_t AP_GPS_UBLOX::config_key_size (ConfigKey key) const private
Definition at line 952 of file AP_GPS_UBLOX.cpp.
Referenced by _configure_valset(), and _parse_gps().
find_active_config_index()
int8_t AP_GPS_UBLOX::find_active_config_index (ConfigKey key) const private
Definition at line 976 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps().
get_error_codes()
bool AP_GPS_UBLOX::get_error_codes (uint32_t & error_codes) const inline override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 149 of file AP_GPS_UBLOX.h.
get_lag()
bool AP_GPS_UBLOX::get_lag (float & lag_sec) const override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 2075 of file AP_GPS_UBLOX.cpp.
get_RTCMV3()
bool AP_GPS_UBLOX::get_RTCMV3 (const uint8_t *& bytes, uint16_t & len) override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 2135 of file AP_GPS_UBLOX.cpp.
highest_supported_status()
AP_GPS::GPS_Status AP_GPS_UBLOX::highest_supported_status (void) inline override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 133 of file AP_GPS_UBLOX.h.
is_configured()
bool AP_GPS_UBLOX::is_configured (void) const inline override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 137 of file AP_GPS_UBLOX.h.
is_healthy()
bool AP_GPS_UBLOX::is_healthy (void) const override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 2157 of file AP_GPS_UBLOX.cpp.
log_mon_hw()
void AP_GPS_UBLOX::log_mon_hw (void) private
Definition at line 776 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps().
log_mon_hw2()
void AP_GPS_UBLOX::log_mon_hw2 (void) private
Definition at line 802 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps().
log_rxm_raw()
void AP_GPS_UBLOX::log_rxm_raw (const struct ubx_rxm_raw & raw) private
Definition at line 867 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps().
log_rxm_rawx()
void AP_GPS_UBLOX::log_rxm_rawx (const struct ubx_rxm_rawx & raw) private
Definition at line 895 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps().
log_tim_tm2()
void AP_GPS_UBLOX::log_tim_tm2 (void) private
Referenced by _parse_gps().
mb_use_uart2()
bool AP_GPS_UBLOX::mb_use_uart2 (void) const inline private
Definition at line 824 of file AP_GPS_UBLOX.h.
Referenced by _request_next_config(), AP_GPS_UBLOX(), and is_healthy().
name()
const char * AP_GPS_UBLOX::name () const inline override virtual
Implements AP_GPS_Backend.
Definition at line 160 of file AP_GPS_UBLOX.h.
read()
bool AP_GPS_UBLOX::read (void) override virtual
Implements AP_GPS_Backend.
Definition at line 608 of file AP_GPS_UBLOX.cpp.
send_next_rate_update()
void AP_GPS_UBLOX::send_next_rate_update (void) private
supports_F9_config()
bool AP_GPS_UBLOX::supports_F9_config (void) const private
Definition at line 2181 of file AP_GPS_UBLOX.cpp.
Referenced by _configure_valget(), _configure_valset(), _request_next_config(), and is_healthy().
unexpected_message()
void AP_GPS_UBLOX::unexpected_message (void) private
Definition at line 938 of file AP_GPS_UBLOX.cpp.
Referenced by _parse_gps().
Write_AP_Logger_Log_Startup_messages()
void AP_GPS_UBLOX::Write_AP_Logger_Log_Startup_messages () const override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 2114 of file AP_GPS_UBLOX.cpp.
Member Data Documentation
_buffer
union AP_GPS_UBLOX::PACKED AP_GPS_UBLOX::_buffer private
Referenced by _parse_gps(), log_mon_hw(), log_mon_hw2(), and read().
_cfg_needs_save
bool AP_GPS_UBLOX::_cfg_needs_save private
Definition at line 793 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), _verify_rate(), and read().
_cfg_saved
bool AP_GPS_UBLOX::_cfg_saved private
Definition at line 759 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), and read().
_ck_a
uint8_t AP_GPS_UBLOX::_ck_a private
Definition at line 749 of file AP_GPS_UBLOX.h.
Referenced by read().
_ck_b
uint8_t AP_GPS_UBLOX::_ck_b private
Definition at line 750 of file AP_GPS_UBLOX.h.
Referenced by read().
_class
uint8_t AP_GPS_UBLOX::_class private
Definition at line 758 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), read(), and unexpected_message().
_delay_time
uint16_t AP_GPS_UBLOX::_delay_time private
Definition at line 766 of file AP_GPS_UBLOX.h.
Referenced by read().
_disable_counter
uint8_t AP_GPS_UBLOX::_disable_counter private
Definition at line 785 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), and unexpected_message().
_hardware_generation
uint8_t AP_GPS_UBLOX::_hardware_generation private
Definition at line 772 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), _request_next_config(), get_lag(), and supports_F9_config().
_have_version
bool AP_GPS_UBLOX::_have_version private
Definition at line 769 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), _request_next_config(), and Write_AP_Logger_Log_Startup_messages().
_last_cfg_sent_time
uint32_t AP_GPS_UBLOX::_last_cfg_sent_time private
Definition at line 763 of file AP_GPS_UBLOX.h.
Referenced by _save_cfg(), and read().
_last_config_time
uint32_t AP_GPS_UBLOX::_last_config_time private
Definition at line 765 of file AP_GPS_UBLOX.h.
Referenced by read().
_last_pos_time
uint32_t AP_GPS_UBLOX::_last_pos_time private
Definition at line 762 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps().
_last_pvt_itow
uint32_t AP_GPS_UBLOX::_last_pvt_itow private
Definition at line 773 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps().
_last_relposned_itow
uint32_t AP_GPS_UBLOX::_last_relposned_itow private
Definition at line 774 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps().
_last_relposned_ms
uint32_t AP_GPS_UBLOX::_last_relposned_ms private
Definition at line 775 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps().
_last_vel_time
uint32_t AP_GPS_UBLOX::_last_vel_time private
Definition at line 761 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps().
_msg_id
uint8_t AP_GPS_UBLOX::_msg_id private
Definition at line 754 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), read(), and unexpected_message().
_new_position
bool AP_GPS_UBLOX::_new_position private
Definition at line 781 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps().
_new_speed
bool AP_GPS_UBLOX::_new_speed private
Definition at line 783 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps().
_next_message
uint8_t AP_GPS_UBLOX::_next_message private
Definition at line 767 of file AP_GPS_UBLOX.h.
Referenced by _request_next_config().
_num_cfg_save_tries
uint8_t AP_GPS_UBLOX::_num_cfg_save_tries private
Definition at line 764 of file AP_GPS_UBLOX.h.
Referenced by _save_cfg(), and read().
_payload_counter
uint16_t AP_GPS_UBLOX::_payload_counter private
Definition at line 756 of file AP_GPS_UBLOX.h.
Referenced by read().
_payload_length
uint16_t AP_GPS_UBLOX::_payload_length private
Definition at line 755 of file AP_GPS_UBLOX.h.
Referenced by _check_new_itow(), _parse_gps(), log_mon_hw(), and read().
_pps_freq
uint8_t AP_GPS_UBLOX::_pps_freq = 1 private
Definition at line 850 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps().
_step
uint8_t AP_GPS_UBLOX::_step private
Definition at line 753 of file AP_GPS_UBLOX.h.
Referenced by read().
_ublox_port
uint8_t AP_GPS_UBLOX::_ublox_port private
Definition at line 768 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), and _request_message_rate().
_unconfigured_messages
uint32_t AP_GPS_UBLOX::_unconfigured_messages private
Definition at line 771 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), _request_next_config(), _verify_rate(), AP_GPS_UBLOX(), broadcast_configuration_failure_reason(), get_error_codes(), is_configured(), log_mon_hw(), and read().
_version
struct ubx_mon_ver AP_GPS_UBLOX::_version private
Definition at line 770 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), and Write_AP_Logger_Log_Startup_messages().
[struct]
struct { ... } AP_GPS_UBLOX::active_config
Referenced by _configure_config_set(), _parse_gps(), _request_next_config(), and find_active_config_index().
config_L5_ovrd_dis
const AP_GPS_UBLOX::config_list AP_GPS_UBLOX::config_L5_ovrd_dis static private
Initial value:
{
    {ConfigKey::CFG_SIGNAL_L5_HEALTH_OVRD, 0},
}
Definition at line 268 of file AP_GPS_UBLOX.h.
Referenced by _request_next_config().
config_L5_ovrd_ena
const AP_GPS_UBLOX::config_list AP_GPS_UBLOX::config_L5_ovrd_ena static private
Initial value:
{
    {ConfigKey::CFG_SIGNAL_L5_HEALTH_OVRD, 1},
    {ConfigKey::CFG_SIGNAL_GPS_L5_ENA, 1},
}
Definition at line 263 of file AP_GPS_UBLOX.h.
Referenced by _request_next_config().
config_M10
const AP_GPS_UBLOX::config_list AP_GPS_UBLOX::config_M10 static private
Initial value:
{
 { ConfigKey::CFG_SIGNAL_BDS_ENA, 1},
 { ConfigKey::CFG_SIGNAL_BDS_B1_ENA, 0},
 { ConfigKey::CFG_SIGNAL_BDS_B1C_ENA, 1},
 { ConfigKey::CFG_SIGNAL_GLO_ENA, 0},
 { ConfigKey::CFG_SIGNAL_QZSS_ENA, 1},
 { ConfigKey::CFG_SIGNAL_QZSS_L1CA_ENA, 1},
 { ConfigKey::CFG_SIGNAL_QZSS_L1S_ENA, 1},
 { ConfigKey::CFG_NAVSPG_DYNMODEL, 8},
}
Definition at line 248 of file AP_GPS_UBLOX.h.
Referenced by _request_next_config().
config_MB_Base_uart1
const AP_GPS_UBLOX::config_list AP_GPS_UBLOX::config_MB_Base_uart1 static private
Initial value:
{
 { ConfigKey::CFG_UART1OUTPROT_RTCM3X, 1},
 { ConfigKey::CFG_UART2OUTPROT_RTCM3X, 0},
 { ConfigKey::MSGOUT_UBX_NAV_RELPOSNED_UART1, 0},
 { ConfigKey::MSGOUT_UBX_NAV_RELPOSNED_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_0_UART1, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_1_UART1, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1077_UART1, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1087_UART1, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1097_UART1, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1127_UART1, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1230_UART1, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_0_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_1_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1077_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1087_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1097_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1127_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1230_UART2, 0},
}
Definition at line 144 of file AP_GPS_UBLOX.h.
Referenced by _request_next_config().
config_MB_Base_uart2
const AP_GPS_UBLOX::config_list AP_GPS_UBLOX::config_MB_Base_uart2 static private
Initial value:
{
 { ConfigKey::CFG_UART2_ENABLED, 1},
 { ConfigKey::CFG_UART2_BAUDRATE, 460800},
 { ConfigKey::CFG_UART2OUTPROT_RTCM3X, 1},
 { ConfigKey::CFG_UART1OUTPROT_RTCM3X, 0},
 { ConfigKey::CFG_UART1INPROT_RTCM3X, 1},
 { ConfigKey::MSGOUT_UBX_NAV_RELPOSNED_UART2, 0},
 { ConfigKey::MSGOUT_UBX_NAV_RELPOSNED_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_0_UART2, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_1_UART2, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1077_UART2, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1087_UART2, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1097_UART2, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1127_UART2, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1230_UART2, RTK_MB_RTCM_RATE},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_0_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_1_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1077_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1087_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1097_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1127_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1230_UART1, 0},
}
Definition at line 165 of file AP_GPS_UBLOX.h.
Referenced by _request_next_config().
config_MB_Rover_uart1
const AP_GPS_UBLOX::config_list AP_GPS_UBLOX::config_MB_Rover_uart1 static private
Initial value:
{
 { ConfigKey::CFG_UART2OUTPROT_RTCM3X, 0},
 { ConfigKey::CFG_UART1INPROT_RTCM3X, 1},
 { ConfigKey::CFG_UART2INPROT_RTCM3X, 0},
 { ConfigKey::MSGOUT_UBX_NAV_RELPOSNED_UART1, 1},
 { ConfigKey::MSGOUT_UBX_NAV_RELPOSNED_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_0_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_1_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1077_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1087_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1097_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1127_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1230_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_0_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_1_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1077_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1087_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1097_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1127_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1230_UART2, 0},
}
Definition at line 196 of file AP_GPS_UBLOX.h.
Referenced by _request_next_config().
config_MB_Rover_uart2
const AP_GPS_UBLOX::config_list AP_GPS_UBLOX::config_MB_Rover_uart2 static private
Initial value:
{
 { ConfigKey::CFG_UART2_ENABLED, 1},
 { ConfigKey::CFG_UART2_BAUDRATE, 460800},
 { ConfigKey::CFG_UART2OUTPROT_RTCM3X, 0},
 { ConfigKey::CFG_UART2INPROT_RTCM3X, 1},
 { ConfigKey::CFG_UART1INPROT_RTCM3X, 0},
 { ConfigKey::MSGOUT_UBX_NAV_RELPOSNED_UART1, 1},
 { ConfigKey::MSGOUT_UBX_NAV_RELPOSNED_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_0_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_1_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1077_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1087_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1097_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1127_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1230_UART2, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_0_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE4072_1_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1077_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1087_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1097_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1127_UART1, 0},
 { ConfigKey::MSGOUT_RTCM_3X_TYPE1230_UART1, 0},
}
Definition at line 218 of file AP_GPS_UBLOX.h.
Referenced by _request_next_config().
count
uint8_t AP_GPS_UBLOX::count
Definition at line 859 of file AP_GPS_UBLOX.h.
Referenced by _configure_config_set().
done_mask
uint32_t AP_GPS_UBLOX::done_mask
Definition at line 860 of file AP_GPS_UBLOX.h.
fetch_index
int8_t AP_GPS_UBLOX::fetch_index
Definition at line 863 of file AP_GPS_UBLOX.h.
havePvtMsg
bool AP_GPS_UBLOX::havePvtMsg private
Definition at line 797 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), _request_next_config(), _verify_rate(), and read().
layers
uint8_t AP_GPS_UBLOX::layers
Definition at line 862 of file AP_GPS_UBLOX.h.
Referenced by _configure_config_set(), and _configure_valset().
list
const config_list* AP_GPS_UBLOX::list
Definition at line 858 of file AP_GPS_UBLOX.h.
Referenced by _configure_config_set(), and _request_next_config().
next_fix
AP_GPS::GPS_Status AP_GPS_UBLOX::next_fix private
Definition at line 791 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps().
noReceivedHdop
bool AP_GPS_UBLOX::noReceivedHdop private
Definition at line 795 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps().
role
AP_GPS::GPS_Role AP_GPS_UBLOX::role private
Definition at line 778 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), _request_next_config(), AP_GPS_UBLOX(), get_lag(), and is_healthy().
rtcm3_parser
RTCM3_Parser* AP_GPS_UBLOX::rtcm3_parser private
Definition at line 876 of file AP_GPS_UBLOX.h.
Referenced by AP_GPS_UBLOX(), clear_RTCMV3(), get_RTCMV3(), is_healthy(), read(), and ~AP_GPS_UBLOX().
supports_l5
bool AP_GPS_UBLOX::supports_l5 private
Definition at line 879 of file AP_GPS_UBLOX.h.
Referenced by _parse_gps(), and _request_next_config().
unconfig_bit
uint32_t AP_GPS_UBLOX::unconfig_bit
Definition at line 861 of file AP_GPS_UBLOX.h.
Referenced by _configure_config_set().
The documentation for this class was generated from the following files:
libraries/AP_GPS/AP_GPS_UBLOX.h
libraries/AP_GPS/AP_GPS_UBLOX.cpp