APM:Libraries: StorageAccess Class Reference
StorageAccess Class Reference
#include <StorageManager.h>
Public Member Functions
StorageAccess (StorageManager::StorageType _type)
uint16_t size (void) const
bool read_block (void *dst, uint16_t src, size_t n) const
bool write_block (uint16_t dst, const void *src, size_t n) const
uint8_t read_byte (uint16_t loc) const
uint8_t read_uint8 (uint16_t loc) const
uint16_t read_uint16 (uint16_t loc) const
uint32_t read_uint32 (uint16_t loc) const
float read_float (uint16_t loc) const
void write_byte (uint16_t loc, uint8_t value) const
void write_uint8 (uint16_t loc, uint8_t value) const
void write_uint16 (uint16_t loc, uint16_t value) const
void write_uint32 (uint16_t loc, uint32_t value) const
void write_float (uint16_t loc, float value) const
bool copy_area (const StorageAccess &source) const
bool attach_file (const char *fname, uint16_t size_kbyte)
Private Attributes
const StorageManager::StorageType type
uint16_t total_size
Detailed Description
Definition at line 91 of file StorageManager.h.
Constructor & Destructor Documentation
StorageAccess()
StorageAccess::StorageAccess (StorageManager::StorageType _type)
Definition at line 119 of file StorageManager.cpp.
Member Function Documentation
attach_file()
bool StorageAccess::attach_file (const char * fname, uint16_t size_kbyte)
copy_area()
bool StorageAccess::copy_area (const StorageAccess & source) const
Definition at line 321 of file StorageManager.cpp.
Referenced by AP_Param::setup().
read_block()
bool StorageAccess::read_block (void * dst, uint16_t src, size_t n) const
Definition at line 139 of file StorageManager.cpp.
Referenced by AP_Param::convert_parameter_width(), AP_Param::find_old_parameter(), AP_Rally::get_rally_point_with_index(), AP_Param::load(), AP_Param::load_all(), AP_Param::load_object_from_eeprom(), loop(), read_byte(), read_float(), read_uint16(), read_uint32(), AP_Param::scan(), AP_Param::setup(), and GCS_MAVLINK::signing_key_load().
read_byte()
uint8_t StorageAccess::read_byte (uint16_t loc) const
Definition at line 249 of file StorageManager.cpp.
Referenced by read_uint8().
read_float()
float StorageAccess::read_float (uint16_t loc) const
Definition at line 279 of file StorageManager.cpp.
read_uint16()
uint16_t StorageAccess::read_uint16 (uint16_t loc) const
Definition at line 259 of file StorageManager.cpp.
read_uint32()
uint32_t StorageAccess::read_uint32 (uint16_t loc) const
Definition at line 269 of file StorageManager.cpp.
read_uint8()
uint8_t StorageAccess::read_uint8 (uint16_t loc) const inline
Definition at line 105 of file StorageManager.h.
size()
uint16_t StorageAccess::size (void) const inline
Definition at line 97 of file StorageManager.h.
Referenced by copy_area(), AP_Rally::get_rally_max(), AP_Param::load_all(), AP_Param::load_object_from_eeprom(), loop(), AP_Param::save_sync(), AP_Param::scan(), setup(), GCS_MAVLINK::signing_key_load(), GCS_MAVLINK::signing_key_save(), and AP_Param::storage_size().
write_block()
bool StorageAccess::write_block (uint16_t dst, const void * src, size_t n) const
Definition at line 193 of file StorageManager.cpp.
Referenced by copy_area(), AP_Param::eeprom_write_check(), GCS_MAVLINK::handle_preflight_reboot(), loop(), AP_Rally::set_rally_point_with_index(), GCS_MAVLINK::signing_key_save(), write_byte(), write_float(), write_uint16(), and write_uint32().
write_byte()
void StorageAccess::write_byte (uint16_t loc, uint8_t value) const
Definition at line 289 of file StorageManager.cpp.
Referenced by setup(), and write_uint8().
write_float()
void StorageAccess::write_float (uint16_t loc, float value) const
Definition at line 313 of file StorageManager.cpp.
write_uint16()
void StorageAccess::write_uint16 (uint16_t loc, uint16_t value) const
Definition at line 297 of file StorageManager.cpp.
write_uint32()
void StorageAccess::write_uint32 (uint16_t loc, uint32_t value) const
Definition at line 305 of file StorageManager.cpp.
write_uint8()
void StorageAccess::write_uint8 (uint16_t loc, uint8_t value) const inline
Definition at line 111 of file StorageManager.h.
Member Data Documentation
total_size
uint16_t StorageAccess::total_size private
Definition at line 124 of file StorageManager.h.
Referenced by size(), and StorageAccess().
type
const StorageManager::StorageType StorageAccess::type private
Definition at line 123 of file StorageManager.h.
The documentation for this class was generated from the following files:
libraries/StorageManager/StorageManager.h
libraries/StorageManager/StorageManager.cpp