APM:Libraries: AP_HMC5843_BusDriver Class Reference
AP_HMC5843_BusDriver Class Reference abstract
#include <AP_Compass_HMC5843.h>
Public Member Functions
virtual ~AP_HMC5843_BusDriver ()
virtual bool block_read (uint8_t reg, uint8_t *buf, uint32_t size)=0
virtual bool register_read (uint8_t reg, uint8_t *val)=0
virtual bool register_write (uint8_t reg, uint8_t val)=0
virtual AP_HAL::Semaphore * get_semaphore ()=0
virtual bool configure ()
virtual bool start_measurements ()
virtual AP_HAL::Device::PeriodicHandle register_periodic_callback (uint32_t, AP_HAL::Device::PeriodicCb)=0
virtual void set_device_type (uint8_t devtype)=0
virtual uint32_t get_bus_id (void) const =0
virtual void set_retries (uint8_t retries)
Detailed Description
Definition at line 74 of file AP_Compass_HMC5843.h.
Constructor & Destructor Documentation
~AP_HMC5843_BusDriver()
virtual AP_HMC5843_BusDriver::~AP_HMC5843_BusDriver () inline virtual
Definition at line 77 of file AP_Compass_HMC5843.h.
Member Function Documentation
block_read()
virtual bool AP_HMC5843_BusDriver::block_read (uint8_t reg, uint8_t * buf, uint32_t size) pure virtual
Implemented in AP_HMC5843_BusDriver_HALDevice.
Referenced by AP_Compass_HMC5843::_check_whoami(), and AP_Compass_HMC5843::_read_sample().
configure()
virtual bool AP_HMC5843_BusDriver::configure () inline virtual
Definition at line 85 of file AP_Compass_HMC5843.h.
Referenced by AP_Compass_HMC5843::init().
get_bus_id()
virtual uint32_t AP_HMC5843_BusDriver::get_bus_id (void) const pure virtual
Implemented in AP_HMC5843_BusDriver_HALDevice.
Referenced by AP_Compass_HMC5843::init().
get_semaphore()
virtual AP_HAL::Semaphore * AP_HMC5843_BusDriver::get_semaphore () pure virtual
Implemented in AP_HMC5843_BusDriver_HALDevice.
Referenced by AP_Compass_HMC5843::init().
register_periodic_callback()
virtual AP_HAL::Device::PeriodicHandle AP_HMC5843_BusDriver::register_periodic_callback (uint32_t , AP_HAL::Device::PeriodicCb) pure virtual
Implemented in AP_HMC5843_BusDriver_HALDevice.
Referenced by AP_Compass_HMC5843::init().
register_read()
virtual bool AP_HMC5843_BusDriver::register_read (uint8_t reg, uint8_t * val) pure virtual
Implemented in AP_HMC5843_BusDriver_HALDevice.
register_write()
virtual bool AP_HMC5843_BusDriver::register_write (uint8_t reg, uint8_t val) pure virtual
Implemented in AP_HMC5843_BusDriver_HALDevice.
Referenced by AP_Compass_HMC5843::_calibrate(), AP_Compass_HMC5843::_setup_sampling_mode(), and AP_Compass_HMC5843::_take_sample().
set_device_type()
virtual void AP_HMC5843_BusDriver::set_device_type (uint8_t devtype) pure virtual
Implemented in AP_HMC5843_BusDriver_HALDevice.
Referenced by AP_Compass_HMC5843::init().
set_retries()
virtual void AP_HMC5843_BusDriver::set_retries (uint8_t retries) inline virtual
Reimplemented in AP_HMC5843_BusDriver_HALDevice.
Definition at line 96 of file AP_Compass_HMC5843.h.
Referenced by AP_Compass_HMC5843::init().
start_measurements()
virtual bool AP_HMC5843_BusDriver::start_measurements () inline virtual
Definition at line 86 of file AP_Compass_HMC5843.h.
Referenced by AP_Compass_HMC5843::init().
The documentation for this class was generated from the following file:
libraries/AP_Compass/AP_Compass_HMC5843.h