APM:Libraries: AP_Generator_Backend Class Reference
AP_Generator_Backend Class Reference abstract
#include <AP_Generator_Backend.h>
Public Member Functions
AP_Generator_Backend (AP_Generator &frontend)
virtual ~AP_Generator_Backend ()
virtual void init (void)=0
virtual void update (void)=0
virtual bool pre_arm_check (char *failmsg, uint8_t failmsg_len) const
virtual AP_BattMonitor::Failsafe update_failsafes (void) const
virtual bool healthy (void) const =0
virtual bool stop (void)
virtual bool idle (void)
virtual bool run (void)
virtual void send_generator_status (const GCS_MAVLINK &channel)
Protected Member Functions
void update_frontend (void)
Protected Attributes
float _voltage
float _current
float _fuel_remaining
float _consumed_mah
uint16_t _rpm
AP_Generator & _frontend
Detailed Description
Definition at line 7 of file AP_Generator_Backend.h.
Constructor & Destructor Documentation
AP_Generator_Backend()
AP_Generator_Backend::AP_Generator_Backend (AP_Generator & frontend)
Definition at line 20 of file AP_Generator_Backend.cpp.
~AP_Generator_Backend()
virtual AP_Generator_Backend::~AP_Generator_Backend () inline virtual
Definition at line 15 of file AP_Generator_Backend.h.
Member Function Documentation
healthy()
virtual bool AP_Generator_Backend::healthy (void) const pure virtual
Implemented in AP_Generator_IE_FuelCell.
Referenced by update_frontend().
idle()
virtual bool AP_Generator_Backend::idle (void) inline virtual
Definition at line 32 of file AP_Generator_Backend.h.
Referenced by AP_Generator::idle().
init()
virtual void AP_Generator_Backend::init (void) pure virtual
Implemented in AP_Generator_IE_2400, AP_Generator_IE_650_800, and AP_Generator_IE_FuelCell.
Referenced by AP_Generator::init().
pre_arm_check()
virtual bool AP_Generator_Backend::pre_arm_check (char * failmsg, uint8_t failmsg_len) const inline virtual
Reimplemented in AP_Generator_IE_FuelCell.
Definition at line 21 of file AP_Generator_Backend.h.
Referenced by AP_Generator::pre_arm_check().
run()
virtual bool AP_Generator_Backend::run (void) inline virtual
Definition at line 33 of file AP_Generator_Backend.h.
Referenced by AP_Generator::run().
send_generator_status()
virtual void AP_Generator_Backend::send_generator_status (const GCS_MAVLINK & channel) inline virtual
Definition at line 36 of file AP_Generator_Backend.h.
Referenced by AP_Generator::send_generator_status().
stop()
virtual bool AP_Generator_Backend::stop (void) inline virtual
Definition at line 31 of file AP_Generator_Backend.h.
Referenced by AP_Generator::stop().
update()
virtual void AP_Generator_Backend::update (void) pure virtual
Implemented in AP_Generator_IE_FuelCell.
Referenced by AP_Generator::update().
update_failsafes()
virtual AP_BattMonitor::Failsafe AP_Generator_Backend::update_failsafes (void) const inline virtual
Reimplemented in AP_Generator_IE_2400, and AP_Generator_IE_650_800.
Definition at line 24 of file AP_Generator_Backend.h.
Referenced by AP_Generator::update_failsafes().
update_frontend()
void AP_Generator_Backend::update_frontend (void) protected
Definition at line 26 of file AP_Generator_Backend.cpp.
Referenced by AP_Generator_IE_FuelCell::update().
Member Data Documentation
_consumed_mah
float AP_Generator_Backend::_consumed_mah protected
Definition at line 47 of file AP_Generator_Backend.h.
Referenced by AP_Generator_IE_2400::assign_measurements(), AP_Generator_IE_650_800::assign_measurements(), and update_frontend().
_current
float AP_Generator_Backend::_current protected
Definition at line 45 of file AP_Generator_Backend.h.
Referenced by AP_Generator_IE_2400::assign_measurements(), and update_frontend().
_frontend
AP_Generator& AP_Generator_Backend::_frontend protected
Definition at line 50 of file AP_Generator_Backend.h.
Referenced by AP_Generator_IE_2400::init(), AP_Generator_IE_650_800::init(), and update_frontend().
_fuel_remaining
float AP_Generator_Backend::_fuel_remaining protected
Definition at line 46 of file AP_Generator_Backend.h.
Referenced by AP_Generator_IE_2400::assign_measurements(), AP_Generator_IE_650_800::assign_measurements(), and update_frontend().
_rpm
uint16_t AP_Generator_Backend::_rpm protected
Definition at line 48 of file AP_Generator_Backend.h.
Referenced by update_frontend().
_voltage
float AP_Generator_Backend::_voltage protected
Definition at line 44 of file AP_Generator_Backend.h.
Referenced by AP_Generator_IE_2400::assign_measurements(), AP_Generator_IE_650_800::assign_measurements(), and update_frontend().
The documentation for this class was generated from the following files:
libraries/AP_Generator/AP_Generator_Backend.h
libraries/AP_Generator/AP_Generator_Backend.cpp