APM:Libraries: AP_RPM_Backend Class Reference
AP_RPM_Backend Class Reference abstract
#include <RPM_Backend.h>
Public Member Functions
AP_RPM_Backend (AP_RPM &_ap_rpm, uint8_t instance, AP_RPM::RPM_State &_state)
virtual ~AP_RPM_Backend (void)
virtual void update ()=0
int8_t get_pin (void) const
void update_esc_telem_outbound ()
Protected Attributes
AP_RPM & ap_rpm
AP_RPM::RPM_State & state
Detailed Description
Definition at line 21 of file RPM_Backend.h.
Constructor & Destructor Documentation
AP_RPM_Backend()
AP_RPM_Backend::AP_RPM_Backend (AP_RPM & _ap_rpm, uint8_t instance, AP_RPM::RPM_State & _state)
Definition at line 29 of file RPM_Backend.cpp.
~AP_RPM_Backend()
virtual AP_RPM_Backend::~AP_RPM_Backend (void) inline virtual
Definition at line 29 of file RPM_Backend.h.
Member Function Documentation
get_pin()
int8_t AP_RPM_Backend::get_pin (void) const inline
Definition at line 34 of file RPM_Backend.h.
Referenced by AP_RPM_Pin::update().
update()
virtual void AP_RPM_Backend::update () pure virtual
Implemented in AP_RPM_Pin.
Referenced by AP_RPM::update().
update_esc_telem_outbound()
void AP_RPM_Backend::update_esc_telem_outbound ()
Referenced by AP_RPM::update().
Member Data Documentation
ap_rpm
AP_RPM& AP_RPM_Backend::ap_rpm protected
Definition at line 45 of file RPM_Backend.h.
Referenced by get_pin(), and AP_RPM_Pin::update().
state
AP_RPM::RPM_State& AP_RPM_Backend::state protected
Definition at line 46 of file RPM_Backend.h.
Referenced by AP_RPM_Backend(), get_pin(), AP_RPM_Pin::irq_handler(), and AP_RPM_Pin::update().
The documentation for this class was generated from the following files:
libraries/AP_RPM/RPM_Backend.h
libraries/AP_RPM/RPM_Backend.cpp