APM:Libraries: SerialDevice Class Reference
SerialDevice Class Reference abstract
#include <SerialDevice.h>
Public Member Functions
virtual ~SerialDevice ()
virtual bool open ()=0
virtual bool close ()=0
virtual ssize_t write (const uint8_t *buf, uint16_t n)=0
virtual ssize_t read (uint8_t *buf, uint16_t n)=0
virtual void set_blocking (bool blocking)=0
virtual void set_speed (uint32_t speed)=0
virtual AP_HAL::UARTDriver::flow_control get_flow_control (void)
virtual void set_flow_control (AP_HAL::UARTDriver::flow_control flow_control_setting)
virtual void set_parity (int v)
Detailed Description
Definition at line 8 of file SerialDevice.h.
Constructor & Destructor Documentation
~SerialDevice()
virtual SerialDevice::~SerialDevice () inline virtual
Definition at line 10 of file SerialDevice.h.
Member Function Documentation
close()
virtual bool SerialDevice::close () pure virtual
Implemented in ConsoleDevice, TCPServerDevice, UARTDevice, and UDPDevice.
Referenced by Linux::UARTDriver::_end().
get_flow_control()
virtual AP_HAL::UARTDriver::flow_control SerialDevice::get_flow_control (void) inline virtual
Reimplemented in UARTDevice.
Definition at line 18 of file SerialDevice.h.
Referenced by Linux::UARTDriver::get_flow_control().
open()
virtual bool SerialDevice::open () pure virtual
Implemented in ConsoleDevice, TCPServerDevice, UARTDevice, and UDPDevice.
Referenced by Linux::UARTDriver::_begin(), and Linux::UARTDriver::_write_fd().
read()
virtual ssize_t SerialDevice::read (uint8_t * buf, uint16_t n) pure virtual
Implemented in ConsoleDevice, TCPServerDevice, UARTDevice, and UDPDevice.
Referenced by Linux::UARTDriver::_read_fd().
set_blocking()
virtual void SerialDevice::set_blocking (bool blocking) pure virtual
Implemented in ConsoleDevice, TCPServerDevice, UARTDevice, and UDPDevice.
Referenced by Linux::UARTDriver::_begin().
set_flow_control()
virtual void SerialDevice::set_flow_control (AP_HAL::UARTDriver::flow_control flow_control_setting) inline virtual
Reimplemented in UARTDevice.
Definition at line 19 of file SerialDevice.h.
Referenced by Linux::UARTDriver::set_flow_control().
set_parity()
virtual void SerialDevice::set_parity (int v) inline virtual
Reimplemented in UARTDevice.
Definition at line 25 of file SerialDevice.h.
Referenced by Linux::UARTDriver::configure_parity().
set_speed()
virtual void SerialDevice::set_speed (uint32_t speed) pure virtual
Implemented in ConsoleDevice, TCPServerDevice, UARTDevice, and UDPDevice.
Referenced by Linux::UARTDriver::_begin().
write()
virtual ssize_t SerialDevice::write (const uint8_t * buf, uint16_t n) pure virtual
Implemented in ConsoleDevice, TCPServerDevice, UARTDevice, and UDPDevice.
Referenced by Linux::UARTDriver::_write_fd().
The documentation for this class was generated from the following file:
libraries/AP_HAL_Linux/SerialDevice.h