APM:Libraries: AP::PerfInfo Class Reference
AP::PerfInfo Class Reference
#include <PerfInfo.h>
Classes
struct TaskInfo
Public Member Functions
PerfInfo ()
CLASS_NO_COPY (PerfInfo)
void reset ()
void ignore_this_loop ()
void check_loop_time (uint32_t time_in_micros)
uint16_t get_num_loops () const
uint32_t get_max_time () const
uint32_t get_min_time () const
uint16_t get_num_long_running () const
uint32_t get_avg_time () const
uint32_t get_stddev_time () const
float get_filtered_time () const
float get_filtered_loop_rate_hz () const
void set_loop_rate (uint16_t rate_hz)
void update_logging () const
void allocate_task_info (uint8_t num_tasks)
void free_task_info ()
bool has_task_info ()
const TaskInfo * get_task_info (uint8_t task_index) const
void update_task_info (uint8_t task_index, uint16_t task_time_us, bool overrun)
void task_slipped (uint8_t task_index)
Private Attributes
uint16_t loop_rate_hz
uint16_t overtime_threshold_micros
uint16_t loop_count
uint32_t max_time
uint32_t min_time
uint64_t sigma_time
uint64_t sigmasquared_time
uint16_t long_running
uint32_t last_check_us
float filtered_loop_time
bool ignore_loop
uint8_t _num_tasks
TaskInfo * _task_info
Detailed Description
Definition at line 8 of file PerfInfo.h.
Constructor & Destructor Documentation
PerfInfo()
AP::PerfInfo::PerfInfo () inline
Definition at line 10 of file PerfInfo.h.
Member Function Documentation
allocate_task_info()
void AP::PerfInfo::allocate_task_info (uint8_t num_tasks)
Definition at line 37 of file PerfInfo.cpp.
Referenced by AP_Scheduler::init().
check_loop_time()
void AP::PerfInfo::check_loop_time (uint32_t time_in_micros)
Definition at line 104 of file PerfInfo.cpp.
Referenced by AP_Scheduler::loop().
CLASS_NO_COPY()
AP::PerfInfo::CLASS_NO_COPY (PerfInfo)
free_task_info()
void AP::PerfInfo::free_task_info ()
Definition at line 48 of file PerfInfo.cpp.
get_avg_time()
uint32_t AP::PerfInfo::get_avg_time () const
Definition at line 169 of file PerfInfo.cpp.
get_filtered_loop_rate_hz()
float AP::PerfInfo::get_filtered_loop_rate_hz () const
Definition at line 187 of file PerfInfo.cpp.
Referenced by AP_Scheduler::get_filtered_loop_rate_hz().
get_filtered_time()
float AP::PerfInfo::get_filtered_time () const
Definition at line 181 of file PerfInfo.cpp.
Referenced by AP_Scheduler::get_filtered_loop_time().
get_max_time()
uint32_t AP::PerfInfo::get_max_time () const
Definition at line 151 of file PerfInfo.cpp.
get_min_time()
uint32_t AP::PerfInfo::get_min_time () const
Definition at line 157 of file PerfInfo.cpp.
get_num_long_running()
uint16_t AP::PerfInfo::get_num_long_running () const
Definition at line 163 of file PerfInfo.cpp.
get_num_loops()
uint16_t AP::PerfInfo::get_num_loops () const
Definition at line 145 of file PerfInfo.cpp.
get_stddev_time()
uint32_t AP::PerfInfo::get_stddev_time () const
Definition at line 175 of file PerfInfo.cpp.
get_task_info()
const TaskInfo * AP::PerfInfo::get_task_info (uint8_t task_index) const inline
Definition at line 49 of file PerfInfo.h.
Referenced by AP_Scheduler::task_info().
has_task_info()
bool AP::PerfInfo::has_task_info () inline
Definition at line 47 of file PerfInfo.h.
ignore_this_loop()
void AP::PerfInfo::ignore_this_loop ()
Definition at line 31 of file PerfInfo.cpp.
reset()
void AP::PerfInfo::reset ()
Definition at line 17 of file PerfInfo.cpp.
Referenced by AP_Scheduler::init().
set_loop_rate()
void AP::PerfInfo::set_loop_rate (uint16_t rate_hz)
Definition at line 210 of file PerfInfo.cpp.
Referenced by AP_Scheduler::init().
task_slipped()
void AP::PerfInfo::task_slipped (uint8_t task_index) inline
Definition at line 55 of file PerfInfo.h.
Referenced by AP_Scheduler::run().
update_logging()
void AP::PerfInfo::update_logging () const
Definition at line 197 of file PerfInfo.cpp.
update_task_info()
void AP::PerfInfo::update_task_info (uint8_t task_index, uint16_t task_time_us, bool overrun)
Definition at line 56 of file PerfInfo.cpp.
Referenced by AP_Scheduler::run().
Member Data Documentation
_num_tasks
uint8_t AP::PerfInfo::_num_tasks private
Definition at line 74 of file PerfInfo.h.
Referenced by get_task_info(), reset(), and task_slipped().
_task_info
TaskInfo* AP::PerfInfo::_task_info private
Definition at line 75 of file PerfInfo.h.
Referenced by get_task_info(), has_task_info(), reset(), and task_slipped().
filtered_loop_time
float AP::PerfInfo::filtered_loop_time private
Definition at line 71 of file PerfInfo.h.
ignore_loop
bool AP::PerfInfo::ignore_loop private
Definition at line 72 of file PerfInfo.h.
last_check_us
uint32_t AP::PerfInfo::last_check_us private
Definition at line 70 of file PerfInfo.h.
long_running
uint16_t AP::PerfInfo::long_running private
Definition at line 69 of file PerfInfo.h.
Referenced by reset().
loop_count
uint16_t AP::PerfInfo::loop_count private
Definition at line 64 of file PerfInfo.h.
Referenced by reset().
loop_rate_hz
uint16_t AP::PerfInfo::loop_rate_hz private
Definition at line 62 of file PerfInfo.h.
max_time
uint32_t AP::PerfInfo::max_time private
Definition at line 65 of file PerfInfo.h.
Referenced by reset().
min_time
uint32_t AP::PerfInfo::min_time private
Definition at line 66 of file PerfInfo.h.
Referenced by reset().
overtime_threshold_micros
uint16_t AP::PerfInfo::overtime_threshold_micros private
Definition at line 63 of file PerfInfo.h.
sigma_time
uint64_t AP::PerfInfo::sigma_time private
Definition at line 67 of file PerfInfo.h.
Referenced by reset().
sigmasquared_time
uint64_t AP::PerfInfo::sigmasquared_time private
Definition at line 68 of file PerfInfo.h.
Referenced by reset().
The documentation for this class was generated from the following files:
libraries/AP_Scheduler/PerfInfo.h
libraries/AP_Scheduler/PerfInfo.cpp