APM:Libraries: AP_RCProtocol_GHST Class Reference
AP_RCProtocol_GHST Class Reference
#include <AP_RCProtocol_GHST.h>
Classes
struct Channels12Bit_4Chan
struct Frame
struct LinkStatisticsFrame
struct LinkStatus
struct RadioFrame
Public Types
enum FrameType {
GHST_UL_RC_CHANS_HS4_5TO8 = 0x10 , GHST_UL_RC_CHANS_HS4_9TO12 = 0x11 , GHST_UL_RC_CHANS_HS4_13TO16 = 0x12 , GHST_UL_RC_CHANS_RSSI = 0x13 ,
GHST_UL_RC_VTX_CTRL = 0x14 , GHST_UL_VTX_SETUP = 0x20 , GHST_UL_MSP_REQ = 0x21 , GHST_UL_MSP_WRITE = 0x22 ,
GHST_DL_PACK_STAT = 0x23 , GHST_DL_GPS_PRIMARY = 0x25 , GHST_DL_GPS_SECONDARY = 0x26 , GHST_DL_MAGBARO = 0x27 ,
GHST_DL_MSP_RESP = 0x28 , GHST_UL_RC_CHANS_HS4_12_5TO8 = 0x30 , GHST_UL_RC_CHANS_HS4_12_9TO12 = 0x31 , GHST_UL_RC_CHANS_HS4_12_13TO16 = 0x32 ,
GHST_UL_RC_CHANS_12_RSSI = 0x33
}
enum DeviceAddress { GHST_ADDRESS_FLIGHT_CONTROLLER = 0x82 , GHST_ADDRESS_GOGGLES = 0x83 , GHST_ADDRESS_GHST_RECEIVER = 0x89 }
enum RFMode {
GHST_RF_MODE_NORMAL = 5 , GHST_RF_MODE_RACE = 6 , GHST_RF_MODE_PURERACE = 7 , GHST_RF_MODE_LR = 8 ,
GHST_RF_MODE_RACE250 = 10 , GHST_RF_MODE_RACE500 = 11 , GHTS_RF_MODE_SOLID150 = 12 , GHST_RF_MODE_SOLID250 = 13 ,
RF_MODE_MAX_MODES , RF_MODE_UNKNOWN
}
Public Member Functions
AP_RCProtocol_GHST (AP_RCProtocol &_frontend)
virtual ~AP_RCProtocol_GHST ()
void process_byte (uint8_t byte, uint32_t baudrate) override
void process_handshake (uint32_t baudrate) override
void update (void) override
bool is_rx_active () const override
bool is_tx_active () const
bool is_telemetry_supported () const
const volatile LinkStatus & get_link_status () const
uint16_t get_link_rate () const
const char * get_protocol_string () const
Public Member Functions inherited from AP_RCProtocol_Backend
AP_RCProtocol_Backend (AP_RCProtocol &_frontend)
virtual ~AP_RCProtocol_Backend ()
virtual void process_pulse (uint32_t width_s0, uint32_t width_s1)
uint16_t read (uint8_t chan)
void read (uint16_t *pwm, uint8_t n)
bool new_input ()
uint8_t num_channels () const
virtual void start_bind (void)
uint32_t get_rc_frame_count (void) const
void reset_rc_frame_count (void)
uint32_t get_rc_input_count (void) const
uint32_t get_rc_protocols_mask (void) const
bool protocol_enabled (enum AP_RCProtocol::rcprotocol_t protocol) const
int16_t get_RSSI (void) const
int16_t get_rx_link_quality (void) const
AP_HAL::UARTDriver * get_UART (void) const
AP_HAL::UARTDriver * get_available_UART (void) const
bool have_UART (void) const
bool is_detected () const
Static Public Member Functions
static AP_RCProtocol_GHST * get_singleton ()
Public Attributes
struct AP_RCProtocol_GHST::Frame PACKED
struct AP_RCProtocol_GHST::Channels12Bit_4Chan PACKED
struct AP_RCProtocol_GHST::RadioFrame PACKED
struct AP_RCProtocol_GHST::LinkStatisticsFrame PACKED
Private Member Functions
void _process_byte (uint32_t timestamp_us, uint8_t byte)
bool decode_ghost_packet ()
bool process_telemetry (bool check_constraint=true)
void process_link_stats_frame (const void *data)
bool write_frame (Frame *frame)
AP_HAL::UARTDriver * get_current_UART ()
void add_to_buffer (uint8_t index, uint8_t b)
int16_t derive_scaled_lq_value (uint8_t uplink_lq)
Private Attributes
struct Frame _frame
struct Frame _telemetry_frame
uint8_t _frame_ofs
uint8_t _frame_crc
const uint8_t MAX_CHANNELS = MIN((uint8_t)GHST_MAX_CHANNELS, (uint8_t)MAX_RCIN_CHANNELS)
uint16_t _channels [GHST_MAX_CHANNELS]
uint32_t _last_frame_time_us
uint32_t _last_tx_frame_time_us
uint32_t _last_rx_frame_time_us
uint32_t _start_frame_time_us
bool telem_available
bool _use_lq_for_rssi
volatile struct LinkStatus _link_status
Static Private Attributes
static AP_RCProtocol_GHST * _singleton
static const uint16_t RF_MODE_RATES [RFMode::RF_MODE_MAX_MODES]
Additional Inherited Members
Protected Member Functions inherited from AP_RCProtocol_Backend
void add_input (uint8_t num_channels, uint16_t *values, bool in_failsafe, int16_t rssi=-1, int16_t rx_link_quality=-1)
void log_data (AP_RCProtocol::rcprotocol_t prot, uint32_t timestamp, const uint8_t *data, uint8_t len) const
Static Protected Member Functions inherited from AP_RCProtocol_Backend
static void decode_11bit_channels (const uint8_t *data, uint8_t nchannels, uint16_t *values, uint16_t mult, uint16_t div, uint16_t offset)
Protected Attributes inherited from AP_RCProtocol_Backend
struct AP_RCProtocol_Backend::Channels11Bit_8Chan PACKED
AP_RCProtocol & frontend
Detailed Description
Definition at line 34 of file AP_RCProtocol_GHST.h.
Member Enumeration Documentation
DeviceAddress
enum AP_RCProtocol_GHST::DeviceAddress
Enumerator
GHST_ADDRESS_FLIGHT_CONTROLLER
GHST_ADDRESS_GOGGLES
GHST_ADDRESS_GHST_RECEIVER
Definition at line 82 of file AP_RCProtocol_GHST.h.
FrameType
enum AP_RCProtocol_GHST::FrameType
Enumerator
GHST_UL_RC_CHANS_HS4_5TO8
GHST_UL_RC_CHANS_HS4_9TO12
GHST_UL_RC_CHANS_HS4_13TO16
GHST_UL_RC_CHANS_RSSI
GHST_UL_RC_VTX_CTRL
GHST_UL_VTX_SETUP
GHST_UL_MSP_REQ
GHST_UL_MSP_WRITE
GHST_DL_PACK_STAT
GHST_DL_GPS_PRIMARY
GHST_DL_GPS_SECONDARY
GHST_DL_MAGBARO
GHST_DL_MSP_RESP
GHST_UL_RC_CHANS_HS4_12_5TO8
GHST_UL_RC_CHANS_HS4_12_9TO12
GHST_UL_RC_CHANS_HS4_12_13TO16
GHST_UL_RC_CHANS_12_RSSI
Definition at line 58 of file AP_RCProtocol_GHST.h.
RFMode
enum AP_RCProtocol_GHST::RFMode
Enumerator
GHST_RF_MODE_NORMAL
GHST_RF_MODE_RACE
GHST_RF_MODE_PURERACE
GHST_RF_MODE_LR
GHST_RF_MODE_RACE250
GHST_RF_MODE_RACE500
GHTS_RF_MODE_SOLID150
GHST_RF_MODE_SOLID250
RF_MODE_MAX_MODES
RF_MODE_UNKNOWN
Definition at line 127 of file AP_RCProtocol_GHST.h.
Constructor & Destructor Documentation
AP_RCProtocol_GHST()
AP_RCProtocol_GHST::AP_RCProtocol_GHST (AP_RCProtocol & _frontend)
Definition at line 100 of file AP_RCProtocol_GHST.cpp.
~AP_RCProtocol_GHST()
AP_RCProtocol_GHST::~AP_RCProtocol_GHST () virtual
Definition at line 115 of file AP_RCProtocol_GHST.cpp.
Member Function Documentation
_process_byte()
void AP_RCProtocol_GHST::_process_byte (uint32_t timestamp_us, uint8_t byte) private
Definition at line 129 of file AP_RCProtocol_GHST.cpp.
Referenced by process_byte().
add_to_buffer()
void AP_RCProtocol_GHST::add_to_buffer (uint8_t index, uint8_t b) inline private
Definition at line 179 of file AP_RCProtocol_GHST.h.
Referenced by _process_byte().
decode_ghost_packet()
bool AP_RCProtocol_GHST::decode_ghost_packet () private
Definition at line 255 of file AP_RCProtocol_GHST.cpp.
Referenced by _process_byte().
derive_scaled_lq_value()
int16_t AP_RCProtocol_GHST::derive_scaled_lq_value (uint8_t uplink_lq) private
Definition at line 452 of file AP_RCProtocol_GHST.cpp.
Referenced by process_link_stats_frame().
get_current_UART()
AP_HAL::UARTDriver * AP_RCProtocol_GHST::get_current_UART () inline private
Definition at line 175 of file AP_RCProtocol_GHST.h.
Referenced by process_handshake(), process_telemetry(), and write_frame().
get_link_rate()
uint16_t AP_RCProtocol_GHST::get_link_rate () const
Definition at line 125 of file AP_RCProtocol_GHST.cpp.
get_link_status()
const volatile LinkStatus & AP_RCProtocol_GHST::get_link_status () const inline
Definition at line 150 of file AP_RCProtocol_GHST.h.
get_protocol_string()
const char * AP_RCProtocol_GHST::get_protocol_string () const
Definition at line 120 of file AP_RCProtocol_GHST.cpp.
get_singleton()
static AP_RCProtocol_GHST * AP_RCProtocol_GHST::get_singleton () inline static
Definition at line 54 of file AP_RCProtocol_GHST.h.
Referenced by AP::ghost().
is_rx_active()
bool AP_RCProtocol_GHST::is_rx_active () const inline override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 43 of file AP_RCProtocol_GHST.h.
is_telemetry_supported()
bool AP_RCProtocol_GHST::is_telemetry_supported () const
Definition at line 410 of file AP_RCProtocol_GHST.cpp.
is_tx_active()
bool AP_RCProtocol_GHST::is_tx_active () const inline
Definition at line 48 of file AP_RCProtocol_GHST.h.
Referenced by process_telemetry().
process_byte()
void AP_RCProtocol_GHST::process_byte (uint8_t byte, uint32_t baudrate) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 419 of file AP_RCProtocol_GHST.cpp.
process_handshake()
void AP_RCProtocol_GHST::process_handshake (uint32_t baudrate) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 429 of file AP_RCProtocol_GHST.cpp.
process_link_stats_frame()
void AP_RCProtocol_GHST::process_link_stats_frame (const void * data) private
Definition at line 386 of file AP_RCProtocol_GHST.cpp.
Referenced by decode_ghost_packet().
process_telemetry()
bool AP_RCProtocol_GHST::process_telemetry (bool check_constraint = true) private
Definition at line 356 of file AP_RCProtocol_GHST.cpp.
Referenced by decode_ghost_packet().
update()
void AP_RCProtocol_GHST::update (void) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 201 of file AP_RCProtocol_GHST.cpp.
write_frame()
bool AP_RCProtocol_GHST::write_frame (Frame * frame) private
Definition at line 206 of file AP_RCProtocol_GHST.cpp.
Referenced by process_telemetry().
Member Data Documentation
_channels
uint16_t AP_RCProtocol_GHST::_channels[GHST_MAX_CHANNELS] private
Definition at line 177 of file AP_RCProtocol_GHST.h.
Referenced by _process_byte(), and decode_ghost_packet().
_frame
struct Frame AP_RCProtocol_GHST::_frame private
Definition at line 161 of file AP_RCProtocol_GHST.h.
Referenced by _process_byte(), add_to_buffer(), and decode_ghost_packet().
_frame_crc
uint8_t AP_RCProtocol_GHST::_frame_crc private
Definition at line 164 of file AP_RCProtocol_GHST.h.
Referenced by _process_byte().
_frame_ofs
uint8_t AP_RCProtocol_GHST::_frame_ofs private
Definition at line 163 of file AP_RCProtocol_GHST.h.
Referenced by _process_byte().
_last_frame_time_us
uint32_t AP_RCProtocol_GHST::_last_frame_time_us private
Definition at line 181 of file AP_RCProtocol_GHST.h.
Referenced by _process_byte().
_last_rx_frame_time_us
uint32_t AP_RCProtocol_GHST::_last_rx_frame_time_us private
Definition at line 183 of file AP_RCProtocol_GHST.h.
Referenced by _process_byte(), and is_rx_active().
_last_tx_frame_time_us
uint32_t AP_RCProtocol_GHST::_last_tx_frame_time_us private
Definition at line 182 of file AP_RCProtocol_GHST.h.
Referenced by _process_byte(), and is_tx_active().
_link_status
volatile struct LinkStatus AP_RCProtocol_GHST::_link_status private
Definition at line 189 of file AP_RCProtocol_GHST.h.
Referenced by _process_byte(), get_link_rate(), get_link_status(), is_telemetry_supported(), and process_link_stats_frame().
_singleton
AP_RCProtocol_GHST * AP_RCProtocol_GHST::_singleton static private
Definition at line 168 of file AP_RCProtocol_GHST.h.
Referenced by AP_RCProtocol_GHST(), get_singleton(), and ~AP_RCProtocol_GHST().
_start_frame_time_us
uint32_t AP_RCProtocol_GHST::_start_frame_time_us private
Definition at line 184 of file AP_RCProtocol_GHST.h.
Referenced by _process_byte().
_telemetry_frame
struct Frame AP_RCProtocol_GHST::_telemetry_frame private
Definition at line 162 of file AP_RCProtocol_GHST.h.
Referenced by process_telemetry().
_use_lq_for_rssi
bool AP_RCProtocol_GHST::_use_lq_for_rssi private
Definition at line 186 of file AP_RCProtocol_GHST.h.
Referenced by process_link_stats_frame().
MAX_CHANNELS
const uint8_t AP_RCProtocol_GHST::MAX_CHANNELS = MIN((uint8_t)GHST_MAX_CHANNELS, (uint8_t)MAX_RCIN_CHANNELS) private
Definition at line 166 of file AP_RCProtocol_GHST.h.
Referenced by _process_byte().
PACKED [1/4]
struct AP_RCProtocol_GHST::Frame AP_RCProtocol_GHST::PACKED
PACKED [2/4]
struct AP_RCProtocol_GHST::Channels12Bit_4Chan AP_RCProtocol_GHST::PACKED
PACKED [3/4]
struct AP_RCProtocol_GHST::RadioFrame AP_RCProtocol_GHST::PACKED
PACKED [4/4]
struct AP_RCProtocol_GHST::LinkStatisticsFrame AP_RCProtocol_GHST::PACKED
RF_MODE_RATES
const uint16_t AP_RCProtocol_GHST::RF_MODE_RATES static private
Initial value:
= {
    55, 160, 250, 19, 250, 500, 150, 250,
}
Definition at line 94 of file AP_RCProtocol_GHST.h.
Referenced by get_link_rate().
telem_available
bool AP_RCProtocol_GHST::telem_available private
Definition at line 185 of file AP_RCProtocol_GHST.h.
Referenced by process_telemetry().
The documentation for this class was generated from the following files:
libraries/AP_RCProtocol/AP_RCProtocol_GHST.h
libraries/AP_RCProtocol/AP_RCProtocol_GHST.cpp