APM:Libraries: AP_OADatabase Class Reference
AP_OADatabase Class Reference
#include <AP_OADatabase.h>
Classes
struct OA_DbItem
Public Types
enum OA_DbItemImportance { Low , Normal , High }
Public Member Functions
AP_OADatabase ()
CLASS_NO_COPY (AP_OADatabase)
void init ()
void update ()
void queue_push (const Vector3f &pos, uint32_t timestamp_ms, float distance)
bool healthy () const
const OA_DbItem & get_item (uint32_t i) const
uint16_t database_count () const
bool process_queue ()
void send_adsb_vehicle (mavlink_channel_t chan, uint16_t interval_ms)
Static Public Member Functions
static AP_OADatabase * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
enum class OutputLevel { NONE = 0 , HIGH = 1 , HIGH_AND_NORMAL = 2 , ALL = 3 }
Private Member Functions
void init_queue ()
void init_database ()
void database_item_add (const OA_DbItem &item)
void database_item_refresh (const uint16_t index, const uint32_t timestamp_ms, const float radius)
void database_item_remove (const uint16_t index)
void database_items_remove_all_expired ()
uint8_t get_send_to_gcs_flags (const OA_DbItemImportance importance)
bool is_close_to_item_in_database (const uint16_t index, const OA_DbItem &item) const
Private Attributes
AP_Int16 _queue_size_param
AP_Int16 _database_size_param
AP_Int8 _database_expiry_seconds
AP_Enum< OutputLevel > _output_level
AP_Float _beam_width
AP_Float _radius_min
AP_Float _dist_max
AP_Float _min_alt
struct {
ObjectBuffer< OA_DbItem > * items
uint16_t size
HAL_Semaphore sem
} _queue
float dist_to_radius_scalar
struct {
OA_DbItem * items
uint16_t count
uint16_t size
} _database
uint16_t _next_index_to_send [MAVLINK_COMM_NUM_BUFFERS]
uint16_t _highest_index_sent [MAVLINK_COMM_NUM_BUFFERS]
uint32_t _last_send_to_gcs_ms [MAVLINK_COMM_NUM_BUFFERS]
Static Private Attributes
static AP_OADatabase * _singleton
Detailed Description
Definition at line 8 of file AP_OADatabase.h.
Member Enumeration Documentation
OA_DbItemImportance
enum AP_OADatabase::OA_DbItemImportance
Enumerator
Low
Normal
High
Definition at line 20 of file AP_OADatabase.h.
OutputLevel
enum class AP_OADatabase::OutputLevel strong private
Enumerator
NONE
HIGH
HIGH_AND_NORMAL
ALL
Definition at line 77 of file AP_OADatabase.h.
Constructor & Destructor Documentation
AP_OADatabase()
AP_OADatabase::AP_OADatabase ()
Definition at line 109 of file AP_OADatabase.cpp.
Member Function Documentation
CLASS_NO_COPY()
AP_OADatabase::CLASS_NO_COPY (AP_OADatabase)
database_count()
uint16_t AP_OADatabase::database_count () const inline
Definition at line 47 of file AP_OADatabase.h.
Referenced by AP_OABendyRuler::calc_margin_from_object_database().
database_item_add()
void AP_OADatabase::database_item_add (const OA_DbItem & item) private
Definition at line 281 of file AP_OADatabase.cpp.
Referenced by process_queue().
database_item_refresh()
void AP_OADatabase::database_item_refresh (const uint16_t index, const uint32_t timestamp_ms, const float radius) private
Definition at line 314 of file AP_OADatabase.cpp.
Referenced by process_queue().
database_item_remove()
void AP_OADatabase::database_item_remove (const uint16_t index) private
Definition at line 291 of file AP_OADatabase.cpp.
Referenced by database_items_remove_all_expired().
database_items_remove_all_expired()
void AP_OADatabase::database_items_remove_all_expired () private
Definition at line 334 of file AP_OADatabase.cpp.
Referenced by update().
get_item()
const OA_DbItem & AP_OADatabase::get_item (uint32_t i) const inline
Definition at line 44 of file AP_OADatabase.h.
Referenced by AP_OABendyRuler::calc_margin_from_object_database().
get_send_to_gcs_flags()
uint8_t AP_OADatabase::get_send_to_gcs_flags (const OA_DbItemImportance importance) private
Definition at line 209 of file AP_OADatabase.cpp.
Referenced by database_item_add(), database_item_refresh(), database_item_remove(), and process_queue().
get_singleton()
static AP_OADatabase * AP_OADatabase::get_singleton () inline static
Definition at line 16 of file AP_OADatabase.h.
Referenced by AP::oadatabase().
healthy()
bool AP_OADatabase::healthy () const inline
Definition at line 41 of file AP_OADatabase.h.
Referenced by AP_OABendyRuler::calc_margin_from_object_database(), init(), process_queue(), queue_push(), and update().
init()
void AP_OADatabase::init ()
Definition at line 119 of file AP_OADatabase.cpp.
Referenced by AP_OAPathPlanner::init().
init_database()
void AP_OADatabase::init_database () private
Definition at line 197 of file AP_OADatabase.cpp.
Referenced by init().
init_queue()
void AP_OADatabase::init_queue () private
Definition at line 182 of file AP_OADatabase.cpp.
Referenced by init().
is_close_to_item_in_database()
bool AP_OADatabase::is_close_to_item_in_database (const uint16_t index, const OA_DbItem & item) const private
Definition at line 357 of file AP_OADatabase.cpp.
Referenced by process_queue().
process_queue()
bool AP_OADatabase::process_queue ()
Definition at line 234 of file AP_OADatabase.cpp.
Referenced by AP_OAPathPlanner::avoidance_thread(), and update().
queue_push()
void AP_OADatabase::queue_push (const Vector3f & pos, uint32_t timestamp_ms, float distance)
Definition at line 146 of file AP_OADatabase.cpp.
send_adsb_vehicle()
void AP_OADatabase::send_adsb_vehicle (mavlink_channel_t chan, uint16_t interval_ms)
update()
void AP_OADatabase::update ()
Definition at line 135 of file AP_OADatabase.cpp.
Referenced by AP_OAPathPlanner::avoidance_thread().
Member Data Documentation
_beam_width
AP_Float AP_OADatabase::_beam_width private
Definition at line 89 of file AP_OADatabase.h.
Referenced by init().
[struct]
struct { ... } AP_OADatabase::_database
Referenced by database_count(), database_item_add(), database_item_refresh(), database_item_remove(), database_items_remove_all_expired(), get_item(), healthy(), init(), init_database(), is_close_to_item_in_database(), and process_queue().
_database_expiry_seconds
AP_Int8 AP_OADatabase::_database_expiry_seconds private
Definition at line 87 of file AP_OADatabase.h.
Referenced by database_items_remove_all_expired().
_database_size_param
AP_Int16 AP_OADatabase::_database_size_param private
Definition at line 86 of file AP_OADatabase.h.
Referenced by init_database().
_dist_max
AP_Float AP_OADatabase::_dist_max private
Definition at line 91 of file AP_OADatabase.h.
Referenced by queue_push().
_highest_index_sent
uint16_t AP_OADatabase::_highest_index_sent[MAVLINK_COMM_NUM_BUFFERS] private
Definition at line 108 of file AP_OADatabase.h.
_last_send_to_gcs_ms
uint32_t AP_OADatabase::_last_send_to_gcs_ms[MAVLINK_COMM_NUM_BUFFERS] private
Definition at line 109 of file AP_OADatabase.h.
_min_alt
AP_Float AP_OADatabase::_min_alt private
Definition at line 92 of file AP_OADatabase.h.
Referenced by queue_push().
_next_index_to_send
uint16_t AP_OADatabase::_next_index_to_send[MAVLINK_COMM_NUM_BUFFERS] private
Definition at line 107 of file AP_OADatabase.h.
_output_level
AP_Enum<OutputLevel> AP_OADatabase::_output_level private
Definition at line 88 of file AP_OADatabase.h.
Referenced by get_send_to_gcs_flags().
[struct]
struct { ... } AP_OADatabase::_queue
Referenced by healthy(), init(), init_queue(), process_queue(), and queue_push().
_queue_size_param
AP_Int16 AP_OADatabase::_queue_size_param private
Definition at line 85 of file AP_OADatabase.h.
Referenced by init_queue().
_radius_min
AP_Float AP_OADatabase::_radius_min private
Definition at line 90 of file AP_OADatabase.h.
Referenced by queue_push().
_singleton
AP_OADatabase * AP_OADatabase::_singleton static private
Definition at line 111 of file AP_OADatabase.h.
Referenced by AP_OADatabase(), and get_singleton().
count
uint16_t AP_OADatabase::count
Definition at line 103 of file AP_OADatabase.h.
dist_to_radius_scalar
float AP_OADatabase::dist_to_radius_scalar private
Definition at line 99 of file AP_OADatabase.h.
Referenced by init(), and queue_push().
items [1/2]
ObjectBuffer<OA_DbItem>* AP_OADatabase::items
Definition at line 95 of file AP_OADatabase.h.
items [2/2]
OA_DbItem* AP_OADatabase::items
Definition at line 102 of file AP_OADatabase.h.
sem
HAL_Semaphore AP_OADatabase::sem
Definition at line 97 of file AP_OADatabase.h.
size
uint16_t AP_OADatabase::size
Definition at line 96 of file AP_OADatabase.h.
var_info
const AP_Param::GroupInfo AP_OADatabase::var_info static
Definition at line 39 of file AP_OADatabase.h.
The documentation for this class was generated from the following files:
libraries/AC_Avoidance/AP_OADatabase.h
libraries/AC_Avoidance/AP_OADatabase.cpp