APM:Libraries: AP_HAL::I2CDevice Class Reference
AP_HAL::I2CDevice Class Reference abstract
#include <I2CDevice.h>
Public Member Functions
I2CDevice ()
virtual ~I2CDevice ()
virtual bool set_speed (Device::Speed speed) override=0
virtual bool transfer (const uint8_t *send, uint32_t send_len, uint8_t *recv, uint32_t recv_len) override=0
virtual bool read_registers_multiple (uint8_t first_reg, uint8_t *recv, uint32_t recv_len, uint8_t times)=0
virtual Semaphore * get_semaphore () override=0
virtual Device::PeriodicHandle register_periodic_callback (uint32_t period_usec, Device::PeriodicCb) override=0
virtual bool adjust_periodic_callback (Device::PeriodicHandle h, uint32_t period_usec) override=0
virtual void set_split_transfers (bool set)
Public Member Functions inherited from AP_HAL::Device
FUNCTOR_TYPEDEF (PeriodicCb, void)
FUNCTOR_TYPEDEF (RegisterRWCb, void, uint8_t, uint8_t *, uint32_t, bool)
FUNCTOR_TYPEDEF (BankSelectCb, bool, uint8_t)
Device (enum BusType type)
enum BusType bus_type (void) const
uint8_t bus_num (void) const
uint32_t get_bus_id (void) const
uint8_t get_bus_address (void) const
void set_device_type (uint8_t devtype)
virtual ~Device ()
virtual void set_address (uint8_t address)
virtual void set_cmd_header (const CommandHeader &cmd_hdr)
virtual bool enter_xip_mode (void **map_ptr)
virtual bool exit_xip_mode ()
bool read_registers (uint8_t first_reg, uint8_t *recv, uint32_t recv_len)
bool write_register (uint8_t reg, uint8_t val, bool checked=false)
virtual void set_register_rw_callback (RegisterRWCb register_rw_callback)
bool transfer_bank (uint8_t bank, const uint8_t *send, uint32_t send_len, uint8_t *recv, uint32_t recv_len)
bool read_bank_registers (uint8_t bank, uint8_t first_reg, uint8_t *recv, uint32_t recv_len)
bool write_bank_register (uint8_t bank, uint8_t reg, uint8_t val, bool checked=false)
void set_checked_register (uint8_t bank, uint8_t reg, uint8_t val)
void set_checked_register (uint8_t reg, uint8_t val)
bool setup_checked_registers (uint8_t num_regs, uint8_t frequency=10)
bool check_next_register (void)
bool check_next_register (struct checkreg &fail)
bool read (uint8_t *recv, uint32_t recv_len)
virtual PeriodicHandle register_periodic_callback (uint32_t period_usec, PeriodicCb)=0
virtual bool unregister_callback (PeriodicHandle h)
virtual void setup_bankselect_callback (BankSelectCb bank_select)
virtual void deregister_bankselect_callback ()
virtual void register_completion_callback (AP_HAL::MemberProc proc)
virtual void register_completion_callback (AP_HAL::Proc proc)
virtual bool set_chip_select (bool set)
void set_read_flag (uint8_t flag)
uint32_t get_bus_id_devtype (uint8_t devtype) const
virtual void set_retries (uint8_t retries)
Additional Inherited Members
Public Types inherited from AP_HAL::Device
enum BusType {
BUS_TYPE_UNKNOWN = 0 , BUS_TYPE_I2C = 1 , BUS_TYPE_SPI = 2 , BUS_TYPE_UAVCAN = 3 ,
BUS_TYPE_SITL = 4 , BUS_TYPE_MSP = 5 , BUS_TYPE_SERIAL = 6 , BUS_TYPE_WSPI = 7
}
enum Speed { SPEED_HIGH , SPEED_LOW }
typedef void * PeriodicHandle
typedef void * RegisterRWHandle
Static Public Member Functions inherited from AP_HAL::Device
static uint32_t make_bus_id (enum BusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype)
static uint32_t change_bus_id (uint32_t old_id, uint8_t devtype)
static enum BusType devid_get_bus_type (uint32_t dev_id)
static uint8_t devid_get_bus (uint32_t dev_id)
static uint8_t devid_get_address (uint32_t dev_id)
static uint8_t devid_get_devtype (uint32_t dev_id)
Protected Member Functions inherited from AP_HAL::Device
void set_device_address (uint8_t address)
void set_device_bus (uint8_t bus)
Protected Attributes inherited from AP_HAL::Device
uint8_t _read_flag = 0
union DeviceId _bus_id
Detailed Description
Definition at line 28 of file I2CDevice.h.
Constructor & Destructor Documentation
I2CDevice()
AP_HAL::I2CDevice::I2CDevice () inline
Definition at line 30 of file I2CDevice.h.
~I2CDevice()
virtual AP_HAL::I2CDevice::~I2CDevice () inline virtual
Reimplemented in ChibiOS::I2CDevice, Empty::I2CDevice, ESP32::I2CDevice, Linux::I2CDevice, and HALSITL::I2CDevice.
Definition at line 32 of file I2CDevice.h.
Member Function Documentation
adjust_periodic_callback()
virtual bool AP_HAL::I2CDevice::adjust_periodic_callback (Device::PeriodicHandle h, uint32_t period_usec) override pure virtual
Implements AP_HAL::Device.
Implemented in ChibiOS::I2CDevice, Empty::I2CDevice, ESP32::I2CDevice, Linux::I2CDevice, and HALSITL::I2CDevice.
Referenced by AP_BattMonitor_SMBus_SUI::init().
get_semaphore()
virtual Semaphore * AP_HAL::I2CDevice::get_semaphore () override pure virtual
Implements AP_HAL::Device.
Implemented in ChibiOS::I2CDevice, Empty::I2CDevice, ESP32::I2CDevice, Linux::I2CDevice, and HALSITL::I2CDevice.
Referenced by AP_InertialSensor_L3G4200D::_accel_init(), Linux::RCOutput_Bebop::_clear_error(), Linux::RCOutput_Bebop::_get_info(), AP_InertialSensor_L3G4200D::_gyro_init(), AP_RangeFinder_MaxsonarI2CXL::_init(), Linux::RCOutput_Bebop::_play_sound(), Linux::RCOutput_Bebop::_set_ref_speed(), Linux::RCOutput_Bebop::_start_prop(), Linux::RCOutput_Bebop::_stop_prop(), Linux::RCOutput_Bebop::_toggle_gpio(), AP_RangeFinder_VL53L1X::detect(), AP_RangeFinder_LightWareI2C::detect(), AP_RangeFinder_VL53L0X::detect(), Linux::RCOutput_PCA9685::force_safety_off(), Linux::RCOutput_PCA9685::force_safety_on(), AP_AK09916_BusDriver_HALDevice::get_semaphore(), AP_AK8963_BusDriver_HALDevice::get_semaphore(), AP_Baro_ICM20789::init(), AP_Baro_ICP101XX::init(), AP_Baro_ICP201XX::init(), AP_RangeFinder_Benewake_TFMiniPlus::init(), AP_Airspeed_ASP5033::init(), AP_Airspeed_MS5525::init(), AP_Airspeed_SDP3X::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_RangeFinder_TeraRangerI2C::init(), IS31FL3195::init(), LP5562::init(), NCP5623::init(), PCA9685LED_I2C::init(), ToshibaLED_I2C::init(), Linux::RCOutput_Bebop::play_note(), AP_Airspeed_MS4525::probe(), Linux::RCOutput_PCA9685::push(), Linux::RCOutput_Bebop::read_obs_data(), Linux::RCOutput_PCA9685::reset_all_channels(), Linux::RCOutput_PCA9685::set_freq(), AP_Airspeed_DLVR::setup(), AP_ICEngine_TCA9554::TCA9554_init(), and AP_ICEngine_TCA9554::TCA9554_set().
read_registers_multiple()
virtual bool AP_HAL::I2CDevice::read_registers_multiple (uint8_t first_reg, uint8_t * recv, uint32_t recv_len, uint8_t times) pure virtual
Implemented in ChibiOS::I2CDevice, Empty::I2CDevice, ESP32::I2CDevice, Linux::I2CDevice, and HALSITL::I2CDevice.
register_periodic_callback()
virtual Device::PeriodicHandle AP_HAL::I2CDevice::register_periodic_callback (uint32_t period_usec, Device::PeriodicCb) override pure virtual
Referenced by AP_RangeFinder_MaxsonarI2CXL::_init(), AP_ADC_ADS1115::init(), AP_Baro_ICM20789::init(), AP_Baro_ICP101XX::init(), AP_Baro_ICP201XX::init(), AP_RangeFinder_Benewake_TFMiniPlus::init(), AP_RangeFinder_VL53L0X::init(), AP_Airspeed_ASP5033::init(), AP_Airspeed_MS4525::init(), AP_Airspeed_MS5525::init(), AP_Airspeed_SDP3X::init(), AP_RangeFinder_VL53L1X::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_RangeFinder_TeraRangerI2C::init(), AP_BattMonitor_SMBus::init(), IS31FL3195::init(), LP5562::init(), NCP5623::init(), PCA9685LED_I2C::init(), ToshibaLED_I2C::init(), AP_RangeFinder_LightWareI2C::legacy_init(), AP_AK09916_BusDriver_HALDevice::register_periodic_callback(), AP_AK8963_BusDriver_HALDevice::register_periodic_callback(), AP_Airspeed_DLVR::setup(), AP_RangeFinder_LightWareI2C::sf20_init(), and AP_InertialSensor_L3G4200D::start().
set_speed()
virtual bool AP_HAL::I2CDevice::set_speed (Device::Speed speed) override pure virtual
Implements AP_HAL::Device.
Implemented in Empty::I2CDevice.
Referenced by AP_Airspeed_ASP5033::init(), and AP_Airspeed_DLVR::setup().
set_split_transfers()
virtual void AP_HAL::I2CDevice::set_split_transfers (bool set) inline virtual
Reimplemented in ChibiOS::I2CDevice, Linux::I2CDevice, and HALSITL::I2CDevice.
Definition at line 69 of file I2CDevice.h.
Referenced by AP_RangeFinder_PulsedLightLRF::init().
transfer()
virtual bool AP_HAL::I2CDevice::transfer (const uint8_t * send, uint32_t send_len, uint8_t * recv, uint32_t recv_len) override pure virtual
Implements AP_HAL::Device.
Implemented in ChibiOS::I2CDevice, Empty::I2CDevice, ESP32::I2CDevice, Linux::I2CDevice, and HALSITL::I2CDevice.
Referenced by Linux::CameraSensor_Mt9v117::_apply_patch(), Linux::RCOutput_Bebop::_clear_error(), AP_Airspeed_MS4525::_collect(), AP_Airspeed_MS4525::_measure(), Linux::CameraSensor_Mt9v117::_read_reg16(), Linux::CameraSensor_Mt9v117::_read_reg8(), AP_Airspeed_SDP3X::_send_command(), Linux::RCOutput_Bebop::_set_ref_speed(), AP_ADC_ADS1115::_start_conversion(), Linux::RCOutput_Bebop::_start_prop(), Linux::RCOutput_Bebop::_stop_prop(), AP_Airspeed_SDP3X::_timer(), PCA9685LED_I2C::_timer(), ToshibaLED_I2C::_timer(), Linux::CameraSensor_Mt9v117::_write_reg16(), Linux::CameraSensor_Mt9v117::_write_reg32(), Linux::CameraSensor_Mt9v117::_write_reg8(), AP_RangeFinder_TeraRangerI2C::collect_raw(), AP_Baro_ICP201XX::dummy_reg(), AP_RangeFinder_MaxsonarI2CXL::get_reading(), AP_RangeFinder_Benewake_TFMiniPlus::init(), AP_RangeFinder_VL53L0X::init(), AP_Airspeed_MS5525::init(), AP_Airspeed_SDP3X::init(), PCA9685LED_I2C::init(), ToshibaLED_I2C::init(), AP_RangeFinder_LightWareI2C::legacy_get_reading(), AP_RangeFinder_LightWareI2C::legacy_init(), AP_RangeFinder_TeraRangerI2C::measure(), Linux::RCOutput_Bebop::play_note(), Linux::RCOutput_PCA9685::push(), AP_Baro_ICM20789::read_calibration_data(), AP_Baro_ICP101XX::read_measure_results(), AP_Airspeed_MS5525::read_prom(), AP_Baro_ICP201XX::read_reg(), AP_RangeFinder_VL53L1X::read_register(), AP_RangeFinder_VL53L1X::read_register16(), AP_RangeFinder_VL53L0X::read_register16(), AP_Baro_ICP101XX::read_response(), Linux::RCOutput_PCA9685::reset_all_channels(), AP_Baro_ICM20789::send_cmd16(), AP_Baro_ICP101XX::send_command(), AP_Baro_ICP101XX::send_command(), AP_RangeFinder_MaxsonarI2CXL::start_reading(), AP_Airspeed_MS5525::timer(), AP_RangeFinder_Benewake_TFMiniPlus::timer(), AP_Baro_ICM20789::timer(), NCP5623::write(), AP_RangeFinder_LightWareI2C::write_bytes(), AP_Baro_ICP201XX::write_reg(), AP_RangeFinder_VL53L1X::write_register(), AP_RangeFinder_VL53L1X::write_register16(), AP_RangeFinder_VL53L0X::write_register16(), and AP_RangeFinder_VL53L1X::write_register32().
The documentation for this class was generated from the following file:
libraries/AP_HAL/I2CDevice.h