APM:Libraries: AP_RangeFinder_TeraRangerI2C Class Reference
AP_RangeFinder_TeraRangerI2C Class Reference
#include <AP_RangeFinder_TeraRangerI2C.h>
Public Member Functions
void update (void) override
Public Member Functions inherited from AP_RangeFinder_Backend
AP_RangeFinder_Backend (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params)
virtual ~AP_RangeFinder_Backend (void)
virtual void init_serial (uint8_t serial_instance)
virtual void handle_msg (const mavlink_message_t &msg)
enum Rotation orientation () const
float distance () const
uint16_t distance_cm () const
int8_t signal_quality_pct () const WARN_IF_UNUSED
uint16_t voltage_mv () const
virtual int16_t max_distance_cm () const
virtual int16_t min_distance_cm () const
int16_t ground_clearance_cm () const
MAV_DISTANCE_SENSOR get_mav_distance_sensor_type () const
RangeFinder::Status status () const
RangeFinder::Type type () const
bool has_data () const
uint8_t range_valid_count () const
const Vector3f & get_pos_offset () const
uint32_t last_reading_ms () const
virtual bool get_temp (float &temp) const
RangeFinder::Type allocated_type () const
Static Public Member Functions
static AP_RangeFinder_Backend * detect (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > i2c_dev)
Protected Member Functions
virtual MAV_DISTANCE_SENSOR _get_mav_distance_sensor_type () const override
Protected Member Functions inherited from AP_RangeFinder_Backend
void update_status (RangeFinder::RangeFinder_State &state_arg) const
void update_status ()
void set_status (RangeFinder::Status status)
Private Member Functions
AP_RangeFinder_TeraRangerI2C (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > i2c_dev)
bool measure (void)
bool collect_raw (uint16_t &raw_distance)
bool process_raw_measure (uint16_t raw_distance, uint16_t &distance_cm)
bool init (void)
void timer (void)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev
struct {
uint32_t sum
uint32_t count
} accum
Additional Inherited Members
Static Protected Member Functions inherited from AP_RangeFinder_Backend
static void set_status (RangeFinder::RangeFinder_State &state_arg, RangeFinder::Status status)
Protected Attributes inherited from AP_RangeFinder_Backend
RangeFinder::RangeFinder_State & state
AP_RangeFinder_Params & params
HAL_Semaphore _sem
RangeFinder::Type _backend_type
Detailed Description
Definition at line 12 of file AP_RangeFinder_TeraRangerI2C.h.
Constructor & Destructor Documentation
AP_RangeFinder_TeraRangerI2C()
AP_RangeFinder_TeraRangerI2C::AP_RangeFinder_TeraRangerI2C (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > i2c_dev) private
Definition at line 35 of file AP_RangeFinder_TeraRangerI2C.cpp.
Referenced by detect().
Member Function Documentation
_get_mav_distance_sensor_type()
virtual MAV_DISTANCE_SENSOR AP_RangeFinder_TeraRangerI2C::_get_mav_distance_sensor_type () const inline override protected virtual
Implements AP_RangeFinder_Backend.
Definition at line 25 of file AP_RangeFinder_TeraRangerI2C.h.
collect_raw()
bool AP_RangeFinder_TeraRangerI2C::collect_raw (uint16_t & raw_distance) private
Definition at line 118 of file AP_RangeFinder_TeraRangerI2C.cpp.
Referenced by init(), and timer().
detect()
AP_RangeFinder_Backend * AP_RangeFinder_TeraRangerI2C::detect (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > i2c_dev) static
Definition at line 48 of file AP_RangeFinder_TeraRangerI2C.cpp.
Referenced by RangeFinder::detect_instance().
init()
bool AP_RangeFinder_TeraRangerI2C::init (void) private
Definition at line 72 of file AP_RangeFinder_TeraRangerI2C.cpp.
Referenced by detect().
measure()
bool AP_RangeFinder_TeraRangerI2C::measure (void) private
Definition at line 111 of file AP_RangeFinder_TeraRangerI2C.cpp.
Referenced by init(), and timer().
process_raw_measure()
bool AP_RangeFinder_TeraRangerI2C::process_raw_measure (uint16_t raw_distance, uint16_t & distance_cm) private
Definition at line 137 of file AP_RangeFinder_TeraRangerI2C.cpp.
Referenced by timer().
timer()
void AP_RangeFinder_TeraRangerI2C::timer (void) private
Definition at line 159 of file AP_RangeFinder_TeraRangerI2C.cpp.
Referenced by init().
update()
void AP_RangeFinder_TeraRangerI2C::update (void) override virtual
Implements AP_RangeFinder_Backend.
Definition at line 180 of file AP_RangeFinder_TeraRangerI2C.cpp.
Member Data Documentation
[struct]
struct { ... } AP_RangeFinder_TeraRangerI2C::accum
Referenced by timer(), and update().
count
uint32_t AP_RangeFinder_TeraRangerI2C::count
Definition at line 45 of file AP_RangeFinder_TeraRangerI2C.h.
dev
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_RangeFinder_TeraRangerI2C::dev private
Definition at line 41 of file AP_RangeFinder_TeraRangerI2C.h.
Referenced by collect_raw(), init(), and measure().
sum
uint32_t AP_RangeFinder_TeraRangerI2C::sum
Definition at line 44 of file AP_RangeFinder_TeraRangerI2C.h.
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder_TeraRangerI2C.h
libraries/AP_RangeFinder/AP_RangeFinder_TeraRangerI2C.cpp