APM:Libraries: SITL::SerialDevice Class Reference
SITL::SerialDevice Class Reference
#include <SIM_SerialDevice.h>
Public Member Functions
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Protected Member Functions
bool init_sitl_pointer () WARN_IF_UNUSED
Protected Attributes
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Private Member Functions
bool is_match_baud (void) const
ssize_t corrupt_transfer (char *buffer, const ssize_t ret, const size_t size) const
Private Attributes
uint32_t autopilot_baud
Detailed Description
Definition at line 26 of file SIM_SerialDevice.h.
Constructor & Destructor Documentation
SerialDevice()
SerialDevice::SerialDevice (uint16_t tx_bufsize = 512, uint16_t rx_bufsize = 512)
Definition at line 30 of file SIM_SerialDevice.cpp.
Member Function Documentation
corrupt_transfer()
ssize_t SITL::SerialDevice::corrupt_transfer (char * buffer, const ssize_t ret, const size_t size) const private
device_baud()
virtual uint32_t SITL::SerialDevice::device_baud () const inline virtual
Reimplemented in SITL::RF_NMEA.
Definition at line 40 of file SIM_SerialDevice.h.
init_sitl_pointer()
bool SerialDevice::init_sitl_pointer () protected
Definition at line 36 of file SIM_SerialDevice.cpp.
Referenced by SITL::Vicon::update(), SITL::InertialLabs::update(), SITL::MicroStrain::update(), and SITL::VectorNav::update().
is_match_baud()
bool SerialDevice::is_match_baud (void) const private
baudrates match
Return values
true matched baudreate
false unmatched baudreate
Definition at line 144 of file SIM_SerialDevice.cpp.
read_from_autopilot()
ssize_t SerialDevice::read_from_autopilot (char * buffer, size_t size) const
Definition at line 79 of file SIM_SerialDevice.cpp.
Referenced by SITL::RF_Wasp::check_configuration(), SITL::RF_LightWareSerial::check_synced(), SITL::ADSB::send_report(), SITL::CRSF::update(), SITL::EFI_MegaSquirt::update(), SITL::Frsky_D::update(), SITL::FETtecOneWireESC::update_input(), SITL::PS_LightWare_SF45B::update_input(), SITL::PS_RPLidar::update_input(), SITL::EFI_Hirth::update_receive(), and SITL::ADSB_Sagetech_MXS::update_serial_input().
read_from_device()
ssize_t SerialDevice::read_from_device (char * buffer, size_t size) const
Definition at line 111 of file SIM_SerialDevice.cpp.
Referenced by HALSITL::UARTDriver::handle_reading_from_device_to_readbuffer().
set_autopilot_baud()
void SITL::SerialDevice::set_autopilot_baud (uint32_t baud) inline
Definition at line 35 of file SIM_SerialDevice.h.
Referenced by HALSITL::UARTDriver::_begin().
write_to_autopilot()
ssize_t SerialDevice::write_to_autopilot (const char * buffer, size_t size) const virtual
Definition at line 101 of file SIM_SerialDevice.cpp.
Referenced by SITL::RF_Wasp::check_configuration(), SITL::VectorNav::nmea_printf(), SITL::PS_LightWare_SF45B::send(), SITL::MicroStrain::send_packet(), SITL::InertialLabs::send_packet(), SITL::VectorNav::send_packet1(), SITL::VectorNav::send_packet2(), SITL::ADSB::send_report(), SITL::FETtecOneWireESC::send_response(), SITL::PS_RPLidar::send_response_descriptor(), SITL::EFI_MegaSquirt::send_table(), SITL::SerialRangeFinder::send_temperature(), SITL::ADSB_Sagetech_MXS::send_vehicle_message_state_vector(), SITL::ADSB_Sagetech_MXS::send_vehicle_message_status_report(), SITL::AIS::update(), SITL::CRSF::update(), SITL::SerialProximitySensor::update(), SITL::SerialRangeFinder::update(), SITL::PS_RPLidar::update_input(), SITL::PS_TeraRangerTower::update_output(), SITL::PS_RPLidar::update_output_scan(), SITL::IntelligentEnergy24::update_send(), SITL::RichenPower::update_send(), SITL::ADSB_Sagetech_MXS::update_serial_output(), and SITL::Vicon::update_vicon_position_estimate().
write_to_device()
ssize_t SerialDevice::write_to_device (const char * buffer, size_t size) const
Definition at line 132 of file SIM_SerialDevice.cpp.
Referenced by HALSITL::UARTDriver::handle_writing_from_writebuffer_to_device().
Member Data Documentation
_sitl
class SIM* SITL::SerialDevice::_sitl protected
Definition at line 44 of file SIM_SerialDevice.h.
Referenced by SITL::MicroStrain5::send_filter_packet(), SITL::MicroStrain7::send_filter_packet(), SITL::MicroStrain5::send_gnss_packet(), SITL::MicroStrain7::send_gnss_packet(), SITL::MicroStrain::send_imu_packet(), SITL::InertialLabs::send_packet(), SITL::VectorNav::send_packet1(), SITL::VectorNav::send_packet2(), SITL::ADSB::send_report(), SITL::Vicon::should_send(), SITL::ADSB::update(), SITL::ADSB::update_simulated_vehicles(), and SITL::Vicon::update_vicon_position_estimate().
autopilot_baud
uint32_t SITL::SerialDevice::autopilot_baud private
Definition at line 55 of file SIM_SerialDevice.h.
Referenced by set_autopilot_baud().
from_autopilot
ByteBuffer* SITL::SerialDevice::from_autopilot protected
Definition at line 47 of file SIM_SerialDevice.h.
to_autopilot
ByteBuffer* SITL::SerialDevice::to_autopilot protected
Definition at line 46 of file SIM_SerialDevice.h.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_SerialDevice.h
libraries/SITL/SIM_SerialDevice.cpp