APM:Libraries: SlewCalculator2D Class Reference
SlewCalculator2D Class Reference
#include <SlewCalculator2D.h>
Public Member Functions
SlewCalculator2D ()
CLASS_NO_COPY (SlewCalculator2D)
void update (const Vector2f &sample, float dt)
float get_slew_rate () const
Private Attributes
SlewLimiter xlimiter
SlewLimiter ylimiter
float slew_rate_max = 0
float slew_rate_tau = 1.0
Detailed Description
Definition at line 12 of file SlewCalculator2D.h.
Constructor & Destructor Documentation
SlewCalculator2D()
SlewCalculator2D::SlewCalculator2D ()
Definition at line 21 of file SlewCalculator2D.cpp.
Member Function Documentation
CLASS_NO_COPY()
SlewCalculator2D::CLASS_NO_COPY (SlewCalculator2D)
get_slew_rate()
float SlewCalculator2D::get_slew_rate () const
Definition at line 40 of file SlewCalculator2D.cpp.
Referenced by AC_PID_2D::get_slew_rate(), and AC_PID_2D::update_all().
update()
void SlewCalculator2D::update (const Vector2f & sample, float dt)
Definition at line 28 of file SlewCalculator2D.cpp.
Referenced by AC_PID_2D::update_all().
Member Data Documentation
slew_rate_max
float SlewCalculator2D::slew_rate_max = 0 private
Definition at line 28 of file SlewCalculator2D.h.
slew_rate_tau
float SlewCalculator2D::slew_rate_tau = 1.0 private
Definition at line 29 of file SlewCalculator2D.h.
xlimiter
SlewLimiter SlewCalculator2D::xlimiter private
Definition at line 25 of file SlewCalculator2D.h.
Referenced by get_slew_rate(), and update().
ylimiter
SlewLimiter SlewCalculator2D::ylimiter private
Definition at line 26 of file SlewCalculator2D.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/Filter/SlewCalculator2D.h
libraries/Filter/SlewCalculator2D.cpp