APM:Libraries: AP_DAL_Airspeed Class Reference
AP_DAL_Airspeed Class Reference
#include <AP_DAL_Airspeed.h>
Public Member Functions
bool healthy (uint8_t i) const
bool healthy () const
bool use (uint8_t i) const
bool use () const
float get_airspeed (uint8_t i) const
float get_airspeed () const
uint32_t last_update_ms (uint8_t i) const
uint32_t last_update_ms () const
uint8_t get_num_sensors (void) const
uint8_t get_primary (void) const
AP_DAL_Airspeed ()
void start_frame ()
void handle_message (const log_RASH &msg)
void handle_message (const log_RASI &msg)
Private Attributes
struct log_RASH _RASH
struct log_RASI _RASI [AIRSPEED_MAX_SENSORS]
Detailed Description
Definition at line 7 of file AP_DAL_Airspeed.h.
Constructor & Destructor Documentation
AP_DAL_Airspeed()
AP_DAL_Airspeed::AP_DAL_Airspeed ()
Definition at line 6 of file AP_DAL_Airspeed.cpp.
Member Function Documentation
get_airspeed() [1/2]
float AP_DAL_Airspeed::get_airspeed () const inline
Definition at line 33 of file AP_DAL_Airspeed.h.
Referenced by get_airspeed().
get_airspeed() [2/2]
float AP_DAL_Airspeed::get_airspeed (uint8_t i) const inline
Definition at line 30 of file AP_DAL_Airspeed.h.
get_num_sensors()
uint8_t AP_DAL_Airspeed::get_num_sensors (void) const inline
Definition at line 42 of file AP_DAL_Airspeed.h.
get_primary()
uint8_t AP_DAL_Airspeed::get_primary (void) const inline
Definition at line 45 of file AP_DAL_Airspeed.h.
Referenced by get_airspeed(), healthy(), last_update_ms(), NavEKF3_core::update_airspeed_selection(), and use().
handle_message() [1/2]
void AP_DAL_Airspeed::handle_message (const log_RASH & msg) inline
Definition at line 52 of file AP_DAL_Airspeed.h.
Referenced by AP_DAL::handle_message(), and AP_DAL::handle_message().
handle_message() [2/2]
void AP_DAL_Airspeed::handle_message (const log_RASI & msg) inline
Definition at line 55 of file AP_DAL_Airspeed.h.
healthy() [1/2]
bool AP_DAL_Airspeed::healthy () const inline
Definition at line 17 of file AP_DAL_Airspeed.h.
Referenced by healthy().
healthy() [2/2]
bool AP_DAL_Airspeed::healthy (uint8_t i) const inline
Definition at line 13 of file AP_DAL_Airspeed.h.
last_update_ms() [1/2]
uint32_t AP_DAL_Airspeed::last_update_ms () const inline
Definition at line 39 of file AP_DAL_Airspeed.h.
Referenced by last_update_ms().
last_update_ms() [2/2]
uint32_t AP_DAL_Airspeed::last_update_ms (uint8_t i) const inline
Definition at line 38 of file AP_DAL_Airspeed.h.
start_frame()
void AP_DAL_Airspeed::start_frame ()
Definition at line 15 of file AP_DAL_Airspeed.cpp.
Referenced by AP_DAL::start_frame().
use() [1/2]
bool AP_DAL_Airspeed::use () const inline
Definition at line 25 of file AP_DAL_Airspeed.h.
Referenced by use().
use() [2/2]
bool AP_DAL_Airspeed::use (uint8_t i) const inline
Definition at line 22 of file AP_DAL_Airspeed.h.
Member Data Documentation
_RASH
struct log_RASH AP_DAL_Airspeed::_RASH private
Definition at line 61 of file AP_DAL_Airspeed.h.
Referenced by get_num_sensors(), get_primary(), handle_message(), and start_frame().
_RASI
struct log_RASI AP_DAL_Airspeed::_RASI[AIRSPEED_MAX_SENSORS] private
Definition at line 62 of file AP_DAL_Airspeed.h.
Referenced by AP_DAL_Airspeed(), get_airspeed(), handle_message(), healthy(), last_update_ms(), start_frame(), and use().
The documentation for this class was generated from the following files:
libraries/AP_DAL/AP_DAL_Airspeed.h
libraries/AP_DAL/AP_DAL_Airspeed.cpp