APM:Libraries: AP_CustomRotations Class Reference
AP_CustomRotations Class Reference
#include <AP_CustomRotations.h>
Public Member Functions
AP_CustomRotations ()
CLASS_NO_COPY (AP_CustomRotations)
void init ()
void from_rotation (enum Rotation r, QuaternionD &q)
void from_rotation (enum Rotation r, Quaternion &q)
void rotate (enum Rotation r, Vector3d &v)
void rotate (enum Rotation r, Vector3f &v)
void convert (Rotation r, float roll, float pitch, float yaw)
void set (Rotation r, float roll, float pitch, float yaw)
Static Public Member Functions
static AP_CustomRotations * get_singleton (void)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
AP_CustomRotation * get_rotation (Rotation r)
Private Attributes
AP_Int8 enable
AP_CustomRotation * rotations [NUM_CUST_ROT]
AP_CustomRotation_params params [NUM_CUST_ROT]
Static Private Attributes
static AP_CustomRotations * singleton
Detailed Description
Definition at line 49 of file AP_CustomRotations.h.
Constructor & Destructor Documentation
AP_CustomRotations()
AP_CustomRotations::AP_CustomRotations ()
Definition at line 45 of file AP_CustomRotations.cpp.
Member Function Documentation
CLASS_NO_COPY()
AP_CustomRotations::CLASS_NO_COPY (AP_CustomRotations)
convert()
void AP_CustomRotations::convert (Rotation r, float roll, float pitch, float yaw)
Definition at line 72 of file AP_CustomRotations.cpp.
Referenced by Compass::init(), and AP_AHRS::init().
from_rotation() [1/2]
void AP_CustomRotations::from_rotation (enum Rotation r, Quaternion & q)
Definition at line 107 of file AP_CustomRotations.cpp.
from_rotation() [2/2]
void AP_CustomRotations::from_rotation (enum Rotation r, QuaternionD & q)
Definition at line 98 of file AP_CustomRotations.cpp.
Referenced by TEST().
get_rotation()
AP_CustomRotation * AP_CustomRotations::get_rotation (Rotation r) private
Definition at line 134 of file AP_CustomRotations.cpp.
Referenced by convert(), from_rotation(), from_rotation(), init(), rotate(), rotate(), and set().
get_singleton()
static AP_CustomRotations * AP_CustomRotations::get_singleton (void) inline static
Definition at line 55 of file AP_CustomRotations.h.
Referenced by AP::custom_rotations().
init()
void AP_CustomRotations::init ()
Definition at line 57 of file AP_CustomRotations.cpp.
Referenced by AP_Vehicle::setup().
rotate() [1/2]
void AP_CustomRotations::rotate (enum Rotation r, Vector3d & v)
Definition at line 116 of file AP_CustomRotations.cpp.
Referenced by TEST().
rotate() [2/2]
void AP_CustomRotations::rotate (enum Rotation r, Vector3f & v)
Definition at line 125 of file AP_CustomRotations.cpp.
set()
void AP_CustomRotations::set (Rotation r, float roll, float pitch, float yaw)
Definition at line 86 of file AP_CustomRotations.cpp.
Referenced by TEST(), test_euler(), and test_euler().
Member Data Documentation
enable
AP_Int8 AP_CustomRotations::enable private
Definition at line 72 of file AP_CustomRotations.h.
Referenced by get_rotation(), and init().
params
AP_CustomRotation_params AP_CustomRotations::params[NUM_CUST_ROT] private
Definition at line 78 of file AP_CustomRotations.h.
Referenced by get_rotation().
rotations
AP_CustomRotation* AP_CustomRotations::rotations[NUM_CUST_ROT] private
Definition at line 76 of file AP_CustomRotations.h.
Referenced by get_rotation().
singleton
AP_CustomRotations * AP_CustomRotations::singleton static private
Definition at line 80 of file AP_CustomRotations.h.
Referenced by AP_CustomRotations(), and get_singleton().
var_info
const AP_Param::GroupInfo AP_CustomRotations::var_info static
Initial value:
= {
    AP_GROUPINFO_FLAGS("_ENABLE", 1, AP_CustomRotations, enable, 0, AP_PARAM_FLAG_ENABLE),
    AP_SUBGROUPINFO(params[0], "1_", 2, AP_CustomRotations, AP_CustomRotation_params),
    AP_SUBGROUPINFO(params[1], "2_", 3, AP_CustomRotations, AP_CustomRotation_params),
    AP_GROUPEND
}
Definition at line 12 of file AP_CustomRotations.h.
The documentation for this class was generated from the following files:
libraries/AP_CustomRotations/AP_CustomRotations.h
libraries/AP_CustomRotations/AP_CustomRotations.cpp