APM:Libraries: AP_Frsky_Telem Class Reference
AP_Frsky_Telem Class Reference
#include <AP_Frsky_Telem.h>
Public Member Functions
AP_Frsky_Telem ()
~AP_Frsky_Telem ()
CLASS_NO_COPY (AP_Frsky_Telem)
bool init (bool use_external_data=false)
void queue_message (MAV_SEVERITY severity, const char *text)
Static Public Member Functions
static AP_Frsky_Telem * get_singleton (void)
static bool get_telem_data (AP_Frsky_Backend::sport_packet_t *packet_array, uint8_t &packet_count, const uint8_t max_size)
static bool set_telem_data (const uint8_t frame, const uint16_t appid, const uint32_t data)
Private Member Functions
bool _get_telem_data (AP_Frsky_Backend::sport_packet_t *packet_array, uint8_t &packet_count, const uint8_t max_size)
bool _set_telem_data (const uint8_t frame, const uint16_t appid, const uint32_t data)
Static Private Member Functions
static void try_create_singleton_for_external_data (void)
Private Attributes
AP_Frsky_Backend * _backend
AP_Frsky_Parameters * _frsky_parameters
Static Private Attributes
static AP_Frsky_Telem * singleton
Detailed Description
Definition at line 26 of file AP_Frsky_Telem.h.
Constructor & Destructor Documentation
AP_Frsky_Telem()
AP_Frsky_Telem::AP_Frsky_Telem ()
Definition at line 44 of file AP_Frsky_Telem.cpp.
Referenced by try_create_singleton_for_external_data().
~AP_Frsky_Telem()
AP_Frsky_Telem::~AP_Frsky_Telem (void)
Definition at line 53 of file AP_Frsky_Telem.cpp.
Member Function Documentation
_get_telem_data()
bool AP_Frsky_Telem::_get_telem_data (AP_Frsky_Backend::sport_packet_t * packet_array, uint8_t & packet_count, const uint8_t max_size) private
Definition at line 94 of file AP_Frsky_Telem.cpp.
Referenced by get_telem_data().
_set_telem_data()
bool AP_Frsky_Telem::_set_telem_data (const uint8_t frame, const uint16_t appid, const uint32_t data) private
Definition at line 106 of file AP_Frsky_Telem.cpp.
Referenced by set_telem_data().
CLASS_NO_COPY()
AP_Frsky_Telem::CLASS_NO_COPY (AP_Frsky_Telem)
get_singleton()
static AP_Frsky_Telem * AP_Frsky_Telem::get_singleton (void) inline static
Definition at line 39 of file AP_Frsky_Telem.h.
Referenced by AP::frsky_telem().
get_telem_data()
bool AP_Frsky_Telem::get_telem_data (AP_Frsky_Backend::sport_packet_t * packet_array, uint8_t & packet_count, const uint8_t max_size) static
Definition at line 130 of file AP_Frsky_Telem.cpp.
Referenced by AP_RCProtocol_FPort::decode_downlink().
init()
bool AP_Frsky_Telem::init (bool use_external_data = false)
Definition at line 61 of file AP_Frsky_Telem.cpp.
Referenced by try_create_singleton_for_external_data().
queue_message()
void AP_Frsky_Telem::queue_message (MAV_SEVERITY severity, const char * text) inline
Definition at line 50 of file AP_Frsky_Telem.h.
set_telem_data()
bool AP_Frsky_Telem::set_telem_data (const uint8_t frame, const uint16_t appid, const uint32_t data) static
Definition at line 143 of file AP_Frsky_Telem.cpp.
Referenced by AP_RCProtocol_FPort::decode_downlink().
try_create_singleton_for_external_data()
void AP_Frsky_Telem::try_create_singleton_for_external_data (void) static private
Definition at line 115 of file AP_Frsky_Telem.cpp.
Referenced by get_telem_data(), and set_telem_data().
Member Data Documentation
_backend
AP_Frsky_Backend* AP_Frsky_Telem::_backend private
Definition at line 59 of file AP_Frsky_Telem.h.
Referenced by _get_telem_data(), _set_telem_data(), init(), and queue_message().
_frsky_parameters
AP_Frsky_Parameters* AP_Frsky_Telem::_frsky_parameters private
Definition at line 60 of file AP_Frsky_Telem.h.
Referenced by AP_Frsky_Telem(), and init().
singleton
AP_Frsky_Telem * AP_Frsky_Telem::singleton static private
Definition at line 69 of file AP_Frsky_Telem.h.
Referenced by AP_Frsky_Telem(), get_singleton(), get_telem_data(), set_telem_data(), try_create_singleton_for_external_data(), and ~AP_Frsky_Telem().
The documentation for this class was generated from the following files:
libraries/AP_Frsky_Telem/AP_Frsky_Telem.h
libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp