APM:Libraries: Bitmask< num_bits > Class Template Reference
Bitmask< num_bits > Class Template Reference
#include <Bitmask.h>
Public Member Functions
Bitmask ()
Bitmask & operator= (const Bitmask &other)
bool operator== (const Bitmask &other)
bool operator!= (const Bitmask &other)
Bitmask (const Bitmask &other)=delete
void set (uint16_t bit)
void setall (void)
void clear (uint16_t bit)
void setonoff (uint16_t bit, bool onoff)
void clearall (void)
bool get (uint16_t bit) const
bool empty (void) const
uint16_t count () const
int16_t first_set () const
uint16_t size () const
Private Attributes
uint16_t numbits
uint16_t numwords
uint32_t bits [(num_bits+31)/32]
Detailed Description
template<uint16_t num_bits>
class Bitmask< num_bits >
Definition at line 27 of file Bitmask.h.
Constructor & Destructor Documentation
Bitmask() [1/2]
template<uint16_t num_bits> Bitmask< num_bits >::Bitmask () inline
Definition at line 29 of file Bitmask.h.
Bitmask() [2/2]
template<uint16_t num_bits> Bitmask< num_bits >::Bitmask (const Bitmask< num_bits > & other) delete
Member Function Documentation
clear()
template<uint16_t num_bits> void Bitmask< num_bits >::clear (uint16_t bit) inline
Definition at line 78 of file Bitmask.h.
Referenced by ESP32::Storage::_flash_write(), HALSITL::Storage::_flash_write(), ChibiOS::Storage::_timer_tick(), HALSITL::Storage::_timer_tick(), GCS_MAVLINK::remove_message_from_bucket(), Bitmask< num_bits >::setonoff(), AP_Logger_RateLimiter::should_log(), TEST(), and GCS_MAVLINK::update_send().
clearall()
template<uint16_t num_bits> void Bitmask< num_bits >::clearall (void) inline
Definition at line 94 of file Bitmask.h.
Referenced by ChibiOS::Storage::_storage_open(), ESP32::Storage::_storage_open(), HALSITL::Storage::_storage_open(), Bitmask< num_bits >::Bitmask(), GCS_MAVLINK::find_next_bucket_to_send(), and SRV_Channels::update_aux_servo_function().
count()
template<uint16_t num_bits> uint16_t Bitmask< num_bits >::count () const inline
Definition at line 122 of file Bitmask.h.
Referenced by GCS_MAVLINK::remove_message_from_bucket(), GCS_MAVLINK::set_ap_message_interval(), and GCS_MAVLINK::update_send().
empty()
template<uint16_t num_bits> bool Bitmask< num_bits >::empty (void) const inline
Definition at line 112 of file Bitmask.h.
Referenced by ChibiOS::Storage::_timer_tick(), ESP32::Storage::_timer_tick(), and HALSITL::Storage::_timer_tick().
first_set()
template<uint16_t num_bits> int16_t Bitmask< num_bits >::first_set () const inline
Definition at line 137 of file Bitmask.h.
Referenced by GCS_MAVLINK::next_deferred_bucket_message_to_send(), and GCS_MAVLINK::update_send().
get()
template<uint16_t num_bits> bool Bitmask< num_bits >::get (uint16_t bit) const inline
Definition at line 99 of file Bitmask.h.
Referenced by ChibiOS::Storage::_timer_tick(), ESP32::Storage::_timer_tick(), HALSITL::Storage::_timer_tick(), SRV_Channels::function_assigned(), GCS_MAVLINK::get_ap_message_interval(), GCS_MAVLINK::set_ap_message_interval(), AP_Logger_RateLimiter::should_log(), TEST(), and TEST().
operator!=()
template<uint16_t num_bits> bool Bitmask< num_bits >::operator!= (const Bitmask< num_bits > & other) inline
Definition at line 48 of file Bitmask.h.
operator=()
template<uint16_t num_bits> Bitmask & Bitmask< num_bits >::operator= (const Bitmask< num_bits > & other) inline
Definition at line 35 of file Bitmask.h.
operator==()
template<uint16_t num_bits> bool Bitmask< num_bits >::operator== (const Bitmask< num_bits > & other) inline
Definition at line 40 of file Bitmask.h.
set()
template<uint16_t num_bits> void Bitmask< num_bits >::set (uint16_t bit) inline
Definition at line 55 of file Bitmask.h.
Referenced by ChibiOS::Storage::_mark_dirty(), ESP32::Storage::_mark_dirty(), HALSITL::Storage::_mark_dirty(), SITL::I2CRegisters::add_register(), SITL::QMC5883L::QMC5883L(), GCS_MAVLINK::send_message(), GCS_MAVLINK::set_ap_message_interval(), SRV_Channels::set_aux_channel_default(), SRV_Channels::set_default_function(), Bitmask< num_bits >::setonoff(), AP_Logger_RateLimiter::should_log(), TEST(), TEST(), and SRV_Channels::update_aux_servo_function().
setall()
template<uint16_t num_bits> void Bitmask< num_bits >::setall (void) inline
Definition at line 67 of file Bitmask.h.
setonoff()
template<uint16_t num_bits> void Bitmask< num_bits >::setonoff (uint16_t bit, bool onoff) inline
Definition at line 85 of file Bitmask.h.
size()
template<uint16_t num_bits> uint16_t Bitmask< num_bits >::size () const inline
Definition at line 156 of file Bitmask.h.
Member Data Documentation
bits
template<uint16_t num_bits> uint32_t Bitmask< num_bits >::bits[(num_bits+31)/32] private
Definition at line 163 of file Bitmask.h.
Referenced by Bitmask< num_bits >::clear(), Bitmask< num_bits >::clearall(), Bitmask< num_bits >::count(), Bitmask< num_bits >::empty(), Bitmask< num_bits >::first_set(), Bitmask< num_bits >::get(), Bitmask< num_bits >::operator=(), Bitmask< num_bits >::operator==(), Bitmask< num_bits >::set(), and Bitmask< num_bits >::setall().
numbits
template<uint16_t num_bits> uint16_t Bitmask< num_bits >::numbits private
Definition at line 161 of file Bitmask.h.
Referenced by Bitmask< num_bits >::get(), Bitmask< num_bits >::operator==(), Bitmask< num_bits >::set(), Bitmask< num_bits >::setall(), and Bitmask< num_bits >::size().
numwords
template<uint16_t num_bits> uint16_t Bitmask< num_bits >::numwords private
Definition at line 162 of file Bitmask.h.
Referenced by Bitmask< num_bits >::clearall(), Bitmask< num_bits >::count(), Bitmask< num_bits >::empty(), Bitmask< num_bits >::first_set(), Bitmask< num_bits >::operator=(), Bitmask< num_bits >::operator==(), and Bitmask< num_bits >::setall().
The documentation for this class was generated from the following file:
libraries/AP_Common/Bitmask.h