APM:Libraries: SITL::FETtecOneWireESC Class Reference
SITL::FETtecOneWireESC Class Reference
#include <SIM_FETtecOneWireESC.h>
Classes
struct ConfigMessageHeader
class ESC
class ESC_TYPE
class ESCTelem
union MessageUnion
class OK
class PackedMessage
class SetFastComLength
class SetTLMType
class SN
class SW_VER
Public Member Functions
FETtecOneWireESC ()
void update (const class Aircraft &aircraft)
bool enabled () const
void update_sitl_input_pwm (struct sitl_input &input)
Public Member Functions inherited from SITL::SerialDevice
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Static Public Attributes
static const AP_Param::GroupInfo var_info []
Private Types
enum class TLMType : uint8_t { NORMAL = 0 , ALTERNATIVE =1 }
enum class ConfigMessageType {
OK = 0 , BL_PAGE_CORRECT = 1 , NOT_OK = 2 , BL_START_FW = 3 ,
BL_PAGES_TO_FLASH = 4 , REQ_TYPE = 5 , REQ_SN = 6 , REQ_SW_VER = 7 ,
BEEP = 13 , SET_FAST_COM_LENGTH = 26 , SET_TLM_TYPE = 27 , SET_LED_TMP_COLOR = 51
}
enum class ResponseFrameHeaderID { MASTER = 0x01 , BOOTLOADER = 0x02 , ESC = 0x03 }
Private Member Functions
void consume_bytes (uint8_t count)
void bootloader_handle_config_message (ESC &esc)
void running_handle_config_message (ESC &esc)
void handle_config_message ()
void handle_config_message_set_tlm_type (ESC &esc)
void handle_fast_esc_data ()
void update_escs ()
void update_send (const class Aircraft &aircraft)
void update_input ()
void send_esc_telemetry (const class Aircraft &aircraft)
template<typename T >
void send_response (const T &r)
Private Attributes
AP_Int8 _enabled
AP_Int32 _powered_mask
MessageUnion u
uint8_t buflen
struct {
uint8_t min_esc_id
uint8_t id_count = 255
} fast_com
ESC escs [16]
Additional Inherited Members
Protected Member Functions inherited from SITL::SerialDevice
bool init_sitl_pointer () WARN_IF_UNUSED
Protected Attributes inherited from SITL::SerialDevice
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Detailed Description
Definition at line 54 of file SIM_FETtecOneWireESC.h.
Member Enumeration Documentation
ConfigMessageType
enum class SITL::FETtecOneWireESC::ConfigMessageType strong private
Enumerator
OK
BL_PAGE_CORRECT
NOT_OK
BL_START_FW
BL_PAGES_TO_FLASH
REQ_TYPE
REQ_SN
REQ_SW_VER
BEEP
SET_FAST_COM_LENGTH
SET_TLM_TYPE
SET_LED_TMP_COLOR
Definition at line 208 of file SIM_FETtecOneWireESC.h.
ResponseFrameHeaderID
enum class SITL::FETtecOneWireESC::ResponseFrameHeaderID strong private
Enumerator
MASTER
BOOTLOADER
ESC
Definition at line 287 of file SIM_FETtecOneWireESC.h.
TLMType
enum class SITL::FETtecOneWireESC::TLMType : uint8_t strong private
Enumerator
NORMAL
ALTERNATIVE
Definition at line 81 of file SIM_FETtecOneWireESC.h.
Constructor & Destructor Documentation
FETtecOneWireESC()
FETtecOneWireESC::FETtecOneWireESC ()
Definition at line 76 of file SIM_FETtecOneWireESC.cpp.
Member Function Documentation
bootloader_handle_config_message()
void FETtecOneWireESC::bootloader_handle_config_message (FETtecOneWireESC::ESC & esc) private
Definition at line 182 of file SIM_FETtecOneWireESC.cpp.
Referenced by handle_config_message().
consume_bytes()
void FETtecOneWireESC::consume_bytes (uint8_t count) private
Definition at line 372 of file SIM_FETtecOneWireESC.cpp.
Referenced by update_input().
enabled()
bool SITL::FETtecOneWireESC::enabled () const inline
Definition at line 64 of file SIM_FETtecOneWireESC.h.
handle_config_message()
void FETtecOneWireESC::handle_config_message () private
Definition at line 153 of file SIM_FETtecOneWireESC.cpp.
Referenced by update_input().
handle_config_message_set_tlm_type()
void FETtecOneWireESC::handle_config_message_set_tlm_type (ESC & esc) private
Definition at line 281 of file SIM_FETtecOneWireESC.cpp.
Referenced by running_handle_config_message().
handle_fast_esc_data()
void FETtecOneWireESC::handle_fast_esc_data () private
Definition at line 297 of file SIM_FETtecOneWireESC.cpp.
Referenced by update_input().
running_handle_config_message()
void FETtecOneWireESC::running_handle_config_message (FETtecOneWireESC::ESC & esc) private
Definition at line 220 of file SIM_FETtecOneWireESC.cpp.
Referenced by handle_config_message().
send_esc_telemetry()
void FETtecOneWireESC::send_esc_telemetry (const class Aircraft & aircraft) private
Definition at line 475 of file SIM_FETtecOneWireESC.cpp.
Referenced by update_send().
send_response()
template<typename T > void FETtecOneWireESC::send_response (const T & r) private
Definition at line 174 of file SIM_FETtecOneWireESC.cpp.
Referenced by bootloader_handle_config_message(), handle_config_message_set_tlm_type(), running_handle_config_message(), send_esc_telemetry(), and update_escs().
update()
void FETtecOneWireESC::update (const class Aircraft & aircraft)
Definition at line 141 of file SIM_FETtecOneWireESC.cpp.
update_escs()
void FETtecOneWireESC::update_escs () private
Definition at line 91 of file SIM_FETtecOneWireESC.cpp.
Referenced by update().
update_input()
void FETtecOneWireESC::update_input () private
Definition at line 385 of file SIM_FETtecOneWireESC.cpp.
Referenced by update().
update_send()
void FETtecOneWireESC::update_send (const class Aircraft & aircraft) private
Definition at line 508 of file SIM_FETtecOneWireESC.cpp.
Referenced by update().
update_sitl_input_pwm()
void FETtecOneWireESC::update_sitl_input_pwm (struct sitl_input & input)
Definition at line 461 of file SIM_FETtecOneWireESC.cpp.
Member Data Documentation
_enabled
AP_Int8 SITL::FETtecOneWireESC::_enabled private
Definition at line 70 of file SIM_FETtecOneWireESC.h.
Referenced by enabled(), and update().
_powered_mask
AP_Int32 SITL::FETtecOneWireESC::_powered_mask private
Definition at line 71 of file SIM_FETtecOneWireESC.h.
Referenced by update_escs().
buflen
uint8_t SITL::FETtecOneWireESC::buflen private
Definition at line 203 of file SIM_FETtecOneWireESC.h.
Referenced by consume_bytes(), and update_input().
escs
ESC SITL::FETtecOneWireESC::escs[16] private
Definition at line 293 of file SIM_FETtecOneWireESC.h.
Referenced by FETtecOneWireESC(), handle_config_message(), handle_fast_esc_data(), send_esc_telemetry(), update_escs(), update_input(), and update_sitl_input_pwm().
[struct]
struct { ... } SITL::FETtecOneWireESC::fast_com
Referenced by handle_fast_esc_data(), and update_input().
id_count
uint8_t SITL::FETtecOneWireESC::id_count = 255
Definition at line 267 of file SIM_FETtecOneWireESC.h.
min_esc_id
uint8_t SITL::FETtecOneWireESC::min_esc_id
Definition at line 266 of file SIM_FETtecOneWireESC.h.
u
MessageUnion SITL::FETtecOneWireESC::u private
Definition at line 202 of file SIM_FETtecOneWireESC.h.
Referenced by bootloader_handle_config_message(), consume_bytes(), handle_config_message(), handle_config_message_set_tlm_type(), handle_fast_esc_data(), running_handle_config_message(), and update_input().
var_info
const AP_Param::GroupInfo FETtecOneWireESC::var_info static
Initial value:
= {
    AP_GROUPINFO("ENA", 1, FETtecOneWireESC, _enabled, 0),
    AP_GROUPINFO("POW", 2, FETtecOneWireESC, _powered_mask, 0xfff),
    AP_GROUPEND
}
Definition at line 62 of file SIM_FETtecOneWireESC.h.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_FETtecOneWireESC.h
libraries/SITL/SIM_FETtecOneWireESC.cpp