APM:Libraries: AP_Baro_MS56XX Class Reference
AP_Baro_MS56XX Class Reference
#include <AP_Baro_MS5611.h>
Public Types
enum MS56XX_TYPE { BARO_MS5611 = 0 , BARO_MS5607 = 1 , BARO_MS5637 = 2 , BARO_MS5837 = 3 }
Public Types inherited from AP_Baro_Backend
enum DevTypes {
DEVTYPE_BARO_SITL = 0x01 , DEVTYPE_BARO_BMP085 = 0x02 , DEVTYPE_BARO_BMP280 = 0x03 , DEVTYPE_BARO_BMP388 = 0x04 ,
DEVTYPE_BARO_DPS280 = 0x05 , DEVTYPE_BARO_DPS310 = 0x06 , DEVTYPE_BARO_FBM320 = 0x07 , DEVTYPE_BARO_ICM20789 = 0x08 ,
DEVTYPE_BARO_KELLERLD = 0x09 , DEVTYPE_BARO_LPS2XH = 0x0A , DEVTYPE_BARO_MS5611 = 0x0B , DEVTYPE_BARO_SPL06 = 0x0C ,
DEVTYPE_BARO_UAVCAN = 0x0D , DEVTYPE_BARO_MSP = 0x0E , DEVTYPE_BARO_ICP101XX = 0x0F , DEVTYPE_BARO_ICP201XX = 0x10 ,
DEVTYPE_BARO_MS5607 = 0x11 , DEVTYPE_BARO_MS5837 = 0x12 , DEVTYPE_BARO_MS5637 = 0x13 , DEVTYPE_BARO_BMP390 = 0x14
}
Public Member Functions
void update () override
Public Member Functions inherited from AP_Baro_Backend
AP_Baro_Backend (AP_Baro &baro)
virtual ~AP_Baro_Backend (void)
virtual void accumulate (void)
void backend_update (uint8_t instance)
bool pressure_ok (float press)
uint32_t get_error_count () const
Static Public Member Functions
static AP_Baro_Backend * probe_5611 (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
static AP_Baro_Backend * probe_5607 (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
static AP_Baro_Backend * probe_5637 (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
static AP_Baro_Backend * probe_5837 (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
static AP_Baro_Backend * probe (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum MS56XX_TYPE ms56xx_type=BARO_MS5611)
Private Member Functions
AP_Baro_MS56XX (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum MS56XX_TYPE ms56xx_type)
bool _init ()
void _calculate_5611 ()
void _calculate_5607 ()
void _calculate_5637 ()
void _calculate_5837 ()
bool _read_prom_5611 (uint16_t prom[8])
bool _read_prom_5637 (uint16_t prom[8])
uint16_t _read_prom_word (uint8_t word)
uint32_t _read_adc ()
void _timer ()
Static Private Member Functions
static void _update_and_wrap_accumulator (uint32_t *accum, uint32_t val, uint8_t *count, uint8_t max_count)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _dev
struct {
uint32_t s_D1
uint32_t s_D2
uint8_t d1_count
uint8_t d2_count
} _accum
uint8_t _state
uint8_t _instance
float _D1
float _D2
struct {
uint16_t c1
uint16_t c2
uint16_t c3
uint16_t c4
uint16_t c5
uint16_t c6
} _cal_reg
bool _discard_next
enum MS56XX_TYPE _ms56xx_type
Additional Inherited Members
Protected Member Functions inherited from AP_Baro_Backend
void _copy_to_frontend (uint8_t instance, float pressure, float temperature)
virtual void update_healthy_flag (uint8_t instance)
void set_bus_id (uint8_t instance, uint32_t id)
Protected Attributes inherited from AP_Baro_Backend
AP_Baro & _frontend
HAL_Semaphore _sem
float _mean_pressure
uint32_t _error_count
Detailed Description
Definition at line 31 of file AP_Baro_MS5611.h.
Member Enumeration Documentation
MS56XX_TYPE
enum AP_Baro_MS56XX::MS56XX_TYPE
Enumerator
BARO_MS5611
BARO_MS5607
BARO_MS5637
BARO_MS5837
Definition at line 36 of file AP_Baro_MS5611.h.
Constructor & Destructor Documentation
AP_Baro_MS56XX()
AP_Baro_MS56XX::AP_Baro_MS56XX (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum MS56XX_TYPE ms56xx_type) private
Definition at line 60 of file AP_Baro_MS5611.cpp.
Referenced by probe().
Member Function Documentation
_calculate_5607()
void AP_Baro_MS56XX::_calculate_5607 () private
Definition at line 414 of file AP_Baro_MS5611.cpp.
Referenced by update().
_calculate_5611()
void AP_Baro_MS56XX::_calculate_5611 () private
Definition at line 374 of file AP_Baro_MS5611.cpp.
Referenced by update().
_calculate_5637()
void AP_Baro_MS56XX::_calculate_5637 () private
Definition at line 452 of file AP_Baro_MS5611.cpp.
Referenced by update().
_calculate_5837()
void AP_Baro_MS56XX::_calculate_5837 () private
Definition at line 487 of file AP_Baro_MS5611.cpp.
Referenced by update().
_init()
bool AP_Baro_MS56XX::_init () private
Definition at line 82 of file AP_Baro_MS5611.cpp.
Referenced by probe().
_read_adc()
uint32_t AP_Baro_MS56XX::_read_adc () private
Definition at line 191 of file AP_Baro_MS5611.cpp.
Referenced by _timer().
_read_prom_5611()
bool AP_Baro_MS56XX::_read_prom_5611 (uint16_t prom[8]) private
Definition at line 200 of file AP_Baro_MS5611.cpp.
Referenced by _init().
_read_prom_5637()
bool AP_Baro_MS56XX::_read_prom_5637 (uint16_t prom[8]) private
Definition at line 230 of file AP_Baro_MS5611.cpp.
Referenced by _init().
_read_prom_word()
uint16_t AP_Baro_MS56XX::_read_prom_word (uint8_t word) private
Definition at line 181 of file AP_Baro_MS5611.cpp.
Referenced by _read_prom_5611(), and _read_prom_5637().
_timer()
void AP_Baro_MS56XX::_timer (void) private
Definition at line 271 of file AP_Baro_MS5611.cpp.
Referenced by _init().
_update_and_wrap_accumulator()
void AP_Baro_MS56XX::_update_and_wrap_accumulator (uint32_t * accum, uint32_t val, uint8_t * count, uint8_t max_count) static private
Definition at line 321 of file AP_Baro_MS5611.cpp.
Referenced by _timer().
probe()
AP_Baro_Backend * AP_Baro_MS56XX::probe (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum MS56XX_TYPE ms56xx_type = BARO_MS5611) static
Definition at line 67 of file AP_Baro_MS5611.cpp.
Referenced by AP_Baro::init(), probe_5607(), probe_5611(), probe_5637(), and probe_5837().
probe_5607()
static AP_Baro_Backend * AP_Baro_MS56XX::probe_5607 (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev) inline static
Definition at line 46 of file AP_Baro_MS5611.h.
Referenced by AP_Baro::_probe_i2c_barometers().
probe_5611()
static AP_Baro_Backend * AP_Baro_MS56XX::probe_5611 (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev) inline static
Definition at line 43 of file AP_Baro_MS5611.h.
Referenced by AP_Baro::_probe_i2c_barometers().
probe_5637()
static AP_Baro_Backend * AP_Baro_MS56XX::probe_5637 (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev) inline static
Definition at line 49 of file AP_Baro_MS5611.h.
Referenced by AP_Baro::_probe_i2c_barometers().
probe_5837()
static AP_Baro_Backend * AP_Baro_MS56XX::probe_5837 (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev) inline static
Definition at line 52 of file AP_Baro_MS5611.h.
Referenced by AP_Baro::_probe_i2c_barometers().
update()
void AP_Baro_MS56XX::update (void) override virtual
Implements AP_Baro_Backend.
Definition at line 332 of file AP_Baro_MS5611.cpp.
Member Data Documentation
[struct]
struct { ... } AP_Baro_MS56XX::_accum
Referenced by _init(), _timer(), and update().
[struct]
struct { ... } AP_Baro_MS56XX::_cal_reg
Referenced by _calculate_5607(), _calculate_5611(), _calculate_5637(), _calculate_5837(), and _init().
_D1
float AP_Baro_MS56XX::_D1 private
Definition at line 98 of file AP_Baro_MS5611.h.
Referenced by _calculate_5607(), _calculate_5611(), _calculate_5637(), _calculate_5837(), and update().
_D2
float AP_Baro_MS56XX::_D2 private
Definition at line 98 of file AP_Baro_MS5611.h.
Referenced by _calculate_5607(), _calculate_5611(), _calculate_5637(), _calculate_5837(), and update().
_dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_Baro_MS56XX::_dev private
Definition at line 84 of file AP_Baro_MS5611.h.
Referenced by _init(), _read_adc(), _read_prom_word(), and _timer().
_discard_next
bool AP_Baro_MS56XX::_discard_next private
Definition at line 105 of file AP_Baro_MS5611.h.
Referenced by _timer().
_instance
uint8_t AP_Baro_MS56XX::_instance private
Definition at line 95 of file AP_Baro_MS5611.h.
Referenced by _calculate_5607(), _calculate_5611(), _calculate_5637(), _calculate_5837(), and _init().
_ms56xx_type
enum MS56XX_TYPE AP_Baro_MS56XX::_ms56xx_type private
Definition at line 107 of file AP_Baro_MS5611.h.
Referenced by _init(), and update().
_state
uint8_t AP_Baro_MS56XX::_state private
Definition at line 94 of file AP_Baro_MS5611.h.
Referenced by _init(), and _timer().
c1
uint16_t AP_Baro_MS56XX::c1
Definition at line 102 of file AP_Baro_MS5611.h.
c2
uint16_t AP_Baro_MS56XX::c2
Definition at line 102 of file AP_Baro_MS5611.h.
c3
uint16_t AP_Baro_MS56XX::c3
Definition at line 102 of file AP_Baro_MS5611.h.
c4
uint16_t AP_Baro_MS56XX::c4
Definition at line 102 of file AP_Baro_MS5611.h.
c5
uint16_t AP_Baro_MS56XX::c5
Definition at line 102 of file AP_Baro_MS5611.h.
c6
uint16_t AP_Baro_MS56XX::c6
Definition at line 102 of file AP_Baro_MS5611.h.
d1_count
uint8_t AP_Baro_MS56XX::d1_count
Definition at line 90 of file AP_Baro_MS5611.h.
d2_count
uint8_t AP_Baro_MS56XX::d2_count
Definition at line 91 of file AP_Baro_MS5611.h.
s_D1
uint32_t AP_Baro_MS56XX::s_D1
Definition at line 88 of file AP_Baro_MS5611.h.
s_D2
uint32_t AP_Baro_MS56XX::s_D2
Definition at line 89 of file AP_Baro_MS5611.h.
The documentation for this class was generated from the following files:
libraries/AP_Baro/AP_Baro_MS5611.h
libraries/AP_Baro/AP_Baro_MS5611.cpp