APM:Libraries: SoftSerial Class Reference
SoftSerial Class Reference
#include <SoftSerial.h>
Public Types
enum serial_config { SERIAL_CONFIG_8N1 = 0 , SERIAL_CONFIG_8E2I = 1 , SERIAL_CONFIG_8N1I = 2 }
Public Member Functions
SoftSerial (uint32_t baudrate, enum serial_config config)
bool process_pulse (uint32_t width_s0, uint32_t width_s1, uint8_t &b)
uint32_t get_byte_timestamp_us (void) const
uint32_t baud () const
Private Attributes
const uint32_t baudrate
const uint8_t half_bit
enum serial_config config
uint8_t data_width
uint8_t byte_width
uint16_t stop_mask
uint32_t timestamp_us
uint32_t byte_timestamp_us
struct {
uint32_t byte
uint16_t bit_ofs
} state
Detailed Description
Definition at line 20 of file SoftSerial.h.
Member Enumeration Documentation
serial_config
enum SoftSerial::serial_config
Enumerator
SERIAL_CONFIG_8N1
SERIAL_CONFIG_8E2I
SERIAL_CONFIG_8N1I
Definition at line 22 of file SoftSerial.h.
Constructor & Destructor Documentation
SoftSerial()
SoftSerial::SoftSerial (uint32_t baudrate, enum serial_config config)
Definition at line 23 of file SoftSerial.cpp.
Member Function Documentation
baud()
uint32_t SoftSerial::baud () const inline
Definition at line 36 of file SoftSerial.h.
Referenced by AP_RCProtocol_SBUS::process_byte().
get_byte_timestamp_us()
uint32_t SoftSerial::get_byte_timestamp_us (void) const inline
Definition at line 32 of file SoftSerial.h.
Referenced by AP_RCProtocol_DSM::process_pulse(), AP_RCProtocol_FPort::process_pulse(), AP_RCProtocol_IBUS::process_pulse(), AP_RCProtocol_SBUS::process_pulse(), AP_RCProtocol_SRXL::process_pulse(), and AP_RCProtocol_SUMD::process_pulse().
process_pulse()
bool SoftSerial::process_pulse (uint32_t width_s0, uint32_t width_s1, uint8_t & b)
Definition at line 47 of file SoftSerial.cpp.
Referenced by AP_RCProtocol_DSM::process_pulse(), AP_RCProtocol_FPort::process_pulse(), AP_RCProtocol_IBUS::process_pulse(), AP_RCProtocol_SBUS::process_pulse(), AP_RCProtocol_SRXL::process_pulse(), AP_RCProtocol_ST24::process_pulse(), and AP_RCProtocol_SUMD::process_pulse().
Member Data Documentation
baudrate
const uint32_t SoftSerial::baudrate private
Definition at line 39 of file SoftSerial.h.
Referenced by baud(), and process_pulse().
bit_ofs
uint16_t SoftSerial::bit_ofs
Definition at line 51 of file SoftSerial.h.
byte
uint32_t SoftSerial::byte
Definition at line 50 of file SoftSerial.h.
byte_timestamp_us
uint32_t SoftSerial::byte_timestamp_us private
Definition at line 47 of file SoftSerial.h.
Referenced by get_byte_timestamp_us(), and process_pulse().
byte_width
uint8_t SoftSerial::byte_width private
Definition at line 44 of file SoftSerial.h.
Referenced by process_pulse(), and SoftSerial().
config
enum serial_config SoftSerial::config private
Definition at line 41 of file SoftSerial.h.
Referenced by process_pulse(), and SoftSerial().
data_width
uint8_t SoftSerial::data_width private
Definition at line 43 of file SoftSerial.h.
Referenced by SoftSerial().
half_bit
const uint8_t SoftSerial::half_bit private
Definition at line 40 of file SoftSerial.h.
Referenced by process_pulse().
[struct]
struct { ... } SoftSerial::state
Referenced by process_pulse().
stop_mask
uint16_t SoftSerial::stop_mask private
Definition at line 45 of file SoftSerial.h.
Referenced by process_pulse(), and SoftSerial().
timestamp_us
uint32_t SoftSerial::timestamp_us private
Definition at line 46 of file SoftSerial.h.
Referenced by process_pulse().
The documentation for this class was generated from the following files:
libraries/AP_RCProtocol/SoftSerial.h
libraries/AP_RCProtocol/SoftSerial.cpp