APM:Libraries: AR_PivotTurn Class Reference
AR_PivotTurn Class Reference
#include <AR_PivotTurn.h>
Public Member Functions
AR_PivotTurn (AR_AttitudeControl &atc)
void enable (bool enable_pivot)
bool active () const
void check_activation (float desired_heading_deg, bool force_active=false)
bool would_activate (float yaw_change_deg) const WARN_IF_UNUSED
void deactivate ()
float get_turn_rate_rads (float desired_heading_deg, float dt)
float get_rate_max () const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
uint32_t get_delay_duration_ms () const
Private Attributes
AP_Int16 _angle
AP_Int16 _rate_max
AP_Float _delay
AR_AttitudeControl & _atc
bool _enabled
bool _active
uint32_t _delay_start_ms
Detailed Description
Definition at line 19 of file AR_PivotTurn.h.
Constructor & Destructor Documentation
AR_PivotTurn()
AR_PivotTurn::AR_PivotTurn (AR_AttitudeControl & atc)
Definition at line 65 of file AR_PivotTurn.cpp.
Member Function Documentation
active()
bool AR_PivotTurn::active () const
Definition at line 81 of file AR_PivotTurn.cpp.
Referenced by AR_WPNav::update(), and AR_WPNav::update_steering_and_speed().
check_activation()
void AR_PivotTurn::check_activation (float desired_heading_deg, bool force_active = false)
Definition at line 88 of file AR_PivotTurn.cpp.
Referenced by get_turn_rate_rads(), AR_WPNav::set_desired_location(), and AR_WPNav::set_desired_location_expect_fast_update().
deactivate()
void AR_PivotTurn::deactivate () inline
Definition at line 40 of file AR_PivotTurn.h.
Referenced by AR_WPNav::init(), and AR_WPNav::set_desired_location().
enable()
void AR_PivotTurn::enable (bool enable_pivot)
Definition at line 72 of file AR_PivotTurn.cpp.
Referenced by AR_WPNav::set_turn_params().
get_delay_duration_ms()
uint32_t AR_PivotTurn::get_delay_duration_ms () const private
Definition at line 149 of file AR_PivotTurn.cpp.
Referenced by check_activation().
get_rate_max()
float AR_PivotTurn::get_rate_max () const inline
Definition at line 48 of file AR_PivotTurn.h.
Referenced by AR_WPNav::get_pivot_rate().
get_turn_rate_rads()
float AR_PivotTurn::get_turn_rate_rads (float desired_heading_deg, float dt)
Definition at line 137 of file AR_PivotTurn.cpp.
Referenced by AR_WPNav::update_steering_and_speed().
would_activate()
bool AR_PivotTurn::would_activate (float yaw_change_deg) const
Definition at line 123 of file AR_PivotTurn.cpp.
Referenced by AR_WPNav::set_desired_location().
Member Data Documentation
_active
bool AR_PivotTurn::_active private
Definition at line 68 of file AR_PivotTurn.h.
Referenced by active(), check_activation(), deactivate(), and enable().
_angle
AP_Int16 AR_PivotTurn::_angle private
Definition at line 59 of file AR_PivotTurn.h.
Referenced by check_activation(), and would_activate().
_atc
AR_AttitudeControl& AR_PivotTurn::_atc private
Definition at line 64 of file AR_PivotTurn.h.
Referenced by get_turn_rate_rads().
_delay
AP_Float AR_PivotTurn::_delay private
Definition at line 61 of file AR_PivotTurn.h.
Referenced by get_delay_duration_ms().
_delay_start_ms
uint32_t AR_PivotTurn::_delay_start_ms private
Definition at line 69 of file AR_PivotTurn.h.
Referenced by check_activation().
_enabled
bool AR_PivotTurn::_enabled private
Definition at line 67 of file AR_PivotTurn.h.
Referenced by active(), check_activation(), enable(), and would_activate().
_rate_max
AP_Int16 AR_PivotTurn::_rate_max private
Definition at line 60 of file AR_PivotTurn.h.
Referenced by get_rate_max(), and get_turn_rate_rads().
var_info
const AP_Param::GroupInfo AR_PivotTurn::var_info static
Definition at line 33 of file AR_PivotTurn.h.
The documentation for this class was generated from the following files:
libraries/AR_WPNav/AR_PivotTurn.h
libraries/AR_WPNav/AR_PivotTurn.cpp