APM:Libraries: AP_Baro_ICP101XX Class Reference
AP_Baro_ICP101XX Class Reference
#include <AP_Baro_ICP101XX.h>
Public Member Functions
void update () override
Public Member Functions inherited from AP_Baro_Backend
AP_Baro_Backend (AP_Baro &baro)
virtual ~AP_Baro_Backend (void)
virtual void accumulate (void)
void backend_update (uint8_t instance)
bool pressure_ok (float press)
uint32_t get_error_count () const
Static Public Member Functions
static AP_Baro_Backend * probe (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
Private Member Functions
AP_Baro_ICP101XX (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
bool init ()
bool send_cmd16 (uint16_t cmd)
bool read_measure_results (uint8_t *buf, uint8_t len)
bool read_response (uint16_t cmd, uint8_t *buf, uint8_t len)
bool send_command (uint16_t cmd)
bool send_command (uint16_t cmd, uint8_t *data, uint8_t len)
int8_t cal_crc (uint8_t seed, uint8_t data)
bool start_measure (uint16_t mode)
bool read_calibration_data (void)
void convert_data (uint32_t Praw, uint32_t Traw)
void calculate_conversion_constants (const float p_Pa[3], const float p_LUT[3], float &A, float &B, float &C)
float get_pressure (uint32_t p_LSB, uint32_t T_LSB)
void timer (void)
Private Attributes
int16_t sensor_constants [4]
uint8_t instance
AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev
uint32_t last_measure_us
struct {
float tsum
float psum
uint32_t count
} accum
const float p_Pa_calib [3] = {45000.0, 80000.0, 105000.0}
const float LUT_lower = 3.5 * (1U<<20)
const float LUT_upper = 11.5 * (1U<<20)
const float quadr_factor = 1 / 16777216.0
const float offst_factor = 2048.0
uint32_t measure_interval = 0
Additional Inherited Members
Public Types inherited from AP_Baro_Backend
enum DevTypes {
DEVTYPE_BARO_SITL = 0x01 , DEVTYPE_BARO_BMP085 = 0x02 , DEVTYPE_BARO_BMP280 = 0x03 , DEVTYPE_BARO_BMP388 = 0x04 ,
DEVTYPE_BARO_DPS280 = 0x05 , DEVTYPE_BARO_DPS310 = 0x06 , DEVTYPE_BARO_FBM320 = 0x07 , DEVTYPE_BARO_ICM20789 = 0x08 ,
DEVTYPE_BARO_KELLERLD = 0x09 , DEVTYPE_BARO_LPS2XH = 0x0A , DEVTYPE_BARO_MS5611 = 0x0B , DEVTYPE_BARO_SPL06 = 0x0C ,
DEVTYPE_BARO_UAVCAN = 0x0D , DEVTYPE_BARO_MSP = 0x0E , DEVTYPE_BARO_ICP101XX = 0x0F , DEVTYPE_BARO_ICP201XX = 0x10 ,
DEVTYPE_BARO_MS5607 = 0x11 , DEVTYPE_BARO_MS5837 = 0x12 , DEVTYPE_BARO_MS5637 = 0x13 , DEVTYPE_BARO_BMP390 = 0x14
}
Protected Member Functions inherited from AP_Baro_Backend
void _copy_to_frontend (uint8_t instance, float pressure, float temperature)
virtual void update_healthy_flag (uint8_t instance)
void set_bus_id (uint8_t instance, uint32_t id)
Protected Attributes inherited from AP_Baro_Backend
AP_Baro & _frontend
HAL_Semaphore _sem
float _mean_pressure
uint32_t _error_count
Detailed Description
Definition at line 11 of file AP_Baro_ICP101XX.h.
Constructor & Destructor Documentation
AP_Baro_ICP101XX()
AP_Baro_ICP101XX::AP_Baro_ICP101XX (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev) private
Definition at line 52 of file AP_Baro_ICP101XX.cpp.
Referenced by probe().
Member Function Documentation
cal_crc()
int8_t AP_Baro_ICP101XX::cal_crc (uint8_t seed, uint8_t data) private
Definition at line 151 of file AP_Baro_ICP101XX.cpp.
Referenced by read_calibration_data().
calculate_conversion_constants()
void AP_Baro_ICP101XX::calculate_conversion_constants (const float p_Pa[3], const float p_LUT[3], float & A, float & B, float & C) private
Definition at line 234 of file AP_Baro_ICP101XX.cpp.
Referenced by get_pressure().
convert_data()
void AP_Baro_ICP101XX::convert_data (uint32_t Praw, uint32_t Traw) private
Definition at line 265 of file AP_Baro_ICP101XX.cpp.
Referenced by timer().
get_pressure()
float AP_Baro_ICP101XX::get_pressure (uint32_t p_LSB, uint32_t T_LSB) private
Definition at line 253 of file AP_Baro_ICP101XX.cpp.
Referenced by convert_data().
init()
bool AP_Baro_ICP101XX::init () private
Definition at line 72 of file AP_Baro_ICP101XX.cpp.
Referenced by probe().
probe()
AP_Baro_Backend * AP_Baro_ICP101XX::probe (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev) static
Definition at line 58 of file AP_Baro_ICP101XX.cpp.
read_calibration_data()
bool AP_Baro_ICP101XX::read_calibration_data (void) private
Definition at line 173 of file AP_Baro_ICP101XX.cpp.
Referenced by init().
read_measure_results()
bool AP_Baro_ICP101XX::read_measure_results (uint8_t * buf, uint8_t len) private
Definition at line 121 of file AP_Baro_ICP101XX.cpp.
Referenced by timer().
read_response()
bool AP_Baro_ICP101XX::read_response (uint16_t cmd, uint8_t * buf, uint8_t len) private
Definition at line 126 of file AP_Baro_ICP101XX.cpp.
Referenced by init(), and read_calibration_data().
send_cmd16()
bool AP_Baro_ICP101XX::send_cmd16 (uint16_t cmd) private
send_command() [1/2]
bool AP_Baro_ICP101XX::send_command (uint16_t cmd) private
Definition at line 134 of file AP_Baro_ICP101XX.cpp.
Referenced by init(), read_calibration_data(), and start_measure().
send_command() [2/2]
bool AP_Baro_ICP101XX::send_command (uint16_t cmd, uint8_t * data, uint8_t len) private
Definition at line 142 of file AP_Baro_ICP101XX.cpp.
start_measure()
bool AP_Baro_ICP101XX::start_measure (uint16_t mode) private
Definition at line 195 of file AP_Baro_ICP101XX.cpp.
Referenced by init(), and timer().
timer()
void AP_Baro_ICP101XX::timer (void) private
Definition at line 284 of file AP_Baro_ICP101XX.cpp.
Referenced by init().
update()
void AP_Baro_ICP101XX::update (void) override virtual
Implements AP_Baro_Backend.
Definition at line 304 of file AP_Baro_ICP101XX.cpp.
Member Data Documentation
[struct]
struct { ... } AP_Baro_ICP101XX::accum
Referenced by convert_data(), and update().
count
uint32_t AP_Baro_ICP101XX::count
Definition at line 50 of file AP_Baro_ICP101XX.h.
dev
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_Baro_ICP101XX::dev private
Definition at line 41 of file AP_Baro_ICP101XX.h.
Referenced by init(), probe(), read_measure_results(), read_response(), send_command(), and send_command().
instance
uint8_t AP_Baro_ICP101XX::instance private
Definition at line 39 of file AP_Baro_ICP101XX.h.
Referenced by init(), and update().
last_measure_us
uint32_t AP_Baro_ICP101XX::last_measure_us private
Definition at line 44 of file AP_Baro_ICP101XX.h.
Referenced by timer().
LUT_lower
const float AP_Baro_ICP101XX::LUT_lower = 3.5 * (1U<<20) private
Definition at line 56 of file AP_Baro_ICP101XX.h.
Referenced by get_pressure().
LUT_upper
const float AP_Baro_ICP101XX::LUT_upper = 11.5 * (1U<<20) private
Definition at line 57 of file AP_Baro_ICP101XX.h.
Referenced by get_pressure().
measure_interval
uint32_t AP_Baro_ICP101XX::measure_interval = 0 private
Definition at line 60 of file AP_Baro_ICP101XX.h.
Referenced by init(), start_measure(), and timer().
offst_factor
const float AP_Baro_ICP101XX::offst_factor = 2048.0 private
Definition at line 59 of file AP_Baro_ICP101XX.h.
Referenced by get_pressure().
p_Pa_calib
const float AP_Baro_ICP101XX::p_Pa_calib[3] = {45000.0, 80000.0, 105000.0} private
Definition at line 55 of file AP_Baro_ICP101XX.h.
Referenced by get_pressure().
psum
float AP_Baro_ICP101XX::psum
Definition at line 49 of file AP_Baro_ICP101XX.h.
quadr_factor
const float AP_Baro_ICP101XX::quadr_factor = 1 / 16777216.0 private
Definition at line 58 of file AP_Baro_ICP101XX.h.
Referenced by get_pressure().
sensor_constants
int16_t AP_Baro_ICP101XX::sensor_constants[4] private
Definition at line 37 of file AP_Baro_ICP101XX.h.
Referenced by get_pressure(), and read_calibration_data().
tsum
float AP_Baro_ICP101XX::tsum
Definition at line 48 of file AP_Baro_ICP101XX.h.
The documentation for this class was generated from the following files:
libraries/AP_Baro/AP_Baro_ICP101XX.h
libraries/AP_Baro/AP_Baro_ICP101XX.cpp