APM:Libraries: AP_MotorsHeli_RSC Class Reference
AP_MotorsHeli_RSC Class Reference
#include <AP_MotorsHeli_RSC.h>
Public Types
enum class RotorControlState { STOP = 0 , IDLE , ACTIVE }
Public Member Functions
AP_MotorsHeli_RSC (SRV_Channel::Aux_servo_function_t aux_fn, uint8_t default_channel)
void init_servo ()
void set_control_mode (RotorControlMode mode)
void reset_rsc_mode_param ()
uint8_t get_control_mode () const
void set_critical_speed (float critical_speed)
float get_desired_speed () const
void set_desired_speed (float desired_speed)
float get_rotor_speed () const
void set_governor_output (float governor_output)
float get_governor_output () const
void governor_reset ()
float get_control_output () const
void set_idle_output (float idle_output)
void autothrottle_run ()
void set_throttle_curve ()
void set_ramp_time (int8_t ramp_time)
void set_runup_time (int8_t runup_time)
bool is_runup_complete () const
bool is_spooldown_complete () const
void set_collective (float collective)
void use_bailout_ramp_time (bool enable)
void set_autorotation_flag (bool flag)
void set_arot_idle_output (int16_t idle)
void set_rsc_arot_man_enable (int8_t enable)
void set_rsc_arot_engage_time (int8_t eng_time)
void set_turbine_start (bool turbine_start)
void output (RotorControlState state)
uint32_t get_output_mask () const
bool rotor_speed_above_critical (void) const
Public Attributes
AP_Int16 _rsc_setpoint
AP_Int8 _rsc_mode
AP_Int8 _ramp_time
AP_Int8 _runup_time
AP_Int16 _critical_speed
AP_Int16 _idle_output
AP_Int16 _arot_idle_output
AP_Int8 _rsc_arot_engage_time
AP_Int8 _rsc_arot_man_enable
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void update_rotor_ramp (float rotor_ramp_input, float dt)
void update_rotor_runup (float dt)
void write_rsc (float servo_out)
float calculate_throttlecurve (float collective_in)
float get_critical_speed () const
float get_idle_output () const
float get_governor_torque () const
float get_governor_compensator () const
float get_arot_idle_output () const
Private Attributes
uint64_t _last_update_us
SRV_Channel::Aux_servo_function_t _aux_fn
uint8_t _default_channel
RotorControlMode _control_mode = ROTOR_CONTROL_MODE_DISABLED
float _desired_speed
float _control_output
float _rotor_ramp_output
float _rotor_runup_output
bool _runup_complete
float _thrcrv_poly [4][4]
float _collective_in
float _rotor_rpm
bool _turbine_start
bool _starting
float _governor_output
bool _governor_engage
bool _autothrottle
bool _governor_fault
bool _use_bailout_ramp
bool _in_autorotation
bool _spooldown_complete
float _fast_idle_timer
uint8_t _governor_fault_count
float _governor_torque_reference
bool _autorotating
bool _bailing_out
float _idle_throttle
bool _gov_bailing_out
AP_Int16 _power_slewrate
AP_Int16 _thrcrv [5]
AP_Int16 _governor_rpm
AP_Float _governor_torque
AP_Float _governor_compensator
AP_Float _governor_droop_response
AP_Float _governor_ff
AP_Float _governor_range
AP_Int16 _cooldown_time
Friends
class AP_MotorsHeli_Single
class AP_MotorsHeli_Dual
class AP_MotorsHeli_Quad
Detailed Description
Definition at line 42 of file AP_MotorsHeli_RSC.h.
Member Enumeration Documentation
RotorControlState
enum class AP_MotorsHeli_RSC::RotorControlState strong
Enumerator
STOP
IDLE
ACTIVE
Definition at line 57 of file AP_MotorsHeli_RSC.h.
Constructor & Destructor Documentation
AP_MotorsHeli_RSC()
AP_MotorsHeli_RSC::AP_MotorsHeli_RSC (SRV_Channel::Aux_servo_function_t aux_fn, uint8_t default_channel) inline
Definition at line 48 of file AP_MotorsHeli_RSC.h.
Member Function Documentation
autothrottle_run()
void AP_MotorsHeli_RSC::autothrottle_run ()
Definition at line 534 of file AP_MotorsHeli_RSC.cpp.
Referenced by output().
calculate_throttlecurve()
float AP_MotorsHeli_RSC::calculate_throttlecurve (float collective_in) private
Definition at line 520 of file AP_MotorsHeli_RSC.cpp.
Referenced by autothrottle_run(), and output().
get_arot_idle_output()
float AP_MotorsHeli_RSC::get_arot_idle_output () const inline private
Definition at line 210 of file AP_MotorsHeli_RSC.h.
Referenced by output().
get_control_mode()
uint8_t AP_MotorsHeli_RSC::get_control_mode () const inline
Definition at line 73 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Dual::calculate_armed_scalars(), AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), and AP_MotorsHeli::get_rsc_mode().
get_control_output()
float AP_MotorsHeli_RSC::get_control_output () const inline
Definition at line 91 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::get_control_output().
get_critical_speed()
float AP_MotorsHeli_RSC::get_critical_speed () const inline private
Definition at line 206 of file AP_MotorsHeli_RSC.h.
Referenced by rotor_speed_above_critical(), and update_rotor_runup().
get_desired_speed()
float AP_MotorsHeli_RSC::get_desired_speed () const inline
Definition at line 79 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::get_desired_rotor_speed().
get_governor_compensator()
float AP_MotorsHeli_RSC::get_governor_compensator () const inline private
Definition at line 209 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run().
get_governor_output()
float AP_MotorsHeli_RSC::get_governor_output () const inline
Definition at line 89 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::get_governor_output().
get_governor_torque()
float AP_MotorsHeli_RSC::get_governor_torque () const inline private
Definition at line 208 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run().
get_idle_output()
float AP_MotorsHeli_RSC::get_idle_output () const inline private
Definition at line 207 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), AP_MotorsHeli_Single::get_yaw_offset(), and output().
get_output_mask()
uint32_t AP_MotorsHeli_RSC::get_output_mask () const
Definition at line 511 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli::get_motor_mask(), and AP_MotorsHeli_Single::get_motor_mask().
get_rotor_speed()
float AP_MotorsHeli_RSC::get_rotor_speed () const
Definition at line 491 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli::get_main_rotor_speed(), rotor_speed_above_critical(), and update_rotor_runup().
governor_reset()
void AP_MotorsHeli_RSC::governor_reset ()
Definition at line 612 of file AP_MotorsHeli_RSC.cpp.
Referenced by autothrottle_run(), and output().
init_servo()
void AP_MotorsHeli_RSC::init_servo ()
Definition at line 225 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Dual::init_outputs(), AP_MotorsHeli_Quad::init_outputs(), and AP_MotorsHeli_Single::init_outputs().
is_runup_complete()
bool AP_MotorsHeli_RSC::is_runup_complete () const inline
Definition at line 99 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Dual::update_motor_control(), AP_MotorsHeli_Quad::update_motor_control(), and AP_MotorsHeli_Single::update_motor_control().
is_spooldown_complete()
bool AP_MotorsHeli_RSC::is_spooldown_complete () const inline
Definition at line 102 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Dual::update_motor_control(), AP_MotorsHeli_Quad::update_motor_control(), and AP_MotorsHeli_Single::update_motor_control().
output()
void AP_MotorsHeli_RSC::output (RotorControlState state)
Definition at line 247 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Dual::update_motor_control(), AP_MotorsHeli_Quad::update_motor_control(), and AP_MotorsHeli_Single::update_motor_control().
reset_rsc_mode_param()
void AP_MotorsHeli_RSC::reset_rsc_mode_param () inline
Definition at line 70 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Dual::calculate_armed_scalars(), AP_MotorsHeli_Quad::calculate_armed_scalars(), and AP_MotorsHeli_Single::calculate_armed_scalars().
rotor_speed_above_critical()
bool AP_MotorsHeli_RSC::rotor_speed_above_critical (void) const inline
Definition at line 132 of file AP_MotorsHeli_RSC.h.
Referenced by update_rotor_runup().
set_arot_idle_output()
void AP_MotorsHeli_RSC::set_arot_idle_output (int16_t idle) inline
Definition at line 114 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
set_autorotation_flag()
void AP_MotorsHeli_RSC::set_autorotation_flag (bool flag) inline
Definition at line 111 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Dual::calculate_armed_scalars(), AP_MotorsHeli_Quad::calculate_armed_scalars(), and AP_MotorsHeli_Single::calculate_armed_scalars().
set_collective()
void AP_MotorsHeli_RSC::set_collective (float collective) inline
Definition at line 105 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Dual::move_actuators(), AP_MotorsHeli_Quad::move_actuators(), and AP_MotorsHeli_Single::move_actuators().
set_control_mode()
void AP_MotorsHeli_RSC::set_control_mode (RotorControlMode mode) inline
Definition at line 67 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Dual::calculate_scalars(), AP_MotorsHeli_Quad::calculate_scalars(), and AP_MotorsHeli_Single::calculate_scalars().
set_critical_speed()
void AP_MotorsHeli_RSC::set_critical_speed (float critical_speed) inline
Definition at line 76 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
set_desired_speed()
void AP_MotorsHeli_RSC::set_desired_speed (float desired_speed) inline
Definition at line 82 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::set_desired_rotor_speed(), and AP_MotorsHeli_Single::set_desired_rotor_speed().
set_governor_output()
void AP_MotorsHeli_RSC::set_governor_output (float governor_output) inline
Definition at line 88 of file AP_MotorsHeli_RSC.h.
set_idle_output()
void AP_MotorsHeli_RSC::set_idle_output (float idle_output) inline
Definition at line 92 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
set_ramp_time()
void AP_MotorsHeli_RSC::set_ramp_time (int8_t ramp_time) inline
Definition at line 97 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
set_rsc_arot_engage_time()
void AP_MotorsHeli_RSC::set_rsc_arot_engage_time (int8_t eng_time) inline
Definition at line 120 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
set_rsc_arot_man_enable()
void AP_MotorsHeli_RSC::set_rsc_arot_man_enable (int8_t enable) inline
Definition at line 117 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
set_runup_time()
void AP_MotorsHeli_RSC::set_runup_time (int8_t runup_time) inline
Definition at line 98 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars().
set_throttle_curve()
void AP_MotorsHeli_RSC::set_throttle_curve ()
Definition at line 234 of file AP_MotorsHeli_RSC.cpp.
Referenced by AP_MotorsHeli_Dual::calculate_armed_scalars(), AP_MotorsHeli_Quad::calculate_armed_scalars(), and AP_MotorsHeli_Single::calculate_armed_scalars().
set_turbine_start()
void AP_MotorsHeli_RSC::set_turbine_start (bool turbine_start) inline
Definition at line 123 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::update_turbine_start().
update_rotor_ramp()
void AP_MotorsHeli_RSC::update_rotor_ramp (float rotor_ramp_input, float dt) private
Definition at line 390 of file AP_MotorsHeli_RSC.cpp.
Referenced by output().
update_rotor_runup()
void AP_MotorsHeli_RSC::update_rotor_runup (float dt) private
Definition at line 431 of file AP_MotorsHeli_RSC.cpp.
Referenced by output().
use_bailout_ramp_time()
void AP_MotorsHeli_RSC::use_bailout_ramp_time (bool enable) inline
Definition at line 108 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Dual::calculate_armed_scalars(), AP_MotorsHeli_Quad::calculate_armed_scalars(), and AP_MotorsHeli_Single::calculate_armed_scalars().
write_rsc()
void AP_MotorsHeli_RSC::write_rsc (float servo_out) private
Definition at line 499 of file AP_MotorsHeli_RSC.cpp.
Referenced by output().
Friends And Related Symbol Documentation
AP_MotorsHeli_Dual
friend class AP_MotorsHeli_Dual friend
Definition at line 45 of file AP_MotorsHeli_RSC.h.
AP_MotorsHeli_Quad
friend class AP_MotorsHeli_Quad friend
Definition at line 46 of file AP_MotorsHeli_RSC.h.
AP_MotorsHeli_Single
friend class AP_MotorsHeli_Single friend
Definition at line 44 of file AP_MotorsHeli_RSC.h.
Member Data Documentation
_arot_idle_output
AP_Int16 AP_MotorsHeli_RSC::_arot_idle_output
Definition at line 144 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars(), get_arot_idle_output(), output(), and set_arot_idle_output().
_autorotating
bool AP_MotorsHeli_RSC::_autorotating private
Definition at line 177 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and update_rotor_runup().
_autothrottle
bool AP_MotorsHeli_RSC::_autothrottle private
Definition at line 169 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), and output().
_aux_fn
SRV_Channel::Aux_servo_function_t AP_MotorsHeli_RSC::_aux_fn private
Definition at line 152 of file AP_MotorsHeli_RSC.h.
Referenced by get_output_mask(), init_servo(), and write_rsc().
_bailing_out
bool AP_MotorsHeli_RSC::_bailing_out private
Definition at line 178 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and update_rotor_ramp().
_collective_in
float AP_MotorsHeli_RSC::_collective_in private
Definition at line 163 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), output(), and set_collective().
_control_mode
RotorControlMode AP_MotorsHeli_RSC::_control_mode = ROTOR_CONTROL_MODE_DISABLED private
Definition at line 156 of file AP_MotorsHeli_RSC.h.
Referenced by get_control_mode(), get_output_mask(), output(), reset_rsc_mode_param(), set_control_mode(), update_rotor_ramp(), update_rotor_runup(), and write_rsc().
_control_output
float AP_MotorsHeli_RSC::_control_output private
Definition at line 158 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), get_control_output(), and output().
_cooldown_time
AP_Int16 AP_MotorsHeli_RSC::_cooldown_time private
Definition at line 203 of file AP_MotorsHeli_RSC.h.
Referenced by output().
_critical_speed
AP_Int16 AP_MotorsHeli_RSC::_critical_speed
Definition at line 142 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::arming_checks(), AP_MotorsHeli_Single::calculate_scalars(), get_critical_speed(), and set_critical_speed().
_default_channel
uint8_t AP_MotorsHeli_RSC::_default_channel private
Definition at line 153 of file AP_MotorsHeli_RSC.h.
Referenced by init_servo().
_desired_speed
float AP_MotorsHeli_RSC::_desired_speed private
Definition at line 157 of file AP_MotorsHeli_RSC.h.
Referenced by get_desired_speed(), output(), and set_desired_speed().
_fast_idle_timer
float AP_MotorsHeli_RSC::_fast_idle_timer private
Definition at line 174 of file AP_MotorsHeli_RSC.h.
Referenced by output().
_gov_bailing_out
bool AP_MotorsHeli_RSC::_gov_bailing_out private
Definition at line 180 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), output(), and update_rotor_ramp().
_governor_compensator
AP_Float AP_MotorsHeli_RSC::_governor_compensator private
Definition at line 199 of file AP_MotorsHeli_RSC.h.
Referenced by get_governor_compensator().
_governor_droop_response
AP_Float AP_MotorsHeli_RSC::_governor_droop_response private
Definition at line 200 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run().
_governor_engage
bool AP_MotorsHeli_RSC::_governor_engage private
Definition at line 168 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), and governor_reset().
_governor_fault
bool AP_MotorsHeli_RSC::_governor_fault private
Definition at line 170 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), and output().
_governor_fault_count
uint8_t AP_MotorsHeli_RSC::_governor_fault_count private
Definition at line 175 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), and governor_reset().
_governor_ff
AP_Float AP_MotorsHeli_RSC::_governor_ff private
Definition at line 201 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run().
_governor_output
float AP_MotorsHeli_RSC::_governor_output private
Definition at line 167 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), get_governor_output(), governor_reset(), and set_governor_output().
_governor_range
AP_Float AP_MotorsHeli_RSC::_governor_range private
Definition at line 202 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run().
_governor_rpm
AP_Int16 AP_MotorsHeli_RSC::_governor_rpm private
Definition at line 197 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run().
_governor_torque
AP_Float AP_MotorsHeli_RSC::_governor_torque private
Definition at line 198 of file AP_MotorsHeli_RSC.h.
Referenced by get_governor_torque().
_governor_torque_reference
float AP_MotorsHeli_RSC::_governor_torque_reference private
Definition at line 176 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), and governor_reset().
_idle_output
AP_Int16 AP_MotorsHeli_RSC::_idle_output
Definition at line 143 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::arming_checks(), AP_MotorsHeli_Single::calculate_scalars(), get_idle_output(), and set_idle_output().
_idle_throttle
float AP_MotorsHeli_RSC::_idle_throttle private
Definition at line 179 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), and output().
_in_autorotation
bool AP_MotorsHeli_RSC::_in_autorotation private
Definition at line 172 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_autorotation_flag().
_last_update_us
uint64_t AP_MotorsHeli_RSC::_last_update_us private
Definition at line 149 of file AP_MotorsHeli_RSC.h.
Referenced by output().
_power_slewrate
AP_Int16 AP_MotorsHeli_RSC::_power_slewrate private
Definition at line 195 of file AP_MotorsHeli_RSC.h.
Referenced by output().
_ramp_time
AP_Int8 AP_MotorsHeli_RSC::_ramp_time
Definition at line 140 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::arming_checks(), AP_MotorsHeli_Single::calculate_scalars(), set_ramp_time(), update_rotor_ramp(), and update_rotor_runup().
_rotor_ramp_output
float AP_MotorsHeli_RSC::_rotor_ramp_output private
Definition at line 159 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), output(), update_rotor_ramp(), and update_rotor_runup().
_rotor_rpm
float AP_MotorsHeli_RSC::_rotor_rpm private
Definition at line 164 of file AP_MotorsHeli_RSC.h.
Referenced by autothrottle_run(), and output().
_rotor_runup_output
float AP_MotorsHeli_RSC::_rotor_runup_output private
Definition at line 160 of file AP_MotorsHeli_RSC.h.
Referenced by get_rotor_speed(), and update_rotor_runup().
_rsc_arot_engage_time
AP_Int8 AP_MotorsHeli_RSC::_rsc_arot_engage_time
Definition at line 145 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli_Single::calculate_scalars(), set_rsc_arot_engage_time(), and update_rotor_ramp().
_rsc_arot_man_enable
AP_Int8 AP_MotorsHeli_RSC::_rsc_arot_man_enable
Definition at line 146 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::arot_man_enabled(), AP_MotorsHeli_Single::calculate_scalars(), and set_rsc_arot_man_enable().
_rsc_mode
AP_Int8 AP_MotorsHeli_RSC::_rsc_mode
Definition at line 139 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::arming_checks(), AP_MotorsHeli_Dual::calculate_armed_scalars(), AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), AP_MotorsHeli_Dual::calculate_scalars(), AP_MotorsHeli_Quad::calculate_scalars(), AP_MotorsHeli_Single::calculate_scalars(), and reset_rsc_mode_param().
_rsc_setpoint
AP_Int16 AP_MotorsHeli_RSC::_rsc_setpoint
Definition at line 138 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::arming_checks(), and AP_MotorsHeli::get_rsc_setpoint().
_runup_complete
bool AP_MotorsHeli_RSC::_runup_complete private
Definition at line 161 of file AP_MotorsHeli_RSC.h.
Referenced by is_runup_complete(), and update_rotor_runup().
_runup_time
AP_Int8 AP_MotorsHeli_RSC::_runup_time
Definition at line 141 of file AP_MotorsHeli_RSC.h.
Referenced by AP_MotorsHeli::arming_checks(), AP_MotorsHeli_Single::calculate_scalars(), set_runup_time(), and update_rotor_runup().
_spooldown_complete
bool AP_MotorsHeli_RSC::_spooldown_complete private
Definition at line 173 of file AP_MotorsHeli_RSC.h.
Referenced by is_spooldown_complete(), and update_rotor_runup().
_starting
bool AP_MotorsHeli_RSC::_starting private
Definition at line 166 of file AP_MotorsHeli_RSC.h.
Referenced by output().
_thrcrv
AP_Int16 AP_MotorsHeli_RSC::_thrcrv[5] private
Definition at line 196 of file AP_MotorsHeli_RSC.h.
Referenced by set_throttle_curve().
_thrcrv_poly
float AP_MotorsHeli_RSC::_thrcrv_poly[4][4] private
Definition at line 162 of file AP_MotorsHeli_RSC.h.
Referenced by calculate_throttlecurve(), and set_throttle_curve().
_turbine_start
bool AP_MotorsHeli_RSC::_turbine_start private
Definition at line 165 of file AP_MotorsHeli_RSC.h.
Referenced by output(), and set_turbine_start().
_use_bailout_ramp
bool AP_MotorsHeli_RSC::_use_bailout_ramp private
Definition at line 171 of file AP_MotorsHeli_RSC.h.
Referenced by output(), update_rotor_ramp(), update_rotor_runup(), and use_bailout_ramp_time().
var_info
const AP_Param::GroupInfo AP_MotorsHeli_RSC::var_info static
Definition at line 24 of file AP_MotorsHeli_RSC.h.
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_MotorsHeli_RSC.h
libraries/AP_Motors/AP_MotorsHeli_RSC.cpp