APM:Libraries: AverageFilter< T, U, FILTER_SIZE > Class Template Reference
AverageFilter< T, U, FILTER_SIZE > Class Template Reference
#include <AverageFilter.h>
Public Member Functions
AverageFilter ()
virtual T apply (T sample) override
virtual void reset () override
Public Member Functions inherited from FilterWithBuffer< T, FILTER_SIZE >
FilterWithBuffer ()
uint8_t get_filter_size () const
T get_sample (uint8_t i) const
Protected Attributes
uint8_t _num_samples
Protected Attributes inherited from FilterWithBuffer< T, FILTER_SIZE >
T samples [FILTER_SIZE]
uint8_t sample_index
Detailed Description
template<class T, class U, uint8_t FILTER_SIZE>
class AverageFilter< T, U, FILTER_SIZE >
Definition at line 28 of file AverageFilter.h.
Constructor & Destructor Documentation
AverageFilter()
template<class T , class U , uint8_t FILTER_SIZE> AverageFilter< T, U, FILTER_SIZE >::AverageFilter () inline
Definition at line 32 of file AverageFilter.h.
Member Function Documentation
apply()
template<class T , class U , uint8_t FILTER_SIZE> T AverageFilter< T, U, FILTER_SIZE >::apply (T sample) override virtual
Reimplemented from FilterWithBuffer< T, FILTER_SIZE >.
Reimplemented in AverageIntegralFilter< int32_t, int32_t, 10 >, and AverageIntegralFilter< T, U, FILTER_SIZE >.
Definition at line 79 of file AverageFilter.h.
Referenced by AP_TECS::_update_speed(), readTemp(), TEST(), TEST(), and Variometer::update().
reset()
template<class T , class U , uint8_t FILTER_SIZE> void AverageFilter< T, U, FILTER_SIZE >::reset (void) override virtual
Reimplemented from FilterWithBuffer< T, FILTER_SIZE >.
Definition at line 100 of file AverageFilter.h.
Referenced by AP_TECS::_update_speed(), TEST(), TEST(), and AP_TECS::update_50hz().
Member Data Documentation
_num_samples
template<class T , class U , uint8_t FILTER_SIZE> uint8_t AverageFilter< T, U, FILTER_SIZE >::_num_samples protected
Definition at line 43 of file AverageFilter.h.
The documentation for this class was generated from the following file:
libraries/Filter/AverageFilter.h