APM:Libraries: AC_P Class Reference
AC_P Class Reference
Object managing one P controller.
#include <AC_P.h>
Public Member Functions
AC_P (const float &initial_p=0.0f)
CLASS_NO_COPY (AC_P)
float get_p (float error) const
void load_gains ()
void save_gains ()
parameter accessors
static const struct AP_Param::GroupInfo var_info []
AP_Float _kp
const float default_kp
void operator() (const float p)
Overload the function call operator to permit relatively easy initialisation.
AP_Float & kP ()
const AP_Float & kP () const
void kP (const float v)
Detailed Description
Object managing one P controller.
Definition at line 13 of file AC_P.h.
Constructor & Destructor Documentation
AC_P()
AC_P::AC_P (const float & initial_p = 0.0f) inline
Constructor for P that saves its settings to EEPROM
Note
PIs must be named to avoid either multiple parameters with the same name, or an overly complex constructor.
Parameters
initial_p Initial value for the P term.
Definition at line 23 of file AC_P.h.
Member Function Documentation
CLASS_NO_COPY()
AC_P::CLASS_NO_COPY (AC_P)
get_p()
float AC_P::get_p (float error) const
Iterate the P controller, return the new control value
Positive error produces positive output.
Parameters
error The measured error value
dt The time delta in milliseconds (note that update interval cannot be more than 65.535 seconds due to limited range of the data type).
Returns
The updated control output.
Definition at line 15 of file AC_P.cpp.
Referenced by AR_AttitudeControl::get_turn_rate_from_heading(), AC_Autorotation::update_forward_speed_controller(), and AC_Autorotation::update_hs_glide_controller().
kP() [1/3]
AP_Float & AC_P::kP () inline
Definition at line 60 of file AC_P.h.
Referenced by AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AC_AttitudeControl::input_shaping_rate_predictor(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), AC_AttitudeControl::max_angle_step_bf_pitch(), AC_AttitudeControl::max_angle_step_bf_roll(), AC_AttitudeControl::max_angle_step_bf_yaw(), AC_AutoTune_Heli::save_tuning_gains(), AC_AutoTune_Multi::save_tuning_gains(), AC_AttitudeControl::thrust_heading_rotation_angles(), and AC_AttitudeControl::update_ang_vel_target_from_att_error().
kP() [2/3]
const AP_Float & AC_P::kP () const inline
Definition at line 61 of file AC_P.h.
kP() [3/3]
void AC_P::kP (const float v) inline
Definition at line 62 of file AC_P.h.
load_gains()
void AC_P::load_gains ()
Load gain properties
Definition at line 20 of file AC_P.cpp.
operator()()
void AC_P::operator() (const float p) inline
Overload the function call operator to permit relatively easy initialisation.
Definition at line 57 of file AC_P.h.
save_gains()
void AC_P::save_gains ()
Save gain properties
Definition at line 25 of file AC_P.cpp.
Referenced by AC_AutoTune_Heli::save_tuning_gains(), and AC_AutoTune_Multi::save_tuning_gains().
Member Data Documentation
_kp
AP_Float AC_P::_kp private
Definition at line 67 of file AC_P.h.
Referenced by get_p(), kP(), kP(), kP(), load_gains(), operator()(), and save_gains().
default_kp
const float AC_P::default_kp private
Definition at line 69 of file AC_P.h.
var_info
const AP_Param::GroupInfo AC_P::var_info static
Initial value:
= {
    AP_GROUPINFO_FLAGS_DEFAULT_POINTER("P",    0, AC_P, _kp, default_kp),
    AP_GROUPEND
}
Definition at line 7 of file AC_P.h.
The documentation for this class was generated from the following files:
libraries/AC_PID/AC_P.h
libraries/AC_PID/AC_P.cpp