APM:Libraries: AP_Frsky_SPort Class Reference
AP_Frsky_SPort Class Reference
#include <AP_Frsky_SPort.h>
Public Member Functions
AP_Frsky_SPort (AP_HAL::UARTDriver *port)
CLASS_NO_COPY (AP_Frsky_SPort)
void send () override
bool sport_telemetry_push (const uint8_t sensor, const uint8_t frame, const uint16_t appid, const int32_t data)
uint16_t prep_number (int32_t const number, const uint8_t digits, const uint8_t power)
Public Member Functions inherited from AP_Frsky_Backend
AP_Frsky_Backend (AP_HAL::UARTDriver *port)
virtual ~AP_Frsky_Backend ()
virtual bool init ()
virtual uint32_t initial_baud () const
virtual bool get_telem_data (sport_packet_t *packet_array, uint8_t &packet_count, const uint8_t max_size)
virtual bool set_telem_data (const uint8_t frame, const uint16_t appid, const uint32_t data)
virtual void queue_text_message (MAV_SEVERITY severity, const char *text)
Static Public Member Functions
static AP_Frsky_SPort * get_singleton (void)
Protected Member Functions
void send_sport_frame (uint8_t frame, uint16_t appid, uint32_t data)
uint32_t calc_gps_latlng (bool &send_latitude)
Protected Member Functions inherited from AP_Frsky_Backend
virtual bool init_serial_port ()
void calc_nav_alt (void)
void calc_gps_position (void)
bool calc_rpm (const uint8_t instance, int32_t &value) const
float get_vspeed_ms (void)
float format_gps (float dec)
Static Protected Member Functions
static uint8_t calc_sensor_id (const uint8_t physical_id)
Protected Attributes
struct {
bool send_latitude
bool send_airspeed
uint32_t gps_lng_sample
uint8_t new_byte
} _passthrough
struct {
sport_packet_t packet
bool pending = false
HAL_Semaphore sem
} _sport_push_buffer
Protected Attributes inherited from AP_Frsky_Backend
AP_HAL::UARTDriver * _port
struct {
int32_t vario_vspd
char lat_ns
char lon_ew
uint16_t latdddmm
uint16_t latmmmm
uint16_t londddmm
uint16_t lonmmmm
uint16_t alt_gps_meters
uint16_t alt_gps_cm
uint16_t alt_nav_meters
uint16_t alt_nav_cm
int16_t speed_in_meter
uint16_t speed_in_centimeter
uint16_t yaw
} _SPort_data
Private Attributes
struct {
bool sport_status
bool gps_refresh
bool vario_refresh
uint8_t fas_call
uint8_t gps_call
uint8_t vario_call
uint8_t various_call
uint8_t rpm_call
} _SPort
Static Private Attributes
static AP_Frsky_SPort * singleton
Additional Inherited Members
Protected Types inherited from AP_Frsky_Backend
enum frsky_options_e : uint8_t { OPTION_AIRSPEED_AND_GROUNDSPEED = 1U<<0 }
Static Protected Attributes inherited from AP_Frsky_Backend
static const uint8_t DATA_ID_GPS_ALT_BP = 0x01
static const uint8_t DATA_ID_TEMP1 = 0x02
static const uint8_t DATA_ID_FUEL = 0x04
static const uint8_t DATA_ID_TEMP2 = 0x05
static const uint8_t DATA_ID_GPS_ALT_AP = 0x09
static const uint8_t DATA_ID_BARO_ALT_BP = 0x10
static const uint8_t DATA_ID_GPS_SPEED_BP = 0x11
static const uint8_t DATA_ID_GPS_LONG_BP = 0x12
static const uint8_t DATA_ID_GPS_LAT_BP = 0x13
static const uint8_t DATA_ID_GPS_COURS_BP = 0x14
static const uint8_t DATA_ID_GPS_SPEED_AP = 0x19
static const uint8_t DATA_ID_GPS_LONG_AP = 0x1A
static const uint8_t DATA_ID_GPS_LAT_AP = 0x1B
static const uint8_t DATA_ID_BARO_ALT_AP = 0x21
static const uint8_t DATA_ID_GPS_LONG_EW = 0x22
static const uint8_t DATA_ID_GPS_LAT_NS = 0x23
static const uint8_t DATA_ID_CURRENT = 0x28
static const uint8_t DATA_ID_VFAS = 0x39
static const uint8_t START_STOP_D = 0x5E
static const uint8_t BYTESTUFF_D = 0x5D
static const uint16_t ALT_ID = 0x010F
static const uint16_t VARIO_ID = 0x011F
static const uint16_t CURR_ID = 0x020F
static const uint16_t VFAS_ID = 0x021F
static const uint16_t TEMP1_ID = 0x040F
static const uint16_t TEMP2_ID = 0x041F
static const uint16_t RPM1_ID = 0x050E
static const uint16_t RPM2_ID = 0x050F
static const uint16_t FUEL_ID = 0x060F
static const uint16_t GPS_LONG_LATI_FIRST_ID = 0x0800
static const uint16_t GPS_ALT_ID = 0x082F
static const uint16_t GPS_SPEED_ID = 0x083F
static const uint16_t GPS_COURS_ID = 0x084F
static const uint16_t DIY_FIRST_ID = 0x5000
static const uint8_t FRAME_HEAD = 0x7E
static const uint8_t FRAME_DLE = 0x7D
static const uint8_t FRAME_XOR = 0x20
static const uint8_t SPORT_DATA_FRAME = 0x10
static const uint8_t SENSOR_ID_VARIO = 0x00
static const uint8_t SENSOR_ID_FAS = 0x22
static const uint8_t SENSOR_ID_GPS = 0x83
static const uint8_t SENSOR_ID_RPM = 0xE4
static const uint8_t SENSOR_ID_SP2UR = 0xC6
Detailed Description
Definition at line 7 of file AP_Frsky_SPort.h.
Constructor & Destructor Documentation
AP_Frsky_SPort()
AP_Frsky_SPort::AP_Frsky_SPort (AP_HAL::UARTDriver * port) inline
Definition at line 12 of file AP_Frsky_SPort.h.
Member Function Documentation
calc_gps_latlng()
uint32_t AP_Frsky_SPort::calc_gps_latlng (bool & send_latitude) protected
Definition at line 173 of file AP_Frsky_SPort.cpp.
Referenced by AP_Frsky_SPort_Passthrough::process_packet(), and send().
calc_sensor_id()
uint8_t AP_Frsky_SPort::calc_sensor_id (const uint8_t physical_id) static protected
Definition at line 374 of file AP_Frsky_SPort.cpp.
Referenced by AP_Frsky_SPort_Passthrough::set_sensor_id().
CLASS_NO_COPY()
AP_Frsky_SPort::CLASS_NO_COPY (AP_Frsky_SPort)
get_singleton()
static AP_Frsky_SPort * AP_Frsky_SPort::get_singleton (void) inline static
Definition at line 25 of file AP_Frsky_SPort.h.
Referenced by AP::frsky_sport().
prep_number()
uint16_t AP_Frsky_SPort::prep_number (int32_t const number, const uint8_t digits, const uint8_t power)
Definition at line 387 of file AP_Frsky_SPort.cpp.
Referenced by AP_Frsky_SPort_Passthrough::calc_ap_status(), AP_Frsky_SPort_Passthrough::calc_attiandrng(), AP_Frsky_SPort_Passthrough::calc_batt(), AP_Frsky_SPort_Passthrough::calc_gps_status(), AP_Frsky_SPort_Passthrough::calc_home(), AP_Frsky_SPort_Passthrough::calc_terrain(), AP_Frsky_SPort_Passthrough::calc_velandyaw(), AP_Frsky_SPort_Passthrough::calc_waypoint(), and AP_Frsky_SPort_Passthrough::calc_wind().
send()
void AP_Frsky_SPort::send (void) override virtual
Implements AP_Frsky_Backend.
Reimplemented in AP_Frsky_SPort_Passthrough.
Definition at line 23 of file AP_Frsky_SPort.cpp.
send_sport_frame()
void AP_Frsky_SPort::send_sport_frame (uint8_t frame, uint16_t appid, uint32_t data) protected
Definition at line 198 of file AP_Frsky_SPort.cpp.
Referenced by send(), and AP_Frsky_SPort_Passthrough::send_sport_frame().
sport_telemetry_push()
bool AP_Frsky_SPort::sport_telemetry_push (const uint8_t sensor, const uint8_t frame, const uint16_t appid, const int32_t data)
Definition at line 459 of file AP_Frsky_SPort.cpp.
Member Data Documentation
[struct]
struct { ... } AP_Frsky_SPort::_passthrough
Referenced by AP_Frsky_SPort_Passthrough::calc_velandyaw(), AP_Frsky_SPort_Passthrough::is_packet_ready(), AP_Frsky_SPort_Passthrough::process_packet(), send(), and AP_Frsky_SPort_Passthrough::send().
[struct]
struct { ... } AP_Frsky_SPort::_SPort
Referenced by send().
[struct]
struct { ... } AP_Frsky_SPort::_sport_push_buffer
Referenced by AP_Frsky_SPort_Passthrough::adjust_packet_weight(), AP_Frsky_SPort_Passthrough::is_packet_ready(), AP_Frsky_SPort_Passthrough::process_packet(), send(), AP_Frsky_SPort_Passthrough::send(), and sport_telemetry_push().
fas_call
uint8_t AP_Frsky_SPort::fas_call
Definition at line 55 of file AP_Frsky_SPort.h.
gps_call
uint8_t AP_Frsky_SPort::gps_call
Definition at line 56 of file AP_Frsky_SPort.h.
gps_lng_sample
uint32_t AP_Frsky_SPort::gps_lng_sample
Definition at line 36 of file AP_Frsky_SPort.h.
gps_refresh
bool AP_Frsky_SPort::gps_refresh
Definition at line 53 of file AP_Frsky_SPort.h.
new_byte
uint8_t AP_Frsky_SPort::new_byte
Definition at line 37 of file AP_Frsky_SPort.h.
packet
sport_packet_t AP_Frsky_SPort::packet
Definition at line 44 of file AP_Frsky_SPort.h.
pending
bool AP_Frsky_SPort::pending = false
Definition at line 45 of file AP_Frsky_SPort.h.
rpm_call
uint8_t AP_Frsky_SPort::rpm_call
Definition at line 59 of file AP_Frsky_SPort.h.
sem
HAL_Semaphore AP_Frsky_SPort::sem
Definition at line 46 of file AP_Frsky_SPort.h.
send_airspeed
bool AP_Frsky_SPort::send_airspeed
Definition at line 35 of file AP_Frsky_SPort.h.
send_latitude
bool AP_Frsky_SPort::send_latitude
Definition at line 34 of file AP_Frsky_SPort.h.
Referenced by calc_gps_latlng().
singleton
AP_Frsky_SPort * AP_Frsky_SPort::singleton static private
Definition at line 62 of file AP_Frsky_SPort.h.
Referenced by AP_Frsky_SPort(), and get_singleton().
sport_status
bool AP_Frsky_SPort::sport_status
Definition at line 52 of file AP_Frsky_SPort.h.
vario_call
uint8_t AP_Frsky_SPort::vario_call
Definition at line 57 of file AP_Frsky_SPort.h.
vario_refresh
bool AP_Frsky_SPort::vario_refresh
Definition at line 54 of file AP_Frsky_SPort.h.
various_call
uint8_t AP_Frsky_SPort::various_call
Definition at line 58 of file AP_Frsky_SPort.h.
The documentation for this class was generated from the following files:
libraries/AP_Frsky_Telem/AP_Frsky_SPort.h
libraries/AP_Frsky_Telem/AP_Frsky_SPort.cpp