APM:Libraries: Linux::Semaphore Class Reference
Linux::Semaphore Class Reference
#include <Semaphores.h>
Public Member Functions
Semaphore ()
bool give () override
bool take (uint32_t timeout_ms) override
bool take_nonblocking () override
Public Member Functions inherited from AP_HAL::Semaphore
Semaphore ()
CLASS_NO_COPY (Semaphore)
virtual void take_blocking ()
virtual ~Semaphore (void)
Protected Attributes
pthread_mutex_t _lock
Friends
class BinarySemaphore
Detailed Description
Definition at line 11 of file Semaphores.h.
Constructor & Destructor Documentation
Semaphore()
Semaphore::Semaphore ()
Definition at line 10 of file Semaphores.cpp.
Member Function Documentation
give()
bool Semaphore::give () override virtual
Implements AP_HAL::Semaphore.
Definition at line 19 of file Semaphores.cpp.
Referenced by Linux::Scheduler::_run_io(), Linux::UARTDriver::_write(), Linux::I2CBus::end_cb(), and Linux::SPIBus::end_cb().
take()
bool Semaphore::take (uint32_t timeout_ms) override virtual
Implements AP_HAL::Semaphore.
Definition at line 24 of file Semaphores.cpp.
take_nonblocking()
bool Semaphore::take_nonblocking () override virtual
Implements AP_HAL::Semaphore.
Definition at line 42 of file Semaphores.cpp.
Referenced by Linux::UARTDriver::_write(), and take().
Friends And Related Symbol Documentation
BinarySemaphore
friend class BinarySemaphore friend
Definition at line 13 of file Semaphores.h.
Member Data Documentation
_lock
pthread_mutex_t Linux::Semaphore::_lock protected
Definition at line 19 of file Semaphores.h.
Referenced by give(), Semaphore(), take(), take_nonblocking(), Linux::BinarySemaphore::wait(), and Linux::BinarySemaphore::wait_blocking().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Semaphores.h
libraries/AP_HAL_Linux/Semaphores.cpp