APM:Libraries: AP_GPS Class Reference
AP_GPS Class Reference
#include <AP_GPS.h>
Classes
struct detect_state
struct GPS_State
struct GPS_timing
struct rtcm_buffer
Public Types
enum GPS_Type {
GPS_TYPE_NONE = 0 , GPS_TYPE_AUTO = 1 , GPS_TYPE_UBLOX = 2 , GPS_TYPE_NMEA = 5 ,
GPS_TYPE_SIRF = 6 , GPS_TYPE_HIL = 7 , GPS_TYPE_SBP = 8 , GPS_TYPE_UAVCAN = 9 ,
GPS_TYPE_SBF = 10 , GPS_TYPE_GSOF = 11 , GPS_TYPE_ERB = 13 , GPS_TYPE_MAV = 14 ,
GPS_TYPE_NOVA = 15 , GPS_TYPE_HEMI = 16 , GPS_TYPE_UBLOX_RTK_BASE = 17 , GPS_TYPE_UBLOX_RTK_ROVER = 18 ,
GPS_TYPE_MSP = 19 , GPS_TYPE_ALLYSTAR = 20 , GPS_TYPE_EXTERNAL_AHRS = 21 , GPS_TYPE_UAVCAN_RTK_BASE = 22 ,
GPS_TYPE_UAVCAN_RTK_ROVER = 23 , GPS_TYPE_UNICORE_NMEA = 24 , GPS_TYPE_UNICORE_MOVINGBASE_NMEA = 25 , GPS_TYPE_SBF_DUAL_ANTENNA = 26
}
enum GPS_Status {
NO_GPS = 0 , NO_FIX = 1 , GPS_OK_FIX_2D = 2 , GPS_OK_FIX_3D = 3 ,
GPS_OK_FIX_3D_DGPS = 4 , GPS_OK_FIX_3D_RTK_FLOAT = 5 , GPS_OK_FIX_3D_RTK_FIXED = 6
}
enum GPS_Engine_Setting {
GPS_ENGINE_NONE = -1 , GPS_ENGINE_PORTABLE = 0 , GPS_ENGINE_STATIONARY = 2 , GPS_ENGINE_PEDESTRIAN = 3 ,
GPS_ENGINE_AUTOMOTIVE = 4 , GPS_ENGINE_SEA = 5 , GPS_ENGINE_AIRBORNE_1G = 6 , GPS_ENGINE_AIRBORNE_2G = 7 ,
GPS_ENGINE_AIRBORNE_4G = 8
}
enum GPS_Role { GPS_ROLE_NORMAL , GPS_ROLE_MB_BASE , GPS_ROLE_MB_ROVER }
enum class CovarianceType : uint8_t { UNKNOWN = 0 , APPROXIMATED = 1 , DIAGONAL_KNOWN = 2 , KNOWN = 3 }
enum class SBAS_Mode : int8_t { Disabled = 0 , Enabled = 1 , DoNotChange = 2 }
Public Member Functions
AP_GPS ()
CLASS_NO_COPY (AP_GPS)
HAL_Semaphore & get_semaphore (void)
void init (const class AP_SerialManager &serial_manager)
Startup initialisation.
void update (void)
void handle_msg (mavlink_channel_t chan, const mavlink_message_t &msg)
uint8_t num_sensors (void) const
uint8_t primary_sensor (void) const
GPS_Status status (uint8_t instance) const
Query GPS status.
GPS_Status status (void) const
char status_onechar (void) const
GPS_Status highest_supported_status (uint8_t instance) const WARN_IF_UNUSED
const Location & location (uint8_t instance) const
const Location & location () const
bool get_undulation (uint8_t instance, float &undulation) const
bool get_undulation (float &undulation) const
bool speed_accuracy (uint8_t instance, float &sacc) const
bool speed_accuracy (float &sacc) const
bool horizontal_accuracy (uint8_t instance, float &hacc) const
bool horizontal_accuracy (float &hacc) const
bool vertical_accuracy (uint8_t instance, float &vacc) const
bool vertical_accuracy (float &vacc) const
CovarianceType position_covariance (const uint8_t instance, Matrix3f &cov) const WARN_IF_UNUSED
const Vector3f & velocity (uint8_t instance) const
const Vector3f & velocity () const
float ground_speed (uint8_t instance) const
float ground_speed () const
uint32_t ground_speed_cm (void) const
float ground_course (uint8_t instance) const
float ground_course () const
int32_t ground_course_cd (uint8_t instance) const
int32_t ground_course_cd () const
bool gps_yaw_deg (uint8_t instance, float &yaw_deg, float &accuracy_deg, uint32_t &time_ms) const
bool gps_yaw_deg (float &yaw_deg, float &accuracy_deg, uint32_t &time_ms) const
uint8_t num_sats (uint8_t instance) const
uint8_t num_sats () const
uint32_t time_week_ms (uint8_t instance) const
uint32_t time_week_ms () const
uint16_t time_week (uint8_t instance) const
uint16_t time_week () const
uint16_t get_hdop (uint8_t instance) const
uint16_t get_hdop () const
uint16_t get_vdop (uint8_t instance) const
uint16_t get_vdop () const
uint32_t last_fix_time_ms (uint8_t instance) const
uint32_t last_fix_time_ms (void) const
uint32_t last_message_time_ms (uint8_t instance) const
uint32_t last_message_time_ms (void) const
uint16_t last_message_delta_time_ms (uint8_t instance) const
uint16_t last_message_delta_time_ms (void) const
bool have_vertical_velocity (uint8_t instance) const
bool have_vertical_velocity (void) const
bool have_gps_yaw (uint8_t instance) const
bool have_gps_yaw (void) const
bool have_gps_yaw_configured (uint8_t instance) const
bool get_lag (uint8_t instance, float &lag_sec) const
bool get_lag (float &lag_sec) const
const Vector3f & get_antenna_offset (uint8_t instance) const
void lock_port (uint8_t instance, bool locked)
void send_mavlink_gps_raw (mavlink_channel_t chan)
void send_mavlink_gps2_raw (mavlink_channel_t chan)
void send_mavlink_gps_rtk (mavlink_channel_t chan, uint8_t inst)
bool first_unconfigured_gps (uint8_t &instance) const WARN_IF_UNUSED
void broadcast_first_configuration_failure_reason (void) const
bool all_consistent (float &distance) const
bool blend_health_check () const
void send_blob_start (uint8_t instance)
void send_blob_start (uint8_t instance, const char *_blob, uint16_t size)
void send_blob_update (uint8_t instance)
uint64_t time_epoch_usec (uint8_t instance) const
uint64_t time_epoch_usec (void) const
uint64_t last_message_epoch_usec (uint8_t instance) const
uint64_t last_message_epoch_usec () const
void Write_AP_Logger_Log_Startup_messages ()
void set_log_gps_bit (uint32_t bit)
bool is_healthy (uint8_t instance) const
bool is_healthy (void) const
bool prepare_for_arming (void)
bool backends_healthy (char failure_msg[], uint16_t failure_msg_len)
bool logging_failed (void) const
bool logging_present (void) const
bool logging_enabled (void) const
void force_disable (bool disable)
void set_force_disable_yaw (bool disable)
void handle_gps_rtcm_fragment (uint8_t flags, const uint8_t *data, uint8_t len)
GPS_Type get_type (uint8_t instance) const
uint32_t get_itow (uint8_t instance) const
bool get_error_codes (uint8_t instance, uint32_t &error_codes) const
bool get_error_codes (uint32_t &error_codes) const
void inject_MBL_data (uint8_t *data, uint16_t length)
void get_RelPosHeading (uint32_t &timestamp, float &relPosHeading, float &relPosLength, float &relPosD, float &accHeading)
bool get_RTCMV3 (const uint8_t *&bytes, uint16_t &len)
void clear_RTCMV3 ()
Static Public Member Functions
static AP_GPS * get_singleton ()
static uint64_t istate_time_to_epoch_ms (uint16_t gps_week, uint32_t gps_ms)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Types
enum DriverOptions : int16_t {
UBX_MBUseUart2 = (1U << 0U) , SBF_UseBaseForYaw = (1U << 1U) , UBX_Use115200 = (1U << 2U) , UAVCAN_MBUseDedicatedBus = (1 << 3U) ,
HeightEllipsoid = (1U << 4) , GPSL5HealthOverride = (1U << 5) , AlwaysRTCMDecode = (1U << 6) , DisableRTCMDecode = (1U << 7)
}
Protected Member Functions
bool option_set (const DriverOptions option) const
Protected Attributes
AP_Int8 _type [GPS_MAX_RECEIVERS]
AP_Int8 _navfilter
AP_Int8 _auto_switch
AP_Int16 _sbp_logmask
AP_Int8 _inject_to
uint32_t _last_instance_swap_ms
AP_Enum< SBAS_Mode > _sbas_mode
AP_Int8 _min_elevation
AP_Int8 _raw_data
AP_Int8 _gnss_mode [GPS_MAX_RECEIVERS]
AP_Int16 _rate_ms [GPS_MAX_RECEIVERS]
AP_Int8 _save_config
AP_Int8 _auto_config
AP_Vector3f _antenna_offset [GPS_MAX_RECEIVERS]
AP_Int16 _delay_ms [GPS_MAX_RECEIVERS]
AP_Int8 _com_port [GPS_MAX_RECEIVERS]
AP_Int8 _blend_mask
AP_Int16 _driver_options
AP_Int8 _primary
MovingBase mb_params [GPS_MAX_RECEIVERS]
uint32_t _log_gps_bit = -1
Private Types
enum GPS_AUTO_CONFIG { GPS_AUTO_CONFIG_DISABLE = 0 , GPS_AUTO_CONFIG_ENABLE_SERIAL_ONLY = 1 , GPS_AUTO_CONFIG_ENABLE_ALL = 2 }
enum class GPSAutoSwitch { NONE = 0 , USE_BEST = 1 , BLEND = 2 , USE_PRIMARY_IF_3D_FIX = 4 }
Private Member Functions
uint16_t get_rate_ms (uint8_t instance) const
void detect_instance (uint8_t instance)
AP_GPS_Backend * _detect_instance (uint8_t instance)
void update_instance (uint8_t instance)
void handle_gps_rtcm_data (mavlink_channel_t chan, const mavlink_message_t &msg)
void handle_gps_inject (const mavlink_message_t &msg)
void inject_data (const uint8_t *data, uint16_t len)
void inject_data (uint8_t instance, const uint8_t *data, uint16_t len)
bool calc_blend_weights (void)
void calc_blended_state (void)
bool should_log () const
bool needs_uart (GPS_Type type) const
void update_primary (void)
Update primary instance.
uint16_t gps_yaw_cdeg (uint8_t instance) const
void Write_GPS (uint8_t instance)
Private Attributes
HAL_Semaphore rsem
GPS_timing timing [GPS_MAX_INSTANCES]
GPS_State state [GPS_MAX_INSTANCES]
AP_GPS_Backend * drivers [GPS_MAX_RECEIVERS]
AP_HAL::UARTDriver * _port [GPS_MAX_RECEIVERS]
uint8_t primary_instance
primary GPS instance
uint8_t num_instances
number of GPS instances present
uint8_t locked_ports
struct AP_GPS::detect_state detect_state [GPS_MAX_RECEIVERS]
struct {
const char * blob
uint16_t remaining
} initblob_state [GPS_MAX_RECEIVERS]
struct AP_GPS::rtcm_buffer * rtcm_buffer
struct {
uint16_t fragments_used
uint16_t fragments_discarded
} rtcm_stats
Vector3f _blended_antenna_offset
float _blended_lag_sec
float _blend_weights [GPS_MAX_RECEIVERS]
bool _output_is_blended
uint8_t _blend_health_counter
bool _force_disable_gps
bool _force_disable_gps_yaw
Static Private Attributes
static AP_GPS * _singleton
static const uint32_t _baudrates [] = {9600U, 115200U, 4800U, 19200U, 38400U, 57600U, 230400U, 460800U}
static const char _initialisation_blob []
static const char _initialisation_raw_blob []
Friends
class AP_GPS_ERB
class AP_GPS_GSOF
class AP_GPS_MAV
class AP_GPS_MSP
class AP_GPS_ExternalAHRS
class AP_GPS_NMEA
class AP_GPS_NOVA
class AP_GPS_PX4
class AP_GPS_SBF
class AP_GPS_SBP
class AP_GPS_SBP2
class AP_GPS_SIRF
class AP_GPS_UBLOX
class AP_GPS_Backend
class AP_GPS_DroneCAN
Detailed Description
GPS driver main class
Definition at line 75 of file AP_GPS.h.
Member Enumeration Documentation
CovarianceType
enum class AP_GPS::CovarianceType : uint8_t strong
Enumerator
UNKNOWN
The GPS does not support any accuracy metrics.
APPROXIMATED
The accuracy is approximated through metrics such as HDOP/VDOP.
DIAGONAL_KNOWN
The diagonal (east, north, up) components of covariance are reported by the GPS.
KNOWN
The full covariance array is reported by the GPS.
Definition at line 175 of file AP_GPS.h.
DriverOptions
enum AP_GPS::DriverOptions : int16_t protected
Enumerator
UBX_MBUseUart2
SBF_UseBaseForYaw
UBX_Use115200
UAVCAN_MBUseDedicatedBus
HeightEllipsoid
GPSL5HealthOverride
AlwaysRTCMDecode
DisableRTCMDecode
Definition at line 622 of file AP_GPS.h.
GPS_AUTO_CONFIG
enum AP_GPS::GPS_AUTO_CONFIG private
Enumerator
GPS_AUTO_CONFIG_DISABLE
GPS_AUTO_CONFIG_ENABLE_SERIAL_ONLY
GPS_AUTO_CONFIG_ENABLE_ALL
Definition at line 770 of file AP_GPS.h.
GPS_Engine_Setting
enum AP_GPS::GPS_Engine_Setting
Enumerator
GPS_ENGINE_NONE
GPS_ENGINE_PORTABLE
GPS_ENGINE_STATIONARY
GPS_ENGINE_PEDESTRIAN
GPS_ENGINE_AUTOMOTIVE
GPS_ENGINE_SEA
GPS_ENGINE_AIRBORNE_1G
GPS_ENGINE_AIRBORNE_2G
GPS_ENGINE_AIRBORNE_4G
Definition at line 155 of file AP_GPS.h.
GPS_Role
enum AP_GPS::GPS_Role
Enumerator
GPS_ROLE_NORMAL
GPS_ROLE_MB_BASE
GPS_ROLE_MB_ROVER
Definition at line 168 of file AP_GPS.h.
GPS_Status
enum AP_GPS::GPS_Status
GPS status codes. These are kept aligned with MAVLink by static_assert in AP_GPS.cpp
Enumerator
NO_GPS
No GPS connected/detected.
NO_FIX
Receiving valid GPS messages but no lock.
GPS_OK_FIX_2D
Receiving valid messages and 2D lock.
GPS_OK_FIX_3D
Receiving valid messages and 3D lock.
GPS_OK_FIX_3D_DGPS
Receiving valid messages and 3D lock with differential improvements.
GPS_OK_FIX_3D_RTK_FLOAT
Receiving valid messages and 3D RTK Float.
GPS_OK_FIX_3D_RTK_FIXED
Receiving valid messages and 3D RTK Fixed.
Definition at line 143 of file AP_GPS.h.
GPS_Type
enum AP_GPS::GPS_Type
Enumerator
GPS_TYPE_NONE
GPS_TYPE_AUTO
GPS_TYPE_UBLOX
GPS_TYPE_NMEA
GPS_TYPE_SIRF
GPS_TYPE_HIL
GPS_TYPE_SBP
GPS_TYPE_UAVCAN
GPS_TYPE_SBF
GPS_TYPE_GSOF
GPS_TYPE_ERB
GPS_TYPE_MAV
GPS_TYPE_NOVA
GPS_TYPE_HEMI
GPS_TYPE_UBLOX_RTK_BASE
GPS_TYPE_UBLOX_RTK_ROVER
GPS_TYPE_MSP
GPS_TYPE_ALLYSTAR
GPS_TYPE_EXTERNAL_AHRS
GPS_TYPE_UAVCAN_RTK_BASE
GPS_TYPE_UAVCAN_RTK_ROVER
GPS_TYPE_UNICORE_NMEA
GPS_TYPE_UNICORE_MOVINGBASE_NMEA
GPS_TYPE_SBF_DUAL_ANTENNA
Definition at line 109 of file AP_GPS.h.
GPSAutoSwitch
enum class AP_GPS::GPSAutoSwitch strong private
Enumerator
NONE
USE_BEST
BLEND
USE_PRIMARY_IF_3D_FIX
Definition at line 776 of file AP_GPS.h.
SBAS_Mode
enum class AP_GPS::SBAS_Mode : int8_t strong
Enumerator
Disabled
Enabled
DoNotChange
Definition at line 576 of file AP_GPS.h.
Constructor & Destructor Documentation
AP_GPS()
AP_GPS::AP_GPS ()
Definition at line 434 of file AP_GPS.cpp.
Member Function Documentation
_detect_instance()
AP_GPS_Backend * AP_GPS::_detect_instance (uint8_t instance) private
Definition at line 722 of file AP_GPS.cpp.
Referenced by detect_instance().
all_consistent()
bool AP_GPS::all_consistent (float & distance) const
Definition at line 1578 of file AP_GPS.cpp.
backends_healthy()
bool AP_GPS::backends_healthy (char failure_msg[], uint16_t failure_msg_len)
Definition at line 2281 of file AP_GPS.cpp.
blend_health_check()
bool AP_GPS::blend_health_check () const
Definition at line 1595 of file AP_GPS.cpp.
Referenced by is_healthy().
broadcast_first_configuration_failure_reason()
void AP_GPS::broadcast_first_configuration_failure_reason (void) const
Definition at line 1565 of file AP_GPS.cpp.
calc_blend_weights()
bool AP_GPS::calc_blend_weights (void) private
Definition at line 1864 of file AP_GPS.cpp.
Referenced by update_primary().
calc_blended_state()
void AP_GPS::calc_blended_state (void) private
Definition at line 2038 of file AP_GPS.cpp.
Referenced by update_primary().
CLASS_NO_COPY()
AP_GPS::CLASS_NO_COPY (AP_GPS)
clear_RTCMV3()
void AP_GPS::clear_RTCMV3 ()
Definition at line 1105 of file AP_GPS.cpp.
detect_instance()
void AP_GPS::detect_instance (uint8_t instance) private
Definition at line 697 of file AP_GPS.cpp.
Referenced by update_instance().
first_unconfigured_gps()
bool AP_GPS::first_unconfigured_gps (uint8_t & instance) const
Definition at line 1554 of file AP_GPS.cpp.
Referenced by broadcast_first_configuration_failure_reason(), and get_lag().
force_disable()
void AP_GPS::force_disable (bool disable) inline
Definition at line 553 of file AP_GPS.h.
Referenced by RC_Channel::do_aux_function().
get_antenna_offset()
const Vector3f & AP_GPS::get_antenna_offset (uint8_t instance) const
Definition at line 1828 of file AP_GPS.cpp.
Referenced by AP_DAL_GPS::start_frame().
get_error_codes() [1/2]
bool AP_GPS::get_error_codes (uint32_t & error_codes) const inline
Definition at line 574 of file AP_GPS.h.
Referenced by get_error_codes().
get_error_codes() [2/2]
bool AP_GPS::get_error_codes (uint8_t instance, uint32_t & error_codes) const
Definition at line 2326 of file AP_GPS.cpp.
get_hdop() [1/2]
uint16_t AP_GPS::get_hdop () const inline
Definition at line 418 of file AP_GPS.h.
Referenced by get_hdop(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
get_hdop() [2/2]
uint16_t AP_GPS::get_hdop (uint8_t instance) const inline
Definition at line 415 of file AP_GPS.h.
Referenced by AP_Spektrum_Telem::calc_gps_location(), AP_Frsky_SPort_Passthrough::calc_gps_status(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AP_OSD_Screen::draw_hdop(), and AP_DAL_GPS::start_frame().
get_itow()
uint32_t AP_GPS::get_itow (uint8_t instance) const
Definition at line 2318 of file AP_GPS.cpp.
get_lag() [1/2]
bool AP_GPS::get_lag (float & lag_sec) const inline
Definition at line 482 of file AP_GPS.h.
get_lag() [2/2]
bool AP_GPS::get_lag (uint8_t instance, float & lag_sec) const
Definition at line 1790 of file AP_GPS.cpp.
Referenced by calc_blended_state(), AP_GPS_Backend::check_new_itow(), get_lag(), gps_yaw_deg(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), and AP_DAL_GPS::start_frame().
get_rate_ms()
uint16_t AP_GPS::get_rate_ms (uint8_t instance) const private
Definition at line 1851 of file AP_GPS.cpp.
Referenced by AP_GPS_UBLOX::_configure_rate(), calc_blend_weights(), and AP_GPS_Backend::check_new_itow().
get_RelPosHeading()
void AP_GPS::get_RelPosHeading (uint32_t & timestamp, float & relPosHeading, float & relPosLength, float & relPosD, float & accHeading)
Definition at line 1080 of file AP_GPS.cpp.
get_RTCMV3()
bool AP_GPS::get_RTCMV3 (const uint8_t *& bytes, uint16_t & len)
Definition at line 1095 of file AP_GPS.cpp.
Referenced by update_instance().
get_semaphore()
HAL_Semaphore & AP_GPS::get_semaphore (void) inline
Definition at line 104 of file AP_GPS.h.
Referenced by AP_Hott_Telem::send_GPS().
get_singleton()
static AP_GPS * AP_GPS::get_singleton () inline static
Definition at line 99 of file AP_GPS.h.
Referenced by AP::gps().
get_type()
GPS_Type AP_GPS::get_type (uint8_t instance) const inline
Definition at line 566 of file AP_GPS.h.
Referenced by AP_GPS_Backend::get_type(), is_healthy(), and update_primary().
get_undulation() [1/2]
bool AP_GPS::get_undulation (float & undulation) const inline
Definition at line 326 of file AP_GPS.h.
get_undulation() [2/2]
bool AP_GPS::get_undulation (uint8_t instance, float & undulation) const
Definition at line 2337 of file AP_GPS.cpp.
Referenced by get_undulation(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
get_vdop() [1/2]
uint16_t AP_GPS::get_vdop () const inline
Definition at line 426 of file AP_GPS.h.
Referenced by get_vdop(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
get_vdop() [2/2]
uint16_t AP_GPS::get_vdop (uint8_t instance) const inline
Definition at line 423 of file AP_GPS.h.
gps_yaw_cdeg()
uint16_t AP_GPS::gps_yaw_cdeg (uint8_t instance) const private
Definition at line 1448 of file AP_GPS.cpp.
Referenced by send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
gps_yaw_deg() [1/2]
bool AP_GPS::gps_yaw_deg (float & yaw_deg, float & accuracy_deg, uint32_t & time_ms) const inline
Definition at line 386 of file AP_GPS.h.
gps_yaw_deg() [2/2]
bool AP_GPS::gps_yaw_deg (uint8_t instance, float & yaw_deg, float & accuracy_deg, uint32_t & time_ms) const
Definition at line 2408 of file AP_GPS.cpp.
Referenced by gps_yaw_cdeg(), gps_yaw_deg(), and AP_DAL_GPS::start_frame().
ground_course() [1/2]
float AP_GPS::ground_course () const inline
Definition at line 373 of file AP_GPS.h.
Referenced by ground_course(), ground_course_cd(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
ground_course() [2/2]
float AP_GPS::ground_course (uint8_t instance) const inline
Definition at line 370 of file AP_GPS.h.
Referenced by loop(), and AP_Hott_Telem::send_GPS().
ground_course_cd() [1/2]
int32_t AP_GPS::ground_course_cd () const inline
Definition at line 380 of file AP_GPS.h.
Referenced by ground_course_cd().
ground_course_cd() [2/2]
int32_t AP_GPS::ground_course_cd (uint8_t instance) const inline
Definition at line 377 of file AP_GPS.h.
Referenced by AR_AttitudeControl::get_forward_speed().
ground_speed() [1/2]
float AP_GPS::ground_speed () const inline
Definition at line 360 of file AP_GPS.h.
Referenced by ground_speed(), ground_speed_cm(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
ground_speed() [2/2]
float AP_GPS::ground_speed (uint8_t instance) const inline
Definition at line 357 of file AP_GPS.h.
Referenced by AP_AHRS::_airspeed_estimate(), AR_AttitudeControl::get_forward_speed(), loop(), AP_LTM_Telem::send_Gframe(), AP_Hott_Telem::send_GPS(), AP_Landing::type_slope_verify_land(), and GCS_MAVLINK::vfr_hud_airspeed().
ground_speed_cm()
uint32_t AP_GPS::ground_speed_cm (void) const inline
Definition at line 365 of file AP_GPS.h.
handle_gps_inject()
void AP_GPS::handle_gps_inject (const mavlink_message_t & msg) private
handle_gps_rtcm_data()
void AP_GPS::handle_gps_rtcm_data (mavlink_channel_t chan, const mavlink_message_t & msg) private
Definition at line 1683 of file AP_GPS.cpp.
handle_gps_rtcm_fragment()
void AP_GPS::handle_gps_rtcm_fragment (uint8_t flags, const uint8_t * data, uint8_t len)
Definition at line 1604 of file AP_GPS.cpp.
Referenced by handle_gps_rtcm_data().
handle_msg()
void AP_GPS::handle_msg (mavlink_channel_t chan, const mavlink_message_t & msg)
Referenced by GCS_MAVLINK::handle_message().
have_gps_yaw() [1/2]
bool AP_GPS::have_gps_yaw (uint8_t instance) const inline
Definition at line 465 of file AP_GPS.h.
have_gps_yaw() [2/2]
bool AP_GPS::have_gps_yaw (void) const inline
Definition at line 468 of file AP_GPS.h.
Referenced by gps_yaw_deg(), and have_gps_yaw().
have_gps_yaw_configured()
bool AP_GPS::have_gps_yaw_configured (uint8_t instance) const inline
Definition at line 475 of file AP_GPS.h.
Referenced by gps_yaw_cdeg().
have_vertical_velocity() [1/2]
bool AP_GPS::have_vertical_velocity (uint8_t instance) const inline
Definition at line 457 of file AP_GPS.h.
Referenced by NavEKF2_core::calcGpsGoodToAlign(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), and AP_DAL_GPS::start_frame().
have_vertical_velocity() [2/2]
bool AP_GPS::have_vertical_velocity (void) const inline
Definition at line 460 of file AP_GPS.h.
Referenced by calc_blended_state(), and have_vertical_velocity().
highest_supported_status()
AP_GPS::GPS_Status AP_GPS::highest_supported_status (uint8_t instance) const
Definition at line 903 of file AP_GPS.cpp.
horizontal_accuracy() [1/2]
bool AP_GPS::horizontal_accuracy (float & hacc) const inline
Definition at line 337 of file AP_GPS.h.
horizontal_accuracy() [2/2]
bool AP_GPS::horizontal_accuracy (uint8_t instance, float & hacc) const
Definition at line 520 of file AP_GPS.cpp.
Referenced by calc_blend_weights(), calc_blended_state(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), horizontal_accuracy(), position_covariance(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), AP_Hott_Telem::send_GPS(), send_mavlink_gps2_raw(), send_mavlink_gps_raw(), and AP_DAL_GPS::start_frame().
init()
void AP_GPS::init (const class AP_SerialManager & serial_manager)
Startup initialisation.
Definition at line 467 of file AP_GPS.cpp.
Referenced by setup().
inject_data() [1/2]
void AP_GPS::inject_data (const uint8_t * data, uint16_t len) private
Definition at line 1419 of file AP_GPS.cpp.
Referenced by handle_gps_rtcm_fragment(), inject_data(), inject_MBL_data(), and update_instance().
inject_data() [2/2]
void AP_GPS::inject_data (uint8_t instance, const uint8_t * data, uint16_t len) private
Definition at line 1435 of file AP_GPS.cpp.
inject_MBL_data()
void AP_GPS::inject_MBL_data (uint8_t * data, uint16_t length)
Definition at line 1117 of file AP_GPS.cpp.
is_healthy() [1/2]
bool AP_GPS::is_healthy (uint8_t instance) const
Definition at line 2227 of file AP_GPS.cpp.
Referenced by GCS::update_sensor_status_flags().
is_healthy() [2/2]
bool AP_GPS::is_healthy (void) const inline
Definition at line 537 of file AP_GPS.h.
Referenced by is_healthy().
istate_time_to_epoch_ms()
uint64_t AP_GPS::istate_time_to_epoch_ms (uint16_t gps_week, uint32_t gps_ms) static
convert GPS week and milliseconds to unix epoch in milliseconds
Definition at line 561 of file AP_GPS.cpp.
Referenced by last_message_epoch_usec(), and time_epoch_usec().
last_fix_time_ms() [1/2]
uint32_t AP_GPS::last_fix_time_ms (uint8_t instance) const inline
Definition at line 432 of file AP_GPS.h.
Referenced by AP_AdvancedFailsafe::check().
last_fix_time_ms() [2/2]
uint32_t AP_GPS::last_fix_time_ms (void) const inline
Definition at line 435 of file AP_GPS.h.
Referenced by calc_blended_state(), last_fix_time_ms(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
last_message_delta_time_ms() [1/2]
uint16_t AP_GPS::last_message_delta_time_ms (uint8_t instance) const inline
Definition at line 449 of file AP_GPS.h.
last_message_delta_time_ms() [2/2]
uint16_t AP_GPS::last_message_delta_time_ms (void) const inline
Definition at line 452 of file AP_GPS.h.
Referenced by last_message_delta_time_ms().
last_message_epoch_usec() [1/2]
uint64_t AP_GPS::last_message_epoch_usec () const inline
Definition at line 520 of file AP_GPS.h.
Referenced by last_message_epoch_usec().
last_message_epoch_usec() [2/2]
uint64_t AP_GPS::last_message_epoch_usec (uint8_t instance) const
calculate last message time since the unix epoch in microseconds
Definition at line 590 of file AP_GPS.cpp.
last_message_time_ms() [1/2]
uint32_t AP_GPS::last_message_time_ms (uint8_t instance) const inline
Definition at line 441 of file AP_GPS.h.
Referenced by loop(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), and AP_DAL_GPS::start_frame().
last_message_time_ms() [2/2]
uint32_t AP_GPS::last_message_time_ms (void) const inline
Definition at line 444 of file AP_GPS.h.
Referenced by calc_blended_state(), last_message_time_ms(), and update_instance().
location() [1/2]
const Location & AP_GPS::location () const inline
Definition at line 316 of file AP_GPS.h.
Referenced by all_consistent(), calc_blended_state(), location(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
location() [2/2]
const Location & AP_GPS::location (uint8_t instance) const inline
Definition at line 313 of file AP_GPS.h.
Referenced by AP_Baro::arming_checks(), AP_Frsky_SPort::calc_gps_latlng(), AP_Spektrum_Telem::calc_gps_location(), AP_Spektrum_Telem::calc_gps_status(), AP_Frsky_SPort_Passthrough::calc_gps_status(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AP_AdvancedFailsafe::check_altlimit(), AP_OSD_Screen::draw_gps_latitude(), AP_OSD_Screen::draw_gps_longitude(), AP_AHRS::get_relative_position_D_home(), NavEKF3_core::getGPSLLH(), NavEKF2_core::getLLH(), NavEKF3_core::getPosNE(), loop(), AP_AdvancedFailsafe::max_range_update(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), AP_Hott_Telem::send_GPS(), and AP_DAL_GPS::start_frame().
lock_port()
void AP_GPS::lock_port (uint8_t instance, bool lock)
Lock a GPS port, preventing the GPS driver from using it. This can be used to allow a user to control a GPS port via the SERIAL_CONTROL protocol
Definition at line 1405 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::handle_serial_control().
logging_enabled()
bool AP_GPS::logging_enabled (void) const inline
Definition at line 550 of file AP_GPS.h.
Referenced by logging_failed(), and GCS::update_sensor_status_flags().
logging_failed()
bool AP_GPS::logging_failed (void) const
Definition at line 2303 of file AP_GPS.cpp.
Referenced by GCS::update_sensor_status_flags().
logging_present()
bool AP_GPS::logging_present (void) const inline
Definition at line 549 of file AP_GPS.h.
Referenced by GCS::update_sensor_status_flags().
needs_uart()
bool AP_GPS::needs_uart (GPS_Type type) const private
Definition at line 448 of file AP_GPS.cpp.
Referenced by init().
num_sats() [1/2]
uint8_t AP_GPS::num_sats () const inline
Definition at line 394 of file AP_GPS.h.
Referenced by calc_blended_state(), num_sats(), send_mavlink_gps2_raw(), and send_mavlink_gps_raw().
num_sats() [2/2]
uint8_t AP_GPS::num_sats (uint8_t instance) const inline
Definition at line 391 of file AP_GPS.h.
Referenced by AP_Spektrum_Telem::calc_gps_status(), AP_Frsky_SPort_Passthrough::calc_gps_status(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AP_OSD_Screen::draw_sats(), loop(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), AP_LTM_Telem::send_Gframe(), AP_Hott_Telem::send_GPS(), and AP_DAL_GPS::start_frame().
num_sensors()
uint8_t AP_GPS::num_sensors (void) const
Definition at line 501 of file AP_GPS.cpp.
Referenced by AP_DAL_GPS::start_frame(), and NavEKF3_core::update_gps_selection().
option_set()
bool AP_GPS::option_set (const DriverOptions option) const inline protected
Definition at line 634 of file AP_GPS.h.
Referenced by _detect_instance(), handle_gps_rtcm_data(), AP_GPS_Backend::option_set(), and send_blob_start().
position_covariance()
AP_GPS::CovarianceType AP_GPS::position_covariance (const uint8_t instance, Matrix3f & cov) const
Definition at line 538 of file AP_GPS.cpp.
prepare_for_arming()
bool AP_GPS::prepare_for_arming (void)
Definition at line 2271 of file AP_GPS.cpp.
primary_sensor()
uint8_t AP_GPS::primary_sensor (void) const inline
Definition at line 271 of file AP_GPS.h.
Referenced by NavEKF2_core::readGpsData(), AP_DAL_GPS::start_frame(), and NavEKF3_core::update_gps_selection().
send_blob_start() [1/2]
void AP_GPS::send_blob_start (uint8_t instance)
Definition at line 614 of file AP_GPS.cpp.
Referenced by _detect_instance(), AP_GPS_SIRF::AP_GPS_SIRF(), AP_GPS_UBLOX::AP_GPS_UBLOX(), and send_blob_start().
send_blob_start() [2/2]
void AP_GPS::send_blob_start (uint8_t instance, const char * _blob, uint16_t size)
Definition at line 603 of file AP_GPS.cpp.
send_blob_update()
void AP_GPS::send_blob_update (uint8_t instance)
Definition at line 673 of file AP_GPS.cpp.
Referenced by _detect_instance(), and update_instance().
send_mavlink_gps2_raw()
void AP_GPS::send_mavlink_gps2_raw (mavlink_channel_t chan)
Definition at line 1500 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::try_send_message().
send_mavlink_gps_raw()
void AP_GPS::send_mavlink_gps_raw (mavlink_channel_t chan)
Definition at line 1465 of file AP_GPS.cpp.
Referenced by GCS_MAVLINK::try_send_message().
send_mavlink_gps_rtk()
void AP_GPS::send_mavlink_gps_rtk (mavlink_channel_t chan, uint8_t inst)
Referenced by GCS_MAVLINK::try_send_message().
set_force_disable_yaw()
void AP_GPS::set_force_disable_yaw (bool disable) inline
Definition at line 558 of file AP_GPS.h.
Referenced by RC_Channel::do_aux_function().
set_log_gps_bit()
void AP_GPS::set_log_gps_bit (uint32_t bit) inline
Definition at line 532 of file AP_GPS.h.
should_log()
bool AP_GPS::should_log () const private
Definition at line 911 of file AP_GPS.cpp.
Referenced by calc_blended_state(), AP_GPS_Backend::should_log(), and update_instance().
speed_accuracy() [1/2]
bool AP_GPS::speed_accuracy (float & sacc) const inline
Definition at line 332 of file AP_GPS.h.
speed_accuracy() [2/2]
bool AP_GPS::speed_accuracy (uint8_t instance, float & sacc) const
Definition at line 511 of file AP_GPS.cpp.
Referenced by calc_blend_weights(), calc_blended_state(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), AP_Hott_Telem::send_GPS(), send_mavlink_gps2_raw(), send_mavlink_gps_raw(), speed_accuracy(), and AP_DAL_GPS::start_frame().
status() [1/2]
GPS_Status AP_GPS::status (uint8_t instance) const inline
Query GPS status.
Definition at line 276 of file AP_GPS.h.
Referenced by AP_AHRS::_active_EKF_type(), AP_Baro::arming_checks(), AP_Spektrum_Telem::calc_gps_location(), AP_Frsky_SPort_Passthrough::calc_gps_status(), AP_AdvancedFailsafe::check_altlimit(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), AP_OSD_Screen::draw_sats(), AP_AHRS::get_relative_position_D_home(), NavEKF3_core::getGPSLLH(), NavEKF2_core::getLLH(), NavEKF3_core::getPosNE(), loop(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), NavEKF3_core::readGpsYawData(), AP_LTM_Telem::send_Gframe(), AP_DAL_GPS::start_frame(), AP_Landing::type_slope_verify_land(), NavEKF3_core::update_gps_selection(), and GCS::update_sensor_status_flags().
status() [2/2]
GPS_Status AP_GPS::status (void) const inline
Definition at line 282 of file AP_GPS.h.
Referenced by calc_blend_weights(), calc_blended_state(), get_lag(), send_mavlink_gps2_raw(), send_mavlink_gps_raw(), status(), status(), status_onechar(), update_instance(), update_primary(), and Write_AP_Logger_Log_Startup_messages().
status_onechar()
char AP_GPS::status_onechar (void) const inline
Definition at line 288 of file AP_GPS.h.
Referenced by AP_Hott_Telem::send_GPS().
time_epoch_usec() [1/2]
uint64_t AP_GPS::time_epoch_usec (uint8_t instance) const
calculate current time since the unix epoch in microseconds
Definition at line 570 of file AP_GPS.cpp.
time_epoch_usec() [2/2]
uint64_t AP_GPS::time_epoch_usec (void) const inline
Definition at line 515 of file AP_GPS.h.
Referenced by time_epoch_usec(), and update_instance().
time_week() [1/2]
uint16_t AP_GPS::time_week () const inline
Definition at line 410 of file AP_GPS.h.
Referenced by calc_blended_state(), and time_week().
time_week() [2/2]
uint16_t AP_GPS::time_week (uint8_t instance) const inline
Definition at line 407 of file AP_GPS.h.
Referenced by loop().
time_week_ms() [1/2]
uint32_t AP_GPS::time_week_ms () const inline
Definition at line 402 of file AP_GPS.h.
Referenced by calc_blended_state(), and time_week_ms().
time_week_ms() [2/2]
uint32_t AP_GPS::time_week_ms (uint8_t instance) const inline
Definition at line 399 of file AP_GPS.h.
Referenced by loop().
update()
void AP_GPS::update (void)
Update GPS state based on possible bytes received from the module. This routine must be called periodically (typically at 10Hz or more) to process incoming data.
Definition at line 1132 of file AP_GPS.cpp.
Referenced by loop().
update_instance()
void AP_GPS::update_instance (uint8_t instance) private
Definition at line 934 of file AP_GPS.cpp.
Referenced by update().
update_primary()
void AP_GPS::update_primary (void) private
Update primary instance.
Definition at line 1170 of file AP_GPS.cpp.
Referenced by update().
velocity() [1/2]
const Vector3f & AP_GPS::velocity () const inline
Definition at line 352 of file AP_GPS.h.
Referenced by calc_blended_state(), and velocity().
velocity() [2/2]
const Vector3f & AP_GPS::velocity (uint8_t instance) const inline
Definition at line 349 of file AP_GPS.h.
Referenced by AP_Airspeed::check_sensor_ahrs_wind_max_failures(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), and AP_DAL_GPS::start_frame().
vertical_accuracy() [1/2]
bool AP_GPS::vertical_accuracy (float & vacc) const inline
Definition at line 342 of file AP_GPS.h.
vertical_accuracy() [2/2]
bool AP_GPS::vertical_accuracy (uint8_t instance, float & vacc) const
Definition at line 529 of file AP_GPS.cpp.
Referenced by calc_blend_weights(), calc_blended_state(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), position_covariance(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), send_mavlink_gps2_raw(), send_mavlink_gps_raw(), AP_DAL_GPS::start_frame(), and vertical_accuracy().
Write_AP_Logger_Log_Startup_messages()
void AP_GPS::Write_AP_Logger_Log_Startup_messages ()
Definition at line 1776 of file AP_GPS.cpp.
Write_GPS()
void AP_GPS::Write_GPS (uint8_t instance) private
Referenced by calc_blended_state(), and update_instance().
Friends And Related Symbol Documentation
AP_GPS_Backend
friend class AP_GPS_Backend friend
Definition at line 90 of file AP_GPS.h.
AP_GPS_DroneCAN
friend class AP_GPS_DroneCAN friend
Definition at line 91 of file AP_GPS.h.
AP_GPS_ERB
friend class AP_GPS_ERB friend
Definition at line 77 of file AP_GPS.h.
Referenced by _detect_instance().
AP_GPS_ExternalAHRS
friend class AP_GPS_ExternalAHRS friend
Definition at line 81 of file AP_GPS.h.
Referenced by _detect_instance().
AP_GPS_GSOF
friend class AP_GPS_GSOF friend
Definition at line 78 of file AP_GPS.h.
Referenced by _detect_instance().
AP_GPS_MAV
friend class AP_GPS_MAV friend
Definition at line 79 of file AP_GPS.h.
Referenced by _detect_instance().
AP_GPS_MSP
friend class AP_GPS_MSP friend
Definition at line 80 of file AP_GPS.h.
Referenced by _detect_instance().
AP_GPS_NMEA
friend class AP_GPS_NMEA friend
Definition at line 82 of file AP_GPS.h.
Referenced by _detect_instance().
AP_GPS_NOVA
friend class AP_GPS_NOVA friend
Definition at line 83 of file AP_GPS.h.
Referenced by _detect_instance().
AP_GPS_PX4
friend class AP_GPS_PX4 friend
Definition at line 84 of file AP_GPS.h.
AP_GPS_SBF
friend class AP_GPS_SBF friend
Definition at line 85 of file AP_GPS.h.
Referenced by _detect_instance().
AP_GPS_SBP
friend class AP_GPS_SBP friend
Definition at line 86 of file AP_GPS.h.
Referenced by _detect_instance().
AP_GPS_SBP2
friend class AP_GPS_SBP2 friend
Definition at line 87 of file AP_GPS.h.
Referenced by _detect_instance().
AP_GPS_SIRF
friend class AP_GPS_SIRF friend
Definition at line 88 of file AP_GPS.h.
Referenced by _detect_instance().
AP_GPS_UBLOX
friend class AP_GPS_UBLOX friend
Definition at line 89 of file AP_GPS.h.
Referenced by _detect_instance().
Member Data Documentation
_antenna_offset
AP_Vector3f AP_GPS::_antenna_offset[GPS_MAX_RECEIVERS] protected
Definition at line 606 of file AP_GPS.h.
Referenced by calc_blended_state(), AP_GPS_Backend::calculate_moving_base_yaw(), and get_antenna_offset().
_auto_config
AP_Int8 AP_GPS::_auto_config protected
Definition at line 605 of file AP_GPS.h.
Referenced by _detect_instance(), AP_GPS_UBLOX::_request_next_config(), AP_GPS_NOVA::AP_GPS_NOVA(), AP_GPS_SBF::broadcast_configuration_failure_reason(), AP_GPS_UBLOX::get_lag(), AP_GPS_SBF::is_configured(), AP_GPS_UBLOX::is_configured(), AP_GPS_UBLOX::is_healthy(), AP_GPS_NOVA::read(), AP_GPS_SBF::read(), AP_GPS_NMEA::send_config(), and update_instance().
_auto_switch
AP_Int8 AP_GPS::_auto_switch protected
Definition at line 595 of file AP_GPS.h.
Referenced by init(), and update_primary().
_baudrates
const uint32_t AP_GPS::_baudrates = {9600U, 115200U, 4800U, 19200U, 38400U, 57600U, 230400U, 460800U} static private
Definition at line 82 of file AP_GPS.h.
Referenced by _detect_instance().
_blend_health_counter
uint8_t AP_GPS::_blend_health_counter private
Definition at line 748 of file AP_GPS.h.
Referenced by blend_health_check(), and update_primary().
_blend_mask
AP_Int8 AP_GPS::_blend_mask protected
Definition at line 609 of file AP_GPS.h.
Referenced by calc_blend_weights().
_blend_weights
float AP_GPS::_blend_weights[GPS_MAX_RECEIVERS] private
Definition at line 746 of file AP_GPS.h.
Referenced by calc_blend_weights(), and calc_blended_state().
_blended_antenna_offset
Vector3f AP_GPS::_blended_antenna_offset private
Definition at line 744 of file AP_GPS.h.
Referenced by calc_blended_state(), and get_antenna_offset().
_blended_lag_sec
float AP_GPS::_blended_lag_sec private
Definition at line 745 of file AP_GPS.h.
Referenced by calc_blended_state(), and get_lag().
_com_port
AP_Int8 AP_GPS::_com_port[GPS_MAX_RECEIVERS] protected
Definition at line 608 of file AP_GPS.h.
Referenced by AP_GPS_GSOF::AP_GPS_GSOF(), AP_GPS_SBF::read(), and AP_GPS_GSOF::read().
_delay_ms
AP_Int16 AP_GPS::_delay_ms[GPS_MAX_RECEIVERS] protected
Definition at line 607 of file AP_GPS.h.
Referenced by get_lag().
_driver_options
AP_Int16 AP_GPS::_driver_options protected
Definition at line 610 of file AP_GPS.h.
Referenced by option_set().
_force_disable_gps
bool AP_GPS::_force_disable_gps private
Definition at line 785 of file AP_GPS.h.
Referenced by force_disable(), status(), and update_instance().
_force_disable_gps_yaw
bool AP_GPS::_force_disable_gps_yaw private
Definition at line 788 of file AP_GPS.h.
Referenced by have_gps_yaw(), and set_force_disable_yaw().
_gnss_mode
AP_Int8 AP_GPS::_gnss_mode[GPS_MAX_RECEIVERS] protected
Definition at line 602 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps().
_initialisation_blob
const char AP_GPS::_initialisation_blob static private
Initial value:
=
    UBLOX_SET_BINARY_230400
    SIRF_SET_BINARY
    NMEA_UNICORE_SETUP
    ""
Definition at line 699 of file AP_GPS.h.
Referenced by AP_GPS(), and send_blob_start().
_initialisation_raw_blob
const char AP_GPS::_initialisation_raw_blob[] static private
Definition at line 700 of file AP_GPS.h.
_inject_to
AP_Int8 AP_GPS::_inject_to protected
Definition at line 597 of file AP_GPS.h.
Referenced by inject_data().
_last_instance_swap_ms
uint32_t AP_GPS::_last_instance_swap_ms protected
Definition at line 598 of file AP_GPS.h.
Referenced by init(), and update_primary().
_log_gps_bit
uint32_t AP_GPS::_log_gps_bit = -1 protected
Definition at line 620 of file AP_GPS.h.
Referenced by set_log_gps_bit(), and should_log().
_min_elevation
AP_Int8 AP_GPS::_min_elevation protected
Definition at line 600 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps().
_navfilter
AP_Int8 AP_GPS::_navfilter protected
Definition at line 594 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps().
_output_is_blended
bool AP_GPS::_output_is_blended private
Definition at line 747 of file AP_GPS.h.
Referenced by num_sensors(), and update_primary().
_port
AP_HAL::UARTDriver* AP_GPS::_port[GPS_MAX_RECEIVERS] private
Definition at line 668 of file AP_GPS.h.
Referenced by _detect_instance(), init(), and send_blob_update().
_primary
AP_Int8 AP_GPS::_primary protected
Definition at line 611 of file AP_GPS.h.
Referenced by init(), is_healthy(), and update_primary().
_rate_ms
AP_Int16 AP_GPS::_rate_ms[GPS_MAX_RECEIVERS] protected
Definition at line 603 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps(), get_rate_ms(), init(), and AP_GPS_NMEA::send_config().
_raw_data
AP_Int8 AP_GPS::_raw_data protected
Definition at line 601 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps(), AP_GPS_UBLOX::_request_next_config(), AP_GPS_UBLOX::_verify_rate(), logging_enabled(), AP_GPS_SBF::logging_healthy(), logging_present(), AP_GPS_SBF::prepare_for_arming(), and AP_GPS_SBF::read().
_save_config
AP_Int8 AP_GPS::_save_config protected
Definition at line 604 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::read(), and AP_GPS_NMEA::send_config().
_sbas_mode
AP_Enum<SBAS_Mode> AP_GPS::_sbas_mode protected
Definition at line 599 of file AP_GPS.h.
Referenced by AP_GPS_UBLOX::_parse_gps(), AP_GPS_UBLOX::_request_next_config(), AP_GPS_SBF::parse(), and AP_GPS_SBF::read().
_sbp_logmask
AP_Int16 AP_GPS::_sbp_logmask protected
Definition at line 596 of file AP_GPS.h.
_singleton
AP_GPS * AP_GPS::_singleton static private
Definition at line 639 of file AP_GPS.h.
Referenced by AP_GPS(), and get_singleton().
_type
AP_Int8 AP_GPS::_type[GPS_MAX_RECEIVERS] protected
Definition at line 593 of file AP_GPS.h.
Referenced by _detect_instance(), all_consistent(), backends_healthy(), clear_RTCMV3(), first_unconfigured_gps(), get_lag(), get_RTCMV3(), get_type(), gps_yaw_deg(), init(), inject_data(), inject_MBL_data(), is_healthy(), send_blob_start(), send_mavlink_gps2_raw(), update_instance(), and update_primary().
blob
const char* AP_GPS::blob
Definition at line 694 of file AP_GPS.h.
Referenced by send_blob_start(), and send_blob_update().
detect_state
struct AP_GPS::detect_state AP_GPS::detect_state[GPS_MAX_RECEIVERS] private
Referenced by AP_GPS_Backend::_detection_message().
drivers
AP_GPS_Backend* AP_GPS::drivers[GPS_MAX_RECEIVERS] private
Definition at line 667 of file AP_GPS.h.
Referenced by all_consistent(), broadcast_first_configuration_failure_reason(), clear_RTCMV3(), detect_instance(), first_unconfigured_gps(), get_error_codes(), get_itow(), get_lag(), get_RelPosHeading(), get_RTCMV3(), highest_supported_status(), inject_data(), is_healthy(), last_message_epoch_usec(), logging_failed(), prepare_for_arming(), time_epoch_usec(), update(), update_instance(), and Write_AP_Logger_Log_Startup_messages().
fragments_discarded
uint16_t AP_GPS::fragments_discarded
Definition at line 731 of file AP_GPS.h.
fragments_used
uint16_t AP_GPS::fragments_used
Definition at line 730 of file AP_GPS.h.
[struct]
struct { ... } AP_GPS::initblob_state[GPS_MAX_RECEIVERS]
Referenced by _detect_instance(), send_blob_start(), and send_blob_update().
locked_ports
uint8_t AP_GPS::locked_ports private
Definition at line 677 of file AP_GPS.h.
Referenced by lock_port(), and update_instance().
mb_params
MovingBase AP_GPS::mb_params[GPS_MAX_RECEIVERS] protected
Definition at line 617 of file AP_GPS.h.
Referenced by AP_GPS_Backend::calculate_moving_base_yaw().
num_instances
uint8_t AP_GPS::num_instances private
number of GPS instances present
Definition at line 674 of file AP_GPS.h.
Referenced by all_consistent(), get_rate_ms(), num_sensors(), update(), and Write_AP_Logger_Log_Startup_messages().
primary_instance
uint8_t AP_GPS::primary_instance private
primary GPS instance
Definition at line 671 of file AP_GPS.h.
Referenced by get_error_codes(), get_hdop(), get_lag(), get_undulation(), get_vdop(), gps_yaw_deg(), ground_course(), ground_course_cd(), ground_speed(), have_gps_yaw(), have_vertical_velocity(), horizontal_accuracy(), is_healthy(), last_fix_time_ms(), last_message_delta_time_ms(), last_message_epoch_usec(), last_message_time_ms(), location(), num_sats(), primary_sensor(), speed_accuracy(), status(), time_epoch_usec(), time_week(), time_week_ms(), update(), update_primary(), velocity(), and vertical_accuracy().
remaining
uint16_t AP_GPS::remaining
Definition at line 695 of file AP_GPS.h.
Referenced by _detect_instance(), and send_blob_update().
rsem
HAL_Semaphore AP_GPS::rsem private
Definition at line 640 of file AP_GPS.h.
Referenced by get_semaphore(), and update().
rtcm_buffer
struct AP_GPS::rtcm_buffer * AP_GPS::rtcm_buffer private
[struct]
struct { ... } AP_GPS::rtcm_stats
Referenced by handle_gps_rtcm_fragment().
state
GPS_State AP_GPS::state[GPS_MAX_INSTANCES] private
Definition at line 666 of file AP_GPS.h.
Referenced by _detect_instance(), all_consistent(), backends_healthy(), calc_blend_weights(), calc_blended_state(), detect_instance(), get_hdop(), get_lag(), get_RelPosHeading(), get_undulation(), get_vdop(), gps_yaw_deg(), ground_course(), ground_speed(), have_gps_yaw(), have_gps_yaw_configured(), have_vertical_velocity(), horizontal_accuracy(), init(), is_healthy(), last_message_epoch_usec(), location(), num_sats(), send_mavlink_gps2_raw(), speed_accuracy(), status(), time_epoch_usec(), time_week(), time_week_ms(), update(), update_instance(), update_primary(), velocity(), vertical_accuracy(), and Write_AP_Logger_Log_Startup_messages().
timing
GPS_timing AP_GPS::timing[GPS_MAX_INSTANCES] private
Definition at line 665 of file AP_GPS.h.
Referenced by calc_blended_state(), detect_instance(), is_healthy(), last_fix_time_ms(), last_message_delta_time_ms(), last_message_time_ms(), and update_instance().
var_info
const AP_Param::GroupInfo AP_GPS::var_info static
Definition at line 132 of file AP_GPS.h.
The documentation for this class was generated from the following files:
libraries/AP_GPS/AP_GPS.h
libraries/AP_GPS/AP_GPS.cpp