APM:Libraries: SITL::I2CRegisters Class Reference
SITL::I2CRegisters Class Reference abstract
#include <SIM_I2CDevice.h>
Public Types
enum class RegMode { RDONLY = 11 , WRONLY = 22 , RDWR = 33 }
Protected Member Functions
virtual int rdwr (I2C::i2c_rdwr_ioctl_data *&data)=0
void add_register (const char *name, uint8_t reg, RegMode mode)
void set_debug (bool value)
bool get_debug () const
Protected Attributes
const char * regname [256]
Bitmask< 256 > writable_registers
Bitmask< 256 > readable_registers
Private Attributes
bool debug
Detailed Description
Definition at line 15 of file SIM_I2CDevice.h.
Member Enumeration Documentation
RegMode
enum class SITL::I2CRegisters::RegMode strong
Enumerator
RDONLY
WRONLY
RDWR
Definition at line 19 of file SIM_I2CDevice.h.
Member Function Documentation
add_register()
void SITL::I2CRegisters::add_register (const char * name, uint8_t reg, RegMode mode) protected
Definition at line 15 of file SIM_I2CDevice.cpp.
Referenced by SITL::SMBusDevice::add_register(), SITL::I2CRegisters_ConfigurableLength::add_register(), SITL::InvensenseV3::init(), SITL::LM2755::init(), and SITL::ToshibaLED::init().
get_debug()
bool SITL::I2CRegisters::get_debug () const inline protected
Definition at line 36 of file SIM_I2CDevice.h.
rdwr()
virtual int SITL::I2CRegisters::rdwr (I2C::i2c_rdwr_ioctl_data *& data) protected pure virtual
Implemented in SITL::I2CRegisters_ConfigurableLength, SITL::I2CRegisters_16Bit, SITL::I2CRegisters_8Bit, SITL::InvensenseV3, SITL::IS31FL3195, SITL::LM2755, SITL::LP5562, SITL::SMBusDevice, SITL::MCP9600, and SITL::ToshibaLED.
set_debug()
void SITL::I2CRegisters::set_debug (bool value) inline protected
Definition at line 35 of file SIM_I2CDevice.h.
Referenced by SITL::MCP9600::init().
Member Data Documentation
debug
bool SITL::I2CRegisters::debug private
Definition at line 39 of file SIM_I2CDevice.h.
Referenced by get_debug(), and set_debug().
readable_registers
Bitmask<256> SITL::I2CRegisters::readable_registers protected
Definition at line 33 of file SIM_I2CDevice.h.
Referenced by add_register().
regname
const char* SITL::I2CRegisters::regname[256] protected
Definition at line 31 of file SIM_I2CDevice.h.
Referenced by add_register().
writable_registers
Bitmask<256> SITL::I2CRegisters::writable_registers protected
Definition at line 32 of file SIM_I2CDevice.h.
Referenced by add_register().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_I2CDevice.h
libraries/SITL/SIM_I2CDevice.cpp