APM:Libraries: AP_RCProtocol_CRSF Class Reference
AP_RCProtocol_CRSF Class Reference
#include <AP_RCProtocol_CRSF.h>
Classes
struct Frame
struct LinkStatisticsFrame
struct LinkStatisticsRXFrame
struct LinkStatisticsTXFrame
struct LinkStatus
struct SubsetChannelsFrame
Public Types
enum FrameType {
CRSF_FRAMETYPE_GPS = 0x02 , CRSF_FRAMETYPE_BATTERY_SENSOR = 0x08 , CRSF_FRAMETYPE_HEARTBEAT = 0x0B , CRSF_FRAMETYPE_VTX = 0x0F ,
CRSF_FRAMETYPE_VTX_TELEM = 0x10 , CRSF_FRAMETYPE_LINK_STATISTICS = 0x14 , CRSF_FRAMETYPE_RC_CHANNELS_PACKED = 0x16 , CRSF_FRAMETYPE_SUBSET_RC_CHANNELS_PACKED = 0x17 ,
CRSF_FRAMETYPE_RC_CHANNELS_PACKED_11BIT = 0x18 , CRSF_FRAMETYPE_LINK_STATISTICS_RX = 0x1C , CRSF_FRAMETYPE_LINK_STATISTICS_TX = 0x1D , CRSF_FRAMETYPE_ATTITUDE = 0x1E ,
CRSF_FRAMETYPE_FLIGHT_MODE = 0x21 , CRSF_FRAMETYPE_PARAM_DEVICE_PING = 0x28 , CRSF_FRAMETYPE_PARAM_DEVICE_INFO = 0x29 , CRSF_FRAMETYPE_PARAMETER_SETTINGS_ENTRY = 0x2B ,
CRSF_FRAMETYPE_PARAMETER_READ = 0x2C , CRSF_FRAMETYPE_PARAMETER_WRITE = 0x2D , CRSF_FRAMETYPE_COMMAND = 0x32 , CRSF_FRAMETYPE_AP_CUSTOM_TELEM_LEGACY = 0x7F ,
CRSF_FRAMETYPE_AP_CUSTOM_TELEM = 0x80
}
enum CommandID {
CRSF_COMMAND_FC = 0x01 , CRSF_COMMAND_BLUETOOTH = 0x03 , CRSF_COMMAND_OSD = 0x05 , CRSF_COMMAND_VTX = 0x08 ,
CRSF_COMMAND_LED = 0x09 , CRSF_COMMAND_GENERAL = 0x0A , CRSF_COMMAND_RX = 0x10
}
enum CommandFC { CRSF_COMMAND_FC_DISARM = 0x01 , CRSF_COMMAND_SCALE_CHANNEL = 0x02 }
enum CommandBluetooth { CRSF_COMMAND_BLUETOOTH_RESET = 0x01 , CRSF_COMMAND_BLUETOOTH_ENABLE = 0x02 , CRSF_COMMAND_BLUETOOTH_ECHO = 0x64 }
enum CommandOSD { CRSF_COMMAND_OSD_SEND = 0x01 }
enum CommandVTX {
CRSF_COMMAND_VTX_CHANNEL = 0x01 , CRSF_COMMAND_VTX_FREQ = 0x02 , CRSF_COMMAND_VTX_POWER = 0x03 , CRSF_COMMAND_VTX_PITMODE = 0x04 ,
CRSF_COMMAND_VTX_PITMODE_POWERUP = 0x05 , CRSF_COMMAND_VTX_POWER_DBM = 0x08
}
enum CommandLED {
CRSF_COMMAND_LED_SET_DEFAULT = 0x01 , CRSF_COMMAND_LED_COLOR = 0x02 , CRSF_COMMAND_LED_PULSE = 0x03 , CRSF_COMMAND_LED_BLINK = 0x04 ,
CRSF_COMMAND_LED_SHIFT = 0x05
}
enum CommandRX { CRSF_COMMAND_RX_BIND = 0x01 }
enum CommandGeneral {
CRSF_COMMAND_GENERAL_CHILD_DEVICE_REQUEST = 0x04 , CRSF_COMMAND_GENERAL_CHILD_DEVICE_FRAME = 0x05 , CRSF_COMMAND_GENERAL_FIRMWARE_UPDATE_BOOTLOADER = 0x0A , CRSF_COMMAND_GENERAL_FIRMWARE_UPDATE_ERASE = 0x0B ,
CRSF_COMMAND_GENERAL_WRITE_SERIAL_NUMBER = 0x13 , CRSF_COMMAND_GENERAL_USER_ID = 0x15 , CRSF_COMMAND_GENERAL_SOFTWARE_PRODUCT_KEY = 0x60 , CRSF_COMMAND_GENERAL_CRSF_SPEED_PROPOSAL = 0x70 ,
CRSF_COMMAND_GENERAL_CRSF_SPEED_RESPONSE = 0x71
}
enum CustomTelemSubTypeID : uint8_t { CRSF_AP_CUSTOM_TELEM_SINGLE_PACKET_PASSTHROUGH = 0xF0 , CRSF_AP_CUSTOM_TELEM_STATUS_TEXT = 0xF1 , CRSF_AP_CUSTOM_TELEM_MULTI_PACKET_PASSTHROUGH = 0xF2 }
enum DeviceAddress {
CRSF_ADDRESS_BROADCAST = 0x00 , CRSF_ADDRESS_USB = 0x10 , CRSF_ADDRESS_TBS_CORE_PNP_PRO = 0x80 , CRSF_ADDRESS_RESERVED1 = 0x8A ,
CRSF_ADDRESS_PNP_PRO_CURRENT_SENSOR = 0xC0 , CRSF_ADDRESS_PNP_PRO_GPS = 0xC2 , CRSF_ADDRESS_TBS_BLACKBOX = 0xC4 , CRSF_ADDRESS_FLIGHT_CONTROLLER = 0xC8 ,
CRSF_ADDRESS_RESERVED2 = 0xCA , CRSF_ADDRESS_RACE_TAG = 0xCC , CRSF_ADDRESS_VTX = 0xCE , CRSF_ADDRESS_RADIO_TRANSMITTER = 0xEA ,
CRSF_ADDRESS_CRSF_RECEIVER = 0xEC , CRSF_ADDRESS_CRSF_TRANSMITTER = 0xEE
}
enum ExtendedFrameOffset {
CRSF_EXTENDED_FRAME_LENGTH_OFFSET = 1 , CRSF_EXTENDED_FRAME_TYPE_OFFSET = 2 , CRSF_EXTENDED_FRAME_DESTINATION_OFFSET = 3 , CRSF_EXTENDED_FRAME_ORIGIN_OFFSET = 4 ,
CRSF_EXTENDED_FRAME_PAYLOAD_OFFSET = 5
}
enum class ProtocolType { PROTOCOL_CRSF , PROTOCOL_TRACER , PROTOCOL_ELRS }
enum RFMode {
CRSF_RF_MODE_4HZ = 0 , CRSF_RF_MODE_50HZ , CRSF_RF_MODE_150HZ , CRSF_RF_MODE_250HZ ,
ELRS_RF_MODE_4HZ , ELRS_RF_MODE_25HZ , ELRS_RF_MODE_50HZ , ELRS_RF_MODE_100HZ ,
ELRS_RF_MODE_150HZ , ELRS_RF_MODE_200HZ , ELRS_RF_MODE_250HZ , ELRS_RF_MODE_500HZ ,
RF_MODE_MAX_MODES , RF_MODE_UNKNOWN
}
Public Member Functions
AP_RCProtocol_CRSF (AP_RCProtocol &_frontend)
virtual ~AP_RCProtocol_CRSF ()
void process_byte (uint8_t byte, uint32_t baudrate) override
void process_handshake (uint32_t baudrate) override
void update (void) override
bool change_baud_rate (uint32_t baudrate)
uint32_t get_bootstrap_baud_rate () const
bool is_rx_active () const override
bool is_tx_active () const
const volatile LinkStatus & get_link_status () const
uint16_t get_link_rate (ProtocolType protocol) const
const char * get_protocol_string (ProtocolType protocol) const
Public Member Functions inherited from AP_RCProtocol_Backend
AP_RCProtocol_Backend (AP_RCProtocol &_frontend)
virtual ~AP_RCProtocol_Backend ()
virtual void process_pulse (uint32_t width_s0, uint32_t width_s1)
uint16_t read (uint8_t chan)
void read (uint16_t *pwm, uint8_t n)
bool new_input ()
uint8_t num_channels () const
virtual void start_bind (void)
uint32_t get_rc_frame_count (void) const
void reset_rc_frame_count (void)
uint32_t get_rc_input_count (void) const
uint32_t get_rc_protocols_mask (void) const
bool protocol_enabled (enum AP_RCProtocol::rcprotocol_t protocol) const
int16_t get_RSSI (void) const
int16_t get_rx_link_quality (void) const
AP_HAL::UARTDriver * get_UART (void) const
AP_HAL::UARTDriver * get_available_UART (void) const
bool have_UART (void) const
bool is_detected () const
Static Public Member Functions
static AP_RCProtocol_CRSF * get_singleton ()
Public Attributes
struct AP_RCProtocol_CRSF::Frame PACKED
struct AP_RCProtocol_CRSF::LinkStatisticsFrame PACKED
struct AP_RCProtocol_CRSF::LinkStatisticsRXFrame PACKED
struct AP_RCProtocol_CRSF::LinkStatisticsTXFrame PACKED
struct AP_RCProtocol_CRSF::SubsetChannelsFrame PACKED
Private Member Functions
void _process_byte (uint8_t byte)
bool check_frame (uint32_t timestamp_us)
void skip_to_next_frame (uint32_t timestamp_us)
bool decode_crsf_packet ()
bool process_telemetry (bool check_constraint=true)
void process_link_stats_frame (const void *data)
void process_link_stats_rx_frame (const void *data)
void process_link_stats_tx_frame (const void *data)
void decode_variable_bit_channels (const uint8_t *data, uint8_t frame_length, uint8_t nchannels, uint16_t *values)
void write_frame (Frame *frame)
void start_uart ()
AP_HAL::UARTDriver * get_current_UART ()
int16_t derive_scaled_lq_value (uint8_t uplink_lq)
Private Attributes
struct Frame _frame
uint8_t * _frame_bytes = (uint8_t*)&_frame
struct Frame _telemetry_frame
uint8_t _frame_ofs
const uint8_t MAX_CHANNELS = MIN((uint8_t)CRSF_MAX_CHANNELS, (uint8_t)MAX_RCIN_CHANNELS)
uint16_t _channels [CRSF_MAX_CHANNELS]
uint32_t _last_frame_time_us
uint32_t _last_tx_frame_time_us
uint32_t _last_uart_start_time_ms
uint32_t _last_rx_frame_time_us
uint32_t _start_frame_time_us
bool telem_available
uint32_t _new_baud_rate
bool _crsf_v3_active
bool _use_lq_for_rssi
volatile struct LinkStatus _link_status
AP_HAL::UARTDriver * _uart
Static Private Attributes
static AP_RCProtocol_CRSF * _singleton
static const uint16_t RF_MODE_RATES [RFMode::RF_MODE_MAX_MODES]
Additional Inherited Members
Protected Member Functions inherited from AP_RCProtocol_Backend
void add_input (uint8_t num_channels, uint16_t *values, bool in_failsafe, int16_t rssi=-1, int16_t rx_link_quality=-1)
void log_data (AP_RCProtocol::rcprotocol_t prot, uint32_t timestamp, const uint8_t *data, uint8_t len) const
Static Protected Member Functions inherited from AP_RCProtocol_Backend
static void decode_11bit_channels (const uint8_t *data, uint8_t nchannels, uint16_t *values, uint16_t mult, uint16_t div, uint16_t offset)
Protected Attributes inherited from AP_RCProtocol_Backend
struct AP_RCProtocol_Backend::Channels11Bit_8Chan PACKED
AP_RCProtocol & frontend
Detailed Description
Definition at line 39 of file AP_RCProtocol_CRSF.h.
Member Enumeration Documentation
CommandBluetooth
enum AP_RCProtocol_CRSF::CommandBluetooth
Enumerator
CRSF_COMMAND_BLUETOOTH_RESET
CRSF_COMMAND_BLUETOOTH_ENABLE
CRSF_COMMAND_BLUETOOTH_ECHO
Definition at line 119 of file AP_RCProtocol_CRSF.h.
CommandFC
enum AP_RCProtocol_CRSF::CommandFC
Enumerator
CRSF_COMMAND_FC_DISARM
CRSF_COMMAND_SCALE_CHANNEL
Definition at line 113 of file AP_RCProtocol_CRSF.h.
CommandGeneral
enum AP_RCProtocol_CRSF::CommandGeneral
Enumerator
CRSF_COMMAND_GENERAL_CHILD_DEVICE_REQUEST
CRSF_COMMAND_GENERAL_CHILD_DEVICE_FRAME
CRSF_COMMAND_GENERAL_FIRMWARE_UPDATE_BOOTLOADER
CRSF_COMMAND_GENERAL_FIRMWARE_UPDATE_ERASE
CRSF_COMMAND_GENERAL_WRITE_SERIAL_NUMBER
CRSF_COMMAND_GENERAL_USER_ID
CRSF_COMMAND_GENERAL_SOFTWARE_PRODUCT_KEY
CRSF_COMMAND_GENERAL_CRSF_SPEED_PROPOSAL
CRSF_COMMAND_GENERAL_CRSF_SPEED_RESPONSE
Definition at line 155 of file AP_RCProtocol_CRSF.h.
CommandID
enum AP_RCProtocol_CRSF::CommandID
Enumerator
CRSF_COMMAND_FC
CRSF_COMMAND_BLUETOOTH
CRSF_COMMAND_OSD
CRSF_COMMAND_VTX
CRSF_COMMAND_LED
CRSF_COMMAND_GENERAL
CRSF_COMMAND_RX
Definition at line 102 of file AP_RCProtocol_CRSF.h.
CommandLED
enum AP_RCProtocol_CRSF::CommandLED
Enumerator
CRSF_COMMAND_LED_SET_DEFAULT
CRSF_COMMAND_LED_COLOR
CRSF_COMMAND_LED_PULSE
CRSF_COMMAND_LED_BLINK
CRSF_COMMAND_LED_SHIFT
Definition at line 141 of file AP_RCProtocol_CRSF.h.
CommandOSD
enum AP_RCProtocol_CRSF::CommandOSD
Enumerator
CRSF_COMMAND_OSD_SEND
Definition at line 126 of file AP_RCProtocol_CRSF.h.
CommandRX
enum AP_RCProtocol_CRSF::CommandRX
Enumerator
CRSF_COMMAND_RX_BIND
Definition at line 150 of file AP_RCProtocol_CRSF.h.
CommandVTX
enum AP_RCProtocol_CRSF::CommandVTX
Enumerator
CRSF_COMMAND_VTX_CHANNEL
CRSF_COMMAND_VTX_FREQ
CRSF_COMMAND_VTX_POWER
CRSF_COMMAND_VTX_PITMODE
CRSF_COMMAND_VTX_PITMODE_POWERUP
CRSF_COMMAND_VTX_POWER_DBM
Definition at line 131 of file AP_RCProtocol_CRSF.h.
CustomTelemSubTypeID
enum AP_RCProtocol_CRSF::CustomTelemSubTypeID : uint8_t
Enumerator
CRSF_AP_CUSTOM_TELEM_SINGLE_PACKET_PASSTHROUGH
CRSF_AP_CUSTOM_TELEM_STATUS_TEXT
CRSF_AP_CUSTOM_TELEM_MULTI_PACKET_PASSTHROUGH
Definition at line 168 of file AP_RCProtocol_CRSF.h.
DeviceAddress
enum AP_RCProtocol_CRSF::DeviceAddress
Enumerator
CRSF_ADDRESS_BROADCAST
CRSF_ADDRESS_USB
CRSF_ADDRESS_TBS_CORE_PNP_PRO
CRSF_ADDRESS_RESERVED1
CRSF_ADDRESS_PNP_PRO_CURRENT_SENSOR
CRSF_ADDRESS_PNP_PRO_GPS
CRSF_ADDRESS_TBS_BLACKBOX
CRSF_ADDRESS_FLIGHT_CONTROLLER
CRSF_ADDRESS_RESERVED2
CRSF_ADDRESS_RACE_TAG
CRSF_ADDRESS_VTX
CRSF_ADDRESS_RADIO_TRANSMITTER
CRSF_ADDRESS_CRSF_RECEIVER
CRSF_ADDRESS_CRSF_TRANSMITTER
Definition at line 174 of file AP_RCProtocol_CRSF.h.
ExtendedFrameOffset
enum AP_RCProtocol_CRSF::ExtendedFrameOffset
Enumerator
CRSF_EXTENDED_FRAME_LENGTH_OFFSET
CRSF_EXTENDED_FRAME_TYPE_OFFSET
CRSF_EXTENDED_FRAME_DESTINATION_OFFSET
CRSF_EXTENDED_FRAME_ORIGIN_OFFSET
CRSF_EXTENDED_FRAME_PAYLOAD_OFFSET
Definition at line 191 of file AP_RCProtocol_CRSF.h.
FrameType
enum AP_RCProtocol_CRSF::FrameType
Enumerator
CRSF_FRAMETYPE_GPS
CRSF_FRAMETYPE_BATTERY_SENSOR
CRSF_FRAMETYPE_HEARTBEAT
CRSF_FRAMETYPE_VTX
CRSF_FRAMETYPE_VTX_TELEM
CRSF_FRAMETYPE_LINK_STATISTICS
CRSF_FRAMETYPE_RC_CHANNELS_PACKED
CRSF_FRAMETYPE_SUBSET_RC_CHANNELS_PACKED
CRSF_FRAMETYPE_RC_CHANNELS_PACKED_11BIT
CRSF_FRAMETYPE_LINK_STATISTICS_RX
CRSF_FRAMETYPE_LINK_STATISTICS_TX
CRSF_FRAMETYPE_ATTITUDE
CRSF_FRAMETYPE_FLIGHT_MODE
CRSF_FRAMETYPE_PARAM_DEVICE_PING
CRSF_FRAMETYPE_PARAM_DEVICE_INFO
CRSF_FRAMETYPE_PARAMETER_SETTINGS_ENTRY
CRSF_FRAMETYPE_PARAMETER_READ
CRSF_FRAMETYPE_PARAMETER_WRITE
CRSF_FRAMETYPE_COMMAND
CRSF_FRAMETYPE_AP_CUSTOM_TELEM_LEGACY
CRSF_FRAMETYPE_AP_CUSTOM_TELEM
Definition at line 75 of file AP_RCProtocol_CRSF.h.
ProtocolType
enum class AP_RCProtocol_CRSF::ProtocolType strong
Enumerator
PROTOCOL_CRSF
PROTOCOL_TRACER
PROTOCOL_ELRS
Definition at line 249 of file AP_RCProtocol_CRSF.h.
RFMode
enum AP_RCProtocol_CRSF::RFMode
Enumerator
CRSF_RF_MODE_4HZ
CRSF_RF_MODE_50HZ
CRSF_RF_MODE_150HZ
CRSF_RF_MODE_250HZ
ELRS_RF_MODE_4HZ
ELRS_RF_MODE_25HZ
ELRS_RF_MODE_50HZ
ELRS_RF_MODE_100HZ
ELRS_RF_MODE_150HZ
ELRS_RF_MODE_200HZ
ELRS_RF_MODE_250HZ
ELRS_RF_MODE_500HZ
RF_MODE_MAX_MODES
RF_MODE_UNKNOWN
Definition at line 255 of file AP_RCProtocol_CRSF.h.
Constructor & Destructor Documentation
AP_RCProtocol_CRSF()
AP_RCProtocol_CRSF::AP_RCProtocol_CRSF (AP_RCProtocol & _frontend)
Definition at line 168 of file AP_RCProtocol_CRSF.cpp.
~AP_RCProtocol_CRSF()
AP_RCProtocol_CRSF::~AP_RCProtocol_CRSF () virtual
Definition at line 189 of file AP_RCProtocol_CRSF.cpp.
Member Function Documentation
_process_byte()
void AP_RCProtocol_CRSF::_process_byte (uint8_t byte) private
Definition at line 226 of file AP_RCProtocol_CRSF.cpp.
Referenced by process_byte(), and update().
change_baud_rate()
bool AP_RCProtocol_CRSF::change_baud_rate (uint32_t baudrate)
Definition at line 640 of file AP_RCProtocol_CRSF.cpp.
check_frame()
bool AP_RCProtocol_CRSF::check_frame (uint32_t timestamp_us) private
Definition at line 257 of file AP_RCProtocol_CRSF.cpp.
Referenced by _process_byte(), and skip_to_next_frame().
decode_crsf_packet()
bool AP_RCProtocol_CRSF::decode_crsf_packet () private
Definition at line 413 of file AP_RCProtocol_CRSF.cpp.
Referenced by check_frame().
decode_variable_bit_channels()
void AP_RCProtocol_CRSF::decode_variable_bit_channels (const uint8_t * data, uint8_t frame_length, uint8_t nchannels, uint16_t * values) private
Definition at line 487 of file AP_RCProtocol_CRSF.cpp.
Referenced by decode_crsf_packet().
derive_scaled_lq_value()
int16_t AP_RCProtocol_CRSF::derive_scaled_lq_value (uint8_t uplink_lq) private
Definition at line 678 of file AP_RCProtocol_CRSF.cpp.
Referenced by process_link_stats_frame(), process_link_stats_rx_frame(), and process_link_stats_tx_frame().
get_bootstrap_baud_rate()
uint32_t AP_RCProtocol_CRSF::get_bootstrap_baud_rate () const inline
Definition at line 49 of file AP_RCProtocol_CRSF.h.
Referenced by change_baud_rate(), process_handshake(), and start_uart().
get_current_UART()
AP_HAL::UARTDriver * AP_RCProtocol_CRSF::get_current_UART () inline private
Definition at line 313 of file AP_RCProtocol_CRSF.h.
Referenced by decode_crsf_packet(), process_handshake(), process_telemetry(), and write_frame().
get_link_rate()
uint16_t AP_RCProtocol_CRSF::get_link_rate (ProtocolType protocol) const
Definition at line 205 of file AP_RCProtocol_CRSF.cpp.
get_link_status()
const volatile LinkStatus & AP_RCProtocol_CRSF::get_link_status () const inline
Definition at line 280 of file AP_RCProtocol_CRSF.h.
get_protocol_string()
const char * AP_RCProtocol_CRSF::get_protocol_string (ProtocolType protocol) const
Definition at line 194 of file AP_RCProtocol_CRSF.cpp.
get_singleton()
static AP_RCProtocol_CRSF * AP_RCProtocol_CRSF::get_singleton () inline static
Definition at line 71 of file AP_RCProtocol_CRSF.h.
Referenced by AP::crsf().
is_rx_active()
bool AP_RCProtocol_CRSF::is_rx_active () const inline override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 58 of file AP_RCProtocol_CRSF.h.
is_tx_active()
bool AP_RCProtocol_CRSF::is_tx_active () const inline
Definition at line 65 of file AP_RCProtocol_CRSF.h.
Referenced by process_telemetry(), and update().
process_byte()
void AP_RCProtocol_CRSF::process_byte (uint8_t byte, uint32_t baudrate) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 216 of file AP_RCProtocol_CRSF.cpp.
process_handshake()
void AP_RCProtocol_CRSF::process_handshake (uint32_t baudrate) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 661 of file AP_RCProtocol_CRSF.cpp.
process_link_stats_frame()
void AP_RCProtocol_CRSF::process_link_stats_frame (const void * data) private
Definition at line 577 of file AP_RCProtocol_CRSF.cpp.
Referenced by decode_crsf_packet().
process_link_stats_rx_frame()
void AP_RCProtocol_CRSF::process_link_stats_rx_frame (const void * data) private
Definition at line 606 of file AP_RCProtocol_CRSF.cpp.
Referenced by decode_crsf_packet().
process_link_stats_tx_frame()
void AP_RCProtocol_CRSF::process_link_stats_tx_frame (const void * data) private
Definition at line 618 of file AP_RCProtocol_CRSF.cpp.
Referenced by decode_crsf_packet().
process_telemetry()
bool AP_RCProtocol_CRSF::process_telemetry (bool check_constraint = true) private
Definition at line 550 of file AP_RCProtocol_CRSF.cpp.
Referenced by decode_crsf_packet(), and update().
skip_to_next_frame()
void AP_RCProtocol_CRSF::skip_to_next_frame (uint32_t timestamp_us) private
Definition at line 314 of file AP_RCProtocol_CRSF.cpp.
Referenced by _process_byte().
start_uart()
void AP_RCProtocol_CRSF::start_uart () private
Definition at line 630 of file AP_RCProtocol_CRSF.cpp.
Referenced by AP_RCProtocol_CRSF(), and update().
update()
void AP_RCProtocol_CRSF::update (void) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 343 of file AP_RCProtocol_CRSF.cpp.
Referenced by HALSITL::SITL_State_Common::sim_update(), and AP_VideoTX::update().
write_frame()
void AP_RCProtocol_CRSF::write_frame (Frame * frame) private
Definition at line 378 of file AP_RCProtocol_CRSF.cpp.
Referenced by process_telemetry().
Member Data Documentation
_channels
uint16_t AP_RCProtocol_CRSF::_channels[CRSF_MAX_CHANNELS] private
Definition at line 315 of file AP_RCProtocol_CRSF.h.
Referenced by check_frame(), decode_crsf_packet(), and decode_variable_bit_channels().
_crsf_v3_active
bool AP_RCProtocol_CRSF::_crsf_v3_active private
Definition at line 324 of file AP_RCProtocol_CRSF.h.
Referenced by decode_crsf_packet(), and get_protocol_string().
_frame
struct Frame AP_RCProtocol_CRSF::_frame private
Definition at line 291 of file AP_RCProtocol_CRSF.h.
Referenced by _process_byte(), check_frame(), and decode_crsf_packet().
_frame_bytes
uint8_t* AP_RCProtocol_CRSF::_frame_bytes = (uint8_t*)&_frame private
Definition at line 292 of file AP_RCProtocol_CRSF.h.
Referenced by _process_byte(), check_frame(), and skip_to_next_frame().
_frame_ofs
uint8_t AP_RCProtocol_CRSF::_frame_ofs private
Definition at line 294 of file AP_RCProtocol_CRSF.h.
Referenced by _process_byte(), check_frame(), and skip_to_next_frame().
_last_frame_time_us
uint32_t AP_RCProtocol_CRSF::_last_frame_time_us private
Definition at line 317 of file AP_RCProtocol_CRSF.h.
Referenced by check_frame(), and update().
_last_rx_frame_time_us
uint32_t AP_RCProtocol_CRSF::_last_rx_frame_time_us private
Definition at line 320 of file AP_RCProtocol_CRSF.h.
Referenced by check_frame(), and is_rx_active().
_last_tx_frame_time_us
uint32_t AP_RCProtocol_CRSF::_last_tx_frame_time_us private
Definition at line 318 of file AP_RCProtocol_CRSF.h.
Referenced by check_frame(), and is_tx_active().
_last_uart_start_time_ms
uint32_t AP_RCProtocol_CRSF::_last_uart_start_time_ms private
Definition at line 319 of file AP_RCProtocol_CRSF.h.
Referenced by update().
_link_status
volatile struct LinkStatus AP_RCProtocol_CRSF::_link_status private
Definition at line 329 of file AP_RCProtocol_CRSF.h.
Referenced by check_frame(), get_link_rate(), get_link_status(), process_link_stats_frame(), process_link_stats_rx_frame(), and process_link_stats_tx_frame().
_new_baud_rate
uint32_t AP_RCProtocol_CRSF::_new_baud_rate private
Definition at line 323 of file AP_RCProtocol_CRSF.h.
Referenced by change_baud_rate(), and decode_crsf_packet().
_singleton
AP_RCProtocol_CRSF * AP_RCProtocol_CRSF::_singleton static private
Definition at line 298 of file AP_RCProtocol_CRSF.h.
Referenced by AP_RCProtocol_CRSF(), get_singleton(), and ~AP_RCProtocol_CRSF().
_start_frame_time_us
uint32_t AP_RCProtocol_CRSF::_start_frame_time_us private
Definition at line 321 of file AP_RCProtocol_CRSF.h.
Referenced by _process_byte(), and skip_to_next_frame().
_telemetry_frame
struct Frame AP_RCProtocol_CRSF::_telemetry_frame private
Definition at line 293 of file AP_RCProtocol_CRSF.h.
Referenced by process_telemetry().
_uart
AP_HAL::UARTDriver* AP_RCProtocol_CRSF::_uart private
Definition at line 333 of file AP_RCProtocol_CRSF.h.
Referenced by AP_RCProtocol_CRSF(), decode_crsf_packet(), get_current_UART(), process_byte(), start_uart(), and update().
_use_lq_for_rssi
bool AP_RCProtocol_CRSF::_use_lq_for_rssi private
Definition at line 326 of file AP_RCProtocol_CRSF.h.
Referenced by process_link_stats_frame(), process_link_stats_rx_frame(), process_link_stats_tx_frame(), and update().
MAX_CHANNELS
const uint8_t AP_RCProtocol_CRSF::MAX_CHANNELS = MIN((uint8_t)CRSF_MAX_CHANNELS, (uint8_t)MAX_RCIN_CHANNELS) private
Definition at line 296 of file AP_RCProtocol_CRSF.h.
Referenced by check_frame().
PACKED [1/5]
struct AP_RCProtocol_CRSF::Frame AP_RCProtocol_CRSF::PACKED
PACKED [2/5]
struct AP_RCProtocol_CRSF::LinkStatisticsFrame AP_RCProtocol_CRSF::PACKED
PACKED [3/5]
struct AP_RCProtocol_CRSF::LinkStatisticsRXFrame AP_RCProtocol_CRSF::PACKED
PACKED [4/5]
struct AP_RCProtocol_CRSF::LinkStatisticsTXFrame AP_RCProtocol_CRSF::PACKED
PACKED [5/5]
struct AP_RCProtocol_CRSF::SubsetChannelsFrame AP_RCProtocol_CRSF::PACKED
RF_MODE_RATES
const uint16_t AP_RCProtocol_CRSF::RF_MODE_RATES static private
Initial value:
= {
    4, 50, 150, 250,
    4, 25, 50, 100, 150, 200, 250, 500
}
Definition at line 161 of file AP_RCProtocol_CRSF.h.
Referenced by get_link_rate().
telem_available
bool AP_RCProtocol_CRSF::telem_available private
Definition at line 322 of file AP_RCProtocol_CRSF.h.
Referenced by process_telemetry().
The documentation for this class was generated from the following files:
libraries/AP_RCProtocol/AP_RCProtocol_CRSF.h
libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp