APM:Libraries: SITL::SerialProximitySensor Class Reference
SITL::SerialProximitySensor Class Reference abstract
#include <SIM_SerialProximitySensor.h>
Public Member Functions
SerialProximitySensor ()
virtual void update (const Location &location)
virtual uint16_t reading_interval_ms () const
virtual uint32_t packet_for_location (const Location &location, uint8_t *data, uint8_t buflen)=0
float measure_distance_at_angle_bf (const Location &location, float angle) const
Public Member Functions inherited from SITL::SerialDevice
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Private Attributes
uint32_t last_sent_ms
Additional Inherited Members
Protected Member Functions inherited from SITL::SerialDevice
bool init_sitl_pointer () WARN_IF_UNUSED
Protected Attributes inherited from SITL::SerialDevice
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Detailed Description
Definition at line 33 of file SIM_SerialProximitySensor.h.
Constructor & Destructor Documentation
SerialProximitySensor()
SITL::SerialProximitySensor::SerialProximitySensor () inline
Definition at line 36 of file SIM_SerialProximitySensor.h.
Member Function Documentation
measure_distance_at_angle_bf()
float SITL::SerialProximitySensor::measure_distance_at_angle_bf (const Location & location, float angle) const inline
Definition at line 48 of file SIM_SerialProximitySensor.h.
Referenced by SITL::PS_TeraRangerTower::update_output(), SITL::PS_LightWare_SF45B::update_output_scan(), and SITL::PS_RPLidar::update_output_scan().
packet_for_location()
virtual uint32_t SITL::SerialProximitySensor::packet_for_location (const Location & location, uint8_t * data, uint8_t buflen) pure virtual
Implemented in SITL::PS_LightWare_SF45B, SITL::PS_RPLidar, and SITL::PS_TeraRangerTower.
Referenced by update().
reading_interval_ms()
virtual uint16_t SITL::SerialProximitySensor::reading_interval_ms () const inline virtual
Definition at line 41 of file SIM_SerialProximitySensor.h.
Referenced by update().
update()
void SerialProximitySensor::update (const Location & location) virtual
Reimplemented in SITL::PS_LightWare_SF45B, SITL::PS_RPLidar, and SITL::PS_TeraRangerTower.
Definition at line 29 of file SIM_SerialProximitySensor.cpp.
Member Data Documentation
last_sent_ms
uint32_t SITL::SerialProximitySensor::last_sent_ms private
Definition at line 54 of file SIM_SerialProximitySensor.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_SerialProximitySensor.h
libraries/SITL/SIM_SerialProximitySensor.cpp