APM:Libraries: AP_OSD_AbstractScreen Class Reference
AP_OSD_AbstractScreen Class Reference
#include <AP_OSD.h>
Public Member Functions
AP_OSD_AbstractScreen ()
virtual void draw (void)
void set_backend (AP_OSD_Backend *_backend)
Public Attributes
AP_Int8 enabled
AP_Int16 channel_min
AP_Int16 channel_max
Protected Types
enum unit_type {
ALTITUDE =0 , SPEED =1 , VSPEED =2 , DISTANCE =3 ,
DISTANCE_LONG =4 , TEMPERATURE =5 , UNIT_TYPE_LAST =6
}
Protected Member Functions
bool check_option (uint32_t option)
char u_icon (enum unit_type unit)
float u_scale (enum unit_type unit, float value)
Protected Attributes
AP_OSD_Backend * backend
AP_OSD * osd
Static Protected Attributes
static uint8_t symbols_lookup_table [AP_OSD_NUM_SYMBOLS]
Friends
class AP_OSD
Detailed Description
Definition at line 76 of file AP_OSD.h.
Member Enumeration Documentation
unit_type
enum AP_OSD_AbstractScreen::unit_type protected
Enumerator
ALTITUDE
SPEED
VSPEED
DISTANCE
DISTANCE_LONG
TEMPERATURE
UNIT_TYPE_LAST
Definition at line 100 of file AP_OSD.h.
Constructor & Destructor Documentation
AP_OSD_AbstractScreen()
AP_OSD_AbstractScreen::AP_OSD_AbstractScreen () inline
Definition at line 81 of file AP_OSD.h.
Member Function Documentation
check_option()
bool AP_OSD_AbstractScreen::check_option (uint32_t option) protected
Definition at line 1204 of file AP_OSD_Screen.cpp.
Referenced by AP_OSD_Screen::draw_horizon(), AP_OSD_Screen::draw_wind(), AP_OSD_Screen::get_arrow_font_index(), and AP_MSP_Telem_Backend::update_flight_mode_str().
draw()
virtual void AP_OSD_AbstractScreen::draw (void) inline virtual
Definition at line 82 of file AP_OSD.h.
Referenced by AP_OSD::update_osd().
set_backend()
void AP_OSD_AbstractScreen::set_backend (AP_OSD_Backend * _backend)
Definition at line 1198 of file AP_OSD_Screen.cpp.
Referenced by AP_OSD::update_osd().
u_icon()
char AP_OSD_AbstractScreen::u_icon (enum unit_type unit) protected
Definition at line 1212 of file AP_OSD_Screen.cpp.
Referenced by AP_OSD_Screen::draw_altitude(), AP_OSD_Screen::draw_aspd1(), AP_OSD_Screen::draw_aspd2(), AP_OSD_Screen::draw_aspeed(), AP_OSD_Screen::draw_atemp(), AP_OSD_Screen::draw_distance(), AP_OSD_Screen::draw_rngf(), AP_OSD_Screen::draw_sidebars(), AP_OSD_Screen::draw_speed(), AP_OSD_Screen::draw_stat(), AP_OSD_Screen::draw_temp(), and AP_OSD_Screen::draw_vspeed().
u_scale()
float AP_OSD_AbstractScreen::u_scale (enum unit_type unit, float value) protected
Definition at line 1258 of file AP_OSD_Screen.cpp.
Referenced by AP_OSD_Screen::draw_altitude(), AP_OSD_Screen::draw_aspd1(), AP_OSD_Screen::draw_aspd2(), AP_OSD_Screen::draw_aspeed(), AP_OSD_Screen::draw_atemp(), AP_OSD_Screen::draw_distance(), AP_OSD_Screen::draw_rngf(), AP_OSD_Screen::draw_sidebars(), AP_OSD_Screen::draw_speed(), AP_OSD_Screen::draw_stat(), AP_OSD_Screen::draw_temp(), and AP_OSD_Screen::draw_vspeed().
Friends And Related Symbol Documentation
AP_OSD
friend class AP_OSD friend
Definition at line 78 of file AP_OSD.h.
Member Data Documentation
backend
AP_OSD_Backend* AP_OSD_AbstractScreen::backend protected
Definition at line 113 of file AP_OSD.h.
Referenced by AP_OSD_Screen::draw_altitude(), AP_OSD_Screen::draw_aspd1(), AP_OSD_Screen::draw_aspd2(), AP_OSD_Screen::draw_aspeed(), AP_OSD_Screen::draw_atemp(), AP_OSD_Screen::draw_callsign(), AP_OSD_Screen::draw_compass(), AP_OSD_Screen::draw_dist(), AP_OSD_Screen::draw_distance(), AP_OSD_Screen::draw_flightime(), AP_OSD_Screen::draw_fltmode(), AP_OSD_Screen::draw_gps_latitude(), AP_OSD_Screen::draw_gps_longitude(), AP_OSD_Screen::draw_gspeed(), AP_OSD_Screen::draw_hdop(), AP_OSD_Screen::draw_heading(), AP_OSD_Screen::draw_home(), AP_OSD_Screen::draw_horizon(), AP_OSD_Screen::draw_message(), AP_OSD_ParamScreen::draw_parameter(), AP_OSD_Screen::draw_pitch_angle(), AP_OSD_Screen::draw_rngf(), AP_OSD_Screen::draw_roll_angle(), AP_OSD_Screen::draw_sats(), AP_OSD_Screen::draw_sidebars(), AP_OSD_Screen::draw_speed(), AP_OSD_Screen::draw_stat(), AP_OSD_Screen::draw_temp(), AP_OSD_Screen::draw_throttle(), AP_OSD_Screen::draw_vspeed(), AP_OSD_Screen::draw_waypoint(), AP_OSD_Screen::draw_wind(), AP_OSD_Screen::draw_xtrack_error(), and set_backend().
channel_max
AP_Int16 AP_OSD_AbstractScreen::channel_max
Definition at line 88 of file AP_OSD.h.
channel_min
AP_Int16 AP_OSD_AbstractScreen::channel_min
Definition at line 87 of file AP_OSD.h.
enabled
AP_Int8 AP_OSD_AbstractScreen::enabled
Definition at line 86 of file AP_OSD.h.
Referenced by AP_OSD::AP_OSD(), AP_OSD::next_screen(), and AP_OSD_ParamScreen::save_parameters().
osd
AP_OSD* AP_OSD_AbstractScreen::osd protected
Definition at line 114 of file AP_OSD.h.
Referenced by check_option(), AP_OSD_Screen::draw_dist(), AP_OSD_Screen::draw_distance(), AP_OSD_Screen::draw_sats(), AP_OSD_Screen::draw_sidebars(), AP_OSD_Screen::draw_stat(), AP_OSD_Screen::draw_vspeed(), AP_OSD_Screen::draw_waypoint(), AP_OSD_Screen::draw_xtrack_error(), set_backend(), u_icon(), u_scale(), and AP_OSD_ParamScreen::update_state_machine().
symbols_lookup_table
uint8_t AP_OSD_AbstractScreen::symbols_lookup_table static protected
Definition at line 116 of file AP_OSD.h.
Referenced by AP_OSD::init_backend().
The documentation for this class was generated from the following files:
libraries/AP_OSD/AP_OSD.h
libraries/AP_OSD/AP_OSD_Screen.cpp