APM:Libraries: AP_Filesystem_Param Class Reference
AP_Filesystem_Param Class Reference
#include <AP_Filesystem_Param.h>
Classes
struct cursor
struct header
struct rfile
Public Member Functions
int open (const char *fname, int flags, bool allow_absolute_paths=false) override
int close (int fd) override
int32_t read (int fd, void *buf, uint32_t count) override
int32_t lseek (int fd, int32_t offset, int whence) override
int stat (const char *pathname, struct stat *stbuf) override
int32_t write (int fd, const void *buf, uint32_t count) override
Public Member Functions inherited from AP_Filesystem_Backend
virtual int fsync (int fd)
virtual int unlink (const char *pathname)
virtual int mkdir (const char *pathname)
virtual void * opendir (const char *pathname)
virtual struct dirent * readdir (void *dirp)
virtual int closedir (void *dirp)
virtual int rename (const char *oldpath, const char *newpath)
virtual int64_t disk_free (const char *path)
virtual int64_t disk_space (const char *path)
virtual bool set_mtime (const char *filename, const uint32_t mtime_sec)
virtual bool retry_mount (void)
virtual void unmount (void)
virtual bool format (void)
virtual AP_Filesystem_Backend::FormatStatus get_format_status () const
virtual FileData * load_file (const char *filename)
virtual void unload_file (FileData *fd)
Private Member Functions
bool token_seek (const struct rfile &r, const uint32_t data_ofs, struct cursor &c)
uint8_t pack_param (const struct rfile &r, struct cursor &c, uint8_t *buf)
bool check_file_name (const char *fname)
bool finish_upload (const rfile &r)
bool param_upload_parse (const rfile &r, bool &need_retry)
Private Attributes
struct AP_Filesystem_Param::rfile file [max_open_file]
Static Private Attributes
static constexpr uint8_t num_cursors = 2
static constexpr uint8_t max_open_file = 4
static constexpr uint8_t max_pack_len = AP_MAX_NAME_SIZE + 2 + 4 + 4 + 3
static constexpr uint16_t pmagic = 0x671b
static constexpr uint16_t pmagic_with_default = 0x671c
Additional Inherited Members
Public Types inherited from AP_Filesystem_Backend
enum class FormatStatus {
NOT_STARTED , PENDING , IN_PROGRESS , SUCCESS ,
FAILURE
}
Protected Member Functions inherited from AP_Filesystem_Backend
bool file_op_allowed (void) const
Detailed Description
Definition at line 27 of file AP_Filesystem_Param.h.
Member Function Documentation
check_file_name()
bool AP_Filesystem_Param::check_file_name (const char * fname) private
Definition at line 485 of file AP_Filesystem_Param.cpp.
Referenced by open(), and stat().
close()
int AP_Filesystem_Param::close (int fd) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 126 of file AP_Filesystem_Param.cpp.
Referenced by open().
finish_upload()
bool AP_Filesystem_Param::finish_upload (const rfile & r) private
Definition at line 645 of file AP_Filesystem_Param.cpp.
Referenced by close().
lseek()
int32_t AP_Filesystem_Param::lseek (int fd, int32_t offset, int whence) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 449 of file AP_Filesystem_Param.cpp.
open()
int AP_Filesystem_Param::open (const char * fname, int flags, bool allow_absolute_paths = false) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 34 of file AP_Filesystem_Param.cpp.
Referenced by close(), lseek(), open(), read(), and write().
pack_param()
uint8_t AP_Filesystem_Param::pack_param (const struct rfile & r, struct cursor & c, uint8_t * buf) private
Definition at line 170 of file AP_Filesystem_Param.cpp.
Referenced by read(), and token_seek().
param_upload_parse()
bool AP_Filesystem_Param::param_upload_parse (const rfile & r, bool & need_retry) private
Definition at line 537 of file AP_Filesystem_Param.cpp.
Referenced by finish_upload().
read()
int32_t AP_Filesystem_Param::read (int fd, void * buf, uint32_t count) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 319 of file AP_Filesystem_Param.cpp.
stat()
int AP_Filesystem_Param::stat (const char * pathname, struct stat * stbuf) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 470 of file AP_Filesystem_Param.cpp.
token_seek()
bool AP_Filesystem_Param::token_seek (const struct rfile & r, const uint32_t data_ofs, struct cursor & c) private
Definition at line 282 of file AP_Filesystem_Param.cpp.
Referenced by read().
write()
int32_t AP_Filesystem_Param::write (int fd, const void * buf, uint32_t count) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 498 of file AP_Filesystem_Param.cpp.
Member Data Documentation
file
struct AP_Filesystem_Param::rfile AP_Filesystem_Param::file[max_open_file] private
Referenced by close(), lseek(), open(), read(), and write().
max_open_file
constexpr uint8_t AP_Filesystem_Param::max_open_file = 4 static constexpr private
Definition at line 44 of file AP_Filesystem_Param.h.
Referenced by close(), lseek(), open(), read(), and write().
max_pack_len
constexpr uint8_t AP_Filesystem_Param::max_pack_len = AP_MAX_NAME_SIZE + 2 + 4 + 4 + 3 static constexpr private
Definition at line 47 of file AP_Filesystem_Param.h.
Referenced by read(), and token_seek().
num_cursors
constexpr uint8_t AP_Filesystem_Param::num_cursors = 2 static constexpr private
Definition at line 41 of file AP_Filesystem_Param.h.
Referenced by open(), and read().
pmagic
constexpr uint16_t AP_Filesystem_Param::pmagic = 0x671b static constexpr private
Definition at line 50 of file AP_Filesystem_Param.h.
Referenced by param_upload_parse(), and write().
pmagic_with_default
constexpr uint16_t AP_Filesystem_Param::pmagic_with_default = 0x671c static constexpr private
Definition at line 51 of file AP_Filesystem_Param.h.
Referenced by read().
The documentation for this class was generated from the following files:
libraries/AP_Filesystem/AP_Filesystem_Param.h
libraries/AP_Filesystem/AP_Filesystem_Param.cpp