APM:Libraries: AP_Motors Class Reference
AP_Motors Class Reference abstract
#include <AP_Motors_Class.h>
Classes
struct AP_Motors_limit
Public Types
enum motor_frame_class {
MOTOR_FRAME_UNDEFINED = 0 , MOTOR_FRAME_QUAD = 1 , MOTOR_FRAME_HEXA = 2 , MOTOR_FRAME_OCTA = 3 ,
MOTOR_FRAME_OCTAQUAD = 4 , MOTOR_FRAME_Y6 = 5 , MOTOR_FRAME_HELI = 6 , MOTOR_FRAME_TRI = 7 ,
MOTOR_FRAME_SINGLE = 8 , MOTOR_FRAME_COAX = 9 , MOTOR_FRAME_TAILSITTER = 10 , MOTOR_FRAME_HELI_DUAL = 11 ,
MOTOR_FRAME_DODECAHEXA = 12 , MOTOR_FRAME_HELI_QUAD = 13 , MOTOR_FRAME_DECA = 14 , MOTOR_FRAME_SCRIPTING_MATRIX = 15 ,
MOTOR_FRAME_6DOF_SCRIPTING = 16 , MOTOR_FRAME_DYNAMIC_SCRIPTING_MATRIX = 17
}
enum motor_frame_type {
MOTOR_FRAME_TYPE_PLUS = 0 , MOTOR_FRAME_TYPE_X = 1 , MOTOR_FRAME_TYPE_V = 2 , MOTOR_FRAME_TYPE_H = 3 ,
MOTOR_FRAME_TYPE_VTAIL = 4 , MOTOR_FRAME_TYPE_ATAIL = 5 , MOTOR_FRAME_TYPE_PLUSREV = 6 , MOTOR_FRAME_TYPE_Y6B = 10 ,
MOTOR_FRAME_TYPE_Y6F = 11 , MOTOR_FRAME_TYPE_BF_X = 12 , MOTOR_FRAME_TYPE_DJI_X = 13 , MOTOR_FRAME_TYPE_CW_X = 14 ,
MOTOR_FRAME_TYPE_I = 15 , MOTOR_FRAME_TYPE_NYT_PLUS = 16 , MOTOR_FRAME_TYPE_NYT_X = 17 , MOTOR_FRAME_TYPE_BF_X_REV = 18 ,
MOTOR_FRAME_TYPE_Y4 = 19
}
enum class DesiredSpoolState : uint8_t { SHUT_DOWN = 0 , GROUND_IDLE = 1 , THROTTLE_UNLIMITED = 2 }
enum class SpoolState : uint8_t {
SHUT_DOWN = 0 , GROUND_IDLE = 1 , SPOOLING_UP = 2 , THROTTLE_UNLIMITED = 3 ,
SPOOLING_DOWN = 4
}
enum MotorOptions : uint8_t { BATT_RAW_VOLTAGE = (1 << 0U) }
Public Member Functions
const char * get_frame_string () const
void get_frame_and_type_string (char *buffer, uint8_t buflen) const
AP_Motors (uint16_t speed_hz=AP_MOTORS_SPEED_DEFAULT)
virtual bool arming_checks (size_t buflen, char *buffer) const
virtual bool motor_test_checks (size_t buflen, char *buffer) const
bool initialised_ok () const
void set_initialised_ok (bool val)
bool armed () const
void armed (bool arm)
void set_interlock (bool set)
bool get_interlock () const
bool get_spoolup_block () const
void set_spoolup_block (bool set)
void set_roll (float roll_in)
void set_roll_ff (float roll_in)
void set_pitch (float pitch_in)
void set_pitch_ff (float pitch_in)
void set_yaw (float yaw_in)
void set_yaw_ff (float yaw_in)
void set_throttle (float throttle_in)
void set_throttle_avg_max (float throttle_avg_max)
void set_throttle_filter_cutoff (float filt_hz)
void set_slew_filter_cutoff (float filt_hz)
void set_forward (float forward_in)
void set_lateral (float lateral_in)
virtual void set_roll_pitch (float roll_deg, float pitch_deg)
float get_roll () const
float get_roll_ff () const
float get_pitch () const
float get_pitch_ff () const
float get_yaw () const
float get_yaw_ff () const
float get_throttle_out () const
float get_throttle () const
float get_throttle_bidirectional () const
float get_throttle_slew_rate () const
float get_forward () const
float get_lateral () const
virtual float get_throttle_hover () const =0
void set_thrust_boost (bool enable)
bool get_thrust_boost () const
virtual uint8_t get_lost_motor () const
void set_desired_spool_state (enum DesiredSpoolState spool)
enum DesiredSpoolState get_desired_spool_state (void) const
enum SpoolState get_spool_state (void) const
void set_dt (float dt)
float get_dt () const
void set_limit_flag_pitch_roll_yaw (bool flag)
virtual void set_update_rate (uint16_t speed_hz)
virtual void init (motor_frame_class frame_class, motor_frame_type frame_type)=0
virtual void set_frame_class_and_type (motor_frame_class frame_class, motor_frame_type frame_type)=0
virtual void output ()=0
virtual void output_min ()=0
void output_test_seq (uint8_t motor_seq, int16_t pwm)
virtual uint32_t get_motor_mask ()=0
void set_radio_passthrough (float roll_input, float pitch_input, float throttle_input, float yaw_input)
virtual float get_roll_factor (uint8_t i)
virtual float get_pitch_factor (uint8_t i)
virtual bool is_motor_enabled (uint8_t i)
virtual bool init_targets_on_arming () const
bool is_digital_pwm_type () const
bool is_brushed_pwm_type () const
bool is_normal_pwm_type () const
MAV_TYPE get_frame_mav_type () const
virtual void rc_write (uint8_t chan, uint16_t pwm)
bool has_option (MotorOptions option)
Static Public Member Functions
static AP_Motors * get_singleton (void)
Public Attributes
struct AP_Motors::AP_Motors_limit limit
Protected Types
enum pwm_type {
PWM_TYPE_NORMAL = 0 , PWM_TYPE_ONESHOT = 1 , PWM_TYPE_ONESHOT125 = 2 , PWM_TYPE_BRUSHED = 3 ,
PWM_TYPE_DSHOT150 = 4 , PWM_TYPE_DSHOT300 = 5 , PWM_TYPE_DSHOT600 = 6 , PWM_TYPE_DSHOT1200 = 7 ,
PWM_TYPE_PWM_RANGE = 8
}
Protected Member Functions
virtual void output_armed_stabilizing ()=0
virtual void rc_write_angle (uint8_t chan, int16_t angle_cd)
virtual void rc_set_freq (uint32_t mask, uint16_t freq_hz)
uint32_t motor_mask_to_srv_channel_mask (uint32_t mask) const
void add_motor_num (int8_t motor_num)
virtual void update_throttle_filter ()=0
virtual void save_params_on_disarm ()
virtual const char * _get_frame_string () const =0
virtual const char * get_type_string () const
virtual void _output_test_seq (uint8_t motor_seq, int16_t pwm)=0
Protected Attributes
float _dt
uint16_t _speed_hz
float _roll_in
float _roll_in_ff
float _pitch_in
float _pitch_in_ff
float _yaw_in
float _yaw_in_ff
float _throttle_in
float _throttle_out
float _throttle_slew_rate
float _forward_in
float _lateral_in
float _throttle_avg_max
LowPassFilterFloat _throttle_filter
DerivativeFilterFloat_Size7 _throttle_slew
LowPassFilterFloat _throttle_slew_filter
DesiredSpoolState _spool_desired
SpoolState _spool_state
uint32_t _motor_fast_mask
uint32_t _motor_pwm_range_mask
float _roll_radio_passthrough
float _pitch_radio_passthrough
float _throttle_radio_passthrough
float _yaw_radio_passthrough
AP_Int8 _pwm_type
bool _thrust_boost
bool _thrust_balanced
float _thrust_boost_ratio
AP_Int16 _options
MAV_TYPE _mav_type
Private Attributes
bool _armed
bool _interlock
bool _initialised_ok
bool _spoolup_block
Static Private Attributes
static AP_Motors * _singleton
Detailed Description
Definition at line 56 of file AP_Motors_Class.h.
Member Enumeration Documentation
DesiredSpoolState
enum class AP_Motors::DesiredSpoolState : uint8_t strong
Enumerator
SHUT_DOWN
GROUND_IDLE
THROTTLE_UNLIMITED
Definition at line 171 of file AP_Motors_Class.h.
motor_frame_class
enum AP_Motors::motor_frame_class
Enumerator
MOTOR_FRAME_UNDEFINED
MOTOR_FRAME_QUAD
MOTOR_FRAME_HEXA
MOTOR_FRAME_OCTA
MOTOR_FRAME_OCTAQUAD
MOTOR_FRAME_Y6
MOTOR_FRAME_HELI
MOTOR_FRAME_TRI
MOTOR_FRAME_SINGLE
MOTOR_FRAME_COAX
MOTOR_FRAME_TAILSITTER
MOTOR_FRAME_HELI_DUAL
MOTOR_FRAME_DODECAHEXA
MOTOR_FRAME_HELI_QUAD
MOTOR_FRAME_DECA
MOTOR_FRAME_SCRIPTING_MATRIX
MOTOR_FRAME_6DOF_SCRIPTING
MOTOR_FRAME_DYNAMIC_SCRIPTING_MATRIX
Definition at line 59 of file AP_Motors_Class.h.
motor_frame_type
enum AP_Motors::motor_frame_type
Enumerator
MOTOR_FRAME_TYPE_PLUS
MOTOR_FRAME_TYPE_X
MOTOR_FRAME_TYPE_V
MOTOR_FRAME_TYPE_H
MOTOR_FRAME_TYPE_VTAIL
MOTOR_FRAME_TYPE_ATAIL
MOTOR_FRAME_TYPE_PLUSREV
MOTOR_FRAME_TYPE_Y6B
MOTOR_FRAME_TYPE_Y6F
MOTOR_FRAME_TYPE_BF_X
MOTOR_FRAME_TYPE_DJI_X
MOTOR_FRAME_TYPE_CW_X
MOTOR_FRAME_TYPE_I
MOTOR_FRAME_TYPE_NYT_PLUS
MOTOR_FRAME_TYPE_NYT_X
MOTOR_FRAME_TYPE_BF_X_REV
MOTOR_FRAME_TYPE_Y4
Definition at line 83 of file AP_Motors_Class.h.
MotorOptions
enum AP_Motors::MotorOptions : uint8_t
Enumerator
BATT_RAW_VOLTAGE
Definition at line 284 of file AP_Motors_Class.h.
pwm_type
enum AP_Motors::pwm_type protected
Enumerator
PWM_TYPE_NORMAL
PWM_TYPE_ONESHOT
PWM_TYPE_ONESHOT125
PWM_TYPE_BRUSHED
PWM_TYPE_DSHOT150
PWM_TYPE_DSHOT300
PWM_TYPE_DSHOT600
PWM_TYPE_DSHOT1200
PWM_TYPE_PWM_RANGE
Definition at line 357 of file AP_Motors_Class.h.
SpoolState
enum class AP_Motors::SpoolState : uint8_t strong
Enumerator
SHUT_DOWN
GROUND_IDLE
SPOOLING_UP
THROTTLE_UNLIMITED
SPOOLING_DOWN
Definition at line 182 of file AP_Motors_Class.h.
Constructor & Destructor Documentation
AP_Motors()
AP_Motors::AP_Motors (uint16_t speed_hz = AP_MOTORS_SPEED_DEFAULT)
Definition at line 30 of file AP_Motors_Class.cpp.
Member Function Documentation
_get_frame_string()
virtual const char * AP_Motors::_get_frame_string () const protected pure virtual
Implemented in AP_MotorsCoax, AP_MotorsHeli, AP_MotorsHeli_Dual, AP_MotorsHeli_Quad, AP_MotorsMatrix, AP_MotorsSingle, AP_MotorsTailsitter, AP_MotorsTri, and AP_MotorsMulticopter_test.
Referenced by get_frame_string().
_output_test_seq()
virtual void AP_Motors::_output_test_seq (uint8_t motor_seq, int16_t pwm) protected pure virtual
Implemented in AP_MotorsCoax, AP_MotorsHeli, AP_MotorsMatrix, AP_MotorsSingle, AP_MotorsTailsitter, AP_MotorsTri, and AP_MotorsMulticopter_test.
Referenced by output_test_seq().
add_motor_num()
void AP_Motors::add_motor_num (int8_t motor_num) protected
Definition at line 204 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsMatrix::add_motor_raw(), AP_MotorsCoax::init(), AP_MotorsSingle::init(), AP_MotorsTri::init(), AP_MotorsHeli_Quad::init_outputs(), and AP_MotorsHeli_Single::init_outputs().
armed() [1/2]
bool AP_Motors::armed () const inline
Definition at line 120 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli_Dual::calculate_armed_scalars(), AP_MotorsHeli_Quad::calculate_armed_scalars(), AP_MotorsHeli_Single::calculate_armed_scalars(), AP_MotorsMulticopter::get_current_limit_max_throttle(), AC_AutoTune::init_internals(), motor_order_test(), AP_MotorsHeli::output(), AP_MotorsHeli::output_logic(), AP_MotorsMulticopter::output_logic(), AP_MotorsMulticopter::output_motor_mask(), AP_MotorsMatrix::output_test_num(), output_test_seq(), AP_MotorsMulticopter::output_to_pwm(), AC_AutoTune::run(), AP_MotorsMatrix::set_frame_class_and_type(), AP_MotorsMulticopter::set_throttle_passthrough_for_esc_calibration(), stability_test(), and AP_MotorsMulticopter::update_throttle_filter().
armed() [2/2]
void AP_Motors::armed (bool arm)
Definition at line 75 of file AP_Motors_Class.cpp.
arming_checks()
bool AP_Motors::arming_checks (size_t buflen, char * buffer) const virtual
Reimplemented in AP_MotorsCoax, AP_MotorsHeli, AP_MotorsHeli_Dual, AP_MotorsHeli_Single, AP_MotorsMulticopter, AP_MotorsSingle, and AP_MotorsTri.
Definition at line 286 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsCoax::arming_checks(), AP_MotorsHeli::arming_checks(), AP_MotorsMulticopter::arming_checks(), AP_MotorsSingle::arming_checks(), and motor_test_checks().
get_desired_spool_state()
enum DesiredSpoolState AP_Motors::get_desired_spool_state (void) const inline
Definition at line 179 of file AP_Motors_Class.h.
get_dt()
float AP_Motors::get_dt () const inline
Definition at line 197 of file AP_Motors_Class.h.
Referenced by Thrust_Linearization::update_lift_max_from_batt_voltage().
get_forward()
float AP_Motors::get_forward () const inline
Definition at line 161 of file AP_Motors_Class.h.
get_frame_and_type_string()
void AP_Motors::get_frame_and_type_string (char * buffer, uint8_t buflen) const
Definition at line 60 of file AP_Motors_Class.cpp.
Referenced by print_all_motor_matrix(), setup(), and stability_test().
get_frame_mav_type()
MAV_TYPE AP_Motors::get_frame_mav_type () const inline
Definition at line 270 of file AP_Motors_Class.h.
get_frame_string()
const char * AP_Motors::get_frame_string () const
Definition at line 252 of file AP_Motors_Class.cpp.
Referenced by get_frame_and_type_string().
get_interlock()
bool AP_Motors::get_interlock () const inline
Definition at line 127 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli::output_logic(), AP_MotorsMulticopter::output_logic(), AP_MotorsMulticopter::output_motor_mask(), and AC_AutoTune::run().
get_lateral()
float AP_Motors::get_lateral () const inline
Definition at line 162 of file AP_Motors_Class.h.
get_lost_motor()
virtual uint8_t AP_Motors::get_lost_motor () const inline virtual
Reimplemented in AP_MotorsMatrix.
Definition at line 168 of file AP_Motors_Class.h.
get_motor_mask()
virtual uint32_t AP_Motors::get_motor_mask () pure virtual
Implemented in AP_MotorsCoax, AP_MotorsHeli, AP_MotorsHeli_Single, AP_MotorsMatrix, AP_MotorsMulticopter, AP_MotorsSingle, AP_MotorsTailsitter, and AP_MotorsTri.
Referenced by AP_InertialSensor::init(), and setup().
get_pitch()
float AP_Motors::get_pitch () const inline
Definition at line 153 of file AP_Motors_Class.h.
Referenced by AC_AutoTune_Heli::dwell_test_run(), and AC_AutoTune_Heli::rate_ff_test_run().
get_pitch_factor()
virtual float AP_Motors::get_pitch_factor (uint8_t i) inline virtual
Reimplemented in AP_MotorsMatrix.
Definition at line 252 of file AP_Motors_Class.h.
get_pitch_ff()
float AP_Motors::get_pitch_ff () const inline
Definition at line 154 of file AP_Motors_Class.h.
get_roll()
float AP_Motors::get_roll () const inline
Definition at line 151 of file AP_Motors_Class.h.
Referenced by AC_AutoTune_Heli::dwell_test_run(), and AC_AutoTune_Heli::rate_ff_test_run().
get_roll_factor()
virtual float AP_Motors::get_roll_factor (uint8_t i) inline virtual
Reimplemented in AP_MotorsMatrix, and AP_MotorsTri.
Definition at line 249 of file AP_Motors_Class.h.
Referenced by AP_MotorsMulticopter::output_motor_mask().
get_roll_ff()
float AP_Motors::get_roll_ff () const inline
Definition at line 152 of file AP_Motors_Class.h.
get_singleton()
static AP_Motors * AP_Motors::get_singleton (void) inline static
Definition at line 111 of file AP_Motors_Class.h.
Referenced by AC_AutoTune::init_internals(), and AP::motors().
get_spool_state()
enum SpoolState AP_Motors::get_spool_state (void) const inline
Definition at line 191 of file AP_Motors_Class.h.
get_spoolup_block()
bool AP_Motors::get_spoolup_block () const inline
Definition at line 130 of file AP_Motors_Class.h.
Referenced by AP_MotorsMulticopter::output_logic().
get_throttle()
float AP_Motors::get_throttle () const inline
Definition at line 158 of file AP_Motors_Class.h.
Referenced by AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsHeli::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsMulticopter::output_boost_throttle(), AP_MotorsHeli::output_disarmed(), AP_MotorsMulticopter::output_logic(), AP_MotorsMulticopter::output_rpyt(), AP_MotorsHeli::update_throttle_hover(), AP_MotorsMulticopter::update_throttle_hover(), and AC_AttitudeControl_Multi::update_throttle_rpy_mix().
get_throttle_bidirectional()
float AP_Motors::get_throttle_bidirectional () const inline
Definition at line 159 of file AP_Motors_Class.h.
Referenced by AP_Motors6DOF::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), and AP_Motors6DOF::output_armed_stabilizing_vectored_6dof().
get_throttle_hover()
virtual float AP_Motors::get_throttle_hover () const pure virtual
Implemented in AP_MotorsHeli, and AP_MotorsMulticopter.
Referenced by AC_AttitudeControl_Multi::get_throttle_avg_max(), AC_AttitudeControl_Sub::get_throttle_avg_max(), AC_PosControl::get_throttle_with_vibration_override(), AC_PosControl::init_z_controller(), AC_AttitudeControl::max_rate_step_bf_pitch(), AC_AttitudeControl::max_rate_step_bf_roll(), AC_AttitudeControl::max_rate_step_bf_yaw(), AC_PosControl::relax_z_controller(), AC_AttitudeControl_Multi::update_throttle_rpy_mix(), and AC_PosControl::update_z_controller().
get_throttle_out()
float AP_Motors::get_throttle_out () const inline
Definition at line 157 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Multi::update_throttle_rpy_mix().
get_throttle_slew_rate()
float AP_Motors::get_throttle_slew_rate () const inline
Definition at line 160 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Multi::update_throttle_gain_boost().
get_thrust_boost()
bool AP_Motors::get_thrust_boost () const inline
Definition at line 167 of file AP_Motors_Class.h.
get_type_string()
virtual const char * AP_Motors::get_type_string () const inline protected virtual
Reimplemented in AP_MotorsMatrix.
Definition at line 371 of file AP_Motors_Class.h.
Referenced by get_frame_and_type_string().
get_yaw()
float AP_Motors::get_yaw () const inline
Definition at line 155 of file AP_Motors_Class.h.
Referenced by AC_AutoTune_Heli::dwell_test_run(), and AC_AutoTune_Heli::rate_ff_test_run().
get_yaw_ff()
float AP_Motors::get_yaw_ff () const inline
Definition at line 156 of file AP_Motors_Class.h.
has_option()
bool AP_Motors::has_option (MotorOptions option) inline
Definition at line 287 of file AP_Motors_Class.h.
Referenced by Thrust_Linearization::update_lift_max_from_batt_voltage().
init()
virtual void AP_Motors::init (motor_frame_class frame_class, motor_frame_type frame_type) pure virtual
Implemented in AP_MotorsCoax, AP_MotorsHeli, AP_MotorsMatrix, AP_MotorsSingle, AP_MotorsTailsitter, AP_MotorsTri, and AP_MotorsMulticopter_test.
Referenced by setup().
init_targets_on_arming()
virtual bool AP_Motors::init_targets_on_arming () const inline virtual
Reimplemented in AP_MotorsHeli.
Definition at line 259 of file AP_Motors_Class.h.
initialised_ok()
bool AP_Motors::initialised_ok () const inline
Definition at line 116 of file AP_Motors_Class.h.
Referenced by AP_MotorsMatrix::add_motor_raw(), arming_checks(), AP_MotorsHeli_Dual::init_outputs(), AP_MotorsHeli_Quad::init_outputs(), AP_MotorsHeli_Single::init_outputs(), AP_MotorsHeli_Dual::output_to_motors(), AP_MotorsHeli_Quad::output_to_motors(), AP_MotorsHeli_Single::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsTailsitter::output_to_motors(), print_all_motor_matrix(), and setup().
is_brushed_pwm_type()
bool AP_Motors::is_brushed_pwm_type () const inline
Definition at line 265 of file AP_Motors_Class.h.
is_digital_pwm_type()
bool AP_Motors::is_digital_pwm_type () const
Definition at line 233 of file AP_Motors_Class.cpp.
is_motor_enabled()
virtual bool AP_Motors::is_motor_enabled (uint8_t i) inline virtual
Reimplemented in AP_MotorsMulticopter.
Definition at line 255 of file AP_Motors_Class.h.
is_normal_pwm_type()
bool AP_Motors::is_normal_pwm_type () const inline
Definition at line 268 of file AP_Motors_Class.h.
motor_mask_to_srv_channel_mask()
uint32_t AP_Motors::motor_mask_to_srv_channel_mask (uint32_t mask) const protected
Definition at line 188 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsCoax::get_motor_mask(), AP_MotorsMatrix::get_motor_mask(), AP_MotorsSingle::get_motor_mask(), AP_MotorsTri::get_motor_mask(), and rc_set_freq().
motor_test_checks()
bool AP_Motors::motor_test_checks (size_t buflen, char * buffer) const virtual
Reimplemented in AP_MotorsHeli.
Definition at line 296 of file AP_Motors_Class.cpp.
output()
virtual void AP_Motors::output () pure virtual
Implemented in AP_MotorsHeli, and AP_MotorsMulticopter.
Referenced by update_motors().
output_armed_stabilizing()
virtual void AP_Motors::output_armed_stabilizing () protected pure virtual
Implemented in AP_Motors6DOF, AP_MotorsCoax, AP_MotorsHeli, AP_MotorsMatrix, AP_MotorsSingle, AP_MotorsTailsitter, AP_MotorsTri, and AP_MotorsMulticopter_test.
Referenced by AP_MotorsMulticopter::output().
output_min()
virtual void AP_Motors::output_min () pure virtual
Implemented in AP_Motors6DOF, AP_MotorsHeli, and AP_MotorsMulticopter.
Referenced by setup().
output_test_seq()
void AP_Motors::output_test_seq (uint8_t motor_seq, int16_t pwm)
Definition at line 279 of file AP_Motors_Class.cpp.
Referenced by motor_order_test().
rc_set_freq()
void AP_Motors::rc_set_freq (uint32_t mask, uint16_t freq_hz) protected virtual
Definition at line 128 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsCoax::set_update_rate(), AP_MotorsHeli_Dual::set_update_rate(), AP_MotorsHeli_Quad::set_update_rate(), AP_MotorsHeli_Single::set_update_rate(), AP_MotorsMatrix::set_update_rate(), AP_MotorsSingle::set_update_rate(), and AP_MotorsTri::set_update_rate().
rc_write()
void AP_Motors::rc_write (uint8_t chan, uint16_t pwm) virtual
Definition at line 105 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsCoax::_output_test_seq(), AP_MotorsMatrix::_output_test_seq(), AP_MotorsSingle::_output_test_seq(), AP_MotorsTri::_output_test_seq(), AP_Motors6DOF::output_min(), AP_MotorsMulticopter::output_motor_mask(), AP_MotorsMatrix::output_test_num(), AP_Motors6DOF::output_to_motors(), AP_MotorsCoax::output_to_motors(), AP_MotorsHeli_Single::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsTri::output_to_motors(), and AP_MotorsMulticopter::set_throttle_passthrough_for_esc_calibration().
rc_write_angle()
void AP_Motors::rc_write_angle (uint8_t chan, int16_t angle_cd) protected virtual
Definition at line 119 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsTri::output_motor_mask(), AP_MotorsCoax::output_to_motors(), AP_MotorsHeli_Quad::output_to_motors(), AP_MotorsHeli_Single::output_to_motors(), AP_MotorsSingle::output_to_motors(), and AP_MotorsTri::output_to_motors().
save_params_on_disarm()
virtual void AP_Motors::save_params_on_disarm () inline protected virtual
Reimplemented in AP_MotorsHeli, and AP_MotorsMulticopter.
Definition at line 310 of file AP_Motors_Class.h.
Referenced by armed().
set_desired_spool_state()
void AP_Motors::set_desired_spool_state (enum DesiredSpoolState spool)
Definition at line 86 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsMulticopter::output_min(), AC_AutoTune::run(), and stability_test().
set_dt()
void AP_Motors::set_dt (float dt) inline
Definition at line 196 of file AP_Motors_Class.h.
Referenced by setup().
set_forward()
void AP_Motors::set_forward (float forward_in) inline
Definition at line 144 of file AP_Motors_Class.h.
set_frame_class_and_type()
virtual void AP_Motors::set_frame_class_and_type (motor_frame_class frame_class, motor_frame_type frame_type) pure virtual
Implemented in AP_MotorsCoax, AP_MotorsHeli, AP_MotorsMatrix, AP_MotorsSingle, AP_MotorsTailsitter, AP_MotorsTri, and AP_MotorsMulticopter_test.
set_initialised_ok()
void AP_Motors::set_initialised_ok (bool val) inline
Definition at line 117 of file AP_Motors_Class.h.
Referenced by AP_MotorsCoax::init(), AP_MotorsSingle::init(), AP_MotorsTailsitter::init(), AP_MotorsTri::init(), AP_MotorsHeli_Dual::init_outputs(), AP_MotorsHeli_Quad::init_outputs(), AP_MotorsHeli_Single::init_outputs(), AP_MotorsCoax::set_frame_class_and_type(), AP_MotorsTri::set_frame_class_and_type(), setup(), and AP_MotorsMatrix::setup_motors().
set_interlock()
void AP_Motors::set_interlock (bool set) inline
Definition at line 124 of file AP_Motors_Class.h.
Referenced by stability_test().
set_lateral()
void AP_Motors::set_lateral (float lateral_in) inline
Definition at line 145 of file AP_Motors_Class.h.
set_limit_flag_pitch_roll_yaw()
void AP_Motors::set_limit_flag_pitch_roll_yaw (bool flag)
Definition at line 214 of file AP_Motors_Class.cpp.
Referenced by AP_MotorsHeli::output_logic(), and AP_MotorsHeli::output_min().
set_pitch()
void AP_Motors::set_pitch (float pitch_in) inline
Definition at line 136 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), AC_AttitudeControl_Sub::rate_controller_run(), and stability_test().
set_pitch_ff()
void AP_Motors::set_pitch_ff (float pitch_in) inline
Definition at line 137 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Multi::rate_controller_run().
set_radio_passthrough()
void AP_Motors::set_radio_passthrough (float roll_input, float pitch_input, float throttle_input, float yaw_input)
Definition at line 94 of file AP_Motors_Class.cpp.
set_roll()
void AP_Motors::set_roll (float roll_in) inline
Definition at line 134 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), AC_AttitudeControl_Sub::rate_controller_run(), and stability_test().
set_roll_ff()
void AP_Motors::set_roll_ff (float roll_in) inline
Definition at line 135 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Multi::rate_controller_run().
set_roll_pitch()
virtual void AP_Motors::set_roll_pitch (float roll_deg, float pitch_deg) inline virtual
Definition at line 148 of file AP_Motors_Class.h.
set_slew_filter_cutoff()
void AP_Motors::set_slew_filter_cutoff (float filt_hz) inline
Definition at line 143 of file AP_Motors_Class.h.
set_spoolup_block()
void AP_Motors::set_spoolup_block (bool set) inline
Definition at line 131 of file AP_Motors_Class.h.
set_throttle()
void AP_Motors::set_throttle (float throttle_in) inline
Definition at line 140 of file AP_Motors_Class.h.
Referenced by AC_Autorotation::set_collective(), AC_AttitudeControl_Heli::set_throttle_out(), AC_AttitudeControl_Multi::set_throttle_out(), AC_AttitudeControl_Sub::set_throttle_out(), and stability_test().
set_throttle_avg_max()
void AP_Motors::set_throttle_avg_max (float throttle_avg_max) inline
Definition at line 141 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Multi::set_throttle_out(), AC_AttitudeControl_Sub::set_throttle_out(), and setup().
set_throttle_filter_cutoff()
void AP_Motors::set_throttle_filter_cutoff (float filt_hz) inline
Definition at line 142 of file AP_Motors_Class.h.
Referenced by AC_Autorotation::set_collective(), AC_AttitudeControl_Heli::set_throttle_out(), AC_AttitudeControl_Multi::set_throttle_out(), and AC_AttitudeControl_Sub::set_throttle_out().
set_thrust_boost()
void AP_Motors::set_thrust_boost (bool enable) inline
Definition at line 166 of file AP_Motors_Class.h.
Referenced by update_motors().
set_update_rate()
virtual void AP_Motors::set_update_rate (uint16_t speed_hz) inline virtual
Reimplemented in AP_MotorsCoax, AP_MotorsHeli_Dual, AP_MotorsHeli_Quad, AP_MotorsHeli_Single, AP_MotorsMatrix, AP_MotorsSingle, AP_MotorsTailsitter, AP_MotorsTri, and AP_MotorsHeli.
Definition at line 221 of file AP_Motors_Class.h.
Referenced by setup().
set_yaw()
void AP_Motors::set_yaw (float yaw_in) inline
Definition at line 138 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), AC_AttitudeControl_Sub::rate_controller_run(), and stability_test().
set_yaw_ff()
void AP_Motors::set_yaw_ff (float yaw_in) inline
Definition at line 139 of file AP_Motors_Class.h.
Referenced by AC_AttitudeControl_Multi::rate_controller_run().
update_throttle_filter()
virtual void AP_Motors::update_throttle_filter () protected pure virtual
Implemented in AP_MotorsHeli, and AP_MotorsMulticopter.
Member Data Documentation
_armed
bool AP_Motors::_armed private
Definition at line 388 of file AP_Motors_Class.h.
Referenced by armed(), armed(), and set_desired_spool_state().
_dt
float AP_Motors::_dt protected
Definition at line 313 of file AP_Motors_Class.h.
Referenced by AP_MotorsMatrix::check_for_failed_motor(), AP_MotorsMulticopter::get_current_limit_max_throttle(), get_dt(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsMulticopter::output_logic(), AP_MotorsHeli_Dual::servo_test(), AP_MotorsHeli_Single::servo_test(), AP_MotorsMulticopter::set_actuator_with_slew(), set_dt(), AP_MotorsHeli::update_throttle_filter(), and AP_MotorsMulticopter::update_throttle_filter().
_forward_in
float AP_Motors::_forward_in protected
Definition at line 324 of file AP_Motors_Class.h.
Referenced by get_forward(), AP_Motors6DOF::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), and set_forward().
_initialised_ok
bool AP_Motors::_initialised_ok private
Definition at line 390 of file AP_Motors_Class.h.
Referenced by initialised_ok(), and set_initialised_ok().
_interlock
bool AP_Motors::_interlock private
Definition at line 389 of file AP_Motors_Class.h.
Referenced by get_interlock(), output_test_seq(), and set_interlock().
_lateral_in
float AP_Motors::_lateral_in protected
Definition at line 325 of file AP_Motors_Class.h.
Referenced by get_lateral(), AP_Motors6DOF::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), and set_lateral().
_mav_type
MAV_TYPE AP_Motors::_mav_type protected
Definition at line 355 of file AP_Motors_Class.h.
Referenced by get_frame_mav_type(), AP_MotorsCoax::init(), AP_MotorsHeli::init(), AP_MotorsSingle::init(), AP_MotorsTailsitter::init(), AP_MotorsTri::init(), AP_MotorsMatrix::setup_deca_matrix(), AP_MotorsMatrix::setup_dodecahexa_matrix(), AP_MotorsMatrix::setup_hexa_matrix(), AP_MotorsMatrix::setup_motors(), AP_MotorsMatrix::setup_octa_matrix(), AP_MotorsMatrix::setup_octaquad_matrix(), AP_MotorsMatrix::setup_quad_matrix(), and AP_MotorsMatrix::setup_y6_matrix().
_motor_fast_mask
uint32_t AP_Motors::_motor_fast_mask protected
Definition at line 334 of file AP_Motors_Class.h.
Referenced by rc_set_freq().
_motor_pwm_range_mask
uint32_t AP_Motors::_motor_pwm_range_mask protected
Definition at line 337 of file AP_Motors_Class.h.
Referenced by rc_set_freq(), and rc_write().
_options
AP_Int16 AP_Motors::_options protected
Definition at line 353 of file AP_Motors_Class.h.
Referenced by has_option().
_pitch_in
float AP_Motors::_pitch_in protected
Definition at line 317 of file AP_Motors_Class.h.
Referenced by get_pitch(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsHeli::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsHeli::output_disarmed(), AP_MotorsHeli_Dual::servo_test(), AP_MotorsHeli_Single::servo_test(), and set_pitch().
_pitch_in_ff
float AP_Motors::_pitch_in_ff protected
Definition at line 318 of file AP_Motors_Class.h.
Referenced by get_pitch_ff(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsMulticopter::output_rpyt(), and set_pitch_ff().
_pitch_radio_passthrough
float AP_Motors::_pitch_radio_passthrough protected
Definition at line 341 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli::output_disarmed(), AP_MotorsCoax::output_to_motors(), AP_MotorsSingle::output_to_motors(), and set_radio_passthrough().
_pwm_type
AP_Int8 AP_Motors::_pwm_type protected
Definition at line 345 of file AP_Motors_Class.h.
Referenced by is_brushed_pwm_type(), is_digital_pwm_type(), is_normal_pwm_type(), rc_set_freq(), and AP_MotorsMulticopter::update_throttle_range().
_roll_in
float AP_Motors::_roll_in protected
Definition at line 315 of file AP_Motors_Class.h.
Referenced by get_roll(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsHeli::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsHeli::output_disarmed(), AP_MotorsHeli_Dual::servo_test(), AP_MotorsHeli_Single::servo_test(), and set_roll().
_roll_in_ff
float AP_Motors::_roll_in_ff protected
Definition at line 316 of file AP_Motors_Class.h.
Referenced by get_roll_ff(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsMulticopter::output_rpyt(), and set_roll_ff().
_roll_radio_passthrough
float AP_Motors::_roll_radio_passthrough protected
Definition at line 340 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli::output_disarmed(), AP_MotorsCoax::output_to_motors(), AP_MotorsSingle::output_to_motors(), and set_radio_passthrough().
_singleton
AP_Motors * AP_Motors::_singleton static private
Definition at line 393 of file AP_Motors_Class.h.
Referenced by AP_Motors(), and get_singleton().
_speed_hz
uint16_t AP_Motors::_speed_hz protected
Definition at line 314 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli::init(), AP_MotorsMatrix::init(), AP_MotorsTri::init(), set_update_rate(), AP_MotorsCoax::set_update_rate(), AP_MotorsHeli_Dual::set_update_rate(), AP_MotorsHeli_Quad::set_update_rate(), AP_MotorsHeli_Single::set_update_rate(), AP_MotorsMatrix::set_update_rate(), AP_MotorsSingle::set_update_rate(), AP_MotorsTailsitter::set_update_rate(), and AP_MotorsTri::set_update_rate().
_spool_desired
DesiredSpoolState AP_Motors::_spool_desired protected
Definition at line 330 of file AP_Motors_Class.h.
Referenced by get_desired_spool_state(), AP_MotorsHeli::output_logic(), AP_MotorsMulticopter::output_logic(), and set_desired_spool_state().
_spool_state
SpoolState AP_Motors::_spool_state protected
Definition at line 331 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli::get_rotor_control_state(), get_spool_state(), AP_MotorsHeli::output_logic(), AP_MotorsMulticopter::output_logic(), AP_MotorsMulticopter::output_min(), AP_Motors6DOF::output_to_motors(), AP_MotorsCoax::output_to_motors(), AP_MotorsHeli_Single::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsTailsitter::output_to_motors(), AP_MotorsTri::output_to_motors(), AP_MotorsMulticopter::output_to_pwm(), and AP_MotorsMulticopter::spool_up_complete().
_spoolup_block
bool AP_Motors::_spoolup_block private
Definition at line 391 of file AP_Motors_Class.h.
Referenced by get_spoolup_block(), and set_spoolup_block().
_throttle_avg_max
float AP_Motors::_throttle_avg_max protected
Definition at line 326 of file AP_Motors_Class.h.
Referenced by AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), and set_throttle_avg_max().
_throttle_filter
LowPassFilterFloat AP_Motors::_throttle_filter protected
Definition at line 327 of file AP_Motors_Class.h.
Referenced by AP_Motors(), get_throttle(), get_throttle_bidirectional(), AP_MotorsHeli::output_disarmed(), AP_MotorsHeli_Dual::servo_test(), AP_MotorsHeli_Single::servo_test(), set_throttle_filter_cutoff(), AP_MotorsHeli::update_throttle_filter(), and AP_MotorsMulticopter::update_throttle_filter().
_throttle_in
float AP_Motors::_throttle_in protected
Definition at line 321 of file AP_Motors_Class.h.
Referenced by set_throttle(), AP_MotorsHeli::update_throttle_filter(), and AP_MotorsMulticopter::update_throttle_filter().
_throttle_out
float AP_Motors::_throttle_out protected
Definition at line 322 of file AP_Motors_Class.h.
Referenced by get_throttle_out(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), and AP_MotorsTri::output_armed_stabilizing().
_throttle_radio_passthrough
float AP_Motors::_throttle_radio_passthrough protected
Definition at line 342 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli::init(), AP_MotorsHeli::output_disarmed(), and set_radio_passthrough().
_throttle_slew
DerivativeFilterFloat_Size7 AP_Motors::_throttle_slew protected
Definition at line 328 of file AP_Motors_Class.h.
Referenced by AP_Motors(), and AP_MotorsMulticopter::update_throttle_filter().
_throttle_slew_filter
LowPassFilterFloat AP_Motors::_throttle_slew_filter protected
Definition at line 329 of file AP_Motors_Class.h.
Referenced by AP_Motors(), set_slew_filter_cutoff(), and AP_MotorsMulticopter::update_throttle_filter().
_throttle_slew_rate
float AP_Motors::_throttle_slew_rate protected
Definition at line 323 of file AP_Motors_Class.h.
Referenced by get_throttle_slew_rate(), and AP_MotorsMulticopter::update_throttle_filter().
_thrust_balanced
bool AP_Motors::_thrust_balanced protected
Definition at line 349 of file AP_Motors_Class.h.
Referenced by AP_Motors(), AP_MotorsMatrix::check_for_failed_motor(), and AP_MotorsMulticopter::output_logic().
_thrust_boost
bool AP_Motors::_thrust_boost protected
Definition at line 348 of file AP_Motors_Class.h.
Referenced by AP_Motors(), AP_MotorsMatrix::check_for_failed_motor(), get_thrust_boost(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsMulticopter::output_logic(), and set_thrust_boost().
_thrust_boost_ratio
float AP_Motors::_thrust_boost_ratio protected
Definition at line 350 of file AP_Motors_Class.h.
Referenced by AP_MotorsMatrix::boost_ratio(), and AP_MotorsMulticopter::output_logic().
_yaw_in
float AP_Motors::_yaw_in protected
Definition at line 319 of file AP_Motors_Class.h.
Referenced by get_yaw(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsHeli::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsHeli::output_disarmed(), AP_MotorsHeli_Single::servo_test(), and set_yaw().
_yaw_in_ff
float AP_Motors::_yaw_in_ff protected
Definition at line 320 of file AP_Motors_Class.h.
Referenced by get_yaw_ff(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsMulticopter::output_rpyt(), and set_yaw_ff().
_yaw_radio_passthrough
float AP_Motors::_yaw_radio_passthrough protected
Definition at line 343 of file AP_Motors_Class.h.
Referenced by AP_MotorsHeli::output_disarmed(), and set_radio_passthrough().
limit
struct AP_Motors::AP_Motors_limit AP_Motors::limit
Referenced by AP_Motors(), AC_PosControl::get_throttle_with_vibration_override(), AP_MotorsHeli_Dual::move_actuators(), AP_MotorsHeli_Quad::move_actuators(), AP_MotorsHeli_Single::move_actuators(), AP_MotorsHeli_Single::move_yaw(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_MotorsMulticopter::output_logic(), AP_Motors6DOF::output_min(), AP_MotorsHeli::output_min(), AP_MotorsHeli_Single::output_to_ddfp_tail(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Multi::rate_controller_run(), AC_AttitudeControl_Sub::rate_controller_run(), AC_AttitudeControl_Heli::rate_target_to_motor_yaw(), set_limit_flag_pitch_roll_yaw(), stability_test(), AP_MotorsMulticopter::update_external_limits(), and AC_PosControl::update_z_controller().
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_Motors_Class.h
libraries/AP_Motors/AP_Motors_Class.cpp