APM:Libraries: SITL::SingleCopter Class Reference
SITL::SingleCopter Class Reference
#include <SIM_SingleCopter.h>
Public Member Functions
SingleCopter (const char *frame_str)
void update (const struct sitl_input &input) override
Static Public Member Functions
static Aircraft * create (const char *frame_str)
Private Types
enum { FRAME_SINGLE , FRAME_COAX }
Private Attributes
float terminal_rotation_rate = 4*radians(360.0f)
float hover_throttle = 0.65f
float terminal_velocity = 40
float rotor_rot_accel = radians(20) * AP_MOTORS_MATRIX_YAW_FACTOR_CW
float roll_rate_max = radians(700)
float pitch_rate_max = radians(700)
float yaw_rate_max = radians(700)
float thrust_scale
enum SITL::SingleCopter:: { ... } frame_type
Detailed Description
Definition at line 29 of file SIM_SingleCopter.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
FRAME_SINGLE
FRAME_COAX
Definition at line 51 of file SIM_SingleCopter.h.
Constructor & Destructor Documentation
SingleCopter()
SingleCopter::SingleCopter (const char * frame_str)
Definition at line 25 of file SIM_SingleCopter.cpp.
Referenced by create().
Member Function Documentation
create()
static Aircraft * SITL::SingleCopter::create (const char * frame_str) inline static
Definition at line 37 of file SIM_SingleCopter.h.
update()
void SingleCopter::update (const struct sitl_input & input) override
Definition at line 48 of file SIM_SingleCopter.cpp.
Member Data Documentation
[]
enum { ... } SITL::SingleCopter::frame_type
Referenced by SingleCopter(), and update().
hover_throttle
float SITL::SingleCopter::hover_throttle = 0.65f private
Definition at line 43 of file SIM_SingleCopter.h.
Referenced by SingleCopter().
pitch_rate_max
float SITL::SingleCopter::pitch_rate_max = radians(700) private
Definition at line 47 of file SIM_SingleCopter.h.
Referenced by update().
roll_rate_max
float SITL::SingleCopter::roll_rate_max = radians(700) private
Definition at line 46 of file SIM_SingleCopter.h.
Referenced by update().
rotor_rot_accel
float SITL::SingleCopter::rotor_rot_accel = radians(20) * AP_MOTORS_MATRIX_YAW_FACTOR_CW private
Definition at line 45 of file SIM_SingleCopter.h.
Referenced by update().
terminal_rotation_rate
float SITL::SingleCopter::terminal_rotation_rate = 4*radians(360.0f) private
Definition at line 42 of file SIM_SingleCopter.h.
Referenced by update().
terminal_velocity
float SITL::SingleCopter::terminal_velocity = 40 private
Definition at line 44 of file SIM_SingleCopter.h.
Referenced by update().
thrust_scale
float SITL::SingleCopter::thrust_scale private
Definition at line 49 of file SIM_SingleCopter.h.
Referenced by SingleCopter(), and update().
yaw_rate_max
float SITL::SingleCopter::yaw_rate_max = radians(700) private
Definition at line 48 of file SIM_SingleCopter.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_SingleCopter.h
libraries/SITL/SIM_SingleCopter.cpp