APM:Libraries: AP_HAL::WSPIDevice Class Reference
AP_HAL::WSPIDevice Class Reference abstract
#include <WSPIDevice.h>
Public Member Functions
WSPIDevice ()
virtual bool transfer (const uint8_t *send, uint32_t send_len, uint8_t *recv, uint32_t recv_len) override=0
virtual void set_cmd_header (const CommandHeader &cmd_hdr) override=0
virtual bool is_busy ()=0
virtual AP_HAL::Semaphore * get_semaphore () override=0
Public Member Functions inherited from AP_HAL::Device
FUNCTOR_TYPEDEF (PeriodicCb, void)
FUNCTOR_TYPEDEF (RegisterRWCb, void, uint8_t, uint8_t *, uint32_t, bool)
FUNCTOR_TYPEDEF (BankSelectCb, bool, uint8_t)
Device (enum BusType type)
enum BusType bus_type (void) const
uint8_t bus_num (void) const
uint32_t get_bus_id (void) const
uint8_t get_bus_address (void) const
void set_device_type (uint8_t devtype)
virtual ~Device ()
virtual void set_address (uint8_t address)
virtual bool set_speed (Speed speed)=0
virtual bool enter_xip_mode (void **map_ptr)
virtual bool exit_xip_mode ()
bool read_registers (uint8_t first_reg, uint8_t *recv, uint32_t recv_len)
bool write_register (uint8_t reg, uint8_t val, bool checked=false)
virtual void set_register_rw_callback (RegisterRWCb register_rw_callback)
bool transfer_bank (uint8_t bank, const uint8_t *send, uint32_t send_len, uint8_t *recv, uint32_t recv_len)
bool read_bank_registers (uint8_t bank, uint8_t first_reg, uint8_t *recv, uint32_t recv_len)
bool write_bank_register (uint8_t bank, uint8_t reg, uint8_t val, bool checked=false)
void set_checked_register (uint8_t bank, uint8_t reg, uint8_t val)
void set_checked_register (uint8_t reg, uint8_t val)
bool setup_checked_registers (uint8_t num_regs, uint8_t frequency=10)
bool check_next_register (void)
bool check_next_register (struct checkreg &fail)
bool read (uint8_t *recv, uint32_t recv_len)
virtual PeriodicHandle register_periodic_callback (uint32_t period_usec, PeriodicCb)=0
virtual bool adjust_periodic_callback (PeriodicHandle h, uint32_t period_usec)=0
virtual bool unregister_callback (PeriodicHandle h)
virtual void setup_bankselect_callback (BankSelectCb bank_select)
virtual void deregister_bankselect_callback ()
virtual void register_completion_callback (AP_HAL::MemberProc proc)
virtual void register_completion_callback (AP_HAL::Proc proc)
virtual bool set_chip_select (bool set)
void set_read_flag (uint8_t flag)
uint32_t get_bus_id_devtype (uint8_t devtype) const
virtual void set_retries (uint8_t retries)
Protected Attributes
uint32_t _trx_flags
Protected Attributes inherited from AP_HAL::Device
uint8_t _read_flag = 0
union DeviceId _bus_id
Additional Inherited Members
Public Types inherited from AP_HAL::Device
enum BusType {
BUS_TYPE_UNKNOWN = 0 , BUS_TYPE_I2C = 1 , BUS_TYPE_SPI = 2 , BUS_TYPE_UAVCAN = 3 ,
BUS_TYPE_SITL = 4 , BUS_TYPE_MSP = 5 , BUS_TYPE_SERIAL = 6 , BUS_TYPE_WSPI = 7
}
enum Speed { SPEED_HIGH , SPEED_LOW }
typedef void * PeriodicHandle
typedef void * RegisterRWHandle
Static Public Member Functions inherited from AP_HAL::Device
static uint32_t make_bus_id (enum BusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype)
static uint32_t change_bus_id (uint32_t old_id, uint8_t devtype)
static enum BusType devid_get_bus_type (uint32_t dev_id)
static uint8_t devid_get_bus (uint32_t dev_id)
static uint8_t devid_get_address (uint32_t dev_id)
static uint8_t devid_get_devtype (uint32_t dev_id)
Protected Member Functions inherited from AP_HAL::Device
void set_device_address (uint8_t address)
void set_device_bus (uint8_t bus)
Detailed Description
Definition at line 136 of file WSPIDevice.h.
Constructor & Destructor Documentation
WSPIDevice()
AP_HAL::WSPIDevice::WSPIDevice () inline
Definition at line 140 of file WSPIDevice.h.
Member Function Documentation
get_semaphore()
virtual AP_HAL::Semaphore * AP_HAL::WSPIDevice::get_semaphore () override pure virtual
Implements AP_HAL::Device.
Implemented in Empty::WSPIDevice.
Referenced by AP_FlashIface_JEDEC::reset_device().
is_busy()
virtual bool AP_HAL::WSPIDevice::is_busy () pure virtual
Referenced by AP_FlashIface_JEDEC::is_device_busy().
set_cmd_header()
virtual void AP_HAL::WSPIDevice::set_cmd_header (const CommandHeader & cmd_hdr) override pure virtual
Reimplemented from AP_HAL::Device.
Implemented in Empty::WSPIDevice.
Referenced by AP_FlashIface_JEDEC::configure_device(), AP_FlashIface_JEDEC::detect_device(), AP_FlashIface_JEDEC::read(), AP_FlashIface_JEDEC::read_reg(), AP_FlashIface_JEDEC::reset_device(), AP_FlashIface_JEDEC::send_cmd(), AP_FlashIface_JEDEC::start_erase_offset(), AP_FlashIface_JEDEC::start_mass_erase(), AP_FlashIface_JEDEC::start_program_offset(), AP_FlashIface_JEDEC::start_xip_mode(), and AP_FlashIface_JEDEC::write_reg().
transfer()
virtual bool AP_HAL::WSPIDevice::transfer (const uint8_t * send, uint32_t send_len, uint8_t * recv, uint32_t recv_len) override pure virtual
Implements AP_HAL::Device.
Implemented in Empty::WSPIDevice.
Referenced by AP_FlashIface_JEDEC::configure_device(), AP_FlashIface_JEDEC::detect_device(), AP_FlashIface_JEDEC::read(), AP_FlashIface_JEDEC::read_reg(), AP_FlashIface_JEDEC::reset_device(), AP_FlashIface_JEDEC::send_cmd(), AP_FlashIface_JEDEC::start_erase_offset(), AP_FlashIface_JEDEC::start_mass_erase(), AP_FlashIface_JEDEC::start_program_offset(), and AP_FlashIface_JEDEC::write_reg().
Member Data Documentation
_trx_flags
uint32_t AP_HAL::WSPIDevice::_trx_flags protected
Definition at line 154 of file WSPIDevice.h.
The documentation for this class was generated from the following file:
libraries/AP_HAL/WSPIDevice.h