APM:Libraries: AP_Spektrum_Telem Class Reference
AP_Spektrum_Telem Class Reference
#include <AP_Spektrum_Telem.h>
Classes
struct MessageChunk
Public Member Functions
AP_Spektrum_Telem ()
~AP_Spektrum_Telem () override
CLASS_NO_COPY (AP_Spektrum_Telem)
virtual bool init () override
Public Member Functions inherited from AP_RCTelemetry
AP_RCTelemetry (uint8_t time_slots)
virtual ~AP_RCTelemetry ()
CLASS_NO_COPY (AP_RCTelemetry)
virtual void queue_message (MAV_SEVERITY severity, const char *text)
void enable_scheduler_entry (const uint8_t slot)
void disable_scheduler_entry (const uint8_t slot)
void set_scheduler_entry_min_period (const uint8_t slot, const uint32_t min_period_ms)
bool is_scheduler_entry_enabled (const uint8_t slot) const
virtual void reset_scheduler_entry_min_periods ()
uint32_t sensor_status_flags () const
uint16_t get_avg_packet_rate () const
uint16_t get_max_packet_rate () const
Static Public Member Functions
static AP_Spektrum_Telem * get_singleton (void)
static bool get_telem_data (uint8_t *data)
Private Types
enum SensorType {
QOS , RPM , TEXT , ATTITUDE ,
GPS_LOC , ESC , ALTITUDE , AIRSPEED ,
GPS_STATUS , VOLTAGE , AMPS , MAH ,
TEMP , NUM_SENSORS
}
Private Member Functions
bool get_next_msg_chunk (void) override
bool repeat_msg_chunk (void)
void send_msg_chunk (const MessageChunk &message)
bool is_packet_ready (uint8_t idx, bool queue_empty) override
void process_packet (uint8_t idx) override
void adjust_packet_weight (bool queue_empty) override
void calc_qos ()
void calc_batt_volts (uint8_t instance)
void calc_temperature (uint8_t instance)
void calc_batt_amps (uint8_t instance)
void calc_batt_mah ()
void calc_altitude ()
void calc_airspeed ()
void calc_attandmag ()
void calc_gps_location ()
void calc_gps_status ()
void calc_esc ()
void calc_rpm ()
void setup_wfq_scheduler (void) override
bool _get_telem_data (uint8_t *data)
Private Attributes
struct AP_Spektrum_Telem::MessageChunk _msg_chunk
float _max_speed = 0.0f
float _max_alt = 0.0f
PACKED UN_TELEMETRY _telem
bool _telem_pending
Static Private Attributes
static AP_Spektrum_Telem * singleton
Additional Inherited Members
Protected Member Functions inherited from AP_RCTelemetry
uint8_t run_wfq_scheduler (const bool use_shaper=true)
bool process_scheduler_entry (const uint8_t slot)
void set_scheduler_entry (uint8_t slot, uint32_t weight, uint32_t min_period_ms)
void add_scheduler_entry (uint32_t weight, uint32_t min_period_ms)
Protected Attributes inherited from AP_RCTelemetry
uint8_t _time_slots
struct {
uint32_t last_poll_timer
uint32_t avg_packet_counter
uint32_t packet_timer [TELEM_TIME_SLOT_MAX]
uint32_t packet_weight [TELEM_TIME_SLOT_MAX]
uint32_t packet_min_period [TELEM_TIME_SLOT_MAX]
uint16_t avg_packet_rate
uint16_t max_packet_rate
} _scheduler
struct {
HAL_Semaphore sem
ObjectBuffer< mavlink_statustext_t > queue {TELEM_PAYLOAD_STATUS_CAPACITY}
mavlink_statustext_t next
bool available
} _statustext
Detailed Description
Definition at line 42 of file AP_Spektrum_Telem.h.
Member Enumeration Documentation
SensorType
enum AP_Spektrum_Telem::SensorType private
Enumerator
QOS
RPM
TEXT
ATTITUDE
GPS_LOC
ESC
ALTITUDE
AIRSPEED
GPS_STATUS
VOLTAGE
AMPS
MAH
TEMP
NUM_SENSORS
Definition at line 62 of file AP_Spektrum_Telem.h.
Constructor & Destructor Documentation
AP_Spektrum_Telem()
AP_Spektrum_Telem::AP_Spektrum_Telem ()
Definition at line 57 of file AP_Spektrum_Telem.cpp.
Referenced by get_telem_data().
~AP_Spektrum_Telem()
AP_Spektrum_Telem::~AP_Spektrum_Telem (void) override
Definition at line 62 of file AP_Spektrum_Telem.cpp.
Member Function Documentation
_get_telem_data()
bool AP_Spektrum_Telem::_get_telem_data (uint8_t * data) private
Definition at line 613 of file AP_Spektrum_Telem.cpp.
Referenced by get_telem_data().
adjust_packet_weight()
void AP_Spektrum_Telem::adjust_packet_weight (bool queue_empty) override private virtual
Reimplemented from AP_RCTelemetry.
Definition at line 101 of file AP_Spektrum_Telem.cpp.
calc_airspeed()
void AP_Spektrum_Telem::calc_airspeed () private
Definition at line 446 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
calc_altitude()
void AP_Spektrum_Telem::calc_altitude () private
Definition at line 428 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
calc_attandmag()
void AP_Spektrum_Telem::calc_attandmag (void) private
Definition at line 473 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
calc_batt_amps()
void AP_Spektrum_Telem::calc_batt_amps (uint8_t instance) private
Definition at line 347 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
calc_batt_mah()
void AP_Spektrum_Telem::calc_batt_mah () private
Definition at line 366 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
calc_batt_volts()
void AP_Spektrum_Telem::calc_batt_volts (uint8_t instance) private
Definition at line 333 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
calc_esc()
void AP_Spektrum_Telem::calc_esc () private
Definition at line 580 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
calc_gps_location()
void AP_Spektrum_Telem::calc_gps_location () private
Definition at line 498 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
calc_gps_status()
void AP_Spektrum_Telem::calc_gps_status () private
Definition at line 551 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
calc_qos()
void AP_Spektrum_Telem::calc_qos () private
Definition at line 282 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
calc_rpm()
void AP_Spektrum_Telem::calc_rpm () private
Definition at line 297 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
calc_temperature()
void AP_Spektrum_Telem::calc_temperature (uint8_t instance) private
Definition at line 419 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
CLASS_NO_COPY()
AP_Spektrum_Telem::CLASS_NO_COPY (AP_Spektrum_Telem)
get_next_msg_chunk()
bool AP_Spektrum_Telem::get_next_msg_chunk (void) override private virtual
Reimplemented from AP_RCTelemetry.
Definition at line 203 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
get_singleton()
static AP_Spektrum_Telem * AP_Spektrum_Telem::get_singleton (void) inline static
Definition at line 53 of file AP_Spektrum_Telem.h.
Referenced by AP::spektrum_telem().
get_telem_data()
bool AP_Spektrum_Telem::get_telem_data (uint8_t * data) static
Definition at line 628 of file AP_Spektrum_Telem.cpp.
Referenced by srxlFillTelemetry().
init()
bool AP_Spektrum_Telem::init (void) override virtual
Reimplemented from AP_RCTelemetry.
Definition at line 67 of file AP_Spektrum_Telem.cpp.
Referenced by get_telem_data().
is_packet_ready()
bool AP_Spektrum_Telem::is_packet_ready (uint8_t idx, bool queue_empty) override private virtual
Reimplemented from AP_RCTelemetry.
Definition at line 111 of file AP_Spektrum_Telem.cpp.
process_packet()
void AP_Spektrum_Telem::process_packet (uint8_t idx) override private virtual
Implements AP_RCTelemetry.
Definition at line 127 of file AP_Spektrum_Telem.cpp.
repeat_msg_chunk()
bool AP_Spektrum_Telem::repeat_msg_chunk (void) private
Definition at line 178 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
send_msg_chunk()
void AP_Spektrum_Telem::send_msg_chunk (const MessageChunk & message) private
Definition at line 323 of file AP_Spektrum_Telem.cpp.
Referenced by process_packet().
setup_wfq_scheduler()
void AP_Spektrum_Telem::setup_wfq_scheduler (void) override private virtual
Implements AP_RCTelemetry.
Definition at line 79 of file AP_Spektrum_Telem.cpp.
Member Data Documentation
_max_alt
float AP_Spektrum_Telem::_max_alt = 0.0f private
Definition at line 88 of file AP_Spektrum_Telem.h.
Referenced by calc_altitude().
_max_speed
float AP_Spektrum_Telem::_max_speed = 0.0f private
Definition at line 87 of file AP_Spektrum_Telem.h.
Referenced by calc_airspeed().
_msg_chunk
struct AP_Spektrum_Telem::MessageChunk AP_Spektrum_Telem::_msg_chunk private
Referenced by get_next_msg_chunk(), process_packet(), and repeat_msg_chunk().
_telem
PACKED UN_TELEMETRY AP_Spektrum_Telem::_telem private
Definition at line 130 of file AP_Spektrum_Telem.h.
Referenced by _get_telem_data(), calc_airspeed(), calc_altitude(), calc_attandmag(), calc_batt_amps(), calc_batt_mah(), calc_batt_volts(), calc_esc(), calc_gps_location(), calc_gps_status(), calc_qos(), calc_rpm(), calc_temperature(), and send_msg_chunk().
_telem_pending
bool AP_Spektrum_Telem::_telem_pending private
Definition at line 131 of file AP_Spektrum_Telem.h.
Referenced by _get_telem_data(), calc_airspeed(), calc_altitude(), calc_attandmag(), calc_batt_amps(), calc_batt_mah(), calc_batt_volts(), calc_esc(), calc_gps_location(), calc_gps_status(), calc_qos(), calc_rpm(), calc_temperature(), and send_msg_chunk().
singleton
AP_Spektrum_Telem * AP_Spektrum_Telem::singleton static private
Definition at line 133 of file AP_Spektrum_Telem.h.
Referenced by AP_Spektrum_Telem(), get_singleton(), get_telem_data(), and ~AP_Spektrum_Telem().
The documentation for this class was generated from the following files:
libraries/AP_RCTelemetry/AP_Spektrum_Telem.h
libraries/AP_RCTelemetry/AP_Spektrum_Telem.cpp