APM:Libraries: SITL::EFI_MegaSquirt Class Reference
SITL::EFI_MegaSquirt Class Reference
#include <SIM_EFI_MegaSquirt.h>
Classes
struct PACKED
Public Member Functions
void update ()
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
Public Member Functions inherited from SITL::SerialDevice
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Private Member Functions
void send_table ()
Private Attributes
struct SITL::EFI_MegaSquirt::PACKED r_command
uint8_t * buf = (uint8_t *)&r_command
uint8_t ofs
struct SITL::EFI_MegaSquirt::PACKED table7
float tps
Additional Inherited Members
Protected Member Functions inherited from SITL::SerialDevice
bool init_sitl_pointer () WARN_IF_UNUSED
Protected Attributes inherited from SITL::SerialDevice
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Detailed Description
Definition at line 37 of file SIM_EFI_MegaSquirt.h.
Member Function Documentation
send_table()
void EFI_MegaSquirt::send_table (void) private
Definition at line 119 of file SIM_EFI_MegaSquirt.cpp.
Referenced by update().
SerialDevice()
SerialDevice::SerialDevice (uint16_t tx_bufsize = 512, uint16_t rx_bufsize = 512)
Definition at line 29 of file SIM_SerialDevice.cpp.
update()
void EFI_MegaSquirt::update ()
Definition at line 38 of file SIM_EFI_MegaSquirt.cpp.
Referenced by HALSITL::SITL_State_Common::sim_update().
Member Data Documentation
buf
uint8_t* SITL::EFI_MegaSquirt::buf = (uint8_t *)&r_command private
Definition at line 56 of file SIM_EFI_MegaSquirt.h.
Referenced by update().
ofs
uint8_t SITL::EFI_MegaSquirt::ofs private
Definition at line 57 of file SIM_EFI_MegaSquirt.h.
Referenced by update().
r_command
struct SITL::EFI_MegaSquirt::PACKED SITL::EFI_MegaSquirt::r_command private
Referenced by send_table(), and update().
table7
struct SITL::EFI_MegaSquirt::PACKED SITL::EFI_MegaSquirt::table7 private
Referenced by send_table(), and update().
tps
float SITL::EFI_MegaSquirt::tps private
Definition at line 100 of file SIM_EFI_MegaSquirt.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_EFI_MegaSquirt.h
libraries/SITL/SIM_EFI_MegaSquirt.cpp