APM:Libraries: GCS_MAVLINK Class Reference
GCS_MAVLINK Class Reference abstract
MAVLink transport control class.
#include <GCS.h>
Classes
struct deferred_message_bucket_t
struct deferred_message_t
struct ftp_state
struct LastRadioStatus
struct pending_ftp
struct pending_param_reply
struct pending_param_request
struct stream_entries
Public Types
enum streams : uint8_t {
STREAM_RAW_SENSORS , STREAM_EXTENDED_STATUS , STREAM_RC_CHANNELS , STREAM_RAW_CONTROLLER ,
STREAM_POSITION , STREAM_EXTRA1 , STREAM_EXTRA2 , STREAM_EXTRA3 ,
STREAM_PARAMS , STREAM_ADSB , NUM_STREAMS
}
Public Member Functions
GCS_MAVLINK (GCS_MAVLINK_Parameters &parameters, AP_HAL::UARTDriver &uart)
virtual ~GCS_MAVLINK ()
mavlink_message_t * channel_buffer ()
mavlink_status_t * channel_status ()
void update_receive (uint32_t max_time_us=1000)
void update_send ()
bool init (uint8_t instance)
void send_message (enum ap_message id)
void send_text (MAV_SEVERITY severity, const char *fmt,...) const FMT_PRINTF(3
void void queued_param_send ()
Send the next pending parameter, called from deferred message handling code.
void queued_mission_request_send ()
bool sending_mavlink1 () const
bool requesting_mission_items () const
uint16_t txspace () const
Check for available transmit space.
bool check_payload_size (uint16_t max_payload_len)
void out_of_space_to_send ()
void send_mission_ack (const mavlink_message_t &msg, MAV_MISSION_TYPE mission_type, MAV_MISSION_RESULT result) const
virtual void packetReceived (const mavlink_status_t &status, const mavlink_message_t &msg)
void send_message (uint32_t msgid, const char *pkt)
void send_message (const char *pkt, const mavlink_msg_entry_t *entry)
AP_HAL::UARTDriver * get_uart ()
virtual uint8_t sysid_my_gcs () const =0
virtual bool sysid_enforce () const
void send_parameter_value (const char *param_name, ap_var_type param_type, float param_value)
bool is_high_bandwidth ()
bool have_flow_control ()
bool is_active () const
bool is_streaming () const
mavlink_channel_t get_chan () const
uint32_t get_last_heartbeat_time () const
virtual MISSION_STATE mission_state (const class AP_Mission &mission) const
void send_mission_current (const class AP_Mission &mission, uint16_t seq)
void send_heartbeat (void) const
void send_meminfo (void)
void send_fence_status () const
void send_power_status (void)
void send_battery_status (const uint8_t instance) const
bool send_battery_status ()
void send_distance_sensor ()
void send_proximity ()
virtual void send_nav_controller_output () const =0
virtual void send_pid_tuning ()=0
void send_ahrs2 ()
void send_system_time () const
void send_rc_channels () const
void send_rc_channels_raw () const
void send_raw_imu ()
void send_scaled_pressure_instance (uint8_t instance, void(*send_fn)(mavlink_channel_t chan, uint32_t time_boot_ms, float press_abs, float press_diff, int16_t temperature, int16_t temperature_press_diff))
void send_scaled_pressure ()
void send_scaled_pressure2 ()
virtual void send_scaled_pressure3 ()
void send_simstate () const
void send_sim_state () const
void send_ahrs ()
void send_battery2 ()
void send_opticalflow ()
virtual void send_attitude () const
virtual void send_attitude_quaternion () const
void send_autopilot_version () const
void send_extended_sys_state () const
void send_local_position () const
void send_vfr_hud ()
void send_vibration () const
void send_gimbal_device_attitude_status () const
void send_gimbal_manager_information () const
void send_gimbal_manager_status () const
void send_named_float (const char *name, float value) const
void send_home_position () const
void send_gps_global_origin () const
virtual void send_attitude_target ()
virtual void send_position_target_global_int ()
virtual void send_position_target_local_ned ()
void send_servo_output_raw ()
void send_accelcal_vehicle_position (uint32_t position)
void send_scaled_imu (uint8_t instance, void(*send_fn)(mavlink_channel_t chan, uint32_t time_ms, int16_t xacc, int16_t yacc, int16_t zacc, int16_t xgyro, int16_t ygyro, int16_t zgyro, int16_t xmag, int16_t ymag, int16_t zmag, int16_t temperature))
void send_sys_status ()
void send_set_position_target_global_int (uint8_t target_system, uint8_t target_component, const Location &loc)
void send_rpm () const
void send_generator_status () const
void send_water_depth () const
int8_t battery_remaining_pct (const uint8_t instance) const
void send_high_latency2 () const
void send_uavionix_adsb_out_status () const
void send_autopilot_state_for_gimbal_device () const
void lock (bool _lock)
bool locked () const
bool is_private (void) const
FUNCTOR_TYPEDEF (protocol_handler_fn_t, bool, uint8_t, AP_HAL::UARTDriver *)
virtual uint64_t capabilities () const
uint16_t get_stream_slowdown_ms () const
uint8_t get_last_txbuf () const
MAV_RESULT set_message_interval (uint32_t msg_id, int32_t interval_us)
Static Public Member Functions
static uint32_t last_radio_status_remrssi_ms ()
static float telemetry_radio_rssi ()
static uint8_t active_channel_mask (void)
static uint8_t streaming_channel_mask (void)
static uint8_t private_channel_mask (void)
static void set_channel_private (mavlink_channel_t chan)
static bool is_private (mavlink_channel_t _chan)
static void send_to_components (uint32_t msgid, const char *pkt, uint8_t pkt_len)
static void disable_channel_routing (mavlink_channel_t chan)
static bool find_by_mavtype (uint8_t mav_type, uint8_t &sysid, uint8_t &compid, mavlink_channel_t &channel)
static bool find_by_mavtype_and_compid (uint8_t mav_type, uint8_t compid, uint8_t &sysid, mavlink_channel_t &channel)
static GCS_MAVLINK * find_by_mavtype_and_compid (uint8_t mav_type, uint8_t compid, uint8_t &sysid)
static void update_signing_timestamp (uint64_t timestamp_usec)
static uint8_t packet_overhead_chan (mavlink_channel_t chan)
Public Attributes
uint32_t last_heartbeat_time
uint16_t mission_item_reached_index = AP_MISSION_CMD_INDEX_NONE
bool is_high_latency_link
Static Public Attributes
static const struct stream_entries all_stream_entries []
Protected Member Functions
bool mavlink_coordinate_frame_to_location_alt_frame (MAV_FRAME coordinate_frame, Location::AltFrame &frame)
bool accept_packet (const mavlink_status_t &status, const mavlink_message_t &msg) const
void set_ekf_origin (const Location &loc)
virtual MAV_MODE base_mode () const =0
MAV_STATE system_status () const
virtual MAV_STATE vehicle_system_status () const =0
virtual MAV_VTOL_STATE vtol_state () const
virtual MAV_LANDED_STATE landed_state () const
uint8_t packet_overhead (void) const
void handle_heartbeat (const mavlink_message_t &msg) const
virtual bool persist_streamrates () const
void handle_request_data_stream (const mavlink_message_t &msg)
virtual void handle_command_ack (const mavlink_message_t &msg)
void handle_set_mode (const mavlink_message_t &msg)
void handle_command_int (const mavlink_message_t &msg)
MAV_RESULT handle_command_do_set_home (const mavlink_command_int_t &packet)
virtual MAV_RESULT handle_command_int_packet (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
MAV_RESULT handle_command_int_external_position_estimate (const mavlink_command_int_t &packet)
virtual bool set_home_to_current_location (bool lock)=0
virtual bool set_home (const Location &loc, bool lock)=0
MAV_RESULT handle_command_do_aux_function (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_storage_format (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
void handle_mission_request_list (const mavlink_message_t &msg)
void handle_mission_request_int (const mavlink_message_t &msg)
void handle_mission_clear_all (const mavlink_message_t &msg)
void handle_mission_count (const mavlink_message_t &msg)
void handle_mission_write_partial_list (const mavlink_message_t &msg)
void handle_mission_item (const mavlink_message_t &msg)
void handle_distance_sensor (const mavlink_message_t &msg)
void handle_obstacle_distance (const mavlink_message_t &msg)
void handle_obstacle_distance_3d (const mavlink_message_t &msg)
void handle_adsb_message (const mavlink_message_t &msg)
void handle_osd_param_config (const mavlink_message_t &msg) const
void handle_common_param_message (const mavlink_message_t &msg)
void handle_param_set (const mavlink_message_t &msg)
void handle_param_request_list (const mavlink_message_t &msg)
void handle_param_request_read (const mavlink_message_t &msg)
virtual bool params_ready () const
void handle_rc_channels_override (const mavlink_message_t &msg)
void handle_system_time_message (const mavlink_message_t &msg)
void handle_common_rally_message (const mavlink_message_t &msg)
void handle_rally_fetch_point (const mavlink_message_t &msg)
void handle_rally_point (const mavlink_message_t &msg) const
void handle_fence_message (const mavlink_message_t &msg)
void handle_param_value (const mavlink_message_t &msg)
void handle_radio_status (const mavlink_message_t &msg)
void handle_serial_control (const mavlink_message_t &msg)
void handle_vision_position_delta (const mavlink_message_t &msg)
virtual void handle_message (const mavlink_message_t &msg)
void handle_set_gps_global_origin (const mavlink_message_t &msg)
void handle_setup_signing (const mavlink_message_t &msg) const
virtual MAV_RESULT handle_preflight_reboot (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
void deadlock_sem (void)
MAV_RESULT handle_do_set_safety_switch_state (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
MAV_RESULT handle_command_set_message_interval (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_get_message_interval (const mavlink_command_int_t &packet)
bool get_ap_message_interval (ap_message id, uint16_t &interval_ms) const
MAV_RESULT handle_command_request_message (const mavlink_command_int_t &packet)
MAV_RESULT handle_START_RX_PAIR (const mavlink_command_int_t &packet)
virtual MAV_RESULT handle_flight_termination (const mavlink_command_int_t &packet)
void handle_send_autopilot_version (const mavlink_message_t &msg)
MAV_RESULT handle_command_request_autopilot_capabilities (const mavlink_command_int_t &packet)
virtual void send_banner ()
void send_received_message_deprecation_warning (const char *message)
void handle_device_op_read (const mavlink_message_t &msg)
void handle_device_op_write (const mavlink_message_t &msg)
void send_timesync ()
uint64_t timesync_receive_timestamp_ns () const
uint64_t timesync_timestamp_ns () const
void handle_timesync (const mavlink_message_t &msg)
void handle_statustext (const mavlink_message_t &msg) const
void handle_named_value (const mavlink_message_t &msg) const
bool telemetry_delayed () const
virtual uint32_t telem_delay () const =0
MAV_RESULT handle_command_run_prearm_checks (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_flash_bootloader (const mavlink_command_int_t &packet)
virtual MAV_RESULT handle_command_preflight_calibration (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
virtual MAV_RESULT _handle_command_preflight_calibration (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
virtual MAV_RESULT _handle_command_preflight_calibration_baro (const mavlink_message_t &msg)
MAV_RESULT handle_command_battery_reset (const mavlink_command_int_t &packet)
void handle_command_long (const mavlink_message_t &msg)
MAV_RESULT handle_command_accelcal_vehicle_pos (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_mag_cal (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_fixed_mag_cal_yaw (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_camera (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_set_roi (const mavlink_command_int_t &packet)
virtual MAV_RESULT handle_command_do_set_roi (const Location &roi_loc)
MAV_RESULT handle_command_do_gripper (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_sprayer (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_set_mode (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_get_home_position (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_fence_enable (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_debug_trap (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_set_ekf_source_set (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_airframe_configuration (const mavlink_command_int_t &packet)
void can_frame_callback (uint8_t bus, const AP_HAL::CANFrame &)
void handle_can_frame (const mavlink_message_t &msg) const
void handle_optical_flow (const mavlink_message_t &msg)
void handle_manual_control (const mavlink_message_t &msg)
virtual void handle_landing_target (const mavlink_landing_target_t &packet, uint32_t timestamp_ms)
virtual bool try_send_message (enum ap_message id)
virtual void send_global_position_int ()
bool try_send_mission_message (enum ap_message id)
void send_hwstatus ()
void handle_data_packet (const mavlink_message_t &msg)
virtual int32_t global_position_int_alt () const
virtual int32_t global_position_int_relative_alt () const
virtual float vfr_hud_climbrate () const
virtual float vfr_hud_airspeed () const
virtual int16_t vfr_hud_throttle () const
virtual float vfr_hud_alt () const
virtual int16_t high_latency_target_altitude () const
virtual uint8_t high_latency_tgt_heading () const
virtual uint16_t high_latency_tgt_dist () const
virtual uint8_t high_latency_tgt_airspeed () const
virtual uint8_t high_latency_wind_speed () const
virtual uint8_t high_latency_wind_direction () const
int8_t high_latency_air_temperature () const
MAV_RESULT handle_control_high_latency (const mavlink_command_int_t &packet)
void manual_override (class RC_Channel *c, int16_t value_in, uint16_t offset, float scaler, const uint32_t tnow, bool reversed=false)
uint8_t receiver_rssi () const
uint32_t correct_offboard_timestamp_usec_to_ms (uint64_t offboard_usec, uint16_t payload_size)
virtual void convert_COMMAND_LONG_to_COMMAND_INT (const mavlink_command_long_t &in, mavlink_command_int_t &out, MAV_FRAME frame=MAV_FRAME_GLOBAL_RELATIVE_ALT)
virtual bool mav_frame_for_command_long (MAV_FRAME &fame, MAV_CMD packet_command) const
MAV_RESULT try_command_long_as_command_int (const mavlink_command_long_t &packet, const mavlink_message_t &msg)
bool location_from_command_t (const mavlink_command_int_t &in, Location &out)
Static Protected Member Functions
static MAV_PARAM_TYPE mav_param_type (enum ap_var_type t)
Protected Attributes
AP_Param * _queued_parameter
next parameter to
mavlink_channel_t chan
AP_Int16 * streamRates
struct {
HAL_Semaphore sem
bool taken
} _deadlock_sem
struct {
int64_t sent_ts1
uint32_t last_sent_ms
const uint16_t interval_ms = 10000
} _timesync_request
Static Protected Attributes
static constexpr const float magic_force_arm_value = 2989.0f
static constexpr const float magic_force_disarm_value = 21196.0f
Private Types
enum class Flags {
USING_SIGNING = (1<<0) , ACTIVE = (1<<1) , STREAMING = (1<<2) , PRIVATE = (1<<3) ,
LOCKED = (1<<4)
}
enum class FTP_OP : uint8_t {
None = 0 , TerminateSession = 1 , ResetSessions = 2 , ListDirectory = 3 ,
OpenFileRO = 4 , ReadFile = 5 , CreateFile = 6 , WriteFile = 7 ,
RemoveFile = 8 , CreateDirectory = 9 , RemoveDirectory = 10 , OpenFileWO = 11 ,
TruncateFile = 12 , Rename = 13 , CalcFileCRC32 = 14 , BurstReadFile = 15 ,
Ack = 128 , Nack = 129
}
enum class FTP_ERROR : uint8_t {
None = 0 , Fail = 1 , FailErrno = 2 , InvalidDataSize = 3 ,
InvalidSession = 4 , NoSessionsAvailable = 5 , EndOfFile = 6 , UnknownCommand = 7 ,
FileExists = 8 , FileProtected = 9 , FileNotFound = 10
}
enum class FTP_FILE_MODE { Read , Write }
Private Member Functions
void log_mavlink_stats ()
MAV_RESULT _set_mode_common (const MAV_MODE base_mode, const uint32_t custom_mode)
void service_statustext (void)
MAV_RESULT handle_servorelay_message (const mavlink_command_int_t &packet)
bool send_relay_status () const
bool calibrate_gyros ()
int8_t get_deferred_message_index (const ap_message id) const
int8_t deferred_message_to_send_index (uint16_t now16_ms)
ap_message next_deferred_bucket_message_to_send (uint16_t now16_ms)
void find_next_bucket_to_send (uint16_t now16_ms)
void remove_message_from_bucket (int8_t bucket, ap_message id)
bool should_send_message_in_delay_callback (const ap_message id) const
bool get_default_interval_for_ap_message (const ap_message id, uint16_t &interval) const
uint16_t get_interval_for_stream (GCS_MAVLINK::streams id) const
bool set_mavlink_message_id_interval (const uint32_t mavlink_id, const uint16_t interval_ms)
ap_message mavlink_id_to_ap_message_id (const uint32_t mavlink_id) const
bool set_ap_message_interval (enum ap_message id, uint16_t interval_ms)
void initialise_message_intervals_for_stream (GCS_MAVLINK::streams id)
void initialise_message_intervals_from_streamrates ()
uint16_t get_reschedule_interval_ms (const deferred_message_bucket_t &deferred) const
bool do_try_send_message (const ap_message id)
void param_io_timer (void)
uint8_t send_parameter_async_replies ()
bool ftp_init (void)
void handle_file_transfer_protocol (const mavlink_message_t &msg)
bool send_ftp_reply (const pending_ftp &reply)
void ftp_worker (void)
void ftp_push_replies (pending_ftp &reply)
void send_distance_sensor (const class AP_RangeFinder_Backend *sensor, const uint8_t instance) const
virtual bool handle_guided_request (AP_Mission::Mission_Command &cmd)
virtual void handle_change_alt_request (AP_Mission::Mission_Command &cmd)
void handle_common_mission_message (const mavlink_message_t &msg)
virtual void handle_manual_control_axes (const mavlink_manual_control_t &packet, const uint32_t tnow)
void handle_vicon_position_estimate (const mavlink_message_t &msg)
void handle_vision_position_estimate (const mavlink_message_t &msg)
void handle_global_vision_position_estimate (const mavlink_message_t &msg)
void handle_att_pos_mocap (const mavlink_message_t &msg)
void handle_odometry (const mavlink_message_t &msg)
void handle_common_vision_position_estimate_data (const uint64_t usec, const float x, const float y, const float z, const float roll, const float pitch, const float yaw, const float covariance[21], const uint8_t reset_counter, const uint16_t payload_size)
void handle_vision_speed_estimate (const mavlink_message_t &msg)
void handle_landing_target (const mavlink_message_t &msg)
void lock_channel (const mavlink_channel_t chan, bool lock)
void load_signing_key (void)
bool signing_enabled (void) const
Static Private Member Functions
static bool command_long_stores_location (const MAV_CMD command)
static void ftp_error (struct pending_ftp &response, FTP_ERROR error)
static int gen_dir_entry (char *dest, size_t space, const char *path, const struct dirent *entry)
static void ftp_list_dir (struct pending_ftp &request, struct pending_ftp &response)
static bool signing_key_save (const struct SigningKey &key)
static bool signing_key_load (struct SigningKey &key)
static void save_signing_timestamp (bool force_save_now)
Private Attributes
mavlink_message_t _channel_buffer
mavlink_status_t _channel_status
const AP_SerialManager::UARTState * uartstate
uint32_t last_deprecation_warning_send_time_ms
const char * last_deprecation_message
AP_HAL::UARTDriver * _port
The stream we are communicating over.
enum ap_var_type _queued_parameter_type
type of the next
AP_Param::ParamToken _queued_parameter_token
uint16_t _queued_parameter_index
AP_Param token for.
uint16_t _queued_parameter_count
saved count of
uint32_t _queued_parameter_send_time_ms
uint16_t stream_slowdown_ms
uint8_t last_txbuf = 100
struct GCS_MAVLINK::deferred_message_t deferred_message [3]
int8_t next_deferred_message_to_send_cache = -1
deferred_message_bucket_t deferred_message_bucket [10]
uint8_t sending_bucket_id = no_bucket_to_send
Bitmask< MSG_LAST > bucket_message_ids_to_send
Bitmask< MSG_LAST > pushed_ap_message_ids
bool deferred_messages_initialised
mavlink_signing_t signing
struct {
GCS_MAVLINK::protocol_handler_fn_t handler
uint32_t last_mavlink_ms
uint32_t last_alternate_ms
bool active
} alternative
JitterCorrection lag_correction
Location global_position_current_loc
uint8_t last_tx_seq
uint16_t send_packet_count
uint16_t out_of_space_to_send_count
uint32_t last_mavlink_stats_logged
uint8_t last_battery_status_idx
uint8_t proximity_ever_valid_bitmask
bool _locked
Static Private Attributes
static struct GCS_MAVLINK::LastRadioStatus last_radio_status
static const uint8_t no_bucket_to_send = -1
static const ap_message no_message_to_send = (ap_message)-1
static uint32_t reserve_param_space_start_ms
static uint8_t mavlink_active = 0
static uint8_t mavlink_private = 0
static uint8_t chan_is_streaming = 0
static MAVLink_routing routing
static ObjectBuffer< pending_param_request > param_requests
static ObjectBuffer< pending_param_reply > param_replies
static bool param_timer_registered
static struct ftp_state ftp
static mavlink_signing_streams_t signing_streams
static uint32_t last_signing_save_ms
static StorageAccess _signing_storage
Friends
class GCS
Detailed Description
MAVLink transport control class.
Definition at line 189 of file GCS.h.
Member Enumeration Documentation
Flags
enum class GCS_MAVLINK::Flags strong private
Enumerator
USING_SIGNING
ACTIVE
STREAMING
PRIVATE
LOCKED
Definition at line 769 of file GCS.h.
FTP_ERROR
enum class GCS_MAVLINK::FTP_ERROR : uint8_t strong private
Enumerator
None
Fail
FailErrno
InvalidDataSize
InvalidSession
NoSessionsAvailable
EndOfFile
UnknownCommand
FileExists
FileProtected
FileNotFound
Definition at line 966 of file GCS.h.
FTP_FILE_MODE
enum class GCS_MAVLINK::FTP_FILE_MODE strong private
Enumerator
Read
Write
Definition at line 994 of file GCS.h.
FTP_OP
enum class GCS_MAVLINK::FTP_OP : uint8_t strong private
Enumerator
None
TerminateSession
ResetSessions
ListDirectory
OpenFileRO
ReadFile
CreateFile
WriteFile
RemoveFile
CreateDirectory
RemoveDirectory
OpenFileWO
TruncateFile
Rename
CalcFileCRC32
BurstReadFile
Ack
Nack
Definition at line 945 of file GCS.h.
streams
enum GCS_MAVLINK::streams : uint8_t
Enumerator
STREAM_RAW_SENSORS
STREAM_EXTENDED_STATUS
STREAM_RC_CHANNELS
STREAM_RAW_CONTROLLER
STREAM_POSITION
STREAM_EXTRA1
STREAM_EXTRA2
STREAM_EXTRA3
STREAM_PARAMS
STREAM_ADSB
NUM_STREAMS
Definition at line 281 of file GCS.h.
Constructor & Destructor Documentation
GCS_MAVLINK()
GCS_MAVLINK::GCS_MAVLINK (GCS_MAVLINK_Parameters & parameters, AP_HAL::UARTDriver & uart)
Definition at line 126 of file GCS_Common.cpp.
~GCS_MAVLINK()
virtual GCS_MAVLINK::~GCS_MAVLINK () inline virtual
Definition at line 195 of file GCS.h.
Member Function Documentation
_handle_command_preflight_calibration()
MAV_RESULT GCS_MAVLINK::_handle_command_preflight_calibration (const mavlink_command_int_t & packet, const mavlink_message_t & msg) protected virtual
Definition at line 4478 of file GCS_Common.cpp.
Referenced by handle_command_preflight_calibration().
_handle_command_preflight_calibration_baro()
MAV_RESULT GCS_MAVLINK::_handle_command_preflight_calibration_baro (const mavlink_message_t & msg) protected virtual
Definition at line 4455 of file GCS_Common.cpp.
Referenced by _handle_command_preflight_calibration().
_set_mode_common()
MAV_RESULT GCS_MAVLINK::_set_mode_common (const MAV_MODE base_mode, const uint32_t custom_mode) private
Definition at line 2629 of file GCS_Common.cpp.
Referenced by handle_command_do_set_mode(), and handle_set_mode().
accept_packet()
bool GCS_MAVLINK::accept_packet (const mavlink_status_t & status, const mavlink_message_t & msg) const protected
Definition at line 6579 of file GCS_Common.cpp.
Referenced by packetReceived().
active_channel_mask()
static uint8_t GCS_MAVLINK::active_channel_mask (void) inline static
Definition at line 413 of file GCS.h.
Referenced by MAVLink_routing::handle_heartbeat(), is_active(), and GCS::statustext_send_channel_mask().
base_mode()
virtual MAV_MODE GCS_MAVLINK::base_mode () const protected pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by send_heartbeat(), and send_high_latency2().
battery_remaining_pct()
int8_t GCS_MAVLINK::battery_remaining_pct (const uint8_t instance) const
Referenced by send_high_latency2(), and send_sys_status().
calibrate_gyros()
bool GCS_MAVLINK::calibrate_gyros () private
Referenced by _handle_command_preflight_calibration().
can_frame_callback()
void GCS_MAVLINK::can_frame_callback (uint8_t bus, const AP_HAL::CANFrame &) protected
capabilities()
uint64_t GCS_MAVLINK::capabilities () const virtual
Definition at line 6748 of file GCS_Common.cpp.
Referenced by send_autopilot_version().
channel_buffer()
mavlink_message_t * GCS_MAVLINK::channel_buffer () inline
Definition at line 198 of file GCS.h.
Referenced by mavlink_get_channel_buffer(), and update_receive().
channel_status()
mavlink_status_t * GCS_MAVLINK::channel_status () inline
Definition at line 199 of file GCS.h.
Referenced by mavlink_get_channel_status(), and update_receive().
check_payload_size()
bool GCS_MAVLINK::check_payload_size (uint16_t max_payload_len)
Definition at line 393 of file GCS.cpp.
Referenced by MAVLink_routing::check_and_forward(), and send_message().
command_long_stores_location()
bool GCS_MAVLINK::command_long_stores_location (const MAV_CMD command) static private
Definition at line 4860 of file GCS_Common.cpp.
Referenced by convert_COMMAND_LONG_to_COMMAND_INT(), location_from_command_t(), and try_command_long_as_command_int().
convert_COMMAND_LONG_to_COMMAND_INT()
void GCS_MAVLINK::convert_COMMAND_LONG_to_COMMAND_INT (const mavlink_command_long_t & in, mavlink_command_int_t & out, MAV_FRAME frame = MAV_FRAME_GLOBAL_RELATIVE_ALT) protected virtual
Definition at line 4937 of file GCS_Common.cpp.
Referenced by handle_command_long(), and try_command_long_as_command_int().
correct_offboard_timestamp_usec_to_ms()
uint32_t GCS_MAVLINK::correct_offboard_timestamp_usec_to_ms (uint64_t offboard_usec, uint16_t payload_size) protected
Definition at line 6559 of file GCS_Common.cpp.
Referenced by handle_landing_target().
deadlock_sem()
void GCS_MAVLINK::deadlock_sem (void) protected
Definition at line 3337 of file GCS_Common.cpp.
Referenced by handle_preflight_reboot().
deferred_message_to_send_index()
int8_t GCS_MAVLINK::deferred_message_to_send_index (uint16_t now16_ms) private
Definition at line 1289 of file GCS_Common.cpp.
Referenced by update_send().
disable_channel_routing()
static void GCS_MAVLINK::disable_channel_routing (mavlink_channel_t chan) inline static
Definition at line 447 of file GCS.h.
do_try_send_message()
bool GCS_MAVLINK::do_try_send_message (const ap_message id) private
Definition at line 1246 of file GCS_Common.cpp.
Referenced by update_send().
find_by_mavtype()
static bool GCS_MAVLINK::find_by_mavtype (uint8_t mav_type, uint8_t & sysid, uint8_t & compid, mavlink_channel_t & channel) inline static
Definition at line 453 of file GCS.h.
find_by_mavtype_and_compid() [1/2]
GCS_MAVLINK * GCS_MAVLINK::find_by_mavtype_and_compid (uint8_t mav_type, uint8_t compid, uint8_t & sysid) static
Definition at line 84 of file GCS_MAVLink.cpp.
find_by_mavtype_and_compid() [2/2]
static bool GCS_MAVLINK::find_by_mavtype_and_compid (uint8_t mav_type, uint8_t compid, uint8_t & sysid, mavlink_channel_t & channel) inline static
Definition at line 459 of file GCS.h.
find_next_bucket_to_send()
void GCS_MAVLINK::find_next_bucket_to_send (uint16_t now16_ms) private
Definition at line 1174 of file GCS_Common.cpp.
Referenced by next_deferred_bucket_message_to_send(), remove_message_from_bucket(), and update_send().
ftp_error()
void GCS_MAVLINK::ftp_error (struct pending_ftp & response, FTP_ERROR error) static private
Definition at line 132 of file GCS_FTP.cpp.
Referenced by ftp_list_dir(), and ftp_worker().
ftp_init()
bool GCS_MAVLINK::ftp_init (void) private
Definition at line 37 of file GCS_FTP.cpp.
Referenced by handle_file_transfer_protocol().
ftp_list_dir()
void GCS_MAVLINK::ftp_list_dir (struct pending_ftp & request, struct pending_ftp & response) static private
Definition at line 615 of file GCS_FTP.cpp.
Referenced by ftp_worker().
ftp_push_replies()
void GCS_MAVLINK::ftp_push_replies (pending_ftp & reply) private
Definition at line 156 of file GCS_FTP.cpp.
Referenced by ftp_worker().
ftp_worker()
void GCS_MAVLINK::ftp_worker (void) private
Definition at line 163 of file GCS_FTP.cpp.
Referenced by ftp_init().
FUNCTOR_TYPEDEF()
GCS_MAVLINK::FUNCTOR_TYPEDEF (protocol_handler_fn_t , bool , uint8_t , AP_HAL::UARTDriver *)
gen_dir_entry()
int GCS_MAVLINK::gen_dir_entry (char * dest, size_t space, const char * path, const struct dirent * entry) static private
Definition at line 583 of file GCS_FTP.cpp.
Referenced by ftp_list_dir().
get_ap_message_interval()
bool GCS_MAVLINK::get_ap_message_interval (ap_message id, uint16_t & interval_ms) const protected
Definition at line 3002 of file GCS_Common.cpp.
Referenced by handle_command_get_message_interval().
get_chan()
mavlink_channel_t GCS_MAVLINK::get_chan () const inline
Definition at line 312 of file GCS.h.
Referenced by MAVLink_routing::check_and_forward(), MAVLink_routing::handle_heartbeat(), MissionItemProtocol::handle_mission_item(), MissionItemProtocol::handle_mission_request_list(), MAVLink_routing::learn_route(), MissionItemProtocol::queued_request_send(), MissionItemProtocol::send_mission_ack(), and MissionItemProtocol::update().
get_default_interval_for_ap_message()
bool GCS_MAVLINK::get_default_interval_for_ap_message (const ap_message id, uint16_t & interval) const private
Definition at line 6515 of file GCS_Common.cpp.
Referenced by set_message_interval().
get_deferred_message_index()
int8_t GCS_MAVLINK::get_deferred_message_index (const ap_message id) const private
Definition at line 1279 of file GCS_Common.cpp.
Referenced by get_ap_message_interval(), and set_ap_message_interval().
get_interval_for_stream()
uint16_t GCS_MAVLINK::get_interval_for_stream (GCS_MAVLINK::streams id) const private
Definition at line 6293 of file GCS_Common.cpp.
Referenced by get_default_interval_for_ap_message(), and initialise_message_intervals_for_stream().
get_last_heartbeat_time()
uint32_t GCS_MAVLINK::get_last_heartbeat_time () const inline
Definition at line 313 of file GCS.h.
get_last_txbuf()
uint8_t GCS_MAVLINK::get_last_txbuf () const inline
Definition at line 483 of file GCS.h.
Referenced by queued_param_send().
get_reschedule_interval_ms()
uint16_t GCS_MAVLINK::get_reschedule_interval_ms (const deferred_message_bucket_t & deferred) const private
Definition at line 1143 of file GCS_Common.cpp.
Referenced by find_next_bucket_to_send(), next_deferred_bucket_message_to_send(), and update_send().
get_stream_slowdown_ms()
uint16_t GCS_MAVLINK::get_stream_slowdown_ms () const inline
Definition at line 482 of file GCS.h.
Referenced by MissionItemProtocol::update().
get_uart()
AP_HAL::UARTDriver * GCS_MAVLINK::get_uart () inline
Definition at line 266 of file GCS.h.
Referenced by handle_serial_control().
global_position_int_alt()
int32_t GCS_MAVLINK::global_position_int_alt () const protected virtual
Definition at line 5594 of file GCS_Common.cpp.
Referenced by send_global_position_int().
global_position_int_relative_alt()
int32_t GCS_MAVLINK::global_position_int_relative_alt () const protected virtual
Definition at line 5597 of file GCS_Common.cpp.
Referenced by send_global_position_int().
handle_adsb_message()
void GCS_MAVLINK::handle_adsb_message (const mavlink_message_t & msg) protected
Referenced by handle_message().
handle_att_pos_mocap()
void GCS_MAVLINK::handle_att_pos_mocap (const mavlink_message_t & msg) private
Referenced by handle_message().
handle_can_frame()
void GCS_MAVLINK::handle_can_frame (const mavlink_message_t & msg) const protected
Referenced by handle_message().
handle_change_alt_request()
virtual void GCS_MAVLINK::handle_change_alt_request (AP_Mission::Mission_Command & cmd) inline private virtual
Definition at line 1025 of file GCS.h.
Referenced by handle_mission_item().
handle_command_accelcal_vehicle_pos()
MAV_RESULT GCS_MAVLINK::handle_command_accelcal_vehicle_pos (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_ack()
void GCS_MAVLINK::handle_command_ack (const mavlink_message_t & msg) protected virtual
Definition at line 3769 of file GCS_Common.cpp.
Referenced by handle_message().
handle_command_airframe_configuration()
MAV_RESULT GCS_MAVLINK::handle_command_airframe_configuration (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_battery_reset()
MAV_RESULT GCS_MAVLINK::handle_command_battery_reset (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_camera()
MAV_RESULT GCS_MAVLINK::handle_command_camera (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_debug_trap()
MAV_RESULT GCS_MAVLINK::handle_command_debug_trap (const mavlink_command_int_t & packet) protected
Definition at line 4685 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_command_do_aux_function()
MAV_RESULT GCS_MAVLINK::handle_command_do_aux_function (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_do_fence_enable()
MAV_RESULT GCS_MAVLINK::handle_command_do_fence_enable (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_do_gripper()
MAV_RESULT GCS_MAVLINK::handle_command_do_gripper (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_do_set_home()
MAV_RESULT GCS_MAVLINK::handle_command_do_set_home (const mavlink_command_int_t & packet) protected
Definition at line 5046 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_command_do_set_mode()
MAV_RESULT GCS_MAVLINK::handle_command_do_set_mode (const mavlink_command_int_t & packet) protected
Definition at line 4658 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_command_do_set_roi() [1/2]
MAV_RESULT GCS_MAVLINK::handle_command_do_set_roi (const Location & roi_loc) protected virtual
Definition at line 5011 of file GCS_Common.cpp.
handle_command_do_set_roi() [2/2]
MAV_RESULT GCS_MAVLINK::handle_command_do_set_roi (const mavlink_command_int_t & packet) protected
Definition at line 5099 of file GCS_Common.cpp.
Referenced by handle_command_do_set_roi(), and handle_command_int_packet().
handle_command_do_sprayer()
MAV_RESULT GCS_MAVLINK::handle_command_do_sprayer (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_fixed_mag_cal_yaw()
MAV_RESULT GCS_MAVLINK::handle_command_fixed_mag_cal_yaw (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_flash_bootloader()
MAV_RESULT GCS_MAVLINK::handle_command_flash_bootloader (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_get_home_position()
MAV_RESULT GCS_MAVLINK::handle_command_get_home_position (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_get_message_interval()
MAV_RESULT GCS_MAVLINK::handle_command_get_message_interval (const mavlink_command_int_t & packet) protected
Definition at line 3023 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_command_int()
void GCS_MAVLINK::handle_command_int (const mavlink_message_t & msg) protected
Definition at line 5379 of file GCS_Common.cpp.
Referenced by handle_message().
handle_command_int_external_position_estimate()
MAV_RESULT GCS_MAVLINK::handle_command_int_external_position_estimate (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_int_packet()
MAV_RESULT GCS_MAVLINK::handle_command_int_packet (const mavlink_command_int_t & packet, const mavlink_message_t & msg) protected virtual
Definition at line 5159 of file GCS_Common.cpp.
Referenced by handle_command_int(), and try_command_long_as_command_int().
handle_command_long()
void GCS_MAVLINK::handle_command_long (const mavlink_message_t & msg) protected
Definition at line 4956 of file GCS_Common.cpp.
Referenced by handle_message().
handle_command_mag_cal()
MAV_RESULT GCS_MAVLINK::handle_command_mag_cal (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_preflight_calibration()
MAV_RESULT GCS_MAVLINK::handle_command_preflight_calibration (const mavlink_command_int_t & packet, const mavlink_message_t & msg) protected virtual
Definition at line 4550 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_command_request_autopilot_capabilities()
MAV_RESULT GCS_MAVLINK::handle_command_request_autopilot_capabilities (const mavlink_command_int_t & packet) protected
Definition at line 4646 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_command_request_message()
MAV_RESULT GCS_MAVLINK::handle_command_request_message (const mavlink_command_int_t & packet) protected
Definition at line 2991 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_command_run_prearm_checks()
MAV_RESULT GCS_MAVLINK::handle_command_run_prearm_checks (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_set_ekf_source_set()
MAV_RESULT GCS_MAVLINK::handle_command_set_ekf_source_set (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_command_set_message_interval()
MAV_RESULT GCS_MAVLINK::handle_command_set_message_interval (const mavlink_command_int_t & packet) protected
Definition at line 2921 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_command_storage_format()
MAV_RESULT GCS_MAVLINK::handle_command_storage_format (const mavlink_command_int_t & packet, const mavlink_message_t & msg) protected
Referenced by handle_command_int_packet().
handle_common_mission_message()
void GCS_MAVLINK::handle_common_mission_message (const mavlink_message_t & msg) private
Definition at line 4288 of file GCS_Common.cpp.
Referenced by handle_message().
handle_common_param_message()
void GCS_MAVLINK::handle_common_param_message (const mavlink_message_t & msg) protected
Definition at line 459 of file GCS_Param.cpp.
Referenced by handle_message().
handle_common_rally_message()
void GCS_MAVLINK::handle_common_rally_message (const mavlink_message_t & msg) protected
Referenced by handle_message().
handle_common_vision_position_estimate_data()
void GCS_MAVLINK::handle_common_vision_position_estimate_data (const uint64_t usec, const float x, const float y, const float z, const float roll, const float pitch, const float yaw, const float covariance[21], const uint8_t reset_counter, const uint16_t payload_size) private
handle_control_high_latency()
MAV_RESULT GCS_MAVLINK::handle_control_high_latency (const mavlink_command_int_t & packet) protected
Definition at line 6958 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_data_packet()
void GCS_MAVLINK::handle_data_packet (const mavlink_message_t & msg) protected
Definition at line 3609 of file GCS_Common.cpp.
Referenced by handle_message().
handle_device_op_read()
void GCS_MAVLINK::handle_device_op_read (const mavlink_message_t & msg) protected
Definition at line 34 of file GCS_DeviceOp.cpp.
Referenced by handle_message().
handle_device_op_write()
void GCS_MAVLINK::handle_device_op_write (const mavlink_message_t & msg) protected
Definition at line 101 of file GCS_DeviceOp.cpp.
Referenced by handle_message().
handle_distance_sensor()
void GCS_MAVLINK::handle_distance_sensor (const mavlink_message_t & msg) protected
Definition at line 3891 of file GCS_Common.cpp.
Referenced by handle_message().
handle_do_set_safety_switch_state()
MAV_RESULT GCS_MAVLINK::handle_do_set_safety_switch_state (const mavlink_command_int_t & packet, const mavlink_message_t & msg) protected
Definition at line 5140 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_fence_message()
void GCS_MAVLINK::handle_fence_message (const mavlink_message_t & msg) protected
Referenced by handle_message().
handle_file_transfer_protocol()
void GCS_MAVLINK::handle_file_transfer_protocol (const mavlink_message_t & msg) private
Definition at line 71 of file GCS_FTP.cpp.
Referenced by handle_message().
handle_flight_termination()
MAV_RESULT GCS_MAVLINK::handle_flight_termination (const mavlink_command_int_t & packet) protected virtual
Definition at line 3349 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_global_vision_position_estimate()
void GCS_MAVLINK::handle_global_vision_position_estimate (const mavlink_message_t & msg) private
Referenced by handle_message().
handle_guided_request()
virtual bool GCS_MAVLINK::handle_guided_request (AP_Mission::Mission_Command & cmd) inline private virtual
Definition at line 1024 of file GCS.h.
Referenced by handle_mission_item().
handle_heartbeat()
void GCS_MAVLINK::handle_heartbeat (const mavlink_message_t & msg) const protected
Definition at line 3946 of file GCS_Common.cpp.
Referenced by handle_message().
handle_landing_target() [1/2]
virtual void GCS_MAVLINK::handle_landing_target (const mavlink_landing_target_t & packet, uint32_t timestamp_ms) inline protected virtual
Definition at line 695 of file GCS.h.
Referenced by handle_landing_target(), and handle_message().
handle_landing_target() [2/2]
void GCS_MAVLINK::handle_landing_target (const mavlink_message_t & msg) private
Definition at line 5036 of file GCS_Common.cpp.
handle_manual_control()
void GCS_MAVLINK::handle_manual_control (const mavlink_message_t & msg) protected
Referenced by handle_message().
handle_manual_control_axes()
virtual void GCS_MAVLINK::handle_manual_control_axes (const mavlink_manual_control_t & packet, const uint32_t tnow) inline private virtual
Definition at line 1028 of file GCS.h.
handle_message()
void GCS_MAVLINK::handle_message (const mavlink_message_t & msg) protected virtual
Definition at line 3958 of file GCS_Common.cpp.
Referenced by packetReceived().
handle_mission_clear_all()
void GCS_MAVLINK::handle_mission_clear_all (const mavlink_message_t & msg) protected
Definition at line 741 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_count()
void GCS_MAVLINK::handle_mission_count (const mavlink_message_t & msg) protected
Definition at line 719 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_item()
void GCS_MAVLINK::handle_mission_item (const mavlink_message_t & msg) protected
Definition at line 884 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_request_int()
void GCS_MAVLINK::handle_mission_request_int (const mavlink_message_t & msg) protected
Definition at line 607 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_request_list()
void GCS_MAVLINK::handle_mission_request_list (const mavlink_message_t & msg) protected
Definition at line 585 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_mission_write_partial_list()
void GCS_MAVLINK::handle_mission_write_partial_list (const mavlink_message_t & msg) protected
Definition at line 767 of file GCS_Common.cpp.
Referenced by handle_common_mission_message().
handle_named_value()
void GCS_MAVLINK::handle_named_value (const mavlink_message_t & msg) const protected
Definition at line 3510 of file GCS_Common.cpp.
Referenced by handle_message().
handle_obstacle_distance()
void GCS_MAVLINK::handle_obstacle_distance (const mavlink_message_t & msg) protected
Referenced by handle_message().
handle_obstacle_distance_3d()
void GCS_MAVLINK::handle_obstacle_distance_3d (const mavlink_message_t & msg) protected
Referenced by handle_message().
handle_odometry()
void GCS_MAVLINK::handle_odometry (const mavlink_message_t & msg) private
Referenced by handle_message().
handle_optical_flow()
void GCS_MAVLINK::handle_optical_flow (const mavlink_message_t & msg) protected
Referenced by handle_message().
handle_osd_param_config()
void GCS_MAVLINK::handle_osd_param_config (const mavlink_message_t & msg) const protected
Referenced by handle_message().
handle_param_request_list()
void GCS_MAVLINK::handle_param_request_list (const mavlink_message_t & msg) protected
Definition at line 206 of file GCS_Param.cpp.
Referenced by handle_common_param_message().
handle_param_request_read()
void GCS_MAVLINK::handle_param_request_read (const mavlink_message_t & msg) protected
Definition at line 225 of file GCS_Param.cpp.
Referenced by handle_common_param_message().
handle_param_set()
void GCS_MAVLINK::handle_param_set (const mavlink_message_t & msg) protected
Definition at line 263 of file GCS_Param.cpp.
Referenced by handle_common_param_message().
handle_param_value()
void GCS_MAVLINK::handle_param_value (const mavlink_message_t & msg) protected
Definition at line 799 of file GCS_Common.cpp.
Referenced by handle_message().
handle_preflight_reboot()
MAV_RESULT GCS_MAVLINK::handle_preflight_reboot (const mavlink_command_int_t & packet, const mavlink_message_t & msg) protected virtual
but allow it if forced:
Definition at line 3203 of file GCS_Common.cpp.
Referenced by handle_command_int_packet().
handle_radio_status()
void GCS_MAVLINK::handle_radio_status (const mavlink_message_t & msg) protected
Definition at line 831 of file GCS_Common.cpp.
Referenced by handle_message().
handle_rally_fetch_point()
void GCS_MAVLINK::handle_rally_fetch_point (const mavlink_message_t & msg) protected
handle_rally_point()
void GCS_MAVLINK::handle_rally_point (const mavlink_message_t & msg) const protected
handle_rc_channels_override()
void GCS_MAVLINK::handle_rc_channels_override (const mavlink_message_t & msg) protected
Referenced by handle_message().
handle_request_data_stream()
void GCS_MAVLINK::handle_request_data_stream (const mavlink_message_t & msg) protected
Definition at line 129 of file GCS_Param.cpp.
Referenced by handle_message().
handle_send_autopilot_version()
void GCS_MAVLINK::handle_send_autopilot_version (const mavlink_message_t & msg) protected
Definition at line 4353 of file GCS_Common.cpp.
Referenced by handle_message().
handle_serial_control()
void GCS_MAVLINK::handle_serial_control (const mavlink_message_t & msg) protected
handle a SERIAL_CONTROL message
Definition at line 33 of file GCS_serial_control.cpp.
Referenced by handle_message().
handle_servorelay_message()
MAV_RESULT GCS_MAVLINK::handle_servorelay_message (const mavlink_command_int_t & packet) private
Referenced by handle_command_int_packet().
handle_set_gps_global_origin()
void GCS_MAVLINK::handle_set_gps_global_origin (const mavlink_message_t & msg) protected
Referenced by handle_message().
handle_set_mode()
void GCS_MAVLINK::handle_set_mode (const mavlink_message_t & msg) protected
Definition at line 2615 of file GCS_Common.cpp.
Referenced by handle_message().
handle_setup_signing()
void GCS_MAVLINK::handle_setup_signing (const mavlink_message_t & msg) const protected
Definition at line 70 of file GCS_Signing.cpp.
Referenced by handle_message().
handle_START_RX_PAIR()
MAV_RESULT GCS_MAVLINK::handle_START_RX_PAIR (const mavlink_command_int_t & packet) protected
Referenced by handle_command_int_packet().
handle_statustext()
void GCS_MAVLINK::handle_statustext (const mavlink_message_t & msg) const protected
Definition at line 3476 of file GCS_Common.cpp.
Referenced by handle_message().
handle_system_time_message()
void GCS_MAVLINK::handle_system_time_message (const mavlink_message_t & msg) protected
Referenced by handle_message().
handle_timesync()
void GCS_MAVLINK::handle_timesync (const mavlink_message_t & msg) protected
Definition at line 3404 of file GCS_Common.cpp.
Referenced by handle_message().
handle_vicon_position_estimate()
void GCS_MAVLINK::handle_vicon_position_estimate (const mavlink_message_t & msg) private
Referenced by handle_message().
handle_vision_position_delta()
void GCS_MAVLINK::handle_vision_position_delta (const mavlink_message_t & msg) protected
Referenced by handle_message().
handle_vision_position_estimate()
void GCS_MAVLINK::handle_vision_position_estimate (const mavlink_message_t & msg) private
Referenced by handle_message().
handle_vision_speed_estimate()
void GCS_MAVLINK::handle_vision_speed_estimate (const mavlink_message_t & msg) private
Referenced by handle_message().
have_flow_control()
bool GCS_MAVLINK::have_flow_control (void)
Definition at line 105 of file GCS_Param.cpp.
Referenced by queued_param_send().
high_latency_air_temperature()
int8_t GCS_MAVLINK::high_latency_air_temperature () const protected
Definition at line 6939 of file GCS_Common.cpp.
Referenced by send_high_latency2().
high_latency_target_altitude()
virtual int16_t GCS_MAVLINK::high_latency_target_altitude () const inline protected virtual
Definition at line 715 of file GCS.h.
Referenced by send_high_latency2().
high_latency_tgt_airspeed()
virtual uint8_t GCS_MAVLINK::high_latency_tgt_airspeed () const inline protected virtual
Definition at line 718 of file GCS.h.
Referenced by send_high_latency2().
high_latency_tgt_dist()
virtual uint16_t GCS_MAVLINK::high_latency_tgt_dist () const inline protected virtual
Definition at line 717 of file GCS.h.
Referenced by send_high_latency2().
high_latency_tgt_heading()
virtual uint8_t GCS_MAVLINK::high_latency_tgt_heading () const inline protected virtual
Definition at line 716 of file GCS.h.
Referenced by send_high_latency2().
high_latency_wind_direction()
virtual uint8_t GCS_MAVLINK::high_latency_wind_direction () const inline protected virtual
Definition at line 720 of file GCS.h.
Referenced by send_high_latency2().
high_latency_wind_speed()
virtual uint8_t GCS_MAVLINK::high_latency_wind_speed () const inline protected virtual
Definition at line 719 of file GCS.h.
Referenced by send_high_latency2().
init()
bool GCS_MAVLINK::init (uint8_t instance)
Definition at line 134 of file GCS_Common.cpp.
Referenced by GCS::create_gcs_mavlink_backend().
initialise_message_intervals_for_stream()
void GCS_MAVLINK::initialise_message_intervals_for_stream (GCS_MAVLINK::streams id) private
Definition at line 6306 of file GCS_Common.cpp.
Referenced by handle_request_data_stream(), and initialise_message_intervals_from_streamrates().
initialise_message_intervals_from_streamrates()
void GCS_MAVLINK::initialise_message_intervals_from_streamrates () private
Definition at line 6498 of file GCS_Common.cpp.
Referenced by update_send().
is_active()
bool GCS_MAVLINK::is_active () const inline
Definition at line 305 of file GCS.h.
Referenced by GCS::send_to_active_channels(), and update_receive().
is_high_bandwidth()
bool GCS_MAVLINK::is_high_bandwidth () inline
Definition at line 301 of file GCS.h.
is_private() [1/2]
static bool GCS_MAVLINK::is_private (mavlink_channel_t _chan) inline static
Definition at line 426 of file GCS.h.
Referenced by MAVLink_routing::check_and_forward(), and GCS::send_to_active_channels().
is_private() [2/2]
bool GCS_MAVLINK::is_private (void) const inline
Definition at line 431 of file GCS.h.
Referenced by is_private(), and update_receive().
is_streaming()
bool GCS_MAVLINK::is_streaming () const inline
Definition at line 308 of file GCS.h.
Referenced by send_message(), and update_receive().
landed_state()
virtual MAV_LANDED_STATE GCS_MAVLINK::landed_state () const inline protected virtual
Definition at line 502 of file GCS.h.
Referenced by send_extended_sys_state().
last_radio_status_remrssi_ms()
static uint32_t GCS_MAVLINK::last_radio_status_remrssi_ms () inline static
Definition at line 317 of file GCS.h.
load_signing_key()
void GCS_MAVLINK::load_signing_key (void) private
Definition at line 133 of file GCS_Signing.cpp.
Referenced by handle_setup_signing(), and init().
location_from_command_t()
bool GCS_MAVLINK::location_from_command_t (const mavlink_command_int_t & in, Location & out) protected
Definition at line 4835 of file GCS_Common.cpp.
Referenced by handle_command_do_set_home(), and handle_command_do_set_roi().
lock()
void GCS_MAVLINK::lock (bool _lock) inline
Definition at line 403 of file GCS.h.
Referenced by handle_serial_control().
lock_channel()
void GCS_MAVLINK::lock_channel (const mavlink_channel_t chan, bool lock) private
locked()
bool GCS_MAVLINK::locked () const inline
Definition at line 407 of file GCS.h.
Referenced by update_receive().
log_mavlink_stats()
void GCS_MAVLINK::log_mavlink_stats () private
Referenced by update_receive().
manual_override()
void GCS_MAVLINK::manual_override (class RC_Channel * c, int16_t value_in, uint16_t offset, float scaler, const uint32_t tnow, bool reversed = false) protected
mav_frame_for_command_long()
bool GCS_MAVLINK::mav_frame_for_command_long (MAV_FRAME & fame, MAV_CMD packet_command) const protected virtual
Definition at line 4881 of file GCS_Common.cpp.
Referenced by try_command_long_as_command_int().
mav_param_type()
MAV_PARAM_TYPE GCS_MAVLINK::mav_param_type (enum ap_var_type t) static protected
Definition at line 101 of file GCS_MAVLink.cpp.
Referenced by queued_param_send(), send_parameter_async_replies(), send_parameter_value(), and GCS::send_parameter_value().
mavlink_coordinate_frame_to_location_alt_frame()
bool GCS_MAVLINK::mavlink_coordinate_frame_to_location_alt_frame (MAV_FRAME coordinate_frame, Location::AltFrame & frame) protected
Definition at line 6725 of file GCS_Common.cpp.
Referenced by location_from_command_t().
mavlink_id_to_ap_message_id()
ap_message GCS_MAVLINK::mavlink_id_to_ap_message_id (const uint32_t mavlink_id) const private
Definition at line 962 of file GCS_Common.cpp.
Referenced by handle_command_get_message_interval(), handle_command_request_message(), set_mavlink_message_id_interval(), and set_message_interval().
mission_state()
MISSION_STATE GCS_MAVLINK::mission_state (const class AP_Mission & mission) const virtual
Definition at line 637 of file GCS_Common.cpp.
Referenced by send_mission_current().
next_deferred_bucket_message_to_send()
ap_message GCS_MAVLINK::next_deferred_bucket_message_to_send (uint16_t now16_ms) private
Definition at line 1218 of file GCS_Common.cpp.
Referenced by update_send().
out_of_space_to_send()
void GCS_MAVLINK::out_of_space_to_send () inline
Definition at line 228 of file GCS.h.
Referenced by gcs_out_of_space_to_send().
packet_overhead()
uint8_t GCS_MAVLINK::packet_overhead (void) const inline protected
Definition at line 510 of file GCS.h.
Referenced by check_payload_size(), and queued_param_send().
packet_overhead_chan()
uint8_t GCS_MAVLINK::packet_overhead_chan (mavlink_channel_t chan) static
Definition at line 244 of file GCS_Signing.cpp.
Referenced by MAVLink_routing::handle_heartbeat(), packet_overhead(), and MAVLink_routing::send_to_components().
packetReceived()
void GCS_MAVLINK::packetReceived (const mavlink_status_t & status, const mavlink_message_t & msg) virtual
Definition at line 1744 of file GCS_Common.cpp.
Referenced by update_receive().
param_io_timer()
void GCS_MAVLINK::param_io_timer (void) private
Definition at line 369 of file GCS_Param.cpp.
Referenced by handle_param_request_read().
params_ready()
virtual bool GCS_MAVLINK::params_ready () const inline protected virtual
Definition at line 568 of file GCS.h.
Referenced by handle_param_request_list().
persist_streamrates()
virtual bool GCS_MAVLINK::persist_streamrates () const inline protected virtual
Definition at line 517 of file GCS.h.
Referenced by handle_request_data_stream().
private_channel_mask()
static uint8_t GCS_MAVLINK::private_channel_mask (void) inline static
Definition at line 419 of file GCS.h.
queued_mission_request_send()
void GCS_MAVLINK::queued_mission_request_send ()
queued_param_send()
void GCS_MAVLINK::queued_param_send ()
Send the next pending parameter, called from deferred message handling code.
Definition at line 41 of file GCS_Param.cpp.
Referenced by try_send_message().
receiver_rssi()
uint8_t GCS_MAVLINK::receiver_rssi () const protected
remove_message_from_bucket()
void GCS_MAVLINK::remove_message_from_bucket (int8_t bucket, ap_message id) private
Definition at line 1584 of file GCS_Common.cpp.
Referenced by set_ap_message_interval().
requesting_mission_items()
bool GCS_MAVLINK::requesting_mission_items () const
Definition at line 757 of file GCS_Common.cpp.
Referenced by get_reschedule_interval_ms().
save_signing_timestamp()
void GCS_MAVLINK::save_signing_timestamp (bool force_save_now) static private
Definition at line 199 of file GCS_Signing.cpp.
Referenced by send_message(), and update_signing_timestamp().
send_accelcal_vehicle_position()
void GCS_MAVLINK::send_accelcal_vehicle_position (uint32_t position)
Definition at line 3125 of file GCS_Common.cpp.
send_ahrs()
void GCS_MAVLINK::send_ahrs ()
Definition at line 2220 of file GCS_Common.cpp.
Referenced by try_send_message().
send_ahrs2()
void GCS_MAVLINK::send_ahrs2 ()
Definition at line 556 of file GCS_Common.cpp.
Referenced by try_send_message().
send_attitude()
void GCS_MAVLINK::send_attitude () const virtual
Definition at line 5552 of file GCS_Common.cpp.
Referenced by try_send_message().
send_attitude_quaternion()
void GCS_MAVLINK::send_attitude_quaternion () const virtual
Definition at line 5569 of file GCS_Common.cpp.
Referenced by try_send_message().
send_attitude_target()
virtual void GCS_MAVLINK::send_attitude_target () inline virtual
Definition at line 380 of file GCS.h.
Referenced by try_send_message().
send_autopilot_state_for_gimbal_device()
void GCS_MAVLINK::send_autopilot_state_for_gimbal_device () const
Definition at line 5776 of file GCS_Common.cpp.
Referenced by try_send_message().
send_autopilot_version()
void GCS_MAVLINK::send_autopilot_version () const
Definition at line 2707 of file GCS_Common.cpp.
Referenced by try_send_message().
send_banner()
void GCS_MAVLINK::send_banner () protected virtual
Definition at line 4359 of file GCS_Common.cpp.
Referenced by handle_command_int_packet(), handle_param_request_list(), and send_ftp_reply().
send_battery2()
void GCS_MAVLINK::send_battery2 ()
Referenced by try_send_message().
send_battery_status() [1/2]
bool GCS_MAVLINK::send_battery_status ()
Referenced by try_send_message().
send_battery_status() [2/2]
void GCS_MAVLINK::send_battery_status (const uint8_t instance) const
send_distance_sensor() [1/2]
void GCS_MAVLINK::send_distance_sensor ()
Definition at line 427 of file GCS_Common.cpp.
Referenced by send_distance_sensor(), and try_send_message().
send_distance_sensor() [2/2]
void GCS_MAVLINK::send_distance_sensor (const class AP_RangeFinder_Backend * sensor, const uint8_t instance) const private
send_extended_sys_state()
void GCS_MAVLINK::send_extended_sys_state () const
Definition at line 5547 of file GCS_Common.cpp.
Referenced by try_send_message().
send_fence_status()
void GCS_MAVLINK::send_fence_status () const
Referenced by try_send_message().
send_ftp_reply()
bool GCS_MAVLINK::send_ftp_reply (const pending_ftp & reply) private
Definition at line 98 of file GCS_FTP.cpp.
Referenced by ftp_push_replies().
send_generator_status()
void GCS_MAVLINK::send_generator_status () const
Referenced by try_send_message().
send_gimbal_device_attitude_status()
void GCS_MAVLINK::send_gimbal_device_attitude_status () const
Referenced by try_send_message().
send_gimbal_manager_information()
void GCS_MAVLINK::send_gimbal_manager_information () const
Referenced by try_send_message().
send_gimbal_manager_status()
void GCS_MAVLINK::send_gimbal_manager_status () const
Referenced by try_send_message().
send_global_position_int()
void GCS_MAVLINK::send_global_position_int () protected virtual
Definition at line 5608 of file GCS_Common.cpp.
Referenced by try_send_message().
send_gps_global_origin()
void GCS_MAVLINK::send_gps_global_origin () const
Referenced by try_send_message().
send_heartbeat()
void GCS_MAVLINK::send_heartbeat (void) const
Definition at line 2893 of file GCS_Common.cpp.
Referenced by try_send_message().
send_high_latency2()
void GCS_MAVLINK::send_high_latency2 () const
Definition at line 6855 of file GCS_Common.cpp.
Referenced by try_send_message().
send_home_position()
void GCS_MAVLINK::send_home_position () const
Referenced by try_send_message().
send_hwstatus()
void GCS_MAVLINK::send_hwstatus () protected
Definition at line 5458 of file GCS_Common.cpp.
Referenced by try_send_message().
send_local_position()
void GCS_MAVLINK::send_local_position () const
Definition at line 2773 of file GCS_Common.cpp.
Referenced by try_send_message().
send_meminfo()
void GCS_MAVLINK::send_meminfo (void)
Definition at line 203 of file GCS_Common.cpp.
Referenced by try_send_message().
send_message() [1/3]
void GCS_MAVLINK::send_message (const char * pkt, const mavlink_msg_entry_t * entry) inline
Definition at line 253 of file GCS.h.
send_message() [2/3]
void GCS_MAVLINK::send_message (enum ap_message id)
Definition at line 1722 of file GCS_Common.cpp.
Referenced by handle_command_request_autopilot_capabilities(), handle_command_request_message(), MissionItemProtocol::handle_mission_item(), MissionItemProtocol::handle_mission_request_int(), handle_send_autopilot_version(), MissionItemProtocol::init_send_requests(), send_message(), GCS::send_to_active_channels(), and MissionItemProtocol::update().
send_message() [3/3]
void GCS_MAVLINK::send_message (uint32_t msgid, const char * pkt) inline
Definition at line 246 of file GCS.h.
send_mission_ack()
void GCS_MAVLINK::send_mission_ack (const mavlink_message_t & msg, MAV_MISSION_TYPE mission_type, MAV_MISSION_RESULT result) const inline
Definition at line 230 of file GCS.h.
Referenced by handle_mission_clear_all(), handle_mission_item(), and handle_mission_write_partial_list().
send_mission_current()
void GCS_MAVLINK::send_mission_current (const class AP_Mission & mission, uint16_t seq)
Definition at line 656 of file GCS_Common.cpp.
Referenced by try_send_mission_message().
send_named_float()
void GCS_MAVLINK::send_named_float (const char * name, float value) const
Definition at line 2819 of file GCS_Common.cpp.
send_nav_controller_output()
virtual void GCS_MAVLINK::send_nav_controller_output () const pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by try_send_message().
send_opticalflow()
void GCS_MAVLINK::send_opticalflow ()
Referenced by try_send_message().
send_parameter_async_replies()
uint8_t GCS_MAVLINK::send_parameter_async_replies () private
Definition at line 418 of file GCS_Param.cpp.
Referenced by queued_param_send().
send_parameter_value()
void GCS_MAVLINK::send_parameter_value (const char * param_name, ap_var_type param_type, float param_value)
Definition at line 326 of file GCS_Param.cpp.
Referenced by handle_param_set().
send_pid_tuning()
virtual void GCS_MAVLINK::send_pid_tuning () pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by try_send_message().
send_position_target_global_int()
virtual void GCS_MAVLINK::send_position_target_global_int () inline virtual
Definition at line 381 of file GCS.h.
Referenced by try_send_message().
send_position_target_local_ned()
virtual void GCS_MAVLINK::send_position_target_local_ned () inline virtual
Definition at line 382 of file GCS.h.
Referenced by try_send_message().
send_power_status()
void GCS_MAVLINK::send_power_status (void)
Definition at line 211 of file GCS_Common.cpp.
Referenced by try_send_message().
send_proximity()
void GCS_MAVLINK::send_proximity ()
Referenced by send_distance_sensor().
send_raw_imu()
void GCS_MAVLINK::send_raw_imu ()
Definition at line 2078 of file GCS_Common.cpp.
Referenced by try_send_message().
send_rc_channels()
void GCS_MAVLINK::send_rc_channels () const
Referenced by try_send_message().
send_rc_channels_raw()
void GCS_MAVLINK::send_rc_channels_raw () const
Referenced by try_send_message().
send_received_message_deprecation_warning()
void GCS_MAVLINK::send_received_message_deprecation_warning (const char * message) protected
Definition at line 5827 of file GCS_Common.cpp.
Referenced by handle_message().
send_relay_status()
bool GCS_MAVLINK::send_relay_status () const private
Referenced by try_send_message().
send_rpm()
void GCS_MAVLINK::send_rpm () const
Referenced by try_send_message().
send_scaled_imu()
void GCS_MAVLINK::send_scaled_imu (uint8_t instance, void(*)(mavlink_channel_t chan, uint32_t time_ms, int16_t xacc, int16_t yacc, int16_t zacc, int16_t xgyro, int16_t ygyro, int16_t zgyro, int16_t xmag, int16_t ymag, int16_t zmag, int16_t temperature) send_fn)
Definition at line 2110 of file GCS_Common.cpp.
Referenced by try_send_message().
send_scaled_pressure()
void GCS_MAVLINK::send_scaled_pressure ()
Definition at line 2205 of file GCS_Common.cpp.
Referenced by try_send_message().
send_scaled_pressure2()
void GCS_MAVLINK::send_scaled_pressure2 ()
Definition at line 2210 of file GCS_Common.cpp.
Referenced by try_send_message().
send_scaled_pressure3()
void GCS_MAVLINK::send_scaled_pressure3 () virtual
Definition at line 2215 of file GCS_Common.cpp.
Referenced by try_send_message().
send_scaled_pressure_instance()
void GCS_MAVLINK::send_scaled_pressure_instance (uint8_t instance, void(*)(mavlink_channel_t chan, uint32_t time_boot_ms, float press_abs, float press_diff, int16_t temperature, int16_t temperature_press_diff) send_fn)
Definition at line 2159 of file GCS_Common.cpp.
Referenced by send_scaled_pressure(), send_scaled_pressure2(), and send_scaled_pressure3().
send_servo_output_raw()
void GCS_MAVLINK::send_servo_output_raw ()
Definition at line 3079 of file GCS_Common.cpp.
Referenced by try_send_message().
send_set_position_target_global_int()
void GCS_MAVLINK::send_set_position_target_global_int (uint8_t target_system, uint8_t target_component, const Location & loc)
Definition at line 5663 of file GCS_Common.cpp.
send_sim_state()
void GCS_MAVLINK::send_sim_state () const
Referenced by try_send_message().
send_simstate()
void GCS_MAVLINK::send_simstate () const
Referenced by try_send_message().
send_sys_status()
void GCS_MAVLINK::send_sys_status ()
Definition at line 5490 of file GCS_Common.cpp.
Referenced by try_send_message().
send_system_time()
void GCS_MAVLINK::send_system_time () const
Definition at line 1988 of file GCS_Common.cpp.
Referenced by try_send_message().
send_text()
void GCS_MAVLINK::send_text (MAV_SEVERITY severity, const char * fmt, ...) const
Definition at line 810 of file GCS_Common.cpp.
Referenced by handle_command_int_packet(), handle_preflight_reboot(), handle_setup_signing(), send_banner(), and send_received_message_deprecation_warning().
send_timesync()
void GCS_MAVLINK::send_timesync () protected
Definition at line 3466 of file GCS_Common.cpp.
Referenced by update_receive().
send_to_components()
static void GCS_MAVLINK::send_to_components (uint32_t msgid, const char * pkt, uint8_t pkt_len) inline static
Definition at line 442 of file GCS.h.
Referenced by AP_BattMonitor::checkPoweringOff(), and handle_control_high_latency().
send_uavionix_adsb_out_status()
void GCS_MAVLINK::send_uavionix_adsb_out_status () const
Referenced by try_send_message().
send_vfr_hud()
void GCS_MAVLINK::send_vfr_hud ()
Definition at line 3176 of file GCS_Common.cpp.
Referenced by try_send_message().
send_vibration()
void GCS_MAVLINK::send_vibration () const
Definition at line 2800 of file GCS_Common.cpp.
Referenced by try_send_message().
send_water_depth()
void GCS_MAVLINK::send_water_depth () const
Referenced by try_send_message().
sending_mavlink1()
bool GCS_MAVLINK::sending_mavlink1 () const
Definition at line 2002 of file GCS_Common.cpp.
Referenced by MissionItemProtocol::mavlink2_requirement_met().
service_statustext()
void GCS_MAVLINK::service_statustext (void) private
Definition at line 2401 of file GCS_Common.cpp.
Referenced by GCS::send_textv(), and GCS::update_send().
set_ap_message_interval()
bool GCS_MAVLINK::set_ap_message_interval (enum ap_message id, uint16_t interval_ms) private
Definition at line 1612 of file GCS_Common.cpp.
Referenced by initialise_message_intervals_for_stream(), set_mavlink_message_id_interval(), and set_message_interval().
set_channel_private()
void GCS_MAVLINK::set_channel_private (mavlink_channel_t chan) static
Definition at line 94 of file GCS_MAVLink.cpp.
Referenced by init().
set_ekf_origin()
void GCS_MAVLINK::set_ekf_origin (const Location & loc) protected
set_home()
virtual bool GCS_MAVLINK::set_home (const Location & loc, bool lock) protected pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by handle_command_do_set_home().
set_home_to_current_location()
virtual bool GCS_MAVLINK::set_home_to_current_location (bool lock) protected pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by handle_command_do_set_home().
set_mavlink_message_id_interval()
bool GCS_MAVLINK::set_mavlink_message_id_interval (const uint32_t mavlink_id, const uint16_t interval_ms) private
Definition at line 1112 of file GCS_Common.cpp.
Referenced by initialise_message_intervals_from_streamrates().
set_message_interval()
MAV_RESULT GCS_MAVLINK::set_message_interval (uint32_t msg_id, int32_t interval_us)
Definition at line 2926 of file GCS_Common.cpp.
Referenced by handle_command_set_message_interval(), and GCS::set_message_interval().
should_send_message_in_delay_callback()
bool GCS_MAVLINK::should_send_message_in_delay_callback (const ap_message id) const private
Definition at line 1123 of file GCS_Common.cpp.
Referenced by do_try_send_message().
signing_enabled()
bool GCS_MAVLINK::signing_enabled (void) const private
Definition at line 232 of file GCS_Signing.cpp.
signing_key_load()
bool GCS_MAVLINK::signing_key_load (struct SigningKey & key) static private
Definition at line 53 of file GCS_Signing.cpp.
Referenced by load_signing_key(), and save_signing_timestamp().
signing_key_save()
bool GCS_MAVLINK::signing_key_save (const struct SigningKey & key) static private
Definition at line 45 of file GCS_Signing.cpp.
Referenced by handle_setup_signing(), and save_signing_timestamp().
streaming_channel_mask()
static uint8_t GCS_MAVLINK::streaming_channel_mask (void) inline static
Definition at line 416 of file GCS.h.
Referenced by GCS::statustext_send_channel_mask().
sysid_enforce()
virtual bool GCS_MAVLINK::sysid_enforce () const inline virtual
Definition at line 269 of file GCS.h.
Referenced by accept_packet().
sysid_my_gcs()
virtual uint8_t GCS_MAVLINK::sysid_my_gcs () const pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by accept_packet(), handle_heartbeat(), and handle_statustext().
system_status()
MAV_STATE GCS_MAVLINK::system_status () const protected
Definition at line 2874 of file GCS_Common.cpp.
Referenced by send_heartbeat().
telem_delay()
virtual uint32_t GCS_MAVLINK::telem_delay () const protected pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by telemetry_delayed().
telemetry_delayed()
bool GCS_MAVLINK::telemetry_delayed () const protected
Definition at line 3060 of file GCS_Common.cpp.
Referenced by do_try_send_message().
telemetry_radio_rssi()
float GCS_MAVLINK::telemetry_radio_rssi () static
Definition at line 818 of file GCS_Common.cpp.
Referenced by AP_RSSI::read_telemetry_radio_rssi().
timesync_receive_timestamp_ns()
uint64_t GCS_MAVLINK::timesync_receive_timestamp_ns () const protected
Definition at line 3384 of file GCS_Common.cpp.
Referenced by handle_timesync().
timesync_timestamp_ns()
uint64_t GCS_MAVLINK::timesync_timestamp_ns () const protected
Definition at line 3393 of file GCS_Common.cpp.
Referenced by send_timesync().
try_command_long_as_command_int()
MAV_RESULT GCS_MAVLINK::try_command_long_as_command_int (const mavlink_command_long_t & packet, const mavlink_message_t & msg) protected
Definition at line 4905 of file GCS_Common.cpp.
Referenced by handle_command_long().
try_send_message()
bool GCS_MAVLINK::try_send_message (enum ap_message id) protected virtual
Reimplemented in GCS_MAVLINK_Dummy.
Definition at line 5845 of file GCS_Common.cpp.
Referenced by do_try_send_message().
try_send_mission_message()
bool GCS_MAVLINK::try_send_mission_message (enum ap_message id) protected
Definition at line 5418 of file GCS_Common.cpp.
Referenced by try_send_message().
txspace()
uint16_t GCS_MAVLINK::txspace () const inline
Check for available transmit space.
Definition at line 215 of file GCS.h.
Referenced by check_payload_size(), comm_get_txspace(), handle_command_get_message_interval(), queued_param_send(), and service_statustext().
update_receive()
void GCS_MAVLINK::update_receive (uint32_t max_time_us = 1000)
Definition at line 1788 of file GCS_Common.cpp.
update_send()
void GCS_MAVLINK::update_send ()
Definition at line 1453 of file GCS_Common.cpp.
update_signing_timestamp()
void GCS_MAVLINK::update_signing_timestamp (uint64_t timestamp_usec) static
Definition at line 170 of file GCS_Signing.cpp.
Referenced by AP_RTC::set_utc_usec().
vehicle_system_status()
virtual MAV_STATE GCS_MAVLINK::vehicle_system_status () const protected pure virtual
Implemented in GCS_MAVLINK_Dummy.
Referenced by system_status().
vfr_hud_airspeed()
float GCS_MAVLINK::vfr_hud_airspeed () const protected virtual
Definition at line 3140 of file GCS_Common.cpp.
Referenced by send_high_latency2(), and send_vfr_hud().
vfr_hud_alt()
float GCS_MAVLINK::vfr_hud_alt () const protected virtual
Definition at line 3171 of file GCS_Common.cpp.
Referenced by send_vfr_hud().
vfr_hud_climbrate()
float GCS_MAVLINK::vfr_hud_climbrate () const protected virtual
Definition at line 3159 of file GCS_Common.cpp.
Referenced by send_vfr_hud().
vfr_hud_throttle()
virtual int16_t GCS_MAVLINK::vfr_hud_throttle () const inline protected virtual
Definition at line 711 of file GCS.h.
Referenced by GCS::get_hud_throttle(), send_high_latency2(), and send_vfr_hud().
vtol_state()
virtual MAV_VTOL_STATE GCS_MAVLINK::vtol_state () const inline protected virtual
Definition at line 501 of file GCS.h.
Referenced by send_extended_sys_state().
Friends And Related Symbol Documentation
GCS
friend class GCS friend
Definition at line 192 of file GCS.h.
Member Data Documentation
_channel_buffer
mavlink_message_t GCS_MAVLINK::_channel_buffer private
Definition at line 757 of file GCS.h.
Referenced by channel_buffer().
_channel_status
mavlink_status_t GCS_MAVLINK::_channel_status private
Definition at line 758 of file GCS.h.
Referenced by channel_status(), init(), load_signing_key(), packetReceived(), sending_mavlink1(), and update_send().
[struct]
struct { ... } GCS_MAVLINK::_deadlock_sem
Referenced by deadlock_sem(), and handle_preflight_reboot().
_locked
bool GCS_MAVLINK::_locked private
Definition at line 1111 of file GCS.h.
Referenced by lock(), locked(), and txspace().
_port
AP_HAL::UARTDriver* GCS_MAVLINK::_port private
The stream we are communicating over.
Definition at line 795 of file GCS.h.
Referenced by correct_offboard_timestamp_usec_to_ms(), GCS_MAVLINK(), get_uart(), handle_message(), have_flow_control(), init(), queued_param_send(), timesync_receive_timestamp_ns(), txspace(), and update_receive().
_queued_parameter
AP_Param* GCS_MAVLINK::_queued_parameter protected
next parameter to
Definition at line 507 of file GCS.h.
Referenced by get_reschedule_interval_ms(), handle_param_request_list(), and queued_param_send().
_queued_parameter_count
uint16_t GCS_MAVLINK::_queued_parameter_count private
saved count of
Definition at line 805 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
_queued_parameter_index
uint16_t GCS_MAVLINK::_queued_parameter_index private
AP_Param token for.
next queued
Definition at line 803 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
_queued_parameter_send_time_ms
uint32_t GCS_MAVLINK::_queued_parameter_send_time_ms private
Definition at line 808 of file GCS.h.
Referenced by handle_param_request_list(), queued_param_send(), and send_parameter_async_replies().
_queued_parameter_token
AP_Param::ParamToken GCS_MAVLINK::_queued_parameter_token private
Definition at line 801 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
_queued_parameter_type
enum ap_var_type GCS_MAVLINK::_queued_parameter_type private
type of the next
Perform queued sending operations
Definition at line 799 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
_signing_storage
StorageAccess GCS_MAVLINK::_signing_storage static private
Definition at line 1054 of file GCS.h.
Referenced by signing_key_load(), and signing_key_save().
[struct]
struct { ... } GCS_MAVLINK::_timesync_request
Referenced by handle_timesync(), send_timesync(), and update_receive().
active
bool GCS_MAVLINK::active
Definition at line 1072 of file GCS.h.
all_stream_entries
const struct stream_entries GCS_MAVLINK::all_stream_entries[] static
Definition at line 479 of file GCS.h.
[struct]
struct { ... } GCS_MAVLINK::alternative
Referenced by GCS::install_alternative_protocol(), and update_receive().
bucket_message_ids_to_send
Bitmask<MSG_LAST> GCS_MAVLINK::bucket_message_ids_to_send private
Definition at line 849 of file GCS.h.
Referenced by find_next_bucket_to_send(), next_deferred_bucket_message_to_send(), remove_message_from_bucket(), set_ap_message_interval(), and update_send().
chan
mavlink_channel_t GCS_MAVLINK::chan protected
Definition at line 509 of file GCS.h.
Referenced by _handle_command_preflight_calibration_baro(), check_payload_size(), disable_channel_routing(), do_try_send_message(), get_chan(), GCS::get_channel_from_port_number(), handle_command_get_message_interval(), handle_command_int(), handle_command_long(), handle_data_packet(), handle_device_op_read(), handle_device_op_write(), handle_file_transfer_protocol(), handle_landing_target(), handle_message(), handle_mission_count(), handle_mission_request_list(), handle_param_request_read(), handle_preflight_reboot(), handle_serial_control(), handle_timesync(), have_flow_control(), init(), is_active(), is_high_bandwidth(), is_private(), load_signing_key(), packet_overhead(), packet_overhead_chan(), packetReceived(), queued_param_send(), save_signing_timestamp(), send_accelcal_vehicle_position(), send_ahrs(), send_ahrs2(), send_attitude(), send_attitude_quaternion(), send_autopilot_state_for_gimbal_device(), send_autopilot_version(), send_distance_sensor(), send_extended_sys_state(), send_ftp_reply(), send_global_position_int(), send_heartbeat(), send_high_latency2(), send_hwstatus(), send_local_position(), send_meminfo(), send_message(), send_message(), GCS::send_message(), send_mission_ack(), send_mission_current(), GCS::send_mission_item_reached_message(), send_named_float(), send_parameter_value(), send_power_status(), send_raw_imu(), send_scaled_imu(), send_scaled_pressure_instance(), send_servo_output_raw(), send_set_position_target_global_int(), send_sys_status(), send_system_time(), send_text(), send_timesync(), send_vfr_hud(), send_vibration(), service_statustext(), GCS::service_statustext(), GCS::set_message_interval(), signing_enabled(), telemetry_delayed(), timesync_receive_timestamp_ns(), try_send_message(), try_send_mission_message(), GCS::update_receive(), update_receive(), GCS::update_send(), and update_signing_timestamp().
chan_is_streaming
uint8_t GCS_MAVLINK::chan_is_streaming = 0 static private
Definition at line 912 of file GCS.h.
Referenced by send_message(), and streaming_channel_mask().
deferred_message
struct GCS_MAVLINK::deferred_message_t GCS_MAVLINK::deferred_message[3] private
Initial value:
= {
        { MSG_HEARTBEAT, },
        { MSG_NEXT_PARAM, },
        { MSG_HIGH_LATENCY2, },
    }
Referenced by deferred_message_to_send_index(), get_ap_message_interval(), get_deferred_message_index(), set_ap_message_interval(), and update_send().
deferred_message_bucket
deferred_message_bucket_t GCS_MAVLINK::deferred_message_bucket[10] private
Definition at line 845 of file GCS.h.
Referenced by find_next_bucket_to_send(), get_ap_message_interval(), next_deferred_bucket_message_to_send(), remove_message_from_bucket(), set_ap_message_interval(), update_receive(), and update_send().
deferred_messages_initialised
bool GCS_MAVLINK::deferred_messages_initialised private
Definition at line 887 of file GCS.h.
Referenced by update_send().
ftp
struct ftp_state GCS_MAVLINK::ftp static private
Definition at line 1009 of file GCS.h.
Referenced by ftp_init(), ftp_worker(), get_reschedule_interval_ms(), handle_file_transfer_protocol(), and send_ftp_reply().
global_position_current_loc
Location GCS_MAVLINK::global_position_current_loc private
Definition at line 1079 of file GCS.h.
Referenced by global_position_int_alt(), send_global_position_int(), send_vfr_hud(), and vfr_hud_alt().
handler
GCS_MAVLINK::protocol_handler_fn_t GCS_MAVLINK::handler
Definition at line 1069 of file GCS.h.
Referenced by GCS::install_alternative_protocol().
interval_ms
const uint16_t GCS_MAVLINK::interval_ms = 10000
Definition at line 635 of file GCS.h.
Referenced by deferred_message_to_send_index(), get_ap_message_interval(), get_reschedule_interval_ms(), handle_command_get_message_interval(), initialise_message_intervals_for_stream(), remove_message_from_bucket(), set_ap_message_interval(), set_mavlink_message_id_interval(), set_message_interval(), update_receive(), and update_send().
is_high_latency_link
bool GCS_MAVLINK::is_high_latency_link
Definition at line 435 of file GCS.h.
Referenced by comm_send_buffer(), GCS_MAVLINK_Dummy::GCS_MAVLINK(), and initialise_message_intervals_from_streamrates().
lag_correction
JitterCorrection GCS_MAVLINK::lag_correction private
Definition at line 1075 of file GCS.h.
Referenced by correct_offboard_timestamp_usec_to_ms().
last_alternate_ms
uint32_t GCS_MAVLINK::last_alternate_ms
Definition at line 1071 of file GCS.h.
last_battery_status_idx
uint8_t GCS_MAVLINK::last_battery_status_idx private
Definition at line 1102 of file GCS.h.
last_deprecation_message
const char* GCS_MAVLINK::last_deprecation_message private
Definition at line 783 of file GCS.h.
Referenced by send_received_message_deprecation_warning().
last_deprecation_warning_send_time_ms
uint32_t GCS_MAVLINK::last_deprecation_warning_send_time_ms private
Definition at line 782 of file GCS.h.
Referenced by send_received_message_deprecation_warning().
last_heartbeat_time
uint32_t GCS_MAVLINK::last_heartbeat_time
Definition at line 315 of file GCS.h.
Referenced by get_last_heartbeat_time(), and try_send_message().
last_mavlink_ms
uint32_t GCS_MAVLINK::last_mavlink_ms
Definition at line 1070 of file GCS.h.
last_mavlink_stats_logged
uint32_t GCS_MAVLINK::last_mavlink_stats_logged private
Definition at line 1100 of file GCS.h.
Referenced by update_receive().
last_radio_status
struct GCS_MAVLINK::LastRadioStatus GCS_MAVLINK::last_radio_status static private
Referenced by handle_radio_status(), last_radio_status_remrssi_ms(), and telemetry_radio_rssi().
last_sent_ms
uint32_t GCS_MAVLINK::last_sent_ms
Definition at line 634 of file GCS.h.
Referenced by remove_message_from_bucket(), and update_send().
last_signing_save_ms
uint32_t GCS_MAVLINK::last_signing_save_ms static private
Definition at line 1052 of file GCS.h.
Referenced by save_signing_timestamp().
last_tx_seq
uint8_t GCS_MAVLINK::last_tx_seq private
Definition at line 1081 of file GCS.h.
Referenced by update_send().
last_txbuf
uint8_t GCS_MAVLINK::last_txbuf = 100 private
Definition at line 813 of file GCS.h.
Referenced by get_last_txbuf(), and handle_radio_status().
magic_force_arm_value
constexpr const float GCS_MAVLINK::magic_force_arm_value = 2989.0f static constexpr protected
Definition at line 727 of file GCS.h.
magic_force_disarm_value
constexpr const float GCS_MAVLINK::magic_force_disarm_value = 21196.0f static constexpr protected
Definition at line 728 of file GCS.h.
mavlink_active
uint8_t GCS_MAVLINK::mavlink_active = 0 static private
Definition at line 906 of file GCS.h.
Referenced by active_channel_mask(), and packetReceived().
mavlink_private
uint8_t GCS_MAVLINK::mavlink_private = 0 static private
Definition at line 909 of file GCS.h.
Referenced by is_private(), private_channel_mask(), and set_channel_private().
mission_item_reached_index
uint16_t GCS_MAVLINK::mission_item_reached_index = AP_MISSION_CMD_INDEX_NONE
Definition at line 323 of file GCS.h.
Referenced by try_send_mission_message().
next_deferred_message_to_send_cache
int8_t GCS_MAVLINK::next_deferred_message_to_send_cache = -1 private
Definition at line 838 of file GCS.h.
Referenced by deferred_message_to_send_index(), and update_send().
no_bucket_to_send
const uint8_t GCS_MAVLINK::no_bucket_to_send = -1 static private
Definition at line 846 of file GCS.h.
Referenced by find_next_bucket_to_send(), is_streaming(), next_deferred_bucket_message_to_send(), and set_ap_message_interval().
no_message_to_send
const ap_message GCS_MAVLINK::no_message_to_send = (ap_message)-1 static private
Definition at line 847 of file GCS.h.
Referenced by next_deferred_bucket_message_to_send(), and update_send().
out_of_space_to_send_count
uint16_t GCS_MAVLINK::out_of_space_to_send_count private
Definition at line 1083 of file GCS.h.
Referenced by out_of_space_to_send().
param_replies
ObjectBuffer< GCS_MAVLINK::pending_param_reply > GCS_MAVLINK::param_replies static private
Definition at line 934 of file GCS.h.
Referenced by param_io_timer(), and send_parameter_async_replies().
param_requests
ObjectBuffer< GCS_MAVLINK::pending_param_request > GCS_MAVLINK::param_requests static private
Definition at line 933 of file GCS.h.
Referenced by handle_param_request_read(), and param_io_timer().
param_timer_registered
bool GCS_MAVLINK::param_timer_registered static private
Definition at line 937 of file GCS.h.
Referenced by handle_param_request_read().
proximity_ever_valid_bitmask
uint8_t GCS_MAVLINK::proximity_ever_valid_bitmask private
Definition at line 1107 of file GCS.h.
pushed_ap_message_ids
Bitmask<MSG_LAST> GCS_MAVLINK::pushed_ap_message_ids private
Definition at line 857 of file GCS.h.
Referenced by send_message(), and update_send().
reserve_param_space_start_ms
uint32_t GCS_MAVLINK::reserve_param_space_start_ms static private
Definition at line 903 of file GCS.h.
Referenced by handle_param_request_read(), packet_overhead_chan(), and send_parameter_async_replies().
routing
MAVLink_routing GCS_MAVLINK::routing static private
Definition at line 915 of file GCS.h.
Referenced by disable_channel_routing(), find_by_mavtype(), find_by_mavtype_and_compid(), find_by_mavtype_and_compid(), packetReceived(), and send_to_components().
sem
HAL_Semaphore GCS_MAVLINK::sem
Definition at line 592 of file GCS.h.
send_packet_count
uint16_t GCS_MAVLINK::send_packet_count private
Definition at line 1082 of file GCS.h.
Referenced by update_send().
sending_bucket_id
uint8_t GCS_MAVLINK::sending_bucket_id = no_bucket_to_send private
Definition at line 848 of file GCS.h.
Referenced by find_next_bucket_to_send(), is_streaming(), next_deferred_bucket_message_to_send(), remove_message_from_bucket(), set_ap_message_interval(), and update_send().
sent_ts1
int64_t GCS_MAVLINK::sent_ts1
Definition at line 633 of file GCS.h.
signing
mavlink_signing_t GCS_MAVLINK::signing private
Definition at line 1050 of file GCS.h.
Referenced by load_signing_key().
signing_streams
mavlink_signing_streams_t GCS_MAVLINK::signing_streams static private
Definition at line 1051 of file GCS.h.
Referenced by load_signing_key().
stream_slowdown_ms
uint16_t GCS_MAVLINK::stream_slowdown_ms private
Definition at line 811 of file GCS.h.
Referenced by get_reschedule_interval_ms(), get_stream_slowdown_ms(), and handle_radio_status().
streamRates
AP_Int16* GCS_MAVLINK::streamRates protected
Definition at line 513 of file GCS.h.
Referenced by GCS_MAVLINK(), get_interval_for_stream(), and handle_request_data_stream().
taken
bool GCS_MAVLINK::taken
Definition at line 593 of file GCS.h.
uartstate
const AP_SerialManager::UARTState* GCS_MAVLINK::uartstate private
Definition at line 760 of file GCS.h.
Referenced by capabilities(), init(), and packetReceived().
The documentation for this class was generated from the following files:
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS.cpp
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/GCS_MAVLink/GCS_DeviceOp.cpp
libraries/GCS_MAVLink/GCS_FTP.cpp
libraries/GCS_MAVLink/GCS_MAVLink.cpp
libraries/GCS_MAVLink/GCS_Param.cpp
libraries/GCS_MAVLink/GCS_serial_control.cpp
libraries/GCS_MAVLink/GCS_Signing.cpp