APM:Libraries: SpeedToFly Class Reference
SpeedToFly Class Reference
#include <SpeedToFly.h>
Public Member Functions
SpeedToFly (const Variometer::PolarParams &polarParams)
void update (float Wx, float Wz, float Wexp, float CLmin, float CLmax)
float speed_to_fly (void)
Private Attributes
float _CL_estimate = -1.0f
const Variometer::PolarParams & _polarParams
Detailed Description
Definition at line 10 of file SpeedToFly.h.
Constructor & Destructor Documentation
SpeedToFly()
SpeedToFly::SpeedToFly (const Variometer::PolarParams & polarParams) inline
Definition at line 17 of file SpeedToFly.h.
Member Function Documentation
speed_to_fly()
float SpeedToFly::speed_to_fly (void) inline
Definition at line 21 of file SpeedToFly.h.
Referenced by SoaringController::get_cruising_target_airspeed(), and SoaringController::update_cruising().
update()
void SpeedToFly::update (float Wx, float Wz, float Wexp, float CLmin, float CLmax)
Definition at line 8 of file SpeedToFly.cpp.
Referenced by SoaringController::update_cruising().
Member Data Documentation
_CL_estimate
float SpeedToFly::_CL_estimate = -1.0f private
Definition at line 12 of file SpeedToFly.h.
Referenced by speed_to_fly(), and update().
_polarParams
const Variometer::PolarParams& SpeedToFly::_polarParams private
Definition at line 14 of file SpeedToFly.h.
Referenced by speed_to_fly(), and update().
The documentation for this class was generated from the following files:
libraries/AP_Soaring/SpeedToFly.h
libraries/AP_Soaring/SpeedToFly.cpp