APM:Libraries: AP_InertialNav Class Reference
AP_InertialNav Class Reference
#include <AP_InertialNav.h>
Public Member Functions
AP_InertialNav (AP_AHRS &ahrs)
void update (bool high_vibes=false)
nav_filter_status get_filter_status () const
const Vector3f & get_position_neu_cm () const
const Vector2f & get_position_xy_cm () const
float get_position_z_up_cm () const
const Vector3f & get_velocity_neu_cms () const
const Vector2f & get_velocity_xy_cms () const
float get_speed_xy_cms () const
float get_velocity_z_up_cms () const
Private Attributes
Vector3f _relpos_cm
Vector3f _velocity_cm
AP_AHRS & _ahrs_ekf
Detailed Description
Definition at line 11 of file AP_InertialNav.h.
Constructor & Destructor Documentation
AP_InertialNav()
AP_InertialNav::AP_InertialNav (AP_AHRS & ahrs) inline
Definition at line 15 of file AP_InertialNav.h.
Member Function Documentation
get_filter_status()
nav_filter_status AP_InertialNav::get_filter_status () const
get_filter_status - returns filter status as a series of flags
get_filter_status : returns filter status as a series of flags
Definition at line 51 of file AP_InertialNav.cpp.
Referenced by AC_AutoTune::position_ok().
get_position_neu_cm()
const Vector3f & AP_InertialNav::get_position_neu_cm (void) const
get_position_neu_cm - returns the current position relative to the EKF origin in cm.
Returns
Definition at line 63 of file AP_InertialNav.cpp.
Referenced by AC_WPNav::advance_wp_target_along_track(), AC_PosControl::get_pos_error_cm(), AC_AutoTune::get_poshold_attitude(), AC_Circle::init_start_angle(), AC_Circle::set_center(), AC_PosControl::standby_xyz_reset(), and AC_PosControl::update_xy_controller().
get_position_xy_cm()
const Vector2f & AP_InertialNav::get_position_xy_cm () const
get_position_xy_cm - returns the current x-y position relative to the EKF origin in cm.
Returns
Definition at line 73 of file AP_InertialNav.cpp.
Referenced by AC_PosControl::crosstrack_error(), AC_PosControl::get_bearing_to_target_cd(), AC_PosControl::get_pos_error_xy_cm(), AC_PosControl::get_stopping_point_xy_cm(), AC_WPNav::get_wp_bearing_to_destination(), AC_WPNav_OA::get_wp_bearing_to_destination(), AC_WPNav::get_wp_distance_to_destination(), AC_WPNav_OA::get_wp_distance_to_destination(), AC_PosControl::handle_ekf_xy_reset(), AC_PosControl::init_xy_controller(), AC_WPNav::shift_wp_origin_and_destination_to_current_pos_xy(), AC_PosControl::soften_for_landing_xy(), AC_PosControl::stop_pos_xy_stabilisation(), AC_PosControl::stop_vel_xy_stabilisation(), and AC_Circle::update().
get_position_z_up_cm()
float AP_InertialNav::get_position_z_up_cm () const
get_position_z_up_cm - returns the current z position relative to the EKF origin, frame z up, in cm.
Returns
get_position_z_up_cm - returns the current z position relative to the EKF origin, frame z-axis up, in cm.
Returns
Definition at line 82 of file AP_InertialNav.cpp.
Referenced by AC_PosControl::get_pos_error_z_cm(), AC_PosControl::get_stopping_point_z_cm(), AC_Circle::get_terrain_offset(), AC_WPNav::get_terrain_offset(), AC_PosControl::handle_ekf_z_reset(), AC_PosControl::init_z_controller(), AC_PosControl::pos_offset_z_scaler(), and AC_PosControl::update_z_controller().
get_speed_xy_cms()
float AP_InertialNav::get_speed_xy_cms () const
get_speed_xy_cms - returns the current horizontal speed in cm/s
Returns
the current horizontal speed in cm/s
Definition at line 115 of file AP_InertialNav.cpp.
get_velocity_neu_cms()
const Vector3f & AP_InertialNav::get_velocity_neu_cms () const
get_velocity_neu_cms - returns the current velocity in cm/s
Returns
velocity vector: .x : latitude velocity in cm/s .y : longitude velocity in cm/s .z : vertical velocity in cm/s
Definition at line 95 of file AP_InertialNav.cpp.
Referenced by AC_WPNav::advance_wp_target_along_track().
get_velocity_xy_cms()
const Vector2f & AP_InertialNav::get_velocity_xy_cms () const
get_velocity_xy_cms - returns the current x-y velocity relative to the EKF origin in cm.
Returns
Definition at line 105 of file AP_InertialNav.cpp.
Referenced by AC_PosControl::get_stopping_point_xy_cm(), AC_PosControl::handle_ekf_xy_reset(), AC_PosControl::init_xy_controller(), AC_PosControl::stop_vel_xy_stabilisation(), and AC_PosControl::update_xy_controller().
get_velocity_z_up_cms()
float AP_InertialNav::get_velocity_z_up_cms () const
get_velocity_z_up_cms - returns the current z-axis velocity, frame z-axis up, in cm/s
Returns
z-axis velocity, frame z-axis up, in cm/s
Definition at line 125 of file AP_InertialNav.cpp.
Referenced by AC_PosControl::get_stopping_point_z_cm(), AC_PosControl::handle_ekf_z_reset(), AC_PosControl::init_z_controller(), and AC_PosControl::update_z_controller().
update()
void AP_InertialNav::update (bool high_vibes = false)
update internal state
Definition at line 14 of file AP_InertialNav.cpp.
Member Data Documentation
_ahrs_ekf
AP_AHRS& AP_InertialNav::_ahrs_ekf private
Definition at line 83 of file AP_InertialNav.h.
Referenced by get_filter_status(), and update().
_relpos_cm
Vector3f AP_InertialNav::_relpos_cm private
Definition at line 81 of file AP_InertialNav.h.
Referenced by get_position_neu_cm(), get_position_xy_cm(), get_position_z_up_cm(), and update().
_velocity_cm
Vector3f AP_InertialNav::_velocity_cm private
Definition at line 82 of file AP_InertialNav.h.
Referenced by get_speed_xy_cms(), get_velocity_neu_cms(), get_velocity_xy_cms(), get_velocity_z_up_cms(), and update().
The documentation for this class was generated from the following files:
libraries/AP_InertialNav/AP_InertialNav.h
libraries/AP_InertialNav/AP_InertialNav.cpp