APM:Libraries: AP_Logger_Flash_JEDEC Class Reference
AP_Logger_Flash_JEDEC Class Reference
#include <AP_Logger_Flash_JEDEC.h>
Public Member Functions
AP_Logger_Flash_JEDEC (AP_Logger &front, LoggerMessageWriter_DFLogStart *writer)
void Init (void) override
bool CardInserted () const override
Public Member Functions inherited from AP_Logger_Block
AP_Logger_Block (AP_Logger &front, LoggerMessageWriter_DFLogStart *writer)
void EraseAll () override
uint16_t find_last_log () override
void get_log_boundaries (uint16_t list_entry, uint32_t &start_page, uint32_t &end_page) override
void get_log_info (uint16_t list_entry, uint32_t &size, uint32_t &time_utc) override
int16_t get_log_data (uint16_t list_entry, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data) override WARN_IF_UNUSED
uint16_t get_num_logs () override
void start_new_log (void) override
uint32_t bufferspace_available () override
void stop_logging (void) override
void stop_logging_async (void) override
bool logging_failed () const override
bool logging_started (void) const override
void io_timer (void) override
Public Member Functions inherited from AP_Logger_Backend
FUNCTOR_TYPEDEF (vehicle_startup_message_Writer, void)
AP_Logger_Backend (AP_Logger &front, class LoggerMessageWriter_DFLogStart *writer)
vehicle_startup_message_Writer vehicle_message_writer () const
bool WriteBlock (const void *pBuffer, uint16_t size)
bool WriteCriticalBlock (const void *pBuffer, uint16_t size)
bool WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical, bool writev_streaming=false)
virtual uint16_t find_oldest_log ()
virtual void PrepForArming ()
void Fill_Format (const struct LogStructure *structure, struct log_Format &pkt)
void Fill_Format_Units (const struct LogStructure *s, struct log_Format_Units &pkt)
virtual void flush (void)
virtual void remote_log_block_status_msg (const class GCS_MAVLINK &link, const mavlink_message_t &msg)
virtual void periodic_tasks ()
uint8_t num_types () const
const struct LogStructure * structure (uint8_t structure) const
uint8_t num_units () const
const struct UnitStructure * unit (uint8_t unit) const
uint8_t num_multipliers () const
const struct MultiplierStructure * multiplier (uint8_t multiplier) const
bool Write_EntireMission ()
bool Write_RallyPoint (uint8_t total, uint8_t sequence, const class RallyLocation &rally_point)
bool Write_Rally ()
bool Write_Format (const struct LogStructure *structure)
bool Write_Message (const char *message)
bool Write_MessageF (const char *fmt,...)
bool Write_Mission_Cmd (const AP_Mission &mission, const AP_Mission::Mission_Command &cmd)
bool Write_Mode (uint8_t mode, const ModeReason reason)
bool Write_Parameter (const char *name, float value, float default_val)
bool Write_Parameter (const AP_Param *ap, const AP_Param::ParamToken &token, enum ap_var_type type, float default_val)
bool Write_VER ()
uint32_t num_dropped (void) const
bool Write_Emit_FMT (uint8_t msg_type)
bool Write (uint8_t msg_type, va_list arg_list, bool is_critical=false, bool is_streaming=false)
virtual bool logging_enabled () const
bool allow_start_ekf () const
virtual void vehicle_was_disarmed ()
bool Write_Unit (const struct UnitStructure *s)
bool Write_Multiplier (const struct MultiplierStructure *s)
bool Write_Format_Units (const struct LogStructure *structure)
Static Public Member Functions
static AP_Logger_Backend * probe (AP_Logger &front, LoggerMessageWriter_DFLogStart *ls)
Private Member Functions
void BufferToPage (uint32_t PageAdr) override
void PageToBuffer (uint32_t PageAdr) override
void SectorErase (uint32_t SectorAdr) override
void Sector4kErase (uint32_t SectorAdr) override
void StartErase () override
bool InErase () override
void send_command_addr (uint8_t cmd, uint32_t address)
void WaitReady ()
bool Busy ()
uint8_t ReadStatusReg ()
void Enter4ByteAddressMode (void)
void WriteEnable ()
bool getSectorCount (void)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev
AP_HAL::Semaphore * dev_sem
bool flash_died
uint32_t erase_start_ms
uint8_t erase_cmd
bool use_32bit_address
bool read_cache_valid
Additional Inherited Members
Protected Member Functions inherited from AP_Logger_Block
bool _WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical) override
void periodic_1Hz () override
void periodic_10Hz (const uint32_t now) override
bool WritesOK () const override
uint32_t get_sector (uint32_t current_page) const
uint32_t get_block (uint32_t current_page) const
Protected Member Functions inherited from AP_Logger_Backend
virtual void periodic_fullrate ()
bool ShouldLog (bool is_critical)
virtual bool StartNewLogOK () const
virtual void PrepForArming_start_logging (void)
virtual bool WriteBlockCheckStartupMessages ()
virtual void WriteMoreStartupMessages ()
virtual void push_log_blocks ()
virtual void start_new_log_reset_variables ()
uint16_t log_num_from_list_entry (const uint16_t list_entry)
uint32_t critical_message_reserved_space (uint32_t bufsize) const
uint32_t non_messagewriter_message_reserved_space (uint32_t bufsize) const
void df_stats_gather (uint16_t bytes_written, uint32_t space_remaining)
void df_stats_log ()
void df_stats_clear ()
Protected Attributes inherited from AP_Logger_Block
uint32_t df_PageSize
uint16_t df_PagePerBlock
uint16_t df_PagePerSector
uint32_t df_NumPages
volatile bool log_write_started
uint8_t * buffer
uint32_t last_messagewrite_message_sent
uint32_t df_Read_PageAdr
Protected Attributes inherited from AP_Logger_Backend
AP_Logger & _front
LoggerMessageWriter_DFLogStart * _startup_messagewriter
bool _writing_startup_messages
uint16_t _cached_oldest_log
uint32_t _dropped
uint32_t _log_file_size_bytes
bool _rotate_pending
bool _initialised
AP_Logger_RateLimiter * rate_limiter
Detailed Description
Definition at line 12 of file AP_Logger_Flash_JEDEC.h.
Constructor & Destructor Documentation
AP_Logger_Flash_JEDEC()
AP_Logger_Flash_JEDEC::AP_Logger_Flash_JEDEC (AP_Logger & front, LoggerMessageWriter_DFLogStart * writer) inline
Definition at line 14 of file AP_Logger_Flash_JEDEC.h.
Referenced by probe().
Member Function Documentation
BufferToPage()
void AP_Logger_Flash_JEDEC::BufferToPage (uint32_t PageAdr) override private virtual
Implements AP_Logger_Block.
Definition at line 247 of file AP_Logger_Flash_JEDEC.cpp.
Busy()
bool AP_Logger_Flash_JEDEC::Busy () private
Definition at line 183 of file AP_Logger_Flash_JEDEC.cpp.
Referenced by InErase(), and WaitReady().
CardInserted()
bool AP_Logger_Flash_JEDEC::CardInserted (void) const inline override virtual
Implements AP_Logger_Block.
Definition at line 21 of file AP_Logger_Flash_JEDEC.h.
Enter4ByteAddressMode()
void AP_Logger_Flash_JEDEC::Enter4ByteAddressMode (void) private
Definition at line 188 of file AP_Logger_Flash_JEDEC.cpp.
Referenced by Init().
getSectorCount()
bool AP_Logger_Flash_JEDEC::getSectorCount (void) private
Definition at line 106 of file AP_Logger_Flash_JEDEC.cpp.
Referenced by Init().
InErase()
bool AP_Logger_Flash_JEDEC::InErase () override private virtual
Implements AP_Logger_Block.
Definition at line 309 of file AP_Logger_Flash_JEDEC.cpp.
Init()
void AP_Logger_Flash_JEDEC::Init (void) override virtual
Reimplemented from AP_Logger_Block.
Definition at line 60 of file AP_Logger_Flash_JEDEC.cpp.
PageToBuffer()
void AP_Logger_Flash_JEDEC::PageToBuffer (uint32_t PageAdr) override private virtual
Implements AP_Logger_Block.
Definition at line 218 of file AP_Logger_Flash_JEDEC.cpp.
probe()
static AP_Logger_Backend * AP_Logger_Flash_JEDEC::probe (AP_Logger & front, LoggerMessageWriter_DFLogStart * ls) inline static
Definition at line 16 of file AP_Logger_Flash_JEDEC.h.
ReadStatusReg()
uint8_t AP_Logger_Flash_JEDEC::ReadStatusReg () private
Definition at line 174 of file AP_Logger_Flash_JEDEC.cpp.
Referenced by Busy().
Sector4kErase()
void AP_Logger_Flash_JEDEC::Sector4kErase (uint32_t SectorAdr) override private virtual
Implements AP_Logger_Block.
Definition at line 287 of file AP_Logger_Flash_JEDEC.cpp.
SectorErase()
void AP_Logger_Flash_JEDEC::SectorErase (uint32_t SectorAdr) override private virtual
Implements AP_Logger_Block.
Definition at line 274 of file AP_Logger_Flash_JEDEC.cpp.
send_command_addr()
void AP_Logger_Flash_JEDEC::send_command_addr (uint8_t cmd, uint32_t address) private
Definition at line 199 of file AP_Logger_Flash_JEDEC.cpp.
Referenced by BufferToPage(), PageToBuffer(), Sector4kErase(), and SectorErase().
StartErase()
void AP_Logger_Flash_JEDEC::StartErase () override private virtual
Implements AP_Logger_Block.
Definition at line 296 of file AP_Logger_Flash_JEDEC.cpp.
WaitReady()
void AP_Logger_Flash_JEDEC::WaitReady () private
Definition at line 89 of file AP_Logger_Flash_JEDEC.cpp.
Referenced by getSectorCount(), PageToBuffer(), and WriteEnable().
WriteEnable()
void AP_Logger_Flash_JEDEC::WriteEnable (void) private
Definition at line 318 of file AP_Logger_Flash_JEDEC.cpp.
Referenced by BufferToPage(), Sector4kErase(), SectorErase(), and StartErase().
Member Data Documentation
dev
AP_HAL::OwnPtr<AP_HAL::SPIDevice> AP_Logger_Flash_JEDEC::dev private
Definition at line 39 of file AP_Logger_Flash_JEDEC.h.
Referenced by BufferToPage(), Enter4ByteAddressMode(), getSectorCount(), Init(), PageToBuffer(), ReadStatusReg(), send_command_addr(), StartErase(), and WriteEnable().
dev_sem
AP_HAL::Semaphore* AP_Logger_Flash_JEDEC::dev_sem private
Definition at line 40 of file AP_Logger_Flash_JEDEC.h.
Referenced by BufferToPage(), Enter4ByteAddressMode(), getSectorCount(), Init(), PageToBuffer(), ReadStatusReg(), Sector4kErase(), SectorErase(), StartErase(), and WriteEnable().
erase_cmd
uint8_t AP_Logger_Flash_JEDEC::erase_cmd private
Definition at line 44 of file AP_Logger_Flash_JEDEC.h.
Referenced by getSectorCount(), and SectorErase().
erase_start_ms
uint32_t AP_Logger_Flash_JEDEC::erase_start_ms private
Definition at line 43 of file AP_Logger_Flash_JEDEC.h.
Referenced by InErase(), and StartErase().
flash_died
bool AP_Logger_Flash_JEDEC::flash_died private
Definition at line 42 of file AP_Logger_Flash_JEDEC.h.
Referenced by CardInserted(), Init(), and WaitReady().
read_cache_valid
bool AP_Logger_Flash_JEDEC::read_cache_valid private
Definition at line 46 of file AP_Logger_Flash_JEDEC.h.
Referenced by BufferToPage(), and PageToBuffer().
use_32bit_address
bool AP_Logger_Flash_JEDEC::use_32bit_address private
Definition at line 45 of file AP_Logger_Flash_JEDEC.h.
Referenced by getSectorCount(), Init(), and send_command_addr().
The documentation for this class was generated from the following files:
libraries/AP_Logger/AP_Logger_Flash_JEDEC.h
libraries/AP_Logger/AP_Logger_Flash_JEDEC.cpp