APM:Libraries: AC_AttitudeControl Class Reference
AC_AttitudeControl Class Reference abstract
#include <AC_AttitudeControl.h>
Classes
struct HeadingCommand
Public Types
enum class HeadingMode { Angle_Only , Angle_And_Rate , Rate_Only }
Public Member Functions
AC_AttitudeControl (AP_AHRS_View &ahrs, const AP_MultiCopter &aparm, AP_Motors &motors)
virtual ~AC_AttitudeControl ()
void set_dt (float dt)
float get_dt () const
AC_P & get_angle_roll_p ()
AC_P & get_angle_pitch_p ()
AC_P & get_angle_yaw_p ()
virtual AC_PID & get_rate_roll_pid ()=0
virtual AC_PID & get_rate_pitch_pid ()=0
virtual AC_PID & get_rate_yaw_pid ()=0
virtual const AC_PID & get_rate_roll_pid () const =0
virtual const AC_PID & get_rate_pitch_pid () const =0
virtual const AC_PID & get_rate_yaw_pid () const =0
float get_accel_roll_max_cdss () const
float get_accel_roll_max_radss () const
void set_accel_roll_max_cdss (float accel_roll_max)
void save_accel_roll_max_cdss (float accel_roll_max)
float get_accel_pitch_max_cdss () const
float get_accel_pitch_max_radss () const
void set_accel_pitch_max_cdss (float accel_pitch_max)
void save_accel_pitch_max_cdss (float accel_pitch_max)
float get_accel_yaw_max_cdss () const
float get_accel_yaw_max_radss () const
void set_accel_yaw_max_cdss (float accel_yaw_max)
void save_accel_yaw_max_cdss (float accel_yaw_max)
float get_ang_vel_roll_max_rads () const
float get_ang_vel_pitch_max_rads () const
float get_ang_vel_yaw_max_rads () const
float get_slew_yaw_max_degs () const
float get_input_tc () const
void set_input_tc (float input_tc)
void relax_attitude_controllers ()
virtual void relax_attitude_controllers (bool exclude_pitch)
void reset_rate_controller_I_terms ()
void reset_rate_controller_I_terms_smoothly ()
void reset_target_and_rate (bool reset_rate=true)
void reset_yaw_target_and_rate (bool reset_rate=true)
void inertial_frame_reset ()
virtual void input_quaternion (Quaternion &attitude_desired_quat, Vector3f ang_vel_target)
virtual void input_euler_angle_roll_pitch_euler_rate_yaw (float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_rate_cds)
virtual void input_euler_angle_roll_pitch_yaw (float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_angle_cd, bool slew_yaw)
virtual void input_euler_rate_yaw_euler_angle_pitch_bf_roll (bool plane_controls, float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_rate_cds)
virtual void input_euler_rate_roll_pitch_yaw (float euler_roll_rate_cds, float euler_pitch_rate_cds, float euler_yaw_rate_cds)
virtual void input_rate_bf_roll_pitch_yaw (float roll_rate_bf_cds, float pitch_rate_bf_cds, float yaw_rate_bf_cds)
virtual void input_rate_bf_roll_pitch_yaw_2 (float roll_rate_bf_cds, float pitch_rate_bf_cds, float yaw_rate_bf_cds)
virtual void input_rate_bf_roll_pitch_yaw_3 (float roll_rate_bf_cds, float pitch_rate_bf_cds, float yaw_rate_bf_cds)
virtual void input_angle_step_bf_roll_pitch_yaw (float roll_angle_step_bf_cd, float pitch_angle_step_bf_cd, float yaw_angle_step_bf_cd)
virtual void input_thrust_vector_rate_heading (const Vector3f &thrust_vector, float heading_rate_cds, bool slew_yaw=true)
virtual void input_thrust_vector_heading (const Vector3f &thrust_vector, float heading_angle_cd, float heading_rate_cds)
void input_thrust_vector_heading (const Vector3f &thrust_vector, float heading_cd)
Quaternion attitude_from_thrust_vector (Vector3f thrust_vector, float heading_angle) const
virtual void rate_controller_run ()=0
void euler_rate_to_ang_vel (const Vector3f &euler_rad, const Vector3f &euler_rate_rads, Vector3f &ang_vel_rads)
bool ang_vel_to_euler_rate (const Vector3f &euler_rad, const Vector3f &ang_vel_rads, Vector3f &euler_rate_rads)
void use_sqrt_controller (bool use_sqrt_cont)
Vector3f get_att_target_euler_cd () const
const Vector3f & get_att_target_euler_rad () const
Quaternion get_attitude_target_quat () const
const Vector3f & get_attitude_target_ang_vel () const
float get_att_error_angle_deg () const
void rate_bf_roll_target (float rate_cds)
void rate_bf_pitch_target (float rate_cds)
void rate_bf_yaw_target (float rate_cds)
void rate_bf_roll_sysid (float rate)
void rate_bf_pitch_sysid (float rate)
void rate_bf_yaw_sysid (float rate)
void actuator_roll_sysid (float command)
void actuator_pitch_sysid (float command)
void actuator_yaw_sysid (float command)
float max_rate_step_bf_roll ()
float max_rate_step_bf_pitch ()
float max_rate_step_bf_yaw ()
float max_angle_step_bf_roll ()
float max_angle_step_bf_pitch ()
float max_angle_step_bf_yaw ()
Vector3f rate_bf_targets () const
const Vector3f & get_rate_ef_targets () const
void bf_feedforward (bool enable_or_disable)
void bf_feedforward_save (bool enable_or_disable)
bool get_bf_feedforward ()
void accel_limiting (bool enable_or_disable)
virtual void update_althold_lean_angle_max (float throttle_in)=0
virtual void set_throttle_out (float throttle_in, bool apply_angle_boost, float filt_cutoff)=0
float get_throttle_in () const
float angle_boost () const
virtual float get_althold_lean_angle_max_cd () const
float lean_angle_max_cd () const
float lean_angle_deg () const
void input_shaping_rate_predictor (const Vector2f &error_angle, Vector2f &target_ang_vel, float dt) const
void ang_vel_limit (Vector3f &euler_rad, float ang_vel_roll_max, float ang_vel_pitch_max, float ang_vel_yaw_max) const
Vector3f euler_accel_limit (const Vector3f &euler_rad, const Vector3f &euler_accel)
void attitude_controller_run_quat ()
void thrust_heading_rotation_angles (Quaternion &attitude_target, const Quaternion &attitude_body, Vector3f &attitude_error, float &thrust_angle, float &thrust_error_angle) const
void thrust_vector_rotation_angles (const Quaternion &attitude_target, const Quaternion &attitude_body, Quaternion &thrust_vector_correction, Vector3f &attitude_error, float &thrust_angle, float &thrust_error_angle) const
virtual void parameter_sanity_check ()
virtual void set_notch_sample_rate (float sample_rate)
virtual bool is_throttle_mix_min () const
virtual void set_throttle_mix_min ()
virtual void set_throttle_mix_man ()
virtual void set_throttle_mix_max (float ratio)
virtual void set_throttle_mix_value (float value)
virtual float get_throttle_mix (void) const
virtual void use_flybar_passthrough (bool passthrough, bool tail_passthrough)
virtual void use_leaky_i (bool leaky_i)
virtual void set_hover_roll_trim_scalar (float scalar)
virtual float get_roll_trim_cd ()
virtual void passthrough_bf_roll_pitch_rate_yaw (float roll_passthrough, float pitch_passthrough, float yaw_rate_bf_cds)
bool pre_arm_checks (const char *param_prefix, char *failure_msg, const uint8_t failure_msg_len)
virtual void set_inverted_flight (bool inverted)
void get_rpy_srate (float &roll_srate, float &pitch_srate, float &yaw_srate)
void set_roll_pitch_rate_tc (float input_tc)
void set_yaw_rate_tc (float input_tc)
void set_angle_P_scale (const Vector3f &angle_P_scale)
void set_angle_P_scale_mult (const Vector3f &angle_P_scale)
const Vector3f & get_last_angle_P_scale (void) const
void set_PD_scale_mult (const Vector3f &pd_scale)
const Vector3f & get_PD_scale_logging (void) const
void control_monitor_log (void) const
float control_monitor_rms_output_roll (void) const
float control_monitor_rms_output_roll_P (void) const
float control_monitor_rms_output_roll_D (void) const
float control_monitor_rms_output_pitch_P (void) const
float control_monitor_rms_output_pitch_D (void) const
float control_monitor_rms_output_pitch (void) const
float control_monitor_rms_output_yaw (void) const
void input_thrust_vector_heading (const Vector3f &thrust_vector, HeadingCommand heading)
Static Public Member Functions
static AC_AttitudeControl * get_singleton (void)
static float input_shaping_angle (float error_angle, float input_tc, float accel_max, float target_ang_vel, float desired_ang_vel, float max_ang_vel, float dt)
static float input_shaping_angle (float error_angle, float input_tc, float accel_max, float target_ang_vel, float dt)
static float input_shaping_ang_vel (float target_ang_vel, float desired_ang_vel, float accel_max, float dt, float input_tc)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
static constexpr Vector3f VECTORF_111 {1.0f,1.0f,1.0f}
Protected Member Functions
Vector3f update_ang_vel_target_from_att_error (const Vector3f &attitude_error_rot_vec_rad)
virtual float get_roll_trim_rad ()
float get_slew_yaw_max_rads () const
void control_monitor_filter_pid (float value, float &rms_P)
void control_monitor_update (void)
Protected Attributes
AP_Float _slew_yaw
AP_Float _ang_vel_roll_max
AP_Float _ang_vel_pitch_max
AP_Float _ang_vel_yaw_max
AP_Float _accel_roll_max
AP_Float _accel_pitch_max
AP_Float _accel_yaw_max
AP_Int8 _rate_bf_ff_enabled
AP_Int8 _angle_boost_enabled
AC_P _p_angle_roll
AC_P _p_angle_pitch
AC_P _p_angle_yaw
AP_Float _angle_limit_tc
AP_Float _input_tc
float _dt
Vector3f _euler_angle_target
Vector3f _euler_rate_target
Quaternion _attitude_target
Vector3f _ang_vel_target
Vector3f _ang_vel_body
Vector3f _sysid_ang_vel_body
Vector3f _actuator_sysid
Quaternion _attitude_ang_error
float _thrust_angle
float _thrust_error_angle
float _throttle_in = 0.0f
float _angle_boost
bool _use_sqrt_controller
float _althold_lean_angle_max = 0.0f
float _throttle_rpy_mix_desired
float _throttle_rpy_mix
float _feedforward_scalar = 1.0f
float _rate_rp_tc
float _rate_y_tc
Vector3f _angle_P_scale {1,1,1}
Vector3f _angle_P_scale_used
Vector3f _pd_scale {1,1,1}
Vector3f _pd_scale_used
const AP_AHRS_View & _ahrs
const AP_MultiCopter & _aparm
AP_Motors & _motors
struct {
float rms_roll_P
float rms_roll_D
float rms_pitch_P
float rms_pitch_D
float rms_yaw
} _control_monitor
Static Protected Attributes
static AC_AttitudeControl * _singleton
Detailed Description
Definition at line 47 of file AC_AttitudeControl.h.
Member Enumeration Documentation
HeadingMode
enum class AC_AttitudeControl::HeadingMode strong
Enumerator
Angle_Only
Angle_And_Rate
Rate_Only
Definition at line 583 of file AC_AttitudeControl.h.
Constructor & Destructor Documentation
AC_AttitudeControl()
AC_AttitudeControl::AC_AttitudeControl (AP_AHRS_View & ahrs, const AP_MultiCopter & aparm, AP_Motors & motors) inline
Definition at line 49 of file AC_AttitudeControl.h.
~AC_AttitudeControl()
virtual AC_AttitudeControl::~AC_AttitudeControl () inline virtual
Definition at line 72 of file AC_AttitudeControl.h.
Member Function Documentation
accel_limiting()
void AC_AttitudeControl::accel_limiting (bool enable_or_disable)
Definition at line 1048 of file AC_AttitudeControl.cpp.
actuator_pitch_sysid()
void AC_AttitudeControl::actuator_pitch_sysid (float command) inline
Definition at line 251 of file AC_AttitudeControl.h.
actuator_roll_sysid()
void AC_AttitudeControl::actuator_roll_sysid (float command) inline
Definition at line 248 of file AC_AttitudeControl.h.
actuator_yaw_sysid()
void AC_AttitudeControl::actuator_yaw_sysid (float command) inline
Definition at line 254 of file AC_AttitudeControl.h.
ang_vel_limit()
void AC_AttitudeControl::ang_vel_limit (Vector3f & euler_rad, float ang_vel_roll_max, float ang_vel_pitch_max, float ang_vel_yaw_max) const
Definition at line 888 of file AC_AttitudeControl.cpp.
Referenced by attitude_controller_run_quat(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_quaternion(), input_shaping_rate_predictor(), input_thrust_vector_heading(), and input_thrust_vector_rate_heading().
ang_vel_to_euler_rate()
bool AC_AttitudeControl::ang_vel_to_euler_rate (const Vector3f & euler_rad, const Vector3f & ang_vel_rads, Vector3f & euler_rate_rads)
Definition at line 993 of file AC_AttitudeControl.cpp.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), relax_attitude_controllers(), and AC_AttitudeControl_TS::relax_attitude_controllers().
angle_boost()
float AC_AttitudeControl::angle_boost () const inline
Definition at line 302 of file AC_AttitudeControl.h.
attitude_controller_run_quat()
void AC_AttitudeControl::attitude_controller_run_quat ()
Definition at line 708 of file AC_AttitudeControl.cpp.
Referenced by input_angle_step_bf_roll_pitch_yaw(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_thrust_vector_heading(), and input_thrust_vector_rate_heading().
attitude_from_thrust_vector()
Quaternion AC_AttitudeControl::attitude_from_thrust_vector (Vector3f thrust_vector, float heading_angle) const
Definition at line 676 of file AC_AttitudeControl.cpp.
Referenced by input_thrust_vector_heading(), and input_thrust_vector_rate_heading().
bf_feedforward()
void AC_AttitudeControl::bf_feedforward (bool enable_or_disable) inline
Definition at line 281 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::load_intra_test_gains(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Heli::load_orig_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Heli::load_tuned_gains(), AC_AutoTune_Multi::load_tuned_gains(), AC_AutoTune_Heli::test_init(), and AC_AutoTune_Heli::updating_angle_p_up_all().
bf_feedforward_save()
void AC_AttitudeControl::bf_feedforward_save (bool enable_or_disable) inline
Definition at line 284 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::save_tuning_gains(), and AC_AutoTune_Multi::save_tuning_gains().
control_monitor_filter_pid()
void AC_AttitudeControl::control_monitor_filter_pid (float value, float & rms_P) protected
Definition at line 15 of file ControlMonitor.cpp.
Referenced by control_monitor_update().
control_monitor_log()
void AC_AttitudeControl::control_monitor_log (void) const
control_monitor_rms_output_pitch()
float AC_AttitudeControl::control_monitor_rms_output_pitch (void) const
Definition at line 92 of file ControlMonitor.cpp.
control_monitor_rms_output_pitch_D()
float AC_AttitudeControl::control_monitor_rms_output_pitch_D (void) const
Definition at line 108 of file ControlMonitor.cpp.
control_monitor_rms_output_pitch_P()
float AC_AttitudeControl::control_monitor_rms_output_pitch_P (void) const
Definition at line 100 of file ControlMonitor.cpp.
control_monitor_rms_output_roll()
float AC_AttitudeControl::control_monitor_rms_output_roll (void) const
Definition at line 68 of file ControlMonitor.cpp.
control_monitor_rms_output_roll_D()
float AC_AttitudeControl::control_monitor_rms_output_roll_D (void) const
Definition at line 84 of file ControlMonitor.cpp.
control_monitor_rms_output_roll_P()
float AC_AttitudeControl::control_monitor_rms_output_roll_P (void) const
Definition at line 76 of file ControlMonitor.cpp.
control_monitor_rms_output_yaw()
float AC_AttitudeControl::control_monitor_rms_output_yaw (void) const
Definition at line 116 of file ControlMonitor.cpp.
control_monitor_update()
void AC_AttitudeControl::control_monitor_update (void) protected
Definition at line 26 of file ControlMonitor.cpp.
Referenced by AC_AttitudeControl_Multi::rate_controller_run(), and AC_AttitudeControl_Sub::rate_controller_run().
euler_accel_limit()
Vector3f AC_AttitudeControl::euler_accel_limit (const Vector3f & euler_rad, const Vector3f & euler_accel)
Definition at line 911 of file AC_AttitudeControl.cpp.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), and input_euler_rate_roll_pitch_yaw().
euler_rate_to_ang_vel()
void AC_AttitudeControl::euler_rate_to_ang_vel (const Vector3f & euler_rad, const Vector3f & euler_rate_rads, Vector3f & ang_vel_rads)
Definition at line 979 of file AC_AttitudeControl.cpp.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), and reset_yaw_target_and_rate().
get_accel_pitch_max_cdss()
float AC_AttitudeControl::get_accel_pitch_max_cdss () const inline
Definition at line 102 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AC_AutoTune_Heli::save_tuning_gains(), and AC_AutoTune_Multi::save_tuning_gains().
get_accel_pitch_max_radss()
float AC_AttitudeControl::get_accel_pitch_max_radss () const inline
Definition at line 103 of file AC_AttitudeControl.h.
Referenced by AC_WPNav::calc_scurve_jerk_and_snap(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), input_shaping_rate_predictor(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), AC_PosControl::set_max_speed_accel_xy(), and update_ang_vel_target_from_att_error().
get_accel_roll_max_cdss()
float AC_AttitudeControl::get_accel_roll_max_cdss () const inline
Definition at line 92 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AC_AutoTune_Heli::save_tuning_gains(), and AC_AutoTune_Multi::save_tuning_gains().
get_accel_roll_max_radss()
float AC_AttitudeControl::get_accel_roll_max_radss () const inline
Definition at line 93 of file AC_AttitudeControl.h.
Referenced by AC_WPNav::calc_scurve_jerk_and_snap(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), input_shaping_rate_predictor(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), AC_PosControl::set_max_speed_accel_xy(), and update_ang_vel_target_from_att_error().
get_accel_yaw_max_cdss()
float AC_AttitudeControl::get_accel_yaw_max_cdss () const inline
Definition at line 112 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AC_AutoTune_Heli::save_tuning_gains(), and AC_AutoTune_Multi::save_tuning_gains().
get_accel_yaw_max_radss()
float AC_AttitudeControl::get_accel_yaw_max_radss () const inline
Definition at line 113 of file AC_AttitudeControl.h.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), thrust_heading_rotation_angles(), and update_ang_vel_target_from_att_error().
get_althold_lean_angle_max_cd()
float AC_AttitudeControl::get_althold_lean_angle_max_cd () const virtual
Definition at line 1069 of file AC_AttitudeControl.cpp.
Referenced by AC_PosControl::init_xy_controller(), and AC_PosControl::update_xy_controller().
get_ang_vel_pitch_max_rads()
float AC_AttitudeControl::get_ang_vel_pitch_max_rads () const inline
Definition at line 125 of file AC_AttitudeControl.h.
Referenced by AC_WPNav::calc_scurve_jerk_and_snap(), max_rate_step_bf_pitch(), and AC_PosControl::set_max_speed_accel_xy().
get_ang_vel_roll_max_rads()
float AC_AttitudeControl::get_ang_vel_roll_max_rads () const inline
Definition at line 122 of file AC_AttitudeControl.h.
Referenced by AC_WPNav::calc_scurve_jerk_and_snap(), max_rate_step_bf_roll(), and AC_PosControl::set_max_speed_accel_xy().
get_ang_vel_yaw_max_rads()
float AC_AttitudeControl::get_ang_vel_yaw_max_rads () const inline
Definition at line 128 of file AC_AttitudeControl.h.
Referenced by max_rate_step_bf_yaw().
get_angle_pitch_p()
AC_P & AC_AttitudeControl::get_angle_pitch_p () inline
Definition at line 82 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), pre_arm_checks(), AC_AutoTune_Heli::save_tuning_gains(), and AC_AutoTune_Multi::save_tuning_gains().
get_angle_roll_p()
AC_P & AC_AttitudeControl::get_angle_roll_p () inline
Definition at line 81 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), pre_arm_checks(), AC_AutoTune_Heli::save_tuning_gains(), and AC_AutoTune_Multi::save_tuning_gains().
get_angle_yaw_p()
AC_P & AC_AttitudeControl::get_angle_yaw_p () inline
Definition at line 83 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), pre_arm_checks(), AC_AutoTune_Heli::save_tuning_gains(), and AC_AutoTune_Multi::save_tuning_gains().
get_att_error_angle_deg()
float AC_AttitudeControl::get_att_error_angle_deg () const inline
Definition at line 227 of file AC_AttitudeControl.h.
get_att_target_euler_cd()
Vector3f AC_AttitudeControl::get_att_target_euler_cd () const inline
Definition at line 217 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::dwell_test_run(), and AC_PosControl::init_xy_controller().
get_att_target_euler_rad()
const Vector3f & AC_AttitudeControl::get_att_target_euler_rad () const inline
Definition at line 218 of file AC_AttitudeControl.h.
Referenced by AC_PosControl::lean_angles_to_accel_xy().
get_attitude_target_ang_vel()
const Vector3f & AC_AttitudeControl::get_attitude_target_ang_vel () const inline
Definition at line 224 of file AC_AttitudeControl.h.
get_attitude_target_quat()
Quaternion AC_AttitudeControl::get_attitude_target_quat () const inline
Definition at line 221 of file AC_AttitudeControl.h.
get_bf_feedforward()
bool AC_AttitudeControl::get_bf_feedforward () inline
Definition at line 287 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), AC_AutoTune_Heli::load_tuned_gains(), AC_AutoTune_Multi::load_tuned_gains(), AC_AutoTune_Heli::save_tuning_gains(), AC_AutoTune_Multi::save_tuning_gains(), and AC_PosControl::set_max_speed_accel_xy().
get_dt()
float AC_AttitudeControl::get_dt () const inline
Definition at line 78 of file AC_AttitudeControl.h.
Referenced by AC_Loiter::set_pilot_desired_acceleration().
get_input_tc()
float AC_AttitudeControl::get_input_tc () const inline
Definition at line 134 of file AC_AttitudeControl.h.
Referenced by AC_WPNav::calc_scurve_jerk_and_snap(), and AC_AutoTune_Heli::dwell_test_run().
get_last_angle_P_scale()
const Vector3f & AC_AttitudeControl::get_last_angle_P_scale (void) const inline
Definition at line 402 of file AC_AttitudeControl.h.
get_PD_scale_logging()
const Vector3f & AC_AttitudeControl::get_PD_scale_logging (void) const inline
Definition at line 411 of file AC_AttitudeControl.h.
get_rate_ef_targets()
const Vector3f & AC_AttitudeControl::get_rate_ef_targets () const inline
Definition at line 278 of file AC_AttitudeControl.h.
get_rate_pitch_pid() [1/2]
virtual const AC_PID & AC_AttitudeControl::get_rate_pitch_pid () const pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
get_rate_pitch_pid() [2/2]
virtual AC_PID & AC_AttitudeControl::get_rate_pitch_pid () pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), control_monitor_update(), AC_AutoTune_Heli::dwell_test_init(), AC_AutoTune_Heli::dwell_test_run(), get_rpy_srate(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), max_rate_step_bf_pitch(), pre_arm_checks(), relax_attitude_controllers(), reset_rate_controller_I_terms(), reset_rate_controller_I_terms_smoothly(), AC_AutoTune_Heli::save_tuning_gains(), AC_AutoTune_Multi::save_tuning_gains(), and AC_AutoTune_Multi::twitch_test_init().
get_rate_roll_pid() [1/2]
virtual const AC_PID & AC_AttitudeControl::get_rate_roll_pid () const pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
get_rate_roll_pid() [2/2]
virtual AC_PID & AC_AttitudeControl::get_rate_roll_pid () pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), control_monitor_update(), AC_AutoTune_Heli::dwell_test_init(), AC_AutoTune_Heli::dwell_test_run(), get_rpy_srate(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), max_rate_step_bf_roll(), pre_arm_checks(), relax_attitude_controllers(), reset_rate_controller_I_terms(), reset_rate_controller_I_terms_smoothly(), AC_AutoTune_Heli::save_tuning_gains(), AC_AutoTune_Multi::save_tuning_gains(), and AC_AutoTune_Multi::twitch_test_init().
get_rate_yaw_pid() [1/2]
virtual const AC_PID & AC_AttitudeControl::get_rate_yaw_pid () const pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
get_rate_yaw_pid() [2/2]
virtual AC_PID & AC_AttitudeControl::get_rate_yaw_pid () pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Referenced by AC_AutoTune_Heli::backup_gains_and_initialise(), AC_AutoTune_Multi::backup_gains_and_initialise(), control_monitor_update(), AC_AutoTune_Heli::dwell_test_init(), AC_AutoTune_Heli::dwell_test_run(), get_rpy_srate(), AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_intra_test_gains(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Multi::load_test_gains(), AC_AutoTune_Multi::load_tuned_gains(), max_rate_step_bf_yaw(), pre_arm_checks(), relax_attitude_controllers(), reset_rate_controller_I_terms(), reset_rate_controller_I_terms_smoothly(), AC_AutoTune_Heli::save_tuning_gains(), AC_AutoTune_Multi::save_tuning_gains(), thrust_heading_rotation_angles(), and AC_AutoTune_Multi::twitch_test_init().
get_roll_trim_cd()
virtual float AC_AttitudeControl::get_roll_trim_cd () inline virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 369 of file AC_AttitudeControl.h.
get_roll_trim_rad()
virtual float AC_AttitudeControl::get_roll_trim_rad () inline protected virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 425 of file AC_AttitudeControl.h.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), and input_euler_angle_roll_pitch_yaw().
get_rpy_srate()
void AC_AttitudeControl::get_rpy_srate (float & roll_srate, float & pitch_srate, float & yaw_srate)
Definition at line 1189 of file AC_AttitudeControl.cpp.
get_singleton()
static AC_AttitudeControl * AC_AttitudeControl::get_singleton (void) inline static
Definition at line 67 of file AC_AttitudeControl.h.
get_slew_yaw_max_degs()
float AC_AttitudeControl::get_slew_yaw_max_degs () const
Definition at line 159 of file AC_AttitudeControl.cpp.
Referenced by get_slew_yaw_max_rads().
get_slew_yaw_max_rads()
float AC_AttitudeControl::get_slew_yaw_max_rads () const inline protected
Definition at line 428 of file AC_AttitudeControl.h.
Referenced by input_euler_angle_roll_pitch_yaw(), input_thrust_vector_heading(), and input_thrust_vector_rate_heading().
get_throttle_in()
float AC_AttitudeControl::get_throttle_in () const inline
Definition at line 299 of file AC_AttitudeControl.h.
Referenced by AC_PosControl::init_z_controller().
get_throttle_mix()
virtual float AC_AttitudeControl::get_throttle_mix (void) const inline virtual
Reimplemented in AC_AttitudeControl_Multi.
Definition at line 356 of file AC_AttitudeControl.h.
inertial_frame_reset()
void AC_AttitudeControl::inertial_frame_reset ()
Definition at line 965 of file AC_AttitudeControl.cpp.
input_angle_step_bf_roll_pitch_yaw()
void AC_AttitudeControl::input_angle_step_bf_roll_pitch_yaw (float roll_angle_step_bf_cd, float pitch_angle_step_bf_cd, float yaw_angle_step_bf_cd) virtual
Definition at line 535 of file AC_AttitudeControl.cpp.
Referenced by AC_AutoTune_Multi::twitch_test_run().
input_euler_angle_roll_pitch_euler_rate_yaw()
void AC_AttitudeControl::input_euler_angle_roll_pitch_euler_rate_yaw (float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_rate_cds) virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 269 of file AC_AttitudeControl.cpp.
Referenced by AC_AutoTune_Heli::dwell_test_run(), AC_AttitudeControl_Heli::input_euler_angle_roll_pitch_euler_rate_yaw(), AC_AttitudeControl_Sub::input_euler_angle_roll_pitch_slew_yaw(), AC_AutoTune_Heli::rate_ff_test_run(), and AC_AutoTune::run().
input_euler_angle_roll_pitch_yaw()
void AC_AttitudeControl::input_euler_angle_roll_pitch_yaw (float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_angle_cd, bool slew_yaw) virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 320 of file AC_AttitudeControl.cpp.
Referenced by AC_AutoTune::control_attitude(), AC_AutoTune_Heli::dwell_test_run(), AC_AttitudeControl_Sub::input_euler_angle_roll_pitch_slew_yaw(), AC_AttitudeControl_Heli::input_euler_angle_roll_pitch_yaw(), AC_AutoTune_Heli::rate_ff_test_run(), and AC_AutoTune_Heli::test_run().
input_euler_rate_roll_pitch_yaw()
void AC_AttitudeControl::input_euler_rate_roll_pitch_yaw (float euler_roll_rate_cds, float euler_pitch_rate_cds, float euler_yaw_rate_cds) virtual
Definition at line 379 of file AC_AttitudeControl.cpp.
input_euler_rate_yaw_euler_angle_pitch_bf_roll()
virtual void AC_AttitudeControl::input_euler_rate_yaw_euler_angle_pitch_bf_roll (bool plane_controls, float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_rate_cds) inline virtual
Reimplemented in AC_AttitudeControl_TS.
Definition at line 173 of file AC_AttitudeControl.h.
input_quaternion()
void AC_AttitudeControl::input_quaternion (Quaternion & attitude_desired_quat, Vector3f ang_vel_target) virtual
Definition at line 231 of file AC_AttitudeControl.cpp.
input_rate_bf_roll_pitch_yaw()
void AC_AttitudeControl::input_rate_bf_roll_pitch_yaw (float roll_rate_bf_cds, float pitch_rate_bf_cds, float yaw_rate_bf_cds) virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 421 of file AC_AttitudeControl.cpp.
Referenced by AC_AutoTune_Heli::dwell_test_run(), AC_AttitudeControl_Heli::input_rate_bf_roll_pitch_yaw(), AC_AutoTune_Heli::rate_ff_test_run(), and AC_AutoTune_Multi::twitch_test_run().
input_rate_bf_roll_pitch_yaw_2()
void AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_2 (float roll_rate_bf_cds, float pitch_rate_bf_cds, float yaw_rate_bf_cds) virtual
Definition at line 458 of file AC_AttitudeControl.cpp.
input_rate_bf_roll_pitch_yaw_3()
void AC_AttitudeControl::input_rate_bf_roll_pitch_yaw_3 (float roll_rate_bf_cds, float pitch_rate_bf_cds, float yaw_rate_bf_cds) virtual
Definition at line 481 of file AC_AttitudeControl.cpp.
input_shaping_ang_vel()
float AC_AttitudeControl::input_shaping_ang_vel (float target_ang_vel, float desired_ang_vel, float accel_max, float dt, float input_tc) static
Definition at line 848 of file AC_AttitudeControl.cpp.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_rate_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), input_shaping_angle(), and input_thrust_vector_rate_heading().
input_shaping_angle() [1/2]
float AC_AttitudeControl::input_shaping_angle (float error_angle, float input_tc, float accel_max, float target_ang_vel, float desired_ang_vel, float max_ang_vel, float dt) static
Definition at line 835 of file AC_AttitudeControl.cpp.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_quaternion(), input_shaping_rate_predictor(), input_thrust_vector_heading(), and input_thrust_vector_rate_heading().
input_shaping_angle() [2/2]
static float AC_AttitudeControl::input_shaping_angle (float error_angle, float input_tc, float accel_max, float target_ang_vel, float dt) inline static
Definition at line 316 of file AC_AttitudeControl.h.
Referenced by input_shaping_angle().
input_shaping_rate_predictor()
void AC_AttitudeControl::input_shaping_rate_predictor (const Vector2f & error_angle, Vector2f & target_ang_vel, float dt) const
Definition at line 867 of file AC_AttitudeControl.cpp.
Referenced by AC_Loiter::set_pilot_desired_acceleration().
input_thrust_vector_heading() [1/3]
void AC_AttitudeControl::input_thrust_vector_heading (const Vector3f & thrust_vector, float heading_angle_cd, float heading_rate_cds) virtual
Definition at line 613 of file AC_AttitudeControl.cpp.
Referenced by input_thrust_vector_heading().
input_thrust_vector_heading() [2/3]
void AC_AttitudeControl::input_thrust_vector_heading (const Vector3f & thrust_vector, float heading_cd) inline
Definition at line 194 of file AC_AttitudeControl.h.
Referenced by input_thrust_vector_heading().
input_thrust_vector_heading() [3/3]
void AC_AttitudeControl::input_thrust_vector_heading (const Vector3f & thrust_vector, HeadingCommand heading)
Definition at line 661 of file AC_AttitudeControl.cpp.
input_thrust_vector_rate_heading()
void AC_AttitudeControl::input_thrust_vector_rate_heading (const Vector3f & thrust_vector, float heading_rate_cds, bool slew_yaw = true) virtual
Definition at line 560 of file AC_AttitudeControl.cpp.
Referenced by input_thrust_vector_heading().
is_throttle_mix_min()
virtual bool AC_AttitudeControl::is_throttle_mix_min () const inline virtual
Reimplemented in AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Definition at line 349 of file AC_AttitudeControl.h.
lean_angle_deg()
float AC_AttitudeControl::lean_angle_deg () const inline
Definition at line 311 of file AC_AttitudeControl.h.
lean_angle_max_cd()
float AC_AttitudeControl::lean_angle_max_cd () const inline
Definition at line 308 of file AC_AttitudeControl.h.
Referenced by AC_Loiter::get_angle_max_cd(), AC_PosControl::get_lean_angle_max_cd(), and AC_Loiter::sanity_check_params().
max_angle_step_bf_pitch()
float AC_AttitudeControl::max_angle_step_bf_pitch () inline
Definition at line 269 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Multi::twitch_test_init().
max_angle_step_bf_roll()
float AC_AttitudeControl::max_angle_step_bf_roll () inline
Definition at line 266 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Multi::twitch_test_init().
max_angle_step_bf_yaw()
float AC_AttitudeControl::max_angle_step_bf_yaw () inline
Definition at line 272 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Multi::twitch_test_init().
max_rate_step_bf_pitch()
float AC_AttitudeControl::max_rate_step_bf_pitch ()
Definition at line 1091 of file AC_AttitudeControl.cpp.
Referenced by max_angle_step_bf_pitch(), and AC_AutoTune_Multi::twitch_test_init().
max_rate_step_bf_roll()
float AC_AttitudeControl::max_rate_step_bf_roll ()
Definition at line 1076 of file AC_AttitudeControl.cpp.
Referenced by max_angle_step_bf_roll(), and AC_AutoTune_Multi::twitch_test_init().
max_rate_step_bf_yaw()
float AC_AttitudeControl::max_rate_step_bf_yaw ()
Definition at line 1106 of file AC_AttitudeControl.cpp.
Referenced by max_angle_step_bf_yaw(), and AC_AutoTune_Multi::twitch_test_init().
parameter_sanity_check()
virtual void AC_AttitudeControl::parameter_sanity_check () inline virtual
Reimplemented in AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Definition at line 343 of file AC_AttitudeControl.h.
passthrough_bf_roll_pitch_rate_yaw()
virtual void AC_AttitudeControl::passthrough_bf_roll_pitch_rate_yaw (float roll_passthrough, float pitch_passthrough, float yaw_rate_bf_cds) inline virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 372 of file AC_AttitudeControl.h.
pre_arm_checks()
bool AC_AttitudeControl::pre_arm_checks (const char * param_prefix, char * failure_msg, const uint8_t failure_msg_len)
Definition at line 1120 of file AC_AttitudeControl.cpp.
rate_bf_pitch_sysid()
void AC_AttitudeControl::rate_bf_pitch_sysid (float rate) inline
Definition at line 242 of file AC_AttitudeControl.h.
rate_bf_pitch_target()
void AC_AttitudeControl::rate_bf_pitch_target (float rate_cds) inline
Definition at line 233 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::dwell_test_run(), AC_AutoTune_Heli::rate_ff_test_run(), and AC_AutoTune_Multi::twitch_test_run().
rate_bf_roll_sysid()
void AC_AttitudeControl::rate_bf_roll_sysid (float rate) inline
Definition at line 239 of file AC_AttitudeControl.h.
rate_bf_roll_target()
void AC_AttitudeControl::rate_bf_roll_target (float rate_cds) inline
Definition at line 230 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::dwell_test_run(), AC_AutoTune_Heli::rate_ff_test_run(), and AC_AutoTune_Multi::twitch_test_run().
rate_bf_targets()
Vector3f AC_AttitudeControl::rate_bf_targets () const inline
Definition at line 275 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::dwell_test_run(), and AC_AutoTune_Heli::rate_ff_test_run().
rate_bf_yaw_sysid()
void AC_AttitudeControl::rate_bf_yaw_sysid (float rate) inline
Definition at line 245 of file AC_AttitudeControl.h.
rate_bf_yaw_target()
void AC_AttitudeControl::rate_bf_yaw_target (float rate_cds) inline
Definition at line 236 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::dwell_test_run(), AC_AutoTune_Heli::rate_ff_test_run(), and AC_AutoTune_Multi::twitch_test_run().
rate_controller_run()
virtual void AC_AttitudeControl::rate_controller_run () pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
relax_attitude_controllers() [1/2]
void AC_AttitudeControl::relax_attitude_controllers ()
Definition at line 168 of file AC_AttitudeControl.cpp.
Referenced by AC_AttitudeControl_TS::relax_attitude_controllers().
relax_attitude_controllers() [2/2]
virtual void AC_AttitudeControl::relax_attitude_controllers (bool exclude_pitch) inline virtual
Reimplemented in AC_AttitudeControl_TS.
Definition at line 143 of file AC_AttitudeControl.h.
Referenced by relax_attitude_controllers().
reset_rate_controller_I_terms()
void AC_AttitudeControl::reset_rate_controller_I_terms ()
Definition at line 192 of file AC_AttitudeControl.cpp.
Referenced by relax_attitude_controllers().
reset_rate_controller_I_terms_smoothly()
void AC_AttitudeControl::reset_rate_controller_I_terms_smoothly ()
Definition at line 200 of file AC_AttitudeControl.cpp.
reset_target_and_rate()
void AC_AttitudeControl::reset_target_and_rate (bool reset_rate = true)
Definition at line 933 of file AC_AttitudeControl.cpp.
Referenced by AC_AutoTune_Heli::rate_ff_test_run().
reset_yaw_target_and_rate()
void AC_AttitudeControl::reset_yaw_target_and_rate (bool reset_rate = true)
Definition at line 947 of file AC_AttitudeControl.cpp.
Referenced by AC_AutoTune_Heli::rate_ff_test_run().
save_accel_pitch_max_cdss()
void AC_AttitudeControl::save_accel_pitch_max_cdss (float accel_pitch_max) inline
Definition at line 109 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::save_tuning_gains(), and AC_AutoTune_Multi::save_tuning_gains().
save_accel_roll_max_cdss()
void AC_AttitudeControl::save_accel_roll_max_cdss (float accel_roll_max) inline
Definition at line 99 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::save_tuning_gains(), and AC_AutoTune_Multi::save_tuning_gains().
save_accel_yaw_max_cdss()
void AC_AttitudeControl::save_accel_yaw_max_cdss (float accel_yaw_max) inline
Definition at line 119 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Multi::save_tuning_gains().
set_accel_pitch_max_cdss()
void AC_AttitudeControl::set_accel_pitch_max_cdss (float accel_pitch_max) inline
Definition at line 106 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Heli::load_tuned_gains(), and AC_AutoTune_Multi::load_tuned_gains().
set_accel_roll_max_cdss()
void AC_AttitudeControl::set_accel_roll_max_cdss (float accel_roll_max) inline
Definition at line 96 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_orig_gains(), AC_AutoTune_Heli::load_tuned_gains(), and AC_AutoTune_Multi::load_tuned_gains().
set_accel_yaw_max_cdss()
void AC_AttitudeControl::set_accel_yaw_max_cdss (float accel_yaw_max) inline
Definition at line 116 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune_Heli::load_gain_set(), AC_AutoTune_Multi::load_orig_gains(), and AC_AutoTune_Multi::load_tuned_gains().
set_angle_P_scale()
void AC_AttitudeControl::set_angle_P_scale (const Vector3f & angle_P_scale) inline
Definition at line 393 of file AC_AttitudeControl.h.
set_angle_P_scale_mult()
void AC_AttitudeControl::set_angle_P_scale_mult (const Vector3f & angle_P_scale) inline
Definition at line 399 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Multi::update_throttle_gain_boost().
set_dt()
void AC_AttitudeControl::set_dt (float dt) inline
Definition at line 77 of file AC_AttitudeControl.h.
set_hover_roll_trim_scalar()
virtual void AC_AttitudeControl::set_hover_roll_trim_scalar (float scalar) inline virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 365 of file AC_AttitudeControl.h.
set_input_tc()
void AC_AttitudeControl::set_input_tc (float input_tc) inline
Definition at line 137 of file AC_AttitudeControl.h.
set_inverted_flight()
virtual void AC_AttitudeControl::set_inverted_flight (bool inverted) inline virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 380 of file AC_AttitudeControl.h.
set_notch_sample_rate()
virtual void AC_AttitudeControl::set_notch_sample_rate (float sample_rate) inline virtual
Reimplemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Definition at line 346 of file AC_AttitudeControl.h.
set_PD_scale_mult()
void AC_AttitudeControl::set_PD_scale_mult (const Vector3f & pd_scale) inline
Definition at line 408 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Multi::update_throttle_gain_boost().
set_roll_pitch_rate_tc()
void AC_AttitudeControl::set_roll_pitch_rate_tc (float input_tc) inline
Definition at line 386 of file AC_AttitudeControl.h.
set_throttle_mix_man()
virtual void AC_AttitudeControl::set_throttle_mix_man () inline virtual
Reimplemented in AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Definition at line 353 of file AC_AttitudeControl.h.
set_throttle_mix_max()
virtual void AC_AttitudeControl::set_throttle_mix_max (float ratio) inline virtual
Reimplemented in AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Definition at line 354 of file AC_AttitudeControl.h.
set_throttle_mix_min()
virtual void AC_AttitudeControl::set_throttle_mix_min () inline virtual
Reimplemented in AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Definition at line 352 of file AC_AttitudeControl.h.
set_throttle_mix_value()
virtual void AC_AttitudeControl::set_throttle_mix_value (float value) inline virtual
Reimplemented in AC_AttitudeControl_Multi.
Definition at line 355 of file AC_AttitudeControl.h.
set_throttle_out()
virtual void AC_AttitudeControl::set_throttle_out (float throttle_in, bool apply_angle_boost, float filt_cutoff) pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Referenced by AC_AutoTune::run(), and AC_PosControl::update_z_controller().
set_yaw_rate_tc()
void AC_AttitudeControl::set_yaw_rate_tc (float input_tc) inline
Definition at line 389 of file AC_AttitudeControl.h.
thrust_heading_rotation_angles()
void AC_AttitudeControl::thrust_heading_rotation_angles (Quaternion & attitude_target, const Quaternion & attitude_body, Vector3f & attitude_error, float & thrust_angle, float & thrust_error_angle) const
Definition at line 760 of file AC_AttitudeControl.cpp.
Referenced by attitude_controller_run_quat().
thrust_vector_rotation_angles()
void AC_AttitudeControl::thrust_vector_rotation_angles (const Quaternion & attitude_target, const Quaternion & attitude_body, Quaternion & thrust_vector_correction, Vector3f & attitude_error, float & thrust_angle, float & thrust_error_angle) const
Definition at line 783 of file AC_AttitudeControl.cpp.
Referenced by input_thrust_vector_heading(), input_thrust_vector_rate_heading(), and thrust_heading_rotation_angles().
update_althold_lean_angle_max()
virtual void AC_AttitudeControl::update_althold_lean_angle_max (float throttle_in) pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
update_ang_vel_target_from_att_error()
Vector3f AC_AttitudeControl::update_ang_vel_target_from_att_error (const Vector3f & attitude_error_rot_vec_rad) protected
Definition at line 1012 of file AC_AttitudeControl.cpp.
Referenced by attitude_controller_run_quat(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), input_rate_bf_roll_pitch_yaw_3(), and AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw().
use_flybar_passthrough()
virtual void AC_AttitudeControl::use_flybar_passthrough (bool passthrough, bool tail_passthrough) inline virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 359 of file AC_AttitudeControl.h.
use_leaky_i()
virtual void AC_AttitudeControl::use_leaky_i (bool leaky_i) inline virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 362 of file AC_AttitudeControl.h.
use_sqrt_controller()
void AC_AttitudeControl::use_sqrt_controller (bool use_sqrt_cont) inline
Definition at line 211 of file AC_AttitudeControl.h.
Referenced by AC_AutoTune::control_attitude(), AC_AutoTune::run(), AC_AutoTune::stop(), AC_AutoTune_Heli::test_run(), and AC_AutoTune_Multi::twitch_test_run().
Member Data Documentation
_accel_pitch_max
AP_Float AC_AttitudeControl::_accel_pitch_max protected
Definition at line 442 of file AC_AttitudeControl.h.
Referenced by accel_limiting(), get_accel_pitch_max_cdss(), get_accel_pitch_max_radss(), save_accel_pitch_max_cdss(), and set_accel_pitch_max_cdss().
_accel_roll_max
AP_Float AC_AttitudeControl::_accel_roll_max protected
Definition at line 439 of file AC_AttitudeControl.h.
Referenced by accel_limiting(), get_accel_roll_max_cdss(), get_accel_roll_max_radss(), save_accel_roll_max_cdss(), and set_accel_roll_max_cdss().
_accel_yaw_max
AP_Float AC_AttitudeControl::_accel_yaw_max protected
Definition at line 445 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), accel_limiting(), get_accel_yaw_max_cdss(), get_accel_yaw_max_radss(), save_accel_yaw_max_cdss(), and set_accel_yaw_max_cdss().
_actuator_sysid
Vector3f AC_AttitudeControl::_actuator_sysid protected
Definition at line 496 of file AC_AttitudeControl.h.
Referenced by actuator_pitch_sysid(), actuator_roll_sysid(), actuator_yaw_sysid(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), and AC_AttitudeControl_Heli::rate_target_to_motor_yaw().
_ahrs
const AP_AHRS_View& AC_AttitudeControl::_ahrs protected
Definition at line 547 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), AC_AttitudeControl_Multi::get_throttle_boosted(), AC_AttitudeControl_Sub::get_throttle_boosted(), inertial_frame_reset(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), AC_AttitudeControl_Heli::integrate_bf_rate_error_to_angle_errors(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), AC_AttitudeControl_Sub::rate_controller_run(), relax_attitude_controllers(), AC_AttitudeControl_TS::relax_attitude_controllers(), reset_target_and_rate(), reset_yaw_target_and_rate(), and AC_AttitudeControl_Heli::set_throttle_out().
_althold_lean_angle_max
float AC_AttitudeControl::_althold_lean_angle_max = 0.0f protected
Definition at line 519 of file AC_AttitudeControl.h.
Referenced by get_althold_lean_angle_max_cd(), AC_AttitudeControl_Heli::update_althold_lean_angle_max(), AC_AttitudeControl_Multi::update_althold_lean_angle_max(), and AC_AttitudeControl_Sub::update_althold_lean_angle_max().
_ang_vel_body
Vector3f AC_AttitudeControl::_ang_vel_body protected
Definition at line 487 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), rate_bf_pitch_target(), rate_bf_roll_target(), rate_bf_targets(), rate_bf_yaw_target(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), AC_AttitudeControl_Sub::rate_controller_run(), relax_attitude_controllers(), and AC_AttitudeControl_TS::relax_attitude_controllers().
_ang_vel_pitch_max
AP_Float AC_AttitudeControl::_ang_vel_pitch_max protected
Definition at line 435 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), get_ang_vel_pitch_max_rads(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_quaternion(), input_shaping_rate_predictor(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), and max_rate_step_bf_pitch().
_ang_vel_roll_max
AP_Float AC_AttitudeControl::_ang_vel_roll_max protected
Definition at line 434 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), get_ang_vel_roll_max_rads(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_quaternion(), input_shaping_rate_predictor(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), and max_rate_step_bf_roll().
_ang_vel_target
Vector3f AC_AttitudeControl::_ang_vel_target protected
Definition at line 483 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), get_attitude_target_ang_vel(), input_angle_step_bf_roll_pitch_yaw(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), AC_AttitudeControl_Heli::integrate_bf_rate_error_to_angle_errors(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), relax_attitude_controllers(), AC_AttitudeControl_TS::relax_attitude_controllers(), reset_target_and_rate(), and reset_yaw_target_and_rate().
_ang_vel_yaw_max
AP_Float AC_AttitudeControl::_ang_vel_yaw_max protected
Definition at line 436 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), get_ang_vel_yaw_max_rads(), get_slew_yaw_max_degs(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_quaternion(), input_thrust_vector_rate_heading(), and max_rate_step_bf_yaw().
_angle_boost
float AC_AttitudeControl::_angle_boost protected
Definition at line 512 of file AC_AttitudeControl.h.
Referenced by angle_boost(), AC_AttitudeControl_Multi::get_throttle_boosted(), AC_AttitudeControl_Sub::get_throttle_boosted(), AC_AttitudeControl_Heli::set_throttle_out(), and AC_AttitudeControl_Multi::set_throttle_out().
_angle_boost_enabled
AP_Int8 AC_AttitudeControl::_angle_boost_enabled protected
Definition at line 451 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Multi::get_throttle_boosted(), and AC_AttitudeControl_Sub::get_throttle_boosted().
_angle_limit_tc
AP_Float AC_AttitudeControl::_angle_limit_tc protected
Definition at line 459 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Heli::update_althold_lean_angle_max(), AC_AttitudeControl_Multi::update_althold_lean_angle_max(), and AC_AttitudeControl_Sub::update_althold_lean_angle_max().
_angle_P_scale
Vector3f AC_AttitudeControl::_angle_P_scale {1,1,1} protected
Definition at line 535 of file AC_AttitudeControl.h.
Referenced by input_shaping_rate_predictor(), set_angle_P_scale(), set_angle_P_scale_mult(), and update_ang_vel_target_from_att_error().
_angle_P_scale_used
Vector3f AC_AttitudeControl::_angle_P_scale_used protected
Definition at line 538 of file AC_AttitudeControl.h.
Referenced by get_last_angle_P_scale(), and update_ang_vel_target_from_att_error().
_aparm
const AP_MultiCopter& AC_AttitudeControl::_aparm protected
Definition at line 548 of file AC_AttitudeControl.h.
Referenced by lean_angle_max_cd().
_attitude_ang_error
Quaternion AC_AttitudeControl::_attitude_ang_error protected
Definition at line 499 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), inertial_frame_reset(), input_rate_bf_roll_pitch_yaw_3(), relax_attitude_controllers(), and AC_AttitudeControl_TS::relax_attitude_controllers().
_attitude_target
Quaternion AC_AttitudeControl::_attitude_target protected
Definition at line 478 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), get_attitude_target_quat(), inertial_frame_reset(), input_angle_step_bf_roll_pitch_yaw(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), relax_attitude_controllers(), AC_AttitudeControl_TS::relax_attitude_controllers(), reset_target_and_rate(), and reset_yaw_target_and_rate().
[struct]
struct { ... } AC_AttitudeControl::_control_monitor
Referenced by control_monitor_rms_output_pitch(), control_monitor_rms_output_pitch_D(), control_monitor_rms_output_pitch_P(), control_monitor_rms_output_roll(), control_monitor_rms_output_roll_D(), control_monitor_rms_output_roll_P(), control_monitor_rms_output_yaw(), and control_monitor_update().
_dt
float AC_AttitudeControl::_dt protected
Definition at line 465 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), get_dt(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), AC_AttitudeControl_Heli::integrate_bf_rate_error_to_angle_errors(), max_rate_step_bf_pitch(), max_rate_step_bf_roll(), max_rate_step_bf_yaw(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Multi::rate_controller_run(), AC_AttitudeControl_Sub::rate_controller_run(), AC_AttitudeControl_Heli::rate_target_to_motor_yaw(), reset_rate_controller_I_terms_smoothly(), set_dt(), AC_AttitudeControl_Heli::update_althold_lean_angle_max(), AC_AttitudeControl_Multi::update_althold_lean_angle_max(), AC_AttitudeControl_Sub::update_althold_lean_angle_max(), update_ang_vel_target_from_att_error(), AC_AttitudeControl_Multi::update_throttle_rpy_mix(), and AC_AttitudeControl_Sub::update_throttle_rpy_mix().
_euler_angle_target
Vector3f AC_AttitudeControl::_euler_angle_target protected
Definition at line 469 of file AC_AttitudeControl.h.
Referenced by get_att_target_euler_cd(), get_att_target_euler_rad(), inertial_frame_reset(), input_angle_step_bf_roll_pitch_yaw(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), relax_attitude_controllers(), AC_AttitudeControl_TS::relax_attitude_controllers(), reset_target_and_rate(), and reset_yaw_target_and_rate().
_euler_rate_target
Vector3f AC_AttitudeControl::_euler_rate_target protected
Definition at line 474 of file AC_AttitudeControl.h.
Referenced by get_rate_ef_targets(), input_angle_step_bf_roll_pitch_yaw(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), relax_attitude_controllers(), AC_AttitudeControl_TS::relax_attitude_controllers(), reset_target_and_rate(), and reset_yaw_target_and_rate().
_feedforward_scalar
float AC_AttitudeControl::_feedforward_scalar = 1.0f protected
Definition at line 528 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), AC_AttitudeControl_Multi::rate_controller_run(), and AC_AttitudeControl_Heli::rate_target_to_motor_yaw().
_input_tc
AP_Float AC_AttitudeControl::_input_tc protected
Definition at line 462 of file AC_AttitudeControl.h.
Referenced by get_input_tc(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_quaternion(), input_shaping_rate_predictor(), input_thrust_vector_heading(), input_thrust_vector_rate_heading(), and set_input_tc().
_motors
AP_Motors& AC_AttitudeControl::_motors protected
Definition at line 549 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Multi::get_throttle_avg_max(), AC_AttitudeControl_Sub::get_throttle_avg_max(), max_rate_step_bf_pitch(), max_rate_step_bf_roll(), max_rate_step_bf_yaw(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), AC_AttitudeControl_Sub::rate_controller_run(), AC_AttitudeControl_Heli::rate_target_to_motor_yaw(), AC_AttitudeControl_Heli::set_throttle_out(), AC_AttitudeControl_Multi::set_throttle_out(), AC_AttitudeControl_Sub::set_throttle_out(), AC_AttitudeControl_Multi::update_throttle_gain_boost(), and AC_AttitudeControl_Multi::update_throttle_rpy_mix().
_p_angle_pitch
AC_P AC_AttitudeControl::_p_angle_pitch protected
Definition at line 455 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), get_angle_pitch_p(), input_shaping_rate_predictor(), max_angle_step_bf_pitch(), and update_ang_vel_target_from_att_error().
_p_angle_roll
AC_P AC_AttitudeControl::_p_angle_roll protected
Definition at line 454 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), get_angle_roll_p(), input_shaping_rate_predictor(), max_angle_step_bf_roll(), and update_ang_vel_target_from_att_error().
_p_angle_yaw
AC_P AC_AttitudeControl::_p_angle_yaw protected
Definition at line 456 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), get_angle_yaw_p(), max_angle_step_bf_yaw(), thrust_heading_rotation_angles(), and update_ang_vel_target_from_att_error().
_pd_scale
Vector3f AC_AttitudeControl::_pd_scale {1,1,1} protected
Definition at line 541 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Multi::rate_controller_run(), and set_PD_scale_mult().
_pd_scale_used
Vector3f AC_AttitudeControl::_pd_scale_used protected
Definition at line 544 of file AC_AttitudeControl.h.
Referenced by get_PD_scale_logging(), and AC_AttitudeControl_Multi::rate_controller_run().
_rate_bf_ff_enabled
AP_Int8 AC_AttitudeControl::_rate_bf_ff_enabled protected
Definition at line 448 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), bf_feedforward(), bf_feedforward_save(), get_bf_feedforward(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_shaping_rate_predictor(), input_thrust_vector_heading(), and input_thrust_vector_rate_heading().
_rate_rp_tc
float AC_AttitudeControl::_rate_rp_tc protected
Definition at line 531 of file AC_AttitudeControl.h.
Referenced by input_euler_rate_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), and set_roll_pitch_rate_tc().
_rate_y_tc
float AC_AttitudeControl::_rate_y_tc protected
Definition at line 532 of file AC_AttitudeControl.h.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_rate_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw_2(), input_rate_bf_roll_pitch_yaw_3(), input_thrust_vector_rate_heading(), and set_yaw_rate_tc().
_singleton
AC_AttitudeControl * AC_AttitudeControl::_singleton static protected
Definition at line 551 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl(), and get_singleton().
_slew_yaw
AP_Float AC_AttitudeControl::_slew_yaw protected
Definition at line 431 of file AC_AttitudeControl.h.
Referenced by get_slew_yaw_max_degs().
_sysid_ang_vel_body
Vector3f AC_AttitudeControl::_sysid_ang_vel_body protected
Definition at line 492 of file AC_AttitudeControl.h.
Referenced by rate_bf_pitch_sysid(), rate_bf_roll_sysid(), rate_bf_targets(), rate_bf_yaw_sysid(), AC_AttitudeControl_Heli::rate_controller_run(), and AC_AttitudeControl_Multi::rate_controller_run().
_throttle_in
float AC_AttitudeControl::_throttle_in = 0.0f protected
Definition at line 508 of file AC_AttitudeControl.h.
Referenced by get_throttle_in(), AC_AttitudeControl_Heli::set_throttle_out(), AC_AttitudeControl_Multi::set_throttle_out(), and AC_AttitudeControl_Sub::set_throttle_out().
_throttle_rpy_mix
float AC_AttitudeControl::_throttle_rpy_mix protected
Definition at line 525 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Multi::get_throttle_avg_max(), AC_AttitudeControl_Sub::get_throttle_avg_max(), AC_AttitudeControl_Multi::get_throttle_mix(), AC_AttitudeControl_Multi::is_throttle_mix_min(), AC_AttitudeControl_Sub::is_throttle_mix_min(), AC_AttitudeControl_Multi::set_throttle_mix_value(), AC_AttitudeControl_Multi::update_throttle_rpy_mix(), and AC_AttitudeControl_Sub::update_throttle_rpy_mix().
_throttle_rpy_mix_desired
float AC_AttitudeControl::_throttle_rpy_mix_desired protected
Definition at line 522 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Multi::set_throttle_mix_man(), AC_AttitudeControl_Sub::set_throttle_mix_man(), AC_AttitudeControl_Multi::set_throttle_mix_max(), AC_AttitudeControl_Sub::set_throttle_mix_max(), AC_AttitudeControl_Multi::set_throttle_mix_min(), AC_AttitudeControl_Sub::set_throttle_mix_min(), AC_AttitudeControl_Multi::set_throttle_mix_value(), AC_AttitudeControl_Multi::update_throttle_rpy_mix(), and AC_AttitudeControl_Sub::update_throttle_rpy_mix().
_thrust_angle
float AC_AttitudeControl::_thrust_angle protected
Definition at line 502 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), AC_AttitudeControl_Multi::get_throttle_boosted(), and lean_angle_deg().
_thrust_error_angle
float AC_AttitudeControl::_thrust_error_angle protected
Definition at line 505 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), get_att_error_angle_deg(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), and relax_attitude_controllers().
_use_sqrt_controller
bool AC_AttitudeControl::_use_sqrt_controller protected
Definition at line 516 of file AC_AttitudeControl.h.
Referenced by update_ang_vel_target_from_att_error(), and use_sqrt_controller().
rms_pitch_D
float AC_AttitudeControl::rms_pitch_D
Definition at line 561 of file AC_AttitudeControl.h.
rms_pitch_P
float AC_AttitudeControl::rms_pitch_P
Definition at line 560 of file AC_AttitudeControl.h.
rms_roll_D
float AC_AttitudeControl::rms_roll_D
Definition at line 559 of file AC_AttitudeControl.h.
rms_roll_P
float AC_AttitudeControl::rms_roll_P
Definition at line 558 of file AC_AttitudeControl.h.
rms_yaw
float AC_AttitudeControl::rms_yaw
Definition at line 562 of file AC_AttitudeControl.h.
var_info
const AP_Param::GroupInfo AC_AttitudeControl::var_info static
Definition at line 21 of file AC_AttitudeControl.h.
VECTORF_111
constexpr Vector3f AC_AttitudeControl::VECTORF_111 {1.0f,1.0f,1.0f} static constexpr
Definition at line 416 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Multi::rate_controller_run(), and update_ang_vel_target_from_att_error().
The documentation for this class was generated from the following files:
libraries/AC_AttitudeControl/AC_AttitudeControl.h
libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
libraries/AC_AttitudeControl/ControlMonitor.cpp