APM:Libraries: Linux::UtilRPI Class Reference
Linux::UtilRPI Class Reference
#include <Util_RPI.h>
Public Member Functions
UtilRPI ()
LINUX_BOARD_TYPE detect_linux_board_type () const
Public Member Functions inherited from Linux::Util
void init (int argc, char *const *argv)
bool run_debug_shell (AP_HAL::BetterStream *stream) override
void commandline_arguments (uint8_t &argc, char *const *&argv) override
void set_hw_rtc (uint64_t time_utc_usec) override
uint64_t get_hw_rtc () const override
const char * get_custom_log_directory () const override final
const char * get_custom_terrain_directory () const override final
const char * get_custom_storage_directory () const override final
void set_custom_log_directory (const char *_custom_log_directory)
void set_custom_terrain_directory (const char *_custom_terrain_directory)
void set_custom_storage_directory (const char *_custom_storage_directory)
void set_custom_defaults_path (const char *_custom_defaults)
const char * get_custom_defaults_file () const override final
bool parse_cpu_set (const char *s, cpu_set_t *cpu_set) const
bool is_chardev_node (const char *path)
void set_imu_temp (float current) override
void set_imu_target_temp (int8_t *target) override
uint32_t available_memory (void) override
bool get_system_id (char buf[50]) override
bool get_system_id_unformatted (uint8_t buf[], uint8_t &len) override
int write_file (const char *path, const char *fmt,...) FMT_PRINTF(3
int int read_file (const char *path, const char *fmt,...) FMT_SCANF(3
int int int get_hw_arm32 ()
bool toneAlarm_init (uint8_t types) override
void toneAlarm_set_buzzer_tone (float frequency, float volume, uint32_t duration_ms) override
bool get_random_vals (uint8_t *data, size_t size) override
Public Member Functions inherited from AP_HAL::Util
int snprintf (char *str, size_t size, const char *format,...) FMT_PRINTF(4
int int vsnprintf (char *str, size_t size, const char *format, va_list ap)
virtual void set_soft_armed (const bool b)
bool get_soft_armed () const
uint32_t get_last_armed_change () const
virtual bool was_watchdog_reset () const
bool was_watchdog_safety_off () const
bool was_watchdog_armed () const
virtual void set_cmdline_parameters ()
virtual enum safety_state safety_switch_state (void)
virtual FlashBootloader flash_bootloader ()
virtual AP_HAL::BetterStream * get_shell_stream ()
virtual void * malloc_type (size_t size, Memory_Type mem_type)
virtual void free_type (void *ptr, size_t size, Memory_Type mem_type)
virtual bool trap () const
virtual void thread_info (ExpandingString &str)
virtual void dma_info (ExpandingString &str)
virtual void mem_info (ExpandingString &str)
virtual bool load_persistent_params (ExpandingString &str) const
virtual bool get_persistent_param_by_name (const char *name, char *value, size_t &len) const
virtual void timer_info (ExpandingString &str)
virtual bool get_true_random_vals (uint8_t *data, size_t size, uint32_t timeout_us)
virtual void log_stack_info (void)
Static Public Member Functions
static UtilRPI * from (AP_HAL::Util *util)
Static Public Member Functions inherited from Linux::Util
static Util * from (AP_HAL::Util *util)
Protected Member Functions
void _get_board_type_using_peripheral_base ()
Private Attributes
LINUX_BOARD_TYPE _linux_board_version = LINUX_BOARD_TYPE::UNKNOWN_BOARD
Additional Inherited Members
Public Types inherited from AP_HAL::Util
enum safety_state : uint8_t { SAFETY_NONE , SAFETY_DISARMED , SAFETY_ARMED }
enum class FlashBootloader {
OK =0 , NO_CHANGE =1 , FAIL =2 , NOT_AVAILABLE =3 ,
NOT_SIGNED =4
}
enum Memory_Type { MEM_DMA_SAFE , MEM_FAST , MEM_FILESYSTEM }
Public Attributes inherited from AP_HAL::Util
struct PersistentData persistent_data
struct PersistentData last_persistent_data
Protected Attributes inherited from AP_HAL::Util
bool soft_armed = false
uint32_t last_armed_change_ms
Detailed Description
Definition at line 15 of file Util_RPI.h.
Constructor & Destructor Documentation
UtilRPI()
UtilRPI::UtilRPI ()
Definition at line 29 of file Util_RPI.cpp.
Member Function Documentation
_get_board_type_using_peripheral_base()
void UtilRPI::_get_board_type_using_peripheral_base () protected
Definition at line 38 of file Util_RPI.cpp.
Referenced by UtilRPI().
detect_linux_board_type()
LINUX_BOARD_TYPE UtilRPI::detect_linux_board_type () const
Definition at line 89 of file Util_RPI.cpp.
Referenced by Linux::GPIO_RPI::init(), and Linux::RCInput_RPI::init().
from()
static UtilRPI * Linux::UtilRPI::from (AP_HAL::Util * util) inline static
Definition at line 19 of file Util_RPI.h.
Referenced by Linux::GPIO_RPI::init(), and Linux::RCInput_RPI::init().
Member Data Documentation
_linux_board_version
LINUX_BOARD_TYPE Linux::UtilRPI::_linux_board_version = LINUX_BOARD_TYPE::UNKNOWN_BOARD private
Definition at line 31 of file Util_RPI.h.
Referenced by _get_board_type_using_peripheral_base(), and detect_linux_board_type().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Util_RPI.h
libraries/AP_HAL_Linux/Util_RPI.cpp