APM:Libraries: BinarySemTest Class Reference
BinarySemTest Class Reference
Public Member Functions
void setup (void)
void thread1 (void)
void thread2 (void)
void update (bool ok)
Public Attributes
HAL_BinarySemaphore sem1 {1}
HAL_BinarySemaphore sem2 {0}
uint32_t ops
uint32_t timeouts
uint32_t last_print_us
HAL_Semaphore mtx
Detailed Description
Definition at line 15 of file BinarySem.cpp.
Member Function Documentation
setup()
void BinarySemTest::setup (void)
Definition at line 30 of file BinarySem.cpp.
Referenced by setup().
thread1()
void BinarySemTest::thread1 (void)
Definition at line 48 of file BinarySem.cpp.
Referenced by setup().
thread2()
void BinarySemTest::thread2 (void)
Definition at line 39 of file BinarySem.cpp.
Referenced by setup().
update()
void BinarySemTest::update (bool ok)
Definition at line 57 of file BinarySem.cpp.
Referenced by thread1(), and thread2().
Member Data Documentation
last_print_us
uint32_t BinarySemTest::last_print_us
Definition at line 26 of file BinarySem.cpp.
Referenced by update().
mtx
HAL_Semaphore BinarySemTest::mtx
Definition at line 27 of file BinarySem.cpp.
Referenced by update().
ops
uint32_t BinarySemTest::ops
Definition at line 25 of file BinarySem.cpp.
Referenced by update().
sem1
HAL_BinarySemaphore BinarySemTest::sem1 {1}
Definition at line 17 of file BinarySem.cpp.
Referenced by thread1(), and thread2().
sem2
HAL_BinarySemaphore BinarySemTest::sem2 {0}
Definition at line 18 of file BinarySem.cpp.
Referenced by thread1(), and thread2().
timeouts
uint32_t BinarySemTest::timeouts
Definition at line 25 of file BinarySem.cpp.
Referenced by update().
The documentation for this class was generated from the following file:
libraries/AP_HAL/examples/BinarySem/BinarySem.cpp