APM:Libraries: AP_Baro_DPS280 Class Reference
AP_Baro_DPS280 Class Reference
#include <AP_Baro_DPS280.h>
Classes
struct dps280_cal
Public Member Functions
AP_Baro_DPS280 (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
void update () override
Public Member Functions inherited from AP_Baro_Backend
AP_Baro_Backend (AP_Baro &baro)
virtual ~AP_Baro_Backend (void)
virtual void accumulate (void)
void backend_update (uint8_t instance)
bool pressure_ok (float press)
uint32_t get_error_count () const
Static Public Member Functions
static AP_Baro_Backend * probe_280 (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
static AP_Baro_Backend * probe (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev, bool _is_dps310=false)
Protected Member Functions
bool init (bool _is_dps310)
bool read_calibration (void)
void timer (void)
void calculate_PT (int32_t UT, int32_t UP, float &pressure, float &temperature)
void fix_config_bits16 (int16_t &v, uint8_t bits) const
void fix_config_bits32 (int32_t &v, uint8_t bits) const
void set_config_registers (void)
void check_health ()
Protected Member Functions inherited from AP_Baro_Backend
void _copy_to_frontend (uint8_t instance, float pressure, float temperature)
virtual void update_healthy_flag (uint8_t instance)
void set_bus_id (uint8_t instance, uint32_t id)
Protected Attributes
AP_HAL::OwnPtr< AP_HAL::Device > dev
uint8_t instance
uint32_t count
uint8_t err_count
float pressure_sum
float temperature_sum
float last_temperature
bool pending_reset
bool is_dps310
struct AP_Baro_DPS280::dps280_cal calibration
Protected Attributes inherited from AP_Baro_Backend
AP_Baro & _frontend
HAL_Semaphore _sem
float _mean_pressure
uint32_t _error_count
Additional Inherited Members
Public Types inherited from AP_Baro_Backend
enum DevTypes {
DEVTYPE_BARO_SITL = 0x01 , DEVTYPE_BARO_BMP085 = 0x02 , DEVTYPE_BARO_BMP280 = 0x03 , DEVTYPE_BARO_BMP388 = 0x04 ,
DEVTYPE_BARO_DPS280 = 0x05 , DEVTYPE_BARO_DPS310 = 0x06 , DEVTYPE_BARO_FBM320 = 0x07 , DEVTYPE_BARO_ICM20789 = 0x08 ,
DEVTYPE_BARO_KELLERLD = 0x09 , DEVTYPE_BARO_LPS2XH = 0x0A , DEVTYPE_BARO_MS5611 = 0x0B , DEVTYPE_BARO_SPL06 = 0x0C ,
DEVTYPE_BARO_UAVCAN = 0x0D , DEVTYPE_BARO_MSP = 0x0E , DEVTYPE_BARO_ICP101XX = 0x0F , DEVTYPE_BARO_ICP201XX = 0x10 ,
DEVTYPE_BARO_MS5607 = 0x11 , DEVTYPE_BARO_MS5837 = 0x12 , DEVTYPE_BARO_MS5637 = 0x13 , DEVTYPE_BARO_BMP390 = 0x14
}
Detailed Description
Definition at line 18 of file AP_Baro_DPS280.h.
Constructor & Destructor Documentation
AP_Baro_DPS280()
AP_Baro_DPS280::AP_Baro_DPS280 (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
Definition at line 46 of file AP_Baro_DPS280.cpp.
Referenced by probe().
Member Function Documentation
calculate_PT()
void AP_Baro_DPS280::calculate_PT (int32_t UT, int32_t UP, float & pressure, float & temperature) protected
Definition at line 211 of file AP_Baro_DPS280.cpp.
Referenced by timer().
check_health()
void AP_Baro_DPS280::check_health (void) protected
Definition at line 234 of file AP_Baro_DPS280.cpp.
Referenced by timer().
fix_config_bits16()
void AP_Baro_DPS280::fix_config_bits16 (int16_t & v, uint8_t bits) const protected
Definition at line 80 of file AP_Baro_DPS280.cpp.
Referenced by read_calibration().
fix_config_bits32()
void AP_Baro_DPS280::fix_config_bits32 (int32_t & v, uint8_t bits) const protected
Definition at line 90 of file AP_Baro_DPS280.cpp.
Referenced by read_calibration(), and timer().
init()
bool AP_Baro_DPS280::init (bool _is_dps310) protected
Definition at line 156 of file AP_Baro_DPS280.cpp.
Referenced by probe().
probe()
AP_Baro_Backend * AP_Baro_DPS280::probe (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev, bool _is_dps310 = false) static
Definition at line 52 of file AP_Baro_DPS280.cpp.
Referenced by AP_Baro_DPS310::probe(), and probe_280().
probe_280()
static AP_Baro_Backend * AP_Baro_DPS280::probe_280 (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev) inline static
Definition at line 25 of file AP_Baro_DPS280.h.
Referenced by AP_Baro::_probe_i2c_barometers().
read_calibration()
bool AP_Baro_DPS280::read_calibration (void) protected
Definition at line 100 of file AP_Baro_DPS280.cpp.
Referenced by init().
set_config_registers()
void AP_Baro_DPS280::set_config_registers (void) protected
Definition at line 137 of file AP_Baro_DPS280.cpp.
Referenced by check_health(), init(), and timer().
timer()
void AP_Baro_DPS280::timer (void) protected
Definition at line 250 of file AP_Baro_DPS280.cpp.
Referenced by init().
update()
void AP_Baro_DPS280::update (void) override virtual
Implements AP_Baro_Backend.
Definition at line 301 of file AP_Baro_DPS280.cpp.
Member Data Documentation
calibration
struct AP_Baro_DPS280::dps280_cal AP_Baro_DPS280::calibration protected
Referenced by calculate_PT(), read_calibration(), and set_config_registers().
count
uint32_t AP_Baro_DPS280::count protected
Definition at line 46 of file AP_Baro_DPS280.h.
Referenced by timer(), and update().
dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_Baro_DPS280::dev protected
Definition at line 42 of file AP_Baro_DPS280.h.
Referenced by check_health(), init(), probe_280(), read_calibration(), set_config_registers(), and timer().
err_count
uint8_t AP_Baro_DPS280::err_count protected
Definition at line 47 of file AP_Baro_DPS280.h.
Referenced by check_health(), and timer().
instance
uint8_t AP_Baro_DPS280::instance protected
Definition at line 44 of file AP_Baro_DPS280.h.
Referenced by init(), and update().
is_dps310
bool AP_Baro_DPS280::is_dps310 protected
Definition at line 52 of file AP_Baro_DPS280.h.
Referenced by probe(), and set_config_registers().
last_temperature
float AP_Baro_DPS280::last_temperature protected
Definition at line 50 of file AP_Baro_DPS280.h.
Referenced by check_health(), and timer().
pending_reset
bool AP_Baro_DPS280::pending_reset protected
Definition at line 51 of file AP_Baro_DPS280.h.
Referenced by check_health(), and timer().
pressure_sum
float AP_Baro_DPS280::pressure_sum protected
Definition at line 48 of file AP_Baro_DPS280.h.
Referenced by timer(), and update().
temperature_sum
float AP_Baro_DPS280::temperature_sum protected
Definition at line 49 of file AP_Baro_DPS280.h.
Referenced by timer(), and update().
The documentation for this class was generated from the following files:
libraries/AP_Baro/AP_Baro_DPS280.h
libraries/AP_Baro/AP_Baro_DPS280.cpp