APM:Libraries: SITL::SMBusDevice Class Reference
SITL::SMBusDevice Class Reference
#include <SIM_SMBusDevice.h>
Public Member Functions
SMBusDevice ()
void set_register (uint8_t reg, uint16_t value)
void set_register (uint8_t reg, int16_t value)
uint16_t get_reg_value (uint8_t reg)
Public Member Functions inherited from SITL::I2CDevice
virtual void init ()
virtual void update (const class Aircraft &aircraft)
Protected Member Functions
int rdwr (I2C::i2c_rdwr_ioctl_data *&data) override
void set_block (uint8_t block, uint8_t *value, uint8_t valuelen)
void add_block (const char *name, uint8_t reg, I2CRegisters::RegMode mode)
void set_block (uint8_t block, const char *value)
void add_register (const char *name, uint8_t reg, I2CRegisters::RegMode mode)
Private Attributes
const char * blockname [256]
Bitmask< 256 > writable_blocks
Bitmask< 256 > readable_blocks
char * values [256]
uint8_t value_lengths [256]
Private Attributes inherited from SITL::I2CRegisters_16Bit
uint16_t word [256]
Private Attributes inherited from SITL::I2CRegisters
const char * regname [256]
Bitmask< 256 > writable_registers
Bitmask< 256 > readable_registers
Additional Inherited Members
Private Types inherited from SITL::I2CRegisters
enum class RegMode { RDONLY = 11 , WRONLY = 22 , RDWR = 33 }
Private Member Functions inherited from SITL::I2CRegisters_16Bit
void set_register (uint8_t reg, uint16_t value)
void set_register (uint8_t reg, int16_t value)
uint16_t get_reg_value (uint8_t reg)
Private Member Functions inherited from SITL::I2CRegisters
void add_register (const char *name, uint8_t reg, RegMode mode)
void set_debug (bool value)
bool get_debug () const
Detailed Description
Definition at line 10 of file SIM_SMBusDevice.h.
Constructor & Destructor Documentation
SMBusDevice()
SITL::SMBusDevice::SMBusDevice () inline
Definition at line 13 of file SIM_SMBusDevice.h.
Member Function Documentation
add_block()
void SITL::SMBusDevice::add_block (const char * name, uint8_t reg, I2CRegisters::RegMode mode) protected
Definition at line 40 of file SIM_SMBusDevice.cpp.
Referenced by SITL::SIM_BattMonitor_SMBus::SIM_BattMonitor_SMBus().
add_register()
void SITL::SMBusDevice::add_register (const char * name, uint8_t reg, I2CRegisters::RegMode mode) inline protected
Definition at line 41 of file SIM_SMBusDevice.h.
Referenced by SITL::Rotoye::Rotoye(), and SITL::SIM_BattMonitor_SMBus::SIM_BattMonitor_SMBus().
get_reg_value()
uint16_t SITL::SMBusDevice::get_reg_value (uint8_t reg) inline
Definition at line 25 of file SIM_SMBusDevice.h.
rdwr()
int SITL::SMBusDevice::rdwr (I2C::i2c_rdwr_ioctl_data *& data) override protected virtual
Implements SITL::I2CDevice.
Definition at line 3 of file SIM_SMBusDevice.cpp.
set_block() [1/2]
void SITL::SMBusDevice::set_block (uint8_t block, const char * value) inline protected
Definition at line 37 of file SIM_SMBusDevice.h.
set_block() [2/2]
void SITL::SMBusDevice::set_block (uint8_t block, uint8_t * value, uint8_t valuelen) protected
Definition at line 54 of file SIM_SMBusDevice.cpp.
Referenced by SITL::Maxell::Maxell(), SITL::Rotoye::Rotoye(), set_block(), SITL::SIM_BattMonitor_SMBus::SIM_BattMonitor_SMBus(), and SITL::SIM_BattMonitor_SMBus_Generic::SIM_BattMonitor_SMBus_Generic().
set_register() [1/2]
void SITL::SMBusDevice::set_register (uint8_t reg, int16_t value) inline
Definition at line 21 of file SIM_SMBusDevice.h.
set_register() [2/2]
void SITL::SMBusDevice::set_register (uint8_t reg, uint16_t value) inline
Definition at line 18 of file SIM_SMBusDevice.h.
Referenced by SITL::Maxell::Maxell(), SITL::Rotoye::Rotoye(), and SITL::SIM_BattMonitor_SMBus::SIM_BattMonitor_SMBus().
Member Data Documentation
blockname
const char* SITL::SMBusDevice::blockname[256] private
Definition at line 47 of file SIM_SMBusDevice.h.
Referenced by rdwr().
readable_blocks
Bitmask<256> SITL::SMBusDevice::readable_blocks private
Definition at line 49 of file SIM_SMBusDevice.h.
value_lengths
uint8_t SITL::SMBusDevice::value_lengths[256] private
Definition at line 53 of file SIM_SMBusDevice.h.
Referenced by rdwr().
values
char* SITL::SMBusDevice::values[256] private
Definition at line 52 of file SIM_SMBusDevice.h.
Referenced by rdwr().
writable_blocks
Bitmask<256> SITL::SMBusDevice::writable_blocks private
Definition at line 48 of file SIM_SMBusDevice.h.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_SMBusDevice.h
libraries/SITL/SIM_SMBusDevice.cpp