APM:Libraries: AP_Compass_IST8310 Class Reference
AP_Compass_IST8310 Class Reference
#include <AP_Compass_IST8310.h>
Public Member Functions
void read () override
Public Member Functions inherited from AP_Compass_Backend
AP_Compass_Backend ()
virtual ~AP_Compass_Backend (void)
Static Public Member Functions
static AP_Compass_Backend * probe (AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, bool force_external, enum Rotation rotation)
Static Public Attributes
static constexpr const char * name = "IST8310"
Private Member Functions
AP_Compass_IST8310 (AP_HAL::OwnPtr< AP_HAL::Device > dev, bool force_external, enum Rotation rotation)
void timer ()
bool init ()
void start_conversion ()
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _dev
AP_HAL::Device::PeriodicHandle _periodic_handle
enum Rotation _rotation
uint8_t _instance
bool _ignore_next_sample
bool _force_external
Additional Inherited Members
Public Types inherited from AP_Compass_Backend
enum DevTypes {
DEVTYPE_HMC5883_OLD = 0x01 , DEVTYPE_HMC5883 = 0x07 , DEVTYPE_LSM303D = 0x02 , DEVTYPE_AK8963 = 0x04 ,
DEVTYPE_BMM150 = 0x05 , DEVTYPE_LSM9DS1 = 0x06 , DEVTYPE_LIS3MDL = 0x08 , DEVTYPE_AK09916 = 0x09 ,
DEVTYPE_IST8310 = 0x0A , DEVTYPE_ICM20948 = 0x0B , DEVTYPE_MMC3416 = 0x0C , DEVTYPE_QMC5883L = 0x0D ,
DEVTYPE_MAG3110 = 0x0E , DEVTYPE_SITL = 0x0F , DEVTYPE_IST8308 = 0x10 , DEVTYPE_RM3100 = 0x11 ,
DEVTYPE_RM3100_2 = 0x12 , DEVTYPE_MMC5983 = 0x13 , DEVTYPE_AK09918 = 0x14 , DEVTYPE_AK09915 = 0x15 ,
DEVTYPE_QMC5883P = 0x16
}
Protected Member Functions inherited from AP_Compass_Backend
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
void set_last_update_usec (uint32_t last_update, uint8_t instance)
void accumulate_sample (Vector3f &field, uint8_t instance, uint32_t max_samples=10)
void drain_accumulated_samples (uint8_t instance, const Vector3f *scale=NULL)
bool register_compass (int32_t dev_id, uint8_t &instance) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void save_dev_id (uint8_t instance)
void set_external (uint8_t instance, bool external)
bool is_external (uint8_t instance)
void set_rotation (uint8_t instance, enum Rotation rotation)
enum Rotation get_board_orientation (void) const
bool field_ok (const Vector3f &field)
uint32_t get_error_count () const
Protected Attributes inherited from AP_Compass_Backend
Compass & _compass
HAL_Semaphore _sem
Detailed Description
Definition at line 38 of file AP_Compass_IST8310.h.
Constructor & Destructor Documentation
AP_Compass_IST8310()
AP_Compass_IST8310::AP_Compass_IST8310 (AP_HAL::OwnPtr< AP_HAL::Device > dev, bool force_external, enum Rotation rotation) private
Definition at line 98 of file AP_Compass_IST8310.cpp.
Referenced by probe().
Member Function Documentation
init()
bool AP_Compass_IST8310::init () private
Definition at line 107 of file AP_Compass_IST8310.cpp.
Referenced by probe().
probe()
AP_Compass_Backend * AP_Compass_IST8310::probe (AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, bool force_external, enum Rotation rotation) static
Definition at line 81 of file AP_Compass_IST8310.cpp.
Referenced by Compass::_probe_external_i2c_compasses(), and Compass::probe_i2c_spi_compasses().
read()
void AP_Compass_IST8310::read (void) override virtual
Implements AP_Compass_Backend.
Definition at line 237 of file AP_Compass_IST8310.cpp.
start_conversion()
void AP_Compass_IST8310::start_conversion () private
Definition at line 183 of file AP_Compass_IST8310.cpp.
Referenced by init(), and timer().
timer()
void AP_Compass_IST8310::timer () private
Definition at line 190 of file AP_Compass_IST8310.cpp.
Referenced by init().
Member Data Documentation
_dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_Compass_IST8310::_dev private
Definition at line 58 of file AP_Compass_IST8310.h.
Referenced by init(), start_conversion(), and timer().
_force_external
bool AP_Compass_IST8310::_force_external private
Definition at line 64 of file AP_Compass_IST8310.h.
Referenced by init().
_ignore_next_sample
bool AP_Compass_IST8310::_ignore_next_sample private
Definition at line 63 of file AP_Compass_IST8310.h.
Referenced by start_conversion(), and timer().
_instance
uint8_t AP_Compass_IST8310::_instance private
Definition at line 62 of file AP_Compass_IST8310.h.
Referenced by init(), read(), and timer().
_periodic_handle
AP_HAL::Device::PeriodicHandle AP_Compass_IST8310::_periodic_handle private
Definition at line 59 of file AP_Compass_IST8310.h.
Referenced by init(), and timer().
_rotation
enum Rotation AP_Compass_IST8310::_rotation private
Definition at line 61 of file AP_Compass_IST8310.h.
Referenced by init().
name
constexpr const char* AP_Compass_IST8310::name = "IST8310" static constexpr
Definition at line 47 of file AP_Compass_IST8310.h.
Referenced by init().
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass_IST8310.h
libraries/AP_Compass/AP_Compass_IST8310.cpp