APM:Libraries: AP_HAL::Device Class Reference
AP_HAL::Device Class Reference abstract
#include <Device.h>
Classes
struct checkreg
struct CommandHeader
union DeviceId
struct DeviceStructure
Public Types
enum BusType {
BUS_TYPE_UNKNOWN = 0 , BUS_TYPE_I2C = 1 , BUS_TYPE_SPI = 2 , BUS_TYPE_UAVCAN = 3 ,
BUS_TYPE_SITL = 4 , BUS_TYPE_MSP = 5 , BUS_TYPE_SERIAL = 6 , BUS_TYPE_WSPI = 7
}
enum Speed { SPEED_HIGH , SPEED_LOW }
typedef void * PeriodicHandle
typedef void * RegisterRWHandle
Public Member Functions
FUNCTOR_TYPEDEF (PeriodicCb, void)
FUNCTOR_TYPEDEF (RegisterRWCb, void, uint8_t, uint8_t *, uint32_t, bool)
FUNCTOR_TYPEDEF (BankSelectCb, bool, uint8_t)
Device (enum BusType type)
enum BusType bus_type (void) const
uint8_t bus_num (void) const
uint32_t get_bus_id (void) const
uint8_t get_bus_address (void) const
void set_device_type (uint8_t devtype)
virtual ~Device ()
virtual void set_address (uint8_t address)
virtual bool set_speed (Speed speed)=0
virtual bool transfer (const uint8_t *send, uint32_t send_len, uint8_t *recv, uint32_t recv_len)=0
virtual void set_cmd_header (const CommandHeader &cmd_hdr)
virtual bool enter_xip_mode (void **map_ptr)
virtual bool exit_xip_mode ()
bool read_registers (uint8_t first_reg, uint8_t *recv, uint32_t recv_len)
bool write_register (uint8_t reg, uint8_t val, bool checked=false)
virtual void set_register_rw_callback (RegisterRWCb register_rw_callback)
bool transfer_bank (uint8_t bank, const uint8_t *send, uint32_t send_len, uint8_t *recv, uint32_t recv_len)
bool read_bank_registers (uint8_t bank, uint8_t first_reg, uint8_t *recv, uint32_t recv_len)
bool write_bank_register (uint8_t bank, uint8_t reg, uint8_t val, bool checked=false)
void set_checked_register (uint8_t bank, uint8_t reg, uint8_t val)
void set_checked_register (uint8_t reg, uint8_t val)
bool setup_checked_registers (uint8_t num_regs, uint8_t frequency=10)
bool check_next_register (void)
bool check_next_register (struct checkreg &fail)
bool read (uint8_t *recv, uint32_t recv_len)
virtual AP_HAL::Semaphore * get_semaphore ()=0
virtual PeriodicHandle register_periodic_callback (uint32_t period_usec, PeriodicCb)=0
virtual bool adjust_periodic_callback (PeriodicHandle h, uint32_t period_usec)=0
virtual bool unregister_callback (PeriodicHandle h)
virtual void setup_bankselect_callback (BankSelectCb bank_select)
virtual void deregister_bankselect_callback ()
virtual void register_completion_callback (AP_HAL::MemberProc proc)
virtual void register_completion_callback (AP_HAL::Proc proc)
virtual bool set_chip_select (bool set)
void set_read_flag (uint8_t flag)
uint32_t get_bus_id_devtype (uint8_t devtype) const
virtual void set_retries (uint8_t retries)
Static Public Member Functions
static uint32_t make_bus_id (enum BusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype)
static uint32_t change_bus_id (uint32_t old_id, uint8_t devtype)
static enum BusType devid_get_bus_type (uint32_t dev_id)
static uint8_t devid_get_bus (uint32_t dev_id)
static uint8_t devid_get_address (uint32_t dev_id)
static uint8_t devid_get_devtype (uint32_t dev_id)
Protected Member Functions
void set_device_address (uint8_t address)
void set_device_bus (uint8_t bus)
Protected Attributes
uint8_t _read_flag = 0
union DeviceId _bus_id
Private Attributes
BankSelectCb _bank_select
RegisterRWCb _register_rw_callback
struct {
uint8_t n_allocated
uint8_t n_set
uint8_t next
uint8_t frequency
uint8_t counter
struct checkreg last_reg_fail
struct checkreg * regs
} _checked
Detailed Description
Definition at line 27 of file Device.h.
Member Typedef Documentation
PeriodicHandle
typedef void* AP_HAL::Device::PeriodicHandle
Definition at line 56 of file Device.h.
RegisterRWHandle
typedef void* AP_HAL::Device::RegisterRWHandle
Definition at line 61 of file Device.h.
Member Enumeration Documentation
BusType
enum AP_HAL::Device::BusType
Enumerator
BUS_TYPE_UNKNOWN
BUS_TYPE_I2C
BUS_TYPE_SPI
BUS_TYPE_UAVCAN
BUS_TYPE_SITL
BUS_TYPE_MSP
BUS_TYPE_SERIAL
BUS_TYPE_WSPI
Definition at line 29 of file Device.h.
Speed
enum AP_HAL::Device::Speed
Enumerator
SPEED_HIGH
SPEED_LOW
Definition at line 40 of file Device.h.
Constructor & Destructor Documentation
Device()
AP_HAL::Device::Device (enum BusType type) inline
Definition at line 65 of file Device.h.
~Device()
virtual AP_HAL::Device::~Device () inline virtual
Definition at line 93 of file Device.h.
Member Function Documentation
adjust_periodic_callback()
virtual bool AP_HAL::Device::adjust_periodic_callback (PeriodicHandle h, uint32_t period_usec) pure virtual
Implemented in ChibiOS::I2CDevice, ChibiOS::SPIDevice, Empty::I2CDevice, ESP32::I2CDevice, ESP32::SPIDevice, Linux::I2CDevice, Linux::SPIDevice, HALSITL::I2CDevice, AP_HAL::I2CDevice, and AP_HAL::SPIDevice.
Referenced by AP_InertialSensor_BMI270::read_fifo(), AP_InertialSensor_Invensensev3::read_fifo(), AP_InertialSensor_BMI088::read_fifo_accel(), AP_InertialSensor_BMI088::read_fifo_gyro(), and AP_Compass_IST8310::timer().
bus_num()
uint8_t AP_HAL::Device::bus_num (void) const inline
Definition at line 76 of file Device.h.
Referenced by AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_QMC5883L::init(), AP_Airspeed_MS4525::init(), ChibiOS::DeviceBus::register_periodic_callback(), and ESP32::DeviceBus::register_periodic_callback().
bus_type()
enum BusType AP_HAL::Device::bus_type (void) const inline
Definition at line 71 of file Device.h.
Referenced by AP_InertialSensor_Invensense::_hardware_init(), AP_InertialSensor_Invensensev2::_hardware_init(), AP_InertialSensor_Invensense::_has_auxiliary_bus(), AP_InertialSensor_Invensensev2::_has_auxiliary_bus(), AP_Baro_BMP280::_init(), AP_Baro_LPS2XH::_init(), AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), AP_InertialSensor_Invensensev2::_set_filter_and_scaling(), AP_InertialSensor_Invensense::_set_filter_register(), AP_HMC5843_BusDriver_HALDevice::AP_HMC5843_BusDriver_HALDevice(), AP_InertialSensor_Invensensev3::hardware_init(), AP_Baro_ICM20789::init(), AP_Compass_LIS3MDL::init(), AP_Compass_MMC5XX3::init(), AP_Compass_RM3100::init(), AP_Baro_DPS280::init(), AP_Baro_BMP388::init(), loop(), AP_Baro_SPL06::probe(), AP_InertialSensor_BMI088::read_accel_registers(), AP_Baro_BMP388::read_registers(), ChibiOS::DeviceBus::register_periodic_callback(), ESP32::DeviceBus::register_periodic_callback(), AP_InertialSensor_Invensensev3::set_filter_and_scaling(), AP_InertialSensor_Invensensev3::set_filter_and_scaling_icm456xy(), AP_InertialSensor_Invensensev3::start(), and AP_InertialSensor_SCHA63T::start().
change_bus_id()
uint32_t AP_HAL::Device::change_bus_id (uint32_t old_id, uint8_t devtype) static
return a new bus ID for the same bus connection but a new device type. This is used for auxiliary bus connections
Definition at line 234 of file Device.cpp.
Referenced by AP_Baro::_have_i2c_driver(), Compass::_have_i2c_driver(), and AuxiliaryBus::set_device_type().
check_next_register() [1/2]
bool AP_HAL::Device::check_next_register (struct checkreg & fail)
check next register value for correctness, with return of failure value. Return false if value is incorrect or register checking has not been setup
Definition at line 158 of file Device.cpp.
check_next_register() [2/2]
bool AP_HAL::Device::check_next_register (void)
check next register value for correctness. Return false if value is incorrect or register checking has not been setup
Definition at line 111 of file Device.cpp.
Referenced by AP_InertialSensor_LSM9DS0::_poll_data(), AP_InertialSensor_LSM9DS1::_poll_data(), AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), AP_Baro_BMP280::_timer(), AP_Baro_SPL06::_timer(), AP_Compass_BMM150::_update(), AP_Baro_DPS280::check_health(), AP_AK09916_BusDriver_HALDevice::check_next_register(), AP_InertialSensor_SCHA63T::read_accel(), AP_InertialSensor_Invensensev3::read_fifo(), AP_InertialSensor_BMI055::read_fifo_accel(), AP_InertialSensor_BMI055::read_fifo_gyro(), AP_InertialSensor_BMI088::read_fifo_gyro(), AP_InertialSensor_SCHA63T::read_gyro(), AP_ICEngine_TCA9554::TCA9554_set(), AP_Compass_LIS3MDL::timer(), AP_Compass_RM3100::timer(), AP_Baro_BMP388::timer(), and AP_RangeFinder_PulsedLightLRF::timer().
deregister_bankselect_callback()
virtual void AP_HAL::Device::deregister_bankselect_callback () inline virtual
Reimplemented in ChibiOS::SPIDevice.
Definition at line 283 of file Device.h.
Referenced by ChibiOS::SPIDevice::deregister_bankselect_callback(), and AP_InertialSensor_Invensensev2::~AP_InertialSensor_Invensensev2().
devid_get_address()
uint8_t AP_HAL::Device::devid_get_address (uint32_t dev_id) static
Definition at line 263 of file Device.cpp.
devid_get_bus()
uint8_t AP_HAL::Device::devid_get_bus (uint32_t dev_id) static
Definition at line 257 of file Device.cpp.
devid_get_bus_type()
enum AP_HAL::Device::BusType AP_HAL::Device::devid_get_bus_type (uint32_t dev_id) static
get bus type
Definition at line 251 of file Device.cpp.
Referenced by Compass::is_replacement_mag(), and Compass::remove_unreg_dev_id().
devid_get_devtype()
uint8_t AP_HAL::Device::devid_get_devtype (uint32_t dev_id) static
Definition at line 269 of file Device.cpp.
enter_xip_mode()
virtual bool AP_HAL::Device::enter_xip_mode (void ** map_ptr) inline virtual
Definition at line 133 of file Device.h.
Referenced by AP_FlashIface_JEDEC::start_xip_mode().
exit_xip_mode()
virtual bool AP_HAL::Device::exit_xip_mode () inline virtual
Definition at line 134 of file Device.h.
Referenced by AP_FlashIface_JEDEC::stop_xip_mode().
FUNCTOR_TYPEDEF() [1/3]
AP_HAL::Device::FUNCTOR_TYPEDEF (BankSelectCb , bool , uint8_t)
FUNCTOR_TYPEDEF() [2/3]
AP_HAL::Device::FUNCTOR_TYPEDEF (PeriodicCb , void)
FUNCTOR_TYPEDEF() [3/3]
AP_HAL::Device::FUNCTOR_TYPEDEF (RegisterRWCb , void , uint8_t , uint8_t * , uint32_t , bool)
get_bus_address()
uint8_t AP_HAL::Device::get_bus_address (void) const inline
Definition at line 86 of file Device.h.
Referenced by AP_Baro_LPS2XH::_imu_i2c_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_Baro_ICM20789::imu_i2c_init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_QMC5883L::init(), AP_Compass_RM3100::init(), and AP_Airspeed_MS4525::init().
get_bus_id()
uint32_t AP_HAL::Device::get_bus_id (void) const inline
Definition at line 81 of file Device.h.
Referenced by AP_Compass_MAG3110::_hardware_init(), AP_Baro_BMP085::_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_Baro_BMP280::_init(), AP_Baro_LPS2XH::_init(), AP_Baro_SPL06::_init(), AP_InertialSensor_LSM9DS0::_poll_data(), AP_InertialSensor_LSM9DS1::_poll_data(), AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), AP_RangeFinder_VL53L0X::check_id(), AP_RangeFinder_VL53L1X::check_id(), AP_InertialSensor_Invensense::get_auxiliary_bus(), AP_InertialSensor_Invensensev2::get_auxiliary_bus(), AP_AK09916_BusDriver_HALDevice::get_bus_id(), AP_AK8963_BusDriver_HALDevice::get_bus_id(), AP_HMC5843_BusDriver_HALDevice::get_bus_id(), AP_Baro_ICM20789::init(), AP_Baro_ICP101XX::init(), AP_Baro_ICP201XX::init(), AP_Compass_BMM150::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_LSM9DS1::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_QMC5883L::init(), AP_Compass_RM3100::init(), AP_Airspeed_ASP5033::init(), AP_Airspeed_MS4525::init(), AP_Airspeed_MS5525::init(), AP_Airspeed_SDP3X::init(), AP_Baro_DPS280::init(), AP_Compass_LSM303D::init(), AP_Compass_MAG3110::init(), AP_Baro_BMP388::init(), AP_Baro_FBM320::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_InertialSensor_SCHA63T::read_accel(), AP_InertialSensor_Invensensev3::read_fifo(), AP_InertialSensor_BMI055::read_fifo_accel(), AP_InertialSensor_BMI055::read_fifo_gyro(), AP_InertialSensor_BMI088::read_fifo_gyro(), AP_InertialSensor_SCHA63T::read_gyro(), AP_RangeFinder_VL53L1X::reset(), AP_Airspeed_DLVR::setup(), and ESP32::I2CDevice::transfer().
get_bus_id_devtype()
uint32_t AP_HAL::Device::get_bus_id_devtype (uint8_t devtype) const
return bus ID with a new devtype
Definition at line 244 of file Device.cpp.
Referenced by AP_InertialSensor_ADIS1647x::start(), AP_InertialSensor_BMI055::start(), AP_InertialSensor_BMI088::start(), AP_InertialSensor_BMI160::start(), AP_InertialSensor_BMI270::start(), AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), AP_InertialSensor_Invensensev3::start(), AP_InertialSensor_SCHA63T::start(), AP_InertialSensor_L3G4200D::start(), AP_InertialSensor_LSM9DS0::start(), AP_InertialSensor_LSM9DS1::start(), and AP_InertialSensor_RST::start().
get_semaphore()
virtual AP_HAL::Semaphore * AP_HAL::Device::get_semaphore () pure virtual
Implemented in ChibiOS::I2CDevice, ChibiOS::SPIDevice, Empty::I2CDevice, Empty::SPIDevice, Empty::WSPIDevice, ESP32::I2CDevice, ESP32::SPIDevice, Linux::I2CDevice, Linux::SPIDevice, HALSITL::I2CDevice, HALSITL::SPIDevice, AP_HAL::I2CDevice, AP_HAL::SPIDevice, and AP_HAL::WSPIDevice.
Referenced by AP_Compass_LSM303D::_hardware_init(), AP_Compass_MAG3110::_hardware_init(), AP_InertialSensor_BMI160::_hardware_init(), AP_InertialSensor_Invensense::_hardware_init(), AP_InertialSensor_Invensensev2::_hardware_init(), AP_Baro_LPS2XH::_imu_i2c_init(), AP_Baro_BMP085::_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_Baro_BMP280::_init(), AP_Baro_LPS2XH::_init(), AP_Baro_SPL06::_init(), AP_InertialSensor_LSM9DS0::_init_sensor(), AP_InertialSensor_BMI055::accel_init(), AP_InertialSensor_BMI088::accel_init(), AP_HMC5843_BusDriver_HALDevice::get_semaphore(), AP_InertialSensor_BMI055::gyro_init(), AP_InertialSensor_BMI088::gyro_init(), GCS_MAVLINK::handle_device_op_read(), GCS_MAVLINK::handle_device_op_write(), AP_InertialSensor_BMI270::hardware_init(), AP_InertialSensor_Invensensev3::hardware_init(), Display_SH1106_I2C::hw_init(), Display_SSD1306_I2C::hw_init(), AP_Baro_ICM20789::imu_spi_init(), AP_Compass_BMM150::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_LSM9DS1::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_QMC5883L::init(), AP_Compass_RM3100::init(), AP_InertialSensor_ADIS1647x::init(), AP_InertialSensor_SCHA63T::init(), AP_Baro_DPS280::init(), AP_Baro_BMP388::init(), AP_Baro_FBM320::init(), loop(), AP_Compass_AK09916::probe_ICM20948(), AP_InertialSensor_ADIS1647x::read_sensor16(), AP_InertialSensor_ADIS1647x::read_sensor32(), AP_InertialSensor_ADIS1647x::read_sensor32_delta(), setup(), AP_InertialSensor_BMI160::start(), AP_InertialSensor_BMI270::start(), AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), and AP_InertialSensor_Invensensev3::start().
make_bus_id()
uint32_t AP_HAL::Device::make_bus_id (enum BusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype) static
make a bus id given bus type, bus number, bus address and device type This is for use by devices that do not use one of the standard HAL Device types, such as UAVCAN devices
Definition at line 221 of file Device.cpp.
Referenced by AP_Baro::_have_i2c_driver(), Compass::_have_i2c_driver(), and AP_InertialSensor_NONE::start().
read()
bool AP_HAL::Device::read (uint8_t * recv, uint32_t recv_len) inline
Wrapper function over transfer() to read a sequence of bytes from device. No value is written, differently from the read_registers() method and hence doesn't include the read flag set by set_read_flag()
Definition at line 229 of file Device.h.
Referenced by AP_RangeFinder_LightWareI2C::sf20_get_reading(), AP_RangeFinder_LightWareI2C::sf20_get_version(), AP_RangeFinder_LightWareI2C::sf20_send_and_expect(), AP_RangeFinder_LightWareI2C::sf20_wait_on_reply(), and AP_Airspeed_DLVR::timer().
read_bank_registers()
bool AP_HAL::Device::read_bank_registers (uint8_t bank, uint8_t first_reg, uint8_t * recv, uint32_t recv_len)
Wrapper function over transfer_bank() to read recv_len registers, starting by first_reg, into the array pointed by recv. The read flag passed to set_read_flag(uint8_t) is ORed with first_reg before performing the transfer.
Return: true on a successful transfer, false on failure.
Definition at line 62 of file Device.cpp.
Referenced by AP_InertialSensor_Invensensev2::_block_read(), AP_InertialSensor_Invensensev2::_register_read(), and GCS_MAVLINK::handle_device_op_read().
read_registers()
bool AP_HAL::Device::read_registers (uint8_t first_reg, uint8_t * recv, uint32_t recv_len)
Wrapper function over transfer() to read recv_len registers, starting by first_reg, into the array pointed by recv. The read flag passed to set_read_flag(uint8_t) is ORed with first_reg before performing the transfer.
Return: true on a successful transfer, false on failure.
Definition at line 182 of file Device.cpp.
Referenced by AP_InertialSensor_L3G4200D::_accel_init(), AP_InertialSensor_L3G4200D::_accumulate_accel(), AP_InertialSensor_L3G4200D::_accumulate_gyro(), AP_Compass_LSM303D::_block_read(), AP_Compass_LSM9DS1::_block_read(), AP_InertialSensor_Invensense::_block_read(), AP_InertialSensor_BMI160::_check_err_reg(), AP_Compass_QMC5883L::_check_whoami(), AP_Baro_LPS2XH::_check_whoami(), AP_Compass_QMC5883L::_dump_registers(), Linux::RCOutput_Bebop::_get_info(), AP_InertialSensor_L3G4200D::_gyro_init(), AP_Compass_MAG3110::_hardware_init(), AP_InertialSensor_BMI160::_hardware_init(), AP_Baro_LPS2XH::_imu_i2c_init(), AP_Baro_BMP085::_init(), AP_Baro_BMP280::_init(), AP_Baro_SPL06::_init(), AP_InertialSensor_RST::_init_accel(), AP_InertialSensor_RST::_init_gyro(), AP_Compass_BMM150::_load_trim_values(), AP_InertialSensor_BMI160::_read_fifo(), AP_Baro_BMP085::_read_pressure(), AP_Compass_MAG3110::_read_sample(), AP_Baro_BMP085::_read_temp(), AP_Compass_LSM303D::_register_read(), AP_Compass_LSM9DS1::_register_read(), AP_InertialSensor_LSM9DS1::_register_read(), AP_InertialSensor_Invensense::_register_read(), AP_InertialSensor_LSM9DS0::_register_read_g(), AP_InertialSensor_LSM9DS0::_register_read_xm(), AP_Baro_BMP280::_timer(), AP_Baro_LPS2XH::_timer(), AP_Baro_SPL06::_timer(), AP_ADC_ADS1115::_update(), AP_Compass_BMM150::_update(), AP_Baro_LPS2XH::_update_pressure(), AP_Baro_LPS2XH::_update_temperature(), AP_InertialSensor_BMI055::accel_init(), AP_InertialSensor_RST::accel_measure(), AP_InertialSensor_Invensensev3::block_read(), AP_AK09916_BusDriver_HALDevice::block_read(), AP_AK8963_BusDriver_HALDevice::block_read(), AP_HMC5843_BusDriver_HALDevice::block_read(), AP_RangeFinder_VL53L0X::check_id(), AP_Airspeed_ASP5033::confirm_sensor_id(), AP_InertialSensor_BMI055::gyro_init(), AP_InertialSensor_BMI088::gyro_init(), AP_InertialSensor_RST::gyro_measure(), AP_Baro_ICM20789::imu_i2c_init(), AP_Baro_ICM20789::imu_spi_init(), AP_Compass_BMM150::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_RM3100::init(), AP_RangeFinder_VL53L0X::init(), AP_Baro_DPS280::init(), AP_Baro_FBM320::init(), AP_RAMTRON::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_RangeFinder_TeraRangerI2C::init(), IS31FL3195::init(), LP5562::init(), PCA9685LED_I2C::init(), AP_Compass_AK09916::probe_ICM20948(), AP_InertialSensor_BMI088::read_accel_registers(), AP_Airspeed_MS5525::read_adc(), AP_BattMonitor_SMBus::read_block(), AP_BattMonitor_SMBus_SUI::read_block_bare(), AP_Baro_DPS280::read_calibration(), AP_Baro_FBM320::read_calibration(), AP_InertialSensor_BMI055::read_fifo_accel(), AP_InertialSensor_BMI055::read_fifo_gyro(), AP_InertialSensor_BMI088::read_fifo_gyro(), Linux::RCOutput_Bebop::read_obs_data(), AP_Airspeed_MS5525::read_prom(), AP_RangeFinder_VL53L0X::read_register(), AP_Baro_BMP388::read_registers(), AP_BattMonitor_SMBus::read_word(), Radio_CC2500::ReadFifo(), Radio_CC2500::ReadReg(), Radio_CC2500::ReadRegisterMulti(), AP_InertialSensor_Invensensev3::register_read(), AP_AK09916_BusDriver_HALDevice::register_read(), AP_AK8963_BusDriver_HALDevice::register_read(), AP_HMC5843_BusDriver_HALDevice::register_read(), AP_Airspeed_ASP5033::timer(), AP_Compass_IST8308::timer(), AP_Compass_IST8310::timer(), AP_Compass_LIS3MDL::timer(), AP_Compass_MMC3416::timer(), AP_Compass_MMC5XX3::timer(), AP_Compass_QMC5883L::timer(), AP_Compass_RM3100::timer(), AP_Baro_DPS280::timer(), AP_Baro_FBM320::timer(), AP_OpticalFlow_PX4Flow::timer(), and AP_RangeFinder_PulsedLightLRF::timer().
register_completion_callback() [1/2]
virtual void AP_HAL::Device::register_completion_callback (AP_HAL::MemberProc proc) inline virtual
Definition at line 293 of file Device.h.
register_completion_callback() [2/2]
virtual void AP_HAL::Device::register_completion_callback (AP_HAL::Proc proc) inline virtual
Definition at line 294 of file Device.h.
register_periodic_callback()
virtual PeriodicHandle AP_HAL::Device::register_periodic_callback (uint32_t period_usec, PeriodicCb) pure virtual
Referenced by AP_Baro_BMP085::_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_Baro_BMP280::_init(), AP_Baro_LPS2XH::_init(), AP_Baro_SPL06::_init(), Display_SH1106_I2C::hw_init(), Display_SSD1306_I2C::hw_init(), AP_Compass_BMM150::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_LSM9DS1::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_QMC5883L::init(), AP_Compass_RM3100::init(), AP_Baro_DPS280::init(), AP_Compass_LSM303D::init(), AP_Compass_MAG3110::init(), AP_IRLock_I2C::init(), AP_Baro_BMP388::init(), AP_Baro_FBM320::init(), AP_HMC5843_BusDriver_HALDevice::register_periodic_callback(), AP_OpticalFlow_PX4Flow::setup_sensor(), AP_InertialSensor_BMI055::start(), AP_InertialSensor_BMI088::start(), AP_InertialSensor_BMI160::start(), AP_InertialSensor_BMI270::start(), AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), AP_InertialSensor_Invensensev3::start(), AP_InertialSensor_SCHA63T::start(), and AP_InertialSensor_LSM9DS0::start().
set_address()
virtual void AP_HAL::Device::set_address (uint8_t address) inline virtual
Reimplemented in ChibiOS::I2CDevice, Empty::I2CDevice, ESP32::I2CDevice, Linux::I2CDevice, and HALSITL::I2CDevice.
Definition at line 101 of file Device.h.
Referenced by AP_Baro_LPS2XH::_imu_i2c_init(), AP_Baro_ICM20789::imu_i2c_init(), and AP_RangeFinder_LightWareI2C::sf20_init().
set_checked_register() [1/2]
void AP_HAL::Device::set_checked_register (uint8_t bank, uint8_t reg, uint8_t val)
set a value for a checked register in a bank
Definition at line 85 of file Device.cpp.
set_checked_register() [2/2]
void AP_HAL::Device::set_checked_register (uint8_t reg, uint8_t val)
set a value for a checked register
Definition at line 80 of file Device.cpp.
set_chip_select()
virtual bool AP_HAL::Device::set_chip_select (bool set) inline virtual
Reimplemented in ChibiOS::SPIDevice.
Definition at line 301 of file Device.h.
Referenced by AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), AP_Logger_Flash_JEDEC::BufferToPage(), AP_Logger_W25N01GV::BufferToPage(), AP_Baro_DPS280::init(), AP_OpticalFlow_Pixart::motion_burst(), AP_Logger_Flash_JEDEC::PageToBuffer(), AP_Logger_W25N01GV::PageToBuffer(), AP_RAMTRON::read(), AP_OpticalFlow_Pixart::reg_read(), AP_OpticalFlow_Pixart::reg_write(), AP_OpticalFlow_Pixart::srom_download(), and AP_RAMTRON::write().
set_cmd_header()
virtual void AP_HAL::Device::set_cmd_header (const CommandHeader & cmd_hdr) inline virtual
Reimplemented in Empty::WSPIDevice, and AP_HAL::WSPIDevice.
Definition at line 127 of file Device.h.
set_device_address()
void AP_HAL::Device::set_device_address (uint8_t address) inline protected
Definition at line 367 of file Device.h.
Referenced by Linux::I2CDevice::I2CDevice(), HALSITL::I2CDevice::I2CDevice(), ESP32::I2CDevice::I2CDevice(), ChibiOS::SPIDevice::SPIDevice(), HALSITL::SPIDevice::SPIDevice(), ESP32::SPIDevice::SPIDevice(), and Linux::SPIDevice::SPIDevice().
set_device_bus()
void AP_HAL::Device::set_device_bus (uint8_t bus) inline protected
Definition at line 372 of file Device.h.
Referenced by Linux::I2CDevice::I2CDevice(), HALSITL::I2CDevice::I2CDevice(), ESP32::I2CDevice::I2CDevice(), ChibiOS::SPIDevice::SPIDevice(), HALSITL::SPIDevice::SPIDevice(), ESP32::SPIDevice::SPIDevice(), and Linux::SPIDevice::SPIDevice().
set_device_type()
void AP_HAL::Device::set_device_type (uint8_t devtype)
Definition at line 57 of file Device.cpp.
Referenced by AP_Baro_BMP085::_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_Baro_BMP280::_init(), AP_Baro_LPS2XH::_init(), AP_Baro_SPL06::_init(), AP_Baro_ICM20789::init(), AP_Baro_ICP101XX::init(), AP_Baro_ICP201XX::init(), AP_Compass_BMM150::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_LSM9DS1::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_QMC5883L::init(), AP_Compass_RM3100::init(), AP_Airspeed_ASP5033::init(), AP_Airspeed_MS4525::init(), AP_Airspeed_MS5525::init(), AP_Airspeed_SDP3X::init(), AP_Baro_DPS280::init(), AP_Compass_LSM303D::init(), AP_Compass_MAG3110::init(), AP_Baro_BMP388::init(), AP_Baro_FBM320::init(), AP_AK09916_BusDriver_HALDevice::set_device_type(), AP_AK8963_BusDriver_HALDevice::set_device_type(), AP_HMC5843_BusDriver_HALDevice::set_device_type(), and AP_Airspeed_DLVR::setup().
set_read_flag()
void AP_HAL::Device::set_read_flag (uint8_t flag)
Some devices connected on the I2C or SPI bus require a bit to be set on the register address in order to perform a read operation. This sets a flag to be used by read_registers(). The flag's default value is zero.
Definition at line 210 of file Device.cpp.
Referenced by AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_LSM9DS1::_hardware_init(), AP_InertialSensor_BMI160::_init(), AP_Baro_LPS2XH::_init(), AP_InertialSensor_RST::_init_accel(), AP_InertialSensor_RST::_init_gyro(), AP_HMC5843_BusDriver_HALDevice::AP_HMC5843_BusDriver_HALDevice(), AP_Baro_ICM20789::imu_spi_init(), AP_Compass_LIS3MDL::init(), AP_Compass_MMC5XX3::init(), AP_Compass_RM3100::init(), AP_InertialSensor_BMI055::init(), AP_InertialSensor_BMI088::init(), AP_InertialSensor_BMI270::init(), AP_Baro_DPS280::init(), AP_Baro_BMP388::init(), AP_Baro_SPL06::probe(), AP_InertialSensor_Invensense::probe(), and AP_InertialSensor_Invensensev2::probe().
set_register_rw_callback()
virtual void AP_HAL::Device::set_register_rw_callback (RegisterRWCb register_rw_callback) inline virtual
Definition at line 157 of file Device.h.
Referenced by ChibiOS::SPIDevice::SPIDevice().
set_retries()
virtual void AP_HAL::Device::set_retries (uint8_t retries) inline virtual
Reimplemented in ChibiOS::I2CDevice, Empty::I2CDevice, ESP32::I2CDevice, Linux::I2CDevice, and HALSITL::I2CDevice.
Definition at line 341 of file Device.h.
Referenced by AP_Compass_MAG3110::_hardware_init(), AP_Baro_LPS2XH::_imu_i2c_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_Baro_ICM20789::imu_i2c_init(), AP_Baro_ICM20789::init(), AP_Baro_ICP101XX::init(), AP_Baro_ICP201XX::init(), AP_Compass_BMM150::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_QMC5883L::init(), AP_Compass_RM3100::init(), AP_RangeFinder_Benewake_TFMiniPlus::init(), AP_Airspeed_ASP5033::init(), AP_Airspeed_MS4525::init(), AP_Airspeed_MS5525::init(), AP_Airspeed_SDP3X::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_RangeFinder_TeraRangerI2C::init(), AP_BattMonitor_SMBus_SUI::init(), IS31FL3195::init(), LP5562::init(), NCP5623::init(), PCA9685LED_I2C::init(), ToshibaLED_I2C::init(), AP_Airspeed_MS4525::probe(), AP_HMC5843_BusDriver_HALDevice::set_retries(), AP_Airspeed_DLVR::setup(), and AP_ICEngine_TCA9554::TCA9554_init().
set_speed()
virtual bool AP_HAL::Device::set_speed (Speed speed) pure virtual
Implemented in ChibiOS::SPIDevice, Empty::SPIDevice, ESP32::SPIDevice, Linux::SPIDevice, HALSITL::SPIDevice, AP_HAL::I2CDevice, AP_HAL::SPIDevice, and Empty::I2CDevice.
Referenced by AP_Compass_LSM9DS1::_check_id(), AP_InertialSensor_Invensensev2::_fifo_reset(), AP_InertialSensor_Invensense::_fifo_reset(), AP_Compass_LSM303D::_hardware_init(), AP_Compass_MAG3110::_hardware_init(), AP_InertialSensor_BMI160::_hardware_init(), AP_InertialSensor_Invensense::_hardware_init(), AP_InertialSensor_Invensensev2::_hardware_init(), AP_InertialSensor_LSM9DS0::_hardware_init(), AP_Baro_BMP280::_init(), AP_Baro_LPS2XH::_init(), AP_Baro_SPL06::_init(), AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), AP_Baro_BMP085::_read_pressure(), AP_Baro_BMP085::_read_temp(), AP_InertialSensor_BMI270::hardware_init(), AP_InertialSensor_Invensensev3::hardware_init(), AP_Baro_ICM20789::imu_spi_init(), AP_InertialSensor_ADIS1647x::init(), AP_Baro_DPS280::init(), AP_Baro_BMP388::init(), AP_Baro_FBM320::init(), AP_InertialSensor_Invensensev3::read_fifo(), AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), and AP_InertialSensor_Invensensev3::start().
setup_bankselect_callback()
virtual void AP_HAL::Device::setup_bankselect_callback (BankSelectCb bank_select) inline virtual
Reimplemented in ChibiOS::SPIDevice.
Definition at line 276 of file Device.h.
Referenced by AP_InertialSensor_Invensensev2::_hardware_init(), ChibiOS::SPIDevice::setup_bankselect_callback(), and ChibiOS::SPIDevice::SPIDevice().
setup_checked_registers()
bool AP_HAL::Device::setup_checked_registers (uint8_t num_regs, uint8_t frequency = 10)
setup for register value checking. Frequency is how often to check registers. If set to 10 then every 10th call to check_next_register will check a register
Definition at line 39 of file Device.cpp.
Referenced by AP_InertialSensor_Invensense::_hardware_init(), AP_InertialSensor_Invensensev2::_hardware_init(), AP_InertialSensor_LSM9DS0::_hardware_init(), AP_Baro_BMP280::_init(), AP_Baro_SPL06::_init(), AP_InertialSensor_BMI055::accel_init(), AP_InertialSensor_BMI055::gyro_init(), AP_InertialSensor_BMI088::gyro_init(), AP_InertialSensor_Invensensev3::hardware_init(), AP_Compass_BMM150::init(), AP_Compass_LIS3MDL::init(), AP_Compass_RM3100::init(), AP_Baro_DPS280::init(), AP_Baro_BMP388::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_AK09916_BusDriver_HALDevice::setup_checked_registers(), and AP_ICEngine_TCA9554::TCA9554_init().
transfer()
virtual bool AP_HAL::Device::transfer (const uint8_t * send, uint32_t send_len, uint8_t * recv, uint32_t recv_len) pure virtual
Implemented in ChibiOS::I2CDevice, ChibiOS::SPIDevice, Empty::I2CDevice, Empty::SPIDevice, Empty::WSPIDevice, ESP32::I2CDevice, ESP32::SPIDevice, Linux::I2CDevice, Linux::SPIDevice, HALSITL::I2CDevice, HALSITL::SPIDevice, AP_HAL::I2CDevice, AP_HAL::SPIDevice, and AP_HAL::WSPIDevice.
Referenced by Linux::RCOutput_AeroIO::_hw_read(), Linux::RCOutput_AeroIO::_hw_write(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_Baro_KellerLD::_read(), AP_Baro_MS56XX::_read_adc(), AP_InertialSensor_LSM9DS0::_read_data_transaction_a(), AP_InertialSensor_LSM9DS0::_read_data_transaction_g(), AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), AP_Baro_BMP085::_read_prom_word(), AP_Baro_MS56XX::_read_prom_word(), AP_Baro_KellerLD::_timer(), AP_Baro_MS56XX::_timer(), Display_SH1106_I2C::_timer(), Display_SSD1306_I2C::_timer(), AP_InertialSensor_BMI270::hardware_init(), Display_SH1106_I2C::hw_init(), Display_SSD1306_I2C::hw_init(), loop(), read(), AP_InertialSensor_BMI088::read_accel_registers(), AP_IRLock_I2C::read_block(), AP_InertialSensor_ADIS1647x::read_reg16(), AP_InertialSensor_SCHA63T::read_register(), AP_Baro_BMP388::read_registers(), AP_InertialSensor_BMI270::read_registers(), AP_InertialSensor_ADIS1647x::read_sensor16(), AP_InertialSensor_ADIS1647x::read_sensor32(), AP_InertialSensor_ADIS1647x::read_sensor32_delta(), AP_InertialSensor_Invensensev3::register_read_bank_icm456xy(), AP_InertialSensor_Invensensev3::register_write_bank_icm456xy(), AP_IRLock_I2C::sync_frame_start(), AP_Baro_KellerLD::transfer_with_delays(), AP_InertialSensor_ADIS1647x::write_reg16(), and AP_InertialSensor_SCHA63T::write_register().
transfer_bank()
bool AP_HAL::Device::transfer_bank (uint8_t bank, const uint8_t * send, uint32_t send_len, uint8_t * recv, uint32_t recv_len)
Wrapper function over transfer() to call bank selection callback and then invoke the transfer call
Return: true on a successful transfer, false on failure.
Definition at line 193 of file Device.cpp.
Referenced by AP_InertialSensor_Invensensev2::_read_fifo(), GCS_MAVLINK::handle_device_op_read(), and GCS_MAVLINK::handle_device_op_write().
unregister_callback()
virtual bool AP_HAL::Device::unregister_callback (PeriodicHandle h) inline virtual
Definition at line 271 of file Device.h.
write_bank_register()
bool AP_HAL::Device::write_bank_register (uint8_t bank, uint8_t reg, uint8_t val, bool checked = false)
Wrapper function over transfer_bank() to write a byte to the register reg. The transfer is done by sending reg and val in that order.
Return: true on a successful transfer, false on failure.
Definition at line 68 of file Device.cpp.
Referenced by AP_InertialSensor_Invensensev2::_register_write(), and GCS_MAVLINK::handle_device_op_write().
write_register()
bool AP_HAL::Device::write_register (uint8_t reg, uint8_t val, bool checked = false)
Wrapper function over transfer() to write a byte to the register reg. The transfer is done by sending reg and val in that order.
Return: true on a successful transfer, false on failure.
Definition at line 168 of file Device.cpp.
Referenced by AP_InertialSensor_L3G4200D::_accel_init(), AP_Baro_BMP085::_cmd_read_pressure(), AP_Baro_BMP085::_cmd_read_temp(), AP_InertialSensor_BMI160::_configure_accel(), AP_InertialSensor_BMI160::_configure_fifo(), AP_InertialSensor_BMI160::_configure_gyro(), AP_InertialSensor_BMI160::_configure_int1_pin(), AP_InertialSensor_LSM9DS1::_fifo_reset(), AP_InertialSensor_L3G4200D::_gyro_init(), AP_Compass_MAG3110::_hardware_init(), AP_InertialSensor_BMI160::_hardware_init(), AP_Baro_LPS2XH::_imu_i2c_init(), AP_Baro_BMP280::_init(), AP_Baro_LPS2XH::_init(), AP_Baro_SPL06::_init(), AP_InertialSensor_RST::_init_accel(), AP_InertialSensor_RST::_init_gyro(), Linux::RCOutput_Bebop::_play_sound(), AP_InertialSensor_BMI160::_read_fifo(), AP_Compass_LSM303D::_register_write(), AP_Compass_LSM9DS1::_register_write(), AP_InertialSensor_LSM9DS1::_register_write(), AP_InertialSensor_Invensense::_register_write(), AP_InertialSensor_LSM9DS0::_register_write_g(), AP_InertialSensor_LSM9DS0::_register_write_xm(), AP_InertialSensor_Invensensev2::_select_bank(), AP_Baro_SPL06::_timer(), IS31FL3195::_timer(), LP5562::_timer(), Linux::RCOutput_Bebop::_toggle_gpio(), AP_Compass_BMM150::_update(), AP_InertialSensor_BMI055::accel_init(), AP_Baro_DPS280::check_health(), AP_Airspeed_ASP5033::confirm_sensor_id(), Linux::RCOutput_PCA9685::force_safety_off(), Linux::RCOutput_PCA9685::force_safety_on(), AP_InertialSensor_BMI055::gyro_init(), AP_InertialSensor_BMI088::gyro_init(), AP_Baro_ICM20789::imu_i2c_init(), AP_Baro_ICM20789::imu_spi_init(), AP_Compass_BMM150::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_QMC5883L::init(), AP_Compass_RM3100::init(), AP_Baro_BMP388::init(), AP_Baro_FBM320::init(), AP_RangeFinder_PulsedLightLRF::init(), IS31FL3195::init(), LP5562::init(), ToshibaLED_I2C::init(), AP_InertialSensor_BMI088::read_fifo_gyro(), AP_AK8963_BusDriver_HALDevice::register_write(), AP_HMC5843_BusDriver_HALDevice::register_write(), AP_AK09916_BusDriver_HALDevice::register_write(), AP_InertialSensor_Invensensev3::register_write(), AP_Baro_DPS280::set_config_registers(), Linux::RCOutput_PCA9685::set_freq(), AP_Compass_IST8310::start_conversion(), AP_ICEngine_TCA9554::TCA9554_init(), AP_ICEngine_TCA9554::TCA9554_set(), AP_Airspeed_ASP5033::timer(), AP_Compass_MMC3416::timer(), AP_Compass_MMC5XX3::timer(), AP_Baro_FBM320::timer(), AP_RangeFinder_PulsedLightLRF::timer(), AP_InertialSensor_BMI088::write_accel_register(), AP_InertialSensor_BMI270::write_register(), AP_RangeFinder_VL53L0X::write_register(), Radio_CC2500::WriteReg(), and Radio_CC2500::WriteRegCheck().
Member Data Documentation
_bank_select
BankSelectCb AP_HAL::Device::_bank_select private
Definition at line 377 of file Device.h.
Referenced by deregister_bankselect_callback(), and setup_bankselect_callback().
_bus_id
union DeviceId AP_HAL::Device::_bus_id protected
Definition at line 364 of file Device.h.
Referenced by bus_num(), bus_type(), Device(), get_bus_address(), get_bus_id(), set_device_address(), and set_device_bus().
[struct]
struct { ... } AP_HAL::Device::_checked
Referenced by setup_checked_registers(), and ~Device().
_read_flag
uint8_t AP_HAL::Device::_read_flag = 0 protected
Definition at line 344 of file Device.h.
Referenced by Linux::I2CDevice::read_registers_multiple().
_register_rw_callback
RegisterRWCb AP_HAL::Device::_register_rw_callback private
Definition at line 378 of file Device.h.
Referenced by set_register_rw_callback().
counter
uint8_t AP_HAL::Device::counter
Definition at line 384 of file Device.h.
frequency
uint8_t AP_HAL::Device::frequency
Definition at line 383 of file Device.h.
Referenced by setup_checked_registers().
last_reg_fail
struct checkreg AP_HAL::Device::last_reg_fail
Definition at line 385 of file Device.h.
n_allocated
uint8_t AP_HAL::Device::n_allocated
Definition at line 380 of file Device.h.
n_set
uint8_t AP_HAL::Device::n_set
Definition at line 381 of file Device.h.
next
uint8_t AP_HAL::Device::next
Definition at line 382 of file Device.h.
regs
struct checkreg* AP_HAL::Device::regs
Definition at line 386 of file Device.h.
The documentation for this class was generated from the following files:
libraries/AP_HAL/Device.h
libraries/AP_HAL/Device.cpp