APM:Libraries: SITL::PS_LightWare_SF45B Class Reference
SITL::PS_LightWare_SF45B Class Reference
#include <SIM_PS_LightWare_SF45B.h>
Classes
class DistanceDataCM
class DistanceOutput
class MsgStream
class PackedMessage
union u
class UpdateRate
Public Member Functions
uint32_t packet_for_location (const Location &location, uint8_t *data, uint8_t buflen) override
void update (const Location &location) override
Public Member Functions inherited from SITL::PS_LightWare
SerialProximitySensor ()
Public Member Functions inherited from SITL::SerialProximitySensor
SerialProximitySensor ()
virtual uint16_t reading_interval_ms () const
float measure_distance_at_angle_bf (const Location &location, float angle) const
Public Member Functions inherited from SITL::SerialDevice
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Private Types
enum class MessageID : uint8_t { DISTANCE_OUTPUT = 27 , STREAM = 30 , DISTANCE_DATA_CM = 44 , UPDATE_RATE = 66 }
enum class InputState { WANT_PREAMBLE = 45 , WANT_FLAGS = 46 , WANT_PAYLOAD = 47 , WANT_CRC = 48 }
enum class State { SCANNING = 21 }
Private Member Functions
void update_input ()
void boomerang_buffer_message (uint8_t len)
void handle_message ()
void send (const char *data, uint32_t len)
uint16_t msg_checksum () const
uint8_t payload_length () const
void move_preamble_in_buffer (uint8_t search_start_pos=0)
void set_inputstate (InputState newstate)
void set_state (State newstate)
void update_output (const Location &location)
void update_output_responses ()
void update_output_scan (const Location &location)
Static Private Member Functions
static uint16_t checksum_bytes (const char *buffer, uint8_t len)
Private Attributes
union SITL::PS_LightWare_SF45B::u _msg
uint8_t _buflen
InputState _inputstate = InputState::WANT_PREAMBLE
uint32_t stream
uint32_t desired_fields
uint8_t update_rate
struct {
bool stream
bool desired_fields
bool update_rate
} send_response
State _state = State::SCANNING
uint32_t last_scan_output_time_ms
float last_degrees_bf
float last_dir = 1
Static Private Attributes
static const uint8_t PREAMBLE = 0xAA
Additional Inherited Members
Protected Member Functions inherited from SITL::SerialDevice
bool init_sitl_pointer () WARN_IF_UNUSED
Protected Attributes inherited from SITL::SerialDevice
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Detailed Description
Definition at line 57 of file SIM_PS_LightWare_SF45B.h.
Member Enumeration Documentation
InputState
enum class SITL::PS_LightWare_SF45B::InputState strong private
Enumerator
WANT_PREAMBLE
WANT_FLAGS
WANT_PAYLOAD
WANT_CRC
Definition at line 218 of file SIM_PS_LightWare_SF45B.h.
MessageID
enum class SITL::PS_LightWare_SF45B::MessageID : uint8_t strong private
Enumerator
DISTANCE_OUTPUT
STREAM
DISTANCE_DATA_CM
UPDATE_RATE
Definition at line 139 of file SIM_PS_LightWare_SF45B.h.
State
enum class SITL::PS_LightWare_SF45B::State strong private
Enumerator
SCANNING
Definition at line 247 of file SIM_PS_LightWare_SF45B.h.
Member Function Documentation
boomerang_buffer_message()
void SITL::PS_LightWare_SF45B::boomerang_buffer_message (uint8_t len) private
checksum_bytes()
static uint16_t SITL::PS_LightWare_SF45B::checksum_bytes (const char * buffer, uint8_t len) inline static private
Definition at line 194 of file SIM_PS_LightWare_SF45B.h.
Referenced by msg_checksum().
handle_message()
void PS_LightWare_SF45B::handle_message () private
Definition at line 60 of file SIM_PS_LightWare_SF45B.cpp.
Referenced by update_input().
move_preamble_in_buffer()
void PS_LightWare_SF45B::move_preamble_in_buffer (uint8_t search_start_pos = 0) private
Definition at line 36 of file SIM_PS_LightWare_SF45B.cpp.
Referenced by update_input().
msg_checksum()
uint16_t SITL::PS_LightWare_SF45B::msg_checksum () const inline private
Definition at line 202 of file SIM_PS_LightWare_SF45B.h.
Referenced by update_input().
packet_for_location()
uint32_t PS_LightWare_SF45B::packet_for_location (const Location & location, uint8_t * data, uint8_t buflen) override virtual
Implements SITL::SerialProximitySensor.
Definition at line 29 of file SIM_PS_LightWare_SF45B.cpp.
payload_length()
uint8_t SITL::PS_LightWare_SF45B::payload_length () const inline private
Definition at line 207 of file SIM_PS_LightWare_SF45B.h.
Referenced by msg_checksum(), and update_input().
send()
void PS_LightWare_SF45B::send (const char * data, uint32_t len) private
Definition at line 52 of file SIM_PS_LightWare_SF45B.cpp.
Referenced by update_output_responses(), and update_output_scan().
set_inputstate()
void SITL::PS_LightWare_SF45B::set_inputstate (InputState newstate) inline private
Definition at line 225 of file SIM_PS_LightWare_SF45B.h.
Referenced by update_input().
set_state()
void SITL::PS_LightWare_SF45B::set_state (State newstate) inline private
Definition at line 251 of file SIM_PS_LightWare_SF45B.h.
update()
void PS_LightWare_SF45B::update (const Location & location) override virtual
Reimplemented from SITL::SerialProximitySensor.
Definition at line 146 of file SIM_PS_LightWare_SF45B.cpp.
update_input()
void PS_LightWare_SF45B::update_input () private
Definition at line 88 of file SIM_PS_LightWare_SF45B.cpp.
Referenced by update().
update_output()
void PS_LightWare_SF45B::update_output (const Location & location) private
Definition at line 152 of file SIM_PS_LightWare_SF45B.cpp.
Referenced by update().
update_output_responses()
void PS_LightWare_SF45B::update_output_responses () private
Definition at line 162 of file SIM_PS_LightWare_SF45B.cpp.
Referenced by update_output().
update_output_scan()
void PS_LightWare_SF45B::update_output_scan (const Location & location) private
Definition at line 184 of file SIM_PS_LightWare_SF45B.cpp.
Referenced by update_output().
Member Data Documentation
_buflen
uint8_t SITL::PS_LightWare_SF45B::_buflen private
Definition at line 192 of file SIM_PS_LightWare_SF45B.h.
Referenced by move_preamble_in_buffer(), payload_length(), and update_input().
_inputstate
InputState SITL::PS_LightWare_SF45B::_inputstate = InputState::WANT_PREAMBLE private
Definition at line 224 of file SIM_PS_LightWare_SF45B.h.
Referenced by set_inputstate(), and update_input().
_msg
union SITL::PS_LightWare_SF45B::u SITL::PS_LightWare_SF45B::_msg private
Referenced by handle_message(), move_preamble_in_buffer(), msg_checksum(), payload_length(), and update_input().
_state
State SITL::PS_LightWare_SF45B::_state = State::SCANNING private
Definition at line 250 of file SIM_PS_LightWare_SF45B.h.
Referenced by set_state(), and update_output().
desired_fields [1/2]
uint32_t SITL::PS_LightWare_SF45B::desired_fields private
Definition at line 234 of file SIM_PS_LightWare_SF45B.h.
Referenced by handle_message(), and update_output_responses().
desired_fields [2/2]
bool SITL::PS_LightWare_SF45B::desired_fields
Definition at line 243 of file SIM_PS_LightWare_SF45B.h.
last_degrees_bf
float SITL::PS_LightWare_SF45B::last_degrees_bf private
Definition at line 262 of file SIM_PS_LightWare_SF45B.h.
Referenced by update_output_scan().
last_dir
float SITL::PS_LightWare_SF45B::last_dir = 1 private
Definition at line 263 of file SIM_PS_LightWare_SF45B.h.
Referenced by update_output_scan().
last_scan_output_time_ms
uint32_t SITL::PS_LightWare_SF45B::last_scan_output_time_ms private
Definition at line 260 of file SIM_PS_LightWare_SF45B.h.
Referenced by update_output_scan().
PREAMBLE
const uint8_t SITL::PS_LightWare_SF45B::PREAMBLE = 0xAA static private
Definition at line 214 of file SIM_PS_LightWare_SF45B.h.
Referenced by move_preamble_in_buffer().
[struct]
struct { ... } SITL::PS_LightWare_SF45B::send_response
Referenced by handle_message(), and update_output_responses().
stream [1/2]
uint32_t SITL::PS_LightWare_SF45B::stream private
Definition at line 233 of file SIM_PS_LightWare_SF45B.h.
Referenced by handle_message(), and update_output_responses().
stream [2/2]
bool SITL::PS_LightWare_SF45B::stream
Definition at line 242 of file SIM_PS_LightWare_SF45B.h.
update_rate [1/2]
uint8_t SITL::PS_LightWare_SF45B::update_rate private
Definition at line 235 of file SIM_PS_LightWare_SF45B.h.
Referenced by handle_message(), and update_output_responses().
update_rate [2/2]
bool SITL::PS_LightWare_SF45B::update_rate
Definition at line 244 of file SIM_PS_LightWare_SF45B.h.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_PS_LightWare_SF45B.h
libraries/SITL/SIM_PS_LightWare_SF45B.cpp