APM:Libraries: SITL::I2CRegisters_16Bit Class Reference
SITL::I2CRegisters_16Bit Class Reference
#include <SIM_I2CDevice.h>
Public Member Functions
int rdwr (I2C::i2c_rdwr_ioctl_data *&data) override
void set_register (uint8_t reg, uint16_t value)
void set_register (uint8_t reg, int16_t value)
uint16_t get_reg_value (uint8_t reg)
Protected Attributes
uint16_t word [256]
Protected Attributes inherited from SITL::I2CRegisters
const char * regname [256]
Bitmask< 256 > writable_registers
Bitmask< 256 > readable_registers
Additional Inherited Members
Public Types inherited from SITL::I2CRegisters
enum class RegMode { RDONLY = 11 , WRONLY = 22 , RDWR = 33 }
Protected Member Functions inherited from SITL::I2CRegisters
void add_register (const char *name, uint8_t reg, RegMode mode)
void set_debug (bool value)
bool get_debug () const
Detailed Description
Definition at line 64 of file SIM_I2CDevice.h.
Member Function Documentation
get_reg_value()
uint16_t SITL::I2CRegisters_16Bit::get_reg_value (uint8_t reg) inline
Definition at line 70 of file SIM_I2CDevice.h.
Referenced by SITL::SMBusDevice::get_reg_value().
rdwr()
int SITL::I2CRegisters_16Bit::rdwr (I2C::i2c_rdwr_ioctl_data *& data) override virtual
Implements SITL::I2CRegisters.
Reimplemented in SITL::SMBusDevice.
Definition at line 46 of file SIM_I2CDevice.cpp.
Referenced by SITL::SMBusDevice::rdwr().
set_register() [1/2]
void SITL::I2CRegisters_16Bit::set_register (uint8_t reg, int16_t value)
Definition at line 37 of file SIM_I2CDevice.cpp.
set_register() [2/2]
void SITL::I2CRegisters_16Bit::set_register (uint8_t reg, uint16_t value)
Definition at line 27 of file SIM_I2CDevice.cpp.
Referenced by SITL::SMBusDevice::set_register(), and SITL::SMBusDevice::set_register().
Member Data Documentation
word
uint16_t SITL::I2CRegisters_16Bit::word[256] protected
Definition at line 76 of file SIM_I2CDevice.h.
Referenced by get_reg_value(), and SITL::SIM_BattMonitor_SMBus::SIM_BattMonitor_SMBus().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_I2CDevice.h
libraries/SITL/SIM_I2CDevice.cpp