APM:Libraries: MMLPlayer Class Reference
MMLPlayer Class Reference
#include <MMLPlayer.h>
Public Member Functions
void update ()
void play (const char *string)
void stop ()
Private Types
enum node_mode_t { MODE_NORMAL , MODE_LEGATO , MODE_STACCATO }
Private Member Functions
void prepare_to_play_string (const char *string)
void start_silence (float duration)
void start_note (float duration, float frequency, float volume)
char next_char ()
uint8_t next_number ()
size_t next_dots ()
float rest_duration (uint32_t rest_length, uint8_t dots) const
void next_action ()
Private Attributes
bool _playing
uint32_t _note_duration_us
uint32_t _note_start_us
const char * _string
uint8_t _tempo
uint8_t _default_note_length
uint8_t _volume
size_t _next
uint8_t _octave
float _silence_duration
bool _repeat
enum MMLPlayer::node_mode_t _note_mode
Detailed Description
Definition at line 6 of file MMLPlayer.h.
Member Enumeration Documentation
node_mode_t
enum MMLPlayer::node_mode_t private
Enumerator
MODE_NORMAL
MODE_LEGATO
MODE_STACCATO
Definition at line 29 of file MMLPlayer.h.
Member Function Documentation
next_action()
void MMLPlayer::next_action () private
Definition at line 131 of file MMLPlayer.cpp.
Referenced by play(), and update().
next_char()
char MMLPlayer::next_char () private
Definition at line 84 of file MMLPlayer.cpp.
Referenced by next_action(), next_dots(), and next_number().
next_dots()
size_t MMLPlayer::next_dots () private
Definition at line 103 of file MMLPlayer.cpp.
Referenced by next_action().
next_number()
uint8_t MMLPlayer::next_number () private
Definition at line 93 of file MMLPlayer.cpp.
Referenced by next_action().
play()
void MMLPlayer::play (const char * string)
Definition at line 42 of file MMLPlayer.cpp.
Referenced by AP_ToneAlarm::play_tune().
prepare_to_play_string()
void MMLPlayer::prepare_to_play_string (const char * string) private
Definition at line 24 of file MMLPlayer.cpp.
Referenced by next_action(), and play().
rest_duration()
float MMLPlayer::rest_duration (uint32_t rest_length, uint8_t dots) const private
Definition at line 113 of file MMLPlayer.cpp.
Referenced by next_action().
start_note()
void MMLPlayer::start_note (float duration, float frequency, float volume) private
Definition at line 61 of file MMLPlayer.cpp.
Referenced by next_action().
start_silence()
void MMLPlayer::start_silence (float duration) private
Definition at line 54 of file MMLPlayer.cpp.
Referenced by next_action().
stop()
void MMLPlayer::stop ()
Definition at line 48 of file MMLPlayer.cpp.
Referenced by next_action(), AP_ToneAlarm::play_tune(), and prepare_to_play_string().
update()
void MMLPlayer::update ()
Definition at line 16 of file MMLPlayer.cpp.
Referenced by AP_ToneAlarm::_timer_task().
Member Data Documentation
_default_note_length
uint8_t MMLPlayer::_default_note_length private
Definition at line 23 of file MMLPlayer.h.
Referenced by next_action(), and prepare_to_play_string().
_next
size_t MMLPlayer::_next private
Definition at line 25 of file MMLPlayer.h.
Referenced by next_action(), next_char(), next_dots(), next_number(), and prepare_to_play_string().
_note_duration_us
uint32_t MMLPlayer::_note_duration_us private
Definition at line 19 of file MMLPlayer.h.
Referenced by prepare_to_play_string(), start_note(), start_silence(), and update().
_note_mode
enum MMLPlayer::node_mode_t MMLPlayer::_note_mode private
Referenced by next_action(), and prepare_to_play_string().
_note_start_us
uint32_t MMLPlayer::_note_start_us private
Definition at line 20 of file MMLPlayer.h.
Referenced by start_note(), start_silence(), and update().
_octave
uint8_t MMLPlayer::_octave private
Definition at line 26 of file MMLPlayer.h.
Referenced by next_action(), and prepare_to_play_string().
_playing
bool MMLPlayer::_playing private
Definition at line 17 of file MMLPlayer.h.
Referenced by prepare_to_play_string(), stop(), and update().
_repeat
bool MMLPlayer::_repeat private
Definition at line 28 of file MMLPlayer.h.
Referenced by next_action(), and prepare_to_play_string().
_silence_duration
float MMLPlayer::_silence_duration private
Definition at line 27 of file MMLPlayer.h.
Referenced by next_action(), and prepare_to_play_string().
_string
const char* MMLPlayer::_string private
Definition at line 21 of file MMLPlayer.h.
Referenced by next_action(), next_char(), and prepare_to_play_string().
_tempo
uint8_t MMLPlayer::_tempo private
Definition at line 22 of file MMLPlayer.h.
Referenced by next_action(), prepare_to_play_string(), and rest_duration().
_volume
uint8_t MMLPlayer::_volume private
Definition at line 24 of file MMLPlayer.h.
Referenced by next_action(), and prepare_to_play_string().
The documentation for this class was generated from the following files:
libraries/AP_Notify/MMLPlayer.h
libraries/AP_Notify/MMLPlayer.cpp