APM:Libraries: Thrust_Linearization Class Reference
Thrust_Linearization Class Reference
#include <AP_Motors_Thrust_Linearization.h>
Public Member Functions
Thrust_Linearization (AP_Motors &_motors)
float apply_thrust_curve_and_volt_scaling (float thrust) const
float remove_thrust_curve_and_volt_scaling (float throttle) const
float thrust_to_actuator (float thrust_in) const
float actuator_to_thrust (float actuator) const
void update_lift_max_from_batt_voltage ()
float get_compensation_gain () const
float get_spin_min () const
float get_spin_max () const
int8_t get_battery_index () const
float get_battery_min_voltage () const
float get_lift_max () const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Attributes
AP_Float curve_expo
AP_Float spin_min
AP_Float spin_max
AP_Int8 batt_idx
AP_Float batt_voltage_max
AP_Float batt_voltage_min
Private Attributes
float lift_max
float throttle_limit
LowPassFilterFloat batt_voltage_filt
AP_Motors & motors
Friends
class AP_MotorsMulticopter
class AP_MotorsMulticopter_test
class AP_MotorsHeli_Single
Detailed Description
Definition at line 7 of file AP_Motors_Thrust_Linearization.h.
Constructor & Destructor Documentation
Thrust_Linearization()
Thrust_Linearization::Thrust_Linearization (AP_Motors & _motors)
Definition at line 86 of file AP_Motors_Thrust_Linearization.cpp.
Member Function Documentation
actuator_to_thrust()
float Thrust_Linearization::actuator_to_thrust (float actuator) const
Definition at line 108 of file AP_Motors_Thrust_Linearization.cpp.
Referenced by setup().
apply_thrust_curve_and_volt_scaling()
float Thrust_Linearization::apply_thrust_curve_and_volt_scaling (float thrust) const
Definition at line 115 of file AP_Motors_Thrust_Linearization.cpp.
Referenced by thrust_to_actuator().
get_battery_index()
int8_t Thrust_Linearization::get_battery_index () const inline
Definition at line 39 of file AP_Motors_Thrust_Linearization.h.
Referenced by AP_MotorsMulticopter::get_current_limit_max_throttle().
get_battery_min_voltage()
float Thrust_Linearization::get_battery_min_voltage () const inline
Definition at line 42 of file AP_Motors_Thrust_Linearization.h.
Referenced by AP_MotorsMulticopter::get_current_limit_max_throttle().
get_compensation_gain()
float Thrust_Linearization::get_compensation_gain () const
Definition at line 185 of file AP_Motors_Thrust_Linearization.cpp.
Referenced by AP_MotorsMatrix::check_for_failed_motor(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), and AP_MotorsTri::output_armed_stabilizing().
get_lift_max()
float Thrust_Linearization::get_lift_max () const inline
Definition at line 45 of file AP_Motors_Thrust_Linearization.h.
Referenced by get_compensation_gain().
get_spin_max()
float Thrust_Linearization::get_spin_max () const inline
Definition at line 36 of file AP_Motors_Thrust_Linearization.h.
get_spin_min()
float Thrust_Linearization::get_spin_min () const inline
Definition at line 33 of file AP_Motors_Thrust_Linearization.h.
Referenced by AP_MotorsMulticopter::actuator_spin_up_to_ground_idle(), AP_MotorsMulticopter::arming_checks(), and AP_MotorsMulticopter::output_logic().
remove_thrust_curve_and_volt_scaling()
float Thrust_Linearization::remove_thrust_curve_and_volt_scaling (float throttle) const
Definition at line 133 of file AP_Motors_Thrust_Linearization.cpp.
Referenced by actuator_to_thrust().
thrust_to_actuator()
float Thrust_Linearization::thrust_to_actuator (float thrust_in) const
Definition at line 100 of file AP_Motors_Thrust_Linearization.cpp.
Referenced by AP_MotorsCoax::output_to_motors(), AP_MotorsHeli_Single::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsTailsitter::output_to_motors(), AP_MotorsTri::output_to_motors(), and setup().
update_lift_max_from_batt_voltage()
void Thrust_Linearization::update_lift_max_from_batt_voltage ()
Definition at line 152 of file AP_Motors_Thrust_Linearization.cpp.
Referenced by AP_MotorsMulticopter::output(), and AP_MotorsHeli_Single::output_to_motors().
Friends And Related Symbol Documentation
AP_MotorsHeli_Single
friend class AP_MotorsHeli_Single friend
Definition at line 10 of file AP_Motors_Thrust_Linearization.h.
AP_MotorsMulticopter
friend class AP_MotorsMulticopter friend
Definition at line 8 of file AP_Motors_Thrust_Linearization.h.
AP_MotorsMulticopter_test
friend class AP_MotorsMulticopter_test friend
Definition at line 9 of file AP_Motors_Thrust_Linearization.h.
Member Data Documentation
batt_idx
AP_Int8 Thrust_Linearization::batt_idx protected
Definition at line 54 of file AP_Motors_Thrust_Linearization.h.
Referenced by get_battery_index(), and update_lift_max_from_batt_voltage().
batt_voltage_filt
LowPassFilterFloat Thrust_Linearization::batt_voltage_filt private
Definition at line 61 of file AP_Motors_Thrust_Linearization.h.
Referenced by apply_thrust_curve_and_volt_scaling(), remove_thrust_curve_and_volt_scaling(), Thrust_Linearization(), and update_lift_max_from_batt_voltage().
batt_voltage_max
AP_Float Thrust_Linearization::batt_voltage_max protected
Definition at line 55 of file AP_Motors_Thrust_Linearization.h.
Referenced by update_lift_max_from_batt_voltage().
batt_voltage_min
AP_Float Thrust_Linearization::batt_voltage_min protected
Definition at line 56 of file AP_Motors_Thrust_Linearization.h.
Referenced by get_battery_min_voltage(), and update_lift_max_from_batt_voltage().
curve_expo
AP_Float Thrust_Linearization::curve_expo protected
Definition at line 51 of file AP_Motors_Thrust_Linearization.h.
Referenced by apply_thrust_curve_and_volt_scaling(), remove_thrust_curve_and_volt_scaling(), AP_MotorsMulticopter_test::set_expo(), and update_lift_max_from_batt_voltage().
lift_max
float Thrust_Linearization::lift_max private
Definition at line 59 of file AP_Motors_Thrust_Linearization.h.
Referenced by apply_thrust_curve_and_volt_scaling(), get_lift_max(), remove_thrust_curve_and_volt_scaling(), and update_lift_max_from_batt_voltage().
motors
AP_Motors& Thrust_Linearization::motors private
Definition at line 63 of file AP_Motors_Thrust_Linearization.h.
Referenced by update_lift_max_from_batt_voltage().
spin_max
AP_Float Thrust_Linearization::spin_max protected
Definition at line 53 of file AP_Motors_Thrust_Linearization.h.
Referenced by actuator_to_thrust(), get_spin_max(), and thrust_to_actuator().
spin_min
AP_Float Thrust_Linearization::spin_min protected
Definition at line 52 of file AP_Motors_Thrust_Linearization.h.
Referenced by actuator_to_thrust(), get_spin_min(), and thrust_to_actuator().
throttle_limit
float Thrust_Linearization::throttle_limit private
Definition at line 60 of file AP_Motors_Thrust_Linearization.h.
var_info
const AP_Param::GroupInfo Thrust_Linearization::var_info static
Definition at line 37 of file AP_Motors_Thrust_Linearization.h.
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_Motors_Thrust_Linearization.h
libraries/AP_Motors/AP_Motors_Thrust_Linearization.cpp