APM:Libraries: SlewLimiter Class Reference
SlewLimiter Class Reference
#include <SlewLimiter.h>
Public Member Functions
SlewLimiter (const float &slew_rate_max, const float &slew_rate_tau)
CLASS_NO_COPY (SlewLimiter)
float modifier (float sample, float dt)
float get_slew_rate (void) const
Private Attributes
const float & slew_rate_max
const float & slew_rate_tau
LowPassFilterFloat slew_filter
float _output_slew_rate
float _modifier_slew_rate
float last_sample
float _max_pos_slew_rate
float _max_neg_slew_rate
uint32_t _max_pos_slew_event_ms
uint32_t _max_neg_slew_event_ms
uint8_t _pos_event_index
uint8_t _neg_event_index
uint32_t _pos_event_ms [SLEWLIMITER_N_EVENTS]
uint32_t _neg_event_ms [SLEWLIMITER_N_EVENTS]
bool _pos_event_stored
bool _neg_event_stored
Detailed Description
Definition at line 13 of file SlewLimiter.h.
Constructor & Destructor Documentation
SlewLimiter()
SlewLimiter::SlewLimiter (const float & slew_rate_max, const float & slew_rate_tau)
Definition at line 33 of file SlewLimiter.cpp.
Member Function Documentation
CLASS_NO_COPY()
SlewLimiter::CLASS_NO_COPY (SlewLimiter)
get_slew_rate()
float SlewLimiter::get_slew_rate (void) const inline
Definition at line 28 of file SlewLimiter.h.
Referenced by SlewCalculator2D::get_slew_rate(), AC_PID::get_slew_rate(), loop(), AP_AutoTune::update(), and AC_PID::update_all().
modifier()
float SlewLimiter::modifier (float sample, float dt)
Definition at line 45 of file SlewLimiter.cpp.
Referenced by loop(), SlewCalculator2D::update(), AP_AutoTune::update(), and AC_PID::update_all().
Member Data Documentation
_max_neg_slew_event_ms
uint32_t SlewLimiter::_max_neg_slew_event_ms private
Definition at line 42 of file SlewLimiter.h.
Referenced by modifier().
_max_neg_slew_rate
float SlewLimiter::_max_neg_slew_rate private
Definition at line 40 of file SlewLimiter.h.
Referenced by modifier().
_max_pos_slew_event_ms
uint32_t SlewLimiter::_max_pos_slew_event_ms private
Definition at line 41 of file SlewLimiter.h.
Referenced by modifier().
_max_pos_slew_rate
float SlewLimiter::_max_pos_slew_rate private
Definition at line 39 of file SlewLimiter.h.
Referenced by modifier().
_modifier_slew_rate
float SlewLimiter::_modifier_slew_rate private
Definition at line 37 of file SlewLimiter.h.
Referenced by modifier().
_neg_event_index
uint8_t SlewLimiter::_neg_event_index private
Definition at line 44 of file SlewLimiter.h.
Referenced by modifier().
_neg_event_ms
uint32_t SlewLimiter::_neg_event_ms[SLEWLIMITER_N_EVENTS] private
Definition at line 46 of file SlewLimiter.h.
Referenced by modifier().
_neg_event_stored
bool SlewLimiter::_neg_event_stored private
Definition at line 48 of file SlewLimiter.h.
Referenced by modifier().
_output_slew_rate
float SlewLimiter::_output_slew_rate private
Definition at line 36 of file SlewLimiter.h.
Referenced by get_slew_rate(), and modifier().
_pos_event_index
uint8_t SlewLimiter::_pos_event_index private
Definition at line 43 of file SlewLimiter.h.
Referenced by modifier().
_pos_event_ms
uint32_t SlewLimiter::_pos_event_ms[SLEWLIMITER_N_EVENTS] private
Definition at line 45 of file SlewLimiter.h.
Referenced by modifier().
_pos_event_stored
bool SlewLimiter::_pos_event_stored private
Definition at line 47 of file SlewLimiter.h.
Referenced by modifier().
last_sample
float SlewLimiter::last_sample private
Definition at line 38 of file SlewLimiter.h.
Referenced by modifier().
slew_filter
LowPassFilterFloat SlewLimiter::slew_filter private
Definition at line 35 of file SlewLimiter.h.
Referenced by modifier(), and SlewLimiter().
slew_rate_max
const float& SlewLimiter::slew_rate_max private
Definition at line 33 of file SlewLimiter.h.
Referenced by modifier().
slew_rate_tau
const float& SlewLimiter::slew_rate_tau private
Definition at line 34 of file SlewLimiter.h.
Referenced by modifier().
The documentation for this class was generated from the following files:
libraries/Filter/SlewLimiter.h
libraries/Filter/SlewLimiter.cpp