APM:Libraries: AP_InertialSensor_BMI160 Class Reference
AP_InertialSensor_BMI160 Class Reference
#include <AP_InertialSensor_BMI160.h>
Public Member Functions
void start () override
bool update () override
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void accumulate ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t get_id () const
float get_clip_limit () const
virtual bool get_output_banner (char *banner, uint8_t banner_len)
Static Public Member Functions
static AP_InertialSensor_Backend * probe (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev, enum Rotation rotation=BMI160_DEFAULT_ROTATION)
static AP_InertialSensor_Backend * probe (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, enum Rotation rotation=BMI160_DEFAULT_ROTATION)
Private Member Functions
AP_InertialSensor_BMI160 (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation)
void _check_err_reg ()
bool _hardware_init ()
bool _init ()
bool _configure_accel ()
bool _configure_gyro ()
bool _configure_int1_pin ()
bool _configure_fifo ()
void _poll_data ()
void _read_fifo ()
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _dev
enum Rotation _rotation
uint8_t _accel_instance
float _accel_scale
uint8_t _gyro_instance
float _gyro_scale
AP_HAL::DigitalSource * _int1_pin
Additional Inherited Members
Public Types inherited from AP_InertialSensor_Backend
enum DevTypes {
DEVTYPE_BMI160 = 0x09 , DEVTYPE_L3G4200D = 0x10 , DEVTYPE_ACC_LSM303D = 0x11 , DEVTYPE_ACC_BMA180 = 0x12 ,
DEVTYPE_ACC_MPU6000 = 0x13 , DEVTYPE_ACC_MPU9250 = 0x16 , DEVTYPE_ACC_IIS328DQ = 0x17 , DEVTYPE_ACC_LSM9DS1 = 0x18 ,
DEVTYPE_GYR_MPU6000 = 0x21 , DEVTYPE_GYR_L3GD20 = 0x22 , DEVTYPE_GYR_MPU9250 = 0x24 , DEVTYPE_GYR_I3G4250D = 0x25 ,
DEVTYPE_GYR_LSM9DS1 = 0x26 , DEVTYPE_INS_ICM20789 = 0x27 , DEVTYPE_INS_ICM20689 = 0x28 , DEVTYPE_INS_BMI055 = 0x29 ,
DEVTYPE_SITL = 0x2A , DEVTYPE_INS_BMI088 = 0x2B , DEVTYPE_INS_ICM20948 = 0x2C , DEVTYPE_INS_ICM20648 = 0x2D ,
DEVTYPE_INS_ICM20649 = 0x2E , DEVTYPE_INS_ICM20602 = 0x2F , DEVTYPE_INS_ICM20601 = 0x30 , DEVTYPE_INS_ADIS1647X = 0x31 ,
DEVTYPE_SERIAL = 0x32 , DEVTYPE_INS_ICM40609 = 0x33 , DEVTYPE_INS_ICM42688 = 0x34 , DEVTYPE_INS_ICM42605 = 0x35 ,
DEVTYPE_INS_ICM40605 = 0x36 , DEVTYPE_INS_IIM42652 = 0x37 , DEVTYPE_BMI270 = 0x38 , DEVTYPE_INS_BMI085 = 0x39 ,
DEVTYPE_INS_ICM42670 = 0x3A , DEVTYPE_INS_ICM45686 = 0x3B , DEVTYPE_INS_SCHA63T = 0x3C
}
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel) __RAMFUNC__
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro) __RAMFUNC__
void _publish_gyro (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void apply_gyro_filters (const uint8_t instance, const Vector3f &gyro)
void save_gyro_window (const uint8_t instance, const Vector3f &gyro, uint8_t phase)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0) __RAMFUNC__
void _notify_new_delta_angle (uint8_t instance, const Vector3f &dangle)
void _publish_accel (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0, bool fsync_set=false) __RAMFUNC__
void _notify_new_delta_velocity (uint8_t instance, const Vector3f &dvelocity)
void _set_accel_oversampling (uint8_t instance, uint8_t n)
void _set_gyro_oversampling (uint8_t instance, uint8_t n)
void _set_accel_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_gyro_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_raw_sample_accel_multiplier (uint8_t instance, uint16_t mul)
void _set_raw_sample_gyro_multiplier (uint8_t instance, uint16_t mul)
void _update_sensor_rate (uint16_t &count, uint32_t &start_us, float &rate_hz) const __RAMFUNC__
bool sensors_converging () const
void _set_accel_max_abs_offset (uint8_t instance, float offset)
float _accel_raw_sample_rate (uint8_t instance) const
void _set_accel_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
float _gyro_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
void _publish_temperature (uint8_t instance, float temperature)
void _inc_accel_error_count (uint8_t instance) __RAMFUNC__
void _inc_gyro_error_count (uint8_t instance) __RAMFUNC__
uint16_t _accel_filter_cutoff (void) const
uint16_t _gyro_filter_cutoff (void) const
uint16_t get_loop_rate_hz (void) const
void update_gyro (uint8_t instance) __RAMFUNC__
void update_accel (uint8_t instance) __RAMFUNC__
void set_gyro_orientation (uint8_t instance, enum Rotation rotation)
void set_accel_orientation (uint8_t instance, enum Rotation rotation)
void increment_clip_count (uint8_t instance)
bool enable_fast_sampling (uint8_t instance) const
bool enable_highres_sampling (uint8_t instance) const
uint8_t get_fast_sampling_rate () const
void _notify_new_accel_sensor_rate_sample (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_gyro_sensor_rate_sample (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void notify_accel_fifo_reset (uint8_t instance) __RAMFUNC__
void notify_gyro_fifo_reset (uint8_t instance) __RAMFUNC__
void log_register_change (uint32_t bus_id, const AP_HAL::Device::checkreg &reg) __RAMFUNC__
void Write_GYR (const uint8_t instance, const uint64_t sample_us, const Vector3f &gyro, bool use_sample_timestamp=false) const __RAMFUNC__
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
HAL_Semaphore _sem
float _clip_limit = 15.5f * GRAVITY_MSS
int16_t _id = -1
uint16_t _last_accel_filter_hz
uint16_t _last_gyro_filter_hz
Detailed Description
Definition at line 32 of file AP_InertialSensor_BMI160.h.
Constructor & Destructor Documentation
AP_InertialSensor_BMI160()
AP_InertialSensor_BMI160::AP_InertialSensor_BMI160 (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation) private
Definition at line 121 of file AP_InertialSensor_BMI160.cpp.
Referenced by probe(), and probe().
Member Function Documentation
_check_err_reg()
void AP_InertialSensor_BMI160::_check_err_reg () private
If the macro BMI160_DEBUG is defined, check if there are errors reported on the device's error register and panic if so. The implementation is empty if the BMI160_DEBUG isn't defined.
Definition at line 221 of file AP_InertialSensor_BMI160.cpp.
Referenced by _configure_accel(), _configure_fifo(), and _configure_gyro().
_configure_accel()
bool AP_InertialSensor_BMI160::_configure_accel () private
Configure accelerometer sensor. The device semaphore must already be taken before calling this function.
Returns
true on success, false otherwise.
Definition at line 237 of file AP_InertialSensor_BMI160.cpp.
Referenced by start().
_configure_fifo()
bool AP_InertialSensor_BMI160::_configure_fifo () private
Configure FIFO.
Returns
true on success, false otherwise.
Definition at line 326 of file AP_InertialSensor_BMI160.cpp.
Referenced by start().
_configure_gyro()
bool AP_InertialSensor_BMI160::_configure_gyro () private
Configure gyroscope sensor. The device semaphore must already be taken before calling this function.
Returns
true on success, false otherwise.
Definition at line 264 of file AP_InertialSensor_BMI160.cpp.
Referenced by start().
_configure_int1_pin()
bool AP_InertialSensor_BMI160::_configure_int1_pin () private
Configure INT1 pin as watermark interrupt pin at the level of one sample if using fifo or data-ready pin otherwise.
Returns
true on success, false otherwise.
Definition at line 290 of file AP_InertialSensor_BMI160.cpp.
Referenced by start().
_hardware_init()
bool AP_InertialSensor_BMI160::_hardware_init () private
Try to perform initialization of the BMI160 device.
The device semaphore must be taken and released by the caller.
Returns
true on success, false otherwise.
Definition at line 446 of file AP_InertialSensor_BMI160.cpp.
Referenced by _init().
_init()
bool AP_InertialSensor_BMI160::_init () private
Try to initialize this driver.
Do sensor and other required initializations.
Returns
true on success, false otherwise.
Definition at line 506 of file AP_InertialSensor_BMI160.cpp.
_poll_data()
void AP_InertialSensor_BMI160::_poll_data () private
Device periodic callback to read data from the sensors.
Definition at line 441 of file AP_InertialSensor_BMI160.cpp.
Referenced by start().
_read_fifo()
void AP_InertialSensor_BMI160::_read_fifo () private
Read samples from fifo.
Definition at line 358 of file AP_InertialSensor_BMI160.cpp.
Referenced by _poll_data().
probe() [1/2]
AP_InertialSensor_Backend * AP_InertialSensor_BMI160::probe (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, enum Rotation rotation = BMI160_DEFAULT_ROTATION) static
Definition at line 153 of file AP_InertialSensor_BMI160.cpp.
probe() [2/2]
AP_InertialSensor_Backend * AP_InertialSensor_BMI160::probe (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev, enum Rotation rotation = BMI160_DEFAULT_ROTATION) static
Definition at line 131 of file AP_InertialSensor_BMI160.cpp.
start()
void AP_InertialSensor_BMI160::start (void) override virtual
Configure the sensors and start reading routine.
Reimplemented from AP_InertialSensor_Backend.
Definition at line 174 of file AP_InertialSensor_BMI160.cpp.
update()
bool AP_InertialSensor_BMI160::update (void) override virtual
Implements AP_InertialSensor_Backend.
Definition at line 214 of file AP_InertialSensor_BMI160.cpp.
Member Data Documentation
_accel_instance
uint8_t AP_InertialSensor_BMI160::_accel_instance private
Definition at line 123 of file AP_InertialSensor_BMI160.h.
Referenced by _read_fifo(), start(), and update().
_accel_scale
float AP_InertialSensor_BMI160::_accel_scale private
Definition at line 124 of file AP_InertialSensor_BMI160.h.
Referenced by _configure_accel(), and _read_fifo().
_dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_InertialSensor_BMI160::_dev private
Definition at line 120 of file AP_InertialSensor_BMI160.h.
Referenced by _check_err_reg(), _configure_accel(), _configure_fifo(), _configure_gyro(), _configure_int1_pin(), _hardware_init(), _init(), _read_fifo(), and start().
_gyro_instance
uint8_t AP_InertialSensor_BMI160::_gyro_instance private
Definition at line 126 of file AP_InertialSensor_BMI160.h.
Referenced by _read_fifo(), start(), and update().
_gyro_scale
float AP_InertialSensor_BMI160::_gyro_scale private
Definition at line 127 of file AP_InertialSensor_BMI160.h.
Referenced by _configure_gyro(), and _read_fifo().
_int1_pin
AP_HAL::DigitalSource* AP_InertialSensor_BMI160::_int1_pin private
Definition at line 129 of file AP_InertialSensor_BMI160.h.
Referenced by _configure_int1_pin(), and _read_fifo().
_rotation
enum Rotation AP_InertialSensor_BMI160::_rotation private
Definition at line 121 of file AP_InertialSensor_BMI160.h.
Referenced by _read_fifo().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_BMI160.h
libraries/AP_InertialSensor/AP_InertialSensor_BMI160.cpp