APM:Libraries: AP_AK09916_BusDriver Class Reference
AP_AK09916_BusDriver Class Reference abstract
#include <AP_Compass_AK09916.h>
Public Member Functions
virtual ~AP_AK09916_BusDriver ()
virtual bool block_read (uint8_t reg, uint8_t *buf, uint32_t size)=0
virtual bool register_read (uint8_t reg, uint8_t *val)=0
virtual bool register_write (uint8_t reg, uint8_t val, bool checked=false)=0
virtual AP_HAL::Semaphore * get_semaphore ()=0
virtual bool configure ()
virtual bool start_measurements ()
virtual AP_HAL::Device::PeriodicHandle register_periodic_callback (uint32_t, AP_HAL::Device::PeriodicCb)=0
virtual void set_device_type (uint8_t devtype)=0
virtual uint32_t get_bus_id (void) const =0
virtual void setup_checked_registers (uint8_t num_regs)
virtual void check_next_register (void)
Detailed Description
Definition at line 112 of file AP_Compass_AK09916.h.
Constructor & Destructor Documentation
~AP_AK09916_BusDriver()
virtual AP_AK09916_BusDriver::~AP_AK09916_BusDriver () inline virtual
Definition at line 115 of file AP_Compass_AK09916.h.
Member Function Documentation
block_read()
virtual bool AP_AK09916_BusDriver::block_read (uint8_t reg, uint8_t * buf, uint32_t size) pure virtual
Implemented in AP_AK09916_BusDriver_HALDevice, and AP_AK09916_BusDriver_Auxiliary.
Referenced by AP_Compass_AK09916::_update().
check_next_register()
virtual void AP_AK09916_BusDriver::check_next_register (void) inline virtual
Reimplemented in AP_AK09916_BusDriver_HALDevice.
Definition at line 139 of file AP_Compass_AK09916.h.
Referenced by AP_Compass_AK09916::_update().
configure()
virtual bool AP_AK09916_BusDriver::configure () inline virtual
Reimplemented in AP_AK09916_BusDriver_Auxiliary.
Definition at line 123 of file AP_Compass_AK09916.h.
Referenced by AP_Compass_AK09916::init().
get_bus_id()
virtual uint32_t AP_AK09916_BusDriver::get_bus_id (void) const pure virtual
Implemented in AP_AK09916_BusDriver_HALDevice, and AP_AK09916_BusDriver_Auxiliary.
Referenced by AP_Compass_AK09916::init().
get_semaphore()
virtual AP_HAL::Semaphore * AP_AK09916_BusDriver::get_semaphore () pure virtual
Implemented in AP_AK09916_BusDriver_HALDevice, and AP_AK09916_BusDriver_Auxiliary.
Referenced by AP_Compass_AK09916::init().
register_periodic_callback()
virtual AP_HAL::Device::PeriodicHandle AP_AK09916_BusDriver::register_periodic_callback (uint32_t , AP_HAL::Device::PeriodicCb) pure virtual
Implemented in AP_AK09916_BusDriver_HALDevice, and AP_AK09916_BusDriver_Auxiliary.
Referenced by AP_Compass_AK09916::init().
register_read()
virtual bool AP_AK09916_BusDriver::register_read (uint8_t reg, uint8_t * val) pure virtual
Implemented in AP_AK09916_BusDriver_HALDevice, and AP_AK09916_BusDriver_Auxiliary.
Referenced by AP_Compass_AK09916::_check_id().
register_write()
virtual bool AP_AK09916_BusDriver::register_write (uint8_t reg, uint8_t val, bool checked = false) pure virtual
Implemented in AP_AK09916_BusDriver_HALDevice, and AP_AK09916_BusDriver_Auxiliary.
Referenced by AP_Compass_AK09916::_reset(), and AP_Compass_AK09916::_setup_mode().
set_device_type()
virtual void AP_AK09916_BusDriver::set_device_type (uint8_t devtype) pure virtual
Implemented in AP_AK09916_BusDriver_HALDevice, and AP_AK09916_BusDriver_Auxiliary.
Referenced by AP_Compass_AK09916::init().
setup_checked_registers()
virtual void AP_AK09916_BusDriver::setup_checked_registers (uint8_t num_regs) inline virtual
setup for register value checking. Frequency is how often to check registers. If set to 10 then every 10th call to check_next_register will check a register
Reimplemented in AP_AK09916_BusDriver_HALDevice.
Definition at line 138 of file AP_Compass_AK09916.h.
Referenced by AP_Compass_AK09916::init().
start_measurements()
virtual bool AP_AK09916_BusDriver::start_measurements () inline virtual
Reimplemented in AP_AK09916_BusDriver_Auxiliary.
Definition at line 124 of file AP_Compass_AK09916.h.
Referenced by AP_Compass_AK09916::init().
The documentation for this class was generated from the following file:
libraries/AP_Compass/AP_Compass_AK09916.h