APM:Libraries: AP_AHRS_Backend Class Reference
AP_AHRS_Backend Class Reference abstract
#include <AP_AHRS_Backend.h>
Classes
struct Estimates
Public Member Functions
AP_AHRS_Backend ()
virtual ~AP_AHRS_Backend ()
CLASS_NO_COPY (AP_AHRS_Backend)
virtual void init ()
virtual int8_t get_primary_core_index () const
virtual uint8_t get_primary_accel_index (void) const
virtual uint8_t get_primary_gyro_index (void) const
virtual void update ()=0
virtual void get_results (Estimates &results)=0
virtual bool pre_arm_check (bool requires_position, char *failure_msg, uint8_t failure_msg_len) const =0
virtual bool attitudes_consistent (char *failure_msg, const uint8_t failure_msg_len) const
virtual void check_lane_switch (void)
virtual bool using_noncompass_for_yaw (void) const
virtual bool using_extnav_for_yaw (void) const
virtual void request_yaw_reset (void)
virtual void set_posvelyaw_source_set (uint8_t source_set_idx)
virtual void reset_gyro_drift (void)=0
virtual void reset ()=0
virtual bool get_hagl (float &height) const WARN_IF_UNUSED
virtual bool wind_estimate (Vector3f &wind) const =0
virtual bool airspeed_estimate (float &airspeed_ret) const WARN_IF_UNUSED
virtual bool airspeed_estimate (uint8_t airspeed_index, float &airspeed_ret) const
bool airspeed_estimate_true (float &airspeed_ret) const WARN_IF_UNUSED
virtual bool airspeed_vector_true (Vector3f &vec) const WARN_IF_UNUSED
virtual Vector2f groundspeed_vector (void)=0
virtual bool get_velocity_NED (Vector3f &vec) const WARN_IF_UNUSED
virtual bool get_vert_pos_rate_D (float &velocity) const =0
virtual bool get_mag_field_correction (Vector3f &ret) const WARN_IF_UNUSED
virtual bool get_mag_field_NED (Vector3f &vec) const
virtual bool get_mag_offsets (uint8_t mag_idx, Vector3f &magOffsets) const
virtual bool set_origin (const Location &loc)
virtual bool get_origin (Location &ret) const =0
virtual bool get_relative_position_NED_origin (Vector3f &vec) const WARN_IF_UNUSED
virtual bool get_relative_position_NE_origin (Vector2f &vecNE) const WARN_IF_UNUSED
virtual bool get_relative_position_D_origin (float &posD) const WARN_IF_UNUSED
float groundspeed (void)
virtual bool use_compass (void)=0
virtual bool get_quaternion (Quaternion &quat) const WARN_IF_UNUSED=0
virtual bool have_inertial_nav (void) const
virtual bool healthy (void) const =0
virtual bool initialised (void) const
virtual bool started (void) const
virtual uint32_t getLastYawResetAngle (float &yawAng)
virtual uint32_t getLastPosNorthEastReset (Vector2f &pos) WARN_IF_UNUSED
virtual uint32_t getLastVelNorthEastReset (Vector2f &vel) const WARN_IF_UNUSED
virtual uint32_t getLastPosDownReset (float &posDelta) WARN_IF_UNUSED
virtual bool resetHeightDatum (void) WARN_IF_UNUSED
virtual bool get_innovations (Vector3f &velInnov, Vector3f &posInnov, Vector3f &magInnov, float &tasInnov, float &yawInnov) const
virtual bool get_filter_status (union nav_filter_status &status) const
virtual bool get_variances (float &velVar, float &posVar, float &hgtVar, Vector3f &magVar, float &tasVar) const
virtual bool get_vel_innovations_and_variances_for_source (uint8_t source, Vector3f &innovations, Vector3f &variances) const WARN_IF_UNUSED
virtual void send_ekf_status_report (class GCS_MAVLINK &link) const =0
virtual bool get_hgt_ctrl_limit (float &limit) const WARN_IF_UNUSED
virtual void set_terrain_hgt_stable (bool stable)
virtual void get_control_limits (float &ekfGndSpdLimit, float &controlScaleXY) const =0
Static Public Member Functions
static float get_EAS2TAS (void)
static bool airspeed_sensor_enabled (void)
static bool airspeed_sensor_enabled (uint8_t airspeed_index)
Detailed Description
Definition at line 39 of file AP_AHRS_Backend.h.
Constructor & Destructor Documentation
AP_AHRS_Backend()
AP_AHRS_Backend::AP_AHRS_Backend () inline
Definition at line 44 of file AP_AHRS_Backend.h.
~AP_AHRS_Backend()
virtual AP_AHRS_Backend::~AP_AHRS_Backend () inline virtual
Definition at line 47 of file AP_AHRS_Backend.h.
Member Function Documentation
airspeed_estimate() [1/2]
virtual bool AP_AHRS_Backend::airspeed_estimate (float & airspeed_ret) const inline virtual
Definition at line 137 of file AP_AHRS_Backend.h.
Referenced by airspeed_estimate_true().
airspeed_estimate() [2/2]
virtual bool AP_AHRS_Backend::airspeed_estimate (uint8_t airspeed_index, float & airspeed_ret) const inline virtual
Definition at line 138 of file AP_AHRS_Backend.h.
airspeed_estimate_true()
bool AP_AHRS_Backend::airspeed_estimate_true (float & airspeed_ret) const inline
Definition at line 142 of file AP_AHRS_Backend.h.
airspeed_sensor_enabled() [1/2]
static bool AP_AHRS_Backend::airspeed_sensor_enabled (uint8_t airspeed_index) inline static
Definition at line 172 of file AP_AHRS_Backend.h.
airspeed_sensor_enabled() [2/2]
static bool AP_AHRS_Backend::airspeed_sensor_enabled (void) inline static
Definition at line 161 of file AP_AHRS_Backend.h.
Referenced by AP_AHRS::airspeed_sensor_enabled(), and AP_AHRS::airspeed_sensor_enabled().
airspeed_vector_true()
virtual bool AP_AHRS_Backend::airspeed_vector_true (Vector3f & vec) const inline virtual
Definition at line 152 of file AP_AHRS_Backend.h.
attitudes_consistent()
virtual bool AP_AHRS_Backend::attitudes_consistent (char * failure_msg, const uint8_t failure_msg_len) const inline virtual
Definition at line 105 of file AP_AHRS_Backend.h.
check_lane_switch()
virtual void AP_AHRS_Backend::check_lane_switch (void) inline virtual
Definition at line 108 of file AP_AHRS_Backend.h.
CLASS_NO_COPY()
AP_AHRS_Backend::CLASS_NO_COPY (AP_AHRS_Backend)
get_control_limits()
virtual void AP_AHRS_Backend::get_control_limits (float & ekfGndSpdLimit, float & controlScaleXY) const pure virtual
get_EAS2TAS()
float AP_AHRS_Backend::get_EAS2TAS (void) static
Definition at line 267 of file AP_AHRS_Backend.cpp.
Referenced by airspeed_estimate_true(), and AP_AHRS::update_state().
get_filter_status()
virtual bool AP_AHRS_Backend::get_filter_status (union nav_filter_status & status) const inline virtual
Definition at line 300 of file AP_AHRS_Backend.h.
get_hagl()
virtual bool AP_AHRS_Backend::get_hagl (float & height) const inline virtual
Definition at line 130 of file AP_AHRS_Backend.h.
get_hgt_ctrl_limit()
virtual bool AP_AHRS_Backend::get_hgt_ctrl_limit (float & limit) const inline virtual
Definition at line 323 of file AP_AHRS_Backend.h.
get_innovations()
virtual bool AP_AHRS_Backend::get_innovations (Vector3f & velInnov, Vector3f & posInnov, Vector3f & magInnov, float & tasInnov, float & yawInnov) const inline virtual
Definition at line 296 of file AP_AHRS_Backend.h.
get_mag_field_correction()
virtual bool AP_AHRS_Backend::get_mag_field_correction (Vector3f & ret) const inline virtual
Definition at line 196 of file AP_AHRS_Backend.h.
get_mag_field_NED()
virtual bool AP_AHRS_Backend::get_mag_field_NED (Vector3f & vec) const inline virtual
Definition at line 200 of file AP_AHRS_Backend.h.
get_mag_offsets()
virtual bool AP_AHRS_Backend::get_mag_offsets (uint8_t mag_idx, Vector3f & magOffsets) const inline virtual
Definition at line 204 of file AP_AHRS_Backend.h.
get_origin()
virtual bool AP_AHRS_Backend::get_origin (Location & ret) const pure virtual
get_primary_accel_index()
virtual uint8_t AP_AHRS_Backend::get_primary_accel_index (void) const inline virtual
Definition at line 78 of file AP_AHRS_Backend.h.
get_primary_core_index()
virtual int8_t AP_AHRS_Backend::get_primary_core_index () const inline virtual
Definition at line 75 of file AP_AHRS_Backend.h.
get_primary_gyro_index()
virtual uint8_t AP_AHRS_Backend::get_primary_gyro_index (void) const inline virtual
Definition at line 87 of file AP_AHRS_Backend.h.
get_quaternion()
virtual bool AP_AHRS_Backend::get_quaternion (Quaternion & quat) const pure virtual
get_relative_position_D_origin()
virtual bool AP_AHRS_Backend::get_relative_position_D_origin (float & posD) const inline virtual
Definition at line 229 of file AP_AHRS_Backend.h.
get_relative_position_NE_origin()
virtual bool AP_AHRS_Backend::get_relative_position_NE_origin (Vector2f & vecNE) const inline virtual
Definition at line 223 of file AP_AHRS_Backend.h.
get_relative_position_NED_origin()
virtual bool AP_AHRS_Backend::get_relative_position_NED_origin (Vector3f & vec) const inline virtual
Definition at line 217 of file AP_AHRS_Backend.h.
get_results()
virtual void AP_AHRS_Backend::get_results (Estimates & results) pure virtual
get_variances()
virtual bool AP_AHRS_Backend::get_variances (float & velVar, float & posVar, float & hgtVar, Vector3f & magVar, float & tasVar) const inline virtual
Definition at line 308 of file AP_AHRS_Backend.h.
get_vel_innovations_and_variances_for_source()
virtual bool AP_AHRS_Backend::get_vel_innovations_and_variances_for_source (uint8_t source, Vector3f & innovations, Vector3f & variances) const inline virtual
Definition at line 314 of file AP_AHRS_Backend.h.
get_velocity_NED()
virtual bool AP_AHRS_Backend::get_velocity_NED (Vector3f & vec) const inline virtual
Definition at line 187 of file AP_AHRS_Backend.h.
get_vert_pos_rate_D()
virtual bool AP_AHRS_Backend::get_vert_pos_rate_D (float & velocity) const pure virtual
getLastPosDownReset()
virtual uint32_t AP_AHRS_Backend::getLastPosDownReset (float & posDelta) inline virtual
Definition at line 281 of file AP_AHRS_Backend.h.
getLastPosNorthEastReset()
virtual uint32_t AP_AHRS_Backend::getLastPosNorthEastReset (Vector2f & pos) inline virtual
Definition at line 269 of file AP_AHRS_Backend.h.
getLastVelNorthEastReset()
virtual uint32_t AP_AHRS_Backend::getLastVelNorthEastReset (Vector2f & vel) const inline virtual
Definition at line 275 of file AP_AHRS_Backend.h.
getLastYawResetAngle()
virtual uint32_t AP_AHRS_Backend::getLastYawResetAngle (float & yawAng) inline virtual
Definition at line 263 of file AP_AHRS_Backend.h.
groundspeed()
float AP_AHRS_Backend::groundspeed (void) inline
Definition at line 234 of file AP_AHRS_Backend.h.
groundspeed_vector()
virtual Vector2f AP_AHRS_Backend::groundspeed_vector (void) pure virtual
Referenced by groundspeed().
have_inertial_nav()
virtual bool AP_AHRS_Backend::have_inertial_nav (void) const inline virtual
Definition at line 246 of file AP_AHRS_Backend.h.
healthy()
virtual bool AP_AHRS_Backend::healthy (void) const pure virtual
init()
void AP_AHRS_Backend::init () virtual
Definition at line 30 of file AP_AHRS_Backend.cpp.
initialised()
virtual bool AP_AHRS_Backend::initialised (void) const inline virtual
Definition at line 254 of file AP_AHRS_Backend.h.
Referenced by started().
pre_arm_check()
virtual bool AP_AHRS_Backend::pre_arm_check (bool requires_position, char * failure_msg, uint8_t failure_msg_len) const pure virtual
request_yaw_reset()
virtual void AP_AHRS_Backend::request_yaw_reset (void) inline virtual
Definition at line 117 of file AP_AHRS_Backend.h.
reset()
virtual void AP_AHRS_Backend::reset () pure virtual
reset_gyro_drift()
virtual void AP_AHRS_Backend::reset_gyro_drift (void) pure virtual
resetHeightDatum()
virtual bool AP_AHRS_Backend::resetHeightDatum (void) inline virtual
Definition at line 290 of file AP_AHRS_Backend.h.
send_ekf_status_report()
virtual void AP_AHRS_Backend::send_ekf_status_report (class GCS_MAVLINK & link) const pure virtual
set_origin()
virtual bool AP_AHRS_Backend::set_origin (const Location & loc) inline virtual
Definition at line 209 of file AP_AHRS_Backend.h.
set_posvelyaw_source_set()
virtual void AP_AHRS_Backend::set_posvelyaw_source_set (uint8_t source_set_idx) inline virtual
Definition at line 120 of file AP_AHRS_Backend.h.
set_terrain_hgt_stable()
virtual void AP_AHRS_Backend::set_terrain_hgt_stable (bool stable) inline virtual
Definition at line 327 of file AP_AHRS_Backend.h.
started()
virtual bool AP_AHRS_Backend::started (void) const inline virtual
Definition at line 257 of file AP_AHRS_Backend.h.
update()
virtual void AP_AHRS_Backend::update () pure virtual
use_compass()
virtual bool AP_AHRS_Backend::use_compass (void) pure virtual
using_extnav_for_yaw()
virtual bool AP_AHRS_Backend::using_extnav_for_yaw (void) const inline virtual
Definition at line 114 of file AP_AHRS_Backend.h.
using_noncompass_for_yaw()
virtual bool AP_AHRS_Backend::using_noncompass_for_yaw (void) const inline virtual
Definition at line 111 of file AP_AHRS_Backend.h.
wind_estimate()
virtual bool AP_AHRS_Backend::wind_estimate (Vector3f & wind) const pure virtual
The documentation for this class was generated from the following files:
libraries/AP_AHRS/AP_AHRS_Backend.h
libraries/AP_AHRS/AP_AHRS_Backend.cpp