APM:Libraries: LowPassFilter< T > Class Template Reference
LowPassFilter< T > Class Template Reference
#include <LowPassFilter.h>
Public Member Functions
LowPassFilter ()
LowPassFilter (float cutoff_freq)
LowPassFilter (float sample_freq, float cutoff_freq)
CLASS_NO_COPY (LowPassFilter)
void set_cutoff_frequency (float cutoff_freq)
void set_cutoff_frequency (float sample_freq, float cutoff_freq)
float get_cutoff_freq (void) const
T apply (T sample, float dt)
T apply (T sample)
const T & get () const
void reset (T value)
void reset (void)
Protected Attributes
float _cutoff_freq
Private Attributes
DigitalLPF< T > _filter
Detailed Description
template<class T>
class LowPassFilter< T >
Definition at line 78 of file LowPassFilter.h.
Constructor & Destructor Documentation
LowPassFilter() [1/3]
template<class T > LowPassFilter< T >::LowPassFilter ()
Definition at line 86 of file LowPassFilter.cpp.
LowPassFilter() [2/3]
template<class T > LowPassFilter< T >::LowPassFilter (float cutoff_freq)
Definition at line 90 of file LowPassFilter.cpp.
LowPassFilter() [3/3]
template<class T > LowPassFilter< T >::LowPassFilter (float sample_freq, float cutoff_freq)
Definition at line 94 of file LowPassFilter.cpp.
Member Function Documentation
apply() [1/2]
template<class T > T LowPassFilter< T >::apply (T sample)
Definition at line 123 of file LowPassFilter.cpp.
apply() [2/2]
template<class T > T LowPassFilter< T >::apply (T sample, float dt)
Definition at line 118 of file LowPassFilter.cpp.
Referenced by AP_TECS::_update_throttle_without_airspeed(), apply_to_filter_under_test(), AP_InertialSensor::calc_vibration_and_clipping(), AC_AutoTune_Heli::dwell_test_run(), loop(), SlewLimiter::modifier(), AC_AutoTune_Heli::rate_ff_test_run(), SITL::Battery::set_current(), AP_Proximity_Boundary_3D::set_filtered_distance(), AC_AutoTune_Multi::twitch_test_run(), AP_WindVane::update(), Variometer::update(), AP_AutoTune::update(), AC_Autorotation::update_forward_speed_controller(), AC_Autorotation::update_hs_glide_controller(), Thrust_Linearization::update_lift_max_from_batt_voltage(), SoaringController::update_thermalling(), AP_MotorsHeli::update_throttle_filter(), and AP_MotorsMulticopter::update_throttle_filter().
CLASS_NO_COPY()
template<class T > LowPassFilter< T >::CLASS_NO_COPY (LowPassFilter< T >)
get()
template<class T > const T & LowPassFilter< T >::get () const
Definition at line 128 of file LowPassFilter.cpp.
Referenced by AP_TECS::_update_throttle_without_airspeed(), Thrust_Linearization::apply_thrust_curve_and_volt_scaling(), AC_AutoTune_Heli::dwell_test_run(), Variometer::get_displayed_value(), Variometer::get_filtered_climb(), AP_Proximity_Boundary_3D::get_filtered_distance(), AP_Proximity_Boundary_3D::get_horizontal_object_angle_and_distance(), AP_Proximity_Boundary_3D::get_obstacle_info(), Variometer::get_stf_value(), SoaringController::get_target(), AP_Motors::get_throttle(), AP_Motors::get_throttle_bidirectional(), Variometer::get_trigger_value(), AP_InertialSensor::get_vibration_levels(), SITL::Battery::get_voltage(), AC_AutoTune_Heli::rate_ff_test_run(), Thrust_Linearization::remove_thrust_curve_and_volt_scaling(), AP_Proximity_Boundary_3D::set_face_attributes(), AP_Proximity_Boundary_3D::update_boundary(), Thrust_Linearization::update_lift_max_from_batt_voltage(), AP_MotorsHeli::update_throttle_filter(), and AP_MotorsMulticopter::update_throttle_filter().
get_cutoff_freq()
template<class T > float LowPassFilter< T >::get_cutoff_freq (void) const
Definition at line 113 of file LowPassFilter.cpp.
Referenced by AP_Proximity_Boundary_3D::set_filtered_distance().
reset() [1/2]
template<class T > void LowPassFilter< T >::reset (T value)
Definition at line 133 of file LowPassFilter.cpp.
Referenced by AP_TECS::_initialise_states(), AP_Motors::AP_Motors(), AC_AutoTune::control_attitude(), AC_AutoTune_Heli::dwell_test_init(), AC_AutoTune_Heli::dwell_test_run(), AC_Autorotation::init_hs_controller(), SoaringController::init_thermalling(), SITL::Battery::init_voltage(), loop(), AP_MotorsHeli::output_disarmed(), AC_AutoTune_Heli::rate_ff_test_init(), AC_AutoTune_Heli::rate_ff_test_run(), reset_all(), Variometer::reset_climb_filter(), Variometer::reset_trigger_filter(), AP_MotorsHeli_Dual::servo_test(), AP_MotorsHeli_Single::servo_test(), AP_Proximity_Boundary_3D::set_filtered_distance(), SlewLimiter::SlewLimiter(), AP_AutoTune::start(), Thrust_Linearization::Thrust_Linearization(), AC_AutoTune_Multi::twitch_test_init(), Thrust_Linearization::update_lift_max_from_batt_voltage(), AP_MotorsHeli::update_throttle_filter(), and AP_MotorsMulticopter::update_throttle_filter().
reset() [2/2]
template<class T > void LowPassFilter< T >::reset (void) inline
Definition at line 96 of file LowPassFilter.h.
set_cutoff_frequency() [1/2]
template<class T > void LowPassFilter< T >::set_cutoff_frequency (float cutoff_freq)
Definition at line 101 of file LowPassFilter.cpp.
Referenced by AP_TECS::_initialise_states(), AP_InertialSensor::AP_InertialSensor(), AP_Motors::AP_Motors(), AP_Proximity_Boundary_3D::apply_filter_freq(), AC_AutoTune_Heli::dwell_test_init(), AC_AutoTune_Heli::rate_ff_test_init(), AP_Motors::set_slew_filter_cutoff(), AP_Motors::set_throttle_filter_cutoff(), setup(), SlewLimiter::SlewLimiter(), AP_AutoTune::start(), Thrust_Linearization::Thrust_Linearization(), AC_AutoTune_Multi::twitch_test_init(), AP_WindVane::update(), Variometer::update(), AC_Autorotation::update_forward_speed_controller(), AC_Autorotation::update_hs_glide_controller(), and SoaringController::update_thermalling().
set_cutoff_frequency() [2/2]
template<class T > void LowPassFilter< T >::set_cutoff_frequency (float sample_freq, float cutoff_freq)
Definition at line 106 of file LowPassFilter.cpp.
Member Data Documentation
_cutoff_freq
template<class T > float LowPassFilter< T >::_cutoff_freq protected
Definition at line 99 of file LowPassFilter.h.
_filter
template<class T > DigitalLPF<T> LowPassFilter< T >::_filter private
Definition at line 102 of file LowPassFilter.h.
Referenced by LowPassFilter< T >::reset().
The documentation for this class was generated from the following files:
libraries/Filter/LowPassFilter.h
libraries/Filter/LowPassFilter.cpp