APM:Libraries: HAL_SITL Class Reference
HAL_SITL Class Reference
#include <HAL_SITL_Class.h>
Public Member Functions
HAL_SITL ()
void run (int argc, char *const argv[], Callbacks *callbacks) const override
void set_storage_posix_enabled (bool _enabled)
bool get_storage_posix_enabled () const
void set_storage_flash_enabled (bool _enabled)
bool get_storage_flash_enabled () const
void set_storage_fram_enabled (bool _enabled)
bool get_storage_fram_enabled () const
void set_wipe_storage (bool _wipe_storage)
bool get_wipe_storage () const
uint8_t get_instance () const
Public Member Functions inherited from AP_HAL::HAL
HAL (AP_HAL::UARTDriver *_serial0, AP_HAL::UARTDriver *_serial1, AP_HAL::UARTDriver *_serial2, AP_HAL::UARTDriver *_serial3, AP_HAL::UARTDriver *_serial4, AP_HAL::UARTDriver *_serial5, AP_HAL::UARTDriver *_serial6, AP_HAL::UARTDriver *_serial7, AP_HAL::UARTDriver *_serial8, AP_HAL::UARTDriver *_serial9, AP_HAL::I2CDeviceManager *_i2c_mgr, AP_HAL::SPIDeviceManager *_spi, AP_HAL::WSPIDeviceManager *_wspi, AP_HAL::AnalogIn *_analogin, AP_HAL::Storage *_storage, AP_HAL::UARTDriver *_console, AP_HAL::GPIO *_gpio, AP_HAL::RCInput *_rcin, AP_HAL::RCOutput *_rcout, AP_HAL::Scheduler *_scheduler, AP_HAL::Util *_util, AP_HAL::OpticalFlow *_opticalflow, AP_HAL::Flash *_flash, AP_HAL::DSP *_dsp, AP_HAL::CANIface **_can_ifaces)
UARTDriver * serial (uint8_t sernum) const
Static Public Member Functions
static void actually_reboot ()
Private Member Functions
void setup_signal_handlers () const
Static Private Member Functions
static void exit_signal_handler (int)
Private Attributes
HALSITL::SITL_State * _sitl_state
bool storage_posix_enabled = true
bool storage_flash_enabled
bool storage_fram_enabled
bool wipe_storage
Additional Inherited Members
Public Attributes inherited from AP_HAL::HAL
AP_HAL::I2CDeviceManager * i2c_mgr
AP_HAL::SPIDeviceManager * spi
AP_HAL::WSPIDeviceManager * wspi
AP_HAL::AnalogIn * analogin
AP_HAL::Storage * storage
AP_HAL::UARTDriver * console
AP_HAL::GPIO * gpio
AP_HAL::RCInput * rcin
AP_HAL::RCOutput * rcout
AP_HAL::Scheduler * scheduler
AP_HAL::Util * util
AP_HAL::OpticalFlow * opticalflow
AP_HAL::Flash * flash
AP_HAL::DSP * dsp
AP_HAL::CANIface ** can
Static Public Attributes inherited from AP_HAL::HAL
static constexpr uint8_t num_serial = 10
Detailed Description
Definition at line 11 of file HAL_SITL_Class.h.
Constructor & Destructor Documentation
HAL_SITL()
HAL_SITL::HAL_SITL ()
Definition at line 87 of file HAL_SITL_Class.cpp.
Member Function Documentation
actually_reboot()
void HAL_SITL::actually_reboot () static
Definition at line 303 of file HAL_SITL_Class.cpp.
Referenced by HALSITL::Scheduler::reboot(), and run().
exit_signal_handler()
void HAL_SITL::exit_signal_handler (int signum) static private
Definition at line 167 of file HAL_SITL_Class.cpp.
Referenced by setup_signal_handlers().
get_instance()
uint8_t HAL_SITL::get_instance () const
Definition at line 197 of file HAL_SITL_Class.cpp.
get_storage_flash_enabled()
bool HAL_SITL::get_storage_flash_enabled () const inline
Definition at line 24 of file HAL_SITL_Class.h.
get_storage_fram_enabled()
bool HAL_SITL::get_storage_fram_enabled () const inline
Definition at line 28 of file HAL_SITL_Class.h.
get_storage_posix_enabled()
bool HAL_SITL::get_storage_posix_enabled () const inline
Definition at line 20 of file HAL_SITL_Class.h.
get_wipe_storage()
bool HAL_SITL::get_wipe_storage () const inline
Definition at line 36 of file HAL_SITL_Class.h.
Referenced by SITL::JEDEC::open_storage_fd(), and SITL::RAMTRON::open_storage_fd().
run()
void HAL_SITL::run (int argc, char *const argv[], Callbacks * callbacks) const override virtual
Implements AP_HAL::HAL.
Definition at line 209 of file HAL_SITL_Class.cpp.
set_storage_flash_enabled()
void HAL_SITL::set_storage_flash_enabled (bool _enabled) inline
Definition at line 21 of file HAL_SITL_Class.h.
set_storage_fram_enabled()
void HAL_SITL::set_storage_fram_enabled (bool _enabled) inline
Definition at line 25 of file HAL_SITL_Class.h.
set_storage_posix_enabled()
void HAL_SITL::set_storage_posix_enabled (bool _enabled) inline
Definition at line 17 of file HAL_SITL_Class.h.
set_wipe_storage()
void HAL_SITL::set_wipe_storage (bool _wipe_storage) inline
Definition at line 33 of file HAL_SITL_Class.h.
setup_signal_handlers()
void HAL_SITL::setup_signal_handlers () const private
Definition at line 172 of file HAL_SITL_Class.cpp.
Referenced by run().
Member Data Documentation
_sitl_state
HALSITL::SITL_State* HAL_SITL::_sitl_state private
Definition at line 45 of file HAL_SITL_Class.h.
Referenced by get_instance(), and run().
storage_flash_enabled
bool HAL_SITL::storage_flash_enabled private
Definition at line 51 of file HAL_SITL_Class.h.
Referenced by get_storage_flash_enabled(), and set_storage_flash_enabled().
storage_fram_enabled
bool HAL_SITL::storage_fram_enabled private
Definition at line 52 of file HAL_SITL_Class.h.
Referenced by get_storage_fram_enabled(), and set_storage_fram_enabled().
storage_posix_enabled
bool HAL_SITL::storage_posix_enabled = true private
Definition at line 50 of file HAL_SITL_Class.h.
Referenced by get_storage_posix_enabled(), and set_storage_posix_enabled().
wipe_storage
bool HAL_SITL::wipe_storage private
Definition at line 55 of file HAL_SITL_Class.h.
Referenced by get_wipe_storage(), and set_wipe_storage().
The documentation for this class was generated from the following files:
libraries/AP_HAL_SITL/HAL_SITL_Class.h
libraries/AP_HAL_SITL/HAL_SITL_Class.cpp