APM:Libraries: AP_InertialSensor_BMI270 Class Reference
AP_InertialSensor_BMI270 Class Reference
#include <AP_InertialSensor_BMI270.h>
Public Member Functions
void start () override
bool update () override
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void accumulate ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t get_id () const
float get_clip_limit () const
virtual bool get_output_banner (char *banner, uint8_t banner_len)
Static Public Member Functions
static AP_InertialSensor_Backend * probe (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev, enum Rotation rotation=BMI270_DEFAULT_ROTATION)
static AP_InertialSensor_Backend * probe (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, enum Rotation rotation=BMI270_DEFAULT_ROTATION)
Private Member Functions
AP_InertialSensor_BMI270 (AP_InertialSensor &imu, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation)
bool read_registers (uint8_t reg, uint8_t *data, uint8_t len)
bool write_register (uint8_t reg, uint8_t v)
void check_err_reg ()
bool hardware_init ()
bool init ()
void configure_accel ()
void configure_gyro ()
void fifo_reset ()
void configure_fifo ()
void read_fifo ()
void parse_accel_frame (const uint8_t *d)
void parse_gyro_frame (const uint8_t *d)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _dev
AP_HAL::Device::PeriodicHandle periodic_handle
enum Rotation _rotation
uint8_t _accel_instance
uint8_t _gyro_instance
uint8_t temperature_counter
Static Private Attributes
static const uint8_t maximum_fifo_config_file []
Additional Inherited Members
Public Types inherited from AP_InertialSensor_Backend
enum DevTypes {
DEVTYPE_BMI160 = 0x09 , DEVTYPE_L3G4200D = 0x10 , DEVTYPE_ACC_LSM303D = 0x11 , DEVTYPE_ACC_BMA180 = 0x12 ,
DEVTYPE_ACC_MPU6000 = 0x13 , DEVTYPE_ACC_MPU9250 = 0x16 , DEVTYPE_ACC_IIS328DQ = 0x17 , DEVTYPE_ACC_LSM9DS1 = 0x18 ,
DEVTYPE_GYR_MPU6000 = 0x21 , DEVTYPE_GYR_L3GD20 = 0x22 , DEVTYPE_GYR_MPU9250 = 0x24 , DEVTYPE_GYR_I3G4250D = 0x25 ,
DEVTYPE_GYR_LSM9DS1 = 0x26 , DEVTYPE_INS_ICM20789 = 0x27 , DEVTYPE_INS_ICM20689 = 0x28 , DEVTYPE_INS_BMI055 = 0x29 ,
DEVTYPE_SITL = 0x2A , DEVTYPE_INS_BMI088 = 0x2B , DEVTYPE_INS_ICM20948 = 0x2C , DEVTYPE_INS_ICM20648 = 0x2D ,
DEVTYPE_INS_ICM20649 = 0x2E , DEVTYPE_INS_ICM20602 = 0x2F , DEVTYPE_INS_ICM20601 = 0x30 , DEVTYPE_INS_ADIS1647X = 0x31 ,
DEVTYPE_SERIAL = 0x32 , DEVTYPE_INS_ICM40609 = 0x33 , DEVTYPE_INS_ICM42688 = 0x34 , DEVTYPE_INS_ICM42605 = 0x35 ,
DEVTYPE_INS_ICM40605 = 0x36 , DEVTYPE_INS_IIM42652 = 0x37 , DEVTYPE_BMI270 = 0x38 , DEVTYPE_INS_BMI085 = 0x39 ,
DEVTYPE_INS_ICM42670 = 0x3A , DEVTYPE_INS_ICM45686 = 0x3B , DEVTYPE_INS_SCHA63T = 0x3C
}
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel) __RAMFUNC__
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro) __RAMFUNC__
void _publish_gyro (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void apply_gyro_filters (const uint8_t instance, const Vector3f &gyro)
void save_gyro_window (const uint8_t instance, const Vector3f &gyro, uint8_t phase)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0) __RAMFUNC__
void _notify_new_delta_angle (uint8_t instance, const Vector3f &dangle)
void _publish_accel (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0, bool fsync_set=false) __RAMFUNC__
void _notify_new_delta_velocity (uint8_t instance, const Vector3f &dvelocity)
void _set_accel_oversampling (uint8_t instance, uint8_t n)
void _set_gyro_oversampling (uint8_t instance, uint8_t n)
void _set_accel_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_gyro_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_raw_sample_accel_multiplier (uint8_t instance, uint16_t mul)
void _set_raw_sample_gyro_multiplier (uint8_t instance, uint16_t mul)
void _update_sensor_rate (uint16_t &count, uint32_t &start_us, float &rate_hz) const __RAMFUNC__
bool sensors_converging () const
void _set_accel_max_abs_offset (uint8_t instance, float offset)
float _accel_raw_sample_rate (uint8_t instance) const
void _set_accel_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
float _gyro_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
void _publish_temperature (uint8_t instance, float temperature)
void _inc_accel_error_count (uint8_t instance) __RAMFUNC__
void _inc_gyro_error_count (uint8_t instance) __RAMFUNC__
uint16_t _accel_filter_cutoff (void) const
uint16_t _gyro_filter_cutoff (void) const
uint16_t get_loop_rate_hz (void) const
void update_gyro (uint8_t instance) __RAMFUNC__
void update_accel (uint8_t instance) __RAMFUNC__
void set_gyro_orientation (uint8_t instance, enum Rotation rotation)
void set_accel_orientation (uint8_t instance, enum Rotation rotation)
void increment_clip_count (uint8_t instance)
bool enable_fast_sampling (uint8_t instance) const
bool enable_highres_sampling (uint8_t instance) const
uint8_t get_fast_sampling_rate () const
void _notify_new_accel_sensor_rate_sample (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_gyro_sensor_rate_sample (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void notify_accel_fifo_reset (uint8_t instance) __RAMFUNC__
void notify_gyro_fifo_reset (uint8_t instance) __RAMFUNC__
void log_register_change (uint32_t bus_id, const AP_HAL::Device::checkreg &reg) __RAMFUNC__
void Write_GYR (const uint8_t instance, const uint64_t sample_us, const Vector3f &gyro, bool use_sample_timestamp=false) const __RAMFUNC__
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
HAL_Semaphore _sem
float _clip_limit = 15.5f * GRAVITY_MSS
int16_t _id = -1
uint16_t _last_accel_filter_hz
uint16_t _last_gyro_filter_hz
Detailed Description
Definition at line 30 of file AP_InertialSensor_BMI270.h.
Constructor & Destructor Documentation
AP_InertialSensor_BMI270()
AP_InertialSensor_BMI270::AP_InertialSensor_BMI270 (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation) private
Definition at line 150 of file AP_InertialSensor_BMI270.cpp.
Referenced by probe(), and probe().
Member Function Documentation
check_err_reg()
void AP_InertialSensor_BMI270::check_err_reg () private
If the macro BMI270_DEBUG is defined, check if there are errors reported on the device's error register and panic if so. The implementation is empty if the BMI270_DEBUG isn't defined.
Definition at line 268 of file AP_InertialSensor_BMI270.cpp.
Referenced by configure_accel(), configure_fifo(), and configure_gyro().
configure_accel()
void AP_InertialSensor_BMI270::configure_accel () private
Configure accelerometer sensor. The device semaphore must already be taken before calling this function.
Returns
true on success, false otherwise.
Definition at line 319 of file AP_InertialSensor_BMI270.cpp.
Referenced by start().
configure_fifo()
void AP_InertialSensor_BMI270::configure_fifo () private
Configure FIFO.
Definition at line 344 of file AP_InertialSensor_BMI270.cpp.
Referenced by start().
configure_gyro()
void AP_InertialSensor_BMI270::configure_gyro () private
Configure gyroscope sensor. The device semaphore must already be taken before calling this function.
Returns
true on success, false otherwise.
Definition at line 331 of file AP_InertialSensor_BMI270.cpp.
Referenced by start().
fifo_reset()
void AP_InertialSensor_BMI270::fifo_reset () private
Reset FIFO.
Definition at line 362 of file AP_InertialSensor_BMI270.cpp.
Referenced by configure_fifo(), and read_fifo().
hardware_init()
bool AP_InertialSensor_BMI270::hardware_init () private
Try to perform initialization of the BMI270 device.
The device semaphore must be taken and released by the caller.
Returns
true on success, false otherwise.
Definition at line 509 of file AP_InertialSensor_BMI270.cpp.
Referenced by init().
init()
bool AP_InertialSensor_BMI270::init () private
Try to initialize this driver.
Do sensor and other required initializations.
Returns
true on success, false otherwise.
Definition at line 580 of file AP_InertialSensor_BMI270.cpp.
Referenced by hardware_init().
parse_accel_frame()
void AP_InertialSensor_BMI270::parse_accel_frame (const uint8_t * d) private
Definition at line 478 of file AP_InertialSensor_BMI270.cpp.
Referenced by read_fifo().
parse_gyro_frame()
void AP_InertialSensor_BMI270::parse_gyro_frame (const uint8_t * d) private
Definition at line 494 of file AP_InertialSensor_BMI270.cpp.
Referenced by read_fifo().
probe() [1/2]
AP_InertialSensor_Backend * AP_InertialSensor_BMI270::probe (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, enum Rotation rotation = BMI270_DEFAULT_ROTATION) static
Definition at line 182 of file AP_InertialSensor_BMI270.cpp.
probe() [2/2]
AP_InertialSensor_Backend * AP_InertialSensor_BMI270::probe (AP_InertialSensor & imu, AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev, enum Rotation rotation = BMI270_DEFAULT_ROTATION) static
Definition at line 160 of file AP_InertialSensor_BMI270.cpp.
read_fifo()
void AP_InertialSensor_BMI270::read_fifo (void) private
Read samples from fifo.
Definition at line 374 of file AP_InertialSensor_BMI270.cpp.
Referenced by start().
read_registers()
bool AP_InertialSensor_BMI270::read_registers (uint8_t reg, uint8_t * data, uint8_t len) private
Definition at line 238 of file AP_InertialSensor_BMI270.cpp.
Referenced by check_err_reg(), hardware_init(), read_fifo(), and write_register().
start()
void AP_InertialSensor_BMI270::start (void) override virtual
Configure the sensors and start reading routine.
Reimplemented from AP_InertialSensor_Backend.
Definition at line 203 of file AP_InertialSensor_BMI270.cpp.
update()
bool AP_InertialSensor_BMI270::update (void) override virtual
Implements AP_InertialSensor_Backend.
Definition at line 228 of file AP_InertialSensor_BMI270.cpp.
write_register()
bool AP_InertialSensor_BMI270::write_register (uint8_t reg, uint8_t v) private
Definition at line 256 of file AP_InertialSensor_BMI270.cpp.
Referenced by configure_accel(), configure_fifo(), configure_gyro(), fifo_reset(), and hardware_init().
Member Data Documentation
_accel_instance
uint8_t AP_InertialSensor_BMI270::_accel_instance private
Definition at line 118 of file AP_InertialSensor_BMI270.h.
Referenced by fifo_reset(), parse_accel_frame(), read_fifo(), start(), and update().
_dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_InertialSensor_BMI270::_dev private
Definition at line 113 of file AP_InertialSensor_BMI270.h.
Referenced by hardware_init(), init(), read_fifo(), read_registers(), start(), and write_register().
_gyro_instance
uint8_t AP_InertialSensor_BMI270::_gyro_instance private
Definition at line 119 of file AP_InertialSensor_BMI270.h.
Referenced by fifo_reset(), parse_gyro_frame(), read_fifo(), start(), and update().
_rotation
enum Rotation AP_InertialSensor_BMI270::_rotation private
Definition at line 116 of file AP_InertialSensor_BMI270.h.
Referenced by start().
maximum_fifo_config_file
const uint8_t AP_InertialSensor_BMI270::maximum_fifo_config_file static private
Initial value:
= { BMI270_REG_INIT_DATA,
    0xc8, 0x2e, 0x00, 0x2e, 0x80, 0x2e, 0x1a, 0x00, 0xc8, 0x2e, 0x00, 0x2e, 0xc8, 0x2e, 0x00, 0x2e, 0xc8, 0x2e, 0x00,
    0x2e, 0xc8, 0x2e, 0x00, 0x2e, 0xc8, 0x2e, 0x00, 0x2e, 0xc8, 0x2e, 0x00, 0x2e, 0x90, 0x32, 0x21, 0x2e, 0x59, 0xf5,
    0x10, 0x30, 0x21, 0x2e, 0x6a, 0xf5, 0x1a, 0x24, 0x22, 0x00, 0x80, 0x2e, 0x3b, 0x00, 0xc8, 0x2e, 0x44, 0x47, 0x22,
    0x00, 0x37, 0x00, 0xa4, 0x00, 0xff, 0x0f, 0xd1, 0x00, 0x07, 0xad, 0x80, 0x2e, 0x00, 0xc1, 0x80, 0x2e, 0x00, 0xc1,
    0x80, 0x2e, 0x00, 0xc1, 0x80, 0x2e, 0x00, 0xc1, 0x80, 0x2e, 0x00, 0xc1, 0x80, 0x2e, 0x00, 0xc1, 0x80, 0x2e, 0x00,
    0xc1, 0x80, 0x2e, 0x00, 0xc1, 0x80, 0x2e, 0x00, 0xc1, 0x80, 0x2e, 0x00, 0xc1, 0x80, 0x2e, 0x00, 0xc1, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x11, 0x24, 0xfc, 0xf5, 0x80, 0x30, 0x40, 0x42, 0x50, 0x50, 0x00, 0x30, 0x12, 0x24, 0xeb,
    0x00, 0x03, 0x30, 0x00, 0x2e, 0xc1, 0x86, 0x5a, 0x0e, 0xfb, 0x2f, 0x21, 0x2e, 0xfc, 0xf5, 0x13, 0x24, 0x63, 0xf5,
    0xe0, 0x3c, 0x48, 0x00, 0x22, 0x30, 0xf7, 0x80, 0xc2, 0x42, 0xe1, 0x7f, 0x3a, 0x25, 0xfc, 0x86, 0xf0, 0x7f, 0x41,
    0x33, 0x98, 0x2e, 0xc2, 0xc4, 0xd6, 0x6f, 0xf1, 0x30, 0xf1, 0x08, 0xc4, 0x6f, 0x11, 0x24, 0xff, 0x03, 0x12, 0x24,
    0x00, 0xfc, 0x61, 0x09, 0xa2, 0x08, 0x36, 0xbe, 0x2a, 0xb9, 0x13, 0x24, 0x38, 0x00, 0x64, 0xbb, 0xd1, 0xbe, 0x94,
    0x0a, 0x71, 0x08, 0xd5, 0x42, 0x21, 0xbd, 0x91, 0xbc, 0xd2, 0x42, 0xc1, 0x42, 0x00, 0xb2, 0xfe, 0x82, 0x05, 0x2f,
    0x50, 0x30, 0x21, 0x2e, 0x21, 0xf2, 0x00, 0x2e, 0x00, 0x2e, 0xd0, 0x2e, 0xf0, 0x6f, 0x02, 0x30, 0x02, 0x42, 0x20,
    0x26, 0xe0, 0x6f, 0x02, 0x31, 0x03, 0x40, 0x9a, 0x0a, 0x02, 0x42, 0xf0, 0x37, 0x05, 0x2e, 0x5e, 0xf7, 0x10, 0x08,
    0x12, 0x24, 0x1e, 0xf2, 0x80, 0x42, 0x83, 0x84, 0xf1, 0x7f, 0x0a, 0x25, 0x13, 0x30, 0x83, 0x42, 0x3b, 0x82, 0xf0,
    0x6f, 0x00, 0x2e, 0x00, 0x2e, 0xd0, 0x2e, 0x12, 0x40, 0x52, 0x42, 0x00, 0x2e, 0x12, 0x40, 0x52, 0x42, 0x3e, 0x84,
    0x00, 0x40, 0x40, 0x42, 0x7e, 0x82, 0xe1, 0x7f, 0xf2, 0x7f, 0x98, 0x2e, 0x6a, 0xd6, 0x21, 0x30, 0x23, 0x2e, 0x61,
    0xf5, 0xeb, 0x2c, 0xe1, 0x6f
}
The following device config microcode has the following copyright:
Copyright (c) 2020 Bosch Sensortec GmbH. All rights reserved.
BSD-3-Clause
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 105 of file AP_InertialSensor_BMI270.h.
Referenced by hardware_init().
periodic_handle
AP_HAL::Device::PeriodicHandle AP_InertialSensor_BMI270::periodic_handle private
Definition at line 114 of file AP_InertialSensor_BMI270.h.
Referenced by read_fifo(), and start().
temperature_counter
uint8_t AP_InertialSensor_BMI270::temperature_counter private
Definition at line 120 of file AP_InertialSensor_BMI270.h.
Referenced by read_fifo().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_BMI270.h
libraries/AP_InertialSensor/AP_InertialSensor_BMI270.cpp