APM:Libraries: AP_HAL::GPIO Class Reference
AP_HAL::GPIO Class Reference abstract
#include <GPIO.h>
Public Types
enum INTERRUPT_TRIGGER_TYPE { INTERRUPT_NONE , INTERRUPT_FALLING , INTERRUPT_RISING , INTERRUPT_BOTH }
Public Member Functions
GPIO ()
virtual void init ()=0
virtual void pinMode (uint8_t pin, uint8_t output)=0
virtual void pinMode (uint8_t pin, uint8_t output, uint8_t alt)
virtual uint8_t read (uint8_t pin)=0
virtual void write (uint8_t pin, uint8_t value)=0
virtual void toggle (uint8_t pin)=0
virtual bool valid_pin (uint8_t pin) const
virtual bool pin_to_servo_channel (uint8_t pin, uint8_t &servo_ch) const
virtual bool get_mode (uint8_t pin, uint32_t &mode)
virtual void set_mode (uint8_t pin, uint32_t mode)
virtual AP_HAL::DigitalSource * channel (uint16_t n)=0
FUNCTOR_TYPEDEF (irq_handler_fn_t, void, uint8_t, bool, uint32_t)
virtual bool attach_interrupt (uint8_t pin, irq_handler_fn_t fn, INTERRUPT_TRIGGER_TYPE mode)
virtual bool attach_interrupt (uint8_t pin, AP_HAL::Proc proc, INTERRUPT_TRIGGER_TYPE mode)
bool detach_interrupt (uint8_t pin)
virtual bool wait_pin (uint8_t pin, INTERRUPT_TRIGGER_TYPE mode, uint32_t timeout_us)
virtual bool usb_connected (void)=0
virtual void timer_tick (void)
virtual bool arming_checks (size_t buflen, char *buffer) const
Detailed Description
Definition at line 47 of file GPIO.h.
Member Enumeration Documentation
INTERRUPT_TRIGGER_TYPE
enum AP_HAL::GPIO::INTERRUPT_TRIGGER_TYPE
Enumerator
INTERRUPT_NONE
INTERRUPT_FALLING
INTERRUPT_RISING
INTERRUPT_BOTH
Definition at line 72 of file GPIO.h.
Constructor & Destructor Documentation
GPIO()
AP_HAL::GPIO::GPIO () inline
Definition at line 49 of file GPIO.h.
Member Function Documentation
arming_checks()
virtual bool AP_HAL::GPIO::arming_checks (size_t buflen, char * buffer) const inline virtual
Reimplemented in ChibiOS::GPIO.
Definition at line 118 of file GPIO.h.
Referenced by AP_Arming::system_checks().
attach_interrupt() [1/2]
virtual bool AP_HAL::GPIO::attach_interrupt (uint8_t pin, AP_HAL::Proc proc, INTERRUPT_TRIGGER_TYPE mode) inline virtual
Reimplemented in ChibiOS::GPIO.
Definition at line 93 of file GPIO.h.
attach_interrupt() [2/2]
virtual bool AP_HAL::GPIO::attach_interrupt (uint8_t pin, irq_handler_fn_t fn, INTERRUPT_TRIGGER_TYPE mode) inline virtual
Reimplemented in ChibiOS::GPIO.
Definition at line 87 of file GPIO.h.
Referenced by AP_GPS_UBLOX::_parse_gps(), detach_interrupt(), AP_HAL::PWMSource::set_pin(), AP_Camera_Backend::setup_feedback_callback(), AP_RPM_Pin::update(), and AP_WheelEncoder_Quadrature::update_pin().
channel()
virtual AP_HAL::DigitalSource * AP_HAL::GPIO::channel (uint16_t n) pure virtual
Implemented in ChibiOS::GPIO, Empty::GPIO, Linux::GPIO_BBB, Linux::GPIO_RPI, HALSITL::GPIO, and Linux::GPIO_Sysfs.
Referenced by AP_InertialSensor_BMI160::_configure_int1_pin(), AP_Baro_BMP085::_init(), AP_InertialSensor_Invensense::_init(), AP_InertialSensor_Invensensev2::_init(), Linux::CameraSensor_Mt9v117::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), AP_InertialSensor_LSM9DS1::_init_sensor(), Linux::RCInput_RPI::init(), Linux::RCOutput_PCA9685::init(), AP_Compass_LSM303D::init(), Linux::SPIDevice::SPIDevice(), test_gpio_input(), and test_gpio_output().
detach_interrupt()
bool AP_HAL::GPIO::detach_interrupt (uint8_t pin) inline
Definition at line 98 of file GPIO.h.
Referenced by AP_HAL::PWMSource::set_pin(), AP_RPM_Pin::update(), AP_WheelEncoder_Quadrature::update_pin(), and AP_HAL::PWMSource::~PWMSource().
FUNCTOR_TYPEDEF()
AP_HAL::GPIO::FUNCTOR_TYPEDEF (irq_handler_fn_t , void , uint8_t , bool , uint32_t)
get_mode()
virtual bool AP_HAL::GPIO::get_mode (uint8_t pin, uint32_t & mode) inline virtual
Definition at line 66 of file GPIO.h.
Referenced by AP_RCProtocol_DSM::start_bind().
init()
virtual void AP_HAL::GPIO::init () pure virtual
Implemented in ChibiOS::GPIO, Empty::GPIO, Linux::GPIO_BBB, Linux::GPIO_RPI, Linux::GPIO_Sysfs, and HALSITL::GPIO.
Referenced by AP_BoardConfig::board_setup(), and HAL_Linux::run().
pin_to_servo_channel()
virtual bool AP_HAL::GPIO::pin_to_servo_channel (uint8_t pin, uint8_t & servo_ch) const inline virtual
Reimplemented in ChibiOS::GPIO.
Definition at line 63 of file GPIO.h.
Referenced by AP_Button::arming_checks(), AP_Relay::arming_checks(), AP_RPM::arming_checks(), and RangeFinder::prearm_healthy().
pinMode() [1/2]
virtual void AP_HAL::GPIO::pinMode (uint8_t pin, uint8_t output) pure virtual
Implemented in ChibiOS::GPIO, Empty::GPIO, Linux::GPIO_BBB, GPIO_Navigator, Linux::GPIO_RPI, HALSITL::GPIO, and Linux::GPIO_Sysfs.
Referenced by AP_AdvancedFailsafe::check(), AP_RangeFinder_PWM::check_stop_pin(), AP_Relay::get_pin(), AP_AdvancedFailsafe::heartbeat(), Linux::HeatPwm::HeatPwm(), AP_InertialSensor_ADIS1647x::init(), Linux::RCInput_PRU::init(), HALSITL::RCOutput::init(), Buzzer::init(), PixRacerLED::init(), Linux::DigitalSource::mode(), AP_IOMCU_FW::rcout_config_update(), AP_LeakDetector_Digital::read(), AP_Relay::set_pin(), AP_HAL::PWMSource::set_pin(), AP_Camera_Backend::setup_feedback_callback(), AP_Button::setup_pins(), test_gpio_input(), test_gpio_output(), AP_SBusOut::update(), AP_RangeFinder_HC_SR04::update(), AP_RCProtocol_DSM::update(), AP_RPM_Pin::update(), and AP_WheelEncoder_Quadrature::update_pin().
pinMode() [2/2]
virtual void AP_HAL::GPIO::pinMode (uint8_t pin, uint8_t output, uint8_t alt) inline virtual
Reimplemented in GPIO_Navigator, and Linux::GPIO_RPI.
Definition at line 54 of file GPIO.h.
read()
virtual uint8_t AP_HAL::GPIO::read (uint8_t pin) pure virtual
Implemented in ChibiOS::GPIO, Empty::GPIO, Linux::GPIO_BBB, GPIO_Navigator, Linux::GPIO_RPI, HALSITL::GPIO, and Linux::GPIO_Sysfs.
Referenced by AP_Camera_Backend::feedback_pin_timer(), AP_Button::get_mask(), AP_Relay::get_pin(), Linux::DigitalSource::read(), HALSITL::DigitalSource::read(), AP_LeakDetector_Digital::read(), test_gpio_input(), HALSITL::DigitalSource::toggle(), and AP_WheelEncoder_Quadrature::update_pin().
set_mode()
virtual void AP_HAL::GPIO::set_mode (uint8_t pin, uint32_t mode) inline virtual
Definition at line 67 of file GPIO.h.
Referenced by AP_RCProtocol_DSM::update().
timer_tick()
virtual void AP_HAL::GPIO::timer_tick (void) inline virtual
Reimplemented in ChibiOS::GPIO.
Definition at line 115 of file GPIO.h.
Referenced by ChibiOS::Scheduler::_monitor_thread().
toggle()
virtual void AP_HAL::GPIO::toggle (uint8_t pin) pure virtual
Implemented in ChibiOS::GPIO, Empty::GPIO, Linux::GPIO_BBB, Linux::GPIO_RPI, HALSITL::GPIO, and Linux::GPIO_Sysfs.
usb_connected()
virtual bool AP_HAL::GPIO::usb_connected (void) pure virtual
Implemented in Linux::GPIO_Sysfs, ChibiOS::GPIO, Empty::GPIO, Linux::GPIO_BBB, Linux::GPIO_RPI, and HALSITL::GPIO.
Referenced by RGBLed::get_brightness(), GCS_MAVLINK::have_flow_control(), AP_Logger::log_while_disarmed(), and GCS_MAVLINK::telemetry_delayed().
valid_pin()
virtual bool AP_HAL::GPIO::valid_pin (uint8_t pin) const inline virtual
Reimplemented in ChibiOS::GPIO, and HALSITL::GPIO.
Definition at line 59 of file GPIO.h.
Referenced by AP_Button::arming_checks(), AP_Relay::arming_checks(), AP_RPM::arming_checks(), and RangeFinder::prearm_healthy().
wait_pin()
virtual bool AP_HAL::GPIO::wait_pin (uint8_t pin, INTERRUPT_TRIGGER_TYPE mode, uint32_t timeout_us) inline virtual
Reimplemented in ChibiOS::GPIO.
Definition at line 109 of file GPIO.h.
Referenced by AP_InertialSensor_ADIS1647x::loop().
write()
virtual void AP_HAL::GPIO::write (uint8_t pin, uint8_t value) pure virtual
Implemented in ChibiOS::GPIO, Empty::GPIO, Linux::GPIO_BBB, GPIO_Navigator, Linux::GPIO_RPI, HALSITL::GPIO, and Linux::GPIO_Sysfs.
Referenced by AP_BoardConfig::board_setup(), AP_AdvancedFailsafe::check(), AP_IOMCU_FW::GPIO_write(), AP_AdvancedFailsafe::heartbeat(), Linux::HeatPwm::HeatPwm(), PixRacerLED::hw_set_rgb(), Linux::RCInput_PRU::init(), PixRacerLED::init(), Buzzer::on(), ChibiOS::UARTDriver::set_options(), AP_Relay::set_pin(), AP_Camera_Backend::setup_feedback_callback(), AP_Button::setup_pins(), test_gpio_output(), HALSITL::DigitalSource::toggle(), AP_SBusOut::update(), AP_RangeFinder_HC_SR04::update(), AP_RangeFinder_PWM::update(), AP_RCProtocol_DSM::update(), Linux::DigitalSource::write(), and HALSITL::DigitalSource::write().
The documentation for this class was generated from the following file:
libraries/AP_HAL/GPIO.h