APM:Libraries: Radio_CC2500 Class Reference
Radio_CC2500 Class Reference
#include <driver_cc2500.h>
Public Member Functions
Radio_CC2500 (AP_HAL::OwnPtr< AP_HAL::SPIDevice > _dev)
void ReadFifo (uint8_t *dpbuffer, uint8_t len)
void WriteFifo (const uint8_t *dpbuffer, uint8_t len)
void ReadRegisterMulti (uint8_t address, uint8_t *data, uint8_t length)
void WriteRegisterMulti (uint8_t address, const uint8_t *data, uint8_t length)
uint8_t ReadReg (uint8_t reg)
uint8_t Strobe (uint8_t address)
void WriteReg (uint8_t address, uint8_t data)
void WriteRegCheck (uint8_t address, uint8_t data)
void SetPower (uint8_t power)
bool Reset (void)
bool lock_bus (void)
void unlock_bus (void)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev
uint8_t last_power
Detailed Description
Definition at line 140 of file driver_cc2500.h.
Constructor & Destructor Documentation
Radio_CC2500()
Radio_CC2500::Radio_CC2500 (AP_HAL::OwnPtr< AP_HAL::SPIDevice > _dev)
Definition at line 15 of file driver_cc2500.cpp.
Member Function Documentation
lock_bus()
bool Radio_CC2500::lock_bus (void) inline
Definition at line 158 of file driver_cc2500.h.
ReadFifo()
void Radio_CC2500::ReadFifo (uint8_t * dpbuffer, uint8_t len)
Definition at line 19 of file driver_cc2500.cpp.
ReadReg()
uint8_t Radio_CC2500::ReadReg (uint8_t reg)
Definition at line 42 of file driver_cc2500.cpp.
Referenced by Reset(), and WriteRegCheck().
ReadRegisterMulti()
void Radio_CC2500::ReadRegisterMulti (uint8_t address, uint8_t * data, uint8_t length)
Definition at line 29 of file driver_cc2500.cpp.
Reset()
bool Radio_CC2500::Reset (void)
Definition at line 82 of file driver_cc2500.cpp.
SetPower()
void Radio_CC2500::SetPower (uint8_t power)
Definition at line 61 of file driver_cc2500.cpp.
Strobe()
uint8_t Radio_CC2500::Strobe (uint8_t address)
Definition at line 49 of file driver_cc2500.cpp.
Referenced by Reset().
unlock_bus()
void Radio_CC2500::unlock_bus (void) inline
Definition at line 166 of file driver_cc2500.h.
WriteFifo()
void Radio_CC2500::WriteFifo (const uint8_t * dpbuffer, uint8_t len)
Definition at line 24 of file driver_cc2500.cpp.
WriteReg()
void Radio_CC2500::WriteReg (uint8_t address, uint8_t data)
Definition at line 56 of file driver_cc2500.cpp.
Referenced by SetPower().
WriteRegCheck()
void Radio_CC2500::WriteRegCheck (uint8_t address, uint8_t data)
Definition at line 95 of file driver_cc2500.cpp.
WriteRegisterMulti()
void Radio_CC2500::WriteRegisterMulti (uint8_t address, const uint8_t * data, uint8_t length)
Definition at line 34 of file driver_cc2500.cpp.
Referenced by WriteFifo().
Member Data Documentation
dev
AP_HAL::OwnPtr<AP_HAL::SPIDevice> Radio_CC2500::dev private
Definition at line 172 of file driver_cc2500.h.
Referenced by lock_bus(), ReadFifo(), ReadReg(), ReadRegisterMulti(), Strobe(), unlock_bus(), WriteReg(), WriteRegCheck(), and WriteRegisterMulti().
last_power
uint8_t Radio_CC2500::last_power private
Definition at line 173 of file driver_cc2500.h.
Referenced by SetPower().
The documentation for this class was generated from the following files:
libraries/AP_Radio/driver_cc2500.h
libraries/AP_Radio/driver_cc2500.cpp