APM:Libraries: ModeFilter< T, FILTER_SIZE > Class Template Reference
ModeFilter< T, FILTER_SIZE > Class Template Reference
#include <ModeFilter.h>
Public Member Functions
ModeFilter (uint8_t return_element)
virtual T apply (T sample) override
virtual T get () const
Public Member Functions inherited from FilterWithBuffer< T, FILTER_SIZE >
FilterWithBuffer ()
virtual void reset () override
uint8_t get_filter_size () const
T get_sample (uint8_t i) const
Private Member Functions
void isort (T sample, bool drop_high_sample)
Private Attributes
uint8_t _return_element
T _output
bool drop_high_sample
Additional Inherited Members
Protected Attributes inherited from FilterWithBuffer< T, FILTER_SIZE >
T samples [FILTER_SIZE]
uint8_t sample_index
Detailed Description
template<class T, uint8_t FILTER_SIZE>
class ModeFilter< T, FILTER_SIZE >
Definition at line 27 of file ModeFilter.h.
Constructor & Destructor Documentation
ModeFilter()
template<class T , uint8_t FILTER_SIZE> ModeFilter< T, FILTER_SIZE >::ModeFilter (uint8_t return_element)
Definition at line 20 of file ModeFilter.cpp.
Member Function Documentation
apply()
template<class T , uint8_t FILTER_SIZE> T ModeFilter< T, FILTER_SIZE >::apply (T sample) override virtual
Reimplemented from FilterWithBuffer< T, FILTER_SIZE >.
Definition at line 34 of file ModeFilter.cpp.
Referenced by AP_AutoTune::update(), and AP_RPM_Pin::update().
get()
template<class T , uint8_t FILTER_SIZE> virtual T ModeFilter< T, FILTER_SIZE >::get () const inline virtual
Definition at line 36 of file ModeFilter.h.
Referenced by AP_RPM_Pin::update().
isort()
template<class T , uint8_t FILTER_SIZE> void ModeFilter< T, FILTER_SIZE >::isort (T sample, bool drop_high_sample) private
Definition at line 57 of file ModeFilter.cpp.
Member Data Documentation
_output
template<class T , uint8_t FILTER_SIZE> T ModeFilter< T, FILTER_SIZE >::_output private
Definition at line 43 of file ModeFilter.h.
Referenced by ModeFilter< T, FILTER_SIZE >::get().
_return_element
template<class T , uint8_t FILTER_SIZE> uint8_t ModeFilter< T, FILTER_SIZE >::_return_element private
Definition at line 42 of file ModeFilter.h.
Referenced by ModeFilter< T, FILTER_SIZE >::ModeFilter().
drop_high_sample
template<class T , uint8_t FILTER_SIZE> bool ModeFilter< T, FILTER_SIZE >::drop_high_sample private
Definition at line 45 of file ModeFilter.h.
The documentation for this class was generated from the following files:
libraries/Filter/ModeFilter.h
libraries/Filter/ModeFilter.cpp