APM:Libraries: AP_FlashStorage Class Reference
AP_FlashStorage Class Reference
#include <AP_FlashStorage.h>
Classes
struct block_header
struct sector_header
Public Member Functions
FUNCTOR_TYPEDEF (FlashWrite, bool, uint8_t, uint32_t, const uint8_t *, uint16_t)
FUNCTOR_TYPEDEF (FlashRead, bool, uint8_t, uint32_t, uint8_t *, uint16_t)
FUNCTOR_TYPEDEF (FlashErase, bool, uint8_t)
FUNCTOR_TYPEDEF (FlashEraseOK, bool)
AP_FlashStorage (uint8_t *mem_buffer, uint32_t flash_sector_size, FlashWrite flash_write, FlashRead flash_read, FlashErase flash_erase, FlashEraseOK flash_erase_ok)
bool init (void)
bool erase (void) WARN_IF_UNUSED
bool re_initialise (void) WARN_IF_UNUSED
bool switch_full_sector (void) WARN_IF_UNUSED
bool write (uint16_t offset, uint16_t length) WARN_IF_UNUSED
Static Public Attributes
static const uint16_t storage_size = HAL_STORAGE_SIZE
Private Types
enum SectorState { SECTOR_STATE_AVAILABLE = 1 , SECTOR_STATE_IN_USE = 2 , SECTOR_STATE_FULL = 3 , SECTOR_STATE_INVALID = 4 }
enum BlockState { BLOCK_STATE_AVAILABLE = 0x3 , BLOCK_STATE_WRITING = 0x1 , BLOCK_STATE_VALID = 0x0 }
Private Member Functions
bool load_sector (uint8_t sector) WARN_IF_UNUSED
bool erase_sector (uint8_t sector, bool mark_available) WARN_IF_UNUSED
bool erase_all () WARN_IF_UNUSED
bool write_all () WARN_IF_UNUSED
bool all_zero (uint16_t ofs, uint16_t size) WARN_IF_UNUSED
bool switch_sectors (void) WARN_IF_UNUSED
bool protected_switch_full_sector (void) WARN_IF_UNUSED
Private Attributes
uint8_t * mem_buffer
const uint32_t flash_sector_size
FlashWrite flash_write
FlashRead flash_read
FlashErase flash_erase
FlashEraseOK flash_erase_ok
uint8_t current_sector
uint32_t write_offset
uint32_t reserved_space
bool write_error
bool in_switch_full_sector
Static Private Attributes
static const uint8_t block_size = 8
static const uint8_t max_write = 64
static const uint16_t num_blocks = (HAL_STORAGE_SIZE+(block_size-1)) / block_size
static const uint32_t signature = 0x51685B
static const uint32_t reserve_size = (storage_size / max_write) * (sizeof(block_header) + max_write) + max_write
Detailed Description
Definition at line 78 of file AP_FlashStorage.h.
Member Enumeration Documentation
BlockState
enum AP_FlashStorage::BlockState private
Enumerator
BLOCK_STATE_AVAILABLE
BLOCK_STATE_WRITING
BLOCK_STATE_VALID
Definition at line 204 of file AP_FlashStorage.h.
SectorState
enum AP_FlashStorage::SectorState private
Enumerator
SECTOR_STATE_AVAILABLE
SECTOR_STATE_IN_USE
SECTOR_STATE_FULL
SECTOR_STATE_INVALID
Definition at line 163 of file AP_FlashStorage.h.
Constructor & Destructor Documentation
AP_FlashStorage()
AP_FlashStorage::AP_FlashStorage (uint8_t * mem_buffer, uint32_t flash_sector_size, FlashWrite flash_write, FlashRead flash_read, FlashErase flash_erase, FlashEraseOK flash_erase_ok)
Definition at line 33 of file AP_FlashStorage.cpp.
Member Function Documentation
all_zero()
bool AP_FlashStorage::all_zero (uint16_t ofs, uint16_t size) private
Definition at line 385 of file AP_FlashStorage.cpp.
Referenced by write_all().
erase()
bool AP_FlashStorage::erase (void) inline
Definition at line 119 of file AP_FlashStorage.h.
erase_all()
bool AP_FlashStorage::erase_all (void) private
Definition at line 344 of file AP_FlashStorage.cpp.
Referenced by erase(), init(), and re_initialise().
erase_sector()
bool AP_FlashStorage::erase_sector (uint8_t sector, bool mark_available) private
Definition at line 328 of file AP_FlashStorage.cpp.
Referenced by erase_all(), init(), and protected_switch_full_sector().
FUNCTOR_TYPEDEF() [1/4]
AP_FlashStorage::FUNCTOR_TYPEDEF (FlashErase , bool , uint8_t)
FUNCTOR_TYPEDEF() [2/4]
AP_FlashStorage::FUNCTOR_TYPEDEF (FlashEraseOK , bool)
FUNCTOR_TYPEDEF() [3/4]
AP_FlashStorage::FUNCTOR_TYPEDEF (FlashRead , bool , uint8_t , uint32_t , uint8_t * , uint16_t)
FUNCTOR_TYPEDEF() [4/4]
AP_FlashStorage::FUNCTOR_TYPEDEF (FlashWrite , bool , uint8_t , uint32_t , const uint8_t * , uint16_t)
init()
bool AP_FlashStorage::init (void)
Definition at line 47 of file AP_FlashStorage.cpp.
Referenced by ESP32::Storage::_flash_load(), HALSITL::Storage::_flash_load(), and FlashTest::loop().
load_sector()
bool AP_FlashStorage::load_sector (uint8_t sector) private
Definition at line 264 of file AP_FlashStorage.cpp.
Referenced by init().
protected_switch_full_sector()
bool AP_FlashStorage::protected_switch_full_sector (void) private
Definition at line 159 of file AP_FlashStorage.cpp.
Referenced by switch_full_sector().
re_initialise()
bool AP_FlashStorage::re_initialise (void)
Definition at line 452 of file AP_FlashStorage.cpp.
Referenced by ESP32::Storage::_flash_write_data(), and HALSITL::Storage::_flash_write_data().
switch_full_sector()
bool AP_FlashStorage::switch_full_sector (void)
Definition at line 140 of file AP_FlashStorage.cpp.
Referenced by write().
switch_sectors()
bool AP_FlashStorage::switch_sectors (void) private
Definition at line 396 of file AP_FlashStorage.cpp.
Referenced by protected_switch_full_sector(), and write().
write()
bool AP_FlashStorage::write (uint16_t offset, uint16_t length)
Definition at line 177 of file AP_FlashStorage.cpp.
Referenced by ESP32::Storage::_flash_write(), HALSITL::Storage::_flash_write(), FlashTest::write(), and write_all().
write_all()
bool AP_FlashStorage::write_all () private
Definition at line 367 of file AP_FlashStorage.cpp.
Referenced by init(), protected_switch_full_sector(), and re_initialise().
Member Data Documentation
block_size
const uint8_t AP_FlashStorage::block_size = 8 static private
Definition at line 89 of file AP_FlashStorage.h.
Referenced by load_sector(), and write().
current_sector
uint8_t AP_FlashStorage::current_sector private
Definition at line 144 of file AP_FlashStorage.h.
Referenced by erase_all(), init(), protected_switch_full_sector(), switch_sectors(), write(), and write_all().
flash_erase
FlashErase AP_FlashStorage::flash_erase private
Definition at line 141 of file AP_FlashStorage.h.
Referenced by erase_sector().
flash_erase_ok
FlashEraseOK AP_FlashStorage::flash_erase_ok private
Definition at line 142 of file AP_FlashStorage.h.
Referenced by re_initialise(), and write().
flash_read
FlashRead AP_FlashStorage::flash_read private
Definition at line 140 of file AP_FlashStorage.h.
Referenced by init(), load_sector(), and switch_sectors().
flash_sector_size
const uint32_t AP_FlashStorage::flash_sector_size private
Definition at line 138 of file AP_FlashStorage.h.
Referenced by load_sector(), and write().
flash_write
FlashWrite AP_FlashStorage::flash_write private
Definition at line 139 of file AP_FlashStorage.h.
Referenced by erase_all(), erase_sector(), switch_sectors(), and write().
in_switch_full_sector
bool AP_FlashStorage::in_switch_full_sector private
Definition at line 243 of file AP_FlashStorage.h.
Referenced by switch_full_sector().
max_write
const uint8_t AP_FlashStorage::max_write = 64 static private
Definition at line 90 of file AP_FlashStorage.h.
Referenced by write(), and write_all().
mem_buffer
uint8_t* AP_FlashStorage::mem_buffer private
Definition at line 137 of file AP_FlashStorage.h.
Referenced by all_zero(), init(), load_sector(), and write().
num_blocks
const uint16_t AP_FlashStorage::num_blocks = (HAL_STORAGE_SIZE+(block_size-1)) / block_size static private
Definition at line 92 of file AP_FlashStorage.h.
reserve_size
const uint32_t AP_FlashStorage::reserve_size = (storage_size / max_write) * (sizeof(block_header) + max_write) + max_write static private
Definition at line 218 of file AP_FlashStorage.h.
Referenced by switch_sectors().
reserved_space
uint32_t AP_FlashStorage::reserved_space private
Definition at line 146 of file AP_FlashStorage.h.
Referenced by init(), protected_switch_full_sector(), switch_sectors(), write(), and write_all().
signature
const uint32_t AP_FlashStorage::signature = 0x51685B static private
Definition at line 151 of file AP_FlashStorage.h.
Referenced by AP_FlashStorage::sector_header::get_state(), AP_FlashStorage::sector_header::set_state(), and AP_FlashStorage::sector_header::signature_ok().
storage_size
const uint16_t AP_FlashStorage::storage_size = HAL_STORAGE_SIZE static
Definition at line 134 of file AP_FlashStorage.h.
Referenced by init(), load_sector(), and write_all().
write_error
bool AP_FlashStorage::write_error private
Definition at line 147 of file AP_FlashStorage.h.
Referenced by erase_all(), init(), protected_switch_full_sector(), switch_sectors(), and write().
write_offset
uint32_t AP_FlashStorage::write_offset private
Definition at line 145 of file AP_FlashStorage.h.
Referenced by erase_all(), load_sector(), switch_sectors(), write(), and write_all().
The documentation for this class was generated from the following files:
libraries/AP_FlashStorage/AP_FlashStorage.h
libraries/AP_FlashStorage/AP_FlashStorage.cpp