APM:Libraries: AP_RangeFinder_Benewake_TFMiniPlus Class Reference
AP_RangeFinder_Benewake_TFMiniPlus Class Reference
#include <AP_RangeFinder_Benewake_TFMiniPlus.h>
Public Member Functions
void update (void) override
Public Member Functions inherited from AP_RangeFinder_Backend
AP_RangeFinder_Backend (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params)
virtual ~AP_RangeFinder_Backend (void)
virtual void init_serial (uint8_t serial_instance)
virtual void handle_msg (const mavlink_message_t &msg)
enum Rotation orientation () const
float distance () const
uint16_t distance_cm () const
int8_t signal_quality_pct () const WARN_IF_UNUSED
uint16_t voltage_mv () const
virtual int16_t max_distance_cm () const
virtual int16_t min_distance_cm () const
int16_t ground_clearance_cm () const
MAV_DISTANCE_SENSOR get_mav_distance_sensor_type () const
RangeFinder::Status status () const
RangeFinder::Type type () const
bool has_data () const
uint8_t range_valid_count () const
const Vector3f & get_pos_offset () const
uint32_t last_reading_ms () const
virtual bool get_temp (float &temp) const
RangeFinder::Type allocated_type () const
Static Public Member Functions
static AP_RangeFinder_Backend * detect (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
Protected Member Functions
virtual MAV_DISTANCE_SENSOR _get_mav_distance_sensor_type () const override
Protected Member Functions inherited from AP_RangeFinder_Backend
void update_status (RangeFinder::RangeFinder_State &state_arg) const
void update_status ()
void set_status (RangeFinder::Status status)
Private Member Functions
AP_RangeFinder_Benewake_TFMiniPlus (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
bool init ()
void timer ()
void process_raw_measure (le16_t distance_raw, le16_t strength_raw, uint16_t &output_distance_cm)
bool check_checksum (uint8_t *arr, int pkt_len)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
struct {
uint32_t sum
uint32_t count
} accum
Additional Inherited Members
Static Protected Member Functions inherited from AP_RangeFinder_Backend
static void set_status (RangeFinder::RangeFinder_State &state_arg, RangeFinder::Status status)
Protected Attributes inherited from AP_RangeFinder_Backend
RangeFinder::RangeFinder_State & state
AP_RangeFinder_Params & params
HAL_Semaphore _sem
RangeFinder::Type _backend_type
Detailed Description
Definition at line 31 of file AP_RangeFinder_Benewake_TFMiniPlus.h.
Constructor & Destructor Documentation
AP_RangeFinder_Benewake_TFMiniPlus()
AP_RangeFinder_Benewake_TFMiniPlus::AP_RangeFinder_Benewake_TFMiniPlus (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev) private
Definition at line 41 of file AP_RangeFinder_Benewake_TFMiniPlus.cpp.
Referenced by detect().
Member Function Documentation
_get_mav_distance_sensor_type()
virtual MAV_DISTANCE_SENSOR AP_RangeFinder_Benewake_TFMiniPlus::_get_mav_distance_sensor_type () const inline override protected virtual
Implements AP_RangeFinder_Backend.
Definition at line 45 of file AP_RangeFinder_Benewake_TFMiniPlus.h.
check_checksum()
bool AP_RangeFinder_Benewake_TFMiniPlus::check_checksum (uint8_t * arr, int pkt_len) private
Definition at line 178 of file AP_RangeFinder_Benewake_TFMiniPlus.cpp.
Referenced by init(), and timer().
detect()
AP_RangeFinder_Backend * AP_RangeFinder_Benewake_TFMiniPlus::detect (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev) static
Definition at line 50 of file AP_RangeFinder_Benewake_TFMiniPlus.cpp.
Referenced by RangeFinder::detect_instance().
init()
bool AP_RangeFinder_Benewake_TFMiniPlus::init () private
Definition at line 69 of file AP_RangeFinder_Benewake_TFMiniPlus.cpp.
Referenced by detect().
process_raw_measure()
void AP_RangeFinder_Benewake_TFMiniPlus::process_raw_measure (le16_t distance_raw, le16_t strength_raw, uint16_t & output_distance_cm) private
Definition at line 156 of file AP_RangeFinder_Benewake_TFMiniPlus.cpp.
Referenced by timer().
timer()
void AP_RangeFinder_Benewake_TFMiniPlus::timer () private
Definition at line 191 of file AP_RangeFinder_Benewake_TFMiniPlus.cpp.
Referenced by init().
update()
void AP_RangeFinder_Benewake_TFMiniPlus::update (void) override virtual
Implements AP_RangeFinder_Backend.
Definition at line 141 of file AP_RangeFinder_Benewake_TFMiniPlus.cpp.
Member Data Documentation
_dev
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_RangeFinder_Benewake_TFMiniPlus::_dev private
Definition at line 62 of file AP_RangeFinder_Benewake_TFMiniPlus.h.
Referenced by init(), and timer().
[struct]
struct { ... } AP_RangeFinder_Benewake_TFMiniPlus::accum
Referenced by timer(), and update().
count
uint32_t AP_RangeFinder_Benewake_TFMiniPlus::count
Definition at line 66 of file AP_RangeFinder_Benewake_TFMiniPlus.h.
sum
uint32_t AP_RangeFinder_Benewake_TFMiniPlus::sum
Definition at line 65 of file AP_RangeFinder_Benewake_TFMiniPlus.h.
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder_Benewake_TFMiniPlus.h
libraries/AP_RangeFinder/AP_RangeFinder_Benewake_TFMiniPlus.cpp