APM:Libraries: Frame_helper Class Reference
Frame_helper Class Reference
Public Member Functions
void public_load_frame_params (const char *model_json)
float get_capacity ()
float get_max_volt ()
float get_resistance ()
void public_load_frame_params (const char *model_json)
float public_get_air_density (float alt_amsl)
float get_pwm_min ()
float get_pwm_max ()
float get_spin_min ()
float get_spin_max ()
float get_prop_expo ()
float get_slew_max ()
float get_max_voltage ()
float get_mass ()
float get_ref_current ()
float get_ref_voltage ()
float get_ref_alt ()
float get_hover_thr_out ()
float get_disk_area ()
float get_mdrag_coef ()
float get_num_motors ()
Public Member Functions inherited from SITL::Frame
Frame (const char *_name, uint8_t _num_motors, Motor *_motors)
void current_and_voltage (float &voltage, float &current)
float get_mass (void) const
void set_mass (float new_mass)
Additional Inherited Members
Public Attributes inherited from SITL::Frame
const char * name
uint8_t num_motors
Motor * motors
float terminal_velocity
float terminal_rotation_rate
uint8_t motor_offset
Protected Member Functions inherited from SITL::Frame
void load_frame_params (const char *model_json)
float get_air_density (float alt_amsl) const
Protected Attributes inherited from SITL::Frame
struct Model model
Detailed Description
Definition at line 20 of file EvaluateBatteryModel.cpp.
Member Function Documentation
get_capacity()
float Frame_helper::get_capacity () inline
Definition at line 28 of file EvaluateBatteryModel.cpp.
Referenced by setup().
get_disk_area()
float Frame_helper::get_disk_area () inline
Definition at line 45 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_hover_thr_out()
float Frame_helper::get_hover_thr_out () inline
Definition at line 44 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_mass()
float Frame_helper::get_mass (void) inline
Definition at line 40 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_max_volt()
float Frame_helper::get_max_volt () inline
Definition at line 29 of file EvaluateBatteryModel.cpp.
Referenced by setup().
get_max_voltage()
float Frame_helper::get_max_voltage () inline
Definition at line 39 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_mdrag_coef()
float Frame_helper::get_mdrag_coef () inline
Definition at line 46 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_num_motors()
float Frame_helper::get_num_motors () inline
Definition at line 47 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_prop_expo()
float Frame_helper::get_prop_expo () inline
Definition at line 37 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_pwm_max()
float Frame_helper::get_pwm_max () inline
Definition at line 34 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_pwm_min()
float Frame_helper::get_pwm_min () inline
Definition at line 33 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_ref_alt()
float Frame_helper::get_ref_alt () inline
Definition at line 43 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_ref_current()
float Frame_helper::get_ref_current () inline
Definition at line 41 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_ref_voltage()
float Frame_helper::get_ref_voltage () inline
Definition at line 42 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_resistance()
float Frame_helper::get_resistance () inline
Definition at line 30 of file EvaluateBatteryModel.cpp.
Referenced by setup().
get_slew_max()
float Frame_helper::get_slew_max () inline
Definition at line 38 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_spin_max()
float Frame_helper::get_spin_max () inline
Definition at line 36 of file EvaluateMotorModel.cpp.
Referenced by setup().
get_spin_min()
float Frame_helper::get_spin_min () inline
Definition at line 35 of file EvaluateMotorModel.cpp.
Referenced by setup().
public_get_air_density()
float Frame_helper::public_get_air_density (float alt_amsl) inline
Definition at line 29 of file EvaluateMotorModel.cpp.
Referenced by setup().
public_load_frame_params() [1/2]
void Frame_helper::public_load_frame_params (const char * model_json) inline
Definition at line 24 of file EvaluateBatteryModel.cpp.
Referenced by setup().
public_load_frame_params() [2/2]
void Frame_helper::public_load_frame_params (const char * model_json) inline
Definition at line 25 of file EvaluateMotorModel.cpp.
The documentation for this class was generated from the following files:
libraries/SITL/examples/EvaluateBatteryModel/EvaluateBatteryModel.cpp
libraries/SITL/examples/EvaluateMotorModel/EvaluateMotorModel.cpp