APM:Libraries: AC_AttitudeControl_Multi Class Reference
AC_AttitudeControl_Multi Class Reference
#include <AC_AttitudeControl_Multi.h>
Public Member Functions
AC_AttitudeControl_Multi (AP_AHRS_View &ahrs, const AP_MultiCopter &aparm, AP_MotorsMulticopter &motors)
virtual ~AC_AttitudeControl_Multi ()
AC_PID & get_rate_roll_pid () override
AC_PID & get_rate_pitch_pid () override
AC_PID & get_rate_yaw_pid () override
const AC_PID & get_rate_roll_pid () const override
const AC_PID & get_rate_pitch_pid () const override
const AC_PID & get_rate_yaw_pid () const override
void update_althold_lean_angle_max (float throttle_in) override
void set_throttle_out (float throttle_in, bool apply_angle_boost, float filt_cutoff) override
float get_throttle_boosted (float throttle_in)
void set_throttle_mix_min () override
void set_throttle_mix_man () override
void set_throttle_mix_max (float ratio) override
void set_throttle_mix_value (float value) override
float get_throttle_mix (void) const override
bool is_throttle_mix_min () const override
void rate_controller_run () override
void parameter_sanity_check () override
void set_notch_sample_rate (float sample_rate) override
Public Member Functions inherited from AC_AttitudeControl
AC_AttitudeControl (AP_AHRS_View &ahrs, const AP_MultiCopter &aparm, AP_Motors &motors)
virtual ~AC_AttitudeControl ()
void set_dt (float dt)
float get_dt () const
AC_P & get_angle_roll_p ()
AC_P & get_angle_pitch_p ()
AC_P & get_angle_yaw_p ()
float get_accel_roll_max_cdss () const
float get_accel_roll_max_radss () const
void set_accel_roll_max_cdss (float accel_roll_max)
void save_accel_roll_max_cdss (float accel_roll_max)
float get_accel_pitch_max_cdss () const
float get_accel_pitch_max_radss () const
void set_accel_pitch_max_cdss (float accel_pitch_max)
void save_accel_pitch_max_cdss (float accel_pitch_max)
float get_accel_yaw_max_cdss () const
float get_accel_yaw_max_radss () const
void set_accel_yaw_max_cdss (float accel_yaw_max)
void save_accel_yaw_max_cdss (float accel_yaw_max)
float get_ang_vel_roll_max_rads () const
float get_ang_vel_pitch_max_rads () const
float get_ang_vel_yaw_max_rads () const
float get_slew_yaw_max_degs () const
float get_input_tc () const
void set_input_tc (float input_tc)
void relax_attitude_controllers ()
virtual void relax_attitude_controllers (bool exclude_pitch)
void reset_rate_controller_I_terms ()
void reset_rate_controller_I_terms_smoothly ()
void reset_target_and_rate (bool reset_rate=true)
void reset_yaw_target_and_rate (bool reset_rate=true)
void inertial_frame_reset ()
virtual void input_quaternion (Quaternion &attitude_desired_quat, Vector3f ang_vel_target)
virtual void input_euler_angle_roll_pitch_euler_rate_yaw (float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_rate_cds)
virtual void input_euler_angle_roll_pitch_yaw (float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_angle_cd, bool slew_yaw)
virtual void input_euler_rate_yaw_euler_angle_pitch_bf_roll (bool plane_controls, float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_rate_cds)
virtual void input_euler_rate_roll_pitch_yaw (float euler_roll_rate_cds, float euler_pitch_rate_cds, float euler_yaw_rate_cds)
virtual void input_rate_bf_roll_pitch_yaw (float roll_rate_bf_cds, float pitch_rate_bf_cds, float yaw_rate_bf_cds)
virtual void input_rate_bf_roll_pitch_yaw_2 (float roll_rate_bf_cds, float pitch_rate_bf_cds, float yaw_rate_bf_cds)
virtual void input_rate_bf_roll_pitch_yaw_3 (float roll_rate_bf_cds, float pitch_rate_bf_cds, float yaw_rate_bf_cds)
virtual void input_angle_step_bf_roll_pitch_yaw (float roll_angle_step_bf_cd, float pitch_angle_step_bf_cd, float yaw_angle_step_bf_cd)
virtual void input_thrust_vector_rate_heading (const Vector3f &thrust_vector, float heading_rate_cds, bool slew_yaw=true)
virtual void input_thrust_vector_heading (const Vector3f &thrust_vector, float heading_angle_cd, float heading_rate_cds)
void input_thrust_vector_heading (const Vector3f &thrust_vector, float heading_cd)
Quaternion attitude_from_thrust_vector (Vector3f thrust_vector, float heading_angle) const
void euler_rate_to_ang_vel (const Vector3f &euler_rad, const Vector3f &euler_rate_rads, Vector3f &ang_vel_rads)
bool ang_vel_to_euler_rate (const Vector3f &euler_rad, const Vector3f &ang_vel_rads, Vector3f &euler_rate_rads)
void use_sqrt_controller (bool use_sqrt_cont)
Vector3f get_att_target_euler_cd () const
const Vector3f & get_att_target_euler_rad () const
Quaternion get_attitude_target_quat () const
const Vector3f & get_attitude_target_ang_vel () const
float get_att_error_angle_deg () const
void rate_bf_roll_target (float rate_cds)
void rate_bf_pitch_target (float rate_cds)
void rate_bf_yaw_target (float rate_cds)
void rate_bf_roll_sysid (float rate)
void rate_bf_pitch_sysid (float rate)
void rate_bf_yaw_sysid (float rate)
void actuator_roll_sysid (float command)
void actuator_pitch_sysid (float command)
void actuator_yaw_sysid (float command)
float max_rate_step_bf_roll ()
float max_rate_step_bf_pitch ()
float max_rate_step_bf_yaw ()
float max_angle_step_bf_roll ()
float max_angle_step_bf_pitch ()
float max_angle_step_bf_yaw ()
Vector3f rate_bf_targets () const
const Vector3f & get_rate_ef_targets () const
void bf_feedforward (bool enable_or_disable)
void bf_feedforward_save (bool enable_or_disable)
bool get_bf_feedforward ()
void accel_limiting (bool enable_or_disable)
float get_throttle_in () const
float angle_boost () const
virtual float get_althold_lean_angle_max_cd () const
float lean_angle_max_cd () const
float lean_angle_deg () const
void input_shaping_rate_predictor (const Vector2f &error_angle, Vector2f &target_ang_vel, float dt) const
void ang_vel_limit (Vector3f &euler_rad, float ang_vel_roll_max, float ang_vel_pitch_max, float ang_vel_yaw_max) const
Vector3f euler_accel_limit (const Vector3f &euler_rad, const Vector3f &euler_accel)
void attitude_controller_run_quat ()
void thrust_heading_rotation_angles (Quaternion &attitude_target, const Quaternion &attitude_body, Vector3f &attitude_error, float &thrust_angle, float &thrust_error_angle) const
void thrust_vector_rotation_angles (const Quaternion &attitude_target, const Quaternion &attitude_body, Quaternion &thrust_vector_correction, Vector3f &attitude_error, float &thrust_angle, float &thrust_error_angle) const
virtual void use_flybar_passthrough (bool passthrough, bool tail_passthrough)
virtual void use_leaky_i (bool leaky_i)
virtual void set_hover_roll_trim_scalar (float scalar)
virtual float get_roll_trim_cd ()
virtual void passthrough_bf_roll_pitch_rate_yaw (float roll_passthrough, float pitch_passthrough, float yaw_rate_bf_cds)
bool pre_arm_checks (const char *param_prefix, char *failure_msg, const uint8_t failure_msg_len)
virtual void set_inverted_flight (bool inverted)
void get_rpy_srate (float &roll_srate, float &pitch_srate, float &yaw_srate)
void set_roll_pitch_rate_tc (float input_tc)
void set_yaw_rate_tc (float input_tc)
void set_angle_P_scale (const Vector3f &angle_P_scale)
void set_angle_P_scale_mult (const Vector3f &angle_P_scale)
const Vector3f & get_last_angle_P_scale (void) const
void set_PD_scale_mult (const Vector3f &pd_scale)
const Vector3f & get_PD_scale_logging (void) const
void control_monitor_log (void) const
float control_monitor_rms_output_roll (void) const
float control_monitor_rms_output_roll_P (void) const
float control_monitor_rms_output_roll_D (void) const
float control_monitor_rms_output_pitch_P (void) const
float control_monitor_rms_output_pitch_D (void) const
float control_monitor_rms_output_pitch (void) const
float control_monitor_rms_output_yaw (void) const
void input_thrust_vector_heading (const Vector3f &thrust_vector, HeadingCommand heading)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Static Public Attributes inherited from AC_AttitudeControl
static const struct AP_Param::GroupInfo var_info []
static constexpr Vector3f VECTORF_111 {1.0f,1.0f,1.0f}
Protected Member Functions
void update_throttle_gain_boost ()
void update_throttle_rpy_mix ()
float get_throttle_avg_max (float throttle_in)
Protected Member Functions inherited from AC_AttitudeControl
Vector3f update_ang_vel_target_from_att_error (const Vector3f &attitude_error_rot_vec_rad)
virtual float get_roll_trim_rad ()
float get_slew_yaw_max_rads () const
void control_monitor_filter_pid (float value, float &rms_P)
void control_monitor_update (void)
Protected Attributes
AP_MotorsMulticopter & _motors_multi
AC_PID _pid_rate_roll
AC_PID _pid_rate_pitch
AC_PID _pid_rate_yaw
AP_Float _thr_mix_man
AP_Float _thr_mix_min
AP_Float _thr_mix_max
AP_Float _throttle_gain_boost
Protected Attributes inherited from AC_AttitudeControl
AP_Float _slew_yaw
AP_Float _ang_vel_roll_max
AP_Float _ang_vel_pitch_max
AP_Float _ang_vel_yaw_max
AP_Float _accel_roll_max
AP_Float _accel_pitch_max
AP_Float _accel_yaw_max
AP_Int8 _rate_bf_ff_enabled
AP_Int8 _angle_boost_enabled
AC_P _p_angle_roll
AC_P _p_angle_pitch
AC_P _p_angle_yaw
AP_Float _angle_limit_tc
AP_Float _input_tc
float _dt
Vector3f _euler_angle_target
Vector3f _euler_rate_target
Quaternion _attitude_target
Vector3f _ang_vel_target
Vector3f _ang_vel_body
Vector3f _sysid_ang_vel_body
Vector3f _actuator_sysid
Quaternion _attitude_ang_error
float _thrust_angle
float _thrust_error_angle
float _throttle_in = 0.0f
float _angle_boost
bool _use_sqrt_controller
float _althold_lean_angle_max = 0.0f
float _throttle_rpy_mix_desired
float _throttle_rpy_mix
float _feedforward_scalar = 1.0f
float _rate_rp_tc
float _rate_y_tc
Vector3f _angle_P_scale {1,1,1}
Vector3f _angle_P_scale_used
Vector3f _pd_scale {1,1,1}
Vector3f _pd_scale_used
const AP_AHRS_View & _ahrs
const AP_MultiCopter & _aparm
AP_Motors & _motors
struct {
float rms_roll_P
float rms_roll_D
float rms_pitch_P
float rms_pitch_D
float rms_yaw
} _control_monitor
Additional Inherited Members
Public Types inherited from AC_AttitudeControl
enum class HeadingMode { Angle_Only , Angle_And_Rate , Rate_Only }
Static Public Member Functions inherited from AC_AttitudeControl
static AC_AttitudeControl * get_singleton (void)
static float input_shaping_angle (float error_angle, float input_tc, float accel_max, float target_ang_vel, float desired_ang_vel, float max_ang_vel, float dt)
static float input_shaping_angle (float error_angle, float input_tc, float accel_max, float target_ang_vel, float dt)
static float input_shaping_ang_vel (float target_ang_vel, float desired_ang_vel, float accel_max, float dt, float input_tc)
Static Protected Attributes inherited from AC_AttitudeControl
static AC_AttitudeControl * _singleton
Detailed Description
Definition at line 42 of file AC_AttitudeControl_Multi.h.
Constructor & Destructor Documentation
AC_AttitudeControl_Multi()
AC_AttitudeControl_Multi::AC_AttitudeControl_Multi (AP_AHRS_View & ahrs, const AP_MultiCopter & aparm, AP_MotorsMulticopter & motors)
Definition at line 323 of file AC_AttitudeControl_Multi.cpp.
~AC_AttitudeControl_Multi()
virtual AC_AttitudeControl_Multi::~AC_AttitudeControl_Multi () inline virtual
Definition at line 47 of file AC_AttitudeControl_Multi.h.
Member Function Documentation
get_rate_pitch_pid() [1/2]
const AC_PID & AC_AttitudeControl_Multi::get_rate_pitch_pid () const inline override virtual
Implements AC_AttitudeControl.
Definition at line 54 of file AC_AttitudeControl_Multi.h.
get_rate_pitch_pid() [2/2]
AC_PID & AC_AttitudeControl_Multi::get_rate_pitch_pid () inline override virtual
Implements AC_AttitudeControl.
Definition at line 51 of file AC_AttitudeControl_Multi.h.
Referenced by rate_controller_run().
get_rate_roll_pid() [1/2]
const AC_PID & AC_AttitudeControl_Multi::get_rate_roll_pid () const inline override virtual
Implements AC_AttitudeControl.
Definition at line 53 of file AC_AttitudeControl_Multi.h.
get_rate_roll_pid() [2/2]
AC_PID & AC_AttitudeControl_Multi::get_rate_roll_pid () inline override virtual
Implements AC_AttitudeControl.
Definition at line 50 of file AC_AttitudeControl_Multi.h.
Referenced by rate_controller_run(), and AC_AttitudeControl_TS::relax_attitude_controllers().
get_rate_yaw_pid() [1/2]
const AC_PID & AC_AttitudeControl_Multi::get_rate_yaw_pid () const inline override virtual
Implements AC_AttitudeControl.
Definition at line 55 of file AC_AttitudeControl_Multi.h.
get_rate_yaw_pid() [2/2]
AC_PID & AC_AttitudeControl_Multi::get_rate_yaw_pid () inline override virtual
Implements AC_AttitudeControl.
Definition at line 52 of file AC_AttitudeControl_Multi.h.
Referenced by rate_controller_run(), and AC_AttitudeControl_TS::relax_attitude_controllers().
get_throttle_avg_max()
float AC_AttitudeControl_Multi::get_throttle_avg_max (float throttle_in) protected
Definition at line 395 of file AC_AttitudeControl_Multi.cpp.
Referenced by set_throttle_out().
get_throttle_boosted()
float AC_AttitudeControl_Multi::get_throttle_boosted (float throttle_in)
Definition at line 374 of file AC_AttitudeControl_Multi.cpp.
Referenced by set_throttle_out().
get_throttle_mix()
float AC_AttitudeControl_Multi::get_throttle_mix (void) const inline override virtual
Reimplemented from AC_AttitudeControl.
Definition at line 73 of file AC_AttitudeControl_Multi.h.
is_throttle_mix_min()
bool AC_AttitudeControl_Multi::is_throttle_mix_min () const inline override virtual
Reimplemented from AC_AttitudeControl.
Definition at line 76 of file AC_AttitudeControl_Multi.h.
parameter_sanity_check()
void AC_AttitudeControl_Multi::parameter_sanity_check () override virtual
Reimplemented from AC_AttitudeControl.
Definition at line 473 of file AC_AttitudeControl_Multi.cpp.
rate_controller_run()
void AC_AttitudeControl_Multi::rate_controller_run () override virtual
Implements AC_AttitudeControl.
Definition at line 442 of file AC_AttitudeControl_Multi.cpp.
set_notch_sample_rate()
void AC_AttitudeControl_Multi::set_notch_sample_rate (float sample_rate) override virtual
Reimplemented from AC_AttitudeControl.
Definition at line 495 of file AC_AttitudeControl_Multi.cpp.
Referenced by AC_AttitudeControl_Multi().
set_throttle_mix_man()
void AC_AttitudeControl_Multi::set_throttle_mix_man () inline override virtual
Reimplemented from AC_AttitudeControl.
Definition at line 70 of file AC_AttitudeControl_Multi.h.
set_throttle_mix_max()
void AC_AttitudeControl_Multi::set_throttle_mix_max (float ratio) override virtual
Reimplemented from AC_AttitudeControl.
Definition at line 366 of file AC_AttitudeControl_Multi.cpp.
set_throttle_mix_min()
void AC_AttitudeControl_Multi::set_throttle_mix_min () inline override virtual
Reimplemented from AC_AttitudeControl.
Definition at line 69 of file AC_AttitudeControl_Multi.h.
set_throttle_mix_value()
void AC_AttitudeControl_Multi::set_throttle_mix_value (float value) inline override virtual
Reimplemented from AC_AttitudeControl.
Definition at line 72 of file AC_AttitudeControl_Multi.h.
set_throttle_out()
void AC_AttitudeControl_Multi::set_throttle_out (float throttle_in, bool apply_angle_boost, float filt_cutoff) override virtual
Implements AC_AttitudeControl.
Definition at line 350 of file AC_AttitudeControl_Multi.cpp.
update_althold_lean_angle_max()
void AC_AttitudeControl_Multi::update_althold_lean_angle_max (float throttle_in) override virtual
Implements AC_AttitudeControl.
Definition at line 335 of file AC_AttitudeControl_Multi.cpp.
Referenced by set_throttle_out().
update_throttle_gain_boost()
void AC_AttitudeControl_Multi::update_throttle_gain_boost () protected
Definition at line 402 of file AC_AttitudeControl_Multi.cpp.
Referenced by rate_controller_run().
update_throttle_rpy_mix()
void AC_AttitudeControl_Multi::update_throttle_rpy_mix () protected
Definition at line 415 of file AC_AttitudeControl_Multi.cpp.
Referenced by rate_controller_run().
Member Data Documentation
_motors_multi
AP_MotorsMulticopter& AC_AttitudeControl_Multi::_motors_multi protected
Definition at line 101 of file AC_AttitudeControl_Multi.h.
Referenced by update_althold_lean_angle_max().
_pid_rate_pitch
AC_PID AC_AttitudeControl_Multi::_pid_rate_pitch protected
Initial value:
{
        AC_PID::Defaults{
            .p         = AC_ATC_MULTI_RATE_RP_P,
            .i         = AC_ATC_MULTI_RATE_RP_I,
            .d         = AC_ATC_MULTI_RATE_RP_D,
            .ff        = 0.0f,
            .imax      = AC_ATC_MULTI_RATE_RP_IMAX,
            .filt_T_hz = AC_ATC_MULTI_RATE_RPY_FILT_HZ,
            .filt_E_hz = 0.0f,
            .filt_D_hz = AC_ATC_MULTI_RATE_RPY_FILT_HZ,
            .srmax     = 0,
            .srtau     = 1.0
        }
    }
Definition at line 116 of file AC_AttitudeControl_Multi.h.
Referenced by get_rate_pitch_pid(), get_rate_pitch_pid(), and set_notch_sample_rate().
_pid_rate_roll
AC_PID AC_AttitudeControl_Multi::_pid_rate_roll protected
Initial value:
{
        AC_PID::Defaults{
            .p         = AC_ATC_MULTI_RATE_RP_P,
            .i         = AC_ATC_MULTI_RATE_RP_I,
            .d         = AC_ATC_MULTI_RATE_RP_D,
            .ff        = 0.0f,
            .imax      = AC_ATC_MULTI_RATE_RP_IMAX,
            .filt_T_hz = AC_ATC_MULTI_RATE_RPY_FILT_HZ,
            .filt_E_hz = 0.0f,
            .filt_D_hz = AC_ATC_MULTI_RATE_RPY_FILT_HZ,
            .srmax     = 0,
            .srtau     = 1.0
        }
    }
Definition at line 102 of file AC_AttitudeControl_Multi.h.
Referenced by get_rate_roll_pid(), get_rate_roll_pid(), and set_notch_sample_rate().
_pid_rate_yaw
AC_PID AC_AttitudeControl_Multi::_pid_rate_yaw protected
Initial value:
{
        AC_PID::Defaults{
            .p         = AC_ATC_MULTI_RATE_YAW_P,
            .i         = AC_ATC_MULTI_RATE_YAW_I,
            .d         = AC_ATC_MULTI_RATE_YAW_D,
            .ff        = 0.0f,
            .imax      = AC_ATC_MULTI_RATE_YAW_IMAX,
            .filt_T_hz = AC_ATC_MULTI_RATE_RPY_FILT_HZ,
            .filt_E_hz = AC_ATC_MULTI_RATE_YAW_FILT_HZ,
            .filt_D_hz = AC_ATC_MULTI_RATE_RPY_FILT_HZ,
            .srmax     = 0,
            .srtau     = 1.0
        }
    }
Definition at line 131 of file AC_AttitudeControl_Multi.h.
Referenced by get_rate_yaw_pid(), get_rate_yaw_pid(), and set_notch_sample_rate().
_thr_mix_man
AP_Float AC_AttitudeControl_Multi::_thr_mix_man protected
Definition at line 146 of file AC_AttitudeControl_Multi.h.
Referenced by AC_AttitudeControl_TS::input_euler_rate_yaw_euler_angle_pitch_bf_roll(), parameter_sanity_check(), AC_AttitudeControl_TS::relax_attitude_controllers(), set_notch_sample_rate(), and set_throttle_mix_man().
_thr_mix_max
AP_Float AC_AttitudeControl_Multi::_thr_mix_max protected
Definition at line 148 of file AC_AttitudeControl_Multi.h.
Referenced by parameter_sanity_check(), and set_throttle_mix_max().
_thr_mix_min
AP_Float AC_AttitudeControl_Multi::_thr_mix_min protected
Definition at line 147 of file AC_AttitudeControl_Multi.h.
Referenced by is_throttle_mix_min(), parameter_sanity_check(), set_throttle_mix_max(), and set_throttle_mix_min().
_throttle_gain_boost
AP_Float AC_AttitudeControl_Multi::_throttle_gain_boost protected
Definition at line 151 of file AC_AttitudeControl_Multi.h.
Referenced by update_throttle_gain_boost().
var_info
const AP_Param::GroupInfo AC_AttitudeControl_Multi::var_info static
Definition at line 8 of file AC_AttitudeControl_Multi.h.
The documentation for this class was generated from the following files:
libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.h
libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp