APM:Libraries: AP_HAL::OpticalFlow Class Reference
AP_HAL::OpticalFlow Class Reference abstract
#include <OpticalFlow.h>
Classes
class Data_Frame
Public Member Functions
virtual void init ()=0
virtual bool read (Data_Frame &frame)=0
virtual void push_gyro (float gyro_x, float gyro_y, float dt)=0
virtual void push_gyro_bias (float gyro_bias_x, float gyro_bias_y)=0
Detailed Description
Definition at line 17 of file OpticalFlow.h.
Member Function Documentation
init()
virtual void AP_HAL::OpticalFlow::init () pure virtual
Implemented in Empty::OpticalFlow, and Linux::OpticalFlow_Onboard.
Referenced by AP_OpticalFlow_Onboard::init().
push_gyro()
virtual void AP_HAL::OpticalFlow::push_gyro (float gyro_x, float gyro_y, float dt) pure virtual
Implemented in Empty::OpticalFlow, and Linux::OpticalFlow_Onboard.
Referenced by AP_InertialSensor_Backend::_notify_new_delta_angle(), and AP_InertialSensor_Backend::_notify_new_gyro_raw_sample().
push_gyro_bias()
virtual void AP_HAL::OpticalFlow::push_gyro_bias (float gyro_bias_x, float gyro_bias_y) pure virtual
Implemented in Empty::OpticalFlow, and Linux::OpticalFlow_Onboard.
Referenced by AP_AHRS::update().
read()
virtual bool AP_HAL::OpticalFlow::read (Data_Frame & frame) pure virtual
Implemented in Linux::OpticalFlow_Onboard, and Empty::OpticalFlow.
Referenced by AP_OpticalFlow_Onboard::update().
The documentation for this class was generated from the following file:
libraries/AP_HAL/OpticalFlow.h