APM:Libraries: AP_Param Class Reference
AP_Param Class Reference
#include <AP_Param.h>
Classes
struct ConversionInfo
struct defaults_list
struct defaults_table_struct
struct EEPROM_header
struct G2ObjectConversion
struct GroupInfo
struct GroupNesting
struct Info
struct Param_header
struct param_override
struct param_save
struct ParamToken
struct TopLevelObjectConversion
Public Types
enum { CONVERT_FLAG_REVERSE =1 , CONVERT_FLAG_FORCE =2 }
Public Member Functions
AP_Param (const struct Info *info)
AP_Param ()
void copy_name_info (const struct AP_Param::Info *info, const struct GroupInfo *ginfo, const struct GroupNesting &group_nesting, uint8_t idx, char *buffer, size_t bufferSize, bool force_scalar=false) const
void copy_name_token (const ParamToken &token, char *buffer, size_t bufferSize, bool force_scalar=false) const
void notify () const
void save_sync (bool force_save, bool send_to_gcs)
void save (bool force_save=false)
bool load (void)
void set_float (float value, enum ap_var_type var_type)
bool convert_parameter_width (ap_var_type old_ptype, float scale_factor=1.0)
bool convert_centi_parameter (ap_var_type old_ptype)
float cast_to_float (enum ap_var_type type) const
cast a variable to a float given its type
bool configured (void) const
bool is_read_only (void) const
Static Public Member Functions
static bool setup ()
static bool initialised (void)
static uint32_t group_id (const struct GroupInfo *grpinfo, uint32_t base, uint8_t i, uint8_t shift)
static AP_Param * find (const char *name, enum ap_var_type *ptype, uint16_t *flags=nullptr)
static bool set_default_by_name (const char *name, float value)
static void set_defaults_from_table (const struct defaults_table_struct *table, uint8_t count)
static bool set_by_name (const char *name, float value)
static bool get (const char *name, float &value)
static bool set_and_save_by_name (const char *name, float value)
static bool set_and_save_by_name_ifchanged (const char *name, float value)
static AP_Param * find_by_index (uint16_t idx, enum ap_var_type *ptype, ParamToken *token)
static AP_Param * find_by_name (const char *name, enum ap_var_type *ptype, ParamToken *token)
static bool find_key_by_pointer_group (const void *ptr, uint16_t vindex, const struct GroupInfo *group_info, ptrdiff_t offset, uint16_t &key)
static bool find_key_by_pointer (const void *ptr, uint16_t &key)
static bool find_top_level_key_by_pointer (const void *ptr, uint16_t &key)
static AP_Param * find_object (const char *name)
static void flush (void)
static bool load_all ()
static uint16_t storage_used ()
static uint16_t storage_size ()
static void reload_defaults_file (bool last_pass)
static void load_object_from_eeprom (const void *object_pointer, const struct GroupInfo *group_info)
static void set_value (enum ap_var_type type, void *ptr, float def_value)
static void setup_object_defaults (const void *object_pointer, const struct GroupInfo *group_info)
static bool set_object_value (const void *object_pointer, const struct GroupInfo *group_info, const char *name, float value)
static void setup_sketch_defaults (void)
static bool find_old_parameter (const struct ConversionInfo *info, AP_Param *value)
static void convert_old_parameters (const struct ConversionInfo *conversion_table, uint8_t table_size, uint8_t flags=0)
static void convert_old_parameters_scaled (const ConversionInfo *conversion_table, uint8_t table_size, float scaler, uint8_t flags)
static void convert_g2_objects (const void *g2, const G2ObjectConversion g2_conversions[], uint8_t num_conversions)
static void convert_toplevel_objects (const TopLevelObjectConversion g2_conversions[], uint8_t num_conversions)
static void convert_old_parameter (const struct ConversionInfo *info, float scaler, uint8_t flags=0)
static void convert_class (uint16_t param_key, void *object_pointer, const struct AP_Param::GroupInfo *group_info, uint16_t old_index, bool is_top_level)
static bool get_param_by_index (void *obj_ptr, uint8_t idx, ap_var_type old_ptype, void *pvalue)
static void erase_all (void)
static AP_Param * first (ParamToken *token, enum ap_var_type *ptype, float *default_val=nullptr)
static AP_Param * next (ParamToken *token, enum ap_var_type *ptype)
static AP_Param * next (ParamToken *token, enum ap_var_type *ptype, bool skip_disabled, float *default_val=nullptr)
static AP_Param * next_scalar (ParamToken *token, enum ap_var_type *ptype, float *default_val=nullptr)
static uint8_t type_size (enum ap_var_type type)
get the size of a type in bytes
static void check_var_info (void)
static uint16_t get_persistent_key (uint16_t key)
static uint16_t count_parameters (void)
static void invalidate_count (void)
static void set_hide_disabled_groups (bool value)
static void set_frame_type_flags (uint16_t flags_to_set)
static bool check_frame_type (uint16_t flags)
static AP_Param * get_singleton ()
static bool load_defaults_file (const char *filename, bool last_pass)
Static Protected Member Functions
static void add_default (AP_Param *ap, float v)
Private Member Functions
const struct Info * find_var_info_group (const struct GroupInfo *group_info, uint16_t vindex, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset, uint32_t *group_element, const struct GroupInfo *&group_ret, struct GroupNesting &group_nesting, uint8_t *idx) const
const struct Info * find_var_info (uint32_t *group_element, const struct GroupInfo *&group_ret, struct GroupNesting &group_nesting, uint8_t *idx) const
const struct Info * find_var_info_token (const ParamToken &token, uint32_t *group_element, const struct GroupInfo *&group_ret, struct GroupNesting &group_nesting, uint8_t *idx) const
void add_vector3f_suffix (char *buffer, size_t buffer_size, uint8_t idx) const
bool configured_in_defaults_file (bool &read_only) const
bool configured_in_storage (void) const
void send_parameter (const char *name, enum ap_var_type param_header_type, uint8_t idx) const
void save_io_handler (void)
Static Private Member Functions
static void check_group_info (const struct GroupInfo *group_info, uint16_t *total_size, uint8_t max_bits, uint8_t prefix_length)
static bool duplicate_key (uint16_t vindex, uint16_t key)
static bool adjust_group_offset (uint16_t vindex, const struct GroupInfo &group_info, ptrdiff_t &new_offset)
static bool get_base (const struct Info &info, ptrdiff_t &base)
static const struct GroupInfo * get_group_info (const struct GroupInfo &ginfo)
get group_info pointer based on flags
static const struct GroupInfo * get_group_info (const struct Info &ginfo)
get group_info pointer based on flags
static const struct Info * find_by_header_group (struct Param_header phdr, void **ptr, uint16_t vindex, const struct GroupInfo *group_info, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset)
static const struct Info * find_by_header (struct Param_header phdr, void **ptr)
static AP_Param * find_group (const char *name, uint16_t vindex, ptrdiff_t group_offset, const struct GroupInfo *group_info, enum ap_var_type *ptype)
static void write_sentinal (uint16_t ofs)
static uint16_t get_key (const Param_header &phdr)
static void set_key (Param_header &phdr, uint16_t key)
static bool is_sentinal (const Param_header &phrd)
static bool scan (const struct Param_header *phdr, uint16_t *pofs)
static void eeprom_write_check (const void *ptr, uint16_t ofs, uint8_t size)
static AP_Param * next_group (const uint16_t vindex, const struct GroupInfo *group_info, bool *found_current, const uint32_t group_base, const uint8_t group_shift, const ptrdiff_t group_offset, ParamToken *token, enum ap_var_type *ptype, bool skip_disabled, float *default_val)
static float get_default_value (const AP_Param *object_ptr, const struct GroupInfo &info)
static float get_default_value (const AP_Param *object_ptr, const struct Info &info)
static bool parse_param_line (char *line, char **vname, float &value, bool &read_only)
static bool count_defaults_in_file (const char *filename, uint16_t &num_defaults)
static bool count_param_defaults (const volatile char *ptr, int32_t length, uint16_t &count)
static bool read_param_defaults_file (const char *filename, bool last_pass, uint16_t &idx)
static void load_defaults_file_from_filesystem (const char *filename, bool lastpass)
static void load_defaults_file_from_romfs (const char *filename, bool lastpass)
static void load_param_defaults (const volatile char *ptr, int32_t length, bool last_pass)
static bool count_embedded_param_defaults (uint16_t &count)
static void load_embedded_param_defaults (bool last_pass)
static const struct Info & var_info (uint16_t i)
static void check_default (AP_Param *ap, float *default_value)
Static Private Attributes
static AP_Param * _singleton
static uint16_t sentinal_offset
static const uint8_t _group_level_shift = 6
static const uint8_t _group_bits = 18
static const uint16_t _sentinal_key = 0x1FF
static const uint8_t _sentinal_type = 0x1F
static const uint8_t _sentinal_group = 0xFF
static uint16_t _frame_type_flags
static bool done_all_default_params
static StorageAccess _storage
static StorageAccess _storage_bak
static uint16_t _num_vars
static uint16_t _parameter_count
static uint16_t _count_marker
static uint16_t _count_marker_done
static HAL_Semaphore _count_sem
static const struct Info * _var_info
static struct param_override * param_overrides
static uint16_t num_param_overrides
static uint16_t param_overrides_len
static uint16_t num_read_only
static const uint8_t k_EEPROM_magic0 = 0x50
static const uint8_t k_EEPROM_magic1 = 0x41
"AP"
static const uint8_t k_EEPROM_revision = 6
current format revision
static bool _hide_disabled_groups = true
static ObjectBuffer_TS< struct param_save > save_queue {30}
static bool registered_save_handler
static defaults_list * default_list
Detailed Description
Base class for variables.
Provides naming and lookup services for variables.
Definition at line 193 of file AP_Param.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
CONVERT_FLAG_REVERSE
CONVERT_FLAG_FORCE
Definition at line 504 of file AP_Param.h.
Constructor & Destructor Documentation
AP_Param() [1/2]
AP_Param::AP_Param (const struct Info * info) inline
Definition at line 244 of file AP_Param.h.
AP_Param() [2/2]
AP_Param::AP_Param () inline
Definition at line 260 of file AP_Param.h.
Member Function Documentation
add_default()
void AP_Param::add_default (AP_Param * ap, float v) static protected
Definition at line 2830 of file AP_Param.cpp.
add_vector3f_suffix()
void AP_Param::add_vector3f_suffix (char * buffer, size_t buffer_size, uint8_t idx) const private
add a _X, _Y, _Z suffix to the name of a Vector3f element
Parameters
buffer
buffer_size
idx Suffix: 0 --> _X; 1 --> _Y; 2 --> _Z; (other --> undefined)
Definition at line 787 of file AP_Param.cpp.
Referenced by copy_name_info().
adjust_group_offset()
bool AP_Param::adjust_group_offset (uint16_t vindex, const struct GroupInfo & group_info, ptrdiff_t & new_offset) static private
Definition at line 403 of file AP_Param.cpp.
Referenced by find_by_header_group(), find_group(), find_key_by_pointer_group(), find_var_info_group(), load_object_from_eeprom(), and next_group().
cast_to_float()
float AP_Param::cast_to_float (enum ap_var_type type) const
cast a variable to a float given its type
Definition at line 1916 of file AP_Param.cpp.
Referenced by convert_old_parameter(), convert_parameter_width(), GCS_MAVLINK::handle_param_set(), GCS_MAVLINK::queued_param_send(), save_sync(), and send_parameter().
check_default()
void AP_Param::check_default (AP_Param * ap, float * default_value) static private
Definition at line 2815 of file AP_Param.cpp.
Referenced by first(), and next_scalar().
check_frame_type()
bool AP_Param::check_frame_type (uint16_t flags) static
Definition at line 216 of file AP_Param.cpp.
Referenced by next(), and next_group().
check_group_info()
void AP_Param::check_group_info (const struct GroupInfo * group_info, uint16_t * total_size, uint8_t max_bits, uint8_t prefix_length) static private
Definition at line 230 of file AP_Param.cpp.
Referenced by check_group_info(), and check_var_info().
check_var_info()
void AP_Param::check_var_info (void) static
Definition at line 311 of file AP_Param.cpp.
Referenced by AP_Vehicle::setup().
configured()
bool AP_Param::configured (void) const
Definition at line 1422 of file AP_Param.cpp.
Referenced by SITL::FlightAxis::FlightAxis(), SITL::JSON::JSON(), SITL::Morse::Morse(), SITL::SilentWings::SilentWings(), and SITL::Webots::Webots().
configured_in_defaults_file()
bool AP_Param::configured_in_defaults_file (bool & read_only) const private
Definition at line 1397 of file AP_Param.cpp.
Referenced by configured(), and is_read_only().
configured_in_storage()
bool AP_Param::configured_in_storage (void) const private
Definition at line 1367 of file AP_Param.cpp.
Referenced by configured(), convert_class(), convert_old_parameter(), and convert_parameter_width().
convert_centi_parameter()
bool AP_Param::convert_centi_parameter (ap_var_type old_ptype) inline
Definition at line 499 of file AP_Param.h.
convert_class()
void AP_Param::convert_class (uint16_t param_key, void * object_pointer, const struct AP_Param::GroupInfo * group_info, uint16_t old_index, bool is_top_level) static
Definition at line 2032 of file AP_Param.cpp.
Referenced by convert_g2_objects(), and convert_toplevel_objects().
convert_g2_objects()
void AP_Param::convert_g2_objects (const void * g2, const G2ObjectConversion g2_conversions[], uint8_t num_conversions) static
Definition at line 2077 of file AP_Param.cpp.
convert_old_parameter()
void AP_Param::convert_old_parameter (const struct ConversionInfo * info, float scaler, uint8_t flags = 0) static
Definition at line 1956 of file AP_Param.cpp.
Referenced by AP_BattMonitor::convert_dynamic_param_groups(), convert_old_parameters_scaled(), AP_Camera::convert_params(), AP_Mount::convert_params(), AP_RPM::convert_params(), and AP_Airspeed::convert_per_instance().
convert_old_parameters()
void AP_Param::convert_old_parameters (const struct ConversionInfo * conversion_table, uint8_t table_size, uint8_t flags = 0) static
Definition at line 2014 of file AP_Param.cpp.
convert_old_parameters_scaled()
void AP_Param::convert_old_parameters_scaled (const ConversionInfo * conversion_table, uint8_t table_size, float scaler, uint8_t flags) static
Definition at line 2020 of file AP_Param.cpp.
Referenced by convert_old_parameters().
convert_parameter_width()
bool AP_Param::convert_parameter_width (ap_var_type old_ptype, float scale_factor = 1.0)
Definition at line 2102 of file AP_Param.cpp.
Referenced by convert_centi_parameter().
convert_toplevel_objects()
void AP_Param::convert_toplevel_objects (const TopLevelObjectConversion g2_conversions[], uint8_t num_conversions) static
Definition at line 2090 of file AP_Param.cpp.
copy_name_info()
void AP_Param::copy_name_info (const struct AP_Param::Info * info, const struct GroupInfo * ginfo, const struct GroupNesting & group_nesting, uint8_t idx, char * buffer, size_t bufferSize, bool force_scalar = false) const
Copy the variable's name, prefixed by any containing group name, to a buffer.
If the variable has no name, the buffer will contain an empty string.
Note that if the combination of names is larger than the buffer, the result in the buffer will be truncated.
Parameters
token token giving current variable
buffer The destination buffer
bufferSize Total size of the destination buffer.
Definition at line 818 of file AP_Param.cpp.
Referenced by copy_name_token(), notify(), and save_sync().
copy_name_token()
void AP_Param::copy_name_token (const ParamToken & token, char * buffer, size_t bufferSize, bool force_scalar = false) const
Copy the variable's name, prefixed by any containing group name, to a buffer.
Uses token to look up AP_Param::Info for the variable
Definition at line 803 of file AP_Param.cpp.
Referenced by AP_OSD_ParamSetting::copy_name(), AP_OSD_ParamSetting::copy_name_camel_case(), and GCS_MAVLINK::queued_param_send().
count_defaults_in_file()
static bool AP_Param::count_defaults_in_file (const char * filename, uint16_t & num_defaults) static private
count_embedded_param_defaults()
static bool AP_Param::count_embedded_param_defaults (uint16_t & count) static private
count_param_defaults()
static bool AP_Param::count_param_defaults (const volatile char * ptr, int32_t length, uint16_t & count) static private
count_parameters()
uint16_t AP_Param::count_parameters (void) static
Definition at line 2605 of file AP_Param.cpp.
Referenced by GCS_MAVLINK::handle_param_request_list(), AP_Filesystem_Param::pack_param(), GCS_MAVLINK::param_io_timer(), AP_Filesystem_Param::read(), save_io_handler(), GCS_MAVLINK::send_parameter_value(), GCS::send_parameter_value(), and AP_Filesystem_Param::stat().
duplicate_key()
bool AP_Param::duplicate_key (uint16_t vindex, uint16_t key) static private
Definition at line 276 of file AP_Param.cpp.
Referenced by check_var_info().
eeprom_write_check()
void AP_Param::eeprom_write_check (const void * ptr, uint16_t ofs, uint8_t size) static private
Definition at line 151 of file AP_Param.cpp.
Referenced by erase_all(), save_sync(), and write_sentinal().
erase_all()
void AP_Param::erase_all (void) static
Erase all variables in EEPROM.
Definition at line 174 of file AP_Param.cpp.
Referenced by HALSITL::SITL_State::_parse_command_line(), GCS_MAVLINK::handle_command_int_packet(), AP_Vehicle::load_parameters(), and setup().
find()
AP_Param * AP_Param::find (const char * name, enum ap_var_type * ptype, uint16_t * flags = nullptr) static
Find a variable by name.
If the variable has no name, it cannot be found by this interface.
Parameters
name The full name of the variable to be found.
flags If non-null will be filled with parameter flags
Returns
A pointer to the variable, or nullptr if it does not exist.
Definition at line 910 of file AP_Param.cpp.
Referenced by HALSITL::SITL_State::_set_param_default(), convert_old_parameter(), AP_Mount::convert_params(), SITL::FlightAxis::FlightAxis(), get(), AP_Frsky_MAVliteMsgHandler::handle_param_set(), GCS_MAVLINK::handle_param_set(), SITL::JSON::JSON(), SITL::Morse::Morse(), GCS_MAVLINK::param_io_timer(), AP_Filesystem_Param::param_upload_parse(), set_and_save_by_name(), set_and_save_by_name_ifchanged(), set_by_name(), set_default_by_name(), SITL::SilentWings::SilentWings(), and SITL::Webots::Webots().
find_by_header()
const struct AP_Param::Info * AP_Param::find_by_header (struct Param_header phdr, void ** ptr) static private
Definition at line 502 of file AP_Param.cpp.
Referenced by load_all(), and load_object_from_eeprom().
find_by_header_group()
const struct AP_Param::Info * AP_Param::find_by_header_group (struct Param_header phdr, void ** ptr, uint16_t vindex, const struct GroupInfo * group_info, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset) static private
Definition at line 451 of file AP_Param.cpp.
Referenced by find_by_header(), and find_by_header_group().
find_by_index()
AP_Param * AP_Param::find_by_index (uint16_t idx, enum ap_var_type * ptype, ParamToken * token) static
Find a variable by index.
Parameters
idx The index of the variable
Returns
A pointer to the variable, or nullptr if it does not exist.
Definition at line 956 of file AP_Param.cpp.
Referenced by GCS_MAVLINK::param_io_timer().
find_by_name()
AP_Param * AP_Param::find_by_name (const char * name, enum ap_var_type * ptype, ParamToken * token) static
Definition at line 969 of file AP_Param.cpp.
Referenced by AP_BattMonitor::convert_dynamic_param_groups(), and AP_OSD_ParamSetting::set_by_name().
find_group()
AP_Param * AP_Param::find_group (const char * name, uint16_t vindex, ptrdiff_t group_offset, const struct GroupInfo * group_info, enum ap_var_type * ptype) static private
Definition at line 846 of file AP_Param.cpp.
Referenced by find(), and find_group().
find_key_by_pointer()
bool AP_Param::find_key_by_pointer (const void * ptr, uint16_t & key) static
Definition at line 1030 of file AP_Param.cpp.
Referenced by AP_Airspeed::convert_per_instance(), and load_object_from_eeprom().
find_key_by_pointer_group()
bool AP_Param::find_key_by_pointer_group (const void * ptr, uint16_t vindex, const struct GroupInfo * group_info, ptrdiff_t offset, uint16_t & key) static
Find a variable by pointer
Parameters
p Pointer to variable
Returns
key for variable
Definition at line 990 of file AP_Param.cpp.
Referenced by find_key_by_pointer(), and find_key_by_pointer_group().
find_object()
AP_Param * AP_Param::find_object (const char * name) static
Find a object in the top level var_info table
If the variable has no name, it cannot be found by this interface.
Parameters
name The full name of the variable to be found.
Definition at line 1091 of file AP_Param.cpp.
find_old_parameter()
bool AP_Param::find_old_parameter (const struct ConversionInfo * info, AP_Param * value) static
Definition at line 1935 of file AP_Param.cpp.
Referenced by convert_class(), convert_old_parameter(), NavEKF3::convert_parameters(), get_param_by_index(), Compass::init(), and AP_AHRS::init().
find_top_level_key_by_pointer()
bool AP_Param::find_top_level_key_by_pointer (const void * ptr, uint16_t & key) static
Find key of top level group variable by pointer
Parameters
p Pointer to variable
Returns
key for variable
Definition at line 1057 of file AP_Param.cpp.
Referenced by AP_BattMonitor::convert_dynamic_param_groups(), convert_g2_objects(), NavEKF3::convert_parameters(), AP_Camera::convert_params(), AP_Mount::convert_params(), AP_RPM::convert_params(), AP_Airspeed::convert_per_instance(), get_param_by_index(), Compass::init(), and AP_AHRS::init().
find_var_info()
const struct AP_Param::Info * AP_Param::find_var_info (uint32_t * group_element, const struct GroupInfo *& group_ret, struct GroupNesting & group_nesting, uint8_t * idx) const private
Definition at line 605 of file AP_Param.cpp.
Referenced by configured_in_defaults_file(), configured_in_storage(), convert_parameter_width(), load(), notify(), and save_sync().
find_var_info_group()
const struct AP_Param::Info * AP_Param::find_var_info_group (const struct GroupInfo * group_info, uint16_t vindex, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset, uint32_t * group_element, const struct GroupInfo *& group_ret, struct GroupNesting & group_nesting, uint8_t * idx) const private
Definition at line 534 of file AP_Param.cpp.
Referenced by find_var_info(), find_var_info_group(), and find_var_info_token().
find_var_info_token()
const struct AP_Param::Info * AP_Param::find_var_info_token (const ParamToken & token, uint32_t * group_element, const struct GroupInfo *& group_ret, struct GroupNesting & group_nesting, uint8_t * idx) const private
Definition at line 648 of file AP_Param.cpp.
Referenced by copy_name_token().
first()
AP_Param * AP_Param::first (ParamToken * token, enum ap_var_type * ptype, float * default_val = nullptr) static
Returns the first variable
Returns
The first variable in _var_info, or nullptr if there are none.
Definition at line 1705 of file AP_Param.cpp.
Referenced by count_parameters(), find_by_index(), find_by_name(), GCS_MAVLINK::handle_param_request_list(), AP_OSD_ParamScreen::modify_configured_parameter(), AP_Filesystem_Param::pack_param(), LoggerMessageWriter_DFLogStart::reset(), and AP_OSD_ParamSetting::update().
flush()
void AP_Param::flush (void) static
flush all pending parameter saves used on reboot
Definition at line 1292 of file AP_Param.cpp.
Referenced by convert_class(), convert_old_parameters_scaled(), and AP_Vehicle::reboot().
get()
bool AP_Param::get (const char * name, float & value) static
gat a value by name, used by scripting
Parameters
name The full name of the variable to be found.
value A reference to the variable
Returns
true if the variable is found
Definition at line 2724 of file AP_Param.cpp.
Referenced by AP_OSD_ParamSetting::guess_ranges(), AP_Frsky_MAVliteMsgHandler::handle_param_request_read(), AP_Frsky_MAVliteMsgHandler::handle_param_set(), and AP_OSD_ParamScreen::modify_parameter().
get_base()
bool AP_Param::get_base (const struct Info & info, ptrdiff_t & base) static private
Definition at line 430 of file AP_Param.cpp.
Referenced by adjust_group_offset(), find(), find_by_header(), find_by_header_group(), find_group(), find_key_by_pointer_group(), find_object(), find_var_info(), find_var_info_group(), find_var_info_token(), first(), load(), next_group(), and setup_sketch_defaults().
get_default_value() [1/2]
float AP_Param::get_default_value (const AP_Param * object_ptr, const struct GroupInfo & info) static private
Definition at line 2538 of file AP_Param.cpp.
Referenced by first(), load(), next(), next_group(), save_sync(), and setup_sketch_defaults().
get_default_value() [2/2]
float AP_Param::get_default_value (const AP_Param * object_ptr, const struct Info & info) static private
Definition at line 2551 of file AP_Param.cpp.
get_group_info() [1/2]
const struct AP_Param::GroupInfo * AP_Param::get_group_info (const struct GroupInfo & ginfo) static private
get group_info pointer based on flags
Definition at line 291 of file AP_Param.cpp.
Referenced by check_group_info(), check_var_info(), find(), find_by_header(), find_by_header_group(), find_group(), find_key_by_pointer(), find_key_by_pointer_group(), find_var_info(), find_var_info_group(), find_var_info_token(), load_object_from_eeprom(), next(), and next_group().
get_group_info() [2/2]
const struct AP_Param::GroupInfo * AP_Param::get_group_info (const struct Info & ginfo) static private
get group_info pointer based on flags
Definition at line 302 of file AP_Param.cpp.
get_key()
uint16_t AP_Param::get_key (const Param_header & phdr) static private
Definition at line 714 of file AP_Param.cpp.
Referenced by find_by_header(), is_sentinal(), load_object_from_eeprom(), and scan().
get_param_by_index()
bool AP_Param::get_param_by_index (void * obj_ptr, uint8_t idx, ap_var_type old_ptype, void * pvalue) static
Definition at line 1077 of file AP_Param.cpp.
Referenced by AP_Camera::convert_params(), AP_Mount::convert_params(), AP_Relay::convert_params(), AP_RPM::convert_params(), AP_PitchController::convert_pid(), and AP_RollController::convert_pid().
get_persistent_key()
static uint16_t AP_Param::get_persistent_key (uint16_t key) inline static
Definition at line 559 of file AP_Param.h.
Referenced by AP_OSD_ParamScreen::modify_configured_parameter(), AP_OSD_ParamSetting::set_by_name(), and AP_OSD_ParamSetting::update().
get_singleton()
static AP_Param * AP_Param::get_singleton () inline static
Definition at line 595 of file AP_Param.h.
Referenced by AP::param().
group_id()
uint32_t AP_Param::group_id (const struct GroupInfo * grpinfo, uint32_t base, uint8_t i, uint8_t shift) static
Definition at line 196 of file AP_Param.cpp.
Referenced by find_by_header_group(), find_var_info_group(), and next_group().
initialised()
bool AP_Param::initialised (void) static
Definition at line 392 of file AP_Param.cpp.
invalidate_count()
void AP_Param::invalidate_count (void) static
Definition at line 2640 of file AP_Param.cpp.
Referenced by RangeFinder::detect_instance(), GCS_MAVLINK::handle_param_set(), AP_BattMonitor::init(), AP_RunCam::init(), load_object_from_eeprom(), AP_Filesystem_Param::pack_param(), save_sync(), set_frame_type_flags(), and AP_Vehicle::setup().
is_read_only()
bool AP_Param::is_read_only (void) const
Definition at line 1428 of file AP_Param.cpp.
Referenced by AP_OSD_ParamSetting::guess_ranges(), AP_Frsky_MAVliteMsgHandler::handle_param_set(), GCS_MAVLINK::handle_param_set(), and AP_OSD_ParamScreen::modify_parameter().
is_sentinal()
bool AP_Param::is_sentinal (const Param_header & phrd) static private
Definition at line 731 of file AP_Param.cpp.
Referenced by load_all(), load_object_from_eeprom(), and scan().
load()
bool AP_Param::load (void)
Load the variable from EEPROM.
Returns
True if the variable was loaded successfully.
Definition at line 1304 of file AP_Param.cpp.
load_all()
bool AP_Param::load_all () static
Load all variables from EEPROM
This function performs a best-efforts attempt to load all of the variables from EEPROM. If some fail to load, their values will remain as they are.
Returns
False if any variable failed to load
Definition at line 1528 of file AP_Param.cpp.
Referenced by AP_Vehicle::load_parameters().
load_defaults_file()
static bool AP_Param::load_defaults_file (const char * filename, bool last_pass) static
Referenced by SITL::Plane::Plane().
load_defaults_file_from_filesystem()
static void AP_Param::load_defaults_file_from_filesystem (const char * filename, bool lastpass) static private
Referenced by reload_defaults_file().
load_defaults_file_from_romfs()
static void AP_Param::load_defaults_file_from_romfs (const char * filename, bool lastpass) static private
Referenced by reload_defaults_file().
load_embedded_param_defaults()
static void AP_Param::load_embedded_param_defaults (bool last_pass) static private
Referenced by reload_defaults_file().
load_object_from_eeprom()
void AP_Param::load_object_from_eeprom (const void * object_pointer, const struct GroupInfo * group_info) static
Definition at line 1645 of file AP_Param.cpp.
Referenced by RangeFinder::detect_instance(), AP_OAPathPlanner::init(), AP_BattMonitor::init(), and load_object_from_eeprom().
load_param_defaults()
static void AP_Param::load_param_defaults (const volatile char * ptr, int32_t length, bool last_pass) static private
next() [1/2]
static AP_Param * AP_Param::next (ParamToken * token, enum ap_var_type * ptype) inline static
Returns the next variable in _var_info, recursing into groups as needed
Definition at line 536 of file AP_Param.h.
Referenced by next().
next() [2/2]
AP_Param * AP_Param::next (ParamToken * token, enum ap_var_type * ptype, bool skip_disabled, float * default_val = nullptr) static
Returns the next variable in _var_info, recursing into groups as needed
Definition at line 1831 of file AP_Param.cpp.
next_group()
AP_Param * AP_Param::next_group (const uint16_t vindex, const struct GroupInfo * group_info, bool * found_current, const uint32_t group_base, const uint8_t group_shift, const ptrdiff_t group_offset, ParamToken * token, enum ap_var_type * ptype, bool skip_disabled, float * default_val) static private
Returns the next variable in a group, recursing into groups as needed
Definition at line 1732 of file AP_Param.cpp.
Referenced by next(), and next_group().
next_scalar()
AP_Param * AP_Param::next_scalar (ParamToken * token, enum ap_var_type * ptype, float * default_val = nullptr) static
Returns the next scalar variable in _var_info, recursing into groups as needed
Returns the next scalar in _var_info, recursing into groups as needed
Definition at line 1897 of file AP_Param.cpp.
Referenced by count_parameters(), find_by_index(), find_by_name(), AP_OSD_ParamScreen::modify_configured_parameter(), AP_Filesystem_Param::pack_param(), LoggerMessageWriter_DFLogStart::process(), GCS_MAVLINK::queued_param_send(), and AP_OSD_ParamSetting::update().
notify()
void AP_Param::notify () const
Notify GCS of current parameter value
Definition at line 1107 of file AP_Param.cpp.
parse_param_line()
bool AP_Param::parse_param_line (char * line, char ** vname, float & value, bool & read_only) static private
Definition at line 2196 of file AP_Param.cpp.
read_param_defaults_file()
static bool AP_Param::read_param_defaults_file (const char * filename, bool last_pass, uint16_t & idx) static private
reload_defaults_file()
void AP_Param::reload_defaults_file (bool last_pass) static
reoad the hal.util defaults file. Called after pointer parameters have been allocated
Definition at line 1569 of file AP_Param.cpp.
Referenced by load_all(), and load_object_from_eeprom().
save()
void AP_Param::save (bool force_save = false)
Save the current value of the variable to storage, async interface
Parameters
force_save If true then force save even if default
Definition at line 1244 of file AP_Param.cpp.
Referenced by convert_class(), convert_old_parameter(), SITL::FlightAxis::FlightAxis(), GCS_MAVLINK::handle_param_set(), SITL::JSON::JSON(), SITL::Morse::Morse(), AP_OSD_ParamScreen::save_parameters(), SITL::SilentWings::SilentWings(), and SITL::Webots::Webots().
save_io_handler()
void AP_Param::save_io_handler (void) private
Definition at line 1277 of file AP_Param.cpp.
Referenced by load_all().
save_sync()
void AP_Param::save_sync (bool force_save, bool send_to_gcs)
Save the current value of the variable to storage, synchronous API
Parameters
force_save If true then force save even if default
Returns
True if the variable was saved successfully.
Definition at line 1136 of file AP_Param.cpp.
Referenced by AP_Filesystem_Param::param_upload_parse(), and save_io_handler().
scan()
bool AP_Param::scan (const struct Param_header * phdr, uint16_t * pofs) static private
Definition at line 755 of file AP_Param.cpp.
Referenced by configured_in_storage(), convert_parameter_width(), find_old_parameter(), load(), and save_sync().
send_parameter()
void AP_Param::send_parameter (const char * name, enum ap_var_type param_header_type, uint8_t idx) const private
Definition at line 2565 of file AP_Param.cpp.
Referenced by notify(), and save_sync().
set_and_save_by_name()
bool AP_Param::set_and_save_by_name (const char * name, float value) static
set and save a value by name
Parameters
name The full name of the variable to be found.
value The new value
Returns
true if the variable is found
Definition at line 2757 of file AP_Param.cpp.
Referenced by NavEKF3::convert_parameters(), and AP_Frsky_MAVliteMsgHandler::handle_param_set().
set_and_save_by_name_ifchanged()
bool AP_Param::set_and_save_by_name_ifchanged (const char * name, float value) static
Definition at line 2787 of file AP_Param.cpp.
set_by_name()
bool AP_Param::set_by_name (const char * name, float value) static
set a value by name
Parameters
name The full name of the variable to be found.
value The new value
Returns
true if the variable is found
Definition at line 2694 of file AP_Param.cpp.
Referenced by setup().
set_default_by_name()
bool AP_Param::set_default_by_name (const char * name, float value) static
set a default value by name
Parameters
name The full name of the variable to be found.
value The default value
Returns
true if the variable is found
Definition at line 2651 of file AP_Param.cpp.
Referenced by SITL::FlightAxis::FlightAxis(), SITL::JSON::JSON(), SITL::Morse::Morse(), HALSITL::Util::set_cmdline_parameters(), set_defaults_from_table(), SITL::SilentWings::SilentWings(), SITL::Webots::Webots(), and SITL::XPlane::XPlane().
set_defaults_from_table()
void AP_Param::set_defaults_from_table (const struct defaults_table_struct * table, uint8_t count) static
set parameter defaults from a defaults_table_struct
Parameters
table pointer to array of defaults_table_struct structures
count number of elements in table array
Definition at line 2682 of file AP_Param.cpp.
Referenced by AP_OSD_MSP::setup_defaults().
set_float()
void AP_Param::set_float (float value, enum ap_var_type var_type)
Definition at line 2160 of file AP_Param.cpp.
Referenced by GCS_MAVLINK::handle_param_set(), and AP_Filesystem_Param::param_upload_parse().
set_frame_type_flags()
static void AP_Param::set_frame_type_flags (uint16_t flags_to_set) inline static
Definition at line 570 of file AP_Param.h.
set_hide_disabled_groups()
static void AP_Param::set_hide_disabled_groups (bool value) inline static
Definition at line 567 of file AP_Param.h.
Referenced by HALSITL::SITL_State::_parse_command_line().
set_key()
void AP_Param::set_key (Param_header & phdr, uint16_t key) static private
Definition at line 722 of file AP_Param.cpp.
Referenced by configured_in_storage(), convert_parameter_width(), find_old_parameter(), load(), save_sync(), and write_sentinal().
set_object_value()
bool AP_Param::set_object_value (const void * object_pointer, const struct GroupInfo * group_info, const char * name, float value) static
Definition at line 1486 of file AP_Param.cpp.
Referenced by set_object_value_and_report(), and setup().
set_value()
void AP_Param::set_value (enum ap_var_type type, void * ptr, float def_value) static
Definition at line 1441 of file AP_Param.cpp.
Referenced by convert_old_parameter(), convert_parameter_width(), load(), set_object_value(), and setup_sketch_defaults().
setup()
bool AP_Param::setup (void) static
Definition at line 352 of file AP_Param.cpp.
Referenced by setup(), and setup_sketch_defaults().
setup_object_defaults()
void AP_Param::setup_object_defaults (const void * object_pointer, const struct GroupInfo * group_info) static
Definition at line 10 of file main.cpp.
Referenced by AC_AttitudeControl::AC_AttitudeControl(), AC_AttitudeControl_Heli::AC_AttitudeControl_Heli(), AC_AttitudeControl_Multi::AC_AttitudeControl_Multi(), AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), AC_Autorotation::AC_Autorotation(), AC_AutoTune_Heli::AC_AutoTune_Heli(), AC_AutoTune_Multi::AC_AutoTune_Multi(), AC_Avoid::AC_Avoid(), AC_Circle::AC_Circle(), AC_CommandModel::AC_CommandModel(), AC_InputManager::AC_InputManager(), AC_InputManager_Heli::AC_InputManager_Heli(), AC_Loiter::AC_Loiter(), AC_P::AC_P(), AC_P_1D::AC_P_1D(), AC_P_2D::AC_P_2D(), AC_PI::AC_PI(), AC_PI_2D::AC_PI_2D(), AC_PID::AC_PID(), AC_PID_2D::AC_PID_2D(), AC_PID_Basic::AC_PID_Basic(), AC_PosControl::AC_PosControl(), AC_PrecLand::AC_PrecLand(), AC_Sprayer::AC_Sprayer(), AC_WeatherVane::AC_WeatherVane(), AC_WPNav::AC_WPNav(), AP_AdvancedFailsafe::AP_AdvancedFailsafe(), AP_AHRS::AP_AHRS(), AP_Airspeed::AP_Airspeed(), AP_Airspeed_Params::AP_Airspeed_Params(), AP_Arming::AP_Arming(), AP_Baro::AP_Baro(), AP_BattMonitor::AP_BattMonitor(), AP_BattMonitor_Analog::AP_BattMonitor_Analog(), AP_BattMonitor_Params::AP_BattMonitor_Params(), AP_BattMonitor_SMBus::AP_BattMonitor_SMBus(), AP_BattMonitor_Sum::AP_BattMonitor_Sum(), AP_BattMonitor_Synthetic_Current::AP_BattMonitor_Synthetic_Current(), AP_Beacon::AP_Beacon(), AP_Button::AP_Button(), AP_Camera::AP_Camera(), AP_Camera_Params::AP_Camera_Params(), AP_CustomRotation_params::AP_CustomRotation_params(), AP_CustomRotations::AP_CustomRotations(), AP_Follow::AP_Follow(), AP_Frsky_Parameters::AP_Frsky_Parameters(), AP_Generator::AP_Generator(), AP_GPS::AP_GPS(), AP_Gripper::AP_Gripper(), AP_ICEngine::AP_ICEngine(), AP_InertialSensor::AP_InertialSensor(), AP_InertialSensor_Params::AP_InertialSensor_Params(), AP_L1_Control::AP_L1_Control(), AP_Landing::AP_Landing(), AP_LeakDetector::AP_LeakDetector(), AP_Logger::AP_Logger(), AP_Mission::AP_Mission(), AP_Motors6DOF::AP_Motors6DOF(), AP_MotorsHeli::AP_MotorsHeli(), AP_MotorsHeli_Dual::AP_MotorsHeli_Dual(), AP_MotorsHeli_RSC::AP_MotorsHeli_RSC(), AP_MotorsHeli_Single::AP_MotorsHeli_Single(), AP_MotorsHeli_Swash::AP_MotorsHeli_Swash(), AP_MotorsMulticopter::AP_MotorsMulticopter(), AP_MotorsUGV::AP_MotorsUGV(), AP_Mount::AP_Mount(), AP_Mount_Params::AP_Mount_Params(), AP_MSP::AP_MSP(), AP_NavEKF_Source::AP_NavEKF_Source(), AP_Networking::AP_Networking(), AP_Networking_IPV4::AP_Networking_IPV4(), AP_Networking_MAC::AP_Networking_MAC(), AP_Notify::AP_Notify(), AP_OABendyRuler::AP_OABendyRuler(), AP_OADatabase::AP_OADatabase(), AP_OAPathPlanner::AP_OAPathPlanner(), AP_OpticalFlow::AP_OpticalFlow(), AP_OSD::AP_OSD(), AP_OSD_ParamScreen::AP_OSD_ParamScreen(), AP_OSD_ParamSetting::AP_OSD_ParamSetting(), AP_OSD_ParamSetting::AP_OSD_ParamSetting(), AP_OSD_Screen::AP_OSD_Screen(), AP_OSD_Setting::AP_OSD_Setting(), AP_Parachute::AP_Parachute(), AP_PitchController::AP_PitchController(), AP_Proximity_Params::AP_Proximity_Params(), AP_Rally::AP_Rally(), AP_RangeFinder_Params::AP_RangeFinder_Params(), AP_RangeFinder_Wasp::AP_RangeFinder_Wasp(), AP_Relay::AP_Relay(), AP_Relay_Params::AP_Relay_Params(), AP_RollController::AP_RollController(), AP_RPM::AP_RPM(), AP_RPM_Params::AP_RPM_Params(), AP_RSSI::AP_RSSI(), AP_RTC::AP_RTC(), AP_RunCam::AP_RunCam(), AP_SBusOut::AP_SBusOut(), AP_Scheduler::AP_Scheduler(), AP_SerialManager::AP_SerialManager(), AP_SmartRTL::AP_SmartRTL(), AP_Stats::AP_Stats(), AP_SteerController::AP_SteerController(), AP_TECS::AP_TECS(), AP_Tuning::AP_Tuning(), AP_Vehicle::AP_Vehicle(), AP_VideoTX::AP_VideoTX(), AP_WheelEncoder::AP_WheelEncoder(), AP_WheelRateControl::AP_WheelRateControl(), AP_Winch::AP_Winch(), AP_WindVane::AP_WindVane(), AP_YawController::AP_YawController(), AR_AttitudeControl::AR_AttitudeControl(), AR_PivotTurn::AR_PivotTurn(), AR_PosControl::AR_PosControl(), AR_WPNav::AR_WPNav(), Compass::Compass(), Compass_PerMotor::Compass_PerMotor(), SITL::FETtecOneWireESC::FETtecOneWireESC(), GCS_MAVLINK_Parameters::GCS_MAVLINK_Parameters(), SITL::Gripper_EPM::Gripper_EPM(), SITL::Gripper_Servo::Gripper_Servo(), HarmonicNotchFilterParams::HarmonicNotchFilterParams(), SITL::IntelligentEnergy24::IntelligentEnergy24(), JSButton::JSButton(), MovingBase::MovingBase(), NavEKF2::NavEKF2(), NavEKF3::NavEKF3(), SITL::Parachute::Parachute(), PID::PID(), RangeFinder::RangeFinder(), RC_Channel::RC_Channel(), RC_Channels::RC_Channels(), RCMapper::RCMapper(), SITL::RichenPower::RichenPower(), SITL::ShipSim::ShipSim(), SITL::SIM_Precland::SIM_Precland(), SoaringController::SoaringController(), SITL::Sprayer::Sprayer(), SRV_Channel::SRV_Channel(), SRV_Channels::SRV_Channels(), Thrust_Linearization::Thrust_Linearization(), and SITL::ToneAlarm::ToneAlarm().
setup_sketch_defaults()
void AP_Param::setup_sketch_defaults (void) static
Definition at line 1509 of file AP_Param.cpp.
Referenced by AP_Vehicle::setup().
storage_size()
static uint16_t AP_Param::storage_size () inline static
Definition at line 437 of file AP_Param.h.
Referenced by LoggerMessageWriter_WriteSysInfo::process().
storage_used()
static uint16_t AP_Param::storage_used () inline static
Definition at line 434 of file AP_Param.h.
Referenced by LoggerMessageWriter_WriteSysInfo::process().
type_size()
uint8_t AP_Param::type_size (enum ap_var_type type) static
get the size of a type in bytes
Definition at line 690 of file AP_Param.cpp.
Referenced by check_group_info(), check_var_info(), convert_class(), convert_old_parameter(), convert_parameter_width(), find_old_parameter(), load(), load_all(), load_object_from_eeprom(), AP_Filesystem_Param::pack_param(), save_sync(), and scan().
var_info()
static const struct Info & AP_Param::var_info (uint16_t i) inline static private
Definition at line 810 of file AP_Param.h.
write_sentinal()
void AP_Param::write_sentinal (uint16_t ofs) static private
Definition at line 162 of file AP_Param.cpp.
Referenced by erase_all(), and save_sync().
Member Data Documentation
_count_marker
uint16_t AP_Param::_count_marker static private
Definition at line 795 of file AP_Param.h.
Referenced by count_parameters(), and invalidate_count().
_count_marker_done
uint16_t AP_Param::_count_marker_done static private
Definition at line 796 of file AP_Param.h.
Referenced by count_parameters().
_count_sem
HAL_Semaphore AP_Param::_count_sem static private
Definition at line 797 of file AP_Param.h.
Referenced by count_parameters().
_frame_type_flags
uint16_t AP_Param::_frame_type_flags static private
Definition at line 657 of file AP_Param.h.
Referenced by check_frame_type(), and set_frame_type_flags().
_group_bits
const uint8_t AP_Param::_group_bits = 18 static private
Definition at line 651 of file AP_Param.h.
Referenced by check_group_info(), find_by_header_group(), and find_var_info_group().
_group_level_shift
const uint8_t AP_Param::_group_level_shift = 6 static private
Definition at line 650 of file AP_Param.h.
Referenced by check_group_info(), find_by_header_group(), find_var_info_group(), and next_group().
_hide_disabled_groups
bool AP_Param::_hide_disabled_groups = true static private
Definition at line 833 of file AP_Param.h.
Referenced by next_group(), and set_hide_disabled_groups().
_num_vars
uint16_t AP_Param::_num_vars static private
Definition at line 793 of file AP_Param.h.
Referenced by AP_Param(), check_var_info(), duplicate_key(), find(), find_by_header(), find_key_by_pointer(), find_object(), find_top_level_key_by_pointer(), find_var_info(), first(), next(), and setup_sketch_defaults().
_parameter_count
uint16_t AP_Param::_parameter_count static private
Definition at line 794 of file AP_Param.h.
Referenced by count_parameters().
_sentinal_group
const uint8_t AP_Param::_sentinal_group = 0xFF static private
Definition at line 655 of file AP_Param.h.
Referenced by write_sentinal().
_sentinal_key
const uint16_t AP_Param::_sentinal_key = 0x1FF static private
Definition at line 653 of file AP_Param.h.
Referenced by is_sentinal(), and write_sentinal().
_sentinal_type
const uint8_t AP_Param::_sentinal_type = 0x1F static private
Definition at line 654 of file AP_Param.h.
Referenced by is_sentinal(), and write_sentinal().
_singleton
AP_Param * AP_Param::_singleton static private
Definition at line 612 of file AP_Param.h.
Referenced by AP_Param(), and get_singleton().
_storage
StorageAccess AP_Param::_storage static private
Definition at line 791 of file AP_Param.h.
Referenced by convert_parameter_width(), eeprom_write_check(), find_old_parameter(), load(), load_all(), load_object_from_eeprom(), save_sync(), scan(), setup(), and storage_size().
_storage_bak
StorageAccess AP_Param::_storage_bak static private
Definition at line 792 of file AP_Param.h.
Referenced by eeprom_write_check(), and setup().
_var_info
const AP_Param::Info * AP_Param::_var_info static private
Definition at line 798 of file AP_Param.h.
Referenced by AP_Param(), initialised(), and var_info().
default_list
AP_Param::defaults_list * AP_Param::default_list static private
Definition at line 853 of file AP_Param.h.
Referenced by add_default(), and check_default().
done_all_default_params
bool AP_Param::done_all_default_params static private
Definition at line 662 of file AP_Param.h.
Referenced by load_object_from_eeprom().
k_EEPROM_magic0
const uint8_t AP_Param::k_EEPROM_magic0 = 0x50 static private
Definition at line 829 of file AP_Param.h.
Referenced by erase_all(), and setup().
k_EEPROM_magic1
const uint8_t AP_Param::k_EEPROM_magic1 = 0x41 static private
"AP"
Definition at line 830 of file AP_Param.h.
Referenced by erase_all(), and setup().
k_EEPROM_revision
const uint8_t AP_Param::k_EEPROM_revision = 6 static private
current format revision
Definition at line 831 of file AP_Param.h.
Referenced by erase_all(), and setup().
num_param_overrides
uint16_t AP_Param::num_param_overrides static private
Definition at line 824 of file AP_Param.h.
Referenced by add_default(), configured_in_defaults_file(), get_default_value(), and get_default_value().
num_read_only
uint16_t AP_Param::num_read_only static private
Definition at line 826 of file AP_Param.h.
Referenced by is_read_only().
param_overrides
struct AP_Param::param_override * AP_Param::param_overrides static private
Definition at line 823 of file AP_Param.h.
Referenced by add_default(), configured_in_defaults_file(), get_default_value(), and get_default_value().
param_overrides_len
uint16_t AP_Param::param_overrides_len static private
Definition at line 825 of file AP_Param.h.
registered_save_handler
bool AP_Param::registered_save_handler static private
Definition at line 842 of file AP_Param.h.
Referenced by load_all().
save_queue
ObjectBuffer_TS< AP_Param::param_save > AP_Param::save_queue {30} static private
Definition at line 115 of file AP_Param.h.
Referenced by flush(), save(), and save_io_handler().
sentinal_offset
uint16_t AP_Param::sentinal_offset static private
Definition at line 626 of file AP_Param.h.
Referenced by load_all(), load_object_from_eeprom(), scan(), storage_used(), and write_sentinal().
The documentation for this class was generated from the following files:
libraries/AP_Param/AP_Param.h
libraries/AP_DAL/examples/AP_DAL_Standalone/main.cpp
libraries/AP_Param/AP_Param.cpp