APM:Libraries: AP_OABendyRuler Class Reference
AP_OABendyRuler Class Reference
#include <AP_OABendyRuler.h>
Public Types
enum class OABendyType { OA_BENDY_DISABLED = 0 , OA_BENDY_HORIZONTAL = 1 , OA_BENDY_VERTICAL = 2 }
Public Member Functions
AP_OABendyRuler ()
CLASS_NO_COPY (AP_OABendyRuler)
void set_config (float margin_max)
bool update (const Location &current_loc, const Location &destination, const Vector2f &ground_speed_vec, Location &origin_new, Location &destination_new, OABendyType &bendy_type, bool proximity_only)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
OABendyType get_type () const
bool search_xy_path (const Location &current_loc, const Location &destination, float ground_course_deg, Location &destination_new, float lookahead_step_1_dist, float lookahead_step_2_dist, float bearing_to_dest, float distance_to_dest, bool proximity_only)
bool search_vertical_path (const Location &current_loc, const Location &destination, Location &destination_new, float lookahead_step1_dist, float lookahead_step2_dist, float bearing_to_dest, float distance_to_dest, bool proximity_only)
float calc_avoidance_margin (const Location &start, const Location &end, bool proximity_only) const
bool resist_bearing_change (const Location &destination, const Location &current_loc, bool active, float bearing_test, float lookahead_step1_dist, float margin, Location &prev_dest, float &prev_bearing, float &final_bearing, float &final_margin, bool proximity_only) const
bool calc_margin_from_circular_fence (const Location &start, const Location &end, float &margin) const
bool calc_margin_from_alt_fence (const Location &start, const Location &end, float &margin) const
bool calc_margin_from_inclusion_and_exclusion_polygons (const Location &start, const Location &end, float &margin) const
bool calc_margin_from_inclusion_and_exclusion_circles (const Location &start, const Location &end, float &margin) const
bool calc_margin_from_object_database (const Location &start, const Location &end, float &margin) const
void Write_OABendyRuler (const uint8_t type, const bool active, const float target_yaw, const float target_pitch, const bool resist_chg, const float margin, const Location &final_dest, const Location &oa_dest) const
Private Attributes
float _margin_max
AP_Float _lookahead
AP_Float _bendy_ratio
AP_Int16 _bendy_angle
AP_Int8 _bendy_type
float _current_lookahead
float _bearing_prev
Location _destination_prev
Detailed Description
Definition at line 11 of file AP_OABendyRuler.h.
Member Enumeration Documentation
OABendyType
enum class AP_OABendyRuler::OABendyType strong
Enumerator
OA_BENDY_DISABLED
OA_BENDY_HORIZONTAL
OA_BENDY_VERTICAL
Definition at line 20 of file AP_OABendyRuler.h.
Constructor & Destructor Documentation
AP_OABendyRuler()
AP_OABendyRuler::AP_OABendyRuler ()
Definition at line 75 of file AP_OABendyRuler.cpp.
Member Function Documentation
calc_avoidance_margin()
float AP_OABendyRuler::calc_avoidance_margin (const Location & start, const Location & end, bool proximity_only) const private
Definition at line 416 of file AP_OABendyRuler.cpp.
Referenced by resist_bearing_change(), search_vertical_path(), and search_xy_path().
calc_margin_from_alt_fence()
bool AP_OABendyRuler::calc_margin_from_alt_fence (const Location & start, const Location & end, float & margin) const private
Definition at line 488 of file AP_OABendyRuler.cpp.
Referenced by calc_avoidance_margin().
calc_margin_from_circular_fence()
bool AP_OABendyRuler::calc_margin_from_circular_fence (const Location & start, const Location & end, float & margin) const private
Definition at line 458 of file AP_OABendyRuler.cpp.
Referenced by calc_avoidance_margin().
calc_margin_from_inclusion_and_exclusion_circles()
bool AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_circles (const Location & start, const Location & end, float & margin) const private
Definition at line 594 of file AP_OABendyRuler.cpp.
Referenced by calc_avoidance_margin().
calc_margin_from_inclusion_and_exclusion_polygons()
bool AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_polygons (const Location & start, const Location & end, float & margin) const private
Definition at line 524 of file AP_OABendyRuler.cpp.
Referenced by calc_avoidance_margin().
calc_margin_from_object_database()
bool AP_OABendyRuler::calc_margin_from_object_database (const Location & start, const Location & end, float & margin) const private
Definition at line 674 of file AP_OABendyRuler.cpp.
Referenced by calc_avoidance_margin().
CLASS_NO_COPY()
AP_OABendyRuler::CLASS_NO_COPY (AP_OABendyRuler)
get_type()
AP_OABendyRuler::OABendyType AP_OABendyRuler::get_type () const private
Definition at line 353 of file AP_OABendyRuler.cpp.
Referenced by calc_avoidance_margin(), and update().
resist_bearing_change()
bool AP_OABendyRuler::resist_bearing_change (const Location & destination, const Location & current_loc, bool active, float bearing_test, float lookahead_step1_dist, float margin, Location & prev_dest, float & prev_bearing, float & final_bearing, float & final_margin, bool proximity_only) const private
Definition at line 377 of file AP_OABendyRuler.cpp.
Referenced by search_xy_path().
search_vertical_path()
bool AP_OABendyRuler::search_vertical_path (const Location & current_loc, const Location & destination, Location & destination_new, float lookahead_step1_dist, float lookahead_step2_dist, float bearing_to_dest, float distance_to_dest, bool proximity_only) private
Definition at line 246 of file AP_OABendyRuler.cpp.
Referenced by update().
search_xy_path()
bool AP_OABendyRuler::search_xy_path (const Location & current_loc, const Location & destination, float ground_course_deg, Location & destination_new, float lookahead_step_1_dist, float lookahead_step_2_dist, float bearing_to_dest, float distance_to_dest, bool proximity_only) private
Definition at line 137 of file AP_OABendyRuler.cpp.
Referenced by update().
set_config()
void AP_OABendyRuler::set_config (float margin_max) inline
Definition at line 18 of file AP_OABendyRuler.h.
Referenced by AP_OAPathPlanner::avoidance_thread().
update()
bool AP_OABendyRuler::update (const Location & current_loc, const Location & destination, const Vector2f & ground_speed_vec, Location & origin_new, Location & destination_new, OABendyType & bendy_type, bool proximity_only)
Definition at line 84 of file AP_OABendyRuler.cpp.
Referenced by AP_OAPathPlanner::avoidance_thread().
Write_OABendyRuler()
void AP_OABendyRuler::Write_OABendyRuler (const uint8_t type, const bool active, const float target_yaw, const float target_pitch, const bool resist_chg, const float margin, const Location & final_dest, const Location & oa_dest) const inline private
Definition at line 74 of file AP_OABendyRuler.h.
Referenced by search_vertical_path(), and search_xy_path().
Member Data Documentation
_bearing_prev
float AP_OABendyRuler::_bearing_prev private
Definition at line 88 of file AP_OABendyRuler.h.
Referenced by AP_OABendyRuler(), and search_xy_path().
_bendy_angle
AP_Int16 AP_OABendyRuler::_bendy_angle private
Definition at line 83 of file AP_OABendyRuler.h.
Referenced by resist_bearing_change().
_bendy_ratio
AP_Float AP_OABendyRuler::_bendy_ratio private
Definition at line 82 of file AP_OABendyRuler.h.
Referenced by resist_bearing_change().
_bendy_type
AP_Int8 AP_OABendyRuler::_bendy_type private
Definition at line 84 of file AP_OABendyRuler.h.
Referenced by get_type().
_current_lookahead
float AP_OABendyRuler::_current_lookahead private
Definition at line 87 of file AP_OABendyRuler.h.
Referenced by search_vertical_path(), search_xy_path(), and update().
_destination_prev
Location AP_OABendyRuler::_destination_prev private
Definition at line 89 of file AP_OABendyRuler.h.
Referenced by search_xy_path().
_lookahead
AP_Float AP_OABendyRuler::_lookahead private
Definition at line 81 of file AP_OABendyRuler.h.
Referenced by search_vertical_path(), search_xy_path(), and update().
_margin_max
float AP_OABendyRuler::_margin_max private
Definition at line 78 of file AP_OABendyRuler.h.
Referenced by search_vertical_path(), search_xy_path(), and set_config().
var_info
const AP_Param::GroupInfo AP_OABendyRuler::var_info static
Definition at line 38 of file AP_OABendyRuler.h.
Referenced by AP_OAPathPlanner::init().
The documentation for this class was generated from the following files:
libraries/AC_Avoidance/AP_OABendyRuler.h
libraries/AC_Avoidance/AP_OABendyRuler.cpp