APM:Libraries: SITL::MS5XXX Class Reference
SITL::MS5XXX Class Reference abstract
#include <SIM_MS5XXX.h>
Public Member Functions
MS5XXX ()
Public Member Functions inherited from SITL::I2CDevice
virtual void init ()
Protected Member Functions
int rdwr (I2C::i2c_rdwr_ioctl_data *&data) override
void update (const class Aircraft &aircraft) override
Private Types
enum class Command : uint8_t {
RESET = 0x1E , READ_CONVERSION = 0x00 , READ_C0 = 0xa0 , READ_C1 = 0xa2 ,
READ_C2 = 0xa4 , READ_C3 = 0xa6 , READ_C4 = 0xa8 , READ_C5 = 0xaa ,
READ_C6 = 0xac , READ_CRC = 0xae , CONVERT_D2_OSR_1024 = 0x54 , CONVERT_D1_OSR_1024 = 0x44
}
enum class State : uint8_t {
COLD = 5 , COLD_WAIT = 6 , UNINITIALISED = 7 , RUNNING = 17 ,
RESET_START = 27 , RESET_WAIT = 28 , CONVERSION_D1_START = 37 , CONVERSION_D1_WAIT = 38 ,
CONVERSION_D2_START = 47 , CONVERSION_D2_WAIT = 48
}
Private Member Functions
void reset ()
virtual void load_prom (uint16_t *loaded_prom, uint8_t len) const =0
virtual void convert (float P_Pa, float Temp_C, uint32_t &D1, uint32_t &D2)=0
virtual void convert_forward (int32_t D1, int32_t D2, float &P_Pa, float &Temp_C)=0
virtual void get_pressure_temperature_readings (float &P_Pa, float &Temp_C)=0
virtual void check_conversion_accuracy (float P_Pa, float Temp_C, uint32_t D1, uint32_t D2)=0
void convert_D1 ()
void convert_D2 ()
Private Attributes
State state = State::COLD
uint32_t command_start_us
uint8_t convert_out [3]
bool prom_loaded = false
uint16_t loaded_prom [128/16]
uint16_t conversion_time_osr_1024_us = 2280
Detailed Description
Definition at line 9 of file SIM_MS5XXX.h.
Member Enumeration Documentation
Command
enum class SITL::MS5XXX::Command : uint8_t strong private
Enumerator
RESET
READ_CONVERSION
READ_C0
READ_C1
READ_C2
READ_C3
READ_C4
READ_C5
READ_C6
READ_CRC
CONVERT_D2_OSR_1024
CONVERT_D1_OSR_1024
Definition at line 28 of file SIM_MS5XXX.h.
State
enum class SITL::MS5XXX::State : uint8_t strong private
Enumerator
COLD
COLD_WAIT
UNINITIALISED
RUNNING
RESET_START
RESET_WAIT
CONVERSION_D1_START
CONVERSION_D1_WAIT
CONVERSION_D2_START
CONVERSION_D2_WAIT
Definition at line 48 of file SIM_MS5XXX.h.
Constructor & Destructor Documentation
MS5XXX()
MS5XXX::MS5XXX ()
Definition at line 12 of file SIM_MS5XXX.cpp.
Member Function Documentation
check_conversion_accuracy()
virtual void SITL::MS5XXX::check_conversion_accuracy (float P_Pa, float Temp_C, uint32_t D1, uint32_t D2) private pure virtual
Implemented in SITL::MS5525, and SITL::MS5611.
Referenced by convert_D1().
convert()
virtual void SITL::MS5XXX::convert (float P_Pa, float Temp_C, uint32_t & D1, uint32_t & D2) private pure virtual
Implemented in SITL::MS5525, and SITL::MS5611.
Referenced by convert_D1(), and convert_D2().
convert_D1()
void MS5XXX::convert_D1 () private
Definition at line 24 of file SIM_MS5XXX.cpp.
Referenced by update().
convert_D2()
void MS5XXX::convert_D2 () private
Definition at line 50 of file SIM_MS5XXX.cpp.
Referenced by update().
convert_forward()
virtual void SITL::MS5XXX::convert_forward (int32_t D1, int32_t D2, float & P_Pa, float & Temp_C) private pure virtual
Implemented in SITL::MS5525, and SITL::MS5611.
get_pressure_temperature_readings()
virtual void SITL::MS5XXX::get_pressure_temperature_readings (float & P_Pa, float & Temp_C) private pure virtual
Implemented in SITL::MS5525, and SITL::MS5611.
Referenced by convert_D1(), and convert_D2().
load_prom()
virtual void SITL::MS5XXX::load_prom (uint16_t * loaded_prom, uint8_t len) const private pure virtual
Implemented in SITL::MS5525, and SITL::MS5611.
Referenced by reset().
rdwr()
int MS5XXX::rdwr (I2C::i2c_rdwr_ioctl_data *& data) override protected virtual
Implements SITL::I2CDevice.
Definition at line 149 of file SIM_MS5XXX.cpp.
reset()
void MS5XXX::reset () private
Definition at line 17 of file SIM_MS5XXX.cpp.
Referenced by update().
update()
void MS5XXX::update (const class Aircraft & aircraft) override protected virtual
Reimplemented from SITL::I2CDevice.
Definition at line 74 of file SIM_MS5XXX.cpp.
Member Data Documentation
command_start_us
uint32_t SITL::MS5XXX::command_start_us private
Definition at line 68 of file SIM_MS5XXX.h.
Referenced by update().
conversion_time_osr_1024_us
uint16_t SITL::MS5XXX::conversion_time_osr_1024_us = 2280 private
Definition at line 76 of file SIM_MS5XXX.h.
Referenced by update().
convert_out
uint8_t SITL::MS5XXX::convert_out[3] private
Definition at line 70 of file SIM_MS5XXX.h.
Referenced by convert_D1(), convert_D2(), rdwr(), and update().
loaded_prom
uint16_t SITL::MS5XXX::loaded_prom[128/16] private
Definition at line 73 of file SIM_MS5XXX.h.
Referenced by rdwr(), and reset().
prom_loaded
bool SITL::MS5XXX::prom_loaded = false private
Definition at line 72 of file SIM_MS5XXX.h.
Referenced by reset(), and update().
state
State SITL::MS5XXX::state = State::COLD private
Definition at line 66 of file SIM_MS5XXX.h.
Referenced by rdwr(), and update().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_MS5XXX.h
libraries/SITL/SIM_MS5XXX.cpp