APM:Libraries: AP_Baro_LPS2XH Class Reference
AP_Baro_LPS2XH Class Reference
#include <AP_Baro_LPS2XH.h>
Public Types
enum LPS2XH_TYPE { BARO_LPS22H = 0 , BARO_LPS25H = 1 }
Public Types inherited from AP_Baro_Backend
enum DevTypes {
DEVTYPE_BARO_SITL = 0x01 , DEVTYPE_BARO_BMP085 = 0x02 , DEVTYPE_BARO_BMP280 = 0x03 , DEVTYPE_BARO_BMP388 = 0x04 ,
DEVTYPE_BARO_DPS280 = 0x05 , DEVTYPE_BARO_DPS310 = 0x06 , DEVTYPE_BARO_FBM320 = 0x07 , DEVTYPE_BARO_ICM20789 = 0x08 ,
DEVTYPE_BARO_KELLERLD = 0x09 , DEVTYPE_BARO_LPS2XH = 0x0A , DEVTYPE_BARO_MS5611 = 0x0B , DEVTYPE_BARO_SPL06 = 0x0C ,
DEVTYPE_BARO_UAVCAN = 0x0D , DEVTYPE_BARO_MSP = 0x0E , DEVTYPE_BARO_ICP101XX = 0x0F , DEVTYPE_BARO_ICP201XX = 0x10 ,
DEVTYPE_BARO_MS5607 = 0x11 , DEVTYPE_BARO_MS5837 = 0x12 , DEVTYPE_BARO_MS5637 = 0x13 , DEVTYPE_BARO_BMP390 = 0x14
}
Public Member Functions
AP_Baro_LPS2XH (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
void update () override
Public Member Functions inherited from AP_Baro_Backend
AP_Baro_Backend (AP_Baro &baro)
virtual ~AP_Baro_Backend (void)
virtual void accumulate (void)
void backend_update (uint8_t instance)
bool pressure_ok (float press)
uint32_t get_error_count () const
Static Public Member Functions
static AP_Baro_Backend * probe (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
static AP_Baro_Backend * probe_InvensenseIMU (AP_Baro &baro, AP_HAL::OwnPtr< AP_HAL::Device > dev, uint8_t imu_address)
Private Member Functions
virtual ~AP_Baro_LPS2XH (void)
bool _init (void)
void _timer (void)
void _update_temperature (void)
void _update_pressure (void)
bool _imu_i2c_init (uint8_t imu_address)
bool _check_whoami (void)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _dev
uint8_t _instance
float _pressure_sum
uint32_t _pressure_count
float _temperature
uint32_t CallTime = 0
enum LPS2XH_TYPE _lps2xh_type
Additional Inherited Members
Protected Member Functions inherited from AP_Baro_Backend
void _copy_to_frontend (uint8_t instance, float pressure, float temperature)
virtual void update_healthy_flag (uint8_t instance)
void set_bus_id (uint8_t instance, uint32_t id)
Protected Attributes inherited from AP_Baro_Backend
AP_Baro & _frontend
HAL_Semaphore _sem
float _mean_pressure
uint32_t _error_count
Detailed Description
Definition at line 19 of file AP_Baro_LPS2XH.h.
Member Enumeration Documentation
LPS2XH_TYPE
enum AP_Baro_LPS2XH::LPS2XH_TYPE
Enumerator
BARO_LPS22H
BARO_LPS25H
Definition at line 22 of file AP_Baro_LPS2XH.h.
Constructor & Destructor Documentation
AP_Baro_LPS2XH()
AP_Baro_LPS2XH::AP_Baro_LPS2XH (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev)
Definition at line 59 of file AP_Baro_LPS2XH.cpp.
Referenced by probe(), and probe_InvensenseIMU().
~AP_Baro_LPS2XH()
virtual AP_Baro_LPS2XH::~AP_Baro_LPS2XH (void) inline private virtual
Definition at line 36 of file AP_Baro_LPS2XH.h.
Member Function Documentation
_check_whoami()
bool AP_Baro_LPS2XH::_check_whoami (void) private
Definition at line 195 of file AP_Baro_LPS2XH.cpp.
Referenced by _init().
_imu_i2c_init()
bool AP_Baro_LPS2XH::_imu_i2c_init (uint8_t imu_address) private
Definition at line 109 of file AP_Baro_LPS2XH.cpp.
Referenced by probe_InvensenseIMU().
_init()
bool AP_Baro_LPS2XH::_init (void) private
Definition at line 139 of file AP_Baro_LPS2XH.cpp.
Referenced by probe(), and probe_InvensenseIMU().
_timer()
void AP_Baro_LPS2XH::_timer (void) private
Definition at line 216 of file AP_Baro_LPS2XH.cpp.
Referenced by _init().
_update_pressure()
void AP_Baro_LPS2XH::_update_pressure (void) private
Definition at line 267 of file AP_Baro_LPS2XH.cpp.
Referenced by _timer().
_update_temperature()
void AP_Baro_LPS2XH::_update_temperature (void) private
Definition at line 247 of file AP_Baro_LPS2XH.cpp.
Referenced by _timer().
probe()
AP_Baro_Backend * AP_Baro_LPS2XH::probe (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev) static
Definition at line 65 of file AP_Baro_LPS2XH.cpp.
Referenced by AP_Baro::_probe_i2c_barometers().
probe_InvensenseIMU()
AP_Baro_Backend * AP_Baro_LPS2XH::probe_InvensenseIMU (AP_Baro & baro, AP_HAL::OwnPtr< AP_HAL::Device > dev, uint8_t imu_address) static
Definition at line 81 of file AP_Baro_LPS2XH.cpp.
Referenced by AP_Baro::init().
update()
void AP_Baro_LPS2XH::update (void) override virtual
Implements AP_Baro_Backend.
Definition at line 234 of file AP_Baro_LPS2XH.cpp.
Member Data Documentation
_dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_Baro_LPS2XH::_dev private
Definition at line 46 of file AP_Baro_LPS2XH.h.
Referenced by _check_whoami(), _imu_i2c_init(), _init(), _timer(), _update_pressure(), and _update_temperature().
_instance
uint8_t AP_Baro_LPS2XH::_instance private
Definition at line 48 of file AP_Baro_LPS2XH.h.
Referenced by _init(), and update().
_lps2xh_type
enum LPS2XH_TYPE AP_Baro_LPS2XH::_lps2xh_type private
Definition at line 55 of file AP_Baro_LPS2XH.h.
Referenced by _check_whoami(), _init(), and _update_temperature().
_pressure_count
uint32_t AP_Baro_LPS2XH::_pressure_count private
Definition at line 50 of file AP_Baro_LPS2XH.h.
Referenced by _update_pressure(), and update().
_pressure_sum
float AP_Baro_LPS2XH::_pressure_sum private
Definition at line 49 of file AP_Baro_LPS2XH.h.
Referenced by _update_pressure(), and update().
_temperature
float AP_Baro_LPS2XH::_temperature private
Definition at line 51 of file AP_Baro_LPS2XH.h.
Referenced by _update_temperature(), and update().
CallTime
uint32_t AP_Baro_LPS2XH::CallTime = 0 private
Definition at line 53 of file AP_Baro_LPS2XH.h.
Referenced by _init().
The documentation for this class was generated from the following files:
libraries/AP_Baro/AP_Baro_LPS2XH.h
libraries/AP_Baro/AP_Baro_LPS2XH.cpp