APM:Libraries: SITL::I2CRegisters_8Bit Class Reference
SITL::I2CRegisters_8Bit Class Reference
#include <SIM_I2CDevice.h>
Public Member Functions
int rdwr (I2C::i2c_rdwr_ioctl_data *&data) override
void set_register (uint8_t reg, uint8_t value)
void set_register (uint8_t reg, int8_t value)
uint8_t get_register (uint8_t num)
void assert_register_value (uint8_t reg, uint8_t value)
Protected Member Functions
virtual void rdwr_store_register_value (uint8_t reg, uint8_t value)
Protected Member Functions inherited from SITL::I2CRegisters
void add_register (const char *name, uint8_t reg, RegMode mode)
void set_debug (bool value)
bool get_debug () const
Protected Attributes
uint8_t byte [256]
Protected Attributes inherited from SITL::I2CRegisters
const char * regname [256]
Bitmask< 256 > writable_registers
Bitmask< 256 > readable_registers
Additional Inherited Members
Public Types inherited from SITL::I2CRegisters
enum class RegMode { RDONLY = 11 , WRONLY = 22 , RDWR = 33 }
Detailed Description
Definition at line 79 of file SIM_I2CDevice.h.
Member Function Documentation
assert_register_value()
void SITL::I2CRegisters_8Bit::assert_register_value (uint8_t reg, uint8_t value)
Definition at line 160 of file SIM_I2CDevice.cpp.
get_register()
uint8_t SITL::I2CRegisters_8Bit::get_register (uint8_t num) inline
Definition at line 85 of file SIM_I2CDevice.h.
Referenced by SITL::LM2755::update(), and SITL::ToshibaLED::update().
rdwr()
int SITL::I2CRegisters_8Bit::rdwr (I2C::i2c_rdwr_ioctl_data *& data) override virtual
Implements SITL::I2CRegisters.
Reimplemented in SITL::InvensenseV3, SITL::IS31FL3195, SITL::LM2755, SITL::LP5562, and SITL::ToshibaLED.
Definition at line 112 of file SIM_I2CDevice.cpp.
Referenced by SITL::InvensenseV3::rdwr(), SITL::IS31FL3195::rdwr(), SITL::LM2755::rdwr(), SITL::LP5562::rdwr(), and SITL::ToshibaLED::rdwr().
rdwr_store_register_value()
virtual void SITL::I2CRegisters_8Bit::rdwr_store_register_value (uint8_t reg, uint8_t value) inline protected virtual
Reimplemented in SITL::IS31FL3195.
Definition at line 95 of file SIM_I2CDevice.h.
Referenced by SITL::IS31FL3195::rdwr_store_register_value().
set_register() [1/2]
void SITL::I2CRegisters_8Bit::set_register (uint8_t reg, int8_t value)
Definition at line 103 of file SIM_I2CDevice.cpp.
set_register() [2/2]
void SITL::I2CRegisters_8Bit::set_register (uint8_t reg, uint8_t value)
Definition at line 94 of file SIM_I2CDevice.cpp.
Referenced by SITL::ICM40609::init(), and SITL::LM2755::init().
Member Data Documentation
byte
uint8_t SITL::I2CRegisters_8Bit::byte[256] protected
Definition at line 99 of file SIM_I2CDevice.h.
Referenced by SITL::LM2755::update().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_I2CDevice.h
libraries/SITL/SIM_I2CDevice.cpp