APM:Libraries: AP_BoardConfig Class Reference
AP_BoardConfig Class Reference
#include <AP_BoardConfig.h>
Public Types
enum px4_board_type {
BOARD_TYPE_UNKNOWN = -1 , PX4_BOARD_AUTO = 0 , PX4_BOARD_PX4V1 = 1 , PX4_BOARD_PIXHAWK = 2 ,
PX4_BOARD_PIXHAWK2 = 3 , PX4_BOARD_PIXRACER = 4 , PX4_BOARD_PHMINI = 5 , PX4_BOARD_PH2SLIM = 6 ,
PX4_BOARD_AEROFC = 13 , PX4_BOARD_PIXHAWK_PRO = 14 , PX4_BOARD_AUAV21 = 20 , PX4_BOARD_PCNC1 = 21 ,
PX4_BOARD_MINDPXV2 = 22 , PX4_BOARD_SP01 = 23 , PX4_BOARD_FMUV5 = 24 , VRX_BOARD_BRAIN51 = 30 ,
VRX_BOARD_BRAIN52 = 32 , VRX_BOARD_BRAIN52E = 33 , VRX_BOARD_UBRAIN51 = 34 , VRX_BOARD_UBRAIN52 = 35 ,
VRX_BOARD_CORE10 = 36 , VRX_BOARD_BRAIN54 = 38 , PX4_BOARD_FMUV6 = 39 , FMUV6_BOARD_HOLYBRO_6X = 40 ,
FMUV6_BOARD_CUAV_6X = 41 , FMUV6_BOARD_HOLYBRO_6X_REV6 = 42 , FMUV6_BOARD_HOLYBRO_6X_45686 = 43 , PX4_BOARD_OLDDRIVERS = 100
}
enum board_safety_button_option { BOARD_SAFETY_OPTION_BUTTON_ACTIVE_SAFETY_OFF = (1 << 0) , BOARD_SAFETY_OPTION_BUTTON_ACTIVE_SAFETY_ON = (1 << 1) , BOARD_SAFETY_OPTION_BUTTON_ACTIVE_ARMED = (1 << 2) , BOARD_SAFETY_OPTION_SAFETY_ON_DISARM = (1 << 3) }
enum board_options {
BOARD_OPTION_WATCHDOG = (1 << 0) , DISABLE_FTP = (1<<1) , ALLOW_SET_INTERNAL_PARM = (1<<2) , BOARD_OPTION_DEBUG_ENABLE = (1<<3) ,
UNLOCK_FLASH = (1<<4) , WRITE_PROTECT_FLASH = (1<<5) , WRITE_PROTECT_BOOTLOADER = (1<<6) , SKIP_BOARD_VALIDATION = (1<<7) ,
DISABLE_ARMING_GPIO = (1<<8)
}
Public Member Functions
AP_BoardConfig ()
CLASS_NO_COPY (AP_BoardConfig)
void init (void)
void init_safety (void)
void set_default_safety_ignore_mask (uint32_t mask)
uint8_t get_alt_config (void)
uint16_t get_safety_button_options (void) const
uint16_t get_safety_mask (void) const
uint32_t get_serial_number () const
bool safety_button_handle_pressed (uint8_t press_count)
Static Public Member Functions
static AP_BoardConfig * get_singleton (void)
static void config_error (const char *reason,...) FMT_PRINTF(1
static void allocation_error (const char *reason,...) FMT_PRINTF(1
static bool in_config_error (void)
static enum px4_board_type get_board_type (void)
static uint8_t io_enabled (void)
static bool io_dshot (void)
static uint8_t get_sdcard_slowdown (void)
static bool arming_gpio_disabled (void)
static bool ftp_disabled (void)
static bool watchdog_enabled (void)
static bool unlock_flash (void)
static bool protect_flash (void)
static bool protect_bootloader (void)
static bool allow_set_internal_parameters (void)
Public Attributes
static void NORETURN
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void board_init_safety (void)
void board_init_debug (void)
void board_setup_uart (void)
void board_setup_sbus (void)
void board_setup (void)
Static Private Member Functions
static void throw_error (const char *err_str, const char *fmt, va_list arg) NORETURN
Private Attributes
AP_Int32 vehicleSerialNumber
struct {
AP_Int8 safety_enable
AP_Int16 safety_option
AP_Int32 ignore_safety_channels
AP_Int8 ser_rtscts [6]
AP_Int8 sbus_out_rate
AP_Int8 board_type
AP_Int8 io_enable
AP_Int8 io_dshot
} state
AP_Int8 _pwm_volt_sel
AP_Int8 _sdcard_slowdown
AP_Int16 _boot_delay_ms
AP_Int32 _options
AP_Int8 _alt_config
Static Private Attributes
static AP_BoardConfig * _singleton
static bool _in_error_loop
Detailed Description
Definition at line 15 of file AP_BoardConfig.h.
Member Enumeration Documentation
board_options
enum AP_BoardConfig::board_options
Enumerator
BOARD_OPTION_WATCHDOG
DISABLE_FTP
ALLOW_SET_INTERNAL_PARM
BOARD_OPTION_DEBUG_ENABLE
UNLOCK_FLASH
WRITE_PROTECT_FLASH
WRITE_PROTECT_BOOTLOADER
SKIP_BOARD_VALIDATION
DISABLE_ARMING_GPIO
Definition at line 151 of file AP_BoardConfig.h.
board_safety_button_option
enum AP_BoardConfig::board_safety_button_option
Enumerator
BOARD_SAFETY_OPTION_BUTTON_ACTIVE_SAFETY_OFF
BOARD_SAFETY_OPTION_BUTTON_ACTIVE_SAFETY_ON
BOARD_SAFETY_OPTION_BUTTON_ACTIVE_ARMED
BOARD_SAFETY_OPTION_SAFETY_ON_DISARM
Definition at line 110 of file AP_BoardConfig.h.
px4_board_type
enum AP_BoardConfig::px4_board_type
Enumerator
BOARD_TYPE_UNKNOWN
PX4_BOARD_AUTO
PX4_BOARD_PX4V1
PX4_BOARD_PIXHAWK
PX4_BOARD_PIXHAWK2
PX4_BOARD_PIXRACER
PX4_BOARD_PHMINI
PX4_BOARD_PH2SLIM
PX4_BOARD_AEROFC
PX4_BOARD_PIXHAWK_PRO
PX4_BOARD_AUAV21
PX4_BOARD_PCNC1
PX4_BOARD_MINDPXV2
PX4_BOARD_SP01
PX4_BOARD_FMUV5
VRX_BOARD_BRAIN51
VRX_BOARD_BRAIN52
VRX_BOARD_BRAIN52E
VRX_BOARD_UBRAIN51
VRX_BOARD_UBRAIN52
VRX_BOARD_CORE10
VRX_BOARD_BRAIN54
PX4_BOARD_FMUV6
FMUV6_BOARD_HOLYBRO_6X
FMUV6_BOARD_CUAV_6X
FMUV6_BOARD_HOLYBRO_6X_REV6
FMUV6_BOARD_HOLYBRO_6X_45686
PX4_BOARD_OLDDRIVERS
Definition at line 44 of file AP_BoardConfig.h.
Constructor & Destructor Documentation
AP_BoardConfig()
AP_BoardConfig::AP_BoardConfig ()
Definition at line 97 of file AP_BoardConfig.cpp.
Member Function Documentation
allocation_error()
void AP_BoardConfig::allocation_error (const char * reason, ...) static
Definition at line 473 of file AP_BoardConfig.cpp.
Referenced by AP_DAL_RangeFinder::AP_DAL_RangeFinder(), AP_CustomRotations::init(), AP_Logger::init(), and AP_DAL::init_sensors().
allow_set_internal_parameters()
static bool AP_BoardConfig::allow_set_internal_parameters (void) inline static
Definition at line 198 of file AP_BoardConfig.h.
Referenced by AP_Frsky_MAVliteMsgHandler::handle_param_set(), and GCS_MAVLINK::handle_param_set().
arming_gpio_disabled()
static bool AP_BoardConfig::arming_gpio_disabled (void) inline static
Definition at line 164 of file AP_BoardConfig.h.
board_init_debug()
void AP_BoardConfig::board_init_debug (void) private
Definition at line 55 of file board_drivers.cpp.
Referenced by init_safety().
board_init_safety()
void AP_BoardConfig::board_init_safety (void) private
Definition at line 34 of file board_drivers.cpp.
Referenced by init_safety().
board_setup()
void AP_BoardConfig::board_setup (void) private
Definition at line 457 of file board_drivers.cpp.
Referenced by init().
board_setup_sbus()
void AP_BoardConfig::board_setup_sbus (void) private
Definition at line 424 of file board_drivers.cpp.
Referenced by board_setup().
board_setup_uart()
void AP_BoardConfig::board_setup_uart (void) private
Definition at line 390 of file board_drivers.cpp.
Referenced by board_setup().
CLASS_NO_COPY()
AP_BoardConfig::CLASS_NO_COPY (AP_BoardConfig)
config_error()
void AP_BoardConfig::config_error (const char * reason, ...) static
Definition at line 483 of file AP_BoardConfig.cpp.
Referenced by AP_Logger::assert_same_fmt_for_name(), AP_Baro::calibrate(), AP_InertialSensor::detect_backends(), AP_Logger::init(), AP_InertialSensor::init(), AP_AHRS::init(), AP_Baro::init(), RC_Channel::init_aux_function(), AP_Logger::msg_fmt_for_name(), AP_Param::set_defaults_from_table(), and AP_Logger::validate_structures().
ftp_disabled()
static bool AP_BoardConfig::ftp_disabled (void) inline static
Definition at line 173 of file AP_BoardConfig.h.
Referenced by GCS_MAVLINK::capabilities(), and GCS_MAVLINK::ftp_init().
get_alt_config()
uint8_t AP_BoardConfig::get_alt_config (void) inline
Definition at line 106 of file AP_BoardConfig.h.
get_board_type()
static enum px4_board_type AP_BoardConfig::get_board_type (void) inline static
Definition at line 78 of file AP_BoardConfig.h.
Referenced by Compass::_detect_backends(), Compass::_probe_external_i2c_compasses(), AP_Baro::_probe_i2c_barometers(), AP_InertialSensor::detect_backends(), AP_Baro::init(), Compass::probe_i2c_spi_compasses(), and AP_OpticalFlow_PX4Flow::scan_buses().
get_safety_button_options()
uint16_t AP_BoardConfig::get_safety_button_options (void) const inline
Definition at line 118 of file AP_BoardConfig.h.
Referenced by AP_Arming::disarm(), and safety_button_handle_pressed().
get_safety_mask()
uint16_t AP_BoardConfig::get_safety_mask (void) const inline
Definition at line 123 of file AP_BoardConfig.h.
Referenced by ESP32::RCOutput::safety_update(), and HALSITL::RCOutput::write().
get_sdcard_slowdown()
static uint8_t AP_BoardConfig::get_sdcard_slowdown (void) inline static
Definition at line 146 of file AP_BoardConfig.h.
Referenced by sdcard_init(), and AP_Vehicle::setup().
get_serial_number()
uint32_t AP_BoardConfig::get_serial_number () const inline
Definition at line 127 of file AP_BoardConfig.h.
get_singleton()
static AP_BoardConfig * AP_BoardConfig::get_singleton (void) inline static
Definition at line 23 of file AP_BoardConfig.h.
Referenced by AP::boardConfig(), AP_Arming::disarm(), ESP32::RCOutput::safety_update(), and HALSITL::RCOutput::write().
in_config_error()
static bool AP_BoardConfig::in_config_error (void) inline static
Definition at line 40 of file AP_BoardConfig.h.
Referenced by GCS::out_of_time(), and AP_Vehicle::scheduler_delay_callback().
init()
void AP_BoardConfig::init (void)
Definition at line 376 of file AP_BoardConfig.cpp.
Referenced by DummyVehicle::init(), setup(), setup(), SchedTest::setup(), setup(), and AP_Vehicle::setup().
init_safety()
void AP_BoardConfig::init_safety (void)
Definition at line 421 of file AP_BoardConfig.cpp.
Referenced by AP_Vehicle::loop().
io_dshot()
static bool AP_BoardConfig::io_dshot (void) inline static
Definition at line 97 of file AP_BoardConfig.h.
io_enabled()
static uint8_t AP_BoardConfig::io_enabled (void) inline static
Definition at line 89 of file AP_BoardConfig.h.
Referenced by ChibiOS::RCInput::_timer_tick(), ChibiOS::GPIO::channel(), ChibiOS::GPIO::init(), HALSITL::RCOutput::init(), io_dshot(), ChibiOS::GPIO::pin_to_servo_channel(), ChibiOS::RCInput::rc_bind(), ChibiOS::Scheduler::reboot(), GCS_MAVLINK::send_banner(), AP_Arming::servo_checks(), ChibiOS::GPIO::toggle(), ChibiOS::GPIO::valid_pin(), and ChibiOS::GPIO::write().
protect_bootloader()
static bool AP_BoardConfig::protect_bootloader (void) inline static
Definition at line 193 of file AP_BoardConfig.h.
Referenced by main_loop().
protect_flash()
static bool AP_BoardConfig::protect_flash (void) inline static
Definition at line 188 of file AP_BoardConfig.h.
Referenced by main_loop().
safety_button_handle_pressed()
bool AP_BoardConfig::safety_button_handle_pressed (uint8_t press_count)
Definition at line 497 of file AP_BoardConfig.cpp.
Referenced by ESP32::RCOutput::safety_update().
set_default_safety_ignore_mask()
void AP_BoardConfig::set_default_safety_ignore_mask (uint32_t mask)
Definition at line 416 of file AP_BoardConfig.cpp.
throw_error()
void AP_BoardConfig::throw_error (const char * err_str, const char * fmt, va_list arg) static private
Definition at line 432 of file AP_BoardConfig.cpp.
Referenced by allocation_error(), and config_error().
unlock_flash()
static bool AP_BoardConfig::unlock_flash (void) inline static
Definition at line 183 of file AP_BoardConfig.h.
Referenced by main_loop().
watchdog_enabled()
static bool AP_BoardConfig::watchdog_enabled (void) inline static
Definition at line 178 of file AP_BoardConfig.h.
Referenced by ChibiOS::Scheduler::_monitor_thread(), main_loop(), HAL_SITL::run(), and save_fault_watchdog().
Member Data Documentation
_alt_config
AP_Int8 AP_BoardConfig::_alt_config private
Definition at line 317 of file AP_BoardConfig.h.
Referenced by get_alt_config().
_boot_delay_ms
AP_Int16 AP_BoardConfig::_boot_delay_ms private
Definition at line 313 of file AP_BoardConfig.h.
Referenced by init().
_in_error_loop
bool AP_BoardConfig::_in_error_loop static private
Definition at line 273 of file AP_BoardConfig.h.
Referenced by in_config_error(), and throw_error().
_options
AP_Int32 AP_BoardConfig::_options private
Definition at line 315 of file AP_BoardConfig.h.
Referenced by allow_set_internal_parameters(), arming_gpio_disabled(), board_init_debug(), ftp_disabled(), protect_bootloader(), protect_flash(), unlock_flash(), and watchdog_enabled().
_pwm_volt_sel
AP_Int8 AP_BoardConfig::_pwm_volt_sel private
Definition at line 307 of file AP_BoardConfig.h.
Referenced by board_setup().
_sdcard_slowdown
AP_Int8 AP_BoardConfig::_sdcard_slowdown private
Definition at line 310 of file AP_BoardConfig.h.
Referenced by get_sdcard_slowdown(), and init().
_singleton
AP_BoardConfig * AP_BoardConfig::_singleton static private
Definition at line 227 of file AP_BoardConfig.h.
Referenced by allow_set_internal_parameters(), arming_gpio_disabled(), ftp_disabled(), get_sdcard_slowdown(), get_singleton(), io_dshot(), io_enabled(), protect_bootloader(), protect_flash(), unlock_flash(), and watchdog_enabled().
board_type
AP_Int8 AP_BoardConfig::board_type
Definition at line 239 of file AP_BoardConfig.h.
ignore_safety_channels
AP_Int32 AP_BoardConfig::ignore_safety_channels
Definition at line 234 of file AP_BoardConfig.h.
io_dshot
AP_Int8 AP_BoardConfig::io_dshot
Definition at line 241 of file AP_BoardConfig.h.
Referenced by HALSITL::RCOutput::init(), and io_dshot().
io_enable
AP_Int8 AP_BoardConfig::io_enable
Definition at line 240 of file AP_BoardConfig.h.
Referenced by io_enabled().
NORETURN
static void AP_BoardConfig::NORETURN
Definition at line 33 of file AP_BoardConfig.h.
safety_enable
AP_Int8 AP_BoardConfig::safety_enable
Definition at line 232 of file AP_BoardConfig.h.
safety_option
AP_Int16 AP_BoardConfig::safety_option
Definition at line 233 of file AP_BoardConfig.h.
sbus_out_rate
AP_Int8 AP_BoardConfig::sbus_out_rate
Definition at line 237 of file AP_BoardConfig.h.
ser_rtscts
AP_Int8 AP_BoardConfig::ser_rtscts[6]
Definition at line 236 of file AP_BoardConfig.h.
[struct]
struct { ... } AP_BoardConfig::state
Referenced by board_init_safety(), board_setup_sbus(), board_setup_uart(), get_safety_button_options(), get_safety_mask(), io_dshot(), io_enabled(), and set_default_safety_ignore_mask().
var_info
const AP_Param::GroupInfo AP_BoardConfig::var_info static
Definition at line 109 of file AP_BoardConfig.h.
vehicleSerialNumber
AP_Int32 AP_BoardConfig::vehicleSerialNumber private
Definition at line 229 of file AP_BoardConfig.h.
Referenced by get_serial_number(), and init().
The documentation for this class was generated from the following files:
libraries/AP_BoardConfig/AP_BoardConfig.h
libraries/AP_BoardConfig/AP_BoardConfig.cpp
libraries/AP_BoardConfig/board_drivers.cpp