APM:Libraries: AR_AttitudeControl Class Reference
AR_AttitudeControl Class Reference
#include <AR_AttitudeControl.h>
Public Member Functions
AR_AttitudeControl ()
CLASS_NO_COPY (AR_AttitudeControl)
float get_steering_out_lat_accel (float desired_accel, bool motor_limit_left, bool motor_limit_right, float dt)
float get_steering_out_heading (float heading_rad, float rate_max_rads, bool motor_limit_left, bool motor_limit_right, float dt)
float get_turn_rate_from_heading (float heading_rad, float rate_max_rads) const
float get_steering_out_rate (float desired_rate, bool motor_limit_left, bool motor_limit_right, float dt)
float get_desired_turn_rate () const
float get_desired_lat_accel () const
bool get_lat_accel (float &lat_accel) const
float get_turn_rate_from_lat_accel (float lat_accel, float speed) const
float get_turn_lat_accel_max () const
bool steering_limit_left () const
bool steering_limit_right () const
void set_throttle_limits (float throttle_accel_max, float throttle_decel_max)
float get_throttle_out_speed (float desired_speed, bool motor_limit_low, bool motor_limit_high, float cruise_speed, float cruise_throttle, float dt)
float get_throttle_out_stop (bool motor_limit_low, bool motor_limit_high, float cruise_speed, float cruise_throttle, float dt, bool &stopped)
float get_throttle_out_from_pitch (float desired_pitch, float pitch_max, bool motor_limit, float dt)
bool pitch_limited () const
float get_desired_pitch () const
float get_sail_out_from_heel (float desired_heel, float dt)
AC_P & get_steering_angle_p ()
AC_PID & get_steering_rate_pid ()
AC_PID & get_pitch_to_throttle_pid ()
AC_PID & get_sailboat_heel_pid ()
const AP_PIDInfo & get_throttle_speed_pid_info () const
void set_notch_sample_rate (float sample_rate)
void get_srate (float &steering_srate, float &speed_srate)
bool get_forward_speed (float &speed) const
float get_accel_max () const
float get_decel_max () const
bool speed_control_active () const
float get_desired_speed () const
float get_desired_speed_accel_limited (float desired_speed, float dt) const
float get_stopping_distance (float speed) const
float get_stop_speed () const
void relax_I ()
Static Public Member Functions
static AR_AttitudeControl * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
AC_P _steer_angle_p
AC_PID _steer_rate_pid
AC_PID _throttle_speed_pid
AC_PID _pitch_to_throttle_pid
AP_Float _pitch_to_throttle_ff
AP_Float _pitch_limit_tc
AP_Float _pitch_limit_throttle_thresh
AP_Float _throttle_accel_max
AP_Float _throttle_decel_max
AP_Int8 _brake_enable
AP_Float _stop_speed
AP_Float _steer_accel_max
AP_Float _steer_rate_max
AP_Float _turn_lateral_G_max
uint32_t _steer_lat_accel_last_ms
uint32_t _steer_turn_last_ms
float _desired_lat_accel
float _desired_turn_rate
bool _steering_limit_left
bool _steering_limit_right
uint32_t _speed_last_ms
float _desired_speed
uint32_t _stop_last_ms
bool _throttle_limit_low
bool _throttle_limit_high
AP_PIDInfo _throttle_speed_pid_info
uint32_t _balance_last_ms = 0
float _pitch_limit_low = 0
float _pitch_limit_high = 0
bool _pitch_limited = false
AC_PID _sailboat_heel_pid
uint32_t _heel_controller_last_ms = 0
Static Private Attributes
static AR_AttitudeControl * _singleton
Detailed Description
Definition at line 7 of file AR_AttitudeControl.h.
Constructor & Destructor Documentation
AR_AttitudeControl()
AR_AttitudeControl::AR_AttitudeControl ()
Definition at line 570 of file AR_AttitudeControl.cpp.
Member Function Documentation
CLASS_NO_COPY()
AR_AttitudeControl::CLASS_NO_COPY (AR_AttitudeControl)
get_accel_max()
float AR_AttitudeControl::get_accel_max () const inline
Definition at line 113 of file AR_AttitudeControl.h.
Referenced by get_stopping_distance(), and AR_WPNav::init().
get_decel_max()
float AR_AttitudeControl::get_decel_max () const
Definition at line 998 of file AR_AttitudeControl.cpp.
Referenced by AR_WPNav::init().
get_desired_lat_accel()
float AR_AttitudeControl::get_desired_lat_accel () const
Definition at line 714 of file AR_AttitudeControl.cpp.
get_desired_pitch()
float AR_AttitudeControl::get_desired_pitch () const
Definition at line 918 of file AR_AttitudeControl.cpp.
get_desired_speed()
float AR_AttitudeControl::get_desired_speed () const
Definition at line 1018 of file AR_AttitudeControl.cpp.
get_desired_speed_accel_limited()
float AR_AttitudeControl::get_desired_speed_accel_limited (float desired_speed, float dt) const
Definition at line 1028 of file AR_AttitudeControl.cpp.
Referenced by get_throttle_out_speed(), get_throttle_out_stop(), AR_PosControl::update(), AR_WPNav::update(), AR_WPNav_OA::update(), and AR_WPNav::update_steering_and_speed().
get_desired_turn_rate()
float AR_AttitudeControl::get_desired_turn_rate () const
Definition at line 704 of file AR_AttitudeControl.cpp.
get_forward_speed()
bool AR_AttitudeControl::get_forward_speed (float & speed) const
Definition at line 976 of file AR_AttitudeControl.cpp.
Referenced by get_desired_speed_accel_limited(), get_lat_accel(), get_steering_out_lat_accel(), get_steering_out_rate(), get_throttle_out_speed(), get_throttle_out_stop(), AR_WPNav::update(), and AR_WPNav_OA::update().
get_lat_accel()
bool AR_AttitudeControl::get_lat_accel (float & lat_accel) const
Definition at line 724 of file AR_AttitudeControl.cpp.
get_pitch_to_throttle_pid()
AC_PID & AR_AttitudeControl::get_pitch_to_throttle_pid () inline
Definition at line 99 of file AR_AttitudeControl.h.
get_sail_out_from_heel()
float AR_AttitudeControl::get_sail_out_from_heel (float desired_heel, float dt)
Definition at line 930 of file AR_AttitudeControl.cpp.
get_sailboat_heel_pid()
AC_PID & AR_AttitudeControl::get_sailboat_heel_pid () inline
Definition at line 100 of file AR_AttitudeControl.h.
get_singleton()
static AR_AttitudeControl * AR_AttitudeControl::get_singleton () inline static
Definition at line 16 of file AR_AttitudeControl.h.
get_srate()
void AR_AttitudeControl::get_srate (float & steering_srate, float & speed_srate)
Definition at line 969 of file AR_AttitudeControl.cpp.
get_steering_angle_p()
AC_P & AR_AttitudeControl::get_steering_angle_p () inline
Definition at line 97 of file AR_AttitudeControl.h.
get_steering_out_heading()
float AR_AttitudeControl::get_steering_out_heading (float heading_rad, float rate_max_rads, bool motor_limit_left, bool motor_limit_right, float dt)
Definition at line 605 of file AR_AttitudeControl.cpp.
get_steering_out_lat_accel()
float AR_AttitudeControl::get_steering_out_lat_accel (float desired_accel, bool motor_limit_left, bool motor_limit_right, float dt)
Definition at line 583 of file AR_AttitudeControl.cpp.
get_steering_out_rate()
float AR_AttitudeControl::get_steering_out_rate (float desired_rate, bool motor_limit_left, bool motor_limit_right, float dt)
Definition at line 639 of file AR_AttitudeControl.cpp.
Referenced by get_steering_out_heading(), and get_steering_out_lat_accel().
get_steering_rate_pid()
AC_PID & AR_AttitudeControl::get_steering_rate_pid () inline
Definition at line 98 of file AR_AttitudeControl.h.
Referenced by get_srate().
get_stop_speed()
float AR_AttitudeControl::get_stop_speed () const inline
Definition at line 131 of file AR_AttitudeControl.h.
get_stopping_distance()
float AR_AttitudeControl::get_stopping_distance (float speed) const
Definition at line 1058 of file AR_AttitudeControl.cpp.
Referenced by AR_WPNav::get_stopping_location().
get_throttle_out_from_pitch()
float AR_AttitudeControl::get_throttle_out_from_pitch (float desired_pitch, float pitch_max, bool motor_limit, float dt)
Definition at line 862 of file AR_AttitudeControl.cpp.
get_throttle_out_speed()
float AR_AttitudeControl::get_throttle_out_speed (float desired_speed, bool motor_limit_low, bool motor_limit_high, float cruise_speed, float cruise_throttle, float dt)
Definition at line 752 of file AR_AttitudeControl.cpp.
Referenced by get_throttle_out_stop().
get_throttle_out_stop()
float AR_AttitudeControl::get_throttle_out_stop (bool motor_limit_low, bool motor_limit_high, float cruise_speed, float cruise_throttle, float dt, bool & stopped)
Definition at line 812 of file AR_AttitudeControl.cpp.
get_throttle_speed_pid_info()
const AP_PIDInfo & AR_AttitudeControl::get_throttle_speed_pid_info () const inline
Definition at line 101 of file AR_AttitudeControl.h.
get_turn_lat_accel_max()
float AR_AttitudeControl::get_turn_lat_accel_max () const inline
Definition at line 55 of file AR_AttitudeControl.h.
Referenced by get_steering_out_rate(), AR_WPNav::init(), and AR_PosControl::update().
get_turn_rate_from_heading()
float AR_AttitudeControl::get_turn_rate_from_heading (float heading_rad, float rate_max_rads) const
Definition at line 614 of file AR_AttitudeControl.cpp.
Referenced by get_steering_out_heading(), and AR_PivotTurn::get_turn_rate_rads().
get_turn_rate_from_lat_accel()
float AR_AttitudeControl::get_turn_rate_from_lat_accel (float lat_accel, float speed) const
Definition at line 735 of file AR_AttitudeControl.cpp.
Referenced by get_steering_out_lat_accel(), get_steering_out_rate(), and AR_PosControl::update().
pitch_limited()
bool AR_AttitudeControl::pitch_limited () const inline
Definition at line 88 of file AR_AttitudeControl.h.
relax_I()
void AR_AttitudeControl::relax_I ()
Definition at line 1073 of file AR_AttitudeControl.cpp.
set_notch_sample_rate()
void AR_AttitudeControl::set_notch_sample_rate (float sample_rate)
Definition at line 1080 of file AR_AttitudeControl.cpp.
set_throttle_limits()
void AR_AttitudeControl::set_throttle_limits (float throttle_accel_max, float throttle_decel_max)
speed_control_active()
bool AR_AttitudeControl::speed_control_active () const
Definition at line 1008 of file AR_AttitudeControl.cpp.
Referenced by get_desired_speed(), get_desired_speed_accel_limited(), and get_throttle_out_speed().
steering_limit_left()
bool AR_AttitudeControl::steering_limit_left () const inline
Definition at line 59 of file AR_AttitudeControl.h.
Referenced by AR_PosControl::update().
steering_limit_right()
bool AR_AttitudeControl::steering_limit_right () const inline
Definition at line 60 of file AR_AttitudeControl.h.
Referenced by AR_PosControl::update().
Member Data Documentation
_balance_last_ms
uint32_t AR_AttitudeControl::_balance_last_ms = 0 private
Definition at line 177 of file AR_AttitudeControl.h.
Referenced by get_desired_pitch(), and get_throttle_out_from_pitch().
_brake_enable
AP_Int8 AR_AttitudeControl::_brake_enable private
Definition at line 154 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_speed().
_desired_lat_accel
float AR_AttitudeControl::_desired_lat_accel private
Definition at line 163 of file AR_AttitudeControl.h.
Referenced by get_desired_lat_accel(), and get_steering_out_lat_accel().
_desired_speed
float AR_AttitudeControl::_desired_speed private
Definition at line 170 of file AR_AttitudeControl.h.
Referenced by get_desired_speed(), get_desired_speed_accel_limited(), get_throttle_out_speed(), and get_throttle_out_stop().
_desired_turn_rate
float AR_AttitudeControl::_desired_turn_rate private
Definition at line 164 of file AR_AttitudeControl.h.
Referenced by get_desired_turn_rate(), and get_steering_out_rate().
_heel_controller_last_ms
uint32_t AR_AttitudeControl::_heel_controller_last_ms = 0 private
Definition at line 184 of file AR_AttitudeControl.h.
Referenced by get_sail_out_from_heel().
_pitch_limit_high
float AR_AttitudeControl::_pitch_limit_high = 0 private
Definition at line 179 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_from_pitch().
_pitch_limit_low
float AR_AttitudeControl::_pitch_limit_low = 0 private
Definition at line 178 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_from_pitch().
_pitch_limit_tc
AP_Float AR_AttitudeControl::_pitch_limit_tc private
Definition at line 149 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_from_pitch().
_pitch_limit_throttle_thresh
AP_Float AR_AttitudeControl::_pitch_limit_throttle_thresh private
Definition at line 150 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_from_pitch().
_pitch_limited
bool AR_AttitudeControl::_pitch_limited = false private
Definition at line 180 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_from_pitch(), and pitch_limited().
_pitch_to_throttle_ff
AP_Float AR_AttitudeControl::_pitch_to_throttle_ff private
Definition at line 148 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_from_pitch().
_pitch_to_throttle_pid
AC_PID AR_AttitudeControl::_pitch_to_throttle_pid private
Definition at line 147 of file AR_AttitudeControl.h.
Referenced by get_desired_pitch(), get_pitch_to_throttle_pid(), get_throttle_out_from_pitch(), relax_I(), and set_notch_sample_rate().
_sailboat_heel_pid
AC_PID AR_AttitudeControl::_sailboat_heel_pid private
Definition at line 183 of file AR_AttitudeControl.h.
Referenced by get_sail_out_from_heel(), and get_sailboat_heel_pid().
_singleton
AR_AttitudeControl * AR_AttitudeControl::_singleton static private
Definition at line 141 of file AR_AttitudeControl.h.
Referenced by AR_AttitudeControl(), and get_singleton().
_speed_last_ms
uint32_t AR_AttitudeControl::_speed_last_ms private
Definition at line 169 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_speed(), get_throttle_out_stop(), and speed_control_active().
_steer_accel_max
AP_Float AR_AttitudeControl::_steer_accel_max private
Definition at line 156 of file AR_AttitudeControl.h.
Referenced by get_steering_out_rate(), and get_turn_rate_from_heading().
_steer_angle_p
AC_P AR_AttitudeControl::_steer_angle_p private
Definition at line 144 of file AR_AttitudeControl.h.
Referenced by get_steering_angle_p(), and get_turn_rate_from_heading().
_steer_lat_accel_last_ms
uint32_t AR_AttitudeControl::_steer_lat_accel_last_ms private
Definition at line 161 of file AR_AttitudeControl.h.
Referenced by get_desired_lat_accel(), and get_steering_out_lat_accel().
_steer_rate_max
AP_Float AR_AttitudeControl::_steer_rate_max private
Definition at line 157 of file AR_AttitudeControl.h.
Referenced by get_steering_out_rate().
_steer_rate_pid
AC_PID AR_AttitudeControl::_steer_rate_pid private
Definition at line 145 of file AR_AttitudeControl.h.
Referenced by get_steering_out_rate(), get_steering_rate_pid(), relax_I(), and set_notch_sample_rate().
_steer_turn_last_ms
uint32_t AR_AttitudeControl::_steer_turn_last_ms private
Definition at line 162 of file AR_AttitudeControl.h.
Referenced by get_desired_turn_rate(), and get_steering_out_rate().
_steering_limit_left
bool AR_AttitudeControl::_steering_limit_left private
Definition at line 165 of file AR_AttitudeControl.h.
Referenced by get_steering_out_rate(), and steering_limit_left().
_steering_limit_right
bool AR_AttitudeControl::_steering_limit_right private
Definition at line 166 of file AR_AttitudeControl.h.
Referenced by get_steering_out_rate(), and steering_limit_right().
_stop_last_ms
uint32_t AR_AttitudeControl::_stop_last_ms private
Definition at line 171 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_stop().
_stop_speed
AP_Float AR_AttitudeControl::_stop_speed private
Definition at line 155 of file AR_AttitudeControl.h.
Referenced by get_stop_speed(), and get_throttle_out_stop().
_throttle_accel_max
AP_Float AR_AttitudeControl::_throttle_accel_max private
Definition at line 152 of file AR_AttitudeControl.h.
Referenced by get_accel_max(), get_decel_max(), and get_desired_speed_accel_limited().
_throttle_decel_max
AP_Float AR_AttitudeControl::_throttle_decel_max private
Definition at line 153 of file AR_AttitudeControl.h.
Referenced by get_decel_max(), and get_desired_speed_accel_limited().
_throttle_limit_high
bool AR_AttitudeControl::_throttle_limit_high private
Definition at line 173 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_speed().
_throttle_limit_low
bool AR_AttitudeControl::_throttle_limit_low private
Definition at line 172 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_speed().
_throttle_speed_pid
AC_PID AR_AttitudeControl::_throttle_speed_pid private
Definition at line 146 of file AR_AttitudeControl.h.
Referenced by get_throttle_out_speed(), get_throttle_out_stop(), relax_I(), and set_notch_sample_rate().
_throttle_speed_pid_info
AP_PIDInfo AR_AttitudeControl::_throttle_speed_pid_info private
Definition at line 174 of file AR_AttitudeControl.h.
Referenced by get_srate(), get_throttle_out_speed(), and get_throttle_speed_pid_info().
_turn_lateral_G_max
AP_Float AR_AttitudeControl::_turn_lateral_G_max private
Definition at line 158 of file AR_AttitudeControl.h.
Referenced by get_turn_lat_accel_max().
var_info
const AP_Param::GroupInfo AR_AttitudeControl::var_info static
Definition at line 68 of file AR_AttitudeControl.h.
The documentation for this class was generated from the following files:
libraries/APM_Control/AR_AttitudeControl.h
libraries/APM_Control/AR_AttitudeControl.cpp