APM:Libraries: AP_HAL::UARTDriver Class Reference
AP_HAL::UARTDriver Class Reference abstract
#include <UARTDriver.h>
Public Types
enum {
OPTION_RXINV = (1U<<0) , OPTION_TXINV = (1U<<1) , OPTION_HDPLEX = (1U<<2) , OPTION_SWAP = (1U<<3) ,
OPTION_PULLDOWN_RX = (1U<<4) , OPTION_PULLUP_RX = (1U<<5) , OPTION_PULLDOWN_TX = (1U<<6) , OPTION_PULLUP_TX = (1U<<7) ,
OPTION_NODMA_RX = (1U<<8) , OPTION_NODMA_TX = (1U<<9) , OPTION_MAVLINK_NO_FORWARD = (1U<<10) , OPTION_NOFIFO = (1U<<11) ,
OPTION_NOSTREAMOVERRIDE = (1U<<12)
}
enum flow_control { FLOW_CONTROL_DISABLE =0 , FLOW_CONTROL_ENABLE =1 , FLOW_CONTROL_AUTO =2 }
Public Member Functions
UARTDriver ()
CLASS_NO_COPY (UARTDriver)
void begin (uint32_t baud)
void begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace)
void begin_locked (uint32_t baud, uint16_t rxSpace, uint16_t txSpace, uint32_t write_key)
size_t write (uint8_t c) override
size_t write (const uint8_t *buffer, size_t size) override
size_t write (const char *str) override
int16_t read (void) override
bool read (uint8_t &b) override WARN_IF_UNUSED
ssize_t read (uint8_t *buffer, uint16_t count) override
void end ()
void flush ()
virtual bool is_initialized ()=0
virtual bool tx_pending ()=0
bool lock_port (uint32_t write_key, uint32_t read_key)
uint32_t available () override
uint32_t available_locked (uint32_t key)
bool discard_input () override
size_t write_locked (const uint8_t *buffer, size_t size, uint32_t key)
ssize_t read_locked (uint8_t *buf, size_t count, uint32_t key) WARN_IF_UNUSED
virtual bool set_options (uint16_t options)
virtual uint16_t get_options (void) const
virtual void set_flow_control (enum flow_control flow_control_setting)
virtual enum flow_control get_flow_control (void)
virtual void configure_parity (uint8_t v)
virtual void set_stop_bits (int n)
virtual bool set_unbuffered_writes (bool on)
virtual bool wait_timeout (uint16_t n, uint32_t timeout_ms)
virtual void _timer_tick (void)
virtual uint64_t receive_time_constraint_us (uint16_t nbytes)
virtual uint32_t bw_in_bytes_per_second () const
virtual uint32_t get_baud_rate () const
virtual bool is_dma_enabled () const
virtual void uart_info (ExpandingString &str)
virtual bool set_RTS_pin (bool high)
virtual bool set_CTS_pin (bool high)
virtual uint32_t get_usb_baud (void) const
virtual void disable_rxtx (void) const
bool is_write_locked (void) const
Public Member Functions inherited from AP_HAL::BetterStream
virtual void printf (const char *,...) FMT_PRINTF(2
virtual void virtual void vprintf (const char *, va_list)
void print (const char *str)
void println (const char *str)
virtual uint32_t txspace ()=0
Protected Member Functions
virtual void _begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace)=0
virtual size_t _write (const uint8_t *buffer, size_t size)=0
virtual ssize_t _read (uint8_t *buffer, uint16_t count) WARN_IF_UNUSED=0
virtual void _end ()=0
virtual void _flush ()=0
virtual uint32_t _available ()=0
virtual bool _discard_input (void)=0
Protected Attributes
uint32_t lock_write_key
uint32_t lock_read_key
Private Attributes
uint16_t _last_options
Detailed Description
Definition at line 20 of file UARTDriver.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
OPTION_RXINV
OPTION_TXINV
OPTION_HDPLEX
OPTION_SWAP
OPTION_PULLDOWN_RX
OPTION_PULLUP_RX
OPTION_PULLDOWN_TX
OPTION_PULLUP_TX
OPTION_NODMA_RX
OPTION_NODMA_TX
OPTION_MAVLINK_NO_FORWARD
OPTION_NOFIFO
OPTION_NOSTREAMOVERRIDE
Definition at line 85 of file UARTDriver.h.
flow_control
enum AP_HAL::UARTDriver::flow_control
Enumerator
FLOW_CONTROL_DISABLE
FLOW_CONTROL_ENABLE
FLOW_CONTROL_AUTO
Definition at line 101 of file UARTDriver.h.
Constructor & Destructor Documentation
UARTDriver()
AP_HAL::UARTDriver::UARTDriver () inline
Definition at line 22 of file UARTDriver.h.
Member Function Documentation
_available()
virtual uint32_t AP_HAL::UARTDriver::_available () protected pure virtual
Implemented in DummyUart, DummyUart, ChibiOS::UARTDriver, Empty::UARTDriver, ESP32::UARTDriver, ESP32::WiFiDriver, ESP32::WiFiUdpDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
_begin()
virtual void AP_HAL::UARTDriver::_begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace) protected pure virtual
Implemented in ChibiOS::UARTDriver, Empty::UARTDriver, ESP32::UARTDriver, ESP32::WiFiDriver, ESP32::WiFiUdpDriver, Linux::SPIUARTDriver, Linux::UARTDriver, HALSITL::UARTDriver, DummyUart, and DummyUart.
Referenced by begin().
_discard_input()
virtual bool AP_HAL::UARTDriver::_discard_input (void) protected pure virtual
Implemented in DummyUart, DummyUart, ChibiOS::UARTDriver, Empty::UARTDriver, ESP32::UARTDriver, ESP32::WiFiDriver, ESP32::WiFiUdpDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
_end()
virtual void AP_HAL::UARTDriver::_end () protected pure virtual
Implemented in DummyUart, DummyUart, ChibiOS::UARTDriver, Empty::UARTDriver, ESP32::UARTDriver, ESP32::WiFiDriver, ESP32::WiFiUdpDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
_flush()
virtual void AP_HAL::UARTDriver::_flush () protected pure virtual
Implemented in DummyUart, DummyUart, ChibiOS::UARTDriver, Empty::UARTDriver, ESP32::UARTDriver, ESP32::WiFiDriver, ESP32::WiFiUdpDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
_read()
virtual ssize_t AP_HAL::UARTDriver::_read (uint8_t * buffer, uint16_t count) protected pure virtual
Implemented in DummyUart, ESP32::WiFiUdpDriver, DummyUart, ChibiOS::UARTDriver, ESP32::UARTDriver, HALSITL::UARTDriver, Linux::UARTDriver, ESP32::WiFiDriver, and Empty::UARTDriver.
_timer_tick()
virtual void AP_HAL::UARTDriver::_timer_tick (void) inline virtual
Reimplemented in ESP32::UARTDriver, Linux::SPIUARTDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
Definition at line 128 of file UARTDriver.h.
Referenced by HALSITL::Scheduler::_run_io_procs(), Linux::Scheduler::_run_uarts(), and ESP32::Scheduler::_uart_thread().
_write()
virtual size_t AP_HAL::UARTDriver::_write (const uint8_t * buffer, size_t size) protected pure virtual
Implemented in DummyUart, DummyUart, ChibiOS::UARTDriver, Empty::UARTDriver, ESP32::UARTDriver, ESP32::WiFiDriver, ESP32::WiFiUdpDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
available()
uint32_t AP_HAL::UARTDriver::available () override virtual
Implements AP_HAL::BetterStream.
Definition at line 124 of file UARTDriver.cpp.
Referenced by AP_GPS_SBP::_sbp_process(), AP_GPS_SBP2::_sbp_process(), drive(), AP_RangeFinder_LeddarOne::get_reading(), loop(), AP_Hott_Telem::loop(), loop(), AP_RangeFinder_LeddarOne::parse_response(), AP_MSP_Telem_Backend::process_incoming_data(), AP_GPS_ERB::read(), AP_GPS_NMEA::read(), AP_GPS_SBF::read(), AP_GPS_SIRF::read(), AP_GPS_UBLOX::read(), AP_GPS_GSOF::read(), AP_Mount_Alexmos::read_incoming(), AP_Mount_SToRM32_serial::read_incoming(), AP_Mount_Siyi::read_incoming_packets(), AP_SmartAudio::read_response(), AP_RunCam::receive(), ChibiOS::UARTDriver::receive_time_constraint_us(), ESP32::UARTDriver::receive_time_constraint_us(), Linux::UARTDriver::receive_time_constraint_us(), HALSITL::UARTDriver::receive_time_constraint_us(), run_test(), AP_Frsky_SPort::send(), AP_Frsky_SPort_Passthrough::send(), AP_Hott_Telem::send_packet(), AP_WindVane_NMEA::update(), AP_Beacon_Marvelmind::update(), AP_Beacon_Nooploop::update(), AP_Beacon_Pozyx::update(), AP_Generator_IE_FuelCell::update(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_UPFLOW::update(), AP_RCProtocol_CRSF::update(), GCS_MAVLINK::update_receive(), and ChibiOS::UARTDriver::wait_timeout().
available_locked()
uint32_t AP_HAL::UARTDriver::available_locked (uint32_t key)
Definition at line 77 of file UARTDriver.cpp.
begin() [1/2]
void AP_HAL::UARTDriver::begin (uint32_t baud)
Definition at line 15 of file UARTDriver.cpp.
Referenced by Linux::SPIUARTDriver::_begin(), AP_GPS::_detect_instance(), AP_GPS_UBLOX::_parse_gps(), AP_Beacon_Marvelmind::AP_Beacon_Backend(), AP_RCProtocol::SerialConfig::apply_to_uart(), AP_RCProtocol_SRXL2::change_baud_rate(), AP_RCProtocol_CRSF::decode_crsf_packet(), AP_LTM_Telem::init(), AP_SerialManager::init(), AP_OpticalFlow_CXOF::init(), AP_OpticalFlow_UPFLOW::init(), AP_WindVane_NMEA::init(), GCS_MAVLINK::init(), AP_Generator_IE_FuelCell::init(), AP_SerialManager::init_console(), AP_RangeFinder_Backend_Serial::init_serial(), AP_MSP_Telem_Backend::init_uart(), AP_MSP_Telem_DisplayPort::init_uart(), AP_MSP_Telem_DJI::init_uart(), AP_SmartAudio::loop(), AP_Frsky_Backend::loop(), AP_Hott_Telem::loop(), main_loop(), AP_RCProtocol_CRSF::process_handshake(), AP_RCProtocol_GHST::process_handshake(), HAL_Empty::run(), HAL_Linux::run(), HAL_SITL::run(), setup(), setup(), setup_uart(), AP_RunCam::start_uart(), AP_RCProtocol_CRSF::start_uart(), AP_RangeFinder_Wasp::update(), and AP_SmartAudio::update_baud_rate().
begin() [2/2]
void AP_HAL::UARTDriver::begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace)
Definition at line 6 of file UARTDriver.cpp.
begin_locked()
void AP_HAL::UARTDriver::begin_locked (uint32_t baud, uint16_t rxSpace, uint16_t txSpace, uint32_t write_key)
Definition at line 38 of file UARTDriver.cpp.
bw_in_bytes_per_second()
virtual uint32_t AP_HAL::UARTDriver::bw_in_bytes_per_second () const inline virtual
Reimplemented in ChibiOS::UARTDriver, ESP32::UARTDriver, ESP32::WiFiDriver, ESP32::WiFiUdpDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
Definition at line 143 of file UARTDriver.h.
Referenced by GCS_MAVLINK::ftp_worker(), and GCS_MAVLINK::queued_param_send().
CLASS_NO_COPY()
AP_HAL::UARTDriver::CLASS_NO_COPY (UARTDriver)
configure_parity()
virtual void AP_HAL::UARTDriver::configure_parity (uint8_t v) inline virtual
Reimplemented in ChibiOS::UARTDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
Definition at line 109 of file UARTDriver.h.
Referenced by AP_RCProtocol::SerialConfig::apply_to_uart(), AP_SerialManager::init(), AP_SmartAudio::init(), AP_RunCam::start_uart(), and AP_RCProtocol_CRSF::start_uart().
disable_rxtx()
virtual void AP_HAL::UARTDriver::disable_rxtx (void) const inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 170 of file UARTDriver.h.
Referenced by AP_SerialManager::init().
discard_input()
bool AP_HAL::UARTDriver::discard_input () override virtual
Implements AP_HAL::BetterStream.
Definition at line 148 of file UARTDriver.cpp.
Referenced by AP_RunCam::drain(), AP_RangeFinder_LeddarOne::get_reading(), AP_SmartAudio::loop(), AP_Hott_Telem::loop(), and AP_RunCam::start_uart().
end()
void AP_HAL::UARTDriver::end ()
Definition at line 132 of file UARTDriver.cpp.
Referenced by AP_RangeFinder_Wasp::update().
flush()
void AP_HAL::UARTDriver::flush ()
Definition at line 140 of file UARTDriver.cpp.
Referenced by ESP32::UARTDriver::_begin(), AP_Vehicle::reboot(), AP_RunCam::send_packet(), AP_SmartAudio::send_request(), AP_RCProtocol_CRSF::write_frame(), and AP_RCProtocol_GHST::write_frame().
get_baud_rate()
virtual uint32_t AP_HAL::UARTDriver::get_baud_rate () const inline virtual
Reimplemented in ChibiOS::UARTDriver, ESP32::UARTDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
Definition at line 147 of file UARTDriver.h.
Referenced by AP_GPS::_detect_instance(), AP_RCProtocol_CRSF::process_handshake(), and AP_RCProtocol_GHST::process_handshake().
get_flow_control()
virtual enum flow_control AP_HAL::UARTDriver::get_flow_control (void) inline virtual
Reimplemented in ChibiOS::UARTDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
Definition at line 107 of file UARTDriver.h.
Referenced by GCS_MAVLINK::have_flow_control(), GCS_MAVLINK::init(), and AP_GPS_SBF::read().
get_options()
virtual uint16_t AP_HAL::UARTDriver::get_options (void) const inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 83 of file UARTDriver.h.
Referenced by AP_RCProtocol::SerialConfig::apply_to_uart(), GCS_MAVLINK::handle_message(), AP_SmartAudio::init(), AP_RunCam::start_uart(), and AP_RCProtocol_CRSF::start_uart().
get_usb_baud()
virtual uint32_t AP_HAL::UARTDriver::get_usb_baud (void) const inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 167 of file UARTDriver.h.
is_dma_enabled()
virtual bool AP_HAL::UARTDriver::is_dma_enabled () const inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 152 of file UARTDriver.h.
Referenced by AP_RCProtocol_CRSF::change_baud_rate().
is_initialized()
virtual bool AP_HAL::UARTDriver::is_initialized () pure virtual
Implemented in DummyUart, DummyUart, ChibiOS::UARTDriver, Empty::UARTDriver, ESP32::UARTDriver, ESP32::WiFiDriver, ESP32::WiFiUdpDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
Referenced by loop(), and AP_RCProtocol_SRXL2::send_on_uart().
is_write_locked()
bool AP_HAL::UARTDriver::is_write_locked (void) const inline
Definition at line 184 of file UARTDriver.h.
lock_port()
bool AP_HAL::UARTDriver::lock_port (uint32_t write_key, uint32_t read_key)
Definition at line 23 of file UARTDriver.cpp.
read() [1/3]
bool AP_HAL::UARTDriver::read (uint8_t & b) override virtual
Implements AP_HAL::BetterStream.
Definition at line 108 of file UARTDriver.cpp.
read() [2/3]
ssize_t AP_HAL::UARTDriver::read (uint8_t * buffer, uint16_t count) override virtual
Reimplemented from AP_HAL::BetterStream.
Definition at line 103 of file UARTDriver.cpp.
read() [3/3]
int16_t AP_HAL::UARTDriver::read (void) override virtual
Reimplemented from AP_HAL::BetterStream.
Definition at line 114 of file UARTDriver.cpp.
Referenced by AP_GPS::_detect_instance(), AP_GPS_SBP::_sbp_process(), AP_GPS_SBP2::_sbp_process(), AP_RangeFinder_USD1_Serial::detect_version(), AP_RangeFinder_Benewake::get_reading(), AP_RangeFinder_BLPing::get_reading(), AP_RangeFinder_GYUS42v2::get_reading(), AP_RangeFinder_Lanbao::get_reading(), AP_RangeFinder_LeddarVu8::get_reading(), AP_RangeFinder_LightWareSerial::get_reading(), AP_RangeFinder_MaxsonarSerialLV::get_reading(), AP_RangeFinder_NMEA::get_reading(), AP_RangeFinder_TeraRanger_Serial::get_reading(), AP_RangeFinder_USD1_Serial::get_reading(), AP_RangeFinder_Wasp::get_reading(), HALSITL::UARTDriver::handle_reading_from_device_to_readbuffer(), loop(), AP_Hott_Telem::loop(), loop(), AP_RangeFinder_LeddarOne::parse_response(), AP_MSP_Telem_Backend::process_incoming_data(), AP_GPS_ERB::read(), AP_GPS_NMEA::read(), AP_GPS_NOVA::read(), AP_GPS_SBF::read(), AP_GPS_SIRF::read(), AP_GPS_UBLOX::read(), AP_GPS_GSOF::read(), HALSITL::UARTDriver::read_from_async_csv(), AP_Mount_Alexmos::read_incoming(), AP_Mount_SToRM32_serial::read_incoming(), AP_Mount_Siyi::read_incoming_packets(), AP_SmartAudio::read_response(), AP_RunCam::receive(), run_test(), AP_Frsky_SPort::send(), AP_Frsky_SPort_Passthrough::send(), AP_Hott_Telem::send_packet(), AP_WindVane_NMEA::update(), AP_Beacon_Marvelmind::update(), AP_Beacon_Nooploop::update(), AP_Beacon_Pozyx::update(), AP_Generator_IE_FuelCell::update(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_UPFLOW::update(), AP_RCProtocol_CRSF::update(), and GCS_MAVLINK::update_receive().
read_locked()
ssize_t AP_HAL::UARTDriver::read_locked (uint8_t * buf, size_t count, uint32_t key)
Definition at line 62 of file UARTDriver.cpp.
receive_time_constraint_us()
uint64_t AP_HAL::UARTDriver::receive_time_constraint_us (uint16_t nbytes) virtual
Reimplemented in ChibiOS::UARTDriver, ESP32::UARTDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
Definition at line 162 of file UARTDriver.cpp.
Referenced by AP_GPS_Backend::check_new_itow(), GCS_MAVLINK::correct_offboard_timestamp_usec_to_ms(), AP_RCProtocol_FPort::decode_downlink(), AP_RCProtocol_SRXL2::send_on_uart(), AP_GPS_Backend::set_uart_timestamp(), GCS_MAVLINK::timesync_receive_timestamp_ns(), AP_OpticalFlow_CXOF::update(), and AP_RCProtocol_GHST::write_frame().
set_CTS_pin()
virtual bool AP_HAL::UARTDriver::set_CTS_pin (bool high) inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 164 of file UARTDriver.h.
set_flow_control()
virtual void AP_HAL::UARTDriver::set_flow_control (enum flow_control flow_control_setting) inline virtual
Reimplemented in Linux::UARTDriver.
Definition at line 106 of file UARTDriver.h.
Referenced by AP_GPS::_detect_instance(), AP_RCProtocol::add_uart(), AP_BoardConfig::board_setup_uart(), AP_RCProtocol_SRXL2::change_baud_rate(), AP_LTM_Telem::init(), AP_SerialManager::init(), AP_SmartAudio::init(), GCS_MAVLINK::init(), AP_Frsky_Backend::init_serial_port(), AP_MSP_Telem_DJI::init_uart(), setup(), AP_RunCam::start_uart(), and AP_RCProtocol_CRSF::start_uart().
set_options()
virtual bool AP_HAL::UARTDriver::set_options (uint16_t options) inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 82 of file UARTDriver.h.
Referenced by AP_RCProtocol::SerialConfig::apply_to_uart(), AP_SerialManager::find_serial(), AP_SmartAudio::init(), AP_SerialManager::set_options(), AP_RunCam::start_uart(), and AP_RCProtocol_CRSF::start_uart().
set_RTS_pin()
virtual bool AP_HAL::UARTDriver::set_RTS_pin (bool high) inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 163 of file UARTDriver.h.
set_stop_bits()
virtual void AP_HAL::UARTDriver::set_stop_bits (int n) inline virtual
Reimplemented in ChibiOS::UARTDriver, and HALSITL::UARTDriver.
Definition at line 110 of file UARTDriver.h.
Referenced by AP_RCProtocol::SerialConfig::apply_to_uart(), AP_SerialManager::init(), AP_SmartAudio::init(), AP_RunCam::start_uart(), and AP_RCProtocol_CRSF::start_uart().
set_unbuffered_writes()
virtual bool AP_HAL::UARTDriver::set_unbuffered_writes (bool on) inline virtual
Reimplemented in ChibiOS::UARTDriver, and HALSITL::UARTDriver.
Definition at line 115 of file UARTDriver.h.
Referenced by AP_RCProtocol_SRXL2::change_baud_rate(), AP_SerialManager::init(), AP_Hott_Telem::loop(), and setup().
tx_pending()
virtual bool AP_HAL::UARTDriver::tx_pending () pure virtual
Implemented in DummyUart, DummyUart, ChibiOS::UARTDriver, Empty::UARTDriver, ESP32::UARTDriver, ESP32::WiFiDriver, ESP32::WiFiUdpDriver, Linux::UARTDriver, and HALSITL::UARTDriver.
Referenced by AP_RCProtocol_CRSF::decode_crsf_packet(), and AP_RangeFinder_Wasp::get_reading().
uart_info()
virtual void AP_HAL::UARTDriver::uart_info (ExpandingString & str) inline virtual
Definition at line 156 of file UARTDriver.h.
wait_timeout()
virtual bool AP_HAL::UARTDriver::wait_timeout (uint16_t n, uint32_t timeout_ms) inline virtual
Reimplemented in ChibiOS::UARTDriver.
Definition at line 122 of file UARTDriver.h.
write() [1/3]
size_t AP_HAL::UARTDriver::write (const char * str) override virtual
Reimplemented from AP_HAL::BetterStream.
Definition at line 98 of file UARTDriver.cpp.
write() [2/3]
size_t AP_HAL::UARTDriver::write (const uint8_t * buffer, size_t size) override virtual
Implements AP_HAL::BetterStream.
Definition at line 85 of file UARTDriver.cpp.
write() [3/3]
size_t AP_HAL::UARTDriver::write (uint8_t c) override virtual
Implements AP_HAL::BetterStream.
Definition at line 93 of file UARTDriver.cpp.
Referenced by AP_GPS_UBLOX::_send_message(), AP_GPS_NOVA::AP_GPS_NOVA(), comm_send_buffer(), AP_RCProtocol_FPort::decode_downlink(), AP_Mount_SToRM32_serial::get_angles(), AP_RangeFinder_LeddarOne::get_reading(), AP_RangeFinder_LightWareSerial::get_reading(), HALSITL::UARTDriver::handle_writing_from_writebuffer_to_device(), GCS_MAVLINK::init(), AP_GPS_Backend::inject_data(), AP_GPS_SBP::inject_data(), AP_GPS_SBP2::inject_data(), loop(), AP_GPS_SBF::mount_disk(), nmea_printf(), AP_GPS_NOVA::read(), AP_GPS_SBF::read(), AP_RangeFinder_LeddarVu8::request_distances(), AP_Beacon_Nooploop::request_setting(), AP_GPS_GSOF::requestBaud(), AP_GPS_GSOF::requestGSOF(), AP_GPS::send_blob_update(), AP_Frsky_D::send_byte(), AP_Mount_Alexmos::send_command(), AP_LTM_Telem::send_LTM(), PingProtocol::send_message(), AP_RCProtocol_SRXL2::send_on_uart(), AP_RunCam::send_packet(), AP_Hott_Telem::send_packet(), AP_Mount_Siyi::send_packet(), AP_SmartAudio::send_request(), AP_Frsky_SPort::send_sport_frame(), AP_Mount_SToRM32_serial::send_target_angles(), AP_Frsky_D::send_uint16(), AP_GPS_SBF::unmount_disk(), AP_SBusOut::update(), AP_RangeFinder_Wasp::update(), AP_RCProtocol_CRSF::write_frame(), and AP_RCProtocol_GHST::write_frame().
write_locked()
size_t AP_HAL::UARTDriver::write_locked (const uint8_t * buffer, size_t size, uint32_t key)
Definition at line 51 of file UARTDriver.cpp.
Member Data Documentation
_last_options
uint16_t AP_HAL::UARTDriver::_last_options private
Definition at line 226 of file UARTDriver.h.
Referenced by get_options(), and set_options().
lock_read_key
uint32_t AP_HAL::UARTDriver::lock_read_key protected
Definition at line 191 of file UARTDriver.h.
lock_write_key
uint32_t AP_HAL::UARTDriver::lock_write_key protected
Definition at line 190 of file UARTDriver.h.
Referenced by begin(), and is_write_locked().
The documentation for this class was generated from the following files:
libraries/AP_HAL/UARTDriver.h
libraries/AP_HAL/UARTDriver.cpp