APM:Libraries: SITL::MicroStrain Class Reference
SITL::MicroStrain Class Reference abstract
#include <SIM_MicroStrain.h>
Classes
struct MicroStrain_Packet
Public Member Functions
MicroStrain ()
void update (void)
Public Member Functions inherited from SITL::SerialDevice
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Protected Member Functions
void generate_checksum (MicroStrain_Packet &)
void send_packet (MicroStrain_Packet)
void send_imu_packet ()
virtual void send_gnss_packet ()=0
virtual void send_filter_packet ()=0
void put_float (MicroStrain_Packet &, float)
void put_double (MicroStrain_Packet &, double)
void put_int (MicroStrain_Packet &, uint16_t)
Protected Member Functions inherited from SITL::SerialDevice
bool init_sitl_pointer () WARN_IF_UNUSED
Static Protected Member Functions
static void simulation_timeval (struct timeval *tv)
Protected Attributes
uint32_t last_imu_pkt_ms
uint32_t last_gnss_pkt_ms
uint32_t last_filter_pkt_ms
uint64_t start_us
Protected Attributes inherited from SITL::SerialDevice
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Detailed Description
Definition at line 20 of file SIM_MicroStrain.h.
Constructor & Destructor Documentation
MicroStrain()
MicroStrain::MicroStrain ()
Definition at line 27 of file SIM_MicroStrain.cpp.
Member Function Documentation
generate_checksum()
void MicroStrain::generate_checksum (MicroStrain_Packet & packet) protected
Definition at line 48 of file SIM_MicroStrain.cpp.
Referenced by send_packet().
put_double()
void MicroStrain::put_double (MicroStrain_Packet & packet, double d) protected
Definition at line 292 of file SIM_MicroStrain.cpp.
Referenced by SITL::MicroStrain5::send_filter_packet(), SITL::MicroStrain7::send_filter_packet(), SITL::MicroStrain5::send_gnss_packet(), and SITL::MicroStrain7::send_gnss_packet().
put_float()
void MicroStrain::put_float (MicroStrain_Packet & packet, float f) protected
Definition at line 284 of file SIM_MicroStrain.cpp.
Referenced by SITL::MicroStrain5::send_filter_packet(), SITL::MicroStrain7::send_filter_packet(), SITL::MicroStrain5::send_gnss_packet(), SITL::MicroStrain7::send_gnss_packet(), and send_imu_packet().
put_int()
void MicroStrain::put_int (MicroStrain_Packet & packet, uint16_t t) protected
Definition at line 300 of file SIM_MicroStrain.cpp.
Referenced by SITL::MicroStrain5::send_filter_packet(), SITL::MicroStrain7::send_filter_packet(), SITL::MicroStrain5::send_gnss_packet(), and SITL::MicroStrain7::send_gnss_packet().
send_filter_packet()
virtual void SITL::MicroStrain::send_filter_packet () protected pure virtual
Implemented in SITL::MicroStrain5, and SITL::MicroStrain7.
Referenced by update().
send_gnss_packet()
virtual void SITL::MicroStrain::send_gnss_packet () protected pure virtual
Implemented in SITL::MicroStrain5, and SITL::MicroStrain7.
Referenced by update().
send_imu_packet()
void MicroStrain::send_imu_packet (void) protected
Definition at line 77 of file SIM_MicroStrain.cpp.
Referenced by update().
send_packet()
void MicroStrain::send_packet (MicroStrain_Packet packet) protected
Definition at line 67 of file SIM_MicroStrain.cpp.
Referenced by SITL::MicroStrain5::send_filter_packet(), SITL::MicroStrain7::send_filter_packet(), SITL::MicroStrain5::send_gnss_packet(), SITL::MicroStrain7::send_gnss_packet(), and send_imu_packet().
simulation_timeval()
void MicroStrain::simulation_timeval (struct timeval * tv) static protected
Definition at line 32 of file SIM_MicroStrain.cpp.
Referenced by SITL::MicroStrain5::send_filter_packet(), SITL::MicroStrain7::send_filter_packet(), SITL::MicroStrain5::send_gnss_packet(), SITL::MicroStrain7::send_gnss_packet(), and send_imu_packet().
update()
void MicroStrain::update (void)
Definition at line 257 of file SIM_MicroStrain.cpp.
Referenced by HALSITL::SITL_State_Common::sim_update().
Member Data Documentation
last_filter_pkt_ms
uint32_t SITL::MicroStrain::last_filter_pkt_ms protected
Definition at line 41 of file SIM_MicroStrain.h.
Referenced by update().
last_gnss_pkt_ms
uint32_t SITL::MicroStrain::last_gnss_pkt_ms protected
Definition at line 40 of file SIM_MicroStrain.h.
Referenced by update().
last_imu_pkt_ms
uint32_t SITL::MicroStrain::last_imu_pkt_ms protected
Definition at line 39 of file SIM_MicroStrain.h.
Referenced by update().
start_us
uint64_t SITL::MicroStrain::start_us protected
Definition at line 57 of file SIM_MicroStrain.h.
Referenced by send_imu_packet().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_MicroStrain.h
libraries/SITL/SIM_MicroStrain.cpp