APM:Libraries: AP_Airspeed Class Reference
AP_Airspeed Class Reference
#include <AP_Airspeed.h>
Classes
struct airspeed_state
Public Types
enum pitot_tube_order { PITOT_TUBE_ORDER_POSITIVE = 0 , PITOT_TUBE_ORDER_NEGATIVE = 1 , PITOT_TUBE_ORDER_AUTO = 2 }
enum OptionsMask { ON_FAILURE_AHRS_WIND_MAX_DO_DISABLE = (1<<0) , ON_FAILURE_AHRS_WIND_MAX_RECOVERY_DO_REENABLE = (1<<1) , DISABLE_VOLTAGE_CORRECTION = (1<<2) , USE_EKF_CONSISTENCY = (1<<3) }
enum airspeed_type {
TYPE_NONE =0 , TYPE_I2C_MS4525 =1 , TYPE_ANALOG =2 , TYPE_I2C_MS5525 =3 ,
TYPE_I2C_MS5525_ADDRESS_1 =4 , TYPE_I2C_MS5525_ADDRESS_2 =5 , TYPE_I2C_SDP3X =6 , TYPE_I2C_DLVR_5IN =7 ,
TYPE_UAVCAN =8 , TYPE_I2C_DLVR_10IN =9 , TYPE_I2C_DLVR_20IN =10 , TYPE_I2C_DLVR_30IN =11 ,
TYPE_I2C_DLVR_60IN =12 , TYPE_NMEA_WATER =13 , TYPE_MSP =14 , TYPE_I2C_ASP5033 =15 ,
TYPE_EXTERNAL =16 , TYPE_SITL =100
}
enum class CalibrationState { NOT_STARTED , IN_PROGRESS , SUCCESS , FAILED }
Public Member Functions
AP_Airspeed ()
void set_fixedwing_parameters (const class AP_FixedWing *_fixed_wing_parameters)
void init (void)
void allocate ()
void set_log_bit (uint32_t log_bit)
void set_calibration_enabled (bool enable)
void update (void)
void calibrate (bool in_startup)
float get_airspeed (uint8_t i) const
float get_airspeed (void) const
float get_raw_airspeed (uint8_t i) const
float get_raw_airspeed (void) const
float get_airspeed_ratio (uint8_t i) const
float get_airspeed_ratio (void) const
bool get_temperature (uint8_t i, float &temperature)
bool get_temperature (float &temperature)
void set_airspeed_ratio (uint8_t i, float ratio)
void set_airspeed_ratio (float ratio)
bool use (uint8_t i) const
bool use (void) const
void force_disable_use (bool value)
bool enabled (uint8_t i) const
bool enabled (void) const
float get_differential_pressure (uint8_t i) const
float get_differential_pressure (void) const
void update_calibration (const Vector3f &vground, int16_t max_airspeed_allowed_during_cal)
bool healthy (uint8_t i) const
bool healthy (void) const
bool all_healthy (void) const
uint32_t last_update_ms (uint8_t i) const
uint32_t last_update_ms (void) const
uint8_t get_primary (void) const
uint8_t get_num_sensors (void) const
float get_corrected_pressure (uint8_t i) const
float get_corrected_pressure (void) const
CalibrationState get_calibration_state () const
Static Public Member Functions
static AP_Airspeed * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
bool lib_enabled () const
void read (uint8_t i)
float get_pressure (uint8_t i)
float get_health_probability (uint8_t i) const
float get_health_probability (void) const
float get_test_ratio (uint8_t i) const
float get_test_ratio (void) const
void update_calibration (uint8_t i, float raw_pressure)
void update_calibration (uint8_t i, const Vector3f &vground, int16_t max_airspeed_allowed_during_cal)
void send_airspeed_calibration (const Vector3f &vg)
float get_offset (uint8_t i) const
float get_offset (void) const
void check_sensor_failures ()
void check_sensor_ahrs_wind_max_failures (uint8_t i)
void Log_Airspeed ()
bool add_backend (AP_Airspeed_Backend *backend)
void convert_per_instance ()
Private Attributes
AP_Int8 _enable
AP_Int8 primary_sensor
AP_Int8 max_speed_pcnt
AP_Int32 _options
AP_Float _wind_max
AP_Float _wind_warn
AP_Float _wind_gate
AP_Airspeed_Params param [AIRSPEED_MAX_SENSORS]
CalibrationState calibration_state [AIRSPEED_MAX_SENSORS]
struct AP_Airspeed::airspeed_state state [AIRSPEED_MAX_SENSORS]
bool calibration_enabled
bool _force_disable_use
uint8_t primary
uint8_t num_sensors
uint32_t _log_bit = -1
AP_Airspeed_Backend * sensor [AIRSPEED_MAX_SENSORS]
const AP_FixedWing * fixed_wing_parameters
Static Private Attributes
static AP_Airspeed * _singleton
Friends
class AP_Airspeed_Backend
Detailed Description
Definition at line 69 of file AP_Airspeed.h.
Member Enumeration Documentation
airspeed_type
enum AP_Airspeed::airspeed_type
Enumerator
TYPE_NONE
TYPE_I2C_MS4525
TYPE_ANALOG
TYPE_I2C_MS5525
TYPE_I2C_MS5525_ADDRESS_1
TYPE_I2C_MS5525_ADDRESS_2
TYPE_I2C_SDP3X
TYPE_I2C_DLVR_5IN
TYPE_UAVCAN
TYPE_I2C_DLVR_10IN
TYPE_I2C_DLVR_20IN
TYPE_I2C_DLVR_30IN
TYPE_I2C_DLVR_60IN
TYPE_NMEA_WATER
TYPE_MSP
TYPE_I2C_ASP5033
TYPE_EXTERNAL
TYPE_SITL
Definition at line 176 of file AP_Airspeed.h.
CalibrationState
enum class AP_Airspeed::CalibrationState strong
Enumerator
NOT_STARTED
IN_PROGRESS
SUCCESS
FAILED
Definition at line 219 of file AP_Airspeed.h.
OptionsMask
enum AP_Airspeed::OptionsMask
Enumerator
ON_FAILURE_AHRS_WIND_MAX_DO_DISABLE
ON_FAILURE_AHRS_WIND_MAX_RECOVERY_DO_REENABLE
DISABLE_VOLTAGE_CORRECTION
USE_EKF_CONSISTENCY
Definition at line 169 of file AP_Airspeed.h.
pitot_tube_order
enum AP_Airspeed::pitot_tube_order
Enumerator
PITOT_TUBE_ORDER_POSITIVE
PITOT_TUBE_ORDER_NEGATIVE
PITOT_TUBE_ORDER_AUTO
Definition at line 165 of file AP_Airspeed.h.
Constructor & Destructor Documentation
AP_Airspeed()
AP_Airspeed::AP_Airspeed ()
Definition at line 190 of file AP_Airspeed.cpp.
Member Function Documentation
add_backend()
bool AP_Airspeed::add_backend (AP_Airspeed_Backend * backend) private
Definition at line 215 of file AP_Airspeed.cpp.
all_healthy()
bool AP_Airspeed::all_healthy (void) const
Definition at line 845 of file AP_Airspeed.cpp.
Referenced by GCS::update_sensor_status_flags().
allocate()
void AP_Airspeed::allocate ()
Definition at line 332 of file AP_Airspeed.cpp.
Referenced by init().
calibrate()
void AP_Airspeed::calibrate (bool in_startup)
Definition at line 507 of file AP_Airspeed.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration_baro(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_calibration_baro(), setup(), and AP_Vehicle::setup().
check_sensor_ahrs_wind_max_failures()
void AP_Airspeed::check_sensor_ahrs_wind_max_failures (uint8_t i) private
Definition at line 23 of file AP_Airspeed_Health.cpp.
Referenced by check_sensor_failures().
check_sensor_failures()
void AP_Airspeed::check_sensor_failures () private
Definition at line 14 of file AP_Airspeed_Health.cpp.
Referenced by update().
convert_per_instance()
void AP_Airspeed::convert_per_instance () private
Definition at line 245 of file AP_Airspeed.cpp.
Referenced by init().
enabled() [1/2]
bool AP_Airspeed::enabled (uint8_t i) const
Definition at line 863 of file AP_Airspeed.cpp.
Referenced by GCS_MAVLINK::high_latency_air_temperature(), GCS_MAVLINK::send_scaled_pressure_instance(), AP_LTM_Telem::send_Sframe(), AP_Vehicle::setup(), and GCS::update_sensor_status_flags().
enabled() [2/2]
bool AP_Airspeed::enabled (void) const inline
Definition at line 139 of file AP_Airspeed.h.
Referenced by all_healthy(), calibrate(), enabled(), get_airspeed(), get_corrected_pressure(), get_differential_pressure(), get_pressure(), get_raw_airspeed(), get_temperature(), healthy(), init(), read(), update(), update_calibration(), and use().
force_disable_use()
void AP_Airspeed::force_disable_use (bool value) inline
Definition at line 133 of file AP_Airspeed.h.
Referenced by RC_Channel::do_aux_function().
get_airspeed() [1/2]
float AP_Airspeed::get_airspeed (uint8_t i) const
Definition at line 884 of file AP_Airspeed.cpp.
Referenced by AP_AHRS::_airspeed_estimate(), AP_Spektrum_Telem::calc_airspeed(), NavEKF2_core::detectFlight(), AP_OSD_Screen::draw_aspd1(), AP_OSD_Screen::draw_aspd2(), loop(), NavEKF3_core::readAirSpdData(), AP_Hott_Telem::send_EAM(), AP_LTM_Telem::send_Sframe(), AP_DAL_Airspeed::start_frame(), and GCS_MAVLINK::vfr_hud_airspeed().
get_airspeed() [2/2]
float AP_Airspeed::get_airspeed (void) const inline
Definition at line 100 of file AP_Airspeed.h.
Referenced by get_airspeed(), and update().
get_airspeed_ratio() [1/2]
float AP_Airspeed::get_airspeed_ratio (uint8_t i) const inline
Definition at line 107 of file AP_Airspeed.h.
Referenced by AP_Airspeed_Backend::get_airspeed_ratio().
get_airspeed_ratio() [2/2]
float AP_Airspeed::get_airspeed_ratio (void) const inline
Definition at line 114 of file AP_Airspeed.h.
Referenced by get_airspeed_ratio().
get_calibration_state()
AP_Airspeed::CalibrationState AP_Airspeed::get_calibration_state () const
Definition at line 587 of file AP_Airspeed.cpp.
Referenced by GCS_MAVLINK_InProgress::check_tasks().
get_corrected_pressure() [1/2]
float AP_Airspeed::get_corrected_pressure (uint8_t i) const
Definition at line 910 of file AP_Airspeed.cpp.
get_corrected_pressure() [2/2]
float AP_Airspeed::get_corrected_pressure (void) const inline
Definition at line 207 of file AP_Airspeed.h.
Referenced by get_corrected_pressure().
get_differential_pressure() [1/2]
float AP_Airspeed::get_differential_pressure (uint8_t i) const
Definition at line 902 of file AP_Airspeed.cpp.
Referenced by GCS_MAVLINK::send_scaled_pressure_instance().
get_differential_pressure() [2/2]
float AP_Airspeed::get_differential_pressure (void) const inline
Definition at line 143 of file AP_Airspeed.h.
Referenced by get_differential_pressure(), and update_calibration().
get_health_probability() [1/2]
float AP_Airspeed::get_health_probability (uint8_t i) const inline private
Definition at line 299 of file AP_Airspeed.h.
get_health_probability() [2/2]
float AP_Airspeed::get_health_probability (void) const inline private
Definition at line 302 of file AP_Airspeed.h.
Referenced by get_health_probability().
get_num_sensors()
uint8_t AP_Airspeed::get_num_sensors (void) const inline
Definition at line 201 of file AP_Airspeed.h.
Referenced by AP_DAL_Airspeed::start_frame().
get_offset() [1/2]
float AP_Airspeed::get_offset (uint8_t i) const inline private
Definition at line 318 of file AP_Airspeed.h.
get_offset() [2/2]
float AP_Airspeed::get_offset (void) const inline private
Definition at line 325 of file AP_Airspeed.h.
Referenced by get_offset(), and read().
get_pressure()
float AP_Airspeed::get_pressure (uint8_t i) private
Definition at line 481 of file AP_Airspeed.cpp.
Referenced by read().
get_primary()
uint8_t AP_Airspeed::get_primary (void) const inline
Definition at line 198 of file AP_Airspeed.h.
Referenced by AP_DAL_Airspeed::start_frame().
get_raw_airspeed() [1/2]
float AP_Airspeed::get_raw_airspeed (uint8_t i) const
Definition at line 893 of file AP_Airspeed.cpp.
get_raw_airspeed() [2/2]
float AP_Airspeed::get_raw_airspeed (void) const inline
Definition at line 104 of file AP_Airspeed.h.
Referenced by get_raw_airspeed().
get_singleton()
static AP_Airspeed * AP_Airspeed::get_singleton () inline static
Definition at line 203 of file AP_Airspeed.h.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration_baro(), AP::airspeed(), GCS_MAVLINK_InProgress::check_tasks(), AP_OSD_Screen::draw_aspd1(), AP_OSD_Screen::draw_aspd2(), AP_OSD_Screen::draw_atemp(), AP_Baro::get_external_temperature(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_calibration_baro(), GCS_MAVLINK::high_latency_air_temperature(), AP_Hott_Telem::send_EAM(), GCS_MAVLINK::send_scaled_pressure_instance(), GCS::update_sensor_status_flags(), and GCS_MAVLINK::vfr_hud_airspeed().
get_temperature() [1/2]
bool AP_Airspeed::get_temperature (float & temperature) inline
Definition at line 118 of file AP_Airspeed.h.
Referenced by get_temperature().
get_temperature() [2/2]
bool AP_Airspeed::get_temperature (uint8_t i, float & temperature)
Definition at line 494 of file AP_Airspeed.cpp.
Referenced by AP_OSD_Screen::draw_atemp(), AP_Baro::get_external_temperature(), GCS_MAVLINK::high_latency_air_temperature(), loop(), and GCS_MAVLINK::send_scaled_pressure_instance().
get_test_ratio() [1/2]
float AP_Airspeed::get_test_ratio (uint8_t i) const inline private
Definition at line 307 of file AP_Airspeed.h.
get_test_ratio() [2/2]
float AP_Airspeed::get_test_ratio (void) const inline private
Definition at line 310 of file AP_Airspeed.h.
Referenced by get_test_ratio().
healthy() [1/2]
bool AP_Airspeed::healthy (uint8_t i) const
Definition at line 874 of file AP_Airspeed.cpp.
Referenced by AP_AHRS_Backend::airspeed_sensor_enabled(), AP_AHRS_Backend::airspeed_sensor_enabled(), AP_Spektrum_Telem::calc_airspeed(), AP_OSD_Screen::draw_aspd1(), AP_OSD_Screen::draw_aspd2(), AP_OSD_Screen::draw_atemp(), AP_Baro::get_external_temperature(), loop(), NavEKF3_core::readAirSpdData(), AP_Hott_Telem::send_EAM(), AP_DAL_Airspeed::start_frame(), and GCS_MAVLINK::vfr_hud_airspeed().
healthy() [2/2]
bool AP_Airspeed::healthy (void) const inline
Definition at line 150 of file AP_Airspeed.h.
Referenced by all_healthy(), healthy(), update(), and update_calibration().
init()
void AP_Airspeed::init (void)
Definition at line 310 of file AP_Airspeed.cpp.
Referenced by add_backend(), allocate(), setup(), and AP_Vehicle::setup().
last_update_ms() [1/2]
uint32_t AP_Airspeed::last_update_ms (uint8_t i) const inline
Definition at line 156 of file AP_Airspeed.h.
Referenced by NavEKF3_core::readAirSpdData(), and AP_DAL_Airspeed::start_frame().
last_update_ms() [2/2]
uint32_t AP_Airspeed::last_update_ms (void) const inline
Definition at line 157 of file AP_Airspeed.h.
Referenced by last_update_ms().
lib_enabled()
bool AP_Airspeed::lib_enabled () const private
Definition at line 855 of file AP_Airspeed.cpp.
Referenced by calibrate(), enabled(), init(), update(), and use().
Log_Airspeed()
void AP_Airspeed::Log_Airspeed () private
Referenced by update().
read()
void AP_Airspeed::read (uint8_t i) private
Definition at line 604 of file AP_Airspeed.cpp.
Referenced by update().
send_airspeed_calibration()
void AP_Airspeed::send_airspeed_calibration (const Vector3f & vg) private
Referenced by update_calibration().
set_airspeed_ratio() [1/2]
void AP_Airspeed::set_airspeed_ratio (float ratio) inline
Definition at line 125 of file AP_Airspeed.h.
Referenced by set_airspeed_ratio().
set_airspeed_ratio() [2/2]
void AP_Airspeed::set_airspeed_ratio (uint8_t i, float ratio) inline
Definition at line 122 of file AP_Airspeed.h.
set_calibration_enabled()
void AP_Airspeed::set_calibration_enabled (bool enable) inline
Definition at line 88 of file AP_Airspeed.h.
set_fixedwing_parameters()
void AP_Airspeed::set_fixedwing_parameters (const class AP_FixedWing * _fixed_wing_parameters)
Definition at line 207 of file AP_Airspeed.cpp.
set_log_bit()
void AP_Airspeed::set_log_bit (uint32_t log_bit) inline
Definition at line 84 of file AP_Airspeed.h.
update()
void AP_Airspeed::update (void)
Definition at line 673 of file AP_Airspeed.cpp.
Referenced by loop().
update_calibration() [1/3]
void AP_Airspeed::update_calibration (const Vector3f & vground, int16_t max_airspeed_allowed_during_cal)
Definition at line 162 of file Airspeed_Calibration.cpp.
Referenced by read(), and update_calibration().
update_calibration() [2/3]
void AP_Airspeed::update_calibration (uint8_t i, const Vector3f & vground, int16_t max_airspeed_allowed_during_cal) private
Definition at line 117 of file Airspeed_Calibration.cpp.
update_calibration() [3/3]
void AP_Airspeed::update_calibration (uint8_t i, float raw_pressure) private
Definition at line 545 of file AP_Airspeed.cpp.
use() [1/2]
bool AP_Airspeed::use (uint8_t i) const
Definition at line 818 of file AP_Airspeed.cpp.
Referenced by AP_AHRS_Backend::airspeed_sensor_enabled(), AP_AHRS_Backend::airspeed_sensor_enabled(), NavEKF3_core::readAirSpdData(), AP_DAL_Airspeed::start_frame(), and GCS::update_sensor_status_flags().
use() [2/2]
bool AP_Airspeed::use (void) const inline
Definition at line 130 of file AP_Airspeed.h.
Referenced by check_sensor_ahrs_wind_max_failures(), use(), and use().
Friends And Related Symbol Documentation
AP_Airspeed_Backend
friend class AP_Airspeed_Backend friend
Definition at line 72 of file AP_Airspeed.h.
Member Data Documentation
_enable
AP_Int8 AP_Airspeed::_enable private
Definition at line 231 of file AP_Airspeed.h.
Referenced by init(), and lib_enabled().
_force_disable_use
bool AP_Airspeed::_force_disable_use private
Definition at line 285 of file AP_Airspeed.h.
Referenced by force_disable_use(), and use().
_log_bit
uint32_t AP_Airspeed::_log_bit = -1 private
Definition at line 291 of file AP_Airspeed.h.
Referenced by set_log_bit(), and update().
_options
AP_Int32 AP_Airspeed::_options private
Definition at line 236 of file AP_Airspeed.h.
Referenced by check_sensor_ahrs_wind_max_failures(), and AP_Airspeed_Backend::disable_voltage_correction().
_singleton
AP_Airspeed * AP_Airspeed::_singleton static private
Definition at line 229 of file AP_Airspeed.h.
Referenced by AP_Airspeed(), and get_singleton().
_wind_gate
AP_Float AP_Airspeed::_wind_gate private
Definition at line 239 of file AP_Airspeed.h.
Referenced by check_sensor_ahrs_wind_max_failures().
_wind_max
AP_Float AP_Airspeed::_wind_max private
Definition at line 237 of file AP_Airspeed.h.
Referenced by check_sensor_ahrs_wind_max_failures().
_wind_warn
AP_Float AP_Airspeed::_wind_warn private
Definition at line 238 of file AP_Airspeed.h.
Referenced by check_sensor_ahrs_wind_max_failures().
calibration_enabled
bool AP_Airspeed::calibration_enabled private
Definition at line 282 of file AP_Airspeed.h.
Referenced by set_calibration_enabled(), and update_calibration().
calibration_state
CalibrationState AP_Airspeed::calibration_state[AIRSPEED_MAX_SENSORS] private
Definition at line 243 of file AP_Airspeed.h.
Referenced by calibrate(), get_calibration_state(), and update_calibration().
fixed_wing_parameters
const AP_FixedWing* AP_Airspeed::fixed_wing_parameters private
Definition at line 336 of file AP_Airspeed.h.
Referenced by set_fixedwing_parameters(), and update_calibration().
max_speed_pcnt
AP_Int8 AP_Airspeed::max_speed_pcnt private
Definition at line 235 of file AP_Airspeed.h.
Referenced by update_calibration().
num_sensors
uint8_t AP_Airspeed::num_sensors private
Definition at line 289 of file AP_Airspeed.h.
Referenced by add_backend(), allocate(), and get_num_sensors().
param
AP_Airspeed_Params AP_Airspeed::param[AIRSPEED_MAX_SENSORS] private
Definition at line 241 of file AP_Airspeed.h.
Referenced by allocate(), AP_Airspeed(), AP_Airspeed_Backend::bus_is_configured(), calibrate(), check_sensor_ahrs_wind_max_failures(), enabled(), get_airspeed_ratio(), AP_Airspeed_Backend::get_bus(), get_offset(), AP_Airspeed_Backend::get_pin(), AP_Airspeed_Backend::get_psi_range(), AP_Airspeed_Backend::get_tube_order(), healthy(), init(), read(), set_airspeed_ratio(), AP_Airspeed_Backend::set_bus_id(), AP_Airspeed_Backend::set_offset(), AP_Airspeed_Backend::set_skip_cal(), AP_Airspeed_Backend::set_use(), update_calibration(), update_calibration(), and use().
primary
uint8_t AP_Airspeed::primary private
Definition at line 288 of file AP_Airspeed.h.
Referenced by enabled(), get_airspeed(), get_airspeed_ratio(), get_corrected_pressure(), get_differential_pressure(), get_health_probability(), get_offset(), get_primary(), get_raw_airspeed(), get_temperature(), get_test_ratio(), healthy(), last_update_ms(), set_airspeed_ratio(), update(), and use().
primary_sensor
AP_Int8 AP_Airspeed::primary_sensor private
Definition at line 234 of file AP_Airspeed.h.
Referenced by update().
sensor
AP_Airspeed_Backend* AP_Airspeed::sensor[AIRSPEED_MAX_SENSORS] private
Definition at line 330 of file AP_Airspeed.h.
Referenced by add_backend(), allocate(), calibrate(), get_pressure(), get_temperature(), healthy(), and read().
state
struct AP_Airspeed::airspeed_state AP_Airspeed::state[AIRSPEED_MAX_SENSORS] private
Referenced by allocate(), calibrate(), check_sensor_ahrs_wind_max_failures(), get_airspeed(), get_corrected_pressure(), get_differential_pressure(), get_health_probability(), get_pressure(), get_raw_airspeed(), get_test_ratio(), healthy(), last_update_ms(), read(), AP_Airspeed_Backend::set_use_zero_offset(), update_calibration(), and update_calibration().
var_info
const AP_Param::GroupInfo AP_Airspeed::var_info static
Definition at line 94 of file AP_Airspeed.h.
Referenced by setup().
The documentation for this class was generated from the following files:
libraries/AP_Airspeed/AP_Airspeed.h
libraries/AP_Airspeed/Airspeed_Calibration.cpp
libraries/AP_Airspeed/AP_Airspeed.cpp
libraries/AP_Airspeed/AP_Airspeed_Health.cpp