APM:Libraries: AP_Frsky_SPortParser Class Reference
AP_Frsky_SPortParser Class Reference
#include <AP_Frsky_SPortParser.h>
Public Member Functions
bool process_byte (AP_Frsky_SPort::sport_packet_t &sport_packet, const uint8_t data)
Private Types
enum class ParseState : uint8_t { IDLE , START , IN_FRAME , XOR }
Private Member Functions
bool should_process_packet (const uint8_t *packet, bool discard_duplicates)
bool get_packet (AP_Frsky_SPort::sport_packet_t &sport_packet, bool discard_duplicates)
Private Attributes
struct {
uint8_t rx_buffer_count
uint8_t rx_buffer [TELEMETRY_RX_BUFFER_SIZE]
uint8_t last_packet [SPORT_PACKET_SIZE]
ParseState state
} _parse_state
Detailed Description
Definition at line 25 of file AP_Frsky_SPortParser.h.
Member Enumeration Documentation
ParseState
enum class AP_Frsky_SPortParser::ParseState : uint8_t strong private
Enumerator
IDLE
START
IN_FRAME
XOR
Definition at line 33 of file AP_Frsky_SPortParser.h.
Member Function Documentation
get_packet()
bool AP_Frsky_SPortParser::get_packet (AP_Frsky_SPort::sport_packet_t & sport_packet, bool discard_duplicates) private
Definition at line 323 of file AP_Frsky_SPort.cpp.
Referenced by process_byte().
process_byte()
bool AP_Frsky_SPortParser::process_byte (AP_Frsky_SPort::sport_packet_t & sport_packet, const uint8_t data)
Definition at line 276 of file AP_Frsky_SPort.cpp.
Referenced by AP_Frsky_SPort_Passthrough::send().
should_process_packet()
bool AP_Frsky_SPortParser::should_process_packet (const uint8_t * packet, bool discard_duplicates) private
Definition at line 250 of file AP_Frsky_SPort.cpp.
Referenced by get_packet().
Member Data Documentation
[struct]
struct { ... } AP_Frsky_SPortParser::_parse_state
Referenced by get_packet(), process_byte(), and should_process_packet().
last_packet
uint8_t AP_Frsky_SPortParser::last_packet[SPORT_PACKET_SIZE]
Definition at line 43 of file AP_Frsky_SPortParser.h.
rx_buffer
uint8_t AP_Frsky_SPortParser::rx_buffer[TELEMETRY_RX_BUFFER_SIZE]
Definition at line 42 of file AP_Frsky_SPortParser.h.
rx_buffer_count
uint8_t AP_Frsky_SPortParser::rx_buffer_count
Definition at line 41 of file AP_Frsky_SPortParser.h.
state
ParseState AP_Frsky_SPortParser::state
Definition at line 44 of file AP_Frsky_SPortParser.h.
The documentation for this class was generated from the following files:
libraries/AP_Frsky_Telem/AP_Frsky_SPortParser.h
libraries/AP_Frsky_Telem/AP_Frsky_SPort.cpp