APM:Libraries: Linux::Scheduler Class Reference
Linux::Scheduler Class Reference
#include <Scheduler.h>
Classes
class SchedulerThread
Public Member Functions
Scheduler ()
void init () override
void delay (uint16_t ms) override
void delay_microseconds (uint16_t us) override
void register_timer_process (AP_HAL::MemberProc) override
void register_io_process (AP_HAL::MemberProc) override
bool in_main_thread () const override
void register_timer_failsafe (AP_HAL::Proc, uint32_t period_us) override
void set_system_initialized () override
bool is_system_initialized () override
void reboot (bool hold_in_bootloader) override
void stop_clock (uint64_t time_usec) override
uint64_t stopped_clock_usec () const
void microsleep (uint32_t usec)
void teardown ()
bool thread_create (AP_HAL::MemberProc, const char *name, uint32_t stack_size, priority_base base, int8_t priority) override
void set_cpu_affinity (const cpu_set_t &cpu_affinity)
Public Member Functions inherited from AP_HAL::Scheduler
Scheduler ()
virtual void delay_microseconds_boost (uint16_t us)
virtual void expect_delay_ms (uint32_t ms)
virtual bool in_expected_delay (void) const
virtual void boost_end (void)
virtual void register_delay_callback (AP_HAL::Proc, uint16_t min_time_ms)
virtual bool in_delay_callback () const
virtual void * disable_interrupts_save (void)
virtual void restore_interrupts (void *)
virtual void call_delay_cb ()
Static Public Member Functions
static Scheduler * from (AP_HAL::Scheduler *scheduler)
Private Member Functions
void init_realtime ()
void init_cpu_affinity ()
void _wait_all_threads ()
void _debug_stack ()
uint8_t calculate_thread_priority (priority_base base, int8_t priority) const
void _timer_task ()
void _io_task ()
void _rcin_task ()
void _uart_task ()
void _run_io ()
void _run_uarts ()
Private Attributes
AP_HAL::Proc _failsafe
bool _initialized
pthread_barrier_t _initialized_barrier
AP_HAL::MemberProc _timer_proc [LINUX_SCHEDULER_MAX_TIMER_PROCS]
uint8_t _num_timer_procs
volatile bool _in_timer_proc
AP_HAL::MemberProc _io_proc [LINUX_SCHEDULER_MAX_IO_PROCS]
uint8_t _num_io_procs
SchedulerThread _timer_thread {FUNCTOR_BIND_MEMBER(&Scheduler::_timer_task, void), *this}
SchedulerThread _io_thread {FUNCTOR_BIND_MEMBER(&Scheduler::_io_task, void), *this}
SchedulerThread _rcin_thread {FUNCTOR_BIND_MEMBER(&Scheduler::_rcin_task, void), *this}
SchedulerThread _uart_thread {FUNCTOR_BIND_MEMBER(&Scheduler::_uart_task, void), *this}
uint64_t _stopped_clock_usec
uint64_t _last_stack_debug_msec
pthread_t _main_ctx
Semaphore _io_semaphore
cpu_set_t _cpu_affinity
Additional Inherited Members
Public Types inherited from AP_HAL::Scheduler
enum priority_base {
PRIORITY_BOOST , PRIORITY_MAIN , PRIORITY_SPI , PRIORITY_I2C ,
PRIORITY_CAN , PRIORITY_TIMER , PRIORITY_RCOUT , PRIORITY_LED ,
PRIORITY_RCIN , PRIORITY_IO , PRIORITY_UART , PRIORITY_STORAGE ,
PRIORITY_SCRIPTING , PRIORITY_NET
}
Public Attributes inherited from AP_HAL::Scheduler
uint16_t _min_delay_cb_ms
Detailed Description
Definition at line 20 of file Scheduler.h.
Constructor & Destructor Documentation
Scheduler()
Scheduler::Scheduler ()
Definition at line 62 of file Scheduler.cpp.
Member Function Documentation
_debug_stack()
void Scheduler::_debug_stack () private
Definition at line 144 of file Scheduler.cpp.
Referenced by init().
_io_task()
void Scheduler::_io_task () private
Definition at line 297 of file Scheduler.cpp.
_rcin_task()
void Scheduler::_rcin_task () private
Definition at line 287 of file Scheduler.cpp.
_run_io()
void Scheduler::_run_io (void) private
Definition at line 262 of file Scheduler.cpp.
Referenced by _io_task().
_run_uarts()
void Scheduler::_run_uarts () private
Definition at line 279 of file Scheduler.cpp.
Referenced by _uart_task().
_timer_task()
void Scheduler::_timer_task () private
Definition at line 238 of file Scheduler.cpp.
_uart_task()
void Scheduler::_uart_task () private
Definition at line 292 of file Scheduler.cpp.
_wait_all_threads()
void Scheduler::_wait_all_threads () private
Definition at line 311 of file Scheduler.cpp.
Referenced by Linux::Scheduler::SchedulerThread::_run(), and set_system_initialized().
calculate_thread_priority()
uint8_t Scheduler::calculate_thread_priority (priority_base base, int8_t priority) const private
Definition at line 376 of file Scheduler.cpp.
Referenced by thread_create().
delay()
void Scheduler::delay (uint16_t ms) override virtual
Implements AP_HAL::Scheduler.
Definition at line 170 of file Scheduler.cpp.
delay_microseconds()
void Scheduler::delay_microseconds (uint16_t us) override virtual
Implements AP_HAL::Scheduler.
Definition at line 192 of file Scheduler.cpp.
from()
static Scheduler * Linux::Scheduler::from (AP_HAL::Scheduler * scheduler) inline static
Definition at line 24 of file Scheduler.h.
Referenced by Linux::PeriodicThread::_run(), and HAL_Linux::run().
in_main_thread()
bool Scheduler::in_main_thread () const override virtual
Implements AP_HAL::Scheduler.
Definition at line 306 of file Scheduler.cpp.
Referenced by delay().
init()
void Scheduler::init () override virtual
Implements AP_HAL::Scheduler.
Definition at line 102 of file Scheduler.cpp.
init_cpu_affinity()
void Scheduler::init_cpu_affinity () private
Definition at line 91 of file Scheduler.cpp.
Referenced by init().
init_realtime()
void Scheduler::init_realtime () private
Definition at line 68 of file Scheduler.cpp.
Referenced by init().
is_system_initialized()
bool Linux::Scheduler::is_system_initialized () inline override virtual
Implements AP_HAL::Scheduler.
Definition at line 40 of file Scheduler.h.
microsleep()
void Scheduler::microsleep (uint32_t usec)
Definition at line 162 of file Scheduler.cpp.
Referenced by Linux::PeriodicThread::_run(), delay(), and delay_microseconds().
reboot()
void Scheduler::reboot (bool hold_in_bootloader) override virtual
Implements AP_HAL::Scheduler.
Definition at line 330 of file Scheduler.cpp.
register_io_process()
void Scheduler::register_io_process (AP_HAL::MemberProc proc) override virtual
Implements AP_HAL::Scheduler.
Definition at line 217 of file Scheduler.cpp.
register_timer_failsafe()
void Scheduler::register_timer_failsafe (AP_HAL::Proc failsafe, uint32_t period_us) override virtual
Implements AP_HAL::Scheduler.
Definition at line 233 of file Scheduler.cpp.
register_timer_process()
void Scheduler::register_timer_process (AP_HAL::MemberProc proc) override virtual
Implements AP_HAL::Scheduler.
Definition at line 200 of file Scheduler.cpp.
Referenced by init().
set_cpu_affinity()
void Linux::Scheduler::set_cpu_affinity (const cpu_set_t & cpu_affinity) inline
Definition at line 61 of file Scheduler.h.
Referenced by HAL_Linux::run().
set_system_initialized()
void Scheduler::set_system_initialized () override virtual
Implements AP_HAL::Scheduler.
Definition at line 319 of file Scheduler.cpp.
stop_clock()
void Scheduler::stop_clock (uint64_t time_usec) override virtual
optional function to stop clock at a given time, used by log replay
Reimplemented from AP_HAL::Scheduler.
Definition at line 347 of file Scheduler.cpp.
stopped_clock_usec()
uint64_t Linux::Scheduler::stopped_clock_usec () const inline
Definition at line 46 of file Scheduler.h.
teardown()
void Scheduler::teardown ()
Definition at line 362 of file Scheduler.cpp.
Referenced by HAL_Linux::run().
thread_create()
bool Scheduler::thread_create (AP_HAL::MemberProc proc, const char * name, uint32_t stack_size, priority_base base, int8_t priority) override virtual
Reimplemented from AP_HAL::Scheduler.
Definition at line 409 of file Scheduler.cpp.
Member Data Documentation
_cpu_affinity
cpu_set_t Linux::Scheduler::_cpu_affinity private
Definition at line 119 of file Scheduler.h.
Referenced by init_cpu_affinity(), Scheduler(), and set_cpu_affinity().
_failsafe
AP_HAL::Proc Linux::Scheduler::_failsafe private
Definition at line 85 of file Scheduler.h.
Referenced by _timer_task(), and register_timer_failsafe().
_in_timer_proc
volatile bool Linux::Scheduler::_in_timer_proc private
Definition at line 92 of file Scheduler.h.
Referenced by _timer_task().
_initialized
bool Linux::Scheduler::_initialized private
Definition at line 87 of file Scheduler.h.
Referenced by is_system_initialized(), and set_system_initialized().
_initialized_barrier
pthread_barrier_t Linux::Scheduler::_initialized_barrier private
Definition at line 88 of file Scheduler.h.
Referenced by _wait_all_threads(), and init().
_io_proc
AP_HAL::MemberProc Linux::Scheduler::_io_proc[LINUX_SCHEDULER_MAX_IO_PROCS] private
Definition at line 94 of file Scheduler.h.
Referenced by _run_io(), and register_io_process().
_io_semaphore
Semaphore Linux::Scheduler::_io_semaphore private
Definition at line 118 of file Scheduler.h.
Referenced by _run_io().
_io_thread
SchedulerThread Linux::Scheduler::_io_thread {FUNCTOR_BIND_MEMBER(&Scheduler::_io_task, void), *this} private
Definition at line 102 of file Scheduler.h.
Referenced by _debug_stack(), and teardown().
_last_stack_debug_msec
uint64_t Linux::Scheduler::_last_stack_debug_msec private
Definition at line 115 of file Scheduler.h.
Referenced by _debug_stack().
_main_ctx
pthread_t Linux::Scheduler::_main_ctx private
Definition at line 116 of file Scheduler.h.
Referenced by in_main_thread(), and init().
_num_io_procs
uint8_t Linux::Scheduler::_num_io_procs private
Definition at line 95 of file Scheduler.h.
Referenced by _run_io(), and register_io_process().
_num_timer_procs
uint8_t Linux::Scheduler::_num_timer_procs private
Definition at line 91 of file Scheduler.h.
Referenced by _timer_task(), and register_timer_process().
_rcin_thread
SchedulerThread Linux::Scheduler::_rcin_thread {FUNCTOR_BIND_MEMBER(&Scheduler::_rcin_task, void), *this} private
Definition at line 103 of file Scheduler.h.
Referenced by _debug_stack(), and teardown().
_stopped_clock_usec
uint64_t Linux::Scheduler::_stopped_clock_usec private
Definition at line 114 of file Scheduler.h.
Referenced by delay(), delay_microseconds(), and stopped_clock_usec().
_timer_proc
AP_HAL::MemberProc Linux::Scheduler::_timer_proc[LINUX_SCHEDULER_MAX_TIMER_PROCS] private
Definition at line 90 of file Scheduler.h.
Referenced by _timer_task(), and register_timer_process().
_timer_thread
SchedulerThread Linux::Scheduler::_timer_thread {FUNCTOR_BIND_MEMBER(&Scheduler::_timer_task, void), *this} private
Definition at line 101 of file Scheduler.h.
Referenced by _debug_stack(), and teardown().
_uart_thread
SchedulerThread Linux::Scheduler::_uart_thread {FUNCTOR_BIND_MEMBER(&Scheduler::_uart_task, void), *this} private
Definition at line 104 of file Scheduler.h.
Referenced by _debug_stack(), and teardown().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Scheduler.h
libraries/AP_HAL_Linux/Scheduler.cpp