APM:Libraries: AP_InternalError Class Reference
AP_InternalError Class Reference
#include <AP_InternalError.h>
Public Types
enum class error_t : uint32_t {
logger_mapfailure = (1U << 0) , logger_missing_logstructure = (1U << 1) , logger_logwrite_missingfmt = (1U << 2) , logger_too_many_deletions = (1U << 3) ,
logger_bad_getfilename = (1U << 4) , panic = (1U << 5) , logger_flushing_without_sem = (1U << 6) , logger_bad_current_block = (1U << 7) ,
logger_blockcount_mismatch = (1U << 8) , logger_dequeue_failure = (1U << 9) , constraining_nan = (1U << 10) , watchdog_reset = (1U << 11) ,
iomcu_reset = (1U << 12) , iomcu_fail = (1U << 13) , spi_fail = (1U << 14) , main_loop_stuck = (1U << 15) ,
gcs_bad_missionprotocol_link = (1U << 16) , bitmask_range = (1U << 17) , gcs_offset = (1U << 18) , i2c_isr = (1U << 19) ,
flow_of_control = (1U << 20) , switch_full_sector_recursion = (1U << 21) , bad_rotation = (1U << 22) , stack_overflow = (1U << 23) ,
imu_reset = (1U << 24) , gpio_isr = (1U << 25) , mem_guard = (1U << 26) , dma_fail = (1U << 27) ,
params_restored = (1U << 28) , invalid_arg_or_result = (1U << 29) , __LAST__ = (1U << 30)
}
Public Member Functions
uint16_t last_error_line () const
void error (const AP_InternalError::error_t error, uint16_t line)
void errors_as_string (uint8_t *buffer, uint16_t len) const
void error_to_string (char *buffer, uint16_t len, error_t error_code) const
uint32_t count () const
uint32_t errors () const
Private Attributes
uint32_t internal_errors
uint32_t total_error_count
uint16_t last_line
Detailed Description
Definition at line 31 of file AP_InternalError.h.
Member Enumeration Documentation
error_t
enum class AP_InternalError::error_t : uint32_t strong
Enumerator
logger_mapfailure
logger_missing_logstructure
logger_logwrite_missingfmt
logger_too_many_deletions
logger_bad_getfilename
panic
logger_flushing_without_sem
logger_bad_current_block
logger_blockcount_mismatch
logger_dequeue_failure
constraining_nan
watchdog_reset
iomcu_reset
iomcu_fail
spi_fail
main_loop_stuck
gcs_bad_missionprotocol_link
bitmask_range
gcs_offset
i2c_isr
flow_of_control
switch_full_sector_recursion
bad_rotation
stack_overflow
imu_reset
gpio_isr
mem_guard
dma_fail
params_restored
invalid_arg_or_result
__LAST__
Definition at line 43 of file AP_InternalError.h.
Member Function Documentation
count()
uint32_t AP_InternalError::count () const inline
Definition at line 93 of file AP_InternalError.h.
Referenced by GCS_MAVLINK::send_sys_status().
error()
void AP_InternalError::error (const AP_InternalError::error_t error, uint16_t line)
Definition at line 17 of file AP_InternalError.cpp.
Referenced by ChibiOS::Scheduler::_monitor_thread(), ChibiOS::Scheduler::check_stack_free(), and constrain_value_line().
error_to_string()
void AP_InternalError::error_to_string (char * buffer, uint16_t len, error_t error_code) const
Definition at line 78 of file AP_InternalError.cpp.
Referenced by error().
errors()
uint32_t AP_InternalError::errors () const inline
Definition at line 96 of file AP_InternalError.h.
Referenced by AP_Vehicle::loop(), and GCS_MAVLINK::send_sys_status().
errors_as_string()
void AP_InternalError::errors_as_string (uint8_t * buffer, uint16_t len) const
Definition at line 84 of file AP_InternalError.cpp.
Referenced by AP_Arming::system_checks().
last_error_line()
uint16_t AP_InternalError::last_error_line () const inline
Definition at line 82 of file AP_InternalError.h.
Member Data Documentation
internal_errors
uint32_t AP_InternalError::internal_errors private
Definition at line 103 of file AP_InternalError.h.
Referenced by error(), errors(), and errors_as_string().
last_line
uint16_t AP_InternalError::last_line private
Definition at line 106 of file AP_InternalError.h.
Referenced by error(), and last_error_line().
total_error_count
uint32_t AP_InternalError::total_error_count private
Definition at line 105 of file AP_InternalError.h.
Referenced by count(), and error().
The documentation for this class was generated from the following files:
libraries/AP_InternalError/AP_InternalError.h
libraries/AP_InternalError/AP_InternalError.cpp