APM:Libraries: AP_BattMonitor Class Reference
AP_BattMonitor Class Reference
#include <AP_BattMonitor.h>
Classes
struct BattMonitor_State
struct cells
Public Types
enum class Failsafe : uint8_t { None = 0 , Low , Critical }
enum class Type {
NONE = 0 , ANALOG_VOLTAGE_ONLY = 3 , ANALOG_VOLTAGE_AND_CURRENT = 4 , SOLO = 5 ,
BEBOP = 6 , SMBus_Generic = 7 , UAVCAN_BatteryInfo = 8 , BLHeliESC = 9 ,
Sum = 10 , FuelFlow = 11 , FuelLevel_PWM = 12 , SUI3 = 13 ,
SUI6 = 14 , NeoDesign = 15 , MAXELL = 16 , GENERATOR_ELEC = 17 ,
GENERATOR_FUEL = 18 , Rotoye = 19 , INA2XX = 21 , LTC2946 = 22 ,
Torqeedo = 23 , FuelLevel_Analog = 24 , Analog_Volt_Synthetic_Current = 25 , INA239_SPI = 26 ,
EFI = 27 , AD7091R5 = 28 , Scripting = 29
}
Public Member Functions
FUNCTOR_TYPEDEF (battery_failsafe_handler_fn_t, void, const char *, const int8_t)
AP_BattMonitor (uint32_t log_battery_bit, battery_failsafe_handler_fn_t battery_failsafe_handler_fn, const int8_t *failsafe_priorities)
CLASS_NO_COPY (AP_BattMonitor)
uint8_t num_instances (void) const
void init ()
void read ()
Read the battery voltage and current for all batteries. Should be called at 10hz.
bool healthy (uint8_t instance) const
bool healthy () const
float voltage (uint8_t instance) const
voltage - returns battery voltage in volts
float voltage () const
float gcs_voltage (uint8_t instance) const
voltage - returns battery voltage in volts for GCS, may be resting voltage if option enabled
float gcs_voltage (void) const
float voltage_resting_estimate (uint8_t instance) const
float voltage_resting_estimate () const
bool current_amps (float &current, const uint8_t instance=AP_BATT_PRIMARY_INSTANCE) const WARN_IF_UNUSED
current_amps - returns the instantaneous current draw in amperes
bool consumed_mah (float &mah, const uint8_t instance=AP_BATT_PRIMARY_INSTANCE) const WARN_IF_UNUSED
consumed_mah - returns total current drawn since start-up in milliampere.hours
bool consumed_wh (float &wh, const uint8_t instance=AP_BATT_PRIMARY_INSTANCE) const WARN_IF_UNUSED
consumed_wh - returns total energy drawn since start-up in watt.hours
virtual bool capacity_remaining_pct (uint8_t &percentage, uint8_t instance) const WARN_IF_UNUSED
capacity_remaining_pct - returns true if the percentage is valid and writes to percentage argument
bool capacity_remaining_pct (uint8_t &percentage) const WARN_IF_UNUSED
bool time_remaining (uint32_t &seconds, const uint8_t instance=AP_BATT_PRIMARY_INSTANCE) const WARN_IF_UNUSED
time_remaining - returns remaining battery time
int32_t pack_capacity_mah (uint8_t instance) const
pack_capacity_mah - returns the capacity of the battery pack in mAh when the pack is full
int32_t pack_capacity_mah () const
bool has_failsafed (void) const
returns true if a battery failsafe has ever been triggered
int8_t get_highest_failsafe_priority (void) const
returns the highest failsafe action that has been triggered
enum Type get_type () const
get_type - returns battery monitor type
enum Type get_type (uint8_t instance) const
int32_t get_serial_number () const
get_serial_number - returns battery serial number
int32_t get_serial_number (uint8_t instance) const
bool overpower_detected () const
true when (voltage * current) > watt_max
bool overpower_detected (uint8_t instance) const
bool has_cell_voltages () const
bool has_cell_voltages (const uint8_t instance) const
const cells & get_cell_voltages () const
const cells & get_cell_voltages (const uint8_t instance) const
bool get_cell_voltage (uint8_t instance, uint8_t cell, float &voltage) const
bool get_temperature (float &temperature) const
bool get_temperature (float &temperature, const uint8_t instance) const
void MPPT_set_powered_state_to_all (const bool power_on)
void MPPT_set_powered_state (const uint8_t instance, const bool power_on)
bool get_cycle_count (uint8_t instance, uint16_t &cycles) const
float get_resistance () const
float get_resistance (uint8_t instance) const
bool arming_checks (size_t buflen, char *buffer) const
void checkPoweringOff (void)
bool reset_remaining_mask (uint16_t battery_mask, float percentage)
bool reset_remaining (uint8_t instance, float percentage)
MAV_BATTERY_CHARGE_STATE get_mavlink_charge_state (const uint8_t instance) const
uint32_t get_mavlink_fault_bitmask (const uint8_t instance) const
bool get_state_of_health_pct (uint8_t instance, uint8_t &soh_pct) const
Static Public Member Functions
static AP_BattMonitor * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo * backend_var_info [AP_BATT_MONITOR_MAX_INSTANCES]
static const struct AP_Param::GroupInfo var_info []
Protected Attributes
AP_BattMonitor_Params _params [AP_BATT_MONITOR_MAX_INSTANCES]
parameters
Private Member Functions
void convert_dynamic_param_groups (uint8_t instance)
number of monitors
Failsafe check_failsafe (const uint8_t instance)
returns the failsafe state of the battery
void check_failsafes (void)
Private Attributes
BattMonitor_State state [AP_BATT_MONITOR_MAX_INSTANCES]
AP_BattMonitor_Backend * drivers [AP_BATT_MONITOR_MAX_INSTANCES]
uint32_t _log_battery_bit
uint8_t _num_instances
battery_failsafe_handler_fn_t _battery_failsafe_handler_fn
const int8_t * _failsafe_priorities
int8_t _highest_failsafe_priority
bool _has_triggered_failsafe
Static Private Attributes
static AP_BattMonitor * _singleton
Friends
class AP_BattMonitor_Backend
class AP_BattMonitor_Analog
class AP_BattMonitor_SMBus
class AP_BattMonitor_SMBus_Solo
class AP_BattMonitor_SMBus_Generic
class AP_BattMonitor_SMBus_Maxell
class AP_BattMonitor_SMBus_Rotoye
class AP_BattMonitor_DroneCAN
class AP_BattMonitor_Sum
class AP_BattMonitor_FuelFlow
class AP_BattMonitor_FuelLevel_PWM
class AP_BattMonitor_Generator
class AP_BattMonitor_EFI
class AP_BattMonitor_INA2XX
class AP_BattMonitor_INA239
class AP_BattMonitor_LTC2946
class AP_BattMonitor_AD7091R5
class AP_BattMonitor_Torqeedo
class AP_BattMonitor_FuelLevel_Analog
class AP_BattMonitor_Synthetic_Current
class AP_BattMonitor_Scripting
Detailed Description
Definition at line 54 of file AP_BattMonitor.h.
Member Enumeration Documentation
Failsafe
enum class AP_BattMonitor::Failsafe : uint8_t strong
Enumerator
None
Low
Critical
Definition at line 82 of file AP_BattMonitor.h.
Type
enum class AP_BattMonitor::Type strong
Enumerator
NONE
ANALOG_VOLTAGE_ONLY
ANALOG_VOLTAGE_AND_CURRENT
SOLO
BEBOP
SMBus_Generic
UAVCAN_BatteryInfo
BLHeliESC
Sum
FuelFlow
FuelLevel_PWM
SUI3
SUI6
NeoDesign
MAXELL
GENERATOR_ELEC
GENERATOR_FUEL
Rotoye
INA2XX
LTC2946
Torqeedo
FuelLevel_Analog
Analog_Volt_Synthetic_Current
INA239_SPI
EFI
AD7091R5
Scripting
Definition at line 89 of file AP_BattMonitor.h.
Constructor & Destructor Documentation
AP_BattMonitor()
AP_BattMonitor::AP_BattMonitor (uint32_t log_battery_bit, battery_failsafe_handler_fn_t battery_failsafe_handler_fn, const int8_t * failsafe_priorities)
Definition at line 414 of file AP_BattMonitor.cpp.
Member Function Documentation
arming_checks()
bool AP_BattMonitor::arming_checks (size_t buflen, char * buffer) const
Definition at line 956 of file AP_BattMonitor.cpp.
Referenced by arming_checks().
capacity_remaining_pct() [1/2]
bool AP_BattMonitor::capacity_remaining_pct (uint8_t & percentage) const inline
Definition at line 207 of file AP_BattMonitor.h.
Referenced by capacity_remaining_pct().
capacity_remaining_pct() [2/2]
bool AP_BattMonitor::capacity_remaining_pct (uint8_t & percentage, uint8_t instance) const virtual
capacity_remaining_pct - returns true if the percentage is valid and writes to percentage argument
Definition at line 766 of file AP_BattMonitor.cpp.
Referenced by AP_Frsky_D::send(), and AP_Frsky_SPort::send().
check_failsafe()
Failsafe AP_BattMonitor::check_failsafe (const uint8_t instance) private
returns the failsafe state of the battery
check_failsafes()
void AP_BattMonitor::check_failsafes (void) private
Definition at line 794 of file AP_BattMonitor.cpp.
Referenced by read().
checkPoweringOff()
void AP_BattMonitor::checkPoweringOff (void)
Definition at line 971 of file AP_BattMonitor.cpp.
Referenced by read().
CLASS_NO_COPY()
AP_BattMonitor::CLASS_NO_COPY (AP_BattMonitor)
consumed_mah()
bool AP_BattMonitor::consumed_mah (float & mah, const uint8_t instance = AP_BATT_PRIMARY_INSTANCE) const
consumed_mah - returns total current drawn since start-up in milliampere.hours
Definition at line 742 of file AP_BattMonitor.cpp.
Referenced by AP_Frsky_SPort_Passthrough::calc_batt(), AP_Spektrum_Telem::calc_batt_mah(), check_failsafes(), and consumed_mah().
consumed_wh()
bool AP_BattMonitor::consumed_wh (float & wh, const uint8_t instance = AP_BATT_PRIMARY_INSTANCE) const
consumed_wh - returns total energy drawn since start-up in watt.hours
consumed_wh - returns energy consumed since start-up in Watt.hours
Definition at line 756 of file AP_BattMonitor.cpp.
convert_dynamic_param_groups()
void AP_BattMonitor::convert_dynamic_param_groups (uint8_t instance) private
number of monitors
Definition at line 603 of file AP_BattMonitor.cpp.
Referenced by init().
current_amps()
bool AP_BattMonitor::current_amps (float & current, const uint8_t instance = AP_BATT_PRIMARY_INSTANCE) const
current_amps - returns the instantaneous current draw in amperes
Definition at line 732 of file AP_BattMonitor.cpp.
Referenced by AP_Frsky_SPort_Passthrough::calc_batt(), AP_Spektrum_Telem::calc_batt_amps(), AP_Spektrum_Telem::calc_batt_mah(), AP_BattMonitor_Sum::read(), AP_Frsky_D::send(), and AP_Frsky_SPort::send().
FUNCTOR_TYPEDEF()
AP_BattMonitor::FUNCTOR_TYPEDEF (battery_failsafe_handler_fn_t , void , const char * , const int8_t)
gcs_voltage() [1/2]
float AP_BattMonitor::gcs_voltage (uint8_t instance) const
voltage - returns battery voltage in volts for GCS, may be resting voltage if option enabled
Definition at line 720 of file AP_BattMonitor.cpp.
gcs_voltage() [2/2]
float AP_BattMonitor::gcs_voltage (void) const inline
Definition at line 189 of file AP_BattMonitor.h.
Referenced by gcs_voltage().
get_cell_voltage()
bool AP_BattMonitor::get_cell_voltage (uint8_t instance, uint8_t cell, float & voltage) const
Definition at line 896 of file AP_BattMonitor.cpp.
get_cell_voltages() [1/2]
const cells & AP_BattMonitor::get_cell_voltages () const inline
Definition at line 241 of file AP_BattMonitor.h.
Referenced by get_cell_voltage(), and get_cell_voltages().
get_cell_voltages() [2/2]
const AP_BattMonitor::cells & AP_BattMonitor::get_cell_voltages (const uint8_t instance) const
Definition at line 886 of file AP_BattMonitor.cpp.
get_cycle_count()
bool AP_BattMonitor::get_cycle_count (uint8_t instance, uint16_t & cycles) const
Definition at line 948 of file AP_BattMonitor.cpp.
get_highest_failsafe_priority()
int8_t AP_BattMonitor::get_highest_failsafe_priority (void) const inline
returns the highest failsafe action that has been triggered
Definition at line 220 of file AP_BattMonitor.h.
get_mavlink_charge_state()
MAV_BATTERY_CHARGE_STATE AP_BattMonitor::get_mavlink_charge_state (const uint8_t instance) const
Definition at line 1030 of file AP_BattMonitor.cpp.
get_mavlink_fault_bitmask()
uint32_t AP_BattMonitor::get_mavlink_fault_bitmask (const uint8_t instance) const
Definition at line 1056 of file AP_BattMonitor.cpp.
Referenced by get_mavlink_charge_state().
get_resistance() [1/2]
float AP_BattMonitor::get_resistance () const inline
Definition at line 263 of file AP_BattMonitor.h.
Referenced by get_resistance().
get_resistance() [2/2]
float AP_BattMonitor::get_resistance (uint8_t instance) const inline
Definition at line 264 of file AP_BattMonitor.h.
get_serial_number() [1/2]
int32_t AP_BattMonitor::get_serial_number () const inline
get_serial_number - returns battery serial number
Definition at line 229 of file AP_BattMonitor.h.
Referenced by get_serial_number().
get_serial_number() [2/2]
int32_t AP_BattMonitor::get_serial_number (uint8_t instance) const inline
Definition at line 230 of file AP_BattMonitor.h.
get_singleton()
static AP_BattMonitor * AP_BattMonitor::get_singleton () inline static
Definition at line 127 of file AP_BattMonitor.h.
Referenced by AP::battery().
get_state_of_health_pct()
bool AP_BattMonitor::get_state_of_health_pct (uint8_t instance, uint8_t & soh_pct) const
Definition at line 1065 of file AP_BattMonitor.cpp.
get_temperature() [1/2]
bool AP_BattMonitor::get_temperature (float & temperature) const inline
Definition at line 248 of file AP_BattMonitor.h.
Referenced by AP_Spektrum_Telem::calc_batt_mah(), and get_temperature().
get_temperature() [2/2]
bool AP_BattMonitor::get_temperature (float & temperature, const uint8_t instance) const
Definition at line 913 of file AP_BattMonitor.cpp.
get_type() [1/2]
enum Type AP_BattMonitor::get_type () const inline
get_type - returns battery monitor type
Definition at line 223 of file AP_BattMonitor.h.
Referenced by get_type(), healthy(), init(), and read().
get_type() [2/2]
enum Type AP_BattMonitor::get_type (uint8_t instance) const inline
Definition at line 224 of file AP_BattMonitor.h.
has_cell_voltages() [1/2]
bool AP_BattMonitor::has_cell_voltages () const inline
Definition at line 239 of file AP_BattMonitor.h.
Referenced by get_cell_voltage(), and has_cell_voltages().
has_cell_voltages() [2/2]
bool AP_BattMonitor::has_cell_voltages (const uint8_t instance) const
Definition at line 876 of file AP_BattMonitor.cpp.
has_failsafed()
bool AP_BattMonitor::has_failsafed (void) const inline
returns true if a battery failsafe has ever been triggered
Definition at line 217 of file AP_BattMonitor.h.
healthy() [1/2]
bool AP_BattMonitor::healthy () const
Definition at line 1094 of file AP_BattMonitor.cpp.
Referenced by get_mavlink_charge_state(), and healthy().
healthy() [2/2]
bool AP_BattMonitor::healthy (uint8_t instance) const
Definition at line 694 of file AP_BattMonitor.cpp.
Referenced by AP_BattMonitor_Sum::read().
init()
void AP_BattMonitor::init ()
Definition at line 429 of file AP_BattMonitor.cpp.
MPPT_set_powered_state()
void AP_BattMonitor::MPPT_set_powered_state (const uint8_t instance, const bool power_on)
Definition at line 1084 of file AP_BattMonitor.cpp.
Referenced by MPPT_set_powered_state_to_all().
MPPT_set_powered_state_to_all()
void AP_BattMonitor::MPPT_set_powered_state_to_all (const bool power_on)
Definition at line 1074 of file AP_BattMonitor.cpp.
Referenced by RC_Channel::do_aux_function().
num_instances()
uint8_t AP_BattMonitor::num_instances (void) const inline
Definition at line 169 of file AP_BattMonitor.h.
Referenced by AP_Frsky_SPort_Passthrough::calc_param(), AP_Frsky_SPort_Passthrough::is_packet_ready(), and AP_BattMonitor_Sum::read().
overpower_detected() [1/2]
bool AP_BattMonitor::overpower_detected () const
true when (voltage * current) > watt_max
Definition at line 853 of file AP_BattMonitor.cpp.
Referenced by overpower_detected().
overpower_detected() [2/2]
bool AP_BattMonitor::overpower_detected (uint8_t instance) const
Definition at line 865 of file AP_BattMonitor.cpp.
pack_capacity_mah() [1/2]
int32_t AP_BattMonitor::pack_capacity_mah () const inline
Definition at line 214 of file AP_BattMonitor.h.
Referenced by pack_capacity_mah().
pack_capacity_mah() [2/2]
int32_t AP_BattMonitor::pack_capacity_mah (uint8_t instance) const
pack_capacity_mah - returns the capacity of the battery pack in mAh when the pack is full
Definition at line 785 of file AP_BattMonitor.cpp.
Referenced by AP_Frsky_SPort_Passthrough::calc_param().
read()
void AP_BattMonitor::read ()
Read the battery voltage and current for all batteries. Should be called at 10hz.
Definition at line 660 of file AP_BattMonitor.cpp.
reset_remaining()
bool AP_BattMonitor::reset_remaining (uint8_t instance, float percentage) inline
Definition at line 274 of file AP_BattMonitor.h.
reset_remaining_mask()
bool AP_BattMonitor::reset_remaining_mask (uint16_t battery_mask, float percentage)
Definition at line 999 of file AP_BattMonitor.cpp.
Referenced by reset_remaining().
time_remaining()
bool AP_BattMonitor::time_remaining (uint32_t & seconds, const uint8_t instance = AP_BATT_PRIMARY_INSTANCE) const
time_remaining - returns remaining battery time
Definition at line 775 of file AP_BattMonitor.cpp.
voltage() [1/2]
float AP_BattMonitor::voltage () const inline
Definition at line 185 of file AP_BattMonitor.h.
Referenced by check_failsafes(), get_cell_voltage(), and voltage().
voltage() [2/2]
float AP_BattMonitor::voltage (uint8_t instance) const
voltage - returns battery voltage in volts
Definition at line 699 of file AP_BattMonitor.cpp.
Referenced by AP_Frsky_SPort_Passthrough::calc_batt(), AP_Spektrum_Telem::calc_batt_volts(), AP_Spektrum_Telem::calc_rpm(), AP_BattMonitor_Sum::read(), AP_Frsky_D::send(), AP_Frsky_SPort::send(), and Thrust_Linearization::update_lift_max_from_batt_voltage().
voltage_resting_estimate() [1/2]
float AP_BattMonitor::voltage_resting_estimate () const inline
Definition at line 194 of file AP_BattMonitor.h.
Referenced by gcs_voltage(), and voltage_resting_estimate().
voltage_resting_estimate() [2/2]
float AP_BattMonitor::voltage_resting_estimate (uint8_t instance) const
get voltage with sag removed (based on battery current draw and resistance) this will always be greater than or equal to the raw voltage
Definition at line 710 of file AP_BattMonitor.cpp.
Referenced by Thrust_Linearization::update_lift_max_from_batt_voltage().
Friends And Related Symbol Documentation
AP_BattMonitor_AD7091R5
friend class AP_BattMonitor_AD7091R5 friend
Definition at line 72 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_Analog
friend class AP_BattMonitor_Analog friend
Definition at line 57 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_Backend
friend class AP_BattMonitor_Backend friend
Definition at line 56 of file AP_BattMonitor.h.
AP_BattMonitor_DroneCAN
friend class AP_BattMonitor_DroneCAN friend
Definition at line 63 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_EFI
friend class AP_BattMonitor_EFI friend
Definition at line 68 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_FuelFlow
friend class AP_BattMonitor_FuelFlow friend
Definition at line 65 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_FuelLevel_Analog
friend class AP_BattMonitor_FuelLevel_Analog friend
Definition at line 75 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_FuelLevel_PWM
friend class AP_BattMonitor_FuelLevel_PWM friend
Definition at line 66 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_Generator
friend class AP_BattMonitor_Generator friend
Definition at line 67 of file AP_BattMonitor.h.
AP_BattMonitor_INA239
friend class AP_BattMonitor_INA239 friend
Definition at line 70 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_INA2XX
friend class AP_BattMonitor_INA2XX friend
Definition at line 69 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_LTC2946
friend class AP_BattMonitor_LTC2946 friend
Definition at line 71 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_Scripting
friend class AP_BattMonitor_Scripting friend
Definition at line 77 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_SMBus
friend class AP_BattMonitor_SMBus friend
Definition at line 58 of file AP_BattMonitor.h.
AP_BattMonitor_SMBus_Generic
friend class AP_BattMonitor_SMBus_Generic friend
Definition at line 60 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_SMBus_Maxell
friend class AP_BattMonitor_SMBus_Maxell friend
Definition at line 61 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_SMBus_Rotoye
friend class AP_BattMonitor_SMBus_Rotoye friend
Definition at line 62 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_SMBus_Solo
friend class AP_BattMonitor_SMBus_Solo friend
Definition at line 59 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_Sum
friend class AP_BattMonitor_Sum friend
Definition at line 64 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_Synthetic_Current
friend class AP_BattMonitor_Synthetic_Current friend
Definition at line 76 of file AP_BattMonitor.h.
Referenced by init().
AP_BattMonitor_Torqeedo
friend class AP_BattMonitor_Torqeedo friend
Definition at line 74 of file AP_BattMonitor.h.
Referenced by init().
Member Data Documentation
_battery_failsafe_handler_fn
battery_failsafe_handler_fn_t AP_BattMonitor::_battery_failsafe_handler_fn private
Definition at line 310 of file AP_BattMonitor.h.
Referenced by check_failsafes().
_failsafe_priorities
const int8_t* AP_BattMonitor::_failsafe_priorities private
Definition at line 311 of file AP_BattMonitor.h.
Referenced by check_failsafes().
_has_triggered_failsafe
bool AP_BattMonitor::_has_triggered_failsafe private
Definition at line 314 of file AP_BattMonitor.h.
Referenced by check_failsafes(), has_failsafed(), and reset_remaining_mask().
_highest_failsafe_priority
int8_t AP_BattMonitor::_highest_failsafe_priority private
Definition at line 313 of file AP_BattMonitor.h.
Referenced by check_failsafes(), get_highest_failsafe_priority(), init(), and reset_remaining_mask().
_log_battery_bit
uint32_t AP_BattMonitor::_log_battery_bit private
Definition at line 301 of file AP_BattMonitor.h.
Referenced by read().
_num_instances
uint8_t AP_BattMonitor::_num_instances private
Definition at line 302 of file AP_BattMonitor.h.
Referenced by arming_checks(), capacity_remaining_pct(), check_failsafes(), checkPoweringOff(), consumed_mah(), consumed_wh(), current_amps(), gcs_voltage(), get_cycle_count(), get_mavlink_charge_state(), get_mavlink_fault_bitmask(), get_state_of_health_pct(), get_temperature(), has_cell_voltages(), healthy(), healthy(), init(), MPPT_set_powered_state(), MPPT_set_powered_state_to_all(), num_instances(), overpower_detected(), overpower_detected(), read(), reset_remaining_mask(), time_remaining(), voltage(), and voltage_resting_estimate().
_params
AP_BattMonitor_Params AP_BattMonitor::_params[AP_BATT_MONITOR_MAX_INSTANCES] protected
parameters
Definition at line 294 of file AP_BattMonitor.h.
Referenced by check_failsafes(), get_serial_number(), get_type(), init(), overpower_detected(), and pack_capacity_mah().
_singleton
AP_BattMonitor * AP_BattMonitor::_singleton static private
Definition at line 297 of file AP_BattMonitor.h.
Referenced by AP_BattMonitor(), and get_singleton().
backend_var_info
const AP_Param::GroupInfo * AP_BattMonitor::backend_var_info static
Definition at line 166 of file AP_BattMonitor.h.
Referenced by init().
drivers
AP_BattMonitor_Backend* AP_BattMonitor::drivers[AP_BATT_MONITOR_MAX_INSTANCES] private
Definition at line 300 of file AP_BattMonitor.h.
Referenced by arming_checks(), capacity_remaining_pct(), check_failsafes(), consumed_mah(), consumed_wh(), current_amps(), gcs_voltage(), get_cycle_count(), get_mavlink_fault_bitmask(), get_state_of_health_pct(), get_temperature(), has_cell_voltages(), init(), MPPT_set_powered_state(), read(), reset_remaining_mask(), time_remaining(), and voltage_resting_estimate().
state
BattMonitor_State AP_BattMonitor::state[AP_BATT_MONITOR_MAX_INSTANCES] private
Definition at line 299 of file AP_BattMonitor.h.
Referenced by check_failsafes(), checkPoweringOff(), consumed_mah(), consumed_wh(), current_amps(), gcs_voltage(), get_cell_voltages(), get_mavlink_charge_state(), get_resistance(), healthy(), init(), overpower_detected(), reset_remaining_mask(), time_remaining(), and voltage().
var_info
const AP_Param::GroupInfo AP_BattMonitor::var_info static
Definition at line 46 of file AP_BattMonitor.h.
The documentation for this class was generated from the following files:
libraries/AP_BattMonitor/AP_BattMonitor.h
libraries/AP_BattMonitor/AP_BattMonitor.cpp