APM:Libraries: AP_OpticalFlow Class Reference
AP_OpticalFlow Class Reference
#include <AP_OpticalFlow.h>
Classes
struct AP_OpticalFlow_Flags
struct OpticalFlow_state
Public Types
enum class Type {
NONE = 0 , PX4FLOW = 1 , PIXART = 2 , BEBOP = 3 ,
CXOF = 4 , MAVLINK = 5 , UAVCAN = 6 , MSP = 7 ,
UPFLOW = 8 , SITL = 10
}
Public Member Functions
AP_OpticalFlow ()
CLASS_NO_COPY (AP_OpticalFlow)
void init (uint32_t log_bit)
bool enabled () const
bool healthy () const
void update (void)
void handle_msg (const mavlink_message_t &msg)
uint8_t quality () const
const Vector2f & flowRate () const
const Vector2f & bodyRate () const
uint32_t last_update () const
float get_height_override () const
const Vector3f & get_pos_offset (void) const
void start_calibration ()
void stop_calibration ()
Static Public Member Functions
static AP_OpticalFlow * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void update_state (const OpticalFlow_state &state)
void Log_Write_Optflow ()
Private Attributes
OpticalFlow_backend * backend
struct AP_OpticalFlow::AP_OpticalFlow_Flags _flags
AP_Enum< Type > _type
AP_Int16 _flowScalerX
AP_Int16 _flowScalerY
AP_Int16 _yawAngle_cd
AP_Vector3f _pos_offset
AP_Int8 _address
AP_Float _height_override
struct OpticalFlow_state _state
uint32_t _last_update_ms
uint32_t _log_bit = -1
AP_OpticalFlow_Calibrator * _calibrator
Static Private Attributes
static AP_OpticalFlow * _singleton
Friends
class OpticalFlow_backend
Detailed Description
Definition at line 32 of file AP_OpticalFlow.h.
Member Enumeration Documentation
Type
enum class AP_OpticalFlow::Type strong
Enumerator
NONE
PX4FLOW
PIXART
BEBOP
CXOF
MAVLINK
UAVCAN
MSP
UPFLOW
SITL
Definition at line 46 of file AP_OpticalFlow.h.
Constructor & Destructor Documentation
AP_OpticalFlow()
AP_OpticalFlow::AP_OpticalFlow ()
Definition at line 110 of file AP_OpticalFlow.cpp.
Member Function Documentation
bodyRate()
const Vector2f & AP_OpticalFlow::bodyRate () const inline
Definition at line 86 of file AP_OpticalFlow.h.
CLASS_NO_COPY()
AP_OpticalFlow::CLASS_NO_COPY (AP_OpticalFlow)
enabled()
bool AP_OpticalFlow::enabled () const inline
Definition at line 63 of file AP_OpticalFlow.h.
Referenced by handle_msg(), AP_DAL::start_frame(), update(), and GCS::update_sensor_status_flags().
flowRate()
const Vector2f & AP_OpticalFlow::flowRate () const inline
Definition at line 83 of file AP_OpticalFlow.h.
get_height_override()
float AP_OpticalFlow::get_height_override () const inline
Definition at line 92 of file AP_OpticalFlow.h.
Referenced by update_state().
get_pos_offset()
const Vector3f & AP_OpticalFlow::get_pos_offset (void) const inline
Definition at line 101 of file AP_OpticalFlow.h.
Referenced by update_state().
get_singleton()
static AP_OpticalFlow * AP_OpticalFlow::get_singleton () inline static
Definition at line 42 of file AP_OpticalFlow.h.
Referenced by AP::opticalflow().
handle_msg()
void AP_OpticalFlow::handle_msg (const mavlink_message_t & msg)
Definition at line 215 of file AP_OpticalFlow.cpp.
healthy()
bool AP_OpticalFlow::healthy () const inline
Definition at line 66 of file AP_OpticalFlow.h.
Referenced by setup(), and GCS::update_sensor_status_flags().
init()
void AP_OpticalFlow::init (uint32_t log_bit)
Definition at line 117 of file AP_OpticalFlow.cpp.
Referenced by setup().
last_update()
uint32_t AP_OpticalFlow::last_update () const inline
Definition at line 89 of file AP_OpticalFlow.h.
Log_Write_Optflow()
void AP_OpticalFlow::Log_Write_Optflow () private
Referenced by update_state().
quality()
uint8_t AP_OpticalFlow::quality () const inline
Definition at line 80 of file AP_OpticalFlow.h.
Referenced by update_state().
start_calibration()
void AP_OpticalFlow::start_calibration ()
Definition at line 243 of file AP_OpticalFlow.cpp.
Referenced by RC_Channel::do_aux_function().
stop_calibration()
void AP_OpticalFlow::stop_calibration ()
Definition at line 258 of file AP_OpticalFlow.cpp.
Referenced by RC_Channel::do_aux_function().
update()
void AP_OpticalFlow::update (void)
Definition at line 184 of file AP_OpticalFlow.cpp.
update_state()
void AP_OpticalFlow::update_state (const OpticalFlow_state & state) private
Definition at line 266 of file AP_OpticalFlow.cpp.
Referenced by OpticalFlow_backend::_update_frontend().
Friends And Related Symbol Documentation
OpticalFlow_backend
friend class OpticalFlow_backend friend
Definition at line 34 of file AP_OpticalFlow.h.
Member Data Documentation
_address
AP_Int8 AP_OpticalFlow::_address private
Definition at line 128 of file AP_OpticalFlow.h.
Referenced by OpticalFlow_backend::get_address().
_calibrator
AP_OpticalFlow_Calibrator* AP_OpticalFlow::_calibrator private
Definition at line 144 of file AP_OpticalFlow.h.
Referenced by start_calibration(), stop_calibration(), and update().
_flags
struct AP_OpticalFlow::AP_OpticalFlow_Flags AP_OpticalFlow::_flags private
Referenced by healthy(), and update().
_flowScalerX
AP_Int16 AP_OpticalFlow::_flowScalerX private
Definition at line 124 of file AP_OpticalFlow.h.
Referenced by OpticalFlow_backend::_flowScaler(), and update().
_flowScalerY
AP_Int16 AP_OpticalFlow::_flowScalerY private
Definition at line 125 of file AP_OpticalFlow.h.
Referenced by OpticalFlow_backend::_flowScaler(), and update().
_height_override
AP_Float AP_OpticalFlow::_height_override private
Definition at line 129 of file AP_OpticalFlow.h.
Referenced by get_height_override().
_last_update_ms
uint32_t AP_OpticalFlow::_last_update_ms private
Definition at line 137 of file AP_OpticalFlow.h.
Referenced by last_update(), update(), and update_state().
_log_bit
uint32_t AP_OpticalFlow::_log_bit = -1 private
Definition at line 140 of file AP_OpticalFlow.h.
Referenced by init().
_pos_offset
AP_Vector3f AP_OpticalFlow::_pos_offset private
Definition at line 127 of file AP_OpticalFlow.h.
Referenced by get_pos_offset().
_singleton
AP_OpticalFlow * AP_OpticalFlow::_singleton static private
Definition at line 114 of file AP_OpticalFlow.h.
Referenced by AP_OpticalFlow(), and get_singleton().
_state
struct OpticalFlow_state AP_OpticalFlow::_state private
Definition at line 135 of file AP_OpticalFlow.h.
Referenced by bodyRate(), flowRate(), quality(), and update_state().
_type
AP_Enum<Type> AP_OpticalFlow::_type private
Definition at line 123 of file AP_OpticalFlow.h.
Referenced by enabled(), and init().
_yawAngle_cd
AP_Int16 AP_OpticalFlow::_yawAngle_cd private
Definition at line 126 of file AP_OpticalFlow.h.
Referenced by OpticalFlow_backend::_yawAngleRad().
backend
OpticalFlow_backend* AP_OpticalFlow::backend private
Definition at line 116 of file AP_OpticalFlow.h.
Referenced by handle_msg(), healthy(), init(), and update().
var_info
const AP_Param::GroupInfo AP_OpticalFlow::var_info static
Definition at line 31 of file AP_OpticalFlow.h.
The documentation for this class was generated from the following files:
libraries/AP_OpticalFlow/AP_OpticalFlow.h
libraries/AP_OpticalFlow/AP_OpticalFlow.cpp