APM:Libraries: AP_RunCam Class Reference
AP_RunCam Class Reference
Object managing a RunCam device.
#include <AP_RunCam.h>
Classes
struct Menu
class Request
Public Types
enum class DeviceType {
Disabled = 0 , SplitMicro = 1 , Split = 2 , Split4k = 3 ,
Hybrid = 4 , Run24k = 5
}
enum class ControlOperation {
RCDEVICE_PROTOCOL_SIMULATE_WIFI_BTN = 0x00 , RCDEVICE_PROTOCOL_SIMULATE_POWER_BTN = 0x01 , RCDEVICE_PROTOCOL_CHANGE_MODE = 0x02 , RCDEVICE_PROTOCOL_CHANGE_START_RECORDING = 0x03 ,
RCDEVICE_PROTOCOL_CHANGE_STOP_RECORDING = 0x04 , UNKNOWN_CAMERA_OPERATION = 0xFF
}
enum class ControlOption {
STICK_YAW_RIGHT = (1 << 0) , STICK_ROLL_RIGHT = (1 << 1) , THREE_POS_SWITCH = (1 << 2) , TWO_POS_SWITCH = (1 << 3) ,
VIDEO_RECORDING_AT_BOOT = (1 << 4)
}
Public Member Functions
AP_RunCam ()
CLASS_NO_COPY (AP_RunCam)
void init ()
bool simulate_camera_button (const ControlOperation operation, const uint32_t transition_timeout=RUNCAM_DEFAULT_BUTTON_PRESS_DELAY)
void start_recording ()
void stop_recording ()
void enter_osd ()
void exit_osd ()
void osd_option ()
void update ()
bool pre_arm_check (char *failure_msg, const uint8_t failure_msg_len) const
Static Public Member Functions
static AP_RunCam * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
enum class Feature {
RCDEVICE_PROTOCOL_FEATURE_SIMULATE_POWER_BUTTON = (1 << 0) , RCDEVICE_PROTOCOL_FEATURE_SIMULATE_WIFI_BUTTON = (1 << 1) , RCDEVICE_PROTOCOL_FEATURE_CHANGE_MODE = (1 << 2) , RCDEVICE_PROTOCOL_FEATURE_SIMULATE_5_KEY_OSD_CABLE = (1 << 3) ,
RCDEVICE_PROTOCOL_FEATURE_DEVICE_SETTINGS_ACCESS = (1 << 4) , RCDEVICE_PROTOCOL_FEATURE_DISPLAY_PORT = (1 << 5) , RCDEVICE_PROTOCOL_FEATURE_START_RECORDING = (1 << 6) , RCDEVICE_PROTOCOL_FEATURE_STOP_RECORDING = (1 << 7) ,
FEATURES_OVERRIDE = (1 << 14)
}
enum class Command {
RCDEVICE_PROTOCOL_COMMAND_GET_DEVICE_INFO = 0x00 , RCDEVICE_PROTOCOL_COMMAND_CAMERA_CONTROL = 0x01 , RCDEVICE_PROTOCOL_COMMAND_5KEY_SIMULATION_PRESS = 0x02 , RCDEVICE_PROTOCOL_COMMAND_5KEY_SIMULATION_RELEASE = 0x03 ,
RCDEVICE_PROTOCOL_COMMAND_5KEY_CONNECTION = 0x04 , COMMAND_NONE
}
enum class ConnectionOperation { RCDEVICE_PROTOCOL_5KEY_FUNCTION_OPEN = 0x01 , RCDEVICE_PROTOCOL_5KEY_FUNCTION_CLOSE = 0x02 }
enum class SimulationOperation {
SIMULATION_NONE = 0x00 , RCDEVICE_PROTOCOL_5KEY_SIMULATION_SET = 0x01 , RCDEVICE_PROTOCOL_5KEY_SIMULATION_LEFT = 0x02 , RCDEVICE_PROTOCOL_5KEY_SIMULATION_RIGHT = 0x03 ,
RCDEVICE_PROTOCOL_5KEY_SIMULATION_UP = 0x04 , RCDEVICE_PROTOCOL_5KEY_SIMULATION_DOWN = 0x05
}
enum class ProtocolVersion { RCSPLIT_VERSION = 0x00 , VERSION_1_0 = 0x01 , UNKNOWN }
enum class RequestStatus {
NONE , PENDING , SUCCESS , INCORRECT_CRC ,
TIMEOUT
}
enum class State {
INITIALIZING , INITIALIZED , READY , VIDEO_RECORDING ,
ENTERING_MENU , IN_MENU , EXITING_MENU
}
enum class Event {
NONE , ENTER_MENU , EXIT_MENU , IN_MENU_ENTER ,
IN_MENU_RIGHT , IN_MENU_UP , IN_MENU_DOWN , IN_MENU_EXIT ,
BUTTON_RELEASE , STOP_RECORDING , START_RECORDING
}
enum class OSDOption {
NONE , ENTER , EXIT , OPTION ,
NO_OPTION
}
enum class VideoOption { NOT_RECORDING = 0 , RECORDING = 1 }
enum class ButtonState { NONE , PRESSED , RELEASED }
Private Member Functions
FUNCTOR_TYPEDEF (parse_func_t, void, const Request &)
uint8_t get_top_menu_length () const
uint8_t get_sub_menu_length (uint8_t submenu) const
void disable_osd ()
void enable_osd ()
void update_osd ()
void update_state_machine_armed ()
void update_state_machine_disarmed ()
void handle_initialized (Event ev)
void handle_ready (Event ev)
void handle_recording (Event ev)
void handle_in_menu (Event ev)
AP_RunCam::Event map_rc_input_to_event () const
void handle_2_key_simulation_process (Event ev)
void exit_2_key_osd_menu ()
void handle_5_key_simulation_process (Event ev)
void handle_5_key_simulation_response (const Request &request)
ControlOperation start_recording_command () const
ControlOperation stop_recording_command () const
void receive ()
void drain ()
void start_uart ()
void get_device_info ()
SimulationOperation map_key_to_protocol_operation (const Event ev) const
void send_5_key_OSD_cable_simulation_event (const Event key, const uint32_t transition_timeout=RUNCAM_5KEY_BUTTON_PRESS_DELAY)
void open_5_key_OSD_cable_connection (parse_func_t parseFunc)
void close_5_key_OSD_cable_connection (parse_func_t parseFunc)
void simulate_5_key_OSD_cable_button_press (const SimulationOperation operation, parse_func_t parseFunc)
void simulate_5_key_OSD_cable_button_release (parse_func_t parseFunc)
void send_request_and_waiting_response (Command commandID, uint8_t param, uint32_t timeout, uint16_t maxRetryTimes, parse_func_t parseFunc)
void send_packet (Command command, uint8_t param)
void parse_device_info (const Request &request)
bool camera_ready () const
bool has_feature (const Feature feature) const
bool has_2_key_OSD () const
bool has_5_key_OSD () const
bool is_arming_prevented () const
void simulation_OSD_cable_failed (const Request &request)
bool request_pending (uint32_t now)
Private Attributes
const uint16_t RCDEVICE_PROTOCOL_FEATURE_2_KEY_OSD
AP_Int16 _features
AP_Int32 _boot_delay_ms
AP_Int32 _button_delay_ms
AP_Int32 _mode_delay_ms
AP_Int8 _cam_type
AP_Int8 _cam_control_option
VideoOption _video_recording = VideoOption::NOT_RECORDING
ProtocolVersion _protocol_version = ProtocolVersion::UNKNOWN
AP_HAL::UARTDriver * uart
State _state = State::INITIALIZING
uint32_t _last_osd_update_ms
uint32_t _transition_start_ms
uint32_t _transition_timeout_ms
Event _last_rc_event
State _last_state = State::INITIALIZING
OSDOption _last_osd_option = OSDOption::NONE
int8_t _last_in_menu
VideoOption _last_video_recording = VideoOption::NOT_RECORDING
ButtonState _button_pressed = ButtonState::NONE
bool _waiting_device_response
OSDOption _osd_option
int8_t _in_menu
int8_t _menu_enter_level
int8_t _top_menu_pos
uint8_t _sub_menu_pos
uint8_t _recv_buf [RUNCAM_MAX_PACKET_SIZE]
class AP_RunCam::Request _pending_request
Static Private Attributes
static const uint8_t RUNCAM_NUM_SUB_MENUS = 5
static const uint8_t RUNCAM_NUM_EXPECTED_RESPONSES = 4
static const uint8_t RUNCAM_MAX_MENUS = 1
static const uint8_t RUNCAM_MAX_MENU_LENGTH = 6
static const uint8_t RUNCAM_MAX_DEVICE_TYPES = 5
static uint8_t _sub_menu_lengths [RUNCAM_NUM_SUB_MENUS]
static Menu _menus [RUNCAM_MAX_DEVICE_TYPES]
static AP_RunCam * _singleton
Detailed Description
Object managing a RunCam device.
Definition at line 46 of file AP_RunCam.h.
Member Enumeration Documentation
ButtonState
enum class AP_RunCam::ButtonState strong private
Enumerator
NONE
PRESSED
RELEASED
Definition at line 210 of file AP_RunCam.h.
Command
enum class AP_RunCam::Command strong private
Enumerator
RCDEVICE_PROTOCOL_COMMAND_GET_DEVICE_INFO
RCDEVICE_PROTOCOL_COMMAND_CAMERA_CONTROL
RCDEVICE_PROTOCOL_COMMAND_5KEY_SIMULATION_PRESS
RCDEVICE_PROTOCOL_COMMAND_5KEY_SIMULATION_RELEASE
RCDEVICE_PROTOCOL_COMMAND_5KEY_CONNECTION
COMMAND_NONE
Definition at line 132 of file AP_RunCam.h.
ConnectionOperation
enum class AP_RunCam::ConnectionOperation strong private
Enumerator
RCDEVICE_PROTOCOL_5KEY_FUNCTION_OPEN
RCDEVICE_PROTOCOL_5KEY_FUNCTION_CLOSE
Definition at line 142 of file AP_RunCam.h.
ControlOperation
enum class AP_RunCam::ControlOperation strong
Enumerator
RCDEVICE_PROTOCOL_SIMULATE_WIFI_BTN
RCDEVICE_PROTOCOL_SIMULATE_POWER_BTN
RCDEVICE_PROTOCOL_CHANGE_MODE
RCDEVICE_PROTOCOL_CHANGE_START_RECORDING
RCDEVICE_PROTOCOL_CHANGE_STOP_RECORDING
UNKNOWN_CAMERA_OPERATION
Definition at line 69 of file AP_RunCam.h.
ControlOption
enum class AP_RunCam::ControlOption strong
Enumerator
STICK_YAW_RIGHT
STICK_ROLL_RIGHT
THREE_POS_SWITCH
TWO_POS_SWITCH
VIDEO_RECORDING_AT_BOOT
Definition at line 79 of file AP_RunCam.h.
DeviceType
enum class AP_RunCam::DeviceType strong
Enumerator
Disabled
SplitMicro
Split
Split4k
Hybrid
Run24k
Definition at line 59 of file AP_RunCam.h.
Event
enum class AP_RunCam::Event strong private
Enumerator
NONE
ENTER_MENU
EXIT_MENU
IN_MENU_ENTER
IN_MENU_RIGHT
IN_MENU_UP
IN_MENU_DOWN
IN_MENU_EXIT
BUTTON_RELEASE
STOP_RECORDING
START_RECORDING
Definition at line 183 of file AP_RunCam.h.
Feature
enum class AP_RunCam::Feature strong private
Enumerator
RCDEVICE_PROTOCOL_FEATURE_SIMULATE_POWER_BUTTON
RCDEVICE_PROTOCOL_FEATURE_SIMULATE_WIFI_BUTTON
RCDEVICE_PROTOCOL_FEATURE_CHANGE_MODE
RCDEVICE_PROTOCOL_FEATURE_SIMULATE_5_KEY_OSD_CABLE
RCDEVICE_PROTOCOL_FEATURE_DEVICE_SETTINGS_ACCESS
RCDEVICE_PROTOCOL_FEATURE_DISPLAY_PORT
RCDEVICE_PROTOCOL_FEATURE_START_RECORDING
RCDEVICE_PROTOCOL_FEATURE_STOP_RECORDING
FEATURES_OVERRIDE
Definition at line 114 of file AP_RunCam.h.
OSDOption
enum class AP_RunCam::OSDOption strong private
Enumerator
NONE
ENTER
EXIT
OPTION
NO_OPTION
Definition at line 197 of file AP_RunCam.h.
ProtocolVersion
enum class AP_RunCam::ProtocolVersion strong private
Enumerator
RCSPLIT_VERSION
VERSION_1_0
UNKNOWN
Definition at line 158 of file AP_RunCam.h.
RequestStatus
enum class AP_RunCam::RequestStatus strong private
Enumerator
NONE
PENDING
SUCCESS
INCORRECT_CRC
TIMEOUT
Definition at line 165 of file AP_RunCam.h.
SimulationOperation
enum class AP_RunCam::SimulationOperation strong private
Enumerator
SIMULATION_NONE
RCDEVICE_PROTOCOL_5KEY_SIMULATION_SET
RCDEVICE_PROTOCOL_5KEY_SIMULATION_LEFT
RCDEVICE_PROTOCOL_5KEY_SIMULATION_RIGHT
RCDEVICE_PROTOCOL_5KEY_SIMULATION_UP
RCDEVICE_PROTOCOL_5KEY_SIMULATION_DOWN
Definition at line 148 of file AP_RunCam.h.
State
enum class AP_RunCam::State strong private
Enumerator
INITIALIZING
INITIALIZED
READY
VIDEO_RECORDING
ENTERING_MENU
IN_MENU
EXITING_MENU
Definition at line 173 of file AP_RunCam.h.
VideoOption
enum class AP_RunCam::VideoOption strong private
Enumerator
NOT_RECORDING
RECORDING
Definition at line 205 of file AP_RunCam.h.
Constructor & Destructor Documentation
AP_RunCam()
AP_RunCam::AP_RunCam ()
Definition at line 121 of file AP_RunCam.cpp.
Member Function Documentation
camera_ready()
bool AP_RunCam::camera_ready () const private
Definition at line 971 of file AP_RunCam.cpp.
Referenced by pre_arm_check().
CLASS_NO_COPY()
AP_RunCam::CLASS_NO_COPY (AP_RunCam)
close_5_key_OSD_cable_connection()
void AP_RunCam::close_5_key_OSD_cable_connection (parse_func_t parseFunc) private
Definition at line 879 of file AP_RunCam.cpp.
Referenced by send_5_key_OSD_cable_simulation_event().
disable_osd()
void AP_RunCam::disable_osd () inline private
Definition at line 340 of file AP_RunCam.h.
Referenced by handle_2_key_simulation_process(), and handle_5_key_simulation_process().
drain()
void AP_RunCam::drain () private
Definition at line 779 of file AP_RunCam.cpp.
Referenced by send_request_and_waiting_response().
enable_osd()
void AP_RunCam::enable_osd () inline private
Definition at line 349 of file AP_RunCam.h.
Referenced by exit_2_key_osd_menu(), and handle_5_key_simulation_process().
enter_osd()
void AP_RunCam::enter_osd ()
Definition at line 202 of file AP_RunCam.cpp.
Referenced by RC_Channel::do_aux_function_runcam_osd_control().
exit_2_key_osd_menu()
void AP_RunCam::exit_2_key_osd_menu () private
Definition at line 608 of file AP_RunCam.cpp.
Referenced by handle_2_key_simulation_process().
exit_osd()
void AP_RunCam::exit_osd ()
Definition at line 209 of file AP_RunCam.cpp.
Referenced by RC_Channel::do_aux_function_runcam_osd_control().
FUNCTOR_TYPEDEF()
AP_RunCam::FUNCTOR_TYPEDEF (parse_func_t , void , const Request &) private
get_device_info()
void AP_RunCam::get_device_info () private
Definition at line 801 of file AP_RunCam.cpp.
Referenced by init().
get_singleton()
static AP_RunCam * AP_RunCam::get_singleton () inline static
Definition at line 55 of file AP_RunCam.h.
Referenced by AP::runcam().
get_sub_menu_length()
uint8_t AP_RunCam::get_sub_menu_length (uint8_t submenu) const inline private
Definition at line 335 of file AP_RunCam.h.
Referenced by handle_2_key_simulation_process().
get_top_menu_length()
uint8_t AP_RunCam::get_top_menu_length () const inline private
Definition at line 330 of file AP_RunCam.h.
Referenced by handle_2_key_simulation_process().
handle_2_key_simulation_process()
void AP_RunCam::handle_2_key_simulation_process (Event ev) private
Definition at line 522 of file AP_RunCam.cpp.
Referenced by handle_in_menu().
handle_5_key_simulation_process()
void AP_RunCam::handle_5_key_simulation_process (Event ev) private
Definition at line 624 of file AP_RunCam.cpp.
Referenced by handle_in_menu().
handle_5_key_simulation_response()
void AP_RunCam::handle_5_key_simulation_response (const Request & request) private
Definition at line 669 of file AP_RunCam.cpp.
Referenced by send_5_key_OSD_cable_simulation_event().
handle_in_menu()
void AP_RunCam::handle_in_menu (Event ev) private
Definition at line 441 of file AP_RunCam.cpp.
Referenced by update_state_machine_disarmed().
handle_initialized()
void AP_RunCam::handle_initialized (Event ev) private
Definition at line 363 of file AP_RunCam.cpp.
Referenced by update_state_machine_disarmed().
handle_ready()
void AP_RunCam::handle_ready (Event ev) private
Definition at line 384 of file AP_RunCam.cpp.
Referenced by update_state_machine_armed(), and update_state_machine_disarmed().
handle_recording()
void AP_RunCam::handle_recording (Event ev) private
Definition at line 412 of file AP_RunCam.cpp.
Referenced by update_state_machine_armed(), and update_state_machine_disarmed().
has_2_key_OSD()
bool AP_RunCam::has_2_key_OSD () const inline private
Definition at line 420 of file AP_RunCam.h.
Referenced by handle_in_menu(), has_5_key_OSD(), and parse_device_info().
has_5_key_OSD()
bool AP_RunCam::has_5_key_OSD () const inline private
Definition at line 423 of file AP_RunCam.h.
Referenced by handle_in_menu(), map_rc_input_to_event(), and parse_device_info().
has_feature()
bool AP_RunCam::has_feature (const Feature feature) const inline private
Definition at line 418 of file AP_RunCam.h.
Referenced by exit_2_key_osd_menu(), handle_initialized(), has_5_key_OSD(), parse_device_info(), and update_state_machine_armed().
init()
void AP_RunCam::init ()
Definition at line 133 of file AP_RunCam.cpp.
Referenced by AP_Vehicle::setup().
is_arming_prevented()
bool AP_RunCam::is_arming_prevented () const inline private
Definition at line 429 of file AP_RunCam.h.
Referenced by map_rc_input_to_event(), and pre_arm_check().
map_key_to_protocol_operation()
AP_RunCam::SimulationOperation AP_RunCam::map_key_to_protocol_operation (const Event ev) const private
Definition at line 808 of file AP_RunCam.cpp.
Referenced by send_5_key_OSD_cable_simulation_event().
map_rc_input_to_event()
AP_RunCam::Event AP_RunCam::map_rc_input_to_event () const private
Definition at line 452 of file AP_RunCam.cpp.
Referenced by update_state_machine_disarmed().
open_5_key_OSD_cable_connection()
void AP_RunCam::open_5_key_OSD_cable_connection (parse_func_t parseFunc) private
Definition at line 872 of file AP_RunCam.cpp.
Referenced by send_5_key_OSD_cable_simulation_event().
osd_option()
void AP_RunCam::osd_option ()
Definition at line 216 of file AP_RunCam.cpp.
Referenced by RC_Channel::do_aux_function_runcam_control().
parse_device_info()
void AP_RunCam::parse_device_info (const Request & request) private
Definition at line 950 of file AP_RunCam.cpp.
Referenced by get_device_info().
pre_arm_check()
bool AP_RunCam::pre_arm_check (char * failure_msg, const uint8_t failure_msg_len) const
Definition at line 239 of file AP_RunCam.cpp.
receive()
void AP_RunCam::receive () private
Definition at line 732 of file AP_RunCam.cpp.
Referenced by update().
request_pending()
bool AP_RunCam::request_pending (uint32_t now) private
Definition at line 992 of file AP_RunCam.cpp.
Referenced by receive().
send_5_key_OSD_cable_simulation_event()
void AP_RunCam::send_5_key_OSD_cable_simulation_event (const Event key, const uint32_t transition_timeout = RUNCAM_5KEY_BUTTON_PRESS_DELAY) private
Definition at line 839 of file AP_RunCam.cpp.
Referenced by handle_5_key_simulation_process().
send_packet()
void AP_RunCam::send_packet (Command command, uint8_t param) private
Definition at line 919 of file AP_RunCam.cpp.
Referenced by request_pending(), send_request_and_waiting_response(), and simulate_camera_button().
send_request_and_waiting_response()
void AP_RunCam::send_request_and_waiting_response (Command commandID, uint8_t param, uint32_t timeout, uint16_t maxRetryTimes, parse_func_t parseFunc) private
Definition at line 907 of file AP_RunCam.cpp.
Referenced by close_5_key_OSD_cable_connection(), get_device_info(), open_5_key_OSD_cable_connection(), simulate_5_key_OSD_cable_button_press(), and simulate_5_key_OSD_cable_button_release().
simulate_5_key_OSD_cable_button_press()
void AP_RunCam::simulate_5_key_OSD_cable_button_press (const SimulationOperation operation, parse_func_t parseFunc) private
Definition at line 886 of file AP_RunCam.cpp.
Referenced by send_5_key_OSD_cable_simulation_event().
simulate_5_key_OSD_cable_button_release()
void AP_RunCam::simulate_5_key_OSD_cable_button_release (parse_func_t parseFunc) private
Definition at line 898 of file AP_RunCam.cpp.
Referenced by send_5_key_OSD_cable_simulation_event().
simulate_camera_button()
bool AP_RunCam::simulate_camera_button (const ControlOperation operation, const uint32_t transition_timeout = RUNCAM_DEFAULT_BUTTON_PRESS_DELAY)
Definition at line 174 of file AP_RunCam.cpp.
Referenced by exit_2_key_osd_menu(), handle_2_key_simulation_process(), handle_initialized(), handle_ready(), and handle_recording().
simulation_OSD_cable_failed()
void AP_RunCam::simulation_OSD_cable_failed (const Request & request) private
Definition at line 980 of file AP_RunCam.cpp.
Referenced by handle_5_key_simulation_response().
start_recording()
void AP_RunCam::start_recording ()
Definition at line 188 of file AP_RunCam.cpp.
Referenced by RC_Channel::do_aux_function_runcam_control().
start_recording_command()
AP_RunCam::ControlOperation AP_RunCam::start_recording_command () const private
Definition at line 714 of file AP_RunCam.cpp.
Referenced by exit_2_key_osd_menu(), handle_initialized(), and handle_ready().
start_uart()
void AP_RunCam::start_uart () private
Definition at line 789 of file AP_RunCam.cpp.
Referenced by init(), and request_pending().
stop_recording()
void AP_RunCam::stop_recording ()
Definition at line 195 of file AP_RunCam.cpp.
Referenced by RC_Channel::do_aux_function_runcam_control().
stop_recording_command()
AP_RunCam::ControlOperation AP_RunCam::stop_recording_command () const private
Definition at line 723 of file AP_RunCam.cpp.
Referenced by handle_initialized(), and handle_recording().
update()
void AP_RunCam::update ()
Definition at line 222 of file AP_RunCam.cpp.
update_osd()
void AP_RunCam::update_osd () private
Definition at line 263 of file AP_RunCam.cpp.
Referenced by update().
update_state_machine_armed()
void AP_RunCam::update_state_machine_armed () private
Definition at line 285 of file AP_RunCam.cpp.
Referenced by update_osd().
update_state_machine_disarmed()
void AP_RunCam::update_state_machine_disarmed () private
Definition at line 312 of file AP_RunCam.cpp.
Referenced by update_osd().
Member Data Documentation
_boot_delay_ms
AP_Int32 AP_RunCam::_boot_delay_ms private
Definition at line 225 of file AP_RunCam.h.
Referenced by init().
_button_delay_ms
AP_Int32 AP_RunCam::_button_delay_ms private
Definition at line 227 of file AP_RunCam.h.
Referenced by handle_2_key_simulation_process().
_button_pressed
ButtonState AP_RunCam::_button_pressed = ButtonState::NONE private
Definition at line 256 of file AP_RunCam.h.
Referenced by handle_5_key_simulation_process(), handle_5_key_simulation_response(), map_rc_input_to_event(), simulate_5_key_OSD_cable_button_press(), and simulate_5_key_OSD_cable_button_release().
_cam_control_option
AP_Int8 AP_RunCam::_cam_control_option private
Definition at line 233 of file AP_RunCam.h.
Referenced by AP_RunCam(), handle_initialized(), handle_ready(), handle_recording(), map_rc_input_to_event(), and parse_device_info().
_cam_type
AP_Int8 AP_RunCam::_cam_type private
Definition at line 231 of file AP_RunCam.h.
Referenced by AP_RunCam(), get_sub_menu_length(), get_top_menu_length(), handle_2_key_simulation_process(), init(), start_recording_command(), stop_recording_command(), and update().
_features
AP_Int16 AP_RunCam::_features private
Definition at line 223 of file AP_RunCam.h.
Referenced by has_2_key_OSD(), has_feature(), and parse_device_info().
_in_menu
int8_t AP_RunCam::_in_menu private
Definition at line 262 of file AP_RunCam.h.
Referenced by exit_2_key_osd_menu(), handle_2_key_simulation_process(), handle_5_key_simulation_process(), init(), is_arming_prevented(), and update_state_machine_disarmed().
_last_in_menu
int8_t AP_RunCam::_last_in_menu private
Definition at line 253 of file AP_RunCam.h.
Referenced by update_state_machine_disarmed().
_last_osd_option
OSDOption AP_RunCam::_last_osd_option = OSDOption::NONE private
Definition at line 252 of file AP_RunCam.h.
Referenced by map_rc_input_to_event(), and update_state_machine_disarmed().
_last_osd_update_ms
uint32_t AP_RunCam::_last_osd_update_ms private
Definition at line 244 of file AP_RunCam.h.
Referenced by update().
_last_rc_event
Event AP_RunCam::_last_rc_event private
Definition at line 250 of file AP_RunCam.h.
Referenced by update_state_machine_disarmed().
_last_state
State AP_RunCam::_last_state = State::INITIALIZING private
Definition at line 251 of file AP_RunCam.h.
Referenced by update_state_machine_disarmed().
_last_video_recording
VideoOption AP_RunCam::_last_video_recording = VideoOption::NOT_RECORDING private
Definition at line 254 of file AP_RunCam.h.
Referenced by map_rc_input_to_event(), and update_state_machine_disarmed().
_menu_enter_level
int8_t AP_RunCam::_menu_enter_level private
Definition at line 264 of file AP_RunCam.h.
Referenced by exit_2_key_osd_menu(), handle_2_key_simulation_process(), init(), and is_arming_prevented().
_menus
AP_RunCam::Menu AP_RunCam::_menus static private
Initial value:
= {
    { 6, { 5, 8, 3, 3, 7 }},
    { 0, { 0 }},
    { 6, { 4, 10, 3, 3, 7 }},
    { 1, { 0 }},
    { 6, { 3, 10, 2, 2, 8 }},
}
Definition at line 111 of file AP_RunCam.h.
Referenced by get_sub_menu_length(), and get_top_menu_length().
_mode_delay_ms
AP_Int32 AP_RunCam::_mode_delay_ms private
Definition at line 229 of file AP_RunCam.h.
Referenced by exit_2_key_osd_menu(), handle_2_key_simulation_process(), handle_initialized(), handle_ready(), and handle_recording().
_osd_option
OSDOption AP_RunCam::_osd_option private
Definition at line 260 of file AP_RunCam.h.
Referenced by enter_osd(), exit_osd(), handle_2_key_simulation_process(), handle_5_key_simulation_process(), map_rc_input_to_event(), osd_option(), parse_device_info(), start_recording(), stop_recording(), and update_state_machine_disarmed().
_pending_request
class AP_RunCam::Request AP_RunCam::_pending_request private
Referenced by receive(), request_pending(), and send_request_and_waiting_response().
_protocol_version
ProtocolVersion AP_RunCam::_protocol_version = ProtocolVersion::UNKNOWN private
Definition at line 238 of file AP_RunCam.h.
Referenced by parse_device_info(), and simulate_camera_button().
_recv_buf
uint8_t AP_RunCam::_recv_buf[RUNCAM_MAX_PACKET_SIZE] private
Definition at line 272 of file AP_RunCam.h.
Referenced by AP_RunCam::Request::get_crc().
_singleton
AP_RunCam * AP_RunCam::_singleton static private
Definition at line 435 of file AP_RunCam.h.
Referenced by AP_RunCam(), and get_singleton().
_state
State AP_RunCam::_state = State::INITIALIZING private
Definition at line 242 of file AP_RunCam.h.
Referenced by camera_ready(), enter_osd(), exit_2_key_osd_menu(), exit_osd(), handle_2_key_simulation_process(), handle_5_key_simulation_response(), handle_initialized(), handle_ready(), handle_recording(), parse_device_info(), start_recording(), stop_recording(), update_state_machine_armed(), and update_state_machine_disarmed().
_sub_menu_lengths
uint8_t AP_RunCam::_sub_menu_lengths[RUNCAM_NUM_SUB_MENUS] static private
Definition at line 270 of file AP_RunCam.h.
_sub_menu_pos
uint8_t AP_RunCam::_sub_menu_pos private
Definition at line 268 of file AP_RunCam.h.
Referenced by handle_2_key_simulation_process(), handle_ready(), and handle_recording().
_top_menu_pos
int8_t AP_RunCam::_top_menu_pos private
Definition at line 266 of file AP_RunCam.h.
Referenced by handle_2_key_simulation_process(), handle_ready(), and handle_recording().
_transition_start_ms
uint32_t AP_RunCam::_transition_start_ms private
Definition at line 246 of file AP_RunCam.h.
Referenced by init(), update_state_machine_armed(), and update_state_machine_disarmed().
_transition_timeout_ms
uint32_t AP_RunCam::_transition_timeout_ms private
Definition at line 248 of file AP_RunCam.h.
Referenced by init(), send_5_key_OSD_cable_simulation_event(), simulate_camera_button(), update_state_machine_armed(), and update_state_machine_disarmed().
_video_recording
VideoOption AP_RunCam::_video_recording = VideoOption::NOT_RECORDING private
Definition at line 236 of file AP_RunCam.h.
Referenced by AP_RunCam(), exit_2_key_osd_menu(), handle_2_key_simulation_process(), handle_initialized(), map_rc_input_to_event(), parse_device_info(), start_recording(), stop_recording(), update_state_machine_armed(), and update_state_machine_disarmed().
_waiting_device_response
bool AP_RunCam::_waiting_device_response private
Definition at line 258 of file AP_RunCam.h.
Referenced by handle_5_key_simulation_response(), send_5_key_OSD_cable_simulation_event(), simulation_OSD_cable_failed(), and update_state_machine_disarmed().
RCDEVICE_PROTOCOL_FEATURE_2_KEY_OSD
const uint16_t AP_RunCam::RCDEVICE_PROTOCOL_FEATURE_2_KEY_OSD private
Initial value:
=
        uint16_t(Feature::RCDEVICE_PROTOCOL_FEATURE_CHANGE_MODE)
        | uint16_t(Feature::RCDEVICE_PROTOCOL_FEATURE_SIMULATE_WIFI_BUTTON)
        | uint16_t(Feature::RCDEVICE_PROTOCOL_FEATURE_SIMULATE_POWER_BUTTON)
Definition at line 126 of file AP_RunCam.h.
Referenced by has_2_key_OSD().
RUNCAM_MAX_DEVICE_TYPES
const uint8_t AP_RunCam::RUNCAM_MAX_DEVICE_TYPES = 5 static private
Definition at line 220 of file AP_RunCam.h.
Referenced by AP_RunCam().
RUNCAM_MAX_MENU_LENGTH
const uint8_t AP_RunCam::RUNCAM_MAX_MENU_LENGTH = 6 static private
Definition at line 219 of file AP_RunCam.h.
RUNCAM_MAX_MENUS
const uint8_t AP_RunCam::RUNCAM_MAX_MENUS = 1 static private
Definition at line 218 of file AP_RunCam.h.
RUNCAM_NUM_EXPECTED_RESPONSES
const uint8_t AP_RunCam::RUNCAM_NUM_EXPECTED_RESPONSES = 4 static private
Definition at line 217 of file AP_RunCam.h.
Referenced by AP_RunCam::Request::get_expected_response_length().
RUNCAM_NUM_SUB_MENUS
const uint8_t AP_RunCam::RUNCAM_NUM_SUB_MENUS = 5 static private
Definition at line 216 of file AP_RunCam.h.
uart
AP_HAL::UARTDriver* AP_RunCam::uart private
Definition at line 240 of file AP_RunCam.h.
Referenced by drain(), init(), pre_arm_check(), receive(), send_packet(), simulate_camera_button(), start_uart(), and update().
var_info
const AP_Param::GroupInfo AP_RunCam::var_info static
Definition at line 34 of file AP_RunCam.h.
The documentation for this class was generated from the following files:
libraries/AP_Camera/AP_RunCam.h
libraries/AP_Camera/AP_RunCam.cpp