APM:Libraries: SITL::WebotsPython Class Reference
SITL::WebotsPython Class Reference
#include <SIM_Webots_Python.h>
Classes
struct fdm_packet
packet from Webots (the Flight Dynamics Model) python struct code 'd'*(1+3+3+3+3+3)
struct servo_packet
packet to send to Webots python struct code 'f'*16
Public Member Functions
WebotsPython (const char *frame_str)
void update (const struct sitl_input &input) override
void set_interface_ports (const char *address, const int port_in, const int port_out) override
Static Public Member Functions
static Aircraft * create (const char *frame_str)
Private Member Functions
void recv_fdm (const struct sitl_input &input)
receive sensor packet from Webots
void send_servos (const struct sitl_input &input)
send servo packet to Webots
void drain_sockets ()
drain all pending packets from Webots
Private Attributes
double last_timestamp
SocketAPM_native socket_sitl
const char * _webots_address = "127.0.0.1"
int _webots_port = 9002
Static Private Attributes
static const uint64_t WEBOTS_TIMEOUT_US = 5000000
Detailed Description
Definition at line 37 of file SIM_Webots_Python.h.
Constructor & Destructor Documentation
WebotsPython()
SITL::WebotsPython::WebotsPython (const char * frame_str)
Definition at line 28 of file SIM_Webots_Python.cpp.
Referenced by create().
Member Function Documentation
create()
static Aircraft * SITL::WebotsPython::create (const char * frame_str) inline static
Definition at line 45 of file SIM_Webots_Python.h.
drain_sockets()
void SITL::WebotsPython::drain_sockets () private
drain all pending packets from Webots
Definition at line 134 of file SIM_Webots_Python.cpp.
Referenced by update().
recv_fdm()
void SITL::WebotsPython::recv_fdm (const struct sitl_input & input) private
receive sensor packet from Webots
Definition at line 77 of file SIM_Webots_Python.cpp.
Referenced by update().
send_servos()
void SITL::WebotsPython::send_servos (const struct sitl_input & input) private
send servo packet to Webots
Definition at line 65 of file SIM_Webots_Python.cpp.
Referenced by recv_fdm(), and update().
set_interface_ports()
void SITL::WebotsPython::set_interface_ports (const char * address, const int port_in, const int port_out) override
Definition at line 43 of file SIM_Webots_Python.cpp.
update()
void SITL::WebotsPython::update (const struct sitl_input & input) override
Definition at line 157 of file SIM_Webots_Python.cpp.
Member Data Documentation
_webots_address
const char* SITL::WebotsPython::_webots_address = "127.0.0.1" private
Definition at line 82 of file SIM_Webots_Python.h.
Referenced by send_servos(), and set_interface_ports().
_webots_port
int SITL::WebotsPython::_webots_port = 9002 private
Definition at line 83 of file SIM_Webots_Python.h.
Referenced by send_servos(), and set_interface_ports().
last_timestamp
double SITL::WebotsPython::last_timestamp private
Definition at line 79 of file SIM_Webots_Python.h.
Referenced by recv_fdm().
socket_sitl
SocketAPM_native SITL::WebotsPython::socket_sitl private
Definition at line 81 of file SIM_Webots_Python.h.
Referenced by drain_sockets(), recv_fdm(), send_servos(), and set_interface_ports().
WEBOTS_TIMEOUT_US
const uint64_t SITL::WebotsPython::WEBOTS_TIMEOUT_US = 5000000 static private
Definition at line 84 of file SIM_Webots_Python.h.
Referenced by recv_fdm().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_Webots_Python.h
libraries/SITL/SIM_Webots_Python.cpp