APM:Libraries: AP_ROMFS Class Reference
AP_ROMFS Class Reference
#include <AP_ROMFS.h>
Classes
struct embedded_file
Static Public Member Functions
static const uint8_t * find_decompress (const char *name, uint32_t &size)
static void free (const uint8_t *data)
static const char * dir_list (const char *dirname, uint16_t &ofs)
Static Private Member Functions
static const AP_ROMFS::embedded_file * find_file (const char *name)
Static Private Attributes
static const struct embedded_file files [] = {}
Detailed Description
Definition at line 8 of file AP_ROMFS.h.
Member Function Documentation
dir_list()
const char * AP_ROMFS::dir_list (const char * dirname, uint16_t & ofs) static
Definition at line 122 of file AP_ROMFS.cpp.
find_decompress()
const uint8_t * AP_ROMFS::find_decompress (const char * name, uint32_t & size) static
Definition at line 53 of file AP_ROMFS.cpp.
find_file()
const AP_ROMFS::embedded_file * AP_ROMFS::find_file (const char * name) static private
Definition at line 37 of file AP_ROMFS.cpp.
Referenced by find_decompress().
free()
void AP_ROMFS::free (const uint8_t * data) static
Definition at line 110 of file AP_ROMFS.cpp.
Referenced by find_decompress(), and free().
Member Data Documentation
files
const AP_ROMFS::embedded_file AP_ROMFS::files = {} static private
Definition at line 31 of file AP_ROMFS.h.
Referenced by dir_list(), and find_file().
The documentation for this class was generated from the following files:
libraries/AP_ROMFS/AP_ROMFS.h
libraries/AP_ROMFS/AP_ROMFS.cpp