APM:Libraries: AP_Compass_BMM150 Class Reference
AP_Compass_BMM150 Class Reference
#include <AP_Compass_BMM150.h>
Public Member Functions
void read () override
Public Member Functions inherited from AP_Compass_Backend
AP_Compass_Backend ()
virtual ~AP_Compass_Backend (void)
Static Public Member Functions
static AP_Compass_Backend * probe (AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, bool force_external, enum Rotation rotation)
Static Public Attributes
static constexpr const char * name = "BMM150"
Private Member Functions
AP_Compass_BMM150 (AP_HAL::OwnPtr< AP_HAL::Device > dev, bool force_external, enum Rotation rotation)
bool init ()
void _update ()
bool _load_trim_values ()
int16_t _compensate_xy (int16_t xy, uint32_t rhall, int32_t txy1, int32_t txy2) const
int16_t _compensate_z (int16_t z, uint32_t rhall) const
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _dev
uint8_t _compass_instance
struct {
int8_t x1
int8_t y1
int8_t x2
int8_t y2
uint16_t z1
int16_t z2
int16_t z3
int16_t z4
uint8_t xy1
int8_t xy2
uint16_t xyz1
} _dig
uint32_t _last_read_ms
enum Rotation _rotation
bool _force_external
Additional Inherited Members
Public Types inherited from AP_Compass_Backend
enum DevTypes {
DEVTYPE_HMC5883_OLD = 0x01 , DEVTYPE_HMC5883 = 0x07 , DEVTYPE_LSM303D = 0x02 , DEVTYPE_AK8963 = 0x04 ,
DEVTYPE_BMM150 = 0x05 , DEVTYPE_LSM9DS1 = 0x06 , DEVTYPE_LIS3MDL = 0x08 , DEVTYPE_AK09916 = 0x09 ,
DEVTYPE_IST8310 = 0x0A , DEVTYPE_ICM20948 = 0x0B , DEVTYPE_MMC3416 = 0x0C , DEVTYPE_QMC5883L = 0x0D ,
DEVTYPE_MAG3110 = 0x0E , DEVTYPE_SITL = 0x0F , DEVTYPE_IST8308 = 0x10 , DEVTYPE_RM3100 = 0x11 ,
DEVTYPE_RM3100_2 = 0x12 , DEVTYPE_MMC5983 = 0x13 , DEVTYPE_AK09918 = 0x14 , DEVTYPE_AK09915 = 0x15 ,
DEVTYPE_QMC5883P = 0x16
}
Protected Member Functions inherited from AP_Compass_Backend
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
void set_last_update_usec (uint32_t last_update, uint8_t instance)
void accumulate_sample (Vector3f &field, uint8_t instance, uint32_t max_samples=10)
void drain_accumulated_samples (uint8_t instance, const Vector3f *scale=NULL)
bool register_compass (int32_t dev_id, uint8_t &instance) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void save_dev_id (uint8_t instance)
void set_external (uint8_t instance, bool external)
bool is_external (uint8_t instance)
void set_rotation (uint8_t instance, enum Rotation rotation)
enum Rotation get_board_orientation (void) const
bool field_ok (const Vector3f &field)
uint32_t get_error_count () const
Protected Attributes inherited from AP_Compass_Backend
Compass & _compass
HAL_Semaphore _sem
Detailed Description
Definition at line 34 of file AP_Compass_BMM150.h.
Constructor & Destructor Documentation
AP_Compass_BMM150()
AP_Compass_BMM150::AP_Compass_BMM150 (AP_HAL::OwnPtr< AP_HAL::Device > dev, bool force_external, enum Rotation rotation) private
Definition at line 82 of file AP_Compass_BMM150.cpp.
Referenced by probe().
Member Function Documentation
_compensate_xy()
int16_t AP_Compass_BMM150::_compensate_xy (int16_t xy, uint32_t rhall, int32_t txy1, int32_t txy2) const private
Definition at line 247 of file AP_Compass_BMM150.cpp.
Referenced by _update().
_compensate_z()
int16_t AP_Compass_BMM150::_compensate_z (int16_t z, uint32_t rhall) const private
Definition at line 266 of file AP_Compass_BMM150.cpp.
Referenced by _update().
_load_trim_values()
bool AP_Compass_BMM150::_load_trim_values () private
Definition at line 87 of file AP_Compass_BMM150.cpp.
Referenced by init().
_update()
void AP_Compass_BMM150::_update () private
Definition at line 287 of file AP_Compass_BMM150.cpp.
Referenced by init().
init()
bool AP_Compass_BMM150::init () private
Device periodic callback to read data from the sensor.
Definition at line 142 of file AP_Compass_BMM150.cpp.
Referenced by probe().
probe()
AP_Compass_Backend * AP_Compass_BMM150::probe (AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, bool force_external, enum Rotation rotation) static
Definition at line 68 of file AP_Compass_BMM150.cpp.
Referenced by Compass::_probe_external_i2c_compasses(), and Compass::probe_i2c_spi_compasses().
read()
void AP_Compass_BMM150::read (void) override virtual
Implements AP_Compass_Backend.
Definition at line 325 of file AP_Compass_BMM150.cpp.
Member Data Documentation
_compass_instance
uint8_t AP_Compass_BMM150::_compass_instance private
Definition at line 57 of file AP_Compass_BMM150.h.
Referenced by _update(), init(), and read().
_dev
AP_HAL::OwnPtr<AP_HAL::Device> AP_Compass_BMM150::_dev private
Definition at line 55 of file AP_Compass_BMM150.h.
Referenced by _load_trim_values(), _update(), and init().
[struct]
struct { ... } AP_Compass_BMM150::_dig
Referenced by _compensate_xy(), _compensate_z(), _load_trim_values(), and _update().
_force_external
bool AP_Compass_BMM150::_force_external private
Definition at line 75 of file AP_Compass_BMM150.h.
Referenced by init().
_last_read_ms
uint32_t AP_Compass_BMM150::_last_read_ms private
Definition at line 73 of file AP_Compass_BMM150.h.
Referenced by _update(), and init().
_rotation
enum Rotation AP_Compass_BMM150::_rotation private
Definition at line 74 of file AP_Compass_BMM150.h.
Referenced by init().
name
constexpr const char* AP_Compass_BMM150::name = "BMM150" static constexpr
Definition at line 41 of file AP_Compass_BMM150.h.
x1
int8_t AP_Compass_BMM150::x1
Definition at line 60 of file AP_Compass_BMM150.h.
x2
int8_t AP_Compass_BMM150::x2
Definition at line 62 of file AP_Compass_BMM150.h.
xy1
uint8_t AP_Compass_BMM150::xy1
Definition at line 68 of file AP_Compass_BMM150.h.
xy2
int8_t AP_Compass_BMM150::xy2
Definition at line 69 of file AP_Compass_BMM150.h.
xyz1
uint16_t AP_Compass_BMM150::xyz1
Definition at line 70 of file AP_Compass_BMM150.h.
y1
int8_t AP_Compass_BMM150::y1
Definition at line 61 of file AP_Compass_BMM150.h.
y2
int8_t AP_Compass_BMM150::y2
Definition at line 63 of file AP_Compass_BMM150.h.
z1
uint16_t AP_Compass_BMM150::z1
Definition at line 64 of file AP_Compass_BMM150.h.
z2
int16_t AP_Compass_BMM150::z2
Definition at line 65 of file AP_Compass_BMM150.h.
z3
int16_t AP_Compass_BMM150::z3
Definition at line 66 of file AP_Compass_BMM150.h.
z4
int16_t AP_Compass_BMM150::z4
Definition at line 67 of file AP_Compass_BMM150.h.
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass_BMM150.h
libraries/AP_Compass/AP_Compass_BMM150.cpp