APM:Libraries: AP_Mount Class Reference
AP_Mount Class Reference
#include <AP_Mount.h>
Public Types
enum class Type {
None = 0 , Servo = 1 , Alexmos = 3 , SToRM32_serial = 5 ,
BrushlessPWM = 7 , Siyi = 8
}
Public Member Functions
AP_Mount ()
CLASS_NO_COPY (AP_Mount)
void init ()
void update ()
void update_fast ()
uint8_t get_primary_instance () const
Type get_mount_type () const
Type get_mount_type (uint8_t instance) const
bool has_pan_control () const
bool has_pan_control (uint8_t instance) const
enum MAV_MOUNT_MODE get_mode () const
enum MAV_MOUNT_MODE get_mode (uint8_t instance) const
void set_mode (enum MAV_MOUNT_MODE mode)
void set_mode (uint8_t instance, enum MAV_MOUNT_MODE mode)
void set_mode_to_default ()
void set_mode_to_default (uint8_t instance)
void set_yaw_lock (bool yaw_lock)
void set_yaw_lock (uint8_t instance, bool yaw_lock)
void set_angle_target (float roll_deg, float pitch_deg, float yaw_deg, bool yaw_is_earth_frame)
void set_angle_target (uint8_t instance, float roll_deg, float pitch_deg, float yaw_deg, bool yaw_is_earth_frame)
void set_rate_target (float roll_degs, float pitch_degs, float yaw_degs, bool yaw_lock)
void set_rate_target (uint8_t instance, float roll_degs, float pitch_degs, float yaw_degs, bool yaw_lock)
void set_roi_target (const Location &target_loc)
void set_roi_target (uint8_t instance, const Location &target_loc)
void clear_roi_target ()
void clear_roi_target (uint8_t instance)
void set_target_sysid (uint8_t sysid)
void set_target_sysid (uint8_t instance, uint8_t sysid)
MAV_RESULT handle_command_do_set_roi_sysid (const mavlink_command_int_t &packet)
MAV_RESULT handle_command (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
void handle_param_value (const mavlink_message_t &msg)
void handle_message (mavlink_channel_t chan, const mavlink_message_t &msg)
void send_gimbal_device_attitude_status (mavlink_channel_t chan)
void send_gimbal_manager_information (mavlink_channel_t chan)
void send_gimbal_manager_status (mavlink_channel_t chan)
bool get_attitude_euler (uint8_t instance, float &roll_deg, float &pitch_deg, float &yaw_bf_deg)
bool pre_arm_checks (char *failure_msg, uint8_t failure_msg_len)
bool get_rate_target (uint8_t instance, float &roll_degs, float &pitch_degs, float &yaw_degs, bool &yaw_is_earth_frame)
bool get_angle_target (uint8_t instance, float &roll_deg, float &pitch_deg, float &yaw_deg, bool &yaw_is_earth_frame)
bool get_location_target (uint8_t instance, Location &target_loc)
void set_attitude_euler (uint8_t instance, float roll_deg, float pitch_deg, float yaw_bf_deg)
void write_log ()
void write_log (uint8_t instance, uint64_t timestamp_us)
bool take_picture (uint8_t instance)
bool record_video (uint8_t instance, bool start_recording)
bool set_zoom (uint8_t instance, ZoomType zoom_type, float zoom_value)
SetFocusResult set_focus (uint8_t instance, FocusType focus_type, float focus_value)
bool set_tracking (uint8_t instance, TrackingType tracking_type, const Vector2f &p1, const Vector2f &p2)
bool set_lens (uint8_t instance, uint8_t lens)
void send_camera_information (uint8_t instance, mavlink_channel_t chan) const
void send_camera_settings (uint8_t instance, mavlink_channel_t chan) const
void send_camera_capture_status (uint8_t instance, mavlink_channel_t chan) const
bool get_rangefinder_distance (uint8_t instance, float &distance_m) const
Static Public Member Functions
static AP_Mount * get_singleton ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Attributes
AP_Mount_Params _params [AP_MOUNT_MAX_INSTANCES]
uint8_t _num_instances
uint8_t _primary
AP_Mount_Backend * _backends [AP_MOUNT_MAX_INSTANCES]
Static Protected Attributes
static AP_Mount * _singleton
Private Member Functions
AP_Mount_Backend * get_primary () const
AP_Mount_Backend * get_instance (uint8_t instance) const
void handle_gimbal_report (mavlink_channel_t chan, const mavlink_message_t &msg)
MAV_RESULT handle_command_do_mount_configure (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_mount_control (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_gimbal_manager_pitchyaw (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_gimbal_manager_configure (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
void handle_gimbal_manager_set_attitude (const mavlink_message_t &msg)
void handle_gimbal_manager_set_pitchyaw (const mavlink_message_t &msg)
void handle_global_position_int (const mavlink_message_t &msg)
Change the configuration of the mount.
void handle_gimbal_device_information (const mavlink_message_t &msg)
void handle_gimbal_device_attitude_status (const mavlink_message_t &msg)
void convert_params ()
Friends
class AP_Mount_Backend
class AP_Mount_Servo
class AP_Mount_SoloGimbal
class AP_Mount_Alexmos
class AP_Mount_SToRM32
class AP_Mount_SToRM32_serial
class AP_Mount_Gremsy
class AP_Mount_Siyi
class AP_Mount_Scripting
class AP_Mount_Xacti
class AP_Mount_Viewpro
Detailed Description
Definition at line 56 of file AP_Mount.h.
Member Enumeration Documentation
Type
enum class AP_Mount::Type strong
Enumerator
None
Servo
no mount
Alexmos
servo controlled mount
SToRM32_serial
Alexmos mount.
BrushlessPWM
SToRM32 mount using custom serial protocol.
Siyi
Brushless (stabilized) gimbal using PWM protocol.
Definition at line 83 of file AP_Mount.h.
Constructor & Destructor Documentation
AP_Mount()
AP_Mount::AP_Mount ()
Definition at line 38 of file AP_Mount.cpp.
Member Function Documentation
CLASS_NO_COPY()
AP_Mount::CLASS_NO_COPY (AP_Mount)
clear_roi_target() [1/2]
void AP_Mount::clear_roi_target () inline
Definition at line 174 of file AP_Mount.h.
Referenced by clear_roi_target(), and GCS_MAVLINK::handle_command_do_set_roi().
clear_roi_target() [2/2]
void AP_Mount::clear_roi_target (uint8_t instance)
Definition at line 759 of file AP_Mount.cpp.
convert_params()
void AP_Mount::convert_params () private
Definition at line 970 of file AP_Mount.cpp.
Referenced by init().
get_angle_target()
bool AP_Mount::get_angle_target (uint8_t instance, float & roll_deg, float & pitch_deg, float & yaw_deg, bool & yaw_is_earth_frame)
Definition at line 687 of file AP_Mount.cpp.
get_attitude_euler()
bool AP_Mount::get_attitude_euler (uint8_t instance, float & roll_deg, float & pitch_deg, float & yaw_bf_deg)
Definition at line 627 of file AP_Mount.cpp.
get_instance()
AP_Mount_Backend * AP_Mount::get_instance (uint8_t instance) const private
Definition at line 881 of file AP_Mount.cpp.
Referenced by clear_roi_target(), get_angle_target(), get_attitude_euler(), get_location_target(), get_mode(), get_primary(), get_rangefinder_distance(), get_rate_target(), handle_command_do_gimbal_manager_configure(), handle_command_do_gimbal_manager_pitchyaw(), handle_gimbal_manager_set_attitude(), handle_gimbal_manager_set_pitchyaw(), has_pan_control(), record_video(), send_camera_capture_status(), send_camera_information(), send_camera_settings(), set_angle_target(), set_attitude_euler(), set_focus(), set_lens(), set_mode(), set_mode_to_default(), set_rate_target(), set_roi_target(), set_target_sysid(), set_tracking(), set_yaw_lock(), set_zoom(), and take_picture().
get_location_target()
bool AP_Mount::get_location_target (uint8_t instance, Location & target_loc)
Definition at line 697 of file AP_Mount.cpp.
get_mode() [1/2]
enum MAV_MOUNT_MODE AP_Mount::get_mode () const inline
Definition at line 141 of file AP_Mount.h.
Referenced by get_mode().
get_mode() [2/2]
MAV_MOUNT_MODE AP_Mount::get_mode (uint8_t instance) const
Definition at line 218 of file AP_Mount.cpp.
get_mount_type() [1/2]
Type AP_Mount::get_mount_type () const inline
Definition at line 133 of file AP_Mount.h.
Referenced by AP_Camera_Backend::get_gimbal_device_id(), get_mount_type(), init(), and pre_arm_checks().
get_mount_type() [2/2]
AP_Mount::Type AP_Mount::get_mount_type (uint8_t instance) const
Definition at line 196 of file AP_Mount.cpp.
get_primary()
AP_Mount_Backend * AP_Mount::get_primary () const private
Definition at line 876 of file AP_Mount.cpp.
Referenced by handle_command_do_gimbal_manager_configure(), handle_command_do_gimbal_manager_pitchyaw(), handle_command_do_mount_configure(), handle_command_do_mount_control(), handle_gimbal_manager_set_attitude(), and handle_gimbal_manager_set_pitchyaw().
get_primary_instance()
uint8_t AP_Mount::get_primary_instance () const inline
Definition at line 130 of file AP_Mount.h.
get_rangefinder_distance()
bool AP_Mount::get_rangefinder_distance (uint8_t instance, float & distance_m) const
Definition at line 867 of file AP_Mount.cpp.
get_rate_target()
bool AP_Mount::get_rate_target (uint8_t instance, float & roll_degs, float & pitch_degs, float & yaw_degs, bool & yaw_is_earth_frame)
Definition at line 677 of file AP_Mount.cpp.
get_singleton()
static AP_Mount * AP_Mount::get_singleton () inline static
Definition at line 78 of file AP_Mount.h.
Referenced by AP::mount().
handle_command()
MAV_RESULT AP_Mount::handle_command (const mavlink_command_int_t & packet, const mavlink_message_t & msg)
Definition at line 509 of file AP_Mount.cpp.
handle_command_do_gimbal_manager_configure()
MAV_RESULT AP_Mount::handle_command_do_gimbal_manager_configure (const mavlink_command_int_t & packet, const mavlink_message_t & msg) private
Definition at line 365 of file AP_Mount.cpp.
Referenced by handle_command().
handle_command_do_gimbal_manager_pitchyaw()
MAV_RESULT AP_Mount::handle_command_do_gimbal_manager_pitchyaw (const mavlink_command_int_t & packet) private
Definition at line 314 of file AP_Mount.cpp.
Referenced by handle_command().
handle_command_do_mount_configure()
MAV_RESULT AP_Mount::handle_command_do_mount_configure (const mavlink_command_int_t & packet) private
Definition at line 291 of file AP_Mount.cpp.
Referenced by handle_command().
handle_command_do_mount_control()
MAV_RESULT AP_Mount::handle_command_do_mount_control (const mavlink_command_int_t & packet) private
Definition at line 304 of file AP_Mount.cpp.
Referenced by handle_command().
handle_command_do_set_roi_sysid()
MAV_RESULT AP_Mount::handle_command_do_set_roi_sysid (const mavlink_command_int_t & packet)
Definition at line 503 of file AP_Mount.cpp.
Referenced by handle_command().
handle_gimbal_device_attitude_status()
void AP_Mount::handle_gimbal_device_attitude_status (const mavlink_message_t & msg) private
Definition at line 960 of file AP_Mount.cpp.
Referenced by handle_message().
handle_gimbal_device_information()
void AP_Mount::handle_gimbal_device_information (const mavlink_message_t & msg) private
Definition at line 950 of file AP_Mount.cpp.
Referenced by handle_message().
handle_gimbal_manager_set_attitude()
void AP_Mount::handle_gimbal_manager_set_attitude (const mavlink_message_t & msg) private
Definition at line 384 of file AP_Mount.cpp.
Referenced by handle_message().
handle_gimbal_manager_set_pitchyaw()
void AP_Mount::handle_gimbal_manager_set_pitchyaw (const mavlink_message_t & msg) private
Definition at line 449 of file AP_Mount.cpp.
Referenced by handle_message().
handle_gimbal_report()
void AP_Mount::handle_gimbal_report (mavlink_channel_t chan, const mavlink_message_t & msg) private
Definition at line 890 of file AP_Mount.cpp.
Referenced by handle_message().
handle_global_position_int()
void AP_Mount::handle_global_position_int (const mavlink_message_t & msg) private
Change the configuration of the mount.
Definition at line 528 of file AP_Mount.cpp.
Referenced by handle_message().
handle_message()
void AP_Mount::handle_message (mavlink_channel_t chan, const mavlink_message_t & msg)
Definition at line 899 of file AP_Mount.cpp.
handle_param_value()
void AP_Mount::handle_param_value (const mavlink_message_t & msg)
Definition at line 939 of file AP_Mount.cpp.
Referenced by GCS_MAVLINK::handle_param_value().
has_pan_control() [1/2]
bool AP_Mount::has_pan_control () const inline
Definition at line 137 of file AP_Mount.h.
Referenced by has_pan_control().
has_pan_control() [2/2]
bool AP_Mount::has_pan_control (uint8_t instance) const
Definition at line 206 of file AP_Mount.cpp.
init()
void AP_Mount::init ()
Definition at line 52 of file AP_Mount.cpp.
pre_arm_checks()
bool AP_Mount::pre_arm_checks (char * failure_msg, uint8_t failure_msg_len)
Definition at line 650 of file AP_Mount.cpp.
record_video()
bool AP_Mount::record_video (uint8_t instance, bool start_recording)
Definition at line 784 of file AP_Mount.cpp.
send_camera_capture_status()
void AP_Mount::send_camera_capture_status (uint8_t instance, mavlink_channel_t chan) const
Definition at line 857 of file AP_Mount.cpp.
send_camera_information()
void AP_Mount::send_camera_information (uint8_t instance, mavlink_channel_t chan) const
Definition at line 837 of file AP_Mount.cpp.
send_camera_settings()
void AP_Mount::send_camera_settings (uint8_t instance, mavlink_channel_t chan) const
Definition at line 847 of file AP_Mount.cpp.
send_gimbal_device_attitude_status()
void AP_Mount::send_gimbal_device_attitude_status (mavlink_channel_t chan)
send_gimbal_manager_information()
void AP_Mount::send_gimbal_manager_information (mavlink_channel_t chan)
send_gimbal_manager_status()
void AP_Mount::send_gimbal_manager_status (mavlink_channel_t chan)
set_angle_target() [1/2]
void AP_Mount::set_angle_target (float roll_deg, float pitch_deg, float yaw_deg, bool yaw_is_earth_frame) inline
Definition at line 161 of file AP_Mount.h.
Referenced by set_angle_target().
set_angle_target() [2/2]
void AP_Mount::set_angle_target (uint8_t instance, float roll_deg, float pitch_deg, float yaw_deg, bool yaw_is_earth_frame)
Definition at line 267 of file AP_Mount.cpp.
set_attitude_euler()
void AP_Mount::set_attitude_euler (uint8_t instance, float roll_deg, float pitch_deg, float yaw_bf_deg)
Definition at line 706 of file AP_Mount.cpp.
set_focus()
SetFocusResult AP_Mount::set_focus (uint8_t instance, FocusType focus_type, float focus_value)
Definition at line 805 of file AP_Mount.cpp.
set_lens()
bool AP_Mount::set_lens (uint8_t instance, uint8_t lens)
Definition at line 827 of file AP_Mount.cpp.
set_mode() [1/2]
void AP_Mount::set_mode (enum MAV_MOUNT_MODE mode) inline
Definition at line 146 of file AP_Mount.h.
Referenced by RC_Channel::do_aux_function(), and set_mode().
set_mode() [2/2]
void AP_Mount::set_mode (uint8_t instance, enum MAV_MOUNT_MODE mode)
Definition at line 241 of file AP_Mount.cpp.
set_mode_to_default() [1/2]
void AP_Mount::set_mode_to_default () inline
Definition at line 151 of file AP_Mount.h.
Referenced by RC_Channel::do_aux_function(), init(), and set_mode_to_default().
set_mode_to_default() [2/2]
void AP_Mount::set_mode_to_default (uint8_t instance)
Definition at line 231 of file AP_Mount.cpp.
set_rate_target() [1/2]
void AP_Mount::set_rate_target (float roll_degs, float pitch_degs, float yaw_degs, bool yaw_lock) inline
Definition at line 166 of file AP_Mount.h.
Referenced by set_rate_target().
set_rate_target() [2/2]
void AP_Mount::set_rate_target (uint8_t instance, float roll_degs, float pitch_degs, float yaw_degs, bool yaw_lock)
Definition at line 280 of file AP_Mount.cpp.
set_roi_target() [1/2]
void AP_Mount::set_roi_target (const Location & target_loc) inline
Definition at line 170 of file AP_Mount.h.
Referenced by GCS_MAVLINK::handle_command_do_set_roi(), and set_roi_target().
set_roi_target() [2/2]
void AP_Mount::set_roi_target (uint8_t instance, const Location & target_loc)
Definition at line 749 of file AP_Mount.cpp.
set_target_sysid() [1/2]
void AP_Mount::set_target_sysid (uint8_t instance, uint8_t sysid)
Definition at line 738 of file AP_Mount.cpp.
set_target_sysid() [2/2]
void AP_Mount::set_target_sysid (uint8_t sysid) inline
Definition at line 178 of file AP_Mount.h.
Referenced by handle_command_do_set_roi_sysid(), and set_target_sysid().
set_tracking()
bool AP_Mount::set_tracking (uint8_t instance, TrackingType tracking_type, const Vector2f & p1, const Vector2f & p2)
Definition at line 817 of file AP_Mount.cpp.
set_yaw_lock() [1/2]
void AP_Mount::set_yaw_lock (bool yaw_lock) inline
Definition at line 156 of file AP_Mount.h.
Referenced by RC_Channel::do_aux_function(), and set_yaw_lock().
set_yaw_lock() [2/2]
void AP_Mount::set_yaw_lock (uint8_t instance, bool yaw_lock)
Definition at line 254 of file AP_Mount.cpp.
set_zoom()
bool AP_Mount::set_zoom (uint8_t instance, ZoomType zoom_type, float zoom_value)
Definition at line 794 of file AP_Mount.cpp.
take_picture()
bool AP_Mount::take_picture (uint8_t instance)
Definition at line 773 of file AP_Mount.cpp.
update()
void AP_Mount::update ()
Definition at line 174 of file AP_Mount.cpp.
update_fast()
void AP_Mount::update_fast ()
Definition at line 185 of file AP_Mount.cpp.
write_log() [1/2]
void AP_Mount::write_log ()
write_log() [2/2]
void AP_Mount::write_log (uint8_t instance, uint64_t timestamp_us)
Friends And Related Symbol Documentation
AP_Mount_Alexmos
friend class AP_Mount_Alexmos friend
Definition at line 62 of file AP_Mount.h.
Referenced by init().
AP_Mount_Backend
friend class AP_Mount_Backend friend
Definition at line 59 of file AP_Mount.h.
AP_Mount_Gremsy
friend class AP_Mount_Gremsy friend
Definition at line 65 of file AP_Mount.h.
Referenced by init().
AP_Mount_Scripting
friend class AP_Mount_Scripting friend
Definition at line 67 of file AP_Mount.h.
Referenced by init().
AP_Mount_Servo
friend class AP_Mount_Servo friend
Definition at line 60 of file AP_Mount.h.
Referenced by init().
AP_Mount_Siyi
friend class AP_Mount_Siyi friend
Definition at line 66 of file AP_Mount.h.
Referenced by init().
AP_Mount_SoloGimbal
friend class AP_Mount_SoloGimbal friend
Definition at line 61 of file AP_Mount.h.
Referenced by init().
AP_Mount_SToRM32
friend class AP_Mount_SToRM32 friend
Definition at line 63 of file AP_Mount.h.
Referenced by init().
AP_Mount_SToRM32_serial
friend class AP_Mount_SToRM32_serial friend
Definition at line 64 of file AP_Mount.h.
Referenced by init().
AP_Mount_Viewpro
friend class AP_Mount_Viewpro friend
Definition at line 69 of file AP_Mount.h.
Referenced by init().
AP_Mount_Xacti
friend class AP_Mount_Xacti friend
Definition at line 68 of file AP_Mount.h.
Referenced by init().
Member Data Documentation
_backends
AP_Mount_Backend* AP_Mount::_backends[AP_MOUNT_MAX_INSTANCES] protected
Definition at line 282 of file AP_Mount.h.
Referenced by get_instance(), handle_gimbal_device_attitude_status(), handle_gimbal_device_information(), handle_gimbal_report(), handle_global_position_int(), handle_param_value(), init(), pre_arm_checks(), update(), and update_fast().
_num_instances
uint8_t AP_Mount::_num_instances protected
Definition at line 280 of file AP_Mount.h.
Referenced by init(), and pre_arm_checks().
_params
AP_Mount_Params AP_Mount::_params[AP_MOUNT_MAX_INSTANCES] protected
Definition at line 277 of file AP_Mount.h.
Referenced by convert_params(), get_mount_type(), init(), and set_mode_to_default().
_primary
uint8_t AP_Mount::_primary protected
Definition at line 281 of file AP_Mount.h.
Referenced by clear_roi_target(), get_mode(), get_mount_type(), get_primary(), get_primary_instance(), has_pan_control(), init(), set_angle_target(), set_mode(), set_mode_to_default(), set_rate_target(), set_roi_target(), set_target_sysid(), and set_yaw_lock().
_singleton
AP_Mount * AP_Mount::_singleton static protected
Definition at line 274 of file AP_Mount.h.
Referenced by AP_Mount(), and get_singleton().
var_info
const AP_Param::GroupInfo AP_Mount::var_info static
Initial value:
= {
    AP_SUBGROUPINFO(_params[0], "1", 43, AP_Mount, AP_Mount_Params),
    AP_SUBGROUPINFO(_params[1], "2", 44, AP_Mount, AP_Mount_Params),
    AP_GROUPEND
}
Definition at line 23 of file AP_Mount.h.
The documentation for this class was generated from the following files:
libraries/AP_Mount/AP_Mount.h
libraries/AP_Mount/AP_Mount.cpp