APM:Libraries: AP_Filesystem_Posix Class Reference
AP_Filesystem_Posix Class Reference
#include <AP_Filesystem_posix.h>
Public Member Functions
int open (const char *fname, int flags, bool allow_absolute_paths=false) override
int close (int fd) override
int32_t read (int fd, void *buf, uint32_t count) override
int32_t write (int fd, const void *buf, uint32_t count) override
int fsync (int fd) override
int32_t lseek (int fd, int32_t offset, int whence) override
int stat (const char *pathname, struct stat *stbuf) override
int unlink (const char *pathname) override
int mkdir (const char *pathname) override
void * opendir (const char *pathname) override
struct dirent * readdir (void *dirp) override
int closedir (void *dirp) override
int rename (const char *oldpath, const char *newpath) override
int64_t disk_free (const char *path) override
int64_t disk_space (const char *path) override
bool set_mtime (const char *filename, const uint32_t mtime_sec) override
Public Member Functions inherited from AP_Filesystem_Backend
virtual bool retry_mount (void)
virtual void unmount (void)
virtual bool format (void)
virtual AP_Filesystem_Backend::FormatStatus get_format_status () const
virtual FileData * load_file (const char *filename)
virtual void unload_file (FileData *fd)
Additional Inherited Members
Public Types inherited from AP_Filesystem_Backend
enum class FormatStatus {
NOT_STARTED , PENDING , IN_PROGRESS , SUCCESS ,
FAILURE
}
Protected Member Functions inherited from AP_Filesystem_Backend
bool file_op_allowed (void) const
Detailed Description
Definition at line 32 of file AP_Filesystem_posix.h.
Member Function Documentation
close()
int AP_Filesystem_Posix::close (int fd) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 71 of file AP_Filesystem_posix.cpp.
closedir()
int AP_Filesystem_Posix::closedir (void * dirp) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 141 of file AP_Filesystem_posix.cpp.
disk_free()
int64_t AP_Filesystem_Posix::disk_free (const char * path) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 156 of file AP_Filesystem_posix.cpp.
disk_space()
int64_t AP_Filesystem_Posix::disk_space (const char * path) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 168 of file AP_Filesystem_posix.cpp.
fsync()
int AP_Filesystem_Posix::fsync (int fd) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 89 of file AP_Filesystem_posix.cpp.
lseek()
int32_t AP_Filesystem_Posix::lseek (int fd, int32_t offset, int whence) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 95 of file AP_Filesystem_posix.cpp.
mkdir()
int AP_Filesystem_Posix::mkdir (const char * pathname) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 121 of file AP_Filesystem_posix.cpp.
open()
int AP_Filesystem_Posix::open (const char * fname, int flags, bool allow_absolute_paths = false) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 55 of file AP_Filesystem_posix.cpp.
opendir()
void * AP_Filesystem_Posix::opendir (const char * pathname) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 128 of file AP_Filesystem_posix.cpp.
Referenced by opendir().
read()
int32_t AP_Filesystem_Posix::read (int fd, void * buf, uint32_t count) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 77 of file AP_Filesystem_posix.cpp.
readdir()
struct dirent * AP_Filesystem_Posix::readdir (void * dirp) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 135 of file AP_Filesystem_posix.cpp.
rename()
int AP_Filesystem_Posix::rename (const char * oldpath, const char * newpath) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 147 of file AP_Filesystem_posix.cpp.
set_mtime()
bool AP_Filesystem_Posix::set_mtime (const char * filename, const uint32_t mtime_sec) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 183 of file AP_Filesystem_posix.cpp.
stat()
int AP_Filesystem_Posix::stat (const char * pathname, struct stat * stbuf) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 101 of file AP_Filesystem_posix.cpp.
Referenced by open().
unlink()
int AP_Filesystem_Posix::unlink (const char * pathname) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 108 of file AP_Filesystem_posix.cpp.
Referenced by unlink().
write()
int32_t AP_Filesystem_Posix::write (int fd, const void * buf, uint32_t count) override virtual
Reimplemented from AP_Filesystem_Backend.
Definition at line 83 of file AP_Filesystem_posix.cpp.
The documentation for this class was generated from the following files:
libraries/AP_Filesystem/AP_Filesystem_posix.h
libraries/AP_Filesystem/AP_Filesystem_posix.cpp