APM:Libraries: MultiHeap Class Reference
MultiHeap Class Reference
#include <MultiHeap.h>
Public Member Functions
bool create (uint32_t total_size, uint8_t max_heaps)
void destroy (void)
bool available (void) const
void * allocate (uint32_t size)
void deallocate (void *ptr)
void * change_size (void *ptr, uint32_t old_size, uint32_t new_size)
Private Attributes
uint8_t num_heaps
void ** heaps
Detailed Description
Definition at line 7 of file MultiHeap.h.
Member Function Documentation
allocate()
void * MultiHeap::allocate (uint32_t size)
Definition at line 93 of file MultiHeap.cpp.
Referenced by change_size().
available()
bool MultiHeap::available (void) const
Definition at line 85 of file MultiHeap.cpp.
Referenced by allocate(), deallocate(), and destroy().
change_size()
void * MultiHeap::change_size (void * ptr, uint32_t old_size, uint32_t new_size)
Definition at line 126 of file MultiHeap.cpp.
create()
bool MultiHeap::create (uint32_t total_size, uint8_t max_heaps)
Definition at line 34 of file MultiHeap.cpp.
deallocate()
void MultiHeap::deallocate (void * ptr)
Definition at line 113 of file MultiHeap.cpp.
Referenced by change_size().
destroy()
void MultiHeap::destroy (void)
Definition at line 68 of file MultiHeap.cpp.
Referenced by create().
Member Data Documentation
heaps
void** MultiHeap::heaps private
Definition at line 28 of file MultiHeap.h.
Referenced by allocate(), available(), change_size(), create(), deallocate(), and destroy().
num_heaps
uint8_t MultiHeap::num_heaps private
Definition at line 27 of file MultiHeap.h.
Referenced by allocate(), create(), and destroy().
The documentation for this class was generated from the following files:
libraries/AP_Common/MultiHeap.h
libraries/AP_Common/MultiHeap.cpp