APM:Libraries: HALSITL::SITL_State Class Reference
HALSITL::SITL_State Class Reference
#include <SITL_State.h>
Classes
struct readings_wind
Public Member Functions
void init (int argc, char *const argv[]) override
void loop_hook (void)
uint16_t base_port (void) const
bool use_rtscts (void) const
uint8_t get_instance () const
Public Member Functions inherited from HALSITL::SITL_State_Common
SITL::SerialDevice * create_serial_sim (const char *name, const char *arg)
float _sonar_pin_voltage () const
void multicast_state_open (void)
void multicast_state_send (void)
Static Public Member Functions
static bool parse_home (const char *home_str, Location &loc, float &yaw_degrees)
static bool lookup_location (const char *home_str, Location &loc, float &yaw_degrees)
Public Attributes
const char * _serial_path [9]
std::vector< struct AP_Param::defaults_table_struct > cmdline_param
Public Attributes inherited from HALSITL::SITL_State_Common
float sonar_pin_voltage
float airspeed_pin_voltage [AIRSPEED_MAX_SENSORS]
float voltage_pin_voltage
float current_pin_voltage
float voltage2_pin_voltage
float current2_pin_voltage
uint16_t pwm_input [SITL_RC_INPUT_CHANNELS]
bool new_rc_input
uint16_t pwm_output [SITL_NUM_CHANNELS]
bool output_ready = false
SITL::Vicon * vicon
SITL::RF_Benewake_TF02 * benewake_tf02
SITL::RF_Benewake_TF03 * benewake_tf03
SITL::RF_JRE * jre
SITL::RF_Benewake_TFmini * benewake_tfmini
SITL::RF_Nooploop * nooploop
SITL::RF_TeraRanger_Serial * teraranger_serial
SITL::RF_LightWareSerial * lightwareserial
SITL::RF_LightWareSerialBinary * lightwareserial_binary
SITL::RF_Lanbao * lanbao
SITL::RF_BLping * blping
SITL::RF_LeddarOne * leddarone
SITL::RF_RDS02UF * rds02uf
SITL::RF_USD1_v0 * USD1_v0
SITL::RF_USD1_v1 * USD1_v1
SITL::RF_MaxsonarSerialLV * maxsonarseriallv
SITL::RF_Wasp * wasp
SITL::RF_NMEA * nmea
SITL::RF_MAVLink * rf_mavlink
SITL::RF_GYUS42v2 * gyus42v2
SITL::Frsky_D * frsky_d
SITL::FETtecOneWireESC * fetteconewireesc
SITL::PS_RPLidarA1 * rplidara1
SITL::VectorNav * vectornav
SITL::MicroStrain5 * microstrain5
SITL::MicroStrain7 * microstrain7
SITL::InertialLabs * inertiallabs
SITL::EFI_MegaSquirt * efi_ms
SITL::EFI_Hirth * efi_hirth
SocketAPM_native fg_socket {true}
const char * defaults_path = HAL_PARAM_DEFAULTS_PATH
SITL::GPS * gps [2]
int mc_out_fd = -1
Private Member Functions
void _parse_command_line (int argc, char *const argv[])
void _set_param_default (const char *parm)
void _usage (void)
void _sitl_setup ()
bool _setup_fdm (void)
void _setup_timer (void)
void _setup_adc (void)
void set_height_agl (void)
void _update_rangefinder ()
void _set_signal_handlers (void) const
void _update_airspeed (float airspeed)
void _check_rc_input (void)
bool _read_rc_sitl_input ()
void _fdm_input_local (void)
void _output_to_flightgear (void)
void _simulator_servos (struct sitl_input &input)
void _fdm_input_step (void)
void wait_clock (uint64_t wait_time_usec)
float _sonar_pin_voltage () const
void multicast_state_open (void)
void multicast_state_send (void)
void multicast_servo_update (struct sitl_input &input)
void check_servo_input (void)
Private Attributes
uint8_t _instance
uint16_t _base_port
pid_t _parent_pid
uint32_t _update_count
Scheduler * _scheduler
SocketAPM_native _sitl_rc_in {true}
bool _rc_in_started
uint16_t _rcin_port
uint16_t _fg_view_port
uint16_t _irlock_port
bool _synthetic_clock_mode
bool _use_rtscts
bool _use_fg_view
const char * _fg_address
uint8_t store_index_wind
uint32_t last_store_time_wind
VectorN< readings_wind, wind_buffer_length > buffer_wind
uint32_t time_delta_wind
uint32_t delayed_time_wind
uint32_t wind_start_delay_micros
SITL::GPS * gps [2]
int mc_out_fd = -1
int servo_in_fd = -1
uint16_t mc_servo [SITL_NUM_CHANNELS]
Static Private Attributes
static const uint8_t wind_buffer_length = 50
Friends
class HALSITL::Scheduler
class HALSITL::Util
class HALSITL::GPIO
Additional Inherited Members
Public Types inherited from HALSITL::SITL_State_Common
enum vehicle_type {
NONE , ArduCopter , Rover , ArduPlane ,
ArduSub , Blimp
}
Protected Member Functions inherited from HALSITL::SITL_State_Common
void sim_update (void)
void update_voltage_current (struct sitl_input &input, float throttle)
Protected Attributes inherited from HALSITL::SITL_State_Common
enum vehicle_type _vehicle
SITL::Aircraft * sitl_model
SITL::SIM * _sitl
Detailed Description
Definition at line 15 of file SITL_State.h.
Member Function Documentation
_check_rc_input()
void SITL_State::_check_rc_input (void) private
Definition at line 231 of file SITL_State.cpp.
Referenced by _fdm_input_local().
_fdm_input_local()
void SITL_State::_fdm_input_local (void) private
Definition at line 333 of file SITL_State.cpp.
Referenced by _fdm_input_step().
_fdm_input_step()
void SITL_State::_fdm_input_step (void) private
Definition at line 141 of file SITL_State.cpp.
Referenced by wait_clock().
_output_to_flightgear()
void SITL_State::_output_to_flightgear (void) private
Definition at line 297 of file SITL_State.cpp.
Referenced by _fdm_input_local().
_parse_command_line()
void SITL_State::_parse_command_line (int argc, char *const argv[]) private
Definition at line 207 of file SITL_cmdline.cpp.
Referenced by init().
_read_rc_sitl_input()
bool SITL_State::_read_rc_sitl_input () private
Definition at line 243 of file SITL_State.cpp.
Referenced by _check_rc_input().
_set_param_default()
void SITL_State::_set_param_default (const char * parm) private
Definition at line 32 of file SITL_State.cpp.
Referenced by _parse_command_line().
_set_signal_handlers()
void SITL_State::_set_signal_handlers (void) const private
Definition at line 188 of file SITL_cmdline.cpp.
Referenced by _parse_command_line().
_setup_adc()
void HALSITL::SITL_State::_setup_adc (void) private
_setup_fdm()
bool SITL_State::_setup_fdm (void) private
Definition at line 116 of file SITL_State.cpp.
Referenced by _read_rc_sitl_input(), and _sitl_setup().
_setup_timer()
void HALSITL::SITL_State::_setup_timer (void) private
_simulator_servos()
void SITL_State::_simulator_servos (struct sitl_input & input) private
Definition at line 396 of file SITL_State.cpp.
Referenced by _fdm_input_local().
_sitl_setup()
void SITL_State::_sitl_setup () private
Definition at line 68 of file SITL_State.cpp.
Referenced by _parse_command_line().
_sonar_pin_voltage()
float SITL_State::_sonar_pin_voltage () const private
Definition at line 24 of file sitl_rangefinder.cpp.
Referenced by _update_rangefinder().
_update_airspeed()
void SITL_State::_update_airspeed (float airspeed) private
Definition at line 51 of file sitl_airspeed.cpp.
Referenced by _fdm_input_step(), and _sitl_setup().
_update_rangefinder()
void SITL_State::_update_rangefinder () private
Definition at line 52 of file sitl_rangefinder.cpp.
Referenced by _fdm_input_step().
_usage()
void SITL_State::_usage (void) private
Definition at line 76 of file SITL_cmdline.cpp.
Referenced by _parse_command_line().
base_port()
uint16_t HALSITL::SITL_State::base_port (void) const inline
Definition at line 23 of file SITL_State.h.
Referenced by HALSITL::UARTDriver::_tcp_start_connection().
check_servo_input()
void SITL_State::check_servo_input (void) private
Definition at line 696 of file SITL_State.cpp.
Referenced by multicast_state_send().
get_instance()
uint8_t HALSITL::SITL_State::get_instance () const inline
Definition at line 55 of file SITL_State.h.
Referenced by HAL_SITL::get_instance().
init()
void SITL_State::init (int argc, char *const argv[]) override virtual
Implements HALSITL::SITL_State_Common.
Definition at line 561 of file SITL_State.cpp.
Referenced by HAL_SITL::run().
lookup_location()
bool SITL_State::lookup_location (const char * home_str, Location & loc, float & yaw_degrees) static
Definition at line 703 of file SITL_cmdline.cpp.
Referenced by _parse_command_line().
loop_hook()
void HALSITL::SITL_State::loop_hook (void)
multicast_servo_update()
void SITL_State::multicast_servo_update (struct sitl_input & input) private
Definition at line 714 of file SITL_State.cpp.
Referenced by _fdm_input_local().
multicast_state_open()
void SITL_State::multicast_state_open (void) private
Definition at line 616 of file SITL_State.cpp.
Referenced by multicast_state_send().
multicast_state_send()
void SITL_State::multicast_state_send (void) private
Definition at line 679 of file SITL_State.cpp.
Referenced by _fdm_input_local().
parse_home()
bool SITL_State::parse_home (const char * home_str, Location & loc, float & yaw_degrees) static
Definition at line 647 of file SITL_cmdline.cpp.
Referenced by _parse_command_line(), and lookup_location().
set_height_agl()
void SITL_State::set_height_agl (void) private
Definition at line 574 of file SITL_State.cpp.
Referenced by _fdm_input_local().
use_rtscts()
bool HALSITL::SITL_State::use_rtscts (void) const inline
Definition at line 27 of file SITL_State.h.
Referenced by HALSITL::UARTDriver::_uart_start_connection().
wait_clock()
void SITL_State::wait_clock (uint64_t wait_time_usec) private
Definition at line 181 of file SITL_State.cpp.
Referenced by HALSITL::Scheduler::delay_microseconds().
Friends And Related Symbol Documentation
HALSITL::GPIO
friend class HALSITL::GPIO friend
Definition at line 18 of file SITL_State.h.
HALSITL::Scheduler
friend class HALSITL::Scheduler friend
Definition at line 16 of file SITL_State.h.
HALSITL::Util
friend class HALSITL::Util friend
Definition at line 17 of file SITL_State.h.
Member Data Documentation
_base_port
uint16_t HALSITL::SITL_State::_base_port private
Definition at line 82 of file SITL_State.h.
Referenced by _parse_command_line(), and base_port().
_fg_address
const char* HALSITL::SITL_State::_fg_address private
Definition at line 99 of file SITL_State.h.
Referenced by _parse_command_line(), and _sitl_setup().
_fg_view_port
uint16_t HALSITL::SITL_State::_fg_view_port private
Definition at line 91 of file SITL_State.h.
Referenced by _parse_command_line(), and _sitl_setup().
_instance
uint8_t HALSITL::SITL_State::_instance private
Definition at line 81 of file SITL_State.h.
Referenced by _parse_command_line(), get_instance(), and multicast_state_open().
_irlock_port
uint16_t HALSITL::SITL_State::_irlock_port private
Definition at line 92 of file SITL_State.h.
Referenced by _parse_command_line(), and _sitl_setup().
_parent_pid
pid_t HALSITL::SITL_State::_parent_pid private
Definition at line 83 of file SITL_State.h.
Referenced by _fdm_input_step(), and _sitl_setup().
_rc_in_started
bool HALSITL::SITL_State::_rc_in_started private
Definition at line 89 of file SITL_State.h.
Referenced by _setup_fdm().
_rcin_port
uint16_t HALSITL::SITL_State::_rcin_port private
Definition at line 90 of file SITL_State.h.
Referenced by _parse_command_line(), and _setup_fdm().
_scheduler
Scheduler* HALSITL::SITL_State::_scheduler private
Definition at line 86 of file SITL_State.h.
Referenced by _fdm_input_step(), and init().
_serial_path
const char* HALSITL::SITL_State::_serial_path[9]
Initial value:
{
        "tcp:0:wait",
        "tcp:2",
        "tcp:3",
        "GPS1",
        "GPS2",
        "tcp:5",
        "tcp:6",
        "tcp:7",
        "tcp:8",
    }
Definition at line 32 of file SITL_State.h.
Referenced by HALSITL::UARTDriver::_begin(), and _parse_command_line().
_sitl_rc_in
SocketAPM_native HALSITL::SITL_State::_sitl_rc_in {true} private
Definition at line 88 of file SITL_State.h.
Referenced by _read_rc_sitl_input(), and _setup_fdm().
_synthetic_clock_mode
bool HALSITL::SITL_State::_synthetic_clock_mode private
Definition at line 94 of file SITL_State.h.
Referenced by _fdm_input_local(), _parse_command_line(), and _sitl_setup().
_update_count
uint32_t HALSITL::SITL_State::_update_count private
Definition at line 84 of file SITL_State.h.
Referenced by _fdm_input_local(), and _fdm_input_step().
_use_fg_view
bool HALSITL::SITL_State::_use_fg_view private
Definition at line 97 of file SITL_State.h.
Referenced by _fdm_input_local(), _parse_command_line(), and _sitl_setup().
_use_rtscts
bool HALSITL::SITL_State::_use_rtscts private
Definition at line 96 of file SITL_State.h.
Referenced by _parse_command_line(), and use_rtscts().
buffer_wind
VectorN<readings_wind,wind_buffer_length> HALSITL::SITL_State::buffer_wind private
Definition at line 111 of file SITL_State.h.
cmdline_param
std::vector<struct AP_Param::defaults_table_struct> HALSITL::SITL_State::cmdline_param
Definition at line 43 of file SITL_State.h.
Referenced by _parse_command_line(), and HALSITL::Util::set_cmdline_parameters().
delayed_time_wind
uint32_t HALSITL::SITL_State::delayed_time_wind private
Definition at line 113 of file SITL_State.h.
gps
SITL::GPS* HALSITL::SITL_State::gps[2] private
Definition at line 117 of file SITL_State.h.
last_store_time_wind
uint32_t HALSITL::SITL_State::last_store_time_wind private
Definition at line 110 of file SITL_State.h.
mc_out_fd
int HALSITL::SITL_State::mc_out_fd = -1 private
Definition at line 124 of file SITL_State.h.
Referenced by multicast_state_open(), and multicast_state_send().
mc_servo
uint16_t HALSITL::SITL_State::mc_servo[SITL_NUM_CHANNELS] private
Definition at line 132 of file SITL_State.h.
Referenced by check_servo_input(), and multicast_servo_update().
servo_in_fd
int HALSITL::SITL_State::servo_in_fd = -1 private
Definition at line 125 of file SITL_State.h.
Referenced by check_servo_input(), and multicast_state_open().
store_index_wind
uint8_t HALSITL::SITL_State::store_index_wind private
Definition at line 109 of file SITL_State.h.
time_delta_wind
uint32_t HALSITL::SITL_State::time_delta_wind private
Definition at line 112 of file SITL_State.h.
wind_buffer_length
const uint8_t HALSITL::SITL_State::wind_buffer_length = 50 static private
Definition at line 102 of file SITL_State.h.
wind_start_delay_micros
uint32_t HALSITL::SITL_State::wind_start_delay_micros private
Definition at line 114 of file SITL_State.h.
Referenced by _simulator_servos().
The documentation for this class was generated from the following files:
libraries/AP_HAL_SITL/SITL_State.h
libraries/AP_HAL_SITL/sitl_airspeed.cpp
libraries/AP_HAL_SITL/SITL_cmdline.cpp
libraries/AP_HAL_SITL/sitl_rangefinder.cpp
libraries/AP_HAL_SITL/SITL_State.cpp