APM:Libraries: AP_Compass_Backend Class Reference
AP_Compass_Backend Class Reference abstract
#include <AP_Compass_Backend.h>
Public Types
enum DevTypes {
DEVTYPE_HMC5883_OLD = 0x01 , DEVTYPE_HMC5883 = 0x07 , DEVTYPE_LSM303D = 0x02 , DEVTYPE_AK8963 = 0x04 ,
DEVTYPE_BMM150 = 0x05 , DEVTYPE_LSM9DS1 = 0x06 , DEVTYPE_LIS3MDL = 0x08 , DEVTYPE_AK09916 = 0x09 ,
DEVTYPE_IST8310 = 0x0A , DEVTYPE_ICM20948 = 0x0B , DEVTYPE_MMC3416 = 0x0C , DEVTYPE_QMC5883L = 0x0D ,
DEVTYPE_MAG3110 = 0x0E , DEVTYPE_SITL = 0x0F , DEVTYPE_IST8308 = 0x10 , DEVTYPE_RM3100 = 0x11 ,
DEVTYPE_RM3100_2 = 0x12 , DEVTYPE_MMC5983 = 0x13 , DEVTYPE_AK09918 = 0x14 , DEVTYPE_AK09915 = 0x15 ,
DEVTYPE_QMC5883P = 0x16
}
Public Member Functions
AP_Compass_Backend ()
virtual ~AP_Compass_Backend (void)
virtual void read (void)=0
Protected Member Functions
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
void set_last_update_usec (uint32_t last_update, uint8_t instance)
void accumulate_sample (Vector3f &field, uint8_t instance, uint32_t max_samples=10)
void drain_accumulated_samples (uint8_t instance, const Vector3f *scale=NULL)
bool register_compass (int32_t dev_id, uint8_t &instance) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void save_dev_id (uint8_t instance)
void set_external (uint8_t instance, bool external)
bool is_external (uint8_t instance)
void set_rotation (uint8_t instance, enum Rotation rotation)
enum Rotation get_board_orientation (void) const
bool field_ok (const Vector3f &field)
uint32_t get_error_count () const
Protected Attributes
Compass & _compass
HAL_Semaphore _sem
Private Member Functions
void apply_corrections (Vector3f &mag, uint8_t i)
Private Attributes
float _mean_field_length
uint32_t _error_count
Detailed Description
Definition at line 35 of file AP_Compass_Backend.h.
Member Enumeration Documentation
DevTypes
enum AP_Compass_Backend::DevTypes
Enumerator
DEVTYPE_HMC5883_OLD
DEVTYPE_HMC5883
DEVTYPE_LSM303D
DEVTYPE_AK8963
DEVTYPE_BMM150
DEVTYPE_LSM9DS1
DEVTYPE_LIS3MDL
DEVTYPE_AK09916
DEVTYPE_IST8310
DEVTYPE_ICM20948
DEVTYPE_MMC3416
DEVTYPE_QMC5883L
DEVTYPE_MAG3110
DEVTYPE_SITL
DEVTYPE_IST8308
DEVTYPE_RM3100
DEVTYPE_RM3100_2
DEVTYPE_MMC5983
DEVTYPE_AK09918
DEVTYPE_AK09915
DEVTYPE_QMC5883P
Definition at line 55 of file AP_Compass_Backend.h.
Constructor & Destructor Documentation
AP_Compass_Backend()
AP_Compass_Backend::AP_Compass_Backend ()
Definition at line 16 of file AP_Compass_Backend.cpp.
~AP_Compass_Backend()
virtual AP_Compass_Backend::~AP_Compass_Backend (void) inline virtual
Definition at line 42 of file AP_Compass_Backend.h.
Member Function Documentation
accumulate_sample()
void AP_Compass_Backend::accumulate_sample (Vector3f & field, uint8_t instance, uint32_t max_samples = 10) protected
Definition at line 139 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_HMC5843::_timer(), AP_Compass_AK09916::_update(), AP_Compass_AK8963::_update(), AP_Compass_BMM150::_update(), AP_Compass_LSM303D::_update(), AP_Compass_MAG3110::_update(), AP_Compass_LSM9DS1::_update(), AP_Compass_IST8308::timer(), AP_Compass_IST8310::timer(), AP_Compass_LIS3MDL::timer(), AP_Compass_MMC3416::timer(), AP_Compass_MMC5XX3::timer(), AP_Compass_QMC5883L::timer(), and AP_Compass_RM3100::timer().
apply_corrections()
void AP_Compass_Backend::apply_corrections (Vector3f & mag, uint8_t i) private
correct_field()
void AP_Compass_Backend::correct_field (Vector3f & mag, uint8_t i) protected
Definition at line 76 of file AP_Compass_Backend.cpp.
Referenced by accumulate_sample().
drain_accumulated_samples()
void AP_Compass_Backend::drain_accumulated_samples (uint8_t instance, const Vector3f * scale = NULL) protected
Definition at line 166 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_AK09916::read(), AP_Compass_AK8963::read(), AP_Compass_BMM150::read(), AP_Compass_HMC5843::read(), AP_Compass_IST8308::read(), AP_Compass_IST8310::read(), AP_Compass_LIS3MDL::read(), AP_Compass_LSM303D::read(), AP_Compass_LSM9DS1::read(), AP_Compass_MAG3110::read(), AP_Compass_MMC3416::read(), AP_Compass_MMC5XX3::read(), AP_Compass_QMC5883L::read(), and AP_Compass_RM3100::read().
field_ok()
bool AP_Compass_Backend::field_ok (const Vector3f & field) protected
Definition at line 261 of file AP_Compass_Backend.cpp.
Referenced by accumulate_sample().
get_board_orientation()
enum Rotation AP_Compass_Backend::get_board_orientation (void) const protected
Definition at line 297 of file AP_Compass_Backend.cpp.
get_error_count()
uint32_t AP_Compass_Backend::get_error_count () const inline protected
Definition at line 142 of file AP_Compass_Backend.h.
is_external()
bool AP_Compass_Backend::is_external (uint8_t instance) protected
Definition at line 244 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_HMC5843::_timer(), rotate_field(), and AP_Compass_QMC5883L::timer().
publish_filtered_field()
void AP_Compass_Backend::publish_filtered_field (const Vector3f & mag, uint8_t instance) protected
Definition at line 191 of file AP_Compass_Backend.cpp.
Referenced by drain_accumulated_samples().
publish_raw_field()
void AP_Compass_Backend::publish_raw_field (const Vector3f & mag, uint8_t instance) protected
Definition at line 61 of file AP_Compass_Backend.cpp.
Referenced by accumulate_sample().
read()
virtual void AP_Compass_Backend::read (void) pure virtual
Implemented in AP_Compass_AK09916, AP_Compass_AK8963, AP_Compass_BMM150, AP_Compass_HMC5843, AP_Compass_IST8308, AP_Compass_IST8310, AP_Compass_LIS3MDL, AP_Compass_LSM303D, AP_Compass_LSM9DS1, AP_Compass_MAG3110, AP_Compass_MMC3416, AP_Compass_MMC5XX3, AP_Compass_QMC5883L, AP_Compass_QMC5883P, and AP_Compass_RM3100.
Referenced by Compass::read().
register_compass()
bool AP_Compass_Backend::register_compass (int32_t dev_id, uint8_t & instance) const protected
Definition at line 211 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_AK09916::init(), AP_Compass_AK8963::init(), AP_Compass_BMM150::init(), AP_Compass_HMC5843::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_LSM9DS1::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_QMC5883L::init(), AP_Compass_RM3100::init(), AP_Compass_LSM303D::init(), and AP_Compass_MAG3110::init().
rotate_field()
void AP_Compass_Backend::rotate_field (Vector3f & mag, uint8_t instance) protected
Definition at line 21 of file AP_Compass_Backend.cpp.
Referenced by accumulate_sample().
save_dev_id()
void AP_Compass_Backend::save_dev_id (uint8_t instance) protected
Definition at line 229 of file AP_Compass_Backend.cpp.
set_dev_id()
void AP_Compass_Backend::set_dev_id (uint8_t instance, uint32_t dev_id) protected
Definition at line 220 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_AK09916::init(), AP_Compass_AK8963::init(), AP_Compass_BMM150::init(), AP_Compass_HMC5843::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_LSM9DS1::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_QMC5883L::init(), AP_Compass_RM3100::init(), AP_Compass_LSM303D::init(), and AP_Compass_MAG3110::init().
set_external()
void AP_Compass_Backend::set_external (uint8_t instance, bool external) protected
Definition at line 237 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_AK09916::init(), AP_Compass_BMM150::init(), AP_Compass_HMC5843::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_QMC5883L::init(), AP_Compass_RM3100::init(), and AP_Compass_MAG3110::init().
set_last_update_usec()
void AP_Compass_Backend::set_last_update_usec (uint32_t last_update, uint8_t instance) protected
Definition at line 201 of file AP_Compass_Backend.cpp.
set_rotation()
void AP_Compass_Backend::set_rotation (uint8_t instance, enum Rotation rotation) protected
Definition at line 250 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_AK09916::init(), AP_Compass_AK8963::init(), AP_Compass_BMM150::init(), AP_Compass_HMC5843::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_LSM9DS1::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_QMC5883L::init(), AP_Compass_RM3100::init(), AP_Compass_LSM303D::init(), and AP_Compass_MAG3110::init().
Member Data Documentation
_compass
Compass& AP_Compass_Backend::_compass protected
Definition at line 134 of file AP_Compass_Backend.h.
Referenced by accumulate_sample(), correct_field(), drain_accumulated_samples(), field_ok(), get_board_orientation(), is_external(), publish_filtered_field(), publish_raw_field(), register_compass(), rotate_field(), save_dev_id(), set_dev_id(), set_external(), set_last_update_usec(), and set_rotation().
_error_count
uint32_t AP_Compass_Backend::_error_count private
Definition at line 149 of file AP_Compass_Backend.h.
Referenced by field_ok(), and get_error_count().
_mean_field_length
float AP_Compass_Backend::_mean_field_length private
Definition at line 147 of file AP_Compass_Backend.h.
Referenced by field_ok().
_sem
HAL_Semaphore AP_Compass_Backend::_sem protected
Definition at line 137 of file AP_Compass_Backend.h.
Referenced by accumulate_sample(), and drain_accumulated_samples().
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass_Backend.h
libraries/AP_Compass/AP_Compass_Backend.cpp