APM:Libraries: AP_GPS_GSOF Class Reference
AP_GPS_GSOF Class Reference
#include <AP_GPS_GSOF.h>
Classes
struct Msg_Parser
Public Member Functions
AP_GPS_GSOF (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
AP_GPS::GPS_Status highest_supported_status (void) override WARN_IF_UNUSED
bool read () override WARN_IF_UNUSED
const char * name () const override
Public Member Functions inherited from AP_GPS_Backend
AP_GPS_Backend (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
virtual ~AP_GPS_Backend (void)
virtual bool is_configured (void) const
virtual void inject_data (const uint8_t *data, uint16_t len)
virtual void broadcast_configuration_failure_reason (void) const
virtual bool get_lag (float &lag) const
virtual bool is_healthy (void) const
virtual bool logging_healthy (void) const
void broadcast_gps_type () const
virtual void Write_AP_Logger_Log_Startup_messages () const
virtual bool prepare_for_arming (void)
virtual bool get_RTCMV3 (const uint8_t *&bytes, uint16_t &len)
virtual void clear_RTCMV3 (void)
virtual bool get_error_codes (uint32_t &error_codes) const
uint32_t get_last_itow_ms (void) const
bool option_set (const AP_GPS::DriverOptions option) const
Private Types
enum class HW_Port { COM1 = 0 , COM2 = 1 }
enum class Output_Rate { FREQ_10_HZ = 1 , FREQ_50_HZ = 15 , FREQ_100_HZ = 16 }
Private Member Functions
bool parse (const uint8_t temp) WARN_IF_UNUSED
bool process_message () WARN_IF_UNUSED
void requestBaud (const HW_Port portIndex)
void requestGSOF (const uint8_t messageType, const HW_Port portIndex, const Output_Rate rateHz)
double SwapDouble (const uint8_t *src, const uint32_t pos) const WARN_IF_UNUSED
float SwapFloat (const uint8_t *src, const uint32_t pos) const WARN_IF_UNUSED
uint32_t SwapUint32 (const uint8_t *src, const uint32_t pos) const WARN_IF_UNUSED
uint16_t SwapUint16 (const uint8_t *src, const uint32_t pos) const WARN_IF_UNUSED
bool validate_baud (const uint8_t baud) const WARN_IF_UNUSED
bool validate_com_port (const uint8_t com_port) const WARN_IF_UNUSED
Private Attributes
struct AP_GPS_GSOF::Msg_Parser msg
uint8_t packetcount
uint32_t gsofmsg_time
uint8_t gsofmsgreq_index
const uint8_t gsofmsgreq [5] = {1,2,8,9,12}
Static Private Attributes
static const uint8_t STX = 0x02
static const uint8_t ETX = 0x03
Additional Inherited Members
Protected Member Functions inherited from AP_GPS_Backend
void fill_3d_velocity (void)
void velocity_to_speed_course (AP_GPS::GPS_State &s)
void make_gps_time (uint32_t bcd_date, uint32_t bcd_milliseconds)
void _detection_message (char *buffer, uint8_t buflen) const
bool should_log () const
void set_uart_timestamp (uint16_t nbytes)
void check_new_itow (uint32_t itow, uint32_t msg_length)
bool calculate_moving_base_yaw (const float reported_heading_deg, const float reported_distance, const float reported_D)
bool calculate_moving_base_yaw (AP_GPS::GPS_State &interim_state, const float reported_heading_deg, const float reported_distance, const float reported_D)
AP_GPS::GPS_Type get_type () const
virtual void set_pps_desired_freq (uint8_t freq)
void set_alt_amsl_cm (AP_GPS::GPS_State &_state, int32_t alt_amsl_cm)
Protected Attributes inherited from AP_GPS_Backend
AP_HAL::UARTDriver * port
UART we are attached to.
AP_GPS & gps
access to frontend (for parameters)
AP_GPS::GPS_State & state
public state for this instance
uint64_t _last_pps_time_us
JitterCorrection jitter_correction
uint32_t _last_itow_ms
bool _have_itow
Detailed Description
Definition at line 27 of file AP_GPS_GSOF.h.
Member Enumeration Documentation
HW_Port
enum class AP_GPS_GSOF::HW_Port strong private
Enumerator
COM1
COM2
Definition at line 46 of file AP_GPS_GSOF.h.
Output_Rate
enum class AP_GPS_GSOF::Output_Rate strong private
Enumerator
FREQ_10_HZ
FREQ_50_HZ
FREQ_100_HZ
Definition at line 53 of file AP_GPS_GSOF.h.
Constructor & Destructor Documentation
AP_GPS_GSOF()
AP_GPS_GSOF::AP_GPS_GSOF (AP_GPS & _gps, AP_GPS::GPS_State & _state, AP_HAL::UARTDriver * _port)
Definition at line 53 of file AP_GPS_GSOF.cpp.
Member Function Documentation
highest_supported_status()
AP_GPS::GPS_Status AP_GPS_GSOF::highest_supported_status (void) inline override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 32 of file AP_GPS_GSOF.h.
name()
const char * AP_GPS_GSOF::name () const inline override virtual
Implements AP_GPS_Backend.
Definition at line 39 of file AP_GPS_GSOF.h.
parse()
bool AP_GPS_GSOF::parse (const uint8_t temp) private
Definition at line 109 of file AP_GPS_GSOF.cpp.
Referenced by read().
process_message()
bool AP_GPS_GSOF::process_message (void) private
Definition at line 257 of file AP_GPS_GSOF.cpp.
Referenced by parse().
read()
bool AP_GPS_GSOF::read (void) override virtual
Implements AP_GPS_Backend.
Definition at line 79 of file AP_GPS_GSOF.cpp.
requestBaud()
void AP_GPS_GSOF::requestBaud (const HW_Port portIndex) private
Definition at line 165 of file AP_GPS_GSOF.cpp.
Referenced by AP_GPS_GSOF().
requestGSOF()
void AP_GPS_GSOF::requestGSOF (const uint8_t messageType, const HW_Port portIndex, const Output_Rate rateHz) private
Definition at line 186 of file AP_GPS_GSOF.cpp.
Referenced by read().
SwapDouble()
double AP_GPS_GSOF::SwapDouble (const uint8_t * src, const uint32_t pos) const private
Definition at line 207 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
SwapFloat()
float AP_GPS_GSOF::SwapFloat (const uint8_t * src, const uint32_t pos) const private
Definition at line 226 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
SwapUint16()
uint16_t AP_GPS_GSOF::SwapUint16 (const uint8_t * src, const uint32_t pos) const private
Definition at line 249 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
SwapUint32()
uint32_t AP_GPS_GSOF::SwapUint32 (const uint8_t * src, const uint32_t pos) const private
Definition at line 241 of file AP_GPS_GSOF.cpp.
Referenced by process_message().
validate_baud()
bool AP_GPS_GSOF::validate_baud (const uint8_t baud) const private
validate_com_port()
bool AP_GPS_GSOF::validate_com_port (const uint8_t com_port) const private
Definition at line 364 of file AP_GPS_GSOF.cpp.
Referenced by AP_GPS_GSOF(), and read().
Member Data Documentation
ETX
const uint8_t AP_GPS_GSOF::ETX = 0x03 static private
Definition at line 106 of file AP_GPS_GSOF.h.
gsofmsg_time
uint32_t AP_GPS_GSOF::gsofmsg_time private
Definition at line 109 of file AP_GPS_GSOF.h.
Referenced by AP_GPS_GSOF(), and read().
gsofmsgreq
const uint8_t AP_GPS_GSOF::gsofmsgreq[5] = {1,2,8,9,12} private
Definition at line 111 of file AP_GPS_GSOF.h.
Referenced by AP_GPS_GSOF(), and read().
gsofmsgreq_index
uint8_t AP_GPS_GSOF::gsofmsgreq_index private
Definition at line 110 of file AP_GPS_GSOF.h.
Referenced by read().
msg
struct AP_GPS_GSOF::Msg_Parser AP_GPS_GSOF::msg private
Referenced by AP_GPS_GSOF(), parse(), and process_message().
packetcount
uint8_t AP_GPS_GSOF::packetcount private
Definition at line 108 of file AP_GPS_GSOF.h.
Referenced by requestBaud(), and requestGSOF().
STX
const uint8_t AP_GPS_GSOF::STX = 0x02 static private
Definition at line 105 of file AP_GPS_GSOF.h.
Referenced by parse().
The documentation for this class was generated from the following files:
libraries/AP_GPS/AP_GPS_GSOF.h
libraries/AP_GPS/AP_GPS_GSOF.cpp