APM:Libraries: AP_Filesystem_Backend Class Reference
AP_Filesystem_Backend Class Reference
#include <AP_Filesystem_backend.h>
Public Types
enum class FormatStatus {
NOT_STARTED , PENDING , IN_PROGRESS , SUCCESS ,
FAILURE
}
Public Member Functions
virtual int open (const char *fname, int flags, bool allow_absolute_paths=false)
virtual int close (int fd)
virtual int32_t read (int fd, void *buf, uint32_t count)
virtual int32_t write (int fd, const void *buf, uint32_t count)
virtual int fsync (int fd)
virtual int32_t lseek (int fd, int32_t offset, int whence)
virtual int stat (const char *pathname, struct stat *stbuf)
virtual int unlink (const char *pathname)
virtual int mkdir (const char *pathname)
virtual void * opendir (const char *pathname)
virtual struct dirent * readdir (void *dirp)
virtual int closedir (void *dirp)
virtual int rename (const char *oldpath, const char *newpath)
virtual int64_t disk_free (const char *path)
virtual int64_t disk_space (const char *path)
virtual bool set_mtime (const char *filename, const uint32_t mtime_sec)
virtual bool retry_mount (void)
virtual void unmount (void)
virtual bool format (void)
virtual AP_Filesystem_Backend::FormatStatus get_format_status () const
virtual FileData * load_file (const char *filename)
virtual void unload_file (FileData *fd)
Protected Member Functions
bool file_op_allowed (void) const
Detailed Description
Definition at line 42 of file AP_Filesystem_backend.h.
Member Enumeration Documentation
FormatStatus
enum class AP_Filesystem_Backend::FormatStatus strong
Enumerator
NOT_STARTED
PENDING
IN_PROGRESS
SUCCESS
FAILURE
Definition at line 77 of file AP_Filesystem_backend.h.
Member Function Documentation
close()
virtual int AP_Filesystem_Backend::close (int fd) inline virtual
Reimplemented in AP_Filesystem_ESP32, AP_Filesystem_Param, AP_Filesystem_Posix, and AP_Filesystem_Sys.
Definition at line 49 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::close(), load_file(), and AP_Filesystem::open().
closedir()
virtual int AP_Filesystem_Backend::closedir (void * dirp) inline virtual
Reimplemented in AP_Filesystem_ESP32, AP_Filesystem_Posix, and AP_Filesystem_Sys.
Definition at line 59 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::closedir(), and AP_Filesystem::readdir().
disk_free()
virtual int64_t AP_Filesystem_Backend::disk_free (const char * path) inline virtual
Reimplemented in AP_Filesystem_ESP32, and AP_Filesystem_Posix.
Definition at line 63 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::disk_free().
disk_space()
virtual int64_t AP_Filesystem_Backend::disk_space (const char * path) inline virtual
Reimplemented in AP_Filesystem_ESP32, and AP_Filesystem_Posix.
Definition at line 66 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::disk_space().
file_op_allowed()
bool AP_Filesystem_Backend::file_op_allowed (void) const protected
Definition at line 69 of file AP_Filesystem_backend.cpp.
format()
virtual bool AP_Filesystem_Backend::format (void) inline virtual
Definition at line 86 of file AP_Filesystem_backend.h.
fsync()
virtual int AP_Filesystem_Backend::fsync (int fd) inline virtual
Reimplemented in AP_Filesystem_ESP32, and AP_Filesystem_Posix.
Definition at line 52 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::fsync().
get_format_status()
virtual AP_Filesystem_Backend::FormatStatus AP_Filesystem_Backend::get_format_status () const inline virtual
Definition at line 87 of file AP_Filesystem_backend.h.
load_file()
FileData * AP_Filesystem_Backend::load_file (const char * filename) virtual
Definition at line 24 of file AP_Filesystem_backend.cpp.
Referenced by AP_Filesystem::load_file().
lseek()
virtual int32_t AP_Filesystem_Backend::lseek (int fd, int32_t offset, int whence) inline virtual
Reimplemented in AP_Filesystem_ESP32, AP_Filesystem_Param, AP_Filesystem_Posix, and AP_Filesystem_Sys.
Definition at line 53 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::lseek().
mkdir()
virtual int AP_Filesystem_Backend::mkdir (const char * pathname) inline virtual
Reimplemented in AP_Filesystem_ESP32, and AP_Filesystem_Posix.
Definition at line 56 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::mkdir().
open()
virtual int AP_Filesystem_Backend::open (const char * fname, int flags, bool allow_absolute_paths = false) inline virtual
Reimplemented in AP_Filesystem_ESP32, AP_Filesystem_Param, AP_Filesystem_Posix, and AP_Filesystem_Sys.
Definition at line 46 of file AP_Filesystem_backend.h.
Referenced by load_file(), and AP_Filesystem::open().
opendir()
virtual void * AP_Filesystem_Backend::opendir (const char * pathname) inline virtual
Reimplemented in AP_Filesystem_ESP32, AP_Filesystem_Posix, and AP_Filesystem_Sys.
Definition at line 57 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::opendir(), and AP_Filesystem::readdir().
read()
virtual int32_t AP_Filesystem_Backend::read (int fd, void * buf, uint32_t count) inline virtual
Reimplemented in AP_Filesystem_ESP32, AP_Filesystem_Param, AP_Filesystem_Posix, and AP_Filesystem_Sys.
Definition at line 50 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::fgets(), load_file(), and AP_Filesystem::read().
readdir()
virtual struct dirent * AP_Filesystem_Backend::readdir (void * dirp) inline virtual
Reimplemented in AP_Filesystem_ESP32, AP_Filesystem_Posix, and AP_Filesystem_Sys.
Definition at line 58 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::readdir().
rename()
virtual int AP_Filesystem_Backend::rename (const char * oldpath, const char * newpath) inline virtual
Reimplemented in AP_Filesystem_ESP32, and AP_Filesystem_Posix.
Definition at line 60 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::rename().
retry_mount()
virtual bool AP_Filesystem_Backend::retry_mount (void) inline virtual
Definition at line 72 of file AP_Filesystem_backend.h.
set_mtime()
virtual bool AP_Filesystem_Backend::set_mtime (const char * filename, const uint32_t mtime_sec) inline virtual
Reimplemented in AP_Filesystem_ESP32, and AP_Filesystem_Posix.
Definition at line 69 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::set_mtime().
stat()
virtual int AP_Filesystem_Backend::stat (const char * pathname, struct stat * stbuf) inline virtual
Reimplemented in AP_Filesystem_ESP32, AP_Filesystem_Param, AP_Filesystem_Posix, and AP_Filesystem_Sys.
Definition at line 54 of file AP_Filesystem_backend.h.
Referenced by load_file(), and AP_Filesystem::stat().
unlink()
virtual int AP_Filesystem_Backend::unlink (const char * pathname) inline virtual
Reimplemented in AP_Filesystem_ESP32, and AP_Filesystem_Posix.
Definition at line 55 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::unlink().
unload_file()
void AP_Filesystem_Backend::unload_file (FileData * fd) virtual
Definition at line 60 of file AP_Filesystem_backend.cpp.
unmount()
virtual void AP_Filesystem_Backend::unmount (void) inline virtual
Definition at line 75 of file AP_Filesystem_backend.h.
write()
virtual int32_t AP_Filesystem_Backend::write (int fd, const void * buf, uint32_t count) inline virtual
Reimplemented in AP_Filesystem_ESP32, AP_Filesystem_Param, and AP_Filesystem_Posix.
Definition at line 51 of file AP_Filesystem_backend.h.
Referenced by AP_Filesystem::write().
The documentation for this class was generated from the following files:
libraries/AP_Filesystem/AP_Filesystem_backend.h
libraries/AP_Filesystem/AP_Filesystem_backend.cpp