APM:Libraries: AP_Compass_AK09916 Class Reference
AP_Compass_AK09916 Class Reference
#include <AP_Compass_AK09916.h>
Classes
struct sample_regs
Public Member Functions
virtual ~AP_Compass_AK09916 ()
void read () override
Public Member Functions inherited from AP_Compass_Backend
AP_Compass_Backend ()
virtual ~AP_Compass_Backend (void)
Static Public Member Functions
static AP_Compass_Backend * probe (AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, bool force_external, enum Rotation rotation)
static AP_Compass_Backend * probe_ICM20948 (AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev_icm, bool force_external, enum Rotation rotation)
static AP_Compass_Backend * probe_ICM20948 (uint8_t mpu9250_instance, enum Rotation rotation)
static AP_Compass_Backend * probe_ICM20948_SPI (uint8_t mpu9250_instance, enum Rotation rotation)
static AP_Compass_Backend * probe_ICM20948_I2C (uint8_t mpu9250_instance, enum Rotation rotation)
Static Public Attributes
static constexpr const char * name = "AK09916"
Private Member Functions
AP_Compass_AK09916 (AP_AK09916_BusDriver *bus, bool force_external, enum Rotation rotation)
bool init ()
void _make_factory_sensitivity_adjustment (Vector3f &field) const
void _make_adc_sensitivity_adjustment (Vector3f &field) const
bool _reset ()
bool _setup_mode ()
bool _check_id ()
bool _calibrate ()
void _update ()
Private Attributes
AP_AK09916_BusDriver * _bus
bool _force_external
uint8_t _compass_instance
bool _initialized
enum Rotation _rotation
enum AP_Compass_Backend::DevTypes _devtype
uint8_t no_data
Additional Inherited Members
Public Types inherited from AP_Compass_Backend
enum DevTypes {
DEVTYPE_HMC5883_OLD = 0x01 , DEVTYPE_HMC5883 = 0x07 , DEVTYPE_LSM303D = 0x02 , DEVTYPE_AK8963 = 0x04 ,
DEVTYPE_BMM150 = 0x05 , DEVTYPE_LSM9DS1 = 0x06 , DEVTYPE_LIS3MDL = 0x08 , DEVTYPE_AK09916 = 0x09 ,
DEVTYPE_IST8310 = 0x0A , DEVTYPE_ICM20948 = 0x0B , DEVTYPE_MMC3416 = 0x0C , DEVTYPE_QMC5883L = 0x0D ,
DEVTYPE_MAG3110 = 0x0E , DEVTYPE_SITL = 0x0F , DEVTYPE_IST8308 = 0x10 , DEVTYPE_RM3100 = 0x11 ,
DEVTYPE_RM3100_2 = 0x12 , DEVTYPE_MMC5983 = 0x13 , DEVTYPE_AK09918 = 0x14 , DEVTYPE_AK09915 = 0x15 ,
DEVTYPE_QMC5883P = 0x16
}
Protected Member Functions inherited from AP_Compass_Backend
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
void set_last_update_usec (uint32_t last_update, uint8_t instance)
void accumulate_sample (Vector3f &field, uint8_t instance, uint32_t max_samples=10)
void drain_accumulated_samples (uint8_t instance, const Vector3f *scale=NULL)
bool register_compass (int32_t dev_id, uint8_t &instance) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void save_dev_id (uint8_t instance)
void set_external (uint8_t instance, bool external)
bool is_external (uint8_t instance)
void set_rotation (uint8_t instance, enum Rotation rotation)
enum Rotation get_board_orientation (void) const
bool field_ok (const Vector3f &field)
uint32_t get_error_count () const
Protected Attributes inherited from AP_Compass_Backend
Compass & _compass
HAL_Semaphore _sem
Detailed Description
Definition at line 47 of file AP_Compass_AK09916.h.
Constructor & Destructor Documentation
~AP_Compass_AK09916()
AP_Compass_AK09916::~AP_Compass_AK09916 () virtual
Definition at line 70 of file AP_Compass_AK09916.cpp.
AP_Compass_AK09916()
AP_Compass_AK09916::AP_Compass_AK09916 (AP_AK09916_BusDriver * bus, bool force_external, enum Rotation rotation) private
Definition at line 61 of file AP_Compass_AK09916.cpp.
Referenced by probe(), probe_ICM20948_I2C(), and probe_ICM20948_SPI().
Member Function Documentation
_calibrate()
bool AP_Compass_AK09916::_calibrate () private
_check_id()
bool AP_Compass_AK09916::_check_id () private
Definition at line 337 of file AP_Compass_AK09916.cpp.
Referenced by init().
_make_adc_sensitivity_adjustment()
void AP_Compass_AK09916::_make_adc_sensitivity_adjustment (Vector3f & field) const private
Definition at line 290 of file AP_Compass_AK09916.cpp.
Referenced by _update().
_make_factory_sensitivity_adjustment()
void AP_Compass_AK09916::_make_factory_sensitivity_adjustment (Vector3f & field) const private
_reset()
bool AP_Compass_AK09916::_reset () private
Definition at line 365 of file AP_Compass_AK09916.cpp.
Referenced by _update(), and init().
_setup_mode()
bool AP_Compass_AK09916::_setup_mode () private
Definition at line 361 of file AP_Compass_AK09916.cpp.
Referenced by _update(), and init().
_update()
void AP_Compass_AK09916::_update () private
Definition at line 297 of file AP_Compass_AK09916.cpp.
Referenced by init().
init()
bool AP_Compass_AK09916::init () private
Definition at line 220 of file AP_Compass_AK09916.cpp.
Referenced by probe(), probe_ICM20948_I2C(), and probe_ICM20948_SPI().
probe()
AP_Compass_Backend * AP_Compass_AK09916::probe (AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, bool force_external, enum Rotation rotation) static
Definition at line 75 of file AP_Compass_AK09916.cpp.
Referenced by Compass::_probe_external_i2c_compasses(), and probe_ICM20948().
probe_ICM20948() [1/2]
AP_Compass_Backend * AP_Compass_AK09916::probe_ICM20948 (AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev_icm, bool force_external, enum Rotation rotation) static
Definition at line 97 of file AP_Compass_AK09916.cpp.
Referenced by Compass::_probe_external_i2c_compasses(), and Compass::probe_i2c_spi_compasses().
probe_ICM20948() [2/2]
AP_Compass_Backend * AP_Compass_AK09916::probe_ICM20948 (uint8_t mpu9250_instance, enum Rotation rotation) static
Definition at line 169 of file AP_Compass_AK09916.cpp.
probe_ICM20948_I2C()
AP_Compass_Backend * AP_Compass_AK09916::probe_ICM20948_I2C (uint8_t mpu9250_instance, enum Rotation rotation) static
Definition at line 199 of file AP_Compass_AK09916.cpp.
probe_ICM20948_SPI()
AP_Compass_Backend * AP_Compass_AK09916::probe_ICM20948_SPI (uint8_t mpu9250_instance, enum Rotation rotation) static
Definition at line 175 of file AP_Compass_AK09916.cpp.
Referenced by probe_ICM20948().
read()
void AP_Compass_AK09916::read (void) override virtual
Implements AP_Compass_Backend.
Definition at line 281 of file AP_Compass_AK09916.cpp.
Member Data Documentation
_bus
AP_AK09916_BusDriver* AP_Compass_AK09916::_bus private
Definition at line 101 of file AP_Compass_AK09916.h.
Referenced by _check_id(), _reset(), _setup_mode(), _update(), init(), and ~AP_Compass_AK09916().
_compass_instance
uint8_t AP_Compass_AK09916::_compass_instance private
Definition at line 104 of file AP_Compass_AK09916.h.
Referenced by _update(), init(), and read().
_devtype
enum AP_Compass_Backend::DevTypes AP_Compass_AK09916::_devtype private
Definition at line 107 of file AP_Compass_AK09916.h.
Referenced by _check_id(), and init().
_force_external
bool AP_Compass_AK09916::_force_external private
Definition at line 103 of file AP_Compass_AK09916.h.
Referenced by init().
_initialized
bool AP_Compass_AK09916::_initialized private
Definition at line 105 of file AP_Compass_AK09916.h.
Referenced by init(), and read().
_rotation
enum Rotation AP_Compass_AK09916::_rotation private
Definition at line 106 of file AP_Compass_AK09916.h.
Referenced by init().
name
constexpr const char* AP_Compass_AK09916::name = "AK09916" static constexpr
Definition at line 72 of file AP_Compass_AK09916.h.
no_data
uint8_t AP_Compass_AK09916::no_data private
Definition at line 108 of file AP_Compass_AK09916.h.
Referenced by _update().
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass_AK09916.h
libraries/AP_Compass/AP_Compass_AK09916.cpp