APM:Libraries: AP_DAL Class Reference
AP_DAL Class Reference
#include <AP_DAL.h>
Public Types
enum class FrameType : uint8_t {
InitialiseFilterEKF2 = 1U<<0 , UpdateFilterEKF2 = 1U<<1 , InitialiseFilterEKF3 = 1<<2 , UpdateFilterEKF3 = 1<<3 ,
LogWriteEKF2 = 1<<4 , LogWriteEKF3 = 1<<5
}
enum class Event : uint8_t {
resetGyroBias = 0 , resetHeightDatum = 1 , setTerrainHgtStable = 9 , unsetTerrainHgtStable = 10 ,
requestYawReset = 11 , checkLaneSwitch = 12 , setSourceSet0 = 13 , setSourceSet1 = 14 ,
setSourceSet2 = 15
}
enum class VehicleClass : uint8_t {
UNKNOWN , GROUND , COPTER , FIXED_WING ,
SUBMARINE
}
enum class StateMask { ARMED = (1U<<0) }
enum class EKFType : uint8_t { EKF2 = 0 , EKF3 = 1 }
enum Memory_Type { MEM_DMA_SAFE , MEM_FAST }
Public Member Functions
AP_DAL ()
void start_frame (FrameType frametype)
void end_frame (void)
uint64_t micros64 () const
uint32_t micros () const
uint32_t millis () const
void log_event2 (Event event)
void log_SetOriginLLH2 (const Location &loc)
void log_writeDefaultAirSpeed2 (const float aspeed, const float uncertainty)
void log_event3 (Event event)
void log_SetOriginLLH3 (const Location &loc)
void log_SetLatLng (const Location &loc, float posAccuracy, uint32_t timestamp_ms)
void log_writeDefaultAirSpeed3 (const float aspeed, const float uncertainty)
void log_writeEulerYawAngle (float yawAngle, float yawAngleErr, uint32_t timeStamp_ms, uint8_t type)
bool ekf_low_time_remaining (EKFType etype, uint8_t core)
bool get_armed () const
uint32_t available_memory () const
int8_t get_ekf_type (void) const
int snprintf (char *str, size_t size, const char *format,...) const
void * malloc_type (size_t size, enum Memory_Type mem_type) const
AP_DAL_InertialSensor & ins ()
AP_DAL_Baro & baro ()
AP_DAL_GPS & gps ()
AP_DAL_RangeFinder * rangefinder ()
AP_DAL_Airspeed * airspeed ()
AP_DAL_Compass & compass ()
bool airspeed_sensor_enabled (void) const
float get_EAS2TAS (void) const
VehicleClass get_vehicle_class (void) const
bool get_fly_forward (void) const
bool get_takeoff_expected (void) const
bool get_touchdown_expected (void) const
void set_takeoff_expected ()
const Vector3f & get_trim () const
const Matrix3f & get_rotation_vehicle_body_to_autopilot_body (void) const
const class Location & get_home (void) const
uint32_t get_time_flying_ms (void) const
bool opticalflow_enabled (void) const
bool wheelencoder_enabled (void) const
void writeOptFlowMeas (const uint8_t rawFlowQuality, const Vector2f &rawFlowRates, const Vector2f &rawGyroRates, const uint32_t msecFlowMeas, const Vector3f &posOffset, float heightOverride)
void writeExtNavData (const Vector3f &pos, const Quaternion &quat, float posErr, float angErr, uint32_t timeStamp_ms, uint16_t delay_ms, uint32_t resetTime_ms)
void writeExtNavVelData (const Vector3f &vel, float err, uint32_t timeStamp_ms, uint16_t delay_ms)
void writeWheelOdom (float delAng, float delTime, uint32_t timeStamp_ms, const Vector3f &posOffset, float radius)
void writeBodyFrameOdom (float quality, const Vector3f &delPos, const Vector3f &delAng, float delTime, uint32_t timeStamp_ms, uint16_t delay_ms, const Vector3f &posOffset)
void handle_message (const log_RFRH &msg)
void handle_message (const log_RFRN &msg)
void handle_message (const log_RFRF &msg, NavEKF2 &ekf2, NavEKF3 &ekf3)
void handle_message (const log_RISH &msg)
void handle_message (const log_RISI &msg)
void handle_message (const log_RASH &msg)
void handle_message (const log_RASI &msg)
void handle_message (const log_RBRH &msg)
void handle_message (const log_RBRI &msg)
void handle_message (const log_RRNH &msg)
void handle_message (const log_RRNI &msg)
void handle_message (const log_RGPH &msg)
void handle_message (const log_RGPI &msg)
void handle_message (const log_RGPJ &msg)
void handle_message (const log_RMGH &msg)
void handle_message (const log_RMGI &msg)
void handle_message (const log_RBCH &msg)
void handle_message (const log_RBCI &msg)
void handle_message (const log_RVOH &msg)
void handle_message (const log_ROFH &msg, NavEKF2 &ekf2, NavEKF3 &ekf3)
void handle_message (const log_REPH &msg, NavEKF2 &ekf2, NavEKF3 &ekf3)
void handle_message (const log_REVH &msg, NavEKF2 &ekf2, NavEKF3 &ekf3)
void handle_message (const log_RWOH &msg, NavEKF2 &ekf2, NavEKF3 &ekf3)
void handle_message (const log_RBOH &msg, NavEKF2 &ekf2, NavEKF3 &ekf3)
void handle_message (const log_RSLL &msg, NavEKF2 &ekf2, NavEKF3 &ekf3)
uint8_t logging_core (uint8_t c) const
Static Public Member Functions
static AP_DAL * get_singleton ()
Private Member Functions
void init_sensors (void)
Private Attributes
struct log_RFRH _RFRH
struct log_RFRF _RFRF
struct log_RFRN _RFRN
struct log_ROFH _ROFH
struct log_REPH _REPH
struct log_REVH _REVH
struct log_RWOH _RWOH
struct log_RBOH _RBOH
struct log_RSLL _RSLL
uint32_t _micros
uint32_t _millis
Matrix3f _rotation_vehicle_body_to_autopilot_body
Location _home
uint32_t _last_imu_time_us
AP_DAL_InertialSensor _ins
AP_DAL_Baro _baro
AP_DAL_GPS _gps
AP_DAL_RangeFinder * _rangefinder
AP_DAL_Compass _compass
AP_DAL_Airspeed * _airspeed
bool ekf2_init_done
bool ekf3_init_done
bool init_done
Static Private Attributes
static AP_DAL * _singleton = nullptr
static bool logging_started
static bool force_write
Detailed Description
Definition at line 24 of file AP_DAL.h.
Member Enumeration Documentation
EKFType
enum class AP_DAL::EKFType : uint8_t strong
Enumerator
EKF2
EKF3
Definition at line 95 of file AP_DAL.h.
Event
enum class AP_DAL::Event : uint8_t strong
Enumerator
resetGyroBias
resetHeightDatum
setTerrainHgtStable
unsetTerrainHgtStable
requestYawReset
checkLaneSwitch
setSourceSet0
setSourceSet1
setSourceSet2
Definition at line 36 of file AP_DAL.h.
FrameType
enum class AP_DAL::FrameType : uint8_t strong
Enumerator
InitialiseFilterEKF2
UpdateFilterEKF2
InitialiseFilterEKF3
UpdateFilterEKF3
LogWriteEKF2
LogWriteEKF3
Definition at line 27 of file AP_DAL.h.
Memory_Type
enum AP_DAL::Memory_Type
Enumerator
MEM_DMA_SAFE
MEM_FAST
Definition at line 124 of file AP_DAL.h.
StateMask
enum class AP_DAL::StateMask strong
Enumerator
ARMED
Definition at line 90 of file AP_DAL.h.
VehicleClass
enum class AP_DAL::VehicleClass : uint8_t strong
Enumerator
UNKNOWN
GROUND
COPTER
FIXED_WING
SUBMARINE
Definition at line 56 of file AP_DAL.h.
Constructor & Destructor Documentation
AP_DAL()
AP_DAL::AP_DAL () inline
Definition at line 64 of file AP_DAL.h.
Referenced by get_singleton().
Member Function Documentation
airspeed()
AP_DAL_Airspeed * AP_DAL::airspeed () inline
Definition at line 137 of file AP_DAL.h.
Referenced by NavEKF2_core::detectFlight(), NavEKF3_core::detectFlight(), NavEKF3_core::errorScore(), NavEKF2_core::readAirSpdData(), NavEKF3_core::readAirSpdData(), NavEKF3_core::setup_core(), and NavEKF3_core::update_airspeed_selection().
airspeed_sensor_enabled()
bool AP_DAL::airspeed_sensor_enabled (void) const inline
Definition at line 154 of file AP_DAL.h.
Referenced by NavEKF2_core::detectFlight(), NavEKF3_core::setup_core(), NavEKF2_core::useAirspeed(), and NavEKF3_core::useAirspeed().
available_memory()
uint32_t AP_DAL::available_memory () const inline
Definition at line 112 of file AP_DAL.h.
Referenced by NavEKF3::InitialiseFilter(), NavEKF2_core::setup_core(), and NavEKF3_core::setup_core().
baro()
AP_DAL_Baro & AP_DAL::baro () inline
Definition at line 131 of file AP_DAL.h.
Referenced by AP_NavEKF_Source::pre_arm_check(), NavEKF2_core::readBaroData(), NavEKF3_core::readBaroData(), NavEKF2_core::resetHeightDatum(), NavEKF3_core::resetHeightDatum(), and NavEKF3_core::update_baro_selection().
compass()
AP_DAL_Compass & AP_DAL::compass () inline
Definition at line 151 of file AP_DAL.h.
Referenced by NavEKF3_core::EKFGSF_resetMainFilterYaw(), NavEKF2_core::getMagOffsets(), NavEKF3_core::getMagOffsets(), NavEKF2_core::InitialiseVariablesMag(), NavEKF3_core::InitialiseVariablesMag(), NavEKF2_core::MagDeclination(), NavEKF3_core::MagDeclination(), AP_NavEKF_Source::pre_arm_check(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), NavEKF2_core::tryChangeCompass(), NavEKF3_core::tryChangeCompass(), NavEKF3_core::update_mag_selection(), NavEKF2_core::use_compass(), and NavEKF3_core::use_compass().
ekf_low_time_remaining()
bool AP_DAL::ekf_low_time_remaining (EKFType etype, uint8_t core)
Definition at line 313 of file AP_DAL.cpp.
end_frame()
void AP_DAL::end_frame (void)
Definition at line 172 of file AP_DAL.cpp.
Referenced by log_event2(), log_event3(), log_SetLatLng(), start_frame(), writeBodyFrameOdom(), writeExtNavData(), writeExtNavVelData(), writeOptFlowMeas(), and writeWheelOdom().
get_armed()
bool AP_DAL::get_armed () const inline
Definition at line 104 of file AP_DAL.h.
Referenced by NavEKF2_core::controlFilterModes(), NavEKF3_core::controlFilterModes(), NavEKF2_core::UpdateFilter(), NavEKF3_core::UpdateFilter(), and NavEKF3::UpdateFilter().
get_EAS2TAS()
float AP_DAL::get_EAS2TAS (void) const inline
Definition at line 161 of file AP_DAL.h.
Referenced by NavEKF2_core::detectFlight(), NavEKF3_core::detectFlight(), NavEKF2_core::FuseAirspeed(), NavEKF2_core::readAirSpdData(), NavEKF3_core::readAirSpdData(), NavEKF2_core::runYawEstimatorPrediction(), and NavEKF2_core::setWindMagStateLearningMode().
get_ekf_type()
int8_t AP_DAL::get_ekf_type (void) const inline
Definition at line 117 of file AP_DAL.h.
get_fly_forward()
bool AP_DAL::get_fly_forward (void) const inline
Definition at line 169 of file AP_DAL.h.
Referenced by NavEKF2_core::assume_zero_sideslip(), and NavEKF3_core::assume_zero_sideslip().
get_home()
const class Location & AP_DAL::get_home (void) const inline
Definition at line 195 of file AP_DAL.h.
Referenced by NavEKF2_core::InitialiseFilterBootstrap(), and NavEKF3_core::InitialiseFilterBootstrap().
get_rotation_vehicle_body_to_autopilot_body()
const Matrix3f & AP_DAL::get_rotation_vehicle_body_to_autopilot_body (void) const inline
Definition at line 189 of file AP_DAL.h.
Referenced by NavEKF2_core::getRotationBodyToNED(), and NavEKF3_core::getRotationBodyToNED().
get_singleton()
static AP_DAL * AP_DAL::get_singleton () inline static
Definition at line 66 of file AP_DAL.h.
Referenced by AP::dal().
get_takeoff_expected()
bool AP_DAL::get_takeoff_expected (void) const inline
Definition at line 173 of file AP_DAL.h.
Referenced by NavEKF3_core::calcOutputStates(), NavEKF2_core::CovariancePrediction(), NavEKF3_core::detectFlight(), NavEKF3_core::FuseVelPosNED(), NavEKF2_core::readBaroData(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), NavEKF2_core::updateFilterStatus(), and NavEKF3_core::updateFilterStatus().
get_time_flying_ms()
uint32_t AP_DAL::get_time_flying_ms (void) const inline
Definition at line 199 of file AP_DAL.h.
Referenced by NavEKF2_core::detectFlight(), and NavEKF3_core::detectFlight().
get_touchdown_expected()
bool AP_DAL::get_touchdown_expected (void) const inline
Definition at line 177 of file AP_DAL.h.
Referenced by NavEKF2_core::FuseVelPosNED(), NavEKF3_core::FuseVelPosNED(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), NavEKF2_core::updateFilterStatus(), and NavEKF3_core::updateFilterStatus().
get_trim()
const Vector3f & AP_DAL::get_trim () const inline
Definition at line 185 of file AP_DAL.h.
Referenced by NavEKF2_core::getEulerAngles(), and NavEKF3_core::getEulerAngles().
get_vehicle_class()
VehicleClass AP_DAL::get_vehicle_class (void) const inline
Definition at line 165 of file AP_DAL.h.
Referenced by NavEKF2_core::assume_zero_sideslip(), and NavEKF3_core::assume_zero_sideslip().
gps()
AP_DAL_GPS & AP_DAL::gps () inline
Definition at line 132 of file AP_DAL.h.
Referenced by NavEKF2_core::calcGpsGoodForFlight(), NavEKF3_core::calcGpsGoodForFlight(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), NavEKF2_core::CorrectGPSForAntennaOffset(), NavEKF3_core::CorrectGPSForAntennaOffset(), NavEKF2_core::FuseVelPosNED(), NavEKF3_core::getGPSLLH(), NavEKF2_core::getLLH(), NavEKF2_core::getPosNE(), NavEKF3_core::getPosNE(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), AP_NavEKF_Source::pre_arm_check(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), NavEKF3_core::readGpsYawData(), NavEKF2_core::ResetHeight(), NavEKF2_core::resetHeightDatum(), NavEKF3_core::resetHeightDatum(), NavEKF3_core::setup_core(), and NavEKF3_core::update_gps_selection().
handle_message() [1/25]
void AP_DAL::handle_message (const log_RASH & msg) inline
Definition at line 243 of file AP_DAL.h.
handle_message() [2/25]
void AP_DAL::handle_message (const log_RASI & msg) inline
Definition at line 249 of file AP_DAL.h.
handle_message() [3/25]
void AP_DAL::handle_message (const log_RBCH & msg) inline
Definition at line 293 of file AP_DAL.h.
handle_message() [4/25]
void AP_DAL::handle_message (const log_RBCI & msg) inline
Definition at line 301 of file AP_DAL.h.
handle_message() [5/25]
void AP_DAL::handle_message (const log_RBOH & msg, NavEKF2 & ekf2, NavEKF3 & ekf3)
handle_message() [6/25]
void AP_DAL::handle_message (const log_RBRH & msg) inline
Definition at line 256 of file AP_DAL.h.
handle_message() [7/25]
void AP_DAL::handle_message (const log_RBRI & msg) inline
Definition at line 259 of file AP_DAL.h.
handle_message() [8/25]
void AP_DAL::handle_message (const log_REPH & msg, NavEKF2 & ekf2, NavEKF3 & ekf3)
handle_message() [9/25]
void AP_DAL::handle_message (const log_REVH & msg, NavEKF2 & ekf2, NavEKF3 & ekf3)
handle_message() [10/25]
void AP_DAL::handle_message (const log_RFRF & msg, NavEKF2 & ekf2, NavEKF3 & ekf3)
handle_message() [11/25]
void AP_DAL::handle_message (const log_RFRH & msg) inline
Definition at line 223 of file AP_DAL.h.
handle_message() [12/25]
void AP_DAL::handle_message (const log_RFRN & msg) inline
Definition at line 228 of file AP_DAL.h.
handle_message() [13/25]
void AP_DAL::handle_message (const log_RGPH & msg) inline
Definition at line 276 of file AP_DAL.h.
handle_message() [14/25]
void AP_DAL::handle_message (const log_RGPI & msg) inline
Definition at line 279 of file AP_DAL.h.
handle_message() [15/25]
void AP_DAL::handle_message (const log_RGPJ & msg) inline
Definition at line 282 of file AP_DAL.h.
handle_message() [16/25]
void AP_DAL::handle_message (const log_RISH & msg) inline
Definition at line 236 of file AP_DAL.h.
handle_message() [17/25]
void AP_DAL::handle_message (const log_RISI & msg) inline
Definition at line 239 of file AP_DAL.h.
handle_message() [18/25]
void AP_DAL::handle_message (const log_RMGH & msg) inline
Definition at line 286 of file AP_DAL.h.
handle_message() [19/25]
void AP_DAL::handle_message (const log_RMGI & msg) inline
Definition at line 289 of file AP_DAL.h.
handle_message() [20/25]
void AP_DAL::handle_message (const log_ROFH & msg, NavEKF2 & ekf2, NavEKF3 & ekf3)
handle_message() [21/25]
void AP_DAL::handle_message (const log_RRNH & msg) inline
Definition at line 263 of file AP_DAL.h.
handle_message() [22/25]
void AP_DAL::handle_message (const log_RRNI & msg) inline
Definition at line 269 of file AP_DAL.h.
handle_message() [23/25]
void AP_DAL::handle_message (const log_RSLL & msg, NavEKF2 & ekf2, NavEKF3 & ekf3)
handle_message() [24/25]
void AP_DAL::handle_message (const log_RVOH & msg) inline
Definition at line 309 of file AP_DAL.h.
handle_message() [25/25]
void AP_DAL::handle_message (const log_RWOH & msg, NavEKF2 & ekf2, NavEKF3 & ekf3)
init_sensors()
void AP_DAL::init_sensors (void) private
Definition at line 127 of file AP_DAL.cpp.
Referenced by start_frame().
ins()
AP_DAL_InertialSensor & AP_DAL::ins () inline
Definition at line 130 of file AP_DAL.h.
Referenced by NavEKF2_core::detectOptFlowTakeoff(), NavEKF3_core::detectOptFlowTakeoff(), NavEKF2::InitialiseFilter(), NavEKF3::InitialiseFilter(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), NavEKF2_core::learnInactiveBiases(), NavEKF3_core::learnInactiveBiases(), NavEKF2_core::readDeltaAngle(), NavEKF3_core::readDeltaAngle(), NavEKF2_core::readDeltaVelocity(), NavEKF3_core::readDeltaVelocity(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), NavEKF2_core::setup_core(), NavEKF3_core::setup_core(), and NavEKF3_core::updateMovementCheck().
log_event2()
void AP_DAL::log_event2 (AP_DAL::Event event)
Definition at line 180 of file AP_DAL.cpp.
Referenced by NavEKF2::checkLaneSwitch(), NavEKF2::requestYawReset(), NavEKF2::resetGyroBias(), NavEKF2::resetHeightDatum(), and NavEKF2::setTerrainHgtStable().
log_event3()
void AP_DAL::log_event3 (AP_DAL::Event event)
Definition at line 214 of file AP_DAL.cpp.
Referenced by NavEKF3::checkLaneSwitch(), NavEKF3::requestYawReset(), NavEKF3::resetGyroBias(), NavEKF3::resetHeightDatum(), NavEKF3::setPosVelYawSourceSet(), and NavEKF3::setTerrainHgtStable().
log_SetLatLng()
void AP_DAL::log_SetLatLng (const Location & loc, float posAccuracy, uint32_t timestamp_ms)
Definition at line 364 of file AP_DAL.cpp.
Referenced by NavEKF3::setLatLng().
log_SetOriginLLH2()
void AP_DAL::log_SetOriginLLH2 (const Location & loc)
Definition at line 191 of file AP_DAL.cpp.
Referenced by NavEKF2::setOriginLLH().
log_SetOriginLLH3()
void AP_DAL::log_SetOriginLLH3 (const Location & loc)
Definition at line 225 of file AP_DAL.cpp.
Referenced by NavEKF3::setOriginLLH().
log_writeDefaultAirSpeed2()
void AP_DAL::log_writeDefaultAirSpeed2 (const float aspeed, const float uncertainty)
Definition at line 203 of file AP_DAL.cpp.
Referenced by NavEKF2::writeDefaultAirSpeed().
log_writeDefaultAirSpeed3()
void AP_DAL::log_writeDefaultAirSpeed3 (const float aspeed, const float uncertainty)
Definition at line 237 of file AP_DAL.cpp.
Referenced by NavEKF3::writeDefaultAirSpeed().
log_writeEulerYawAngle()
void AP_DAL::log_writeEulerYawAngle (float yawAngle, float yawAngleErr, uint32_t timeStamp_ms, uint8_t type)
Definition at line 248 of file AP_DAL.cpp.
Referenced by NavEKF3::writeEulerYawAngle().
logging_core()
uint8_t AP_DAL::logging_core (uint8_t c) const
Definition at line 276 of file AP_DAL.cpp.
malloc_type()
void * AP_DAL::malloc_type (size_t size, enum Memory_Type mem_type) const
Definition at line 270 of file AP_DAL.cpp.
Referenced by NavEKF2::InitialiseFilter(), and NavEKF3::InitialiseFilter().
micros()
uint32_t AP_DAL::micros () const inline
Definition at line 76 of file AP_DAL.h.
Referenced by NavEKF2_core::UpdateFilter().
micros64()
uint64_t AP_DAL::micros64 () const inline
Definition at line 75 of file AP_DAL.h.
Referenced by NavEKF2::InitialiseFilter(), NavEKF3::InitialiseFilter(), NavEKF2::UpdateFilter(), NavEKF3::UpdateFilter(), NavEKF3_core::updateMovementCheck(), and NavEKF3_core::verifyTiltErrorVariance().
millis()
uint32_t AP_DAL::millis () const inline
Definition at line 77 of file AP_DAL.h.
Referenced by NavEKF2::checkLaneSwitch(), NavEKF3::checkLaneSwitch(), NavEKF3_core::FuseOptFlow(), NavEKF3_core::getVelInnovationsAndVariancesForSource(), NavEKF3_core::SelectVelPosFusion(), NavEKF3_core::setup_core(), NavEKF2_core::UpdateFilter(), NavEKF3_core::UpdateFilter(), NavEKF2::UpdateFilter(), and NavEKF3::UpdateFilter().
opticalflow_enabled()
bool AP_DAL::opticalflow_enabled (void) const inline
Definition at line 203 of file AP_DAL.h.
Referenced by AP_NavEKF_Source::pre_arm_check(), and NavEKF3_core::setup_core().
rangefinder()
AP_DAL_RangeFinder * AP_DAL::rangefinder () inline
Definition at line 134 of file AP_DAL.h.
Referenced by NavEKF2_core::getHeightControlLimit(), NavEKF3_core::getHeightControlLimit(), AP_NavEKF_Source::pre_arm_check(), NavEKF2_core::readRangeFinder(), NavEKF3_core::readRangeFinder(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), and NavEKF3_core::setup_core().
set_takeoff_expected()
void AP_DAL::set_takeoff_expected ()
Definition at line 116 of file AP_DAL.cpp.
Referenced by NavEKF3_core::calcOutputStates().
snprintf()
int AP_DAL::snprintf (char * str, size_t size, const char * format, ...) const
Definition at line 261 of file AP_DAL.cpp.
Referenced by NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), NavEKF3::pre_arm_check(), NavEKF2::pre_arm_check(), NavEKF2_core::readGpsData(), and NavEKF3_core::readGpsData().
start_frame()
void AP_DAL::start_frame (AP_DAL::FrameType frametype)
Definition at line 23 of file AP_DAL.cpp.
Referenced by NavEKF2::InitialiseFilter(), NavEKF3::InitialiseFilter(), NavEKF2::UpdateFilter(), and NavEKF3::UpdateFilter().
wheelencoder_enabled()
bool AP_DAL::wheelencoder_enabled (void) const inline
Definition at line 207 of file AP_DAL.h.
Referenced by AP_NavEKF_Source::pre_arm_check().
writeBodyFrameOdom()
void AP_DAL::writeBodyFrameOdom (float quality, const Vector3f & delPos, const Vector3f & delAng, float delTime, uint32_t timeStamp_ms, uint16_t delay_ms, const Vector3f & posOffset)
Definition at line 403 of file AP_DAL.cpp.
Referenced by NavEKF3::writeBodyFrameOdom().
writeExtNavData()
void AP_DAL::writeExtNavData (const Vector3f & pos, const Quaternion & quat, float posErr, float angErr, uint32_t timeStamp_ms, uint16_t delay_ms, uint32_t resetTime_ms)
Definition at line 349 of file AP_DAL.cpp.
Referenced by NavEKF2::writeExtNavData(), and NavEKF3::writeExtNavData().
writeExtNavVelData()
void AP_DAL::writeExtNavVelData (const Vector3f & vel, float err, uint32_t timeStamp_ms, uint16_t delay_ms)
Definition at line 376 of file AP_DAL.cpp.
Referenced by NavEKF2::writeExtNavVelData(), and NavEKF3::writeExtNavVelData().
writeOptFlowMeas()
void AP_DAL::writeOptFlowMeas (const uint8_t rawFlowQuality, const Vector2f & rawFlowRates, const Vector2f & rawGyroRates, const uint32_t msecFlowMeas, const Vector3f & posOffset, float heightOverride)
Definition at line 334 of file AP_DAL.cpp.
Referenced by NavEKF2::writeOptFlowMeas(), and NavEKF3::writeOptFlowMeas().
writeWheelOdom()
void AP_DAL::writeWheelOdom (float delAng, float delTime, uint32_t timeStamp_ms, const Vector3f & posOffset, float radius)
Definition at line 390 of file AP_DAL.cpp.
Referenced by NavEKF3::writeWheelOdom().
Member Data Documentation
_airspeed
AP_DAL_Airspeed* AP_DAL::_airspeed private
Definition at line 363 of file AP_DAL.h.
Referenced by airspeed(), handle_message(), handle_message(), init_sensors(), and start_frame().
_baro
AP_DAL_Baro AP_DAL::_baro private
Definition at line 359 of file AP_DAL.h.
Referenced by baro(), handle_message(), handle_message(), and start_frame().
_compass
AP_DAL_Compass AP_DAL::_compass private
Definition at line 362 of file AP_DAL.h.
Referenced by compass(), handle_message(), handle_message(), and start_frame().
_gps
AP_DAL_GPS AP_DAL::_gps private
Definition at line 360 of file AP_DAL.h.
Referenced by gps(), handle_message(), handle_message(), handle_message(), and start_frame().
_home
Location AP_DAL::_home private
Definition at line 355 of file AP_DAL.h.
Referenced by get_home(), handle_message(), and start_frame().
_ins
AP_DAL_InertialSensor AP_DAL::_ins private
Definition at line 358 of file AP_DAL.h.
Referenced by handle_message(), handle_message(), ins(), and start_frame().
_last_imu_time_us
uint32_t AP_DAL::_last_imu_time_us private
Definition at line 356 of file AP_DAL.h.
Referenced by start_frame().
_micros
uint32_t AP_DAL::_micros private
Definition at line 351 of file AP_DAL.h.
Referenced by handle_message(), micros(), and start_frame().
_millis
uint32_t AP_DAL::_millis private
Definition at line 352 of file AP_DAL.h.
Referenced by handle_message(), millis(), and start_frame().
_rangefinder
AP_DAL_RangeFinder* AP_DAL::_rangefinder private
Definition at line 361 of file AP_DAL.h.
Referenced by handle_message(), handle_message(), init_sensors(), rangefinder(), and start_frame().
_RBOH
struct log_RBOH AP_DAL::_RBOH private
Definition at line 347 of file AP_DAL.h.
Referenced by writeBodyFrameOdom().
_REPH
struct log_REPH AP_DAL::_REPH private
Definition at line 344 of file AP_DAL.h.
Referenced by writeExtNavData().
_REVH
struct log_REVH AP_DAL::_REVH private
Definition at line 345 of file AP_DAL.h.
Referenced by writeExtNavVelData().
_RFRF
struct log_RFRF AP_DAL::_RFRF private
Definition at line 339 of file AP_DAL.h.
Referenced by ekf_low_time_remaining(), end_frame(), and start_frame().
_RFRH
struct log_RFRH AP_DAL::_RFRH private
Definition at line 338 of file AP_DAL.h.
Referenced by get_time_flying_ms(), handle_message(), micros64(), and start_frame().
_RFRN
struct log_RFRN AP_DAL::_RFRN private
Definition at line 340 of file AP_DAL.h.
Referenced by airspeed_sensor_enabled(), available_memory(), get_armed(), get_EAS2TAS(), get_ekf_type(), get_fly_forward(), get_takeoff_expected(), get_touchdown_expected(), get_trim(), get_vehicle_class(), handle_message(), opticalflow_enabled(), start_frame(), and wheelencoder_enabled().
_ROFH
struct log_ROFH AP_DAL::_ROFH private
Definition at line 343 of file AP_DAL.h.
Referenced by writeOptFlowMeas().
_rotation_vehicle_body_to_autopilot_body
Matrix3f AP_DAL::_rotation_vehicle_body_to_autopilot_body private
Definition at line 354 of file AP_DAL.h.
Referenced by get_rotation_vehicle_body_to_autopilot_body(), and start_frame().
_RSLL
struct log_RSLL AP_DAL::_RSLL private
Definition at line 348 of file AP_DAL.h.
Referenced by log_SetLatLng().
_RWOH
struct log_RWOH AP_DAL::_RWOH private
Definition at line 346 of file AP_DAL.h.
Referenced by writeWheelOdom().
_singleton
AP_DAL * AP_DAL::_singleton = nullptr static private
Definition at line 335 of file AP_DAL.h.
Referenced by get_singleton().
ekf2_init_done
bool AP_DAL::ekf2_init_done private
Definition at line 374 of file AP_DAL.h.
ekf3_init_done
bool AP_DAL::ekf3_init_done private
Definition at line 375 of file AP_DAL.h.
force_write
bool AP_DAL::force_write static private
Definition at line 372 of file AP_DAL.h.
Referenced by start_frame().
init_done
bool AP_DAL::init_done private
Definition at line 378 of file AP_DAL.h.
Referenced by init_sensors(), and start_frame().
logging_started
bool AP_DAL::logging_started static private
Definition at line 371 of file AP_DAL.h.
Referenced by start_frame().
The documentation for this class was generated from the following files:
libraries/AP_DAL/AP_DAL.h
libraries/AP_DAL/AP_DAL.cpp