APM:Libraries: SITL::last_letter Class Reference
SITL::last_letter Class Reference
#include <SIM_last_letter.h>
Classes
struct fdm_packet
struct servo_packet
Public Member Functions
last_letter (const char *frame_str)
void update (const struct sitl_input &input) override
Static Public Member Functions
static Aircraft * create (const char *frame_str)
Private Member Functions
void recv_fdm (const struct sitl_input &input)
void send_servos (const struct sitl_input &input)
void start_last_letter (void)
Private Attributes
uint64_t last_timestamp_us
SocketAPM_native sock
Static Private Attributes
static const uint16_t fdm_port = 5002
Detailed Description
Definition at line 38 of file SIM_last_letter.h.
Constructor & Destructor Documentation
last_letter()
SITL::last_letter::last_letter (const char * frame_str)
Definition at line 34 of file SIM_last_letter.cpp.
Referenced by create().
Member Function Documentation
create()
static Aircraft * SITL::last_letter::create (const char * frame_str) inline static
Definition at line 46 of file SIM_last_letter.h.
recv_fdm()
void SITL::last_letter::recv_fdm (const struct sitl_input & input) private
Definition at line 90 of file SIM_last_letter.cpp.
Referenced by update().
send_servos()
void SITL::last_letter::send_servos (const struct sitl_input & input) private
Definition at line 79 of file SIM_last_letter.cpp.
Referenced by recv_fdm(), and update().
start_last_letter()
void SITL::last_letter::start_last_letter (void) private
Definition at line 53 of file SIM_last_letter.cpp.
Referenced by last_letter().
update()
void SITL::last_letter::update (const struct sitl_input & input) override
Definition at line 127 of file SIM_last_letter.cpp.
Member Data Documentation
fdm_port
const uint16_t SITL::last_letter::fdm_port = 5002 static private
Definition at line 51 of file SIM_last_letter.h.
Referenced by last_letter(), and send_servos().
last_timestamp_us
uint64_t SITL::last_letter::last_timestamp_us private
Definition at line 79 of file SIM_last_letter.h.
Referenced by recv_fdm().
sock
SocketAPM_native SITL::last_letter::sock private
Definition at line 80 of file SIM_last_letter.h.
Referenced by last_letter(), recv_fdm(), and send_servos().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_last_letter.h
libraries/SITL/SIM_last_letter.cpp