APM:Libraries: AP_Arming Class Reference
AP_Arming Class Reference
#include <AP_Arming.h>
Public Types
enum ArmingChecks {
ARMING_CHECK_ALL = (1U << 0) , ARMING_CHECK_BARO = (1U << 1) , ARMING_CHECK_COMPASS = (1U << 2) , ARMING_CHECK_GPS = (1U << 3) ,
ARMING_CHECK_INS = (1U << 4) , ARMING_CHECK_PARAMETERS = (1U << 5) , ARMING_CHECK_RC = (1U << 6) , ARMING_CHECK_VOLTAGE = (1U << 7) ,
ARMING_CHECK_BATTERY = (1U << 8) , ARMING_CHECK_AIRSPEED = (1U << 9) , ARMING_CHECK_LOGGING = (1U << 10) , ARMING_CHECK_SWITCH = (1U << 11) ,
ARMING_CHECK_GPS_CONFIG = (1U << 12) , ARMING_CHECK_SYSTEM = (1U << 13) , ARMING_CHECK_MISSION = (1U << 14) , ARMING_CHECK_RANGEFINDER = (1U << 15) ,
ARMING_CHECK_CAMERA = (1U << 16) , ARMING_CHECK_AUX_AUTH = (1U << 17) , ARMING_CHECK_VISION = (1U << 18) , ARMING_CHECK_FFT = (1U << 19) ,
ARMING_CHECK_OSD = (1U << 20)
}
enum class Method {
RUDDER = 0 , MAVLINK = 1 , AUXSWITCH = 2 , MOTORTEST = 3 ,
SCRIPTING = 4 , TERMINATION = 5 , CPUFAILSAFE = 6 , BATTERYFAILSAFE = 7 ,
SOLOPAUSEWHENLANDED = 8 , AFS = 9 , ADSBCOLLISIONACTION = 10 , PARACHUTE_RELEASE = 11 ,
CRASH = 12 , LANDED = 13 , MISSIONEXIT = 14 , FENCEBREACH = 15 ,
RADIOFAILSAFE = 16 , DISARMDELAY = 17 , GCSFAILSAFE = 18 , TERRRAINFAILSAFE = 19 ,
FAILSAFE_ACTION_TERMINATE = 20 , TERRAINFAILSAFE = 21 , MOTORDETECTDONE = 22 , BADFLOWOFCONTROL = 23 ,
EKFFAILSAFE = 24 , GCS_FAILSAFE_SURFACEFAILED = 25 , GCS_FAILSAFE_HOLDFAILED = 26 , TAKEOFFTIMEOUT = 27 ,
AUTOLANDED = 28 , PILOT_INPUT_FAILSAFE = 29 , TOYMODELANDTHROTTLE = 30 , TOYMODELANDFORCE = 31 ,
LANDING = 32 , DEADRECKON_FAILSAFE = 33 , BLACKBOX = 34 , DDS = 35 ,
UNKNOWN = 100
}
enum class Required { NO = 0 , YES_MIN_PWM = 1 , YES_ZERO_PWM = 2 }
enum class RudderArming { IS_DISABLED = 0 , ARMONLY = 1 , ARMDISARM = 2 }
enum class Option : int32_t { DISABLE_PREARM_DISPLAY = (1U << 0) , DISABLE_STATUSTEXT_ON_STATE_CHANGE = (1U << 1) }
Public Member Functions
AP_Arming ()
CLASS_NO_COPY (AP_Arming)
void update ()
void init (void)
Required arming_required () const
virtual bool arm (AP_Arming::Method method, bool do_arming_checks=true)
virtual bool disarm (AP_Arming::Method method, bool do_disarm_checks=true)
bool is_armed () const
bool is_armed_and_safety_off () const
uint32_t get_enabled_checks () const
virtual bool pre_arm_checks (bool report)
virtual bool arm_checks (AP_Arming::Method method)
uint16_t compass_magfield_expected () const
RudderArming get_rudder_arming_type () const
Method last_disarm_method () const
Method last_arm_method () const
bool option_enabled (Option option) const
void send_arm_disarm_statustext (const char *string) const
Static Public Member Functions
static AP_Arming * get_singleton ()
static bool method_is_GCS (Method method)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
virtual bool barometer_checks (bool report)
bool airspeed_checks (bool report)
bool logging_checks (bool report)
bool compass_checks (bool report)
virtual bool gps_checks (bool report)
bool battery_checks (bool report)
bool hardware_safety_check (bool report)
virtual bool board_voltage_checks (bool report)
virtual bool rc_calibration_checks (bool report)
bool rc_in_calibration_check (bool report)
bool rc_arm_checks (AP_Arming::Method method)
bool manual_transmitter_checks (bool report)
virtual bool mission_checks (bool report)
bool terrain_checks (bool report) const
virtual bool terrain_database_required () const
bool rangefinder_checks (bool report)
bool fence_checks (bool report)
bool camera_checks (bool display_failure)
bool osd_checks (bool display_failure) const
bool mount_checks (bool display_failure) const
bool generator_checks (bool report) const
bool opendroneid_checks (bool display_failure)
bool serial_protocol_checks (bool display_failure)
bool estop_checks (bool display_failure)
virtual bool system_checks (bool report)
bool can_checks (bool report)
bool fettec_checks (bool display_failure) const
bool servo_checks (bool report) const
bool rc_checks_copter_sub (bool display_failure, const class RC_Channel *channels[4]) const
bool visodom_checks (bool report) const
bool disarm_switch_checks (bool report) const
virtual bool mandatory_checks (bool report)
bool check_enabled (const enum AP_Arming::ArmingChecks check) const
void check_failed (const enum AP_Arming::ArmingChecks check, bool report, const char *fmt,...) const FMT_PRINTF(4
void void check_failed (bool report, const char *fmt,...) const FMT_PRINTF(3
void void void Log_Write_Arm (bool forced, AP_Arming::Method method)
void Log_Write_Disarm (bool forced, AP_Arming::Method method)
Protected Attributes
AP_Enum< Required > require
AP_Int32 checks_to_perform
AP_Float accel_error_threshold
AP_Int8 _rudder_arming
AP_Int32 _required_mission_items
AP_Int32 _arming_options
AP_Int16 magfield_error_threshold
bool armed
uint32_t last_accel_pass_ms
uint32_t last_gyro_pass_ms
Private Types
enum MIS_ITEM_CHECK {
MIS_ITEM_CHECK_LAND = (1 << 0) , MIS_ITEM_CHECK_VTOL_LAND = (1 << 1) , MIS_ITEM_CHECK_DO_LAND_START = (1 << 2) , MIS_ITEM_CHECK_TAKEOFF = (1 << 3) ,
MIS_ITEM_CHECK_VTOL_TAKEOFF = (1 << 4) , MIS_ITEM_CHECK_RALLY = (1 << 5) , MIS_ITEM_CHECK_RETURN_TO_LAUNCH = (1 << 6) , MIS_ITEM_CHECK_MAX
}
Private Member Functions
void check_forced_logging (const AP_Arming::Method method)
void update_arm_gpio ()
Private Attributes
Method _last_disarm_method = Method::UNKNOWN
Method _last_arm_method = Method::UNKNOWN
uint32_t last_prearm_display_ms
bool running_arming_checks
bool last_prearm_checks_result
bool report_immediately
Static Private Attributes
static AP_Arming * _singleton = nullptr
Detailed Description
Definition at line 11 of file AP_Arming.h.
Member Enumeration Documentation
ArmingChecks
enum AP_Arming::ArmingChecks
Enumerator
ARMING_CHECK_ALL
ARMING_CHECK_BARO
ARMING_CHECK_COMPASS
ARMING_CHECK_GPS
ARMING_CHECK_INS
ARMING_CHECK_PARAMETERS
ARMING_CHECK_RC
ARMING_CHECK_VOLTAGE
ARMING_CHECK_BATTERY
ARMING_CHECK_AIRSPEED
ARMING_CHECK_LOGGING
ARMING_CHECK_SWITCH
ARMING_CHECK_GPS_CONFIG
ARMING_CHECK_SYSTEM
ARMING_CHECK_MISSION
ARMING_CHECK_RANGEFINDER
ARMING_CHECK_CAMERA
ARMING_CHECK_AUX_AUTH
ARMING_CHECK_VISION
ARMING_CHECK_FFT
ARMING_CHECK_OSD
Definition at line 22 of file AP_Arming.h.
Method
enum class AP_Arming::Method strong
Enumerator
RUDDER
MAVLINK
AUXSWITCH
MOTORTEST
SCRIPTING
TERMINATION
CPUFAILSAFE
BATTERYFAILSAFE
SOLOPAUSEWHENLANDED
AFS
ADSBCOLLISIONACTION
PARACHUTE_RELEASE
CRASH
LANDED
MISSIONEXIT
FENCEBREACH
RADIOFAILSAFE
DISARMDELAY
GCSFAILSAFE
TERRRAINFAILSAFE
FAILSAFE_ACTION_TERMINATE
TERRAINFAILSAFE
MOTORDETECTDONE
BADFLOWOFCONTROL
EKFFAILSAFE
GCS_FAILSAFE_SURFACEFAILED
GCS_FAILSAFE_HOLDFAILED
TAKEOFFTIMEOUT
AUTOLANDED
PILOT_INPUT_FAILSAFE
TOYMODELANDTHROTTLE
TOYMODELANDFORCE
LANDING
DEADRECKON_FAILSAFE
BLACKBOX
DDS
UNKNOWN
Definition at line 46 of file AP_Arming.h.
MIS_ITEM_CHECK
enum AP_Arming::MIS_ITEM_CHECK private
Enumerator
MIS_ITEM_CHECK_LAND
MIS_ITEM_CHECK_VTOL_LAND
MIS_ITEM_CHECK_DO_LAND_START
MIS_ITEM_CHECK_TAKEOFF
MIS_ITEM_CHECK_VTOL_TAKEOFF
MIS_ITEM_CHECK_RALLY
MIS_ITEM_CHECK_RETURN_TO_LAUNCH
MIS_ITEM_CHECK_MAX
Definition at line 273 of file AP_Arming.h.
Option
enum class AP_Arming::Option : int32_t strong
Enumerator
DISABLE_PREARM_DISPLAY
DISABLE_STATUSTEXT_ON_STATE_CHANGE
Definition at line 142 of file AP_Arming.h.
Required
enum class AP_Arming::Required strong
Enumerator
NO
YES_MIN_PWM
YES_ZERO_PWM
Definition at line 86 of file AP_Arming.h.
RudderArming
enum class AP_Arming::RudderArming strong
Enumerator
IS_DISABLED
ARMONLY
ARMDISARM
Definition at line 116 of file AP_Arming.h.
Constructor & Destructor Documentation
AP_Arming()
AP_Arming::AP_Arming ()
Definition at line 170 of file AP_Arming.cpp.
Member Function Documentation
airspeed_checks()
bool AP_Arming::airspeed_checks (bool report) protected
arm()
bool AP_Arming::arm (AP_Arming::Method method, bool do_arming_checks = true) virtual
Reimplemented in Arming.
Definition at line 1653 of file AP_Arming.cpp.
Referenced by RC_Channel::do_aux_function(), and RC_Channel::do_aux_function_armdisarm().
arm_checks()
bool AP_Arming::arm_checks (AP_Arming::Method method) virtual
Definition at line 1601 of file AP_Arming.cpp.
Referenced by arm().
arming_required()
AP_Arming::Required AP_Arming::arming_required () const
Definition at line 1781 of file AP_Arming.cpp.
Referenced by is_armed(), and pre_arm_checks().
barometer_checks()
bool AP_Arming::barometer_checks (bool report) protected virtual
Definition at line 284 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
battery_checks()
bool AP_Arming::battery_checks (bool report) protected
Referenced by pre_arm_checks().
board_voltage_checks()
bool AP_Arming::board_voltage_checks (bool report) protected virtual
Definition at line 953 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
camera_checks()
bool AP_Arming::camera_checks (bool display_failure) protected
Referenced by pre_arm_checks().
can_checks()
bool AP_Arming::can_checks (bool report) protected
Referenced by pre_arm_checks().
check_enabled()
bool AP_Arming::check_enabled (const enum AP_Arming::ArmingChecks check) const protected
Definition at line 223 of file AP_Arming.cpp.
Referenced by arm_checks(), barometer_checks(), board_voltage_checks(), check_failed(), compass_checks(), hardware_safety_check(), rangefinder_checks(), system_checks(), and terrain_checks().
check_failed() [1/2]
void AP_Arming::check_failed (bool report, const char * fmt, ...) const protected
Definition at line 260 of file AP_Arming.cpp.
check_failed() [2/2]
void AP_Arming::check_failed (const enum AP_Arming::ArmingChecks check, bool report, const char * fmt, ...) const protected
Definition at line 231 of file AP_Arming.cpp.
Referenced by arm_checks(), barometer_checks(), board_voltage_checks(), compass_checks(), estop_checks(), hardware_safety_check(), rangefinder_checks(), serial_protocol_checks(), servo_checks(), system_checks(), and terrain_checks().
check_forced_logging()
void AP_Arming::check_forced_logging (const AP_Arming::Method method) private
Referenced by disarm().
CLASS_NO_COPY()
AP_Arming::CLASS_NO_COPY (AP_Arming)
compass_checks()
bool AP_Arming::compass_checks (bool report) protected
Definition at line 473 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
compass_magfield_expected()
uint16_t AP_Arming::compass_magfield_expected () const
Definition at line 200 of file AP_Arming.cpp.
disarm()
bool AP_Arming::disarm (AP_Arming::Method method, bool do_disarm_checks = true) virtual
Definition at line 1721 of file AP_Arming.cpp.
Referenced by RC_Channel::do_aux_function(), and RC_Channel::do_aux_function_armdisarm().
disarm_switch_checks()
bool AP_Arming::disarm_switch_checks (bool report) const protected
Referenced by pre_arm_checks().
estop_checks()
bool AP_Arming::estop_checks (bool display_failure) protected
Definition at line 1488 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
fence_checks()
bool AP_Arming::fence_checks (bool report) protected
Referenced by pre_arm_checks().
fettec_checks()
bool AP_Arming::fettec_checks (bool display_failure) const protected
Referenced by pre_arm_checks().
generator_checks()
bool AP_Arming::generator_checks (bool report) const protected
Referenced by pre_arm_checks().
get_enabled_checks()
uint32_t AP_Arming::get_enabled_checks () const
Definition at line 218 of file AP_Arming.cpp.
get_rudder_arming_type()
RudderArming AP_Arming::get_rudder_arming_type () const inline
Definition at line 122 of file AP_Arming.h.
get_singleton()
AP_Arming * AP_Arming::get_singleton () static
Definition at line 1947 of file AP_Arming.cpp.
Referenced by AP::arming().
gps_checks()
virtual bool AP_Arming::gps_checks (bool report) protected virtual
Referenced by pre_arm_checks().
hardware_safety_check()
bool AP_Arming::hardware_safety_check (bool report) protected
Definition at line 671 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
init()
void AP_Arming::init (void)
is_armed()
bool AP_Arming::is_armed () const
Definition at line 205 of file AP_Arming.cpp.
Referenced by is_armed_and_safety_off(), and ReplayGyroFFT::loop().
is_armed_and_safety_off()
bool AP_Arming::is_armed_and_safety_off () const
Definition at line 213 of file AP_Arming.cpp.
last_arm_method()
Method AP_Arming::last_arm_method () const inline
Definition at line 139 of file AP_Arming.h.
last_disarm_method()
Method AP_Arming::last_disarm_method () const inline
Definition at line 135 of file AP_Arming.h.
Referenced by AP_Vehicle::is_crashed().
Log_Write_Arm()
void void void AP_Arming::Log_Write_Arm (bool forced, AP_Arming::Method method) protected
Referenced by arm().
Log_Write_Disarm()
void AP_Arming::Log_Write_Disarm (bool forced, AP_Arming::Method method) protected
Referenced by disarm().
logging_checks()
bool AP_Arming::logging_checks (bool report) protected
Referenced by pre_arm_checks().
mandatory_checks()
bool AP_Arming::mandatory_checks (bool report) protected virtual
Definition at line 1641 of file AP_Arming.cpp.
Referenced by arm().
manual_transmitter_checks()
bool AP_Arming::manual_transmitter_checks (bool report) protected
Referenced by pre_arm_checks().
method_is_GCS()
static bool AP_Arming::method_is_GCS (Method method) inline static
Definition at line 152 of file AP_Arming.h.
mission_checks()
virtual bool AP_Arming::mission_checks (bool report) protected virtual
Referenced by pre_arm_checks().
mount_checks()
bool AP_Arming::mount_checks (bool display_failure) const protected
Referenced by pre_arm_checks().
opendroneid_checks()
bool AP_Arming::opendroneid_checks (bool display_failure) protected
Referenced by mandatory_checks(), and pre_arm_checks().
option_enabled()
bool AP_Arming::option_enabled (Option option) const inline
Definition at line 146 of file AP_Arming.h.
Referenced by send_arm_disarm_statustext(), and update().
osd_checks()
bool AP_Arming::osd_checks (bool display_failure) const protected
Referenced by pre_arm_checks().
pre_arm_checks()
bool AP_Arming::pre_arm_checks (bool report) virtual
Definition at line 1509 of file AP_Arming.cpp.
Referenced by arm(), and update().
rangefinder_checks()
bool AP_Arming::rangefinder_checks (bool report) protected
Definition at line 882 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
rc_arm_checks()
bool AP_Arming::rc_arm_checks (AP_Arming::Method method) protected
Referenced by arm_checks().
rc_calibration_checks()
virtual bool AP_Arming::rc_calibration_checks (bool report) protected virtual
rc_checks_copter_sub()
bool AP_Arming::rc_checks_copter_sub (bool display_failure, const class RC_Channel * channels[4]) const protected
rc_in_calibration_check()
bool AP_Arming::rc_in_calibration_check (bool report) protected
Referenced by mandatory_checks().
send_arm_disarm_statustext()
void AP_Arming::send_arm_disarm_statustext (const char * string) const
Definition at line 1773 of file AP_Arming.cpp.
serial_protocol_checks()
bool AP_Arming::serial_protocol_checks (bool display_failure) protected
Definition at line 1478 of file AP_Arming.cpp.
Referenced by mandatory_checks(), and pre_arm_checks().
servo_checks()
bool AP_Arming::servo_checks (bool report) const protected
Definition at line 900 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
system_checks()
bool AP_Arming::system_checks (bool report) protected virtual
Definition at line 1004 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
terrain_checks()
bool AP_Arming::terrain_checks (bool report) const protected
Definition at line 1106 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
terrain_database_required()
bool AP_Arming::terrain_database_required () const protected virtual
Definition at line 1090 of file AP_Arming.cpp.
Referenced by terrain_checks().
update()
void AP_Arming::update (void)
Definition at line 181 of file AP_Arming.cpp.
update_arm_gpio()
void AP_Arming::update_arm_gpio () private
Referenced by arm(), and disarm().
visodom_checks()
bool AP_Arming::visodom_checks (bool report) const protected
Referenced by pre_arm_checks().
Member Data Documentation
_arming_options
AP_Int32 AP_Arming::_arming_options protected
Definition at line 163 of file AP_Arming.h.
Referenced by option_enabled().
_last_arm_method
Method AP_Arming::_last_arm_method = Method::UNKNOWN private
Definition at line 303 of file AP_Arming.h.
Referenced by arm(), and last_arm_method().
_last_disarm_method
Method AP_Arming::_last_disarm_method = Method::UNKNOWN private
Definition at line 302 of file AP_Arming.h.
Referenced by disarm(), and last_disarm_method().
_required_mission_items
AP_Int32 AP_Arming::_required_mission_items protected
Definition at line 162 of file AP_Arming.h.
_rudder_arming
AP_Int8 AP_Arming::_rudder_arming protected
Definition at line 161 of file AP_Arming.h.
Referenced by get_rudder_arming_type().
_singleton
AP_Arming * AP_Arming::_singleton = nullptr static private
Definition at line 263 of file AP_Arming.h.
Referenced by AP_Arming(), and get_singleton().
accel_error_threshold
AP_Float AP_Arming::accel_error_threshold protected
Definition at line 160 of file AP_Arming.h.
armed
bool AP_Arming::armed protected
Definition at line 167 of file AP_Arming.h.
Referenced by arm(), Arming::arm(), disarm(), is_armed(), and pre_arm_checks().
checks_to_perform
AP_Int32 AP_Arming::checks_to_perform protected
Definition at line 159 of file AP_Arming.h.
Referenced by arm(), check_enabled(), and get_enabled_checks().
last_accel_pass_ms
uint32_t AP_Arming::last_accel_pass_ms protected
Definition at line 168 of file AP_Arming.h.
last_gyro_pass_ms
uint32_t AP_Arming::last_gyro_pass_ms protected
Definition at line 169 of file AP_Arming.h.
last_prearm_checks_result
bool AP_Arming::last_prearm_checks_result private
Definition at line 308 of file AP_Arming.h.
Referenced by pre_arm_checks().
last_prearm_display_ms
uint32_t AP_Arming::last_prearm_display_ms private
Definition at line 305 of file AP_Arming.h.
Referenced by update().
magfield_error_threshold
AP_Int16 AP_Arming::magfield_error_threshold protected
Definition at line 164 of file AP_Arming.h.
Referenced by compass_checks().
report_immediately
bool AP_Arming::report_immediately private
Definition at line 309 of file AP_Arming.h.
Referenced by pre_arm_checks(), and update().
require
AP_Enum<Required> AP_Arming::require protected
Definition at line 158 of file AP_Arming.h.
Referenced by arming_required().
running_arming_checks
bool AP_Arming::running_arming_checks private
Definition at line 306 of file AP_Arming.h.
Referenced by arm(), check_failed(), and check_failed().
var_info
const AP_Param::GroupInfo AP_Arming::var_info static
Definition at line 91 of file AP_Arming.h.
The documentation for this class was generated from the following files:
libraries/AP_Arming/AP_Arming.h
libraries/AP_Arming/AP_Arming.cpp