APM:Libraries: SocketExample Class Reference
SocketExample Class Reference
#include <SocketExample.h>
Classes
struct in_addr
Public Member Functions
SocketExample (bool _datagram)
SocketExample (bool _datagram, int _fd)
~SocketExample ()
bool connect (const char *address, uint16_t port)
bool bind (const char *address, uint16_t port)
bool reuseaddress () const
bool set_blocking (bool blocking) const
bool set_cloexec () const
void set_broadcast (void) const
ssize_t send (const void *pkt, size_t size) const
ssize_t sendto (const void *buf, size_t size, const char *address, uint16_t port)
ssize_t recv (void *pkt, size_t size, uint32_t timeout_ms)
void last_recv_address (const char *&ip_addr, uint16_t &port) const
bool pollin (uint32_t timeout_ms)
bool pollout (uint32_t timeout_ms)
bool listen (uint16_t backlog) const
SocketExample * accept (uint32_t timeout_ms)
Private Member Functions
void make_sockaddr (const char *address, uint16_t port, struct sockaddr_in &sockaddr)
Private Attributes
bool datagram
int fd = -1
Detailed Description
Definition at line 31 of file SocketExample.h.
Constructor & Destructor Documentation
SocketExample() [1/2]
SocketExample::SocketExample (bool _datagram)
Definition at line 21 of file SocketExample.cpp.
Referenced by accept().
SocketExample() [2/2]
SocketExample::SocketExample (bool _datagram, int _fd)
Definition at line 25 of file SocketExample.cpp.
~SocketExample()
SocketExample::~SocketExample ()
Definition at line 36 of file SocketExample.cpp.
Member Function Documentation
accept()
SocketExample * SocketExample::accept (uint32_t timeout_ms)
Definition at line 214 of file SocketExample.cpp.
Referenced by accept().
bind()
bool SocketExample::bind (const char * address, uint16_t port)
Definition at line 73 of file SocketExample.cpp.
Referenced by bind(), and libAP_JSON::InitSockets().
connect()
bool SocketExample::connect (const char * address, uint16_t port)
Definition at line 59 of file SocketExample.cpp.
Referenced by connect().
last_recv_address()
void SocketExample::last_recv_address (const char *& ip_addr, uint16_t & port) const
Definition at line 149 of file SocketExample.cpp.
Referenced by libAP_JSON::ReceiveServoPacket().
listen()
bool SocketExample::listen (uint16_t backlog) const
Definition at line 205 of file SocketExample.cpp.
make_sockaddr()
void SocketExample::make_sockaddr (const char * address, uint16_t port, struct sockaddr_in & sockaddr) private
Definition at line 44 of file SocketExample.cpp.
Referenced by bind(), connect(), and sendto().
pollin()
bool SocketExample::pollin (uint32_t timeout_ms)
Definition at line 164 of file SocketExample.cpp.
Referenced by accept(), and recv().
pollout()
bool SocketExample::pollout (uint32_t timeout_ms)
Definition at line 185 of file SocketExample.cpp.
recv()
ssize_t SocketExample::recv (void * pkt, size_t size, uint32_t timeout_ms)
Definition at line 137 of file SocketExample.cpp.
Referenced by libAP_JSON::ReceiveServoPacket().
reuseaddress()
bool SocketExample::reuseaddress (void) const
Definition at line 88 of file SocketExample.cpp.
Referenced by libAP_JSON::InitSockets().
send()
ssize_t SocketExample::send (const void * pkt, size_t size) const
Definition at line 119 of file SocketExample.cpp.
sendto()
ssize_t SocketExample::sendto (const void * buf, size_t size, const char * address, uint16_t port)
Definition at line 127 of file SocketExample.cpp.
Referenced by libAP_JSON::SendState().
set_blocking()
bool SocketExample::set_blocking (bool blocking) const
Definition at line 97 of file SocketExample.cpp.
Referenced by libAP_JSON::InitSockets().
set_broadcast()
void SocketExample::set_broadcast (void) const
Definition at line 155 of file SocketExample.cpp.
set_cloexec()
bool SocketExample::set_cloexec () const
Definition at line 111 of file SocketExample.cpp.
Member Data Documentation
datagram
bool SocketExample::datagram private
Definition at line 65 of file SocketExample.h.
Referenced by SocketExample().
fd
int SocketExample::fd = -1 private
Definition at line 68 of file SocketExample.h.
Referenced by accept(), bind(), connect(), listen(), pollin(), pollout(), recv(), reuseaddress(), send(), sendto(), set_blocking(), set_broadcast(), set_cloexec(), SocketExample(), and ~SocketExample().
The documentation for this class was generated from the following files:
libraries/SITL/examples/JSON/C++/SocketExample.h
libraries/SITL/examples/JSON/C++/SocketExample.cpp