APM:Libraries: AP_HAL::Util Class Reference
AP_HAL::Util Class Reference abstract
#include <Util.h>
Classes
struct PersistentData
Public Types
enum safety_state : uint8_t { SAFETY_NONE , SAFETY_DISARMED , SAFETY_ARMED }
enum class FlashBootloader {
OK =0 , NO_CHANGE =1 , FAIL =2 , NOT_AVAILABLE =3 ,
NOT_SIGNED =4
}
enum Memory_Type { MEM_DMA_SAFE , MEM_FAST , MEM_FILESYSTEM }
Public Member Functions
int snprintf (char *str, size_t size, const char *format,...) FMT_PRINTF(4
int int vsnprintf (char *str, size_t size, const char *format, va_list ap)
virtual void set_soft_armed (const bool b)
bool get_soft_armed () const
uint32_t get_last_armed_change () const
virtual bool was_watchdog_reset () const
bool was_watchdog_safety_off () const
bool was_watchdog_armed () const
virtual const char * get_custom_log_directory () const
virtual const char * get_custom_terrain_directory () const
virtual const char * get_custom_storage_directory () const
virtual const char * get_custom_defaults_file () const
virtual void set_cmdline_parameters ()
virtual bool run_debug_shell (AP_HAL::BetterStream *stream)=0
virtual enum safety_state safety_switch_state (void)
virtual void set_hw_rtc (uint64_t time_utc_usec)=0
virtual uint64_t get_hw_rtc () const =0
virtual FlashBootloader flash_bootloader ()
virtual bool get_system_id (char buf[50])
virtual bool get_system_id_unformatted (uint8_t buf[], uint8_t &len)
virtual void commandline_arguments (uint8_t &argc, char *const *&argv)
virtual bool toneAlarm_init (uint8_t types)
virtual void toneAlarm_set_buzzer_tone (float frequency, float volume, uint32_t duration_ms)
virtual AP_HAL::BetterStream * get_shell_stream ()
virtual void set_imu_temp (float current)
virtual void set_imu_target_temp (int8_t *target)
virtual void * malloc_type (size_t size, Memory_Type mem_type)
virtual void free_type (void *ptr, size_t size, Memory_Type mem_type)
virtual uint32_t available_memory (void)
virtual bool trap () const
virtual void thread_info (ExpandingString &str)
virtual void dma_info (ExpandingString &str)
virtual void mem_info (ExpandingString &str)
virtual bool load_persistent_params (ExpandingString &str) const
virtual bool get_persistent_param_by_name (const char *name, char *value, size_t &len) const
virtual void timer_info (ExpandingString &str)
virtual bool get_random_vals (uint8_t *data, size_t size)
virtual bool get_true_random_vals (uint8_t *data, size_t size, uint32_t timeout_us)
virtual void log_stack_info (void)
Public Attributes
struct PersistentData persistent_data
struct PersistentData last_persistent_data
Protected Attributes
bool soft_armed = false
uint32_t last_armed_change_ms
Detailed Description
Definition at line 9 of file Util.h.
Member Enumeration Documentation
FlashBootloader
enum class AP_HAL::Util::FlashBootloader strong
Enumerator
OK
NO_CHANGE
FAIL
NOT_AVAILABLE
NOT_SIGNED
Definition at line 107 of file Util.h.
Memory_Type
enum AP_HAL::Util::Memory_Type
Enumerator
MEM_DMA_SAFE
MEM_FAST
MEM_FILESYSTEM
Definition at line 148 of file Util.h.
safety_state
enum AP_HAL::Util::safety_state : uint8_t
Enumerator
SAFETY_NONE
SAFETY_DISARMED
SAFETY_ARMED
Definition at line 51 of file Util.h.
Member Function Documentation
available_memory()
virtual uint32_t AP_HAL::Util::available_memory (void) inline virtual
how much free memory do we have in bytes. If unknown return 4096
Reimplemented in ChibiOS::Util, ESP32::Util, Linux::Util, and HALSITL::Util.
Definition at line 171 of file Util.h.
Referenced by AP_ExpandingArrayGeneric::expand(), AP_IOMCU_FW::init(), loop(), AP_IOMCU_FW::rcout_config_update(), GCS_MAVLINK::send_meminfo(), AP_Vehicle::setup(), AP_DAL::start_frame(), and test_xplane().
commandline_arguments()
virtual void AP_HAL::Util::commandline_arguments (uint8_t & argc, char *const *& argv) inline virtual
return commandline arguments, if available
Reimplemented in Linux::Util, and HALSITL::Util.
Definition at line 131 of file Util.h.
Referenced by setup().
dma_info()
virtual void AP_HAL::Util::dma_info (ExpandingString & str) inline virtual
Definition at line 180 of file Util.h.
Referenced by AP_Filesystem_Sys::open().
flash_bootloader()
virtual FlashBootloader AP_HAL::Util::flash_bootloader () inline virtual
Reimplemented in ESP32::Util.
Definition at line 116 of file Util.h.
free_type()
virtual void AP_HAL::Util::free_type (void * ptr, size_t size, Memory_Type mem_type) inline virtual
Reimplemented in ChibiOS::Util, and ESP32::Util.
Definition at line 154 of file Util.h.
Referenced by NavEKF2::InitialiseFilter(), ChibiOS::RCOutput::setup_group_DMA(), AP_InertialSensor_Invensense::~AP_InertialSensor_Invensense(), AP_InertialSensor_Invensensev2::~AP_InertialSensor_Invensensev2(), and AP_InertialSensor_Invensensev3::~AP_InertialSensor_Invensensev3().
get_custom_defaults_file()
virtual const char * AP_HAL::Util::get_custom_defaults_file () const inline virtual
Reimplemented in ChibiOS::Util, HALSITL::Util, and Linux::Util.
Definition at line 39 of file Util.h.
Referenced by AP_Param::reload_defaults_file().
get_custom_log_directory()
virtual const char * AP_HAL::Util::get_custom_log_directory () const inline virtual
Reimplemented in Linux::Util.
Definition at line 34 of file Util.h.
get_custom_storage_directory()
virtual const char * AP_HAL::Util::get_custom_storage_directory () const inline virtual
Reimplemented in Linux::Util.
Definition at line 36 of file Util.h.
Referenced by Linux::Storage::init().
get_custom_terrain_directory()
virtual const char * AP_HAL::Util::get_custom_terrain_directory () const inline virtual
Reimplemented in Linux::Util.
Definition at line 35 of file Util.h.
get_hw_rtc()
virtual uint64_t AP_HAL::Util::get_hw_rtc () const pure virtual
Implemented in ChibiOS::Util, ESP32::Util, Linux::Util, and HALSITL::Util.
Referenced by AP_BoardConfig::init().
get_last_armed_change()
uint32_t AP_HAL::Util::get_last_armed_change () const inline
Definition at line 21 of file Util.h.
Referenced by AP_Logger::in_log_persistance().
get_persistent_param_by_name()
virtual bool AP_HAL::Util::get_persistent_param_by_name (const char * name, char * value, size_t & len) const inline virtual
Definition at line 188 of file Util.h.
get_random_vals()
virtual bool AP_HAL::Util::get_random_vals (uint8_t * data, size_t size) inline virtual
Reimplemented in ChibiOS::Util, Linux::Util, and HALSITL::Util.
Definition at line 200 of file Util.h.
Referenced by chibios_rand_generate(), loop(), and TEST().
get_shell_stream()
virtual AP_HAL::BetterStream * AP_HAL::Util::get_shell_stream () inline virtual
Definition at line 139 of file Util.h.
Referenced by GCS_MAVLINK::handle_serial_control().
get_soft_armed()
bool AP_HAL::Util::get_soft_armed () const inline
Definition at line 18 of file Util.h.
Referenced by AP_AHRS::_active_EKF_type(), Compass::_detect_runtime(), ChibiOS::Storage::_flash_erase_ok(), ESP32::Storage::_flash_erase_ok(), HALSITL::Storage::_flash_erase_ok(), AP_AHRS::_get_origin(), ChibiOS::Scheduler::_io_thread(), ESP32::Scheduler::_io_thread(), AP_GPS_UBLOX::_request_next_config(), AP_AHRS::_should_use_airspeed_sensor(), AP_MotorsUGV::active(), AP_memory_guard_error(), AP_stack_overflow(), AP_VideoTX::change_power(), AP_BattMonitor::check_failsafes(), AP_Vehicle::check_motor_noise(), SITL::XPlane::check_reload_dref(), RC_Channel::do_aux_function(), ChibiOS::RCOutput::dshot_send(), AP_Logger_Block::EraseAll(), AP_Filesystem_Backend::file_op_allowed(), AP_Filesystem::format(), AP_MSP_Telem_Backend::get_osd_flight_mode_bitmask(), AP_Spektrum_Telem::get_telem_data(), GCS_MAVLINK::handle_command_preflight_calibration(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_calibration_baro(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_reboot(), GCS_MAVLINK::handle_preflight_reboot(), GCS_MAVLINK::handle_setup_signing(), DShotLED::hw_set_rgb(), AP_Logger::in_log_persistance(), AP_TempCalibration::learn_calibration(), AP_Logger_Backend::logging_enabled(), AP_GPS_SBF::logging_healthy(), AP_SmartAudio::loop(), AP_AdvancedFailsafe::max_range_update(), AP_Vehicle::one_Hz_update(), AP_MotorsUGV::output(), AP_GPS_SBF::read(), AP_GPS_UBLOX::read(), AP_BoardConfig::safety_button_handle_pressed(), AP_Param::save(), AP_Hott_Telem::send_Vario(), AP_MotorsUGV::set_throttle(), AP_Logger_RateLimiter::should_log(), AP_DAL::start_frame(), AP_ICEngine::throttle_override(), ChibiOS::GPIO::timer_tick(), AP_Frsky_Telem::try_create_singleton_for_external_data(), AP_Camera_Backend::update(), AP_ESC_Telem_SITL::update(), AP_VideoTX::update(), AP_WindVane::update(), SITL::BalanceBot::update(), SITL::Sailboat::update(), AR_PosControl::update(), AR_WPNav::update(), AR_WPNav_OA::update(), AP_ICEngine::update(), AP_Baro::update_field_elevation(), AP_AHRS::update_orientation(), AP_RunCam::update_osd(), ChibiOS::AnalogIn::update_power_flags(), GCS::update_sensor_status_flags(), SITL::Sailboat::update_wave(), HALSITL::SITL_State::wait_clock(), and AP_Logger::Write_Power().
get_system_id()
virtual bool AP_HAL::Util::get_system_id (char buf[50]) inline virtual
Reimplemented in ChibiOS::Util, ESP32::Util, Linux::Util, and HALSITL::Util.
Definition at line 125 of file Util.h.
Referenced by LoggerMessageWriter_WriteSysInfo::process(), and GCS_MAVLINK::send_banner().
get_system_id_unformatted()
virtual bool AP_HAL::Util::get_system_id_unformatted (uint8_t buf[], uint8_t & len) inline virtual
Reimplemented in ChibiOS::Util, ESP32::Util, Linux::Util, and HALSITL::Util.
Definition at line 126 of file Util.h.
Referenced by AP_Networking::init(), AP_MSP_Telem_Backend::msp_process_out_uid(), and GCS_MAVLINK::send_autopilot_version().
get_true_random_vals()
virtual bool AP_HAL::Util::get_true_random_vals (uint8_t * data, size_t size, uint32_t timeout_us) inline virtual
Reimplemented in ChibiOS::Util.
Definition at line 203 of file Util.h.
load_persistent_params()
virtual bool AP_HAL::Util::load_persistent_params (ExpandingString & str) const inline virtual
Definition at line 186 of file Util.h.
Referenced by AP_Filesystem_Sys::open().
log_stack_info()
virtual void AP_HAL::Util::log_stack_info (void) inline virtual
Reimplemented in ChibiOS::Util.
Definition at line 206 of file Util.h.
Referenced by AP_Logger::io_thread().
malloc_type()
virtual void * AP_HAL::Util::malloc_type (size_t size, Memory_Type mem_type) inline virtual
Reimplemented in ChibiOS::Util, and ESP32::Util.
Definition at line 153 of file Util.h.
Referenced by ChibiOS::UARTDriver::_begin(), ChibiOS::SoftSigReader::attach_capture_timer(), AP_Logger_Block::Init(), AP_DAL::malloc_type(), AP_Networking::sendfile(), ChibiOS::AnalogIn::setup_adc(), ChibiOS::RCOutput::setup_group_DMA(), AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), and AP_InertialSensor_Invensensev3::start().
mem_info()
virtual void AP_HAL::Util::mem_info (ExpandingString & str) inline virtual
Reimplemented in ChibiOS::Util.
Definition at line 183 of file Util.h.
Referenced by AP_Filesystem_Sys::open().
run_debug_shell()
virtual bool AP_HAL::Util::run_debug_shell (AP_HAL::BetterStream * stream) pure virtual
Implemented in ChibiOS::Util, Empty::Util, ESP32::Util, Linux::Util, and HALSITL::Util.
safety_switch_state()
virtual enum safety_state AP_HAL::Util::safety_switch_state (void) inline virtual
Reimplemented in ChibiOS::Util, ESP32::Util, and HALSITL::Util.
Definition at line 95 of file Util.h.
Referenced by AP_ICEngine::allow_throttle_while_disarmed(), AP_BoardConfig::board_init_safety(), ChibiOS::RCOutput::dshot_send(), RGBLed::get_colour_sequence_traffic_light(), AP_Arming::hardware_safety_check(), AP_Arming::is_armed_and_safety_off(), ESP32::RCOutput::push(), ChibiOS::RCOutput::push_local(), AP_BoardConfig::safety_button_handle_pressed(), GCS::update_sensor_status_flags(), ESP32::RCOutput::write_int(), and AP_Logger::Write_Power().
set_cmdline_parameters()
virtual void AP_HAL::Util::set_cmdline_parameters () inline virtual
Reimplemented in HALSITL::Util.
Definition at line 44 of file Util.h.
Referenced by AP_Param::reload_defaults_file().
set_hw_rtc()
virtual void AP_HAL::Util::set_hw_rtc (uint64_t time_utc_usec) pure virtual
Implemented in ChibiOS::Util, ESP32::Util, Linux::Util, and HALSITL::Util.
Referenced by AP_RTC::set_utc_usec().
set_imu_target_temp()
virtual void AP_HAL::Util::set_imu_target_temp (int8_t * target) inline virtual
Reimplemented in Linux::Util.
Definition at line 145 of file Util.h.
set_imu_temp()
virtual void AP_HAL::Util::set_imu_temp (float current) inline virtual
Reimplemented in Linux::Util.
Definition at line 142 of file Util.h.
set_soft_armed()
void Util::set_soft_armed (const bool b) virtual
Reimplemented in ChibiOS::Util.
Definition at line 71 of file Util.cpp.
Referenced by ChibiOS::Util::set_soft_armed().
snprintf()
int Util::snprintf (char * str, size_t size, const char * format, ...)
Definition at line 44 of file Util.cpp.
Referenced by AP_GPS_Backend::_detection_message(), AP_HAL::RCOutput::append_to_banner(), AP_Baro::arming_checks(), AP_BattMonitor::arming_checks(), AP_Button::arming_checks(), AP_Motors::arming_checks(), AP_Parachute::arming_checks(), AP_Relay::arming_checks(), AP_RPM::arming_checks(), ChibiOS::GPIO::arming_checks(), AP_MotorsHeli::arming_checks(), AP_MotorsHeli_Dual::arming_checks(), AP_MotorsHeli_Single::arming_checks(), AP_MotorsMulticopter::arming_checks(), AP_MotorsTri::arming_checks(), AP_GPS::backends_healthy(), AP_Arming::check_failed(), AP_Arming::check_failed(), AP_Generator_IE_2400::check_for_err_code(), AP_Generator_IE_650_800::check_for_err_code(), AP_Generator_IE_2400::check_for_warning_code(), AP_BattMonitor::convert_dynamic_param_groups(), AP_RPM::convert_params(), AP_Airspeed::convert_per_instance(), AP_InternalError::errors_as_string(), GCS_MAVLINK::gen_dir_entry(), AP_Motors::get_frame_and_type_string(), ChibiOS::RCOutput::get_output_mode_banner(), GCS_MAVLINK::handle_statustext(), AP_MotorsHeli::motor_test_checks(), nmea_vaprintf(), AC_InputManager_Heli::parameter_check(), AP_AHRS::pre_arm_check(), AP_NavEKF_Source::pre_arm_check(), AP_Winch::pre_arm_check(), AP_RunCam::pre_arm_check(), AP_OSD::pre_arm_check(), AP_OAPathPlanner::pre_arm_check(), AC_AttitudeControl::pre_arm_checks(), AC_PosControl::pre_arm_checks(), RangeFinder::prearm_healthy(), SITL::GPS_FILE::publish(), AP_AHRS::set_failure_inconsistent_message(), ChibiOS::RCOutput::setup_group_DMA(), TEST(), test_printf_floats(), test_printf_null_termination(), ChibiOS::UARTDriver::thread_init(), AP_BoardConfig::throw_error(), AP_RangeFinder_Wasp::update(), and SITL::IntelligentEnergy24::update_send().
thread_info()
virtual void AP_HAL::Util::thread_info (ExpandingString & str) inline virtual
Reimplemented in ChibiOS::Util, and ESP32::Util.
Definition at line 177 of file Util.h.
Referenced by AP_Filesystem_Sys::open().
timer_info()
virtual void AP_HAL::Util::timer_info (ExpandingString & str) inline virtual
Reimplemented in ChibiOS::Util.
Definition at line 197 of file Util.h.
Referenced by AP_Filesystem_Sys::open().
toneAlarm_init()
virtual bool AP_HAL::Util::toneAlarm_init (uint8_t types) inline virtual
Reimplemented in ChibiOS::Util, and Linux::Util.
Definition at line 133 of file Util.h.
Referenced by AP_ToneAlarm::init().
toneAlarm_set_buzzer_tone()
virtual void AP_HAL::Util::toneAlarm_set_buzzer_tone (float frequency, float volume, uint32_t duration_ms) inline virtual
Reimplemented in ChibiOS::Util, and Linux::Util.
Definition at line 134 of file Util.h.
Referenced by MMLPlayer::start_note(), MMLPlayer::start_silence(), and MMLPlayer::stop().
trap()
virtual bool AP_HAL::Util::trap () const inline virtual
Reimplemented in HALSITL::Util.
Definition at line 174 of file Util.h.
Referenced by GCS_MAVLINK::handle_command_debug_trap().
vsnprintf()
int Util::vsnprintf (char * str, size_t size, const char * format, va_list ap)
Definition at line 12 of file main.cpp.
Referenced by __wrap_snprintf(), __wrap_vsnprintf(), AP_OSD_Backend::format_string_for_osd(), nmea_vaprintf(), ExpandingString::printf(), GCS::send_textv(), AP_DAL::snprintf(), snprintf(), AP_Logger::Write_MessageF(), and AP_Logger_Backend::Write_MessageF().
was_watchdog_armed()
bool AP_HAL::Util::was_watchdog_armed () const inline
Definition at line 32 of file Util.h.
Referenced by ChibiOS::Storage::_save_backup(), RangeFinder::detect_instance(), AP_Logger::init(), AP_RangeFinder_VL53L1X::init(), and AP_BoardConfig::init().
was_watchdog_reset()
virtual bool AP_HAL::Util::was_watchdog_reset () const inline virtual
Reimplemented in ChibiOS::Util, ESP32::Util, and HALSITL::Util.
Definition at line 24 of file Util.h.
Referenced by ChibiOS::Scheduler::_monitor_thread(), AP_Airspeed::calibrate(), AP_Baro::calibrate(), AP_InertialSensor::gyro_calibration_timing(), AP_AHRS::load_watchdog_home(), main_loop(), AP_Vehicle::send_watchdog_reset_statustext(), was_watchdog_armed(), and was_watchdog_safety_off().
was_watchdog_safety_off()
bool AP_HAL::Util::was_watchdog_safety_off () const inline
Definition at line 27 of file Util.h.
Referenced by AP_BoardConfig::board_init_safety(), and AP_IOMCU_FW::init().
Member Data Documentation
last_armed_change_ms
uint32_t AP_HAL::Util::last_armed_change_ms protected
Definition at line 220 of file Util.h.
Referenced by get_last_armed_change().
last_persistent_data
struct PersistentData AP_HAL::Util::last_persistent_data
Definition at line 90 of file Util.h.
Referenced by ChibiOS::Scheduler::_monitor_thread(), main_loop(), HAL_SITL::run(), and AP_Vehicle::send_watchdog_reset_statustext().
persistent_data
struct PersistentData AP_HAL::Util::persistent_data
Definition at line 88 of file Util.h.
Referenced by ChibiOS::Scheduler::_monitor_thread(), AP_stack_overflow(), ChibiOS::Scheduler::delay(), ChibiOS::SPIDevice::do_transfer(), AP_InternalError::error(), GCS_MAVLINK::handle_command_int(), GCS_MAVLINK::handle_command_long(), AP_AHRS::load_watchdog_home(), AP_Scheduler::loop(), main_loop(), HAL_SITL::run(), AP_Scheduler::run(), save_fault_watchdog(), AP_AHRS::set_home(), ChibiOS::Scheduler::try_force_mutex(), GCS_MAVLINK::update_receive(), was_watchdog_armed(), was_watchdog_safety_off(), and WithSemaphore::WithSemaphore().
soft_armed
bool AP_HAL::Util::soft_armed = false protected
Definition at line 219 of file Util.h.
Referenced by get_soft_armed().
The documentation for this class was generated from the following files:
libraries/AP_HAL/Util.h
libraries/AP_DAL/examples/AP_DAL_Standalone/main.cpp
libraries/AP_HAL/Util.cpp