APM:Libraries: SplineCurve Class Reference
SplineCurve Class Reference
#include <SplineCurve.h>
Public Member Functions
void set_speed_accel (float speed_xy, float speed_up, float speed_down, float accel_xy, float accel_z)
void set_origin_and_destination (const Vector3f &origin, const Vector3f &destination, const Vector3f &origin_vel, const Vector3f &destination_vel)
void advance_target_along_track (float dt, Vector3f &target_pos, Vector3f &target_vel)
bool reached_destination () const WARN_IF_UNUSED
const Vector3f & get_destination_vel () WARN_IF_UNUSED
float get_origin_speed_max () const WARN_IF_UNUSED
float get_destination_speed_max () const WARN_IF_UNUSED
void set_destination_speed_max (float destination_speed_max)
Private Member Functions
void calc_dt_speed_max (float time, float distance_delta, float &spline_dt, Vector3f &target_pos, Vector3f &spline_vel_unit, float &speed_max, float &accel_max)
void update_solution (const Vector3f &origin, const Vector3f &dest, const Vector3f &origin_vel, const Vector3f &dest_vel)
void calc_target_pos_vel (float time, Vector3f &position, Vector3f &velocity, Vector3f &acceleration, Vector3f &jerk)
Private Attributes
Vector3f _origin
Vector3f _destination
Vector3f _origin_vel
Vector3f _destination_vel
Vector3f _hermite_solution [4]
float _time
float _speed_xy
float _speed_up
float _speed_down
float _accel_xy
float _accel_z
float _origin_speed_max
float _destination_speed_max
bool _reached_destination
bool _zero_length
Detailed Description
Definition at line 5 of file SplineCurve.h.
Member Function Documentation
advance_target_along_track()
void SplineCurve::advance_target_along_track (float dt, Vector3f & target_pos, Vector3f & target_vel)
Definition at line 102 of file SplineCurve.cpp.
Referenced by AC_WPNav::advance_wp_target_along_track().
calc_dt_speed_max()
void SplineCurve::calc_dt_speed_max (float time, float distance_delta, float & spline_dt, Vector3f & target_pos, Vector3f & spline_vel_unit, float & speed_max, float & accel_max) private
Definition at line 134 of file SplineCurve.cpp.
Referenced by advance_target_along_track(), and set_origin_and_destination().
calc_target_pos_vel()
void SplineCurve::calc_target_pos_vel (float time, Vector3f & position, Vector3f & velocity, Vector3f & acceleration, Vector3f & jerk) private
Definition at line 233 of file SplineCurve.cpp.
Referenced by calc_dt_speed_max().
get_destination_speed_max()
float SplineCurve::get_destination_speed_max () const inline
Definition at line 33 of file SplineCurve.h.
Referenced by AC_WPNav::set_wp_destination_next().
get_destination_vel()
const Vector3f & SplineCurve::get_destination_vel () inline
Definition at line 27 of file SplineCurve.h.
Referenced by AC_WPNav::set_spline_destination(), and AC_WPNav::set_spline_destination_next().
get_origin_speed_max()
float SplineCurve::get_origin_speed_max () const inline
Definition at line 30 of file SplineCurve.h.
Referenced by AC_WPNav::set_spline_destination_next().
reached_destination()
bool SplineCurve::reached_destination () const inline
Definition at line 24 of file SplineCurve.h.
Referenced by AC_WPNav::advance_wp_target_along_track().
set_destination_speed_max()
void SplineCurve::set_destination_speed_max (float destination_speed_max) inline
Definition at line 34 of file SplineCurve.h.
Referenced by AC_WPNav::set_spline_destination_next(), and AC_WPNav::set_wp_destination_next().
set_origin_and_destination()
void SplineCurve::set_origin_and_destination (const Vector3f & origin, const Vector3f & destination, const Vector3f & origin_vel, const Vector3f & destination_vel)
Definition at line 48 of file SplineCurve.cpp.
Referenced by AC_WPNav::set_spline_destination(), and AC_WPNav::set_spline_destination_next().
set_speed_accel()
void SplineCurve::set_speed_accel (float speed_xy, float speed_up, float speed_down, float accel_xy, float accel_z)
Definition at line 34 of file SplineCurve.cpp.
Referenced by AC_WPNav::set_spline_destination(), AC_WPNav::set_spline_destination_next(), and AC_WPNav::update_track_with_speed_accel_limits().
update_solution()
void SplineCurve::update_solution (const Vector3f & origin, const Vector3f & dest, const Vector3f & origin_vel, const Vector3f & dest_vel) private
Definition at line 220 of file SplineCurve.cpp.
Referenced by set_origin_and_destination().
Member Data Documentation
_accel_xy
float SplineCurve::_accel_xy private
Definition at line 62 of file SplineCurve.h.
Referenced by calc_dt_speed_max(), and set_speed_accel().
_accel_z
float SplineCurve::_accel_z private
Definition at line 63 of file SplineCurve.h.
Referenced by calc_dt_speed_max(), and set_speed_accel().
_destination
Vector3f SplineCurve::_destination private
Definition at line 54 of file SplineCurve.h.
Referenced by advance_target_along_track(), calc_dt_speed_max(), and set_origin_and_destination().
_destination_speed_max
float SplineCurve::_destination_speed_max private
Definition at line 65 of file SplineCurve.h.
Referenced by calc_dt_speed_max(), get_destination_speed_max(), set_destination_speed_max(), and set_origin_and_destination().
_destination_vel
Vector3f SplineCurve::_destination_vel private
Definition at line 56 of file SplineCurve.h.
Referenced by get_destination_vel(), and set_origin_and_destination().
_hermite_solution
Vector3f SplineCurve::_hermite_solution[4] private
Definition at line 57 of file SplineCurve.h.
Referenced by calc_target_pos_vel(), and update_solution().
_origin
Vector3f SplineCurve::_origin private
Definition at line 53 of file SplineCurve.h.
Referenced by set_origin_and_destination().
_origin_speed_max
float SplineCurve::_origin_speed_max private
Definition at line 64 of file SplineCurve.h.
Referenced by get_origin_speed_max(), and set_origin_and_destination().
_origin_vel
Vector3f SplineCurve::_origin_vel private
Definition at line 55 of file SplineCurve.h.
Referenced by set_origin_and_destination().
_reached_destination
bool SplineCurve::_reached_destination private
Definition at line 66 of file SplineCurve.h.
Referenced by advance_target_along_track(), calc_dt_speed_max(), reached_destination(), and set_origin_and_destination().
_speed_down
float SplineCurve::_speed_down private
Definition at line 61 of file SplineCurve.h.
Referenced by calc_dt_speed_max(), and set_speed_accel().
_speed_up
float SplineCurve::_speed_up private
Definition at line 60 of file SplineCurve.h.
Referenced by calc_dt_speed_max(), and set_speed_accel().
_speed_xy
float SplineCurve::_speed_xy private
Definition at line 59 of file SplineCurve.h.
Referenced by calc_dt_speed_max(), and set_speed_accel().
_time
float SplineCurve::_time private
Definition at line 58 of file SplineCurve.h.
Referenced by advance_target_along_track(), and set_origin_and_destination().
_zero_length
bool SplineCurve::_zero_length private
Definition at line 67 of file SplineCurve.h.
Referenced by advance_target_along_track(), and set_origin_and_destination().
The documentation for this class was generated from the following files:
libraries/AP_Math/SplineCurve.h
libraries/AP_Math/SplineCurve.cpp