APM:Libraries: ExpandingString Class Reference
ExpandingString Class Reference
#include <ExpandingString.h>
Public Member Functions
const char * get_string (void) const
uint32_t get_length (void) const
char * get_writeable_string (void) const
void printf (const char *format,...) FMT_PRINTF(2
void bool append (const char *s, uint32_t len)
void set_buffer (char *s, uint32_t total_len, uint32_t used_len)
void reset ()
~ExpandingString ()
bool has_failed_allocation () const
Private Member Functions
bool expand (uint32_t min_needed) WARN_IF_UNUSED
Private Attributes
char * buf
uint32_t buflen
uint32_t used
bool allocation_failed
bool external_buffer
Detailed Description
Definition at line 25 of file ExpandingString.h.
Constructor & Destructor Documentation
~ExpandingString()
ExpandingString::~ExpandingString ()
Definition at line 109 of file ExpandingString.cpp.
Referenced by TEST().
Member Function Documentation
append()
bool ExpandingString::append (const char * s, uint32_t len)
Definition at line 94 of file ExpandingString.cpp.
Referenced by TEST(), and AP_Filesystem_Param::write().
expand()
bool ExpandingString::expand (uint32_t min_needed) private
Definition at line 30 of file ExpandingString.cpp.
Referenced by append(), and printf().
get_length()
uint32_t ExpandingString::get_length (void) const inline
Definition at line 31 of file ExpandingString.h.
Referenced by AP_Filesystem_Sys::lseek(), AP_Filesystem_Sys::open(), AP_Filesystem_Param::param_upload_parse(), AP_Filesystem_Sys::read(), TEST(), and AP_Filesystem_Param::write().
get_string()
const char * ExpandingString::get_string (void) const inline
Definition at line 28 of file ExpandingString.h.
Referenced by AP_Filesystem_Param::param_upload_parse(), AP_Filesystem_Sys::read(), and TEST().
get_writeable_string()
char * ExpandingString::get_writeable_string (void) const inline
Definition at line 34 of file ExpandingString.h.
Referenced by TEST(), and AP_Filesystem_Param::write().
has_failed_allocation()
bool ExpandingString::has_failed_allocation () const inline
Definition at line 52 of file ExpandingString.h.
Referenced by AP_Filesystem_Sys::open(), and TEST().
printf()
void ExpandingString::printf (const char * format, ...)
Definition at line 60 of file ExpandingString.cpp.
Referenced by ChibiOS::Util::mem_info(), AP::PerfInfo::TaskInfo::print(), AP_Scheduler::task_info(), TEST(), ESP32::Util::thread_info(), and ChibiOS::RCOutput::timer_info().
reset()
void ExpandingString::reset () inline
Definition at line 47 of file ExpandingString.h.
set_buffer()
void ExpandingString::set_buffer (char * s, uint32_t total_len, uint32_t used_len)
Definition at line 117 of file ExpandingString.cpp.
Referenced by AP_Filesystem_Sys::open().
Member Data Documentation
allocation_failed
bool ExpandingString::allocation_failed private
Definition at line 60 of file ExpandingString.h.
Referenced by append(), expand(), has_failed_allocation(), printf(), and set_buffer().
buf
char* ExpandingString::buf private
Definition at line 57 of file ExpandingString.h.
Referenced by append(), expand(), get_string(), get_writeable_string(), printf(), set_buffer(), and ~ExpandingString().
buflen
uint32_t ExpandingString::buflen private
Definition at line 58 of file ExpandingString.h.
Referenced by append(), expand(), printf(), and set_buffer().
external_buffer
bool ExpandingString::external_buffer private
Definition at line 61 of file ExpandingString.h.
Referenced by expand(), set_buffer(), and ~ExpandingString().
used
uint32_t ExpandingString::used private
Definition at line 59 of file ExpandingString.h.
Referenced by append(), expand(), get_length(), printf(), reset(), and set_buffer().
The documentation for this class was generated from the following files:
libraries/AP_Common/ExpandingString.h
libraries/AP_Common/ExpandingString.cpp