APM:Libraries: GCS Class Reference
GCS Class Reference abstract
global GCS object
#include <GCS.h>
Classes
struct statustext_t
class StatusTextQueue
Public Member Functions
GCS ()
virtual uint32_t custom_mode () const =0
virtual MAV_TYPE frame_type () const =0
virtual const char * frame_string () const
StatusTextQueue & statustext_queue ()
uint32_t sysid_myggcs_last_seen_time_ms () const
void sysid_myggcs_seen (uint32_t seen_time_ms)
void send_to_active_channels (uint32_t msgid, const char *pkt)
void send_text (MAV_SEVERITY severity, const char *fmt,...) FMT_PRINTF(3
void void send_textv (MAV_SEVERITY severity, const char *fmt, va_list arg_list)
virtual void send_textv (MAV_SEVERITY severity, const char *fmt, va_list arg_list, uint8_t mask)
uint8_t statustext_send_channel_mask () const
virtual GCS_MAVLINK * chan (const uint8_t ofs)=0
virtual const GCS_MAVLINK * chan (const uint8_t ofs) const =0
uint8_t num_gcs () const
void send_message (enum ap_message id)
void send_mission_item_reached_message (uint16_t mission_index)
void send_named_float (const char *name, float value) const
void send_parameter_value (const char *param_name, ap_var_type param_type, float param_value)
class MissionItemProtocol * get_prot_for_mission_type (const MAV_MISSION_TYPE mission_type) const
void try_send_queued_message_for_type (MAV_MISSION_TYPE type) const
void update_send ()
void update_receive ()
virtual uint16_t min_loop_time_remaining_for_message_send_us () const
void init ()
void setup_console ()
void setup_uarts ()
bool out_of_time () const
bool install_alternative_protocol (mavlink_channel_t chan, GCS_MAVLINK::protocol_handler_fn_t handler)
int16_t get_hud_throttle (void) const
void update_passthru ()
void get_sensor_status_flags (uint32_t &present, uint32_t &enabled, uint32_t &health)
virtual bool vehicle_initialised () const
virtual bool simple_input_active () const
virtual bool supersimple_input_active () const
MAV_RESULT set_message_interval (uint8_t port_num, uint32_t msg_id, int32_t interval_us)
uint8_t get_channel_from_port_number (uint8_t port_num)
void enable_high_latency_connections (bool enabled)
bool get_high_latency_status ()
virtual uint8_t sysid_this_mav () const =0
Static Public Member Functions
static class GCS * get_singleton ()
Public Attributes
bool high_latency_link_enabled
Static Public Attributes
static class MissionItemProtocol * missionitemprotocols [3]
Protected Member Functions
virtual GCS_MAVLINK * new_gcs_mavlink_backend (GCS_MAVLINK_Parameters &params, AP_HAL::UARTDriver &uart)=0
virtual void update_vehicle_sensor_status_flags ()
Protected Attributes
uint32_t control_sensors_present
uint32_t control_sensors_enabled
uint32_t control_sensors_health
GCS_MAVLINK_Parameters chan_parameters [MAVLINK_COMM_NUM_BUFFERS]
uint8_t _num_gcs
GCS_MAVLINK * _chan [MAVLINK_COMM_NUM_BUFFERS]
Private Member Functions
void create_gcs_mavlink_backend (GCS_MAVLINK_Parameters &params, AP_HAL::UARTDriver &uart)
void update_sensor_status_flags ()
void service_statustext (void)
void passthru_timer ()
Private Attributes
char statustext_printf_buffer [256+1]
uint32_t _sysid_mygcs_last_seen_time_ms
StatusTextQueue _statustext_queue {_status_capacity}
bool initialised_missionitemprotocol_objects
bool update_send_has_been_called
struct {
bool enabled
bool timer_installed
AP_HAL::UARTDriver * port1
AP_HAL::UARTDriver * port2
uint32_t start_ms
uint32_t last_ms
uint32_t last_port1_data_ms
uint32_t baud1
uint32_t baud2
uint8_t timeout_s
HAL_Semaphore sem
} _passthru
uint8_t first_backend_to_send
Static Private Attributes
static GCS * _singleton = nullptr
static const uint8_t _status_capacity = 7
Detailed Description
global GCS object
Definition at line 1116 of file GCS.h.
Constructor & Destructor Documentation
GCS()
GCS::GCS () inline
Definition at line 1121 of file GCS.h.
Member Function Documentation
chan() [1/2]
virtual const GCS_MAVLINK * GCS::chan (const uint8_t ofs) const pure virtual
chan() [2/2]
virtual GCS_MAVLINK * GCS::chan (const uint8_t ofs) pure virtual
Referenced by MAVLink_routing::check_and_forward(), comm_get_txspace(), comm_send_buffer(), GCS_MAVLINK::find_by_mavtype_and_compid(), gcs_out_of_space_to_send(), GCS_MAVLINK::handle_serial_control(), GCS_MAVLINK::handle_setup_signing(), loop(), mavlink_get_channel_buffer(), and mavlink_get_channel_status().
create_gcs_mavlink_backend()
void GCS::create_gcs_mavlink_backend (GCS_MAVLINK_Parameters & params, AP_HAL::UARTDriver & uart) private
Definition at line 2541 of file GCS_Common.cpp.
custom_mode()
virtual uint32_t GCS::custom_mode () const pure virtual
Implemented in GCS_Dummy.
Referenced by AP_Frsky_SPort_Passthrough::calc_ap_status().
enable_high_latency_connections()
void GCS::enable_high_latency_connections (bool enabled)
Definition at line 120 of file GCS.cpp.
Referenced by GCS_MAVLINK::handle_control_high_latency().
frame_string()
virtual const char * GCS::frame_string () const inline virtual
Definition at line 1139 of file GCS.h.
Referenced by AP_RCTelemetry::init().
frame_type()
virtual MAV_TYPE GCS::frame_type () const pure virtual
Implemented in GCS_Dummy.
Referenced by AP_Frsky_SPort_Passthrough::calc_param().
get_channel_from_port_number()
uint8_t GCS::get_channel_from_port_number (uint8_t port_num)
Definition at line 2979 of file GCS_Common.cpp.
get_high_latency_status()
bool GCS::get_high_latency_status ()
Definition at line 126 of file GCS.cpp.
get_hud_throttle()
int16_t GCS::get_hud_throttle (void) const inline
Definition at line 1237 of file GCS.h.
get_prot_for_mission_type()
MissionItemProtocol * GCS::get_prot_for_mission_type (const MAV_MISSION_TYPE mission_type) const
Definition at line 576 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::handle_mission_clear_all(), GCS_MAVLINK::handle_mission_count(), GCS_MAVLINK::handle_mission_item(), GCS_MAVLINK::handle_mission_request_int(), GCS_MAVLINK::handle_mission_request_list(), and GCS_MAVLINK::handle_mission_write_partial_list().
get_sensor_status_flags()
void GCS::get_sensor_status_flags (uint32_t & present, uint32_t & enabled, uint32_t & health)
Definition at line 29 of file GCS.cpp.
Referenced by GCS_MAVLINK::send_high_latency2(), GCS_MAVLINK::send_sys_status(), and AP_RCTelemetry::sensor_status_flags().
get_singleton()
static class GCS * GCS::get_singleton () inline static
Definition at line 1133 of file GCS.h.
Referenced by gcs().
init()
void GCS::init ()
Definition at line 48 of file GCS.cpp.
Referenced by setup(), and AP_Vehicle::setup().
install_alternative_protocol()
bool GCS::install_alternative_protocol (mavlink_channel_t chan, GCS_MAVLINK::protocol_handler_fn_t handler)
Definition at line 137 of file GCS.cpp.
min_loop_time_remaining_for_message_send_us()
virtual uint16_t GCS::min_loop_time_remaining_for_message_send_us () const inline virtual
Definition at line 1208 of file GCS.h.
Referenced by out_of_time().
new_gcs_mavlink_backend()
virtual GCS_MAVLINK * GCS::new_gcs_mavlink_backend (GCS_MAVLINK_Parameters & params, AP_HAL::UARTDriver & uart) protected pure virtual
Implemented in GCS_Dummy.
num_gcs()
uint8_t GCS::num_gcs () const inline
Definition at line 1183 of file GCS.h.
Referenced by GCS_MAVLINK::handle_serial_control(), and send_to_active_channels().
out_of_time()
bool GCS::out_of_time () const
Definition at line 357 of file GCS.cpp.
passthru_timer()
void GCS::passthru_timer (void) private
Definition at line 6669 of file GCS_Common.cpp.
Referenced by update_passthru().
send_message()
void GCS::send_message (enum ap_message id)
Definition at line 2446 of file GCS_Common.cpp.
send_mission_item_reached_message()
void GCS::send_mission_item_reached_message (uint16_t mission_index)
Definition at line 2514 of file GCS_Common.cpp.
send_named_float()
void GCS::send_named_float (const char * name, float value) const
Definition at line 107 of file GCS.cpp.
Referenced by AP_WindVane::send_wind(), AP_InertialSensor_Invensense::update(), and AP_Airspeed::update().
send_parameter_value()
void GCS::send_parameter_value (const char * param_name, ap_var_type param_type, float param_value)
Definition at line 343 of file GCS_Param.cpp.
send_text()
void GCS::send_text (MAV_SEVERITY severity, const char * fmt, ...)
Definition at line 80 of file GCS.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration_baro(), ESP32::RCInput::_timer_tick(), AP_AdvancedFailsafe::check(), MAVLink_routing::check_and_forward(), AP_BattMonitor::checkPoweringOff(), AC_AutoTune::currently_level(), AC_AutoTune_Heli::do_gcs_announcements(), AC_AutoTune_Multi::do_gcs_announcements(), AC_AutoTune_Heli::do_post_test_gcs_announcements(), enable_high_latency_connections(), GCS_MAVLINK::ftp_init(), GCS_MAVLINK::ftp_worker(), AP_AdvancedFailsafe::gcs_terminate(), GCS_MAVLINK::handle_command_preflight_calibration(), MissionItemProtocol::handle_mission_write_partial_list(), GCS_MAVLINK::handle_param_set(), GCS_MAVLINK::handle_timesync(), AP_Follow::init_offsets_if_required(), MissionItemProtocol::mavlink2_requirement_met(), GCS_MAVLINK::mavlink_coordinate_frame_to_location_alt_frame(), AP_AdvancedFailsafe::max_range_update(), AP_MotorsUGV::pre_arm_check(), AC_AutoTune_Multi::report_axis_gains(), AC_AutoTune_Heli::report_axis_gains(), AC_AutoTune::run(), MissionItemProtocol::send_mission_item_warning(), AC_AutoTune::send_step_string(), GCS_MAVLINK::set_mavlink_message_id_interval(), GCS_MAVLINK::set_message_interval(), AC_AutoTune_Heli::test_run(), GCS_MAVLINK::try_send_message(), AP_WheelEncoder_SITL_Quadrature::update(), SoaringController::update_active_state(), AC_AutoTune::update_gcs(), update_passthru(), GCS_MAVLINK::update_receive(), and AC_AutoTune_Heli::updating_max_gains().
send_textv() [1/2]
void GCS::send_textv (MAV_SEVERITY severity, const char * fmt, va_list arg_list)
Definition at line 68 of file GCS.cpp.
Referenced by AP_Arming::check_failed(), AP_Arming::check_failed(), GCS_MAVLINK::send_text(), send_text(), send_textv(), and AP_BoardConfig::throw_error().
send_textv() [2/2]
void GCS::send_textv (MAV_SEVERITY severity, const char * fmt, va_list arg_list, uint8_t mask) virtual
Reimplemented in GCS_Dummy.
Definition at line 2240 of file GCS_Common.cpp.
send_to_active_channels()
void GCS::send_to_active_channels (uint32_t msgid, const char * pkt)
Definition at line 88 of file GCS.cpp.
Referenced by send_named_float(), and send_parameter_value().
service_statustext()
void GCS::service_statustext (void) private
Definition at line 2348 of file GCS_Common.cpp.
set_message_interval()
MAV_RESULT GCS::set_message_interval (uint8_t port_num, uint32_t msg_id, int32_t interval_us)
Definition at line 2968 of file GCS_Common.cpp.
setup_console()
void GCS::setup_console ()
Definition at line 2522 of file GCS_Common.cpp.
Referenced by setup(), and AP_Vehicle::setup().
setup_uarts()
void GCS::setup_uarts ()
Definition at line 2560 of file GCS_Common.cpp.
simple_input_active()
virtual bool GCS::simple_input_active () const inline virtual
Definition at line 1251 of file GCS.h.
Referenced by AP_Frsky_SPort_Passthrough::calc_ap_status(), and AP_MSP_Telem_Backend::update_flight_mode_str().
statustext_queue()
StatusTextQueue & GCS::statustext_queue () inline
Definition at line 1159 of file GCS.h.
Referenced by GCS_MAVLINK::service_statustext().
statustext_send_channel_mask()
uint8_t GCS::statustext_send_channel_mask () const
Definition at line 56 of file GCS.cpp.
Referenced by send_textv().
supersimple_input_active()
virtual bool GCS::supersimple_input_active () const inline virtual
Definition at line 1252 of file GCS.h.
Referenced by AP_Frsky_SPort_Passthrough::calc_ap_status(), and AP_MSP_Telem_Backend::update_flight_mode_str().
sysid_myggcs_last_seen_time_ms()
uint32_t GCS::sysid_myggcs_last_seen_time_ms () const inline
Definition at line 1165 of file GCS.h.
Referenced by AP_AdvancedFailsafe::check().
sysid_myggcs_seen()
void GCS::sysid_myggcs_seen (uint32_t seen_time_ms) inline
Definition at line 1169 of file GCS.h.
Referenced by GCS_MAVLINK::handle_heartbeat().
sysid_this_mav()
virtual uint8_t GCS::sysid_this_mav () const pure virtual
Implemented in GCS_Dummy.
Referenced by init().
try_send_queued_message_for_type()
void GCS::try_send_queued_message_for_type (MAV_MISSION_TYPE type) const
Definition at line 5410 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::try_send_mission_message().
update_passthru()
void GCS::update_passthru (void)
Definition at line 6607 of file GCS_Common.cpp.
update_receive()
void GCS::update_receive (void)
Definition at line 2505 of file GCS_Common.cpp.
Referenced by AP_Vehicle::scheduler_delay_callback(), and AP_BoardConfig::throw_error().
update_send()
void GCS::update_send ()
Definition at line 2453 of file GCS_Common.cpp.
Referenced by AP_Vehicle::scheduler_delay_callback(), and AP_BoardConfig::throw_error().
update_sensor_status_flags()
void GCS::update_sensor_status_flags () private
Definition at line 152 of file GCS.cpp.
Referenced by get_sensor_status_flags().
update_vehicle_sensor_status_flags()
virtual void GCS::update_vehicle_sensor_status_flags () inline protected virtual
Definition at line 1276 of file GCS.h.
Referenced by update_sensor_status_flags().
vehicle_initialised()
virtual bool GCS::vehicle_initialised () const inline virtual
Definition at line 1249 of file GCS.h.
Referenced by AP_Frsky_SPort_Passthrough::is_packet_ready().
Member Data Documentation
_chan
GCS_MAVLINK* GCS::_chan[MAVLINK_COMM_NUM_BUFFERS] protected
Definition at line 1280 of file GCS.h.
_num_gcs
uint8_t GCS::_num_gcs protected
Definition at line 1279 of file GCS.h.
Referenced by num_gcs(), and send_textv().
[struct]
struct { ... } GCS::_passthru
_singleton
GCS * GCS::_singleton = nullptr static private
Definition at line 1284 of file GCS.h.
Referenced by GCS(), and get_singleton().
_status_capacity
const uint8_t GCS::_status_capacity = 7 static private
Definition at line 1305 of file GCS.h.
_statustext_queue
StatusTextQueue GCS::_statustext_queue {_status_capacity} private
Definition at line 1312 of file GCS.h.
Referenced by statustext_queue().
_sysid_mygcs_last_seen_time_ms
uint32_t GCS::_sysid_mygcs_last_seen_time_ms private
Definition at line 1301 of file GCS.h.
Referenced by sysid_myggcs_last_seen_time_ms(), and sysid_myggcs_seen().
baud1
uint32_t GCS::baud1
Definition at line 1329 of file GCS.h.
baud2
uint32_t GCS::baud2
Definition at line 1330 of file GCS.h.
chan_parameters
GCS_MAVLINK_Parameters GCS::chan_parameters[MAVLINK_COMM_NUM_BUFFERS] protected
Definition at line 1278 of file GCS.h.
control_sensors_enabled
uint32_t GCS::control_sensors_enabled protected
Definition at line 1274 of file GCS.h.
Referenced by get_sensor_status_flags(), and update_sensor_status_flags().
control_sensors_health
uint32_t GCS::control_sensors_health protected
Definition at line 1275 of file GCS.h.
Referenced by get_sensor_status_flags(), and update_sensor_status_flags().
control_sensors_present
uint32_t GCS::control_sensors_present protected
Definition at line 1273 of file GCS.h.
Referenced by get_sensor_status_flags(), and update_sensor_status_flags().
enabled
bool GCS::enabled
Definition at line 1322 of file GCS.h.
Referenced by enable_high_latency_connections(), get_sensor_status_flags(), and update_sensor_status_flags().
first_backend_to_send
uint8_t GCS::first_backend_to_send private
Definition at line 1342 of file GCS.h.
high_latency_link_enabled
bool GCS::high_latency_link_enabled
Definition at line 1261 of file GCS.h.
Referenced by enable_high_latency_connections(), and get_high_latency_status().
initialised_missionitemprotocol_objects
bool GCS::initialised_missionitemprotocol_objects private
Definition at line 1315 of file GCS.h.
last_ms
uint32_t GCS::last_ms
Definition at line 1327 of file GCS.h.
last_port1_data_ms
uint32_t GCS::last_port1_data_ms
Definition at line 1328 of file GCS.h.
missionitemprotocols
MissionItemProtocol * GCS::missionitemprotocols static
Definition at line 1197 of file GCS.h.
Referenced by get_prot_for_mission_type(), and GCS_MAVLINK::requesting_mission_items().
port1
AP_HAL::UARTDriver* GCS::port1
Definition at line 1324 of file GCS.h.
port2
AP_HAL::UARTDriver* GCS::port2
Definition at line 1325 of file GCS.h.
sem
HAL_Semaphore GCS::sem
Definition at line 1332 of file GCS.h.
start_ms
uint32_t GCS::start_ms
Definition at line 1326 of file GCS.h.
statustext_printf_buffer
char GCS::statustext_printf_buffer[256+1] private
Definition at line 1289 of file GCS.h.
timeout_s
uint8_t GCS::timeout_s
Definition at line 1331 of file GCS.h.
timer_installed
bool GCS::timer_installed
Definition at line 1323 of file GCS.h.
update_send_has_been_called
bool GCS::update_send_has_been_called private
Definition at line 1318 of file GCS.h.
Referenced by send_textv().
The documentation for this class was generated from the following files:
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS.cpp
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/GCS_MAVLink/GCS_Param.cpp