APM:Libraries: AP_Baro Class Reference
AP_Baro Class Reference
#include <AP_Baro.h>
Classes
struct sensor
class WindCoeff
Public Types
enum baro_type_t { BARO_TYPE_AIR , BARO_TYPE_WATER }
enum Options : uint16_t { TreatMS5611AsMS5607 = (1U << 0U) }
Public Member Functions
AP_Baro ()
CLASS_NO_COPY (AP_Baro)
void init (void)
void update (void)
bool healthy (void) const
bool healthy (uint8_t instance) const
bool all_healthy (void) const
bool arming_checks (size_t buflen, char *buffer) const
uint8_t get_primary (void) const
float get_pressure (void) const
float get_pressure (uint8_t instance) const
const Vector3f & get_dynamic_pressure (uint8_t instance) const
float get_temperature (void) const
float get_temperature (uint8_t instance) const
float get_pressure_correction (void) const
float get_pressure_correction (uint8_t instance) const
void accumulate (void)
void calibrate (bool save=true)
void update_calibration (void)
float get_altitude (void) const
float get_altitude (uint8_t instance) const
uint8_t external_bus () const
float get_altitude_difference (float base_pressure, float pressure) const
float get_sealevel_pressure (float pressure) const
float get_EAS2TAS (void)
float get_air_density_ratio (void)
float get_climb_rate (void)
float get_ground_temperature (void) const
float get_ground_pressure (void) const
float get_ground_pressure (uint8_t i) const
void set_external_temperature (float temperature)
uint32_t get_last_update (void) const
uint32_t get_last_update (uint8_t instance) const
float get_external_temperature (void) const
float get_external_temperature (const uint8_t instance) const
void set_primary_baro (uint8_t primary)
void set_type (uint8_t instance, baro_type_t type)
baro_type_t get_type (uint8_t instance)
uint8_t register_sensor (void)
uint8_t num_instances (void) const
void set_baro_drift_altitude (float alt)
float get_baro_drift_offset (void) const
void set_pressure_correction (uint8_t instance, float p_correction)
uint8_t get_filter_range () const
void set_log_baro_bit (uint32_t bit)
bool should_log () const
HAL_Semaphore & get_semaphore (void)
bool option_enabled (const Options option) const
Static Public Member Functions
static AP_Baro * get_singleton (void)
static void SimpleAtmosphere (const float alt, float &sigma, float &delta, float &theta)
static void SimpleUnderWaterAtmosphere (float alt, float &rho, float &delta, float &theta)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
enum {
PROBE_BMP085 =(1<<0) , PROBE_BMP280 =(1<<1) , PROBE_MS5611 =(1<<2) , PROBE_MS5607 =(1<<3) ,
PROBE_MS5637 =(1<<4) , PROBE_FBM320 =(1<<5) , PROBE_DPS280 =(1<<6) , PROBE_LPS25H =(1<<7) ,
PROBE_KELLER =(1<<8) , PROBE_MS5837 =(1<<9) , PROBE_BMP388 =(1<<10) , PROBE_SPL06 =(1<<11) ,
PROBE_MSP =(1<<12)
}
Private Member Functions
bool _have_i2c_driver (uint8_t bus_num, uint8_t address) const
bool _add_backend (AP_Baro_Backend *backend)
void _probe_i2c_barometers (void)
float wind_pressure_correction (uint8_t instance)
void Write_Baro (void)
void Write_Baro_instance (uint64_t time_us, uint8_t baro_instance)
void update_field_elevation ()
Private Attributes
uint8_t _num_drivers
AP_Baro_Backend * drivers [BARO_MAX_DRIVERS]
uint8_t _num_sensors
uint8_t _primary
uint32_t _log_baro_bit = -1
bool init_done
uint8_t msp_instance_mask
struct AP_Baro::sensor sensors [BARO_MAX_INSTANCES]
AP_Float _alt_offset
float _alt_offset_active
AP_Float _field_elevation
float _field_elevation_active
uint32_t _field_elevation_last_ms
AP_Int8 _primary_baro
AP_Int8 _ext_bus
float _last_altitude_EAS2TAS
float _EAS2TAS
float _external_temperature
uint32_t _last_external_temperature_ms
DerivativeFilterFloat_Size7 _climb_rate_filter
AP_Float _specific_gravity
AP_Float _user_ground_temperature
float _guessed_ground_temperature
uint32_t _last_notify_ms
AP_Int8 _filter_range
AP_Int32 _baro_probe_ext
AP_Float _alt_error_max
AP_Int16 _options
HAL_Semaphore _rsem
Static Private Attributes
static AP_Baro * _singleton
Friends
class AP_Baro_Backend
class AP_Baro_SITL
class AP_Baro_DroneCAN
Detailed Description
Definition at line 27 of file AP_Baro.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
PROBE_BMP085
PROBE_BMP280
PROBE_MS5611
PROBE_MS5607
PROBE_MS5637
PROBE_FBM320
PROBE_DPS280
PROBE_LPS25H
PROBE_KELLER
PROBE_MS5837
PROBE_BMP388
PROBE_SPL06
PROBE_MSP
Definition at line 233 of file AP_Baro.h.
baro_type_t
enum AP_Baro::baro_type_t
Enumerator
BARO_TYPE_AIR
BARO_TYPE_WATER
Definition at line 45 of file AP_Baro.h.
Options
enum AP_Baro::Options : uint16_t
Enumerator
TreatMS5611AsMS5607
Definition at line 202 of file AP_Baro.h.
Constructor & Destructor Documentation
AP_Baro()
AP_Baro::AP_Baro ()
Definition at line 267 of file AP_Baro.cpp.
Member Function Documentation
_add_backend()
bool AP_Baro::_add_backend (AP_Baro_Backend * backend) private
Definition at line 537 of file AP_Baro.cpp.
_have_i2c_driver()
bool AP_Baro::_have_i2c_driver (uint8_t bus_num, uint8_t address) const private
Definition at line 552 of file AP_Baro.cpp.
_probe_i2c_barometers()
void AP_Baro::_probe_i2c_barometers (void) private
Definition at line 802 of file AP_Baro.cpp.
Referenced by init().
accumulate()
void AP_Baro::accumulate (void)
Definition at line 1043 of file AP_Baro.cpp.
Referenced by loop().
all_healthy()
bool AP_Baro::all_healthy (void) const
Definition at line 1066 of file AP_Baro.cpp.
Referenced by arming_checks(), and GCS::update_sensor_status_flags().
arming_checks()
bool AP_Baro::arming_checks (size_t buflen, char * buffer) const
Definition at line 1116 of file AP_Baro.cpp.
calibrate()
void AP_Baro::calibrate (bool save = true)
Definition at line 277 of file AP_Baro.cpp.
Referenced by setup().
CLASS_NO_COPY()
AP_Baro::CLASS_NO_COPY (AP_Baro)
external_bus()
uint8_t AP_Baro::external_bus () const inline
Definition at line 109 of file AP_Baro.h.
get_air_density_ratio()
float AP_Baro::get_air_density_ratio (void)
Definition at line 460 of file AP_Baro.cpp.
Referenced by Thrust_Linearization::get_compensation_gain(), and wind_pressure_correction().
get_altitude() [1/2]
float AP_Baro::get_altitude (uint8_t instance) const inline
Definition at line 106 of file AP_Baro.h.
get_altitude() [2/2]
float AP_Baro::get_altitude (void) const inline
Definition at line 105 of file AP_Baro.h.
Referenced by HALSITL::SITL_State::_simulator_servos(), get_altitude(), get_EAS2TAS(), AP_AHRS::get_relative_position_D_home(), loop(), NavEKF2_core::readBaroData(), NavEKF3_core::readBaroData(), AP_DAL_Baro::start_frame(), update(), and AP_TECS::update_50hz().
get_altitude_difference()
float AP_Baro::get_altitude_difference (float base_pressure, float pressure) const
Definition at line 405 of file AP_Baro.cpp.
Referenced by arming_checks(), AP_AdvancedFailsafe::check_altlimit(), and update().
get_baro_drift_offset()
float AP_Baro::get_baro_drift_offset (void) const inline
Definition at line 173 of file AP_Baro.h.
get_climb_rate()
float AP_Baro::get_climb_rate (void)
Definition at line 473 of file AP_Baro.cpp.
Referenced by AP_OSD_Screen::draw_vspeed(), AP_MSP_Telem_Backend::get_vspeed_ms(), and loop().
get_dynamic_pressure()
const Vector3f & AP_Baro::get_dynamic_pressure (uint8_t instance) const inline
Definition at line 80 of file AP_Baro.h.
get_EAS2TAS()
float AP_Baro::get_EAS2TAS (void)
Definition at line 433 of file AP_Baro.cpp.
Referenced by get_air_density_ratio(), AP_AHRS_Backend::get_EAS2TAS(), AP_DAL::start_frame(), and AP_Airspeed::update_calibration().
get_external_temperature() [1/2]
float AP_Baro::get_external_temperature (const uint8_t instance) const
Definition at line 504 of file AP_Baro.cpp.
get_external_temperature() [2/2]
float AP_Baro::get_external_temperature (void) const inline
Definition at line 150 of file AP_Baro.h.
Referenced by calibrate(), get_external_temperature(), and update_calibration().
get_filter_range()
uint8_t AP_Baro::get_filter_range () const inline
Definition at line 184 of file AP_Baro.h.
Referenced by AP_Baro_Backend::pressure_ok().
get_ground_pressure() [1/2]
float AP_Baro::get_ground_pressure (uint8_t i) const inline
Definition at line 136 of file AP_Baro.h.
get_ground_pressure() [2/2]
float AP_Baro::get_ground_pressure (void) const inline
Definition at line 135 of file AP_Baro.h.
Referenced by get_ground_pressure().
get_ground_temperature()
float AP_Baro::get_ground_temperature (void) const
Definition at line 482 of file AP_Baro.cpp.
Referenced by get_altitude_difference(), get_EAS2TAS(), and get_sealevel_pressure().
get_last_update() [1/2]
uint32_t AP_Baro::get_last_update (uint8_t instance) const inline
Definition at line 145 of file AP_Baro.h.
get_last_update() [2/2]
uint32_t AP_Baro::get_last_update (void) const inline
Definition at line 144 of file AP_Baro.h.
Referenced by AP_AdvancedFailsafe::check_altlimit(), get_last_update(), NavEKF2_core::readBaroData(), NavEKF3_core::readBaroData(), AP_DAL_Baro::start_frame(), and update().
get_pressure() [1/2]
float AP_Baro::get_pressure (uint8_t instance) const inline
Definition at line 77 of file AP_Baro.h.
get_pressure() [2/2]
float AP_Baro::get_pressure (void) const inline
Definition at line 76 of file AP_Baro.h.
Referenced by AP_Airspeed_SDP3X::_correct_pressure(), HALSITL::SITL_State::_update_airspeed(), arming_checks(), AP_AdvancedFailsafe::check_altlimit(), get_EAS2TAS(), get_EAS2TAS(), get_pressure(), AP_TempCalibration::learn_calibration(), loop(), AP_Baro_KellerLD::read_mode_type(), GCS_MAVLINK::send_scaled_pressure_instance(), AP_Baro_KellerLD::update(), and update_calibration().
get_pressure_correction() [1/2]
float AP_Baro::get_pressure_correction (uint8_t instance) const inline
Definition at line 89 of file AP_Baro.h.
get_pressure_correction() [2/2]
float AP_Baro::get_pressure_correction (void) const inline
Definition at line 88 of file AP_Baro.h.
Referenced by get_pressure_correction().
get_primary()
uint8_t AP_Baro::get_primary (void) const inline
Definition at line 73 of file AP_Baro.h.
Referenced by AP_DAL_Baro::start_frame(), and NavEKF3_core::update_baro_selection().
get_sealevel_pressure()
float AP_Baro::get_sealevel_pressure (float pressure) const
Definition at line 418 of file AP_Baro.cpp.
Referenced by calibrate(), and update_calibration().
get_semaphore()
HAL_Semaphore & AP_Baro::get_semaphore (void) inline
Definition at line 191 of file AP_Baro.h.
Referenced by AP_OSD_Screen::draw_vspeed(), and AP_MSP_Telem_Backend::get_vspeed_ms().
get_singleton()
static AP_Baro * AP_Baro::get_singleton (void) inline static
Definition at line 40 of file AP_Baro.h.
Referenced by AP_Airspeed_SDP3X::_correct_pressure(), and AP::baro().
get_temperature() [1/2]
float AP_Baro::get_temperature (uint8_t instance) const inline
Definition at line 85 of file AP_Baro.h.
get_temperature() [2/2]
float AP_Baro::get_temperature (void) const inline
Definition at line 84 of file AP_Baro.h.
Referenced by AP_TempCalibration::apply_calibration(), AP_OSD_Screen::draw_temp(), get_external_temperature(), get_temperature(), SITL::EFI_Hirth::init(), AP_TempCalibration::learn_calibration(), loop(), AP_Hott_Telem::send_EAM(), SITL::EFI_Hirth::send_record1(), GCS_MAVLINK::send_scaled_pressure_instance(), AP_TempCalibration::setup_learning(), and SITL::EFI_Hirth::update_engine_model().
get_type()
baro_type_t AP_Baro::get_type (uint8_t instance) inline
Definition at line 160 of file AP_Baro.h.
healthy() [1/2]
bool AP_Baro::healthy (uint8_t instance) const
Definition at line 993 of file AP_Baro.cpp.
healthy() [2/2]
bool AP_Baro::healthy (void) const inline
Definition at line 58 of file AP_Baro.h.
Referenced by all_healthy(), AP_TempCalibration::apply_calibration(), calibrate(), healthy(), AP_TempCalibration::learn_calibration(), loop(), AP_Hott_Telem::send_EAM(), AP_DAL_Baro::start_frame(), update(), NavEKF3_core::update_baro_selection(), and update_calibration().
init()
void AP_Baro::init (void)
Definition at line 579 of file AP_Baro.cpp.
Referenced by setup().
num_instances()
uint8_t AP_Baro::num_instances (void) const inline
Definition at line 167 of file AP_Baro.h.
Referenced by AP_Airspeed_SDP3X::_correct_pressure(), GCS_MAVLINK::send_scaled_pressure_instance(), AP_DAL_Baro::start_frame(), NavEKF3_core::update_baro_selection(), and GCS::update_sensor_status_flags().
option_enabled()
bool AP_Baro::option_enabled (const Options option) const inline
Definition at line 207 of file AP_Baro.h.
Referenced by AP_Baro_MS56XX::_init().
register_sensor()
uint8_t AP_Baro::register_sensor (void)
Definition at line 1054 of file AP_Baro.cpp.
Referenced by AP_Baro_BMP085::_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_Baro_BMP280::_init(), AP_Baro_LPS2XH::_init(), AP_Baro_SPL06::_init(), AP_Baro_Dummy::AP_Baro_Dummy(), AP_Baro_ICM20789::init(), AP_Baro_ICP101XX::init(), AP_Baro_ICP201XX::init(), AP_Baro_DPS280::init(), AP_Baro_BMP388::init(), and AP_Baro_FBM320::init().
set_baro_drift_altitude()
void AP_Baro::set_baro_drift_altitude (float alt) inline
Definition at line 170 of file AP_Baro.h.
set_external_temperature()
void AP_Baro::set_external_temperature (float temperature)
Definition at line 495 of file AP_Baro.cpp.
set_log_baro_bit()
void AP_Baro::set_log_baro_bit (uint32_t bit) inline
Definition at line 187 of file AP_Baro.h.
set_pressure_correction()
void AP_Baro::set_pressure_correction (uint8_t instance, float p_correction)
Definition at line 1077 of file AP_Baro.cpp.
Referenced by AP_TempCalibration::apply_calibration().
set_primary_baro()
void AP_Baro::set_primary_baro (uint8_t primary) inline
Definition at line 154 of file AP_Baro.h.
set_type()
void AP_Baro::set_type (uint8_t instance, baro_type_t type) inline
Definition at line 157 of file AP_Baro.h.
Referenced by AP_Baro_KellerLD::_init(), and AP_Baro_MS56XX::_init().
should_log()
bool AP_Baro::should_log () const
Referenced by update().
SimpleAtmosphere()
void AP_Baro::SimpleAtmosphere (const float alt, float & sigma, float & delta, float & theta) static
Definition at line 15 of file AP_Baro_HIL.cpp.
Referenced by SITL::Frame::get_air_density(), get_EAS2TAS(), SITL::MS5525::get_pressure_temperature_readings(), SITL::MS5611::get_pressure_temperature_readings(), SITL::TSYS01::get_sim_temperature(), SITL::MicroStrain::send_imu_packet(), SITL::InertialLabs::send_packet(), SITL::VectorNav::send_packet1(), and SITL::Airspeed_DLVR::update().
SimpleUnderWaterAtmosphere()
void AP_Baro::SimpleUnderWaterAtmosphere (float alt, float & rho, float & delta, float & theta) static
Definition at line 38 of file AP_Baro_HIL.cpp.
Referenced by SITL::SerialRangeFinder::send_temperature().
update()
void AP_Baro::update (void)
Definition at line 897 of file AP_Baro.cpp.
Referenced by calibrate(), and loop().
update_calibration()
void AP_Baro::update_calibration (void)
Definition at line 377 of file AP_Baro.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration_baro(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_calibration_baro(), AP_DAL_Baro::update_calibration(), and update_field_elevation().
update_field_elevation()
void AP_Baro::update_field_elevation (void) private
Definition at line 1005 of file AP_Baro.cpp.
Referenced by update().
wind_pressure_correction()
float AP_Baro::wind_pressure_correction (uint8_t instance) private
Definition at line 71 of file AP_Baro_Wind.cpp.
Referenced by update().
Write_Baro()
void AP_Baro::Write_Baro (void) private
Referenced by update().
Write_Baro_instance()
void AP_Baro::Write_Baro_instance (uint64_t time_us, uint8_t baro_instance) private
Friends And Related Symbol Documentation
AP_Baro_Backend
friend class AP_Baro_Backend friend
Definition at line 29 of file AP_Baro.h.
AP_Baro_DroneCAN
friend class AP_Baro_DroneCAN friend
Definition at line 31 of file AP_Baro.h.
AP_Baro_SITL
friend class AP_Baro_SITL friend
Definition at line 30 of file AP_Baro.h.
Referenced by init().
Member Data Documentation
_alt_error_max
AP_Float AP_Baro::_alt_error_max private
Definition at line 310 of file AP_Baro.h.
Referenced by arming_checks().
_alt_offset
AP_Float AP_Baro::_alt_offset private
Definition at line 283 of file AP_Baro.h.
Referenced by calibrate(), set_baro_drift_altitude(), and update().
_alt_offset_active
float AP_Baro::_alt_offset_active private
Definition at line 284 of file AP_Baro.h.
Referenced by get_baro_drift_offset(), and update().
_baro_probe_ext
AP_Int32 AP_Baro::_baro_probe_ext private
Definition at line 307 of file AP_Baro.h.
Referenced by _probe_i2c_barometers(), and init().
_climb_rate_filter
DerivativeFilterFloat_Size7 AP_Baro::_climb_rate_filter private
Definition at line 294 of file AP_Baro.h.
Referenced by get_climb_rate(), and update().
_EAS2TAS
float AP_Baro::_EAS2TAS private
Definition at line 291 of file AP_Baro.h.
Referenced by get_EAS2TAS(), and update_calibration().
_ext_bus
AP_Int8 AP_Baro::_ext_bus private
Definition at line 289 of file AP_Baro.h.
Referenced by _probe_i2c_barometers(), external_bus(), and init().
_external_temperature
float AP_Baro::_external_temperature private
Definition at line 292 of file AP_Baro.h.
Referenced by get_external_temperature(), and set_external_temperature().
_field_elevation
AP_Float AP_Baro::_field_elevation private
Definition at line 285 of file AP_Baro.h.
Referenced by AP_Baro(), init(), and update_field_elevation().
_field_elevation_active
float AP_Baro::_field_elevation_active private
Definition at line 286 of file AP_Baro.h.
Referenced by AP_Baro(), arming_checks(), get_altitude_difference(), get_sealevel_pressure(), and update_field_elevation().
_field_elevation_last_ms
uint32_t AP_Baro::_field_elevation_last_ms private
Definition at line 287 of file AP_Baro.h.
Referenced by update_field_elevation().
_filter_range
AP_Int8 AP_Baro::_filter_range private
Definition at line 306 of file AP_Baro.h.
Referenced by get_filter_range().
_guessed_ground_temperature
float AP_Baro::_guessed_ground_temperature private
Definition at line 297 of file AP_Baro.h.
Referenced by calibrate(), get_ground_temperature(), and update_calibration().
_last_altitude_EAS2TAS
float AP_Baro::_last_altitude_EAS2TAS private
Definition at line 290 of file AP_Baro.h.
Referenced by get_EAS2TAS().
_last_external_temperature_ms
uint32_t AP_Baro::_last_external_temperature_ms private
Definition at line 293 of file AP_Baro.h.
Referenced by get_external_temperature(), and set_external_temperature().
_last_notify_ms
uint32_t AP_Baro::_last_notify_ms private
Definition at line 300 of file AP_Baro.h.
Referenced by update_calibration().
_log_baro_bit
uint32_t AP_Baro::_log_baro_bit = -1 private
Definition at line 226 of file AP_Baro.h.
Referenced by set_log_baro_bit().
_num_drivers
uint8_t AP_Baro::_num_drivers private
Definition at line 217 of file AP_Baro.h.
Referenced by _add_backend(), _have_i2c_driver(), accumulate(), calibrate(), init(), and update().
_num_sensors
uint8_t AP_Baro::_num_sensors private
Definition at line 221 of file AP_Baro.h.
Referenced by AP_Baro_Backend::_copy_to_frontend(), all_healthy(), calibrate(), init(), num_instances(), register_sensor(), set_pressure_correction(), update(), update_calibration(), and AP_Baro_Backend::update_healthy_flag().
_options
AP_Int16 AP_Baro::_options private
Definition at line 313 of file AP_Baro.h.
Referenced by option_enabled().
_primary
uint8_t AP_Baro::_primary private
Definition at line 224 of file AP_Baro.h.
Referenced by get_altitude(), get_external_temperature(), get_ground_pressure(), get_last_update(), get_pressure(), get_pressure_correction(), get_primary(), get_temperature(), healthy(), and update().
_primary_baro
AP_Int8 AP_Baro::_primary_baro private
Definition at line 288 of file AP_Baro.h.
Referenced by set_primary_baro(), and update().
_rsem
HAL_Semaphore AP_Baro::_rsem private
Definition at line 316 of file AP_Baro.h.
Referenced by get_semaphore(), and update().
_singleton
AP_Baro * AP_Baro::_singleton static private
Definition at line 214 of file AP_Baro.h.
Referenced by AP_Baro(), and get_singleton().
_specific_gravity
AP_Float AP_Baro::_specific_gravity private
Definition at line 295 of file AP_Baro.h.
Referenced by update().
_user_ground_temperature
AP_Float AP_Baro::_user_ground_temperature private
Definition at line 296 of file AP_Baro.h.
Referenced by get_ground_temperature().
drivers
AP_Baro_Backend* AP_Baro::drivers[BARO_MAX_DRIVERS] private
Definition at line 218 of file AP_Baro.h.
Referenced by _add_backend(), accumulate(), calibrate(), init(), and update().
init_done
bool AP_Baro::init_done private
Definition at line 228 of file AP_Baro.h.
Referenced by init().
msp_instance_mask
uint8_t AP_Baro::msp_instance_mask private
Definition at line 230 of file AP_Baro.h.
Referenced by init().
sensors
struct AP_Baro::sensor AP_Baro::sensors[BARO_MAX_INSTANCES] private
Referenced by AP_Baro_Backend::_copy_to_frontend(), _have_i2c_driver(), calibrate(), get_altitude(), get_dynamic_pressure(), get_ground_pressure(), get_last_update(), get_pressure(), get_pressure_correction(), get_temperature(), get_type(), healthy(), init(), AP_Baro_Backend::set_bus_id(), set_pressure_correction(), set_type(), update(), update_calibration(), AP_Baro_Backend::update_healthy_flag(), and wind_pressure_correction().
var_info
const AP_Param::GroupInfo AP_Baro::var_info static
Definition at line 80 of file AP_Baro.h.
The documentation for this class was generated from the following files:
libraries/AP_Baro/AP_Baro.h
libraries/AP_Baro/AP_Baro.cpp
libraries/AP_Baro/AP_Baro_HIL.cpp
libraries/AP_Baro/AP_Baro_Wind.cpp