APM:Libraries: AP_VideoTX Class Reference
AP_VideoTX Class Reference
#include <AP_VideoTX.h>
Classes
struct PowerLevel
Public Types
enum class VideoOptions {
VTX_PITMODE = (1 << 0) , VTX_PITMODE_UNTIL_ARM = (1 << 1) , VTX_PITMODE_ON_DISARM = (1 << 2) , VTX_UNLOCKED = (1 << 3) ,
VTX_PULLDOWN = (1 << 4) , VTX_SA_ONE_STOP_BIT = (1 << 5) , VTX_SA_IGNORE_CRC = (1 << 6) , VTX_CRSF_IGNORE_STAT = (1 << 7)
}
enum VideoBand {
BAND_A , BAND_B , BAND_E , FATSHARK ,
RACEBAND , LOW_RACEBAND , BAND_1G3_A , BAND_1G3_B ,
MAX_BANDS
}
enum class PowerActive { Unknown , Active , Inactive }
Public Member Functions
AP_VideoTX ()
~AP_VideoTX ()
CLASS_NO_COPY (AP_VideoTX)
bool init ()
void update ()
void set_frequency_mhz (uint16_t freq)
void set_configured_frequency_mhz (uint16_t freq)
uint16_t get_frequency_mhz () const
uint16_t get_configured_frequency_mhz () const
bool update_frequency () const
void update_configured_frequency ()
void set_power_mw (uint16_t power)
void set_power_level (uint8_t level, PowerActive active=PowerActive::Active)
void set_power_dbm (uint8_t power, PowerActive active=PowerActive::Active)
void set_power_dac (uint16_t power, PowerActive active=PowerActive::Active)
uint8_t update_power_dbm (uint8_t power, PowerActive active=PowerActive::Active)
void update_all_power_dbm (uint8_t nlevels, const uint8_t levels[])
void set_configured_power_mw (uint16_t power)
uint16_t get_configured_power_mw () const
uint16_t get_power_mw () const
uint8_t get_configured_power_dbm () const
uint8_t get_configured_power_level () const
uint8_t get_configured_power_dac () const
bool update_power () const
void change_power (int8_t position)
void set_band (uint8_t band)
void set_configured_band (uint8_t band)
uint8_t get_configured_band () const
uint8_t get_band () const
bool update_band () const
void set_channel (uint8_t channel)
void set_configured_channel (uint8_t channel)
uint8_t get_configured_channel () const
uint8_t get_channel () const
bool update_channel () const
void update_configured_channel_and_band ()
void set_options (uint16_t options)
void set_configured_options (uint16_t options)
uint16_t get_configured_options () const
uint16_t get_options () const
bool has_option (VideoOptions option) const
bool get_configured_pitmode () const
bool get_pitmode () const
bool update_options () const
void set_enabled (bool enabled)
bool get_enabled () const
bool update_enabled () const
bool have_params_changed () const
bool set_defaults ()
void announce_vtx_settings () const
void set_power_is_current ()
void set_freq_is_current ()
void set_options_are_current ()
void set_configuration_finished (bool configuration_finished)
bool is_configuration_finished ()
Static Public Member Functions
static AP_VideoTX * get_singleton (void)
static uint16_t get_frequency_mhz (uint8_t band, uint8_t channel)
static bool get_band_and_channel (uint16_t freq, VideoBand &band, uint8_t &channel)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
static const char * band_names [] = {"A","B","E","F","R","L"}
static PowerLevel _power_levels [VTX_MAX_POWER_LEVELS]
static const uint16_t VIDEO_CHANNELS [MAX_BANDS][VTX_MAX_CHANNELS]
static AP_VideoTX * singleton
Private Member Functions
uint8_t find_current_power () const
Private Attributes
AP_Int16 _frequency_mhz
uint16_t _current_frequency
AP_Int16 _power_mw
uint16_t _current_power
AP_Int16 _max_power_mw
AP_Int8 _band
uint16_t _current_band
AP_Int8 _channel
uint8_t _current_channel
AP_Int16 _options
uint16_t _current_options
AP_Int8 _enabled
bool _current_enabled
bool _initialized
bool _defaults_set
bool _configuration_finished
Detailed Description
Definition at line 26 of file AP_VideoTX.h.
Member Enumeration Documentation
PowerActive
enum class AP_VideoTX::PowerActive strong
Enumerator
Unknown
Active
Inactive
Definition at line 70 of file AP_VideoTX.h.
VideoBand
enum AP_VideoTX::VideoBand
Enumerator
BAND_A
BAND_B
BAND_E
FATSHARK
RACEBAND
LOW_RACEBAND
BAND_1G3_A
BAND_1G3_B
MAX_BANDS
Definition at line 58 of file AP_VideoTX.h.
VideoOptions
enum class AP_VideoTX::VideoOptions strong
Enumerator
VTX_PITMODE
VTX_PITMODE_UNTIL_ARM
VTX_PITMODE_ON_DISARM
VTX_UNLOCKED
VTX_PULLDOWN
VTX_SA_ONE_STOP_BIT
VTX_SA_IGNORE_CRC
VTX_CRSF_IGNORE_STAT
Definition at line 45 of file AP_VideoTX.h.
Constructor & Destructor Documentation
AP_VideoTX()
AP_VideoTX::AP_VideoTX ()
Definition at line 121 of file AP_VideoTX.cpp.
~AP_VideoTX()
AP_VideoTX::~AP_VideoTX (void)
Definition at line 132 of file AP_VideoTX.cpp.
Member Function Documentation
announce_vtx_settings()
void AP_VideoTX::announce_vtx_settings () const
Definition at line 500 of file AP_VideoTX.cpp.
Referenced by AP_SmartAudio::loop(), and set_defaults().
change_power()
void AP_VideoTX::change_power (int8_t position)
Definition at line 510 of file AP_VideoTX.cpp.
Referenced by RC_Channel::read_aux().
CLASS_NO_COPY()
AP_VideoTX::CLASS_NO_COPY (AP_VideoTX)
find_current_power()
uint8_t AP_VideoTX::find_current_power () const private
Definition at line 190 of file AP_VideoTX.cpp.
Referenced by get_configured_power_dac(), get_configured_power_dbm(), get_configured_power_level(), and update().
get_band()
uint8_t AP_VideoTX::get_band () const inline
Definition at line 129 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer(), and AP_SmartAudio::update_vtx_params().
get_band_and_channel()
bool AP_VideoTX::get_band_and_channel (uint16_t freq, VideoBand & band, uint8_t & channel) static
Definition at line 170 of file AP_VideoTX.cpp.
Referenced by set_defaults(), and update_configured_channel_and_band().
get_channel()
uint8_t AP_VideoTX::get_channel () const inline
Definition at line 135 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer(), and AP_SmartAudio::update_vtx_params().
get_configured_band()
uint8_t AP_VideoTX::get_configured_band () const inline
Definition at line 128 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::update_vtx_params().
get_configured_channel()
uint8_t AP_VideoTX::get_configured_channel () const inline
Definition at line 134 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::update_vtx_params().
get_configured_frequency_mhz()
uint16_t AP_VideoTX::get_configured_frequency_mhz () const inline
Definition at line 94 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::update_vtx_params().
get_configured_options()
uint16_t AP_VideoTX::get_configured_options () const inline
Definition at line 141 of file AP_VideoTX.h.
Referenced by change_power(), AP_SmartAudio::parse_response_buffer(), and AP_SmartAudio::update_vtx_params().
get_configured_pitmode()
bool AP_VideoTX::get_configured_pitmode () const inline
Definition at line 144 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::update_vtx_params().
get_configured_power_dac()
uint8_t AP_VideoTX::get_configured_power_dac () const inline
Definition at line 118 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer().
get_configured_power_dbm()
uint8_t AP_VideoTX::get_configured_power_dbm () const inline
Definition at line 110 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer(), set_power_is_current(), and AP_SmartAudio::update_vtx_params().
get_configured_power_level()
uint8_t AP_VideoTX::get_configured_power_level () const inline
Definition at line 114 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer(), and AP_SmartAudio::update_vtx_params().
get_configured_power_mw()
uint16_t AP_VideoTX::get_configured_power_mw () const inline
Definition at line 106 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::update_vtx_params().
get_enabled()
bool AP_VideoTX::get_enabled () const inline
Definition at line 149 of file AP_VideoTX.h.
get_frequency_mhz() [1/2]
uint16_t AP_VideoTX::get_frequency_mhz () const inline
Definition at line 93 of file AP_VideoTX.h.
Referenced by set_defaults(), and update_configured_frequency().
get_frequency_mhz() [2/2]
static uint16_t AP_VideoTX::get_frequency_mhz (uint8_t band, uint8_t channel) inline static
Definition at line 88 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer(), and AP_SmartAudio::update_vtx_params().
get_options()
uint16_t AP_VideoTX::get_options () const inline
Definition at line 142 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::update_vtx_params().
get_pitmode()
bool AP_VideoTX::get_pitmode () const inline
Definition at line 145 of file AP_VideoTX.h.
Referenced by update_power(), and AP_SmartAudio::update_vtx_params().
get_power_mw()
uint16_t AP_VideoTX::get_power_mw () const inline
Definition at line 107 of file AP_VideoTX.h.
Referenced by init(), AP_SmartAudio::parse_response_buffer(), set_defaults(), set_power_dac(), set_power_level(), update(), update_power(), and AP_SmartAudio::update_vtx_params().
get_singleton()
static AP_VideoTX * AP_VideoTX::get_singleton (void) inline static
Definition at line 40 of file AP_VideoTX.h.
Referenced by AP::vtx().
has_option()
bool AP_VideoTX::has_option (VideoOptions option) const inline
Definition at line 143 of file AP_VideoTX.h.
Referenced by announce_vtx_settings(), change_power(), AP_SmartAudio::ignore_crc(), AP_SmartAudio::send_request(), and update().
have_params_changed()
bool AP_VideoTX::have_params_changed () const
Definition at line 413 of file AP_VideoTX.cpp.
init()
bool AP_VideoTX::init (void)
Definition at line 137 of file AP_VideoTX.cpp.
Referenced by AP_Vehicle::setup().
is_configuration_finished()
bool AP_VideoTX::is_configuration_finished () inline
Definition at line 164 of file AP_VideoTX.h.
set_band()
void AP_VideoTX::set_band (uint8_t band) inline
Definition at line 126 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer(), and AP_SmartAudio::update_vtx_settings().
set_channel()
void AP_VideoTX::set_channel (uint8_t channel) inline
Definition at line 132 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer(), and AP_SmartAudio::update_vtx_settings().
set_configuration_finished()
void AP_VideoTX::set_configuration_finished (bool configuration_finished) inline
Definition at line 163 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::loop(), and AP_SmartAudio::update_vtx_params().
set_configured_band()
void AP_VideoTX::set_configured_band (uint8_t band) inline
Definition at line 127 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer().
set_configured_channel()
void AP_VideoTX::set_configured_channel (uint8_t channel) inline
Definition at line 133 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer().
set_configured_frequency_mhz()
void AP_VideoTX::set_configured_frequency_mhz (uint16_t freq) inline
Definition at line 92 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer().
set_configured_options()
void AP_VideoTX::set_configured_options (uint16_t options) inline
Definition at line 140 of file AP_VideoTX.h.
Referenced by change_power().
set_configured_power_mw()
void AP_VideoTX::set_configured_power_mw (uint16_t power)
Definition at line 185 of file AP_VideoTX.cpp.
Referenced by change_power(), and AP_SmartAudio::parse_response_buffer().
set_defaults()
bool AP_VideoTX::set_defaults ()
Definition at line 444 of file AP_VideoTX.cpp.
Referenced by AP_SmartAudio::update_vtx_settings().
set_enabled()
void AP_VideoTX::set_enabled (bool enabled)
Definition at line 317 of file AP_VideoTX.cpp.
Referenced by AP_SmartAudio::update_vtx_settings().
set_freq_is_current()
void AP_VideoTX::set_freq_is_current ()
Definition at line 330 of file AP_VideoTX.cpp.
set_frequency_mhz()
void AP_VideoTX::set_frequency_mhz (uint16_t freq) inline
Definition at line 91 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer(), and AP_SmartAudio::update_vtx_settings().
set_options()
void AP_VideoTX::set_options (uint16_t options) inline
Definition at line 139 of file AP_VideoTX.h.
Referenced by AP_SmartAudio::parse_response_buffer(), and AP_SmartAudio::update_vtx_settings().
set_options_are_current()
void AP_VideoTX::set_options_are_current () inline
Definition at line 161 of file AP_VideoTX.h.
set_power_dac()
void AP_VideoTX::set_power_dac (uint16_t power, PowerActive active = PowerActive::Active)
Definition at line 300 of file AP_VideoTX.cpp.
Referenced by AP_SmartAudio::parse_response_buffer().
set_power_dbm()
void AP_VideoTX::set_power_dbm (uint8_t power, PowerActive active = PowerActive::Active)
Definition at line 201 of file AP_VideoTX.cpp.
Referenced by AP_SmartAudio::parse_response_buffer(), set_power_is_current(), and AP_SmartAudio::update_vtx_settings().
set_power_is_current()
void AP_VideoTX::set_power_is_current ()
Definition at line 325 of file AP_VideoTX.cpp.
set_power_level()
void AP_VideoTX::set_power_level (uint8_t level, PowerActive active = PowerActive::Active)
Definition at line 282 of file AP_VideoTX.cpp.
Referenced by AP_SmartAudio::parse_response_buffer(), and AP_SmartAudio::update_vtx_settings().
set_power_mw()
void AP_VideoTX::set_power_mw (uint16_t power)
Definition at line 271 of file AP_VideoTX.cpp.
update()
void AP_VideoTX::update (void)
Definition at line 338 of file AP_VideoTX.cpp.
update_all_power_dbm()
void AP_VideoTX::update_all_power_dbm (uint8_t nlevels, const uint8_t levels[])
Definition at line 257 of file AP_VideoTX.cpp.
Referenced by AP_SmartAudio::update_vtx_settings().
update_band()
bool AP_VideoTX::update_band () const inline
Definition at line 130 of file AP_VideoTX.h.
Referenced by have_params_changed(), and AP_SmartAudio::update_vtx_params().
update_channel()
bool AP_VideoTX::update_channel () const inline
Definition at line 136 of file AP_VideoTX.h.
Referenced by have_params_changed(), and AP_SmartAudio::update_vtx_params().
update_configured_channel_and_band()
void AP_VideoTX::update_configured_channel_and_band ()
Definition at line 430 of file AP_VideoTX.cpp.
Referenced by AP_SmartAudio::parse_response_buffer(), set_defaults(), and AP_SmartAudio::update_vtx_params().
update_configured_frequency()
void AP_VideoTX::update_configured_frequency ()
Definition at line 424 of file AP_VideoTX.cpp.
Referenced by AP_SmartAudio::parse_response_buffer(), set_defaults(), update_configured_channel_and_band(), and AP_SmartAudio::update_vtx_params().
update_enabled()
bool AP_VideoTX::update_enabled () const inline
Definition at line 150 of file AP_VideoTX.h.
update_frequency()
bool AP_VideoTX::update_frequency () const inline
Definition at line 95 of file AP_VideoTX.h.
Referenced by have_params_changed(), and AP_SmartAudio::update_vtx_params().
update_options()
bool AP_VideoTX::update_options () const
Definition at line 371 of file AP_VideoTX.cpp.
Referenced by have_params_changed(), and AP_SmartAudio::update_vtx_params().
update_power()
bool AP_VideoTX::update_power () const
Definition at line 398 of file AP_VideoTX.cpp.
Referenced by have_params_changed(), and AP_SmartAudio::update_vtx_params().
update_power_dbm()
uint8_t AP_VideoTX::update_power_dbm (uint8_t power, PowerActive active = PowerActive::Active)
Definition at line 235 of file AP_VideoTX.cpp.
Referenced by AP_SmartAudio::parse_response_buffer(), set_power_dbm(), and update_all_power_dbm().
Member Data Documentation
_band
AP_Int8 AP_VideoTX::_band private
Definition at line 180 of file AP_VideoTX.h.
Referenced by announce_vtx_settings(), get_configured_band(), init(), set_configured_band(), set_defaults(), set_freq_is_current(), update_band(), update_configured_channel_and_band(), and update_configured_frequency().
_channel
AP_Int8 AP_VideoTX::_channel private
Definition at line 184 of file AP_VideoTX.h.
Referenced by announce_vtx_settings(), get_configured_channel(), init(), set_configured_channel(), set_defaults(), set_freq_is_current(), update_channel(), update_configured_channel_and_band(), and update_configured_frequency().
_configuration_finished
bool AP_VideoTX::_configuration_finished private
Definition at line 198 of file AP_VideoTX.h.
Referenced by is_configuration_finished(), and set_configuration_finished().
_current_band
uint16_t AP_VideoTX::_current_band private
Definition at line 181 of file AP_VideoTX.h.
Referenced by get_band(), init(), set_band(), set_defaults(), set_freq_is_current(), and update_band().
_current_channel
uint8_t AP_VideoTX::_current_channel private
Definition at line 185 of file AP_VideoTX.h.
Referenced by get_channel(), init(), set_channel(), set_defaults(), set_freq_is_current(), and update_channel().
_current_enabled
bool AP_VideoTX::_current_enabled private
Definition at line 192 of file AP_VideoTX.h.
Referenced by init(), set_enabled(), and update_enabled().
_current_frequency
uint16_t AP_VideoTX::_current_frequency private
Definition at line 172 of file AP_VideoTX.h.
Referenced by get_frequency_mhz(), init(), set_defaults(), set_freq_is_current(), set_frequency_mhz(), and update_frequency().
_current_options
uint16_t AP_VideoTX::_current_options private
Definition at line 189 of file AP_VideoTX.h.
Referenced by get_options(), get_pitmode(), init(), set_defaults(), set_options(), set_options_are_current(), and update_options().
_current_power
uint16_t AP_VideoTX::_current_power private
Definition at line 176 of file AP_VideoTX.h.
Referenced by init(), set_power_dac(), set_power_dbm(), set_power_level(), and set_power_mw().
_defaults_set
bool AP_VideoTX::_defaults_set private
Definition at line 196 of file AP_VideoTX.h.
Referenced by set_defaults(), update_band(), update_channel(), update_enabled(), update_frequency(), update_options(), and update_power().
_enabled
AP_Int8 AP_VideoTX::_enabled private
Definition at line 191 of file AP_VideoTX.h.
Referenced by change_power(), get_enabled(), have_params_changed(), init(), set_enabled(), update(), and update_enabled().
_frequency_mhz
AP_Int16 AP_VideoTX::_frequency_mhz private
Definition at line 171 of file AP_VideoTX.h.
Referenced by announce_vtx_settings(), get_configured_frequency_mhz(), init(), set_configured_frequency_mhz(), set_defaults(), set_freq_is_current(), update_configured_channel_and_band(), update_configured_frequency(), and update_frequency().
_initialized
bool AP_VideoTX::_initialized private
Definition at line 194 of file AP_VideoTX.h.
Referenced by init().
_max_power_mw
AP_Int16 AP_VideoTX::_max_power_mw private
Definition at line 177 of file AP_VideoTX.h.
Referenced by change_power().
_options
AP_Int16 AP_VideoTX::_options private
Definition at line 188 of file AP_VideoTX.h.
Referenced by get_configured_options(), get_configured_pitmode(), has_option(), init(), set_configured_options(), set_defaults(), set_options_are_current(), update(), and update_options().
_power_levels
AP_VideoTX::PowerLevel AP_VideoTX::_power_levels static
Initial value:
= {
    { 0xFF,  0,    0, 0    },
    { 0,    25,   14, 7    },
    { 0x11, 100,  20, 0xFF },
    { 1,    200,  23, 16   },
    { 0x12, 400,  26, 0xFF },
    { 2,    500,  27, 25   },
    { 3,    800,  29, 40   },
    { 0x13, 1000, 30, 0xFF },
    { 0xFF, 0,    0,  0XFF, PowerActive::Inactive }
}
Definition at line 107 of file AP_VideoTX.h.
Referenced by change_power(), find_current_power(), get_configured_power_dac(), get_configured_power_dbm(), get_configured_power_level(), init(), set_power_dac(), set_power_dbm(), set_power_level(), set_power_mw(), update(), update_all_power_dbm(), update_power(), and update_power_dbm().
_power_mw
AP_Int16 AP_VideoTX::_power_mw private
Definition at line 175 of file AP_VideoTX.h.
Referenced by announce_vtx_settings(), find_current_power(), get_configured_power_mw(), init(), set_configured_power_mw(), set_defaults(), update(), and update_power().
band_names
const char * AP_VideoTX::band_names = {"A","B","E","F","R","L"} static
Definition at line 90 of file AP_VideoTX.h.
Referenced by announce_vtx_settings().
singleton
AP_VideoTX * AP_VideoTX::singleton static
Definition at line 166 of file AP_VideoTX.h.
Referenced by AP_VideoTX(), get_singleton(), and ~AP_VideoTX().
var_info
const AP_Param::GroupInfo AP_VideoTX::var_info static
Definition at line 29 of file AP_VideoTX.h.
VIDEO_CHANNELS
const uint16_t AP_VideoTX::VIDEO_CHANNELS static
Initial value:
=
{
    { 5865, 5845, 5825, 5805, 5785, 5765, 5745, 5725},
    { 5733, 5752, 5771, 5790, 5809, 5828, 5847, 5866},
    { 5705, 5685, 5665, 5645, 5885, 5905, 5925, 5945},
    { 5740, 5760, 5780, 5800, 5820, 5840, 5860, 5880},
    { 5658, 5695, 5732, 5769, 5806, 5843, 5880, 5917},
    { 5621, 5584, 5547, 5510, 5473, 5436, 5399, 5362},
    { 1080, 1120, 1160, 1200, 1240, 1280, 1320, 1360},
    { 1080, 1120, 1160, 1200, 1258, 1280, 1320, 1360}
}
Definition at line 92 of file AP_VideoTX.h.
Referenced by get_band_and_channel(), and get_frequency_mhz().
The documentation for this class was generated from the following files:
libraries/AP_VideoTX/AP_VideoTX.h
libraries/AP_VideoTX/AP_VideoTX.cpp