APM:Libraries: Linux::SPIDeviceManager Class Reference
Linux::SPIDeviceManager Class Reference
#include <SPIDevice.h>
Public Member Functions
SPIDeviceManager ()
AP_HAL::OwnPtr< AP_HAL::SPIDevice > get_device (const char *name) override
void teardown ()
uint8_t get_count () override
const char * get_device_name (uint8_t idx) override
Public Member Functions inherited from AP_HAL::SPIDeviceManager
virtual void set_register_rw_callback (const char *name, AP_HAL::Device::RegisterRWCb cb)
Static Public Member Functions
static SPIDeviceManager * from (AP_HAL::SPIDeviceManager *spi_mgr)
Protected Member Functions
void _unregister (SPIBus &b)
AP_HAL::OwnPtr< AP_HAL::SPIDevice > _create_device (SPIBus &b, SPIDesc &device_desc) const
Protected Attributes
std::vector< SPIBus * > _buses
Static Protected Attributes
static const uint8_t _n_device_desc = LINUX_SPI_DEVICE_NUM_DEVICES
static SPIDesc _device []
Friends
class SPIDevice
Detailed Description
Definition at line 77 of file SPIDevice.h.
Constructor & Destructor Documentation
SPIDeviceManager()
Linux::SPIDeviceManager::SPIDeviceManager () inline
Definition at line 86 of file SPIDevice.h.
Member Function Documentation
_create_device()
AP_HAL::OwnPtr< AP_HAL::SPIDevice > Linux::SPIDeviceManager::_create_device (SPIBus & b, SPIDesc & device_desc) const protected
Definition at line 501 of file SPIDevice.cpp.
Referenced by get_device().
_unregister()
void Linux::SPIDeviceManager::_unregister (SPIBus & b) protected
Definition at line 516 of file SPIDevice.cpp.
Referenced by Linux::SPIDevice::~SPIDevice().
from()
static SPIDeviceManager * Linux::SPIDeviceManager::from (AP_HAL::SPIDeviceManager * spi_mgr) inline static
Definition at line 81 of file SPIDevice.h.
Referenced by HAL_Linux::run(), and Linux::SPIDevice::~SPIDevice().
get_count()
uint8_t Linux::SPIDeviceManager::get_count () override virtual
Reimplemented from AP_HAL::SPIDeviceManager.
Definition at line 489 of file SPIDevice.cpp.
get_device()
AP_HAL::OwnPtr< AP_HAL::SPIDevice > Linux::SPIDeviceManager::get_device (const char * name) override virtual
Reimplemented from AP_HAL::SPIDeviceManager.
Definition at line 450 of file SPIDevice.cpp.
get_device_name()
const char * Linux::SPIDeviceManager::get_device_name (uint8_t idx) override virtual
Reimplemented from AP_HAL::SPIDeviceManager.
Definition at line 494 of file SPIDevice.cpp.
teardown()
void Linux::SPIDeviceManager::teardown ()
Definition at line 531 of file SPIDevice.cpp.
Referenced by HAL_Linux::run().
Friends And Related Symbol Documentation
SPIDevice
friend class SPIDevice friend
Definition at line 79 of file SPIDevice.h.
Referenced by _create_device().
Member Data Documentation
_buses
std::vector<SPIBus*> Linux::SPIDeviceManager::_buses protected
Definition at line 112 of file SPIDevice.h.
Referenced by _unregister(), get_device(), SPIDeviceManager(), and teardown().
_device
SPIDesc Linux::SPIDeviceManager::_device static protected
Initial value:
= {
    SPIDesc("lsm9ds0_am", 1, 0, SPI_MODE_3, 8, BBB_P9_17,  10*MHZ,10*MHZ),
    SPIDesc("lsm9ds0_g",  1, 0, SPI_MODE_3, 8, BBB_P8_9,   10*MHZ,10*MHZ),
    SPIDesc("ms5611",     2, 0, SPI_MODE_3, 8, BBB_P9_42,  10*MHZ,10*MHZ),
    SPIDesc("mpu6000",    2, 0, SPI_MODE_3, 8, BBB_P9_28,  500*1000, 20*MHZ),
    SPIDesc("mpu9250",    2, 0, SPI_MODE_3, 8, BBB_P9_23,  1*MHZ, 11*MHZ),
}
Definition at line 115 of file SPIDevice.h.
Referenced by get_device(), and get_device_name().
_n_device_desc
const uint8_t Linux::SPIDeviceManager::_n_device_desc = LINUX_SPI_DEVICE_NUM_DEVICES static protected
Definition at line 114 of file SPIDevice.h.
Referenced by get_count(), and get_device().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/SPIDevice.h
libraries/AP_HAL_Linux/SPIDevice.cpp