APM:Libraries: AP_RCProtocol_ST24 Class Reference
AP_RCProtocol_ST24 Class Reference
#include <AP_RCProtocol_ST24.h>
Classes
struct ChannelData12
struct ChannelData24
struct ReceiverFcPacket
struct TelemetryData
Public Member Functions
AP_RCProtocol_ST24 (AP_RCProtocol &_frontend)
void process_pulse (uint32_t width_s0, uint32_t width_s1) override
void process_byte (uint8_t byte, uint32_t baudrate) override
Public Member Functions inherited from AP_RCProtocol_Backend
AP_RCProtocol_Backend (AP_RCProtocol &_frontend)
virtual ~AP_RCProtocol_Backend ()
virtual void process_handshake (uint32_t baudrate)
uint16_t read (uint8_t chan)
void read (uint16_t *pwm, uint8_t n)
bool new_input ()
uint8_t num_channels () const
virtual void start_bind (void)
virtual void update (void)
uint32_t get_rc_frame_count (void) const
void reset_rc_frame_count (void)
uint32_t get_rc_input_count (void) const
uint32_t get_rc_protocols_mask (void) const
bool protocol_enabled (enum AP_RCProtocol::rcprotocol_t protocol) const
int16_t get_RSSI (void) const
int16_t get_rx_link_quality (void) const
AP_HAL::UARTDriver * get_UART (void) const
AP_HAL::UARTDriver * get_available_UART (void) const
bool have_UART (void) const
virtual bool is_rx_active () const
bool is_detected () const
Private Types
enum ST24_PACKET_TYPE { ST24_PACKET_TYPE_CHANNELDATA12 = 0 , ST24_PACKET_TYPE_CHANNELDATA24 , ST24_PACKET_TYPE_TRANSMITTERGPSDATA }
enum ST24_DECODE_STATE {
ST24_DECODE_STATE_UNSYNCED = 0 , ST24_DECODE_STATE_GOT_STX1 , ST24_DECODE_STATE_GOT_STX2 , ST24_DECODE_STATE_GOT_LEN ,
ST24_DECODE_STATE_GOT_TYPE , ST24_DECODE_STATE_GOT_DATA
}
Private Member Functions
void _process_byte (uint8_t byte)
Static Private Member Functions
static uint8_t st24_crc8 (uint8_t *ptr, uint8_t len)
Private Attributes
enum ST24_DECODE_STATE _decode_state = ST24_DECODE_STATE_UNSYNCED
uint8_t _rxlen
ReceiverFcPacket _rxpacket
SoftSerial ss {115200, SoftSerial::SERIAL_CONFIG_8N1}
Additional Inherited Members
Protected Member Functions inherited from AP_RCProtocol_Backend
void add_input (uint8_t num_channels, uint16_t *values, bool in_failsafe, int16_t rssi=-1, int16_t rx_link_quality=-1)
void log_data (AP_RCProtocol::rcprotocol_t prot, uint32_t timestamp, const uint8_t *data, uint8_t len) const
Static Protected Member Functions inherited from AP_RCProtocol_Backend
static void decode_11bit_channels (const uint8_t *data, uint8_t nchannels, uint16_t *values, uint16_t mult, uint16_t div, uint16_t offset)
Protected Attributes inherited from AP_RCProtocol_Backend
struct AP_RCProtocol_Backend::Channels11Bit_8Chan PACKED
AP_RCProtocol & frontend
Detailed Description
Definition at line 43 of file AP_RCProtocol_ST24.h.
Member Enumeration Documentation
ST24_DECODE_STATE
enum AP_RCProtocol_ST24::ST24_DECODE_STATE private
Enumerator
ST24_DECODE_STATE_UNSYNCED
ST24_DECODE_STATE_GOT_STX1
ST24_DECODE_STATE_GOT_STX2
ST24_DECODE_STATE_GOT_LEN
ST24_DECODE_STATE_GOT_TYPE
ST24_DECODE_STATE_GOT_DATA
Definition at line 140 of file AP_RCProtocol_ST24.h.
ST24_PACKET_TYPE
enum AP_RCProtocol_ST24::ST24_PACKET_TYPE private
Enumerator
ST24_PACKET_TYPE_CHANNELDATA12
ST24_PACKET_TYPE_CHANNELDATA24
ST24_PACKET_TYPE_TRANSMITTERGPSDATA
Definition at line 51 of file AP_RCProtocol_ST24.h.
Constructor & Destructor Documentation
AP_RCProtocol_ST24()
AP_RCProtocol_ST24::AP_RCProtocol_ST24 (AP_RCProtocol & _frontend) inline
Definition at line 45 of file AP_RCProtocol_ST24.h.
Member Function Documentation
_process_byte()
void AP_RCProtocol_ST24::_process_byte (uint8_t byte) private
Definition at line 90 of file AP_RCProtocol_ST24.cpp.
Referenced by process_byte(), and process_pulse().
process_byte()
void AP_RCProtocol_ST24::process_byte (uint8_t byte, uint32_t baudrate) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 235 of file AP_RCProtocol_ST24.cpp.
process_pulse()
void AP_RCProtocol_ST24::process_pulse (uint32_t width_s0, uint32_t width_s1) override virtual
Reimplemented from AP_RCProtocol_Backend.
Definition at line 82 of file AP_RCProtocol_ST24.cpp.
st24_crc8()
uint8_t AP_RCProtocol_ST24::st24_crc8 (uint8_t * ptr, uint8_t len) static private
Definition at line 55 of file AP_RCProtocol_ST24.cpp.
Referenced by _process_byte().
Member Data Documentation
_decode_state
enum ST24_DECODE_STATE AP_RCProtocol_ST24::_decode_state = ST24_DECODE_STATE_UNSYNCED private
Definition at line 149 of file AP_RCProtocol_ST24.h.
Referenced by _process_byte().
_rxlen
uint8_t AP_RCProtocol_ST24::_rxlen private
Definition at line 150 of file AP_RCProtocol_ST24.h.
Referenced by _process_byte().
_rxpacket
ReceiverFcPacket AP_RCProtocol_ST24::_rxpacket private
Definition at line 152 of file AP_RCProtocol_ST24.h.
Referenced by _process_byte().
ss
SoftSerial AP_RCProtocol_ST24::ss {115200, SoftSerial::SERIAL_CONFIG_8N1} private
Definition at line 154 of file AP_RCProtocol_ST24.h.
Referenced by process_pulse().
The documentation for this class was generated from the following files:
libraries/AP_RCProtocol/AP_RCProtocol_ST24.h
libraries/AP_RCProtocol/AP_RCProtocol_ST24.cpp