APM:Libraries: AP_RangeFinder_Backend Class Reference
AP_RangeFinder_Backend Class Reference abstract
#include <AP_RangeFinder_Backend.h>
Public Member Functions
AP_RangeFinder_Backend (RangeFinder::RangeFinder_State &_state, AP_RangeFinder_Params &_params)
virtual ~AP_RangeFinder_Backend (void)
virtual void update ()=0
virtual void init_serial (uint8_t serial_instance)
virtual void handle_msg (const mavlink_message_t &msg)
enum Rotation orientation () const
float distance () const
uint16_t distance_cm () const
int8_t signal_quality_pct () const WARN_IF_UNUSED
uint16_t voltage_mv () const
virtual int16_t max_distance_cm () const
virtual int16_t min_distance_cm () const
int16_t ground_clearance_cm () const
MAV_DISTANCE_SENSOR get_mav_distance_sensor_type () const
RangeFinder::Status status () const
RangeFinder::Type type () const
bool has_data () const
uint8_t range_valid_count () const
const Vector3f & get_pos_offset () const
uint32_t last_reading_ms () const
virtual bool get_temp (float &temp) const
RangeFinder::Type allocated_type () const
Protected Member Functions
void update_status (RangeFinder::RangeFinder_State &state_arg) const
void update_status ()
void set_status (RangeFinder::Status status)
virtual MAV_DISTANCE_SENSOR _get_mav_distance_sensor_type () const =0
Static Protected Member Functions
static void set_status (RangeFinder::RangeFinder_State &state_arg, RangeFinder::Status status)
Protected Attributes
RangeFinder::RangeFinder_State & state
AP_RangeFinder_Params & params
HAL_Semaphore _sem
RangeFinder::Type _backend_type
Detailed Description
Definition at line 22 of file AP_RangeFinder_Backend.h.
Constructor & Destructor Documentation
AP_RangeFinder_Backend()
AP_RangeFinder_Backend::AP_RangeFinder_Backend (RangeFinder::RangeFinder_State & _state, AP_RangeFinder_Params & _params)
Definition at line 27 of file AP_RangeFinder_Backend.cpp.
~AP_RangeFinder_Backend()
virtual AP_RangeFinder_Backend::~AP_RangeFinder_Backend (void) inline virtual
Definition at line 30 of file AP_RangeFinder_Backend.h.
Member Function Documentation
_get_mav_distance_sensor_type()
virtual MAV_DISTANCE_SENSOR AP_RangeFinder_Backend::_get_mav_distance_sensor_type () const protected pure virtual
Implemented in AP_RangeFinder_analog, AP_RangeFinder_BBB_PRU, AP_RangeFinder_Benewake, AP_RangeFinder_Benewake_TFMiniPlus, AP_RangeFinder_BLPing, AP_RangeFinder_GYUS42v2, AP_RangeFinder_HC_SR04, AP_RangeFinder_Lanbao, AP_RangeFinder_LeddarOne, AP_RangeFinder_LeddarVu8, AP_RangeFinder_LightWareI2C, AP_RangeFinder_LightWareSerial, AP_RangeFinder_MaxsonarI2CXL, AP_RangeFinder_MaxsonarSerialLV, AP_RangeFinder_NMEA, AP_RangeFinder_PulsedLightLRF, AP_RangeFinder_PWM, AP_RangeFinder_SITL, AP_RangeFinder_TeraRanger_Serial, AP_RangeFinder_TeraRangerI2C, AP_RangeFinder_USD1_Serial, AP_RangeFinder_VL53L0X, AP_RangeFinder_VL53L1X, and AP_RangeFinder_Wasp.
Referenced by get_mav_distance_sensor_type().
allocated_type()
RangeFinder::Type AP_RangeFinder_Backend::allocated_type () const inline
Definition at line 80 of file AP_RangeFinder_Backend.h.
distance()
float AP_RangeFinder_Backend::distance () const inline
Definition at line 51 of file AP_RangeFinder_Backend.h.
Referenced by RangeFinder::distance_orient(), and AP_RangeFinder_Benewake_TFMiniPlus::timer().
distance_cm()
uint16_t AP_RangeFinder_Backend::distance_cm () const inline
Definition at line 52 of file AP_RangeFinder_Backend.h.
Referenced by AP_RangeFinder_LightWareSerial::is_lost_signal_distance(), loop(), and AP_DAL_RangeFinder_Backend::start_frame().
get_mav_distance_sensor_type()
MAV_DISTANCE_SENSOR AP_RangeFinder_Backend::get_mav_distance_sensor_type () const
Definition at line 34 of file AP_RangeFinder_Backend.cpp.
Referenced by RangeFinder::get_mav_distance_sensor_type_orient().
get_pos_offset()
const Vector3f & AP_RangeFinder_Backend::get_pos_offset () const inline
Definition at line 70 of file AP_RangeFinder_Backend.h.
Referenced by RangeFinder::get_pos_offset_orient(), and AP_DAL_RangeFinder_Backend::start_frame().
get_temp()
virtual bool AP_RangeFinder_Backend::get_temp (float & temp) const inline virtual
Reimplemented in AP_RangeFinder_NMEA.
Definition at line 76 of file AP_RangeFinder_Backend.h.
Referenced by RangeFinder::get_temp().
ground_clearance_cm()
int16_t AP_RangeFinder_Backend::ground_clearance_cm () const inline
Definition at line 57 of file AP_RangeFinder_Backend.h.
Referenced by RangeFinder::ground_clearance_cm_orient().
handle_msg()
virtual void AP_RangeFinder_Backend::handle_msg (const mavlink_message_t & msg) inline virtual
Definition at line 36 of file AP_RangeFinder_Backend.h.
Referenced by RangeFinder::handle_msg().
has_data()
bool AP_RangeFinder_Backend::has_data () const
Definition at line 50 of file AP_RangeFinder_Backend.cpp.
Referenced by RangeFinder::has_data_orient(), and loop().
init_serial()
virtual void AP_RangeFinder_Backend::init_serial (uint8_t serial_instance) inline virtual
Reimplemented in AP_RangeFinder_Backend_Serial.
Definition at line 34 of file AP_RangeFinder_Backend.h.
Referenced by RangeFinder::_add_backend().
last_reading_ms()
uint32_t AP_RangeFinder_Backend::last_reading_ms () const inline
Definition at line 73 of file AP_RangeFinder_Backend.h.
Referenced by RangeFinder::last_reading_ms().
max_distance_cm()
virtual int16_t AP_RangeFinder_Backend::max_distance_cm () const inline virtual
Definition at line 55 of file AP_RangeFinder_Backend.h.
Referenced by AP_RangeFinder_Benewake::get_reading(), AP_RangeFinder_LeddarVu8::get_reading(), AP_RangeFinder_LightWareSerial::get_reading(), AP_RangeFinder_TeraRanger_Serial::get_reading(), AP_RangeFinder_LightWareI2C::legacy_get_reading(), RangeFinder::max_distance_cm_orient(), AP_RangeFinder_Benewake_TFMiniPlus::process_raw_measure(), AP_RangeFinder_TeraRangerI2C::process_raw_measure(), AP_RangeFinder_LightWareI2C::sf20_parse_stream(), and update_status().
min_distance_cm()
virtual int16_t AP_RangeFinder_Backend::min_distance_cm () const inline virtual
Definition at line 56 of file AP_RangeFinder_Backend.h.
Referenced by RangeFinder::min_distance_cm_orient(), and update_status().
orientation()
enum Rotation AP_RangeFinder_Backend::orientation () const inline
Definition at line 50 of file AP_RangeFinder_Backend.h.
Referenced by RangeFinder::find_instance(), GCS_MAVLINK::send_distance_sensor(), and AP_DAL_RangeFinder_Backend::start_frame().
range_valid_count()
uint8_t AP_RangeFinder_Backend::range_valid_count () const inline
Definition at line 66 of file AP_RangeFinder_Backend.h.
Referenced by RangeFinder::range_valid_count_orient().
set_status() [1/2]
void AP_RangeFinder_Backend::set_status (RangeFinder::RangeFinder_State & state_arg, RangeFinder::Status status) static protected
Definition at line 69 of file AP_RangeFinder_Backend.cpp.
Referenced by AP_RangeFinder_analog::AP_RangeFinder_analog(), AP_RangeFinder_HC_SR04::AP_RangeFinder_HC_SR04(), AP_RangeFinder_Wasp::get_reading(), AP_RangeFinder_LightWareI2C::legacy_timer(), AP_RangeFinder_LightWareI2C::sf20_timer(), AP_RangeFinder_PulsedLightLRF::timer(), AP_RangeFinder_Backend_Serial::update(), AP_RangeFinder_Benewake_TFMiniPlus::update(), AP_RangeFinder_MaxsonarI2CXL::update(), AP_RangeFinder_PWM::update(), AP_RangeFinder_TeraRangerI2C::update(), AP_RangeFinder_VL53L0X::update(), AP_RangeFinder_VL53L1X::update(), AP_RangeFinder_Wasp::update(), update_status(), and AP_RangeFinder_analog::update_voltage().
set_status() [2/2]
void AP_RangeFinder_Backend::set_status (RangeFinder::Status status) inline protected
Definition at line 90 of file AP_RangeFinder_Backend.h.
Referenced by set_status().
signal_quality_pct()
int8_t AP_RangeFinder_Backend::signal_quality_pct () const inline
Definition at line 53 of file AP_RangeFinder_Backend.h.
Referenced by RangeFinder::signal_quality_pct_orient().
status()
RangeFinder::Status AP_RangeFinder_Backend::status () const
Definition at line 41 of file AP_RangeFinder_Backend.cpp.
Referenced by RangeFinder::find_instance(), AP_RangeFinder_BLPing::get_signal_quality_pct(), loop(), set_status(), AP_DAL_RangeFinder_Backend::start_frame(), RangeFinder::status_orient(), and AP_RangeFinder_BLPing::update().
type()
RangeFinder::Type AP_RangeFinder_Backend::type () const inline
Definition at line 60 of file AP_RangeFinder_Backend.h.
Referenced by AP_RangeFinder_Backend(), get_mav_distance_sensor_type(), loop(), and status().
update()
virtual void AP_RangeFinder_Backend::update () pure virtual
Implemented in AP_RangeFinder_SITL, AP_RangeFinder_analog, AP_RangeFinder_Backend_Serial, AP_RangeFinder_BBB_PRU, AP_RangeFinder_Benewake_TFMiniPlus, AP_RangeFinder_BLPing, AP_RangeFinder_HC_SR04, AP_RangeFinder_LightWareI2C, AP_RangeFinder_MaxsonarI2CXL, AP_RangeFinder_PulsedLightLRF, AP_RangeFinder_PWM, AP_RangeFinder_TeraRangerI2C, AP_RangeFinder_VL53L0X, AP_RangeFinder_VL53L1X, and AP_RangeFinder_Wasp.
Referenced by RangeFinder::update().
update_status() [1/2]
void AP_RangeFinder_Backend::update_status () inline protected
Definition at line 86 of file AP_RangeFinder_Backend.h.
Referenced by AP_RangeFinder_LightWareI2C::legacy_timer(), AP_RangeFinder_LightWareI2C::sf20_timer(), AP_RangeFinder_PulsedLightLRF::timer(), AP_RangeFinder_SITL::update(), AP_RangeFinder_analog::update(), AP_RangeFinder_Backend_Serial::update(), AP_RangeFinder_Benewake_TFMiniPlus::update(), AP_RangeFinder_HC_SR04::update(), AP_RangeFinder_MaxsonarI2CXL::update(), AP_RangeFinder_PWM::update(), AP_RangeFinder_TeraRangerI2C::update(), AP_RangeFinder_VL53L0X::update(), AP_RangeFinder_VL53L1X::update(), and update_status().
update_status() [2/2]
void AP_RangeFinder_Backend::update_status (RangeFinder::RangeFinder_State & state_arg) const protected
Definition at line 56 of file AP_RangeFinder_Backend.cpp.
voltage_mv()
uint16_t AP_RangeFinder_Backend::voltage_mv () const inline
Definition at line 54 of file AP_RangeFinder_Backend.h.
Member Data Documentation
_backend_type
RangeFinder::Type AP_RangeFinder_Backend::_backend_type protected
Definition at line 99 of file AP_RangeFinder_Backend.h.
Referenced by allocated_type(), and AP_RangeFinder_Backend().
_sem
HAL_Semaphore AP_RangeFinder_Backend::_sem protected
Definition at line 96 of file AP_RangeFinder_Backend.h.
Referenced by AP_RangeFinder_MaxsonarI2CXL::_timer(), AP_RangeFinder_Benewake_TFMiniPlus::timer(), AP_RangeFinder_VL53L1X::timer(), AP_RangeFinder_TeraRangerI2C::timer(), AP_RangeFinder_Benewake_TFMiniPlus::update(), AP_RangeFinder_MaxsonarI2CXL::update(), AP_RangeFinder_TeraRangerI2C::update(), and AP_RangeFinder_VL53L1X::update().
params
AP_RangeFinder_Params& AP_RangeFinder_Backend::params protected
Definition at line 93 of file AP_RangeFinder_Backend.h.
Referenced by AP_RangeFinder_MaxsonarSerialLV::AP_RangeFinder_MaxsonarSerialLV(), AP_RangeFinder_PWM::AP_RangeFinder_PWM(), AP_RangeFinder_HC_SR04::check_echo_pin(), AP_RangeFinder_PWM::check_pin(), AP_RangeFinder_PWM::check_stop_pin(), AP_RangeFinder_HC_SR04::check_trigger_pin(), get_pos_offset(), AP_RangeFinder_PWM::get_reading(), AP_RangeFinder_MaxsonarSerialLV::get_reading(), AP_RangeFinder_LeddarVu8::get_sensor_address(), ground_clearance_cm(), max_distance_cm(), min_distance_cm(), orientation(), AP_RangeFinder_PWM::out_of_range(), type(), AP_RangeFinder_analog::update(), AP_RangeFinder_PWM::update(), and AP_RangeFinder_analog::update_voltage().
state
RangeFinder::RangeFinder_State& AP_RangeFinder_Backend::state protected
Definition at line 92 of file AP_RangeFinder_Backend.h.
Referenced by AP_RangeFinder_MaxsonarI2CXL::_timer(), AP_RangeFinder_Wasp::AP_RangeFinder_Wasp(), distance(), distance_cm(), AP_RangeFinder_LightWareSerial::get_reading(), AP_RangeFinder_Wasp::get_reading(), has_data(), last_reading_ms(), AP_RangeFinder_LightWareI2C::legacy_timer(), range_valid_count(), set_status(), AP_RangeFinder_LightWareI2C::sf20_timer(), signal_quality_pct(), status(), AP_RangeFinder_PulsedLightLRF::timer(), AP_RangeFinder_SITL::update(), AP_RangeFinder_analog::update(), AP_RangeFinder_Backend_Serial::update(), AP_RangeFinder_BBB_PRU::update(), AP_RangeFinder_Benewake_TFMiniPlus::update(), AP_RangeFinder_HC_SR04::update(), AP_RangeFinder_MaxsonarI2CXL::update(), AP_RangeFinder_PWM::update(), AP_RangeFinder_TeraRangerI2C::update(), AP_RangeFinder_VL53L0X::update(), AP_RangeFinder_VL53L1X::update(), AP_RangeFinder_Wasp::update(), update_status(), AP_RangeFinder_analog::update_voltage(), and voltage_mv().
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder_Backend.h
libraries/AP_RangeFinder/AP_RangeFinder_Backend.cpp