APM:Libraries: SITL::RF_Benewake Class Reference
SITL::RF_Benewake Class Reference abstract
#include <SIM_RF_Benewake.h>
Public Member Functions
uint32_t packet_for_alt (uint16_t alt_cm, uint8_t *buffer, uint8_t buflen) override
Public Member Functions inherited from SITL::SerialRangeFinder
SerialRangeFinder ()
virtual void update (float range)
virtual uint16_t reading_interval_ms () const
virtual bool has_temperature () const
virtual uint32_t packet_for_temperature (float temperature, uint8_t *buffer, uint8_t buflen)
Public Member Functions inherited from SITL::SerialDevice
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Private Member Functions
virtual uint8_t byte4 () const =0
virtual uint8_t byte5 () const =0
virtual uint8_t byte6 () const =0
virtual uint8_t byte7 () const =0
Additional Inherited Members
Protected Member Functions inherited from SITL::SerialDevice
bool init_sitl_pointer () WARN_IF_UNUSED
Protected Attributes inherited from SITL::SerialDevice
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Detailed Description
Definition at line 25 of file SIM_RF_Benewake.h.
Member Function Documentation
byte4()
virtual uint8_t SITL::RF_Benewake::byte4 () const private pure virtual
Implemented in SITL::RF_Benewake_TF02, SITL::RF_Benewake_TF03, and SITL::RF_Benewake_TFmini.
Referenced by packet_for_alt().
byte5()
virtual uint8_t SITL::RF_Benewake::byte5 () const private pure virtual
Implemented in SITL::RF_Benewake_TF02, SITL::RF_Benewake_TF03, and SITL::RF_Benewake_TFmini.
Referenced by packet_for_alt().
byte6()
virtual uint8_t SITL::RF_Benewake::byte6 () const private pure virtual
Implemented in SITL::RF_Benewake_TF02, SITL::RF_Benewake_TF03, and SITL::RF_Benewake_TFmini.
Referenced by packet_for_alt().
byte7()
virtual uint8_t SITL::RF_Benewake::byte7 () const private pure virtual
Implemented in SITL::RF_Benewake_TF02, SITL::RF_Benewake_TF03, and SITL::RF_Benewake_TFmini.
Referenced by packet_for_alt().
packet_for_alt()
uint32_t RF_Benewake::packet_for_alt (uint16_t alt_cm, uint8_t * buffer, uint8_t buflen) override virtual
Implements SITL::SerialRangeFinder.
Definition at line 23 of file SIM_RF_Benewake.cpp.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_RF_Benewake.h
libraries/SITL/SIM_RF_Benewake.cpp