APM:Libraries: AP_RAMTRON Class Reference
AP_RAMTRON Class Reference
#include <AP_RAMTRON.h>
Classes
struct ramtron_id
Public Member Functions
bool init (void)
uint32_t get_size (void) const
bool read (uint32_t offset, uint8_t *const buf, uint32_t size)
bool write (uint32_t offset, uint8_t const *const buf, uint32_t size)
Private Types
enum class RDID_type : uint8_t { Cypress , Fujitsu , Petabytes }
Private Member Functions
bool _init (void)
bool _read (uint32_t offset, uint8_t *const buf, uint32_t size)
void send_offset (uint8_t cmd, uint32_t offset) const
Private Attributes
AP_HAL::OwnPtr< AP_HAL::SPIDevice > dev
uint8_t id = UINT8_MAX
Static Private Attributes
static const struct ramtron_id ramtron_ids []
Detailed Description
Definition at line 9 of file AP_RAMTRON.h.
Member Enumeration Documentation
RDID_type
enum class AP_RAMTRON::RDID_type : uint8_t strong private
Enumerator
Cypress
Fujitsu
Petabytes
Definition at line 28 of file AP_RAMTRON.h.
Member Function Documentation
_init()
bool AP_RAMTRON::_init (void) private
_read()
bool AP_RAMTRON::_read (uint32_t offset, uint8_t *const buf, uint32_t size) private
get_size()
uint32_t AP_RAMTRON::get_size (void) const inline
Definition at line 16 of file AP_RAMTRON.h.
Referenced by read(), and write().
init()
bool AP_RAMTRON::init (void)
Definition at line 49 of file AP_RAMTRON.cpp.
read()
bool AP_RAMTRON::read (uint32_t offset, uint8_t *const buf, uint32_t size)
Definition at line 133 of file AP_RAMTRON.cpp.
Referenced by read().
send_offset()
void AP_RAMTRON::send_offset (uint8_t cmd, uint32_t offset) const private
Definition at line 121 of file AP_RAMTRON.cpp.
Referenced by read(), and write().
write()
bool AP_RAMTRON::write (uint32_t offset, uint8_t const *const buf, uint32_t size)
Definition at line 190 of file AP_RAMTRON.cpp.
Member Data Documentation
dev
AP_HAL::OwnPtr<AP_HAL::SPIDevice> AP_RAMTRON::dev private
Definition at line 26 of file AP_RAMTRON.h.
Referenced by init(), read(), send_offset(), and write().
id
uint8_t AP_RAMTRON::id = UINT8_MAX private
Definition at line 42 of file AP_RAMTRON.h.
Referenced by get_size().
ramtron_ids
const AP_RAMTRON::ramtron_id AP_RAMTRON::ramtron_ids static private
Initial value:
= {
    { 0x21, 0x00,  16, 2, RDID_type::Cypress },
    { 0x21, 0x08,  16, 2, RDID_type::Cypress },
    { 0x22, 0x00,  32, 2, RDID_type::Cypress },
    { 0x22, 0x08,  32, 2, RDID_type::Cypress },
    { 0x22, 0x48,  32, 2, RDID_type::Cypress },
    { 0x22, 0x01,  32, 2, RDID_type::Cypress },
    { 0x23, 0x00,  64, 2, RDID_type::Cypress },
    { 0x23, 0x01,  64, 2, RDID_type::Cypress },
    { 0x24, 0x00, 128, 3, RDID_type::Cypress },
    { 0x24, 0x01, 128, 3, RDID_type::Cypress },
    { 0x25, 0x08, 256, 3, RDID_type::Cypress },
    { 0x26, 0x08, 512, 3, RDID_type::Cypress },
    { 0x27, 0x03, 128, 3, RDID_type::Fujitsu },
    { 0x05, 0x09,  32, 2, RDID_type::Fujitsu },
    { 0x24, 0x03,  16, 2, RDID_type::Fujitsu },
    { 0x25, 0x03,  32, 2, RDID_type::Fujitsu },
    { 0x22, 0x00,  16, 2, RDID_type::Petabytes },
    { 0x24, 0x00, 256, 3, RDID_type::Petabytes },
}
Definition at line 25 of file AP_RAMTRON.h.
Referenced by get_size(), init(), and send_offset().
The documentation for this class was generated from the following files:
libraries/AP_RAMTRON/AP_RAMTRON.h
libraries/AP_RAMTRON/AP_RAMTRON.cpp