APM:Libraries: LoggerMessageWriter Class Reference
LoggerMessageWriter Class Reference abstract
#include <LoggerMessageWriter.h>
Public Member Functions
virtual void reset ()=0
virtual void process ()=0
virtual bool finished ()
virtual void set_logger_backend (class AP_Logger_Backend *backend)
bool out_of_time_for_writing_messages () const
Protected Attributes
bool _finished = false
AP_Logger_Backend * _logger_backend = nullptr
Detailed Description
Definition at line 6 of file LoggerMessageWriter.h.
Member Function Documentation
finished()
virtual bool LoggerMessageWriter::finished () inline virtual
Definition at line 11 of file LoggerMessageWriter.h.
Referenced by AP_Logger_Backend::allow_start_ekf(), LoggerMessageWriter_DFLogStart::process(), AP_Logger_Backend::ShouldLog(), AP_Logger_Backend::WriteBlockCheckStartupMessages(), and AP_Logger_Backend::WriteMoreStartupMessages().
out_of_time_for_writing_messages()
bool LoggerMessageWriter::out_of_time_for_writing_messages () const
Definition at line 39 of file LoggerMessageWriter.cpp.
Referenced by LoggerMessageWriter_DFLogStart::out_of_time_for_writing_messages_df(), and LoggerMessageWriter_WriteEntireMission::process().
process()
virtual void LoggerMessageWriter::process () pure virtual
Implemented in LoggerMessageWriter_WriteSysInfo, LoggerMessageWriter_WriteEntireMission, LoggerMessageWriter_WriteAllRallyPoints, and LoggerMessageWriter_DFLogStart.
reset()
void LoggerMessageWriter::reset () pure virtual
Implemented in LoggerMessageWriter_WriteSysInfo, LoggerMessageWriter_WriteEntireMission, LoggerMessageWriter_WriteAllRallyPoints, and LoggerMessageWriter_DFLogStart.
Definition at line 34 of file LoggerMessageWriter.cpp.
Referenced by LoggerMessageWriter_WriteSysInfo::reset(), LoggerMessageWriter_WriteEntireMission::reset(), and LoggerMessageWriter_DFLogStart::reset().
set_logger_backend()
virtual void LoggerMessageWriter::set_logger_backend (class AP_Logger_Backend * backend) inline virtual
Reimplemented in LoggerMessageWriter_DFLogStart.
Definition at line 13 of file LoggerMessageWriter.h.
Referenced by LoggerMessageWriter_DFLogStart::set_logger_backend().
Member Data Documentation
_finished
bool LoggerMessageWriter::_finished = false protected
Definition at line 20 of file LoggerMessageWriter.h.
Referenced by finished(), LoggerMessageWriter_WriteSysInfo::process(), LoggerMessageWriter_WriteEntireMission::process(), LoggerMessageWriter_DFLogStart::process(), and reset().
_logger_backend
AP_Logger_Backend* LoggerMessageWriter::_logger_backend = nullptr protected
Definition at line 21 of file LoggerMessageWriter.h.
Referenced by LoggerMessageWriter_WriteSysInfo::process(), LoggerMessageWriter_WriteEntireMission::process(), LoggerMessageWriter_DFLogStart::process(), and set_logger_backend().
The documentation for this class was generated from the following files:
libraries/AP_Logger/LoggerMessageWriter.h
libraries/AP_Logger/LoggerMessageWriter.cpp