APM:Libraries: AP_MSP_Telem_Backend Class Reference
AP_MSP_Telem_Backend Class Reference abstract
#include <AP_MSP_Telem_Backend.h>
Classes
struct airspeed_state_s
struct battery_state_s
struct gps_state_s
struct home_state_s
Public Types
typedef struct AP_MSP_Telem_Backend::battery_state_s battery_state_t
typedef struct PACKED AP_MSP_Telem_Backend::gps_state_s gps_state_t
typedef struct AP_MSP_Telem_Backend::airspeed_state_s airspeed_state_t
typedef struct AP_MSP_Telem_Backend::home_state_s home_state_t
Public Member Functions
AP_MSP_Telem_Backend (AP_HAL::UARTDriver *uart)
virtual bool init () override
virtual bool init_uart ()
virtual void enable_warnings ()
virtual void hide_osd_items (void)
void process_incoming_data ()
void process_outgoing_data ()
virtual void msp_displayport_heartbeat ()
virtual void msp_displayport_grab ()
virtual void msp_displayport_release ()
virtual void msp_displayport_clear_screen ()
virtual void msp_displayport_draw_screen ()
virtual void msp_displayport_write_string (uint8_t col, uint8_t row, bool blink, const char *string)
virtual void msp_displayport_set_options (const uint8_t font_index, const uint8_t screen_resolution)
Protected Types
enum msp_packet_type : uint8_t {
EMPTY_SLOT = 0 , NAME , STATUS , CONFIG ,
RAW_GPS , COMP_GPS , ATTITUDE , ALTITUDE ,
ANALOG , BATTERY_STATE , RTC_DATETIME
}
Protected Member Functions
bool is_packet_ready (uint8_t idx, bool queue_empty) override
void process_packet (uint8_t idx) override
void adjust_packet_weight (bool queue_empty) override
void setup_wfq_scheduler (void) override
bool get_next_msg_chunk (void) override
uint8_t calc_cell_count (float battery_voltage)
virtual float get_vspeed_ms (void) const
virtual bool get_rssi (float &rssi) const
virtual void update_home_pos (home_state_t &home_state)
virtual void update_battery_state (battery_state_t &_battery_state)
virtual void update_gps_state (gps_state_t &gps_state)
virtual void update_airspeed (airspeed_state_t &airspeed_state)
virtual void update_flight_mode_str (char *flight_mode_str, uint8_t size, bool wind_enabled)
void msp_process_received_command ()
MSP::MSPCommandResult msp_process_command (MSP::msp_packet_t *cmd, MSP::msp_packet_t *reply)
MSP::MSPCommandResult msp_process_sensor_command (uint16_t cmd_msp, MSP::sbuf_t *src)
MSP::MSPCommandResult msp_process_out_command (uint16_t cmd_msp, MSP::sbuf_t *dst)
void msp_send_packet (uint16_t cmd, MSP::msp_version_e msp_version, const void *p, uint16_t size, bool is_request)
void msp_handle_opflow (const MSP::msp_opflow_data_message_t &pkt)
void msp_handle_rangefinder (const MSP::msp_rangefinder_data_message_t &pkt)
void msp_handle_gps (const MSP::msp_gps_data_message_t &pkt)
void msp_handle_compass (const MSP::msp_compass_data_message_t &pkt)
void msp_handle_baro (const MSP::msp_baro_data_message_t &pkt)
void msp_handle_airspeed (const MSP::msp_airspeed_data_message_t &pkt)
virtual uint32_t get_osd_flight_mode_bitmask (void)
virtual bool is_scheduler_enabled () const =0
virtual bool use_msp_thread () const
virtual AP_SerialManager::SerialProtocol get_serial_protocol () const =0
virtual bool displaying_stats_screen () const
virtual MSP::MSPCommandResult msp_process_out_api_version (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_fc_version (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_fc_variant (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_uid (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_board_info (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_build_info (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_name (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_status (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_osd_config (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_raw_gps (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_comp_gps (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_attitude (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_altitude (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_analog (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_battery_state (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_esc_sensor_data (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_rtc (MSP::sbuf_t *dst)
virtual MSP::MSPCommandResult msp_process_out_rc (MSP::sbuf_t *dst)
Protected Attributes
const uint16_t msp_packet_type_map [MSP_TIME_SLOT_MAX]
uint64_t osd_hidden_items_bitmask
MSP::msp_port_t _msp_port
Static Protected Attributes
static constexpr uint8_t arrows [8] = {0x91, 0x97, 0x92, 0x98, 0x93, 0x99, 0x90, 0x96}
static const uint8_t message_scroll_time_ms = 200
static const uint8_t message_scroll_delay = 5
Private Attributes
friend AP_MSP
uint8_t _time_slots
struct {
uint32_t last_poll_timer
uint32_t avg_packet_counter
uint32_t packet_timer [TELEM_TIME_SLOT_MAX]
uint32_t packet_weight [TELEM_TIME_SLOT_MAX]
uint32_t packet_min_period [TELEM_TIME_SLOT_MAX]
uint16_t avg_packet_rate
uint16_t max_packet_rate
} _scheduler
struct {
HAL_Semaphore sem
ObjectBuffer< mavlink_statustext_t > queue {TELEM_PAYLOAD_STATUS_CAPACITY}
mavlink_statustext_t next
bool available
} _statustext
Additional Inherited Members
Private Member Functions inherited from AP_RCTelemetry
AP_RCTelemetry (uint8_t time_slots)
virtual ~AP_RCTelemetry ()
CLASS_NO_COPY (AP_RCTelemetry)
virtual void queue_message (MAV_SEVERITY severity, const char *text)
void enable_scheduler_entry (const uint8_t slot)
void disable_scheduler_entry (const uint8_t slot)
void set_scheduler_entry_min_period (const uint8_t slot, const uint32_t min_period_ms)
bool is_scheduler_entry_enabled (const uint8_t slot) const
virtual void reset_scheduler_entry_min_periods ()
uint32_t sensor_status_flags () const
uint16_t get_avg_packet_rate () const
uint16_t get_max_packet_rate () const
uint8_t run_wfq_scheduler (const bool use_shaper=true)
bool process_scheduler_entry (const uint8_t slot)
void set_scheduler_entry (uint8_t slot, uint32_t weight, uint32_t min_period_ms)
void add_scheduler_entry (uint32_t weight, uint32_t min_period_ms)
Detailed Description
Definition at line 38 of file AP_MSP_Telem_Backend.h.
Member Typedef Documentation
airspeed_state_t
typedef struct AP_MSP_Telem_Backend::airspeed_state_s AP_MSP_Telem_Backend::airspeed_state_t
battery_state_t
typedef struct AP_MSP_Telem_Backend::battery_state_s AP_MSP_Telem_Backend::battery_state_t
gps_state_t
typedef struct PACKED AP_MSP_Telem_Backend::gps_state_s AP_MSP_Telem_Backend::gps_state_t
home_state_t
typedef struct AP_MSP_Telem_Backend::home_state_s AP_MSP_Telem_Backend::home_state_t
Member Enumeration Documentation
msp_packet_type
enum AP_MSP_Telem_Backend::msp_packet_type : uint8_t protected
Enumerator
EMPTY_SLOT
NAME
STATUS
CONFIG
RAW_GPS
COMP_GPS
ATTITUDE
ALTITUDE
ANALOG
BATTERY_STATE
RTC_DATETIME
Definition at line 97 of file AP_MSP_Telem_Backend.h.
Constructor & Destructor Documentation
AP_MSP_Telem_Backend()
AP_MSP_Telem_Backend::AP_MSP_Telem_Backend (AP_HAL::UARTDriver * uart)
Definition at line 46 of file AP_MSP_Telem_Backend.cpp.
Member Function Documentation
adjust_packet_weight()
void AP_MSP_Telem_Backend::adjust_packet_weight (bool queue_empty) inline override protected virtual
Reimplemented from AP_RCTelemetry.
Definition at line 155 of file AP_MSP_Telem_Backend.h.
calc_cell_count()
uint8_t AP_MSP_Telem_Backend::calc_cell_count (float battery_voltage) protected
displaying_stats_screen()
bool AP_MSP_Telem_Backend::displaying_stats_screen () const protected virtual
Definition at line 1289 of file AP_MSP_Telem_Backend.cpp.
Referenced by AP_MSP_Telem_DJI::get_rssi(), hide_osd_items(), AP_MSP_Telem_DJI::msp_process_out_esc_sensor_data(), AP_MSP_Telem_DJI::update_airspeed(), AP_MSP_Telem_DJI::update_battery_state(), AP_MSP_Telem_DJI::update_flight_mode_str(), AP_MSP_Telem_DJI::update_gps_state(), and AP_MSP_Telem_DJI::update_home_pos().
enable_warnings()
void AP_MSP_Telem_Backend::enable_warnings () virtual
Definition at line 340 of file AP_MSP_Telem_Backend.cpp.
Referenced by init().
get_next_msg_chunk()
bool AP_MSP_Telem_Backend::get_next_msg_chunk (void) inline override protected virtual
Reimplemented from AP_RCTelemetry.
Definition at line 157 of file AP_MSP_Telem_Backend.h.
get_osd_flight_mode_bitmask()
uint32_t AP_MSP_Telem_Backend::get_osd_flight_mode_bitmask (void) protected virtual
Reimplemented in AP_MSP_Telem_DJI.
Definition at line 594 of file AP_MSP_Telem_Backend.cpp.
Referenced by AP_MSP_Telem_DJI::get_osd_flight_mode_bitmask(), and msp_process_out_status().
get_rssi()
bool AP_MSP_Telem_Backend::get_rssi (float & rssi) const protected virtual
Reimplemented in AP_MSP_Telem_DJI.
Definition at line 1306 of file AP_MSP_Telem_Backend.cpp.
Referenced by AP_MSP_Telem_DJI::get_rssi(), hide_osd_items(), and msp_process_out_analog().
get_serial_protocol()
virtual AP_SerialManager::SerialProtocol AP_MSP_Telem_Backend::get_serial_protocol () const protected pure virtual
Implemented in AP_MSP_Telem_DisplayPort, AP_MSP_Telem_DJI, and AP_MSP_Telem_Generic.
get_vspeed_ms()
float AP_MSP_Telem_Backend::get_vspeed_ms (void) const protected virtual
Definition at line 169 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_altitude().
hide_osd_items()
void AP_MSP_Telem_Backend::hide_osd_items (void) virtual
Reimplemented in AP_MSP_Telem_DJI.
Definition at line 1135 of file AP_MSP_Telem_Backend.cpp.
Referenced by AP_MSP_Telem_DJI::hide_osd_items(), and AP_MSP::loop().
init()
bool AP_MSP_Telem_Backend::init (void) override virtual
Reimplemented from AP_RCTelemetry.
Definition at line 81 of file AP_MSP_Telem_Backend.cpp.
Referenced by AP_MSP::init_backend().
init_uart()
bool AP_MSP_Telem_Backend::init_uart () virtual
Reimplemented in AP_MSP_Telem_DisplayPort, and AP_MSP_Telem_DJI.
Definition at line 87 of file AP_MSP_Telem_Backend.cpp.
Referenced by AP_MSP::loop().
is_packet_ready()
bool AP_MSP_Telem_Backend::is_packet_ready (uint8_t idx, bool queue_empty) override protected virtual
Reimplemented from AP_RCTelemetry.
Definition at line 107 of file AP_MSP_Telem_Backend.cpp.
is_scheduler_enabled()
virtual bool AP_MSP_Telem_Backend::is_scheduler_enabled () const protected pure virtual
Implemented in AP_MSP_Telem_DisplayPort, AP_MSP_Telem_DJI, and AP_MSP_Telem_Generic.
Referenced by process_outgoing_data().
msp_displayport_clear_screen()
void AP_MSP_Telem_Backend::msp_displayport_clear_screen () virtual
Definition at line 1247 of file AP_MSP_Telem_Backend.cpp.
msp_displayport_draw_screen()
void AP_MSP_Telem_Backend::msp_displayport_draw_screen () virtual
Definition at line 1254 of file AP_MSP_Telem_Backend.cpp.
msp_displayport_grab()
void AP_MSP_Telem_Backend::msp_displayport_grab () virtual
Definition at line 1235 of file AP_MSP_Telem_Backend.cpp.
msp_displayport_heartbeat()
void AP_MSP_Telem_Backend::msp_displayport_heartbeat () virtual
Definition at line 1225 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_displayport_grab().
msp_displayport_release()
void AP_MSP_Telem_Backend::msp_displayport_release () virtual
Definition at line 1240 of file AP_MSP_Telem_Backend.cpp.
msp_displayport_set_options()
void AP_MSP_Telem_Backend::msp_displayport_set_options (const uint8_t font_index, const uint8_t screen_resolution) virtual
Definition at line 1283 of file AP_MSP_Telem_Backend.cpp.
msp_displayport_write_string()
void AP_MSP_Telem_Backend::msp_displayport_write_string (uint8_t col, uint8_t row, bool blink, const char * string) virtual
Definition at line 1260 of file AP_MSP_Telem_Backend.cpp.
msp_handle_airspeed()
void AP_MSP_Telem_Backend::msp_handle_airspeed (const MSP::msp_airspeed_data_message_t & pkt) protected
Definition at line 584 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_sensor_command().
msp_handle_baro()
void AP_MSP_Telem_Backend::msp_handle_baro (const MSP::msp_baro_data_message_t & pkt) protected
Definition at line 577 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_sensor_command().
msp_handle_compass()
void AP_MSP_Telem_Backend::msp_handle_compass (const MSP::msp_compass_data_message_t & pkt) protected
Definition at line 570 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_sensor_command().
msp_handle_gps()
void AP_MSP_Telem_Backend::msp_handle_gps (const MSP::msp_gps_data_message_t & pkt) protected
Definition at line 563 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_sensor_command().
msp_handle_opflow()
void AP_MSP_Telem_Backend::msp_handle_opflow (const MSP::msp_opflow_data_message_t & pkt) protected
Definition at line 541 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_sensor_command().
msp_handle_rangefinder()
void AP_MSP_Telem_Backend::msp_handle_rangefinder (const MSP::msp_rangefinder_data_message_t & pkt) protected
Definition at line 552 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_sensor_command().
msp_process_command()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_command (MSP::msp_packet_t * cmd, MSP::msp_packet_t * reply) protected
Definition at line 427 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_received_command().
msp_process_out_altitude()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_altitude (MSP::sbuf_t * dst) protected virtual
Definition at line 905 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_analog()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_analog (MSP::sbuf_t * dst) protected virtual
Definition at line 922 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_api_version()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_api_version (MSP::sbuf_t * dst) protected virtual
Definition at line 604 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_attitude()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_attitude (MSP::sbuf_t * dst) protected virtual
Definition at line 886 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_battery_state()
virtual MSP::MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_battery_state (MSP::sbuf_t * dst) protected virtual
Referenced by msp_process_out_command().
msp_process_out_board_info()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_board_info (MSP::sbuf_t * dst) protected virtual
Definition at line 1089 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_build_info()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_build_info (MSP::sbuf_t * dst) protected virtual
Definition at line 1113 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_command()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_command (uint16_t cmd_msp, MSP::sbuf_t * dst) protected
Definition at line 451 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_command(), and process_packet().
msp_process_out_comp_gps()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_comp_gps (MSP::sbuf_t * dst) protected virtual
Definition at line 675 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_esc_sensor_data()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_esc_sensor_data (MSP::sbuf_t * dst) protected virtual
Reimplemented in AP_MSP_Telem_DJI.
Definition at line 995 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_fc_variant()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_fc_variant (MSP::sbuf_t * dst) protected virtual
Reimplemented in AP_MSP_Telem_DisplayPort, and AP_MSP_Telem_DJI.
Definition at line 636 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_fc_version()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_fc_version (MSP::sbuf_t * dst) protected virtual
Definition at line 620 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_name()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_name (MSP::sbuf_t * dst) protected virtual
Definition at line 703 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_osd_config()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_osd_config (MSP::sbuf_t * dst) protected virtual
Definition at line 805 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_raw_gps()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_raw_gps (MSP::sbuf_t * dst) protected virtual
Definition at line 642 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_rc()
virtual MSP::MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_rc (MSP::sbuf_t * dst) protected virtual
Referenced by msp_process_out_command().
msp_process_out_rtc()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_rtc (MSP::sbuf_t * dst) protected virtual
Definition at line 1023 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_status()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_status (MSP::sbuf_t * dst) protected virtual
Definition at line 780 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_out_uid()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_out_uid (MSP::sbuf_t * dst) protected virtual
Definition at line 1126 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_command().
msp_process_received_command()
void AP_MSP_Telem_Backend::msp_process_received_command () protected
Definition at line 395 of file AP_MSP_Telem_Backend.cpp.
Referenced by process_incoming_data().
msp_process_sensor_command()
MSPCommandResult AP_MSP_Telem_Backend::msp_process_sensor_command (uint16_t cmd_msp, MSP::sbuf_t * src) protected
Definition at line 501 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_command().
msp_send_packet()
void AP_MSP_Telem_Backend::msp_send_packet (uint16_t cmd, MSP::msp_version_e msp_version, const void * p, uint16_t size, bool is_request) protected
Definition at line 376 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_displayport_clear_screen(), msp_displayport_draw_screen(), msp_displayport_heartbeat(), msp_displayport_release(), msp_displayport_set_options(), and msp_displayport_write_string().
process_incoming_data()
void AP_MSP_Telem_Backend::process_incoming_data ()
Definition at line 352 of file AP_MSP_Telem_Backend.cpp.
Referenced by AP_MSP::loop().
process_outgoing_data()
void AP_MSP_Telem_Backend::process_outgoing_data ()
Definition at line 97 of file AP_MSP_Telem_Backend.cpp.
Referenced by AP_MSP::loop().
process_packet()
void AP_MSP_Telem_Backend::process_packet (uint8_t idx) override protected virtual
Implements AP_RCTelemetry.
Definition at line 135 of file AP_MSP_Telem_Backend.cpp.
setup_wfq_scheduler()
void AP_MSP_Telem_Backend::setup_wfq_scheduler (void) override protected virtual
Implements AP_RCTelemetry.
Definition at line 54 of file AP_MSP_Telem_Backend.cpp.
update_airspeed()
void AP_MSP_Telem_Backend::update_airspeed (airspeed_state_t & airspeed_state) protected virtual
Reimplemented in AP_MSP_Telem_DJI.
Definition at line 255 of file AP_MSP_Telem_Backend.cpp.
Referenced by hide_osd_items(), msp_process_out_raw_gps(), and AP_MSP_Telem_DJI::update_airspeed().
update_battery_state()
virtual void AP_MSP_Telem_Backend::update_battery_state (battery_state_t & _battery_state) protected virtual
Reimplemented in AP_MSP_Telem_DJI.
Referenced by msp_process_out_analog(), and AP_MSP_Telem_DJI::update_battery_state().
update_flight_mode_str()
void AP_MSP_Telem_Backend::update_flight_mode_str (char * flight_mode_str, uint8_t size, bool wind_enabled) protected virtual
Reimplemented in AP_MSP_Telem_DJI.
Definition at line 269 of file AP_MSP_Telem_Backend.cpp.
Referenced by msp_process_out_name(), and AP_MSP_Telem_DJI::update_flight_mode_str().
update_gps_state()
virtual void AP_MSP_Telem_Backend::update_gps_state (gps_state_t & gps_state) protected virtual
Reimplemented in AP_MSP_Telem_DJI.
Referenced by hide_osd_items(), msp_process_out_raw_gps(), and AP_MSP_Telem_DJI::update_gps_state().
update_home_pos()
void AP_MSP_Telem_Backend::update_home_pos (home_state_t & home_state) protected virtual
Reimplemented in AP_MSP_Telem_DJI.
Definition at line 185 of file AP_MSP_Telem_Backend.cpp.
Referenced by hide_osd_items(), msp_process_out_altitude(), msp_process_out_comp_gps(), and AP_MSP_Telem_DJI::update_home_pos().
use_msp_thread()
virtual bool AP_MSP_Telem_Backend::use_msp_thread () const inline protected virtual
Reimplemented in AP_MSP_Telem_DisplayPort.
Definition at line 195 of file AP_MSP_Telem_Backend.h.
Referenced by AP_MSP::init().
Member Data Documentation
_msp_port
MSP::msp_port_t AP_MSP_Telem_Backend::_msp_port protected
Definition at line 150 of file AP_MSP_Telem_Backend.h.
Referenced by AP_MSP_Telem_Backend(), init_uart(), AP_MSP_Telem_DisplayPort::init_uart(), AP_MSP_Telem_DJI::init_uart(), msp_process_received_command(), msp_send_packet(), process_incoming_data(), and process_packet().
AP_MSP
friend AP_MSP_Telem_Backend::AP_MSP private
Definition at line 40 of file AP_MSP_Telem_Backend.h.
arrows
constexpr uint8_t AP_MSP_Telem_Backend::arrows = {0x91, 0x97, 0x92, 0x98, 0x93, 0x99, 0x90, 0x96} static constexpr protected
Definition at line 141 of file AP_MSP_Telem_Backend.h.
Referenced by update_flight_mode_str().
message_scroll_delay
const uint8_t AP_MSP_Telem_Backend::message_scroll_delay = 5 static protected
Definition at line 144 of file AP_MSP_Telem_Backend.h.
Referenced by msp_process_out_name().
message_scroll_time_ms
const uint8_t AP_MSP_Telem_Backend::message_scroll_time_ms = 200 static protected
Definition at line 143 of file AP_MSP_Telem_Backend.h.
Referenced by msp_process_out_name().
msp_packet_type_map
const uint16_t AP_MSP_Telem_Backend::msp_packet_type_map[MSP_TIME_SLOT_MAX] protected
Initial value:
= {
        0,
        MSP_NAME,
        MSP_STATUS,
        MSP_OSD_CONFIG,
        MSP_RAW_GPS,
        MSP_COMP_GPS,
        MSP_ATTITUDE,
        MSP_ALTITUDE,
        MSP_ANALOG,
        MSP_BATTERY_STATE,
        MSP_RTC
    }
Definition at line 114 of file AP_MSP_Telem_Backend.h.
Referenced by process_packet().
osd_hidden_items_bitmask
uint64_t AP_MSP_Telem_Backend::osd_hidden_items_bitmask protected
Definition at line 147 of file AP_MSP_Telem_Backend.h.
Referenced by hide_osd_items(), AP_MSP_Telem_DJI::hide_osd_items(), and msp_process_out_osd_config().
The documentation for this class was generated from the following files:
libraries/AP_MSP/AP_MSP_Telem_Backend.h
libraries/AP_MSP/AP_MSP_Telem_Backend.cpp