APM:Libraries: SITL::SerialRangeFinder Class Reference
SITL::SerialRangeFinder Class Reference abstract
#include <SIM_SerialRangeFinder.h>
Public Member Functions
SerialRangeFinder ()
virtual void update (float range)
virtual uint32_t packet_for_alt (uint16_t alt_cm, uint8_t *buffer, uint8_t buflen)=0
virtual uint16_t reading_interval_ms () const
virtual bool has_temperature () const
virtual uint32_t packet_for_temperature (float temperature, uint8_t *buffer, uint8_t buflen)
Public Member Functions inherited from SITL::SerialDevice
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Private Member Functions
void send_temperature ()
Private Attributes
uint32_t last_sent_ms
Additional Inherited Members
Protected Member Functions inherited from SITL::SerialDevice
bool init_sitl_pointer () WARN_IF_UNUSED
Protected Attributes inherited from SITL::SerialDevice
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Detailed Description
Definition at line 29 of file SIM_SerialRangeFinder.h.
Constructor & Destructor Documentation
SerialRangeFinder()
SITL::SerialRangeFinder::SerialRangeFinder () inline
Definition at line 32 of file SIM_SerialRangeFinder.h.
Member Function Documentation
has_temperature()
virtual bool SITL::SerialRangeFinder::has_temperature () const inline virtual
Reimplemented in SITL::RF_NMEA.
Definition at line 42 of file SIM_SerialRangeFinder.h.
Referenced by update().
packet_for_alt()
virtual uint32_t SITL::SerialRangeFinder::packet_for_alt (uint16_t alt_cm, uint8_t * buffer, uint8_t buflen) pure virtual
Implemented in SITL::RF_Benewake, SITL::RF_BLping, SITL::RF_GYUS42v2, SITL::RF_JRE, SITL::RF_Lanbao, SITL::RF_LeddarOne, SITL::RF_LightWareSerial, SITL::RF_LightWareSerialBinary, SITL::RF_MAVLink, SITL::RF_MaxsonarSerialLV, SITL::RF_NMEA, SITL::RF_Nooploop, SITL::RF_RDS02UF, SITL::RF_TeraRanger_Serial, SITL::RF_USD1_v0, SITL::RF_USD1_v1, and SITL::RF_Wasp.
Referenced by update().
packet_for_temperature()
virtual uint32_t SITL::SerialRangeFinder::packet_for_temperature (float temperature, uint8_t * buffer, uint8_t buflen) inline virtual
Reimplemented in SITL::RF_NMEA.
Definition at line 43 of file SIM_SerialRangeFinder.h.
Referenced by send_temperature().
reading_interval_ms()
virtual uint16_t SITL::SerialRangeFinder::reading_interval_ms () const inline virtual
Reimplemented in SITL::RF_GYUS42v2, and SITL::RF_Wasp.
Definition at line 39 of file SIM_SerialRangeFinder.h.
Referenced by update().
send_temperature()
void SerialRangeFinder::send_temperature () private
Definition at line 46 of file SIM_SerialRangeFinder.cpp.
Referenced by update().
update()
void SerialRangeFinder::update (float range) virtual
Reimplemented in SITL::RF_LightWareSerial, and SITL::RF_Wasp.
Definition at line 23 of file SIM_SerialRangeFinder.cpp.
Referenced by HALSITL::SITL_State_Common::sim_update(), SITL::RF_LightWareSerial::update(), and SITL::RF_Wasp::update().
Member Data Documentation
last_sent_ms
uint32_t SITL::SerialRangeFinder::last_sent_ms private
Definition at line 48 of file SIM_SerialRangeFinder.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_SerialRangeFinder.h
libraries/SITL/SIM_SerialRangeFinder.cpp