APM:Libraries: AP_Vehicle Class Reference
AP_Vehicle Class Reference abstract
#include <AP_Vehicle.h>
Public Member Functions
AP_Vehicle ()
CLASS_NO_COPY (AP_Vehicle)
void setup (void) override final
void loop () override final
virtual bool set_mode (const uint8_t new_mode, const ModeReason reason)=0
virtual uint8_t get_mode () const =0
ModeReason get_control_mode_reason () const
virtual bool current_mode_requires_mission () const
void notify_no_such_mode (uint8_t mode_number)
void get_common_scheduler_tasks (const AP_Scheduler::Task *&tasks, uint8_t &num_tasks)
void set_likely_flying (bool b)
bool get_likely_flying (void) const
uint32_t get_time_flying_ms (void) const
virtual bool is_crashed () const
virtual bool is_landing () const
virtual bool is_taking_off () const
virtual bool should_zero_rc_outputs_on_reboot () const
void reboot (bool hold_in_bootloader)
virtual bool get_wp_distance_m (float &distance) const
virtual bool get_wp_bearing_deg (float &bearing) const
virtual bool get_wp_crosstrack_error_m (float &xtrack_error) const
virtual bool get_pan_tilt_norm (float &pan_norm, float &tilt_norm) const
virtual void get_osd_roll_pitch_rad (float &roll, float &pitch) const
virtual bool get_rate_ef_targets (Vector3f &rate_ef_targets) const
Static Public Member Functions
static AP_Vehicle * get_singleton ()
Protected Member Functions
virtual void init_ardupilot ()=0
virtual void load_parameters ()=0
void load_parameters (AP_Int16 &format_version, const uint16_t expected_format_version)
virtual void set_control_channels ()
void update_arming ()
void check_motor_noise ()
bool block_GCS_mode_change (uint8_t mode_num, const uint8_t *mode_list, uint8_t mode_list_length) const
Protected Attributes
AP_BoardConfig BoardConfig
AP_Scheduler scheduler
float G_Dt
AP_Baro barometer
RangeFinder rangefinder
AP_Notify notify
ModeReason control_mode_reason = ModeReason::UNKNOWN
Static Protected Attributes
static const struct AP_Param::GroupInfo var_info []
static const struct AP_Scheduler::Task scheduler_tasks []
Private Member Functions
void send_watchdog_reset_statustext ()
void one_Hz_update ()
Static Private Member Functions
static void scheduler_delay_callback ()
Private Attributes
uint8_t one_Hz_counter
bool likely_flying
uint32_t _last_flying_ms
uint32_t _last_notch_update_ms [HAL_INS_NUM_HARMONIC_NOTCH_FILTERS]
bool done_safety_init
uint32_t _last_internal_errors
AP_Int32 flight_mode_GCS_block
Static Private Attributes
static AP_Vehicle * _singleton = nullptr
Detailed Description
Definition at line 85 of file AP_Vehicle.h.
Constructor & Destructor Documentation
AP_Vehicle()
AP_Vehicle::AP_Vehicle () inline
Definition at line 89 of file AP_Vehicle.h.
Member Function Documentation
block_GCS_mode_change()
bool AP_Vehicle::block_GCS_mode_change (uint8_t mode_num, const uint8_t * mode_list, uint8_t mode_list_length) const protected
check_motor_noise()
void AP_Vehicle::check_motor_noise () protected
Definition at line 1050 of file AP_Vehicle.cpp.
CLASS_NO_COPY()
AP_Vehicle::CLASS_NO_COPY (AP_Vehicle)
current_mode_requires_mission()
virtual bool AP_Vehicle::current_mode_requires_mission () const inline virtual
Definition at line 122 of file AP_Vehicle.h.
Referenced by GCS_MAVLINK::send_mission_current().
get_common_scheduler_tasks()
void AP_Vehicle::get_common_scheduler_tasks (const AP_Scheduler::Task *& tasks, uint8_t & num_tasks)
Definition at line 653 of file AP_Vehicle.cpp.
Referenced by AP_Scheduler::init().
get_control_mode_reason()
ModeReason AP_Vehicle::get_control_mode_reason () const inline
Definition at line 118 of file AP_Vehicle.h.
get_likely_flying()
bool AP_Vehicle::get_likely_flying (void) const inline
Definition at line 154 of file AP_Vehicle.h.
get_mode()
virtual uint8_t AP_Vehicle::get_mode () const pure virtual
Implemented in DummyVehicle, and DummyVehicle.
get_osd_roll_pitch_rad()
void AP_Vehicle::get_osd_roll_pitch_rad (float & roll, float & pitch) const virtual
Definition at line 961 of file AP_Vehicle.cpp.
Referenced by AP_Frsky_SPort_Passthrough::calc_attiandrng(), and AP_OSD_Screen::draw_horizon().
get_pan_tilt_norm()
virtual bool AP_Vehicle::get_pan_tilt_norm (float & pan_norm, float & tilt_norm) const inline virtual
Definition at line 282 of file AP_Vehicle.h.
get_rate_ef_targets()
virtual bool AP_Vehicle::get_rate_ef_targets (Vector3f & rate_ef_targets) const inline virtual
Definition at line 290 of file AP_Vehicle.h.
Referenced by GCS_MAVLINK::send_autopilot_state_for_gimbal_device().
get_singleton()
AP_Vehicle * AP_Vehicle::get_singleton () static
Definition at line 1112 of file AP_Vehicle.cpp.
Referenced by AP::vehicle().
get_time_flying_ms()
uint32_t AP_Vehicle::get_time_flying_ms (void) const inline
Definition at line 162 of file AP_Vehicle.h.
Referenced by AP_DAL::start_frame().
get_wp_bearing_deg()
virtual bool AP_Vehicle::get_wp_bearing_deg (float & bearing) const inline virtual
Definition at line 267 of file AP_Vehicle.h.
Referenced by AP_Frsky_SPort_Passthrough::calc_waypoint().
get_wp_crosstrack_error_m()
virtual bool AP_Vehicle::get_wp_crosstrack_error_m (float & xtrack_error) const inline virtual
Definition at line 273 of file AP_Vehicle.h.
get_wp_distance_m()
virtual bool AP_Vehicle::get_wp_distance_m (float & distance) const inline virtual
Definition at line 261 of file AP_Vehicle.h.
Referenced by AP_Frsky_SPort_Passthrough::calc_waypoint().
init_ardupilot()
virtual void AP_Vehicle::init_ardupilot () protected pure virtual
Implemented in DummyVehicle, and DummyVehicle.
Referenced by setup().
is_crashed()
bool AP_Vehicle::is_crashed () const virtual
Definition at line 735 of file AP_Vehicle.cpp.
is_landing()
virtual bool AP_Vehicle::is_landing () const inline virtual
Definition at line 245 of file AP_Vehicle.h.
is_taking_off()
virtual bool AP_Vehicle::is_taking_off () const inline virtual
Definition at line 248 of file AP_Vehicle.h.
load_parameters() [1/2]
virtual void AP_Vehicle::load_parameters () protected pure virtual
Implemented in DummyVehicle, and DummyVehicle.
Referenced by setup().
load_parameters() [2/2]
void AP_Vehicle::load_parameters (AP_Int16 & format_version, const uint16_t expected_format_version) protected
Definition at line 8 of file Parameters.cpp.
loop()
void AP_Vehicle::loop (void) final override virtual
Implements AP_HAL::HAL::Callbacks.
Definition at line 520 of file AP_Vehicle.cpp.
notify_no_such_mode()
void AP_Vehicle::notify_no_such_mode (uint8_t mode_number)
Definition at line 888 of file AP_Vehicle.cpp.
one_Hz_update()
void AP_Vehicle::one_Hz_update (void) private
Definition at line 1018 of file AP_Vehicle.cpp.
reboot()
void AP_Vehicle::reboot (bool hold_in_bootloader)
Definition at line 896 of file AP_Vehicle.cpp.
Referenced by AP_Frsky_MAVliteMsgHandler::handle_command_preflight_reboot(), and GCS_MAVLINK::handle_preflight_reboot().
scheduler_delay_callback()
void AP_Vehicle::scheduler_delay_callback () static private
Definition at line 665 of file AP_Vehicle.cpp.
Referenced by setup().
send_watchdog_reset_statustext()
void AP_Vehicle::send_watchdog_reset_statustext () private
Definition at line 710 of file AP_Vehicle.cpp.
Referenced by setup().
set_control_channels()
virtual void AP_Vehicle::set_control_channels () inline protected virtual
Definition at line 298 of file AP_Vehicle.h.
Referenced by setup().
set_likely_flying()
void AP_Vehicle::set_likely_flying (bool b) inline
Definition at line 142 of file AP_Vehicle.h.
set_mode()
virtual bool AP_Vehicle::set_mode (const uint8_t new_mode, const ModeReason reason) pure virtual
Implemented in DummyVehicle, and DummyVehicle.
setup()
void AP_Vehicle::setup (void) final override virtual
Implements AP_HAL::HAL::Callbacks.
Definition at line 300 of file AP_Vehicle.cpp.
should_zero_rc_outputs_on_reboot()
virtual bool AP_Vehicle::should_zero_rc_outputs_on_reboot () const inline virtual
Definition at line 251 of file AP_Vehicle.h.
Referenced by reboot().
update_arming()
void AP_Vehicle::update_arming () protected
Member Data Documentation
_last_flying_ms
uint32_t AP_Vehicle::_last_flying_ms private
Definition at line 516 of file AP_Vehicle.h.
Referenced by get_time_flying_ms(), and set_likely_flying().
_last_internal_errors
uint32_t AP_Vehicle::_last_internal_errors private
Definition at line 529 of file AP_Vehicle.h.
Referenced by loop().
_last_notch_update_ms
uint32_t AP_Vehicle::_last_notch_update_ms[HAL_INS_NUM_HARMONIC_NOTCH_FILTERS] private
Definition at line 517 of file AP_Vehicle.h.
_singleton
AP_Vehicle * AP_Vehicle::_singleton = nullptr static private
Definition at line 519 of file AP_Vehicle.h.
Referenced by AP_Vehicle(), get_singleton(), and scheduler_delay_callback().
barometer
AP_Baro AP_Vehicle::barometer protected
Definition at line 319 of file AP_Vehicle.h.
BoardConfig
AP_BoardConfig AP_Vehicle::BoardConfig protected
Definition at line 301 of file AP_Vehicle.h.
Referenced by DummyVehicle::init(), loop(), and setup().
control_mode_reason
ModeReason AP_Vehicle::control_mode_reason = ModeReason::UNKNOWN protected
Definition at line 476 of file AP_Vehicle.h.
Referenced by get_control_mode_reason().
done_safety_init
bool AP_Vehicle::done_safety_init private
Definition at line 526 of file AP_Vehicle.h.
Referenced by loop().
flight_mode_GCS_block
AP_Int32 AP_Vehicle::flight_mode_GCS_block private
Definition at line 540 of file AP_Vehicle.h.
G_Dt
float AP_Vehicle::G_Dt protected
Definition at line 313 of file AP_Vehicle.h.
Referenced by loop(), and setup().
likely_flying
bool AP_Vehicle::likely_flying private
Definition at line 515 of file AP_Vehicle.h.
Referenced by get_likely_flying(), get_time_flying_ms(), and set_likely_flying().
notify
AP_Notify AP_Vehicle::notify protected
Definition at line 372 of file AP_Vehicle.h.
Referenced by reboot(), and scheduler_delay_callback().
one_Hz_counter
uint8_t AP_Vehicle::one_Hz_counter private
Definition at line 512 of file AP_Vehicle.h.
Referenced by one_Hz_update().
rangefinder
RangeFinder AP_Vehicle::rangefinder protected
Definition at line 329 of file AP_Vehicle.h.
scheduler
AP_Scheduler AP_Vehicle::scheduler protected
Definition at line 309 of file AP_Vehicle.h.
Referenced by loop(), and setup().
scheduler_tasks
const AP_Scheduler::Task AP_Vehicle::scheduler_tasks static protected
Definition at line 576 of file AP_Vehicle.h.
Referenced by get_common_scheduler_tasks().
var_info
const AP_Param::GroupInfo AP_Vehicle::var_info static protected
Definition at line 36 of file AP_Vehicle.h.
The documentation for this class was generated from the following files:
libraries/AP_Vehicle/AP_Vehicle.h
libraries/AP_Vehicle/AP_Vehicle.cpp
libraries/AP_Vehicle/Parameters.cpp