APM:Libraries: AP_OADijkstra Class Reference
AP_OADijkstra Class Reference
#include <AP_OADijkstra.h>
Classes
struct ShortPathNode
Public Types
enum AP_OADijkstra_State : uint8_t { DIJKSTRA_STATE_NOT_REQUIRED = 0 , DIJKSTRA_STATE_ERROR , DIJKSTRA_STATE_SUCCESS }
Public Member Functions
AP_OADijkstra (AP_Int16 &options)
CLASS_NO_COPY (AP_OADijkstra)
void set_fence_margin (float margin)
void recalculate_path ()
AP_OADijkstra_State update (const Location &current_loc, const Location &destination, const Location &next_destination, Location &origin_new, Location &destination_new, Location &next_destination_new, bool &dest_to_next_dest_clear)
Private Types
enum class AP_OADijkstra_Error : uint8_t {
DIJKSTRA_ERROR_NONE = 0 , DIJKSTRA_ERROR_OUT_OF_MEMORY , DIJKSTRA_ERROR_OVERLAPPING_POLYGON_POINTS , DIJKSTRA_ERROR_FAILED_TO_BUILD_INNER_POLYGON ,
DIJKSTRA_ERROR_OVERLAPPING_POLYGON_LINES , DIJKSTRA_ERROR_FENCE_DISABLED , DIJKSTRA_ERROR_TOO_MANY_FENCE_POINTS , DIJKSTRA_ERROR_NO_POSITION_ESTIMATE ,
DIJKSTRA_ERROR_COULD_NOT_FIND_PATH
}
typedef uint8_t node_index
Private Member Functions
bool some_fences_enabled () const
const char * get_error_msg (AP_OADijkstra_Error error_id) const
void report_error (AP_OADijkstra_Error error_id)
bool check_inclusion_polygon_updated () const
bool create_inclusion_polygon_with_margin (float margin_cm, AP_OADijkstra_Error &err_id)
bool check_exclusion_polygon_updated () const
bool create_exclusion_polygon_with_margin (float margin_cm, AP_OADijkstra_Error &err_id)
bool check_exclusion_circle_updated () const
bool create_exclusion_circle_with_margin (float margin_cm, AP_OADijkstra_Error &err_id)
uint16_t total_numpoints () const
bool get_point (uint16_t index, Vector2f &point) const
bool intersects_fence (const Vector2f &seg_start, const Vector2f &seg_end) const
bool create_fence_visgraph (AP_OADijkstra_Error &err_id)
bool calc_shortest_path (const Location &origin, const Location &destination, AP_OADijkstra_Error &err_id)
bool update_visgraph (AP_OAVisGraph &visgraph, const AP_OAVisGraph::OAItemID &oaid, const Vector2f &position, bool add_extra_position=false, Vector2f extra_position=Vector2f(0, 0))
void update_visible_node_distances (node_index curr_node_idx)
bool find_node_from_id (const AP_OAVisGraph::OAItemID &id, node_index &node_idx) const
bool find_closest_node_idx (node_index &node_idx) const
uint8_t get_shortest_path_numpoints () const
bool get_shortest_path_point (uint8_t point_num, Vector2f &pos) const
bool convert_node_to_point (const AP_OAVisGraph::OAItemID &id, Vector2f &pos) const
void Write_OADijkstra (const uint8_t state, const uint8_t error_id, const uint8_t curr_point, const uint8_t tot_points, const Location &final_dest, const Location &oa_dest) const
void Write_Visgraph_point (const uint8_t version, const uint8_t point_num, const int32_t Lat, const int32_t Lon) const
Private Attributes
enum AP_OADijkstra::AP_OADijkstra_Error _error_id
bool _inclusion_polygon_with_margin_ok
bool _exclusion_polygon_with_margin_ok
bool _exclusion_circle_with_margin_ok
bool _polyfence_visgraph_ok
bool _shortest_path_ok
Location _destination_prev
Location _next_destination_prev
uint8_t _path_idx_returned
bool _dest_to_next_dest_clear
float _polyfence_margin = 10
AP_ExpandingArray< Vector2f > _inclusion_polygon_pts
uint8_t _inclusion_polygon_numpoints
uint32_t _inclusion_polygon_update_ms
AP_ExpandingArray< Vector2f > _exclusion_polygon_pts
uint8_t _exclusion_polygon_numpoints
uint32_t _exclusion_polygon_update_ms
AP_ExpandingArray< Vector2f > _exclusion_circle_pts
uint8_t _exclusion_circle_numpoints
uint32_t _exclusion_circle_update_ms
AP_OAVisGraph _fence_visgraph
AP_OAVisGraph _source_visgraph
AP_OAVisGraph _destination_visgraph
AP_ExpandingArray< ShortPathNode > _short_path_data
node_index _short_path_data_numpoints
AP_ExpandingArray< AP_OAVisGraph::OAItemID > _path
uint8_t _path_numpoints
Vector2f _path_source
Vector2f _path_destination
AP_OADijkstra_Error _error_last_id
uint32_t _error_last_report_ms
uint8_t _log_num_points
uint8_t _log_visgraph_version
AP_Int16 & _options
Detailed Description
Definition at line 13 of file AP_OADijkstra.h.
Member Typedef Documentation
node_index
typedef uint8_t AP_OADijkstra::node_index private
Definition at line 167 of file AP_OADijkstra.h.
Member Enumeration Documentation
AP_OADijkstra_Error
enum class AP_OADijkstra::AP_OADijkstra_Error : uint8_t strong private
Enumerator
DIJKSTRA_ERROR_NONE
DIJKSTRA_ERROR_OUT_OF_MEMORY
DIJKSTRA_ERROR_OVERLAPPING_POLYGON_POINTS
DIJKSTRA_ERROR_FAILED_TO_BUILD_INNER_POLYGON
DIJKSTRA_ERROR_OVERLAPPING_POLYGON_LINES
DIJKSTRA_ERROR_FENCE_DISABLED
DIJKSTRA_ERROR_TOO_MANY_FENCE_POINTS
DIJKSTRA_ERROR_NO_POSITION_ESTIMATE
DIJKSTRA_ERROR_COULD_NOT_FIND_PATH
Definition at line 50 of file AP_OADijkstra.h.
AP_OADijkstra_State
enum AP_OADijkstra::AP_OADijkstra_State : uint8_t
Enumerator
DIJKSTRA_STATE_NOT_REQUIRED
DIJKSTRA_STATE_ERROR
DIJKSTRA_STATE_SUCCESS
Definition at line 27 of file AP_OADijkstra.h.
Constructor & Destructor Documentation
AP_OADijkstra()
AP_OADijkstra::AP_OADijkstra (AP_Int16 & options)
Member Function Documentation
calc_shortest_path()
bool AP_OADijkstra::calc_shortest_path (const Location & origin, const Location & destination, AP_OADijkstra_Error & err_id) private
check_exclusion_circle_updated()
bool AP_OADijkstra::check_exclusion_circle_updated () const private
check_exclusion_polygon_updated()
bool AP_OADijkstra::check_exclusion_polygon_updated () const private
check_inclusion_polygon_updated()
bool AP_OADijkstra::check_inclusion_polygon_updated () const private
CLASS_NO_COPY()
AP_OADijkstra::CLASS_NO_COPY (AP_OADijkstra)
convert_node_to_point()
bool AP_OADijkstra::convert_node_to_point (const AP_OAVisGraph::OAItemID & id, Vector2f & pos) const private
create_exclusion_circle_with_margin()
bool AP_OADijkstra::create_exclusion_circle_with_margin (float margin_cm, AP_OADijkstra_Error & err_id) private
create_exclusion_polygon_with_margin()
bool AP_OADijkstra::create_exclusion_polygon_with_margin (float margin_cm, AP_OADijkstra_Error & err_id) private
create_fence_visgraph()
bool AP_OADijkstra::create_fence_visgraph (AP_OADijkstra_Error & err_id) private
create_inclusion_polygon_with_margin()
bool AP_OADijkstra::create_inclusion_polygon_with_margin (float margin_cm, AP_OADijkstra_Error & err_id) private
find_closest_node_idx()
bool AP_OADijkstra::find_closest_node_idx (node_index & node_idx) const private
find_node_from_id()
bool AP_OADijkstra::find_node_from_id (const AP_OAVisGraph::OAItemID & id, node_index & node_idx) const private
get_error_msg()
const char * AP_OADijkstra::get_error_msg (AP_OADijkstra_Error error_id) const private
get_point()
bool AP_OADijkstra::get_point (uint16_t index, Vector2f & point) const private
get_shortest_path_numpoints()
uint8_t AP_OADijkstra::get_shortest_path_numpoints () const inline private
Definition at line 196 of file AP_OADijkstra.h.
get_shortest_path_point()
bool AP_OADijkstra::get_shortest_path_point (uint8_t point_num, Vector2f & pos) const private
intersects_fence()
bool AP_OADijkstra::intersects_fence (const Vector2f & seg_start, const Vector2f & seg_end) const private
recalculate_path()
void AP_OADijkstra::recalculate_path () inline
Definition at line 24 of file AP_OADijkstra.h.
Referenced by AP_OAPathPlanner::avoidance_thread().
report_error()
void AP_OADijkstra::report_error (AP_OADijkstra_Error error_id) private
set_fence_margin()
void AP_OADijkstra::set_fence_margin (float margin) inline
Definition at line 21 of file AP_OADijkstra.h.
Referenced by AP_OAPathPlanner::avoidance_thread().
some_fences_enabled()
bool AP_OADijkstra::some_fences_enabled () const private
total_numpoints()
uint16_t AP_OADijkstra::total_numpoints () const private
update()
AP_OADijkstra_State AP_OADijkstra::update (const Location & current_loc, const Location & destination, const Location & next_destination, Location & origin_new, Location & destination_new, Location & next_destination_new, bool & dest_to_next_dest_clear)
Referenced by AP_OAPathPlanner::avoidance_thread().
update_visgraph()
bool AP_OADijkstra::update_visgraph (AP_OAVisGraph & visgraph, const AP_OAVisGraph::OAItemID & oaid, const Vector2f & position, bool add_extra_position = false, Vector2f extra_position = Vector2f(0, 0)) private
update_visible_node_distances()
void AP_OADijkstra::update_visible_node_distances (node_index curr_node_idx) private
Write_OADijkstra()
void AP_OADijkstra::Write_OADijkstra (const uint8_t state, const uint8_t error_id, const uint8_t curr_point, const uint8_t tot_points, const Location & final_dest, const Location & oa_dest) const inline private
Definition at line 213 of file AP_OADijkstra.h.
Write_Visgraph_point()
void AP_OADijkstra::Write_Visgraph_point (const uint8_t version, const uint8_t point_num, const int32_t Lat, const int32_t Lon) const inline private
Definition at line 214 of file AP_OADijkstra.h.
Member Data Documentation
_dest_to_next_dest_clear
bool AP_OADijkstra::_dest_to_next_dest_clear private
Definition at line 138 of file AP_OADijkstra.h.
_destination_prev
Location AP_OADijkstra::_destination_prev private
Definition at line 135 of file AP_OADijkstra.h.
_destination_visgraph
AP_OAVisGraph AP_OADijkstra::_destination_visgraph private
Definition at line 159 of file AP_OADijkstra.h.
_error_id
enum AP_OADijkstra::AP_OADijkstra_Error AP_OADijkstra::_error_id private
_error_last_id
AP_OADijkstra_Error AP_OADijkstra::_error_last_id private
Definition at line 205 of file AP_OADijkstra.h.
_error_last_report_ms
uint32_t AP_OADijkstra::_error_last_report_ms private
Definition at line 206 of file AP_OADijkstra.h.
_exclusion_circle_numpoints
uint8_t AP_OADijkstra::_exclusion_circle_numpoints private
Definition at line 153 of file AP_OADijkstra.h.
_exclusion_circle_pts
AP_ExpandingArray<Vector2f> AP_OADijkstra::_exclusion_circle_pts private
Definition at line 152 of file AP_OADijkstra.h.
_exclusion_circle_update_ms
uint32_t AP_OADijkstra::_exclusion_circle_update_ms private
Definition at line 154 of file AP_OADijkstra.h.
_exclusion_circle_with_margin_ok
bool AP_OADijkstra::_exclusion_circle_with_margin_ok private
Definition at line 131 of file AP_OADijkstra.h.
_exclusion_polygon_numpoints
uint8_t AP_OADijkstra::_exclusion_polygon_numpoints private
Definition at line 148 of file AP_OADijkstra.h.
_exclusion_polygon_pts
AP_ExpandingArray<Vector2f> AP_OADijkstra::_exclusion_polygon_pts private
Definition at line 147 of file AP_OADijkstra.h.
_exclusion_polygon_update_ms
uint32_t AP_OADijkstra::_exclusion_polygon_update_ms private
Definition at line 149 of file AP_OADijkstra.h.
_exclusion_polygon_with_margin_ok
bool AP_OADijkstra::_exclusion_polygon_with_margin_ok private
Definition at line 130 of file AP_OADijkstra.h.
_fence_visgraph
AP_OAVisGraph AP_OADijkstra::_fence_visgraph private
Definition at line 157 of file AP_OADijkstra.h.
_inclusion_polygon_numpoints
uint8_t AP_OADijkstra::_inclusion_polygon_numpoints private
Definition at line 143 of file AP_OADijkstra.h.
_inclusion_polygon_pts
AP_ExpandingArray<Vector2f> AP_OADijkstra::_inclusion_polygon_pts private
Definition at line 142 of file AP_OADijkstra.h.
_inclusion_polygon_update_ms
uint32_t AP_OADijkstra::_inclusion_polygon_update_ms private
Definition at line 144 of file AP_OADijkstra.h.
_inclusion_polygon_with_margin_ok
bool AP_OADijkstra::_inclusion_polygon_with_margin_ok private
Definition at line 129 of file AP_OADijkstra.h.
_log_num_points
uint8_t AP_OADijkstra::_log_num_points private
Definition at line 216 of file AP_OADijkstra.h.
_log_visgraph_version
uint8_t AP_OADijkstra::_log_visgraph_version private
Definition at line 217 of file AP_OADijkstra.h.
_next_destination_prev
Location AP_OADijkstra::_next_destination_prev private
Definition at line 136 of file AP_OADijkstra.h.
_options
AP_Int16& AP_OADijkstra::_options private
Definition at line 220 of file AP_OADijkstra.h.
_path
AP_ExpandingArray<AP_OAVisGraph::OAItemID> AP_OADijkstra::_path private
Definition at line 190 of file AP_OADijkstra.h.
_path_destination
Vector2f AP_OADijkstra::_path_destination private
Definition at line 193 of file AP_OADijkstra.h.
_path_idx_returned
uint8_t AP_OADijkstra::_path_idx_returned private
Definition at line 137 of file AP_OADijkstra.h.
_path_numpoints
uint8_t AP_OADijkstra::_path_numpoints private
Definition at line 191 of file AP_OADijkstra.h.
Referenced by get_shortest_path_numpoints().
_path_source
Vector2f AP_OADijkstra::_path_source private
Definition at line 192 of file AP_OADijkstra.h.
_polyfence_margin
float AP_OADijkstra::_polyfence_margin = 10 private
Definition at line 141 of file AP_OADijkstra.h.
Referenced by set_fence_margin().
_polyfence_visgraph_ok
bool AP_OADijkstra::_polyfence_visgraph_ok private
Definition at line 132 of file AP_OADijkstra.h.
_short_path_data
AP_ExpandingArray<ShortPathNode> AP_OADijkstra::_short_path_data private
Definition at line 174 of file AP_OADijkstra.h.
_short_path_data_numpoints
node_index AP_OADijkstra::_short_path_data_numpoints private
Definition at line 175 of file AP_OADijkstra.h.
_shortest_path_ok
bool AP_OADijkstra::_shortest_path_ok private
Definition at line 133 of file AP_OADijkstra.h.
Referenced by recalculate_path().
_source_visgraph
AP_OAVisGraph AP_OADijkstra::_source_visgraph private
Definition at line 158 of file AP_OADijkstra.h.
The documentation for this class was generated from the following file:
libraries/AC_Avoidance/AP_OADijkstra.h