APM:Libraries: AP_Baro_Backend Class Reference
AP_Baro_Backend Class Reference abstract
#include <AP_Baro_Backend.h>
Public Types
enum DevTypes {
DEVTYPE_BARO_SITL = 0x01 , DEVTYPE_BARO_BMP085 = 0x02 , DEVTYPE_BARO_BMP280 = 0x03 , DEVTYPE_BARO_BMP388 = 0x04 ,
DEVTYPE_BARO_DPS280 = 0x05 , DEVTYPE_BARO_DPS310 = 0x06 , DEVTYPE_BARO_FBM320 = 0x07 , DEVTYPE_BARO_ICM20789 = 0x08 ,
DEVTYPE_BARO_KELLERLD = 0x09 , DEVTYPE_BARO_LPS2XH = 0x0A , DEVTYPE_BARO_MS5611 = 0x0B , DEVTYPE_BARO_SPL06 = 0x0C ,
DEVTYPE_BARO_UAVCAN = 0x0D , DEVTYPE_BARO_MSP = 0x0E , DEVTYPE_BARO_ICP101XX = 0x0F , DEVTYPE_BARO_ICP201XX = 0x10 ,
DEVTYPE_BARO_MS5607 = 0x11 , DEVTYPE_BARO_MS5837 = 0x12 , DEVTYPE_BARO_MS5637 = 0x13 , DEVTYPE_BARO_BMP390 = 0x14
}
Public Member Functions
AP_Baro_Backend (AP_Baro &baro)
virtual ~AP_Baro_Backend (void)
virtual void update ()=0
virtual void accumulate (void)
void backend_update (uint8_t instance)
bool pressure_ok (float press)
uint32_t get_error_count () const
Protected Member Functions
void _copy_to_frontend (uint8_t instance, float pressure, float temperature)
virtual void update_healthy_flag (uint8_t instance)
void set_bus_id (uint8_t instance, uint32_t id)
Protected Attributes
AP_Baro & _frontend
HAL_Semaphore _sem
float _mean_pressure
uint32_t _error_count
Detailed Description
Definition at line 5 of file AP_Baro_Backend.h.
Member Enumeration Documentation
DevTypes
enum AP_Baro_Backend::DevTypes
Enumerator
DEVTYPE_BARO_SITL
DEVTYPE_BARO_BMP085
DEVTYPE_BARO_BMP280
DEVTYPE_BARO_BMP388
DEVTYPE_BARO_DPS280
DEVTYPE_BARO_DPS310
DEVTYPE_BARO_FBM320
DEVTYPE_BARO_ICM20789
DEVTYPE_BARO_KELLERLD
DEVTYPE_BARO_LPS2XH
DEVTYPE_BARO_MS5611
DEVTYPE_BARO_SPL06
DEVTYPE_BARO_UAVCAN
DEVTYPE_BARO_MSP
DEVTYPE_BARO_ICP101XX
DEVTYPE_BARO_ICP201XX
DEVTYPE_BARO_MS5607
DEVTYPE_BARO_MS5837
DEVTYPE_BARO_MS5637
DEVTYPE_BARO_BMP390
Definition at line 40 of file AP_Baro_Backend.h.
Constructor & Destructor Documentation
AP_Baro_Backend()
AP_Baro_Backend::AP_Baro_Backend (AP_Baro & baro)
Definition at line 9 of file AP_Baro_Backend.cpp.
~AP_Baro_Backend()
virtual AP_Baro_Backend::~AP_Baro_Backend (void) inline virtual
Definition at line 9 of file AP_Baro_Backend.h.
Member Function Documentation
_copy_to_frontend()
void AP_Baro_Backend::_copy_to_frontend (uint8_t instance, float pressure, float temperature) protected
Definition at line 49 of file AP_Baro_Backend.cpp.
Referenced by AP_Baro_MS56XX::_calculate_5607(), AP_Baro_MS56XX::_calculate_5611(), AP_Baro_MS56XX::_calculate_5637(), AP_Baro_MS56XX::_calculate_5837(), AP_Baro_BMP085::update(), AP_Baro_BMP280::update(), AP_Baro_BMP388::update(), AP_Baro_DPS280::update(), AP_Baro_FBM320::update(), AP_Baro_ICM20789::update(), AP_Baro_ICP101XX::update(), AP_Baro_ICP201XX::update(), AP_Baro_KellerLD::update(), AP_Baro_LPS2XH::update(), AP_Baro_SPL06::update(), and AP_Baro_Dummy::update().
accumulate()
virtual void AP_Baro_Backend::accumulate (void) inline virtual
Definition at line 18 of file AP_Baro_Backend.h.
Referenced by AP_Baro::accumulate().
backend_update()
void AP_Baro_Backend::backend_update (uint8_t instance)
Definition at line 39 of file AP_Baro_Backend.cpp.
Referenced by AP_Baro::update().
get_error_count()
uint32_t AP_Baro_Backend::get_error_count () const inline
Definition at line 25 of file AP_Baro_Backend.h.
pressure_ok()
bool AP_Baro_Backend::pressure_ok (float press)
Definition at line 73 of file AP_Baro_Backend.cpp.
Referenced by AP_Baro_BMP085::_calculate(), AP_Baro_KellerLD::_read(), AP_Baro_MS56XX::_timer(), AP_Baro_BMP280::_update_pressure(), AP_Baro_SPL06::_update_pressure(), AP_Baro_ICM20789::convert_data(), AP_Baro_ICP101XX::convert_data(), AP_Baro_DPS280::timer(), and AP_Baro_FBM320::timer().
set_bus_id()
void AP_Baro_Backend::set_bus_id (uint8_t instance, uint32_t id) inline protected
Definition at line 80 of file AP_Baro_Backend.h.
Referenced by AP_Baro_BMP085::_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_Baro_BMP280::_init(), AP_Baro_LPS2XH::_init(), AP_Baro_SPL06::_init(), AP_Baro_ICM20789::init(), AP_Baro_ICP101XX::init(), AP_Baro_ICP201XX::init(), AP_Baro_DPS280::init(), AP_Baro_BMP388::init(), and AP_Baro_FBM320::init().
update()
virtual void AP_Baro_Backend::update () pure virtual
Implemented in AP_Baro_BMP085, AP_Baro_BMP280, AP_Baro_BMP388, AP_Baro_DPS280, AP_Baro_FBM320, AP_Baro_ICM20789, AP_Baro_ICP101XX, AP_Baro_ICP201XX, AP_Baro_KellerLD, AP_Baro_LPS2XH, AP_Baro_MS56XX, AP_Baro_SPL06, and AP_Baro_Dummy.
Referenced by backend_update().
update_healthy_flag()
void AP_Baro_Backend::update_healthy_flag (uint8_t instance) protected virtual
Definition at line 14 of file AP_Baro_Backend.cpp.
Referenced by backend_update().
Member Data Documentation
_error_count
uint32_t AP_Baro_Backend::_error_count protected
Definition at line 77 of file AP_Baro_Backend.h.
Referenced by get_error_count(), and pressure_ok().
_frontend
AP_Baro& AP_Baro_Backend::_frontend protected
Definition at line 65 of file AP_Baro_Backend.h.
Referenced by _copy_to_frontend(), AP_Baro_BMP085::_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_Baro_BMP280::_init(), AP_Baro_LPS2XH::_init(), AP_Baro_SPL06::_init(), AP_Baro_Dummy::AP_Baro_Dummy(), AP_Baro_ICM20789::init(), AP_Baro_ICP101XX::init(), AP_Baro_ICP201XX::init(), AP_Baro_DPS280::init(), AP_Baro_BMP388::init(), AP_Baro_FBM320::init(), pressure_ok(), AP_Baro_KellerLD::read_mode_type(), set_bus_id(), AP_Baro_KellerLD::update(), and update_healthy_flag().
_mean_pressure
float AP_Baro_Backend::_mean_pressure protected
Definition at line 75 of file AP_Baro_Backend.h.
Referenced by pressure_ok().
_sem
HAL_Semaphore AP_Baro_Backend::_sem protected
Definition at line 70 of file AP_Baro_Backend.h.
Referenced by AP_Baro_BMP085::_calculate(), AP_Baro_KellerLD::_read(), AP_Baro_MS56XX::_timer(), AP_Baro_BMP280::_update_pressure(), AP_Baro_SPL06::_update_pressure(), AP_Baro_LPS2XH::_update_pressure(), AP_Baro_BMP280::_update_temperature(), AP_Baro_SPL06::_update_temperature(), AP_Baro_LPS2XH::_update_temperature(), AP_Baro_ICM20789::convert_data(), AP_Baro_ICP101XX::convert_data(), AP_Baro_ICP201XX::timer(), AP_Baro_DPS280::timer(), AP_Baro_FBM320::timer(), AP_Baro_BMP085::update(), AP_Baro_BMP280::update(), AP_Baro_BMP388::update(), AP_Baro_DPS280::update(), AP_Baro_FBM320::update(), AP_Baro_ICM20789::update(), AP_Baro_ICP101XX::update(), AP_Baro_ICP201XX::update(), AP_Baro_KellerLD::update(), AP_Baro_LPS2XH::update(), AP_Baro_MS56XX::update(), AP_Baro_SPL06::update(), update_healthy_flag(), AP_Baro_BMP388::update_pressure(), and AP_Baro_BMP388::update_temperature().
The documentation for this class was generated from the following files:
libraries/AP_Baro/AP_Baro_Backend.h
libraries/AP_Baro/AP_Baro_Backend.cpp