APM:Libraries: AP_SerialManager Class Reference
AP_SerialManager Class Reference
#include <AP_SerialManager.h>
Classes
class UARTState
Public Types
enum SerialProtocol {
SerialProtocol_None = -1 , SerialProtocol_Console = 0 , SerialProtocol_MAVLink = 1 , SerialProtocol_MAVLink2 = 2 ,
SerialProtocol_FrSky_D = 3 , SerialProtocol_FrSky_SPort = 4 , SerialProtocol_GPS = 5 , SerialProtocol_GPS2 = 6 ,
SerialProtocol_AlexMos = 7 , SerialProtocol_Gimbal = 8 , SerialProtocol_Rangefinder = 9 , SerialProtocol_FrSky_SPort_Passthrough = 10 ,
SerialProtocol_Lidar360 = 11 , SerialProtocol_Aerotenna_USD1 = 12 , SerialProtocol_Beacon = 13 , SerialProtocol_Volz = 14 ,
SerialProtocol_Sbus1 = 15 , SerialProtocol_ESCTelemetry = 16 , SerialProtocol_Devo_Telem = 17 , SerialProtocol_OpticalFlow = 18 ,
SerialProtocol_Robotis = 19 , SerialProtocol_NMEAOutput = 20 , SerialProtocol_WindVane = 21 , SerialProtocol_SLCAN = 22 ,
SerialProtocol_RCIN = 23 , SerialProtocol_EFI = 24 , SerialProtocol_LTM_Telem = 25 , SerialProtocol_RunCam = 26 ,
SerialProtocol_Hott = 27 , SerialProtocol_Scripting = 28 , SerialProtocol_CRSF = 29 , SerialProtocol_Generator = 30 ,
SerialProtocol_Winch = 31 , SerialProtocol_MSP = 32 , SerialProtocol_DJI_FPV = 33 , SerialProtocol_AirSpeed = 34 ,
SerialProtocol_ADSB = 35 , SerialProtocol_AHRS = 36 , SerialProtocol_SmartAudio = 37 , SerialProtocol_FETtecOneWire = 38 ,
SerialProtocol_Torqeedo = 39 , SerialProtocol_AIS = 40 , SerialProtocol_CoDevESC = 41 , SerialProtocol_MSP_DisplayPort = 42 ,
SerialProtocol_MAVLinkHL = 43 , SerialProtocol_Tramp = 44 , SerialProtocol_DDS_XRCE = 45 , SerialProtocol_IMUOUT = 46 ,
SerialProtocol_PPP = 48 , SerialProtocol_NumProtocols
}
Public Member Functions
AP_SerialManager ()
CLASS_NO_COPY (AP_SerialManager)
void init_console ()
void init ()
AP_HAL::UARTDriver * find_serial (enum SerialProtocol protocol, uint8_t instance) const
bool have_serial (enum SerialProtocol protocol, uint8_t instance) const
uint32_t find_baudrate (enum SerialProtocol protocol, uint8_t instance) const
int8_t find_portnum (enum SerialProtocol protocol, uint8_t instance) const
bool get_passthru (AP_HAL::UARTDriver *&port1, AP_HAL::UARTDriver *&port2, uint8_t &timeout_s, uint32_t &baud1, uint32_t &baud2)
void disable_passthru (void)
AP_HAL::UARTDriver * get_serial_by_id (uint8_t id)
void set_protocol_and_baud (uint8_t sernum, enum SerialProtocol protocol, uint32_t baudrate)
const UARTState * get_state_by_id (uint8_t id) const
const UARTState * find_protocol_instance (enum SerialProtocol protocol, uint8_t instance) const
Static Public Member Functions
static AP_SerialManager * get_singleton (void)
static uint32_t map_baudrate (int32_t rate)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
bool protocol_match (enum SerialProtocol protocol1, enum SerialProtocol protocol2) const
void set_options (uint16_t i)
Private Attributes
UARTState state [SERIALMANAGER_MAX_PORTS]
AP_Int8 passthru_port1
AP_Int8 passthru_port2
AP_Int8 passthru_timeout
bool init_console_done
Static Private Attributes
static AP_SerialManager * _singleton
Detailed Description
Definition at line 30 of file AP_SerialManager.h.
Member Enumeration Documentation
SerialProtocol
enum AP_SerialManager::SerialProtocol
Enumerator
SerialProtocol_None
SerialProtocol_Console
SerialProtocol_MAVLink
SerialProtocol_MAVLink2
SerialProtocol_FrSky_D
SerialProtocol_FrSky_SPort
SerialProtocol_GPS
SerialProtocol_GPS2
SerialProtocol_AlexMos
SerialProtocol_Gimbal
SerialProtocol_Rangefinder
SerialProtocol_FrSky_SPort_Passthrough
SerialProtocol_Lidar360
SerialProtocol_Aerotenna_USD1
SerialProtocol_Beacon
SerialProtocol_Volz
SerialProtocol_Sbus1
SerialProtocol_ESCTelemetry
SerialProtocol_Devo_Telem
SerialProtocol_OpticalFlow
SerialProtocol_Robotis
SerialProtocol_NMEAOutput
SerialProtocol_WindVane
SerialProtocol_SLCAN
SerialProtocol_RCIN
SerialProtocol_EFI
SerialProtocol_LTM_Telem
SerialProtocol_RunCam
SerialProtocol_Hott
SerialProtocol_Scripting
SerialProtocol_CRSF
SerialProtocol_Generator
SerialProtocol_Winch
SerialProtocol_MSP
SerialProtocol_DJI_FPV
SerialProtocol_AirSpeed
SerialProtocol_ADSB
SerialProtocol_AHRS
SerialProtocol_SmartAudio
SerialProtocol_FETtecOneWire
SerialProtocol_Torqeedo
SerialProtocol_AIS
SerialProtocol_CoDevESC
SerialProtocol_MSP_DisplayPort
SerialProtocol_MAVLinkHL
SerialProtocol_Tramp
SerialProtocol_DDS_XRCE
SerialProtocol_IMUOUT
SerialProtocol_PPP
SerialProtocol_NumProtocols
Definition at line 37 of file AP_SerialManager.h.
Constructor & Destructor Documentation
AP_SerialManager()
AP_SerialManager::AP_SerialManager ()
Definition at line 402 of file AP_SerialManager.cpp.
Member Function Documentation
CLASS_NO_COPY()
AP_SerialManager::CLASS_NO_COPY (AP_SerialManager)
disable_passthru()
void AP_SerialManager::disable_passthru (void)
Definition at line 824 of file AP_SerialManager.cpp.
Referenced by GCS::update_passthru().
find_baudrate()
uint32_t AP_SerialManager::find_baudrate (enum SerialProtocol protocol, uint8_t instance) const
Definition at line 673 of file AP_SerialManager.cpp.
Referenced by AP_Beacon_Marvelmind::AP_Beacon_Backend(), AP_WindVane_NMEA::init(), and AP_RangeFinder_Backend_Serial::initial_baudrate().
find_portnum()
int8_t AP_SerialManager::find_portnum (enum SerialProtocol protocol, uint8_t instance) const
Definition at line 683 of file AP_SerialManager.cpp.
find_protocol_instance()
const AP_SerialManager::UARTState * AP_SerialManager::find_protocol_instance (enum SerialProtocol protocol, uint8_t instance) const
Definition at line 603 of file AP_SerialManager.cpp.
Referenced by find_baudrate(), find_portnum(), find_serial(), have_serial(), and GCS_MAVLINK::init().
find_serial()
AP_HAL::UARTDriver * AP_SerialManager::find_serial (enum SerialProtocol protocol, uint8_t instance) const
Definition at line 635 of file AP_SerialManager.cpp.
Referenced by AP_Beacon_Marvelmind::AP_Beacon_Backend(), AP_RCProtocol_CRSF::AP_RCProtocol_CRSF(), AP_OpticalFlow_CXOF::detect(), AP_OpticalFlow_UPFLOW::detect(), AP_RunCam::init(), AP_LTM_Telem::init(), AP_MSP::init(), AP_SmartAudio::init(), AP_Mount_Alexmos::init(), AP_Mount_Siyi::init(), AP_Mount_SToRM32_serial::init(), AP_Frsky_Telem::init(), AP_WindVane_NMEA::init(), AP_GPS::init(), AP_Hott_Telem::init(), AP_SBusOut::init(), AP_Generator_IE_FuelCell::init(), AP_RangeFinder_Backend_Serial::init_serial(), GCS::setup_console(), and GCS::setup_uarts().
get_passthru()
bool AP_SerialManager::get_passthru (AP_HAL::UARTDriver *& port1, AP_HAL::UARTDriver *& port2, uint8_t & timeout_s, uint32_t & baud1, uint32_t & baud2)
Definition at line 800 of file AP_SerialManager.cpp.
Referenced by GCS::update_passthru().
get_serial_by_id()
AP_HAL::UARTDriver * AP_SerialManager::get_serial_by_id (uint8_t id)
Definition at line 693 of file AP_SerialManager.cpp.
Referenced by GCS::get_channel_from_port_number(), get_passthru(), and GCS_MAVLINK::handle_serial_control().
get_singleton()
static AP_SerialManager * AP_SerialManager::get_singleton (void) inline static
Definition at line 92 of file AP_SerialManager.h.
Referenced by AP_OpticalFlow_CXOF::detect(), AP_OpticalFlow_UPFLOW::detect(), AP_RunCam::init(), AP_SBusOut::init(), and AP::serialmanager().
get_state_by_id()
const AP_SerialManager::UARTState * AP_SerialManager::get_state_by_id (uint8_t id) const
Definition at line 711 of file AP_SerialManager.cpp.
Referenced by get_passthru().
have_serial()
bool AP_SerialManager::have_serial (enum SerialProtocol protocol, uint8_t instance) const
Definition at line 665 of file AP_SerialManager.cpp.
init()
void AP_SerialManager::init ()
Definition at line 424 of file AP_SerialManager.cpp.
Referenced by setup(), and AP_Vehicle::setup().
init_console()
void AP_SerialManager::init_console ()
Definition at line 410 of file AP_SerialManager.cpp.
Referenced by init(), setup(), and AP_Vehicle::setup().
map_baudrate()
uint32_t AP_SerialManager::map_baudrate (int32_t rate) static
Definition at line 731 of file AP_SerialManager.cpp.
Referenced by AP_SerialManager::UARTState::baudrate().
protocol_match()
bool AP_SerialManager::protocol_match (enum SerialProtocol protocol1, enum SerialProtocol protocol2) const private
Definition at line 767 of file AP_SerialManager.cpp.
Referenced by find_protocol_instance().
set_options()
void AP_SerialManager::set_options (uint16_t i) private
Definition at line 790 of file AP_SerialManager.cpp.
Referenced by init().
set_protocol_and_baud()
void AP_SerialManager::set_protocol_and_baud (uint8_t sernum, enum SerialProtocol protocol, uint32_t baudrate)
Definition at line 830 of file AP_SerialManager.cpp.
Member Data Documentation
_singleton
AP_SerialManager * AP_SerialManager::_singleton static private
Definition at line 190 of file AP_SerialManager.h.
Referenced by AP_SerialManager(), and get_singleton().
init_console_done
bool AP_SerialManager::init_console_done private
Definition at line 207 of file AP_SerialManager.h.
Referenced by init_console().
passthru_port1
AP_Int8 AP_SerialManager::passthru_port1 private
Definition at line 197 of file AP_SerialManager.h.
Referenced by get_passthru().
passthru_port2
AP_Int8 AP_SerialManager::passthru_port2 private
Definition at line 198 of file AP_SerialManager.h.
Referenced by disable_passthru(), get_passthru(), and init().
passthru_timeout
AP_Int8 AP_SerialManager::passthru_timeout private
Definition at line 199 of file AP_SerialManager.h.
Referenced by get_passthru().
state
UARTState AP_SerialManager::state[SERIALMANAGER_MAX_PORTS] private
Definition at line 194 of file AP_SerialManager.h.
Referenced by find_protocol_instance(), get_state_by_id(), init(), set_options(), and set_protocol_and_baud().
var_info
const AP_Param::GroupInfo AP_SerialManager::var_info static
Definition at line 164 of file AP_SerialManager.h.
Referenced by setup().
The documentation for this class was generated from the following files:
libraries/AP_SerialManager/AP_SerialManager.h
libraries/AP_SerialManager/AP_SerialManager.cpp