APM:Libraries: AP_SmartAudio Class Reference
AP_SmartAudio Class Reference
#include <AP_SmartAudio.h>
Classes
struct Frame
struct FrameHeader
struct Packet
struct Settings
struct SettingsExtendedResponseFrame
struct SettingsResponseFrame
struct U16ResponseFrame
struct U8ResponseFrame
Public Types
enum ProtocolVersion { SMARTAUDIO_SPEC_PROTOCOL_v1 = 0 , SMARTAUDIO_SPEC_PROTOCOL_v2 = 1 , SMARTAUDIO_SPEC_PROTOCOL_v21 = 2 }
Public Member Functions
AP_SmartAudio ()
CLASS_NO_COPY (AP_SmartAudio)
bool init ()
Static Public Member Functions
static AP_SmartAudio * get_singleton (void)
Public Attributes
struct AP_SmartAudio::FrameHeader PACKED
struct AP_SmartAudio::Frame PACKED
struct AP_SmartAudio::U8ResponseFrame PACKED
struct AP_SmartAudio::U16ResponseFrame PACKED
struct AP_SmartAudio::SettingsResponseFrame PACKED
struct AP_SmartAudio::SettingsExtendedResponseFrame PACKED
struct AP_SmartAudio::Packet PACKED
Private Member Functions
void print_settings (const Settings *settings)
void update_vtx_params ()
void update_vtx_settings (const Settings &settings)
bool ignore_crc () const
void loop ()
void send_request (const Frame &requestFrame, uint8_t size)
bool read_response (uint8_t *response_buffer)
bool parse_frame_response (const uint8_t *buffer)
bool parse_response_buffer (const uint8_t *buffer)
bool get_readings (AP_VideoTX *vtx_dest)
void request_settings ()
void set_operation_mode (uint8_t mode)
void set_frequency (uint16_t frequency, bool isPitModeFreq)
void set_channel (uint8_t chan)
void request_pit_mode_frequency ()
void set_power (uint16_t power_mw, uint16_t dbm)
void set_power (uint8_t power_level)
void set_band_channel (const uint8_t band, const uint8_t channel)
void push_command_only_frame (uint8_t command)
void push_uint8_command_frame (uint8_t command, uint8_t data)
void push_uint16_command_frame (uint8_t command, uint16_t data)
void update_baud_rate ()
void set_configuration_pending (bool pending)
bool is_configuration_pending ()
Static Private Member Functions
static void unpack_frequency (Settings *settings, const uint16_t frequency)
static void unpack_settings (Settings *settings, const SettingsResponseFrame *frame)
static void unpack_settings (Settings *settings, const SettingsExtendedResponseFrame *frame)
Private Attributes
AP_HAL::UARTDriver * _port
uint8_t _inline_buffer_length
uint8_t _packet_size
ProtocolVersion _protocol_version
uint16_t _packets_sent
uint16_t _packets_rcvd
bool _vtx_freq_change_pending
bool _vtx_power_change_pending
bool _vtx_options_change_pending
bool _vtx_changes_pending
bool _vtx_use_set_freq
int32_t _smartbaud = AP_SMARTAUDIO_UART_BAUD
int32_t _smartbaud_direction = 1
uint8_t _vtx_state_idx
Settings _vtx_states_buffer [2]
Settings * _vtx_current_state
volatile bool _initialised
ObjectBuffer< Packet > requests_queue {SMARTAUDIO_BUFFER_CAPACITY}
uint32_t _last_request_sent_ms
bool _is_waiting_response
Static Private Attributes
static AP_SmartAudio * _singleton
Detailed Description
Definition at line 66 of file AP_SmartAudio.h.
Member Enumeration Documentation
ProtocolVersion
enum AP_SmartAudio::ProtocolVersion
Enumerator
SMARTAUDIO_SPEC_PROTOCOL_v1
SMARTAUDIO_SPEC_PROTOCOL_v2
SMARTAUDIO_SPEC_PROTOCOL_v21
Definition at line 69 of file AP_SmartAudio.h.
Constructor & Destructor Documentation
AP_SmartAudio()
AP_SmartAudio::AP_SmartAudio ()
Definition at line 34 of file AP_SmartAudio.cpp.
Member Function Documentation
CLASS_NO_COPY()
AP_SmartAudio::CLASS_NO_COPY (AP_SmartAudio)
get_readings()
bool AP_SmartAudio::get_readings (AP_VideoTX * vtx_dest) private
get_singleton()
static AP_SmartAudio * AP_SmartAudio::get_singleton (void) inline static
Definition at line 153 of file AP_SmartAudio.h.
ignore_crc()
bool AP_SmartAudio::ignore_crc () const inline private
Definition at line 217 of file AP_SmartAudio.h.
Referenced by parse_response_buffer(), and read_response().
init()
bool AP_SmartAudio::init ()
Definition at line 42 of file AP_SmartAudio.cpp.
is_configuration_pending()
bool AP_SmartAudio::is_configuration_pending () inline private
Definition at line 262 of file AP_SmartAudio.h.
Referenced by loop().
loop()
void AP_SmartAudio::loop () private
Definition at line 70 of file AP_SmartAudio.cpp.
Referenced by init().
parse_frame_response()
bool AP_SmartAudio::parse_frame_response (const uint8_t * buffer) private
parse_response_buffer()
bool AP_SmartAudio::parse_response_buffer (const uint8_t * buffer) private
Definition at line 544 of file AP_SmartAudio.cpp.
Referenced by read_response().
print_settings()
void AP_SmartAudio::print_settings (const Settings * settings) private
Definition at line 495 of file AP_SmartAudio.cpp.
Referenced by parse_response_buffer().
push_command_only_frame()
void AP_SmartAudio::push_command_only_frame (uint8_t command) private
Definition at line 365 of file AP_SmartAudio.cpp.
Referenced by request_settings().
push_uint16_command_frame()
void AP_SmartAudio::push_uint16_command_frame (uint8_t command, uint16_t data) private
Definition at line 389 of file AP_SmartAudio.cpp.
Referenced by request_pit_mode_frequency(), set_band_channel(), and set_frequency().
push_uint8_command_frame()
void AP_SmartAudio::push_uint8_command_frame (uint8_t command, uint8_t data) private
Definition at line 377 of file AP_SmartAudio.cpp.
Referenced by set_channel(), set_operation_mode(), and set_power().
read_response()
bool AP_SmartAudio::read_response (uint8_t * response_buffer) private
Reads the response from vtx in the wire
response_buffer, response buffer to fill in
inline_buffer_length , used to passthrought the response lenght in case the response where splitted
Definition at line 280 of file AP_SmartAudio.cpp.
Referenced by loop().
request_pit_mode_frequency()
void AP_SmartAudio::request_pit_mode_frequency () private
Request pitMode Frequency setted into the vtx hardware
Definition at line 435 of file AP_SmartAudio.cpp.
request_settings()
void AP_SmartAudio::request_settings () private
Sends get settings command.
Definition at line 402 of file AP_SmartAudio.cpp.
Referenced by loop().
send_request()
void AP_SmartAudio::send_request (const Frame & requestFrame, uint8_t size) private
Sends an SmartAudio Command to the vtx, waits response on the update event
Parameters
frameBuffer frameBuffer to send over the wire
size size of the framebuffer wich needs to be sended
Definition at line 252 of file AP_SmartAudio.cpp.
Referenced by loop().
set_band_channel()
void AP_SmartAudio::set_band_channel (const uint8_t band, const uint8_t channel) private
Definition at line 449 of file AP_SmartAudio.cpp.
set_channel()
void AP_SmartAudio::set_channel (uint8_t chan) private
Definition at line 426 of file AP_SmartAudio.cpp.
Referenced by update_vtx_params().
set_configuration_pending()
void AP_SmartAudio::set_configuration_pending (bool pending) inline private
Definition at line 261 of file AP_SmartAudio.h.
Referenced by loop().
set_frequency()
void AP_SmartAudio::set_frequency (uint16_t frequency, bool isPitModeFreq) private
Sets the frequency to transmit in the vtx. When isPitModeFreq active the freq will be set to be used when in pitmode (in range)
Definition at line 418 of file AP_SmartAudio.cpp.
Referenced by update_vtx_params().
set_operation_mode()
void AP_SmartAudio::set_operation_mode (uint8_t mode) private
Definition at line 408 of file AP_SmartAudio.cpp.
Referenced by update_vtx_params().
set_power() [1/2]
void AP_SmartAudio::set_power (uint16_t power_mw, uint16_t dbm) private
Referenced by update_vtx_params().
set_power() [2/2]
void AP_SmartAudio::set_power (uint8_t power_level) private
Definition at line 442 of file AP_SmartAudio.cpp.
unpack_frequency()
void AP_SmartAudio::unpack_frequency (AP_SmartAudio::Settings * settings, const uint16_t frequency) static private
Definition at line 455 of file AP_SmartAudio.cpp.
Referenced by parse_response_buffer(), and unpack_settings().
unpack_settings() [1/2]
void AP_SmartAudio::unpack_settings (Settings * settings, const SettingsExtendedResponseFrame * frame) static private
Definition at line 476 of file AP_SmartAudio.cpp.
unpack_settings() [2/2]
void AP_SmartAudio::unpack_settings (Settings * settings, const SettingsResponseFrame * frame) static private
Definition at line 465 of file AP_SmartAudio.cpp.
Referenced by parse_response_buffer(), and unpack_settings().
update_baud_rate()
void AP_SmartAudio::update_baud_rate () private
Definition at line 651 of file AP_SmartAudio.cpp.
Referenced by loop().
update_vtx_params()
void AP_SmartAudio::update_vtx_params () private
Definition at line 162 of file AP_SmartAudio.cpp.
Referenced by loop().
update_vtx_settings()
void AP_SmartAudio::update_vtx_settings (const Settings & settings) private
Definition at line 507 of file AP_SmartAudio.cpp.
Referenced by parse_response_buffer().
Member Data Documentation
_initialised
volatile bool AP_SmartAudio::_initialised private
Definition at line 197 of file AP_SmartAudio.h.
Referenced by loop(), and update_vtx_settings().
_inline_buffer_length
uint8_t AP_SmartAudio::_inline_buffer_length private
Definition at line 172 of file AP_SmartAudio.h.
Referenced by loop(), and read_response().
_is_waiting_response
bool AP_SmartAudio::_is_waiting_response private
Definition at line 206 of file AP_SmartAudio.h.
Referenced by loop(), and read_response().
_last_request_sent_ms
uint32_t AP_SmartAudio::_last_request_sent_ms private
Definition at line 203 of file AP_SmartAudio.h.
Referenced by loop().
_packet_size
uint8_t AP_SmartAudio::_packet_size private
Definition at line 174 of file AP_SmartAudio.h.
Referenced by read_response().
_packets_rcvd
uint16_t AP_SmartAudio::_packets_rcvd private
Definition at line 179 of file AP_SmartAudio.h.
Referenced by read_response(), and update_baud_rate().
_packets_sent
uint16_t AP_SmartAudio::_packets_sent private
Definition at line 178 of file AP_SmartAudio.h.
Referenced by read_response(), send_request(), and update_baud_rate().
_port
AP_HAL::UARTDriver* AP_SmartAudio::_port private
Definition at line 166 of file AP_SmartAudio.h.
Referenced by init(), loop(), read_response(), send_request(), and update_baud_rate().
_protocol_version
ProtocolVersion AP_SmartAudio::_protocol_version private
Definition at line 176 of file AP_SmartAudio.h.
Referenced by parse_response_buffer(), and update_vtx_params().
_singleton
AP_SmartAudio * AP_SmartAudio::_singleton static private
Definition at line 169 of file AP_SmartAudio.h.
Referenced by AP_SmartAudio(), and get_singleton().
_smartbaud
int32_t AP_SmartAudio::_smartbaud = AP_SMARTAUDIO_UART_BAUD private
Definition at line 188 of file AP_SmartAudio.h.
Referenced by loop(), and update_baud_rate().
_smartbaud_direction
int32_t AP_SmartAudio::_smartbaud_direction = 1 private
Definition at line 189 of file AP_SmartAudio.h.
Referenced by update_baud_rate().
_vtx_changes_pending
bool AP_SmartAudio::_vtx_changes_pending private
Definition at line 184 of file AP_SmartAudio.h.
Referenced by is_configuration_pending(), and set_configuration_pending().
_vtx_current_state
Settings* AP_SmartAudio::_vtx_current_state private
Definition at line 194 of file AP_SmartAudio.h.
_vtx_freq_change_pending
bool AP_SmartAudio::_vtx_freq_change_pending private
Definition at line 181 of file AP_SmartAudio.h.
Referenced by loop(), update_vtx_params(), and update_vtx_settings().
_vtx_options_change_pending
bool AP_SmartAudio::_vtx_options_change_pending private
Definition at line 183 of file AP_SmartAudio.h.
Referenced by loop(), update_vtx_params(), and update_vtx_settings().
_vtx_power_change_pending
bool AP_SmartAudio::_vtx_power_change_pending private
Definition at line 182 of file AP_SmartAudio.h.
Referenced by loop(), update_vtx_params(), and update_vtx_settings().
_vtx_state_idx
uint8_t AP_SmartAudio::_vtx_state_idx private
Definition at line 192 of file AP_SmartAudio.h.
_vtx_states_buffer
Settings AP_SmartAudio::_vtx_states_buffer[2] private
Definition at line 193 of file AP_SmartAudio.h.
_vtx_use_set_freq
bool AP_SmartAudio::_vtx_use_set_freq private
Definition at line 185 of file AP_SmartAudio.h.
Referenced by update_vtx_params(), and update_vtx_settings().
PACKED [1/7]
struct AP_SmartAudio::FrameHeader AP_SmartAudio::PACKED
PACKED [2/7]
struct AP_SmartAudio::Frame AP_SmartAudio::PACKED
PACKED [3/7]
struct AP_SmartAudio::U8ResponseFrame AP_SmartAudio::PACKED
PACKED [4/7]
struct AP_SmartAudio::U16ResponseFrame AP_SmartAudio::PACKED
PACKED [5/7]
struct AP_SmartAudio::SettingsResponseFrame AP_SmartAudio::PACKED
PACKED [6/7]
struct AP_SmartAudio::SettingsExtendedResponseFrame AP_SmartAudio::PACKED
PACKED [7/7]
struct AP_SmartAudio::Packet AP_SmartAudio::PACKED
requests_queue
ObjectBuffer<Packet> AP_SmartAudio::requests_queue {SMARTAUDIO_BUFFER_CAPACITY} private
Definition at line 200 of file AP_SmartAudio.h.
Referenced by loop(), push_command_only_frame(), push_uint16_command_frame(), and push_uint8_command_frame().
The documentation for this class was generated from the following files:
libraries/AP_VideoTX/AP_SmartAudio.h
libraries/AP_VideoTX/AP_SmartAudio.cpp