APM:Libraries: OpticalFlow_backend Class Reference
OpticalFlow_backend Class Reference abstract
#include <AP_OpticalFlow_Backend.h>
Public Member Functions
OpticalFlow_backend (AP_OpticalFlow &_frontend)
virtual ~OpticalFlow_backend (void)
CLASS_NO_COPY (OpticalFlow_backend)
virtual void init ()
virtual void update ()=0
virtual void handle_msg (const mavlink_message_t &msg)
Protected Member Functions
void _update_frontend (const struct AP_OpticalFlow::OpticalFlow_state &state)
Vector2f _flowScaler (void) const
float _yawAngleRad (void) const
void _applyYaw (Vector2f &v)
uint8_t get_address (void) const
Protected Attributes
AP_OpticalFlow & frontend
HAL_Semaphore _sem
Friends
class AP_OpticalFlow
Detailed Description
Definition at line 25 of file AP_OpticalFlow_Backend.h.
Constructor & Destructor Documentation
OpticalFlow_backend()
OpticalFlow_backend::OpticalFlow_backend (AP_OpticalFlow & _frontend)
Definition at line 22 of file AP_OpticalFlow_Backend.cpp.
~OpticalFlow_backend()
OpticalFlow_backend::~OpticalFlow_backend (void) virtual
Definition at line 27 of file AP_OpticalFlow_Backend.cpp.
Member Function Documentation
_applyYaw()
void OpticalFlow_backend::_applyYaw (Vector2f & v) protected
Definition at line 38 of file AP_OpticalFlow_Backend.cpp.
Referenced by AP_OpticalFlow_PX4Flow::timer(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_Onboard::update(), AP_OpticalFlow_Pixart::update(), and AP_OpticalFlow_UPFLOW::update().
_flowScaler()
Vector2f OpticalFlow_backend::_flowScaler (void) const inline protected
Definition at line 58 of file AP_OpticalFlow_Backend.h.
Referenced by AP_OpticalFlow_PX4Flow::timer(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_Onboard::update(), AP_OpticalFlow_Pixart::update(), and AP_OpticalFlow_UPFLOW::update().
_update_frontend()
void OpticalFlow_backend::_update_frontend (const struct AP_OpticalFlow::OpticalFlow_state & state) protected
Definition at line 32 of file AP_OpticalFlow_Backend.cpp.
Referenced by AP_OpticalFlow_PX4Flow::timer(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_Onboard::update(), AP_OpticalFlow_Pixart::update(), and AP_OpticalFlow_UPFLOW::update().
_yawAngleRad()
float OpticalFlow_backend::_yawAngleRad (void) const inline protected
Definition at line 61 of file AP_OpticalFlow_Backend.h.
Referenced by _applyYaw().
CLASS_NO_COPY()
OpticalFlow_backend::CLASS_NO_COPY (OpticalFlow_backend)
get_address()
uint8_t OpticalFlow_backend::get_address (void) const inline protected
Definition at line 67 of file AP_OpticalFlow_Backend.h.
Referenced by AP_OpticalFlow_PX4Flow::scan_buses().
handle_msg()
virtual void OpticalFlow_backend::handle_msg (const mavlink_message_t & msg) inline virtual
Definition at line 43 of file AP_OpticalFlow_Backend.h.
Referenced by AP_OpticalFlow::handle_msg().
init()
virtual void OpticalFlow_backend::init (void) inline virtual
Reimplemented in AP_OpticalFlow_CXOF, AP_OpticalFlow_Pixart, AP_OpticalFlow_PX4Flow, AP_OpticalFlow_UPFLOW, and AP_OpticalFlow_Onboard.
Definition at line 37 of file AP_OpticalFlow_Backend.h.
Referenced by AP_OpticalFlow::init().
update()
virtual void OpticalFlow_backend::update () pure virtual
Implemented in AP_OpticalFlow_CXOF, AP_OpticalFlow_Onboard, AP_OpticalFlow_Pixart, AP_OpticalFlow_PX4Flow, and AP_OpticalFlow_UPFLOW.
Referenced by AP_OpticalFlow::update().
Friends And Related Symbol Documentation
AP_OpticalFlow
friend class AP_OpticalFlow friend
Definition at line 27 of file AP_OpticalFlow_Backend.h.
Member Data Documentation
_sem
HAL_Semaphore OpticalFlow_backend::_sem protected
Definition at line 70 of file AP_OpticalFlow_Backend.h.
Referenced by AP_OpticalFlow_Pixart::timer(), and AP_OpticalFlow_Pixart::update().
frontend
AP_OpticalFlow& OpticalFlow_backend::frontend protected
Definition at line 52 of file AP_OpticalFlow_Backend.h.
Referenced by _flowScaler(), _update_frontend(), _yawAngleRad(), and get_address().
The documentation for this class was generated from the following files:
libraries/AP_OpticalFlow/AP_OpticalFlow_Backend.h
libraries/AP_OpticalFlow/AP_OpticalFlow_Backend.cpp