APM:Libraries: AP_ICEngine_TCA9554 Class Reference
AP_ICEngine_TCA9554 Class Reference
#include <AP_ICEngine_TCA9554.h>
Public Member Functions
void set_starter (bool on)
Private Types
enum TCA9554_state_t { STARTER_OFF = 0x30 , STARTER_ON = 0x11 }
Private Member Functions
bool TCA9554_init ()
void TCA9554_set (TCA9554_state_t value)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev_TCA9554
TCA9554_state_t last_state
bool initialised
uint32_t last_reg_check_ms
Detailed Description
Definition at line 10 of file AP_ICEngine_TCA9554.h.
Member Enumeration Documentation
TCA9554_state_t
enum AP_ICEngine_TCA9554::TCA9554_state_t private
Enumerator
STARTER_OFF
STARTER_ON
Definition at line 17 of file AP_ICEngine_TCA9554.h.
Member Function Documentation
set_starter()
void AP_ICEngine_TCA9554::set_starter (bool on)
Definition at line 85 of file AP_ICEngine_TCA9554.cpp.
Referenced by AP_ICEngine::set_starter().
TCA9554_init()
bool AP_ICEngine_TCA9554::TCA9554_init () private
Definition at line 33 of file AP_ICEngine_TCA9554.cpp.
Referenced by set_starter().
TCA9554_set()
void AP_ICEngine_TCA9554::TCA9554_set (TCA9554_state_t value) private
Definition at line 63 of file AP_ICEngine_TCA9554.cpp.
Referenced by set_starter().
Member Data Documentation
dev_TCA9554
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_ICEngine_TCA9554::dev_TCA9554 private
Definition at line 15 of file AP_ICEngine_TCA9554.h.
Referenced by TCA9554_init(), and TCA9554_set().
initialised
bool AP_ICEngine_TCA9554::initialised private
Definition at line 23 of file AP_ICEngine_TCA9554.h.
Referenced by set_starter().
last_reg_check_ms
uint32_t AP_ICEngine_TCA9554::last_reg_check_ms private
Definition at line 27 of file AP_ICEngine_TCA9554.h.
Referenced by TCA9554_set().
last_state
TCA9554_state_t AP_ICEngine_TCA9554::last_state private
Definition at line 21 of file AP_ICEngine_TCA9554.h.
Referenced by TCA9554_set().
The documentation for this class was generated from the following files:
libraries/AP_ICEngine/AP_ICEngine_TCA9554.h
libraries/AP_ICEngine/AP_ICEngine_TCA9554.cpp