APM:Libraries: AP_Relay Class Reference
AP_Relay Class Reference
Class to manage the ArduPilot relay.
#include <AP_Relay.h>
Public Member Functions
AP_Relay ()
CLASS_NO_COPY (AP_Relay)
void init ()
void on (uint8_t instance)
void off (uint8_t instance)
bool get (uint8_t instance) const
bool enabled (uint8_t instance) const
void toggle (uint8_t instance)
bool arming_checks (size_t buflen, char *buffer) const
bool send_relay_status (const class GCS_MAVLINK &link) const
void set (AP_Relay_Params::FUNCTION function, bool value)
bool enabled (AP_Relay_Params::FUNCTION function) const
Static Public Member Functions
static AP_Relay * get_singleton (void)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
bool function_valid (AP_Relay_Params::FUNCTION function) const
void set (uint8_t instance, bool value)
void set_defaults ()
void convert_params ()
void set_pin_by_instance (uint8_t instance, bool value)
void set_pin (const int16_t pin, const bool value)
bool get_pin (const int16_t pin) const
Private Attributes
AP_Relay_Params _params [AP_RELAY_NUM_RELAYS]
Static Private Attributes
static AP_Relay * singleton
Detailed Description
Class to manage the ArduPilot relay.
Definition at line 33 of file AP_Relay.h.
Constructor & Destructor Documentation
AP_Relay()
AP_Relay::AP_Relay (void)
Definition at line 191 of file AP_Relay.cpp.
Member Function Documentation
arming_checks()
bool AP_Relay::arming_checks (size_t buflen, char * buffer) const
Definition at line 443 of file AP_Relay.cpp.
Referenced by AP_Arming::system_checks().
CLASS_NO_COPY()
AP_Relay::CLASS_NO_COPY (AP_Relay)
convert_params()
void AP_Relay::convert_params () private
Definition at line 203 of file AP_Relay.cpp.
Referenced by init().
enabled() [1/2]
bool AP_Relay::enabled (AP_Relay_Params::FUNCTION function) const
Definition at line 551 of file AP_Relay.cpp.
enabled() [2/2]
bool AP_Relay::enabled (uint8_t instance) const
Definition at line 544 of file AP_Relay.cpp.
Referenced by AP_Parachute::arming_checks(), and AP_MotorsUGV::pre_arm_check().
function_valid()
bool AP_Relay::function_valid (AP_Relay_Params::FUNCTION function) const private
Definition at line 331 of file AP_Relay.cpp.
Referenced by arming_checks(), init(), and set().
get()
bool AP_Relay::get (uint8_t instance) const
Definition at line 492 of file AP_Relay.cpp.
Referenced by toggle().
get_pin()
bool AP_Relay::get_pin (const int16_t pin) const private
Definition at line 503 of file AP_Relay.cpp.
Referenced by get(), and set_pin_by_instance().
get_singleton()
static AP_Relay * AP_Relay::get_singleton (void) inline static
Definition at line 65 of file AP_Relay.h.
Referenced by AP::relay().
init()
void AP_Relay::init ()
Definition at line 336 of file AP_Relay.cpp.
off()
void AP_Relay::off (uint8_t instance) inline
Definition at line 51 of file AP_Relay.h.
on()
void AP_Relay::on (uint8_t instance) inline
Definition at line 48 of file AP_Relay.h.
send_relay_status()
bool AP_Relay::send_relay_status (const class GCS_MAVLINK & link) const
set() [1/2]
void AP_Relay::set (AP_Relay_Params::FUNCTION function, bool value)
Definition at line 378 of file AP_Relay.cpp.
Referenced by off(), on(), AP_MotorsUGV::output_throttle(), AP_ICEngine::set_ignition(), AP_ICEngine::set_starter(), toggle(), and AP_Parachute::update().
set() [2/2]
void AP_Relay::set (uint8_t instance, bool value) private
Definition at line 422 of file AP_Relay.cpp.
set_defaults()
void AP_Relay::set_defaults () private
Definition at line 314 of file AP_Relay.cpp.
Referenced by init().
set_pin()
void AP_Relay::set_pin (const int16_t pin, const bool value) private
Definition at line 523 of file AP_Relay.cpp.
Referenced by set_pin_by_instance().
set_pin_by_instance()
void AP_Relay::set_pin_by_instance (uint8_t instance, bool value) private
Definition at line 395 of file AP_Relay.cpp.
Referenced by init(), set(), and set().
toggle()
void AP_Relay::toggle (uint8_t instance)
Definition at line 435 of file AP_Relay.cpp.
Referenced by AP_ServoRelayEvents::update_events().
Member Data Documentation
_params
AP_Relay_Params AP_Relay::_params[AP_RELAY_NUM_RELAYS] private
Definition at line 79 of file AP_Relay.h.
Referenced by arming_checks(), convert_params(), enabled(), enabled(), get(), init(), set(), set(), set_defaults(), set_pin_by_instance(), and toggle().
singleton
AP_Relay * AP_Relay::singleton static private
Definition at line 77 of file AP_Relay.h.
Referenced by AP_Relay(), and get_singleton().
var_info
const AP_Param::GroupInfo AP_Relay::var_info static
Definition at line 81 of file AP_Relay.h.
The documentation for this class was generated from the following files:
libraries/AP_Relay/AP_Relay.h
libraries/AP_Relay/AP_Relay.cpp