APM:Libraries: AP_MotorsMulticopter Class Reference
AP_MotorsMulticopter Class Reference abstract
#include <AP_MotorsMulticopter.h>
Public Member Functions
AP_MotorsMulticopter (uint16_t speed_hz=AP_MOTORS_SPEED_DEFAULT)
virtual void output () override
void output_min () override
void set_yaw_headroom (int16_t pwm)
void update_throttle_range ()
void update_throttle_hover (float dt)
virtual float get_throttle_hover () const override
void set_throttle_passthrough_for_esc_calibration (float throttle_input)
float get_throttle_thrust_max () const
bool spool_up_complete () const
virtual void output_motor_mask (float thrust, uint16_t mask, float rudder_dt)
virtual uint32_t get_motor_mask () override
int16_t get_pwm_output_min () const
int16_t get_pwm_output_max () const
bool check_mot_pwm_params () const
FUNCTOR_TYPEDEF (thrust_compensation_fn_t, void, float *, uint8_t)
void set_thrust_compensation_callback (thrust_compensation_fn_t callback)
virtual void disable_yaw_torque (void)
bool is_motor_enabled (uint8_t i) override
void convert_pwm_min_max_param (int16_t radio_min, int16_t radio_max)
bool arming_checks (size_t buflen, char *buffer) const override
float get_throttle_avg_max () const
int16_t get_yaw_headroom () const
Public Member Functions inherited from AP_Motors
const char * get_frame_string () const
void get_frame_and_type_string (char *buffer, uint8_t buflen) const
AP_Motors (uint16_t speed_hz=AP_MOTORS_SPEED_DEFAULT)
virtual bool motor_test_checks (size_t buflen, char *buffer) const
bool initialised_ok () const
void set_initialised_ok (bool val)
bool armed () const
void armed (bool arm)
void set_interlock (bool set)
bool get_interlock () const
bool get_spoolup_block () const
void set_spoolup_block (bool set)
void set_roll (float roll_in)
void set_roll_ff (float roll_in)
void set_pitch (float pitch_in)
void set_pitch_ff (float pitch_in)
void set_yaw (float yaw_in)
void set_yaw_ff (float yaw_in)
void set_throttle (float throttle_in)
void set_throttle_avg_max (float throttle_avg_max)
void set_throttle_filter_cutoff (float filt_hz)
void set_slew_filter_cutoff (float filt_hz)
void set_forward (float forward_in)
void set_lateral (float lateral_in)
virtual void set_roll_pitch (float roll_deg, float pitch_deg)
float get_roll () const
float get_roll_ff () const
float get_pitch () const
float get_pitch_ff () const
float get_yaw () const
float get_yaw_ff () const
float get_throttle_out () const
float get_throttle () const
float get_throttle_bidirectional () const
float get_throttle_slew_rate () const
float get_forward () const
float get_lateral () const
void set_thrust_boost (bool enable)
bool get_thrust_boost () const
virtual uint8_t get_lost_motor () const
void set_desired_spool_state (enum DesiredSpoolState spool)
enum DesiredSpoolState get_desired_spool_state (void) const
enum SpoolState get_spool_state (void) const
void set_dt (float dt)
float get_dt () const
void set_limit_flag_pitch_roll_yaw (bool flag)
virtual void set_update_rate (uint16_t speed_hz)
virtual void init (motor_frame_class frame_class, motor_frame_type frame_type)=0
virtual void set_frame_class_and_type (motor_frame_class frame_class, motor_frame_type frame_type)=0
void output_test_seq (uint8_t motor_seq, int16_t pwm)
void set_radio_passthrough (float roll_input, float pitch_input, float throttle_input, float yaw_input)
virtual float get_roll_factor (uint8_t i)
virtual float get_pitch_factor (uint8_t i)
virtual bool init_targets_on_arming () const
bool is_digital_pwm_type () const
bool is_brushed_pwm_type () const
bool is_normal_pwm_type () const
MAV_TYPE get_frame_mav_type () const
virtual void rc_write (uint8_t chan, uint16_t pwm)
bool has_option (MotorOptions option)
Public Attributes
Thrust_Linearization thr_lin {*this}
Public Attributes inherited from AP_Motors
struct AP_Motors::AP_Motors_limit limit
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Types
enum HoverLearn { HOVER_LEARN_DISABLED = 0 , HOVER_LEARN_ONLY = 1 , HOVER_LEARN_AND_SAVE = 2 }
Protected Types inherited from AP_Motors
enum pwm_type {
PWM_TYPE_NORMAL = 0 , PWM_TYPE_ONESHOT = 1 , PWM_TYPE_ONESHOT125 = 2 , PWM_TYPE_BRUSHED = 3 ,
PWM_TYPE_DSHOT150 = 4 , PWM_TYPE_DSHOT300 = 5 , PWM_TYPE_DSHOT600 = 6 , PWM_TYPE_DSHOT1200 = 7 ,
PWM_TYPE_PWM_RANGE = 8
}
Protected Member Functions
void output_logic ()
virtual void output_to_motors ()=0
virtual void update_throttle_filter () override
virtual float get_current_limit_max_throttle ()
int16_t output_to_pwm (float _actuator_output)
void set_actuator_with_slew (float &actuator_output, float input)
float actuator_spin_up_to_ground_idle () const
virtual void thrust_compensation (void)
virtual void output_boost_throttle (void)
virtual void output_rpyt (void)
void save_params_on_disarm () override
void update_external_limits ()
bool motor_enabled_mask (uint8_t i) const
Protected Member Functions inherited from AP_Motors
virtual void output_armed_stabilizing ()=0
virtual void rc_write_angle (uint8_t chan, int16_t angle_cd)
virtual void rc_set_freq (uint32_t mask, uint16_t freq_hz)
uint32_t motor_mask_to_srv_channel_mask (uint32_t mask) const
void add_motor_num (int8_t motor_num)
virtual const char * _get_frame_string () const =0
virtual const char * get_type_string () const
virtual void _output_test_seq (uint8_t motor_seq, int16_t pwm)=0
Protected Attributes
AP_Int16 _yaw_headroom
AP_Float _slew_up_time
AP_Float _slew_dn_time
AP_Float _safe_time
AP_Float _spin_arm
AP_Float _batt_current_max
AP_Float _batt_current_time_constant
AP_Int16 _pwm_min
AP_Int16 _pwm_max
AP_Float _throttle_hover
AP_Int8 _throttle_hover_learn
AP_Int8 _disarm_disable_pwm
AP_Float _yaw_servo_angle_max_deg
AP_Float _spool_up_time
AP_Float _spool_down_time
AP_Float _boost_scale
bool motor_enabled [AP_MOTORS_MAX_NUM_MOTORS]
float _spin_up_ratio
float _throttle_limit
float _throttle_thrust_max
float _disarm_safe_timer
thrust_compensation_fn_t _thrust_compensation_callback
float _actuator [AP_MOTORS_MAX_NUM_MOTORS]
uint16_t _motor_mask_override
Protected Attributes inherited from AP_Motors
float _dt
uint16_t _speed_hz
float _roll_in
float _roll_in_ff
float _pitch_in
float _pitch_in_ff
float _yaw_in
float _yaw_in_ff
float _throttle_in
float _throttle_out
float _throttle_slew_rate
float _forward_in
float _lateral_in
float _throttle_avg_max
LowPassFilterFloat _throttle_filter
DerivativeFilterFloat_Size7 _throttle_slew
LowPassFilterFloat _throttle_slew_filter
DesiredSpoolState _spool_desired
SpoolState _spool_state
uint32_t _motor_fast_mask
uint32_t _motor_pwm_range_mask
float _roll_radio_passthrough
float _pitch_radio_passthrough
float _throttle_radio_passthrough
float _yaw_radio_passthrough
AP_Int8 _pwm_type
bool _thrust_boost
bool _thrust_balanced
float _thrust_boost_ratio
AP_Int16 _options
MAV_TYPE _mav_type
Additional Inherited Members
Public Types inherited from AP_Motors
enum motor_frame_class {
MOTOR_FRAME_UNDEFINED = 0 , MOTOR_FRAME_QUAD = 1 , MOTOR_FRAME_HEXA = 2 , MOTOR_FRAME_OCTA = 3 ,
MOTOR_FRAME_OCTAQUAD = 4 , MOTOR_FRAME_Y6 = 5 , MOTOR_FRAME_HELI = 6 , MOTOR_FRAME_TRI = 7 ,
MOTOR_FRAME_SINGLE = 8 , MOTOR_FRAME_COAX = 9 , MOTOR_FRAME_TAILSITTER = 10 , MOTOR_FRAME_HELI_DUAL = 11 ,
MOTOR_FRAME_DODECAHEXA = 12 , MOTOR_FRAME_HELI_QUAD = 13 , MOTOR_FRAME_DECA = 14 , MOTOR_FRAME_SCRIPTING_MATRIX = 15 ,
MOTOR_FRAME_6DOF_SCRIPTING = 16 , MOTOR_FRAME_DYNAMIC_SCRIPTING_MATRIX = 17
}
enum motor_frame_type {
MOTOR_FRAME_TYPE_PLUS = 0 , MOTOR_FRAME_TYPE_X = 1 , MOTOR_FRAME_TYPE_V = 2 , MOTOR_FRAME_TYPE_H = 3 ,
MOTOR_FRAME_TYPE_VTAIL = 4 , MOTOR_FRAME_TYPE_ATAIL = 5 , MOTOR_FRAME_TYPE_PLUSREV = 6 , MOTOR_FRAME_TYPE_Y6B = 10 ,
MOTOR_FRAME_TYPE_Y6F = 11 , MOTOR_FRAME_TYPE_BF_X = 12 , MOTOR_FRAME_TYPE_DJI_X = 13 , MOTOR_FRAME_TYPE_CW_X = 14 ,
MOTOR_FRAME_TYPE_I = 15 , MOTOR_FRAME_TYPE_NYT_PLUS = 16 , MOTOR_FRAME_TYPE_NYT_X = 17 , MOTOR_FRAME_TYPE_BF_X_REV = 18 ,
MOTOR_FRAME_TYPE_Y4 = 19
}
enum class DesiredSpoolState : uint8_t { SHUT_DOWN = 0 , GROUND_IDLE = 1 , THROTTLE_UNLIMITED = 2 }
enum class SpoolState : uint8_t {
SHUT_DOWN = 0 , GROUND_IDLE = 1 , SPOOLING_UP = 2 , THROTTLE_UNLIMITED = 3 ,
SPOOLING_DOWN = 4
}
enum MotorOptions : uint8_t { BATT_RAW_VOLTAGE = (1 << 0U) }
Static Public Member Functions inherited from AP_Motors
static AP_Motors * get_singleton (void)
Detailed Description
Definition at line 28 of file AP_MotorsMulticopter.h.
Member Enumeration Documentation
HoverLearn
enum AP_MotorsMulticopter::HoverLearn protected
Enumerator
HOVER_LEARN_DISABLED
HOVER_LEARN_ONLY
HOVER_LEARN_AND_SAVE
Definition at line 149 of file AP_MotorsMulticopter.h.
Constructor & Destructor Documentation
AP_MotorsMulticopter()
AP_MotorsMulticopter::AP_MotorsMulticopter (uint16_t speed_hz = AP_MOTORS_SPEED_DEFAULT)
Definition at line 238 of file AP_MotorsMulticopter.cpp.
Member Function Documentation
actuator_spin_up_to_ground_idle()
float AP_MotorsMulticopter::actuator_spin_up_to_ground_idle () const protected
Definition at line 455 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsCoax::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsTailsitter::output_to_motors(), and AP_MotorsTri::output_to_motors().
arming_checks()
bool AP_MotorsMulticopter::arming_checks (size_t buflen, char * buffer) const override virtual
Reimplemented from AP_Motors.
Reimplemented in AP_MotorsSingle, and AP_MotorsTri.
Definition at line 781 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsTri::arming_checks().
check_mot_pwm_params()
bool AP_MotorsMulticopter::check_mot_pwm_params () const
Definition at line 461 of file AP_MotorsMulticopter.cpp.
Referenced by arming_checks().
convert_pwm_min_max_param()
void AP_MotorsMulticopter::convert_pwm_min_max_param (int16_t radio_min, int16_t radio_max)
Definition at line 772 of file AP_MotorsMulticopter.cpp.
disable_yaw_torque()
virtual void AP_MotorsMulticopter::disable_yaw_torque (void) inline virtual
Reimplemented in AP_MotorsMatrix.
Definition at line 84 of file AP_MotorsMulticopter.h.
FUNCTOR_TYPEDEF()
AP_MotorsMulticopter::FUNCTOR_TYPEDEF (thrust_compensation_fn_t , void , float * , uint8_t)
get_current_limit_max_throttle()
float AP_MotorsMulticopter::get_current_limit_max_throttle () protected virtual
Reimplemented in AP_Motors6DOF.
Definition at line 348 of file AP_MotorsMulticopter.cpp.
Referenced by output_logic().
get_motor_mask()
uint32_t AP_MotorsMulticopter::get_motor_mask () override virtual
Implements AP_Motors.
Reimplemented in AP_MotorsCoax, AP_MotorsMatrix, AP_MotorsSingle, AP_MotorsTailsitter, and AP_MotorsTri.
Definition at line 757 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsCoax::get_motor_mask(), AP_MotorsMatrix::get_motor_mask(), AP_MotorsSingle::get_motor_mask(), AP_MotorsTailsitter::get_motor_mask(), AP_MotorsTri::get_motor_mask(), and update_throttle_range().
get_pwm_output_max()
int16_t AP_MotorsMulticopter::get_pwm_output_max () const inline
Definition at line 71 of file AP_MotorsMulticopter.h.
Referenced by AP_Motors6DOF::calc_thrust_to_pwm(), output_motor_mask(), output_to_pwm(), set_throttle_passthrough_for_esc_calibration(), and update_throttle_range().
get_pwm_output_min()
int16_t AP_MotorsMulticopter::get_pwm_output_min () const inline
Definition at line 70 of file AP_MotorsMulticopter.h.
Referenced by AP_Motors6DOF::calc_thrust_to_pwm(), output_motor_mask(), output_to_pwm(), set_throttle_passthrough_for_esc_calibration(), and update_throttle_range().
get_throttle_avg_max()
float AP_MotorsMulticopter::get_throttle_avg_max () const
Referenced by stability_test().
get_throttle_hover()
virtual float AP_MotorsMulticopter::get_throttle_hover () const inline override virtual
Implements AP_Motors.
Definition at line 48 of file AP_MotorsMulticopter.h.
Referenced by get_current_limit_max_throttle().
get_throttle_thrust_max()
float AP_MotorsMulticopter::get_throttle_thrust_max () const inline
Definition at line 55 of file AP_MotorsMulticopter.h.
Referenced by AC_AttitudeControl_Multi::update_althold_lean_angle_max(), and AC_AttitudeControl_Sub::update_althold_lean_angle_max().
get_yaw_headroom()
int16_t AP_MotorsMulticopter::get_yaw_headroom () const
Referenced by stability_test().
is_motor_enabled()
bool AP_MotorsMulticopter::is_motor_enabled (uint8_t i) inline override virtual
Reimplemented from AP_Motors.
Definition at line 87 of file AP_MotorsMulticopter.h.
motor_enabled_mask()
bool AP_MotorsMulticopter::motor_enabled_mask (uint8_t i) const inline protected
Definition at line 199 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsMatrix::output_to_motors(), and AP_MotorsTri::output_to_motors().
output()
void AP_MotorsMulticopter::output () override virtual
Implements AP_Motors.
Definition at line 246 of file AP_MotorsMulticopter.cpp.
Referenced by output_min().
output_boost_throttle()
void AP_MotorsMulticopter::output_boost_throttle (void) protected virtual
Definition at line 291 of file AP_MotorsMulticopter.cpp.
Referenced by output().
output_logic()
void AP_MotorsMulticopter::output_logic () protected
Definition at line 495 of file AP_MotorsMulticopter.cpp.
Referenced by output().
output_min()
void AP_MotorsMulticopter::output_min () override virtual
Implements AP_Motors.
Definition at line 311 of file AP_MotorsMulticopter.cpp.
output_motor_mask()
void AP_MotorsMulticopter::output_motor_mask (float thrust, uint16_t mask, float rudder_dt) virtual
Reimplemented in AP_MotorsTri.
Definition at line 728 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsTri::output_motor_mask().
output_rpyt()
void AP_MotorsMulticopter::output_rpyt (void) protected virtual
Definition at line 302 of file AP_MotorsMulticopter.cpp.
Referenced by output().
output_to_motors()
virtual void AP_MotorsMulticopter::output_to_motors () protected pure virtual
Implemented in AP_Motors6DOF, AP_MotorsCoax, AP_MotorsMatrix, AP_MotorsSingle, AP_MotorsTailsitter, AP_MotorsTri, and AP_MotorsMulticopter_test.
Referenced by output().
output_to_pwm()
int16_t AP_MotorsMulticopter::output_to_pwm (float _actuator_output) protected
Definition at line 406 of file AP_MotorsMulticopter.cpp.
Referenced by AP_MotorsCoax::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsTailsitter::output_to_motors(), and AP_MotorsTri::output_to_motors().
save_params_on_disarm()
void AP_MotorsMulticopter::save_params_on_disarm () override protected virtual
Reimplemented from AP_Motors.
Definition at line 763 of file AP_MotorsMulticopter.cpp.
set_actuator_with_slew()
void AP_MotorsMulticopter::set_actuator_with_slew (float & actuator_output, float input) protected
Definition at line 425 of file AP_MotorsMulticopter.cpp.
Referenced by output_motor_mask(), AP_MotorsCoax::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsTailsitter::output_to_motors(), and AP_MotorsTri::output_to_motors().
set_throttle_passthrough_for_esc_calibration()
void AP_MotorsMulticopter::set_throttle_passthrough_for_esc_calibration (float throttle_input)
Definition at line 709 of file AP_MotorsMulticopter.cpp.
set_thrust_compensation_callback()
void AP_MotorsMulticopter::set_thrust_compensation_callback (thrust_compensation_fn_t callback) inline
Definition at line 78 of file AP_MotorsMulticopter.h.
set_yaw_headroom()
void AP_MotorsMulticopter::set_yaw_headroom (int16_t pwm) inline
Definition at line 41 of file AP_MotorsMulticopter.h.
Referenced by setup().
spool_up_complete()
bool AP_MotorsMulticopter::spool_up_complete () const inline
Definition at line 58 of file AP_MotorsMulticopter.h.
thrust_compensation()
virtual void AP_MotorsMulticopter::thrust_compensation (void) inline protected virtual
Reimplemented in AP_MotorsMatrix, and AP_MotorsTri.
Definition at line 134 of file AP_MotorsMulticopter.h.
Referenced by output().
update_external_limits()
void AP_MotorsMulticopter::update_external_limits () protected
Definition at line 279 of file AP_MotorsMulticopter.cpp.
Referenced by output().
update_throttle_filter()
void AP_MotorsMulticopter::update_throttle_filter () override protected virtual
Implements AP_Motors.
Definition at line 319 of file AP_MotorsMulticopter.cpp.
Referenced by output().
update_throttle_hover()
void AP_MotorsMulticopter::update_throttle_hover (float dt)
Definition at line 486 of file AP_MotorsMulticopter.cpp.
update_throttle_range()
void AP_MotorsMulticopter::update_throttle_range ()
Definition at line 473 of file AP_MotorsMulticopter.cpp.
Referenced by setup().
Member Data Documentation
_actuator
float AP_MotorsMulticopter::_actuator[AP_MOTORS_MAX_NUM_MOTORS] protected
Definition at line 194 of file AP_MotorsMulticopter.h.
Referenced by output_motor_mask(), AP_MotorsCoax::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsTailsitter::output_to_motors(), and AP_MotorsTri::output_to_motors().
_batt_current_max
AP_Float AP_MotorsMulticopter::_batt_current_max protected
Definition at line 161 of file AP_MotorsMulticopter.h.
Referenced by get_current_limit_max_throttle(), and AP_Motors6DOF::output_armed_stabilizing().
_batt_current_time_constant
AP_Float AP_MotorsMulticopter::_batt_current_time_constant protected
Definition at line 162 of file AP_MotorsMulticopter.h.
Referenced by get_current_limit_max_throttle(), and AP_Motors6DOF::output_armed_stabilizing().
_boost_scale
AP_Float AP_MotorsMulticopter::_boost_scale protected
Definition at line 177 of file AP_MotorsMulticopter.h.
Referenced by output_boost_throttle().
_disarm_disable_pwm
AP_Int8 AP_MotorsMulticopter::_disarm_disable_pwm protected
Definition at line 167 of file AP_MotorsMulticopter.h.
Referenced by output_logic(), and output_to_pwm().
_disarm_safe_timer
float AP_MotorsMulticopter::_disarm_safe_timer protected
Definition at line 188 of file AP_MotorsMulticopter.h.
Referenced by output_logic().
_motor_mask_override
uint16_t AP_MotorsMulticopter::_motor_mask_override protected
Definition at line 204 of file AP_MotorsMulticopter.h.
Referenced by motor_enabled_mask(), output(), and output_motor_mask().
_pwm_max
AP_Int16 AP_MotorsMulticopter::_pwm_max protected
Definition at line 164 of file AP_MotorsMulticopter.h.
Referenced by check_mot_pwm_params(), convert_pwm_min_max_param(), get_pwm_output_max(), and update_throttle_range().
_pwm_min
AP_Int16 AP_MotorsMulticopter::_pwm_min protected
Definition at line 163 of file AP_MotorsMulticopter.h.
Referenced by convert_pwm_min_max_param(), get_pwm_output_min(), and update_throttle_range().
_safe_time
AP_Float AP_MotorsMulticopter::_safe_time protected
Definition at line 159 of file AP_MotorsMulticopter.h.
Referenced by output_logic().
_slew_dn_time
AP_Float AP_MotorsMulticopter::_slew_dn_time protected
Definition at line 158 of file AP_MotorsMulticopter.h.
Referenced by set_actuator_with_slew().
_slew_up_time
AP_Float AP_MotorsMulticopter::_slew_up_time protected
Definition at line 157 of file AP_MotorsMulticopter.h.
Referenced by set_actuator_with_slew().
_spin_arm
AP_Float AP_MotorsMulticopter::_spin_arm protected
Definition at line 160 of file AP_MotorsMulticopter.h.
Referenced by arming_checks(), and output_logic().
_spin_up_ratio
float AP_MotorsMulticopter::_spin_up_ratio protected
Definition at line 183 of file AP_MotorsMulticopter.h.
Referenced by actuator_spin_up_to_ground_idle(), output_logic(), AP_MotorsCoax::output_to_motors(), and AP_MotorsSingle::output_to_motors().
_spool_down_time
AP_Float AP_MotorsMulticopter::_spool_down_time protected
Definition at line 174 of file AP_MotorsMulticopter.h.
Referenced by output_logic().
_spool_up_time
AP_Float AP_MotorsMulticopter::_spool_up_time protected
Definition at line 173 of file AP_MotorsMulticopter.h.
Referenced by output_logic().
_throttle_hover
AP_Float AP_MotorsMulticopter::_throttle_hover protected
Definition at line 165 of file AP_MotorsMulticopter.h.
Referenced by get_throttle_hover(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), save_params_on_disarm(), and update_throttle_hover().
_throttle_hover_learn
AP_Int8 AP_MotorsMulticopter::_throttle_hover_learn protected
Definition at line 166 of file AP_MotorsMulticopter.h.
Referenced by save_params_on_disarm(), and update_throttle_hover().
_throttle_limit
float AP_MotorsMulticopter::_throttle_limit protected
Definition at line 186 of file AP_MotorsMulticopter.h.
Referenced by get_current_limit_max_throttle().
_throttle_thrust_max
float AP_MotorsMulticopter::_throttle_thrust_max protected
Definition at line 187 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsMatrix::check_for_failed_motor(), get_throttle_thrust_max(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), and output_logic().
_thrust_compensation_callback
thrust_compensation_fn_t AP_MotorsMulticopter::_thrust_compensation_callback protected
Definition at line 191 of file AP_MotorsMulticopter.h.
Referenced by set_thrust_compensation_callback(), AP_MotorsMatrix::thrust_compensation(), and AP_MotorsTri::thrust_compensation().
_yaw_headroom
AP_Int16 AP_MotorsMulticopter::_yaw_headroom protected
Definition at line 156 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), and set_yaw_headroom().
_yaw_servo_angle_max_deg
AP_Float AP_MotorsMulticopter::_yaw_servo_angle_max_deg protected
Definition at line 170 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsTri::init(), and AP_MotorsTri::output_armed_stabilizing().
motor_enabled
bool AP_MotorsMulticopter::motor_enabled[AP_MOTORS_MAX_NUM_MOTORS] protected
Definition at line 180 of file AP_MotorsMulticopter.h.
Referenced by AP_MotorsMatrix::_output_test_seq(), AP_MotorsMatrix::add_motor_raw(), arming_checks(), AP_MotorsMatrix::check_for_failed_motor(), AP_MotorsMatrix::get_motor_mask(), AP_MotorsCoax::init(), AP_MotorsSingle::init(), AP_MotorsTri::init(), is_motor_enabled(), motor_enabled_mask(), AP_Motors6DOF::motor_is_enabled(), AP_MotorsMatrix::normalise_rpy_factors(), AP_Motors6DOF::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), AP_Motors6DOF::output_min(), output_motor_mask(), AP_MotorsMatrix::output_test_num(), AP_Motors6DOF::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsMatrix::remove_motor(), set_throttle_passthrough_for_esc_calibration(), and AP_MotorsMatrix::set_update_rate().
thr_lin
Thrust_Linearization AP_MotorsMulticopter::thr_lin {*this}
Definition at line 105 of file AP_MotorsMulticopter.h.
Referenced by actuator_spin_up_to_ground_idle(), arming_checks(), AP_MotorsMatrix::check_for_failed_motor(), get_current_limit_max_throttle(), output(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsTailsitter::output_armed_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), output_logic(), AP_MotorsCoax::output_to_motors(), AP_MotorsMatrix::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsTailsitter::output_to_motors(), AP_MotorsTri::output_to_motors(), AP_MotorsMulticopter_test::set_expo(), and setup().
var_info
const AP_Param::GroupInfo AP_MotorsMulticopter::var_info static
Definition at line 32 of file AP_MotorsMulticopter.h.
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_MotorsMulticopter.h
libraries/AP_Motors/AP_MotorsMulticopter.cpp