APM:Libraries: Display Class Reference
Display Class Reference
#include <Display.h>
Public Member Functions
bool init (void) override
void update () override
void send_text_blocking (const char *text, uint8_t line) override
void release_text (uint8_t line) override
Public Member Functions inherited from NotifyDevice
virtual ~NotifyDevice ()
virtual void play_tune (const char *tune)
virtual void rgb_control (uint8_t r, uint8_t g, uint8_t b, uint8_t rate_hz)
virtual void rgb_set_id (uint8_t r, uint8_t g, uint8_t b, uint8_t id)
Private Member Functions
void draw_char (uint16_t x, uint16_t y, const char c)
void draw_text (uint16_t x, uint16_t y, const char *c)
void update_all ()
void update_arm (uint8_t r)
void update_prearm (uint8_t r)
void update_gps (uint8_t r)
void update_gps_sats (uint8_t r)
void update_ekf (uint8_t r)
void update_battery (uint8_t r)
void update_mode (uint8_t r)
void update_text (uint8_t r)
void update_text_empty (uint8_t r)
Private Attributes
Display_Backend * _driver
uint8_t _mstartpos
uint8_t _movedelay
uint8_t _screenpage
const uint16_t _send_text_valid_millis = 20000
uint8_t _send_text_scr_override
Friends
class Display_Backend
Additional Inherited Members
Public Attributes inherited from NotifyDevice
const AP_Notify * pNotify
Detailed Description
Definition at line 17 of file Display.h.
Member Function Documentation
draw_char()
void Display::draw_char (uint16_t x, uint16_t y, const char c) private
Definition at line 477 of file Display.cpp.
Referenced by draw_text().
draw_text()
void Display::draw_text (uint16_t x, uint16_t y, const char * c) private
Definition at line 456 of file Display.cpp.
Referenced by send_text_blocking(), update_arm(), update_ekf(), update_mode(), update_prearm(), update_text(), and update_text_empty().
init()
bool Display::init (void) override virtual
Implements NotifyDevice.
Definition at line 330 of file Display.cpp.
release_text()
void Display::release_text (uint8_t line) override virtual
Reimplemented from NotifyDevice.
Definition at line 451 of file Display.cpp.
send_text_blocking()
void Display::send_text_blocking (const char * text, uint8_t line) override virtual
Reimplemented from NotifyDevice.
Definition at line 436 of file Display.cpp.
update()
void Display::update (void) override virtual
Implements NotifyDevice.
Definition at line 376 of file Display.cpp.
update_all()
void Display::update_all () private
Definition at line 405 of file Display.cpp.
Referenced by init(), and update().
update_arm()
void Display::update_arm (uint8_t r) private
Definition at line 500 of file Display.cpp.
Referenced by update().
update_battery()
void Display::update_battery (uint8_t r) private
Referenced by update_all().
update_ekf()
void Display::update_ekf (uint8_t r) private
Definition at line 562 of file Display.cpp.
Referenced by update_all().
update_gps()
void Display::update_gps (uint8_t r) private
Referenced by update_all().
update_gps_sats()
void Display::update_gps_sats (uint8_t r) private
update_mode()
void Display::update_mode (uint8_t r) private
Definition at line 586 of file Display.cpp.
Referenced by update_all().
update_prearm()
void Display::update_prearm (uint8_t r) private
Definition at line 509 of file Display.cpp.
Referenced by update_all().
update_text()
void Display::update_text (uint8_t r) private
Definition at line 604 of file Display.cpp.
Referenced by update_all().
update_text_empty()
void Display::update_text_empty (uint8_t r) private
Definition at line 595 of file Display.cpp.
Referenced by update_text().
Friends And Related Symbol Documentation
Display_Backend
friend class Display_Backend friend
Definition at line 19 of file Display.h.
Member Data Documentation
_driver
Display_Backend* Display::_driver private
Definition at line 39 of file Display.h.
Referenced by draw_char(), init(), and update().
_movedelay
uint8_t Display::_movedelay private
Definition at line 42 of file Display.h.
Referenced by update_text(), and update_text_empty().
_mstartpos
uint8_t Display::_mstartpos private
Definition at line 41 of file Display.h.
Referenced by update_text(), and update_text_empty().
_screenpage
uint8_t Display::_screenpage private
Definition at line 43 of file Display.h.
Referenced by update().
_send_text_scr_override
uint8_t Display::_send_text_scr_override private
Definition at line 49 of file Display.h.
Referenced by release_text(), send_text_blocking(), and update_all().
_send_text_valid_millis
const uint16_t Display::_send_text_valid_millis = 20000 private
Definition at line 46 of file Display.h.
Referenced by update_text().
The documentation for this class was generated from the following files:
libraries/AP_Notify/Display.h
libraries/AP_Notify/Display.cpp