APM:Libraries: AP_Frsky_MAVlite_Message Class Reference
AP_Frsky_MAVlite_Message Class Reference
#include <AP_Frsky_MAVlite_Message.h>
Public Member Functions
bool get_float (float &value, const uint8_t offset) const WARN_IF_UNUSED
bool set_float (const float value, const uint8_t offset) WARN_IF_UNUSED
bool get_string (char *value, const uint8_t offset) const WARN_IF_UNUSED
bool set_string (const char *value, const uint8_t offset) WARN_IF_UNUSED
bool get_uint16 (uint16_t &value, const uint8_t offset) const WARN_IF_UNUSED
bool set_uint16 (const uint16_t value, const uint8_t offset) WARN_IF_UNUSED
bool get_uint8 (uint8_t &value, const uint8_t offset) const WARN_IF_UNUSED
bool set_uint8 (const uint8_t value, const uint8_t offset) WARN_IF_UNUSED
Static Public Member Functions
static void bit8_pack (uint8_t &value, const uint8_t bit_value, const uint8_t bit_count, const uint8_t bit_offset)
static uint8_t bit8_unpack (const uint8_t value, const uint8_t bit_count, const uint8_t bit_offset)
Public Attributes
uint8_t msgid = 0
uint8_t len = 0
uint8_t payload [MAVLITE_MAX_PAYLOAD_LEN]
Private Member Functions
bool get_bytes (uint8_t *bytes, const uint8_t offset, const uint8_t count) const WARN_IF_UNUSED
bool set_bytes (const uint8_t *bytes, const uint8_t offset, const uint8_t count) WARN_IF_UNUSED
Detailed Description
Definition at line 10 of file AP_Frsky_MAVlite_Message.h.
Member Function Documentation
bit8_pack()
void AP_Frsky_MAVlite_Message::bit8_pack (uint8_t & value, const uint8_t bit_value, const uint8_t bit_count, const uint8_t bit_offset) static
Definition at line 49 of file AP_Frsky_MAVlite_Message.cpp.
bit8_unpack()
uint8_t AP_Frsky_MAVlite_Message::bit8_unpack (const uint8_t value, const uint8_t bit_count, const uint8_t bit_offset) static
Definition at line 40 of file AP_Frsky_MAVlite_Message.cpp.
Referenced by AP_Frsky_MAVliteMsgHandler::handle_command_long().
get_bytes()
bool AP_Frsky_MAVlite_Message::get_bytes (uint8_t * bytes, const uint8_t offset, const uint8_t count) const private
Definition at line 6 of file AP_Frsky_MAVlite_Message.cpp.
Referenced by get_float(), get_string(), get_uint16(), and get_uint8().
get_float()
bool AP_Frsky_MAVlite_Message::get_float (float & value, const uint8_t offset) const inline
Definition at line 13 of file AP_Frsky_MAVlite_Message.h.
Referenced by AP_Frsky_MAVliteMsgHandler::handle_command_long(), and AP_Frsky_MAVliteMsgHandler::handle_param_set().
get_string()
bool AP_Frsky_MAVlite_Message::get_string (char * value, const uint8_t offset) const
Definition at line 25 of file AP_Frsky_MAVlite_Message.cpp.
Referenced by AP_Frsky_MAVliteMsgHandler::handle_param_request_read(), and AP_Frsky_MAVliteMsgHandler::handle_param_set().
get_uint16()
bool AP_Frsky_MAVlite_Message::get_uint16 (uint16_t & value, const uint8_t offset) const inline
Definition at line 23 of file AP_Frsky_MAVlite_Message.h.
Referenced by AP_Frsky_MAVliteMsgHandler::handle_command_long().
get_uint8()
bool AP_Frsky_MAVlite_Message::get_uint8 (uint8_t & value, const uint8_t offset) const inline
Definition at line 30 of file AP_Frsky_MAVlite_Message.h.
Referenced by AP_Frsky_MAVliteMsgHandler::handle_command_long().
set_bytes()
bool AP_Frsky_MAVlite_Message::set_bytes (const uint8_t * bytes, const uint8_t offset, const uint8_t count) private
Definition at line 15 of file AP_Frsky_MAVlite_Message.cpp.
Referenced by set_float(), set_string(), set_uint16(), and set_uint8().
set_float()
bool AP_Frsky_MAVlite_Message::set_float (const float value, const uint8_t offset) inline
Definition at line 16 of file AP_Frsky_MAVlite_Message.h.
Referenced by AP_Frsky_MAVliteMsgHandler::handle_param_request_read(), and AP_Frsky_MAVliteMsgHandler::handle_param_set().
set_string()
bool AP_Frsky_MAVlite_Message::set_string (const char * value, const uint8_t offset)
Definition at line 34 of file AP_Frsky_MAVlite_Message.cpp.
Referenced by AP_Frsky_MAVliteMsgHandler::handle_param_request_read(), and AP_Frsky_MAVliteMsgHandler::handle_param_set().
set_uint16()
bool AP_Frsky_MAVlite_Message::set_uint16 (const uint16_t value, const uint8_t offset) inline
Definition at line 26 of file AP_Frsky_MAVlite_Message.h.
Referenced by AP_Frsky_MAVliteMsgHandler::send_command_ack().
set_uint8()
bool AP_Frsky_MAVlite_Message::set_uint8 (const uint8_t value, const uint8_t offset) inline
Definition at line 33 of file AP_Frsky_MAVlite_Message.h.
Referenced by AP_Frsky_MAVliteMsgHandler::send_command_ack().
Member Data Documentation
len
uint8_t AP_Frsky_MAVlite_Message::len = 0
Definition at line 38 of file AP_Frsky_MAVlite_Message.h.
Referenced by get_string(), AP_Frsky_MAVlite_SPortToMAVlite::parse(), AP_Frsky_MAVlite_MAVliteToSPort::process(), and set_bytes().
msgid
uint8_t AP_Frsky_MAVlite_Message::msgid = 0
Definition at line 37 of file AP_Frsky_MAVlite_Message.h.
Referenced by AP_Frsky_MAVliteMsgHandler::handle_param_request_read(), AP_Frsky_MAVliteMsgHandler::handle_param_set(), AP_Frsky_MAVlite_SPortToMAVlite::parse(), AP_Frsky_MAVlite_MAVliteToSPort::process(), AP_Frsky_MAVliteMsgHandler::process_message(), and AP_Frsky_MAVliteMsgHandler::send_command_ack().
payload
uint8_t AP_Frsky_MAVlite_Message::payload[MAVLITE_MAX_PAYLOAD_LEN]
Definition at line 39 of file AP_Frsky_MAVlite_Message.h.
Referenced by get_bytes(), AP_Frsky_MAVlite_SPortToMAVlite::parse(), AP_Frsky_MAVlite_MAVliteToSPort::process(), and set_bytes().
The documentation for this class was generated from the following files:
libraries/AP_Frsky_Telem/AP_Frsky_MAVlite_Message.h
libraries/AP_Frsky_Telem/AP_Frsky_MAVlite_Message.cpp