APM:Libraries: AC_PosControl Class Reference
AC_PosControl Class Reference
#include <AC_PosControl.h>
Public Member Functions
AC_PosControl (AP_AHRS_View &ahrs, const AP_InertialNav &inav, const class AP_Motors &motors, AC_AttitudeControl &attitude_control)
Constructor.
void set_dt (float dt)
float get_dt () const
float get_shaping_jerk_xy_cmsss () const
get_shaping_jerk_xy_cmsss - gets the jerk limit of the xy kinematic path generation in cm/s/s/s
void input_pos_xyz (const Vector3p &pos, float pos_offset_z, float pos_offset_z_buffer)
float pos_offset_z_scaler (float pos_offset_z, float pos_offset_z_buffer) const
pos_offset_z_scaler - calculates a multiplier used to reduce the horizontal velocity to allow the z position controller to stay within the provided buffer range
void set_max_speed_accel_xy (float speed_cms, float accel_cmss)
void set_correction_speed_accel_xy (float speed_cms, float accel_cmss)
float get_max_speed_xy_cms () const
get_max_speed_xy_cms - get the maximum horizontal speed in cm/s
float get_max_accel_xy_cmss () const
get_max_accel_xy_cmss - get the maximum horizontal acceleration in cm/s/s
void set_pos_error_max_xy_cm (float error_max)
float get_pos_error_max_xy_cm ()
void init_xy_controller_stopping_point ()
void relax_velocity_controller_xy ()
This function decays the output acceleration by 95% every half second to achieve a smooth transition to zero requested acceleration.
void soften_for_landing_xy ()
reduce response for landing
void init_xy_controller ()
void input_accel_xy (const Vector3f &accel)
void input_vel_accel_xy (Vector2f &vel, const Vector2f &accel, bool limit_output=true)
void input_pos_vel_accel_xy (Vector2p &pos, Vector2f &vel, const Vector2f &accel, bool limit_output=true)
bool is_active_xy () const
void stop_pos_xy_stabilisation ()
stop_pos_xy_stabilisation - sets the target to the current position to remove any position corrections from the system
void stop_vel_xy_stabilisation ()
stop_vel_xy_stabilisation - sets the target to the current position and velocity to the current velocity to remove any position and velocity corrections from the system
void update_xy_controller ()
void set_max_speed_accel_z (float speed_down, float speed_up, float accel_cmss)
void set_correction_speed_accel_z (float speed_down, float speed_up, float accel_cmss)
float get_max_accel_z_cmss () const
get_max_accel_z_cmss - get the maximum vertical acceleration in cm/s/s
float get_pos_error_z_up_cm ()
float get_pos_error_z_down_cm ()
float get_max_speed_up_cms () const
get_max_speed_up_cms - accessors for current maximum up speed in cm/s
float get_max_speed_down_cms () const
get_max_speed_down_cms - accessors for current maximum down speed in cm/s. Will be a negative number
void init_z_controller_no_descent ()
void init_z_controller_stopping_point ()
void relax_z_controller (float throttle_setting)
This function decays the output acceleration by 95% every half second to achieve a smooth transition to zero requested acceleration.
void init_z_controller ()
virtual void input_accel_z (float accel)
virtual void input_vel_accel_z (float &vel, float accel, bool limit_output=true)
void set_pos_target_z_from_climb_rate_cm (float vel)
void land_at_climb_rate_cm (float vel, bool ignore_descent_limit)
void input_pos_vel_accel_z (float &pos, float &vel, float accel, bool limit_output=true)
void set_alt_target_with_slew (float pos)
void update_pos_offset_z (float pos_offset)
update_pos_offset_z - updates the vertical offsets used by terrain following
bool is_active_z () const
void update_z_controller ()
void set_pos_vel_accel (const Vector3p &pos, const Vector3f &vel, const Vector3f &accel)
set commanded position (cm), velocity (cm/s) and acceleration (cm/s/s) inputs when the path is created externally.
void set_pos_vel_accel_xy (const Vector2p &pos, const Vector2f &vel, const Vector2f &accel)
set position, velocity and acceleration targets
void set_pos_target_xy_cm (float pos_x, float pos_y)
Position.
const Vector3p & get_pos_target_cm () const
get_pos_target_cm - returns the position target, frame NEU in cm relative to the EKF origin
void set_pos_target_z_cm (float pos_target)
set_pos_target_z_cm - set altitude target in cm above the EKF origin
float get_pos_target_z_cm () const
get_pos_target_z_cm - get target altitude (in cm above the EKF origin)
void get_stopping_point_xy_cm (Vector2p &stopping_point) const
get_stopping_point_xy_cm - calculates stopping point in NEU cm based on current position, velocity, vehicle acceleration
void get_stopping_point_z_cm (postype_t &stopping_point) const
get_stopping_point_z_cm - calculates stopping point in NEU cm based on current position, velocity, vehicle acceleration
const Vector3f get_pos_error_cm () const
get_pos_error_cm - get position error vector between the current and target position
float get_pos_error_xy_cm () const
get_pos_error_xy_cm - get the length of the position error vector in the xy plane
float get_pos_error_z_cm () const
get_pos_error_z_cm - returns altitude error in cm
void set_vel_desired_cms (const Vector3f &des_vel)
Velocity.
void set_vel_desired_xy_cms (const Vector2f &vel)
set_vel_desired_xy_cms - sets horizontal desired velocity in NEU cm/s
const Vector3f & get_vel_desired_cms ()
get_vel_desired_cms - returns desired velocity (i.e. feed forward) in cm/s in NEU
const Vector3f & get_vel_target_cms () const
void set_vel_desired_z_cms (float vel_z_cms)
set_vel_desired_z_cms - sets desired velocity in cm/s in z axis
float get_vel_target_z_cms () const
get_vel_target_z_cms - returns target vertical speed in cm/s
void set_accel_desired_xy_cmss (const Vector2f &accel_cms)
Acceleration.
const Vector3f & get_accel_target_cmss () const
void set_pos_offset_target_z_cm (float pos_offset_target_z)
Offset.
void set_pos_offset_z_cm (float pos_offset_z)
set_pos_offset_z_cm - set altitude offset in cm above the EKF origin
float get_pos_offset_z_cm () const
get_pos_offset_z_cm - returns altitude offset in cm above the EKF origin
float get_vel_offset_z_cms () const
get_vel_offset_z_cm - returns current vertical offset speed in cm/s
float get_accel_offset_z_cmss () const
get_accel_offset_z_cm - returns current vertical offset acceleration in cm/s/s
float get_roll_cd () const
Outputs.
float get_pitch_cd () const
float get_yaw_cd () const
get desired yaw to be passed to the attitude controller
float get_yaw_rate_cds () const
get desired yaw rate to be passed to the attitude controller
Vector3f get_thrust_vector () const
get desired roll and pitch to be passed to the attitude controller
int32_t get_bearing_to_target_cd () const
get_bearing_to_target_cd - get bearing to target position in centi-degrees
float get_lean_angle_max_cd () const
get_lean_angle_max_cd - returns the maximum lean angle the autopilot may request
void set_lean_angle_max_cd (float angle_max_cd)
AC_P_2D & get_pos_xy_p ()
Other.
AC_P_1D & get_pos_z_p ()
AC_PID_2D & get_vel_xy_pid ()
AC_PID_Basic & get_vel_z_pid ()
AC_PID & get_accel_z_pid ()
void set_externally_limited_xy ()
Vector3f lean_angles_to_accel (const Vector3f &att_target_euler) const
void write_log ()
bool pre_arm_checks (const char *param_prefix, char *failure_msg, const uint8_t failure_msg_len)
void set_vibe_comp (bool on_off)
float get_vel_z_control_ratio () const
get_vel_z_error_ratio - returns the proportion of error relative to the maximum request
float crosstrack_error () const
crosstrack_error - returns horizontal error to the closest point to the current track
void standby_xyz_reset ()
float get_z_accel_cmss () const
bool get_fwd_pitch_is_limited () const
returns true when the forward pitch demand is limited by the maximum allowed tilt
Static Public Member Functions
static void Write_PSCN (float pos_target, float pos, float vel_desired, float vel_target, float vel, float accel_desired, float accel_target, float accel)
static void Write_PSCE (float pos_target, float pos, float vel_desired, float vel_target, float vel, float accel_desired, float accel_target, float accel)
static void Write_PSCD (float pos_target, float pos, float vel_desired, float vel_target, float vel, float accel_desired, float accel_target, float accel)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
float get_throttle_with_vibration_override ()
void accel_to_lean_angles (float accel_x_cmss, float accel_y_cmss, float &roll_target, float &pitch_target) const
void lean_angles_to_accel_xy (float &accel_x_cmss, float &accel_y_cmss) const
bool calculate_yaw_and_rate_yaw ()
float calculate_overspeed_gain ()
void init_ekf_xy_reset ()
initialise and check for ekf position resets
void handle_ekf_xy_reset ()
handle_ekf_xy_reset - check for ekf position reset and adjust loiter or brake target position
void init_ekf_z_reset ()
initialise ekf z axis reset check
void handle_ekf_z_reset ()
handle_ekf_z_reset - check for ekf position reset and adjust loiter or brake target position
bool has_good_timing (void) const
Protected Attributes
AP_AHRS_View & _ahrs
const AP_InertialNav & _inav
const class AP_Motors & _motors
AC_AttitudeControl & _attitude_control
AP_Float _lean_angle_max
AP_Float _shaping_jerk_xy
AP_Float _shaping_jerk_z
AC_P_2D _p_pos_xy
AC_P_1D _p_pos_z
AC_PID_2D _pid_vel_xy
AC_PID_Basic _pid_vel_z
AC_PID _pid_accel_z
float _dt
uint32_t _last_update_xy_ticks
uint32_t _last_update_z_ticks
float _vel_max_xy_cms
float _vel_max_up_cms
float _vel_max_down_cms
float _accel_max_xy_cmss
float _accel_max_z_cmss
float _jerk_max_xy_cmsss
float _jerk_max_z_cmsss
float _vel_z_control_ratio = 2.0f
float _roll_target
float _pitch_target
float _yaw_target
float _yaw_rate_target
Vector3p _pos_target
Vector3f _vel_desired
Vector3f _vel_target
Vector3f _accel_desired
Vector3f _accel_target
Vector3f _limit_vector
bool _fwd_pitch_is_limited
float _pos_offset_target_z
float _pos_offset_z
float _vel_offset_z
float _accel_offset_z
uint32_t _ekf_xy_reset_ms
uint32_t _ekf_z_reset_ms
bool _vibe_comp_enabled
float _angle_max_override_cd
Static Private Member Functions
static void Write_PSCx (LogMessages ID, float pos_target, float pos, float vel_desired, float vel_target, float vel, float accel_desired, float accel_target, float accel)
Detailed Description
Definition at line 38 of file AC_PosControl.h.
Constructor & Destructor Documentation
AC_PosControl()
AC_PosControl::AC_PosControl (AP_AHRS_View & ahrs, const AP_InertialNav & inav, const class AP_Motors & motors, AC_AttitudeControl & attitude_control)
Constructor.
Definition at line 328 of file AC_PosControl.cpp.
Member Function Documentation
accel_to_lean_angles()
void AC_PosControl::accel_to_lean_angles (float accel_x_cmss, float accel_y_cmss, float & roll_target, float & pitch_target) const protected
private methods
Definition at line 1208 of file AC_PosControl.cpp.
Referenced by update_xy_controller().
calculate_overspeed_gain()
float AC_PosControl::calculate_overspeed_gain () protected
Definition at line 1259 of file AC_PosControl.cpp.
Referenced by input_accel_z(), input_pos_vel_accel_z(), input_pos_xyz(), and input_vel_accel_z().
calculate_yaw_and_rate_yaw()
bool AC_PosControl::calculate_yaw_and_rate_yaw () protected
Definition at line 1234 of file AC_PosControl.cpp.
Referenced by update_xy_controller().
crosstrack_error()
float AC_PosControl::crosstrack_error () const
crosstrack_error - returns horizontal error to the closest point to the current track
Definition at line 1187 of file AC_PosControl.cpp.
Referenced by AC_WPNav::crosstrack_error().
get_accel_offset_z_cmss()
float AC_PosControl::get_accel_offset_z_cmss () const inline
get_accel_offset_z_cm - returns current vertical offset acceleration in cm/s/s
Definition at line 326 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_wp_target_along_track().
get_accel_target_cmss()
const Vector3f & AC_PosControl::get_accel_target_cmss () const inline
Definition at line 308 of file AC_PosControl.h.
Referenced by get_thrust_vector(), and AC_Loiter::init_target().
get_accel_z_pid()
AC_PID & AC_PosControl::get_accel_z_pid () inline
Definition at line 364 of file AC_PosControl.h.
Referenced by pre_arm_checks().
get_bearing_to_target_cd()
int32_t AC_PosControl::get_bearing_to_target_cd () const
get_bearing_to_target_cd - get bearing to target position in centi-degrees
Definition at line 1122 of file AC_PosControl.cpp.
Referenced by AC_Circle::get_bearing_to_target(), and AC_Loiter::get_bearing_to_target().
get_dt()
float AC_PosControl::get_dt () const inline
Definition at line 52 of file AC_PosControl.h.
Referenced by AC_Loiter::calc_desired_velocity(), AC_Circle::update(), and AC_WPNav::update_wpnav().
get_fwd_pitch_is_limited()
bool AC_PosControl::get_fwd_pitch_is_limited () const inline
returns true when the forward pitch demand is limited by the maximum allowed tilt
Definition at line 400 of file AC_PosControl.h.
get_lean_angle_max_cd()
float AC_PosControl::get_lean_angle_max_cd () const
get_lean_angle_max_cd - returns the maximum lean angle the autopilot may request
Accessors
Definition at line 1028 of file AC_PosControl.cpp.
Referenced by AC_Loiter::get_angle_max_cd(), init_xy_controller(), and update_xy_controller().
get_max_accel_xy_cmss()
float AC_PosControl::get_max_accel_xy_cmss () const inline
get_max_accel_xy_cmss - get the maximum horizontal acceleration in cm/s/s
Definition at line 88 of file AC_PosControl.h.
Referenced by AC_Circle::calc_velocities(), AC_WPNav::set_spline_destination(), and AC_WPNav::set_spline_destination_next().
get_max_accel_z_cmss()
float AC_PosControl::get_max_accel_z_cmss () const inline
get_max_accel_z_cmss - get the maximum vertical acceleration in cm/s/s
Definition at line 163 of file AC_PosControl.h.
Referenced by AC_Loiter::calc_desired_velocity(), AC_WPNav::set_speed_down(), AC_WPNav::set_speed_up(), AC_WPNav::set_spline_destination(), AC_WPNav::set_spline_destination_next(), and update_pos_offset_z().
get_max_speed_down_cms()
float AC_PosControl::get_max_speed_down_cms () const inline
get_max_speed_down_cms - accessors for current maximum down speed in cm/s. Will be a negative number
Definition at line 175 of file AC_PosControl.h.
Referenced by AC_WPNav::set_speed_up(), AC_WPNav::set_spline_destination(), AC_WPNav::set_spline_destination_next(), AC_WPNav::set_wp_destination(), AC_WPNav::set_wp_destination_next(), update_pos_offset_z(), and AC_WPNav::update_track_with_speed_accel_limits().
get_max_speed_up_cms()
float AC_PosControl::get_max_speed_up_cms () const inline
get_max_speed_up_cms - accessors for current maximum up speed in cm/s
Definition at line 172 of file AC_PosControl.h.
Referenced by AC_WPNav::set_speed_down(), AC_WPNav::set_spline_destination(), AC_WPNav::set_spline_destination_next(), AC_WPNav::set_wp_destination(), AC_WPNav::set_wp_destination_next(), update_pos_offset_z(), and AC_WPNav::update_track_with_speed_accel_limits().
get_max_speed_xy_cms()
float AC_PosControl::get_max_speed_xy_cms () const inline
get_max_speed_xy_cms - get the maximum horizontal speed in cm/s
Definition at line 85 of file AC_PosControl.h.
Referenced by AC_Circle::calc_velocities(), AC_WPNav::set_spline_destination(), AC_WPNav::set_spline_destination_next(), AC_WPNav::set_wp_destination(), AC_WPNav::set_wp_destination_next(), and AC_WPNav::update_track_with_speed_accel_limits().
get_pitch_cd()
float AC_PosControl::get_pitch_cd () const inline
Definition at line 333 of file AC_PosControl.h.
Referenced by AC_Circle::get_pitch(), AC_Loiter::get_pitch(), AC_WPNav::get_pitch(), and AC_Loiter::init_target().
get_pos_error_cm()
const Vector3f AC_PosControl::get_pos_error_cm () const inline
get_pos_error_cm - get position error vector between the current and target position
Definition at line 272 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_wp_target_along_track().
get_pos_error_max_xy_cm()
float AC_PosControl::get_pos_error_max_xy_cm () inline
Definition at line 92 of file AC_PosControl.h.
get_pos_error_xy_cm()
float AC_PosControl::get_pos_error_xy_cm () const inline
get_pos_error_xy_cm - get the length of the position error vector in the xy plane
Definition at line 275 of file AC_PosControl.h.
Referenced by AC_Circle::get_distance_to_target(), and AC_Loiter::get_distance_to_target().
get_pos_error_z_cm()
float AC_PosControl::get_pos_error_z_cm () const inline
get_pos_error_z_cm - returns altitude error in cm
Definition at line 278 of file AC_PosControl.h.
get_pos_error_z_down_cm()
float AC_PosControl::get_pos_error_z_down_cm () inline
Definition at line 169 of file AC_PosControl.h.
get_pos_error_z_up_cm()
float AC_PosControl::get_pos_error_z_up_cm () inline
Definition at line 166 of file AC_PosControl.h.
get_pos_offset_z_cm()
float AC_PosControl::get_pos_offset_z_cm () const inline
get_pos_offset_z_cm - returns altitude offset in cm above the EKF origin
Definition at line 320 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_wp_target_along_track(), AC_WPNav::set_spline_destination(), and AC_WPNav::set_wp_destination().
get_pos_target_cm()
const Vector3p & AC_PosControl::get_pos_target_cm () const inline
get_pos_target_cm - returns the position target, frame NEU in cm relative to the EKF origin
Definition at line 257 of file AC_PosControl.h.
Referenced by AC_Loiter::calc_desired_velocity(), and AC_Circle::init().
get_pos_target_z_cm()
float AC_PosControl::get_pos_target_z_cm () const inline
get_pos_target_z_cm - get target altitude (in cm above the EKF origin)
Definition at line 263 of file AC_PosControl.h.
Referenced by AC_Circle::update().
get_pos_xy_p()
AC_P_2D & AC_PosControl::get_pos_xy_p () inline
Other.
get pid controllers
Definition at line 360 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_wp_target_along_track(), AC_Loiter::calc_desired_velocity(), and pre_arm_checks().
get_pos_z_p()
AC_P_1D & AC_PosControl::get_pos_z_p () inline
Definition at line 361 of file AC_PosControl.h.
Referenced by AC_Loiter::calc_desired_velocity(), and pre_arm_checks().
get_roll_cd()
float AC_PosControl::get_roll_cd () const inline
Outputs.
get desired roll and pitch to be passed to the attitude controller
Definition at line 332 of file AC_PosControl.h.
Referenced by AC_Circle::get_roll(), AC_Loiter::get_roll(), AC_WPNav::get_roll(), and AC_Loiter::init_target().
get_shaping_jerk_xy_cmsss()
float AC_PosControl::get_shaping_jerk_xy_cmsss () const inline
get_shaping_jerk_xy_cmsss - gets the jerk limit of the xy kinematic path generation in cm/s/s/s
Definition at line 55 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_wp_target_along_track().
get_stopping_point_xy_cm()
void AC_PosControl::get_stopping_point_xy_cm (Vector2p & stopping_point) const
get_stopping_point_xy_cm - calculates stopping point in NEU cm based on current position, velocity, vehicle acceleration
get_stopping_point_xy_cm - calculates stopping point in NEU cm based on current position, velocity, vehicle acceleration function does not change the z axis
Definition at line 1083 of file AC_PosControl.cpp.
Referenced by AC_Circle::get_closest_point_on_circle(), AC_Loiter::get_stopping_point_xy(), AC_WPNav::get_wp_stopping_point(), AC_WPNav::get_wp_stopping_point_xy(), and init_xy_controller_stopping_point().
get_stopping_point_z_cm()
void AC_PosControl::get_stopping_point_z_cm (postype_t & stopping_point) const
get_stopping_point_z_cm - calculates stopping point in NEU cm based on current position, velocity, vehicle acceleration
Definition at line 1108 of file AC_PosControl.cpp.
Referenced by AC_WPNav::get_wp_stopping_point(), and init_z_controller_stopping_point().
get_throttle_with_vibration_override()
float AC_PosControl::get_throttle_with_vibration_override () protected
System methods
Definition at line 1133 of file AC_PosControl.cpp.
Referenced by update_z_controller().
get_thrust_vector()
Vector3f AC_PosControl::get_thrust_vector () const
get desired roll and pitch to be passed to the attitude controller
Definition at line 1074 of file AC_PosControl.cpp.
Referenced by AC_Circle::get_thrust_vector(), AC_Loiter::get_thrust_vector(), and AC_WPNav::get_thrust_vector().
get_vel_desired_cms()
const Vector3f & AC_PosControl::get_vel_desired_cms () inline
get_vel_desired_cms - returns desired velocity (i.e. feed forward) in cm/s in NEU
Definition at line 290 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_wp_target_along_track(), AC_Loiter::calc_desired_velocity(), and AC_WPNav::set_wp_destination().
get_vel_offset_z_cms()
float AC_PosControl::get_vel_offset_z_cms () const inline
get_vel_offset_z_cm - returns current vertical offset speed in cm/s
Definition at line 323 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_wp_target_along_track(), and AC_WPNav::set_wp_destination().
get_vel_target_cms()
const Vector3f & AC_PosControl::get_vel_target_cms () const inline
Definition at line 293 of file AC_PosControl.h.
get_vel_target_z_cms()
float AC_PosControl::get_vel_target_z_cms () const inline
get_vel_target_z_cms - returns target vertical speed in cm/s
Definition at line 299 of file AC_PosControl.h.
get_vel_xy_pid()
AC_PID_2D & AC_PosControl::get_vel_xy_pid () inline
Definition at line 362 of file AC_PosControl.h.
Referenced by AC_Loiter::calc_desired_velocity().
get_vel_z_control_ratio()
float AC_PosControl::get_vel_z_control_ratio () const inline
get_vel_z_error_ratio - returns the proportion of error relative to the maximum request
Definition at line 385 of file AC_PosControl.h.
get_vel_z_pid()
AC_PID_Basic & AC_PosControl::get_vel_z_pid () inline
Definition at line 363 of file AC_PosControl.h.
Referenced by pre_arm_checks().
get_yaw_cd()
float AC_PosControl::get_yaw_cd () const inline
get desired yaw to be passed to the attitude controller
Definition at line 336 of file AC_PosControl.h.
Referenced by AC_WPNav::get_yaw().
get_yaw_rate_cds()
float AC_PosControl::get_yaw_rate_cds () const inline
get desired yaw rate to be passed to the attitude controller
Definition at line 339 of file AC_PosControl.h.
get_z_accel_cmss()
float AC_PosControl::get_z_accel_cmss () const inline
Definition at line 397 of file AC_PosControl.h.
Referenced by init_z_controller(), and update_z_controller().
handle_ekf_xy_reset()
void AC_PosControl::handle_ekf_xy_reset () protected
handle_ekf_xy_reset - check for ekf position reset and adjust loiter or brake target position
Definition at line 1278 of file AC_PosControl.cpp.
Referenced by input_accel_xy(), and update_xy_controller().
handle_ekf_z_reset()
void AC_PosControl::handle_ekf_z_reset () protected
handle_ekf_z_reset - check for ekf position reset and adjust loiter or brake target position
Definition at line 1300 of file AC_PosControl.cpp.
Referenced by update_z_controller().
has_good_timing()
bool AC_PosControl::has_good_timing (void) const protected
Definition at line 1343 of file AC_PosControl.cpp.
Referenced by update_xy_controller(), and update_z_controller().
init_ekf_xy_reset()
void AC_PosControl::init_ekf_xy_reset () protected
initialise and check for ekf position resets
initialise ekf xy position reset check
Definition at line 1271 of file AC_PosControl.cpp.
Referenced by init_xy_controller(), and standby_xyz_reset().
init_ekf_z_reset()
void AC_PosControl::init_ekf_z_reset () protected
initialise ekf z axis reset check
Definition at line 1293 of file AC_PosControl.cpp.
Referenced by init_z_controller().
init_xy_controller()
void AC_PosControl::init_xy_controller ()
This function is the default initialisation for any position control that provides position, velocity and acceleration. This function is private and contains all the shared xy axis initialisation functions
init_xy_controller - initialise the position controller to the current position, velocity, acceleration and attitude. This function is the default initialisation for any position control that provides position, velocity and acceleration.
Definition at line 508 of file AC_PosControl.cpp.
Referenced by init_xy_controller_stopping_point(), relax_velocity_controller_xy(), AC_WPNav::shift_wp_origin_and_destination_to_current_pos_xy(), and update_xy_controller().
init_xy_controller_stopping_point()
void AC_PosControl::init_xy_controller_stopping_point ()
init_xy_controller_stopping_point - initialise the position controller to the stopping point with zero velocity and acceleration. This function should be used when the expected kinematic path assumes a stationary initial condition but does not specify a specific starting position. The starting position can be retrieved by getting the position target using get_pos_target_cm() after calling this function.
Definition at line 470 of file AC_PosControl.cpp.
Referenced by AC_Circle::init(), AC_Circle::init(), AC_Loiter::init_target(), and AC_WPNav::wp_and_spline_init().
init_z_controller()
void AC_PosControl::init_z_controller ()
This function is the default initialisation for any position control that provides position, velocity and acceleration. This function is private and contains all the shared z axis initialisation functions
init_z_controller - initialise the position controller to the current position, velocity, acceleration and attitude. This function is the default initialisation for any position control that provides position, velocity and acceleration. This function is private and contains all the shared z axis initialisation functions
Definition at line 779 of file AC_PosControl.cpp.
Referenced by AC_AutoTune::init_position_controller(), init_z_controller_no_descent(), init_z_controller_stopping_point(), relax_z_controller(), and update_z_controller().
init_z_controller_no_descent()
void AC_PosControl::init_z_controller_no_descent ()
init_z_controller_no_descent - initialise the position controller to the current position, velocity, acceleration and attitude. This function is the default initialisation for any position control that provides position, velocity and acceleration. This function does not allow any negative velocity or acceleration
init_z_controller - initialise the position controller to the current position, velocity, acceleration and attitude. This function is the default initialisation for any position control that provides position, velocity and acceleration. This function does not allow any negative velocity or acceleration
Definition at line 739 of file AC_PosControl.cpp.
init_z_controller_stopping_point()
void AC_PosControl::init_z_controller_stopping_point ()
init_z_controller_stopping_point - initialise the position controller to the stopping point with zero velocity and acceleration. This function should be used when the expected kinematic path assumes a stationary initial condition but does not specify a specific starting position. The starting position can be retrieved by getting the position target using get_pos_target_cm() after calling this function.
Definition at line 754 of file AC_PosControl.cpp.
Referenced by AC_Circle::init(), AC_Circle::init(), and AC_WPNav::wp_and_spline_init().
input_accel_xy()
void AC_PosControl::input_accel_xy (const Vector3f & accel)
input_accel_xy - calculate a jerk limited path from the current position, velocity and acceleration to an input acceleration. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The kinematic path is constrained by the maximum acceleration and jerk set using the function set_max_speed_accel_xy. The jerk limit defines the acceleration error decay in the kinematic path as the system approaches constant acceleration. The jerk limit also defines the time taken to achieve the maximum acceleration.
Definition at line 554 of file AC_PosControl.cpp.
input_accel_z()
void AC_PosControl::input_accel_z (float accel) virtual
input_accel_z - calculate a jerk limited path from the current position, velocity and acceleration to an input acceleration. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The kinematic path is constrained by the maximum acceleration and jerk set using the function set_max_speed_accel_z.
input_accel_z - calculate a jerk limited path from the current position, velocity and acceleration to an input acceleration. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt.
Definition at line 819 of file AC_PosControl.cpp.
input_pos_vel_accel_xy()
void AC_PosControl::input_pos_vel_accel_xy (Vector2p & pos, Vector2f & vel, const Vector2f & accel, bool limit_output = true)
input_pos_vel_accel_xy - calculate a jerk limited path from the current position, velocity and acceleration to an input position velocity and acceleration. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The kinematic path is constrained by the maximum acceleration and jerk set using the function set_max_speed_accel_xy. The function alters the pos and vel to be the kinematic path based on accel The parameter limit_output specifies if the velocity and acceleration limits are applied to the sum of commanded and correction values or just correction.
input_pos_vel_accel_xy - calculate a jerk limited path from the current position, velocity and acceleration to an input position velocity and acceleration. The pos and vel are projected forwards in time based on a time step of dt and acceleration accel. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The function alters the pos and vel to be the kinematic path based on accel The parameter limit_output specifies if the velocity and acceleration limits are applied to the sum of commanded and correction values or just correction.
Definition at line 583 of file AC_PosControl.cpp.
Referenced by AC_Circle::update().
input_pos_vel_accel_z()
void AC_PosControl::input_pos_vel_accel_z (float & pos, float & vel, float accel, bool limit_output = true)
input_pos_vel_accel_z - calculate a jerk limited path from the current position, velocity and acceleration to an input position velocity and acceleration. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The function alters the pos and vel to be the kinematic path based on accel The parameter limit_output specifies if the velocity and acceleration limits are applied to the sum of commanded and correction values or just correction.
input_pos_vel_accel_z - calculate a jerk limited path from the current position, velocity and acceleration to an input position velocity and acceleration. The pos and vel are projected forwards in time based on a time step of dt and acceleration accel. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The function alters the pos and vel to be the kinematic path based on accel The parameter limit_output specifies if the velocity and acceleration limits are applied to the sum of commanded and correction values or just correction.
Definition at line 892 of file AC_PosControl.cpp.
Referenced by set_alt_target_with_slew(), and AC_Circle::update().
input_pos_xyz()
void AC_PosControl::input_pos_xyz (const Vector3p & pos, float pos_offset_z, float pos_offset_z_buffer)
3D position shaper input_pos_xyz - calculate a jerk limited path from the current position, velocity and acceleration to an input position. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The kinematic path is constrained by the maximum acceleration and jerk set using the function set_max_speed_accel_xy.
3D position shaper input_pos_xyz - calculate a jerk limited path from the current position, velocity and acceleration to an input position. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The kinematic path is constrained by the maximum jerk parameter and the velocity and acceleration limits set using the function set_max_speed_accel_xy. The jerk limit defines the acceleration error decay in the kinematic path as the system approaches constant acceleration. The jerk limit also defines the time taken to achieve the maximum acceleration. The function alters the input velocity to be the velocity that the system could reach zero acceleration in the minimum time.
Definition at line 361 of file AC_PosControl.cpp.
Referenced by AC_WPNav_OA::update_wpnav().
input_vel_accel_xy()
void AC_PosControl::input_vel_accel_xy (Vector2f & vel, const Vector2f & accel, bool limit_output = true)
input_vel_accel_xy - calculate a jerk limited path from the current position, velocity and acceleration to an input velocity and acceleration. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The kinematic path is constrained by the maximum acceleration and jerk set using the function set_max_speed_accel_xy. The function alters the vel to be the kinematic path based on accel The parameter limit_output specifies if the velocity and acceleration limits are applied to the sum of commanded and correction values or just correction.
input_vel_accel_xy - calculate a jerk limited path from the current position, velocity and acceleration to an input velocity and acceleration. The vel is projected forwards in time based on a time step of dt and acceleration accel. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The kinematic path is constrained by the maximum acceleration and jerk set using the function set_max_speed_accel_xy. The parameter limit_output specifies if the velocity and acceleration limits are applied to the sum of commanded and correction values or just correction.
Definition at line 568 of file AC_PosControl.cpp.
input_vel_accel_z()
void AC_PosControl::input_vel_accel_z (float & vel, float accel, bool limit_output = true) virtual
input_vel_accel_z - calculate a jerk limited path from the current position, velocity and acceleration to an input velocity and acceleration. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The kinematic path is constrained by the maximum acceleration and jerk set using the function set_max_speed_accel_z. The function alters the vel to be the kinematic path based on accel The parameter limit_output specifies if the velocity and acceleration limits are applied to the sum of commanded and correction values or just correction.
input_accel_z - calculate a jerk limited path from the current position, velocity and acceleration to an input acceleration. The function takes the current position, velocity, and acceleration and calculates the required jerk limited adjustment to the acceleration for the next time dt. The kinematic path is constrained by the maximum acceleration and jerk set using the function set_max_speed_accel_z. The parameter limit_output specifies if the velocity and acceleration limits are applied to the sum of commanded and correction values or just correction.
Definition at line 834 of file AC_PosControl.cpp.
Referenced by land_at_climb_rate_cm(), and set_pos_target_z_from_climb_rate_cm().
is_active_xy()
bool AC_PosControl::is_active_xy () const
Definition at line 615 of file AC_PosControl.cpp.
Referenced by init_xy_controller(), and update_xy_controller().
is_active_z()
bool AC_PosControl::is_active_z () const
Definition at line 937 of file AC_PosControl.cpp.
Referenced by update_z_controller().
land_at_climb_rate_cm()
void AC_PosControl::land_at_climb_rate_cm (float vel, bool ignore_descent_limit)
land_at_climb_rate_cm - adjusts target up or down using a commanded climb rate in cm/s using the default position control kinematic path. ignore_descent_limit turns off output saturation handling to aid in landing detection. ignore_descent_limit should be true unless landing.
land_at_climb_rate_cm - adjusts target up or down using a commanded climb rate in cm/s using the default position control kinematic path. ignore_descent_limit turns off output saturation handling to aid in landing detection. ignore_descent_limit should be false unless landing.
Definition at line 877 of file AC_PosControl.cpp.
lean_angles_to_accel()
Vector3f AC_PosControl::lean_angles_to_accel (const Vector3f & att_target_euler) const
Definition at line 1056 of file AC_PosControl.cpp.
Referenced by lean_angles_to_accel_xy(), and AC_Loiter::set_pilot_desired_acceleration().
lean_angles_to_accel_xy()
void AC_PosControl::lean_angles_to_accel_xy (float & accel_x_cmss, float & accel_y_cmss) const protected
Definition at line 1222 of file AC_PosControl.cpp.
Referenced by init_xy_controller().
pos_offset_z_scaler()
float AC_PosControl::pos_offset_z_scaler (float pos_offset_z, float pos_offset_z_buffer) const
pos_offset_z_scaler - calculates a multiplier used to reduce the horizontal velocity to allow the z position controller to stay within the provided buffer range
Definition at line 420 of file AC_PosControl.cpp.
Referenced by AC_WPNav::advance_wp_target_along_track(), and input_pos_xyz().
pre_arm_checks()
bool AC_PosControl::pre_arm_checks (const char * param_prefix, char * failure_msg, const uint8_t failure_msg_len)
Definition at line 1314 of file AC_PosControl.cpp.
relax_velocity_controller_xy()
void AC_PosControl::relax_velocity_controller_xy ()
This function decays the output acceleration by 95% every half second to achieve a smooth transition to zero requested acceleration.
Definition at line 481 of file AC_PosControl.cpp.
Referenced by AC_Loiter::init_target(), and AC_WPNav::shift_wp_origin_and_destination_to_stopping_point_xy().
relax_z_controller()
void AC_PosControl::relax_z_controller (float throttle_setting)
This function decays the output acceleration by 95% every half second to achieve a smooth transition to zero requested acceleration.
Definition at line 766 of file AC_PosControl.cpp.
Referenced by AC_AutoTune::run().
set_accel_desired_xy_cmss()
void AC_PosControl::set_accel_desired_xy_cmss (const Vector2f & accel_cms) inline
Acceleration.
Definition at line 305 of file AC_PosControl.h.
set_alt_target_with_slew()
void AC_PosControl::set_alt_target_with_slew (float pos)
set_alt_target_with_slew - adjusts target up or down using a commanded altitude in cm using the default position control kinematic path.
Definition at line 915 of file AC_PosControl.cpp.
set_correction_speed_accel_xy()
void AC_PosControl::set_correction_speed_accel_xy (float speed_cms, float accel_cmss)
set_max_speed_accel_xy - set the position controller correction velocity and acceleration limit This should be done only during initialisation to avoid discontinuities
Definition at line 462 of file AC_PosControl.cpp.
Referenced by AC_Loiter::init_target(), AC_Loiter::init_target(), AC_WPNav::set_speed_xy(), and AC_WPNav::wp_and_spline_init().
set_correction_speed_accel_z()
void AC_PosControl::set_correction_speed_accel_z (float speed_down, float speed_up, float accel_cmss)
set_correction_speed_accel_z - set the position controller correction velocity and acceleration limit speed_down can be positive or negative but will always be interpreted as a descent speed This should be done only during initialisation to avoid discontinuities
set_correction_speed_accel_z - set the position controller correction velocity and acceleration limit speed_down can be positive or negative but will always be interpreted as a descent speed. This should be done only during initialisation to avoid discontinuities
Definition at line 730 of file AC_PosControl.cpp.
Referenced by AC_WPNav::wp_and_spline_init().
set_dt()
void AC_PosControl::set_dt (float dt) inline
set_dt / get_dt - dt is the time since the last time the position controllers were updated _dt should be set based on the time of the last IMU read used by these controllers the position controller should run updates for active controllers on each loop to ensure normal operation
Definition at line 51 of file AC_PosControl.h.
set_externally_limited_xy()
void AC_PosControl::set_externally_limited_xy () inline
set_limit_accel_xy - mark that accel has been limited this prevents integrator buildup
Definition at line 368 of file AC_PosControl.h.
Referenced by soften_for_landing_xy().
set_lean_angle_max_cd()
void AC_PosControl::set_lean_angle_max_cd (float angle_max_cd) inline
Definition at line 354 of file AC_PosControl.h.
set_max_speed_accel_xy()
void AC_PosControl::set_max_speed_accel_xy (float speed_cms, float accel_cmss)
Lateral position controller set_max_speed_accel_xy - set the maximum horizontal speed in cm/s and acceleration in cm/s/s This function only needs to be called if using the kinematic shaping. This can be done at any time as changes in these parameters are handled smoothly by the kinematic shaping.
Definition at line 437 of file AC_PosControl.cpp.
Referenced by AC_WPNav::set_speed_xy(), and AC_WPNav::wp_and_spline_init().
set_max_speed_accel_z()
void AC_PosControl::set_max_speed_accel_z (float speed_down, float speed_up, float accel_cmss)
Vertical position controller set_max_speed_accel_z - set the maximum vertical speed in cm/s and acceleration in cm/s/s speed_down can be positive or negative but will always be interpreted as a descent speed This can be done at any time as changes in these parameters are handled smoothly by the kinematic shaping.
Vertical position controller set_max_speed_accel_z - set the maximum vertical speed in cm/s and acceleration in cm/s/s speed_down can be positive or negative but will always be interpreted as a descent speed. This function only needs to be called if using the kinematic shaping. This can be done at any time as changes in these parameters are handled smoothly by the kinematic shaping.
Definition at line 701 of file AC_PosControl.cpp.
Referenced by AC_WPNav::set_speed_down(), AC_WPNav::set_speed_up(), and AC_WPNav::wp_and_spline_init().
set_pos_error_max_xy_cm()
void AC_PosControl::set_pos_error_max_xy_cm (float error_max) inline
Definition at line 91 of file AC_PosControl.h.
Referenced by AC_Loiter::init_target(), and AC_Loiter::init_target().
set_pos_offset_target_z_cm()
void AC_PosControl::set_pos_offset_target_z_cm (float pos_offset_target_z) inline
Offset.
set_pos_offset_target_z_cm - set altitude offset target in cm above the EKF origin
Definition at line 314 of file AC_PosControl.h.
set_pos_offset_z_cm()
void AC_PosControl::set_pos_offset_z_cm (float pos_offset_z) inline
set_pos_offset_z_cm - set altitude offset in cm above the EKF origin
Definition at line 317 of file AC_PosControl.h.
Referenced by AC_WPNav::set_spline_destination(), and AC_WPNav::set_wp_destination().
set_pos_target_xy_cm()
void AC_PosControl::set_pos_target_xy_cm (float pos_x, float pos_y) inline
Position.
set_pos_target_xy_cm - sets the position target, frame NEU in cm relative to the EKF origin
Definition at line 254 of file AC_PosControl.h.
Referenced by AC_Loiter::init_target(), and AC_WPNav::shift_wp_origin_and_destination_to_stopping_point_xy().
set_pos_target_z_cm()
void AC_PosControl::set_pos_target_z_cm (float pos_target) inline
set_pos_target_z_cm - set altitude target in cm above the EKF origin
Definition at line 260 of file AC_PosControl.h.
set_pos_target_z_from_climb_rate_cm()
void AC_PosControl::set_pos_target_z_from_climb_rate_cm (float vel)
set_pos_target_z_from_climb_rate_cm - adjusts target up or down using a commanded climb rate in cm/s using the default position control kinematic path. The zero target altitude is varied to follow pos_offset_z
Definition at line 855 of file AC_PosControl.cpp.
Referenced by AC_AutoTune::run(), and AC_Circle::update().
set_pos_vel_accel()
void AC_PosControl::set_pos_vel_accel (const Vector3p & pos, const Vector3f & vel, const Vector3f & accel)
set commanded position (cm), velocity (cm/s) and acceleration (cm/s/s) inputs when the path is created externally.
set position, velocity and acceleration targets
Accessors
Definition at line 1040 of file AC_PosControl.cpp.
Referenced by AC_WPNav::advance_wp_target_along_track().
set_pos_vel_accel_xy()
void AC_PosControl::set_pos_vel_accel_xy (const Vector2p & pos, const Vector2f & vel, const Vector2f & accel)
set position, velocity and acceleration targets
Definition at line 1048 of file AC_PosControl.cpp.
Referenced by AC_Loiter::calc_desired_velocity().
set_vel_desired_cms()
void AC_PosControl::set_vel_desired_cms (const Vector3f & des_vel) inline
Velocity.
set_vel_desired_cms - sets desired velocity in NEU cm/s
Definition at line 284 of file AC_PosControl.h.
set_vel_desired_xy_cms()
void AC_PosControl::set_vel_desired_xy_cms (const Vector2f & vel) inline
set_vel_desired_xy_cms - sets horizontal desired velocity in NEU cm/s
Definition at line 287 of file AC_PosControl.h.
set_vel_desired_z_cms()
void AC_PosControl::set_vel_desired_z_cms (float vel_z_cms) inline
set_vel_desired_z_cms - sets desired velocity in cm/s in z axis
Definition at line 296 of file AC_PosControl.h.
set_vibe_comp()
void AC_PosControl::set_vibe_comp (bool on_off) inline
Definition at line 382 of file AC_PosControl.h.
soften_for_landing_xy()
void AC_PosControl::soften_for_landing_xy ()
reduce response for landing
Definition at line 494 of file AC_PosControl.cpp.
Referenced by AC_Loiter::soften_for_landing().
standby_xyz_reset()
void AC_PosControl::standby_xyz_reset ()
standby_xyz_reset - resets I terms and removes position error This function will let Loiter and Alt Hold continue to operate in the event that the flight controller is in control of the aircraft when in standby.
Definition at line 1148 of file AC_PosControl.cpp.
stop_pos_xy_stabilisation()
void AC_PosControl::stop_pos_xy_stabilisation ()
stop_pos_xy_stabilisation - sets the target to the current position to remove any position corrections from the system
Definition at line 594 of file AC_PosControl.cpp.
stop_vel_xy_stabilisation()
void AC_PosControl::stop_vel_xy_stabilisation ()
stop_vel_xy_stabilisation - sets the target to the current position and velocity to the current velocity to remove any position and velocity corrections from the system
Definition at line 600 of file AC_PosControl.cpp.
update_pos_offset_z()
void AC_PosControl::update_pos_offset_z (float pos_offset)
update_pos_offset_z - updates the vertical offsets used by terrain following
Definition at line 922 of file AC_PosControl.cpp.
Referenced by AC_WPNav::advance_wp_target_along_track(), input_pos_xyz(), and set_pos_target_z_from_climb_rate_cm().
update_xy_controller()
void AC_PosControl::update_xy_controller ()
update_xy_controller - runs the horizontal position controller correcting position, velocity and acceleration errors. Position and velocity errors are converted to velocity and acceleration targets using PID objects Desired velocity and accelerations are added to these corrections as they are calculated Kinematically consistent target position and desired velocity and accelerations should be provided before calling this function
Definition at line 625 of file AC_PosControl.cpp.
Referenced by AC_Loiter::update(), AC_Circle::update(), AC_WPNav::update_wpnav(), and AC_WPNav_OA::update_wpnav().
update_z_controller()
void AC_PosControl::update_z_controller ()
update_z_controller - runs the vertical position controller correcting position, velocity and acceleration errors. Position and velocity errors are converted to velocity and acceleration targets using PID objects Desired velocity and accelerations are added to these corrections as they are calculated Kinematically consistent target position and desired velocity and accelerations should be provided before calling this function
Definition at line 947 of file AC_PosControl.cpp.
Referenced by AC_AutoTune::run().
write_log()
void AC_PosControl::write_log ()
Write_PSCD()
static void AC_PosControl::Write_PSCD (float pos_target, float pos, float vel_desired, float vel_target, float vel, float accel_desired, float accel_target, float accel) static
Write_PSCE()
static void AC_PosControl::Write_PSCE (float pos_target, float pos, float vel_desired, float vel_target, float vel, float accel_desired, float accel_target, float accel) static
Write_PSCN()
static void AC_PosControl::Write_PSCN (float pos_target, float pos, float vel_desired, float vel_target, float vel, float accel_desired, float accel_target, float accel) static
Write_PSCx()
static void AC_PosControl::Write_PSCx (LogMessages ID, float pos_target, float pos, float vel_desired, float vel_target, float vel, float accel_desired, float accel_target, float accel) static private
Member Data Documentation
_accel_desired
Vector3f AC_PosControl::_accel_desired protected
Definition at line 470 of file AC_PosControl.h.
Referenced by calculate_yaw_and_rate_yaw(), init_xy_controller(), init_xy_controller_stopping_point(), init_z_controller(), init_z_controller_no_descent(), init_z_controller_stopping_point(), input_accel_xy(), input_accel_z(), input_pos_vel_accel_xy(), input_pos_vel_accel_z(), input_pos_xyz(), input_vel_accel_xy(), input_vel_accel_z(), set_accel_desired_xy_cmss(), set_pos_target_z_from_climb_rate_cm(), set_pos_vel_accel(), set_pos_vel_accel_xy(), update_xy_controller(), and update_z_controller().
_accel_max_xy_cmss
float AC_PosControl::_accel_max_xy_cmss protected
Definition at line 454 of file AC_PosControl.h.
Referenced by get_max_accel_xy_cmss(), get_stopping_point_xy_cm(), input_pos_vel_accel_xy(), input_pos_xyz(), input_vel_accel_xy(), and set_max_speed_accel_xy().
_accel_max_z_cmss
float AC_PosControl::_accel_max_z_cmss protected
Definition at line 455 of file AC_PosControl.h.
Referenced by get_max_accel_z_cmss(), get_stopping_point_z_cm(), init_z_controller(), input_pos_vel_accel_z(), input_pos_xyz(), input_vel_accel_z(), and set_max_speed_accel_z().
_accel_offset_z
float AC_PosControl::_accel_offset_z protected
Definition at line 479 of file AC_PosControl.h.
Referenced by get_accel_offset_z_cmss(), init_z_controller(), input_pos_xyz(), set_pos_target_z_from_climb_rate_cm(), and update_pos_offset_z().
_accel_target
Vector3f AC_PosControl::_accel_target protected
Definition at line 471 of file AC_PosControl.h.
Referenced by get_accel_target_cmss(), get_throttle_with_vibration_override(), init_xy_controller(), init_z_controller(), init_z_controller_no_descent(), relax_velocity_controller_xy(), set_externally_limited_xy(), update_xy_controller(), and update_z_controller().
_ahrs
AP_AHRS_View& AC_PosControl::_ahrs protected
Definition at line 432 of file AC_PosControl.h.
Referenced by accel_to_lean_angles(), get_z_accel_cmss(), handle_ekf_xy_reset(), handle_ekf_z_reset(), init_ekf_xy_reset(), init_ekf_z_reset(), lean_angles_to_accel_xy(), and update_xy_controller().
_angle_max_override_cd
float AC_PosControl::_angle_max_override_cd protected
Definition at line 489 of file AC_PosControl.h.
Referenced by get_lean_angle_max_cd(), init_xy_controller(), and set_lean_angle_max_cd().
_attitude_control
AC_AttitudeControl& AC_PosControl::_attitude_control protected
Definition at line 435 of file AC_PosControl.h.
Referenced by get_lean_angle_max_cd(), init_xy_controller(), init_z_controller(), lean_angles_to_accel_xy(), set_max_speed_accel_xy(), update_xy_controller(), and update_z_controller().
_dt
float AC_PosControl::_dt protected
Definition at line 448 of file AC_PosControl.h.
Referenced by get_dt(), get_throttle_with_vibration_override(), input_accel_xy(), input_accel_z(), input_pos_vel_accel_xy(), input_pos_vel_accel_z(), input_pos_xyz(), input_vel_accel_xy(), input_vel_accel_z(), relax_velocity_controller_xy(), relax_z_controller(), set_dt(), soften_for_landing_xy(), update_pos_offset_z(), update_xy_controller(), and update_z_controller().
_ekf_xy_reset_ms
uint32_t AC_PosControl::_ekf_xy_reset_ms protected
Definition at line 482 of file AC_PosControl.h.
Referenced by handle_ekf_xy_reset(), and init_ekf_xy_reset().
_ekf_z_reset_ms
uint32_t AC_PosControl::_ekf_z_reset_ms protected
Definition at line 483 of file AC_PosControl.h.
Referenced by handle_ekf_z_reset(), and init_ekf_z_reset().
_fwd_pitch_is_limited
bool AC_PosControl::_fwd_pitch_is_limited protected
Definition at line 474 of file AC_PosControl.h.
Referenced by get_fwd_pitch_is_limited(), and update_xy_controller().
_inav
const AP_InertialNav& AC_PosControl::_inav protected
Definition at line 433 of file AC_PosControl.h.
Referenced by crosstrack_error(), get_bearing_to_target_cd(), get_pos_error_cm(), get_pos_error_xy_cm(), get_pos_error_z_cm(), get_stopping_point_xy_cm(), get_stopping_point_z_cm(), handle_ekf_xy_reset(), handle_ekf_z_reset(), init_xy_controller(), init_z_controller(), pos_offset_z_scaler(), soften_for_landing_xy(), standby_xyz_reset(), stop_pos_xy_stabilisation(), stop_vel_xy_stabilisation(), update_xy_controller(), and update_z_controller().
_jerk_max_xy_cmsss
float AC_PosControl::_jerk_max_xy_cmsss protected
Definition at line 456 of file AC_PosControl.h.
Referenced by input_accel_xy(), input_pos_vel_accel_xy(), input_pos_xyz(), input_vel_accel_xy(), and set_max_speed_accel_xy().
_jerk_max_z_cmsss
float AC_PosControl::_jerk_max_z_cmsss protected
Definition at line 457 of file AC_PosControl.h.
Referenced by input_accel_z(), input_pos_vel_accel_z(), input_pos_xyz(), input_vel_accel_z(), set_max_speed_accel_z(), and update_pos_offset_z().
_last_update_xy_ticks
uint32_t AC_PosControl::_last_update_xy_ticks protected
Definition at line 449 of file AC_PosControl.h.
Referenced by init_xy_controller(), is_active_xy(), and update_xy_controller().
_last_update_z_ticks
uint32_t AC_PosControl::_last_update_z_ticks protected
Definition at line 450 of file AC_PosControl.h.
Referenced by init_z_controller(), is_active_z(), and update_z_controller().
_lean_angle_max
AP_Float AC_PosControl::_lean_angle_max protected
Definition at line 438 of file AC_PosControl.h.
Referenced by get_lean_angle_max_cd().
_limit_vector
Vector3f AC_PosControl::_limit_vector protected
Definition at line 472 of file AC_PosControl.h.
Referenced by input_accel_xy(), input_accel_z(), input_pos_vel_accel_xy(), input_pos_vel_accel_z(), input_pos_xyz(), input_vel_accel_xy(), input_vel_accel_z(), land_at_climb_rate_cm(), set_externally_limited_xy(), update_pos_offset_z(), update_xy_controller(), and update_z_controller().
_motors
const class AP_Motors& AC_PosControl::_motors protected
Definition at line 434 of file AC_PosControl.h.
Referenced by get_throttle_with_vibration_override(), init_z_controller(), relax_z_controller(), and update_z_controller().
_p_pos_xy
AC_P_2D AC_PosControl::_p_pos_xy protected
Definition at line 441 of file AC_PosControl.h.
Referenced by get_pos_error_max_xy_cm(), get_pos_xy_p(), get_stopping_point_xy_cm(), handle_ekf_xy_reset(), input_accel_xy(), input_pos_vel_accel_xy(), input_pos_xyz(), input_vel_accel_xy(), set_correction_speed_accel_xy(), set_pos_error_max_xy_cm(), and update_xy_controller().
_p_pos_z
AC_P_1D AC_PosControl::_p_pos_z protected
Definition at line 442 of file AC_PosControl.h.
Referenced by get_pos_error_z_down_cm(), get_pos_error_z_up_cm(), get_pos_z_p(), get_stopping_point_z_cm(), handle_ekf_z_reset(), input_accel_z(), input_pos_vel_accel_z(), input_pos_xyz(), input_vel_accel_z(), set_correction_speed_accel_z(), update_pos_offset_z(), and update_z_controller().
_pid_accel_z
AC_PID AC_PosControl::_pid_accel_z protected
Definition at line 445 of file AC_PosControl.h.
Referenced by get_accel_z_pid(), get_throttle_with_vibration_override(), init_z_controller(), relax_z_controller(), set_max_speed_accel_z(), standby_xyz_reset(), and update_z_controller().
_pid_vel_xy
AC_PID_2D AC_PosControl::_pid_vel_xy protected
Definition at line 443 of file AC_PosControl.h.
Referenced by get_vel_xy_pid(), handle_ekf_xy_reset(), init_xy_controller(), input_accel_xy(), input_pos_vel_accel_xy(), input_pos_xyz(), input_vel_accel_xy(), standby_xyz_reset(), stop_vel_xy_stabilisation(), and update_xy_controller().
_pid_vel_z
AC_PID_Basic AC_PosControl::_pid_vel_z protected
Definition at line 444 of file AC_PosControl.h.
Referenced by get_throttle_with_vibration_override(), get_vel_z_pid(), handle_ekf_z_reset(), init_z_controller(), input_accel_z(), input_pos_vel_accel_z(), input_pos_xyz(), input_vel_accel_z(), update_pos_offset_z(), and update_z_controller().
_pitch_target
float AC_PosControl::_pitch_target protected
Definition at line 462 of file AC_PosControl.h.
Referenced by get_pitch_cd(), init_xy_controller(), and update_xy_controller().
_pos_offset_target_z
float AC_PosControl::_pos_offset_target_z protected
Definition at line 476 of file AC_PosControl.h.
Referenced by init_z_controller(), set_pos_offset_target_z_cm(), and set_pos_target_z_from_climb_rate_cm().
_pos_offset_z
float AC_PosControl::_pos_offset_z protected
Definition at line 477 of file AC_PosControl.h.
Referenced by get_pos_offset_z_cm(), init_z_controller(), input_pos_xyz(), pos_offset_z_scaler(), set_pos_offset_z_cm(), set_pos_target_z_from_climb_rate_cm(), and update_pos_offset_z().
_pos_target
Vector3p AC_PosControl::_pos_target protected
Definition at line 467 of file AC_PosControl.h.
Referenced by crosstrack_error(), get_bearing_to_target_cd(), get_pos_error_cm(), get_pos_error_xy_cm(), get_pos_error_z_cm(), get_pos_target_cm(), get_pos_target_z_cm(), handle_ekf_xy_reset(), handle_ekf_z_reset(), init_xy_controller(), init_xy_controller_stopping_point(), init_z_controller(), init_z_controller_stopping_point(), input_accel_xy(), input_accel_z(), input_pos_vel_accel_xy(), input_pos_vel_accel_z(), input_pos_xyz(), input_vel_accel_xy(), input_vel_accel_z(), pos_offset_z_scaler(), set_pos_target_xy_cm(), set_pos_target_z_cm(), set_pos_target_z_from_climb_rate_cm(), set_pos_vel_accel(), set_pos_vel_accel_xy(), soften_for_landing_xy(), standby_xyz_reset(), stop_pos_xy_stabilisation(), stop_vel_xy_stabilisation(), update_xy_controller(), and update_z_controller().
_roll_target
float AC_PosControl::_roll_target protected
Definition at line 461 of file AC_PosControl.h.
Referenced by get_roll_cd(), init_xy_controller(), and update_xy_controller().
_shaping_jerk_xy
AP_Float AC_PosControl::_shaping_jerk_xy protected
Definition at line 439 of file AC_PosControl.h.
Referenced by get_shaping_jerk_xy_cmsss(), and set_max_speed_accel_xy().
_shaping_jerk_z
AP_Float AC_PosControl::_shaping_jerk_z protected
Definition at line 440 of file AC_PosControl.h.
Referenced by set_max_speed_accel_z().
_vel_desired
Vector3f AC_PosControl::_vel_desired protected
Definition at line 468 of file AC_PosControl.h.
Referenced by calculate_overspeed_gain(), calculate_yaw_and_rate_yaw(), crosstrack_error(), get_vel_desired_cms(), init_xy_controller(), init_xy_controller_stopping_point(), init_z_controller(), init_z_controller_no_descent(), init_z_controller_stopping_point(), input_accel_xy(), input_accel_z(), input_pos_vel_accel_xy(), input_pos_vel_accel_z(), input_pos_xyz(), input_vel_accel_xy(), input_vel_accel_z(), set_pos_target_z_from_climb_rate_cm(), set_pos_vel_accel(), set_pos_vel_accel_xy(), set_vel_desired_cms(), set_vel_desired_xy_cms(), set_vel_desired_z_cms(), stop_vel_xy_stabilisation(), update_xy_controller(), and update_z_controller().
_vel_max_down_cms
float AC_PosControl::_vel_max_down_cms protected
Definition at line 453 of file AC_PosControl.h.
Referenced by calculate_overspeed_gain(), get_max_speed_down_cms(), input_pos_vel_accel_z(), input_pos_xyz(), set_max_speed_accel_z(), and update_z_controller().
_vel_max_up_cms
float AC_PosControl::_vel_max_up_cms protected
Definition at line 452 of file AC_PosControl.h.
Referenced by calculate_overspeed_gain(), get_max_speed_up_cms(), input_pos_vel_accel_z(), input_pos_xyz(), and set_max_speed_accel_z().
_vel_max_xy_cms
float AC_PosControl::_vel_max_xy_cms protected
Definition at line 451 of file AC_PosControl.h.
Referenced by calculate_yaw_and_rate_yaw(), get_max_speed_xy_cms(), get_stopping_point_xy_cm(), input_pos_vel_accel_xy(), input_pos_xyz(), and set_max_speed_accel_xy().
_vel_offset_z
float AC_PosControl::_vel_offset_z protected
Definition at line 478 of file AC_PosControl.h.
Referenced by get_vel_offset_z_cms(), init_z_controller(), input_pos_xyz(), set_pos_target_z_from_climb_rate_cm(), and update_pos_offset_z().
_vel_target
Vector3f AC_PosControl::_vel_target protected
Definition at line 469 of file AC_PosControl.h.
Referenced by get_vel_target_cms(), get_vel_target_z_cms(), handle_ekf_xy_reset(), handle_ekf_z_reset(), init_xy_controller(), init_z_controller(), init_z_controller_no_descent(), stop_vel_xy_stabilisation(), update_xy_controller(), and update_z_controller().
_vel_z_control_ratio
float AC_PosControl::_vel_z_control_ratio = 2.0f protected
Definition at line 458 of file AC_PosControl.h.
Referenced by get_vel_z_control_ratio(), and update_z_controller().
_vibe_comp_enabled
bool AC_PosControl::_vibe_comp_enabled protected
Definition at line 486 of file AC_PosControl.h.
Referenced by set_vibe_comp(), and update_z_controller().
_yaw_rate_target
float AC_PosControl::_yaw_rate_target protected
Definition at line 464 of file AC_PosControl.h.
Referenced by calculate_yaw_and_rate_yaw(), get_yaw_rate_cds(), and init_xy_controller().
_yaw_target
float AC_PosControl::_yaw_target protected
Definition at line 463 of file AC_PosControl.h.
Referenced by calculate_yaw_and_rate_yaw(), get_yaw_cd(), and init_xy_controller().
var_info
const AP_Param::GroupInfo AC_PosControl::var_info static
Definition at line 77 of file AC_PosControl.h.
The documentation for this class was generated from the following files:
libraries/AC_AttitudeControl/AC_PosControl.h
libraries/AC_AttitudeControl/AC_PosControl.cpp