APM:Libraries: AP_BattMonitor_SMBus Class Reference
AP_BattMonitor_SMBus Class Reference abstract
#include <AP_BattMonitor_SMBus.h>
Public Types
enum BATTMONITOR_SMBUS {
BATTMONITOR_SMBUS_TEMP = 0x08 , BATTMONITOR_SMBUS_VOLTAGE = 0x09 , BATTMONITOR_SMBUS_CURRENT = 0x0A , BATTMONITOR_SMBUS_REMAINING_CAPACITY = 0x0F ,
BATTMONITOR_SMBUS_FULL_CHARGE_CAPACITY = 0x10 , BATTMONITOR_SMBUS_CYCLE_COUNT = 0x17 , BATTMONITOR_SMBUS_SPECIFICATION_INFO = 0x1A , BATTMONITOR_SMBUS_SERIAL = 0x1C ,
BATTMONITOR_SMBUS_MANUFACTURE_NAME = 0x20 , BATTMONITOR_SMBUS_MANUFACTURE_DATA = 0x23
}
Public Member Functions
AP_BattMonitor_SMBus (AP_BattMonitor &mon, AP_BattMonitor::BattMonitor_State &mon_state, AP_BattMonitor_Params &params, uint8_t i2c_bus)
Constructor.
virtual ~AP_BattMonitor_SMBus ()
bool has_cell_voltages () const override
bool has_temperature () const override
bool has_current () const override
returns true if battery monitor instance provides current info
bool reset_remaining (float percentage) override
bool get_cycle_count (uint16_t &cycles) const override
virtual void init (void) override
Public Member Functions inherited from AP_BattMonitor_Backend
AP_BattMonitor_Backend (AP_BattMonitor &mon, AP_BattMonitor::BattMonitor_State &mon_state, AP_BattMonitor_Params &params)
virtual ~AP_BattMonitor_Backend (void)
virtual bool has_time_remaining () const
returns true if battery monitor instance provides time remaining info
virtual bool has_consumed_energy () const
returns true if battery monitor instance provides consumed energy info
virtual bool get_temperature (float &temperature) const
virtual bool capacity_remaining_pct (uint8_t &percentage) const WARN_IF_UNUSED
bool get_state_of_health_pct (uint8_t &soh_pct) const
float voltage_resting_estimate () const
virtual void update_resistance_estimate ()
virtual AP_BattMonitor::Failsafe update_failsafes (void)
bool arming_checks (char *buffer, size_t buflen) const
virtual uint32_t get_mavlink_fault_bitmask () const
void Log_Write_BAT (const uint8_t instance, const uint64_t time_us) const
void Log_Write_BCL (const uint8_t instance, const uint64_t time_us) const
virtual void mppt_set_powered_state (bool power_on)
void update_esc_telem_outbound ()
bool option_is_set (const AP_BattMonitor_Params::Options option) const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void read (void) override
read the battery_voltage and current, should be called at 10hz
void read_full_charge_capacity (void)
void read_remaining_capacity (void)
virtual uint16_t get_capacity_scaler () const
virtual void read_temp (void)
void read_serial_number (void)
void read_cycle_count ()
bool read_word (uint8_t reg, uint16_t &data) const
uint8_t read_block (uint8_t reg, uint8_t *data, uint8_t len) const
uint8_t get_PEC (const uint8_t i2c_addr, uint8_t cmd, bool reading, const uint8_t buff[], uint8_t len) const
get_PEC - calculate packet error correction code of buffer
virtual void timer (void)=0
Protected Member Functions inherited from AP_BattMonitor_Backend
void check_failsafe_types (bool &low_voltage, bool &low_capacity, bool &critical_voltage, bool &critical_capacity) const
void update_consumed (AP_BattMonitor::BattMonitor_State &state, uint32_t dt_us)
Protected Attributes
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
bool _pec_supported
int32_t _serial_number = -1
uint16_t _full_charge_capacity
bool _has_cell_voltages
uint16_t _cycle_count = 0
bool _has_cycle_count
bool _has_temperature
AP_HAL::Device::PeriodicHandle timer_handle
AP_Int8 _bus
AP_Int8 _address
Protected Attributes inherited from AP_BattMonitor_Backend
AP_BattMonitor & _mon
AP_BattMonitor::BattMonitor_State & _state
AP_BattMonitor_Params & _params
Additional Inherited Members
Static Public Member Functions inherited from AP_BattMonitor_Backend
static float calculate_mah (float amps, float dt_us)
Detailed Description
Definition at line 19 of file AP_BattMonitor_SMBus.h.
Member Enumeration Documentation
BATTMONITOR_SMBUS
enum AP_BattMonitor_SMBus::BATTMONITOR_SMBUS
Enumerator
BATTMONITOR_SMBUS_TEMP
BATTMONITOR_SMBUS_VOLTAGE
BATTMONITOR_SMBUS_CURRENT
BATTMONITOR_SMBUS_REMAINING_CAPACITY
BATTMONITOR_SMBUS_FULL_CHARGE_CAPACITY
BATTMONITOR_SMBUS_CYCLE_COUNT
BATTMONITOR_SMBUS_SPECIFICATION_INFO
BATTMONITOR_SMBUS_SERIAL
BATTMONITOR_SMBUS_MANUFACTURE_NAME
BATTMONITOR_SMBUS_MANUFACTURE_DATA
Definition at line 24 of file AP_BattMonitor_SMBus.h.
Constructor & Destructor Documentation
AP_BattMonitor_SMBus()
AP_BattMonitor_SMBus::AP_BattMonitor_SMBus (AP_BattMonitor & mon, AP_BattMonitor::BattMonitor_State & mon_state, AP_BattMonitor_Params & params, uint8_t i2c_bus)
Constructor.
Definition at line 36 of file AP_BattMonitor_SMBus.cpp.
~AP_BattMonitor_SMBus()
virtual AP_BattMonitor_SMBus::~AP_BattMonitor_SMBus () inline virtual
Definition at line 44 of file AP_BattMonitor_SMBus.h.
Member Function Documentation
get_capacity_scaler()
virtual uint16_t AP_BattMonitor_SMBus::get_capacity_scaler () const inline protected virtual
Reimplemented in AP_BattMonitor_SMBus_Maxell.
Definition at line 75 of file AP_BattMonitor_SMBus.h.
Referenced by read_full_charge_capacity(), and read_remaining_capacity().
get_cycle_count()
bool AP_BattMonitor_SMBus::get_cycle_count (uint16_t & cycles) const override virtual
Reimplemented from AP_BattMonitor_Backend.
Definition at line 60 of file AP_BattMonitor_SMBus.cpp.
get_PEC()
uint8_t AP_BattMonitor_SMBus::get_PEC (const uint8_t i2c_addr, uint8_t cmd, bool reading, const uint8_t buff[], uint8_t len) const protected
get_PEC - calculate packet error correction code of buffer
Definition at line 220 of file AP_BattMonitor_SMBus.cpp.
Referenced by read_block(), and read_word().
has_cell_voltages()
bool AP_BattMonitor_SMBus::has_cell_voltages () const inline override virtual
Reimplemented from AP_BattMonitor_Backend.
Definition at line 46 of file AP_BattMonitor_SMBus.h.
has_current()
bool AP_BattMonitor_SMBus::has_current () const inline override virtual
returns true if battery monitor instance provides current info
Implements AP_BattMonitor_Backend.
Definition at line 51 of file AP_BattMonitor_SMBus.h.
has_temperature()
bool AP_BattMonitor_SMBus::has_temperature () const inline override virtual
Reimplemented from AP_BattMonitor_Backend.
Definition at line 48 of file AP_BattMonitor_SMBus.h.
init()
void AP_BattMonitor_SMBus::init (void) override virtual
Reimplemented from AP_BattMonitor_Backend.
Reimplemented in AP_BattMonitor_SMBus_SUI.
Definition at line 50 of file AP_BattMonitor_SMBus.cpp.
Referenced by AP_BattMonitor_SMBus_SUI::init().
read()
void AP_BattMonitor_SMBus::read (void) override protected virtual
read the battery_voltage and current, should be called at 10hz
Implements AP_BattMonitor_Backend.
Definition at line 70 of file AP_BattMonitor_SMBus.cpp.
read_block()
uint8_t AP_BattMonitor_SMBus::read_block (uint8_t reg, uint8_t * data, uint8_t len) const protected
Definition at line 181 of file AP_BattMonitor_SMBus.cpp.
Referenced by AP_BattMonitor_SMBus_Generic::check_pec_support(), and AP_BattMonitor_SMBus_SUI::read_cell_voltages().
read_cycle_count()
void AP_BattMonitor_SMBus::read_cycle_count () protected
Definition at line 143 of file AP_BattMonitor_SMBus.cpp.
Referenced by AP_BattMonitor_SMBus_Generic::timer().
read_full_charge_capacity()
void AP_BattMonitor_SMBus::read_full_charge_capacity (void) protected
Definition at line 86 of file AP_BattMonitor_SMBus.cpp.
Referenced by AP_BattMonitor_SMBus_Generic::timer(), AP_BattMonitor_SMBus_NeoDesign::timer(), and AP_BattMonitor_SMBus_SUI::timer().
read_remaining_capacity()
void AP_BattMonitor_SMBus::read_remaining_capacity (void) protected
Definition at line 99 of file AP_BattMonitor_SMBus.cpp.
Referenced by AP_BattMonitor_SMBus_Generic::timer(), AP_BattMonitor_SMBus_NeoDesign::timer(), and AP_BattMonitor_SMBus_SUI::timer().
read_serial_number()
void AP_BattMonitor_SMBus::read_serial_number (void) protected
Definition at line 129 of file AP_BattMonitor_SMBus.cpp.
Referenced by AP_BattMonitor_SMBus_Generic::timer(), and AP_BattMonitor_SMBus_SUI::timer().
read_temp()
void AP_BattMonitor_SMBus::read_temp (void) protected virtual
Reimplemented in AP_BattMonitor_SMBus_Rotoye.
Definition at line 114 of file AP_BattMonitor_SMBus.cpp.
Referenced by AP_BattMonitor_SMBus_Generic::timer(), AP_BattMonitor_SMBus_NeoDesign::timer(), and AP_BattMonitor_SMBus_SUI::timer().
read_word()
bool AP_BattMonitor_SMBus::read_word (uint8_t reg, uint16_t & data) const protected
Definition at line 154 of file AP_BattMonitor_SMBus.cpp.
Referenced by AP_BattMonitor_SMBus_Generic::check_pec_support(), AP_BattMonitor_SMBus_SUI::read_cell_voltages(), read_cycle_count(), read_full_charge_capacity(), read_remaining_capacity(), read_serial_number(), read_temp(), AP_BattMonitor_SMBus_Rotoye::read_temp(), AP_BattMonitor_SMBus_Generic::timer(), and AP_BattMonitor_SMBus_NeoDesign::timer().
reset_remaining()
bool AP_BattMonitor_SMBus::reset_remaining (float percentage) inline override virtual
Reimplemented from AP_BattMonitor_Backend.
Definition at line 54 of file AP_BattMonitor_SMBus.h.
timer()
virtual void AP_BattMonitor_SMBus::timer (void) protected pure virtual
Implemented in AP_BattMonitor_SMBus_Generic, AP_BattMonitor_SMBus_NeoDesign, and AP_BattMonitor_SMBus_SUI.
Referenced by init().
Member Data Documentation
_address
AP_Int8 AP_BattMonitor_SMBus::_address protected
Definition at line 114 of file AP_BattMonitor_SMBus.h.
Referenced by init(), read_block(), and read_word().
_bus
AP_Int8 AP_BattMonitor_SMBus::_bus protected
Definition at line 113 of file AP_BattMonitor_SMBus.h.
Referenced by AP_BattMonitor_SMBus(), and init().
_cycle_count
uint16_t AP_BattMonitor_SMBus::_cycle_count = 0 protected
Definition at line 104 of file AP_BattMonitor_SMBus.h.
Referenced by get_cycle_count(), and read_cycle_count().
_dev
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_BattMonitor_SMBus::_dev protected
Definition at line 98 of file AP_BattMonitor_SMBus.h.
Referenced by init(), AP_BattMonitor_SMBus_SUI::init(), read_block(), AP_BattMonitor_SMBus_SUI::read_block_bare(), and read_word().
_full_charge_capacity
uint16_t AP_BattMonitor_SMBus::_full_charge_capacity protected
Definition at line 102 of file AP_BattMonitor_SMBus.h.
Referenced by read(), and read_full_charge_capacity().
_has_cell_voltages
bool AP_BattMonitor_SMBus::_has_cell_voltages protected
Definition at line 103 of file AP_BattMonitor_SMBus.h.
Referenced by has_cell_voltages(), AP_BattMonitor_SMBus_SUI::read_cell_voltages(), AP_BattMonitor_SMBus_Generic::timer(), and AP_BattMonitor_SMBus_NeoDesign::timer().
_has_cycle_count
bool AP_BattMonitor_SMBus::_has_cycle_count protected
Definition at line 105 of file AP_BattMonitor_SMBus.h.
Referenced by get_cycle_count(), and read_cycle_count().
_has_temperature
bool AP_BattMonitor_SMBus::_has_temperature protected
Definition at line 106 of file AP_BattMonitor_SMBus.h.
Referenced by has_temperature(), read_temp(), and AP_BattMonitor_SMBus_Rotoye::read_temp().
_pec_supported
bool AP_BattMonitor_SMBus::_pec_supported protected
Definition at line 99 of file AP_BattMonitor_SMBus.h.
Referenced by AP_BattMonitor_SMBus_NeoDesign::AP_BattMonitor_SMBus_NeoDesign(), AP_BattMonitor_SMBus_SUI::AP_BattMonitor_SMBus_SUI(), AP_BattMonitor_SMBus_Generic::check_pec_support(), read_block(), and read_word().
_serial_number
int32_t AP_BattMonitor_SMBus::_serial_number = -1 protected
Definition at line 101 of file AP_BattMonitor_SMBus.h.
Referenced by read(), and read_serial_number().
timer_handle
AP_HAL::Device::PeriodicHandle AP_BattMonitor_SMBus::timer_handle protected
Definition at line 110 of file AP_BattMonitor_SMBus.h.
Referenced by init(), and AP_BattMonitor_SMBus_SUI::init().
var_info
const AP_Param::GroupInfo AP_BattMonitor_SMBus::var_info static
Initial value:
= {
    AP_GROUPINFO("I2C_BUS", 10, AP_BattMonitor_SMBus, _bus, 0),
    AP_GROUPINFO("I2C_ADDR", 11, AP_BattMonitor_SMBus, _address, AP_BATTMONITOR_SMBUS_I2C_ADDR),
    AP_GROUPEND
}
Definition at line 11 of file AP_BattMonitor_SMBus.h.
Referenced by AP_BattMonitor_SMBus().
The documentation for this class was generated from the following files:
libraries/AP_BattMonitor/AP_BattMonitor_SMBus.h
libraries/AP_BattMonitor/AP_BattMonitor_SMBus.cpp