APM:Libraries: SITL::Submarine Class Reference
SITL::Submarine Class Reference
#include <SIM_Submarine.h>
Public Member Functions
Submarine (const char *frame_str)
void update (const struct sitl_input &input) override
Static Public Member Functions
static Aircraft * create (const char *frame_str)
Protected Member Functions
bool on_ground () const override
float rangefinder_beam_width () const override
float perpendicular_distance_to_rangefinder_surface () const override
float calculate_sea_floor_depth (const Vector3d &) const
Calculate sea floor depth from submarine position This creates a non planar floor for rangefinder sensor test TODO: Create a better sea floor with procedural generatation.
void calculate_forces (const struct sitl_input &input, Vector3f &rot_accel, Vector3f &body_accel)
float calculate_buoyancy_acceleration ()
Calculate buoyancy force of the frame.
void calculate_drag_force (const Vector3f &velocity, const Vector3f &drag_coefficient, Vector3f &force) const
Calculate drag force against body.
void calculate_angular_drag_torque (const Vector3f &angular_velocity, const Vector3f &drag_coefficient, Vector3f &torque) const
Calculate angular drag torque using the equivalente sphere area and assuming a laminar external flow.
void calculate_buoyancy_torque (Vector3f &torque)
Calculate the torque induced by buoyancy foam.
Protected Attributes
const float water_density = 1023.6
struct {
float length = 0.457
float width = 0.338
float height = 0.254
float weight = 10.5
float thrust = 51.48
float thruster_mount_radius = 0.25
float equivalent_sphere_radius = 0.2
float volume = 4 * M_PI * powf(equivalent_sphere_radius, 3) / 3
float density = 500
float mass = volume * density
float moment_of_inertia = 2 * (mass * powf(equivalent_sphere_radius, 2) / 5)
const Vector3f linear_drag_coefficient = Vector3f(1.4, 1.8, 2.0)
const Vector3f angular_drag_coefficient = Vector3f(1.05, 1.05, 1.05)
float equivalent_sphere_area = M_PI_4 * powf(volume * 3.0f / 4.0f, 2.0f / 3.0f)
} frame_property
Frame * frame
Thruster * thrusters
uint8_t n_thrusters
Detailed Description
Definition at line 45 of file SIM_Submarine.h.
Constructor & Destructor Documentation
Submarine()
Submarine::Submarine (const char * frame_str)
Definition at line 50 of file SIM_Submarine.cpp.
Referenced by create().
Member Function Documentation
calculate_angular_drag_torque()
void Submarine::calculate_angular_drag_torque (const Vector3f & angular_velocity, const Vector3f & drag_coefficient, Vector3f & torque) const protected
Calculate angular drag torque using the equivalente sphere area and assuming a laminar external flow.
$F_D = C_D*A*\rho*V^2/2$ where: $F_D$ is the drag force $C_D$ is the drag coefficient $A$ is the surface area in contact with the fluid $/rho$ is the fluid density (1000kg/m³ for water) $V$ is the fluid velocity velocity relative to the surface
Parameters
angular_velocity Body frame velocity of fluid
drag_coefficient Rotational drag coefficient of body
It's necessary to keep the velocity orientation from the body frame. To do so, a mathematical artifice is used to do velocity square but without loosing the direction. $(|V|/V)*V^2$ = $|V|*V$
Definition at line 191 of file SIM_Submarine.cpp.
Referenced by calculate_forces().
calculate_buoyancy_acceleration()
float Submarine::calculate_buoyancy_acceleration () protected
Calculate buoyancy force of the frame.
Returns
float
Definition at line 213 of file SIM_Submarine.cpp.
Referenced by calculate_forces().
calculate_buoyancy_torque()
void Submarine::calculate_buoyancy_torque (Vector3f & torque) protected
Calculate the torque induced by buoyancy foam.
Parameters
torque Output torques
Definition at line 129 of file SIM_Submarine.cpp.
Referenced by calculate_forces().
calculate_drag_force()
void Submarine::calculate_drag_force (const Vector3f & velocity, const Vector3f & drag_coefficient, Vector3f & force) const protected
Calculate drag force against body.
Parameters
velocity Body frame velocity of fluid
drag_coefficient Drag coefficient of body
force Output forces $ F_D = rho * v^2 * A * C_D / 2 $ rho = water density (kg/m^3), V = velocity (m/s), A = area (m^2), C_D = drag_coefficient
It's necessary to keep the velocity orientation from the body frame. To do so, a mathematical artifice is used to do velocity square but without loosing the direction. $(|V|/V)*V^2$ = $|V|*V$
Definition at line 160 of file SIM_Submarine.cpp.
Referenced by calculate_forces().
calculate_forces()
void Submarine::calculate_forces (const struct sitl_input & input, Vector3f & rot_accel, Vector3f & body_accel) protected
Definition at line 75 of file SIM_Submarine.cpp.
Referenced by update().
calculate_sea_floor_depth()
float Submarine::calculate_sea_floor_depth (const Vector3d &) const protected
Calculate sea floor depth from submarine position This creates a non planar floor for rangefinder sensor test TODO: Create a better sea floor with procedural generatation.
Parameters
position
Returns
float
Definition at line 146 of file SIM_Submarine.cpp.
Referenced by calculate_forces(), and perpendicular_distance_to_rangefinder_surface().
create()
static Aircraft * SITL::Submarine::create (const char * frame_str) inline static
Definition at line 53 of file SIM_Submarine.h.
on_ground()
bool Submarine::on_ground () const override protected
Definition at line 257 of file SIM_Submarine.cpp.
perpendicular_distance_to_rangefinder_surface()
float Submarine::perpendicular_distance_to_rangefinder_surface () const override protected
Definition at line 68 of file SIM_Submarine.cpp.
rangefinder_beam_width()
float SITL::Submarine::rangefinder_beam_width () const inline override protected
Definition at line 92 of file SIM_Submarine.h.
update()
void Submarine::update (const struct sitl_input & input) override
Definition at line 234 of file SIM_Submarine.cpp.
Member Data Documentation
angular_drag_coefficient
const Vector3f SITL::Submarine::angular_drag_coefficient = Vector3f(1.05, 1.05, 1.05)
Definition at line 80 of file SIM_Submarine.h.
density
float SITL::Submarine::density = 500
Definition at line 71 of file SIM_Submarine.h.
equivalent_sphere_area
float SITL::Submarine::equivalent_sphere_area = M_PI_4 * powf(volume * 3.0f / 4.0f, 2.0f / 3.0f)
Definition at line 86 of file SIM_Submarine.h.
equivalent_sphere_radius
float SITL::Submarine::equivalent_sphere_radius = 0.2
Definition at line 68 of file SIM_Submarine.h.
frame
Frame* SITL::Submarine::frame protected
Definition at line 109 of file SIM_Submarine.h.
[struct]
const struct { ... } SITL::Submarine::frame_property
Referenced by calculate_angular_drag_torque(), calculate_buoyancy_acceleration(), calculate_drag_force(), and calculate_forces().
height
float SITL::Submarine::height = 0.254
Definition at line 64 of file SIM_Submarine.h.
length
float SITL::Submarine::length = 0.457
Definition at line 62 of file SIM_Submarine.h.
linear_drag_coefficient
const Vector3f SITL::Submarine::linear_drag_coefficient = Vector3f(1.4, 1.8, 2.0)
Definition at line 78 of file SIM_Submarine.h.
mass
float SITL::Submarine::mass = volume * density
Definition at line 72 of file SIM_Submarine.h.
moment_of_inertia
float SITL::Submarine::moment_of_inertia = 2 * (mass * powf(equivalent_sphere_radius, 2) / 5)
Definition at line 75 of file SIM_Submarine.h.
n_thrusters
uint8_t SITL::Submarine::n_thrusters protected
Definition at line 111 of file SIM_Submarine.h.
Referenced by calculate_forces(), and Submarine().
thrust
float SITL::Submarine::thrust = 51.48
Definition at line 66 of file SIM_Submarine.h.
Referenced by calculate_forces().
thruster_mount_radius
float SITL::Submarine::thruster_mount_radius = 0.25
Definition at line 67 of file SIM_Submarine.h.
thrusters
Thruster* SITL::Submarine::thrusters protected
Definition at line 110 of file SIM_Submarine.h.
Referenced by calculate_forces(), and Submarine().
volume
float SITL::Submarine::volume = 4 * M_PI * powf(equivalent_sphere_radius, 3) / 3
Definition at line 70 of file SIM_Submarine.h.
water_density
const float SITL::Submarine::water_density = 1023.6 protected
Definition at line 59 of file SIM_Submarine.h.
Referenced by calculate_drag_force().
weight
float SITL::Submarine::weight = 10.5
Definition at line 65 of file SIM_Submarine.h.
width
float SITL::Submarine::width = 0.338
Definition at line 63 of file SIM_Submarine.h.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_Submarine.h
libraries/SITL/SIM_Submarine.cpp