APM:Libraries: SITL::ADSB_Sagetech_MXS Class Reference
SITL::ADSB_Sagetech_MXS Class Reference
#include <SIM_ADSB_Sagetech_MXS.h>
Classes
class Ack
class DataRequest
class FlightIDMessage
class GPS
class Installation
class ModeStatusReport
class ModeStatusReportBuffer
class Operating
class PackedMessage
class StateVectorReport
union StateVectorReport_ReportStructure
class StateVectorReportBuffer
class TargetRequest
union u
Public Member Functions
void update (const class Aircraft *sitl_model)
Public Member Functions inherited from SITL::SerialDevice
SerialDevice (uint16_t tx_bufsize=512, uint16_t rx_bufsize=512)
ssize_t read_from_device (char *buffer, size_t size) const
ssize_t write_to_device (const char *buffer, size_t size) const
void set_autopilot_baud (uint32_t baud)
ssize_t read_from_autopilot (char *buffer, size_t size) const
virtual ssize_t write_to_autopilot (const char *buffer, size_t size) const
virtual uint32_t device_baud () const
Private Types
enum class MsgType : uint8_t {
INSTALLATION = 0x01 , FLIGHTID = 0x02 , OPMSG = 0x03 , GPS = 0x04 ,
DATAREQ = 0x05 , TARGETREQUEST = 0x0B , ACK = 0x80 , STATEVECTORREPORT = 0x91 ,
MODESTATUSREPORT = 0x92
}
enum class OperatingMode { OFF , MAINTENANCE }
enum class InputState { WANT_START_BYTE = 56 , WANT_PREAMBLE = 57 , WANT_PAYLOAD = 60 , WANT_CHECKSUM = 61 }
Private Member Functions
void update_serial_input ()
void update_serial_output (const Aircraft *sitl_model)
void update_serial_output_vehicles (const Aircraft *sitl_model)
void pack_scaled_geocoord (uint8_t buf[3], float coord)
void pack_scaled_alt (uint8_t buf[3], float alt_m)
uint8_t scaled_groundspeed (float speed_m_s) const
void pack_scaled_groundspeed (uint8_t dest[1], float speed_m_s) const
void pack_scaled_airspeed (uint8_t dest[2], float speed_m_s) const
void pack_scaled_vertical_rate (uint8_t dest[2], float speed_m_s) const
void pack_int32_into_uint8_ts (int32_t source, uint8_t dest[3])
void send_vehicle_message (const class ADSB_Vehicle &vehicle)
void send_vehicle_message_state_vector (const class ADSB_Vehicle &vehicle)
void send_vehicle_message_status_report (const class ADSB_Vehicle &vehicle)
void update_rf_output ()
void update_rf_input ()
bool handle_message (const SITL::ADSB_Sagetech_MXS::Installation &)
bool handle_message (const SITL::ADSB_Sagetech_MXS::FlightIDMessage &)
bool handle_message (const SITL::ADSB_Sagetech_MXS::Operating &)
bool handle_message (const SITL::ADSB_Sagetech_MXS::GPS &)
bool handle_message (const SITL::ADSB_Sagetech_MXS::DataRequest &)
bool handle_message (const SITL::ADSB_Sagetech_MXS::TargetRequest &)
bool _handle_message ()
void handle_message ()
double lon_string_to_double (const uint8_t *lat)
double lat_string_to_double (const uint8_t *lng)
void assert_good_flight_id ()
void move_preamble_in_buffer (uint8_t search_start_pos=0)
void set_input_state (InputState newstate)
Private Attributes
enum SITL::ADSB_Sagetech_MXS::OperatingMode operating_mode
union SITL::ADSB_Sagetech_MXS::u msg
uint8_t buflen
struct {
bool send
MsgType ackType
uint8_t ackId
} ack_info
uint8_t msgid
struct {
struct {
double lat
double lng
} gps
} info_from_vehicle
char flight_id [8]
uint32_t flight_id_set_time_ms
enum SITL::ADSB_Sagetech_MXS::InputState input_state = InputState::WANT_START_BYTE
Additional Inherited Members
Protected Member Functions inherited from SITL::SerialDevice
bool init_sitl_pointer () WARN_IF_UNUSED
Protected Attributes inherited from SITL::SerialDevice
class SIM * _sitl
ByteBuffer * to_autopilot
ByteBuffer * from_autopilot
Detailed Description
Definition at line 27 of file SIM_ADSB_Sagetech_MXS.h.
Member Enumeration Documentation
InputState
enum class SITL::ADSB_Sagetech_MXS::InputState strong private
Enumerator
WANT_START_BYTE
WANT_PREAMBLE
WANT_PAYLOAD
WANT_CHECKSUM
Definition at line 387 of file SIM_ADSB_Sagetech_MXS.h.
MsgType
enum class SITL::ADSB_Sagetech_MXS::MsgType : uint8_t strong private
Enumerator
INSTALLATION
FLIGHTID
OPMSG
GPS
DATAREQ
TARGETREQUEST
ACK
STATEVECTORREPORT
MODESTATUSREPORT
Definition at line 56 of file SIM_ADSB_Sagetech_MXS.h.
OperatingMode
enum class SITL::ADSB_Sagetech_MXS::OperatingMode strong private
Enumerator
OFF
MAINTENANCE
Definition at line 103 of file SIM_ADSB_Sagetech_MXS.h.
Member Function Documentation
_handle_message()
bool ADSB_Sagetech_MXS::_handle_message () private
Definition at line 102 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by handle_message().
assert_good_flight_id()
void ADSB_Sagetech_MXS::assert_good_flight_id () private
Definition at line 160 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by handle_message().
handle_message() [1/7]
void ADSB_Sagetech_MXS::handle_message () private
Definition at line 132 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by _handle_message(), and update_serial_input().
handle_message() [2/7]
bool ADSB_Sagetech_MXS::handle_message (const SITL::ADSB_Sagetech_MXS::DataRequest & _msg) private
Definition at line 231 of file SIM_ADSB_Sagetech_MXS.cpp.
handle_message() [3/7]
bool ADSB_Sagetech_MXS::handle_message (const SITL::ADSB_Sagetech_MXS::FlightIDMessage & _msg) private
Definition at line 181 of file SIM_ADSB_Sagetech_MXS.cpp.
handle_message() [4/7]
bool ADSB_Sagetech_MXS::handle_message (const SITL::ADSB_Sagetech_MXS::GPS & _msg) private
Definition at line 220 of file SIM_ADSB_Sagetech_MXS.cpp.
handle_message() [5/7]
bool ADSB_Sagetech_MXS::handle_message (const SITL::ADSB_Sagetech_MXS::Installation & opmsg) private
Definition at line 144 of file SIM_ADSB_Sagetech_MXS.cpp.
handle_message() [6/7]
bool ADSB_Sagetech_MXS::handle_message (const SITL::ADSB_Sagetech_MXS::Operating & _msg) private
Definition at line 193 of file SIM_ADSB_Sagetech_MXS.cpp.
handle_message() [7/7]
bool ADSB_Sagetech_MXS::handle_message (const SITL::ADSB_Sagetech_MXS::TargetRequest & _msg) private
Definition at line 242 of file SIM_ADSB_Sagetech_MXS.cpp.
lat_string_to_double()
double ADSB_Sagetech_MXS::lat_string_to_double (const uint8_t * lng) private
Definition at line 211 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by handle_message(), and lon_string_to_double().
lon_string_to_double()
double ADSB_Sagetech_MXS::lon_string_to_double (const uint8_t * lat) private
Definition at line 205 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by handle_message().
move_preamble_in_buffer()
void ADSB_Sagetech_MXS::move_preamble_in_buffer (uint8_t search_start_pos = 0) private
Definition at line 21 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by update_serial_input().
pack_int32_into_uint8_ts()
void ADSB_Sagetech_MXS::pack_int32_into_uint8_ts (int32_t source, uint8_t dest[3]) private
Definition at line 305 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by pack_scaled_alt(), pack_scaled_geocoord(), send_vehicle_message_state_vector(), and send_vehicle_message_status_report().
pack_scaled_airspeed()
void ADSB_Sagetech_MXS::pack_scaled_airspeed (uint8_t dest[2], float speed_m_s) const private
Definition at line 352 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by send_vehicle_message_state_vector().
pack_scaled_alt()
void ADSB_Sagetech_MXS::pack_scaled_alt (uint8_t buf[3], float alt_m) private
Definition at line 298 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by send_vehicle_message_state_vector().
pack_scaled_geocoord()
void ADSB_Sagetech_MXS::pack_scaled_geocoord (uint8_t buf[3], float coord) private
Definition at line 290 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by send_vehicle_message_state_vector().
pack_scaled_groundspeed()
void ADSB_Sagetech_MXS::pack_scaled_groundspeed (uint8_t dest[1], float speed_m_s) const private
Definition at line 346 of file SIM_ADSB_Sagetech_MXS.cpp.
pack_scaled_vertical_rate()
void ADSB_Sagetech_MXS::pack_scaled_vertical_rate (uint8_t dest[2], float speed_m_s) const private
Definition at line 359 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by send_vehicle_message_state_vector().
scaled_groundspeed()
uint8_t ADSB_Sagetech_MXS::scaled_groundspeed (float speed_m_s) const private
Definition at line 313 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by pack_scaled_groundspeed().
send_vehicle_message()
void ADSB_Sagetech_MXS::send_vehicle_message (const class ADSB_Vehicle & vehicle) private
Definition at line 366 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by update_serial_output_vehicles().
send_vehicle_message_state_vector()
void ADSB_Sagetech_MXS::send_vehicle_message_state_vector (const class ADSB_Vehicle & vehicle) private
Definition at line 372 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by send_vehicle_message().
send_vehicle_message_status_report()
void ADSB_Sagetech_MXS::send_vehicle_message_status_report (const class ADSB_Vehicle & vehicle) private
Definition at line 469 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by send_vehicle_message().
set_input_state()
void SITL::ADSB_Sagetech_MXS::set_input_state (InputState newstate) inline private
Definition at line 393 of file SIM_ADSB_Sagetech_MXS.h.
Referenced by update_serial_input().
update()
void ADSB_Sagetech_MXS::update (const class Aircraft * sitl_model)
Definition at line 539 of file SIM_ADSB_Sagetech_MXS.cpp.
update_rf_input()
void ADSB_Sagetech_MXS::update_rf_input () private
Definition at line 529 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by update().
update_rf_output()
void ADSB_Sagetech_MXS::update_rf_output () private
Definition at line 534 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by update().
update_serial_input()
void ADSB_Sagetech_MXS::update_serial_input () private
Definition at line 36 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by update().
update_serial_output()
void ADSB_Sagetech_MXS::update_serial_output (const Aircraft * sitl_model) private
Definition at line 252 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by update().
update_serial_output_vehicles()
void ADSB_Sagetech_MXS::update_serial_output_vehicles (const Aircraft * sitl_model) private
Definition at line 274 of file SIM_ADSB_Sagetech_MXS.cpp.
Referenced by update_serial_output().
Member Data Documentation
[struct]
struct { ... } SITL::ADSB_Sagetech_MXS::ack_info
Referenced by handle_message(), and update_serial_output().
ackId
uint8_t SITL::ADSB_Sagetech_MXS::ackId
Definition at line 357 of file SIM_ADSB_Sagetech_MXS.h.
ackType
MsgType SITL::ADSB_Sagetech_MXS::ackType
Definition at line 356 of file SIM_ADSB_Sagetech_MXS.h.
buflen
uint8_t SITL::ADSB_Sagetech_MXS::buflen private
Definition at line 333 of file SIM_ADSB_Sagetech_MXS.h.
Referenced by move_preamble_in_buffer(), and update_serial_input().
flight_id
char SITL::ADSB_Sagetech_MXS::flight_id[8] private
Definition at line 370 of file SIM_ADSB_Sagetech_MXS.h.
Referenced by assert_good_flight_id(), and handle_message().
flight_id_set_time_ms
uint32_t SITL::ADSB_Sagetech_MXS::flight_id_set_time_ms private
Definition at line 371 of file SIM_ADSB_Sagetech_MXS.h.
Referenced by handle_message().
[struct]
struct { ... } SITL::ADSB_Sagetech_MXS::gps
[struct]
struct { ... } SITL::ADSB_Sagetech_MXS::info_from_vehicle
Referenced by handle_message().
input_state
enum SITL::ADSB_Sagetech_MXS::InputState SITL::ADSB_Sagetech_MXS::input_state = InputState::WANT_START_BYTE private
Referenced by set_input_state(), and update_serial_input().
lat
double SITL::ADSB_Sagetech_MXS::lat
Definition at line 364 of file SIM_ADSB_Sagetech_MXS.h.
lng
double SITL::ADSB_Sagetech_MXS::lng
Definition at line 365 of file SIM_ADSB_Sagetech_MXS.h.
msg
union SITL::ADSB_Sagetech_MXS::u SITL::ADSB_Sagetech_MXS::msg private
Referenced by _handle_message(), handle_message(), move_preamble_in_buffer(), and update_serial_input().
msgid
uint8_t SITL::ADSB_Sagetech_MXS::msgid private
Definition at line 360 of file SIM_ADSB_Sagetech_MXS.h.
Referenced by send_vehicle_message_state_vector(), send_vehicle_message_status_report(), and update_serial_output().
operating_mode
enum SITL::ADSB_Sagetech_MXS::OperatingMode SITL::ADSB_Sagetech_MXS::operating_mode private
Referenced by handle_message().
send
bool SITL::ADSB_Sagetech_MXS::send
Definition at line 355 of file SIM_ADSB_Sagetech_MXS.h.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_ADSB_Sagetech_MXS.h
libraries/SITL/SIM_ADSB_Sagetech_MXS.cpp