APM:Libraries: SITL::RAMTRON Class Reference
SITL::RAMTRON Class Reference abstract
#include <SIM_RAMTRON.h>
Public Member Functions
int rdwr (uint8_t count, SPI::spi_ioc_transfer *&data) override
Public Member Functions inherited from SITL::SPIDevice
virtual void init ()
virtual void update (const class Aircraft &aircraft)
Protected Member Functions
virtual void fill_rdid (uint8_t *buf, uint8_t len)=0
virtual uint32_t storage_size () const =0
virtual const char * filename () const =0
Private Types
enum class State { WAITING , READING_RDID , READING , WRITING }
Private Member Functions
void open_storage_fd ()
Private Attributes
enum SITL::RAMTRON::State state = State::WAITING
bool write_enabled
uint32_t xfr_addr
int storage_fd = -1
Detailed Description
Definition at line 15 of file SIM_RAMTRON.h.
Member Enumeration Documentation
State
enum class SITL::RAMTRON::State strong private
Enumerator
WAITING
READING_RDID
READING
WRITING
Definition at line 29 of file SIM_RAMTRON.h.
Member Function Documentation
filename()
virtual const char * SITL::RAMTRON::filename () const protected pure virtual
Implemented in SITL::RAMTRON_FM25V02.
Referenced by open_storage_fd().
fill_rdid()
virtual void SITL::RAMTRON::fill_rdid (uint8_t * buf, uint8_t len) protected pure virtual
Implemented in SITL::RAMTRON_FM25V02.
Referenced by rdwr().
open_storage_fd()
void RAMTRON::open_storage_fd () private
Definition at line 17 of file SIM_RAMTRON.cpp.
Referenced by rdwr().
rdwr()
int RAMTRON::rdwr (uint8_t count, SPI::spi_ioc_transfer *& data) override virtual
Implements SITL::SPIDevice.
Definition at line 36 of file SIM_RAMTRON.cpp.
storage_size()
virtual uint32_t SITL::RAMTRON::storage_size () const protected pure virtual
Implemented in SITL::RAMTRON_FM25V02.
Referenced by open_storage_fd(), and rdwr().
Member Data Documentation
state
enum SITL::RAMTRON::State SITL::RAMTRON::state = State::WAITING private
Referenced by rdwr().
storage_fd
int SITL::RAMTRON::storage_fd = -1 private
Definition at line 40 of file SIM_RAMTRON.h.
Referenced by open_storage_fd(), and rdwr().
write_enabled
bool SITL::RAMTRON::write_enabled private
Definition at line 36 of file SIM_RAMTRON.h.
Referenced by rdwr().
xfr_addr
uint32_t SITL::RAMTRON::xfr_addr private
Definition at line 37 of file SIM_RAMTRON.h.
Referenced by rdwr().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_RAMTRON.h
libraries/SITL/SIM_RAMTRON.cpp