APM:Libraries: AP_LoggerTest_AllTypes Class Reference
AP_LoggerTest_AllTypes Class Reference
Public Member Functions
void setup () override
void loop () override
Private Member Functions
void Log_Write_TypeMessages ()
void Log_Write_TypeMessages_Log_Write ()
void flush_logger (AP_Logger &logger)
Private Attributes
AP_Int32 log_bitmask
AP_Logger logger
AP_Scheduler scheduler
Detailed Description
Definition at line 101 of file AP_Logger_AllTypes.cpp.
Member Function Documentation
flush_logger()
void AP_LoggerTest_AllTypes::flush_logger (AP_Logger & logger) private
Definition at line 118 of file AP_Logger_AllTypes.cpp.
Referenced by Log_Write_TypeMessages(), and Log_Write_TypeMessages_Log_Write().
Log_Write_TypeMessages()
void AP_LoggerTest_AllTypes::Log_Write_TypeMessages () private
Definition at line 132 of file AP_Logger_AllTypes.cpp.
Referenced by setup().
Log_Write_TypeMessages_Log_Write()
void AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write () private
Definition at line 182 of file AP_Logger_AllTypes.cpp.
Referenced by setup().
loop()
void AP_LoggerTest_AllTypes::loop (void) override virtual
Implements AP_HAL::HAL::Callbacks.
Definition at line 264 of file AP_Logger_AllTypes.cpp.
setup()
void AP_LoggerTest_AllTypes::setup (void) override virtual
Implements AP_HAL::HAL::Callbacks.
Definition at line 246 of file AP_Logger_AllTypes.cpp.
Member Data Documentation
log_bitmask
AP_Int32 AP_LoggerTest_AllTypes::log_bitmask private
Definition at line 108 of file AP_Logger_AllTypes.cpp.
Referenced by setup().
logger
AP_Logger AP_LoggerTest_AllTypes::logger private
Definition at line 109 of file AP_Logger_AllTypes.cpp.
Referenced by Log_Write_TypeMessages(), Log_Write_TypeMessages_Log_Write(), and setup().
scheduler
AP_Scheduler AP_LoggerTest_AllTypes::scheduler private
Definition at line 110 of file AP_Logger_AllTypes.cpp.
The documentation for this class was generated from the following file:
libraries/AP_Logger/examples/AP_Logger_AllTypes/AP_Logger_AllTypes.cpp