APM:Libraries: AC_PrecLand_Backend Class Reference
AC_PrecLand_Backend Class Reference abstract
#include <AC_PrecLand_Backend.h>
Public Member Functions
AC_PrecLand_Backend (const AC_PrecLand &frontend, AC_PrecLand::precland_state &state)
virtual ~AC_PrecLand_Backend ()
virtual void init ()=0
virtual void update ()=0
virtual bool get_los_body (Vector3f &dir_body)=0
virtual uint32_t los_meas_time_ms ()=0
virtual bool have_los_meas ()=0
virtual float distance_to_target ()
virtual void handle_msg (const mavlink_landing_target_t &packet, uint32_t timestamp_ms)
int8_t get_bus (void) const
Protected Attributes
const AC_PrecLand & _frontend
AC_PrecLand::precland_state & _state
Detailed Description
Definition at line 12 of file AC_PrecLand_Backend.h.
Constructor & Destructor Documentation
AC_PrecLand_Backend()
AC_PrecLand_Backend::AC_PrecLand_Backend (const AC_PrecLand & frontend, AC_PrecLand::precland_state & state) inline
Definition at line 16 of file AC_PrecLand_Backend.h.
~AC_PrecLand_Backend()
virtual AC_PrecLand_Backend::~AC_PrecLand_Backend () inline virtual
Definition at line 21 of file AC_PrecLand_Backend.h.
Member Function Documentation
distance_to_target()
virtual float AC_PrecLand_Backend::distance_to_target () inline virtual
Reimplemented in AC_PrecLand_Companion, and AC_PrecLand_SITL.
Definition at line 40 of file AC_PrecLand_Backend.h.
Referenced by AC_PrecLand::construct_pos_meas_using_rangefinder().
get_bus()
int8_t AC_PrecLand_Backend::get_bus (void) const inline
Definition at line 46 of file AC_PrecLand_Backend.h.
Referenced by AC_PrecLand_IRLock::init(), and AC_PrecLand_SITL_Gazebo::init().
get_los_body()
virtual bool AC_PrecLand_Backend::get_los_body (Vector3f & dir_body) pure virtual
Implemented in AC_PrecLand_Companion, AC_PrecLand_IRLock, AC_PrecLand_SITL, and AC_PrecLand_SITL_Gazebo.
Referenced by AC_PrecLand::retrieve_los_meas().
handle_msg()
virtual void AC_PrecLand_Backend::handle_msg (const mavlink_landing_target_t & packet, uint32_t timestamp_ms) inline virtual
Reimplemented in AC_PrecLand_Companion.
Definition at line 43 of file AC_PrecLand_Backend.h.
Referenced by AC_PrecLand::handle_msg().
have_los_meas()
virtual bool AC_PrecLand_Backend::have_los_meas () pure virtual
Implemented in AC_PrecLand_Companion, AC_PrecLand_IRLock, AC_PrecLand_SITL, and AC_PrecLand_SITL_Gazebo.
init()
virtual void AC_PrecLand_Backend::init () pure virtual
Implemented in AC_PrecLand_Companion, AC_PrecLand_IRLock, AC_PrecLand_SITL, and AC_PrecLand_SITL_Gazebo.
Referenced by AC_PrecLand::init().
los_meas_time_ms()
virtual uint32_t AC_PrecLand_Backend::los_meas_time_ms () pure virtual
Implemented in AC_PrecLand_Companion, AC_PrecLand_IRLock, AC_PrecLand_SITL, and AC_PrecLand_SITL_Gazebo.
Referenced by AC_PrecLand::retrieve_los_meas().
update()
virtual void AC_PrecLand_Backend::update () pure virtual
Implemented in AC_PrecLand_Companion, AC_PrecLand_IRLock, AC_PrecLand_SITL, and AC_PrecLand_SITL_Gazebo.
Referenced by AC_PrecLand::update().
Member Data Documentation
_frontend
const AC_PrecLand& AC_PrecLand_Backend::_frontend protected
Definition at line 49 of file AC_PrecLand_Backend.h.
Referenced by get_bus(), and AC_PrecLand_SITL::update().
_state
AC_PrecLand::precland_state& AC_PrecLand_Backend::_state protected
Definition at line 50 of file AC_PrecLand_Backend.h.
Referenced by AC_PrecLand_Companion::init(), AC_PrecLand_IRLock::update(), AC_PrecLand_SITL::update(), and AC_PrecLand_SITL_Gazebo::update().
The documentation for this class was generated from the following file:
libraries/AC_PrecLand/AC_PrecLand_Backend.h