APM:Libraries: SITL::I2CRegisters_ConfigurableLength Class Reference
SITL::I2CRegisters_ConfigurableLength Class Reference
#include <SIM_I2CDevice.h>
Public Member Functions
void add_register (const char *name, uint8_t reg, uint8_t len, RegMode mode)
int rdwr (I2C::i2c_rdwr_ioctl_data *&data) override
void set_register (uint8_t reg, uint8_t *data, uint8_t len)
void set_register (uint8_t reg, uint16_t value)
void set_register (uint8_t reg, int16_t value)
void set_register (uint8_t reg, uint8_t value)
void set_register (uint8_t reg, int8_t value)
void get_reg_value (uint8_t reg, uint8_t &value) const
Protected Attributes
uint32_t reg_data [256]
uint8_t reg_data_len [256]
Protected Attributes inherited from SITL::I2CRegisters
const char * regname [256]
Bitmask< 256 > writable_registers
Bitmask< 256 > readable_registers
Additional Inherited Members
Public Types inherited from SITL::I2CRegisters
enum class RegMode { RDONLY = 11 , WRONLY = 22 , RDWR = 33 }
Protected Member Functions inherited from SITL::I2CRegisters
void add_register (const char *name, uint8_t reg, RegMode mode)
void set_debug (bool value)
bool get_debug () const
Detailed Description
Definition at line 42 of file SIM_I2CDevice.h.
Member Function Documentation
add_register()
void SITL::I2CRegisters_ConfigurableLength::add_register (const char * name, uint8_t reg, uint8_t len, RegMode mode)
Definition at line 201 of file SIM_I2CDevice.cpp.
Referenced by SITL::MCP9600::init().
get_reg_value()
void SITL::I2CRegisters_ConfigurableLength::get_reg_value (uint8_t reg, uint8_t & value) const
Definition at line 312 of file SIM_I2CDevice.cpp.
Referenced by SITL::MCP9600::update().
rdwr()
int SITL::I2CRegisters_ConfigurableLength::rdwr (I2C::i2c_rdwr_ioctl_data *& data) override virtual
Implements SITL::I2CRegisters.
Reimplemented in SITL::MCP9600.
Definition at line 260 of file SIM_I2CDevice.cpp.
Referenced by SITL::MCP9600::rdwr().
set_register() [1/5]
void SITL::I2CRegisters_ConfigurableLength::set_register (uint8_t reg, int16_t value)
Definition at line 223 of file SIM_I2CDevice.cpp.
set_register() [2/5]
void SITL::I2CRegisters_ConfigurableLength::set_register (uint8_t reg, int8_t value)
Definition at line 248 of file SIM_I2CDevice.cpp.
set_register() [3/5]
void SITL::I2CRegisters_ConfigurableLength::set_register (uint8_t reg, uint16_t value)
Definition at line 210 of file SIM_I2CDevice.cpp.
set_register() [4/5]
void SITL::I2CRegisters_ConfigurableLength::set_register (uint8_t reg, uint8_t * data, uint8_t len)
Referenced by SITL::MCP9600::init(), and SITL::MCP9600::update().
set_register() [5/5]
void SITL::I2CRegisters_ConfigurableLength::set_register (uint8_t reg, uint8_t value)
Definition at line 236 of file SIM_I2CDevice.cpp.
Member Data Documentation
reg_data
uint32_t SITL::I2CRegisters_ConfigurableLength::reg_data[256] protected
Definition at line 60 of file SIM_I2CDevice.h.
reg_data_len
uint8_t SITL::I2CRegisters_ConfigurableLength::reg_data_len[256] protected
Definition at line 61 of file SIM_I2CDevice.h.
The documentation for this class was generated from the following files:
libraries/SITL/SIM_I2CDevice.h
libraries/SITL/SIM_I2CDevice.cpp