APM:Libraries: AP_InertialSensor_Backend Class Reference
AP_InertialSensor_Backend Class Reference abstract
#include <AP_InertialSensor_Backend.h>
Public Types
enum DevTypes {
DEVTYPE_BMI160 = 0x09 , DEVTYPE_L3G4200D = 0x10 , DEVTYPE_ACC_LSM303D = 0x11 , DEVTYPE_ACC_BMA180 = 0x12 ,
DEVTYPE_ACC_MPU6000 = 0x13 , DEVTYPE_ACC_MPU9250 = 0x16 , DEVTYPE_ACC_IIS328DQ = 0x17 , DEVTYPE_ACC_LSM9DS1 = 0x18 ,
DEVTYPE_GYR_MPU6000 = 0x21 , DEVTYPE_GYR_L3GD20 = 0x22 , DEVTYPE_GYR_MPU9250 = 0x24 , DEVTYPE_GYR_I3G4250D = 0x25 ,
DEVTYPE_GYR_LSM9DS1 = 0x26 , DEVTYPE_INS_ICM20789 = 0x27 , DEVTYPE_INS_ICM20689 = 0x28 , DEVTYPE_INS_BMI055 = 0x29 ,
DEVTYPE_SITL = 0x2A , DEVTYPE_INS_BMI088 = 0x2B , DEVTYPE_INS_ICM20948 = 0x2C , DEVTYPE_INS_ICM20648 = 0x2D ,
DEVTYPE_INS_ICM20649 = 0x2E , DEVTYPE_INS_ICM20602 = 0x2F , DEVTYPE_INS_ICM20601 = 0x30 , DEVTYPE_INS_ADIS1647X = 0x31 ,
DEVTYPE_SERIAL = 0x32 , DEVTYPE_INS_ICM40609 = 0x33 , DEVTYPE_INS_ICM42688 = 0x34 , DEVTYPE_INS_ICM42605 = 0x35 ,
DEVTYPE_INS_ICM40605 = 0x36 , DEVTYPE_INS_IIM42652 = 0x37 , DEVTYPE_BMI270 = 0x38 , DEVTYPE_INS_BMI085 = 0x39 ,
DEVTYPE_INS_ICM42670 = 0x3A , DEVTYPE_INS_ICM45686 = 0x3B , DEVTYPE_INS_SCHA63T = 0x3C
}
Public Member Functions
AP_InertialSensor_Backend (AP_InertialSensor &imu)
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual bool update ()=0
virtual void accumulate ()
virtual void start ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t get_id () const
float get_clip_limit () const
virtual bool get_output_banner (char *banner, uint8_t banner_len)
Protected Member Functions
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel) __RAMFUNC__
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro) __RAMFUNC__
void _publish_gyro (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void apply_gyro_filters (const uint8_t instance, const Vector3f &gyro)
void save_gyro_window (const uint8_t instance, const Vector3f &gyro, uint8_t phase)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0) __RAMFUNC__
void _notify_new_delta_angle (uint8_t instance, const Vector3f &dangle)
void _publish_accel (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0, bool fsync_set=false) __RAMFUNC__
void _notify_new_delta_velocity (uint8_t instance, const Vector3f &dvelocity)
void _set_accel_oversampling (uint8_t instance, uint8_t n)
void _set_gyro_oversampling (uint8_t instance, uint8_t n)
void _set_accel_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_gyro_sensor_rate_sampling_enabled (uint8_t instance, bool value)
void _set_raw_sample_accel_multiplier (uint8_t instance, uint16_t mul)
void _set_raw_sample_gyro_multiplier (uint8_t instance, uint16_t mul)
void _update_sensor_rate (uint16_t &count, uint32_t &start_us, float &rate_hz) const __RAMFUNC__
bool sensors_converging () const
void _set_accel_max_abs_offset (uint8_t instance, float offset)
float _accel_raw_sample_rate (uint8_t instance) const
void _set_accel_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
float _gyro_raw_sample_rate (uint8_t instance) const
void _set_gyro_raw_sample_rate (uint8_t instance, uint16_t rate_hz)
void _publish_temperature (uint8_t instance, float temperature)
void _inc_accel_error_count (uint8_t instance) __RAMFUNC__
void _inc_gyro_error_count (uint8_t instance) __RAMFUNC__
uint16_t _accel_filter_cutoff (void) const
uint16_t _gyro_filter_cutoff (void) const
uint16_t get_loop_rate_hz (void) const
void update_gyro (uint8_t instance) __RAMFUNC__
void update_accel (uint8_t instance) __RAMFUNC__
void set_gyro_orientation (uint8_t instance, enum Rotation rotation)
void set_accel_orientation (uint8_t instance, enum Rotation rotation)
void increment_clip_count (uint8_t instance)
bool enable_fast_sampling (uint8_t instance) const
bool enable_highres_sampling (uint8_t instance) const
uint8_t get_fast_sampling_rate () const
void _notify_new_accel_sensor_rate_sample (uint8_t instance, const Vector3f &accel) __RAMFUNC__
void _notify_new_gyro_sensor_rate_sample (uint8_t instance, const Vector3f &gyro) __RAMFUNC__
void notify_accel_fifo_reset (uint8_t instance) __RAMFUNC__
void notify_gyro_fifo_reset (uint8_t instance) __RAMFUNC__
void log_register_change (uint32_t bus_id, const AP_HAL::Device::checkreg &reg) __RAMFUNC__
void Write_GYR (const uint8_t instance, const uint64_t sample_us, const Vector3f &gyro, bool use_sample_timestamp=false) const __RAMFUNC__
Protected Attributes
AP_InertialSensor & _imu
HAL_Semaphore _sem
float _clip_limit = 15.5f * GRAVITY_MSS
int16_t _id = -1
uint16_t _last_accel_filter_hz
uint16_t _last_gyro_filter_hz
Private Member Functions
bool should_log_imu_raw () const
void log_accel_raw (uint8_t instance, const uint64_t sample_us, const Vector3f &accel) __RAMFUNC__
void log_gyro_raw (uint8_t instance, const uint64_t sample_us, const Vector3f &raw_gyro, const Vector3f &filtered_gyro) __RAMFUNC__
void Write_ACC (const uint8_t instance, const uint64_t sample_us, const Vector3f &accel) const __RAMFUNC__
Detailed Description
Definition at line 39 of file AP_InertialSensor_Backend.h.
Member Enumeration Documentation
DevTypes
enum AP_InertialSensor_Backend::DevTypes
Enumerator
DEVTYPE_BMI160
DEVTYPE_L3G4200D
DEVTYPE_ACC_LSM303D
DEVTYPE_ACC_BMA180
DEVTYPE_ACC_MPU6000
DEVTYPE_ACC_MPU9250
DEVTYPE_ACC_IIS328DQ
DEVTYPE_ACC_LSM9DS1
DEVTYPE_GYR_MPU6000
DEVTYPE_GYR_L3GD20
DEVTYPE_GYR_MPU9250
DEVTYPE_GYR_I3G4250D
DEVTYPE_GYR_LSM9DS1
DEVTYPE_INS_ICM20789
DEVTYPE_INS_ICM20689
DEVTYPE_INS_BMI055
DEVTYPE_SITL
DEVTYPE_INS_BMI088
DEVTYPE_INS_ICM20948
DEVTYPE_INS_ICM20648
DEVTYPE_INS_ICM20649
DEVTYPE_INS_ICM20602
DEVTYPE_INS_ICM20601
DEVTYPE_INS_ADIS1647X
DEVTYPE_SERIAL
DEVTYPE_INS_ICM40609
DEVTYPE_INS_ICM42688
DEVTYPE_INS_ICM42605
DEVTYPE_INS_ICM40605
DEVTYPE_INS_IIM42652
DEVTYPE_BMI270
DEVTYPE_INS_BMI085
DEVTYPE_INS_ICM42670
DEVTYPE_INS_ICM45686
DEVTYPE_INS_SCHA63T
Definition at line 96 of file AP_InertialSensor_Backend.h.
Constructor & Destructor Documentation
AP_InertialSensor_Backend() [1/2]
AP_InertialSensor_Backend::AP_InertialSensor_Backend (AP_InertialSensor & imu)
Definition at line 22 of file AP_InertialSensor_Backend.cpp.
AP_InertialSensor_Backend() [2/2]
AP_InertialSensor_Backend::AP_InertialSensor_Backend (const AP_InertialSensor_Backend & that) delete
~AP_InertialSensor_Backend()
virtual AP_InertialSensor_Backend::~AP_InertialSensor_Backend (void) inline virtual
Definition at line 47 of file AP_InertialSensor_Backend.h.
Member Function Documentation
_accel_filter_cutoff()
uint16_t AP_InertialSensor_Backend::_accel_filter_cutoff (void) const inline protected
Definition at line 255 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_L3G4200D::_accel_init(), and update_accel().
_accel_raw_sample_rate()
float AP_InertialSensor_Backend::_accel_raw_sample_rate (uint8_t instance) const inline protected
Definition at line 221 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_ADIS1647x::read_sensor32_delta(), and update_accel().
_gyro_filter_cutoff()
uint16_t AP_InertialSensor_Backend::_gyro_filter_cutoff (void) const inline protected
Definition at line 258 of file AP_InertialSensor_Backend.h.
Referenced by update_gyro().
_gyro_raw_sample_rate()
float AP_InertialSensor_Backend::_gyro_raw_sample_rate (uint8_t instance) const inline protected
Definition at line 232 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_ADIS1647x::read_sensor32_delta(), and update_gyro().
_inc_accel_error_count()
void AP_InertialSensor_Backend::_inc_accel_error_count (uint8_t instance) protected
Definition at line 729 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_LSM9DS0::_poll_data(), AP_InertialSensor_LSM9DS1::_poll_data(), AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), AP_InertialSensor_SCHA63T::read_accel(), AP_InertialSensor_BMI270::read_fifo(), AP_InertialSensor_Invensensev3::read_fifo(), AP_InertialSensor_BMI055::read_fifo_accel(), and AP_InertialSensor_BMI088::read_fifo_accel().
_inc_gyro_error_count()
void AP_InertialSensor_Backend::_inc_gyro_error_count (uint8_t instance) protected
Definition at line 735 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_LSM9DS0::_poll_data(), AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), AP_InertialSensor_BMI270::read_fifo(), AP_InertialSensor_Invensensev3::read_fifo(), AP_InertialSensor_BMI055::read_fifo_gyro(), AP_InertialSensor_BMI088::read_fifo_gyro(), and AP_InertialSensor_SCHA63T::read_gyro().
_notify_new_accel_raw_sample()
void AP_InertialSensor_Backend::_notify_new_accel_raw_sample (uint8_t instance, const Vector3f & accel, uint64_t sample_us = 0, bool fsync_set = false) protected
Definition at line 511 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Invensensev2::_accumulate(), AP_InertialSensor_Invensense::_accumulate(), AP_InertialSensor_L3G4200D::_accumulate_accel(), AP_InertialSensor_Invensensev2::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Invensense::_accumulate_sensor_rate_sampling(), AP_InertialSensor_LSM9DS0::_read_data_transaction_a(), AP_InertialSensor_LSM9DS1::_read_data_transaction_x(), AP_InertialSensor_BMI160::_read_fifo(), AP_InertialSensor_RST::accel_measure(), AP_InertialSensor_Invensensev3::accumulate_samples(), AP_InertialSensor_NONE::generate_accel(), AP_InertialSensor_BMI270::parse_accel_frame(), AP_InertialSensor_SCHA63T::read_accel(), AP_InertialSensor_BMI055::read_fifo_accel(), AP_InertialSensor_BMI088::read_fifo_accel(), AP_InertialSensor_ADIS1647x::read_sensor16(), and AP_InertialSensor_ADIS1647x::read_sensor32().
_notify_new_accel_sensor_rate_sample()
void AP_InertialSensor_Backend::_notify_new_accel_sensor_rate_sample (uint8_t instance, const Vector3f & accel) protected
Definition at line 672 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Invensensev2::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Invensense::_accumulate_sensor_rate_sampling(), and AP_InertialSensor_NONE::generate_accel().
_notify_new_delta_angle()
void AP_InertialSensor_Backend::_notify_new_delta_angle (uint8_t instance, const Vector3f & dangle) protected
Definition at line 357 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_ADIS1647x::read_sensor32_delta().
_notify_new_delta_velocity()
void AP_InertialSensor_Backend::_notify_new_delta_velocity (uint8_t instance, const Vector3f & dvelocity) protected
Definition at line 601 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_ADIS1647x::read_sensor32_delta().
_notify_new_gyro_raw_sample()
void AP_InertialSensor_Backend::_notify_new_gyro_raw_sample (uint8_t instance, const Vector3f & accel, uint64_t sample_us = 0) protected
Definition at line 258 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Invensensev2::_accumulate(), AP_InertialSensor_Invensense::_accumulate(), AP_InertialSensor_L3G4200D::_accumulate_gyro(), AP_InertialSensor_Invensensev2::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Invensense::_accumulate_sensor_rate_sampling(), AP_InertialSensor_LSM9DS0::_read_data_transaction_g(), AP_InertialSensor_LSM9DS1::_read_data_transaction_g(), AP_InertialSensor_BMI160::_read_fifo(), AP_InertialSensor_Invensensev3::accumulate_samples(), AP_InertialSensor_NONE::generate_gyro(), AP_InertialSensor_RST::gyro_measure(), AP_InertialSensor_BMI270::parse_gyro_frame(), AP_InertialSensor_BMI055::read_fifo_gyro(), AP_InertialSensor_BMI088::read_fifo_gyro(), AP_InertialSensor_SCHA63T::read_gyro(), AP_InertialSensor_ADIS1647x::read_sensor16(), and AP_InertialSensor_ADIS1647x::read_sensor32().
_notify_new_gyro_sensor_rate_sample()
void AP_InertialSensor_Backend::_notify_new_gyro_sensor_rate_sample (uint8_t instance, const Vector3f & gyro) protected
Definition at line 687 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Invensensev2::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Invensense::_accumulate_sensor_rate_sampling(), and AP_InertialSensor_NONE::generate_gyro().
_publish_accel()
void AP_InertialSensor_Backend::_publish_accel (uint8_t instance, const Vector3f & accel) protected
Definition at line 484 of file AP_InertialSensor_Backend.cpp.
Referenced by update_accel().
_publish_gyro()
void AP_InertialSensor_Backend::_publish_gyro (uint8_t instance, const Vector3f & gyro) protected
Definition at line 165 of file AP_InertialSensor_Backend.cpp.
Referenced by update_gyro().
_publish_temperature()
void AP_InertialSensor_Backend::_publish_temperature (uint8_t instance, float temperature) protected
Definition at line 743 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_NONE::generate_accel(), AP_InertialSensor_BMI270::read_fifo(), AP_InertialSensor_BMI055::read_fifo_accel(), AP_InertialSensor_BMI088::read_fifo_accel(), AP_InertialSensor_ADIS1647x::read_sensor16(), AP_InertialSensor_ADIS1647x::read_sensor32(), AP_InertialSensor_ADIS1647x::read_sensor32_delta(), AP_InertialSensor_SCHA63T::set_temperature(), AP_InertialSensor_Invensensev2::update(), AP_InertialSensor_Invensensev3::update(), AP_InertialSensor_LSM9DS0::update(), and AP_InertialSensor_Invensense::update().
_rotate_and_correct_accel()
void AP_InertialSensor_Backend::_rotate_and_correct_accel (uint8_t instance, Vector3f & accel) protected
Definition at line 94 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Invensensev2::_accumulate(), AP_InertialSensor_Invensense::_accumulate(), AP_InertialSensor_L3G4200D::_accumulate_accel(), AP_InertialSensor_Invensensev2::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Invensense::_accumulate_sensor_rate_sampling(), _notify_new_delta_velocity(), AP_InertialSensor_LSM9DS0::_read_data_transaction_a(), AP_InertialSensor_LSM9DS1::_read_data_transaction_x(), AP_InertialSensor_BMI160::_read_fifo(), AP_InertialSensor_RST::accel_measure(), AP_InertialSensor_Invensensev3::accumulate_samples(), AP_InertialSensor_NONE::generate_accel(), AP_InertialSensor_BMI270::parse_accel_frame(), AP_InertialSensor_SCHA63T::read_accel(), AP_InertialSensor_BMI055::read_fifo_accel(), AP_InertialSensor_BMI088::read_fifo_accel(), AP_InertialSensor_ADIS1647x::read_sensor16(), and AP_InertialSensor_ADIS1647x::read_sensor32().
_rotate_and_correct_gyro()
void AP_InertialSensor_Backend::_rotate_and_correct_gyro (uint8_t instance, Vector3f & gyro) protected
Definition at line 137 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Invensensev2::_accumulate(), AP_InertialSensor_Invensense::_accumulate(), AP_InertialSensor_L3G4200D::_accumulate_gyro(), AP_InertialSensor_Invensensev2::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Invensense::_accumulate_sensor_rate_sampling(), _notify_new_delta_angle(), AP_InertialSensor_LSM9DS0::_read_data_transaction_g(), AP_InertialSensor_LSM9DS1::_read_data_transaction_g(), AP_InertialSensor_BMI160::_read_fifo(), AP_InertialSensor_Invensensev3::accumulate_samples(), AP_InertialSensor_NONE::generate_gyro(), AP_InertialSensor_RST::gyro_measure(), AP_InertialSensor_BMI270::parse_gyro_frame(), AP_InertialSensor_BMI055::read_fifo_gyro(), AP_InertialSensor_BMI088::read_fifo_gyro(), AP_InertialSensor_SCHA63T::read_gyro(), AP_InertialSensor_ADIS1647x::read_sensor16(), and AP_InertialSensor_ADIS1647x::read_sensor32().
_set_accel_max_abs_offset()
void AP_InertialSensor_Backend::_set_accel_max_abs_offset (uint8_t instance, float offset) protected
Definition at line 722 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_LSM9DS0::start(), and AP_InertialSensor_LSM9DS1::start().
_set_accel_oversampling()
void AP_InertialSensor_Backend::_set_accel_oversampling (uint8_t instance, uint8_t n) protected
Definition at line 46 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Invensensev2::_set_filter_and_scaling(), and AP_InertialSensor_Invensense::_set_filter_register().
_set_accel_raw_sample_rate()
void AP_InertialSensor_Backend::_set_accel_raw_sample_rate (uint8_t instance, uint16_t rate_hz) inline protected
Definition at line 227 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), and AP_InertialSensor_Invensensev3::start().
_set_accel_sensor_rate_sampling_enabled()
void AP_InertialSensor_Backend::_set_accel_sensor_rate_sampling_enabled (uint8_t instance, bool value) inline protected
Definition at line 186 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_Invensensev2::_set_filter_and_scaling(), and AP_InertialSensor_Invensense::_set_filter_register().
_set_gyro_oversampling()
void AP_InertialSensor_Backend::_set_gyro_oversampling (uint8_t instance, uint8_t n) protected
Definition at line 52 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Invensensev2::_set_filter_and_scaling(), and AP_InertialSensor_Invensense::_set_filter_register().
_set_gyro_raw_sample_rate()
void AP_InertialSensor_Backend::_set_gyro_raw_sample_rate (uint8_t instance, uint16_t rate_hz) inline protected
Definition at line 238 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), and AP_InertialSensor_Invensensev3::start().
_set_gyro_sensor_rate_sampling_enabled()
void AP_InertialSensor_Backend::_set_gyro_sensor_rate_sampling_enabled (uint8_t instance, bool value) inline protected
Definition at line 195 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_Invensensev2::_set_filter_and_scaling(), and AP_InertialSensor_Invensense::_set_filter_register().
_set_raw_sample_accel_multiplier()
void AP_InertialSensor_Backend::_set_raw_sample_accel_multiplier (uint8_t instance, uint16_t mul) inline protected
Definition at line 204 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), and AP_InertialSensor_Invensensev3::start().
_set_raw_sample_gyro_multiplier()
void AP_InertialSensor_Backend::_set_raw_sample_gyro_multiplier (uint8_t instance, uint16_t mul) inline protected
Definition at line 207 of file AP_InertialSensor_Backend.h.
_update_sensor_rate()
void AP_InertialSensor_Backend::_update_sensor_rate (uint16_t & count, uint32_t & start_us, float & rate_hz) const protected
Definition at line 64 of file AP_InertialSensor_Backend.cpp.
Referenced by _notify_new_accel_raw_sample(), _notify_new_delta_angle(), _notify_new_delta_velocity(), and _notify_new_gyro_raw_sample().
accumulate()
virtual void AP_InertialSensor_Backend::accumulate () inline virtual
Reimplemented in AP_InertialSensor_Invensense, AP_InertialSensor_Invensensev2, AP_InertialSensor_Invensensev3, and AP_InertialSensor_NONE.
Definition at line 59 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor::wait_for_sample().
apply_gyro_filters()
void AP_InertialSensor_Backend::apply_gyro_filters (const uint8_t instance, const Vector3f & gyro) protected
Definition at line 209 of file AP_InertialSensor_Backend.cpp.
Referenced by _notify_new_delta_angle(), and _notify_new_gyro_raw_sample().
enable_fast_sampling()
bool AP_InertialSensor_Backend::enable_fast_sampling (uint8_t instance) const inline protected
Definition at line 291 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_Invensensev2::_set_filter_and_scaling(), AP_InertialSensor_Invensense::_set_filter_register(), AP_InertialSensor_NONE::generate_accel(), AP_InertialSensor_NONE::generate_gyro(), AP_InertialSensor_Invensensev3::set_filter_and_scaling(), AP_InertialSensor_Invensensev3::set_filter_and_scaling_icm456xy(), and AP_InertialSensor_SCHA63T::start().
enable_highres_sampling()
bool AP_InertialSensor_Backend::enable_highres_sampling (uint8_t instance) const inline protected
Definition at line 296 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_Invensensev3::start().
get_auxiliary_bus()
virtual AuxiliaryBus * AP_InertialSensor_Backend::get_auxiliary_bus () inline virtual
Reimplemented in AP_InertialSensor_Invensense, and AP_InertialSensor_Invensensev2.
Definition at line 70 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor::get_auxiliary_bus().
get_clip_limit()
float AP_InertialSensor_Backend::get_clip_limit () const inline
Definition at line 79 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor::calc_vibration_and_clipping().
get_fast_sampling_rate()
uint8_t AP_InertialSensor_Backend::get_fast_sampling_rate () const inline protected
Definition at line 301 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_Invensensev2::_set_filter_and_scaling(), AP_InertialSensor_Invensense::_set_filter_register(), AP_InertialSensor_Invensensev3::calculate_fast_sampling_backend_rate(), AP_InertialSensor_Invensensev3::set_filter_and_scaling(), AP_InertialSensor_Invensensev3::set_filter_and_scaling_icm456xy(), and AP_InertialSensor_SCHA63T::start().
get_id()
int16_t AP_InertialSensor_Backend::get_id () const inline
Definition at line 76 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor::_find_backend().
get_loop_rate_hz()
uint16_t AP_InertialSensor_Backend::get_loop_rate_hz (void) const inline protected
Definition at line 261 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_Invensensev2::_set_filter_and_scaling(), AP_InertialSensor_Invensense::_set_filter_register(), and AP_InertialSensor_Invensensev3::calculate_fast_sampling_backend_rate().
get_output_banner()
virtual bool AP_InertialSensor_Backend::get_output_banner (char * banner, uint8_t banner_len) inline virtual
Reimplemented in AP_InertialSensor_Invensense, AP_InertialSensor_Invensensev2, and AP_InertialSensor_Invensensev3.
Definition at line 82 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor::get_output_banner().
increment_clip_count()
void AP_InertialSensor_Backend::increment_clip_count (uint8_t instance) inline protected
Definition at line 286 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_Invensensev2::_accumulate_sensor_rate_sampling(), and AP_InertialSensor_Invensense::_accumulate_sensor_rate_sampling().
log_accel_raw()
void AP_InertialSensor_Backend::log_accel_raw (uint8_t instance, const uint64_t sample_us, const Vector3f & accel) private
Definition at line 702 of file AP_InertialSensor_Backend.cpp.
Referenced by _notify_new_accel_raw_sample(), and _notify_new_delta_velocity().
log_gyro_raw()
void AP_InertialSensor_Backend::log_gyro_raw (uint8_t instance, const uint64_t sample_us, const Vector3f & raw_gyro, const Vector3f & filtered_gyro) private
Definition at line 437 of file AP_InertialSensor_Backend.cpp.
Referenced by _notify_new_delta_angle(), and _notify_new_gyro_raw_sample().
log_register_change()
void AP_InertialSensor_Backend::log_register_change (uint32_t bus_id, const AP_HAL::Device::checkreg & reg) protected
Definition at line 839 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_LSM9DS0::_poll_data(), AP_InertialSensor_LSM9DS1::_poll_data(), AP_InertialSensor_Invensensev2::_read_fifo(), AP_InertialSensor_Invensense::_read_fifo(), AP_InertialSensor_SCHA63T::read_accel(), AP_InertialSensor_Invensensev3::read_fifo(), AP_InertialSensor_BMI055::read_fifo_accel(), AP_InertialSensor_BMI055::read_fifo_gyro(), AP_InertialSensor_BMI088::read_fifo_gyro(), and AP_InertialSensor_SCHA63T::read_gyro().
notify_accel_fifo_reset()
void AP_InertialSensor_Backend::notify_accel_fifo_reset (uint8_t instance) protected
Definition at line 30 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Invensense::_fast_fifo_reset(), AP_InertialSensor_Invensensev2::_fifo_reset(), AP_InertialSensor_LSM9DS1::_fifo_reset(), AP_InertialSensor_Invensense::_fifo_reset(), AP_InertialSensor_BMI270::fifo_reset(), and AP_InertialSensor_Invensensev3::fifo_reset().
notify_gyro_fifo_reset()
void AP_InertialSensor_Backend::notify_gyro_fifo_reset (uint8_t instance) protected
Definition at line 39 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Invensense::_fast_fifo_reset(), AP_InertialSensor_Invensensev2::_fifo_reset(), AP_InertialSensor_LSM9DS1::_fifo_reset(), AP_InertialSensor_Invensense::_fifo_reset(), AP_InertialSensor_BMI270::fifo_reset(), and AP_InertialSensor_Invensensev3::fifo_reset().
save_gyro_window()
void AP_InertialSensor_Backend::save_gyro_window (const uint8_t instance, const Vector3f & gyro, uint8_t phase) protected
Definition at line 183 of file AP_InertialSensor_Backend.cpp.
Referenced by apply_gyro_filters().
sensors_converging()
bool AP_InertialSensor_Backend::sensors_converging () const inline protected
Definition at line 215 of file AP_InertialSensor_Backend.h.
Referenced by _update_sensor_rate(), and update_gyro().
set_accel_orientation()
void AP_InertialSensor_Backend::set_accel_orientation (uint8_t instance, enum Rotation rotation) inline protected
Definition at line 280 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_ADIS1647x::start(), AP_InertialSensor_BMI055::start(), AP_InertialSensor_BMI088::start(), AP_InertialSensor_BMI270::start(), AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), AP_InertialSensor_Invensensev3::start(), AP_InertialSensor_SCHA63T::start(), AP_InertialSensor_LSM9DS0::start(), AP_InertialSensor_LSM9DS1::start(), and AP_InertialSensor_RST::start().
set_gyro_orientation()
void AP_InertialSensor_Backend::set_gyro_orientation (uint8_t instance, enum Rotation rotation) inline protected
Definition at line 276 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_ADIS1647x::start(), AP_InertialSensor_BMI055::start(), AP_InertialSensor_BMI088::start(), AP_InertialSensor_BMI270::start(), AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), AP_InertialSensor_Invensensev3::start(), AP_InertialSensor_SCHA63T::start(), AP_InertialSensor_LSM9DS0::start(), AP_InertialSensor_LSM9DS1::start(), and AP_InertialSensor_RST::start().
should_log_imu_raw()
bool AP_InertialSensor_Backend::should_log_imu_raw () const private
Referenced by log_accel_raw(), and log_gyro_raw().
start()
virtual void AP_InertialSensor_Backend::start (void) inline virtual
Reimplemented in AP_InertialSensor_ADIS1647x, AP_InertialSensor_BMI055, AP_InertialSensor_BMI088, AP_InertialSensor_BMI160, AP_InertialSensor_BMI270, AP_InertialSensor_Invensense, AP_InertialSensor_Invensensev2, AP_InertialSensor_Invensensev3, AP_InertialSensor_NONE, AP_InertialSensor_SCHA63T, AP_InertialSensor_L3G4200D, AP_InertialSensor_LSM9DS0, AP_InertialSensor_LSM9DS1, and AP_InertialSensor_RST.
Definition at line 65 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor::_start_backends().
update()
virtual bool AP_InertialSensor_Backend::update () pure virtual
Implemented in AP_InertialSensor_ADIS1647x, AP_InertialSensor_BMI055, AP_InertialSensor_BMI088, AP_InertialSensor_BMI160, AP_InertialSensor_BMI270, AP_InertialSensor_Invensensev2, AP_InertialSensor_Invensensev3, AP_InertialSensor_L3G4200D, AP_InertialSensor_LSM9DS0, AP_InertialSensor_LSM9DS1, AP_InertialSensor_NONE, AP_InertialSensor_RST, AP_InertialSensor_SCHA63T, and AP_InertialSensor_Invensense.
Referenced by AP_InertialSensor::update().
update_accel()
void AP_InertialSensor_Backend::update_accel (uint8_t instance) protected
Definition at line 801 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_ADIS1647x::update(), AP_InertialSensor_BMI055::update(), AP_InertialSensor_BMI088::update(), AP_InertialSensor_BMI160::update(), AP_InertialSensor_BMI270::update(), AP_InertialSensor_Invensensev2::update(), AP_InertialSensor_Invensensev3::update(), AP_InertialSensor_L3G4200D::update(), AP_InertialSensor_LSM9DS0::update(), AP_InertialSensor_LSM9DS1::update(), AP_InertialSensor_NONE::update(), AP_InertialSensor_RST::update(), AP_InertialSensor_SCHA63T::update(), and AP_InertialSensor_Invensense::update().
update_gyro()
void AP_InertialSensor_Backend::update_gyro (uint8_t instance) protected
Definition at line 764 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_ADIS1647x::update(), AP_InertialSensor_BMI055::update(), AP_InertialSensor_BMI088::update(), AP_InertialSensor_BMI160::update(), AP_InertialSensor_BMI270::update(), AP_InertialSensor_Invensensev2::update(), AP_InertialSensor_Invensensev3::update(), AP_InertialSensor_L3G4200D::update(), AP_InertialSensor_LSM9DS0::update(), AP_InertialSensor_LSM9DS1::update(), AP_InertialSensor_NONE::update(), AP_InertialSensor_RST::update(), AP_InertialSensor_SCHA63T::update(), and AP_InertialSensor_Invensense::update().
Write_ACC()
void AP_InertialSensor_Backend::Write_ACC (const uint8_t instance, const uint64_t sample_us, const Vector3f & accel) const private
Referenced by log_accel_raw().
Write_GYR()
void AP_InertialSensor_Backend::Write_GYR (const uint8_t instance, const uint64_t sample_us, const Vector3f & gyro, bool use_sample_timestamp = false) const protected
Referenced by AP_InertialSensor_Invensensev3::accumulate_samples(), and log_gyro_raw().
Member Data Documentation
_clip_limit
float AP_InertialSensor_Backend::_clip_limit = 15.5f * GRAVITY_MSS protected
Definition at line 142 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_Invensensev2::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Invensense::_accumulate_sensor_rate_sampling(), AP_InertialSensor_Invensensev2::_hardware_init(), AP_InertialSensor_ADIS1647x::check_product_id(), get_clip_limit(), AP_InertialSensor_Invensensev3::hardware_init(), and AP_InertialSensor_Invensense::start().
_id
int16_t AP_InertialSensor_Backend::_id = -1 protected
Definition at line 252 of file AP_InertialSensor_Backend.h.
Referenced by get_id(), AP_InertialSensor_Invensense::probe(), AP_InertialSensor_Invensensev2::probe(), AP_InertialSensor_Invensense::probe(), and AP_InertialSensor_Invensensev2::probe().
_imu
AP_InertialSensor& AP_InertialSensor_Backend::_imu protected
Definition at line 136 of file AP_InertialSensor_Backend.h.
Referenced by _accel_filter_cutoff(), _accel_raw_sample_rate(), _gyro_filter_cutoff(), _gyro_raw_sample_rate(), _inc_accel_error_count(), _inc_gyro_error_count(), _notify_new_accel_raw_sample(), _notify_new_accel_sensor_rate_sample(), _notify_new_delta_angle(), _notify_new_delta_velocity(), _notify_new_gyro_raw_sample(), _notify_new_gyro_sensor_rate_sample(), _publish_accel(), _publish_gyro(), _publish_temperature(), _rotate_and_correct_accel(), _rotate_and_correct_gyro(), _set_accel_max_abs_offset(), _set_accel_oversampling(), _set_accel_raw_sample_rate(), _set_accel_sensor_rate_sampling_enabled(), _set_gyro_oversampling(), _set_gyro_raw_sample_rate(), _set_gyro_sensor_rate_sampling_enabled(), _set_raw_sample_accel_multiplier(), _set_raw_sample_gyro_multiplier(), apply_gyro_filters(), AP_InertialSensor_NONE::detect(), enable_fast_sampling(), get_fast_sampling_rate(), get_loop_rate_hz(), increment_clip_count(), log_accel_raw(), log_gyro_raw(), notify_accel_fifo_reset(), notify_gyro_fifo_reset(), AP_InertialSensor_LSM9DS0::probe(), AP_InertialSensor_LSM9DS1::probe(), save_gyro_window(), set_accel_orientation(), set_gyro_orientation(), AP_InertialSensor_ADIS1647x::start(), AP_InertialSensor_BMI055::start(), AP_InertialSensor_BMI088::start(), AP_InertialSensor_BMI160::start(), AP_InertialSensor_BMI270::start(), AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), AP_InertialSensor_Invensensev3::start(), AP_InertialSensor_NONE::start(), AP_InertialSensor_SCHA63T::start(), AP_InertialSensor_L3G4200D::start(), AP_InertialSensor_LSM9DS0::start(), AP_InertialSensor_LSM9DS1::start(), AP_InertialSensor_RST::start(), update_accel(), and update_gyro().
_last_accel_filter_hz
uint16_t AP_InertialSensor_Backend::_last_accel_filter_hz protected
Definition at line 273 of file AP_InertialSensor_Backend.h.
Referenced by update_accel().
_last_gyro_filter_hz
uint16_t AP_InertialSensor_Backend::_last_gyro_filter_hz protected
Definition at line 274 of file AP_InertialSensor_Backend.h.
Referenced by update_gyro().
_sem
HAL_Semaphore AP_InertialSensor_Backend::_sem protected
Definition at line 139 of file AP_InertialSensor_Backend.h.
Referenced by _notify_new_accel_raw_sample(), _notify_new_delta_angle(), _notify_new_delta_velocity(), _notify_new_gyro_raw_sample(), update_accel(), and update_gyro().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp