APM:Libraries: AP_RTC Class Reference
AP_RTC Class Reference
#include <AP_RTC.h>
Public Types
enum source_type : uint8_t { SOURCE_GPS = 0 , SOURCE_MAVLINK_SYSTEM_TIME = 1 , SOURCE_HW = 2 , SOURCE_NONE }
Public Member Functions
AP_RTC ()
bool get_utc_usec (uint64_t &usec) const
void set_utc_usec (uint64_t time_utc_usec, source_type type)
bool get_system_clock_utc (uint8_t &hour, uint8_t &min, uint8_t &sec, uint16_t &ms) const
bool get_local_time (uint8_t &hour, uint8_t &min, uint8_t &sec, uint16_t &ms) const
uint32_t get_time_utc (int32_t hour, int32_t min, int32_t sec, int32_t ms)
bool get_date_and_time_utc (uint16_t &year, uint8_t &month, uint8_t &day, uint8_t &hour, uint8_t &min, uint8_t &sec, uint16_t &ms) const
HAL_Semaphore & get_semaphore (void)
bool clock_s_to_date_fields (const uint32_t utc_sec32, uint16_t &year, uint8_t &month, uint8_t &day, uint8_t &hour, uint8_t &min, uint8_t &sec, uint8_t &wday) const
uint32_t date_fields_to_clock_s (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t min, uint8_t sec) const
Static Public Member Functions
static AP_RTC * get_singleton ()
Public Attributes
AP_Int8 allowed_types
AP_Int16 tz_min
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void clock_ms_to_hms_fields (const uint64_t time_ms, uint8_t &hour, uint8_t &min, uint8_t &sec, uint16_t &ms) const
Static Private Member Functions
static bool _is_leap (uint32_t y)
static uint32_t _timegm (struct tm &tm)
Private Attributes
HAL_Semaphore rsem
source_type rtc_source_type = SOURCE_NONE
int64_t rtc_shift
Static Private Attributes
static AP_RTC * _singleton
Detailed Description
Definition at line 11 of file AP_RTC.h.
Member Enumeration Documentation
source_type
enum AP_RTC::source_type : uint8_t
Enumerator
SOURCE_GPS
SOURCE_MAVLINK_SYSTEM_TIME
SOURCE_HW
SOURCE_NONE
Definition at line 25 of file AP_RTC.h.
Constructor & Destructor Documentation
AP_RTC()
AP_RTC::AP_RTC ()
Definition at line 14 of file AP_RTC.cpp.
Member Function Documentation
_is_leap()
bool AP_RTC::_is_leap (uint32_t y) static private
Definition at line 132 of file AP_RTC.cpp.
Referenced by _timegm().
_timegm()
uint32_t AP_RTC::_timegm (struct tm & tm) static private
Definition at line 141 of file AP_RTC.cpp.
Referenced by date_fields_to_clock_s().
clock_ms_to_hms_fields()
void AP_RTC::clock_ms_to_hms_fields (const uint64_t time_ms, uint8_t & hour, uint8_t & min, uint8_t & sec, uint16_t & ms) const private
Definition at line 97 of file AP_RTC.cpp.
Referenced by get_local_time(), and get_system_clock_utc().
clock_s_to_date_fields()
bool AP_RTC::clock_s_to_date_fields (const uint32_t utc_sec32, uint16_t & year, uint8_t & month, uint8_t & day, uint8_t & hour, uint8_t & min, uint8_t & sec, uint8_t & wday) const
Definition at line 111 of file AP_RTC.cpp.
date_fields_to_clock_s()
uint32_t AP_RTC::date_fields_to_clock_s (uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t min, uint8_t sec) const
Definition at line 174 of file AP_RTC.cpp.
get_date_and_time_utc()
bool AP_RTC::get_date_and_time_utc (uint16_t & year, uint8_t & month, uint8_t & day, uint8_t & hour, uint8_t & min, uint8_t & sec, uint16_t & ms) const
Definition at line 280 of file AP_RTC.cpp.
get_local_time()
bool AP_RTC::get_local_time (uint8_t & hour, uint8_t & min, uint8_t & sec, uint16_t & ms) const
Definition at line 198 of file AP_RTC.cpp.
get_semaphore()
HAL_Semaphore & AP_RTC::get_semaphore (void) inline
Definition at line 61 of file AP_RTC.h.
Referenced by AP_Hott_Telem::send_GPS().
get_singleton()
static AP_RTC * AP_RTC::get_singleton () inline static
Definition at line 56 of file AP_RTC.h.
Referenced by AP::rtc().
get_system_clock_utc()
bool AP_RTC::get_system_clock_utc (uint8_t & hour, uint8_t & min, uint8_t & sec, uint16_t & ms) const
Definition at line 186 of file AP_RTC.cpp.
Referenced by AP_Spektrum_Telem::calc_gps_status(), get_time_utc(), loop(), and AP_Hott_Telem::send_GPS().
get_time_utc()
uint32_t AP_RTC::get_time_utc (int32_t hour, int32_t min, int32_t sec, int32_t ms)
Definition at line 217 of file AP_RTC.cpp.
Referenced by loop().
get_utc_usec()
bool AP_RTC::get_utc_usec (uint64_t & usec) const
Definition at line 88 of file AP_RTC.cpp.
Referenced by get_date_and_time_utc(), get_local_time(), get_system_clock_utc(), loop(), and GCS_MAVLINK::send_system_time().
set_utc_usec()
void AP_RTC::set_utc_usec (uint64_t time_utc_usec, source_type type)
Definition at line 46 of file AP_RTC.cpp.
Referenced by AP_BoardConfig::init(), loop(), setup(), and AP_GPS::update_instance().
Member Data Documentation
_singleton
AP_RTC * AP_RTC::_singleton static private
Definition at line 70 of file AP_RTC.h.
Referenced by AP_RTC(), and get_singleton().
allowed_types
AP_Int8 AP_RTC::allowed_types
Definition at line 19 of file AP_RTC.h.
Referenced by set_utc_usec().
rsem
HAL_Semaphore AP_RTC::rsem private
Definition at line 71 of file AP_RTC.h.
Referenced by get_semaphore(), and set_utc_usec().
rtc_shift
int64_t AP_RTC::rtc_shift private
Definition at line 74 of file AP_RTC.h.
Referenced by get_utc_usec(), and set_utc_usec().
rtc_source_type
source_type AP_RTC::rtc_source_type = SOURCE_NONE private
Definition at line 73 of file AP_RTC.h.
Referenced by get_utc_usec(), and set_utc_usec().
tz_min
AP_Int16 AP_RTC::tz_min
Definition at line 20 of file AP_RTC.h.
Referenced by get_local_time().
var_info
const AP_Param::GroupInfo AP_RTC::var_info static
Initial value:
= {
    AP_GROUPINFO("_TYPES",  1, AP_RTC, allowed_types, 1),
    AP_GROUPINFO("_TZ_MIN",  2, AP_RTC, tz_min, 0),
    AP_GROUPEND
}
Definition at line 27 of file AP_RTC.h.
The documentation for this class was generated from the following files:
libraries/AP_RTC/AP_RTC.h
libraries/AP_RTC/AP_RTC.cpp