APM:Libraries: ByteBuffer Class Reference
ByteBuffer Class Reference
#include <RingBuffer.h>
Classes
struct IoVec
Public Member Functions
ByteBuffer (uint32_t size)
ByteBuffer (uint8_t *_buf, uint32_t _size)
~ByteBuffer (void)
uint32_t available (void) const
void clear (void)
uint32_t space (void) const
bool is_empty (void) const WARN_IF_UNUSED
uint32_t write (const uint8_t *data, uint32_t len)
uint32_t read (uint8_t *data, uint32_t len)
bool read_byte (uint8_t *data) WARN_IF_UNUSED
bool update (const uint8_t *data, uint32_t len)
uint32_t get_size (void) const
bool set_size (uint32_t size)
bool set_size_best (uint32_t size)
bool advance (uint32_t n)
const uint8_t * readptr (uint32_t &available_bytes)
int16_t peek (uint32_t ofs) const
uint32_t peekbytes (uint8_t *data, uint32_t len)
uint8_t peekiovec (IoVec vec[2], uint32_t len)
uint8_t reserve (IoVec vec[2], uint32_t len)
bool commit (uint32_t len)
Private Attributes
uint8_t * buf
uint32_t size
std::atomic< uint32_t > head {0}
std::atomic< uint32_t > tail {0}
bool external_buf
Detailed Description
Definition at line 12 of file RingBuffer.h.
Constructor & Destructor Documentation
ByteBuffer() [1/2]
ByteBuffer::ByteBuffer (uint32_t size)
Definition at line 6 of file RingBuffer.cpp.
ByteBuffer() [2/2]
ByteBuffer::ByteBuffer (uint8_t * _buf, uint32_t _size) inline
Definition at line 15 of file RingBuffer.h.
~ByteBuffer()
ByteBuffer::~ByteBuffer (void)
Definition at line 13 of file RingBuffer.cpp.
Member Function Documentation
advance()
bool ByteBuffer::advance (uint32_t n)
Definition at line 137 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_write_pending_bytes(), ObjectBuffer< T >::advance(), ObjectBuffer_TS< T >::advance(), HALSITL::UARTDriver::handle_writing_from_writebuffer_to_device(), ObjectBuffer< T >::pop(), ObjectBuffer_TS< T >::pop(), ObjectBuffer< T >::push_force(), ObjectBuffer_TS< T >::push_force(), ObjectBuffer< T >::push_force(), ObjectBuffer_TS< T >::push_force(), read(), read_byte(), TEST(), ESP32::UARTDriver::write_data(), ESP32::WiFiDriver::write_data(), ESP32::WiFiUdpDriver::write_data(), ChibiOS::UARTDriver::write_pending_bytes_DMA(), and ChibiOS::UARTDriver::write_pending_bytes_NODMA().
available()
uint32_t ByteBuffer::available (void) const
Definition at line 58 of file RingBuffer.cpp.
Referenced by ChibiOS::UARTDriver::_available(), ESP32::UARTDriver::_available(), ESP32::WiFiDriver::_available(), ESP32::WiFiUdpDriver::_available(), Linux::UARTDriver::_available(), HALSITL::UARTDriver::_available(), HALSITL::UARTDriver::_flush(), ChibiOS::UARTDriver::_rx_timer_tick(), ChibiOS::UARTDriver::_tx_timer_tick(), Linux::UARTDriver::_write_pending_bytes(), advance(), ObjectBuffer_TS< T >::available(), ObjectBuffer< T >::available(), HALSITL::UARTDriver::handle_writing_from_writebuffer_to_device(), AP_Logger_Block::io_timer(), peek(), peekiovec(), ObjectBuffer< T >::pop(), ObjectBuffer_TS< T >::pop(), ChibiOS::UARTDriver::rxbuff_full_irq(), ChibiOS::UARTDriver::tx_pending(), ESP32::UARTDriver::tx_pending(), ESP32::WiFiDriver::tx_pending(), ESP32::WiFiUdpDriver::tx_pending(), Linux::UARTDriver::tx_pending(), update(), ChibiOS::UARTDriver::write_pending_bytes(), and ChibiOS::UARTDriver::write_pending_bytes_DMA().
clear()
void ByteBuffer::clear (void)
Definition at line 70 of file RingBuffer.cpp.
Referenced by ChibiOS::UARTDriver::_begin(), Linux::UARTDriver::_begin(), HALSITL::UARTDriver::_begin(), ChibiOS::UARTDriver::_discard_input(), Linux::UARTDriver::_discard_input(), HALSITL::UARTDriver::_discard_input(), ObjectBuffer< T >::clear(), ObjectBuffer_TS< T >::clear(), AP_Logger_Block::EraseAll(), AP_Logger_Block::io_timer(), and AP_Logger_Block::stop_logging().
commit()
bool ByteBuffer::commit (uint32_t len)
Definition at line 230 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_timer_tick(), ChibiOS::UARTDriver::read_bytes_NODMA(), and write().
get_size()
uint32_t ByteBuffer::get_size (void) const inline
Definition at line 50 of file RingBuffer.h.
Referenced by ChibiOS::UARTDriver::_begin(), AP_Logger_Block::_WritePrioritisedBlock(), ObjectBuffer_TS< T >::get_size(), ObjectBuffer< T >::get_size(), and AP_Logger_Block::Init().
is_empty()
bool ByteBuffer::is_empty (void) const
Definition at line 95 of file RingBuffer.cpp.
Referenced by ObjectBuffer< T >::is_empty(), and ObjectBuffer_TS< T >::is_empty().
peek()
int16_t ByteBuffer::peek (uint32_t ofs) const
Definition at line 274 of file RingBuffer.cpp.
Referenced by read_byte().
peekbytes()
uint32_t ByteBuffer::peekbytes (uint8_t * data, uint32_t len)
Definition at line 185 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_write_pending_bytes(), HALSITL::UARTDriver::handle_writing_from_writebuffer_to_device(), ObjectBuffer< T >::peek(), ObjectBuffer_TS< T >::peek(), ObjectBuffer< T >::peek(), ObjectBuffer_TS< T >::peek(), read(), ESP32::UARTDriver::write_data(), ESP32::WiFiDriver::write_data(), ESP32::WiFiUdpDriver::write_data(), and ChibiOS::UARTDriver::write_pending_bytes_DMA().
peekiovec()
uint8_t ByteBuffer::peekiovec (ByteBuffer::IoVec iovec[2], uint32_t len)
Definition at line 146 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_write_pending_bytes(), peekbytes(), TEST(), and ChibiOS::UARTDriver::write_pending_bytes_NODMA().
read()
uint32_t ByteBuffer::read (uint8_t * data, uint32_t len)
Definition at line 240 of file RingBuffer.cpp.
Referenced by ESP32::WiFiUdpDriver::_read(), ChibiOS::UARTDriver::_read(), ESP32::UARTDriver::_read(), HALSITL::UARTDriver::_read(), Linux::UARTDriver::_read(), ESP32::WiFiDriver::_read(), consumer_thread(), ObjectBuffer< T >::pop(), ObjectBuffer_TS< T >::pop(), and AP_Logger_Block::write_log_page().
read_byte()
bool ByteBuffer::read_byte (uint8_t * data)
Definition at line 247 of file RingBuffer.cpp.
readptr()
const uint8_t * ByteBuffer::readptr (uint32_t & available_bytes)
Definition at line 266 of file RingBuffer.cpp.
Referenced by HALSITL::UARTDriver::handle_writing_from_writebuffer_to_device(), peekiovec(), ObjectBuffer< T >::readptr(), and ObjectBuffer_TS< T >::readptr().
reserve()
uint8_t ByteBuffer::reserve (ByteBuffer::IoVec iovec[2], uint32_t len)
Definition at line 199 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_timer_tick(), ChibiOS::UARTDriver::read_bytes_NODMA(), and write().
set_size()
bool ByteBuffer::set_size (uint32_t size)
Definition at line 23 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_allocate_buffers(), ESP32::UARTDriver::_begin(), ESP32::WiFiDriver::_begin(), ESP32::WiFiUdpDriver::_begin(), Linux::SPIUARTDriver::_begin(), Linux::UARTDriver::_deallocate_buffers(), ChibiOS::UARTDriver::_end(), ESP32::UARTDriver::_end(), HALSITL::UARTDriver::_uart_start_connection(), AP_Logger_Block::Init(), ObjectBuffer< T >::set_size(), ObjectBuffer_TS< T >::set_size(), set_size_best(), and TEST().
set_size_best()
bool ByteBuffer::set_size_best (uint32_t size)
Definition at line 47 of file RingBuffer.cpp.
Referenced by ChibiOS::UARTDriver::_begin().
space()
uint32_t ByteBuffer::space (void) const
Definition at line 75 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_timer_tick(), AP_Logger_Block::_WritePrioritisedBlock(), commit(), HALSITL::UARTDriver::handle_reading_from_device_to_readbuffer(), ObjectBuffer< T >::push(), ObjectBuffer_TS< T >::push(), ObjectBuffer< T >::push(), ObjectBuffer_TS< T >::push(), ObjectBuffer< T >::push_force(), ObjectBuffer_TS< T >::push_force(), ObjectBuffer< T >::push_force(), ObjectBuffer_TS< T >::push_force(), ChibiOS::UARTDriver::read_bytes_NODMA(), reserve(), ObjectBuffer_TS< T >::space(), ObjectBuffer< T >::space(), ChibiOS::UARTDriver::txspace(), ESP32::UARTDriver::txspace(), ESP32::WiFiDriver::txspace(), ESP32::WiFiUdpDriver::txspace(), Linux::UARTDriver::txspace(), HALSITL::UARTDriver::txspace(), and ChibiOS::UARTDriver::update_rts_line().
update()
bool ByteBuffer::update (const uint8_t * data, uint32_t len)
Definition at line 119 of file RingBuffer.cpp.
Referenced by ObjectBuffer< T >::update(), and ObjectBuffer_TS< T >::update().
write()
uint32_t ByteBuffer::write (const uint8_t * data, uint32_t len)
Definition at line 100 of file RingBuffer.cpp.
Referenced by ChibiOS::UARTDriver::_rx_timer_tick(), ChibiOS::UARTDriver::_write(), ESP32::UARTDriver::_write(), ESP32::WiFiDriver::_write(), ESP32::WiFiUdpDriver::_write(), Linux::UARTDriver::_write(), HALSITL::UARTDriver::_write(), Linux::SPIUARTDriver::_write_fd(), AP_Logger_Block::_WritePrioritisedBlock(), HALSITL::UARTDriver::handle_reading_from_device_to_readbuffer(), producer_thread(), ObjectBuffer< T >::push(), ObjectBuffer_TS< T >::push(), ObjectBuffer< T >::push(), ObjectBuffer_TS< T >::push(), ESP32::WiFiUdpDriver::read_all(), ESP32::UARTDriver::read_data(), ESP32::WiFiDriver::read_data(), ChibiOS::UARTDriver::rxbuff_full_irq(), AP_Logger_Block::start_new_log(), and TEST().
Member Data Documentation
buf
uint8_t* ByteBuffer::buf private
Definition at line 98 of file RingBuffer.h.
Referenced by ByteBuffer(), peek(), peekiovec(), readptr(), reserve(), set_size(), update(), and ~ByteBuffer().
external_buf
bool ByteBuffer::external_buf private
Definition at line 104 of file RingBuffer.h.
Referenced by ByteBuffer(), set_size(), and ~ByteBuffer().
head
std::atomic<uint32_t> ByteBuffer::head {0} private
Definition at line 101 of file RingBuffer.h.
Referenced by advance(), available(), clear(), is_empty(), peek(), readptr(), set_size(), space(), and update().
size
uint32_t ByteBuffer::size private
Definition at line 99 of file RingBuffer.h.
Referenced by advance(), available(), ByteBuffer(), commit(), get_size(), peek(), readptr(), reserve(), set_size(), space(), and update().
tail
std::atomic<uint32_t> ByteBuffer::tail {0} private
Definition at line 102 of file RingBuffer.h.
Referenced by available(), clear(), commit(), is_empty(), readptr(), reserve(), set_size(), and space().
The documentation for this class was generated from the following files:
libraries/AP_HAL/utility/RingBuffer.h
libraries/AP_HAL/utility/RingBuffer.cpp