APM:Libraries: AP_Camera_Backend Class Reference
AP_Camera_Backend Class Reference abstract
#include <AP_Camera_Backend.h>
Public Types
enum class Options : int8_t { RecordWhileArmed = (1 << 0U) }
Public Member Functions
AP_Camera_Backend (AP_Camera &frontend, AP_Camera_Params &params, uint8_t instance)
CLASS_NO_COPY (AP_Camera_Backend)
virtual void init ()
virtual void update ()
virtual bool healthy () const
virtual void cam_mode_toggle ()
bool take_picture ()
void take_multiple_pictures (uint32_t time_interval_ms, int16_t total_num)
void stop_capture ()
virtual bool trigger_pic ()=0
virtual bool record_video (bool start_recording)
virtual bool set_zoom (ZoomType zoom_type, float zoom_value)
virtual SetFocusResult set_focus (FocusType focus_type, float focus_value)
virtual bool set_tracking (TrackingType tracking_type, const Vector2f &p1, const Vector2f &p2)
virtual bool set_lens (uint8_t lens)
float horizontal_fov () const
float vertical_fov () const
virtual void handle_message (mavlink_channel_t chan, const mavlink_message_t &msg)
virtual void configure (float shooting_mode, float shutter_speed, float aperture, float ISO, int32_t exposure_type, int32_t cmd_id, float engine_cutoff_time)
virtual void control (float session, float zoom_pos, float zoom_step, float focus_lock, int32_t shooting_cmd, int32_t cmd_id)
void set_trigger_distance (float distance_m)
void send_camera_feedback (mavlink_channel_t chan)
virtual void send_camera_information (mavlink_channel_t chan) const
virtual void send_camera_settings (mavlink_channel_t chan) const
virtual void send_camera_capture_status (mavlink_channel_t chan) const
Protected Member Functions
void setup_feedback_callback ()
void feedback_pin_isr (uint8_t pin, bool high, uint32_t timestamp_us)
void feedback_pin_timer ()
void check_feedback ()
void prep_mavlink_msg_camera_feedback (uint64_t timestamp_us)
void log_picture ()
void Write_Camera (uint64_t timestamp_us=0)
void Write_Trigger ()
void Write_CameraInfo (enum LogMessages msg, uint64_t timestamp_us=0)
uint8_t get_mount_instance () const
uint8_t get_gimbal_device_id () const
Protected Attributes
AP_Camera & _frontend
AP_Camera_Params & _params
struct {
uint64_t timestamp_us
Location location
int32_t roll_sensor
int32_t pitch_sensor
int32_t yaw_sensor
uint32_t feedback_trigger_logged_count
} camera_feedback
struct {
uint32_t time_interval_ms
int16_t num_remaining
} time_interval_settings
uint8_t _instance
bool timer_installed
bool isr_installed
uint8_t last_pin_state
uint32_t feedback_trigger_count
uint32_t feedback_trigger_timestamp_us
bool trigger_pending
uint32_t last_picture_time_ms
Location last_location
uint16_t image_index
bool last_is_armed
Detailed Description
Definition at line 29 of file AP_Camera_Backend.h.
Member Enumeration Documentation
Options
enum class AP_Camera_Backend::Options : int8_t strong
Enumerator
RecordWhileArmed
Definition at line 40 of file AP_Camera_Backend.h.
Constructor & Destructor Documentation
AP_Camera_Backend()
AP_Camera_Backend::AP_Camera_Backend (AP_Camera & frontend, AP_Camera_Params & params, uint8_t instance)
Definition at line 11 of file AP_Camera_Backend.cpp.
Member Function Documentation
cam_mode_toggle()
virtual void AP_Camera_Backend::cam_mode_toggle () inline virtual
Definition at line 54 of file AP_Camera_Backend.h.
Referenced by AP_Camera::cam_mode_toggle().
check_feedback()
void AP_Camera_Backend::check_feedback () protected
Definition at line 362 of file AP_Camera_Backend.cpp.
CLASS_NO_COPY()
AP_Camera_Backend::CLASS_NO_COPY (AP_Camera_Backend)
configure()
virtual void AP_Camera_Backend::configure (float shooting_mode, float shutter_speed, float aperture, float ISO, int32_t exposure_type, int32_t cmd_id, float engine_cutoff_time) inline virtual
Reimplemented in AP_Camera_Servo.
Definition at line 96 of file AP_Camera_Backend.h.
Referenced by AP_Camera::configure().
control()
void AP_Camera_Backend::control (float session, float zoom_pos, float zoom_step, float focus_lock, int32_t shooting_cmd, int32_t cmd_id) virtual
Definition at line 168 of file AP_Camera_Backend.cpp.
Referenced by AP_Camera::control().
feedback_pin_isr()
void AP_Camera_Backend::feedback_pin_isr (uint8_t pin, bool high, uint32_t timestamp_us) protected
Definition at line 341 of file AP_Camera_Backend.cpp.
Referenced by setup_feedback_callback().
feedback_pin_timer()
void AP_Camera_Backend::feedback_pin_timer () protected
Definition at line 349 of file AP_Camera_Backend.cpp.
Referenced by setup_feedback_callback().
get_gimbal_device_id()
uint8_t AP_Camera_Backend::get_gimbal_device_id () const protected
Definition at line 110 of file AP_Camera_Backend.cpp.
Referenced by send_camera_information().
get_mount_instance()
uint8_t AP_Camera_Backend::get_mount_instance () const protected
Definition at line 100 of file AP_Camera_Backend.cpp.
Referenced by get_gimbal_device_id().
handle_message()
virtual void AP_Camera_Backend::handle_message (mavlink_channel_t chan, const mavlink_message_t & msg) inline virtual
Definition at line 93 of file AP_Camera_Backend.h.
Referenced by AP_Camera::handle_message().
healthy()
virtual bool AP_Camera_Backend::healthy () const inline virtual
Definition at line 51 of file AP_Camera_Backend.h.
horizontal_fov()
float AP_Camera_Backend::horizontal_fov () const inline
Definition at line 89 of file AP_Camera_Backend.h.
init()
virtual void AP_Camera_Backend::init () inline virtual
Definition at line 45 of file AP_Camera_Backend.h.
Referenced by AP_Camera::init().
log_picture()
void AP_Camera_Backend::log_picture () protected
Referenced by take_picture().
prep_mavlink_msg_camera_feedback()
void AP_Camera_Backend::prep_mavlink_msg_camera_feedback (uint64_t timestamp_us) protected
Definition at line 382 of file AP_Camera_Backend.cpp.
Referenced by check_feedback().
record_video()
virtual bool AP_Camera_Backend::record_video (bool start_recording) inline virtual
Definition at line 71 of file AP_Camera_Backend.h.
Referenced by AP_Camera::record_video(), and update().
send_camera_capture_status()
void AP_Camera_Backend::send_camera_capture_status (mavlink_channel_t chan) const virtual
Definition at line 294 of file AP_Camera_Backend.cpp.
Referenced by AP_Camera::send_camera_capture_status().
send_camera_feedback()
void AP_Camera_Backend::send_camera_feedback (mavlink_channel_t chan)
Definition at line 177 of file AP_Camera_Backend.cpp.
Referenced by AP_Camera::send_feedback().
send_camera_information()
void AP_Camera_Backend::send_camera_information (mavlink_channel_t chan) const virtual
Definition at line 212 of file AP_Camera_Backend.cpp.
Referenced by AP_Camera::send_camera_information().
send_camera_settings()
void AP_Camera_Backend::send_camera_settings (mavlink_channel_t chan) const virtual
Definition at line 241 of file AP_Camera_Backend.cpp.
Referenced by AP_Camera::send_camera_settings().
set_focus()
virtual SetFocusResult AP_Camera_Backend::set_focus (FocusType focus_type, float focus_value) inline virtual
Definition at line 78 of file AP_Camera_Backend.h.
Referenced by AP_Camera::set_focus().
set_lens()
virtual bool AP_Camera_Backend::set_lens (uint8_t lens) inline virtual
Definition at line 86 of file AP_Camera_Backend.h.
Referenced by AP_Camera::set_lens().
set_tracking()
virtual bool AP_Camera_Backend::set_tracking (TrackingType tracking_type, const Vector2f & p1, const Vector2f & p2) inline virtual
Definition at line 83 of file AP_Camera_Backend.h.
Referenced by AP_Camera::set_tracking().
set_trigger_distance()
void AP_Camera_Backend::set_trigger_distance (float distance_m) inline
Definition at line 102 of file AP_Camera_Backend.h.
Referenced by AP_Camera::set_trigger_distance().
set_zoom()
virtual bool AP_Camera_Backend::set_zoom (ZoomType zoom_type, float zoom_value) inline virtual
Definition at line 74 of file AP_Camera_Backend.h.
Referenced by AP_Camera::set_zoom().
setup_feedback_callback()
void AP_Camera_Backend::setup_feedback_callback () protected
Definition at line 315 of file AP_Camera_Backend.cpp.
Referenced by take_picture().
stop_capture()
void AP_Camera_Backend::stop_capture ()
Definition at line 162 of file AP_Camera_Backend.cpp.
Referenced by AP_Camera::stop_capture().
take_multiple_pictures()
void AP_Camera_Backend::take_multiple_pictures (uint32_t time_interval_ms, int16_t total_num)
Definition at line 156 of file AP_Camera_Backend.cpp.
Referenced by AP_Camera::take_multiple_pictures().
take_picture()
bool AP_Camera_Backend::take_picture ()
Definition at line 126 of file AP_Camera_Backend.cpp.
Referenced by control(), AP_Camera::take_picture(), and update().
trigger_pic()
virtual bool AP_Camera_Backend::trigger_pic () pure virtual
Implemented in AP_Camera_Servo.
Referenced by take_picture().
update()
void AP_Camera_Backend::update () virtual
Reimplemented in AP_Camera_Servo.
Definition at line 18 of file AP_Camera_Backend.cpp.
Referenced by AP_Camera::update(), and AP_Camera_Servo::update().
vertical_fov()
float AP_Camera_Backend::vertical_fov () const inline
Definition at line 90 of file AP_Camera_Backend.h.
Write_Camera()
void AP_Camera_Backend::Write_Camera (uint64_t timestamp_us = 0) protected
Referenced by check_feedback().
Write_CameraInfo()
void AP_Camera_Backend::Write_CameraInfo (enum LogMessages msg, uint64_t timestamp_us = 0) protected
Write_Trigger()
void AP_Camera_Backend::Write_Trigger () protected
Member Data Documentation
_frontend
AP_Camera& AP_Camera_Backend::_frontend protected
Definition at line 130 of file AP_Camera_Backend.h.
_instance
uint8_t AP_Camera_Backend::_instance protected
Definition at line 169 of file AP_Camera_Backend.h.
Referenced by get_mount_instance(), and send_camera_feedback().
_params
AP_Camera_Params& AP_Camera_Backend::_params protected
Definition at line 131 of file AP_Camera_Backend.h.
Referenced by AP_Camera_Servo::configure(), feedback_pin_timer(), get_mount_instance(), horizontal_fov(), set_trigger_distance(), setup_feedback_callback(), take_picture(), AP_Camera_Servo::trigger_pic(), update(), AP_Camera_Servo::update(), and vertical_fov().
[struct]
struct { ... } AP_Camera_Backend::camera_feedback
Referenced by prep_mavlink_msg_camera_feedback(), and send_camera_feedback().
feedback_trigger_count
uint32_t AP_Camera_Backend::feedback_trigger_count protected
Definition at line 173 of file AP_Camera_Backend.h.
Referenced by check_feedback(), feedback_pin_isr(), and feedback_pin_timer().
feedback_trigger_logged_count
uint32_t AP_Camera_Backend::feedback_trigger_logged_count
Definition at line 147 of file AP_Camera_Backend.h.
Referenced by check_feedback(), and prep_mavlink_msg_camera_feedback().
feedback_trigger_timestamp_us
uint32_t AP_Camera_Backend::feedback_trigger_timestamp_us protected
Definition at line 174 of file AP_Camera_Backend.h.
Referenced by check_feedback(), feedback_pin_isr(), and feedback_pin_timer().
image_index
uint16_t AP_Camera_Backend::image_index protected
Definition at line 179 of file AP_Camera_Backend.h.
Referenced by send_camera_capture_status(), send_camera_feedback(), and take_picture().
isr_installed
bool AP_Camera_Backend::isr_installed protected
Definition at line 171 of file AP_Camera_Backend.h.
Referenced by setup_feedback_callback().
last_is_armed
bool AP_Camera_Backend::last_is_armed protected
Definition at line 180 of file AP_Camera_Backend.h.
Referenced by update().
last_location
Location AP_Camera_Backend::last_location protected
Definition at line 178 of file AP_Camera_Backend.h.
Referenced by take_picture().
last_picture_time_ms
uint32_t AP_Camera_Backend::last_picture_time_ms protected
Definition at line 177 of file AP_Camera_Backend.h.
Referenced by take_picture().
last_pin_state
uint8_t AP_Camera_Backend::last_pin_state protected
Definition at line 172 of file AP_Camera_Backend.h.
Referenced by feedback_pin_timer().
location
Location AP_Camera_Backend::location
Definition at line 143 of file AP_Camera_Backend.h.
num_remaining
int16_t AP_Camera_Backend::num_remaining
Definition at line 153 of file AP_Camera_Backend.h.
pitch_sensor
int32_t AP_Camera_Backend::pitch_sensor
Definition at line 145 of file AP_Camera_Backend.h.
roll_sensor
int32_t AP_Camera_Backend::roll_sensor
Definition at line 144 of file AP_Camera_Backend.h.
time_interval_ms
uint32_t AP_Camera_Backend::time_interval_ms
Definition at line 152 of file AP_Camera_Backend.h.
Referenced by take_multiple_pictures().
[struct]
struct { ... } AP_Camera_Backend::time_interval_settings
Referenced by send_camera_capture_status(), stop_capture(), and take_multiple_pictures().
timer_installed
bool AP_Camera_Backend::timer_installed protected
Definition at line 170 of file AP_Camera_Backend.h.
Referenced by setup_feedback_callback().
timestamp_us
uint64_t AP_Camera_Backend::timestamp_us
Definition at line 142 of file AP_Camera_Backend.h.
Referenced by feedback_pin_isr(), and prep_mavlink_msg_camera_feedback().
trigger_pending
bool AP_Camera_Backend::trigger_pending protected
Definition at line 176 of file AP_Camera_Backend.h.
Referenced by take_picture(), and update().
yaw_sensor
int32_t AP_Camera_Backend::yaw_sensor
Definition at line 146 of file AP_Camera_Backend.h.
The documentation for this class was generated from the following files:
libraries/AP_Camera/AP_Camera_Backend.h
libraries/AP_Camera/AP_Camera_Backend.cpp