APM:Libraries: Linux::GPIO_Sysfs Class Reference
Linux::GPIO_Sysfs Class Reference
#include <GPIO_Sysfs.h>
Public Member Functions
void init () override
void pinMode (uint8_t vpin, uint8_t output) override
uint8_t read (uint8_t vpin) override
void write (uint8_t vpin, uint8_t value) override
void toggle (uint8_t vpin) override
AP_HAL::DigitalSource * channel (uint16_t vpin) override
bool usb_connected () override
Public Member Functions inherited from AP_HAL::GPIO
GPIO ()
virtual void pinMode (uint8_t pin, uint8_t output, uint8_t alt)
virtual bool valid_pin (uint8_t pin) const
virtual bool pin_to_servo_channel (uint8_t pin, uint8_t &servo_ch) const
virtual bool get_mode (uint8_t pin, uint32_t &mode)
virtual void set_mode (uint8_t pin, uint32_t mode)
FUNCTOR_TYPEDEF (irq_handler_fn_t, void, uint8_t, bool, uint32_t)
virtual bool attach_interrupt (uint8_t pin, irq_handler_fn_t fn, INTERRUPT_TRIGGER_TYPE mode)
virtual bool attach_interrupt (uint8_t pin, AP_HAL::Proc proc, INTERRUPT_TRIGGER_TYPE mode)
bool detach_interrupt (uint8_t pin)
virtual bool wait_pin (uint8_t pin, INTERRUPT_TRIGGER_TYPE mode, uint32_t timeout_us)
virtual void timer_tick (void)
virtual bool arming_checks (size_t buflen, char *buffer) const
Static Public Member Functions
static GPIO_Sysfs * from (AP_HAL::GPIO *gpio)
Static Public Attributes
static const unsigned pin_table []
static const uint8_t n_pins = _AERO_GPIO_MAX
Protected Member Functions
void _pinMode (unsigned int pin, uint8_t output)
int _open_pin_value (unsigned int pin, int flags)
Static Protected Member Functions
static bool _export_pin (uint8_t vpin)
Friends
class DigitalSource_Sysfs
Additional Inherited Members
Public Types inherited from AP_HAL::GPIO
enum INTERRUPT_TRIGGER_TYPE { INTERRUPT_NONE , INTERRUPT_FALLING , INTERRUPT_RISING , INTERRUPT_BOTH }
Detailed Description
Generic implementation of AP_HAL::GPIO for Linux based boards.
Definition at line 29 of file GPIO_Sysfs.h.
Member Function Documentation
_export_pin()
bool GPIO_Sysfs::_export_pin (uint8_t vpin) static protected
Definition at line 216 of file GPIO_Sysfs.cpp.
Referenced by channel(), and pinMode().
_open_pin_value()
int GPIO_Sysfs::_open_pin_value (unsigned int pin, int flags) protected
Definition at line 120 of file GPIO_Sysfs.cpp.
Referenced by channel(), read(), and write().
_pinMode()
void GPIO_Sysfs::_pinMode (unsigned int pin, uint8_t output) protected
Definition at line 107 of file GPIO_Sysfs.cpp.
Referenced by pinMode().
channel()
AP_HAL::DigitalSource * GPIO_Sysfs::channel (uint16_t vpin) override virtual
Implements AP_HAL::GPIO.
Definition at line 194 of file GPIO_Sysfs.cpp.
from()
static GPIO_Sysfs * Linux::GPIO_Sysfs::from (AP_HAL::GPIO * gpio) inline static
Definition at line 36 of file GPIO_Sysfs.h.
Referenced by Linux::DigitalSource_Sysfs::mode().
init()
void GPIO_Sysfs::init () override virtual
Implements AP_HAL::GPIO.
Definition at line 81 of file GPIO_Sysfs.cpp.
pinMode()
void GPIO_Sysfs::pinMode (uint8_t vpin, uint8_t output) override virtual
Implements AP_HAL::GPIO.
Definition at line 94 of file GPIO_Sysfs.cpp.
read()
uint8_t GPIO_Sysfs::read (uint8_t vpin) override virtual
Implements AP_HAL::GPIO.
Definition at line 136 of file GPIO_Sysfs.cpp.
Referenced by toggle().
toggle()
void GPIO_Sysfs::toggle (uint8_t vpin) override virtual
Implements AP_HAL::GPIO.
Definition at line 189 of file GPIO_Sysfs.cpp.
usb_connected()
bool GPIO_Sysfs::usb_connected (void) override virtual
Implements AP_HAL::GPIO.
Definition at line 211 of file GPIO_Sysfs.cpp.
write()
void GPIO_Sysfs::write (uint8_t vpin, uint8_t value) override virtual
Implements AP_HAL::GPIO.
Definition at line 161 of file GPIO_Sysfs.cpp.
Referenced by toggle().
Friends And Related Symbol Documentation
DigitalSource_Sysfs
friend class DigitalSource_Sysfs friend
Definition at line 30 of file GPIO_Sysfs.h.
Referenced by channel().
Member Data Documentation
n_pins
const uint8_t Linux::GPIO_Sysfs::n_pins = _AERO_GPIO_MAX static
Definition at line 34 of file GPIO_Sysfs.h.
Referenced by _export_pin(), channel(), pinMode(), read(), and write().
pin_table
const unsigned Linux::GPIO_Sysfs::pin_table static
Initial value:
= {
    [AERO_GPIO_BMI160_INT1] = 411,
}
Definition at line 23 of file GPIO_Sysfs.h.
Referenced by _export_pin(), channel(), pinMode(), read(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/GPIO_Sysfs.h
libraries/AP_HAL_Linux/GPIO_Aero.cpp
libraries/AP_HAL_Linux/GPIO_Bebop.cpp
libraries/AP_HAL_Linux/GPIO_Disco.cpp
libraries/AP_HAL_Linux/GPIO_Edge.cpp
libraries/AP_HAL_Linux/GPIO_Navio.cpp
libraries/AP_HAL_Linux/GPIO_Navio2.cpp
libraries/AP_HAL_Linux/GPIO_Sysfs.cpp