APM:Libraries: Location Class Reference
Location Class Reference
#include <Location.h>
Public Types
enum class AltFrame { ABSOLUTE = 0 , ABOVE_HOME = 1 , ABOVE_ORIGIN = 2 , ABOVE_TERRAIN = 3 }
enumeration of possible altitude types
Public Member Functions
Location ()
constructors
Location (int32_t latitude, int32_t longitude, int32_t alt_in_cm, AltFrame frame)
Location (const Vector3f &ekf_offset_neu, AltFrame frame)
Location (const Vector3d &ekf_offset_neu, AltFrame frame)
void set_alt_cm (int32_t alt_cm, AltFrame frame)
bool get_alt_cm (AltFrame desired_frame, int32_t &ret_alt_cm) const WARN_IF_UNUSED
get altitude in desired frame
AltFrame get_alt_frame () const
bool change_alt_frame (AltFrame desired_frame)
bool get_vector_xy_from_origin_NE (Vector2f &vec_ne) const WARN_IF_UNUSED
bool get_vector_from_origin_NEU (Vector3f &vec_neu) const WARN_IF_UNUSED
ftype get_distance (const Location &loc2) const
bool get_alt_distance (const Location &loc2, ftype &distance) const WARN_IF_UNUSED
Vector3f get_distance_NED (const Location &loc2) const
Vector3d get_distance_NED_double (const Location &loc2) const
Vector2f get_distance_NE (const Location &loc2) const
Vector2d get_distance_NE_double (const Location &loc2) const
Vector2F get_distance_NE_ftype (const Location &loc2) const
void offset (ftype ofs_north, ftype ofs_east)
void offset (const Vector3p &ofs_ned)
void offset_bearing (ftype bearing_deg, ftype distance)
void offset_bearing_and_pitch (ftype bearing_deg, ftype pitch_deg, ftype distance)
bool is_zero (void) const WARN_IF_UNUSED
void zero (void)
ftype get_bearing (const Location &loc2) const
int32_t get_bearing_to (const Location &loc2) const
bool same_latlon_as (const Location &loc2) const
bool same_alt_as (const Location &loc2) const
bool same_loc_as (const Location &loc2) const
bool sanitize (const Location &defaultLoc)
bool check_latlng () const
bool past_interval_finish_line (const Location &point1, const Location &point2) const
float line_path_proportion (const Location &point1, const Location &point2) const
void linearly_interpolate_alt (const Location &point1, const Location &point2)
bool initialised () const
Static Public Member Functions
static void offset_latlng (int32_t &lat, int32_t &lng, ftype ofs_north, ftype ofs_east)
static ftype longitude_scale (int32_t lat)
static int32_t wrap_longitude (int64_t lon)
static int32_t limit_lattitude (int32_t lat)
static int32_t diff_longitude (int32_t lon1, int32_t lon2)
Public Attributes
uint8_t relative_alt: 1
uint8_t loiter_ccw: 1
uint8_t terrain_alt: 1
uint8_t origin_alt: 1
uint8_t loiter_xtrack: 1
int32_t alt
int32_t lat
int32_t lng
Static Private Attributes
static constexpr float LOCATION_SCALING_FACTOR = LATLON_TO_M
static constexpr float LOCATION_SCALING_FACTOR_INV = LATLON_TO_M_INV
Detailed Description
Definition at line 7 of file Location.h.
Member Enumeration Documentation
AltFrame
enum class Location::AltFrame strong
enumeration of possible altitude types
Enumerator
ABSOLUTE
ABOVE_HOME
ABOVE_ORIGIN
ABOVE_TERRAIN
Definition at line 23 of file Location.h.
Constructor & Destructor Documentation
Location() [1/4]
Location::Location ()
constructors
Definition at line 11 of file Location.cpp.
Location() [2/4]
Location::Location (int32_t latitude, int32_t longitude, int32_t alt_in_cm, AltFrame frame)
Definition at line 28 of file Location.cpp.
Location() [3/4]
Location::Location (const Vector3f & ekf_offset_neu, AltFrame frame)
Location() [4/4]
Location::Location (const Vector3d & ekf_offset_neu, AltFrame frame)
Member Function Documentation
change_alt_frame()
bool Location::change_alt_frame (AltFrame desired_frame)
Definition at line 83 of file Location.cpp.
Referenced by AP_Follow::handle_msg(), and AP_AHRS::set_home().
check_latlng()
bool Location::check_latlng () const
Definition at line 422 of file Location.cpp.
Referenced by GCS_MAVLINK::handle_command_do_set_roi(), sanitize(), and AP_AHRS::set_home().
diff_longitude()
int32_t Location::diff_longitude (int32_t lon1, int32_t lon2) static
Definition at line 471 of file Location.cpp.
Referenced by AP_Mount_Backend::get_angle_target_to_location(), get_bearing(), get_distance(), get_distance_NE(), get_distance_NE_double(), get_distance_NE_ftype(), get_distance_NED(), and get_distance_NED_double().
get_alt_cm()
bool Location::get_alt_cm (AltFrame desired_frame, int32_t & ret_alt_cm) const
get altitude in desired frame
Definition at line 109 of file Location.cpp.
Referenced by AP_OABendyRuler::calc_margin_from_alt_fence(), change_alt_frame(), get_alt_distance(), AP_Mount_Backend::get_angle_target_to_location(), AC_WPNav::get_vector_NEU(), sanitize(), GCS_MAVLINK::send_set_position_target_global_int(), and AC_Circle::set_center().
get_alt_distance()
bool Location::get_alt_distance (const Location & loc2, ftype & distance) const
Definition at line 252 of file Location.cpp.
Referenced by same_alt_as().
get_alt_frame()
Location::AltFrame Location::get_alt_frame () const
Definition at line 94 of file Location.cpp.
Referenced by get_alt_cm(), AC_WPNav::get_vector_NEU(), linearly_interpolate_alt(), same_alt_as(), sanitize(), and AC_Circle::set_center().
get_bearing()
ftype Location::get_bearing (const Location & loc2) const
Definition at line 388 of file Location.cpp.
Referenced by get_bearing_to(), and SITL::ShipSim::get_ground_speed_adjustment().
get_bearing_to()
int32_t Location::get_bearing_to (const Location & loc2) const inline
Definition at line 106 of file Location.h.
Referenced by AP_Frsky_SPort_Passthrough::calc_home(), AP_OSD_Screen::draw_home(), AR_WPNav::get_corner_angle(), AP_OABendyRuler::search_xy_path(), test_one_offset(), AP_Landing::type_slope_setup_landing_glide_slope(), AP_Landing::type_slope_verify_abort_landing(), AP_Landing::type_slope_verify_land(), AP_OABendyRuler::update(), AR_WPNav::update_distance_and_bearing_to_destination(), AP_MSP_Telem_Backend::update_home_pos(), AP_L1_Control::update_loiter(), AR_WPNav_OA::update_oa_distance_and_bearing_to_destination(), and AP_L1_Control::update_waypoint().
get_distance()
ftype Location::get_distance (const Location & loc2) const
Definition at line 244 of file Location.cpp.
Referenced by AR_WPNav::advance_wp_target_along_track(), AP_Rally::calc_best_rally_or_home_location(), AP_Frsky_SPort_Passthrough::calc_home(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AP_OSD_Screen::draw_home(), AP_Rally::find_nearest_rally_point(), SITL::ShipSim::get_ground_speed_adjustment(), AP_AdvancedFailsafe::max_range_update(), SITL::SilentWings::process_packet(), AP_OABendyRuler::search_xy_path(), test_one_offset(), AP_Landing::type_slope_adjust_landing_slope_for_rangefinder_bump(), AP_Landing::type_slope_setup_landing_glide_slope(), AP_Landing::type_slope_verify_land(), AP_OABendyRuler::update(), AR_WPNav::update_distance_and_bearing_to_destination(), AP_MSP_Telem_Backend::update_home_pos(), AR_WPNav_OA::update_oa_distance_and_bearing_to_destination(), SITL::ADSB::update_simulated_vehicles(), and AP_OSD::update_stats().
get_distance_NE()
Vector2f Location::get_distance_NE (const Location & loc2) const
Definition at line 266 of file Location.cpp.
Referenced by AP_GPS::calc_blended_state(), AR_WPNav::calc_crosstrack_error(), AP_OABendyRuler::calc_margin_from_circular_fence(), AP_AHRS::get_relative_position_NE_home(), line_path_proportion(), AP_Beacon_SITL::update(), SITL::ADSB_Vehicle::update(), AP_L1_Control::update_loiter(), and AP_L1_Control::update_waypoint().
get_distance_NE_double()
Vector2d Location::get_distance_NE_double (const Location & loc2) const
Definition at line 288 of file Location.cpp.
Referenced by TEST().
get_distance_NE_ftype()
Vector2F Location::get_distance_NE_ftype (const Location & loc2) const
Definition at line 294 of file Location.cpp.
Referenced by NavEKF3_core::CorrectExtNavForSensorOffset(), NavEKF2_core::getPosNE(), NavEKF3_core::getPosNE(), NavEKF3_core::moveEKFOrigin(), NavEKF2_core::readGpsData(), NavEKF3_core::ResetPosition(), and NavEKF3_core::SelectVelPosFusion().
get_distance_NED()
Vector3f Location::get_distance_NED (const Location & loc2) const
Definition at line 273 of file Location.cpp.
Referenced by AP_GPS::all_consistent(), AP_AHRS::get_relative_position_NED_home(), and AP_Follow::get_target_dist_and_vel_ned().
get_distance_NED_double()
Vector3d Location::get_distance_NED_double (const Location & loc2) const
Definition at line 281 of file Location.cpp.
get_vector_from_origin_NEU()
bool Location::get_vector_from_origin_NEU (Vector3f & vec_neu) const
Referenced by AP_OABendyRuler::calc_margin_from_object_database(), AC_Circle::set_center(), SITL::SIM_Precland::update(), and AC_WPNav_OA::update_wpnav().
get_vector_xy_from_origin_NE()
bool Location::get_vector_xy_from_origin_NE (Vector2f & vec_ne) const
Referenced by AR_WPNav::advance_wp_target_along_track(), AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_circles(), AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_polygons(), AC_WPNav::get_vector_NEU(), AC_Circle::set_center(), AR_WPNav::set_desired_location(), AR_WPNav::update_psc_input_shaping(), and AC_WPNav_OA::update_wpnav().
initialised()
bool Location::initialised () const inline
Definition at line 149 of file Location.h.
Referenced by get_alt_cm(), AP_Mount_Backend::get_angle_target_to_location(), AR_WPNav::get_corner_angle(), AR_WPNav::set_desired_location(), and TEST().
is_zero()
bool Location::is_zero (void) const
Definition at line 17 of file Location.cpp.
Referenced by TEST().
limit_lattitude()
int32_t Location::limit_lattitude (int32_t lat) static
Definition at line 489 of file Location.cpp.
Referenced by offset_latlng().
line_path_proportion()
float Location::line_path_proportion (const Location & point1, const Location & point2) const
Definition at line 443 of file Location.cpp.
Referenced by linearly_interpolate_alt(), past_interval_finish_line(), and AP_Landing::type_slope_setup_landing_glide_slope().
linearly_interpolate_alt()
void Location::linearly_interpolate_alt (const Location & point1, const Location & point2)
Definition at line 503 of file Location.cpp.
Referenced by AC_WPNav_OA::update_wpnav().
longitude_scale()
ftype Location::longitude_scale (int32_t lat) static
Definition at line 349 of file Location.cpp.
Referenced by get_bearing(), get_distance(), get_distance_NE(), get_distance_NE_double(), get_distance_NE_ftype(), get_distance_NED(), get_distance_NED_double(), and offset_latlng().
offset() [1/2]
void Location::offset (const Vector3p & ofs_ned)
Definition at line 318 of file Location.cpp.
offset() [2/2]
void Location::offset (ftype ofs_north, ftype ofs_east)
Definition at line 311 of file Location.cpp.
Referenced by AP_GPS::calc_blended_state(), NavEKF3_core::checkUpdateEarthField(), SITL::ShipSim::get_ground_speed_adjustment(), AP_AHRS::get_location_from_home_offset(), AP_AHRS::get_location_from_origin_offset(), AR_WPNav::get_stopping_location(), SoaringController::get_target(), AC_PrecLand::get_target_location(), AP_Follow::get_target_location_and_velocity(), AP_Follow::get_target_location_and_velocity_ofs(), NavEKF2_core::getLLH(), NavEKF3_core::getLLH(), NavEKF3_core::moveEKFOrigin(), offset_bearing(), offset_bearing_and_pitch(), SITL::ShipSim::send_report(), AR_WPNav::set_desired_location_NED(), AR_WPNav::set_desired_location_NED(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), test_one_offset(), AP_Beacon_SITL::update(), SITL::ADSB_Vehicle::update(), and SITL::ShipSim::update().
offset_bearing()
void Location::offset_bearing (ftype bearing_deg, ftype distance)
Definition at line 331 of file Location.cpp.
Referenced by SITL::ShipSim::get_ground_speed_adjustment(), AP_OABendyRuler::resist_bearing_change(), AP_OABendyRuler::search_xy_path(), TEST(), AP_Landing::type_slope_setup_landing_glide_slope(), and AP_Landing::type_slope_verify_land().
offset_bearing_and_pitch()
void Location::offset_bearing_and_pitch (ftype bearing_deg, ftype pitch_deg, ftype distance)
Definition at line 339 of file Location.cpp.
Referenced by AP_OABendyRuler::search_vertical_path(), and TEST().
offset_latlng()
void Location::offset_latlng (int32_t & lat, int32_t & lng, ftype ofs_north, ftype ofs_east) static
Definition at line 301 of file Location.cpp.
Referenced by NavEKF3_core::CorrectGPSForAntennaOffset(), offset(), and offset().
past_interval_finish_line()
bool Location::past_interval_finish_line (const Location & point1, const Location & point2) const
Definition at line 432 of file Location.cpp.
Referenced by AR_WPNav::advance_wp_target_along_track(), and test_passed_waypoint().
same_alt_as()
bool Location::same_alt_as (const Location & loc2) const
Definition at line 407 of file Location.cpp.
Referenced by same_loc_as().
same_latlon_as()
bool Location::same_latlon_as (const Location & loc2) const
Definition at line 402 of file Location.cpp.
Referenced by AP_OAPathPlanner::mission_avoidance(), AP_OABendyRuler::resist_bearing_change(), same_loc_as(), TEST(), TEST(), and AR_WPNav_OA::update().
same_loc_as()
bool Location::same_loc_as (const Location & loc2) const inline
Definition at line 117 of file Location.h.
sanitize()
bool Location::sanitize (const Location & defaultLoc)
Definition at line 358 of file Location.cpp.
Referenced by TEST().
set_alt_cm()
void Location::set_alt_cm (int32_t alt_cm, AltFrame frame)
Definition at line 57 of file Location.cpp.
Referenced by AP_Rally::calc_best_rally_or_home_location(), change_alt_frame(), NavEKF2_core::getLLH(), NavEKF3_core::getLLH(), AP_Mount_Backend::handle_global_position_int(), AP_Follow::handle_msg(), linearly_interpolate_alt(), AP_AHRS::load_watchdog_home(), Location(), GCS_MAVLINK::location_from_command_t(), and TEST().
wrap_longitude()
int32_t Location::wrap_longitude (int64_t lon) static
Definition at line 458 of file Location.cpp.
Referenced by offset_latlng().
zero()
void Location::zero (void)
Definition at line 22 of file Location.cpp.
Referenced by Location(), Location(), and AC_WPNav_OA::update_wpnav().
Member Data Documentation
alt
int32_t Location::alt
Definition at line 18 of file Location.h.
Referenced by AP_GPS_SBP::_attempt_state_update(), AP_GPS_SBP2::_attempt_state_update(), AP_GPS_UBLOX::_parse_gps(), AP_Baro::arming_checks(), AP_GPS::calc_blended_state(), AP_Spektrum_Telem::calc_gps_location(), AP_Frsky_Backend::calc_gps_position(), AP_Spektrum_Telem::calc_gps_status(), AP_Frsky_SPort_Passthrough::calc_gps_status(), AP_Frsky_SPort_Passthrough::calc_home(), AP_Frsky_Backend::calc_nav_alt(), AP_AdvancedFailsafe::check_altlimit(), get_alt_cm(), get_distance_NED(), get_distance_NED_double(), AP_Beacon::get_origin(), AP_AHRS::get_relative_position_D_home(), AP_Follow::get_target_dist_and_vel_ned(), AC_PrecLand::get_target_location(), AP_Follow::get_target_location_and_velocity(), AP_Follow::get_target_location_and_velocity_ofs(), NavEKF2_core::getLLH(), NavEKF3_core::getLLH(), NavEKF2_core::getOriginLLH(), NavEKF3_core::getOriginLLH(), NavEKF2_core::getPosD(), NavEKF3_core::getPosD(), NavEKF3_core::getPosD_local(), GCS_MAVLINK::global_position_int_alt(), GCS_MAVLINK::handle_command_do_set_roi(), AP_DAL::handle_message(), AP_DAL_GPS::handle_message(), AP_Follow::handle_msg(), initialised(), linearly_interpolate_alt(), AP_DAL::log_SetOriginLLH2(), AP_DAL::log_SetOriginLLH3(), loop(), offset(), offset_bearing_and_pitch(), HALSITL::SITL_State::parse_home(), MissionTest::print_mission(), AP_GPS_GSOF::process_message(), SITL::SilentWings::process_packet(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), NavEKF2_core::resetHeightDatum(), NavEKF3_core::resetHeightDatum(), AP_Landing::restart_landing_sequence(), MissionTest::run_max_cmd_test(), same_alt_as(), sanitize(), GCS_MAVLINK::send_high_latency2(), AP_GPS::send_mavlink_gps2_raw(), AP_GPS::send_mavlink_gps_raw(), SITL::ShipSim::send_report(), SITL::ADSB_Sagetech_MXS::send_vehicle_message_state_vector(), AP_GPS_Backend::set_alt_amsl_cm(), set_alt_cm(), AP_AHRS::set_home(), NavEKF2_core::setOrigin(), NavEKF3_core::setOrigin(), AP_DAL_GPS::start_frame(), AP_DAL::start_frame(), TEST(), TEST(), AP_Landing::type_slope_adjust_landing_slope_for_rangefinder_bump(), AP_Landing::type_slope_setup_landing_glide_slope(), AP_Landing::type_slope_verify_land(), AP_Beacon_SITL::update(), SITL::ShipSim::update(), AP_Baro::update_field_elevation(), AC_WPNav_OA::update_wpnav(), and GCS_MAVLINK::vfr_hud_alt().
lat
int32_t Location::lat
Definition at line 19 of file Location.h.
Referenced by AP_GPS_SBP::_attempt_state_update(), AP_GPS_SBP2::_attempt_state_update(), AP_GPS_ERB::_parse_gps(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_SIRF::_parse_gps(), AP_GPS_NMEA::_term_complete(), AP_Frsky_SPort::calc_gps_latlng(), AP_Spektrum_Telem::calc_gps_location(), AP_Frsky_Backend::calc_gps_position(), AP_Frsky_SPort_Passthrough::calc_home(), check_latlng(), AP_OSD_Screen::draw_gps_latitude(), AP_Mount_Backend::get_angle_target_to_location(), get_bearing(), get_distance(), get_distance_NE(), get_distance_NE_double(), get_distance_NE_ftype(), get_distance_NED(), get_distance_NED_double(), AP_Declination::get_earth_field_ga(), AP_Beacon::get_origin(), NavEKF3_core::getEarthFieldTable(), NavEKF2_core::getLLH(), NavEKF3_core::getLLH(), GCS_MAVLINK::handle_command_do_set_roi(), AP_Mount_Backend::handle_global_position_int(), AP_DAL::handle_message(), AP_DAL_GPS::handle_message(), AP_Follow::handle_msg(), initialised(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), limit_lattitude(), AP_AHRS::load_watchdog_home(), Location(), GCS_MAVLINK::location_from_command_t(), location_from_point(), AP_DAL::log_SetLatLng(), AP_DAL::log_SetOriginLLH2(), AP_DAL::log_SetOriginLLH3(), longitude_scale(), loop(), offset(), offset(), offset_latlng(), HALSITL::SITL_State::parse_home(), MissionTest::print_mission(), AP_GPS_NOVA::process_message(), AP_GPS_SBF::process_message(), AP_GPS_GSOF::process_message(), SITL::SilentWings::process_packet(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), same_latlon_as(), sanitize(), AP_LTM_Telem::send_Gframe(), GCS_MAVLINK::send_global_position_int(), AP_Hott_Telem::send_GPS(), GCS_MAVLINK::send_high_latency2(), AP_GPS::send_mavlink_gps2_raw(), AP_GPS::send_mavlink_gps_raw(), SITL::ShipSim::send_report(), GCS_MAVLINK::send_set_position_target_global_int(), SITL::ADSB_Sagetech_MXS::send_vehicle_message_state_vector(), AP_AHRS::set_home(), NavEKF2_core::setOrigin(), NavEKF3_core::setOrigin(), AP_DAL_GPS::start_frame(), AP_DAL::start_frame(), test_accuracy(), test_offset(), Compass::try_set_initial_location(), AP_Beacon_SITL::update(), and SITL::ShipSim::update().
lng
int32_t Location::lng
Definition at line 20 of file Location.h.
Referenced by AP_GPS_SBP::_attempt_state_update(), AP_GPS_SBP2::_attempt_state_update(), AP_GPS_ERB::_parse_gps(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_SIRF::_parse_gps(), AP_GPS_NMEA::_term_complete(), AP_Frsky_SPort::calc_gps_latlng(), AP_Spektrum_Telem::calc_gps_location(), AP_Frsky_Backend::calc_gps_position(), AP_Frsky_SPort_Passthrough::calc_home(), check_latlng(), AP_OSD_Screen::draw_gps_longitude(), AP_Mount_Backend::get_angle_target_to_location(), get_bearing(), get_distance(), get_distance_NE(), get_distance_NE_double(), get_distance_NE_ftype(), get_distance_NED(), get_distance_NED_double(), AP_Declination::get_earth_field_ga(), AP_Beacon::get_origin(), NavEKF3_core::getEarthFieldTable(), NavEKF2_core::getLLH(), NavEKF3_core::getLLH(), GCS_MAVLINK::handle_command_do_set_roi(), AP_Mount_Backend::handle_global_position_int(), AP_DAL::handle_message(), AP_DAL_GPS::handle_message(), AP_Follow::handle_msg(), initialised(), AP_AHRS::load_watchdog_home(), Location(), GCS_MAVLINK::location_from_command_t(), location_from_point(), AP_DAL::log_SetLatLng(), AP_DAL::log_SetOriginLLH2(), AP_DAL::log_SetOriginLLH3(), loop(), offset(), offset(), offset_latlng(), HALSITL::SITL_State::parse_home(), MissionTest::print_mission(), AP_GPS_NOVA::process_message(), AP_GPS_SBF::process_message(), AP_GPS_GSOF::process_message(), SITL::SilentWings::process_packet(), NavEKF2_core::readGpsData(), NavEKF3_core::readGpsData(), same_latlon_as(), sanitize(), AP_LTM_Telem::send_Gframe(), GCS_MAVLINK::send_global_position_int(), AP_Hott_Telem::send_GPS(), GCS_MAVLINK::send_high_latency2(), AP_GPS::send_mavlink_gps2_raw(), AP_GPS::send_mavlink_gps_raw(), SITL::ShipSim::send_report(), GCS_MAVLINK::send_set_position_target_global_int(), SITL::ADSB_Sagetech_MXS::send_vehicle_message_state_vector(), AP_AHRS::set_home(), AP_DAL_GPS::start_frame(), AP_DAL::start_frame(), test_accuracy(), Compass::try_set_initial_location(), AP_Beacon_SITL::update(), and SITL::ShipSim::update().
LOCATION_SCALING_FACTOR
constexpr float Location::LOCATION_SCALING_FACTOR = LATLON_TO_M static constexpr private
Definition at line 164 of file Location.h.
Referenced by get_distance(), get_distance_NE(), get_distance_NE_double(), get_distance_NE_ftype(), get_distance_NED(), and get_distance_NED_double().
LOCATION_SCALING_FACTOR_INV
constexpr float Location::LOCATION_SCALING_FACTOR_INV = LATLON_TO_M_INV static constexpr private
Definition at line 166 of file Location.h.
Referenced by offset_latlng().
loiter_ccw
uint8_t Location::loiter_ccw
Definition at line 12 of file Location.h.
loiter_xtrack
uint8_t Location::loiter_xtrack
Definition at line 15 of file Location.h.
origin_alt
uint8_t Location::origin_alt
Definition at line 14 of file Location.h.
Referenced by get_alt_frame(), and set_alt_cm().
relative_alt
uint8_t Location::relative_alt
Definition at line 11 of file Location.h.
Referenced by AP_Frsky_SPort_Passthrough::calc_home(), AP_Frsky_Backend::calc_nav_alt(), get_alt_frame(), AP_Follow::get_target_dist_and_vel_ned(), sanitize(), and set_alt_cm().
terrain_alt
uint8_t Location::terrain_alt
Definition at line 13 of file Location.h.
Referenced by get_alt_frame(), and set_alt_cm().
The documentation for this class was generated from the following files:
libraries/AP_Common/Location.h
libraries/AP_Common/Location.cpp