APM:Libraries: Linux::GPIO_RPI Class Reference
Linux::GPIO_RPI Class Reference
Class for Raspberry PI GPIO control.
#include <GPIO_RPI.h>
Public Member Functions
GPIO_RPI ()
void init () override
void pinMode (uint8_t pin, uint8_t output) override
void pinMode (uint8_t pin, uint8_t output, uint8_t alt) override
uint8_t read (uint8_t pin) override
void write (uint8_t pin, uint8_t value) override
void toggle (uint8_t pin) override
AP_HAL::DigitalSource * channel (uint16_t n) override
bool usb_connected (void) override
Public Member Functions inherited from AP_HAL::GPIO
GPIO ()
virtual bool valid_pin (uint8_t pin) const
virtual bool pin_to_servo_channel (uint8_t pin, uint8_t &servo_ch) const
virtual bool get_mode (uint8_t pin, uint32_t &mode)
virtual void set_mode (uint8_t pin, uint32_t mode)
FUNCTOR_TYPEDEF (irq_handler_fn_t, void, uint8_t, bool, uint32_t)
virtual bool attach_interrupt (uint8_t pin, irq_handler_fn_t fn, INTERRUPT_TRIGGER_TYPE mode)
virtual bool attach_interrupt (uint8_t pin, AP_HAL::Proc proc, INTERRUPT_TRIGGER_TYPE mode)
bool detach_interrupt (uint8_t pin)
virtual bool wait_pin (uint8_t pin, INTERRUPT_TRIGGER_TYPE mode, uint32_t timeout_us)
virtual void timer_tick (void)
virtual bool arming_checks (size_t buflen, char *buffer) const
Private Types
enum class Address : uint32_t { BCM2708_PERIPHERAL_BASE = 0x20000000 , BCM2709_PERIPHERAL_BASE = 0x3F000000 , BCM2711_PERIPHERAL_BASE = 0xFE000000 }
enum class PeripheralOffset : uint32_t { GPIO = 0x200000 }
Private Member Functions
bool openMemoryDevice ()
Open memory device to allow gpio address access Should be used before get_memory_pointer calls in the initialization.
void closeMemoryDevice ()
Close open memory device.
volatile uint32_t * get_memory_pointer (uint32_t address, uint32_t range) const
Return pointer to memory location with specific range access.
uint32_t get_address (GPIO_RPI::Address address, GPIO_RPI::PeripheralOffset offset) const
Get memory address based in base address and peripheral offset.
void set_gpio_mode_alt (int pin, int alternative)
Change functionality of GPIO Function Select Registers (GPFSELn) to any alternative function. Each GPIO pin is mapped to 3 bits inside a 32 bits register, E.g:
void set_gpio_mode_in (int pin)
Set a specific GPIO as input Check Linux::GPIO_RPI::set_gpio_mode_alt for more information.
void set_gpio_mode_out (int pin)
Set a specific GPIO as output Check Linux::GPIO_RPI::set_gpio_mode_alt for more information.
void set_gpio_high (int pin)
Modify GPSET0 (GPIO Pin Output Set 0) register to set pin as high Writing zero to this register has no effect, please use Linux::GPIO_RPI::set_gpio_low to set pin as low.
void set_gpio_low (int pin)
Modify GPCLR0 (GPIO Pin Output Clear 0) register to set pin as low Writing zero to this register has no effect, please use Linux::GPIO_RPI::set_gpio_high to set pin as high.
bool get_gpio_logic_state (int pin)
Read GPLEV0 (GPIO Pin Level 0) register check the logic state of a specific pin.
Private Attributes
volatile uint32_t * _gpio
int _system_memory_device
uint32_t _gpio_output_port_status = 0x00
Static Private Attributes
static const uint8_t _gpio_registers_memory_range = 0xB4
static const char * _system_memory_device_path = "/dev/mem"
Additional Inherited Members
Public Types inherited from AP_HAL::GPIO
enum INTERRUPT_TRIGGER_TYPE { INTERRUPT_NONE , INTERRUPT_FALLING , INTERRUPT_RISING , INTERRUPT_BOTH }
Detailed Description
Class for Raspberry PI GPIO control.
For more information: https://elinux.org/RPi_BCM2835_GPIOs
Definition at line 26 of file GPIO_RPI.h.
Member Enumeration Documentation
Address
enum class Linux::GPIO_RPI::Address : uint32_t strong private
Enumerator
BCM2708_PERIPHERAL_BASE
BCM2709_PERIPHERAL_BASE
BCM2711_PERIPHERAL_BASE
Definition at line 44 of file GPIO_RPI.h.
PeripheralOffset
enum class Linux::GPIO_RPI::PeripheralOffset : uint32_t strong private
Enumerator
GPIO
Definition at line 51 of file GPIO_RPI.h.
Constructor & Destructor Documentation
GPIO_RPI()
GPIO_RPI::GPIO_RPI ()
Definition at line 36 of file GPIO_RPI.cpp.
Member Function Documentation
channel()
AP_HAL::DigitalSource * GPIO_RPI::channel (uint16_t n) override virtual
Implements AP_HAL::GPIO.
Definition at line 245 of file GPIO_RPI.cpp.
closeMemoryDevice()
void GPIO_RPI::closeMemoryDevice () private
Close open memory device.
Definition at line 155 of file GPIO_RPI.cpp.
Referenced by init().
get_address()
uint32_t GPIO_RPI::get_address (GPIO_RPI::Address address, GPIO_RPI::PeripheralOffset offset) const private
Get memory address based in base address and peripheral offset.
Parameters
address
offset
Returns
uint32_t
Definition at line 121 of file GPIO_RPI.cpp.
Referenced by init().
get_gpio_logic_state()
bool GPIO_RPI::get_gpio_logic_state (int pin) private
Read GPLEV0 (GPIO Pin Level 0) register check the logic state of a specific pin.
GPLEV0 is a 32bits register that each bit points to a respective GPIO pin: 0b...101 ││└── GPIO Pin 1, 1st bit, LSBit, Pin is in High state │└─── GPIO Pin 2, 2nd bit, Pin is in Low state └──── GPIO Pin 3, 3rd bit, Pin is in High state
Parameters
pin
Returns
true
false
Definition at line 113 of file GPIO_RPI.cpp.
Referenced by read().
get_memory_pointer()
volatile uint32_t * GPIO_RPI::get_memory_pointer (uint32_t address, uint32_t range) const private
Return pointer to memory location with specific range access.
Parameters
address
range
Returns
volatile uint32_t*
Definition at line 126 of file GPIO_RPI.cpp.
Referenced by init().
init()
void GPIO_RPI::init () override virtual
Implements AP_HAL::GPIO.
Definition at line 162 of file GPIO_RPI.cpp.
openMemoryDevice()
bool GPIO_RPI::openMemoryDevice () private
Open memory device to allow gpio address access Should be used before get_memory_pointer calls in the initialization.
Returns
true
false
Definition at line 144 of file GPIO_RPI.cpp.
Referenced by init().
pinMode() [1/2]
void GPIO_RPI::pinMode (uint8_t pin, uint8_t output) override virtual
Implements AP_HAL::GPIO.
Definition at line 194 of file GPIO_RPI.cpp.
Referenced by GPIO_Navigator::pinMode(), and GPIO_Navigator::pinMode().
pinMode() [2/2]
void GPIO_RPI::pinMode (uint8_t pin, uint8_t output, uint8_t alt) override virtual
Reimplemented from AP_HAL::GPIO.
Definition at line 204 of file GPIO_RPI.cpp.
read()
uint8_t GPIO_RPI::read (uint8_t pin) override virtual
Implements AP_HAL::GPIO.
Definition at line 217 of file GPIO_RPI.cpp.
Referenced by GPIO_Navigator::read().
set_gpio_high()
void GPIO_RPI::set_gpio_high (int pin) private
Modify GPSET0 (GPIO Pin Output Set 0) register to set pin as high Writing zero to this register has no effect, please use Linux::GPIO_RPI::set_gpio_low to set pin as low.
GPSET0 is a 32bits register that each bit points to a respective GPIO pin: 0b...101 ││└── GPIO Pin 1, 1st bit, LSBit, defined as High │└─── GPIO Pin 2, 2nd bit, No effect └──── GPIO Pin 3, 3rd bit, defined as High ...
Parameters
pin
Definition at line 97 of file GPIO_RPI.cpp.
Referenced by write().
set_gpio_low()
void GPIO_RPI::set_gpio_low (int pin) private
Modify GPCLR0 (GPIO Pin Output Clear 0) register to set pin as low Writing zero to this register has no effect, please use Linux::GPIO_RPI::set_gpio_high to set pin as high.
GPCLR0 is a 32bits register that each bit points to a respective GPIO pin: 0b...101 ││└── GPIO Pin 1, 1st bit, LSBit, defined as Low │└─── GPIO Pin 2, 2nd bit, No effect └──── GPIO Pin 3, 3rd bit, defined as Low
Parameters
pin
Definition at line 105 of file GPIO_RPI.cpp.
Referenced by write().
set_gpio_mode_alt()
void GPIO_RPI::set_gpio_mode_alt (int pin, int alternative) private
Change functionality of GPIO Function Select Registers (GPFSELn) to any alternative function. Each GPIO pin is mapped to 3 bits inside a 32 bits register, E.g:
0b00...'010'101 ││ │││ ││└── GPIO Pin N, 1st bit, LSBit ││ │││ │└─── GPIO Pin N, 2nd bit ││ │││ └──── GPIO Pin N, 3rd bit, MSBit ││ ││└────── GPIO Pin N+1, 1st bit, LSBit ││ │└─────── GPIO Pin N+1, 2nd bit, ││ └──────── GPIO Pin N+1, 3rd bit, MSBit ││ ... │└───────────── Reserved └────────────── Reserved
And the value of this 3 bits selects the functionality of the GPIO pin, E.g: 000 = GPIO Pin N is an input 001 = GPIO Pin N is an output 100 = GPIO Pin N takes alternate function 0 101 = GPIO Pin N takes alternate function 1 110 = GPIO Pin N takes alternate function 2 111 = GPIO Pin N takes alternate function 3 011 = GPIO Pin N takes alternate function 4 010 = GPIO Pin N takes alternate function 5
The alternative functions are defined in the BCM datasheet under "Alternative Function" section for each pin.
This information is also valid for:
Linux::GPIO_RPI::set_gpio_mode_in
Linux::GPIO_RPI::set_gpio_mode_out
Parameters
pin
Creates a mask to enable the alternative function based in the following logic:
Alternative Function 3 bits value
Function 0 0b100
Function 1 0b101
Function 2 0b110
Function 3 0b111
Function 4 0b011
Function 5 0b010
Definition at line 40 of file GPIO_RPI.cpp.
Referenced by pinMode().
set_gpio_mode_in()
void GPIO_RPI::set_gpio_mode_in (int pin) private
Set a specific GPIO as input Check Linux::GPIO_RPI::set_gpio_mode_alt for more information.
Parameters
pin
Definition at line 68 of file GPIO_RPI.cpp.
Referenced by pinMode(), and pinMode().
set_gpio_mode_out()
void GPIO_RPI::set_gpio_mode_out (int pin) private
Set a specific GPIO as output Check Linux::GPIO_RPI::set_gpio_mode_alt for more information.
Parameters
pin
Definition at line 81 of file GPIO_RPI.cpp.
Referenced by pinMode(), and pinMode().
toggle()
void GPIO_RPI::toggle (uint8_t pin) override virtual
Implements AP_HAL::GPIO.
Definition at line 234 of file GPIO_RPI.cpp.
usb_connected()
bool GPIO_RPI::usb_connected (void) override virtual
Implements AP_HAL::GPIO.
Definition at line 250 of file GPIO_RPI.cpp.
write()
void GPIO_RPI::write (uint8_t pin, uint8_t value) override virtual
Implements AP_HAL::GPIO.
Definition at line 225 of file GPIO_RPI.cpp.
Referenced by toggle(), and GPIO_Navigator::write().
Member Data Documentation
_gpio
volatile uint32_t* Linux::GPIO_RPI::_gpio private
Definition at line 187 of file GPIO_RPI.h.
Referenced by get_gpio_logic_state(), init(), set_gpio_high(), set_gpio_low(), set_gpio_mode_alt(), set_gpio_mode_in(), and set_gpio_mode_out().
_gpio_output_port_status
uint32_t Linux::GPIO_RPI::_gpio_output_port_status = 0x00 private
Definition at line 196 of file GPIO_RPI.h.
Referenced by toggle().
_gpio_registers_memory_range
const uint8_t GPIO_RPI::_gpio_registers_memory_range = 0xB4 static private
Definition at line 189 of file GPIO_RPI.h.
Referenced by init().
_system_memory_device
int Linux::GPIO_RPI::_system_memory_device private
Definition at line 194 of file GPIO_RPI.h.
Referenced by closeMemoryDevice(), get_memory_pointer(), and openMemoryDevice().
_system_memory_device_path
const char * GPIO_RPI::_system_memory_device_path = "/dev/mem" static private
Definition at line 191 of file GPIO_RPI.h.
Referenced by openMemoryDevice().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/GPIO_RPI.h
libraries/AP_HAL_Linux/GPIO_RPI.cpp