APM:Libraries: NotchFilter< T > Class Template Reference
NotchFilter< T > Class Template Reference
#include <NotchFilter.h>
Public Member Functions
void init (float sample_freq_hz, float center_freq_hz, float bandwidth_hz, float attenuation_dB)
void init_with_A_and_Q (float sample_freq_hz, float center_freq_hz, float A, float Q)
T apply (const T &sample)
void reset ()
float center_freq_hz () const
float sample_freq_hz () const
Static Public Member Functions
static void calculate_A_and_Q (float center_freq_hz, float bandwidth_hz, float attenuation_dB, float &A, float &Q)
Protected Attributes
bool initialised
bool need_reset
float b0
float b1
float b2
float a1
float a2
float _center_freq_hz
float _sample_freq_hz
T ntchsig1
T ntchsig2
T signal2
T signal1
Friends
class HarmonicNotchFilter< T >
Detailed Description
template<class T>
class NotchFilter< T >
Definition at line 33 of file NotchFilter.h.
Member Function Documentation
apply()
template<class T > T NotchFilter< T >::apply (const T & sample)
Definition at line 105 of file NotchFilter.cpp.
Referenced by AP_InertialSensor_Backend::apply_gyro_filters(), apply_to_filter_under_test(), TEST(), and TEST().
calculate_A_and_Q()
template<class T > void NotchFilter< T >::calculate_A_and_Q (float center_freq_hz, float bandwidth_hz, float attenuation_dB, float & A, float & Q) static
Definition at line 31 of file NotchFilter.cpp.
Referenced by HarmonicNotchFilter< T >::init().
center_freq_hz()
template<class T > float NotchFilter< T >::center_freq_hz () const inline
Definition at line 41 of file NotchFilter.h.
Referenced by AP_InertialSensor::init().
init()
template<class T > void NotchFilter< T >::init (float sample_freq_hz, float center_freq_hz, float bandwidth_hz, float attenuation_dB)
Definition at line 45 of file NotchFilter.cpp.
Referenced by AP_InertialSensor::init(), setup(), TEST(), and TEST().
init_with_A_and_Q()
template<class T > void NotchFilter< T >::init_with_A_and_Q (float sample_freq_hz, float center_freq_hz, float A, float Q)
Definition at line 59 of file NotchFilter.cpp.
reset()
template<class T > void NotchFilter< T >::reset ()
Definition at line 129 of file NotchFilter.cpp.
Referenced by AP_InertialSensor_Backend::apply_gyro_filters(), reset_all(), TEST(), and TEST().
sample_freq_hz()
template<class T > float NotchFilter< T >::sample_freq_hz () const inline
Definition at line 42 of file NotchFilter.h.
Friends And Related Symbol Documentation
HarmonicNotchFilter< T >
template<class T > friend class HarmonicNotchFilter< T > friend
Definition at line 75 of file NotchFilter.h.
Member Data Documentation
_center_freq_hz
template<class T > float NotchFilter< T >::_center_freq_hz protected
Definition at line 51 of file NotchFilter.h.
Referenced by NotchFilter< T >::center_freq_hz(), and NotchHelper::print_transfer_function().
_sample_freq_hz
template<class T > float NotchFilter< T >::_sample_freq_hz protected
Definition at line 51 of file NotchFilter.h.
Referenced by NotchHelper::print_transfer_function(), and NotchFilter< T >::sample_freq_hz().
a1
template<class T > float NotchFilter< T >::a1 protected
Definition at line 50 of file NotchFilter.h.
Referenced by NotchHelper::print_transfer_function().
a2
template<class T > float NotchFilter< T >::a2 protected
Definition at line 50 of file NotchFilter.h.
Referenced by NotchHelper::print_transfer_function().
b0
template<class T > float NotchFilter< T >::b0 protected
Definition at line 50 of file NotchFilter.h.
Referenced by NotchHelper::print_transfer_function().
b1
template<class T > float NotchFilter< T >::b1 protected
Definition at line 50 of file NotchFilter.h.
Referenced by NotchHelper::print_transfer_function().
b2
template<class T > float NotchFilter< T >::b2 protected
Definition at line 50 of file NotchFilter.h.
Referenced by NotchHelper::print_transfer_function().
initialised
template<class T > bool NotchFilter< T >::initialised protected
Definition at line 49 of file NotchFilter.h.
need_reset
template<class T > bool NotchFilter< T >::need_reset protected
Definition at line 49 of file NotchFilter.h.
ntchsig1
template<class T > T NotchFilter< T >::ntchsig1 protected
Definition at line 52 of file NotchFilter.h.
ntchsig2
template<class T > T NotchFilter< T >::ntchsig2 protected
Definition at line 52 of file NotchFilter.h.
signal1
template<class T > T NotchFilter< T >::signal1 protected
Definition at line 52 of file NotchFilter.h.
signal2
template<class T > T NotchFilter< T >::signal2 protected
Definition at line 52 of file NotchFilter.h.
The documentation for this class was generated from the following files:
libraries/Filter/NotchFilter.h
libraries/Filter/NotchFilter.cpp