APM:Libraries: libraries/AP_Math/control.h File Reference
control.h File Reference
#include <AP_HAL/AP_HAL_Boards.h>
#include "vector2.h"
#include "vector3.h"
Macros
#define HAL_WITH_POSTYPE_DOUBLE BOARD_FLASH_SIZE > 1024
#define topostype tofloat
Typedefs
typedef float postype_t
typedef Vector2f Vector2p
typedef Vector3f Vector3p
Functions
void update_vel_accel (float &vel, float accel, float dt, float limit, float vel_error)
void update_pos_vel_accel (postype_t &pos, float &vel, float accel, float dt, float limit, float pos_error, float vel_error)
void update_vel_accel_xy (Vector2f &vel, const Vector2f &accel, float dt, const Vector2f &limit, const Vector2f &vel_error)
void update_pos_vel_accel_xy (Vector2p &pos, Vector2f &vel, const Vector2f &accel, float dt, const Vector2f &limit, const Vector2f &pos_error, const Vector2f &vel_error)
void shape_accel (float accel_input, float &accel, float jerk_max, float dt)
void shape_accel_xy (const Vector2f &accel_input, Vector2f &accel, float jerk_max, float dt)
void shape_accel_xy (const Vector3f &accel_input, Vector3f &accel, float jerk_max, float dt)
void shape_vel_accel (float vel_input, float accel_input, float vel, float &accel, float accel_min, float accel_max, float jerk_max, float dt, bool limit_total_accel)
void shape_vel_accel_xy (const Vector2f &vel_input1, const Vector2f &accel_input, const Vector2f &vel, Vector2f &accel, float accel_max, float jerk_max, float dt, bool limit_total_accel)
void shape_pos_vel_accel (const postype_t pos_input, float vel_input, float accel_input, const postype_t pos, float vel, float &accel, float vel_min, float vel_max, float accel_min, float accel_max, float jerk_max, float dt, bool limit_total)
void shape_pos_vel_accel_xy (const Vector2p &pos_input, const Vector2f &vel_input, const Vector2f &accel_input, const Vector2p &pos, const Vector2f &vel, Vector2f &accel, float vel_max, float accel_max, float jerk_max, float dt, bool limit_total)
bool limit_accel_xy (const Vector2f &vel, Vector2f &accel, float accel_max)
float sqrt_controller (float error, float p, float second_ord_lim, float dt)
Vector2f sqrt_controller (const Vector2f &error, float p, float second_ord_lim, float dt)
float inv_sqrt_controller (float output, float p, float D_max)
float stopping_distance (float velocity, float p, float accel_max)
float kinematic_limit (Vector3f direction, float max_xy, float max_z_pos, float max_z_neg)
float input_expo (float input, float expo)
float angle_to_accel (float angle_deg)
float accel_to_angle (float accel)
void rc_input_to_roll_pitch (float roll_in_unit, float pitch_in_unit, float angle_max_deg, float angle_limit_deg, float &roll_out_deg, float &pitch_out_deg)
Macro Definition Documentation
HAL_WITH_POSTYPE_DOUBLE
#define HAL_WITH_POSTYPE_DOUBLE BOARD_FLASH_SIZE > 1024
Definition at line 8 of file control.h.
topostype
#define topostype tofloat
Definition at line 20 of file control.h.
Referenced by AC_Loiter::calc_desired_velocity(), AC_PosControl::get_stopping_point_xy_cm(), AC_PosControl::handle_ekf_xy_reset(), and AR_PosControl::handle_ekf_xy_reset().
Typedef Documentation
postype_t
typedef float postype_t
Definition at line 17 of file control.h.
Vector2p
typedef Vector2f Vector2p
Definition at line 18 of file control.h.
Vector3p
typedef Vector3f Vector3p
Definition at line 19 of file control.h.
Function Documentation
accel_to_angle()
float accel_to_angle (float accel)
Definition at line 536 of file control.cpp.
Referenced by AC_PosControl::accel_to_lean_angles(), AC_Autorotation::update_forward_speed_controller(), and AC_PosControl::update_xy_controller().
angle_to_accel()
float angle_to_accel (float angle_deg)
Definition at line 530 of file control.cpp.
Referenced by AC_Loiter::calc_desired_velocity(), AC_PosControl::init_xy_controller(), and AC_PosControl::update_xy_controller().
input_expo()
float input_expo (float input, float expo)
Definition at line 520 of file control.cpp.
inv_sqrt_controller()
float inv_sqrt_controller (float output, float p, float D_max)
Definition at line 449 of file control.cpp.
Referenced by AC_P_2D::set_limits(), AC_P_1D::set_limits(), stopping_distance(), TEST(), and AC_AttitudeControl::thrust_heading_rotation_angles().
kinematic_limit()
float kinematic_limit (Vector3f direction, float max_xy, float max_z_pos, float max_z_neg)
Definition at line 482 of file control.cpp.
Referenced by SplineCurve::calc_dt_speed_max(), AC_PosControl::input_pos_xyz(), SCurve::set_kinematic_limits(), and SCurve::set_speed_max().
limit_accel_xy()
bool limit_accel_xy (const Vector2f & vel, Vector2f & accel, float accel_max)
Definition at line 369 of file control.cpp.
Referenced by AC_PosControl::update_xy_controller().
rc_input_to_roll_pitch()
void rc_input_to_roll_pitch (float roll_in_unit, float pitch_in_unit, float angle_max_deg, float angle_limit_deg, float & roll_out_deg, float & pitch_out_deg)
Definition at line 546 of file control.cpp.
Referenced by TEST(), TEST(), and TEST().
shape_accel()
void shape_accel (float accel_input, float & accel, float jerk_max, float dt)
Definition at line 111 of file control.cpp.
Referenced by AC_PosControl::input_accel_z(), and shape_vel_accel().
shape_accel_xy() [1/2]
void shape_accel_xy (const Vector2f & accel_input, Vector2f & accel, float jerk_max, float dt)
Definition at line 129 of file control.cpp.
Referenced by AC_PosControl::input_accel_xy(), shape_accel_xy(), and shape_vel_accel_xy().
shape_accel_xy() [2/2]
void shape_accel_xy (const Vector3f & accel_input, Vector3f & accel, float jerk_max, float dt)
Definition at line 146 of file control.cpp.
shape_pos_vel_accel()
void shape_pos_vel_accel (const postype_t pos_input, float vel_input, float accel_input, const postype_t pos, float vel, float & accel, float vel_min, float vel_max, float accel_min, float accel_max, float jerk_max, float dt, bool limit_total)
Definition at line 275 of file control.cpp.
Referenced by AC_PosControl::input_pos_vel_accel_z(), AC_PosControl::input_pos_xyz(), and AC_PosControl::update_pos_offset_z().
shape_pos_vel_accel_xy()
void shape_pos_vel_accel_xy (const Vector2p & pos_input, const Vector2f & vel_input, const Vector2f & accel_input, const Vector2p & pos, const Vector2f & vel, Vector2f & accel, float vel_max, float accel_max, float jerk_max, float dt, bool limit_total)
Definition at line 324 of file control.cpp.
Referenced by AR_PosControl::input_pos_vel_accel_target(), AC_PosControl::input_pos_vel_accel_xy(), and AC_PosControl::input_pos_xyz().
shape_vel_accel()
void shape_vel_accel (float vel_input, float accel_input, float vel, float & accel, float accel_min, float accel_max, float jerk_max, float dt, bool limit_total_accel)
Definition at line 166 of file control.cpp.
Referenced by AC_WPNav::advance_wp_target_along_track(), AC_PosControl::input_vel_accel_z(), and shape_pos_vel_accel().
shape_vel_accel_xy()
void shape_vel_accel_xy (const Vector2f & vel_input1, const Vector2f & accel_input, const Vector2f & vel, Vector2f & accel, float accel_max, float jerk_max, float dt, bool limit_total_accel)
Definition at line 209 of file control.cpp.
Referenced by AC_PosControl::input_vel_accel_xy(), and shape_pos_vel_accel_xy().
sqrt_controller() [1/2]
Vector2f sqrt_controller (const Vector2f & error, float p, float second_ord_lim, float dt)
Definition at line 436 of file control.cpp.
sqrt_controller() [2/2]
float sqrt_controller (float error, float p, float second_ord_lim, float dt)
Definition at line 401 of file control.cpp.
Referenced by AC_Loiter::calc_desired_velocity(), AC_Avoid::get_max_speed(), AC_AttitudeControl::input_shaping_ang_vel(), AC_AttitudeControl::input_shaping_angle(), shape_pos_vel_accel(), shape_pos_vel_accel_xy(), shape_vel_accel(), shape_vel_accel_xy(), sqrt_controller(), TEST(), TEST(), AC_P_1D::update_all(), AC_P_2D::update_all(), and AC_AttitudeControl::update_ang_vel_target_from_att_error().
stopping_distance()
float stopping_distance (float velocity, float p, float accel_max)
Definition at line 475 of file control.cpp.
Referenced by AC_PosControl::get_stopping_point_xy_cm(), and AC_PosControl::get_stopping_point_z_cm().
update_pos_vel_accel()
void update_pos_vel_accel (postype_t & pos, float & vel, float accel, float dt, float limit, float pos_error, float vel_error)
Definition at line 53 of file control.cpp.
Referenced by AC_PosControl::input_accel_z(), AC_PosControl::input_pos_vel_accel_z(), AC_PosControl::input_pos_xyz(), AC_PosControl::input_vel_accel_z(), TEST(), and AC_PosControl::update_pos_offset_z().
update_pos_vel_accel_xy()
void update_pos_vel_accel_xy (Vector2p & pos, Vector2f & vel, const Vector2f & accel, float dt, const Vector2f & limit, const Vector2f & pos_error, const Vector2f & vel_error)
Definition at line 88 of file control.cpp.
Referenced by AC_PosControl::input_accel_xy(), AR_PosControl::input_pos_vel_accel_target(), AC_PosControl::input_pos_vel_accel_xy(), AC_PosControl::input_pos_xyz(), AC_PosControl::input_vel_accel_xy(), and TEST().
update_vel_accel()
void update_vel_accel (float & vel, float accel, float dt, float limit, float vel_error)
Definition at line 34 of file control.cpp.
Referenced by AC_WPNav::advance_wp_target_along_track(), AC_PosControl::input_vel_accel_z(), and update_pos_vel_accel().
update_vel_accel_xy()
void update_vel_accel_xy (Vector2f & vel, const Vector2f & accel, float dt, const Vector2f & limit, const Vector2f & vel_error)
Definition at line 70 of file control.cpp.
Referenced by AC_PosControl::input_vel_accel_xy(), and update_pos_vel_accel_xy().