APM:Libraries: libraries/AP_Math/crc.h File Reference
crc.h File Reference
#include <stdint.h>
Macros
#define FNV_1_OFFSET_BASIS_64 14695981039346656037UL
Functions
uint16_t crc_crc4 (uint16_t *data)
uint8_t crc_crc8 (const uint8_t *p, uint8_t len)
uint8_t crc8_generic (const uint8_t *buf, const uint16_t buf_len, const uint8_t polynomial)
uint8_t crc8_dvb_s2 (uint8_t crc, uint8_t a)
uint8_t crc8_dvb (uint8_t crc, uint8_t a, uint8_t seed)
uint8_t crc8_dvb_s2_update (uint8_t crc, const void *data, uint32_t length)
uint8_t crc8_dvb_update (uint8_t crc, const uint8_t *buf, const uint16_t buf_len)
uint8_t crc8_maxim (const uint8_t *data, uint16_t length)
uint8_t crc8_sae (const uint8_t *data, uint16_t length)
uint16_t crc_xmodem_update (uint16_t crc, uint8_t data)
uint16_t crc_xmodem (const uint8_t *data, uint16_t len)
uint32_t crc_crc32 (uint32_t crc, const uint8_t *buf, uint32_t size)
uint32_t crc32_small (uint32_t crc, const uint8_t *buf, uint32_t size)
uint32_t crc_crc24 (const uint8_t *bytes, uint16_t len)
uint16_t crc_crc16_ibm (uint16_t crc_accum, uint8_t *data_blk_ptr, uint16_t data_blk_size)
uint8_t crc_sum8_with_carry (const uint8_t *p, uint8_t len)
uint16_t crc16_ccitt (const uint8_t *buf, uint32_t len, uint16_t crc)
uint16_t crc16_ccitt_r (const uint8_t *buf, uint32_t len, uint16_t crc, uint16_t out)
uint16_t crc16_ccitt_GDL90 (const uint8_t *buf, uint32_t len, uint16_t crc)
uint16_t calc_crc_modbus (const uint8_t *buf, uint16_t len)
uint16_t crc_fletcher16 (const uint8_t *buffer, uint32_t len)
void hash_fnv_1a (uint32_t len, const uint8_t *buf, uint64_t *hash)
uint64_t crc_crc64 (const uint32_t *data, uint16_t num_words)
uint8_t parity (uint8_t byte)
uint8_t crc_sum_of_bytes (const uint8_t *data, uint16_t count)
uint16_t crc_sum_of_bytes_16 (const uint8_t *data, uint16_t count)
Macro Definition Documentation
FNV_1_OFFSET_BASIS_64
#define FNV_1_OFFSET_BASIS_64 14695981039346656037UL
Definition at line 57 of file crc.h.
Function Documentation
calc_crc_modbus()
uint16_t calc_crc_modbus (const uint8_t * buf, uint16_t len)
Calculate Modbus CRC16 for array of bytes
Parameters
[in] buf input buffer
[in] len size of buffer
Returns
CRC value
Definition at line 422 of file crc.cpp.
Referenced by AP_RangeFinder_LeddarOne::CRC16(), AP_RangeFinder_Lanbao::get_reading(), SITL::RF_Lanbao::packet_for_alt(), SITL::RF_LeddarOne::packet_for_alt(), AP_RangeFinder_LeddarVu8::parse_byte(), AP_RangeFinder_LeddarVu8::request_distances(), and AP_Beacon_Marvelmind::update().
crc16_ccitt()
uint16_t crc16_ccitt (const uint8_t * buf, uint32_t len, uint16_t crc)
Definition at line 379 of file crc.cpp.
Referenced by AP_GPS_SBP2::_detect(), AP_GPS_SBP::_detect(), AP_GPS_SBP::_sbp_process(), AP_GPS_SBP2::_sbp_process(), AP_GPS_SBF::parse(), AP_Mount_Siyi::read_incoming_packets(), AP_Mount_Siyi::send_packet(), SITL::VectorNav::send_packet1(), and SITL::VectorNav::send_packet2().
crc16_ccitt_GDL90()
uint16_t crc16_ccitt_GDL90 (const uint8_t * buf, uint32_t len, uint16_t crc)
Definition at line 407 of file crc.cpp.
crc16_ccitt_r()
uint16_t crc16_ccitt_r (const uint8_t * buf, uint32_t len, uint16_t crc, uint16_t out)
Definition at line 388 of file crc.cpp.
Referenced by SITL::RF_JRE::packet_for_alt().
crc32_small()
uint32_t crc32_small (uint32_t crc, const uint8_t * buf, uint32_t size)
Definition at line 318 of file crc.cpp.
Referenced by AP_IOMCU_FW::calculate_fw_crc(), and AP_ROMFS::find_decompress().
crc8_dvb()
uint8_t crc8_dvb (uint8_t crc, uint8_t a, uint8_t seed)
Definition at line 112 of file crc.cpp.
Referenced by crc8_dvb_s2(), crc8_dvb_update(), crc8_generic(), and SITL::TSYS03::rdwr_handle_read().
crc8_dvb_s2()
uint8_t crc8_dvb_s2 (uint8_t crc, uint8_t a)
Definition at line 106 of file crc.cpp.
Referenced by AP_RCProtocol_GHST::_process_byte(), crc8_dvb_s2_update(), AP_RunCam::Request::get_crc(), MSP::msp_parse_received_data(), AP_RunCam::send_packet(), AP_RCProtocol_CRSF::write_frame(), and AP_RCProtocol_GHST::write_frame().
crc8_dvb_s2_update()
uint8_t crc8_dvb_s2_update (uint8_t crc, const void * data, uint32_t length)
Definition at line 126 of file crc.cpp.
Referenced by AP_RCProtocol_CRSF::check_frame(), MSP::msp_serial_encode(), AP_SmartAudio::parse_response_buffer(), AP_SmartAudio::push_command_only_frame(), AP_SmartAudio::push_uint16_command_frame(), and AP_SmartAudio::push_uint8_command_frame().
crc8_dvb_update()
uint8_t crc8_dvb_update (uint8_t crc, const uint8_t * buf, const uint16_t buf_len)
Definition at line 138 of file crc.cpp.
Referenced by SITL::FETtecOneWireESC::PackedMessage< T >::calculate_checksum(), and SITL::FETtecOneWireESC::update_input().
crc8_generic()
uint8_t crc8_generic (const uint8_t * buf, const uint16_t buf_len, const uint8_t polynomial)
Definition at line 96 of file crc.cpp.
crc8_maxim()
uint8_t crc8_maxim (const uint8_t * data, uint16_t length)
Definition at line 185 of file crc.cpp.
crc8_sae()
uint8_t crc8_sae (const uint8_t * data, uint16_t length)
Definition at line 217 of file crc.cpp.
Referenced by AP_InertialSensor_SCHA63T::read_register(), and AP_InertialSensor_SCHA63T::write_register().
crc_crc16_ibm()
uint16_t crc_crc16_ibm (uint16_t crc_accum, uint8_t * data_blk_ptr, uint16_t data_blk_size)
Definition at line 499 of file crc.cpp.
crc_crc24()
uint32_t crc_crc24 (const uint8_t * bytes, uint16_t len)
Definition at line 464 of file crc.cpp.
Referenced by RTCM3_Parser::parse().
crc_crc32()
uint32_t crc_crc32 (uint32_t crc, const uint8_t * buf, uint32_t size)
Definition at line 308 of file crc.cpp.
Referenced by AP_GPS_NMEA::_decode(), AP_Filesystem::crc32(), CRC32_MS(), AP_Networking::init(), AP_RAMTRON::read(), and AP_RAMTRON::write().
crc_crc4()
uint16_t crc_crc4 (uint16_t * data)
crc4 method from datasheet for 16 bytes (8 short values)
Parameters
[in] data
Returns
crc4
Definition at line 30 of file crc.cpp.
Referenced by AP_Baro_MS56XX::_read_prom_5611(), AP_Baro_MS56XX::_read_prom_5637(), and AP_Airspeed_MS5525::crc4_prom().
crc_crc64()
uint64_t crc_crc64 (const uint32_t * data, uint16_t num_words)
Definition at line 552 of file crc.cpp.
crc_crc8()
uint8_t crc_crc8 (const uint8_t * p, uint8_t len)
Definition at line 83 of file crc.cpp.
Referenced by AP_RangeFinder_TeraRangerI2C::collect_raw(), AP_RangeFinder_TeraRanger_Serial::get_reading(), AP_IOMCU_FW::handle_code_read(), AP_IOMCU_FW::handle_code_write(), SITL::RF_TeraRanger_Serial::packet_for_alt(), AP_IOMCU_FW::process_io_packet(), and SITL::PS_TeraRangerTower::update_output().
crc_fletcher16()
uint16_t crc_fletcher16 (const uint8_t * buffer, uint32_t len)
Definition at line 441 of file crc.cpp.
crc_sum8_with_carry()
uint8_t crc_sum8_with_carry (const uint8_t * p, uint8_t len)
Definition at line 484 of file crc.cpp.
Referenced by AP_RCProtocol_FPort::check_checksum(), and AP_RCProtocol_FPort::decode_downlink().
crc_sum_of_bytes()
uint8_t crc_sum_of_bytes (const uint8_t * data, uint16_t count)
Definition at line 614 of file crc.cpp.
Referenced by SITL::EFI_Hirth::PackedRecord< T >::update_checksum(), and SITL::EFI_Hirth::update_receive().
crc_sum_of_bytes_16()
uint16_t crc_sum_of_bytes_16 (const uint8_t * data, uint16_t count)
Definition at line 603 of file crc.cpp.
Referenced by crc_sum_of_bytes(), and SITL::InertialLabs::send_packet().
crc_xmodem()
uint16_t crc_xmodem (const uint8_t * data, uint16_t len)
Definition at line 249 of file crc.cpp.
crc_xmodem_update()
uint16_t crc_xmodem_update (uint16_t crc, uint8_t data)
Definition at line 234 of file crc.cpp.
Referenced by AP_RCProtocol_SRXL::_process_byte(), AP_RCProtocol_SUMD::_process_byte(), SITL::PS_LightWare_SF45B::PackedMessage< T >::calculate_checksum(), SITL::PS_LightWare_SF45B::checksum_bytes(), crc_xmodem(), srxl_decode(), and sumd_decode().
hash_fnv_1a()
void hash_fnv_1a (uint32_t len, const uint8_t * buf, uint64_t * hash)
Definition at line 454 of file crc.cpp.
parity()
uint8_t parity (uint8_t byte)
Definition at line 579 of file crc.cpp.
Referenced by ESP32::UARTDriver::_begin(), Linux::RCInput::_process_sbus_pulse(), RTCM3_Parser::parse(), SoftSerial::process_pulse(), send_byte(), and TEST().