APM:Libraries: libraries/AP_Math/crc.cpp File Reference
crc.cpp File Reference
#include <stdint.h>
#include "crc.h"
#include <AP_HAL/AP_HAL_Boards.h>
Macros
#define FNV_1_PRIME_64 1099511628211UL
Functions
uint16_t crc_crc4 (uint16_t *data)
uint8_t crc_crc8 (const uint8_t *p, uint8_t len)
uint8_t crc8_generic (const uint8_t *buf, const uint16_t buf_len, const uint8_t polynomial)
uint8_t crc8_dvb_s2 (uint8_t crc, uint8_t a)
uint8_t crc8_dvb (uint8_t crc, uint8_t a, uint8_t seed)
uint8_t crc8_dvb_s2_update (uint8_t crc, const void *data, uint32_t length)
uint8_t crc8_dvb_update (uint8_t crc, const uint8_t *buf, const uint16_t buf_len)
uint8_t crc8_maxim (const uint8_t *data, uint16_t length)
uint8_t crc8_sae (const uint8_t *data, uint16_t length)
uint16_t crc_xmodem_update (uint16_t crc, uint8_t data)
uint16_t crc_xmodem (const uint8_t *data, uint16_t len)
uint32_t crc_crc32 (uint32_t crc, const uint8_t *buf, uint32_t size)
uint32_t crc32_small (uint32_t crc, const uint8_t *buf, uint32_t size)
uint16_t crc16_ccitt (const uint8_t *buf, uint32_t len, uint16_t crc)
uint16_t crc16_ccitt_r (const uint8_t *buf, uint32_t len, uint16_t crc, uint16_t out)
uint16_t crc16_ccitt_GDL90 (const uint8_t *buf, uint32_t len, uint16_t crc)
uint16_t calc_crc_modbus (const uint8_t *buf, uint16_t len)
uint16_t crc_fletcher16 (const uint8_t *buffer, uint32_t len)
void hash_fnv_1a (uint32_t len, const uint8_t *buf, uint64_t *hash)
uint32_t crc_crc24 (const uint8_t *bytes, uint16_t len)
uint8_t crc_sum8_with_carry (const uint8_t *p, uint8_t len)
uint16_t crc_crc16_ibm (uint16_t crc_accum, uint8_t *data_blk_ptr, uint16_t data_blk_size)
uint64_t crc_crc64 (const uint32_t *data, uint16_t num_words)
uint8_t parity (uint8_t byte)
uint16_t crc_sum_of_bytes_16 (const uint8_t *data, uint16_t count)
uint8_t crc_sum_of_bytes (const uint8_t *data, uint16_t count)
Variables
static const uint8_t crc8_table []
static const uint8_t crc8_table_maxim []
static const uint8_t crc8_table_sae [256]
static const uint32_t crc32_tab []
static const uint16_t crc16tab [256]
Macro Definition Documentation
FNV_1_PRIME_64
#define FNV_1_PRIME_64 1099511628211UL
Definition at line 453 of file crc.cpp.
Referenced by hash_fnv_1a().
Function Documentation
calc_crc_modbus()
uint16_t calc_crc_modbus (const uint8_t * buf, uint16_t len)
Calculate Modbus CRC16 for array of bytes
Parameters
[in] buf input buffer
[in] len size of buffer
Returns
CRC value
Definition at line 422 of file crc.cpp.
Referenced by AP_RangeFinder_LeddarOne::CRC16(), AP_RangeFinder_Lanbao::get_reading(), SITL::RF_Lanbao::packet_for_alt(), SITL::RF_LeddarOne::packet_for_alt(), AP_RangeFinder_LeddarVu8::parse_byte(), AP_RangeFinder_LeddarVu8::request_distances(), and AP_Beacon_Marvelmind::update().
crc16_ccitt()
uint16_t crc16_ccitt (const uint8_t * buf, uint32_t len, uint16_t crc)
Definition at line 379 of file crc.cpp.
Referenced by AP_GPS_SBP2::_detect(), AP_GPS_SBP::_detect(), AP_GPS_SBP::_sbp_process(), AP_GPS_SBP2::_sbp_process(), AP_GPS_SBF::parse(), AP_Mount_Siyi::read_incoming_packets(), AP_Mount_Siyi::send_packet(), SITL::VectorNav::send_packet1(), and SITL::VectorNav::send_packet2().
crc16_ccitt_GDL90()
uint16_t crc16_ccitt_GDL90 (const uint8_t * buf, uint32_t len, uint16_t crc)
Definition at line 407 of file crc.cpp.
crc16_ccitt_r()
uint16_t crc16_ccitt_r (const uint8_t * buf, uint32_t len, uint16_t crc, uint16_t out)
Definition at line 388 of file crc.cpp.
Referenced by SITL::RF_JRE::packet_for_alt().
crc32_small()
uint32_t crc32_small (uint32_t crc, const uint8_t * buf, uint32_t size)
Definition at line 318 of file crc.cpp.
Referenced by AP_IOMCU_FW::calculate_fw_crc(), and AP_ROMFS::find_decompress().
crc8_dvb()
uint8_t crc8_dvb (uint8_t crc, uint8_t a, uint8_t seed)
Definition at line 112 of file crc.cpp.
Referenced by crc8_dvb_s2(), crc8_dvb_update(), crc8_generic(), and SITL::TSYS03::rdwr_handle_read().
crc8_dvb_s2()
uint8_t crc8_dvb_s2 (uint8_t crc, uint8_t a)
Definition at line 106 of file crc.cpp.
Referenced by AP_RCProtocol_GHST::_process_byte(), crc8_dvb_s2_update(), AP_RunCam::Request::get_crc(), MSP::msp_parse_received_data(), AP_RunCam::send_packet(), AP_RCProtocol_CRSF::write_frame(), and AP_RCProtocol_GHST::write_frame().
crc8_dvb_s2_update()
uint8_t crc8_dvb_s2_update (uint8_t crc, const void * data, uint32_t length)
Definition at line 126 of file crc.cpp.
Referenced by AP_RCProtocol_CRSF::check_frame(), MSP::msp_serial_encode(), AP_SmartAudio::parse_response_buffer(), AP_SmartAudio::push_command_only_frame(), AP_SmartAudio::push_uint16_command_frame(), and AP_SmartAudio::push_uint8_command_frame().
crc8_dvb_update()
uint8_t crc8_dvb_update (uint8_t crc, const uint8_t * buf, const uint16_t buf_len)
Definition at line 138 of file crc.cpp.
Referenced by SITL::FETtecOneWireESC::PackedMessage< T >::calculate_checksum(), and SITL::FETtecOneWireESC::update_input().
crc8_generic()
uint8_t crc8_generic (const uint8_t * buf, const uint16_t buf_len, const uint8_t polynomial)
Definition at line 96 of file crc.cpp.
crc8_maxim()
uint8_t crc8_maxim (const uint8_t * data, uint16_t length)
Definition at line 185 of file crc.cpp.
crc8_sae()
uint8_t crc8_sae (const uint8_t * data, uint16_t length)
Definition at line 217 of file crc.cpp.
Referenced by AP_InertialSensor_SCHA63T::read_register(), and AP_InertialSensor_SCHA63T::write_register().
crc_crc16_ibm()
uint16_t crc_crc16_ibm (uint16_t crc_accum, uint8_t * data_blk_ptr, uint16_t data_blk_size)
Definition at line 499 of file crc.cpp.
crc_crc24()
uint32_t crc_crc24 (const uint8_t * bytes, uint16_t len)
Definition at line 464 of file crc.cpp.
Referenced by RTCM3_Parser::parse().
crc_crc32()
uint32_t crc_crc32 (uint32_t crc, const uint8_t * buf, uint32_t size)
Definition at line 308 of file crc.cpp.
Referenced by AP_GPS_NMEA::_decode(), AP_Filesystem::crc32(), CRC32_MS(), AP_Networking::init(), AP_RAMTRON::read(), and AP_RAMTRON::write().
crc_crc4()
uint16_t crc_crc4 (uint16_t * data)
crc4 method from datasheet for 16 bytes (8 short values)
Parameters
[in] data
Returns
crc4
Definition at line 30 of file crc.cpp.
Referenced by AP_Baro_MS56XX::_read_prom_5611(), AP_Baro_MS56XX::_read_prom_5637(), and AP_Airspeed_MS5525::crc4_prom().
crc_crc64()
uint64_t crc_crc64 (const uint32_t * data, uint16_t num_words)
Definition at line 552 of file crc.cpp.
crc_crc8()
uint8_t crc_crc8 (const uint8_t * p, uint8_t len)
Definition at line 83 of file crc.cpp.
Referenced by AP_RangeFinder_TeraRangerI2C::collect_raw(), AP_RangeFinder_TeraRanger_Serial::get_reading(), AP_IOMCU_FW::handle_code_read(), AP_IOMCU_FW::handle_code_write(), SITL::RF_TeraRanger_Serial::packet_for_alt(), AP_IOMCU_FW::process_io_packet(), and SITL::PS_TeraRangerTower::update_output().
crc_fletcher16()
uint16_t crc_fletcher16 (const uint8_t * buffer, uint32_t len)
Definition at line 441 of file crc.cpp.
crc_sum8_with_carry()
uint8_t crc_sum8_with_carry (const uint8_t * p, uint8_t len)
Definition at line 484 of file crc.cpp.
Referenced by AP_RCProtocol_FPort::check_checksum(), and AP_RCProtocol_FPort::decode_downlink().
crc_sum_of_bytes()
uint8_t crc_sum_of_bytes (const uint8_t * data, uint16_t count)
Definition at line 614 of file crc.cpp.
Referenced by SITL::EFI_Hirth::PackedRecord< T >::update_checksum(), and SITL::EFI_Hirth::update_receive().
crc_sum_of_bytes_16()
uint16_t crc_sum_of_bytes_16 (const uint8_t * data, uint16_t count)
Definition at line 603 of file crc.cpp.
Referenced by crc_sum_of_bytes(), and SITL::InertialLabs::send_packet().
crc_xmodem()
uint16_t crc_xmodem (const uint8_t * data, uint16_t len)
Definition at line 249 of file crc.cpp.
crc_xmodem_update()
uint16_t crc_xmodem_update (uint16_t crc, uint8_t data)
Definition at line 234 of file crc.cpp.
Referenced by AP_RCProtocol_SRXL::_process_byte(), AP_RCProtocol_SUMD::_process_byte(), SITL::PS_LightWare_SF45B::PackedMessage< T >::calculate_checksum(), SITL::PS_LightWare_SF45B::checksum_bytes(), crc_xmodem(), srxl_decode(), and sumd_decode().
hash_fnv_1a()
void hash_fnv_1a (uint32_t len, const uint8_t * buf, uint64_t * hash)
Definition at line 454 of file crc.cpp.
parity()
uint8_t parity (uint8_t byte)
Definition at line 579 of file crc.cpp.
Referenced by ESP32::UARTDriver::_begin(), Linux::RCInput::_process_sbus_pulse(), RTCM3_Parser::parse(), SoftSerial::process_pulse(), send_byte(), and TEST().
Variable Documentation
crc16tab
const uint16_t crc16tab[256] static
Definition at line 344 of file crc.cpp.
Referenced by crc16_ccitt(), and crc16_ccitt_GDL90().
crc32_tab
const uint32_t crc32_tab[] static
Definition at line 261 of file crc.cpp.
Referenced by crc_crc32().
crc8_table
const uint8_t crc8_table[] static
Initial value:
= {
    0x00, 0x07, 0x0e, 0x09, 0x1c, 0x1b, 0x12, 0x15, 0x38, 0x3f, 0x36, 0x31,
    0x24, 0x23, 0x2a, 0x2d, 0x70, 0x77, 0x7e, 0x79, 0x6c, 0x6b, 0x62, 0x65,
    0x48, 0x4f, 0x46, 0x41, 0x54, 0x53, 0x5a, 0x5d, 0xe0, 0xe7, 0xee, 0xe9,
    0xfc, 0xfb, 0xf2, 0xf5, 0xd8, 0xdf, 0xd6, 0xd1, 0xc4, 0xc3, 0xca, 0xcd,
    0x90, 0x97, 0x9e, 0x99, 0x8c, 0x8b, 0x82, 0x85, 0xa8, 0xaf, 0xa6, 0xa1,
    0xb4, 0xb3, 0xba, 0xbd, 0xc7, 0xc0, 0xc9, 0xce, 0xdb, 0xdc, 0xd5, 0xd2,
    0xff, 0xf8, 0xf1, 0xf6, 0xe3, 0xe4, 0xed, 0xea, 0xb7, 0xb0, 0xb9, 0xbe,
    0xab, 0xac, 0xa5, 0xa2, 0x8f, 0x88, 0x81, 0x86, 0x93, 0x94, 0x9d, 0x9a,
    0x27, 0x20, 0x29, 0x2e, 0x3b, 0x3c, 0x35, 0x32, 0x1f, 0x18, 0x11, 0x16,
    0x03, 0x04, 0x0d, 0x0a, 0x57, 0x50, 0x59, 0x5e, 0x4b, 0x4c, 0x45, 0x42,
    0x6f, 0x68, 0x61, 0x66, 0x73, 0x74, 0x7d, 0x7a, 0x89, 0x8e, 0x87, 0x80,
    0x95, 0x92, 0x9b, 0x9c, 0xb1, 0xb6, 0xbf, 0xb8, 0xad, 0xaa, 0xa3, 0xa4,
    0xf9, 0xfe, 0xf7, 0xf0, 0xe5, 0xe2, 0xeb, 0xec, 0xc1, 0xc6, 0xcf, 0xc8,
    0xdd, 0xda, 0xd3, 0xd4, 0x69, 0x6e, 0x67, 0x60, 0x75, 0x72, 0x7b, 0x7c,
    0x51, 0x56, 0x5f, 0x58, 0x4d, 0x4a, 0x43, 0x44, 0x19, 0x1e, 0x17, 0x10,
    0x05, 0x02, 0x0b, 0x0c, 0x21, 0x26, 0x2f, 0x28, 0x3d, 0x3a, 0x33, 0x34,
    0x4e, 0x49, 0x40, 0x47, 0x52, 0x55, 0x5c, 0x5b, 0x76, 0x71, 0x78, 0x7f,
    0x6a, 0x6d, 0x64, 0x63, 0x3e, 0x39, 0x30, 0x37, 0x22, 0x25, 0x2c, 0x2b,
    0x06, 0x01, 0x08, 0x0f, 0x1a, 0x1d, 0x14, 0x13, 0xae, 0xa9, 0xa0, 0xa7,
    0xb2, 0xb5, 0xbc, 0xbb, 0x96, 0x91, 0x98, 0x9f, 0x8a, 0x8d, 0x84, 0x83,
    0xde, 0xd9, 0xd0, 0xd7, 0xc2, 0xc5, 0xcc, 0xcb, 0xe6, 0xe1, 0xe8, 0xef,
    0xfa, 0xfd, 0xf4, 0xf3
}
Definition at line 55 of file crc.cpp.
Referenced by crc_crc8().
crc8_table_maxim
const uint8_t crc8_table_maxim[] static
Definition at line 150 of file crc.cpp.
Referenced by crc8_maxim().
crc8_table_sae
const uint8_t crc8_table_sae[256] static
Initial value:
= {
    0x00, 0x1D, 0x3A, 0x27, 0x74, 0x69, 0x4E, 0x53, 0xE8, 0xF5, 0xD2, 0xCF, 0x9C, 0x81, 0xA6, 0xBB,
    0xCD, 0xD0, 0xF7, 0xEA, 0xB9, 0xA4, 0x83, 0x9E, 0x25, 0x38, 0x1F, 0x02, 0x51, 0x4C, 0x6B, 0x76,
    0x87, 0x9A, 0xBD, 0xA0, 0xF3, 0xEE, 0xC9, 0xD4, 0x6F, 0x72, 0x55, 0x48, 0x1B, 0x06, 0x21, 0x3C,
    0x4A, 0x57, 0x70, 0x6D, 0x3E, 0x23, 0x04, 0x19, 0xA2, 0xBF, 0x98, 0x85, 0xD6, 0xCB, 0xEC, 0xF1,
    0x13, 0x0E, 0x29, 0x34, 0x67, 0x7A, 0x5D, 0x40, 0xFB, 0xE6, 0xC1, 0xDC, 0x8F, 0x92, 0xB5, 0xA8,
    0xDE, 0xC3, 0xE4, 0xF9, 0xAA, 0xB7, 0x90, 0x8D, 0x36, 0x2B, 0x0C, 0x11, 0x42, 0x5F, 0x78, 0x65,
    0x94, 0x89, 0xAE, 0xB3, 0xE0, 0xFD, 0xDA, 0xC7, 0x7C, 0x61, 0x46, 0x5B, 0x08, 0x15, 0x32, 0x2F,
    0x59, 0x44, 0x63, 0x7E, 0x2D, 0x30, 0x17, 0x0A, 0xB1, 0xAC, 0x8B, 0x96, 0xC5, 0xD8, 0xFF, 0xE2,
    0x26, 0x3B, 0x1C, 0x01, 0x52, 0x4F, 0x68, 0x75, 0xCE, 0xD3, 0xF4, 0xE9, 0xBA, 0xA7, 0x80, 0x9D,
    0xEB, 0xF6, 0xD1, 0xCC, 0x9F, 0x82, 0xA5, 0xB8, 0x03, 0x1E, 0x39, 0x24, 0x77, 0x6A, 0x4D, 0x50,
    0xA1, 0xBC, 0x9B, 0x86, 0xD5, 0xC8, 0xEF, 0xF2, 0x49, 0x54, 0x73, 0x6E, 0x3D, 0x20, 0x07, 0x1A,
    0x6C, 0x71, 0x56, 0x4B, 0x18, 0x05, 0x22, 0x3F, 0x84, 0x99, 0xBE, 0xA3, 0xF0, 0xED, 0xCA, 0xD7,
    0x35, 0x28, 0x0F, 0x12, 0x41, 0x5C, 0x7B, 0x66, 0xDD, 0xC0, 0xE7, 0xFA, 0xA9, 0xB4, 0x93, 0x8E,
    0xF8, 0xE5, 0xC2, 0xDF, 0x8C, 0x91, 0xB6, 0xAB, 0x10, 0x0D, 0x2A, 0x37, 0x64, 0x79, 0x5E, 0x43,
    0xB2, 0xAF, 0x88, 0x95, 0xC6, 0xDB, 0xFC, 0xE1, 0x5A, 0x47, 0x60, 0x7D, 0x2E, 0x33, 0x14, 0x09,
    0x7F, 0x62, 0x45, 0x58, 0x0B, 0x16, 0x31, 0x2C, 0x97, 0x8A, 0xAD, 0xB0, 0xE3, 0xFE, 0xD9, 0xC4,
}
Definition at line 198 of file crc.cpp.
Referenced by crc8_sae().