APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/ECUDefines.h File Reference
ECUDefines.h File Reference
#include <stdbool.h>
#include "ECUProtocol.h"
Classes
struct ECU_AuxiliaryErrorBits_t
struct ECU_AutronicErrorBits_t
struct ECU_ErrorBits_t
struct ECU_ThrottleDelayConfigBits_t
struct ECU_ThrottleConfigBits_t
struct ECU_ThrottleCurveConfigBits_t
struct ECU_ECUSettings_t
struct ECU_CompileOptions_t
Macros
#define getMinLengthOfECU_AuxiliaryErrorBits_t() (4)
return the minimum encoded length for the ECU_AuxiliaryErrorBits_t structure
#define getMaxLengthOfECU_AuxiliaryErrorBits_t() (4)
return the maximum encoded length for the ECU_AuxiliaryErrorBits_t structure
#define getMinLengthOfECU_AutronicErrorBits_t() (4)
return the minimum encoded length for the ECU_AutronicErrorBits_t structure
#define getMaxLengthOfECU_AutronicErrorBits_t() (4)
return the maximum encoded length for the ECU_AutronicErrorBits_t structure
#define getMinLengthOfECU_ErrorBits_t() (8)
return the minimum encoded length for the ECU_ErrorBits_t structure
#define getMaxLengthOfECU_ErrorBits_t() (8)
return the maximum encoded length for the ECU_ErrorBits_t structure
#define getMinLengthOfECU_ThrottleDelayConfigBits_t() (1)
return the minimum encoded length for the ECU_ThrottleDelayConfigBits_t structure
#define getMaxLengthOfECU_ThrottleDelayConfigBits_t() (1)
return the maximum encoded length for the ECU_ThrottleDelayConfigBits_t structure
#define getMinLengthOfECU_ThrottleConfigBits_t() (1)
return the minimum encoded length for the ECU_ThrottleConfigBits_t structure
#define getMaxLengthOfECU_ThrottleConfigBits_t() (1)
return the maximum encoded length for the ECU_ThrottleConfigBits_t structure
#define getMinLengthOfECU_ThrottleCurveConfigBits_t() (1)
return the minimum encoded length for the ECU_ThrottleCurveConfigBits_t structure
#define getMaxLengthOfECU_ThrottleCurveConfigBits_t() (1)
return the maximum encoded length for the ECU_ThrottleCurveConfigBits_t structure
#define getMinLengthOfECU_ECUSettings_t() (7)
return the minimum encoded length for the ECU_ECUSettings_t structure
#define getMaxLengthOfECU_ECUSettings_t() (7)
return the maximum encoded length for the ECU_ECUSettings_t structure
#define getMinLengthOfECU_CompileOptions_t() (2)
return the minimum encoded length for the ECU_CompileOptions_t structure
#define getMaxLengthOfECU_CompileOptions_t() (2)
return the maximum encoded length for the ECU_CompileOptions_t structure
Functions
void encodeECU_AuxiliaryErrorBits_t (uint8_t *data, int *bytecount, const ECU_AuxiliaryErrorBits_t *user)
Encode a ECU_AuxiliaryErrorBits_t into a byte array.
int decodeECU_AuxiliaryErrorBits_t (const uint8_t *data, int *bytecount, ECU_AuxiliaryErrorBits_t *user)
Decode a ECU_AuxiliaryErrorBits_t from a byte array.
void encodeECU_AutronicErrorBits_t (uint8_t *data, int *bytecount, const ECU_AutronicErrorBits_t *user)
Encode a ECU_AutronicErrorBits_t into a byte array.
int decodeECU_AutronicErrorBits_t (const uint8_t *data, int *bytecount, ECU_AutronicErrorBits_t *user)
Decode a ECU_AutronicErrorBits_t from a byte array.
void encodeECU_ErrorBits_t (uint8_t *data, int *bytecount, const ECU_ErrorBits_t *user)
Encode a ECU_ErrorBits_t into a byte array.
int decodeECU_ErrorBits_t (const uint8_t *data, int *bytecount, ECU_ErrorBits_t *user)
Decode a ECU_ErrorBits_t from a byte array.
void encodeECU_ThrottleDelayConfigBits_t (uint8_t *data, int *bytecount, const ECU_ThrottleDelayConfigBits_t *user)
Encode a ECU_ThrottleDelayConfigBits_t into a byte array.
int decodeECU_ThrottleDelayConfigBits_t (const uint8_t *data, int *bytecount, ECU_ThrottleDelayConfigBits_t *user)
Decode a ECU_ThrottleDelayConfigBits_t from a byte array.
void encodeECU_ThrottleConfigBits_t (uint8_t *data, int *bytecount, const ECU_ThrottleConfigBits_t *user)
Encode a ECU_ThrottleConfigBits_t into a byte array.
int decodeECU_ThrottleConfigBits_t (const uint8_t *data, int *bytecount, ECU_ThrottleConfigBits_t *user)
Decode a ECU_ThrottleConfigBits_t from a byte array.
void encodeECU_ThrottleCurveConfigBits_t (uint8_t *data, int *bytecount, const ECU_ThrottleCurveConfigBits_t *user)
Encode a ECU_ThrottleCurveConfigBits_t into a byte array.
int decodeECU_ThrottleCurveConfigBits_t (const uint8_t *data, int *bytecount, ECU_ThrottleCurveConfigBits_t *user)
Decode a ECU_ThrottleCurveConfigBits_t from a byte array.
void encodeECU_ECUSettings_t (uint8_t *data, int *bytecount, const ECU_ECUSettings_t *user)
Encode a ECU_ECUSettings_t into a byte array.
int decodeECU_ECUSettings_t (const uint8_t *data, int *bytecount, ECU_ECUSettings_t *user)
Decode a ECU_ECUSettings_t from a byte array.
void encodeECU_CompileOptions_t (uint8_t *data, int *bytecount, const ECU_CompileOptions_t *user)
Encode a ECU_CompileOptions_t into a byte array.
int decodeECU_CompileOptions_t (const uint8_t *data, int *bytecount, ECU_CompileOptions_t *user)
Decode a ECU_CompileOptions_t from a byte array.
Macro Definition Documentation
getMaxLengthOfECU_AutronicErrorBits_t
#define getMaxLengthOfECU_AutronicErrorBits_t () (4)
return the maximum encoded length for the ECU_AutronicErrorBits_t structure
Definition at line 90 of file ECUDefines.h.
getMaxLengthOfECU_AuxiliaryErrorBits_t
#define getMaxLengthOfECU_AuxiliaryErrorBits_t () (4)
return the maximum encoded length for the ECU_AuxiliaryErrorBits_t structure
Definition at line 50 of file ECUDefines.h.
getMaxLengthOfECU_CompileOptions_t
#define getMaxLengthOfECU_CompileOptions_t () (2)
return the maximum encoded length for the ECU_CompileOptions_t structure
Definition at line 207 of file ECUDefines.h.
getMaxLengthOfECU_ECUSettings_t
#define getMaxLengthOfECU_ECUSettings_t () (7)
return the maximum encoded length for the ECU_ECUSettings_t structure
Definition at line 183 of file ECUDefines.h.
getMaxLengthOfECU_ErrorBits_t
#define getMaxLengthOfECU_ErrorBits_t () (8)
return the maximum encoded length for the ECU_ErrorBits_t structure
Definition at line 108 of file ECUDefines.h.
getMaxLengthOfECU_ThrottleConfigBits_t
#define getMaxLengthOfECU_ThrottleConfigBits_t () (1)
return the maximum encoded length for the ECU_ThrottleConfigBits_t structure
Definition at line 145 of file ECUDefines.h.
getMaxLengthOfECU_ThrottleCurveConfigBits_t
#define getMaxLengthOfECU_ThrottleCurveConfigBits_t () (1)
return the maximum encoded length for the ECU_ThrottleCurveConfigBits_t structure
Definition at line 162 of file ECUDefines.h.
getMaxLengthOfECU_ThrottleDelayConfigBits_t
#define getMaxLengthOfECU_ThrottleDelayConfigBits_t () (1)
return the maximum encoded length for the ECU_ThrottleDelayConfigBits_t structure
Definition at line 126 of file ECUDefines.h.
getMinLengthOfECU_AutronicErrorBits_t
#define getMinLengthOfECU_AutronicErrorBits_t () (4)
return the minimum encoded length for the ECU_AutronicErrorBits_t structure
Definition at line 87 of file ECUDefines.h.
getMinLengthOfECU_AuxiliaryErrorBits_t
#define getMinLengthOfECU_AuxiliaryErrorBits_t () (4)
return the minimum encoded length for the ECU_AuxiliaryErrorBits_t structure
Definition at line 47 of file ECUDefines.h.
getMinLengthOfECU_CompileOptions_t
#define getMinLengthOfECU_CompileOptions_t () (2)
return the minimum encoded length for the ECU_CompileOptions_t structure
Definition at line 204 of file ECUDefines.h.
getMinLengthOfECU_ECUSettings_t
#define getMinLengthOfECU_ECUSettings_t () (7)
return the minimum encoded length for the ECU_ECUSettings_t structure
Definition at line 180 of file ECUDefines.h.
getMinLengthOfECU_ErrorBits_t
#define getMinLengthOfECU_ErrorBits_t () (8)
return the minimum encoded length for the ECU_ErrorBits_t structure
Definition at line 105 of file ECUDefines.h.
getMinLengthOfECU_ThrottleConfigBits_t
#define getMinLengthOfECU_ThrottleConfigBits_t () (1)
return the minimum encoded length for the ECU_ThrottleConfigBits_t structure
Definition at line 142 of file ECUDefines.h.
getMinLengthOfECU_ThrottleCurveConfigBits_t
#define getMinLengthOfECU_ThrottleCurveConfigBits_t () (1)
return the minimum encoded length for the ECU_ThrottleCurveConfigBits_t structure
Definition at line 159 of file ECUDefines.h.
getMinLengthOfECU_ThrottleDelayConfigBits_t
#define getMinLengthOfECU_ThrottleDelayConfigBits_t () (1)
return the minimum encoded length for the ECU_ThrottleDelayConfigBits_t structure
Definition at line 123 of file ECUDefines.h.
Function Documentation
decodeECU_AutronicErrorBits_t()
int decodeECU_AutronicErrorBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_AutronicErrorBits_t * _pg_user)
Decode a ECU_AutronicErrorBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 209 of file ECUDefines.c.
Referenced by decodeECU_ErrorBits_t(), and decodeECU_ErrorsPacketStructure().
decodeECU_AuxiliaryErrorBits_t()
int decodeECU_AuxiliaryErrorBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_AuxiliaryErrorBits_t * _pg_user)
Decode a ECU_AuxiliaryErrorBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 75 of file ECUDefines.c.
Referenced by decodeECU_ErrorBits_t(), and decodeECU_ErrorsPacketStructure().
decodeECU_CompileOptions_t()
int decodeECU_CompileOptions_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_CompileOptions_t * _pg_user)
Decode a ECU_CompileOptions_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 625 of file ECUDefines.c.
Referenced by decodeECU_eepromSettingsPacket(), and decodeECU_eepromSettingsPacketStructure().
decodeECU_ECUSettings_t()
int decodeECU_ECUSettings_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_ECUSettings_t * _pg_user)
Decode a ECU_ECUSettings_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 544 of file ECUDefines.c.
decodeECU_ErrorBits_t()
int decodeECU_ErrorBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_ErrorBits_t * _pg_user)
Decode a ECU_ErrorBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 325 of file ECUDefines.c.
decodeECU_ThrottleConfigBits_t()
int decodeECU_ThrottleConfigBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_ThrottleConfigBits_t * _pg_user)
Decode a ECU_ThrottleConfigBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 431 of file ECUDefines.c.
Referenced by decodeECU_ThrottleCalibrationPacket(), decodeECU_ThrottleCalibrationPacketStructure(), and decodeECU_ThrottleSettingsPacketStructure().
decodeECU_ThrottleCurveConfigBits_t()
int decodeECU_ThrottleCurveConfigBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_ThrottleCurveConfigBits_t * _pg_user)
Decode a ECU_ThrottleCurveConfigBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 485 of file ECUDefines.c.
Referenced by decodeECU_ThrottleSettingsPacketStructure().
decodeECU_ThrottleDelayConfigBits_t()
int decodeECU_ThrottleDelayConfigBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_ThrottleDelayConfigBits_t * _pg_user)
Decode a ECU_ThrottleDelayConfigBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 376 of file ECUDefines.c.
Referenced by decodeECU_ThrottleSettingsPacketStructure(), decodeECU_TPSDelayCalibrationPacket(), and decodeECU_TPSDelayCalibrationPacketStructure().
encodeECU_AutronicErrorBits_t()
void encodeECU_AutronicErrorBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_AutronicErrorBits_t * _pg_user)
Encode a ECU_AutronicErrorBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 116 of file ECUDefines.c.
Referenced by encodeECU_ErrorBits_t(), and encodeECU_ErrorsPacketStructure().
encodeECU_AuxiliaryErrorBits_t()
void encodeECU_AuxiliaryErrorBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_AuxiliaryErrorBits_t * _pg_user)
Encode a ECU_AuxiliaryErrorBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 35 of file ECUDefines.c.
Referenced by encodeECU_ErrorBits_t(), and encodeECU_ErrorsPacketStructure().
encodeECU_CompileOptions_t()
void encodeECU_CompileOptions_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_CompileOptions_t * _pg_user)
Encode a ECU_CompileOptions_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 580 of file ECUDefines.c.
Referenced by encodeECU_eepromSettingsPacket(), and encodeECU_eepromSettingsPacketStructure().
encodeECU_ECUSettings_t()
void encodeECU_ECUSettings_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_ECUSettings_t * _pg_user)
Encode a ECU_ECUSettings_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 509 of file ECUDefines.c.
encodeECU_ErrorBits_t()
void encodeECU_ErrorBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_ErrorBits_t * _pg_user)
Encode a ECU_ErrorBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 302 of file ECUDefines.c.
encodeECU_ThrottleConfigBits_t()
void encodeECU_ThrottleConfigBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_ThrottleConfigBits_t * _pg_user)
Encode a ECU_ThrottleConfigBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 402 of file ECUDefines.c.
Referenced by encodeECU_ThrottleCalibrationPacket(), encodeECU_ThrottleCalibrationPacketStructure(), and encodeECU_ThrottleSettingsPacketStructure().
encodeECU_ThrottleCurveConfigBits_t()
void encodeECU_ThrottleCurveConfigBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_ThrottleCurveConfigBits_t * _pg_user)
Encode a ECU_ThrottleCurveConfigBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 461 of file ECUDefines.c.
Referenced by encodeECU_ThrottleSettingsPacketStructure().
encodeECU_ThrottleDelayConfigBits_t()
void encodeECU_ThrottleDelayConfigBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_ThrottleDelayConfigBits_t * _pg_user)
Encode a ECU_ThrottleDelayConfigBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 351 of file ECUDefines.c.
Referenced by encodeECU_ThrottleSettingsPacketStructure(), encodeECU_TPSDelayCalibrationPacket(), and encodeECU_TPSDelayCalibrationPacketStructure().