APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/ECUDefines.c File Reference
ECUDefines.c File Reference
#include "ECUDefines.h"
#include "fielddecode.h"
#include "fieldencode.h"
#include "scaleddecode.h"
#include "scaledencode.h"
Functions
void encodeECU_AuxiliaryErrorBits_t (uint8_t *_pg_data, int *_pg_bytecount, const ECU_AuxiliaryErrorBits_t *_pg_user)
Encode a ECU_AuxiliaryErrorBits_t into a byte array.
int decodeECU_AuxiliaryErrorBits_t (const uint8_t *_pg_data, int *_pg_bytecount, ECU_AuxiliaryErrorBits_t *_pg_user)
Decode a ECU_AuxiliaryErrorBits_t from a byte array.
void encodeECU_AutronicErrorBits_t (uint8_t *_pg_data, int *_pg_bytecount, const ECU_AutronicErrorBits_t *_pg_user)
Encode a ECU_AutronicErrorBits_t into a byte array.
int decodeECU_AutronicErrorBits_t (const uint8_t *_pg_data, int *_pg_bytecount, ECU_AutronicErrorBits_t *_pg_user)
Decode a ECU_AutronicErrorBits_t from a byte array.
void encodeECU_ErrorBits_t (uint8_t *_pg_data, int *_pg_bytecount, const ECU_ErrorBits_t *_pg_user)
Encode a ECU_ErrorBits_t into a byte array.
int decodeECU_ErrorBits_t (const uint8_t *_pg_data, int *_pg_bytecount, ECU_ErrorBits_t *_pg_user)
Decode a ECU_ErrorBits_t from a byte array.
void encodeECU_ThrottleDelayConfigBits_t (uint8_t *_pg_data, int *_pg_bytecount, const ECU_ThrottleDelayConfigBits_t *_pg_user)
Encode a ECU_ThrottleDelayConfigBits_t into a byte array.
int decodeECU_ThrottleDelayConfigBits_t (const uint8_t *_pg_data, int *_pg_bytecount, ECU_ThrottleDelayConfigBits_t *_pg_user)
Decode a ECU_ThrottleDelayConfigBits_t from a byte array.
void encodeECU_ThrottleConfigBits_t (uint8_t *_pg_data, int *_pg_bytecount, const ECU_ThrottleConfigBits_t *_pg_user)
Encode a ECU_ThrottleConfigBits_t into a byte array.
int decodeECU_ThrottleConfigBits_t (const uint8_t *_pg_data, int *_pg_bytecount, ECU_ThrottleConfigBits_t *_pg_user)
Decode a ECU_ThrottleConfigBits_t from a byte array.
void encodeECU_ThrottleCurveConfigBits_t (uint8_t *_pg_data, int *_pg_bytecount, const ECU_ThrottleCurveConfigBits_t *_pg_user)
Encode a ECU_ThrottleCurveConfigBits_t into a byte array.
int decodeECU_ThrottleCurveConfigBits_t (const uint8_t *_pg_data, int *_pg_bytecount, ECU_ThrottleCurveConfigBits_t *_pg_user)
Decode a ECU_ThrottleCurveConfigBits_t from a byte array.
void encodeECU_ECUSettings_t (uint8_t *_pg_data, int *_pg_bytecount, const ECU_ECUSettings_t *_pg_user)
Encode a ECU_ECUSettings_t into a byte array.
int decodeECU_ECUSettings_t (const uint8_t *_pg_data, int *_pg_bytecount, ECU_ECUSettings_t *_pg_user)
Decode a ECU_ECUSettings_t from a byte array.
void encodeECU_CompileOptions_t (uint8_t *_pg_data, int *_pg_bytecount, const ECU_CompileOptions_t *_pg_user)
Encode a ECU_CompileOptions_t into a byte array.
int decodeECU_CompileOptions_t (const uint8_t *_pg_data, int *_pg_bytecount, ECU_CompileOptions_t *_pg_user)
Decode a ECU_CompileOptions_t from a byte array.
Function Documentation
decodeECU_AutronicErrorBits_t()
int decodeECU_AutronicErrorBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_AutronicErrorBits_t * _pg_user)
Decode a ECU_AutronicErrorBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 209 of file ECUDefines.c.
Referenced by decodeECU_ErrorBits_t(), and decodeECU_ErrorsPacketStructure().
decodeECU_AuxiliaryErrorBits_t()
int decodeECU_AuxiliaryErrorBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_AuxiliaryErrorBits_t * _pg_user)
Decode a ECU_AuxiliaryErrorBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 75 of file ECUDefines.c.
Referenced by decodeECU_ErrorBits_t(), and decodeECU_ErrorsPacketStructure().
decodeECU_CompileOptions_t()
int decodeECU_CompileOptions_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_CompileOptions_t * _pg_user)
Decode a ECU_CompileOptions_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 625 of file ECUDefines.c.
Referenced by decodeECU_eepromSettingsPacket(), and decodeECU_eepromSettingsPacketStructure().
decodeECU_ECUSettings_t()
int decodeECU_ECUSettings_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_ECUSettings_t * _pg_user)
Decode a ECU_ECUSettings_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 544 of file ECUDefines.c.
decodeECU_ErrorBits_t()
int decodeECU_ErrorBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_ErrorBits_t * _pg_user)
Decode a ECU_ErrorBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 325 of file ECUDefines.c.
decodeECU_ThrottleConfigBits_t()
int decodeECU_ThrottleConfigBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_ThrottleConfigBits_t * _pg_user)
Decode a ECU_ThrottleConfigBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 431 of file ECUDefines.c.
Referenced by decodeECU_ThrottleCalibrationPacket(), decodeECU_ThrottleCalibrationPacketStructure(), and decodeECU_ThrottleSettingsPacketStructure().
decodeECU_ThrottleCurveConfigBits_t()
int decodeECU_ThrottleCurveConfigBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_ThrottleCurveConfigBits_t * _pg_user)
Decode a ECU_ThrottleCurveConfigBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 485 of file ECUDefines.c.
Referenced by decodeECU_ThrottleSettingsPacketStructure().
decodeECU_ThrottleDelayConfigBits_t()
int decodeECU_ThrottleDelayConfigBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ECU_ThrottleDelayConfigBits_t * _pg_user)
Decode a ECU_ThrottleDelayConfigBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 376 of file ECUDefines.c.
Referenced by decodeECU_ThrottleSettingsPacketStructure(), decodeECU_TPSDelayCalibrationPacket(), and decodeECU_TPSDelayCalibrationPacketStructure().
encodeECU_AutronicErrorBits_t()
void encodeECU_AutronicErrorBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_AutronicErrorBits_t * _pg_user)
Encode a ECU_AutronicErrorBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 116 of file ECUDefines.c.
Referenced by encodeECU_ErrorBits_t(), and encodeECU_ErrorsPacketStructure().
encodeECU_AuxiliaryErrorBits_t()
void encodeECU_AuxiliaryErrorBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_AuxiliaryErrorBits_t * _pg_user)
Encode a ECU_AuxiliaryErrorBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 35 of file ECUDefines.c.
Referenced by encodeECU_ErrorBits_t(), and encodeECU_ErrorsPacketStructure().
encodeECU_CompileOptions_t()
void encodeECU_CompileOptions_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_CompileOptions_t * _pg_user)
Encode a ECU_CompileOptions_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 580 of file ECUDefines.c.
Referenced by encodeECU_eepromSettingsPacket(), and encodeECU_eepromSettingsPacketStructure().
encodeECU_ECUSettings_t()
void encodeECU_ECUSettings_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_ECUSettings_t * _pg_user)
Encode a ECU_ECUSettings_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 509 of file ECUDefines.c.
encodeECU_ErrorBits_t()
void encodeECU_ErrorBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_ErrorBits_t * _pg_user)
Encode a ECU_ErrorBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 302 of file ECUDefines.c.
encodeECU_ThrottleConfigBits_t()
void encodeECU_ThrottleConfigBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_ThrottleConfigBits_t * _pg_user)
Encode a ECU_ThrottleConfigBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 402 of file ECUDefines.c.
Referenced by encodeECU_ThrottleCalibrationPacket(), encodeECU_ThrottleCalibrationPacketStructure(), and encodeECU_ThrottleSettingsPacketStructure().
encodeECU_ThrottleCurveConfigBits_t()
void encodeECU_ThrottleCurveConfigBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_ThrottleCurveConfigBits_t * _pg_user)
Encode a ECU_ThrottleCurveConfigBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 461 of file ECUDefines.c.
Referenced by encodeECU_ThrottleSettingsPacketStructure().
encodeECU_ThrottleDelayConfigBits_t()
void encodeECU_ThrottleDelayConfigBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ECU_ThrottleDelayConfigBits_t * _pg_user)
Encode a ECU_ThrottleDelayConfigBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 351 of file ECUDefines.c.
Referenced by encodeECU_ThrottleSettingsPacketStructure(), encodeECU_TPSDelayCalibrationPacket(), and encodeECU_TPSDelayCalibrationPacketStructure().