APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/ECUProtocol.h File Reference
ECUProtocol.h File Reference
#include <stdbool.h>
#include <stdint.h>
Macros
#define getECUApi() 11
#define getECUVersion() "7.0"
#define translateECU(x) x
Enumerations
enum ECUResetCommands {
ECU_RESET_THROTTLE = 0x01 , ECU_RESET_PUMP = 0x02 , ECU_RESET_GOVERNOR = 0x04 , ECU_RESET_TELEMETRY = 0x08 ,
ECU_RESET_ALL = 0xFF
}
enum ECUDebugResetTests { ECU_DEBUG_RESET_STACK_OVERFLOW = 0x01 , ECU_DEBUG_RESET_STACK_UNDERFLOW , ECU_DEBUG_RESET_DIVIDE_BY_ZERO , ECU_DEBUG_RESET_INFINITE_LOOP }
enum ECUThrottleSource {
ECU_TPS_SRC_NONE = 0x00 , ECU_TPS_SRC_RPM = 0x01 , ECU_TPS_SRC_PWM = 0x02 , ECU_TPS_SRC_SERIAL = 0x04 ,
ECU_TPS_SRC_CAN = 0x08 , ECU_TPS_SRC_ANALOG = 0x0F
}
enum DualFuelPumpMode { ECU_DUAL_PUMP_MODE_DISABLED = 0x00 , ECU_DUAL_PUMP_MODE_PRIMARY_CE , ECU_DUAL_PUMP_MODE_SECONDARY_TSA , ECU_DUAL_PUMP_MODE_BOTH }
enum DualFuelPumpState { ECU_DUAL_PUMP_STATE_RESET = 0x00 , ECU_DUAL_PUMP_STATE_CMD , ECU_DUAL_PUMP_STATE_TEST , ECU_DUAL_PUMP_STATE_FAILURE }
enum DualFuelPumpCommands { ECU_DUAL_PUMP_CMD_SET_PUMP = 0x01 , ECU_DUAL_PUMP_CMD_TEST_PUMP = 0x02 }
enum ECUPackets {
PKT_ECU_TELEMETRY_FAST = 0x00 , PKT_ECU_TELEMETRY_SLOW_0 , PKT_ECU_TELEMETRY_SLOW_1 , PKT_ECU_TELEMETRY_SLOW_2 ,
PKT_ECU_TELEMETRY_SLOW_3 , PKT_ECU_THROTTLE_CALIBRATION = 0x05 , PKT_ECU_THROTTLE , PKT_ECU_THROTTLE_COMBINED ,
PKT_ECU_RPM_COMMAND , PKT_ECU_RPM_CALIBRATION , PKT_ECU_HARDWARE_CONFIG , PKT_ECU_SOFTWARE_VERSION ,
PKT_ECU_TPS_DELAY_CONFIG , PKT_ECU_TELEMETRY_SETTINGS , PKT_ECU_PUMP_CONFIG , PKT_ECU_ERROR_MSG ,
PKT_ECU_POWER_CYCLES = 0x10 , PKT_ECU_PUMP_2_CONFIG , PKT_ECU_PUMP_DEBUG , PKT_ECU_TOTAL_ENGINE_TIME ,
PKT_ECU_SYS_CMD , PKT_ECU_USER_DATA , PKT_ECU_THROTTLE_CURVE_0 , PKT_ECU_THROTTLE_CURVE_1 ,
PKT_ECU_GPIO , PKT_ECU_SETTINGS_DATA , PKT_ECU_AUTRONIC_MEMORY , PKT_ECU_CHT_LOOP ,
PKT_ECU_CANAUTRONIC_RELAY = 0x1F
}
enum ECUSpecialPackets { ECU_CE_CAL_TITLE_1 = 0xA0 , ECU_CE_CAL_TITLE_2 , ECU_CE_CAL_TITLE_3 }
enum ECUSystemCommands {
CMD_ECU_CALIBRATE_ANALOG_CLOSED = 0x01 , CMD_ECU_CALIBRATE_ANALOG_OPEN , CMD_ECU_CALIBRATE_PULSE_CLOSED , CMD_ECU_CALIBRATE_PULSE_OPEN ,
CMD_ECU_CALIBRATE_PULSE_WRITE , CMD_ECU_SET_OUTPUT_DRIVER = 0x0A , CMD_ECU_SET_THROTTLE_CURVE_ACTIVE , CMD_ECU_SET_THROTTLE_CURVE_ELEMENT ,
CMD_ECU_REQUEST_THROTTLE_CURVE_DATA , CMD_ECU_RESET_FUEL_USED = 0x10 , CMD_ECU_SET_FUEL_USED_DIVISOR , CMD_ECU_FUEL_USED_RESET_ON_STARTUP ,
CMD_ECU_SET_GOVERNOR_MODE = 0x20 , CMD_ECU_SET_SERVO_CAN_MODE = 0x28 , CMD_ECU_RESET_INTO_BOOTLOADER = 0x30 , CMD_ECU_RESET_DEFAULT_SETTINGS ,
CMD_ECU_SET_SERIAL_MODE = 0x40 , CMD_ECU_SET_NODE_ID = 0x50 , CMD_ECU_SET_USER_DATA = 0x60 , CMD_ECU_RESET_ENGINE_TIME = 0xA5 ,
CMD_ECU_RESET_ECU = 0xD0
}
Functions
const char * ECUPackets_EnumLabel (int value)
Lookup label for 'ECUPackets' enum entry.
const char * ECUSystemCommands_EnumLabel (int value)
Lookup label for 'ECUSystemCommands' enum entry.
uint8_t * getECUPacketData (void *pkt)
const uint8_t * getECUPacketDataConst (const void *pkt)
void finishECUPacket (void *pkt, int size, uint32_t packetID)
Complete a packet after the data have been encoded.
int getECUPacketSize (const void *pkt)
uint32_t getECUPacketID (const void *pkt)
Macro Definition Documentation
getECUApi
#define getECUApi () 11
Returns
the protocol API enumeration
Definition at line 46 of file ECUProtocol.h.
getECUVersion
#define getECUVersion () "7.0"
Returns
the protocol version string
Definition at line 49 of file ECUProtocol.h.
translateECU
#define translateECU (x) x
Definition at line 53 of file ECUProtocol.h.
Referenced by ECUPackets_EnumLabel(), and ECUSystemCommands_EnumLabel().
Enumeration Type Documentation
DualFuelPumpCommands
enum DualFuelPumpCommands
Enumerator
ECU_DUAL_PUMP_CMD_SET_PUMP
Switch to a particular pump mode.
ECU_DUAL_PUMP_CMD_TEST_PUMP
Temporarily switch to a particular pump mode.
Definition at line 105 of file ECUProtocol.h.
DualFuelPumpMode
enum DualFuelPumpMode
Enumerator
ECU_DUAL_PUMP_MODE_DISABLED
Both pumps disabled.
ECU_DUAL_PUMP_MODE_PRIMARY_CE
Primary pump running.
ECU_DUAL_PUMP_MODE_SECONDARY_TSA
Secondary pump running.
ECU_DUAL_PUMP_MODE_BOTH
Both pumps running.
Definition at line 89 of file ECUProtocol.h.
DualFuelPumpState
enum DualFuelPumpState
Enumerator
ECU_DUAL_PUMP_STATE_RESET
Pump state machine is in the initial reset state.
ECU_DUAL_PUMP_STATE_CMD
Pump was explicitly commanded to the current state.
ECU_DUAL_PUMP_STATE_TEST
Pump is running in manual test mode.
ECU_DUAL_PUMP_STATE_FAILURE
Pump has switched over due to detected failure.
Definition at line 97 of file ECUProtocol.h.
ECUDebugResetTests
enum ECUDebugResetTests
Enumerator
ECU_DEBUG_RESET_STACK_OVERFLOW
ECU_DEBUG_RESET_STACK_UNDERFLOW
ECU_DEBUG_RESET_DIVIDE_BY_ZERO
ECU_DEBUG_RESET_INFINITE_LOOP
Definition at line 68 of file ECUProtocol.h.
ECUPackets
enum ECUPackets
ECU packet identifier (ID) definitions
Enumerator
PKT_ECU_TELEMETRY_FAST
High priority telemetry data from the ECU.
PKT_ECU_TELEMETRY_SLOW_0
First low priority telemetry packet from the ECU.
PKT_ECU_TELEMETRY_SLOW_1
Second low priority telemetry packet from the ECU.
PKT_ECU_TELEMETRY_SLOW_2
Third low priority telemetry packet from the ECU.
PKT_ECU_TELEMETRY_SLOW_3
Fourth low priority telemetry packet from the ECU (reserved for future use)
PKT_ECU_THROTTLE_CALIBRATION
Throttle calibration values.
PKT_ECU_THROTTLE
ECU throttle command.
PKT_ECU_THROTTLE_COMBINED
ECU Throttle command (position and pulse)
PKT_ECU_RPM_COMMAND
RPM setpoint command.
PKT_ECU_RPM_CALIBRATION
RPM control loop calibration values.
PKT_ECU_HARDWARE_CONFIG
Serial number information.
PKT_ECU_SOFTWARE_VERSION
Firmware version information.
PKT_ECU_TPS_DELAY_CONFIG
Throttle delay configuration.
PKT_ECU_TELEMETRY_SETTINGS
Telemetry configuration.
PKT_ECU_PUMP_CONFIG
ECU Pump configuration packet 1 of 2.
PKT_ECU_ERROR_MSG
Error messages.
PKT_ECU_POWER_CYCLES
System information.
PKT_ECU_PUMP_2_CONFIG
ECU Pump configuration packet 2 of 2.
PKT_ECU_PUMP_DEBUG
Pump debug information.
PKT_ECU_TOTAL_ENGINE_TIME
Total engine run-time.
PKT_ECU_SYS_CMD
ECU System command.
PKT_ECU_USER_DATA
User-configurable data bytes.
PKT_ECU_THROTTLE_CURVE_0
Throttle curve data, packet 1 of 2.
PKT_ECU_THROTTLE_CURVE_1
Throttle curve data, packet 2 of 2.
PKT_ECU_GPIO
GPIO settings.
PKT_ECU_SETTINGS_DATA
Non-volatile settings information.
PKT_ECU_AUTRONIC_MEMORY
Read or write Autronic RAM.
PKT_ECU_CHT_LOOP
Control loop settings for the CHT control loop.
PKT_ECU_CANAUTRONIC_RELAY
Relay Autronic data across CAN.
Definition at line 114 of file ECUProtocol.h.
ECUResetCommands
enum ECUResetCommands
Enumeration defining RESET commands for ECU settings
Enumerator
ECU_RESET_THROTTLE
Reset throttle settings to default values.
ECU_RESET_PUMP
Reset pump settings to default values.
ECU_RESET_GOVERNOR
Reset governor settings to default values.
ECU_RESET_TELEMETRY
Reset telemetry settings to default values.
ECU_RESET_ALL
Reset all ECU settings to default values.
Definition at line 59 of file ECUProtocol.h.
ECUSpecialPackets
enum ECUSpecialPackets
Enumerator
ECU_CE_CAL_TITLE_1
ECU_CE_CAL_TITLE_2
ECU_CE_CAL_TITLE_3
Definition at line 150 of file ECUProtocol.h.
ECUSystemCommands
enum ECUSystemCommands
These system command identifiers are used with the system command packet.
Enumerator
CMD_ECU_CALIBRATE_ANALOG_CLOSED
Save the current value of the analog throttle position input as the 'Closed' position. To calibrate the closed analog input position, set the desired analog input level, and send this command to the ECU.
CMD_ECU_CALIBRATE_ANALOG_OPEN
Save the current value of the analog throttle position input as the 'Open' position. To calibrate the open analog input position, set the desired analog input level, and send this command to the ECU.
CMD_ECU_CALIBRATE_PULSE_CLOSED
Save the current value of the throttle output pulse width to a temporary variable in the ECU. When the CALIBRATE_PULSE_WRITE command is sent to the ECU, this value will be saved as the 'Closed' pulse width.
CMD_ECU_CALIBRATE_PULSE_OPEN
Save the current value of the throttle output pulse width to a temporary variable in the ECU. When the CALIBRATE_PULSE_WRITE command is sent to the ECU, this value will be saved as the 'Open' pulse width.
CMD_ECU_CALIBRATE_PULSE_WRITE
Configure the throttle output positions. The CALIBRATE_PULSE_CLOSED and CALIBRATE_PULSE_OPEN commands should have already been sent to the ECU. The ECU then saves the temporary values as the 'Closed' and 'Open' throttle output values, respectively.
CMD_ECU_SET_OUTPUT_DRIVER
Set one of four high-current output drivers. Send two bytes after the command byte. Byte 1: Driver - Select driver number (1, 2, 3 or 4) Byte 2: Status - Set driver status (1 = ON, 0 = OFF)
CMD_ECU_SET_THROTTLE_CURVE_ACTIVE
Turn the throttle linearization curve either on or off. Byte 1: 1 = ON 0 = OFF.
CMD_ECU_SET_THROTTLE_CURVE_ELEMENT
Set individual elements in the throttle linearization lookup table. Byte 1 = Element number (0 to 10, inclusive) Byte 2 = Value (0 to 200 inclusive) Each bit of the 'value' byte represents 0.5% throttle. So, 0 = 0% and 200 = 100%.
CMD_ECU_REQUEST_THROTTLE_CURVE_DATA
Request the throttle curve lookup table data. If requested on CAN, the data will be returned on CAN. If requested on RS232, the data will be returned on RS232.
CMD_ECU_RESET_FUEL_USED
Reset the FuelUsed value. This will set the FuelUsed data to zero.
CMD_ECU_SET_FUEL_USED_DIVISOR
Configure the FuelUsed divisor. This is an unsigned 16-bit value. The fuel used value is divided by this divisor before being transmitted by the auxiliary processor. Set this value to 1 to leave the fuel used data unaffected. If you use values greater than 100 the divisor is automatically interpreted as being in units of 0.01 (i.e. 100 times the resolution).
CMD_ECU_FUEL_USED_RESET_ON_STARTUP
Set or clear the Fuel Used reset flag. If this flag is set, the FuelUsed data will reset (to zero) when the ECU is power cycled. 1 = Reset Fuel Used data on powerup 0 = Do not reset Fuel Used data on power up.
CMD_ECU_SET_GOVERNOR_MODE
Manually set the RPM governor mode Byte1 = MODE 0 = Governor Off (Open loop throttle control) 1 = Governor based on throttle command 2 = Governor based on RPM command.
CMD_ECU_SET_SERVO_CAN_MODE
CMD_ECU_RESET_INTO_BOOTLOADER
Reset the ECU into bootloader mode.
CMD_ECU_RESET_DEFAULT_SETTINGS
Set ECU settings to their default values.
CMD_ECU_SET_SERIAL_MODE
Set the serial relay mode used for Autronic relay.
CMD_ECU_SET_NODE_ID
Set the address (CAN node ID) for the ECU.
CMD_ECU_SET_USER_DATA
Save a single byte of USER_DATA in EEPROM Byte1 = USER_DATA address (0 to 7) Byte2 = USER_DATA variable (0x00 to 0xFF)
CMD_ECU_RESET_ENGINE_TIME
Reset the engine time counter. If no further bytes are sent after the RESET_ENGINE_TIME command, this will set the engine time (in seconds) to zero. Note that the 'Total Engine Time' counter is not reset. To set the engine time to a specific value, send the engine time in seconds as a 3-byte (big endian) number after the RESET_ENGINE_TIME command.
CMD_ECU_RESET_ECU
Cause a system reset.
Definition at line 161 of file ECUProtocol.h.
ECUThrottleSource
enum ECUThrottleSource
ECU throttle position signal source enumeration
Enumerator
ECU_TPS_SRC_NONE
No throttle source.
ECU_TPS_SRC_RPM
Throttle is commanded by RPM governor.
ECU_TPS_SRC_PWM
Throttle is commanded from PWM input.
ECU_TPS_SRC_SERIAL
Throttle is commanded from serial command packet.
ECU_TPS_SRC_CAN
Throttle is commanded from CAN command packet.
ECU_TPS_SRC_ANALOG
Throttle is commanded from analog input.
Definition at line 79 of file ECUProtocol.h.
Function Documentation
ECUPackets_EnumLabel()
const char * ECUPackets_EnumLabel (int value)
Lookup label for 'ECUPackets' enum entry.
Returns
the label of a 'ECUPackets' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 29 of file ECUProtocol.c.
ECUSystemCommands_EnumLabel()
const char * ECUSystemCommands_EnumLabel (int value)
Lookup label for 'ECUSystemCommands' enum entry.
Returns
the label of a 'ECUSystemCommands' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 97 of file ECUProtocol.c.
finishECUPacket()
void finishECUPacket (void * pkt, int size, uint32_t packetID)
Complete a packet after the data have been encoded.
Referenced by encodeECU_CalibrateAnalogClosedPacket(), encodeECU_CalibrateAnalogOpenPacket(), encodeECU_CalibratePulseClosedPacket(), encodeECU_CalibratePulseOpenPacket(), encodeECU_CalibratePulseWritePacket(), encodeECU_CHTLoopSettingsPacket(), encodeECU_CHTLoopSettingsPacketStructure(), encodeECU_DualPump_SelectPumpPacket(), encodeECU_DualPump_SetTelemetryPeriodPacket(), encodeECU_DualPump_TestPumpPacketStructure(), encodeECU_DualPumpControlTelemetryPacketStructure(), encodeECU_ECUDataPacketStructure(), encodeECU_eepromSettingsPacket(), encodeECU_eepromSettingsPacketStructure(), encodeECU_ErrorsPacketStructure(), encodeECU_FuelUsedSettingsPacketStructure(), encodeECU_GovernorSettingsPacketStructure(), encodeECU_HardwareConfigPacketStructure(), encodeECU_PowerCyclesPacketStructure(), encodeECU_Pump2ConfigPacketStructure(), encodeECU_PumpConfigPacketStructure(), encodeECU_PumpDebugPacketStructure(), encodeECU_PumpSettingsPacketStructure(), encodeECU_RequestThrottleCurveDataPacket(), encodeECU_ResetECUPacket(), encodeECU_ResetEngineTimePacket(), encodeECU_ResetFuelUsedPacket(), encodeECU_RPMCommandPacketStructure(), encodeECU_RPMLoopCalibrationPacketStructure(), encodeECU_SetECUAddressPacket(), encodeECU_SetFuelUsedDivisorPacket(), encodeECU_SetFuelUsedResetFlagPacket(), encodeECU_SetGovernorModePacket(), encodeECU_SetOutputDriverPacket(), encodeECU_SetSerialModePacket(), encodeECU_SetThrottleCurveActivePacket(), encodeECU_SetThrottleCurveElementPacket(), encodeECU_SetUserDataPacket(), encodeECU_SystemCommandPacketStructure(), encodeECU_TelemetryFastPacket(), encodeECU_TelemetryFastPacketStructure(), encodeECU_TelemetrySettingsPacketStructure(), encodeECU_TelemetrySlow0PacketStructure(), encodeECU_TelemetrySlow1PacketStructure(), encodeECU_TelemetrySlow2PacketStructure(), encodeECU_ThrottleCalibrationPacket(), encodeECU_ThrottleCalibrationPacketStructure(), encodeECU_ThrottleCommandPacket(), encodeECU_ThrottleCurve1Packet(), encodeECU_ThrottleCurvePacket(), encodeECU_ThrottleSettingsPacketStructure(), encodeECU_TotalEngineTimePacket(), encodeECU_TPSDelayCalibrationPacket(), encodeECU_TPSDelayCalibrationPacketStructure(), encodeECU_UserDataPacket(), and encodeECU_VersionPacketStructure().
getECUPacketData()
uint8_t * getECUPacketData (void * pkt)
Returns
the packet data pointer from the packet
Referenced by encodeECU_CalibrateAnalogClosedPacket(), encodeECU_CalibrateAnalogOpenPacket(), encodeECU_CalibratePulseClosedPacket(), encodeECU_CalibratePulseOpenPacket(), encodeECU_CalibratePulseWritePacket(), encodeECU_CHTLoopSettingsPacket(), encodeECU_CHTLoopSettingsPacketStructure(), encodeECU_DualPump_SelectPumpPacket(), encodeECU_DualPump_SetTelemetryPeriodPacket(), encodeECU_DualPump_TestPumpPacketStructure(), encodeECU_DualPumpControlTelemetryPacketStructure(), encodeECU_ECUDataPacketStructure(), encodeECU_eepromSettingsPacket(), encodeECU_eepromSettingsPacketStructure(), encodeECU_ErrorsPacketStructure(), encodeECU_FuelUsedSettingsPacketStructure(), encodeECU_GovernorSettingsPacketStructure(), encodeECU_HardwareConfigPacketStructure(), encodeECU_PowerCyclesPacketStructure(), encodeECU_Pump2ConfigPacketStructure(), encodeECU_PumpConfigPacketStructure(), encodeECU_PumpDebugPacketStructure(), encodeECU_PumpSettingsPacketStructure(), encodeECU_RequestThrottleCurveDataPacket(), encodeECU_ResetECUPacket(), encodeECU_ResetEngineTimePacket(), encodeECU_ResetFuelUsedPacket(), encodeECU_RPMCommandPacketStructure(), encodeECU_RPMLoopCalibrationPacketStructure(), encodeECU_SetECUAddressPacket(), encodeECU_SetFuelUsedDivisorPacket(), encodeECU_SetFuelUsedResetFlagPacket(), encodeECU_SetGovernorModePacket(), encodeECU_SetOutputDriverPacket(), encodeECU_SetSerialModePacket(), encodeECU_SetThrottleCurveActivePacket(), encodeECU_SetThrottleCurveElementPacket(), encodeECU_SetUserDataPacket(), encodeECU_SystemCommandPacketStructure(), encodeECU_TelemetryFastPacket(), encodeECU_TelemetryFastPacketStructure(), encodeECU_TelemetrySettingsPacketStructure(), encodeECU_TelemetrySlow0PacketStructure(), encodeECU_TelemetrySlow1PacketStructure(), encodeECU_TelemetrySlow2PacketStructure(), encodeECU_ThrottleCalibrationPacket(), encodeECU_ThrottleCalibrationPacketStructure(), encodeECU_ThrottleCommandPacket(), encodeECU_ThrottleCurve1Packet(), encodeECU_ThrottleCurvePacket(), encodeECU_ThrottleSettingsPacketStructure(), encodeECU_TotalEngineTimePacket(), encodeECU_TPSDelayCalibrationPacket(), encodeECU_TPSDelayCalibrationPacketStructure(), encodeECU_UserDataPacket(), and encodeECU_VersionPacketStructure().
getECUPacketDataConst()
const uint8_t * getECUPacketDataConst (const void * pkt)
Returns
the packet data pointer from the packet, const
Referenced by decodeECU_CalibrateAnalogClosedPacket(), decodeECU_CalibrateAnalogOpenPacket(), decodeECU_CalibratePulseClosedPacket(), decodeECU_CalibratePulseOpenPacket(), decodeECU_CalibratePulseWritePacket(), decodeECU_CHTLoopSettingsPacket(), decodeECU_CHTLoopSettingsPacketStructure(), decodeECU_DualPump_SelectPumpPacket(), decodeECU_DualPump_SetTelemetryPeriodPacket(), decodeECU_DualPump_TestPumpPacketStructure(), decodeECU_DualPumpControlTelemetryPacketStructure(), decodeECU_ECUDataPacketStructure(), decodeECU_eepromSettingsPacket(), decodeECU_eepromSettingsPacketStructure(), decodeECU_ErrorsPacketStructure(), decodeECU_FuelUsedSettingsPacketStructure(), decodeECU_GovernorSettingsPacketStructure(), decodeECU_HardwareConfigPacketStructure(), decodeECU_PowerCyclesPacketStructure(), decodeECU_Pump2ConfigPacketStructure(), decodeECU_PumpConfigPacketStructure(), decodeECU_PumpDebugPacketStructure(), decodeECU_PumpSettingsPacketStructure(), decodeECU_RequestThrottleCurveDataPacket(), decodeECU_ResetECUPacket(), decodeECU_ResetEngineTimePacket(), decodeECU_ResetFuelUsedPacket(), decodeECU_RPMCommandPacketStructure(), decodeECU_RPMLoopCalibrationPacketStructure(), decodeECU_SetECUAddressPacket(), decodeECU_SetFuelUsedDivisorPacket(), decodeECU_SetFuelUsedResetFlagPacket(), decodeECU_SetGovernorModePacket(), decodeECU_SetOutputDriverPacket(), decodeECU_SetSerialModePacket(), decodeECU_SetThrottleCurveActivePacket(), decodeECU_SetThrottleCurveElementPacket(), decodeECU_SetUserDataPacket(), decodeECU_SystemCommandPacketStructure(), decodeECU_TelemetryFastPacket(), decodeECU_TelemetryFastPacketStructure(), decodeECU_TelemetrySettingsPacketStructure(), decodeECU_TelemetrySlow0PacketStructure(), decodeECU_TelemetrySlow1PacketStructure(), decodeECU_TelemetrySlow2PacketStructure(), decodeECU_ThrottleCalibrationPacket(), decodeECU_ThrottleCalibrationPacketStructure(), decodeECU_ThrottleCommandPacket(), decodeECU_ThrottleCurve1Packet(), decodeECU_ThrottleCurvePacket(), decodeECU_ThrottleSettingsPacketStructure(), decodeECU_TotalEngineTimePacket(), decodeECU_TPSDelayCalibrationPacket(), decodeECU_TPSDelayCalibrationPacketStructure(), decodeECU_UserDataPacket(), and decodeECU_VersionPacketStructure().
getECUPacketID()
uint32_t getECUPacketID (const void * pkt)
Returns
the ID of a packet from the packet header
Referenced by decodeECU_CalibrateAnalogClosedPacket(), decodeECU_CalibrateAnalogOpenPacket(), decodeECU_CalibratePulseClosedPacket(), decodeECU_CalibratePulseOpenPacket(), decodeECU_CalibratePulseWritePacket(), decodeECU_CHTLoopSettingsPacket(), decodeECU_CHTLoopSettingsPacketStructure(), decodeECU_DualPump_SelectPumpPacket(), decodeECU_DualPump_SetTelemetryPeriodPacket(), decodeECU_DualPump_TestPumpPacketStructure(), decodeECU_DualPumpControlTelemetryPacketStructure(), decodeECU_ECUDataPacketStructure(), decodeECU_eepromSettingsPacket(), decodeECU_eepromSettingsPacketStructure(), decodeECU_ErrorsPacketStructure(), decodeECU_FuelUsedSettingsPacketStructure(), decodeECU_GovernorSettingsPacketStructure(), decodeECU_HardwareConfigPacketStructure(), decodeECU_PowerCyclesPacketStructure(), decodeECU_Pump2ConfigPacketStructure(), decodeECU_PumpConfigPacketStructure(), decodeECU_PumpDebugPacketStructure(), decodeECU_PumpSettingsPacketStructure(), decodeECU_RequestThrottleCurveDataPacket(), decodeECU_ResetECUPacket(), decodeECU_ResetEngineTimePacket(), decodeECU_ResetFuelUsedPacket(), decodeECU_RPMCommandPacketStructure(), decodeECU_RPMLoopCalibrationPacketStructure(), decodeECU_SetECUAddressPacket(), decodeECU_SetFuelUsedDivisorPacket(), decodeECU_SetFuelUsedResetFlagPacket(), decodeECU_SetGovernorModePacket(), decodeECU_SetOutputDriverPacket(), decodeECU_SetSerialModePacket(), decodeECU_SetThrottleCurveActivePacket(), decodeECU_SetThrottleCurveElementPacket(), decodeECU_SetUserDataPacket(), decodeECU_SystemCommandPacketStructure(), decodeECU_TelemetryFastPacket(), decodeECU_TelemetryFastPacketStructure(), decodeECU_TelemetrySettingsPacketStructure(), decodeECU_TelemetrySlow0PacketStructure(), decodeECU_TelemetrySlow1PacketStructure(), decodeECU_TelemetrySlow2PacketStructure(), decodeECU_ThrottleCalibrationPacket(), decodeECU_ThrottleCalibrationPacketStructure(), decodeECU_ThrottleCommandPacket(), decodeECU_ThrottleCurve1Packet(), decodeECU_ThrottleCurvePacket(), decodeECU_ThrottleSettingsPacketStructure(), decodeECU_TotalEngineTimePacket(), decodeECU_TPSDelayCalibrationPacket(), decodeECU_TPSDelayCalibrationPacketStructure(), decodeECU_UserDataPacket(), and decodeECU_VersionPacketStructure().
getECUPacketSize()
int getECUPacketSize (const void * pkt)
Returns
the size of a packet from the packet header
Referenced by decodeECU_CalibrateAnalogClosedPacket(), decodeECU_CalibrateAnalogOpenPacket(), decodeECU_CalibratePulseClosedPacket(), decodeECU_CalibratePulseOpenPacket(), decodeECU_CalibratePulseWritePacket(), decodeECU_CHTLoopSettingsPacket(), decodeECU_CHTLoopSettingsPacketStructure(), decodeECU_DualPump_SelectPumpPacket(), decodeECU_DualPump_SetTelemetryPeriodPacket(), decodeECU_DualPump_TestPumpPacketStructure(), decodeECU_DualPumpControlTelemetryPacketStructure(), decodeECU_ECUDataPacketStructure(), decodeECU_eepromSettingsPacket(), decodeECU_eepromSettingsPacketStructure(), decodeECU_ErrorsPacketStructure(), decodeECU_FuelUsedSettingsPacketStructure(), decodeECU_GovernorSettingsPacketStructure(), decodeECU_HardwareConfigPacketStructure(), decodeECU_PowerCyclesPacketStructure(), decodeECU_Pump2ConfigPacketStructure(), decodeECU_PumpConfigPacketStructure(), decodeECU_PumpDebugPacketStructure(), decodeECU_PumpSettingsPacketStructure(), decodeECU_RequestThrottleCurveDataPacket(), decodeECU_ResetECUPacket(), decodeECU_ResetEngineTimePacket(), decodeECU_ResetFuelUsedPacket(), decodeECU_RPMCommandPacketStructure(), decodeECU_RPMLoopCalibrationPacketStructure(), decodeECU_SetECUAddressPacket(), decodeECU_SetFuelUsedDivisorPacket(), decodeECU_SetFuelUsedResetFlagPacket(), decodeECU_SetGovernorModePacket(), decodeECU_SetOutputDriverPacket(), decodeECU_SetSerialModePacket(), decodeECU_SetThrottleCurveActivePacket(), decodeECU_SetThrottleCurveElementPacket(), decodeECU_SetUserDataPacket(), decodeECU_SystemCommandPacketStructure(), decodeECU_TelemetryFastPacket(), decodeECU_TelemetryFastPacketStructure(), decodeECU_TelemetrySettingsPacketStructure(), decodeECU_TelemetrySlow0PacketStructure(), decodeECU_TelemetrySlow1PacketStructure(), decodeECU_TelemetrySlow2PacketStructure(), decodeECU_ThrottleCalibrationPacket(), decodeECU_ThrottleCalibrationPacketStructure(), decodeECU_ThrottleCommandPacket(), decodeECU_ThrottleCurve1Packet(), decodeECU_ThrottleCurvePacket(), decodeECU_ThrottleSettingsPacketStructure(), decodeECU_TotalEngineTimePacket(), decodeECU_TPSDelayCalibrationPacket(), decodeECU_TPSDelayCalibrationPacketStructure(), decodeECU_UserDataPacket(), and decodeECU_VersionPacketStructure().