APM:Libraries: libraries/AP_Param/tools/eedump_apparam.c File Reference
eedump_apparam.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
Classes
struct EEPROM_header
struct Param_header
Enumerations
enum ap_var_type {
AP_PARAM_NONE = 0 , AP_PARAM_INT8 , AP_PARAM_INT16 , AP_PARAM_INT32 ,
AP_PARAM_FLOAT , AP_PARAM_VECTOR3F , AP_PARAM_VECTOR6F , AP_PARAM_MATRIX3F ,
AP_PARAM_GROUP
}
Functions
static uint8_t type_size (enum ap_var_type type)
static void fail (const char *why)
int main (int argc, char *argv[])
Variables
uint8_t eeprom [0x1000]
static const uint16_t k_EEPROM_magic0 = 0x50
static const uint16_t k_EEPROM_magic1 = 0x41
static const uint16_t k_EEPROM_revision = 6
static const char * type_names [8]
static const uint16_t _sentinal_key = 0x1FF
static const uint8_t _sentinal_type = 0x1F
static const uint8_t _sentinal_group = 0xFF
Enumeration Type Documentation
ap_var_type
enum ap_var_type
Enumerator
AP_PARAM_NONE
AP_PARAM_INT8
AP_PARAM_INT16
AP_PARAM_INT32
AP_PARAM_FLOAT
AP_PARAM_VECTOR3F
AP_PARAM_VECTOR6F
AP_PARAM_MATRIX3F
AP_PARAM_GROUP
Definition at line 29 of file eedump_apparam.c.
Function Documentation
fail()
static void fail (const char * why) static
Definition at line 83 of file eedump_apparam.c.
Referenced by Linux::Storage::_storage_create(), AP_HAL::Device::check_next_register(), GCS_MAVLINK::handle_device_op_read(), GCS_MAVLINK::handle_device_op_write(), AP_Compass_AK09916::init(), AP_Compass_AK8963::init(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_QMC5883L::init(), AP_RangeFinder_Benewake_TFMiniPlus::init(), main(), AP_Compass_AK09916::probe_ICM20948(), and setup().
main()
int main (int argc, char * argv[])
Definition at line 90 of file eedump_apparam.c.
type_size()
static uint8_t type_size (enum ap_var_type type) static
Definition at line 57 of file eedump_apparam.c.
Referenced by main().
Variable Documentation
_sentinal_group
const uint8_t _sentinal_group = 0xFF static
Definition at line 55 of file eedump_apparam.c.
_sentinal_key
const uint16_t _sentinal_key = 0x1FF static
Definition at line 53 of file eedump_apparam.c.
Referenced by main().
_sentinal_type
const uint8_t _sentinal_type = 0x1F static
Definition at line 54 of file eedump_apparam.c.
Referenced by main().
eeprom
uint8_t eeprom[0x1000]
Definition at line 17 of file eedump_apparam.c.
Referenced by main().
k_EEPROM_magic0
const uint16_t k_EEPROM_magic0 = 0x50 static
Definition at line 25 of file eedump_apparam.c.
Referenced by main().
k_EEPROM_magic1
const uint16_t k_EEPROM_magic1 = 0x41 static
Definition at line 26 of file eedump_apparam.c.
Referenced by main().
k_EEPROM_revision
const uint16_t k_EEPROM_revision = 6 static
Definition at line 27 of file eedump_apparam.c.
Referenced by main().
type_names
const char* type_names[8] static
Initial value:
= {
    "NONE", "INT8", "INT16", "INT32", "FLOAT", "VECTOR3F", "MATRIX6F", "GROUP"
}
Definition at line 41 of file eedump_apparam.c.
Referenced by main().