APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/ESCDefines.h File Reference
ESCDefines.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include "ESCVelocityProtocol.h"
Classes
struct ESC_StatusBits_t
struct ESC_WarningBits_t
struct ESC_ErrorBits_t
struct ESC_TelemetryPackets_t
struct ESC_DebugPackets_t
struct ESC_ControlLoopCommon_t
Macros
#define getMinLengthOfESC_StatusBits_t() (3)
return the minimum encoded length for the ESC_StatusBits_t structure
#define getMaxLengthOfESC_StatusBits_t() (3)
return the maximum encoded length for the ESC_StatusBits_t structure
#define getMinLengthOfESC_WarningBits_t() (2)
return the minimum encoded length for the ESC_WarningBits_t structure
#define getMaxLengthOfESC_WarningBits_t() (2)
return the maximum encoded length for the ESC_WarningBits_t structure
#define getMinLengthOfESC_ExtendedWarningBits_t() 0
return the minimum encoded length for the ESC_ExtendedWarningBits_t structure
#define getMaxLengthOfESC_ExtendedWarningBits_t() (2)
return the maximum encoded length for the ESC_ExtendedWarningBits_t structure
#define getMinLengthOfESC_ErrorBits_t() (2)
return the minimum encoded length for the ESC_ErrorBits_t structure
#define getMaxLengthOfESC_ErrorBits_t() (2)
return the maximum encoded length for the ESC_ErrorBits_t structure
#define getMinLengthOfESC_ExtendedErrorBits_t() 0
return the minimum encoded length for the ESC_ExtendedErrorBits_t structure
#define getMaxLengthOfESC_ExtendedErrorBits_t() (1)
return the maximum encoded length for the ESC_ExtendedErrorBits_t structure
#define getMinLengthOfESC_TelemetryPackets_t() (1)
return the minimum encoded length for the ESC_TelemetryPackets_t structure
#define getMaxLengthOfESC_TelemetryPackets_t() (1)
return the maximum encoded length for the ESC_TelemetryPackets_t structure
#define getMinLengthOfESC_DebugPackets_t() (1)
return the minimum encoded length for the ESC_DebugPackets_t structure
#define getMaxLengthOfESC_DebugPackets_t() (2)
return the maximum encoded length for the ESC_DebugPackets_t structure
#define getMinLengthOfESC_ControlLoopCommon_t() (8)
return the minimum encoded length for the ESC_ControlLoopCommon_t structure
#define getMaxLengthOfESC_ControlLoopCommon_t() (11)
return the maximum encoded length for the ESC_ControlLoopCommon_t structure
Functions
void encodeESC_StatusBits_t (uint8_t *data, int *bytecount, const ESC_StatusBits_t *user)
Encode a ESC_StatusBits_t into a byte array.
int decodeESC_StatusBits_t (const uint8_t *data, int *bytecount, ESC_StatusBits_t *user)
Decode a ESC_StatusBits_t from a byte array.
void encodeESC_WarningBits_t (uint8_t *data, int *bytecount, const ESC_WarningBits_t *user)
Encode a ESC_WarningBits_t into a byte array.
int decodeESC_WarningBits_t (const uint8_t *data, int *bytecount, ESC_WarningBits_t *user)
Decode a ESC_WarningBits_t from a byte array.
void encodeESC_ExtendedWarningBits_t (uint8_t *data, int *bytecount, const ESC_WarningBits_t *user)
Encode a ESC_ExtendedWarningBits_t into a byte array.
int decodeESC_ExtendedWarningBits_t (const uint8_t *data, int *bytecount, ESC_WarningBits_t *user)
Decode a ESC_ExtendedWarningBits_t from a byte array.
void encodeESC_ErrorBits_t (uint8_t *data, int *bytecount, const ESC_ErrorBits_t *user)
Encode a ESC_ErrorBits_t into a byte array.
int decodeESC_ErrorBits_t (const uint8_t *data, int *bytecount, ESC_ErrorBits_t *user)
Decode a ESC_ErrorBits_t from a byte array.
void encodeESC_ExtendedErrorBits_t (uint8_t *data, int *bytecount, const ESC_ErrorBits_t *user)
Encode a ESC_ExtendedErrorBits_t into a byte array.
int decodeESC_ExtendedErrorBits_t (const uint8_t *data, int *bytecount, ESC_ErrorBits_t *user)
Decode a ESC_ExtendedErrorBits_t from a byte array.
void encodeESC_TelemetryPackets_t (uint8_t *data, int *bytecount, const ESC_TelemetryPackets_t *user)
Encode a ESC_TelemetryPackets_t into a byte array.
int decodeESC_TelemetryPackets_t (const uint8_t *data, int *bytecount, ESC_TelemetryPackets_t *user)
Decode a ESC_TelemetryPackets_t from a byte array.
void encodeESC_DebugPackets_t (uint8_t *data, int *bytecount, const ESC_DebugPackets_t *user)
Encode a ESC_DebugPackets_t into a byte array.
int decodeESC_DebugPackets_t (const uint8_t *data, int *bytecount, ESC_DebugPackets_t *user)
Decode a ESC_DebugPackets_t from a byte array.
void encodeESC_ControlLoopCommon_t (uint8_t *data, int *bytecount, const ESC_ControlLoopCommon_t *user)
Encode a ESC_ControlLoopCommon_t into a byte array.
int decodeESC_ControlLoopCommon_t (const uint8_t *data, int *bytecount, ESC_ControlLoopCommon_t *user)
Decode a ESC_ControlLoopCommon_t from a byte array.
Macro Definition Documentation
getMaxLengthOfESC_ControlLoopCommon_t
#define getMaxLengthOfESC_ControlLoopCommon_t () (11)
return the maximum encoded length for the ESC_ControlLoopCommon_t structure
Definition at line 244 of file ESCDefines.h.
getMaxLengthOfESC_DebugPackets_t
#define getMaxLengthOfESC_DebugPackets_t () (2)
return the maximum encoded length for the ESC_DebugPackets_t structure
Definition at line 221 of file ESCDefines.h.
getMaxLengthOfESC_ErrorBits_t
#define getMaxLengthOfESC_ErrorBits_t () (2)
return the maximum encoded length for the ESC_ErrorBits_t structure
Definition at line 152 of file ESCDefines.h.
getMaxLengthOfESC_ExtendedErrorBits_t
#define getMaxLengthOfESC_ExtendedErrorBits_t () (1)
return the maximum encoded length for the ESC_ExtendedErrorBits_t structure
Definition at line 164 of file ESCDefines.h.
getMaxLengthOfESC_ExtendedWarningBits_t
#define getMaxLengthOfESC_ExtendedWarningBits_t () (2)
return the maximum encoded length for the ESC_ExtendedWarningBits_t structure
Definition at line 122 of file ESCDefines.h.
getMaxLengthOfESC_StatusBits_t
#define getMaxLengthOfESC_StatusBits_t () (3)
return the maximum encoded length for the ESC_StatusBits_t structure
Definition at line 68 of file ESCDefines.h.
getMaxLengthOfESC_TelemetryPackets_t
#define getMaxLengthOfESC_TelemetryPackets_t () (1)
return the maximum encoded length for the ESC_TelemetryPackets_t structure
Definition at line 192 of file ESCDefines.h.
getMaxLengthOfESC_WarningBits_t
#define getMaxLengthOfESC_WarningBits_t () (2)
return the maximum encoded length for the ESC_WarningBits_t structure
Definition at line 110 of file ESCDefines.h.
getMinLengthOfESC_ControlLoopCommon_t
#define getMinLengthOfESC_ControlLoopCommon_t () (8)
return the minimum encoded length for the ESC_ControlLoopCommon_t structure
Definition at line 241 of file ESCDefines.h.
getMinLengthOfESC_DebugPackets_t
#define getMinLengthOfESC_DebugPackets_t () (1)
return the minimum encoded length for the ESC_DebugPackets_t structure
Definition at line 218 of file ESCDefines.h.
getMinLengthOfESC_ErrorBits_t
#define getMinLengthOfESC_ErrorBits_t () (2)
return the minimum encoded length for the ESC_ErrorBits_t structure
Definition at line 149 of file ESCDefines.h.
getMinLengthOfESC_ExtendedErrorBits_t
#define getMinLengthOfESC_ExtendedErrorBits_t () 0
return the minimum encoded length for the ESC_ExtendedErrorBits_t structure
Definition at line 161 of file ESCDefines.h.
getMinLengthOfESC_ExtendedWarningBits_t
#define getMinLengthOfESC_ExtendedWarningBits_t () 0
return the minimum encoded length for the ESC_ExtendedWarningBits_t structure
Definition at line 119 of file ESCDefines.h.
getMinLengthOfESC_StatusBits_t
#define getMinLengthOfESC_StatusBits_t () (3)
return the minimum encoded length for the ESC_StatusBits_t structure
Definition at line 65 of file ESCDefines.h.
getMinLengthOfESC_TelemetryPackets_t
#define getMinLengthOfESC_TelemetryPackets_t () (1)
return the minimum encoded length for the ESC_TelemetryPackets_t structure
Definition at line 189 of file ESCDefines.h.
getMinLengthOfESC_WarningBits_t
#define getMinLengthOfESC_WarningBits_t () (2)
return the minimum encoded length for the ESC_WarningBits_t structure
Definition at line 107 of file ESCDefines.h.
Function Documentation
decodeESC_ControlLoopCommon_t()
int decodeESC_ControlLoopCommon_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_ControlLoopCommon_t * _pg_user)
Decode a ESC_ControlLoopCommon_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 780 of file ESCDefines.c.
Referenced by decodeESC_RPMControlLoopSettings_t(), decodeESC_RPMControlLoopSettingsPacketStructure(), decodeESC_VoltageControlLoopSettingsPacket(), and decodeESC_VoltageControlLoopSettingsPacketStructure().
decodeESC_DebugPackets_t()
int decodeESC_DebugPackets_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_DebugPackets_t * _pg_user)
Decode a ESC_DebugPackets_t from a byte array.
These bits are used to select which debug packets are transmitted at high-frequency by the ESC
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 687 of file ESCDefines.c.
decodeESC_ErrorBits_t()
int decodeESC_ErrorBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_ErrorBits_t * _pg_user)
Decode a ESC_ErrorBits_t from a byte array.
The error bits enumerate critical system errors that will cause the ESC to stop functioning until the error cases are alleviated
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 460 of file ESCDefines.c.
Referenced by decodeESC_WarningErrorStatusPacket().
decodeESC_ExtendedErrorBits_t()
int decodeESC_ExtendedErrorBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_ErrorBits_t * _pg_user)
Decode a ESC_ExtendedErrorBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 529 of file ESCDefines.c.
Referenced by decodeESC_WarningErrorStatusPacket().
decodeESC_ExtendedWarningBits_t()
int decodeESC_ExtendedWarningBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_WarningBits_t * _pg_user)
Decode a ESC_ExtendedWarningBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 376 of file ESCDefines.c.
Referenced by decodeESC_WarningErrorStatusPacket().
decodeESC_StatusBits_t()
int decodeESC_StatusBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_StatusBits_t * _pg_user)
Decode a ESC_StatusBits_t from a byte array.
The status of the ESC is represented using these status bits. ESC system functionality can be quickly determined using these bits
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 118 of file ESCDefines.c.
Referenced by decodeESC_StatusAPacket(), and decodeESC_StatusAPacketStructure().
decodeESC_TelemetryPackets_t()
int decodeESC_TelemetryPackets_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_TelemetryPackets_t * _pg_user)
Decode a ESC_TelemetryPackets_t from a byte array.
These bits are used to determine which packets are automatically transmitted as telemetry data by the ESC. Only the packets described here can be configured as telemetry packets
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 596 of file ESCDefines.c.
Referenced by decodeESC_TelemetryConfig_t(), decodeESC_TelemetryConfigPacket(), and decodeESC_TelemetryConfigPacketStructure().
decodeESC_WarningBits_t()
int decodeESC_WarningBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_WarningBits_t * _pg_user)
Decode a ESC_WarningBits_t from a byte array.
The warning bits enumerate various system warnings/errors of which the user (or user software) should be made aware. These warning bits are transmitted in the telemetry packets such that user software is aware of any these warning conditions and can poll the ESC for particular packets if any further information is needed. The ESC will continue to function in the case of a warning state
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 277 of file ESCDefines.c.
Referenced by decodeESC_WarningErrorStatusPacket().
encodeESC_ControlLoopCommon_t()
void encodeESC_ControlLoopCommon_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_ControlLoopCommon_t * _pg_user)
Encode a ESC_ControlLoopCommon_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 735 of file ESCDefines.c.
Referenced by encodeESC_RPMControlLoopSettings_t(), encodeESC_RPMControlLoopSettingsPacketStructure(), encodeESC_VoltageControlLoopSettingsPacket(), and encodeESC_VoltageControlLoopSettingsPacketStructure().
encodeESC_DebugPackets_t()
void encodeESC_DebugPackets_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_DebugPackets_t * _pg_user)
Encode a ESC_DebugPackets_t into a byte array.
These bits are used to select which debug packets are transmitted at high-frequency by the ESC
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 639 of file ESCDefines.c.
encodeESC_ErrorBits_t()
void encodeESC_ErrorBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_ErrorBits_t * _pg_user)
Encode a ESC_ErrorBits_t into a byte array.
The error bits enumerate critical system errors that will cause the ESC to stop functioning until the error cases are alleviated
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 412 of file ESCDefines.c.
Referenced by encodeESC_WarningErrorStatusPacket().
encodeESC_ExtendedErrorBits_t()
void encodeESC_ExtendedErrorBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_ErrorBits_t * _pg_user)
Encode a ESC_ExtendedErrorBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 508 of file ESCDefines.c.
Referenced by encodeESC_WarningErrorStatusPacket().
encodeESC_ExtendedWarningBits_t()
void encodeESC_ExtendedWarningBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_WarningBits_t * _pg_user)
Encode a ESC_ExtendedWarningBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 343 of file ESCDefines.c.
Referenced by encodeESC_WarningErrorStatusPacket().
encodeESC_StatusBits_t()
void encodeESC_StatusBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_StatusBits_t * _pg_user)
Encode a ESC_StatusBits_t into a byte array.
The status of the ESC is represented using these status bits. ESC system functionality can be quickly determined using these bits
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 35 of file ESCDefines.c.
Referenced by encodeESC_StatusAPacket(), and encodeESC_StatusAPacketStructure().
encodeESC_TelemetryPackets_t()
void encodeESC_TelemetryPackets_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_TelemetryPackets_t * _pg_user)
Encode a ESC_TelemetryPackets_t into a byte array.
These bits are used to determine which packets are automatically transmitted as telemetry data by the ESC. Only the packets described here can be configured as telemetry packets
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 553 of file ESCDefines.c.
Referenced by encodeESC_TelemetryConfig_t(), encodeESC_TelemetryConfigPacket(), and encodeESC_TelemetryConfigPacketStructure().
encodeESC_WarningBits_t()
void encodeESC_WarningBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_WarningBits_t * _pg_user)
Encode a ESC_WarningBits_t into a byte array.
The warning bits enumerate various system warnings/errors of which the user (or user software) should be made aware. These warning bits are transmitted in the telemetry packets such that user software is aware of any these warning conditions and can poll the ESC for particular packets if any further information is needed. The ESC will continue to function in the case of a warning state
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 206 of file ESCDefines.c.
Referenced by encodeESC_WarningErrorStatusPacket().