APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/ESCDefines.c File Reference
ESCDefines.c File Reference
#include "ESCDefines.h"
#include "fielddecode.h"
#include "fieldencode.h"
#include "scaleddecode.h"
#include "scaledencode.h"
Functions
void encodeESC_StatusBits_t (uint8_t *_pg_data, int *_pg_bytecount, const ESC_StatusBits_t *_pg_user)
Encode a ESC_StatusBits_t into a byte array.
int decodeESC_StatusBits_t (const uint8_t *_pg_data, int *_pg_bytecount, ESC_StatusBits_t *_pg_user)
Decode a ESC_StatusBits_t from a byte array.
void encodeESC_WarningBits_t (uint8_t *_pg_data, int *_pg_bytecount, const ESC_WarningBits_t *_pg_user)
Encode a ESC_WarningBits_t into a byte array.
int decodeESC_WarningBits_t (const uint8_t *_pg_data, int *_pg_bytecount, ESC_WarningBits_t *_pg_user)
Decode a ESC_WarningBits_t from a byte array.
void encodeESC_ExtendedWarningBits_t (uint8_t *_pg_data, int *_pg_bytecount, const ESC_WarningBits_t *_pg_user)
Encode a ESC_ExtendedWarningBits_t into a byte array.
int decodeESC_ExtendedWarningBits_t (const uint8_t *_pg_data, int *_pg_bytecount, ESC_WarningBits_t *_pg_user)
Decode a ESC_ExtendedWarningBits_t from a byte array.
void encodeESC_ErrorBits_t (uint8_t *_pg_data, int *_pg_bytecount, const ESC_ErrorBits_t *_pg_user)
Encode a ESC_ErrorBits_t into a byte array.
int decodeESC_ErrorBits_t (const uint8_t *_pg_data, int *_pg_bytecount, ESC_ErrorBits_t *_pg_user)
Decode a ESC_ErrorBits_t from a byte array.
void encodeESC_ExtendedErrorBits_t (uint8_t *_pg_data, int *_pg_bytecount, const ESC_ErrorBits_t *_pg_user)
Encode a ESC_ExtendedErrorBits_t into a byte array.
int decodeESC_ExtendedErrorBits_t (const uint8_t *_pg_data, int *_pg_bytecount, ESC_ErrorBits_t *_pg_user)
Decode a ESC_ExtendedErrorBits_t from a byte array.
void encodeESC_TelemetryPackets_t (uint8_t *_pg_data, int *_pg_bytecount, const ESC_TelemetryPackets_t *_pg_user)
Encode a ESC_TelemetryPackets_t into a byte array.
int decodeESC_TelemetryPackets_t (const uint8_t *_pg_data, int *_pg_bytecount, ESC_TelemetryPackets_t *_pg_user)
Decode a ESC_TelemetryPackets_t from a byte array.
void encodeESC_DebugPackets_t (uint8_t *_pg_data, int *_pg_bytecount, const ESC_DebugPackets_t *_pg_user)
Encode a ESC_DebugPackets_t into a byte array.
int decodeESC_DebugPackets_t (const uint8_t *_pg_data, int *_pg_bytecount, ESC_DebugPackets_t *_pg_user)
Decode a ESC_DebugPackets_t from a byte array.
void encodeESC_ControlLoopCommon_t (uint8_t *_pg_data, int *_pg_bytecount, const ESC_ControlLoopCommon_t *_pg_user)
Encode a ESC_ControlLoopCommon_t into a byte array.
int decodeESC_ControlLoopCommon_t (const uint8_t *_pg_data, int *_pg_bytecount, ESC_ControlLoopCommon_t *_pg_user)
Decode a ESC_ControlLoopCommon_t from a byte array.
Function Documentation
decodeESC_ControlLoopCommon_t()
int decodeESC_ControlLoopCommon_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_ControlLoopCommon_t * _pg_user)
Decode a ESC_ControlLoopCommon_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 780 of file ESCDefines.c.
Referenced by decodeESC_RPMControlLoopSettings_t(), decodeESC_RPMControlLoopSettingsPacketStructure(), decodeESC_VoltageControlLoopSettingsPacket(), and decodeESC_VoltageControlLoopSettingsPacketStructure().
decodeESC_DebugPackets_t()
int decodeESC_DebugPackets_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_DebugPackets_t * _pg_user)
Decode a ESC_DebugPackets_t from a byte array.
These bits are used to select which debug packets are transmitted at high-frequency by the ESC
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 687 of file ESCDefines.c.
decodeESC_ErrorBits_t()
int decodeESC_ErrorBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_ErrorBits_t * _pg_user)
Decode a ESC_ErrorBits_t from a byte array.
The error bits enumerate critical system errors that will cause the ESC to stop functioning until the error cases are alleviated
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 460 of file ESCDefines.c.
Referenced by decodeESC_WarningErrorStatusPacket().
decodeESC_ExtendedErrorBits_t()
int decodeESC_ExtendedErrorBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_ErrorBits_t * _pg_user)
Decode a ESC_ExtendedErrorBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 529 of file ESCDefines.c.
Referenced by decodeESC_WarningErrorStatusPacket().
decodeESC_ExtendedWarningBits_t()
int decodeESC_ExtendedWarningBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_WarningBits_t * _pg_user)
Decode a ESC_ExtendedWarningBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 376 of file ESCDefines.c.
Referenced by decodeESC_WarningErrorStatusPacket().
decodeESC_StatusBits_t()
int decodeESC_StatusBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_StatusBits_t * _pg_user)
Decode a ESC_StatusBits_t from a byte array.
The status of the ESC is represented using these status bits. ESC system functionality can be quickly determined using these bits
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 118 of file ESCDefines.c.
Referenced by decodeESC_StatusAPacket(), and decodeESC_StatusAPacketStructure().
decodeESC_TelemetryPackets_t()
int decodeESC_TelemetryPackets_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_TelemetryPackets_t * _pg_user)
Decode a ESC_TelemetryPackets_t from a byte array.
These bits are used to determine which packets are automatically transmitted as telemetry data by the ESC. Only the packets described here can be configured as telemetry packets
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 596 of file ESCDefines.c.
Referenced by decodeESC_TelemetryConfig_t(), decodeESC_TelemetryConfigPacket(), and decodeESC_TelemetryConfigPacketStructure().
decodeESC_WarningBits_t()
int decodeESC_WarningBits_t (const uint8_t * _pg_data, int * _pg_bytecount, ESC_WarningBits_t * _pg_user)
Decode a ESC_WarningBits_t from a byte array.
The warning bits enumerate various system warnings/errors of which the user (or user software) should be made aware. These warning bits are transmitted in the telemetry packets such that user software is aware of any these warning conditions and can poll the ESC for particular packets if any further information is needed. The ESC will continue to function in the case of a warning state
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 277 of file ESCDefines.c.
Referenced by decodeESC_WarningErrorStatusPacket().
encodeESC_ControlLoopCommon_t()
void encodeESC_ControlLoopCommon_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_ControlLoopCommon_t * _pg_user)
Encode a ESC_ControlLoopCommon_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 735 of file ESCDefines.c.
Referenced by encodeESC_RPMControlLoopSettings_t(), encodeESC_RPMControlLoopSettingsPacketStructure(), encodeESC_VoltageControlLoopSettingsPacket(), and encodeESC_VoltageControlLoopSettingsPacketStructure().
encodeESC_DebugPackets_t()
void encodeESC_DebugPackets_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_DebugPackets_t * _pg_user)
Encode a ESC_DebugPackets_t into a byte array.
These bits are used to select which debug packets are transmitted at high-frequency by the ESC
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 639 of file ESCDefines.c.
encodeESC_ErrorBits_t()
void encodeESC_ErrorBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_ErrorBits_t * _pg_user)
Encode a ESC_ErrorBits_t into a byte array.
The error bits enumerate critical system errors that will cause the ESC to stop functioning until the error cases are alleviated
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 412 of file ESCDefines.c.
Referenced by encodeESC_WarningErrorStatusPacket().
encodeESC_ExtendedErrorBits_t()
void encodeESC_ExtendedErrorBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_ErrorBits_t * _pg_user)
Encode a ESC_ExtendedErrorBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 508 of file ESCDefines.c.
Referenced by encodeESC_WarningErrorStatusPacket().
encodeESC_ExtendedWarningBits_t()
void encodeESC_ExtendedWarningBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_WarningBits_t * _pg_user)
Encode a ESC_ExtendedWarningBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 343 of file ESCDefines.c.
Referenced by encodeESC_WarningErrorStatusPacket().
encodeESC_StatusBits_t()
void encodeESC_StatusBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_StatusBits_t * _pg_user)
Encode a ESC_StatusBits_t into a byte array.
The status of the ESC is represented using these status bits. ESC system functionality can be quickly determined using these bits
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 35 of file ESCDefines.c.
Referenced by encodeESC_StatusAPacket(), and encodeESC_StatusAPacketStructure().
encodeESC_TelemetryPackets_t()
void encodeESC_TelemetryPackets_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_TelemetryPackets_t * _pg_user)
Encode a ESC_TelemetryPackets_t into a byte array.
These bits are used to determine which packets are automatically transmitted as telemetry data by the ESC. Only the packets described here can be configured as telemetry packets
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 553 of file ESCDefines.c.
Referenced by encodeESC_TelemetryConfig_t(), encodeESC_TelemetryConfigPacket(), and encodeESC_TelemetryConfigPacketStructure().
encodeESC_WarningBits_t()
void encodeESC_WarningBits_t (uint8_t * _pg_data, int * _pg_bytecount, const ESC_WarningBits_t * _pg_user)
Encode a ESC_WarningBits_t into a byte array.
The warning bits enumerate various system warnings/errors of which the user (or user software) should be made aware. These warning bits are transmitted in the telemetry packets such that user software is aware of any these warning conditions and can poll the ESC for particular packets if any further information is needed. The ESC will continue to function in the case of a warning state
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 206 of file ESCDefines.c.
Referenced by encodeESC_WarningErrorStatusPacket().