APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/ESCVelocityProtocol.h File Reference
ESCVelocityProtocol.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
Macros
#define getESCVelocityApi() 88
#define getESCVelocityVersion() "3.70"
Enumerations
enum ESCDisableSequence { ESC_DISABLE_A = 0xAA , ESC_DISABLE_B = 0xC3 }
enum ESCEnableSequence { ESC_ENABLE_A = 0xAA , ESC_ENABLE_B = 0x3C }
enum ESCOperatingModes {
ESC_MODE_STANDBY = 0x00 , ESC_MODE_PWM , ESC_MODE_RPM , ESC_MODE_VOLT ,
ESC_VALID_MODES
}
enum ESCCommandSources { ESC_COMMAND_SOURCE_NONE = 0x00 , ESC_COMMAND_SOURCE_CAN , ESC_COMMAND_SOURCE_PWM }
enum ESCMotorTemperatureSensor {
ESC_MOTOR_TEMP_SENSOR_OFF = 0x00 , ESC_MOTOR_TEMP_SENSOR_KTY84 , ESC_MOTOR_TEMP_SENSOR_KTY83 , ESC_MOTOR_TEMP_SENSOR_NTC_SH ,
ESC_MOTOR_TEMP_SENSOR_NTC_BETA
}
enum ESCMotorDirection { ESC_MOTOR_DIR_ABC = 0 , ESC_MOTOR_DIR_ACB = 1 , ESC_MOTOR_DIR_OTHER = 3 }
enum ESCHallSensorMode { ESC_HALL_MODE_SENSORLESS = 0 , ESC_HALL_MODE_SENSORED = 1 , ESC_HALL_MODE_HYBRID = 2 }
enum ESCAFWModes { ESC_AFW_MODE_OFF = 0 , ESC_AFW_MODE_ON = 1 , ESC_AFW_MODE_DYNAMIC = 2 , ESC_AFW_MODE_OTHER = 3 }
enum ESCPWMFreqModes { ESC_PWM_FREQ_FIXED = 0 , ESC_PWM_FREQ_RAMP = 1 , ESC_PWM_FREQ_OTHER = 3 }
enum ESCTimingAdvanceModes { ESC_TIMING_ADVANCE_MODE_FIXED = 0 , ESC_TIMING_ADVANCE_MODE_RAMP = 1 , ESC_TIMING_ADVANCE_MODE_OTHER = 3 }
enum ESCProtectionActions { ESC_PROTECTION_WARNING = 0 , ESC_PROTECTION_FOLDBACK = 1 , ESC_PROTECTION_DISABLE = 2 , ESC_PROTECTION_INVALID = 7 }
enum ESCBeepModes { ESC_BEEP_NONE = 0b00 , ESC_BEEP_STATUS = 0b01 , ESC_BEEP_ERROR = 0b10 , ESC_BEEP_ALL = 0b11 }
enum ESCStandbyCause {
ESC_STANDBY_CAUSE_CMD = 0x0001 , ESC_STANDBY_CAUSE_INHIBIT = 0x0002 , ESC_STANDBY_CAUSE_TIMEOUT = 0x0004 , ESC_STANDBY_CAUSE_HALL_SENSOR_ERROR = 0x0008 ,
ESC_STANDBY_CAUSE_INVALID_CMD = 0x0010 , ESC_STANDBY_CAUSE_PWM_ARM = 0x0020 , ESC_STANDBY_CAUSE_FAILED_START = 0x0040 , ESC_STANDBY_CAUSE_MIN_CMD = 0x0080 ,
ESC_STANDBY_CAUSE_FAILED_RESYNC = 0x0100 , ESC_STANDBY_CAUSE_UNEXPECTED = 0x0200 , ESC_STANDBY_CAUSE_RESET = 0x8000
}
enum ESCDisableCause {
ESC_DISABLE_CAUSE_NONE = 0x0000 , ESC_DISABLE_CAUSE_CAN_CMD = 0x0001 , ESC_DISABLE_CAUSE_PWM_TIMEOUT = 0x0002 , ESC_DISABLE_CAUSE_HARDWARE = 0x0004 ,
ESC_DISABLE_CAUSE_OVERCURRENT = 0x0008 , ESC_DISABLE_CAUSE_OVERSPEED = 0x0010 , ESC_DISABLE_CAUSE_OVERTEMP = 0x0020 , ESC_DISABLE_CAUSE_UNDERVOLTAGE = 0x0040 ,
ESC_DISABLE_CAUSE_FAILED_START = 0x0080 , ESC_DISABLE_CAUSE_COMMUTATION_ERROR = 0x0100 , ESC_DISABLE_CAUSE_PHASE_VOLTAGE = 0x0200 , ESC_DISABLE_CAUSE_REGEN_CURRENT = 0x0400 ,
ESC_DISABLE_CAUSE_INVALID_STATE = 0x2000 , ESC_DISABLE_CAUSE_RESET = 0x8000
}
enum ESCMotorOffCause {
ESC_MOTOR_OFF_STANDBY = 0x0001 , ESC_MOTOR_OFF_BEEP = 0x0002 , ESC_MOTOR_OFF_INITIALISE = 0x0004 , ESC_MOTOR_OFF_INHIBITED = 0x0010 ,
ESC_MOTOR_OFF_THROTTLE_MIN = 0x0020 , ESC_MOTOR_OFF_NOT_RUNNING = 0x0040 , ESC_MOTOR_OFF_FAILED_START = 0x0080 , ESC_MOTOR_OFF_INVALID = 0x8000
}
enum ESCFailedStartCause {
ESC_FAILED_START_CAUSE_RESET = 0x0000 , ESC_FAILED_START_CAUSE_TIMEOUT = 0x0001 , ESC_FAILED_START_CAUSE_OVERSPEED = 0x0002 , ESC_FAILED_START_CAUSE_OVERCURRENT = 0x0004 ,
ESC_FAILED_START_CAUSE_SPIN_REVERSED = 0x0010 , ESC_FAILED_START_CAUSE_SPIN_TOO_FAST = 0x0020 , ESC_FAILED_START_CAUSE_INVALID = 0x8000
}
enum ESCMultiCommandPackets {
PKT_ESC_SETPOINT_1 = 0 , PKT_ESC_SETPOINT_2 , PKT_ESC_SETPOINT_3 , PKT_ESC_SETPOINT_4 ,
PKT_ESC_SETPOINT_5 , PKT_ESC_SETPOINT_6 , PKT_ESC_SETPOINT_7 , PKT_ESC_SETPOINT_8 ,
PKT_ESC_SETPOINT_9 , PKT_ESC_SETPOINT_10 , PKT_ESC_SETPOINT_11 , PKT_ESC_SETPOINT_12 ,
PKT_ESC_SETPOINT_13 , PKT_ESC_SETPOINT_14 , PKT_ESC_SETPOINT_15 , PKT_ESC_SETPOINT_16
}
enum ESCCommandPackets {
PKT_ESC_PWM_CMD = 0x10 , PKT_ESC_RPM_CMD , PKT_ESC_VOLT_CMD , PKT_ESC_DISABLE = 0x20 ,
PKT_ESC_STANDBY
}
enum ESCStatusPackets {
PKT_ESC_STATUS_A = 0x80 , PKT_ESC_STATUS_B , PKT_ESC_STATUS_C , PKT_ESC_STATUS_D ,
PKT_ESC_ACCELEROMETER = 0x88
}
enum ESCPackets {
PKT_ESC_SYSTEM_CMD = 0x50 , PKT_ESC_SET_TITLE = 0x51 , PKT_ESC_CONTROL_LOOP_DATA = 0x8A , PKT_ESC_HALL_SENSOR_INFO = 0x8C ,
PKT_ESC_WARNINGS_ERRORS = 0x86 , PKT_ESC_MOTOR_FLAGS = 0x87 , PKT_ESC_EVENT = 0x8D , PKT_ESC_SERIAL_NUMBER = 0x90 ,
PKT_ESC_TITLE = 0x91 , PKT_ESC_FIRMWARE = 0x92 , PKT_ESC_SYSTEM_INFO = 0x93 , PKT_ESC_TELEMETRY_SETTINGS = 0x94 ,
PKT_ESC_EEPROM = 0x95 , PKT_ESC_EXTRA = 0x96 , PKT_ESC_MOTOR_TEMP_SENSOR = 0x97 , PKT_ESC_COMMISSIONING = 0x99 ,
PKT_ESC_TELLTALES = 0x9A , PKT_ESC_GIT_HASH = 0x9B , PKT_ESC_LEGACY_MOTOR_STATUS = 0xA0 , PKT_ESC_LEGACY_MOTOR_SETTINGS = 0xA5 ,
PKT_ESC_LEGACY_MOTOR_SETTINGS_2 = 0xA6 , PKT_ESC_LEGACY_MOTOR_FIRMWARE = 0xAA , PKT_ESC_MOTOR_SETTINGS = 0xA7 , PKT_ESC_MOTOR_STARTING = 0xA8 ,
PKT_ESC_MOTOR_PARAMETERS = 0xA9 , PKT_ESC_MOTOR_HALL_CONFIG = 0xAB , PKT_ESC_CONFIG = 0xB0 , PKT_ESC_WARNINGS = 0xB1 ,
PKT_ESC_PROTECTION_LEVELS = 0xB2 , PKT_ESC_PROTECTION_ACTIONS = 0xB3 , PKT_ESC_VOLT_LOOP_SETTINGS = 0xB4 , PKT_ESC_RPM_LOOP_SETTINGS = 0xB5 ,
PKT_ESC_STARTING_SETTINGS = 0xB6 , PKT_ESC_CURRENT_CALIBRATION = 0xB7 , PKT_ESC_IO_TABLE_SETTINGS = 0xC0 , PKT_ESC_IO_TABLE_ELEMENT = 0xC1 ,
PKT_ESC_THROTTLE_CURVE = 0xC2 , PKT_ESC_PWM_INPUT_CALIBRATION = 0xC3 , PKT_ESC_BULK_TRANSFER = 0xF0 , PKT_ESC_DRONECAN_SETTINGS = 0xFA
}
enum ESCSystemCommands {
CMD_ESC_SET_NODE_ID = 0x50 , CMD_ESC_SET_USER_ID_A , CMD_ESC_SET_USER_ID_B , CMD_ESC_TARE_CURRENT = 0x60 ,
CMD_ESC_IDENTIFY = 0x70 , CMD_ESC_SET_MOTOR_DIRECTION = 0x90 , CMD_ESC_REQUEST_HF_DATA = 0xB0 , CMD_ESC_CONFIGURE_IO_MAP = 0xC0 ,
CMD_ESC_CONFIGURE_IO_ELEMENT , CMD_ESC_RESET_SETTINGS = 0xD0 , CMD_ESC_ENTER_DEBUG = 0xDE , CMD_ESC_EXIT_DEBUG ,
CMD_ESC_UNLOCK_SETTINGS = 0xF5 , CMD_ESC_LOCK_SETTINGS = 0xF6 , CMD_ESC_VALIDATE_SETTINGS = 0xF7 , CMD_ESC_RESET_MOTOR_RUN_TIME = 0xFA ,
CMD_ESC_ENTER_BOOTLOADER = 0xFB , CMD_ESC_RESET
}
enum CANProtocols { CAN_PROTOCOL_PICCOLO = 0x00 , CAN_PROTOCOL_DRONECAN = 0x01 , CAN_PROTOCOL_NONE = 0xFF }
enum CANBaudRates {
CAN_BAUD_RATES_INVALID = 0x00 , CAN_BAUD_RATES_1000K , CAN_BAUD_RATES_500K , CAN_BAUD_RATES_250K ,
CAN_BAUD_RATES_125K , CAN_BAUD_RATES_100K , CAN_BAUD_RATES_50K
}
Functions
const char * ESCOperatingModes_EnumLabel (int value)
Lookup label for 'ESCOperatingModes' enum entry.
const char * ESCCommandSources_EnumLabel (int value)
Lookup label for 'ESCCommandSources' enum entry.
const char * ESCMotorTemperatureSensor_EnumLabel (int value)
Lookup label for 'ESCMotorTemperatureSensor' enum entry.
const char * ESCMotorDirection_EnumLabel (int value)
Lookup label for 'ESCMotorDirection' enum entry.
const char * ESCHallSensorMode_EnumLabel (int value)
Lookup label for 'ESCHallSensorMode' enum entry.
const char * ESCAFWModes_EnumLabel (int value)
Lookup label for 'ESCAFWModes' enum entry.
const char * ESCPWMFreqModes_EnumLabel (int value)
Lookup label for 'ESCPWMFreqModes' enum entry.
const char * ESCTimingAdvanceModes_EnumLabel (int value)
Lookup label for 'ESCTimingAdvanceModes' enum entry.
const char * ESCProtectionActions_EnumLabel (int value)
Lookup label for 'ESCProtectionActions' enum entry.
const char * ESCBeepModes_EnumLabel (int value)
Lookup label for 'ESCBeepModes' enum entry.
const char * ESCStandbyCause_EnumLabel (int value)
Lookup label for 'ESCStandbyCause' enum entry.
const char * ESCDisableCause_EnumLabel (int value)
Lookup label for 'ESCDisableCause' enum entry.
const char * ESCMotorOffCause_EnumLabel (int value)
Lookup label for 'ESCMotorOffCause' enum entry.
const char * ESCFailedStartCause_EnumLabel (int value)
Lookup label for 'ESCFailedStartCause' enum entry.
const char * ESCMultiCommandPackets_EnumLabel (int value)
Lookup label for 'ESCMultiCommandPackets' enum entry.
const char * ESCCommandPackets_EnumLabel (int value)
Lookup label for 'ESCCommandPackets' enum entry.
const char * ESCStatusPackets_EnumLabel (int value)
Lookup label for 'ESCStatusPackets' enum entry.
const char * ESCPackets_EnumLabel (int value)
Lookup label for 'ESCPackets' enum entry.
const char * ESCSystemCommands_EnumLabel (int value)
Lookup label for 'ESCSystemCommands' enum entry.
const char * CANProtocols_EnumLabel (int value)
Lookup label for 'CANProtocols' enum entry.
const char * CANBaudRates_EnumLabel (int value)
Lookup label for 'CANBaudRates' enum entry.
uint8_t * getESCVelocityPacketData (void *pkt)
const uint8_t * getESCVelocityPacketDataConst (const void *pkt)
void finishESCVelocityPacket (void *pkt, int size, uint32_t packetID)
Complete a packet after the data have been encoded.
int getESCVelocityPacketSize (const void *pkt)
uint32_t getESCVelocityPacketID (const void *pkt)
Macro Definition Documentation
getESCVelocityApi
#define getESCVelocityApi () 88
Returns
the protocol API enumeration
Definition at line 50 of file ESCVelocityProtocol.h.
getESCVelocityVersion
#define getESCVelocityVersion () "3.70"
Returns
the protocol version string
Definition at line 53 of file ESCVelocityProtocol.h.
Referenced by encodeESC_TelemetrySettingsPacket(), and encodeESC_TelemetrySettingsPacketStructure().
Enumeration Type Documentation
CANBaudRates
enum CANBaudRates
ESC CAN Baud rates
Enumerator
CAN_BAUD_RATES_INVALID
CAN_BAUD_RATES_1000K
CAN_BAUD_RATES_500K
CAN_BAUD_RATES_250K
CAN_BAUD_RATES_125K
CAN_BAUD_RATES_100K
CAN_BAUD_RATES_50K
Definition at line 440 of file ESCVelocityProtocol.h.
CANProtocols
enum CANProtocols
ESC CAN Protocols
Enumerator
CAN_PROTOCOL_PICCOLO
Piccolo CAN protocol.
CAN_PROTOCOL_DRONECAN
DroneCAN CAN protocol.
CAN_PROTOCOL_NONE
No protocol specified.
Definition at line 427 of file ESCVelocityProtocol.h.
ESCAFWModes
enum ESCAFWModes
AFW operation modes
Enumerator
ESC_AFW_MODE_OFF
AFW always off (during this motor running state)
ESC_AFW_MODE_ON
AFW always on (during this motor running state)
ESC_AFW_MODE_DYNAMIC
AFW may change state.
ESC_AFW_MODE_OTHER
Future expansion.
Definition at line 145 of file ESCVelocityProtocol.h.
ESCBeepModes
enum ESCBeepModes
Motor beep modes enumeration
Enumerator
ESC_BEEP_NONE
ESC_BEEP_STATUS
Motor status beeps only.
ESC_BEEP_ERROR
Motor error beeps only.
ESC_BEEP_ALL
All motor beeps.
Definition at line 199 of file ESCVelocityProtocol.h.
ESCCommandPackets
enum ESCCommandPackets
ESC Command Packets
Enumerator
PKT_ESC_PWM_CMD
Send a PWM (Pulse width) command to a particular ESC.
PKT_ESC_RPM_CMD
Send an RPM (Speed) command to a particular ESC.
PKT_ESC_VOLT_CMD
Send a voltage loop command to a particular ESC.
PKT_ESC_DISABLE
Send this packet to an ESC to disable the ESC.
PKT_ESC_STANDBY
Send this packet to an ESC to enable the ESC and place it in Standby mode.
Definition at line 319 of file ESCVelocityProtocol.h.
ESCCommandSources
enum ESCCommandSources
ESC Command Sources
Enumerator
ESC_COMMAND_SOURCE_NONE
No valid command has been received.
ESC_COMMAND_SOURCE_CAN
Most recent command from CAN.
ESC_COMMAND_SOURCE_PWM
Most recent command from PWM.
Definition at line 91 of file ESCVelocityProtocol.h.
ESCDisableCause
enum ESCDisableCause
ESC disable cause flags
Enumerator
ESC_DISABLE_CAUSE_NONE
Unused / blank value.
ESC_DISABLE_CAUSE_CAN_CMD
ESC is disabled by a CAN command.
ESC_DISABLE_CAUSE_PWM_TIMEOUT
PWM signal lost.
ESC_DISABLE_CAUSE_HARDWARE
Hardware enable signal deasserted.
ESC_DISABLE_CAUSE_OVERCURRENT
ESC disabled due to overcurrent.
ESC_DISABLE_CAUSE_OVERSPEED
ESC disabled due to overspeed.
ESC_DISABLE_CAUSE_OVERTEMP
ESC disabled due to overtemperature.
ESC_DISABLE_CAUSE_UNDERVOLTAGE
ESC disabled due to undervoltage.
ESC_DISABLE_CAUSE_FAILED_START
ESC disabled due to starting failure (see ESCFailedStartCause for details)
ESC_DISABLE_CAUSE_COMMUTATION_ERROR
ESC disabled due to commutation failure.
ESC_DISABLE_CAUSE_PHASE_VOLTAGE
Phase voltage issues detected.
ESC_DISABLE_CAUSE_REGEN_CURRENT
Regen current exceeded threshold.
ESC_DISABLE_CAUSE_INVALID_STATE
ESC disabled due to invalid commutation state.
ESC_DISABLE_CAUSE_RESET
ESC is disabled by processor reset.
Definition at line 234 of file ESCVelocityProtocol.h.
ESCDisableSequence
enum ESCDisableSequence
Constant values required for sending a disable (inhibit) command
Enumerator
ESC_DISABLE_A
Constant value required for disabling the ESC.
ESC_DISABLE_B
Constant value required for disabling the ESC.
Definition at line 58 of file ESCVelocityProtocol.h.
ESCEnableSequence
enum ESCEnableSequence
Constant values required for sending an enable command
Enumerator
ESC_ENABLE_A
Constant value required for enabling the ESC.
ESC_ENABLE_B
Constant value required for enabling the ESC.
Definition at line 67 of file ESCVelocityProtocol.h.
ESCFailedStartCause
enum ESCFailedStartCause
Failed start cause flags
Enumerator
ESC_FAILED_START_CAUSE_RESET
No failed start has been recorded.
ESC_FAILED_START_CAUSE_TIMEOUT
Starting procedure timed out.
ESC_FAILED_START_CAUSE_OVERSPEED
Commutation speed too high.
ESC_FAILED_START_CAUSE_OVERCURRENT
Starting current exceeded.
ESC_FAILED_START_CAUSE_SPIN_REVERSED
Motor is already spinning, in reverse direction.
ESC_FAILED_START_CAUSE_SPIN_TOO_FAST
Motor is already spinning, above maximum catch speed.
ESC_FAILED_START_CAUSE_INVALID
Definition at line 276 of file ESCVelocityProtocol.h.
ESCHallSensorMode
enum ESCHallSensorMode
Hall sensor modes
Enumerator
ESC_HALL_MODE_SENSORLESS
Sensorless control only.
ESC_HALL_MODE_SENSORED
Sensored control only.
ESC_HALL_MODE_HYBRID
Sensored starting, running below RPM threshold and where sensorless control is unreliable.
Definition at line 132 of file ESCVelocityProtocol.h.
ESCMotorDirection
enum ESCMotorDirection
Motor direction
Enumerator
ESC_MOTOR_DIR_ABC
Motor phase sequence A / B / C.
ESC_MOTOR_DIR_ACB
Motor phase sequence A / C / B.
ESC_MOTOR_DIR_OTHER
Unknown / unsupported direction.
Definition at line 119 of file ESCVelocityProtocol.h.
ESCMotorOffCause
enum ESCMotorOffCause
ESC motor OFF cause
Enumerator
ESC_MOTOR_OFF_STANDBY
Motor turned off due to system standby.
ESC_MOTOR_OFF_BEEP
Motor turned off due to beeping routine.
ESC_MOTOR_OFF_INITIALISE
Motor turned off at system initialisation.
ESC_MOTOR_OFF_INHIBITED
Motor turned off due to ESC being inhibited.
ESC_MOTOR_OFF_THROTTLE_MIN
Throttle below minimum value.
ESC_MOTOR_OFF_NOT_RUNNING
Motor does not have valid commutation.
ESC_MOTOR_OFF_FAILED_START
Starting routine failed.
ESC_MOTOR_OFF_INVALID
Definition at line 258 of file ESCVelocityProtocol.h.
ESCMotorTemperatureSensor
enum ESCMotorTemperatureSensor
ESC motor temperature sensor options
Enumerator
ESC_MOTOR_TEMP_SENSOR_OFF
No temperature sensor selected.
ESC_MOTOR_TEMP_SENSOR_KTY84
KTY84 or equivalent.
ESC_MOTOR_TEMP_SENSOR_KTY83
KTY83 or equivalent.
ESC_MOTOR_TEMP_SENSOR_NTC_SH
NTC sensor (SteinhartHart equation)
ESC_MOTOR_TEMP_SENSOR_NTC_BETA
NTC sensor (Beta equation)
Definition at line 104 of file ESCVelocityProtocol.h.
ESCMultiCommandPackets
enum ESCMultiCommandPackets
ESC Multi Command Packets
Enumerator
PKT_ESC_SETPOINT_1
This packet is used to send commands to multiple ESCs with sequential CAN IDs 1 - 4.
PKT_ESC_SETPOINT_2
This packet is used to send commands to multiple ESCs with sequential CAN IDs 5 - 8.
PKT_ESC_SETPOINT_3
This packet is used to send commands to multiple ESCs with sequential CAN IDs 9 - 12.
PKT_ESC_SETPOINT_4
This packet is used to send commands to multiple ESCs with sequential CAN IDs 13 - 16.
PKT_ESC_SETPOINT_5
This packet is used to send commands to multiple ESCs with sequential CAN IDs 17 - 20.
PKT_ESC_SETPOINT_6
This packet is used to send commands to multiple ESCs with sequential CAN IDs 21 - 24.
PKT_ESC_SETPOINT_7
This packet is used to send commands to multiple ESCs with sequential CAN IDs 25 - 28.
PKT_ESC_SETPOINT_8
This packet is used to send commands to multiple ESCs with sequential CAN IDs 29 - 32.
PKT_ESC_SETPOINT_9
This packet is used to send commands to multiple ESCs with sequential CAN IDs 33 - 36.
PKT_ESC_SETPOINT_10
This packet is used to send commands to multiple ESCs with sequential CAN IDs 37 - 40.
PKT_ESC_SETPOINT_11
This packet is used to send commands to multiple ESCs with sequential CAN IDs 41 - 44.
PKT_ESC_SETPOINT_12
This packet is used to send commands to multiple ESCs with sequential CAN IDs 45 - 48.
PKT_ESC_SETPOINT_13
This packet is used to send commands to multiple ESCs with sequential CAN IDs 49 - 52.
PKT_ESC_SETPOINT_14
This packet is used to send commands to multiple ESCs with sequential CAN IDs 53 - 56.
PKT_ESC_SETPOINT_15
This packet is used to send commands to multiple ESCs with sequential CAN IDs 57 - 60.
PKT_ESC_SETPOINT_16
This packet is used to send commands to multiple ESCs with sequential CAN IDs 61 - 64.
Definition at line 293 of file ESCVelocityProtocol.h.
ESCOperatingModes
enum ESCOperatingModes
ESC Operational Modes
Enumerator
ESC_MODE_STANDBY
ESC is in standby mode - the motor is OFF but the ESC is ready to accept motor commands.
ESC_MODE_PWM
ESC is controlling motor in open-loop mode based on a 'PWM' (Pulse Width) input.
ESC_MODE_RPM
ESC is controlling motor speed based on an RPM setpoint.
ESC_MODE_VOLT
ESC is controlling DC voltage based on a provided setpoint.
ESC_VALID_MODES
ESC mode counter.
Definition at line 76 of file ESCVelocityProtocol.h.
ESCPackets
enum ESCPackets
ESC Packets Definitions
Enumerator
PKT_ESC_SYSTEM_CMD
Send a configuration command to the ESC (followed by optional command data bytes)
PKT_ESC_SET_TITLE
Set the ESC descriptor title.
PKT_ESC_CONTROL_LOOP_DATA
Control loop output data - varies depending on the operational mode of the ESC.
PKT_ESC_HALL_SENSOR_INFO
Hall sensor information - detected pattern, advance, validity.
PKT_ESC_WARNINGS_ERRORS
ESC warning / error status information.
PKT_ESC_MOTOR_FLAGS
Motor status flags.
PKT_ESC_EVENT
Event description packet.
PKT_ESC_SERIAL_NUMBER
ESC Serial Number and User ID information.
PKT_ESC_TITLE
Human-readable string descriptor (max 8 chars) of the particular ESC.
PKT_ESC_FIRMWARE
ESC Firmware information.
PKT_ESC_SYSTEM_INFO
ESC system information packet.
PKT_ESC_TELEMETRY_SETTINGS
Telemetry packet configuration.
PKT_ESC_EEPROM
ESC non-volatile data information and settings.
PKT_ESC_EXTRA
Extra settings.
PKT_ESC_MOTOR_TEMP_SENSOR
Motor temperature sensor settings.
PKT_ESC_COMMISSIONING
ESC commissioning data (factory only)
PKT_ESC_TELLTALES
ESC telltales.
PKT_ESC_GIT_HASH
ESC firmware git hash.
PKT_ESC_LEGACY_MOTOR_STATUS
ESC motor status information.
PKT_ESC_LEGACY_MOTOR_SETTINGS
ESC motor configuration.
PKT_ESC_LEGACY_MOTOR_SETTINGS_2
ESC Motor settings information.
PKT_ESC_LEGACY_MOTOR_FIRMWARE
ESC motor control firmware information.
PKT_ESC_MOTOR_SETTINGS
Motor control settings packet.
PKT_ESC_MOTOR_STARTING
Motor starting settings packet.
PKT_ESC_MOTOR_PARAMETERS
Motor and system parameters.
PKT_ESC_MOTOR_HALL_CONFIG
Motor hall sensor configuration.
PKT_ESC_CONFIG
ESC Configuration parameters.
PKT_ESC_WARNINGS
Warning level values for various ESC parameters (legacy)
PKT_ESC_PROTECTION_LEVELS
ESC protection values.
PKT_ESC_PROTECTION_ACTIONS
ESC protection actions.
PKT_ESC_VOLT_LOOP_SETTINGS
Voltage Control Loop Settings.
PKT_ESC_RPM_LOOP_SETTINGS
RPM Control Loop Settings.
PKT_ESC_STARTING_SETTINGS
ESC auto-starting configuration for RPM mode.
PKT_ESC_CURRENT_CALIBRATION
ESC current sense calibration settings.
PKT_ESC_IO_TABLE_SETTINGS
Configuration of the Input/Output mapping.
PKT_ESC_IO_TABLE_ELEMENT
A single element of the Input/Output mapping table.
PKT_ESC_THROTTLE_CURVE
Throttle curve calibration.
PKT_ESC_PWM_INPUT_CALIBRATION
PWM input calibration.
PKT_ESC_BULK_TRANSFER
Bulk data transfer (long packets)
PKT_ESC_DRONECAN_SETTINGS
DroneCAN specific settings.
Definition at line 349 of file ESCVelocityProtocol.h.
ESCProtectionActions
enum ESCProtectionActions
ESC protection actions
Enumerator
ESC_PROTECTION_WARNING
Warning bit is set.
ESC_PROTECTION_FOLDBACK
Motor duty cycle is limited.
ESC_PROTECTION_DISABLE
ESC is disabled.
ESC_PROTECTION_INVALID
Invalid protection action.
Definition at line 185 of file ESCVelocityProtocol.h.
ESCPWMFreqModes
enum ESCPWMFreqModes
PWM operation modes
Enumerator
ESC_PWM_FREQ_FIXED
PWM frequency is the specified value.
ESC_PWM_FREQ_RAMP
ESC_PWM_FREQ_OTHER
Future expansion.
Definition at line 159 of file ESCVelocityProtocol.h.
ESCStandbyCause
enum ESCStandbyCause
ESC standby cause flags
Enumerator
ESC_STANDBY_CAUSE_CMD
ESC was put into STANDBY mode by a command.
ESC_STANDBY_CAUSE_INHIBIT
ESC was put into STANDBY mode by SW or HW inhibit.
ESC_STANDBY_CAUSE_TIMEOUT
ESC was put into STANDBY mode due to keepalive timeout.
ESC_STANDBY_CAUSE_HALL_SENSOR_ERROR
ESC was put into STANDBY mode due to a hall sensor error.
ESC_STANDBY_CAUSE_INVALID_CMD
ESC was put into STANDBY mode due to a command being invalid.
ESC_STANDBY_CAUSE_PWM_ARM
PWM arming signal detected.
ESC_STANDBY_CAUSE_FAILED_START
ESC was put into STANDBY mode due to failed starting routine.
ESC_STANDBY_CAUSE_MIN_CMD
ESC was put into STANDBY mode due to the received command below minimum threshold.
ESC_STANDBY_CAUSE_FAILED_RESYNC
ESC was put into STANDBY mode due to failed resync routine.
ESC_STANDBY_CAUSE_UNEXPECTED
ESC was put intot STANDBY mode due to an unexpected internal state.
ESC_STANDBY_CAUSE_RESET
Definition at line 213 of file ESCVelocityProtocol.h.
ESCStatusPackets
enum ESCStatusPackets
ESC Status Packets
Enumerator
PKT_ESC_STATUS_A
ESC Status A telemetry packet transmitted by the ESC at regular intervals.
PKT_ESC_STATUS_B
ESC Status B telemetry packet transmitted by the ESC at regular intervals.
PKT_ESC_STATUS_C
ESC Status C telemetry packet transmitted by the ESC at regular intervals.
PKT_ESC_STATUS_D
ECC Status D telemetry packet transmitted by the ESC at regular intervals.
PKT_ESC_ACCELEROMETER
Raw accelerometer data.
Definition at line 334 of file ESCVelocityProtocol.h.
ESCSystemCommands
enum ESCSystemCommands
ESC System Commands
Enumerator
CMD_ESC_SET_NODE_ID
Set the CAN Node ID for the target ESC.
CMD_ESC_SET_USER_ID_A
Set user ID A value.
CMD_ESC_SET_USER_ID_B
Set user ID B value.
CMD_ESC_TARE_CURRENT
Tare the current measurement.
CMD_ESC_IDENTIFY
Identify the ESC with a sequence of LED flashes / beeps.
CMD_ESC_SET_MOTOR_DIRECTION
Set the motor direction.
CMD_ESC_REQUEST_HF_DATA
Request high-frequency telemetry data.
CMD_ESC_CONFIGURE_IO_MAP
Configure the Input/Output map for the ESC.
CMD_ESC_CONFIGURE_IO_ELEMENT
Configure (or request) a particular element of the I/O map.
CMD_ESC_RESET_SETTINGS
Reset ESC settings to default parameters.
CMD_ESC_ENTER_DEBUG
Enter debug mode.
CMD_ESC_EXIT_DEBUG
Exit debug mode.
CMD_ESC_UNLOCK_SETTINGS
Unlock ESC nonvolatile settings.
CMD_ESC_LOCK_SETTINGS
Lock ESC nonvolatile settings.
CMD_ESC_VALIDATE_SETTINGS
Mark the current settings as valid.
CMD_ESC_RESET_MOTOR_RUN_TIME
Reset motor run time.
CMD_ESC_ENTER_BOOTLOADER
Enter bootloader mode.
CMD_ESC_RESET
Reset ESC.
Definition at line 399 of file ESCVelocityProtocol.h.
ESCTimingAdvanceModes
enum ESCTimingAdvanceModes
PWM operation modes
Enumerator
ESC_TIMING_ADVANCE_MODE_FIXED
Timing advance is the specified value.
ESC_TIMING_ADVANCE_MODE_RAMP
ESC_TIMING_ADVANCE_MODE_OTHER
Future expansion.
Definition at line 172 of file ESCVelocityProtocol.h.
Function Documentation
CANBaudRates_EnumLabel()
const char * CANBaudRates_EnumLabel (int value)
Lookup label for 'CANBaudRates' enum entry.
Returns
the label of a 'CANBaudRates' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 676 of file ESCVelocityProtocol.c.
CANProtocols_EnumLabel()
const char * CANProtocols_EnumLabel (int value)
Lookup label for 'CANProtocols' enum entry.
Returns
the label of a 'CANProtocols' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 654 of file ESCVelocityProtocol.c.
ESCAFWModes_EnumLabel()
const char * ESCAFWModes_EnumLabel (int value)
Lookup label for 'ESCAFWModes' enum entry.
Returns
the label of a 'ESCAFWModes' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 146 of file ESCVelocityProtocol.c.
ESCBeepModes_EnumLabel()
const char * ESCBeepModes_EnumLabel (int value)
Lookup label for 'ESCBeepModes' enum entry.
Returns
the label of a 'ESCBeepModes' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 238 of file ESCVelocityProtocol.c.
ESCCommandPackets_EnumLabel()
const char * ESCCommandPackets_EnumLabel (int value)
Lookup label for 'ESCCommandPackets' enum entry.
Returns
the label of a 'ESCCommandPackets' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 454 of file ESCVelocityProtocol.c.
ESCCommandSources_EnumLabel()
const char * ESCCommandSources_EnumLabel (int value)
Lookup label for 'ESCCommandSources' enum entry.
Returns
the label of a 'ESCCommandSources' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 54 of file ESCVelocityProtocol.c.
ESCDisableCause_EnumLabel()
const char * ESCDisableCause_EnumLabel (int value)
Lookup label for 'ESCDisableCause' enum entry.
Returns
the label of a 'ESCDisableCause' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 300 of file ESCVelocityProtocol.c.
ESCFailedStartCause_EnumLabel()
const char * ESCFailedStartCause_EnumLabel (int value)
Lookup label for 'ESCFailedStartCause' enum entry.
Returns
the label of a 'ESCFailedStartCause' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 376 of file ESCVelocityProtocol.c.
ESCHallSensorMode_EnumLabel()
const char * ESCHallSensorMode_EnumLabel (int value)
Lookup label for 'ESCHallSensorMode' enum entry.
Returns
the label of a 'ESCHallSensorMode' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 124 of file ESCVelocityProtocol.c.
ESCMotorDirection_EnumLabel()
const char * ESCMotorDirection_EnumLabel (int value)
Lookup label for 'ESCMotorDirection' enum entry.
Returns
the label of a 'ESCMotorDirection' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 102 of file ESCVelocityProtocol.c.
ESCMotorOffCause_EnumLabel()
const char * ESCMotorOffCause_EnumLabel (int value)
Lookup label for 'ESCMotorOffCause' enum entry.
Returns
the label of a 'ESCMotorOffCause' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 344 of file ESCVelocityProtocol.c.
ESCMotorTemperatureSensor_EnumLabel()
const char * ESCMotorTemperatureSensor_EnumLabel (int value)
Lookup label for 'ESCMotorTemperatureSensor' enum entry.
Returns
the label of a 'ESCMotorTemperatureSensor' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 76 of file ESCVelocityProtocol.c.
ESCMultiCommandPackets_EnumLabel()
const char * ESCMultiCommandPackets_EnumLabel (int value)
Lookup label for 'ESCMultiCommandPackets' enum entry.
Returns
the label of a 'ESCMultiCommandPackets' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 406 of file ESCVelocityProtocol.c.
ESCOperatingModes_EnumLabel()
const char * ESCOperatingModes_EnumLabel (int value)
Lookup label for 'ESCOperatingModes' enum entry.
Returns
the label of a 'ESCOperatingModes' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 28 of file ESCVelocityProtocol.c.
ESCPackets_EnumLabel()
const char * ESCPackets_EnumLabel (int value)
Lookup label for 'ESCPackets' enum entry.
Returns
the label of a 'ESCPackets' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 506 of file ESCVelocityProtocol.c.
ESCProtectionActions_EnumLabel()
const char * ESCProtectionActions_EnumLabel (int value)
Lookup label for 'ESCProtectionActions' enum entry.
Returns
the label of a 'ESCProtectionActions' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 214 of file ESCVelocityProtocol.c.
ESCPWMFreqModes_EnumLabel()
const char * ESCPWMFreqModes_EnumLabel (int value)
Lookup label for 'ESCPWMFreqModes' enum entry.
Returns
the label of a 'ESCPWMFreqModes' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 170 of file ESCVelocityProtocol.c.
ESCStandbyCause_EnumLabel()
const char * ESCStandbyCause_EnumLabel (int value)
Lookup label for 'ESCStandbyCause' enum entry.
Returns
the label of a 'ESCStandbyCause' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 262 of file ESCVelocityProtocol.c.
ESCStatusPackets_EnumLabel()
const char * ESCStatusPackets_EnumLabel (int value)
Lookup label for 'ESCStatusPackets' enum entry.
Returns
the label of a 'ESCStatusPackets' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 480 of file ESCVelocityProtocol.c.
ESCSystemCommands_EnumLabel()
const char * ESCSystemCommands_EnumLabel (int value)
Lookup label for 'ESCSystemCommands' enum entry.
Returns
the label of a 'ESCSystemCommands' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 602 of file ESCVelocityProtocol.c.
ESCTimingAdvanceModes_EnumLabel()
const char * ESCTimingAdvanceModes_EnumLabel (int value)
Lookup label for 'ESCTimingAdvanceModes' enum entry.
Returns
the label of a 'ESCTimingAdvanceModes' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 192 of file ESCVelocityProtocol.c.
finishESCVelocityPacket()
void finishESCVelocityPacket (void * pkt, int size, uint32_t packetID)
Complete a packet after the data have been encoded.
Referenced by encodeESC_AddressPacket(), encodeESC_AddressPacketStructure(), encodeESC_CommandMultipleESCsPacket(), encodeESC_ConfigPacket(), encodeESC_ConfigPacketStructure(), encodeESC_ControlLoopOutputsPacket(), encodeESC_ControlLoopOutputsPacketStructure(), encodeESC_DisablePacket(), encodeESC_EEPROMSettingsPacket(), encodeESC_EEPROMSettingsPacketStructure(), encodeESC_EnablePacket(), encodeESC_EnterBootloaderPacket(), encodeESC_FirmwarePacket(), encodeESC_FirmwarePacketStructure(), encodeESC_GitHashPacket(), encodeESC_GitHashPacketStructure(), encodeESC_HallSensorInfoPacket(), encodeESC_LockSettingsPacket(), encodeESC_MotorHallSensorConfigPacketStructure(), encodeESC_MotorParametersPacketStructure(), encodeESC_MotorStatusFlagsPacket(), encodeESC_MotorStatusFlagsPacketStructure(), encodeESC_ProtectionActionsPacket(), encodeESC_ProtectionActionsPacketStructure(), encodeESC_ProtectionValuesPacket(), encodeESC_ProtectionValuesPacketStructure(), encodeESC_PWMCommandPacket(), encodeESC_PWMInputCalibrationPacket(), encodeESC_PWMInputCalibrationPacketStructure(), encodeESC_ResetESCPacket(), encodeESC_ResetMotorRunTimePacket(), encodeESC_RPMCommandPacket(), encodeESC_RPMControlLoopSettingsPacketStructure(), encodeESC_SetMotorDirectionPacket(), encodeESC_SetNodeIDPacket(), encodeESC_SetUserIDAPacket(), encodeESC_SetUserIDBPacket(), encodeESC_StatusAPacket(), encodeESC_StatusAPacketStructure(), encodeESC_StatusBPacket(), encodeESC_StatusBPacketStructure(), encodeESC_StatusCPacket(), encodeESC_StatusCPacketStructure(), encodeESC_StatusDPacket(), encodeESC_StatusDPacketStructure(), encodeESC_SystemInfoPacket(), encodeESC_SystemInfoPacketStructure(), encodeESC_TelemetryConfigPacket(), encodeESC_TelemetryConfigPacketStructure(), encodeESC_TelemetrySettingsPacket(), encodeESC_TelemetrySettingsPacketStructure(), encodeESC_TelltaleValuesPacket(), encodeESC_TelltaleValuesPacketStructure(), encodeESC_TempSensorConfigPacket(), encodeESC_TempSensorConfigPacketStructure(), encodeESC_TitlePacket(), encodeESC_TitlePacketStructure(), encodeESC_UnlockSettingsPacket(), encodeESC_ValidateSettingsPacket(), encodeESC_VoltageCommandPacket(), encodeESC_VoltageControlLoopSettingsPacket(), encodeESC_VoltageControlLoopSettingsPacketStructure(), and encodeESC_WarningErrorStatusPacket().
getESCVelocityPacketData()
uint8_t * getESCVelocityPacketData (void * pkt)
Returns
the packet data pointer from the packet
Referenced by encodeESC_AddressPacket(), encodeESC_AddressPacketStructure(), encodeESC_CommandMultipleESCsPacket(), encodeESC_ConfigPacket(), encodeESC_ConfigPacketStructure(), encodeESC_ControlLoopOutputsPacket(), encodeESC_ControlLoopOutputsPacketStructure(), encodeESC_DisablePacket(), encodeESC_EEPROMSettingsPacket(), encodeESC_EEPROMSettingsPacketStructure(), encodeESC_EnablePacket(), encodeESC_EnterBootloaderPacket(), encodeESC_FirmwarePacket(), encodeESC_FirmwarePacketStructure(), encodeESC_GitHashPacket(), encodeESC_GitHashPacketStructure(), encodeESC_HallSensorInfoPacket(), encodeESC_LockSettingsPacket(), encodeESC_MotorHallSensorConfigPacketStructure(), encodeESC_MotorParametersPacketStructure(), encodeESC_MotorStatusFlagsPacket(), encodeESC_MotorStatusFlagsPacketStructure(), encodeESC_ProtectionActionsPacket(), encodeESC_ProtectionActionsPacketStructure(), encodeESC_ProtectionValuesPacket(), encodeESC_ProtectionValuesPacketStructure(), encodeESC_PWMCommandPacket(), encodeESC_PWMInputCalibrationPacket(), encodeESC_PWMInputCalibrationPacketStructure(), encodeESC_ResetESCPacket(), encodeESC_ResetMotorRunTimePacket(), encodeESC_RPMCommandPacket(), encodeESC_RPMControlLoopSettingsPacketStructure(), encodeESC_SetMotorDirectionPacket(), encodeESC_SetNodeIDPacket(), encodeESC_SetUserIDAPacket(), encodeESC_SetUserIDBPacket(), encodeESC_StatusAPacket(), encodeESC_StatusAPacketStructure(), encodeESC_StatusBPacket(), encodeESC_StatusBPacketStructure(), encodeESC_StatusCPacket(), encodeESC_StatusCPacketStructure(), encodeESC_StatusDPacket(), encodeESC_StatusDPacketStructure(), encodeESC_SystemInfoPacket(), encodeESC_SystemInfoPacketStructure(), encodeESC_TelemetryConfigPacket(), encodeESC_TelemetryConfigPacketStructure(), encodeESC_TelemetrySettingsPacket(), encodeESC_TelemetrySettingsPacketStructure(), encodeESC_TelltaleValuesPacket(), encodeESC_TelltaleValuesPacketStructure(), encodeESC_TempSensorConfigPacket(), encodeESC_TempSensorConfigPacketStructure(), encodeESC_TitlePacket(), encodeESC_TitlePacketStructure(), encodeESC_UnlockSettingsPacket(), encodeESC_ValidateSettingsPacket(), encodeESC_VoltageCommandPacket(), encodeESC_VoltageControlLoopSettingsPacket(), encodeESC_VoltageControlLoopSettingsPacketStructure(), and encodeESC_WarningErrorStatusPacket().
getESCVelocityPacketDataConst()
const uint8_t * getESCVelocityPacketDataConst (const void * pkt)
Returns
the packet data pointer from the packet, const
Referenced by decodeESC_AddressPacket(), decodeESC_AddressPacketStructure(), decodeESC_CommandMultipleESCsPacket(), decodeESC_ConfigPacket(), decodeESC_ConfigPacketStructure(), decodeESC_ControlLoopOutputsPacket(), decodeESC_ControlLoopOutputsPacketStructure(), decodeESC_DisablePacket(), decodeESC_EEPROMSettingsPacket(), decodeESC_EEPROMSettingsPacketStructure(), decodeESC_EnablePacket(), decodeESC_EnterBootloaderPacket(), decodeESC_FirmwarePacket(), decodeESC_FirmwarePacketStructure(), decodeESC_GitHashPacket(), decodeESC_GitHashPacketStructure(), decodeESC_HallSensorInfoPacket(), decodeESC_LockSettingsPacket(), decodeESC_MotorHallSensorConfigPacketStructure(), decodeESC_MotorParametersPacketStructure(), decodeESC_MotorStatusFlagsPacket(), decodeESC_MotorStatusFlagsPacketStructure(), decodeESC_ProtectionActionsPacket(), decodeESC_ProtectionActionsPacketStructure(), decodeESC_ProtectionValuesPacket(), decodeESC_ProtectionValuesPacketStructure(), decodeESC_PWMCommandPacket(), decodeESC_PWMInputCalibrationPacket(), decodeESC_PWMInputCalibrationPacketStructure(), decodeESC_ResetESCPacket(), decodeESC_ResetMotorRunTimePacket(), decodeESC_RPMCommandPacket(), decodeESC_RPMControlLoopSettingsPacketStructure(), decodeESC_SetMotorDirectionPacket(), decodeESC_SetNodeIDPacket(), decodeESC_SetUserIDAPacket(), decodeESC_SetUserIDBPacket(), decodeESC_StatusAPacket(), decodeESC_StatusAPacketStructure(), decodeESC_StatusBPacket(), decodeESC_StatusBPacketStructure(), decodeESC_StatusCPacket(), decodeESC_StatusCPacketStructure(), decodeESC_StatusDPacket(), decodeESC_StatusDPacketStructure(), decodeESC_SystemInfoPacket(), decodeESC_SystemInfoPacketStructure(), decodeESC_TelemetryConfigPacket(), decodeESC_TelemetryConfigPacketStructure(), decodeESC_TelemetrySettingsPacket(), decodeESC_TelemetrySettingsPacketStructure(), decodeESC_TelltaleValuesPacket(), decodeESC_TelltaleValuesPacketStructure(), decodeESC_TempSensorConfigPacket(), decodeESC_TempSensorConfigPacketStructure(), decodeESC_TitlePacket(), decodeESC_TitlePacketStructure(), decodeESC_UnlockSettingsPacket(), decodeESC_ValidateSettingsPacket(), decodeESC_VoltageCommandPacket(), decodeESC_VoltageControlLoopSettingsPacket(), decodeESC_VoltageControlLoopSettingsPacketStructure(), and decodeESC_WarningErrorStatusPacket().
getESCVelocityPacketID()
uint32_t getESCVelocityPacketID (const void * pkt)
Returns
the ID of a packet from the packet header
Referenced by decodeESC_AddressPacket(), decodeESC_AddressPacketStructure(), decodeESC_CommandMultipleESCsPacket(), decodeESC_ConfigPacket(), decodeESC_ConfigPacketStructure(), decodeESC_ControlLoopOutputsPacket(), decodeESC_ControlLoopOutputsPacketStructure(), decodeESC_DisablePacket(), decodeESC_EEPROMSettingsPacket(), decodeESC_EEPROMSettingsPacketStructure(), decodeESC_EnablePacket(), decodeESC_EnterBootloaderPacket(), decodeESC_FirmwarePacket(), decodeESC_FirmwarePacketStructure(), decodeESC_GitHashPacket(), decodeESC_GitHashPacketStructure(), decodeESC_HallSensorInfoPacket(), decodeESC_LockSettingsPacket(), decodeESC_MotorHallSensorConfigPacketStructure(), decodeESC_MotorParametersPacketStructure(), decodeESC_MotorStatusFlagsPacket(), decodeESC_MotorStatusFlagsPacketStructure(), decodeESC_ProtectionActionsPacket(), decodeESC_ProtectionActionsPacketStructure(), decodeESC_ProtectionValuesPacket(), decodeESC_ProtectionValuesPacketStructure(), decodeESC_PWMCommandPacket(), decodeESC_PWMInputCalibrationPacket(), decodeESC_PWMInputCalibrationPacketStructure(), decodeESC_ResetESCPacket(), decodeESC_ResetMotorRunTimePacket(), decodeESC_RPMCommandPacket(), decodeESC_RPMControlLoopSettingsPacketStructure(), decodeESC_SetMotorDirectionPacket(), decodeESC_SetNodeIDPacket(), decodeESC_SetUserIDAPacket(), decodeESC_SetUserIDBPacket(), decodeESC_StatusAPacket(), decodeESC_StatusAPacketStructure(), decodeESC_StatusBPacket(), decodeESC_StatusBPacketStructure(), decodeESC_StatusCPacket(), decodeESC_StatusCPacketStructure(), decodeESC_StatusDPacket(), decodeESC_StatusDPacketStructure(), decodeESC_SystemInfoPacket(), decodeESC_SystemInfoPacketStructure(), decodeESC_TelemetryConfigPacket(), decodeESC_TelemetryConfigPacketStructure(), decodeESC_TelemetrySettingsPacket(), decodeESC_TelemetrySettingsPacketStructure(), decodeESC_TelltaleValuesPacket(), decodeESC_TelltaleValuesPacketStructure(), decodeESC_TempSensorConfigPacket(), decodeESC_TempSensorConfigPacketStructure(), decodeESC_TitlePacket(), decodeESC_TitlePacketStructure(), decodeESC_UnlockSettingsPacket(), decodeESC_ValidateSettingsPacket(), decodeESC_VoltageCommandPacket(), decodeESC_VoltageControlLoopSettingsPacket(), decodeESC_VoltageControlLoopSettingsPacketStructure(), and decodeESC_WarningErrorStatusPacket().
getESCVelocityPacketSize()
int getESCVelocityPacketSize (const void * pkt)
Returns
the size of a packet from the packet header
Referenced by decodeESC_AddressPacket(), decodeESC_AddressPacketStructure(), decodeESC_CommandMultipleESCsPacket(), decodeESC_ConfigPacket(), decodeESC_ConfigPacketStructure(), decodeESC_ControlLoopOutputsPacket(), decodeESC_ControlLoopOutputsPacketStructure(), decodeESC_DisablePacket(), decodeESC_EEPROMSettingsPacket(), decodeESC_EEPROMSettingsPacketStructure(), decodeESC_EnablePacket(), decodeESC_EnterBootloaderPacket(), decodeESC_FirmwarePacket(), decodeESC_FirmwarePacketStructure(), decodeESC_GitHashPacket(), decodeESC_GitHashPacketStructure(), decodeESC_HallSensorInfoPacket(), decodeESC_LockSettingsPacket(), decodeESC_MotorHallSensorConfigPacketStructure(), decodeESC_MotorParametersPacketStructure(), decodeESC_MotorStatusFlagsPacket(), decodeESC_MotorStatusFlagsPacketStructure(), decodeESC_ProtectionActionsPacket(), decodeESC_ProtectionActionsPacketStructure(), decodeESC_ProtectionValuesPacket(), decodeESC_ProtectionValuesPacketStructure(), decodeESC_PWMCommandPacket(), decodeESC_PWMInputCalibrationPacket(), decodeESC_PWMInputCalibrationPacketStructure(), decodeESC_ResetESCPacket(), decodeESC_ResetMotorRunTimePacket(), decodeESC_RPMCommandPacket(), decodeESC_RPMControlLoopSettingsPacketStructure(), decodeESC_SetMotorDirectionPacket(), decodeESC_SetNodeIDPacket(), decodeESC_SetUserIDAPacket(), decodeESC_SetUserIDBPacket(), decodeESC_StatusAPacket(), decodeESC_StatusAPacketStructure(), decodeESC_StatusBPacket(), decodeESC_StatusBPacketStructure(), decodeESC_StatusCPacket(), decodeESC_StatusCPacketStructure(), decodeESC_StatusDPacket(), decodeESC_StatusDPacketStructure(), decodeESC_SystemInfoPacket(), decodeESC_SystemInfoPacketStructure(), decodeESC_TelemetryConfigPacket(), decodeESC_TelemetryConfigPacketStructure(), decodeESC_TelemetrySettingsPacket(), decodeESC_TelemetrySettingsPacketStructure(), decodeESC_TelltaleValuesPacket(), decodeESC_TelltaleValuesPacketStructure(), decodeESC_TempSensorConfigPacket(), decodeESC_TempSensorConfigPacketStructure(), decodeESC_TitlePacket(), decodeESC_TitlePacketStructure(), decodeESC_UnlockSettingsPacket(), decodeESC_ValidateSettingsPacket(), decodeESC_VoltageCommandPacket(), decodeESC_VoltageControlLoopSettingsPacket(), decodeESC_VoltageControlLoopSettingsPacketStructure(), and decodeESC_WarningErrorStatusPacket().