APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/fielddecode.c File Reference
fielddecode.c File Reference
#include "fielddecode.h"
Functions
void stringFromBytes (char *string, const uint8_t *bytes, int *index, int maxLength, int fixedLength)
Decode a null terminated string from a byte stream.
void bytesFromBeBytes (uint8_t *data, const uint8_t *bytes, int *index, int num)
Copy an array of bytes from a byte stream without changing the order.
void bytesFromLeBytes (uint8_t *data, const uint8_t *bytes, int *index, int num)
Copy an array of bytes from a byte stream while reversing the order.
float float32FromBeBytes (const uint8_t *bytes, int *index)
Decode a 4 byte float from a big endian byte stream.
float float32FromLeBytes (const uint8_t *bytes, int *index)
Decode a 4 byte float from a little endian byte stream.
uint32_t uint32FromBeBytes (const uint8_t *bytes, int *index)
Decode a unsigned 4 byte integer from a big endian byte stream.
uint32_t uint32FromLeBytes (const uint8_t *bytes, int *index)
Decode a unsigned 4 byte integer from a little endian byte stream.
int32_t int32FromBeBytes (const uint8_t *bytes, int *index)
Decode a signed 4 byte integer from a big endian byte stream.
int32_t int32FromLeBytes (const uint8_t *bytes, int *index)
Decode a signed 4 byte integer from a little endian byte stream.
uint32_t uint24FromBeBytes (const uint8_t *bytes, int *index)
Decode a unsigned 3 byte integer from a big endian byte stream.
uint32_t uint24FromLeBytes (const uint8_t *bytes, int *index)
Decode a unsigned 3 byte integer from a little endian byte stream.
int32_t int24FromBeBytes (const uint8_t *bytes, int *index)
Decode a signed 3 byte integer from a big endian byte stream.
int32_t int24FromLeBytes (const uint8_t *bytes, int *index)
Decode a signed 3 byte integer from a little endian byte stream.
uint16_t uint16FromBeBytes (const uint8_t *bytes, int *index)
Decode a unsigned 2 byte integer from a big endian byte stream.
uint16_t uint16FromLeBytes (const uint8_t *bytes, int *index)
Decode a unsigned 2 byte integer from a little endian byte stream.
int16_t int16FromBeBytes (const uint8_t *bytes, int *index)
Decode a signed 2 byte integer from a big endian byte stream.
int16_t int16FromLeBytes (const uint8_t *bytes, int *index)
Decode a signed 2 byte integer from a little endian byte stream.
Function Documentation
bytesFromBeBytes()
void bytesFromBeBytes (uint8_t * data, const uint8_t * bytes, int * index, int num)
Copy an array of bytes from a byte stream without changing the order.
Copy an array of bytes from a byte stream without changing the order.
Parameters
data receives the copied bytes
bytes is a pointer to the byte stream to be copied from.
index gives the location of the first byte in the byte stream, and will be incremented by num when this function is complete.
num is the number of bytes to copy
Definition at line 68 of file fielddecode.c.
bytesFromLeBytes()
void bytesFromLeBytes (uint8_t * data, const uint8_t * bytes, int * index, int num)
Copy an array of bytes from a byte stream while reversing the order.
Copy an array of bytes from a byte stream, reversing the order.
Parameters
data receives the copied bytes
bytes is a pointer to the byte stream to be copied.
index gives the location of the first byte in the byte stream, and will be incremented by num when this function is complete.
num is the number of bytes to copy
Definition at line 94 of file fielddecode.c.
float32FromBeBytes()
float float32FromBeBytes (const uint8_t * bytes, int * index)
Decode a 4 byte float from a big endian byte stream.
Decode a 4 byte float from a big endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 121 of file fielddecode.c.
Referenced by decodeECU_GovernorSettingsPacketStructure(), decodeECU_PumpSettingsPacketStructure(), decodeESC_TempSensorConfigPacket(), and decodeESC_TempSensorConfigPacketStructure().
float32FromLeBytes()
float float32FromLeBytes (const uint8_t * bytes, int * index)
Decode a 4 byte float from a little endian byte stream.
Decode a 4 byte float from a little endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 141 of file fielddecode.c.
int16FromBeBytes()
int16_t int16FromBeBytes (const uint8_t * bytes, int * index)
Decode a signed 2 byte integer from a big endian byte stream.
Decode a signed 2 byte integer from a big endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 399 of file fielddecode.c.
Referenced by decodeESC_ControlLoopOutputsPacket(), decodeESC_ControlLoopOutputsPacketStructure(), decodeESC_StatusBPacket(), decodeESC_StatusBPacketStructure(), decodeESC_TempSensorConfigPacket(), decodeESC_TempSensorConfigPacketStructure(), decodeServo_AccelerometerPacket(), decodeServo_Config_t(), decodeServo_ConfigPacket(), decodeServo_ConfigPacketStructure(), decodeServo_MultiPositionCommandPacket(), decodeServo_PositionCommandPacket(), decodeServo_StatusAPacket(), decodeServo_StatusAPacketStructure(), decodeServo_StatusBPacket(), decodeServo_StatusBPacketStructure(), decodeServo_StatusCPacket(), decodeServo_StatusCPacketStructure(), float32ScaledFrom2SignedBeBytes(), int16ScaledFrom2SignedBeBytes(), int32ScaledFrom2SignedBeBytes(), uint16ScaledFrom2SignedBeBytes(), and uint32ScaledFrom2SignedBeBytes().
int16FromLeBytes()
int16_t int16FromLeBytes (const uint8_t * bytes, int * index)
Decode a signed 2 byte integer from a little endian byte stream.
Decode a signed 2 byte integer from a little endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 421 of file fielddecode.c.
Referenced by float32ScaledFrom2SignedLeBytes(), int16ScaledFrom2SignedLeBytes(), int32ScaledFrom2SignedLeBytes(), uint16ScaledFrom2SignedLeBytes(), and uint32ScaledFrom2SignedLeBytes().
int24FromBeBytes()
int32_t int24FromBeBytes (const uint8_t * bytes, int * index)
Decode a signed 3 byte integer from a big endian byte stream.
Decode a signed 3 byte integer from a big endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 303 of file fielddecode.c.
Referenced by float32ScaledFrom3SignedBeBytes(), int32ScaledFrom3SignedBeBytes(), and uint32ScaledFrom3SignedBeBytes().
int24FromLeBytes()
int32_t int24FromLeBytes (const uint8_t * bytes, int * index)
Decode a signed 3 byte integer from a little endian byte stream.
Decode a signed 3 byte integer from a little endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 329 of file fielddecode.c.
Referenced by float32ScaledFrom3SignedLeBytes(), int32ScaledFrom3SignedLeBytes(), and uint32ScaledFrom3SignedLeBytes().
int32FromBeBytes()
int32_t int32FromBeBytes (const uint8_t * bytes, int * index)
Decode a signed 4 byte integer from a big endian byte stream.
Decode a signed 4 byte integer from a big endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 209 of file fielddecode.c.
Referenced by float32ScaledFrom4SignedBeBytes(), int32ScaledFrom4SignedBeBytes(), and uint32ScaledFrom4SignedBeBytes().
int32FromLeBytes()
int32_t int32FromLeBytes (const uint8_t * bytes, int * index)
Decode a signed 4 byte integer from a little endian byte stream.
Decode a signed 4 byte integer from a little endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 233 of file fielddecode.c.
Referenced by float32ScaledFrom4SignedLeBytes(), int32ScaledFrom4SignedLeBytes(), and uint32ScaledFrom4SignedLeBytes().
stringFromBytes()
void stringFromBytes (char * string, const uint8_t * bytes, int * index, int maxLength, int fixedLength)
Decode a null terminated string from a byte stream.
Decode a null terminated string from a byte stream
Parameters
string receives the deocded null-terminated string.
bytes is a pointer to the byte stream to be decoded.
index gives the location of the first byte in the byte stream, and will be incremented by the number of bytes decoded when this function is complete.
maxLength is the maximum number of bytes that can be decoded. maxLength includes the null terminator, which is always applied.
fixedLength should be 1 to force the number of bytes decoded to be exactly equal to maxLength.
Definition at line 34 of file fielddecode.c.
Referenced by decodeESC_GitHashPacket(), decodeESC_GitHashPacketStructure(), decodeESC_TelemetrySettingsPacket(), and decodeESC_TelemetrySettingsPacketStructure().
uint16FromBeBytes()
uint16_t uint16FromBeBytes (const uint8_t * bytes, int * index)
Decode a unsigned 2 byte integer from a big endian byte stream.
Decode a unsigned 2 byte integer from a big endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 355 of file fielddecode.c.
Referenced by decodeECU_DualPumpControlTelemetryPacketStructure(), decodeECU_ECUDataPacketStructure(), decodeECU_ECUSettings_t(), decodeECU_eepromSettingsPacket(), decodeECU_eepromSettingsPacketStructure(), decodeECU_FuelUsedSettingsPacketStructure(), decodeECU_HardwareConfigPacketStructure(), decodeECU_PowerCyclesPacketStructure(), decodeECU_SetECUAddressPacket(), decodeECU_SetFuelUsedDivisorPacket(), decodeECU_TelemetryFastPacket(), decodeECU_TelemetryFastPacketStructure(), decodeECU_ThrottleCalibrationPacket(), decodeECU_ThrottleCalibrationPacketStructure(), decodeECU_ThrottleSettingsPacketStructure(), decodeECU_VersionPacketStructure(), decodeESC_AddressPacket(), decodeESC_AddressPacketStructure(), decodeESC_CommandMultipleESCsPacket(), decodeESC_EEPROMSettingsPacket(), decodeESC_EEPROMSettingsPacketStructure(), decodeESC_FirmwarePacket(), decodeESC_FirmwarePacketStructure(), decodeESC_MotorHallSensorConfigPacketStructure(), decodeESC_MotorParametersPacketStructure(), decodeESC_MotorStatusFlagsPacket(), decodeESC_MotorStatusFlagsPacketStructure(), decodeESC_ProtectionValuesPacket(), decodeESC_ProtectionValuesPacketStructure(), decodeESC_PWMCommandPacket(), decodeESC_PWMInputCalibrationPacket(), decodeESC_PWMInputCalibrationPacketStructure(), decodeESC_ResetMotorRunTimePacket(), decodeESC_RPMCommandPacket(), decodeESC_RPMControlLoopSettings_t(), decodeESC_RPMControlLoopSettingsPacketStructure(), decodeESC_SetUserIDAPacket(), decodeESC_SetUserIDBPacket(), decodeESC_StatusAPacket(), decodeESC_StatusAPacketStructure(), decodeESC_StatusBPacket(), decodeESC_StatusBPacketStructure(), decodeESC_StatusCPacket(), decodeESC_StatusCPacketStructure(), decodeESC_SystemInfoPacket(), decodeESC_SystemInfoPacketStructure(), decodeESC_TelltaleValuesPacket(), decodeESC_TelltaleValuesPacketStructure(), decodeESC_TempSensorConfigPacket(), decodeESC_TempSensorConfigPacketStructure(), decodeESC_VoltageCommandPacket(), decodeServo_AddressPacket(), decodeServo_AddressPacketStructure(), decodeServo_Config_t(), decodeServo_ConfigPacket(), decodeServo_ConfigPacketStructure(), decodeServo_FirmwarePacket(), decodeServo_FirmwarePacketStructure(), decodeServo_SettingsInfoPacket(), decodeServo_SettingsInfoPacketStructure(), decodeServo_SetUserIdAPacket(), decodeServo_SetUserIdBPacket(), decodeServo_StatusBPacket(), decodeServo_StatusBPacketStructure(), decodeServo_SystemInfoPacket(), decodeServo_SystemInfoPacketStructure(), float32ScaledFrom2UnsignedBeBytes(), int16ScaledFrom2UnsignedBeBytes(), int32ScaledFrom2UnsignedBeBytes(), uint16ScaledFrom2UnsignedBeBytes(), and uint32ScaledFrom2UnsignedBeBytes().
uint16FromLeBytes()
uint16_t uint16FromLeBytes (const uint8_t * bytes, int * index)
Decode a unsigned 2 byte integer from a little endian byte stream.
Decode a unsigned 2 byte integer from a little endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 377 of file fielddecode.c.
Referenced by float32ScaledFrom2UnsignedLeBytes(), int16ScaledFrom2UnsignedLeBytes(), int32ScaledFrom2UnsignedLeBytes(), uint16ScaledFrom2UnsignedLeBytes(), and uint32ScaledFrom2UnsignedLeBytes().
uint24FromBeBytes()
uint32_t uint24FromBeBytes (const uint8_t * bytes, int * index)
Decode a unsigned 3 byte integer from a big endian byte stream.
Decode a unsigned 3 byte integer from a big endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 257 of file fielddecode.c.
Referenced by decodeECU_ResetEngineTimePacket(), decodeECU_TelemetrySlow1PacketStructure(), decodeECU_TotalEngineTimePacket(), decodeServo_AddressPacket(), decodeServo_AddressPacketStructure(), float32ScaledFrom3UnsignedBeBytes(), int32ScaledFrom3UnsignedBeBytes(), and uint32ScaledFrom3UnsignedBeBytes().
uint24FromLeBytes()
uint32_t uint24FromLeBytes (const uint8_t * bytes, int * index)
Decode a unsigned 3 byte integer from a little endian byte stream.
Decode a unsigned 3 byte integer from a little endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 280 of file fielddecode.c.
Referenced by float32ScaledFrom3UnsignedLeBytes(), int32ScaledFrom3UnsignedLeBytes(), and uint32ScaledFrom3UnsignedLeBytes().
uint32FromBeBytes()
uint32_t uint32FromBeBytes (const uint8_t * bytes, int * index)
Decode a unsigned 4 byte integer from a big endian byte stream.
Decode a unsigned 4 byte integer from a big endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 161 of file fielddecode.c.
Referenced by decodeECU_ECUDataPacketStructure(), decodeECU_PowerCyclesPacketStructure(), decodeECU_TelemetryFastPacket(), decodeECU_TelemetryFastPacketStructure(), decodeESC_SetNodeIDPacket(), decodeESC_SystemInfoPacket(), decodeESC_SystemInfoPacketStructure(), decodeESC_TelltaleValuesPacket(), decodeESC_TelltaleValuesPacketStructure(), decodeServo_SetNodeIDPacket(), decodeServo_SystemInfoPacket(), decodeServo_SystemInfoPacketStructure(), float32FromBeBytes(), float32ScaledFrom4UnsignedBeBytes(), int32ScaledFrom4UnsignedBeBytes(), and uint32ScaledFrom4UnsignedBeBytes().
uint32FromLeBytes()
uint32_t uint32FromLeBytes (const uint8_t * bytes, int * index)
Decode a unsigned 4 byte integer from a little endian byte stream.
Decode a unsigned 4 byte integer from a little endian byte stream.
Parameters
bytes is a pointer to the byte stream which contains the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Returns
the number decoded from the byte stream
Definition at line 185 of file fielddecode.c.
Referenced by float32FromLeBytes(), float32ScaledFrom4UnsignedLeBytes(), int32ScaledFrom4UnsignedLeBytes(), and uint32ScaledFrom4UnsignedLeBytes().