APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/fieldencode.c File Reference
fieldencode.c File Reference
#include "fieldencode.h"
Functions
void pgstrncpy (char *dst, const char *src, int maxLength)
Copy a null terminated string.
void stringToBytes (const char *string, uint8_t *bytes, int *index, int maxLength, int fixedLength)
Encode a null terminated string on a byte stream.
void bytesToBeBytes (const uint8_t *data, uint8_t *bytes, int *index, int num)
Copy an array of bytes to a byte stream without changing the order.
void bytesToLeBytes (const uint8_t *data, uint8_t *bytes, int *index, int num)
Copy an array of bytes to a byte stream while reversing the order.
void float32ToBeBytes (float number, uint8_t *bytes, int *index)
Encode a 4 byte float on a big endian byte stream.
void float32ToLeBytes (float number, uint8_t *bytes, int *index)
Encode a 4 byte float on a little endian byte stream.
void uint32ToBeBytes (uint32_t number, uint8_t *bytes, int *index)
Encode a unsigned 4 byte integer on a big endian byte stream.
void uint32ToLeBytes (uint32_t number, uint8_t *bytes, int *index)
Encode a unsigned 4 byte integer on a little endian byte stream.
void int32ToBeBytes (int32_t number, uint8_t *bytes, int *index)
Encode a signed 4 byte integer on a big endian byte stream.
void int32ToLeBytes (int32_t number, uint8_t *bytes, int *index)
Encode a signed 4 byte integer on a little endian byte stream.
void uint24ToBeBytes (uint32_t number, uint8_t *bytes, int *index)
Encode a unsigned 3 byte integer on a big endian byte stream.
void uint24ToLeBytes (uint32_t number, uint8_t *bytes, int *index)
Encode a unsigned 3 byte integer on a little endian byte stream.
void int24ToBeBytes (int32_t number, uint8_t *bytes, int *index)
Encode a signed 3 byte integer on a big endian byte stream.
void int24ToLeBytes (int32_t number, uint8_t *bytes, int *index)
Encode a signed 3 byte integer on a little endian byte stream.
void uint16ToBeBytes (uint16_t number, uint8_t *bytes, int *index)
Encode a unsigned 2 byte integer on a big endian byte stream.
void uint16ToLeBytes (uint16_t number, uint8_t *bytes, int *index)
Encode a unsigned 2 byte integer on a little endian byte stream.
void int16ToBeBytes (int16_t number, uint8_t *bytes, int *index)
Encode a signed 2 byte integer on a big endian byte stream.
void int16ToLeBytes (int16_t number, uint8_t *bytes, int *index)
Encode a signed 2 byte integer on a little endian byte stream.
Function Documentation
bytesToBeBytes()
void bytesToBeBytes (const uint8_t * data, uint8_t * bytes, int * index, int num)
Copy an array of bytes to a byte stream without changing the order.
Copy an array of bytes to a byte stream without changing the order.
Parameters
data is the array of bytes to copy.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by num when this function is complete.
num is the number of bytes to copy
Definition at line 90 of file fieldencode.c.
bytesToLeBytes()
void bytesToLeBytes (const uint8_t * data, uint8_t * bytes, int * index, int num)
Copy an array of bytes to a byte stream while reversing the order.
Copy an array of bytes to a byte stream while reversing the order.
Parameters
data is the array of bytes to copy.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by num when this function is complete.
num is the number of bytes to copy
Definition at line 116 of file fieldencode.c.
float32ToBeBytes()
void float32ToBeBytes (float number, uint8_t * bytes, int * index)
Encode a 4 byte float on a big endian byte stream.
Encode a 4 byte float on a big endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Definition at line 143 of file fieldencode.c.
Referenced by encodeECU_GovernorSettingsPacketStructure(), encodeECU_PumpSettingsPacketStructure(), encodeESC_TempSensorConfigPacket(), and encodeESC_TempSensorConfigPacketStructure().
float32ToLeBytes()
void float32ToLeBytes (float number, uint8_t * bytes, int * index)
Encode a 4 byte float on a little endian byte stream.
Encode a 4 byte float on a little endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Definition at line 163 of file fieldencode.c.
int16ToBeBytes()
void int16ToBeBytes (int16_t number, uint8_t * bytes, int * index)
Encode a signed 2 byte integer on a big endian byte stream.
Encode a signed 2 byte integer on a big endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
Definition at line 397 of file fieldencode.c.
Referenced by encodeESC_ControlLoopOutputsPacket(), encodeESC_ControlLoopOutputsPacketStructure(), encodeESC_StatusBPacket(), encodeESC_StatusBPacketStructure(), encodeESC_StatusCPacket(), encodeESC_StatusCPacketStructure(), encodeESC_TempSensorConfigPacket(), encodeESC_TempSensorConfigPacketStructure(), encodeServo_AccelerometerPacket(), encodeServo_Config_t(), encodeServo_ConfigPacket(), encodeServo_ConfigPacketStructure(), encodeServo_MultiPositionCommandPacket(), encodeServo_PositionCommandPacket(), encodeServo_StatusAPacket(), encodeServo_StatusAPacketStructure(), encodeServo_StatusBPacket(), encodeServo_StatusBPacketStructure(), encodeServo_StatusCPacket(), encodeServo_StatusCPacketStructure(), float32ScaledTo2SignedBeBytes(), int16ScaledTo2SignedBeBytes(), int32ScaledTo2SignedBeBytes(), uint16ScaledTo2SignedBeBytes(), and uint32ScaledTo2SignedBeBytes().
int16ToLeBytes()
void int16ToLeBytes (int16_t number, uint8_t * bytes, int * index)
Encode a signed 2 byte integer on a little endian byte stream.
Encode a signed 2 byte integer on a little endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
Definition at line 416 of file fieldencode.c.
Referenced by float32ScaledTo2SignedLeBytes(), int16ScaledTo2SignedLeBytes(), int32ScaledTo2SignedLeBytes(), uint16ScaledTo2SignedLeBytes(), and uint32ScaledTo2SignedLeBytes().
int24ToBeBytes()
void int24ToBeBytes (int32_t number, uint8_t * bytes, int * index)
Encode a signed 3 byte integer on a big endian byte stream.
Encode a signed 3 byte integer on a big endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
Definition at line 317 of file fieldencode.c.
Referenced by float32ScaledTo3SignedBeBytes(), int32ScaledTo3SignedBeBytes(), and uint32ScaledTo3SignedBeBytes().
int24ToLeBytes()
void int24ToLeBytes (int32_t number, uint8_t * bytes, int * index)
Encode a signed 3 byte integer on a little endian byte stream.
Encode a signed 3 byte integer on a little endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
Definition at line 338 of file fieldencode.c.
Referenced by float32ScaledTo3SignedLeBytes(), int32ScaledTo3SignedLeBytes(), and uint32ScaledTo3SignedLeBytes().
int32ToBeBytes()
void int32ToBeBytes (int32_t number, uint8_t * bytes, int * index)
Encode a signed 4 byte integer on a big endian byte stream.
Encode a signed 4 byte integer on a big endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Definition at line 229 of file fieldencode.c.
Referenced by float32ScaledTo4SignedBeBytes(), int32ScaledTo4SignedBeBytes(), and uint32ScaledTo4SignedBeBytes().
int32ToLeBytes()
void int32ToLeBytes (int32_t number, uint8_t * bytes, int * index)
Encode a signed 4 byte integer on a little endian byte stream.
Encode a signed 4 byte integer on a little endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Definition at line 252 of file fieldencode.c.
Referenced by float32ScaledTo4SignedLeBytes(), int32ScaledTo4SignedLeBytes(), and uint32ScaledTo4SignedLeBytes().
pgstrncpy()
void pgstrncpy (char * dst, const char * src, int maxLength)
Copy a null terminated string.
Copy a null terminated string to a destination whose maximum length (with null terminator) is maxLength. The destination string is guaranteed to have a null terminator when this operation is complete. This is a replacement for strncpy().
Parameters
dst receives the string, and is guaranteed to be null terminated.
src is the null terminated source string to copy.
maxLength is the size of the dst buffer.
Definition at line 31 of file fieldencode.c.
stringToBytes()
void stringToBytes (const char * string, uint8_t * bytes, int * index, int maxLength, int fixedLength)
Encode a null terminated string on a byte stream.
Encode a null terminated string on a byte stream
Parameters
string is the null termianted string to encode
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by the number of bytes encoded when this function is complete.
maxLength is the maximum number of bytes that can be encoded. A null terminator is always included in the encoding.
fixedLength should be 1 to force the number of bytes encoded to be exactly equal to maxLength.
Definition at line 50 of file fieldencode.c.
Referenced by encodeESC_GitHashPacket(), encodeESC_GitHashPacketStructure(), encodeESC_TelemetrySettingsPacket(), encodeESC_TelemetrySettingsPacketStructure(), and pgstrncpy().
uint16ToBeBytes()
void uint16ToBeBytes (uint16_t number, uint8_t * bytes, int * index)
Encode a unsigned 2 byte integer on a big endian byte stream.
Encode a unsigned 2 byte integer on a big endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
Definition at line 359 of file fieldencode.c.
Referenced by encodeECU_DualPumpControlTelemetryPacketStructure(), encodeECU_ECUDataPacketStructure(), encodeECU_ECUSettings_t(), encodeECU_eepromSettingsPacket(), encodeECU_eepromSettingsPacketStructure(), encodeECU_FuelUsedSettingsPacketStructure(), encodeECU_HardwareConfigPacketStructure(), encodeECU_PowerCyclesPacketStructure(), encodeECU_Pump2ConfigPacketStructure(), encodeECU_SetECUAddressPacket(), encodeECU_SetFuelUsedDivisorPacket(), encodeECU_TelemetryFastPacket(), encodeECU_TelemetryFastPacketStructure(), encodeECU_ThrottleCalibrationPacket(), encodeECU_ThrottleCalibrationPacketStructure(), encodeECU_ThrottleSettingsPacketStructure(), encodeECU_VersionPacketStructure(), encodeESC_AddressPacket(), encodeESC_AddressPacketStructure(), encodeESC_CommandMultipleESCsPacket(), encodeESC_Config_t(), encodeESC_ConfigPacket(), encodeESC_ConfigPacketStructure(), encodeESC_EEPROMSettingsPacket(), encodeESC_EEPROMSettingsPacketStructure(), encodeESC_FirmwarePacket(), encodeESC_FirmwarePacketStructure(), encodeESC_MotorHallSensorConfigPacketStructure(), encodeESC_MotorParametersPacketStructure(), encodeESC_MotorStatusFlagsPacket(), encodeESC_MotorStatusFlagsPacketStructure(), encodeESC_ProtectionValuesPacket(), encodeESC_ProtectionValuesPacketStructure(), encodeESC_PWMCommandPacket(), encodeESC_PWMInputCalibrationPacket(), encodeESC_PWMInputCalibrationPacketStructure(), encodeESC_ResetMotorRunTimePacket(), encodeESC_RPMCommandPacket(), encodeESC_RPMControlLoopSettings_t(), encodeESC_RPMControlLoopSettingsPacketStructure(), encodeESC_SetUserIDAPacket(), encodeESC_SetUserIDBPacket(), encodeESC_StatusAPacket(), encodeESC_StatusAPacketStructure(), encodeESC_StatusBPacket(), encodeESC_StatusBPacketStructure(), encodeESC_StatusCPacket(), encodeESC_StatusCPacketStructure(), encodeESC_SystemInfoPacket(), encodeESC_SystemInfoPacketStructure(), encodeESC_TelltaleValuesPacket(), encodeESC_TelltaleValuesPacketStructure(), encodeESC_TempSensorConfigPacket(), encodeESC_TempSensorConfigPacketStructure(), encodeESC_VoltageCommandPacket(), encodeServo_AddressPacket(), encodeServo_AddressPacketStructure(), encodeServo_Config_t(), encodeServo_ConfigPacket(), encodeServo_ConfigPacketStructure(), encodeServo_FirmwarePacket(), encodeServo_FirmwarePacketStructure(), encodeServo_SettingsInfoPacket(), encodeServo_SettingsInfoPacketStructure(), encodeServo_SetUserIdAPacket(), encodeServo_SetUserIdBPacket(), encodeServo_StatusBPacket(), encodeServo_StatusBPacketStructure(), encodeServo_SystemInfoPacket(), encodeServo_SystemInfoPacketStructure(), float32ScaledTo2UnsignedBeBytes(), int16ScaledTo2UnsignedBeBytes(), int32ScaledTo2UnsignedBeBytes(), uint16ScaledTo2UnsignedBeBytes(), and uint32ScaledTo2UnsignedBeBytes().
uint16ToLeBytes()
void uint16ToLeBytes (uint16_t number, uint8_t * bytes, int * index)
Encode a unsigned 2 byte integer on a little endian byte stream.
Encode a unsigned 2 byte integer on a little endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
Definition at line 378 of file fieldencode.c.
Referenced by float32ScaledTo2UnsignedLeBytes(), int16ScaledTo2UnsignedLeBytes(), int32ScaledTo2UnsignedLeBytes(), uint16ScaledTo2UnsignedLeBytes(), and uint32ScaledTo2UnsignedLeBytes().
uint24ToBeBytes()
void uint24ToBeBytes (uint32_t number, uint8_t * bytes, int * index)
Encode a unsigned 3 byte integer on a big endian byte stream.
Encode a unsigned 3 byte integer on a big endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
Definition at line 275 of file fieldencode.c.
Referenced by encodeECU_ResetEngineTimePacket(), encodeECU_TelemetrySlow1PacketStructure(), encodeECU_TotalEngineTimePacket(), encodeServo_AddressPacket(), encodeServo_AddressPacketStructure(), float32ScaledTo3UnsignedBeBytes(), int32ScaledTo3UnsignedBeBytes(), and uint32ScaledTo3UnsignedBeBytes().
uint24ToLeBytes()
void uint24ToLeBytes (uint32_t number, uint8_t * bytes, int * index)
Encode a unsigned 3 byte integer on a little endian byte stream.
Encode a unsigned 3 byte integer on a little endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
Definition at line 296 of file fieldencode.c.
Referenced by float32ScaledTo3UnsignedLeBytes(), int32ScaledTo3UnsignedLeBytes(), and uint32ScaledTo3UnsignedLeBytes().
uint32ToBeBytes()
void uint32ToBeBytes (uint32_t number, uint8_t * bytes, int * index)
Encode a unsigned 4 byte integer on a big endian byte stream.
Encode a unsigned 4 byte integer on a big endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Definition at line 183 of file fieldencode.c.
Referenced by encodeECU_ECUDataPacketStructure(), encodeECU_PowerCyclesPacketStructure(), encodeECU_TelemetryFastPacket(), encodeECU_TelemetryFastPacketStructure(), encodeESC_SetNodeIDPacket(), encodeESC_SystemInfoPacket(), encodeESC_SystemInfoPacketStructure(), encodeESC_TelltaleValuesPacket(), encodeESC_TelltaleValuesPacketStructure(), encodeServo_SetNodeIDPacket(), encodeServo_SystemInfoPacket(), encodeServo_SystemInfoPacketStructure(), float32ScaledTo4UnsignedBeBytes(), float32ToBeBytes(), int32ScaledTo4UnsignedBeBytes(), and uint32ScaledTo4UnsignedBeBytes().
uint32ToLeBytes()
void uint32ToLeBytes (uint32_t number, uint8_t * bytes, int * index)
Encode a unsigned 4 byte integer on a little endian byte stream.
Encode a unsigned 4 byte integer on a little endian byte stream.
Parameters
number is the value to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
Definition at line 206 of file fieldencode.c.
Referenced by float32ScaledTo4UnsignedLeBytes(), float32ToLeBytes(), int32ScaledTo4UnsignedLeBytes(), and uint32ScaledTo4UnsignedLeBytes().