APM:Libraries: libraries/AP_Filesystem/examples/File_IO/File_IO.cpp File Reference
File_IO.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_BoardConfig/AP_BoardConfig.h>
#include <AP_Filesystem/AP_Filesystem.h>
#include <stdio.h>
Macros
#define BUFFER_SIZE 50
Functions
void setup ()
void loop ()
static void write_file (const char *)
static void read_file (const char *)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static AP_BoardConfig board_config
int file_count = 0
const char * dir_path = nullptr
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 50
Definition at line 9 of file File_IO.cpp.
Referenced by read_file(), and write_file().
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
loop()
void loop (void)
Definition at line 40 of file File_IO.cpp.
read_file()
static void read_file (const char * file_path) static
Definition at line 84 of file File_IO.cpp.
Referenced by loop().
setup()
void setup (void)
Definition at line 23 of file File_IO.cpp.
write_file()
static void write_file (const char * file_path) static
Definition at line 58 of file File_IO.cpp.
Referenced by loop().
Variable Documentation
board_config
AP_BoardConfig board_config static
Definition at line 16 of file File_IO.cpp.
Referenced by setup().
dir_path
const char* dir_path = nullptr
Definition at line 19 of file File_IO.cpp.
Referenced by loop(), and setup().
file_count
int file_count = 0
Definition at line 18 of file File_IO.cpp.
Referenced by loop(), and write_file().
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
This file test realloc failure on ExpandingString
Definition at line 11 of file File_IO.cpp.
Referenced by loop(), read_file(), setup(), and write_file().