APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/flash.h File Reference
flash.h File Reference
#include "hal.h"
Functions
uint32_t stm32_flash_getpageaddr (uint32_t page)
uint32_t stm32_flash_getpagesize (uint32_t page)
uint32_t stm32_flash_getnumpages (void)
bool stm32_flash_erasepage (uint32_t page)
bool stm32_flash_write (uint32_t addr, const void *buf, uint32_t count)
void stm32_flash_keep_unlocked (bool set)
bool stm32_flash_ispageerased (uint32_t page)
void stm32_flash_protect_flash (bool bootloader, bool protect)
write protect the main flash or bootloader sectors
void stm32_flash_unprotect_flash (void)
void stm32_flash_set_NRST_MODE (uint8_t nrst_mode)
bool stm32_flash_recent_erase (void)
Function Documentation
stm32_flash_erasepage()
bool stm32_flash_erasepage (uint32_t page)
Definition at line 458 of file flash.c.
Referenced by ChibiOS::Flash::erasepage().
stm32_flash_getnumpages()
uint32_t stm32_flash_getnumpages (void)
Definition at line 426 of file flash.c.
Referenced by ChibiOS::Flash::getnumpages().
stm32_flash_getpageaddr()
uint32_t stm32_flash_getpageaddr (uint32_t page)
Definition at line 387 of file flash.c.
Referenced by ChibiOS::Flash::getpageaddr(), stm32_flash_erasepage(), and stm32_flash_ispageerased().
stm32_flash_getpagesize()
uint32_t stm32_flash_getpagesize (uint32_t page)
Definition at line 413 of file flash.c.
Referenced by ChibiOS::Flash::getpagesize(), stm32_flash_erasepage(), stm32_flash_getpageaddr(), and stm32_flash_ispageerased().
stm32_flash_ispageerased()
bool stm32_flash_ispageerased (uint32_t page)
Definition at line 431 of file flash.c.
Referenced by ChibiOS::Flash::ispageerased(), and stm32_flash_erasepage().
stm32_flash_keep_unlocked()
void stm32_flash_keep_unlocked (bool set)
Definition at line 920 of file flash.c.
Referenced by CrashCatcher_DumpEndFlash(), CrashCatcher_DumpStartFlash(), and ChibiOS::Flash::keep_unlocked().
stm32_flash_protect_flash()
void stm32_flash_protect_flash (bool bootloader, bool protect)
write protect the main flash or bootloader sectors
Definition at line 934 of file flash.c.
stm32_flash_recent_erase()
bool stm32_flash_recent_erase (void)
Definition at line 1105 of file flash.c.
Referenced by ChibiOS::Scheduler::in_expected_delay().
stm32_flash_set_NRST_MODE()
void stm32_flash_set_NRST_MODE (uint8_t nrst_mode)
Referenced by __late_init().
stm32_flash_unprotect_flash()
void stm32_flash_unprotect_flash (void)
Definition at line 1007 of file flash.c.
stm32_flash_write()
bool stm32_flash_write (uint32_t addr, const void * buf, uint32_t count)
Definition at line 905 of file flash.c.
Referenced by CrashCatcher_DumpEndFlash(), flush_dump_buffer(), and ChibiOS::Flash::write().