APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/flash.c File Reference
flash.c File Reference
#include "flash.h"
#include "hal.h"
#include <string.h>
#include "stm32_util.h"
#include "hrt.h"
#include <assert.h>
Macros
#define KB(x) ((x*1024))
#define STM32_FLASH_BASE 0x08000000
#define STM32_FLASH_SIZE KB(BOARD_FLASH_SIZE)
#define STM32_FLASH_DISABLE_ISR 1
#define STM32_FLASH_BANK2_START (STM32_FLASH_BASE+0x00080000)
#define STM32_FLASH_NBANKS 2
#define FLASH_KEY1 0x45670123
#define FLASH_KEY2 0xCDEF89AB
#define FLASH_OPTKEY1 0x08192A3B
#define FLASH_OPTKEY2 0x4C5D6E7F
Functions
static uint16_t getreg16 (unsigned int addr)
static void putreg16 (uint16_t val, unsigned int addr)
static uint32_t getreg32 (unsigned int addr)
static void putreg32 (uint32_t val, unsigned int addr)
static void stm32_flash_wait_idle (void)
static void stm32_flash_clear_errors (void)
static void stm32_flash_unlock (void)
void stm32_flash_lock (void)
uint32_t stm32_flash_getpageaddr (uint32_t page)
uint32_t stm32_flash_getpagesize (uint32_t page)
uint32_t stm32_flash_getnumpages ()
bool stm32_flash_ispageerased (uint32_t page)
bool stm32_flash_erasepage (uint32_t page)
bool stm32_flash_write (uint32_t addr, const void *buf, uint32_t count)
void stm32_flash_keep_unlocked (bool set)
void stm32_flash_protect_flash (bool bootloader, bool protect)
write protect the main flash or bootloader sectors
void stm32_flash_unprotect_flash ()
bool stm32_flash_recent_erase (void)
Variables
static uint32_t flash_pageaddr [STM32_FLASH_NPAGES]
static bool flash_pageaddr_initialised
static bool flash_keep_unlocked
static uint32_t last_erase_ms
uint32_t _flash_fail_line
uint32_t _flash_fail_addr
uint32_t _flash_fail_count
uint8_t * _flash_fail_buf
Macro Definition Documentation
FLASH_KEY1
#define FLASH_KEY1 0x45670123
Definition at line 180 of file flash.c.
Referenced by stm32_flash_unlock().
FLASH_KEY2
#define FLASH_KEY2 0xCDEF89AB
Definition at line 183 of file flash.c.
Referenced by stm32_flash_unlock().
FLASH_OPTKEY1
#define FLASH_OPTKEY1 0x08192A3B
Definition at line 186 of file flash.c.
FLASH_OPTKEY2
#define FLASH_OPTKEY2 0x4C5D6E7F
Definition at line 189 of file flash.c.
KB
#define KB (x) ((x*1024))
Definition at line 71 of file flash.c.
STM32_FLASH_BANK2_START
#define STM32_FLASH_BANK2_START (STM32_FLASH_BASE+0x00080000)
Definition at line 82 of file flash.c.
STM32_FLASH_BASE
#define STM32_FLASH_BASE 0x08000000
Definition at line 73 of file flash.c.
Referenced by stm32_flash_getpageaddr().
STM32_FLASH_DISABLE_ISR
#define STM32_FLASH_DISABLE_ISR 1
Definition at line 78 of file flash.c.
STM32_FLASH_NBANKS
#define STM32_FLASH_NBANKS 2
Definition at line 161 of file flash.c.
Referenced by stm32_flash_protect_flash(), stm32_flash_unprotect_flash(), and stm32_flash_wait_idle().
STM32_FLASH_SIZE
#define STM32_FLASH_SIZE KB(BOARD_FLASH_SIZE)
Definition at line 74 of file flash.c.
Function Documentation
getreg16()
static uint16_t getreg16 (unsigned int addr) inline static
Definition at line 196 of file flash.c.
getreg32()
static uint32_t getreg32 (unsigned int addr) inline static
Definition at line 210 of file flash.c.
Referenced by stm32_flash_ispageerased().
putreg16()
static void putreg16 (uint16_t val, unsigned int addr) inline static
Definition at line 204 of file flash.c.
putreg32()
static void putreg32 (uint32_t val, unsigned int addr) inline static
Definition at line 218 of file flash.c.
stm32_flash_clear_errors()
static void stm32_flash_clear_errors (void) static
Definition at line 241 of file flash.c.
Referenced by stm32_flash_erasepage(), stm32_flash_protect_flash(), and stm32_flash_unprotect_flash().
stm32_flash_erasepage()
bool stm32_flash_erasepage (uint32_t page)
Definition at line 458 of file flash.c.
Referenced by ChibiOS::Flash::erasepage().
stm32_flash_getnumpages()
uint32_t stm32_flash_getnumpages (void)
Definition at line 426 of file flash.c.
Referenced by ChibiOS::Flash::getnumpages().
stm32_flash_getpageaddr()
uint32_t stm32_flash_getpageaddr (uint32_t page)
Definition at line 387 of file flash.c.
Referenced by ChibiOS::Flash::getpageaddr(), stm32_flash_erasepage(), and stm32_flash_ispageerased().
stm32_flash_getpagesize()
uint32_t stm32_flash_getpagesize (uint32_t page)
Definition at line 413 of file flash.c.
Referenced by ChibiOS::Flash::getpagesize(), stm32_flash_erasepage(), stm32_flash_getpageaddr(), and stm32_flash_ispageerased().
stm32_flash_ispageerased()
bool stm32_flash_ispageerased (uint32_t page)
Definition at line 431 of file flash.c.
Referenced by ChibiOS::Flash::ispageerased(), and stm32_flash_erasepage().
stm32_flash_keep_unlocked()
void stm32_flash_keep_unlocked (bool set)
Definition at line 920 of file flash.c.
Referenced by CrashCatcher_DumpEndFlash(), CrashCatcher_DumpStartFlash(), and ChibiOS::Flash::keep_unlocked().
stm32_flash_lock()
void stm32_flash_lock (void)
Definition at line 289 of file flash.c.
Referenced by stm32_flash_erasepage(), stm32_flash_keep_unlocked(), and stm32_flash_unprotect_flash().
stm32_flash_protect_flash()
void stm32_flash_protect_flash (bool bootloader, bool protect)
write protect the main flash or bootloader sectors
Definition at line 934 of file flash.c.
Referenced by main_loop().
stm32_flash_recent_erase()
bool stm32_flash_recent_erase (void)
Definition at line 1105 of file flash.c.
Referenced by ChibiOS::Scheduler::in_expected_delay().
stm32_flash_unlock()
static void stm32_flash_unlock (void) static
Definition at line 255 of file flash.c.
Referenced by stm32_flash_erasepage(), stm32_flash_keep_unlocked(), and stm32_flash_unprotect_flash().
stm32_flash_unprotect_flash()
void stm32_flash_unprotect_flash (void)
Definition at line 1007 of file flash.c.
Referenced by main_loop().
stm32_flash_wait_idle()
static void stm32_flash_wait_idle (void) static
Definition at line 223 of file flash.c.
Referenced by stm32_flash_erasepage(), stm32_flash_lock(), stm32_flash_unlock(), and stm32_flash_unprotect_flash().
stm32_flash_write()
bool stm32_flash_write (uint32_t addr, const void * buf, uint32_t count)
Definition at line 905 of file flash.c.
Referenced by CrashCatcher_DumpEndFlash(), flush_dump_buffer(), and ChibiOS::Flash::write().
Variable Documentation
_flash_fail_addr
uint32_t _flash_fail_addr
Definition at line 760 of file flash.c.
_flash_fail_buf
uint8_t* _flash_fail_buf
Definition at line 762 of file flash.c.
_flash_fail_count
uint32_t _flash_fail_count
Definition at line 761 of file flash.c.
_flash_fail_line
uint32_t _flash_fail_line
Definition at line 759 of file flash.c.
flash_keep_unlocked
bool flash_keep_unlocked static
Definition at line 177 of file flash.c.
Referenced by stm32_flash_keep_unlocked(), stm32_flash_lock(), and stm32_flash_unlock().
flash_pageaddr
uint32_t flash_pageaddr[STM32_FLASH_NPAGES] static
Definition at line 173 of file flash.c.
Referenced by stm32_flash_getpageaddr().
flash_pageaddr_initialised
bool flash_pageaddr_initialised static
Definition at line 174 of file flash.c.
Referenced by stm32_flash_getpageaddr().
last_erase_ms
uint32_t last_erase_ms static
Definition at line 452 of file flash.c.
Referenced by stm32_flash_erasepage(), and stm32_flash_recent_erase().