APM:Libraries: libraries/GCS_MAVLink/GCS_MAVLink.h File Reference
GCS_MAVLink.h File Reference
One size fits all header for MAVLink integration.
#include <AP_HAL/AP_HAL_Boards.h>
#include <AP_Networking/AP_Networking_Config.h>
#include "include/mavlink/v2.0/all/version.h"
#include "include/mavlink/v2.0/mavlink_types.h"
#include "include/mavlink/v2.0/all/mavlink.h"
Macros
#define MAVLINK_SEPARATE_HELPERS
#define MAVLINK_NO_CONVERSION_HELPERS
#define MAVLINK_SEND_UART_BYTES(chan, buf, len) comm_send_buffer(chan, buf, len)
#define MAVLINK_START_UART_SEND(chan, size) comm_send_lock(chan, size)
#define MAVLINK_END_UART_SEND(chan, size) comm_send_unlock(chan)
#define MAVLINK_COMM_NUM_BUFFERS 5
#define MAVLINK_GET_CHANNEL_BUFFER 1
#define MAVLINK_GET_CHANNEL_STATUS 1
#define MAVLINK_MAX_PAYLOAD_LEN 255
#define MAVLINK_USE_CONVENIENCE_FUNCTIONS
Functions
static bool valid_channel (mavlink_channel_t chan)
mavlink_message_t * mavlink_get_channel_buffer (uint8_t chan)
mavlink_status_t * mavlink_get_channel_status (uint8_t chan)
void comm_send_buffer (mavlink_channel_t chan, const uint8_t *buf, uint8_t len)
uint16_t comm_get_txspace (mavlink_channel_t chan)
void comm_send_lock (mavlink_channel_t chan, uint16_t size)
void comm_send_unlock (mavlink_channel_t chan)
HAL_Semaphore & comm_chan_lock (mavlink_channel_t chan)
Variables
AP_HAL::UARTDriver * mavlink_comm_port [MAVLINK_COMM_NUM_BUFFERS]
MAVLink streams used for each telemetry port.
bool gcs_alternative_active [MAVLINK_COMM_NUM_BUFFERS]
mavlink_system_t mavlink_system
MAVLink system definition.
Detailed Description
One size fits all header for MAVLink integration.
Definition in file GCS_MAVLink.h.
Macro Definition Documentation
MAVLINK_COMM_NUM_BUFFERS
#define MAVLINK_COMM_NUM_BUFFERS 5
Definition at line 23 of file GCS_MAVLink.h.
Referenced by MAVLink_routing::check_and_forward(), MAVLink_routing::handle_heartbeat(), GCS_MAVLINK::handle_setup_signing(), GCS_MAVLINK::save_signing_timestamp(), MAVLink_routing::send_to_components(), GCS::setup_uarts(), GCS_MAVLINK::update_signing_timestamp(), and valid_channel().
MAVLINK_END_UART_SEND
#define MAVLINK_END_UART_SEND (chan, size) comm_send_unlock(chan)
Definition at line 16 of file GCS_MAVLink.h.
MAVLINK_GET_CHANNEL_BUFFER
#define MAVLINK_GET_CHANNEL_BUFFER 1
Definition at line 26 of file GCS_MAVLink.h.
MAVLINK_GET_CHANNEL_STATUS
#define MAVLINK_GET_CHANNEL_STATUS 1
Definition at line 27 of file GCS_MAVLink.h.
MAVLINK_MAX_PAYLOAD_LEN
#define MAVLINK_MAX_PAYLOAD_LEN 255
Definition at line 42 of file GCS_MAVLink.h.
MAVLINK_NO_CONVERSION_HELPERS
#define MAVLINK_NO_CONVERSION_HELPERS
Definition at line 11 of file GCS_MAVLink.h.
MAVLINK_SEND_UART_BYTES
#define MAVLINK_SEND_UART_BYTES (chan, buf, len) comm_send_buffer(chan, buf, len)
Definition at line 13 of file GCS_MAVLink.h.
MAVLINK_SEPARATE_HELPERS
#define MAVLINK_SEPARATE_HELPERS
Definition at line 10 of file GCS_MAVLink.h.
MAVLINK_START_UART_SEND
#define MAVLINK_START_UART_SEND (chan, size) comm_send_lock(chan, size)
Definition at line 15 of file GCS_MAVLink.h.
MAVLINK_USE_CONVENIENCE_FUNCTIONS
#define MAVLINK_USE_CONVENIENCE_FUNCTIONS
Definition at line 75 of file GCS_MAVLink.h.
Function Documentation
comm_chan_lock()
HAL_Semaphore & comm_chan_lock (mavlink_channel_t chan)
Definition at line 189 of file GCS_MAVLink.cpp.
Referenced by GCS_MAVLINK::do_try_send_message(), GCS_MAVLINK::send_ftp_reply(), and GCS_MAVLINK::service_statustext().
comm_get_txspace()
uint16_t comm_get_txspace (mavlink_channel_t chan)
Check for available transmit space on the nominated MAVLink channel
Parameters
chan Channel to check
Returns
Number of bytes available
Definition at line 121 of file GCS_MAVLink.cpp.
Referenced by MAVLink_routing::handle_heartbeat(), and MAVLink_routing::send_to_components().
comm_send_buffer()
void comm_send_buffer (mavlink_channel_t chan, const uint8_t * buf, uint8_t len)
Definition at line 133 of file GCS_MAVLink.cpp.
comm_send_lock()
void comm_send_lock (mavlink_channel_t chan, uint16_t size)
Definition at line 165 of file GCS_MAVLink.cpp.
comm_send_unlock()
void comm_send_unlock (mavlink_channel_t chan)
Definition at line 178 of file GCS_MAVLink.cpp.
mavlink_get_channel_buffer()
mavlink_message_t * mavlink_get_channel_buffer (uint8_t chan)
Definition at line 44 of file GCS_MAVLink.cpp.
mavlink_get_channel_status()
mavlink_status_t * mavlink_get_channel_status (uint8_t chan)
Definition at line 56 of file GCS_MAVLink.cpp.
Referenced by accept_unsigned_callback(), GCS_MAVLINK::packet_overhead_chan(), GCS_MAVLINK::save_signing_timestamp(), GCS_MAVLINK::signing_enabled(), and GCS_MAVLINK::update_signing_timestamp().
valid_channel()
static bool valid_channel (mavlink_channel_t chan) inline static
Sanity check MAVLink channel
Parameters
chan Channel to send to
Definition at line 56 of file GCS_MAVLink.h.
Referenced by comm_send_buffer(), GCS_MAVLINK::ftp_worker(), and GCS_MAVLINK::init().
Variable Documentation
gcs_alternative_active
bool gcs_alternative_active[MAVLINK_COMM_NUM_BUFFERS] extern
Definition at line 73 of file GCS_MAVLink.cpp.
Referenced by comm_send_buffer(), and GCS_MAVLINK::update_receive().
mavlink_comm_port
AP_HAL::UARTDriver* mavlink_comm_port[MAVLINK_COMM_NUM_BUFFERS] extern
MAVLink streams used for each telemetry port.
Definition at line 72 of file GCS_MAVLink.cpp.
Referenced by comm_send_buffer(), comm_send_lock(), GCS_MAVLINK::ftp_worker(), GCS_MAVLINK::init(), and GCS_MAVLINK::update_receive().
mavlink_system
mavlink_system_t mavlink_system extern
MAVLink system definition.
Definition at line 79 of file GCS_MAVLink.cpp.