APM:Libraries: libraries/GCS_MAVLink/GCS_Common.cpp File Reference
GCS_Common.cpp File Reference
#include "GCS_config.h"
#include "GCS.h"
#include <AC_Fence/AC_Fence.h>
#include <AP_Compass/AP_Compass.h>
#include <AP_ADSB/AP_ADSB.h>
#include <AP_AdvancedFailsafe/AP_AdvancedFailsafe.h>
#include <AP_AHRS/AP_AHRS.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_Arming/AP_Arming.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_Logger/AP_Logger.h>
#include <AP_OpticalFlow/AP_OpticalFlow.h>
#include <AP_Vehicle/AP_Vehicle.h>
#include <AP_RangeFinder/AP_RangeFinder.h>
#include <AP_RangeFinder/AP_RangeFinder_Backend.h>
#include <AP_Airspeed/AP_Airspeed.h>
#include <AP_Camera/AP_Camera.h>
#include <AP_Gripper/AP_Gripper.h>
#include <AC_Sprayer/AC_Sprayer.h>
#include <AP_BLHeli/AP_BLHeli.h>
#include <AP_Relay/AP_Relay.h>
#include <AP_RSSI/AP_RSSI.h>
#include <AP_RTC/AP_RTC.h>
#include <AP_Scheduler/AP_Scheduler.h>
#include <AP_SerialManager/AP_SerialManager.h>
#include <AP_RCTelemetry/AP_Spektrum_Telem.h>
#include <AP_Mount/AP_Mount.h>
#include <AP_Common/AP_FWVersion.h>
#include <AP_VisualOdom/AP_VisualOdom.h>
#include <AP_Baro/AP_Baro.h>
#include <AP_EFI/AP_EFI.h>
#include <AP_Proximity/AP_Proximity.h>
#include <AP_Scripting/AP_Scripting.h>
#include <SRV_Channel/SRV_Channel.h>
#include <AP_Winch/AP_Winch.h>
#include <AP_Mission/AP_Mission.h>
#include <AP_OpenDroneID/AP_OpenDroneID.h>
#include <AP_OSD/AP_OSD.h>
#include <AP_RCTelemetry/AP_CRSF_Telem.h>
#include <AP_RPM/AP_RPM.h>
#include <AP_AIS/AP_AIS.h>
#include <AP_Filesystem/AP_Filesystem.h>
#include <AP_Frsky_Telem/AP_Frsky_Telem.h>
#include <RC_Channel/RC_Channel.h>
#include <AP_KDECAN/AP_KDECAN.h>
#include <AP_LandingGear/AP_LandingGear.h>
#include <AP_Landing/AP_Landing_config.h>
#include "MissionItemProtocol_Waypoints.h"
#include "MissionItemProtocol_Rally.h"
#include "MissionItemProtocol_Fence.h"
#include <AP_Notify/AP_Notify.h>
#include <AP_Vehicle/AP_Vehicle_config.h>
#include <stdio.h>
#include <SITL/SITL.h>
#include <AP_BattMonitor/AP_BattMonitor_config.h>
#include <AP_GPS/AP_GPS.h>
#include <ctype.h>
Functions
static int32_t convert_COMMAND_LONG_loc_param (float param, bool stores_location)
GCS & gcs ()
Variables
const AP_HAL::HAL & hal
Function Documentation
convert_COMMAND_LONG_loc_param()
static int32_t convert_COMMAND_LONG_loc_param (float param, bool stores_location) static
Definition at line 4924 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::convert_COMMAND_LONG_to_COMMAND_INT().
gcs()
GCS & gcs ()
Definition at line 6846 of file GCS_Common.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration_baro(), ESP32::RCInput::_timer_tick(), AP_Frsky_SPort_Passthrough::calc_ap_status(), AP_Frsky_SPort_Passthrough::calc_param(), AP_AdvancedFailsafe::check(), MAVLink_routing::check_and_forward(), AP_Arming::check_failed(), AP_Arming::check_failed(), AP_BattMonitor::checkPoweringOff(), comm_get_txspace(), comm_send_buffer(), AC_AutoTune::currently_level(), AC_AutoTune_Heli::do_gcs_announcements(), AC_AutoTune_Multi::do_gcs_announcements(), AC_AutoTune_Heli::do_post_test_gcs_announcements(), AP_OSD_Screen::draw_throttle(), GCS::enable_high_latency_connections(), GCS_MAVLINK::find_by_mavtype_and_compid(), GCS_MAVLINK::ftp_init(), GCS_MAVLINK::ftp_worker(), gcs_out_of_space_to_send(), AP_AdvancedFailsafe::gcs_terminate(), GCS_MAVLINK::handle_command_preflight_calibration(), GCS_MAVLINK::handle_control_high_latency(), GCS_MAVLINK::handle_heartbeat(), GCS_MAVLINK::handle_mission_clear_all(), GCS_MAVLINK::handle_mission_count(), GCS_MAVLINK::handle_mission_item(), GCS_MAVLINK::handle_mission_request_int(), GCS_MAVLINK::handle_mission_request_list(), GCS_MAVLINK::handle_mission_write_partial_list(), MissionItemProtocol::handle_mission_write_partial_list(), GCS_MAVLINK::handle_param_set(), GCS_MAVLINK::handle_serial_control(), GCS_MAVLINK::handle_setup_signing(), GCS_MAVLINK::handle_timesync(), AP_RCTelemetry::init(), AP_Follow::init_offsets_if_required(), AP_Frsky_SPort_Passthrough::is_packet_ready(), loop(), MissionItemProtocol::mavlink2_requirement_met(), GCS_MAVLINK::mavlink_coordinate_frame_to_location_alt_frame(), mavlink_get_channel_buffer(), mavlink_get_channel_status(), AP_AdvancedFailsafe::max_range_update(), AP_MotorsUGV::pre_arm_check(), AC_AutoTune_Multi::report_axis_gains(), AC_AutoTune_Heli::report_axis_gains(), GCS_MAVLINK::requesting_mission_items(), AC_AutoTune::run(), AP_Vehicle::scheduler_delay_callback(), AP_Frsky_D::send(), AP_Frsky_SPort::send(), GCS_MAVLINK::send_heartbeat(), GCS_MAVLINK::send_high_latency2(), MissionItemProtocol::send_mission_item_warning(), GCS::send_named_float(), GCS::send_parameter_value(), GCS_MAVLINK::send_power_status(), AC_AutoTune::send_step_string(), GCS_MAVLINK::send_sys_status(), GCS_MAVLINK::send_text(), AP_WindVane::send_wind(), AP_RCTelemetry::sensor_status_flags(), GCS_MAVLINK::service_statustext(), GCS_MAVLINK::set_mavlink_message_id_interval(), GCS_MAVLINK::set_message_interval(), setup(), AP_Vehicle::setup(), AC_AutoTune_Heli::test_run(), AP_BoardConfig::throw_error(), GCS_MAVLINK::try_send_message(), GCS_MAVLINK::try_send_mission_message(), AP_InertialSensor_Invensense::update(), AP_Airspeed::update(), AP_WheelEncoder_SITL_Quadrature::update(), SoaringController::update_active_state(), AP_MSP_Telem_Backend::update_flight_mode_str(), AC_AutoTune::update_gcs(), GCS::update_passthru(), GCS_MAVLINK::update_receive(), GCS_MAVLINK::update_send(), and AC_AutoTune_Heli::updating_max_gains().
Variable Documentation
hal
const AP_HAL::HAL& hal extern
The data_array uses 3 elements to perform the data transaction. The first element is a data byte that provides to FPGA's hardware the transaction type that will be realized inside the SPI module. Where:
╔═════════╦═════════╦══════════╦══════════╦══════════╦══════════╦══════════╦═══════════╗ ║ MSB ║ ║ ║ ║ ║ ║ ║ LSB ║ ╠═════════╬═════════╬══════════╬══════════╬══════════╬══════════╬══════════╬═══════════╣ ║ wr_addr ║ rd_addr ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ ╚═════════╩═════════╩══════════╩══════════╩══════════╩══════════╩══════════╩═══════════╝
╔═══════════╦═════════╦═════════╗ ║ Register ║ wr_addr ║ rd_addr ║ ╠═══════════╬═════════╬═════════╣ ║ write ║ 0 ║ X ║ ╠═══════════╬═════════╬═════════╣ ║ read ║ X ║ 0 ║ ╠═══════════╬═════════╬═════════╣ ║ status ║ 1 ║ 1 ║ ╚═══════════╩═════════╩═════════╝
So, to perform a write transaction in the SPI module it's necessary to send. E.g: 0b 01xx xxxx And to a read transaction.. 0b 10xx xxxx
The PWM frequency is always even and the duty cycle percentage odd. E.g: pwm_01: Address 0x0000 frequency : Address 0x0001 duty cycle pwm_02: Address 0x0002 frequency Eg of allowed values: // PWM channel in 100Hz uint16_t freq = 100;
// duty cycle in (1823/65535) that's 2.78% of 100Hz: // the signal will hold high until 278 usec uint16_t duty = 1823;
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.