APM:Libraries: I2C
I2C
Low-level I2C peripheral driver.
Files
file i2c_sw.c
Low-level I2C driver software implementation using for ESP SoCs.
file i2c_sw.h
Low-level I2C peripheral driver interface definition.
Classes
struct _i2c_bus_t
Macros
#define I2C_READ (0x0001)
Read bit needs to be set when reading.
#define I2C_10BIT_MAGIC (0xF0u)
Special bit pattern indicating a 10 bit address is used.
Functions
void i2c_init (_i2c_bus_t *bus)
Initialize the given I2C bus.
int i2c_read_reg (_i2c_bus_t *bus, uint16_t addr, uint16_t reg, void *data, uint8_t flags)
Convenience function for reading one byte from a given register address.
int i2c_read_regs (_i2c_bus_t *bus, uint16_t addr, uint16_t reg, void *data, size_t len, uint8_t flags)
Convenience function for reading several bytes from a given register address.
int i2c_read_byte (_i2c_bus_t *bus, uint16_t addr, void *data, uint8_t flags)
Convenience function for reading one byte from a device.
int i2c_read_bytes (_i2c_bus_t *bus, uint16_t addr, void *data, size_t len, uint8_t flags)
Convenience function for reading bytes from a device.
int i2c_write_byte (_i2c_bus_t *bus, uint16_t addr, uint8_t data, uint8_t flags)
Convenience function for writing a single byte onto the bus.
int i2c_write_bytes (_i2c_bus_t *bus, uint16_t addr, const void *data, size_t len, uint8_t flags)
Convenience function for writing several bytes onto the bus.
int i2c_write_reg (_i2c_bus_t *bus, uint16_t addr, uint16_t reg, uint8_t data, uint8_t flags)
Convenience function for writing one byte to a given register address.
int i2c_write_regs (_i2c_bus_t *bus, uint16_t addr, uint16_t reg, const void *data, size_t len, uint8_t flags)
Convenience function for writing data to a given register address.
enum i2c_speed_t {
I2C_SPEED_LOW = 0 , I2C_SPEED_NORMAL , I2C_SPEED_FAST , I2C_SPEED_FAST_PLUS ,
I2C_SPEED_HIGH
}
Default mapping of I2C bus speed values.
enum i2c_flags_t { I2C_ADDR10 = 0x01 , I2C_REG16 = 0x02 , I2C_NOSTOP = 0x04 , I2C_NOSTART = 0x08 }
I2C transfer flags.
typedef unsigned int i2c_t
Default i2c_t type definition.
#define I2C_DEV(x) (x)
Default I2C device access macro.
#define I2C_UNDEF (UINT_MAX)
Default I2C undefined value.
Detailed Description
Low-level I2C peripheral driver.
This interface provides a simple abstraction to use the MCUs I2C peripherals. It provides support for 7-bit and 10-bit addressing and can be used for different kind of register addressing schemes.
Usage
Example for reading a 8-bit register on a device, using a 10-bit device address and 8-bit register addresses and using a RESTART condition (CAUTION: this example does not check any return values...):
// initialize the bus (this is normally done during boot time)
i2c_init(dev);
...
// before accessing the bus, we need to acquire it
i2c_acquire(dev);
// next we write the register address, but create no STOP condition when done
i2c_write_byte(dev, device_addr, reg_addr, (I2C_NOSTOP | I2C_ADDR10));
// and now we read the register value
i2c_read_byte(dev, device_addr, &reg_value, I2C_ADDR10);
// finally we have to release the bus
i2c_release(dev);
Example for writing a 16-bit register with 16-bit register addressing and 7-bit device addressing:
// initialize the bus
i2c_init(dev);
...
// first, acquire the shared bus again
i2c_acquire(dev);
// write the 16-bit register address to the device and prevent STOP condition
i2c_write_byte(dev, device_addr, reg_addr, I2C_NOSTOP);
// and write the data after a REPEATED START
i2c_write_bytes(dev, device_addr, reg_data, 2, 0);
// and finally free the bus again
i2c_release(dev);
Pull Resistors
The I2C signal lines SDA/SCL need external pull-up resistors which connect the lines to the positive voltage supply Vcc. The I2C driver implementation should enable the pin's internal pull-up resistors. There are however some use cases for which the internal pull resistors are not strong enough and the I2C bus will show faulty behavior. This can for example happen when connecting a logic analyzer which will raise the capacitance of the bus. In this case you should make sure you connect external pull-up resistors to both I2C bus lines.
The minimum and maximum resistances are computed by:
where:
Supply voltage, Low level voltage, Low level output current, Signal rise time, Bus capacitance
The pull-up resistors depend on the bus speed. Some typical values are:
Normal mode: 10kΩ
Fast mode: 2kΩ
Fast plus mode: 2kΩ
For more details refer to section 7.1 in:
http://www.nxp.com/documents/user_manual/UM10204.pdf
(Low-) power implications
The I2C interface realizes a transaction-based access scheme to the bus. From a power management perspective, we can leverage this by only powering on the I2C peripheral while it is actually used, that is inside an i2c_acquire() - i2c_release() block.
After initialization, the I2C peripheral should be powered off (e.g. through peripheral clock gating). It should only be powered on once a transaction on the I2C bus starts, namely in the i2c_acquire() function. Once the transaction is finished, the corresponding I2C peripheral should be powered off again in the i2c_release() function.
If the implementation puts the active thread to sleep while a transfer is in progress (e.g. when using DMA), the implementation might need to block certain power states.
Macro Definition Documentation
I2C_10BIT_MAGIC
#define I2C_10BIT_MAGIC (0xF0u)
Special bit pattern indicating a 10 bit address is used.
Should only be used internally in CPU driver implementations, this is not intended to be used by applications.
See also
https://www.i2c-bus.org/addressing/10-bit-addressing/
Definition at line 168 of file i2c_sw.h.
I2C_DEV
#define I2C_DEV (x) (x)
Default I2C device access macro.
Definition at line 133 of file i2c_sw.h.
I2C_READ
#define I2C_READ (0x0001)
Read bit needs to be set when reading.
Definition at line 158 of file i2c_sw.h.
Referenced by i2c_read_bytes().
I2C_UNDEF
#define I2C_UNDEF (UINT_MAX)
Default I2C undefined value.
Definition at line 142 of file i2c_sw.h.
Typedef Documentation
i2c_t
typedef unsigned int i2c_t
Default i2c_t type definition.
Definition at line 151 of file i2c_sw.h.
Enumeration Type Documentation
i2c_flags_t
enum i2c_flags_t
I2C transfer flags.
Enumerator
I2C_ADDR10
use 10-bit device addressing
I2C_REG16
use 16-bit register addressing, big-endian
I2C_NOSTOP
do not issue a STOP condition after transfer
I2C_NOSTART
skip START sequence, ignores address field
Definition at line 187 of file i2c_sw.h.
i2c_speed_t
enum i2c_speed_t
Default mapping of I2C bus speed values.
Enumerator
I2C_SPEED_LOW
low speed mode: ~10 kbit/s
I2C_SPEED_NORMAL
normal mode: ~100 kbit/s
I2C_SPEED_FAST
fast mode: ~400 kbit/s
I2C_SPEED_FAST_PLUS
fast plus mode: ~1000 kbit/s
I2C_SPEED_HIGH
high speed mode: ~3400 kbit/s
Definition at line 174 of file i2c_sw.h.
Function Documentation
i2c_init()
void i2c_init (_i2c_bus_t * bus)
Initialize the given I2C bus.
The given I2C device will be initialized with the parameters as specified in the boards periph_conf.h, using the pins and the speed value given there.
The bus MUST not be acquired before initializing it, as this is handled internally by the i2c_init function!
Parameters
[in] dev the device to initialize
Definition at line 113 of file i2c_sw.c.
Referenced by ESP32::I2CDeviceManager::I2CDeviceManager(), and setup().
i2c_read_byte()
int i2c_read_byte (_i2c_bus_t * bus, uint16_t addr, void * data, uint8_t flags)
Convenience function for reading one byte from a device.
Note
This function is using a repeated start sequence for reading from the specified register address.
Precondition
i2c_acquire must be called before accessing the bus
Parameters
[in] dev I2C peripheral device
[in] addr 7-bit or 10-bit device address (right-aligned)
[out] data memory location to store received data
[in] flags optional flags (see i2c_flags_t)
Returns
0 When success
-EIO When slave device doesn't ACK the byte
-ENXIO When no devices respond on the address sent on the bus
-ETIMEDOUT When timeout occurs before device's response
-EINVAL When an invalid argument is given
-EOPNOTSUPP When MCU driver doesn't support the flag operation
-EAGAIN When a lost bus arbitration occurs
Definition at line 688 of file i2c_sw.c.
i2c_read_bytes()
int i2c_read_bytes (_i2c_bus_t * bus, uint16_t addr, void * data, size_t len, uint8_t flags)
Convenience function for reading bytes from a device.
Note
This function is using a repeated start sequence for reading from the specified register address.
Precondition
i2c_acquire must be called before accessing the bus
Parameters
[in] dev I2C peripheral device
[in] addr 7-bit or 10-bit device address (right-aligned)
[out] data memory location to store received data
[in] len the number of bytes to read into data
[in] flags optional flags (see i2c_flags_t)
Returns
0 When success
-EIO When slave device doesn't ACK the byte
-ENXIO When no devices respond on the address sent on the bus
-ETIMEDOUT When timeout occurs before device's response
-EINVAL When an invalid argument is given
-EOPNOTSUPP When MCU driver doesn't support the flag operation
-EAGAIN When a lost bus arbitration occurs
Definition at line 168 of file i2c_sw.c.
Referenced by i2c_read_byte(), i2c_read_regs(), and ESP32::I2CDevice::transfer().
i2c_read_reg()
int i2c_read_reg (_i2c_bus_t * bus, uint16_t addr, uint16_t reg, void * data, uint8_t flags)
Convenience function for reading one byte from a given register address.
Note
This function is using a repeated start sequence for reading from the specified register address.
Precondition
i2c_acquire must be called before accessing the bus
Parameters
[in] dev I2C peripheral device
[in] reg register address to read from (8- or 16-bit, right-aligned)
[in] addr 7-bit or 10-bit device address (right-aligned)
[out] data memory location to store received data
[in] flags optional flags (see i2c_flags_t)
Returns
0 When success
-EIO When slave device doesn't ACK the byte
-ENXIO When no devices respond on the address sent on the bus
-ETIMEDOUT When timeout occurs before device's response
-EINVAL When an invalid argument is given
-EOPNOTSUPP When MCU driver doesn't support the flag operation
-EAGAIN When a lost bus arbitration occurs
Definition at line 681 of file i2c_sw.c.
i2c_read_regs()
int i2c_read_regs (_i2c_bus_t * bus, uint16_t addr, uint16_t reg, void * data, size_t len, uint8_t flags)
Convenience function for reading several bytes from a given register address.
Note
This function is using a repeated start sequence for reading from the specified register address.
Precondition
i2c_acquire must be called before accessing the bus
Parameters
[in] dev I2C peripheral device
[in] reg register address to read from (8- or 16-bit, right-aligned)
[in] addr 7-bit or 10-bit device address (right-aligned)
[out] data memory location to store received data
[in] len the number of bytes to read into data
[in] flags optional flags (see i2c_flags_t)
Returns
0 When success
-EIO When slave device doesn't ACK the byte
-ENXIO When no devices respond on the address sent on the bus
-ETIMEDOUT When timeout occurs before device's response
-EINVAL When an invalid argument is given
-EOPNOTSUPP When MCU driver doesn't support the flag operation
-EAGAIN When a lost bus arbitration occurs
Definition at line 657 of file i2c_sw.c.
Referenced by i2c_read_reg().
i2c_write_byte()
int i2c_write_byte (_i2c_bus_t * bus, uint16_t addr, uint8_t data, uint8_t flags)
Convenience function for writing a single byte onto the bus.
Precondition
i2c_acquire must be called before accessing the bus
Parameters
[in] dev I2C peripheral device
[in] addr 7-bit or 10-bit device address (right-aligned)
[in] data byte to write to the device
[in] flags optional flags (see i2c_flags_t)
Returns
0 When success
-EIO When slave device doesn't ACK the byte
-ENXIO When no devices respond on the address sent on the bus
-ETIMEDOUT When timeout occurs before device's response
-EINVAL When an invalid argument is given
-EOPNOTSUPP When MCU driver doesn't support the flag operation
-EAGAIN When a lost bus arbitration occurs
Definition at line 693 of file i2c_sw.c.
i2c_write_bytes()
int i2c_write_bytes (_i2c_bus_t * bus, uint16_t addr, const void * data, size_t len, uint8_t flags)
Convenience function for writing several bytes onto the bus.
Precondition
i2c_acquire must be called before accessing the bus
Parameters
[in] dev I2C peripheral device
[in] addr 7-bit or 10-bit device address (right-aligned)
[in] data array holding the bytes to write to the device
[in] len the number of bytes to write
[in] flags optional flags (see i2c_flags_t)
Returns
0 When success
-EIO When slave device doesn't ACK the byte
-ENXIO When no devices respond on the address sent on the bus
-ETIMEDOUT When timeout occurs before device's response
-EINVAL When an invalid argument is given
-EOPNOTSUPP When MCU driver doesn't support the flag operation
-EAGAIN When a lost bus arbitration occurs
Definition at line 220 of file i2c_sw.c.
Referenced by i2c_read_regs(), i2c_write_byte(), i2c_write_regs(), and ESP32::I2CDevice::transfer().
i2c_write_reg()
int i2c_write_reg (_i2c_bus_t * bus, uint16_t addr, uint16_t reg, uint8_t data, uint8_t flags)
Convenience function for writing one byte to a given register address.
Note
This function is using a continuous sequence for writing to the specified register address. It first writes the register then data.
Precondition
i2c_acquire must be called before accessing the bus
Parameters
[in] dev I2C peripheral device
[in] reg register address to read from (8- or 16-bit, right-aligned)
[in] addr 7-bit or 10-bit device address (right-aligned)
[in] data byte to write
[in] flags optional flags (see i2c_flags_t)
Returns
0 When success
-EIO When slave device doesn't ACK the byte
-ENXIO When no devices respond on the address sent on the bus
-ETIMEDOUT When timeout occurs before device's response
-EINVAL When an invalid argument is given
-EOPNOTSUPP When MCU driver doesn't support the flag operation
-EAGAIN When a lost bus arbitration occurs
Definition at line 722 of file i2c_sw.c.
i2c_write_regs()
int i2c_write_regs (_i2c_bus_t * bus, uint16_t addr, uint16_t reg, const void * data, size_t len, uint8_t flags)
Convenience function for writing data to a given register address.
Note
This function is using a continuous sequence for writing to the specified register address. It first writes the register then data.
Precondition
i2c_acquire must be called before accessing the bus
Parameters
[in] dev I2C peripheral device
[in] reg register address to read from (8- or 16-bit, right-aligned)
[in] addr 7-bit or 10-bit device address (right-aligned)
[out] data memory location to store received data
[in] len the number of bytes to write
[in] flags optional flags (see i2c_flags_t)
Returns
0 When success
-EIO When slave device doesn't ACK the byte
-ENXIO When no devices respond on the address sent on the bus
-ETIMEDOUT When timeout occurs before device's response
-EINVAL When an invalid argument is given
-EOPNOTSUPP When MCU driver doesn't support the flag operation
-EAGAIN When a lost bus arbitration occurs
Definition at line 698 of file i2c_sw.c.
Referenced by i2c_write_reg().