APM:Libraries: libraries/AP_HAL_SITL/HAL_SITL_Class.cpp File Reference
HAL_SITL_Class.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <assert.h>
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "AP_HAL_SITL.h"
#include "AP_HAL_SITL_Namespace.h"
#include "HAL_SITL_Class.h"
#include "Scheduler.h"
#include "AnalogIn.h"
#include "UARTDriver.h"
#include "I2CDevice.h"
#include "Storage.h"
#include "RCInput.h"
#include "RCOutput.h"
#include "GPIO.h"
#include "SITL_State.h"
#include "Util.h"
#include "DSP.h"
#include "CANSocketIface.h"
#include "SPIDevice.h"
#include <AP_BoardConfig/AP_BoardConfig.h>
#include <AP_HAL_Empty/AP_HAL_Empty.h>
#include <AP_HAL_Empty/AP_HAL_Empty_Private.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_Logger/AP_Logger.h>
#include <AP_RCProtocol/AP_RCProtocol_config.h>
Functions
static bool watchdog_save (const uint32_t *data, uint32_t nwords)
static bool watchdog_load (uint32_t *data, uint32_t nwords)
static void sig_alrm (int signum)
static void fill_stack_nan (void)
Variables
HAL_SITL & hal_sitl = (HAL_SITL&)AP_HAL::get_HAL_mutable()
static Storage sitlStorage
static SITL_State sitlState
static Empty::RCInput sitlRCInput
static Empty::OpticalFlow emptyOpticalFlow
static Empty::Flash emptyFlash
static UARTDriver sitlSerial0Driver (0, &sitlState)
static UARTDriver sitlSerial1Driver (1, &sitlState)
static UARTDriver sitlSerial2Driver (2, &sitlState)
static UARTDriver sitlSerial3Driver (3, &sitlState)
static UARTDriver sitlSerial4Driver (4, &sitlState)
static UARTDriver sitlSerial5Driver (5, &sitlState)
static UARTDriver sitlSerial6Driver (6, &sitlState)
static UARTDriver sitlSerial7Driver (7, &sitlState)
static UARTDriver sitlSerial8Driver (8, &sitlState)
static UARTDriver sitlSerial9Driver (9, &sitlState)
static I2CDeviceManager i2c_mgr_instance
static SPIDeviceManager spi_mgr_instance
static Empty::WSPIDeviceManager wspi_mgr_instance
static char * new_argv [100]
static HAL_SITL hal_sitl_inst
Function Documentation
fill_stack_nan()
static void fill_stack_nan (void) static
Definition at line 191 of file HAL_SITL_Class.cpp.
Referenced by HAL_SITL::run().
sig_alrm()
static void sig_alrm (int signum) static
Definition at line 159 of file HAL_SITL_Class.cpp.
Referenced by HAL_SITL::run().
watchdog_load()
static bool watchdog_load (uint32_t * data, uint32_t nwords) static
Definition at line 145 of file HAL_SITL_Class.cpp.
Referenced by HAL_SITL::run().
watchdog_save()
static bool watchdog_save (const uint32_t * data, uint32_t nwords) static
Definition at line 129 of file HAL_SITL_Class.cpp.
Referenced by HAL_SITL::run().
Variable Documentation
emptyFlash
Empty::Flash emptyFlash static
Definition at line 59 of file HAL_SITL_Class.cpp.
emptyOpticalFlow
Empty::OpticalFlow emptyOpticalFlow static
Definition at line 58 of file HAL_SITL_Class.cpp.
hal_sitl
HAL_SITL& hal_sitl = (HAL_SITL&)AP_HAL::get_HAL_mutable()
Definition at line 39 of file HAL_SITL_Class.cpp.
Referenced by SITL::JEDEC::open_storage_fd(), and SITL::RAMTRON::open_storage_fd().
hal_sitl_inst
HAL_SITL hal_sitl_inst static
Definition at line 309 of file HAL_SITL_Class.cpp.
i2c_mgr_instance
I2CDeviceManager i2c_mgr_instance static
Definition at line 72 of file HAL_SITL_Class.cpp.
new_argv
char* new_argv[100] static
Definition at line 124 of file HAL_SITL_Class.cpp.
Referenced by HAL_SITL::actually_reboot(), HAL_SITL::run(), and sig_alrm().
sitlRCInput
Empty::RCInput sitlRCInput static
Definition at line 47 of file HAL_SITL_Class.cpp.
sitlSerial0Driver
UARTDriver sitlSerial0Driver(0, &sitlState) (0 , & sitlState) static
sitlSerial1Driver
UARTDriver sitlSerial1Driver(1, &sitlState) (1 , & sitlState) static
sitlSerial2Driver
UARTDriver sitlSerial2Driver(2, &sitlState) (2 , & sitlState) static
sitlSerial3Driver
UARTDriver sitlSerial3Driver(3, &sitlState) (3 , & sitlState) static
sitlSerial4Driver
UARTDriver sitlSerial4Driver(4, &sitlState) (4 , & sitlState) static
sitlSerial5Driver
UARTDriver sitlSerial5Driver(5, &sitlState) (5 , & sitlState) static
sitlSerial6Driver
UARTDriver sitlSerial6Driver(6, &sitlState) (6 , & sitlState) static
sitlSerial7Driver
UARTDriver sitlSerial7Driver(7, &sitlState) (7 , & sitlState) static
sitlSerial8Driver
UARTDriver sitlSerial8Driver(8, &sitlState) (8 , & sitlState) static
sitlSerial9Driver
UARTDriver sitlSerial9Driver(9, &sitlState) (9 , & sitlState) static
sitlState
static Util utilInstance & sitlState static
Definition at line 42 of file HAL_SITL_Class.cpp.
Referenced by HALSITL::Util::set_cmdline_parameters(), and HALSITL::UARTDriver::UARTDriver().
sitlStorage
Storage sitlStorage static
Definition at line 41 of file HAL_SITL_Class.cpp.
spi_mgr_instance
SPIDeviceManager spi_mgr_instance static
Definition at line 77 of file HAL_SITL_Class.cpp.
wspi_mgr_instance
Empty::WSPIDeviceManager wspi_mgr_instance static
Definition at line 85 of file HAL_SITL_Class.cpp.