APM:Libraries: libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.h File Reference
HAL_ChibiOS_Class.h File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_HAL_Empty/AP_HAL_Empty_Namespace.h>
#include <AP_HAL_ChibiOS/AP_HAL_ChibiOS_Namespace.h>
#include "hwdef/common/halconf.h"
#include <stdio.h>
#include "ch.h"
Classes
class HAL_ChibiOS
Functions
void hal_chibios_set_priority (uint8_t priority)
thread_t * get_main_thread (void)
Function Documentation
get_main_thread()
thread_t * get_main_thread (void)
Definition at line 200 of file HAL_ChibiOS_Class.cpp.
Referenced by ChibiOS::Scheduler::in_main_thread(), ESP32::Util::thread_info(), and ChibiOS::Scheduler::try_force_mutex().
hal_chibios_set_priority()
void hal_chibios_set_priority (uint8_t priority)
Definition at line 187 of file HAL_ChibiOS_Class.cpp.
Referenced by ChibiOS::Scheduler::boost_end(), main_loop(), and set_high_priority().