APM:Libraries: libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp File Reference
HAL_ChibiOS_Class.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <assert.h>
#include <hal.h>
#include "HAL_ChibiOS_Class.h"
#include <AP_HAL_Empty/AP_HAL_Empty_Private.h>
#include <AP_HAL_ChibiOS/AP_HAL_ChibiOS_Private.h>
#include "shared_dma.h"
#include "sdcard.h"
#include "hwdef/common/usbcfg.h"
#include "hwdef/common/stm32_util.h"
#include "hwdef/common/watchdog.h"
#include <AP_BoardConfig/AP_BoardConfig.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_Logger/AP_Logger.h>
#include <AP_Vehicle/AP_Vehicle_Type.h>
#include <AP_HAL/SIMState.h>
#include <hwdef.h>
Macros
#define SERIAL0_BAUD 115200
Functions
void hal_chibios_set_priority (uint8_t priority)
thread_t * get_main_thread ()
static void main_loop ()
Variables
static HAL_SERIAL0_DRIVER
static HAL_SERIAL1_DRIVER
static HAL_SERIAL2_DRIVER
static HAL_SERIAL3_DRIVER
static HAL_SERIAL4_DRIVER
static HAL_SERIAL5_DRIVER
static HAL_SERIAL6_DRIVER
static HAL_SERIAL7_DRIVER
static HAL_SERIAL8_DRIVER
static HAL_SERIAL9_DRIVER
static Empty::I2CDeviceManager i2cDeviceManager
static ChibiOS::SPIDeviceManager spiDeviceManager
static ChibiOS::AnalogIn analogIn
static ChibiOS::Storage storageDriver
static ChibiOS::GPIO gpioDriver
static ChibiOS::RCInput rcinDriver
static ChibiOS::RCOutput rcoutDriver
static ChibiOS::Scheduler schedulerInstance
static ChibiOS::Util utilInstance
static Empty::OpticalFlow opticalFlowDriver
static ChibiOS::Flash flashDriver
static bool thread_running = false
static thread_t * daemon_task
const AP_HAL::HAL & hal
static AP_HAL::HAL::Callbacks * g_callbacks
static HAL_ChibiOS hal_chibios
Macro Definition Documentation
SERIAL0_BAUD
#define SERIAL0_BAUD 115200
Definition at line 42 of file HAL_ChibiOS_Class.cpp.
Referenced by main_loop().
Function Documentation
get_main_thread()
thread_t * get_main_thread (void)
Definition at line 200 of file HAL_ChibiOS_Class.cpp.
Referenced by ChibiOS::Scheduler::in_main_thread(), ESP32::Util::thread_info(), and ChibiOS::Scheduler::try_force_mutex().
hal_chibios_set_priority()
void hal_chibios_set_priority (uint8_t priority)
Definition at line 187 of file HAL_ChibiOS_Class.cpp.
Referenced by ChibiOS::Scheduler::boost_end(), main_loop(), and set_high_priority().
main_loop()
static void main_loop () static
Definition at line 207 of file HAL_ChibiOS_Class.cpp.
Referenced by HAL_ChibiOS::run().
Variable Documentation
analogIn
ChibiOS::AnalogIn analogIn static
Definition at line 84 of file HAL_ChibiOS_Class.cpp.
daemon_task
thread_t* daemon_task static
Handle of daemon task / thread
Definition at line 179 of file HAL_ChibiOS_Class.cpp.
Referenced by get_main_thread(), hal_chibios_set_priority(), and main_loop().
flashDriver
ChibiOS::Flash flashDriver static
Definition at line 116 of file HAL_ChibiOS_Class.cpp.
g_callbacks
AP_HAL::HAL::Callbacks* g_callbacks static
Definition at line 205 of file HAL_ChibiOS_Class.cpp.
Referenced by main_loop(), and HAL_ChibiOS::run().
gpioDriver
ChibiOS::GPIO gpioDriver static
Definition at line 94 of file HAL_ChibiOS_Class.cpp.
hal
const AP_HAL::HAL& hal extern
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.
Referenced by main_loop().
hal_chibios
HAL_ChibiOS hal_chibios static
Definition at line 353 of file HAL_ChibiOS_Class.cpp.
Referenced by AP_HAL::get_HAL(), and AP_HAL::get_HAL_mutable().
HAL_SERIAL0_DRIVER
HAL_SERIAL0_DRIVER static
Definition at line 48 of file HAL_ChibiOS_Class.cpp.
HAL_SERIAL1_DRIVER
HAL_SERIAL1_DRIVER static
Definition at line 49 of file HAL_ChibiOS_Class.cpp.
HAL_SERIAL2_DRIVER
HAL_SERIAL2_DRIVER static
Definition at line 50 of file HAL_ChibiOS_Class.cpp.
HAL_SERIAL3_DRIVER
HAL_SERIAL3_DRIVER static
Definition at line 51 of file HAL_ChibiOS_Class.cpp.
HAL_SERIAL4_DRIVER
HAL_SERIAL4_DRIVER static
Definition at line 52 of file HAL_ChibiOS_Class.cpp.
HAL_SERIAL5_DRIVER
HAL_SERIAL5_DRIVER static
Definition at line 53 of file HAL_ChibiOS_Class.cpp.
HAL_SERIAL6_DRIVER
HAL_SERIAL6_DRIVER static
Definition at line 54 of file HAL_ChibiOS_Class.cpp.
HAL_SERIAL7_DRIVER
HAL_SERIAL7_DRIVER static
Definition at line 55 of file HAL_ChibiOS_Class.cpp.
HAL_SERIAL8_DRIVER
HAL_SERIAL8_DRIVER static
Definition at line 56 of file HAL_ChibiOS_Class.cpp.
HAL_SERIAL9_DRIVER
HAL_SERIAL9_DRIVER static
Definition at line 57 of file HAL_ChibiOS_Class.cpp.
i2cDeviceManager
Empty::I2CDeviceManager i2cDeviceManager static
Definition at line 74 of file HAL_ChibiOS_Class.cpp.
opticalFlowDriver
Empty::OpticalFlow opticalFlowDriver static
Definition at line 105 of file HAL_ChibiOS_Class.cpp.
rcinDriver
ChibiOS::RCInput rcinDriver static
Definition at line 95 of file HAL_ChibiOS_Class.cpp.
rcoutDriver
ChibiOS::RCOutput rcoutDriver static
Definition at line 98 of file HAL_ChibiOS_Class.cpp.
schedulerInstance
ChibiOS::Scheduler schedulerInstance static
Definition at line 103 of file HAL_ChibiOS_Class.cpp.
Referenced by main_loop().
spiDeviceManager
ChibiOS::SPIDeviceManager spiDeviceManager static
Definition at line 78 of file HAL_ChibiOS_Class.cpp.
storageDriver
ChibiOS::Storage storageDriver static
Definition at line 92 of file HAL_ChibiOS_Class.cpp.
thread_running
bool thread_running = false static
Daemon status flag
Definition at line 178 of file HAL_ChibiOS_Class.cpp.
Referenced by main_loop().
utilInstance
ChibiOS::Util utilInstance static
Definition at line 104 of file HAL_ChibiOS_Class.cpp.
Referenced by main_loop(), HAL_Linux::run(), and HAL_SITL::run().