APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/hrt.h File Reference
hrt.h File Reference
Functions
void hrt_init (void)
uint64_t hrt_micros64 (void)
uint64_t hrt_micros64_from_ISR (void)
uint32_t hrt_micros32 (void)
uint32_t hrt_millis32 (void)
uint32_t hrt_millis32I (void)
uint32_t hrt_millis32_from_ISR (void)
uint64_t hrt_millis64 (void)
Function Documentation
hrt_init()
void hrt_init (void)
hrt_micros32()
uint32_t hrt_micros32 (void)
Definition at line 122 of file hrt.c.
Referenced by AP_HAL::micros(), and AP_HAL::micros16().
hrt_micros64()
uint64_t hrt_micros64 (void)
Definition at line 103 of file hrt.c.
Referenced by hrt_millis64(), AP_HAL::micros64(), stm32_get_utc_usec(), and stm32_set_utc_usec().
hrt_micros64_from_ISR()
uint64_t hrt_micros64_from_ISR (void)
hrt_millis32()
uint32_t hrt_millis32 (void)
Definition at line 153 of file hrt.c.
Referenced by AP_HAL::millis(), AP_HAL::millis16(), stm32_flash_erasepage(), and stm32_flash_recent_erase().
hrt_millis32_from_ISR()
uint32_t hrt_millis32_from_ISR (void)
hrt_millis32I()
uint32_t hrt_millis32I (void)
hrt_millis64()
uint64_t hrt_millis64 (void)
Definition at line 148 of file hrt.c.
Referenced by hrt_millis32(), and AP_HAL::millis64().