APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/hrt.c File Reference
hrt.c File Reference
#include "ch.h"
#include "hal.h"
#include "hrt.h"
#include <stdint.h>
#include "../../../AP_Math/div1000.h"
Functions
static uint32_t get_systime_us32 (void)
static uint64_t hrt_micros64I (void)
static bool is_locked (void)
uint64_t hrt_micros64 ()
uint32_t hrt_micros32 ()
uint64_t hrt_millis64 ()
uint32_t hrt_millis32 ()
Function Documentation
get_systime_us32()
static uint32_t get_systime_us32 (void) static
Definition at line 73 of file hrt.c.
Referenced by hrt_micros32().
hrt_micros32()
uint32_t hrt_micros32 (void)
Definition at line 122 of file hrt.c.
Referenced by AP_HAL::micros(), and AP_HAL::micros16().
hrt_micros64()
uint64_t hrt_micros64 (void)
Definition at line 103 of file hrt.c.
Referenced by hrt_millis64(), AP_HAL::micros64(), stm32_get_utc_usec(), and stm32_set_utc_usec().
hrt_micros64I()
static uint64_t hrt_micros64I (void) static
Definition at line 87 of file hrt.c.
Referenced by hrt_micros64().
hrt_millis32()
uint32_t hrt_millis32 (void)
Definition at line 153 of file hrt.c.
Referenced by AP_HAL::millis(), AP_HAL::millis16(), stm32_flash_erasepage(), and stm32_flash_recent_erase().
hrt_millis64()
uint64_t hrt_millis64 (void)
Definition at line 148 of file hrt.c.
Referenced by hrt_millis32(), and AP_HAL::millis64().
is_locked()
static bool is_locked (void) inline static
Definition at line 99 of file hrt.c.
Referenced by hrt_micros32(), and hrt_micros64().