APM:Libraries: libraries/AP_HAL_ESP32/i2c_sw.c File Reference
i2c_sw.c File Reference
I2C
Low-level I2C driver software implementation using for ESP SoCs.
#include "esp_err.h"
#include <assert.h>
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include "esp_attr.h"
#include "rom/ets_sys.h"
#include "soc/gpio_reg.h"
#include "soc/gpio_struct.h"
#include <string.h>
#include "esp_types.h"
#include "esp_intr_alloc.h"
#include "esp_log.h"
#include "malloc.h"
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "freertos/xtensa_api.h"
#include "freertos/task.h"
#include "freertos/ringbuf.h"
#include "soc/dport_reg.h"
#include "esp_pm.h"
#include "soc/soc_memory_layout.h"
#include "soc/i2c_periph.h"
#include "driver/i2c.h"
#include "driver/periph_ctrl.h"
#include "lwip/netdb.h"
#include "i2c_sw.h"
Macros
#define DEBUG printf
#define I2C_CLOCK_STRETCH 200
#define GPIO_SET(l, h, b) if (b < 32) GPIO.l = BIT(b); else GPIO.h.val = BIT(b-32)
#define GPIO_GET(l, h, b) ((b < 32) ? GPIO.l & BIT(b) : GPIO.h.val & BIT(b-32))
Functions
static void _i2c_delay (_i2c_bus_t *bus)
static bool _i2c_scl_read (_i2c_bus_t *bus)
static bool _i2c_sda_read (_i2c_bus_t *bus)
static void _i2c_scl_high (_i2c_bus_t *bus)
static void _i2c_scl_low (_i2c_bus_t *bus)
static void _i2c_sda_high (_i2c_bus_t *bus)
static void _i2c_sda_low (_i2c_bus_t *bus)
static int _i2c_start_cond (_i2c_bus_t *bus)
static int _i2c_stop_cond (_i2c_bus_t *bus)
static int _i2c_write_bit (_i2c_bus_t *bus, bool bit)
static int _i2c_read_bit (_i2c_bus_t *bus, bool *bit)
static int _i2c_write_byte (_i2c_bus_t *bus, uint8_t byte)
static int _i2c_read_byte (_i2c_bus_t *bus, uint8_t *byte, bool ack)
static int _i2c_arbitration_lost (_i2c_bus_t *bus, const char *func)
static void _i2c_abort (_i2c_bus_t *bus, const char *func)
static void _i2c_clear (_i2c_bus_t *bus)
void i2c_init (_i2c_bus_t *bus)
Initialize the given I2C bus.
int IRAM_ATTR i2c_read_bytes (_i2c_bus_t *bus, uint16_t addr, void *data, size_t len, uint8_t flags)
Convenience function for reading bytes from a device.
int IRAM_ATTR i2c_write_bytes (_i2c_bus_t *bus, uint16_t addr, const void *data, size_t len, uint8_t flags)
Convenience function for writing several bytes onto the bus.
int i2c_read_regs (_i2c_bus_t *bus, uint16_t addr, uint16_t reg, void *data, size_t len, uint8_t flags)
Convenience function for reading several bytes from a given register address.
int i2c_read_reg (_i2c_bus_t *bus, uint16_t addr, uint16_t reg, void *data, uint8_t flags)
Convenience function for reading one byte from a given register address.
int i2c_read_byte (_i2c_bus_t *bus, uint16_t addr, void *data, uint8_t flags)
Convenience function for reading one byte from a device.
int i2c_write_byte (_i2c_bus_t *bus, uint16_t addr, uint8_t data, uint8_t flags)
Convenience function for writing a single byte onto the bus.
int i2c_write_regs (_i2c_bus_t *bus, uint16_t addr, uint16_t reg, const void *data, size_t len, uint8_t flags)
Convenience function for writing data to a given register address.
int i2c_write_reg (_i2c_bus_t *bus, uint16_t addr, uint16_t reg, uint8_t data, uint8_t flags)
Convenience function for writing one byte to a given register address.
Variables
static const uint32_t _i2c_delays [][3]
Detailed Description
Low-level I2C driver software implementation using for ESP SoCs.
Author
Gunar Schorcht gunar.nosp@m.@sch.nosp@m.orcht.nosp@m..net
Definition in file i2c_sw.c.
Macro Definition Documentation
DEBUG
#define DEBUG printf
Definition at line 30 of file i2c_sw.c.
Referenced by SITL::I2CRegisters::add_register(), i2c_init(), SITL::I2CRegisters_ConfigurableLength::set_register(), SITL::I2CRegisters_16Bit::set_register(), SITL::I2CRegisters_ConfigurableLength::set_register(), SITL::I2CRegisters_8Bit::set_register(), SITL::I2CRegisters_ConfigurableLength::set_register(), SITL::I2CRegisters_16Bit::set_register(), SITL::I2CRegisters_ConfigurableLength::set_register(), and SITL::I2CRegisters_8Bit::set_register().
GPIO_GET
#define GPIO_GET (l, h, b) ((b < 32) ? GPIO.l & BIT(b) : GPIO.h.val & BIT(b-32))
Definition at line 73 of file i2c_sw.c.
Referenced by _i2c_scl_read(), and _i2c_sda_read().
GPIO_SET
#define GPIO_SET (l, h, b) if (b < 32) GPIO.l = BIT(b); else GPIO.h.val = BIT(b-32)
Definition at line 72 of file i2c_sw.c.
Referenced by _i2c_scl_high(), _i2c_scl_low(), _i2c_sda_high(), and _i2c_sda_low().
I2C_CLOCK_STRETCH
#define I2C_CLOCK_STRETCH 200
Definition at line 69 of file i2c_sw.c.
Referenced by _i2c_read_bit(), _i2c_start_cond(), _i2c_stop_cond(), and _i2c_write_bit().
Function Documentation
_i2c_abort()
static void _i2c_abort (_i2c_bus_t * bus, const char * func) static
Definition at line 376 of file i2c_sw.c.
Referenced by i2c_read_bytes(), and i2c_write_bytes().
_i2c_arbitration_lost()
static IRAM_ATTR int _i2c_arbitration_lost (_i2c_bus_t * bus, const char * func) static
Definition at line 391 of file i2c_sw.c.
Referenced by _i2c_start_cond(), _i2c_stop_cond(), and _i2c_write_bit().
_i2c_clear()
static void _i2c_clear (_i2c_bus_t * bus) static
Sometimes a slave blocks and drives the SDA line permanently low. Send some clock pulses in that case (10 at maximum)
Definition at line 342 of file i2c_sw.c.
Referenced by _i2c_abort(), _i2c_arbitration_lost(), and i2c_init().
_i2c_delay()
static void _i2c_delay (_i2c_bus_t * bus) inline static
Definition at line 274 of file i2c_sw.c.
Referenced by _i2c_clear(), _i2c_read_bit(), _i2c_start_cond(), _i2c_stop_cond(), and _i2c_write_bit().
_i2c_read_bit()
static IRAM_ATTR int _i2c_read_bit (_i2c_bus_t * bus, bool * bit) static
Definition at line 572 of file i2c_sw.c.
Referenced by _i2c_read_byte(), and _i2c_write_byte().
_i2c_read_byte()
static IRAM_ATTR int _i2c_read_byte (_i2c_bus_t * bus, uint8_t * byte, bool ack) static
Definition at line 638 of file i2c_sw.c.
Referenced by i2c_read_bytes().
_i2c_scl_high()
static void _i2c_scl_high (_i2c_bus_t * bus) inline static
Definition at line 310 of file i2c_sw.c.
Referenced by _i2c_abort(), _i2c_arbitration_lost(), _i2c_clear(), _i2c_read_bit(), _i2c_start_cond(), _i2c_stop_cond(), _i2c_write_bit(), and i2c_init().
_i2c_scl_low()
static void _i2c_scl_low (_i2c_bus_t * bus) inline static
Definition at line 318 of file i2c_sw.c.
Referenced by _i2c_clear(), _i2c_read_bit(), _i2c_start_cond(), and _i2c_write_bit().
_i2c_scl_read()
static bool _i2c_scl_read (_i2c_bus_t * bus) inline static
Definition at line 296 of file i2c_sw.c.
Referenced by _i2c_clear(), _i2c_read_bit(), _i2c_start_cond(), _i2c_stop_cond(), and _i2c_write_bit().
_i2c_sda_high()
static void _i2c_sda_high (_i2c_bus_t * bus) inline static
Definition at line 326 of file i2c_sw.c.
Referenced by _i2c_abort(), _i2c_arbitration_lost(), _i2c_read_bit(), _i2c_start_cond(), _i2c_stop_cond(), _i2c_write_bit(), and i2c_init().
_i2c_sda_low()
static void _i2c_sda_low (_i2c_bus_t * bus) inline static
Definition at line 334 of file i2c_sw.c.
Referenced by _i2c_start_cond(), _i2c_stop_cond(), and _i2c_write_bit().
_i2c_sda_read()
static bool _i2c_sda_read (_i2c_bus_t * bus) inline static
Definition at line 303 of file i2c_sw.c.
Referenced by _i2c_clear(), _i2c_read_bit(), _i2c_start_cond(), _i2c_stop_cond(), and _i2c_write_bit().
_i2c_start_cond()
static IRAM_ATTR int _i2c_start_cond (_i2c_bus_t * bus) static
Definition at line 408 of file i2c_sw.c.
Referenced by i2c_read_bytes(), and i2c_write_bytes().
_i2c_stop_cond()
static IRAM_ATTR int _i2c_stop_cond (_i2c_bus_t * bus) static
Definition at line 467 of file i2c_sw.c.
Referenced by i2c_read_bytes(), and i2c_write_bytes().
_i2c_write_bit()
static IRAM_ATTR int _i2c_write_bit (_i2c_bus_t * bus, bool bit) static
Definition at line 521 of file i2c_sw.c.
Referenced by _i2c_read_byte(), and _i2c_write_byte().
_i2c_write_byte()
static IRAM_ATTR int _i2c_write_byte (_i2c_bus_t * bus, uint8_t byte) static
Definition at line 614 of file i2c_sw.c.
Referenced by i2c_read_bytes(), and i2c_write_bytes().
Variable Documentation
_i2c_delays
const uint32_t _i2c_delays[][3] static
Initial value:
=
{
    [I2C_SPEED_LOW]       = {790, 1590, 2390},
    [I2C_SPEED_NORMAL]    = { 70,  150,  230},
    [I2C_SPEED_FAST]      = { 11,   31,   51},
    [I2C_SPEED_FAST_PLUS] = {  0,    7,   15},
    [I2C_SPEED_HIGH]      = {  0,    0,    0}
}
Definition at line 78 of file i2c_sw.c.
Referenced by i2c_init().