APM:Libraries: libraries/AP_FlashIface/examples/jedec_test_bl/jedec_test.cpp File Reference
jedec_test.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_FlashIface/AP_FlashIface.h>
#include <stdio.h>
#include <support.h>
#include <hal.h>
Functions
static UNUSED_FUNCTION void test_page_program ()
static UNUSED_FUNCTION void test_sector_erase ()
static UNUSED_FUNCTION void test_mass_erase ()
int main ()
Variables
AP_FlashIface_JEDEC jedec_dev
Function Documentation
main()
int main ()
Definition at line 146 of file jedec_test.cpp.
Referenced by app_main().
test_mass_erase()
static UNUSED_FUNCTION void test_mass_erase () static
Definition at line 112 of file jedec_test.cpp.
test_page_program()
static UNUSED_FUNCTION void test_page_program () static
Definition at line 9 of file jedec_test.cpp.
Referenced by main().
test_sector_erase()
static UNUSED_FUNCTION void test_sector_erase () static
Definition at line 73 of file jedec_test.cpp.
Referenced by main().
Variable Documentation
jedec_dev
AP_FlashIface_JEDEC jedec_dev
Definition at line 7 of file jedec_test.cpp.
Referenced by main(), test_mass_erase(), test_page_program(), and test_sector_erase().