APM:Libraries: libraries/AP_Scripting/lua/src/lapi.c File Reference
lapi.c File Reference
#include "lprefix.h"
#include <stdarg.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lundump.h"
#include "lvm.h"
Classes
struct CallS
Macros
#define lapi_c
#define LUA_CORE
#define NONVALIDVALUE cast(TValue *, luaO_nilobject)
#define isvalid(o) ((o) != luaO_nilobject)
#define ispseudo(i) ((i) <= LUA_REGISTRYINDEX)
#define isupvalue(i) ((i) < LUA_REGISTRYINDEX)
#define isstackindex(i, o) (isvalid(o) && !ispseudo(i))
#define api_checkvalidindex(l, o) api_check(l, isvalid(o), "invalid index")
#define api_checkstackindex(l, i, o) api_check(l, isstackindex(i, o), "index not in the stack")
#define checkresults(L, na, nr)
Functions
static TValue * index2addr (lua_State *L, int idx)
static void growstack (lua_State *L, void *ud)
LUA_API int lua_checkstack (lua_State *L, int n)
LUA_API void lua_xmove (lua_State *from, lua_State *to, int n)
LUA_API lua_CFunction lua_atpanic (lua_State *L, lua_CFunction panicf)
LUA_API const lua_Number * lua_version (lua_State *L)
LUA_API int lua_absindex (lua_State *L, int idx)
LUA_API int lua_gettop (lua_State *L)
LUA_API void lua_settop (lua_State *L, int idx)
static void reverse (lua_State *L, StkId from, StkId to)
LUA_API void lua_rotate (lua_State *L, int idx, int n)
LUA_API void lua_copy (lua_State *L, int fromidx, int toidx)
LUA_API void lua_pushvalue (lua_State *L, int idx)
LUA_API int lua_type (lua_State *L, int idx)
LUA_API const char * lua_typename (lua_State *L, int t)
LUA_API int lua_iscfunction (lua_State *L, int idx)
LUA_API int lua_isinteger (lua_State *L, int idx)
LUA_API int lua_isnumber (lua_State *L, int idx)
LUA_API int lua_isstring (lua_State *L, int idx)
LUA_API int lua_isuserdata (lua_State *L, int idx)
LUA_API int lua_rawequal (lua_State *L, int index1, int index2)
LUA_API void lua_arith (lua_State *L, int op)
LUA_API int lua_compare (lua_State *L, int index1, int index2, int op)
LUA_API size_t lua_stringtonumber (lua_State *L, const char *s)
LUA_API lua_Number lua_tonumberx (lua_State *L, int idx, int *pisnum)
LUA_API lua_Integer lua_tointegerx (lua_State *L, int idx, int *pisnum)
LUA_API int lua_toboolean (lua_State *L, int idx)
LUA_API const char * lua_tolstring (lua_State *L, int idx, size_t *len)
LUA_API size_t lua_rawlen (lua_State *L, int idx)
LUA_API lua_CFunction lua_tocfunction (lua_State *L, int idx)
LUA_API void * lua_touserdata (lua_State *L, int idx)
LUA_API lua_State * lua_tothread (lua_State *L, int idx)
LUA_API const void * lua_topointer (lua_State *L, int idx)
LUA_API void lua_pushnil (lua_State *L)
LUA_API void lua_pushnumber (lua_State *L, lua_Number n)
LUA_API void lua_pushinteger (lua_State *L, lua_Integer n)
LUA_API const char * lua_pushlstring (lua_State *L, const char *s, size_t len)
LUA_API const char * lua_pushstring (lua_State *L, const char *s)
LUA_API const char * lua_pushvfstring (lua_State *L, const char *fmt, va_list argp)
LUA_API const char * lua_pushfstring (lua_State *L, const char *fmt,...)
LUA_API void lua_pushcclosure (lua_State *L, lua_CFunction fn, int n)
LUA_API void lua_pushboolean (lua_State *L, int b)
LUA_API void lua_pushlightuserdata (lua_State *L, void *p)
LUA_API int lua_pushthread (lua_State *L)
static int auxgetstr (lua_State *L, const TValue *t, const char *k)
LUA_API int lua_getglobal (lua_State *L, const char *name)
LUA_API int lua_gettable (lua_State *L, int idx)
LUA_API int lua_getfield (lua_State *L, int idx, const char *k)
LUA_API int lua_geti (lua_State *L, int idx, lua_Integer n)
LUA_API int lua_rawget (lua_State *L, int idx)
LUA_API int lua_rawgeti (lua_State *L, int idx, lua_Integer n)
LUA_API int lua_rawgetp (lua_State *L, int idx, const void *p)
LUA_API void lua_createtable (lua_State *L, int narray, int nrec)
LUA_API int lua_getmetatable (lua_State *L, int objindex)
LUA_API int lua_getuservalue (lua_State *L, int idx)
static void auxsetstr (lua_State *L, const TValue *t, const char *k)
LUA_API void lua_setglobal (lua_State *L, const char *name)
LUA_API void lua_settable (lua_State *L, int idx)
LUA_API void lua_setfield (lua_State *L, int idx, const char *k)
LUA_API void lua_seti (lua_State *L, int idx, lua_Integer n)
LUA_API void lua_rawset (lua_State *L, int idx)
LUA_API void lua_rawseti (lua_State *L, int idx, lua_Integer n)
LUA_API void lua_rawsetp (lua_State *L, int idx, const void *p)
LUA_API int lua_setmetatable (lua_State *L, int objindex)
LUA_API void lua_setuservalue (lua_State *L, int idx)
LUA_API void lua_callk (lua_State *L, int nargs, int nresults, lua_KContext ctx, lua_KFunction k)
static void f_call (lua_State *L, void *ud)
LUA_API int lua_pcallk (lua_State *L, int nargs, int nresults, int errfunc, lua_KContext ctx, lua_KFunction k)
LUA_API int lua_load (lua_State *L, lua_Reader reader, void *data, const char *chunkname, const char *mode)
LUA_API int lua_dump (lua_State *L, lua_Writer writer, void *data, int strip)
LUA_API int lua_status (lua_State *L)
LUA_API int lua_gc (lua_State *L, int what, int data)
LUA_API int lua_error (lua_State *L)
LUA_API int lua_next (lua_State *L, int idx)
LUA_API void lua_concat (lua_State *L, int n)
LUA_API void lua_len (lua_State *L, int idx)
LUA_API lua_Alloc lua_getallocf (lua_State *L, void **ud)
LUA_API void lua_setallocf (lua_State *L, lua_Alloc f, void *ud)
LUA_API void * lua_newuserdata (lua_State *L, size_t size)
static const char * aux_upvalue (StkId fi, int n, TValue **val, CClosure **owner, UpVal **uv)
LUA_API const char * lua_getupvalue (lua_State *L, int funcindex, int n)
LUA_API const char * lua_setupvalue (lua_State *L, int funcindex, int n)
static UpVal ** getupvalref (lua_State *L, int fidx, int n, LClosure **pf)
LUA_API void * lua_upvalueid (lua_State *L, int fidx, int n)
LUA_API void lua_upvaluejoin (lua_State *L, int fidx1, int n1, int fidx2, int n2)
Variables
const char lua_ident []
Macro Definition Documentation
api_checkstackindex
#define api_checkstackindex (l, i, o) api_check(l, isstackindex(i, o), "index not in the stack")
Definition at line 56 of file lapi.c.
Referenced by lua_pcallk(), and lua_rotate().
api_checkvalidindex
#define api_checkvalidindex (l, o) api_check(l, isvalid(o), "invalid index")
Definition at line 54 of file lapi.c.
Referenced by lua_copy().
checkresults
#define checkresults (L, na, nr)
Value:
     api_check(L, (nr) == LUA_MULTRET || (L->ci->top - L->top >= (nr) - (na)), \
    "results from function overflow current stack size")
Definition at line 904 of file lapi.c.
Referenced by lua_callk(), and lua_pcallk().
ispseudo
#define ispseudo (i) ((i) <= LUA_REGISTRYINDEX)
Definition at line 46 of file lapi.c.
Referenced by index2addr(), and lua_absindex().
isstackindex
#define isstackindex (i, o) (isvalid(o) && !ispseudo(i))
Definition at line 52 of file lapi.c.
isupvalue
#define isupvalue (i) ((i) < LUA_REGISTRYINDEX)
Definition at line 49 of file lapi.c.
Referenced by lua_copy().
isvalid
#define isvalid (o) ((o) != luaO_nilobject)
Definition at line 43 of file lapi.c.
Referenced by lua_compare(), lua_rawequal(), and lua_type().
lapi_c
#define lapi_c
Definition at line 7 of file lapi.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lapi.c.
NONVALIDVALUE
#define NONVALIDVALUE cast(TValue *, luaO_nilobject)
Definition at line 40 of file lapi.c.
Referenced by index2addr().
Function Documentation
aux_upvalue()
static const char * aux_upvalue (StkId fi, int n, TValue ** val, CClosure ** owner, UpVal ** uv) static
Definition at line 1199 of file lapi.c.
Referenced by lua_getupvalue(), and lua_setupvalue().
auxgetstr()
static int auxgetstr (lua_State * L, const TValue * t, const char * k) static
Definition at line 588 of file lapi.c.
Referenced by lua_getfield(), and lua_getglobal().
auxsetstr()
static void auxsetstr (lua_State * L, const TValue * t, const char * k) static
Definition at line 743 of file lapi.c.
Referenced by lua_setfield(), and lua_setglobal().
f_call()
static void f_call (lua_State * L, void * ud) static
Definition at line 941 of file lapi.c.
Referenced by lua_pcallk().
getupvalref()
static UpVal ** getupvalref (lua_State * L, int fidx, int n, LClosure ** pf) static
Definition at line 1259 of file lapi.c.
Referenced by lua_upvalueid(), and lua_upvaluejoin().
growstack()
static void growstack (lua_State * L, void * ud) static
Definition at line 91 of file lapi.c.
Referenced by lua_checkstack().
index2addr()
static TValue * index2addr (lua_State * L, int idx) static
Definition at line 60 of file lapi.c.
Referenced by getupvalref(), lua_compare(), lua_copy(), lua_getfield(), lua_geti(), lua_getmetatable(), lua_gettable(), lua_getupvalue(), lua_getuservalue(), lua_iscfunction(), lua_isinteger(), lua_isnumber(), lua_isstring(), lua_isuserdata(), lua_len(), lua_next(), lua_pcallk(), lua_pushvalue(), lua_rawequal(), lua_rawget(), lua_rawgeti(), lua_rawgetp(), lua_rawlen(), lua_rawset(), lua_rawseti(), lua_rawsetp(), lua_rotate(), lua_setfield(), lua_seti(), lua_setmetatable(), lua_settable(), lua_setupvalue(), lua_setuservalue(), lua_toboolean(), lua_tocfunction(), lua_tointegerx(), lua_tolstring(), lua_tonumberx(), lua_topointer(), lua_tothread(), lua_touserdata(), lua_type(), and lua_upvalueid().
lua_absindex()
LUA_API int lua_absindex (lua_State * L, int idx)
Definition at line 160 of file lapi.c.
Referenced by luaL_callmeta(), luaL_getsubtable(), luaL_ref(), and luaL_unref().
lua_arith()
LUA_API void lua_arith (lua_State * L, int op)
Definition at line 302 of file lapi.c.
lua_atpanic()
LUA_API lua_CFunction lua_atpanic (lua_State * L, lua_CFunction panicf)
Definition at line 134 of file lapi.c.
lua_callk()
LUA_API void lua_callk (lua_State * L, int nargs, int nresults, lua_KContext ctx, lua_KFunction k)
Definition at line 909 of file lapi.c.
Referenced by luaB_dofile().
lua_checkstack()
LUA_API int lua_checkstack (lua_State * L, int n)
Definition at line 97 of file lapi.c.
Referenced by auxresume(), checkstack(), luaL_checkstack(), pmain(), and unpack().
lua_compare()
LUA_API int lua_compare (lua_State * L, int index1, int index2, int op)
Definition at line 318 of file lapi.c.
Referenced by math_max(), math_min(), sort_comp(), and tmove().
lua_concat()
LUA_API void lua_concat (lua_State * L, int n)
Definition at line 1140 of file lapi.c.
Referenced by findfield(), luaB_auxwrap(), luaB_error(), luaL_error(), and luaL_traceback().
lua_copy()
LUA_API void lua_copy (lua_State * L, int fromidx, int toidx)
Definition at line 222 of file lapi.c.
Referenced by pushglobalfuncname().
lua_createtable()
LUA_API void lua_createtable (lua_State * L, int narray, int nrec)
Definition at line 684 of file lapi.c.
Referenced by createclibstable(), createmetatable(), createsearcherstable(), db_sethook(), luaL_newmetatable(), os_date(), and pack().
lua_dump()
LUA_API int lua_dump (lua_State * L, lua_Writer writer, void * data, int strip)
Definition at line 1016 of file lapi.c.
Referenced by str_dump().
lua_error()
LUA_API int lua_error (lua_State * L)
Definition at line 1114 of file lapi.c.
Referenced by luaB_auxwrap(), luaB_dofile(), luaB_error(), and luaL_error().
lua_gc()
LUA_API int lua_gc (lua_State * L, int what, int data)
Definition at line 1040 of file lapi.c.
Referenced by luaB_collectgarbage().
lua_getallocf()
LUA_API lua_Alloc lua_getallocf (lua_State * L, void ** ud)
Definition at line 1166 of file lapi.c.
Referenced by resizebox().
lua_getfield()
LUA_API int lua_getfield (lua_State * L, int idx, const char * k)
Definition at line 622 of file lapi.c.
Referenced by checkclib(), findfile(), findloader(), g_iofile(), getboolfield(), getfield(), getiofile(), io_close(), io_lines(), ll_require(), luaL_getsubtable(), luaL_requiref(), luaopen_table(), noenv(), pushglobalfuncname(), and searcher_preload().
lua_getglobal()
LUA_API int lua_getglobal (lua_State * L, const char * name)
Definition at line 605 of file lapi.c.
Referenced by luaB_print().
lua_geti()
LUA_API int lua_geti (lua_State * L, int idx, lua_Integer n)
Definition at line 628 of file lapi.c.
Referenced by addfield(), auxsort(), ipairsaux(), partition(), tinsert(), tmove(), tremove(), and unpack().
lua_getmetatable()
LUA_API int lua_getmetatable (lua_State * L, int objindex)
Definition at line 697 of file lapi.c.
Referenced by checktab(), db_getmetatable(), luaB_getmetatable(), luaL_getmetafield(), and luaL_testudata().
lua_gettable()
LUA_API int lua_gettable (lua_State * L, int idx)
Definition at line 612 of file lapi.c.
Referenced by add_value().
lua_gettop()
LUA_API int lua_gettop (lua_State * L)
Definition at line 167 of file lapi.c.
Referenced by aux_lines(), auxresume(), dofilecont(), finishpcall(), g_read(), g_write(), luaB_assert(), luaB_auxwrap(), luaB_coresume(), luaB_costatus(), luaB_pcall(), luaB_print(), luaB_select(), luaB_xpcall(), luaB_yield(), luaL_loadfilex(), luaL_traceback(), math_max(), math_min(), math_random(), pack(), pushglobalfuncname(), str_char(), str_format(), tinsert(), and utfchar().
lua_getupvalue()
LUA_API const char * lua_getupvalue (lua_State * L, int funcindex, int n)
Definition at line 1224 of file lapi.c.
Referenced by auxupvalue(), checkupval(), and ll_require().
lua_getuservalue()
LUA_API int lua_getuservalue (lua_State * L, int idx)
Definition at line 724 of file lapi.c.
Referenced by db_getuservalue().
lua_iscfunction()
LUA_API int lua_iscfunction (lua_State * L, int idx)
Definition at line 264 of file lapi.c.
Referenced by db_upvaluejoin().
lua_isinteger()
LUA_API int lua_isinteger (lua_State * L, int idx)
Definition at line 270 of file lapi.c.
Referenced by addliteral(), g_write(), luaL_tolstring(), math_abs(), math_ceil(), math_floor(), math_fmod(), math_modf(), and math_type().
lua_isnumber()
LUA_API int lua_isnumber (lua_State * L, int idx)
Definition at line 276 of file lapi.c.
Referenced by interror().
lua_isstring()
LUA_API int lua_isstring (lua_State * L, int idx)
Definition at line 283 of file lapi.c.
Referenced by add_value(), addfield(), findloader(), generic_reader(), and luaL_tolstring().
lua_isuserdata()
LUA_API int lua_isuserdata (lua_State * L, int idx)
Definition at line 289 of file lapi.c.
lua_len()
LUA_API void lua_len (lua_State * L, int idx)
Definition at line 1156 of file lapi.c.
Referenced by luaL_len().
lua_load()
LUA_API int lua_load (lua_State * L, lua_Reader reader, void * data, const char * chunkname, const char * mode)
Definition at line 992 of file lapi.c.
Referenced by combine(), luaB_load(), luaL_loadbufferx(), and luaL_loadfilex().
lua_newuserdata()
LUA_API void * lua_newuserdata (lua_State * L, size_t size)
Definition at line 1184 of file lapi.c.
Referenced by gmatch(), newbox(), and newprefile().
lua_next()
LUA_API int lua_next (lua_State * L, int idx)
Definition at line 1123 of file lapi.c.
Referenced by findfield(), and luaB_next().
lua_pcallk()
LUA_API int lua_pcallk (lua_State * L, int nargs, int nresults, int errfunc, lua_KContext ctx, lua_KFunction k)
Definition at line 948 of file lapi.c.
Referenced by luaB_pcall(), and luaB_xpcall().
lua_pushboolean()
LUA_API void lua_pushboolean (lua_State * L, int b)
Definition at line 557 of file lapi.c.
Referenced by aux_lines(), finishpcall(), ll_require(), lookforfunc(), luaB_collectgarbage(), luaB_coresume(), luaB_corunning(), luaB_pcall(), luaB_rawequal(), luaB_xpcall(), luaB_yieldable(), luaL_execresult(), luaL_fileresult(), math_ult(), os_execute(), setboolfield(), and settabsb().
lua_pushcclosure()
LUA_API void lua_pushcclosure (lua_State * L, lua_CFunction fn, int n)
Definition at line 532 of file lapi.c.
Referenced by aux_lines(), createsearcherstable(), gmatch(), luaB_cowrap(), and luaL_setfuncs().
lua_pushfstring()
LUA_API const char * lua_pushfstring (lua_State * L, const char * fmt, ...)
Definition at line 519 of file lapi.c.
Referenced by checkoption(), db_getinfo(), errfile(), f_tostring(), loadfunc(), luaL_checkoption(), luaL_fileresult(), luaL_loadfilex(), luaL_tolstring(), luaL_traceback(), luaL_where(), pushfuncname(), pushutfchar(), searcher_Croot(), searcher_preload(), searchpath(), setpath(), and typeerror().
lua_pushinteger()
LUA_API void lua_pushinteger (lua_State * L, lua_Integer n)
Definition at line 466 of file lapi.c.
Referenced by aux_lines(), byteoffset(), codepoint(), db_gethook(), f_seek(), hookf(), ipairsaux(), iter_aux(), iter_codes(), luaB_collectgarbage(), luaB_ipairs(), luaB_rawlen(), luaB_select(), luaB_tonumber(), luaL_execresult(), luaL_fileresult(), luaL_unref(), luaopen_math(), main(), math_abs(), math_fmod(), math_random(), math_toint(), pack(), pairsmeta(), push_onecapture(), pushnumint(), setfield(), settabsi(), str_byte(), str_find_aux(), str_gsub(), str_len(), str_packsize(), str_unpack(), and utflen().
lua_pushlightuserdata()
LUA_API void lua_pushlightuserdata (lua_State * L, void * p)
Definition at line 565 of file lapi.c.
Referenced by addtoclib(), db_upvalueid(), and main().
lua_pushlstring()
LUA_API const char * lua_pushlstring (lua_State * L, const char * s, size_t len)
Definition at line 479 of file lapi.c.
Referenced by add_value(), loadfunc(), luaL_pushresult(), luaopen_utf8(), push_onecapture(), pushnexttemplate(), searcher_Croot(), str_sub(), and str_unpack().
lua_pushnil()
LUA_API void lua_pushnil (lua_State * L)
Definition at line 450 of file lapi.c.
Referenced by byteoffset(), db_gethook(), db_getinfo(), db_getlocal(), db_getmetatable(), db_getuservalue(), findfield(), g_read(), hookf(), io_lines(), io_noclose(), io_type(), ll_loadlib(), ll_searchpath(), load_aux(), luaB_getmetatable(), luaB_next(), luaB_tonumber(), luaL_execresult(), luaL_fileresult(), math_toint(), math_type(), pairsmeta(), read_number(), str_find_aux(), str_pack(), tremove(), and utflen().
lua_pushnumber()
LUA_API void lua_pushnumber (lua_State * L, lua_Number n)
Definition at line 458 of file lapi.c.
Referenced by luaB_collectgarbage(), luaopen_math(), math_abs(), math_acos(), math_asin(), math_atan(), math_cos(), math_deg(), math_exp(), math_fmod(), math_log(), math_modf(), math_rad(), math_random(), math_sin(), math_sqrt(), math_tan(), os_clock(), os_difftime(), pushnumint(), and str_unpack().
lua_pushstring()
LUA_API const char * lua_pushstring (lua_State * L, const char * s)
Definition at line 491 of file lapi.c.
Referenced by auxupvalue(), checkfield(), checkload(), db_gethook(), db_getlocal(), db_sethook(), db_setlocal(), findloader(), hookf(), ll_loadlib(), ll_require(), luaB_type(), luaL_execresult(), luaL_fileresult(), luaL_getmetafield(), luaL_newmetatable(), luaL_requiref(), luaL_tolstring(), os_getenv(), os_setlocale(), os_tmpname(), pushglobalfuncname(), searcher_Croot(), setpath(), and settabss().
lua_pushthread()
LUA_API int lua_pushthread (lua_State * L)
Definition at line 573 of file lapi.c.
Referenced by db_gethook(), db_sethook(), hookf(), and luaB_corunning().
lua_pushvalue()
LUA_API void lua_pushvalue (lua_State * L, int idx)
Definition at line 237 of file lapi.c.
Referenced by add_value(), addtoclib(), auxsort(), createmeta(), createmetatable(), createsearcherstable(), createstdfile(), db_getinfo(), db_getlocal(), db_getregistry(), db_sethook(), db_traceback(), finishpcall(), g_iofile(), generic_reader(), io_readline(), iter_codes(), lf_write(), ll_require(), load_aux(), luaB_cocreate(), luaB_error(), luaB_ipairs(), luaB_print(), luaB_xpcall(), luaL_callmeta(), luaL_getsubtable(), luaL_newmetatable(), luaL_requiref(), luaL_setfuncs(), luaL_tolstring(), luaopen_base(), luaopen_package(), math_max(), math_min(), pairsmeta(), sort_comp(), and tmove().
lua_pushvfstring()
LUA_API const char * lua_pushvfstring (lua_State * L, const char * fmt, va_list argp)
Definition at line 508 of file lapi.c.
Referenced by luaL_error().
lua_rawequal()
LUA_API int lua_rawequal (lua_State * L, int index1, int index2)
Definition at line 295 of file lapi.c.
Referenced by findfield(), luaB_rawequal(), and luaL_testudata().
lua_rawget()
LUA_API int lua_rawget (lua_State * L, int idx)
Definition at line 647 of file lapi.c.
Referenced by checkfield(), db_gethook(), hookf(), luaB_rawget(), and luaL_getmetafield().
lua_rawgeti()
LUA_API int lua_rawgeti (lua_State * L, int idx, lua_Integer n)
Definition at line 658 of file lapi.c.
Referenced by findloader(), gctm(), ll_require(), luaL_ref(), and luaL_unref().
lua_rawgetp()
LUA_API int lua_rawgetp (lua_State * L, int idx, const void * p)
Definition at line 670 of file lapi.c.
Referenced by addtoclib(), checkclib(), db_gethook(), db_sethook(), and hookf().
lua_rawlen()
LUA_API size_t lua_rawlen (lua_State * L, int idx)
Definition at line 392 of file lapi.c.
Referenced by luaB_rawlen(), luaL_ref(), and read_line().
lua_rawset()
LUA_API void lua_rawset (lua_State * L, int idx)
Definition at line 801 of file lapi.c.
Referenced by db_sethook(), and luaB_rawset().
lua_rawseti()
LUA_API void lua_rawseti (lua_State * L, int idx, lua_Integer n)
Definition at line 817 of file lapi.c.
Referenced by addtoclib(), createsearcherstable(), luaL_ref(), and luaL_unref().
lua_rawsetp()
LUA_API void lua_rawsetp (lua_State * L, int idx, const void * p)
Definition at line 830 of file lapi.c.
Referenced by createclibstable(), and db_sethook().
lua_rotate()
LUA_API void lua_rotate (lua_State * L, int idx, int n)
Definition at line 207 of file lapi.c.
Referenced by aux_lines(), db_getlocal(), luaB_xpcall(), and treatstackoption().
lua_setallocf()
LUA_API void lua_setallocf (lua_State * L, lua_Alloc f, void * ud)
Definition at line 1176 of file lapi.c.
lua_setfield()
LUA_API void lua_setfield (lua_State * L, int idx, const char * k)
Definition at line 777 of file lapi.c.
Referenced by addtoclib(), createclibstable(), createmeta(), createmetatable(), createsearcherstable(), createstdfile(), db_sethook(), g_iofile(), ll_require(), luaL_getsubtable(), luaL_newmetatable(), luaL_requiref(), luaL_setfuncs(), luaopen_base(), luaopen_math(), luaopen_package(), luaopen_utf8(), newbox(), pack(), setboolfield(), setfield(), setpath(), settabsb(), settabsi(), settabss(), and treatstackoption().
lua_setglobal()
LUA_API void lua_setglobal (lua_State * L, const char * name)
Definition at line 759 of file lapi.c.
Referenced by luaL_requiref(), and luaopen_table().
lua_seti()
LUA_API void lua_seti (lua_State * L, int idx, lua_Integer n)
Definition at line 783 of file lapi.c.
Referenced by pack(), set2(), tinsert(), tmove(), and tremove().
lua_setmetatable()
LUA_API int lua_setmetatable (lua_State * L, int objindex)
Definition at line 846 of file lapi.c.
Referenced by createclibstable(), createmetatable(), db_sethook(), db_setmetatable(), luaB_setmetatable(), luaL_setmetatable(), and newbox().
lua_settable()
LUA_API void lua_settable (lua_State * L, int idx)
Definition at line 766 of file lapi.c.
lua_settop()
LUA_API void lua_settop (lua_State * L, int idx)
Definition at line 172 of file lapi.c.
Referenced by db_debug(), db_sethook(), db_setlocal(), db_setmetatable(), db_setuservalue(), gmatch(), io_readline(), ll_require(), luaB_assert(), luaB_dofile(), luaB_error(), luaB_load(), luaB_next(), luaB_rawget(), luaB_rawset(), luaB_setmetatable(), luaB_tonumber(), luaL_loadfilex(), math_ceil(), math_floor(), math_modf(), os_time(), pushglobalfuncname(), sort(), and str_dump().
lua_setupvalue()
LUA_API const char * lua_setupvalue (lua_State * L, int funcindex, int n)
Definition at line 1238 of file lapi.c.
Referenced by auxupvalue(), ll_require(), and load_aux().
lua_setuservalue()
LUA_API void lua_setuservalue (lua_State * L, int idx)
Definition at line 886 of file lapi.c.
Referenced by db_setuservalue().
lua_status()
LUA_API int lua_status (lua_State * L)
Definition at line 1031 of file lapi.c.
Referenced by auxresume(), and luaB_costatus().
lua_stringtonumber()
LUA_API size_t lua_stringtonumber (lua_State * L, const char * s)
Definition at line 337 of file lapi.c.
Referenced by luaB_tonumber(), and read_number().
lua_toboolean()
LUA_API int lua_toboolean (lua_State * L, int idx)
Definition at line 367 of file lapi.c.
Referenced by add_value(), getboolfield(), io_readline(), ll_require(), luaB_assert(), luaL_requiref(), luaL_tolstring(), noenv(), os_exit(), sort_comp(), str_dump(), and str_find_aux().
lua_tocfunction()
LUA_API lua_CFunction lua_tocfunction (lua_State * L, int idx)
Definition at line 404 of file lapi.c.
lua_tointegerx()
LUA_API lua_Integer lua_tointegerx (lua_State * L, int idx, int * pisnum)
Definition at line 356 of file lapi.c.
Referenced by getfield(), luaL_checkinteger(), luaL_len(), and math_toint().
lua_tolstring()
LUA_API const char * lua_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 373 of file lapi.c.
Referenced by add_s(), addliteral(), generic_reader(), luaB_load(), luaB_print(), luaB_tonumber(), luaL_addvalue(), luaL_checklstring(), and luaL_tolstring().
lua_tonumberx()
LUA_API lua_Number lua_tonumberx (lua_State * L, int idx, int * pisnum)
Definition at line 345 of file lapi.c.
Referenced by luaL_checknumber().
lua_topointer()
LUA_API const void * lua_topointer (lua_State * L, int idx)
Definition at line 429 of file lapi.c.
Referenced by luaL_tolstring().
lua_tothread()
LUA_API lua_State * lua_tothread (lua_State * L, int idx)
Definition at line 423 of file lapi.c.
Referenced by getco(), getthread(), and luaB_auxwrap().
lua_touserdata()
LUA_API void * lua_touserdata (lua_State * L, int idx)
Definition at line 413 of file lapi.c.
Referenced by checkclib(), gctm(), getiofile(), gmatch_aux(), io_readline(), luaL_testudata(), pmain(), and resizebox().
lua_type()
LUA_API int lua_type (lua_State * L, int idx)
Definition at line 251 of file lapi.c.
Referenced by addliteral(), checktab(), db_getuservalue(), db_setmetatable(), findfield(), g_read(), g_write(), luaB_auxwrap(), luaB_error(), luaB_rawlen(), luaB_select(), luaB_setmetatable(), luaB_tonumber(), luaB_type(), luaL_checkany(), luaL_checktype(), luaL_tolstring(), math_type(), str_gsub(), and typeerror().
lua_typename()
LUA_API const char * lua_typename (lua_State * L, int t)
Definition at line 257 of file lapi.c.
Referenced by luaB_type(), and tag_error().
lua_upvalueid()
LUA_API void * lua_upvalueid (lua_State * L, int fidx, int n)
Definition at line 1270 of file lapi.c.
Referenced by db_upvalueid().
lua_upvaluejoin()
LUA_API void lua_upvaluejoin (lua_State * L, int fidx1, int n1, int fidx2, int n2)
Definition at line 1289 of file lapi.c.
Referenced by db_upvaluejoin().
lua_version()
LUA_API const lua_Number * lua_version (lua_State * L)
Definition at line 144 of file lapi.c.
Referenced by f_luaopen(), and luaL_checkversion_().
lua_xmove()
LUA_API void lua_xmove (lua_State * from, lua_State * to, int n)
Definition at line 118 of file lapi.c.
Referenced by auxresume(), db_gethook(), db_getinfo(), db_getlocal(), db_sethook(), db_setlocal(), luaB_cocreate(), and treatstackoption().
reverse()
static void reverse (lua_State * L, StkId from, StkId to) static
Definition at line 193 of file lapi.c.
Referenced by lua_rotate(), AP_SteerController::set_reverse(), and AP_L1_Control::set_reverse().
Variable Documentation
lua_ident
const char lua_ident[]
Initial value:
=
  "$LuaVersion: " LUA_COPYRIGHT " $"
  "$LuaAuthors: " LUA_AUTHORS " $"
Definition at line 34 of file lapi.c.