APM:Libraries: libraries/AP_Scripting/lua/src/lauxlib.h File Reference
lauxlib.h File Reference
#include <stddef.h>
#include <stdio.h>
#include "lua.h"
Classes
struct luaL_Reg
struct luaL_Buffer
struct luaL_Stream
Macros
#define LUA_ERRFILE (LUA_ERRERR+1)
#define LUA_LOADED_TABLE "_LOADED"
#define LUA_PRELOAD_TABLE "_PRELOAD"
#define LUAL_NUMSIZES (sizeof(lua_Integer)*16 + sizeof(lua_Number))
#define luaL_checkversion(L) luaL_checkversion_(L, LUA_VERSION_NUM, LUAL_NUMSIZES)
#define LUA_NOREF (-2)
#define LUA_REFNIL (-1)
#define luaL_loadfile(L, f) luaL_loadfilex(L,f,NULL)
#define luaL_newlibtable(L, l) lua_createtable(L, 0, sizeof(l)/sizeof((l)[0]) - 1)
#define luaL_newlib(L, l) (luaL_checkversion(L), luaL_newlibtable(L,l), luaL_setfuncs(L,l,0))
#define luaL_argcheck(L, cond, arg, extramsg) ((void)((cond) || luaL_argerror(L, (arg), (extramsg))))
#define luaL_checkstring(L, n) (luaL_checklstring(L, (n), NULL))
#define luaL_optstring(L, n, d) (luaL_optlstring(L, (n), (d), NULL))
#define luaL_typename(L, i) lua_typename(L, lua_type(L,(i)))
#define luaL_dofile(L, fn) (luaL_loadfile(L, fn) || lua_pcall(L, 0, LUA_MULTRET, 0))
#define luaL_dostring(L, s) (luaL_loadstring(L, s) || lua_pcall(L, 0, LUA_MULTRET, 0))
#define luaL_getmetatable(L, n) (lua_getfield(L, LUA_REGISTRYINDEX, (n)))
#define luaL_opt(L, f, n, d) (lua_isnoneornil(L,(n)) ? (d) : f(L,(n)))
#define luaL_loadbuffer(L, s, sz, n) luaL_loadbufferx(L,s,sz,n,NULL)
#define luaL_addchar(B, c)
#define luaL_addsize(B, s) ((B)->n += (s))
#define luaL_prepbuffer(B) luaL_prepbuffsize(B, LUAL_BUFFERSIZE)
#define LUA_FILEHANDLE "FILE*"
#define lua_writestring(s, l) fwrite((s), sizeof(char), (l), stdout)
#define lua_writeline() (lua_writestring("\n", 1), fflush(stdout))
#define lua_writestringerror(s, p) (fprintf(stderr, (s), (p)), fflush(stderr))
Typedefs
typedef struct luaL_Reg luaL_Reg
typedef struct luaL_Buffer luaL_Buffer
typedef struct luaL_Stream luaL_Stream
Functions
uint32_t lua_random32 (void)
LUALIB_API void luaL_checkversion_ (lua_State *L, lua_Number ver, size_t sz)
LUALIB_API int luaL_getmetafield (lua_State *L, int obj, const char *e)
LUALIB_API int luaL_callmeta (lua_State *L, int obj, const char *e)
LUALIB_API const char * luaL_tolstring (lua_State *L, int idx, size_t *len)
LUALIB_API int luaL_argerror (lua_State *L, int arg, const char *extramsg)
LUALIB_API const char * luaL_checklstring (lua_State *L, int arg, size_t *l)
LUALIB_API const char * luaL_optlstring (lua_State *L, int arg, const char *def, size_t *l)
LUALIB_API lua_Number luaL_checknumber (lua_State *L, int arg)
LUALIB_API lua_Number luaL_optnumber (lua_State *L, int arg, lua_Number def)
LUALIB_API lua_Integer luaL_checkinteger (lua_State *L, int arg)
LUALIB_API lua_Integer luaL_optinteger (lua_State *L, int arg, lua_Integer def)
LUALIB_API void luaL_checkstack (lua_State *L, int sz, const char *msg)
LUALIB_API void luaL_checktype (lua_State *L, int arg, int t)
LUALIB_API void luaL_checkany (lua_State *L, int arg)
LUALIB_API int luaL_newmetatable (lua_State *L, const char *tname)
LUALIB_API void luaL_setmetatable (lua_State *L, const char *tname)
LUALIB_API void * luaL_testudata (lua_State *L, int ud, const char *tname)
LUALIB_API void * luaL_checkudata (lua_State *L, int ud, const char *tname)
LUALIB_API void luaL_where (lua_State *L, int lvl)
LUALIB_API int luaL_error (lua_State *L, const char *fmt,...)
LUALIB_API int luaL_checkoption (lua_State *L, int arg, const char *def, const char *const lst[])
LUALIB_API int luaL_fileresult (lua_State *L, int stat, const char *fname)
LUALIB_API int luaL_execresult (lua_State *L, int stat)
LUALIB_API int luaL_ref (lua_State *L, int t)
LUALIB_API void luaL_unref (lua_State *L, int t, int ref)
LUALIB_API int luaL_loadfilex (lua_State *L, const char *filename, const char *mode)
LUALIB_API int luaL_loadbufferx (lua_State *L, const char *buff, size_t sz, const char *name, const char *mode)
LUALIB_API int luaL_loadstring (lua_State *L, const char *s)
LUALIB_API lua_State * luaL_newstate (void)
LUALIB_API lua_Integer luaL_len (lua_State *L, int idx)
LUALIB_API const char * luaL_gsub (lua_State *L, const char *s, const char *p, const char *r)
LUALIB_API void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup)
LUALIB_API int luaL_getsubtable (lua_State *L, int idx, const char *fname)
LUALIB_API void luaL_traceback (lua_State *L, lua_State *L1, const char *msg, int level)
LUALIB_API void luaL_requiref (lua_State *L, const char *modname, lua_CFunction openf, int glb)
LUALIB_API void luaL_buffinit (lua_State *L, luaL_Buffer *B)
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addlstring (luaL_Buffer *B, const char *s, size_t l)
LUALIB_API void luaL_addstring (luaL_Buffer *B, const char *s)
LUALIB_API void luaL_addvalue (luaL_Buffer *B)
LUALIB_API void luaL_pushresult (luaL_Buffer *B)
LUALIB_API void luaL_pushresultsize (luaL_Buffer *B, size_t sz)
LUALIB_API char * luaL_buffinitsize (lua_State *L, luaL_Buffer *B, size_t sz)
Macro Definition Documentation
LUA_ERRFILE
#define LUA_ERRFILE (LUA_ERRERR+1)
Definition at line 20 of file lauxlib.h.
Referenced by errfile().
LUA_FILEHANDLE
#define LUA_FILEHANDLE "FILE*"
Definition at line 192 of file lauxlib.h.
Referenced by createmeta(), io_type(), and newprefile().
LUA_LOADED_TABLE
#define LUA_LOADED_TABLE "_LOADED"
Definition at line 24 of file lauxlib.h.
Referenced by ll_require(), luaL_requiref(), luaopen_package(), and pushglobalfuncname().
LUA_NOREF
#define LUA_NOREF (-2)
Definition at line 79 of file lauxlib.h.
LUA_PRELOAD_TABLE
#define LUA_PRELOAD_TABLE "_PRELOAD"
Definition at line 28 of file lauxlib.h.
Referenced by luaopen_package(), and searcher_preload().
LUA_REFNIL
#define LUA_REFNIL (-1)
Definition at line 80 of file lauxlib.h.
Referenced by luaL_ref().
lua_writeline
#define lua_writeline () (lua_writestring("\n", 1), fflush(stdout))
Definition at line 230 of file lauxlib.h.
Referenced by luaB_print().
lua_writestring
#define lua_writestring (s, l) fwrite((s), sizeof(char), (l), stdout)
Definition at line 225 of file lauxlib.h.
Referenced by luaB_print().
lua_writestringerror
#define lua_writestringerror (s, p) (fprintf(stderr, (s), (p)), fflush(stderr))
Definition at line 235 of file lauxlib.h.
Referenced by db_debug().
luaL_addchar
#define luaL_addchar (B, c)
Value:
  ((void)((B)->n < (B)->size || luaL_prepbuffsize((B), 1)), \
   ((B)->b[(B)->n++] = (c)))
Definition at line 159 of file lauxlib.h.
Referenced by add_s(), addquoted(), os_date(), read_line(), str_format(), str_gsub(), and str_pack().
luaL_addsize
#define luaL_addsize (B, s) ((B)->n += (s))
Definition at line 163 of file lauxlib.h.
Referenced by addliteral(), luaL_addlstring(), luaL_pushresultsize(), os_date(), packint(), read_all(), read_chars(), read_line(), str_format(), and str_pack().
luaL_argcheck
#define luaL_argcheck (L, cond, arg, extramsg) ((void)((cond) || luaL_argerror(L, (arg), (extramsg))))
Definition at line 124 of file lauxlib.h.
Referenced by aux_lines(), byteoffset(), checkupval(), codepoint(), db_setmetatable(), db_upvaluejoin(), f_seek(), getco(), io_open(), l_checktime(), luaB_rawlen(), luaB_select(), luaB_setmetatable(), luaB_tonumber(), luaB_type(), math_fmod(), math_max(), math_min(), math_random(), pushutfchar(), sort(), str_char(), str_format(), str_gsub(), str_pack(), str_packsize(), str_unpack(), tinsert(), tmove(), tremove(), and utflen().
luaL_checkstring
#define luaL_checkstring (L, n) (luaL_checklstring(L, (n), NULL))
Definition at line 126 of file lauxlib.h.
Referenced by db_sethook(), g_read(), io_lines(), io_open(), io_popen(), iter_codes(), ll_loadlib(), ll_require(), ll_searchpath(), luaL_checkoption(), os_getenv(), os_remove(), os_rename(), searcher_C(), searcher_Croot(), searcher_Lua(), searcher_preload(), str_pack(), str_packsize(), and str_unpack().
luaL_checkversion
#define luaL_checkversion (L) luaL_checkversion_(L, LUA_VERSION_NUM, LUAL_NUMSIZES)
Definition at line 42 of file lauxlib.h.
luaL_dofile
#define luaL_dofile (L, fn) (luaL_loadfile(L, fn) || lua_pcall(L, 0, LUA_MULTRET, 0))
Definition at line 131 of file lauxlib.h.
luaL_dostring
#define luaL_dostring (L, s) (luaL_loadstring(L, s) || lua_pcall(L, 0, LUA_MULTRET, 0))
Definition at line 134 of file lauxlib.h.
luaL_getmetatable
#define luaL_getmetatable (L, n) (lua_getfield(L, LUA_REGISTRYINDEX, (n)))
Definition at line 137 of file lauxlib.h.
Referenced by luaL_newmetatable(), luaL_setmetatable(), and luaL_testudata().
luaL_loadbuffer
#define luaL_loadbuffer (L, s, sz, n) luaL_loadbufferx(L,s,sz,n,NULL)
Definition at line 141 of file lauxlib.h.
Referenced by db_debug(), and luaL_loadstring().
luaL_loadfile
#define luaL_loadfile (L, f) luaL_loadfilex(L,f,NULL)
Definition at line 88 of file lauxlib.h.
Referenced by luaB_dofile(), pmain(), and searcher_Lua().
luaL_newlib
#define luaL_newlib (L, l) (luaL_checkversion(L), luaL_newlibtable(L,l), luaL_setfuncs(L,l,0))
Definition at line 121 of file lauxlib.h.
Referenced by luaopen_coroutine(), luaopen_debug(), luaopen_io(), luaopen_math(), luaopen_os(), luaopen_package(), luaopen_string(), luaopen_table(), and luaopen_utf8().
luaL_newlibtable
#define luaL_newlibtable (L, l) lua_createtable(L, 0, sizeof(l)/sizeof((l)[0]) - 1)
Definition at line 118 of file lauxlib.h.
LUAL_NUMSIZES
#define LUAL_NUMSIZES (sizeof(lua_Integer)*16 + sizeof(lua_Number))
Definition at line 37 of file lauxlib.h.
Referenced by luaL_checkversion_().
luaL_opt
#define luaL_opt (L, f, n, d) (lua_isnoneornil(L,(n)) ? (d) : f(L,(n)))
Definition at line 139 of file lauxlib.h.
Referenced by luaL_optinteger(), luaL_optnumber(), os_date(), and unpack().
luaL_optstring
#define luaL_optstring (L, n, d) (luaL_optlstring(L, (n), (d), NULL))
Definition at line 127 of file lauxlib.h.
Referenced by db_getinfo(), io_open(), io_popen(), ll_searchpath(), luaB_dofile(), luaB_load(), luaB_loadfile(), luaL_checkoption(), os_execute(), and os_setlocale().
luaL_prepbuffer
#define luaL_prepbuffer (B) luaL_prepbuffsize(B, LUAL_BUFFERSIZE)
Definition at line 174 of file lauxlib.h.
Referenced by read_all(), and read_line().
luaL_typename
#define luaL_typename (L, i) lua_typename(L, lua_type(L,(i)))
Definition at line 129 of file lauxlib.h.
Referenced by add_value(), addfield(), luaL_tolstring(), and typeerror().
Typedef Documentation
luaL_Buffer
typedef struct luaL_Buffer luaL_Buffer
luaL_Reg
typedef struct luaL_Reg luaL_Reg
luaL_Stream
typedef struct luaL_Stream luaL_Stream
Function Documentation
lua_random32()
uint32_t lua_random32 (void)
Definition at line 1053 of file lauxlib.c.
Referenced by l_randomizePivot().
luaL_addlstring()
LUALIB_API void luaL_addlstring (luaL_Buffer * B, const char * s, size_t l)
Definition at line 531 of file lauxlib.c.
Referenced by add_s(), luaL_addstring(), luaL_addvalue(), luaL_gsub(), str_gsub(), str_pack(), tconcat(), and writer().
luaL_addstring()
LUALIB_API void luaL_addstring (luaL_Buffer * B, const char * s)
Definition at line 540 of file lauxlib.c.
Referenced by addquoted(), and luaL_gsub().
luaL_addvalue()
LUALIB_API void luaL_addvalue (luaL_Buffer * B)
Definition at line 561 of file lauxlib.c.
Referenced by add_s(), add_value(), addfield(), addliteral(), findloader(), searchpath(), str_format(), and utfchar().
luaL_argerror()
LUALIB_API int luaL_argerror (lua_State * L, int arg, const char * extramsg)
Definition at line 167 of file lauxlib.c.
Referenced by addliteral(), checkoption(), db_getinfo(), db_getlocal(), db_setlocal(), g_read(), getdetails(), interror(), luaL_checkany(), luaL_checkoption(), str_format(), str_packsize(), str_unpack(), and typeerror().
luaL_buffinit()
LUALIB_API void luaL_buffinit (lua_State * L, luaL_Buffer * B)
Definition at line 572 of file lauxlib.c.
Referenced by findloader(), luaL_buffinitsize(), luaL_gsub(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), str_pack(), tconcat(), and utfchar().
luaL_buffinitsize()
LUALIB_API char * luaL_buffinitsize (lua_State * L, luaL_Buffer * B, size_t sz)
Definition at line 580 of file lauxlib.c.
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
luaL_callmeta()
LUALIB_API int luaL_callmeta (lua_State * L, int obj, const char * e)
Definition at line 793 of file lauxlib.c.
Referenced by luaL_tolstring().
luaL_checkany()
LUALIB_API void luaL_checkany (lua_State * L, int arg)
Definition at line 387 of file lauxlib.c.
Referenced by db_getmetatable(), db_setlocal(), db_setupvalue(), db_setuservalue(), io_type(), luaB_assert(), luaB_getmetatable(), luaB_ipairs(), luaB_pcall(), luaB_rawequal(), luaB_rawget(), luaB_rawset(), luaB_tonumber(), luaB_tostring(), math_toint(), math_type(), and pairsmeta().
luaL_checkinteger()
LUALIB_API lua_Integer luaL_checkinteger (lua_State * L, int arg)
Definition at line 433 of file lauxlib.c.
Referenced by auxupvalue(), byteoffset(), checkupval(), db_getinfo(), db_getlocal(), db_setlocal(), g_read(), ipairsaux(), l_checktime(), luaB_select(), luaB_tonumber(), luaL_optinteger(), math_random(), math_ult(), pushutfchar(), str_char(), str_format(), str_pack(), str_rep(), str_sub(), tinsert(), tmove(), and unpack().
luaL_checklstring()
LUALIB_API const char * luaL_checklstring (lua_State * L, int arg, size_t * l)
Definition at line 393 of file lauxlib.c.
Referenced by byteoffset(), codepoint(), g_write(), gmatch(), iter_aux(), luaL_optlstring(), str_byte(), str_find_aux(), str_format(), str_gsub(), str_len(), str_lower(), str_pack(), str_rep(), str_reverse(), str_sub(), str_unpack(), str_upper(), and utflen().
luaL_checknumber()
LUALIB_API lua_Number luaL_checknumber (lua_State * L, int arg)
Definition at line 411 of file lauxlib.c.
Referenced by luaL_optnumber(), math_abs(), math_acos(), math_asin(), math_atan(), math_ceil(), math_cos(), math_deg(), math_exp(), math_floor(), math_fmod(), math_log(), math_modf(), math_rad(), math_randomseed(), math_sin(), math_sqrt(), math_tan(), str_format(), and str_pack().
luaL_checkoption()
LUALIB_API int luaL_checkoption (lua_State * L, int arg, const char * def, const char *const lst[])
Definition at line 351 of file lauxlib.c.
Referenced by f_seek(), luaB_collectgarbage(), and os_setlocale().
luaL_checkstack()
LUALIB_API void luaL_checkstack (lua_State * L, int sz, const char * msg)
Definition at line 371 of file lauxlib.c.
Referenced by codepoint(), g_read(), generic_reader(), io_readline(), luaL_setfuncs(), luaL_traceback(), push_captures(), str_byte(), and str_unpack().
luaL_checktype()
LUALIB_API void luaL_checktype (lua_State * L, int arg, int t)
Definition at line 381 of file lauxlib.c.
Referenced by auxupvalue(), checktab(), checkupval(), db_sethook(), db_setuservalue(), luaB_cocreate(), luaB_load(), luaB_next(), luaB_rawget(), luaB_rawset(), luaB_setmetatable(), luaB_tonumber(), luaB_xpcall(), os_time(), sort(), and str_dump().
luaL_checkudata()
LUALIB_API void * luaL_checkudata (lua_State * L, int ud, const char * tname)
Definition at line 336 of file lauxlib.c.
luaL_checkversion_()
LUALIB_API void luaL_checkversion_ (lua_State * L, lua_Number ver, size_t sz)
Definition at line 1038 of file lauxlib.c.
luaL_error()
LUALIB_API int luaL_error (lua_State * L, const char * fmt, ...)
Definition at line 226 of file lauxlib.c.
Referenced by add_s(), add_value(), addfield(), byteoffset(), capture_to_close(), check_capture(), checkload(), checkstack(), classend(), codepoint(), findfile(), findloader(), generic_reader(), getfield(), getiofile(), getnumlimit(), getoption(), io_readline(), iter_aux(), luaB_print(), luaB_setmetatable(), luaL_argerror(), luaL_checkstack(), luaL_checkversion_(), luaL_len(), luaL_prepbuffsize(), luaL_tolstring(), luaopen_bit32(), match(), matchbalance(), math_random(), opencheck(), os_date(), os_time(), os_tmpname(), partition(), push_onecapture(), resizebox(), scanformat(), start_capture(), str_byte(), str_dump(), str_format(), str_rep(), tinsert(), tofile(), unpack(), and unpackint().
luaL_execresult()
LUALIB_API int luaL_execresult (lua_State * L, int stat)
Definition at line 277 of file lauxlib.c.
Referenced by io_pclose(), and os_execute().
luaL_fileresult()
LUALIB_API int luaL_fileresult (lua_State * L, int stat, const char * fname)
Definition at line 237 of file lauxlib.c.
Referenced by f_flush(), f_seek(), g_read(), g_write(), io_fclose(), io_flush(), io_open(), io_popen(), io_tmpfile(), luaL_execresult(), os_remove(), and os_rename().
luaL_getmetafield()
LUALIB_API int luaL_getmetafield (lua_State * L, int obj, const char * e)
Definition at line 777 of file lauxlib.c.
Referenced by luaB_getmetatable(), luaB_setmetatable(), luaL_callmeta(), luaL_tolstring(), pairsmeta(), and typeerror().
luaL_getsubtable()
LUALIB_API int luaL_getsubtable (lua_State * L, int idx, const char * fname)
Definition at line 956 of file lauxlib.c.
Referenced by luaL_requiref(), and luaopen_package().
luaL_gsub()
LUALIB_API const char * luaL_gsub (lua_State * L, const char * s, const char * p, const char * r)
Definition at line 996 of file lauxlib.c.
Referenced by loadfunc(), searchpath(), and setpath().
luaL_len()
LUALIB_API lua_Integer luaL_len (lua_State * L, int idx)
Definition at line 803 of file lauxlib.c.
Referenced by addtoclib(), gctm(), and unpack().
luaL_loadbufferx()
LUALIB_API int luaL_loadbufferx (lua_State * L, const char * buff, size_t sz, const char * name, const char * mode)
Definition at line 760 of file lauxlib.c.
Referenced by luaB_load().
luaL_loadfilex()
LUALIB_API int luaL_loadfilex (lua_State * L, const char * filename, const char * mode)
Definition at line 706 of file lauxlib.c.
Referenced by luaB_loadfile().
luaL_loadstring()
LUALIB_API int luaL_loadstring (lua_State * L, const char * s)
Definition at line 769 of file lauxlib.c.
luaL_newmetatable()
LUALIB_API int luaL_newmetatable (lua_State * L, const char * tname)
Definition at line 302 of file lauxlib.c.
Referenced by createmeta(), and newbox().
luaL_newstate()
LUALIB_API lua_State * luaL_newstate (void)
Referenced by main().
luaL_optinteger()
LUALIB_API lua_Integer luaL_optinteger (lua_State * L, int arg, lua_Integer def)
Definition at line 443 of file lauxlib.c.
Referenced by byteoffset(), codepoint(), db_sethook(), db_traceback(), f_seek(), luaB_collectgarbage(), luaB_error(), os_exit(), str_byte(), str_find_aux(), str_gsub(), str_sub(), str_unpack(), tconcat(), tremove(), unpack(), and utflen().
luaL_optlstring()
LUALIB_API const char * luaL_optlstring (lua_State * L, int arg, const char * def, size_t * l)
Definition at line 400 of file lauxlib.c.
Referenced by os_date(), str_rep(), and tconcat().
luaL_optnumber()
LUALIB_API lua_Number luaL_optnumber (lua_State * L, int arg, lua_Number def)
Definition at line 420 of file lauxlib.c.
Referenced by math_atan().
luaL_prepbuffsize()
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer * B, size_t sz)
Definition at line 508 of file lauxlib.c.
Referenced by addliteral(), luaL_addlstring(), luaL_buffinitsize(), os_date(), packint(), read_chars(), str_format(), and str_pack().
luaL_pushresult()
LUALIB_API void luaL_pushresult (luaL_Buffer * B)
Definition at line 545 of file lauxlib.c.
Referenced by findloader(), luaL_gsub(), luaL_pushresultsize(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), str_pack(), tconcat(), and utfchar().
luaL_pushresultsize()
LUALIB_API void luaL_pushresultsize (luaL_Buffer * B, size_t sz)
Definition at line 555 of file lauxlib.c.
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
luaL_ref()
LUALIB_API int luaL_ref (lua_State * L, int t)
Definition at line 598 of file lauxlib.c.
luaL_requiref()
LUALIB_API void luaL_requiref (lua_State * L, const char * modname, lua_CFunction openf, int glb)
Definition at line 976 of file lauxlib.c.
Referenced by luaL_openlibs().
luaL_setfuncs()
LUALIB_API void luaL_setfuncs (lua_State * L, const luaL_Reg * l, int nup)
Definition at line 939 of file lauxlib.c.
Referenced by createmeta(), luaopen_base(), luaopen_base_sandbox(), and luaopen_package().
luaL_setmetatable()
LUALIB_API void luaL_setmetatable (lua_State * L, const char * tname)
Definition at line 315 of file lauxlib.c.
Referenced by newprefile().
luaL_testudata()
LUALIB_API void * luaL_testudata (lua_State * L, int ud, const char * tname)
Definition at line 321 of file lauxlib.c.
Referenced by io_type(), and luaL_checkudata().
luaL_tolstring()
LUALIB_API const char * luaL_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 815 of file lauxlib.c.
Referenced by add_s(), addliteral(), luaB_tostring(), and str_format().
luaL_traceback()
LUALIB_API void luaL_traceback (lua_State * L, lua_State * L1, const char * msg, int level)
Definition at line 128 of file lauxlib.c.
Referenced by db_traceback().
luaL_unref()
LUALIB_API void luaL_unref (lua_State * L, int t, int ref)
Definition at line 619 of file lauxlib.c.
luaL_where()
LUALIB_API void luaL_where (lua_State * L, int lvl)
Definition at line 208 of file lauxlib.c.
Referenced by luaB_auxwrap(), luaB_error(), and luaL_error().