APM:Libraries: libraries/AP_Scripting/lua/src/lauxlib.c File Reference
lauxlib.c File Reference
#include "lprefix.h"
#include <errno.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
Classes
struct UBox
struct LoadF
struct LoadS
Macros
#define lauxlib_c
#define LUA_LIB
#define LEVELS1 10 /* size of the first part of the stack */
#define LEVELS2 11 /* size of the second part of the stack */
#define l_inspectstat(stat, what) /* no op */
#define buffonstack(B) ((B)->b != (B)->initb)
#define freelist 0
Typedefs
typedef struct UBox UBox
typedef struct LoadF LoadF
typedef struct LoadS LoadS
Functions
static int findfield (lua_State *L, int objidx, int level)
static int pushglobalfuncname (lua_State *L, lua_Debug *ar)
static void pushfuncname (lua_State *L, lua_Debug *ar)
static int lastlevel (lua_State *L)
LUALIB_API void luaL_traceback (lua_State *L, lua_State *L1, const char *msg, int level)
LUALIB_API int luaL_argerror (lua_State *L, int arg, const char *extramsg)
static int typeerror (lua_State *L, int arg, const char *tname)
static void tag_error (lua_State *L, int arg, int tag)
LUALIB_API void luaL_where (lua_State *L, int level)
LUALIB_API int luaL_error (lua_State *L, const char *fmt,...)
LUALIB_API int luaL_fileresult (lua_State *L, int stat, const char *fname)
LUALIB_API int luaL_execresult (lua_State *L, int stat)
LUALIB_API int luaL_newmetatable (lua_State *L, const char *tname)
LUALIB_API void luaL_setmetatable (lua_State *L, const char *tname)
LUALIB_API void * luaL_testudata (lua_State *L, int ud, const char *tname)
LUALIB_API void * luaL_checkudata (lua_State *L, int ud, const char *tname)
LUALIB_API int luaL_checkoption (lua_State *L, int arg, const char *def, const char *const lst[])
LUALIB_API void luaL_checkstack (lua_State *L, int space, const char *msg)
LUALIB_API void luaL_checktype (lua_State *L, int arg, int t)
LUALIB_API void luaL_checkany (lua_State *L, int arg)
LUALIB_API const char * luaL_checklstring (lua_State *L, int arg, size_t *len)
LUALIB_API const char * luaL_optlstring (lua_State *L, int arg, const char *def, size_t *len)
LUALIB_API lua_Number luaL_checknumber (lua_State *L, int arg)
LUALIB_API lua_Number luaL_optnumber (lua_State *L, int arg, lua_Number def)
static void interror (lua_State *L, int arg)
LUALIB_API lua_Integer luaL_checkinteger (lua_State *L, int arg)
LUALIB_API lua_Integer luaL_optinteger (lua_State *L, int arg, lua_Integer def)
static void * resizebox (lua_State *L, int idx, size_t newsize)
static int boxgc (lua_State *L)
static void * newbox (lua_State *L, size_t newsize)
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addlstring (luaL_Buffer *B, const char *s, size_t l)
LUALIB_API void luaL_addstring (luaL_Buffer *B, const char *s)
LUALIB_API void luaL_pushresult (luaL_Buffer *B)
LUALIB_API void luaL_pushresultsize (luaL_Buffer *B, size_t sz)
LUALIB_API void luaL_addvalue (luaL_Buffer *B)
LUALIB_API void luaL_buffinit (lua_State *L, luaL_Buffer *B)
LUALIB_API char * luaL_buffinitsize (lua_State *L, luaL_Buffer *B, size_t sz)
LUALIB_API int luaL_ref (lua_State *L, int t)
LUALIB_API void luaL_unref (lua_State *L, int t, int ref)
static const char * getF (lua_State *L, void *ud, size_t *size)
static int errfile (lua_State *L, const char *what, int fnameindex)
static int skipBOM (LoadF *lf)
static int skipcomment (LoadF *lf, int *cp)
LUALIB_API int luaL_loadfilex (lua_State *L, const char *filename, const char *mode)
static const char * getS (lua_State *L, void *ud, size_t *size)
LUALIB_API int luaL_loadbufferx (lua_State *L, const char *buff, size_t size, const char *name, const char *mode)
LUALIB_API int luaL_loadstring (lua_State *L, const char *s)
LUALIB_API int luaL_getmetafield (lua_State *L, int obj, const char *event)
LUALIB_API int luaL_callmeta (lua_State *L, int obj, const char *event)
LUALIB_API lua_Integer luaL_len (lua_State *L, int idx)
LUALIB_API const char * luaL_tolstring (lua_State *L, int idx, size_t *len)
LUALIB_API void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup)
LUALIB_API int luaL_getsubtable (lua_State *L, int idx, const char *fname)
LUALIB_API void luaL_requiref (lua_State *L, const char *modname, lua_CFunction openf, int glb)
LUALIB_API const char * luaL_gsub (lua_State *L, const char *s, const char *p, const char *r)
LUALIB_API void luaL_checkversion_ (lua_State *L, lua_Number ver, size_t sz)
uint32_t lua_random32 (void)
Macro Definition Documentation
buffonstack
#define buffonstack (B) ((B)->b != (B)->initb)
Definition at line 502 of file lauxlib.c.
Referenced by luaL_addvalue(), luaL_prepbuffsize(), and luaL_pushresult().
freelist
#define freelist 0
Definition at line 595 of file lauxlib.c.
Referenced by luaL_ref(), and luaL_unref().
l_inspectstat
#define l_inspectstat (stat, what) /* no op */
Definition at line 270 of file lauxlib.c.
Referenced by luaL_execresult().
lauxlib_c
#define lauxlib_c
Definition at line 7 of file lauxlib.c.
LEVELS1
#define LEVELS1 10 /* size of the first part of the stack */
Definition at line 40 of file lauxlib.c.
Referenced by luaL_traceback().
LEVELS2
#define LEVELS2 11 /* size of the second part of the stack */
Definition at line 41 of file lauxlib.c.
Referenced by luaL_traceback().
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lauxlib.c.
Typedef Documentation
LoadF
typedef struct LoadF LoadF
LoadS
typedef struct LoadS LoadS
UBox
typedef struct UBox UBox
Function Documentation
boxgc()
static int boxgc (lua_State * L) static
Definition at line 479 of file lauxlib.c.
Referenced by newbox().
errfile()
static int errfile (lua_State * L, const char * what, int fnameindex) static
Definition at line 663 of file lauxlib.c.
Referenced by luaL_loadfilex().
findfield()
static int findfield (lua_State * L, int objidx, int level) static
Definition at line 49 of file lauxlib.c.
Referenced by findfield(), and pushglobalfuncname().
getF()
static const char * getF (lua_State * L, void * ud, size_t * size) static
Definition at line 645 of file lauxlib.c.
Referenced by luaL_loadfilex().
getS()
static const char * getS (lua_State * L, void * ud, size_t * size) static
Definition at line 750 of file lauxlib.c.
Referenced by luaL_loadbufferx().
interror()
static void interror (lua_State * L, int arg) static
Definition at line 425 of file lauxlib.c.
Referenced by luaL_checkinteger().
lastlevel()
static int lastlevel (lua_State * L) static
Definition at line 113 of file lauxlib.c.
Referenced by luaL_traceback().
lua_random32()
uint32_t lua_random32 (void)
Definition at line 1053 of file lauxlib.c.
Referenced by l_randomizePivot().
luaL_addlstring()
LUALIB_API void luaL_addlstring (luaL_Buffer * B, const char * s, size_t l)
Definition at line 531 of file lauxlib.c.
Referenced by add_s(), luaL_addstring(), luaL_addvalue(), luaL_gsub(), str_gsub(), str_pack(), tconcat(), and writer().
luaL_addstring()
LUALIB_API void luaL_addstring (luaL_Buffer * B, const char * s)
Definition at line 540 of file lauxlib.c.
Referenced by addquoted(), and luaL_gsub().
luaL_addvalue()
LUALIB_API void luaL_addvalue (luaL_Buffer * B)
Definition at line 561 of file lauxlib.c.
Referenced by add_s(), add_value(), addfield(), addliteral(), findloader(), searchpath(), str_format(), and utfchar().
luaL_argerror()
LUALIB_API int luaL_argerror (lua_State * L, int arg, const char * extramsg)
Definition at line 167 of file lauxlib.c.
Referenced by addliteral(), checkoption(), db_getinfo(), db_getlocal(), db_setlocal(), g_read(), getdetails(), interror(), luaL_checkany(), luaL_checkoption(), str_format(), str_packsize(), str_unpack(), and typeerror().
luaL_buffinit()
LUALIB_API void luaL_buffinit (lua_State * L, luaL_Buffer * B)
Definition at line 572 of file lauxlib.c.
Referenced by findloader(), luaL_buffinitsize(), luaL_gsub(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), str_pack(), tconcat(), and utfchar().
luaL_buffinitsize()
LUALIB_API char * luaL_buffinitsize (lua_State * L, luaL_Buffer * B, size_t sz)
Definition at line 580 of file lauxlib.c.
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
luaL_callmeta()
LUALIB_API int luaL_callmeta (lua_State * L, int obj, const char * event)
Definition at line 793 of file lauxlib.c.
Referenced by luaL_tolstring().
luaL_checkany()
LUALIB_API void luaL_checkany (lua_State * L, int arg)
Definition at line 387 of file lauxlib.c.
Referenced by db_getmetatable(), db_setlocal(), db_setupvalue(), db_setuservalue(), io_type(), luaB_assert(), luaB_getmetatable(), luaB_ipairs(), luaB_pcall(), luaB_rawequal(), luaB_rawget(), luaB_rawset(), luaB_tonumber(), luaB_tostring(), math_toint(), math_type(), and pairsmeta().
luaL_checkinteger()
LUALIB_API lua_Integer luaL_checkinteger (lua_State * L, int arg)
Definition at line 433 of file lauxlib.c.
Referenced by auxupvalue(), byteoffset(), checkupval(), db_getinfo(), db_getlocal(), db_setlocal(), g_read(), ipairsaux(), l_checktime(), luaB_select(), luaB_tonumber(), luaL_optinteger(), math_random(), math_ult(), pushutfchar(), str_char(), str_format(), str_pack(), str_rep(), str_sub(), tinsert(), tmove(), and unpack().
luaL_checklstring()
LUALIB_API const char * luaL_checklstring (lua_State * L, int arg, size_t * len)
Definition at line 393 of file lauxlib.c.
Referenced by byteoffset(), codepoint(), g_write(), gmatch(), iter_aux(), luaL_optlstring(), str_byte(), str_find_aux(), str_format(), str_gsub(), str_len(), str_lower(), str_pack(), str_rep(), str_reverse(), str_sub(), str_unpack(), str_upper(), and utflen().
luaL_checknumber()
LUALIB_API lua_Number luaL_checknumber (lua_State * L, int arg)
Definition at line 411 of file lauxlib.c.
Referenced by luaL_optnumber(), math_abs(), math_acos(), math_asin(), math_atan(), math_ceil(), math_cos(), math_deg(), math_exp(), math_floor(), math_fmod(), math_log(), math_modf(), math_rad(), math_randomseed(), math_sin(), math_sqrt(), math_tan(), str_format(), and str_pack().
luaL_checkoption()
LUALIB_API int luaL_checkoption (lua_State * L, int arg, const char * def, const char *const lst[])
Definition at line 351 of file lauxlib.c.
Referenced by f_seek(), luaB_collectgarbage(), and os_setlocale().
luaL_checkstack()
LUALIB_API void luaL_checkstack (lua_State * L, int space, const char * msg)
Definition at line 371 of file lauxlib.c.
Referenced by codepoint(), g_read(), generic_reader(), io_readline(), luaL_setfuncs(), luaL_traceback(), push_captures(), str_byte(), and str_unpack().
luaL_checktype()
LUALIB_API void luaL_checktype (lua_State * L, int arg, int t)
Definition at line 381 of file lauxlib.c.
Referenced by auxupvalue(), checktab(), checkupval(), db_sethook(), db_setuservalue(), luaB_cocreate(), luaB_load(), luaB_next(), luaB_rawget(), luaB_rawset(), luaB_setmetatable(), luaB_tonumber(), luaB_xpcall(), os_time(), sort(), and str_dump().
luaL_checkudata()
LUALIB_API void * luaL_checkudata (lua_State * L, int ud, const char * tname)
Definition at line 336 of file lauxlib.c.
luaL_checkversion_()
LUALIB_API void luaL_checkversion_ (lua_State * L, lua_Number ver, size_t sz)
Definition at line 1038 of file lauxlib.c.
luaL_error()
LUALIB_API int luaL_error (lua_State * L, const char * fmt, ...)
Definition at line 226 of file lauxlib.c.
Referenced by add_s(), add_value(), addfield(), byteoffset(), capture_to_close(), check_capture(), checkload(), checkstack(), classend(), codepoint(), findfile(), findloader(), generic_reader(), getfield(), getiofile(), getnumlimit(), getoption(), io_readline(), iter_aux(), luaB_print(), luaB_setmetatable(), luaL_argerror(), luaL_checkstack(), luaL_checkversion_(), luaL_len(), luaL_prepbuffsize(), luaL_tolstring(), luaopen_bit32(), match(), matchbalance(), math_random(), opencheck(), os_date(), os_time(), os_tmpname(), partition(), push_onecapture(), resizebox(), scanformat(), start_capture(), str_byte(), str_dump(), str_format(), str_rep(), tinsert(), tofile(), unpack(), and unpackint().
luaL_execresult()
LUALIB_API int luaL_execresult (lua_State * L, int stat)
Definition at line 277 of file lauxlib.c.
Referenced by io_pclose(), and os_execute().
luaL_fileresult()
LUALIB_API int luaL_fileresult (lua_State * L, int stat, const char * fname)
Definition at line 237 of file lauxlib.c.
Referenced by f_flush(), f_seek(), g_read(), g_write(), io_fclose(), io_flush(), io_open(), io_popen(), io_tmpfile(), luaL_execresult(), os_remove(), and os_rename().
luaL_getmetafield()
LUALIB_API int luaL_getmetafield (lua_State * L, int obj, const char * event)
Definition at line 777 of file lauxlib.c.
Referenced by luaB_getmetatable(), luaB_setmetatable(), luaL_callmeta(), luaL_tolstring(), pairsmeta(), and typeerror().
luaL_getsubtable()
LUALIB_API int luaL_getsubtable (lua_State * L, int idx, const char * fname)
Definition at line 956 of file lauxlib.c.
Referenced by luaL_requiref(), and luaopen_package().
luaL_gsub()
LUALIB_API const char * luaL_gsub (lua_State * L, const char * s, const char * p, const char * r)
Definition at line 996 of file lauxlib.c.
Referenced by loadfunc(), searchpath(), and setpath().
luaL_len()
LUALIB_API lua_Integer luaL_len (lua_State * L, int idx)
Definition at line 803 of file lauxlib.c.
Referenced by addtoclib(), gctm(), and unpack().
luaL_loadbufferx()
LUALIB_API int luaL_loadbufferx (lua_State * L, const char * buff, size_t size, const char * name, const char * mode)
Definition at line 760 of file lauxlib.c.
Referenced by luaB_load().
luaL_loadfilex()
LUALIB_API int luaL_loadfilex (lua_State * L, const char * filename, const char * mode)
Definition at line 706 of file lauxlib.c.
Referenced by luaB_loadfile().
luaL_loadstring()
LUALIB_API int luaL_loadstring (lua_State * L, const char * s)
Definition at line 769 of file lauxlib.c.
luaL_newmetatable()
LUALIB_API int luaL_newmetatable (lua_State * L, const char * tname)
Definition at line 302 of file lauxlib.c.
Referenced by createmeta(), and newbox().
luaL_optinteger()
LUALIB_API lua_Integer luaL_optinteger (lua_State * L, int arg, lua_Integer def)
Definition at line 443 of file lauxlib.c.
Referenced by byteoffset(), codepoint(), db_sethook(), db_traceback(), f_seek(), luaB_collectgarbage(), luaB_error(), os_exit(), str_byte(), str_find_aux(), str_gsub(), str_sub(), str_unpack(), tconcat(), tremove(), unpack(), and utflen().
luaL_optlstring()
LUALIB_API const char * luaL_optlstring (lua_State * L, int arg, const char * def, size_t * len)
Definition at line 400 of file lauxlib.c.
Referenced by os_date(), str_rep(), and tconcat().
luaL_optnumber()
LUALIB_API lua_Number luaL_optnumber (lua_State * L, int arg, lua_Number def)
Definition at line 420 of file lauxlib.c.
Referenced by math_atan().
luaL_prepbuffsize()
LUALIB_API char * luaL_prepbuffsize (luaL_Buffer * B, size_t sz)
Definition at line 508 of file lauxlib.c.
Referenced by addliteral(), luaL_addlstring(), luaL_buffinitsize(), os_date(), packint(), read_chars(), str_format(), and str_pack().
luaL_pushresult()
LUALIB_API void luaL_pushresult (luaL_Buffer * B)
Definition at line 545 of file lauxlib.c.
Referenced by findloader(), luaL_gsub(), luaL_pushresultsize(), os_date(), read_all(), read_chars(), read_line(), searchpath(), str_dump(), str_format(), str_gsub(), str_pack(), tconcat(), and utfchar().
luaL_pushresultsize()
LUALIB_API void luaL_pushresultsize (luaL_Buffer * B, size_t sz)
Definition at line 555 of file lauxlib.c.
Referenced by str_char(), str_lower(), str_rep(), str_reverse(), and str_upper().
luaL_ref()
LUALIB_API int luaL_ref (lua_State * L, int t)
Definition at line 598 of file lauxlib.c.
luaL_requiref()
LUALIB_API void luaL_requiref (lua_State * L, const char * modname, lua_CFunction openf, int glb)
Definition at line 976 of file lauxlib.c.
Referenced by luaL_openlibs().
luaL_setfuncs()
LUALIB_API void luaL_setfuncs (lua_State * L, const luaL_Reg * l, int nup)
Definition at line 939 of file lauxlib.c.
Referenced by createmeta(), luaopen_base(), luaopen_base_sandbox(), and luaopen_package().
luaL_setmetatable()
LUALIB_API void luaL_setmetatable (lua_State * L, const char * tname)
Definition at line 315 of file lauxlib.c.
Referenced by newprefile().
luaL_testudata()
LUALIB_API void * luaL_testudata (lua_State * L, int ud, const char * tname)
Definition at line 321 of file lauxlib.c.
Referenced by io_type(), and luaL_checkudata().
luaL_tolstring()
LUALIB_API const char * luaL_tolstring (lua_State * L, int idx, size_t * len)
Definition at line 815 of file lauxlib.c.
Referenced by add_s(), addliteral(), luaB_tostring(), and str_format().
luaL_traceback()
LUALIB_API void luaL_traceback (lua_State * L, lua_State * L1, const char * msg, int level)
Definition at line 128 of file lauxlib.c.
Referenced by db_traceback().
luaL_unref()
LUALIB_API void luaL_unref (lua_State * L, int t, int ref)
Definition at line 619 of file lauxlib.c.
luaL_where()
LUALIB_API void luaL_where (lua_State * L, int level)
Definition at line 208 of file lauxlib.c.
Referenced by luaB_auxwrap(), luaB_error(), and luaL_error().
newbox()
static void * newbox (lua_State * L, size_t newsize) static
Definition at line 485 of file lauxlib.c.
Referenced by luaL_prepbuffsize().
pushfuncname()
static void pushfuncname (lua_State * L, lua_Debug * ar) static
Definition at line 97 of file lauxlib.c.
Referenced by luaL_traceback().
pushglobalfuncname()
static int pushglobalfuncname (lua_State * L, lua_Debug * ar) static
Definition at line 76 of file lauxlib.c.
Referenced by luaL_argerror(), and pushfuncname().
resizebox()
static void * resizebox (lua_State * L, int idx, size_t newsize) static
Definition at line 464 of file lauxlib.c.
Referenced by boxgc(), luaL_prepbuffsize(), luaL_pushresult(), newbox(), and resizebox().
skipBOM()
static int skipBOM (LoadF * lf) static
Definition at line 672 of file lauxlib.c.
Referenced by skipcomment().
skipcomment()
static int skipcomment (LoadF * lf, int * cp) static
Definition at line 693 of file lauxlib.c.
Referenced by luaL_loadfilex().
tag_error()
static void tag_error (lua_State * L, int arg, int tag) static
Definition at line 199 of file lauxlib.c.
Referenced by interror(), luaL_checklstring(), luaL_checknumber(), and luaL_checktype().
typeerror()
static int typeerror (lua_State * L, int arg, const char * tname) static
Definition at line 185 of file lauxlib.c.
Referenced by luaL_checkudata(), and tag_error().