APM:Libraries: libraries/AP_Scripting/lua/src/ldebug.h File Reference
ldebug.h File Reference
#include "lstate.h"
Macros
#define pcRel(pc, p) (cast(int, (pc) - (p)->code) - 1)
#define getfuncline(f, pc) (((f)->lineinfo) ? (f)->lineinfo[pc] : -1)
#define resethookcount(L) (L->hookcount = L->basehookcount)
Functions
LUAI_FUNC l_noret luaG_typeerror (lua_State *L, const TValue *o, const char *opname)
LUAI_FUNC l_noret luaG_concaterror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC l_noret luaG_opinterror (lua_State *L, const TValue *p1, const TValue *p2, const char *msg)
LUAI_FUNC l_noret luaG_tointerror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC l_noret luaG_ordererror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC l_noret luaG_runerror (lua_State *L, const char *fmt,...)
LUAI_FUNC const char * luaG_addinfo (lua_State *L, const char *msg, TString *src, int line)
LUAI_FUNC l_noret luaG_errormsg (lua_State *L)
LUAI_FUNC void luaG_traceexec (lua_State *L)
Macro Definition Documentation
getfuncline
#define getfuncline (f, pc) (((f)->lineinfo) ? (f)->lineinfo[pc] : -1)
Definition at line 16 of file ldebug.h.
Referenced by currentline(), luaG_traceexec(), and PrintCode().
pcRel
#define pcRel (pc, p) (cast(int, (pc) - (p)->code) - 1)
Definition at line 14 of file ldebug.h.
Referenced by currentpc(), and luaG_traceexec().
resethookcount
#define resethookcount (L) (L->hookcount = L->basehookcount)
Definition at line 18 of file ldebug.h.
Referenced by lua_newthread(), lua_sethook(), luaG_traceexec(), and preinit_thread().
Function Documentation
luaG_addinfo()
LUAI_FUNC const char * luaG_addinfo (lua_State * L, const char * msg, TString * src, int line)
Definition at line 629 of file ldebug.c.
Referenced by lexerror(), and luaG_runerror().
luaG_concaterror()
LUAI_FUNC l_noret luaG_concaterror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 592 of file ldebug.c.
Referenced by luaT_trybinTM().
luaG_errormsg()
LUAI_FUNC l_noret luaG_errormsg (lua_State * L)
Definition at line 641 of file ldebug.c.
Referenced by lua_error(), and luaG_runerror().
luaG_opinterror()
LUAI_FUNC l_noret luaG_opinterror (lua_State * L, const TValue * p1, const TValue * p2, const char * msg)
Definition at line 598 of file ldebug.c.
Referenced by luaT_trybinTM().
luaG_ordererror()
LUAI_FUNC l_noret luaG_ordererror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 618 of file ldebug.c.
Referenced by luaV_lessequal(), and luaV_lessthan().
luaG_runerror()
LUAI_FUNC l_noret luaG_runerror (lua_State * L, const char * fmt, ...)
Definition at line 653 of file ldebug.c.
Referenced by findindex(), lua_yieldk(), luaD_growstack(), luaG_ordererror(), luaG_tointerror(), luaG_typeerror(), luaH_newkey(), luaM_growaux_(), luaM_toobig(), luaO_pushvfstring(), luaV_concat(), luaV_div(), luaV_execute(), luaV_finishget(), luaV_finishset(), luaV_mod(), setnodevector(), and stackerror().
luaG_tointerror()
LUAI_FUNC l_noret luaG_tointerror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 610 of file ldebug.c.
Referenced by luaT_trybinTM().
luaG_traceexec()
LUAI_FUNC void luaG_traceexec (lua_State * L)
Definition at line 667 of file ldebug.c.
luaG_typeerror()
LUAI_FUNC l_noret luaG_typeerror (lua_State * L, const TValue * o, const char * opname)
Definition at line 586 of file ldebug.c.
Referenced by luaG_concaterror(), luaG_opinterror(), luaV_finishget(), luaV_finishset(), luaV_objlen(), and tryfuncTM().