APM:Libraries: libraries/AP_Scripting/lua/src/ldo.h File Reference
ldo.h File Reference
#include "lobject.h"
#include "lstate.h"
#include "lzio.h"
Macros
#define luaD_checkstackaux(L, n, pre, pos)
#define luaD_checkstack(L, n) luaD_checkstackaux(L,n,(void)0,(void)0)
#define savestack(L, p) ((char *)(p) - (char *)L->stack)
#define restorestack(L, n) ((TValue *)((char *)L->stack + (n)))
Typedefs
typedef void(* Pfunc) (lua_State *L, void *ud)
Functions
LUAI_FUNC int luaD_protectedparser (lua_State *L, ZIO *z, const char *name, const char *mode)
LUAI_FUNC void luaD_hook (lua_State *L, int event, int line)
LUAI_FUNC int luaD_precall (lua_State *L, StkId func, int nresults)
LUAI_FUNC void luaD_call (lua_State *L, StkId func, int nResults)
LUAI_FUNC void luaD_callnoyield (lua_State *L, StkId func, int nResults)
LUAI_FUNC int luaD_pcall (lua_State *L, Pfunc func, void *u, ptrdiff_t oldtop, ptrdiff_t ef)
LUAI_FUNC int luaD_poscall (lua_State *L, CallInfo *ci, StkId firstResult, int nres)
LUAI_FUNC void luaD_reallocstack (lua_State *L, int newsize)
LUAI_FUNC void luaD_growstack (lua_State *L, int n)
LUAI_FUNC void luaD_shrinkstack (lua_State *L)
LUAI_FUNC void luaD_inctop (lua_State *L)
LUAI_FUNC l_noret luaD_throw (lua_State *L, int errcode)
LUAI_FUNC int luaD_rawrunprotected (lua_State *L, Pfunc f, void *ud)
Macro Definition Documentation
luaD_checkstack
#define luaD_checkstack (L, n) luaD_checkstackaux(L,n,(void)0,(void)0)
Definition at line 28 of file ldo.h.
Referenced by luaD_hook(), luaD_inctop(), luaO_pushvfstring(), and luaV_execute().
luaD_checkstackaux
#define luaD_checkstackaux (L, n, pre, pos)
Value:
    if (L->stack_last - L->top <= (n)) \
      { pre; luaD_growstack(L, n); pos; } else { condmovestack(L,pre,pos); }
Definition at line 23 of file ldo.h.
restorestack
#define restorestack (L, n) ((TValue *)((char *)L->stack + (n)))
Definition at line 33 of file ldo.h.
Referenced by luaD_hook(), luaD_pcall(), luaD_poscall(), luaG_errormsg(), luaT_callTM(), recover(), resume(), and swapextra().
savestack
#define savestack (L, p) ((char *)(p) - (char *)L->stack)
Definition at line 32 of file ldo.h.
Referenced by GCTM(), lua_pcallk(), lua_yieldk(), luaD_hook(), luaD_poscall(), luaD_protectedparser(), luaT_callTM(), and swapextra().
Typedef Documentation
Pfunc
typedef void(* Pfunc) (lua_State *L, void *ud)
Definition at line 37 of file ldo.h.
Function Documentation
luaD_call()
LUAI_FUNC void luaD_call (lua_State * L, StkId func, int nResults)
Definition at line 504 of file ldo.c.
Referenced by lua_callk(), lua_pcallk(), luaD_callnoyield(), luaT_callTM(), and luaV_execute().
luaD_callnoyield()
LUAI_FUNC void luaD_callnoyield (lua_State * L, StkId func, int nResults)
Definition at line 516 of file ldo.c.
Referenced by dothecall(), f_call(), lua_callk(), luaG_errormsg(), and luaT_callTM().
luaD_growstack()
LUAI_FUNC void luaD_growstack (lua_State * L, int n)
Definition at line 200 of file ldo.c.
Referenced by growstack().
luaD_hook()
LUAI_FUNC void luaD_hook (lua_State * L, int event, int line)
Definition at line 262 of file ldo.c.
Referenced by callhook(), luaD_poscall(), luaD_precall(), and luaG_traceexec().
luaD_inctop()
LUAI_FUNC void luaD_inctop (lua_State * L)
Definition at line 249 of file ldo.c.
Referenced by luaO_pushvfstring(), luaU_undump(), luaY_parser(), and pushstr().
luaD_pcall()
LUAI_FUNC int luaD_pcall (lua_State * L, Pfunc func, void * u, ptrdiff_t oldtop, ptrdiff_t ef)
Definition at line 730 of file ldo.c.
Referenced by GCTM(), lua_pcallk(), and luaD_protectedparser().
luaD_poscall()
LUAI_FUNC int luaD_poscall (lua_State * L, CallInfo * ci, StkId firstResult, int nres)
Definition at line 385 of file ldo.c.
Referenced by finishCcall(), luaD_precall(), luaV_execute(), and resume().
luaD_precall()
LUAI_FUNC int luaD_precall (lua_State * L, StkId func, int nresults)
Definition at line 422 of file ldo.c.
Referenced by luaD_call(), luaD_precall(), luaV_execute(), and resume().
luaD_protectedparser()
LUAI_FUNC int luaD_protectedparser (lua_State * L, ZIO * z, const char * name, const char * mode)
Definition at line 796 of file ldo.c.
Referenced by lua_load().
luaD_rawrunprotected()
LUAI_FUNC int luaD_rawrunprotected (lua_State * L, Pfunc f, void * ud)
Definition at line 139 of file ldo.c.
Referenced by lua_checkstack(), lua_newstate(), lua_resume(), luaD_pcall(), and luaH_resize().
luaD_reallocstack()
LUAI_FUNC void luaD_reallocstack (lua_State * L, int newsize)
Definition at line 186 of file ldo.c.
Referenced by luaD_growstack(), and luaD_shrinkstack().
luaD_shrinkstack()
LUAI_FUNC void luaD_shrinkstack (lua_State * L)
Definition at line 230 of file ldo.c.
Referenced by luaD_pcall(), recover(), and traversethread().
luaD_throw()
LUAI_FUNC l_noret luaD_throw (lua_State * L, int errcode)
Definition at line 111 of file ldo.c.
Referenced by checkmode(), error(), GCTM(), lexerror(), lua_yieldk(), luaD_growstack(), luaD_throw(), luaG_errormsg(), luaG_traceexec(), luaH_resize(), luaM_realloc_(), and stackerror().