APM:Libraries: libraries/AP_Scripting/lua/src/ldo.c File Reference
ldo.c File Reference
#include "lprefix.h"
#include <setjmp.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lopcodes.h"
#include "lparser.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lundump.h"
#include "lvm.h"
#include "lzio.h"
Classes
struct lua_longjmp
struct SParser
Macros
#define ldo_c
#define LUA_CORE
#define errorstatus(s) ((s) > LUA_YIELD)
#define LUAI_THROW(L, c) longjmp((c)->b, 1)
#define LUAI_TRY(L, c, a) if (setjmp((c)->b) == 0) { a }
#define luai_jmpbuf jmp_buf
#define ERRORSTACKSIZE (LUAI_MAXSTACK + 200)
#define next_ci(L) (L->ci = (L->ci->next ? L->ci->next : luaE_extendCI(L)))
#define checkstackp(L, n, p)
Functions
static void seterrorobj (lua_State *L, int errcode, StkId oldtop)
l_noret luaD_throw (lua_State *L, int errcode)
int luaD_rawrunprotected (lua_State *L, Pfunc f, void *ud)
static void correctstack (lua_State *L, TValue *oldstack)
void luaD_reallocstack (lua_State *L, int newsize)
void luaD_growstack (lua_State *L, int n)
static int stackinuse (lua_State *L)
void luaD_shrinkstack (lua_State *L)
void luaD_inctop (lua_State *L)
void luaD_hook (lua_State *L, int event, int line)
static void callhook (lua_State *L, CallInfo *ci)
static StkId adjust_varargs (lua_State *L, Proto *p, int actual)
static void tryfuncTM (lua_State *L, StkId func)
static int moveresults (lua_State *L, const TValue *firstResult, StkId res, int nres, int wanted)
int luaD_poscall (lua_State *L, CallInfo *ci, StkId firstResult, int nres)
int luaD_precall (lua_State *L, StkId func, int nresults)
static void stackerror (lua_State *L)
void luaD_call (lua_State *L, StkId func, int nResults)
void luaD_callnoyield (lua_State *L, StkId func, int nResults)
static void finishCcall (lua_State *L, int status)
static void unroll (lua_State *L, void *ud)
static CallInfo * findpcall (lua_State *L)
static int recover (lua_State *L, int status)
static int resume_error (lua_State *L, const char *msg, int narg)
static void resume (lua_State *L, void *ud)
LUA_API int lua_resume (lua_State *L, lua_State *from, int nargs)
LUA_API int lua_isyieldable (lua_State *L)
LUA_API int lua_yieldk (lua_State *L, int nresults, lua_KContext ctx, lua_KFunction k)
int luaD_pcall (lua_State *L, Pfunc func, void *u, ptrdiff_t old_top, ptrdiff_t ef)
static void checkmode (lua_State *L, const char *mode, const char *x)
static void f_parser (lua_State *L, void *ud)
int luaD_protectedparser (lua_State *L, ZIO *z, const char *name, const char *mode)
Macro Definition Documentation
checkstackp
#define checkstackp (L, n, p)
Value:
  luaD_checkstackaux(L, n, \
    ptrdiff_t t__ = savestack(L, p);  /* save 'p' */ \
    luaC_checkGC(L),  /* stack grow uses memory */ \
    p = restorestack(L, t__))  /* 'pos' part: restore 'p' */
Definition at line 408 of file ldo.c.
Referenced by luaD_precall().
ERRORSTACKSIZE
#define ERRORSTACKSIZE (LUAI_MAXSTACK + 200)
Definition at line 183 of file ldo.c.
Referenced by luaD_growstack(), and luaD_reallocstack().
errorstatus
#define errorstatus (s) ((s) > LUA_YIELD)
Definition at line 39 of file ldo.c.
Referenced by lua_resume().
ldo_c
#define ldo_c
Definition at line 7 of file ldo.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file ldo.c.
luai_jmpbuf
#define luai_jmpbuf jmp_buf
Definition at line 76 of file ldo.c.
LUAI_THROW
#define LUAI_THROW (L, c) longjmp((c)->b, 1)
Definition at line 74 of file ldo.c.
Referenced by luaD_throw().
LUAI_TRY
#define LUAI_TRY (L, c, a) if (setjmp((c)->b) == 0) { a }
Definition at line 75 of file ldo.c.
Referenced by luaD_rawrunprotected().
next_ci
#define next_ci (L) (L->ci = (L->ci->next ? L->ci->next : luaE_extendCI(L)))
Definition at line 404 of file ldo.c.
Referenced by luaD_precall().
Function Documentation
adjust_varargs()
static StkId adjust_varargs (lua_State * L, Proto * p, int actual) static
Definition at line 302 of file ldo.c.
Referenced by luaD_precall().
callhook()
static void callhook (lua_State * L, CallInfo * ci) static
Definition at line 289 of file ldo.c.
Referenced by luaD_precall().
checkmode()
static void checkmode (lua_State * L, const char * mode, const char * x) static
Definition at line 766 of file ldo.c.
Referenced by f_parser().
correctstack()
static void correctstack (lua_State * L, TValue * oldstack) static
Definition at line 167 of file ldo.c.
Referenced by luaD_reallocstack().
f_parser()
static void f_parser (lua_State * L, void * ud) static
Definition at line 775 of file ldo.c.
Referenced by luaD_protectedparser().
findpcall()
static CallInfo * findpcall (lua_State * L) static
Definition at line 575 of file ldo.c.
Referenced by recover().
finishCcall()
static void finishCcall (lua_State * L, int status) static
Definition at line 527 of file ldo.c.
Referenced by unroll().
lua_isyieldable()
LUA_API int lua_isyieldable (lua_State * L)
Definition at line 696 of file ldo.c.
Referenced by luaB_yieldable().
lua_resume()
LUA_API int lua_resume (lua_State * L, lua_State * from, int nargs)
Definition at line 657 of file ldo.c.
Referenced by auxresume().
lua_yieldk()
LUA_API int lua_yieldk (lua_State * L, int nresults, lua_KContext ctx, lua_KFunction k)
Definition at line 701 of file ldo.c.
luaD_call()
void luaD_call (lua_State * L, StkId func, int nResults)
Definition at line 504 of file ldo.c.
Referenced by lua_callk(), lua_pcallk(), luaD_callnoyield(), luaT_callTM(), and luaV_execute().
luaD_callnoyield()
void luaD_callnoyield (lua_State * L, StkId func, int nResults)
Definition at line 516 of file ldo.c.
Referenced by dothecall(), f_call(), lua_callk(), luaG_errormsg(), and luaT_callTM().
luaD_growstack()
void luaD_growstack (lua_State * L, int n)
Definition at line 200 of file ldo.c.
Referenced by growstack().
luaD_hook()
void luaD_hook (lua_State * L, int event, int line)
Definition at line 262 of file ldo.c.
Referenced by callhook(), luaD_poscall(), luaD_precall(), and luaG_traceexec().
luaD_inctop()
void luaD_inctop (lua_State * L)
Definition at line 249 of file ldo.c.
Referenced by luaO_pushvfstring(), luaU_undump(), luaY_parser(), and pushstr().
luaD_pcall()
int luaD_pcall (lua_State * L, Pfunc func, void * u, ptrdiff_t old_top, ptrdiff_t ef)
Definition at line 730 of file ldo.c.
Referenced by GCTM(), lua_pcallk(), and luaD_protectedparser().
luaD_poscall()
int luaD_poscall (lua_State * L, CallInfo * ci, StkId firstResult, int nres)
Definition at line 385 of file ldo.c.
Referenced by finishCcall(), luaD_precall(), luaV_execute(), and resume().
luaD_precall()
int luaD_precall (lua_State * L, StkId func, int nresults)
Definition at line 422 of file ldo.c.
Referenced by luaD_call(), luaD_precall(), luaV_execute(), and resume().
luaD_protectedparser()
int luaD_protectedparser (lua_State * L, ZIO * z, const char * name, const char * mode)
Definition at line 796 of file ldo.c.
Referenced by lua_load().
luaD_rawrunprotected()
int luaD_rawrunprotected (lua_State * L, Pfunc f, void * ud)
Definition at line 139 of file ldo.c.
Referenced by lua_checkstack(), lua_newstate(), lua_resume(), luaD_pcall(), and luaH_resize().
luaD_reallocstack()
void luaD_reallocstack (lua_State * L, int newsize)
Definition at line 186 of file ldo.c.
Referenced by luaD_growstack(), and luaD_shrinkstack().
luaD_shrinkstack()
void luaD_shrinkstack (lua_State * L)
Definition at line 230 of file ldo.c.
Referenced by luaD_pcall(), recover(), and traversethread().
luaD_throw()
l_noret luaD_throw (lua_State * L, int errcode)
Definition at line 111 of file ldo.c.
Referenced by checkmode(), error(), GCTM(), lexerror(), lua_yieldk(), luaD_growstack(), luaD_throw(), luaG_errormsg(), luaG_traceexec(), luaH_resize(), luaM_realloc_(), and stackerror().
moveresults()
static int moveresults (lua_State * L, const TValue * firstResult, StkId res, int nres, int wanted) static
Definition at line 343 of file ldo.c.
Referenced by luaD_poscall().
recover()
static int recover (lua_State * L, int status) static
Definition at line 590 of file ldo.c.
Referenced by lua_resume().
resume()
static void resume (lua_State * L, void * ud) static
Definition at line 628 of file ldo.c.
Referenced by lua_resume().
resume_error()
static int resume_error (lua_State * L, const char * msg, int narg) static
Definition at line 612 of file ldo.c.
Referenced by lua_resume().
seterrorobj()
static void seterrorobj (lua_State * L, int errcode, StkId oldtop) static
Definition at line 92 of file ldo.c.
Referenced by lua_resume(), luaD_pcall(), luaD_throw(), and recover().
stackerror()
static void stackerror (lua_State * L) static
Definition at line 490 of file ldo.c.
Referenced by luaD_call().
stackinuse()
static int stackinuse (lua_State * L) static
Definition at line 219 of file ldo.c.
Referenced by luaD_shrinkstack().
tryfuncTM()
static void tryfuncTM (lua_State * L, StkId func) static
Definition at line 324 of file ldo.c.
Referenced by luaD_precall().
unroll()
static void unroll (lua_State * L, void * ud) static
Definition at line 557 of file ldo.c.
Referenced by lua_resume(), and resume().