APM:Libraries: libraries/AP_Scripting/lua/src/lgc.c File Reference
lgc.c File Reference
#include "lprefix.h"
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
Macros
#define lgc_c
#define LUA_CORE
#define GCSinsideatomic (GCSpause + 1)
#define GCSWEEPCOST ((sizeof(TString) + 4) / 4)
#define GCSWEEPMAX (cast_int((GCSTEPSIZE / GCSWEEPCOST) / 4))
#define GCFINALIZECOST GCSWEEPCOST
#define STEPMULADJ 200
#define PAUSEADJ 100
#define maskcolors (~(bitmask(BLACKBIT) | WHITEBITS))
#define makewhite(g, x) (x->marked = cast_byte((x->marked & maskcolors) | luaC_white(g)))
#define white2gray(x) resetbits(x->marked, WHITEBITS)
#define black2gray(x) resetbit(x->marked, BLACKBIT)
#define valiswhite(x) (iscollectable(x) && iswhite(gcvalue(x)))
#define checkdeadkey(n) lua_assert(!ttisdeadkey(gkey(n)) || ttisnil(gval(n)))
#define checkconsistency(obj) lua_longassert(!iscollectable(obj) || righttt(obj))
#define markvalue(g, o)
#define markobject(g, t) { if (iswhite(t)) reallymarkobject(g, obj2gco(t)); }
#define markobjectN(g, t) { if (t) markobject(g,t); }
#define gnodelast(h) gnode(h, cast(size_t, sizenode(h)))
#define linkgclist(o, p) ((o)->gclist = (p), (p) = obj2gco(o))
#define sweepwholelist(L, p) sweeplist(L,p,MAX_LUMEM)
Functions
static void reallymarkobject (global_State *g, GCObject *o)
static void removeentry (Node *n)
static int iscleared (global_State *g, const TValue *o)
void luaC_barrier_ (lua_State *L, GCObject *o, GCObject *v)
void luaC_barrierback_ (lua_State *L, Table *t)
void luaC_upvalbarrier_ (lua_State *L, UpVal *uv)
void luaC_fix (lua_State *L, GCObject *o)
GCObject * luaC_newobj (lua_State *L, int tt, size_t sz)
static void markmt (global_State *g)
static void markbeingfnz (global_State *g)
static void remarkupvals (global_State *g)
static void restartcollection (global_State *g)
static void traverseweakvalue (global_State *g, Table *h)
static int traverseephemeron (global_State *g, Table *h)
static void traversestrongtable (global_State *g, Table *h)
static lu_mem traversetable (global_State *g, Table *h)
static int traverseproto (global_State *g, Proto *f)
static lu_mem traverseCclosure (global_State *g, CClosure *cl)
static lu_mem traverseLclosure (global_State *g, LClosure *cl)
static lu_mem traversethread (global_State *g, lua_State *th)
static void propagatemark (global_State *g)
static void propagateall (global_State *g)
static void convergeephemerons (global_State *g)
static void clearkeys (global_State *g, GCObject *l, GCObject *f)
static void clearvalues (global_State *g, GCObject *l, GCObject *f)
void luaC_upvdeccount (lua_State *L, UpVal *uv)
static void freeLclosure (lua_State *L, LClosure *cl)
static void freeobj (lua_State *L, GCObject *o)
static GCObject ** sweeplist (lua_State *L, GCObject **p, lu_mem count)
static GCObject ** sweeptolive (lua_State *L, GCObject **p)
static void checkSizes (lua_State *L, global_State *g)
static GCObject * udata2finalize (global_State *g)
static void dothecall (lua_State *L, void *ud)
static void GCTM (lua_State *L, int propagateerrors)
static int runafewfinalizers (lua_State *L)
static void callallpendingfinalizers (lua_State *L)
static GCObject ** findlast (GCObject **p)
static void separatetobefnz (global_State *g, int all)
void luaC_checkfinalizer (lua_State *L, GCObject *o, Table *mt)
static void setpause (global_State *g)
static void entersweep (lua_State *L)
void luaC_freeallobjects (lua_State *L)
static l_mem atomic (lua_State *L)
static lu_mem sweepstep (lua_State *L, global_State *g, int nextstate, GCObject **nextlist)
static lu_mem singlestep (lua_State *L)
void luaC_runtilstate (lua_State *L, int statesmask)
static l_mem getdebt (global_State *g)
void luaC_step (lua_State *L)
void luaC_fullgc (lua_State *L, int isemergency)
Macro Definition Documentation
black2gray
#define black2gray (x) resetbit(x->marked, BLACKBIT)
Definition at line 71 of file lgc.c.
Referenced by luaC_barrierback_(), propagatemark(), and traversetable().
checkconsistency
#define checkconsistency (obj) lua_longassert(!iscollectable(obj) || righttt(obj))
Definition at line 79 of file lgc.c.
checkdeadkey
#define checkdeadkey (n) lua_assert(!ttisdeadkey(gkey(n)) || ttisnil(gval(n)))
Definition at line 76 of file lgc.c.
Referenced by traverseephemeron(), traversestrongtable(), and traverseweakvalue().
GCFINALIZECOST
#define GCFINALIZECOST GCSWEEPCOST
Definition at line 45 of file lgc.c.
Referenced by singlestep().
GCSinsideatomic
#define GCSinsideatomic (GCSpause + 1)
Definition at line 33 of file lgc.c.
Referenced by atomic(), traverseLclosure(), and traversethread().
GCSWEEPCOST
#define GCSWEEPCOST ((sizeof(TString) + 4) / 4)
Definition at line 39 of file lgc.c.
Referenced by sweepstep().
GCSWEEPMAX
#define GCSWEEPMAX (cast_int((GCSTEPSIZE / GCSWEEPCOST) / 4))
Definition at line 42 of file lgc.c.
Referenced by sweepstep().
gnodelast
#define gnodelast (h) gnode(h, cast(size_t, sizenode(h)))
Definition at line 107 of file lgc.c.
Referenced by clearkeys(), clearvalues(), traverseephemeron(), traversestrongtable(), and traverseweakvalue().
lgc_c
#define lgc_c
Definition at line 7 of file lgc.c.
linkgclist
#define linkgclist (o, p) ((o)->gclist = (p), (p) = obj2gco(o))
Definition at line 113 of file lgc.c.
Referenced by luaC_barrierback_(), propagatemark(), reallymarkobject(), traverseephemeron(), traversetable(), and traverseweakvalue().
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lgc.c.
makewhite
#define makewhite (g, x) (x->marked = cast_byte((x->marked & maskcolors) | luaC_white(g)))
Definition at line 67 of file lgc.c.
Referenced by luaC_barrier_(), luaC_checkfinalizer(), singlestep(), and udata2finalize().
markobject
#define markobject (g, t) { if (iswhite(t)) reallymarkobject(g, obj2gco(t)); }
Definition at line 86 of file lgc.c.
Referenced by atomic(), iscleared(), luaC_upvalbarrier_(), markbeingfnz(), and restartcollection().
markobjectN
#define markobjectN (g, t) { if (t) markobject(g,t); }
Definition at line 92 of file lgc.c.
Referenced by markmt(), reallymarkobject(), traverseLclosure(), traverseproto(), and traversetable().
markvalue
#define markvalue (g, o)
Value:
  { checkconsistency(o); \
  if (valiswhite(o)) reallymarkobject(g,gcvalue(o)); }
Definition at line 83 of file lgc.c.
Referenced by atomic(), remarkupvals(), restartcollection(), traverseCclosure(), traverseLclosure(), traverseproto(), traversestrongtable(), traversethread(), and traverseweakvalue().
maskcolors
#define maskcolors (~(bitmask(BLACKBIT) | WHITEBITS))
Definition at line 66 of file lgc.c.
Referenced by sweeplist().
PAUSEADJ
#define PAUSEADJ 100
Definition at line 59 of file lgc.c.
Referenced by setpause().
STEPMULADJ
#define STEPMULADJ 200
Definition at line 52 of file lgc.c.
Referenced by getdebt(), and luaC_step().
sweepwholelist
#define sweepwholelist (L, p) sweeplist(L,p,MAX_LUMEM)
Definition at line 724 of file lgc.c.
Referenced by luaC_freeallobjects().
valiswhite
#define valiswhite (x) (iscollectable(x) && iswhite(gcvalue(x)))
Definition at line 74 of file lgc.c.
Referenced by reallymarkobject(), removeentry(), and traverseephemeron().
white2gray
#define white2gray (x) resetbits(x->marked, WHITEBITS)
Definition at line 70 of file lgc.c.
Referenced by luaC_fix(), and reallymarkobject().
Function Documentation
atomic()
static l_mem atomic (lua_State * L) static
Definition at line 982 of file lgc.c.
Referenced by singlestep().
callallpendingfinalizers()
static void callallpendingfinalizers (lua_State * L) static
Definition at line 859 of file lgc.c.
Referenced by luaC_freeallobjects().
checkSizes()
static void checkSizes (lua_State * L, global_State * g) static
Definition at line 778 of file lgc.c.
Referenced by singlestep().
clearkeys()
static void clearkeys (global_State * g, GCObject * l, GCObject * f) static
Definition at line 639 of file lgc.c.
Referenced by atomic().
clearvalues()
static void clearvalues (global_State * g, GCObject * l, GCObject * f) static
Definition at line 658 of file lgc.c.
Referenced by atomic().
convergeephemerons()
static void convergeephemerons (global_State * g) static
Definition at line 608 of file lgc.c.
Referenced by atomic().
dothecall()
static void dothecall (lua_State * L, void * ud) static
Definition at line 801 of file lgc.c.
Referenced by GCTM().
entersweep()
static void entersweep (lua_State * L) static
Definition at line 959 of file lgc.c.
Referenced by luaC_fullgc(), and singlestep().
findlast()
static GCObject ** findlast (GCObject ** p) static
Definition at line 869 of file lgc.c.
Referenced by separatetobefnz().
freeLclosure()
static void freeLclosure (lua_State * L, LClosure * cl) static
Definition at line 686 of file lgc.c.
Referenced by freeobj().
freeobj()
static void freeobj (lua_State * L, GCObject * o) static
Definition at line 697 of file lgc.c.
Referenced by sweeplist().
GCTM()
static void GCTM (lua_State * L, int propagateerrors) static
Definition at line 807 of file lgc.c.
Referenced by callallpendingfinalizers(), and runafewfinalizers().
getdebt()
static l_mem getdebt (global_State * g) static
Definition at line 1115 of file lgc.c.
Referenced by luaC_step().
iscleared()
static int iscleared (global_State * g, const TValue * o) static
Definition at line 139 of file lgc.c.
Referenced by clearkeys(), clearvalues(), traverseephemeron(), and traverseweakvalue().
luaC_barrier_()
void luaC_barrier_ (lua_State * L, GCObject * o, GCObject * v)
Definition at line 155 of file lgc.c.
luaC_barrierback_()
void luaC_barrierback_ (lua_State * L, Table * t)
Definition at line 171 of file lgc.c.
luaC_checkfinalizer()
void luaC_checkfinalizer (lua_State * L, GCObject * o, Table * mt)
Definition at line 902 of file lgc.c.
Referenced by lua_setmetatable().
luaC_fix()
void luaC_fix (lua_State * L, GCObject * o)
Definition at line 194 of file lgc.c.
Referenced by luaS_init(), luaT_init(), and luaX_init().
luaC_freeallobjects()
void luaC_freeallobjects (lua_State * L)
Definition at line 967 of file lgc.c.
Referenced by close_state().
luaC_fullgc()
void luaC_fullgc (lua_State * L, int isemergency)
Definition at line 1159 of file lgc.c.
Referenced by lua_gc(), and luaM_realloc_().
luaC_newobj()
GCObject * luaC_newobj (lua_State * L, int tt, size_t sz)
Definition at line 208 of file lgc.c.
Referenced by createstrobj(), luaF_newCclosure(), luaF_newLclosure(), luaF_newproto(), luaH_new(), and luaS_newudata().
luaC_runtilstate()
void luaC_runtilstate (lua_State * L, int statesmask)
Definition at line 1104 of file lgc.c.
Referenced by luaC_fullgc().
luaC_step()
void luaC_step (lua_State * L)
Definition at line 1129 of file lgc.c.
Referenced by lua_gc().
luaC_upvalbarrier_()
void luaC_upvalbarrier_ (lua_State * L, UpVal * uv)
Definition at line 185 of file lgc.c.
luaC_upvdeccount()
void luaC_upvdeccount (lua_State * L, UpVal * uv)
Definition at line 678 of file lgc.c.
Referenced by freeLclosure(), and lua_upvaluejoin().
markbeingfnz()
static void markbeingfnz (global_State * g) static
Definition at line 299 of file lgc.c.
Referenced by atomic(), and restartcollection().
markmt()
static void markmt (global_State * g) static
Definition at line 289 of file lgc.c.
Referenced by atomic(), and restartcollection().
propagateall()
static void propagateall (global_State * g) static
Definition at line 603 of file lgc.c.
Referenced by atomic(), convergeephemerons(), and singlestep().
propagatemark()
static void propagatemark (global_State * g) static
Definition at line 559 of file lgc.c.
Referenced by propagateall(), and singlestep().
reallymarkobject()
static void reallymarkobject (global_State * g, GCObject * o) static
Definition at line 235 of file lgc.c.
Referenced by luaC_barrier_(), and traverseephemeron().
remarkupvals()
static void remarkupvals (global_State * g) static
Definition at line 312 of file lgc.c.
Referenced by atomic().
removeentry()
static void removeentry (Node * n) static
Definition at line 125 of file lgc.c.
Referenced by clearkeys(), clearvalues(), traverseephemeron(), traversestrongtable(), and traverseweakvalue().
restartcollection()
static void restartcollection (global_State * g) static
Definition at line 337 of file lgc.c.
Referenced by singlestep().
runafewfinalizers()
static int runafewfinalizers (lua_State * L) static
Definition at line 844 of file lgc.c.
Referenced by luaC_step(), and singlestep().
separatetobefnz()
static void separatetobefnz (global_State * g, int all) static
Definition at line 880 of file lgc.c.
Referenced by atomic(), and luaC_freeallobjects().
setpause()
static void setpause (global_State * g) static
Definition at line 940 of file lgc.c.
Referenced by luaC_fullgc(), and luaC_step().
singlestep()
static lu_mem singlestep (lua_State * L) static
Definition at line 1045 of file lgc.c.
Referenced by luaC_runtilstate(), and luaC_step().
sweeplist()
static GCObject ** sweeplist (lua_State * L, GCObject ** p, lu_mem count) static
Definition at line 735 of file lgc.c.
Referenced by entersweep(), sweepstep(), and sweeptolive().
sweepstep()
static lu_mem sweepstep (lua_State * L, global_State * g, int nextstate, GCObject ** nextlist) static
Definition at line 1029 of file lgc.c.
Referenced by singlestep().
sweeptolive()
static GCObject ** sweeptolive (lua_State * L, GCObject ** p) static
Definition at line 758 of file lgc.c.
Referenced by luaC_checkfinalizer().
traverseCclosure()
static lu_mem traverseCclosure (global_State * g, CClosure * cl) static
Definition at line 501 of file lgc.c.
Referenced by propagatemark().
traverseephemeron()
static int traverseephemeron (global_State * g, Table * h) static
Definition at line 394 of file lgc.c.
Referenced by convergeephemerons(), and traversetable().
traverseLclosure()
static lu_mem traverseLclosure (global_State * g, LClosure * cl) static
Definition at line 514 of file lgc.c.
Referenced by propagatemark().
traverseproto()
static int traverseproto (global_State * g, Proto * f) static
Definition at line 479 of file lgc.c.
Referenced by propagatemark().
traversestrongtable()
static void traversestrongtable (global_State * g, Table * h) static
Definition at line 433 of file lgc.c.
Referenced by traversetable().
traversetable()
static lu_mem traversetable (global_State * g, Table * h) static
Definition at line 451 of file lgc.c.
Referenced by propagatemark().
traversethread()
static lu_mem traversethread (global_State * g, lua_State * th) static
Definition at line 530 of file lgc.c.
Referenced by propagatemark().
traverseweakvalue()
static void traverseweakvalue (global_State * g, Table * h) static
Definition at line 361 of file lgc.c.
Referenced by traversetable().
udata2finalize()
static GCObject * udata2finalize (global_State * g) static
Definition at line 788 of file lgc.c.
Referenced by GCTM().