APM:Libraries: libraries/AP_Math/location.h File Reference
location.h File Reference
#include <inttypes.h>
#include "vector2.h"
#include "vector3.h"
Functions
template<typename T >
float get_horizontal_distance_cm (const Vector2< T > &origin, const Vector2< T > &destination)
float get_bearing_cd (const Vector2f &origin, const Vector2f &destination)
void wgsllh2ecef (const Vector3d &llh, Vector3d &ecef)
void wgsecef2llh (const Vector3d &ecef, Vector3d &llh)
bool check_lat (float lat) WARN_IF_UNUSED
bool check_lng (float lng) WARN_IF_UNUSED
bool check_lat (int32_t lat) WARN_IF_UNUSED
bool check_lng (int32_t lng) WARN_IF_UNUSED
bool check_latlng (float lat, float lng) WARN_IF_UNUSED
bool check_latlng (int32_t lat, int32_t lng) WARN_IF_UNUSED
Function Documentation
check_lat() [1/2]
bool check_lat (float lat)
Definition at line 37 of file location.cpp.
Referenced by Location::check_latlng(), check_latlng(), and check_latlng().
check_lat() [2/2]
bool check_lat (int32_t lat)
Definition at line 45 of file location.cpp.
check_latlng() [1/2]
bool check_latlng (float lat, float lng)
Definition at line 53 of file location.cpp.
Referenced by AP_Mount::handle_global_position_int().
check_latlng() [2/2]
bool check_latlng (int32_t lat, int32_t lng)
Definition at line 57 of file location.cpp.
check_lng() [1/2]
bool check_lng (float lng)
Definition at line 41 of file location.cpp.
Referenced by Location::check_latlng(), check_latlng(), and check_latlng().
check_lng() [2/2]
bool check_lng (int32_t lng)
Definition at line 49 of file location.cpp.
get_bearing_cd()
float get_bearing_cd (const Vector2f & origin, const Vector2f & destination)
Definition at line 27 of file location.cpp.
Referenced by AC_PosControl::get_bearing_to_target_cd(), AC_WPNav::get_wp_bearing_to_destination(), AC_WPNav_OA::get_wp_bearing_to_destination(), and AC_Circle::update().
get_horizontal_distance_cm()
template<typename T > float get_horizontal_distance_cm (const Vector2< T > & origin, const Vector2< T > & destination)
Definition at line 14 of file location.h.
Referenced by AC_PosControl::get_pos_error_xy_cm(), AC_WPNav::get_wp_distance_to_destination(), and AC_WPNav_OA::get_wp_distance_to_destination().
wgsecef2llh()
void wgsecef2llh (const Vector3d & ecef, Vector3d & llh)
Definition at line 42 of file location_double.cpp.
Referenced by test_wgs_conversion_functions().
wgsllh2ecef()
void wgsllh2ecef (const Vector3d & llh, Vector3d & ecef)
Definition at line 32 of file location_double.cpp.
Referenced by test_wgs_conversion_functions().