APM:Libraries: libraries/AP_Scripting/lua/src/lstate.c File Reference
lstate.c File Reference
#include "lprefix.h"
#include <stddef.h>
#include <string.h>
#include "lua.h"
#include "lapi.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lgc.h"
#include "llex.h"
#include "lmem.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "ltm.h"
#include "lauxlib.h"
#include <time.h>
Classes
struct LX
struct LG
Macros
#define lstate_c
#define LUA_CORE
#define LUAI_GCPAUSE 200 /* 200% */
#define LUAI_GCMUL 200 /* GC runs 'twice the speed' of memory allocation */
#define luai_makeseed() cast(unsigned int, time(NULL))
#define fromstate(L) (cast(LX *, cast(lu_byte *, (L)) - offsetof(LX, l)))
#define addbuff(b, p, e)
Typedefs
typedef struct LX LX
typedef struct LG LG
Functions
static unsigned int makeseed (lua_State *L)
void luaE_setdebt (global_State *g, l_mem debt)
CallInfo * luaE_extendCI (lua_State *L)
void luaE_freeCI (lua_State *L)
void luaE_shrinkCI (lua_State *L)
static void stack_init (lua_State *L1, lua_State *L)
static void freestack (lua_State *L)
static void init_registry (lua_State *L, global_State *g)
static void f_luaopen (lua_State *L, void *ud)
static void preinit_thread (lua_State *L, global_State *g)
static void close_state (lua_State *L)
LUA_API lua_State * lua_newthread (lua_State *L)
void luaE_freethread (lua_State *L, lua_State *L1)
LUA_API lua_State * lua_newstate (lua_Alloc f, void *ud)
LUA_API void lua_close (lua_State *L)
Macro Definition Documentation
addbuff
#define addbuff (b, p, e)
Value:
  { size_t t = cast(size_t, e); \
    memcpy(b + p, &t, sizeof(t)); p += sizeof(t); }
Definition at line 85 of file lstate.c.
Referenced by makeseed().
fromstate
#define fromstate (L) (cast(LX *, cast(lu_byte *, (L)) - offsetof(LX, l)))
Definition at line 78 of file lstate.c.
Referenced by close_state(), and luaE_freethread().
lstate_c
#define lstate_c
Definition at line 7 of file lstate.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lstate.c.
LUAI_GCMUL
#define LUAI_GCMUL 200 /* GC runs 'twice the speed' of memory allocation */
Definition at line 40 of file lstate.c.
Referenced by lua_newstate().
LUAI_GCPAUSE
#define LUAI_GCPAUSE 200 /* 200% */
Definition at line 36 of file lstate.c.
Referenced by lua_newstate().
luai_makeseed
#define luai_makeseed () cast(unsigned int, time(NULL))
Definition at line 53 of file lstate.c.
Referenced by makeseed().
Typedef Documentation
LG
typedef struct LG LG
LX
typedef struct LX LX
Function Documentation
close_state()
static void close_state (lua_State * L) static
Definition at line 250 of file lstate.c.
Referenced by lua_close(), and lua_newstate().
f_luaopen()
static void f_luaopen (lua_State * L, void * ud) static
Definition at line 211 of file lstate.c.
Referenced by lua_newstate().
freestack()
static void freestack (lua_State * L) static
Definition at line 179 of file lstate.c.
Referenced by close_state(), and luaE_freethread().
init_registry()
static void init_registry (lua_State * L, global_State * g) static
Definition at line 192 of file lstate.c.
Referenced by f_luaopen().
lua_close()
LUA_API void lua_close (lua_State * L)
Definition at line 349 of file lstate.c.
Referenced by main(), and os_exit().
lua_newstate()
LUA_API lua_State * lua_newstate (lua_Alloc f, void * ud)
Definition at line 303 of file lstate.c.
Referenced by makeseed().
lua_newthread()
LUA_API lua_State * lua_newthread (lua_State * L)
Definition at line 263 of file lstate.c.
Referenced by luaB_cocreate().
luaE_extendCI()
CallInfo * luaE_extendCI (lua_State * L)
Definition at line 116 of file lstate.c.
luaE_freeCI()
void luaE_freeCI (lua_State * L)
Definition at line 130 of file lstate.c.
Referenced by freestack(), and luaD_shrinkstack().
luaE_freethread()
void luaE_freethread (lua_State * L, lua_State * L1)
Definition at line 293 of file lstate.c.
Referenced by freeobj().
luaE_setdebt()
void luaE_setdebt (global_State * g, l_mem debt)
Definition at line 106 of file lstate.c.
Referenced by lua_gc(), luaC_step(), and setpause().
luaE_shrinkCI()
void luaE_shrinkCI (lua_State * L)
Definition at line 145 of file lstate.c.
Referenced by luaD_shrinkstack().
makeseed()
static unsigned int makeseed (lua_State * L) static
Definition at line 89 of file lstate.c.
Referenced by lua_newstate().
preinit_thread()
static void preinit_thread (lua_State * L, global_State * g) static
Definition at line 229 of file lstate.c.
Referenced by lua_newstate(), and lua_newthread().
stack_init()
static void stack_init (lua_State * L1, lua_State * L) static
Definition at line 159 of file lstate.c.
Referenced by f_luaopen(), and lua_newthread().