APM:Libraries: libraries/AP_Scripting/lua/src/lstring.c File Reference
lstring.c File Reference
#include "lprefix.h"
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
Macros
#define lstring_c
#define LUA_CORE
#define MEMERRMSG "not enough mem, increase SCR_HEAP_SIZE"
#define LUAI_HASHLIMIT 5
Functions
int luaS_eqlngstr (TString *a, TString *b)
unsigned int luaS_hash (const char *str, size_t l, unsigned int seed)
unsigned int luaS_hashlongstr (TString *ts)
void luaS_resize (lua_State *L, int newsize)
void luaS_clearcache (global_State *g)
void luaS_init (lua_State *L)
static TString * createstrobj (lua_State *L, size_t l, int tag, unsigned int h)
TString * luaS_createlngstrobj (lua_State *L, size_t l)
void luaS_remove (lua_State *L, TString *ts)
static TString * internshrstr (lua_State *L, const char *str, size_t l)
TString * luaS_newlstr (lua_State *L, const char *str, size_t l)
TString * luaS_new (lua_State *L, const char *str)
Udata * luaS_newudata (lua_State *L, size_t s)
Macro Definition Documentation
lstring_c
#define lstring_c
Definition at line 7 of file lstring.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file lstring.c.
LUAI_HASHLIMIT
#define LUAI_HASHLIMIT 5
Definition at line 33 of file lstring.c.
Referenced by luaS_hash().
MEMERRMSG
#define MEMERRMSG "not enough mem, increase SCR_HEAP_SIZE"
Definition at line 25 of file lstring.c.
Referenced by luaS_init().
Function Documentation
createstrobj()
static TString * createstrobj (lua_State * L, size_t l, int tag, unsigned int h) static
Definition at line 133 of file lstring.c.
Referenced by internshrstr(), and luaS_createlngstrobj().
internshrstr()
static TString * internshrstr (lua_State * L, const char * str, size_t l) static
Definition at line 172 of file lstring.c.
Referenced by luaS_newlstr().
luaS_clearcache()
void luaS_clearcache (global_State * g)
Definition at line 103 of file lstring.c.
Referenced by atomic().
luaS_createlngstrobj()
TString * luaS_createlngstrobj (lua_State * L, size_t l)
Definition at line 152 of file lstring.c.
Referenced by LoadString(), luaS_newlstr(), and luaV_concat().
luaS_eqlngstr()
int luaS_eqlngstr (TString * a, TString * b)
Definition at line 40 of file lstring.c.
Referenced by luaV_equalobj().
luaS_hash()
unsigned int luaS_hash (const char * str, size_t l, unsigned int seed)
Definition at line 49 of file lstring.c.
Referenced by internshrstr(), luaS_hashlongstr(), and makeseed().
luaS_hashlongstr()
unsigned int luaS_hashlongstr (TString * ts)
Definition at line 58 of file lstring.c.
Referenced by mainposition().
luaS_init()
void luaS_init (lua_State * L)
Definition at line 116 of file lstring.c.
Referenced by f_luaopen().
luaS_new()
TString * luaS_new (lua_State * L, const char * str)
Definition at line 224 of file lstring.c.
Referenced by auxgetstr(), auxsetstr(), breaklabel(), gotostat(), lua_pushlstring(), lua_pushstring(), luaT_init(), luaT_objtypename(), luaX_init(), luaY_parser(), and resume_error().
luaS_newlstr()
TString * luaS_newlstr (lua_State * L, const char * str, size_t l)
Definition at line 204 of file lstring.c.
Referenced by LoadString(), lua_concat(), lua_pushlstring(), luaO_tostring(), luaS_new(), luaV_concat(), luaX_newstring(), and pushstr().
luaS_newudata()
Udata * luaS_newudata (lua_State * L, size_t s)
Definition at line 241 of file lstring.c.
Referenced by lua_newuserdata().
luaS_remove()
void luaS_remove (lua_State * L, TString * ts)
Definition at line 159 of file lstring.c.
Referenced by freeobj().
luaS_resize()
void luaS_resize (lua_State * L, int newsize)
Definition at line 71 of file lstring.c.
Referenced by checkSizes(), internshrstr(), and luaS_init().