APM:Libraries: libraries/AP_Scripting/lua/src/lstrlib.c File Reference
lstrlib.c File Reference
#include "lprefix.h"
#include <ctype.h>
#include <float.h>
#include <limits.h>
#include <locale.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
Classes
struct MatchState
struct GMatchState
struct cD
union Ftypes
struct Header
Macros
#define lstrlib_c
#define LUA_LIB
#define LUA_MAXCAPTURES 32
#define uchar(c) ((unsigned char)(c))
#define MAX_SIZET ((size_t)(~(size_t)0))
#define MAXSIZE (sizeof(size_t) < sizeof(int) ? MAX_SIZET : (size_t)(INT_MAX))
#define CAP_UNFINISHED (-1)
#define CAP_POSITION (-2)
#define MAXCCALLS 200
#define L_ESC '%'
#define SPECIALS "^$*+?.([%-"
#define MAX_ITEM (120 + l_mathlim(MAX_10_EXP))
#define FLAGS "-+ #0"
#define MAX_FORMAT 32
#define LUAL_PACKPADBYTE 0x00
#define MAXINTSIZE 16
#define NB CHAR_BIT
#define MC ((1 << NB) - 1)
#define SZINT ((int)sizeof(lua_Integer))
#define MAXALIGN (offsetof(struct cD, u))
Typedefs
typedef struct MatchState MatchState
typedef struct GMatchState GMatchState
typedef union Ftypes Ftypes
typedef struct Header Header
typedef enum KOption KOption
Enumerations
enum KOption {
Kint , Kuint , Kfloat , Kchar ,
Kstring , Kzstr , Kpadding , Kpaddalign ,
Knop
}
Functions
static int str_len (lua_State *L)
static lua_Integer posrelat (lua_Integer pos, size_t len)
static int str_sub (lua_State *L)
static int str_reverse (lua_State *L)
static int str_lower (lua_State *L)
static int str_upper (lua_State *L)
static int str_rep (lua_State *L)
static int str_byte (lua_State *L)
static int str_char (lua_State *L)
static int writer (lua_State *L, const void *b, size_t size, void *B)
static int str_dump (lua_State *L)
static const char * match (MatchState *ms, const char *s, const char *p)
static int check_capture (MatchState *ms, int l)
static int capture_to_close (MatchState *ms)
static const char * classend (MatchState *ms, const char *p)
static int match_class (int c, int cl)
static int matchbracketclass (int c, const char *p, const char *ec)
static int singlematch (MatchState *ms, const char *s, const char *p, const char *ep)
static const char * matchbalance (MatchState *ms, const char *s, const char *p)
static const char * max_expand (MatchState *ms, const char *s, const char *p, const char *ep)
static const char * min_expand (MatchState *ms, const char *s, const char *p, const char *ep)
static const char * start_capture (MatchState *ms, const char *s, const char *p, int what)
static const char * end_capture (MatchState *ms, const char *s, const char *p)
static const char * match_capture (MatchState *ms, const char *s, int l)
static const char * lmemfind (const char *s1, size_t l1, const char *s2, size_t l2)
static void push_onecapture (MatchState *ms, int i, const char *s, const char *e)
static int push_captures (MatchState *ms, const char *s, const char *e)
static int nospecials (const char *p, size_t l)
static void prepstate (MatchState *ms, lua_State *L, const char *s, size_t ls, const char *p, size_t lp)
static void reprepstate (MatchState *ms)
static int str_find_aux (lua_State *L, int find)
static int str_find (lua_State *L)
static int str_match (lua_State *L)
static int gmatch_aux (lua_State *L)
static int gmatch (lua_State *L)
static void add_s (MatchState *ms, luaL_Buffer *b, const char *s, const char *e)
static void add_value (MatchState *ms, luaL_Buffer *b, const char *s, const char *e, int tr)
static int str_gsub (lua_State *L)
static void addquoted (luaL_Buffer *b, const char *s, size_t len)
static void checkdp (char *buff, int nb)
static void addliteral (lua_State *L, luaL_Buffer *b, int arg)
static const char * scanformat (lua_State *L, const char *strfrmt, char *form)
static void addlenmod (char *form, const char *lenmod)
static int str_format (lua_State *L)
static int digit (int c)
static int getnum (const char **fmt, int df)
static int getnumlimit (Header *h, const char **fmt, int df)
static void initheader (lua_State *L, Header *h)
static KOption getoption (Header *h, const char **fmt, int *size)
static KOption getdetails (Header *h, size_t totalsize, const char **fmt, int *psize, int *ntoalign)
static void packint (luaL_Buffer *b, lua_Unsigned n, int islittle, int size, int neg)
static void copywithendian (volatile char *dest, volatile const char *src, int size, int islittle)
static int str_pack (lua_State *L)
static int str_packsize (lua_State *L)
static lua_Integer unpackint (lua_State *L, const char *str, int islittle, int size, int issigned)
static int str_unpack (lua_State *L)
static void createmetatable (lua_State *L)
LUAMOD_API int luaopen_string (lua_State *L)
Variables
union {
int dummy
char little
} nativeendian = {1}
static const luaL_Reg strlib []
Macro Definition Documentation
CAP_POSITION
#define CAP_POSITION (-2)
Definition at line 218 of file lstrlib.c.
Referenced by match(), and push_onecapture().
CAP_UNFINISHED
#define CAP_UNFINISHED (-1)
Definition at line 217 of file lstrlib.c.
Referenced by capture_to_close(), check_capture(), end_capture(), match(), and push_onecapture().
FLAGS
#define FLAGS "-+ #0"
Definition at line 907 of file lstrlib.c.
Referenced by scanformat().
L_ESC
#define L_ESC '%'
Definition at line 245 of file lstrlib.c.
Referenced by add_s(), classend(), match(), matchbracketclass(), singlematch(), and str_format().
lstrlib_c
#define lstrlib_c
Definition at line 7 of file lstrlib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file lstrlib.c.
LUA_MAXCAPTURES
#define LUA_MAXCAPTURES 32
Definition at line 41 of file lstrlib.c.
Referenced by start_capture().
LUAL_PACKPADBYTE
#define LUAL_PACKPADBYTE 0x00
Definition at line 1114 of file lstrlib.c.
Referenced by str_pack().
MAX_FORMAT
#define MAX_FORMAT 32
Definition at line 912 of file lstrlib.c.
Referenced by str_format().
MAX_ITEM
#define MAX_ITEM (120 + l_mathlim(MAX_10_EXP))
Definition at line 903 of file lstrlib.c.
Referenced by addliteral(), and str_format().
MAX_SIZET
#define MAX_SIZET ((size_t)(~(size_t)0))
Definition at line 53 of file lstrlib.c.
MAXALIGN
#define MAXALIGN (offsetof(struct cD, u))
Definition at line 1143 of file lstrlib.c.
Referenced by getoption().
MAXCCALLS
#define MAXCCALLS 200
Definition at line 241 of file lstrlib.c.
Referenced by prepstate(), and reprepstate().
MAXINTSIZE
#define MAXINTSIZE 16
Definition at line 1118 of file lstrlib.c.
Referenced by getnumlimit().
MAXSIZE
#define MAXSIZE (sizeof(size_t) < sizeof(int) ? MAX_SIZET : (size_t)(INT_MAX))
Definition at line 55 of file lstrlib.c.
Referenced by getnum(), str_packsize(), and str_rep().
MC
#define MC ((1 << NB) - 1)
Definition at line 1124 of file lstrlib.c.
Referenced by packint(), and unpackint().
NB
#define NB CHAR_BIT
Definition at line 1121 of file lstrlib.c.
Referenced by packint(), str_pack(), and unpackint().
SPECIALS
#define SPECIALS "^$*+?.([%-"
Definition at line 246 of file lstrlib.c.
Referenced by nospecials().
SZINT
#define SZINT ((int)sizeof(lua_Integer))
Definition at line 1127 of file lstrlib.c.
Referenced by packint(), str_pack(), and unpackint().
uchar
#define uchar (c) ((unsigned char)(c))
Definition at line 46 of file lstrlib.c.
Referenced by add_s(), addquoted(), match(), matchbracketclass(), scanformat(), singlematch(), str_byte(), str_char(), str_lower(), and str_upper().
Typedef Documentation
Ftypes
typedef union Ftypes Ftypes
GMatchState
typedef struct GMatchState GMatchState
Header
typedef struct Header Header
KOption
typedef enum KOption KOption
MatchState
typedef struct MatchState MatchState
Enumeration Type Documentation
KOption
enum KOption
Enumerator
Kint
Kuint
Kfloat
Kchar
Kstring
Kzstr
Kpadding
Kpaddalign
Knop
Definition at line 1170 of file lstrlib.c.
Function Documentation
add_s()
static void add_s (MatchState * ms, luaL_Buffer * b, const char * s, const char * e) static
Definition at line 710 of file lstrlib.c.
Referenced by add_value().
add_value()
static void add_value (MatchState * ms, luaL_Buffer * b, const char * s, const char * e, int tr) static
Definition at line 738 of file lstrlib.c.
Referenced by str_gsub().
addlenmod()
static void addlenmod (char * form, const char * lenmod) static
Definition at line 1013 of file lstrlib.c.
Referenced by str_format().
addliteral()
static void addliteral (lua_State * L, luaL_Buffer * b, int arg) static
Definition at line 950 of file lstrlib.c.
Referenced by str_format().
addquoted()
static void addquoted (luaL_Buffer * b, const char * s, size_t len) static
Definition at line 915 of file lstrlib.c.
Referenced by addliteral().
capture_to_close()
static int capture_to_close (MatchState * ms) static
Definition at line 257 of file lstrlib.c.
Referenced by end_capture().
check_capture()
static int check_capture (MatchState * ms, int l) static
Definition at line 249 of file lstrlib.c.
Referenced by match_capture().
checkdp()
static void checkdp (char * buff, int nb) static
Definition at line 941 of file lstrlib.c.
Referenced by addliteral().
classend()
static const char * classend (MatchState * ms, const char * p) static
Definition at line 265 of file lstrlib.c.
Referenced by match().
copywithendian()
static void copywithendian (volatile char * dest, volatile const char * src, int size, int islittle) static
Definition at line 1323 of file lstrlib.c.
Referenced by str_pack(), and str_unpack().
createmetatable()
static void createmetatable (lua_State * L) static
Definition at line 1571 of file lstrlib.c.
Referenced by luaopen_string().
digit()
static int digit (int c) static
Definition at line 1187 of file lstrlib.c.
Referenced by b_str2int(), ftoa_engine(), getnum(), ulltoa_invert(), and ultoa_invert().
end_capture()
static const char * end_capture (MatchState * ms, const char * s, const char * p) static
Definition at line 410 of file lstrlib.c.
Referenced by match().
getdetails()
static KOption getdetails (Header * h, size_t totalsize, const char ** fmt, int * psize, int * ntoalign) static
Definition at line 1275 of file lstrlib.c.
Referenced by str_pack(), str_packsize(), and str_unpack().
getnum()
static int getnum (const char ** fmt, int df) static
Definition at line 1189 of file lstrlib.c.
Referenced by getnumlimit(), and getoption().
getnumlimit()
static int getnumlimit (Header * h, const char ** fmt, int df) static
Definition at line 1206 of file lstrlib.c.
Referenced by getoption().
getoption()
static KOption getoption (Header * h, const char ** fmt, int * size) static
Definition at line 1228 of file lstrlib.c.
Referenced by getdetails().
gmatch()
static int gmatch (lua_State * L) static
Definition at line 696 of file lstrlib.c.
gmatch_aux()
static int gmatch_aux (lua_State * L) static
Definition at line 680 of file lstrlib.c.
Referenced by gmatch().
initheader()
static void initheader (lua_State * L, Header * h) static
Definition at line 1218 of file lstrlib.c.
Referenced by str_pack(), str_packsize(), and str_unpack().
lmemfind()
static const char * lmemfind (const char * s1, size_t l1, const char * s2, size_t l2) static
Definition at line 535 of file lstrlib.c.
Referenced by str_find_aux().
luaopen_string()
LUAMOD_API int luaopen_string (lua_State * L)
Definition at line 1586 of file lstrlib.c.
match()
static const char * match (MatchState * ms, const char * s, const char * p) static
Definition at line 432 of file lstrlib.c.
Referenced by end_capture(), gmatch_aux(), match(), max_expand(), min_expand(), start_capture(), str_find_aux(), and str_gsub().
match_capture()
static const char * match_capture (MatchState * ms, const char * s, int l) static
Definition at line 421 of file lstrlib.c.
Referenced by match().
match_class()
static int match_class (int c, int cl) static
Definition at line 289 of file lstrlib.c.
Referenced by matchbracketclass(), and singlematch().
matchbalance()
static const char * matchbalance (MatchState * ms, const char * s, const char * p) static
Definition at line 348 of file lstrlib.c.
Referenced by match().
matchbracketclass()
static int matchbracketclass (int c, const char * p, const char * ec) static
Definition at line 309 of file lstrlib.c.
Referenced by match(), and singlematch().
max_expand()
static const char * max_expand (MatchState * ms, const char * s, const char * p, const char * ep) static
Definition at line 368 of file lstrlib.c.
Referenced by match().
min_expand()
static const char * min_expand (MatchState * ms, const char * s, const char * p, const char * ep) static
Definition at line 383 of file lstrlib.c.
Referenced by match().
nospecials()
static int nospecials (const char * p, size_t l) static
Definition at line 587 of file lstrlib.c.
Referenced by str_find_aux().
packint()
static void packint (luaL_Buffer * b, lua_Unsigned n, int islittle, int size, int neg) static
Definition at line 1302 of file lstrlib.c.
Referenced by str_pack().
posrelat()
static lua_Integer posrelat (lua_Integer pos, size_t len) static
Definition at line 70 of file lstrlib.c.
Referenced by str_byte(), str_find_aux(), str_sub(), and str_unpack().
prepstate()
static void prepstate (MatchState * ms, lua_State * L, const char * s, size_t ls, const char * p, size_t lp) static
Definition at line 598 of file lstrlib.c.
Referenced by gmatch(), str_find_aux(), and str_gsub().
push_captures()
static int push_captures (MatchState * ms, const char * s, const char * e) static
Definition at line 576 of file lstrlib.c.
Referenced by add_value(), gmatch_aux(), and str_find_aux().
push_onecapture()
static void push_onecapture (MatchState * ms, int i, const char * s, const char * e) static
Definition at line 557 of file lstrlib.c.
Referenced by add_s(), add_value(), and push_captures().
reprepstate()
static void reprepstate (MatchState * ms) static
Definition at line 608 of file lstrlib.c.
Referenced by gmatch_aux(), str_find_aux(), and str_gsub().
scanformat()
static const char * scanformat (lua_State * L, const char * strfrmt, char * form) static
Definition at line 988 of file lstrlib.c.
Referenced by str_format().
singlematch()
static int singlematch (MatchState * ms, const char * s, const char * p, const char * ep) static
Definition at line 332 of file lstrlib.c.
Referenced by match(), max_expand(), and min_expand().
start_capture()
static const char * start_capture (MatchState * ms, const char * s, const char * p, int what) static
Definition at line 396 of file lstrlib.c.
Referenced by match().
str_byte()
static int str_byte (lua_State * L) static
Definition at line 155 of file lstrlib.c.
str_char()
static int str_char (lua_State * L) static
Definition at line 174 of file lstrlib.c.
str_dump()
static int str_dump (lua_State * L) static
Definition at line 196 of file lstrlib.c.
str_find()
static int str_find (lua_State * L) static
Definition at line 661 of file lstrlib.c.
str_find_aux()
static int str_find_aux (lua_State * L, int find) static
Definition at line 614 of file lstrlib.c.
Referenced by str_find(), and str_match().
str_format()
static int str_format (lua_State * L) static
Definition at line 1023 of file lstrlib.c.
str_gsub()
static int str_gsub (lua_State * L) static
Definition at line 769 of file lstrlib.c.
str_len()
static int str_len (lua_State * L) static
Definition at line 61 of file lstrlib.c.
str_lower()
static int str_lower (lua_State * L) static
Definition at line 103 of file lstrlib.c.
str_match()
static int str_match (lua_State * L) static
Definition at line 666 of file lstrlib.c.
str_pack()
static int str_pack (lua_State * L) static
Definition at line 1337 of file lstrlib.c.
str_packsize()
static int str_packsize (lua_State * L) static
Definition at line 1424 of file lstrlib.c.
str_rep()
static int str_rep (lua_State * L) static
Definition at line 129 of file lstrlib.c.
str_reverse()
static int str_reverse (lua_State * L) static
Definition at line 91 of file lstrlib.c.
str_sub()
static int str_sub (lua_State * L) static
Definition at line 77 of file lstrlib.c.
str_unpack()
static int str_unpack (lua_State * L) static
Definition at line 1483 of file lstrlib.c.
str_upper()
static int str_upper (lua_State * L) static
Definition at line 116 of file lstrlib.c.
unpackint()
static lua_Integer unpackint (lua_State * L, const char * str, int islittle, int size, int issigned) static
Definition at line 1457 of file lstrlib.c.
Referenced by str_unpack().
writer()
static int writer (lua_State * L, const void * b, size_t size, void * B) static
Definition at line 189 of file lstrlib.c.
Referenced by AP_Logger_Backend::AP_Logger_Backend(), lua_dump(), AP_Logger::setVehicle_Startup_Writer(), and str_dump().
Variable Documentation
dummy
int dummy
Definition at line 1132 of file lstrlib.c.
Referenced by luaT_trybinTM().
little
char little
Definition at line 1133 of file lstrlib.c.
[union]
const union { ... } nativeendian
Referenced by copywithendian(), getoption(), and initheader().
strlib
const luaL_Reg strlib[] static
Initial value:
= {
  {"byte", str_byte},
  {"char", str_char},
  {"find", str_find},
  {"format", str_format},
  {"gmatch", gmatch},
  {"gsub", str_gsub},
  {"len", str_len},
  {"lower", str_lower},
  {"match", str_match},
  {"rep", str_rep},
  {"reverse", str_reverse},
  {"sub", str_sub},
  {"upper", str_upper},
  {"pack", str_pack},
  {"packsize", str_packsize},
  {"unpack", str_unpack},
  {NULL, NULL}
}
Definition at line 1549 of file lstrlib.c.
Referenced by luaopen_string().