APM:Libraries: libraries/AP_Scripting/lua/src/ltable.c File Reference
ltable.c File Reference
#include "lprefix.h"
#include <math.h>
#include <limits.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lgc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstate.h"
#include "lstring.h"
#include "ltable.h"
#include "lvm.h"
Classes
struct AuxsetnodeT
Macros
#define ltable_c
#define LUA_CORE
#define MAXABITS cast_int(sizeof(int) * CHAR_BIT - 1)
#define MAXASIZE (1u << MAXABITS)
#define MAXHBITS (MAXABITS - 1)
#define hashpow2(t, n) (gnode(t, lmod((n), sizenode(t))))
#define hashstr(t, str) hashpow2(t, (str)->hash)
#define hashboolean(t, p) hashpow2(t, p)
#define hashint(t, i) hashpow2(t, i)
#define hashmod(t, n) (gnode(t, ((n) % ((sizenode(t)-1)|1))))
#define hashpointer(t, p) hashmod(t, point2uint(p))
#define dummynode (&dummynode_)
Functions
static int l_hashfloat (lua_Number n)
static Node * mainposition (const Table *t, const TValue *key)
static unsigned int arrayindex (const TValue *key)
static unsigned int findindex (lua_State *L, Table *t, StkId key)
int luaH_next (lua_State *L, Table *t, StkId key)
static unsigned int computesizes (unsigned int nums[], unsigned int *pna)
static int countint (const TValue *key, unsigned int *nums)
static unsigned int numusearray (const Table *t, unsigned int *nums)
static int numusehash (const Table *t, unsigned int *nums, unsigned int *pna)
static void setarrayvector (lua_State *L, Table *t, unsigned int size)
static void setnodevector (lua_State *L, Table *t, unsigned int size)
static void auxsetnode (lua_State *L, void *ud)
void luaH_resize (lua_State *L, Table *t, unsigned int nasize, unsigned int nhsize)
void luaH_resizearray (lua_State *L, Table *t, unsigned int nasize)
static void rehash (lua_State *L, Table *t, const TValue *ek)
Table * luaH_new (lua_State *L)
void luaH_free (lua_State *L, Table *t)
static Node * getfreepos (Table *t)
TValue * luaH_newkey (lua_State *L, Table *t, const TValue *key)
const TValue * luaH_getint (Table *t, lua_Integer key)
const TValue * luaH_getshortstr (Table *t, TString *key)
static const TValue * getgeneric (Table *t, const TValue *key)
const TValue * luaH_getstr (Table *t, TString *key)
const TValue * luaH_get (Table *t, const TValue *key)
TValue * luaH_set (lua_State *L, Table *t, const TValue *key)
void luaH_setint (lua_State *L, Table *t, lua_Integer key, TValue *value)
static lua_Unsigned unbound_search (Table *t, lua_Unsigned j)
lua_Unsigned luaH_getn (Table *t)
Variables
static const Node dummynode_
Macro Definition Documentation
dummynode
#define dummynode (&dummynode_)
Definition at line 82 of file ltable.c.
Referenced by setnodevector().
hashboolean
#define hashboolean (t, p) hashpow2(t, p)
Definition at line 68 of file ltable.c.
Referenced by mainposition().
hashint
#define hashint (t, i) hashpow2(t, i)
Definition at line 69 of file ltable.c.
Referenced by luaH_getint(), and mainposition().
hashmod
#define hashmod (t, n) (gnode(t, ((n) % ((sizenode(t)-1)|1))))
Definition at line 76 of file ltable.c.
Referenced by mainposition().
hashpointer
#define hashpointer (t, p) hashmod(t, point2uint(p))
Definition at line 79 of file ltable.c.
Referenced by mainposition().
hashpow2
#define hashpow2 (t, n) (gnode(t, lmod((n), sizenode(t))))
Definition at line 65 of file ltable.c.
Referenced by mainposition().
hashstr
#define hashstr (t, str) hashpow2(t, (str)->hash)
Definition at line 67 of file ltable.c.
Referenced by luaH_getshortstr(), and mainposition().
ltable_c
#define ltable_c
Definition at line 7 of file ltable.c.
LUA_CORE
#define LUA_CORE
Definition at line 8 of file ltable.c.
MAXABITS
#define MAXABITS cast_int(sizeof(int) * CHAR_BIT - 1)
Definition at line 53 of file ltable.c.
Referenced by numusearray(), and rehash().
MAXASIZE
#define MAXASIZE (1u << MAXABITS)
Definition at line 54 of file ltable.c.
Referenced by arrayindex().
MAXHBITS
#define MAXHBITS (MAXABITS - 1)
Definition at line 62 of file ltable.c.
Referenced by setnodevector().
Function Documentation
arrayindex()
static unsigned int arrayindex (const TValue * key) static
Definition at line 151 of file ltable.c.
Referenced by countint(), and findindex().
auxsetnode()
static void auxsetnode (lua_State * L, void * ud) static
Definition at line 348 of file ltable.c.
Referenced by luaH_resize().
computesizes()
static unsigned int computesizes (unsigned int nums[], unsigned int * pna) static
Definition at line 226 of file ltable.c.
Referenced by rehash().
countint()
static int countint (const TValue * key, unsigned int * nums) static
Definition at line 250 of file ltable.c.
Referenced by numusehash(), and rehash().
findindex()
static unsigned int findindex (lua_State * L, Table * t, StkId key) static
Definition at line 166 of file ltable.c.
Referenced by luaH_next().
getfreepos()
static Node * getfreepos (Table * t) static
Definition at line 448 of file ltable.c.
Referenced by luaH_newkey().
getgeneric()
static const TValue * getgeneric (Table * t, const TValue * key) static
Definition at line 567 of file ltable.c.
Referenced by luaH_get(), and luaH_getstr().
l_hashfloat()
static int l_hashfloat (lua_Number n) static
Definition at line 104 of file ltable.c.
Referenced by mainposition().
luaH_free()
void luaH_free (lua_State * L, Table * t)
Definition at line 440 of file ltable.c.
Referenced by freeobj().
luaH_get()
const TValue * luaH_get (Table * t, const TValue * key)
Definition at line 596 of file ltable.c.
Referenced by lua_rawget(), lua_rawgetp(), luaH_set(), luaV_finishget(), and luaV_finishset().
luaH_getint()
const TValue * luaH_getint (Table * t, lua_Integer key)
Definition at line 523 of file ltable.c.
Referenced by lua_getglobal(), lua_geti(), lua_load(), lua_rawgeti(), lua_setglobal(), lua_seti(), luaH_get(), luaH_setint(), and unbound_search().
luaH_getn()
lua_Unsigned luaH_getn (Table * t)
Definition at line 667 of file ltable.c.
Referenced by lua_rawlen(), and luaV_objlen().
luaH_getshortstr()
const TValue * luaH_getshortstr (Table * t, TString * key)
Definition at line 546 of file ltable.c.
Referenced by luaH_get(), luaH_getstr(), luaT_gettm(), luaT_gettmbyobj(), and luaT_objtypename().
luaH_getstr()
const TValue * luaH_getstr (Table * t, TString * key)
Definition at line 582 of file ltable.c.
Referenced by auxgetstr(), auxsetstr(), and luaV_execute().
luaH_new()
Table * luaH_new (lua_State * L)
Definition at line 428 of file ltable.c.
Referenced by collectvalidlines(), init_registry(), lua_createtable(), luaV_execute(), and luaY_parser().
luaH_newkey()
TValue * luaH_newkey (lua_State * L, Table * t, const TValue * key)
Definition at line 468 of file ltable.c.
Referenced by luaH_set(), luaH_setint(), and luaV_finishset().
luaH_next()
int luaH_next (lua_State * L, Table * t, StkId key)
Definition at line 193 of file ltable.c.
Referenced by lua_next().
luaH_resize()
void luaH_resize (lua_State * L, Table * t, unsigned int nasize, unsigned int nhsize)
Definition at line 354 of file ltable.c.
Referenced by init_registry(), lua_createtable(), luaH_resizearray(), luaV_execute(), and rehash().
luaH_resizearray()
void luaH_resizearray (lua_State * L, Table * t, unsigned int nasize)
Definition at line 394 of file ltable.c.
Referenced by luaV_execute().
luaH_set()
TValue * luaH_set (lua_State * L, Table * t, const TValue * key)
Definition at line 617 of file ltable.c.
Referenced by addk(), lua_rawset(), lua_rawsetp(), luaH_newkey(), luaH_resize(), and luaX_newstring().
luaH_setint()
void luaH_setint (lua_State * L, Table * t, lua_Integer key, TValue * value)
Definition at line 625 of file ltable.c.
Referenced by collectvalidlines(), init_registry(), lua_rawseti(), luaH_resize(), and luaV_execute().
mainposition()
static Node * mainposition (const Table * t, const TValue * key) static
Definition at line 124 of file ltable.c.
Referenced by findindex(), getgeneric(), and luaH_newkey().
numusearray()
static unsigned int numusearray (const Table * t, unsigned int * nums) static
Definition at line 266 of file ltable.c.
Referenced by rehash().
numusehash()
static int numusehash (const Table * t, unsigned int * nums, unsigned int * pna) static
Definition at line 292 of file ltable.c.
Referenced by rehash().
rehash()
static void rehash (lua_State * L, Table * t, const TValue * ek) static
Definition at line 402 of file ltable.c.
Referenced by luaH_newkey().
setarrayvector()
static void setarrayvector (lua_State * L, Table * t, unsigned int size) static
Definition at line 308 of file ltable.c.
Referenced by luaH_resize().
setnodevector()
static void setnodevector (lua_State * L, Table * t, unsigned int size) static
Definition at line 317 of file ltable.c.
Referenced by auxsetnode(), and luaH_new().
unbound_search()
static lua_Unsigned unbound_search (Table * t, lua_Unsigned j) static
Definition at line 639 of file ltable.c.
Referenced by luaH_getn().
Variable Documentation
dummynode_
const Node dummynode_ static
Initial value:
= {
  {NILCONSTANT},
  {{NILCONSTANT, 0}}
}
Definition at line 84 of file ltable.c.