APM:Libraries: libraries/AP_Scripting/lua/src/ltablib.c File Reference
ltablib.c File Reference
#include "lprefix.h"
#include <limits.h>
#include <stddef.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
#include <time.h>
Macros
#define ltablib_c
#define LUA_LIB
#define TAB_R 1 /* read */
#define TAB_W 2 /* write */
#define TAB_L 4 /* length */
#define TAB_RW (TAB_R | TAB_W) /* read/write */
#define aux_getn(L, n, w) (checktab(L, n, (w) | TAB_L), luaL_len(L, n))
#define sof(e) (sizeof(e) / sizeof(unsigned int))
#define RANLIMIT 100u
Typedefs
typedef unsigned int IdxT
Functions
static int checkfield (lua_State *L, const char *key, int n)
static void checktab (lua_State *L, int arg, int what)
static int tinsert (lua_State *L)
static int tremove (lua_State *L)
static int tmove (lua_State *L)
static void addfield (lua_State *L, luaL_Buffer *b, lua_Integer i)
static int tconcat (lua_State *L)
static int pack (lua_State *L)
static int unpack (lua_State *L)
static unsigned int l_randomizePivot (void)
static void set2 (lua_State *L, IdxT i, IdxT j)
static int sort_comp (lua_State *L, int a, int b)
static IdxT partition (lua_State *L, IdxT lo, IdxT up)
static IdxT choosePivot (IdxT lo, IdxT up, unsigned int rnd)
static void auxsort (lua_State *L, IdxT lo, IdxT up, unsigned int rnd)
static int sort (lua_State *L)
LUAMOD_API int luaopen_table (lua_State *L)
Variables
static const luaL_Reg tab_funcs []
Macro Definition Documentation
aux_getn
#define aux_getn (L, n, w) (checktab(L, n, (w) | TAB_L), luaL_len(L, n))
Definition at line 33 of file ltablib.c.
Referenced by sort(), tconcat(), tinsert(), and tremove().
ltablib_c
#define ltablib_c
Definition at line 7 of file ltablib.c.
LUA_LIB
#define LUA_LIB
Definition at line 8 of file ltablib.c.
RANLIMIT
#define RANLIMIT 100u
Definition at line 278 of file ltablib.c.
Referenced by auxsort().
sof
#define sof (e) (sizeof(e) / sizeof(unsigned int))
Definition at line 250 of file ltablib.c.
Referenced by l_randomizePivot().
TAB_L
#define TAB_L 4 /* length */
Definition at line 29 of file ltablib.c.
Referenced by checktab().
TAB_R
#define TAB_R 1 /* read */
Definition at line 27 of file ltablib.c.
Referenced by checktab(), tconcat(), and tmove().
TAB_RW
#define TAB_RW (TAB_R | TAB_W) /* read/write */
Definition at line 30 of file ltablib.c.
Referenced by sort(), tinsert(), and tremove().
TAB_W
#define TAB_W 2 /* write */
Definition at line 28 of file ltablib.c.
Referenced by checktab(), and tmove().
Typedef Documentation
IdxT
typedef unsigned int IdxT
Definition at line 236 of file ltablib.c.
Function Documentation
addfield()
static void addfield (lua_State * L, luaL_Buffer * b, lua_Integer i) static
Definition at line 160 of file ltablib.c.
Referenced by tconcat().
auxsort()
static void auxsort (lua_State * L, IdxT lo, IdxT up, unsigned int rnd) static
Definition at line 361 of file ltablib.c.
Referenced by auxsort(), and sort().
checkfield()
static int checkfield (lua_State * L, const char * key, int n) static
Definition at line 36 of file ltablib.c.
Referenced by checktab().
checktab()
static void checktab (lua_State * L, int arg, int what) static
Definition at line 46 of file ltablib.c.
Referenced by tmove().
choosePivot()
static IdxT choosePivot (IdxT lo, IdxT up, unsigned int rnd) static
Definition at line 350 of file ltablib.c.
Referenced by auxsort().
l_randomizePivot()
static unsigned int l_randomizePivot (void) static
Definition at line 258 of file ltablib.c.
Referenced by auxsort().
luaopen_table()
LUAMOD_API int luaopen_table (lua_State * L)
Definition at line 445 of file ltablib.c.
pack()
static int pack (lua_State * L) static
Definition at line 194 of file ltablib.c.
partition()
static IdxT partition (lua_State * L, IdxT lo, IdxT up) static
Definition at line 314 of file ltablib.c.
Referenced by auxsort().
set2()
static void set2 (lua_State * L, IdxT i, IdxT j) static
Definition at line 281 of file ltablib.c.
Referenced by auxsort(), and partition().
sort()
static int sort (lua_State * L) static
Definition at line 415 of file ltablib.c.
sort_comp()
static int sort_comp (lua_State * L, int a, int b) static
Definition at line 291 of file ltablib.c.
Referenced by auxsort(), and partition().
tconcat()
static int tconcat (lua_State * L) static
Definition at line 169 of file ltablib.c.
tinsert()
static int tinsert (lua_State * L) static
Definition at line 79 of file ltablib.c.
tmove()
static int tmove (lua_State * L) static
Definition at line 128 of file ltablib.c.
tremove()
static int tremove (lua_State * L) static
Definition at line 106 of file ltablib.c.
unpack()
static int unpack (lua_State * L) static
Definition at line 207 of file ltablib.c.
Variable Documentation
tab_funcs
const luaL_Reg tab_funcs[] static
Initial value:
= {
  {"concat", tconcat},
  {"insert", tinsert},
  {"pack", pack},
  {"unpack", unpack},
  {"remove", tremove},
  {"move", tmove},
  {"sort", sort},
  {NULL, NULL}
}
Definition at line 430 of file ltablib.c.
Referenced by luaopen_table().