APM:Libraries: libraries/AP_Scripting/lua/src/ltm.h File Reference
ltm.h File Reference
#include "lobject.h"
Macros
#define gfasttm(g, et, e)
#define fasttm(l, et, e) gfasttm(G(l), et, e)
#define ttypename(x) luaT_typenames_[(x) + 1]
Enumerations
enum TMS {
TM_INDEX , TM_NEWINDEX , TM_GC , TM_MODE ,
TM_LEN , TM_EQ , TM_ADD , TM_SUB ,
TM_MUL , TM_MOD , TM_POW , TM_DIV ,
TM_IDIV , TM_BAND , TM_BOR , TM_BXOR ,
TM_SHL , TM_SHR , TM_UNM , TM_BNOT ,
TM_LT , TM_LE , TM_CONCAT , TM_CALL ,
TM_N
}
Functions
LUAI_FUNC const char * luaT_objtypename (lua_State *L, const TValue *o)
LUAI_FUNC const TValue * luaT_gettm (Table *events, TMS event, TString *ename)
LUAI_FUNC const TValue * luaT_gettmbyobj (lua_State *L, const TValue *o, TMS event)
LUAI_FUNC void luaT_init (lua_State *L)
LUAI_FUNC void luaT_callTM (lua_State *L, const TValue *f, const TValue *p1, const TValue *p2, TValue *p3, int hasres)
LUAI_FUNC int luaT_callbinTM (lua_State *L, const TValue *p1, const TValue *p2, StkId res, TMS event)
LUAI_FUNC void luaT_trybinTM (lua_State *L, const TValue *p1, const TValue *p2, StkId res, TMS event)
LUAI_FUNC int luaT_callorderTM (lua_State *L, const TValue *p1, const TValue *p2, TMS event)
Variables
LUAI_DDEC const char *const luaT_typenames_ [LUA_TOTALTAGS]
Macro Definition Documentation
fasttm
#define fasttm (l, et, e) gfasttm(G(l), et, e)
Definition at line 51 of file ltm.h.
Referenced by luaV_equalobj(), luaV_finishget(), luaV_finishset(), and luaV_objlen().
gfasttm
#define gfasttm (g, et, e)
Value:
  ((et) == NULL ? NULL : \
  ((et)->flags & (1u<<(e))) ? NULL : luaT_gettm(et, e, (g)->tmname[e]))
Definition at line 48 of file ltm.h.
Referenced by luaC_checkfinalizer(), and traversetable().
ttypename
#define ttypename (x) luaT_typenames_[(x) + 1]
Definition at line 53 of file ltm.h.
Referenced by lua_typename(), and luaT_objtypename().
Enumeration Type Documentation
TMS
enum TMS
Enumerator
TM_INDEX
TM_NEWINDEX
TM_GC
TM_MODE
TM_LEN
TM_EQ
TM_ADD
TM_SUB
TM_MUL
TM_MOD
TM_POW
TM_DIV
TM_IDIV
TM_BAND
TM_BOR
TM_BXOR
TM_SHL
TM_SHR
TM_UNM
TM_BNOT
TM_LT
TM_LE
TM_CONCAT
TM_CALL
TM_N
Definition at line 18 of file ltm.h.
Function Documentation
luaT_callbinTM()
LUAI_FUNC int luaT_callbinTM (lua_State * L, const TValue * p1, const TValue * p2, StkId res, TMS event)
Definition at line 126 of file ltm.c.
Referenced by luaT_callorderTM(), and luaT_trybinTM().
luaT_callorderTM()
LUAI_FUNC int luaT_callorderTM (lua_State * L, const TValue * p1, const TValue * p2, TMS event)
Definition at line 160 of file ltm.c.
Referenced by luaV_lessequal(), and luaV_lessthan().
luaT_callTM()
LUAI_FUNC void luaT_callTM (lua_State * L, const TValue * f, const TValue * p1, const TValue * p2, TValue * p3, int hasres)
Definition at line 104 of file ltm.c.
Referenced by luaT_callbinTM(), luaV_equalobj(), luaV_finishget(), luaV_finishset(), and luaV_objlen().
luaT_gettm()
LUAI_FUNC const TValue * luaT_gettm (Table * events, TMS event, TString * ename)
Definition at line 61 of file ltm.c.
luaT_gettmbyobj()
LUAI_FUNC const TValue * luaT_gettmbyobj (lua_State * L, const TValue * o, TMS event)
Definition at line 72 of file ltm.c.
Referenced by GCTM(), luaT_callbinTM(), luaV_finishget(), luaV_finishset(), luaV_objlen(), and tryfuncTM().
luaT_init()
LUAI_FUNC void luaT_init (lua_State * L)
Definition at line 39 of file ltm.c.
Referenced by f_luaopen().
luaT_objtypename()
LUAI_FUNC const char * luaT_objtypename (lua_State * L, const TValue * o)
Definition at line 92 of file ltm.c.
Referenced by luaG_ordererror(), and luaG_typeerror().
luaT_trybinTM()
LUAI_FUNC void luaT_trybinTM (lua_State * L, const TValue * p1, const TValue * p2, StkId res, TMS event)
Definition at line 137 of file ltm.c.
Referenced by luaO_arith(), luaV_concat(), and luaV_execute().
Variable Documentation
luaT_typenames_
LUAI_DDEC const char* const luaT_typenames_[LUA_TOTALTAGS]
Definition at line 55 of file ltm.h.