APM:Libraries: libraries/AP_Scripting/lua_common_defs.h File Reference
lua_common_defs.h File Reference
#include <AP_HAL/AP_HAL_Boards.h>
Macros
#define REPL_DIRECTORY "./repl"
#define SCRIPTING_DIRECTORY "./scripts"
#define REPL_IN REPL_DIRECTORY "/in"
#define REPL_OUT REPL_DIRECTORY "/out"
Functions
int lua_get_current_ref ()
const char * lua_get_modules_path ()
void lua_abort (void) __attribute__((noreturn))
Macro Definition Documentation
REPL_DIRECTORY
#define REPL_DIRECTORY "./repl"
Definition at line 9 of file lua_common_defs.h.
REPL_IN
#define REPL_IN REPL_DIRECTORY "/in"
Definition at line 22 of file lua_common_defs.h.
REPL_OUT
#define REPL_OUT REPL_DIRECTORY "/out"
Definition at line 26 of file lua_common_defs.h.
SCRIPTING_DIRECTORY
#define SCRIPTING_DIRECTORY "./scripts"
Definition at line 17 of file lua_common_defs.h.
Function Documentation
lua_abort()
void lua_abort (void)
Referenced by luaD_throw().
lua_get_current_ref()
int lua_get_current_ref ()
Referenced by ll_require().
lua_get_modules_path()
const char * lua_get_modules_path ()
Referenced by luaopen_package().