APM:Libraries: libraries/AP_Scripting/lua/src/lundump.c File Reference
lundump.c File Reference
#include "lprefix.h"
#include <string.h>
#include "lua.h"
#include "ldebug.h"
#include "ldo.h"
#include "lfunc.h"
#include "lmem.h"
#include "lobject.h"
#include "lstring.h"
#include "lundump.h"
#include "lzio.h"
Classes
struct LoadState
Macros
#define lundump_c
#define LUA_CORE
#define luai_verifycode(L, b, f) /* empty */
#define LoadVector(S, b, n) LoadBlock(S,b,(n)*sizeof((b)[0]))
#define LoadVar(S, x) LoadVector(S,&x,1)
#define checksize(S, t) fchecksize(S,sizeof(t),#t)
Functions
static l_noret error (LoadState *S, const char *why)
static void LoadBlock (LoadState *S, void *b, size_t size)
static lu_byte LoadByte (LoadState *S)
static int LoadInt (LoadState *S)
static lua_Number LoadNumber (LoadState *S)
static lua_Integer LoadInteger (LoadState *S)
static TString * LoadString (LoadState *S)
static void LoadCode (LoadState *S, Proto *f)
static void LoadFunction (LoadState *S, Proto *f, TString *psource)
static void LoadConstants (LoadState *S, Proto *f)
static void LoadProtos (LoadState *S, Proto *f)
static void LoadUpvalues (LoadState *S, Proto *f)
static void LoadDebug (LoadState *S, Proto *f)
static void checkliteral (LoadState *S, const char *s, const char *msg)
static void fchecksize (LoadState *S, size_t size, const char *tname)
static void checkHeader (LoadState *S)
LClosure * luaU_undump (lua_State *L, ZIO *Z, const char *name)
Macro Definition Documentation
checksize
#define checksize (S, t) fchecksize(S,sizeof(t),#t)
Definition at line 241 of file lundump.c.
Referenced by checkHeader().
LoadVar
#define LoadVar (S, x) LoadVector(S,&x,1)
Definition at line 64 of file lundump.c.
Referenced by LoadByte(), LoadInt(), LoadInteger(), LoadNumber(), and LoadString().
LoadVector
#define LoadVector (S, b, n) LoadBlock(S,b,(n)*sizeof((b)[0]))
Definition at line 56 of file lundump.c.
Referenced by checkliteral(), LoadCode(), LoadDebug(), and LoadString().
LUA_CORE
#define LUA_CORE
Definition at line 15 of file lundump.c.
luai_verifycode
#define luai_verifycode (L, b, f) /* empty */
Definition at line 35 of file lundump.c.
Referenced by luaU_undump().
lundump_c
#define lundump_c
Definition at line 14 of file lundump.c.
Function Documentation
checkHeader()
static void checkHeader (LoadState * S) static
Definition at line 243 of file lundump.c.
Referenced by luaU_undump().
checkliteral()
static void checkliteral (LoadState * S, const char * s, const char * msg) static
Definition at line 226 of file lundump.c.
Referenced by checkHeader().
error()
static l_noret error (LoadState * S, const char * why) static
Definition at line 46 of file lundump.c.
fchecksize()
static void fchecksize (LoadState * S, size_t size, const char * tname) static
Definition at line 235 of file lundump.c.
LoadBlock()
static void LoadBlock (LoadState * S, void * b, size_t size) static
Definition at line 58 of file lundump.c.
LoadByte()
static lu_byte LoadByte (LoadState * S) static
Definition at line 67 of file lundump.c.
Referenced by checkHeader(), fchecksize(), LoadConstants(), LoadFunction(), LoadString(), LoadUpvalues(), and luaU_undump().
LoadCode()
static void LoadCode (LoadState * S, Proto * f) static
Definition at line 114 of file lundump.c.
Referenced by LoadFunction().
LoadConstants()
static void LoadConstants (LoadState * S, Proto * f) static
Definition at line 125 of file lundump.c.
Referenced by LoadFunction().
LoadDebug()
static void LoadDebug (LoadState * S, Proto * f) static
Definition at line 187 of file lundump.c.
Referenced by LoadFunction().
LoadFunction()
static void LoadFunction (LoadState * S, Proto * f, TString * psource) static
Definition at line 209 of file lundump.c.
Referenced by LoadProtos(), and luaU_undump().
LoadInt()
static int LoadInt (LoadState * S) static
Definition at line 74 of file lundump.c.
Referenced by LoadCode(), LoadConstants(), LoadDebug(), LoadFunction(), LoadProtos(), and LoadUpvalues().
LoadInteger()
static lua_Integer LoadInteger (LoadState * S) static
Definition at line 88 of file lundump.c.
Referenced by checkHeader(), and LoadConstants().
LoadNumber()
static lua_Number LoadNumber (LoadState * S) static
Definition at line 81 of file lundump.c.
Referenced by checkHeader(), and LoadConstants().
LoadProtos()
static void LoadProtos (LoadState * S, Proto * f) static
Definition at line 159 of file lundump.c.
Referenced by LoadFunction().
LoadString()
static TString * LoadString (LoadState * S) static
Definition at line 95 of file lundump.c.
Referenced by LoadConstants(), LoadDebug(), and LoadFunction().
LoadUpvalues()
static void LoadUpvalues (LoadState * S, Proto * f) static
Definition at line 173 of file lundump.c.
Referenced by LoadFunction().
luaU_undump()
LClosure * luaU_undump (lua_State * L, ZIO * Z, const char * name)
Definition at line 265 of file lundump.c.
Referenced by f_parser().