APM:Libraries: libraries/AP_Scripting/lua/src/lvm.h File Reference
lvm.h File Reference
#include "ldo.h"
#include "lobject.h"
#include "ltm.h"
Macros
#define cvt2str(o) ttisnumber(o)
#define cvt2num(o) ttisstring(o)
#define LUA_FLOORN2I 0
#define tonumber(o, n) (ttisfloat(o) ? (*(n) = fltvalue(o), 1) : luaV_tonumber_(o,n))
#define tointeger(o, i) (ttisinteger(o) ? (*(i) = ivalue(o), 1) : luaV_tointeger(o,i,LUA_FLOORN2I))
#define intop(op, v1, v2) l_castU2S(l_castS2U(v1) op l_castS2U(v2))
#define luaV_rawequalobj(t1, t2) luaV_equalobj(NULL,t1,t2)
#define luaV_fastget(L, t, k, slot, f)
#define luaV_gettable(L, t, k, v)
#define luaV_fastset(L, t, k, slot, f, v)
#define luaV_settable(L, t, k, v)
Functions
LUAI_FUNC int luaV_equalobj (lua_State *L, const TValue *t1, const TValue *t2)
LUAI_FUNC int luaV_lessthan (lua_State *L, const TValue *l, const TValue *r)
LUAI_FUNC int luaV_lessequal (lua_State *L, const TValue *l, const TValue *r)
LUAI_FUNC int luaV_tonumber_ (const TValue *obj, lua_Number *n)
LUAI_FUNC int luaV_tointeger (const TValue *obj, lua_Integer *p, int mode)
LUAI_FUNC void luaV_finishget (lua_State *L, const TValue *t, TValue *key, StkId val, const TValue *slot)
LUAI_FUNC void luaV_finishset (lua_State *L, const TValue *t, TValue *key, StkId val, const TValue *slot)
LUAI_FUNC void luaV_finishOp (lua_State *L)
LUAI_FUNC void luaV_execute (lua_State *L)
LUAI_FUNC void luaV_concat (lua_State *L, int total)
LUAI_FUNC lua_Integer luaV_div (lua_State *L, lua_Integer x, lua_Integer y)
LUAI_FUNC lua_Integer luaV_mod (lua_State *L, lua_Integer x, lua_Integer y)
LUAI_FUNC lua_Integer luaV_shiftl (lua_Integer x, lua_Integer y)
LUAI_FUNC void luaV_objlen (lua_State *L, StkId ra, const TValue *rb)
Macro Definition Documentation
cvt2num
#define cvt2num (o) ttisstring(o)
Definition at line 24 of file lvm.h.
Referenced by luaV_tointeger(), and luaV_tonumber_().
cvt2str
#define cvt2str (o) ttisnumber(o)
Definition at line 17 of file lvm.h.
Referenced by lua_isstring(), lua_tolstring(), luaG_concaterror(), and luaV_concat().
intop
#define intop (op, v1, v2) l_castU2S(l_castS2U(v1) op l_castS2U(v2))
Definition at line 46 of file lvm.h.
Referenced by intarith(), luaV_div(), luaV_execute(), and luaV_shiftl().
LUA_FLOORN2I
#define LUA_FLOORN2I 0
Definition at line 36 of file lvm.h.
luaV_fastget
#define luaV_fastget (L, t, k, slot, f)
Value:
  (!ttistable(t)  \
   ? (slot = NULL, 0)  /* not a table; 'slot' is NULL and result is 0 */  \
   : (slot = f(hvalue(t), k),  /* else, do raw access */  \
      !ttisnil(slot)))  /* result not nil? */
Definition at line 58 of file lvm.h.
Referenced by auxgetstr(), lua_geti(), luaV_execute(), and luaV_finishget().
luaV_fastset
#define luaV_fastset (L, t, k, slot, f, v)
Value:
  (!ttistable(t) \
   ? (slot = NULL, 0) \
   : (slot = f(hvalue(t), k), \
     ttisnil(slot) ? 0 \
     : (luaC_barrierback(L, hvalue(t), v), \
        setobj2t(L, cast(TValue *,slot), v), \
        1)))
Definition at line 80 of file lvm.h.
Referenced by auxsetstr(), lua_seti(), and luaV_finishset().
luaV_gettable
#define luaV_gettable (L, t, k, v)
Value:
  { const TValue *slot; \
  if (luaV_fastget(L,t,k,slot,luaH_get)) { setobj2s(L, v, slot); } \
  else luaV_finishget(L,t,k,v,slot); }
Definition at line 67 of file lvm.h.
Referenced by lua_gettable().
luaV_rawequalobj
#define luaV_rawequalobj (t1, t2) luaV_equalobj(NULL,t1,t2)
Definition at line 48 of file lvm.h.
Referenced by addk(), findindex(), getgeneric(), and lua_rawequal().
luaV_settable
#define luaV_settable (L, t, k, v)
Value:
  { const TValue *slot; \
  if (!luaV_fastset(L,t,k,slot,luaH_get,v)) \
    luaV_finishset(L,t,k,v,slot); }
Definition at line 90 of file lvm.h.
Referenced by lua_settable().
tointeger
#define tointeger (o, i) (ttisinteger(o) ? (*(i) = ivalue(o), 1) : luaV_tointeger(o,i,LUA_FLOORN2I))
Definition at line 43 of file lvm.h.
Referenced by lua_tointegerx(), luaG_tointerror(), luaO_arith(), luaV_equalobj(), luaV_execute(), and validop().
tonumber
#define tonumber (o, n) (ttisfloat(o) ? (*(n) = fltvalue(o), 1) : luaV_tonumber_(o,n))
Definition at line 40 of file lvm.h.
Referenced by forlimit(), lua_isnumber(), lua_tonumberx(), luaG_opinterror(), luaO_arith(), luaT_trybinTM(), and luaV_execute().
Function Documentation
luaV_concat()
LUAI_FUNC void luaV_concat (lua_State * L, int total)
Definition at line 478 of file lvm.c.
Referenced by lua_concat(), luaO_pushvfstring(), luaV_execute(), and luaV_finishOp().
luaV_div()
LUAI_FUNC lua_Integer luaV_div (lua_State * L, lua_Integer x, lua_Integer y)
Definition at line 556 of file lvm.c.
Referenced by intarith(), and luaV_execute().
luaV_equalobj()
LUAI_FUNC int luaV_equalobj (lua_State * L, const TValue * t1, const TValue * t2)
Definition at line 411 of file lvm.c.
Referenced by lua_compare(), and luaV_execute().
luaV_execute()
LUAI_FUNC void luaV_execute (lua_State * L)
Definition at line 790 of file lvm.c.
Referenced by luaD_call(), resume(), and unroll().
luaV_finishget()
LUAI_FUNC void luaV_finishget (lua_State * L, const TValue * t, TValue * key, StkId val, const TValue * slot)
Definition at line 164 of file lvm.c.
Referenced by auxgetstr(), lua_geti(), and luaV_execute().
luaV_finishOp()
LUAI_FUNC void luaV_finishOp (lua_State * L)
Definition at line 660 of file lvm.c.
Referenced by unroll().
luaV_finishset()
LUAI_FUNC void luaV_finishset (lua_State * L, const TValue * t, TValue * key, StkId val, const TValue * slot)
Definition at line 207 of file lvm.c.
Referenced by auxsetstr(), and lua_seti().
luaV_lessequal()
LUAI_FUNC int luaV_lessequal (lua_State * L, const TValue * l, const TValue * r)
Definition at line 388 of file lvm.c.
Referenced by lua_compare(), and luaV_execute().
luaV_lessthan()
LUAI_FUNC int luaV_lessthan (lua_State * L, const TValue * l, const TValue * r)
Definition at line 368 of file lvm.c.
Referenced by lua_compare(), and luaV_execute().
luaV_mod()
LUAI_FUNC lua_Integer luaV_mod (lua_State * L, lua_Integer x, lua_Integer y)
Definition at line 576 of file lvm.c.
Referenced by intarith(), and luaV_execute().
luaV_objlen()
LUAI_FUNC void luaV_objlen (lua_State * L, StkId ra, const TValue * rb)
Definition at line 521 of file lvm.c.
Referenced by lua_len(), and luaV_execute().
luaV_shiftl()
LUAI_FUNC lua_Integer luaV_shiftl (lua_Integer x, lua_Integer y)
Definition at line 597 of file lvm.c.
Referenced by intarith(), and luaV_execute().
luaV_tointeger()
LUAI_FUNC int luaV_tointeger (const TValue * obj, lua_Integer * p, int mode)
Definition at line 98 of file lvm.c.
Referenced by forlimit(), luaH_get(), and luaH_newkey().
luaV_tonumber_()
LUAI_FUNC int luaV_tonumber_ (const TValue * obj, lua_Number * n)
Definition at line 76 of file lvm.c.