APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c File Reference
malloc.c File Reference
#include <stdio.h>
#include <string.h>
#include <hal.h>
#include <ch.h>
#include <stdarg.h>
#include <stdint.h>
#include "stm32_util.h"
Macros
#define MEM_REGION_FLAG_DMA_OK 1
#define MEM_REGION_FLAG_FAST 2
#define MEM_REGION_FLAG_AXI_BUS 4
#define MEM_REGION_FLAG_ETH_SAFE 8
#define NUM_MEMORY_REGIONS (sizeof(memory_regions)/sizeof(memory_regions[0]))
#define MIN_ALIGNMENT 8U
#define DMA_ALIGNMENT 8U
#define DMA_RESERVE_SIZE 6144
Functions
void malloc_init (void)
static void * malloc_flags (size_t size, uint32_t flags)
void malloc_check (const void *p)
void * malloc (size_t size)
void * malloc_dma (size_t size)
void * malloc_axi_sram (size_t size)
void * malloc_eth_safe (size_t size)
void * malloc_fastmem (size_t size)
void * calloc (size_t nmemb, size_t size)
void free (void *ptr)
size_t mem_available (void)
thread_t * thread_create_alloc (size_t size, const char *name, tprio_t prio, tfunc_t pf, void *arg)
uint8_t malloc_get_heaps (memory_heap_t **_heaps, const struct memory_region **regions)
void memory_flush_all (void)
char * strdup (const char *str)
bool is_address_in_memory (void *addr)
void * get_addr_mem_region_start_addr (void *addr)
void * get_addr_mem_region_end_addr (void *addr)
void * __wrap__calloc_r (void *rptr, size_t nmemb, size_t size)
void * __wrap__malloc_r (void *rptr, size_t size)
void __wrap__free_r (void *rptr, void *ptr)
bool mem_is_dma_safe (const void *addr, uint32_t size, bool filesystem_op)
Variables
static const struct memory_region memory_regions [] = { HAL_MEMORY_REGIONS }
static memory_heap_t heaps [NUM_MEMORY_REGIONS]
static memory_heap_t dma_reserve_heap
Macro Definition Documentation
DMA_ALIGNMENT
#define DMA_ALIGNMENT 8U
Definition at line 62 of file malloc.c.
Referenced by malloc_flags().
DMA_RESERVE_SIZE
#define DMA_RESERVE_SIZE 6144
Definition at line 67 of file malloc.c.
Referenced by malloc_init().
MEM_REGION_FLAG_AXI_BUS
#define MEM_REGION_FLAG_AXI_BUS 4
Definition at line 41 of file malloc.c.
Referenced by malloc_axi_sram(), malloc_flags(), and mem_is_dma_safe().
MEM_REGION_FLAG_DMA_OK
#define MEM_REGION_FLAG_DMA_OK 1
Definition at line 39 of file malloc.c.
Referenced by malloc_axi_sram(), malloc_dma(), malloc_flags(), and mem_is_dma_safe().
MEM_REGION_FLAG_ETH_SAFE
#define MEM_REGION_FLAG_ETH_SAFE 8
Definition at line 42 of file malloc.c.
Referenced by malloc_eth_safe(), and malloc_flags().
MEM_REGION_FLAG_FAST
#define MEM_REGION_FLAG_FAST 2
Definition at line 40 of file malloc.c.
Referenced by malloc_fastmem(), and malloc_flags().
MIN_ALIGNMENT
#define MIN_ALIGNMENT 8U
Definition at line 57 of file malloc.c.
Referenced by malloc_flags().
NUM_MEMORY_REGIONS
#define NUM_MEMORY_REGIONS (sizeof(memory_regions)/sizeof(memory_regions[0]))
Definition at line 51 of file malloc.c.
Referenced by get_addr_mem_region_end_addr(), get_addr_mem_region_start_addr(), is_address_in_memory(), malloc_flags(), malloc_get_heaps(), malloc_init(), mem_available(), mem_is_dma_safe(), memory_flush_all(), and thread_create_alloc().
Function Documentation
__wrap__calloc_r()
void * __wrap__calloc_r (void * rptr, size_t nmemb, size_t size)
Definition at line 569 of file malloc.c.
__wrap__free_r()
void __wrap__free_r (void * rptr, void * ptr)
Definition at line 582 of file malloc.c.
__wrap__malloc_r()
void * __wrap__malloc_r (void * rptr, size_t size)
Definition at line 575 of file malloc.c.
calloc()
void * calloc (size_t nmemb, size_t size)
Definition at line 408 of file malloc.c.
Referenced by __wrap__calloc_r(), __wrap__malloc_r(), __wrap_vasprintf(), Linux::OpticalFlow_Onboard::_run_optflow(), Linux::VideoIn::allocate_buffers(), AuxiliaryBus::AuxiliaryBus(), bouncebuffer_init(), ByteBuffer::ByteBuffer(), AP_ExpandingArrayGeneric::expand(), AP_GPS::handle_gps_rtcm_fragment(), AP_SmartRTL::init(), ekf_imu_buffer::init(), ekf_ring_buffer::init(), malloc(), ESP32::Util::malloc_type(), AP_HAL::Util::malloc_type(), Linux::Memory_table::Memory_table(), AP_Logger::msg_fmt_for_name(), operator new(), operator new[](), ByteBuffer::set_size(), AccelCalibrator::set_status(), and ESP32::Scheduler::thread_create().
free()
void free (void * ptr)
Definition at line 413 of file malloc.c.
Referenced by __wrap__free_r(), HALSITL::UARTDriver::_begin(), Linux::UARTDriver::_parseDevicePath(), Linux::OpticalFlow_Onboard::_run_optflow(), ChibiOS::Storage::_save_backup(), HALSITL::SITL_State::_set_param_default(), apfs_fclose(), apfs_fprintf(), apfs_freopen(), apfs_tmpfile(), base64_decode(), BM_Crop8bpp(), BM_YuyvToGrey(), bouncebuffer_setup_read(), bouncebuffer_setup_write(), MultiHeap::destroy(), emit_docs(), emit_docs_method(), error(), SITL::FlightAxis::exchange_data(), ESP32::Util::free_type(), AP_HAL::Util::free_type(), Linux::I2CDeviceManager::get_device(), Linux::Led_Sysfs::init(), Linux::PWM_Sysfs_Base::init(), AP_SmartRTL::init(), ekf_imu_buffer::init(), ekf_ring_buffer::init(), SITL::XPlane::load_dref_map(), AP_Filesystem_Backend::load_file(), HALSITL::SITL_State::lookup_location(), main(), AP_Logger::msg_fmt_for_name(), newbuffsize(), nmea_printf(), SITL::VectorNav::nmea_printf(), nmea_printf_buffer(), nmea_vaprintf(), Linux::RCInput_Navio2::open_channel(), operator delete(), operator delete[](), AP_GPS_SBF::parse(), HALSITL::SITL_State::parse_home(), realloc(), SITL::JSON_Master::send(), SITL::JSBSim::send_servos(), SITL::SilentWings::send_servos(), AP_Networking::sendfile_check(), SITL::SMBusDevice::set_block(), ExpandingString::set_buffer(), AnalogSource_Navio2::set_channel(), ByteBuffer::set_size(), AccelCalibrator::set_status(), SITL::FlightAxis::soap_request_start(), stackCheck(), ChibiOS::Scheduler::thread_create(), ESP32::Scheduler::thread_create(), HALSITL::Scheduler::thread_create(), ChibiOS::Scheduler::thread_create_trampoline(), ESP32::Scheduler::thread_create_trampoline(), HALSITL::Scheduler::thread_create_trampoline(), trace(), AP_Filesystem_Backend::unload_file(), AP_ExpandingArrayGeneric::~AP_ExpandingArrayGeneric(), AP_GPS_SBF::~AP_GPS_SBF(), AuxiliaryBus::~AuxiliaryBus(), ByteBuffer::~ByteBuffer(), ExpandingString::~ExpandingString(), ESP32::I2CDevice::~I2CDevice(), Linux::Memory_table::~Memory_table(), Linux::PWM_Sysfs_Base::~PWM_Sysfs_Base(), ChibiOS::SPIDevice::~SPIDevice(), and ESP32::SPIDevice::~SPIDevice().
get_addr_mem_region_end_addr()
void * get_addr_mem_region_end_addr (void * addr)
Definition at line 554 of file malloc.c.
Referenced by CrashCatcher_DumpStartFlash().
get_addr_mem_region_start_addr()
void * get_addr_mem_region_start_addr (void * addr)
Definition at line 539 of file malloc.c.
Referenced by CrashCatcher_DumpStartFlash().
is_address_in_memory()
bool is_address_in_memory (void * addr)
Definition at line 524 of file malloc.c.
Referenced by CrashCatcher_DumpStartFlash(), and CrashCatcher_GetMemoryRegions().
malloc()
void * malloc (size_t size)
Definition at line 361 of file malloc.c.
Referenced by calloc(), and strdup().
malloc_axi_sram()
void * malloc_axi_sram (size_t size)
Definition at line 378 of file malloc.c.
Referenced by bouncebuffer_init(), bouncebuffer_setup_read(), bouncebuffer_setup_write(), ESP32::Util::malloc_type(), and sdcard_init().
malloc_check()
void malloc_check (const void * p)
Definition at line 350 of file malloc.c.
Referenced by ChibiOS::Scheduler::_monitor_thread().
malloc_dma()
void * malloc_dma (size_t size)
Definition at line 369 of file malloc.c.
Referenced by ChibiOS::SPIDevice::acquire_bus(), bouncebuffer_init(), bouncebuffer_setup_read(), bouncebuffer_setup_write(), malloc_init(), and ESP32::Util::malloc_type().
malloc_eth_safe()
void * malloc_eth_safe (size_t size)
Definition at line 390 of file malloc.c.
malloc_fastmem()
void * malloc_fastmem (size_t size)
Definition at line 403 of file malloc.c.
Referenced by ESP32::Util::malloc_type().
malloc_flags()
static void * malloc_flags (size_t size, uint32_t flags) static
Definition at line 124 of file malloc.c.
Referenced by malloc(), malloc_axi_sram(), malloc_dma(), malloc_eth_safe(), and malloc_fastmem().
malloc_get_heaps()
uint8_t malloc_get_heaps (memory_heap_t ** _heaps, const struct memory_region ** regions)
Definition at line 485 of file malloc.c.
Referenced by ChibiOS::Util::mem_info().
malloc_init()
void malloc_init (void)
Definition at line 77 of file malloc.c.
Referenced by __late_init().
mem_available()
size_t mem_available (void)
Definition at line 427 of file malloc.c.
mem_is_dma_safe()
bool mem_is_dma_safe (const void * addr, uint32_t size, bool filesystem_op)
Definition at line 623 of file malloc.c.
Referenced by bouncebuffer_setup_read(), and bouncebuffer_setup_write().
memory_flush_all()
void memory_flush_all (void)
Definition at line 498 of file malloc.c.
strdup()
char * strdup (const char * str)
Definition at line 509 of file malloc.c.
Referenced by HALSITL::UARTDriver::_begin(), Linux::PWM_Sysfs_Bebop::_generate_export_path(), HALSITL::SITL_State::_parse_command_line(), Linux::UARTDriver::_parseDevicePath(), HALSITL::SITL_State::_set_param_default(), SITL::XPlane::add_dref(), SITL::XPlane::load_dref_map(), SITL::Frame::load_frame_params(), SITL::Morse::Morse(), HALSITL::SITL_State::parse_home(), SITL::FlightAxis::soap_request_end(), and SITL::Webots::Webots().
thread_create_alloc()
thread_t * thread_create_alloc (size_t size, const char * name, tprio_t prio, tfunc_t pf, void * arg)
Definition at line 459 of file malloc.c.
Referenced by ChibiOS::DeviceBus::register_periodic_callback(), ChibiOS::Scheduler::thread_create(), ChibiOS::UARTDriver::thread_init(), and ChibiOS::UARTDriver::thread_rx_init().
Variable Documentation
dma_reserve_heap
memory_heap_t dma_reserve_heap static
Definition at line 71 of file malloc.c.
Referenced by malloc_flags(), malloc_init(), and mem_available().
heaps
memory_heap_t heaps[NUM_MEMORY_REGIONS] static
Definition at line 55 of file malloc.c.
Referenced by malloc_flags(), malloc_get_heaps(), malloc_init(), mem_available(), ChibiOS::Util::mem_info(), and thread_create_alloc().
memory_regions
const struct memory_region memory_regions[] = { HAL_MEMORY_REGIONS } static
Definition at line 48 of file malloc.c.
Referenced by get_addr_mem_region_end_addr(), get_addr_mem_region_start_addr(), is_address_in_memory(), malloc_flags(), malloc_get_heaps(), malloc_init(), mem_is_dma_safe(), and memory_flush_all().