APM:Libraries: libraries/AP_Math/matrix_alg.cpp File Reference
matrix_alg.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include "AP_Math.h"
#include <stdio.h>
#include <fenv.h>
Functions
template<typename T >
static T * matrix_multiply (const T *A, const T *B, uint16_t n)
template<typename T >
static void swap (T &a, T &b)
template<typename T >
static void mat_pivot (const T *A, T *pivot, uint16_t n)
template<typename T >
static void mat_forward_sub (const T *L, T *out, uint16_t n)
template<typename T >
static void mat_back_sub (const T *U, T *out, uint16_t n)
template<typename T >
static void mat_LU_decompose (const T *A, T *L, T *U, T *P, uint16_t n)
template<typename T >
static bool mat_inverseN (const T *A, T *inv, uint16_t n)
template<typename T >
static bool inverse3x3 (const T m[], T invOut[])
template<typename T >
static bool inverse4x4 (const T m[], T invOut[])
template<typename T >
bool mat_inverse (const T x[], T y[], uint16_t dim)
template<typename T >
void mat_mul (const T *A, const T *B, T *C, uint16_t n)
template<typename T >
void mat_identity (T *A, uint16_t n)
template bool mat_inverse< float > (const float x[], float y[], uint16_t dim)
template void mat_mul< float > (const float *A, const float *B, float *C, uint16_t n)
template void mat_identity< float > (float x[], uint16_t dim)
template bool mat_inverse< double > (const double x[], double y[], uint16_t dim)
template void mat_mul< double > (const double *A, const double *B, double *C, uint16_t n)
template void mat_identity< double > (double x[], uint16_t dim)
Function Documentation
inverse3x3()
template<typename T > static bool inverse3x3 (const T m[], T invOut[]) static
Definition at line 245 of file matrix_alg.cpp.
Referenced by mat_inverse().
inverse4x4()
template<typename T > static bool inverse4x4 (const T m[], T invOut[]) static
Definition at line 284 of file matrix_alg.cpp.
Referenced by mat_inverse().
mat_back_sub()
template<typename T > static void mat_back_sub (const T * U, T * out, uint16_t n) static
Definition at line 129 of file matrix_alg.cpp.
Referenced by mat_inverseN().
mat_forward_sub()
template<typename T > static void mat_forward_sub (const T * L, T * out, uint16_t n) static
Definition at line 107 of file matrix_alg.cpp.
Referenced by mat_inverseN().
mat_identity()
template<typename T > void mat_identity (T * A, uint16_t n)
Definition at line 461 of file matrix_alg.cpp.
Referenced by test_matrix_inverse().
mat_identity< double >()
template void mat_identity< double > (double x[], uint16_t dim)
mat_identity< float >()
template void mat_identity< float > (float x[], uint16_t dim)
mat_inverse()
template<typename T > bool mat_inverse (const T x[], T y[], uint16_t dim)
Definition at line 438 of file matrix_alg.cpp.
mat_inverse< double >()
template bool mat_inverse< double > (const double x[], double y[], uint16_t dim)
mat_inverse< float >()
template bool mat_inverse< float > (const float x[], float y[], uint16_t dim)
mat_inverseN()
template<typename T > static bool mat_inverseN (const T * A, T * inv, uint16_t n) static
Definition at line 193 of file matrix_alg.cpp.
Referenced by mat_inverse().
mat_LU_decompose()
template<typename T > static void mat_LU_decompose (const T * A, T * L, T * U, T * P, uint16_t n) static
Definition at line 152 of file matrix_alg.cpp.
Referenced by mat_inverseN().
mat_mul()
template<typename T > void mat_mul (const T * A, const T * B, T * C, uint16_t n)
Definition at line 448 of file matrix_alg.cpp.
Referenced by test_matrix_inverse().
mat_mul< double >()
template void mat_mul< double > (const double * A, const double * B, double * C, uint16_t n)
mat_mul< float >()
template void mat_mul< float > (const float * A, const float * B, float * C, uint16_t n)
mat_pivot()
template<typename T > static void mat_pivot (const T * A, T * pivot, uint16_t n) static
Definition at line 69 of file matrix_alg.cpp.
Referenced by mat_LU_decompose().
matrix_multiply()
template<typename T > static T * matrix_multiply (const T * A, const T * B, uint16_t n) static
Definition at line 36 of file matrix_alg.cpp.
Referenced by mat_inverseN(), and mat_LU_decompose().
swap()
template<typename T > static void swap (T & a, T & b) inline static
Definition at line 52 of file matrix_alg.cpp.
Referenced by mat_pivot(), my_mexInputArray2Buff(), my_mexReturnArrayFromBuff(), AP_JSON::value::operator=(), AP_JSON::value::operator=(), and scalarmult().