APM:Libraries: libraries/AP_CheckFirmware/monocypher.h File Reference
monocypher.h File Reference
#include <stddef.h>
#include <stdint.h>
Classes
struct crypto_sign_vtable
Type definitions ///.
struct crypto_poly1305_ctx
struct crypto_blake2b_ctx
struct crypto_sign_ctx_abstract
struct crypto_sign_ctx
Macros
#define crypto_key_exchange_public_key crypto_x25519_public_key
Typedefs
typedef crypto_sign_ctx_abstract crypto_check_ctx_abstract
typedef crypto_sign_ctx crypto_check_ctx
Functions
int crypto_verify16 (const uint8_t a[16], const uint8_t b[16])
High level interface ///.
int crypto_verify32 (const uint8_t a[32], const uint8_t b[32])
int crypto_verify64 (const uint8_t a[64], const uint8_t b[64])
void crypto_wipe (void *secret, size_t size)
void crypto_lock (uint8_t mac[16], uint8_t *cipher_text, const uint8_t key[32], const uint8_t nonce[24], const uint8_t *plain_text, size_t text_size)
int crypto_unlock (uint8_t *plain_text, const uint8_t key[32], const uint8_t nonce[24], const uint8_t mac[16], const uint8_t *cipher_text, size_t text_size)
void crypto_lock_aead (uint8_t mac[16], uint8_t *cipher_text, const uint8_t key[32], const uint8_t nonce[24], const uint8_t *ad, size_t ad_size, const uint8_t *plain_text, size_t text_size)
int crypto_unlock_aead (uint8_t *plain_text, const uint8_t key[32], const uint8_t nonce[24], const uint8_t mac[16], const uint8_t *ad, size_t ad_size, const uint8_t *cipher_text, size_t text_size)
void crypto_blake2b (uint8_t hash[64], const uint8_t *message, size_t message_size)
void crypto_blake2b_general (uint8_t *hash, size_t hash_size, const uint8_t *key, size_t key_size, const uint8_t *message, size_t message_size)
void crypto_blake2b_init (crypto_blake2b_ctx *ctx)
void crypto_blake2b_update (crypto_blake2b_ctx *ctx, const uint8_t *message, size_t message_size)
void crypto_blake2b_final (crypto_blake2b_ctx *ctx, uint8_t *hash)
void crypto_blake2b_general_init (crypto_blake2b_ctx *ctx, size_t hash_size, const uint8_t *key, size_t key_size)
void crypto_argon2i (uint8_t *hash, uint32_t hash_size, void *work_area, uint32_t nb_blocks, uint32_t nb_iterations, const uint8_t *password, uint32_t password_size, const uint8_t *salt, uint32_t salt_size)
void crypto_argon2i_general (uint8_t *hash, uint32_t hash_size, void *work_area, uint32_t nb_blocks, uint32_t nb_iterations, const uint8_t *password, uint32_t password_size, const uint8_t *salt, uint32_t salt_size, const uint8_t *key, uint32_t key_size, const uint8_t *ad, uint32_t ad_size)
void crypto_key_exchange (uint8_t shared_key[32], const uint8_t your_secret_key[32], const uint8_t their_public_key[32])
Key exchange ///.
void crypto_sign_public_key (uint8_t public_key[32], const uint8_t secret_key[32])
void crypto_sign (uint8_t signature[64], const uint8_t secret_key[32], const uint8_t public_key[32], const uint8_t *message, size_t message_size)
int crypto_check (const uint8_t signature[64], const uint8_t public_key[32], const uint8_t *message, size_t message_size)
void crypto_hchacha20 (uint8_t out[32], const uint8_t key[32], const uint8_t in[16])
Low level primitives ///.
void crypto_chacha20 (uint8_t *cipher_text, const uint8_t *plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[8])
void crypto_xchacha20 (uint8_t *cipher_text, const uint8_t *plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[24])
void crypto_ietf_chacha20 (uint8_t *cipher_text, const uint8_t *plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[12])
uint64_t crypto_chacha20_ctr (uint8_t *cipher_text, const uint8_t *plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[8], uint64_t ctr)
uint64_t crypto_xchacha20_ctr (uint8_t *cipher_text, const uint8_t *plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[24], uint64_t ctr)
uint32_t crypto_ietf_chacha20_ctr (uint8_t *cipher_text, const uint8_t *plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[12], uint32_t ctr)
void crypto_poly1305 (uint8_t mac[16], const uint8_t *message, size_t message_size, const uint8_t key[32])
void crypto_poly1305_init (crypto_poly1305_ctx *ctx, const uint8_t key[32])
void crypto_poly1305_update (crypto_poly1305_ctx *ctx, const uint8_t *message, size_t message_size)
void crypto_poly1305_final (crypto_poly1305_ctx *ctx, uint8_t mac[16])
void crypto_x25519_public_key (uint8_t public_key[32], const uint8_t secret_key[32])
void crypto_x25519 (uint8_t raw_shared_secret[32], const uint8_t your_secret_key[32], const uint8_t their_public_key[32])
void crypto_x25519_dirty_small (uint8_t pk[32], const uint8_t sk[32])
void crypto_x25519_dirty_fast (uint8_t pk[32], const uint8_t sk[32])
void crypto_x25519_inverse (uint8_t blind_salt[32], const uint8_t private_key[32], const uint8_t curve_point[32])
void crypto_from_eddsa_private (uint8_t x25519[32], const uint8_t eddsa[32])
EdDSA to X25519 ///.
void crypto_from_eddsa_public (uint8_t x25519[32], const uint8_t eddsa[32])
void crypto_sign_init_first_pass (crypto_sign_ctx_abstract *ctx, const uint8_t secret_key[32], const uint8_t public_key[32])
void crypto_sign_update (crypto_sign_ctx_abstract *ctx, const uint8_t *message, size_t message_size)
void crypto_sign_init_second_pass (crypto_sign_ctx_abstract *ctx)
void crypto_sign_final (crypto_sign_ctx_abstract *ctx, uint8_t signature[64])
void crypto_check_init (crypto_check_ctx_abstract *ctx, const uint8_t signature[64], const uint8_t public_key[32])
void crypto_check_update (crypto_check_ctx_abstract *ctx, const uint8_t *message, size_t message_size)
int crypto_check_final (crypto_check_ctx_abstract *ctx)
void crypto_sign_public_key_custom_hash (uint8_t public_key[32], const uint8_t secret_key[32], const crypto_sign_vtable *hash)
void crypto_sign_init_first_pass_custom_hash (crypto_sign_ctx_abstract *ctx, const uint8_t secret_key[32], const uint8_t public_key[32], const crypto_sign_vtable *hash)
void crypto_check_init_custom_hash (crypto_check_ctx_abstract *ctx, const uint8_t signature[64], const uint8_t public_key[32], const crypto_sign_vtable *hash)
void crypto_hidden_to_curve (uint8_t curve[32], const uint8_t hidden[32])
int crypto_curve_to_hidden (uint8_t hidden[32], const uint8_t curve[32], uint8_t tweak)
void crypto_hidden_key_pair (uint8_t hidden[32], uint8_t secret_key[32], uint8_t seed[32])
Variables
const crypto_sign_vtable crypto_blake2b_vtable
Macro Definition Documentation
crypto_key_exchange_public_key
#define crypto_key_exchange_public_key crypto_x25519_public_key
Definition at line 200 of file monocypher.h.
Typedef Documentation
crypto_check_ctx
typedef crypto_sign_ctx crypto_check_ctx
Definition at line 108 of file monocypher.h.
crypto_check_ctx_abstract
typedef crypto_sign_ctx_abstract crypto_check_ctx_abstract
Definition at line 102 of file monocypher.h.
Function Documentation
crypto_argon2i()
void crypto_argon2i (uint8_t * hash, uint32_t hash_size, void * work_area, uint32_t nb_blocks, uint32_t nb_iterations, const uint8_t * password, uint32_t password_size, const uint8_t * salt, uint32_t salt_size)
crypto_argon2i_general()
void crypto_argon2i_general (uint8_t * hash, uint32_t hash_size, void * work_area, uint32_t nb_blocks, uint32_t nb_iterations, const uint8_t * password, uint32_t password_size, const uint8_t * salt, uint32_t salt_size, const uint8_t * key, uint32_t key_size, const uint8_t * ad, uint32_t ad_size)
crypto_blake2b()
void crypto_blake2b (uint8_t hash[64], const uint8_t * message, size_t message_size)
Definition at line 669 of file monocypher.cpp.
Referenced by crypto_from_eddsa_private().
crypto_blake2b_final()
void crypto_blake2b_final (crypto_blake2b_ctx * ctx, uint8_t * hash)
Definition at line 643 of file monocypher.cpp.
Referenced by blake2b_vtable_final(), and crypto_blake2b_general().
crypto_blake2b_general()
void crypto_blake2b_general (uint8_t * hash, size_t hash_size, const uint8_t * key, size_t key_size, const uint8_t * message, size_t message_size)
Definition at line 659 of file monocypher.cpp.
Referenced by crypto_blake2b().
crypto_blake2b_general_init()
void crypto_blake2b_general_init (crypto_blake2b_ctx * ctx, size_t hash_size, const uint8_t * key, size_t key_size)
Definition at line 591 of file monocypher.cpp.
Referenced by crypto_blake2b_general(), and crypto_blake2b_init().
crypto_blake2b_init()
void crypto_blake2b_init (crypto_blake2b_ctx * ctx)
Definition at line 613 of file monocypher.cpp.
Referenced by blake2b_vtable_init().
crypto_blake2b_update()
void crypto_blake2b_update (crypto_blake2b_ctx * ctx, const uint8_t * message, size_t message_size)
Definition at line 618 of file monocypher.cpp.
Referenced by blake2b_vtable_update(), and crypto_blake2b_general().
crypto_chacha20()
void crypto_chacha20 (uint8_t * cipher_text, const uint8_t * plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[8])
Definition at line 299 of file monocypher.cpp.
Referenced by crypto_hidden_key_pair(), crypto_lock_aead(), and crypto_unlock_aead().
crypto_chacha20_ctr()
uint64_t crypto_chacha20_ctr (uint8_t * cipher_text, const uint8_t * plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[8], uint64_t ctr)
Definition at line 220 of file monocypher.cpp.
Referenced by crypto_chacha20(), crypto_ietf_chacha20_ctr(), crypto_lock_aead(), crypto_unlock_aead(), and crypto_xchacha20_ctr().
crypto_check()
int crypto_check (const uint8_t signature[64], const uint8_t public_key[32], const uint8_t * message, size_t message_size)
Definition at line 2453 of file monocypher.cpp.
crypto_check_final()
int crypto_check_final (crypto_check_ctx_abstract * ctx)
Definition at line 2439 of file monocypher.cpp.
Referenced by crypto_check().
crypto_check_init()
void crypto_check_init (crypto_check_ctx_abstract * ctx, const uint8_t signature[64], const uint8_t public_key[32])
Definition at line 2426 of file monocypher.cpp.
Referenced by crypto_check().
crypto_check_init_custom_hash()
void crypto_check_init_custom_hash (crypto_check_ctx_abstract * ctx, const uint8_t signature[64], const uint8_t public_key[32], const crypto_sign_vtable * hash)
Definition at line 2413 of file monocypher.cpp.
Referenced by crypto_check_init().
crypto_check_update()
void crypto_check_update (crypto_check_ctx_abstract * ctx, const uint8_t * message, size_t message_size)
Definition at line 2433 of file monocypher.cpp.
Referenced by crypto_check().
crypto_curve_to_hidden()
int crypto_curve_to_hidden (uint8_t hidden[32], const uint8_t curve[32], uint8_t tweak)
Definition at line 2788 of file monocypher.cpp.
Referenced by crypto_hidden_key_pair().
crypto_from_eddsa_private()
void crypto_from_eddsa_private (uint8_t x25519[32], const uint8_t eddsa[32])
EdDSA to X25519 ///.
Definition at line 2466 of file monocypher.cpp.
crypto_from_eddsa_public()
void crypto_from_eddsa_public (uint8_t x25519[32], const uint8_t eddsa[32])
Definition at line 2474 of file monocypher.cpp.
crypto_hchacha20()
void crypto_hchacha20 (uint8_t out[32], const uint8_t key[32], const uint8_t in[16])
Low level primitives ///.
Definition at line 207 of file monocypher.cpp.
Referenced by crypto_key_exchange(), crypto_lock_aead(), crypto_unlock_aead(), and crypto_xchacha20_ctr().
crypto_hidden_key_pair()
void crypto_hidden_key_pair (uint8_t hidden[32], uint8_t secret_key[32], uint8_t seed[32])
Definition at line 2822 of file monocypher.cpp.
crypto_hidden_to_curve()
void crypto_hidden_to_curve (uint8_t curve[32], const uint8_t hidden[32])
Definition at line 2715 of file monocypher.cpp.
crypto_ietf_chacha20()
void crypto_ietf_chacha20 (uint8_t * cipher_text, const uint8_t * plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[12])
Definition at line 305 of file monocypher.cpp.
crypto_ietf_chacha20_ctr()
uint32_t crypto_ietf_chacha20_ctr (uint8_t * cipher_text, const uint8_t * plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[12], uint32_t ctr)
Definition at line 278 of file monocypher.cpp.
Referenced by crypto_ietf_chacha20().
crypto_key_exchange()
void crypto_key_exchange (uint8_t shared_key[32], const uint8_t your_secret_key[32], const uint8_t their_public_key[32])
Key exchange ///.
Definition at line 2847 of file monocypher.cpp.
crypto_lock()
void crypto_lock (uint8_t mac[16], uint8_t * cipher_text, const uint8_t key[32], const uint8_t nonce[24], const uint8_t * plain_text, size_t text_size)
Definition at line 3031 of file monocypher.cpp.
crypto_lock_aead()
void crypto_lock_aead (uint8_t mac[16], uint8_t * cipher_text, const uint8_t key[32], const uint8_t nonce[24], const uint8_t * ad, size_t ad_size, const uint8_t * plain_text, size_t text_size)
Definition at line 2991 of file monocypher.cpp.
Referenced by crypto_lock().
crypto_poly1305()
void crypto_poly1305 (uint8_t mac[16], const uint8_t * message, size_t message_size, const uint8_t key[32])
Definition at line 470 of file monocypher.cpp.
crypto_poly1305_final()
void crypto_poly1305_final (crypto_poly1305_ctx * ctx, uint8_t mac[16])
Definition at line 440 of file monocypher.cpp.
Referenced by crypto_poly1305(), and lock_auth().
crypto_poly1305_init()
void crypto_poly1305_init (crypto_poly1305_ctx * ctx, const uint8_t key[32])
Definition at line 398 of file monocypher.cpp.
Referenced by crypto_poly1305(), and lock_auth().
crypto_poly1305_update()
void crypto_poly1305_update (crypto_poly1305_ctx * ctx, const uint8_t * message, size_t message_size)
Definition at line 412 of file monocypher.cpp.
Referenced by crypto_poly1305(), and lock_auth().
crypto_sign()
void crypto_sign (uint8_t signature[64], const uint8_t secret_key[32], const uint8_t public_key[32], const uint8_t * message, size_t message_size)
Definition at line 2399 of file monocypher.cpp.
crypto_sign_final()
void crypto_sign_final (crypto_sign_ctx_abstract * ctx, uint8_t signature[64])
Definition at line 2385 of file monocypher.cpp.
Referenced by crypto_sign().
crypto_sign_init_first_pass()
void crypto_sign_init_first_pass (crypto_sign_ctx_abstract * ctx, const uint8_t secret_key[32], const uint8_t public_key[32])
Definition at line 2351 of file monocypher.cpp.
Referenced by crypto_sign().
crypto_sign_init_first_pass_custom_hash()
void crypto_sign_init_first_pass_custom_hash (crypto_sign_ctx_abstract * ctx, const uint8_t secret_key[32], const uint8_t public_key[32], const crypto_sign_vtable * hash)
Definition at line 2325 of file monocypher.cpp.
Referenced by crypto_sign_init_first_pass().
crypto_sign_init_second_pass()
void crypto_sign_init_second_pass (crypto_sign_ctx_abstract * ctx)
Definition at line 2365 of file monocypher.cpp.
Referenced by crypto_sign().
crypto_sign_public_key()
void crypto_sign_public_key (uint8_t public_key[32], const uint8_t secret_key[32])
Definition at line 2319 of file monocypher.cpp.
crypto_sign_public_key_custom_hash()
void crypto_sign_public_key_custom_hash (uint8_t public_key[32], const uint8_t secret_key[32], const crypto_sign_vtable * hash)
Definition at line 2305 of file monocypher.cpp.
Referenced by crypto_sign_init_first_pass_custom_hash(), and crypto_sign_public_key().
crypto_sign_update()
void crypto_sign_update (crypto_sign_ctx_abstract * ctx, const uint8_t * message, size_t message_size)
Definition at line 2359 of file monocypher.cpp.
Referenced by crypto_sign().
crypto_unlock()
int crypto_unlock (uint8_t * plain_text, const uint8_t key[32], const uint8_t nonce[24], const uint8_t mac[16], const uint8_t * cipher_text, size_t text_size)
Definition at line 3038 of file monocypher.cpp.
crypto_unlock_aead()
int crypto_unlock_aead (uint8_t * plain_text, const uint8_t key[32], const uint8_t nonce[24], const uint8_t mac[16], const uint8_t * ad, size_t ad_size, const uint8_t * cipher_text, size_t text_size)
Definition at line 3007 of file monocypher.cpp.
Referenced by crypto_unlock().
crypto_verify16()
int crypto_verify16 (const uint8_t a[16], const uint8_t b[16])
High level interface ///.
Definition at line 158 of file monocypher.cpp.
Referenced by crypto_unlock_aead().
crypto_verify32()
int crypto_verify32 (const uint8_t a[32], const uint8_t b[32])
Definition at line 159 of file monocypher.cpp.
Referenced by crypto_check_final(), and fe_isequal().
crypto_verify64()
int crypto_verify64 (const uint8_t a[64], const uint8_t b[64])
Definition at line 160 of file monocypher.cpp.
crypto_wipe()
void crypto_wipe (void * secret, size_t size)
Definition at line 162 of file monocypher.cpp.
Referenced by crypto_hidden_key_pair(), and crypto_sign_final().
crypto_x25519()
void crypto_x25519 (uint8_t raw_shared_secret[32], const uint8_t your_secret_key[32], const uint8_t their_public_key[32])
Definition at line 1649 of file monocypher.cpp.
Referenced by crypto_key_exchange(), and crypto_x25519_public_key().
crypto_x25519_dirty_fast()
void crypto_x25519_dirty_fast (uint8_t pk[32], const uint8_t sk[32])
Definition at line 2596 of file monocypher.cpp.
Referenced by crypto_hidden_key_pair().
crypto_x25519_dirty_small()
void crypto_x25519_dirty_small (uint8_t pk[32], const uint8_t sk[32])
Definition at line 2560 of file monocypher.cpp.
crypto_x25519_inverse()
void crypto_x25519_inverse (uint8_t blind_salt[32], const uint8_t private_key[32], const uint8_t curve_point[32])
Definition at line 2910 of file monocypher.cpp.
crypto_x25519_public_key()
void crypto_x25519_public_key (uint8_t public_key[32], const uint8_t secret_key[32])
Definition at line 1661 of file monocypher.cpp.
crypto_xchacha20()
void crypto_xchacha20 (uint8_t * cipher_text, const uint8_t * plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[24])
Definition at line 312 of file monocypher.cpp.
crypto_xchacha20_ctr()
uint64_t crypto_xchacha20_ctr (uint8_t * cipher_text, const uint8_t * plain_text, size_t text_size, const uint8_t key[32], const uint8_t nonce[24], uint64_t ctr)
Definition at line 287 of file monocypher.cpp.
Referenced by crypto_xchacha20().
Variable Documentation
crypto_blake2b_vtable
const crypto_sign_vtable crypto_blake2b_vtable extern
Definition at line 683 of file monocypher.cpp.
Referenced by crypto_check_init(), crypto_sign_init_first_pass(), and crypto_sign_public_key().