APM:Libraries: AP_HAL::WSPI Namespace Reference
AP_HAL::WSPI Namespace Reference
Variables
constexpr uint32_t CFG_CMD_MODE_MASK = (7LU << 0LU)
constexpr uint32_t CFG_CMD_MODE_NONE = (0LU << 0LU)
constexpr uint32_t CFG_CMD_MODE_ONE_LINE = (1LU << 0LU)
constexpr uint32_t CFG_CMD_MODE_TWO_LINES = (2LU << 0LU)
constexpr uint32_t CFG_CMD_MODE_FOUR_LINES = (3LU << 0LU)
constexpr uint32_t CFG_CMD_MODE_EIGHT_LINES = (4LU << 0LU)
constexpr uint32_t CFG_CMD_SIZE_MASK = (3LU << 4LU)
constexpr uint32_t CFG_CMD_SIZE_8 = (0LU << 4LU)
constexpr uint32_t CFG_ADDR_MODE_MASK = (7LU << 8LU)
constexpr uint32_t CFG_ADDR_MODE_NONE = (0LU << 8LU)
constexpr uint32_t CFG_ADDR_MODE_ONE_LINE = (1LU << 8LU)
constexpr uint32_t CFG_ADDR_MODE_TWO_LINES = (2LU << 8LU)
constexpr uint32_t CFG_ADDR_MODE_FOUR_LINES = (3LU << 8LU)
constexpr uint32_t CFG_ADDR_MODE_EIGHT_LINES = (4LU << 8LU)
constexpr uint32_t CFG_ADDR_SIZE_MASK = (3LU << 12LU)
constexpr uint32_t CFG_ADDR_SIZE_8 = (0LU << 12LU)
constexpr uint32_t CFG_ADDR_SIZE_16 = (1LU << 12LU)
constexpr uint32_t CFG_ADDR_SIZE_24 = (2LU << 12LU)
constexpr uint32_t CFG_ADDR_SIZE_32 = (3LU << 12LU)
constexpr uint32_t CFG_ALT_MODE_MASK = (7LU << 16LU)
constexpr uint32_t CFG_ALT_MODE_NONE = (0LU << 16LU)
constexpr uint32_t CFG_ALT_MODE_ONE_LINE = (1LU << 16LU)
constexpr uint32_t CFG_ALT_MODE_TWO_LINES = (2LU << 16LU)
constexpr uint32_t CFG_ALT_MODE_FOUR_LINES = (3LU << 16LU)
constexpr uint32_t CFG_ALT_MODE_EIGHT_LINES = (4LU << 16LU)
constexpr uint32_t CFG_ALT_DDR = (1LU << 19LU)
constexpr uint32_t CFG_ALT_SIZE_MASK = (3LU << 20LU)
constexpr uint32_t CFG_ALT_SIZE_8 = (0LU << 20LU)
constexpr uint32_t CFG_ALT_SIZE_16 = (1LU << 20LU)
constexpr uint32_t CFG_ALT_SIZE_24 = (2LU << 20LU)
constexpr uint32_t CFG_ALT_SIZE_32 = (3LU << 20LU)
constexpr uint32_t CFG_DATA_MODE_MASK = (7LU << 24LU)
constexpr uint32_t CFG_DATA_MODE_NONE = (0LU << 24LU)
constexpr uint32_t CFG_DATA_MODE_ONE_LINE = (1LU << 24LU)
constexpr uint32_t CFG_DATA_MODE_TWO_LINES = (2LU << 24LU)
constexpr uint32_t CFG_DATA_MODE_FOUR_LINES = (3LU << 24LU)
constexpr uint32_t CFG_DATA_MODE_EIGHT_LINES = (4LU << 24LU)
constexpr uint32_t CFG_DATA_DDR = (1LU << 27LU)
constexpr uint32_t CFG_SIOO = (1LU << 31LU)
Variable Documentation
CFG_ADDR_MODE_EIGHT_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_ADDR_MODE_EIGHT_LINES = (4LU << 8LU) constexpr
Definition at line 98 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::read(), and AP_FlashIface_JEDEC::start_xip_mode().
CFG_ADDR_MODE_FOUR_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_ADDR_MODE_FOUR_LINES = (3LU << 8LU) constexpr
Definition at line 97 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::read(), and AP_FlashIface_JEDEC::start_xip_mode().
CFG_ADDR_MODE_MASK
constexpr uint32_t AP_HAL::WSPI::CFG_ADDR_MODE_MASK = (7LU << 8LU) constexpr
Definition at line 93 of file WSPIDevice.h.
CFG_ADDR_MODE_NONE
constexpr uint32_t AP_HAL::WSPI::CFG_ADDR_MODE_NONE = (0LU << 8LU) constexpr
Definition at line 94 of file WSPIDevice.h.
CFG_ADDR_MODE_ONE_LINE
constexpr uint32_t AP_HAL::WSPI::CFG_ADDR_MODE_ONE_LINE = (1LU << 8LU) constexpr
Definition at line 95 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::configure_device(), AP_FlashIface_JEDEC::detect_device(), AP_FlashIface_JEDEC::start_erase_offset(), and AP_FlashIface_JEDEC::start_program_offset().
CFG_ADDR_MODE_TWO_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_ADDR_MODE_TWO_LINES = (2LU << 8LU) constexpr
Definition at line 96 of file WSPIDevice.h.
CFG_ADDR_SIZE_16
constexpr uint32_t AP_HAL::WSPI::CFG_ADDR_SIZE_16 = (1LU << 12LU) constexpr
Definition at line 103 of file WSPIDevice.h.
CFG_ADDR_SIZE_24
constexpr uint32_t AP_HAL::WSPI::CFG_ADDR_SIZE_24 = (2LU << 12LU) constexpr
Definition at line 104 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::detect_device(), AP_FlashIface_JEDEC::read(), AP_FlashIface_JEDEC::start_erase_offset(), AP_FlashIface_JEDEC::start_program_offset(), and AP_FlashIface_JEDEC::start_xip_mode().
CFG_ADDR_SIZE_32
constexpr uint32_t AP_HAL::WSPI::CFG_ADDR_SIZE_32 = (3LU << 12LU) constexpr
Definition at line 105 of file WSPIDevice.h.
CFG_ADDR_SIZE_8
constexpr uint32_t AP_HAL::WSPI::CFG_ADDR_SIZE_8 = (0LU << 12LU) constexpr
Definition at line 102 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::configure_device().
CFG_ADDR_SIZE_MASK
constexpr uint32_t AP_HAL::WSPI::CFG_ADDR_SIZE_MASK = (3LU << 12LU) constexpr
Definition at line 101 of file WSPIDevice.h.
CFG_ALT_DDR
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_DDR = (1LU << 19LU) constexpr
Definition at line 114 of file WSPIDevice.h.
CFG_ALT_MODE_EIGHT_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_MODE_EIGHT_LINES = (4LU << 16LU) constexpr
Definition at line 112 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::read(), and AP_FlashIface_JEDEC::start_xip_mode().
CFG_ALT_MODE_FOUR_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_MODE_FOUR_LINES = (3LU << 16LU) constexpr
Definition at line 111 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::read(), and AP_FlashIface_JEDEC::start_xip_mode().
CFG_ALT_MODE_MASK
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_MODE_MASK = (7LU << 16LU) constexpr
Definition at line 107 of file WSPIDevice.h.
CFG_ALT_MODE_NONE
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_MODE_NONE = (0LU << 16LU) constexpr
Definition at line 108 of file WSPIDevice.h.
CFG_ALT_MODE_ONE_LINE
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_MODE_ONE_LINE = (1LU << 16LU) constexpr
Definition at line 109 of file WSPIDevice.h.
CFG_ALT_MODE_TWO_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_MODE_TWO_LINES = (2LU << 16LU) constexpr
Definition at line 110 of file WSPIDevice.h.
CFG_ALT_SIZE_16
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_SIZE_16 = (1LU << 20LU) constexpr
Definition at line 118 of file WSPIDevice.h.
CFG_ALT_SIZE_24
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_SIZE_24 = (2LU << 20LU) constexpr
Definition at line 119 of file WSPIDevice.h.
CFG_ALT_SIZE_32
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_SIZE_32 = (3LU << 20LU) constexpr
Definition at line 120 of file WSPIDevice.h.
CFG_ALT_SIZE_8
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_SIZE_8 = (0LU << 20LU) constexpr
Definition at line 117 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::read(), and AP_FlashIface_JEDEC::start_xip_mode().
CFG_ALT_SIZE_MASK
constexpr uint32_t AP_HAL::WSPI::CFG_ALT_SIZE_MASK = (3LU << 20LU) constexpr
Definition at line 116 of file WSPIDevice.h.
CFG_CMD_MODE_EIGHT_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_CMD_MODE_EIGHT_LINES = (4LU << 0LU) constexpr
Definition at line 88 of file WSPIDevice.h.
CFG_CMD_MODE_FOUR_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_CMD_MODE_FOUR_LINES = (3LU << 0LU) constexpr
Definition at line 87 of file WSPIDevice.h.
CFG_CMD_MODE_MASK
constexpr uint32_t AP_HAL::WSPI::CFG_CMD_MODE_MASK = (7LU << 0LU) constexpr
Definition at line 83 of file WSPIDevice.h.
CFG_CMD_MODE_NONE
constexpr uint32_t AP_HAL::WSPI::CFG_CMD_MODE_NONE = (0LU << 0LU) constexpr
Definition at line 84 of file WSPIDevice.h.
CFG_CMD_MODE_ONE_LINE
constexpr uint32_t AP_HAL::WSPI::CFG_CMD_MODE_ONE_LINE = (1LU << 0LU) constexpr
Definition at line 85 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::configure_device(), AP_FlashIface_JEDEC::detect_device(), AP_FlashIface_JEDEC::read(), AP_FlashIface_JEDEC::read_reg(), AP_FlashIface_JEDEC::reset_device(), AP_FlashIface_JEDEC::send_cmd(), AP_FlashIface_JEDEC::start_erase_offset(), AP_FlashIface_JEDEC::start_mass_erase(), AP_FlashIface_JEDEC::start_program_offset(), AP_FlashIface_JEDEC::start_xip_mode(), and AP_FlashIface_JEDEC::write_reg().
CFG_CMD_MODE_TWO_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_CMD_MODE_TWO_LINES = (2LU << 0LU) constexpr
Definition at line 86 of file WSPIDevice.h.
CFG_CMD_SIZE_8
constexpr uint32_t AP_HAL::WSPI::CFG_CMD_SIZE_8 = (0LU << 4LU) constexpr
Definition at line 91 of file WSPIDevice.h.
CFG_CMD_SIZE_MASK
constexpr uint32_t AP_HAL::WSPI::CFG_CMD_SIZE_MASK = (3LU << 4LU) constexpr
Definition at line 90 of file WSPIDevice.h.
CFG_DATA_DDR
constexpr uint32_t AP_HAL::WSPI::CFG_DATA_DDR = (1LU << 27LU) constexpr
Definition at line 129 of file WSPIDevice.h.
CFG_DATA_MODE_EIGHT_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_DATA_MODE_EIGHT_LINES = (4LU << 24LU) constexpr
Definition at line 127 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::read(), and AP_FlashIface_JEDEC::start_xip_mode().
CFG_DATA_MODE_FOUR_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_DATA_MODE_FOUR_LINES = (3LU << 24LU) constexpr
Definition at line 126 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::read(), and AP_FlashIface_JEDEC::start_xip_mode().
CFG_DATA_MODE_MASK
constexpr uint32_t AP_HAL::WSPI::CFG_DATA_MODE_MASK = (7LU << 24LU) constexpr
Definition at line 122 of file WSPIDevice.h.
CFG_DATA_MODE_NONE
constexpr uint32_t AP_HAL::WSPI::CFG_DATA_MODE_NONE = (0LU << 24LU) constexpr
Definition at line 123 of file WSPIDevice.h.
CFG_DATA_MODE_ONE_LINE
constexpr uint32_t AP_HAL::WSPI::CFG_DATA_MODE_ONE_LINE = (1LU << 24LU) constexpr
Definition at line 124 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::configure_device(), AP_FlashIface_JEDEC::detect_device(), AP_FlashIface_JEDEC::read_reg(), AP_FlashIface_JEDEC::start_program_offset(), and AP_FlashIface_JEDEC::write_reg().
CFG_DATA_MODE_TWO_LINES
constexpr uint32_t AP_HAL::WSPI::CFG_DATA_MODE_TWO_LINES = (2LU << 24LU) constexpr
Definition at line 125 of file WSPIDevice.h.
CFG_SIOO
constexpr uint32_t AP_HAL::WSPI::CFG_SIOO = (1LU << 31LU) constexpr
Definition at line 131 of file WSPIDevice.h.
Referenced by AP_FlashIface_JEDEC::start_xip_mode().