APM:Libraries: AP Namespace Reference
AP Namespace Reference
Classes
class PerfInfo
Functions
AC_Avoid * ac_avoid ()
AP_OADatabase * oadatabase ()
AP_OAPathPlanner * ap_oapathplanner ()
AC_Fence * fence ()
AC_PrecLand * ac_precland ()
AC_Sprayer * sprayer ()
AP_AdvancedFailsafe * advancedfailsafe ()
AP_AHRS & ahrs ()
AP_Airspeed * airspeed ()
AP_Arming & arming ()
AP_Baro & baro ()
AP_BattMonitor & battery ()
AP_Beacon * beacon ()
AP_BoardConfig * boardConfig (void)
AP_Button & button ()
AP_Camera * camera ()
AP_RunCam * runcam ()
const AP_FWVersion & fwversion ()
Compass & compass ()
AP_CustomRotations & custom_rotations ()
AP_DAL & dal ()
AP_ExternalControl * externalcontrol ()
AP_Filesystem & FS ()
AP_Follow & follow ()
AP_Frsky_SPort * frsky_sport ()
AP_Frsky_SPort_Passthrough * frsky_passthrough_telem ()
AP_Frsky_Telem * frsky_telem ()
AP_Generator * generator ()
AP_GPS & gps ()
AP_Gripper & gripper ()
AP_Hott_Telem * hott_telem ()
AP_ICEngine * ice ()
AP_InertialSensor & ins ()
AP_InternalError & internalerror ()
AP_Logger & logger ()
AP_Mission * mission ()
AP_Motors * motors ()
AP_Mount * mount ()
AP_MSP * msp ()
AP_Networking & network ()
AP_Notify & notify ()
AP_OpticalFlow * opticalflow ()
AP_OSD * osd ()
AP_Parachute * parachute ()
AP_Param * param ()
AP_Rally * rally ()
RangeFinder * rangefinder ()
RCMapper * rcmap ()
AP_RCProtocol & RC ()
AP_RCProtocol_CRSF * crsf ()
AP_RCProtocol_GHST * ghost ()
AP_Spektrum_Telem * spektrum_telem ()
AP_Relay * relay ()
AP_RPM * rpm ()
AP_RSSI * rssi ()
AP_RTC & rtc ()
AP_Scheduler & scheduler ()
AP_SerialManager & serialmanager ()
AP_ServoRelayEvents * servorelayevents ()
AP_Stats * stats ()
AP_Vehicle * vehicle ()
AP_VideoTX & vtx ()
AP_WheelEncoder * wheelencoder ()
AP_Winch * winch ()
AP_WindVane * windvane ()
AP_MotorsUGV * motors_ugv ()
Function Documentation
ac_avoid()
AC_Avoid * AP::ac_avoid ()
Definition at line 1483 of file AC_Avoid.cpp.
Referenced by AC_Loiter::calc_desired_velocity(), RC_Channel::do_aux_function_avoid_proximity(), and AR_PosControl::update().
ac_precland()
AC_PrecLand * AP::ac_precland ()
Definition at line 827 of file AC_PrecLand.cpp.
Referenced by AC_PrecLand_StateMachine::get_failsafe_actions(), AC_PrecLand_StateMachine::get_target_lost_actions(), AC_PrecLand_StateMachine::init(), AC_PrecLand_StateMachine::retry_landing(), and AC_PrecLand_StateMachine::update().
advancedfailsafe()
AP_AdvancedFailsafe * AP::advancedfailsafe ()
Definition at line 494 of file AP_AdvancedFailsafe.cpp.
Referenced by GCS_MAVLINK::capabilities(), and GCS_MAVLINK::handle_flight_termination().
ahrs()
AP_AHRS & AP::ahrs ()
Definition at line 3558 of file AP_AHRS.cpp.
Referenced by AP_InertialSensor::_calculate_trim(), AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_OpticalFlow_Calibrator::add_sample(), AC_Avoid::adjust_velocity_polygon(), AC_Avoid::adjust_velocity_proximity(), AC_Avoid::adjust_velocity_z(), AR_WPNav::advance_wp_target_along_track(), AP_InertialSensor_Backend::apply_gyro_filters(), AP_OAPathPlanner::avoidance_thread(), AP_Spektrum_Telem::calc_airspeed(), AP_Spektrum_Telem::calc_altitude(), AP_Spektrum_Telem::calc_attandmag(), AP_Rally::calc_best_rally_or_home_location(), AC_Loiter::calc_desired_velocity(), AP_Frsky_Backend::calc_gps_position(), AP_Frsky_SPort_Passthrough::calc_home(), AP_OABendyRuler::calc_margin_from_circular_fence(), AP_Frsky_Backend::calc_nav_alt(), AC_Autorotation::calc_speed_forward(), AP_Frsky_SPort_Passthrough::calc_velandyaw(), AP_Frsky_SPort_Passthrough::calc_wind(), AP_GPS_Backend::calculate_moving_base_yaw(), AR_PivotTurn::check_activation(), AP_RCTelemetry::check_ekf_status(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), AC_PrecLand::check_target_status(), AP_Arming::compass_checks(), AC_PrecLand::construct_pos_meas_using_rangefinder(), RC_Channel::do_aux_function(), AP_OSD_Screen::draw_altitude(), AP_OSD_Screen::draw_aspeed(), AP_OSD_Screen::draw_compass(), AP_OSD_Screen::draw_gspeed(), AP_OSD_Screen::draw_heading(), AP_OSD_Screen::draw_home(), AP_OSD_Screen::draw_horizon(), AP_OSD_Screen::draw_pitch_angle(), AP_OSD_Screen::draw_roll_angle(), AP_OSD_Screen::draw_sidebars(), AP_OSD_Screen::draw_vspeed(), AP_OSD_Screen::draw_waypoint(), AP_OSD_Screen::draw_wind(), Location::get_alt_cm(), AP_Mount_Backend::get_angle_target_to_home(), AP_Mount_Backend::get_angle_target_to_location(), AP_Mount_Backend::MountTarget::get_bf_yaw(), AP_Mount_Backend::MountTarget::get_ef_yaw(), AR_AttitudeControl::get_forward_speed(), AR_AttitudeControl::get_lat_accel(), AR_PosControl::get_pos_error(), AP_PitchController::get_rate_out(), AP_YawController::get_rate_out(), AR_AttitudeControl::get_sail_out_from_heel(), AP_YawController::get_servo_out(), AP_PitchController::get_servo_out(), AP_SteerController::get_steering_out_lat_accel(), AP_SteerController::get_steering_out_rate(), AR_AttitudeControl::get_steering_out_rate(), AR_WPNav::get_stopping_location(), SoaringController::get_target(), AP_Follow::get_target_dist_and_vel_ned(), AC_PrecLand::get_target_location(), AC_PrecLand::get_target_position_cm(), SoaringController::get_thermalling_radius(), AR_AttitudeControl::get_throttle_out_from_pitch(), AR_AttitudeControl::get_turn_rate_from_heading(), AP_Frsky_Backend::get_vspeed_ms(), AP_MSP_Telem_Backend::get_vspeed_ms(), AC_WPNav::get_wp_destination_loc(), AC_WeatherVane::get_yaw_out(), GCS_MAVLINK::global_position_int_relative_alt(), AR_PosControl::handle_ekf_xy_reset(), Compass::init(), AR_PosControl::init(), AR_PosControl::init_ekf_xy_reset(), SoaringController::init_thermalling(), AC_AttitudeControl_Sub::input_euler_angle_roll_pitch_slew_yaw(), AP_Frsky_SPort_Passthrough::is_packet_ready(), AP_InertialSensor_Backend::log_gyro_raw(), AP_OAPathPlanner::mission_avoidance(), AP_MSP_Telem_Backend::msp_process_out_attitude(), AC_AutoTune::position_ok(), AP_Camera_Backend::prep_mavlink_msg_camera_feedback(), AP_OADatabase::queue_push(), AP_WindVane::record_home_heading(), AC_PrecLand_StateMachine::retry_landing(), AC_PrecLand::run_estimator(), AC_PrecLand::run_output_prediction(), AP_Frsky_D::send(), AP_LTM_Telem::send_Aframe(), GCS_MAVLINK::send_ahrs(), GCS_MAVLINK::send_ahrs2(), GCS_MAVLINK::send_attitude(), AP_Mount_Siyi::send_attitude(), GCS_MAVLINK::send_attitude_quaternion(), GCS_MAVLINK::send_autopilot_state_for_gimbal_device(), AP_Hott_Telem::send_EAM(), AP_LTM_Telem::send_Gframe(), GCS_MAVLINK::send_global_position_int(), AP_Hott_Telem::send_GPS(), GCS_MAVLINK::send_high_latency2(), GCS_MAVLINK::send_local_position(), AP_Mount_Siyi::send_target_angles(), AP_Hott_Telem::send_Vario(), GCS_MAVLINK::send_vfr_hud(), AR_WPNav::set_desired_location_NED(), AR_WPNav::set_desired_location_NED(), AP_SmartRTL::set_home(), AP_DAL::set_takeoff_expected(), AP_DAL::start_frame(), AP_Camera_Backend::take_picture(), AP_OpticalFlow_Pixart::timer(), GCS_MAVLINK::try_send_message(), Compass::try_set_initial_location(), AC_Sprayer::update(), AP_OpticalFlow_Calibrator::update(), AP_WindVane::update(), AC_PrecLand_SITL::update(), AP_IRLock_SITL::update(), AP_SmartRTL::update(), Variometer::update(), AP_OABendyRuler::update(), AR_PosControl::update(), AR_WPNav::update(), AR_WPNav_OA::update(), AC_PrecLand::update(), AP_ICEngine::update(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_UPFLOW::update(), AP_MSP_Telem_Backend::update_airspeed(), AP_Mount_Servo::update_angle_outputs(), AP_WindVane::update_apparent_wind_dir_from_true(), SoaringController::update_cruising(), AP_WindVane_Home::update_direction(), AR_WPNav::update_distance_and_bearing_to_destination(), AP_Baro::update_field_elevation(), AP_MSP_Telem_Backend::update_flight_mode_str(), AP_MSP_Telem_Backend::update_home_pos(), AR_WPNav_OA::update_oa_distance_and_bearing_to_destination(), GCS::update_sensor_status_flags(), AP_OpticalFlow::update_state(), AP_OSD::update_stats(), SoaringController::update_thermalling(), AP_WindVane::update_true_wind_speed_and_direction(), AC_WPNav_OA::update_wpnav(), AC_PosControl::update_xy_controller(), AC_PosControl::update_z_controller(), GCS_MAVLINK::vfr_hud_climbrate(), and AP_Baro::wind_pressure_correction().
airspeed()
AP_Airspeed * AP::airspeed ()
Definition at line 955 of file AP_Airspeed.cpp.
Referenced by AP_AHRS::_airspeed_estimate(), AP_AHRS_Backend::airspeed_sensor_enabled(), AP_AHRS_Backend::airspeed_sensor_enabled(), AP_Spektrum_Telem::calc_airspeed(), RC_Channel::do_aux_function(), AP_AHRS::get_active_airspeed_index(), AP_DAL::init_sensors(), AP_MSP_Telem_Backend::msp_handle_airspeed(), AP_LTM_Telem::send_Sframe(), AP_DAL_Airspeed::start_frame(), and GCS::update_sensor_status_flags().
ap_oapathplanner()
AP_OAPathPlanner * AP::ap_oapathplanner ()
Definition at line 429 of file AP_OAPathPlanner.cpp.
arming()
AP_Arming & AP::arming ()
Definition at line 1954 of file AP_Arming.cpp.
Referenced by RC_Channel::do_aux_function(), RC_Channel::do_aux_function_armdisarm(), AP_Vehicle::is_crashed(), and GCS::update_sensor_status_flags().
baro()
AP_Baro & AP::baro ()
Definition at line 1146 of file AP_Baro.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration_baro(), HALSITL::SITL_State::_simulator_servos(), HALSITL::SITL_State::_update_airspeed(), AP_TempCalibration::apply_calibration(), AP_Arming::barometer_checks(), AP_Spektrum_Telem::calc_rpm(), AP_Spektrum_Telem::calc_temperature(), AP_AdvancedFailsafe::check_altlimit(), AP_OSD_Screen::draw_temp(), AP_OSD_Screen::draw_vspeed(), Thrust_Linearization::get_compensation_gain(), get_EAS2TAS(), AP_AHRS_Backend::get_EAS2TAS(), AP_AHRS::get_relative_position_D_home(), AP_Frsky_Backend::get_vspeed_ms(), AP_MSP_Telem_Backend::get_vspeed_ms(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_calibration_baro(), SITL::EFI_Hirth::init(), AP_TempCalibration::learn_calibration(), AP_MSP_Telem_Backend::msp_handle_baro(), AP_Hott_Telem::send_EAM(), SITL::EFI_Hirth::send_record1(), GCS_MAVLINK::send_scaled_pressure_instance(), AP_TempCalibration::setup_learning(), AP_DAL_Baro::start_frame(), AP_DAL::start_frame(), SITL::EFI_MegaSquirt::update(), AP_TECS::update_50hz(), AP_DAL_Baro::update_calibration(), AP_Airspeed::update_calibration(), SITL::EFI_Hirth::update_engine_model(), and GCS::update_sensor_status_flags().
battery()
AP_BattMonitor & AP::battery ()
Definition at line 1119 of file AP_BattMonitor.cpp.
Referenced by AP_Frsky_SPort_Passthrough::calc_batt(), AP_Spektrum_Telem::calc_batt_amps(), AP_Spektrum_Telem::calc_batt_mah(), AP_Spektrum_Telem::calc_batt_volts(), AP_Frsky_SPort_Passthrough::calc_param(), AP_Spektrum_Telem::calc_rpm(), AP_Compass_Backend::correct_field(), RC_Channel::do_aux_function(), AP_MotorsMulticopter::get_current_limit_max_throttle(), AP_Frsky_SPort_Passthrough::is_packet_ready(), AP_Motors6DOF::output_armed_stabilizing(), AP_Frsky_D::send(), AP_Frsky_SPort::send(), AP_Hott_Telem::send_EAM(), AP_LTM_Telem::send_Sframe(), GCS_MAVLINK::send_sys_status(), Thrust_Linearization::update_lift_max_from_batt_voltage(), GCS::update_sensor_status_flags(), and AP_OSD::update_stats().
beacon()
AP_Beacon * AP::beacon ()
Definition at line 428 of file AP_Beacon.cpp.
Referenced by AP_DAL::init_sensors().
boardConfig()
AP_BoardConfig * AP::boardConfig (void)
Definition at line 521 of file AP_BoardConfig.cpp.
Referenced by AP_InertialSensor_Backend::_publish_temperature(), and AP_Compass_Backend::rotate_field().
button()
AP_Button & AP::button ()
Definition at line 403 of file AP_Button.cpp.
Referenced by AP_Arming::system_checks().
camera()
AP_Camera * AP::camera ()
Definition at line 801 of file AP_Camera.cpp.
Referenced by AP_Relay::convert_params(), GCS_MAVLINK::handle_message(), and GCS_MAVLINK::try_send_message().
compass()
Compass & AP::compass ()
Definition at line 2237 of file AP_Compass.cpp.
Referenced by AP_AHRS::_active_EKF_type(), GCS_MAVLINK::_handle_command_preflight_calibration(), AP_AHRS::attitudes_consistent(), AP_Spektrum_Telem::calc_attandmag(), AP_Arming::compass_checks(), RC_Channel::do_aux_function(), loop(), AP_MSP_Telem_Backend::msp_handle_compass(), AP_AHRS::pre_arm_check(), GCS_MAVLINK::send_raw_imu(), GCS_MAVLINK::send_scaled_imu(), setup(), AP_DAL_Compass::start_frame(), GCS_MAVLINK::try_send_message(), AP_AHRS::update_orientation(), GCS::update_sensor_status_flags(), AP_Logger::Write_Compass(), and AP_Logger::Write_Compass_instance().
crsf()
AP_RCProtocol_CRSF * AP::crsf ()
Definition at line 684 of file AP_RCProtocol_CRSF.cpp.
custom_rotations()
AP_CustomRotations & AP::custom_rotations ()
Definition at line 154 of file AP_CustomRotations.cpp.
Referenced by Compass::init(), AP_AHRS::init(), TEST(), test_euler(), and test_euler().
dal()
AP_DAL & AP::dal ()
Definition at line 523 of file AP_DAL.cpp.
Referenced by AP_NavEKF_Source::align_inactive_sources(), NavEKF2::checkLaneSwitch(), NavEKF3::checkLaneSwitch(), NavEKF3::convert_parameters(), AP_NavEKF_Source::getPosZSource(), AP_NavEKF_Source::getYawSource(), NavEKF2::InitialiseFilter(), NavEKF3::InitialiseFilter(), AP_NavEKF_Source::pre_arm_check(), NavEKF3::pre_arm_check(), NavEKF2::pre_arm_check(), NavEKF2::requestYawReset(), NavEKF3::requestYawReset(), NavEKF2::resetGyroBias(), NavEKF3::resetGyroBias(), NavEKF2::resetHeightDatum(), NavEKF3::resetHeightDatum(), NavEKF3::setLatLng(), NavEKF2::setOriginLLH(), NavEKF3::setOriginLLH(), NavEKF3::setPosVelYawSourceSet(), NavEKF2::setTerrainHgtStable(), NavEKF3::setTerrainHgtStable(), NavEKF2::UpdateFilter(), NavEKF3::UpdateFilter(), NavEKF3::writeBodyFrameOdom(), NavEKF2::writeDefaultAirSpeed(), NavEKF3::writeDefaultAirSpeed(), NavEKF3::writeEulerYawAngle(), NavEKF2::writeExtNavData(), NavEKF3::writeExtNavData(), NavEKF2::writeExtNavVelData(), NavEKF3::writeExtNavVelData(), NavEKF2::writeOptFlowMeas(), NavEKF3::writeOptFlowMeas(), and NavEKF3::writeWheelOdom().
externalcontrol()
AP_ExternalControl * AP::externalcontrol ()
Definition at line 17 of file AP_ExternalControl.cpp.
fence()
AC_Fence * AP::fence ()
Definition at line 785 of file AC_Fence.cpp.
Referenced by AC_Avoid::adjust_velocity_z(), AP_Arming::arm(), AP_Frsky_SPort_Passthrough::calc_ap_status(), GCS_MAVLINK::capabilities(), AP_AdvancedFailsafe::check(), AP_Arming::disarm(), GCS::update_send(), GCS::update_sensor_status_flags(), and AP_Landing::verify_abort_landing().
follow()
AP_Follow & AP::follow ()
Definition at line 537 of file AP_Follow.cpp.
frsky_passthrough_telem()
AP_Frsky_SPort_Passthrough * AP::frsky_passthrough_telem ()
Definition at line 966 of file AP_Frsky_SPort_Passthrough.cpp.
frsky_sport()
AP_Frsky_SPort * AP::frsky_sport ()
Definition at line 474 of file AP_Frsky_SPort.cpp.
frsky_telem()
AP_Frsky_Telem * AP::frsky_telem ()
Definition at line 155 of file AP_Frsky_Telem.cpp.
Referenced by GCS::send_textv().
FS()
AP_Filesystem & AP::FS ()
Definition at line 413 of file AP_Filesystem.cpp.
Referenced by HALSITL::UARTDriver::_begin(), ChibiOS::Scheduler::_io_thread(), ChibiOS::Storage::_save_backup(), ChibiOS::Storage::_storage_open(), ChibiOS::Storage::_timer_tick(), ap_networking_printf(), apfs_fclose(), apfs_fflush(), apfs_fgets(), apfs_fopen(), apfs_fprintf(), apfs_fputs(), apfs_fread(), apfs_freopen(), apfs_fseek(), apfs_ftell(), apfs_fwrite(), apfs_getc(), apfs_remove(), AP_Logger::check_crash_dump_save(), SITL::XPlane::check_reload_dref(), GCS_MAVLINK_InProgress::check_tasks(), AP_Networking::SendFile::close(), AP_OSD_Screen::draw_callsign(), GCS_MAVLINK::ftp_list_dir(), GCS_MAVLINK::ftp_worker(), GCS_MAVLINK::gen_dir_entry(), AP_BoardConfig::init(), AP_ToneAlarm::init(), SITL::XPlane::load_dref_map(), AP_OSD_Backend::load_font_data(), SITL::Frame::load_frame_params(), AP_JSON::load_json(), HALSITL::SITL_State::lookup_location(), read_file(), ChibiOS::Scheduler::reboot(), sdcard_retry(), AP_Networking::sendfile_check(), setup(), and write_file().
fwversion()
const AP_FWVersion & AP::fwversion ()
Definition at line 5 of file AP_FWVersion.cpp.
Referenced by AP_RCTelemetry::init(), AP_MSP_Telem_Backend::msp_process_out_board_info(), AP_MSP_Telem_Backend::msp_process_out_build_info(), LoggerMessageWriter_WriteSysInfo::process(), GCS_MAVLINK::send_autopilot_version(), GCS_MAVLINK::send_banner(), AP_Vehicle::setup(), TEST(), and AP_Logger_Backend::Write_VER().
generator()
AP_Generator * AP::generator ()
Definition at line 185 of file AP_Generator.cpp.
ghost()
AP_RCProtocol_GHST * AP::ghost ()
Definition at line 458 of file AP_RCProtocol_GHST.cpp.
gps()
AP_GPS & AP::gps ()
Definition at line 2442 of file AP_GPS.cpp.
Referenced by AP_AHRS::_active_EKF_type(), AP_AHRS::_airspeed_estimate(), AP_Arming::arm_checks(), AP_Baro::arming_checks(), AP_Frsky_SPort::calc_gps_latlng(), AP_Spektrum_Telem::calc_gps_location(), AP_Spektrum_Telem::calc_gps_status(), AP_Frsky_SPort_Passthrough::calc_gps_status(), AP_AdvancedFailsafe::check(), AP_AdvancedFailsafe::check_altlimit(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), RC_Channel::do_aux_function(), AP_OSD_Screen::draw_gps_latitude(), AP_OSD_Screen::draw_gps_longitude(), AP_OSD_Screen::draw_hdop(), AP_OSD_Screen::draw_sats(), AR_AttitudeControl::get_forward_speed(), AP_AHRS::get_relative_position_D_home(), GCS_MAVLINK::handle_message(), GCS_MAVLINK::handle_serial_control(), AP_AdvancedFailsafe::max_range_update(), AP_MSP_Telem_Backend::msp_handle_gps(), AP_Frsky_D::send(), AP_Frsky_SPort::send(), AP_LTM_Telem::send_Gframe(), AP_Hott_Telem::send_GPS(), setup(), AP_DAL_GPS::start_frame(), GCS_MAVLINK::try_send_message(), AP_Landing::type_slope_verify_land(), GCS::update_sensor_status_flags(), and GCS_MAVLINK::vfr_hud_airspeed().
gripper()
AP_Gripper & AP::gripper ()
Definition at line 171 of file AP_Gripper.cpp.
Referenced by AP_Vehicle::setup().
hott_telem()
AP_Hott_Telem * AP::hott_telem ()
Definition at line 449 of file AP_Hott_Telem.cpp.
ice()
AP_ICEngine * AP::ice ()
Definition at line 657 of file AP_ICEngine.cpp.
Referenced by AP_Relay::convert_params().
ins()
AP_InertialSensor & AP::ins ()
Definition at line 2780 of file AP_InertialSensor.cpp.
Referenced by AP_AHRS::_get_primary_IMU_index(), AP_AHRS::_getCorrectedDeltaVelocityNED(), GCS_MAVLINK::_handle_command_preflight_calibration(), AP_TECS::_update_speed(), AP_Frsky_SPort_Passthrough::calc_ap_status(), AC_PrecLand::construct_pos_meas_using_rangefinder(), RC_Channel::do_aux_function(), AP_DAL::ekf_low_time_remaining(), AP_AHRS::get_accel(), AP_AHRS::get_gyro_latest(), AP_AHRS_Backend::get_primary_accel_index(), AP_AHRS_Backend::get_primary_gyro_index(), AP_YawController::get_servo_out(), AP_AHRS::get_vibration(), GCS_MAVLINK::handle_command_ack(), AP_DAL_InertialSensor::handle_message(), AP_SerialManager::init(), AP_TempCalibration::learn_calibration(), AP_Scheduler::loop(), AP_Compass_AK09916::probe_ICM20948_I2C(), AP_Compass_AK09916::probe_ICM20948_SPI(), AC_PrecLand::run_output_prediction(), GCS_MAVLINK::send_banner(), GCS_MAVLINK::send_raw_imu(), GCS_MAVLINK::send_scaled_imu(), GCS_MAVLINK::send_vibration(), setup(), AP_DAL_InertialSensor::start_frame(), AP_DAL::start_frame(), AP_OpticalFlow_Pixart::timer(), AP_AHRS::update(), Variometer::update(), AP_AutoTune::update(), SITL::Gimbal::update(), AP_AHRS::update_orientation(), and GCS::update_sensor_status_flags().
internalerror()
AP_InternalError & AP::internalerror ()
Definition at line 113 of file AP_InternalError.cpp.
Referenced by ChibiOS::Scheduler::_monitor_thread(), ChibiOS::Scheduler::check_stack_free(), constrain_value_line(), AP_InternalError::error(), AP_Vehicle::loop(), GCS_MAVLINK::send_sys_status(), AP_Arming::system_checks(), and GCS_MAVLINK::system_status().
logger()
AP_Logger & AP::logger ()
Definition at line 1740 of file AP_Logger.cpp.
Referenced by ChibiOS::Scheduler::_monitor_thread(), AP_InertialSensor_Invensense::_read_fifo(), AP_TECS::_update_pitch(), AP_TECS::_update_throttle_with_airspeed(), AP_Arming::arm(), SITL::Blimp::calculate_forces(), AP_GPS_Backend::calculate_moving_base_yaw(), SCurve::calculate_path(), GCS_MAVLINK::handle_command_int(), GCS_MAVLINK::handle_command_long(), GCS_MAVLINK::handle_message(), AP_Follow::handle_msg(), GCS_MAVLINK::handle_radio_status(), GCS_MAVLINK::handle_timesync(), AP_RCProtocol_Backend::log_data(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_InertialSensor_Backend::log_register_change(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_UBLOX::log_rxm_rawx(), ChibiOS::Util::log_stack_info(), LoggerMessageWriter_DFLogStart::process(), Compass::read(), RC_Channels::read_aux_all(), ChibiOS::Scheduler::reboot(), SITL::JSON_Master::receive(), SITL::AirSim::recv_fdm(), SITL::JSON::recv_fdm(), LoggerMessageWriter_DFLogStart::reset(), HAL_SITL::run(), RC_Channel::run_aux_function(), AP_Vehicle::scheduler_delay_callback(), AP_AHRS::set_home(), AP_Relay::set_pin_by_instance(), AP_Rally::set_rally_point_with_index(), AP_NavEKF_Source::setPosVelYawSourceSet(), AP_Logger_RateLimiter::should_log(), AP_DAL::start_frame(), AP_Compass_MMC3416::timer(), ChibiOS::Scheduler::try_force_mutex(), AP_WindVane::update(), AP_Baro_ICM20789::update(), AP_InertialSensor_Invensense::update(), Variometer::update(), SITL::Blimp::update(), AP_AutoTune::update(), AP_Airspeed::update(), AP_Baro::update(), AP_GPS::update(), SoaringController::update_cruising(), AP_TECS::update_pitch_throttle(), GCS_MAVLINK::update_send(), GCS::update_sensor_status_flags(), SoaringController::update_thermalling(), NavEKF3_core::updateMovementCheck(), NavEKF3_core::verifyTiltErrorVariance(), AP_GPS_Backend::Write_AP_Logger_Log_Startup_messages(), AP_GPS_NMEA::Write_AP_Logger_Log_Startup_messages(), and AP_GPS_UBLOX::Write_AP_Logger_Log_Startup_messages().
mission()
AP_Mission * AP::mission ()
Referenced by AP_Frsky_SPort_Passthrough::calc_waypoint(), AP_AdvancedFailsafe::check(), GCS_MAVLINK::handle_common_mission_message(), AP_Frsky_SPort_Passthrough::is_packet_ready(), LoggerMessageWriter_WriteEntireMission::process(), GCS_MAVLINK::send_high_latency2(), AP_Hott_Telem::send_Vario(), AP_Arming::terrain_database_required(), GCS_MAVLINK::try_send_mission_message(), and GCS::update_send().
motors()
AP_Motors * AP::motors ()
Definition at line 305 of file AP_Motors_Class.cpp.
Referenced by AP_InertialSensor::init(), and AC_Autorotation::set_collective().
motors_ugv()
AP_MotorsUGV * AP::motors_ugv ()
Definition at line 1165 of file AP_MotorsUGV.cpp.
Referenced by AP_Relay::convert_params().
mount()
AP_Mount * AP::mount ()
Definition at line 1064 of file AP_Mount.cpp.
Referenced by RC_Channel::do_aux_function(), AP_Camera_Backend::get_gimbal_device_id(), GCS_MAVLINK::handle_command_do_set_roi(), and GCS_MAVLINK::handle_param_value().
msp()
AP_MSP * AP::msp ()
Definition at line 238 of file AP_MSP.cpp.
Referenced by AP_MSP_Telem_Backend::displaying_stats_screen(), AP_MSP_Telem_Backend::enable_warnings(), AP_MSP_Telem_Backend::hide_osd_items(), AP_MSP_Telem_DJI::hide_osd_items(), AP_MSP_Telem_DJI::is_scheduler_enabled(), AP_MSP_Telem_DisplayPort::msp_process_out_fc_variant(), AP_MSP_Telem_Backend::msp_process_out_name(), AP_MSP_Telem_Backend::msp_process_out_osd_config(), AP_MSP_Telem_Backend::msp_process_out_raw_gps(), AP_MSP_Telem_Backend::update_flight_mode_str(), and AP_MSP_Telem_DJI::update_home_pos().
network()
AP_Networking & AP::network ()
Definition at line 414 of file AP_Networking.cpp.
Referenced by ap_networking_printf(), and network().
notify()
AP_Notify & AP::notify ()
Definition at line 577 of file AP_Notify.cpp.
Referenced by AP_MSP_Telem_DJI::get_osd_flight_mode_bitmask(), AP_MSP_Telem_Backend::hide_osd_items(), AP_MSP_Telem_DJI::hide_osd_items(), AP_MSP::loop(), AP_MSP_Telem_Backend::msp_process_out_status(), MMLPlayer::next_action(), and MMLPlayer::start_note().
oadatabase()
AP_OADatabase * AP::oadatabase ()
Definition at line 479 of file AP_OADatabase.cpp.
Referenced by AP_OABendyRuler::calc_margin_from_object_database().
opticalflow()
AP_OpticalFlow * AP::opticalflow ()
Definition at line 316 of file AP_OpticalFlow.cpp.
Referenced by RC_Channel::do_aux_function(), AP_MSP_Telem_Backend::msp_handle_opflow(), AP_DAL::start_frame(), and GCS::update_sensor_status_flags().
osd()
AP_OSD * AP::osd ()
Definition at line 663 of file AP_OSD.cpp.
Referenced by AP_RunCam::disable_osd(), AP_MSP_Telem_Backend::displaying_stats_screen(), AP_RunCam::enable_osd(), AP_MSP_Telem_DJI::get_rssi(), AP_MSP_Telem_Backend::hide_osd_items(), AP_MSP::loop(), AP_MSP_Telem_DJI::msp_process_out_esc_sensor_data(), AP_MSP_Telem_Backend::msp_process_out_name(), AP_MSP_Telem_Backend::msp_process_out_osd_config(), AP_MSP_Telem_Backend::msp_process_out_raw_gps(), AP_MSP_Telem_DJI::update_airspeed(), AP_MSP_Telem_DJI::update_battery_state(), AP_MSP_Telem_Backend::update_flight_mode_str(), AP_MSP_Telem_DJI::update_gps_state(), AP_MSP_Telem_DJI::update_home_pos(), AP_RunCam::update_osd(), and AP_MSP::update_osd_item_settings().
parachute()
AP_Parachute * AP::parachute ()
Definition at line 267 of file AP_Parachute.cpp.
Referenced by AP_Relay::convert_params(), AP_Arming::system_checks(), and AP_ICEngine::update().
param()
AP_Param * AP::param ()
Definition at line 442 of file AP_Param.cpp.
rally()
AP_Rally * AP::rally ()
Definition at line 192 of file AP_Rally.cpp.
Referenced by GCS_MAVLINK::capabilities(), and GCS::update_send().
rangefinder()
RangeFinder * AP::rangefinder ()
Definition at line 908 of file AP_RangeFinder.cpp.
Referenced by AP_DAL_RangeFinder::AP_DAL_RangeFinder(), AP_DAL_RangeFinder::ground_clearance_cm_orient(), GCS_MAVLINK::handle_distance_sensor(), AP_DAL::init_sensors(), AP_DAL_RangeFinder::max_distance_cm_orient(), AP_MSP_Telem_Backend::msp_handle_rangefinder(), and AP_DAL_RangeFinder::start_frame().
RC()
AP_RCProtocol & AP::RC ()
Definition at line 593 of file AP_RCProtocol.cpp.
Referenced by HALSITL::Scheduler::_run_io_procs(), ChibiOS::RCInput::_timer_tick(), ESP32::RCInput::_timer_tick(), Linux::RCInput_RCProtocol::_timer_tick(), AP_IOMCU_FW::handle_code_write(), AP_SerialManager::init(), ChibiOS::RCInput::init(), ESP32::RCInput::init(), Linux::RCInput_RCProtocol::init(), ChibiOS::RCInput::rc_bind(), AP_IOMCU_FW::rcin_serial_init(), AP_IOMCU_FW::rcin_serial_update(), AP_IOMCU_FW::rcin_update(), and setup().
rcmap()
RCMapper * AP::rcmap ()
Definition at line 75 of file AP_RCMapper.cpp.
Referenced by AP_RunCam::map_rc_input_to_event().
relay()
AP_Relay * AP::relay ()
Definition at line 684 of file AP_Relay.cpp.
Referenced by AP_Parachute::arming_checks(), AP_MotorsUGV::output_throttle(), AP_MotorsUGV::pre_arm_check(), AP_ICEngine::set_ignition(), AP_ICEngine::set_starter(), AP_Arming::system_checks(), AP_Parachute::update(), and AP_ServoRelayEvents::update_events().
rpm()
AP_RPM * AP::rpm ()
Definition at line 312 of file AP_RPM.cpp.
Referenced by AP_Spektrum_Telem::calc_rpm(), AP_Frsky_Backend::calc_rpm(), AP_Frsky_SPort_Passthrough::calc_rpm(), AP_Frsky_SPort_Passthrough::is_packet_ready(), AP_Frsky_SPort::send(), AP_Hott_Telem::send_EAM(), AP_Arming::system_checks(), AP_ICEngine::update(), and AP_ICEngine::update_idle_governor().
rssi()
AP_RSSI * AP::rssi ()
Definition at line 273 of file AP_RSSI.cpp.
Referenced by AP_MSP_Telem_Backend::get_rssi(), and AP_MSP_Telem_DJI::get_rssi().
rtc()
AP_RTC & AP::rtc ()
Definition at line 308 of file AP_RTC.cpp.
Referenced by AP_Spektrum_Telem::calc_gps_status(), AP_Logger_Block::get_log_info(), AP_MSP_Telem_Backend::hide_osd_items(), AP_BoardConfig::init(), loop(), AP_MSP_Telem_Backend::msp_process_out_rtc(), AP_Hott_Telem::send_GPS(), GCS_MAVLINK::send_system_time(), setup(), AP_Logger_Block::start_new_log(), AP_Stats::update(), AP_Mount_Siyi::update(), and AP_GPS::update_instance().
runcam()
AP_RunCam * AP::runcam ()
Definition at line 1061 of file AP_RunCam.cpp.
Referenced by RC_Channel::do_aux_function_runcam_control(), and RC_Channel::do_aux_function_runcam_osd_control().
scheduler()
AP_Scheduler & AP::scheduler ()
Definition at line 536 of file AP_Scheduler.cpp.
Referenced by AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AC_AttitudeControl_Heli::AC_AttitudeControl_Heli(), AC_AttitudeControl_Multi::AC_AttitudeControl_Multi(), AC_AutoTune_Heli::dwell_test_run(), AP_YawController::get_rate_out(), AC_PrecLand::init(), SRV_Channels::init(), AC_PosControl::init_xy_controller(), AC_PosControl::init_z_controller(), AC_PosControl::is_active_xy(), AC_PosControl::is_active_z(), AC_AttitudeControl::max_rate_step_bf_pitch(), AC_AttitudeControl::max_rate_step_bf_roll(), AC_AttitudeControl::max_rate_step_bf_yaw(), AP_Filesystem_Sys::open(), GCS::out_of_time(), LoggerMessageWriter::out_of_time_for_writing_messages(), LoggerMessageWriter_DFLogStart::out_of_time_for_writing_messages_df(), AC_AutoTune_Heli::rate_ff_test_run(), GCS_MAVLINK::send_sys_status(), GCS_MAVLINK::set_ap_message_interval(), AC_AttitudeControl_Heli::set_inverted_flight(), SRV_Channels::set_output_pwm_chan_timeout(), AP_Vehicle::setup(), AP_Logger_RateLimiter::should_log(), AP_AutoTune::start(), AP_Arming::system_checks(), AP_ICEngine::throttle_override(), AC_AutoTune_Multi::twitch_test_run(), AP_ICEngine::update_idle_governor(), AP::PerfInfo::update_logging(), AC_PosControl::update_xy_controller(), and AC_PosControl::update_z_controller().
serialmanager()
AP_SerialManager & AP::serialmanager ()
Definition at line 868 of file AP_SerialManager.cpp.
Referenced by AP_Beacon_Marvelmind::AP_Beacon_Backend(), AP_RCProtocol_CRSF::AP_RCProtocol_CRSF(), AP_OpticalFlow_CXOF::detect(), AP_OpticalFlow_UPFLOW::detect(), RangeFinder::detect_instance(), GCS::get_channel_from_port_number(), GCS_MAVLINK::handle_serial_control(), AP_LTM_Telem::init(), AP_MSP::init(), AP_Networking::init(), AP_SmartAudio::init(), AP_Mount_Alexmos::init(), AP_Mount_Siyi::init(), AP_Mount_SToRM32_serial::init(), AP_Spektrum_Telem::init(), AP_Frsky_Telem::init(), GCS_MAVLINK::init(), AP_Hott_Telem::init(), AP_Generator_IE_FuelCell::init(), AP_RangeFinder_Backend_Serial::init_serial(), AP_RangeFinder_Backend_Serial::initial_baudrate(), AP_Arming::serial_protocol_checks(), GCS::setup_console(), GCS::setup_uarts(), and GCS::update_passthru().
servorelayevents()
AP_ServoRelayEvents * AP::servorelayevents ()
Definition at line 204 of file AP_ServoRelayEvents.cpp.
spektrum_telem()
AP_Spektrum_Telem * AP::spektrum_telem ()
Definition at line 646 of file AP_Spektrum_Telem.cpp.
Referenced by GCS::send_textv().
sprayer()
AC_Sprayer * AP::sprayer ()
Definition at line 198 of file AC_Sprayer.cpp.
stats()
AP_Stats * AP::stats (void)
Definition at line 153 of file AP_Stats.cpp.
Referenced by AP_OSD_Screen::draw_flightime(), AP_Hott_Telem::send_EAM(), and AP_MSP_Telem_DJI::update_flight_mode_str().
vehicle()
AP_Vehicle * AP::vehicle ()
Definition at line 1119 of file AP_Vehicle.cpp.
Referenced by GCS_MAVLINK::_set_mode_common(), AP_Frsky_Telem::AP_Frsky_Telem(), AP_Frsky_SPort_Passthrough::calc_attiandrng(), AP_Frsky_SPort_Passthrough::calc_waypoint(), AP_OSD_Screen::draw_horizon(), AP_Frsky_MAVliteMsgHandler::handle_command_do_set_mode(), AP_Frsky_MAVliteMsgHandler::handle_command_preflight_reboot(), GCS_MAVLINK::handle_preflight_reboot(), AP_Scheduler::init(), GCS_MAVLINK::send_autopilot_state_for_gimbal_device(), GCS_MAVLINK::send_mission_current(), and AP_DAL::start_frame().
vtx()
AP_VideoTX & AP::vtx ()
Definition at line 550 of file AP_VideoTX.cpp.
Referenced by AP_SmartAudio::ignore_crc(), AP_SmartAudio::init(), AP_SmartAudio::loop(), AP_SmartAudio::parse_response_buffer(), RC_Channel::read_aux(), AP_SmartAudio::send_request(), AP_SmartAudio::update_vtx_params(), and AP_SmartAudio::update_vtx_settings().
wheelencoder()
AP_WheelEncoder * AP::wheelencoder ()
Definition at line 360 of file AP_WheelEncoder.cpp.
Referenced by AP_DAL::start_frame().
winch()
AP_Winch * AP::winch ()
Definition at line 179 of file AP_Winch.cpp.
windvane()
AP_WindVane * AP::windvane ()
Definition at line 494 of file AP_WindVane.cpp.