APM:Libraries: AP_HAL Namespace Reference
AP_HAL Namespace Reference
Namespaces
namespace WSPI
Classes
class AnalogIn
class AnalogSource
class BetterStream
class BinarySemaphore
struct CANFrame
class CANIface
class Device
class DigitalSource
class DSP
class Flash
class GPIO
class HAL
class I2CDevice
class I2CDeviceManager
class OpticalFlow
class OwnPtr
class PWMSource
class RCInput
class RCOutput
class Scheduler
class Semaphore
class SPIDevice
class SPIDeviceManager
class Storage
class UARTDriver
class Util
class WSPIDevice
class WSPIDeviceManager
Typedefs
typedef void(* Proc) (void)
Enumerations
enum SPIDeviceType { SPIDevice_Type = -1 }
Functions
FUNCTOR_TYPEDEF (MemberProc, void)
const HAL & get_HAL ()
HAL & get_HAL_mutable ()
void init ()
void panic (const char *errormsg,...) FMT_PRINTF(1
uint16_t micros16 ()
uint32_t micros ()
uint32_t millis ()
uint16_t millis16 ()
uint64_t micros64 ()
uint64_t millis64 ()
void dump_stack_trace ()
void dump_core_file ()
template<typename T , typename S , typename R >
bool timeout_expired (const T past_time, const S now, const R timeout)
template<typename T , typename S , typename R >
T timeout_remaining (const T past_time, const S now, const R timeout)
template<typename T >
bool operator== (T *a, const OwnPtr< T > &b)
template<typename T >
bool operator== (const OwnPtr< T > &a, T *b)
template<typename T >
bool operator!= (T *a, const OwnPtr< T > &b)
template<typename T >
bool operator!= (const OwnPtr< T > &a, T *b)
static uint64_t ts_to_nsec (struct timespec &ts)
static uint64_t ts_to_nsec (struct timespec &ts)
static void run_command_on_ownpid (const char *commandname)
Variables
void NORETURN
struct {
uint64_t AP_HAL::start_time_ns
} state
struct {
uint64_t AP_HAL::start_time_ns
} state
Typedef Documentation
Proc
typedef void(* AP_HAL::Proc) (void)
Definition at line 55 of file AP_HAL_Namespace.h.
Enumeration Type Documentation
SPIDeviceType
enum AP_HAL::SPIDeviceType
Global names for all of the existing SPI devices on all platforms.
Enumerator
SPIDevice_Type
Definition at line 62 of file AP_HAL_Namespace.h.
Function Documentation
dump_core_file()
void AP_HAL::dump_core_file ()
Definition at line 149 of file system.cpp.
Referenced by _sig_fpe(), and _sig_segv().
dump_stack_trace()
void AP_HAL::dump_stack_trace ()
Definition at line 145 of file system.cpp.
Referenced by _sig_fpe(), and _sig_segv().
FUNCTOR_TYPEDEF()
AP_HAL::FUNCTOR_TYPEDEF (MemberProc , void)
get_HAL()
const AP_HAL::HAL & AP_HAL::get_HAL ()
Definition at line 355 of file HAL_ChibiOS_Class.cpp.
Referenced by sdcard_init().
get_HAL_mutable()
AP_HAL::HAL & AP_HAL::get_HAL_mutable ()
Definition at line 359 of file HAL_ChibiOS_Class.cpp.
init()
void AP_HAL::init ()
Definition at line 323 of file system.cpp.
Referenced by AP_HAL::HAL::HAL(), and AP_HAL::CANIface::init().
micros()
uint32_t AP_HAL::micros ()
Definition at line 352 of file system.cpp.
Referenced by ESP32::SoftSigReaderInt::_irq_handler(), AP_RCProtocol_CRSF::_process_byte(), AP_RCProtocol_ST24::_process_byte(), HALSITL::SITL_State::_simulator_servos(), ChibiOS::AnalogIn::_timer_tick(), ChibiOS::RCInput::_timer_tick(), ESP32::RCInput::_timer_tick(), Linux::RCInput_Navio2::_timer_tick(), Linux::SPIUARTDriver::_timer_tick(), AnalogIn_ADS1115::_update(), AP_InertialSensor_Backend::_update_sensor_rate(), AP_Camera_Backend::check_feedback(), AP::PerfInfo::check_loop_time(), LoggerMessageWriter_DFLogStart::check_process_limit(), AP_SmartRTL::detect_loops(), AP_SmartRTL::detect_simplifications(), GCS_MAVLINK::do_try_send_message(), AP_DAL::ekf_low_time_remaining(), AP_Camera_Backend::feedback_pin_timer(), GCS_MAVLINK::find_next_bucket_to_send(), HALSITL::UARTDriver::handle_reading_from_device_to_readbuffer(), HALSITL::UARTDriver::handle_writing_from_writebuffer_to_device(), AP_Airspeed_MS5525::init(), AP_OpticalFlow_CXOF::init(), AP_Logger::io_thread(), AP_RCProtocol_CRSF::is_rx_active(), AP_RCProtocol_GHST::is_rx_active(), AP_RCProtocol_CRSF::is_tx_active(), AP_RCProtocol_GHST::is_tx_active(), loop(), loop(), AP_Scheduler::loop(), AP_InertialSensor_ADIS1647x::loop(), pal_interrupt_cb_functor(), LoggerMessageWriter_DFLogStart::process(), AP_RCProtocol_FPort::process_byte(), AP_RCProtocol_GHST::process_byte(), AP_RCProtocol_IBUS::process_byte(), AP_RCProtocol_SBUS::process_byte(), AP_RCProtocol_SRXL::process_byte(), AP_RCProtocol_SRXL2::process_byte(), AP_RCProtocol_SUMD::process_byte(), AP_Compass_Backend::publish_filtered_field(), GCS_MAVLINK::queued_param_send(), AP_BattMonitor_Analog::read(), AP_BattMonitor_Bebop::read(), AP_BattMonitor_Sum::read(), AP_BattMonitor_Synthetic_Current::read(), AP_BattMonitor_SMBus_SUI::read_cell_voltages(), HALSITL::UARTDriver::read_from_async_csv(), AP_Scheduler::run(), GCS_MAVLINK::send_autopilot_state_for_gimbal_device(), SITL::ADSB::send_report(), SITL::Gimbal::send_report(), GCS_MAVLINK::send_servo_output_raw(), setup(), setup(), AP_LoggerTest::setup(), AP_OpticalFlow_Pixart::setup_sensor(), MMLPlayer::start_note(), MMLPlayer::start_silence(), test_one_offset(), AP_Scheduler::time_available_usec(), AP_Airspeed_MS5525::timer(), AP_Baro_ICP201XX::timer(), AP_Baro_ICM20789::timer(), AP_Baro_ICP101XX::timer(), AP_OpticalFlow_Pixart::timer(), AP_BattMonitor_SMBus_Generic::timer(), AP_BattMonitor_SMBus_NeoDesign::timer(), AP_BattMonitor_SMBus_SUI::timer(), ChibiOS::UARTDriver::tx_complete(), ChibiOS::UARTDriver::uart_thread(), AP_IOMCU_FW::update(), MMLPlayer::update(), AP_SBusOut::update(), BinarySemTest::update(), SITL::MS5XXX::update(), SITL::Gimbal::update(), SITL::InertialLabs::update(), SITL::ShipSim::update(), SITL::VectorNav::update(), AP_InertialSensor::update(), AP_OpticalFlow_CXOF::update(), AP_RCProtocol_CRSF::update(), AP_BattMonitor_SMBus_SUI::update_health(), GCS_MAVLINK::update_receive(), GCS_MAVLINK::update_send(), SITL::ADSB::update_simulated_vehicles(), AP_MotorsMulticopter::update_throttle_filter(), AP_L1_Control::update_waypoint(), AP_InertialSensor::wait_for_sample(), AP_Logger::Write_NamedValueFloat(), ChibiOS::UARTDriver::write_pending_bytes(), ChibiOS::UARTDriver::write_pending_bytes_DMA(), and ChibiOS::UARTDriver::write_pending_bytes_NODMA().
micros16()
uint16_t AP_HAL::micros16 ()
Definition at line 366 of file system.cpp.
micros64()
uint64_t AP_HAL::micros64 ()
Definition at line 387 of file system.cpp.
Referenced by Linux::RCInput_SoloLink::_check_hdr(), ChibiOS::Scheduler::_monitor_thread(), AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_notify_new_accel_sensor_rate_sample(), AP_InertialSensor_Backend::_notify_new_delta_angle(), AP_InertialSensor_Backend::_notify_new_delta_velocity(), AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_InertialSensor_Backend::_notify_new_gyro_sensor_rate_sample(), Linux::RCInput::_process_dsm_pulse(), AP_InertialSensor_LSM9DS0::_read_data_transaction_a(), AP_InertialSensor_LSM9DS0::_read_data_transaction_g(), ESP32::UARTDriver::_receive_timestamp_update(), Linux::PeriodicThread::_run(), I2CBus::_timer_tick(), Linux::UARTDriver::_timer_tick(), AP_TECS::_update_pitch(), AP_TECS::_update_throttle_with_airspeed(), AP_InertialSensor_Invensensev3::accumulate_samples(), Linux::RCInput::add_dsm_input(), Linux::RCInput::add_srxl_input(), ChibiOS::DeviceBus::adjust_timer(), ESP32::DeviceBus::adjust_timer(), ChibiOS::DeviceBus::bus_thread(), ESP32::DeviceBus::bus_thread(), SITL::Motor::calculate_forces(), SITL::Blimp::calculate_forces(), AP_GPS_Backend::calculate_moving_base_yaw(), SCurve::calculate_path(), ChibiOS::RCOutput::pwm_group::can_send_dshot_pulse(), SoaringController::check_cruise_criteria(), AP_Camera_Backend::check_feedback(), AP_GPS_Backend::check_new_itow(), SoaringController::check_thermal_criteria(), GCS_MAVLINK::correct_offboard_timestamp_usec_to_ms(), AP_RCProtocol_FPort::decode_downlink(), ChibiOS::Scheduler::delay(), ESP32::Scheduler::delay(), Linux::Scheduler::delay(), HALSITL::Scheduler::delay_microseconds(), delay_ms(), AP_Logger_Backend::Fill_Format_Units(), AP_InertialSensor_NONE::generate_accel(), AP_InertialSensor_NONE::generate_gyro(), AP_RTC::get_utc_usec(), AP_InertialSensor_NONE::gyro_drift(), AP_Follow::handle_msg(), GCS_MAVLINK::handle_named_value(), HALSITL::UARTDriver::handle_reading_from_device_to_readbuffer(), GCS_MAVLINK::handle_timesync(), SoaringController::init_cruising(), SoaringController::init_thermalling(), AP_RCProtocol_Backend::log_data(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_InertialSensor_Backend::log_register_change(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_UBLOX::log_rxm_rawx(), ChibiOS::Util::log_stack_info(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages(), AP_LoggerTest_AllTypes::Log_Write_TypeMessages_Log_Write(), AP_MotorsHeli_RSC::output(), AP_BattMonitor::read(), SITL::JSON_Master::receive(), AP_HAL::UARTDriver::receive_time_constraint_us(), ChibiOS::UARTDriver::receive_timestamp_update(), SITL::AirSim::recv_fdm(), SITL::JSON::recv_fdm(), I2CBus::register_periodic_callback(), SPIBus::register_periodic_callback(), ChibiOS::DeviceBus::register_periodic_callback(), ESP32::DeviceBus::register_periodic_callback(), HAL_SITL::run(), RC_Channel::run_aux_function(), AP_HAL::CANIface::send(), AP_RCProtocol_SRXL2::send_on_uart(), GCS_MAVLINK::send_raw_imu(), SITL::Morse::send_report(), AP_Frsky_SPort::send_sport_frame(), GCS_MAVLINK::send_vibration(), SITL::Battery::set_current(), AP_Relay::set_pin_by_instance(), AP_RTC::set_utc_usec(), AP_LoggerTest::setup(), SITL::Sprayer::should_report(), SITL::Gripper_EPM::should_report(), SITL::Gripper_Servo::should_report(), SITL::Parachute::should_report(), SITL::MicroStrain::simulation_timeval(), simulation_timeval(), AP_DAL::start_frame(), SoaringController::suppress_throttle(), ChibiOS::Semaphore::take(), ESP32::Semaphore::take(), Linux::Semaphore::take(), HALSITL::Semaphore::take(), test_page_program(), AP_GPS::time_epoch_usec(), AP_Compass_MMC3416::timer(), AP_InertialSensor_NONE::timer_update(), GCS_MAVLINK::timesync_receive_timestamp_ns(), GCS_MAVLINK::timesync_timestamp_ns(), ChibiOS::Scheduler::try_force_mutex(), AP_WindVane::update(), AP_Baro_ICM20789::update(), Variometer::update(), SITL::Gripper_Servo::update(), SITL::ICEngine::update(), SITL::Parachute::update(), SITL::Sprayer::update(), SITL::Blimp::update(), AC_PrecLand::update(), AP_AutoTune::update(), AP_TECS::update_50hz(), SoaringController::update_cruising(), SITL::Gripper_EPM::update_from_demand(), AP_TECS::update_pitch_throttle(), SoaringController::update_thermalling(), SITL::Vicon::update_vicon_position_estimate(), HALSITL::BinarySemaphore::wait(), HALSITL::SITL_State::wait_clock(), AP_Logger_Backend::Write_AP_Logger_Stats_File(), AP_Logger::Write_Command(), AP_Logger::Write_Compass(), AP_Logger::Write_Error(), AP_Logger::Write_Event(), AP_RCProtocol_GHST::write_frame(), AP_Logger_Backend::Write_Message(), AP_Logger_Backend::Write_Mission_Cmd(), AP_Logger_Backend::Write_Mode(), AP_Logger_Backend::Write_Multiplier(), AP_Logger_Backend::Write_Parameter(), AP_Logger::Write_PID(), AP_Logger::Write_Power(), AP_Logger::Write_Radio(), AP_Logger::Write_RCOUT(), AP_Logger::Write_SRTL(), AP_Logger_Backend::Write_Unit(), AP_Logger_Backend::Write_VER(), and AP_Logger::Write_Winch().
millis()
uint32_t AP_HAL::millis ()
Definition at line 377 of file system.cpp.
Referenced by AP_GPS_SBP::_attempt_state_update(), AP_GPS_SBP2::_attempt_state_update(), SITL::Calibration::_calibration_poses(), AP_Baro_BMP085::_cmd_read_pressure(), AP_Baro_BMP085::_cmd_read_temp(), AP_Airspeed_MS4525::_collect(), AP_Baro_Backend::_copy_to_frontend(), AP_Baro_BMP085::_data_ready(), AP_GPS::_detect_instance(), Compass::_detect_runtime(), AP_TECS::_detect_underspeed(), ChibiOS::Scheduler::_expect_delay_ms(), HALSITL::SITL_State::_fdm_input_step(), AP_InertialSensor_Invensense::_fifo_reset(), ChibiOS::Storage::_flash_write_data(), ESP32::Storage::_flash_write_data(), HALSITL::Storage::_flash_write_data(), HALSITL::UARTDriver::_flush(), AP_GPS_NMEA::_have_new_message(), ChibiOS::Scheduler::_io_thread(), ESP32::Scheduler::_io_thread(), AP_Airspeed_MS4525::_measure(), ChibiOS::Scheduler::_monitor_thread(), AP_GPS_ERB::_parse_gps(), AP_GPS_UBLOX::_parse_gps(), AP_RCProtocol_SRXL2::_process_byte(), AP_Baro_BMP085::_read_pressure(), ChibiOS::Storage::_save_backup(), AP_GPS_UBLOX::_save_cfg(), AP_GPS_SBP::_sbp_process_message(), AP_GPS_SBP2::_sbp_process_message(), AP_GPS_NMEA::_term_complete(), AP_Airspeed_MS4525::_timer(), AP_Airspeed_SDP3X::_timer(), AP_RangeFinder_MaxsonarI2CXL::_timer(), ESP32::AnalogIn::_timer_tick(), ChibiOS::RCInput::_timer_tick(), ChibiOS::Storage::_timer_tick(), ESP32::Storage::_timer_tick(), Linux::RCInput_RCProtocol::_timer_tick(), HALSITL::Storage::_timer_tick(), HALSITL::UARTDriver::_uart_start_connection(), AP_Compass_BMM150::_update(), AP_TECS::_update_throttle_without_airspeed(), AP_Logger_Block::_WritePrioritisedBlock(), AP_SteerController::active(), Linux::RCInput::add_dsm_input(), Linux::RCInput::add_sbus_input(), AC_Avoid::adjust_velocity(), AP_GPS_GSOF::AP_GPS_GSOF(), AP_GPS_SBF::AP_GPS_SBF(), AP_GPS_SBP::AP_GPS_SBP(), AP_Logger::arming_failure(), AP_OAPathPlanner::avoidance_thread(), AP_GPS::backends_healthy(), AC_AutoTune::backup_gains_and_initialise(), AC_Loiter::calc_desired_velocity(), AP_Airspeed_MS5525::calculate(), AP_GPS_Backend::calculate_moving_base_yaw(), AP_WindVane_Analog::calibrate(), AP_Airspeed::calibrate(), AP_Baro::calibrate(), Compass_PerMotor::calibration_update(), AP_AdvancedFailsafe::check(), AR_PivotTurn::check_activation(), AP_RCProtocol::check_added_uart(), AP_AdvancedFailsafe::check_altlimit(), AP_ToneAlarm::check_cont_tone(), AC_PrecLand::check_ekf_init_timeout(), AP_RCTelemetry::check_ekf_status(), AP_Proximity_Boundary_3D::check_face_timeout(), AccelCalibrator::check_for_timeout(), AP_Tuning::check_input(), AP_Vehicle::check_motor_noise(), AP_GPS_Backend::check_new_itow(), AP_Tuning::check_selector_switch(), AP_Airspeed::check_sensor_ahrs_wind_max_failures(), AP_RCTelemetry::check_sensor_status_flags(), AP_Parachute::check_sink_rate(), AC_PrecLand::check_target_status(), GCS_MAVLINK_InProgress::check_tasks(), AC_AutoTune::control_attitude(), AC_AutoTune::currently_level(), AP_OADatabase::database_items_remove_all_expired(), RC_Channel::debounce_completed(), AP_RangeFinder_NMEA::decode_latest_term(), HALSITL::Scheduler::delay(), delay_one_ms(), AP_RCProtocol::detect_async_protocol(), AP_GPS::detect_instance(), AC_AutoTune_Heli::do_gcs_announcements(), AC_AutoTune_Multi::do_gcs_announcements(), AP_OSD_Screen::draw_message(), AC_AutoTune_Heli::dwell_test_run(), SchedTest::five_second_call(), GCS_MAVLINK::ftp_worker(), AR_AttitudeControl::get_desired_lat_accel(), AR_AttitudeControl::get_desired_pitch(), AR_AttitudeControl::get_desired_turn_rate(), AP_Airspeed_ASP5033::get_differential_pressure(), AP_Airspeed_DLVR::get_differential_pressure(), AP_Airspeed_MS4525::get_differential_pressure(), AP_Airspeed_MS5525::get_differential_pressure(), AP_Airspeed_SDP3X::get_differential_pressure(), AP_Baro::get_external_temperature(), AC_PrecLand_StateMachine::get_failsafe_actions(), PID::get_pid(), AP_Mount_Siyi::get_rangefinder_distance(), AP_WheelRateControl::get_rate_controlled_throttle(), AP_RangeFinder_LeddarOne::get_reading(), AP_RangeFinder_LeddarVu8::get_reading(), AP_RangeFinder_LightWareSerial::get_reading(), AP_RangeFinder_Wasp::get_reading(), AP_RangeFinder_VL53L0X::get_reading(), AP_RangeFinder_VL53L1X::get_reading(), AP_GPS::get_RelPosHeading(), GCS_MAVLINK::get_reschedule_interval_ms(), AR_AttitudeControl::get_sail_out_from_heel(), AP_YawController::get_servo_out(), AR_AttitudeControl::get_steering_out_lat_accel(), AP_SteerController::get_steering_out_rate(), AR_AttitudeControl::get_steering_out_rate(), AP_Follow::get_target_heading_deg(), AP_Follow::get_target_location_and_velocity(), AC_PrecLand_StateMachine::get_target_lost_actions(), AP_RangeFinder_NMEA::get_temp(), AP_Airspeed_ASP5033::get_temperature(), AP_Airspeed_DLVR::get_temperature(), AP_Airspeed_MS4525::get_temperature(), AP_Airspeed_MS5525::get_temperature(), AP_Airspeed_SDP3X::get_temperature(), AR_AttitudeControl::get_throttle_out_from_pitch(), AR_AttitudeControl::get_throttle_out_speed(), AR_AttitudeControl::get_throttle_out_stop(), AP_Vehicle::get_time_flying_ms(), AP_Beacon::get_vehicle_position_ned(), AC_WeatherVane::get_yaw_out(), AP_Gripper_EPM::grab(), GCS_MAVLINK::handle_heartbeat(), AP_RunCam::handle_initialized(), SITL::ADSB_Sagetech_MXS::handle_message(), MissionItemProtocol::handle_mission_item(), AP_Follow::handle_msg(), GCS_MAVLINK::handle_param_request_list(), GCS_MAVLINK::handle_param_request_read(), GCS_MAVLINK::handle_preflight_reboot(), GCS_MAVLINK::handle_radio_status(), RC_Channel::has_override(), AP_Follow::have_target(), AP_Mount_Siyi::healthy(), AP_Beacon_Marvelmind::healthy(), AP_Beacon_Nooploop::healthy(), AP_Beacon_Pozyx::healthy(), AP_Beacon_SITL::healthy(), ChibiOS::Storage::healthy(), ESP32::Storage::healthy(), HALSITL::Storage::healthy(), ChibiOS::Scheduler::in_expected_delay(), AP_Logger::in_log_persistance(), AP_Logger_Flash_JEDEC::InErase(), AP_Logger_W25N01GV::InErase(), AP_RunCam::init(), AP_Compass_BMM150::init(), AP_Generator_IE_FuelCell::init(), AC_AutoTune::init_internals(), MissionItemProtocol::init_send_requests(), AP_AHRS::initialised(), AP_GPS_SBP::inject_data(), AP_GPS_SBP2::inject_data(), SITL::SilentWings::interim_update(), AP_Logger_Block::io_thread_alive(), AP_Logger_Block::io_timer(), AC_Circle::is_active(), AC_WPNav::is_active(), AR_PosControl::is_active(), AR_WPNav::is_active(), AP_TempCalibration::learn_calibration(), AC_Avoid::limit_accel(), AC_Avoid::limits_active(), loop(), ReplayGyroFFT::loop(), AP_SmartAudio::loop(), AP_MSP::loop(), AP_AdvancedFailsafe::max_range_update(), SITL::Vicon::maybe_send_heartbeat(), AP_OAPathPlanner::mission_avoidance(), SlewLimiter::modifier(), AP_MSP_Telem_Backend::msp_process_out_name(), AP_RCProtocol::new_input(), AccelCalibrator::new_sample(), SchedTest::one_hz_print(), TCPServerDevice::open(), SITL::RF_LeddarOne::packet_for_alt(), SITL::RF_MAVLink::packet_for_alt(), GCS_MAVLINK::packet_overhead_chan(), AP_GPS_SBF::parse(), AP_Beacon_Pozyx::parse_buffer(), AP_Beacon_Nooploop::parse_node_frame2(), GCS::passthru_timer(), AP_Logger_Backend::periodic_tasks(), Buzzer::play_pattern(), AP_ToneAlarm::play_tone(), AP_Beacon_Marvelmind::process_beacons_distances_datagram(), AP_RCProtocol::process_byte(), AP_RCProtocol_DSM::process_byte(), AP_RCProtocol_SRXL2::process_handshake(), AP_GPS_NOVA::process_message(), AP_GPS_SBF::process_message(), AP_GPS_GSOF::process_message(), AP_Mount_Siyi::process_packet(), SITL::SilentWings::process_packet(), AP_RCProtocol::process_pulse(), GCS::StatusTextQueue::prune(), SITL::GPS_FILE::publish(), AP_Compass_Backend::publish_filtered_field(), AP_Compass_Backend::publish_raw_field(), GCS_MAVLINK::queued_param_send(), MissionItemProtocol::queued_request_send(), AC_AutoTune_Heli::rate_ff_test_run(), AP_IOMCU_FW::rcin_serial_update(), ChibiOS::RCOutput::rcout_thread(), SITL::I2CCommandResponseDevice::rdwr(), Compass::read(), AP_GPS_NOVA::read(), AP_GPS_SBF::read(), AP_GPS_UBLOX::read(), AP_GPS_GSOF::read(), AP_Airspeed::read(), AP_IRLock_I2C::read_block(), AP_IRLock_I2C::read_frames(), RC_Channels::read_input(), AP_RSSI::read_pwm_pin_rssi(), AP_BattMonitor_SMBus::read_temp(), AP_BattMonitor_SMBus_Rotoye::read_temp(), AP_RunCam::receive(), SITL::XPlane::receive_data(), AP_Parachute::release(), AP_Gripper_EPM::release(), AP_RunCam::Request::Request(), AP_RangeFinder_LeddarVu8::request_distances(), AP_SmartRTL::request_thorough_cleanup(), AC_WeatherVane::reset(), AP_Proximity_Boundary_3D::reset_face(), AC_AutoTune::run(), HAL_SITL::run(), AP_SmartRTL::run_background_cleanup(), AC_PrecLand::run_estimator(), AC_PrecLand::run_output_prediction(), MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_while_stopped_test(), AP_RCTelemetry::run_wfq_scheduler(), ESP32::RCOutput::safety_update(), GCS_MAVLINK::save_signing_timestamp(), AP_Vehicle::scheduler_delay_callback(), AP_Frsky_D::send(), GCS_MAVLINK::send_attitude(), AP_Mount_Siyi::send_attitude(), GCS_MAVLINK::send_attitude_quaternion(), AP_Camera_Backend::send_camera_capture_status(), AP_Camera_Backend::send_camera_information(), AP_Mount_Siyi::send_camera_information(), AP_Camera_Backend::send_camera_settings(), AP_Mount_Siyi::send_camera_settings(), AP_GPS_NMEA::send_config(), GCS_MAVLINK::send_ftp_reply(), AP_Mount_Backend::send_gimbal_manager_information(), AP_Mount_Backend::send_gimbal_manager_status(), GCS_MAVLINK::send_global_position_int(), GCS_MAVLINK::send_high_latency2(), GCS_MAVLINK::send_local_position(), GCS_MAVLINK::send_named_float(), GCS::send_named_float(), GCS_MAVLINK::send_parameter_async_replies(), GCS_MAVLINK::send_received_message_deprecation_warning(), SITL::ADSB::send_report(), SITL::Gimbal::send_report(), SITL::Morse::send_report(), SITL::ShipSim::send_report(), GCS_MAVLINK::send_scaled_imu(), GCS_MAVLINK::send_scaled_pressure_instance(), GCS_MAVLINK::send_set_position_target_global_int(), GCS_MAVLINK::send_system_time(), AP_Mount_SToRM32_serial::send_target_angles(), AP_Mount_Siyi::send_target_angles(), AP_Notify::send_text(), AP_Mount_Backend::send_warning_to_GCS(), AP_InertialSensor_Backend::sensors_converging(), AP_InertialSensor::set_accel_peak_hold(), AP_Beacon_Backend::set_beacon_distance(), AP_LeakDetector::set_detect(), AP_Baro::set_external_temperature(), AP_Proximity_Boundary_3D::set_face_attributes(), AP_Proximity_Boundary_3D::set_filtered_distance(), AP_Stats::set_flying(), AP_SmartRTL::set_home(), Linux::HeatPwm::set_imu_temp(), AP_Vehicle::set_likely_flying(), RC_Channel::set_override(), AP_Rally::set_rally_point_with_index(), AP_Parachute::set_sink_rate(), AP_HAL::Util::set_soft_armed(), SITL::TSYS01::set_state(), SITL::TSYS03::set_state(), AP_Beacon_Marvelmind::set_stationary_beacons_positions(), AccelCalibrator::set_status(), AP_AHRS::set_takeoff_expected(), AP_AHRS::set_touchdown_expected(), AP_Beacon_Backend::set_vehicle_position(), AP_RangeFinder_LightWareI2C::sf20_wait_on_reply(), AP_Logger_Backend::ShouldLog(), AR_AttitudeControl::speed_control_active(), AP_OpticalFlow_Calibrator::start(), AP_RangeFinder_VL53L0X::start_continuous(), AP_Logger_Flash_JEDEC::StartErase(), AP_Logger_W25N01GV::StartErase(), AP_AutoTune::state_change(), AP_IRLock_I2C::sync_frame_start(), AP_Camera_Backend::take_picture(), AC_PrecLand::target_acquired(), AP_ICEngine_TCA9554::TCA9554_set(), GCS_MAVLINK::telemetry_delayed(), GCS_MAVLINK::telemetry_radio_rssi(), test_mass_erase(), test_sector_erase(), test_uart(), AP_BoardConfig::throw_error(), AP_LTM_Telem::tick(), AP_GPS::time_epoch_usec(), SITL::TSYS01::time_in_state_ms(), SITL::TSYS03::time_in_state_ms(), TimeCheck::TimeCheck(), AP_Airspeed_ASP5033::timer(), AP_Airspeed_DLVR::timer(), AP_Compass_MMC3416::timer(), AP_OpticalFlow_Pixart::timer(), AP_RangeFinder_PulsedLightLRF::timer(), GCS_MAVLINK::try_send_message(), AC_AutoTune_Multi::twitching_measure_acceleration(), AC_AutoTune_Multi::twitching_test_angle(), AC_AutoTune_Multi::twitching_test_rate(), AP_Landing::type_slope_verify_land(), AC_Sprayer::update(), AP_Arming::update(), AP_RunCam::update(), AP_IOMCU_FW::update(), AP_OpticalFlow_Calibrator::update(), AP_Parachute::update(), AP_Stats::update(), MissionItemProtocol::update(), SITL::AIS::update(), SITL::CRSF::update(), SITL::SIM_GeneratorEngine::update(), AC_PrecLand_Companion::update(), AC_PrecLand_IRLock::update(), AC_PrecLand_SITL::update(), AC_PrecLand_SITL_Gazebo::update(), AP_Beacon_Nooploop::update(), AP_Beacon_SITL::update(), AP_IRLock_I2C::update(), AP_Mount_Siyi::update(), AP_Mount_SToRM32_serial::update(), RGBLed::update(), AP_RangeFinder_SITL::update(), AP_InertialSensor_Invensense::update(), BinarySemTest::update(), AP_SmartRTL::update(), SITL::Airspeed_DLVR::update(), SITL::SIM_BattMonitor_SMBus::update(), SITL::Rotoye::update(), SITL::MCP9600::update(), SITL::SIM_Precland::update(), SITL::SerialProximitySensor::update(), SITL::Parachute::update(), SITL::SilentWings::update(), SITL::XPlane::update(), AC_Circle::update(), AC_AutoTune_FreqResp::update(), AR_PosControl::update(), AR_WPNav::update(), SITL::SerialRangeFinder::update(), AC_PrecLand::update(), AP_AutoTune::update(), AP_Button::update(), AP_ICEngine::update(), AP_LeakDetector::update(), AP_OpticalFlow::update(), SITL::MicroStrain::update(), SITL::ShipSim::update(), AP_InertialSensor::update(), AP_Generator_IE_FuelCell::update(), AP_OpticalFlow_Onboard::update(), AP_OpticalFlow_Pixart::update(), AP_RangeFinder_analog::update(), AP_RangeFinder_Backend_Serial::update(), AP_RangeFinder_BBB_PRU::update(), AP_RangeFinder_Benewake_TFMiniPlus::update(), AP_RangeFinder_BLPing::update(), AP_RangeFinder_HC_SR04::update(), AP_RangeFinder_MaxsonarI2CXL::update(), AP_RangeFinder_PWM::update(), AP_RangeFinder_TeraRangerI2C::update(), AP_RangeFinder_VL53L0X::update(), AP_RangeFinder_VL53L1X::update(), AP_RangeFinder_Wasp::update(), AP_RCProtocol_CRSF::update(), AP_RCProtocol_DSM::update(), AP_RCProtocol_SRXL2::update(), AP_RPM_Pin::update(), AP_WheelEncoder_SITL_Quadrature::update(), AP_AHRS::update_AOA_SSA(), AP_RCTelemetry::update_avg_packet_rate(), AP_Airspeed::update_calibration(), AP_Baro::update_calibration(), SITL::RichenPower::update_control_pin(), AP_OSD::update_current_screen(), SITL::EFI_Hirth::update_engine_model(), AP_ServoRelayEvents::update_events(), AP_BattMonitor_Backend::update_failsafes(), AP_Baro::update_field_elevation(), AP_AHRS::update_flags(), AP_Stats::update_flighttime(), AP_Gripper_EPM::update_gripper(), AP_Baro_Backend::update_healthy_flag(), AP_GPS::update_instance(), AP_AHRS::update_orientation(), SITL::PS_TeraRangerTower::update_output(), SITL::PS_LightWare_SF45B::update_output_scan(), SITL::PS_RPLidar::update_output_scan(), RGBLed::update_override(), GCS::update_passthru(), Buzzer::update_pattern_to_play(), Buzzer::update_playing_pattern(), ChibiOS::AnalogIn::update_power_flags(), AP_GPS::update_primary(), SITL::EFI_Hirth::update_receive(), GCS_MAVLINK::update_receive(), AP_BattMonitor_Backend::update_resistance_estimate(), AP_Stats::update_runtime(), GCS_MAVLINK::update_send(), SITL::EFI_Hirth::update_send(), SITL::IntelligentEnergy24::update_send(), SITL::RichenPower::update_send(), AR_WPNav::update_speed_max(), AP_OpticalFlow::update_state(), AP_OSD_ParamScreen::update_state_machine(), AP_RunCam::update_state_machine_armed(), AP_RunCam::update_state_machine_disarmed(), AP_OSD::update_stats(), Display::update_text(), AC_WPNav::update_wpnav(), AP_Mount_Siyi::update_zoom_control(), ChibiOS::UARTDriver::wait_timeout(), AP_Logger_Flash_JEDEC::WaitReady(), AP_Logger_W25N01GV::WaitReady(), ChibiOS::Scheduler::watchdog_pat(), AC_WPNav::wp_and_spline_init(), and TimeCheck::~TimeCheck().
millis16()
uint16_t AP_HAL::millis16 ()
Definition at line 382 of file system.cpp.
Referenced by GCS::StatusTextQueue::prune(), GCS_MAVLINK::remove_message_from_bucket(), GCS::send_textv(), GCS_MAVLINK::set_ap_message_interval(), AP_Logger_RateLimiter::should_log_streaming(), SITL::InvensenseV3::update(), and GCS_MAVLINK::update_receive().
millis64()
uint64_t AP_HAL::millis64 ()
Definition at line 392 of file system.cpp.
Referenced by Linux::Scheduler::_debug_stack(), SITL::Plane::calculate_forces(), ESP32::Scheduler::print_main_loop_rate(), ESP32::Scheduler::print_stats(), AP_Button::timer_update(), AP_ESC_Telem_SITL::update(), SITL::ADSB_Vehicle::update(), and AP_Button::update().
operator!=() [1/2]
template<typename T > bool AP_HAL::operator!= (const OwnPtr< T > & a, T * b) inline
Definition at line 121 of file OwnPtr.h.
operator!=() [2/2]
template<typename T > bool AP_HAL::operator!= (T * a, const OwnPtr< T > & b) inline
Definition at line 115 of file OwnPtr.h.
operator==() [1/2]
template<typename T > bool AP_HAL::operator== (const OwnPtr< T > & a, T * b) inline
Definition at line 109 of file OwnPtr.h.
operator==() [2/2]
template<typename T > bool AP_HAL::operator== (T * a, const OwnPtr< T > & b) inline
Definition at line 103 of file OwnPtr.h.
panic()
void WEAK AP_HAL::panic (const char * errormsg, ...)
Definition at line 327 of file system.cpp.
Referenced by AP_InertialSensor_L3G4200D::_accel_init(), AP_Baro::_add_backend(), AP_InertialSensor::_add_backend(), RangeFinder::_add_backend(), Linux::SPIUARTDriver::_begin(), HALSITL::UARTDriver::_begin(), AP_RCProtocol_SRXL2::_bootstrap(), AP_InertialSensor_BMI160::_check_err_reg(), AP_ADC_ADS1115::_convert_register_data_to_mv(), ChibiOS::Storage::_flash_load(), ESP32::Storage::_flash_load(), HALSITL::Storage::_flash_load(), Linux::PWM_Sysfs_Bebop::_generate_duty_path(), Linux::PWM_Sysfs::_generate_duty_path(), Linux::PWM_Sysfs_Bebop::_generate_enable_path(), Linux::PWM_Sysfs::_generate_enable_path(), Linux::PWM_Sysfs::_generate_export_path(), Linux::PWM_Sysfs_Bebop::_generate_period_path(), Linux::PWM_Sysfs::_generate_period_path(), Linux::PWM_Sysfs::_generate_polarity_path(), AP_InertialSensor_LSM9DS0::_gyro_disable_i2c(), AP_InertialSensor_L3G4200D::_gyro_init(), Linux::CameraSensor_Mt9v117::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), AP_InertialSensor_LSM9DS1::_init_sensor(), HALSITL::SITL_State::_parse_command_line(), Linux::UARTDriver::_parseDevicePath(), Linux::OpticalFlow_Onboard::_run_optflow(), Linux::RCOutput_Bebop::_run_rcout(), HALSITL::SITL_State::_simulator_servos(), AP_InertialSensor::_start_backends(), ChibiOS::Storage::_storage_open(), HALSITL::Storage::_storage_open(), HALSITL::UARTDriver::_uart_start_connection(), AC_PrecLand::AC_PrecLand(), AC_Sprayer::AC_Sprayer(), HAL_SITL::actually_reboot(), AP_Airspeed::add_backend(), SITL::InvensenseV3::add_block(), SITL::XPlane::add_dref(), SITL::InvensenseV3::add_fifo(), SITL::XPlane::add_joyinput(), SITL::I2CRegisters_ConfigurableLength::add_register(), SITL::AIS::AIS(), AP_AdvancedFailsafe::AP_AdvancedFailsafe(), AP_AHRS_View::AP_AHRS_View(), AP_Airspeed::AP_Airspeed(), AP_Arming::AP_Arming(), AP_BattMonitor::AP_BattMonitor(), AP_Beacon::AP_Beacon(), AP_Button::AP_Button(), AP_CustomRotations::AP_CustomRotations(), AP_Generator::AP_Generator(), AP_GPS::AP_GPS(), AP_Gripper::AP_Gripper(), AP_Hott_Telem::AP_Hott_Telem(), AP_ICEngine::AP_ICEngine(), AP_InertialSensor::AP_InertialSensor(), AP_Logger::AP_Logger(), AP_memory_guard_error(), AP_Mission::AP_Mission(), AP_MotorsMatrix::AP_MotorsMatrix(), AP_Mount::AP_Mount(), AP_Networking::AP_Networking(), AP_Notify::AP_Notify(), AP_OADatabase::AP_OADatabase(), AP_OSD::AP_OSD(), AP_Parachute::AP_Parachute(), AP_Param::AP_Param(), AP_Rally::AP_Rally(), AP_RCProtocol_CRSF::AP_RCProtocol_CRSF(), AP_RCProtocol_GHST::AP_RCProtocol_GHST(), AP_RCProtocol_SRXL2::AP_RCProtocol_SRXL2(), AP_Relay::AP_Relay(), AP_RPM::AP_RPM(), AP_RSSI::AP_RSSI(), AP_RunCam::AP_RunCam(), AP_Scheduler::AP_Scheduler(), AP_stack_overflow(), AP_Vehicle::AP_Vehicle(), AP_VideoTX::AP_VideoTX(), AP_Winch::AP_Winch(), AP_WindVane::AP_WindVane(), SITL::EFI_Hirth::assert_receive_size(), SITL::I2CRegisters_8Bit::assert_register_value(), SITL::JEDEC::assert_writes_enabled(), SITL::FETtecOneWireESC::bootloader_handle_config_message(), Linux::CameraSensor_Mt9v117::CameraSensor_Mt9v117(), catch_sigbus(), catch_sigbus(), catch_sigbus(), SITL::MS5525::check_conversion_accuracy(), SITL::MS5611::check_conversion_accuracy(), AP_InertialSensor_BMI270::check_err_reg(), HALSITL::Semaphore::check_owner(), HALSITL::Scheduler::check_thread_stacks(), comm_send_buffer(), Compass::Compass(), SITL::Morse::connect_sockets(), SITL::Webots::connect_sockets(), SITL::FETtecOneWireESC::consume_bytes(), HALSITL::SITL_State_Common::create_serial_sim(), SITL::JSBSim::create_templates(), AP_InternalError::error(), fill_nanf(), fill_nanf(), FlashTest::flash_erase(), FlashTest::flash_read(), FlashTest::flash_write(), GCS::GCS(), Location::get_alt_cm(), Linux::I2CDeviceManager::get_device(), Linux::VideoIn::get_frame(), SITL::I2CRegisters_ConfigurableLength::get_reg_value(), HALSITL::Semaphore::give(), SITL::FETtecOneWireESC::handle_config_message(), SITL::FETtecOneWireESC::handle_config_message_set_tlm_type(), SITL::FETtecOneWireESC::handle_fast_esc_data(), AP_Mount::handle_message(), GCS_MAVLINK::handle_preflight_reboot(), GCS_MAVLINK::handle_serial_control(), Linux::Led_Sysfs::init(), Linux::PWM_Sysfs_Base::init(), SITL::I2C::init(), SITL::SPI::init(), AP_FlashIface_JEDEC::init(), Linux::GPIO_BBB::init(), Linux::GPIO_RPI::init(), Linux::GPIO_Sysfs::init(), Linux::OpticalFlow_Onboard::init(), Linux::RCInput_AioPRU::init(), Linux::RCInput_Navio2::init(), Linux::RCInput_PRU::init(), Linux::RCInput_SoloLink::init(), Linux::RCInput_UART::init(), Linux::RCInput_ZYNQ::init(), Linux::RCOutput_AeroIO::init(), Linux::RCOutput_Sysfs::init(), Linux::Scheduler::init(), Linux::Storage::init(), SITL::SIM_BattMonitor_SMBus_Generic::init(), SITL::JSON_Master::init(), AP_Baro::init(), AP_Logger_Block::Init(), AP_Logger_Flash_JEDEC::Init(), AP_Logger_W25N01GV::Init(), Linux::Scheduler::init_cpu_affinity(), Linux::Scheduler::init_realtime(), SITL::SPI::ioctl(), SITL::Frame::load_frame_params(), FlashTest::loop(), GCS_MAVLINK::next_deferred_bucket_message_to_send(), Linux::SPIBus::open(), Linux::RCInput_Navio2::open_channel(), SITL::JEDEC::open_storage_fd(), SITL::RAMTRON::open_storage_fd(), Linux::GPIO_RPI::openMemoryDevice(), SITL::RF_MAVLink::packet_for_alt(), SITL::RF_RDS02UF::packet_for_alt(), SITL::JEDEC::page_erase(), SITL::JEDEC::parse_addr(), SITL::Frame::parse_float(), SITL::Frame::parse_vector3(), RangeFinder::RangeFinder(), RC_Channels::RC_Channels(), Linux::RCInput_Multi::RCInput_Multi(), Linux::RCInput_UART::RCInput_UART(), RCMapper::RCMapper(), SITL::I2CCommandResponseDevice::rdwr(), SITL::Airspeed_DLVR::rdwr(), SITL::I2CRegisters_ConfigurableLength::rdwr(), SITL::I2CRegisters_16Bit::rdwr(), SITL::I2CRegisters_8Bit::rdwr(), SITL::MS5XXX::rdwr(), SITL::QMC5883L::rdwr(), SITL::SMBusDevice::rdwr(), SITL::TSYS01::rdwr(), SITL::JEDEC::rdwr(), SITL::RAMTRON::rdwr(), SITL::InvensenseV3::rdwr_block(), SITL::InvensenseV3::rdwr_fifo(), SITL::TSYS03::rdwr_handle_read(), SITL::TSYS03::rdwr_handle_write(), HALSITL::UARTDriver::read_from_async_csv(), Compass::register_compass(), Linux::I2CDevice::register_periodic_callback(), Linux::SPIDevice::register_periodic_callback(), ChibiOS::DeviceBus::register_periodic_callback(), AP_Baro::register_sensor(), SITL::FETtecOneWireESC::running_handle_config_message(), SITL::FETtecOneWireESC::send_response(), MAVLink_routing::send_to_components(), GCS_MAVLINK::set_ap_message_interval(), SITL::InvensenseV3::set_block(), SITL::SMBusDevice::set_block(), AnalogSource_Navio2::set_channel(), SITL::I2CRegisters_ConfigurableLength::set_register(), SITL::I2CRegisters_16Bit::set_register(), SITL::I2CRegisters_ConfigurableLength::set_register(), SITL::I2CRegisters_8Bit::set_register(), SITL::I2CRegisters_ConfigurableLength::set_register(), SITL::I2CRegisters_16Bit::set_register(), SITL::I2CRegisters_ConfigurableLength::set_register(), SITL::I2CRegisters_8Bit::set_register(), ChibiOS::Scheduler::set_system_initialized(), ESP32::Scheduler::set_system_initialized(), Linux::Scheduler::set_system_initialized(), HALSITL::Scheduler::set_system_initialized(), setup(), ChibiOS::AnalogIn::setup_adc(), sitl_flash_open(), sitl_flash_write(), Linux::SPIDevice::SPIDevice(), AP_InertialSensor_ADIS1647x::start(), AP_InertialSensor_BMI160::start(), AP_InertialSensor_Invensense::start(), AP_InertialSensor_Invensensev2::start(), AP_InertialSensor_Invensensev3::start(), Linux::Thread::start(), AP_Logger::start_io_thread(), SITL::JSBSim::start_JSBSim(), Linux::RCInput_RPI::termination_handler(), HALSITL::Scheduler::thread_create(), ChibiOS::UARTDriver::thread_init(), ChibiOS::UARTDriver::thread_rx_init(), GCS_MAVLINK::try_send_message(), SITL::AIS::update(), SITL::SIM_GeneratorEngine::update(), SITL::LM2755::LEDChannel::update(), SITL::Frsky_D::update(), SITL::SIM_BattMonitor_SMBus_Generic::update(), SITL::LM2755::update(), SITL::LP5562::update(), SITL::MCP9600::update(), AP_WheelEncoder_SITL_Quadrature::update(), SITL::FETtecOneWireESC::update_input(), SITL::PS_LightWare_SF45B::update_input(), SITL::PS_RPLidar::update_input(), SITL::EFI_Hirth::update_receive(), SITL::InvensenseV3::update_sample_count(), SITL::EFI_Hirth::update_send(), SITL::IntelligentEnergy24::update_send(), SITL::RichenPower::update_send(), SITL::ADSB_Sagetech_MXS::update_serial_input(), AP_Logger_Backend::validate_WritePrioritisedBlock(), AP_Logger::Write_calc_msg_len(), SITL::InvensenseV3::write_to_fifo(), AP_Logger::WriteReplayBlock(), and SITL::XPlane::XPlane().
run_command_on_ownpid()
static void AP_HAL::run_command_on_ownpid (const char * commandname) static
Definition at line 63 of file system.cpp.
Referenced by dump_core_file(), and dump_stack_trace().
timeout_expired()
template<typename T , typename S , typename R > bool AP_HAL::timeout_expired (const T past_time, const S now, const R timeout) inline
Definition at line 30 of file system.h.
Referenced by timeout_test(), ChibiOS::RCOutput::timer_tick(), and ChibiOS::RCOutput::trigger_groups().
timeout_remaining()
template<typename T , typename S , typename R > T AP_HAL::timeout_remaining (const T past_time, const S now, const R timeout) inline
Definition at line 44 of file system.h.
Referenced by ChibiOS::RCOutput::dshot_send(), timeout_remaining(), and ChibiOS::RCOutput::trigger_groups().
ts_to_nsec() [1/2]
static uint64_t AP_HAL::ts_to_nsec (struct timespec & ts) static
Definition at line 20 of file system.cpp.
ts_to_nsec() [2/2]
static uint64_t AP_HAL::ts_to_nsec (struct timespec & ts) static
Definition at line 24 of file system.cpp.
Variable Documentation
NORETURN
void AP_HAL::NORETURN
Definition at line 13 of file system.h.
start_time_ns
uint64_t AP_HAL::start_time_ns
Definition at line 17 of file system.cpp.
[struct] [1/2]
struct { ... } AP_HAL::state
[struct] [2/2]
struct { ... } AP_HAL::state