APM:Libraries: MSP Namespace Reference
MSP Namespace Reference
Classes
struct msp_packet_s
struct msp_port_s
struct PACKED
struct sbuf_s
Typedefs
typedef struct MSP::msp_packet_s msp_packet_t
typedef struct MSP::PACKED msp_header_v1_t
typedef struct MSP::PACKED msp_header_jumbo_t
typedef struct MSP::PACKED msp_header_v2_t
typedef struct MSP::msp_port_s msp_port_t
typedef struct MSP::sbuf_s sbuf_t
typedef struct MSP::PACKED msp_rangefinder_data_message_t
typedef struct MSP::PACKED msp_opflow_data_message_t
typedef struct MSP::PACKED msp_gps_data_message_t
typedef struct MSP::PACKED msp_baro_data_message_t
typedef struct MSP::PACKED msp_compass_data_message_t
typedef struct MSP::PACKED msp_airspeed_data_message_t
Enumerations
enum msp_version_e { MSP_V1 = 0 , MSP_V2_OVER_V1 = 1 , MSP_V2_NATIVE = 2 , MSP_VERSION_COUNT }
enum MSPCommandResult { MSP_RESULT_ACK = 1 , MSP_RESULT_ERROR = -1 , MSP_RESULT_NO_REPLY = 0 }
enum msp_flags_e { MSP_FLAG_DONT_REPLY = (1 << 0) }
enum msp_state_e {
MSP_IDLE , MSP_HEADER_START , MSP_HEADER_M , MSP_HEADER_X ,
MSP_HEADER_V1 , MSP_PAYLOAD_V1 , MSP_CHECKSUM_V1 , MSP_HEADER_V2_OVER_V1 ,
MSP_PAYLOAD_V2_OVER_V1 , MSP_CHECKSUM_V2_OVER_V1 , MSP_HEADER_V2_NATIVE , MSP_PAYLOAD_V2_NATIVE ,
MSP_CHECKSUM_V2_NATIVE , MSP_COMMAND_RECEIVED
}
enum msp_displayport_subcmd_e : uint8_t {
MSP_DISPLAYPORT_HEARTBEAT = 0 , MSP_DISPLAYPORT_RELEASE = 1 , MSP_DISPLAYPORT_CLEAR_SCREEN = 2 , MSP_DISPLAYPORT_WRITE_STRING = 3 ,
MSP_DISPLAYPORT_DRAW_SCREEN = 4 , MSP_DISPLAYPORT_SET_OPTIONS = 5
}
enum battery_state_e : uint8_t {
MSP_BATTERY_OK = 0 , MSP_BATTERY_WARNING , MSP_BATTERY_CRITICAL , MSP_BATTERY_NOT_PRESENT ,
MSP_BATTERY_INIT
}
Functions
uint8_t msp_serial_checksum_buf (uint8_t checksum, const uint8_t *data, uint32_t len)
uint32_t msp_serial_send_frame (msp_port_t *msp, const uint8_t *hdr, uint32_t hdr_len, const uint8_t *data, uint32_t data_len, const uint8_t *crc, uint32_t crc_len)
uint32_t msp_serial_encode (msp_port_t *msp, msp_packet_t *packet, msp_version_e msp_version, bool is_request=false)
bool msp_parse_received_data (msp_port_t *msp, uint8_t c)
uint8_t * sbuf_ptr (sbuf_t *buf)
uint16_t sbuf_bytes_remaining (const sbuf_t *buf)
bool sbuf_check_bounds (const sbuf_t *buf, const uint8_t len)
void sbuf_switch_to_reader (sbuf_t *buf, uint8_t *base)
void sbuf_write_data (sbuf_t *dst, const void *data, int len)
Typedef Documentation
msp_airspeed_data_message_t
typedef struct MSP::PACKED MSP::msp_airspeed_data_message_t
msp_baro_data_message_t
typedef struct MSP::PACKED MSP::msp_baro_data_message_t
msp_compass_data_message_t
typedef struct MSP::PACKED MSP::msp_compass_data_message_t
msp_gps_data_message_t
typedef struct MSP::PACKED MSP::msp_gps_data_message_t
msp_header_jumbo_t
typedef struct MSP::PACKED MSP::msp_header_jumbo_t
msp_header_v1_t
typedef struct MSP::PACKED MSP::msp_header_v1_t
msp_header_v2_t
typedef struct MSP::PACKED MSP::msp_header_v2_t
msp_opflow_data_message_t
typedef struct MSP::PACKED MSP::msp_opflow_data_message_t
msp_packet_t
typedef struct MSP::msp_packet_s MSP::msp_packet_t
msp_port_t
typedef struct MSP::msp_port_s MSP::msp_port_t
msp_rangefinder_data_message_t
typedef struct MSP::PACKED MSP::msp_rangefinder_data_message_t
sbuf_t
typedef struct MSP::sbuf_s MSP::sbuf_t
Enumeration Type Documentation
battery_state_e
enum MSP::battery_state_e : uint8_t
Enumerator
MSP_BATTERY_OK
MSP_BATTERY_WARNING
MSP_BATTERY_CRITICAL
MSP_BATTERY_NOT_PRESENT
MSP_BATTERY_INIT
Definition at line 124 of file msp.h.
msp_displayport_subcmd_e
enum MSP::msp_displayport_subcmd_e : uint8_t
Enumerator
MSP_DISPLAYPORT_HEARTBEAT
MSP_DISPLAYPORT_RELEASE
MSP_DISPLAYPORT_CLEAR_SCREEN
MSP_DISPLAYPORT_WRITE_STRING
MSP_DISPLAYPORT_DRAW_SCREEN
MSP_DISPLAYPORT_SET_OPTIONS
Definition at line 86 of file msp.h.
msp_flags_e
enum MSP::msp_flags_e
Enumerator
MSP_FLAG_DONT_REPLY
Definition at line 61 of file msp.h.
msp_state_e
enum MSP::msp_state_e
Enumerator
MSP_IDLE
MSP_HEADER_START
MSP_HEADER_M
MSP_HEADER_X
MSP_HEADER_V1
MSP_PAYLOAD_V1
MSP_CHECKSUM_V1
MSP_HEADER_V2_OVER_V1
MSP_PAYLOAD_V2_OVER_V1
MSP_CHECKSUM_V2_OVER_V1
MSP_HEADER_V2_NATIVE
MSP_PAYLOAD_V2_NATIVE
MSP_CHECKSUM_V2_NATIVE
MSP_COMMAND_RECEIVED
Definition at line 65 of file msp.h.
msp_version_e
enum MSP::msp_version_e
Enumerator
MSP_V1
MSP_V2_OVER_V1
MSP_V2_NATIVE
MSP_VERSION_COUNT
Definition at line 40 of file msp.h.
MSPCommandResult
enum MSP::MSPCommandResult
Enumerator
MSP_RESULT_ACK
MSP_RESULT_ERROR
MSP_RESULT_NO_REPLY
Definition at line 48 of file msp.h.
Function Documentation
msp_parse_received_data()
bool MSP::msp_parse_received_data (msp_port_t * msp, uint8_t c)
Definition at line 152 of file msp.cpp.
Referenced by AP_MSP_Telem_Backend::process_incoming_data().
msp_serial_checksum_buf()
uint8_t MSP::msp_serial_checksum_buf (uint8_t checksum, const uint8_t * data, uint32_t len)
Definition at line 13 of file msp.cpp.
Referenced by msp_serial_encode().
msp_serial_encode()
uint32_t MSP::msp_serial_encode (msp_port_t * msp, msp_packet_t * packet, msp_version_e msp_version, bool is_request = false)
Definition at line 51 of file msp.cpp.
Referenced by AP_MSP_Telem_Backend::msp_process_received_command(), AP_MSP_Telem_Backend::msp_send_packet(), and AP_MSP_Telem_Backend::process_packet().
msp_serial_send_frame()
uint32_t MSP::msp_serial_send_frame (msp_port_t * msp, const uint8_t * hdr, uint32_t hdr_len, const uint8_t * data, uint32_t data_len, const uint8_t * crc, uint32_t crc_len)
Definition at line 24 of file msp.cpp.
Referenced by msp_serial_encode().
sbuf_bytes_remaining()
uint16_t MSP::sbuf_bytes_remaining (const sbuf_t * buf)
Definition at line 16 of file msp_sbuf.cpp.
Referenced by msp_serial_encode(), and sbuf_check_bounds().
sbuf_check_bounds()
bool MSP::sbuf_check_bounds (const sbuf_t * buf, const uint8_t len)
Definition at line 21 of file msp_sbuf.cpp.
Referenced by sbuf_write_data().
sbuf_ptr()
uint8_t * MSP::sbuf_ptr (sbuf_t * buf)
Definition at line 11 of file msp_sbuf.cpp.
Referenced by msp_serial_encode().
sbuf_switch_to_reader()
void MSP::sbuf_switch_to_reader (sbuf_t * buf, uint8_t * base)
Definition at line 30 of file msp_sbuf.cpp.
Referenced by AP_MSP_Telem_Backend::msp_process_received_command(), AP_MSP_Telem_Backend::msp_send_packet(), and AP_MSP_Telem_Backend::process_packet().
sbuf_write_data()
void MSP::sbuf_write_data (sbuf_t * dst, const void * data, int len)
Definition at line 36 of file msp_sbuf.cpp.
Referenced by AP_MSP_Telem_Backend::msp_process_out_altitude(), AP_MSP_Telem_Backend::msp_process_out_analog(), AP_MSP_Telem_Backend::msp_process_out_api_version(), AP_MSP_Telem_Backend::msp_process_out_attitude(), AP_MSP_Telem_Backend::msp_process_out_board_info(), AP_MSP_Telem_Backend::msp_process_out_build_info(), AP_MSP_Telem_Backend::msp_process_out_comp_gps(), AP_MSP_Telem_Backend::msp_process_out_esc_sensor_data(), AP_MSP_Telem_DJI::msp_process_out_esc_sensor_data(), AP_MSP_Telem_Backend::msp_process_out_fc_variant(), AP_MSP_Telem_DisplayPort::msp_process_out_fc_variant(), AP_MSP_Telem_DJI::msp_process_out_fc_variant(), AP_MSP_Telem_Backend::msp_process_out_fc_version(), AP_MSP_Telem_Backend::msp_process_out_name(), AP_MSP_Telem_Backend::msp_process_out_osd_config(), AP_MSP_Telem_Backend::msp_process_out_raw_gps(), AP_MSP_Telem_Backend::msp_process_out_rtc(), AP_MSP_Telem_Backend::msp_process_out_status(), AP_MSP_Telem_Backend::msp_process_out_uid(), and AP_MSP_Telem_Backend::msp_send_packet().