APM:Libraries: libraries/AP_Common/NMEA.cpp File Reference
NMEA.cpp File Reference
#include "NMEA.h"
Functions
char * nmea_vaprintf (const char *fmt, va_list ap)
bool nmea_printf (AP_HAL::UARTDriver *uart, const char *fmt,...)
uint16_t nmea_printf_buffer (char *buf, const uint16_t buf_max_len, const char *fmt,...)
Variables
const AP_HAL::HAL & hal
Function Documentation
nmea_printf()
bool nmea_printf (AP_HAL::UARTDriver * uart, const char * fmt, ...)
Definition at line 65 of file NMEA.cpp.
Referenced by AP_GPS_NMEA::send_config(), TEST(), and TEST().
nmea_printf_buffer()
uint16_t nmea_printf_buffer (char * buf, const uint16_t buf_max_len, const char * fmt, ...)
Definition at line 91 of file NMEA.cpp.
nmea_vaprintf()
char * nmea_vaprintf (const char * fmt, va_list ap)
Definition at line 25 of file NMEA.cpp.
Referenced by nmea_printf(), SITL::VectorNav::nmea_printf(), and nmea_printf_buffer().
Variable Documentation
hal
const AP_HAL::HAL& hal extern
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.
Referenced by nmea_vaprintf().