APM:Libraries: libraries/AP_Common/NMEA.h File Reference
NMEA.h File Reference
#include <AP_HAL/AP_HAL.h>
Functions
char * nmea_vaprintf (const char *fmt, va_list ap)
bool nmea_printf (AP_HAL::UARTDriver *uart, const char *fmt,...) FMT_PRINTF(2
bool uint16_t nmea_printf_buffer (char *buf, const uint16_t buf_max_len, const char *fmt,...)
Function Documentation
nmea_printf()
bool nmea_printf (AP_HAL::UARTDriver * uart, const char * fmt, ...)
nmea_printf_buffer()
bool uint16_t nmea_printf_buffer (char * buf, const uint16_t buf_max_len, const char * fmt, ...)
Definition at line 91 of file NMEA.cpp.
nmea_vaprintf()
char * nmea_vaprintf (const char * fmt, va_list ap)
Definition at line 25 of file NMEA.cpp.
Referenced by nmea_printf(), SITL::VectorNav::nmea_printf(), and nmea_printf_buffer().