APM:Libraries: libraries/SITL/examples/JSON/MATLAB/tcp_udp_ip_2.0.6/pnet.c File Reference
pnet.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <ctype.h>
#include <errno.h>
#include <netdb.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <fcntl.h>
#include "mex.h"
Classes
struct io_buff
struct con_info
Macros
#define VERSION "Version 2.0.5 2003-09-16"
#define IFWINDOWS(dothis)
#define IFUNIX(dothis) dothis
#define s_errno errno
#define nonblockingsocket(s) fcntl(s,F_SETFL,O_NONBLOCK)
#define INADDR_NONE (-1)
#define MSG_NOSIGNAL 0
#define debug_view_con_status(X)
#define MAX_CON 100 /* Maximum number of simultanius tcpip connections.*/
#define NAMEBUFF_LEN 100
#define MINBUFFSIZE 1000 /* readbuffer will shrink to this size if datalength is smaller. */
#define CBNAMELEN 30
#define CON_FREE -1 /* Find a new free struct in struct array */
#define BACKLOG 50 /* How many pending connections queue will hold */
#define double_inf HUGE_VAL
#define DEFAULT_WRITETIMEOUT double_inf
#define DEFAULT_READTIMEOUT double_inf
#define DEFAULT_INPUT_SIZE 50000
#define DEFAULT_USLEEP 10000
#define STATUS_FREE -1
#define STATUS_NOCONNECT 0
#define STATUS_TCP_SOCKET 1
#define STATUS_IO_OK 5
#define STATUS_UDP_CLIENT 6
#define STATUS_UDP_SERVER 8
#define STATUS_CONNECT 10
#define STATUS_TCP_CLIENT 11
#define STATUS_TCP_SERVER 12
#define STATUS_UDP_CLIENT_CONNECT 18
#define STATUS_UDP_SERVER_CONNECT 19
#define IS_STATUS_IO_OK(x) ((x)>=STATUS_IO_OK)
#define IS_STATUS_CONNECTED(x) ((x)>=STATUS_CONNECT)
#define IS_STATUS_UDP_NO_CON(x) ((x)==STATUS_UDP_CLIENT || (x)==STATUS_UDP_SERVER)
#define IS_STATUS_TCP_CONNECTED(x) ((x)==STATUS_TCP_CLIENT || (x)==STATUS_TCP_SERVER)
#define SWAPDATA(a, b) { a^=b; b^=a; a^=b; }
Functions
void Print_Start_Message ()
int myoptstrcmp (const char *s1, const char *s2)
void * myrealloc (char *ptr, int newsize)
void newbuffsize (io_buff *buff, int newsize)
mxClassID str2classid (const char *str)
mxClassID classid2size (const mxClassID id)
void byteswapdata (char *ptr, const int elements, const int elementsize, int mode)
void byteswapcopy (char *dest, char *src, const int elements, const int elementsize, int mode)
void __debug_view_con_status (char *str)
double my_now ()
int move_con (int idx)
int my_mexIsInputArgOK (const int argno)
const mxArray * my_mexInputArg (const int argno)
const char * my_mexInputOptionString (const int argno)
const char * my_mexFindInputString (int argno)
int my_mexFindInputOption (int argno, const char *opt)
double my_mexInputCell (const int argno, int cell_no)
int my_mexInputSize (const int argno)
double my_mexInputScalar (const int argno)
int my_mexInputArray2Buff (const int argno, io_buff *buff)
void my_mexReturnValue (double val)
void my_mexReturnMatrix (int rows, int cols, double *vals)
void my_mexReturnString (const char *str)
void my_mexReturnArrayFromBuff (const int argno, io_buff *buff, const int line)
int ipv4_lookup (const char *hostname, int port)
int writedata ()
void init_con (int fid, int status)
void close_con ()
int closeall (void)
void CleanUpMex (void)
int read2buff (const int len, int newline, int noblock)
int readtype2buff (int len, mxClassID datatype, int newline, int noblock)
int tcp_connect (const char *hostname, const int port)
int tcp_udp_socket (int port, int dgram_f)
int tcpiplisten (int noblock)
int udp_connect (const char *hostname, int port)
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Variables
int gret_args =0
int gnlhs
mxArray ** gplhs
int gnrhs
const mxArray ** gprhs
con_info con [MAX_CON]
int con_index =0
unsigned long mex_call_counter =0
Macro Definition Documentation
BACKLOG
#define BACKLOG 50 /* How many pending connections queue will hold */
Definition at line 123 of file pnet.c.
Referenced by tcp_udp_socket().
CBNAMELEN
#define CBNAMELEN 30
Definition at line 119 of file pnet.c.
Referenced by mexFunction().
CON_FREE
#define CON_FREE -1 /* Find a new free struct in struct array */
Definition at line 121 of file pnet.c.
Referenced by move_con(), tcp_connect(), and tcpiplisten().
debug_view_con_status
#define debug_view_con_status (X)
Definition at line 114 of file pnet.c.
Referenced by mexFunction(), move_con(), and my_mexReturnArrayFromBuff().
DEFAULT_INPUT_SIZE
#define DEFAULT_INPUT_SIZE 50000
Definition at line 128 of file pnet.c.
Referenced by my_mexInputSize().
DEFAULT_READTIMEOUT
#define DEFAULT_READTIMEOUT double_inf
Definition at line 127 of file pnet.c.
Referenced by init_con().
DEFAULT_USLEEP
#define DEFAULT_USLEEP 10000
Definition at line 129 of file pnet.c.
Referenced by read2buff(), tcpiplisten(), and writedata().
DEFAULT_WRITETIMEOUT
#define DEFAULT_WRITETIMEOUT double_inf
Definition at line 126 of file pnet.c.
Referenced by init_con().
double_inf
#define double_inf HUGE_VAL
Definition at line 125 of file pnet.c.
IFUNIX
#define IFUNIX (dothis) dothis
Definition at line 86 of file pnet.c.
IFWINDOWS
#define IFWINDOWS (dothis)
Definition at line 85 of file pnet.c.
Referenced by CleanUpMex().
INADDR_NONE
#define INADDR_NONE (-1)
Definition at line 101 of file pnet.c.
Referenced by ipv4_lookup().
IS_STATUS_CONNECTED
#define IS_STATUS_CONNECTED (x) ((x)>=STATUS_CONNECT)
Definition at line 145 of file pnet.c.
Referenced by read2buff().
IS_STATUS_IO_OK
#define IS_STATUS_IO_OK (x) ((x)>=STATUS_IO_OK)
Definition at line 144 of file pnet.c.
Referenced by read2buff().
IS_STATUS_TCP_CONNECTED
#define IS_STATUS_TCP_CONNECTED (x) ((x)==STATUS_TCP_CLIENT || (x)==STATUS_TCP_SERVER)
Definition at line 147 of file pnet.c.
Referenced by mexFunction(), read2buff(), and writedata().
IS_STATUS_UDP_NO_CON
#define IS_STATUS_UDP_NO_CON (x) ((x)==STATUS_UDP_CLIENT || (x)==STATUS_UDP_SERVER)
Definition at line 146 of file pnet.c.
Referenced by mexFunction(), and writedata().
MAX_CON
#define MAX_CON 100 /* Maximum number of simultanius tcpip connections.*/
Definition at line 116 of file pnet.c.
Referenced by closeall(), mexFunction(), and move_con().
MINBUFFSIZE
#define MINBUFFSIZE 1000 /* readbuffer will shrink to this size if datalength is smaller. */
Definition at line 118 of file pnet.c.
MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
Definition at line 106 of file pnet.c.
Referenced by read2buff(), and writedata().
NAMEBUFF_LEN
#define NAMEBUFF_LEN 100
Definition at line 117 of file pnet.c.
nonblockingsocket
#define nonblockingsocket (s) fcntl(s,F_SETFL,O_NONBLOCK)
Definition at line 97 of file pnet.c.
Referenced by tcp_connect(), tcp_udp_socket(), tcpiplisten(), and udp_connect().
s_errno
#define s_errno errno
Definition at line 89 of file pnet.c.
Referenced by read2buff(), and writedata().
STATUS_CONNECT
#define STATUS_CONNECT 10
Definition at line 138 of file pnet.c.
STATUS_FREE
#define STATUS_FREE -1
Definition at line 132 of file pnet.c.
Referenced by close_con(), mexFunction(), and move_con().
STATUS_IO_OK
#define STATUS_IO_OK 5
Definition at line 135 of file pnet.c.
Referenced by writedata().
STATUS_NOCONNECT
#define STATUS_NOCONNECT 0
Definition at line 133 of file pnet.c.
Referenced by read2buff(), and writedata().
STATUS_TCP_CLIENT
#define STATUS_TCP_CLIENT 11
Definition at line 139 of file pnet.c.
Referenced by tcp_connect().
STATUS_TCP_SERVER
#define STATUS_TCP_SERVER 12
Definition at line 140 of file pnet.c.
Referenced by tcpiplisten().
STATUS_TCP_SOCKET
#define STATUS_TCP_SOCKET 1
Definition at line 134 of file pnet.c.
Referenced by mexFunction().
STATUS_UDP_CLIENT
#define STATUS_UDP_CLIENT 6
Definition at line 136 of file pnet.c.
Referenced by mexFunction(), and udp_connect().
STATUS_UDP_CLIENT_CONNECT
#define STATUS_UDP_CLIENT_CONNECT 18
Definition at line 141 of file pnet.c.
Referenced by udp_connect().
STATUS_UDP_SERVER
#define STATUS_UDP_SERVER 8
Definition at line 137 of file pnet.c.
STATUS_UDP_SERVER_CONNECT
#define STATUS_UDP_SERVER_CONNECT 19
Definition at line 142 of file pnet.c.
Referenced by udp_connect().
SWAPDATA
#define SWAPDATA (a, b) { a^=b; b^=a; a^=b; }
VERSION
#define VERSION "Version 2.0.5 2003-09-16"
Definition at line 5 of file pnet.c.
Referenced by Print_Start_Message().
Function Documentation
__debug_view_con_status()
void __debug_view_con_status (char * str)
Definition at line 445 of file pnet.c.
byteswapcopy()
void byteswapcopy (char * dest, char * src, const int elements, const int elementsize, int mode)
Definition at line 417 of file pnet.c.
Referenced by my_mexInputArray2Buff(), and my_mexReturnArrayFromBuff().
byteswapdata()
void byteswapdata (char * ptr, const int elements, const int elementsize, int mode)
Definition at line 373 of file pnet.c.
classid2size()
mxClassID classid2size (const mxClassID id)
Definition at line 262 of file pnet.c.
Referenced by my_mexInputArray2Buff(), my_mexReturnArrayFromBuff(), and readtype2buff().
CleanUpMex()
void CleanUpMex (void)
Definition at line 900 of file pnet.c.
Referenced by mexFunction().
close_con()
void close_con ()
Definition at line 874 of file pnet.c.
Referenced by closeall(), mexFunction(), and tcp_connect().
closeall()
int closeall (void)
Definition at line 887 of file pnet.c.
Referenced by CleanUpMex(), and mexFunction().
init_con()
void init_con (int fid, int status)
Definition at line 863 of file pnet.c.
Referenced by close_con(), and mexFunction().
ipv4_lookup()
int ipv4_lookup (const char * hostname, int port)
Definition at line 783 of file pnet.c.
Referenced by mexFunction(), tcp_connect(), and udp_connect().
mexFunction()
void mexFunction (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[])
Definition at line 1096 of file pnet.c.
move_con()
int move_con (int idx)
Definition at line 492 of file pnet.c.
Referenced by mexFunction(), and tcpiplisten().
my_mexFindInputOption()
int my_mexFindInputOption (int argno, const char * opt)
Definition at line 569 of file pnet.c.
Referenced by mexFunction(), my_mexInputArray2Buff(), and my_mexReturnArrayFromBuff().
my_mexFindInputString()
const char * my_mexFindInputString (int argno)
Definition at line 553 of file pnet.c.
Referenced by mexFunction().
my_mexInputArg()
const mxArray * my_mexInputArg (const int argno)
Definition at line 531 of file pnet.c.
Referenced by mexFunction(), my_mexFindInputOption(), my_mexInputArray2Buff(), my_mexInputCell(), my_mexInputOptionString(), my_mexInputScalar(), my_mexInputSize(), and my_mexReturnArrayFromBuff().
my_mexInputArray2Buff()
int my_mexInputArray2Buff (const int argno, io_buff * buff)
Definition at line 629 of file pnet.c.
Referenced by mexFunction().
my_mexInputCell()
double my_mexInputCell (const int argno, int cell_no)
Definition at line 585 of file pnet.c.
Referenced by my_mexInputSize(), and my_mexReturnArrayFromBuff().
my_mexInputOptionString()
const char * my_mexInputOptionString (const int argno)
Definition at line 541 of file pnet.c.
Referenced by mexFunction(), my_mexFindInputString(), my_mexInputScalar(), my_mexInputSize(), and my_mexReturnArrayFromBuff().
my_mexInputScalar()
double my_mexInputScalar (const int argno)
Definition at line 619 of file pnet.c.
Referenced by mexFunction().
my_mexInputSize()
int my_mexInputSize (const int argno)
Definition at line 597 of file pnet.c.
Referenced by mexFunction(), and my_mexReturnArrayFromBuff().
my_mexIsInputArgOK()
int my_mexIsInputArgOK (const int argno)
Definition at line 521 of file pnet.c.
Referenced by mexFunction(), my_mexFindInputOption(), my_mexFindInputString(), my_mexInputArg(), my_mexInputOptionString(), my_mexInputSize(), and my_mexReturnArrayFromBuff().
my_mexReturnArrayFromBuff()
void my_mexReturnArrayFromBuff (const int argno, io_buff * buff, const int line)
Definition at line 701 of file pnet.c.
Referenced by mexFunction().
my_mexReturnMatrix()
void my_mexReturnMatrix (int rows, int cols, double * vals)
Definition at line 674 of file pnet.c.
Referenced by mexFunction().
my_mexReturnString()
void my_mexReturnString (const char * str)
Definition at line 689 of file pnet.c.
Referenced by mexFunction().
my_mexReturnValue()
void my_mexReturnValue (double val)
Definition at line 657 of file pnet.c.
Referenced by mexFunction().
my_now()
double my_now ()
Definition at line 470 of file pnet.c.
Referenced by read2buff(), tcpiplisten(), and writedata().
myoptstrcmp()
int myoptstrcmp (const char * s1, const char * s2)
Definition at line 198 of file pnet.c.
Referenced by mexFunction(), my_mexFindInputOption(), and str2classid().
myrealloc()
void * myrealloc (char * ptr, int newsize)
Definition at line 213 of file pnet.c.
Referenced by newbuffsize().
newbuffsize()
void newbuffsize (io_buff * buff, int newsize)
Definition at line 223 of file pnet.c.
Referenced by close_con(), mexFunction(), my_mexInputArray2Buff(), my_mexReturnArrayFromBuff(), read2buff(), and writedata().
Print_Start_Message()
void Print_Start_Message ()
Definition at line 184 of file pnet.c.
Referenced by mexFunction().
read2buff()
int read2buff (const int len, int newline, int noblock)
Definition at line 909 of file pnet.c.
Referenced by mexFunction(), and readtype2buff().
readtype2buff()
int readtype2buff (int len, mxClassID datatype, int newline, int noblock)
Definition at line 984 of file pnet.c.
Referenced by mexFunction().
str2classid()
mxClassID str2classid (const char * str)
Definition at line 247 of file pnet.c.
Referenced by mexFunction(), and my_mexReturnArrayFromBuff().
tcp_connect()
int tcp_connect (const char * hostname, const int port)
Definition at line 992 of file pnet.c.
Referenced by mexFunction().
tcp_udp_socket()
int tcp_udp_socket (int port, int dgram_f)
Definition at line 1016 of file pnet.c.
Referenced by mexFunction().
tcpiplisten()
int tcpiplisten (int noblock)
Definition at line 1045 of file pnet.c.
Referenced by mexFunction().
udp_connect()
int udp_connect (const char * hostname, int port)
Definition at line 1068 of file pnet.c.
Referenced by mexFunction().
writedata()
int writedata ()
Definition at line 810 of file pnet.c.
Referenced by mexFunction().
Variable Documentation
con
con_info con[MAX_CON]
Definition at line 179 of file pnet.c.
Referenced by __debug_view_con_status(), close_con(), closeall(), init_con(), ipv4_lookup(), mexFunction(), move_con(), read2buff(), tcp_connect(), tcpiplisten(), udp_connect(), and writedata().
con_index
int con_index =0
Definition at line 180 of file pnet.c.
Referenced by __debug_view_con_status(), close_con(), closeall(), init_con(), ipv4_lookup(), mexFunction(), move_con(), read2buff(), tcp_connect(), tcpiplisten(), udp_connect(), and writedata().
gnlhs
int gnlhs
Definition at line 173 of file pnet.c.
Referenced by mexFunction(), my_mexReturnArrayFromBuff(), my_mexReturnMatrix(), my_mexReturnString(), and my_mexReturnValue().
gnrhs
int gnrhs
Definition at line 175 of file pnet.c.
Referenced by mexFunction(), and my_mexIsInputArgOK().
gplhs
mxArray** gplhs
Definition at line 174 of file pnet.c.
Referenced by mexFunction(), my_mexReturnArrayFromBuff(), my_mexReturnMatrix(), my_mexReturnString(), and my_mexReturnValue().
gprhs
const mxArray** gprhs
Definition at line 176 of file pnet.c.
Referenced by mexFunction(), my_mexInputArg(), and my_mexInputArray2Buff().
gret_args
int gret_args =0
Definition at line 172 of file pnet.c.
Referenced by mexFunction(), my_mexReturnArrayFromBuff(), my_mexReturnMatrix(), my_mexReturnString(), and my_mexReturnValue().
mex_call_counter
unsigned long mex_call_counter =0
Definition at line 181 of file pnet.c.
Referenced by mexFunction().