APM:Libraries: libraries/AP_Math/polygon.h File Reference
polygon.h File Reference
#include "vector2.h"
Functions
template<typename T >
bool Polygon_outside (const Vector2< T > &P, const Vector2< T > *V, unsigned n) WARN_IF_UNUSED
template<typename T >
bool Polygon_complete (const Vector2< T > *V, unsigned n) WARN_IF_UNUSED
bool Polygon_intersects (const Vector2f *V, unsigned N, const Vector2f &p1, const Vector2f &p2, Vector2f &intersection) WARN_IF_UNUSED
float Polygon_closest_distance_line (const Vector2f *V, unsigned N, const Vector2f &p1, const Vector2f &p2)
float Polygon_closest_distance_point (const Vector2f *V, unsigned N, const Vector2f &p)
Function Documentation
Polygon_closest_distance_line()
float Polygon_closest_distance_line (const Vector2f * V, unsigned N, const Vector2f & p1, const Vector2f & p2)
Definition at line 180 of file polygon.cpp.
Referenced by AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_polygons().
Polygon_closest_distance_point()
float Polygon_closest_distance_point (const Vector2f * V, unsigned N, const Vector2f & p)
Definition at line 203 of file polygon.cpp.
Polygon_complete()
template<typename T > bool Polygon_complete (const Vector2< T > * V, unsigned n)
Definition at line 116 of file polygon.cpp.
Referenced by Polygon_intersects(), Polygon_outside(), and setup().
Polygon_intersects()
bool Polygon_intersects (const Vector2f * V, unsigned N, const Vector2f & p1, const Vector2f & p2, Vector2f & intersection)
Definition at line 133 of file polygon.cpp.
Referenced by Polygon_closest_distance_line().
Polygon_outside()
template<typename T > bool Polygon_outside (const Vector2< T > & P, const Vector2< T > * V, unsigned n)
Definition at line 40 of file polygon.cpp.
Referenced by AC_Avoid::adjust_velocity_polygon(), AP_OABendyRuler::calc_margin_from_inclusion_and_exclusion_polygons(), setup(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().