APM:Libraries: libraries/RC_Channel/RC_Channel.h File Reference
RC_Channel.h File Reference
RC_Channel manager, with EEPROM-backed storage of constants.
#include "RC_Channel_config.h"
#include <AP_Common/AP_Common.h>
#include <AP_Param/AP_Param.h>
#include <AP_Math/AP_Math.h>
#include <AP_Common/Bitmask.h>
Classes
class RC_Channel
Object managing one RC channel.
struct RC_Channel::LookupTable
class RC_Channels
Macros
#define NUM_RC_CHANNELS 16
Functions
RC_Channels & rc ()
Detailed Description
RC_Channel manager, with EEPROM-backed storage of constants.
Definition in file RC_Channel.h.
Macro Definition Documentation
NUM_RC_CHANNELS
#define NUM_RC_CHANNELS 16
Definition at line 14 of file RC_Channel.h.
Referenced by RC_Channels_Example::channel(), RC_Channels::clear_overrides(), RC_Channels::convert_options(), RC_Channels::duplicate_options_exist(), RC_Channels::find_channel_for_option(), RC_Channels::flight_mode_channel(), RC_Channels::get_override_mask(), RC_Channels::get_radio_in(), RC_Channels::get_valid_channel_count(), RC_Channels::has_active_overrides(), RC_Channels::init(), RC_Channels::init_aux_all(), RC_Channels::read_aux_all(), RC_Channels::read_input(), and RC_Channels::set_override().
Function Documentation
rc()
RC_Channels & rc ()
Definition at line 314 of file RC_Channels.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration(), AnalogIn_ADS1115::_update(), AP_RCProtocol_Backend::add_input(), DigitalLPF< T >::apply(), AC_PI_2D::calc_filt_alpha(), calc_lowpass_alpha_dt(), AP_RCProtocol::check_added_uart(), AP_Tuning::check_input(), AP_Tuning::check_selector_switch(), RC_Channels::clear_overrides(), create_socket_server(), AP_RCProtocol_FPort::decode_downlink(), RC_Channel::do_aux_function_rc_override_enable(), AP_ICEngine::engine_control(), AP_Arming::estop_checks(), AP_RCProtocol_CRSF::get_bootstrap_baud_rate(), RC_Channels::get_channel_pos(), RC_Channels::get_override_mask(), AP_Mount_Backend::get_rc_input(), RC_Channels::has_active_overrides(), RC_Channel::has_override(), AP_RCProtocol_Backend::log_data(), loop(), luaV_execute(), AP_RunCam::map_rc_input_to_event(), SRV_Channel::output_ch(), print_radio_values(), AP_RCProtocol::process_byte(), AP_RCProtocol::process_pulse(), AP_IOMCU_FW::rcin_serial_update(), AP_IOMCU_FW::rcin_update(), RC_Channel::read_3pos_switch(), AP_RSSI::read_channel_rssi(), RC_Channel::run_aux_function(), AP_Button::run_aux_functions(), SRV_Channels::set_output_limit(), RC_Channel::set_override(), RC_Channels::set_override(), AP_Mount_Backend::set_rctargeting_on_rcinput_change(), setup(), AP_RCProtocol::should_search(), TEST(), AP_ICEngine::update(), RC_Channel::update(), AP_RCProtocol_CRSF::update(), AP_WindVane_Home::update_direction(), and GCS::update_sensor_status_flags().