APM:Libraries: libraries/RC_Channel/RC_Channels.cpp File Reference
RC_Channels.cpp File Reference
#include "RC_Channel_config.h"
#include <stdlib.h>
#include <cmath>
#include <AP_HAL/AP_HAL.h>
#include <AP_Math/AP_Math.h>
#include <AP_Logger/AP_Logger.h>
#include "RC_Channel.h"
Functions
RC_Channels & rc ()
Variables
const AP_HAL::HAL & hal
Function Documentation
rc()
RC_Channels & rc ()
Definition at line 314 of file RC_Channels.cpp.
Referenced by GCS_MAVLINK::_handle_command_preflight_calibration(), AnalogIn_ADS1115::_update(), AP_RCProtocol_Backend::add_input(), DigitalLPF< T >::apply(), AC_PI_2D::calc_filt_alpha(), calc_lowpass_alpha_dt(), AP_RCProtocol::check_added_uart(), AP_Tuning::check_input(), AP_Tuning::check_selector_switch(), RC_Channels::clear_overrides(), create_socket_server(), AP_RCProtocol_FPort::decode_downlink(), RC_Channel::do_aux_function_rc_override_enable(), AP_ICEngine::engine_control(), AP_Arming::estop_checks(), AP_RCProtocol_CRSF::get_bootstrap_baud_rate(), RC_Channels::get_channel_pos(), RC_Channels::get_override_mask(), AP_Mount_Backend::get_rc_input(), RC_Channels::has_active_overrides(), RC_Channel::has_override(), AP_RCProtocol_Backend::log_data(), loop(), luaV_execute(), AP_RunCam::map_rc_input_to_event(), SRV_Channel::output_ch(), print_radio_values(), AP_RCProtocol::process_byte(), AP_RCProtocol::process_pulse(), AP_IOMCU_FW::rcin_serial_update(), AP_IOMCU_FW::rcin_update(), RC_Channel::read_3pos_switch(), AP_RSSI::read_channel_rssi(), RC_Channel::run_aux_function(), AP_Button::run_aux_functions(), SRV_Channels::set_output_limit(), RC_Channel::set_override(), RC_Channels::set_override(), AP_Mount_Backend::set_rctargeting_on_rcinput_change(), setup(), AP_RCProtocol::should_search(), TEST(), AP_ICEngine::update(), RC_Channel::update(), AP_RCProtocol_CRSF::update(), AP_WindVane_Home::update_direction(), and GCS::update_sensor_status_flags().
Variable Documentation
hal
const AP_HAL::HAL& hal extern
The data_array uses 3 elements to perform the data transaction. The first element is a data byte that provides to FPGA's hardware the transaction type that will be realized inside the SPI module. Where:
╔═════════╦═════════╦══════════╦══════════╦══════════╦══════════╦══════════╦═══════════╗ ║ MSB ║ ║ ║ ║ ║ ║ ║ LSB ║ ╠═════════╬═════════╬══════════╬══════════╬══════════╬══════════╬══════════╬═══════════╣ ║ wr_addr ║ rd_addr ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ ╚═════════╩═════════╩══════════╩══════════╩══════════╩══════════╩══════════╩═══════════╝
╔═══════════╦═════════╦═════════╗ ║ Register ║ wr_addr ║ rd_addr ║ ╠═══════════╬═════════╬═════════╣ ║ write ║ 0 ║ X ║ ╠═══════════╬═════════╬═════════╣ ║ read ║ X ║ 0 ║ ╠═══════════╬═════════╬═════════╣ ║ status ║ 1 ║ 1 ║ ╚═══════════╩═════════╩═════════╝
So, to perform a write transaction in the SPI module it's necessary to send. E.g: 0b 01xx xxxx And to a read transaction.. 0b 10xx xxxx
The PWM frequency is always even and the duty cycle percentage odd. E.g: pwm_01: Address 0x0000 frequency : Address 0x0001 duty cycle pwm_02: Address 0x0002 frequency Eg of allowed values: // PWM channel in 100Hz uint16_t freq = 100;
// duty cycle in (1823/65535) that's 2.78% of 100Hz: // the signal will hold high until 278 usec uint16_t duty = 1823;
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.