APM:Libraries: libraries/AP_HAL_Linux/RCOutput_AioPRU.cpp File Reference
RCOutput_AioPRU.cpp File Reference
#include "RCOutput_AioPRU.h"
#include <fcntl.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <unistd.h>
#include <AP_HAL/AP_HAL.h>
#include "../../Tools/Linux_HAL_Essentials/pru/aiopru/RcAioPRU_BBBLUE_bin.h"
Functions
static void catch_sigbus (int sig)
Function Documentation
catch_sigbus()
static void catch_sigbus (int sig) static
Definition at line 33 of file RCOutput_AioPRU.cpp.
Referenced by Linux::RCOutput_AioPRU::init(), Linux::RCOutput_PRU::init(), and Linux::RCOutput_ZYNQ::init().