APM:Libraries: libraries/AP_RCProtocol/examples/RCProtocolTest/RCProtocolTest.cpp File Reference
RCProtocolTest.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_RCProtocol/AP_RCProtocol.h>
#include <AP_SerialManager/AP_SerialManager.h>
#include <RC_Channel/RC_Channel.h>
#include <AP_VideoTX/AP_VideoTX.h>
#include <stdio.h>
#include <RC_Channel/RC_Channels_VarInfo.h>
Classes
class RC_Channel_Example
class RC_Channels_Example
Macros
#define RC_CHANNELS_SUBCLASS RC_Channels_Example
#define RC_CHANNEL_SUBCLASS RC_Channel_Example
Functions
void setup ()
void loop ()
static void delay_ms (uint32_t ms)
static bool check_result (const char *name, bool bytes, const uint16_t *values, uint8_t nvalues)
static bool test_byte_protocol (const char *name, uint32_t baudrate, const uint8_t *bytes, uint8_t nbytes, const uint16_t *values, uint8_t nvalues, uint8_t repeats, uint8_t pause_at)
static void send_bit (uint8_t bit, uint32_t baudrate, bool inverted)
static void send_byte (uint8_t b, uint32_t baudrate, bool inverted)
static void send_pause (uint8_t b, uint32_t baudrate, uint32_t pause_us, bool inverted)
static bool test_pulse_protocol (const char *name, uint32_t baudrate, const uint8_t *bytes, uint8_t nbytes, const uint16_t *values, uint8_t nvalues, uint8_t repeats, uint8_t pause_at, bool inverted)
static bool test_protocol (const char *name, uint32_t baudrate, const uint8_t *bytes, uint8_t nbytes, const uint16_t *values, uint8_t nvalues, uint8_t repeats=1, int8_t pause_at=0, bool inverted=false)
static bool test_protocol_bytesonly (const char *name, uint32_t baudrate, const uint8_t *bytes, uint8_t nbytes, const uint16_t *values, uint8_t nvalues, uint8_t repeats=1, int8_t pause_at=0, bool inverted=false)
AP_HAL_MAIN ()
Variables
static RC_Channels_Example rchannels
static AP_SerialManager serial_manager
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static AP_VideoTX vtx
static AP_RCProtocol * rcprot
static uint32_t test_count
static uint32_t test_failures
Macro Definition Documentation
RC_CHANNEL_SUBCLASS
#define RC_CHANNEL_SUBCLASS RC_Channel_Example
Definition at line 48 of file RCProtocolTest.cpp.
RC_CHANNELS_SUBCLASS
#define RC_CHANNELS_SUBCLASS RC_Channels_Example
Definition at line 47 of file RCProtocolTest.cpp.
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
check_result()
static bool check_result (const char * name, bool bytes, const uint16_t * values, uint8_t nvalues) static
Definition at line 81 of file RCProtocolTest.cpp.
Referenced by test_byte_protocol(), and test_pulse_protocol().
delay_ms()
static void delay_ms (uint32_t ms) static
Definition at line 64 of file RCProtocolTest.cpp.
Referenced by AP_BoardConfig::init(), setup(), AP_FlashIface_JEDEC::start_erase_offset(), AP_FlashIface_JEDEC::start_mass_erase(), AP_FlashIface_JEDEC::start_sector_erase(), test_byte_protocol(), test_mass_erase(), test_sector_erase(), AP_Parachute::update(), SITL::Vicon::update_vicon_position_estimate(), AP_AHRS::writeBodyFrameOdom(), NavEKF3::writeBodyFrameOdom(), NavEKF3_core::writeBodyFrameOdom(), AP_AHRS::writeExtNavData(), AP_DAL::writeExtNavData(), NavEKF2::writeExtNavData(), NavEKF2_core::writeExtNavData(), NavEKF3::writeExtNavData(), NavEKF3_core::writeExtNavData(), AP_AHRS::writeExtNavVelData(), AP_DAL::writeExtNavVelData(), NavEKF2::writeExtNavVelData(), NavEKF2_core::writeExtNavVelData(), NavEKF3::writeExtNavVelData(), and NavEKF3_core::writeExtNavVelData().
loop()
void loop (void)
Definition at line 285 of file RCProtocolTest.cpp.
send_bit()
static void send_bit (uint8_t bit, uint32_t baudrate, bool inverted) static
Definition at line 149 of file RCProtocolTest.cpp.
Referenced by send_byte(), and send_pause().
send_byte()
static void send_byte (uint8_t b, uint32_t baudrate, bool inverted) static
Definition at line 175 of file RCProtocolTest.cpp.
Referenced by test_pulse_protocol().
send_pause()
static void send_pause (uint8_t b, uint32_t baudrate, uint32_t pause_us, bool inverted) static
Definition at line 199 of file RCProtocolTest.cpp.
Referenced by test_pulse_protocol().
setup()
void setup (void)
Definition at line 74 of file RCProtocolTest.cpp.
test_byte_protocol()
static bool test_byte_protocol (const char * name, uint32_t baudrate, const uint8_t * bytes, uint8_t nbytes, const uint16_t * values, uint8_t nvalues, uint8_t repeats, uint8_t pause_at) static
Definition at line 127 of file RCProtocolTest.cpp.
Referenced by test_protocol(), and test_protocol_bytesonly().
test_protocol()
static bool test_protocol (const char * name, uint32_t baudrate, const uint8_t * bytes, uint8_t nbytes, const uint16_t * values, uint8_t nvalues, uint8_t repeats = 1, int8_t pause_at = 0, bool inverted = false) static
Definition at line 236 of file RCProtocolTest.cpp.
Referenced by loop().
test_protocol_bytesonly()
static bool test_protocol_bytesonly (const char * name, uint32_t baudrate, const uint8_t * bytes, uint8_t nbytes, const uint16_t * values, uint8_t nvalues, uint8_t repeats = 1, int8_t pause_at = 0, bool inverted = false) static
Definition at line 261 of file RCProtocolTest.cpp.
Referenced by loop().
test_pulse_protocol()
static bool test_pulse_protocol (const char * name, uint32_t baudrate, const uint8_t * bytes, uint8_t nbytes, const uint16_t * values, uint8_t nvalues, uint8_t repeats, uint8_t pause_at, bool inverted) static
Definition at line 210 of file RCProtocolTest.cpp.
Referenced by test_protocol(), and test_protocol_bytesonly().
Variable Documentation
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
This file test realloc failure on ExpandingString
Definition at line 55 of file RCProtocolTest.cpp.
Referenced by delay_ms(), and setup().
rchannels
RC_Channels_Example rchannels static
Definition at line 52 of file RCProtocolTest.cpp.
rcprot
AP_RCProtocol* rcprot static
Definition at line 59 of file RCProtocolTest.cpp.
Referenced by check_result(), send_bit(), test_byte_protocol(), test_protocol(), and test_protocol_bytesonly().
serial_manager
AP_SerialManager serial_manager static
Definition at line 53 of file RCProtocolTest.cpp.
test_count
uint32_t test_count static
Definition at line 61 of file RCProtocolTest.cpp.
Referenced by loop().
test_failures
uint32_t test_failures static
Definition at line 62 of file RCProtocolTest.cpp.
Referenced by check_result(), and loop().
vtx
AP_VideoTX vtx static
Definition at line 57 of file RCProtocolTest.cpp.
Referenced by AP_SmartAudio::loop(), AP_SmartAudio::parse_response_buffer(), AP_SmartAudio::send_request(), AP_Vehicle::setup(), AP_SmartAudio::update_vtx_params(), and AP_SmartAudio::update_vtx_settings().