APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/scaleddecode.c File Reference
scaleddecode.c File Reference
#include "scaleddecode.h"
#include "fielddecode.h"
Functions
float float32ScaledFromBitfield (unsigned int value, float min, float invscaler)
Compute a float using inverse floating point scaling from the base integer type used for bitfields.
float float32ScaledFrom4UnsignedBeBytes (const uint8_t *bytes, int *index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 4 unsigned bytes in big endian order.
float float32ScaledFrom4UnsignedLeBytes (const uint8_t *bytes, int *index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 4 unsigned bytes in little endian order.
float float32ScaledFrom4SignedBeBytes (const uint8_t *bytes, int *index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 4 signed bytes in big endian order.
float float32ScaledFrom4SignedLeBytes (const uint8_t *bytes, int *index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 4 signed bytes in little endian order.
float float32ScaledFrom3UnsignedBeBytes (const uint8_t *bytes, int *index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 3 unsigned bytes in big endian order.
float float32ScaledFrom3UnsignedLeBytes (const uint8_t *bytes, int *index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 3 unsigned bytes in little endian order.
float float32ScaledFrom3SignedBeBytes (const uint8_t *bytes, int *index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 3 signed bytes in big endian order.
float float32ScaledFrom3SignedLeBytes (const uint8_t *bytes, int *index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 3 signed bytes in little endian order.
float float32ScaledFrom2UnsignedBeBytes (const uint8_t *bytes, int *index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 2 unsigned bytes in big endian order.
float float32ScaledFrom2UnsignedLeBytes (const uint8_t *bytes, int *index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 2 unsigned bytes in little endian order.
float float32ScaledFrom2SignedBeBytes (const uint8_t *bytes, int *index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 2 signed bytes in big endian order.
float float32ScaledFrom2SignedLeBytes (const uint8_t *bytes, int *index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 2 signed bytes in little endian order.
float float32ScaledFrom1UnsignedBytes (const uint8_t *bytes, int *index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 1 unsigned byte.
float float32ScaledFrom1SignedBytes (const uint8_t *bytes, int *index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 1 signed byte.
uint32_t uint32ScaledFromBitfield (unsigned int value, int32_t min, uint32_t divisor)
Compute a uint32_t using inverse integer scaling from the base integer type used for bitfields.
uint32_t uint32ScaledFrom4UnsignedBeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in big endian order.
uint32_t uint32ScaledFrom4UnsignedLeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in little endian order.
uint32_t uint32ScaledFrom4SignedBeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 4 signed bytes in big endian order.
uint32_t uint32ScaledFrom4SignedLeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 4 signed bytes in little endian order.
uint32_t uint32ScaledFrom3UnsignedBeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in big endian order.
uint32_t uint32ScaledFrom3UnsignedLeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in little endian order.
uint32_t uint32ScaledFrom3SignedBeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 3 signed bytes in big endian order.
uint32_t uint32ScaledFrom3SignedLeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 3 signed bytes in little endian order.
uint32_t uint32ScaledFrom2UnsignedBeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
uint32_t uint32ScaledFrom2UnsignedLeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
uint32_t uint32ScaledFrom2SignedBeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
uint32_t uint32ScaledFrom2SignedLeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
uint32_t uint32ScaledFrom1UnsignedBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 1 unsigned byte.
uint32_t uint32ScaledFrom1SignedBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 1 signed byte.
int32_t int32ScaledFromBitfield (unsigned int value, int32_t min, uint32_t divisor)
Compute a int32_t using inverse integer scaling from the base integer type used for bitfields.
int32_t int32ScaledFrom4UnsignedBeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in big endian order.
int32_t int32ScaledFrom4UnsignedLeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in little endian order.
int32_t int32ScaledFrom4SignedBeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 4 signed bytes in big endian order.
int32_t int32ScaledFrom4SignedLeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 4 signed bytes in little endian order.
int32_t int32ScaledFrom3UnsignedBeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in big endian order.
int32_t int32ScaledFrom3UnsignedLeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in little endian order.
int32_t int32ScaledFrom3SignedBeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 3 signed bytes in big endian order.
int32_t int32ScaledFrom3SignedLeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 3 signed bytes in little endian order.
int32_t int32ScaledFrom2UnsignedBeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
int32_t int32ScaledFrom2UnsignedLeBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
int32_t int32ScaledFrom2SignedBeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
int32_t int32ScaledFrom2SignedLeBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
int32_t int32ScaledFrom1UnsignedBytes (const uint8_t *bytes, int *index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 1 unsigned byte.
int32_t int32ScaledFrom1SignedBytes (const uint8_t *bytes, int *index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 1 signed byte.
uint16_t uint16ScaledFromBitfield (unsigned int value, int16_t min, uint16_t divisor)
Compute a uint16_t using inverse integer scaling from the base integer type used for bitfields.
uint16_t uint16ScaledFrom2UnsignedBeBytes (const uint8_t *bytes, int *index, int16_t min, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
uint16_t uint16ScaledFrom2UnsignedLeBytes (const uint8_t *bytes, int *index, int16_t min, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
uint16_t uint16ScaledFrom2SignedBeBytes (const uint8_t *bytes, int *index, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
uint16_t uint16ScaledFrom2SignedLeBytes (const uint8_t *bytes, int *index, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
uint16_t uint16ScaledFrom1UnsignedBytes (const uint8_t *bytes, int *index, int16_t min, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 1 unsigned byte.
uint16_t uint16ScaledFrom1SignedBytes (const uint8_t *bytes, int *index, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 1 signed byte.
int16_t int16ScaledFromBitfield (unsigned int value, int16_t min, uint16_t divisor)
Compute a int16_t using inverse integer scaling from the base integer type used for bitfields.
int16_t int16ScaledFrom2UnsignedBeBytes (const uint8_t *bytes, int *index, int16_t min, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
int16_t int16ScaledFrom2UnsignedLeBytes (const uint8_t *bytes, int *index, int16_t min, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
int16_t int16ScaledFrom2SignedBeBytes (const uint8_t *bytes, int *index, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
int16_t int16ScaledFrom2SignedLeBytes (const uint8_t *bytes, int *index, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
int16_t int16ScaledFrom1UnsignedBytes (const uint8_t *bytes, int *index, int16_t min, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 1 unsigned byte.
int16_t int16ScaledFrom1SignedBytes (const uint8_t *bytes, int *index, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 1 signed byte.
uint8_t uint8ScaledFromBitfield (unsigned int value, int8_t min, uint8_t divisor)
Compute a uint8_t using inverse integer scaling from the base integer type used for bitfields.
uint8_t uint8ScaledFrom1UnsignedBytes (const uint8_t *bytes, int *index, int8_t min, uint8_t divisor)
Decode a uint8_t from a byte stream by inverse integer scaling from 1 unsigned byte.
uint8_t uint8ScaledFrom1SignedBytes (const uint8_t *bytes, int *index, uint8_t divisor)
Decode a uint8_t from a byte stream by inverse integer scaling from 1 signed byte.
int8_t int8ScaledFromBitfield (unsigned int value, int8_t min, uint8_t divisor)
Compute a int8_t using inverse integer scaling from the base integer type used for bitfields.
int8_t int8ScaledFrom1UnsignedBytes (const uint8_t *bytes, int *index, int8_t min, uint8_t divisor)
Decode a int8_t from a byte stream by inverse integer scaling from 1 unsigned byte.
int8_t int8ScaledFrom1SignedBytes (const uint8_t *bytes, int *index, uint8_t divisor)
Decode a int8_t from a byte stream by inverse integer scaling from 1 signed byte.
Function Documentation
float32ScaledFrom1SignedBytes()
float float32ScaledFrom1SignedBytes (const uint8_t * bytes, int * index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 1 signed byte.
Decode a float from a byte stream by inverse floating point scaling from 1 signed byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be decoded.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = min + encoded*invscaler.
Definition at line 264 of file scaleddecode.c.
Referenced by decodeECU_RPMLoopCalibrationPacketStructure(), and decodeECU_TelemetrySlow1PacketStructure().
float32ScaledFrom1UnsignedBytes()
float float32ScaledFrom1UnsignedBytes (const uint8_t * bytes, int * index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 1 unsigned byte.
Decode a float from a byte stream by inverse floating point scaling from 1 unsigned byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = encoded*invscaler.
Definition at line 247 of file scaleddecode.c.
Referenced by decodeECU_GovernorSettingsPacketStructure(), decodeECU_RPMLoopCalibrationPacketStructure(), decodeECU_SetThrottleCurveElementPacket(), decodeECU_TelemetryFastPacket(), decodeECU_TelemetryFastPacketStructure(), decodeECU_TelemetrySlow0PacketStructure(), decodeECU_TelemetrySlow1PacketStructure(), decodeECU_TelemetrySlow2PacketStructure(), decodeECU_ThrottleCurve1Packet(), decodeECU_ThrottleCurvePacket(), decodeESC_ProtectionValuesPacket(), decodeESC_ProtectionValuesPacketStructure(), decodeESC_StatusCPacket(), and decodeESC_StatusCPacketStructure().
float32ScaledFrom2SignedBeBytes()
float float32ScaledFrom2SignedBeBytes (const uint8_t * bytes, int * index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 2 signed bytes in big endian order.
Decode a float from a byte stream by inverse floating point scaling from 2 signed bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be decoded.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = min + encoded*invscaler.
Definition at line 214 of file scaleddecode.c.
Referenced by decodeECU_PumpDebugPacketStructure(), decodeESC_ControlLoopOutputsPacket(), decodeESC_ControlLoopOutputsPacketStructure(), decodeESC_TelltaleValuesPacket(), and decodeESC_TelltaleValuesPacketStructure().
float32ScaledFrom2SignedLeBytes()
float float32ScaledFrom2SignedLeBytes (const uint8_t * bytes, int * index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 2 signed bytes in little endian order.
Decode a float from a byte stream by inverse floating point scaling from 2 signed bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be decoded.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = min + encoded*invscaler.
Definition at line 231 of file scaleddecode.c.
float32ScaledFrom2UnsignedBeBytes()
float float32ScaledFrom2UnsignedBeBytes (const uint8_t * bytes, int * index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 2 unsigned bytes in big endian order.
Decode a float from a byte stream by inverse floating point scaling from 2 unsigned bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = encoded*invscaler.
Definition at line 181 of file scaleddecode.c.
Referenced by decodeECU_CHTLoopSettingsPacket(), decodeECU_CHTLoopSettingsPacketStructure(), decodeECU_Pump2ConfigPacketStructure(), decodeECU_PumpConfigPacketStructure(), decodeECU_PumpDebugPacketStructure(), decodeECU_RPMLoopCalibrationPacketStructure(), decodeECU_TelemetrySlow0PacketStructure(), decodeECU_TelemetrySlow1PacketStructure(), decodeECU_TelemetrySlow2PacketStructure(), decodeECU_ThrottleCommandPacket(), decodeESC_ControlLoopCommon_t(), decodeESC_RPMControlLoopSettings_t(), and decodeESC_RPMControlLoopSettingsPacketStructure().
float32ScaledFrom2UnsignedLeBytes()
float float32ScaledFrom2UnsignedLeBytes (const uint8_t * bytes, int * index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 2 unsigned bytes in little endian order.
Decode a float from a byte stream by inverse floating point scaling from 2 unsigned bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = encoded*invscaler.
Definition at line 197 of file scaleddecode.c.
float32ScaledFrom3SignedBeBytes()
float float32ScaledFrom3SignedBeBytes (const uint8_t * bytes, int * index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 3 signed bytes in big endian order.
Decode a float from a byte stream by inverse floating point scaling from 3 signed bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be decoded.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = min + encoded*invscaler.
Definition at line 148 of file scaleddecode.c.
float32ScaledFrom3SignedLeBytes()
float float32ScaledFrom3SignedLeBytes (const uint8_t * bytes, int * index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 3 signed bytes in little endian order.
Decode a float from a byte stream by inverse floating point scaling from 3 signed bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be decoded.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = min + encoded*invscaler.
Definition at line 165 of file scaleddecode.c.
float32ScaledFrom3UnsignedBeBytes()
float float32ScaledFrom3UnsignedBeBytes (const uint8_t * bytes, int * index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 3 unsigned bytes in big endian order.
Decode a float from a byte stream by inverse floating point scaling from 3 unsigned bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = encoded*invscaler.
Definition at line 115 of file scaleddecode.c.
float32ScaledFrom3UnsignedLeBytes()
float float32ScaledFrom3UnsignedLeBytes (const uint8_t * bytes, int * index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 3 unsigned bytes in little endian order.
Decode a float from a byte stream by inverse floating point scaling from 3 unsigned bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = encoded*invscaler.
Definition at line 131 of file scaleddecode.c.
float32ScaledFrom4SignedBeBytes()
float float32ScaledFrom4SignedBeBytes (const uint8_t * bytes, int * index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 4 signed bytes in big endian order.
Decode a float from a byte stream by inverse floating point scaling from 4 signed bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be decoded.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = min + encoded*invscaler.
Definition at line 82 of file scaleddecode.c.
float32ScaledFrom4SignedLeBytes()
float float32ScaledFrom4SignedLeBytes (const uint8_t * bytes, int * index, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 4 signed bytes in little endian order.
Decode a float from a byte stream by inverse floating point scaling from 4 signed bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be decoded.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = min + encoded*invscaler.
Definition at line 99 of file scaleddecode.c.
float32ScaledFrom4UnsignedBeBytes()
float float32ScaledFrom4UnsignedBeBytes (const uint8_t * bytes, int * index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 4 unsigned bytes in big endian order.
Decode a float from a byte stream by inverse floating point scaling from 4 unsigned bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = encoded*invscaler.
Definition at line 49 of file scaleddecode.c.
float32ScaledFrom4UnsignedLeBytes()
float float32ScaledFrom4UnsignedLeBytes (const uint8_t * bytes, int * index, float min, float invscaler)
Decode a float from a byte stream by inverse floating point scaling from 4 unsigned bytes in little endian order.
Decode a float from a byte stream by inverse floating point scaling from 4 unsigned bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
invscaler is multiplied by the decoded integer to create the return value. invscaler should be the inverse of the scaler given to the encode function.
Returns
the correctly scaled decoded value: return = encoded*invscaler.
Definition at line 65 of file scaleddecode.c.
float32ScaledFromBitfield()
float float32ScaledFromBitfield (unsigned int value, float min, float invscaler)
Compute a float using inverse floating point scaling from the base integer type used for bitfields.
Compute a float using inverse floating point scaling from the base integer type used for bitfields.
Parameters
value is the integer bitfield number to inverse scale
min is the minimum value that can be represented.
invscaler is multiplied by the integer to create the return value. invscaler should be the inverse of the scaler given to the scaling function.
Returns
the correctly scaled decoded value: return = min + value*invscaler.
Definition at line 33 of file scaleddecode.c.
int16ScaledFrom1SignedBytes()
int16_t int16ScaledFrom1SignedBytes (const uint8_t * bytes, int * index, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 1 signed byte.
Decode a int16_t from a byte stream by inverse integer scaling from 1 signed byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 940 of file scaleddecode.c.
int16ScaledFrom1UnsignedBytes()
int16_t int16ScaledFrom1UnsignedBytes (const uint8_t * bytes, int * index, int16_t min, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Decode a int16_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 925 of file scaleddecode.c.
int16ScaledFrom2SignedBeBytes()
int16_t int16ScaledFrom2SignedBeBytes (const uint8_t * bytes, int * index, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
Decode a int16_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 894 of file scaleddecode.c.
int16ScaledFrom2SignedLeBytes()
int16_t int16ScaledFrom2SignedLeBytes (const uint8_t * bytes, int * index, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
Decode a int16_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 909 of file scaleddecode.c.
int16ScaledFrom2UnsignedBeBytes()
int16_t int16ScaledFrom2UnsignedBeBytes (const uint8_t * bytes, int * index, int16_t min, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
Decode a int16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 863 of file scaleddecode.c.
int16ScaledFrom2UnsignedLeBytes()
int16_t int16ScaledFrom2UnsignedLeBytes (const uint8_t * bytes, int * index, int16_t min, uint16_t divisor)
Decode a int16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
Decode a int16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 879 of file scaleddecode.c.
int16ScaledFromBitfield()
int16_t int16ScaledFromBitfield (unsigned int value, int16_t min, uint16_t divisor)
Compute a int16_t using inverse integer scaling from the base integer type used for bitfields.
Compute a int16_t using inverse integer scaling from the base integer type used for bitfields.
Parameters
value is the integer bitfield number to inverse scale
min is the minimum value that can be represented.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 847 of file scaleddecode.c.
int32ScaledFrom1SignedBytes()
int32_t int32ScaledFrom1SignedBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 1 signed byte.
Decode a int32_t from a byte stream by inverse integer scaling from 1 signed byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 726 of file scaleddecode.c.
int32ScaledFrom1UnsignedBytes()
int32_t int32ScaledFrom1UnsignedBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Decode a int32_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 711 of file scaleddecode.c.
int32ScaledFrom2SignedBeBytes()
int32_t int32ScaledFrom2SignedBeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 680 of file scaleddecode.c.
int32ScaledFrom2SignedLeBytes()
int32_t int32ScaledFrom2SignedLeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 695 of file scaleddecode.c.
int32ScaledFrom2UnsignedBeBytes()
int32_t int32ScaledFrom2UnsignedBeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 649 of file scaleddecode.c.
int32ScaledFrom2UnsignedLeBytes()
int32_t int32ScaledFrom2UnsignedLeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 665 of file scaleddecode.c.
int32ScaledFrom3SignedBeBytes()
int32_t int32ScaledFrom3SignedBeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 3 signed bytes in big endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 3 signed bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 618 of file scaleddecode.c.
int32ScaledFrom3SignedLeBytes()
int32_t int32ScaledFrom3SignedLeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 3 signed bytes in little endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 3 signed bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 633 of file scaleddecode.c.
int32ScaledFrom3UnsignedBeBytes()
int32_t int32ScaledFrom3UnsignedBeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in big endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 587 of file scaleddecode.c.
int32ScaledFrom3UnsignedLeBytes()
int32_t int32ScaledFrom3UnsignedLeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in little endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 603 of file scaleddecode.c.
int32ScaledFrom4SignedBeBytes()
int32_t int32ScaledFrom4SignedBeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 4 signed bytes in big endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 4 signed bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 556 of file scaleddecode.c.
int32ScaledFrom4SignedLeBytes()
int32_t int32ScaledFrom4SignedLeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 4 signed bytes in little endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 4 signed bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 571 of file scaleddecode.c.
int32ScaledFrom4UnsignedBeBytes()
int32_t int32ScaledFrom4UnsignedBeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in big endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 525 of file scaleddecode.c.
int32ScaledFrom4UnsignedLeBytes()
int32_t int32ScaledFrom4UnsignedLeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a int32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in little endian order.
Decode a int32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 541 of file scaleddecode.c.
int32ScaledFromBitfield()
int32_t int32ScaledFromBitfield (unsigned int value, int32_t min, uint32_t divisor)
Compute a int32_t using inverse integer scaling from the base integer type used for bitfields.
Compute a int32_t using inverse integer scaling from the base integer type used for bitfields.
Parameters
value is the integer bitfield number to inverse scale
min is the minimum value that can be represented.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 509 of file scaleddecode.c.
int8ScaledFrom1SignedBytes()
int8_t int8ScaledFrom1SignedBytes (const uint8_t * bytes, int * index, uint8_t divisor)
Decode a int8_t from a byte stream by inverse integer scaling from 1 signed byte.
Decode a int8_t from a byte stream by inverse integer scaling from 1 signed byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 1030 of file scaleddecode.c.
int8ScaledFrom1UnsignedBytes()
int8_t int8ScaledFrom1UnsignedBytes (const uint8_t * bytes, int * index, int8_t min, uint8_t divisor)
Decode a int8_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Decode a int8_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 1015 of file scaleddecode.c.
int8ScaledFromBitfield()
int8_t int8ScaledFromBitfield (unsigned int value, int8_t min, uint8_t divisor)
Compute a int8_t using inverse integer scaling from the base integer type used for bitfields.
Compute a int8_t using inverse integer scaling from the base integer type used for bitfields.
Parameters
value is the integer bitfield number to inverse scale
min is the minimum value that can be represented.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 999 of file scaleddecode.c.
uint16ScaledFrom1SignedBytes()
uint16_t uint16ScaledFrom1SignedBytes (const uint8_t * bytes, int * index, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 1 signed byte.
Decode a uint16_t from a byte stream by inverse integer scaling from 1 signed byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 833 of file scaleddecode.c.
uint16ScaledFrom1UnsignedBytes()
uint16_t uint16ScaledFrom1UnsignedBytes (const uint8_t * bytes, int * index, int16_t min, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Decode a uint16_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 818 of file scaleddecode.c.
uint16ScaledFrom2SignedBeBytes()
uint16_t uint16ScaledFrom2SignedBeBytes (const uint8_t * bytes, int * index, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
Decode a uint16_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 787 of file scaleddecode.c.
uint16ScaledFrom2SignedLeBytes()
uint16_t uint16ScaledFrom2SignedLeBytes (const uint8_t * bytes, int * index, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
Decode a uint16_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 802 of file scaleddecode.c.
uint16ScaledFrom2UnsignedBeBytes()
uint16_t uint16ScaledFrom2UnsignedBeBytes (const uint8_t * bytes, int * index, int16_t min, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
Decode a uint16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 756 of file scaleddecode.c.
uint16ScaledFrom2UnsignedLeBytes()
uint16_t uint16ScaledFrom2UnsignedLeBytes (const uint8_t * bytes, int * index, int16_t min, uint16_t divisor)
Decode a uint16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
Decode a uint16_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 772 of file scaleddecode.c.
uint16ScaledFromBitfield()
uint16_t uint16ScaledFromBitfield (unsigned int value, int16_t min, uint16_t divisor)
Compute a uint16_t using inverse integer scaling from the base integer type used for bitfields.
Compute a uint16_t using inverse integer scaling from the base integer type used for bitfields.
Parameters
value is the integer bitfield number to inverse scale
min is the minimum value that can be represented.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 740 of file scaleddecode.c.
uint32ScaledFrom1SignedBytes()
uint32_t uint32ScaledFrom1SignedBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 1 signed byte.
Decode a uint32_t from a byte stream by inverse integer scaling from 1 signed byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 495 of file scaleddecode.c.
uint32ScaledFrom1UnsignedBytes()
uint32_t uint32ScaledFrom1UnsignedBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Decode a uint32_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 480 of file scaleddecode.c.
uint32ScaledFrom2SignedBeBytes()
uint32_t uint32ScaledFrom2SignedBeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 2 signed bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 449 of file scaleddecode.c.
uint32ScaledFrom2SignedLeBytes()
uint32_t uint32ScaledFrom2SignedLeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 2 signed bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 464 of file scaleddecode.c.
uint32ScaledFrom2UnsignedBeBytes()
uint32_t uint32ScaledFrom2UnsignedBeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 418 of file scaleddecode.c.
uint32ScaledFrom2UnsignedLeBytes()
uint32_t uint32ScaledFrom2UnsignedLeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 2 unsigned bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 434 of file scaleddecode.c.
uint32ScaledFrom3SignedBeBytes()
uint32_t uint32ScaledFrom3SignedBeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 3 signed bytes in big endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 3 signed bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 387 of file scaleddecode.c.
uint32ScaledFrom3SignedLeBytes()
uint32_t uint32ScaledFrom3SignedLeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 3 signed bytes in little endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 3 signed bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 402 of file scaleddecode.c.
uint32ScaledFrom3UnsignedBeBytes()
uint32_t uint32ScaledFrom3UnsignedBeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in big endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 356 of file scaleddecode.c.
uint32ScaledFrom3UnsignedLeBytes()
uint32_t uint32ScaledFrom3UnsignedLeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in little endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 3 unsigned bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 372 of file scaleddecode.c.
uint32ScaledFrom4SignedBeBytes()
uint32_t uint32ScaledFrom4SignedBeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 4 signed bytes in big endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 4 signed bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 325 of file scaleddecode.c.
uint32ScaledFrom4SignedLeBytes()
uint32_t uint32ScaledFrom4SignedLeBytes (const uint8_t * bytes, int * index, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 4 signed bytes in little endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 4 signed bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 340 of file scaleddecode.c.
uint32ScaledFrom4UnsignedBeBytes()
uint32_t uint32ScaledFrom4UnsignedBeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in big endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in big endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 294 of file scaleddecode.c.
uint32ScaledFrom4UnsignedLeBytes()
uint32_t uint32ScaledFrom4UnsignedLeBytes (const uint8_t * bytes, int * index, int32_t min, uint32_t divisor)
Decode a uint32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in little endian order.
Decode a uint32_t from a byte stream by inverse integer scaling from 4 unsigned bytes in little endian order.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 310 of file scaleddecode.c.
uint32ScaledFromBitfield()
uint32_t uint32ScaledFromBitfield (unsigned int value, int32_t min, uint32_t divisor)
Compute a uint32_t using inverse integer scaling from the base integer type used for bitfields.
Compute a uint32_t using inverse integer scaling from the base integer type used for bitfields.
Parameters
value is the integer bitfield number to inverse scale
min is the minimum value that can be represented.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 278 of file scaleddecode.c.
uint8ScaledFrom1SignedBytes()
uint8_t uint8ScaledFrom1SignedBytes (const uint8_t * bytes, int * index, uint8_t divisor)
Decode a uint8_t from a byte stream by inverse integer scaling from 1 signed byte.
Decode a uint8_t from a byte stream by inverse integer scaling from 1 signed byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = encoded/divisor.
Definition at line 985 of file scaleddecode.c.
uint8ScaledFrom1UnsignedBytes()
uint8_t uint8ScaledFrom1UnsignedBytes (const uint8_t * bytes, int * index, int8_t min, uint8_t divisor)
Decode a uint8_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Decode a uint8_t from a byte stream by inverse integer scaling from 1 unsigned byte.
Parameters
bytes is a pointer to the byte stream to decode.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be decoded.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 970 of file scaleddecode.c.
uint8ScaledFromBitfield()
uint8_t uint8ScaledFromBitfield (unsigned int value, int8_t min, uint8_t divisor)
Compute a uint8_t using inverse integer scaling from the base integer type used for bitfields.
Compute a uint8_t using inverse integer scaling from the base integer type used for bitfields.
Parameters
value is the integer bitfield number to inverse scale
min is the minimum value that can be represented.
divisor is divided into the encoded integer to create the return value.
Returns
the correctly scaled decoded value: return = min + encoded/divisor.
Definition at line 954 of file scaleddecode.c.