APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/scaledencode.c File Reference
scaledencode.c File Reference
#include "scaledencode.h"
#include "fieldencode.h"
Functions
unsigned int float32ScaledToBitfield (float value, float min, float scaler, int bits)
Scale a float using floating point scaling to the base integer type used for bitfields.
void float32ScaledTo4UnsignedBeBytes (float value, uint8_t *bytes, int *index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 4 unsigned bytes in big endian order.
void float32ScaledTo4UnsignedLeBytes (float value, uint8_t *bytes, int *index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 4 unsigned bytes in little endian order.
void float32ScaledTo4SignedBeBytes (float value, uint8_t *bytes, int *index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 4 signed bytes in big endian order.
void float32ScaledTo4SignedLeBytes (float value, uint8_t *bytes, int *index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 4 signed bytes in little endian order.
void float32ScaledTo3UnsignedBeBytes (float value, uint8_t *bytes, int *index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 3 unsigned bytes in big endian order.
void float32ScaledTo3UnsignedLeBytes (float value, uint8_t *bytes, int *index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 3 unsigned bytes in little endian order.
void float32ScaledTo3SignedBeBytes (float value, uint8_t *bytes, int *index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 3 signed bytes in big endian order.
void float32ScaledTo3SignedLeBytes (float value, uint8_t *bytes, int *index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 3 signed bytes in little endian order.
void float32ScaledTo2UnsignedBeBytes (float value, uint8_t *bytes, int *index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 2 unsigned bytes in big endian order.
void float32ScaledTo2UnsignedLeBytes (float value, uint8_t *bytes, int *index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 2 unsigned bytes in little endian order.
void float32ScaledTo2SignedBeBytes (float value, uint8_t *bytes, int *index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 2 signed bytes in big endian order.
void float32ScaledTo2SignedLeBytes (float value, uint8_t *bytes, int *index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 2 signed bytes in little endian order.
void float32ScaledTo1UnsignedBytes (float value, uint8_t *bytes, int *index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 1 unsigned byte.
void float32ScaledTo1SignedBytes (float value, uint8_t *bytes, int *index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 1 signed byte.
unsigned int uint32ScaledToBitfield (uint32_t value, int32_t min, uint32_t scaler, int bits)
Scale a uint32_t using integer scaling to the base integer type used for bitfields.
void uint32ScaledTo4UnsignedBeBytes (uint32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in big endian order.
void uint32ScaledTo4UnsignedLeBytes (uint32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in little endian order.
void uint32ScaledTo4SignedBeBytes (uint32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 4 signed bytes in big endian order.
void uint32ScaledTo4SignedLeBytes (uint32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 4 signed bytes in little endian order.
void uint32ScaledTo3UnsignedBeBytes (uint32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in big endian order.
void uint32ScaledTo3UnsignedLeBytes (uint32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in little endian order.
void uint32ScaledTo3SignedBeBytes (uint32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 3 signed bytes in big endian order.
void uint32ScaledTo3SignedLeBytes (uint32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 3 signed bytes in little endian order.
void uint32ScaledTo2UnsignedBeBytes (uint32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
void uint32ScaledTo2UnsignedLeBytes (uint32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
void uint32ScaledTo2SignedBeBytes (uint32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
void uint32ScaledTo2SignedLeBytes (uint32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
void uint32ScaledTo1UnsignedBytes (uint32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 1 unsigned byte.
void uint32ScaledTo1SignedBytes (uint32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 1 signed byte.
unsigned int int32ScaledToBitfield (int32_t value, int32_t min, uint32_t scaler, int bits)
Scale a int32_t using integer scaling to the base integer type used for bitfields.
void int32ScaledTo4UnsignedBeBytes (int32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in big endian order.
void int32ScaledTo4UnsignedLeBytes (int32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in little endian order.
void int32ScaledTo4SignedBeBytes (int32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 4 signed bytes in big endian order.
void int32ScaledTo4SignedLeBytes (int32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 4 signed bytes in little endian order.
void int32ScaledTo3UnsignedBeBytes (int32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in big endian order.
void int32ScaledTo3UnsignedLeBytes (int32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in little endian order.
void int32ScaledTo3SignedBeBytes (int32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 3 signed bytes in big endian order.
void int32ScaledTo3SignedLeBytes (int32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 3 signed bytes in little endian order.
void int32ScaledTo2UnsignedBeBytes (int32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
void int32ScaledTo2UnsignedLeBytes (int32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
void int32ScaledTo2SignedBeBytes (int32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
void int32ScaledTo2SignedLeBytes (int32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
void int32ScaledTo1UnsignedBytes (int32_t value, uint8_t *bytes, int *index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 1 unsigned byte.
void int32ScaledTo1SignedBytes (int32_t value, uint8_t *bytes, int *index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 1 signed byte.
unsigned int uint16ScaledToBitfield (uint16_t value, int16_t min, uint16_t scaler, int bits)
Scale a uint16_t using integer scaling to the base integer type used for bitfields.
void uint16ScaledTo2UnsignedBeBytes (uint16_t value, uint8_t *bytes, int *index, int16_t min, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
void uint16ScaledTo2UnsignedLeBytes (uint16_t value, uint8_t *bytes, int *index, int16_t min, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
void uint16ScaledTo2SignedBeBytes (uint16_t value, uint8_t *bytes, int *index, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
void uint16ScaledTo2SignedLeBytes (uint16_t value, uint8_t *bytes, int *index, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
void uint16ScaledTo1UnsignedBytes (uint16_t value, uint8_t *bytes, int *index, int16_t min, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 1 unsigned byte.
void uint16ScaledTo1SignedBytes (uint16_t value, uint8_t *bytes, int *index, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 1 signed byte.
unsigned int int16ScaledToBitfield (int16_t value, int16_t min, uint16_t scaler, int bits)
Scale a int16_t using integer scaling to the base integer type used for bitfields.
void int16ScaledTo2UnsignedBeBytes (int16_t value, uint8_t *bytes, int *index, int16_t min, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
void int16ScaledTo2UnsignedLeBytes (int16_t value, uint8_t *bytes, int *index, int16_t min, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
void int16ScaledTo2SignedBeBytes (int16_t value, uint8_t *bytes, int *index, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
void int16ScaledTo2SignedLeBytes (int16_t value, uint8_t *bytes, int *index, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
void int16ScaledTo1UnsignedBytes (int16_t value, uint8_t *bytes, int *index, int16_t min, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 1 unsigned byte.
void int16ScaledTo1SignedBytes (int16_t value, uint8_t *bytes, int *index, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 1 signed byte.
unsigned int uint8ScaledToBitfield (uint8_t value, int8_t min, uint8_t scaler, int bits)
Scale a uint8_t using integer scaling to the base integer type used for bitfields.
void uint8ScaledTo1UnsignedBytes (uint8_t value, uint8_t *bytes, int *index, int8_t min, uint8_t scaler)
Encode a uint8_t on a byte stream by integer scaling to fit in 1 unsigned byte.
void uint8ScaledTo1SignedBytes (uint8_t value, uint8_t *bytes, int *index, uint8_t scaler)
Encode a uint8_t on a byte stream by integer scaling to fit in 1 signed byte.
unsigned int int8ScaledToBitfield (int8_t value, int8_t min, uint8_t scaler, int bits)
Scale a int8_t using integer scaling to the base integer type used for bitfields.
void int8ScaledTo1UnsignedBytes (int8_t value, uint8_t *bytes, int *index, int8_t min, uint8_t scaler)
Encode a int8_t on a byte stream by integer scaling to fit in 1 unsigned byte.
void int8ScaledTo1SignedBytes (int8_t value, uint8_t *bytes, int *index, uint8_t scaler)
Encode a int8_t on a byte stream by integer scaling to fit in 1 signed byte.
Function Documentation
float32ScaledTo1SignedBytes()
void float32ScaledTo1SignedBytes (float value, uint8_t * bytes, int * index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 1 signed byte.
Encode a float on a byte stream by floating point scaling to fit in 1 signed byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 469 of file scaledencode.c.
Referenced by encodeECU_RPMLoopCalibrationPacketStructure(), and encodeECU_TelemetrySlow1PacketStructure().
float32ScaledTo1UnsignedBytes()
void float32ScaledTo1UnsignedBytes (float value, uint8_t * bytes, int * index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 1 unsigned byte.
Encode a float on a byte stream by floating point scaling to fit in 1 unsigned byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 442 of file scaledencode.c.
Referenced by encodeECU_GovernorSettingsPacketStructure(), encodeECU_RPMLoopCalibrationPacketStructure(), encodeECU_SetThrottleCurveElementPacket(), encodeECU_TelemetryFastPacket(), encodeECU_TelemetryFastPacketStructure(), encodeECU_TelemetrySlow0PacketStructure(), encodeECU_TelemetrySlow1PacketStructure(), encodeECU_TelemetrySlow2PacketStructure(), encodeECU_ThrottleCurve1Packet(), encodeECU_ThrottleCurvePacket(), encodeESC_ProtectionValuesPacket(), encodeESC_ProtectionValuesPacketStructure(), encodeESC_StatusCPacket(), and encodeESC_StatusCPacketStructure().
float32ScaledTo2SignedBeBytes()
void float32ScaledTo2SignedBeBytes (float value, uint8_t * bytes, int * index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 2 signed bytes in big endian order.
Encode a float on a byte stream by floating point scaling to fit in 2 signed bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 371 of file scaledencode.c.
Referenced by encodeECU_PumpDebugPacketStructure(), encodeESC_ControlLoopOutputsPacket(), encodeESC_ControlLoopOutputsPacketStructure(), encodeESC_TelltaleValuesPacket(), and encodeESC_TelltaleValuesPacketStructure().
float32ScaledTo2SignedLeBytes()
void float32ScaledTo2SignedLeBytes (float value, uint8_t * bytes, int * index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 2 signed bytes in little endian order.
Encode a float on a byte stream by floating point scaling to fit in 2 signed bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 406 of file scaledencode.c.
float32ScaledTo2UnsignedBeBytes()
void float32ScaledTo2UnsignedBeBytes (float value, uint8_t * bytes, int * index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 2 unsigned bytes in big endian order.
Encode a float on a byte stream by floating point scaling to fit in 2 unsigned bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 316 of file scaledencode.c.
Referenced by encodeECU_CHTLoopSettingsPacket(), encodeECU_CHTLoopSettingsPacketStructure(), encodeECU_Pump2ConfigPacketStructure(), encodeECU_PumpConfigPacketStructure(), encodeECU_PumpDebugPacketStructure(), encodeECU_RPMLoopCalibrationPacketStructure(), encodeECU_TelemetrySlow0PacketStructure(), encodeECU_TelemetrySlow1PacketStructure(), encodeECU_TelemetrySlow2PacketStructure(), encodeECU_ThrottleCommandPacket(), encodeESC_ControlLoopCommon_t(), encodeESC_RPMControlLoopSettings_t(), and encodeESC_RPMControlLoopSettingsPacketStructure().
float32ScaledTo2UnsignedLeBytes()
void float32ScaledTo2UnsignedLeBytes (float value, uint8_t * bytes, int * index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 2 unsigned bytes in little endian order.
Encode a float on a byte stream by floating point scaling to fit in 2 unsigned bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 344 of file scaledencode.c.
float32ScaledTo3SignedBeBytes()
void float32ScaledTo3SignedBeBytes (float value, uint8_t * bytes, int * index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 3 signed bytes in big endian order.
Encode a float on a byte stream by floating point scaling to fit in 3 signed bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 245 of file scaledencode.c.
float32ScaledTo3SignedLeBytes()
void float32ScaledTo3SignedLeBytes (float value, uint8_t * bytes, int * index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 3 signed bytes in little endian order.
Encode a float on a byte stream by floating point scaling to fit in 3 signed bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 280 of file scaledencode.c.
float32ScaledTo3UnsignedBeBytes()
void float32ScaledTo3UnsignedBeBytes (float value, uint8_t * bytes, int * index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 3 unsigned bytes in big endian order.
Encode a float on a byte stream by floating point scaling to fit in 3 unsigned bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 190 of file scaledencode.c.
float32ScaledTo3UnsignedLeBytes()
void float32ScaledTo3UnsignedLeBytes (float value, uint8_t * bytes, int * index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 3 unsigned bytes in little endian order.
Encode a float on a byte stream by floating point scaling to fit in 3 unsigned bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 218 of file scaledencode.c.
float32ScaledTo4SignedBeBytes()
void float32ScaledTo4SignedBeBytes (float value, uint8_t * bytes, int * index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 4 signed bytes in big endian order.
Encode a float on a byte stream by floating point scaling to fit in 4 signed bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 119 of file scaledencode.c.
float32ScaledTo4SignedLeBytes()
void float32ScaledTo4SignedLeBytes (float value, uint8_t * bytes, int * index, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 4 signed bytes in little endian order.
Encode a float on a byte stream by floating point scaling to fit in 4 signed bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 154 of file scaledencode.c.
float32ScaledTo4UnsignedBeBytes()
void float32ScaledTo4UnsignedBeBytes (float value, uint8_t * bytes, int * index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 4 unsigned bytes in big endian order.
Encode a float on a byte stream by floating point scaling to fit in 4 unsigned bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 64 of file scaledencode.c.
float32ScaledTo4UnsignedLeBytes()
void float32ScaledTo4UnsignedLeBytes (float value, uint8_t * bytes, int * index, float min, float scaler)
Encode a float on a byte stream by floating point scaling to fit in 4 unsigned bytes in little endian order.
Encode a float on a byte stream by floating point scaling to fit in 4 unsigned bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 92 of file scaledencode.c.
float32ScaledToBitfield()
unsigned int float32ScaledToBitfield (float value, float min, float scaler, int bits)
Scale a float using floating point scaling to the base integer type used for bitfields.
Scale a float using floating point scaling to the base integer type used for bitfields.
Parameters
value is the number to scale.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer.
bits is the number of bits in the bitfield, used to limit the returned value.
Returns
(value-min)*scaler.
Definition at line 33 of file scaledencode.c.
int16ScaledTo1SignedBytes()
void int16ScaledTo1SignedBytes (int16_t value, uint8_t * bytes, int * index, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 1 signed byte.
Encode a int16_t on a byte stream by integer scaling to fit in 1 signed byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1552 of file scaledencode.c.
int16ScaledTo1UnsignedBytes()
void int16ScaledTo1UnsignedBytes (int16_t value, uint8_t * bytes, int * index, int16_t min, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Encode a int16_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1526 of file scaledencode.c.
int16ScaledTo2SignedBeBytes()
void int16ScaledTo2SignedBeBytes (int16_t value, uint8_t * bytes, int * index, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
Encode a int16_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1489 of file scaledencode.c.
int16ScaledTo2SignedLeBytes()
void int16ScaledTo2SignedLeBytes (int16_t value, uint8_t * bytes, int * index, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
Encode a int16_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1507 of file scaledencode.c.
int16ScaledTo2UnsignedBeBytes()
void int16ScaledTo2UnsignedBeBytes (int16_t value, uint8_t * bytes, int * index, int16_t min, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
Encode a int16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1440 of file scaledencode.c.
int16ScaledTo2UnsignedLeBytes()
void int16ScaledTo2UnsignedLeBytes (int16_t value, uint8_t * bytes, int * index, int16_t min, uint16_t scaler)
Encode a int16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
Encode a int16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1465 of file scaledencode.c.
int16ScaledToBitfield()
unsigned int int16ScaledToBitfield (int16_t value, int16_t min, uint16_t scaler, int bits)
Scale a int16_t using integer scaling to the base integer type used for bitfields.
Scale a int16_t using integer scaling to the base integer type used for bitfields.
Parameters
value is the number to scale.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer.
bits is the number of bits in the bitfield, used to limit the returned value.
Returns
(value-min)*scaler.
Definition at line 1410 of file scaledencode.c.
int32ScaledTo1SignedBytes()
void int32ScaledTo1SignedBytes (int32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 1 signed byte.
Encode a int32_t on a byte stream by integer scaling to fit in 1 signed byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1220 of file scaledencode.c.
int32ScaledTo1UnsignedBytes()
void int32ScaledTo1UnsignedBytes (int32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Encode a int32_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1194 of file scaledencode.c.
int32ScaledTo2SignedBeBytes()
void int32ScaledTo2SignedBeBytes (int32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1145 of file scaledencode.c.
int32ScaledTo2SignedLeBytes()
void int32ScaledTo2SignedLeBytes (int32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1169 of file scaledencode.c.
int32ScaledTo2UnsignedBeBytes()
void int32ScaledTo2UnsignedBeBytes (int32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1092 of file scaledencode.c.
int32ScaledTo2UnsignedLeBytes()
void int32ScaledTo2UnsignedLeBytes (int32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1119 of file scaledencode.c.
int32ScaledTo3SignedBeBytes()
void int32ScaledTo3SignedBeBytes (int32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 3 signed bytes in big endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 3 signed bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1043 of file scaledencode.c.
int32ScaledTo3SignedLeBytes()
void int32ScaledTo3SignedLeBytes (int32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 3 signed bytes in little endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 3 signed bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1067 of file scaledencode.c.
int32ScaledTo3UnsignedBeBytes()
void int32ScaledTo3UnsignedBeBytes (int32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in big endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 990 of file scaledencode.c.
int32ScaledTo3UnsignedLeBytes()
void int32ScaledTo3UnsignedLeBytes (int32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in little endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1017 of file scaledencode.c.
int32ScaledTo4SignedBeBytes()
void int32ScaledTo4SignedBeBytes (int32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 4 signed bytes in big endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 4 signed bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 953 of file scaledencode.c.
int32ScaledTo4SignedLeBytes()
void int32ScaledTo4SignedLeBytes (int32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 4 signed bytes in little endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 4 signed bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 971 of file scaledencode.c.
int32ScaledTo4UnsignedBeBytes()
void int32ScaledTo4UnsignedBeBytes (int32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in big endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 904 of file scaledencode.c.
int32ScaledTo4UnsignedLeBytes()
void int32ScaledTo4UnsignedLeBytes (int32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a int32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in little endian order.
Encode a int32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 929 of file scaledencode.c.
int32ScaledToBitfield()
unsigned int int32ScaledToBitfield (int32_t value, int32_t min, uint32_t scaler, int bits)
Scale a int32_t using integer scaling to the base integer type used for bitfields.
Scale a int32_t using integer scaling to the base integer type used for bitfields.
Parameters
value is the number to scale.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer.
bits is the number of bits in the bitfield, used to limit the returned value.
Returns
(value-min)*scaler.
Definition at line 874 of file scaledencode.c.
int8ScaledTo1SignedBytes()
void int8ScaledTo1SignedBytes (int8_t value, uint8_t * bytes, int * index, uint8_t scaler)
Encode a int8_t on a byte stream by integer scaling to fit in 1 signed byte.
Encode a int8_t on a byte stream by integer scaling to fit in 1 signed byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1701 of file scaledencode.c.
int8ScaledTo1UnsignedBytes()
void int8ScaledTo1UnsignedBytes (int8_t value, uint8_t * bytes, int * index, int8_t min, uint8_t scaler)
Encode a int8_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Encode a int8_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1678 of file scaledencode.c.
int8ScaledToBitfield()
unsigned int int8ScaledToBitfield (int8_t value, int8_t min, uint8_t scaler, int bits)
Scale a int8_t using integer scaling to the base integer type used for bitfields.
Scale a int8_t using integer scaling to the base integer type used for bitfields.
Parameters
value is the number to scale.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer.
bits is the number of bits in the bitfield, used to limit the returned value.
Returns
(value-min)*scaler.
Definition at line 1648 of file scaledencode.c.
uint16ScaledTo1SignedBytes()
void uint16ScaledTo1SignedBytes (uint16_t value, uint8_t * bytes, int * index, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 1 signed byte.
Encode a uint16_t on a byte stream by integer scaling to fit in 1 signed byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1386 of file scaledencode.c.
uint16ScaledTo1UnsignedBytes()
void uint16ScaledTo1UnsignedBytes (uint16_t value, uint8_t * bytes, int * index, int16_t min, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Encode a uint16_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1360 of file scaledencode.c.
uint16ScaledTo2SignedBeBytes()
void uint16ScaledTo2SignedBeBytes (uint16_t value, uint8_t * bytes, int * index, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
Encode a uint16_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1323 of file scaledencode.c.
uint16ScaledTo2SignedLeBytes()
void uint16ScaledTo2SignedLeBytes (uint16_t value, uint8_t * bytes, int * index, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
Encode a uint16_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1341 of file scaledencode.c.
uint16ScaledTo2UnsignedBeBytes()
void uint16ScaledTo2UnsignedBeBytes (uint16_t value, uint8_t * bytes, int * index, int16_t min, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
Encode a uint16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1274 of file scaledencode.c.
uint16ScaledTo2UnsignedLeBytes()
void uint16ScaledTo2UnsignedLeBytes (uint16_t value, uint8_t * bytes, int * index, int16_t min, uint16_t scaler)
Encode a uint16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
Encode a uint16_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1299 of file scaledencode.c.
uint16ScaledToBitfield()
unsigned int uint16ScaledToBitfield (uint16_t value, int16_t min, uint16_t scaler, int bits)
Scale a uint16_t using integer scaling to the base integer type used for bitfields.
Scale a uint16_t using integer scaling to the base integer type used for bitfields.
Parameters
value is the number to scale.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer.
bits is the number of bits in the bitfield, used to limit the returned value.
Returns
(value-min)*scaler.
Definition at line 1244 of file scaledencode.c.
uint32ScaledTo1SignedBytes()
void uint32ScaledTo1SignedBytes (uint32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 1 signed byte.
Encode a uint32_t on a byte stream by integer scaling to fit in 1 signed byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 850 of file scaledencode.c.
uint32ScaledTo1UnsignedBytes()
void uint32ScaledTo1UnsignedBytes (uint32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Encode a uint32_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 824 of file scaledencode.c.
uint32ScaledTo2SignedBeBytes()
void uint32ScaledTo2SignedBeBytes (uint32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 2 signed bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 775 of file scaledencode.c.
uint32ScaledTo2SignedLeBytes()
void uint32ScaledTo2SignedLeBytes (uint32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 2 signed bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 799 of file scaledencode.c.
uint32ScaledTo2UnsignedBeBytes()
void uint32ScaledTo2UnsignedBeBytes (uint32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 722 of file scaledencode.c.
uint32ScaledTo2UnsignedLeBytes()
void uint32ScaledTo2UnsignedLeBytes (uint32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 2 unsigned bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 2 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 749 of file scaledencode.c.
uint32ScaledTo3SignedBeBytes()
void uint32ScaledTo3SignedBeBytes (uint32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 3 signed bytes in big endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 3 signed bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 673 of file scaledencode.c.
uint32ScaledTo3SignedLeBytes()
void uint32ScaledTo3SignedLeBytes (uint32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 3 signed bytes in little endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 3 signed bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 697 of file scaledencode.c.
uint32ScaledTo3UnsignedBeBytes()
void uint32ScaledTo3UnsignedBeBytes (uint32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in big endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 620 of file scaledencode.c.
uint32ScaledTo3UnsignedLeBytes()
void uint32ScaledTo3UnsignedLeBytes (uint32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in little endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 3 unsigned bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 3 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 647 of file scaledencode.c.
uint32ScaledTo4SignedBeBytes()
void uint32ScaledTo4SignedBeBytes (uint32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 4 signed bytes in big endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 4 signed bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 583 of file scaledencode.c.
uint32ScaledTo4SignedLeBytes()
void uint32ScaledTo4SignedLeBytes (uint32_t value, uint8_t * bytes, int * index, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 4 signed bytes in little endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 4 signed bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 601 of file scaledencode.c.
uint32ScaledTo4UnsignedBeBytes()
void uint32ScaledTo4UnsignedBeBytes (uint32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in big endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in big endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 534 of file scaledencode.c.
uint32ScaledTo4UnsignedLeBytes()
void uint32ScaledTo4UnsignedLeBytes (uint32_t value, uint8_t * bytes, int * index, int32_t min, uint32_t scaler)
Encode a uint32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in little endian order.
Encode a uint32_t on a byte stream by integer scaling to fit in 4 unsigned bytes in little endian order.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 4 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 559 of file scaledencode.c.
uint32ScaledToBitfield()
unsigned int uint32ScaledToBitfield (uint32_t value, int32_t min, uint32_t scaler, int bits)
Scale a uint32_t using integer scaling to the base integer type used for bitfields.
Scale a uint32_t using integer scaling to the base integer type used for bitfields.
Parameters
value is the number to scale.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer.
bits is the number of bits in the bitfield, used to limit the returned value.
Returns
(value-min)*scaler.
Definition at line 504 of file scaledencode.c.
uint8ScaledTo1SignedBytes()
void uint8ScaledTo1SignedBytes (uint8_t value, uint8_t * bytes, int * index, uint8_t scaler)
Encode a uint8_t on a byte stream by integer scaling to fit in 1 signed byte.
Encode a uint8_t on a byte stream by integer scaling to fit in 1 signed byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
scaler is multiplied by value to create the encoded integer: encoded = value*scaler.
Definition at line 1630 of file scaledencode.c.
uint8ScaledTo1UnsignedBytes()
void uint8ScaledTo1UnsignedBytes (uint8_t value, uint8_t * bytes, int * index, int8_t min, uint8_t scaler)
Encode a uint8_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Encode a uint8_t on a byte stream by integer scaling to fit in 1 unsigned byte.
Parameters
value is the number to encode.
bytes is a pointer to the byte stream which receives the encoded data.
index gives the location of the first byte in the byte stream, and will be incremented by 1 when this function is complete.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer: encoded = (value-min)*scaler.
Definition at line 1606 of file scaledencode.c.
uint8ScaledToBitfield()
unsigned int uint8ScaledToBitfield (uint8_t value, int8_t min, uint8_t scaler, int bits)
Scale a uint8_t using integer scaling to the base integer type used for bitfields.
Scale a uint8_t using integer scaling to the base integer type used for bitfields.
Parameters
value is the number to scale.
min is the minimum value that can be encoded.
scaler is multiplied by value to create the encoded integer.
bits is the number of bits in the bitfield, used to limit the returned value.
Returns
(value-min)*scaler.
Definition at line 1576 of file scaledencode.c.