APM:Libraries: libraries/AP_HAL_ChibiOS/sdcard.cpp File Reference
sdcard.cpp File Reference
#include <hal.h>
#include "SPIDevice.h"
#include "sdcard.h"
#include "bouncebuffer.h"
#include "hwdef/common/spi_hook.h"
#include <AP_BoardConfig/AP_BoardConfig.h>
#include <AP_Filesystem/AP_Filesystem.h>
#include "stm32_util.h"
Functions
bool sdcard_init ()
void sdcard_stop (void)
bool sdcard_retry (void)
Variables
const AP_HAL::HAL & hal
Function Documentation
sdcard_init()
bool sdcard_init ()
Definition at line 55 of file sdcard.cpp.
Referenced by sdcard_retry().
sdcard_retry()
bool sdcard_retry (void)
Definition at line 186 of file sdcard.cpp.
Referenced by ESP32::Scheduler::_io_thread(), and AP_Vehicle::setup().
sdcard_stop()
void sdcard_stop (void)
Definition at line 160 of file sdcard.cpp.
Referenced by sdcard_init(), and AP_Vehicle::setup().
Variable Documentation
hal
const AP_HAL::HAL& hal extern
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.