APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/ServoProtocol.h File Reference
ServoProtocol.h File Reference
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
Macros
#define getServoApi() 21
#define getServoVersion() "2.11"
#define translateServo(x) x
Enumerations
enum ServoModes { SERVO_MODE_NORMAL , SERVO_MODE_CALIBRATING , SERVO_MODE_TEST , SERVO_MODE_NUM_MODES }
enum ServoTimeoutModes { SERVO_TIMEOUT_ACTION_HOLD , SERVO_TIMEOUT_ACTION_DISABLE , SERVO_TIMEOUT_ACTION_NEUTRAL , SERVO_NUM_TIMEOUT_MODES }
enum ServoMultiCommandPackets {
PKT_SERVO_MULTI_COMMAND_1 = 0x00 , PKT_SERVO_MULTI_COMMAND_2 , PKT_SERVO_MULTI_COMMAND_3 , PKT_SERVO_MULTI_COMMAND_4 ,
PKT_SERVO_MULTI_COMMAND_5 , PKT_SERVO_MULTI_COMMAND_6 , PKT_SERVO_MULTI_COMMAND_7 , PKT_SERVO_MULTI_COMMAND_8 ,
PKT_SERVO_MULTI_COMMAND_9 , PKT_SERVO_MULTI_COMMAND_10 , PKT_SERVO_MULTI_COMMAND_11 , PKT_SERVO_MULTI_COMMAND_12 ,
PKT_SERVO_MULTI_COMMAND_13 , PKT_SERVO_MULTI_COMMAND_14 , PKT_SERVO_MULTI_COMMAND_15 , PKT_SERVO_MULTI_COMMAND_16
}
enum ServoPackets {
PKT_SERVO_POSITION_COMMAND = 0x10 , PKT_SERVO_NEUTRAL_COMMAND = 0x15 , PKT_SERVO_DISABLE = 0x20 , PKT_SERVO_ENABLE ,
PKT_SERVO_SYSTEM_COMMAND = 0x50 , PKT_SERVO_SET_TITLE , PKT_SERVO_STATUS_A = 0x60 , PKT_SERVO_STATUS_B ,
PKT_SERVO_STATUS_C , PKT_SERVO_STATUS_D , PKT_SERVO_ACCELEROMETER , PKT_SERVO_ADDRESS = 0x70 ,
PKT_SERVO_TITLE , PKT_SERVO_FIRMWARE , PKT_SERVO_SYSTEM_INFO , PKT_SERVO_TELEMETRY_CONFIG ,
PKT_SERVO_SETTINGS_INFO , PKT_SERVO_FACTORY , PKT_SERVO_TELLTALE_A = 0x7A , PKT_SERVO_LIMITS = 0x80 ,
PKT_SERVO_CURRENT_LIMITS , PKT_SERVO_POTENTIOMETER , PKT_SERVO_BACKLASH , PKT_SERVO_BIN_DATA ,
PKT_SERVO_WEAR_LEVEL_A , PKT_SERVO_WEAR_LEVEL_B , PKT_SERVO_LOOKUP_TABLE , PKT_SERVO_LOOKUP_ELEMENT ,
PKT_SERVO_CONFIG , PKT_SERVO_DELTA_CONFIG , PKT_SERVO_CALIBRATION , PKT_SERVO_MOTION_CONTROL = 0x8C ,
PKT_SERVO_LIMIT_VALUES , PKT_SERVO_DEBUG_DELTA = 0x90 , PKT_SERVO_DEBUG_CTRL_LOOP , PKT_SERVO_DEBUG_MOTOR ,
PKT_SERVO_DEBUG_MOTION_CTRL , PKT_SERVO_CTRL_LOOP_SETTINGS = 0xA0 , PKT_SERVO_TELLTALE_SETTINGS = 0x101 , PKT_SERVO_USER_SETTINGS = 0x105 ,
PKT_SERVO_SYSTEM_SETTINGS = 0x1FF
}
enum ServoCommands {
CMD_SERVO_CONFIGURE_LOOKUP_TABLE = 0x00 , CMD_SERVO_SET_LOOKUP_TABLE_ELEMENT , CMD_SERVO_GET_LOOKUP_TABLE_ELEMENT , CMD_SERVO_SET_CONFIG = 0x10 ,
CMD_SERVO_SET_CURRENT_LIMIT = 0x20 , CMD_SERVO_SET_TEMPERATURE_LIMIT , CMD_SERVO_SET_RATE_LIMIT , CMD_SERVO_SET_STRENGTH ,
CMD_SERVO_SET_ILIMIT_KP , CMD_SERVO_SET_ILIMIT_KI , CMD_SERVO_SET_MIN_PWM_LIMIT = 0x30 , CMD_SERVO_SET_MAX_PWM_LIMIT ,
CMD_SERVO_SET_NEUTRAL_POSITION , CMD_SERVO_SET_TELEMETRY_PERIOD = 0x40 , CMD_SERVO_SET_SILENCE_PERIOD , CMD_SERVO_SET_TELEMETRY_PACKETS ,
CMD_SERVO_REQUEST_HF_DATA = 0x43 , CMD_SERVO_SET_CMD_TIMEOUT , CMD_SERVO_SET_NODE_ID = 0x50 , CMD_SERVO_SET_USER_ID_A ,
CMD_SERVO_SET_USER_ID_B , CMD_SERVO_CALIBRATE_POT = 0x60 , CMD_SERVO_START_TEST_MODE , CMD_SERVO_STOP_TEST_MODE ,
CMD_SERVO_START_BACKLASH_TEST , CMD_SERVO_RESET_HALL_COUNTS , CMD_SERVO_SET_MIDDLE_POS = 0x70 , CMD_SERVO_RESET_TELLTALES = 0x80 ,
CMD_SERVO_CLEAR_BIN_DATA , CMD_SERVO_ERASE_EEPROM = 0x90 , CMD_SERVO_SET_COMMISSIONING_FLAG = 0x95 , CMD_SERVO_RESET_DEFAULT_SETTINGS = 0xA0 ,
CMD_SERVO_SET_PROFILE_TASK = 0xF0 , CMD_SERVO_UNLOCK_SETTINGS = 0xF5 , CMD_SERVO_LOCK_SETTINGS , CMD_SERVO_ENTER_BOOTLOADER = 0xFB ,
CMD_SERVO_RESET , CMD_SERVO_SET_SERIAL_NUMBER = 0xFF
}
Functions
const char * ServoModes_EnumLabel (int value)
Lookup label for 'ServoModes' enum entry.
const char * ServoMultiCommandPackets_EnumLabel (int value)
Lookup label for 'ServoMultiCommandPackets' enum entry.
const char * ServoPackets_EnumLabel (int value)
Lookup label for 'ServoPackets' enum entry.
const char * ServoCommands_EnumLabel (int value)
Lookup label for 'ServoCommands' enum entry.
uint8_t * getServoPacketData (void *pkt)
const uint8_t * getServoPacketDataConst (const void *pkt)
void finishServoPacket (void *pkt, int size, uint32_t packetID)
Complete a packet after the data have been encoded.
int getServoPacketSize (const void *pkt)
uint32_t getServoPacketID (const void *pkt)
Macro Definition Documentation
getServoApi
#define getServoApi () 21
Returns
the protocol API enumeration
Definition at line 48 of file ServoProtocol.h.
Referenced by encodeServo_TelemetryConfigPacket(), and encodeServo_TelemetryConfigPacketStructure().
getServoVersion
#define getServoVersion () "2.11"
Returns
the protocol version string
Definition at line 51 of file ServoProtocol.h.
translateServo
#define translateServo (x) x
Definition at line 55 of file ServoProtocol.h.
Referenced by ServoCommands_EnumLabel(), ServoModes_EnumLabel(), ServoMultiCommandPackets_EnumLabel(), and ServoPackets_EnumLabel().
Enumeration Type Documentation
ServoCommands
enum ServoCommands
These commands are sent to the servo using the SERVO_SYSTEM_COMMAND packet
Enumerator
CMD_SERVO_CONFIGURE_LOOKUP_TABLE
Configure I/O map parameters.
CMD_SERVO_SET_LOOKUP_TABLE_ELEMENT
Configure an individual I/O element.
CMD_SERVO_GET_LOOKUP_TABLE_ELEMENT
Request an individual I/O element.
CMD_SERVO_SET_CONFIG
Set the servo configuration bits.
CMD_SERVO_SET_CURRENT_LIMIT
Set the servo current limit.
CMD_SERVO_SET_TEMPERATURE_LIMIT
Set the over-temperature warning level.
CMD_SERVO_SET_RATE_LIMIT
Set the servo rate limit.
CMD_SERVO_SET_STRENGTH
Set the servo 'strength' (maximum motor duty cycle)
CMD_SERVO_SET_ILIMIT_KP
Set the servo current-limit proportional gain value.
CMD_SERVO_SET_ILIMIT_KI
Set the servo current-limit integral gain value.
CMD_SERVO_SET_MIN_PWM_LIMIT
Set the minimum clipping value for the servo PWM signal.
CMD_SERVO_SET_MAX_PWM_LIMIT
Set the maximum clipping value for the servo PWM signal.
CMD_SERVO_SET_NEUTRAL_POSITION
Set the neutral position for the servo.
CMD_SERVO_SET_TELEMETRY_PERIOD
Set the servo telemetry period.
CMD_SERVO_SET_SILENCE_PERIOD
Set the servo silence period.
CMD_SERVO_SET_TELEMETRY_PACKETS
Configure telemetry packets.
CMD_SERVO_REQUEST_HF_DATA
Request high-frequency telemetry data.
CMD_SERVO_SET_CMD_TIMEOUT
Set the command timeout for the servo.
CMD_SERVO_SET_NODE_ID
Configure the CAN servo node ID.
CMD_SERVO_SET_USER_ID_A
Set User ID A.
CMD_SERVO_SET_USER_ID_B
Set User ID B.
CMD_SERVO_CALIBRATE_POT
Initiate servo potentiometer calibration procedure.
CMD_SERVO_START_TEST_MODE
CMD_SERVO_STOP_TEST_MODE
CMD_SERVO_START_BACKLASH_TEST
CMD_SERVO_RESET_HALL_COUNTS
CMD_SERVO_SET_MIDDLE_POS
CMD_SERVO_RESET_TELLTALES
Reset servo telltale data.
CMD_SERVO_CLEAR_BIN_DATA
CMD_SERVO_ERASE_EEPROM
CMD_SERVO_SET_COMMISSIONING_FLAG
Set servo commissioning flag.
CMD_SERVO_RESET_DEFAULT_SETTINGS
Reset servo configuration settings to default values.
CMD_SERVO_SET_PROFILE_TASK
Set the task to profile.
CMD_SERVO_UNLOCK_SETTINGS
Unlock servo settings.
CMD_SERVO_LOCK_SETTINGS
Lock servo settings.
CMD_SERVO_ENTER_BOOTLOADER
Enter bootloader mode.
CMD_SERVO_RESET
Reset servo.
CMD_SERVO_SET_SERIAL_NUMBER
Set the serial number.
Definition at line 157 of file ServoProtocol.h.
ServoModes
enum ServoModes
Enumerator
SERVO_MODE_NORMAL
The servo is in normal operational mode.
SERVO_MODE_CALIBRATING
The servo is in calibration mode (factory setting only)
SERVO_MODE_TEST
The servo is in test mode (factory setting only)
SERVO_MODE_NUM_MODES
Definition at line 58 of file ServoProtocol.h.
ServoMultiCommandPackets
enum ServoMultiCommandPackets
Command multiple servo positions with a single command
Enumerator
PKT_SERVO_MULTI_COMMAND_1
Send a position command to servos 1,2,3,4.
PKT_SERVO_MULTI_COMMAND_2
Send a position command to servos 5,6,7,8.
PKT_SERVO_MULTI_COMMAND_3
Send a position command to servos 9,10,11,12.
PKT_SERVO_MULTI_COMMAND_4
Send a position command to servos 13,14,15,16.
PKT_SERVO_MULTI_COMMAND_5
Send a position command to servos 17,18,19,20.
PKT_SERVO_MULTI_COMMAND_6
Send a position command to servos 21,22,23,24.
PKT_SERVO_MULTI_COMMAND_7
Send a position command to servos 25,26,27,28.
PKT_SERVO_MULTI_COMMAND_8
Send a position command to servos 29,30,31,32.
PKT_SERVO_MULTI_COMMAND_9
Send a position command to servos 33,34,35,36.
PKT_SERVO_MULTI_COMMAND_10
Send a position command to servos 37,38,39,40.
PKT_SERVO_MULTI_COMMAND_11
Send a position command to servos 41,42,43,44.
PKT_SERVO_MULTI_COMMAND_12
Send a position command to servos 45,46,47,48.
PKT_SERVO_MULTI_COMMAND_13
Send a position command to servos 49,50,51,52.
PKT_SERVO_MULTI_COMMAND_14
Send a position command to servos 53,54,55,56.
PKT_SERVO_MULTI_COMMAND_15
Send a position command to servos 57,58,59,60.
PKT_SERVO_MULTI_COMMAND_16
Send a position command to servos 61,62,63,64.
Definition at line 80 of file ServoProtocol.h.
ServoPackets
enum ServoPackets
Servo CAN packet identifiers
Enumerator
PKT_SERVO_POSITION_COMMAND
Send a position command to an individual servo.
PKT_SERVO_NEUTRAL_COMMAND
Move the servo to the neutral position.
PKT_SERVO_DISABLE
Disable a single servo, or all servos with a broadcast message.
PKT_SERVO_ENABLE
Enable a single servo, or all servos with a broadcast message.
PKT_SERVO_SYSTEM_COMMAND
Servo system command.
PKT_SERVO_SET_TITLE
Set the title of this servo.
PKT_SERVO_STATUS_A
Servo STATUS_A packet contains status and position information.
PKT_SERVO_STATUS_B
Servo STATUS_B packet contains current, temperature and other information.
PKT_SERVO_STATUS_C
Reserved for future use.
PKT_SERVO_STATUS_D
Reserved for future use.
PKT_SERVO_ACCELEROMETER
Raw accelerometer data.
PKT_SERVO_ADDRESS
Servo address information.
PKT_SERVO_TITLE
Servo title information.
PKT_SERVO_FIRMWARE
Servo firmware information.
PKT_SERVO_SYSTEM_INFO
Servo system info (uptime, etc)
PKT_SERVO_TELEMETRY_CONFIG
Telemetry settings.
PKT_SERVO_SETTINGS_INFO
Non-volatile settings configuration information.
PKT_SERVO_FACTORY
Factory data.
PKT_SERVO_TELLTALE_A
Servo telltale information.
PKT_SERVO_LIMITS
Servo limits (current, strength, temperature)
PKT_SERVO_CURRENT_LIMITS
Current limit control system settings.
PKT_SERVO_POTENTIOMETER
Potentiometer configuration.
PKT_SERVO_BACKLASH
PKT_SERVO_BIN_DATA
Servo telltale binning data.
PKT_SERVO_WEAR_LEVEL_A
Wear estimate information packet 1 of 2.
PKT_SERVO_WEAR_LEVEL_B
Wear estimate information packet 2 of 2.
PKT_SERVO_LOOKUP_TABLE
Input/output mapping table information.
PKT_SERVO_LOOKUP_ELEMENT
Input/output mapping table element information.
PKT_SERVO_CONFIG
General servo configuration.
PKT_SERVO_DELTA_CONFIG
Position error configuration.
PKT_SERVO_CALIBRATION
Servo calibration data.
PKT_SERVO_MOTION_CONTROL
Servo motion control settings.
PKT_SERVO_LIMIT_VALUES
Servo limit value settings.
PKT_SERVO_DEBUG_DELTA
Position debug information.
PKT_SERVO_DEBUG_CTRL_LOOP
Control loop debug information.
PKT_SERVO_DEBUG_MOTOR
Motor information.
PKT_SERVO_DEBUG_MOTION_CTRL
Motion control debug info.
PKT_SERVO_CTRL_LOOP_SETTINGS
Position control loop settings.
PKT_SERVO_TELLTALE_SETTINGS
Telltale settings packet.
PKT_SERVO_USER_SETTINGS
User settings (title, ID etc)
PKT_SERVO_SYSTEM_SETTINGS
System settings (serial number, etc)
Definition at line 106 of file ServoProtocol.h.
ServoTimeoutModes
enum ServoTimeoutModes
Enumerator
SERVO_TIMEOUT_ACTION_HOLD
The servo will hold the current position.
SERVO_TIMEOUT_ACTION_DISABLE
The servo will be disabled.
SERVO_TIMEOUT_ACTION_NEUTRAL
The servo will move to its programmed neutral position.
SERVO_NUM_TIMEOUT_MODES
Definition at line 69 of file ServoProtocol.h.
Function Documentation
finishServoPacket()
void finishServoPacket (void * pkt, int size, uint32_t packetID)
Complete a packet after the data have been encoded.
Referenced by encodeServo_AccelerometerPacket(), encodeServo_AddressPacket(), encodeServo_AddressPacketStructure(), encodeServo_ConfigPacket(), encodeServo_ConfigPacketStructure(), encodeServo_DisablePacket(), encodeServo_EnablePacket(), encodeServo_EnterBootloaderPacket(), encodeServo_FirmwarePacket(), encodeServo_FirmwarePacketStructure(), encodeServo_LockSettingsPacket(), encodeServo_MultiPositionCommandPacket(), encodeServo_NeutralPositionCommandPacket(), encodeServo_PositionCommandPacket(), encodeServo_RequestHighFrequencyDataPacket(), encodeServo_ResetDefaultSettingsPacket(), encodeServo_SetNodeIDPacket(), encodeServo_SettingsInfoPacket(), encodeServo_SettingsInfoPacketStructure(), encodeServo_SetTitlePacket(), encodeServo_SetUserIdAPacket(), encodeServo_SetUserIdBPacket(), encodeServo_StatusAPacket(), encodeServo_StatusAPacketStructure(), encodeServo_StatusBPacket(), encodeServo_StatusBPacketStructure(), encodeServo_StatusCPacket(), encodeServo_StatusCPacketStructure(), encodeServo_SystemInfoPacket(), encodeServo_SystemInfoPacketStructure(), encodeServo_TelemetryConfigPacket(), encodeServo_TelemetryConfigPacketStructure(), encodeServo_TelltaleAPacket(), encodeServo_TitlePacket(), and encodeServo_UnlockSettingsPacket().
getServoPacketData()
uint8_t * getServoPacketData (void * pkt)
Returns
the packet data pointer from the packet
Referenced by encodeServo_AccelerometerPacket(), encodeServo_AddressPacket(), encodeServo_AddressPacketStructure(), encodeServo_ConfigPacket(), encodeServo_ConfigPacketStructure(), encodeServo_EnterBootloaderPacket(), encodeServo_FirmwarePacket(), encodeServo_FirmwarePacketStructure(), encodeServo_LockSettingsPacket(), encodeServo_MultiPositionCommandPacket(), encodeServo_PositionCommandPacket(), encodeServo_RequestHighFrequencyDataPacket(), encodeServo_ResetDefaultSettingsPacket(), encodeServo_SetNodeIDPacket(), encodeServo_SettingsInfoPacket(), encodeServo_SettingsInfoPacketStructure(), encodeServo_SetTitlePacket(), encodeServo_SetUserIdAPacket(), encodeServo_SetUserIdBPacket(), encodeServo_StatusAPacket(), encodeServo_StatusAPacketStructure(), encodeServo_StatusBPacket(), encodeServo_StatusBPacketStructure(), encodeServo_StatusCPacket(), encodeServo_StatusCPacketStructure(), encodeServo_SystemInfoPacket(), encodeServo_SystemInfoPacketStructure(), encodeServo_TelemetryConfigPacket(), encodeServo_TelemetryConfigPacketStructure(), encodeServo_TelltaleAPacket(), encodeServo_TitlePacket(), and encodeServo_UnlockSettingsPacket().
getServoPacketDataConst()
const uint8_t * getServoPacketDataConst (const void * pkt)
Returns
the packet data pointer from the packet, const
Referenced by decodeServo_AccelerometerPacket(), decodeServo_AddressPacket(), decodeServo_AddressPacketStructure(), decodeServo_ConfigPacket(), decodeServo_ConfigPacketStructure(), decodeServo_EnterBootloaderPacket(), decodeServo_FirmwarePacket(), decodeServo_FirmwarePacketStructure(), decodeServo_LockSettingsPacket(), decodeServo_MultiPositionCommandPacket(), decodeServo_PositionCommandPacket(), decodeServo_RequestHighFrequencyDataPacket(), decodeServo_ResetDefaultSettingsPacket(), decodeServo_SetNodeIDPacket(), decodeServo_SettingsInfoPacket(), decodeServo_SettingsInfoPacketStructure(), decodeServo_SetTitlePacket(), decodeServo_SetUserIdAPacket(), decodeServo_SetUserIdBPacket(), decodeServo_StatusAPacket(), decodeServo_StatusAPacketStructure(), decodeServo_StatusBPacket(), decodeServo_StatusBPacketStructure(), decodeServo_StatusCPacket(), decodeServo_StatusCPacketStructure(), decodeServo_SystemInfoPacket(), decodeServo_SystemInfoPacketStructure(), decodeServo_TelemetryConfigPacket(), decodeServo_TelemetryConfigPacketStructure(), decodeServo_TelltaleAPacket(), decodeServo_TitlePacket(), and decodeServo_UnlockSettingsPacket().
getServoPacketID()
uint32_t getServoPacketID (const void * pkt)
Returns
the ID of a packet from the packet header
Referenced by decodeServo_AccelerometerPacket(), decodeServo_AddressPacket(), decodeServo_AddressPacketStructure(), decodeServo_ConfigPacket(), decodeServo_ConfigPacketStructure(), decodeServo_DisablePacket(), decodeServo_EnablePacket(), decodeServo_EnterBootloaderPacket(), decodeServo_FirmwarePacket(), decodeServo_FirmwarePacketStructure(), decodeServo_LockSettingsPacket(), decodeServo_MultiPositionCommandPacket(), decodeServo_NeutralPositionCommandPacket(), decodeServo_PositionCommandPacket(), decodeServo_RequestHighFrequencyDataPacket(), decodeServo_ResetDefaultSettingsPacket(), decodeServo_SetNodeIDPacket(), decodeServo_SettingsInfoPacket(), decodeServo_SettingsInfoPacketStructure(), decodeServo_SetTitlePacket(), decodeServo_SetUserIdAPacket(), decodeServo_SetUserIdBPacket(), decodeServo_StatusAPacket(), decodeServo_StatusAPacketStructure(), decodeServo_StatusBPacket(), decodeServo_StatusBPacketStructure(), decodeServo_StatusCPacket(), decodeServo_StatusCPacketStructure(), decodeServo_SystemInfoPacket(), decodeServo_SystemInfoPacketStructure(), decodeServo_TelemetryConfigPacket(), decodeServo_TelemetryConfigPacketStructure(), decodeServo_TelltaleAPacket(), decodeServo_TitlePacket(), and decodeServo_UnlockSettingsPacket().
getServoPacketSize()
int getServoPacketSize (const void * pkt)
Returns
the size of a packet from the packet header
Referenced by decodeServo_AccelerometerPacket(), decodeServo_AddressPacket(), decodeServo_AddressPacketStructure(), decodeServo_ConfigPacket(), decodeServo_ConfigPacketStructure(), decodeServo_EnterBootloaderPacket(), decodeServo_FirmwarePacket(), decodeServo_FirmwarePacketStructure(), decodeServo_LockSettingsPacket(), decodeServo_MultiPositionCommandPacket(), decodeServo_PositionCommandPacket(), decodeServo_RequestHighFrequencyDataPacket(), decodeServo_ResetDefaultSettingsPacket(), decodeServo_SetNodeIDPacket(), decodeServo_SettingsInfoPacket(), decodeServo_SettingsInfoPacketStructure(), decodeServo_SetTitlePacket(), decodeServo_SetUserIdAPacket(), decodeServo_SetUserIdBPacket(), decodeServo_StatusAPacket(), decodeServo_StatusAPacketStructure(), decodeServo_StatusBPacket(), decodeServo_StatusBPacketStructure(), decodeServo_StatusCPacket(), decodeServo_StatusCPacketStructure(), decodeServo_SystemInfoPacket(), decodeServo_SystemInfoPacketStructure(), decodeServo_TelemetryConfigPacket(), decodeServo_TelemetryConfigPacketStructure(), decodeServo_TelltaleAPacket(), decodeServo_TitlePacket(), and decodeServo_UnlockSettingsPacket().
ServoCommands_EnumLabel()
const char * ServoCommands_EnumLabel (int value)
Lookup label for 'ServoCommands' enum entry.
Returns
the label of a 'ServoCommands' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 198 of file ServoProtocol.c.
ServoModes_EnumLabel()
const char * ServoModes_EnumLabel (int value)
Lookup label for 'ServoModes' enum entry.
Returns
the label of a 'ServoModes' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 28 of file ServoProtocol.c.
ServoMultiCommandPackets_EnumLabel()
const char * ServoMultiCommandPackets_EnumLabel (int value)
Lookup label for 'ServoMultiCommandPackets' enum entry.
Returns
the label of a 'ServoMultiCommandPackets' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 52 of file ServoProtocol.c.
ServoPackets_EnumLabel()
const char * ServoPackets_EnumLabel (int value)
Lookup label for 'ServoPackets' enum entry.
Returns
the label of a 'ServoPackets' enum entry, based on its value
Parameters
value is the integer value of the enum entry
Returns
string label of the given entry
Definition at line 100 of file ServoProtocol.c.