APM:Libraries: libraries/AP_PiccoloCAN/piccolo_protocol/ServoDefines.h File Reference
ServoDefines.h File Reference
#include <stdbool.h>
#include "ServoProtocol.h"
Classes
struct Servo_StatusBits_t
struct Servo_WarningBits_t
struct Servo_ErrorBits_t
struct Servo_TelemetryPackets_t
struct Servo_TelemetrySettings_t
struct Servo_ConfigBits_t
Macros
#define getMinLengthOfServo_StatusBits_t() (1)
return the minimum encoded length for the Servo_StatusBits_t structure
#define getMaxLengthOfServo_StatusBits_t() (1)
return the maximum encoded length for the Servo_StatusBits_t structure
#define getMinLengthOfServo_WarningBits_t() (2)
return the minimum encoded length for the Servo_WarningBits_t structure
#define getMaxLengthOfServo_WarningBits_t() (2)
return the maximum encoded length for the Servo_WarningBits_t structure
#define getMinLengthOfServo_ErrorBits_t() (1)
return the minimum encoded length for the Servo_ErrorBits_t structure
#define getMaxLengthOfServo_ErrorBits_t() (1)
return the maximum encoded length for the Servo_ErrorBits_t structure
#define getMinLengthOfServo_TelemetryPackets_t() (1)
return the minimum encoded length for the Servo_TelemetryPackets_t structure
#define getMaxLengthOfServo_TelemetryPackets_t() (1)
return the maximum encoded length for the Servo_TelemetryPackets_t structure
#define getMinLengthOfServo_TelemetrySettings_t() (4)
return the minimum encoded length for the Servo_TelemetrySettings_t structure
#define getMaxLengthOfServo_TelemetrySettings_t() (4)
return the maximum encoded length for the Servo_TelemetrySettings_t structure
#define getMinLengthOfServo_ConfigBits_t() (2)
return the minimum encoded length for the Servo_ConfigBits_t structure
#define getMaxLengthOfServo_ConfigBits_t() (2)
return the maximum encoded length for the Servo_ConfigBits_t structure
Functions
void encodeServo_StatusBits_t (uint8_t *data, int *bytecount, const Servo_StatusBits_t *user)
Encode a Servo_StatusBits_t into a byte array.
int decodeServo_StatusBits_t (const uint8_t *data, int *bytecount, Servo_StatusBits_t *user)
Decode a Servo_StatusBits_t from a byte array.
void encodeServo_WarningBits_t (uint8_t *data, int *bytecount, const Servo_WarningBits_t *user)
Encode a Servo_WarningBits_t into a byte array.
int decodeServo_WarningBits_t (const uint8_t *data, int *bytecount, Servo_WarningBits_t *user)
Decode a Servo_WarningBits_t from a byte array.
void encodeServo_ErrorBits_t (uint8_t *data, int *bytecount, const Servo_ErrorBits_t *user)
Encode a Servo_ErrorBits_t into a byte array.
int decodeServo_ErrorBits_t (const uint8_t *data, int *bytecount, Servo_ErrorBits_t *user)
Decode a Servo_ErrorBits_t from a byte array.
void encodeServo_TelemetryPackets_t (uint8_t *data, int *bytecount, const Servo_TelemetryPackets_t *user)
Encode a Servo_TelemetryPackets_t into a byte array.
int decodeServo_TelemetryPackets_t (const uint8_t *data, int *bytecount, Servo_TelemetryPackets_t *user)
Decode a Servo_TelemetryPackets_t from a byte array.
void encodeServo_TelemetrySettings_t (uint8_t *data, int *bytecount, const Servo_TelemetrySettings_t *user)
Encode a Servo_TelemetrySettings_t into a byte array.
int decodeServo_TelemetrySettings_t (const uint8_t *data, int *bytecount, Servo_TelemetrySettings_t *user)
Decode a Servo_TelemetrySettings_t from a byte array.
void encodeServo_ConfigBits_t (uint8_t *data, int *bytecount, const Servo_ConfigBits_t *user)
Encode a Servo_ConfigBits_t into a byte array.
int decodeServo_ConfigBits_t (const uint8_t *data, int *bytecount, Servo_ConfigBits_t *user)
Decode a Servo_ConfigBits_t from a byte array.
Macro Definition Documentation
getMaxLengthOfServo_ConfigBits_t
#define getMaxLengthOfServo_ConfigBits_t () (2)
return the maximum encoded length for the Servo_ConfigBits_t structure
Definition at line 180 of file ServoDefines.h.
getMaxLengthOfServo_ErrorBits_t
#define getMaxLengthOfServo_ErrorBits_t () (1)
return the maximum encoded length for the Servo_ErrorBits_t structure
Definition at line 107 of file ServoDefines.h.
getMaxLengthOfServo_StatusBits_t
#define getMaxLengthOfServo_StatusBits_t () (1)
return the maximum encoded length for the Servo_StatusBits_t structure
Definition at line 52 of file ServoDefines.h.
getMaxLengthOfServo_TelemetryPackets_t
#define getMaxLengthOfServo_TelemetryPackets_t () (1)
return the maximum encoded length for the Servo_TelemetryPackets_t structure
Definition at line 134 of file ServoDefines.h.
getMaxLengthOfServo_TelemetrySettings_t
#define getMaxLengthOfServo_TelemetrySettings_t () (4)
return the maximum encoded length for the Servo_TelemetrySettings_t structure
Definition at line 157 of file ServoDefines.h.
getMaxLengthOfServo_WarningBits_t
#define getMaxLengthOfServo_WarningBits_t () (2)
return the maximum encoded length for the Servo_WarningBits_t structure
Definition at line 80 of file ServoDefines.h.
getMinLengthOfServo_ConfigBits_t
#define getMinLengthOfServo_ConfigBits_t () (2)
return the minimum encoded length for the Servo_ConfigBits_t structure
Definition at line 177 of file ServoDefines.h.
getMinLengthOfServo_ErrorBits_t
#define getMinLengthOfServo_ErrorBits_t () (1)
return the minimum encoded length for the Servo_ErrorBits_t structure
Definition at line 104 of file ServoDefines.h.
getMinLengthOfServo_StatusBits_t
#define getMinLengthOfServo_StatusBits_t () (1)
return the minimum encoded length for the Servo_StatusBits_t structure
Definition at line 49 of file ServoDefines.h.
getMinLengthOfServo_TelemetryPackets_t
#define getMinLengthOfServo_TelemetryPackets_t () (1)
return the minimum encoded length for the Servo_TelemetryPackets_t structure
Definition at line 131 of file ServoDefines.h.
getMinLengthOfServo_TelemetrySettings_t
#define getMinLengthOfServo_TelemetrySettings_t () (4)
return the minimum encoded length for the Servo_TelemetrySettings_t structure
Definition at line 154 of file ServoDefines.h.
getMinLengthOfServo_WarningBits_t
#define getMinLengthOfServo_WarningBits_t () (2)
return the minimum encoded length for the Servo_WarningBits_t structure
Definition at line 77 of file ServoDefines.h.
Function Documentation
decodeServo_ConfigBits_t()
int decodeServo_ConfigBits_t (const uint8_t * _pg_data, int * _pg_bytecount, Servo_ConfigBits_t * _pg_user)
Decode a Servo_ConfigBits_t from a byte array.
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 478 of file ServoDefines.c.
Referenced by decodeServo_Config_t(), decodeServo_ConfigPacket(), and decodeServo_ConfigPacketStructure().
decodeServo_ErrorBits_t()
int decodeServo_ErrorBits_t (const uint8_t * _pg_data, int * _pg_bytecount, Servo_ErrorBits_t * _pg_user)
Decode a Servo_ErrorBits_t from a byte array.
Servo error bits
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 242 of file ServoDefines.c.
Referenced by decodeServo_StatusAPacket(), and decodeServo_StatusAPacketStructure().
decodeServo_StatusBits_t()
int decodeServo_StatusBits_t (const uint8_t * _pg_data, int * _pg_bytecount, Servo_StatusBits_t * _pg_user)
Decode a Servo_StatusBits_t from a byte array.
Servo status bits
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 70 of file ServoDefines.c.
Referenced by decodeServo_StatusAPacket(), and decodeServo_StatusAPacketStructure().
decodeServo_TelemetryPackets_t()
int decodeServo_TelemetryPackets_t (const uint8_t * _pg_data, int * _pg_bytecount, Servo_TelemetryPackets_t * _pg_user)
Decode a Servo_TelemetryPackets_t from a byte array.
Servo packet selection
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 327 of file ServoDefines.c.
Referenced by decodeServo_RequestHighFrequencyDataPacket(), and decodeServo_TelemetrySettings_t().
decodeServo_TelemetrySettings_t()
int decodeServo_TelemetrySettings_t (const uint8_t * _pg_data, int * _pg_bytecount, Servo_TelemetrySettings_t * _pg_user)
Decode a Servo_TelemetrySettings_t from a byte array.
Servo telemetry configuration
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 401 of file ServoDefines.c.
Referenced by decodeServo_TelemetryConfigPacket(), and decodeServo_TelemetryConfigPacketStructure().
decodeServo_WarningBits_t()
int decodeServo_WarningBits_t (const uint8_t * _pg_data, int * _pg_bytecount, Servo_WarningBits_t * _pg_user)
Decode a Servo_WarningBits_t from a byte array.
Servo warning bits
Parameters
_pg_data points to the byte array to decoded data from
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
_pg_user is the data to decode from the byte array
Returns
1 if the data are decoded, else 0.
Definition at line 153 of file ServoDefines.c.
Referenced by decodeServo_StatusAPacket(), and decodeServo_StatusAPacketStructure().
encodeServo_ConfigBits_t()
void encodeServo_ConfigBits_t (uint8_t * _pg_data, int * _pg_bytecount, const Servo_ConfigBits_t * _pg_user)
Encode a Servo_ConfigBits_t into a byte array.
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 435 of file ServoDefines.c.
Referenced by encodeServo_Config_t(), encodeServo_ConfigPacket(), and encodeServo_ConfigPacketStructure().
encodeServo_ErrorBits_t()
void encodeServo_ErrorBits_t (uint8_t * _pg_data, int * _pg_bytecount, const Servo_ErrorBits_t * _pg_user)
Encode a Servo_ErrorBits_t into a byte array.
Servo error bits
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 200 of file ServoDefines.c.
Referenced by encodeServo_StatusAPacket(), and encodeServo_StatusAPacketStructure().
encodeServo_StatusBits_t()
void encodeServo_StatusBits_t (uint8_t * _pg_data, int * _pg_bytecount, const Servo_StatusBits_t * _pg_user)
Encode a Servo_StatusBits_t into a byte array.
Servo status bits
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 34 of file ServoDefines.c.
Referenced by encodeServo_StatusAPacket(), and encodeServo_StatusAPacketStructure().
encodeServo_TelemetryPackets_t()
void encodeServo_TelemetryPackets_t (uint8_t * _pg_data, int * _pg_bytecount, const Servo_TelemetryPackets_t * _pg_user)
Encode a Servo_TelemetryPackets_t into a byte array.
Servo packet selection
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 285 of file ServoDefines.c.
Referenced by encodeServo_RequestHighFrequencyDataPacket(), and encodeServo_TelemetrySettings_t().
encodeServo_TelemetrySettings_t()
void encodeServo_TelemetrySettings_t (uint8_t * _pg_data, int * _pg_bytecount, const Servo_TelemetrySettings_t * _pg_user)
Encode a Servo_TelemetrySettings_t into a byte array.
Servo telemetry configuration
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 370 of file ServoDefines.c.
Referenced by encodeServo_TelemetryConfigPacket(), and encodeServo_TelemetryConfigPacketStructure().
encodeServo_WarningBits_t()
void encodeServo_WarningBits_t (uint8_t * _pg_data, int * _pg_bytecount, const Servo_WarningBits_t * _pg_user)
Encode a Servo_WarningBits_t into a byte array.
Servo warning bits
Parameters
_pg_data points to the byte array to add encoded data to
_pg_bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
_pg_user is the data to encode in the byte array
Definition at line 107 of file ServoDefines.c.
Referenced by encodeServo_StatusAPacket(), and encodeServo_StatusAPacketStructure().