APM:Libraries: libraries/AP_ADSB/sagetech-sdk/sgUtil.h File Reference
sgUtil.h File Reference
#include <stdint.h>
Macros
#define swap16(data) ((((data) >> 8) & 0x00FF) | (((data) << 8) & 0xFF00))
#define swap24(data) (((data) >> 16) | ((data)&0x00FF00) | (((data) << 16) & 0xFF0000))
#define swap32(data) (((data) >> 24) | (((data)&0x00FF0000) >> 8) | (((data)&0x0000FF00) << 8) | ((data) << 24))
#define swap64(data) (swap32((data & 0x00000000ffffffffULL))) << 32 | swap32(data >> 32))
#define PI 3.14159265359
#define toRad(deg) ((deg)*PI / 180.0)
#define toDeg(rad) ((rad)*180 / PI)
#define toMeter(feet) ((feet)*0.3048)
#define toFeet(meter) ((meter)*3.2808)
Functions
int16_t toInt16 (const uint8_t bytes[])
int32_t toInt32 (const uint8_t bytes[])
uint16_t toUint16 (const uint8_t bytes[])
uint32_t toUint24 (const uint8_t bytes[])
uint32_t toUint32 (const uint8_t bytes[])
double toDist (const uint8_t *bytes)
uint32_t toIcao (const uint8_t bytes[])
double toLatLon (const uint8_t bytes[])
double toAlt (const uint8_t bytes[])
double toVel (const uint8_t bytes[])
uint8_t toGS (const uint8_t bytes[])
double toHeading (const uint8_t bytes[])
int16_t toHeading2 (double y, double x)
float toTOA (const uint8_t bytes[])
float toFloat (const uint8_t *bufferPos)
double toDouble (const uint8_t *bufferPos)
void uint162Buf (uint8_t *bufferPos, uint16_t value)
void int242Buf (uint8_t *bufferPos, int32_t value)
void uint242Buf (uint8_t *bufferPos, uint32_t value)
void uint322Buf (uint8_t *bufferPos, uint32_t value)
void icao2Buf (uint8_t *bufferPos, uint32_t icao)
void charArray2Buf (uint8_t *bufferPos, char arr[], uint8_t len)
void float2Buf (uint8_t *bufferPos, float value)
void double2Buf (uint8_t *bufferPos, double value)
void latLon2Buf (uint8_t bytes[], double value)
uint8_t calcChecksum (uint8_t *buffer, uint8_t len)
void appendChecksum (uint8_t *buffer, uint8_t len)
Detailed Description
Copyright
Copyright (c) 2021 Sagetech, Inc. All rights reserved.
Author
jimb
Date
Feb 2, 2021
Definition in file sgUtil.h.
Macro Definition Documentation
PI
#define PI 3.14159265359
Definition at line 36 of file sgUtil.h.
swap16
#define swap16 (data) ((((data) >> 8) & 0x00FF) | (((data) << 8) & 0xFF00))
Definition at line 16 of file sgUtil.h.
swap24
#define swap24 (data) (((data) >> 16) | ((data)&0x00FF00) | (((data) << 16) & 0xFF0000))
Definition at line 21 of file sgUtil.h.
swap32
#define swap32 (data) (((data) >> 24) | (((data)&0x00FF0000) >> 8) | (((data)&0x0000FF00) << 8) | ((data) << 24))
Definition at line 26 of file sgUtil.h.
swap64
#define swap64 (data) (swap32((data & 0x00000000ffffffffULL))) << 32 | swap32(data >> 32))
Definition at line 31 of file sgUtil.h.
toDeg
#define toDeg (rad) ((rad)*180 / PI)
Definition at line 45 of file sgUtil.h.
Referenced by toHeading2().
toFeet
#define toFeet (meter) ((meter)*3.2808)
Definition at line 55 of file sgUtil.h.
toMeter
#define toMeter (feet) ((feet)*0.3048)
Definition at line 50 of file sgUtil.h.
toRad
#define toRad (deg) ((deg)*PI / 180.0)
Definition at line 40 of file sgUtil.h.
Function Documentation
appendChecksum()
void appendChecksum (uint8_t * buffer, uint8_t len)
Add the checksum to a host message.
Parameters
buffer The raw message buffer.
len The total quantity of bytes in the buffer
no return value, final buffer byte is set to the checksum value.
Definition at line 16 of file appendChecksum.c.
Referenced by sgEncodeDataReq(), sgEncodeFlightId(), sgEncodeGPS(), sgEncodeInstall(), sgEncodeOperating(), and sgEncodeTargetReq().
calcChecksum()
uint8_t calcChecksum (uint8_t * buffer, uint8_t len)
Calculate checksum for a host message.
Parameters
buffer The raw message buffer.
len The total quantity of bytes in the buffer
Returns
The resulting checksum.
Definition at line 16 of file calcChecksum.c.
Referenced by appendChecksum().
charArray2Buf()
void charArray2Buf (uint8_t * bufferPos, char arr[], uint8_t len)
Converts an array of characters into its host message buffer format
Parameters
bufferPos The address of the field's first corresponding buffer byte.
arr[] The array of characters.
len The number of characters in the array.
no return value, the specified quantity of buffer bytes are filled by reference
Definition at line 17 of file charArray2Buf.c.
Referenced by sgEncodeFlightId(), sgEncodeGPS(), and sgEncodeInstall().
double2Buf()
void double2Buf (uint8_t * bufferPos, double value)
Converts a double into its host message buffer format
Parameters
bufferPos The address of the field's first corresponding buffer byte
value The double to be converted
no return value, eight buffer bytes are filled by reference
Warning
The output of this function depends on the machine's endianness. It is designed for Little-Endian machines, only
float2Buf()
void float2Buf (uint8_t * bufferPos, float value)
Converts a float into its host message buffer format
Parameters
bufferPos The address of the field's first corresponding buffer byte.
value The float to be converted.
no return value, four buffer bytes are filled by reference
Warning
The output of this function depends on the machine's endianness. It is designed for Little-Endian machines, only.
Definition at line 16 of file float2Buf.c.
Referenced by sgEncodeGPS().
icao2Buf()
void icao2Buf (uint8_t * bufferPos, uint32_t icao)
Converts a uint32_t containing an ICAO into its 24-bit host message buffer format
Parameters
bufferPos The address of the field's first corresponding buffer byte.
icao The uint32_t ICAO to be converted.
no return value, three buffer bytes are filled by reference
Warning
icao parameter must be between 0x000000 and 0xFFFFFF
Definition at line 16 of file icao2Buf.c.
Referenced by sgEncodeInstall(), and sgEncodeTargetReq().
int242Buf()
void int242Buf (uint8_t * bufferPos, int32_t value)
Converts a int16_t into its host message buffer format
Parameters
bufferPos The address of the field's first corresponding buffer byte.
value The int32_t to be converted.
no return value, two buffer bytes are filled by reference
latLon2Buf()
void latLon2Buf (uint8_t bytes[], double value)
Converts a double into an encoded lat/lon buffer format.
Parameters
bytes address of the field's first corresponding buffer byte
value the double to be converted.
no return value, 3 buffer bytes are filled by reference.
toAlt()
double toAlt (const uint8_t bytes[])
Convert an array to an altitude.
Parameters
bytes The bytes to get the altitude from.
Returns
The converted altitude.
Definition at line 18 of file toAlt.c.
Referenced by sgDecodeSVR().
toDist()
double toDist (const uint8_t * bytes)
Converts an array of bytes to a distance.
Parameters
bytes The array of bytes to convert.
Returns
The distance value.
toDouble()
double toDouble (const uint8_t * bufferPos)
Convert an array of bytes to a double
Parameters
bufferPos the address of the field's first corresponding buffer byte.
Returns
The converted double value.
toFloat()
float toFloat (const uint8_t * bufferPos)
Convert an array of bytes to a float
Parameters
bufferPos the address of the field's first corresponding buffer byte.
Returns
The converted float value.
toGS()
uint8_t toGS (const uint8_t bytes[])
Converts the array of bytes to the surface ground speed.
Parameters
bytes The bytes to extract the ground speed.
Returns
The converted ground speed.
Definition at line 16 of file toGS.c.
Referenced by sgDecodeSVR().
toHeading()
double toHeading (const uint8_t bytes[])
Converts the bytes into the heading value.
Parameters
bytes The bytes holding the heading value.
Returns
The heading.
Definition at line 18 of file toHeading.c.
Referenced by sgDecodeSVR().
toHeading2()
int16_t toHeading2 (double y, double x)
Determine heading from y and x speed vectors.
Parameters
y The y speed vector.
x The x speed vector.
Returns
The resulting heading.
Definition at line 18 of file toHeading2.c.
Referenced by sgDecodeSVR().
toIcao()
uint32_t toIcao (const uint8_t bytes[])
Converts an array of bytes to a 24 bit unsigned integer with leading 0's.
Parameters
bytes The array of bytes to convert.
Returns
The 32 bit unsigned integer.
Definition at line 16 of file toIcao.c.
Referenced by sgDecodeInstall().
toInt16()
int16_t toInt16 (const uint8_t bytes[])
Converts an array of bytes to a 16 bit integer.
Parameters
bytes The array of bytes to convert.
Returns
The 16 bit integer.
Definition at line 16 of file toInt16.c.
Referenced by sgDecodeSVR(), toTOA(), and toVel().
toInt32()
int32_t toInt32 (const uint8_t bytes[])
Converts an array of bytes to a 32 bit integer.
Parameters
bytes The array of bytes to convert.
Returns
The 32 bit integer.
Definition at line 16 of file toInt32.c.
Referenced by sgDecodeAck(), sgDecodeMSR(), sgDecodeSVR(), toAlt(), and toLatLon().
toLatLon()
double toLatLon (const uint8_t bytes[])
Converts an array of bytes to a lat/lon floating point number.
Parameters
bytes The array of bytes to convert.
Returns
The lat/lon value.
Definition at line 18 of file toLatLon.c.
Referenced by sgDecodeSVR().
toTOA()
float toTOA (const uint8_t bytes[])
Convert the array of bytes to a time of applicability (TOA).
Parameters
bytes The bytes to convert to a TOA.
Returns
The converted TOA.
Definition at line 16 of file toTOA.c.
Referenced by sgDecodeMSR(), and sgDecodeSVR().
toUint16()
uint16_t toUint16 (const uint8_t bytes[])
Converts an array of bytes to a 16 unsigned bit integer.
Parameters
bytes The array of bytes to convert.
Returns
The 16 bit integer.
Definition at line 16 of file toUint16.c.
Referenced by sgDecodeInstall().
toUint24()
uint32_t toUint24 (const uint8_t bytes[])
Converts an array of bytes to a 24 bit unsigned integer with leading 0s.
Parameters
bytes The array of bytes to convert.
Returns
The 24 bit unsigned integer with leading 0s.
toUint32()
uint32_t toUint32 (const uint8_t bytes[])
Converts an array of bytes to a 32 bit unsigned integer.
Parameters
bytes The array of bytes to convert.
Returns
The 32 bit unsigned integer.
Definition at line 16 of file toUint32.c.
Referenced by sgDecodeInstall().
toVel()
double toVel (const uint8_t bytes[])
Converts an array of bytes to an airborne velocity.
Parameters
bytes The bytes to extract the velocity.
Returns
The converted velocity.
Definition at line 18 of file toVel.c.
Referenced by sgDecodeSVR().
uint162Buf()
void uint162Buf (uint8_t * bufferPos, uint16_t value)
Converts a uint16_t into its host message buffer format
Parameters
bufferPos The address of the field's first corresponding buffer byte.
value The uint16_t to be converted.
no return value, two buffer bytes are filled by reference
Definition at line 16 of file uint162Buf.c.
Referenced by sgEncodeInstall(), sgEncodeOperating(), and sgEncodeTargetReq().
uint242Buf()
void uint242Buf (uint8_t * bufferPos, uint32_t value)
Converts a uint32_t into a 24 bit host message buffer format
Parameters
bufferPos The address of the field's first corresponding buffer byte.
value The int32_t to be converted.
no return value, three buffer bytes are filled by reference
uint322Buf()
void uint322Buf (uint8_t * bufferPos, uint32_t value)
Converts a uint32_t into its host message buffer format
Parameters
bufferPos The address of the field's first corresponding buffer byte.
value The uint32_t to be converted.
no return value, two buffer bytes are filled by reference
Definition at line 16 of file uint322Buf.c.
Referenced by sgEncodeFlightId(), and sgEncodeInstall().