APM:Libraries: libraries/AP_HAL_SITL/SITL_cmdline.cpp File Reference
SITL_cmdline.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include "AP_HAL_SITL.h"
#include "AP_HAL_SITL_Namespace.h"
#include "HAL_SITL_Class.h"
#include "UARTDriver.h"
#include <AP_HAL/utility/getopt_cpp.h>
#include <AP_HAL_SITL/Storage.h>
#include <AP_Param/AP_Param.h>
#include <SITL/SIM_Multicopter.h>
#include <SITL/SIM_Helicopter.h>
#include <SITL/SIM_SingleCopter.h>
#include <SITL/SIM_Plane.h>
#include <SITL/SIM_QuadPlane.h>
#include <SITL/SIM_Rover.h>
#include <SITL/SIM_BalanceBot.h>
#include <SITL/SIM_Sailboat.h>
#include <SITL/SIM_MotorBoat.h>
#include <SITL/SIM_CRRCSim.h>
#include <SITL/SIM_Gazebo.h>
#include <SITL/SIM_last_letter.h>
#include <SITL/SIM_JSBSim.h>
#include <SITL/SIM_Tracker.h>
#include <SITL/SIM_Balloon.h>
#include <SITL/SIM_FlightAxis.h>
#include <SITL/SIM_Calibration.h>
#include <SITL/SIM_XPlane.h>
#include <SITL/SIM_Submarine.h>
#include <SITL/SIM_SilentWings.h>
#include <SITL/SIM_Morse.h>
#include <SITL/SIM_AirSim.h>
#include <SITL/SIM_Scrimmage.h>
#include <SITL/SIM_Webots.h>
#include <SITL/SIM_Webots_Python.h>
#include <SITL/SIM_JSON.h>
#include <SITL/SIM_Blimp.h>
#include <SITL/SIM_NoVehicle.h>
#include <AP_Filesystem/AP_Filesystem.h>
#include <AP_Vehicle/AP_Vehicle_Type.h>
#include <signal.h>
#include <stdio.h>
#include <time.h>
#include <sys/time.h>
#include "ap_version.h"
Macros
#define FORCE_VERSION_H_INCLUDE
Functions
static void _sig_fpe (int signum)
static void _sig_segv (int signum)
Variables
HAL_SITL & hal
struct {
const char * name
Aircraft *(* constructor)(const char *frame_str)
} model_constructors []
Macro Definition Documentation
FORCE_VERSION_H_INCLUDE
#define FORCE_VERSION_H_INCLUDE
Definition at line 50 of file SITL_cmdline.cpp.
Function Documentation
_sig_fpe()
static void _sig_fpe (int signum) static
Definition at line 59 of file SITL_cmdline.cpp.
Referenced by HALSITL::SITL_State::_set_signal_handlers().
_sig_segv()
static void _sig_segv (int signum) static
Definition at line 68 of file SITL_cmdline.cpp.
Referenced by HALSITL::SITL_State::_set_signal_handlers().
Variable Documentation
constructor
Aircraft *(* constructor) (const char *frame_str) (const char * frame_str)
Definition at line 131 of file SITL_cmdline.cpp.
Referenced by funcargs(), and simpleexp().
hal
HAL_SITL& hal extern
The data_array uses 3 elements to perform the data transaction. The first element is a data byte that provides to FPGA's hardware the transaction type that will be realized inside the SPI module. Where:
╔═════════╦═════════╦══════════╦══════════╦══════════╦══════════╦══════════╦═══════════╗ ║ MSB ║ ║ ║ ║ ║ ║ ║ LSB ║ ╠═════════╬═════════╬══════════╬══════════╬══════════╬══════════╬══════════╬═══════════╣ ║ wr_addr ║ rd_addr ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ reserved ║ ╚═════════╩═════════╩══════════╩══════════╩══════════╩══════════╩══════════╩═══════════╝
╔═══════════╦═════════╦═════════╗ ║ Register ║ wr_addr ║ rd_addr ║ ╠═══════════╬═════════╬═════════╣ ║ write ║ 0 ║ X ║ ╠═══════════╬═════════╬═════════╣ ║ read ║ X ║ 0 ║ ╠═══════════╬═════════╬═════════╣ ║ status ║ 1 ║ 1 ║ ╚═══════════╩═════════╩═════════╝
So, to perform a write transaction in the SPI module it's necessary to send. E.g: 0b 01xx xxxx And to a read transaction.. 0b 10xx xxxx
The PWM frequency is always even and the duty cycle percentage odd. E.g: pwm_01: Address 0x0000 frequency : Address 0x0001 duty cycle pwm_02: Address 0x0002 frequency Eg of allowed values: // PWM channel in 100Hz uint16_t freq = 100;
// duty cycle in (1823/65535) that's 2.78% of 100Hz: // the signal will hold high until 278 usec uint16_t duty = 1823;
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.
[struct]
const struct { ... } model_constructors[]
Referenced by HALSITL::SITL_State::_parse_command_line().
name
const char* name
Definition at line 130 of file SITL_cmdline.cpp.