APM:Libraries: libraries/AP_Common/sorting.cpp File Reference
sorting.cpp File Reference
#include <stdint.h>
#include "sorting.h"
Functions
void insertion_sort_uint16 (uint16_t *data, uint16_t n)
uint16_t remove_duplicates_uint16 (uint16_t *data, uint16_t n)
bool bisect_search_uint16 (const uint16_t *data, uint16_t n, uint16_t value)
uint16_t remove_list_uint16 (uint16_t *data, uint16_t n, const uint16_t *rem, uint16_t n2)
uint16_t common_list_uint16 (uint16_t *data, uint16_t n, const uint16_t *data2, uint16_t n2)
Function Documentation
bisect_search_uint16()
bool bisect_search_uint16 (const uint16_t * data, uint16_t n, uint16_t value)
Definition at line 59 of file sorting.cpp.
Referenced by common_list_uint16(), remove_list_uint16(), and TEST().
common_list_uint16()
uint16_t common_list_uint16 (uint16_t * data, uint16_t n, const uint16_t * data2, uint16_t n2)
Definition at line 100 of file sorting.cpp.
insertion_sort_uint16()
void insertion_sort_uint16 (uint16_t * data, uint16_t n)
Definition at line 24 of file sorting.cpp.
Referenced by TEST(), TEST(), TEST(), and TEST().
remove_duplicates_uint16()
uint16_t remove_duplicates_uint16 (uint16_t * data, uint16_t n)
Definition at line 42 of file sorting.cpp.
Referenced by TEST().
remove_list_uint16()
uint16_t remove_list_uint16 (uint16_t * data, uint16_t n, const uint16_t * rem, uint16_t n2)
Definition at line 84 of file sorting.cpp.
Referenced by TEST().