APM:Libraries: libraries/AP_HAL/utility/sparse-endian.h File Reference
sparse-endian.h File Reference
#include <AP_Common/AP_Common.h>
#include <AP_Math/AP_Math.h>
#include <byteswap.h>
#include <endian.h>
#include <stdint.h>
Macros
#define __ap_bitwise
#define __ap_force
#define bswap_16_on_le(x) __bswap_16(x)
#define bswap_32_on_le(x) __bswap_32(x)
#define bswap_64_on_le(x) __bswap_64(x)
#define bswap_16_on_be(x) (x)
#define bswap_32_on_be(x) (x)
#define bswap_64_on_be(x) (x)
Typedefs
typedef uint16_t __ap_bitwise le16_t
typedef uint16_t __ap_bitwise be16_t
typedef uint32_t __ap_bitwise le32_t
typedef uint32_t __ap_bitwise be32_t
typedef uint64_t __ap_bitwise le64_t
typedef uint64_t __ap_bitwise be64_t
Functions
static le16_t htole16 (uint16_t value)
static le32_t htole32 (uint32_t value)
static le64_t htole64 (uint64_t value)
static be16_t htobe16 (uint16_t value)
static be32_t htobe32 (uint32_t value)
static be64_t htobe64 (uint64_t value)
static uint16_t le16toh (le16_t value)
static uint32_t le32toh (le32_t value)
static uint64_t le64toh (le64_t value)
static uint16_t be16toh (be16_t value)
static uint32_t be32toh (be32_t value)
static uint64_t be64toh (be64_t value)
static uint16_t le16toh_ptr (const uint8_t *p)
static uint32_t le24toh_ptr (const uint8_t *p)
static uint32_t le32toh_ptr (const uint8_t *p)
static uint64_t le64toh_ptr (const uint8_t *p)
static uint16_t be16toh_ptr (const uint8_t *p)
static uint32_t be24toh_ptr (const uint8_t *p)
static uint32_t be32toh_ptr (const uint8_t *p)
static uint64_t be64toh_ptr (const uint8_t *p)
static float be32tofloat_ptr (const uint8_t *p)
static float be32tofloat_ptr (const uint8_t *p, const uint8_t offset)
static void put_le16_ptr (uint8_t *p, uint16_t v)
static void put_le24_ptr (uint8_t *p, uint32_t v)
static void put_le32_ptr (uint8_t *p, uint32_t v)
static void put_le64_ptr (uint8_t *p, uint64_t v)
static void put_be16_ptr (uint8_t *p, uint16_t v)
static void put_be24_ptr (uint8_t *p, uint32_t v)
static void put_be32_ptr (uint8_t *p, uint32_t v)
static void put_be64_ptr (uint8_t *p, uint64_t v)
Macro Definition Documentation
__ap_bitwise
#define __ap_bitwise
Definition at line 36 of file sparse-endian.h.
__ap_force
#define __ap_force
Definition at line 37 of file sparse-endian.h.
Referenced by be16toh(), be32toh(), be64toh(), htobe16(), htobe32(), htobe64(), htole16(), htole32(), htole64(), le16toh(), le32toh(), and le64toh().
bswap_16_on_be
#define bswap_16_on_be (x) (x)
Definition at line 64 of file sparse-endian.h.
Referenced by htole16(), and le16toh().
bswap_16_on_le
#define bswap_16_on_le (x) __bswap_16(x)
Definition at line 61 of file sparse-endian.h.
Referenced by be16toh(), and htobe16().
bswap_32_on_be
#define bswap_32_on_be (x) (x)
Definition at line 65 of file sparse-endian.h.
Referenced by htole32(), and le32toh().
bswap_32_on_le
#define bswap_32_on_le (x) __bswap_32(x)
Definition at line 62 of file sparse-endian.h.
Referenced by be32toh(), and htobe32().
bswap_64_on_be
#define bswap_64_on_be (x) (x)
Definition at line 66 of file sparse-endian.h.
Referenced by htole64(), and le64toh().
bswap_64_on_le
#define bswap_64_on_le (x) __bswap_64(x)
Definition at line 63 of file sparse-endian.h.
Referenced by be64toh(), and htobe64().
Typedef Documentation
be16_t
typedef uint16_t __ap_bitwise be16_t
Definition at line 41 of file sparse-endian.h.
be32_t
typedef uint32_t __ap_bitwise be32_t
Definition at line 43 of file sparse-endian.h.
be64_t
typedef uint64_t __ap_bitwise be64_t
Definition at line 45 of file sparse-endian.h.
le16_t
typedef uint16_t __ap_bitwise le16_t
Definition at line 40 of file sparse-endian.h.
le32_t
typedef uint32_t __ap_bitwise le32_t
Definition at line 42 of file sparse-endian.h.
le64_t
typedef uint64_t __ap_bitwise le64_t
Definition at line 44 of file sparse-endian.h.
Function Documentation
be16toh()
static uint16_t be16toh (be16_t value) inline static
Definition at line 88 of file sparse-endian.h.
Referenced by Linux::RCOutput_AeroIO::_hw_read(), AP_GPS_SIRF::_parse_gps(), AP_Compass_HMC5843::_read_sample(), Linux::RCOutput_Bebop::_run_rcout(), AP_ADC_ADS1115::_update(), AP_RangeFinder_MaxsonarI2CXL::get_reading(), SITL::I2CRegisters_16Bit::get_reg_value(), AP_RangeFinder_LightWareI2C::legacy_get_reading(), AP_RangeFinder_LightWareI2C::legacy_init(), Linux::RCOutput_Bebop::read_obs_data(), AP_Airspeed_MS5525::read_prom(), AP_RangeFinder_VL53L1X::read_register16(), AP_RangeFinder_VL53L0X::read_register16(), AP_InertialSensor_ADIS1647x::read_sensor16(), AP_InertialSensor_ADIS1647x::read_sensor32(), AP_InertialSensor_ADIS1647x::read_sensor32_delta(), SITL::EFI_MegaSquirt::send_table(), AP_GPS_GSOF::SwapUint16(), AP_RangeFinder_PulsedLightLRF::timer(), and AP_SmartAudio::unpack_settings().
be16toh_ptr()
static uint16_t be16toh_ptr (const uint8_t * p) inline static
Definition at line 97 of file sparse-endian.h.
be24toh_ptr()
static uint32_t be24toh_ptr (const uint8_t * p) inline static
Definition at line 98 of file sparse-endian.h.
be32tofloat_ptr() [1/2]
static float be32tofloat_ptr (const uint8_t * p) inline static
Definition at line 102 of file sparse-endian.h.
Referenced by be32tofloat_ptr().
be32tofloat_ptr() [2/2]
static float be32tofloat_ptr (const uint8_t * p, const uint8_t offset) inline static
Definition at line 103 of file sparse-endian.h.
be32toh()
static uint32_t be32toh (be32_t value) inline static
Definition at line 89 of file sparse-endian.h.
Referenced by AP_GPS_SIRF::_parse_gps(), Linux::RCOutput_Bebop::_run_rcout(), AP_GPS_GSOF::SwapUint32(), and SITL::EFI_MegaSquirt::update().
be32toh_ptr()
static uint32_t be32toh_ptr (const uint8_t * p) inline static
Definition at line 99 of file sparse-endian.h.
Referenced by be32tofloat_ptr().
be64toh()
static uint64_t be64toh (be64_t value) inline static
Definition at line 90 of file sparse-endian.h.
be64toh_ptr()
static uint64_t be64toh_ptr (const uint8_t * p) inline static
Definition at line 100 of file sparse-endian.h.
htobe16()
static be16_t htobe16 (uint16_t value) inline static
Definition at line 80 of file sparse-endian.h.
Referenced by Linux::RCOutput_AeroIO::_hw_read(), Linux::RCOutput_AeroIO::_hw_write(), Linux::RCOutput_Bebop::_set_ref_speed(), AP_ADC_ADS1115::_start_conversion(), AP_Spektrum_Telem::calc_airspeed(), AP_Spektrum_Telem::calc_altitude(), AP_Spektrum_Telem::calc_batt_amps(), AP_Spektrum_Telem::calc_batt_volts(), AP_Spektrum_Telem::calc_esc(), AP_Spektrum_Telem::calc_rpm(), AP_Spektrum_Telem::calc_temperature(), AP_RangeFinder_LightWareI2C::legacy_init(), Linux::RCOutput_Bebop::play_note(), SITL::I2CRegisters_ConfigurableLength::rdwr(), SITL::MS5XXX::rdwr(), SITL::EFI_MegaSquirt::send_table(), SITL::I2CRegisters_ConfigurableLength::set_register(), SITL::I2CRegisters_16Bit::set_register(), SITL::I2CRegisters_ConfigurableLength::set_register(), SITL::I2CRegisters_16Bit::set_register(), SITL::MCP9600::update(), SITL::RichenPower::RichenUnion::update_checksum(), SITL::PS_TeraRangerTower::update_output(), and SITL::RichenPower::update_send().
htobe32()
static be32_t htobe32 (uint32_t value) inline static
Definition at line 81 of file sparse-endian.h.
Referenced by SITL::EFI_MegaSquirt::send_table(), and SITL::RichenPower::update_send().
htobe64()
static be64_t htobe64 (uint64_t value) inline static
Definition at line 82 of file sparse-endian.h.
htole16()
static le16_t htole16 (uint16_t value) inline static
Definition at line 76 of file sparse-endian.h.
Referenced by SITL::QMC5883L::update().
htole32()
static le32_t htole32 (uint32_t value) inline static
Definition at line 77 of file sparse-endian.h.
htole64()
static le64_t htole64 (uint64_t value) inline static
Definition at line 78 of file sparse-endian.h.
le16toh()
static uint16_t le16toh (le16_t value) inline static
Definition at line 84 of file sparse-endian.h.
Referenced by Linux::RCInput_SoloLink::_check_hdr(), AP_Compass_BMM150::_load_trim_values(), AP_InertialSensor_BMI160::_read_fifo(), Linux::RCInput_SoloLink::_timer_tick(), AP_Compass_BMM150::_update(), AP_RangeFinder_Benewake_TFMiniPlus::process_raw_measure(), AP_Compass_IST8308::timer(), AP_Compass_IST8310::timer(), and AP_Compass_QMC5883L::timer().
le16toh_ptr()
static uint16_t le16toh_ptr (const uint8_t * p) inline static
Definition at line 93 of file sparse-endian.h.
Referenced by AP_RCProtocol_SRXL2::capture_scaled_input(), FlashTest::flash_write(), AP_Frsky_SPortParser::get_packet(), and GCS_MAVLINK::handle_file_transfer_protocol().
le24toh_ptr()
static uint32_t le24toh_ptr (const uint8_t * p) inline static
Definition at line 94 of file sparse-endian.h.
le32toh()
static uint32_t le32toh (le32_t value) inline static
Definition at line 85 of file sparse-endian.h.
le32toh_ptr()
static uint32_t le32toh_ptr (const uint8_t * p) inline static
Definition at line 95 of file sparse-endian.h.
Referenced by AP_RCProtocol_FPort::decode_downlink(), AP_Frsky_SPortParser::get_packet(), and GCS_MAVLINK::handle_file_transfer_protocol().
le64toh()
static uint64_t le64toh (le64_t value) inline static
Definition at line 86 of file sparse-endian.h.
le64toh_ptr()
static uint64_t le64toh_ptr (const uint8_t * p) inline static
Definition at line 96 of file sparse-endian.h.
put_be16_ptr()
static void put_be16_ptr (uint8_t * p, uint16_t v) inline static
Definition at line 113 of file sparse-endian.h.
Referenced by AP_SmartAudio::push_uint16_command_frame(), and SITL::MicroStrain::put_int().
put_be24_ptr()
static void put_be24_ptr (uint8_t * p, uint32_t v) inline static
Definition at line 114 of file sparse-endian.h.
put_be32_ptr()
static void put_be32_ptr (uint8_t * p, uint32_t v) inline static
Definition at line 115 of file sparse-endian.h.
Referenced by SITL::MicroStrain::put_float().
put_be64_ptr()
static void put_be64_ptr (uint8_t * p, uint64_t v) inline static
Definition at line 116 of file sparse-endian.h.
Referenced by SITL::MicroStrain::put_double().
put_le16_ptr()
static void put_le16_ptr (uint8_t * p, uint16_t v) inline static
Definition at line 109 of file sparse-endian.h.
Referenced by FlashTest::flash_write(), and GCS_MAVLINK::send_ftp_reply().
put_le24_ptr()
static void put_le24_ptr (uint8_t * p, uint32_t v) inline static
Definition at line 110 of file sparse-endian.h.
put_le32_ptr()
static void put_le32_ptr (uint8_t * p, uint32_t v) inline static
Definition at line 111 of file sparse-endian.h.
Referenced by GCS_MAVLINK::ftp_worker(), and GCS_MAVLINK::send_ftp_reply().
put_le64_ptr()
static void put_le64_ptr (uint8_t * p, uint64_t v) inline static
Definition at line 112 of file sparse-endian.h.