APM:Libraries: libraries/AP_RCProtocol/spm_srxl_config.h File Reference
spm_srxl_config.h File Reference
#include <AP_Math/crc.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_Common/AP_Common.h>
Macros
#define SRXL_NUM_OF_BUSES 1
#define SRXL_DEVICE_ID 0x31
#define SRXL_DEVICE_ID_BASE_RX 0x30
#define SRXL_DEVICE_PRIORITY 20
#define SRXL_DEVICE_INFO (SRXL_DEVINFO_NO_RF)
#define SRXL_SUPPORTED_BAUD_RATES 0
#define SRXL_CRC_CALCULATE(packet, length, crc) crc16_ccitt(packet, length, crc)
#define SRXL_CRC_OPTIMIZE_MODE SRXL_CRC_OPTIMIZE_EXTERNAL
#define SRXL_STM_TARGET_FAMILY SRXL_STM_TARGET_F3
Functions
void srxlChangeBaudRate (uint8_t uart, uint32_t baudRate)
void srxlSendOnUart (uint8_t uart, uint8_t *pBuffer, uint8_t length)
void srxlFillTelemetry (SrxlTelemetryData *pTelemetryData)
void srxlReceivedChannelData (SrxlChannelData *pChannelData, bool isFailsafe)
bool srxlOnBind (SrxlFullID device, SrxlBindData info)
void srxlOnVtx (SrxlVtxData *pVtxData)
static void srxlEnterCriticalSection (void)
static void srxlExitCriticalSection (void)
Macro Definition Documentation
SRXL_CRC_CALCULATE
#define SRXL_CRC_CALCULATE (packet, length, crc) crc16_ccitt(packet, length, crc)
Definition at line 78 of file spm_srxl_config.h.
Referenced by srxlCrc16().
SRXL_CRC_OPTIMIZE_MODE
#define SRXL_CRC_OPTIMIZE_MODE SRXL_CRC_OPTIMIZE_EXTERNAL
Definition at line 80 of file spm_srxl_config.h.
SRXL_DEVICE_ID
#define SRXL_DEVICE_ID 0x31
Definition at line 52 of file spm_srxl_config.h.
Referenced by AP_RCProtocol_SRXL2::_process_byte().
SRXL_DEVICE_ID_BASE_RX
#define SRXL_DEVICE_ID_BASE_RX 0x30
Definition at line 53 of file spm_srxl_config.h.
Referenced by AP_RCProtocol_SRXL2::process_handshake().
SRXL_DEVICE_INFO
#define SRXL_DEVICE_INFO (SRXL_DEVINFO_NO_RF)
Definition at line 67 of file spm_srxl_config.h.
Referenced by AP_RCProtocol_SRXL2::_bootstrap().
SRXL_DEVICE_PRIORITY
#define SRXL_DEVICE_PRIORITY 20
Definition at line 62 of file spm_srxl_config.h.
Referenced by AP_RCProtocol_SRXL2::_bootstrap().
SRXL_NUM_OF_BUSES
#define SRXL_NUM_OF_BUSES 1
Definition at line 44 of file spm_srxl_config.h.
Referenced by srxlEnterBind(), srxlGetDeviceID(), srxlGetTimeoutCount_ms(), srxlInitBus(), srxlIsBusMaster(), srxlOnFrameError(), srxlParsePacket(), srxlRun(), srxlSetBindInfo(), and srxlSetVtxData().
SRXL_STM_TARGET_FAMILY
#define SRXL_STM_TARGET_FAMILY SRXL_STM_TARGET_F3
Definition at line 85 of file spm_srxl_config.h.
SRXL_SUPPORTED_BAUD_RATES
#define SRXL_SUPPORTED_BAUD_RATES 0
Definition at line 70 of file spm_srxl_config.h.
Referenced by AP_RCProtocol_SRXL2::_bootstrap(), and srxlParsePacket().
Function Documentation
srxlChangeBaudRate()
void srxlChangeBaudRate (uint8_t uart, uint32_t baudRate)
Definition at line 329 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlOnFrameError(), srxlParsePacket(), and srxlRun().
srxlEnterCriticalSection()
static void srxlEnterCriticalSection (void) inline static
Definition at line 137 of file spm_srxl_config.h.
Referenced by srxlCrc16().
srxlExitCriticalSection()
static void srxlExitCriticalSection (void) inline static
Definition at line 142 of file spm_srxl_config.h.
Referenced by srxlCrc16().
srxlFillTelemetry()
void srxlFillTelemetry (SrxlTelemetryData * pTelemetryData)
Definition at line 355 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlSend().
srxlOnBind()
bool srxlOnBind (SrxlFullID device, SrxlBindData info)
Definition at line 384 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlParsePacket().
srxlOnVtx()
void srxlOnVtx (SrxlVtxData * pVtxData)
Definition at line 390 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlParsePacket().
srxlReceivedChannelData()
void srxlReceivedChannelData (SrxlChannelData * pChannelData, bool isFailsafe)
Definition at line 367 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlParsePacket().
srxlSendOnUart()
void srxlSendOnUart (uint8_t uart, uint8_t * pBuffer, uint8_t length)
Definition at line 342 of file AP_RCProtocol_SRXL2.cpp.
Referenced by srxlSend().