APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/stdio.h File Reference
stdio.h File Reference
#include <stdarg.h>
#include <stdint.h>
#include <stddef.h>
Macros
#define L_tmpnam 32
Functions
int __wrap_snprintf (char *str, size_t size, const char *fmt,...)
int __wrap_vsnprintf (char *str, size_t size, const char *fmt, va_list ap)
int __wrap_vasprintf (char **strp, const char *fmt, va_list ap)
int __wrap_asprintf (char **strp, const char *fmt,...)
int __wrap_vprintf (const char *fmt, va_list arg)
int __wrap_printf (const char *fmt,...)
int __wrap_scanf (const char *fmt,...)
int __wrap_sscanf (const char *buf, const char *fmt,...)
int __wrap_fprintf (void *f, const char *fmt,...)
int vsnprintf (char *str, size_t size, const char *fmt, va_list ap)
int snprintf (char *str, size_t size, const char *fmt,...)
int vasprintf (char **strp, const char *fmt, va_list ap)
int asprintf (char **strp, const char *fmt,...)
int vprintf (const char *fmt, va_list arg)
int printf (const char *fmt,...)
void * malloc (size_t size)
void * calloc (size_t nmemb, size_t size)
void free (void *ptr)
void * realloc (void *ptr, size_t size) __attribute__((deprecated))
void malloc_check (const void *ptr)
Variables
int(* vprintf_console_hook)(const char *fmt, va_list arg)
Macro Definition Documentation
L_tmpnam
#define L_tmpnam 32
Definition at line 51 of file stdio.h.
Function Documentation
__wrap_asprintf()
int __wrap_asprintf (char ** strp, const char * fmt, ...)
Definition at line 81 of file stdio.cpp.
__wrap_fprintf()
int __wrap_fprintf (void * f, const char * fmt, ...)
Definition at line 127 of file stdio.cpp.
__wrap_printf()
int __wrap_printf (const char * fmt, ...)
Definition at line 106 of file stdio.cpp.
__wrap_scanf()
int __wrap_scanf (const char * fmt, ...)
Definition at line 145 of file stdio.cpp.
__wrap_snprintf()
int __wrap_snprintf (char * str, size_t size, const char * fmt, ...)
Definition at line 41 of file stdio.cpp.
__wrap_sscanf()
int __wrap_sscanf (const char * buf, const char * fmt, ...)
__wrap_vasprintf()
int __wrap_vasprintf (char ** strp, const char * fmt, va_list ap)
Definition at line 66 of file stdio.cpp.
__wrap_vprintf()
int __wrap_vprintf (const char * fmt, va_list arg)
Definition at line 90 of file stdio.cpp.
__wrap_vsnprintf()
int __wrap_vsnprintf (char * str, size_t size, const char * fmt, va_list ap)
Definition at line 57 of file stdio.cpp.
asprintf()
int asprintf (char ** strp, const char * fmt, ...)
Referenced by Linux::PWM_Sysfs_Bebop::_generate_duty_path(), Linux::PWM_Sysfs::_generate_duty_path(), Linux::PWM_Sysfs_Bebop::_generate_enable_path(), Linux::PWM_Sysfs::_generate_enable_path(), Linux::PWM_Sysfs::_generate_export_path(), Linux::PWM_Sysfs_Bebop::_generate_period_path(), Linux::PWM_Sysfs::_generate_period_path(), Linux::PWM_Sysfs::_generate_polarity_path(), HALSITL::SITL_State::_parse_command_line(), ChibiOS::Storage::_save_backup(), SITL::AIS::AIS(), apfs_tmpfile(), SITL::JSBSim::create_templates(), Linux::I2CDeviceManager::get_device(), ESP32::I2CDevice::I2CDevice(), Linux::Led_Sysfs::init(), SITL::XPlane::load_dref_map(), SITL::Frame::load_frame_params(), Linux::RCInput_Navio2::open_channel(), AP_GPS_SBF::read(), SITL::JSON_Master::send(), SITL::JSBSim::send_servos(), SITL::SilentWings::send_servos(), AnalogSource_Navio2::set_channel(), SITL::FlightAxis::soap_request_start(), ChibiOS::SPIDevice::SPIDevice(), ESP32::SPIDevice::SPIDevice(), and SITL::JSBSim::start_JSBSim().
calloc()
void * calloc (size_t nmemb, size_t size)
Definition at line 408 of file malloc.c.
Referenced by __wrap__calloc_r(), __wrap__malloc_r(), __wrap_vasprintf(), Linux::OpticalFlow_Onboard::_run_optflow(), Linux::VideoIn::allocate_buffers(), AuxiliaryBus::AuxiliaryBus(), bouncebuffer_init(), ByteBuffer::ByteBuffer(), AP_ExpandingArrayGeneric::expand(), AP_GPS::handle_gps_rtcm_fragment(), AP_SmartRTL::init(), ekf_imu_buffer::init(), ekf_ring_buffer::init(), malloc(), ESP32::Util::malloc_type(), AP_HAL::Util::malloc_type(), Linux::Memory_table::Memory_table(), AP_Logger::msg_fmt_for_name(), operator new(), operator new[](), ByteBuffer::set_size(), AccelCalibrator::set_status(), and ESP32::Scheduler::thread_create().
free()
void free (void * ptr)
Definition at line 413 of file malloc.c.
Referenced by __wrap__free_r(), HALSITL::UARTDriver::_begin(), Linux::UARTDriver::_parseDevicePath(), Linux::OpticalFlow_Onboard::_run_optflow(), ChibiOS::Storage::_save_backup(), HALSITL::SITL_State::_set_param_default(), apfs_fclose(), apfs_fprintf(), apfs_freopen(), apfs_tmpfile(), base64_decode(), BM_Crop8bpp(), BM_YuyvToGrey(), bouncebuffer_setup_read(), bouncebuffer_setup_write(), MultiHeap::destroy(), emit_docs(), emit_docs_method(), error(), SITL::FlightAxis::exchange_data(), ESP32::Util::free_type(), AP_HAL::Util::free_type(), Linux::I2CDeviceManager::get_device(), Linux::Led_Sysfs::init(), Linux::PWM_Sysfs_Base::init(), AP_SmartRTL::init(), ekf_imu_buffer::init(), ekf_ring_buffer::init(), SITL::XPlane::load_dref_map(), AP_Filesystem_Backend::load_file(), HALSITL::SITL_State::lookup_location(), main(), AP_Logger::msg_fmt_for_name(), newbuffsize(), nmea_printf(), SITL::VectorNav::nmea_printf(), nmea_printf_buffer(), nmea_vaprintf(), Linux::RCInput_Navio2::open_channel(), operator delete(), operator delete[](), AP_GPS_SBF::parse(), HALSITL::SITL_State::parse_home(), realloc(), SITL::JSON_Master::send(), SITL::JSBSim::send_servos(), SITL::SilentWings::send_servos(), AP_Networking::sendfile_check(), SITL::SMBusDevice::set_block(), ExpandingString::set_buffer(), AnalogSource_Navio2::set_channel(), ByteBuffer::set_size(), AccelCalibrator::set_status(), SITL::FlightAxis::soap_request_start(), stackCheck(), ChibiOS::Scheduler::thread_create(), ESP32::Scheduler::thread_create(), HALSITL::Scheduler::thread_create(), ChibiOS::Scheduler::thread_create_trampoline(), ESP32::Scheduler::thread_create_trampoline(), HALSITL::Scheduler::thread_create_trampoline(), trace(), AP_Filesystem_Backend::unload_file(), AP_ExpandingArrayGeneric::~AP_ExpandingArrayGeneric(), AP_GPS_SBF::~AP_GPS_SBF(), AuxiliaryBus::~AuxiliaryBus(), ByteBuffer::~ByteBuffer(), ExpandingString::~ExpandingString(), ESP32::I2CDevice::~I2CDevice(), Linux::Memory_table::~Memory_table(), Linux::PWM_Sysfs_Base::~PWM_Sysfs_Base(), ChibiOS::SPIDevice::~SPIDevice(), and ESP32::SPIDevice::~SPIDevice().
malloc()
void * malloc (size_t size)
Definition at line 8 of file test_nmea_vaprint.cpp.
Referenced by SITL::InvensenseV3::add_block(), SITL::InvensenseV3::add_fifo(), allocate(), base64_decode(), base64_encode_global(), BM_Crop8bpp(), BM_YuyvToGrey(), calloc(), error(), AP_ROMFS::find_decompress(), AP_Filesystem_Backend::load_file(), FlashTest::loop(), AP_Logger::msg_fmt_for_name(), nmea_vaprintf(), realloc(), ChibiOS::DeviceBus::register_periodic_callback(), SITL::SMBusDevice::set_block(), ChibiOS::AnalogIn::setup_adc(), strdup(), ChibiOS::Scheduler::thread_create(), HALSITL::Scheduler::thread_create(), and trace().
malloc_check()
void malloc_check (const void * ptr)
Definition at line 350 of file malloc.c.
Referenced by ChibiOS::Scheduler::_monitor_thread().
printf()
int printf (const char * fmt, ...)
Referenced by AP_Compass_HMC5843::_calibrate(), AP_Compass_BMM150::_compensate_z(), AP_Compass_QMC5883L::_dump_registers(), ESP32::Storage::_flash_erase_ok(), ESP32::Storage::_flash_erase_sector(), ChibiOS::Storage::_flash_load(), ESP32::Storage::_flash_load(), ESP32::Storage::_flash_read_data(), ESP32::Storage::_flash_write(), ChibiOS::Storage::_flash_write_data(), ESP32::Storage::_flash_write_data(), Linux::UtilRPI::_get_board_type_using_peripheral_base(), AP_Compass_MAG3110::_hardware_init(), AP_Baro_KellerLD::_init(), AP_Baro_MS56XX::_init(), AP_InertialSensor_RST::_init_accel(), AP_InertialSensor_RST::_init_gyro(), ESP32::Scheduler::_io_thread(), ESP32::Scheduler::_main_thread(), ESP32::Storage::_mark_dirty(), HALSITL::SITL_State::_parse_command_line(), ESP32::Scheduler::_run_io(), Linux::RCOutput_Bebop::_run_rcout(), ESP32::Scheduler::_run_timers(), HALSITL::SITL_State::_set_param_default(), Linux::VideoIn::_set_streaming(), ChibiOS::Storage::_storage_open(), ESP32::Storage::_storage_open(), ESP32::Scheduler::_storage_thread(), ESP32::Scheduler::_timer_thread(), ESP32::Scheduler::_uart_thread(), AP_InertialSensor_Backend::_update_sensor_rate(), _usage(), HALSITL::SITL_State::_usage(), ESP32::SPIDevice::acquire_bus(), Linux::RCInput::add_dsm_input(), Linux::RCInput::add_sbus_input(), SITL::AirSim::AirSim(), Linux::VideoIn::allocate_buffers(), ESP32::AnalogSource::AnalogSource(), ap_hook_accel_sample(), ap_hook_AHRS_update(), ap_hook_gyro_sample(), ap_hook_setup_complete(), ap_hook_setup_start(), AP_memory_guard_error(), SITL::BalanceBot::BalanceBot(), SITL::Blimp::Blimp(), AP_Logger_Flash_JEDEC::BufferToPage(), AP_Logger_W25N01GV::BufferToPage(), ESP32::DeviceBus::bus_thread(), AP_Logger_W25N01GV::Busy(), SplineCurve::calc_dt_speed_max(), SITL::Motor::calc_thrust(), AP_Airspeed_MS5525::calculate(), SCurve::calculate_path(), SCurve::calculate_track(), MAVLink_routing::check_and_forward(), check_efuse(), AP_RangeFinder_VL53L0X::check_id(), AP_RangeFinder_VL53L1X::check_id(), AP_HAL::Device::check_next_register(), check_result(), AP_Filesystem_ESP32::close(), AP_Filesystem_ESP32::closedir(), SITL::Morse::connect_sockets(), SITL::Webots::connect_sockets(), create_socket_server(), SITL::JSBSim::create_templates(), SCurve::debug(), SITL::XPlane::deselect_code(), ESP32::DeviceBus::DeviceBus(), AP_Filesystem_ESP32::disk_free(), AP_Filesystem_ESP32::disk_space(), doargs(), StorageManager::erase(), SITL::FlightAxis::exchange_data(), AP_Logger_Block::flash_test(), SITL::FlightAxis::FlightAxis(), AP_Filesystem_ESP32::fsync(), ESP32::SPIDeviceManager::get_device(), AP_Logger_Flash_JEDEC::getSectorCount(), AP_Logger_W25N01GV::getSectorCount(), MAVLink_routing::handle_heartbeat(), SITL::XPlane::handle_rref(), ESP32::Storage::healthy(), AP_Logger_Flash_JEDEC::InErase(), AP_Logger_W25N01GV::InErase(), AP_Compass_IST8308::init(), AP_Compass_IST8310::init(), AP_Compass_LIS3MDL::init(), AP_Compass_MMC3416::init(), AP_Compass_MMC5XX3::init(), AP_Compass_QMC5883L::init(), ESP32::SoftSigReaderInt::init(), ESP32::SoftSigReaderRMT::init(), Linux::Led_Sysfs::init(), AP_RangeFinder_VL53L0X::init(), ESP32::Scheduler::init(), Linux::GPIO_BBB::init(), Linux::RCInput_RCProtocol::init(), Linux::RCOutput_Disco::init(), SITL::JSON_Master::init(), AP_IRLock_I2C::init(), AP_Baro_FBM320::init(), AP_BoardConfig::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_Logger_W25N01GV::Init(), AP_Gripper_EPM::init_gripper(), initialize(), SITL::JSBSim::JSBSim(), SITL::JSON::JSON(), MAVLink_routing::learn_route(), SITL::XPlane::load_dref_map(), SITL::Frame::load_frame_params(), AP_JSON::load_json(), HALSITL::SITL_State::lookup_location(), loop(), SchedTest::loop(), FlashTest::loop(), AP_Filesystem_ESP32::lseek(), main(), Linux::RCInput_RPI::map_peripheral(), Linux::Memory_table::Memory_table(), AP_Filesystem_ESP32::mkdir(), SITL::Morse::Morse(), mount_sdcard(), HALSITL::SITL_State::multicast_state_open(), SITL::MultiCopter::MultiCopter(), TCPServerDevice::open(), AP_Filesystem_ESP32::open(), SITL::JSBSim::open_control_socket(), AP_Filesystem_ESP32::opendir(), SITL::AirSim::output_copter(), SITL::AirSim::output_rover(), SITL::JSON::output_servos(), SITL::JEDEC::page_erase(), AP_Logger_Flash_JEDEC::PageToBuffer(), AP_Logger_W25N01GV::PageToBuffer(), parse_controls(), HALSITL::SITL_State::parse_home(), AP_Param::parse_param_line(), SITL::FlightAxis::parse_reply(), SITL::AirSim::parse_sensors(), SITL::JSON::parse_sensors(), SITL::Morse::parse_sensors(), SITL::Webots::parse_sensors(), ESP32::Scheduler::print_stats(), PrintCode(), PrintConstant(), PrintDebug(), PrintHeader(), PrintString(), process_keyboard(), SITL::SilentWings::process_packet(), SITL::GPS_FILE::publish(), SITL::QuadPlane::QuadPlane(), AP_Filesystem_ESP32::read(), ESP32::Storage::read_block(), AP_IRLock_I2C::read_frames(), AP_Baro_KellerLD::read_mode_type(), Linux::RCOutput_Bebop::read_obs_data(), AP_Airspeed_MS5525::read_prom(), AP_Filesystem_ESP32::readdir(), AP_Logger_Block::ReadHeaders(), ESP32::Scheduler::reboot(), SITL::JSON_Master::receive(), SITL::XPlane::receive_data(), SITL::AirSim::recv_fdm(), SITL::JSON::recv_fdm(), ESP32::Scheduler::register_io_process(), ESP32::SPIDevice::register_periodic_callback(), ESP32::DeviceBus::register_periodic_callback(), ESP32::Scheduler::register_timer_process(), AP_Filesystem_ESP32::rename(), SITL::Morse::report_FPS(), SITL::AirSim::report_FPS(), SITL::FlightAxis::report_FPS(), run(), HAL_Linux::run(), AP_OpticalFlow_PX4Flow::scan_buses(), sdcard_init(), SITL::XPlane::select_data(), SITL::XPlane::send_dref(), SITL::ADSB::send_report(), SITL::Gimbal::send_report(), SITL::Morse::send_report(), SITL::ShipSim::send_report(), SITL::EFI_MegaSquirt::send_table(), GCS_Dummy::send_textv(), MAVLink_routing::send_to_components(), AP_HAL::Device::set_checked_register(), SCurve::set_destination_speed_max(), SITL::AirSim::set_interface_ports(), SITL::Gazebo::set_interface_ports(), SITL::JSON::set_interface_ports(), SITL::Scrimmage::set_interface_ports(), SITL::SilentWings::set_interface_ports(), SITL::WebotsPython::set_interface_ports(), AP_Filesystem_ESP32::set_mtime(), set_object_value_and_report(), SCurve::set_origin_speed_max(), ESP32::AnalogSource::set_pin(), ESP32::SPIDevice::set_speed(), SCurve::set_speed_max(), ESP32::Scheduler::set_system_initialized(), setup(), setup(), setup(), setup(), BinarySemTest::setup(), show_matrix(), show_stack_usage(), sig_alrm(), SITL::SimRover::SimRover(), sitl_flash_erasepage(), SITL::FlightAxis::soap_request_end(), socket_accept(), SITL::FlightAxis::socket_creator(), ESP32::SoftSigReaderInt::SoftSigReaderInt(), ESP32::SPIBus::SPIBus(), ESP32::SPIDevice::SPIDevice(), srxl_channels_get_v5(), AP_Logger_Flash_JEDEC::StartErase(), AP_Logger_W25N01GV::StartErase(), AP_Filesystem_ESP32::stat(), sumd_decode(), TEST(), TEST(), TEST(), TEST(), test_matrix_inverse(), PrescalerParameterizedTestFixture::test_prescaler(), PrescalerParameterizedTestFixture::test_prescaler_neopixel(), test_xplane(), ESP32::Scheduler::thread_create(), AP_Compass_IST8308::timer(), AP_Compass_MMC3416::timer(), AP_Compass_MMC5XX3::timer(), AP_Compass_QMC5883L::timer(), ESP32::I2CDevice::transfer(), ESP32::SPIDevice::transfer(), ESP32::SPIDevice::transfer_fullduplex(), type_size(), AP_Filesystem_ESP32::unlink(), SITL::EFI_MegaSquirt::update(), BinarySemTest::update(), SITL::Sprayer::update(), SITL::Balloon::update(), SITL::FlightAxis::update(), SITL::JSON::update(), SITL::SilentWings::update(), SITL::Tracker::update(), SITL::Webots::update(), SITL::XPlane::update(), SITL::ShipSim::update(), update_controls(), SITL::Vicon::update_vicon_position_estimate(), AP_Logger_Flash_JEDEC::WaitReady(), AP_Logger_W25N01GV::WaitReady(), SITL::Webots::Webots(), SITL::WebotsPython::WebotsPython(), AP_Filesystem_ESP32::write(), FlashTest::write(), ESP32::Storage::write_block(), SITL::XPlane::XPlane(), and TimeCheck::~TimeCheck().
realloc()
void * realloc (void * ptr, size_t size)
Definition at line 14 of file test_expandingstring_failure.cpp.
Referenced by myrealloc(), SITL::AirSim::parse_sensors(), SITL::Morse::parse_sensors(), and SITL::Webots::parse_sensors().
snprintf()
int snprintf (char * str, size_t size, const char * fmt, ...)
Referenced by Linux::GPIO_Sysfs::_export_pin(), Linux::GPIO_Sysfs::_open_pin_value(), _parse(), Linux::GPIO_Sysfs::_pinMode(), ChibiOS::Storage::_save_backup(), AP_BoardConfig::allocation_error(), SITL::RF_Wasp::check_configuration(), check_result(), Compass::configured(), AP_Mount::convert_params(), failed(), AP_InertialSensor_Invensense::get_output_banner(), AP_InertialSensor_Invensensev2::get_output_banner(), AP_InertialSensor_Invensensev3::get_output_banner(), HALSITL::Util::get_system_id(), AP_RCTelemetry::init(), SITL::Frame::load_frame_params(), loop(), Linux::SPIBus::open(), Linux::I2CBus::open(), SITL::Morse::output_pwm(), SITL::Webots::output_pwm(), SITL::Morse::output_quad(), SITL::Webots::output_rover(), SITL::Morse::output_rover_regular(), SITL::Morse::output_rover_skid(), SITL::Webots::output_tricopter(), SITL::RF_LightWareSerial::packet_for_alt(), SITL::RF_MaxsonarSerialLV::packet_for_alt(), SITL::RF_NMEA::packet_for_alt(), SITL::RF_Wasp::packet_for_alt(), SITL::RF_NMEA::packet_for_temperature(), Linux::I2CDevice::register_periodic_callback(), Linux::SPIDevice::register_periodic_callback(), ChibiOS::DeviceBus::register_periodic_callback(), ESP32::DeviceBus::register_periodic_callback(), AP_HAL::run_command_on_ownpid(), AP_Hott_Telem::send_Vario(), TEST(), AP_JSON::value::to_str(), AP_InertialSensor_Invensense::update(), SITL::ADSB_Vehicle::update(), AP_MSP_Telem_Backend::update_flight_mode_str(), AP_MSP_Telem_DJI::update_flight_mode_str(), Display::update_mode(), Display::update_text(), and write_file().
vasprintf()
int vasprintf (char ** strp, const char * fmt, va_list ap)
Referenced by __wrap_asprintf(), apfs_fprintf(), and SITL::FlightAxis::soap_request_start().
vprintf()
int vprintf (const char * fmt, va_list arg)
Referenced by AP_HAL::panic(), GCS_Dummy::send_textv(), and AP_BoardConfig::throw_error().
vsnprintf()
int vsnprintf (char * str, size_t size, const char * fmt, va_list ap)
Referenced by __wrap_vasprintf().
Variable Documentation
vprintf_console_hook
int(* vprintf_console_hook) (const char *fmt, va_list arg) (const char * fmt, va_list arg) extern
Definition at line 104 of file stdio.cpp.
Referenced by __wrap_fprintf(), __wrap_printf(), and ChibiOS::UARTDriver::_begin().