APM:Libraries: libraries/AP_HAL_ChibiOS/stdio.cpp File Reference
stdio.cpp File Reference
#include <string.h>
#include <hal.h>
#include <chprintf.h>
#include <ctype.h>
#include "hwdef/common/stdio.h"
#include <AP_HAL/AP_HAL.h>
#include <AP_HAL_ChibiOS/hwdef/common/usbcfg.h>
#include "UARTDriver.h"
Functions
int __wrap_snprintf (char *str, size_t size, const char *fmt,...)
int __wrap_vsnprintf (char *str, size_t size, const char *fmt, va_list ap)
int __wrap_vasprintf (char **strp, const char *fmt, va_list ap)
int __wrap_asprintf (char **strp, const char *fmt,...)
int __wrap_vprintf (const char *fmt, va_list arg)
int __wrap_printf (const char *fmt,...)
int __wrap_fprintf (void *f, const char *fmt,...)
int __wrap_scanf (const char *fmt,...)
int __wrap_fiprintf (const char *fmt,...)
Variables
const AP_HAL::HAL & hal
int(* vprintf_console_hook)(const char *fmt, va_list arg) = vprintf
Function Documentation
__wrap_asprintf()
int __wrap_asprintf (char ** strp, const char * fmt, ...)
Definition at line 81 of file stdio.cpp.
__wrap_fiprintf()
int __wrap_fiprintf (const char * fmt, ...)
Definition at line 154 of file stdio.cpp.
__wrap_fprintf()
int __wrap_fprintf (void * f, const char * fmt, ...)
Definition at line 127 of file stdio.cpp.
__wrap_printf()
int __wrap_printf (const char * fmt, ...)
Definition at line 106 of file stdio.cpp.
__wrap_scanf()
int __wrap_scanf (const char * fmt, ...)
Definition at line 145 of file stdio.cpp.
__wrap_snprintf()
int __wrap_snprintf (char * str, size_t size, const char * fmt, ...)
Definition at line 41 of file stdio.cpp.
__wrap_vasprintf()
int __wrap_vasprintf (char ** strp, const char * fmt, va_list ap)
Definition at line 66 of file stdio.cpp.
__wrap_vprintf()
int __wrap_vprintf (const char * fmt, va_list arg)
Definition at line 90 of file stdio.cpp.
__wrap_vsnprintf()
int __wrap_vsnprintf (char * str, size_t size, const char * fmt, va_list ap)
Definition at line 57 of file stdio.cpp.
Variable Documentation
hal
const AP_HAL::HAL& hal extern
This file test realloc failure on ExpandingString
Definition at line 21 of file AC_PID_test.cpp.
Referenced by __wrap_snprintf(), and __wrap_vsnprintf().
vprintf_console_hook
int(* vprintf_console_hook) (const char *fmt, va_list arg) (const char * fmt, va_list arg) = vprintf
Definition at line 104 of file stdio.cpp.
Referenced by __wrap_fprintf(), __wrap_printf(), and ChibiOS::UARTDriver::_begin().