APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.h File Reference
stm32_util.h File Reference
#include "hal.h"
Classes
struct memory_region
Macros
#define AP_WATCHDOG_SAVE_FAULT_ENABLED 1
#define AP_FASTBOOT_ENABLED 1
Enumerations
enum rtc_boot_magic {
RTC_BOOT_OFF = 0 , RTC_BOOT_HOLD = 0xb0070001 , RTC_BOOT_FAST = 0xb0070002 , RTC_BOOT_CANBL = 0xb0080000 ,
RTC_BOOT_FWOK = 0xb0093a26
}
enum FaultType {
Reset = 1 , NMI = 2 , HardFault = 3 , MemManage = 4 ,
BusFault = 5 , UsageFault = 6
}
Functions
void stm32_timer_set_input_filter (stm32_tim_t *tim, uint8_t channel, uint8_t filter_mode)
void stm32_timer_set_channel_input (stm32_tim_t *tim, uint8_t channel, uint8_t input_source)
void show_stack_usage (void)
size_t mem_available (void)
void * malloc_dma (size_t size)
void * malloc_axi_sram (size_t size)
void * malloc_fastmem (size_t size)
void * malloc_eth_safe (size_t size)
thread_t * thread_create_alloc (size_t size, const char *name, tprio_t prio, tfunc_t pf, void *arg)
bool mem_is_dma_safe (const void *addr, uint32_t size, bool filesystem_op)
uint8_t malloc_get_heaps (memory_heap_t **_heaps, const struct memory_region **regions)
void memory_flush_all (void)
void stm32_set_utc_usec (uint64_t time_utc_usec)
uint64_t stm32_get_utc_usec (void)
uint32_t get_fattime (void)
bool check_limit_flash_1M (void)
enum rtc_boot_magic check_fast_reboot (void)
void set_fast_reboot (enum rtc_boot_magic v)
void peripheral_power_enable (void)
void malloc_init (void)
void set_rtc_backup (uint8_t idx, const uint32_t *v, uint8_t n)
void get_rtc_backup (uint8_t idx, uint32_t *v, uint8_t n)
void stm32_cacheBufferInvalidate (const void *p, size_t size)
void stm32_cacheBufferFlush (const void *p, size_t size)
void system_halt_hook (void)
void stack_overflow (thread_t *tp)
uint32_t stack_free (void *stack_base)
bool is_address_in_memory (void *addr)
void * get_addr_mem_region_start_addr (void *addr)
void * get_addr_mem_region_end_addr (void *addr)
uint32_t stm32_crash_dump_size (void)
uint32_t stm32_crash_dump_addr (void)
uint32_t stm32_crash_dump_max_size (void)
void save_fault_watchdog (uint16_t line, FaultType fault_type, uint32_t fault_addr, uint32_t lr)
uint32_t chibios_rand_generate (void)
void stm32_flash_protect_flash (bool bootloader, bool protect)
write protect the main flash or bootloader sectors
void stm32_flash_unprotect_flash (void)
Variables
stkalign_t __main_stack_base__
stkalign_t __main_stack_end__
stkalign_t __main_thread_stack_base__
stkalign_t __main_thread_stack_end__
Macro Definition Documentation
AP_FASTBOOT_ENABLED
#define AP_FASTBOOT_ENABLED 1
Definition at line 24 of file stm32_util.h.
AP_WATCHDOG_SAVE_FAULT_ENABLED
#define AP_WATCHDOG_SAVE_FAULT_ENABLED 1
Definition at line 20 of file stm32_util.h.
Enumeration Type Documentation
FaultType
enum FaultType
Enumerator
Reset
NMI
HardFault
MemManage
BusFault
UsageFault
Definition at line 159 of file stm32_util.h.
rtc_boot_magic
enum rtc_boot_magic
Enumerator
RTC_BOOT_OFF
RTC_BOOT_HOLD
RTC_BOOT_FAST
RTC_BOOT_CANBL
RTC_BOOT_FWOK
Definition at line 84 of file stm32_util.h.
Function Documentation
check_fast_reboot()
enum rtc_boot_magic check_fast_reboot (void)
Definition at line 259 of file stm32_util.c.
Referenced by set_fast_reboot().
check_limit_flash_1M()
bool check_limit_flash_1M (void)
Referenced by AP_Vehicle::one_Hz_update().
chibios_rand_generate()
uint32_t chibios_rand_generate (void) extern
Generates a block of random values, returns total values generated if nonblocking, for blocking returns if successful or not
Definition at line 313 of file system.cpp.
get_addr_mem_region_end_addr()
void * get_addr_mem_region_end_addr (void * addr)
Definition at line 554 of file malloc.c.
Referenced by CrashCatcher_DumpStartFlash().
get_addr_mem_region_start_addr()
void * get_addr_mem_region_start_addr (void * addr)
Definition at line 539 of file malloc.c.
Referenced by CrashCatcher_DumpStartFlash().
get_fattime()
uint32_t get_fattime (void)
Definition at line 188 of file stm32_util.c.
get_rtc_backup()
void get_rtc_backup (uint8_t idx, uint32_t * v, uint8_t n)
Definition at line 215 of file stm32_util.c.
Referenced by check_fast_reboot(), and stm32_watchdog_load().
is_address_in_memory()
bool is_address_in_memory (void * addr)
Definition at line 524 of file malloc.c.
Referenced by CrashCatcher_DumpStartFlash(), and CrashCatcher_GetMemoryRegions().
malloc_axi_sram()
void * malloc_axi_sram (size_t size)
Definition at line 378 of file malloc.c.
Referenced by bouncebuffer_init(), bouncebuffer_setup_read(), bouncebuffer_setup_write(), ESP32::Util::malloc_type(), and sdcard_init().
malloc_dma()
void * malloc_dma (size_t size)
Definition at line 369 of file malloc.c.
Referenced by ChibiOS::SPIDevice::acquire_bus(), bouncebuffer_init(), bouncebuffer_setup_read(), bouncebuffer_setup_write(), malloc_init(), and ESP32::Util::malloc_type().
malloc_eth_safe()
void * malloc_eth_safe (size_t size)
Definition at line 390 of file malloc.c.
malloc_fastmem()
void * malloc_fastmem (size_t size)
Definition at line 403 of file malloc.c.
Referenced by ESP32::Util::malloc_type().
malloc_get_heaps()
uint8_t malloc_get_heaps (memory_heap_t ** _heaps, const struct memory_region ** regions)
Definition at line 485 of file malloc.c.
Referenced by ChibiOS::Util::mem_info().
malloc_init()
void malloc_init (void)
Definition at line 77 of file malloc.c.
Referenced by __late_init().
mem_available()
size_t mem_available (void)
Definition at line 427 of file malloc.c.
mem_is_dma_safe()
bool mem_is_dma_safe (const void * addr, uint32_t size, bool filesystem_op)
Definition at line 623 of file malloc.c.
Referenced by bouncebuffer_setup_read(), and bouncebuffer_setup_write().
memory_flush_all()
void memory_flush_all (void)
Definition at line 498 of file malloc.c.
peripheral_power_enable()
void peripheral_power_enable (void)
Definition at line 299 of file stm32_util.c.
Referenced by main_loop().
save_fault_watchdog()
void save_fault_watchdog (uint16_t line, FaultType fault_type, uint32_t fault_addr, uint32_t lr)
Definition at line 257 of file system.cpp.
Referenced by CrashCatcher_DumpStart(), HardFault_Handler(), MemManage_Handler(), and UsageFault_Handler().
set_fast_reboot()
void set_fast_reboot (enum rtc_boot_magic v)
Definition at line 267 of file stm32_util.c.
Referenced by ChibiOS::Scheduler::reboot().
set_rtc_backup()
void set_rtc_backup (uint8_t idx, const uint32_t * v, uint8_t n)
Definition at line 231 of file stm32_util.c.
Referenced by set_fast_reboot(), and stm32_watchdog_save().
show_stack_usage()
void show_stack_usage (void)
Definition at line 80 of file stm32_util.c.
stack_free()
uint32_t stack_free (void * stack_base)
Definition at line 487 of file stm32_util.c.
Referenced by ChibiOS::Scheduler::check_stack_free(), ChibiOS::Util::log_stack_info(), and ESP32::Util::thread_info().
stack_overflow()
void stack_overflow (thread_t * tp)
Definition at line 468 of file stm32_util.c.
stm32_cacheBufferFlush()
void stm32_cacheBufferFlush (const void * p, size_t size)
Definition at line 392 of file stm32_util.c.
Referenced by bouncebuffer_setup_write(), memory_flush_all(), ChibiOS::RCOutput::send_pulses_DMAR(), and ChibiOS::UARTDriver::write_pending_bytes_DMA().
stm32_cacheBufferInvalidate()
void stm32_cacheBufferInvalidate (const void * p, size_t size)
Definition at line 387 of file stm32_util.c.
Referenced by ChibiOS::SoftSigReader::_irq_handler(), ChibiOS::AnalogIn::adccallback(), bouncebuffer_setup_read(), ChibiOS::UARTDriver::dma_rx_enable(), and stm32_flash_erasepage().
stm32_crash_dump_addr()
uint32_t stm32_crash_dump_addr (void)
Definition at line 74 of file crashdump.c.
Referenced by CrashCatcher_DumpEndFlash(), flush_dump_buffer(), and stm32_crash_dump_region_erased().
stm32_crash_dump_max_size()
uint32_t stm32_crash_dump_max_size (void)
Definition at line 69 of file crashdump.c.
Referenced by CrashCatcher_DumpEndFlash(), CrashCatcher_DumpMemoryFlash(), CrashCatcher_GetMemoryRegions(), stm32_crash_dump_region_erased(), and stm32_crash_dump_size().
stm32_crash_dump_size()
uint32_t stm32_crash_dump_size (void)
Definition at line 62 of file crashdump.c.
stm32_flash_protect_flash()
void stm32_flash_protect_flash (bool bootloader, bool protect)
write protect the main flash or bootloader sectors
Definition at line 934 of file flash.c.
Referenced by main_loop().
stm32_flash_unprotect_flash()
void stm32_flash_unprotect_flash (void)
Definition at line 1007 of file flash.c.
Referenced by main_loop().
stm32_get_utc_usec()
uint64_t stm32_get_utc_usec (void)
Definition at line 112 of file stm32_util.c.
Referenced by get_fattime(), and HALSITL::Util::get_hw_rtc().
stm32_set_utc_usec()
void stm32_set_utc_usec (uint64_t time_utc_usec)
Definition at line 101 of file stm32_util.c.
stm32_timer_set_channel_input()
void stm32_timer_set_channel_input (stm32_tim_t * tim, uint8_t channel, uint8_t input_source)
Definition at line 49 of file stm32_util.c.
Referenced by ChibiOS::SoftSigReaderInt::init().
stm32_timer_set_input_filter()
void stm32_timer_set_input_filter (stm32_tim_t * tim, uint8_t channel, uint8_t filter_mode)
Definition at line 28 of file stm32_util.c.
Referenced by ChibiOS::SoftSigReader::attach_capture_timer(), and ChibiOS::SoftSigReaderInt::init().
system_halt_hook()
void system_halt_hook (void)
Definition at line 456 of file stm32_util.c.
thread_create_alloc()
thread_t * thread_create_alloc (size_t size, const char * name, tprio_t prio, tfunc_t pf, void * arg)
Definition at line 459 of file malloc.c.
Referenced by ChibiOS::DeviceBus::register_periodic_callback(), ChibiOS::Scheduler::thread_create(), ChibiOS::UARTDriver::thread_init(), and ChibiOS::UARTDriver::thread_rx_init().
Variable Documentation
__main_stack_base__
stkalign_t __main_stack_base__ extern
Referenced by ChibiOS::Scheduler::check_stack_free(), ChibiOS::Util::log_stack_info(), stackCheck(), and ESP32::Util::thread_info().
__main_stack_end__
stkalign_t __main_stack_end__ extern
Referenced by ChibiOS::Util::log_stack_info(), stackCheck(), and ESP32::Util::thread_info().
__main_thread_stack_base__
stkalign_t __main_thread_stack_base__ extern
Referenced by CrashCatcher_GetMemoryRegions(), ChibiOS::Util::log_stack_info(), stackCheck(), and ESP32::Util::thread_info().
__main_thread_stack_end__
stkalign_t __main_thread_stack_end__ extern
Referenced by CrashCatcher_GetMemoryRegions(), ChibiOS::Util::log_stack_info(), stackCheck(), and ESP32::Util::thread_info().