APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.c File Reference
stm32_util.c File Reference
#include "stm32_util.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stm32_dma.h>
#include <hrt.h>
Classes
struct utc_tm
Functions
void stm32_timer_set_input_filter (stm32_tim_t *tim, uint8_t channel, uint8_t filter_mode)
void stm32_timer_set_channel_input (stm32_tim_t *tim, uint8_t channel, uint8_t input_source)
void show_stack_usage (void)
void stm32_set_utc_usec (uint64_t time_utc_usec)
uint64_t stm32_get_utc_usec ()
static bool is_leap (uint32_t y)
static void parse_utc_seconds (uint64_t utc_sec, struct utc_tm *tm)
uint32_t get_fattime ()
void get_rtc_backup (uint8_t idx, uint32_t *v, uint8_t n)
void set_rtc_backup (uint8_t idx, const uint32_t *v, uint8_t n)
enum rtc_boot_magic check_fast_reboot (void)
void set_fast_reboot (enum rtc_boot_magic v)
void peripheral_power_enable (void)
void stm32_cacheBufferInvalidate (const void *p, size_t size)
void stm32_cacheBufferFlush (const void *p, size_t size)
void system_halt_hook (void)
void stack_overflow (thread_t *tp)
uint32_t stack_free (void *stack_base)
Variables
static int64_t utc_time_offset
static const uint8_t ndays [2][12]
Function Documentation
check_fast_reboot()
enum rtc_boot_magic check_fast_reboot (void)
Definition at line 259 of file stm32_util.c.
Referenced by set_fast_reboot().
get_fattime()
uint32_t get_fattime (void)
Definition at line 188 of file stm32_util.c.
get_rtc_backup()
void get_rtc_backup (uint8_t idx, uint32_t * v, uint8_t n)
Definition at line 215 of file stm32_util.c.
Referenced by check_fast_reboot(), and stm32_watchdog_load().
is_leap()
static bool is_leap (uint32_t y) static
Definition at line 130 of file stm32_util.c.
Referenced by parse_utc_seconds().
parse_utc_seconds()
static void parse_utc_seconds (uint64_t utc_sec, struct utc_tm * tm) static
Definition at line 144 of file stm32_util.c.
Referenced by get_fattime().
peripheral_power_enable()
void peripheral_power_enable (void)
Definition at line 299 of file stm32_util.c.
Referenced by main_loop().
set_fast_reboot()
void set_fast_reboot (enum rtc_boot_magic v)
Definition at line 267 of file stm32_util.c.
Referenced by ChibiOS::Scheduler::reboot().
set_rtc_backup()
void set_rtc_backup (uint8_t idx, const uint32_t * v, uint8_t n)
Definition at line 231 of file stm32_util.c.
Referenced by set_fast_reboot(), and stm32_watchdog_save().
show_stack_usage()
void show_stack_usage (void)
Definition at line 80 of file stm32_util.c.
stack_free()
uint32_t stack_free (void * stack_base)
Definition at line 487 of file stm32_util.c.
Referenced by ChibiOS::Scheduler::check_stack_free(), ChibiOS::Util::log_stack_info(), and ESP32::Util::thread_info().
stack_overflow()
void stack_overflow (thread_t * tp)
Definition at line 468 of file stm32_util.c.
stm32_cacheBufferFlush()
void stm32_cacheBufferFlush (const void * p, size_t size)
Definition at line 392 of file stm32_util.c.
Referenced by bouncebuffer_setup_write(), memory_flush_all(), ChibiOS::RCOutput::send_pulses_DMAR(), and ChibiOS::UARTDriver::write_pending_bytes_DMA().
stm32_cacheBufferInvalidate()
void stm32_cacheBufferInvalidate (const void * p, size_t size)
Definition at line 387 of file stm32_util.c.
Referenced by ChibiOS::SoftSigReader::_irq_handler(), ChibiOS::AnalogIn::adccallback(), bouncebuffer_setup_read(), ChibiOS::UARTDriver::dma_rx_enable(), and stm32_flash_erasepage().
stm32_get_utc_usec()
uint64_t stm32_get_utc_usec (void)
Definition at line 112 of file stm32_util.c.
Referenced by get_fattime(), and HALSITL::Util::get_hw_rtc().
stm32_set_utc_usec()
void stm32_set_utc_usec (uint64_t time_utc_usec)
Definition at line 101 of file stm32_util.c.
stm32_timer_set_channel_input()
void stm32_timer_set_channel_input (stm32_tim_t * tim, uint8_t channel, uint8_t input_source)
Definition at line 49 of file stm32_util.c.
Referenced by ChibiOS::SoftSigReaderInt::init().
stm32_timer_set_input_filter()
void stm32_timer_set_input_filter (stm32_tim_t * tim, uint8_t channel, uint8_t filter_mode)
Definition at line 28 of file stm32_util.c.
Referenced by ChibiOS::SoftSigReader::attach_capture_timer(), and ChibiOS::SoftSigReaderInt::init().
system_halt_hook()
void system_halt_hook (void)
Definition at line 456 of file stm32_util.c.
Variable Documentation
ndays
const uint8_t ndays[2][12] static
Initial value:
={
    {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31},
    {31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}}
Definition at line 136 of file stm32_util.c.
Referenced by AP_RTC::_timegm(), and parse_utc_seconds().
utc_time_offset
int64_t utc_time_offset static
Definition at line 23 of file stm32_util.c.
Referenced by get_fattime(), stm32_get_utc_usec(), and stm32_set_utc_usec().