APM:Libraries: AP_HAL::HAL::FunCallbacks Struct Reference
AP_HAL::HAL::FunCallbacks Struct Reference
#include <HAL.h>
Public Member Functions
FunCallbacks (void(*setup_fun)(void), void(*loop_fun)(void))
void setup () override
void loop () override
Private Attributes
void(* _setup)(void)
void(* _loop)(void)
Detailed Description
Definition at line 107 of file HAL.h.
Constructor & Destructor Documentation
FunCallbacks()
AP_HAL::HAL::FunCallbacks::FunCallbacks (void(*)(void) setup_fun, void(*)(void) loop_fun)
Definition at line 7 of file HAL.cpp.
Member Function Documentation
loop()
void AP_HAL::HAL::FunCallbacks::loop (void) inline override virtual
Implements AP_HAL::HAL::Callbacks.
Definition at line 111 of file HAL.h.
Referenced by HAL_Empty::run(), HAL_Linux::run(), and HAL_SITL::run().
setup()
void AP_HAL::HAL::FunCallbacks::setup (void) inline override virtual
Implements AP_HAL::HAL::Callbacks.
Definition at line 110 of file HAL.h.
Referenced by HAL_Empty::run(), HAL_Linux::run(), and HAL_SITL::run().
Member Data Documentation
_loop
void(* AP_HAL::HAL::FunCallbacks::_loop) (void) private
Definition at line 115 of file HAL.h.
Referenced by loop().
_setup
void(* AP_HAL::HAL::FunCallbacks::_setup) (void) private
Definition at line 114 of file HAL.h.
Referenced by setup().
The documentation for this struct was generated from the following files:
libraries/AP_HAL/HAL.h
libraries/AP_HAL/HAL.cpp