APM:Libraries: Vector2< T > Class Template Reference
Vector2< T > Class Template Reference
#include <vector2.h>
Public Member Functions
constexpr Vector2 ()
constexpr Vector2 (const T x0, const T y0)
bool operator== (const Vector2< T > &v) const
bool operator!= (const Vector2< T > &v) const
Vector2< T > operator- (void) const
Vector2< T > operator+ (const Vector2< T > &v) const
Vector2< T > operator- (const Vector2< T > &v) const
Vector2< T > operator* (const T num) const
Vector2< T > operator/ (const T num) const
Vector2< T > & operator+= (const Vector2< T > &v)
Vector2< T > & operator-= (const Vector2< T > &v)
Vector2< T > & operator*= (const T num)
Vector2< T > & operator/= (const T num)
T operator* (const Vector2< T > &v) const
T dot (const Vector2< T > &v) const
T operator% (const Vector2< T > &v) const
T angle (const Vector2< T > &v2) const
T angle (void) const
bool is_nan (void) const WARN_IF_UNUSED
bool is_inf (void) const WARN_IF_UNUSED
bool is_zero (void) const WARN_IF_UNUSED
T & operator[] (uint8_t i)
const T & operator[] (uint8_t i) const
void zero ()
T length_squared () const
T length (void) const
bool limit_length (T max_length)
void normalize ()
Vector2< T > normalized () const
void reflect (const Vector2< T > &n)
void project (const Vector2< T > &v)
Vector2< T > projected (const Vector2< T > &v) const
void offset_bearing (T bearing, T distance)
void rotate (T angle_rad)
Vector2< float > tofloat () const
Vector2< double > todouble () const
bool is_zero (void) const
Static Public Member Functions
static Vector2< T > perpendicular (const Vector2< T > &pos_delta, const Vector2< T > &v1)
static Vector2< T > closest_point (const Vector2< T > &p, const Vector2< T > &v, const Vector2< T > &w)
static Vector2< T > closest_point (const Vector2< T > &p, const Vector2< T > &w)
static T closest_distance_between_line_and_point_squared (const Vector2< T > &w1, const Vector2< T > &w2, const Vector2< T > &p)
static T closest_distance_between_line_and_point (const Vector2< T > &w1, const Vector2< T > &w2, const Vector2< T > &p)
static T closest_distance_between_lines_squared (const Vector2< T > &a1, const Vector2< T > &a2, const Vector2< T > &b1, const Vector2< T > &b2)
static T closest_distance_between_radial_and_point_squared (const Vector2< T > &w, const Vector2< T > &p)
static T closest_distance_between_radial_and_point (const Vector2< T > &w, const Vector2< T > &p)
static bool segment_intersection (const Vector2< T > &seg1_start, const Vector2< T > &seg1_end, const Vector2< T > &seg2_start, const Vector2< T > &seg2_end, Vector2< T > &intersection) WARN_IF_UNUSED
static bool circle_segment_intersection (const Vector2< T > &seg_start, const Vector2< T > &seg_end, const Vector2< T > &circle_center, T radius, Vector2< T > &intersection) WARN_IF_UNUSED
static bool point_on_segment (const Vector2< T > &point, const Vector2< T > &seg_start, const Vector2< T > &seg_end) WARN_IF_UNUSED
Public Attributes
T x
T y
Detailed Description
template<typename T>
class Vector2< T >
Definition at line 42 of file vector2.h.
Constructor & Destructor Documentation
Vector2() [1/2]
template<typename T > constexpr Vector2< T >::Vector2 () inline constexpr
Definition at line 47 of file vector2.h.
Vector2() [2/2]
template<typename T > constexpr Vector2< T >::Vector2 (const T x0, const T y0) inline constexpr
Definition at line 52 of file vector2.h.
Member Function Documentation
angle() [1/2]
template<typename T > T Vector2< T >::angle (const Vector2< T > & v2) const
Definition at line 145 of file vector2.cpp.
Referenced by AP_GPS_Backend::calculate_moving_base_yaw(), AC_PosControl::calculate_yaw_and_rate_yaw(), Compass::consistent(), AP_OABendyRuler::update(), and AP_L1_Control::update_waypoint().
angle() [2/2]
template<typename T > T Vector2< T >::angle (void) const
Definition at line 162 of file vector2.cpp.
circle_segment_intersection()
template<typename T > bool Vector2< T >::circle_segment_intersection (const Vector2< T > & seg_start, const Vector2< T > & seg_end, const Vector2< T > & circle_center, T radius, Vector2< T > & intersection) static
Definition at line 204 of file vector2.cpp.
closest_distance_between_line_and_point()
template<typename T > T Vector2< T >::closest_distance_between_line_and_point (const Vector2< T > & w1, const Vector2< T > & w2, const Vector2< T > & p) static
Definition at line 393 of file vector2.cpp.
closest_distance_between_line_and_point_squared()
template<typename T > T Vector2< T >::closest_distance_between_line_and_point_squared (const Vector2< T > & w1, const Vector2< T > & w2, const Vector2< T > & p) static
Definition at line 382 of file vector2.cpp.
Referenced by Vector2< T >::closest_distance_between_lines_squared().
closest_distance_between_lines_squared()
template<typename T > T Vector2< T >::closest_distance_between_lines_squared (const Vector2< T > & a1, const Vector2< T > & a2, const Vector2< T > & b1, const Vector2< T > & b2) static
Definition at line 404 of file vector2.cpp.
closest_distance_between_radial_and_point()
template<typename T > T Vector2< T >::closest_distance_between_radial_and_point (const Vector2< T > & w, const Vector2< T > & p) static
Definition at line 433 of file vector2.cpp.
closest_distance_between_radial_and_point_squared()
template<typename T > T Vector2< T >::closest_distance_between_radial_and_point_squared (const Vector2< T > & w, const Vector2< T > & p) static
Definition at line 422 of file vector2.cpp.
closest_point() [1/2]
template<typename T > Vector2< T > Vector2< T >::closest_point (const Vector2< T > & p, const Vector2< T > & v, const Vector2< T > & w) static
Definition at line 333 of file vector2.cpp.
closest_point() [2/2]
template<typename T > Vector2< T > Vector2< T >::closest_point (const Vector2< T > & p, const Vector2< T > & w) static
Definition at line 361 of file vector2.cpp.
dot()
template<typename T > T Vector2< T >::dot (const Vector2< T > & v) const inline
Definition at line 93 of file vector2.h.
Referenced by AR_WPNav::advance_wp_target_along_track().
is_inf()
template<typename T > bool Vector2< T >::is_inf (void) const
Definition at line 90 of file vector2.cpp.
Referenced by AP_AHRS::calc_trig(), and AC_PID_2D::update_all().
is_nan()
template<typename T > bool Vector2< T >::is_nan (void) const
Definition at line 84 of file vector2.cpp.
Referenced by AP_AHRS::calc_trig(), and AC_PID_2D::update_all().
is_zero() [1/2]
bool Vector2< double >::is_zero (void) const inline
Definition at line 289 of file vector2.h.
is_zero() [2/2]
template<typename T > bool Vector2< T >::is_zero (void) const inline
Definition at line 115 of file vector2.h.
Referenced by AC_Avoid::adjust_velocity_polygon(), AC_Avoid::adjust_velocity_proximity(), AC_Avoid::calc_backup_velocity_2D(), AC_Loiter::calc_desired_velocity(), SoaringController::check_drift(), Compass::consistent(), AC_Avoid::find_max_quadrant_velocity(), AP_Beacon::get_next_boundary_point(), limit_accel_xy(), Vector2< T >::point_on_segment(), shape_vel_accel_xy(), TEST(), AR_PosControl::update(), and update_vel_accel_xy().
length()
template<typename T > T Vector2< T >::length (void) const
Definition at line 30 of file vector2.cpp.
Referenced by AP_AHRS::_groundspeed(), AC_Avoid::adjust_roll_pitch(), AC_Avoid::adjust_velocity_polygon(), AC_Avoid::adjust_velocity_proximity(), SCurve::advance_target_along_track(), AR_WPNav::advance_wp_target_along_track(), NavEKF2_core::alignMagStateDeclination(), NavEKF3_core::alignMagStateDeclination(), AC_AttitudeControl::ang_vel_limit(), AP_GPS::calc_blended_state(), AR_WPNav::calc_crosstrack_error(), AC_Loiter::calc_desired_velocity(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AC_PosControl::calculate_yaw_and_rate_yaw(), SoaringController::check_drift(), NavEKF2_core::correctEkfOriginHeight(), NavEKF3_core::correctEkfOriginHeight(), AC_PosControl::crosstrack_error(), AC_Circle::get_closest_point_on_circle(), AC_PI_2D::get_i(), AC_PI_2D::get_i_shrink(), AP_InertialNav::get_speed_xy_cms(), AR_WPNav::get_stopping_location(), AC_PosControl::get_stopping_point_xy_cm(), AP_AHRS_Backend::groundspeed(), AP_AHRS::head_wind(), AC_PosControl::input_pos_xyz(), Vector2< int32_t >::length(), AC_Avoid::limit_velocity_3D(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), AP_OADatabase::queue_push(), NavEKF3_core::realignYawGPS(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), AP_Hott_Telem::send_GPS(), sqrt_controller(), AC_Sprayer::update(), AR_PosControl::update(), AP_WindVane::update_apparent_wind_dir_from_true(), AP_L1_Control::update_heading_hold(), AC_PID_2D::update_i(), AP_L1_Control::update_loiter(), AP_WindVane::update_true_wind_speed_and_direction(), AP_L1_Control::update_waypoint(), NavEKF2_core::UpdateStrapdownEquationsNED(), NavEKF3_core::UpdateStrapdownEquationsNED(), AP_GPS_Backend::velocity_to_speed_course(), NavEKF2_core::writeOptFlowMeas(), and NavEKF3_core::writeOptFlowMeas().
length_squared()
template<typename T > T Vector2< T >::length_squared () const
Definition at line 24 of file vector2.cpp.
Referenced by AP_OABendyRuler::calc_margin_from_circular_fence(), Vector2< T >::closest_point(), AC_PosControl::crosstrack_error(), AC_WeatherVane::get_yaw_out(), limit_accel_xy(), NavEKF3_core::realignYawGPS(), shape_vel_accel_xy(), AP_OABendyRuler::update(), update_pos_vel_accel_xy(), and AR_WPNav::update_psc_input_shaping().
limit_length()
template<typename T > bool Vector2< T >::limit_length (T max_length)
Definition at line 37 of file vector2.cpp.
Referenced by AC_PosControl::init_xy_controller(), limit_accel_xy(), rc_input_to_roll_pitch(), AC_PID_2D::set_integrator(), shape_accel_xy(), shape_pos_vel_accel_xy(), shape_vel_accel_xy(), TEST(), AR_PosControl::update(), AC_P_2D::update_all(), and AC_PID_2D::update_i().
normalize()
template<typename T > void Vector2< T >::normalize ()
Definition at line 268 of file vector2.cpp.
Referenced by AC_Avoid::calc_backup_velocity_2D(), AR_WPNav::calc_crosstrack_error(), AP_AHRS::calc_trig(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), TEST(), and AP_L1_Control::update_waypoint().
normalized()
template<typename T > Vector2< T > Vector2< T >::normalized () const
Definition at line 275 of file vector2.cpp.
Referenced by AR_WPNav::advance_wp_target_along_track(), SoaringController::check_drift(), AC_PosControl::crosstrack_error(), AR_WPNav::get_stopping_location(), limit_accel_xy(), shape_vel_accel_xy(), and AP_L1_Control::update_loiter().
offset_bearing()
template<typename T > void Vector2< T >::offset_bearing (T bearing, T distance)
Definition at line 305 of file vector2.cpp.
Referenced by TEST().
operator!=()
template<typename T > template bool Vector2< T >::operator!= (const Vector2< T > & v) const
Definition at line 139 of file vector2.cpp.
operator%()
template<typename T > T Vector2< T >::operator% (const Vector2< T > & v) const
Definition at line 57 of file vector2.cpp.
operator*() [1/2]
template<typename T > Vector2< T > Vector2< T >::operator* (const T num) const
Definition at line 109 of file vector2.cpp.
operator*() [2/2]
template<typename T > T Vector2< T >::operator* (const Vector2< T > & v) const
Definition at line 50 of file vector2.cpp.
operator*=()
template<typename T > Vector2< T > & Vector2< T >::operator*= (const T num)
Definition at line 63 of file vector2.cpp.
operator+()
template<typename T > Vector2< T > Vector2< T >::operator+ (const Vector2< T > & v) const
Definition at line 121 of file vector2.cpp.
operator+=()
template<typename T > Vector2< T > & Vector2< T >::operator+= (const Vector2< T > & v)
Definition at line 96 of file vector2.cpp.
operator-() [1/2]
template<typename T > Vector2< T > Vector2< T >::operator- (const Vector2< T > & v) const
Definition at line 115 of file vector2.cpp.
operator-() [2/2]
template<typename T > Vector2< T > Vector2< T >::operator- (void) const
Definition at line 127 of file vector2.cpp.
operator-=()
template<typename T > Vector2< T > & Vector2< T >::operator-= (const Vector2< T > & v)
Definition at line 77 of file vector2.cpp.
operator/()
template<typename T > Vector2< T > Vector2< T >::operator/ (const T num) const
Definition at line 103 of file vector2.cpp.
operator/=()
template<typename T > Vector2< T > & Vector2< T >::operator/= (const T num)
Definition at line 70 of file vector2.cpp.
operator==()
template<typename T > template bool Vector2< T >::operator== (const Vector2< T > & v) const
Definition at line 133 of file vector2.cpp.
operator[]() [1/2]
template<typename T > T & Vector2< T >::operator[] (uint8_t i) inline
Definition at line 120 of file vector2.h.
operator[]() [2/2]
template<typename T > const T & Vector2< T >::operator[] (uint8_t i) const inline
Definition at line 128 of file vector2.h.
perpendicular()
template<typename T > Vector2< T > Vector2< T >::perpendicular (const Vector2< T > & pos_delta, const Vector2< T > & v1) static
Definition at line 314 of file vector2.cpp.
Referenced by TEST().
point_on_segment()
template<typename T > static bool Vector2< T >::point_on_segment (const Vector2< T > & point, const Vector2< T > & seg_start, const Vector2< T > & seg_end) inline static
Definition at line 244 of file vector2.h.
project()
template<typename T > void Vector2< T >::project (const Vector2< T > & v)
Definition at line 291 of file vector2.cpp.
Referenced by TEST().
projected()
template<typename T > Vector2< T > Vector2< T >::projected (const Vector2< T > & v) const
Definition at line 298 of file vector2.cpp.
Referenced by AR_PosControl::update().
reflect()
template<typename T > void Vector2< T >::reflect (const Vector2< T > & n)
Definition at line 282 of file vector2.cpp.
Referenced by TEST().
rotate()
template<typename T > void Vector2< T >::rotate (T angle_rad)
Definition at line 441 of file vector2.cpp.
Referenced by SITL::ShipSim::get_ground_speed_adjustment(), SITL::ShipSim::send_report(), TEST(), SITL::Ship::update(), and AP_Mount_Servo::update_angle_outputs().
segment_intersection()
template<typename T > bool Vector2< T >::segment_intersection (const Vector2< T > & seg1_start, const Vector2< T > & seg1_end, const Vector2< T > & seg2_start, const Vector2< T > & seg2_end, Vector2< T > & intersection) static
Definition at line 171 of file vector2.cpp.
todouble()
template<typename T > Vector2< double > Vector2< T >::todouble () const inline
Definition at line 178 of file vector2.h.
tofloat()
template<typename T > Vector2< float > Vector2< T >::tofloat () const inline
Definition at line 175 of file vector2.h.
Referenced by AR_WPNav::advance_wp_target_along_track(), AC_Loiter::get_stopping_point_xy(), AC_WPNav::get_wp_stopping_point_xy(), NavEKF2_core::getLastPosNorthEastReset(), NavEKF3_core::getLastPosNorthEastReset(), NavEKF2_core::getLastVelNorthEastReset(), NavEKF3_core::getLastVelNorthEastReset(), NavEKF3_core::getPosNE(), NavEKF2_core::getVariances(), and NavEKF3_core::getVariances().
zero()
template<typename T > void Vector2< T >::zero () inline
Definition at line 137 of file vector2.h.
Referenced by AC_Avoid::adjust_velocity_fence(), AC_Avoid::adjust_velocity_polygon(), AP_GPS::calc_blended_state(), AC_Loiter::clear_pilot_desired_acceleration(), AC_PrecLand::get_target_velocity_cms(), NavEKF2::getLastPosNorthEastReset(), NavEKF3::getLastPosNorthEastReset(), NavEKF3_core::getPosNE(), AR_PosControl::init(), AC_Loiter::init_target(), AC_PosControl::init_xy_controller(), AC_PosControl::init_xy_controller_stopping_point(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), AC_PI_2D::reset_I(), AC_PID_2D::reset_I(), NavEKF3_core::ResetVelocity(), NavEKF2_core::ResetVelocity(), NavEKF2_core::SelectFlowFusion(), NavEKF3_core::SelectFlowFusion(), TEST(), AR_PosControl::update(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_UPFLOW::update(), AC_PID_2D::update_all(), update_pos_vel_accel_xy(), update_vel_accel_xy(), AC_PosControl::update_xy_controller(), NavEKF2::updateLaneSwitchPosResetData(), and NavEKF3::updateLaneSwitchPosResetData().
Member Data Documentation
x
template<typename T > T Vector2< T >::x
Definition at line 44 of file vector2.h.
Referenced by Linux::OpticalFlow_Onboard::_run_optflow(), AP_OpticalFlow_Calibrator::add_sample(), AC_Avoid::adjust_roll_pitch(), AC_Avoid::adjust_speed(), AC_Avoid::adjust_velocity(), AC_Avoid::adjust_velocity_fence(), AC_Avoid::adjust_velocity_proximity(), AR_WPNav::advance_wp_target_along_track(), AC_AttitudeControl::ang_vel_limit(), AP_AHRS::body_to_earth2D(), AP_AHRS_View::body_to_earth2D(), AP_GPS::calc_blended_state(), AC_Loiter::calc_desired_velocity(), AC_Autorotation::calc_speed_forward(), AP_AHRS::calc_trig(), AC_PosControl::calculate_yaw_and_rate_yaw(), NavEKF2_core::CorrectGPSForAntennaOffset(), AC_AutoTune_Heli::dwell_test_run(), AP_AHRS::earth_to_body2D(), AP_AHRS_View::earth_to_body2D(), NavEKF2_core::EstimateTerrainOffset(), NavEKF3_core::EstimateTerrainOffset(), AC_Avoid::find_max_quadrant_velocity(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::FuseAirspeed(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), NavEKF2_core::FuseSideslip(), NavEKF3_core::FuseSideslip(), get_bearing_cd(), AC_Circle::get_closest_point_on_circle(), AC_PID_2D::get_ff(), SITL::ShipSim::get_ground_speed_adjustment(), AP_Beacon::get_next_boundary_point(), AC_Loiter::get_pilot_desired_acceleration(), AC_AutoTune::get_poshold_attitude(), AP_AHRS::get_relative_position_NED_origin(), AR_WPNav::get_stopping_location(), AC_PrecLand::get_target_position_cm(), AC_WPNav::get_vector_NEU(), NavEKF2_core::getAirSpdVec(), NavEKF3_core::getAirSpdVec(), NavEKF2_core::getLLH(), NavEKF3_core::getLLH(), NavEKF2_core::getPosNE(), NavEKF3_core::getPosNE(), NavEKF3_core::getSynthAirDataInnovations(), NavEKF2_core::getWind(), NavEKF3_core::getWind(), AR_PosControl::init(), AC_Loiter::init_target(), AC_Loiter::init_target(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), AC_AttitudeControl::input_shaping_rate_predictor(), Vector2< T >::is_zero(), Location::line_path_proportion(), location_from_point(), Vector2< int32_t >::operator+=(), Vector2< T >::operator[](), Vector2< T >::operator[](), Vector2< T >::point_on_segment(), Polygon_closest_distance_line(), Polygon_intersects(), Polygon_outside(), Linux::OpticalFlow_Onboard::push_gyro(), Linux::OpticalFlow_Onboard::push_gyro_bias(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), rc_input_to_roll_pitch(), NavEKF3_core::ResetPosition(), NavEKF2_core::ResetPosition(), NavEKF2_core::ResetPositionNE(), NavEKF3_core::ResetPositionNE(), NavEKF3_core::ResetVelocity(), NavEKF2_core::ResetVelocity(), AC_PrecLand::run_estimator(), AC_PrecLand::run_output_prediction(), NavEKF2_core::SelectVelPosFusion(), NavEKF3_core::SelectVelPosFusion(), AP_Hott_Telem::send_GPS(), SITL::ShipSim::send_report(), AC_Circle::set_center(), AR_WPNav::set_desired_location(), AC_PI_2D::set_integrator(), AC_Loiter::set_pilot_desired_acceleration(), NavEKF2_core::setAidingMode(), NavEKF3_core::setAidingMode(), setup(), NavEKF2_core::setWindMagStateLearningMode(), NavEKF3_core::setWindMagStateLearningMode(), AC_WPNav::shift_wp_origin_and_destination_to_stopping_point_xy(), TEST(), TEST(), TEST(), AP_OpticalFlow_Pixart::timer(), AP_OpticalFlow_PX4Flow::timer(), Vector2< T >::todouble(), Vector2< T >::tofloat(), AP_Beacon_SITL::update(), AP_InertialNav::update(), SITL::Helicopter::update(), SlewCalculator2D::update(), AR_PosControl::update(), AP_OpticalFlow::update(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_Onboard::update(), AP_OpticalFlow_Pixart::update(), AP_OpticalFlow_UPFLOW::update(), AP_WheelEncoder_SITL_Quadrature::update(), AC_PID_2D::update_all(), AC_P_2D::update_all(), AC_P_2D::update_all(), AP_Mount_Servo::update_angle_outputs(), AP_WindVane::update_apparent_wind_dir_from_true(), AP_Beacon::update_boundary_points(), AP_L1_Control::update_loiter(), SITL::Helicopter::update_rotor_dynamics(), AP_WindVane::update_true_wind_speed_and_direction(), AP_L1_Control::update_waypoint(), AC_WPNav_OA::update_wpnav(), NavEKF2_core::writeOptFlowMeas(), NavEKF3_core::writeOptFlowMeas(), and Vector2< T >::zero().
y
template<typename T > T Vector2< T >::y
Definition at line 44 of file vector2.h.
Referenced by Linux::OpticalFlow_Onboard::_run_optflow(), AP_OpticalFlow_Calibrator::add_sample(), AC_Avoid::adjust_roll_pitch(), AC_Avoid::adjust_velocity(), AC_Avoid::adjust_velocity_fence(), AC_Avoid::adjust_velocity_proximity(), AR_WPNav::advance_wp_target_along_track(), AC_AttitudeControl::ang_vel_limit(), AP_AHRS::body_to_earth2D(), AP_AHRS_View::body_to_earth2D(), AP_GPS::calc_blended_state(), AC_Loiter::calc_desired_velocity(), AC_Autorotation::calc_speed_forward(), AP_AHRS::calc_trig(), AC_PosControl::calculate_yaw_and_rate_yaw(), NavEKF2_core::CorrectGPSForAntennaOffset(), AC_AutoTune_Heli::dwell_test_run(), AP_AHRS::earth_to_body2D(), AP_AHRS_View::earth_to_body2D(), NavEKF2_core::EstimateTerrainOffset(), NavEKF3_core::EstimateTerrainOffset(), AC_Avoid::find_max_quadrant_velocity(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::FuseAirspeed(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), NavEKF2_core::FuseSideslip(), NavEKF3_core::FuseSideslip(), get_bearing_cd(), AC_Circle::get_closest_point_on_circle(), AC_PID_2D::get_ff(), SITL::ShipSim::get_ground_speed_adjustment(), AP_Beacon::get_next_boundary_point(), AC_Loiter::get_pilot_desired_acceleration(), AC_AutoTune::get_poshold_attitude(), AP_AHRS::get_relative_position_NED_origin(), AR_WPNav::get_stopping_location(), AC_PrecLand::get_target_position_cm(), AC_WPNav::get_vector_NEU(), NavEKF2_core::getAirSpdVec(), NavEKF3_core::getAirSpdVec(), NavEKF2_core::getLLH(), NavEKF3_core::getLLH(), NavEKF2_core::getPosNE(), NavEKF3_core::getPosNE(), NavEKF3_core::getSynthAirDataInnovations(), NavEKF2_core::getWind(), NavEKF3_core::getWind(), AR_PosControl::init(), AC_Loiter::init_target(), AC_Loiter::init_target(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), AC_AttitudeControl::input_shaping_rate_predictor(), Vector2< T >::is_zero(), Location::line_path_proportion(), location_from_point(), Vector2< T >::point_on_segment(), Polygon_closest_distance_line(), Polygon_intersects(), Polygon_outside(), Linux::OpticalFlow_Onboard::push_gyro(), Linux::OpticalFlow_Onboard::push_gyro_bias(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), rc_input_to_roll_pitch(), NavEKF3_core::ResetPosition(), NavEKF2_core::ResetPosition(), NavEKF2_core::ResetPositionNE(), NavEKF3_core::ResetPositionNE(), NavEKF3_core::ResetVelocity(), NavEKF2_core::ResetVelocity(), AC_PrecLand::run_estimator(), AC_PrecLand::run_output_prediction(), NavEKF2_core::SelectVelPosFusion(), NavEKF3_core::SelectVelPosFusion(), AP_Hott_Telem::send_GPS(), SITL::ShipSim::send_report(), AC_Circle::set_center(), AR_WPNav::set_desired_location(), AC_PI_2D::set_integrator(), AC_Loiter::set_pilot_desired_acceleration(), NavEKF2_core::setAidingMode(), NavEKF3_core::setAidingMode(), NavEKF2_core::setWindMagStateLearningMode(), NavEKF3_core::setWindMagStateLearningMode(), AC_WPNav::shift_wp_origin_and_destination_to_stopping_point_xy(), TEST(), TEST(), TEST(), AP_OpticalFlow_Pixart::timer(), AP_OpticalFlow_PX4Flow::timer(), Vector2< T >::todouble(), Vector2< T >::tofloat(), AP_Beacon_SITL::update(), AP_InertialNav::update(), SITL::Helicopter::update(), SlewCalculator2D::update(), AR_PosControl::update(), AP_OpticalFlow::update(), AP_OpticalFlow_CXOF::update(), AP_OpticalFlow_Onboard::update(), AP_OpticalFlow_Pixart::update(), AP_OpticalFlow_UPFLOW::update(), AP_WheelEncoder_SITL_Quadrature::update(), AC_PID_2D::update_all(), AC_P_2D::update_all(), AP_Mount_Servo::update_angle_outputs(), AP_WindVane::update_apparent_wind_dir_from_true(), AP_Beacon::update_boundary_points(), AP_L1_Control::update_loiter(), SITL::Helicopter::update_rotor_dynamics(), AP_WindVane::update_true_wind_speed_and_direction(), AP_L1_Control::update_waypoint(), AC_WPNav_OA::update_wpnav(), NavEKF2_core::writeOptFlowMeas(), NavEKF3_core::writeOptFlowMeas(), and Vector2< T >::zero().
The documentation for this class was generated from the following files:
libraries/AP_Math/vector2.h
libraries/AP_Math/vector2.cpp