APM:Libraries: crypto_sign_vtable Struct Reference
crypto_sign_vtable Struct Reference
Type definitions ///.
#include <monocypher.h>
Public Attributes
void(* hash)(uint8_t hash[64], const uint8_t *message, size_t message_size)
void(* init)(void *ctx)
void(* update)(void *ctx, const uint8_t *message, size_t message_size)
void(* final)(void *ctx, uint8_t hash[64])
size_t ctx_size
Detailed Description
Type definitions ///.
Definition at line 67 of file monocypher.h.
Member Data Documentation
ctx_size
size_t crypto_sign_vtable::ctx_size
Definition at line 72 of file monocypher.h.
Referenced by crypto_sign_final().
final
void(* crypto_sign_vtable::final) (void *ctx, uint8_t hash[64])
Definition at line 71 of file monocypher.h.
Referenced by crypto_check_final(), crypto_sign_final(), and crypto_sign_init_second_pass().
hash
void(* crypto_sign_vtable::hash) (uint8_t hash[64], const uint8_t *message, size_t message_size)
Definition at line 68 of file monocypher.h.
Referenced by crypto_sign_init_first_pass_custom_hash(), and crypto_sign_public_key_custom_hash().
init
void(* crypto_sign_vtable::init) (void *ctx)
Definition at line 69 of file monocypher.h.
Referenced by crypto_check_init_custom_hash(), crypto_sign_init_first_pass_custom_hash(), and crypto_sign_init_second_pass().
update
void(* crypto_sign_vtable::update) (void *ctx, const uint8_t *message, size_t message_size)
Definition at line 70 of file monocypher.h.
Referenced by crypto_check_init_custom_hash(), crypto_check_update(), crypto_sign_init_first_pass_custom_hash(), crypto_sign_init_second_pass(), and crypto_sign_update().
The documentation for this struct was generated from the following file:
libraries/AP_CheckFirmware/monocypher.h