APM:Libraries: AP_SmartAudio::FrameHeader Struct Reference
AP_SmartAudio::FrameHeader Struct Reference
#include <AP_SmartAudio.h>
Public Member Functions
void init (uint8_t cmd, uint8_t payloadLength)
Public Attributes
uint8_t syncByte
uint8_t headerByte
uint8_t command
uint8_t length
Detailed Description
Definition at line 92 of file AP_SmartAudio.h.
Member Function Documentation
init()
void AP_SmartAudio::FrameHeader::init (uint8_t cmd, uint8_t payloadLength) inline
Definition at line 98 of file AP_SmartAudio.h.
Referenced by AP_SmartAudio::push_command_only_frame(), AP_SmartAudio::push_uint16_command_frame(), and AP_SmartAudio::push_uint8_command_frame().
Member Data Documentation
command
uint8_t AP_SmartAudio::FrameHeader::command
Definition at line 95 of file AP_SmartAudio.h.
Referenced by init().
headerByte
uint8_t AP_SmartAudio::FrameHeader::headerByte
Definition at line 94 of file AP_SmartAudio.h.
Referenced by init().
length
uint8_t AP_SmartAudio::FrameHeader::length
Definition at line 96 of file AP_SmartAudio.h.
Referenced by init().
syncByte
uint8_t AP_SmartAudio::FrameHeader::syncByte
Definition at line 93 of file AP_SmartAudio.h.
Referenced by init().
The documentation for this struct was generated from the following file:
libraries/AP_VideoTX/AP_SmartAudio.h