APM:Libraries: libraries/AP_Common/tests/test_nmea_vaprint.cpp File Reference
test_nmea_vaprint.cpp File Reference
#include <AP_gtest.h>
#include <AP_HAL/UARTDriver.h>
#include <AP_Common/NMEA.h>
Classes
class BufferPrinter
class DummyUart
Functions
void * malloc (size_t size)
void print_vprintf (AP_HAL::BetterStream *s, const char *fmt, va_list ap)
TEST (NMEA, VAPrintf)
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static uint32_t count = 0
static DummyUart test_uart
Function Documentation
malloc()
void * malloc (size_t size)
Definition at line 8 of file test_nmea_vaprint.cpp.
Referenced by SITL::InvensenseV3::add_block(), SITL::InvensenseV3::add_fifo(), allocate(), base64_decode(), base64_encode_global(), BM_Crop8bpp(), BM_YuyvToGrey(), error(), AP_ROMFS::find_decompress(), AP_Filesystem_Backend::load_file(), FlashTest::loop(), AP_Logger::msg_fmt_for_name(), nmea_vaprintf(), realloc(), ChibiOS::DeviceBus::register_periodic_callback(), SITL::SMBusDevice::set_block(), ChibiOS::AnalogIn::setup_adc(), ChibiOS::Scheduler::thread_create(), HALSITL::Scheduler::thread_create(), and trace().
print_vprintf()
void print_vprintf (AP_HAL::BetterStream * s, const char * fmt, va_list ap)
Definition at line 35 of file test_nmea_vaprint.cpp.
TEST()
TEST (NMEA , VAPrintf)
Definition at line 68 of file test_nmea_vaprint.cpp.
Variable Documentation
count
uint32_t count = 0 static
Definition at line 6 of file test_nmea_vaprint.cpp.
Referenced by malloc(), and print_vprintf().
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
This file test realloc failure on ExpandingString
Definition at line 5 of file test_nmea_vaprint.cpp.
test_uart
DummyUart test_uart static
Definition at line 66 of file test_nmea_vaprint.cpp.
Referenced by TEST().