APM:Libraries: libraries/AP_BattMonitor/tests/test_calculate_mah.cpp File Reference
test_calculate_mah.cpp File Reference
#include <AP_gtest.h>
#include <AP_BattMonitor/AP_BattMonitor_Backend.h>
Functions
static float calculate_mah_with_double_cast (float amps, float dt)
static float calculate_mah (float amps, float dt)
TEST (AP_BATTMONITOR_MAH, test_calculate_mah)
TEST (AP_BATTMONITOR_ACCURACY, test_float_accuracy)
Function Documentation
calculate_mah()
static float calculate_mah (float amps, float dt) static
Definition at line 10 of file test_calculate_mah.cpp.
Referenced by TEST(), and TEST().
calculate_mah_with_double_cast()
static float calculate_mah_with_double_cast (float amps, float dt) static
Definition at line 5 of file test_calculate_mah.cpp.
Referenced by TEST().
TEST() [1/2]
TEST (AP_BATTMONITOR_ACCURACY , test_float_accuracy)
Definition at line 29 of file test_calculate_mah.cpp.
TEST() [2/2]
TEST (AP_BATTMONITOR_MAH , test_calculate_mah)
Definition at line 15 of file test_calculate_mah.cpp.