APM:Libraries: libraries/AP_Common/tests/test_sorting.cpp File Reference
test_sorting.cpp File Reference
#include <AP_gtest.h>
#include <AP_Common/AP_Common.h>
#include <AP_Common/sorting.h>
#include <stdlib.h>
Typedefs
typedef int(* compare_fn_t) (const void *, const void *)
Functions
static int comp16 (const uint16_t *v1, const uint16_t *v2)
static void check_equal (const uint16_t *a1, const uint16_t *a2, uint16_t n)
TEST (Sorting, sort)
static uint16_t dumb_unique (uint16_t *data, uint16_t n)
TEST (Sorting, unique)
static bool dumb_search (uint16_t *data, uint16_t n, uint16_t value)
TEST (Sorting, bisect)
static uint16_t dumb_remove_list (uint16_t *data, uint16_t n, const uint16_t *rem, uint16_t n2)
TEST (Sorting, remove)
Typedef Documentation
compare_fn_t
typedef int(* compare_fn_t) (const void *, const void *)
Definition at line 13 of file test_sorting.cpp.
Function Documentation
check_equal()
static void check_equal (const uint16_t * a1, const uint16_t * a2, uint16_t n) static
Definition at line 19 of file test_sorting.cpp.
Referenced by TEST(), and TEST().
comp16()
static int comp16 (const uint16_t * v1, const uint16_t * v2) static
Definition at line 15 of file test_sorting.cpp.
Referenced by TEST().
dumb_remove_list()
static uint16_t dumb_remove_list (uint16_t * data, uint16_t n, const uint16_t * rem, uint16_t n2) static
Definition at line 108 of file test_sorting.cpp.
Referenced by TEST().
dumb_search()
static bool dumb_search (uint16_t * data, uint16_t n, uint16_t value) static
Definition at line 78 of file test_sorting.cpp.
Referenced by TEST().
dumb_unique()
static uint16_t dumb_unique (uint16_t * data, uint16_t n) static
Definition at line 43 of file test_sorting.cpp.
Referenced by TEST().
TEST() [1/4]
TEST (Sorting , bisect)
Definition at line 88 of file test_sorting.cpp.
TEST() [2/4]
TEST (Sorting , remove)
Definition at line 129 of file test_sorting.cpp.
TEST() [3/4]
TEST (Sorting , sort)
Definition at line 26 of file test_sorting.cpp.
TEST() [4/4]
TEST (Sorting , unique)
Definition at line 58 of file test_sorting.cpp.