APM:Libraries: libraries/AP_HAL/utility/tests/test_own_ptr.cpp File Reference
test_own_ptr.cpp File Reference
#include <AP_gtest.h>
#include <utility>
#include <AP_HAL/utility/OwnPtr.h>
Classes
class TestDeleted
class TestCall
class TestDestructor
class A
class B
Functions
TEST (OwnPtrTest, SamePointer)
TEST (OwnPtrTest, MoveOwnership)
TEST (OwnPtrTest, DeleteOutOfScope)
TEST (OwnPtrTest, DeleteOutOfScopeAfterMove)
TEST (OwnPtrTest, CallMethod)
TEST (OwnPtrTest, MoveToConstructor)
static AP_HAL::OwnPtr< TestDeleted > create_test_deleted (unsigned int &deleted)
TEST (OwnPtrTest, ReturnType)
TEST (OwnPtrTest, ReplacePointer)
TEST (OwnPtrTest, ReplaceWithRawPointer)
TEST (OwnPtrTest, Empty)
TEST (OwnPtrTest, Inheritance)
Function Documentation
create_test_deleted()
static AP_HAL::OwnPtr< TestDeleted > create_test_deleted (unsigned int & deleted) static
Definition at line 116 of file test_own_ptr.cpp.
Referenced by TEST(), TEST(), and TEST().
TEST() [1/11]
TEST (OwnPtrTest , CallMethod)
Definition at line 89 of file test_own_ptr.cpp.
TEST() [2/11]
TEST (OwnPtrTest , DeleteOutOfScope)
Definition at line 54 of file test_own_ptr.cpp.
TEST() [3/11]
TEST (OwnPtrTest , DeleteOutOfScopeAfterMove)
Definition at line 65 of file test_own_ptr.cpp.
TEST() [4/11]
TEST (OwnPtrTest , Empty)
Definition at line 164 of file test_own_ptr.cpp.
TEST() [5/11]
TEST (OwnPtrTest , Inheritance)
Definition at line 186 of file test_own_ptr.cpp.
TEST() [6/11]
TEST (OwnPtrTest , MoveOwnership)
Definition at line 36 of file test_own_ptr.cpp.
TEST() [7/11]
TEST (OwnPtrTest , MoveToConstructor)
Definition at line 103 of file test_own_ptr.cpp.
TEST() [8/11]
TEST (OwnPtrTest , ReplacePointer)
Definition at line 136 of file test_own_ptr.cpp.
TEST() [9/11]
TEST (OwnPtrTest , ReplaceWithRawPointer)
Definition at line 152 of file test_own_ptr.cpp.
TEST() [10/11]
TEST (OwnPtrTest , ReturnType)
Definition at line 121 of file test_own_ptr.cpp.
TEST() [11/11]
TEST (OwnPtrTest , SamePointer)
Definition at line 22 of file test_own_ptr.cpp.