APM:Libraries: libraries/AP_ADSB/sagetech-sdk/toInt32.c File Reference
toInt32.c File Reference
#include "sgUtil.h"
Functions
int32_t toInt32 (const uint8_t bytes[])
Detailed Description
Copyright
Copyright (c) 2021 Sagetech, Inc. All rights reserved.
Author
Jacob.Garrison
Date
Mar 2, 2021
Definition in file toInt32.c.
Function Documentation
toInt32()
int32_t toInt32 (const uint8_t bytes[])
Converts an array of bytes to a 32 bit integer.
Parameters
bytes The array of bytes to convert.
Returns
The 32 bit integer.
Definition at line 16 of file toInt32.c.
Referenced by sgDecodeAck(), sgDecodeMSR(), sgDecodeSVR(), toAlt(), and toLatLon().