APM:Libraries: libraries/AP_HAL_ChibiOS/hwdef/common/watchdog.h File Reference
watchdog.h File Reference
Functions
void stm32_watchdog_init (void)
void stm32_watchdog_pat (void)
bool stm32_was_watchdog_reset (void)
bool stm32_was_software_reset (void)
void stm32_watchdog_save_reason (void)
void stm32_watchdog_clear_reason (void)
void stm32_watchdog_save (const uint32_t *data, uint32_t nwords)
void stm32_watchdog_load (uint32_t *data, uint32_t nwords)
Function Documentation
stm32_was_software_reset()
bool stm32_was_software_reset (void)
Definition at line 120 of file watchdog.c.
stm32_was_watchdog_reset()
bool stm32_was_watchdog_reset (void)
Definition at line 111 of file watchdog.c.
Referenced by main_loop().
stm32_watchdog_clear_reason()
void stm32_watchdog_clear_reason (void)
Definition at line 103 of file watchdog.c.
Referenced by __late_init().
stm32_watchdog_init()
void stm32_watchdog_init (void)
Definition at line 69 of file watchdog.c.
Referenced by main_loop(), and HAL_ChibiOS::run().
stm32_watchdog_load()
void stm32_watchdog_load (uint32_t * data, uint32_t nwords)
Definition at line 137 of file watchdog.c.
Referenced by main_loop().
stm32_watchdog_pat()
void stm32_watchdog_pat (void)
Definition at line 83 of file watchdog.c.
Referenced by CrashCatcher_DumpEndFlash(), CrashCatcher_DumpStartFlash(), flush_dump_buffer(), HAL_ChibiOS::run(), and ChibiOS::Scheduler::watchdog_pat().
stm32_watchdog_save()
void stm32_watchdog_save (const uint32_t * data, uint32_t nwords)
Definition at line 129 of file watchdog.c.
Referenced by ChibiOS::Scheduler::_monitor_thread(), and save_fault_watchdog().
stm32_watchdog_save_reason()
void stm32_watchdog_save_reason (void)
Definition at line 93 of file watchdog.c.
Referenced by __late_init(), stm32_was_software_reset(), and stm32_was_watchdog_reset().