APM:Libraries: libraries/AP_JSON/examples/XPlane/XPlane.cpp File Reference
XPlane.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include <AP_JSON/AP_JSON.h>
#include <stdio.h>
Functions
void setup ()
void loop ()
static bool test_xplane (void)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
static uint32_t test_count
static uint32_t label_count
Function Documentation
AP_HAL_MAIN()
AP_HAL_MAIN ()
loop()
void loop (void)
Definition at line 49 of file XPlane.cpp.
setup()
void setup (void)
Definition at line 44 of file XPlane.cpp.
test_xplane()
static bool test_xplane (void) static
Definition at line 18 of file XPlane.cpp.
Referenced by loop().
Variable Documentation
hal
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
This file test realloc failure on ExpandingString
Definition at line 13 of file XPlane.cpp.
Referenced by loop(), setup(), and test_xplane().
label_count
uint32_t label_count static
Definition at line 16 of file XPlane.cpp.
Referenced by test_xplane().
test_count
uint32_t test_count static
Definition at line 15 of file XPlane.cpp.
Referenced by loop().