APM:Libraries: libraries/AP_NavEKF3/derivation/generated/yaw_generated.cpp File Reference
yaw_generated.cpp File Reference
Variables
const ftype SA0 = 2*q3
const ftype SA1 = 2*q2
const ftype SA2 = SA0*q0 + SA1*q1
const ftype SA3 = sq(q0) + sq(q1) - sq(q2) - sq(q3)
const ftype SA4 = 1.0/sq(SA3)
const ftype SA5 = 1.0F/(sq(SA2)*SA4 + 1)
const ftype SA6 = 1.0F/SA3
const ftype SA7 = SA2*SA4
const ftype SA8 = 2*SA7
const ftype SA9 = 2*SA6
H_YAW [0] = SA5*(SA0*SA6 - SA8*q0)
const ftype SB0 = 2*q0
const ftype SB1 = 2*q1
const ftype SB2 = SB0*q3 + SB1*q2
const ftype SB3 = 1.0/sq(SB2)
const ftype SB4 = sq(q0) + sq(q1) - sq(q2) - sq(q3)
const ftype SB5 = 1.0F/(SB3*sq(SB4) + 1)
const ftype SB6 = 1.0F/SB2
const ftype SB7 = SB3*SB4
const ftype SB8 = 2*SB7
const ftype SB9 = 2*SB6
Variable Documentation
H_YAW
H_YAW[23] = SA5*(SA0*SA6 - SA8*q0)
Definition at line 14 of file yaw_generated.cpp.
Referenced by NavEKF2_core::fuseEulerYaw(), and NavEKF3_core::fuseEulerYaw().
SA0
const ftype SA0 = 2*q3
Definition at line 2 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SA1
const ftype SA1 = 2*q2
Definition at line 3 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SA2
const ftype SA2 = SA0*q0 + SA1*q1
Definition at line 4 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SA3
const ftype SA3 = sq(q0) + sq(q1) - sq(q2) - sq(q3)
Definition at line 5 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SA4
const ftype SA4 = 1.0/sq(SA3)
Definition at line 6 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SA5
const ftype SA5 = 1.0F/(sq(SA2)*SA4 + 1)
Definition at line 7 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SA6
const ftype SA6 = 1.0F/SA3
Definition at line 8 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SA7
const ftype SA7 = SA2*SA4
Definition at line 9 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SA8
const ftype SA8 = 2*SA7
Definition at line 10 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SA9
const ftype SA9 = 2*SA6
Definition at line 11 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SB0
const ftype SB0 = 2*q0
Definition at line 41 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SB1
const ftype SB1 = 2*q1
Definition at line 42 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SB2
const ftype SB2 = SB0*q3 + SB1*q2
Definition at line 43 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SB3
const ftype SB3 = 1.0/sq(SB2)
Definition at line 44 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SB4
const ftype SB4 = sq(q0) + sq(q1) - sq(q2) - sq(q3)
Definition at line 45 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SB5
const ftype SB5 = 1.0F/(SB3*sq(SB4) + 1)
Definition at line 46 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SB6
const ftype SB6 = 1.0F/SB2
Definition at line 47 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SB7
const ftype SB7 = SB3*SB4
Definition at line 48 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SB8
const ftype SB8 = 2*SB7
Definition at line 49 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().
SB9
const ftype SB9 = 2*SB6
Definition at line 50 of file yaw_generated.cpp.
Referenced by NavEKF3_core::fuseEulerYaw().