APM:Rover: GCS_MAVLINK_Rover Class Reference
GCS_MAVLINK_Rover Class Reference
#include <GCS_Mavlink.h>
Public Member Functions
GCS_MAVLINK (GCS_MAVLINK_Parameters &parameters, AP_HAL::UARTDriver &uart)
Public Member Functions inherited from GCS_MAVLINK
GCS_MAVLINK (GCS_MAVLINK_Parameters &parameters, AP_HAL::UARTDriver &uart)
virtual ~GCS_MAVLINK ()
mavlink_message_t * channel_buffer ()
mavlink_status_t * channel_status ()
void update_receive (uint32_t max_time_us=1000)
void update_send ()
bool init (uint8_t instance)
void send_message (enum ap_message id)
void send_text (MAV_SEVERITY severity, const char *fmt,...) const FMT_PRINTF(3
void void queued_param_send ()
void queued_mission_request_send ()
bool sending_mavlink1 () const
bool requesting_mission_items () const
uint16_t txspace () const
bool check_payload_size (uint16_t max_payload_len)
void out_of_space_to_send ()
void send_mission_ack (const mavlink_message_t &msg, MAV_MISSION_TYPE mission_type, MAV_MISSION_RESULT result) const
void send_message (uint32_t msgid, const char *pkt)
void send_message (const char *pkt, const mavlink_msg_entry_t *entry)
AP_HAL::UARTDriver * get_uart ()
void send_parameter_value (const char *param_name, ap_var_type param_type, float param_value)
bool is_high_bandwidth ()
bool have_flow_control ()
bool is_active () const
bool is_streaming () const
mavlink_channel_t get_chan () const
uint32_t get_last_heartbeat_time () const
virtual MISSION_STATE mission_state (const class AP_Mission &mission) const
void send_mission_current (const class AP_Mission &mission, uint16_t seq)
void send_heartbeat (void) const
void send_meminfo (void)
void send_fence_status () const
void send_power_status (void)
void send_battery_status (const uint8_t instance) const
bool send_battery_status ()
void send_distance_sensor ()
void send_proximity ()
void send_ahrs2 ()
void send_system_time () const
void send_rc_channels () const
void send_rc_channels_raw () const
void send_raw_imu ()
void send_scaled_pressure_instance (uint8_t instance, void(*send_fn)(mavlink_channel_t chan, uint32_t time_boot_ms, float press_abs, float press_diff, int16_t temperature, int16_t temperature_press_diff))
void send_scaled_pressure ()
void send_scaled_pressure2 ()
virtual void send_scaled_pressure3 ()
void send_simstate () const
void send_sim_state () const
void send_ahrs ()
void send_battery2 ()
void send_opticalflow ()
virtual void send_attitude () const
virtual void send_attitude_quaternion () const
void send_autopilot_version () const
void send_extended_sys_state () const
void send_local_position () const
void send_vfr_hud ()
void send_vibration () const
void send_gimbal_device_attitude_status () const
void send_gimbal_manager_information () const
void send_gimbal_manager_status () const
void send_named_float (const char *name, float value) const
void send_home_position () const
void send_gps_global_origin () const
virtual void send_attitude_target ()
virtual void send_position_target_local_ned ()
void send_servo_output_raw ()
void send_accelcal_vehicle_position (uint32_t position)
void send_scaled_imu (uint8_t instance, void(*send_fn)(mavlink_channel_t chan, uint32_t time_ms, int16_t xacc, int16_t yacc, int16_t zacc, int16_t xgyro, int16_t ygyro, int16_t zgyro, int16_t xmag, int16_t ymag, int16_t zmag, int16_t temperature))
void send_sys_status ()
void send_set_position_target_global_int (uint8_t target_system, uint8_t target_component, const Location &loc)
void send_rpm () const
void send_generator_status () const
void send_water_depth () const
int8_t battery_remaining_pct (const uint8_t instance) const
void send_high_latency2 () const
void send_uavionix_adsb_out_status () const
void send_autopilot_state_for_gimbal_device () const
void lock (bool _lock)
bool locked () const
bool is_private (void) const
FUNCTOR_TYPEDEF (protocol_handler_fn_t, bool, uint8_t, AP_HAL::UARTDriver *)
uint16_t get_stream_slowdown_ms () const
uint8_t get_last_txbuf () const
MAV_RESULT set_message_interval (uint32_t msg_id, int32_t interval_us)
MAV_STREAM_ENTRY (STREAM_RAW_SENSORS)
MAV_STREAM_ENTRY (STREAM_EXTENDED_STATUS)
MAV_STREAM_ENTRY (STREAM_POSITION)
MAV_STREAM_ENTRY (STREAM_RAW_CONTROLLER)
MAV_STREAM_ENTRY (STREAM_RC_CHANNELS)
MAV_STREAM_ENTRY (STREAM_EXTRA1)
MAV_STREAM_ENTRY (STREAM_EXTRA2)
MAV_STREAM_ENTRY (STREAM_EXTRA3)
MAV_STREAM_ENTRY (STREAM_ADSB)
MAV_STREAM_ENTRY (STREAM_PARAMS)
Protected Member Functions
uint32_t telem_delay () const override
uint8_t sysid_my_gcs () const override
bool sysid_enforce () const override
MAV_RESULT _handle_command_preflight_calibration (const mavlink_command_int_t &packet, const mavlink_message_t &msg) override
MAV_RESULT handle_command_int_packet (const mavlink_command_int_t &packet, const mavlink_message_t &msg) override
MAV_RESULT handle_command_int_do_reposition (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_nav_set_yaw_speed (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
void send_position_target_global_int () override
bool persist_streamrates () const override
bool set_home_to_current_location (bool lock) override
bool set_home (const Location &loc, bool lock) override
uint64_t capabilities () const override
void send_nav_controller_output () const override
void send_pid_tuning () override
Protected Member Functions inherited from GCS_MAVLINK
bool mavlink_coordinate_frame_to_location_alt_frame (MAV_FRAME coordinate_frame, Location::AltFrame &frame)
bool accept_packet (const mavlink_status_t &status, const mavlink_message_t &msg) const
void set_ekf_origin (const Location &loc)
MAV_STATE system_status () const
virtual MAV_VTOL_STATE vtol_state () const
virtual MAV_LANDED_STATE landed_state () const
uint8_t packet_overhead (void) const
void handle_heartbeat (const mavlink_message_t &msg) const
void handle_request_data_stream (const mavlink_message_t &msg)
virtual void handle_command_ack (const mavlink_message_t &msg)
void handle_set_mode (const mavlink_message_t &msg)
void handle_command_int (const mavlink_message_t &msg)
MAV_RESULT handle_command_do_set_home (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_int_external_position_estimate (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_aux_function (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_storage_format (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
void handle_mission_request_list (const mavlink_message_t &msg)
void handle_mission_request_int (const mavlink_message_t &msg)
void handle_mission_clear_all (const mavlink_message_t &msg)
void handle_mission_count (const mavlink_message_t &msg)
void handle_mission_write_partial_list (const mavlink_message_t &msg)
void handle_mission_item (const mavlink_message_t &msg)
void handle_distance_sensor (const mavlink_message_t &msg)
void handle_obstacle_distance (const mavlink_message_t &msg)
void handle_obstacle_distance_3d (const mavlink_message_t &msg)
void handle_adsb_message (const mavlink_message_t &msg)
void handle_osd_param_config (const mavlink_message_t &msg) const
void handle_common_param_message (const mavlink_message_t &msg)
void handle_param_set (const mavlink_message_t &msg)
void handle_param_request_list (const mavlink_message_t &msg)
void handle_param_request_read (const mavlink_message_t &msg)
virtual bool params_ready () const
void handle_rc_channels_override (const mavlink_message_t &msg)
void handle_system_time_message (const mavlink_message_t &msg)
void handle_common_rally_message (const mavlink_message_t &msg)
void handle_rally_fetch_point (const mavlink_message_t &msg)
void handle_rally_point (const mavlink_message_t &msg) const
void handle_fence_message (const mavlink_message_t &msg)
void handle_param_value (const mavlink_message_t &msg)
void handle_radio_status (const mavlink_message_t &msg)
void handle_serial_control (const mavlink_message_t &msg)
void handle_vision_position_delta (const mavlink_message_t &msg)
void handle_set_gps_global_origin (const mavlink_message_t &msg)
void handle_setup_signing (const mavlink_message_t &msg) const
virtual MAV_RESULT handle_preflight_reboot (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
void deadlock_sem (void)
MAV_RESULT handle_do_set_safety_switch_state (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
MAV_RESULT handle_command_set_message_interval (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_get_message_interval (const mavlink_command_int_t &packet)
bool get_ap_message_interval (ap_message id, uint16_t &interval_ms) const
MAV_RESULT handle_command_request_message (const mavlink_command_int_t &packet)
MAV_RESULT handle_START_RX_PAIR (const mavlink_command_int_t &packet)
virtual MAV_RESULT handle_flight_termination (const mavlink_command_int_t &packet)
void handle_send_autopilot_version (const mavlink_message_t &msg)
MAV_RESULT handle_command_request_autopilot_capabilities (const mavlink_command_int_t &packet)
virtual void send_banner ()
void send_received_message_deprecation_warning (const char *message)
void handle_device_op_read (const mavlink_message_t &msg)
void handle_device_op_write (const mavlink_message_t &msg)
void send_timesync ()
uint64_t timesync_receive_timestamp_ns () const
uint64_t timesync_timestamp_ns () const
void handle_timesync (const mavlink_message_t &msg)
void handle_statustext (const mavlink_message_t &msg) const
void handle_named_value (const mavlink_message_t &msg) const
bool telemetry_delayed () const
MAV_RESULT handle_command_run_prearm_checks (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_flash_bootloader (const mavlink_command_int_t &packet)
virtual MAV_RESULT handle_command_preflight_calibration (const mavlink_command_int_t &packet, const mavlink_message_t &msg)
virtual MAV_RESULT _handle_command_preflight_calibration_baro (const mavlink_message_t &msg)
MAV_RESULT handle_command_battery_reset (const mavlink_command_int_t &packet)
void handle_command_long (const mavlink_message_t &msg)
MAV_RESULT handle_command_accelcal_vehicle_pos (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_mag_cal (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_fixed_mag_cal_yaw (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_camera (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_set_roi (const mavlink_command_int_t &packet)
virtual MAV_RESULT handle_command_do_set_roi (const Location &roi_loc)
MAV_RESULT handle_command_do_gripper (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_sprayer (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_set_mode (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_get_home_position (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_do_fence_enable (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_debug_trap (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_set_ekf_source_set (const mavlink_command_int_t &packet)
MAV_RESULT handle_command_airframe_configuration (const mavlink_command_int_t &packet)
void can_frame_callback (uint8_t bus, const AP_HAL::CANFrame &)
void handle_can_frame (const mavlink_message_t &msg) const
void handle_optical_flow (const mavlink_message_t &msg)
void handle_manual_control (const mavlink_message_t &msg)
virtual void send_global_position_int ()
bool try_send_mission_message (enum ap_message id)
void send_hwstatus ()
void handle_data_packet (const mavlink_message_t &msg)
virtual int32_t global_position_int_alt () const
virtual int32_t global_position_int_relative_alt () const
virtual float vfr_hud_climbrate () const
virtual float vfr_hud_airspeed () const
virtual float vfr_hud_alt () const
virtual int16_t high_latency_target_altitude () const
virtual uint8_t high_latency_tgt_heading () const
virtual uint16_t high_latency_tgt_dist () const
virtual uint8_t high_latency_tgt_airspeed () const
virtual uint8_t high_latency_wind_speed () const
virtual uint8_t high_latency_wind_direction () const
int8_t high_latency_air_temperature () const
MAV_RESULT handle_control_high_latency (const mavlink_command_int_t &packet)
void manual_override (class RC_Channel *c, int16_t value_in, uint16_t offset, float scaler, const uint32_t tnow, bool reversed=false)
uint8_t receiver_rssi () const
uint32_t correct_offboard_timestamp_usec_to_ms (uint64_t offboard_usec, uint16_t payload_size)
virtual void convert_COMMAND_LONG_to_COMMAND_INT (const mavlink_command_long_t &in, mavlink_command_int_t &out, MAV_FRAME frame=MAV_FRAME_GLOBAL_RELATIVE_ALT)
virtual bool mav_frame_for_command_long (MAV_FRAME &fame, MAV_CMD packet_command) const
MAV_RESULT try_command_long_as_command_int (const mavlink_command_long_t &packet, const mavlink_message_t &msg)
bool location_from_command_t (const mavlink_command_int_t &in, Location &out)
Private Member Functions
void handle_message (const mavlink_message_t &msg) override
bool handle_guided_request (AP_Mission::Mission_Command &cmd) override
bool try_send_message (enum ap_message id) override
void handle_manual_control_axes (const mavlink_manual_control_t &packet, const uint32_t tnow) override
void handle_set_attitude_target (const mavlink_message_t &msg)
void handle_set_position_target_local_ned (const mavlink_message_t &msg)
void handle_set_position_target_global_int (const mavlink_message_t &msg)
void handle_radio (const mavlink_message_t &msg)
void handle_landing_target (const mavlink_landing_target_t &msg, uint32_t timestamp_ms) override
void send_servo_out ()
void packetReceived (const mavlink_status_t &status, const mavlink_message_t &msg) override
MAV_MODE base_mode () const override
MAV_STATE vehicle_system_status () const override
int16_t vfr_hud_throttle () const override
Additional Inherited Members
Public Types inherited from GCS_MAVLINK
enum streams
Static Public Member Functions inherited from GCS_MAVLINK
static uint32_t last_radio_status_remrssi_ms ()
static float telemetry_radio_rssi ()
static uint8_t active_channel_mask (void)
static uint8_t streaming_channel_mask (void)
static uint8_t private_channel_mask (void)
static void set_channel_private (mavlink_channel_t chan)
static bool is_private (mavlink_channel_t _chan)
static void send_to_components (uint32_t msgid, const char *pkt, uint8_t pkt_len)
static void disable_channel_routing (mavlink_channel_t chan)
static bool find_by_mavtype (uint8_t mav_type, uint8_t &sysid, uint8_t &compid, mavlink_channel_t &channel)
static bool find_by_mavtype_and_compid (uint8_t mav_type, uint8_t compid, uint8_t &sysid, mavlink_channel_t &channel)
static GCS_MAVLINK * find_by_mavtype_and_compid (uint8_t mav_type, uint8_t compid, uint8_t &sysid)
static void update_signing_timestamp (uint64_t timestamp_usec)
static uint8_t packet_overhead_chan (mavlink_channel_t chan)
Public Attributes inherited from GCS_MAVLINK
STREAM_RAW_SENSORS
STREAM_EXTENDED_STATUS
STREAM_RC_CHANNELS
STREAM_RAW_CONTROLLER
STREAM_POSITION
STREAM_EXTRA1
STREAM_EXTRA2
STREAM_EXTRA3
STREAM_PARAMS
STREAM_ADSB
NUM_STREAMS
uint32_t last_heartbeat_time
uint16_t mission_item_reached_index
bool is_high_latency_link
HAL_Semaphore sem
bool taken
int64_t sent_ts1
uint32_t last_sent_ms
const uint16_t interval_ms
GCS_MAVLINK::protocol_handler_fn_t handler
uint32_t last_mavlink_ms
uint32_t last_alternate_ms
bool active
Static Public Attributes inherited from GCS_MAVLINK
static const struct stream_entries all_stream_entries []
Static Protected Member Functions inherited from GCS_MAVLINK
static MAV_PARAM_TYPE mav_param_type (enum ap_var_type t)
Protected Attributes inherited from GCS_MAVLINK
AP_Param * _queued_parameter
mavlink_channel_t chan
AP_Int16 * streamRates
struct GCS_MAVLINK:: { ... } _deadlock_sem
struct GCS_MAVLINK:: { ... } _timesync_request
Static Protected Attributes inherited from GCS_MAVLINK
static constexpr const float magic_force_arm_value
static constexpr const float magic_force_disarm_value
Detailed Description
Definition at line 12 of file GCS_Mavlink.h.
Member Function Documentation
_handle_command_preflight_calibration()
MAV_RESULT GCS_MAVLINK_Rover::_handle_command_preflight_calibration (const mavlink_command_int_t & packet, const mavlink_message_t & msg) override protected virtual
Reimplemented from GCS_MAVLINK.
Definition at line 637 of file GCS_Mavlink.cpp.
base_mode()
MAV_MODE GCS_MAVLINK_Rover::base_mode () const override private virtual
Implements GCS_MAVLINK.
Definition at line 17 of file GCS_Mavlink.cpp.
capabilities()
uint64_t GCS_MAVLINK_Rover::capabilities () const override protected virtual
Reimplemented from GCS_MAVLINK.
Definition at line 1073 of file GCS_Mavlink.cpp.
GCS_MAVLINK()
GCS_MAVLINK::GCS_MAVLINK (GCS_MAVLINK_Parameters & parameters, AP_HAL::UARTDriver & uart)
handle_command_int_do_reposition()
MAV_RESULT GCS_MAVLINK_Rover::handle_command_int_do_reposition (const mavlink_command_int_t & packet) protected
Definition at line 742 of file GCS_Mavlink.cpp.
Referenced by handle_command_int_packet().
handle_command_int_packet()
MAV_RESULT GCS_MAVLINK_Rover::handle_command_int_packet (const mavlink_command_int_t & packet, const mavlink_message_t & msg) override protected virtual
Reimplemented from GCS_MAVLINK.
Definition at line 664 of file GCS_Mavlink.cpp.
handle_command_nav_set_yaw_speed()
MAV_RESULT GCS_MAVLINK_Rover::handle_command_nav_set_yaw_speed (const mavlink_command_int_t & packet, const mavlink_message_t & msg) protected
Definition at line 719 of file GCS_Mavlink.cpp.
Referenced by handle_command_int_packet().
handle_guided_request()
bool GCS_MAVLINK_Rover::handle_guided_request (AP_Mission::Mission_Command & cmd) override private virtual
Reimplemented from GCS_MAVLINK.
Definition at line 626 of file GCS_Mavlink.cpp.
handle_landing_target()
void GCS_MAVLINK_Rover::handle_landing_target (const mavlink_landing_target_t & msg, uint32_t timestamp_ms) override private virtual
Reimplemented from GCS_MAVLINK.
Definition at line 1066 of file GCS_Mavlink.cpp.
handle_manual_control_axes()
void GCS_MAVLINK_Rover::handle_manual_control_axes (const mavlink_manual_control_t & packet, const uint32_t tnow) override private virtual
Reimplemented from GCS_MAVLINK.
Definition at line 804 of file GCS_Mavlink.cpp.
handle_message()
void GCS_MAVLINK_Rover::handle_message (const mavlink_message_t & msg) override private virtual
Reimplemented from GCS_MAVLINK.
Definition at line 782 of file GCS_Mavlink.cpp.
handle_radio()
void GCS_MAVLINK_Rover::handle_radio (const mavlink_message_t & msg) private
handle_set_attitude_target()
void GCS_MAVLINK_Rover::handle_set_attitude_target (const mavlink_message_t & msg) private
Definition at line 810 of file GCS_Mavlink.cpp.
Referenced by handle_message().
handle_set_position_target_global_int()
void GCS_MAVLINK_Rover::handle_set_position_target_global_int (const mavlink_message_t & msg) private
Definition at line 967 of file GCS_Mavlink.cpp.
Referenced by handle_message().
handle_set_position_target_local_ned()
void GCS_MAVLINK_Rover::handle_set_position_target_local_ned (const mavlink_message_t & msg) private
Definition at line 841 of file GCS_Mavlink.cpp.
Referenced by handle_message().
packetReceived()
void GCS_MAVLINK_Rover::packetReceived (const mavlink_status_t & status, const mavlink_message_t & msg) override private virtual
Reimplemented from GCS_MAVLINK.
Definition at line 401 of file GCS_Mavlink.cpp.
persist_streamrates()
bool GCS_MAVLINK_Rover::persist_streamrates () const inline override protected virtual
Reimplemented from GCS_MAVLINK.
Definition at line 32 of file GCS_Mavlink.h.
send_nav_controller_output()
void GCS_MAVLINK_Rover::send_nav_controller_output () const override protected virtual
Implements GCS_MAVLINK.
Definition at line 102 of file GCS_Mavlink.cpp.
send_pid_tuning()
void GCS_MAVLINK_Rover::send_pid_tuning () override protected virtual
Implements GCS_MAVLINK.
Definition at line 187 of file GCS_Mavlink.cpp.
send_position_target_global_int()
void GCS_MAVLINK_Rover::send_position_target_global_int () override protected virtual
Reimplemented from GCS_MAVLINK.
Definition at line 74 of file GCS_Mavlink.cpp.
send_servo_out()
void GCS_MAVLINK_Rover::send_servo_out () private
Definition at line 122 of file GCS_Mavlink.cpp.
Referenced by try_send_message().
set_home()
bool GCS_MAVLINK_Rover::set_home (const Location & loc, bool lock) override protected virtual
Implements GCS_MAVLINK.
Definition at line 660 of file GCS_Mavlink.cpp.
set_home_to_current_location()
bool GCS_MAVLINK_Rover::set_home_to_current_location (bool lock) override protected virtual
Implements GCS_MAVLINK.
Definition at line 656 of file GCS_Mavlink.cpp.
sysid_enforce()
bool GCS_MAVLINK_Rover::sysid_enforce () const override protected virtual
Reimplemented from GCS_MAVLINK.
Definition at line 348 of file GCS_Mavlink.cpp.
sysid_my_gcs()
uint8_t GCS_MAVLINK_Rover::sysid_my_gcs () const override protected virtual
Implements GCS_MAVLINK.
Definition at line 343 of file GCS_Mavlink.cpp.
telem_delay()
uint32_t GCS_MAVLINK_Rover::telem_delay () const override protected virtual
Implements GCS_MAVLINK.
Definition at line 353 of file GCS_Mavlink.cpp.
try_send_message()
bool GCS_MAVLINK_Rover::try_send_message (enum ap_message id) override private virtual
Reimplemented from GCS_MAVLINK.
Definition at line 364 of file GCS_Mavlink.cpp.
vehicle_system_status()
MAV_STATE GCS_MAVLINK_Rover::vehicle_system_status () const override private virtual
Implements GCS_MAVLINK.
Definition at line 59 of file GCS_Mavlink.cpp.
vfr_hud_throttle()
int16_t GCS_MAVLINK_Rover::vfr_hud_throttle () const override private virtual
Reimplemented from GCS_MAVLINK.
Definition at line 147 of file GCS_Mavlink.cpp.
The documentation for this class was generated from the following files:
Rover/GCS_Mavlink.h
Rover/GCS_Mavlink.cpp