APM:Rover: AP_Arming_Rover Class Reference
AP_Arming_Rover Class Reference
#include <AP_Arming.h>
Public Member Functions
AP_Arming_Rover ()
CLASS_NO_COPY (AP_Arming_Rover)
bool pre_arm_checks (bool report) override
bool arm_checks (AP_Arming::Method method) override
bool rc_calibration_checks (const bool display_failure) override
bool gps_checks (bool display_failure) override
bool disarm (AP_Arming::Method method, bool do_disarm_checks=true) override
bool arm (AP_Arming::Method method, bool do_arming_checks=true) override
void update_soft_armed ()
Public Member Functions inherited from AP_Arming
AP_Arming ()
CLASS_NO_COPY (AP_Arming)
void update ()
void init (void)
Required arming_required () const
bool is_armed () const
bool is_armed_and_safety_off () const
uint32_t get_enabled_checks () const
uint16_t compass_magfield_expected () const
RudderArming get_rudder_arming_type () const
Method last_disarm_method () const
Method last_arm_method () const
bool option_enabled (Option option) const
void send_arm_disarm_statustext (const char *string) const
Protected Member Functions
bool oa_check (bool report)
bool parameter_checks (bool report)
bool mode_checks (bool report)
bool motor_checks (bool report)
Protected Member Functions inherited from AP_Arming
virtual bool barometer_checks (bool report)
bool airspeed_checks (bool report)
bool logging_checks (bool report)
bool compass_checks (bool report)
bool battery_checks (bool report)
bool hardware_safety_check (bool report)
virtual bool board_voltage_checks (bool report)
bool rc_in_calibration_check (bool report)
bool rc_arm_checks (AP_Arming::Method method)
bool manual_transmitter_checks (bool report)
virtual bool mission_checks (bool report)
bool terrain_checks (bool report) const
virtual bool terrain_database_required () const
bool rangefinder_checks (bool report)
bool fence_checks (bool report)
bool camera_checks (bool display_failure)
bool osd_checks (bool display_failure) const
bool mount_checks (bool display_failure) const
bool generator_checks (bool report) const
bool opendroneid_checks (bool display_failure)
bool serial_protocol_checks (bool display_failure)
bool estop_checks (bool display_failure)
virtual bool system_checks (bool report)
bool can_checks (bool report)
bool fettec_checks (bool display_failure) const
bool servo_checks (bool report) const
bool rc_checks_copter_sub (bool display_failure, const class RC_Channel *channels[4]) const
bool visodom_checks (bool report) const
bool disarm_switch_checks (bool report) const
virtual bool mandatory_checks (bool report)
bool check_enabled (const enum AP_Arming::ArmingChecks check) const
void check_failed (const enum AP_Arming::ArmingChecks check, bool report, const char *fmt,...) const FMT_PRINTF(4
void void check_failed (bool report, const char *fmt,...) const FMT_PRINTF(3
void void void Log_Write_Arm (bool forced, AP_Arming::Method method)
void Log_Write_Disarm (bool forced, AP_Arming::Method method)
Additional Inherited Members
Public Types inherited from AP_Arming
enum ArmingChecks
enum Method
enum Required
enum RudderArming
enum Option
Static Public Member Functions inherited from AP_Arming
static AP_Arming * get_singleton ()
static bool method_is_GCS (Method method)
Public Attributes inherited from AP_Arming
ARMING_CHECK_ALL
ARMING_CHECK_BARO
ARMING_CHECK_COMPASS
ARMING_CHECK_GPS
ARMING_CHECK_INS
ARMING_CHECK_PARAMETERS
ARMING_CHECK_RC
ARMING_CHECK_VOLTAGE
ARMING_CHECK_BATTERY
ARMING_CHECK_AIRSPEED
ARMING_CHECK_LOGGING
ARMING_CHECK_SWITCH
ARMING_CHECK_GPS_CONFIG
ARMING_CHECK_SYSTEM
ARMING_CHECK_MISSION
ARMING_CHECK_RANGEFINDER
ARMING_CHECK_CAMERA
ARMING_CHECK_AUX_AUTH
ARMING_CHECK_VISION
ARMING_CHECK_FFT
ARMING_CHECK_OSD
Static Public Attributes inherited from AP_Arming
static const struct AP_Param::GroupInfo var_info []
Protected Attributes inherited from AP_Arming
AP_Enum< Required > require
AP_Int32 checks_to_perform
AP_Float accel_error_threshold
AP_Int8 _rudder_arming
AP_Int32 _required_mission_items
AP_Int32 _arming_options
AP_Int16 magfield_error_threshold
bool armed
uint32_t last_accel_pass_ms
uint32_t last_gyro_pass_ms
Detailed Description
Definition at line 9 of file AP_Arming.h.
Constructor & Destructor Documentation
AP_Arming_Rover()
AP_Arming_Rover::AP_Arming_Rover () inline
Definition at line 13 of file AP_Arming.h.
Member Function Documentation
arm()
bool AP_Arming_Rover::arm (AP_Arming::Method method, bool do_arming_checks = true) override virtual
Reimplemented from AP_Arming.
Definition at line 117 of file AP_Arming.cpp.
Referenced by Rover::mavlink_motor_test_start(), and Rover::rudder_arm_disarm_check().
arm_checks()
bool AP_Arming_Rover::arm_checks (AP_Arming::Method method) override virtual
Reimplemented from AP_Arming.
Definition at line 96 of file AP_Arming.cpp.
CLASS_NO_COPY()
AP_Arming_Rover::CLASS_NO_COPY (AP_Arming_Rover)
disarm()
bool AP_Arming_Rover::disarm (AP_Arming::Method method, bool do_disarm_checks = true) override virtual
Reimplemented from AP_Arming.
Definition at line 143 of file AP_Arming.cpp.
Referenced by Rover::crash_check(), Rover::failsafe_check(), Rover::failsafe_trigger(), Rover::fence_check(), Rover::handle_battery_failsafe(), and Rover::rudder_arm_disarm_check().
gps_checks()
bool AP_Arming_Rover::gps_checks (bool display_failure) override virtual
Reimplemented from AP_Arming.
Definition at line 35 of file AP_Arming.cpp.
mode_checks()
bool AP_Arming_Rover::mode_checks (bool report) protected
Definition at line 195 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
motor_checks()
bool AP_Arming_Rover::motor_checks (bool report) protected
Definition at line 206 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
oa_check()
bool AP_Arming_Rover::oa_check (bool report) protected
Definition at line 161 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
parameter_checks()
bool AP_Arming_Rover::parameter_checks (bool report) protected
Definition at line 178 of file AP_Arming.cpp.
Referenced by pre_arm_checks().
pre_arm_checks()
bool AP_Arming_Rover::pre_arm_checks (bool report) override virtual
Reimplemented from AP_Arming.
Definition at line 72 of file AP_Arming.cpp.
Referenced by Rover::one_second_loop().
rc_calibration_checks()
bool AP_Arming_Rover::rc_calibration_checks (const bool display_failure) override virtual
Reimplemented from AP_Arming.
Definition at line 5 of file AP_Arming.cpp.
Referenced by Rover::mavlink_motor_test_check().
update_soft_armed()
void AP_Arming_Rover::update_soft_armed ()
Definition at line 105 of file AP_Arming.cpp.
Referenced by Rover::ahrs_update(), arm(), and disarm().
The documentation for this class was generated from the following files:
Rover/AP_Arming.h
Rover/AP_Arming.cpp