APM:Rover: Mode Class Reference
Mode Class Reference abstract
#include <mode.h>
Public Types
enum class Number : uint8_t {
MANUAL = 0 , ACRO = 1 , STEERING = 3 , HOLD = 4 ,
LOITER = 5 , FOLLOW = 6 , SIMPLE = 7 , CIRCLE = 9 ,
AUTO = 10 , RTL = 11 , SMART_RTL = 12 , GUIDED = 15 ,
INITIALISING = 16
}
Public Member Functions
Mode ()
CLASS_NO_COPY (Mode)
bool enter ()
void exit ()
virtual Number mode_number () const =0
virtual const char * name4 () const =0
virtual void update ()=0
virtual bool is_autopilot_mode () const
virtual bool in_guided_mode () const
virtual bool allows_arming_from_transmitter ()
virtual bool allows_arming () const
bool allows_stick_mixing () const
virtual bool has_manual_input () const
virtual bool attitude_stabilized () const
virtual bool requires_position () const
virtual bool requires_velocity () const
virtual float wp_bearing () const
virtual float nav_bearing () const
virtual float crosstrack_error () const
virtual float get_desired_lat_accel () const
float speed_error () const
virtual float get_distance_to_destination () const
virtual bool get_desired_location (Location &destination) const WARN_IF_UNUSED
virtual bool set_desired_location (const Location &destination, Location next_destination=Location()) WARN_IF_UNUSED
virtual bool reached_destination () const
float get_speed_default (bool rtl=false) const
virtual bool set_desired_speed (float speed)
void set_reversed (bool value)
virtual void handle_tack_request ()
Protected Member Functions
virtual bool _enter ()
virtual void _exit ()
void get_pilot_desired_steering_and_throttle (float &steering_out, float &throttle_out) const
void get_pilot_desired_steering_and_speed (float &steering_out, float &speed_out) const
void get_pilot_desired_lateral (float &lateral_out) const
void get_pilot_desired_heading_and_speed (float &heading_out, float &speed_out) const
void get_pilot_desired_roll_and_pitch (float &roll_out, float &pitch_out) const
void get_pilot_desired_walking_height (float &walking_height_out) const
void navigate_to_waypoint ()
void calc_steering_from_turn_rate (float turn_rate)
void calc_steering_from_lateral_acceleration (float lat_accel, bool reversed=false)
void calc_steering_to_heading (float desired_heading_cd, float rate_max_degs=0.0f)
virtual void calc_throttle (float target_speed, bool avoidance_enabled)
bool stop_vehicle ()
float calc_speed_max (float cruise_speed, float cruise_throttle) const
float calc_speed_nudge (float target_speed, bool reversed)
void get_pilot_input (float &steering_out, float &throttle_out) const
void set_steering (float steering_value)
Protected Attributes
class AP_AHRS & ahrs
class Parameters & g
class ParametersG2 & g2
class RC_Channel *& channel_steer
class RC_Channel *& channel_throttle
class RC_Channel *& channel_lateral
class RC_Channel *& channel_roll
class RC_Channel *& channel_pitch
class RC_Channel *& channel_walking_height
class AR_AttitudeControl & attitude_control
float _distance_to_destination
bool _reached_destination
float _desired_yaw_cd
Detailed Description
Definition at line 8 of file mode.h.
Member Enumeration Documentation
Number
enum class Mode::Number : uint8_t strong
Enumerator
MANUAL
ACRO
STEERING
HOLD
LOITER
FOLLOW
SIMPLE
CIRCLE
AUTO
RTL
SMART_RTL
GUIDED
INITIALISING
Definition at line 14 of file mode.h.
Constructor & Destructor Documentation
Mode()
Mode::Mode ()
Definition at line 3 of file mode.cpp.
Member Function Documentation
_enter()
virtual bool Mode::_enter () inline protected virtual
Reimplemented in ModeAuto, ModeCircle, ModeGuided, ModeLoiter, ModeRTL, ModeSmartRTL, and ModeInitializing.
Definition at line 133 of file mode.h.
Referenced by enter().
_exit()
virtual void Mode::_exit () inline protected virtual
Reimplemented in ModeAuto, and ModeManual.
Definition at line 136 of file mode.h.
Referenced by exit().
allows_arming()
virtual bool Mode::allows_arming () const inline virtual
Reimplemented in ModeRTL, ModeSmartRTL, and ModeInitializing.
Definition at line 72 of file mode.h.
allows_arming_from_transmitter()
virtual bool Mode::allows_arming_from_transmitter () inline virtual
Definition at line 69 of file mode.h.
Referenced by Rover::rudder_arm_disarm_check().
allows_stick_mixing()
bool Mode::allows_stick_mixing () const inline
Definition at line 74 of file mode.h.
Referenced by set_steering().
attitude_stabilized()
virtual bool Mode::attitude_stabilized () const inline virtual
Reimplemented in ModeHold, ModeManual, and ModeInitializing.
Definition at line 84 of file mode.h.
calc_speed_max()
float Mode::calc_speed_max (float cruise_speed, float cruise_throttle) const protected
Definition at line 363 of file mode.cpp.
Referenced by calc_speed_nudge(), get_pilot_desired_heading_and_speed(), and get_pilot_desired_steering_and_speed().
calc_speed_nudge()
float Mode::calc_speed_nudge (float target_speed, bool reversed) protected
Definition at line 384 of file mode.cpp.
Referenced by navigate_to_waypoint(), ModeAuto::update(), and ModeGuided::update().
calc_steering_from_lateral_acceleration()
void Mode::calc_steering_from_lateral_acceleration (float lat_accel, bool reversed = false) protected
Definition at line 474 of file mode.cpp.
Referenced by ModeSteering::update().
calc_steering_from_turn_rate()
void Mode::calc_steering_from_turn_rate (float turn_rate) protected
Definition at line 461 of file mode.cpp.
Referenced by navigate_to_waypoint(), and ModeCircle::update().
calc_steering_to_heading()
void Mode::calc_steering_to_heading (float desired_heading_cd, float rate_max_degs = 0.0f) protected
Definition at line 489 of file mode.cpp.
Referenced by navigate_to_waypoint(), ModeAuto::update(), ModeGuided::update(), ModeLoiter::update(), and ModeSimple::update().
calc_throttle()
void Mode::calc_throttle (float target_speed, bool avoidance_enabled) protected virtual
Reimplemented in ModeAuto.
Definition at line 286 of file mode.cpp.
Referenced by ModeAuto::calc_throttle(), navigate_to_waypoint(), ModeAcro::update(), ModeCircle::update(), ModeGuided::update(), ModeLoiter::update(), ModeSteering::update(), and ModeSimple::update().
CLASS_NO_COPY()
Mode::CLASS_NO_COPY (Mode)
crosstrack_error()
float Mode::crosstrack_error () const virtual
Reimplemented in ModeAuto, ModeCircle, ModeGuided, and ModeLoiter.
Definition at line 230 of file mode.cpp.
Referenced by Rover::get_wp_crosstrack_error_m(), and GCS_MAVLINK_Rover::send_nav_controller_output().
enter()
bool Mode::enter ()
Definition at line 22 of file mode.cpp.
Referenced by Rover::set_mode().
exit()
void Mode::exit ()
Definition at line 16 of file mode.cpp.
Referenced by Rover::set_mode().
get_desired_lat_accel()
float Mode::get_desired_lat_accel () const virtual
Reimplemented in ModeAuto, ModeCircle, ModeGuided, and ModeSteering.
Definition at line 239 of file mode.cpp.
get_desired_location()
virtual bool Mode::get_desired_location (Location & destination) const inline virtual
Reimplemented in ModeAuto, ModeCircle, ModeGuided, ModeLoiter, ModeRTL, and ModeSmartRTL.
Definition at line 108 of file mode.h.
get_distance_to_destination()
virtual float Mode::get_distance_to_destination () const inline virtual
Reimplemented in ModeAuto, ModeCircle, ModeGuided, ModeLoiter, ModeRTL, and ModeSmartRTL.
Definition at line 104 of file mode.h.
Referenced by Rover::get_wp_distance_m(), and GCS_MAVLINK_Rover::send_nav_controller_output().
get_pilot_desired_heading_and_speed()
void Mode::get_pilot_desired_heading_and_speed (float & heading_out, float & speed_out) const protected
Definition at line 162 of file mode.cpp.
Referenced by ModeSimple::update().
get_pilot_desired_lateral()
void Mode::get_pilot_desired_lateral (float & lateral_out) const protected
Definition at line 149 of file mode.cpp.
Referenced by ModeManual::update().
get_pilot_desired_roll_and_pitch()
void Mode::get_pilot_desired_roll_and_pitch (float & roll_out, float & pitch_out) const protected
Definition at line 186 of file mode.cpp.
Referenced by ModeManual::update().
get_pilot_desired_steering_and_speed()
void Mode::get_pilot_desired_steering_and_speed (float & steering_out, float & speed_out) const protected
Definition at line 133 of file mode.cpp.
Referenced by ModeAcro::update(), and ModeSteering::update().
get_pilot_desired_steering_and_throttle()
void Mode::get_pilot_desired_steering_and_throttle (float & steering_out, float & throttle_out) const protected
Definition at line 105 of file mode.cpp.
Referenced by ModeAcro::update(), and ModeManual::update().
get_pilot_desired_walking_height()
void Mode::get_pilot_desired_walking_height (float & walking_height_out) const protected
Definition at line 202 of file mode.cpp.
Referenced by ModeManual::update().
get_pilot_input()
void Mode::get_pilot_input (float & steering_out, float & throttle_out) const protected
Definition at line 59 of file mode.cpp.
Referenced by calc_speed_nudge(), get_pilot_desired_steering_and_speed(), and get_pilot_desired_steering_and_throttle().
get_speed_default()
float Mode::get_speed_default (bool rtl = false) const
Definition at line 262 of file mode.cpp.
handle_tack_request()
void Mode::handle_tack_request () virtual
Reimplemented in ModeAcro.
Definition at line 278 of file mode.cpp.
has_manual_input()
virtual bool Mode::has_manual_input () const inline virtual
Reimplemented in ModeAcro, ModeManual, ModeSteering, and ModeInitializing.
Definition at line 81 of file mode.h.
in_guided_mode()
virtual bool Mode::in_guided_mode () const inline virtual
Reimplemented in ModeAuto, and ModeGuided.
Definition at line 66 of file mode.h.
is_autopilot_mode()
virtual bool Mode::is_autopilot_mode () const inline virtual
Reimplemented in ModeAuto, ModeCircle, ModeGuided, ModeLoiter, ModeRTL, and ModeSmartRTL.
Definition at line 63 of file mode.h.
Referenced by allows_arming_from_transmitter(), allows_stick_mixing(), Rover::crash_check(), crosstrack_error(), get_desired_lat_accel(), Rover::get_wp_bearing_deg(), Rover::get_wp_crosstrack_error_m(), Rover::get_wp_distance_m(), handle_tack_request(), nav_bearing(), Rover::notify_mode(), and wp_bearing().
mode_number()
virtual Number Mode::mode_number () const pure virtual
Implemented in ModeAcro, ModeAuto, ModeCircle, ModeGuided, ModeHold, ModeLoiter, ModeManual, ModeRTL, ModeSmartRTL, ModeSteering, ModeInitializing, and ModeSimple.
Referenced by Rover::get_mode(), Rover::notify_mode(), and Rover::set_mode().
name4()
virtual const char * Mode::name4 () const pure virtual
Implemented in ModeAcro, ModeAuto, ModeCircle, ModeGuided, ModeHold, ModeLoiter, ModeManual, ModeRTL, ModeSmartRTL, ModeSteering, ModeInitializing, and ModeSimple.
Referenced by Rover::notify_mode(), and Rover::set_mode().
nav_bearing()
float Mode::nav_bearing () const virtual
Reimplemented in ModeAuto, ModeCircle, ModeGuided, and ModeLoiter.
Definition at line 221 of file mode.cpp.
Referenced by GCS_MAVLINK_Rover::send_nav_controller_output().
navigate_to_waypoint()
void Mode::navigate_to_waypoint () protected
Definition at line 415 of file mode.cpp.
Referenced by ModeAuto::update(), ModeGuided::update(), ModeRTL::update(), and ModeSmartRTL::update().
reached_destination()
virtual bool Mode::reached_destination () const inline virtual
Reimplemented in ModeAuto, ModeGuided, ModeRTL, and ModeSmartRTL.
Definition at line 115 of file mode.h.
requires_position()
virtual bool Mode::requires_position () const inline virtual
Reimplemented in ModeAcro, ModeHold, ModeManual, and ModeSteering.
Definition at line 87 of file mode.h.
Referenced by enter(), and Rover::failsafe_ekf_event().
requires_velocity()
virtual bool Mode::requires_velocity () const inline virtual
Reimplemented in ModeAcro, ModeHold, ModeManual, and ModeSteering.
Definition at line 88 of file mode.h.
Referenced by enter().
set_desired_location()
bool Mode::set_desired_location (const Location & destination, Location next_destination = Location()) virtual
Reimplemented in ModeAuto, and ModeGuided.
Definition at line 248 of file mode.cpp.
Referenced by ModeAuto::set_desired_location().
set_desired_speed()
virtual bool Mode::set_desired_speed (float speed) inline virtual
Reimplemented in ModeAuto, ModeGuided, ModeRTL, ModeSmartRTL, and ModeCircle.
Definition at line 122 of file mode.h.
set_reversed()
void Mode::set_reversed (bool value)
Definition at line 272 of file mode.cpp.
Referenced by ModeAuto::do_set_reverse(), and enter().
set_steering()
void Mode::set_steering (float steering_value) protected
Definition at line 500 of file mode.cpp.
Referenced by calc_steering_from_lateral_acceleration(), calc_steering_from_turn_rate(), calc_steering_to_heading(), ModeAcro::update(), ModeGuided::update(), and ModeSteering::update().
speed_error()
float Mode::speed_error () const inline
Definition at line 97 of file mode.h.
Referenced by GCS_MAVLINK_Rover::send_nav_controller_output().
stop_vehicle()
bool Mode::stop_vehicle () protected
Definition at line 330 of file mode.cpp.
Referenced by ModeAuto::calc_throttle(), ModeAuto::update(), ModeCircle::update(), ModeGuided::update(), ModeRTL::update(), and ModeSmartRTL::update().
update()
virtual void Mode::update () pure virtual
Implemented in ModeAcro, ModeAuto, ModeCircle, ModeGuided, ModeHold, ModeLoiter, ModeManual, ModeRTL, ModeSmartRTL, ModeSteering, ModeInitializing, and ModeSimple.
Referenced by Rover::update_current_mode().
wp_bearing()
float Mode::wp_bearing () const virtual
Reimplemented in ModeAuto, ModeCircle, ModeGuided, and ModeLoiter.
Definition at line 212 of file mode.cpp.
Referenced by Rover::get_wp_bearing_deg(), and GCS_MAVLINK_Rover::send_nav_controller_output().
Member Data Documentation
_desired_yaw_cd
float Mode::_desired_yaw_cd protected
Definition at line 213 of file mode.h.
Referenced by ModeLoiter::_enter(), ModeAuto::do_nav_set_yaw_speed(), ModeLoiter::nav_bearing(), ModeGuided::set_desired_heading_and_speed(), ModeGuided::set_desired_heading_delta_and_speed(), ModeAuto::update(), ModeGuided::update(), ModeLoiter::update(), and ModeLoiter::wp_bearing().
_distance_to_destination
float Mode::_distance_to_destination protected
Definition at line 211 of file mode.h.
Referenced by ModeAuto::get_distance_to_destination(), ModeCircle::get_distance_to_destination(), ModeGuided::get_distance_to_destination(), ModeLoiter::get_distance_to_destination(), ModeRTL::get_distance_to_destination(), ModeSmartRTL::get_distance_to_destination(), navigate_to_waypoint(), set_desired_location(), ModeCircle::update(), ModeGuided::update(), ModeLoiter::update(), and ModeRTL::update().
_reached_destination
bool Mode::_reached_destination protected
Definition at line 212 of file mode.h.
Referenced by set_desired_location(), and ModeSmartRTL::update().
ahrs
class AP_AHRS& Mode::ahrs protected
Definition at line 199 of file mode.h.
Referenced by ModeLoiter::_enter(), ModeRTL::_enter(), ModeSmartRTL::_enter(), calc_throttle(), ModeAuto::do_nav_set_yaw_speed(), ModeSimple::init_heading(), ModeGuided::set_desired_heading_delta_and_speed(), ModeAuto::update(), and ModeLoiter::update().
attitude_control
class AR_AttitudeControl& Mode::attitude_control protected
Definition at line 208 of file mode.h.
Referenced by ModeLoiter::_enter(), calc_steering_from_lateral_acceleration(), calc_steering_from_turn_rate(), calc_steering_to_heading(), calc_throttle(), navigate_to_waypoint(), stop_vehicle(), ModeAcro::update(), ModeGuided::update(), ModeLoiter::update(), and ModeSteering::update().
channel_lateral
class RC_Channel*& Mode::channel_lateral protected
Definition at line 204 of file mode.h.
channel_pitch
class RC_Channel*& Mode::channel_pitch protected
Definition at line 206 of file mode.h.
Referenced by get_pilot_desired_roll_and_pitch().
channel_roll
class RC_Channel*& Mode::channel_roll protected
Definition at line 205 of file mode.h.
Referenced by get_pilot_desired_roll_and_pitch().
channel_steer
class RC_Channel*& Mode::channel_steer protected
Definition at line 202 of file mode.h.
Referenced by set_steering().
channel_throttle
class RC_Channel*& Mode::channel_throttle protected
Definition at line 203 of file mode.h.
channel_walking_height
class RC_Channel*& Mode::channel_walking_height protected
Definition at line 207 of file mode.h.
Referenced by get_pilot_desired_walking_height().
g
class Parameters& Mode::g protected
Definition at line 200 of file mode.h.
Referenced by calc_speed_nudge(), calc_throttle(), ModeAuto::check_trigger(), get_pilot_desired_heading_and_speed(), get_pilot_desired_steering_and_speed(), get_pilot_desired_steering_and_throttle(), and stop_vehicle().
g2
class ParametersG2& Mode::g2 protected
Definition at line 201 of file mode.h.
Referenced by ModeAuto::_enter(), ModeCircle::_enter(), ModeGuided::_enter(), ModeLoiter::_enter(), ModeRTL::_enter(), ModeSmartRTL::_enter(), ModeManual::_exit(), calc_speed_max(), calc_steering_from_lateral_acceleration(), calc_steering_from_turn_rate(), calc_steering_to_heading(), calc_throttle(), ModeCircle::check_config_speed(), crosstrack_error(), ModeAuto::crosstrack_error(), ModeGuided::crosstrack_error(), ModeAuto::do_circle(), ModeAuto::do_nav_set_yaw_speed(), ModeAuto::exit_mission(), get_desired_lat_accel(), ModeAuto::get_desired_lat_accel(), ModeCircle::get_desired_lat_accel(), ModeGuided::get_desired_lat_accel(), ModeAuto::get_desired_location(), ModeGuided::get_desired_location(), ModeRTL::get_desired_location(), ModeSmartRTL::get_desired_location(), get_pilot_desired_steering_and_speed(), get_pilot_desired_steering_and_throttle(), get_speed_default(), nav_bearing(), ModeAuto::nav_bearing(), ModeCircle::nav_bearing(), ModeGuided::nav_bearing(), navigate_to_waypoint(), ModeAuto::reached_destination(), ModeGuided::reached_destination(), ModeRTL::reached_destination(), ModeAcro::requires_velocity(), ModeSmartRTL::save_position(), ModeGuided::set_desired_location(), set_desired_location(), ModeAuto::set_desired_speed(), ModeGuided::set_desired_speed(), ModeRTL::set_desired_speed(), ModeSmartRTL::set_desired_speed(), ModeCircle::set_desired_speed(), set_reversed(), set_steering(), stop_vehicle(), ModeAcro::update(), ModeAuto::update(), ModeCircle::update(), ModeGuided::update(), ModeHold::update(), ModeLoiter::update(), ModeManual::update(), ModeRTL::update(), ModeSmartRTL::update(), ModeSteering::update(), ModeSimple::update(), ModeAuto::verify_circle(), wp_bearing(), ModeAuto::wp_bearing(), and ModeGuided::wp_bearing().
The documentation for this class was generated from the following files:
Rover/mode.h
Rover/mode.cpp