APM:Rover: Sailboat Class Reference
Sailboat Class Reference
#include <sailboat.h>
Public Types
enum class UseMotor { USE_MOTOR_NEVER = 0 , USE_MOTOR_ASSIST = 1 , USE_MOTOR_ALWAYS = 2 }
Public Member Functions
Sailboat ()
bool sail_enabled () const
bool tack_enabled () const
void init ()
void init_rc_in ()
void get_throttle_and_set_mainsail (float desired_speed, float &throttle_out)
float get_VMG () const
void handle_tack_request_acro ()
float get_tack_heading_rad ()
void handle_tack_request_auto ()
void clear_tack ()
bool tacking () const
bool use_indirect_route (float desired_heading_cd) const
float calc_heading (float desired_heading_cd)
void set_motor_state (UseMotor state, bool report_failure=true)
float get_loiter_radius () const
void set_pilot_desired_mainsail ()
decode pilot mainsail input in manual modes and update the various sail actuator values for different sail types ready for SRV_Channel output.
void set_auto_mainsail (float desired_speed)
Set mainsail in auto modes.
void relax_sails ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
bool motor_assist_tack () const
bool motor_assist_low_wind () const
Private Attributes
AP_Int8 enable
AP_Float sail_angle_min
AP_Float sail_angle_max
AP_Float sail_angle_ideal
AP_Float sail_heel_angle_max
AP_Float sail_no_go
AP_Float sail_windspeed_min
AP_Float xtrack_max
AP_Float loit_radius
RC_Channel * channel_mainsail
bool currently_tacking
float tack_heading_rad
uint32_t tack_request_ms
uint32_t auto_tack_start_ms
uint32_t tack_clear_ms
bool tack_assist
UseMotor motor_state
Detailed Description
Definition at line 19 of file sailboat.h.
Member Enumeration Documentation
UseMotor
enum class Sailboat::UseMotor strong
Enumerator
USE_MOTOR_NEVER
USE_MOTOR_ASSIST
USE_MOTOR_ALWAYS
Definition at line 66 of file sailboat.h.
Constructor & Destructor Documentation
Sailboat()
Sailboat::Sailboat ()
Definition at line 112 of file sailboat.cpp.
Member Function Documentation
calc_heading()
float Sailboat::calc_heading (float desired_heading_cd)
Definition at line 398 of file sailboat.cpp.
Referenced by Mode::navigate_to_waypoint(), and ModeLoiter::update().
clear_tack()
void Sailboat::clear_tack ()
Definition at line 361 of file sailboat.cpp.
Referenced by calc_heading(), and get_tack_heading_rad().
get_loiter_radius()
float Sailboat::get_loiter_radius () const inline
Definition at line 80 of file sailboat.h.
Referenced by ModeLoiter::update().
get_tack_heading_rad()
float Sailboat::get_tack_heading_rad ()
Definition at line 339 of file sailboat.cpp.
get_throttle_and_set_mainsail()
void Sailboat::get_throttle_and_set_mainsail (float desired_speed, float & throttle_out)
Definition at line 276 of file sailboat.cpp.
get_VMG()
float Sailboat::get_VMG () const
Definition at line 309 of file sailboat.cpp.
handle_tack_request_acro()
void Sailboat::handle_tack_request_acro ()
Definition at line 326 of file sailboat.cpp.
handle_tack_request_auto()
void Sailboat::handle_tack_request_auto ()
Definition at line 350 of file sailboat.cpp.
init()
void Sailboat::init ()
Definition at line 139 of file sailboat.cpp.
Referenced by Rover::init_ardupilot().
init_rc_in()
void Sailboat::init_rc_in ()
Definition at line 160 of file sailboat.cpp.
Referenced by Rover::set_control_channels().
motor_assist_low_wind()
bool Sailboat::motor_assist_low_wind () const private
Definition at line 543 of file sailboat.cpp.
Referenced by get_throttle_and_set_mainsail(), and tack_enabled().
motor_assist_tack()
bool Sailboat::motor_assist_tack () const private
Definition at line 531 of file sailboat.cpp.
Referenced by get_throttle_and_set_mainsail().
relax_sails()
void Sailboat::relax_sails ()
Definition at line 268 of file sailboat.cpp.
Referenced by get_throttle_and_set_mainsail(), set_pilot_desired_mainsail(), Mode::stop_vehicle(), and ModeHold::update().
sail_enabled()
bool Sailboat::sail_enabled () const inline
Definition at line 27 of file sailboat.h.
Referenced by get_throttle_and_set_mainsail(), init(), and tack_enabled().
set_auto_mainsail()
void Sailboat::set_auto_mainsail (float desired_speed)
Set mainsail in auto modes.
Parameters
[in] desired_speed desired speed (in m/s) only used to detect desired direction
Definition at line 191 of file sailboat.cpp.
Referenced by get_throttle_and_set_mainsail().
set_motor_state()
void Sailboat::set_motor_state (UseMotor state, bool report_failure = true)
Definition at line 512 of file sailboat.cpp.
Referenced by init().
set_pilot_desired_mainsail()
void Sailboat::set_pilot_desired_mainsail ()
decode pilot mainsail input in manual modes and update the various sail actuator values for different sail types ready for SRV_Channel output.
Definition at line 177 of file sailboat.cpp.
Referenced by ModeManual::update().
tack_enabled()
bool Sailboat::tack_enabled () const
Definition at line 118 of file sailboat.cpp.
Referenced by calc_heading(), Mode::calc_throttle(), handle_tack_request_acro(), handle_tack_request_auto(), init(), Mode::navigate_to_waypoint(), tacking(), and use_indirect_route().
tacking()
bool Sailboat::tacking () const
Definition at line 370 of file sailboat.cpp.
Referenced by Mode::navigate_to_waypoint(), and ModeLoiter::update().
use_indirect_route()
bool Sailboat::use_indirect_route (float desired_heading_cd) const
Definition at line 377 of file sailboat.cpp.
Referenced by Mode::navigate_to_waypoint(), and ModeLoiter::update().
Member Data Documentation
auto_tack_start_ms
uint32_t Sailboat::auto_tack_start_ms private
Definition at line 115 of file sailboat.h.
Referenced by calc_heading().
channel_mainsail
RC_Channel* Sailboat::channel_mainsail private
Definition at line 111 of file sailboat.h.
Referenced by init_rc_in(), and set_pilot_desired_mainsail().
currently_tacking
bool Sailboat::currently_tacking private
Definition at line 112 of file sailboat.h.
Referenced by calc_heading(), clear_tack(), handle_tack_request_acro(), handle_tack_request_auto(), tacking(), and use_indirect_route().
enable
AP_Int8 Sailboat::enable private
Definition at line 101 of file sailboat.h.
Referenced by sail_enabled().
loit_radius
AP_Float Sailboat::loit_radius private
Definition at line 109 of file sailboat.h.
Referenced by get_loiter_radius().
motor_state
UseMotor Sailboat::motor_state private
Definition at line 118 of file sailboat.h.
Referenced by calc_heading(), get_throttle_and_set_mainsail(), init(), motor_assist_low_wind(), motor_assist_tack(), set_motor_state(), and tack_enabled().
sail_angle_ideal
AP_Float Sailboat::sail_angle_ideal private
Definition at line 104 of file sailboat.h.
Referenced by set_auto_mainsail().
sail_angle_max
AP_Float Sailboat::sail_angle_max private
Definition at line 103 of file sailboat.h.
Referenced by set_auto_mainsail().
sail_angle_min
AP_Float Sailboat::sail_angle_min private
Definition at line 102 of file sailboat.h.
Referenced by set_auto_mainsail().
sail_heel_angle_max
AP_Float Sailboat::sail_heel_angle_max private
Definition at line 105 of file sailboat.h.
Referenced by set_auto_mainsail().
sail_no_go
AP_Float Sailboat::sail_no_go private
Definition at line 106 of file sailboat.h.
Referenced by calc_heading(), and use_indirect_route().
sail_windspeed_min
AP_Float Sailboat::sail_windspeed_min private
Definition at line 107 of file sailboat.h.
Referenced by motor_assist_low_wind().
tack_assist
bool Sailboat::tack_assist private
Definition at line 117 of file sailboat.h.
Referenced by calc_heading(), clear_tack(), and motor_assist_tack().
tack_clear_ms
uint32_t Sailboat::tack_clear_ms private
Definition at line 116 of file sailboat.h.
Referenced by calc_heading(), and clear_tack().
tack_heading_rad
float Sailboat::tack_heading_rad private
Definition at line 113 of file sailboat.h.
Referenced by calc_heading(), get_tack_heading_rad(), and handle_tack_request_acro().
tack_request_ms
uint32_t Sailboat::tack_request_ms private
Definition at line 114 of file sailboat.h.
Referenced by calc_heading(), clear_tack(), get_tack_heading_rad(), handle_tack_request_acro(), and handle_tack_request_auto().
var_info
const AP_Param::GroupInfo Sailboat::var_info static
Definition at line 23 of file sailboat.h.
Referenced by Sailboat().
xtrack_max
AP_Float Sailboat::xtrack_max private
Definition at line 108 of file sailboat.h.
Referenced by calc_heading().
The documentation for this class was generated from the following files:
Rover/sailboat.h
Rover/sailboat.cpp