APM:Rover: ModeAuto Class Reference
ModeAuto Class Reference
#include <mode.h>
Public Types
enum Mis_Done_Behave { MIS_DONE_BEHAVE_HOLD = 0 , MIS_DONE_BEHAVE_LOITER = 1 , MIS_DONE_BEHAVE_ACRO = 2 , MIS_DONE_BEHAVE_MANUAL = 3 }
Public Types inherited from Mode
enum class Number : uint8_t {
MANUAL = 0 , ACRO = 1 , STEERING = 3 , HOLD = 4 ,
LOITER = 5 , FOLLOW = 6 , SIMPLE = 7 , CIRCLE = 9 ,
AUTO = 10 , RTL = 11 , SMART_RTL = 12 , GUIDED = 15 ,
INITIALISING = 16
}
Public Member Functions
Number mode_number () const override
const char * name4 () const override
void update () override
void calc_throttle (float target_speed, bool avoidance_enabled) override
bool is_autopilot_mode () const override
bool in_guided_mode () const override
float wp_bearing () const override
float nav_bearing () const override
float crosstrack_error () const override
float get_desired_lat_accel () const override
float get_distance_to_destination () const override
bool get_desired_location (Location &destination) const override WARN_IF_UNUSED
bool set_desired_location (const Location &destination, Location next_destination=Location()) override WARN_IF_UNUSED
bool reached_destination () const override
bool set_desired_speed (float speed) override
void start_RTL ()
bool nav_script_time (uint16_t &id, uint8_t &cmd, float &arg1, float &arg2, int16_t &arg3, int16_t &arg4)
void nav_script_time_done (uint16_t id)
Public Member Functions inherited from Mode
Mode ()
CLASS_NO_COPY (Mode)
bool enter ()
void exit ()
virtual bool allows_arming_from_transmitter ()
virtual bool allows_arming () const
bool allows_stick_mixing () const
virtual bool has_manual_input () const
virtual bool attitude_stabilized () const
virtual bool requires_position () const
virtual bool requires_velocity () const
float speed_error () const
float get_speed_default (bool rtl=false) const
void set_reversed (bool value)
virtual void handle_tack_request ()
Public Attributes
AP_Mission mission
Protected Types
enum SubMode : uint8_t {
WP , HeadingAndSpeed , RTL , Loiter ,
Guided , Stop , NavScriptTime , Circle
}
Protected Member Functions
bool _enter () override
void _exit () override
Protected Member Functions inherited from Mode
void get_pilot_desired_steering_and_throttle (float &steering_out, float &throttle_out) const
void get_pilot_desired_steering_and_speed (float &steering_out, float &speed_out) const
void get_pilot_desired_lateral (float &lateral_out) const
void get_pilot_desired_heading_and_speed (float &heading_out, float &speed_out) const
void get_pilot_desired_roll_and_pitch (float &roll_out, float &pitch_out) const
void get_pilot_desired_walking_height (float &walking_height_out) const
void navigate_to_waypoint ()
void calc_steering_from_turn_rate (float turn_rate)
void calc_steering_from_lateral_acceleration (float lat_accel, bool reversed=false)
void calc_steering_to_heading (float desired_heading_cd, float rate_max_degs=0.0f)
bool stop_vehicle ()
float calc_speed_max (float cruise_speed, float cruise_throttle) const
float calc_speed_nudge (float target_speed, bool reversed)
void get_pilot_input (float &steering_out, float &throttle_out) const
void set_steering (float steering_value)
Protected Attributes
enum ModeAuto::SubMode _submode
Protected Attributes inherited from Mode
class AP_AHRS & ahrs
class Parameters & g
class ParametersG2 & g2
class RC_Channel *& channel_steer
class RC_Channel *& channel_throttle
class RC_Channel *& channel_lateral
class RC_Channel *& channel_roll
class RC_Channel *& channel_pitch
class RC_Channel *& channel_walking_height
class AR_AttitudeControl & attitude_control
float _distance_to_destination
bool _reached_destination
float _desired_yaw_cd
Private Member Functions
bool check_trigger (void)
bool start_loiter ()
void start_guided (const Location &target_loc)
void start_stop ()
void send_guided_position_target ()
bool start_command (const AP_Mission::Mission_Command &cmd)
void exit_mission ()
bool verify_command_callback (const AP_Mission::Mission_Command &cmd)
bool verify_command (const AP_Mission::Mission_Command &cmd)
void do_RTL (void)
bool do_nav_wp (const AP_Mission::Mission_Command &cmd, bool always_stop_at_destination)
void do_nav_guided_enable (const AP_Mission::Mission_Command &cmd)
void do_nav_set_yaw_speed (const AP_Mission::Mission_Command &cmd)
void do_nav_delay (const AP_Mission::Mission_Command &cmd)
bool verify_nav_delay (const AP_Mission::Mission_Command &cmd)
bool verify_nav_wp (const AP_Mission::Mission_Command &cmd)
bool verify_RTL () const
bool verify_loiter_unlimited (const AP_Mission::Mission_Command &cmd)
bool verify_loiter_time (const AP_Mission::Mission_Command &cmd)
bool verify_nav_guided_enable (const AP_Mission::Mission_Command &cmd)
bool verify_nav_set_yaw_speed ()
bool do_circle (const AP_Mission::Mission_Command &cmd)
bool verify_circle (const AP_Mission::Mission_Command &cmd)
void do_wait_delay (const AP_Mission::Mission_Command &cmd)
void do_within_distance (const AP_Mission::Mission_Command &cmd)
bool verify_wait_delay ()
bool verify_within_distance ()
void do_change_speed (const AP_Mission::Mission_Command &cmd)
void do_set_home (const AP_Mission::Mission_Command &cmd)
void do_set_reverse (const AP_Mission::Mission_Command &cmd)
void do_guided_limits (const AP_Mission::Mission_Command &cmd)
Private Attributes
bool waiting_to_start
bool auto_triggered
float _desired_speed
bool _reached_heading
uint16_t loiter_duration
uint32_t loiter_start_time
bool previously_reached_wp
struct {
Location loc
bool valid
uint32_t last_sent_ms
} guided_target
int32_t condition_value
int32_t condition_start
uint32_t nav_delay_time_max_ms
uint32_t nav_delay_time_start_ms
AP_Mission_ChangeDetector mis_change_detector
Detailed Description
Definition at line 239 of file mode.h.
Member Enumeration Documentation
Mis_Done_Behave
enum ModeAuto::Mis_Done_Behave
Enumerator
MIS_DONE_BEHAVE_HOLD
MIS_DONE_BEHAVE_LOITER
MIS_DONE_BEHAVE_ACRO
MIS_DONE_BEHAVE_MANUAL
Definition at line 285 of file mode.h.
SubMode
enum ModeAuto::SubMode : uint8_t protected
Enumerator
WP
HeadingAndSpeed
RTL
Loiter
Guided
Stop
NavScriptTime
Circle
Definition at line 297 of file mode.h.
Member Function Documentation
_enter()
bool ModeAuto::_enter () override protected virtual
Reimplemented from Mode.
Definition at line 5 of file mode_auto.cpp.
_exit()
void ModeAuto::_exit () override protected virtual
Reimplemented from Mode.
Definition at line 37 of file mode_auto.cpp.
calc_throttle()
void ModeAuto::calc_throttle (float target_speed, bool avoidance_enabled) override virtual
Reimplemented from Mode.
Definition at line 149 of file mode_auto.cpp.
Referenced by update().
check_trigger()
bool ModeAuto::check_trigger (void) private
Definition at line 410 of file mode_auto.cpp.
Referenced by calc_throttle().
crosstrack_error()
float ModeAuto::crosstrack_error () const override virtual
Reimplemented from Mode.
Definition at line 208 of file mode_auto.cpp.
do_change_speed()
void ModeAuto::do_change_speed (const AP_Mission::Mission_Command & cmd) private
Definition at line 995 of file mode_auto.cpp.
Referenced by start_command().
do_circle()
bool ModeAuto::do_circle (const AP_Mission::Mission_Command & cmd) private
Definition at line 924 of file mode_auto.cpp.
Referenced by start_command().
do_guided_limits()
void ModeAuto::do_guided_limits (const AP_Mission::Mission_Command & cmd) private
Definition at line 1022 of file mode_auto.cpp.
Referenced by start_command().
do_nav_delay()
void ModeAuto::do_nav_delay (const AP_Mission::Mission_Command & cmd) private
Definition at line 769 of file mode_auto.cpp.
Referenced by start_command().
do_nav_guided_enable()
void ModeAuto::do_nav_guided_enable (const AP_Mission::Mission_Command & cmd) private
Definition at line 797 of file mode_auto.cpp.
Referenced by start_command().
do_nav_set_yaw_speed()
void ModeAuto::do_nav_set_yaw_speed (const AP_Mission::Mission_Command & cmd) private
Definition at line 805 of file mode_auto.cpp.
Referenced by start_command().
do_nav_wp()
bool ModeAuto::do_nav_wp (const AP_Mission::Mission_Command & cmd, bool always_stop_at_destination) private
Definition at line 733 of file mode_auto.cpp.
Referenced by start_command().
do_RTL()
void ModeAuto::do_RTL (void) private
Definition at line 727 of file mode_auto.cpp.
Referenced by start_command().
do_set_home()
void ModeAuto::do_set_home (const AP_Mission::Mission_Command & cmd) private
Definition at line 1003 of file mode_auto.cpp.
Referenced by start_command().
do_set_reverse()
void ModeAuto::do_set_reverse (const AP_Mission::Mission_Command & cmd) private
Definition at line 1016 of file mode_auto.cpp.
Referenced by start_command().
do_wait_delay()
void ModeAuto::do_wait_delay (const AP_Mission::Mission_Command & cmd) private
Definition at line 957 of file mode_auto.cpp.
Referenced by start_command().
do_within_distance()
void ModeAuto::do_within_distance (const AP_Mission::Mission_Command & cmd) private
Definition at line 963 of file mode_auto.cpp.
Referenced by start_command().
exit_mission()
void ModeAuto::exit_mission () private
Definition at line 622 of file mode_auto.cpp.
get_desired_lat_accel()
float ModeAuto::get_desired_lat_accel () const override virtual
Reimplemented from Mode.
Definition at line 232 of file mode_auto.cpp.
get_desired_location()
bool ModeAuto::get_desired_location (Location & destination) const override virtual
Reimplemented from Mode.
Definition at line 281 of file mode_auto.cpp.
get_distance_to_destination()
float ModeAuto::get_distance_to_destination () const override virtual
Reimplemented from Mode.
Definition at line 256 of file mode_auto.cpp.
Referenced by verify_within_distance().
in_guided_mode()
bool ModeAuto::in_guided_mode () const inline override virtual
Reimplemented from Mode.
Definition at line 254 of file mode.h.
is_autopilot_mode()
bool ModeAuto::is_autopilot_mode () const inline override virtual
Reimplemented from Mode.
Definition at line 251 of file mode.h.
mode_number()
Number ModeAuto::mode_number () const inline override virtual
Implements Mode.
Definition at line 243 of file mode.h.
name4()
const char * ModeAuto::name4 () const inline override virtual
Implements Mode.
Definition at line 244 of file mode.h.
nav_bearing()
float ModeAuto::nav_bearing () const override virtual
Reimplemented from Mode.
Definition at line 184 of file mode_auto.cpp.
nav_script_time()
bool ModeAuto::nav_script_time (uint16_t & id, uint8_t & cmd, float & arg1, float & arg2, int16_t & arg3, int16_t & arg4)
Definition at line 383 of file mode_auto.cpp.
nav_script_time_done()
void ModeAuto::nav_script_time_done (uint16_t id)
Definition at line 400 of file mode_auto.cpp.
reached_destination()
bool ModeAuto::reached_destination () const override virtual
Reimplemented from Mode.
Definition at line 323 of file mode_auto.cpp.
Referenced by verify_nav_wp(), and verify_RTL().
send_guided_position_target()
void ModeAuto::send_guided_position_target () private
Definition at line 488 of file mode_auto.cpp.
Referenced by update().
set_desired_location()
bool ModeAuto::set_desired_location (const Location & destination, Location next_destination = Location()) override virtual
Reimplemented from Mode.
Definition at line 310 of file mode_auto.cpp.
Referenced by do_nav_wp().
set_desired_speed()
bool ModeAuto::set_desired_speed (float speed) override virtual
Reimplemented from Mode.
Definition at line 352 of file mode_auto.cpp.
Referenced by do_change_speed().
start_command()
bool ModeAuto::start_command (const AP_Mission::Mission_Command & cmd) private
Definition at line 513 of file mode_auto.cpp.
start_guided()
void ModeAuto::start_guided (const Location & target_loc) private
Definition at line 462 of file mode_auto.cpp.
Referenced by do_nav_guided_enable().
start_loiter()
bool ModeAuto::start_loiter () private
Definition at line 452 of file mode_auto.cpp.
Referenced by _enter(), do_nav_delay(), exit_mission(), and update().
start_RTL()
void ModeAuto::start_RTL ()
Definition at line 375 of file mode_auto.cpp.
Referenced by do_RTL().
start_stop()
void ModeAuto::start_stop () private
Definition at line 482 of file mode_auto.cpp.
Referenced by _enter(), do_nav_delay(), exit_mission(), and update().
update()
void ModeAuto::update () override virtual
Implements Mode.
Definition at line 45 of file mode_auto.cpp.
verify_circle()
bool ModeAuto::verify_circle (const AP_Mission::Mission_Command & cmd) private
Definition at line 946 of file mode_auto.cpp.
Referenced by verify_command().
verify_command()
bool ModeAuto::verify_command (const AP_Mission::Mission_Command & cmd) private
Definition at line 667 of file mode_auto.cpp.
Referenced by verify_command_callback().
verify_command_callback()
bool ModeAuto::verify_command_callback (const AP_Mission::Mission_Command & cmd) private
Definition at line 646 of file mode_auto.cpp.
verify_loiter_time()
bool ModeAuto::verify_loiter_time (const AP_Mission::Mission_Command & cmd) private
Definition at line 885 of file mode_auto.cpp.
Referenced by verify_command().
verify_loiter_unlimited()
bool ModeAuto::verify_loiter_unlimited (const AP_Mission::Mission_Command & cmd) private
Definition at line 878 of file mode_auto.cpp.
Referenced by verify_command().
verify_nav_delay()
bool ModeAuto::verify_nav_delay (const AP_Mission::Mission_Command & cmd) private
Definition at line 863 of file mode_auto.cpp.
Referenced by verify_command().
verify_nav_guided_enable()
bool ModeAuto::verify_nav_guided_enable (const AP_Mission::Mission_Command & cmd) private
Definition at line 895 of file mode_auto.cpp.
Referenced by verify_command().
verify_nav_set_yaw_speed()
bool ModeAuto::verify_nav_set_yaw_speed () private
Definition at line 915 of file mode_auto.cpp.
Referenced by verify_command().
verify_nav_wp()
bool ModeAuto::verify_nav_wp (const AP_Mission::Mission_Command & cmd) private
Definition at line 829 of file mode_auto.cpp.
Referenced by verify_command(), verify_loiter_time(), and verify_loiter_unlimited().
verify_RTL()
bool ModeAuto::verify_RTL () const private
Definition at line 873 of file mode_auto.cpp.
Referenced by verify_command().
verify_wait_delay()
bool ModeAuto::verify_wait_delay () private
Definition at line 972 of file mode_auto.cpp.
Referenced by verify_command().
verify_within_distance()
bool ModeAuto::verify_within_distance () private
Definition at line 981 of file mode_auto.cpp.
Referenced by verify_command().
wp_bearing()
float ModeAuto::wp_bearing () const override virtual
Reimplemented from Mode.
Definition at line 160 of file mode_auto.cpp.
Member Data Documentation
_desired_speed
float ModeAuto::_desired_speed private
Definition at line 352 of file mode.h.
Referenced by do_nav_set_yaw_speed(), set_desired_speed(), and update().
_reached_heading
bool ModeAuto::_reached_heading private
Definition at line 353 of file mode.h.
Referenced by do_nav_set_yaw_speed(), update(), and verify_nav_set_yaw_speed().
_submode
enum ModeAuto::SubMode ModeAuto::_submode protected
Referenced by crosstrack_error(), do_circle(), do_nav_set_yaw_speed(), get_desired_lat_accel(), get_desired_location(), get_distance_to_destination(), in_guided_mode(), nav_bearing(), nav_script_time(), nav_script_time_done(), reached_destination(), set_desired_location(), set_desired_speed(), start_guided(), start_loiter(), start_RTL(), start_stop(), update(), verify_nav_guided_enable(), verify_nav_set_yaw_speed(), and wp_bearing().
auto_triggered
bool ModeAuto::auto_triggered private
Definition at line 349 of file mode.h.
Referenced by _enter(), and check_trigger().
condition_start
int32_t ModeAuto::condition_start private
Definition at line 373 of file mode.h.
Referenced by do_wait_delay(), and verify_wait_delay().
condition_value
int32_t ModeAuto::condition_value private
Definition at line 370 of file mode.h.
Referenced by do_wait_delay(), do_within_distance(), verify_wait_delay(), and verify_within_distance().
[struct]
struct { ... } ModeAuto::guided_target
Referenced by send_guided_position_target(), start_guided(), and verify_nav_guided_enable().
last_sent_ms
uint32_t ModeAuto::last_sent_ms
Definition at line 364 of file mode.h.
loc
Location ModeAuto::loc
Definition at line 362 of file mode.h.
Referenced by start_guided(), and update().
loiter_duration
uint16_t ModeAuto::loiter_duration private
Definition at line 356 of file mode.h.
Referenced by do_nav_wp(), and verify_nav_wp().
loiter_start_time
uint32_t ModeAuto::loiter_start_time private
Definition at line 357 of file mode.h.
Referenced by do_nav_wp(), and verify_nav_wp().
mis_change_detector
AP_Mission_ChangeDetector ModeAuto::mis_change_detector private
Definition at line 395 of file mode.h.
Referenced by update().
mission
AP_Mission ModeAuto::mission
Initial value:
{
        FUNCTOR_BIND_MEMBER(&ModeAuto::start_command, bool, const AP_Mission::Mission_Command&),
        FUNCTOR_BIND_MEMBER(&ModeAuto::verify_command_callback, bool, const AP_Mission::Mission_Command&),
        FUNCTOR_BIND_MEMBER(&ModeAuto::exit_mission, void)}
Definition at line 280 of file mode.h.
Referenced by _enter(), _exit(), do_nav_wp(), Rover::set_home(), start_command(), Rover::startup_ground(), and update().
nav_delay_time_max_ms
uint32_t ModeAuto::nav_delay_time_max_ms private
Definition at line 376 of file mode.h.
Referenced by do_nav_delay(), and verify_nav_delay().
nav_delay_time_start_ms
uint32_t ModeAuto::nav_delay_time_start_ms private
Definition at line 377 of file mode.h.
Referenced by do_nav_delay(), and verify_nav_delay().
previously_reached_wp
bool ModeAuto::previously_reached_wp private
Definition at line 358 of file mode.h.
Referenced by do_nav_wp(), and verify_nav_wp().
valid
bool ModeAuto::valid
Definition at line 363 of file mode.h.
waiting_to_start
bool ModeAuto::waiting_to_start private
Definition at line 348 of file mode.h.
Referenced by _enter(), and update().
The documentation for this class was generated from the following files:
Rover/mode.h
Rover/mode_auto.cpp