APM:Rover: RC_Channel_Rover Class Reference
RC_Channel_Rover Class Reference
#include <RC_Channel.h>
Protected Member Functions
void init_aux_function (AUX_FUNC ch_option, AuxSwitchPos) override
bool do_aux_function (AUX_FUNC ch_option, AuxSwitchPos) override
void mode_switch_changed (modeswitch_pos_t new_pos) override
Protected Member Functions inherited from RC_Channel
void do_aux_function_armdisarm (const AuxSwitchPos ch_flag)
void do_aux_function_avoid_adsb (const AuxSwitchPos ch_flag)
void do_aux_function_avoid_proximity (const AuxSwitchPos ch_flag)
void do_aux_function_camera_trigger (const AuxSwitchPos ch_flag)
bool do_aux_function_record_video (const AuxSwitchPos ch_flag)
bool do_aux_function_camera_zoom (const AuxSwitchPos ch_flag)
bool do_aux_function_camera_manual_focus (const AuxSwitchPos ch_flag)
bool do_aux_function_camera_auto_focus (const AuxSwitchPos ch_flag)
bool do_aux_function_camera_image_tracking (const AuxSwitchPos ch_flag)
bool do_aux_function_camera_lens (const AuxSwitchPos ch_flag)
void do_aux_function_runcam_control (const AuxSwitchPos ch_flag)
void do_aux_function_runcam_osd_control (const AuxSwitchPos ch_flag)
void do_aux_function_fence (const AuxSwitchPos ch_flag)
void do_aux_function_clear_wp (const AuxSwitchPos ch_flag)
void do_aux_function_gripper (const AuxSwitchPos ch_flag)
void do_aux_function_lost_vehicle_sound (const AuxSwitchPos ch_flag)
void do_aux_function_mission_reset (const AuxSwitchPos ch_flag)
void do_aux_function_rc_override_enable (const AuxSwitchPos ch_flag)
void do_aux_function_relay (uint8_t relay, bool val)
void do_aux_function_sprayer (const AuxSwitchPos ch_flag)
void do_aux_function_generator (const AuxSwitchPos ch_flag)
void do_aux_function_fft_notch_tune (const AuxSwitchPos ch_flag)
Private Member Functions
void do_aux_function_change_mode (Mode &mode, const AuxSwitchPos ch_flag)
void add_waypoint_for_current_loc ()
void do_aux_function_sailboat_motor_3pos (const AuxSwitchPos ch_flag)
Additional Inherited Members
Public Types inherited from RC_Channel
enum ControlType
enum AUX_FUNC
enum AuxSwitchPos
enum AuxFuncTriggerSource
Public Member Functions inherited from RC_Channel
RC_Channel (void)
void set_range (uint16_t high)
uint16_t get_range () const
void set_angle (uint16_t angle)
bool get_reverse (void) const
void set_default_dead_zone (int16_t dzone)
uint16_t get_dead_zone (void) const
int16_t get_control_mid () const
bool update (void)
int16_t pwm_to_angle_dz_trim (uint16_t dead_zone, uint16_t trim) const
float norm_input () const
float norm_input_dz () const
float norm_input_ignore_trim () const
bool in_min_dz () const
uint8_t percent_input () const
bool in_trim_dz () const
int16_t get_radio_in () const
void set_radio_in (int16_t val)
int16_t get_control_in () const
void set_control_in (int16_t val)
void clear_override ()
void set_override (const uint16_t v, const uint32_t timestamp_ms)
bool has_override () const
float stick_mixing (const float servo_in)
int16_t get_control_in_zero_dz (void) const
int16_t get_radio_min () const
int16_t get_radio_max () const
int16_t get_radio_trim () const
void set_and_save_trim ()
void set_and_save_radio_trim (int16_t val)
bool configured ()
ControlType get_type (void) const
void init_aux ()
bool read_aux ()
AuxSwitchPos get_aux_switch_pos () const
bool run_aux_function (AUX_FUNC ch_option, AuxSwitchPos pos, AuxFuncTriggerSource source)
const char * string_for_aux_function (AUX_FUNC function) const
const char * string_for_aux_pos (AuxSwitchPos pos) const
Public Attributes inherited from RC_Channel
AP_Int16 option
int8_t debounce_position
int8_t current_position
uint32_t last_edge_time_ms
Static Public Attributes inherited from RC_Channel
static const struct AP_Param::GroupInfo var_info []
static const uint16_t RC_MIN_LIMIT_PWM
static const uint16_t RC_MAX_LIMIT_PWM
static const uint16_t RC_CALIB_MIN_LIMIT_PWM
static const uint16_t RC_CALIB_MAX_LIMIT_PWM
static const uint16_t AUX_SWITCH_PWM_TRIGGER_HIGH
static const uint16_t AUX_SWITCH_PWM_TRIGGER_LOW
static const uint16_t AUX_PWM_TRIGGER_HIGH
static const uint16_t AUX_PWM_TRIGGER_LOW
Protected Types inherited from RC_Channel
typedef int8_t modeswitch_pos_t
Detailed Description
Definition at line 7 of file RC_Channel.h.
Member Function Documentation
add_waypoint_for_current_loc()
void RC_Channel_Rover::add_waypoint_for_current_loc () private
Definition at line 101 of file RC_Channel.cpp.
Referenced by do_aux_function().
do_aux_function()
bool RC_Channel_Rover::do_aux_function (AUX_FUNC ch_option, AuxSwitchPos ch_flag) override protected virtual
Reimplemented from RC_Channel.
Definition at line 133 of file RC_Channel.cpp.
do_aux_function_change_mode()
void RC_Channel_Rover::do_aux_function_change_mode (Mode & mode, const AuxSwitchPos ch_flag) private
Definition at line 84 of file RC_Channel.cpp.
Referenced by do_aux_function().
do_aux_function_sailboat_motor_3pos()
void RC_Channel_Rover::do_aux_function_sailboat_motor_3pos (const AuxSwitchPos ch_flag) private
Definition at line 118 of file RC_Channel.cpp.
Referenced by do_aux_function(), and init_aux_function().
init_aux_function()
void RC_Channel_Rover::init_aux_function (AUX_FUNC ch_option, AuxSwitchPos ch_flag) override protected virtual
Reimplemented from RC_Channel.
Definition at line 29 of file RC_Channel.cpp.
mode_switch_changed()
void RC_Channel_Rover::mode_switch_changed (modeswitch_pos_t new_pos) override protected virtual
Reimplemented from RC_Channel.
Definition at line 18 of file RC_Channel.cpp.
The documentation for this class was generated from the following files:
Rover/RC_Channel.h
Rover/RC_Channel.cpp